### ISSUE TITLE
Reorder Rows Callback?

### ISSUE THREAD

**Issue by kodeine** [wenzhixin/bootstrap-table#1002]
Does not seem to work or am i doing it wrong?

```
    $table.on('reorder-row.bs.table', function (e, name, args) {
        console.log(name, args);
    });
```

**Comment by djhvscf** [comment]
What is the problem? Provide a fiddle please

**Comment by kodeine** [comment]
The code i pasted above doesnt work. Or ik not sure how to setup its callback.

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/e3nk137y/2096/

**Comment by tedbakers** [comment]
this data attribute in the table definition is important 

data-use-row-attr-func="true"
