### ISSUE TITLE
How to add custom attributes dynamically to boostrap table

### ISSUE THREAD

**Issue by naimhiq** [wenzhixin/bootstrap-table#1003]
Hej, 

I have a bootstrap table that I generate dynamically via javascript. Does anyone know how can I add custom attributes to my <tr>s table

**Comment by djhvscf** [comment]
For example??

**Comment by naimhiq** [comment]
For example I would like to add a data attributes on the table row  and give a value for my id in the row selection and then based on that perform any action on rows i.e. delete edit

Thanks for helping out :+1:

**Comment by djhvscf** [comment]
Ok, in that case you can use the data-unique-id table option

**Comment by naimhiq** [comment]
Alright, should i set that to the bootstrap table as property or on the columns:[{}] ?

**Comment by djhvscf** [comment]
It is a table property

**Comment by naimhiq** [comment]
Thanks a lot got it :), by the way I have another question regarding to the table. Is there any example where bootstrap table have a search button as well where you are able to search instead of just autocomplete search input.

**Comment by djhvscf** [comment]
Something like this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

**Comment by naimhiq** [comment]
Yes, thank you :+1:

**Comment by djhvscf** [comment]
Great!
