### ISSUE TITLE
Support for the HTML5 `title` attribute

### ISSUE THREAD

**Issue by Goutte** [wenzhixin/bootstrap-table#1005]
To show a small descriptive text on hover, one can use the `title` attribute on a `<th>`, like so :

``` html
<th data-sortable="true" title="This column is awesome">My Header</th>
```

This attribute is lost/ignored when using `bootstrap-table`.
The `data-title` attribute overrides the contents of the `<th>` ("My Header" in the above example), which is not what I want.

How can one set the hover title ?

**Comment by djhvscf** [comment]
Ok, let me see what is happening with that attribute

**Comment by Goutte** [comment]
Well done, thanks !
