### ISSUE TITLE
Using filterControl

### ISSUE THREAD

**Issue by dfmaxwell** [wenzhixin/bootstrap-table#1006]
Hi, I'm not sure this is the correct place to ask this.  I'm trying to get the filterControl working via JavaScript.  I'm using a server and some other settings, but I have these two jsFiddle examples which demonstrate my issue

This works - where the data-toggle="table" attribute is set in the table
https://jsfiddle.net/6q9p0k6s/1/

This one is what I want to work, but can not seem to get working
https://jsfiddle.net/qazn0pL4/

Any assistance would be appreciated.
Thanks!

**Comment by djhvscf** [comment]
You have to use the lastest version of the filter-control extension.

See this:

https://jsfiddle.net/6q9p0k6s/1/

https://jsfiddle.net/qazn0pL4/
