### ISSUE TITLE
enable cookie 问题

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#1008]
我看了代码例子有两种写法
写法一：
data-cookie="true"
data-cookie-id-table="orders-table-zonesavecookieid"
data-cookie-expire="1y"
///////////////////////////////////////////////////////////////////////////////////
写法二：
                       data-state-save="true"
                       data-state-save-expire="1y"
                       data-state-save-id-table="orders-table-zonesaveid"

现在问题如果我使用写法一，那么回报错，并没有保存cookie在本地 而且会丢失初始化的排序字段和顺序参数data-sort-name="Id"
                       data-sort-order="desc" 参数会丢失

写法二 根本没有反应

**Comment by djhvscf** [comment]
Can you translate this to english?

**Comment by wenzhixin** [comment]
#1012
