### ISSUE TITLE
[help]can I update a row by uniqueid or get a row by unique id?

### ISSUE THREAD

**Issue by sleefd** [wenzhixin/bootstrap-table#1015]

**Comment by djhvscf** [comment]
Now this festyre is not supported, let me create a PR

**Comment by sleefd** [comment]
Good,thx.

**Comment by djhvscf** [comment]
@sleefd see this: http://jsfiddle.net/djhvscf/e3nk137y/2113/

**Comment by mwatz122** [comment]
What about updating the row? We need the index to call the updateRow method. Can we get the index from the row variable? Or is there an updateRowByUniqueId method?
