### ISSUE TITLE
Column show/hide issue

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1017]
Hi,

when am hiding the first column from show/hide column list the second column header name is missing and getting first column data in second column . Please tell me how to fix it 
screenshots 
Before
![nn](https://cloud.githubusercontent.com/assets/12938449/8230965/98c257a0-15e2-11e5-8529-fe5ebaccb70a.PNG)
After
![capture](https://cloud.githubusercontent.com/assets/12938449/8229208/71f6dd0e-15d2-11e5-8e54-ff48d62bb714.PNG)

Similarly while adding individual column filter at the top. If u  hide the first column from show/hide column list the second column search box is missing. Totally confused please tell me what to do..
screenshot 2
![capture2](https://cloud.githubusercontent.com/assets/12938449/8229362/ae7ee5c2-15d3-11e5-8ff1-5c205a3f2a7c.PNG)
 
I'm using version: 1.7.0
Thank you

**Comment by djhvscf** [comment]
Can you provide a fiddle?

**Comment by djhvscf** [comment]
Or your table configuration and your json response

**Comment by wenzhixin** [comment]
Please update to the latest version.

**Comment by djhvscf** [comment]
Yes, please use the lastest version

**Comment by faruk77** [comment]
solved thank you so much
