### ISSUE TITLE
IE 9 下bootstrap-table-mobile.js 的setTimeout写法 导致 SCRIPT 87: 无效参数。错误

### ISSUE THREAD

**Issue by Wowhoo** [wenzhixin/bootstrap-table#1020]
win7 ie9
line 13
 setTimeout(that.resetView(), 1);

改成
setTimeout(function(){
     that.resetView();
}, 1);

就可以避免了

**Comment by wenzhixin** [comment]
这个问题已经解决了：https://github.com/wenzhixin/bootstrap-table/commit/d4cea151bea0dc4650e6c43a243f6e471c70ecb5
