### ISSUE TITLE
Data field unchecked

### ISSUE THREAD

**Issue by jm66** [wenzhixin/bootstrap-table#1023]
Hi,

Is there a way to set a fixed number of columns to display when the table is loaded? Let's say I have a table of 20 columns and I'd like to show only 10 when the table loaded, but if I want to show more, there's the option of click on the menu and check the column to display. 

Thanks for your help.
JM

**Comment by djhvscf** [comment]
You can use the showColumn table option in order to make visible or invislbe the columns.

Also the columns have the data-visible property

**Comment by jm66** [comment]
Thank you. data-visible did it. Sorry, I must have missed this from the docs.
