### ISSUE TITLE
Problem with adminlte and treeview menu

### ISSUE THREAD

**Issue by fbinfopro** [wenzhixin/bootstrap-table#1024]
Hi,
I use adminLTE and when i display a bootstrap table on AdminLTE content-wrapper section, the treeview menu in the main-sidebar left doesnt work. The submenu item doesnt display. When i replace the bootstrap-table with a standard html table, the treeview menu work fine.
Thank you for your help.

**Comment by wenzhixin** [comment]
Please provide a jsFiddle?

**Comment by fbinfopro** [comment]
Sorry , i have not jsfiddle, my application is complex. Bootstrap-table html and datas are generated with MySQL database.

**Comment by dabros** [comment]
@fbinfopro - your most likely using a json or similar data-url to get that data into the table though

Just open that data-url in a new window, then save any amount of entries into a js variable and use that as data source

Or just mimic any data, the actual data is prob not the issue

Then you can just include X files in your fiddle that are needed to see the behaiviour your describing

**Comment by fbinfopro** [comment]
Problem resolved. A bug in my javascript code :-).
Thank you.
