### ISSUE TITLE
Inline Checkboxes within Actions column.

### ISSUE THREAD

**Issue by kodeine** [wenzhixin/bootstrap-table#1025]
I have a question, how can i display 3 `editable checkbox's` in `Item Operate` column?
Based on this [example](http://issues.wenzhixin.net.cn/bootstrap-table/index.html)
And thanks for this package. Loving every bit of it.

**Comment by kodeine** [comment]
@djhvscf need your assistance =)

**Comment by kodeine** [comment]
anyone?

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/welcome.html

**Comment by djhvscf** [comment]
If this is no the solution then reopen this issue @kodeine
