### ISSUE TITLE
after search the table checkbox value set to “false”

### ISSUE THREAD

**Issue by harrisongu** [wenzhixin/bootstrap-table#1026]
I refer to the #175 to set obj id to checkbox input value, but when I try to do searching, the checkbox input value change to "false". This is a bug, right? 

Before search：
```
<td class="bs-checkbox"><input data-index="0" name="toolbar1" type="checkbox" value="1">
```
After search:
```
<td class="bs-checkbox"><input data-index="0" name="toolbar1" type="checkbox" value="false">
```

Thanks for the great project.
Harrison

**Comment by djhvscf** [comment]
Use the maintainSelected option

**Comment by dabros** [comment]
http://bootstrap-table.wenzhixin.net.cn/documentation/

**Comment by harrisongu** [comment]
wow，this option resolve my issue. Thanks @djhvscf @dabros ;)

**Comment by GaryReckard** [comment]
I am using the data-maintain-selected="true" option, and my checkboxes do remain selected. However, the 'value' attribute for my checkboxes gets changed from a numeric value to 'false' or 'true' (depending upon whether it is selected or not).

How can I maintain the numerical value of the checkbox after a search?!

**Comment by dabros** [comment]
@GaryReckard - if not solved from above posts, better off creating a new topic, a closed issue from 2years ago will not get attention

I would recommed searching for related issues first, keywords like "maintain" "maintain-selected" "maintainSelected" and ect would prob help. Id be willing to put already solved/clear in examples already out there
