### ISSUE TITLE
Add id to tr in bootstrap table dynamically 

### ISSUE THREAD

**Issue by naimhiq** [wenzhixin/bootstrap-table#1030]
Hej, 
I am still not able to append an ID coming from my json data to the bootstrap table as attribute in table row <tr>. See http://jsfiddle.net/naimlatifi/b7abv3er/1/                                

The purpose with data-attribute and getting the id row is that I will perform later other actions such as delete , change a row. 

Thanks for your help !

**Comment by djhvscf** [comment]
You can use the data-unique-id table option in order to have an identifier per row

**Comment by naimhiq** [comment]
where should I set it in the column  or bootstrap as property ? , would appreciate if you could show me in the above jsfiddle

**Comment by wenzhixin** [comment]
ref #658

**Comment by naimhiq** [comment]
Well I tried to put the  idField: 'myId' and data-unique-id in the Jquery initialization but still I am not able to get the data attribute with unique id in row <tr> and still I see data-index attr

**Comment by teguhpribadia** [comment]
there is no column options to change value in data-index with custom id ?? so we can take value by $element.attr(data-index)  and without check box also

**Comment by djhvscf** [comment]
You can use the data-unique-id to do that.. The data-index is not an optional option.. you can't hide that attribute.. Use the data-unique-id="name" and in every row you will get something like

```html
<tr ... data-uniqueid="josue"></tr>
<tr ... data-uniqueid="sophy"></tr>
```

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/pts5rnqm/

**Comment by teguhpribadia** [comment]
Oo yes breach and clear , i can see in inspect element also , i can use it , thanks for fast response

**Comment by djhvscf** [comment]
Great!
