### ISSUE TITLE
Reorder column order issue when column is invisble

### ISSUE THREAD

**Issue by haideraliarain** [wenzhixin/bootstrap-table#1031]
1- Hide the column using columns menu and then reorder column and if you visible the hidden column it will show as first column, is there any configuration that column should show as last column instead of first.
2- Is there any configuration, so column like checkbox and radio button can not be dragged?

**Comment by djhvscf** [comment]
The first is not an issue because if you don't move the column and then hide and then visible it will be appear in the original position.

The second is not a supported feature

**Comment by haideraliarain** [comment]
point 1, you understood it wrong, Hide any column then reorder columns and show that column, column will be shown at start of table.

**Comment by djhvscf** [comment]
See this @haideraliarain http://jsfiddle.net/djhvscf/e3nk137y/2194/

**Comment by haideraliarain** [comment]
Thank you.
