### ISSUE TITLE
Multiple tables in the same page

### ISSUE THREAD

**Issue by apuestokid** [wenzhixin/bootstrap-table#1032]
I'm triying to publish multiple tables in the same pages, the tables must have header and footer (data-show-footer="true")

The issue is in the thead secction, the firt table is OK, but the other tables, the data inside thead, doesn't comes out from the table. Find attached image.
![image](https://cloud.githubusercontent.com/assets/3874029/8280792/496a5912-18e1-11e5-9832-11e8fe5109a4.png)

**Comment by djhvscf** [comment]
What should I see??

**Comment by apuestokid** [comment]
Thaks for your response,

The <thead> content is loaded within the tbody content. You can see an empty row that should contain thead data.

Seems it is because the tables are inside bootstrap TABS, maybe i need to refresh table when click the tab buttons but i'm not sure  how to do it, i'm researching. using hide/show columns poths the thead content on it's place.

It seems, that it was another problem because i user numbers with dots (65.33%, 98.50%, etc...) and seems that "data-footer-formatter" can't contain dot character. Removing dots, reapairs footer issues.

**Comment by apuestokid** [comment]
I used this to refresh the table view with every click on the tabs: 
  $(function () {
     $('a.TabID').click(function () {
            $('table#tableID').bootstrapTable('resetView');
        });
    }); 

Is there a way to use dots in the footer?

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle to show the footer problem?

**Comment by apuestokid** [comment]
Look: http://jsfiddle.net/zaggyfed/7/
I used: data-footer-formatter="Using.Dots."

**Comment by wenzhixin** [comment]
http://jsfiddle.net/zaggyfed/8/

**Comment by djhvscf** [comment]
@apuestokid if this is not the solution, please reopen the issue
