### ISSUE TITLE
Trouble with data-url for remote json and local json 

### ISSUE THREAD

**Issue by kThayer2** [wenzhixin/bootstrap-table#1035]
Hi!  When I try to use data-url for my table I always get no matching records found.  I am pulling this directly from the online example: http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html

First off, I am using asp.net 4.0.  My css and js includes look like this:

<link type="text/css" rel="stylesheet" href="../CSS/jquery-ui.min.css">
    <link type="text/css" rel="stylesheet" href="../CSS/jquery-ui.theme.min.css">
    <link type="text/css" rel="stylesheet" href="../CSS/jquery-ui.structure.min.css">

    <link type="text/css" rel="stylesheet" href="../CSS/bootstrap-theme.min.css">
    <link type="text/css" rel="stylesheet" href="../CSS/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="../CSS/bootstrap-table.css">

    <script src="../JavaScripts/rickshaw/vendor/d3.v3.js"></script>
    <script type="text/javascript" src="../JavaScripts/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="../JavaScripts/jquery-ui.min.js"></script>
    <script type="text/javascript" src="../JavaScripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="../JavaScripts/bootstrap-table.js"></script>

My code for the table looks like this:
table data-toggle="table" data-url="http://wenzhixin.net.cn/p/bootstrap-table/docs/data1.json" data-cache="false" data-height="299"
    thead
        tr
          th data-field="id">Item ID /th
          th data-field="name">Item Name /th
          th data-field="price">Item Price /th
     /tr
   /thead
/table

I have also tried many other urls.  I have also tried locally like this:
table data-toggle="table" data-url="file://myfileshare/TableTesting.json" data-cache="false" data-height="299"
  thead
     tr
       th data-field="id">Item ID /th
       th data-field="name">Item Name /th
       th data-field="price">Item Price /th
       /tr
    /thead
/table

I can navigate to those locations on my box just fine.  Everything else with the tables are working perfectly, so I know the js and css files are working.

Thanks for the help!

**Comment by djhvscf** [comment]
Please double check this http://bootstrap-table.wenzhixin.net.cn/examples/

**Comment by wenzhixin** [comment]
Cross domain problem?

**Comment by tmorehouse** [comment]
If the remote data source does not support JSONP callbacks, then the remote data URL will fail.

**Comment by wenzhixin** [comment]
I think you can look the error info in console panel(F12), for eacmple:
```
XMLHttpRequest cannot load http://wenzhixin.net.cn/examples/bootstrap_table/data?order=asc&limit=10&offset=0. No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by tmorehouse** [comment]
The file "http://wenzhixin.net.cn/p/bootstrap-table/docs/data1.json" is a static text JSON file, and will not be wrappable in a JSONP callback.

**Comment by kThayer2** [comment]
Aww, that makes sense.  Thanks a lot of the timely help.  Is there an online web interface that does host the json data examples and support JSONP?
