### ISSUE TITLE
HTML not processed in dropdown

### ISSUE THREAD

**Issue by moerg** [wenzhixin/bootstrap-table#1038]
Hi!

We are trying to put HTML tags (see orange part) and HTML entities (see red part) into a dropdown created with "data-filter-control" attribute and we get that unexpected result.
![dropdown](https://cloud.githubusercontent.com/assets/10135983/8306260/a5a45b58-1984-11e5-8a44-830105fc58ac.png)

**Comment by djhvscf** [comment]
We need an example .. Provide a fiddle please
