### ISSUE TITLE
Issue: Mobile Responsive extension switches back to card view when scrolling on Chrome for Android (and possibly others)

### ISSUE THREAD

**Issue by tmorehouse** [wenzhixin/bootstrap-table#1039]
When using the mobile responsive extension, and a user on a small screen switches to table view (from card view), and the user scrolls it switches back to card view.

This is due to chrome's auto hiding toolbar.  When the tool bar hides (or re-appears), the resize event is fired causing the mobile extension to flip back to card view.

I have a fix for this and will be creating a PR shortly. (adds a change threshold for the window height).

**Comment by djhvscf** [comment]
Sounds great @tmorehouse

**Comment by tmorehouse** [comment]
I've created a patch branch on my fork for this fix.

**Comment by djhvscf** [comment]
Great.. can you create a PR?

**Comment by tmorehouse** [comment]
I think I did... but it ended up as part of the "locale" option PR.

**Comment by djhvscf** [comment]
Yes, you're right.. sorry

**Comment by tmorehouse** [comment]
No Problem.  I wasn't sure how to create a separate pull request from the same fork (still new at this GIT stuff)

**Comment by wenzhixin** [comment]
Merged the PR.

**Comment by tmorehouse** [comment]
Would you like me to update the extension document to include the new `heightThreshold` option?

**Comment by djhvscf** [comment]
Sure!

**Comment by tmorehouse** [comment]
documented in PR #1043
