### ISSUE TITLE
Bootstrap-Table with Json (From Mysql). Table without <THEAD>

### ISSUE THREAD

**Issue by crynos** [wenzhixin/bootstrap-table#1041]
I have a table without THEAD tag because of the layout of it. I was able to mount a simple table using examples , using the "data-field" to attach the JSON. But i wasn't able to do it with out the THEAD, using the "data-field" inside the TD tags. Is this possible? 

If it's not, there's a way to hide the THEAD?

**Comment by djhvscf** [comment]
Use the data-show-header="false"

**Comment by wenzhixin** [comment]
Hi @crynos , `thead` is necessary because we get the table field information from `thead` tag. You can via JavaScript: http://bootstrap-table.wenzhixin.net.cn/getting-started/#usage-via-javascript

**Comment by crynos** [comment]
Thank you guys for the quick response. I was able to hide the header using JS:

```<script>
    $(document).ready(function(){    
    $("#removeme").remove();
});
    </script>```

But i'm having another problem with this. May table isn't "side-by-side" row. It looks something like this:

|                SECTOR                             |               NAME                      |
|      EXTENSION      |    CELPHONE    |             EMAIL                       |
|                                         (fixed title)                                                  | 
|--------------------------------------------------------------------------------------|
|                                                                                                           |
|                                           TEXT                                                       |   
|                                                                                                           |   
|                                                                                                           |   
|--------------------------------------------------------------------------------------|

Can you help me to build this? I'm about to get crazy

**Comment by crynos** [comment]
Can this be done ?

**Comment by djhvscf** [comment]
Sorry but I am not sure what you want

**Comment by crynos** [comment]
My Table don't have a normal header like
|  HEADER 1 | HEADER 2 | HEADER 3 |

To use thead and th tags, i must be able to create a table with multiline header . Something like this:

|  HEADER 1 | HEADER 2 | HEADER 3 |
|____HEADER4___| ___HEADER 5___|


If i can do this, i'll be able to fill this table:
http://www.bootply.com/crynos/vHnJnV9qTI

**Comment by djhvscf** [comment]
Ah gotcha.. Right now this feature is not supported but we are considering add this one in the next release

**Comment by crynos** [comment]
Thank you very much. I'll try to modify the table with jquery then.
