### ISSUE TITLE
Two tr  in the thead, BT will remove the second tr

### ISSUE THREAD

**Issue by sjjliqpl** [wenzhixin/bootstrap-table#1042]
```
<thead>
    <tr>
        <th>book_price</th>
    </tr>
    <tr id="w0-filters" class="filters">
        <td><input type="text" class="form-control" name="book_price"></td>
    </tr>
</thead>
```

![qq20150624-1 2x](https://cloud.githubusercontent.com/assets/2384679/8321834/b03b86a6-1a5e-11e5-821d-4e3f497b570d.png)

**Comment by djhvscf** [comment]
Provide a fiddle please

**Comment by sjjliqpl** [comment]
Thank you guys for the quick response. There is a demo https://jsfiddle.net/sjjliqpl/wsrbLbqh/2/

**Comment by wenzhixin** [comment]
ref #336

**Comment by wenzhixin** [comment]
We will consider add this feature in the following version, close this.
