### ISSUE TITLE
Export table to excel by tableExport plugin: 10 records only, need all records

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1044]
Hello
what about this?

by migueldev:
the exportation just export the current page and not the whole rows that are find it.
![exportexcel](https://cloud.githubusercontent.com/assets/13029902/8325270/9e22da88-1a8a-11e5-8c7d-8292e8d371c9.PNG)

thanks

**Comment by wenzhixin** [comment]
Ref #858

**Comment by joomlaA1** [comment]
thanks

this could be:

var $table = $('#table_id');

        $table.bootstrapTable('togglePagination');
        $table.tableExport({type:'excel', tableName: 'Name',
                       worksheetName: 'Name',
                       fileName: 'Name'});
        $table.bootstrapTable('togglePagination');

**Comment by wenzhixin** [comment]
Added exportDataType option: http://bootstrap-table.wenzhixin.net.cn/extensions/#table-export
Example: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html

**Comment by igor-astsakhov** [comment]
exportDataType didnt work me, I would still get full set of records exported (depending on # in pagination)... had to use " tbodySelector: strSelector"

            var strSelector = $( this ).val() == 'selected' ? 'tr.selected' : 'tr';                                                                          
            $table.bootstrapTable( 'refreshOptions', {                                                                                                       
                exportDataType: $(this).val(),                                                                                                               
                exportOptions: {                                                                                                                                                                                                                             
                    tbodySelector: strSelector                                                                                                               
                }                                                                                                                                            
            });

**Comment by wenzhixin** [comment]
Please provide a jsfiddle @igor-astsakhov

**Comment by ecmattos** [comment]
I have this problem but I changed to all registers (> 1000 records) and dont works.
