### ISSUE TITLE
为什么一直提示这个?

### ISSUE THREAD

**Issue by pkptzx** [wenzhixin/bootstrap-table#1045]
"正在努力地加载数据中，请稍候……"
一直提示这个在表格上面.....
就是例子里面的..就一个html啥都没有:
```
<table data-toggle="table">
	<thead>
		<tr>
			<th>Item ID</th>
			<th>Item Name</th>
			<th>Item Price</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1</td>
			<td>Item 1</td>
			<td>$1</td>
		</tr>
		<tr>
			<td>2</td>
			<td>Item 2</td>
			<td>$2</td>
		</tr>
	</tbody>
</table>
```

**Comment by wenzhixin** [comment]
你有引入 css 文件吗

**Comment by dsimile** [comment]
引入正确的样式文件即可，如下：
<head>
    <meta charset="UTF-8">
    <title>your_name</title>
    
    <script type="text/javascript" src="../static/js/jquery.min.js"></script>
    
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    
    <script type="text/javascript" src="../static/js/bootstrap-table.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.css">
    <script type="text/javascript" src="../static/js/bootstrap-table-zh-CN.min.js"></script>
</head>

**Comment by dsimile** [comment]
`<head>`
    <meta charset="UTF-8">
    <title>全量数据数据对比展示</title>
    
    <script type="text/javascript" src="../static/js/jquery.min.js"></script>
    
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    
    <script type="text/javascript" src="../static/js/bootstrap-table/bootstrap-table.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.css">
    <script type="text/javascript" src="../static/js/bootstrap-table/locale/bootstrap-table-zh-CN.min.js"></script>
</head>

**Comment by dsimile** [comment]
`引入样式问题即可：
<head>
    <meta charset="UTF-8">
    <title>title</title>
    
    <script type="text/javascript" src="../static/js/jquery.min.js"></script>
    
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    
    <script type="text/javascript" src="../static/js/bootstrap-table.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.css">
    <script type="text/javascript" src="../static/js/bootstrap-table-zh-CN.min.js"></script>
</head>`

**Comment by dsimile** [comment]
``引入样式问题即可：
<head>
    <meta charset="UTF-8">
    <title>title</title>
    
    <script type="text/javascript" src="../static/js/jquery.min.js"></script>
    
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    
    <script type="text/javascript" src="../static/js/bootstrap-table.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.css">
    <script type="text/javascript" src="../static/js/bootstrap-table-zh-CN.min.js"></script>
</head>``

**Comment by dsimile** [comment]
``
<head>
    <meta charset="UTF-8">
    <title>title</title>
    
    <script type="text/javascript" src="../static/js/jquery.min.js"></script>
    
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    
    <script type="text/javascript" src="../static/js/bootstrap-table.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.css">
    <script type="text/javascript" src="../static/js/bootstrap-table-zh-CN.min.js"></script>
</head>``

**Comment by dsimile** [comment]
`
<head>
    <meta charset="UTF-8">
    <title>title</title>
    
    <script type="text/javascript" src="../static/js/jquery.min.js"></script>
    
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    
    <script type="text/javascript" src="../static/js/bootstrap-table.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.css">
    <script type="text/javascript" src="../static/js/locale/bootstrap-table-zh-CN.min.js"></script>
</head>`

**Comment by dsimile** [comment]
`

<head>
    <meta charset="UTF-8">
    <title>title</title>
    
    <script type="text/javascript" src="../static/js/jquery.min.js"></script>
    
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    
    <script type="text/javascript" src="../static/js/bootstrap-table.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.css">
    <script type="text/javascript" src="../static/js/locale/bootstrap-table-zh-CN.min.js"></script>
</head>
`

**Comment by dsimile** [comment]
<head>
    <meta charset="UTF-8">
    <title>title</title>
    
    <script type="text/javascript" src="../static/js/jquery.min.js"></script>
    
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    
    <script type="text/javascript" src="../static/js/bootstrap-table.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.css">
    <script type="text/javascript" src="../static/js/locale/bootstrap-table-zh-CN.min.js"></script>
</head>

**Comment by dsimile** [comment]
1. ### 
<head>
    <meta charset="UTF-8">
    <title>title</title>
    
    <script type="text/javascript" src="../static/js/jquery.min.js"></script>
    
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    
    <script type="text/javascript" src="../static/js/bootstrap-table.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.css">
    <script type="text/javascript" src="../static/js/locale/bootstrap-table-zh-CN.min.js"></script>
</head>

**Comment by dsimile** [comment]
`yyy
ggg`

**Comment by dsimile** [comment]
`fff\nnnn`

**Comment by dsimile** [comment]
`import jaga
puliv coud(`

**Comment by dsimile** [comment]
```html
<!--正确引入样式即可：-->
<head>
    <meta charset="UTF-8">
    <title>title</title>
    <!-- jquery -->
    <script type="text/javascript" src="../static/js/jquery.min.js"></script>
    <!-- bootstrap -->
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    <!-- bootstrap-table -->
    <script type="text/javascript" src="../static/js/bootstrap-table.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.css">
    <script type="text/javascript" src="../static/js/bootstrap-table-zh-CN.min.js"></script>
</head>
