### ISSUE TITLE
Hidden field feature

### ISSUE THREAD

**Issue by haideraliarain** [wenzhixin/bootstrap-table#1046]
How to handle hidden fields in this data table. i am creating table dynamically with json from server and i have some ids that i have to add as an hidden input field (i.e <input name="memberIds_200" type="hidden" value="57">).

any solution for this?

**Comment by wenzhixin** [comment]
If you use `radio` or `checkbox` you can set `idField` option. http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by haideraliarain** [comment]
its not about set id.
lets say,

i have row of reservation and reservation id set in checkbox's value and i have another input hidden element that is holding member id whom reservation belongs.

**Comment by wenzhixin** [comment]
I think you can use `visible` and `formatter` column options to do what you want.

**Comment by wenzhixin** [comment]
```html
<th data-field="other_id" data-visible="false" data-formatter="otherIdFormatter"></th>
```

```js
function otherIdFormatter(value) {
    return '<input value="' + value + '" />';
}
```
In fact, you can use the `row` data when you click the row.

**Comment by haideraliarain** [comment]
Thanks
