### ISSUE TITLE
Row data as hyperlink

### ISSUE THREAD

**Issue by rajeshbtlit** [wenzhixin/bootstrap-table#1047]
Hi,
In  bootstrap table , when the data is loaded, can we indicate the row data as hyperlink ? 

I mean each column data in a row as a link ? or a specific column data in a row as a link ?

Thanks,
Rajesh

**Comment by djhvscf** [comment]
You can use the rowStyle function.. See this: http://bootstrap-table.wenzhixin.net.cn/documentation/

**Comment by wenzhixin** [comment]
Use formatter option.

**Comment by rajeshbtlit** [comment]
Thanks a lot guys, appreciate your efforts.
Very thankful to the framework provided.
