### ISSUE TITLE
"Loading" message appears for converting existing HTML tables

### ISSUE THREAD

**Issue by jbezzyswag** [wenzhixin/bootstrap-table#1048]
![screen shot 2015-06-24 at 10 02 37 am](https://cloud.githubusercontent.com/assets/7315908/8331842/6e1b8be6-1a58-11e5-990e-f8e1abaea69a.png)

should i be getting this msg?
 <\table data-classes="table table-bordered table-condensed table-striped  table-sm" data-toggle="table" >
                        <\thead>
                        <\tr>
                            <\th width="5%">TK #</th>
                            <\th width="15%">Tech</th>
                            <\th width="15%" class="text-center">Invoice #</th>
                            <\th width="30%">Customer</th>
                            <\th width="10%" class="text-center">Date</th>
                            <\th width="5%" class="text-center">Class</th>
                            <\th width="10%" class="text-center">Billed</th>
                            <\th width="10%" class="text-center">Department</th>
                        </tr\>
                        </thead\>
                        <tbody\>
.........

                        </tbody\>
                    </table\>

and also how do i get the fixed header to work?

**Comment by wenzhixin** [comment]
css file?? http://bootstrap-table.wenzhixin.net.cn/getting-started/#usage

**Comment by jbezzyswag** [comment]
my b.. just realized i didn't include the css

**Comment by jbezzyswag** [comment]
table still not fixed am i missing something?
![screen shot 2015-06-24 at 10 29 39 am](https://cloud.githubusercontent.com/assets/7315908/8332456/0348ae30-1a5c-11e5-9b3b-68bb13df2692.png)
![screen shot 2015-06-24 at 10 29 47 am](https://cloud.githubusercontent.com/assets/7315908/8332457/034d8a0e-1a5c-11e5-928d-d5f3893a0616.png)

**Comment by djhvscf** [comment]
Provide a fiddle with your configuration please

**Comment by wenzhixin** [comment]
Please check this example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-html.html
