### ISSUE TITLE
Bootstrap-table and backbone

### ISSUE THREAD

**Issue by kryptonianson** [wenzhixin/bootstrap-table#1052]
I am wondering if anyone has used bootstrap-table together with backbone models and collections and how they were able to accomplish it. Or is this something that bootstrap-table needs to build some support in for. Thank you in advance for any help or guidance any of you can give.

**Comment by nabsky** [comment]
I'm using it this way:
```javascript
                var data = [];
                $.each(models, function(index, employee){
                    data.push(employee.toJSON());
                });
                this.$table.bootstrapTable("load", data);
```
I don't know if this is ok or not.

**Comment by kryptonianson** [comment]
that does the trick. thank you so much for your help.
