### ISSUE TITLE
Extension MultiSort when used with Toolbar creates two multi sort buttons in toolbar

### ISSUE THREAD

**Issue by tmorehouse** [wenzhixin/bootstrap-table#1055]
When using both multi-sort and toolbar (for advanced search) extensions, two advanced sort buttons appear, as can be seen in this screen grab:

![image](https://cloud.githubusercontent.com/assets/2781561/8345892/a75b58e6-1acb-11e5-8912-e67611973a14.png)

I believe this code (in the multi-sort extension):

    BootstrapTable.prototype.initToolbar = function() {
        this.showToolbar = true;
        var that = this,
            sortModalId = '#sortModal_' + this.$el.attr('id');
        this.$sortModal = $(sortModalId);

        _initToolbar.apply(this, Array.prototype.slice.apply(arguments));

        if (this.options.showMultiSort) {
            var $btnGroup = this.$toolbar.find('>.btn-group'),
                $multiSortBtn = $btnGroup.find('div.multi-sort');

Should be modified to find only the first button group (or last button group):

        if (this.options.showMultiSort) {
            var $btnGroup = this.$toolbar.find('>.btn-group').first(),
                $multiSortBtn = this.$toolbar.find('div.multi-sort');

**Comment by djhvscf** [comment]
It is correct. Can you open a new PR in order to fix this?? @tmorehouse

**Comment by tmorehouse** [comment]
I just tested it and here is the result:

![image](https://cloud.githubusercontent.com/assets/2781561/8346035/569092a8-1acd-11e5-9f34-43dcef055960.png)

**Comment by tmorehouse** [comment]
PR #1056

**Comment by djhvscf** [comment]
Thanks
