### ISSUE TITLE
maximumCountColumns 

### ISSUE THREAD

**Issue by Jithinsiva** [wenzhixin/bootstrap-table#1058]
hi @wenzhixin ,

is there any option for "maximumCountColumns" like "minimumCountColumns".? is that possible ?
I want to use detailView with 2 Columns on Mobile and Tablet view.
I got detailView with this code:

  $.extend($.fn.bootstrapTable.defaults, {
        mobileResponsive: false,
        minWidth: 562,
        minHeight: undefined,
        checkOnInit: true,
        toggled: false,
        minimunCountColumns: 2,
        detailView: checkDevice()

    });
function checkDevice(){
  if ( $(window).width() < 650 ) {return true;
}
else{
return false;
}
}
Now, I want to hide all columns in mobile except 1st 2 or 3 columns
have a look @ the screenshot attached.
![screen shot 2015-06-24 at 7 06 51 pm](https://cloud.githubusercontent.com/assets/8907116/8346496/26d04b5a-1b1b-11e5-9af7-77090fc96f41.png)
 Exactly like this! Can u help me please?  

PS: I'm not much familiar with Javascript.

**Comment by Jithinsiva** [comment]
Hey, I temporarily solved my issue with CSS. 
Is there any options for which columns to load on mobile/tablet by default for frontend?
Can u please let me know about it?

**Comment by djhvscf** [comment]
Ok, so you want to make invisible some columns when the cardview is true?? Right? I think it can be a new feature for Mobile extension

**Comment by djhvscf** [comment]
@Jithinsiva see this: http://jsfiddle.net/djhvscf/e3nk137y/2270/

**Comment by Jithinsiva** [comment]
@djhvscf  Sorry for the delay. Thanks a lot.  :)
