### ISSUE TITLE
Nested table 

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1060]
Hi,
please tell me how to add nested table. For example check the below screenshot.

![capture](https://cloud.githubusercontent.com/assets/12938449/8351438/f647f1d8-1b4a-11e5-99fa-65810b397ac1.PNG)

is there any similar feature in bootstrap table..please help me

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html
