### ISSUE TITLE
Cookie Extension - pageSize 10

### ISSUE THREAD

**Issue by dfmaxwell** [wenzhixin/bootstrap-table#1061]
Hi, on line 147 of the cookie extension it seems to be defaulting the pagesize to 10.  I have data-page-size="25" set on my table and when I added the cookie extension it resets the pagesize to 10. Can the code be altered to honor the setting I have in place there?

**Comment by djhvscf** [comment]
Your right.. This is a little bug. Let me update the extension

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/1062
