### ISSUE TITLE
duplicate sort icons in sortable colums

### ISSUE THREAD

**Issue by dizzyeyes** [wenzhixin/bootstrap-table#1063]
When using bootstrap-table 1.8.0, there will be repeat sort icons in sortable colums.

Although I dont know why it appears, I used css to avoid this bug.

.sortable{
background-repeat: no-repeat;
background-position: right;
}

**Comment by dizzyeyes** [comment]
![bug](https://cloud.githubusercontent.com/assets/8219708/8361232/6c2f08c4-1ba4-11e5-98b2-f110e5aaa93c.png)
↓↓fixed
![fixed](https://cloud.githubusercontent.com/assets/8219708/8361238/7962a438-1ba4-11e5-9035-7c13486b3987.png)

**Comment by djhvscf** [comment]
You have to use the latest bootstrap-table.css

**Comment by dizzyeyes** [comment]
:+1: ,my fault, fogot to replace css..
