### ISSUE TITLE
How to change page size

### ISSUE THREAD

**Issue by HugLem** [wenzhixin/bootstrap-table#1065]
Hi,
How can I change the page size of my bootstrap table with JavaScript? I tried:

    $('#listing-accesses').bootstrapTable('refreshOptions', {
        pageSize: 25
    });

But it doesn't work and I don't have any error.

**Comment by djhvscf** [comment]
Use the selectPage method.. : See this: http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

**Comment by HugLem** [comment]
Thank you djhvscf, but it's not the page I want to change, it's the amount of rows showed per page that I want to adjust. (10, 25, 50, 100)

**Comment by djhvscf** [comment]
See this example: http://jsfiddle.net/djhvscf/e3nk137y/2222/

**Comment by djhvscf** [comment]
Remember that you have to set data-pagination="true"

**Comment by djhvscf** [comment]
If this is not the solution, reopen the issue!

**Comment by gabisajr** [comment]
This might too late from the last comment, however adding , as a table attr should sort it
` data-page-size="25"`
