### ISSUE TITLE
Multiple tables in one webpage

### ISSUE THREAD

**Issue by sushiMish** [wenzhixin/bootstrap-table#1068]
Hi Everyone,

I have a webpage where I need to put more than 2 tables on one webpage. While doing that I am not able to control the number of rows added on the basis of unique table ID. Please suggest the way to do it.

**Comment by wenzhixin** [comment]
provide a jsfiddle please

**Comment by sushiMish** [comment]
addedNum= function () {
        var resultArr= [];
        $.each(arrayAddedNum, function (key, value) {
            resultArr.push(value["row"]);
        });
   
How can i Maintain the consistency of how the function behaves based on which table is calling the function.

**Comment by djhvscf** [comment]
Provide a fiddle, that will save our time

**Comment by dabros** [comment]
@sushiMish - please do provide fiddle, im not even sure what you mean by "rows added" or what you are trying to achieve

**Comment by wenzhixin** [comment]
You can configure different options of different table, for example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/152.html
