### ISSUE TITLE
ajax请求问题

### ISSUE THREAD

**Issue by bluee00** [wenzhixin/bootstrap-table#1072]
在一个由ajax请求实例化的表格中，有一列操作--点击详情，点击后是展开一个model模态窗，显示的是一个详情的表格，也是ajax请求的；但是点击了第一行以后，再点击别行的详情就不会走ajax请求了，会直接展示第一次请求的数据，这是为什么？应该怎么使用

**Comment by bluee00** [comment]
jsp页面的主要代码：

<div class="container">
    	
    	
    	<div id="toolbar" style="width:860px;">
			<button class="btn btn-primary" data-toggle="modal" data-target="#message_import" type="button">实习活动导入</button>
		</div>
    	<table id="practiceMessage"></table>
    
	    
	    
	    <div id="studentModal" class="modal" aria-hidden="true" data-backdrop="static">
	    	<div class="modal-dialog" style="width:1000px;">
	    		<div class="modal-content">
				    <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal">x</button>
				        <h3>学生详情</h3>
				    </div>
				    <div class="modal-body">
				        <table id="student_detail"></table>
				    </div>
				    <div class="modal-footer">
				        <a href="#" class="btn btn-primary" data-dismiss="modal">关闭</a>
				    </div>
			    </div>
		    </div>
		</div>
		
		<div id="teacherModal" class="modal" aria-hidden="true" data-backdrop="static">
	    	<div class="modal-dialog" style="width:1000px;">
	    		<div class="modal-content">
				    <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal">x</button>
				        <h3>老师详情</h3>
				    </div>
				    <div class="modal-body">
				        <table id="teacher_detail"></table>
				    </div>
				    <div class="modal-footer">
				        <a href="#" class="btn btn-primary" data-dismiss="modal">关闭</a>
				    </div>
			    </div>
		    </div>
		</div>
	 
	</div>

**Comment by bluee00** [comment]
js文件：

$(function(){
	$('#practiceMessage').bootstrapTable({
		method: 'post',
        url: path + '/nuaa/practice_assign/queryPracticeInfoList.do',
        cache: false,
        height: 845,
        striped: true,			//条纹
        pagination: true,		//分页
        pageSize: 10,
        pageList: [10, 25, 50, 100],
        search: true,
        sidePagination:'server',//设置为服务器端分页
        queryParams: queryParams,
        showColumns: true,
        showRefresh: true,
        toolbar: '#toolbar',
        minimumCountColumns: 2,
        columns: [
            {title: '序号', align: 'center', width: 50, formatter: function(value, row, index) { return index+1 } },
            {field: 'practice_code', title: '实习序号', align: 'center' },
            {field: 'practice_year', title: '实习年份', align: 'center' },
            {field: 'unit_name', title: '学院', width: 200, align: 'center' },
            {field: 'province_name', title: '实习省份', align: 'center' },
            {field: 'practice_unit', title: '实习单位', align: 'center' },
            {title: '起止日期', align: 'center', formatter: function(value, row, index) {
            	return row.startTime + '--' + row.endTime;
            } },
            {field: 'total_number', title: '实习人数（合计）', width: 120, align: 'center' },
            {field: 'operate', title: '操作', width: 210, align: 'center', formatter: operateFormatter, events: operateEvents }
        ]
    });
});

/*格式化“操作”列*/
function operateFormatter(value, row, index) {
	return [
            '<a class="edit" href="javascript:void(0)">修改</a>',
            '<a class="remove" href="javascript:void(0)">删除</a>',
            '<a class="student_detail" href="javascript:void(0)">学生详情</a>',
            '<a class="teacher_detail" href="javascript:void(0)">老师详情</a>'
        ].join('&nbsp;&nbsp;');
}

window.operateEvents = {
    'click .edit': function (e, value, row, index) {
        alert('You click edit');
        console.log(value, row, index);
    },
    'click .remove': function (e, value, row, index) {
        alert('You click remove');
        console.log(value, row, index);
    },
    'click .student_detail': function (e, value, row, index) {
    	$('#student_detail').bootstrapTable({
    		method: 'post',
            url: path + '/nuaa/practice_assign/queryPracticeStuList.do',
            cache: false,
            height: 523,
            striped: true,			//条纹
            pagination: true,		//分页
            pageSize: 10,
            pageList: [10, 25, 50, 100],
            search: true,
            sidePagination:'server',//设置为服务器端分页
            queryParams: function queryParams(params) {
            	return {
            		pageSize: params.limit,
            		pageNumber: params.pageNumber,
            		info_id: row.info_id
            	};
            },
            showColumns: true,
            showRefresh: true,
            minimumCountColumns: 2,
            columns: [
                {title: '序号', align: 'center', width: 50, formatter: function(value, row, index) { return index+1 } },
                {field: 'code', title: '学号', align: 'center' },
                {field: 'name', title: '姓名', align: 'center' },
                {field: 'sex', title: '性别', align: 'center', formatter: function(value, row, index) {return getRealSex(value);} },
                {field: 'grade', title: '年级', align: 'center' },
                {field: 'phone', title: '电话', align: 'center' },
                {field: 'phone', title: '备注', align: 'center' }
            ]
        });
    	$('#studentModal').modal('show');
    },
};

**Comment by bluee00** [comment]
js文件：
$(function(){
	$('#practiceMessage').bootstrapTable({
		method: 'post',
        url: path + '/nuaa/practice_assign/queryPracticeInfoList.do',
        cache: false,
        height: 845,
        striped: true,			//条纹
        pagination: true,		//分页
        pageSize: 10,
        pageList: [10, 25, 50, 100],
        search: true,
        sidePagination:'server',//设置为服务器端分页
        queryParams: queryParams,
        showColumns: true,
        showRefresh: true,
        toolbar: '#toolbar',
        minimumCountColumns: 2,
        columns: [
            {title: '序号', align: 'center', width: 50, formatter: function(value, row, index) { return index+1 } },
            {field: 'practice_code', title: '实习序号', align: 'center' },
            {field: 'practice_year', title: '实习年份', align: 'center' },
            {field: 'unit_name', title: '学院', width: 200, align: 'center' },
            {field: 'province_name', title: '实习省份', align: 'center' },
            {field: 'practice_unit', title: '实习单位', align: 'center' },
            {title: '起止日期', align: 'center', formatter: function(value, row, index) {
            	return row.startTime + '--' + row.endTime;
            } },
            {field: 'total_number', title: '实习人数（合计）', width: 120, align: 'center' },
            {field: 'operate', title: '操作', width: 210, align: 'center', formatter: operateFormatter, events: operateEvents }
        ]
    });
});

/*格式化“操作”列*/
function operateFormatter(value, row, index) {
	return [
            '<a class="edit" href="javascript:void(0)">修改</a>',
            '<a class="remove" href="javascript:void(0)">删除</a>',
            '<a class="student_detail" href="javascript:void(0)">学生详情</a>',
            '<a class="teacher_detail" href="javascript:void(0)">老师详情</a>'
        ].join('&nbsp;&nbsp;');
}

window.operateEvents = {
    'click .edit': function (e, value, row, index) {
        alert('You click edit');
        console.log(value, row, index);
    },
    'click .remove': function (e, value, row, index) {
        alert('You click remove');
        console.log(value, row, index);
    },
    'click .student_detail': function (e, value, row, index) {
    	$('#student_detail').bootstrapTable({
    		method: 'post',
            url: path + '/nuaa/practice_assign/queryPracticeStuList.do',
            cache: false,
            height: 523,
            striped: true,			//条纹
            pagination: true,		//分页
            pageSize: 10,
            pageList: [10, 25, 50, 100],
            search: true,
            sidePagination:'server',//设置为服务器端分页
            queryParams: function queryParams(params) {
            	return {
            		pageSize: params.limit,
            		pageNumber: params.pageNumber,
            		info_id: row.info_id
            	};
            },
            showColumns: true,
            showRefresh: true,
            minimumCountColumns: 2,
            columns: [
                {title: '序号', align: 'center', width: 50, formatter: function(value, row, index) { return index+1 } },
                {field: 'code', title: '学号', align: 'center' },
                {field: 'name', title: '姓名', align: 'center' },
                {field: 'sex', title: '性别', align: 'center', formatter: function(value, row, index) {return getRealSex(value);} },
                {field: 'grade', title: '年级', align: 'center' },
                {field: 'phone', title: '电话', align: 'center' },
                {field: 'phone', title: '备注', align: 'center' }
            ]
        });
    	$('#studentModal').modal('show');
    },
};

**Comment by bluee00** [comment]
jsp页面主要部分

**Comment by bluee00** [comment]
jsp主要部分

![11](https://cloud.githubusercontent.com/assets/7921074/8371025/6fa7bb36-1c03-11e5-93eb-eaa900cd9a73.png)

**Comment by bluee00** [comment]
...jsp主要代码
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>实习学生安排</title>
    
    <link href="../public/bootstrap-3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <link href="../public/bootstrap-3.3.4/css/bootstrap-table.css" rel="stylesheet">
    
    <script src="../public/js/jquery-1.11.3.min.js"></script>
    <script src="../public/js/nuaa.js" type="text/javascript"></script>
    <script src="../public/js/ajaxfileupload.js" type="text/javascript"></script>
    <script src="stu_assign.js"></script>
    <script type="text/javascript">
		var path = "${pageContext.request.contextPath}";
	</script>
    
    <style>
	    #message_import,#student_import,#teacher_import
	    {
	        top:200px;
	    }
	    .file-box{ position:relative;width:350px;margin-left:50px;margin-top:15px;}
		.txt{ height:26px; border:1px solid #cdcdcd; width:250px; margin-left:-5px}
		.file{ position:absolute; top:0; right:55px; height:28px; opacity:0; width:300px }
	</style>
</head>

<body>

    <div class="container">
    	<table id="practiceMessage"></table>
	    
	    
	    <div id="studentModal" class="modal" aria-hidden="true" data-backdrop="static">
	    	<div class="modal-dialog" style="width:1000px;">
	    		<div class="modal-content">
				    <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal">x</button>
				        <h3>学生详情</h3>
				    </div>
				    <div class="modal-body">
				        <table id="student_detail"></table>
				    </div>
				    <div class="modal-footer">
				        <a href="#" class="btn btn-primary" data-dismiss="modal">关闭</a>
				    </div>
			    </div>
		    </div>
		</div>
	 
	</div>
	
	
    <script src="../public/bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <script src="../public/bootstrap-3.3.4/js/bootstrap-table.js"></script>
    
    <script src="../public/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>
...

**Comment by bluee00** [comment]
...js的代码
$(function(){
	$('#practiceMessage').bootstrapTable({
		method: 'post',
        url: path + '/nuaa/practice_assign/queryPracticeInfoList.do',
        cache: false,
        height: 845,
        striped: true,			//条纹
        pagination: true,		//分页
        pageSize: 10,
        pageList: [10, 25, 50, 100],
        search: true,
        sidePagination:'server',//设置为服务器端分页
        queryParams: queryParams,
        showColumns: true,
        showRefresh: true,
        toolbar: '#toolbar',
        minimumCountColumns: 2,
        columns: [
            {title: '序号', align: 'center', width: 50, formatter: function(value, row, index) { return index+1 } },
            {field: 'practice_code', title: '实习序号', align: 'center' },
            {field: 'practice_year', title: '实习年份', align: 'center' },
            {field: 'unit_name', title: '学院', width: 200, align: 'center' },
            {field: 'province_name', title: '实习省份', align: 'center' },
            {field: 'practice_unit', title: '实习单位', align: 'center' },
            {title: '起止日期', align: 'center', formatter: function(value, row, index) {
            	return row.startTime + '--' + row.endTime;
            } },
            {field: 'total_number', title: '实习人数（合计）', width: 120, align: 'center' },
            {field: 'operate', title: '操作', width: 210, align: 'center', formatter: operateFormatter, events: operateEvents }
        ]
    });
});

/*格式化“操作”列*/
function operateFormatter(value, row, index) {
	return [
            '<a class="edit" href="javascript:void(0)">修改</a>',
            '<a class="remove" href="javascript:void(0)">删除</a>',
            '<a class="student_detail" href="javascript:void(0)">学生详情</a>',
            '<a class="teacher_detail" href="javascript:void(0)">老师详情</a>'
        ].join('&nbsp;&nbsp;');
}

window.operateEvents = {
    'click .edit': function (e, value, row, index) {
        alert('You click edit');
        console.log(value, row, index);
    },
    'click .remove': function (e, value, row, index) {
        alert('You click remove');
        console.log(value, row, index);
    },
    'click .student_detail': function (e, value, row, index) {
    	$('#student_detail').bootstrapTable({
    		method: 'post',
            url: path + '/nuaa/practice_assign/queryPracticeStuList.do',
            cache: false,
            height: 523,
            striped: true,			//条纹
            pagination: true,		//分页
            pageSize: 10,
            pageList: [10, 25, 50, 100],
            search: true,
            sidePagination:'server',//设置为服务器端分页
            queryParams: function queryParams(params) {
            	return {
            		pageSize: params.limit,
            		pageNumber: params.pageNumber,
            		info_id: row.info_id
            	};
            },
            showColumns: true,
            showRefresh: true,
            minimumCountColumns: 2,
            columns: [
                {title: '序号', align: 'center', width: 50, formatter: function(value, row, index) { return index+1 } },
                {field: 'code', title: '学号', align: 'center' },
                {field: 'name', title: '姓名', align: 'center' },
                {field: 'sex', title: '性别', align: 'center', formatter: function(value, row, index) {return getRealSex(value);} },
                {field: 'grade', title: '年级', align: 'center' },
                {field: 'phone', title: '电话', align: 'center' },
                {field: 'phone', title: '备注', align: 'center' }
            ]
        });
    	$('#studentModal').modal('show');
    },
};
...

**Comment by wenzhixin** [comment]
```js
$(function(){
    $('#practiceMessage').bootstrapTable({
    	...	
    });
    // 先初始化
    $('#student_detail').bootstrapTable({
        ...
    });
});
```

```
    'click .student_detail': function (e, value, row, index) {
        // 使用 refresh 方式，传入 url 和 query
    	$('#student_detail').bootstrapTable('refresh', {
            url: '...',
            query: {
        		pageSize: params.limit,
        		pageNumber: params.pageNumber,
        		info_id: row.info_id
        	}
        });
    	$('#studentModal').modal('show');
    },
};
```

**Comment by wenzhixin** [comment]
bootstrapTable 构造方法只会初始化一次。

**Comment by bluee00** [comment]
sidePagination:'server',这个设置是在初始化里还是在后面的点击方法的refresh里？

**Comment by bluee00** [comment]
我按照你的思路在
...

'click .student_detail': function (e, value, row, index) {
       $('#student_detail').bootstrapTable('refresh', {
    		url: path + '/nuaa/practice_assign/queryPracticeStuList.do',
    		queryParams: function queryParams(params) {
            	return {
            		pageSize: params.limit,
            		pageNumber: params.pageNumber,
            		info_id: row.info_id
            	};
            }
        });
}
...
这么做的时候回传的参数不对啊！并不是pageSize，pageNumber，info_id这三个参数

**Comment by wenzhixin** [comment]
sidePagination:'server' 在初始化设置，
看文档：http://bootstrap-table.wenzhixin.net.cn/documentation/#methods
```
    $('#student_detail').bootstrapTable('refresh', {
        url: '...',
        query: {
            pageSize: params.limit,
            pageNumber: params.pageNumber,
            info_id: row.info_id
        }
    });
```

**Comment by bluee00** [comment]
```javascript
$('#student_detail').bootstrapTable('refresh', {
        url: '...',
        query: {
            pageSize: params.limit,
            pageNumber: params.pageNumber,
            info_id: row.info_id
        }
    });
```
这么使用的时候提示params is not defined

**Comment by wenzhixin** [comment]
改成这样
```javascript
$('#student_detail').bootstrapTable('refresh', {
        url: '...',
        query: {
            info_id: row.info_id
        }
    });
```
初始化还是传 params

**Comment by wenzhixin** [comment]
关闭该问题，假如还有问题 reopen 它。

**Comment by bluee00** [comment]
O(∩_∩)O谢谢！周末有点忙，刚刚调试了一下，可以的！大神，顺便问一下，我想把下面这个方法
```javascript
function queryParams(params) {
return {
pageSize: params.limit,
pageNumber: params.pageNumber
};
```
抽出来变成公共方法作为分页查询的参数，怎么通过js给查询条件赋其他值？

**Comment by bluee00** [comment]
还是有问题，按照你最后的提示 ，模态框弹出的分页表格第一页是没有问题的，第二页就没法显示了，因为传的参数没有info_id，只有pageSize和pageNumber

**Comment by wenzhixin** [comment]
那你用 refreshOptions 方法，重置所有的参数，具体看文档或者例子

**Comment by bluee00** [comment]
可以了

**Comment by wenzhixin** [comment]
OK！
