### ISSUE TITLE
Set Request Headers For Remote Data

### ISSUE THREAD

**Issue by fynnfeldpausch** [wenzhixin/bootstrap-table#1075]
Is there any way to provide request headers for remote data when using the table with a POST request method? In this case, I need to provide an authorization X-Auth-Token...

    <table data-toggle="table" data-url="somePostUrl" data-method="post">
        <thead>
          ...
        </thead>
    </table>

**Comment by wenzhixin** [comment]
You can use `ajaxOptions` option: http://bootstrap-table.wenzhixin.net.cn/documentation/

**Comment by fynnfeldpausch** [comment]
Ah, many thanks.
