### ISSUE TITLE
On click-cell.bs.table event row parameter is undefined

### ISSUE THREAD

**Issue by matopeter** [wenzhixin/bootstrap-table#1076]
When click-cell event triggered, the third (row) parameter is undefined, forth ($element) value is the row object. Code:

$('#hTable').on('click-cell.bs.table', function (field, value, row, $element){
  console.log(field);
  console.log("V: "+value);
  console.log("R: "+row); // this is undefined
  console.log($element);
});

**Comment by wenzhixin** [comment]
The first param is event: 
```
function (e, field, value, row, $element)
```
Example: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/welcome.html

**Comment by matopeter** [comment]
Thank you for your quick answer. I have corrected my code.
I think, it would be great to write it to the documentation. Or is it a convenction? The first parameter always the event itself?

**Comment by wenzhixin** [comment]
Right, when you use `on` to bind the event, the first parameter always the event itself: http://getbootstrap.com/javascript/#js-events.
Of course, you can use this:
```
bootstrapTable({
    onClickCell: (field, value, row, $element) {}
});
```

**Comment by matopeter** [comment]
Thanks again. I got it.
