### ISSUE TITLE
nested json not working. link to fiddle pls help

### ISSUE THREAD

**Issue by aav789** [wenzhixin/bootstrap-table#1077]
I want to display multiple rows of nested json but when i try to do that it does not work. Please help.

http://jsfiddle.net/8svjf80g/188/

Correct above jsfiddle and attach working link please.

**Comment by djhvscf** [comment]
Yes, I'm checking the problem with the flat-json extension

**Comment by aav789** [comment]
Please let me know of solution since i need to give a deliverable by Monday.

**Comment by aav789** [comment]
My problem looks similar to #353. but i am not able to understand the solution to it. Can you please make the changes in the jsfiddle and let me know the link.

I am on a tight deadline. thanks.

**Comment by djhvscf** [comment]
Yes, we are working on it but just in case the multidimensional array is not a supported feature so we have to develop the logic to support that

**Comment by djhvscf** [comment]
If you can help us that will be great! @aav789

**Comment by wenzhixin** [comment]
I think you in your case can handle your response data to what table need @aav789.
