### ISSUE TITLE
Filter-Control & Show/Hide Columns

### ISSUE THREAD

**Issue by dfmaxwell** [wenzhixin/bootstrap-table#1078]
I seem to have two issues with the show/hide columns and it could be directly related to the filter-control since I am using that.  When Hiding/Showing a column the headers will change alignment compared to the cells below.  I've implemented the Cookie Extension so a refresh will have the column shown or missing and things will be aligned correctly.  Thanks for the quick fix on the cookie extension.

The second issue would be that after the show/hide I get inconsistent filters, most of the select elements are empty, so I can't use them without refreshing the page.

**Comment by djhvscf** [comment]
can you provide a fiddle?? I think that issue is already fixed

**Comment by djhvscf** [comment]
Any update here?

**Comment by jetsaredim** [comment]
I submitted a pull request for this issue.  It should allow the column select state to be saved.

**Comment by wenzhixin** [comment]
Please provide a jsFiddle to show your problem.

**Comment by dfmaxwell** [comment]
I've not been able to get a jsFiddle working yet.  My implementation is server based and I can't expose that data externally.  My first shot at a jsFiddle also rendered completely wrong.

**Comment by dfmaxwell** [comment]
I am trying to get an example running and have made some progress.  This example: http://jsfiddle.net/vbrhrbzL/ is not fully functional, The filters aren't populating from the variables, any thoughts on how to get those working so I can keep working on a jsFiddle?  Also I've noticed that even though they aren't working if I hide/show columns the HF Complete and Online are wiped out, initially they have 1 blank dropdown element, afterwards they have no dropdown element.

**Comment by djhvscf** [comment]
Let me check what is happening

**Comment by rhegner** [comment]
I also have issues with the filter-control extension and hidden columns. I think it is related to this issue here.

You can find a very simple jsfiddle here:
https://jsfiddle.net/6ngd2kcg/

As you can see in the HTML code I want to have a filter on "Column 2". But since "Column 1" is invisible, the filter is shown on "Column 3".

**Comment by djhvscf** [comment]
This issue is fixed in the 1.10.1
