### ISSUE TITLE
How to change column data in a Bootstrap Table column

### ISSUE THREAD

**Issue by vicentor** [wenzhixin/bootstrap-table#1080]
I'm not sure I put the right tags, but here's an odd issue I have with the bootstrap-table. I assume there is an object in memory that has values that can be different from the ones shown on screen?

See this: http://stackoverflow.com/questions/31032194/how-to-change-column-data-in-a-bootstrap-table-column

**Comment by djhvscf** [comment]
You can use the updateRow method in order to update the row info

**Comment by djhvscf** [comment]
See this example: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/updateRow.html
