### ISSUE TITLE
css 书写错误？

### ISSUE THREAD

**Issue by Wowhoo** [wenzhixin/bootstrap-table#1086]
bootstrap-table/src/extensions/reorder-rows/bootstrap-table-reorder-rows.css 
.reorder_rows_onDragClass td {
    ...
    -box-shadow: 6px 4px 5px 1px #555, 0 1px 0 #ccc inset, 0 -1px 0 #ccc inset;
}

.reorder_rows_onDragClass td:last-child {
   ...
    -box-shadow: 0 9px 4px -4px #555, 0 1px 0 #ccc inset, 0 -1px 0 #ccc inset, -1px 0 0 #ccc inset;
}

-box-shadow ?   box-shadow！

**Comment by djhvscf** [comment]
Translate this to english because I don't know what you want to

**Comment by Wowhoo** [comment]
Sorry,I mean the CSS clerical error:"-box-shadow".

**Comment by djhvscf** [comment]
So, how should it be?

**Comment by Wowhoo** [comment]
这明显的问题还问，明显没去看文件，最后一条标准属性写法是 box-shadow  不是带把子的“-box-shadow”，难道说这里 把子还有特殊作用，如果有能告诉下吗！谢谢 （对了，看不懂的话请自行翻译成英文）
