### ISSUE TITLE
希望bootstrap-table的固定表头功能继续扩展

### ISSUE THREAD

**Issue by gx0803** [wenzhixin/bootstrap-table#1087]
现在bootstrap能够自适应超多列表格内容的展示，在保持table的显示区域宽度固定的同时，自动产生横向滚动条，支持拖动显示后面的列的内容。

希望在固定表头的同时，能够增加一个API，实现支持对表格前N列内容固定展示的功能，类似于excel表格中的冻结列。这样在拖动查看后面列的内容时，还能很清晰的看出后面的内容和具体的记录之间的关系。

**Comment by wenzhixin** [comment]
已有相关的需求，后续会考虑增加，关联到：#265

**Comment by shengwei2016** [comment]
当表头内容过多，而整个表格容器比较窄的时候导致表头特别大，tbody的内容特别小，这个有什么比较好的解决办法么？排序按钮占过多位置，但是不能修改padding-right值，会导致整个container的padding-bottom值显示错误，下面显示空白内容。求解答
