### ISSUE TITLE
setCustomQueryProperties for querying simple search input ! 

### ISSUE THREAD

**Issue by naimhiq** [wenzhixin/bootstrap-table#1088]
Hi, 

I want to to add a button 'search' for my  input field in bootstrap table and I am using the method for setCustomQueryProperties. I simple call the method setCustomQueryProperties and pass the parameter for my search query from input value and then refresh the table as below 
```
bootstrapTable('setCustomQueryProperties', searchQueryValuehere);
bootstrapTable('refresh');
```
But I have a problem since it just refresh the table and does not find the query searched. 

Thanks for help !

**Comment by naimhiq** [comment]
Any updates on the above ? 

I really appreciate !

**Comment by djhvscf** [comment]
Hi, what is the setCustomQueryProperties method?? Bootstrap-table does not have that method

**Comment by naimhiq** [comment]
Well, I tried and set a method prototype for setCustomQueryProperties in order to get the query from my input field and search in the table with search button but did not succeed. Is there any example to make the input field with the button search so when I want to search in the input search  I press the button instead of keyup and enter. 

Thanks a lot for any help !

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

**Comment by naimhiq** [comment]
Hej, 

I am getting an error while implementing custom toolbar table. I have the same code as https://jsfiddle.net/naimlatifi/7qzg701L/ but I am getting "Uncaught TypeError: Cannot read property 'fixedScroll' of undefined" 

Thanks for help !

**Comment by wenzhixin** [comment]
Is the response data different?

**Comment by naimhiq** [comment]
yeah I have the following data as json https://jsfiddle.net/naimlatifi/7qzg701L/2/

**Comment by wenzhixin** [comment]
Our example is using this response: http://issues.wenzhixin.net.cn/examples/bootstrap_table/data?offset=0&limit=5&search=

**Comment by naimhiq** [comment]
Ah I see, got it to work , however now when I search an item in search field, table is just keeping refreshing does not find the query searched

**Comment by wenzhixin** [comment]
Please view our example source: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/custom-toolbar.html
