### ISSUE TITLE
Select data on click of a hyper link

### ISSUE THREAD

**Issue by rajeshbtlit** [wenzhixin/bootstrap-table#1089]
Hi,
We would need to get the selected data on click of hyper link. But also we need to support multiple select on the table. On click of hyper link should give us the selected row

![hyperlink](https://cloud.githubusercontent.com/assets/11829880/8406751/0f6aa0b8-1e7d-11e5-87d2-b21f307d3224.png)

In the above image, on click of hyper link we cant use sleeted row using:
 $('#table').bootstrapTable({}).on('click-row.bs.table', function (e, row, $element) {

Could you please help

**Comment by djhvscf** [comment]
Review this: https://github.com/wenzhixin/bootstrap-table/issues/1047

**Comment by dabros** [comment]
@rajeshbtlit - no time to do fiddle sorry, and code not in front of me, but there is a very useful looking events you could subscribe to

http://bootstrap-table.wenzhixin.net.cn/documentation/

onClickCell - passes in parameter containing column info already

If you wanted to make more obvious in UI, try appling css to make that <a> anchor/hyperlink fill all space of that cell, so the normal : hover style provides immediate feedback to tell user that whole cell is the link

**Comment by rajeshbtlit** [comment]
Hi dabros, thanks for your response,
here is the jsfiddle, so on click of link in the table, we need the corresponding row data.
https://jsfiddle.net/jupitor/tmLzkt43/2/


Also note that on click of link, the checkbox is checked and on clicking again the check box is unchecked.

So its fairly simple on click of the hyper link , we need to know the corresponding row data as we do using $('#table').bootstrapTable({}).on('click-row.bs.table', function (e, row, $element) {

**Comment by wenzhixin** [comment]
Do you mean like this: https://jsfiddle.net/wenyi/tmLzkt43/3/?

**Comment by dabros** [comment]
@wenzhixin @rajeshbtlit 

https://jsfiddle.net/tmLzkt43/5/

Slight tweak to that example, though still couldnt fill it dynamically to height, it does fill dynamic to width very easily

see my notes in css section
