### ISSUE TITLE
How to put an onclick inside of a TD using data-url

### ISSUE THREAD

**Issue by kThayer2** [wenzhixin/bootstrap-table#1090]
I was wondering if it is possible to put an onclick for a specific td using data-url.  I would need to also put a specific id on that TD to indicate what was clicked.  This is easy to do on a regular table as you have access to the td, but in the case of data-url you don't.

Thanks!

**Comment by djhvscf** [comment]
We have the onClickCell event that returns the: field, value, row, $element

See this: http://bootstrap-table.wenzhixin.net.cn/documentation/#events

**Comment by kThayer2** [comment]
Awesome, thanks!
