### ISSUE TITLE
Pagination on the top and bottom?

### ISSUE THREAD

**Issue by Cowdrey** [wenzhixin/bootstrap-table#1091]
It would be nice to have the option of having pagination on the top or bottom or both.

**Comment by djhvscf** [comment]
Before open a issue,.see the documentation please 

Here is an [example](http://jsfiddle.net/djhvscf/e3nk137y/2289/)

**Comment by Cowdrey** [comment]
Whoops! I completely missed the VAlign in the docs. Sorry about that. Thank you very much for the quick reply.
