### ISSUE TITLE
Filter Control issue when sidePagination is server

### ISSUE THREAD

**Issue by balen** [wenzhixin/bootstrap-table#1092]
When sidePagination is "server", the Filter Control will send the filter to the server AND do a local search of the table.

This is because the function in boostrap-table-filter-control for initSearch does not take into account that the work is done on the server.

The issue can be seen when the filter is select and the variable is a structure like
```
var ticket_types = { '1': "first ticket", '2':'Second ticket'};
```
Then the server will filter by ticket id (1 or 2) and the table will also be filtered locally by the same value. But the column values are the names not the id.
This can be resolved by using the same value for column names as the id i.e.
```
var ticket_types = { 'first ticket': "first ticket", 'Second ticket':'Second ticket'};
```
But this is not ideal. For example, if a more complex filter was used (say a text field) where the server uses implicit wild cards then strings such as "This string" could also match "This is a string" since the server may search "%This%string%" (if using mysql for example). But the extension will further filter the result to remove "This is a string".

The solution would be to change the BootstrapTable.prototype.initSearch in the file so that it only does the work if
```
this.options.sidePagination !== 'server'
```

**Comment by djhvscf** [comment]
Sounds like a good solution.. Can you prepare a fiddle and also a pull request??

**Comment by balen** [comment]
I will put together a pull request.
I am not sure about the fiddle since the server call requires authentication. I will see if I can get a version of the server side without that restriction (it may take a bit longer to get everything in place).

**Comment by djhvscf** [comment]
@balen can you use this [example](http://jsfiddle.net/wenyi/e3nk137y/14/light/) ?? maybe it works for you

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
