### ISSUE TITLE
Question: why $('#table').bootstrapTable({data: data}); not work when with data-toggle="table"?

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1093]
Hello

********
********

var data = 
[
    {
        "id": 0,
        "name": "test0",
        "price": "$0"
    }
];

$(function () {
    $('#table').bootstrapTable({
        data: data
    });
});

********
********

This is ok: (table id="table")
<table id="table">
    <thead>
        <tr>
            <th data-field="id">Item ID</th>
            <th data-field="name">Item Name</th>
            <th data-field="price">Item Price</th>
        </tr>
    </thead>
</table>

This is not ok: (table id="table" data-toggle="table")
<table id="table" data-toggle="table">
    <thead>
        <tr>
            <th data-field="id">Item ID</th>
            <th data-field="name">Item Name</th>
            <th data-field="price">Item Price</th>
        </tr>
    </thead>
</table>

Why not ok? thanks

**Comment by wenzhixin** [comment]
Because bootstrap table is just only initialize once, when you use `data-toggle="table"`, it is the same with `$('#table').bootstrapTable();`, in your case, you can use:
```html
<table data-toggle="table"></table>

$('#table').bootstrapTable('load', data);
```

**Comment by joomlaA1** [comment]
Thank you
