### ISSUE TITLE
How to pass a model to data-url in bootstrap table?

### ISSUE THREAD

**Issue by flook** [wenzhixin/bootstrap-table#1094]
I cannot figure out, how do i pass a model to the `data-url` property of `bootstrap-table` ?

My Razor Code:

    @model IEnumerable<MyModel>

    <table id="myTable" data-url=......">
        <thead>
            <tr>
                <th data-field="MyProperty">
                    Some Example
                </th>
                <th data-field="MyProperty2">
                    Some Example
                </th>
                <th data-field="MyProperty3">
                    Some Example
                </th>
            </tr>
        </thead>
    </table>

My Controller Code -  just in case.

    [HttpGet]
    public ActionResult GetMyValues()
    {
        List<MyTable> myList = myObj.GetValues();
        return PartialView("MyPartialView", myList);
    }

  [1]: http://bootstrap-table.wenzhixin.net.cn/examples/

**Comment by wenzhixin** [comment]
ref #375
