### ISSUE TITLE
Cannot make to work bootstrap-table examples locally ! 

### ISSUE THREAD

**Issue by naimhiq** [wenzhixin/bootstrap-table#1096]
Hej guys, 

I just cloned bootstrap table examples  from  https://github.com/wenzhixin/bootstrap-table-examples but cannot make work it locally. I see in the console I have error like "Failed to load resource" complaining for  "bootstrap-table-editable.js"

Anyone else has the same issue ? 

Thanks for help !

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table-examples#usage
