### ISSUE TITLE
Unable to load bootstrap table

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1097]
![11](https://cloud.githubusercontent.com/assets/12938449/8428392/fce058e2-1f3b-11e5-984f-4caccc9bd7eb.PNG)
![22](https://cloud.githubusercontent.com/assets/12938449/8428393/fe44a102-1f3b-11e5-8e0e-8f50eca20dc0.PNG)

Getting this error please tell me how to fix..

**Comment by djhvscf** [comment]
Hmm.. it not easy to help with this information.. Perhaps double check the jquery reference, the boostrap-table.js reference and the order of those scripts

**Comment by wenzhixin** [comment]
Please provide a jsfiddle to show your problem.
