### ISSUE TITLE
Filter control not working.

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1098]
Hi,
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filtercontrol.html

This example is not working suddenly, getting error. Please check it
![image](https://cloud.githubusercontent.com/assets/12938449/8429185/eaeb798a-1f42-11e5-882d-cef3df5af2af.png)
 please tell me how to fix it.. In my local example also getting same error

**Comment by wenzhixin** [comment]
Updated to: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html
