### ISSUE TITLE
ie8不支持吗?

### ISSUE THREAD

**Issue by pkptzx** [wenzhixin/bootstrap-table#1099]
###ie8不支持吗?

**Comment by wenzhixin** [comment]
支持

**Comment by pkptzx** [comment]
在ie8下面我的表头第一次加载的时候不对三列只有两列的表头,然后表头有两个重叠.点下排序,表头就好了,但还是盖着我的表头盖着表头...

只要有排序的存在...这个问题....官方demo也一样.

**Comment by wenzhixin** [comment]
要看下是什么原因，现在很少使用IE，不过应该是跟 bootstrap 都支持 IE8 及以上的，你说的是哪个页面

**Comment by pkptzx** [comment]
我也无法描述了...我把例子放到我的机器上运行,在IE8下同时打开base sort的例子.github的没问题,我的机器上的就有两个表头压着的问题....只有一个地方不同(例子里没有bootstrap-table.js等),就是bootstrap-table我是单独下的然后考到例子的那个src目录下的.意思是???我下的bootstrap-table比例子的新?才导致的这个问题?

**Comment by pkptzx** [comment]
好吧...我把github在线的例子里的bootstrap-table.min.css和dist下的bootstrap-table.min.css下载下来了...大小都不一样...这...到底用哪个....

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table-examples#usage

**Comment by pkptzx** [comment]
经测试.dist文件夹下的居然和src文件夹下的不一样,最后我使用src下的js没有表头覆盖的问题了.但是还是有表头少一列的问题.

**Comment by wenzhixin** [comment]
提供下截图什么的？

**Comment by maplehsu** [comment]
请问哪个版本号支持IE8.. getOwnPropertyNames  版本 version: 1.11.1 是不支持的
