### ISSUE TITLE
Page getting hang

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1100]
Hi,
Im using this in my application http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html
previous filter control works fine but due to some  undefined column error messages i changed this with new one but it is hanging with above 15 rows while using data-filter-control="select".
 if i remove fdata-filter-control="select" it is working fine..
Please tell me how to fix..

**Comment by djhvscf** [comment]
Oh! Can you provide a little fiddle or more information about the problem that you have??

**Comment by dabros** [comment]
@faruk77 - please refer to #1126 and provide fiddle and more information

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
