### ISSUE TITLE
Want sample example with filter control and cookie

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1101]
Hi,
Im using filter control and cookies in my bootstrap table but combining both not working please provide me any sample example with both the feature.. I already found separate examples for filter control and cookie

**Comment by djhvscf** [comment]
Ok, for now those extensions are not working together.. I mean the cookie extension does not support the controls that the filter-control extension create in the table.. We have to add logic to support filter-control, reorder-columns, reorder-rows extensions

**Comment by faruk77** [comment]
okay thank you
