### ISSUE TITLE
Not  loading latest record after add or update record in IE9/10, while its working fine in other browser

### ISSUE THREAD

**Issue by ravi-ku** [wenzhixin/bootstrap-table#1102]
Hi,

After adding or updating any record ,  bootstrap-table is not updating with latest records;
not even called server side function from where we are fetching the Latest record.
------------------------JS Function-------------------------
function loadAccountMaster() {
        $('#tblAaccountMasters').bootstrapTable('destroy');
        $('#tblAaccountMasters').bootstrapTable({
            url: '/AccountMaster/GetAll',
            pagination: true,
            pageSize: 10,
            pageList: [10, 20, 50],
            search: true,
            showColumns: true,
            showRefresh: true,
            minimumCountColumns: 3,
            clickToSelect: false
        });
    }

------------------------HTML-------------------------
      <table id="tblAaccountMasters"
                   data-show-columns="true"
                   data-search="true"
                   data-pagination="true"
                   data-url="/AccountMaster/GetAll">
                <thead>
                    <tr>
                        <th data-field="Id" data-visible="false" data-switchable="false">Id</th>
                        <th data-field="ExecutionEnvironment" data-visible="false" data-switchable="false">ExecutionEnvironment</th>
                        <th data-field="ClientRestrictions" data-visible="false" data-switchable="false">ClientRestrictions</th>
                        <th data-field="AccountCode"><strong title="Account Group Code">Account Group Code</strong></th>
                        <th data-field="AccountGroupName"><strong title="Account Group Name">Account Group Name</strong></th>
                        <th data-field="operate" data-formatter="operateFormatter" data-events="operateEvents" class="col-md-1"><strong title="Action">Action</strong></th>
                    </tr>
                </thead>
            </table>

regards

**Comment by wenzhixin** [comment]
cache problem?

**Comment by wenzhixin** [comment]
Any update?

**Comment by ravi-ku** [comment]
Sorry for delay response. It was cache issue as you said above.I have set cache = true which resolved the issue.
