### ISSUE TITLE
refresh is not working in IE

### ISSUE THREAD

**Issue by ravi-ku** [wenzhixin/bootstrap-table#1103]
$('#refresh').click(function () {
            $('#tblAaccountMasters').bootstrapTable('refresh', {
                url: '/AccountMaster/GetAll'
            });
        });

Regards,

**Comment by djhvscf** [comment]
I debug on IE10 and it is working.. can you provide more detail?

**Comment by ravi-ku** [comment]
HTML -----------------------
     <div class="toolbar">
                <button id="refresh" class="btn btn-default">Refresh</button>
            </div>
            <table id="tblAaccountMasters"
                   data-toolbar="toolbar"
                   data-show-columns="true"
                   data-search="true"
                   data-pagination="true"
                   @*data-url="/AccountMaster/GetAll"*@>
                <thead>
                    <tr>
                        <th data-field="Id" data-visible="false" data-switchable="false">Id</th>
                        <th data-field="ExecutionEnvironment" data-visible="false" data-switchable="false">ExecutionEnvironment</th>
                        <th data-field="ClientRestrictions" data-visible="false" data-switchable="false">ClientRestrictions</th>
                        <th data-field="AccountCode"><strong title="Account Group Code">Account Group Code</strong></th>
                        <th data-field="AccountGroupName"><strong title="Account Group Name">Account Group Name</strong></th>
                        <th data-field="operate" data-formatter="operateFormatter" data-events="operateEvents" class="col-md-1"><strong title="Action">Action</strong></th>
                    </tr>
                </thead>
            </table>

JS function on page load------------------------
 function loadAccountMaster() {
        $('#tblAaccountMasters').bootstrapTable('destroy');
        $('#tblAaccountMasters').bootstrapTable({
            url: '@Url.Action("GetAll", "AccountMaster")',
            pagination: true,
            pageSize: 10,
            pageList: [10, 20, 50],
            search: true,
            showColumns: true,
            showRefresh: true,
            minimumCountColumns: 3,
            clickToSelect: false
        });
    }

Refreshing JS function-------------------

  $('#refresh').click(function () {
            $('#tblAaccountMasters').bootstrapTable('refresh', {
                url: '/AccountMaster/GetAll'
            });
        });

**Comment by wenzhixin** [comment]
The same with #1102, and I think it is cache problem.
