### ISSUE TITLE
cookie extension

### ISSUE THREAD

**Issue by andresendo** [wenzhixin/bootstrap-table#1104]
Hi,
is it possible to add cookie support for the resizable and reorder-columns extension. Because so can make the user his own table layout.

And any idea why my cookie ext. don't save the hidden or visible columns. All other "cookie ext." features work without problems.

thanks
andre

**Comment by djhvscf** [comment]
See this http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html in order to review the show/hide columns.. There it is working fine

And for the others extension we have to add the logic

**Comment by andresendo** [comment]
I see this:
https://github.com/jetsaredim/bootstrap-table/commits/7d6736d0f148f5ce8e584618aa940c3bf98a62bb/src/extensions/cookie/bootstrap-table-cookie.js

And after i make this two changes.. it works..

So and for the other extensions.. sounds good.

**Comment by andresendo** [comment]
any chance to save the resize and reorder extensions? :)

**Comment by Zetabox** [comment]
Hi,
I'm also looking for saving reorder columns; is it available ?

**Comment by munozdaniel** [comment]
saving reorder columns is it available ?

**Comment by camj256** [comment]
Also looking for re-order resize saving.

**Comment by snipe** [comment]
One more vote for cookie-enabled re-ordering

**Comment by djhvscf** [comment]
Ref #2889
