### ISSUE TITLE
Static table with checkboxes

### ISSUE THREAD

**Issue by vinisorga** [wenzhixin/bootstrap-table#1105]
When i try to use the select checkboxes in a static table specifing the values of the checkboxes, at the time the page loads the values are gone.

example: http://jsfiddle.net/dhaffzbt/5/

**Comment by wenzhixin** [comment]
Sorry, I don't know what you mean.

**Comment by vinisorga** [comment]
![inspect](https://cloud.githubusercontent.com/assets/6579911/8475799/0a32eec8-2091-11e5-8e21-d3b05d1df4ec.png)

**Comment by OfficialBAMM** [comment]
https://jsfiddle.net/dhaffzbt/7/

A workaround for this problem, hope it is helpful for you :)

**Comment by wenzhixin** [comment]
or http://jsfiddle.net/dhaffzbt/8/
