### ISSUE TITLE
Clarification requested

### ISSUE THREAD

**Issue by cgarveyie** [wenzhixin/bootstrap-table#1106]
Hello there, can you please clarify exactly what the effect is of the {silent:true/false} option the table refresh behaviour?

**Comment by wenzhixin** [comment]
if silent is true will not show the loading information

**Comment by cgarveyie** [comment]
Is there any effect on events triggered by the table reloading? e.g. if there is an onLoad behaviour attached to a table and it is refreshed silently, will the onLoad behaviour still trigger?

**Comment by wenzhixin** [comment]
Yes, `onLoadSuccess` event will still trigger.
