### ISSUE TITLE
Border issue

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1109]
Hi,
The filter controls are mixed with headers, please tell me how to add border to above and below of the filter controls like separate row.

**Comment by djhvscf** [comment]
Can you provide an example or a screenshot?

**Comment by faruk77** [comment]
![image](https://cloud.githubusercontent.com/assets/12938449/8615286/0880c33c-270f-11e5-9c56-ca43f0da8997.png)

**Comment by faruk77** [comment]
![capture](https://cloud.githubusercontent.com/assets/12938449/8615305/2f111394-270f-11e5-87d5-36c032adc0b8.PNG)

Please check the screen and tell me how to do this?

**Comment by wenzhixin** [comment]
Use css, I think I have provide a jsFiddle to your problem.
