### ISSUE TITLE
The column name instead of its order number passed to sort.bs.table function.

### ISSUE THREAD

**Issue by b4ubest** [wenzhixin/bootstrap-table#1110]
I load json data and initialize columns through javascript. Then I try to highlight column on sort (make sorted column bordered).
 It works with html table, but doesn't work when I load json data because second parameter, passed to function 'sort.bs.table' is string.

**Comment by b4ubest** [comment]
Example with html table work:
http://b4ubesub.bget.ru/strongclient/app/settings_screen.html
Example with data loaded by json doesn't work
http://localhost:63342/strongclient/app/reports_miss.html

**Comment by b4ubest** [comment]
https://jsfiddle.net/n0h7xkm9/
How can I get sortable column number?

**Comment by wenzhixin** [comment]
Ref #1076

**Comment by b4ubest** [comment]
Thanks
