### ISSUE TITLE
Pagination is returning older results first?

### ISSUE THREAD

**Issue by davidhtien** [wenzhixin/bootstrap-table#1111]
I'm trying to use the server side pagination but the first page returned are the older results even though I sort them on the server side to be newer results first...

**Comment by wenzhixin** [comment]
View our example: http://issues.wenzhixin.net.cn/bootstrap-table/index.html

**Comment by davidhtien** [comment]
I don't really get it... the only thing I see that could help is limiting my api to return only ten results...

**Comment by wenzhixin** [comment]
You need to handle the sort on your server side. for example:
http://issues.wenzhixin.net.cn/examples/bootstrap_table/data?sort=id&order=asc&limit=10&offset=0
http://issues.wenzhixin.net.cn/examples/bootstrap_table/data?sort=id&order=desc&limit=10&offset=0
