### ISSUE TITLE
Three State Sorting - Asc, Desc and Reset to Default

### ISSUE THREAD

**Issue by SarahD** [wenzhixin/bootstrap-table#1119]
Good morning guys!
My company is hoping to have three-state sorting functionality. Is it possible with your tool?
First Click and Second Click function normally, but on the Third Click, it resets to table default. 

Any thoughts or ideas as to how this might be done? Thanks again!

http://jsfiddle.net/webdevsarah/ngjpkptk/

All the best,
Sarah

**Comment by wenzhixin** [comment]
We do not support this feature now.

**Comment by dabros** [comment]
@SarahD 

ref: #1594

**Comment by djhvscf** [comment]
Same of #1594
