### ISSUE TITLE
bootstrap table order by id not working as desired

### ISSUE THREAD

**Issue by BhavinVisariya** [wenzhixin/bootstrap-table#1123]
Order by id - ascending. 
Desired order : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
Getting order  : 1, 10, 11,...,19, 2, 20, 21, ..... , 29, 3, 30, 31,...

This is working as desired on my local machine. But not on any of my servers.

Kindly update me about this issue.

Thanks.

**Comment by wenzhixin** [comment]
Check your response data:
```
"id": 1
```
instead of:
```
"id": "1"
```

**Comment by BhavinVisariya** [comment]
It worked. Thanks for the reply.

I am getting "id": 1 on my local machine and "id": "1" on my server. Can you tell me why is this so?

I am using Laravel framework. I am getting data from database and passing as json without processing it.

**Comment by djhvscf** [comment]
I'm don't know how Laravel works but maybe the issues is related to the database datatype

**Comment by BhavinVisariya** [comment]
database datatype is correct. Anyways thanks.

**Comment by dabros** [comment]
@BhavinVisariya - just try casting it to desired format to keep consistent, which is always a good idea even as purely preventitive

Casting before the json or after should be the same, just do it before passing into actual table
