### ISSUE TITLE
Filter based on combo box with checkboxes

### ISSUE THREAD

**Issue by toontilley** [wenzhixin/bootstrap-table#1124]
Does anyone know of a way to have checkboxes inside the filter box so you can filter on multiple options ie all rows that have either apple or oranges in a specific column?

Many thanks

**Comment by wenzhixin** [comment]
Do you mean: http://issues.wenzhixin.net.cn/bootstrap-table/#options/boolean-options.html?

**Comment by onrozcn** [comment]
i need this solution.

like a this: http://dotansimha.github.io/angularjs-dropdown-multiselect/#/

**Comment by wenzhixin** [comment]
I think you can use [custom toolbar](http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html) to define your own filter or you can use [Filter Control](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html) extension.
Close the issue.
