### ISSUE TITLE
TypeError: $.fn.bootstrapTable is undefined

### ISSUE THREAD

**Issue by TreyTaylor** [wenzhixin/bootstrap-table#1125]
Hey all!

Trying to impliment the filterControl extension of the Bootstrap-table. I added the options to my table/table-headers and when I saw no change I looked to see if there were any errors with the JS console and it came up with *TypeError: $.fn.bootstrapTable is undefined*. 

Here is my code:

html:

    <table
        data-toggle="table"
	data-search="true"
	data-pagination="false"
	data-height="800" 
	data-sort-name="Company_Name"
       	data-sort-order="ASC"
	data-show-columns="true"
        data-show-toogle="true"
        data-show-export="true"
	filterControl="true" 
	filterShowClear="true"
	>
	<thead>
	    <th>Display Name</th>
	    <th>Company Name</th>
	    <th>Address 1</th>
            <th>Address 2</th>
	    <th>Address 3</th>
	    <th>Town Name</th>
	    <th>County</th>
	    <th>Postcode</th>
	    <th>Phone</th>
	    <th>WWW</th>
	    <th>Contact Name</th>
	    <th showFilter="true" filterControl="select">Membership Level Name</th>
	</thead>

The example I followed didn't have a script so I'm assuming this is how? (if not, could someone update the examples :-) )

thanks :smile_cat:

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/filter-control.html

**Comment by djhvscf** [comment]
I think it can be a order references issue.. Please double check your script order @TreyTaylor

**Comment by TreyTaylor** [comment]
@djhvscf aye! you were right :-) thanks (any my bad) though still not showing up :/

**Comment by djhvscf** [comment]
So, is it working for you? @TreyTaylor

**Comment by TreyTaylor** [comment]
Sadly no, just no more errors in the console log, maybe an issue with my code? I think I put the options in the right places?

Would it help to know my Browser info and all that jazz?

**Comment by djhvscf** [comment]
Use.. data-filter-control="true" and data-filter-show-clear="true" in the table configuration and in the TH configuration data-filter-control="select"

**Comment by djhvscf** [comment]
```html
 <table
        data-toggle="table"
	data-search="true"
	data-pagination="false"
	data-height="800" 
	data-sort-name="Company_Name"
       	data-sort-order="ASC"
	data-show-columns="true"
        data-show-toogle="true"
        data-show-export="true"
	data-filter-control="true" 
	data-filter-show-clear="true">
	<thead>
	    <th>Display Name</th>
	    <th>Company Name</th>
	    <th>Address 1</th>
            <th>Address 2</th>
	    <th>Address 3</th>
	    <th>Town Name</th>
	    <th>County</th>
	    <th>Postcode</th>
	    <th>Phone</th>
	    <th>WWW</th>
	    <th>Contact Name</th>
	    <th data-filter-control="select">Membership Level Name</th>
	</thead>
```

**Comment by TreyTaylor** [comment]
Copied into the page and nothings happened.. do I need to do anything anywhere else?

**Comment by djhvscf** [comment]
Provide a fiddle please

**Comment by TreyTaylor** [comment]
http://jsfiddle.net/43ttaxx3/

(not a big user of jsfiddle so I hope its right please let me know if there's anything wrong :s haha)

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/43ttaxx3/4/

**Comment by TreyTaylor** [comment]
I copied it and it still is an issue, I use PHP to call data in a foreach loop if that makes any difference?

**Comment by djhvscf** [comment]
Can you show us some code?

**Comment by TreyTaylor** [comment]
How I get the data (MYSQL):

    SELECT * FROM comp WHERE comp_id = :comp_id

The table:

    <table data-toggle="table"
    data-search="true"
    data-pagination="false"
    data-height="500" 
    data-sort-name="Company_Name"
    data-sort-order="ASC"
    data-show-columns="true"
    data-show-toggle="true"
    data-show-export="true"
    data-filter-control="true"
    data-filter-show-clear="true">
     <thead>
      <th>Display Name</th>
      <th>Company Name</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>Address 3</th>
      <th>Town Name</th>
      <th>County</th>
      <th>Postcode</th>
      <th>Phone</th>
      <th>WWW</th>
     <th>Contact Name</th>
     <th data-filter-control="select">Membership Level Name</th>
   </thead>

How I call the data:

    <?php foreach ($Variable as $Data) : ?>
       <tr>
	    <td><?= $Data['Display_Name'] ?></td>
	    <td><?= $Data['Company_Name'] ?></td>
	    <td><?= $Data['Address_1'] ?></td>
	    <td><?= $Data['Address_2'] ?></td>
	    <td><?= $Data['Address_3'] ?></td>
 	    <td><?= $Data['town_name']?></td>
	    <td><?= $Data['State_']?></td>
	    <td><?= $Data['Zip']?></td>
	    <td><?= $Data['Phone']?></td>
	    <td><?= $Data['WWW']?></td>
	    <td><?= $Data['Contact_Name']?></td>
	    <td ><?= $Data['Membership_Level_Name']?></td>
        </tr>
    <?php endforeach ?>

**Comment by TreyTaylor** [comment]
I don't think it's the PHP, just tried with manuel entries and it still doesn't show... I also checked to make sure everything was linked up properly JS wise, and then copied your code. Changed browser to test if it was a Firefox issue (small chance but might as well test) and again nothing.. it's almost like something is missing and it's not creating the button??

**Comment by dabros** [comment]
@TreyTaylor - i cant speak to the code you shared, but i found many reasons to stick to generating json from php (usually as ajax capable request, so a url that returns the json data)

That can be fed into the bootstrap table and make good use of "refresh" action, as well as very easily debugged

I would strongly discourage printing direct content like you are atm, even if only as it just limits what you can do (no ajax capability, no easy "refresh" button) as well as harder to debug

You can print content onto the page using php (json_encode) inside a script block, assigning it to a js variable and setting that as the datasource, might be easy way to test it first, but just as easy to make any .php file (or route, if using framework) as url endpoint and use as datasource.

Dont have code in front of me atm sorry, but plenty in examples i believe http://bootstrap-table.wenzhixin.net.cn/

**Comment by dabros** [comment]
If you wanted to print it to page as js variable, or even just as is now, you can use F12 or viewsource and save copy of it including the printed content.

A text copy here (so we see where you point resources to originally) might be enough to see the issue, as im thinking it is just as likely still an order or missing resource issue, if no obvious js error from misconfigured data.

If not, you can feed it into a fiddle for us and then upload those linked files (see option on left side when creating fiddle) and we can rule out any version mismatch or other odd issue with file intersection perhaps

**Comment by wenzhixin** [comment]
Have you solved your problem now @TreyTaylor?

**Comment by tvik3000** [comment]
I suppose  you dont have  
$.fn.bootstrapTable.utils = {
        sprintf: sprintf,
        getFieldIndex: getFieldIndex,
        compareObjects: compareObjects,
        calculateObjectValue: calculateObjectValue
    };
in your bootstrap-table.js
refresh latest version of it :)
 wenzhixin, you are awesome! :))
