### ISSUE TITLE
Text Trim issue

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1126]
Hi,
Im using colresizer plugin the header th data is trimming but body td data is not trimming please tell me how to fix this issue. I have checked few examples but they are static, please tell me how to trim text dynamically on column resize.

![trim](https://cloud.githubusercontent.com/assets/12938449/8499257/7be10a6e-21ae-11e5-9375-9979eff0d911.PNG)

**Comment by djhvscf** [comment]
Can you provide an example?? The example [here](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/resizable.html) does not have that issue @faruk77

**Comment by djhvscf** [comment]
Any update here?

**Comment by faruk77** [comment]
Hi did you understand?
I'm using colresizer plugin please tell me how to trim text in cell on column resize..can please provide a example ?

**Comment by faruk77** [comment]
There is no date picker in above two links

**Comment by dabros** [comment]
@faruk77 - can you please provide more info

You have alot of topics, about a bunch of stuff, but very hard to make out exactly what you want

Please take the time to setup a main jsfiddle, then 'branch' it for each problem, to keep code seperate but consistent

We really cant help much without it, especially when using plugins and when the problem not clearly defined (some of your other topics more so than this one, but still)

Thanks

**Comment by faruk77** [comment]
okay sorry i will provide the fiddle example

**Comment by dabros** [comment]
https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Afaruk77+

We are happy to help, but yes please do provide fiddle and more info : )

**Comment by dabros** [comment]
@faruk77 - please provide update here and close if solved

**Comment by dabros** [comment]
@faruk77 - still waiting

**Comment by djhvscf** [comment]
Close this issue because the author is not providing any answer
