### ISSUE TITLE
How to toggle "reorder rows"

### ISSUE THREAD

**Issue by adele2011** [wenzhixin/bootstrap-table#1127]
I want to enable reordering rows when a button is clicked.
I tried refreshOptions:
```
$table.bootstrapTable('refreshOptions', {
    reorderableRows: true
});
```
But it doesn't work.

**Comment by djhvscf** [comment]
Hmm this is not supported because the main plugin is  binded when you change the option.. So we need to add a destroy method in order to unbind the plugin

**Comment by wenzhixin** [comment]
You can use:
```
$table.bootstrapTable('destroy').bootstrapTable({
    reorderableRows: true
});
```
