### ISSUE TITLE
reorder columns throwing error on first switch 

### ISSUE THREAD

**Issue by Cowdrey** [wenzhixin/bootstrap-table#1128]
I may just be using this extension improperly, since your example [here](http://issues.wenzhixin.net.cn/bootstrap-table/index.html#extensions/reorder-columns.html)  seems to work.  I recreated my problem in [jsfiddle](https://jsfiddle.net/qo21dnku/3/). The BootstrapTable object doesn't get created properly (no column field).

Again not sure if it is a bug since your example seems to work fine.

**Comment by djhvscf** [comment]
Please use the master version of [bootstrap-table.js](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js)
