### ISSUE TITLE
table-condensed is not working

### ISSUE THREAD

**Issue by Krinkle** [wenzhixin/bootstrap-table#1130]
Similar to #44.

The class itself is applied, but bootstrap-table has an override rule with `!important` that breaks the condensed style:

<img width="1323" alt="screen shot 2015-07-05 at 07 07 03" src="https://cloud.githubusercontent.com/assets/156867/8510539/77294a7c-22e4-11e5-8afc-d78fe8c6399c.png">

**Comment by poulpo** [comment]
Same problem for me.
It seems it was working on older versions of bootstrap-table when there were no css rules starting with ".bootstrap-table".

**Comment by geeyan** [comment]
Same problem. See:
https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.css#L14-L21

I made a pull-request:
https://github.com/wenzhixin/bootstrap-table/pull/1479

**Comment by wenzhixin** [comment]
Merged
