### ISSUE TITLE
insertRow when search is active

### ISSUE THREAD

**Issue by oferch** [wenzhixin/bootstrap-table#1131]
Hi,
I have a 'duplicate row' button which works fine, by using the insertRow method.
But when the user filter the table data (using the search box), it doesn't work anymore.

Ofer

**Comment by wenzhixin** [comment]
Please provide a jsfiddle to show your problem use our [templates](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports), that will save our time.

**Comment by wenzhixin** [comment]
Any update here?
