### ISSUE TITLE
Grouped / Sum Table

### ISSUE THREAD

**Issue by andresendo** [wenzhixin/bootstrap-table#1132]
Hi,
exists a solution to make a table like this. This is a extjs Table and it's grouped automatically by a table column "Groupname" (like Angebote, Rechnungen...)

<img width="1378" alt="bildschirmfoto 2015-07-05 um 21 12 43" src="https://cloud.githubusercontent.com/assets/255217/8513007/2da51f62-235b-11e5-96d7-eccf1d802a59.png">

It would by so nice if i can make this also with bootstrap-table - so i can remove extjs from my project.

**Comment by djhvscf** [comment]
Use the group-by extensión in order to do that

**Comment by andresendo** [comment]
Is this correct?
		data-groupBy="true"
		data-groupByField="field1"

**Comment by andresendo** [comment]
ok, that is the right way:
data-group-by="true" data-group-by-field="name" 

But it don't work for tables with serverbased data,right?  And is a sum possible per group?

**Comment by djhvscf** [comment]
Right now the sum per group is not supported.. and what do you mean by serverbased?? Ajax stuff??

**Comment by andresendo** [comment]
I make this:
 data-side-pagination="server"
 data-url="json.php"

That don't work... but with your example JS with "data".. that works..  hmm... what do you think any change to a sum per group?

**Comment by dabros** [comment]
With server pagination, prob an issue of you needing to do the grouping on the server side, similar to how you need to pass the total rows count back in. 

@djhvscf  @wenzhixin  Is there a format to return grouped data in from data-side-xx="server"?

**Comment by djhvscf** [comment]
See this https://github.com/wenzhixin/bootstrap-table/pull/1142 @andresendo @dabros

**Comment by andresendo** [comment]
Wow.. that looks good! THX!!! Thanks Dennis!!

Two / three questions about this.. i have reactivated the sorting (not for the grouped col) - i think it works.. ?!

1. Is it possible to make a colspan for the group header? Only with the content of the grouped Header field..also if it visible=false?
2. Can i deactive the sum per col?

Andre

**Comment by djhvscf** [comment]
Ok,
1. Now we have an issue relsted to sorting so I think it is nor working now
2. Now it is not supported
3. Yes, you can call the expandAll method
