### ISSUE TITLE
缺少一个api以及加载其他分页问题

### ISSUE THREAD

**Issue by lmoyrd** [wenzhixin/bootstrap-table#1135]
1.bootstrap-table缺少getRowByUniqueId，源码没找到这个函数，我后来自己加上去了。
2.场景:数据表row中提供写数据库操作的交互按钮，此交互按钮在用户点击后和服务器返回结果这段时间会处于disable(自己加了个类)状态，这样确保用户重复点击。现在发现我在点击按钮后马上切换到下一页，然后再切换回来，发现那个按钮居然已经处于可点击状态，也就是table修改了数据！我看了下，应该是updatePagination函数的问题，但是貌似挺多函数的。希望大大有时间能帮看看。大大可以直接用你自己的例子 http://issues.wenzhixin.net.cn/bootstrap-table/index.html   实践下。

**Comment by wenzhixin** [comment]
1. 是有这个函数的：https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L2066
2. 例子是用服务器拿的模拟数据，使用 editable 编辑之后，数据并不会更新到服务器上，所以切换之后还是原来的问题，这个不是问题。
