### ISSUE TITLE
Adding Search

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1137]
Hi, please tell me how to add my own  individual textbox to each column. I already tried to add it based on column index but while using show/hide getting issue because of im using index please tell me any other alternatives or give me sample example for it..

**Comment by djhvscf** [comment]
Did you use the filter-control extension, did not you?

**Comment by faruk77** [comment]
No added my own search boxes please check the example below

http://jsfiddle.net/skfaruk/dq43uypw/2/

**Comment by djhvscf** [comment]
Well in that case you can see the filter-control code

**Comment by faruk77** [comment]
Hey but there is no date search in filter control

**Comment by djhvscf** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/filter-control/README.md

**Comment by djhvscf** [comment]
You can use the dstepicker plugin fron bootstrap
