### ISSUE TITLE
click editable column selects row click-to-select

### ISSUE THREAD

**Issue by OfficialBAMM** [wenzhixin/bootstrap-table#1138]
Tiny issue while having click-to-select and editable activated. If you click the editable field and to edit it, it selects the row.

OfficialBAMM

Ps. Thanks for this amazing plug-in helped me big time!

**Comment by wenzhixin** [comment]
Please set the `clickToSelect` column option to false to solve this problem:
```
    editable: true,
    clickToSelect: false,
```

**Comment by OfficialBAMM** [comment]
This is not a solution, but just disabling the functionality. 

It's not big deal though.

**Comment by wenzhixin** [comment]
not a solution？

**Comment by OfficialBAMM** [comment]
Sorry. misread your comment.

Thanks :+1:
