### ISSUE TITLE
date search in filter control

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1139]
Hi, please tell me is there any feature to add date picker to searchbox?

**Comment by djhvscf** [comment]
See the datepickeroptions in this documentación..https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/filter-control/README.md

**Comment by periyasamy25** [comment]
I need two date search boxes on top the table.one is for start date and other one is for end date.I need to display rows between these two dates.How to do this?

**Comment by faruk77** [comment]
I added date filter control but it was not firing please tell me how to fix it?

**Comment by djhvscf** [comment]
Example http://jsfiddle.net/djhvscf/e3nk137y/2414/

**Comment by periyasamy25** [comment]
I need two datepicker for single column to search data between these two dates.how to do this. any examples?

**Comment by djhvscf** [comment]
Well, filter-control does not support that featrue,, We can add just one datepicker per column
