### ISSUE TITLE
Remove horizontal scrollbar

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1140]
columns should fit with autosize not with fixed size
when there are more columns, they can shrink instead of scroll bar. Please tell me how to remove horizontal scrollbar

**Comment by dabros** [comment]
fiddle please

**Comment by dabros** [comment]
@faruk77 - please refer to #1126 and provide fiddle and more information

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
