### ISSUE TITLE
option data is not reading from variable

### ISSUE THREAD

**Issue by lordtubington** [wenzhixin/bootstrap-table#1141]
I have a json file with my data for bootstrap-table. What I do is set the json file url, then by using From Date and To Date fields, narrow down the number of results that should be returned from that json file client side. Those results are put into a JSON.stringify variable, and should be displayed in the bootstrap-table. I can get the results to appear in console.log but not in bootstrap-table. I have it built in this codepen link http://codepen.io/lordtubington/pen/GJOVpy

**Comment by wenzhixin** [comment]
I think you can try this:
```
//my_array = JSON.stringify(my_array);
$table.bootstrapTable("load", my_array);
```

**Comment by lordtubington** [comment]
Thanks for the quick reply. I updated my pen at http://codepen.io/lordtubington/pen/GJOVpy with your suggestion but it's still not working. Changed console.log to alert if that helps.

**Comment by wenzhixin** [comment]
Working here: http://codepen.io/anon/pen/YXLaZJ, data-search-text is to initialize the search text.
