### ISSUE TITLE
datepicker  example

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1143]
Hi please any one provide me filter control datepicker example in jsfiddle or any working example

Thank you..

**Comment by wenzhixin** [comment]
#971

**Comment by faruk77** [comment]
There is no date picker in above two links. please check it and provide working example..

**Comment by OfficialBAMM** [comment]
//Date sort. Reverses the string, so that the format is: Y-m-d, and remove the -'s
    function dateSorter(a, b) {
    	    a = a.replace('-', '');
    	    a = a.split("").reverse().join("");
    	    a = parseInt(a);
	    b = b.replace('-', '');
	    b = b.split("").reverse().join("");
	    b = parseInt(b);
	    if (a < b)
	    {
		    return -1;
	    }
	    if (a > b)
	    {
		    return 1;
	    }
    	     return 0;
    } 

The above works.
Put `data-sorter="dateSorter"` in the column you want to sort.

**Comment by wenzhixin** [comment]
Example: http://jsfiddle.net/wenyi/e3nk137y/2435/

**Comment by dabros** [comment]
is this solved, or the same as #1169 ?
