### ISSUE TITLE
I need automatic offset,limit,sorting and pagiantion in custom toolbar

### ISSUE THREAD

**Issue by periyasamy25** [wenzhixin/bootstrap-table#1146]
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html
In this link you have provided custom toolbar but I need automatic offset,limit,sorting and pagiantion and manual search using two datepickers.how to do this?

**Comment by wenzhixin** [comment]
You can define the `queryParams` option to do that, for example:
```js
queryParams: function (p) {
    p.fromDate = $('#fromDatepicker').val();
    p.toDate = $('#toDatepicker').val();
    return p;
}
```

**Comment by periyasamy25** [comment]
Thank you
