### ISSUE TITLE
怎么去掉分页工具栏左侧的条数选择？

### ISSUE THREAD

**Issue by aiien007** [wenzhixin/bootstrap-table#1147]
我使用分页功能的时候 表格底部左侧出现选择显示数据的条数（如 Showing 1 to 10 of 21 rows records per page） 右侧是页码
我只想要右侧页码不要左侧选择显示数据条数的功能 可以做到吗？
谢谢

**Comment by wenzhixin** [comment]
可以的，设置 `formatShowingRows`：http://jsfiddle.net/wenyi/e3nk137y/2421/

**Comment by aiien007** [comment]
你好，我用你的代码试了一下不行
	<script type="text/javascript">
		$(function() {
			$('#user_table').bootstrapTable({
				 method: 'get',
				 url: 'data1.json',
				 cache: false,
				 height: 300,
					pagination: true,
					pageSize: 2,
					formatShowingRows: function () {
						return '';
					},
				 columns: [{
	                    field: 'state',
	                    checkbox: true
	                }, {
	                    field: 'id',
	                    title: 'Item ID',
	                    align: 'right',
	                    valign: 'bottom',
	                    sortable: true
	                }, {
	                    field: 'name',
	                    title: 'Item Name',
	                    align: 'center',
	                    valign: 'middle',
	                    sortable: true
	                }, {
	                    field: 'price',
	                    title: 'Item Price',
	                    align: 'left',
	                    valign: 'top',
	                    sortable: true,
	                }, {
	                    field: 'operate',
	                    title: 'Item Operate',
	                    align: 'center',
	                    valign: 'middle',
	                    clickToSelect: false,
	                }]
			 });
		});
	</script>
左侧还是会出现 选择页码 records per page
不过Showing 1 to 10 of 21 rows 不出现了 
求解

**Comment by wenzhixin** [comment]
设置下这个：formatRecordsPerPage，看文档：http://bootstrap-table.wenzhixin.net.cn/documentation/#localizations
