### ISSUE TITLE
Search brings matching img tags

### ISSUE THREAD

**Issue by cjsfj** [wenzhixin/bootstrap-table#1148]
In my table i have results that contain image tags, but when I search for "img" in the search, it returns these results, which I don't want it to. 

How can I make sure the search only returns results that match text and not images?

Thanks,

C

**Comment by wenzhixin** [comment]
For the image field, you can set `searchable` to `false`.

**Comment by cjsfj** [comment]
So the only solution is to split the image field out from the text? We have img next to text, like an icon for the text.

**Comment by OfficialBAMM** [comment]
What about creating a div with a background 'image'. Something like this:
`<div style="background:url('your image url');width:200px;height:200px"></div>`

**Comment by wenzhixin** [comment]
Added `searchFormatter` option: http://jsfiddle.net/wenyi/e3nk137y/2430/
http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

**Comment by rodi189** [comment]
@wenzhixin need update your example because its not working
