### ISSUE TITLE
好像不能动态更换查询条件？

### ISSUE THREAD

**Issue by penweizgx** [wenzhixin/bootstrap-table#1149]
在查询的时候会更换查询URL和查询条件,现在查询条件（queryParams）绑定了一个方法，我就不能动态的去指定查询条件了？现在bootstrap-table 已经提供了更换URL的方法，单好像不能自己指定查询参数

**Comment by wenzhixin** [comment]
使用 refresh 方法：http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

**Comment by wenzhixin** [comment]
refresh 传入 url 和 query 就可以了
