### ISSUE TITLE
Fixed table header

### ISSUE THREAD

**Issue by OfficialBAMM** [wenzhixin/bootstrap-table#1150]
Something like below. Would be a cool feature :).

http://jsfiddle.net/QHQGF/7/
Note, did not make this.

**Comment by emilchristensen** [comment]
:+1:

**Comment by djhvscf** [comment]
This feature is implemented. You have to set the data-height option in order to get this feature

**Comment by wenzhixin** [comment]
Maybe you can try this extension: https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/sticky-header
