### ISSUE TITLE
How to get the json object name in formatter?

### ISSUE THREAD

**Issue by zpf364** [wenzhixin/bootstrap-table#1151]
I have a json file like this.
{
	"9": {
                 "aa":123,
                 "bb":234
	},
	"10": {
                 "aa":13,
                 "bb":24
	}
}

'9','10' is my object id and  I want to use the object id in column formatter.How can I get the ID  in formatter? Thank you !

**Comment by OfficialBAMM** [comment]
Your question is very unclear. Please provide a fiddle it will improve the answers given.

So what you want is to have the 9 and the 10 as a column header?

**Comment by wenzhixin** [comment]
Like this: http://jsfiddle.net/7y9t8zqb/?
