### ISSUE TITLE
为什么ajax加载服务端数据后，全局设定的jQuery.ajaxSetup complete方法没办法捕获到

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#1153]
为什么ajax加载服务端数据后，全局设定的jQuery.ajaxSetup complete方法没办法捕获到
我设定
jQuery.ajaxSetup({
            beforeSend: function () {
                //$('#loader').show();
               
            },
            complete: function () {
                //$('#loader').hide();
                 
            },
            timeout: function () {
                //alert('error');
            },
            error: function () {
                //alert('error');
            },
            success: function () {
                //alert('success');
            }
        });

我自己写jquery, get,post,ajax都能捕获到 这些事件的，但是boostraptable，只触发了beforeSend ，complete ，error，success都捕获不到，请问哪边可以修改

**Comment by wenzhixin** [comment]
应该是被覆盖了吧，你用 events 吧：
```
$table.on('load-success.bs.table', function (e, data) {

});

$table.on('load-error.bs.table', function (e, status) {

});
```
