### ISSUE TITLE
removeAll方法点击表格报错

### ISSUE THREAD

**Issue by aiien007** [wenzhixin/bootstrap-table#1154]
我想移除表格数据 使用了removeAll方法
移除后表格 显示 No matching records found
1.我怎么修改No matching records found这段话？
2.点击No matching records found部分 报错
firebug提示TypeError: e is undefined
....find("th:eq("+f+")"),i=h.data("field"),j=e[i];c.trigger("click-cell",i,j,e,b),c...
bootstr...4602440 (第 7 行，第 26470 列)

我的代码：$('#user_table').bootstrapTable('removeAll');
谢谢

**Comment by wenzhixin** [comment]
第一点看文档：http://bootstrap-table.wenzhixin.net.cn/documentation/#localizations
或者使用语言文件：https://github.com/wenzhixin/bootstrap-table/blob/master/src/locale/bootstrap-table-zh-CN.js
第二点已经修复了，不过还没发布 release
