### ISSUE TITLE
无法进入responseHandler函数

### ISSUE THREAD

**Issue by iamwelk** [wenzhixin/bootstrap-table#1156]
url: "data/userList.json",
		height: 490,
		pageSize: 10,
		pagination: true,
		sidePagination: "server",
		queryParams: queryFunction,
		responseHandler: dataHandler,
queryParams可以打印出数据，但是responseHandler无法进入，但是从浏览器里可以看到已经加载了json数据，不知道是什么原因。。。

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/353.html 例子是可以的，用浏览器调试下

**Comment by wenzhixin** [comment]
可以了没，假如还有问题的话再 reopen 问题

**Comment by PianoWang** [comment]
同样的问题responseHandler没有办法进，demo同样没法运行。
