### ISSUE TITLE
Bootstrap Table search issue

### ISSUE THREAD

**Issue by naveenkumart** [wenzhixin/bootstrap-table#1157]
We are using ajax json data for Bootstrap table. A part from the data displaying on table, we are getting some more values and assigning them as attribute values for further application use. So when we are searching table data it is considering table view data along with inner attributes data for search but what we need is to search data that was displayed and viewed in cells.

ex:
```
          <table>
                 <tr>
                     <td><a href="javascript:void(0)" a="12" id="nani005">Naveeen</a></td>
               </tr>
         </table>
```

If we search with "Naveen" its showing the row which is good, but when we search with attributes like "nani005" or "12" also its showing the row which we feel it as difficult.

**Comment by wenzhixin** [comment]
Same with #1148

**Comment by naveenkumart** [comment]
Sorry wenzhixin for disturbing you, but it didn't solved my issue. I want to explain the issue again in a clear way:
1) It was correctly searching the data from table
2) But the problem is along with the data that we can see in cells of table, it was also searching inner a, id attributes values data which I don't want.
3) In a single sentence what I want is to search only the data user can see on table and not the inner content of table that can't be seen

Please provide me the solution for this, because I am trying for the whole day and couldn't find the right one.

**Comment by wenzhixin** [comment]
This example can not solve your problem?http://jsfiddle.net/wenyi/e3nk137y/2430/

**Comment by naveenkumart** [comment]
Yes, example which you suggested was totally different from what we need. We don't want to disable search for columns and at the same time it must not search inner attribute values.

Thank you

**Comment by wenzhixin** [comment]
OK, can you provide a jsfiddle to show your problem

**Comment by naveenkumart** [comment]
Here is <a href="https://jsfiddle.net/naavin005/mnmhuu38/8/">my fiddle</a>, if you search for the word "sensor", which is not in the table's visible content but it is there inside of td anchor data attribute, considered as a filterable value and filtering data. 
I looked into bootstrap-table.js file there ur searching the input string with the JSON data and filtering the table. But in our scenario that would be an error because we need to consider only the table's view data.

Thank you

**Comment by djhvscf** [comment]
I think this is not an issue, because if we follow the steps that @naveenkumart said, we are getting data after search "sensor" but this is because we are searching in the anchor html code... I think you can use the strictSearch table option in order to get the correct result.

**Comment by rodi189** [comment]
Somebody have a solution for filter the html inside "<td>" like in editable cell: "<a href="javascript:void(0)" data-name="pagina-3-1" data-pk="undefined" data-value="SOME INFO" class="editable editable-click">SOME INFO</a>"? is annoying when you search "data" and search function read "data" inside all the rowsc
