### ISSUE TITLE
editable select-box bigger than popup

### ISSUE THREAD

**Issue by docholiday** [wenzhixin/bootstrap-table#1159]
Hi wenzhixin,

the possibility to have select-boxes within editable fields is really great!
I have one issue however: If my text is too long, the select-field itself is bigger than the editable popup.
Is it possible, that the popup always uses the size of the selectfield-text plus the 5 or so px on each side as border?

**Comment by wenzhixin** [comment]
I think you can set the options of x-editable: http://bootstrap-table.wenzhixin.net.cn/extensions/#table-editable-column-options

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
