### ISSUE TITLE
Bootstrap Table with Static content

### ISSUE THREAD

**Issue by wirthual** [wenzhixin/bootstrap-table#1160]
Hello, great library! Its so great i really want to use it. But i cant load any data.json from a webserver, i have to use a static table coded by myself in html.

When i try to use bootstrap-table on this table:
      <table data-toggle="table" data-height="299" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1">
      	<tr data-index="0">
      		<td>Table Cell</td>
      		<td>Table Cell</td>
      		<td>Table Cell</td>
      		<td>Table Cell</td>
      		<td>Table Cell</td>
      	</tr>
      </table>

Then i get this error: Uncaught TypeError: Cannot read property 'field' of undefined

Is it possible to use bootstraptable with static content?

**Comment by wirthual** [comment]
Ok it is probably because i missed the table header. I think this fixed it. But now I have problems with styling. My table looks like this:

![screenshot from 2015-07-10 21 05 25](https://cloud.githubusercontent.com/assets/2640499/8626864/6c33a6d2-2747-11e5-8623-b5054ea84aa7.png)

**Comment by wirthual** [comment]
Ok I wrote your Readme now. I will provide a jsFiddle. Sorry for that.

**Comment by wenzhixin** [comment]
Here is an example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-html.html

**Comment by wirthual** [comment]
Issue can be closed. This behaviour is when you dont include the bootstrap css file. Sorry for that.
