### ISSUE TITLE
Populate manually dropdown options

### ISSUE THREAD

**Issue by moerg** [wenzhixin/bootstrap-table#1161]
I use the filter-control plugin and I would to know if it's possible to **manually populate the select options** in the JSON result from remote-url **instead of the plugin using the table data to pulate itself**? The reason is that if we show 10 rows and we don't have any result to show for the specified filter, we cannot filter the column, we **must** load more data in order to see the options.

**Screen shot 1:** 10 rows loaded (options not generated, because they weren't found in the last query)
![image 29](https://cloud.githubusercontent.com/assets/10135983/8810409/e2464bf4-2fbc-11e5-81f0-cf4105ce892f.png)

**Screen shot 2:** 25 rows loaded (options generated, because they were found in the last query)
![image 32](https://cloud.githubusercontent.com/assets/10135983/8810408/e244c018-2fbc-11e5-8671-3c083a755581.png)

**Comment by dabros** [comment]
@moerg - can you please clarify the options you are using for your table?

Most importantly, if this is default behaviour for client-side OR server side queries (how are you getting your data), whether pagination and any relevant filterControl settings.

I havent worked with new filterControl code, but may be able to work on a fiddle if you provide one - if it is a limitation then it is an interesting and hopefully easy problem to solve, which someone can hopefully make a pull request of too.

**Comment by djhvscf** [comment]
You can use the filterData option in order to load the option with an URL

**Comment by moerg** [comment]
@djhvscf do you have any example of *filterData* use? I don't see anything about that in the current doc.

@dabros I load data server-side. The dropdown options come from server-side query. The problem is I limit result to fit data into one page (LIMIT 10). So if I don't have all options in the first page, I cannot select them in the dropdown. In order to see all available options, I **must** display/load all data, this is not the wanted behaviour.

For example: My dropdown has those options: 'Apple', 'Banana', 'Orange'
I load the first 10 rows. In those returned rows, I have only 'Apple' available. But in my table I also have 'Banana' and 'Orange', which can be seen in next pages, because of the LIMIT.
The filter seem to be filled with **showed** data/data in the current page. I want to see all available options, despite of the fact that they are not necessarily in the first page.

**Comment by dabros** [comment]
@djhvscf can maybe help more, but i found referance to a values in index in one of the two filter extensions:

http://bootstrap-table.wenzhixin.net.cn/extensions/#table-filter

Table Filter
Use Plugin: bootstrap table filters
https://github.com/lukaskral/bootstrap-table-filter


The other filter plugin is:

Table Filter Control
Use Plugin: bootstrap-table-filter-control 
Dependence if you use the datepicker option: bootstrap-datepicker v1.4.0
 https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/filter-control

**Comment by dabros** [comment]
@moerg - any update on this?

**Comment by vicentor** [comment]
I believe that @moerg uses the **Table Filter Control** plugin.

The issue seems to be about the plugin not supporting the server-side implementation of Bootstrap-table very well. It's built on the client-side, so the available filters are the ones from the first page only.

Is there any detailed documentation of it somewhere?

**Comment by dabros** [comment]
@wenzhixin @djhvscf - can you help answer that?

**Comment by moerg** [comment]
You're right @vicentor.

**Comment by knoguchi** [comment]
Please see http://stackoverflow.com/questions/30845271/bootstrap-table-filter-control-extension-populating-select-with-complete-list-of

**Comment by djhvscf** [comment]
Thanks @knoguchi for your help! I will add this documentation for filter-data

**Comment by djhvscf** [comment]
Close this issue because we provided an answer
