### ISSUE TITLE
Compatibility with Bootstrap Switch

### ISSUE THREAD

**Issue by itverico** [wenzhixin/bootstrap-table#1163]
Hello, 

First of all, I really like your bootstrap-table.
However, there's one conflict with Bootstrap Switch(http://www.bootstrap-switch.org/) that I'm having a trouble with.

When you try to use Bootstrap Switch styled input checkbox/radios within bootstrap-table, the functionality gets broken. I was able to apply the Bootstrap Switch CSS style with animation, but functions such as "Check all" doesn't work. It seemed as if any input checkbox/radio buttons applied with the bootstrap-switch code get ignored by bootstrap-table.

I used this to apply the style.

$('.bs-checkbox [type="radio"], .bs-checkbox [type="checkbox"]').bootstrapSwitch({
					onColor: 'primary',
					radioAllOff: true,
					onText: "<i class='icon-checkmark'></i>",
					offText: "<i class='icon-checkmark2'></i>"
				});

Any help/hint would be appreciated.

Thanks.

**Comment by wenzhixin** [comment]
Please provide a jsfiddle to show your problem, that will save our time.

**Comment by itverico** [comment]
Sorry for the late reply.

Here's the codepen.
http://codepen.io/anon/pen/NqMEYG

As you can see, checkall button doesn't work. (buttons are missing icons on codepen.)

If I apply the bootstrapswitch function to the show/hide column selector checkboxes, that function gets broken too.

Thanks.

**Comment by itverico** [comment]
I've decided to take out bootstrap-switch function. But any option to style the input checkbox/radio in the future release would be nice.
