### ISSUE TITLE
Refresh method removes checkbox status

### ISSUE THREAD

**Issue by dbaileychess** [wenzhixin/bootstrap-table#1164]
Calling the refresh method on a table wipes out the 'checked' status of checkboxes.

    var $table = $('#results');
    setInterval(function() {
        $table.bootstrapTable('refresh', {silent: true});
         }
        , 2500)

    <table data-toggle='table' data-url='some-url' id='results'>
     <thead>
      <tr><td data-field='state' data-checkbox='true' /></tr>
     </thead>
    </table>

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/search?q=maintain&type=Issues
