### ISSUE TITLE
Silently sorting with serverside pagination

### ISSUE THREAD

**Issue by marcel-k** [wenzhixin/bootstrap-table#1166]
Hi,

I just started using bootstrap-table and i think its great. easy to use while still providing lots of customization.

i'm using serverside pagination and i was just wondering if it is possible to let the user sort the columns 'silently', as in without the 'loading please wait message' popping up. It seems you can only silently load data with the refresh function.

thx in advance

**Comment by djhvscf** [comment]
Sure it is a good feature.. Any pull request is welcome
