### ISSUE TITLE
Check/Uncheck All in all pages

### ISSUE THREAD

**Issue by kikonjar** [wenzhixin/bootstrap-table#1167]
Hi,
I need to know how can I check o uncheck all rows (in all pages, not just the current one). The actual checkbox control that check/uncheck all rows just work withe the rows from the current page. The methods checkAll and uncheckAll works in the same way.

Regards.

**Comment by wenzhixin** [comment]
Added example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/1167.html

**Comment by nngochue** [comment]
Hi wenzhixin, 

Does it work with paging server-side mode? I try but it does not work.

**Comment by arthipesa** [comment]
IMHO, it should be working just fine with any type of paging.

**Comment by The-Phi** [comment]
It's not working with the server side.
 
Here's how the example linked above by @wenzhixin  works:

1) it toggles off the pagination.
2) select everything
3) toggle on the pagination.

So of course with the server side it doesn't work (the server has no way to know which rows were selected). 

I will try to create a workaround server-side: the server needs to store a list of all the selected rows. I think about cookies which may be the easier.

**Comment by nngochue** [comment]
Hi The-Phi,
Solution [here](https://github.com/wenzhixin/bootstrap-table/issues/3445)

**Comment by andersonralves** [comment]
> Added example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/1167.html

with bootstrap 3 not working

**Comment by abryzgin** [comment]
Hello, example: [1167](http://issues.wenzhixin.net.cn/bootstrap-table/#issues/1167.html) does not work

**Comment by wenzhixin** [comment]
In our latest version, we have rename maintainSelected to [maintainMetaData](https://bootstrap-table.com/docs/api/table-options/#maintainmetadata), I have updated the example: https://examples.bootstrap-table.com/#issues/1167.html to work well now, thanks for your feedback @abryzgin.

**Comment by abryzgin** [comment]
@wenzhixin, now, when I upgraded to version 15.2, the export to excel with exportDataType='selected' became incorrect

**Comment by UtechtDustin** [comment]
@abryzgin Please open a new issue and provide us an example (using our online editor), dont post it on closed issues with a other topic.
