### ISSUE TITLE
Date filter not working 

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1169]
http://jsfiddle.net/wenyi/e3nk137y/2435/

Hi the above link working fine but in my local not getting filter {} parameter but event is firing please tell me how to fix it and tell me all exact versions of js files that support date filter...

Thank you..

**Comment by dabros** [comment]
@faruk77  Im really not sure what the problem is, thats not your fiddle as no problem i can see...

Please provide more info and a fiddle showing Your code - we need that

**Comment by dabros** [comment]
@faruk77 - please refer to #1126 and provide fiddle and more information

**Comment by djhvscf** [comment]
The example is working, if this issue is not solved reopen it again @faruk77
