### ISSUE TITLE
calling function

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1170]
Hi have written a function it is not calling while using column hide/show please tell how to run script while using show column/hide options.

First time the script is loading fine but after using show/hide dropdown script is not calling please tell me how to fix...

**Comment by dabros** [comment]
@faruk - look at the events in http://bootstrap-table.wenzhixin.net.cn/documentation/#events - you just need to find relevant callback

And please do include more info with your posts - a fiddle is easy to setup once then just branch if needed for a different problem. Far easier for people without code in front of them setup like your situation (that they can easily branch themselves)

**Comment by dabros** [comment]
@faruk77 - please refer to #1126 and provide fiddle and more information

**Comment by djhvscf** [comment]
Provide a fiddle please, that will save our time. @faruk77

**Comment by wenzhixin** [comment]
any update?

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
