### ISSUE TITLE
show-columns and sortable create an error

### ISSUE THREAD

**Issue by itverico** [wenzhixin/bootstrap-table#1173]
Hello,

When removing a column with an active sort function, only th column is removed and not the body td.

http://codepen.io/anon/pen/pJKERW

* Remove Company column. Only TH column is removed. This is true for any column with an active sort.

Any idea why this is happening?

Thanks.

**Comment by djhvscf** [comment]
That example is not working.. Provide a new one please @itverico

**Comment by wenzhixin** [comment]
any update?

**Comment by itverico** [comment]
Sorry, I've switched to DataTable, as I wasn't able to make your solution work on the project.
Thanks for the follow up though. I'll give your solution another try for my other projects.

**Comment by djhvscf** [comment]
Ok, thanks, @itverico
