### ISSUE TITLE
Toggling drag&drop with Reorder Row Extension

### ISSUE THREAD

**Issue by maxelle** [wenzhixin/bootstrap-table#1174]
Hi i'm trying to toggle drag & drop feature refreshing option reordableRows.

Works well when I pass from false to true
$('#tbLive').bootstrapTable('refreshOptions',{reorderableRows: true});

Seems does not work when pass from true to false
$('#tbLive').bootstrapTable('refreshOptions',{reorderableRows: false});
No errors happen, simply drag & drop remains active

Thanks Max

**Comment by djhvscf** [comment]
Working on it @maxelle

**Comment by dabros** [comment]
@djhvscf - is this issue solved now?

**Comment by djhvscf** [comment]
This issue should be fixed, if not please reopen it.@maxelle
