### ISSUE TITLE
searching disables jquery event listeners

### ISSUE THREAD

**Issue by ajendrex** [wenzhixin/bootstrap-table#1177]
Hello,

I have the following html:

```
  <body>
  <div class="tab-content col-md-12">
        
  <div id="toolbar">
  </div>
  <table class="table" data-toggle="table" data-height=500 data-search="true" data-toolbar="#toolbar" data-show-export="true">
    <thead>
      <tr>
        <th>Región</th>
        <th>Provincia</th>
        <th>Comuna</th>
        <th>Sucursal</th>
      </tr>
    </thead>
    <tbody>   
        <tr class="danger">
          <td>Valparaiso</td>
          <td>San Antonio</td>
          <td>Algarrobo</td>
          <td><b>Portugal de Correos de Chile:</b> Alameda 111111 <a class="cboxiframe" href="/ventas/envios_sucursal/1">ver envíos</a></td>
        </tr>    
    </tbody>
  </table>
      </div>
    <script type="text/javascript">
      $(document).ready(function(){
        $(".cboxiframe").colorbox({iframe:true, innerWidth:"80%", innerHeight:"80%"});
      });
    </script>
    
    
  </body>
```
so, when user clicks on "ver envíos", a colorbox modal shows. However, if I search an item (in this case, If I just type "Val" in order to get the single item as a result), after the search method works, then clicking on "ver envíos" again will open link on the main window (colorbox will not work). This also happens with other third party javascripts, such as those provided by django inplace-edit.

**Comment by wenzhixin** [comment]
Check this: https://github.com/wenzhixin/bootstrap-table/search?q=post-body&type=Issues&utf8=✓

**Comment by dabros** [comment]
@ajendrex - as wenzhixin said, look at the post-body event handler, as documented in http://bootstrap-table.wenzhixin.net.cn/documentation/#events

That link he gave you shows all issues related to this, so should have plenty of examples of similar and maybe example of exactly what you need
