### ISSUE TITLE
getRowByUniqueId方法报错

### ISSUE THREAD

**Issue by aiien007** [wenzhixin/bootstrap-table#1179]
我看到文档里面有这个方法，但是例子中却没有
var ss = $('#user_table').bootstrapTable('getRowByUniqueId', "1")
报错内容：Error: Unknown method: getRowByUniqueId
使用的版本是v1.8.1 - 2015-05-29
请问是什么原因

**Comment by aiien007** [comment]
解决了 min 和dist下的js都未加入这个方法
另：这个uniqueId指的是什么？ 试了数据中的id字段以及行的索引都获取不到内容

**Comment by wenzhixin** [comment]
设置 `uniqueId` 属性就可以了。

**Comment by aiien007** [comment]
还是有点不明白 这是例子 Example: $('#myTable').bootstrapTable('getRowByUniqueId', "122") ;
难道就需要在初始化的时候加入 uniqueId :"122"？
那么每个row不都是122了嘛？

**Comment by wenzhixin** [comment]
这里跟 idField 一样是填写 field 的，例如你的数据： [{id: 1, name: '123'}, {id: 2, name: '234'}]，那你可以设置为  uniqueId: 'id'
