### ISSUE TITLE
Is it possible to resize table header?

### ISSUE THREAD

**Issue by Jithinsiva** [wenzhixin/bootstrap-table#118]
hi, 

Bootstrap-table project is really good. welldone :)

I'm going to use it with "x-editable" ( another plugin) . So that it will become an editable datatable.
but when I enter data with "x-editable" in "bootstrap-table", columns width are changing and  the table headers width remains same. 

Here is test link:
http://qdemo.edualert.in/firmloop-v2.0/Resources/table-test/employees-test.html 

please double click on the [enbable/disable] button and check the table and see "superuser" link is now ediable and see the missmatch of table header and table content.  I want to change table headers width with table contents. Can u help me on this please?

before:
![before](https://cloud.githubusercontent.com/assets/8907116/4398663/22cd03b4-445b-11e4-8de4-8e1cde109b7e.png)

after:
![after](https://cloud.githubusercontent.com/assets/8907116/4398665/2975cb9c-445b-11e4-8199-2b5fb71f6e36.png)

see the missmatch of table header and table content?

I know its not your problem. but i'm asking a help.  

x-editable jsffidle: http://jsfiddle.net/xBB5x/63/

Quick reply will be appreciated because, my project deadline is coming close. I'm a UX Designer not much familiar with javascript and jQuery. I just copy paste things from jsfiddle and documents ;) so, give me jsfiddle if possible.

 ALSO i want to auto start table without click on starttable button. now i'm using this method:
$(document).ready(function(){
 $('.start-example').trigger('click');
});

**Comment by Cure100061148** [comment]
@wenzhixin  sorry, I ran into the same issue. Sorry that I don't really understand. Can you explain solutions to this problem again? Thank you!

I think you can use the popup mode to avoid this problem.
If you use inline mode you can use resetView method to resize the table header.
You can activate bootstrap table just only to set data-toggle="table" on your table. Usage docs

**Comment by Jithinsiva** [comment]
Use resetView

something like this:

 $('.bootstrap-table a').on('hidden', function() {
    $('#table-pagination').bootstrapTable('resetView');
});
