### ISSUE TITLE
Grouped Tableheader

### ISSUE THREAD

**Issue by liKe2k1** [wenzhixin/bootstrap-table#1180]
When i try this:

```javascript
columns: [
	[
		{
			title: 'Reportname',
			rowspan: 2,
			align: 'center',
			valign: 'middle'
		}
	], [
		{
			field: 'report_id',
			title: 'Report-Id',
			sortable: true,
			align: 'center'
		},
		{
			field: 'display_name',
			title: 'Reportname',
			sortable: true,
			align: 'left'
		}
	]
]
```

I get a blank 2 columned table without content and table headers.

Whats wrong with this?

**Comment by ayuha406645** [comment]
use src/bootstrap-table.js
do not use dist/bootstrap-table.js

and the two js code is different, but version is the same??
hope the author check synchronization :)

**Comment by liKe2k1** [comment]
Thanks! =)

**Comment by djhvscf** [comment]
Close this issue @liKe2k1
