### ISSUE TITLE
editable with select doesn't show correct value on page load

### ISSUE THREAD

**Issue by docholiday** [wenzhixin/bootstrap-table#1181]
Hi there,

I'm not sure why, but other than in this example (http://issues.wenzhixin.net.cn/bootstrap-table/#issues/986.html) I don't get the correct value to show as selected. Instead all editable select fields show only  "Empty" until I click on them to select another value (regular editable fields work fine).

In the source code it says "undefined" under data-value und data-pk. When I click on the select field, I get all possible values listed correctly however.

Editable fields without select work as expected.

In your example you use "static" data within the Javascript. I use data from remote using the url-parameter. Could that be the problem?

**Comment by docholiday** [comment]
Any help / idea here?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
