### ISSUE TITLE
How to reapply bindings after ajax call.

### ISSUE THREAD

**Issue by Cowdrey** [wenzhixin/bootstrap-table#1183]
I am pulling in a another table with an ajax call, and want to reapply bindings. I got most the functionality working by just running  
```javascript 
$.getScript("../Scripts/bootstrap-table.js");
```
This same method did not work on the .js files for reorder-columns.

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle to show your problem?

**Comment by Cowdrey** [comment]
Fixed my problem. I was pulling in the table in a partial view and wasn't applying any of my javascript at all. I just rendered the javascript on the partial view and then when the ajax pulled it in it worked fine.
