### ISSUE TITLE
怎么延迟加载数据？

### ISSUE THREAD

**Issue by penweizgx** [wenzhixin/bootstrap-table#1186]
$('#XX').bootstrapTable()在页面先定义好，先不加载数据，然后再根据查询条件动态加载数据

**Comment by wenzhixin** [comment]
用 load 方法，http://issues.wenzhixin.net.cn/bootstrap-table/#methods/load.html （提 issue 前看下文档或者例子，谢谢）

**Comment by wenzhixin** [comment]
文档在这里：http://bootstrap-table.wenzhixin.net.cn/documentation/#methods
