### ISSUE TITLE
Drag Feature

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1187]
Hi,

Please tell me how to drag row from one bootstrap table to another bootstrap table..

**Comment by dabros** [comment]
As far as im aware this is not a standard feature at all

So i would recommend one or both of the following:

1. Describe your use case?

Please describe the use case in detail, and maybe a simple "custom column" with an action button titled "transfer" (or something else entirely) might solve this for you - we cant say if its really needed if no context at all


2. If you still want it, help set it up a little

There are jquery plugins related to this, but dragging between tables is not common use case, and as this is open-source with other pending tickets, i doubt main developer will want to add such complexity.

If you wanted this feature the best thing would be pull request of at least functional (if not ideal) implementation. 

A jsfiddle might be nice to help anyone else play with this - make a fiddle with 2 tables using bstable at top then 2 tables using drag&drop plugin below it (but no bootstrap-table). Then see yourself if easy to integrate, or if anyone else has other ideas.

I only searched for a min, but this one was only one with obvious example showing between tables

http://johnny.github.io/jquery-sortable/

**Comment by dabros** [comment]
@faruk77 - please refer to #1126 and provide fiddle and more information

**Comment by wenzhixin** [comment]
:+1: @dabros

**Comment by wenzhixin** [comment]
Do not support this feature, close it.
