### ISSUE TITLE
Header shows twice in IE8 

### ISSUE THREAD

**Issue by Psihobolt** [wenzhixin/bootstrap-table#1188]
Hello.
In IE8 header shows twice. 
![img](https://cloud.githubusercontent.com/assets/13366217/8724078/55ef9b5c-2bd8-11e5-802a-9f148235dd0e.jpg)

What I need to do?

**Comment by vsalbuq** [comment]
Did you linked `bootstrap-table.css` ?

**Comment by Psihobolt** [comment]
Yes

**Comment by vsalbuq** [comment]
Bootstrap needs ```html5shiv.js``` to work properly in ie8. Did you linked it?

**Comment by Psihobolt** [comment]
Yes, I linked html5shiv,but it did not help

**Comment by Psihobolt** [comment]
This effect is observed when I set a fixed height

**Comment by Psihobolt** [comment]
If you analyze that hidden behind the header, there is a message about loading data

**Comment by vsalbuq** [comment]
I'm sorry, I don't know what else it can be. I've had the same issue, and in my case it was css problem. Since you've linked `bootstrap.css`, `bootstrap-table.css`, `bootstrap.js`, `bootstrap-table.js` and `html5shiv.js`, I don't know.

**Comment by Psihobolt** [comment]
very sorry :-( can anyone has idea?

**Comment by Psihobolt** [comment]
@wenzhixin help me, please!

**Comment by Psihobolt** [comment]
@wenzhixin You will not help me advice?

**Comment by wenzhixin** [comment]
I want to help, but now I don't have an IE browser to test this issue.

**Comment by Psihobolt** [comment]
I found a place where because of what the table fork. But I can not find where is set. In general, the problem is that when you create a table incorrectly determined margin-top table with the class "table table-hover". There's a fixed value? -25px ???

**Comment by Psihobolt** [comment]
@wenzhixin The first image header table forks, and the second is not, if you manually change the value. Tell me where can I find more?

![first-example](https://cloud.githubusercontent.com/assets/13366217/10665879/db07de8a-78d6-11e5-8561-90610ce246dd.jpg)
![second-example](https://cloud.githubusercontent.com/assets/13366217/10665887/e26246ca-78d6-11e5-9321-5c9ee8f75324.jpg)

**Comment by Psihobolt** [comment]
@wenzhixin  I found where to fix it. and then just I noticed that you have version 1.9.0.0 to fix it. I'm sorry to trouble you. Thread can be closed
