### ISSUE TITLE
麻烦作者重新打个all.min.js包

### ISSUE THREAD

**Issue by linziguan** [wenzhixin/bootstrap-table#1189]
在all.min.js或者all.js中没找到RefreshOptions方法，但在src中能找到。希望作者能整合一下。

**Comment by wenzhixin** [comment]
dist 下的代码一般发布 release 才更新，你可以 git clone 代码，然后自己运行 grunt 就可以了：http://bootstrap-table.wenzhixin.net.cn/getting-started/#compiling-css-and-javascript

**Comment by linziguan** [comment]
刚看到了，原来是在新版本中才有。还有，希望作者提供一方法，用于在设置了query后，后面的分页里也带上query的查询参数。某则在点击下一页时，query里的参数就没了。

**Comment by wenzhixin** [comment]
你设置 queryParams 就可以了哦
