### ISSUE TITLE
How to add an ID to the "tr" ?

### ISSUE THREAD

**Issue by zagloo** [wenzhixin/bootstrap-table#119]
Hello,

How can I do that please ?
In Symfony Twig I tried that :

```
{% for tuto in categorie.tutoriels %}
    <tr class="{{ (tuto.ID) }}">
        <td>Bob</td>
    </tr>
{% endfor %}
```

But the class not appear in my html... why ?

**Comment by gudbergsen** [comment]
How to set this ID from a URL source?

Agree with Sopamo - keep all data-* attributes will be good - and set them all from JSON

**Comment by wenzhixin** [comment]
OK, I will consider that feature. Added as a new issue.

**Comment by ParthTandel** [comment]
I am dynamically trying to add new row to my table. The code i wrote works fine but the classes don't gets added if some one could please help me with this .

**Comment by ParthTandel** [comment]
function(){
var newRow = jQuery('<tr><td class="stock_name">'+text1+'</td><td class = "stock_ticker">' +text2+'</td><td class="hit_value">'+text+'</td><td><button class = "btn btn-danger" onclick="remove_watchlist(this);">Delete</button></td></tr>');
jQuery('table#watch_list').append(newRow);
            }
