### ISSUE TITLE
Is it possible to add a hyperlink to a <tr> or a <td> somehow? 

### ISSUE THREAD

**Issue by chickenorbeef** [wenzhixin/bootstrap-table#1191]
I'm using json data to populate the table. Any ideas?

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/search?q=hyperlink&type=Issues&utf8=%E2%9C%93

**Comment by chickenorbeef** [comment]
So if I use this:

```
<th data-field="id" data-formatter="otherIdFormatter"></th>
```
and this:
```
function otherIdFormatter(value) {
    return '<input value="' + value + '" />';
}
```
how do I add the inputted value to the JSON object? Sorry if this is a silly question.

**Comment by wenzhixin** [comment]
`otherIdFormatter(value, row)`, use the row parameter.
