### ISSUE TITLE
`updateSelected()` traversing too far, hit performance

### ISSUE THREAD

**Issue by stalinone** [wenzhixin/bootstrap-table#1192]
`updateSelected()` use `$.parents()` to add or remove `selected` class on parent `<tr>`. I thought it would be more optimizing if we use `$.closest()` instead since what `<tr>` we concerned is the direct parent of the checkbox?

Shown as fiddle: http://jsfiddle.net/qdywt77g/ . The response time of any click is ~1sec on my PC (Win7, i7-3770, Chrome 43). (I purposely add `<form>` into parent DOM since it drastically drive down the performance for some reason...)

**Comment by djhvscf** [comment]
Yes, you're right.. Let me change that and test it.. @stalinone
