### ISSUE TITLE
Problem with large data

### ISSUE THREAD

**Issue by skoushlendra** [wenzhixin/bootstrap-table#1195]
Hiii,

I'm using the bootstrap table and it's working fine for hundreds of records but when I tried with bulk record 20000, 50000 and 100000 it takes few secods to load and that is fine for me but searching, sorting and pagination is too slow and sometimes even the page become un responsive.

Kindly suggest me the solutions, my data is returning from the server and I'm client side pagination.

**Comment by dabros** [comment]
I cant really help with this myself i think, but might help if you share your settings and one of the data-rows, as well as info like if formatters and ect applied

A fiddle with a subset of that data would prob be best

**Comment by wenzhixin** [comment]
I think you need to change to server side pagination in your case @skoushlendra.

**Comment by dabros** [comment]
@wenzhixin - i was thinking that too, but there may still be obvious reason for significant performance drop, or at the very least we can rule that out with more info

@skoushlendra  - i do still recommend fiddle or at least description and copy+paste code so we can see what the data is and how your presenting it - but there is a practical limit

You have ruled out data-load itself (open new tab, F12 then see result time from directly hitting data-url) - so if just searching there maybe some tweaks, but likely it would end up being more efficient to send to server-side filtering

**Comment by skoushlendra** [comment]
The problem with the configuration of the system, when I enhanced the configuration it works fine.

**Comment by ninoNinkovic** [comment]
@skoushlendra what configuration? What did you do to help performance? I have the same issue.

**Comment by skoushlendra** [comment]
@ninoNinkovic  Increased the RAM on server

**Comment by abazanvillanueva** [comment]
@skoushlendra , sorry for the question but,do you think RAM is the solution for the long time JSON parsing from server to js via $AJAX, too?
