### ISSUE TITLE
重新打包后Unknown method: getSelections

### ISSUE THREAD

**Issue by linziguan** [wenzhixin/bootstrap-table#1196]
重新打包（使用grunt）后，使用getSelections，提示Unknown method: getSelections。
在打包前是可以使用的。
grid.bootstrapTable("getSelections");

**Comment by linziguan** [comment]
初始化之后 $.fn.bootstrapTable.methods 的前两个由原来的'getOptions', 'getSelections'变成了
'collapseAll', 'expandAll'

**Comment by linziguan** [comment]
应该是
$.extend($.fn.bootstrapTable.methods, [
        'collapseAll',
        'expandAll'
    ]);
这一句代码造成的。

**Comment by wenzhixin** [comment]
哪里？

**Comment by linziguan** [comment]
是group-by插件引起的，上面那句代码会将$.fn.bootstrapTable.methods里的前两个覆盖成'collapseAll',
'expandAll'。
