### ISSUE TITLE
在使用getRowByUniqueId时

### ISSUE THREAD

**Issue by linziguan** [wenzhixin/bootstrap-table#1197]
在使用getRowByUniqueId时,如果查不到数据，应该返回空，但却返回bootstrap-table对象，原因是以下这一句引起的。
return typeof value === 'undefined' ? this : value;

**Comment by linziguan** [comment]
将dataRow ，初始定义为null则可以解决。
BootstrapTable.prototype.getRowByUniqueId = function (id) {
        var uniqueId = this.options.uniqueId,
            len = this.options.data.length,
            dataRow = null,

**Comment by wenzhixin** [comment]
谢谢，已修复改问题
