### ISSUE TITLE
Is there a way to select active row from the code?

### ISSUE THREAD

**Issue by RedPointMS** [wenzhixin/bootstrap-table#1198]
Hi,

I am trying to set an active row from the code. It sort of works when I use `checkBy` with one of the fields being checkbox. Unfortunately as soon as I make this field not visible, the `checkBy` function has no effect on the row.
Any other way I could set a row as active?

**Comment by dabros** [comment]
@RedPointMS - never used it myself, but go to http://bootstrap-table.wenzhixin.net.cn/documentation/ and ctrl+F for "selected", there are methods for retrieving selected rows

not sure if that quite fits your situation but http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getSelections.html shows it off.

Can you please explain your use case more and ideally provide a fiddle if this doesnt help you?

**Comment by RedPointMS** [comment]
@dabros thank you for taking time and looking into this. I spent some time already going through documentation and trying various methods but none worked so far. I might be missing something obvious.
The basic use case here is to show to the user which row is currently selected. The selection of active row happens in the code rather than by the user clicking on the row. So this is opposite to - for example - `getSelections`, I am looking for a method like `setSelection` but cannot find anything close to such functionality. The workaround that I found that might work was:

1. Creating additional  check column 
2. using `checkBy` method in the code with a field value that matches the row that I want to select. This selects the row and highlights it

The problem with the above solution is that I cannot show checkbox column to the user as it becomes confusing. The obvious solution would be to change property of the check column `visible: false`, but then the row stops being highlighted by `checkBy`. 
I will try to create a fiddle later today to illustrate this.

**Comment by dabros** [comment]
@RedPointMS - im looking foward to the fiddle

It actually sounds like you want to do something i did in a bit hackish way for a project i was prototyping

We went with WPF desktop application in the end, so i never got round to doing any pull request or the like, but i did share detailed info in #725 and a working fiddle that prob is what you need

tbh i cant recall at which point i shared the code, but i did create in the end a fully functioning GetRowByItemId and introduced the 'activeRow' concept into the code, which i persisted through all relevant functions and used callbacks to persist even after refresh and sorting of table data.

As i say in the links somewhere, i changed core code and heavily modded - not ideal - but the concept is sound, just needs to be integrated to be used without rendering the plugin un-updatable.

Please do checkout that topic and others i link to in the posts there, and then assess carefully if you actually **do** need that particular approach - if you do then hopefully you have time to mod it as an extension or the like

**Comment by RedPointMS** [comment]
@dabros - here is the fiddle: http://jsfiddle.net/RedPointMS/r3r06o41/ 

I emulate the selection of the row in the code by implementing the button on the top. When you click on it, the `checkBy` finds the row and highlights it. So far so good. However, if you set the first column "state"  `data-visible:false` you will see the that it stops working. Theoretically the column still exists there so it should be possible to set values to it, but it does not highlight the row any more.

The #725 is what I am looking for, but indeed this is quite significant change and unfortunately I don't have enough JS skills to finish it :( . I thought that I was missing something obvious, if there is function `getSelections` I thought that there would be something like `setSelections`. That's unfortunate, and I presume you don't know about any other work around?

Thanks for your help anyway.

**Comment by dabros** [comment]
@RedPointMS - i cant do much debugging without full working copy, might get to that later though - but i strongly suspect its something to do with the $selectedItem variable in bootstrap-table.js:

```javascript

        this.$selectItem = this.$body.find(sprintf('[name="%s"]', this.options.selectItemName));

/// ...

    BootstrapTable.prototype.updateSelected = function () {
        var checkAll = this.$selectItem.filter(':enabled').length ===
            this.$selectItem.filter(':enabled').filter(':checked').length;

        this.$selectAll.add(this.$selectAll_).prop('checked', checkAll);

        this.$selectItem.each(function () {
            $(this).closest('tr')[$(this).prop('checked') ? 'addClass' : 'removeClass']('selected');
        });
    };

```

Maybe by disabling it visually it makes that :enabled filter return false. 

You can see here that its using that $selectItem element at each index (after filtering for enabled and checked values) to apply the 'selected' class.

Thats also interesting as it shows that you could also maybe workaround by just adding the class="selected" in click.row or similar, but thats pretty much what i did in #725, so nothing much new, and better to integrate with singleSelection and checkBy i think, keep it simple.

I gota have dinner soon, so will look during my break then - if you can change your fiddle to be programmatic initialization and expose the onCheck event, we can see if thats triggered on row selection when the column is hidden, and i can add in other callbacks to help debug

**Comment by dabros** [comment]
I raised it in edit, but worth repeating - if you style with radio, and that checkBy works - whats wrong with that?

If that answers your use case then great

**Comment by RedPointMS** [comment]
@dabros Sorry for late reply, I was tied up this morning. I updated fiddle with `onCheck` event which proves that it works with both visible and invisible column.
You are right about the radio button - not ideal but better than the checkbox. I agree with you that amount of effort to fix this issue doesn't justify the aesthetics, will have to live with this.
Again thank you very much for your help
