### ISSUE TITLE
Filter-control plugin overriden?

### ISSUE THREAD

**Issue by moerg** [wenzhixin/bootstrap-table#1202]
I use bootstrap-table **V1.8.1**.

I initialize bootstrap-table that way:
![image 37](https://cloud.githubusercontent.com/assets/10135983/8810532/8c7b16e0-2fbd-11e5-8fcb-e43479ca2e71.png)

I use with bootstrap-table the *filter-control* extension to filter table data.

I looked at the doc about *queryParams*. According to my understanding, *queryParams* sends **additionnal** parameters to specifed URL.

So if I apply a filter (from extension mentionned above) then use *queryParams*, I am supposed to have two kind of parameter (1: *filter-control extension*, 2: *queryParams*).

After a check, I only have *queryParams* sent to my URL, I don't have any from the *filter-control extension*.

It seems that *queryParams* override or cancel the applied filter.

Did I miss something?

**Comment by moerg** [comment]
BUMP

**Comment by djhvscf** [comment]
Ok, I think this can be a new feature in our extension... Please remember that any pull request is welcome

**Comment by moerg** [comment]
@djhvscf any update on this?

**Comment by vicentor** [comment]
I think that giving more control over the SELECT values *could* help avoid many problems such as this one: https://github.com/wenzhixin/bootstrap-table/issues/1161

**Comment by djhvscf** [comment]
This issue is fixed in the 2.1.0 version of filter-control
