### ISSUE TITLE
Get row value on click. 

### ISSUE THREAD

**Issue by silentgrave** [wenzhixin/bootstrap-table#1204]
Hi 
I'm trying to get me back from the table the value of a hidden column but can not figure out how. Does anyone have any ideas?
Thanks a lot

**Comment by vsalbuq** [comment]
Since you haven't provided any code, suppose you've put a button with `.edit` class in the last column. This is what you would do:

```javascript
window.handlers= {
    'click .edit': function editar(e, value, row, index) {
        console.log(row.hiddenColumn);
    }
}

$('#table').bootstrapTable({
    url: 'data.json',
    method: 'get',
    columns: [{
        field: 'hiddenColumn',
        title: 'hiddenColumn',
        visible: false
        }, {
        field: 'column',
        title: 'column',
        events: handlers
    }]
});

```

This means `row` is an object with all columns, and the name you've given to your fields is the name you must use to get the value you want.

**Comment by dabros** [comment]
@silentgrave - please share a fiddle or at least context as to what user or program action needs this retrieved, and how its used?

You can use singleSelection and getSelections http://bootstrap-table.wenzhixin.net.cn/documentation/ to answer this, the fiddle in #1198 might be what your looking for - just 'fork' that if it is, add whatever other code you have that relates, then share here with clarification on context pls

**Comment by wenzhixin** [comment]
Have you solved your problem? If not reopen this issue and provide a jsFiddle to show what you want, thanks.

**Comment by silentgrave** [comment]
hi! i solved my problem, thanks!
