### ISSUE TITLE
Dynamic select

### ISSUE THREAD

**Issue by dzmitry-masko** [wenzhixin/bootstrap-table#1205]
Hi! There is a small problem. How to use a dynamic select? All lines can be different choices.

{
    field: 'class',
    sortable: true,
    align: 'center',
    editable: {
        type: 'select',
       source: "??????"
        },
    },

{"total":1,"rows":
[{"id":1,"date":"2015-07-25","datetime":"2015-07-25 \u0432 08:00","class":
[{"id":1,"address":"Petra str. 11"}}]
}]}

![image](https://cloud.githubusercontent.com/assets/11837753/8844790/ad475482-3121-11e5-840e-8a4f81873e4f.png)

**Comment by dabros** [comment]
@dzmitry-masko - ive looked at this on 3 different days and still dont understand what it is you want.

Please clarify the problem and what you are trying to achieve, a fiddle would also be ideal as then we can easily mockup solutions for you.

Thanks

**Comment by archerchiu** [comment]
@dzmitry-masko would you want to have different options in each cell on the same column?

**Comment by dzmitry-masko** [comment]
Yes. I realized it, but without tableeditor.
