### ISSUE TITLE
Bootstrap Loading please Wait

### ISSUE THREAD

**Issue by ezazwar1** [wenzhixin/bootstrap-table#1206]
Thanks For Bootstrap Table
Well What i actually do is refresh the data when user clicks on select options  with id of the option and its working fine but when there is no data in one of the option then it continues to show loading please wait.... i tried echoing null when data is empty but still nothing is happening can u please help me fix this issue what i want is to show database is down and unable to connect message but it continues to show loading please wait
![image](https://cloud.githubusercontent.com/assets/13368631/8849513/ef1ab610-315d-11e5-88e2-6ab6485ef9f0.png)

**Comment by wenzhixin** [comment]
You need to return [] instead of null.

**Comment by ezazwar1** [comment]
echoed [] but still showing the same result
loading please wait

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle to show the problem?

**Comment by ezazwar1** [comment]
well i guess i cant help you with that well if you want to see the code i will share it with you 
![image](https://cloud.githubusercontent.com/assets/13368631/8871234/70f28a9c-3211-11e5-92b7-9b4235316f1d.png)
when runnng normal shows output perfectly json  snap included
![image](https://cloud.githubusercontent.com/assets/13368631/8871315/0b79b770-3212-11e5-8c0a-7fe362b0c8f6.png)
when nothing to display json output is 
![image](https://cloud.githubusercontent.com/assets/13368631/8871346/3f95cbc0-3212-11e5-8aa5-230c5a574e50.png)

**Comment by ezazwar1** [comment]
i got it right but it is taking time saying loading please wait for about 15 seconds can i somehow minimize this time

**Comment by wenzhixin** [comment]
```php
echo json_encode(array());
```

**Comment by wenzhixin** [comment]
Use F12(Chrome) to debug your server response.

**Comment by ezazwar1** [comment]
i hope i am not bothering you much today but when i do it via the url the result is pretty fast and the console shows following error
![image](https://cloud.githubusercontent.com/assets/13368631/8871986/21abe66c-3217-11e5-8f97-bb124e230a77.png)

**Comment by ezazwar1** [comment]
anyways i guess my database is actually taking time to connect sorry for wasting your time 
anyways thanks for the help

**Comment by ezazwar1** [comment]
i have issue #1207  pending can you help me with that
thanks again

**Comment by ks1sodge** [comment]
Hi, I have the same problem but with server-side-pagination. So for that returning "[]" won't work as it only removes pagination buttons etc. The old data is still being displayed. What would be the equivalent for returning empty results while having server-side-pagination? 

I tried this one in C#:  `return Content("{\"total\": 0,\"rows\":[]}");`

But then it shows "Loading please wait ...".

Best regards
