### ISSUE TITLE
Is it possible to load bootstrap-table with data from the Model?

### ISSUE THREAD

**Issue by kwingat** [wenzhixin/bootstrap-table#1211]
I've been trying many variations of this but I can't get anything to work. I just get nothing.

![image](https://cloud.githubusercontent.com/assets/12445390/8910209/788cab68-3453-11e5-8515-c44f59ba48e0.png)

![image](https://cloud.githubusercontent.com/assets/12445390/8910216/85adc174-3453-11e5-9b5b-0cb786f11f41.png)

![image](https://cloud.githubusercontent.com/assets/12445390/8910277/d6a11c0c-3453-11e5-80eb-8a66bfd72061.png)

![image](https://cloud.githubusercontent.com/assets/12445390/8910285/e174d484-3453-11e5-936f-76d640550673.png)

**Comment by thantthiri** [comment]
Yes. You can return from model.  please use, Javascriptserializer and assign the value "Data" inside the model .
![controller](https://cloud.githubusercontent.com/assets/13266414/8925759/1b4c80a0-353d-11e5-9f13-bc242d988431.JPG)
![view](https://cloud.githubusercontent.com/assets/13266414/8925760/1b4dc582-353d-11e5-9143-0160490f6bfb.JPG)

**Comment by kwingat** [comment]
What I was doing was mostly correct. What I was doing wrong was using <td> tags instead of <th>. I'll never get those 8hrs back.
