### ISSUE TITLE
[QUESTION] Is it possible to do a colspan in the header?

### ISSUE THREAD

**Issue by rogelio-blanco** [wenzhixin/bootstrap-table#1212]
I have I table that I load with values from the server, I would like to do a colspan ONLY in the header but I still want to load the two columns separated.   In the example below, I would like that "sale" and "id" get combined in the header but separated in the body of the table.

Is it possible?

        <table id="referencesTable" data-toggle="table"
            data-classes="table table-borderless table-condensed table-hover"
            data-side-pagination="server" data-pagination="true"
            data-page-list="[5, 10, 20]">
            <thead>
                <tr>
                    <th data-field="sale" data-align="center"></th>
                    <th data-field="id" data-align="center">#</th>
                    <th data-field="createdAt" data-align="center">Dummy</th>
                    <th data-field="sourceType" data-align="center">Dummy2</th>
                </tr>
            </thead>
        </table>

**Comment by wenzhixin** [comment]
Yes, there is an example here: http://issues.wenzhixin.net.cn/bootstrap-table/#options/group-columns.html

**Comment by rogelio-blanco** [comment]
Thanks for the link, however I still have a question related with that example, is it possible to hide the Item Name and Item Price?   So, I show see in the header only Item Detail and Item ID ?

**Comment by wenzhixin** [comment]
You can add css style to hide them:
```html
    <table id="table"
               data-toggle="table"
               data-url="../json/data1.json">
            <thead>
            <tr>
                <th colspan="2">Item Detail</th>
                <th data-field="id" rowspan="2" data-valign="middle">Item ID</th>
            </tr>
            <tr style="display: none">
                <th data-field="name">Item Name</th>
                <th data-field="price">Item Price</th>
            </tr>
            </thead>
        </table>
```

**Comment by rogelio-blanco** [comment]
:+1:
