### ISSUE TITLE
Missing possibility to put custom header rows or column controls.

### ISSUE THREAD

**Issue by qwiglydee** [wenzhixin/bootstrap-table#1213]
I need to put custom filter controls to some of columns.
The only way I figured out is to markup header manualy, like this:
```html
<table id="grid">
    <thead>
        <tr>
            <th class="field-name">Клиент<br/>
                <input class="form-control" name="name">
            </th>
            <th class="field-region">Регион<br/>
                <select name="region">
                    <option value="">*</option>
                </select>
            </th>
            <th>
                <br/>
                <button class="btn btn-default" type="reset" title="сброс фильтра">
                    <i class="glyphicon glyphicon-asterisk"></i>
                </button>
            </th>
        </tr>
    </thead>
</table>
<script>
$("#grid").boostrapTable({ /* all the options */ })
</script>
``` 
But this breaks all behaviour that relies on titles.
Is there any other way to achieve the same?

**Comment by djhvscf** [comment]
You can use the filter-control extension in orider to achieve that.. See http://bootstrap-table.wenzhixin.net.cn/extensions/#table-filter-control and this http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html

**Comment by qwiglydee** [comment]
the filter-control does not allow to use custom inputs, but only 2 types of predefined 
(and 'select' input could not work with ajax-provided data)
