### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prop' of undefined

### ISSUE THREAD

**Issue by ztx1491** [wenzhixin/bootstrap-table#1214]
Uncaught TypeError: Cannot read property 'prop' of undefined

this.$selectAll.prop is undefined

this.$selectAll.prop('checked', this.$selectItem.length > 0 &&
            this.$selectItem.length === this.$selectItem.filter(':checked').length);

code : 
    
   bst = $('#query_grid').bootstrapTable({
            url: '${ctx}/app/query/queryData',
            method: 'POST',
            queryParams: initQueryParams,
            toolbar: '#toolbar',
            singleSelect: true,
            /* striped: true, */
            pagination: true,
            height: gheight - 120,
            width: gwidth - 45,
            pageSize: ${size},
            pageList: [${size}],
            sidePagination: 'server',
            showMultiSort: true,
            contentType: "application/x-www-form-urlencoded",
            showColumns: true,
            showRefresh: true,
            showToggle: true,
            /* showPaginationSwitch: true, */
            cardView: true,
            checkboxHeader: true,
            mobileResponsive: true,
            clickToSelect: true,
            showExport: true,	//支持导出
            exportTypes: ['json', 'xml', 'csv', 'png', 'doc', /* 'powerpoint', */ 'pdf', 'txt', 'sql', 'excel'],
            columns: [frozenColumns.concat(columns)],

![Uploading QQ截图20150727144006.png…]()
![Uploading QQ截图20150727144131.png…]()

**Comment by ztx1491** [comment]
<script src="extensions/mobile/bootstrap-table-mobile.js"></script>
是这个插件造成的，我去掉就没问题了，但是在拖动表格滚动条时会报下面的错误：
Uncaught TypeError: Cannot read property 'showFooter' of undefined

**Comment by ztx1491** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>Mobile</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="resources/js/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="resources/js/bootstrap-table/1.8.1/bootstrap-table.min.css">
    <script type="text/javascript" src="resources/js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="resources/js/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="resources/js/bootstrap-table/1.8.1/bootstrap-table.js"></script>
    <script src="resources/js/bootstrap-table/1.8.1/extensions/mobile/bootstrap-table-mobile.js"></script>
</head>
<body>
<div class="container">
    <h1>Mobile</h1>
    <table id="table"
           data-toggle="table"
           data-show-columns="true"
           data-search="true"
           data-url="data1.json"
           data-mobile-responsive="true"
           data-check-on-init="true"
           data-pagination="true"
           data-side-pagination="client"
           data-height="300"
           data-page-list="[10, 25, 50, 100, All]">
        <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="id" data-sortable="true">ID</th>
            <th data-field="name" data-sortable="true">Item Name</th>
            <th data-field="price" data-sortable="true">Item Price</th>
        </tr>
        </thead>
    </table>
</div>
</body>
</html>

**Comment by ztx1491** [comment]
resources/js/bootstrap/3.3.5/css/bootstrap.min.css
    resources/js/bootstrap-table/1.8.1/bootstrap-table.min.css
   resources/js/jquery-1.11.0.min.js"
   resources/js/bootstrap/3.3.5/js/bootstrap.min.js"
   resources/js/bootstrap-table/1.8.1/bootstrap-table.js"
    resources/js/bootstrap-table/1.8.1/extensions/mobile/bootstrap-table-mobile.js"

<div class="container">
    <h1>Mobile</h1>
    <table id="table"
           data-toggle="table"
           data-show-columns="true"
           data-search="true"
           data-url="data1.json"
           data-mobile-responsive="true"
           data-check-on-init="true"
           data-pagination="true"
           data-side-pagination="client"
           data-height="300"
           data-page-list="[10, 25, 50, 100, All]">
        <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="id" data-sortable="true">ID</th>
            <th data-field="name" data-sortable="true">Item Name</th>
            <th data-field="price" data-sortable="true">Item Price</th>
        </tr>
        </thead>
    </table>
</div>

**Comment by wenzhixin** [comment]
showFooter 的问题已经解决了，另外 mobile 的问题希望可以提供 jsFiddle 运行例子。

**Comment by ztx1491** [comment]
这个问题已经改好了，bootstrap-table-mobile.js 这个插件没问题：
fitHeader 这个方法里面的代码我改了下，就可以了。
// horizontal scroll event
        // TODO: it's probably better improving the layout than binding to scroll event
        this.$tableBody.off('scroll').on('scroll', function () {
            that.$tableHeader.scrollLeft($(this).scrollLeft());

            //if (this.options.showFooter && !this.options.cardView) {//被修改的代码，this换成that
            if (that.options.showFooter && !that.options.cardView) {
                that.$tableFooter.scrollLeft($(this).scrollLeft());
            }
        });

**Comment by wenzhixin** [comment]
OK
