### ISSUE TITLE
Add fix table scroll error: Uncaught TypeError: Cannot read property 'showFooter' of undefined

### ISSUE THREAD

**Issue by ztx1491** [wenzhixin/bootstrap-table#1216]
this.$tableBody.off('scroll').on('scroll', function () {
            that.$tableHeader.scrollLeft($(this).scrollLeft());

            if (this.options.showFooter && !this.options.cardView) {
                that.$tableFooter.scrollLeft($(this).scrollLeft());
            }
        });

next line: 
if (this.options.showFooter && !this.options.cardView) { 
instead:
if (that.options.showFooter && !that.options.cardView) {

**Comment by wenzhixin** [comment]
Thanks, have fixed this bug.
