### ISSUE TITLE
Cookie extension not working

### ISSUE THREAD

**Issue by xfanwu** [wenzhixin/bootstrap-table#1217]
I am using BT plugin for my project's back-office which running Ruby on Rails. 
The table loads JSON data and pagination from server side. 

The basic features of the table work perfectly but I need the Cookie extension to do the job easier.

I followed [this example](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/cookie.html) to use the extension but it don't write any cookie into my browser(I am sure the browser's cookie is enabled and JS files are loaded). 

I tried to do this from server side:
Assign a local variable to get current page position and load it after each render the document. It works when I refresh the page but not work for the "go back" of "go forward" because it will not trigger the Rails's "render" function so that my view could not find the latest value of page position. After that I decide to do this on client side and I found this extension is exactly what I need. 

Here is a part of the code in my view. Do I miss anything?

```erb
<table id="product_table" class="bootstrap-table" data-toggle="table" data-url="<%= products_path(format: :json) %>"
                                                   data-cookie="true"
                                                   data-cookie-id-table="saveId"
                                                   data-show-columns="true"
                                                   data-search="true"
                                                   data-show-toggle="true"
                                                   data-pagination="true"
                                                   data-side-pagination="server"
                                                   data-sort-name="name"
                                                   data-formatter="operateFormatter"
                                                   data-table="products">
                                                   <thead>
                                                     <tr>
                                                       <th data-field="name" data-sortable="true"><%= t('activerecord.attributes.product.name') %></th>
                                                       <th data-field="barcode" data-sortable="true"><%= t('activerecord.attributes.product.barcode') %></th>                                             
                                                       <th data-field="operate" data-formatter="operateFormatter" data-events="operateEvents"></th>
                                                     </tr>
                                                   </thead>
</table>
```

**Comment by wenzhixin** [comment]
I have tried the extension in server side and it is working well. So I don't know what cause your problem, may be you can debug the code.

**Comment by xfanwu** [comment]
@wenzhixin Thank you for replying soon. I spent a lot of time to do that but still no chance. I am now sure that I miss something. 

Could you please show me your example?

**Comment by xfanwu** [comment]
Finally I found the solution:

In table attribute, instead of 
```html
data-cookie-id-table="saveId"
```
I need to add 

```html
data-state-save="true",
data-state-save-id-table="WhatEverIdForSaveState"
```

However, I found this in [StackOverflow](https://stackoverflow.com/questions/29492470/how-to-save-visible-column-state-in-bootstrap-table-toolbar). The weird thing is the official [example](http://bootstrap-table.wenzhixin.net.cn/extensions/) do not works for me, even I copy-paste the code for testing. 

Anyway thank you very much @wenzhixin .

**Comment by djhvscf** [comment]
You are not using the latest version of cookie extension.. Please double check

**Comment by xfanwu** [comment]
Thank you @djhvscf You are right!

After a check I am currently using the extension v1.1.0 but the latest is v1.2.0

Actually I have installed the extension by using [Rails Assets](https://rails-assets.org/) and include the components the Rails' way, like this:

```ruby
//= require bootstrap-table/extensions/cookie/bootstrap-table-cookie
```

But apparently this only include the file in ```bootstrap-table/dist/cookie``` but not in ```bootstrap-table/src/cookie``` which is the latest version.

**Comment by wenzhixin** [comment]
Updated the example: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html.

**Comment by xfanwu** [comment]
However, I am curious why the extension's version of  ```src``` and ```dist``` are not identical.

In ```dist/extensions/cookie/```
the ```bootstrap-table-cookie.js``` and ```bootstrap-table-cookie.min.js``` files are also different.

**Comment by JintomonSunny** [comment]
Hi All , can you guys tell me what wrong i am doing  ?
because when i add the cookie data is not populating to table . 

My Code
 
/* Scripts */ 
<script src="~/assets/bootstrap-table/src/bootstrap-table.js"></script>
<script src="~/assets/bootstrap-table/src/extensions/export/bootstrap-table-export.js"></script>
<script src="~/assets/bootstrap-cookie/bootstrap-table-cookie.js"></script>
<script src="http://rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js"></script>

/*HTML*/
 <table id="exmtbl" class ="table-sm table-responsive table-condensed"                                         
                                           data-search="false"
                                           data-show-refresh="true"
                                           data-show-toggle="true"
                                           data-show-columns="true"
                                           data-show-export="true"
                                           @*exportTypes='{"sql" "excel"}'*@
                                           data-detail-view="false"
                                           data-detail-formatter="detailFormatter"
                                           data-show-pagination-switch="false"
                                           data-pagination="true"
                                           data-id-field="REQUESTID"
                                           data-page-list="[10, 25, 50, 100, ALL]"
                                           data-show-footer="false"
                                           data-side-pagination="server"
                                           data-url="@Url.Action("Crfdata", "Request")"
                                           data-response-handler="responseHandler"
                                           data-cookie="true"
                                           data-cookie-id-table="usedIDUserCookie123">

**Note *: If i am not adding these two lines data is populating fine and i can perform all other features.**
data-cookie="true"
data-cookie-id-table="usedIDUserCookie123"
