### ISSUE TITLE
while moving data server side pagination not working

### ISSUE THREAD

**Issue by santoshch** [wenzhixin/bootstrap-table#1219]
Hi
   While moving  some of the rows from one table to another table server side pagination is not working in first table.
do you have any support on this?

**Comment by wenzhixin** [comment]
Server side pagination need to retrurn data for example:
`{total: 800, rows: []}`

http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html

**Comment by santoshch** [comment]
it doesn't move  all rows in all pages when select the checkAll checkbox,it selects current page rows only.
after moving the rows from first table to another table ,even the first table  having rows in next pages not loading...showing empty records message..not updated the table.

**Comment by santoshch** [comment]
look at this example once ,this is the scenario,
do the following to get the issue: 1.select checkAll checkbox,2.click on delete button
actually it will load the next page rows,but here showing empty records after removing current page rows 
http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by wenzhixin** [comment]
This is not a problem, because our example is a mock data, data is not saved in database. You need to refresh the table manually after removing rows.
