### ISSUE TITLE
分页高度如何自适应

### ISSUE THREAD

**Issue by aiien007** [wenzhixin/bootstrap-table#1220]
表格有12条数据 每页显示10条 
点击第一页 显示了10条数据，表格占满了
点击第二页 显示了2条数据，表格在分页栏间存在一大片空白
请问可以做到分页栏与数据之间的不留空白吗？
谢谢啦

**Comment by wenzhixin** [comment]
这是个新需求，与 #410 相同，关闭这个。

**Comment by tingwei628** [comment]
Hey, I have the same problems, too. Thanks!
