### ISSUE TITLE
Possible bug when you would like to use colspan in header

### ISSUE THREAD

**Issue by rogelio-blanco** [wenzhixin/bootstrap-table#1224]
Please check #1212

**Comment by wenzhixin** [comment]
The filed row must be rowspan="1".

**Comment by rogelio-blanco** [comment]
Hi,

Thanks for the response; however I still getting the same issue.   When I look at the html source code, I can see that there is like 2 <tr> with the same information.  Could you please take a quick look of it

**Comment by wenzhixin** [comment]
What problem do you say? Is there a jsFiddle? @rogelio-blanco

**Comment by rogelio-blanco** [comment]
Let try to get an example, I'll be back with it

**Comment by wenzhixin** [comment]
Any update?

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels

**Comment by keval47** [comment]
# ### [_``_](`

- 

- [ ] 1. url

`)
