### ISSUE TITLE
data-footer-formatter example

### ISSUE THREAD

**Issue by jcpy** [wenzhixin/bootstrap-table#1225]
Can you give us a data-footer-formatter example here please? http://jsfiddle.net/L6tm1tt3/

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/639.html

**Comment by jcpy** [comment]
Thanks!

**Comment by jcpy** [comment]
thanks!

2015-07-29 3:41 GMT-04:00 文翼 <notifications@github.com>:

> Closed #1225 <https://github.com/wenzhixin/bootstrap-table/issues/1225>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wenzhixin/bootstrap-table/issues/1225#event-368062258>
> .
>



-- 
Juan Carlos López
