### ISSUE TITLE
how to use ajax abort method

### ISSUE THREAD

**Issue by ezazwar1** [wenzhixin/bootstrap-table#1227]
actually i am using the bootstrap table with collaboration with a select which refreshes the table data of the bootstrap table on change of the select option the issue is when on one select it takes time to compete the request and suddenly if i change the select option then on first the data is shown correctly and when first request sends the response the table is overwritten by the old response 

now what i want is to remove all previous requests like using the abort method is there an easy way out 

![image](https://cloud.githubusercontent.com/assets/13368631/8954454/53d4e720-3603-11e5-9cb7-d7cedf8b4e4e.png)

**Comment by wenzhixin** [comment]
I think you needn't use abort method, when you changing the select, you juse need to update the table.
BTW, if you don't what I mean, you can provide a jsFiddle and I will show you how.

**Comment by ezazwar1** [comment]
actually my database i am connecting with is running within intranet i had the same issues with google charts and i did the abort thing and my problem got fixed

**Comment by Claudioln** [comment]
Could you explain how I can get the ajax object for aborting it?
When user typing slow, a lot of ajax request are made, so I want to abort previous requests.
Thanks in advance.

**Comment by wenzhixin** [comment]
Great @ezazwar1, close the issue.
