### ISSUE TITLE
some issues in bootstrap-table-export.js

### ISSUE THREAD

**Issue by yishuluo** [wenzhixin/bootstrap-table#1228]
I used this plugin with django platform.it works well.
When i add i18n for django,then changes webpage language from English to Chinese.It doesn't work.If webpage language back to English,it works well again.
the error is in JQuery.base64.js line 136:throw "INVALID_CHARACTER_ERR: DOM Exception 5";

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/search?q=export&type=Issues&utf8=✓
