### ISSUE TITLE
there is no way to clear a search from javascript

### ISSUE THREAD

**Issue by dvelayos** [wenzhixin/bootstrap-table#1230]
fiddle: https://jsfiddle.net/e3nk137y/2561/

(put something on the search input, press the reset search button, the input search is cleared and the table is refreshed, but no data is shown; tried with 'refresh' and 'refreshOptions').

EDIT: On my custom page, passing all the config with the searchText='' and search=false, and repeating it with search=true, works. (i do it twice changing the search because the searchText is already "" and there is no refresh if there is no change on the options)

**Comment by dabros** [comment]
@dvelayos - can you please clarify if your fiddle includes this workaround, or if the workaround is sufficient, or if issue still exists?

Im pretty tired atm, cant quite tell from your description

thanks

**Comment by wenzhixin** [comment]
Added resetSearch method to reset the search text, you can use like: 
```js
$table.bootstrapTable('resetSearch');
// or
$table.bootstrapTable('resetSearch', 'something');
```
