### ISSUE TITLE
getRowByUniqueId returns unexpected result 

### ISSUE THREAD

**Issue by qwiglydee** [wenzhixin/bootstrap-table#1231]
when nonexiistend rpw is requested, the method returns undefined, and jluery-plugin wrapper returns jquery objects itself, which is quite not what expected instead of datum

**Comment by wenzhixin** [comment]
Sorry, I don't know what you mean.

**Comment by qwiglydee** [comment]
try request row that does not exist in loaded data.
expected result: 
undefined or null
actual result: 
jquery object

**Comment by wenzhixin** [comment]
Can you provide a jsFIddle?

**Comment by qwiglydee** [comment]
https://jsfiddle.net/qwiglydee/gzf5tkho/3/
(result is in debug console)

**Comment by qwiglydee** [comment]
I guess the right way is to make all methods like get/set be not chainable. 
They should apply to first element

**Comment by wenzhixin** [comment]
Update to return `null` to fix this bug.
