### ISSUE TITLE
Translating "Ascending" and "Descending" strings into other languages (in multiple-sort extension)

### ISSUE THREAD

**Issue by mands72** [wenzhixin/bootstrap-table#1234]
Hi there,
I'm looking for a way to translate the words "Ascending" and "Descending" on the multiple-sort into other languages. Using the locales-files I was unable find how to do it. Is there any known way to translate this two values?

Thanks! :-)

**Comment by jtrumbull** [comment]
@mands72

The variable `sort_order` (which defines "Ascending" and "Descending"), is privately declared within multi-sort's anonymous wrapper, so cannot be modified outside of the source. These appear to be the only values _not_ defined in the [locales](http://bootstrap-table.wenzhixin.net.cn/extensions/#table-multiple-sort-locales) -which means it may not be an oversight and that the values may have been intended as international. Any insight @dimbslmh ?

For the interim, below are a couple patches / work-arounds.

<h1>Patch / work-around</h1>

_I typically create a `*.patch.js` (for development) when working with third-party libraries, then bundle with the source as `*.patched.min.js` (for production), to account for any unsupported features and/or open issues._

_In this case, my `bootstrap-table-multiple-sort.patch.js` would reflect one of the following, depending on the situation._

<h2>Option 1: Extend the locales</h2>

This approach adds `formatAscending()` and `formatDescending()` to the locale settings. However, as mentioned above, `sort_order` is not publically accessible, so we need to redefine it inside of the `addLevel()` method -which unfortunately entails copying the entire method.

```javascript
(function ($) {
  'use strict';

  $.extend($.fn.bootstrapTable.locales, {
    formatAscending : function () { // Add formatAscending to locale settings
      return "Ascending";
    },
    formatDescending : function () { // Add formatDescending to locale settings
      return "Descending";
    }
  });

  $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales); // Add to defaults

  var BootstrapTable = $.fn.bootstrapTable.Constructor; // Get the Constructor

  BootstrapTable.prototype.addLevel = function (index, sortPriority) {
    var $sortModal = $("#sortModal"),
    text = index === 0 ? this.options.formatSortBy() : this.options.formatThenBy(),

    // =====================================
    // This is the only modification ----->
    // =====================================
    sort_order = {
      asc : this.options.formatAscending(),
      desc : this.options.formatDescending()
    };
    // =====================================
    // <------------------------------------
    // =====================================

    $sortModal.find('tbody')
      .append($('<tr>')
      .append($('<td>').text(text))
      .append($('<td>').append($('<select class="form-control multi-sort-name">')))
      .append($('<td>').append($('<select class="form-control multi-sort-order">'))));

    var $multiSortName = $sortModal.find('.multi-sort-name').last(),
    $multiSortOrder = $sortModal.find('.multi-sort-order').last();

    this.options.columns.forEach(function (column) {
      if (column.sortable === false || column.visible === false) {
        return true;
      }
      $multiSortName.append('<option value="' + column.field + '">' + column.title + '</option>');
    });

    $.each(sort_order, function (value, order) {
      $multiSortOrder.append('<option value="' + value + '">' + order + '</option>');
    });

    if (sortPriority !== undefined) {
      $multiSortName.find('option[value="' + sortPriority.sortName + '"]').attr("selected", true);
      $multiSortOrder.find('option[value="' + sortPriority.sortOrder + '"]').attr("selected", true);
    }
  };

})(jQuery);
```
Now you can add `formatAscending` and `formatDescending` to your locales file -or somewhere in your app like this:
```javascript
$.extend($.fn.bootstrapTable.defaults, {
  formatAscending : function () {
    return "восходящий";
  },
  formatDescending : function () {
    return "нисходящий";
  }
});
```
And a working jsFiddle: http://jsfiddle.net/joeycakes/jn3p3w2o/

<h2>Option 2: Modify the generated html</h2>

```javascript
(function($) {
  
  'use strict';

  var BootstrapTable = $.fn.bootstrapTable.Constructor,  // get BootstrapTable Constructor
    _init = BootstrapTable.prototype.init; // get init method
    
  BootstrapTable.prototype.init= function() {

    // Call the super method first, so the needed DOM elements exist
    _init.apply(this, Array.prototype.slice.apply(arguments));

    // Overwrite the option tag's inner-html to reflect your desired locale
    $('.form-control.multi-sort-order > option[value=asc]').html('восходящий');
    $('.form-control.multi-sort-order > option[value=desc]').html('нисходящий');

  };
    
})(jQuery);
```
And a working jsfiddle: http://jsfiddle.net/joeycakes/4vsh00zk/

**Comment by djhvscf** [comment]
This sample is working as expected: http://jsfiddle.net/joeycakes/jn3p3w2o/

If this is not your solution, please open again this issue. @mands72
