### ISSUE TITLE
Table header is not resize as per the table width while resizing

### ISSUE THREAD

**Issue by skoushlendra** [wenzhixin/bootstrap-table#1235]
Please refer to the link http://rawgit.com/skoushlendra/POCPrototype/master/WebContent/bootstrap-table.html take some time to load the data.

While hiding the left and right navigation the table is expanded but the alignment of the thead is not appropriate with respect to the rows. The borders were not aligned vertically or the cell of thead.

Grid refresh is required to solve this, but I don't want to refresh the grid for this because in my case the data will be load from the database which will increase the load.
Kindly help me on the same.

![thead problem on bootstrap](https://cloud.githubusercontent.com/assets/4067793/8982482/6cec5ad6-36df-11e5-8da7-b00e3dd518a5.png)

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/faq

**Comment by skoushlendra** [comment]
??

**Comment by wenzhixin** [comment]
You need to use resetView method when resize the window.
