### ISSUE TITLE
[Solved] Loading data with double quotes

### ISSUE THREAD

**Issue by Juiza** [wenzhixin/bootstrap-table#1237]
Hi,
I'm using bootstrap-table plus the extension x-editable. Everything is working fine. The only problem I've is when I'm trying to retrieve information from mysql using this code:
```
    <?php
    require("../util/common.php");

    $dbname = $_GET['dbname'];
    $table = $_GET['table'];

    $stmt = $db->prepare("SELECT * FROM `$dbname`.`$table`");
    $stmt->execute();

    echo json_encode($stmt->fetchAll());
    ?>
```
When i've a field with a double quote in, the content is trimmed on the first double quote (").
The json printed is correctly escaped (\").

Thank you for any help!

**Comment by dabros** [comment]
Can you please include an excerpt from the json_encode result?

Ive had no issue with complex strings in this plugin myself, but i know in past ive had to take extra care to prep some json_encode results when passing to ajax - double escaping can be an issue.

A fiddle taking this input (just as a string, not needing actual url) would be ideal - that way we can play with responseHandler or something similar if needed.

thanks

**Comment by Juiza** [comment]
The thing is working correctly, the problem is that in the cell it creates a link <a href where data-value = "value  "other value" other value " and the content is just value. 

There the json_encode result:
 [{"ID":"1","Safe":"S1","Bits":"B1 ","Type":"Type \"hello\" ","Test":"Test \"hello\"","User":"-","Port":"-   ","Loops":"1","Result":"1","Expected result":"Result \"hello\"","Comments":"Comment \"hello\"","Date":"2015-07-31","Firmware":"Fw1","Hardware":"Hw1"}]

The values in the table are trimmed just before the hello word.

**Comment by dabros** [comment]
The front page of this repo has a link to a fiddle you can use as a template:

https://github.com/wenzhixin/bootstrap-table#reporting-issues

Please use that as template and fork a jsfiddle that shows what you mean, as i really dont know how it is creating a link with broken content, that just sounds you need a formatter tweak or maybe base code limitation - malformed html???

Please put the plugins and settings into the fiddle, using a url or just a string like what you shared

Thanks

**Comment by Juiza** [comment]
http://jsfiddle.net/wogdxrhm/

Is not working, it doesn't make the cell editable even if I've imported everything. 

If you can fix it you shall see my problem, I hope.

**Comment by dabros** [comment]
@Juiza, NP - its usually something simple enough in hindsight.

Please update the title to include [solved] and close this topic.

Thanks
