### ISSUE TITLE
Unable to Export data correctly with pagination (Plugin extension)

### ISSUE THREAD

**Issue by quchie** [wenzhixin/bootstrap-table#1242]
Hi,

I am trying to implement selection on table then export it. The selection will also have fixes from issue #197 which keeps the selection after clicking next page.

But i cant seem to get the correct export data. By the way, the getAllSelections() will always returned selected data on the current page although you have selected something on the previous page.

Here are the sample fiddle:
http://jsfiddle.net/4r6g4cfu/90/

**Comment by wenzhixin** [comment]
I think we need to handle it in server side pagination.

**Comment by geasi** [comment]
I have this problem too in server side pagination.

**Comment by wenzhixin** [comment]
Merged.
