### ISSUE TITLE
How to set radio button after data load

### ISSUE THREAD

**Issue by haideraliarain** [wenzhixin/bootstrap-table#1243]
Hi,
I am loading data remotely and i want to set the radio button true for one record, i tried to use event "load-success.bs.table" but have no idea how to set radio button true.

**Comment by wenzhixin** [comment]
You can use `post-body.bs.table` event and `check/checkBy` method to do that: http://bootstrap-table.wenzhixin.net.cn/documentation/#events

**Comment by haideraliarain** [comment]
Thanks
