### ISSUE TITLE
bootstrap 的model框里使用bootstraptable的样式问题

### ISSUE THREAD

**Issue by bluee00** [wenzhixin/bootstrap-table#1245]
接着 #1118 的问题，如https://jsfiddle.net/k3duj988/ 例子里一样，模态框里一开始加载的表格的高度和它刷新后的高度不一致，我只能在$(function(){})里初始化table，而且如果这么设置：
```javascript
$('#manageListModal').on('shown.bs.modal', function () {
    	$('#manage_list_table').bootstrapTable('resetView');
});
```
的话，刚开始加载是高度一致了，但是刷新的时候太慢了，用户能看到页面模态框的高度变短的过程，我想问一下有更加优化的方案吗？

**Comment by wenzhixin** [comment]
暂时没有其他方案

**Comment by bluee00** [comment]
它高度为什么开始的时候和刷新的时候不一样呢？

**Comment by wenzhixin** [comment]
开始的时候表格是隐藏的（display: none），所以计算的 dom 的高度为 0，或者你可以考虑不设置 height

**Comment by bluee00** [comment]
不设置高度也一样，还是高度不一致

**Comment by bluee00** [comment]
这是我使用的方式不对吗？

**Comment by wenzhixin** [comment]
具体没有测试过，一般情况下建议弹出 modal 后再初始化 table，应该就正常了

**Comment by bluee00** [comment]
主要是这个表格是在另一个表格的一列里点击详情展示出来的，如果弹出在初始化，就每次都是第一次初始化的值了，再也不变化了
