### ISSUE TITLE
带checkbox的表格使用搜索功能后，checkbox中的value丢失，变成false

### ISSUE THREAD

**Issue by gx0803** [wenzhixin/bootstrap-table#1246]
带checkbox的表格使用搜索功能后，checkbox中的value丢失，变成false，导致筛选特定项目后提交到后台无法获取选中项的值，处理失败

**Comment by wenzhixin** [comment]
例子是可以的：http://issues.wenzhixin.net.cn/bootstrap-table/，你可以提供下 jsFiddle 展示的问题吗

**Comment by gx0803** [comment]
例子中我发现checkbox没有设置value，所以看不出问题， jsFiddle展示的问题是什么问题？
	     $.post(
	    		 url,
	  		    {"status":status,"excludePlanId":excludePlanId},
	  		    function(data){
	  		    	//$("#"+status+"_div").html(html);
				    $('#'+tableId).bootstrapTable({
				        data: data,
				        idField:id,
				        uniqueId:id,
				        pagination:true,
				        pageSize:5,
				        pageList:[5],
				        search:true,
				        clickToSelect:true,
				        undefinedText:"",
				        selectItemName:id       
				    });	  		    	
	                $("#main_div>div").hide();
	                $("#"+status+"_div").show();	  		    	
	  	},'json'); 
我这里的idFiled是变量，因为页面是三个tab页，每个tab页都是一个table，id的的name属性不一样，所以会有条件判断idFiled的最终写法。同时指定id对应的列显示为checkbox，如下：
 <th data-field="projectid"  data-checkbox="true"></th>
但是发现使用了搜索以后，过滤出来的记录中checkbox的value为"false"，并且清楚搜索条件value依然是false。没有使用一次搜索前，checkbox都有值。

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by gx0803** [comment]
是在项目开发中使用的，这个bug非常严重，不但搜索以后的checkbox没有值，翻页以后的checkbox也没有值了，时间很紧，暂时没有时间使用jsFiddle来调试了。。。

**Comment by wenzhixin** [comment]
网站的例子是可以的，假如没有运行的环境，那要怎么调试呢？又怎么查找问题所在？

**Comment by wenzhixin** [comment]
已经给了三个 jsFiddle 的模板，一般改一下，使用模拟数据就可以了。很想帮你，但是一个是没有那么多时间，一个是我自己还有事情要做。

**Comment by wenzhixin** [comment]
根据你说的测试了下：http://issues.wenzhixin.net.cn/bootstrap-table/ ，没有出现 checkbox 为 false 的情况。

**Comment by wenzhixin** [comment]
请问解决问题了吗，假如还没解决的话请提供可运行代码，然后重新 open 该问题，谢谢。
