### ISSUE TITLE
Bug with pagination in IE8

### ISSUE THREAD

**Issue by Psihobolt** [wenzhixin/bootstrap-table#1248]
I have bootstrap table
```
<table class="main-table"
           data-toogle="table"
           data-pagination="client"
           data-url="/json/data1.json"
           data-show-refresh="true"
           data-page-list="[10, 25, 50, 100, ALL]">
  <thead>
   ....
 </thead>
</table>
```

Inside the file there are 11 entries. When you delete records from the file and update the table
```
  $(".main-table").bootstrapTable("refresh");
```

There is an error on the line in the bootstrap-table.js [Line 1014](https://github.com/wenzhixin/bootstrap-table/blob/master/dist/bootstrap-table.js#L1014)

The method is not supported.In other browsers such an error does not occur, only in IE8. At the same time when adding a string to a file or to remove another, further it works fine. How can I avoid this prompt?

**Comment by Psihobolt** [comment]
@wenzhixin  I'm a little look into the matter. 
The problem is that IE8 is not supported in Array.prototype.indexOf (). 
Therefore, there are several solutions. The first is to use es5-shiv.js. The second method is to use the $ .inArray (). 
I change from
~~~
if (pageLst.indexOf(this.options.formatAllRows().toLowerCase()) > -1) {
~~~
to
~~~
if ($.InArray(this.options.formatAllRows().toLowerCase(), PageLst) > -1) {
~~~
I made the second option and checked on Ie8 and Firefox 15. I have work. But I'm not sure of the speed of this method. I do novice programmer in Javascript and am not sure that is the best solution so that you wanted to show developments

**Comment by wenzhixin** [comment]
Please use `$.inArray`, I think the speed is no problem, can you help to create a pull request?

**Comment by Psihobolt** [comment]
@wenzhixin I unfortunately do not know how to do it. I'm a beginner and Github :-) May evening check out the FAQ and make :-)

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

**Comment by wenzhixin** [comment]
Merged
