### ISSUE TITLE
Sub table issue

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1249]
Hi,
I have implemented subtable feature in my web appplication working fine but please tell me how to add '+' icon along with first column data instead of adding separately...i have created sample screenshot please check it once..
![capture](https://cloud.githubusercontent.com/assets/12938449/9079437/b8ea0668-3b67-11e5-9a27-380370577a0e.PNG)

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle base on our templates?

**Comment by wenzhixin** [comment]
any update?

**Comment by dabros** [comment]
@faruk77  - #1405 

Seriously, sort out your dozens of questions and try to prioritize the numerous (sometimes superficial) modifications you making.

You posted over 20 issues so far, almost none with fiddles, and are often unclear on what you actually need. I know myself and wenzhixin and djhvscf all tried to help in at least most of these, and most seem a waste of time on both our parts as there is no sign of useful output from them.

Please try to understand several points before asking for help, namely how you should be approaching a project like this that obviously is new enough for you and which are ambitious enough about that you constantly asking for help.

<br/>
**1. Identify the baseline**

This is the core path needed to have a functioning product. 

Ignore superficial requirements like minor UI tweaks and such, and focus on required data presentation and manipulation. Other requirements can be added in later.

<br/>
**2. Explain business problem**

Ive answered 8+ topics when id bet money the question you asking is not question you need. 

Your focused on exact solutions, instead explain the business problem and your 'thoughts' on implementation, ie the approach you are considering and one or more links to help us understand why you think that (similar code and possibly desired output using any js plugin)

<br/>
**3. Useful fiddles**

Im tired of repeating same thing to you - get a working fiddle showing YOUR data, if need be make ANOTHER fiddle showing the related example.

<br/>
**4. Less topics, more detail**

Relates to the first 3 points, your either not clear or you focusing on specific solution and spam questions on those. 

Use bullet points and clear 'current output' vs 'expected/desired output'. 

We are NOT here to build your product, but if you show clear effort (make use of js comments to help us know what you understand) and you can give us an actual reason for what you want, enough for us to understand, then we will try to help.


<br/>
Frankly, have a go at your baseline, make a list of desired modifications, look at the examples and doco so you can at 'least' hypothesise an approach for them, then present that in as few, clearly written, well detailed topics as possible.

<br/>
And finally - if you cant code a modification yourself, and no clear example of it working in our examples pages, decide if you actually need them.

Make the baseline work then worry about the pizzaz

**Comment by faruk77** [comment]
ok i'm really sorry, from next time onwards i will come with fiddle and the above cases what you have explained.

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
