### ISSUE TITLE
分页参数limit出现异常

### ISSUE THREAD

**Issue by M7Studio** [wenzhixin/bootstrap-table#1250]
举例讲，如果数据库共有10条记录，此时bootstrap table设置分页为每页10条，此时进行条件检索，假如结果查出2条，此时清除检索条件刷新表格，只显示出2条记录，调试发现limit竟然是2,如果再次刷新表格limit又变回10,结果正常。

**Comment by wenzhixin** [comment]
不会吧，在 http://issues.wenzhixin.net.cn/bootstrap-table/ 测试是正常的。

**Comment by M7Studio** [comment]
官网的示例不符合复现问题的前提：“数据库里有且仅有10条数据（即总记录数为10条），而当前分页默认为每页10条”时。
我看了一下源码，问题出现在1532行，源头感觉是1140-1142行造成的，注释掉就可以解决问题，但不清楚这里的作用。请见附件图片。

 
Date: Wed, 5 Aug 2015 03:08:58 -0700

**Comment by wenzhixin** [comment]
OK, 有空测试下刚好 10条数据的情况，假如你有发现具体问题可以告诉我。

**Comment by M7Studio** [comment]
我觉得问题在1140-1142行，但是你这个赋值应该是有目的的，我不了解全部的逻辑，只是定位出问题在这里。

**Comment by wenzhixin** [comment]
你说的是这里吗：https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1142

**Comment by M7Studio** [comment]
行号有些不同，在你这里应该是1264-1266

**Comment by M7Studio** [comment]
你看因为<a href="https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1264">1264-1266</a>会导致<a href="https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1664">1664-1669</a>那里判断有问题了

**Comment by wenzhixin** [comment]
没有发新版，src 下是开发版本。发布新版本会发布到 dist 文件夹下。

**Comment by wenzhixin** [comment]
用最新版进行验证没有出现你所说的这个问题
