### ISSUE TITLE
resetView does not reset the search input field

### ISSUE THREAD

**Issue by andrea-schneider** [wenzhixin/bootstrap-table#1251]
Hi
Is there any other function which can be used to clear also the search field while resetting the view?
It is quite confusing for the user if he resets the view but still doesn't see any entries if he did enter a not-macthing search value before resetting the table.

Another question, is there no option to use custom-ajax (https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/custom-ajax.html) without server side pagination? As soon as I remove the param 'data-side-pagination="server"' it doesn't work anymore.

Thanks for your help
Andrea

**Comment by wenzhixin** [comment]
Added resetSearch method to reset the search text, you can use like: 
```js
$table.bootstrapTable('resetSearch');
// or
$table.bootstrapTable('resetSearch', 'something');
```

The second question, the answer is yes, you can use client server side pagination but you need to return an array instead of an object, for example:
```js
params.success([{
    "id": 0,
    "name": "Item 0",
    "price": "$0"
}]);
```
