### ISSUE TITLE
Newline in content with card view

### ISSUE THREAD

**Issue by maxelle** [wenzhixin/bootstrap-table#1253]
hi
to well format a string in a cell i've inserted in it some `<br>`.

Everything works well in table view mode, but when i switch to card view mode the new line goes under the label

In the attached images you can see the result where the column
 "Match" contains "`INTER - JUVENTUS<br>This Is On A New Line`"

thanks Massimo

![tableview](https://cloud.githubusercontent.com/assets/1881396/9107359/f43689de-3c26-11e5-8a68-22936de6fa1f.png)

![cardview](https://cloud.githubusercontent.com/assets/1881396/9107361/f8513b86-3c26-11e5-9f2d-e03b3ae273e8.png)

**Comment by wenzhixin** [comment]
Custom the card view style: http://jsfiddle.net/wenyi/e3nk137y/2667/
