### ISSUE TITLE
Select2 in column head will not focus

### ISSUE THREAD

**Issue by wexwell** [wenzhixin/bootstrap-table#1254]
I have a select dropdown box that I am putting in the table header like this;

`<th>Field<select id='findfield' class='form-control'><option value='All'></option></select></th>`

And I converted it to a select2 dropdown box (https://select2.github.io/) with the following code;

`$("#findfield").select2({dropdownAutoWidth: 'true'});`

If I place it outside of the header it works perfectly, but inside of the header I cannot focus on it to click or use it. I suspect it is the same issue that happens with modals, but I have not figured how to work around this here. Link for similar problem with modals; http://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal.

**Comment by wenzhixin** [comment]
Just like this example: you can try to convert select to select2 dropdown box after `post-body.bs.table` event.

**Comment by wexwell** [comment]
I am using jQuery to initialize and set the table parameters, and the select2 code comes after that. It should be initializing after the table does. It is also at the bottom of the code just like the example. This is the way I had everything to begin with.

Thank you for the response.

**Comment by wenzhixin** [comment]
Good, close the issue.

**Comment by wexwell** [comment]
The problem still exists; my code had all the suggestions mentioned but it still will not focus when the select2 is in the header.

**Comment by wenzhixin** [comment]
Can you use the filter-control extension?

**Comment by wexwell** [comment]
When I looked at the filter control it did not give me the flexibility of the select2. I have a total of 5 of them and 4 will repopulate depending on what was selected with the other ones (or hold all the values in the beginning). I need complete control over the content.

**Comment by wenzhixin** [comment]
Use `post-header.bs.table` event: http://www.codeply.com/go/e4LJoKfhdR

**Comment by wexwell** [comment]
Works perfectly, thank you very much! :)
