### ISSUE TITLE
flat-json does not work on inserted/updated rows

### ISSUE THREAD

**Issue by qwiglydee** [wenzhixin/bootstrap-table#1255]
the flatjson is only called from initData, and thus works with methods load/append/prepend.

when calling insertRow, updateRow data is not flattened

**Comment by wenzhixin** [comment]
Need to add support in extension file: https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/flat-json/bootstrap-table-flat-json.js, remember any pull request is welcome.

**Comment by qwiglydee** [comment]
Is it possible at all to support non-flat objects in data?
Isn't it just a matter of getters/setters in few places?

**Comment by wenzhixin** [comment]
Now we support this feature by default.
