### ISSUE TITLE
菜鸟求教，关于Bootstrap Table Examples的疑问

### ISSUE THREAD

**Issue by Since1990** [wenzhixin/bootstrap-table#1256]
想知道例子中的数据格式是怎么样的，以及加载数据方法的参数设置，看了http请求，一直很奇怪的是url后面的get参数是哪里加上去的。而且，不同的例子里面，加载数据的参数不一样的话，json的格式也是不一样的，我该怎么知道什么时候用什么参数，以及需要什么json格式呢？ 菜鸟虚心求教! 
总结一下我的问题：
1.例子中url后面的参数怎么自己加上去的？
2.Bootstrap Table Examples中welcome.html中的/examples/bootstrap_table/data 哪里有？
3./examples/bootstrap_table/data的数据格式怎么确定，不同table设置，怎么对应不同的json，比如
什么时候需要添加total，rows等固定格式

**Comment by wenzhixin** [comment]
1. 参数是插件自动增加的
2. https://github.com/wenzhixin/bootstrap-table-examples
3. client 端需要返回数组，server 端需要返回 total 和 rows 格式
