### ISSUE TITLE
Index from e, name, args (click-cell.bs.table)

### ISSUE THREAD

**Issue by dzmitry-masko** [wenzhixin/bootstrap-table#1257]
$table.on('all.bs.table', function (e, name, args) {
if ((name == 'click-cell.bs.table') &&  (args[0] == 'time'))
{
$table.bootstrapTable('updateRow', {
    index: 3,
     row: {
              number: 18
               }
 });
}
}):

Question. As of the variables e, name, args get index?

**Comment by wenzhixin** [comment]
```js
function (e, name, args, $el) {
    var index = $el.parent().data('index);
}
```
