### ISSUE TITLE
searching-filtering in columns

### ISSUE THREAD

**Issue by marioene** [wenzhixin/bootstrap-table#1258]
I have a question:
Is the searching/filtering working in your table for all columns in the tables? Because I understand that for Bootstrap DataTables is a problem to search/filter for a column added with add_column and not directly from the query (if the data in columns  in table are from SQL QUERY the searching is working). I tried tot do that in Laravel and I have this problem.

**Comment by wenzhixin** [comment]
Yes, what problem do you have?

**Comment by marioene** [comment]
If I want to populate all the columns from your datatable with results  ONLY from a query, the searching-filtrering it's working fine, but if the results is composed from a query and a customize column added with add_column (in Laravel framework), the searching isn't working in that customized column, but is working in columns generated from query.
Details of my problem here:
http://stackoverflow.com/questions/31781436/datatable-filtering-searching-add-column-in-laravel-project

**Comment by wenzhixin** [comment]
Sorry, I hope to help, but in your problem, it seems you are using dataTable.

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
