### ISSUE TITLE
Table Sort Ajax

### ISSUE THREAD

**Issue by kodeine** [wenzhixin/bootstrap-table#1261]
Wanted to know if its possible to use ajax for data and sort client-side?
I am using ajax to get the data but when i sort it sends the request to server. How can i make it sort client-side.

Thanks.

**Comment by wenzhixin** [comment]
Set sidePagination to client.

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by kodeine** [comment]
Thank you.
