### ISSUE TITLE
Allow providing toolbar option as a Node 

### ISSUE THREAD

**Issue by ebengtso** [wenzhixin/bootstrap-table#1262]
In situations you already have a Node for the toolbar (created on the fly), it's better to use it directly rather than a string selector.

Here is a patch, in line 786, add the condition
`
        if (typeof this.options.toolbar === 'string' || typeof this.options.toolbar === 'object') {
            $(sprintf('<div class="bars pull-%s"></div>', this.options.toolbarAlign))
                .appendTo(this.$toolbar)
                .append($(this.options.toolbar));
        }
`
Thanks

**Comment by wenzhixin** [comment]
Hi @ebengtso, can you create a pull request?

**Comment by ebengtso** [comment]
pull request done.

thanks

**Comment by wenzhixin** [comment]
Merged!
