### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by holmes2136** [wenzhixin/bootstrap-table#1264]
it should fix on line : 331 , or would cause error  "Cannot read property 'forEach' of undefined"

update 

this.columns.forEach(function (column)

to 

this.options.columns.forEach(function (column)

**Comment by wenzhixin** [comment]
You need to update `bootstrap-table.js` to latest version.

**Comment by wenzhixin** [comment]
If the problem exists, reopen the issue.

**Comment by holmes2136** [comment]
Thanks for your reply
