### ISSUE TITLE
searching in multiple columns

### ISSUE THREAD

**Issue by AVSYS-AK** [wenzhixin/bootstrap-table#1265]
Hi,

Before i start, let me appreciate your efforts on this plugin. Its awesome.

Just as i found out, the search functionality is not searching from multiple columns, like combination of words entered in textfield and are present in multiple columns of that row.

Can we enable this ?

e.g https://datatables.net/examples/api/regex.html

If i search in demo table as 'tok acc', it gives me Tokyo and Accountant from two different columns.

**Comment by AVSYS-AK** [comment]
Hi wenzhixin,

I am really looking forward for this feature. Can you help in any way ?

**Comment by wenzhixin** [comment]
I think you can try the filter-control extension at the moment.

**Comment by AVSYS-AK** [comment]
Thanks for the reply. Yes i am using that. But would like the reggae search enabled. 
Please let me know if tis can be done as exclusive development. I don't mind making it live for others.

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/e3nk137y/3046/

**Comment by AVSYS-AK** [comment]
Thanks djhvscf. :+1:
