### ISSUE TITLE
关于自定义的消息展示

### ISSUE THREAD

**Issue by summerf10** [wenzhixin/bootstrap-table#1266]
当表格无数据时显示的是formatNoMatches的值，虽然这个值是可以自定义的，但是无法根据后台的返回值动态的自定义，譬如当我后台程序报错，错误信息返回时，我认为显示No matching records found是不合理的

**Comment by wenzhixin** [comment]
#1791 updateFormatText method: http://jsfiddle.net/e3nk137y/3876/
