### ISSUE TITLE
Sorting Order of hyperlinked info

### ISSUE THREAD

**Issue by trainspotting** [wenzhixin/bootstrap-table#1268]
If you have hyperlinked info in your table like 

```
<tr><td><a href="fruit">Apples</a></td></tr>
<tr><td><a href="animals">Monkeys</a></td></tr>
```

Then the column sort respects the hyperlinks and not the text which is displayed. So in my example A to Z sort puts Monkeys first because of the hyperlink it has.
Does this make sense? Is it technically possible to make the sort ignore the hyperlink?
Thanks!

**Comment by wenzhixin** [comment]
Here is an example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-sort.html.
```js
function sorter(a, b) {
    a = $(a).text();
    b = $(b).text();
    if (a > b) return 1;
    if (a < b) return -1;
    return 0;
}
```
