### ISSUE TITLE
Add i18next support for header and translations.

### ISSUE THREAD

**Issue by inluxc** [wenzhixin/bootstrap-table#1269]
Does any one tried to add i18next to bootrap-table?
This would be nice feature.

**Comment by wenzhixin** [comment]
Maybe this feature can be implemented as an extension. Remember any pull request is welcome.

**Comment by djhvscf** [comment]
Extension implemented https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/i18n-enhance/
