### ISSUE TITLE
UpdateRow - change default values

### ISSUE THREAD

**Issue by dzmitry-masko** [wenzhixin/bootstrap-table#1272]
Loading data tables:
![b_1](https://cloud.githubusercontent.com/assets/11837753/9195792/48b720ee-402e-11e5-9537-11f221e1355c.png)

Changing the select:
![b_2](https://cloud.githubusercontent.com/assets/11837753/9195802/5d135062-402e-11e5-9b37-03c443e0d664.png)

Click updateRow. Changes are not saved.
![b_3](https://cloud.githubusercontent.com/assets/11837753/9195818/74468286-402e-11e5-92a8-f8e6de8808b7.png)

Why is that?

**Comment by dabros** [comment]
@dzmitry-masko - saved to where?

You need to share your code, a fiddle is best (see https://github.com/wenzhixin/bootstrap-table#reporting-issues).

Bootstrap table has absolutely no control over your database, external json files, or anything outside its scope.

There is ample doco and examples - never used editable table myself but they state the steps you need to do to get the data passing back to the server. Its up to you then to actually save the changes.

http://bootstrap-table.wenzhixin.net.cn/documentation/
http://bootstrap-table.wenzhixin.net.cn/extensions/
http://issues.wenzhixin.net.cn/bootstrap-table/


For us to even have an idea of the problem, you need to share your actual code, state exactly how your getting your data and what your doing to save it.

**Comment by wenzhixin** [comment]
You need to save your changed data by yourself @dzmitry-masko.

**Comment by wenzhixin** [comment]
Or use the editable extension.
