### ISSUE TITLE
表格中某一列嵌套一个表格时，主表格与子表格的表头对齐方式，checkbox,radio属性等全部失效

### ISSUE THREAD

**Issue by ljia310** [wenzhixin/bootstrap-table#1273]
示例代码:
<div class="table-responsive"> 
<table id="timeseg-table"  class="table table-condense table-hover" data-toggle="table"> 
    <thead> 
     <tr> 
      <th data-field="state" data-radio="true"></th> 
      <th data-field="id" data-align="center" >编号</th> 
      <th data-field="name" data-align="center">名称</th>
      <th data-field="segment" data-align="center">区间</th> 
     </tr> 
    </thead> 
	

    <tbody>
     <tr> 
      <td></td> 
      <td>1</td> 
      <td>test</td> 
	
	  <td> 

	  <table id="item-table" class="table table-condense table-hover" data-toggle="table"> 
		<thead> 
        <tr> 
      <th data-field="item_id" >ID</th> 
      <th data-field="item_beg" >开始</th> 
	  <th data-field="item_end" >结束</th> 
	 
       </tr> 
      </thead> 
   
	  <tbody>
		 <tr> 
		<td>1</td> 
		<td>100</td> 
		<td>200</td> 
		 </tr> 
		
	</tbody> 
      </table> 

	  </td>
	
     </tr>
    </tbody> 
	
</table> 
</div>

**Comment by wenzhixin** [comment]
HTML 代码直接嵌套子 table 吗？估计不支持这一功能。

**Comment by ljia310** [comment]
以后会增加支持吗？

**Comment by wenzhixin** [comment]
这个实现起来比较麻烦，暂时不考虑支持，请使用 js 的方式，例子：http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html
