### ISSUE TITLE
Samsung Galaxy Note 3 and 4 running Android 5.0

### ISSUE THREAD

**Issue by Gouvi** [wenzhixin/bootstrap-table#1275]
The sort column carrot is not listing items in Alphabetical order with the Default Browser in Android 5.0 or 5.1. I am not able to fully re-produce the issue as I do not have a Samsung Galaxy Note.

Has anyone else had any issues with this?

**Comment by wenzhixin** [comment]
Sorry, I don't know what problem you mean, can you provide some code or screenshot?

**Comment by dabros** [comment]
@Gouvi - we need an update here

Please provide fiddle or screenshots using latest version with description of exactly what is occuring in each image

Or if this is solved please close this issue

thanks

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
