### ISSUE TITLE
Sorting with javascript

### ISSUE THREAD

**Issue by Lars-** [wenzhixin/bootstrap-table#1277]
Is there a way to manual (re)sort a specific column with javascript?

**Comment by wenzhixin** [comment]
No, we don't have such method, but you can sort a specific column when initializing the table.

**Comment by Lars-** [comment]
Is there a way to reinitialize the table? Because that would solve it.

**Comment by wenzhixin** [comment]
Yes, `refreshOptions` method can reinitialize the table, you can try that method.

**Comment by wenzhixin** [comment]
Any update? or you can use jQuery to trigger the `click` event of `th` field. If problem exists, reopen the issue.
