### ISSUE TITLE
wrong row checked when using checkBy with filter

### ISSUE THREAD

**Issue by provivo** [wenzhixin/bootstrap-table#1278]
Hi,
first off, thank you wenzhixin for your efforts!

I have a table with a checkbox in each row and a filter on top.
When I filter and then say 
   $("#table").bootstrapTable('checkBy', {field: "id", values: ["2"]});
it doesn't check the row with id=2 but checks the row number where id=2 used to be before applying the filter.

(data-pagination happens on client side) 

thank you very much,
provivo

**Comment by wenzhixin** [comment]
If the type of id is number, you need to use like this:
```js
$("#table").bootstrapTable('checkBy', {field: id, values: [2]});
```
