### ISSUE TITLE
maintain checkbox state with client-side-pagination, sort and filter?

### ISSUE THREAD

**Issue by provivo** [wenzhixin/bootstrap-table#1279]
Hi,

I have a table with a checkbox in each row and client-side pagination. I would like to have the checkbox state maintained but I can't get it to work..
All the examples I could find have server side pagination enabled.

I really tried for hours and hours but with little success..
Your help would be very much appreciated!

**Comment by wenzhixin** [comment]
You can just set the `maintainSelected` option to `true`, here is the documentation: http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options.
