### ISSUE TITLE
Server-side pagination (sidePagination) does not display table rows

### ISSUE THREAD

**Issue by danielsharvey** [wenzhixin/bootstrap-table#1281]
Hi,

When I am using server-side data with pagination the table does not display any data (the table is empty).

Is this a usage issue or bug?

See https://jsfiddle.net/m8e2kk6d/ for a concrete example.

Thanks,
Daniel

**Comment by wenzhixin** [comment]
The server side pagination need to response an object like:
```js
{
    total: 100,
    rows: []
}
```
for example: http://issues.wenzhixin.net.cn/examples/bootstrap_table/data?order=asc&limit=10&offset=0

**Comment by danielsharvey** [comment]
Thanks for the help. I've updated the documentation and created a pull request. See https://github.com/wenzhixin/bootstrap-table/pull/1286.
