### ISSUE TITLE
GetData with wrong data when pagination enabled. 

### ISSUE THREAD

**Issue by fanwen** [wenzhixin/bootstrap-table#1282]
When pagination is enabled, click next page and get wrong json object data. 
Wrong one has one more field "undefined":false.
(Chinese)
表格有分页功能时，点击了下一页后，用 getData 方法，得到的数据跟真正的数据不同。
错误的数据，包含一个奇怪的  "undefined":false 。

**Comment by wenzhixin** [comment]
不是真正的数据？这个问题应该在最新版本修复了，更新src下的代码到最新，验证下

**Comment by wenzhixin** [comment]
还有问题再 reopen
