### ISSUE TITLE
Dynamically generated input boxes inside the table - how to reference via jquery?

### ISSUE THREAD

**Issue by jimgit** [wenzhixin/bootstrap-table#1283]
I have a column that I use the data-formatter to generate the <input id="abc1"> (dynamic ids when the bootstrap table is generated.  When I later try to refer to this via jquery   

var myValue = $('#abc1').val();  

It's like the dom element doesn't exist.    How do I reference a text box created in the grid?

**Comment by wenzhixin** [comment]
Refer to element via jquery after rendering the table.

**Comment by wenzhixin** [comment]
I think you can use 'onPostBody' event.
