### ISSUE TITLE
Filtering with styled elements

### ISSUE THREAD

**Issue by joshbenhamou** [wenzhixin/bootstrap-table#1284]
Hi. Great plugin, thanks!

I'm trying to filter elements of a table that are not plain text. For example, I've got labels in my table and I would like to filter just the text inside the label. For the moment, I've just stripped html tags from the query on the server side although, clearly, it would be best to stay in plugin.

I tried to remove the html from the filtered values in multiple places but I wasn't able to prevent the request being sent with html. Any ideas?

**Comment by wenzhixin** [comment]
I think you can filter the data in server side in this case.

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
