### ISSUE TITLE
table header: from small window, to big window, the stretch problem, and alignment problem

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1287]
Pictures:

The start:
![iii](https://cloud.githubusercontent.com/assets/13029902/9243835/dea0e85c-41c7-11e5-95ee-fea2659784cc.png)

When toggle is pressed:
![rr](https://cloud.githubusercontent.com/assets/13029902/9243839/e740fbd2-41c7-11e5-9281-dabd7cd34e71.png)

Ta Daaaa:
![ss](https://cloud.githubusercontent.com/assets/13029902/9243841/ebd25b96-41c7-11e5-8db1-921c989c0c83.png)

The stretch problem
and the alignment problem

Thanks

**Comment by wenzhixin** [comment]
Have you used the `resetView` method to resize the header?

**Comment by meetraz** [comment]
I reported this problem here:  https://github.com/wenzhixin/bootstrap-table/issues/639

**Comment by wenzhixin** [comment]
Any update?

**Comment by joomlaA1** [comment]
hello..
i have not used resetView method to resize the header..

how?? tanks

**Comment by wenzhixin** [comment]
@joomlaA1 http://bootstrap-table.wenzhixin.net.cn/faq/

**Comment by joomlaA1** [comment]
thanks
