### ISSUE TITLE
显示内容时是否可以处理一下，以防js注入等

### ISSUE THREAD

**Issue by M7Studio** [wenzhixin/bootstrap-table#1288]
现在数据都是什么就直接出现在页面上的，应该转义处理一下，否则存在安全问题。

**Comment by wenzhixin** [comment]
有注入的详细例子吗？

**Comment by wenzhixin** [comment]
跟问题 #1049 应该是一样的，安全问题暂时不做修改，后面会考虑。

**Comment by M7Studio** [comment]
没有#1049的方法那么麻烦，网上有很多例子，比如利用jquery就可以：
html=$("#x").text(html).html();

**Comment by wenzhixin** [comment]
注入这一块了解比较少，可以举例说明下吗？

**Comment by M7Studio** [comment]
比如恶意用户存到数据库里的值是<script>window.open("xxx")</script>,那你不做转义的话，这个脚本直接通过你的插件加到页面上就会运行了；但如果你转义的话它就变成字符串文本，不会被执行。比如jsp页面的话往往是通过<c:out>来往页面上输出值的，它会转义。

**Comment by wenzhixin** [comment]
有空试下

**Comment by wenzhixin** [comment]
Added `escape` option.
