### ISSUE TITLE
my <select ...> data

### ISSUE THREAD

**Issue by xnext40** [wenzhixin/bootstrap-table#1290]
Hi wenzhixin, great work, thx!
By default bootstrap-table send get parameter ?order=asc
i need renew table if user changed select(not in table) data
how can i add one of more get parameter to query
for example:
?order=asc?selectname1=userselection&radio1=data&selectname2=userselection2
How can I create this functionality?
![2015-08-13_16-47-47](https://cloud.githubusercontent.com/assets/13274300/9251547/69a51ed2-41dc-11e5-8c95-7c69626268ec.png)

**Comment by wenzhixin** [comment]
Here is an example: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/issues/152.html

**Comment by xnext40** [comment]
Thx for reply =) I successly tested this feature =)

**Comment by wenzhixin** [comment]
Great, close it.
