### ISSUE TITLE
Column width large table

### ISSUE THREAD

**Issue by mhzg81** [wenzhixin/bootstrap-table#1291]
Hi. Great work, thanks!
When i'm using width attribute for columns and the table gets to large, it will not get used and it will calculate own width values. Is there a possibility to suppress this and force the custom column width (via JavaScript) ?

**Comment by dabros** [comment]
@mhzg81 - please create a fiddle so we can see when this happens, and play with a fix or workaround

https://github.com/wenzhixin/bootstrap-table#reporting-issues

**Comment by mhzg81** [comment]
ok. Is it possible to set the width of the first two columns? (Fixed size or sothat the data fits in a single line )   

https://jsfiddle.net/1zksL00v/1/

**Comment by MittWillson** [comment]
I have the same problem

**Comment by MittWillson** [comment]
@mhzg81   Interim solution
css:
      table { table-layout:fixed; }

**Comment by dabros** [comment]
@MittWillson @mhzg81 

Sorry for delay, i was ill and only just got back to work today.

After playing with the fiddle, I determined that "data-width" is not the issue so much as how the default table layout treats the "width" property for cells.

    table { table-layout:fixed }

That is 'a' workaround, but it is not recommended as it has its own issues. 

The responsiveness of the standard layout mode is actually fairly desired, just with the option to override if needed.

Thats where these two properties are useful:

    max-width:200px;
    min-width:100px;

Apply one or both as needed, in whatever css class you want, and apply them by using the bootstrap-table column option "data-class".

http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

This fiddle shows it in action:

https://jsfiddle.net/dabros/1zksL00v/9/


I haven't tested it extensively, but it appears to work fine without having to change the table-layout mode.

Please test this more thoroughly and state whether it works well for you.

As a side-note, I submitted a pull request to highlight this in the doco, as its very simple in hindsight, but i can see some possible confusion if not used to thinking bout it, and i also alot of people maybe dont even think of resizing their table to test responsive layout.

https://github.com/wenzhixin/bootstrap-table/pull/1319

**Comment by wenzhixin** [comment]
Great @dabros
