### ISSUE TITLE
Bootstrap Table Filter Control

### ISSUE THREAD

**Issue by mwatz122** [wenzhixin/bootstrap-table#1292]
I am having trouble getting the filter control to work correctly using <b>bootstrap-table-all.js</b> (Note: I can get it to work correctly by using <b>bootstrap-table.js</b> <i>and</i> <b>bootstrap-table-filter-control.js</b> only. Also, I have verified that there are no differences in my <b>bootstrap-table-all.js</b> file in the  <b>bootstrap-table.js</b> and <b>bootstrap-table-filter-control.js</b> sections. <b>This leads me to believe that another extension is breaking the filter-control extension?</b>

I believe I am using the most up-to-date version of <b>bootstrap-table-all.js</b> (I built it myself) by running the <code>npm-install</code> and <code>grunt</code> commands within the bootstrap-table master directory. However, the latest version of <b>bootstrap-table-all.js</b> (built from src) would be appreciated if this is not the case.

Problem/fiddle:
https://jsfiddle.net/mwatz122/8mkpd3qd/

<b>After entering a value in a filter, all results are shown when another filter's value is cleared. Example: 1) Type '231' in the ID filter 2) Set Status to 'Complete' 3) Clear Status and now all results show even though the ID filter is set to only show results with an ID of 231.

Any help with this issue would be GREATLY appreciated. Thank you!

**Comment by mwatz122** [comment]
Update: I am able to resolve this issue by removing the Bootstrap Table Filter extension. It seems as though the Bootstrap Table Filter extension is breaking the Bootstrap Table Filter Control extension.

**Comment by wenzhixin** [comment]
Great, I will consider to remove the filter extension.

**Comment by dabros** [comment]
@wenzhixin @mwatz122 - does the latest version fix this?

**Comment by wenzhixin** [comment]
Removed all.js from 1.9.0
