### ISSUE TITLE
hiding column by visible option can not work

### ISSUE THREAD

**Issue by thfeng** [wenzhixin/bootstrap-table#1294]
I set a anonymity function to visible field of column, the function will return a boolean value, but it did't work. however, if I set a function that return a boolean value directly to visible field, it works normally.
CAN NOT WORK:
columns:[{
                            field: "",
                            title: "billing code",
                            align: 'center',
                            valign: 'middle',
                            formatter: function (val, row, index) {
                                return row.billingCode;
                            },
                            visible: function () {
                                return Manager.removeBillingColumnIfNeeded();
                            },
                            sortable: true
                        }]

WORK NORMALLY:
columns:[{
                            field: "",
                            title: "billing code",
                            align: 'center',
                            valign: 'middle',
                            formatter: function (val, row, index) {
                                return row.billingCode;
                            },
                            visible: Manager.removeBillingColumnIfNeeded(),
                            sortable: true
                        }]

**Comment by wenzhixin** [comment]
The `visible` option can not support `function` type, it can only be `boolean`, I think you can use a variable.
