### ISSUE TITLE
Unable to set different url bootstrap table on refresh

### ISSUE THREAD

**Issue by naimhiq** [wenzhixin/bootstrap-table#1295]
Hello guys, 

I am having problem in my C# handler and bootstrap refresh, 

I have the following handler with methods public class HanlderName: HandlerBase
```
    {
  
        public object RetriveData1()
        {
            // some code here to retrieve data
        }

        public object RetriveData2()
        {
           // some code here to retrieve data
        }
 }

("#myTable").bootstrapTable( {
                    url: '/HandlerName/RetriveData1'
 });
```
and I have a button that when in click is expecting to retrieve second method on refresh
```
 $("#myTable").bootstrapTable('refresh', {
                    url: '/HandlerName/RetriveData2'
     });
```
BUT the problem is that bootstrap tables keeps refreshing and never gets to the second method. I read  for similar issues but I do not know if this has to do with the version of Bootstrap and I have 1.3.0. 

Any idea would be appreciated  ? 

Thanks!

**Comment by wenzhixin** [comment]
You need to change `("#myTable")` to `$("#myTable")`, and here is an example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/409.html

**Comment by naimhiq** [comment]
@wenzhixin 

My mistake and forgot to set  "$" , still not able to get the second method called from my C# handler. 

One question in between, does 1.3.0 version support  bootstrap refresh with new url ? 

THanks !

**Comment by wenzhixin** [comment]
Please use the latest version, v1.8.1

**Comment by naimhiq** [comment]
ok thanks :), I have this in an old project.
