### ISSUE TITLE
bug -- wrong row when using checkBy with filter

### ISSUE THREAD

**Issue by provivo** [wenzhixin/bootstrap-table#1296]
Hi wenzhixin,

when using checkBy with an active filter the wrong row is checked.

I've tried this with the 1.8.1 release **and** the newest commit (f65c2de217)

-- using checkBy before applying filter (**correct**)
![screenshot from 2015-08-14 14 10 00](https://cloud.githubusercontent.com/assets/13765234/9274011/171465b8-4292-11e5-9d08-bb5f77edd390.png)

-- using checkBy after applying filter (**bug**)
![screenshot from 2015-08-14 14 10 42](https://cloud.githubusercontent.com/assets/13765234/9274019/2dc2011c-4292-11e5-9094-9dc1107c59e6.png)

the first row should be checked when instead the third one is checked.

I've also tried this with other field/value pairs -- to the same effect.
(it seems the row numbers aren't updated after applying the filter).

thank you,
provivo

**Comment by dabros** [comment]
@provivo @kolupaevri @wenzhixin @djhvscf - is this issue solved now?

**Comment by dabros** [comment]
@provivo @kolupaevri @wenzhixin @djhvscf - same question, solved yet?

**Comment by djhvscf** [comment]
I think the problem was related to the previous version but the latest version fixes this
