### ISSUE TITLE
getHiddenColumns is missing

### ISSUE THREAD

**Issue by yenyen** [wenzhixin/bootstrap-table#1297]
I saw the `getHiddenColumns` method in the documentation but the method is not in the current code.

**Comment by MittWillson** [comment]
$table.bootstrapTable("getHiddenColumns");

**Comment by MittWillson** [comment]
@yenyen $table.bootstrapTable("getHiddenColumns")

**Comment by yenyen** [comment]
Sorry, I didn't see that the method has added after release 1.8.1
