### ISSUE TITLE
超多列显示固定宽度

### ISSUE THREAD

**Issue by MittWillson** [wenzhixin/bootstrap-table#1298]
比如我设置每个列的宽度 我想当总宽度超过100%的时候能开启滚动条  目前看好像我比如每列都设置好宽度 超过100%的时候会自动占用其他的列宽度 而不是开启滚动条 如果不能再固定宽度的情况下开启滚动条 那显示效果肯定是不如人意

**Comment by MittWillson** [comment]
最终效果例如css： table-layout:fixed;
当然想的是比这种的更加自然 而不是要自己再写一条css 
        (U •́ .̫ •̀ U) 忘了感谢作者了 阿里噶多(ありがとう)

**Comment by wenzhixin** [comment]
能否帮忙提供下 jsFiddle 展示你说的问题呢？

**Comment by MittWillson** [comment]
@wenzhixin 就跟https://github.com/wenzhixin/bootstrap-table/issues/1291这个问题一样 我实验过解决方案后发现个问题就是如果遇到空格就会折行 怎么解决呢

**Comment by MittWillson** [comment]
(U •́ .̫ •̀ U) 再问一个问题 可以设置隐藏值么 比如一行有个值 UserId 不显示 但是操作的时候会带上这个参数 比如删除这个用户 怎么才能让这个值隐藏 除了用hidden

**Comment by wenzhixin** [comment]
不用隐藏，操作的时候可以用row参数获取整列的值，例如row.userId

**Comment by MittWillson** [comment]
@wenzhixin 我的意思是userId这列只是做提交的时候带的参数 但是并不显示给用户

**Comment by wenzhixin** [comment]
例如：http://jsfiddle.net/wenyi/e3nk137y/2952/ 只显示 name 列，但是其他列的值照样可以拿到：row 还是原来的

**Comment by MittWillson** [comment]
@wenzhixin 原来还可以这样。。。。谢谢 问题解决了 ( ؔ⚈͟ ◡ ؔ⚈͟ ๑)
