### ISSUE TITLE
Uncaught TypeError: that.$body.find(...).editable is not a function

### ISSUE THREAD

**Issue by three60** [wenzhixin/bootstrap-table#1299]
I'm getting this error : Uncaught TypeError: that.$body.find(...).editable is not a function on 
<th data-field="email" data-editable="true">Email</th>

I'm including bootstrap-table-editable.js, am I missing something or is this a bug of some sort?

    <title>test</title>	
    <link href="../../../css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="bootstrap-table-master/bootstrap-table.min.css" type="text/css" media="screen">
  </head>
  <body>
  
	<table data-toggle="table" data-url="../sample.json" data-sort-name="name" data-sort-order="asc" data-show-refresh="true" data-search="true">
	    <thead>
	        <tr>
	            <th data-field="code">Code</th>
	            <th data-field="name" data-sortable="true">Name</th>
	            <th data-field="email" data-editable="true">Email</th>
	        </tr>
	    </thead>
	</table>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="../../../js/bootstrap.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="bootstrap-table-master/bootstrap-table.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="bootstrap-table-master/extensions/editable/bootstrap-table-editable.js" type="text/javascript" charset="utf-8"></script>
  </body>

**Comment by wenzhixin** [comment]
You need to import pkugin: https://github.com/vitalets/x-editable.
docs: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable
