### ISSUE TITLE
is it possible to have a context menu on click-row.bs.table

### ISSUE THREAD

**Issue by dlhenke** [wenzhixin/bootstrap-table#1300]
Is it possible to have a context menu on click-row.bs.table, if yes can you provide a example?

Thank you

**Comment by dlhenke** [comment]
for who needs this feature . 
here is a example, if possible to put this in the features i will be very glad..
Note this is not my code, only something that i borrow in the internet and adapted to my own use.

	 $(function() {
	 var $row={};
    $('#proximas_compes').bootstrapTable({url:'/actions/compes_ativas.php', 
    columns: [
    				{
                        field: 'nome',
                        title: 'Competição',
						align: 'Left',
                        valign: 'middle'
                    },{
                        title: 'Cidade',
                        field: 'cidade',
                        align: 'Left',
                    },{
                        title: 'Estado',
                        field: 'estado',
						align: 'Left',
                    },{
                        title: 'Inicio',
                        field: 'inicio',
                        align: 'Left',
                    },{
                        title: 'Final',
                        field: 'fim',
                        align: 'Left',
                    }
                ],}).on('click-row.bs.table', function (e, row, $element) 
                		{              
							$row=row;
							/*$("#proximas_compes td").contextMenu(
								{
										menuSelector: "#contextMenu",
										
										menuSelected: function (invokedOn, selectedMenu) 
										{
											var msg = "You selected the menu item '" + selectedMenu.text() + ' ' + row.nome;
												//"' on the value '" + invokedOn.text() + "'";
											alert(msg);
										}
								});*/
                		}).contextMenu(
								{
										menuSelector: "#contextMenu",
										
										menuSelected: function (invokedOn, selectedMenu) 
										{
										//	var msg = "You selected the menu item '" + selectedMenu.text() + ' ' + $row.nome;
												//"' on the value '" + invokedOn.text() + "'";
											showModal(selectedMenu.attr('id'),selectedMenu.text(),$row);
											//alert(msg);
											//return false;
										}
								})
	});
	(function ($, window) {
    $.fn.contextMenu = function (settings) {
        return this.each(function () 
        {
            // Open context menu
            $(this).on("click", function (e) {
                // return native menu if pressing control
                // botao direito do mouse usar $(this).on("contextmenu", function (e) {
                if (e.ctrlKey) return;
                
                //open menu
                var $menu = $(settings.menuSelector)
                    .data("invokedOn", $(e.target))
                    .show()
                    .css({
                        position: "absolute",
                        left: getMenuPosition(e.clientX, 'width', 'scrollLeft'),
                        top: getMenuPosition(e.clientY, 'height', 'scrollTop')
                    })
                    .off('click')
                    .on('click', 'a', function (e) 
                    {
                        $menu.hide();             
                        var $invokedOn = $menu.data("invokedOn");
                        var $selectedMenu = $(e.target);
                        
                        settings.menuSelected.call(this, $invokedOn, $selectedMenu);
                    });
                
                return false;
            });

            //make sure menu closes on any click
            $(document).click(function () {
                $(settings.menuSelector).hide();
            });
        });
        
        function getMenuPosition(mouse, direction, scrollDir) {
            var win = $(window)[direction](),
                scroll = $(window)[scrollDir](),
                menu = $(settings.menuSelector)[direction](),
                position = mouse + scroll;
                        
            // opening menu would pass the side of the page
            if (mouse + menu > win && menu < mouse) 
                position -= menu;
            
            return position;
        }    

    };
})(jQuery, window);

**Comment by dabros** [comment]
@dlhenke - I too lack time to properly make a Pull Request with tidy code, or convert into plugin or ect.

But please provide a working fiddle of this, as then a chance this might be adapted by somebody.

**Comment by mtik00** [comment]
@dlhenke : FWIW, here's a JSFiddle that uses a combination of bootstrap-table and [bootstrap-contextmenu](https://github.com/sydcanem/bootstrap-contextmenu):
http://jsfiddle.net/e3nk137y/3534/

It works by storing the `<tr>` element ID of the row that was clicked before the menu is shown, and reads it back when the menu item is clicked.  It was surprisingly easy to implement.  I just added the context menu, added the JS, and set the table `id`.  There's no reason you couldn't use any other element/attribute/etc.  I'm storing the data I need as an attribute in the  `<tr>` element.  My plan is to then use that to send a request to the server.  I.e. *act on item X*.

Full disclosure: I really don't know much about JS.  YMMV.

**Comment by wenzhixin** [comment]
There is an extension: https://github.com/prograhammer/bootstrap-table-contextmenu

**Comment by mtik00** [comment]
Even better!  I'll check that out.

**Comment by prograhammer** [comment]
Cool, suddenly some folks starred the extension, so I tagged it at v1.0.0. See the updated [readme](https://github.com/prograhammer/bootstrap-table-contextmenu/blob/master/README.md) and also the updated [demo](http://www.prograhammer.com/demos/bootstrap-table-contextmenu/). Feel free to open any issues or pull requests.

**Comment by dlhenke** [comment]
Thank You prograhammer, is working like a charm.. 
I'm glad to contribute for something . but im more glad that is working for me..
