### ISSUE TITLE
Dynamic generation of group by failed

### ISSUE THREAD

**Issue by gowthamsathiya** [wenzhixin/bootstrap-table#1302]
I tried dynamic generation of groupBy after table is rendered and using dropdown box to group by based on selected attribute from dropdown using following script
```javascript
var $table = $('#table');
$(function () {
    $('select[name="dropdown"]').change(function () {						
	$table.bootstrapTable('refreshOptions', {
	      groupBy: true,
              groupByField: $(this).val()
        });
    });
});
```
It group By for the first selection correctly but for the second selection it fails with following error

ERROR: too much recursion       in following line -  bootstrap-table-group-by.js:19

**Comment by dabros** [comment]
First off, ensure that $table is set in $document.ready() or similar, just saying in case its not, unlikely to be this issue, just good form.

Your using annon function to add change code, im a bit rusty with that but looks fine to me...

I also cant actually see doco bout the groupBy attribute - where did you see this used?

As to recursion error, some thoughts:

$(this) is maybe the issue.

try adding this before $table.bootstrapTable('refreshOpt... 
 
    var $that = $(this)

and use $that

If that doesnt work, store $(this).val() and console.log what it is set to - basic debugging.

**Comment by wenzhixin** [comment]
ref #694

**Comment by djhvscf** [comment]
Merged!
