### ISSUE TITLE
there is an error in help documentation about onColumnSwitch parameter

### ISSUE THREAD

**Issue by AlexJake** [wenzhixin/bootstrap-table#1303]
the page url is [onColumnSwitch-event](http://bootstrap-table.wenzhixin.net.cn/documentation/#events)

there a only two parameter in that doc,but in my test case ,if just `field` and  `checked` two  patameter,  can not get the checked status,if add an parameter `e ` before the `field and checked` parameter ,it's worked fine。 can u confirm it?

**Comment by wenzhixin** [comment]
#1076

**Comment by AlexJake** [comment]
thanks a lot
