### ISSUE TITLE
Sort callbacks

### ISSUE THREAD

**Issue by masterdany88** [wenzhixin/bootstrap-table#1304]
Can I ask for new functionality. I haven't found it in examples and documentation.
I would like to execute some custom action, after sorting rows in table.

Please give me some help.

**Comment by dabros** [comment]
http://bootstrap-table.wenzhixin.net.cn/documentation/#events

I would suggest creating a fiddle or local install of something like you see in http://bootstrap-table.wenzhixin.net.cn/examples/#events

OnPostBody and similar callbacks are triggered every time the table body is affected

Use console.log and see what fits your bill, trust me when i say there is no need for new functionality in this case, use the existing callbacks.

**Comment by wenzhixin** [comment]
Just like @dabros said, no need to add a new event, you can use `onPostBody` to do what you want.
