### ISSUE TITLE
custom search(toolbar)

### ISSUE THREAD

**Issue by xnext40** [wenzhixin/bootstrap-table#1306]
Hi wenzhixin, i successfully  tested feature queryParams, next i need add custom element inline with default input search or create custom search toolbar.
if i create custom search input, default input search not hidden and repeats custom
Q:
1. Can i  use default input search, but add beside inline custom element?
2. how i  can create custom search input with keyup ?
3. how to set min search start symbols to >3
4. how to replace loading string to css spinner
i not use data variables
my code

```javascript
var $table = $('#table');
$table.bootstrapTable({
            method: 'get',
            url: 'http://somesite.com/data1.php',
            search: true,
			cookie: true,
			cookieIdTable: 'yiibook',
			searchAlign: 'left',
            showColumns: true,//Enable columns show\hide
            showRefresh: true,
       	    responseHandler: 'responseHandler',
			toolbar:'#toolbar',
            columns: [
            {
                title: 'Name',
				field: 'name',
                align: 'center',
				sortable: true
            }, {
                title: 'Actions',
                align: 'center'
            },
            {
                title: 'Mail',
                field: 'mail',
                align: 'center',
				sortable: true,
				visible: screen
            },
            {
                title: 'Internal Number',
                field: 'int_num',
                align: 'center',
				sortable: true
            },
            {
                title: 'External number',
                field: 'ext_num',
                align: 'center',
				sortable: true
            }
        ]
        });

function responseHandler(res) {
	var myObjects=[];
	var text=null;
//console.log(res.rows);
    $.each( res.rows, function( ckey, cvalue ) {
// console.log( key + ": " + value );
		$.each( cvalue, function( key, value ) {
		////text =  +' | ' + value.sam + ' | '+ ckey; 
		if(!screen){
		value.name = "<a href=\"mailto:"+ value.mail +"\">" + value.name + "</a><i style=\"display:none\">" + value.sam + "</i><s style=\"display:none\">"+ ckey +"</s>";
		}
		//console.log(text);
		});
//  myObjects.push(value);
 // console.log(value);
$.merge(myObjects,cvalue);
});

    return myObjects;
}
```
![2015-08-17_13-42-42](https://cloud.githubusercontent.com/assets/13274300/9303330/e720a32a-44e5-11e5-8fe7-73df6e5497cb.png)

**Comment by dabros** [comment]
Doesnt answer this question, dont have time to do that, but kinda related as explains a little bout server and client searching and has some more links and maybe useful fiddle

#1239

**Comment by xnext40** [comment]
dabros, #1239, using refresh table, this solution not for me!

I create a simple application
1. search field need only client-side filtering
2. and other one or many fields when changed reloads(refresh) table json data(returns server-side filtered json)

basically I just need to place one or more other elements beside the default search preserving client-side filtering


questions:
1.  by default bootstrap-table generates its own code(toolbar) and can not be changed!
      i need create custom search field code with same client-side filtering(keyup not clicking buttons) functions how default search field
2. how to set min search start symbols to >3
3. how to replace loading string to css spinner or change positioning

**Comment by dabros** [comment]
related to #1354, with more linked topics in posts there

**Comment by dabros** [comment]
@xnext40 - bout 4 topics now revolving round same concept, using custom ui for searches, either client-side or server side

I suggest you read the linked topics and follow links within my posts there, and see how use of custom toolbar is easy, but yes limitation if wanted to replace with custom search box.

Though in your case, is min search symbols even an issue..? 
If for some reason you think it is, then one option would be to look at callbacks (see my fiddle and posts in other topics such as #1354 and linked) and in post-header or wherever (again see fiddle in #1354) maybe you can store referance to the original callback action in a var, then clear the 'change' behaiviour for the search box, apply your own logic that checks the length before calling the original event handler.

Implementing this wouldnt require too much jquery knowledge, and im sure something similar been done before elsewhere if you get stuck.

As to replacing loading string, that should be as simple as hitting F12 and finding the placeholder that holds that text (".fixed-table-loading" from what i can see) then using jquery (either after dom ready, and/or in callbacks/bootstrap-table-event-handlers if needed) to replace the contents.


<br/>
You also havent explained your use case very well at all.

For example, what changes you feel are needed for your 'custom search', beside that 3char limit (which does seem a little arbitrary given speed of client searching).

<br/>
In any case, regarding custom client-side search box, no solution as yet, but definitely a feature request, as seen in #1354

**Comment by wenzhixin** [comment]
replacing loading string, I think you can try to set the `formatLoadingMessage` option, for example:
```js
formatLoadingMessage: function () {
    return '<div class="loading"><img src="loading.gif"></div>';
}
```

**Comment by wenzhixin** [comment]
Because this issue is the same feature with #1347, so let us close this and discuss in #1347.
