### ISSUE TITLE
可不可以加一个 固定一列的功能，类似于 dataTable的 fixedColumn

### ISSUE THREAD

**Issue by ilovezy** [wenzhixin/bootstrap-table#1310]
我boss需要一发固定一列的功能，且固定头部，这样显示大量数据的时候就比较方便，欧诺更是也要一个删除列的功能，其他几个我都可以在 demo中找到了，但是固定一列比如说 最左边的一列，我在你的 demo中没找着，不知道是否能实现呢

**Comment by xqsapper** [comment]
也是需要这个功能

**Comment by wenzhixin** [comment]
与问题 #265 重复。
