### ISSUE TITLE
filterBy过滤问题

### ISSUE THREAD

**Issue by xiaohan2013** [wenzhixin/bootstrap-table#1311]
当用filterBy过滤表中的数据时，无法回到原来的全部数据

$table.bootstrapTable("filterBy",{role:"XXX"})过滤之后，能够得到满足条件的数据，但是我想再次用这个把数据还原$table.bootstrapTable("filterBy",{role:""})原来的全部数据

**Comment by xiaohan2013** [comment]
$table.bootstrapTable("filterBy",{role:"XXX"})过滤之后，能够得到满足条件的数据，但是我想再次用这个把数据还原$table.bootstrapTable("filterBy",{role:""})原来的全部数据

**Comment by wenzhixin** [comment]
麻烦提供下 jsFiddle 例子

**Comment by IamLD** [comment]
I used the following solution.

  $table.bootstrapTable("filterBy")

Removing the parameters, and it can work to back to get all data back .
Maybe you can try with this way.

**Comment by wenzhixin** [comment]
@xiaohan2013 try what @IamLD said.
