### ISSUE TITLE
Reorder Columns extension - data formatter is applied on the wrong column after sorting

### ISSUE THREAD

**Issue by SimaoLiu** [wenzhixin/bootstrap-table#1313]
If enabled re-ordering columns feature with the provided extension, plus a few columns are formatted with data-formatter, and sorting feature is also enabled.
To reproduce:
1) Re-order a column
2) Sort on any column

The data-formatter will be applied to a wrong column.

**Comment by djhvscf** [comment]
Close this issue. Same of #1318

**Comment by SimaoLiu** [comment]
I was trying to fix it by modifying the beforeStop function by adding an array to track the formatters along side the fields when re-ordering columns:
<img width="464" alt="screen shot 2015-08-23 at 1 09 57 pm" src="https://cloud.githubusercontent.com/assets/6552184/9429994/8f00af98-4998-11e5-9d13-569181ff6f76.png">
