### ISSUE TITLE
Reorder Columns does not offset header when dragging inside of scrollable container.

### ISSUE THREAD

**Issue by Cowdrey** [wenzhixin/bootstrap-table#1314]
I also found the issue on the dragtable github: https://github.com/akottr/dragtable/issues/37

But that repository hasn't been updated in 8 months, so I don't know if it will ever be fixed on their end.

**Comment by Cowdrey** [comment]
http://jsfiddle.net/fhsqydu4/5/ jsfiddle showing bug. Scroll as far right as possible and then attempt to move column.

**Comment by Cowdrey** [comment]
http://jsfiddle.net/fhsqydu4/6/ here is my fix.
Added ```javascript 'style="position:relative;"' ```
to  ```javascript '<div class="fixed-table-body">' ``` in the init container function

**Comment by djhvscf** [comment]
See this pull request https://github.com/wenzhixin/bootstrap-table/pull/1337

**Comment by slampenny** [comment]
Tracked this issue down from the dragtable repo. @Cowdrey, you are a lifesaver. Thanks!
