### ISSUE TITLE
Dropdown list not visible in last row

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1316]
Hi,
I added the dropdown in cell, it is working fine but in last row the dropdown list going inside the div. Please tell me how to get outside the div..

jsfiddle link
http://jsfiddle.net/skfaruk/dq43uypw/4/

![capture](https://cloud.githubusercontent.com/assets/12938449/9377528/83f1eb98-4737-11e5-881b-4d8d8c7650b6.PNG)
 Thank you

**Comment by dabros** [comment]
scroll down

Its added as content inside the wrap, you just not noticing the scroll bar updates and you just need to scroll down to see second option.

**Comment by dabros** [comment]
@faruk77  - thanks for the fiddle this time - see how much easier it is to get an answer ; )

**Comment by faruk77** [comment]
okay but i already thinked what u said but im looking for any other solutions from you anyway thank you so much i will use dropup for last row..

**Comment by wenzhixin** [comment]
Just like @dabros said, and you use `index` param @faruk77 : http://jsfiddle.net/wenyi/dq43uypw/7/

**Comment by wenzhixin** [comment]
ref #472

**Comment by dhayalandeena** [comment]
Hi guys, myself also facing the Same issue, having a dropdown which gets cut off, kindly help me how to do with CSS & Javascript
