### ISSUE TITLE
Reordering Columns does not switch header formatter functions.

### ISSUE THREAD

**Issue by Cowdrey** [wenzhixin/bootstrap-table#1318]
This is apparent when using the editable plugin along with the reordering columns.  Immediately after reordering an editable and non-editable column, columns are correct. After filtering any column, the initBody(true) function fires, and it switches all header formats to the the original format of that column index. 
 I am currently working on a solution, i think it should be be as simple as :
```javascript
var temp = that.header.formatters[colA];
that.header.formatters[colA] = that.header.formatters[colB];
that.header.formatters[colB] = temp;
```
will update if it works.

**Comment by Cowdrey** [comment]
Possible duplicate of https://github.com/wenzhixin/bootstrap-table/issues/1313

**Comment by Cowdrey** [comment]
Created a fix for this, I don't know why I thought a swap was all I needed when you have to shift all the columns.

In the bootstrap-table-reorder-columns.js where you set the dragtable options, I changed the beforeStop function to take a variable:

```javascript
beforeStop: function (reorderInfo) {
```

And I added this to the top of the function:
```javascript
                var startMove = reorderInfo.startIndex - 1;
                var endMove = reorderInfo.endIndex - 1;
                var tempFormatter = that.header.formatters[startMove];

                if (startMove < endMove) {
                    for (var i = startMove; i < endMove ; i++)
                    {
                        that.header.formatters[i] = that.header.formatters[i + 1];
                    }
                }
                else
                {
                    for (var i = startMove; i > endMove ; i--)
                    {
                        that.header.formatters[i] = that.header.formatters[i - 1];
                    }

                }
                that.header.formatters[endMove] = tempFormatter;
```
Seems to be working.

**Comment by djhvscf** [comment]
Can you provide a fiddle in order to test your change and your bug?? @Cowdrey

**Comment by Cowdrey** [comment]
Here is the bug, you can observe it after a reordering a column by one, and then applying a filter. The formatters are applied to their original column indexes.
http://jsfiddle.net/fhsqydu4/2/

Here it is after the fix:
http://jsfiddle.net/fhsqydu4/3/

**Comment by Cowdrey** [comment]
Also I tested SimaoLiu's solution in https://github.com/wenzhixin/bootstrap-table/issues/1313 , and that seems to work as well: 
http://jsfiddle.net/fhsqydu4/4/

It is a lot less code than my solution. I feel like my solution might be slightly more efficient, but it is insignificant.

**Comment by Cowdrey** [comment]
Alright, my code change does not take hidden columns into consideration. Completely disregard my code and use the change from https://github.com/wenzhixin/bootstrap-table/issues/1313

**Comment by djhvscf** [comment]
@Cowdrey please open a new PR with your final solution
