### ISSUE TITLE
select dropdown and div clicks in table cells do not work after pagination

### ISSUE THREAD

**Issue by havok2063** [wenzhixin/bootstrap-table#1321]
I have a status select dropdown in a cell for each table.  I also have a div voting element for upvoting or downvoting in another column.  When the table first loads, changing the status, or the vote, correctly triggers the javascript change and the elements update.  Viewing the console shows the correct print statements.  It works for any of the first 5 items on the first page.  

However, when I switch to the 2nd page, the javascript no longer functions, and nothing happens when I change the status or voting elements.  If I go back to page 1 of the table, these are also now broken, and no longer work.  This looks like a bug to me.  

See the jsfiddle
https://jsfiddle.net/havok2063/30way48v/5/

Any ideas on this?  Thanks.

**Comment by wenzhixin** [comment]
Use `$(document).on('click', '.elemetn', function () {});` to instead:
https://jsfiddle.net/30way48v/6/

**Comment by havok2063** [comment]
@wenzhixin Hi.  Thanks for the fix.  That did it.  FYI, in the future, I think it would be extremely helpful for the users to provide a bit more context or feedback when providing a solution.  Not just for me, but for posterity.  It took me some digging to learn why this solution works.  

For anyone else who reads this, the problem (at least) was that I was using the selector
$('element .class').on('click',event)  
which bound my event to only those elements that existed at the time the DOM was created.  For tables that are paginated, all other pages past page 1 do not appear in the DOM.  This is why my events never fired, after I paginated.  

Changing the selector to $(document).on('click','element class',event) binds the events to the top level document.  This captures all events on elements that currently exist in the DOM as well as any new elements that get added later, e.g. during the table pagination.
