### ISSUE TITLE
operateFormatter for different tables

### ISSUE THREAD

**Issue by BenevidesLecontes** [wenzhixin/bootstrap-table#1322]
Hi all! I have two tables ($table and $table_with_no_options) on same page, and i wan't to have different button icons for each table. I tried everything but no success.
Here is my cod.
<img width="890" alt="screen shot 2015-08-21 at 5 53 11 pm" src="https://cloud.githubusercontent.com/assets/1839361/9418890/c03cf72c-482d-11e5-8f0d-20622e930fed.png">

**Comment by wenzhixin** [comment]
You need to use `formatter` column option: http://issues.wenzhixin.net.cn/bootstrap-table/#options/format.html.
