### ISSUE TITLE
when the length of each data are different, th's width is not the same with tds

### ISSUE THREAD

**Issue by EdisonXu** [wenzhixin/bootstrap-table#1323]
https://jsfiddle.net/kt5aj0o9/

**Comment by djhvscf** [comment]
Please provide a fiddle in order to see the issue

**Comment by EdisonXu** [comment]
Try this th with any dummy data: 
<thead>
            <tr>
                <th colspan="3" data-align='center'>Item Detail</th>
                <th data-field="id" rowspan="3" data-align='center'>Item ID</th>
                <th data-field="size" rowspan="2" colspan="2" data-align='center'>Item Size</th>
                <th colspan="2" data-align='center'>Item Responsor</th>
            </tr>
            <tr>
                <th colspan="2" data-align='center'>Item Common</th>
                <th data-field="color" rowspan='2' data-align='center'>Item Color</th>
                <th data-field="ename" rowspan='2' data-align='center'>Employee Name</th>
                <th data-field="eid" rowspan='2' data-align='center'>Employee ID</th>
            </tr>
            <tr>
                <th data-field="name" data-align='center'>Item Name</th>
                <th data-field="price" data-align='center'>Item Price</th>
                <th data-field="esize" data-align='center'>Euro Size</th>
                <th data-field="asize" data-align='center'>Asia Size</th>
            </tr>
        </thead>

**Comment by EdisonXu** [comment]
new process, after removing the "height" element, the display recovers.
however, how can we set the "height" properly?

**Comment by EdisonXu** [comment]
another issue here, I tried the data as 
````
{
            "id": 0,
            "name": "Item 0",
            "price": "$0",
	    "color":"white",
	    "esize":1,
	    "asize":2,
	    "ename":"Eric",
	    "eid":"010000"
        }
````
and the contents are messed up with the headers. check the "Asia Size" and "Employee Name" columns.

**Comment by wenzhixin** [comment]
Can you run your example use these templates: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports?

**Comment by EdisonXu** [comment]
validation and lint are passed with only 3 warning:
IE compatibility, responsiveness and bootstrap version. 
And I believe none of these would be the root cause.

Could you try the table definition and data mentioned above? It's easy to reproduce.

**Comment by EdisonXu** [comment]
pls check https://jsfiddle.net/kt5aj0o9/ 
you can try deleting

**Comment by dabros** [comment]
possibly related: #1291

**Comment by EdisonXu** [comment]
pls check the content of column "Asia Size" and "Employee Name", for some reason, they've been switched

**Comment by dabros** [comment]
@djhvscf - no time to help here atm, but pls update labels so not 'awaiting reply' still

thnks

**Comment by wenzhixin** [comment]
ref #957
