### ISSUE TITLE
hook for data-editable="true" ?

### ISSUE THREAD

**Issue by three60** [wenzhixin/bootstrap-table#1330]
```
<table data-toggle="table" data-url="../sample.json" data-sort-name="name" data-sort-order="asc" data-show-refresh="true" data-search="true">
    <thead>
        <tr>
            <th data-field="code">Code</th>
            <th data-field="name" data-sortable="true">Name</th>
            <th data-field="email" data-editable="true">Email</th>
        </tr>
    </thead>
</table>
```

I have this example working, in that it edits the dom, but is there a hook in order to save on edit?

**Comment by wenzhixin** [comment]
Here is the docs: http://bootstrap-table.wenzhixin.net.cn/extensions/#table-editable

**Comment by three60** [comment]
I've read the docs, I've gave my table above the id of 'test-table' and tried the following:

`<script type="text/javascript">
		$('#test-table').onEditableSave(field, row, oldValue, $el) {
			alert('saving');
		}
	</script>`

Should this work? It does not for me, do I have something incorrect?

**Comment by three60** [comment]
Finally figured this out.

	`$('#test-table').on('editable-save.bs.table', function(field, row, oldValue, $el){
	    console.log(field);
		console.log(row);
		console.log(oldValue);
		console.log($el);
	});`

**Comment by wenzhixin** [comment]
Great :) , in fact, you can check out this example: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/welcome.html

**Comment by cmdalbem** [comment]
I'm trying the same thing and just like @three60 I found the documentation confusing. However I did get it to work, and I'm afraid the actual thing is a little different: you forgot to add the jquery event parameter. The trigger then should look like this:

`$('#test-table').on('editable-save.bs.table', function(e, field, row, oldValue, $el) {
    // your code here
} );`
