### ISSUE TITLE
新手问题

### ISSUE THREAD

**Issue by lv8218218** [wenzhixin/bootstrap-table#1331]
文翼你好，如何能在getSelections中选择一部分列，放在ajax的参数data中，回传给服务器？能给个小例子吗？

**Comment by wenzhixin** [comment]
`getSelections ` 的返回值是数组，你可以使用 jQuery 方法，或者 for 循环对数组进行过滤就可以了，例如：https://jsfiddle.net/wenyi/82nkwwhe/
