### ISSUE TITLE
Freeze/Fixed Column Support

### ISSUE THREAD

**Issue by junelmujar** [wenzhixin/bootstrap-table#1332]
Hi! Thank you for this wonderful plugin. 

Just want to ask if there's a plan to support fixed/freeze column functionality for bootstrap-table? I think it's the only missing feature to make this plugin feature complete :)

Thanks.

/junel

**Comment by dabros** [comment]
@junelmujar - can you please be more clear what you mean by "fixed/freeze column functionality"

Ideally a fiddle showing a jquery plugin that has this feature - not just a screeshot at least.

**Comment by junelmujar** [comment]
Hi @dabros, sorry for the lack of supporting text/doc. I did search but wasn't able find issue #265 :)

Another plugin already has this but I find bootstrap-table easier to implement and use. See link below.

http://www.jeasyui.com/tutorial/datagrid/datagrid5_demo.html

Based on the demo page, the first two columns are frozen and you can scroll right to view more data.

I hope I'm clear with in describing the feature.

Thanks and GOD speed!

/junel

**Comment by djhvscf** [comment]
I'm working on this feature but until this moment it is difficult to implement.. If you have any code or something that can help us, please share it

**Comment by junelmujar** [comment]
Hi @djhvscf!

You may want to look at these plugins for inspiration and examples:

handsontable.com
http://js.lovelotte.net/jQ/tablefreeze/

Thanks!

/junel

**Comment by dabros** [comment]
@djhvscf - no promises, but if you point me to your fork where you trying this, maybe i can help in my free time : )

**Comment by wenzhixin** [comment]
Added an extension: https://github.com/wenzhixin/bootstrap-table-fixed-columns

**Comment by junelmujar** [comment]
Thanks a lot @wenzhixin! You guys rock!

**Comment by djhvscf** [comment]
Exc! :)

**Comment by michaelsogos** [comment]
Hi guys,

Is also possible to improve this useful extension in a way i can froze the first right column?
