### ISSUE TITLE
"that.$selectItem is undefined" if Table option "searchText" is set.

### ISSUE THREAD

**Issue by TAlProg** [wenzhixin/bootstrap-table#1333]
Hallo, Firefox throw Error **that.$selectItem is undefined** if I set Table option **searchText**.
Exception is thrown under **BootstrapTable.prototype.resetRows** [Line "1751"](https://github.com/wenzhixin/bootstrap-table/blob/master/dist/bootstrap-table.js#L1751).
This is my Test-Code:
```javascript
$('#table').bootstrapTable({
	search		: true,
	searchText	: 'Item 2',
	columns: [{
		field: 'id',
		title: 'Item ID'
	}, {
		field: 'name',
		title: 'Item Name'
	}, {
		field: 'price',
		title: 'Item Price'
	}],
	data: [{
		id: 1,
		name: 'Item 1',
		price: '$1'
	}, {
		id: 2,
		name: 'Item 2',
		price: '$2'
	}]
});
```

**Comment by djhvscf** [comment]
Provide a fiddle in order to debug this case, please. @TAlProg

**Comment by TAlProg** [comment]
Done: [jsfiddle](http://jsfiddle.net/pyf523y4/)
