### ISSUE TITLE
using filter-control with server side pagination results in 2 AJAX queries

### ISSUE THREAD

**Issue by prymitive** [wenzhixin/bootstrap-table#1334]
I wanted to use filter-control plugin and I've noticed that there are 2 identical AJAX queries made if I add any filter. I did some quick debugging and it turns out that the first one is fired by ```this.onSearch(event);``` after that ```this.updatePagination();``` is called and it also causes AJAX query to the server.

https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/filter-control/bootstrap-table-filter-control.js#L434

**Comment by djhvscf** [comment]
Oh! Can you provide a new pull request in order to solve this issue?

**Comment by prymitive** [comment]
I'll try, I need to familiarize myself with this code first

**Comment by djhvscf** [comment]
ok, sure @prymitive

**Comment by knoguchi** [comment]
I commented out the `this.updatePagination()` for now.   There might be a bad effect but so far everything works for my purpose - select filter, pagination.

**Comment by djhvscf** [comment]
Same of #1605
