### ISSUE TITLE
Filter + resetView/resetWidth: problem with width in table header

### ISSUE THREAD

**Issue by shinjiDev** [wenzhixin/bootstrap-table#1335]
Hi
I have this case:
https://jsfiddle.net/shinjidev/kt5aj0o9/1/ (please avoid the data)

I need my table header fixed in the top.
The problem when I try the filter is that just one case does not work properly ("Impresos" in the combobox)

I'm not sure why do I have the problem just in one filter case.
I've tried the refresh with resetView and resetWidth without success.

**Comment by wenzhixin** [comment]
Please use `load` method instead: https://jsfiddle.net/wenyi/kt5aj0o9/4/

**Comment by shinjiDev** [comment]
Thank you @wenzhixin :)

**Comment by shinjiDev** [comment]
Dear @wenzhixin 
I'm not very sure but, Don't you think the problem is the method "fitHeader"? Does It consider the hidden rows?

**Comment by wenzhixin** [comment]
Can you help to verify whether the problem still exists using the latest version, thank you.

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **PR**. Thanks!
