### ISSUE TITLE
[bug] Incorrect row submitted to the detail formatter callback when using client side search

### ISSUE THREAD

**Issue by remi-duvergey** [wenzhixin/bootstrap-table#1338]
Hi Wenzhixin,

The row that is available in the detail formatter callback is not the correct one when using the search feature. It looks like it uses the id in the table post filter as opposed to the original table.

Example: you search for value ABC and get one row out of it, its index was 6 and it is now 0 (because only one row matches the filter). As a result, the row that you get in the detail formatter callback is the original row with an index of 0 when in fact, it should be the original row with an index of 6.

Thank,

**Comment by dabros** [comment]
@remi-duvergey - can you please provide a fiddle or even just a link to an example that shows this, and step by step instructions on how to replicate?

**Comment by remi-duvergey** [comment]
While creating the fiddle I tried the latest version (f9b5807bf3046b7eb3357f68f8a786d5ad918974) and it fixed the problem. My application was using the previous one, also versioned 1.8.1 hence the confusion (984980597772bb307ebecb30f3faa35669ca269b).

Investigating a little bit more, it appears that it was fixed with #980, thanks!
