### ISSUE TITLE
Add button into the data show column dropdown list

### ISSUE THREAD

**Issue by Aorewen** [wenzhixin/bootstrap-table#1339]
Hi,
I've created my buttons to check or uncheck some columns with the show/hideColumn function.
I want theses buttons into the dropdown list of data show column toggle.
I tried to give an id to the list and append my buttons but does'nt work.
Someone got an easy way to do this? 
Thanks a lot,

**Comment by dabros** [comment]
@Aorewen - the showColumns option has a very simple and useable ui

Its not clear what exactly your trying to do otherwise, so please provide fiddle and more detail

**Comment by Aorewen** [comment]
http://imgur.com/guMQiEa

As u can see, i want to put my group of buttons into the showColumns dropdown menu.
The problem is he's generated by the bootstrap-table.js, so i don't know how to interact with him.

If u don't understand me, i'll do a fiddle^^

Ty for u reply, sorry for my english.

**Comment by dabros** [comment]
Yes please, do a fiddle

I would you also incorperate or even use http://bootstrap-table.wenzhixin.net.cn/examples/#events as a base, as i feel callbacks are maybe way to go, so include the callback options and the console.log that shows when they occur

Also please explain a litte more, for starters: 

1. **Do you still need 'showColumns'**? 

2. **What do these new buttons do**?

3. **Why do they need to be in same dropdown**?

4. **Would a custom dropdown to complement or even replace the 'showColumns' dropdown work instead?**

<br/>


Thanks

**Comment by djhvscf** [comment]
@dabros Excellent answer! thanks a lot.. @Aorewen, please double check the dabros' answer.

**Comment by Aorewen** [comment]
First of all, a big thank u for ur time and ur complete answer. U try to understand me and i really appreciate that.

Here's my fiddle, u will understand that my problem is really simple.

1. Do you still need 'showColumns'?

Yes absolutely! My buttons are needed in addition, to quickly set columns to show/hide.

2. What do these new buttons do (and how are they different from showColumns default buttons)?

These buttons show/hide some columns, because they are too much columns to be managed.

3. Why do they need to be in same dropdown?

Only for the UI (and now for my personnal knowledge :))

4. Would a custom dropdown to complement or even replace the 'showColumns' dropdown work instead?

To complement, like I tried to explain before.

Thanks u again.

**Comment by dabros** [comment]
https://jsfiddle.net/dabros/emLthg41/

So this isnt complete, but shows how to add custom items.

My best bet is that the logic inside the function that sets up the header (look for when the event 'postHeader'/'post-header' is called inside bootstrap table js), that is where the behaiviour is added to not close the dropdown on selection.

So look at how those other options created and see what you need to add in the callback to make them work.

You can see from the fiddle how to call that logic only once each refresh (add custom class check else will run twice) and how to add an item with click behaiviour, or just as a string.

Maybe add them as strings then after $.prepend() use a custom class on those buttons or LI to attach behaivour, using a data-attribute to hold a comma seperated list of fields you wanted to affect.

In any case - there is how you add to that ui, and some examples of behaiviour. Look at bootstrap-table.js for how to keep dropdown open and ect.

**Comment by Aorewen** [comment]
Thanks for ur answer, i will study and check it tomorrow morning :)

**Comment by dabros** [comment]
Though, all this said, maybe a better approach is a custom dropdown titled 'layout', with options that affect the columns and anything else you want. 

This way you arnt having to interact with any existing elements, and just use the custom toolbar approach i linked above.

No need for checkboxes either, unless you fixed on that, but if desired you can track the 'selected' state by a js variable and use of callbacks (column-switch.bs.table and post-header.bs.table most likely) which could also reset that selected variable to null and remove the 'selected' class on the matching item.

**Comment by Aorewen** [comment]
If u have the time for it, could u provide me a simple fiddle of that?

**Comment by dabros** [comment]
The 2 links i shared above are good examples, with you just needing to add the logic for what to do onClick ofcourse

**Comment by eltony162** [comment]
I had a similar problem. My solution was only added a new option in drowndop menu call "select all".
http://imgur.com/a/vewWA

**Comment by djhvscf** [comment]
Close this issue because the solution was provided

**Comment by sendilgan** [comment]
the photo and look really looks really really good.. can you add  working fiddle ?
that will be really helpful...........................
