### ISSUE TITLE
Reorder Rows with Paging

### ISSUE THREAD

**Issue by thaxy** [wenzhixin/bootstrap-table#1343]
Hi,

I want to use the row reorder plugin with paging activated. First of all this seems to work only with one page. After I dragged a row and I click on another page the pagination bar disappears.
Is this a known Issue?
[Demo](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-rows.html)

I want the user to reorder the rows. Can anyone point me in the right direction to achieve this?
Or is there a way to add drop down controls to each row? So that I could use something like this as a work around?
![sample](http://lh4.ggpht.com/-pqqW52HD47U/Tfh4jYSmiuI/AAAAAAAAAvQ/UxLnnCQuBRk/image_thumb%25255B11%25255D.png?imgmax=800)

**Comment by wenzhixin** [comment]
Fixed in the develop branch.
