### ISSUE TITLE
Correction of code in toolbar extension

### ISSUE THREAD

**Issue by tvvignesh** [wenzhixin/bootstrap-table#1345]
Line No:176
It is given as:
```
showAvdSearch(that.columns, that.options.formatAdvancedSearch(), that.options.formatAdvancedCloseButton(), that);
```

It should be:
```
showAvdSearch(that.options.columns, that.options.formatAdvancedSearch(), that.options.formatAdvancedCloseButton(), that);
```

And lines 167-170 is not needed (Creates 2 icons for advanced search)

```
html.push(sprintf('<div class="columns columns-%s btn-group pull-%s" role="group">', this.options.buttonsAlign, this.options.buttonsAlign));
        html.push(sprintf('<button class="btn btn-default%s' + '" type="button" name="advancedSearch" title="%s">', that.options.iconSize === undefined ? '' : ' btn-' + that.options.iconSize, that.options.formatAdvancedSearch()));
        html.push(sprintf('<i class="%s %s"></i>', that.options.iconsPrefix, that.options.icons.advancedSearchIcon))
        html.push('</button></div>');
```

**Comment by wenzhixin** [comment]
Thanks for your feedback.

1. After 1.8.0, we use `that.columns` instead of `that.options.columns`, so I think you can update to the latest version.

2. I think the icon is necessary, you can look at the example here: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/toolbar.html

**Comment by tvvignesh** [comment]
i am using version 1.8.1 and i have this problem there. so, i fixed using the mentioned solutions. Moreover, if u have more than 1 table with advanced search in a single page, it has problems.. So, i fixed it by storing the value of the "that" object in an array and storing the index of array in the button's data-* attribute

**Comment by wenzhixin** [comment]
You can check out our example here: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/toolbar.html.

Is there a bug when you using advanced search more than 1 table? Can you help to add a jsFiddle to show the problem? Thanks!

BTW: any pull request is welcome.

**Comment by tvvignesh** [comment]
@wenzhixin I am new to github and I am not aware of how to create pull requests. But, I will create fiddle and link it..

**Comment by wenzhixin** [comment]
OK, reopen this issue and looking forward to your jsfiddle.

**Comment by tvvignesh** [comment]
@wenzhixin : here is the fiddle (without any changes made by me to the library and extension)..

http://jsfiddle.net/tvvignesh/L3b5pp2a/4/

The advanced search option takes columns of a single table and gives it to both tables
