### ISSUE TITLE
scrollTo a specific row number is not working

### ISSUE THREAD

**Issue by deepfriedbrain** [wenzhixin/bootstrap-table#1346]
I'm not able to scrollTo a specific row number. I created a fiddle here http://jsfiddle.net/yf0u35jL/3/ to show the issue. If you click on Scroll to row index 3, it just scrolls to the top. It doesn't scroll to the correct row. 

Please let me know if I'm missing something.

Thanks.

**Comment by dabros** [comment]
Its likely that scrollTo number is not row index, as it never says index.

In fact, if you actually debug and look at the code in bootstrap-table.js (which you should always do at least briefly before posting here) you can see this:



    BootstrapTable.prototype.scrollTo = function (value) {
        if (typeof value === 'string') {
            value = value === 'bottom' ? this.$tableBody[0].scrollHeight : 0;
        }
        if (typeof value === 'number') {
            this.$tableBody.scrollTop(value);
        }
        if (typeof value === 'undefined') {
            return this.$tableBody.scrollTop();
        }
    };


That looks like scrollHeight, nothing bout rowIndex, and id actually lean towards guessing its in px or points.

**Comment by deepfriedbrain** [comment]
@dabros I think you are right that it's not row position at all. But when we are dealing with tables, doesn't it make more sense to work with row numbers instead of pixels and points? 

I ended up using jquery's scrollIntoView (after I had grabbed the row at the specified position) and it gave me the desired result.

Thanks for your help and pointers.

**Comment by dabros** [comment]
@deepfriedbrain - looks like your on the right track.

No offence regarding btw - just remember next time to trace each funciton - you would see pretty quick no scrollTop defined so it had to be jquery function, and just an easy google search.

Lots of people never look first, so its always worth repeating for both you and anyone who reads this (i basically given up on stackoverflow as thousands upons thousands of no-research questions).

**Comment by wenzhixin** [comment]
Added an example: http://jsfiddle.net/wenyi/yf0u35jL/4/

**Comment by wenzhixin** [comment]
@dabros jsFiddle can be added to here: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/jsfiddle_examples.md

**Comment by Kaiido** [comment]
@wenzhixin any way to get this `scrollTo specific row` with pagination ? 
I'd like to be able to switch to the correct page by `uniqueId` and currently I can only think of `"nextPage"` until I find the good one... That's dirty... Maybe I missed something though.
