### ISSUE TITLE
提些需求与建议

### ISSUE THREAD

**Issue by linjiaju8** [wenzhixin/bootstrap-table#1348]
1、列表加载时不管sidePagination是server还是client都能支持{total:xx,rows:[{xx}]}及[{xx},{xx}]的数据形式能？我是觉得客户端的一些配置尽量不要去左右服务端的代码。
2、能不能支持类似滚动条分页方式，现在互联网网站很多地方都使用垂直滚动条分页的方式。
3、如果想贡献代码该怎么做？

**Comment by wenzhixin** [comment]
1. client 是支持的，例如你可以用这两个例子：
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/issues/457.html
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/issues/353.html
重定义 `responseHandler` 函数，如：
```js
responseHandler: function (res) {
    if (this.sidePagination === 'client') {
        return res.rows;
    }
}
```

2. 与问题 #256 为同个需求，可以考虑用 extension 来实现，欢迎提交 pull request。

3. https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests，简单的说：fork 分支 - 提交代码 - 创建 pull request。
