### ISSUE TITLE
使用列formatter之后，该列无法被搜索

### ISSUE THREAD

**Issue by lj52man** [wenzhixin/bootstrap-table#135]
如题，没有使用formatter的列搜索正常。

**Comment by zardaloop** [comment]
@wenzhixin I am still having issue on this, I have version 1.7.0 installed but yet I can't run search on formatter columns. Any idea? 
Did you manage to find a solution to this? @lj52man ?

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle? @lj52man @zardaloop

**Comment by zardaloop** [comment]
I figured that out, I could not search because as well as adding formatter I need to add field as well. Obviously because the only thing that is actually searched are the fields not the content of the formatter.  :)
