### ISSUE TITLE
当一列中的 数字带有特殊符号的时候的排序出现点小问题

### ISSUE THREAD

**Issue by ilovezy** [wenzhixin/bootstrap-table#1350]
你好，我这里有列排序，但是当显示的数字中出现 千分号的时候，排序会出现问题，请看截图
请问具体有什么好一点的解决方案吗

![qq 20150831141632](https://cloud.githubusercontent.com/assets/8774988/9573108/ea736098-4fea-11e5-8fcb-575fc11d8cd2.png)

我看了下 sorter 
是只要在最后加这个 priceSorter就可以吗

![qq 20150831143543](https://cloud.githubusercontent.com/assets/8774988/9573313/93eecdf4-4fed-11e5-803d-635d17a50e52.png)

**Comment by wenzhixin** [comment]
是的，自定义排序
