### ISSUE TITLE
Enhancement: searching and sorting over full data when have server side pagination

### ISSUE THREAD

**Issue by haideraliarain** [wenzhixin/bootstrap-table#1351]
Hi,
I have server side pagination and i would like to have search and sort on complete data. Is there any possibility to do this?

**Comment by dabros** [comment]
@haideraliarain - read the documentation, see the examples

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

many of the examples use server side, such as http://issues.wenzhixin.net.cn/bootstrap-table/ (or with a custom toolbar and queryParam function: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html)

open network panel (F12) and see that uses the data-search="true" default search bar these param passed automattically on every data request.

It is 100% up to YOU to implement server side searching and sorting - by default it passes through all neccessary param, and you can easily use queryParam and responseHandler to implement more custom handling of the data, but the code at the end of that url is what searches and sorts.

**Comment by wenzhixin** [comment]
Just like @dabros , our plugin support the feature: searching and sorting over full data when have server side pagination.
