### ISSUE TITLE
在使用"data-formatter"过程中无法调用$scope定义的方法的问题

### ISSUE THREAD

**Issue by c1240539157** [wenzhixin/bootstrap-table#1352]
1、html页面
<table data-toggle="table" 
       data-show-columns="true"  id="internalTable"  data-sortable="true">
    <thead>
    <tr>
        <th class="text-center" data-field="icon" data-formatter="iconfmtFun">图标</th>
    </tr>
    </thead>
</table>
2、js文件
我使用angularjs的scope定义iconfmtFun方法：
  $scope.iconfmtFun = function (value, row, index) {
        return '<img src="' + value + '" height="30px" width="30px" alt="loading">';
    };
出现的问题：
   $scope.iconfmtFun方法，无法被正确调用。

**Comment by wenzhixin** [comment]
你是否有用 [bootstrap-table-angular](https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/angular/bootstrap-table-angular.js) 插件？

**Comment by c1240539157** [comment]
没有，我是直接引用bootstrap-table文件

**Comment by c1240539157** [comment]
没有，我直接引用bootstrap-table.js文件。

**Comment by c1240539157** [comment]
现在这个可以使用吗，如何使用呢

**Comment by wenzhixin** [comment]
可以，增加了例子：http://issues.wenzhixin.net.cn/bootstrap-table/#integrate/angular

**Comment by c1240539157** [comment]
谢谢啦！我觉得你这个开源项目很有发展前景，目前我在公司也在推广这个项目。
请问，我可以加入你们吗？

**Comment by c1240539157** [comment]
你好，还有一个问题我想问一下。
以下两种代码风格，第一种是直接写在html页面，另外一种是放在js代码。你觉得哪种实现更好。我自己倾向于第二种实现，但是我的主管建议我使用第一种方式。我想听听你的意见。
一、
<table data-toggle="table" data-toolbar="#internalSearchToolbar"
       data-show-columns="true" data-id-field="id" id="internalTable" data="resourceApkInternals" data-sortable="true">
    <thead>
    <tr>
        <th data-formatter="rowLineFun" data-switchable="false"></th>
        <th data-field="id">id</th>
        <th class="text-center" data-field="icon" data-formatter="iconfmtFun">图标</th>
        <th data-field="mapid">mapid</th>
        <th class="col-md-2" data-field="packageName">包名</th>
        <th data-field="name">名称</th>
        <th class="text-right" data-field="downloadCount">下载量</th>
        <th class="text-center" data-field="updateTime">更新时间</th>
        <th class="text-center" data-field="status" data-formatter="statusFun">状态</th>
        <th class="text-center" data-formatter="actionFmtFun" data-events="operateEvents">操作</th>
    </tr>
    </thead>
</table>
二、
$scope.$table.bootstrapTable({
    columns: [{
        title: '#',
        valign: 'middle',
        width: '3%',
        switchable: false,
        formatter: function (value, row, index) {
            return index + 1;
        }
    }, {
        field: 'id',
        width: '5%',
        switchable: false,
        valign: 'middle',
        title: 'ID'
    }, {
        field: 'icon',
        title: '图标',
        width: '7%',
        valign: 'middle',
        formatter: function (value, row, index) {
            return '<img src="' + value + '" height="30px" width="30px" alt="loading">';
        }
    }, {
        field: 'name',
        title: '模块名称',
        width: '10%',
        valign: 'middle'
    }, {
        field: 'style',
        title: '呈现样式',
        width: '10%',
        align: 'left',
        valign: 'middle',
        formatter: function (value, row, index) {
            return $filter('searchLabel')(value, $scope.listViews);
        }
    }, {
        field: 'sequence',
        title: '排序序号',
        width: '7%',
        align: 'right',
        valign: 'middle',
        sortable: true
    }, {
        field: 'remark',
        title: '备注',
        width: '15%',
        valign: 'middle'
    }, {
        field: 'updateTime',
        title: '更新时间',
        width: '12%',
        align: 'center',
        valign: 'middle',
        sortable: true
    }, {
        title: '操作',
        align: 'center',
        width: '25%',
        switchable: false,
        valign: 'middle',
        clickToSelect: true,
        events: 'operateEvents',
        formatter: function (value, row, index) {
            return '<a href="javascript:;" class="edit btn btn-warning" ><i class="fa fa-edit"></i>&nbsp;编辑 </a>&nbsp;&nbsp;' +
                '<a href="javascript:;" class="contents btn btn-info" ><i class="fa fa-language"></i>&nbsp;下挂资源 </a>&nbsp;&nbsp;' +
                '<a href="javascript:;" class="targets btn btn-info" > <i class="fa fa-tags"></i>&nbsp;投放目标 </a>'
        }
    }],
    toolbar: '#moduleSearch',
    showColumns: true,
    dataType: 'json',
    footer: true,
    silent: true,
    resizable: true,
    toggle: true,
    rowStyle: function (row, index) {
        if (index % 2 === 0) {
            return {
                classes: 'active'
            };
        }
        return {};
    },
    classes: 'table table-striped table-hover',
    sortable: true,
    striped: true,
    smartDisplay: true,
    idField: 'id',
    formatNoMatches: function () {
        return '<span>没有找到匹配的记录</span> <a class="btn btn-default btn-sm" data-toggle="modal" data-target="#copyModuleModal"> <i class="fa fa-copy">&nbsp;拷贝</i> </a>';
    }
});

**Comment by wenzhixin** [comment]
当然可以，你可以经常参与到 github 中来，多参加讨论，虽然是英文居多。
其实两种都可以。
第一种是写起来比较快，配合现有的 IDE，可以很快的写好并使用。
第二种是灵活性高，而且可以不用暴露全局变量。
假如你只是简单的展示信息，可以用第一种；项目比较大的话，建议用第二种，可扩展或者迁移到单页面应用。我自己是使用第二种多点。
