### ISSUE TITLE
Angularjs ng-click does not work..

### ISSUE THREAD

**Issue by logeshilink** [wenzhixin/bootstrap-table#1353]
Ours is a Angularjs application and we are trying to use bootstrap-table library.. One of the column has an actionable button clicking on which a modal should open. But the ng-click directive does not seem to work with bootstrap-table.

**Comment by wenzhixin** [comment]
Have you used [bootstrap-table-angular](https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/angular/bootstrap-table-angular.js) extension?

**Comment by logeshilink** [comment]
Yes I had.. Also I tried doing ng-click in the example(angular.html) but could not make it work..

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle or example? 
And I added an example: http://issues.wenzhixin.net.cn/bootstrap-table/#integrate/angular, hope this help.

BTW: Because the extension is not developed by myself, and I am not very familiar with angular, so if you can provide a jsFiddle would be great.

**Comment by logeshilink** [comment]
Hi,

I have created a JSFIddle with the issue. The fiddle is
https://jsfiddle.net/hn6du8a7/36/.

Basically I have used the same code as in
http://issues.wenzhixin.net.cn/bootstrap-table/#integrate/angular. Just
that I have added a ng-click event with the formatter and added a
respective handler to the controller scope. It seems that the click event
does not gets registered.

-Logesh

**Comment by SteveyPugs** [comment]
Did anyone every find a solution to this?

**Comment by strikerjjb** [comment]
Following up! Any fix for this issue as anyone using angular will want to use ng-click functions inside the table to hit functions within the controller.

**Comment by strikerjjb** [comment]
@logeshilink I have a fix for this.  You have to include compile as part of the directive creation and then use it to compile the contents of the element again.  Working plunkr here: http://plnkr.co/edit/MyeotRj4YMR0zpofm8lf

**Comment by GenweiWu** [comment]
then,why the latest version of bootstrap-table-angular.js do not have these related code?
