### ISSUE TITLE
使用'sever'端分页时，无法获取分页数据

### ISSUE THREAD

**Issue by c1240539157** [wenzhixin/bootstrap-table#1355]
1、使用服务端分页，当服务端返回分页数据之后，数据无法加载到bootstraptable中。
如下是我的分页参数配置：
       sidePagination: 'server',
        pagination: true,
        pageList: [50, 100, 200],
然后我通过 $table.bootstrapTable('load', data);这种方式把数据加载到bootstrap-table中。但是数据一直无法加载到页面中。

**Comment by wenzhixin** [comment]
使用 server 的时候需要格式：`{total: 800, rows: []}`，区别见文档：http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by wenzhixin** [comment]
client 是需要 Array，客户端分页；server 是需要 Object，服务端分页。

**Comment by c1240539157** [comment]
我后端返回的是形如:data:{"content"：[],"totalPages":0,"totalElements":0,"last":true,"size":50,"number":1,"sort":null,"first":false
,"numberOfElements":0}的json对象，然后我需要取content的内容:
$scope.$table.bootstrapTable('load', data.content);这样写应该没有问题吧？

**Comment by wenzhixin** [comment]
你试一下，这里有很多例子：http://issues.wenzhixin.net.cn/bootstrap-table/

http://issues.wenzhixin.net.cn/bootstrap-table/#issues/353.html
