### ISSUE TITLE
Does anyone work with bootstrapTable use post method

### ISSUE THREAD

**Issue by QuangMuop** [wenzhixin/bootstrap-table#1356]
I worked ok with bootstrapTable use GET method but when method is POST, it always return "405 method not allowed". Does anyone has example bootstrapTable use POST method (I searched but didn't see anywhere)
     $('#table').bootstrapTable(
			                      { method : 'post',
                        			  ...

**Comment by wenzhixin** [comment]
The default `contentType ` is `application/json`, maybe you can set to the other value, and `ajaxOptions ` option will help. You can use the debug model(F12) to check your network request.

**Comment by holmes2136** [comment]
Maybe you can add bootstrapTalble property data-method="post" and   data-content-type="application/x-www-form-urlencoded"  to stay your request is post ,  hope this helps!"

**Comment by teguhpribadia** [comment]
And Maybe also ,
Your code is actually attempting to make a Cross-domain (CORS) request, not an ordinary POST.
