### ISSUE TITLE
How can I search only the data not the whole formatted data?

### ISSUE THREAD

**Issue by sleefd** [wenzhixin/bootstrap-table#1358]
I use a data-formatter to format a td with css.
But everytime I search something that it will search not only the data but the added css,

How can I avoid this?

**Comment by dabros** [comment]
@sleefd - share what extra css you including, prob as simple as using a classname instead of inline css

**Comment by sleefd** [comment]
@dabros  I think the question is related with issue [142]( https://github.com/wenzhixin/bootstrap-table/issues/135).  

And the initSearch method will search on the formatted data as the source code.

**Comment by wenzhixin** [comment]
We need to search formatted data because when you use formatter, for example like this: 
```js
function formatter(val) {
    return val + 1;
}
```
About search, I will consider to add some new feature to solve these problem.
related to #1157

**Comment by dabros** [comment]
@sleefd - my previous post still applies, please share details so we can avoid this conflicting you, and see if still real need for new feature

**Comment by sleefd** [comment]
@dabros Look at this fiddle [!fiddle](https://jsfiddle.net/sleefd/axeuxw4u/),
If you search b, the two rows will display cause of the blue color contains b.

**Comment by sleefd** [comment]
I've read the doc again ,found a new option  searchFormatter, seems that it can be used to define
whether search of new formatted data.

**Comment by wenzhixin** [comment]
Update to the `src` code and use `searchFormatter` or `data-search-formatter` option:
https://jsfiddle.net/wenyi/axeuxw4u/2/

**Comment by wenzhixin** [comment]
I will release a new version soon.

**Comment by soiefmail** [comment]
data-search-formatter="false" still not works when we are putting data-toggle, data-trigger, data-placement, data-content etc in it as data-formatter. It searches for whole content.

**Comment by wenzhixin** [comment]
@soiefmail In your case the value is: `<a href="www.google.com">a</a>`.

Update: https://jsfiddle.net/wenyi/qc70upbt/

**Comment by vasanthsr** [comment]
Hi Wenzhixin,
May I please know if you have a fix to exclude href values in anchor elements when filtering values? To filter values only what is visible on the table.

Thanks
Vas

**Comment by wenzhixin** [comment]
@vasanthsr you can use the [`customSearch`](https://bootstrap-table.com/docs/api/table-options/#customsearch) option to solve your problem in your example.

**Comment by vasanthsr** [comment]
Thanks @wenzhixin . Using the customSearch, we can filter the columns that can be filtered.
I would still want to search on all the columns in the table. Just that I want to search on the anchor tag's label and not on href.
Can you please suggest a way to do that?
Thanks

**Comment by wenzhixin** [comment]
@vasanthsr online example for you: https://live.bootstrap-table.com/code/wenzhixin/7959
