### ISSUE TITLE
Adjust table dynamically until fixed size

### ISSUE THREAD

**Issue by marccollin** [wenzhixin/bootstrap-table#1360]
i have a basic table

<table id="table" data-search="true" data-show-columns="true" data-pagination="true" data-height="250">
...
</table>

when we put a value for height, table seem to take this space as if there is only element...

Is it possible to take all the height only when there are enough element in the table?

**Comment by dabros** [comment]
@marccollin  - have you tried using css to just apply a 'min-height' rule to the table?

something like:

    ```css
    #mytable{ min-height:200px; }

this might not translate perfect from size you using already, worth hitting F12 to check where data-height actually applying to, but mixing that and a 'max-height' value will acheive your desired result. 

Just play with the values till your happy (i suggest in F12 elements view so real-time tweaking).

**Comment by wenzhixin** [comment]
Do you mean the same feature with #410

**Comment by dabros** [comment]
@marccollin - please update us on whether this solved your issue

**Comment by marccollin** [comment]
@wenzhixin, ya it's the same feature.

**Comment by xyluet** [comment]
i have same issue with this
i want to make fixed header, so i have to use data-height in my HTML right ? for example data-height="300".
but if there is only one row, there still some space below, according to the height, how to make like max-height for this ?

**Comment by dabros** [comment]
@xyluet 

If you tried prescribed approach and height option in plugin itself to no effect, then please either:

A. If EXACT same issue, post here but provide more info, OR
B. If AT ALL different, open a new topic, linking to this

Either way, you need to provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). 

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

**Comment by xyluet** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/18754851/17200887/3aeeb176-54b3-11e6-9f3e-00af3ecc1da9.png)

if i specify data-height and only 1 row, there will be expand some space according to specified height. How to make like max-height ?

**Comment by dabros** [comment]
@xyluet - see my last post again, we need a fiddle

**Comment by xyluet** [comment]
@dabros http://jsfiddle.net/e3nk137y/7806/

**Comment by dabros** [comment]
@xyluet 

Played with it for a while, but put simply, if you use the `data-height` option then that is the HEIGHT of the table, regardless of whatever else you do. You can definitely style the table so that its not so obvious, but it will always stay that height.

If you remove the `data-height` then it will autosize perfectly well, though it does risk becoming massive if large dataset. If you have big tables and DONT want to restrict size with `data-height` then just use `pagination`

Problem solved

**Comment by xyluet** [comment]
@dabros 

Okay, I take your suggest. Big thanks for the response

**Comment by fanshaoer** [comment]
@xyluet hi,dude,did you find the solution about the height when use table-fixed.thanks

**Comment by sqiva** [comment]
@fanshaoer 

http://jsfiddle.net/dndph7c3/1/

You can dynamically set the height using that function. You can check if the height is greater using get height or count the data and dynamically set the height.

**Comment by fanshaoer** [comment]
@sqiva thank you.it sounds good,also it will be more convenient if some feature "data-height-flexible" exists.still thanks!

**Comment by nysmoon** [comment]
Adding thiese CSS styles solved it for me:

```
.fixed-table-container {
	border: none;
	height: auto !important;
}

.fixed-table-body {
	max-height: 400px;
}
```

**Comment by nysmoon** [comment]
@xyluet here is your updated fiddle http://jsfiddle.net/dhvddove/1/

Adding these CSS styles solved it:

```
.fixed-table-container {
	border: none;
	height: auto !important;
}

.fixed-table-body {
	max-height: 400px; 
}
```
