### ISSUE TITLE
card view 

### ISSUE THREAD

**Issue by sururbadrus** [wenzhixin/bootstrap-table#1361]
when data is long as option card view text drop
![card view](https://cloud.githubusercontent.com/assets/14106997/9654992/7e91c8d6-5258-11e5-8466-8dc0ce9603ca.jpg)

**Comment by tmorehouse** [comment]
The field label is `float:left` in the CSS.  You can override the CSS to force  left margin on the field content div to make it line up to the right.  Just note on really narrow screens this may make the "right column" very narrow.

Another option is to force a `clear:left` in css on the field content div.

**Comment by wenzhixin** [comment]
The same problem with: #1253
