### ISSUE TITLE
Can not pull in Json file ?

### ISSUE THREAD

**Issue by rickyspires** [wenzhixin/bootstrap-table#1362]
Hello.

I can not get my json file to populate the tables . Please  could someone help.

I am using this code: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/welcome.html

In the table they use data-url="/examples/bootstrap_table/data" - But this files does not exist in the download.

I have changed that to point to mine which is data-url="../../Scripts/data/data1.json" (I know this path is correct).

it look like this:

<code>
    [{
    "id": "1",
    "name": "name1",
    "price": "10"
    }, {
    "id": "2",
    "name": "name2",
    "price": "11"
    }]
</code>

my table looks like this..
filter id = filter-bar-inv
table id = table-inv

<code>
           data-toolbar="#filter-bar-inv"
           data-search="true"
           data-show-refresh="true"
           data-show-toggle="true"
           data-show-columns="true"
           data-show-export="true"
           data-detail-view="true"
           data-detail-formatter="detailFormatter"
           data-minimum-count-columns="2"
           data-show-pagination-switch="true"
           data-pagination="true"
           data-id-field="id"
           data-page-list="[10, 25, 50, 100, ALL]"
           data-show-footer="true"
           data-side-pagination="server"
           data-url="../../Scripts/data/data1.json"
           data-response-handler="responseHandler"></table>
</code>

My Js looks like this the same as https://github.com/wenzhixin/bootstrap-table-examples/blob/master/welcome.html. except i have chaned this:
<code>
    var $table = $('#table-inv'),
    $remove = $('#remove-inv'),
    selections = [];
</code>

Please  help.

Thanks
Ricky

**Comment by wenzhixin** [comment]
The first problem, please check out the usage docs: https://github.com/wenzhixin/bootstrap-table-examples#usage.

After you change url to `data1.json`, you need to change `data-side-pagination="server"` to `data-side-pagination="client"`.

examples: 
http://issues.wenzhixin.net.cn/bootstrap-table/#options/client-side-pagination.html
http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html

**Comment by rickyspires** [comment]
Hello. 
Thankyou fr your reply .
I have changed it to data-side-pagination="client" but I am still not getting anything at all from the json file ?

**Comment by wenzhixin** [comment]
View the source here: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/client-side-pagination.html

**Comment by dabros** [comment]
@rickyspires - you have alot of data options selected, but arnt clear on whether you even checking for errors in console log, or what the network request says.


First debug it, like you would anything javascript and web related

Chrome DevTools (network and console panel are what you want to check): https://developers.google.com/web/tools/chrome-devtools/

Chrome js debugger (old version page, lot of detail, but shows various methods more related to tracing unexpected behaivour): https://developer.chrome.com/devtools/docs/javascript-debugging

JS console.log (more about tracing to see what actually happening): http://www.w3schools.com/js/js_debugging.asp



hitting F12 to open web dev and then telling us Exactly what any errors you see look like - both js errors as well as 

Try scaling back your table to something like this: http://bootstrap-table.wenzhixin.net.cn/examples/#basic-table-from-url

**Comment by jpook101** [comment]
I'm having the same issue... rickyspires did you find a fix?

**Comment by rickyspires** [comment]
Hello Jpook101.

I just removed the data-toggle="table".
If you use data-toggle="table" it works from external json. If you don't it works from js.

I.e 
EXERNAL
<table id="table-inv" class="table table-bordered table-hover dataTable" data-url="../../Scripts/data/invoice.json" data-toggle="table">

My JSON:

[
    {
      "invno": "23543"
    },
    {
      "invno": "346324534"
    }
]

**Comment by jpook101** [comment]
Thanks for the Reply, any help you can give. I really like this table layout  compared to other tables I have working with json files. 

*  I've been looking at the example (most above my head)  
*  I'm testing with MS Visual Studio 2013
*  HTML page (will be asp when in production)
* jquery-2.1.4.js
* This is for all internal company domain/network. 

Why would this not work, I must be missing something? 

==========================================
body
    div class="container"
              table id="table"
               data-toggle="table"
               data-height="460"
               data-search="true"
               data-url="../Json_Data/testdata/JsonEx2.json"
            thead
                tr
                    th data-field="id">ID</th
                    th data-field="name">Item Name</th
                    th data-field="price">Item Price</th
                tr
            thead
        table
    div
 body


Json file:
---------------------------------------------------------------------------- 
[
    {
        "id": "0",
        "name": "Item 0",
        "price": "$0"
    },
    {
        "id": "1",
        "name": "Item 1",
        "price": "$1"
    },
    {
        "id": 2,
        "name": "Item 2",
        "price": "$2"
    },
    {
        "id": 3,
        "name": "Item 3",
        "price": "$3"
    },
    {
        "id": 4,
        "name": "Item 4",
        "price": "$4"
    }
]

**Comment by wenzhixin** [comment]
Have you used the `http://` to open your test html file? @janborup

**Comment by dabros** [comment]
@jpook101 - Open network panel (F12 in most browsers) then refresh page and see what it says about the json request. 

Id be willing to bet either unrelated js error (console panel) or invalid url, which you can help test by replacing "index.html" in your url bar with "../Json_Data/testdata/JsonEx2.json" when viewing the page.

**Comment by wenzhixin** [comment]
Close this issue, if the problem exists reopen it and provide a jsfiddle.
