### ISSUE TITLE
refresh data dynamically?

### ISSUE THREAD

**Issue by geomajor56** [wenzhixin/bootstrap-table#1363]
First of all, this is an awesome table extension, very easy to enable for a noob like me

question: I'm querying the server for particular data and writing to the same file "station_data_table.json" which is the file in the url. (url: 'assets/php/station_data_table.json',)  When another request is made, the refresh button needs to be clicked in order to overwrite previous data. Is it possible to refresh dynamically? Destroy doesn't seem to delete the data. Any suggestions would be great.

Thanks in advance,

Michael

**Comment by wenzhixin** [comment]
I think you can use `refresh` method, docs: http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

**Comment by geomajor56** [comment]
would this be corrrect      $('#tc').bootstrapTable('refresh', {url:
'assets/php/station_data_table.json'});

or
 $('#tc').bootstrapTable('refresh', {silent: true);

can't seem to get these working in the console

**Comment by geomajor56** [comment]
never mind got it, I'm an idiot. Forgot I changed table id.
$('#data-table').bootstrapTable('refresh', {url:
'assets/php/station_data_table.json'});
worked fine.

thanks for your help

**Comment by dabros** [comment]
Look at the numerous examples and clear doco on this.

http://issues.wenzhixin.net.cn/bootstrap-table/#methods/refresh.html

'refresh' can be called from anywhere, including callbacks.

Look at http://issues.wenzhixin.net.cn/bootstrap-table/index.html and hit F12 then view console to see all events being logged. Find one or more that fits you, then see code in that examples that uses a generic loop for most events and specific handlers for others, any event can a specific handler - just find which ones fit you.

Also know that most actions do automattically refresh, if side-pagination="client" at least.

Find an actual use-case where you NEED to refresh, and prove to yourself that its not handled automattically - then add in callbacks or code elsewhere to trigger that refresh when needed.

**Comment by geomajor56** [comment]
thank you so much for the advice. thats a good way to go about things

**Comment by geomajor56** [comment]
It's me again. I'm trying to implement the tableExport.jquery.plugin and I
think I'm missing something. The source files load properly and the export
toggle button appears but it won't download when picking a default format.

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.8.1/extensions/export/bootstrap-table-export.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2014-11-29/FileSaver.min.js"></script>

 <table id="data-table"></table>

$('#data-table').bootstrapTable({
        method: 'get',
        url: 'assets/php/station_data_table.json',
        cache: false,
        refresh: true,
        height: 650,
        striped: false,
        pagination: true,
        pageSize: 100,
        pageList: [10, 25, 50, 100, 200],
        search: false,
        showToggle: true,
        showColumns: true,
        showExport: true,
        showRefresh: true,
        minimumCountColumns: 2,
        clickToSelect: false,

...

any help would be greatly appreciated

**Comment by geomajor56** [comment]
forgot to add the error: Uncaught TypeError: that.$el.tableExport is not a
function

**Comment by wenzhixin** [comment]
@geomajor56, you need to import the plugin script: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/export.html#L13.
