### ISSUE TITLE
Table filtering

### ISSUE THREAD

**Issue by ahyoon** [wenzhixin/bootstrap-table#1366]
@djhvscf @wenzhixin I face many problem when doing table filtering. So i would like start all over again.. So first, i download the latest file which is version 1.8.1 rite? and may i know where is the location of this few file :

```javascript
<script src="bootstrap-table-filter-master/src/bootstrap-table-filter.js"></script>
<script src="bower_components/bootstrap-table-filter-master/src/ext/bs-table.js"></script>
```

I follow the path, but i couldnt find the file or folder..

**Comment by ahyoon** [comment]
hello?? @djhvscf @wenzhixin can help me on this matter?

**Comment by djhvscf** [comment]
Hi, the filter extensión is here https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/filter and the other file is here https://github.com/lukaskral/bootstrap-table-filter/tree/master/src/ext
