### ISSUE TITLE
fixedScroll问题；请问这个问题是由bootstrap.min.js为3.3.5版本造成的吗，Load无法加载数据

### ISSUE THREAD

**Issue by lv8218218** [wenzhixin/bootstrap-table#1367]
![image](https://cloud.githubusercontent.com/assets/13183213/9681270/671c38f8-532f-11e5-802a-1cc1bda82b0f.png)

**Comment by wenzhixin** [comment]
你的data数据的格式不对

**Comment by lv8218218** [comment]
多谢，用bootstrap-table-flat-json.js解决了！
