### ISSUE TITLE
cardVisible in column options not working?

### ISSUE THREAD

**Issue by vangras** [wenzhixin/bootstrap-table#1368]
Hi, I upgraded to v1.8.1 - 2015-08-24 and cardVisible doesn't seem to be working anymore.
If I revert back to v1.8.1 - 2015-05-29 it works fine.

Have specifics changed or is it broken?

Thanks in advance!

**Comment by djhvscf** [comment]
Can you provide a fiddle?

**Comment by vangras** [comment]
Here you go :)
https://jsfiddle.net/g63ab8p5/

Thanks!

**Comment by wenzhixin** [comment]
Can you provide two version: works fine and doesn't work? With the `.js` file instead of `.min.js`.

**Comment by vangras** [comment]
Non working version (v1.8.1 - 2015-08-24): https://jsfiddle.net/g63ab8p5/2/
Working version (v1.8.1 - 2015-05-29): https://jsfiddle.net/2dqsdxgs/

Unfortunately I don't have the non-min js files for version v1.8.1 - 2015-05-29 (working version).

**Comment by djhvscf** [comment]
I think this is working now, if not please open it again @vangras

**Comment by theo222** [comment]
Setting cardVisible=false has no effect in versions 1.10.0 and 1.10.1 
```
...
{
  title: 'Item ID',
  field: 'Id',
  visible:false,
  cardVisible:false, //<---
  footerFormatter: totalTextFormatter
},
...
```
