### ISSUE TITLE
Issue with export plugin export types

### ISSUE THREAD

**Issue by meetraz** [wenzhixin/bootstrap-table#1369]
When using data attributes for my table, this does not work:

`<table data-show-export="true" data-export-types="excel,pdf">`

This does not work either:

`<table data-show-export="true" data-export-types="[excel,pdf]">`

Only this works:

`<table data-show-export="true" data-export-types="['excel','pdf']">`

**Comment by djhvscf** [comment]
This is not an issue because the plugin is expecting an export types array (string) so you have to pass it as array
