### ISSUE TITLE
Refresh Method & 'data' Property

### ISSUE THREAD

**Issue by coolrblue** [wenzhixin/bootstrap-table#137]
Hello Wenzhixin, Thank you for the brilliant work. I found your library recently and utilising it in one of my works which is very neat & useful. I've a question regarding the 'refresh' method of the plugin. When the table is initialized with 'data', whose value is supplied infact by a js function that performs an AJAX call that returns a post-processed output, instead of 'method & url' properties, the refresh do not seem to work. 

Currently, the only way that occurs to me to workaround this problem is to destroy the table and re-initialize. Is it possible to find out why the refresh does not work when the 'data' property is set?

**Comment by jaydeepgiri** [comment]
It Worked for me too.. Thank you wenzhixin..

**Comment by achao123** [comment]
Hi, I having the refresh problem on IE version 11, but is working fine on Chrome and Firefox, any idea? I am using the given syntax but no good.

<pre>$('#table').bootstrapTable('refresh', {url: 'yourUrl'});</pre>

appreciate you can help, thank you in advance.

**Comment by HyramTang** [comment]
I can't work 'refresh' function on the IE 11

**Comment by HyramTang** [comment]
I used another way to solve it，destroy table and redraw
