### ISSUE TITLE
Table export including footer

### ISSUE THREAD

**Issue by meetraz** [wenzhixin/bootstrap-table#1371]
All of my tables have a footer row for the totals amounts. When I export to Excel or PDF, the footer row is missing.

**Comment by djhvscf** [comment]
I'm not sure but I think this feature is not supported in this plugin

**Comment by meetraz** [comment]
If you export a table, all table rows should be exported. The header is included, just not the footer.

**Comment by wenzhixin** [comment]
Yes, now this feature is not supported.

**Comment by andrius-senulis** [comment]
+1 This feature would be great to have.

**Comment by katrina-engelbrecht** [comment]
This feature would be great to have.

**Comment by ibraheemhlaiyil** [comment]
I've changed bootstrap-table-export.js to support this functionality.

See this pull request: https://github.com/ibraheemhlaiyil/bootstrap-table/pull/1

**Comment by wenzhixin** [comment]
Please create PR to this repo and provide a jsfiddle example, thanks @ibraheemhlaiyil

**Comment by ibraheemhlaiyil** [comment]
Use data-export-footer="true" or exportFooter=true to use this feature.

See fiddle: http://jsfiddle.net/dzmzoro9/7/

**Comment by wenzhixin** [comment]
Merged

**Comment by winoth** [comment]
When we use "data-detail-view="true"" - export Table with footer is Not Working.
Because of Column out of bound exception. (column count start count form detail-view)

**Comment by aditya2592** [comment]
When I am exporting the table along with footer, I am getting one row less in the CSV file. The footer is present in the CSV. CSV export without the footer contains all rows. Has anyone faced this issue ?

**Comment by guillermoizqgar** [comment]
Im having some troubles to get the footer export. If I try to export with all rows, I dont have any problem but if I search something in the table and then I try to export, it just exports the footer, what can cause this problem?? Anyone with the same issue??
