### ISSUE TITLE
NULL values included in SORT of TIME column data

### ISSUE THREAD

**Issue by trainspotting** [wenzhixin/bootstrap-table#1373]
When you use BootstrapTable sort on data taken from a SQL database TIME format column, any null values are INCLUDED when they shouldn't be. 

So as a simple example, assume data is 1:00:00, 2:00:00, NULL

Sorted Ascending SHOULD show: 1:00:00, 2:00:00, NULL
Sorted Descending SHOULD show: 2:00:00, 1:00:00, NULL 

The problem is on the Sort Ascending when BootstrapTable delivers NULL, 1:00:00, 2:00:00.... so when you have lots of data and are looking to find the lowest with an ascending sort, you get presented with lots of blank entries first.

Is this fix-able?!?!? Thanks!

**Comment by djhvscf** [comment]
Please provide a fiddle

**Comment by trainspotting** [comment]
Thanks for taking a look... here's the fiddle where you can see the issue with the empty fields dominating the sort when you wouldn't want them too (sort the second column to see what I mean)

https://jsfiddle.net/88Lpwoy1/

**Comment by trainspotting** [comment]
..and as you can see this Fiddle uses HTML table data.. same issue as what I had with my SQL "NULL" data. Seems to be any empty data that gets assumed to be lower than the lower real values when sorting, rather than being left to display after the sorted values that do exist.

**Comment by wenzhixin** [comment]
Because the bug #161, we deal with the `null` value before sort, and I think the result `[NULL, 1:00:00, 2:00:00]`, `[2:00:00, 1:00:00, NULL]` is acceptable.

If you want to sort by what you said, you can try this: https://jsfiddle.net/wenyi/88Lpwoy1/1/.

**Comment by trainspotting** [comment]
Thanks for the fiddle which works perfect.

On my own site unfortunately the... 

var $table = $('#table');
...is throwing this error....
 Uncaught TypeError: $ is not a function 

..So I'm trying to work out why. :-(
But I can't dispute the Fiddle has the perfect end-result!

**Comment by djhvscf** [comment]
I think you are not including the jquery reference

**Comment by trainspotting** [comment]
You are of course 100% right. Thank you. I had assumed the jQuery with Joomla was enough but when I added the jQuery javascript in direct it now works fine. THANKS. Everything sorted now!

**Comment by djhvscf** [comment]
Great!

**Comment by superphonic** [comment]
Just a small update to @wenzhixin jsFiddle. The fiddle as is also dumps 0 values to the end of the table which is probably not what you want. Use `(typeof a === 'undefined')` and `(typeof b === 'undefined')` if you only want truly undefined values to be dumped at the end of the sort, and zeros to be grouped with your other data.
