### ISSUE TITLE
Mergin header columns 

### ISSUE THREAD

**Issue by abazanvillanueva** [wenzhixin/bootstrap-table#1375]
Hi, I'm new on bootstrap-table. So I want to do the same of this
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/group-columns.html
but It seems not to work for me. Someone have the time enougth to show me the way? Thanks

**Comment by wenzhixin** [comment]
So, what's your problem?

**Comment by whilxx** [comment]
Hello, i have trouble to make the header work right, i have this table:
```
<table data-toggle="table">
    <thead>
        <tr><th rowspan="2">car</th><th colspan="3">06  04 2015</th></tr>
        <tr><th>lt</th><th>cost</th><th>tot</th></tr>
    </thead>
    <tbody>
        <tr><td>123</td><td>2</td><td>123.123</td><td>135</td></tr>
        <tr><td>0</td><td>1</td><td>14.35</td><td>1.95</td></tr>
        <tr><td>2</td><td>85</td><td>1.35</td><td>23.75</td></tr>
        <tr><td>23 text</td><td>2</td><td>35</td><td>623</td></tr>
    </tbody>
</table>
```
 and the result shows 2 rows in the header with the same column names, like this

![image](https://cloud.githubusercontent.com/assets/14186896/9746571/4781287a-563e-11e5-9e05-7e446563ad72.png)

**Comment by abazanvillanueva** [comment]
My problem is the same as whilxx's. Help for us, please

**Comment by abazanvillanueva** [comment]
https://github.com/wenzhixin/bootstrap-table/commit/53bf246e1f4f466d82e47c5130336d088e65117f

This is the solution.
