### ISSUE TITLE
Cheked rows becomes unchecked when search 

### ISSUE THREAD

**Issue by nefrexia** [wenzhixin/bootstrap-table#1376]
Hello.

I'm using a selectable list whith the search option like here http://issues.wenzhixin.net.cn/bootstrap-table/

if you check some elements on the list (for example 3, 4 and 5), 
make a search (for example 8)
select some rows (for example 8)
delete the "8" in the search field to get the original view.

Then the first checked elements (3, 4 and 5) are not checked.

Is it normal ?
Is there one way to memorize the checked rows even making researches ?

**Comment by wenzhixin** [comment]
Here is an example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/917.html

**Comment by wenzhixin** [comment]
How to maintain selected on server side.

**Comment by wenzhixin** [comment]
This issue is not a bug.
