### ISSUE TITLE
Dropdown menu for columns cropped by CSS

### ISSUE THREAD

**Issue by vicentor** [wenzhixin/bootstrap-table#1377]
![Cropped](https://cloud.githubusercontent.com/assets/2099885/9721014/76244bb2-5562-11e5-8e14-c32836feba85.png)

I think that the CSS should make it so it shows on top of anything instead of on top of itself only.
To reproduce, simply have 6-7 columns and no rows in your table, you'll see it right away.

**Comment by wenzhixin** [comment]
I think this issue is not a bug, you can set the `height` option of the table.

**Comment by vicentor** [comment]
It could be considered a enhancement, we want the table to be as small as possible and adding the height to fit all the columns would make it at least triple its size. (there is 10 columns)

**Comment by djhvscf** [comment]
This issue is fixed. See this: http://jsfiddle.net/djhvscf/e3nk137y/5425/ @vicentor
