### ISSUE TITLE
table bootstrap clear my inline css of td 

### ISSUE THREAD

**Issue by loadingpoint** [wenzhixin/bootstrap-table#1378]
<td style="color: #fff; background-color:' . $data['color'] . ' !important;">' . $data['product'] . '</td>'
This is my inline css, i want to apply css dynamic that fetch from database,
but when i use table-bootstrap it has clear my css
i use firebug and see style of td it's became blank (style='')
how i keep my inline css?

**Comment by djhvscf** [comment]
You can use the data-row-attributes function in order to add custom attributes to your rows

**Comment by wenzhixin** [comment]
The same with #1301, in your case, you can define:
```
<style>
.red {
    color: #fff;
    background-color: red !important;;
}
.red {
    color: #fff;
    background-color: black !important;;
}
...
</style>
<td class="$data['color']">' . $data['product'] . '</td>'

**Comment by loadingpoint** [comment]
Thank all,
but i can't define css in <style> tag, because color that fetch from db, and it's dynamic color(>200 colors)
have any idea that keep inline-css of <td> tag?

**Comment by wenzhixin** [comment]
Try this:
```
'<td><div style="color: #fff; background-color:' . $data['color'] . ' !important;">' . $data['product'] . '</div></td>'
```
