### ISSUE TITLE
和 editTable 配合出现的一些问题

### ISSUE THREAD

**Issue by MittWillson** [wenzhixin/bootstrap-table#1379]
我按照extensions上的源码改了我已经写好的页面 但是刷新后出现一个致命错误
TypeError: undefined is not an object (evaluating 'obj.length') 
  不知道有什么需要改的 另外您有QQ群之类的么 因为最近我一直在写网页 可能会遇到很多这样的问题 即时通讯的话会比较容易解决问题

**Comment by wenzhixin** [comment]
QQ 群：103558783，你这个问题貌似描述不太清楚，在群上讨论吧。
