### ISSUE TITLE
How can I link text in specified column cells

### ISSUE THREAD

**Issue by SystemF** [wenzhixin/bootstrap-table#1380]
I want to use links in the results (by example: user/{id}/edit), but I can't find out how to achieve this?

Who can tell me? Thanks!

*edit* I use the data json option

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle to show the problem? Maybe you can use `formatter`?

**Comment by SystemF** [comment]
Well I think I should use formatter to surround table cell content with an "a" tag. But I cannot easily find the documentation for this feature.

**Comment by wenzhixin** [comment]
There is an example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/format.html
