### ISSUE TITLE
mergeCells方法没有效果！？

### ISSUE THREAD

**Issue by xiaohan2013** [wenzhixin/bootstrap-table#1382]
$tableExpense.bootstrapTable("mergeCells",{index:9,field:'selected',rowspan:1,colspan:10})

**Comment by wenzhixin** [comment]
例子：http://issues.wenzhixin.net.cn/bootstrap-table/#methods/mergeCells.html

**Comment by xiaohan2013** [comment]
我是这样用的
$tableExpense.bootstrapTable({
    xxx:"xxx",
   ......
});
$tableExpense.bootstrapTable("mergeCells",{index:9,field:'selected',rowspan:1,colspan:10})

mergeCells方法没有通过其他事件去触发！
我现在的需求是要在10条数据后加上一行【加载更多。。。】

**Comment by wenzhixin** [comment]
你的需求需要自己实现
