### ISSUE TITLE
When I use data-mobile-responsive="true" I get TypeError: this.$selectAll is undefined

### ISSUE THREAD

**Issue by rickyspires** [wenzhixin/bootstrap-table#1384]
Hello.
When I use data-mobile-responsive="true" I get TypeError: this.$selectAll is undefined in my console log.

TypeError: this.$selectAll is undefined

```
bootstrap-table.js (line 1964, col 8)
/**
 * @author zhixin wen <wenzhixin2010@gmail.com>
 * version: 1.8.1
 * https://github.com/wenzhixin/bootstrap-table/
 */

            this.$selectAll.prop('checked', this.$selectItem.length > 0 &&
            this.$selectItem.length === this.$selectItem.filter(':checked').length);
```

This is my mobile file:
```
/**
 * @author: Dennis Hernández
 * @webSite: http://djhvscf.github.io/Blog
 * @version: v1.1.0
 */
```

Thank you.

**Comment by rickyspires** [comment]
No worries. 
Do the same thing with css ;)
http://bootsnipp.com/snippets/featured/no-more-tables-respsonsive-table

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports) to show the problem, thanks.

**Comment by djhvscf** [comment]
Close this issue because the user did not provide a example
