### ISSUE TITLE
sending data from one table to another  table

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1386]
![capture](https://cloud.githubusercontent.com/assets/12938449/9735326/94c350e0-5657-11e5-94df-b2003d5e5a2e.PNG)

Hi please check the above image is there any possiblity  to send selected column data from one table to another and according to that we should adjust the pagination.
can we achieve this using bootstrap table?

**Comment by wenzhixin** [comment]
I think you can use `getSelections` method to do that.

**Comment by faruk77** [comment]
ok but what about pagination ? 
If i send a row to another table, is pagination will get update?

**Comment by dabros** [comment]
@faruk77 - how bout you do and tell us

**Comment by djhvscf** [comment]
Close this issue because the user did not provide a example
