### ISSUE TITLE
cells jumping

### ISSUE THREAD

**Issue by Megido6** [wenzhixin/bootstrap-table#1387]
look cells border 
https://i.gyazo.com/eaa3edcdf11981b22ca9d84ef447cfcc.png
https://i.gyazo.com/71072ba688ccd6c580b8bfb5ffc5252e.png

**Comment by wenzhixin** [comment]
Can you provide more information about your problem? 
The faq: bootstrap-table.wenzhixin.net.cn/faq may be help.

**Comment by Megido6** [comment]
you see table border? it shifted each reload page or when I change the page scale

**Comment by wenzhixin** [comment]
Please check out the FAQ.
