### ISSUE TITLE
The radio checkbox works in current page but selecting a different radio button on another page keeps the previous one selected.

### ISSUE THREAD

**Issue by NitinKumarPathak** [wenzhixin/bootstrap-table#1390]
So if i have a row selected using a radio button and when i toggle over to another row, it works just fine, but if i navigate to another page and select another row, the radio button on the other page is kept selected along with this one. This works perfectly fine with regular checkbox.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports) to show the problem, thanks.

**Comment by NitinKumarPathak** [comment]
Here is the fiddle: https://jsfiddle.net/31hnkasr/1/

**Comment by kikonjar** [comment]
I have the same problema. This is my jsfiddle: http://jsfiddle.net/dxcm4a46/

**Comment by wenzhixin** [comment]
Fixed this bug: http://jsfiddle.net/wenyi/dxcm4a46/1/

**Comment by NitinKumarPathak** [comment]
Thank you!
