### ISSUE TITLE
Problem with header IE8

### ISSUE THREAD

**Issue by shinjiDev** [wenzhixin/bootstrap-table#1392]
Hi
I've tried to use bootstrap-table in IE8, everything works fine, but there is a problem when I define a height to the table

http://prntscr.com/8eajnz

As you can see the fixed header is not aligned with the original header. Could you help me please?

Regards

**Comment by shinjiDev** [comment]
Any clue to solve this problem? :(

**Comment by djhvscf** [comment]
I don't see the problem in your screenshot @shinjiDev

**Comment by shinjiDev** [comment]
Try to look the column "Dirección". There you can see that the header is duplicated.

**Comment by wenzhixin** [comment]
I think this problem is solved is the latest version.
