### ISSUE TITLE
Accessibility keyboard when sorting with <th>

### ISSUE THREAD

**Issue by aureliet** [wenzhixin/bootstrap-table#1393]
Hello Wenzhinxin (and the others),

I don't see anything, in order to make the table accessible, when we want to sort it with the `<th>` like in my example : 
http://jsfiddle.net/6nj4nnwu/

Did I miss something ?

I see it is possible, in https://www.datatables.net/

On the datatables.net tables, when I am on a `<th>` through the tabulation, when I press Enter, it sorts it.

You will say "So why don't you use datatables ?"
Well... I tried it too, but I really prefer your bootstrap-table ;-)

Thank you very much,

Aurélie

**Comment by djhvscf** [comment]
I think this is so easy to implement, let me try it @aureliet

**Comment by aureliet** [comment]
Thank you, @djhvscf ! :-)

And I'm trying to understand how to make work the fixed columns, which are presented here, too ;-)
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/fixed-columns.html

I'm new on Github, so maybe I don't search as I should do.

**Comment by djhvscf** [comment]
Did you check this? https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/fixed-columns.html

**Comment by aureliet** [comment]
Yeah, thank you ! :-)

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/e3nk137y/3062/ @aureliet

**Comment by aureliet** [comment]
Hello @djhvscf 
I'll try it tomorrow, when I'll be at work, to see if I can make it work with my project :-)
Thank you again :-)

**Comment by aureliet** [comment]
Impeccable ! it works very well on my project !
Thank you again, @djhvscf !
