### ISSUE TITLE
Sorting column of images

### ISSUE THREAD

**Issue by ptep** [wenzhixin/bootstrap-table#1396]
Trying to get sorting working for columns where images (through custom formatter) are shown to represent data. Any ideas?

Rows with more images on top, then those with fewer, then those without any images on bottom.

http://jsfiddle.net/a9a4yxqw/25/

Thanks!

**Comment by ptep** [comment]
hmm... no ideas?

**Comment by wenzhixin** [comment]
You can try to use `sorter` column option to define the custom sort: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-sort.html

**Comment by djhvscf** [comment]
Solution provided. Close this issue
