### ISSUE TITLE
bootstrap-table-filter ajaxSelect type doesn't fire after the first time

### ISSUE THREAD

**Issue by lynjhim** [wenzhixin/bootstrap-table#1398]
I'm using version 1.6.0, and for reasons i can't mention, updating the version is not an option for me. I'm not sure if this has been address in the newer version but here it goes. Our bootstrap-tables are using bootstrap-table-filter for filtering, on page load both the table and filter loads with values. the filter initially loads with column names that are also the column headers in the table. each of those column names in the filter is configured as "ajaxSelect" of type and the source for each item points to a public ActionResult in the server-side. this ActionResult is the one that gets the distinct values of the selected column name from the entity and loads them in the filter. Supposedly, each time you put a check mark on a column name in the filter should fire the ActionResult to retrieve the updated distinct filter values for that column. The issue is that the filter only fires the ActionResult once, only the first time you selected the column name from the filter. So the filter values for each column doesn't get updated because after the first time, it will never trigger the ActionResult again. What's weird is that it triggers the ActionResult everytime only when you have the browser debugger (F12) open.

if you guys think this issue was already addressed in the newer version, just let me know. I might take a look on the ajaxSelect code see what i can do with my current version of bs table. Otherwise, need guidance on what is going on and maybe propse a work around on how i can make my ActionResult fire everytime.

**Comment by lynjhim** [comment]
Nevermind, stupid of me it was just cache property of $.ajax call.

**Comment by wenzhixin** [comment]
There is a `cache` option: http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by lynjhim** [comment]
Oh ok. Thanks! I'm a new user of your library, haven't really explored everything yet.
