### ISSUE TITLE
Question: Sorting un-unified data

### ISSUE THREAD

**Issue by oneGregWiley** [wenzhixin/bootstrap-table#140]
I'm trying to sort something with different markup, but same data:

Inside a cell, you may find:

`<div class="something somethingElse">{{NumberToSort}}</div>`

How do I get bootstrap-table to sort by `{{NumberToSort}}` instead of `<div class=...`

**Comment by wizeird** [comment]
I figured out a solution for this issue.

Replace this (comment it out ):

                /*** OLD CODE BEGINS HERE ***/
                var aa = a[name],
                    bb = b[name],
                    value = calculateObjectValue(that.header, that.header.sorters[index], [aa, bb]);
                /*** OLD CODE ENDS HERE ***/

With this, inside the bootstrap-table.js file:

               /*** NEW CODE BEGINS HERE ***/
                var aa, bb;
                
                //If the column has a custom formatter function
                if (that.header.formatters[index] !== undefined) {
                    var formattedValueForRowA = calculateObjectValue(that.options.columns[index],
                        that.header.formatters[index], [value, a, index], value),

                        formattedValueForRowB = calculateObjectValue(that.options.columns[index],
                        that.header.formatters[index], [value, b, index], value),

                        value = calculateObjectValue(that.header, that.header.sorters[index], [formattedValueForRowA, formattedValueForRowB]);

                    aa = formattedValueForRowA,
                        bb = formattedValueForRowB;
                
                } else {
                    aa = a[name],
                    bb = b[name],
                    value = calculateObjectValue(that.header, that.header.sorters[index], [aa, bb]);
                }
                /*** NEW CODE ENDS HERE ***/

The above new code ensures that if a column has a custom formatter defined by the programmer then the column values obtained from that formatter will be used.
