### ISSUE TITLE
column "visible: false" doesn't work correctly when it's set as default sort by

### ISSUE THREAD

**Issue by szmeku** [wenzhixin/bootstrap-table#1401]
For given column
```javascript

columns: [{
            field: 'FOO',
            title: 'Foo',
            visible: false     
        },
```

when I set it as default sort by column
```html
<table data-sort-name="FOO" data-sort-order="desc"></table>
```
Foo header is not visible but foo values are still there.

Here's an example https://jsfiddle.net/m6e6st75/1/

**Comment by djhvscf** [comment]
Can you provide a fiddle, please?

**Comment by szmeku** [comment]
https://jsfiddle.net/m6e6st75/1/

**Comment by djhvscf** [comment]
Ok, this is a bug. Any pull request is welcome

**Comment by djhvscf** [comment]
Please update to the latest version. This issue is already fixed
