### ISSUE TITLE
Export function not working on Microsoft Edge navigator

### ISSUE THREAD

**Issue by batistellabr** [wenzhixin/bootstrap-table#1402]
When I try to export some table in Microsoft Edge navigator I got the following error: That’s odd... Microsoft Edge can’t find this page

Does anybody know how to make it work on Edge? It works perfectly on Chrome and Firefox.

Thanks

**Comment by wenzhixin** [comment]
Maybe the plugin does not support Microsoft Edge navigator, we never test in it.

**Comment by djhvscf** [comment]
I'm going to test our plugin in Microsoft Edge Navigator

**Comment by wenzhixin** [comment]
@batistellabr Please discuss this issue in: https://github.com/hhurz/tableExport.jquery.plugin/issues.
