### ISSUE TITLE
Printing a table

### ISSUE THREAD

**Issue by batistellabr** [wenzhixin/bootstrap-table#1403]
Is there any feature in the roadmap to allow a user to print a table using the browser printing funcionality?

If not, do you know any way of doing that? I don't want to export my table to a PDF in order to print it. I simple want my user to print the table he is seeing, but not the rest of the application.

I cannot ask my user to print the page, because my table is paginated. 

Thanks.

**Comment by wenzhixin** [comment]
Now we have the export extension: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html, if it cannot solve your problem I cannot help because the problem is out of our repo.
