### ISSUE TITLE
sub table not work with sort, event

### ISSUE THREAD

**Issue by vunh2301** [wenzhixin/bootstrap-table#1404]
If sort child table -> parent sort.

**Comment by jipexu** [comment]
yeah same prob here

https://jsfiddle.net/jipexu/tpp9a6k5/4/

**Comment by etortato** [comment]
Try this: https://github.com/wenzhixin/bootstrap-table/issues/1712

**Comment by djhvscf** [comment]
Fixed. See #1875 PR

**Comment by wenzhixin** [comment]
Merged, thanks @djhvscf
