### ISSUE TITLE
collapse bootstrap mecanism not work (not synch...) in data-detail-view context ?

### ISSUE THREAD

**Issue by jipexu** [wenzhixin/bootstrap-table#1406]
Hello
I use table with data-detail-view
in the detail view i want to use collapse element (bootstrap class..)
it's not work properly : 
open the detail view (in this is a XX hidden element)
click on the link to show this XX hidden element ==> nothing happens
if i close the detail view and reopen ==> the XX element will be show ....

here is the simple example : 
please play with the second ligne of the table to see ...
https://jsfiddle.net/jipexu/tpp9a6k5/1/

Thanks for any help

**Comment by jipexu** [comment]
https://jsfiddle.net/jipexu/tpp9a6k5/2/

^^^  this is the jsfiddle

**Comment by dabros** [comment]
Adding e.stopProgagation() inside an attached $('.detail-icon').click(function(){...}), that seems to work.

Its obviously a propagation issue, just a matter of testing where to add that line.

https://jsfiddle.net/dabros/vo1npqdx/

I would ask @wenzhixin or @djhvscf has a look at whether this is worth accounting for in base code, as its obvious in this example at least that ANY 'click-row' handler will have conflict if they click '.detail-icon' (see console and how order of log entries change).

**Comment by wenzhixin** [comment]
I will consider to add an option for example: `clickToExpand`, @jipexu you can use the solution what @dabros said.

**Comment by jipexu** [comment]
thanks both
huum i read carefully and try this  : https://jsfiddle.net/dabros/vo1npqdx/ 
but is not work ... i probably miss something but what ??

**Comment by dabros** [comment]
@jipexu - it works fine - update your fiddle (or create one as similar as possible to real use case) then integrate the fix so we can see what you missed or if anything else conflict.

other than that, ofcourse always keep console (F12) open at all times and see if any errors appear

Also do see i immediately added edit saying on my post with fiddle, noting that if you did want to click to load details you might need to tweak it further, but the click events themselves dont conflict anymore so row does expand (not certain if you need that click to load even, first time i seen it, but just make the loading code into reusable function then call from both '.detail-icon' and 'expand-row' if needed, as you can see in logs only one of them runs depending on where you click)

**Comment by djhvscf** [comment]
This issue is fixed.
