### ISSUE TITLE
Compatibility with sticky footer

### ISSUE THREAD

**Issue by GabrielGM** [wenzhixin/bootstrap-table#1407]
There is an issue when using bootstrap-table with bootstrap sticky footer when the table is longer than the screen height (if there is a scrollbar).

Any bootstrap-table can be used.

footer:

    <footer class="footer">
      <div class="container">My sticky © footer</div>
    </footer>

Ok at page load:
http://prntscr.com/8f4r7m
But doesn't stick at the bottom of the page when we scroll:
http://prntscr.com/8f4rpk

**Comment by wenzhixin** [comment]
Can you provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports) instead of images.
I guess you can define the css to solve this problem.

**Comment by GabrielGM** [comment]
With further investigation, it was indeed a problem with the css (that conflicted between the panel, the table and the footer).
Thanks for the reply! Sorry for the waste of time :S
