### ISSUE TITLE
insertRow() does not consider the Formatter of the column

### ISSUE THREAD

**Issue by facualle** [wenzhixin/bootstrap-table#1408]
for example:

```javascript
var firstColumn = {
      field: 'id',
};
var secondColumn = {
      field: 'name',
      formatter: function(value, row, index) {
           return  '<p class="name">'+value+'</p>'
      });
};

var newRow = {
      id: '15',
      name: 'Facundo'
}

table.bootstrapTable('insertRow',{index: 1, row: newRow});

```

When the table loads the new row, it does not put the formatted value in the cell.
I omitted the extra code, so you can understand it better.

Let me know if you don't understand me, and i will put the complete code.

Thanks.

**Comment by facualle** [comment]
I was doing something bad. Thanks.

**Comment by opan** [comment]
hello sir, how you to solve this?, i meet with this issue too

**Comment by facualle** [comment]
You must have something wrong. The method consider the Formatter well.
In my case there was a problem with the json that i sent as a parameter.

**Comment by opan** [comment]
can you share your how you call ```insertRow``` method sir?

**Comment by facualle** [comment]
```javascript
var newRow = {
      id: '15',
      name: 'Facundo'
}
$('#tableID').bootstrapTable('insertRow',{index: 0, row: newRow });
```
