### ISSUE TITLE
data-icons not working ?

### ISSUE THREAD

**Issue by emilmoe** [wenzhixin/bootstrap-table#1411]
I want to change the detailView open and close icons, but the data-icons attribute seems not to be working?

**Comment by djhvscf** [comment]
Can you provide a fiddle in order to see your issue? @emilmoe

**Comment by jipexu** [comment]
same problem for me ...

**Comment by djhvscf** [comment]
Ok, but we need an example with the issue

**Comment by jipexu** [comment]
ok i make one

**Comment by djhvscf** [comment]
Great!

**Comment by jipexu** [comment]
https://jsfiddle.net/jipexu/nj7omwtk/1/

but very unstable i can  not reproduce what i have on my laboratory ..

**Comment by jipexu** [comment]
but what i can say the data attribute work for the 3 first  but not for the two last

icons = {
    refresh: 'fa-refresh',
    toggle: 'fa-toggle-on fa-lg',
    columns: 'fa-th-list',
    detailOpen: 'fa-minus-square',
    detailClose: 'fa-plus-square'
};

**Comment by djhvscf** [comment]
Please use the latest version of our plugin (1.8.1)

**Comment by jipexu** [comment]
https://jsfiddle.net/jipexu/nj7omwtk/3/

**Comment by jipexu** [comment]
now in 1.8.1

**Comment by jipexu** [comment]
https://jsfiddle.net/jipexu/nj7omwtk/3/
so it's same the  data-icons attribute seems doesn't work ..

**Comment by wenzhixin** [comment]
Please use the `src` code, I will release a new version soon.
https://jsfiddle.net/wenyi/nj7omwtk/5/
