### ISSUE TITLE
Sorting by value other than visible td value?

### ISSUE THREAD

**Issue by sdrobs** [wenzhixin/bootstrap-table#1412]
I would like to sort a column that displays humanized times by the actual times that make them. So for example, the column will read "a few seconds", but the actual value to sort by will be 6, (in seconds). It would seem pretty straight forward to have a data-sort-value or something which I could choose to sort the column by. Is this currently possible/is there any workaround to doing this?

**Comment by djhvscf** [comment]
I think you can use the data-formatter función.. See this: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/issues/579.html and this: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/579.html

**Comment by sdrobs** [comment]
Worked great, thanks. I was a little bit confused by the links you attached, but the actual documentation on data-formatter here was pretty clear: http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#format-table

The first few links didn't show that value and row could be passed to the formatter, which was crucial to me.
