### ISSUE TITLE
你好，什么时候能添加以下对require的支持呢

### ISSUE THREAD

**Issue by mengyou658** [wenzhixin/bootstrap-table#1413]
只能页面显示的引入，不能用require("bootstrap-table");
谢谢

**Comment by wenzhixin** [comment]
bootstrap-table 只是普通的 jquery 插件，试下：
```js
requirejs.config( {
    shim: {
        'bootstrap-table': ['jquery']
    }
});
```

**Comment by wenzhixin** [comment]
这里有相关问题：http://stackoverflow.com/questions/10918063/how-to-make-a-jquery-plugin-loadable-with-requirejs

**Comment by mengyou658** [comment]
谢谢啊，我用的是webpack，这种方式可能不适用

**Comment by stevenjlho** [comment]
https://github.com/webpack/docs/wiki/shimming-modules 这里有说明如何加载

**Comment by mengyou658** [comment]
非常感谢!
