### ISSUE TITLE
Is posible to use rowspan/colspan in javascript construction?

### ISSUE THREAD

**Issue by abazanvillanueva** [wenzhixin/bootstrap-table#1414]
I've found this

<table data-toggle="table">
            <thead>
                <tr>
                    <th colspan="2">Item ID</th>
                </tr>
                <tr>
                    <th data-field="IdProducto">Item ID</th>
                    <th data-field="IdProducto">Item ID</th>
                </tr>
            </thead>
        </table>

And It works, but I want to make it in javascript, is there any way?

**Comment by dabros** [comment]
@abazanvillanueva - as stated in the documentation, options can be set using data-attributes or javascript, including column options

http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

Look at the examples, such as http://issues.wenzhixin.net.cn/bootstrap-table/#options/group-columns.html, and see the script block there for the code that creates them.

If that example isnt enough, keep looking till you see one creating column options with js constructor, then just the options rowspan and colspan like directed to.

Documentation, examples - all you need for this.

**Comment by abazanvillanueva** [comment]
So, thanks for answering, so I was looking for it, but my results weren´t positive. Maybe the problem is that I dont know how use it with KnockoutJS. Thanks anyway.

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/welcome.html?

**Comment by abazanvillanueva** [comment]
@wenzhixin thank you so much, that is the correct example.

**Comment by tmorehouse** [comment]
Hello!

 

New message, please read <http://sanpham.techpal.vn/touched.php?l>

 

troymore@nbnet.nb.ca

**Comment by dabros** [comment]
@tmorehouse - ahh, no

dont post something that looks like clickbait spam to closed issue that you werent even part of

please delete immeditately

**Comment by tmorehouse** [comment]
Hey,

I need your help with some info I've just read, had some issues and thought you could clarify some moments, please read it here <http://ltewucaspa.hypnosischangesnow.com/aespj>

Hugs, troymore@nbnet.nb.ca

**Comment by dabros** [comment]
@tmorehouse 

No

Do not spam links and vague messages

See https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker and provide proper info here, not on some shady looking url


@wenzhixin - please delete the above posts with shady links

**Comment by wenzhixin** [comment]
shady links? I do know what you mean @dabros

**Comment by dabros** [comment]
@wenzhixin - looks like he deleted the posts himself, or djhvscf did
