### ISSUE TITLE
Can I make ' number' columns dynamically? Knockout

### ISSUE THREAD

**Issue by abazanvillanueva** [wenzhixin/bootstrap-table#1415]

**Comment by wenzhixin** [comment]
Yes, I think you can.

**Comment by abazanvillanueva** [comment]
Is there any little example? thanks

**Comment by wenzhixin** [comment]
Sorry I am not familiar with Knockout, can your provide a jsFiddle to show your problem?

**Comment by dabros** [comment]
@abazanvillanueva - please provide an update on this issue

**Comment by wenzhixin** [comment]
have you solved your problem? If not reopen the issue.
