### ISSUE TITLE
bootstrap-table

### ISSUE THREAD

**Issue by prakashcse** [wenzhixin/bootstrap-table#1416]
Hi,

i have double table header problem when i m fetching data from server and
i need some text to display on table header (when mouse hover)

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports).

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
