### ISSUE TITLE
no version increments?

### ISSUE THREAD

**Issue by evanrich** [wenzhixin/bootstrap-table#1418]
the latest dist release shows 22 days ago, but the version # is still 1.8.1, which came from may.  Is it possible to keep the version #'s updated? we use them for tracking what libraries/dependencies are included with tools we're using this for.

Thanks!

**Comment by djhvscf** [comment]
Yes, I think we need to improve the version number management

**Comment by djhvscf** [comment]
There is a new "develop" branch
