### ISSUE TITLE
Proper way to update column options

### ISSUE THREAD

**Issue by kolupaevri** [wenzhixin/bootstrap-table#1419]
What is the proper way to update column options, for example `checkboxEnabled`?
The easiest way is to do the following: 

```javascript
var opt = $("table").bootstrapTable("getOptions");
opt["columns"][0][0]["checkboxEnabled"] = your_flag;
$("table").bootstrapTable("refreshOptions", {'columns' : opt["columns"]});
```

This way doesn't work, because of the `compareObjects` function in `BootstrapTable.prototype.refreshOptions`. 
Furthemore, It would be better to move some changing options in separate function which doesn't destroy and init the whole table, because I would like to change checkboxEnabled and right after that, do `checkBy` method (without waiting AJAX reponse of `initServer` function).
Or, should I modify them directly by changing the attribute?

**Comment by wenzhixin** [comment]
In now version, we can just only to support refreshOptions to update the `checkboxEnabled` option.

**Comment by djhvscf** [comment]
Solution provided. Close this issue
