### ISSUE TITLE
Generating data dynamicly

### ISSUE THREAD

**Issue by dkonopka** [wenzhixin/bootstrap-table#1420]
Hey,

Is there possibility to putting data not from for example data1.json, but from script generating rows like:

name= ["a", "b", "c"];

function generateJSON() {
    for (i = 0; i < names.length; i++) {
        $.getJSON("https://api.ipa.com" + name[i], function (json) {
            $('table').append("<tr><td>" +json.a+ "</td><td>" +json.b+ "</td><td>" + json.c+ "</td></tr>");
        });
    }
}

thanks for your answer

**Comment by wenzhixin** [comment]
You can use `append` method to solve your problem, here is an example: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/append.html.
