### ISSUE TITLE
Different behaviour of (un)checkAll \ By with enable option

### ISSUE THREAD

**Issue by kolupaevri** [wenzhixin/bootstrap-table#1421]
There is a `filter(':enabled')` in `BootstrapTable.prototype.checkAll_ = function (checked)`, but there is no such thing in `BootstrapTable.prototype.checkBy_ = function (checked, obj)`.
Is it correct? It is better to have the similar behavior or to update docs about this.

**Comment by wenzhixin** [comment]
Updated to the same.
