### ISSUE TITLE
checkbox event in a column

### ISSUE THREAD

**Issue by mad4hit** [wenzhixin/bootstrap-table#1422]
Hi, thanks for this plugin.
I'm trying to capture the onchange event of input tag with type checkbox for updating an underlying hidden field in the same td but the plugin caputre all fired events. 
Is it possible enable this kind of events? will be very usefull.

Thanks
Alex

**Comment by djhvscf** [comment]
Please review the documentation before open an issue. Here is the event that you have to bind: "check.bs.table". Here is the documentation: http://bootstrap-table.wenzhixin.net.cn/documentation/#events

**Comment by mad4hit** [comment]
Hi thanks for the reply, but the documentatio says: "Fires when user check a row, the parameters contain:
row: the record corresponding to the clicked row. "

i need to access to the dom element, and the event don't pass it.

Thanks for the help
Alex

**Comment by djhvscf** [comment]
Hmm ok, I think we need to implement this.. Let me try it

**Comment by mad4hit** [comment]
Thanks!

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/1435 @mad4hit
