### ISSUE TITLE
Ignoring search in specific column(s)

### ISSUE THREAD

**Issue by tvvignesh** [wenzhixin/bootstrap-table#1425]
Earlier in another issue, i referenced my fiddle: http://jsfiddle.net/tvvignesh/L3b5pp2a/4/

In that I use buttons and icons in the last column. So, I want to avoid search to list those fields when searched. eg. if I type "fa" in the search field, all rows are listed cause I use font awesome and have code as fa-clipboard for icons.

So,  is it possible to ignore respective columns while searching table? Does this feature exist or will it be implemented? Or if I have to do it, how do I?

**Comment by djhvscf** [comment]
Please review the documentation, here you can find the data-searchable column option. http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options, here an example http://jsfiddle.net/L3b5pp2a/6/

**Comment by tvvignesh** [comment]
@djhvscf : thanks a lot for your help. Got it.
