### ISSUE TITLE
rowIndex in onClickCell

### ISSUE THREAD

**Issue by maxelle** [wenzhixin/bootstrap-table#1426]
Is there a way to get the rowIndex inside onClickCell event handler?
I need it to call updateCell inside onClickCell  and it needs the rowIndex as parameter

**Comment by djhvscf** [comment]
As you can see this event provides these parameters: "field, value, row, $element", so in order to get the row index do it like this: $element.parent().data("index")

Documentation: http://bootstrap-table.wenzhixin.net.cn/documentation/#events
