### ISSUE TITLE
server端加载数据时togglePagination失效和export All失效问题及解决方法

### ISSUE THREAD

**Issue by mrbbljc** [wenzhixin/bootstrap-table#1427]
15年9月8日下载的版本，server端加载数据的时候，发现togglePagination按钮关闭pagination后任然只显示1页数据，导致export All也只导出1页的数据量，跟踪代码发现，在load方法中，并没有判断pagination是否启用而是直接判断sidePagination是server端还是client端，并对没有pagination的数据再包装导致数据出错，后台返回的没有pagination的数据就是一个数组，解决办法如下，加入是否启用pagination的判断
   BootstrapTable.prototype.load = function (data) {
        var fixedScroll = false;
   
        if(this.options.pagination){//         -----add
	        // #431: support pagination
	        if (this.options.sidePagination === 'server') {
	            this.options.totalRows = data.total;
	            fixedScroll = data.fixedScroll;
	            data = data.rows;
	        } else if (!$.isArray(data)) { // support fixedScroll
	            fixedScroll = data.fixedScroll;
	            data = data.data;
	        }
        }else{
        	fixedScroll = data.fixedScroll;
        }
请作者核实，已提交此问题，同时感谢作者，赞一个

**Comment by wenzhixin** [comment]
已经合并了 pull request，与问题 #1270 #1242 相同，你可以重新验证下。
