### ISSUE TITLE
Number of rows without pagination

### ISSUE THREAD

**Issue by mrv777** [wenzhixin/bootstrap-table#1430]
Wanted to start out by saying, great job with this!
I do have an issue/feature request that I believe should be easy to add:
**Include an option to display the number of rows in your table at the bottom**

This can currently be done if you enable pagination, but it would nice to have an option to just display the count without pagination.

Thank you again

**Comment by wenzhixin** [comment]
Merged

**Comment by mrv777** [comment]
Thanks.  I got it to work.  I did have to add data-page-size="100" to display all records, otherwise it only showed 10 items
