### ISSUE TITLE
could field be an an element of the columns?

### ISSUE THREAD

**Issue by joostshao** [wenzhixin/bootstrap-table#1431]
<th data-field="name.firname">Name</th>
        <th data-field="license.transer">License</th>
        <th data-field="description.last5Words">Description</th>
        <th data-field="url.proffex">Url</th>

just like this.

in  chinese:

数据字段能不能成为row里面一个 column里面的一个字段？

并不是简单的矩阵表格。

**Comment by wenzhixin** [comment]
可以的：http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/flat-json.html

**Comment by joostshao** [comment]
多谢
