### ISSUE TITLE
Use flatJSON display the content of an array in one column

### ISSUE THREAD

**Issue by naliofer** [wenzhixin/bootstrap-table#1432]
Hi,

Can I use the flatJSON plugin to display the content of an array in one column?
Example:

data.json

[{
        "id": 1,
        "name": "GroupA",
        "members": [{
                "id": 1,
                "name": "410041234567801",
                "callerid": "09278784217"
            },{
                "id": 1,
                "name": "410041234567802",
                "callerid": "09278784218"
            },{
                "id": 1,
                "name": "410041234567803",
                "callerid": "09278784219"
            }
         ]
}]

I wanted to display all members in one column
Group Column 	Members Column
GroupA 	                410041234567801, 410041234567802, 410041234567803,

Thanks!

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/177.html

**Comment by naliofer** [comment]
Doesn't work, My JSON return to me like this:
members.0.name = 410041234567801
members.1.name = 410041234567802
members.2.name = 410041234567803

on the example that you send to me, I just can get row.members

**Comment by djhvscf** [comment]
Can you create a fiddle ?

**Comment by naliofer** [comment]
https://jsfiddle.net/8svjf80g/237/

**Comment by djhvscf** [comment]
Ok, let me try it

**Comment by naliofer** [comment]
Nothing yet?

**Comment by wenzhixin** [comment]
Use the `formatter` option to solve your problem: https://jsfiddle.net/wenyi/8svjf80g/251/.

**Comment by naliofer** [comment]
Thanks, it's working
