### ISSUE TITLE
How to expand all the rows on page load

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1433]
Hi, 
I'm using the bootstrap subtable feature in my project, please tell me how to expand all the rows on page load. Once check the screenshot, as shown in screenshot all the subtables intially should be expand.
![capture](https://cloud.githubusercontent.com/assets/12938449/9959199/8338327a-5e2f-11e5-96a2-6fced98a5fc6.PNG)

i added below code but only one row is expanding as shown in below screenshot
setTimeout(function(){
   $('.detail-icon').click();
 }, 500);
![sdsad](https://cloud.githubusercontent.com/assets/12938449/9959319/9d3cdda0-5e30-11e5-97bc-6dcfa3a1d2ac.PNG)

http://jsfiddle.net/skfaruk/dq43uypw/8/

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/1435

**Comment by faruk77** [comment]
Thank you issue fixed
