### ISSUE TITLE
How to parse array structures inside a json format?

### ISSUE THREAD

**Issue by juandasgandaras** [wenzhixin/bootstrap-table#1434]
How could I parse the information inside an array in a json like this:

       {
                "dn": {
                  "ou": [
                     "roles"
                  ],
                  "cn": [
                     "helpdesk"
                  ],
                  "dc": [
                     "gompute",
                     "net"
                  ]
               },
               "oid": "oid:role:helpdesk",
               "name": "helpdesk",
               "updated_at": "2015-09-16T06:59:18.203141"
     }

I was thinking to parse in this way:

                                <thead>
                                	<tr>
                                		<th data-field="oid" rowspan="2" data-align="center" data-valign="middle" data-sortable="true" >Application short name</th>
                                        <th data-field="name" rowspan="2" data-align="center" data-valign="middle" data-sortable="true" data-sorter="assetSorter">Lic server ids</th>
                                        <th colspan="3" data-align="center">DN</th>
                                        <th data-field="updated_at" rowspan="2" data-valign="middle" data-sortable="true" data-align="center">Update date in ES</th>
            						</tr>
                                
                                    <tr>
                                    	<th data-field="dn.ou" data-sortable="true" data-align="center">OU</th>
                                    	<th data-field="dn.cn" data-sortable="true" data-align="center">CN</th>
                                    	<th data-field="dn.dc" data-sortable="true" data-align="center">DC</th>
                                    </tr>
                                </thead>

but the data  related to 

               "dn": {
                  "ou": [
                     "roles"
                  ],
                  "cn": [
                     "helpdesk"
                  ],
                  "dc": [
                     "gompute",
                     "net"
                  ]
               },

it is not well parsed with data-field="dn.ou"  any idea about this?

**Comment by wenzhixin** [comment]
You can use the flat json extension: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/flat-json.html or try to update the src.
