### ISSUE TITLE
detailView formatter can only receive HTML text

### ISSUE THREAD

**Issue by brauliobo** [wenzhixin/bootstrap-table#1439]
This makes things complicated. For example, you cannot work on the DOM because it is going to be **recreated** from the HTML text. Then binding events to the source DOM that generated the HTML are going to be lost!

This is also inneficient, as you may have a DOM element elsewhere and need to serialize/deserialize it to HTML.

This took me a lot of time on https://github.com/riot/riot/issues/1228

**Comment by brauliobo** [comment]
Actually I think this is a formatter limitation in general: they should be able to take DOM elements and append them where they should be shown.

**Comment by brauliobo** [comment]
a workaround is to append the element directly on `detail` parameter `onExpandRow`, and do not implement the detailView's formatter.

**Comment by wenzhixin** [comment]
So have you solved your problem @brauliobo?

**Comment by brauliobo** [comment]
@wenzhixin Yeah, closing this. But maybe the `fomatter`s logic should somehow be rethinked to accept more options rather than only HTML text.

**Comment by wenzhixin** [comment]
OK, thanks for your advice.
