### ISSUE TITLE
BS 4 alpha ... is there a new fork update for this ?

### ISSUE THREAD

**Issue by jipexu** [wenzhixin/bootstrap-table#1440]
Hi
I use BS4 alpha and can notice a lot of small prob due to the change in BS4 ..
for example change of class name btn-default ==> btn-secondary ... etc 

What are the project about this ?
I can list some issue to help.
Thanks

**Comment by wenzhixin** [comment]
Now our plugin does not support BS4.

**Comment by jipexu** [comment]
Do you think it will support ??  let's say it's almost support ... only some minor problems

**Comment by wenzhixin** [comment]
OK, in fact I haven't used BS4. I will have a try.

**Comment by jipexu** [comment]
coooool tell me if i can help for debug ... because i hardly tested BS4 and have some notice already.

**Comment by wenzhixin** [comment]
Any pull request is welcome :)

**Comment by jipexu** [comment]
Ok i will make a basic jsfiddle with BS4 for testing purpose to play with .. Unfortunately I am not very familiar with Github tool and such but I'm about to learn ...

**Comment by jipexu** [comment]
in bootstrap-table.js
@ first i have add the btn-secondary class before the btn-default class each time that btn-default was used (5 time) now my buttons are nice with BS 4 and 3

**Comment by jipexu** [comment]
now i have to check for the use of the col-*-* classes inside  <th>
for example : 
<th class="col-sm-4">...</th>
<th class="col-sm-4">...</th>
<th class="col-sm-4">...</th>
because in BS4 this classes utilization collapse the first row of the table ... (but at the moment i am not sure if it is a BS4 css mistake or if must fixed in bootstrap-table)

**Comment by jipexu** [comment]
so here is a fiddle with BS4 and bootstrap-table.js (very last + mod for the button class)
https://jsfiddle.net/jipexu/5Lbfntmw/

**Comment by djhvscf** [comment]
@jipexu when Bootstrap-table supports BS4 we will contact to you. Thank you.
