### ISSUE TITLE
using the json file ? 

### ISSUE THREAD

**Issue by rickyspires** [wenzhixin/bootstrap-table#1441]
Hello.
I have changed my json file but now I can not get the data. please help.

It was this.
     [
          {
                "id":"1"
          }
     ]

I changed it to this.

    {
        "pdf" : "path to pdf",
        rows = [
            {
            "id":"1"
            }
        ]
    } 

The json file path is in the html

    table data-url="../../Scripts/data/invoice.json"

Using bootstrap-table.js file.

I would like to get the rows in the table and be able to use the pdf for downloading the invoice

Thanks
Rik

**Comment by wenzhixin** [comment]
You can check out this example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/353.html.
