### ISSUE TITLE
Select input in table cell has value reset after sort action

### ISSUE THREAD

**Issue by notebleu** [wenzhixin/bootstrap-table#1442]
Hello,

We're using Bootstrap Table to enable column sorting.  When we include a select menu in the table and enable sorting there is an issue that I don't know the best way to resolve.  I've created a Fiddle to illustrate the issue:

https://jsfiddle.net/yv5cjahn/

Please follow these steps to duplicate:
1. Select "B" in the select menu in the first row
2. Click the "Group" column heading to cause the table to sort

The select that was updated to "B" a moment ago has been reset to "A".

I think this is because of a caching of the table data when Bootstrap Table is first initialized.  I couldn't find documentation on a method to "reset" the data that Bootstrap Table uses for the sorting each time the select input changes, and would love the communities thoughts on a good solution for this.

Thanks all.

**Comment by djhvscf** [comment]
Ok, let me try it

**Comment by djhvscf** [comment]
I think this is a feature.. What do you think @wenzhixin ?

**Comment by wenzhixin** [comment]
Hi @notebleu, @djhvscf, I don't think this is a feature.
When you change the value of select, you need to update the row data to the table.
Here is the jsFiddle: https://jsfiddle.net/yv5cjahn/2/.

**Comment by notebleu** [comment]
Perfect!  Thank you, that's just what I was looking for.
