### ISSUE TITLE
Can't  set initial query to a specific page

### ISSUE THREAD

**Issue by dberke711** [wenzhixin/bootstrap-table#1443]
I need a way to tell the table to initially display data starting at a specific page number given a page size.  Setting the pageNumber does not work until the table has been populated once, which shouldn't be necessary.

**Comment by djhvscf** [comment]
Can you provide an example, please? @dberke711

**Comment by dberke711** [comment]
Basically, I am trying to restore the state of the table (page size and current page number) when I navigate back to the table from another page.

// These two fields can be variable
var myPageSize = 15;   
var startPageNum = 4;

$("#myTable").bootstrapTable("refreshOptions", { pageSize: myPageSize });
$("#myTable").bootstrapTable("selectPage", startPageNum);
$("#myTable").bootstrapTable("refresh", { url: "http://myurl" });

Here is how my table is defined in markup:
        <div>
            <table id="myTable"
                   class="table bootstrap-table table-condensed"
                   data-striped="true"
                   data-search="false"
                   data-side-pagination="server"
                   data-pagination="true"
                   data-page-size="25"
                   data-pagination-v-align="both">
                <thead>
                    <tr>
                        <th data-field="FullName" data-sortable="true">Full Name</th>
                        <th data-field="CityStateZip" data-sortable="false">City State ZIP</th>
                        <th data-field="Email" data-sortable="true">Email</th>
                        <th data-field="Phone" data-sortable="true">Phone Number</th>
                    </tr>
                </thead>
            </table>
        </div>

**Comment by wenzhixin** [comment]
Have you solved your problem @dberke711?

**Comment by dberke711** [comment]
I discovered the bootstrap-table-cookie extension which provided (mostly) the functionality that I need, but I didn't directly solve the problem.

**Comment by wenzhixin** [comment]
OK, I think it is great if you can provide a jsFiddle, here is an example: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/selectPage-prevPage-nextPage.html.

**Comment by dberke711** [comment]
Looks like I still need this, the bootstrap-table-cookie extension is causing a lot of problems.

I don't think a jsFiddle will help here, the functionality I need doesn't exist.

I want to be able to do this:
~~~~~~
$("#myTable").bootstrapTable({
    pageSize: myPageSize,
    pageNumber: myPageNumber,
    url: "http://myurl"
});
~~~~~~

The pageSize and pageNumber values would then be used to set the initial offset and limit query parameters sent by the bootstrap-table to the server (I am using server-side pagination.)

**Comment by dabros** [comment]
@dberke711 - pls provide a fiddle so we can help you more.

A server-side jsfiddle base is provided here, though you could just use your code and replace columns and data-url if you wanted.

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by djhvscf** [comment]
Close this issue because the user did not respond
