### ISSUE TITLE
Click on 'No matching records found' produces error 

### ISSUE THREAD

**Issue by ravenjam** [wenzhixin/bootstrap-table#1446]
Not sure if this is duplicate. Basically click on 'No matching records found' (table with no records) gives me error in the console 'Uncaught TypeError: Cannot read property "fieldname" of undefined'. Any idea on this?

**Comment by ravenjam** [comment]
JSFiddle: http://jsfiddle.net/4n48y13d/1/
Click 'No matching records found' and see error in the console

**Comment by djhvscf** [comment]
@ravenjam the issue is already fixed but we have not released the latest version, in mean time you can use the master branch code

**Comment by ravenjam** [comment]
Thanks a lot, downloaded code from master branch and worked.
