### ISSUE TITLE
custom toolbar offset 

### ISSUE THREAD

**Issue by waspinator** [wenzhixin/bootstrap-table#1451]
When adding a custom toolbar it is offset from the regular one. They should probably be at the same height.

![custom-toolbar-offset](https://cloud.githubusercontent.com/assets/100416/10036893/f8b48d88-617b-11e5-9796-de6c3e92ad55.PNG)

**Comment by wenzhixin** [comment]
Can you provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports)?

**Comment by waspinator** [comment]
Sure. I just copied the Custom Toolbar example from http://bootstrap-table.wenzhixin.net.cn/examples/ and added data-toolbar-align="right"

http://jsfiddle.net/waspinator/tqbdp0nn/

**Comment by wenzhixin** [comment]
Solution: http://jsfiddle.net/wenyi/tqbdp0nn/1/
