### ISSUE TITLE
clickToSelects header wrong if detailView

### ISSUE THREAD

**Issue by gdoumenc** [wenzhixin/bootstrap-table#1452]
When detailView option is set, the headers array still contains only defined columns, then index for header options is wrong.

As example : 

 // click to select by column
   ...
   that.header.clickToSelects[$tr.children().index($(this))] is wrong if detailView defined

**Comment by wenzhixin** [comment]
Can you provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports)?

**Comment by gdoumenc** [comment]
http://jsfiddle.net/gdoumenc/y2oy38uo/10/

remove data-detail-view and the expected behavior is ok : no selection 
on first column click

Le 23/09/2015 16:47, 文翼 a écrit :
>
> Can you provide a jsFiddle 
> <https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wenzhixin/bootstrap-table/issues/1452#issuecomment-142625153>.
>

-- 
Guillaume DOUMENC
*FPR / CoWorks*
Your Internet Enabler
http://www.fpr-coworks.com

**Comment by wenzhixin** [comment]
OK, In this case you need to remove data-detail-view option.

**Comment by wenzhixin** [comment]
Or: http://jsfiddle.net/wenyi/y2oy38uo/11/

**Comment by wenzhixin** [comment]
Sorry, I misunderstand your issue.

**Comment by gdoumenc** [comment]
No problem, it's always difficult to explain an issue (never enough 
time)  and from you to be sure the guy has understand his own issue and 
know the product ;)

Nevertheless continue your work, good job..

Le 24/09/2015 08:09, 文翼 a écrit :
>
> Sorry, I misunderstand your issue.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wenzhixin/bootstrap-table/issues/1452#issuecomment-142820019>.
>

-- 
Guillaume DOUMENC
*FPR / CoWorks*
Your Internet Enabler
http://www.fpr-coworks.com

**Comment by gdoumenc** [comment]
Means you won't fix the issue????

Le 24/09/2015 11:04, 文翼 a écrit :
>
> Closed #1452 
> <https://github.com/wenzhixin/bootstrap-table/issues/1452> via 618128a 
> <https://github.com/wenzhixin/bootstrap-table/commit/618128ace18bdb997d92ddc9b45c98ba43078af6>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wenzhixin/bootstrap-table/issues/1452#event-417878499>.
>

-- 
Guillaume DOUMENC
*FPR / CoWorks*
Your Internet Enabler
http://www.fpr-coworks.com

**Comment by wenzhixin** [comment]
I have fixed this issue: http://jsfiddle.net/wenyi/y2oy38uo/13/

**Comment by gdoumenc** [comment]
Sorry apologize..

Le 24/09/2015 11:13, 文翼 a écrit :
>
> I have fixed this issue: http://jsfiddle.net/wenyi/y2oy38uo/13/
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wenzhixin/bootstrap-table/issues/1452#issuecomment-142864191>.
>

-- 
Guillaume DOUMENC
*FPR / CoWorks*
Your Internet Enabler
http://www.fpr-coworks.com
