### ISSUE TITLE
filterControl strict filter on numeric values

### ISSUE THREAD

**Issue by liKe2k1** [wenzhixin/bootstrap-table#1453]
If you filter on numeric values it ignores the strict mode:

https://jsfiddle.net/jf2js1rd/3/

Try to filter ID 2.
It will show 2 & 32.
Expected only 2.

Try to filter ID 1
It will show 1 & 15.
Expected only 1.

**Comment by djhvscf** [comment]
But you did not set the strict mode.. I mean I can't see it in your table configuration

**Comment by liKe2k1** [comment]
Updated jsFiddle

https://jsfiddle.net/jf2js1rd/3/

**Comment by djhvscf** [comment]
See this PR: https://github.com/wenzhixin/bootstrap-table/pull/1459

And then the filterStrictSearch is a column option, it is not a extension option. See this example please: https://jsfiddle.net/jf2js1rd/10/

**Comment by liKe2k1** [comment]
Thanks for the fast reply.
