### ISSUE TITLE
Loading Data --- The Noobie Help

### ISSUE THREAD

**Issue by jpook101** [wenzhixin/bootstrap-table#1455]
So I’m going to be that guy. I’m trying to create a web interface for a report. (I’m not a coder; I’m an Exchange/Server admin) I’m following the examples and been reading the documents, but I just don’t understand what I’m doing wrong.  I can get all the option to work, just no data is found. I did the F12 thing in Chrome and i don't see the json file being loaded. 

Put the code up for review:  http://jsfiddle.net/j66aLsg4/

•	using Visual Studio 2013
•	jquery-2.1.4.js
•	Bootstrap v3.3.5

![2015-09-23_13-28-08](https://cloud.githubusercontent.com/assets/14334632/10054741/4a555074-61f8-11e5-8a34-6bf08cd8c8d4.png)

**Comment by djhvscf** [comment]
Everything is ok but make sure that the url path is correct.. I mean use f12 and see in the network tab if the document JsonEx2.json is being loaded. See this: http://jsfiddle.net/j66aLsg4/2/

**Comment by jpook101** [comment]
So i see i'm getting an " internal server 500 error" on the json file. Not 100% sure what that is... going to start to google.

**Comment by wenzhixin** [comment]
You json request is error, need some response like this: http://issues.wenzhixin.net.cn/bootstrap-table/json/data1.json

**Comment by jpook101** [comment]
I'm testing with that File... it still doesn't work.

**Comment by wenzhixin** [comment]
You can debug your code.

**Comment by jpook101** [comment]
Nice replay.. Thanks for the help. (i guess)

**Comment by wenzhixin** [comment]
I mean open the console tab, and see is there some error?

**Comment by jpook101** [comment]
=) .. sorry about that.. need more caffeine.  Yes i'm getting the same 500 error.
