### ISSUE TITLE
How does the 'removeByUniqueId' work?

### ISSUE THREAD

**Issue by ravenjam** [wenzhixin/bootstrap-table#1456]
I'm wondering how does the 'removeByUniqueId' method work? 

I created a js fiddle and just can't make it work as expected: http://jsfiddle.net/4n48y13d/6/

Shouldn't the row with the specific id get removed?

**Comment by wenzhixin** [comment]
Need to set `uniqueId` option: http://jsfiddle.net/wenyi/4n48y13d/7/
example: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/removeByUniqueId.html

**Comment by ravenjam** [comment]
Awesome, thanks a lot!
