### ISSUE TITLE
Multiple filters

### ISSUE THREAD

**Issue by oeilgauche** [wenzhixin/bootstrap-table#1457]
Hi,

Great plugin! I wondered if it was possible to add custom filters. In my case i'd like to filter a column with a date range. What do you think?

Thanks!

**Comment by djhvscf** [comment]
You can use something like this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html but if you want a filter per column you can use this: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html

**Comment by oeilgauche** [comment]
I'll try that, thanks!
