### ISSUE TITLE
Sorting after reordern columns in firefox

### ISSUE THREAD

**Issue by FerGabPereira** [wenzhixin/bootstrap-table#1458]
sorry for my english

in firefox with reorder columns plugin and sorting feature is active. click event is trigger.
Chrome/Opera is Ok.

fiddler:
https://jsfiddle.net/sa2jxhf8/1/

**Comment by djhvscf** [comment]
this is an issue of jquery.dragtable. Please open the issue on this site https://github.com/akottr/dragtable/issues
