### ISSUE TITLE
滚动加载以及语言文字部分

### ISSUE THREAD

**Issue by luocongjay** [wenzhixin/bootstrap-table#1462]
1）预期效果是滚动到底部再追加第二页内容到表格里面。因为是新生成的dom，无法直接绑定事件，如果初始化完成之后有对应的回调函数就好了。
2）语言如果能动态设置，比如搜索默认是search，我想根据不同的业务设置不一样的文字，目前好像还不清楚怎么实现。 谢谢！

**Comment by wenzhixin** [comment]
第一个问题你可以用 prepend 来添加到前面去。
第二个问题现在已经支持了：
#1791 updateFormatText method: http://jsfiddle.net/e3nk137y/3876/
