### ISSUE TITLE
如何自定义表格布局呢？

### ISSUE THREAD

**Issue by crperlin** [wenzhixin/bootstrap-table#1463]
比如搜索框周边的文字样式。。

选择显示的下拉框移动到头部而不是在底部。。。

分页按钮居中！！

**Comment by sunhk25** [comment]
这种个性化设置没必要吧，如果是在想该，那就在自己的插件里改

**Comment by wenzhixin** [comment]
自己改下 css 样式，可以覆盖默认的。
