### ISSUE TITLE
extension cookie prevent to init sort and don't save sortOrder

### ISSUE THREAD

**Issue by FerGabPereira** [wenzhixin/bootstrap-table#1465]
only cookie extension enabled don't save the sorting.

JSFiddler:
https://jsfiddle.net/nu6h662t/2/

initSort don't work with cookie plugin enabled
JSFiddler:
https://jsfiddle.net/4g5f915u/1/

Fernando.

**Comment by djhvscf** [comment]
This issue is already fixed in the latest version.. @FerGabPereira if not, please reopen this issue
