### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prop' of undefined

### ISSUE THREAD

**Issue by amazingSurge** [wenzhixin/bootstrap-table#1468]
The issue is the same with https://github.com/wenzhixin/bootstrap-table/issues/1214

this.$selectAll.prop is undefined

this.$selectAll.prop('checked', this.$selectItem.length > 0 &&

==============================

Update bootstrap-table-mobile.js file from

line 23

    var resetView = function (that) {
        if (that.options.height || that.options.showFooter) {
            setTimeout(that.resetView, 1);
        }
    };

to

    var resetView = function (that) {
        if (that.options.height || that.options.showFooter) {
            setTimeout(function(){
              that.resetView.call(that);
            }, 1);
        }
    };

It resolve the issue. Please update.

**Comment by djhvscf** [comment]
Please open a new PR with your change, @amazingSurge

**Comment by wenzhixin** [comment]
Merged
