### ISSUE TITLE
remote modal shows same content in bootstrap-table

### ISSUE THREAD

**Issue by sunhk25** [wenzhixin/bootstrap-table#1471]
I need to open a  remote modal. my problem is after closing the modal, on next open it shows the same content.
i had try some solutions, but still not resolved.
how can i clear the modal between load/show's?
the examples of problems is here: http://jsfiddle.net/NUCgp/2879/

**Comment by dabros** [comment]
Not a bootstrap table issue at all in its current form, though do see my notes in my fiddle about how you should be integrating this with bootstrap table code.

http://jsfiddle.net/dabros/nrxs2pmL/

For future referance, so so so so so many easily found stackoverflow and other topics out there about exactly this, and dozens of easy tutorials that can show you how to much better setup your handler logic for using them.

**Comment by sunhk25** [comment]
you are awesome,  thanks for your help!
Solved it!
