### ISSUE TITLE
bootstrap-table-filter-control 插件在按键是存在bug

### ISSUE THREAD

**Issue by linziguan** [wenzhixin/bootstrap-table#1472]
bootstrap-table-filter-control 插件在按键是存在bug
当按键是ctrl、alt或shift时，该插件会自动刷新表格，同时使得失去焦点。当在filter的输入框中切换输入法时，体验很不好。

**Comment by linziguan** [comment]
修改方法:
```
header.off('keyup', 'input').on('keyup', 'input', function (event) {
            	var keyCode=event.keyCode;
            	if(keyCode==9||keyCode==16||keyCode==17||keyCode==18){
            		return null;
            	}
                clearTimeout(timeoutId);
                timeoutId = setTimeout(function () {
                    that.onColumnSearch(event);
                }, that.options.searchTimeOut);
            });
```

**Comment by djhvscf** [comment]
Can you translate it to english?

**Comment by archerchiu** [comment]
Hi,
I think @linziguan means that will lost focus on the filter field, user just switch input method and do nothing.

**Comment by rodrigodefigueiredo** [comment]
I'm having trouble after the last update of the filter-control.
After updating bootstrap-table with filter-control does not work any more
rollback version and it worked
Examples on the site do not include this update
https://github.com/wenzhixin/bootstrap-table/commit/40459abc4fd5cb791429fdb4cb28d2a8d8d19886

**Comment by wenzhixin** [comment]
@djhvscf , can you help to check this problem what @rodrigodefigueiredo said.

**Comment by djhvscf** [comment]
@rodrigodefigueiredo can you tell us what is the issue related to filter-control?

**Comment by djhvscf** [comment]
Any update here, @rodrigodefigueiredo ?

**Comment by rodrigodefigueiredo** [comment]
Hi , 
it's been a long time and I was with the working version.
I plan to upgrade soon providing feedback again.

One suggestion is that the examples of the site always use the latest packages distributed and published on github, why the example does not always reflect the version of the library, it is difficult to implement a new component based on the "wrong" documentation.
Thank you for your attention and please , continue to evolve the bootstrap-table, it is fantastic. :-)

**Comment by wenzhixin** [comment]
@linziguan the latest version haven't this problem

**Comment by linziguan** [comment]
最新版本已经没有这个问题了，谢谢。
