### ISSUE TITLE
Table mobile extension doesn't work if column minWidth is set

### ISSUE THREAD

**Issue by AndrejGajdos** [wenzhixin/bootstrap-table#1473]
I use [table resizable](http://bootstrap-table.wenzhixin.net.cn/extensions/#table-resizable) and [table mobile](http://bootstrap-table.wenzhixin.net.cn/extensions/#table-mobile) extensions. If I set minimum width of columns by `minWidth` attribute, table mobile extension doesn't work (table isn't in card view mode).

[jsfiddle](https://jsfiddle.net/88useqm1/12/)

**Comment by djhvscf** [comment]
This issue is because both extension has the same option name.. Let me think how can we fix this without any problem

**Comment by djhvscf** [comment]
Fixed. See this: https://jsfiddle.net/djhvscf/88useqm1/26/
