### ISSUE TITLE
Export table to pdf with utf-8 characters

### ISSUE THREAD

**Issue by yaylitzis** [wenzhixin/bootstrap-table#1481]
I tried to export my table which contains utf-8 characters and these characters are not printed normally.. Is sth I can do to fix this?

p.s.
You have done Great job..

**Comment by wenzhixin** [comment]
Try this: https://github.com/wenzhixin/bootstrap-table/issues/189

**Comment by toniojst** [comment]
jsPDF allow to use custom font. So what is change that we can import base64 font?
