### ISSUE TITLE
Unable export data correctly first time with pagination: true and exportDataType: "all", and the data is not at server side

### ISSUE THREAD

**Issue by RJHsiao** [wenzhixin/bootstrap-table#1482]
如題，
在設定 `pagination: true` 以及 `exportDataType: "all"` 的情況下，
第一次匯出檔案時沒有任何作用。
已經確定問題出在 `that.togglePagination();` 敘述的擺放位置有誤，
應該在宣告事件綁定方法後再手動觸發事件。

另外由於少註冊一個事件，
導致就算上面所描述的問題沒有發生，在表格資料內嵌在網頁內的情況下也不會正常運作。

我已經修正此問題了，等下補上 pull request。

**Comment by wenzhixin** [comment]
Merged
