### ISSUE TITLE
Help Needed: Generate all the columns dynamically along with grid settings based on JSon!

### ISSUE THREAD

**Issue by coderabsolute** [wenzhixin/bootstrap-table#1484]
The grid settings and column definitions are configured in SQL (two tables). I can retrieve them and it should be applied to bootstrap-table during run time. I have been searching all over the place for a documentation since many days and not able to find one, I have also seen refreshOptions example but not sure how this works for 'Dynamic Column Generation' https://github.com/wenzhixin/bootstrap-table-examples/blob/master/methods/refreshOptions.html

Am not sure how to solve my problem. Wondering, has anyone done similar work? I would really appreciate, if I get some guidance?

Note: If my question is too brief, please let me know I would be able to elaborate with some examples.

Thanks in advance!
Yam

**Comment by djhvscf** [comment]
Provide some example please, it will be great!

**Comment by coderabsolute** [comment]
Am going to use this grid control on ASP.NET MVC 5 application. Idea is that SQL tables should hold the grid and column configuration. Grid component should render based on the information provided by the controller. Let me share a bit of SQL table structure.

//This table holds the grid configuration
CREATE TABLE [dbo].[Grid](
	[GridId] [smallint] NOT NULL IDENTITY(1,1),
	[GridName] [varchar](255) NOT NULL,
	[Description] [varchar](255) NULL,
	[Title] [varchar](255) NULL,
	[SQLQuery] [varchar](max) NOT NULL,        //Grid rows should generate based on this query :)
	[CanPrint] [bit] NOT NULL,
	[CanExport] [bit] NOT NULL,
	[CanEdit] [bit] NOT NULL,
	[CanDelete] [bit] NOT NULL,
	[IsHelpImplemented] [bit] NOT NULL,
	[HelpText] [varchar](max) NOT NULL,
	[LastModifiedAppUserId] [int] NOT NULL,
	[CreatedDate] [datetimeoffset](7) NOT NULL,
	[LastModifiedDate] [datetimeoffset](7) NOT NULL,
	[IsActive] [bit] NOT NULL
)

//This table holds the column configuration
CREATE TABLE [dbo].[GridOutputColumn](
	[GridOutputColumnId] [int] IDENTITY(1,1) NOT NULL,
	[GridId] [smallint] NOT NULL,
	[ColumnName] [varchar](255) NOT NULL,
	[DataTypeId] [tinyint] NOT NULL,
	[IsKeyId] [bit] NOT NULL,
	[IsSortable] [bit] NOT NULL,
	[Width] [varchar](64) NULL,
	[HeaderText] [varchar](255) NULL,
	[Tooltip] [varchar](255) NULL,
	[ColumnSequence] [tinyint] NOT NULL,
	[IsColumnHidden] [bit] NOT NULL,
	[ConditionalFormat] [varchar](255) NULL,
	[LastModifiedAppUserId] [int] NOT NULL,
	[CreatedDate] [datetimeoffset](7) NOT NULL,
	[LastModifiedDate] [datetimeoffset](7) NOT NULL
)

Am cracking my head to render the grid dynamically which should include the basic grid, column and row settings. Am I making sense? Or maybe asking too much?

**Comment by wenzhixin** [comment]
Use `refreshOptions` to update the table, can it work?

**Comment by coderabsolute** [comment]
I need to dynamically generate and set properties of the grid as well as columns. Am not sure whether refreshOptions would solve the problem?

**Comment by wenzhixin** [comment]
You can have a try.

**Comment by coderabsolute** [comment]
I will definitely give a try, I think this would be a very good functionality if I can come up with a solution. We can also translate grid columns (not for multi-lingual but other translations in the application).

**Comment by wenzhixin** [comment]
Close the issue.
