### ISSUE TITLE
If data in a cell in empty, it will show up as "-" (default character for undefined data).But if we try to filter the columns containing empty data it searches for string "-" instead of looking for empty data. How do I search or filter columns with empty/undefined data.

### ISSUE THREAD

**Issue by vtikam** [wenzhixin/bootstrap-table#1487]
![capturebootstrapdatatable](https://cloud.githubusercontent.com/assets/14929827/10230154/5bd3e1e2-6899-11e5-9199-a5be1cab2160.JPG)
I want to filter empty data in Business Justification column.
Can you let me know if it is possible or can we add this feature for next releases?

**Comment by dabros** [comment]
@vtikam - fiddle please, so we can play with this and see - i have a few ideas that already supported maybe but cant see exact example

**Comment by vtikam** [comment]
I want to filter on columns that are either empty or undefined like 1st row description or 3rd row stars.
Here is the fiddle
https://jsfiddle.net/vtikam/31f83t4s/

**Comment by wenzhixin** [comment]
You can set the `undefinedText` option to ''.

**Comment by vtikam** [comment]
I will try it out. But what do we use in filter text. Can we have a "Empty Text" option in search text box as well as in the select drop down filter. Basically if we choose the Empty text option it will filter the column where text is empty and show only those rows.

**Comment by dabros** [comment]
@vtikam - can you please update fiddle to use filter-control or whatever advanced plugin for searching, ideally exposing callbacks.

There seem to be 2 filter plugins i can see, i having used advanced search since either of them posted/updated so i actually made my own using (mostly) callbacks way back

**Comment by dabros** [comment]
@vtikam - any update on this?
