### ISSUE TITLE
Fail to load data about version 1.9.0

### ISSUE THREAD

**Issue by archerchiu** [wenzhixin/bootstrap-table#1489]
Hi,
Upgrade to version 1.9.0, seems can not to compatible with version 1.8.1. Buttons like column through events to do something, ex. remove row feature, is going to load failed. Because nothing to append the field value, and version 1.9.0 has no auto append it. Is this new rule in the future?
![image](https://cloud.githubusercontent.com/assets/2604264/10238114/4a45ddc8-68ed-11e5-84bd-0255f3e3567e.png)
Thanks.

**Comment by wenzhixin** [comment]
Can you provide a jsfiddle?

**Comment by iboylmz** [comment]
This error caused by line 222 in bootstrap-table.js.

        for (var p in props) {
            value = value[props[p]];
        }

I solved this with:

           if (value) {
                value = value[props[p]];
            }

I'm not sure it's the right solution. But for now it does the job.

**Comment by wenzhixin** [comment]
Please provide a jsfiddle to show the bug, thanks.

**Comment by iboylmz** [comment]
I can't catch scenarios but problem is about for loop. 

You can try this fiddle:

http://jsfiddle.net/iboylmz/5tm7aakc/

**Comment by archerchiu** [comment]
@iboylmz Good idea. Thanks.

But, I have an extending problem. If the field string includes '.' symbol, table is going to crash.
```
var props = field.split('.');
```
If it's not object operation, the real field key that dynamic composed could not work anymore?

**Comment by wenzhixin** [comment]
Fixed this problem.
