### ISSUE TITLE
(un)check.bs.table: element argument missing on table init

### ISSUE THREAD

**Issue by marank** [wenzhixin/bootstrap-table#1491]
Check this JSFiddle: https://jsfiddle.net/wenyi/e3nk137y/11/ (look at console output)

check.bs.table gets triggered without the corresponding element argument on table init. It is working fine if the user selects/deselects a row.

**Comment by wenzhixin** [comment]
Is your jsFiddle error? But I think it is a bug.

**Comment by marank** [comment]
I'm sorry, just noticed that all javascript is gone in my jsFiddle. But thank you for fixing it!
