### ISSUE TITLE
footer formatter don't work properly

### ISSUE THREAD

**Issue by FerGabPereira** [wenzhixin/bootstrap-table#1493]
data-footer-formatter parse function like a literal:

https://jsfiddle.net/o1711k9p/2/

but if you pass a decimal number...... crash:

https://jsfiddle.net/shoxmv38/2/

ideas?

**Comment by wenzhixin** [comment]
I think you used in a wrong way, the type of `footerFormatter` is function.
Docs: http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options
Example: http://issues.wenzhixin.net.cn/bootstrap-table/index.html
