### ISSUE TITLE
inconsistency, rows or records

### ISSUE THREAD

**Issue by timoline** [wenzhixin/bootstrap-table#1496]
Hello,
maybe it's me but there is some inconsistency.
Is it rows or records?

Showing 1 to 10 of 800 rows 10  records per page

**Comment by wenzhixin** [comment]
rows or records? Which one do you think is more appropriate?

**Comment by timoline** [comment]
hmmm, rows ?

**Comment by dabros** [comment]
yes, rows seems more appropriate

related: http://dba.stackexchange.com/questions/31805/what-is-the-difference-between-a-record-and-a-row-in-sql-server

**Comment by dabros** [comment]
@wenzhixin - if looks good to you, maybe close this issue?

Prob best to scan to make sure i didnt miss any that use both 'rows' and 'records' in same file.

**Comment by timoline** [comment]
In line 436 of bootstrap-table.js, there is still records per page and I see more "records" in this file where it should be "rows"

**Comment by djhvscf** [comment]
@timoline I will open this issue but can you open a new PR with the changes that we should apply ?
