### ISSUE TITLE
Problem whit null value in JSON 

### ISSUE THREAD

**Issue by javieralfaya** [wenzhixin/bootstrap-table#1497]
When i get a field with null value from JSON , the table no show values:

var getItemField = function (item, field) {
        var value = item;

        if (typeof field !== 'string' || item.hasOwnProperty(field)) {
            return item[field];
        }
        var props = field.split('.');
        for (var p in props) {
            value = value[props[p]];    	
        }
        return value;
    };

Can be resolved:
 for (var p in props) {
            value= '';
            value = value[props[p]];    	
        }

**Comment by erick-chali** [comment]
When I have undefined text o null values in my responses I use the table option:
undefinedText : ' ', you can set that value as default.

**Comment by djhvscf** [comment]
@javieralfaya can you provide a fiddle? Thanks

**Comment by wenzhixin** [comment]
This issue is fixed in the latest version!
