### ISSUE TITLE
Prevent re-initialization on search, sort, cell updates, ...

### ISSUE THREAD

**Issue by marank** [wenzhixin/bootstrap-table#1498]
Consider the following jsFiddle: https://jsfiddle.net/4pthhsp9/3/ (I hope it works this time :))

As you can see, I want to activate the input fields based on the selected rows. Moreover, I want to store the input fields' value in a seperate, hidden column. And on top of that, I'd like to use [jquery.maskedinput](https://github.com/digitalBush/jquery.maskedinput) on the input fields.

Sorting, searching and calling 'updateCell' causes the table to re-init itself, resulting in the input fields getting reset.

Is there any way to prevent the table from re-init itself anytime, but instead (for example) manage the rows as jquery objects?

**Comment by sketchman-nyt** [comment]
:+1: I'm having this same problem with updating my table, it gets completely reinitialized with initBody() being called. This closes any open detail views I have open. It would be nice to have a way to say update in place rather than reinitializing the entire table.

**Comment by coffy** [comment]
+1 for not re-rendering of table after "updateCell" call

**Comment by coffy** [comment]
Hi, @marank and @sketchman-nyt , you can try new enhancement #1883 in development branch just addd <code>{reinit: false}</code> when calling updateCell method. Remember you have to update table cell HTML manually, it won't be redrawn from underlying data.

**Comment by wenzhixin** [comment]
Merged in develop, thanks for @coffy

**Comment by jcavandoli** [comment]
I got the same problem with the `append` method.
If you append a new row, the initBody() will redraw the whole table and reset the custom html in each cells.

**Comment by Ericzhiluo** [comment]
the auto-initialization in 'remove' 'update' 'append'  is very annoying as it resets HTML changes you made. Reinitialize the whole table when only one row is updated is unnecessary.

**Comment by djhvscf** [comment]
We're working in an improvement where we will update just the row(s) updated. This will increase the performance

**Comment by arpitjain1616** [comment]
Is there any update on this?

I am not able to make **reinit: false** work with an Input box in the table and updating the cell value with 'updateCellByUniqueId' method. Waiting for the response. @wenzhixin @aureliendavid @djhvscf @dabros @matusferko
