### ISSUE TITLE
Item select from multiple pages

### ISSUE THREAD

**Issue by tejas-shannu** [wenzhixin/bootstrap-table#15]
Dear wenzhixin,

How to select multiple items from different pages. For every page checkbox gets refreshed and I could only see selected items from that page. If I want to select multiple items from different pages how to do it.

**Comment by BhavinVisariya** [comment]
Dear wenzhixin,,

Is this issue fixed?
Can we select multiple items from different pages using server side pagination?

**Comment by wenzhixin** [comment]
client: maintainSelected
server: 
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/917.html
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/1167.html
