### ISSUE TITLE
Example for use extension

### ISSUE THREAD

**Issue by SystemF** [wenzhixin/bootstrap-table#1500]
Noob question. I am trying to use the reorder row extension, but I cannot figure out how I should write the right syntax for the event onReorderRow. Honestly I don't know how to use it so I can save the new order. Can anybody give me a snippet how to instantiate reorder row with the onReorderRow method. Thanks!

**Comment by djhvscf** [comment]
Did you check this: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-rows.html, @SystemF ?

**Comment by SystemF** [comment]
Yes, I did and for so far I had no problems.

The only thing that I can't find out is how to implement the onReorderRows
method. I can't find that in the example page either.

Can you please explain me how and where to call this method?

Thanks!
Op 4 okt. 2015 12:59 AM schreef "Dennis Hernández" <notifications@github.com

**Comment by SystemF** [comment]
I figured out, the drop event only been fired when an id attribute is on the TR.

And, the default initialization in the bootstrap-table.js  is leading. So I have to remove the default and initialize with the options provided in a custom js.

Is there a way to overrule the default initialization because most of the time that's fine?

Hope you understand!

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by SystemF** [comment]
Yes, I‘ve made a workaround but it's not the most elegant way...

But thanks!
