### ISSUE TITLE
Multiple Sort , how to use Locale functions

### ISSUE THREAD

**Issue by LightCrystal** [wenzhixin/bootstrap-table#1503]
Hello everyone,
thanks for this amazing project. I'm spending a lot of time going through examples and documentation but cannot find the answer.
I`m trying to set the Locales for the Multiple Sort extension via JavaScript, but apart for the method to use there are no real examples.

After i set up the table like this:

 $('#table').bootstrapTable({
            showMultiSort:true
        });

What code i need to set a custom value for the multisort extensions?
I see formatMultipleSort and the other functions but I would appreciate some code on how to use set it, and i suggest to update the documentation too.

Thanks!

**Comment by wenzhixin** [comment]
$('#table').bootstrapTable({
            showMultiSort:true,
            formatMultipleSort: function () {
                return 'Locale here';
            }
        });
