### ISSUE TITLE
How To get selected row and its data at server side (c#,aspnet)

### ISSUE THREAD

**Issue by cetindogu** [wenzhixin/bootstrap-table#1506]
i need to get table data(selected row) on postback. (in asp:button onclick event)

**Comment by djhvscf** [comment]
Did you see this: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getSelections.html ?

**Comment by cetindogu** [comment]
yes, it is to get data at CLIENT side. i already can get at client side. thanks

**Comment by djhvscf** [comment]
Sorry about that.. The example that I put dos not work for you?
