### ISSUE TITLE
sort能不能独立一个参数控制是服务端还是客户端排序？

### ISSUE THREAD

**Issue by linjiaju8** [wenzhixin/bootstrap-table#1507]
我们现在就有需求分页使用服务端分页但排序使用客户端排序，貌似现在分页和排序方式都是由sidePagination: 'server'控制的，无法实现这个需求？

**Comment by wenzhixin** [comment]
使用服务端分页但排序使用客户端排序这个需求并不合理吧？例如有 1-100 的记录，第一页显示 1-10，倒序是 10-1，这样是不对的，所以暂时不考虑这个需求。

**Comment by wenzhixin** [comment]
关闭这个问题
