### ISSUE TITLE
INPUT element values aren't perserved when switching between table and card view

### ISSUE THREAD

**Issue by john3parker** [wenzhixin/bootstrap-table#1508]
I have a table with INPUT types checkbox and text. If I change a value in a text field or change the checkbox value then switch to card view, the value isn't perserved and I'm left with the former value. Vice-versa is true as well if I change an INPUT element value in card view and swtich to table view the data values aren't perserved from card view.

I would expect normal behavior to be data is perserved between all views of the table with a need to refresh the screen from the server. I have not looked at the code yet. Any quick feedback before I dive in?

**Comment by djhvscf** [comment]
Can you provide a fiddle? It will save our time

**Comment by john3parker** [comment]
Here's a fiddle demonstrating the issue. 
http://jsfiddle.net/john3parker/c0o4semf/1/

**Comment by djhvscf** [comment]
You have to do something like this: https://jsfiddle.net/yv5cjahn/2/

**Comment by wenzhixin** [comment]
ref #1442

**Comment by john3parker** [comment]
I reviewed your basic example and was able to work up another solution that synced INPUT data between BootstrapTable and DOM. However, the solution was specific to TABLE view and broke down when the view is changed to CARD. Your solution works in both but doesn't work in my scenario. I appreicate your response on this but I think I'm going to run in a different direction on this for now. 

Thanks!

**Comment by wenzhixin** [comment]
Here is the solution: http://jsfiddle.net/c0o4semf/3/
