### ISSUE TITLE
extension table-filter-control

### ISSUE THREAD

**Issue by dfmaxwell** [wenzhixin/bootstrap-table#1511]
I've noticed that when I set the filterData option to a url: "url_filenamehere.php" that two calls get made to my server for each time I load the page for each filter, and likely based on how I'm reading this the same would happen if it was a "var"

I have found that if I comment out line 278:
createControls(that, that.$tableHeader);
that I only see one call made to my server and it doesn't seem to change how things function.

This is an observation I've made as I'm trying to do some troubleshooting.  So, I was wondering if there is a way that this can hit the server just one time instead of two.  I've removed my comment because my issue isn't related to this from what I can tell, but I wanted to rule it out.

Thanks,

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle to show the problem?

**Comment by dfmaxwell** [comment]
I can't easily provide one as the stuff I've built is based off of internal data.  Here is what I discovered.  I had a height set as follows:
height: getHeight(),
function getHeight() {
		return $(window).height() - $('h1').outerHeight(true);
	}

I'm using this effectively in one location and it hits the server twice for the two ajax based dropdowns, but works.  In my most recent use of this, it isn't working, and I didn't think to remove (comment out) the height setting, which when I did things started working as I expected and the hit to the server occurred only once.

**Comment by wenzhixin** [comment]
have you solved your problem? @dfmaxwell

**Comment by dfmaxwell** [comment]
I do not recall.  I had to move on and work on other projects.  I think it was related to the getHeight function I was using.  For now we can close this.  If I get back to test and such I will make sure I have the latest source code first.  Thank you.
