### ISSUE TITLE
Custom Data-Fields and Data-Formatter Search

### ISSUE THREAD

**Issue by mgitis** [wenzhixin/bootstrap-table#1512]
(This issue is similar to that of #142)
 
I have been looking to see where it was possible to search formatted data columns and I found this post. I see where it is possible to search a column where the data-field is set to a known field from the binding json data source, hence if there is a field called "field1" in the binding json data. then once that field is set when creating the table header it can be searched. Now suppose your binding json data was complex and all data would have to be formatted as there would be the need to have multiple custom fields; that is, the table will consist of data that is a combination of data within the binding json data forming logically a new field. For example, in the json binding object you have "firstname" and "lastname", however you want to concatenate both fields and make a new field called "name". From this example "name" does not exist in the binding json data and hence the property data-field cannot be set to "name". How do you go about setting this field so that it could be searched by the built-in search utility or the filter plugin / extension? Please note that in this case I require a custom "field" as I am currently using "operate" as data-field value and it appears that the field ("operate") cannot be searched. Also, note that the custom fields can have more complex combinations and formatting than outlined in this simple example.

JSON data: {"firstname":"john", "lastname:"doe"}

Column Header:
&lt;th&gt; data-field="operate" data-formatter="opNameFormatter" data-sortable="false"&gt;Name&lt;/th&gt;

JavaScript:

function opNameFormatter(value, row, index) {
return row.firstname + ' ' + row.lastname 
}

Also, note that I tried setting the data-field to one of the know fields from the binding json object and I was able to do a search on the field. However, this will not work especially if the json object and the combinations become more complex. Hence I cannot use the same field name for the data-field properties especially if within the json object there is a object with multiple properties (e.g return row.personalinfo.gender and return row.personalinfo.maritalstatus in two separate data-formatter functions). The data-field will not recognize "gender" or "maritalstatus", but will "personalinfo" which cannot be used multiple times as data-field appears to be unique.

Thanks in advance

**Comment by wenzhixin** [comment]
Sorry, can you provide a jsFiddle to show what you want?

**Comment by Shobana16** [comment]
data-search is true but still all columns in a table is not searchable. Only 1st two columns are searchable. rest are not searchable. Can you please help here what i missed? 

'<table id="tableResults" data-pagination="true" ' +
                            'data-page-size="10" data-page-list="[10, 20, 50, All]" '+
                            'data-search="true" data-hover="true" data-striped="true" data-sort-name="create_time" data-sort-order="asc" >' +
                            '<thead><tr>'+
                            '<th data-field="create_time" data-align="center" data-formatter="formatCreateTime" data-sortable="true">Request Time</th>' +
                            '<th data-field="url" data-align="left" data-formatter="formatUrl" data-sortable="true" data-events="clickUrlEvent">Resource</th>' +
                            '<th data-field="method" data-align="center" data-formatter="formatMethod" >Method</th>' +
                            '<th data-field="status" data-align="center" data-formatter="formatStatus" data-sortable="true" >HTTP Status</th>' +
                            '<th data-field="id" data-align="center" data-sortable="true" data-visible="false">Id</th>' +
                            '</tr></thead></table>';

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
