### ISSUE TITLE
merge various Cells in bootstrap Table

### ISSUE THREAD

**Issue by AndresOnteal** [wenzhixin/bootstrap-table#1513]
I'm new to bootstrap table, I'm using the method MergeCells bootstraptable, I once operated at what I did the following code to unify several rows, I wonder what I'm doing wrong.
```
$(function () {

            var table = document.getElementById('table');
            var rowLength = table.rows.length - 1;
            var count = 0;
            var row = table.rows[1].cells[0].innerHTML;
            var saveIndex = 0;
            for (var i = 0; i < rowLength; i += 1) {
                if (row === table.rows[i].cells[0].innerHTML) {
                    count++;
                } else {
                    row === table.rows[i].cells[0].innerHTML;
                    mergeRows(saveIndex, count);
                    saveIndex = i;
                    count = 0;
                }
            }
        });

        function mergeRows(index, rowspan) {
            $('#table').bootstrapTable('mergeCells', {
                index: index,
                field: 'ciudad',
                rowspan: rowspan
            });

        }
```
What I do is call bootstrap function and unify according to the types of records

**Comment by dabros** [comment]
@AndresOnteal - jsfiddle please: https://github.com/wenzhixin/bootstrap-table#reporting-issues

That will hopefully also help explain the 'actual output' vs 'expected output', as entirely unclear what is happening now as opposed to what you want, and we need fiddle to see if anything else affecting it.

Plenty of fiddle examples there and even in other issues, very easy to create.

**Comment by AndresOnteal** [comment]
http://jsfiddle.net/janbs/sz42rymd/2/

There's the example I want is to unify groups, but I just always unifies the first group.

**Comment by dabros** [comment]
Okay, so your description still is vague, but what i can tell from the fiddle indicates you want to **group/merge** the *first column*? if it matches the row below...

Obvious question is why, though i guess its maybe something if you really fixed on that concept and dont care overly about filtering or sorting.

Filtering or sorting aside (as that would require you to use OnPostBody callback, which I would actually recommend regardless as far better form even if not expecting a refresh of contents) then the issue maybe around line 12 on your fiddle...

Im busy atm, but i will play with it more later, maybe refactoring into a post-body callback or similar would work, or slightly different comparator - ill have to look at grouping a little more first.

**Comment by dabros** [comment]
Solution: http://jsfiddle.net/dabros/sz42rymd/4/

Read the lines i changed carefully, your use of starting ints was wrong (super obvious when debugging) and placing console.log calls in merging function helped fix saveIndex issue.

Seemed to be indexing and a typo on your part (what was the second "===" doing there in an assignment???)

Still, read note in previous comment and refactor that code into a 'OnPostBody' or similar callback if still wanting to use it, even if you dont intent to add sorting, filters or any more functionality to the table - its still better form in case you use that code anywhere else or go back to it later to add more.

**Comment by wenzhixin** [comment]
:+1: thanks @dabros, close the issue.

**Comment by AndresOnteal** [comment]
thanks @dabros :+1:
