### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by erick-chali** [wenzhixin/bootstrap-table#1515]
@wenzhixin I'm trying to set  column width but its not working.
I try to do it by data-width="200px" 
And columns : [{width : 200}] both are not working can anyone help me out please.
Thanks

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle? https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by erick-chali** [comment]
@wenzhixin here it is, I appreciate it. 
https://jsfiddle.net/erickchali93/opjaf0tL/1/

**Comment by adrianmihalko** [comment]
+1 for this

I have same problem. 
http://jsfiddle.net/7Ln94oc7/2/

**Comment by erick-chali** [comment]
I think I solved it, 
    `<div class="table-responsive">`
        `<div class="container">`
            The table here
        `</div>`
    `</div>`

And after that the width was placed with no problem, now I'm just trying to fix the resetView action because apparently it overrides the width that was set previously, when the screen changes the size.

**Comment by MonrealRyan** [comment]
+1 for  column width

**Comment by dabros** [comment]
ref: #1915

**Comment by dabros** [comment]
@erick-chali @MonrealRyan @adrianmihalko 

Can all 3 of you please confirm this solves your issues, so we can consider this closed.

**Comment by MonrealRyan** [comment]
@dabros  - sorry late response, but still not working on my side.

**Comment by wenzhixin** [comment]
@MonrealRyan you can try the solution of @erick-chali

**Comment by MonrealRyan** [comment]
@wenzhixin - the table is responsive but not the td or the column.

**Comment by erick-chali** [comment]
ok, then I think we can close this issue since this was my question in the first time, I'm sorry for the delay.

**Comment by Ericzhiluo** [comment]
+1 I have the same issue. Setting data-width have no effect.

**Comment by sanjeev473** [comment]
https://dotnetgenetics.blogspot.com/2018/10/set-bootstrap-table-column-width-and.html
