### ISSUE TITLE
Exporting gives error if the data has unicode characters || Bootstrap Table export

### ISSUE THREAD

**Issue by cetindogu** [wenzhixin/bootstrap-table#1516]
need a solution for version 1.9.0 because jquery.base64.js is not in the source code.

**Comment by dabros** [comment]
ref: #189 - i believe this is topic he referring to for jquery.base64.js

**Comment by dabros** [comment]
@cetindogu - i suggest you delete this issue and post to that closed issue, as subscribers (posters) will be notified, and this is spam if that issue is not solved (for you at least) - it can reopened if confirmed still not solved.

**Comment by wenzhixin** [comment]
Now the base64 function in the export source: https://github.com/hhurz/tableExport.jquery.plugin/blob/master/tableExport.js#L908
