### ISSUE TITLE
filterBy function with custom data attributes

### ISSUE THREAD

**Issue by alecb7** [wenzhixin/bootstrap-table#1517]
Hi there,

I'm using this on an ASP.net MVC4 Umbraco application. 

We have a custom data attribute on our table, let's call it data-x, which we are filling dependant on whether a query string is sent through. I have a list of county councillors which i want to filter by division, the value of the division is what is in data-x. If that value is just one word, e.g. "Hucknall" the search works fine. However as soon as there is a space involved e.g. "Arnold North" it returns no value, even though if i search for "Arnold North" it returns the 2 values it should.

Any suggestions?

Cheers

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle? https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
Close this because [there is no any response in 7 days](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels).
