### ISSUE TITLE
Finding correct row index

### ISSUE THREAD

**Issue by rahulmuraliqllabscom** [wenzhixin/bootstrap-table#1518]
Hi I am having a column with a button. On click of that button I do some modification to the element of that row, for the purpose of updating that row I am collecting row index as follows
var row = $(this).parent().parent();
var rowindex = row.index();
but this works fine in the first page only. Like when I press a button on row 2 in second page(pagination) I am getting the row index as 2 itself but actually it is different. So when I update table row using update method and row index a different row is getting updated

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle? https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by dabros** [comment]
@rahulmuraliqllabscom - please provide an update on this

**Comment by rahulmuraliqllabscom** [comment]
I am  a newbie to js and not in a level to create a js fiddle. I will explain again what I did I used bootstrapTable with client side pagination 

So let us assume i had 100 rows and I choose to display 10 rows per page the item I displayed in a row had a status update button which when pressed updated the status of the item. So in order to populate the row with new status, I retrieved the row index of the row using the code
 var row = $(this).parent().parent();
 var rowindex = row.index();

the element was the button which I clicked but if i was on the second page and pressed 22nd element the the row index I received was 2 with this two when I updated the row of bootstrapTable  the original second row was getting updated

**Comment by rahulmuraliqllabscom** [comment]
anyway since my requirement changed to an extensive search for elements. I dropped bootstrapTable and implemented search with elastic and server side pagination of table with ordinary table element

**Comment by dabros** [comment]
Okay, you gota share the code you used to do this.

its pretty easy to use the templates from https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports to mimic your situation.

What it sounds like is you need to instead use something like `$(this).parent('tr').data('index')`

 As I state in #1644, thats one way of retrieving the index as its printed on each TR as 'data-index'.

And i already typed all that before you posted again ;)

**Comment by pettechbytes** [comment]
@dabros, when I try to use` $(this).parent('tr').data('index') ` it says that it's undefined.  Here's my example:

```
$('table').on('click', '.edit-rule', function () {
    var ruleid = $(this).data('ruleid'); // this returns the correct id I'm looking for
    var row = $(this).closest('tr'); // this returns the correct row
    var rowindex = $(this).parent('tr').data('index'); // this returns undefined
});
```

**Comment by dabros** [comment]
@pettechbytes 

Always know what `$(this)` refers to, `console.log([$(this),$(this).parent('tr')])` will show you whats happening. Your attaching an event to the table, not to any individual cell, im unsure if the other lines would work either, always console.log to test (or use breakpoints in sources panel for chrome, or similar for other browsers)

**Comment by tagx** [comment]
@pettechbytes in that case just try row.data('index'); because if it gives you back the correct row then in some point it can gives you back the index you need. :)
