### ISSUE TITLE
How can I set the first row always selected while searching?

### ISSUE THREAD

**Issue by abazanvillanueva** [wenzhixin/bootstrap-table#1519]

**Comment by dabros** [comment]
???

1. what is selected?
2. where is your fiddle (https://github.com/wenzhixin/bootstrap-table#reporting-issues)
3. we arnt mind readers

**Comment by wenzhixin** [comment]
I believe you can use our [API](http://bootstrap-table.wenzhixin.net.cn/documentation/#events) to do what you want, for example you can listen the `onLoadSuccess` event, and then use `check` method to select the first row.
