### ISSUE TITLE
selectPage methode fails in cookie extension

### ISSUE THREAD

**Issue by KlapZaZa** [wenzhixin/bootstrap-table#1521]
Code line 317 in cookie extension fails. It needs to change from idsStateSaveList to cookieIds. I think it is a change fail.

It should look like this:
    BootstrapTable.prototype.selectPage = function (page) {
        _selectPage.apply(this, Array.prototype.slice.apply(arguments));
        setCookie(this, cookieIds.pageNumber, page);
    };

Over and out ;)

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle to show the problem and create a pull request?
