### ISSUE TITLE
header and column data not aligned properly in chrome and IE10,IE11

### ISSUE THREAD

**Issue by KulanthaivelChinnadurai** [wenzhixin/bootstrap-table#1536]
please check the below link for the issue.
http://jsfiddle.net/hf50xg7z/ 
Please scroll till last column to see alignment issue.
Note: In firefox alignment is working fine.
![girhub](https://cloud.githubusercontent.com/assets/12044331/10422118/6fa48298-70d3-11e5-869a-b9ace68ab508.png)

Request to provide a solution.

**Comment by geospatialem** [comment]
I am having similar issues in my application as well (in Internet Explorer, Chrome, and Firefox), *see below*:

**Overall view:**  
![table-alignment-screenshot](https://cloud.githubusercontent.com/assets/5023024/10732874/2f5f5b16-7bca-11e5-9cc4-6a0a8be813b9.png)

**Close view:**  
![closeup-image](https://cloud.githubusercontent.com/assets/5023024/10732928/608fb8e8-7bca-11e5-99d9-4dadb5a3849e.png)

**Comment by darzzydarzz** [comment]
any updates on ETA for this one?

**Comment by LawrieDawson** [comment]
Hi
Do we have an update on the call.  it is happening in most browsers.

**Comment by LawrieDawson** [comment]
Managed to fix this for all browsers except IE 9 
I put this bit of code into the bootstrap-table.js file at roughly line 1904.
 var colWidth = $('#table thead')[0].children[0].children[index].children[1].getBoundingClientRect().width;  
and  changed   line 1905/6 from 
that.$header_.find(sprintf('th[data-field="%s"]', visibleFields[index]))
                .find('.fht-cell').width($this.innerWidth());

to

that.$header_.find(sprintf('th[data-field="%s"]', visibleFields[index]))
                .find('.fht-cell').width(colWidth);


We don't use anything below IE 9 and seems to work in 10 11 and edge.
you may need to clear the browsers cache to see the changes.

 Any help with IE 9 would be appreciated.

**Comment by djhvscf** [comment]
As you can see here this is solved in our latest release http://jsfiddle.net/djhvscf/hf50xg7z/7/
