### ISSUE TITLE
onReorderRowsDrag and onReorderRowsDrop

### ISSUE THREAD

**Issue by francescomeloni** [wenzhixin/bootstrap-table#1537]
I am having issues trying to work with reorder rows, it works but i need to change some variables when the row is moved. ( old order, new order ) 
is There a jfiddle somewhere? 
Thanks

**Comment by promogest** [comment]
I manage to use 
```javascript
 $table.on('reorder-row.bs.table', function (e, order) {
            console.log(order)
            $.each(order, function (i, value) {
            console.log(value.denominazione, value.unique)
        });
        })```

but reorder is not  active until i click on data-show-toggle ot something like that. 
$table.bootstrapTable({ data: riga.slice(1),height:  $(window).height()- 395});

**Comment by francescomeloni** [comment]
i found a working simpler solution. i have a strange behavior with the insertRow after reorder that seems not work properly .... i ll close this bug anyway. Maybe ill fill another issue
