### ISSUE TITLE
filter-control => unset unnecessary values from select options

### ISSUE THREAD

**Issue by aattd** [wenzhixin/bootstrap-table#1540]
When we have many select filters, it would be great to update filter options and hide values which are not exists in current data view. 

I will better explain it on example: 
https://jsfiddle.net/e3nk137y/3345/

If we choose "First" : "A" than on filter "Second" option "3" shoud be disabled / deactivated .
Generally it would be great to update all filter options after each filtering action.

additional on stackoverflow: http://stackoverflow.com/questions/33101205

**Comment by djhvscf** [comment]
This can be a good feature! @aattd

**Comment by jamesmikesell** [comment]
So i love this feature idea.  Server-side paging and setting the select values from variable/json will definitely make this very difficult to implement for anything other than the situations where we have all of the table data loaded.  But, even at that, this could be an awesome feature to use for the situations not described above.

**Comment by billbo99** [comment]
Any luck progressing this feature request ?

**Comment by djhvscf** [comment]
See this **PR** https://github.com/wenzhixin/bootstrap-table/pull/2460

**Comment by billbo99** [comment]
Would it not be better to refresh the select list based on the values visible in the current column.   

EG rather than disable the options, delete or hide them in the select list.

**Comment by djhvscf** [comment]
@billbo99 refresh is not an option because we can lose performance, I will change the code in order to hide the options

**Comment by djhvscf** [comment]
@billbo99 see this: https://jsfiddle.net/djhvscf/e3nk137y/7581/
