### ISSUE TITLE
Make a table from 2 bootstrapTable

### ISSUE THREAD

**Issue by jonathangreco** [wenzhixin/bootstrap-table#1541]
Hi,
First of all, great module, so full of possibilities.

I post an issue because I have one interrogation that I'm unable to solve at the moment.

I have 2 bootstrap tables.

1- One wich represents my items ( between 0 and 100 000 depends on the user who manage those tables)
2- Users from each networks they have. ( Some networks has also 100 000 lines)

From those two tables, they can select some or all those lists they have for populate another table to create massive orders.

Table Users 
---------------
user 1
user 2
...

Table items
---------------
item 1
Item 2

Composite table
---------------------
user --------------------Item 1 ---------------------------------------item 2 -------------------------- ...
user 1----------------- quantity : 70---------------------------------quantity : 50
user 2-----------------quantity : 20---------------------------------quantity : 10
...

Can I achieve this ? With bootstrap table or do I have to interact with server to create and generate this composite table ?

**Comment by wenzhixin** [comment]
Can you show me the JSON data of your tables? For example these data: 
`quantity : 70---------------------------------quantity : 50`

**Comment by jonathangreco** [comment]
Those data will be filled in the futur constitued table.. (editable) I just need to create this table.

**Comment by wenzhixin** [comment]
have you solved your problem?

**Comment by jonathangreco** [comment]
Hi, thanks for your concerns. Finally i didn't use bootstrap table for this, i make a custom HTML table representation.

Works but much more difficult in native HTML.

**Comment by wenzhixin** [comment]
Sorry, I'm not quite understand what you want, so don't know how to help. Let's close this issue.
