### ISSUE TITLE
server side filter-control fails when results not in first page

### ISSUE THREAD

**Issue by waspinator** [wenzhixin/bootstrap-table#1542]
When using server side data and filter-control no results are displayed when the last searched field has results beyond the pagination limit. Is there a way to have each search box send an individual get variable with it's own query so that the server does the filtering instead of the client?

http://jsfiddle.net/waspinator/Lnoj9x4y/

**Comment by dabros** [comment]
@waspinator  - i think this question slipped under the radar, but ive seen referances to filter-control being used with server code (search for other issues here, removing 'is:open' filter)

Please have a look then '#'+id any that were relevant if they didnt help you or you still have issues
