### ISSUE TITLE
Table refreshes but header name don't

### ISSUE THREAD

**Issue by dltccorreia** [wenzhixin/bootstrap-table#1543]
I'm using the boostrap-table. I pass 2 variables to call a function (by click in a button) that update the table with data. Everything works ok, only the "measure_name" that do'nt refresh... If I made alert(measure_name) I will see my new name but not in the table...
Anyone with a solution?

function go (url,measure_name) {
	$('#table').bootstrapTable({
    url: url,  //get_db_data/ajax_get_chart.php
	pagination: false,
	pageList: [10, 25, 50, 100, 200],
	search: true,
	showToggle: true,
	showPaginationSwitch: true,
	sortName: 'Timestamp',
	sortOrder: 'desc',
	icons:{paginationSwitchDown: 'fa fa-chevron-down', paginationSwitchUp: 'fa fa-chevron-up', toggle: 'fa fa-toggle-on'},
	exportOptions: {fileName: 'OUME-'+measure_name.replace(/\s/g, '')},
	height: '350',
	showExport: true,
	showFooter: false,
	exportDataType: 'all',
	exportTypes:['csv'],
    columns: [{
        field: 'Timestamp',
        title: '<?php echo $lang['HH_TIMESTAMP']; ?>',
		sortable: 'true'
    }, {
        field: 'Value',
        title: measure_name,
		sortable: 'true'
    },]
	
});

$('#table').bootstrapTable('refresh', {
    url: url
});

	}

**Comment by dabros** [comment]
@dltccorreia - there is code block markdown (look for markdown help button when posting) but even then this is definitely a case we absolutely do need a jsfiddle: https://github.com/wenzhixin/bootstrap-table#reporting-issues

Plenty of examples following that link or in other topics, so i suggest save section of your data-source as json string or js array or whatever, place it in fiddle and point to that in data option - that allows us to see better whats going on with you.

A side note is if you already defined url, i dont think you need to pass it again when refreshing, and fiddel will help us see why you refreshing and how as well.

**Comment by wenzhixin** [comment]
in your case you need to use refreshOptions or destroy method when you clicking the button.
