### ISSUE TITLE
Sorting anomaly

### ISSUE THREAD

**Issue by cjamico** [wenzhixin/bootstrap-table#1544]
I'm experiencing a strange sorting issue.  This issue only occurs in the Chrome browser; IE and Firefox seem unaffected. When my column contains all the same values and is sorted, rows jump around randomly.  Sometimes only a few rows jump around and the others remain in place as they should.  No sorting should occur at all because the data in the whole column is identical.  The issue seems to present itself when a custom sort algorithm is used.  

Here is my sorting function, if that helps:
```
function filterColumnSorter(a, b)
{
	var reg = /<.*?\/?>/g;
	var strippedA = a.replace(reg, '');
	var strippedB = b.replace(reg, '');
	if (strippedA < strippedB)
		return 1;
	if (strippedA > strippedB)
		return -1;
	return 0;
}
```
Upon debug outputting the returned values of the sort function, all comparisons return 0 as they should. Yet, the order changes in Chrome.
All other functionality and sorting work as expected.  This is the only case of strange behavior in my table.

Here is a jsfiddle which demonstrates this behavior ( https://jsfiddle.net/ndmqudad/7/ ). Sorting on the Number column should not change the row order because all the values are the same.  As you can see the fiddle always returns 0 and the sort order is still affected.  Sorting on Chrome causes random row movements.  IE and Firefox do not change row order.

**Comment by dabros** [comment]
@cjamico - not sure myself, but some other odd things i noticed are:

1. no console.log inside custom sort function is ever triggered, and 
2. changing to rand output in custom sort function changes nothing, but
3. removing data-sorter makes results jump even more...

https://jsfiddle.net/dabros/ndmqudad/9/

Im not entirely sure that your custom sorter is even being used in this fiddle, as no console output or definable change in results by changing returns to random. If you want to confirm that, use callback for on-sort or similar and debug table object - or debug table object on onPostHeader and get columns, or debug anywhere and just dig to find it.

The jumping seems to happen anyway without this, but very odd the sorter doesnt 'seem' to actually be used in your fiddle.

**Comment by cjamico** [comment]
@dabros  yes, sorry wrote the issue then edited it to include the fiddle.  

The fiddle was just some toying around to see if I could replicate the behavior, it is not using my custom sorter.  Once I had the fiddle going I noticed the behavior even before adding the custom sorter.  I figured if it exhibited the behavior without my sorter, it was more evident there is an issue.

**Comment by dabros** [comment]
@cjamico - still cant really help you myself without a working fiddle that shows YOUR issue (with custom sorter). This quirk is prob just core code something, but the unknown factor of why that fiddle sorter not working, plus the fact you would ideally look at tweaking your custom sorter to avoid this - I need a working fiddle

Maybe someone else noted this before, maybe even developer, though the 'standard miss-sorting' (switch index of 2 entries fairly consistently between eachother if all values being sorted are equal), that not really an issue, but the everything jumble you fiddle is without data-sorter maybe more so - but that is core code so lets get working fiddle of your issue first

**Comment by djhvscf** [comment]
This is a chrome bug. See this: http://stackoverflow.com/questions/12743654/how-can-a-sorted-javascript-array-return-incorrect-values-from-the-comparator

Should we close this issue, @wenzhixin ?

**Comment by wenzhixin** [comment]
OK @djhvscf , close this issue.
