### ISSUE TITLE
Sub Table without the data-icon

### ISSUE THREAD

**Issue by GabrielUlici** [wenzhixin/bootstrap-table#1546]
Hi,

I would like to use this feature but i don't want the data-icon to appear. http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html

or another question it is possible to trigger onExpandRow from onClickCell.

Thanks.

**Comment by dabros** [comment]
onExpandRow is a callback, ie. its calls you as event triggered, it doesnt trigger anything itself...


Also, these relate to details view, second link refers to the expandRow and similar methods: #1406,  #964

As to no details icon, maybe just leave it there but allow row clicks too, or use classes and css (no js) to always hide first column ("tr > td:first-of-type" or similar, easy google search). There is #1249, but faruk has something like 30 poorly constructed topics (some removed later i think, but most remain) and if you want to add a fiddle there we can maybe help you with same goal - it is a seperate issue so best to keep it in that post if you really keen on that exact execution (inline '+' with no details-icon column).

Im a little vague on exactly how sub-tables work but i assume calling expandRow on row click should do it: http://issues.wenzhixin.net.cn/bootstrap-table/

Also, if you want a solution handed to you, we absolutely need a working fiddle, else we can only describe how and 'maybe' point to useful examples: https://github.com/wenzhixin/bootstrap-table#reporting-issues

**Comment by GabrielUlici** [comment]
So here is fiddle https://jsfiddle.net/gabe_green/nn8fwL6z/2/

i want in onClickCell to trigger onExpandRow

**Comment by dabros** [comment]
Solution: https://jsfiddle.net/dabros/nn8fwL6z/3/

Im not 100% sure this is exactly what you wanted, as your code is a little odd tbh but i guess for demo purpose (dummy data).

But you click on name column, details view with sub-table appears.

I would have fixed it in 2min except i got stuck as didnt realise you had already thrown in css without testing it - tell us that next time. I assumed it was a working sub-table demo that just needed to add a second way of expanding details view, not that you had already broken it.

I have some commented code there about expandRow when my initial didnt work, but then i looked again at css and how details view actually presented (see html ouput using console whenever changing css that suddenly breaks something).

**Comment by GabrielUlici** [comment]
Yes this is perfect, thank you.

Sorry about the css i was testing something and i forgot to remove it.

**Comment by danger89** [comment]
@dabros Your CSS solution cause issues with changing perspective to list iso table overview.

I think its better to use the `data-icons` instead:
https://bootstrap-table.com/docs/api/table-options/#icons

[See jsfiddle](https://jsfiddle.net/wenyi/nj7omwtk/5/).
