### ISSUE TITLE
how to show datetime object in bootstap table

### ISSUE THREAD

**Issue by ndalal007** [wenzhixin/bootstrap-table#1547]
Hello,

I'm new to web development and trying to create a bootstrap table that can display datetime.
Currently the table column shows as [object Object].

I'm using php to generate json and then using javascript to decode json.
Other column data shows correctly like username, location, eventtype but not timestamp.

The code below resides in html file:
--------------------------------------------------------------------------------------------------------------
       
        <script src="Scripts/jquery-1.9.1.min.js"></script>
        <script src="Scripts/bootstrap.min.js"></script>
        <script src="Scripts/bootstrap-table.js"></script>
        <script src="scripts/json.date-extensions.min.js"></script>

                <table class="table" id="myTable">
			<thead>
				<tr>
					<th data-field="Username">Username</th>
					<th data-field="EventType">Event Type</th>
                                        <th data-field="TimeStamp">Timestamp</th>
					<th data-field="Location">Location</th>
				</tr>
			</thead>
		</table>

		<script>
		    $('#myTable').bootstrapTable({});
		</script>

            <script>
    		    function load() {
    		        var xmlhttp = new XMLHttpRequest();
    		        var url = "/php/connect.php";

    		        xmlhttp.onreadystatechange = function () {
    		            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
    		                myFunction(xmlhttp.responseText);
    		            }
    		        }
    		        xmlhttp.open("GET", url, true);
    		        xmlhttp.send();

    		        function myFunction(response) {
    		            var jsonData = JSON.parseWithDate(response);
    		            $('#myTable').bootstrapTable("load", jsonData);
    		        }
    		    }
		</script>

        <script>
            JSON.useDateParser();
        </script>
--------------------------------------------------------------------------------------------------------------
Any help is appreciated.
Thanks.

**Comment by dabros** [comment]
@ndalal007 - for this we really need a working fiddle: https://github.com/wenzhixin/bootstrap-table#reporting-issues

I suggest looking at network panel or opening data-url in new window and copying at least some rows, wrapping in single or double quotes and storing as js (string) variable, then point to that for your data. 

You shouldnt need to worry about the xhtml code, but do keep it as json string so you can call those JSON functions, including external assets using jsfiddle option on left for 'external resources'.

Im actually willing to bet its the JSON.useDateParser or JSON.parseWithDate or related code, as if it stays as a string then it should have no issue. A responseHandler or column formatter option may be needed if that code not avoidable, but all it would prob do is 'return obj.ToString()' or similar - but cant say without working fiddle.

http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options
http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by ndalal007** [comment]
Thanks data-formatter attribute did the trick though I had to add a simple javascript function to return date.
