### ISSUE TITLE
Sub Table cannot be sorted.

### ISSUE THREAD

**Issue by sketchman-nyt** [wenzhixin/bootstrap-table#1548]
Sorting on a subtable causes the subtable to close and the sort to bubble to the parent table.

An example can be seen here: http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html

**Step 1:** Click the + arrow to show the sub table
**Step 2:** Click on one of the sort arrows within a header column in the sub table.

**Reasons for this problem**

1. The event may not be being captured for the sub table but instead the parent table.
2. When initBody() is called, it recreates the entire table instead of editing it.

**Comment by prograhammer** [comment]
Thanks for all the great work on this project guys. But any idea on when we could see this problem resolved? I know there are a lot of other issues, but this one seems to be a very fundamental problem of high priority. I committed to this table for my latest project and was quite surprised the sub table wouldn't sort.

**Comment by etortato** [comment]
Give a try to this solution: https://github.com/wenzhixin/bootstrap-table/issues/1712

**Comment by wenzhixin** [comment]
Fixed
