### ISSUE TITLE
cant populate bootstrap table from json data from server

### ISSUE THREAD

**Issue by xmanpsv** [wenzhixin/bootstrap-table#1549]
i can't populate bootstrap table from json data from server, please help.

  <table id="table-javascript">
                       
                    </table>
                    <script>
                        $(document).ready(function () {

                            $('#table-javascript').bootstrapTable({
                                url: 'Datos.asmx/ObtenerReporteConcentrado',                                
                                method: 'get',
                               // pageSize: 10,
                               // pageList: '[10,20,30,40,200]',
                                //sidePagination: 'client',
                                dataType: 'json',
                                queryParams: function (p) {
                                    return {
                                        iFamilias: 1
                                    };
                                }, columns: [
                 {
                     field: 'ClaEmp',
                     title: 'ClaEmp'

                 },
                  {
                      field: 'Empresa',
                      title: 'Empresa'

                  }, {
                      field: 'Producto',
                      title: 'Producto'

                  }, {
                      field: 'TotalDia',
                      title: 'TotalDia'

                  }, {
                      field: 'TotalDiaComparado',
                      title: 'TotalDiaComparado'

                  }, {
                      field: 'TotalDiferenciaDia',
                      title: 'TotalDiferenciaDia'

                  }, {
                      field: 'TotalPorcentajeDia',
                      title: 'TotalPorcentajeDia'

                  }, {
                      field: 'TotalAcumuladoMes',
                      title: 'TotalAcumuladoMes'

                  }, {
                      field: 'TotalAcumuladoMesComparado',
                      title: 'TotalAcumuladoMesComparado'

                  }, {
                      field: 'TotalDiferenciaAcumuladoMes',
                      title: 'TotalDiferenciaAcumuladoMes'

                  }, {
                      field: 'TotalPorcentajeAcumuladoMes',
                      title: 'TotalPorcentajeAcumuladoMes'

                  }, {
                      field: 'TotalAcumuladoAnio',
                      title: 'TotalAcumuladoAnio'

                  }, {
                      field: 'TotalAcumuladoAnioComparado',
                      title: 'TotalAcumuladoAnioComparado'

                  }, {
                      field: 'TotalDiferenciaAcumuladoAnio',
                      title: 'TotalDiferenciaAcumuladoAnio'

                  }, {
                      field: 'TotalPorcentajeAcumuladoAnio',
                      title: 'TotalPorcentajeAcumuladoAnio'

                  }, {
                      field: 'Indice',
                      title: 'Indice'

                  }

                                ]
                            });

                           
                            $('#btnGenerar').click(function () {
                               $("#table-javascript").bootstrapTable('refresh');
                           });

                        });
                    </script>

 The response server:

![respuesta](https://cloud.githubusercontent.com/assets/15129278/10492726/305c06b4-7273-11e5-915a-386e2108c885.png)

please help me to solve my problem, what can i do??

![buscando](https://cloud.githubusercontent.com/assets/15129278/10492802/821a0e24-7273-11e5-834c-e975a9006b59.png)

![nocuentra](https://cloud.githubusercontent.com/assets/15129278/10492817/9399c40a-7273-11e5-855a-57f247e1bb6b.png)

the responsehandler send me 
"Uncaught TypeError: Cannot read property 'fixedScroll' of undefined"

**Comment by dabros** [comment]
@xmanpsv - without a fiddle its hard to say, you havnt included the actual json strings so we can test at all (screenshots are not sufficient as we can do nothing with them)

https://github.com/wenzhixin/bootstrap-table#reporting-issues

Create a generic fiddle using similar settings, including at least some rows from your json string in a var (one way is just open output in html window and just copy paste, wrapping in single or double quotes in var then point to that for data, see fiddle examples in link i posted)

My first guess is wonder why "d" index exists, and why "total" if its client side pagination. Try just returning the rows, as ive only ever seen "total" and "rows" index for server-side pagination examples, i may be wrong there but i just returned rows directly.

A responseHandler maybe needed if you cant change json output, see http://issues.wenzhixin.net.cn/bootstrap-table/ and script block below table for example

**Comment by djhvscf** [comment]
What is the version that you are using? @xmanpsv

**Comment by xmanpsv** [comment]
@dabros  thank you, in framework 3.5 + the index "d" is added automatically, i try to remove from my file, the "total" i can remove it.
i will create the fiddle to post it

**Comment by xmanpsv** [comment]
@djhvscf  jquery is 2.1.4
bootstrap  3.3.5
bootstrap table 1.9.0

**Comment by xmanpsv** [comment]
@dabros  when i change to server side pagination the responsehandler send me "Uncaught TypeError: Cannot read property 'Total' of undefined"

**Comment by xmanpsv** [comment]
@dabros  @djhvscf  i try to do the jsfiddle https://jsfiddle.net/xmanpsv/ccatLnrw/1/  
chek it please
thank

**Comment by dabros** [comment]
@xmanpsv - so your fiddle was broken, clearly so by any cursive glance as beyond not working at all (no console.log calls in certain places triggering) it had broken copy+pasted html.

https://jsfiddle.net/dabros/ccatLnrw/2/

I included copious notes on my changes, though to be honest im a little unsure exactly which step was absolutely needed, but you can just add my changes one by one - none will do any harm.

Do read notes there saying how responseHandler only works with remote data (url) so you can use that for affecting the json before table loads it rows.

I simplified the columns then it suddenly worked, i would suggest looking at that in your execution and maybe do what i did - remove "data-toggle" so it is explicitly initialized via js, not automattically, and then if still issues pass in columns as array. All column options (http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options) can just be passed in via indexes on that columns array.

**Comment by xmanpsv** [comment]
thank you @dabros  , @djhvscf 
i solve my problem, 
i change my code, replace via script by server side example like this

http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#server-side-pagination-table

**Comment by djhvscf** [comment]
Sounds greeeeat!! :) @xmanpsv

**Comment by kghulami** [comment]
djhvscf; can you share your final code here?
