### ISSUE TITLE
Why was bootstrap-table-all.js removed in v1.9.0?

### ISSUE THREAD

**Issue by mwatz122** [wenzhixin/bootstrap-table#1550]
Via ChangeLog:

[bug] Remove <code>bootstrap-table-all.js</code> and <code>bootstrap-table-all.min.js</code>.

Is there a reason the all-inclusive extensions file was removed? Is there any better way to include all extensions without referencing all of the *.js files individually in v1.9.0?

Any help or advice would be greatly appreciated! Thank you :-)

**Comment by djhvscf** [comment]
I'm not completely sure but I think it was removed because it was generating a lot of issues

**Comment by wenzhixin** [comment]
Yes, just like @djhvscf said, because there are many extensions now, if include all extensions will cause a lot of issues.

**Comment by djhvscf** [comment]
So, we can close this issue
