### ISSUE TITLE
Ignore detailView plus column when exporting as Ms-Excel

### ISSUE THREAD

**Issue by u01jmg3** [wenzhixin/bootstrap-table#1551]
When exporting a result set in Ms-Excel format, if detailView is set to `true` an empty column appears in column one of tableExport.xls.

Is there any way to prevent this and ignore the detailView column which contains a plus (+)?

```js
detailView: true,
detailFormatter: 'columnFormatter',
exportTypes: ['excel'],
showExport: true,
```

**Comment by dabros** [comment]
@u01jmg3 - i have no experience with this plugin, but https://github.com/hhurz/tableExport.jquery.plugin#options shows options you can pass in, which includes 'ignoreColumn'. 

I placed a  F12+breakpoint inside bootstrap-table.js in initHeader, so we can see if that first column has proper name (like "detail" or "details") that can be ignored, and got this for the first this.columns index:

```
0: Object
align: "center"
cardVisible: true
checkbox: true
checkboxEnabled: true
clickToSelect: true
field: "state"
fieldIndex: 0
order: "asc"
radio: false
rowspan: 2
searchFormatter: true
searchable: true
sortable: false
switchable: true
valign: "middle"
visible: true
```

Try using "state" in that "ignoreColumns" field, see if that works.

http://bootstrap-table.wenzhixin.net.cn/documentation/#events
http://issues.wenzhixin.net.cn/bootstrap-table/ (script block below table)
http://bootstrap-table.wenzhixin.net.cn/examples/#events (old, but shows syntax too)

**Comment by u01jmg3** [comment]
@dabros: thanks for your help

The following didn't appear to have any effect (possibly because not all options are passed through to tableExport):

```js
$table = $('.results').bootstrapTable({
    ignoreColumn: ['state']
});
```

Ended up going with this although applying on each table load is not efficient:

```js
$table = $('.results').bootstrapTable({
    onLoadSuccess: function(data){
        $('.detail').attr('data-tableexport-display', 'none');
        $('.detail-icon').parent().attr('data-tableexport-display', 'none');
    }
});
```

**Comment by dabros** [comment]
@u01jmg3 - look at the link i gave you, that is **not** how you apply export settings

https://github.com/hhurz/tableExport.jquery.plugin#options

**Comment by u01jmg3** [comment]
@dabros - I've amended my syntax but it was this link which helped me correct it: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/export#exportoptions

Final code to ignore the details view column when exporting:

```js
$table = $('.results').bootstrapTable({
    detailView: true,
    exportTypes: ['excel'],
    showExport: true,
    exportOptions: { ignoreColumn: [0] }
});
```
