### ISSUE TITLE
showRow/hideRow does not work 1.9.0

### ISSUE THREAD

**Issue by GabrielUlici** [wenzhixin/bootstrap-table#1552]
you can test this one it does not work

http://issues.wenzhixin.net.cn/bootstrap-table/#methods/showRow-hideRow.html

**Comment by Datyedyeguy** [comment]
Looks like both the `index` and `uniqueId` properties are required now.  Pass in the one you aren't using as `undefined` for now to work around it.

**Comment by GabrielUlici** [comment]
ok, thanks

**Comment by wenzhixin** [comment]
fixed
