### ISSUE TITLE
Exporting all the rows of table not working

### ISSUE THREAD

**Issue by vikashpar** [wenzhixin/bootstrap-table#1553]
Bootstrap is not exporting all the rows of the table via bootstrap table. 

Please help.

**Comment by djhvscf** [comment]
Did you check this: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html ? @vikashpar

**Comment by vikashpar** [comment]
Yes, but it gives me an error "that.togglePagination" is not a function and also in the example once I select the "Export All" option and export the excel it does not do anything unless I again change the export type option.

Please help, am I missing anything?

**Comment by vikashpar** [comment]
It seems the code is not able to recognize "that.$el.on('load-success.bs.table', function () {",
as it stops here in file "../assets/bootstrap-table/src/extensions/export/bootstrap-table-export.js"

**Comment by dabros** [comment]
@vikashpar - as the live example running from 'master' is working fine, we really need a working fiddle from you showing this issue (https://github.com/wenzhixin/bootstrap-table#reporting-issues) or at least much more detail.

Please either include fiddle or at least copies of full stacktrace and error line from web dev (F12 console). Also include your settings, so html TABLE open tag and any js settings if init via js and not 'data-toggle'.

We may still need fiddle, but this might be enough in this case.

**Comment by dabros** [comment]
@vikashpar - still waiting

**Comment by vikashpar** [comment]
Hi,

Thanks, the issue is resolved.

Sorry for replying you so late.

Please close the ticket.

Regards,
Vikash.

Thanks and regards,
Vikash Parijat.
Mobile No.: +919560907741
