### ISSUE TITLE
How to update columns from server side pagination?

### ISSUE THREAD

**Issue by epool** [wenzhixin/bootstrap-table#1554]
Well, I want to update my table columns when I am using server side pagination. My uses cases is that I am showing the following.

Page 1

Product name | 01-10-2015 | 02-10-2015 | 03-10-2015 | 04-10-2015
------------ | ------------- | ------------- | ------------- | -------------
Product 1 | $12.90 | $12.90 | $12.90 | $12.90
Product 2 | $12.90 | $12.90 | $12.90 | -
Product 3 | $12.90 | $12.90 | - | $12.90

But in some cases the date ranges in the columns could be different for the displayed product per page(maybe more or less dates)

Page 2

Product name | 03-10-2015 | 04-10-2015
------------ | ------------- | -------------
Product 4 | $12.90 | $12.90
Product 5 | $12.90 | $12.90
Product 6 | $12.90 | -

I know maybe this is not the best uses case, but this is my requirements.

In advance thanks.

**Comment by dabros** [comment]
@epool - you really need to break it down and tell us exactly what your current output vs desired output is.

What is it currently doing? (details, not just screenshots)

What **exactly** do you want it to be doing?
