### ISSUE TITLE
getRowByUniqueId and RowIndex

### ISSUE THREAD

**Issue by hallard** [wenzhixin/bootstrap-table#1555]
Sorry guys for my dummy question, I've got a table with values that I receive from Websocket.

To simplify dev and for testing, I simulate new data with a button click. I used of course option `data-unique-id='na'`
I can retrieve my row with `getRowByUniqueId` when the row already exists, and if not I append the new data with 'append'. Append is working fine.
My problem is that `getRowByUniqueId` does not return row index so I can't use `updateRow` after.

So my question is, how to get row index (or data-index property of tr) to be able to update row I've just got ?

Here is my sample function 
```javascript
$('#btn_iinst').click(function () {
   // New simulated data
    var dataTinfo = {  "na": "IINST", "va": "005", "ck": "X", "fl": 4 } ;

  id = dataTinfo['na']
  console.log('ID=' + id);
  idx = $('#tblinfo').bootstrapTable('getRowByUniqueId', id);
  console.log('idx=' + idx);

  if (idx == null)
    // This one is working fine
    $('#tblinfo').bootstrapTable('append', dataTinfo)
  else
   // here is my problem I don't know row index
    $('#tblinfo').bootstrapTable('updateRow', rowindex blahblah)
  });
});
```

thanks for your help

**Comment by Avivbh** [comment]
I don't know of any way to get the row id based on unique id but if all you want to do is update then check the new merged pull request:
https://github.com/wenzhixin/bootstrap-table/pull/1523

**Comment by hallard** [comment]
Will try this, thanks
