### ISSUE TITLE
Feature request : extending rowStyle to data

### ISSUE THREAD

**Issue by gdoumenc** [wenzhixin/bootstrap-table#1557]
I propose to extend rowStyle (add also cellStyle) to not only styles and classes but also data.

Something like :
    function rowStyle(row, index) {
    return {
        classes: 'test',
        data: {'test':'value', 'other':'value1'},
    };

I've made an example : http://jsfiddle.net/gdoumenc/4Lxcecgh/8/

**Comment by weibangtuo** [comment]
`rowStyle` support return classes and css. no support `data`. if you want to formatt data, please set `responseHandler` to table or set `formatter` to table column.

So, you code of `classes: "test"` is work. `data` no work.

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by wenzhixin** [comment]
Just like @weibangtuo said, `rowStyle` only support style feature, in your case you can use `rowAttributes` to do what you want.
