### ISSUE TITLE
bootstrap-table的跨域请求数据

### ISSUE THREAD

**Issue by xiaohan2013** [wenzhixin/bootstrap-table#1558]
当我用bootstrap-table的url从远程去取数据，但是跨域的情况会在
preflight Request的阶段没有起作用，一直在请求一直在pending的状态

**Comment by weibangtuo** [comment]
我们不解决跨域问题，请避免出现跨域问题。出现跨域问题是你们的网站架构出问题，Ajax是不允许跨域的，相关解决方案可在网上找到。
