### ISSUE TITLE
How use interpolate angularjs in column

### ISSUE THREAD

**Issue by rafaoli** [wenzhixin/bootstrap-table#1559]
Hi, I need set column label with angular interpolate.
I'am use angular translate, if use out of table it's works.

```
{{ 'DATE' | translate}} //works..

<table id="table" ng-init="initTable()" data-toggle="table" data-classes="table table-no-bordered"
				data-height="600" data-side-pagination="server" data-page-list="[5, 10, 20, 50, 100, 200]" data-pagination="true">
		<thead>
		        <tr>
				<th data-field="recorded_at_str" data-formatter="linkFormatter" data-align="center">{{ 'DATE' | translate}}</th>
					
			</tr>
		</thead>
</table>

```

**Comment by djhvscf** [comment]
Please provide an example @rafaoli

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
