### ISSUE TITLE
Modal/Scrollview Formatting Issue in Version 1.9.0

### ISSUE THREAD

**Issue by kanderson450** [wenzhixin/bootstrap-table#1562]
As an example I have a Modal which contains a Bootstrap Table & an Unordered List below the Table.

In Version 1.8.1 everything rendered appropriately but in Version 1.9.0 the Table and Unordered List are overlapping.

https://jsfiddle.net/44qu2yzr/

![1-9-0](https://cloud.githubusercontent.com/assets/7154425/10553505/1c2e7944-7410-11e5-8cb1-53eb7fe03641.PNG)

**Comment by kanderson450** [comment]
If you take a look at the jsfiddle that I posted above, you'll see the formatting issue.

**Comment by kanderson450** [comment]
The reason I upgraded to Version 1.9.0 was that I needed the method 'getRowByUniqueId'.  If I didn't need that I would just downgrade, but I cannot.

**Comment by wenzhixin** [comment]
In your case, you need to use the `resetView` method on `shown` event:
```js
$('#modalTable').on('shown.bs.modal', function () {
	$('#table').bootstrapTable('resetView');
});
```
https://jsfiddle.net/44qu2yzr/2/
