### ISSUE TITLE
Sorting by Date in Correct Format

### ISSUE THREAD

**Issue by ChaseGiunta** [wenzhixin/bootstrap-table#1563]
I just need to sort my table by the values in a date colume. Currently, I'm echoing the dates in `YYYY-MM-DD`, but I can echo the date values in whatever format needed, but ultimately want them displayed in `MM/DD/YYYY` or `M/D/YYYY` in Bootstrap Table. Is there a JSFiddle anywhere for how I would go about sorting dates in one of those two formats?

**Comment by ChaseGiunta** [comment]
So I ended up placing the `<span class="hidden">YYYY-MM-DD</span>` before echoing the desired format. Seems hacky but works. Curious as to what the correct way to do this is.

**Comment by kct3937** [comment]
Format the date field as you retrieve it from your table like this...$sql =
"SELECT id,DATE_FORMAT(Rec_Date, '%m/%d/%Y') as mdy_Date, etc...from
<tablename> where ...".  Rec_Date is the field in the table where the date
is stored in the normal mysql/oracle date format.  For presentation I
formatted it on the select and the sort works fine.  I used the name
mdy_Date to remind me what format I was going for.  The names are not
written in stone.

This technique works on all the platforms that I have used. Too many years
of sql programming.

**Comment by ChaseGiunta** [comment]
@kct3937 I don't believe you understood the question. I can output whatever format needed.

**Comment by tmorehouse** [comment]
By default, columns are sorted alphabetically.

You can specify a custom JavaScript sorter function for a column with your dates in it.

**Comment by ChaseGiunta** [comment]
@tmorehouse I appreciate the answer! Yeah I had seen the custom sort options. Unfortunately, I'm not fluent, by any means, in javascript. So I was hoping I would be able to stumble upon a snippet or JSFiddle of something as common as sorting by date.

**Comment by pavanbangaloreraju** [comment]
> So I ended up placing the `<span class="hidden">YYYY-MM-DD</span>` before echoing the desired format. Seems hacky but works. Curious as to what the correct way to do this is.

this didn't work for me
