### ISSUE TITLE
Cookie plugin incompatibility with data-sort-name

### ISSUE THREAD

**Issue by adrianmihalko** [wenzhixin/bootstrap-table#1564]
I set default sort order with data-sort-name and data-sort-order. After I enable cookie plugin the default state is ignored. The plugin itself works, because If I click on any sort option it is saves the state. But If no cookie = default sort order is ignored.

1, Default, no cookie plugin, sort by date
http://jsfiddle.net/s5u4Lqcb/

2, cookie plugin

http://jsfiddle.net/455dzyy5/

You can see that the little sort purple icon is not active anymore.

**Comment by wenzhixin** [comment]
Merged this to develop: https://github.com/wenzhixin/bootstrap-table/pull/1531
