### ISSUE TITLE
Button Styling, CSS modifications and hide a col from showColumn popup

### ISSUE THREAD

**Issue by vdcprivate** [wenzhixin/bootstrap-table#1566]
Hello,
first of all, thank you very much for this great work. It is awesome. 
I have a couple of questions for you.

1) How can I style default buttons as per the styles of my theme. Let's see the following example:

![Button styles](http://imageshack.com/a/img903/2291/xvMMKR.png)

I have a style in my theme named `btn-outline` and I would like to apply the same style to toolbar buttons. How can I apply this class to the button?

2) As you can see the button with text "Azioni" is a dropdown. With the defautl css the dropdown was showing inside the cell and activate the horizontal scrollbar. I have changed the css rule `fixed-table-body` by removing `overflow-x: auto;` and `overflow-y: auto;` and adding `overflow: visible !important;` instead. Do you think there is a better method?

3) As you may see in my table there's an action column. How can I hide the action column from the field list???

![Button styles](http://imageshack.com/a/img905/4306/x2oDtA.png)

Thanks a lot

**Comment by wenzhixin** [comment]
1. Maybe you can use the `iconSize` option, you can have a try: `data-icon-size="outline"`.
2. You can define a class to your field, for example: `th class="azioni"`, and then use the css rule: `azioni`.
3. There is an column option can help you:

Name | Attribute | Type | Default | Description
-------- | ----------- | ------- | ---------- | --------------
switchable | data-switchable | Boolean	true | False to disable the switchable of columns item.
