### ISSUE TITLE
queryParams sending null values

### ISSUE THREAD

**Issue by erick-chali** [wenzhixin/bootstrap-table#1569]
I'm creating my table like this:
`var tabla = $('<table id="tablaConteo2"></table>');`
`var thead = $('<thead></thead>');`
`var enc = $('<tr> <th></th> <th></th> <th></th> <th></th> <th></th> </tr>');`
`thead.appendTo(tabla);`
`enc.appendTo(thead);`
`tabla.appendTo('#tablaDatosToma2');`
`var $tabla = $('#tablaConteo2');`

    $tabla.bootstrapTable({

	   				height: 200,
	   				url: 'BuscarCodigo',
	   				method: 'post',
	   				queryParams: function(p){
	   					return{
	   						codigoProducto : $('#codigoToma2').val(),
		   					bodegaID: $('#bodega').val()
	   					};

	   				},
	   				pagination: true,
	   				pageSize: 50,
	   				pageList: [10, 25, 50, 100, 200],
	   				showRefresh: true,
	   			columns: [
	   			{
                    field: 'codigoProducto',
                    title: 'C\u00F3digo'
                }, 
                {
                    field: 'cantidad',
                    title: 'Cant. Actual',
                    width: '200px'
                },
                {
                    field: 'nuevaCantidad',
                    title: 'Cantidad'
                },
                {
                    field: 'bodega',
                    title: 'Bodega'
                },
                {
                    field: 'estanteria',
                    title: 'Estanter\u00EDa'
                },
                {
                    field: 'seccion',
                    title: 'Secci\u00F3n'
                },
                {
                    field: 'estanteriaID',
                    title: 'Estanter\u00EDa'
                },
                {
                    field: 'seccionID',
                    title: 'Secci\u00F3n'
                }
                ]
	   			});

and the two parameters are sent to a servlet, and usually I retrieve the parameters like this:

`request.getSession().setAttribute("codigoProducto", request.getParameter("codigoProducto"));`
`request.getSession().setAttribute("bodegaID", request.getParameter("bodegaID"));`
however when I try to use the parameters are null.

can anyone tell me why is sending null values

**Comment by weibangtuo** [comment]
`queryParams` function like this is better, object `p` has other data send to server. 
```
queryParams: function(p) {
  p.codigoProducto = $('#codigoToma2').val();
  p.bodegaID = $('#bodega').val()
  return p;
}
```
You issue:
`method: "post"` will send data on body like Restful, and `request.getParameter("bodegaID")` is request data from form. You can get params from request body, or you can set `contentType: "application/x-www-form-urlencoded"` to table conf than you can request params like `request.getParameter("key")`.

**Comment by erick-chali** [comment]
Thank you for the reply, now I get it.
