### ISSUE TITLE
Hide column in a Table with footer will not hide footer td

### ISSUE THREAD

**Issue by manju-reddys** [wenzhixin/bootstrap-table#157]
Hello,

When we hide the table column with footer will not hide the footer td. The header and body get shift to left or right but not the footer.

**Comment by kitarafrei** [comment]
Hi @manju-reddys would you mind sharing how did you do the footer with the sum of the numbers? Thanks!

**Comment by wenzhixin** [comment]
Docs: http://bootstrap-table.wenzhixin.net.cn/documentation/, example: http://jsfiddle.net/L6tm1tt3/

**Comment by manju-reddys** [comment]
Hi All,

Sorry for late response. Its pretty simple when you click on the show/hide column checkbox in the dropdown, get the index of li and hide the respective footer cell.

Thanks,
Manjunath Reddy

**Comment by kitarafrei** [comment]
Hi @wenzhixin ,
I added showFooter: true and on the column I added 

```
columns: [
			{
				field: 'id',
				title: 'Bill Number',
				sortable: true,
				class:	'clickableRow',
				footerFormatter: function (data) {
					return 'Total';
				}
			}
```

But nothing is showing....
Any ideas?

**Comment by kitarafrei** [comment]
@wenzhixin I have a table I'm trying to apply the footer, it works but the problem I have is that the table is showing on the column the format monetary number, like $1,203.00 and sometimes it has like this $1,203,00 ($903.00)

How can I sum it up in this case?

Thanks

**Comment by kitarafrei** [comment]
Hello, is there a way to return on the json feed what to show on the footer for that column?

**Comment by wenzhixin** [comment]
Can the `data-footer-formatter` option help @kitarafrei ?

**Comment by kitarafrei** [comment]
Hi, thanks for replying. I'm not sure, is there a way to just process what I want to have on the footer on the server side and send it through json like I do with the rows?

**Comment by wenzhixin** [comment]
I think now is does not support build the footer use json data from the server side. @kitarafrei

**Comment by kitarafrei** [comment]
@wenzhixin thanks I'll probably have to wait hopefully someone do that as an enhancement! Thanks!
