### ISSUE TITLE
[Bug] Search has unexpected behaviour when used with pagination

### ISSUE THREAD

**Issue by mwatz122** [wenzhixin/bootstrap-table#1574]
https://jsfiddle.net/mwatz122/hqz6p6r4/

When the number of search results matches the current page size, the page size is set to 'ALL'.

<b>Replication:</b>
1) Search 'Santa Barbara' (there should be 10 results which equals the default page size)
2) Clear the search
3) Now 16 records are shown even though the page size should not have been changed from 10

Now refresh the page and start over.

1) Search 'Seattle' (there should be 6 results which does not equal the default page size)
2) Clear the search
3) Now 10 records are correctly shown and the page size remains 10

This bug could be especially problematic if you have a very large number of records. For example, if the table contains 1,500 records with a page size of 25 and a search returns exactly 25 results, clearing the search will display all 1,500 records on the page at once!

**Comment by djhvscf** [comment]
This issue is fixed
