### ISSUE TITLE
Feature Request: UI Improvement for Export Plugin

### ISSUE THREAD

**Issue by dabros** [wenzhixin/bootstrap-table#1576]
Noticed this when looking at #1553, seperate issue so made this.

http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html

In the live example linked above, you do seem to need to select your export type twice if you change from 'export x' to 'export all'. 

But once your on 'export all' (and all rows shown) one click is enough. This is the case for all export types, and reselecting 'export all' also triggers download.

<br/>
This behaivour as i see it is not undesired per-say, but not obvious ui flow to have the dropdown the trigger button, and in same cases require you to 'reselect' after making changes. 

The way it works now is you select your options, and those options were changed (at least in the example above) then 'another' click and select (of already selected option) on either dropdown is required to trigger download.

<br/>
I guess a quirk of the current event handlers and ui that should be improved if possible. 

Perhaps a 'split' button, with an arrow selecting type and main button its attached to just triggering actual export, so its more obvious UI flow.

Though reworking handlers might be enough i feel a seperate button (with split so part of same button group) would be more logical UI.

**Comment by wenzhixin** [comment]
Fixed: https://github.com/wenzhixin/bootstrap-table-examples/commit/43ba9709f56b7de181fef8abc2e84472588485a0
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html
