### ISSUE TITLE
Enable search only on one column instead of all columns

### ISSUE THREAD

**Issue by ykiran** [wenzhixin/bootstrap-table#1579]
Hi,
  Is there any way I can enable the search input to use only one column instead of all columns?
  Currently, the search input searched all the columns.

Thanks,
Kiran.

**Comment by djhvscf** [comment]
You have to use the data-searchable column option in order to allow or don't allow the "search logic".. See this:  http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

**Comment by ykiran** [comment]
Thank you very much @djhvscf, somehow missed this.

Thanks,
Kiran.
