### ISSUE TITLE
Server side pagination Sorting & Searching Local

### ISSUE THREAD

**Issue by princenaman** [wenzhixin/bootstrap-table#1580]
I used the server side pagination,
But i need to implement the sort and search on the local data retrieved.
I.E. if i already have 10 rows from the server I should be able to search on that same data and even sort that data.

Please Help.

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/4r6g4cfu/3/light/

**Comment by princenaman** [comment]
That's what I have currently!
What I want is that the sorting and searching is done on the data currently in the table.

**Comment by dabros** [comment]
@princenaman - its a very simple choice you have to make, either you:

A. Use server side pagination and searching (the same thing, all query variables sent to server and results returned), or

B. Client side, you can still use ajaxOptions or similar to send some extra data with requests, but pagination and searching is performed client-side using the data returned from the request

By simple defination and practical reality these are not combinable - your searches need to happen at same point/side that pagination is, else its not a search, just a ctrl+f for visible content in page at best (and a broken feature by definition)

Pick an approach that makes sense for your situation, either custom searching & pagination on server side, or use client-side by loading the entire data request.

As i mentioned, it is possible to send some extra param with your initial data request even when using client side, but that is not pagination related or the contents of the standard search box. If using client side just keep it simple and only if absolutely needed use responseHandler and ajaxOptions to do some extra handling of the intital data request.

**Comment by princenaman** [comment]
Is there a way i override the search/ sort function?
so i create my own.

**Comment by dabros** [comment]
@princenaman - as was said, if you use server-side-pagination then your search is server-side, else use client side and see filter-control and similar plugins

Mix-and-match between sides issnt a thing, not least of all you only have a small subset returned to client so any search is inherently broken, it would only affect visibile content so just use ctrl+f or find plugin that mimics that.

**Comment by nyarachm** [comment]
@princenaman @djhvscf Hi, how do I store the table data server-side? I am only familiar with saving the data in a json file client-side.

**Comment by dabros** [comment]
@nyarachm - please contain this to #2105 which you opened, as not in the scope of OP in this thread.

**Comment by djhvscf** [comment]
@princenaman There is a `customSearch` and `customSort` function. 

See this:  https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L371 , 
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L373

**Comment by hadimajidi** [comment]
I love ctrl + f
