### ISSUE TITLE
bootstrap-table inside popover not working

### ISSUE THREAD

**Issue by havok2063** [wenzhixin/bootstrap-table#1582]
I'm trying to put a small scrollable bootstrap-table inside a button popover and I'm struggling to get it working and formatting correctly, even in the fiddle.   The table is a small two column table that will contain many code versions, so I would like it to be scrollable.  I'm setting the data-height but that is not working.  I can sort of get the styling of the table correct when placed inside a normal div, but once I put it inside the data-content section of my popover, the entire thing renders horribly.  What am I missing here?

Here is my fiddle
https://jsfiddle.net/d63emLsh/1/

Note:  In my real code, I've defined a jinja2 macro called versiontable that gets piped into the data-content like so

    <button type="button" id='verspopover' data-trigger='hover' class="btn btn-primary" data-toggle="popover" title="Versions" data-content="{{versiontable(session['codeversions'])}}">Code Versions</button>

but I can't get that working inside the jsfiddle.  Plus the affect is the same.  

My defined macro is

    {% macro versiontable(versions) %}

	<div id='versiontable' class='table-responsive'>
		<table class='sastable' data-toggle='table' data-classes='table table-condensed table-bordered table-striped' 
			data-height='200' name='versiontable'>

			<thead id='head'><tr><th>Code</th><th>Version</th></tr></thead>
			<tbody>
				{% for version in versions %}
					<tr><td>{{version['name']}}</td><td>{{version['version']}}</td></tr>
				{% endfor %}			
			</tbody>
		</table>
	</div>

    {% endmacro %}

Thanks for any help.

**Comment by wenzhixin** [comment]
In your case, you need to bootstrap the table manually: https://jsfiddle.net/d63emLsh/3/.
