### ISSUE TITLE
有没有方法或者参数能够是表格的table header和body在改变显示百分比的时候保持对齐？

### ISSUE THREAD

**Issue by joostshao** [wenzhixin/bootstrap-table#1585]
我是用js做的，不知道是不是参数有问题，但是我文档查了也没找到，只找到你的一篇文章。

http://wenzhixin.net.cn/2014/08/10/fixed_table

先上图：

![1](https://cloud.githubusercontent.com/assets/3615951/10634723/517916e4-7826-11e5-8256-db4655492437.png)

但是放大之后就变成了如下：
![2](https://cloud.githubusercontent.com/assets/3615951/10634731/5e5fd744-7826-11e5-8f5a-c2e785471ede.png)

by the way, 我也用过easyui的grid，但是他的table header是不受影响的。

求助，希望给位能帮我

**Comment by weibangtuo** [comment]
使用resetView方法，表格内容变更后，或window resize时候，表格需要重新渲染，调用 `$("#table").bootrapTable("resetView");` 方法重新调整表格。

**Comment by joostshao** [comment]
屌

**Comment by cleverchao** [comment]
@weibangtuo very helpful

**Comment by wenzhixin** [comment]
adjust the header in the latest version
