### ISSUE TITLE
Meteor, AngularJS and Bootstrap-table not working for me

### ISSUE THREAD

**Issue by mryraghi** [wenzhixin/bootstrap-table#1586]
I don't know what I'm doing wrong in such simple steps but Bootstrap-table doesn't work in my website developed with Meteor and AngularJS.

Does somebody have any suggestion?

Thanks

**Comment by wenzhixin** [comment]
Can you provide more information to show the problem?

**Comment by mryraghi** [comment]
I've simply included bootstrap-table.js, bootstrap-table.css and bootstrap-table-en-US.js in my project. Since Meteor automatically merges and includes every js and css file I don't need to include them with a tag in any html file. I have of course jQuery and Bootstrap already included. Then, if I try to copy a simple table somewhere in my project, it will not be rendered. Bootstrap-table seems amazing so I'd really like to implement it. Do you have any hints?

**Comment by mryraghi** [comment]
<img width="1211" alt="screen shot 2015-10-23 at 14 53 40" src="https://cloud.githubusercontent.com/assets/5071701/10702175/05334ba8-7996-11e5-8088-2eb715f996d8.png">
 Take a look at the right side of the screenshot. Is it normal that all that code seems to be commented?

**Comment by wenzhixin** [comment]
Have you used the code in your template?
```js
Template.name.onRendered(function () {
    $('[data-toggole="table"]').bootstrapTable();
});
```

**Comment by wenzhixin** [comment]
close this issue because there is no any response in 7 days: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels
