### ISSUE TITLE
*Bug?* Advanced Search Extension Doesn't Update with Hidden/Shown Columns

### ISSUE THREAD

**Issue by sbenders-abbyy** [wenzhixin/bootstrap-table#1587]
Adding on to : https://github.com/wenzhixin/bootstrap-table/issues/1532 & https://github.com/wenzhixin/bootstrap-table/issues/1584

The Advanced Search Extension seems to only allow Advanced Searching of the initially visible table columns.
If you change the visible columns, the Advanced Search still only lists the initially available columns. It still seems to function correctly, even if the columns are not visible.

In the screenshot below, I have hidden all but two columns, however, the Advanced Search still has input boxes for all the columns that were initially visible:

![image](https://cloud.githubusercontent.com/assets/9826982/10652840/a248ccc6-780e-11e5-85db-408516c0c05e.png)

**Comment by djhvscf** [comment]
See #1979
