### ISSUE TITLE
*Feature* Pagination info should be configurable

### ISSUE THREAD

**Issue by averatec** [wenzhixin/bootstrap-table#1589]
Pagination info should be configurable.
``Showing n to m of k rows)``
That's all. Thanks.

**Comment by dabros** [comment]
@averatec - read the doco, already there under 'localisations': http://bootstrap-table.wenzhixin.net.cn/documentation/

Also do a ctrl+f search in that page for 'pag' and see other page&pagination related options.

**Comment by wenzhixin** [comment]
Just like @dabros said, you can use this function:
```
$table.bootstrapTable({
    formatShowingRows: function (pageFrom, pageTo, totalRows) {
        return ...;
    }
});
```
