### ISSUE TITLE
Column headers misaligned on window or Bootstrap resize

### ISSUE THREAD

**Issue by rfossella** [wenzhixin/bootstrap-table#1590]
Hi.  This issue touches on issue #618 which was closed although the problem exists.  Can #618 be re-opened or should I duplicate issue here?

**Comment by wenzhixin** [comment]
Please provide a jsFiddle?

**Comment by rfossella** [comment]
Is there any way you can decipher the issue with all the details I included in ticket #618?  While I can reproduce it very readily, I'm honestly not sure how to reproduce this scenario with a simple fiddle.  Guidance?

**Comment by erick-chali** [comment]
This help me to sole a similar issue, check out reserView, maybe that is goong to fix it.
http://bootstrap-table.wenzhixin.net.cn/faq/

**Comment by wenzhixin** [comment]
Just like what @erick-chali said.

**Comment by rfossella** [comment]
I assume you mean erick's comment stating, "Try to place the table inside a div with class="table-responsive" or class="container", that helped me to fix the issue."  Because I already do resetView on window resize - again, the issue is when hiding/showing elements that are adjacent to bootstrap-table - window resize not fired.  Is that correct?

**Comment by wenzhixin** [comment]
Yes, in that case resize not fired.

**Comment by rfossella** [comment]
Unfortunately the recommendations of Erick still do not resolve the issue.  I am at a loss for how to resolve this issue as it occurs all the time.  I've attached news pics.

**BEFORE**
![image](https://cloud.githubusercontent.com/assets/1350182/10746317/ecc50caa-7c1f-11e5-90b0-160b02999e9a.png)

**AFTER**
![image](https://cloud.githubusercontent.com/assets/1350182/10746325/fba06ac6-7c1f-11e5-9271-6e75303d84e5.png)

**Comment by erick-chali** [comment]
$( "#yourMenu" ).toggle( "slow", function() {
        $('#tableId').bootstrapTable('resetView');
      });
how about something like this, fire the event when you finish the "toggle" action.

**Comment by rfossella** [comment]
Erick,thanks for your response. Your tip is useful in the case where I set up an explicit toggle as you describe. However, my issue seems to stem from CSS **media queries** that are used within bootstrap. I.e. The hiding of the sidebar in my example happens via media query when window size < 1200. It seems the window resize event occurs first, which I trap and do bootstraptable('resetView'), but (seemingly) immediately after that, another event occurs that hides the sidebar and bootstraptable has misalignment of columns. 

I hope my explanation makes sense. Still trying to get a fiddle together to express issue further. 

 Any more info is appreciated.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports) to your problem, for example like this: http://jsfiddle.net/wenyi/e3nk137y/13/show/

**Comment by hdrodriguez** [comment]
Hello, someone knew how to solve this problem

**Comment by kwagdy** [comment]
This indeed is a persisting issue till today!

**Comment by pchaganti** [comment]
👍
