### ISSUE TITLE
Not able to sort and get sort icon from javascript

### ISSUE THREAD

**Issue by vikashpar** [wenzhixin/bootstrap-table#1591]
Hi,

I have used your plugin and its great. :)

I would like to sort from the javascript and henceforth sort from html through sort icon, but I am finding it difficult. Here is the jsFiddle for your reference (https://jsfiddle.net/vparijat/b5tza2qa/)

Please help me with this.

**Comment by wenzhixin** [comment]
You are using in a wrong way: https://jsfiddle.net/b5tza2qa/1/

**Comment by vikashpar** [comment]
Thanks a lot, it works like a charm now :)

Thanks and regards,
Vikash Parijat.
Mobile No.: +919560907741
