### ISSUE TITLE
How to change click-through order from both/desc/asc to both/asc/desc?

### ISSUE THREAD

**Issue by psisafilin** [wenzhixin/bootstrap-table#1594]
Recently noticed, that there is no way to change the order of the sort option after a click on the sort widget on the table. It always sets desc sorting on the field with "_both_" class. Looking for an option to change that behavior to "_both/asc/desc_".
**PS:** tried column option "order" (_data-order_) - no change.

**Comment by wenzhixin** [comment]
Sorry, I am not quite understand what you mean.

**Comment by psisafilin** [comment]
@wenzhixin, when You first time click on a TH field to sort - it sorts by "DESC" by default. I've found the option for columns (data-order), when I set it equal "desc" - It works almost fine. It doesn't - when You do next sorting on other field and sort again on the first field - it sorts the field by "DESC".
The goal - each initial sorting on a field should done by "ASC"

**Comment by psisafilin** [comment]
Have found workaround - own override of **onSort** method
```
$.fn.bootstrapTable.Constructor.prototype.onSort
```
In which, I've used the old code with some additions. Added two variables:
```
$thisIndex = $this.index(),
$thisColOptions = this.options.columns[0][$thisIndex];
```
Updated the section with **sortName** and **sortOrder** change
```
if (this.options.sortName === $this.data('field')) {
  this.options.sortOrder = this.options.sortOrder === 'asc' ? 'desc' : 'asc';
} else {
  this.options.sortName = $this.data('field');

  if (!isNaN($thisIndex) && $thisColOptions.hasOwnProperty('order')) {
    this.options.sortOrder = $thisColOptions.order === 'asc' ? 'desc' : 'asc';
  } else {
    this.options.sortOrder = $this.data('order') === 'asc' ? 'desc' : 'asc';
  }
}
```
I know it is not a perfect solution for my goal, but if it fits my needs.
If anyone knows a better solution for my goal - please advise.

**Comment by djhvscf** [comment]
Duplicate #2864
