### ISSUE TITLE
sortName not recognized for server-side sorting

### ISSUE THREAD

**Issue by bjoernhaeuser** [wenzhixin/bootstrap-table#1598]
Hey there,

thank you for making bootstrap-table :) I really like it.

I am currently having problems with server-side sorting. I defined the column-option "sort-name", but still the field-name is transmitted to the server.

I tried to look into it, and don't know what the easiest fix would be:
- Changing the option.sortName everywhere would mean that the fieldName / sortName needs to be distinguished everywhere
- Only changing the fieldName into sortName in the `initServer` method seems to be the better way, but I don't know how I could get the column-options for the column besides iterating through every column

Thanks
Björn

**Comment by wenzhixin** [comment]
I think you can use the `queryParams` option to solve your problem, for example:
```js
queryParams: function (params) {
    params.sort = {
        field1: 'sortName1',
        field2: 'sortName2',
    };
}
```

**Comment by bjoernhaeuser** [comment]
@wenzhixin Hm, but that would mean that I use `sort-name` incorrectly? Or is this a bug? :)

**Comment by nyarachm** [comment]
@bjoernhaeuser any luck getting the sort feature to work server-side?

**Comment by dabros** [comment]
@nyarachm - please delete your post here and contain this question to #2105 which you opened, as not in the scope of OP in this thread, and spamming same question in unrelated posts confuses issues.

This thread is about sorting, see my post in #2105 which answers you core issue

**Comment by hozn** [comment]
Was there any resolution on this?  I think I am experiencing the same issue.  I can hack around it in queryParams, but it seems to be a bug.

**Comment by bjoernhaeuser** [comment]
No progress, therefore closing it :) it's probably anyway outdated

**Comment by hozn** [comment]
Wait, why was this closed?  It's still a bug.

**Comment by bjoernhaeuser** [comment]
@hozn because nothing happend in two years :/

**Comment by hozn** [comment]
Well, maybe someone can fix it? :-) The bug is still a bug, so should
someone open another ticket or just leave this one open since it isn't
fixed?

**Comment by dabros** [comment]
@wenzhixin 
@djhvscf 
Can we please clarify if this has been solved, a workaround exists or pending bug
