### ISSUE TITLE
Empty array reference

### ISSUE THREAD

**Issue by iboylmz** [wenzhixin/bootstrap-table#1600]
// if options.data is setting, do not process tbody data
        if (this.options.data.length) {
            return;
        }

This line of code is causing the lost reference when i want to assing an empty array to data programmatically.
And solution is:

        // if options.data is setting, do not process tbody data
        if (this.options.data) { // return if this.options.data an empty array to. (not dependent on length)
            return;
        }

**Comment by iboylmz** [comment]
http://jsfiddle.net/iboylmz/57yfwat9/

vs

http://jsfiddle.net/iboylmz/15xwnq5y/

**Comment by djhvscf** [comment]
I like this solution.. But can you open a new PR against develop branch? @iboylmz

**Comment by wenzhixin** [comment]
Merged
