### ISSUE TITLE
Expanded row is collapsing after row update

### ISSUE THREAD

**Issue by Avivbh** [wenzhixin/bootstrap-table#1603]
When using updateByUniqueId (and maybe also when using updateRow, didn't check it) the row that is being updated is collapsing.
I don't know if you consider this an unwanted behavior, but in my case it isn't.
To locally fix it I added expandRow_ call in the end of updateByUniqueId method (marked row in picture).
![capture](https://cloud.githubusercontent.com/assets/15223524/10736136/0a4668a2-7c14-11e5-837d-5d81c8c7e965.PNG)

Don't know if you consider this to be a bug/issue, just putting it up there for you to know :)

**Comment by djhvscf** [comment]
Can you provide a fiddle?? @Avivbh

**Comment by wenzhixin** [comment]
#1498
