### ISSUE TITLE
BootstrapTable.prototype.onColumnSearch makes 3 requests

### ISSUE THREAD

**Issue by pilb** [wenzhixin/bootstrap-table#1605]
Hi,

Using bootstrap-table-filter-control.js, on server side, 3 requests were sent to server.

Thanks.

**Comment by dabros** [comment]
@pilb - more detail please

Ideally include all relevant header and response info from each, or at least url and summary of it so we see what they were

Also please include copy of your html and js related to this plugin

thanks

**Comment by pilb** [comment]
Please find example here : https://jsfiddle.net/gr24ouqo/4/.

Try to enter text into column filter and you will see 3 requests on network. 

```js
BootstrapTable.prototype.onColumnSearch = function (event) {
        copyValues(this);
        var text = $.trim($(event.currentTarget).val());
        var $field = $(event.currentTarget).parent().parent().parent().data('field')

        if ($.isEmptyObject(this.filterColumnsPartial)) {
            this.filterColumnsPartial = {};
        }
        if (text) {
            this.filterColumnsPartial[$field] = text;
        } else {
            delete this.filterColumnsPartial[$field];
        }

        this.options.pageNumber = 1;
        this.onSearch(event); // First Request
        this.updatePagination(); // Second Request
        this.trigger('column-search', $field, text); // Third Request
    };
```
Thanks,

Pilb

**Comment by dabros** [comment]
No time to chase up further atm, but it appears to make as many duplicate requests as there are columns, even if filter attribute not set on some.

**Comment by dabros** [comment]
mayble related: #1501

**Comment by javieralfaya** [comment]
Hi Dennis,
You have closed this issue and related issue 1501, but ¿It has created a patch for this problem?.
Best regards.

**Comment by djhvscf** [comment]
Until now this issue is opened because we don't have any patch for it.. If you have one please open a new PR @javieralfaya

**Comment by javieralfaya** [comment]
Hi Dennis, this is may patch: 

Table filter control when pagination on server submit response twice, i commented this.update Pagination(); into bootstrap-table-filter-control.js and problem is resolved:

BootstrapTable.prototype.onColumnSearch = function (event) {
    copyValues(this);
    var text = $.trim($(event.currentTarget).val());
    var $field = $(event.currentTarget).parent().parent().parent().data('field')

    if ($.isEmptyObject(this.filterColumnsPartial)) {
        this.filterColumnsPartial = {};
    }
    if (text) {
        this.filterColumnsPartial[$field] = text;
    } else {
        delete this.filterColumnsPartial[$field];
    }

    this.options.pageNumber = 1;
    this.onSearch(event);

    //this.updatePagination();
    this.trigger('column-search', $field, text);
};

**Comment by djhvscf** [comment]
Great! Then open a new PR please, @javieralfaya

**Comment by dabros** [comment]
@javieralfaya - **PR** are always welcome

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

**Comment by rakmovistara** [comment]
still facing this problem. i am using 1.10.1

**Comment by wenzhixin** [comment]
Please update to 1.11.0

**Comment by jmm13** [comment]
Still does it in version: 1.12.1
