### ISSUE TITLE
Extensions list

### ISSUE THREAD

**Issue by wenzhixin** [wenzhixin/bootstrap-table#1606]
- [editable](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/editable/extension.json)
- [export](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/export/extension.json)
- [accent-neutralise](https://github.com/wenzhixin/bootstrap-table/raw/develop/src/extensions/accent-neutralise/extension.json)
- [cookie](https://github.com/wenzhixin/bootstrap-table/raw/develop/src/extensions/cookie/extension.json)
- [contextmenu](https://github.com/prograhammer/bootstrap-table-contextmenu/blob/master/extension.json)
- [filter-control](https://github.com/wenzhixin/bootstrap-table/raw/develop/src/extensions/filter-control/extension.json)
- [filter](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/filter/extension.json)
- [flat-json](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/flat-json/extension.json)
- [group-by](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/group-by/extension.json)
- [group-by-v2](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/group-by-v2/extension.json)
- [key-events](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/key-events/extension.json)
- [mobile](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/mobile/extension.json)
- [multiple-search](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/multiple-search/extension.json)
- [multiple-sort](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/multiple-sort/extension.json)
- [natural-sorting](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/natural-sorting/extension.json)
- [reorder-columns](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/reorder-columns/extension.json)
- [reorder-rows](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/reorder-rows/extension.json)
- [resizable](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/resizable/extension.json)
- [sticky-header](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/sticky-header/extension.json)
- [toolbar](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/toolbar/extension.json)

**Comment by wenzhixin** [comment]
Extension features:
* #256
* #1269

**Comment by pilb** [comment]
Hi,

Do you have an idea of what time will be required to implement #256?

Thanks,

Pilb
