### ISSUE TITLE
getData wrong result during initial onPostBody

### ISSUE THREAD

**Issue by step307** [wenzhixin/bootstrap-table#1607]
I retrieve $('#table').bootstrapTable('getData') inside of onPostBody event.

When it is fired 1st time (on initial render) I receive an HTML element (the table)

But, e.g. when it is fired after $('#table').bootstrapTable('updateRow') I get actual table data as expected.

It also works properly when I access the data by a button click

Fiddle : http://jsfiddle.net/7pnmv4mz/2/

Update: mergeCells also doesn't really work. I suppose, that the event is fired before the plugin is initialized completely.

**Comment by thornomad** [comment]
With this pull #2012 the `data` variable was added to the post-body trigger ... which should resolve this issue.  check it out using develop:

http://jsfiddle.net/thornomad/g8Laun6L/2/

**Comment by marcovzla** [comment]
I have a similar issue, except that I need to retrieve the page in `onPostBody`
and `$('#table').bootstrapTable('getData', true)` returns an html element.

**Comment by thornomad** [comment]
```
function onPostBody(data) {
   // data should be loaded for you here
}
```

If you are accessing `data` in `onPostBody` it is the first argument passed to the function. Hope this helps.

**Comment by marcovzla** [comment]
I tried that but `data` contains all the data and I need the current page only.
Basically, `data` is equivalent to `$('#table').bootstrapTable('getData')`
but I need `$('#table').bootstrapTable('getData', true)`
