### ISSUE TITLE
Export file with filter control select activate

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#1612]
Hi,

If you hace the filter control with select option into a column and you want to export the table to file.
It will return all the option list into the header of the column into the file you have exported.
You can see an example here:
https://jsfiddle.net/1xvbcefc/1/

I've report it the tableExport developer to have the posibility to exclude some class selector.
You can see the conversation here:
https://github.com/hhurz/tableExport.jquery.plugin/issues/44

But the solution return me an error with jQuery 2-1-4.

**Comment by dabros** [comment]
similar? #1551

**Comment by manukieli** [comment]
Thanks for your suggestion, but is not the same issue.

**Comment by dabros** [comment]
@manukieli  - looked at this again and still not sure whats wrong exactly

The latest fiddle in that second link discussion shows export working fine for me, no header issues either...

If there is a js error, then setup a fiddle to make it appear, and include details on how to replicate and what the message says.

Cant help you if to me its not broken.

**Comment by manukieli** [comment]
You can see my issue here: https://jsfiddle.net/1xvbcefc/1/
See the export header into excel file exported.
The issue can be solved with this: https://github.com/hhurz/tableExport.jquery.plugin/issues/44#issuecomment-152225319

But now I've another issue if they are blank cell, see an example here: http://jsfiddle.net/g9kksddk/14/

Thank you very much.

**Comment by dabros** [comment]
@manukieli - thats a nothing issue, just check for empty columns before trying to iterate through the value.

Not entirely sure what that function is doing, never used export, but this seems to fix it for me (exports fine no js error, empty columns stay empty but you could easily define placeholder with an 'else' statement)

```javascript
function DoOnCellHtmlData(cell, row, col, data) {
    var result = "";

    // NOTE - simple comparison, I make no absolute guarantee this sufficient for 'all' use cases
    if(data == "" || data === "undefined")
    {
    	var html = $.parseHTML(data);
        
        $.each( html, function() {
            if ( typeof $(this).html() === 'undefined' )
                result += $(this).text();
            else if ( typeof $(this).attr('class') === 'undefined' || $(this).hasClass('th-inner') === true )
                result += $(this).html();
        });
    }
    return result;
}
```

**Comment by manukieli** [comment]
Thank you for your help.
Your code is a good solution. :+1: :+1: :+1:

**Comment by wenzhixin** [comment]
Great, @dabros

**Comment by hhurz** [comment]
To whom it may concern: dabros comment about manukieli's version of the DoOnCellHtmlData  function from above is right. It contains a wrong if condition to test for an empty or invalid cell text. The function should look like this:

```javascript
function DoOnCellHtmlData(cell, row, col, data) {
    var result = "";

    if(typeof data !== 'undefined' && data != "")
    {
        var html = $.parseHTML(data);

        $.each( html, function() {
            if ( typeof $(this).html() === 'undefined' )
                result += $(this).text();
            else if ( typeof $(this).attr('class') === 'undefined' || $(this).hasClass('th-inner') === true )
                result += $(this).html();
        });
    }
    return result;
}
```

**Comment by dabros** [comment]
@hhurz - thanks for the spot, the `typeof` condition does read as a typo to me now too, so made comment pointing to your post.
