### ISSUE TITLE
Formatting pagination to title `page-last` with the total number of pages

### ISSUE THREAD

**Issue by u01jmg3** [wenzhixin/bootstrap-table#1614]
Is there anyway to format the pagination and add a `title` attribute to the `page-last` button indicating the total number of pages?

Without going to the last page there is no way of knowing the total number of pages which some users might want to know when browsing a paginated table.

**Comment by dabros** [comment]
@u01jmg3 - no, there is a very totals count

"Showing 1 to 10 of x rows"

Example: http://issues.wenzhixin.net.cn/bootstrap-table/

You can also toggle pagination options using http://issues.wenzhixin.net.cn/bootstrap-table/#options/boolean-options.html

If you did want add titles yourself, i suggest using callback like OnPostBody or similar (see that first example i shared and find best event being logged there, all base callbacks logged in console there) then find the $('.bootstrap-table .pagination') or similar, and add titles using the bootstrap table 'getOptions' method (again see examples and doco).

Its doubtful this will make it into a core feature unless you create a pull request (shouldnt be hard, just look for init_pagination or similar in bootstrap-table.js) after forking this repo yourself, but callbacks are always there.

**Comment by u01jmg3** [comment]
PR submitted (#1620)

**Comment by wenzhixin** [comment]
Merged.
