### ISSUE TITLE
Sub-Table checkbox selects all the table

### ISSUE THREAD

**Issue by GabrielUlici** [wenzhixin/bootstrap-table#1619]
Hi,

So i have a table and when i click on the name column it opens a sub-table and when i click on the main checkbox of the sub-table instead of selecting only the rows in the sub-table it selects all the rows in the sub-table and the main table.

It is possible to have the normal behaviour?

https://jsfiddle.net/gabe_green/q3xce1y1/1/

**Comment by djhvscf** [comment]
Ok, I think this is an issue because the checkbox should work only per table/subtable

**Comment by GabrielUlici** [comment]
there exist a way to overwrite the normal behaviour?

**Comment by GabrielUlici** [comment]
can i get some help to know exactly where the calls for the btSelectAll is?
because i searched in the code and the thing that i found is that the code from 793-798 it is called two times. but i cannot figure out why.

**Comment by GabrielUlici** [comment]
so at the end i figure it out and i even solved it.

**Comment by wenzhixin** [comment]
Merged, thanks.
