### ISSUE TITLE
custom tr id is required

### ISSUE THREAD

**Issue by manju-reddys** [wenzhixin/bootstrap-table#162]
We must allow user to chose their own ids to use in TR. Its not always the case to use the json to build the table but we can use this plugin on the existing tables.

In my case I need to build a tree table and I use the TR ids to insert or remove the child TR's without the custom ID's we can't have this working.

Possible solution is to capture the tr attributes and use while initBody process.

**Comment by djhvscf** [comment]
You can close this issue @wenzhixin

**Comment by wenzhixin** [comment]
Closed
