### ISSUE TITLE
自定义按钮问题

### ISSUE THREAD

**Issue by AhaSleeper** [wenzhixin/bootstrap-table#1622]
请问作者，目前这个组件支持在table上面自定义按钮吗？

**Comment by wenzhixin** [comment]
可以，你可以看例子

**Comment by AhaSleeper** [comment]
可以给我一个 链接吗？我今天研究一天了都还没找到，是toolbar那个吗？

**Comment by AhaSleeper** [comment]
谢谢！ 我已经找到，http://bootstrap-table.wenzhixin.net.cn/examples/#toolbar-custom-toolbar
