### ISSUE TITLE
issue with data-filter-control="true"

### ISSUE THREAD

**Issue by grillazz** [wenzhixin/bootstrap-table#1623]
Hey,

When added and data-filter-control="true" have below error when trying to select velue from filert:
reflow: 0.65ms function jQuery.event.fix, jquery.js line 4569
TypeError: thisColumn is undefined

Thansk,

J

**Comment by wenzhixin** [comment]
Can you provide a jsfiddle?

**Comment by grillazz** [comment]
Hi,

Sorry for delay but I had outstanding issues on my list with higher priority.
So... this problem exist only for table with static data (in my case generated by django template)

When I tested with data loaded via REST API everything was fine.

So not sure if this is enough to close this issue or try to fix it.

Thanks,

Jakub

**Comment by wenzhixin** [comment]
close this issue, BTW, any pull request is welcome.
