### ISSUE TITLE
DATE SORT ERROR

### ISSUE THREAD

**Issue by serlogo53** [wenzhixin/bootstrap-table#1628]
i am taking json data. sort is problem.
is anyone help me?

01.11.2015 02:53
01.11.2015 09:15
02.11.2015 01:39
02.11.2015 03:36
02.11.2015 06:52
02.11.2015 07:46
02.11.2015 08:17
02.11.2015 08:19
02.11.2015 08:51
02.11.2015 08:17
02.11.2015 09:12
02.11.2015 09:25
02.11.2015 09:49
02.11.2015 01:39
02.11.2015 10:10
02.11.2015 10:13
02.11.2015 10:17
02.11.2015 11:02
02.11.2015 11:28
02.11.2015 11:30
31.10.2015 05:35
31.10.2015 11:42
31.10.2015 13:41
31.10.2015 18:40
31.10.2015 21:57
31.10.2015 23:57
01.11.2015 03:43
01.11.2015 07:17
01.11.2015 07:26
01.11.2015 07:28
01.11.2015 08:31
01.11.2015 08:31
01.11.2015 08:36
01.11.2015 08:41
01.11.2015 08:41
01.11.2015 08:41
01.11.2015 08:42
01.11.2015 08:43
01.11.2015 08:50
01.11.2015 08:52
01.11.2015 09:03
01.11.2015 09:12
01.11.2015 09:16
01.11.2015 09:21
01.11.2015 09:40
01.11.2015 09:41
01.11.2015 09:53
01.11.2015 10:33
01.11.2015 10:44
01.11.2015 10:47
01.11.2015 10:54
01.11.2015 10:57
01.11.2015 11:01
01.11.2015 11:39
01.11.2015 11:43
01.11.2015 11:47
01.11.2015 12:13
01.11.2015 12:14
01.11.2015 12:42
01.11.2015 12:45
01.11.2015 13:17
01.11.2015 13:22
01.11.2015 15:00
01.11.2015 15:13
01.11.2015 15:29
01.11.2015 15:48
01.11.2015 16:10
01.11.2015 18:03
01.11.2015 18:34
01.11.2015 19:56
01.11.2015 22:15
30.10.2015 12:08
28.10.2015 12:14
30.10.2015 16:17
28.10.2015 13:06
28.10.2015 13:06
30.10.2015 20:26
30.10.2015 21:54
30.10.2015 23:40
31.10.2015 01:44
31.10.2015 02:51
31.10.2015 03:09
31.10.2015 05:58
31.10.2015 06:38
31.10.2015 07:03
31.10.2015 07:10
31.10.2015 07:11
31.10.2015 07:29
31.10.2015 07:30
28.10.2015 15:06
31.10.2015 07:42
26.10.2015 16:24
31.10.2015 07:47
31.10.2015 07:47
31.10.2015 07:53
31.10.2015 08:01
31.10.2015 08:05
31.10.2015 08:30
28.10.2015 15:58
31.10.2015 08:35
31.10.2015 08:35
31.10.2015 08:37
31.10.2015 08:37
31.10.2015 08:38
31.10.2015 08:38
31.10.2015 08:38
31.10.2015 08:38
31.10.2015 02:51
31.10.2015 08:42
31.10.2015 08:45
31.10.2015 08:49
31.10.2015 08:49
31.10.2015 08:49
31.10.2015 08:52
31.10.2015 08:53
31.10.2015 08:54
31.10.2015 08:54
31.10.2015 08:54
31.10.2015 08:56
31.10.2015 08:59
31.10.2015 09:02
31.10.2015 09:04
31.10.2015 09:04
31.10.2015 09:14
31.10.2015 09:15
31.10.2015 09:15
31.10.2015 09:23
31.10.2015 09:25
31.10.2015 09:32
31.10.2015 09:43
31.10.2015 09:44
31.10.2015 09:54
31.10.2015 09:54
31.10.2015 10:00
31.10.2015 10:06
31.10.2015 10:12
31.10.2015 10:26
31.10.2015 10:32
31.10.2015 10:36
31.10.2015 10:37
31.10.2015 10:43
31.10.2015 10:59
31.10.2015 11:11
31.10.2015 11:12
31.10.2015 11:21
31.10.2015 11:22
31.10.2015 11:23
31.10.2015 11:26
31.10.2015 11:33
31.10.2015 11:37
31.10.2015 11:38
31.10.2015 11:54
31.10.2015 12:00
31.10.2015 12:00
31.10.2015 12:20
31.10.2015 12:57
31.10.2015 13:03
31.10.2015 13:24
31.10.2015 14:11
31.10.2015 14:20
31.10.2015 14:23
31.10.2015 14:34
31.10.2015 14:56
31.10.2015 14:57
31.10.2015 15:00
29.10.2015 15:02
31.10.2015 15:42
31.10.2015 15:43
31.10.2015 16:09
31.10.2015 16:32
31.10.2015 16:32
31.10.2015 16:39
31.10.2015 17:17
31.10.2015 17:48
31.10.2015 18:35
31.10.2015 18:47
31.10.2015 20:47
31.10.2015 21:23
22.10.2015 18:38
29.10.2015 15:02
27.10.2015 22:53
30.10.2015 10:24
30.10.2015 10:45
30.10.2015 10:49
30.10.2015 03:10
30.10.2015 11:20
30.10.2015 09:57
30.10.2015 11:24
30.10.2015 11:28
30.10.2015 11:34
30.10.2015 11:35
30.10.2015 11:46
30.10.2015 11:47
30.10.2015 11:51
30.10.2015 11:51
30.10.2015 11:51
30.10.2015 12:07
30.10.2015 12:19
30.10.2015 12:27

**Comment by serlogo53** [comment]
hi again. now i found a way but long. :)
we need to convert date format to us standart.
i used split for this. and it was ok. we are waiting the basic way from masters..



bol=a.split(".");
bol1=bol[2].split(" ");
ta=bol1[0]+'-'+bol[1]+'-'+bol[0]+' '+bol1[1] ;

bol=b.split(".");
bol1=bol[2].split(" ");
tb=bol1[0]+'-'+bol[1]+'-'+bol[0]+' '+bol1[1] ;
 
        if (ta > tb) return 1;
        if (ta < tb) return -1;
 
        return 0;
    }

**Comment by dabros** [comment]
@serlogo53 - just google for 'datetime sorting' and add whatever language (php, mysql, ect) that is creating or returning those dates.

Basically, you shouldnt ever store dates in that format, i live in Australia and i do prefer that as common display form, but you gota save it (or at least return it) as "Y-m-d H:i:s" or similar if you ever want to sort it later, so pretty much all the time.

There are copious numbers of stackoverflow and similar articles out there bout this, should be easy to find better solution to fix your server code, or database code, or (only if absolute needed) use javascript to fix format (inside responseHandler function option, see doco and http://issues.wenzhixin.net.cn/bootstrap-table/)

**Comment by serlogo53** [comment]
i also done it. i explained. i am storing lik y-m-d h:i. but i need to see like d-m-y h:i. i think nothing easy way.. thanks.
