### ISSUE TITLE
Table export including caption tag

### ISSUE THREAD

**Issue by Angelo85** [wenzhixin/bootstrap-table#1630]
My tables have caption tag. When I export to Excel or PDF, the caption tag is missing.

**Comment by dabros** [comment]
@Angelo85 - for those of us a little unsure what that means, please include screenshots or similar (dropbox, ect) of both your table and the exported file, and a description where you expected caption to be in the export.

**Comment by Angelo85** [comment]
hi, https://jsfiddle.net/4arh0hsv/
thanks

**Comment by dabros** [comment]
@Angelo85 - im just going to go ahead and say that bootstrap table doesnt NOT allow captions, but it has nothing to do with them.

Try using GroupColumns instead, like you see here: http://issues.wenzhixin.net.cn/bootstrap-table/#options/group-columns.html

Also always check your fiddles, as your export is broken there

But you can see it working over here: http://issues.wenzhixin.net.cn/bootstrap-table/index.html

**Comment by Angelo85** [comment]
thank you. Ok for export excel, csv but with PDF repeats columns. see http://goo.gl/iDLSuF

It would be nice to also export the tag tfoot https://github.com/wenzhixin/bootstrap-table/issues/1371

**Comment by wenzhixin** [comment]
The table plugin does not support caption tag.
