### ISSUE TITLE
"Empty" cell for Hindi Language

### ISSUE THREAD

**Issue by balrammirani** [wenzhixin/bootstrap-table#1631]
Sir,
Am trying to fill bootstrap table with my json
{
"OriginalText" : "Edit \"Frontpage\" page",
"TranslatedText" : "\"Frontpage\" पृष्ठ को संपादित"
}

Table structure ::

   < table id='tbldata' border="1" data-toggle="table" data-cache="false" data-height="500" data-search="true" data-show-refresh="true" data-show-toggle="true" data-pagination="true" data-page-list="[5, 10, 20, 50, 100, 200]">
                    < thead>
                        < tr>
                            < th data-field="state" data-checkbox="true"></ th>
                            < th data-field="OriginalText"  data-sortable="true">Original Text</ th>
                            < th data-field="TranslatedText" data-editable="true" data-sortable="true">Translated Text</ th>
                        </ tr>
                    </ thead>
                </table>
        
It populates the rows as expected for other data entries but when I try to fill any value which contains quotes in translated content,it displays that translatedtext cell as Empty.
 
So,instead of filling the appropriate values,it fills translated text as "Empty"(though it works perfect for english side).

Please help me out.

**Comment by balrammirani** [comment]
Never mind,got the solution.
Took help from https://github.com/wenzhixin/bootstrap-table/issues/1237 and it worked.

**Comment by wenzhixin** [comment]
OK, close this issue.
