### ISSUE TITLE
popover does not work on th header cell

### ISSUE THREAD

**Issue by havok2063** [wenzhixin/bootstrap-table#1632]
I'm trying to add a popover onto the header cells of my table, such that when I hover over the header column, I get a popover with dynamic html content.   It works with the regular bootstrap table but does not work with your table.  The id of each header column also appears to be blank even though it's defined.  This may or may not be the problem. 

Here is my fiddle.  http://jsfiddle.net/wrpqe5hu/

In the fiddle, the top table is the normal bootstrap table, where it works.  The bottom is the one that doesn't.

**Comment by wenzhixin** [comment]
Use `post-body.bs.table` event to init the popover.

> Fires after the table body is rendered and available in the DOM

http://jsfiddle.net/wenyi/wrpqe5hu/3/

**Comment by serlogo53** [comment]
i also tried. this not working. i am using json data.
in table options i am using

        <table 
    class="table-striped"
         id="table" 
           data-toggle="table"
           data-url="<?php echo "datadurum.php"; ?>"
		   data-show-refresh="true"
      	   data-show-pagination-switch="true"
           data-page-size="50"
           data-page-list="[50, 100, 200]"  
           data-search="true"
           data-sort-name="date" 
           data-sort-order="desc"
           data-click-to-select="true" 
           data-select-item-name="radioName"
           data-height="650"
           data-pagination="true"
           data-query-params-type=""
           data-query-params="queryParams"
           data-show-columns="false"
       		 data-unique-id="hareket_id" 
       		    
           data-toolbar="#toolbar"
           data-id-field="hareket_id"
           data-show-footer="false"
          >

---
i used this but not working.
$('#table').on('post-body.bs.table', function () {
    $('[data-toggle="popover"]').popover();
});
----


if i delete data-toggle options in my table it's working but table not loading. table being empty.

**Comment by wenzhixin** [comment]
You can remove data-toggle and then:
```js
$('#table').on('post-body.bs.table', function () {
    $('[data-toggle="popover"]').popover();
}).bootstrapTable();
```

**Comment by dabros** [comment]
@serlogo53 - its worth having a grasp on jquery basics before diving into code

data-toggle is a common for of initialiser, plugins often use it to distinct elements to run code against on $(document).ready(function(){}) (DOM loaded event)

That is definetly 'not' always useful, especially with content loaded in after that even might have triggered.

I use either when appropriate, but often find myself making functions with patterns like this:

```javascript

function init_something(holder)
{
    if(!holder) holder = document;
    $(holder).find('.thing',function(){
        ...
    });
}

$(document).ready(function(){
    init_something();
    init_something_else();

   // and in ajax.done() or callback or whatever, just pass in scope to check for new objects to run the code against
});

```

Simple '!=' works in this case, pretty simple pattern to use.

**Comment by serlogo53** [comment]
@wenzhixin i removed data toggle from table proporties and aded your sentences but not working. everything is empty. in console log firefox: TypeError: $(...).popover is not a function

**Comment by dabros** [comment]
@serlogo53 - http://getbootstrap.com/javascript/#popovers

ALWAYS debug variables when issues occur, dont just post here.

I suggest console.log() ANY values interacting with that - as trying to call jquery functions like that on null or empty values can sometimes cause similar errors.

It 'could' also mean you need to check your dependencies, as maybe whatever bootstrap version (or custom build) your pointing to has no popover, or something similar is occuring.

Debug debug debug debug

Always check first

**Comment by serlogo53** [comment]
@dabros please after that don't answer my issues. Without your answer its being more easy.. Please !!!!

**Comment by wenzhixin** [comment]
@dabros is right, maybe you forget to import the `bootstrap.js` file?

**Comment by serlogo53** [comment]
@wenzhixin hi. no evertyhing is working. if i forget to put bootsrap.js. page many error. thanks. master we can close.. thanks.

**Comment by havok2063** [comment]
@serlogo53  well since this is my issue, I really should be the one to say if we can close it or not.  I haven't yet had time to say if @wenzhixin's solution worked for me yet or not.  Once I have time to test it, then I will comment.

**Comment by wenzhixin** [comment]
If the problem exists, reopen this issue.
