### ISSUE TITLE
data-filter-control trash icon does not get displayed in combination with export extension.

### ISSUE THREAD

**Issue by jermeyjungbeker** [wenzhixin/bootstrap-table#1633]
https://github.com/wenzhixin/bootstrap-table/blob/1.9.1/src/extensions/filter-control/bootstrap-table-filter-control.js#L303.

My trash icon didn't apear so i looked in the code and when i changed this it worked.
So to keep it simple:

    data-show-export="true"
    data-filter-control="true"
    data-filter-show-clear="true"

Doesn't work together.

**Comment by djhvscf** [comment]
Can you provide a fiddle? please @jermeyjungbeker

**Comment by jermeyjungbeker** [comment]
I'll see what i can do. Never used it but there is always a first for everything.

**Comment by jermeyjungbeker** [comment]
Oke i think this should suffice.

Here is one where you can see the trash icon doesn't get displayed.
1. https://jsfiddle.net/bdxzrk6z/3/

Here is one where you can see that the trash icon gets displayed if you don't use the export extension.
2. https://jsfiddle.net/dsc8rL5t/1/

Take refresh away and it doesn't get rendered again.
3, https://jsfiddle.net/js4veb8L/1/

**Comment by lpawlak** [comment]
I have the same problem using data-show-export

**Comment by wenzhixin** [comment]
Fixed this bug @jermeyjungbeker @lpawlak.
