### ISSUE TITLE
Conflict with angular-bootstrap

### ISSUE THREAD

**Issue by corina10** [wenzhixin/bootstrap-table#1635]
I am using your table in my website but I also need to include 'ui.bootstrap'.
Once I add it your table gets broken. I get this error in console: "pagination is now deprecated. Use uib-pagination instead." If I remove data-pagination from the table it is working fine but I really need the pagination feature.
Is there a way to keep both 'ui.bootstrap' and your table with pagination?

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle please ?

**Comment by dabros** [comment]
@corina10 - fiddle please

https://github.com/wenzhixin/bootstrap-table#reporting-issues
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Also maybe see new example i just noticed today: http://issues.wenzhixin.net.cn/bootstrap-table/index.html#integrate/angular

**Comment by corina10** [comment]
Hi,
I ended up setting pagination to true by default (in the bootstrap table sources)
 so there is no conflict anymore.
