### ISSUE TITLE
layout: search and pagination placement

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1637]
hello.

how make search and pagination side by side

currently:
![search2](https://cloud.githubusercontent.com/assets/13029902/10925166/e0501052-82c6-11e5-9fae-fdafeabb38b8.png)

or how to make look better? thanks

edit:
or how to place the "other" options aligned to search?
like this:
![search4](https://cloud.githubusercontent.com/assets/13029902/10926685/a066fe02-82d4-11e5-8e2a-80786f5b0601.png)

it's like a wen-bootstrap-table container for "custom" content
which can also have aligns like data-halign-custom and valign

thanks

**Comment by dabros** [comment]
@joomlaA1 - this is a simple example, you would want to add styling and ect.

https://jsfiddle.net/dabros/rg93rgkL/

But its very simple to use 'on-post-header' or similar callbacks (test to find if onPostBody or simliar works better if use case where it doesnt trigger correct)

Then you just move the pagination to the toolbar. First define (as a string or node/selector) a custom toolbar holder, to help with layout, then this:

```javascript
    .on('post-header.bs.table', function (){
        // NOTE - here is where you move the element up there
		$('#myToolbar').append($('.fixed-table-pagination'));
    })
```

That basic approach handles any and all situations if you then apply whatever styling corrects you want, or even append parts directly to ".columns.columns-right" or ".pull-right.search".

**Comment by joomlaA1** [comment]
hello @dabros i'm lost

is your answer something that would do like:

transform this:
![search2](https://cloud.githubusercontent.com/assets/13029902/10929899/14abf1ea-82f4-11e5-8083-b101eddd6ef2.png)

to this:
![search3](https://cloud.githubusercontent.com/assets/13029902/10929936/5d53f73a-82f4-11e5-9221-5ee810a36793.png)


i am lost... thanks

**Comment by dabros** [comment]
@joomlaA1 - youve been asking for help on a bunch of topics so far and displayed no real understanding of the basics.

Manipulating it so the code i show in my example lays out like that is jquery 101, very basic knowledge you HAVE to learn yourself before attempting so many custom, and very specific, modifications.

You google, look at jquery tutorials and how to take what i gave you and apply styling - or stick with a product which works great and looks good

**Comment by joomlaA1** [comment]
thanks

**Comment by joomlaA1** [comment]
hello @dabros
i went with on post body similar to:

    .on('post-header.bs.table', function (){
        // NOTE - here is where you move the element up there
        $('#myToolbar').append($('.fixed-table-pagination'));
    })

but its post post post everytime... because i "updateRow"

do we have better way like... once run only..

like     .on('first-post-header.bs.table', function (){
        // NOTE - here is where you move the element up there
        $('#myToolbar').append($('.fixed-table-pagination'));
    })

or other like that... thanks

**Comment by dabros** [comment]
@joomlaA1 - https://www.google.com.au/search?q=append%20if%20not%20there%20already%20jquery&rct=j

just google and look at tutorials and working examples of jquery, as i said above.

In this case, if appending multiple times, google that

**Comment by joomlaA1** [comment]
TY.
went with .one()

**Comment by dabros** [comment]
@joomlaA1 - i personally prefer something like this:

```javascript

if($(el).parent().find('.blah').length)
{
   // affect if needed
}
else
{
   // do append here
}

```

$.one() (http://api.jquery.com/one/) makes me a little nervous in that there may be cases the ui is recreated, not just on init. 

Though given this is the toolbar ui  you could 'maybe' assume that safely, i would still recommend using a more repeatable pattern that doesnt have potential for unexpected behaivour. The `initHeader` or `initPagination` event handlers seem far more reasonable locations for very simple 'if exists then affect, else append' type code.
