### ISSUE TITLE
Server-side search. Possible to require at least 3 characters?

### ISSUE THREAD

**Issue by matthewkris** [wenzhixin/bootstrap-table#1638]
Right now I am limiting things on the server side but the ajax request is still being made despite me not filtering the results. I'd love to be able to now even make a request unless the user enters 2 or more characters. Is this currently possible?

**Comment by dabros** [comment]
@matthewkris - that was one of the issues discussed in #1306 

i cant see it solved there, but there are linked topics you can follow to find out more

**Comment by wenzhixin** [comment]
Use `queryParams` to do what you want.

>When requesting remote data, you can send additional parameters by modifying queryParams. If queryParamsType = 'limit', the params object contains: 
limit, offset, search, sort, order Else, it contains: 
pageSize, pageNumber, searchText, sortName, sortOrder. 
Return false to stop request.

```
queryParams: function (params) {
    if (params.search.length < 3) {
        return false;
    }
    return params;
}
```

**Comment by dabros** [comment]
@wenzhixin - nice, i didnt even think of that :)

@matthewkris - please confirm this solved your issue and close this topic

**Comment by matthewkris** [comment]
@wenzhixin Thanks for the tip! I wasn't really understanding exactly what I could do with the queryParams. Unfortunately there are a few unintended consequences:

* On initial load params.search is undefined thus the result set is empty.
* If a user deletes back down to < 3 chars, the last returned result set is displayed.
* The only solution I could come up with is below which has the intended UX but still makes multiple requests.

```javascript
function queryParams(params) {
   if (typeof params.search !== "undefined" && params.search.length < 3) {
      params.search = "";
   }
   return params;
}
```

**Comment by wenzhixin** [comment]
Try this:
```js
queryParams: function (params) {
    if (params.search && params.search.length >= 3) {
        return params;
    }
    return false;
}
```

**Comment by wenzhixin** [comment]
have you solved your problem? If the problem exists, reopen the issue.
