### ISSUE TITLE
Export to Excel when side-pagination=server and data-page-list=All

### ISSUE THREAD

**Issue by michalmich** [wenzhixin/bootstrap-table#1639]
Hello,
i have problem with export to Ms-excel and Ms-Word when i set side-pagination=server and page-list=All. (Export to JSON, CSV works ok). 
There is no problem when parameter page-list  is set to 10, or 100.

**Comment by wenzhixin** [comment]
So, what problem do you have?

**Comment by michalmich** [comment]
Hi,
the problem partially solved.
 After I added a file Filesaver.js i can generate files properly in Chrome and FF. Without a file Filesaver.js google chrome is not allowed to create   file above 1.5MB (in my case, the clause ALL in data-page-lists).

Thank you
