### ISSUE TITLE
Search box X icon is not working in IE browsers.

### ISSUE THREAD

**Issue by jeevanpulugu** [wenzhixin/bootstrap-table#1640]
Hi,

In IE browsers bootstrap table search box will display a X icon if we enter any text. When we click on this icon it clears the text in the search box but it will not refresh the results of the table. This is happening only in IE browsers.

Is there any way to make table results to reload on click of X icon?

**Comment by wenzhixin** [comment]
You can try to listen the click event of X icon, and then call: `$table.bootstrapTable('refresh')`.

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/e3nk137y/3640/ (open it in IE)

**Comment by djhvscf** [comment]
See this #1875
