### ISSUE TITLE
How to define sorting value for a column

### ISSUE THREAD

**Issue by emzero** [wenzhixin/bootstrap-table#1641]
I'm using Livestamp.js plugin to format a datetime to "an hour ago" style.

So my `<td>`s end up like this:

    <td>
      <abbr title="November 4, 2014 7:14 PM" data-date="2014-11-04T19:14:00-03:00>a year ago</abbr>
    </td>

When sorting, it uses the "a year ago" text and, of course, it doesn't sort it correctly. Is there a way to tell "use this attribute (data-date) to sort this column" ?

**Comment by wenzhixin** [comment]
You can use `sorter` function, for example:
```js
function priceSorter(a, b) {
    a = $(a).data('date');
    b = $(b).data('date');
    if (a > b) return 1;
    if (a < b) return -1;
    return 0;
}
```
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-sort.html
