### ISSUE TITLE
initBody is evel function: extremelly slow

### ISSUE THREAD

**Issue by atelyshev** [wenzhixin/bootstrap-table#1642]
Hello,
I have a table with 3000 rows (it is constant number), no paging. I update that table every 2 sec with variable number of rows (1-100). I found that even update of 10 rows at once kills whole page.
The problem in 
this.initBody(true);
I am use updateRow and on each update it executes initBody. Bump.
What is could be cool, to have method updateRows and pass array of new rows there. Then use of initBody will be smaller.
In my code I just disabled initBody in updateRows and situation much better now. As I see update of data in the row cost nothing. I just introduced initBody on public level and execute it after all needed rows updated.
Having such huck makes grid useful. Only one problem, I still need to execute initBody at the end of my row update. And it is freezing page, making scrolling quite chunky. Is any optimization possible to make initBody not so heavy ? 

Thanks
Aleksey

**Comment by wenzhixin** [comment]
Thanks for your feedback, I will consider the problem what you said, BTW, any pull request is welcome.

**Comment by chuckarinze** [comment]
Hi wenzhixin
Are you currently working on something for this issue?
