### ISSUE TITLE
refresh row only, not refresh whole table

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1644]
hello @wenzhixin @dabros @djhvscf  everyone

today, we have this:
$table.bootstrapTable('refresh');

which would refresh whole table.

can we have "refresh a specific row only"?

or how to do this? thanks
(to avoid refreshing all data, need just one row)

**Comment by wenzhixin** [comment]
you can try `updateRow` method?

**Comment by joomlaA1** [comment]
ok thanks

**Comment by joomlaA1** [comment]
in updateRow

            Update the specified row, the param contains following properties: 
            index: the row index to be updated
            row: the row data

but how do i know the "index" of the row?

i am just using click-cell event which only gives me field, value, row, $element 
no index

thanks

**Comment by joomlaA1** [comment]
@dabros hello... @wenzhixin hello too...

**Comment by dabros** [comment]
@joomlaA1 - im sure i referenced this in response to another one of your questions, but use F12 and see that each row/TR has 'data-index' or similar on it.

Use clickCell or clickRow event and use something like `$element.parent('tr').data('index')`

**Comment by joomlaA1** [comment]
thanks ...
