### ISSUE TITLE
Implementing AJAX option `complete`

### ISSUE THREAD

**Issue by u01jmg3** [wenzhixin/bootstrap-table#1646]
- https://jsfiddle.net/u01jmg3/rkz9rzmj/

As per the fiddle, how can you attach a `complete` callback to AJAX calls? `beforeSend` works fine but `success` and `complete` do not fire. You can use Bootstrap Table's `onLoadSuccess` in place of `success` but there is no `onLoadComplete`. Is this done purposely?

**Comment by dabros** [comment]
ref: #1236

I would maybe point to not using ajaxOptions, but instead ajaxRequest, but the live example i pointed to in that post doesnt really seem to be working, and i cant see another use case that could be extended that way.

So i looked at source code, and very quickly this:


*line 1717 on current master*
```javascript

request = $.extend({}, calculateObjectValue(null, this.options.ajaxOptions), {
    type: this.options.method,
    url: this.options.url,
    data: this.options.contentType === 'application/json' && this.options.method === 'post' ?
        JSON.stringify(data) : data,
    cache: this.options.cache,
    contentType: this.options.contentType,
    dataType: this.options.dataType,
    success: function (res) {
        res = calculateObjectValue(that.options, that.options.responseHandler, [res], res);

        that.load(res);
        that.trigger('load-success', res);
    },
    error: function (res) {
        that.trigger('load-error', res.status, res);
    },
    complete: function () {
        if (!silent) {
            that.$tableLoading.hide();
        }
    }
});

if (this.options.ajax) {
    calculateObjectValue(this, this.options.ajax, [request], null);
} else {
    $.ajax(request);
}

```

That is literally all the code i can see directly interacting with ajax at all. 

So there are two events that are triggered using base code, 'load-success' and 'load-error'. 

No direct callback for 'complete', but you create additional listener for both events or call same function from inside existing listeners to each.

However, with ajaxOptions you can pass in 'additional param', the extend statement they use always appends thier own options over whatever else you pass. 

And **that is fine**, maybe not 'ideal' for simplifying your own code, but just look at the options they do pass through, all except for complete are user defined (this.options) or have callbacks, **except** for complete.

But who cares if no 'on-complete' direct callback, that is more than covered by 'onPostBody' or even by listening to both 'load-success' and 'load-error'. There is also the 'responseHandler' function, which only triggers on success and allows easy manipulation of returned data.

Just look at this and use existing callbacks, you maybe want to pass through 'before send' or ect, but existing events already cover everything else. 

Just look at something like http://issues.wenzhixin.net.cn/bootstrap-table/index.html and see all the events triggering, its more than covered.

**Comment by u01jmg3** [comment]
Thanks for your suggestions @dabros but there is still a problem - `onLoadSuccess` does not return the AJAX object in the same way the native callback `success` does (and defining `ajaxOptions.success` does not work as per my fiddle). `onLoadError` does return the AJAX object so that is unaffected.

A change to the code for `onLoadSuccess` and what it returns, and adding in an `onLoadComplete` callback would be the best thing to do to improve the consistency of how AJAX calls work in Bootstrap Table. I can submit a PR for this?

It might also be worth noting in the documentation that even with `ajaxOptions` you cannot extend and override the native AJAX `success`, `error` or `complete` callbacks to pass in additional parameters as demonstrated by my fiddle.

**Comment by dabros** [comment]
@u01jmg3 - i agree with updating doco, thats on github so go for it :)

Regarding onLoadSuccess, explain a use case where you need the ajax object returned, because the **data** object as far as im aware is (which is passed to both **onLoadSuccess** and **responseHandler**) contains all data you returned, or an error message if failed.

Do test to see if 404 or 500 errors are returned like that, but all custom errors in my code and handled very easily by using either method.

Unless you can find some good reason the **data** object is not sufficient, then i cant see possible use case (error or success) where a combination or one or both of these wont match your situation.

A little inconsitent with $.ajax() perhaps, but i agree with not overwriting the defaults, and dont see need to rework handlers as everything returned from server is sent there (though as i said havent tested critical errors)

**Comment by u01jmg3** [comment]
My use case is simple. I want to be able to track all Bootstrap Table AJAX calls in order to abort calls which have been superseded with a more recent request; this prevents issues of past calls returning after a more recent request has returned (nature of AJAX). I can only do this if I can access the AJAX object. As `onLoadSuccess` prevents me from using `ajaxOptions.success` and amends its response to return the data Array rather than the AJAX object, this is where my problem arises.

Why doesn't `onLoadSuccess` return the AJAX object as it should and then if the data Array is required, it can still be extracted from the AJAX object?

Furthermore, to further improve consistency, an `onLoadComplete` callback should be created.

**Comment by dabros** [comment]
@u01jmg3 

`onLoadComplete` is `responseHandler`, to add both is unneccesary redundancy, but if you think you can merge it in a way to avoid it being flagged as redundant, then i suggest you make **PR** with both doco and code changes (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md)

And `beforeSend` has the ability to abort requests (http://stackoverflow.com/questions/10507079/stop-ajax-on-beforesend) and in **responseHandler** you could even just call ` $table.bootstrapTable('getData');` if you dont want to load the response.

If looking for 'superseded' requests, i would recommend creating a simple variable that matches a uid sent with last request, then return that uid in the response. **responseHandler** can then strip out that index and return the neccessary data (or load existing data). The same applies if the checker variable is a timestamp sent back with each request, which is stored and checked against each time in **responseHandler**.

Now that 'does' leave chance of table reloading same data twice, but removes chance of outdated data.

I can only ever seeing that being an issue in a few cases:

1. if user is triggering manually many times (NOT recommended, just disable button so user cant spam it just cause it takes a few sec).

2. Some type of auto-refresh code on timed interval. In which case you should be expecting table to reload repeatedly so reloading most current data twice shouldnt be a prob.

Outside of what can be easily covered in this way I fail to see how you need to modify or even read the original ajax object, so if you still adament then please provide more detail and context, ideally the code you using and descriptions of why the exact way it is.

If this is such an issue there always the option to load data via your own ajax ticker/interval function, then call `$table.bootstrapTable('load',data);`. But that hardly seems needed when a simple variable (which you can append to window object or similar if needed in wider scope) can easily distinct the most recent request.

**Comment by u01jmg3** [comment]
> onLoadComplete is responseHandler, to add both is unneccesary redundancy, but if you think you can merge it in a way to avoid it being flagged as redundant, then i suggest you make PR with both doco and code changes (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md)

How can it be considered redundant when there is no way of accessing `ajaxOptions.complete` because Bootstrap Table overwrites it without returning any sort of custom callback (in the same way `ajaxOptions.success` has `onLoadSuccess`)? Furthermore, how can `onLoadSuccess` be considered correct when it doesn't return the same object as the native `ajaxOptions.success`?

> And beforeSend has the ability to abort requests (http://stackoverflow.com/questions/10507079/stop-ajax-on-beforesend) and in responseHandler you could even just call $table.bootstrapTable('getData'); if you dont want to load the response.

Your link does not relate to aborting/tracking previous AJAX calls - it only talks about stopping AJAX calls before sending them and then that's it. This is not the same scenario I am dealing with.

>If looking for 'superseded' requests, i would recommend creating a simple variable to check against in responseHandler, which can strip out that index and return the neccessary data (or load existing data).

> You can pass any extra data you want back with the request, including timestamps, which can be stored locally and checked each time.

> Now that 'does' leave chance of table reloading same data twice, but removes chance of outdated data.

I already have a working and thoroughly tested way of tracking AJAX calls. The enhancement to Bootstrap Table is literally a few lines of code. Why are you against my proposal when it's the most logical step?

> Outside of what can be easily covered in this way I fail to see how you need to modify or even read the original ajax object, so if you still adament then please provide more detail and context, ideally the code you using and descriptions of why the exact way it is.

I have already provided a viable use case with explanation. For each library I am using I track the AJAX calls it makes so I can abort them if necessary if they become superseded or if I refer to cached data before a previous AJAX call has had time to reply. This prevents display issues from orphaned calls no longer relevant to the output shown to the user.

Bootstrap Table is the only library I cannot do this with because the AJAX object is not passed back as it should be and I cannot use `ajaxOptions.complete` because it is overwritten.

> If this is such an issue there always the option to load data via your own ajax ticker/interval function, then call $table.bootstrapTable('load',data);. But that hardly seems needed when a simple variable (which you can append to window object or similar if needed in wider scope) can easily distinct the most recent request.

Absolutely, I don't want to have to do this.

**Comment by dabros** [comment]
@u01jmg3 - you fail to provide an answer to question of HOW you are working with the ajax object

ALL you need to do is pass back timestamp or whatever other field you checking against as index in return, then use **responseHandler**

Ive explained that in detail now but you have completely brushed it aside.

As i said above, show code or explanation of WHAT you are checking that cannot work in this way.

**Comment by u01jmg3** [comment]
As per #1575

You have much more control tracking AJAX calls as I have shown below rather than fiddling with timestamps.

```js
<script>
$.xhrPool = [];

$.xhrPool.abortSingle = function(prop){
    if(isset(this[prop]) && this[prop] instanceof Array && this[prop].length > 0){
        $thiz = $(this[prop]);

        $thiz.each(function(i, jqXHR){
            jqXHR.abort();
            $.xhrPool.splice(i, 1);
        });
    }
};

$.xhrPool.abortAll = function(){
    $(this).each(function(i, jqXHR){
        jqXHR.abort();
        $.xhrPool.splice(i, 1);
    });
};

$.extend($.fn.bootstrapTable.defaults, {
    ajaxOptions: {
        beforeSend: function(jqXHR){
            if(!isset($.xhrPool.bootstrapTable)){
                $.xhrPool.bootstrapTable = [];
            }

            $.xhrPool.bootstrapTable.push(jqXHR);
        },
        complete: function(jqXHR){
            var index = $.inArray(jqXHR, $.xhrPool.bootstrapTable);

            if(index > -1){
                $.xhrPool.bootstrapTable.splice(index, 1);
            }
        }
    }
});

// $('.table-results').bootstrapTable();
// $.xhrPool.abortSingle('bootstrapTable');
// $.xhrPool.abortAll();
</script>
```

**Comment by wenzhixin** [comment]
Got the problem and fixed it.

**Comment by u01jmg3** [comment]
:+1:
