### ISSUE TITLE
sidePagination: 'server' configured. but after querying with searching, pageNumber must be (1), but it remembers old page number

### ISSUE THREAD

**Issue by cetindogu** [wenzhixin/bootstrap-table#1647]
for example:
i searched a record with name "Ahmet" and find my record at 5th page. and then search for "Mehmet". BUT pageNumber stil 5.

**Comment by dabros** [comment]
@cetindogu - either please provide a fiddle (https://github.com/wenzhixin/bootstrap-table#reporting-issues) and/or try to replicate this in existing example (http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html), because i certainly couldnt.

**Comment by cetindogu** [comment]
OK. I WILL EXPLAIN MORE DETAILED. AND So Sorry, my wcf service cannot be called from other networks. (for security reasons)

1.) i activicate the table with javascript. And also "search"  is false in my code.
"search:false"
2.) I filter and sort my records at queryParams function:

But Grid do not know that "i filtered the records" because of "queryParams" function
"so grid does not go to 1st PAGE."   :) 







---------------------------
function queryParamsSporcuListesi(params) {

    if (!params.search) {
        params.search = $('#txtBoxTCKimlik').val() + ';' +
                        $('#txtBoxSporcuAdi').val() + ';' +
                        $('#txtBoxSporcuSoyadi').val();
    }
    if (!params.sort) {
        params.sort = 'SporcuId';
    }
    if (!params.limit) {
        params.limit = null;
    }
    if (!params.offset) {
        params.offset = 0;
    }

    return params;
}
----------------------------




my js codes:
<script type="text/javascript">
var mygridoptionsCetGrid1={
sidePagination:'server',
exportDataType:'basic',
idField:'SporcuId',
singleSelect:true,
striped:true,
clickToSelect:true,
search:false,
showExport:false,
showToggle:false,
showColumns:false,
showRefresh:false,
exportTypes:['json', 'xml', 'png', 'csv', 'txt', 'sql', 'doc', 'excel', 'powerpoint', 'pdf'],

pagination:true,
maintainSelected:true,
dataUrl:'SporcuAra.aspx/ListeyiGetir',
queryParams:'queryParamsSporcuListesi'
}; 

var cetGrid;
function BsTable(tableId, cetGridOptions) {
    cetGrid = $('#' + tableId).bootstrapTable({
        trimOnSearch: true,
        cardView: false,
        cache: false,
        smartDisplay: true,
        method: 'post',
        searchAlign: 'left',
        pageSize: 10,
        pageList: [10, 25, 50, 100],
        showColumns: cetGridOptions.showColumns,
        showToggle: cetGridOptions.showToggle,
        striped: cetGridOptions.striped,
        url: cetGridOptions.dataUrl,
        idField: cetGridOptions.idField,
        singleSelect: cetGridOptions.singleSelect,
        clickToSelect: cetGridOptions.clickToSelect,
        showExport: cetGridOptions.showExport,
        exportTypes: cetGridOptions.exportTypes,
        exportDataType: cetGridOptions.exportDataType,
        sidePagination: cetGridOptions.sidePagination,
        queryParams: cetGridOptions.queryParams,
        pagination: cetGridOptions.pagination,

        search: cetGridOptions.search,
        showRefresh: cetGridOptions.showRefresh,
        maintainSelected: cetGridOptions.maintainSelected,
        rowStyle: cetGridOptions.rowStyle
    });

    eval('window.' + tableId + ' =cetGrid;');
}
var defaultQueryParams = function (params) {
    if (!params.filter) {
        params.filter = '';
    }
    if (!params.search) {
        params.search = '';
    }
    if (!params.sort) {
        params.sort = this.idField;
    }
    if (!params.limit) {
        params.limit = null;
    }
    if (!params.offset) {
        params.offset = 0;
    }
    return params;
};
function bsDateFormatter(value) {
    return new Date(value.match(/\d+/)[0] * 1);
}
$(document).ready(function () {
        BsTable('CetGrid1',mygridoptionsCetGrid1)
});</script>


my html

**Comment by cetindogu** [comment]
Hello,
i solved this issue with this: but this is not best practice, i think :) 

there must be an option to reset page in queryParams function(...){...} i think :)


   $('#CetGrid1').bootstrapTable('getOptions').sidePagination = 'client';
    $('#CetGrid1').bootstrapTable('selectPage', 1);
    $('#CetGrid1').bootstrapTable('getOptions').sidePagination = 'server';

**Comment by dabros** [comment]
@wenzhixin @djhvscf - i think this could be solved by setting page number in server side, or setting it to 0 in queryParam, or affect ajaxOptions

Im just a little unsure as very little experience with server side, you prob know example code though

thanks

**Comment by cetindogu** [comment]
@wenzhizin :)

**Comment by cetindogu** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
@dabros, sorry, but what do you mean?

**Comment by cetindogu** [comment]
Just want to say ;) the developer must set a new option for this problem

**Comment by wenzhixin** [comment]
I find this bug has been fixed in the latest version: http://issues.wenzhixin.net.cn/bootstrap-table/
