### ISSUE TITLE
Reorder / Resize state save via Cookie

### ISSUE THREAD

**Issue by andresendo** [wenzhixin/bootstrap-table#1648]
Hi,
is it possible that we can save the reorder and resize via the cookie ext?

Thanks 
andre

**Comment by dabros** [comment]
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/cookie

Sort Order should be saved by default, if you want to add other fields then a **PR** is always welcome.

The code is very simple, so give it a go, but if you try and fail then provide detailed use case as to how you resizing and why this needs to be a cookie value.

**Comment by wenzhixin** [comment]
any pull request is welcome.

**Comment by djhvscf** [comment]
Yes, we need to implement this.. But right now i don't have enough time in order to develop new features so as the guys said "Any pull request is welcome" @andresendo

**Comment by dabros** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

**Comment by djhvscf** [comment]
Same as https://github.com/wenzhixin/bootstrap-table/issues/2889
