### ISSUE TITLE
Column events break with multiple columns with the same field name

### ISSUE THREAD

**Issue by wcatron** [wenzhixin/bootstrap-table#1649]
When creating a table with multiple columns with the same field name (example 'fork_count') the events do not apply to the proper column. They try to apply to the first instance of the field name.

Example first table works, second fails.
https://jsfiddle.net/e3nk137y/3554/

This has worked in the past as evident by this example which uses version 1.6
https://jsfiddle.net/sf36oa42/3/

**Comment by dabros** [comment]
@wcatron - fix your post, your first fiddle doesnt show the issue, and the second points to master, so i think you got them mixed up.

Im not ruling this out as a bug or not, but to work just remember you dont even need **data-field** if your using a **formatter**, as the entire row is passed in.

See my update: https://jsfiddle.net/dabros/sf36oa42/1/

**Comment by wcatron** [comment]
I've updated the original JSFiddles I must not have realized how to save them. 

>Im not ruling this out as a bug or not, but to work just remember you dont even need data-field if your using a formatter, as the entire row is passed in.

I understand that *data-field* is not required, I was able to work around the problem. However, formatters are often times (at least in my projects) reused across multiple tables representing slightly different data. operators should have the same reusability.

>Im not sure that leaving out field wont bug other code, but you can give it your own name if that does happen, which i can only expect if needed to referance by column name.

Once you relook at the fiddles again you should be able to see what I was talking about when I said that it worked previously in version 1.6. I had the same thought that it was necessary for referencing the column. However, having worked previously it seems like if they've updated their referencing and broken functionality. This is how I discovered the issue when I updated my old code that worked.

>Internally it uses some calculateObjectValue or similar that takes into account formatters. However, maybe sortName would be enough to cover all other use cases?

You lost me here. I'm not an expert on the internals of bootstrap. I've dabbled in extending some of the search stuff but other than that I was really looking for some help.

Thanks for taking a look at this!

**Comment by dabros** [comment]
@wcatron - just some quick notes

I make reusable formatters too, but its simple to place some kind of `if(typeOf(val) === 'undefined')` with a switch if further handling needed, and/or 'convenience handlers' aka 'alias' for those formatters that call them but pass in some extra param. You can also define formatter via js so can make those aliases into anonymous functions there and just call your reusables with optional param passed in.

**sortName** is an optional column param that might be needed if you ommit the 'data-field' entirely, or if the 'data-field' doesnt actually match up to a sortable field name.

Also do clarify whether you solved your issue and share how, as what i gave is working code showing what i described.

**Comment by wcatron** [comment]
Although I worked around the problem, I did not solve the underlying issue. There is still a bug that breaks code if people try to use the same data-field twice with an event attached to the latter. Do you agree that it is a bug given the two example JSfiddles? Other people could run into it and it could be effecting more than just events.

**Comment by dabros** [comment]
@wcatron - I dont really see this as a bug, though maybe worth a mention in doco OR (more practically) an example of no 'data-field' and just 'formatter' + 'sortName' in formatter or its own example (call it 'duplicate data-field #1649' as issue example in http://issues.wenzhixin.net.cn/bootstrap-table/index.html)

My rational for not being a bug relates to a few points:

1. the fact that data-field is an *optional* param
2. the ease of use in formatters
3. the rare probability of multiple columns with exact same data and no formatter
4. that 'sortName' covers (i assume) sorting and searching (to be confirmed)

Im worthing with different tech so difficult to test and launch full example (and **PR**), but wouldnt be hard if you keen (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md)

**Comment by wcatron** [comment]
@dabros - I still think there's an underlying problem here. The fact that it's **optional** is why is so concerning that the framework seems to utilize it when setting events instead of relying on a raw column index. This problem is effecting more than just formatters. If you try the same experiment with the **visible** parameter it also fails. I understand it's not common but it's still a bug, and it seems like it's effecting more than just events.

This broke my old code, meaning it could break others who haven't updated yet. I've identified the problem and fixed it with my pull request. Is there a reason that the getFieldIndex was being used verses just using the index provided? I think there are more places this could be simplified. Am I missing some added functionality?

**Comment by dabros** [comment]
@wcatron - i had no part in developing that or extending recent functionality, you have my analysis of how to work with it.

If you do thorough code analysis and feel its lacking, by all means do a **PR** (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md) yourself and/or detail here what changes you feel would make it work, and call in wenzhixin and maybe also djhvscf to approve your ideas too - i will help proof but better to loop in those responsible for most related code.

I still stand by my statements above, but as i also stated there - i am assuming that ommiting it (or using dummy name that doesnt match actual row[index]) can be easily worked around without breaking more core code. by use of aforementioned dummy name and param like `sortName`.

**Comment by wenzhixin** [comment]
@wcatron thanks for your **PR**.

In fact, from v1.9.0 on, I updated the implement of columns field because we need to support header `colspan` and `rowspan`, like @dabros said with same field it is not recommended.

I check out your pull request #1664 and there are two bugs in that: http://issues.wenzhixin.net.cn/bootstrap-table/welcome.html?https://rawgit.com/wcatron/bootstrap-table/fix-data-field/src/bootstrap-table.js. (welcome.html?your-bootstrap-table.js)

**Steps:**
1. click Cloumns and uncheck Item Name to hide name field.
2. click Item Operate. // bug1: nothing to alert
3. Open the `Console` panel (Chrome F12).
4. Copy and paste: `$table.bootstrapTable('mergeCells', {index: 1, field: 'name', colspan: 2, rowspan: 3});` // bug2: merge error.

Let's compare with http://issues.wenzhixin.net.cn/bootstrap-table/welcome.html

**Comment by wcatron** [comment]
Ah, I see where I went wrong and the source of the original problem. By using `$.inArray` to get the field index originally it would always get the first column with the name (leading to #16. I'm going to work on a way that calculates the field index based on the absolute index (without hidden columns) and which columns are hidden.
