### ISSUE TITLE
Improve to integrate AngularJS

### ISSUE THREAD

**Issue by betonetotbo** [wenzhixin/bootstrap-table#165]
I had to change the version 1.2.3 to integrate with AngularJS diretives.

Here is my changes:
     http://jsfiddle.net/njp11jup/

With them, I'm able to compile angularjs directives to process custom cell contents.

An example:

      angular.module('bootstrapTableDirective').directive('bsTable', ['$compile', function($compile) {
        return {
            restrict: 'A',
            link: function(scope, el, attrs) {
                var options = scope.$eval(attrs.bsTable); // evaluate config object from angular controller
                
                // create table over element
                el.bootstrapTable(options);
                
                // monitor DOM changes inside table, to compile dynamic cell content
                el.bind('body-changed.bs.table', function() {
                    $compile(el)(scope);
                });
            }
        };
      }]);

**Comment by AkramKamal** [comment]
here are my solution to use Bootstrap-Table inside angular https://jsfiddle.net/f56eL3nj/

**Comment by wenzhixin** [comment]
Thanks for your resources @AkramKamal , can you help to add an example to our [examples repos](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/integrate/angularjs.html), and I will add it to http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by AkramKamal** [comment]
sure, i will work on it now

**Comment by AkramKamal** [comment]
OK, done, please check https://github.com/AkramKamal/bootstrap-table-examples/tree/master/integrate

**Comment by wenzhixin** [comment]
Good @AkramKamal , you can do a pull request.

**Comment by fynnfeldpausch** [comment]
@AkramKamal What is your reason for resetting the bootstrap table view every .5sec?

**Comment by AkramKamal** [comment]
it's a mistake, I forgot to replace that code with $(window).on('resize', ....

**Comment by wenzhixin** [comment]
@AkramKamal , you can create a new pull request to the bootstrap-table-example repo, thanks.

**Comment by AkramKamal** [comment]
ok, done, https://github.com/AkramKamal/bootstrap-table-examples/tree/master/integrate

**Comment by jpmckearin** [comment]
@AkramKamal This looks really interesting. Just a head's up, using the bs-table-control directive as an element does not work as expected.

**Comment by wenzhixin** [comment]
Merged your commits: https://github.com/wenzhixin/bootstrap-table-examples/pull/38 @AkramKamal

**Comment by AkramKamal** [comment]
@jpmckearin , it's important to have a table tag, not anything else, so, please use it as attribute like this:
<table bs-table-control >
   define your tr and td
</table>

**Comment by losewin** [comment]
I have a problem, when I use the plugin..
below is the error code.. and I dont know why

TypeError: $el.bootstrapTable is not a function
    at Object.fn (bootstrap-table-angular.js:88)
    at n.$digest (angular.js:15826)
    at n.$apply (angular.js:16097)
    at h (angular.js:10546)
    at K (angular.js:10744)
    at XMLHttpRequest.z.onload (angular.js:10685)

**Comment by losewin** [comment]
How do I implement the custom toolbar?, which will bind to angular also ?

**Comment by chiaramcphee** [comment]
Hi there - I have the same question as @losewin. Thanks for your help!

**Comment by 77number** [comment]
@chiaramcphee @losewin You can do anything inside the link function

**Comment by strikerjjb** [comment]
@AkramKamal Your code doesn't seem to account for the ng-click function placed inside of the column formatter option.  How would you adjust the directive/module you wrote to handle this activity?  Also anyone else have any ideas for this? Some earlier comments suggest recompiling the table but I don't know if that is the best option.

**Comment by wipmuralikrishnank24** [comment]
Hi I am trying to Call Web API and bind to Bootstrap table.Could  you please suggest how to do that. the shared exmaple provided only binding 500 manual created record throught loops.but no example avaiable for binding external api.Please suggest.

**Comment by OpenEyeNet** [comment]
I am still unable to get things to work in angular view.
