### ISSUE TITLE
Bug bootstraps table groub by

### ISSUE THREAD

**Issue by endra89** [wenzhixin/bootstrap-table#1650]
https://github.com/wenzhixin/bootstrap-table/issues/694
bug when multiple table please see @djhvscf @Knoxvillekm @wenzhixin :
http://jsfiddle.net/endra89/341n34LL/7/
table1 grouing enable result : table grouping work
table2 grouing false result : table no grouping
and table 3 grouing false result : table not show
please fix it, work fine if using 2 table but not show when using more 3 table
@djhvscf  
http://jsfiddle.net/endra89/73tq9anq/3/
your table workfine, but i need default grouping explant like table made by Knoxvillekm
how to configure ?

**Comment by Knoxvillekm** [comment]
See this fix:
https://github.com/wenzhixin/bootstrap-table/issues/694#issuecomment-136151487

**Comment by endra89** [comment]
miss this part thank
