### ISSUE TITLE
version 1.9.1 - getRowByUniqueId not working

### ISSUE THREAD

**Issue by fan-cpp** [wenzhixin/bootstrap-table#1651]
bootstrapTable version 1.9.1
Browser: Chrome

call method: $('#table').bootstrapTable('getRowByUniqueId', 0);
throw error
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined

**Comment by dabros** [comment]
@fan-cpp - if i recall correct, you need to define table option 'uniqueId' and ensure it has a matching row.

If you hit F12, each TR should have a `data-uniqueid` as well as standard `data-index` printed in it. Ensure it matches what you are trying to use.

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getRowByUniqueId.html

If you think you did it right then you need to share a fiddle replicating the issue: https://github.com/wenzhixin/bootstrap-table#reporting-issues

**Comment by dabros** [comment]
@fan-cpp - can you please confirm that you fixed this issue and close this topic if so?

**Comment by wenzhixin** [comment]
If the problem exists, reopen the issue.
