### ISSUE TITLE
Reset sort icons and functions.

### ISSUE THREAD

**Issue by goper-leo** [wenzhixin/bootstrap-table#1659]
I have a reset button which have functions that can hide and refresh table. But when table is showed again the sort icon is not resetting Ive tried these methods "$('#table').bootstrapTable('resetView');" and "$('#table').bootstrapTable('refresh');" but none of them will refresh the tables. http://159.203.71.70/tools/parametric-search see that for example. Search "Part Number" and when the table is show press any sortable columns and click "Reset" button. Search again with the same before and the sort function and icon is still there not reseting table. Hop you can help Thanks.

**Comment by cetindogu** [comment]
Hello, if search:false and also you filter your records via queryParams: function(...){...}
grid does not know i filter the data :) so there must be an option for resetting page number to (1) before new request.

**Comment by cetindogu** [comment]
https://github.com/wenzhixin/bootstrap-table/issues/1647

this is my topic, similar to yours

**Comment by cetindogu** [comment]
i solved this issue with

   $('#CetGrid1').bootstrapTable('getOptions').sidePagination = 'client';
    $('#CetGrid1').bootstrapTable('selectPage', 1);
    $('#CetGrid1').bootstrapTable('getOptions').sidePagination = 'server';

**Comment by wenzhixin** [comment]
@goper-leo you can use `refreshOptions` method to solve your problem.

**Comment by goper-leo** [comment]
I solve this by destroying the table and create them back. 
$('#table1').bootstrapTable('destroy');
$('table1').bootstrapTable();
This will refresh sorting and page views.

**Comment by wenzhixin** [comment]
You are right, `$('#table1').bootstrapTable('destroy').bootstrapTable();` is same with `$('#table1').bootstrapTable('refreshOptions')`.
