### ISSUE TITLE
invisible column's coding cannot be seen with inspect element

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1661]
The coding of a column with data-visible="false" (for example: 
\<th data-field="fieldName" data-visible="false">\</th\>
) cannot be seen on the "inspect element"?

(The coding, i mean the \<td fieldname visible=false>\<\td\>)

since it cannot be seen, 
it cannot be accessed as sibling of another td (a visible sibling td)????
( like
.siblings( "the invisible field" ) )

it cannot be? i like to get the invisible field's value... ideally by the visible sibling td..

how? thanks

@dabros @wenzhixin @djhvscf

**Comment by wenzhixin** [comment]
I don't know what you say, can you format your question?

**Comment by dabros** [comment]
@joomlaA1 - again, examples and clearer description pls!!!

I assume you talking about `display:none` or `visibility:hidden`. I do recall maybe hearing that `display:none` stops some code from working, but that has absolutely no effect on the **row** data object, present in many methods including **onClickRow** and ect

As we have asked repeatedly from you, provide a fiddle and clear description of what you already tried if you want more help

**Comment by joomlaA1** [comment]
hello i edited the question(codes did not appear before)... thanks
@dabros @wenzhixin @djhvscf

**Comment by dabros** [comment]
@joomlaA1 - my answer still stands as my assumption of what you meant was correct

**Comment by dabros** [comment]
@joomlaA1  - my answer still stands as even though (as now clarified) you referring to how its not even printed if disabled via `showColumns` or `data-visible="false`, neither of those affect the **row** data object I referred to in my answer.

**Comment by dabros** [comment]
@joomlaA1 - prob of interest is also `getRowByUniqueId`, with i explain a little in #1651

By setting `uniqueId` table option you can then use easy traversal to find each rows value of that in the TR, and `getRowByUniqueID` returns the **row** data object matching that.

http://bootstrap-table.wenzhixin.net.cn/documentation/#methods
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getRowByUniqueId.html

**Comment by joomlaA1** [comment]
thanks i go with unique id
