### ISSUE TITLE
Does bootstrap-table search through nested values ?

### ISSUE THREAD

**Issue by IOR88** [wenzhixin/bootstrap-table#1665]
Hi,

From what I have seen in src code, 

there is no support for SEARCH through nested values {a: {b:'',c:{} } } 

If I am wrong I would really appreciate some hint how to make bootstrap-table search through nested values, maybe I have provided some wrong attributes in options 

example from bs-table Angular: 

                        {field: 'properties.name',
                        title: 'Name',
                        sortable: true,}

**Comment by wenzhixin** [comment]
provide a jsfiddle please

**Comment by dabros** [comment]
@IOR88 - fiddle please, this might help

https://github.com/wenzhixin/bootstrap-table#reporting-issues
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
