### ISSUE TITLE
Consuming RestFull web services

### ISSUE THREAD

**Issue by sundsx** [wenzhixin/bootstrap-table#1671]
Hi, i have an issue when submit GET VERBS for retrieve my json data. 
What happen is that the GET called add a sort order parameter by self.
http://web.me/testApi/v5/read/discipline?order=asc"

My api accept order but by column number. ex  "order?=2"
 
So the question is: How i can remove order appended to call by self?
my code: 

     <script type="text/javascript"> 
    var table;
    $(document).ready(function() {
    table =  $('#table-js').bootstrapTable ( {
      method: 'GET',
      url: 'http://web.me/testApi/v5/read/discipline',
     // sort: false,
     // height: 450,
     // cache: false,
     // striped: true,
     // pagination: true,
     // pageSize: 10,
     // pageList: [10, 25,50, 100, 200],
     // minimumCountColumns: 2,
      clickToSelect: true,
      columns: [{
            field: 'id',
            Title: "ID",
            align: "center",  
        }, {
            field: 'disciplinaNome',
            Title: "dataSrc",
            align: "center", 
        }]
    }) ;
    });
    </script>

**Comment by wenzhixin** [comment]
Do you mean ?order=2? You can use requestParams option to do what you want.

**Comment by sundsx** [comment]
YEs ?order=2. Thank You

**Comment by sundsx** [comment]
Thank you wenzhizin, that fix order pararamet, but change the METHOD from GET to OPTION. 

method: 'get',
     queryParams: function (p){
          return {
            order:2
          };
The method must be GET.

**Comment by wenzhixin** [comment]
The default method is 'get', please recheck your problem.

**Comment by wenzhixin** [comment]
If the problem exists, reopen this issue.

**Comment by sundsx** [comment]
![schermata 2015-11-13 alle 14 33 49](https://cloud.githubusercontent.com/assets/1713528/11147095/e029fb66-8a13-11e5-8ecb-9921940f3acf.png)
I am garcefully for your time. But if i use queryParam i get OPTION. So the correct question is: how i can remove order=asc appended by default?

**Comment by wenzhixin** [comment]
you can use `delete params.order;` in `queryParams `function.
