### ISSUE TITLE
data('uniqueid') and other methods description

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1672]
current description is like

Given a jQuery object that represents 1 DOM element, the data('uniqueid') method gets the uniqueid of the element and returns it.

could it be like

Given a jQuery object that represents a set of DOM elements, the data('uniqueid') method gets the uniqueid each of these elements and returns them.

thanks just question

**Comment by wenzhixin** [comment]
pull request is welcome https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

**Comment by dabros** [comment]
@joomlaA1 - in case wasnt clear, all doco is on github and editable, just make a PR to the develop branch (pretty easy even just using browser github UI) with whatever doco changes you feel appropriate

maintaining doco is a significant overhead, and the person who made the particular code is not always to describe it best to people who might not share same level of knowledge of related code - so always appreciated

**Comment by joomlaA1** [comment]
thanks just idea
