### ISSUE TITLE
pagi and pagi detail alignment

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1688]
when:
data-pagination-detail-h-align="right"
                    data-pagination-v-align="top"
                    data-pagination-h-align="right"

it show like this:
![pagi align](https://cloud.githubusercontent.com/assets/13029902/11162537/11b44510-8ae1-11e5-8103-366fb2d30ef6.png)

can it be first is the details then the pagination...

like:
![pagi align3](https://cloud.githubusercontent.com/assets/13029902/11162544/6b0a7670-8ae1-11e5-821e-47706d3e25c2.png)

 thanks

**Comment by joomlaA1** [comment]
@wenzhixin @dabros @djhvscf thanks

**Comment by dabros** [comment]
@joomlaA1 - see the detailed responses in #1637 and what we said there.

And then look at this: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker

This is a place for bugs. I do help with advanced use cases here myself, but most of those are from people thinking there is a bug or wanting a desired feature but either not realising its already there under another name, or that it isnt and good chance PR comes of it.

This, along with the last time you asked this, is not one of those

Learn basic jquery commands and re-arrange the order of elements.

This has been done a thousand thousand times before, just google and stop focusing on bootstrapTable as this is nothing to do with that.

I already gave a working example where you can trigger this whenever needed, showed you how to move the pagination and explained about re-arranging it even more.

Use google, use stackoverflow, learn basic basic jquery
