### ISSUE TITLE
Send and Recover Status Parameters

### ISSUE THREAD

**Issue by juliocorral** [wenzhixin/bootstrap-table#1693]
Hi!,

Ne1 could help me with this? I'll try to explain my problem...

I need an example of this situation. I have a normal table with some columns with order posibilities, a search field and pagination. Last field of every row has several icons to do some actions (see, edit, add language,..) 
What I need is how to get table status parameters (order, search value, page number,...) and send these values to some urls (see url, edit, url,...) and when I'll return to see the table again I need to recover these status parameters to show the table correctly again (same order, same, page number,...)

Please anyone could write a complete and simple example with this situation.

Thank you in advance and sorry for my terriblo English.

**Comment by dabros** [comment]
@juliocorral - use stackoverflow (search for existing) to see how to use inline action buttons, plenty of examples there of ajax buttons

Regarding status variables, not an issue

http://issues.wenzhixin.net.cn/bootstrap-table/

See how order, pagination and other variables are saved and enforced again after you hit 'refresh', or any action that triggers refresh, including custom calls to `$('#table').bootstrapTable('refresh');`

Each TR is printed with data-index, so you can easily use `$(this).parent('tr').data('index')` or similar code to reference that, or set the table option `uniqueId` value so you can easily use `getRowByUniqueId` and similar functions (see examples, doco and other github issues for very clear demonstations of this).

Then, depending on your action, you could:

EDIT - Just use the `updateRow` or `updateByUniqueId` action with returned data from your edit request, 
DELETE - `removeRow` and `removeByUniqueId` would work here
ANYTHING - any data change can be easily reflected **without** requiring any extra handling, by just calling 'refresh', for client or server side.

http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

**Comment by wenzhixin** [comment]
There are two solutions:

1. Use the `bootstrap-table-cookie` extension: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html

2. Save the params by yourself:
```
queryParams: function (params) {
    savedParams = params;
    return saveParams;
}
```

**Comment by juliocorral** [comment]
Thank you for your answer.

I would like to use second option (save params - restore params) but I
don´t know how to get this params and append them to URL that is invoked
clicking on an icon in one row and how to restore these params when I
return from this url with a back button with parameters send by GET to
return table to its initial state (page, order,...)

Could you show me a simple example of this situation and al least the
Javascript functions to do this. I'm not very good in Javascript by now I'm
learning.

Thank in advance.

2015-11-16 3:20 GMT+01:00 文翼 <notifications@github.com>:

**Comment by dabros** [comment]
@juliocorral - do confirm that you have tested default behaivour and methods, like i described in my post. @wenzhixin solution is for the question you asked, but NOT neccessarily the best for your actual use case.

Focus on the core problem, not the solution.

**Comment by wenzhixin** [comment]
maybe help: http://stackoverflow.com/questions/33693929/remember-page-size-in-bootstrap-table

**Comment by juliocorral** [comment]
Thank you for your help.

Finally I've used the bootstrap-table-cookie extension, but I 've a question... How could I reset the save status? I need when I return to the table from one specific page the cookie save status must be reset and table show the initial status (page 1, no special order, no search text,...)

**Comment by dabros** [comment]
@juliocorral - just look on google for something like "clear cookie" or similar.

There are many options, easiest would be clearing the cookie on that other page (dont worry bout boostrap-table.js itself, as i imagine it easily accessible via other cookie methods, plenty jquery and js out there for doing that)

Other options including picking up where you navigated from, plenty of ways to do that (such as more cookies, session data, ect) but depends entirely on context.

Plenty out there for working with cookies and navigation though, maybe post your solution here if of interest to others, but i imagine the solution nothing direct to do with bootstrap-table.js, though maybe called inside event handler.
