### ISSUE TITLE
data-show-columns="true" table thead multiple-rows colspan bug

### ISSUE THREAD

**Issue by zyz** [wenzhixin/bootstrap-table#1694]
如下表格，上表为原始表格，data-show-columns="true"，th1 not checked，colspan of detail1 not change，colspan of detail1 should minus 1 is 2.
<table style="margin:0;padding:0;"><thead>
<tr><th rowspan="2">Id</th><th colspan="3">detail1</th><th colspan="3">detail2</th></tr>
<tr><th>th1</th><th>th2</th><th>th3</th><th>th4</th><th>th5</th><th>th6</th></tr></thead></tatble>
<table style="margin:0;padding:0;"><thead>
<tr><th rowspan="2">Id</th><th colspan="3">detail1</th><th colspan="3">detail2</th></tr>
<tr><th>th2</th><th>th3</th><th>th4</th><th>th5</th><th>th6</th></tr></thead></tatble>

**Comment by zyz** [comment]
correct results
<table>
<thead>
<tr>
<th rowspan="2">Id</th>
<th colspan="2">detail1</th>
<th colspan="3">detail2</th>
</tr>
<tr>
<th>th2</th>
<th>th3</th>
<th>th4</th>
<th>th5</th>
<th>th6</th>
</tr>
</thead>
</table>

**Comment by chenzhikang** [comment]
?

**Comment by zyz** [comment]
正确结果：th4应该属于detail2，而现在的结果th4位置错了。。。
接下来th3列再隐藏，th4,th5列的位置又会错乱的

**Comment by djhvscf** [comment]
Same #https://github.com/wenzhixin/bootstrap-table/issues/1716 .. Close this issue
