### ISSUE TITLE
Reset sorting

### ISSUE THREAD

**Issue by LiveStalker** [wenzhixin/bootstrap-table#1696]
How I can reset sorting on every columns?

**Comment by hellhoundsx** [comment]
The way i do it is, i destroy the table and call the function that creates the table again

$tabledocs.bootstrapTable('destroy');
createtabledocs();

Since the rest of the options never worked for me.

**Comment by dabros** [comment]
@LiveStalker @hellhoundsx - i dont have a working fiddle with sorting it seems, can one of you please post a jsfiddle with similar use case and include what you using atm.

Im happy to look into it when i get time, im think `refreshOptions` with another step may work.

Also pls confirm if you are both using client or server side-pagination?

With server-side, use queryParam or similar approach i assume - happy to trial either way if you give me fiddle.

Some templates and info here:
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
https://github.com/wenzhixin/bootstrap-table#reporting-issues
