### ISSUE TITLE
Jump from editable field to another.

### ISSUE THREAD

**Issue by erick-chali** [wenzhixin/bootstrap-table#1697]
Let me explain I have 4 cells with editable property, when im finished with one field, I want for the next one in the same row to open so I can countinue editing, can we do something like that here, thanks.

**Comment by wenzhixin** [comment]
You can check the next element and then use `$next.editable('show');` to open it.

**Comment by erick-chali** [comment]
I tried to use what  you are saying but it's not working.

**Comment by dabros** [comment]
@erick-chali 

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
https://github.com/wenzhixin/bootstrap-table#reporting-issues

Please create a fiddle, useful templates at those links, so we can replicate issue and see what you have tried.

Also ALWAYS be more descriptive than "not working". At least assure us that you have hit F12 and see no console errors, and describe expected vs actual output/behaviour.

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/e3nk137y/3744/

**Comment by erick-chali** [comment]
thanks for the reply @wenzhixin
