### ISSUE TITLE
Site off?

### ISSUE THREAD

**Issue by mtsys** [wenzhixin/bootstrap-table#1702]
The site http://bootstrap-table.wenzhixin.net.cn/ is off?

**Comment by wenzhixin** [comment]
The server is disabled :(

**Comment by mtsys** [comment]
Need some help to get online content again?

**Comment by hellhoundsx** [comment]
If you need to get some docs, just use this link:

https://web.archive.org/web/20150908233648/http://bootstrap-table.wenzhixin.net.cn/

**Comment by mtsys** [comment]
Tks

**Comment by djhvscf** [comment]
Thanks... @hellhoundsx
