### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by redzioch** [wenzhixin/bootstrap-table#1704]
Is website down (bootstrap-table.wenzhixin.net.cn)? I can not access it for a few hours. https://currentlydown.com/bootstrap-table.wenzhixin.net.cn

**Comment by hellhoundsx** [comment]
https://github.com/wenzhixin/bootstrap-table/issues/1702

Access the link given on this issue

**Comment by djhvscf** [comment]
Yes, the server is disabled.. Please use this link: https://web.archive.org/web/20150908233426/http://bootstrap-table.wenzhixin.net.cn/
