### ISSUE TITLE
horizontal scrollbar

### ISSUE THREAD

**Issue by pbelmann** [wenzhixin/bootstrap-table#1705]
Hi,

Is there a way to have a horizontal scrollbar on top and on the bottom of the table?

Thanks

**Comment by djhvscf** [comment]
I saw your page: http://metagenomics.github.io/MeRaGENE/ and i think in the mean time you can set the data-height property in order to have a fix header

**Comment by dabros** [comment]
@pbelmann - so you do know there is a horizontal scrollbar, so the question is really **"How to have 2 horizontal scrollbars instead of one, top and bottom"**.

More wordy, but definetly need to make distinction.

If of interest: #1182, #1140, #899

**Comment by wenzhixin** [comment]
Any update?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
