### ISSUE TITLE
Return of Ajax

### ISSUE THREAD

**Issue by mtsys** [wenzhixin/bootstrap-table#1706]
my ajax returns structure below. Its component read the return?

<code>
{
	"usuarios":
	[
		{	
			"UsuarioID":1,
			"Nome":"SISTEMA"
		},
		{
			"UsuarioID":2,
			"Nome":"APP"
		{
			"UsuarioID":3,"Nome":"Marlon Tiedt"
		}
	]
}
</code>

**Comment by mtsys** [comment]
I found a post about putting rows. Ai appears the data.
Where do I find documentation with the data that I return from my ajax for the plugin.

**Comment by dabros** [comment]
@mtsys - i think you looking for `responseHandler`

http://bootstrap-table.wenzhixin.net.cn/documentation/

This is seen in many examples, see http://issues.wenzhixin.net.cn/bootstrap-table/

I seem to be having trouble loading that site atm, but also have this fiddle with example of it: https://jsfiddle.net/dabros/acw4jut6/

That fiddle is showing server side and `responseHandler` is very simple, but see doco for how data should be formatted and pass through the array of rows without extra layer, optionally 'total' if using server side (see doco)

something like this:

```javascript
function responseHandler(data)
{
    if(data.usuarios)
       return {'total':data.usuarios.length,'rows':data.usuarios};
    else
       console.error('error with data return, no "usuarios" index detected ", data);

    return null;
}
```

**Comment by mtsys** [comment]
tks
