### ISSUE TITLE
Website doesnt work

### ISSUE THREAD

**Issue by majky358** [wenzhixin/bootstrap-table#1708]
Hi, a bit outside of code scope, but official website http://wenzhixin.net.cn/, could you do something about it ? Thanks much.

**Comment by weibangtuo** [comment]
Sorry. VPS had down. Provider does not fix the problem.
You can temporarily read docs with md file.
https://github.com/wenzhixin/bootstrap-table/tree/master/docs/_i18n/en/documentation

**Comment by gtrdblt** [comment]
In order to prevent future problems like this one, would it be possible for you to save a static copy of your website on github ? 

Thank you.

**Comment by wenzhixin** [comment]
[Running documentation locally](https://github.com/wenzhixin/bootstrap-table/tree/master/docs)

**Comment by AinSynagoga** [comment]
What's the 'root / directory' I'm supposed to run "jekyll serve" from?  Excuse me, but unfortunately not everyone is familiar with Jekyll or Ruby or anything in that matter, I have to maintain a huge project that utilizes bootstrap table, the documentation site is down, and here I am trying to debug Jekyll just to browse some html, it's giving me a "Error: Undefined method 'read_posts' for class 'Jekyll: Site'".

**Comment by bragma** [comment]
What about changing provider?

**Comment by wenzhixin** [comment]
> Dear wen,
Your server is suspended due to bandwidth limit exceed.
Bandwidth will get reset automatically by start of new month or you can add extra bandwidth now.
Thank you.

Consider to change provider :(

**Comment by alviszh** [comment]
what's your jekyll version?
error occurs "Error: Undefined method 'read_posts' for class 'Jekyll: Site'"
