### ISSUE TITLE
Website with demos down ?

### ISSUE THREAD

**Issue by jdriesen** [wenzhixin/bootstrap-table#1710]
Since 3 days, I can't reach http://bootstrap-table.wenzhixin.net.cn/ anymore ...
Any idea ?

Thanks for your reply,

Johnny

**Comment by innerk** [comment]
i can´t reach also :(

**Comment by rjhoffmann** [comment]
see https://github.com/wenzhixin/bootstrap-table/issues/1708

**Comment by jdriesen** [comment]
Solved. Thanks evrb for the help & the fast replies !

**Comment by fhox36** [comment]
The site is working but there are not some resources

**Comment by innerk** [comment]
yep, i'm looking for js table methods, the link of the examples is down
