### ISSUE TITLE
turkish chars not searched

### ISSUE THREAD

**Issue by tarikogut** [wenzhixin/bootstrap-table#1711]
turkish chars not searched

**Comment by dabros** [comment]
@erick-chali

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
https://github.com/wenzhixin/bootstrap-table#reporting-issues

Please create a fiddle, useful templates at those links, so we can replicate issue and see what you have tried.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
