### ISSUE TITLE
"table export " doesn't work  when collapse row/detaill row is active

### ISSUE THREAD

**Issue by milindyadav91** [wenzhixin/bootstrap-table#1713]

**Comment by djhvscf** [comment]
Can you provide a fiddle, please? @milindyadav91

**Comment by milindyadav91** [comment]
![screenshot from 2015-11-24 15_33_44](https://cloud.githubusercontent.com/assets/13883473/11367677/4430e4a6-92db-11e5-98d4-e2bf1f4ba423.png)
![screenshot from 2015-11-24 15_36_28](https://cloud.githubusercontent.com/assets/13883473/11367678/4433e91c-92db-11e5-9968-165918b76eb8.png)
[tableExport-5.pdf](https://github.com/wenzhixin/bootstrap-table/files/42732/tableExport-5.pdf)
[tableExport-6.pdf](https://github.com/wenzhixin/bootstrap-table/files/42733/tableExport-6.pdf)
In this attachment there are four files. 
1.Working pdf and its screenshot and 
2.other after using collapsing row while i'm using pdf its showing like 'tableEport-6' file.

**Comment by djhvscf** [comment]
Thank for your answer, but also can you include the code that you are using.. Just create a fiddle and copy your code @milindyadav91

**Comment by milindyadav91** [comment]
Try  this example http://issues.wenzhixin.net.cn/bootstrap-table/  after using of collapse row try to download in ms-excel or pdf file. you will also see the same issue. try it 
and I will send fiddle's code in some time.

**Comment by wenzhixin** [comment]
It seems that the extension does not support this feature. @hhurz

**Comment by hhurz** [comment]
I'm not sure if I understand this issue. Collapsed rows will not be exported, because detail rows that are not visible are not part of the html table. For expandend rows I think the tableExport extension is working as purposed. 
Regarding to the "Bootstrap Table Examples" that are mentioned above the extension exports this table
![btz_example](https://cloud.githubusercontent.com/assets/4164372/11531430/1caab04c-98fd-11e5-8977-8b8624e4e9a9.PNG)
to a ms-excel file like this
![bt_export](https://cloud.githubusercontent.com/assets/4164372/11531443/2a58fbae-98fd-11e5-899a-f280fa6388f4.PNG)
Beside the not exportable glyph icons the colspan and rowspan of the xls cells are identical to the cells of the original table.
It would be very helpfull indeed if @milindyadav91 could provide a fiddle example to clarify this issue.

**Comment by wenzhixin** [comment]
Just like @hhurz said, close this issue.

**Comment by pavanbangaloreraju** [comment]
> It seems that the extension does not support this feature. @hhurz

is there any other way to get all the data downloaded in excel file.

**Comment by pavanbangaloreraju** [comment]
> I'm not sure if I understand this issue. Collapsed rows will not be exported, because detail rows that are not visible are not part of the html table. For expandend rows I think the tableExport extension is working as purposed.
> Regarding to the "Bootstrap Table Examples" that are mentioned above the extension exports this table
> ![btz_example](https://cloud.githubusercontent.com/assets/4164372/11531430/1caab04c-98fd-11e5-8977-8b8624e4e9a9.PNG)
> to a ms-excel file like this
> ![bt_export](https://cloud.githubusercontent.com/assets/4164372/11531443/2a58fbae-98fd-11e5-899a-f280fa6388f4.PNG)
> Beside the not exportable glyph icons the colspan and rowspan of the xls cells are identical to the cells of the original table.
> It would be very helpfull indeed if @milindyadav91 could provide a fiddle example to clarify this issue.

is there a way to dowwnload all the data without collapse in excel file ?

**Comment by pavanbangaloreraju** [comment]
> I'm not sure if I understand this issue. Collapsed rows will not be exported, because detail rows that are not visible are not part of the html table. For expandend rows I think the tableExport extension is working as purposed.
> Regarding to the "Bootstrap Table Examples" that are mentioned above the extension exports this table
> ![btz_example](https://cloud.githubusercontent.com/assets/4164372/11531430/1caab04c-98fd-11e5-8977-8b8624e4e9a9.PNG)
> to a ms-excel file like this
> ![bt_export](https://cloud.githubusercontent.com/assets/4164372/11531443/2a58fbae-98fd-11e5-899a-f280fa6388f4.PNG)
> Beside the not exportable glyph icons the colspan and rowspan of the xls cells are identical to the cells of the original table.
> It would be very helpfull indeed if @milindyadav91 could provide a fiddle example to clarify this issue.

is there a way to dowwnload all the data without collapse in excel file ?
