### ISSUE TITLE
Bootstrap table filter control doesn't use sidePagination variable

### ISSUE THREAD

**Issue by pomeh** [wenzhixin/bootstrap-table#1714]
I use Bootstrap table configured with `sidePagination = 'server'`.
I've added Bootstrap table filter control extension, and configured `filterControl` to my columns array.

Because `sidePagination = 'server'`, when I enter a filter in the `input` or `select` fields, I don't want the data to be filtered client side, but instead I would prefer to trigger an AJAX query, with the current filters values.

Bootstrap table search functionnality does nothing when using sidePagination server:

```javascript
// https://github.com/wenzhixin/bootstrap-table/blob/5a5a32acf67f2fef65da91fa72c6a965afa1dfb9/src/bootstrap-table.js#L1089
BootstrapTable.prototype.initSearch = function () {
    var that = this;

    if (this.options.sidePagination !== 'server') {
        var s = this.searchText && this.searchText.toLowerCase();
        var f = $.isEmptyObject(this.filterColumns) ? null : this.filterColumns;

        // Check filter
        this.data = f ? $.grep(this.options.data, function (item, i) {
            // [...]
        }) : this.options.data;

        // [...]
    }
};
```

But Bootstrap table filter control does not read this configuration variable, so the filter is done even when `sidePagination` is set to `server`:

```javascript
// https://github.com/wenzhixin/bootstrap-table/blob/5a5a32acf67f2fef65da91fa72c6a965afa1dfb9/src/extensions/filter-control/bootstrap-table-filter-control.js#L361
BootstrapTable.prototype.initSearch = function () {
    _initSearch.apply(this, Array.prototype.slice.apply(arguments));

    var that = this;
    var fp = $.isEmptyObject(this.filterColumnsPartial) ? null : this.filterColumnsPartial;

    //Check partial column filter
    this.data = fp ? $.grep(this.data, function (item, i) {
        // [...]
    }) : this.data;
};
```

Is it possible to don't trigger the client side filter in a such configuration ?

Thanks for your reply.

**Comment by djhvscf** [comment]
This issue is already fixed. @pomeh

**Comment by pomeh** [comment]
That was a quick fix, thanks for your reply :)

**Comment by pomeh** [comment]
@djhvscf do you know if and when this will be merged into the main codebase and released ? Thanks.

**Comment by djhvscf** [comment]
No, I don't. I'm not sure really because @wenzhixin is the charge of the merge.. @pomeh
