### ISSUE TITLE
data-show-columns="true" table thead multiple-rows rowspan colspan bug 

### ISSUE THREAD

**Issue by zyz** [wenzhixin/bootstrap-table#1716]
<a href="https://github.com/wenzhixin/bootstrap-table/issues/1694">prev</a>
<img src="http://www.iconpng.com/png/glyphish-icons/117-todo.png" align="middle" /> Id<br />
<img src="http://www.iconpng.com/png/woocons1/checkbox-empty.png" align="middle" /> th1<br />
<img src="http://www.iconpng.com/png/glyphish-icons/117-todo.png" align="middle" /> th2<br />
<img src="http://www.iconpng.com/png/glyphish-icons/117-todo.png" align="middle" /> th3<br />
<img src="http://www.iconpng.com/png/glyphish-icons/117-todo.png" align="middle" /> th1<br />
<img src="http://www.iconpng.com/png/glyphish-icons/117-todo.png" align="middle" /> th2<br />
<img src="http://www.iconpng.com/png/glyphish-icons/117-todo.png" align="middle" /> th3<br />
<hr/>
th1,th2,th3 is double, I want is the result of the group or with a different prefix to distinguish
<table>
<thead>
<tr>
<th rowspan="2">Id</th><th colspan="3">detail1</th><th colspan="3">detail2</th>
</tr>
<tr>
<th>th1</th><th>th2</th><th>th3</th>
<th>th1</th><th>th2</th><th>th3</th>
</tr>
</thead>
</table>
th1 of detail1 is not check, Incorrect results: th1 of detail2 is in detail1
<table><thead>
<tr>
<th rowspan="2">Id</th><th colspan="3">detail1</th><th colspan="3">detail2</th>
</tr>
<tr>
<th>th2</th><th>th3</th>
<th>th1</th><th>th2</th><th>th3</th>
</tr>
</thead></table>
however, correct results is
<table>
<thead>
<tr>
<th rowspan="2">Id</th><th colspan="2">detail1</th><th colspan="3">detail2</th>
</tr>
<tr>
<th>th2</th><th>th3</th>
<th>th1</th><th>th2</th><th>th3</th>
</tr>
</thead>
</table>
```

**Comment by wenzhixin** [comment]
Please format the code.

**Comment by djhvscf** [comment]
Any update here.. Remember how to ask for help: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

**Comment by memect** [comment]
Have the same problem here. Any ideas?

**Comment by djhvscf** [comment]
@memect can you provide a fiddle?
