### ISSUE TITLE
Title for check box column 

### ISSUE THREAD

**Issue by skipcheru** [wenzhixin/bootstrap-table#1717]
When i am using <data-field="state" data-checkbox="true" > then the column comes with checkbox icon including the header. Can i keep the check box icons in rows but a title for header ?
I pull data from json file and four rows must be of check boxes (very-competent to does-not-apply).
e.g the Active column in Example https://editor.datatables.net/examples/api/checkbox.html.
json sample:

         
        {
                "id": " 1 ",
                "work-task": " Use of digital device such as computers, scanners, cameras, printers e.t.c",
                "very-competent": "",
                "competent": " ",
                "not-competent": " ",
                "does-not-apply": " "
               
        },

**Comment by djhvscf** [comment]
Please see this fiddle: http://jsfiddle.net/e3nk137y/3669/ there you can find how to implement the feature that you want. @skipcheru
