### ISSUE TITLE
column's width propertity cannot take effect

### ISSUE THREAD

**Issue by Xingtao** [wenzhixin/bootstrap-table#172]
Hi, I would like to set all columns' width as a fixed size, so I set up it via columns option. Here is the code:

        var titleColumns = [];
        for (i = 0; i < 10; i++) {
            titleColumns.push({
                field: i,
                title: i,
                width: 100
            });
        }

I expect the width of each column is equal, but it is not. Any suggestion? Thanks.

**Comment by betonetotbo** [comment]
I'm in the same trouble!

I need to set the exact width for each column, to enable the horizontal bar without losing the columns widths.

**Comment by Muzical84** [comment]
The width attribute is being totally ignored in my table columns.  I can set it to 50 or 100 and nothing changes.

```javascript
//AJAX call then:
$("#honorRollTable").bootstrapTable({
            data:json,
            classes:"table,table-condensed",
            cache:false,
            sortable:false,
            smartDisplay:true,
            cardView:cardView,
            width:"50%",
            pagination:false,
            columns: [{
                field: 'LASTNAME',
                title: 'Recipient',
                width:50,
                formatter:nameFormatter
            },{
                field: 'INSTITUTION',
                title: 'Institution',
                width:50
            }] //end columns
        }); //end bootstrapTable
```

**Comment by wenzhixin** [comment]
Supported percentage now.

**Comment by mickaelroupie** [comment]
I would like to define width for each column but I use the Resizable extension.
If I set width, I cannot drag my columns anymore. 
Is there something to do in order to have the compatibility?

Thank you very much! ;)
