### ISSUE TITLE
http://issues.wenzhixin.net.cn/bootstrap-table/ seems broken.

### ISSUE THREAD

**Issue by RaviH** [wenzhixin/bootstrap-table#1721]
<img width="1440" alt="broken_web_page_layout" src="https://cloud.githubusercontent.com/assets/141136/11320797/24558b66-9063-11e5-82c0-1c09591bf1b1.png">
Hi Wenzhizin,

It seems like http://issues.wenzhixin.net.cn/bootstrap-table/ is broken i.e. the layout is not showing how it normally does where I can browse the examples. I have tried with Chrome, Safari and Firefox on Max Pro OS X El Capitan. Can you please look into it.

Thank you to you and all the contributors of this awesome library!

Ravi

**Comment by djhvscf** [comment]
Yes, we are having some troubles with our websites.. Sorry about that

**Comment by wenzhixin** [comment]
Fixed it.

**Comment by djhvscf** [comment]
It is not working @wenzhixin
