### ISSUE TITLE
Order the table filter control items and align them

### ISSUE THREAD

**Issue by LockTar** [wenzhixin/bootstrap-table#1724]
I'm using the table filter control for filtering column data. 
I have a dutch table with dates in it. I've written a custom sorter so the sorting is working. Can I use that custom sorting function for the filter items in the select filter for the dates? Now the order of the items in the select are in the order as of the table. 

Is it also possible to align the items in the select to the right?

See the following fiddle for an example: http://jsfiddle.net/pbg1zesn/1/

Thanks

**Comment by djhvscf** [comment]
Those are good ideas @LockTar I think it is possible.. let me try to implement that, but remember that any Pull Request is very welcome

**Comment by djhvscf** [comment]
Added the alignment option
See this: http://jsfiddle.net/pbg1zesn/2/ and this is the PR https://github.com/wenzhixin/bootstrap-table/pull/1698

**Comment by LockTar** [comment]
You've already created a change. That's quick. I just asked a question if it was possible. But my question was not really clear. I like your change but I don't want the complete `select` aligned to the right but just the items in it. So the arrow just like normal on the left.

I think the change should be after your last commit on PR #1698:
1. Create extra setting for just the `option`
2. Use the setting when creating the `option` list (see `dir`) attribuut
```javascript
selectControl.append($("<option></option>")
                .attr("value", value)
                .attr("dir", "rtl")
                .text($('<div />').html(text).text()));
```

The result (hard coded the `dir` in the `option`) is then http://jsfiddle.net/pbg1zesn/3/

If you agree, I could try to implement this suggestion. But I quite new to GitHub so I don't really know if you can create a pull request from your pull request...

Thanks

**Comment by djhvscf** [comment]
ok, let me add another option to it... I think we can implement both in our plugin. @LockTar  but if you want to implement the change, go ahead!! :+1:

**Comment by LockTar** [comment]
Sure, I will wait for you to complete. My option is not really important.
