### ISSUE TITLE
Configure pagination and sort

### ISSUE THREAD

**Issue by Knoxvillekm** [wenzhixin/bootstrap-table#1726]
How can I configure pagination for JPARepository response:
```
{
  "content": [],
  "last": true,
  "totalElements": 1,
  "totalPages": 1,
  "size": 20,
  "number": 0,
  "sort": null,
  "numberOfElements": 1,
  "first": true
}
```
I can change only dataField to 'content' for now

And how to change page and sort params in request:
```
?size=10&page=0&sort=field,desc"
```

**Comment by dabros** [comment]
@Knoxvillekm - as stated in Contributing.md and elsewhere, look for existing issues first, and see doco and examples

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker

There are plenty of examples out there affecting requestParam and pagination (display, placement, text strings, requestParam sent AND processed returned data.

`queryParams`, `requestParam`?, `responseHandler`, `ajax` - search for these

for example: #1693, #1549

The examples site also has a number using these options, such as:
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/152.html
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/353.html
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/386.html
http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html
http://issues.wenzhixin.net.cn/bootstrap-table/index.html
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/custom-ajax.html


It isnt clear exactly what changes you needing, but these options cover all possible changes to data sent and recieved from server.

**Comment by wenzhixin** [comment]
I think it is easy to solve your problem use `requestParam` and `responseHandler`:

* handle your response:

> ```
 {
  "content": [],
  "last": true,
  "totalElements": 1,
  "totalPages": 1,
  "size": 20,
  "number": 0,
  "sort": null,
  "numberOfElements": 1,
  "first": true
}
```

```
responseHandler: function (res) {
    return {
        rows: res.content,
        total: res.totalElements
    };
}
```

* handle your request:

>`?size=10&page=0&sort=field,desc"`

```
queryParamsType: '',
queryParams: function (params) {
    return {
        size: params.pageSize, 
        page: params.pageNumber, 
        sort: params.sortName + ',' + params.sortOrder
    };
}
```
