### ISSUE TITLE
Table not refreshing data

### ISSUE THREAD

**Issue by luisapuyen** [wenzhixin/bootstrap-table#1729]
I'm trying to refresh the bootstrapTable after any change, but it doesn't seem to work. No request to the server is sent from it. 

Following instructions seen in other posts, I wrote this:

```javascript
            $table.bootstrapTable('refresh', {
			    url: the_url
			});
```

**Nothing happens**, no error, no request. 
If I try this instead:

```javascript
           $table.bootstrapTable({
				url: the_url
			}).bootstrapTable('load');
```

the request is sent to the server, but the results are not displayed, and instead I get this error:

bootstrap-table.js:2109   **Uncaught TypeError: Cannot read property 'fixedScroll' of undefined**

I downloaded the last Bootstrap Table version this morning.

**Comment by djhvscf** [comment]
ok, please provide a fiddle with yout code.. In the meantime you can use the refreshOptions method @luisapuyen

**Comment by wenzhixin** [comment]
Your response data maybe error format.

**Comment by luisapuyen** [comment]
@djhvscf: I tried to create the jsFiddle but I can't get to set up ajax simulations correctly.

@wenzhixin: This is the format for the first load, which is successful (just an excerpt of it because it's huge since I'm using client pagination):

```
[{"id":"1","provincias_id":"1","cod_municipio":"1","DC":"0","nombre":"Alegr\u00eda-Dulantzi","importe_portes":"15.00","modified_at":"2015-11-23 16:32:46"},{"id":"2","provincias_id":"2","cod_municipio":"1","DC":"9","nombre":"Abengibre","importe_portes":"13.00","modified_at":"2015-11-23 16:32:39"},{"id":"3","provincias_id":"3","cod_municipio":"1","DC":"5","nombre":"Adsubia","importe_portes":"10.50","modified_at":"2015-11-23 16:14:34"},{"id":"4","provincias_id":"4","cod_municipio":"1","DC":"0","nombre":"Abla","importe_portes":"10.50","modified_at":"2015-11-23 16:15:17"},{"id":"5","provincias_id":"5","cod_municipio":"1","DC":"3","nombre":"Adanero","importe_portes":"13.00","modified_at":"2015-11-23 16:16:58"},{"id":"6","provincias_id":"6","cod_municipio":"1","DC":"6","nombre":"Acedera","importe_portes":"8.00","modified_at":"2015-11-23 16:18:38"},{"id":"7","provincias_id":"7","cod_municipio":"1","DC":"2","nombre":"Alar\u00f3","importe_portes":"5.50","modified_at":"2015-11-23 16:22:22"},{"id":"8","provincias_id":"8","cod_municipio":"1","DC":"8","nombre":"Abrera","importe_portes":"5.50","modified_at":"2015-11-23 16:22:21"},{"id":"9","provincias_id":"9","cod_municipio":"1","DC":"1","nombre":"Abajas","importe_portes":"16.00","modified_at":"2015-11-23 16:31:28"},{"id":"10","provincias_id":"10","cod_municipio":"1","DC":"5","nombre":"Abad\u00eda","importe_portes":"16.00","modified_at":"2015-11-23 16:31:29"}]
```

And this one is the result gotten the second time if I use the load method (as I said, the refresh method didn't even send any request):

```
[{"id":"2","provincias_id":"2","cod_municipio":"1","DC":"9","nombre":"Abengibre","importe_portes":"13.00","modified_at":"2015-11-23 16:32:39"},{"id":"53","provincias_id":"2","cod_municipio":"2","DC":"4","nombre":"Alatoz","importe_portes":"16.00","modified_at":"2015-11-23 16:31:33"},{"id":"100","provincias_id":"2","cod_municipio":"3","DC":"0","nombre":"Albacete","importe_portes":"16.00","modified_at":"2015-11-23 16:23:54"}]
```

The only difference I've seen between them is that in Chrome Dev Tools the second one is displayed as a one line string in the response tab, whilst the first one is displayed each object in a different line. But in the preview tab both are parsed correctly.

**Comment by dabros** [comment]
@luisapuyen - for fiddles, some info at first link, and example of ajax at second

https://github.com/wenzhixin/bootstrap-table#reporting-issues
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Of course, that doesnt neccessarily mimic 'your' own data, if the data is the issue, but you put your code in the fiddle and comment out what doesnt apply, seeing if your ajax approach works with different data source.

Any extra `responseHandler` or `queryParam` or ect. just comment out with note saying what it did/why it needed.

**Comment by wenzhixin** [comment]
it seems that the table has sent a request after you use refresh method, but cause an error. You can check out our example http://issues.wenzhixin.net.cn/bootstrap-table/#issues/137.html
