### ISSUE TITLE
'resetSearch' method... when data-search="false"

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1730]
$tbl.bootstrapTable('resetSearch', 'text to search');

is working when search box is visible (i.e. data-search="true")

when it is invisible... (i.e. data-search="false"), can it be made to work too..? thanks

**Comment by djhvscf** [comment]
Can we know why will you use the "resetSearch" method when the data-search is set to false?? This method is being used like that because if you don't set the data-search to true we are supposing that you will search nothing

**Comment by joomlaA1** [comment]
i use a searchbox (where i use the method resetSearch) for the inbox drafts and sent...

it is placed on the top part... like this...

{title:Inbox, Drafts, or Sent}                      {searchbox}
-----------------------------------------------------------------------
{marking-refresh-more}          {pagi detail}{pagination}
{                               main table                                   }

like this bootsnipp: http://bootsnipp.com/snippets/7Qybl

thanks

**Comment by joomlaA1** [comment]
i use a searchbox (where i use the method resetSearch) for the inbox drafts and sent...

it is placed on the top part... like this...{}

{title:Inbox, Drafts, or Sent}                      {searchbox}
-----------------------------------------------------------------------
{marking-refresh-more}          {pagi detail}{pagination}
{                               main table                                   }

like this bootsnipp: http://bootsnipp.com/snippets/7Qybl

thanks

**Comment by dabros** [comment]
@joomlaA1 - if you make your toolbar items, such as search, then look at this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

That grabs all inputs in the custom toolbar and submits as part of data-request. Wouldnt be hard to use that basic concept inside a `queryParam` or similar, and just send blank search field content through.

And we need actual fiddle of your code if we are to help you properly.

**Comment by djhvscf** [comment]
ok, let me think about it

**Comment by joomlaA1** [comment]
thanks!!!!

**Comment by wenzhixin** [comment]
Please use custom toolbar just like @dabros said.

**Comment by joomlaA1** [comment]
ok...
