### ISSUE TITLE
Hiding Grouped Column desalign all table columns

### ISSUE THREAD

**Issue by binho500** [wenzhixin/bootstrap-table#1731]
After creating a table with grouped columns, when hiding one of the group columns, the table loses all it's column alignment.

Here are the Images:
![table-bug](https://cloud.githubusercontent.com/assets/15995385/11361360/afd102cc-9295-11e5-94f6-bee9fe171366.png)

And here's the Fiddle where I replicate the error: 
https://jsfiddle.net/binho500/Lfamt3zu/2/

**Comment by binho500** [comment]
Are you guys going to fix this? Are you still doing development in this project?
Thank you!

**Comment by AkramKamal** [comment]
Hello,

I fixed this issue, please see this Fiddle https://jsfiddle.net/hbpn3tbc/
You will see my code after the word "//My code started here"

Thanks

**Comment by binho500** [comment]
It works perfectly.
Thank you very much for your effort.

**Comment by wenzhixin** [comment]
can you help to create a PR? @AkramKamal

**Comment by AkramKamal** [comment]
You are welcome @binho500

**Comment by AkramKamal** [comment]
What you mean by "PR" @wenzhixin

**Comment by wenzhixin** [comment]
Pull request: https://help.github.com/articles/using-pull-requests/

**Comment by BladeChang** [comment]
@AkramKamal I use your code but i still have some problem with hide group column
I got 4 group columns when I load data into  table and  when hide the last child column of last  group
the data of next ungroup column will push into the column I hid and the column dose't hide just lost header

**Comment by AkramKamal** [comment]
@BladeChang Please provide working demo as https://jsfiddle.net/hbpn3tbc/

**Comment by BladeChang** [comment]
@AkramKamal like this [https://jsfiddle.net/BladeChang/hbpn3tbc/25/](url)
