### ISSUE TITLE
regular table

### ISSUE THREAD

**Issue by mtsys** [wenzhixin/bootstrap-table#1732]
No way you have the same html, a normal table and a table of bootstrap-table type. Today all my elements in the table are bootstrap standard-table.

**Comment by djhvscf** [comment]
I'm not sure what you are asking for.. Please, explain a little bit more @mtsys

**Comment by mtsys** [comment]
Let improve the question.
I do not know if it's a setup, but now after loading the bootstrap-table, all my tables, are at the component standard. However, I have the same html, tables in bootstrap-table and standard tables with being pure html.

How do I have a type table html without the bootstrap-table component transform it? @djhvscf

**Comment by dabros** [comment]
@mtsys - we need a fiddle to see what your talking about, as still very unclear

https://github.com/wenzhixin/bootstrap-table#reporting-issues
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Also do see the many examples, which show bootstrap-tables defined from pure html, and others showing a mixture of js, html and json data url (use 'view source in github' in top right)

http://issues.wenzhixin.net.cn/bootstrap-table/
http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-html.html
http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-data.html

Beyond that, never heard of anyone unable to follow the http://bootstrap-table.wenzhixin.net.cn/getting-started/ guide

**Comment by mtsys** [comment]
tks
