### ISSUE TITLE
Add Button in row

### ISSUE THREAD

**Issue by mtsys** [wenzhixin/bootstrap-table#1733]
How do I get the line values and create a button with custom html?

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/ 
There you can see the **item operate** column

**Comment by mtsys** [comment]
the formatter is only available by jQuery or can do so:

<code><th data-field="Login" data-sortable="true" data-formatter="operateformatter">Login</th></code>

@djhvscf

**Comment by mtsys** [comment]
tks
