### ISSUE TITLE
Can I switch the locale does not need to destory table ?

### ISSUE THREAD

**Issue by jewway** [wenzhixin/bootstrap-table#1738]
Have any way to change locale then refresh the DOM  immediately ?

![image](https://cloud.githubusercontent.com/assets/3501899/11418689/26ca2d9a-945d-11e5-8139-ba85158a323a.png)

**Comment by djhvscf** [comment]
Can you explain a little bit more? @jewway

**Comment by jewway** [comment]
I mean when I want to switch languages dynamically ,  i need to destroy the grid then reconstruction it.
Has any API to change grid display languages dynamically ?

**Comment by mastermike14** [comment]
I would suggest sending a locale param to the server to get the translated content or check the user's locale via cookie or whatever server side before sending

**Comment by archerchiu** [comment]
Hi,

As the locale setting is 'zh-CN' ...
@jewway seems wanna: 
`
$('table').bootstrapTable({locale:'en-US'});
`
could be change locale to 'en-US' automatically, instead of destroy table and reload the table again.

**Comment by chenghsuan** [comment]
Hi, there~
I have the same problem and trying to achieve this goal.
Maybe you can try  as following :

    if ($.inArray($.fn.bootstrapTable.methods, 'changeLocale') == -1) {
      $.fn.bootstrapTable.methods.push('changeLocale');
    }

    $.fn.bootstrapTable.Constructor.prototype.changeLocale = function (obj) {
      var locale = obj.locale;
      this.options.locale = locale;
      $.fn.bootstrapTable({locale: locale});
      $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales[locale]);
      $.extend(this.options, $.fn.bootstrapTable.locales[locale]);
      this.initToolbar();
      this.initPagination();
    };

**Comment by wenzhixin** [comment]
This extension: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/i18n-enhance.html may help.
