### ISSUE TITLE
Loosing cell borders

### ISSUE THREAD

**Issue by alexz707** [wenzhixin/bootstrap-table#1740]
hi! 
First of all thanks for your great work!
I have a problem when I have hidden some columns and asigned some alignments (center, left, right).
It seems ok when there is no result but as soon as there are raws to be displayed some borders will disappear:
It's only on firefox on mac... problem doesn't exists on safari...

See screenshot
![bildschirmfoto 2015-11-26 um 13 56 42](https://cloud.githubusercontent.com/assets/562324/11423672/b34f83da-9446-11e5-9d9a-ee2f8f75ee33.png)

**Comment by dabros** [comment]
ref: #1609, maybe related

**Comment by wenzhixin** [comment]
Testing with the latest version in the latest Firefox, there is no such problem, close this issue.
