### ISSUE TITLE
use the hideRow function must be two parameter

### ISSUE THREAD

**Issue by wangy09** [wenzhixin/bootstrap-table#1742]
use the hideRow function must be two parameter,index and uniqueId  ,but I just want to use one parameter such as index or uniqueId。if I use one of them,it can not hide the row.Finally I found a bug in the bootstrap-table.js  2269 line,cange ' if (!params.hasOwnProperty('index') || !params.hasOwnProperty('uniqueId'))' to ' if (!params.hasOwnProperty('index') && !params.hasOwnProperty('uniqueId'))' ,success!

**Comment by dabros** [comment]
I can confirm the example at http://issues.wenzhixin.net.cn/bootstrap-table/#methods/showRow-hideRow.html appears to show this bug too, but im sure it didnt in the past

**Comment by dabros** [comment]
@wenzhixin, @djhvscf - i am somewhat concerned that we referance variable not in current version.

Please see my notes on the PR #1744

thanks

**Comment by wenzhixin** [comment]
Merged.
