### ISSUE TITLE
rowspan and colspan在show column时，出现移位问题

### ISSUE THREAD

**Issue by bmrainc** [wenzhixin/bootstrap-table#1748]
点击取消x之后，如下图：
![image](https://cloud.githubusercontent.com/assets/7332588/11444819/072061f2-9562-11e5-983d-ac6bca2bac35.png)
后面的把前面的顶掉了，这是bug？
能否帮忙解决下，或者设置x不允许取消？

**Comment by dabros** [comment]
@bmrainc - I cant read chinese sorry, but i also cant recreate this

http://issues.wenzhixin.net.cn/bootstrap-table/

Please create a fiddle to show this happening, so we can confirm it

https://github.com/wenzhixin/bootstrap-table#reporting-issues
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

thanks

**Comment by wenzhixin** [comment]
提供下jsfiddle，或者你可以设置 switchable 属性

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/index.html 例子并没有出现你说的问题

**Comment by wenzhixin** [comment]
超过7天没有回复，关闭该问题。

**Comment by yangyachao** [comment]
![default](https://cloud.githubusercontent.com/assets/4145688/14874084/606f7a28-0d2f-11e6-983d-d38131fc5d39.png)

**Comment by yangyachao** [comment]
当合并列在其他列前面时出现此问题，需要重新计算合并列colspan
![1](https://cloud.githubusercontent.com/assets/4145688/14874148/feb7c370-0d2f-11e6-80da-0130e7fc9d4d.png)

**Comment by bmrainc** [comment]
@yangyachao 没错，我就是这个问题，如何重新计算合并列colpan

**Comment by yangyachao** [comment]
具体请看＃2230

https://github.com/wenzhixin/bootstrap-table/issues/2230
