### ISSUE TITLE
filterControl + searchbox + cookies = bug

### ISSUE THREAD

**Issue by ioctaptceb** [wenzhixin/bootstrap-table#1749]
issue: when inputing a filter into a filterControl input box, then refreshing the page, the search box is populated with the same info as the last entered filterControl input. Sometimes this breakes the filtering, either giving too many results or too few.

cause: filterControl uses onSearch the same way that the search input box uses it. 
https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/cookie/bootstrap-table-cookie.js#L321
the cookie is reset every time this function is run.

**Comment by djhvscf** [comment]
I'm not sure that I'm understanding this issue.. Provide a fiddle in order to see the bug. @ioctaptceb

**Comment by ioctaptceb** [comment]
you can see the issue here:
http://jsfiddle.net/fnvk8xwa/3/

to see the issue, in the second column titled 'stars' type in the following string: 'boot'
now, you should see that the table has no elements in the star column with the text 'boot' since the column has only numbers

now reload the page
you will see that boot is searched for in all columns

**Comment by wenzhixin** [comment]
Merged
