### ISSUE TITLE
How to get data on table list under list 

### ISSUE THREAD

**Issue by alok12p74** [wenzhixin/bootstrap-table#1755]
i.e. my json like
[{"name":"alok","award":[{"name":"A"},{"name":"B"}},{"name":"Ashish","award":[{"name":"C"},{"name":"D"}},]

how to show Award name on table

**Comment by dabros** [comment]
@alok12p74 - `formatter` http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

http://issues.wenzhixin.net.cn/bootstrap-table/#options/format.html

Just use one of the passed objects and return the sub-index you want, or whatever formatted string you wanted from it.

One of my fiddles as example: http://jsfiddle.net/rg93rgkL/3/

There are numerous other examples, both in examples web and here (remove 'is:open' filter then do search)
