### ISSUE TITLE
getItemField BUG

### ISSUE THREAD

**Issue by guoai2015** [wenzhixin/bootstrap-table#1757]
var getItemField = function (item, field) {
        var value = item;
        if (typeof field !== 'string' || item.hasOwnProperty(field)) {
            return item[field];
        }
        var props = field.split('.');
        for (var p in props) {
        	if(value != null) {//这里必须判断一下value是否为null，否则将会出错！It is necessary to determine whether the value is null, otherwise it will go wrong!
        		value = value[props[p]];
        	}
        }
        return value;
    };

**Comment by dabros** [comment]
@guoai2015 

PR are always welcome :)

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

**Comment by wenzhixin** [comment]
请提供 jsfiddle 例子

**Comment by wenzhixin** [comment]
验证了下，item 不应该为 null 的情况，例如不支持这种 `data = [{...}, null]`。

**Comment by guoai2015** [comment]
data = [{name: 'Jack', age: 30, son:{name: 'Tom', age: 5}},
           {name: 'Lucy', age: 28}]
像这样的，第一个对象有son，而第二个没有。

**Comment by wenzhixin** [comment]
OK, 已修复： https://github.com/wenzhixin/bootstrap-table/commit/b0f0354e61d3be7a3528d18be187914b3aa209d7

http://jsfiddle.net/wenyi/e3nk137y/3742/
