### ISSUE TITLE
建议增加列默认值

### ISSUE THREAD

**Issue by guoai2015** [wenzhixin/bootstrap-table#1758]
目前仅有一个Table options的undefinedText属性，定义了全局的undefined默认文本，建议增加Column options的undefinedText属性，针对单个列设置默认文本。

Currently only a ‘Table options’ undefinedText property, the definition of the global undefined default text, it is recommended to increase the options undefinedText Column property, set the default text for a single column.

第1534、1535行
value = typeof value === 'undefined' || value === null ?
                        that.options.undefinedText : value;
改为：
value = typeof value === 'undefined' || value === null ?
                    	column.defaultContent ? column.defaultContent : that.options.undefinedText : value;
这样
<th data-field="testnull" data-default-content="空">测试空值</th>

**Comment by wenzhixin** [comment]
欢迎提交 pull request

**Comment by wenzhixin** [comment]
暂时不考虑，你可以通过 formatter 来实现

**Comment by cxgreat2014** [comment]
现在还是通过formatter来实现吗？
