### ISSUE TITLE
CRUD

### ISSUE THREAD

**Issue by batistellabr** [wenzhixin/bootstrap-table#1759]
Is there any crud feature on the component?

For example, dynamically generate an insert form for a new row?

Something like we have in http://www.jtable.org/

**Comment by wenzhixin** [comment]
There is a CRUD example: https://github.com/wenzhixin/bootstrap-table-examples/tree/master/crud

**Comment by batistellabr** [comment]
Thank you.
I had already seen that. But, in this example I have to repeat the table definition in order to create the add modal form. Why not generate this form dynamically based on information about the table?

**Comment by wenzhixin** [comment]
Maybe you can add a table extension to do this, any pull request is welcome.

**Comment by batistellabr** [comment]
Yes, I was trying to see if the idea makes sense for the project.

**Comment by dabros** [comment]
ref: http://stackoverflow.com/questions/12905849/generating-html-forms-from-json-or-xml-feed-using-jquery

**Comment by dabros** [comment]
Interesting idea, but the flaw is that all the ways of doing this (including jtable) seem to rely on a more complex json object. 

In CRUD example above, you arnt repeating table definition, at least no more than you would for jtable or other plugins, exception being that is an explicit field, not dynamic.

I guess column options could be easily expanded to accomadate dynamic forms, though it would be almost as much effort as just using any other dynamic plugin or creating simple form.

That said, there is advantage to having it in same place, so still interesting idea, and not overly difficult as such, given crud type features already present and good examples of creating dynamic ui in pagination, toolbar, ect.

More complex usages like filtered select dropdowns could be handled same way as formatters or ect, pass in 'currentItem' object and 'field', return options array.

**PR** is always welcome, likely as an extension though given its not at all core to most users approach.

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

**Comment by wenzhixin** [comment]
ref #1606, close this one.
