### ISSUE TITLE
希望添加column可拖动

### ISSUE THREAD

**Issue by xiaowei1118** [wenzhixin/bootstrap-table#1761]
添加column可拖动，拖动调整column的宽度

**Comment by wenzhixin** [comment]
支持的：
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-columns.html
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-rows.html
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/resizable.html

**Comment by dishiyicijinqiu** [comment]
@xiaowei1118 当 reorder-rows 与 reorder-columns 同时使用时，会有bug，如果先引用reorder-columns则reorder-columns会失效，否则反之

**Comment by 123liuyu123** [comment]
> @ xiaowei1118当reorder-rows与reorder-columns同时使用时，会有bug，如果先引用reorder-columns则reorder-columns会员失效，否则反之
Hello, I have the same problem. Do you have any solution
