### ISSUE TITLE
boostrap-table-reorder-rows not working if data-url attribute not present

### ISSUE THREAD

**Issue by rubensa** [wenzhixin/bootstrap-table#1763]
I'm trying to use boostrap-table-reorder-rows extension on an already fully loaded table (with tbody content).  I found that the extension doesn't work If I don't specify the table data-url attribute (I don't need it as all my data is already in the table).

It seems that the extension only woks if data is retrieved from server (via AJAX) after loading.

I think that I should be able to use the extension for any data source (including existing table tbody content).

**Comment by wenzhixin** [comment]
Please provide a jsFiddle to show the problem: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md.

**Comment by rubensa** [comment]
Not working on version 1.8.1:
http://jsfiddle.net/rubensa/spt7L8p6

Working on master version:
http://jsfiddle.net/rubensa/spt7L8p6/1/

**Comment by wenzhixin** [comment]
OK, please update to the latest version.
