### ISSUE TITLE
composer Package

### ISSUE THREAD

**Issue by liKe2k1** [wenzhixin/bootstrap-table#1767]
Please provide a composer bundle.

**Comment by wenzhixin** [comment]
sorry I don't know what you mean?

**Comment by liKe2k1** [comment]
watch this 
https://github.com/liKe2k1/bootstrap-table/blob/master/composer.json

**Comment by wenzhixin** [comment]
Can you provide more information about composer?

**Comment by changhuapeng** [comment]
Composer is a dependency/package manager for PHP. You can see [Packagist](https://packagist.org/) for its main repository.

**Comment by wenzhixin** [comment]
@liKe2k1 can you help to create a pull request to the develop branch?

And update:
> "description": An extended Bootstrap table with radio, checkbox, sort, pagination, and other added features.

> "twitter/bootstrap": ">=2.3.0"

**Comment by liKe2k1** [comment]
Done :)

**Comment by wenzhixin** [comment]
Merged in develop branch.
