### ISSUE TITLE
join data-field

### ISSUE THREAD

**Issue by rajapulau** [wenzhixin/bootstrap-table#177]
its possible to join multi data like
example in javascrip = year+id+name

maybe data-field can handle that? 
<th data-field="year">Year</th>

**Comment by omatic-hacker** [comment]
Link don't work, is there any example for Multiple Fields in Column, using js or data-field ? Thanks.

**Comment by cereblanco** [comment]
Broken link.

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/177.html

**Comment by cereblanco** [comment]
Thank you.

**Comment by rmarzocchi84** [comment]
I try it but if I have more than one row it show me always the value of the first row

**Comment by wenzhixin** [comment]
@rmarzocchi84 
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by rmarzocchi84** [comment]
Sorry, the problem is due to my mistake and not to bootstrap table library. In fact I use row.xxx in a modal panel which need to change name 

`<button` type="button" class="btn btn-info" data-toggle="modal" data-target="#myMap'+value+'"><i class="fas fa-map-marked-alt"></i></button> \
    <div class="modal fade" id="myMap'+value+'" role="dialog"> \
    <div class="modal-dialog"> \
      <div class="modal-content">\
        <div class="modal-header">\
          <button type="button" class="close" data-dismiss="modal">&times;</button>\
          <h4 class="modal-title">Anteprima segnalazione '+value+'</h4>\
        </div>\
        <div class="modal-body">\
        <iframe class="embed-responsive-item" style="width:100%; padding-top:0%; height:600px;" src="./mappa_leaflet.php#17/'+row.lat +'/'+row.lon +'"></iframe>\
        </div>\
        \
      </div>\
    </div>\
  </div>\
</div>`
