### ISSUE TITLE
Use the edit table in the tab page, enter no effect and refresh the table after the table has been edited.

### ISSUE THREAD

**Issue by wangy09** [wenzhixin/bootstrap-table#1770]
Use the edit table in the tab page, enter no effect and refresh the table after the table has been edited.How to solve this problem？

**Comment by wenzhixin** [comment]
Please provide a jsFiddle: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports

**Comment by wangy09** [comment]
I have solved it, thank you.
