### ISSUE TITLE
If boostrap-table-reorder-rows extension is present but not used, bootstrap-table does not work

### ISSUE THREAD

**Issue by rubensa** [wenzhixin/bootstrap-table#1771]
If you include extension JS and CSS but you don't use (or set data-reorderable-rows="false") the table doesn't render right (It worked with 1.8.3 but not working with 1.9.1 or master).

**Comment by rubensa** [comment]
Working on version 1.8.1:
http://jsfiddle.net/rubensa/u80hgd7q/

Not working on master version (also tried with 1.9.1):
http://jsfiddle.net/rubensa/u80hgd7q/1/

**Comment by wenzhixin** [comment]
fixed in v1.10.0
