### ISSUE TITLE
Position change of columns

### ISSUE THREAD

**Issue by binottoeduardo** [wenzhixin/bootstrap-table#1772]
Hi, sorry my english...

I need change position columns.

Example: 

Before
ID | Name | Year

After 
ID | Year | Name

Graciously, Binotto

**Comment by wenzhixin** [comment]
You can use our extension: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-columns.html

**Comment by binottoeduardo** [comment]
thank you so much.
