### ISSUE TITLE
How can I show data-showLoading in extension: filter-control?

### ISSUE THREAD

**Issue by maltrics** [wenzhixin/bootstrap-table#1773]
I use extension filter-control , I have a table with 4000 rows, when I search the data with different columns ,  it didn't show the "Loading data wait...."  and the UI will make user wait for a long time.

the data-source is from data-url "aaa/bbb" , when the page load first time ,it will show "Loading data, wait...."  only when I use filter-control , it didn't show.

In the extesion filter-control,  the data is small, I test with a big data, it didn't not show either, how can I make the showLoading function work if I use filter-control extension?  Please give me some adviese.

**Comment by maltrics** [comment]
can any body help me for this?

**Comment by maltrics** [comment]
can any body help me for this, when the data is huge ,seems it is better to use back-ground paging rather than read a bunch of data to the RAM at one time

**Comment by wenzhixin** [comment]
I think you can use `server` side pagination to solve your problem.
