### ISSUE TITLE
How to determine whether a row is selected？

### ISSUE THREAD

**Issue by wangy09** [wenzhixin/bootstrap-table#1774]
How to determine whether a line is selected?Is there such a function?

**Comment by wenzhixin** [comment]
`var selectedRows = $table.bootstrapTable('getSelections');`

**Comment by wangy09** [comment]
You don't understand what I mean, I mean, how to determine whether a line is selected, such as the index for 0

**Comment by wenzhixin** [comment]
$table.bootstrapTable('getData')[0].state

**Comment by wangy09** [comment]
Thank you very much.
