### ISSUE TITLE
When there is no radio or checkbox, whether to select the row?

### ISSUE THREAD

**Issue by wangy09** [wenzhixin/bootstrap-table#1776]
When there is no radio or checkbox, whether to select the row?Why not have these, I can not get the selected row, When I clicked and did not select the row?

**Comment by wenzhixin** [comment]
This example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/563.html maybe help.

**Comment by wangy09** [comment]
I have tried this, this only changed the color, when I use $('#table').BootstrapTable ('getSelections'); and can not get any

**Comment by dabros** [comment]
@wangy09 - then we need a fiddle to replicate this, as ive never heard of `getSelections` not working, and cant replicate using demos.

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
In this case, you need to use:
```
function getSelectedRow() {
    var $table = $('#table');
    var index = $table.find('tr.success').data('index');
    return $table.bootstrapTable('getData')[index];
}
```

Working example: http://jsfiddle.net/wenyi/e3nk137y/3814/

**Comment by kimaina** [comment]
can we incooperate this feature as a boot-strap-table control option? such that we can enable row selection like this:
````
<table id="table" data-toggle="table" data-toolbar=".toolbar" data-selectable-highlight="True"
</table>````

**Comment by wenzhixin** [comment]
@kimaina any pull request is welcome:)

**Comment by dabros** [comment]
@kimaina - highlights have been discussed before, i even had something like this in custom mod i made for prototype project a while ago (#725, http://jsfiddle.net/dabros/z8bL5fg0/) but that approach is bundled with a bunch of other stuff and i never polished as project was changed to desktop app.

Im guessing what you want is a highlight effect on checked rows, so just `$.toggleClass` in check/uncheck methods should work fine, but do see that fiddle if you want to use `click-row` as opposed to checkboxes/radio column. 

The main issue if no checkbox/select is `maintainSelected` type issue, my fiddle is off early code and is fairly involved, see #1782 and issues linked in there, maybe relateable code.

If you find clean way to do this, then **PR** are always welcome :)

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md
