### ISSUE TITLE
Empty field

### ISSUE THREAD

**Issue by gustavomacedo** [wenzhixin/bootstrap-table#1777]
How can I order columns when cells value is empty?

Example:

<table>
<thead>
<tr>
<th>Website<th>
<th>Position<th>
</tr>
</thead>
<tbody>
<tr>
<td>Website 01<td>
<td>5<td>
</tr>
<tr>
<td>Website 02<td>
<td>9<td>
</tr>
<tr>
<td>Website 03<td>
<td> <td>
</tr>
<tr>
<td>Website 04<td>
<td>1<td>
</tr>
<tr>
<td>Website 05<td>
<td> <td>
</tr>
<tr>
<td>Website 06<td>
<td>7<td>
</tr>

</tbody>
</table>

Results:
ASC: (empty field), (empty field), 1, 5, 7, 9
Desc: 9, 7, 5, 1, (empty field), (empty field)

Desired results:
ASC: 1, 5, 7, 9, (empty field), (empty field)
Desc: 9, 7, 5, 1, (empty field), (empty field)

Could anyone help me pls?

**Comment by dabros** [comment]
@gustavomacedo 

http://issues.wenzhixin.net.cn/bootstrap-table/#options/basic-sort.html
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-sort.html

You can click 'see source in github' in top right to see exactly what the source code is.

If you do need help still, then we need fiddle please: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Then say exactly what 'current behaivour' vs 'expected behaivour' is.

It uses native sorting, as far as im aware, so make that fiddle and explain exactly how this doesnt suit you if that is the case, in clear detail.

But first follow those demos and setup basic sorting, passing in custom sorter if that doesnt suit you.

**Comment by wenzhixin** [comment]
Same with: 1373, ref #1765
