### ISSUE TITLE
How to get value of a column whem column is a select 

### ISSUE THREAD

**Issue by juliocorral** [wenzhixin/bootstrap-table#1779]
Hi,

I have a table but one of the columns is a select field to select language. I need to get the select value of the selected row previously to send to other page using "operateEvents" clicking over an icon.

I've tried with operateEvents and row.<name field>.value but is undefined.

Ne1 could help me please? Thank you in advance.

**Comment by dabros** [comment]
@juliocorral - we need a fiddle if we are to help you

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
There is an example: http://issues.wenzhixin.net.cn/bootstrap-table/index.html

```
    window.operateEvents = {
        'click .like': function (e, value, row, index) {
            alert('You click like action, row: ' + JSON.stringify(row));
        },
        'click .remove': function (e, value, row, index) {
            $table.bootstrapTable('remove', {
                field: 'id',
                values: [row.id]
            });
        }
    };
```
