### ISSUE TITLE
pagination from html data

### ISSUE THREAD

**Issue by safiboss** [wenzhixin/bootstrap-table#1780]
Hello!

I would like to know if it is possible to do pagination with this plugin from html data or it is compulsary to pass a json url to the plugin?

If it is possible some kind of guidance would be awesome. I was able to find any.

Thank you in advance.

**Comment by dabros** [comment]
@safiboss - Yes, very simple to prove, just set data-page-size on any sized example, such as the table from data fiddle or demo

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Here is a fork of that fiddle proving it: http://jsfiddle.net/dabros/xqjucjt1/

**Comment by wenzhixin** [comment]
Example here: http://jsfiddle.net/wenyi/e3nk137y/3781/

**Comment by wenzhixin** [comment]
ref: #1765

**Comment by safiboss** [comment]
Thank you!! Hope this question helps future users
