### ISSUE TITLE
Using events...

### ISSUE THREAD

**Issue by aducom** [wenzhixin/bootstrap-table#1785]
The events section on the bootstrap-table website is gone so I just tried, but no luck so far. 
I want to capture the onclickrow event. I have a table like this:

      <table id="id_main_dbgrid_1" name="main_dbgrid_1" data-toggle="table" data-url="./main.php?component=main_dbgrid_1" data-cache="true" data-height="100%" data-search="true" data-show-columns="true" data-show-refresh="true" data-pagination="true" data-side-pagination="server" data-page-list="[5, 10, 20, 50, 100, 250]" data-page-size="1" style="background-color:rgb(204,204,204);">
        <thead>
        <tr style="background-color:rgb(104,104,104);">
            <th data-field="naw_nr" data-searchable="true">nr</th>
            <th data-field="naw_naam" data-searchable="true">naam</th>
            <th data-field="naw_adres" data-searchable="true">adres</th>
            <th data-field="naw_woonplaats" data-searchable="true">woonplaats</th>
        </tr>
       </thead>
      </table>

I applied the following javascript:

        $("#id_main_dbgrid_1").onClickRow(function(row, $data) {
          var str='';
          procbutton(str+'&cmd=first');
        });         

This doesn't get triggered. Other events in the same html like buttons onclick do work, so I must be doing something wrong. Besides that, the grid is working properly.                                     
Can anybody point me what I'm doing wrong here?

**Comment by dabros** [comment]
@aducom - no idea what you mean by 'gone', though there were some website issues a short while back they got fixed fairly quickly

http://bootstrap-table.wenzhixin.net.cn/documentation/#events
http://issues.wenzhixin.net.cn/bootstrap-table/index.html

That example shows how to capture any bootstrap table event, and ample other resources in stackoverflow and here for specific code, as well as old jsfiddle site http://bootstrap-table.wenzhixin.net.cn/examples/#events, which shows pretty much same thing as hitting 'see source in github' in top right of examples site would do.

**Comment by aducom** [comment]
Tnx, for the answer. There are different ways to setup an event. The  $('#eventsTable').on('all.bs.table', function (e, name, args) is one example. But I'm using another approach that works fine for any bootstrap component except the grid. I was wondering why.

**Comment by dabros** [comment]
@aducom - hit F12 and i will bet you see message saying onClickRow doesnt exist

Always debug your code by keeping `console` open and if needed adding breakpoints in `source` (chrome, but comparable in all modern browsers)

See the doco again, and that the `.on('all.bs.table', ` is just catchall, specific handlers adding using syntax seen in *jquery events* column of that doco table.

**Comment by wenzhixin** [comment]
@aducom, you use the event in a wrong way, the correct way is:
```
$("#id_main_dbgrid_1").bootstrapTable({
    onClickRow: function(row, $data) {
      var str='';
      procbutton(str+'&cmd=first');
    })
});
```
or:
```
$table.on('click-row.bs.table', function (e, row) {
    ...
});
```

**Comment by wenzhixin** [comment]
Updated the docs here: https://github.com/wenzhixin/bootstrap-table/blob/develop/docs/_i18n/en/documentation/events.md

**Comment by aducom** [comment]
Tnx for your correction and update docs. It's a great component.
