### ISSUE TITLE
Fixed height header lines don't line up in IE

### ISSUE THREAD

**Issue by darzzydarzz** [wenzhixin/bootstrap-table#1786]
Having issues with fixed height table in IE9+ and Edge (Chrome and FF are ok, havent checked iE8) where the header column lines don't always line up with table column lines. 

fiddle here: http://jsfiddle.net/oLp3gm04/1/

![image](https://cloud.githubusercontent.com/assets/16215431/11671542/48593942-9e5d-11e5-8e6f-a5376855baaa.png)

commenting out this bootstrap table js code seems to fix the issue but not sure what else this will break??? 

that.$header_.find(sprintf('th[data-field="%s"]', visibleFields[index]))
.find('.fht-cell').width($this.innerWidth());

**Comment by darzzydarzz** [comment]
any ETA on this one?

**Comment by wenzhixin** [comment]
Same with #1536
