### ISSUE TITLE
Extension Editable - not working

### ISSUE THREAD

**Issue by alexz707** [wenzhixin/bootstrap-table#1788]
Hi!
I've just discovered that the editable plugin doesn't work as before updating to 1.9.1.
In my application the following config doesn't call the data-url anymore:

<th data-field="bidPrice" 
                    data-editable="true"
                    data-type="number" 
                    data-sortable="false" 
                    data-visible="true"
                    data-title="Bidprice"
                    data-url="<?php echo $this->url('administration/setBidPrice'); ?>"
                    >Bidprice</th>

Before the update it worked like expected. It called the data-url and sent the data.
Now it just closes the overlay and does nothing (also no error)... only the classes change to 

"editable editable-click editable-unsaved"

I have a second editable field with a data-type date and before the update there was also a datepicker...now its just an input field...

Following versions I'm using:
X-editable - v1.5.1
Bootstrap v3.3.2
bootstrap-table - v1.9.1 - 2015-10-25
bootstrap-table editable - v1.9.1 - 2015-10-25
jQuery v2.1.3

Can you please help me finding the problem ?
Thanks for your help!!

regards Alex

**Comment by alexz707** [comment]
Pic of the code: 
![bildschirmfoto 2015-12-09 um 11 44 29](https://cloud.githubusercontent.com/assets/562324/11683315/5317b680-9e6a-11e5-9b86-054fc6db6c64.png)

**Comment by wenzhixin** [comment]
can you provide a jsfiddle:  https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
