### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by maosi** [wenzhixin/bootstrap-table#1791]
Can we show some explicit erro message to instead of the `formatNoMatches` text when something wrong happened?

**Comment by dabros** [comment]
@maosi - can you please explain more on common use case for this?

Namely, some scenerios and how you this message might be presented

**Comment by wenzhixin** [comment]
Added `updateFormatText` method: http://jsfiddle.net/e3nk137y/3876/

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/commit/9574c69faef474d22fb80bbb2e64483018c1e1ce

**Comment by maosi** [comment]
@wenzhixin  @dabros  Thanks a lot ! That's what i want.
