### ISSUE TITLE
Export Button is shown twice after using data-show-export="true" and data-advanced-search="true"'

### ISSUE THREAD

**Issue by DigitalCoder** [wenzhixin/bootstrap-table#1792]
Hello,

I'm using data-show-export="true" and data-advanced-search="true"'
but I can see two button for export

how to have only one ? without hacking in css as this : 
`.bootstrap-table .btn-group[role="group"] .export.btn-group {
    display: none;
}`

Thanks for advance !

**Comment by wenzhixin** [comment]
Please provide a jsFiddle: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by DigitalCoder** [comment]
ok you can find here : 
https://github.com/DigitalCoder/bootstrap-table/tree/issue-1792

**Comment by DigitalCoder** [comment]
Hi !

In fact I've found the solution ^^

I just have to call bootstrap-table-toolbar.js after bootstrap-table-export.js

Regards !

**Comment by wenzhixin** [comment]
Great, remember any pull request is welcome!
