### ISSUE TITLE
当表格中有且仅有一条数据的时候，调用refresh函数刷新的时候不会刷新页面，即使响应的url返回的结果为空

### ISSUE THREAD

**Issue by xiongsenlin** [wenzhixin/bootstrap-table#1793]

**Comment by xiongsenlin** [comment]
BootstrapTable.prototype.initData = function (data, type) {
        if (type === 'append') {
            this.data = this.data.concat(data);
        } else if (type === 'prepend') {
            this.data = [].concat(data).concat(this.data);
        } else {
            this.data = data || this.options.data;
        }

        // Fix #839 Records deleted when adding new row on filtered table
        if (type === 'append') {
            this.options.data = this.options.data.concat(data);
        } else if (type === 'prepend') {
            this.options.data = [].concat(data).concat(this.options.data);
        } else {
            this.options.data = this.data;
        }

        if (this.options.sidePagination === 'server') {
            return;
        }
        this.initSort();
    };

问题我已经定位到了：
else {
            this.data = data || this.options.data;
        }
就是这行代码的问题，因为后端返回的结果data为空，所以这儿就取了this.options.data，所以当我实现了一个功能，逐行删除表格的数据，后端也相应删除，然后删除到只有一行的时候，即使后端已经没有数据了，前端这条数据一直会在，除非手动刷新页面。

**Comment by xiongsenlin** [comment]
最终解决方案为：
 else {
            this.data = data || [];
        }

**Comment by wenzhixin** [comment]
没有数据的时候，后端也要返回空数组：`[]`，或者你可以设置
```js
responseHandler: function (res) {
    return res || [];
}
```

**Comment by wenzhixin** [comment]
你那样改的话是错的，考虑这种情况
```
$table.bootstrapTable({
    data: localData
});
```
