### ISSUE TITLE
Refresh sort after append or prepend rows

### ISSUE THREAD

**Issue by yenyen** [wenzhixin/bootstrap-table#1795]
When you append or prepend rows the sort is not applied

**Comment by dabros** [comment]
@yenyen - im unable to confirm this using examples as non have both sortable and append/prepend

Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports and provide a fiddle

Thanks

**Comment by wenzhixin** [comment]
Please update #1796.
