### ISSUE TITLE
hideRow/showRow not working

### ISSUE THREAD

**Issue by grothendeick** [wenzhixin/bootstrap-table#1799]
Hello,

The methods hideRow/showRow working great on version 1.8.1:
https://jsfiddle.net/r1b4y7ko/4

But the methods doesn't work on master version:
https://jsfiddle.net/j0gmtygs

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/1743

**Comment by grothendeick** [comment]
Thanks but I could not make it working:
http://jsfiddle.net/j0gmtygs

I tried to call the function hideRow as:
`$('#table').bootstrapTable('hideRow', {index:40, isIdField: true});`
and
`$('#table').bootstrapTable('hideRow', {uniqueId:40});`

**Comment by wenzhixin** [comment]
Merged in the develop branch @grothendeick
