### ISSUE TITLE
引入扩展bootstrap-table-reorder-rows.js初始化问题

### ISSUE THREAD

**Issue by yujinjin** [wenzhixin/bootstrap-table#1800]
init初始化时，参数reorderableRows为false直接return了。建议修改成：
![qq 20151214174150](https://cloud.githubusercontent.com/assets/11609930/11777905/20ed8c04-a28c-11e5-95a6-7bbe1ddc58fe.png)

**Comment by wenzhixin** [comment]
看了代码，在最新版本已经修复了该问题。谢谢。
