### ISSUE TITLE
查询参数传入服务器字符乱码，服务器使用spring的CharacterEncodingFilter设置强制转码UTF-8

### ISSUE THREAD

**Issue by xiegang666** [wenzhixin/bootstrap-table#1801]
//查询参数传递
function queryParams(params) {
    return {
                rows: params.limit,	
 
                page: params.offset/params.limit+1, 
                
 		merchantNo : $("#searchNo").val(), 
 				
 		merchantName : $("#searchName").val(), 
                
                sidx: params.sort,	// 排序字段
 
                sord: params.order  // 排序顺序
 
            };
}

服务器获取：String mchName = request.getParameter("merchantName");
得到的是乱码

	<filter>
		<filter-name>CharacterEncodingFilter</filter-name>
		<filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>
		<init-param>
			<param-name>encoding</param-name>
			<param-value>UTF-8</param-value>
		</init-param>
		<init-param>
			<param-name>forceEncoding</param-name>
			<param-value>true</param-value>
		</init-param>
	</filter>

**Comment by wenzhixin** [comment]
bootstrap-table 用的是标准的 jquery ajax请求，你调试下，或者设置下 ajaxOptions

**Comment by NapChen** [comment]
问题解决了吗？我最近也遇到这个问题

**Comment by NapChen** [comment]
还是自己慢慢摸索出来了，在初始化表格的时候添加
contentType : "application/x-www-form-urlencoded;charset=utf-8"

**Comment by xiegang666** [comment]
服务器容器问题，设置 URIEncoding="UTF-8" 搞定

**Comment by 2FA0** [comment]
我也是，tomcat配置端口那一项里加入URIEncoding="UTF-8"就好用了
