### ISSUE TITLE
refresh方法，数据没有及时加载，点击第二遍才正确加载

### ISSUE THREAD

**Issue by xiegang666** [wenzhixin/bootstrap-table#1802]
<table id="table"
                    	   data-toolbar="#toolbar"
                    	   data-toggle="table"
				           data-pagination="true"
				           data-checkbox-header = "true"
				           data-side-pagination="server"
				           data-page-number = "1"
				           data-page-size = "5"
				           data-page-list = "[5,10,20,All]"
				           data-url="$dataUrl"
				           data-query-params="queryParams">

//查询参数传递
function queryParams(params) {
			return {
                rows: params.limit,	// 分页大小
 
                page: params.offset/params.limit+1, // 当前页=开始位置/分页大小+1

                status: $("#selStatus").val(),	// 状态
            };
		}

// 查询
			$("#search").click(function(){
				$("#table").bootstrapTable('refresh');
			});

假设第一次输入条件查询，结果为1条数据，接下来把条件重置，重新查询
这是请求服务器的数据是正确返回的，并且分页信息里的总记录数正确，分页也是正确的
就是table数据还是显示一条

再次点击查询按钮才会显示所有数据

**Comment by wenzhixin** [comment]
不用 `data-page-number` 试试
