### ISSUE TITLE
Checkbox status not persistent after Search or Pagination activation / deactivation

### ISSUE THREAD

**Issue by heiko-huetter** [wenzhixin/bootstrap-table#1803]
If you select some checkboxes in a table and then alter anything in the view (e.g. alter sorting, add a search term or activate / deactivate pagination) the status of the previous selected checkbox is not saved. Instead bootstrap-table displays the original status on page load.

This seems to be unexpected behaviour.

JS Fiddle for testing: http://jsfiddle.net/29u3vuz8/1/embedded/result/

Steps to reproduce: 
1) Select row 2 "multiple-select"
2) Type "boo" into the search field
3) delete "boo" from the search field

Now your selection is gone.

Many thanks

**Comment by djhvscf** [comment]
You have to use "data-maintain-selected="true""
See this fiddle: http://jsfiddle.net/29u3vuz8/2/

**Comment by djhvscf** [comment]
If this does not solve your problem, open this issue again. @heiko-huetter
