### ISSUE TITLE
Search form

### ISSUE THREAD

**Issue by yaylitzis** [wenzhixin/bootstrap-table#1804]
How can I search for a value e.g `30` in the search box and have all the results which contains only the 30 and not like this: 452<b>30</b>

Or search a value only to a specific column.

**Comment by djhvscf** [comment]
Please use "data-strict-search=true"
See this example: http://jsfiddle.net/e3nk137y/3858/
Steps: 
Search "5" -> Don't have any records
Search "11" -> 1 record

**Comment by wenzhixin** [comment]
Added to #1765
