### ISSUE TITLE
json对复杂类型的数据支持建议

### ISSUE THREAD

**Issue by cyw9907** [wenzhixin/bootstrap-table#1805]
假设json数据如下定义：
var data = {
     id :1,
     game:{ id: 2, name:'test'},
    kind : 2
}

		        <tr>
		            <th data-field="game.id">编号</th>
		            <th data-field="game['name']">名称</th>
		            <th data-field="kind">类型</th>
                     </tr>

$("#table-game").bootstrapTable('load', data);
原有代码编号和名称列是无法显示的，通过跟踪代码调试，发现问题在bootstrap-table.js中的第1289行
我将原代码改成如下
//value = item[field],
 -》value = eval('(item.'+field+')'),
则上述示例可以正常显示数据

**Comment by stevenjlho** [comment]
最新版本已经支持该功能了，请参考下面的PR说明
https://github.com/wenzhixin/bootstrap-table/pull/1289
