### ISSUE TITLE
the thicker line

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1806]
hello everyone

have you ever encountered this "thicking line" that is not supposed to happen..?

this is a bootstrap table(just erased the contents) with the thicking line...

![the thicker line](https://cloud.githubusercontent.com/assets/13029902/11834298/1de89582-a406-11e5-80b4-ffc8603228af.png)

?

what causes this

**Comment by dabros** [comment]
@joomlaA1 - Magic

Impossible to say unless you can replicate with a fiddle, but really shouldnt be hard to see by hitting F12 and then 'inspecting', selectively disabling border rules in the inspect panel till you find where it coming from.

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
Please check this problem by yourself or provide a jsfiddle.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
