### ISSUE TITLE
Support for infinite scrolling

### ISSUE THREAD

**Issue by martin-g** [wenzhixin/bootstrap-table#1807]
I've browsed a lot the docs and examples but I wasn't able to find something like http://w2ui.com/web/blog/7/JavaScript-Grid-with-One-Million-Records, i.e. load and unload rows dynamically while using the scrollbar instead of the standard pagination.

Do you have plans for adding such functionality?

**Comment by wenzhixin** [comment]
#256 #1606, any pull request is welcome.

**Comment by martin-g** [comment]
Closing as duplicate of #256
