### ISSUE TITLE
Table row click event doesn't work

### ISSUE THREAD

**Issue by Reshad-A** [wenzhixin/bootstrap-table#1808]
I am trying to handle tr click event of table but for some reason the parameter row is empty. it doesn't contain the clicked row data.

  $(function () {
       
        $('#ContactsTable').on('click-row.bs.table', function (e, row, $element) {
            window.open('/Contacts/Details/' + row[1].trim(), '_self');
        });

    });

**Comment by dabros** [comment]
@Reshad-A - i cant replicate this using examples or my own code, so please provide a fiddle

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
worked example: http://jsfiddle.net/e3nk137y/3873/.

ref #1765
