### ISSUE TITLE
Change the sort icon

### ISSUE THREAD

**Issue by babbelnedd** [wenzhixin/bootstrap-table#1809]
This one is passed in as base64'd image and it seems one can't change it per `icons`. That's kinda weird. Is there a simple way I haven't seen in the configuration?

**Comment by dabros** [comment]
@babbelnedd - if you wanted to change icons, just use css

Go to your site, or a page like http://issues.wenzhixin.net.cn/bootstrap-table/ and hit F12 then inspect and find where it being applied.

You are correct in that it seems to be a base64 image, just look at the selector that applies it and overwrite with whatever you need.

As a basic rule of thumb, for simple themeing like that you are expected to be using css for consistent application, just pass in className to table or wrap if you only want certain tables to be affected, or even pass in class to column itself and see if that affects TH.

**Comment by babbelnedd** [comment]
I were starting using css but It's tbh a pita with the given setup: I just
thought it would be a logical step to replace these icons with some actual
glyphicons for default and make them changeable per `icons`

**Comment by babbelnedd** [comment]
I were starting using css but It's tbh a pita with the given setup. I just wanted to change colors and well... ;) I just thought it would be a logical step to replace these icons with some actual glyphicons for default and make them changeable per `icons`

**Comment by dabros** [comment]
@babbelnedd - just recalled there are some icons settings, see http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

These change prefix and ect, but you need to play with inspect and look at css file to see how being used

**Comment by dabros** [comment]
@babbelnedd - not that hard to save that base64 as image file then edit and copy as base64 string, or use online editor even.

Havent done it myself, but i know people who have, just google it.

**Comment by babbelnedd** [comment]
>  just recalled there are some icons settings

Exactly, but none for the dropdowns as far as I can see.

**Comment by dabros** [comment]
@babbelnedd - then work around it

Remove those classes from your install (or overwrite, ect) then see this:

```

    BootstrapTable.prototype.getCaret = function () {
        var that = this;

        $.each(this.$header.find('th'), function (i, th) {
            $(th).find('.sortable').removeClass('desc asc').addClass($(th).data('field') === that.options.sortName ? that.options.sortOrder : 'both');
        });
    };

```

You can use F12 to confirm the classes being added - just map an existing rule to match that, and/or look into `onPostHeader` and just add a callback that picks up on those classes and appends or affects whatever you wanted.

That callback is called after any change that affects the header, so perfect spot if simple css not enough.

You should be able to create a css rule to apply to acheive desired effect, usign less or whatever you want, and if needed also inject any minimal html to each '.th-inner .sortable'.

**Comment by babbelnedd** [comment]
Thanks for the effort. I'll style it then.

**Comment by geigel** [comment]
Kind of a pain to change but went pretty easy as you jump through the hoops. First download the file as a PNG, edit in Photoshop by applying a color overlay, save back as a PNG, then use an online converter to convert back to base64 (I used https://www.base64-image.de/). then simply update the CSS with the new base64 data instead of the original.
