### ISSUE TITLE
How to format the search input?

### ISSUE THREAD

**Issue by babbelnedd** [wenzhixin/bootstrap-table#1810]
Is there a way to add a class to the created search input?  
Or even better to reference it's own input per selector?

*Without editing source files

**Comment by wenzhixin** [comment]
try this: `$('#table').closest('.bootstrap-table').find('.search input');`

**Comment by wenzhixin** [comment]
Or to use:
```
var $search = $table.data('bootstrap.table').$toolbar.find('.search input');
```
Example: http://jsfiddle.net/e3nk137y/3872/
