### ISSUE TITLE
Table Editable Extensions Question

### ISSUE THREAD

**Issue by zyz** [wenzhixin/bootstrap-table#1814]
http://issues.wenzhixin.net.cn/bootstrap-table/welcome.html
columns:
editable: true equals data-editable="true".
however
editable: {
    type: 'text',
    title: 'Item Price',
    validate: function (value) {
        value = $.trim(value);
        if (!value) {
            return 'This field is required';
        }
        if (!/^$/.test(value)) {
            return 'This field needs to start width $.'
        }
        var data = $table.bootstrapTable('getData'),
        index = $(this).parents('tr').data('index');
        console.log(data[index]);
        return '';
    }
}
How use data-editable?

**Comment by dabros** [comment]
@zyz - its unclear what your asking exactly, not only in that it is too open ended and you havnt formatted your post at all (click the 'styling with Markdown' button on top of github text editer.

But to use editable extension, many examples out there on SO, here, and in official examples pages

All extensions: http://bootstrap-table.wenzhixin.net.cn/extensions/
Editable home: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable
Official Example: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html (click 'see source' button in top right for source code)
Issue example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/986.html

**Comment by zyz** [comment]
function validateNum(value) {
 value = $.trim(value);
 if (!value) {
 return 'This field is required';
 }
 if (!/^$/.test(value)) {
 return 'This field needs to start width $.'
 }
 var data = $table.bootstrapTable('getData'),
 index = $(this).parents('tr').data('index');
 console.log(data[index]);
 return '';
 }

data-editable=" {
 type: 'text',
 title: 'Item Price',
 validate: validateNum}"

**Comment by zyz** [comment]
it is failed

**Comment by dabros** [comment]
@zyz - again, cant tell what you want except to say look at the fully functional examples i linked above.

Failing that, see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports and provide a fiddle that clearly shows your 'expected output' vs 'current output'

**Comment by zyz** [comment]
http://jsfiddle.net/wenyi/e3nk137y/3744/
<table id="table">
  <thead>
    <tr>
      <th data-field="name">Name</th>
      <th data-field="stargazers_count" data-editable="{type:'text'}">Stars</th>
      <th data-field="forks_count" data-editable="{type:'text'}">Forks</th>
      <th data-field="description" data-editable="{type:'textarea'}">Description</th>
    </tr>
  </thead>
</table>
$(function () {
    var $table = $('#table').bootstrapTable({
        idField: 'name',
        url: '/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data1/'
    });
    $table.on('editable-save.bs.table', function (e, field, row, old, $el) {
    		var $els = $table.find('.editable'),
            next = $els.index($el) + 1;

            if (next >= $els.length) {
                return;
            }

            $els.eq(next).editable('show');
    });
});

**Comment by dabros** [comment]
@zyz 

1. you posted EXACT same fiddle link, no saved changes, that i presented as 'example' and told not to actually use

2. again you fail to ask an actual question and state your 'current ouput' vs 'desired output'

3. No mention of whether you even looked at the fully functioning examples or doco links i gave you

4. **Styling with Markdown is supported**  - click the link and use it

**Comment by zyz** [comment]
http://jsfiddle.net/e3nk137y/3913/

**Comment by dabros** [comment]
@zyz - http://jsfiddle.net/dabros/e3nk137y/3916/

See comments in js block

**Comment by zyz** [comment]
Description is input text, is not textarea?
editable-save.bs.table event, if input is empty, 
How to prevent the editable pop-up box shut down?

**Comment by wenzhixin** [comment]
have you solved you problem?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
