### ISSUE TITLE
add dropdown list in a column

### ISSUE THREAD

**Issue by mkghauri** [wenzhixin/bootstrap-table#1821]
Need to add column which contain dropdown list, User can change it using dropdown list.

Can you send me JSON format with Example,

**Comment by dabros** [comment]
@mkghauri - please provide more info and ideally a fiddle in the future

Extensions:
http://bootstrap-table.wenzhixin.net.cn/extensions/

Editable extension:
Home: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable
Official Demo: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html
Select Field: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/986.html
