### ISSUE TITLE
css issue in line 7 .bootstrap-table .table {

### ISSUE THREAD

**Issue by Laro88** [wenzhixin/bootstrap-table#1822]
Hello.
I keep getting problems reported in the bootstrap css file.
Firebug says 
```
SyntaxError: expected expression, got '.'
```
and points to the bootstrap-table line 7 which is the first .bootsrap-table .table

Any suggestions?

**Comment by dabros** [comment]
@Laro88 - please copy+paste the first 20 or so lines of your css file, the html around where you link to that file (`<style type='text/css' href=''/>` ect)  and check its the same contents as the version in https://github.com/wenzhixin/bootstrap-table/tree/master/src

**Comment by Laro88** [comment]
bootstrap-table.css (it says 1.8.1 but it comes from the latest 1.9.1 zip)
```
/**
 * @author zhixin wen <wenzhixin2010@gmail.com>
 * version: 1.8.1
 * https://github.com/wenzhixin/bootstrap-table/
 */

.bootstrap-table .table {
    margin-bottom: 0 !important;
    border-bottom: 1px solid #dddddd;
    border-collapse: collapse !important;
    border-radius: 1px;
}

.bootstrap-table .table:not(.table-condensed),
.bootstrap-table .table:not(.table-condensed) > tbody > tr > th,
.bootstrap-table .table:not(.table-condensed) > tfoot > tr > th,
.bootstrap-table .table:not(.table-condensed) > thead > tr > td,
```
.jade file:
```
extends layout
block css
  script(src='/stylesheets/bootstrap-table.css')
block scripts
  script(src='/javascripts/ext/bootstrap-table.js')
  script(src='/javascripts/ext/bootstrap-table-editable.min.js')
  script(src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js")

  script(src='/javascripts/ext/async.js')  
  script(src='/javascripts/readset_cs.js')

block pageContent
  div.col-sm-6
    table.table
      tr
        td.col-sm-1
          select#selreadsets
``

**Comment by dabros** [comment]
@Laro88  - thanks for that

Im not familiar with the .jade, so maybe StackOverflow is more appropriate location if that is the issue (see )

However, do ensure you including all files (and in same order) as seen in https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/editable.html, though i assume jquery.min.js is included in layout your extending, and ect.

To prove whether .jade, add or even replace bootstrap-table.css with a different css file with various other rules, and/or search online for similiar ".jade css errors" as that.

Also confirm whether browser based issue, which is how i first read your post, but prob issnt the case.

Anyway, if still cant fix it get that info together (proof you tried other css and have correct files, test cross-browser like chrome and IE, ect) then post to SO with backlinks bother here and there

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by wenzhixin** [comment]
If the problem exist, reopen it and provide a jsFiddle, thanks!
