### ISSUE TITLE
call function after to load data

### ISSUE THREAD

**Issue by fhox36** [wenzhixin/bootstrap-table#1823]
Is there any way to call a function after loading the data from the server?

**Comment by dabros** [comment]
@fhox36 - it sounds like `responseHandler` the best fit for you, else look at http://issues.wenzhixin.net.cn/bootstrap-table/ (click 'see source' in top right) and see `responseHandler` and the callbacks being triggered to find one that fits you best.

http://bootstrap-table.wenzhixin.net.cn/documentation/

**Comment by fhox36** [comment]
thanks!, you solved my question
