### ISSUE TITLE
CellStyle of Editable Cells

### ISSUE THREAD

**Issue by jakeholland** [wenzhixin/bootstrap-table#1824]
Here is an issue that i have been experiencing. Cell styles are not reapplied once a cell is edited. Here is a simple example. http://jsfiddle.net/jtholla2/5gLgavfe/2/ Any cell which has "Red" in the description will have a background cell color of red. Once the cell has had been edited to include or exclude "Red" no style changes are applied.

**Comment by dabros** [comment]
@jakeholland - thanks for the interesting problem, but unfortunate not enough time to fix as not overly easy solution.

However, i scoped out what i think is solution, see this fiddle and my `// NOTES` in js block (in top and within code)

http://jsfiddle.net/dabros/5gLgavfe/4/

If anyone else can help with this then great, i doubt i have time till after holidays, but will keep eye on this and help anyone who follows up

**Comment by wenzhixin** [comment]
The jsfiddle seems have solved the problem? @dabros

**Comment by dabros** [comment]
@wenzhixin - not fully, i made notes in js block about halfway down as i was coding, tell me if not clear and i will try to paraphrase later, no time atm
