### ISSUE TITLE
Feature Request: Conditional Columns

### ISSUE THREAD

**Issue by babbelnedd** [wenzhixin/bootstrap-table#1825]
I want to display a column only under specific conditions. There is no way to do this atm.

**Comment by dabros** [comment]
@babbelnedd - please be more specific

Ideally include fiddle (see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports for info and links) so we can test code for you.

There are several ways i can think of, but i never tested them and they all very context specific so both description and fiddle would help pick best for you.

**Comment by dabros** [comment]
@babbelnedd 

As an example though, the simplist way would be to init via js then set `visible` column option using a function to return a bool.

http://bootstrap-table.wenzhixin.net.cn/getting-started/#usage-via-javascript
http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

Untested:

```
<table id="table"></table>


// Shorthand for $( document ).ready()
$(function() {
    $('#table').bootstrapTable({
        columns: [{
            field: 'id',
            title: 'Item ID',
            visible: checkIfVisible('id')
        }, {
            field: 'name',
            title: 'Item Name',
            visible: checkIfVisible('name')
        }, {
            field: 'price',
            title: 'Item Price',
            visible: checkIfVisible('price')
        }],
        data: [{
            id: 1,
            name: 'Item 1',
            price: '$1'
        }, {
            id: 2,
            name: 'Item 2',
            price: '$2'
        }]
    });
});

// NOTE - be careful with scope, though should still work if inside $.() scope above
function checkIfVisible(colname)
{
    if(colname == 'name')
       return false;
    return true;
}
```

**Comment by babbelnedd** [comment]
aaah `visible` works! thank you, my bad
