### ISSUE TITLE
data 加载问题

### ISSUE THREAD

**Issue by ranbo3013** [wenzhixin/bootstrap-table#1826]
第一次数据加载一定要放在document.ready里吗？如果是需要用到table时再加载数据好像就不行了，这是个bug吗？

**Comment by xiaoweiqb** [comment]
用onclick触发加载方法

**Comment by wenzhixin** [comment]
可以用 `load` 方法: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/load.html
