### ISSUE TITLE
Search after click key enter

### ISSUE THREAD

**Issue by mtsys** [wenzhixin/bootstrap-table#1827]
How do I do research only after clicking the enter button?

**Comment by dabros** [comment]
@mtsys - two ways i can think of, three if you include making a PR with ability to toggle this off/on in base code


The actual code for triggering search is fairly simple, and does allow `searchTimeOut` to allow a delay, but is fixed to using certain triggers

```
if (this.options.search) {
            html = [];
            html.push(
                '<div class="pull-' + this.options.searchAlign + ' search">',
                sprintf('<input class="form-control' +
                    sprintf(' input-%s', this.options.iconSize) +
                    '" type="text" placeholder="%s">',
                    this.options.formatSearch()),
                '</div>');

            this.$toolbar.append(html.join(''));
            $search = this.$toolbar.find('.search input');
            $search.off('keyup drop').on('keyup drop', function (event) {
                clearTimeout(timeoutId); // doesn't matter if it's 0
                timeoutId = setTimeout(function () {
                    that.onSearch(event);
                }, that.options.searchTimeOut);
            });
        }
```

One way of doing this would be to make a **PR** with an option `searchTrigger` which defaults to "keyup drop", but allows you to specify and trigger for the `$.on()` handler.

If its just an outside use case, just use `onPostHeader` callback and store referance to existing "keyup drop" event, remove it (call `$.off()`) then assign to new trigger, such as enter key. Just google "change event trigger jquery", "clone event jquery" or "replace event handler jquery" or something to find how if you need to, but its basically just store current event handler in variable, call `$.off()` then call `$.on()` with new trigger, passing in that stored variable.

The third way is use a custom toolbar, good example of that here: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

You can use whatever UI you want, whatever trigger you want, and just use what that example does with grabbing all inputs in custom toolbar, or just explicitly grab search text. If you look at doco and example you see that it uses `queryParam` to handle storing/passing those custom UI values, though for simple search (client side only) `filterBy` might work alright, and bootstrap-table-filter extension likely has its own exposed methods for handling this.

**Comment by djhvscf** [comment]
See: #1880
