### ISSUE TITLE
Data Export doesn't work for many formats

### ISSUE THREAD

**Issue by billzt** [wenzhixin/bootstrap-table#1828]
I use Windows 10, Firefox 43.0.2 to visit http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html . Export formats for JSON and XML works OK. But CSV, TXT and SQL works wrong.

CSV
![csv](https://cloud.githubusercontent.com/assets/1146090/11970824/84bf2a08-a96c-11e5-9b73-c9d25ea6a210.png)

TXT
![txt](https://cloud.githubusercontent.com/assets/1146090/11970826/8bf94eca-a96c-11e5-866c-9648587b2885.png)

SQL
![sql](https://cloud.githubusercontent.com/assets/1146090/11970828/8fa5b0cc-a96c-11e5-9ff7-189ea6ea0cff.png)

Besides, MS-EXCEL seems OK, however when I open the downloaded XLS file using Office 2016, it gives a warning:
![xls](https://cloud.githubusercontent.com/assets/1146090/11970835/b0c830fe-a96c-11e5-9e0d-303b76853c23.PNG)

**Comment by billzt** [comment]
Wow! I've known. FileSaver.min.js should be included before tableExport.min.js .

**Comment by billzt** [comment]
However, the last issue about MS-EXCEL still exists! Although it could be ignored, it is annoying!

**Comment by dabros** [comment]
@billzt - please clarify the still existing issue/s with export, unclear what is happening with MS-EXCEL to annoy you

**Comment by billzt** [comment]
@dabros My Office2016 complains that the exported MS-EXCEL file format is inconsistent with the file  extension name.

![b0c830fe-a96c-11e5-9e0d-303b76853c23](https://cloud.githubusercontent.com/assets/1146090/12085763/4ef934a4-b2fe-11e5-90c6-9d0b5b8dfd6c.PNG)

**Comment by dabros** [comment]
@billzt - can you please look at https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports and maybe the export demo and provide a fiddle which does this, which we can then play with to narrow down what factors cause this issue?

**Comment by wenzhixin** [comment]
Fixed.
