### ISSUE TITLE
is there a way to control editable options with data-attributes ?

### ISSUE THREAD

**Issue by promogest** [wenzhixin/bootstrap-table#1832]
how can i use something like : 
```<th data-field="valore_unitario"
      data-width="3%"
      data-editable="true"
      data-editable-mode="inline"
      data-sortable="true">```

thanks

**Comment by fsauter** [comment]
Hey, I was in need of the same and added this functionality in my fork. I may open a pull request. But I'm sure that my code needs improvement.

https://github.com/fsauter/bootstrap-table
https://github.com/fsauter/bootstrap-table/commit/638cebc72296e9be226d62e79d88565da68badfb

It enables you to add table and specific column data attributes. All editable data attributes must be prefixed with "editable" (see below). Note that table wide options are used for every column but can be overriden.

````html
<table id="dispatch-type-list"
  data-url="data/url.json"
  data-id-field="id"
  data-editable-emptytext="This field is empty"
  data-editable-url="/my/editable/update/path">
  <thead>
    <tr>
      <th class="col-md-1" data-field="id" data-sortable="true" data-align="center">#</th>
      <th class="col-md-3" data-field="name" data-editable="true">Name</th>
      <th class="col-md-7" data-field="description" data-editable="true" data-editable-emptytext="This will override the empty text option of the table.">Description</th>
      <th class="col-md-1" data-align="center" data-formatter="formatter.actions">Actions
      </th>
    </tr>
  </thead>
</table>
````

**Comment by promogest** [comment]
thanks , it works

**Comment by dabros** [comment]
@promogest - please update topic title to include '[solved]' and close issue please

**Comment by promogest** [comment]
it is solved only because @fsauter did a patch and commit a pull request.
