### ISSUE TITLE
abuot update row

### ISSUE THREAD

**Issue by serlogo53** [wenzhixin/bootstrap-table#1834]
hi,
i am using json datasource. i am clicking a row and opening in modal and editing boxes then apply.
in here i am updating row columns by updaterow function. after this again i am wanting to edit end it's not refreshed. i don't want to refresh table data because many data it has got. is it possible a way or am i doing mistakes? best regards.

i assign table values to editbox by "click-row.bs.table" and parsing data.

thanks.

**Comment by wenzhixin** [comment]
You can view this example: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/updateRow.html, and you also need to update the database when you updating the row.

**Comment by serlogo53** [comment]
Thanks. İ also done this. İ think i imagined one more level.
