### ISSUE TITLE
Dynamic Column Title 

### ISSUE THREAD

**Issue by memect** [wenzhixin/bootstrap-table#1837]
Hi, 
Some of my columns' title don't have fix names, where the names are stored in json file, i.e., each data records may have different names. For example,

The json data is:

[
        {"date": [
            "2015-06-30", 
            "2014-12-31", 
            "2013-12-31", 
            "2012-12-31"
        ],
         "value": [
            "1", 
            "2", 
            "3", 
            "4"
          ]
        } 
]

And js code:

  $.getJSON("/api/companies", function (json) {
        $table.bootstrapTable({
            data: json, 
            columns: [
                 {
                        field: 'value.0',
                        title: 'date.0',
                        sortable: true,
                        align: 'center',
                        valign: 'middle'
                    }
           ]

I know value.0 can bind with "1" in json, but how can I bind date.0 with 2015 ?

**Comment by dabros** [comment]
@memect - why dont you setup a fiddle, passing in data via javascript arrays with format that you need: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Then try to describe again current ouput vs desired output, in referance to that fiddle

**Comment by wenzhixin** [comment]
close because [there is no any response in 7 days](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#issues-and-labels).
