### ISSUE TITLE
Sorting isn't correct with data-reactid attributes

### ISSUE THREAD

**Issue by AndrejGajdos** [wenzhixin/bootstrap-table#1839]
I use this plugin in my react application, which generates `data-reactid` attributes by default. With this attributes column sorting is not correct.

[jsfiddle](https://jsfiddle.net/64ce96gw/) - table with data-reactid attributes, sorting is not correct.

If you order *"CustomerN"* column, sequence of rows is not correct.

[jsfiddle](https://jsfiddle.net/ztc2ng8q/) - table without data-reactid attributes, sorting is correct

**Comment by dabros** [comment]
@AndrejGajdos - this has nothing to do with reactid, rather just that you have formatted text that it is sorting.

Im sure this has been answered before, but i just made this fiddle to prove the point:

https://jsfiddle.net/dabros/vz6nnsbe/1/

As seen in the fiddle, prob best to use a formatter that strips that junk html and sorts just the values.

Now, my thought is that if you use formatter to plant that extra html, it will ignore it (see https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L837 and below, atm the location of initSort and related code)

However, im guessing that like the fiddle you presented, the raw data is somehow got this junk html.

If possible, ensure the data passed to the table via json or whatever format doesnt include that junk html, just the value, then that should also fix the issue. Formatters or similar can be used to reapply the reactid and other html if needed, but i dont know reactid so up to you to determine if that is feasible, or just to go with custom sorter.

**Comment by wenzhixin** [comment]
have you solved the problem? @AndrejGajdos

**Comment by AndrejGajdos** [comment]
@wenzhixin solved, answer is [here](http://stackoverflow.com/a/34563804/968379)

**Comment by wenzhixin** [comment]
Great 👍
