### ISSUE TITLE
onClickCell response strange when hide the column before the column bind with onClickCell

### ISSUE THREAD

**Issue by Iuranus** [wenzhixin/bootstrap-table#1841]
Three Column: id name city ...
column is bound with onClickCell
when i hide the column id, the onClickCell event is only triggered on column city
why?

**Comment by dabros** [comment]
@luranus, please link to valid example or provide jsfiddle as i cant replicate in current environment

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
