### ISSUE TITLE
sidePagination not working?

### ISSUE THREAD

**Issue by simple-task** [wenzhixin/bootstrap-table#1842]
Any idea why this is not firing?
<pre>
$('#invoice_table_selector').bootstrapTable({
       
        sidePagination : 'server',
        url: -->'some custom url with params, can not go into html data-url',
        onLoadSuccess: function(res){
            console.log(res);
        }
    });
</pre>

**Comment by goors** [comment]
I had same problem and never able to figure that one out.
Most frustrating.
