### ISSUE TITLE
CSS 没有升级到 1.9.1，footer不能对齐

### ISSUE THREAD

**Issue by weianguo** [wenzhixin/bootstrap-table#1844]
库里的版本还是1.8.1的，footer不能对齐，
而实例里面有1.9.1的css，http://issues.wenzhixin.net.cn/bootstrap-table/#issues/639.html
请更新一下

**Comment by wenzhixin** [comment]
released to v1.10.0: https://github.com/wenzhixin/bootstrap-table/blob/master/dist/bootstrap-table.css
