### ISSUE TITLE
Is there a way to hide pagination details, just show pagination?

### ISSUE THREAD

**Issue by carldai0106** [wenzhixin/bootstrap-table#1846]
Dear Author;

This is a good plugin. Thanks for your work.
As the subject, I want to hide pagination details and just show pagination.
Do you have any way to do?

**Comment by dabros** [comment]
@carldai0106 - as far as im aware that itself is not an option yet, though the opposite (just info) is (i think, untested)

ctrl+f and find options containing 'pag' in http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options.

You can look at the `onlyInfoPagination` option and how that implemented, **PR** are always welcome if you see how to easily create a `onlyNumbersPagination` type option (see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests first, important info)

Other than that, just use css to hide, hit F12 and inspect to find the selector combo you looking for.

**Comment by carldai0106** [comment]
@dabros thank you for your reply. I got it.
