### ISSUE TITLE
New Row

### ISSUE THREAD

**Issue by Mitsaras1911** [wenzhixin/bootstrap-table#1851]
Is it possible to add a row where it will be an input text to write my own data?
Sorry about my bad English :p
Thanks

**Comment by thornomad** [comment]
This is not a direct feature of bootstrap-table.  But you can implement it yourself with a little work.

* Add a button to your toolbar which triggers a bootstrap modal.
* The modal can contain the form 
* Add a `click()` event trigger to the forms submit button, and when clicked, get the data from the form and use the `bootstraTable('insertRow', index, row)` method.  Obviously this just adds the data to the form on the user's page; you would have to implement your own server-side update.

HTH

**Comment by Mitsaras1911** [comment]
is this possible to do this inline?

**Comment by dabros** [comment]
@Mitsaras1911 - the only way i can see it working 'inline' without breaking `detailView` or similar, would be editable extension.

http://bootstrap-table.wenzhixin.net.cn/extensions/
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html

You would do something like what @thornomad recommended, with custom button, but pass the insert some dummy data to make it appear where you wanted (possibly using `scrollTo` '0px' or 'bottom' if needed) then user can edit that data.

If you wanted to be tricky, maybe see if `rowFormatter` updates on editable changes, so it highlights any row that issnt filled out fully, and removes highlight once it is. Or use `onEditableInit`, `onPostBody` or any relevant callback to toggle some other styling or even maybe trigger click event on first editable anchor. 

However, the modal is easiest, especially if you dont really care about editing row afterwards, or find editable extension bit unintuitive for insertion.

Though if you do make a modal, do note fairly easy to use it to edit existing rows, just calling relevant 'update' method on the table when saving changing (changes should be sent via ajax to data source, but in `success` callback call to table to `updateRow` or similar)

http://issues.wenzhixin.net.cn/bootstrap-table/index.html

**Comment by djhvscf** [comment]
Close this issue because the solution was provided
