### ISSUE TITLE
[Feature] detailFormatter without wrapping 

### ISSUE THREAD

**Issue by thornomad** [wenzhixin/bootstrap-table#1852]
Hello - thanks again for the hard work on this.

I want to be able to use `detailFormatter` that does *not* wrap the output string inside of a `td`.  

#### Here is what currently happens:

```html
<tr class="detail-view">
  <td colspan="x">
    <!-- detailFormatter output goes here -->
  </td>
</tr>
```

#### Proposing option to enable output such as:

The *feature* I would like is to be able disable the wrapping in the `<td colspan="x"></td>` so that I may simply add my own '<td>` that will align perfectly with the rest of the table.

```html
<tr class="detail-view">
  <!-- detailFormatter output goes here -->
</tr>
```

I know this use case would break when a user enables `showColumns` ... however, for a basic table view it is very useful and pretty.  If you can think of an appropriate way to integrate this feature I would be happy to code it.

#### How to do it

One idea I had would be to add a setting such as `detailViewUnWrap` which, when `true`, would remove the wrapping.  

I wanted to ask though if this is a feature we could add and if this is the way you wanted to add it before I did the work.

Thanks.

**Comment by dabros** [comment]
@thornomad - i cant see a need for this, as it needs a TD to validate as html and layout properly.

Looking at  , this is enough of an outside use case that it fits exactly with why we make callbacks, in this case `onExpandRow`.

Use that callback/event (param atm include `index, row, $detail`) and then use basic jquery like `$.parent()` to manipulate it however you wanted.

If timing doesnt quite work, add some kind of selector in `detailFormatter` that can be picked up on in whatever event fits the bill, see how http://issues.wenzhixin.net.cn/bootstrap-table/index.html logs events and find what works best.

I can pretty much assure you that having custom option is not at all desired as it breaks html validation if used, unless you adding your own TD in which its irrelevant - just use `detail-formatter` and callbacks if needing to add extra classes or affect the TD or TR parent.

Btw - i also recall some use of formatter returning cellstyle type object, something like `{'classes':'blah'}` and apply that to the TD, but cant recall exact detail, cant see example, and unsure if detailFormatter does that but if you look at the code you can maybe find out.

**Comment by thornomad** [comment]
Hi @dabros - thanks for writing back.

You are right, the user would have to insert the `td` properly to validate.  This wouldn't work, for sure, when `showColumns` was true.  

I used your suggestion of moving the business to `onExpandRow` -- that seems to work just as well and is pretty easy to implement.  Here is how I did it for folks later down the road.

```javascript
// add an element to make searching a little easier so we don't have to loop
// through every .detail-row every time onExpandRow is called or in the case 
// that `expandAllRows` is used
function detailFormatter(index, row) {
  return '<span id="detail-row-' + index + '"></span>';
}

function onExpandRow(index, row) {
  // we need to know, obviously, how many columns are in the bootstrap-table,
  // but in this case we do! so lets add our columns:
  var html = [
    '<td></td>',
    '<td>some data</td>',
    '<td colspan="2">more data</td>',
    '<td colspan="3">less data</td>'
  ];

  $('#detail-row-' + index).closest('td').replaceWith(html.join(''));
}
```

Thanks again!

**Comment by thornomad** [comment]
One last thought after implementation - this is a performance hit when we use `expandAllRows` ... how would you feel about adding a `onExpandAllRows` trigger?  See any additional uses for that?

**Comment by dabros** [comment]
@thornomad - interesting thought, but i cant really see need for that direct as `onPostBody` and `onResetView` and ect kinda cover any use case you can think of.

In no small part because i also cant see any massive performance gain from `onExpandAllRows`.

How about inside whatever handler calls `expandAllRows` you trial what code you think should be used, commenting out your `onExpandRow` code and toggling between the two to test performance.

If there is a noticable gain then pls share here, and we can see if perhaps better using a simple toggle variable (high scope boolean that says whether to execute certain logic) to disable per-row on all-row requests, and visa-versa, or whether maybe it is enough of a different to be a need.

**Comment by thornomad** [comment]
@dabros - all right, if I have time and energy I will look into seeing if this is worth the effort; appreciate you thinking this through with me.
