### ISSUE TITLE
Converting Text String within JSON File to Date and Time

### ISSUE THREAD

**Issue by TheoBearman** [wenzhixin/bootstrap-table#1855]
Good evening,

I am using [this JSON file](http://api.vateud.net/online/pilots/eg.json) in one of my tables. As you can see, one of the JSON objects is `logon` which gives a plain text string for when the person logged on to the VATSIM Network.

My code for my table which is displayed on [this site](https://vatsim.theobearman.com/) is as follows:

```html

<table data-toggle="table" data-url="http://api.vateud.net/online/pilots/eg.json" data-cache="false" data-show-refresh="true" data-query-params="queryParams" data-pagination="true" data-search="true" data-page-list="5, 10, 25, 50, 100, All" data-height="400"
				data-sort-name="callsign" data-sort-order="asc">
					<thead>
						<tr>
							<th data-field="callsign" data-halign="center" data-align="center" data-sortable="true">Callsign</th>
							<th data-field="name" data-halign="center" data-align="center" data-sortable="true">Name</th>
							<th data-field="aircraft" data-halign="center" data-align="center" data-sortable="true">Aircraft</th>
							<th data-field="origin" data-halign="center" data-align="center" data-sortable="true">Departure Airport</th>
							<th data-field="destination" data-halign="center" data-align="center" data-sortable="true">Arrival Airport</th>
							<th data-field="flight_type" data-halign="center" data-align="center" data-sortable="true">Type</th>
							<th data-field="route" data-halign="center" data-align="center" data-sortable="true">Route</th>
							<th data-field="altitude" data-halign="center" data-align="center" data-sortable="true">Altitude</th>
							<th data-field="groundspeed" data-halign="center" data-align="center" data-sortable="true">Groundspeed</th>
							<th data-field="transponder" data-halign="center" data-align="center" data-sortable="true">Squawk</th>
<th data-field="logon" data-halign="center" data-align="center" data-sortable="true">Logon Time</th>
						</tr>
					</thead>
				</table> 
```

Is there a way of using Bootstrap-Tables to parse the plain text string into a formatted date and time stamp before injecting it into the table?

Thanks in advance.

**Comment by dabros** [comment]
@TheoBearman 

`formatter` column option

Plenty of examples out there, including official doco

http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options
http://issues.wenzhixin.net.cn/bootstrap-table/#options/format.html

Just google if unsure, or search through issues or StackOverflow (which is where all non-bug and non-feature-request related questions should be asked: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker)

**Comment by TheoBearman** [comment]
@dabros 

I'm not sure how I can use the `formatter` option to achieve what I set out in the OP.

I am aware it is better to ask on StackOverflow and I have. After not receiving any replies, I posted here.

Thanks again.

**Comment by dabros** [comment]
@TheoBearman 

http://stackoverflow.com/questions/3552461/how-to-format-a-javascript-date

http://jsfiddle.net/wenyi/e3nk137y/21/

Create a formatter, asign as seen in fiddle (via js or via data-formatter, both work and see 'getting started' if dont know what that means). Your formatter returns whatever value you want to display, in this case formatted datestring,

Btw, as seen in doco, that formatter now has more param but you can use just 'value' if thats all you need.

**Comment by TheoBearman** [comment]
How do I configure the formatter to take the `logon` string from the JSON file and then convert that to a formatted date and time?

**Comment by dabros** [comment]
@TheoBearman - google how to format a javascript datetime (like link above) then return that from the formatter

It is a very simple process, 2 steps, both of which have ample examples in links above and elsewhere

**Comment by TheoBearman** [comment]
That bit is fine; what I need to know is how to get a plain text string from an external JSON file for use in the date formatting function.

**Comment by dabros** [comment]
@TheoBearman 

Thats what a formatter does.

Create a column, doesnt even have to be for the logon index as you can use the `row` param to access all index's of that row.

http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

**Comment by dabros** [comment]
@TheoBearman - as stated in http://stackoverflow.com/questions/34649887/how-to-use-bootstrap-table-to-parse-plain-text-string-to-unix-time, please stop double posting.

If you want to ask on SO, put a link here and ask for users help to post in SO to this question.

You can leave this github issue open if you want, but clearly direct users to the SO post and stop double posting here. Or close the SO and stay here.

**Comment by wenzhixin** [comment]
close this issue
