### ISSUE TITLE
Add field to footer-formatter.

### ISSUE THREAD

**Issue by wcatron** [wenzhixin/bootstrap-table#1856]
Feature request: I'm writing a formatter for the footer of column, I'm using the same formatter for a few different tables. One table field is "balance", the other is "amount". Would others find an optional field parameter useful in the formatter function, much like regular formatters.

**Current Usage**
```html
<!-- Table with a balance column. -->
<th data-field="balance" data-footer-formatter="formatterFooterTotalBalance">Balance</th>
```
```html
<!-- Table with an amount column. -->
<th data-field="amount" data-footer-formatter="formatterFooterTotalAmount">Amount</th>
```
```js
formatterFooterTotalBalance(data) {
    var total = 0;
    $.each(data, function (i, row) {
        total += row.balance;
    });
    return 'Total: '+total;
}
formatterFooterTotalAmount(data) {
    var total = 0;
    $.each(data, function (i, row) {
        total += row.amount;
    });
    return 'Total: '+total;
}
```

**Desired Usage**
```html
<!-- Table with a balance column. -->
<th data-field="balance" data-footer-formatter="formatterFooterTotal">Balance</th>
```
```html
<!-- Table with an amount column. -->
<th data-field="amount" data-footer-formatter="formatterFooterTotal">Amount</th>
```
```js
// Both columns function the same way but the data is different.
formatterFooterTotal(data, field) {
    var total = 0;
    $.each(data, function (i, row) {
        total += row[field];
    });
    return 'Total: '+total;
}
```

I can probably write this but wanted to know if this had been previously conceived or if it conflicts with other goals.

**Comment by dabros** [comment]
@wcatron - im still a bit unclear exact use case, can you please lay it out in terms of current output vs desired output?

**Comment by wcatron** [comment]
I've updated my original post with a more detailed use case. It allows for columns with the same functional footer but with a different field name. Much like regular formatters that format the same way, but with a different field for the data.

**Comment by dabros** [comment]
@wcatron - i see what you are getting at.

Here is an excerpt from the column options: http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

<table>
<thead style="display: table-header-group;"><tr><th style="" data-field="0" tabindex="0"><div class="th-inner ">Name</div><div class="fht-cell"></div></th><th style="" data-field="1" tabindex="0"><div class="th-inner ">Attribute</div><div class="fht-cell"></div></th><th style="" data-field="2" tabindex="0"><div class="th-inner ">Type</div><div class="fht-cell"></div></th><th style="" data-field="3" tabindex="0"><div class="th-inner ">Default</div><div class="fht-cell"></div></th><th style="" data-field="4" tabindex="0"><div class="th-inner ">Description</div><div class="fht-cell"></div></th></tr></thead>
<tbody>
<tr data-index="19"><td style="">formatter</td><td style="">data-formatter</td><td style="">Function</td><td style="">undefined</td><td style="">
        The context (this) is the column Object. <br>
        The cell formatter function, take three parameters: <br>
        value: the field value. <br>
        row: the row record data.<br>
        index: the row index.</td></tr>
<tr data-index="20"><td style="">footerFormatter</td><td style="">data-footer-formatter</td><td style="">Function</td><td style="">undefined</td><td style="">
        The context (this) is the column Object. <br>
        The function, take one parameter: <br>
        data: Array of all the  data rows. <br>
        the function should return a string with the text to show in the footer cell.
    </td></tr>
</tbody>
</table>

Ofcourse, this limitation can be overcome by creating 'stubs', something like:

```javascript

formatterFooterTotalBalance(data) {
  return formatterReturnTotalString(data,row.balance,'Total: ');
}
formatterFooterTotalAmount(data) {
  return formatterReturnTotalString(data,row.amount,'Total: ');
}
formatterReturnTotalString(data,field,prefix) {
    var total = 0;
    $.each(data, function (i, row) {
        total += row[field];
    });
    return prefix+total;
}

```

However, as i have come across this concept/type-of-request a few times now, i think it sounds like a practical **PR**, and will be welcome (for both `formatter` and `footerFormatter`): https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

Btw - I also did play with something similar in #678 and #725, notably see the fiddle http://jsfiddle.net/dabros/z8bL5fg0/ and the 'name' param I pass into my `formatter` at bottom of js panel. Just sharing if of interest, not saying that its the way to go at all, but you can see how i did it as all mods in js panel (i suggest copy over to local and explore there, if interested).

**Comment by wenzhixin** [comment]
> The context (this) is the column Object. 
So you can use `this.field` to get the field name.
