### ISSUE TITLE
Changing Number of Fixed Columns Breaks Table Alignment.

### ISSUE THREAD

**Issue by patricklouipedro** [wenzhixin/bootstrap-table#1857]
Hi. i'm used the fixed columns extension. and im currently facing a problem whenever i change the number of fixed columns.

here is an example:
http://jsfiddle.net/fLjkskpe/3/

TIA for the help.

**Comment by jayjo** [comment]
While using the fixed columns extension table rows don't align within when there are multiple lines of text within the cells: [http://jsfiddle.net/9qnpLa6o/]

**Comment by gotohr** [comment]
Also, alignment of rows matching fixed column row is broken, As you scroll further down the table you can see discrepancy between fixed column vertical position and rest of row.

**Comment by wenzhixin** [comment]
Added new version fixed-columns extension: https://github.com/wenzhixin/bootstrap-table/commit/91977960a5705cd074067b2670483b5e9d5c1f44

**Comment by wenzhixin** [comment]
Develop example: http://dev.bootstrap-table.com/examples/#extensions/fixed-columns.html
