### ISSUE TITLE
bootstrapTable调用的ajax请求，可否应用jquery全局事件处理机制

### ISSUE THREAD

**Issue by xiegang666** [wenzhixin/bootstrap-table#1858]
如添加session会话过期处理机制
$.ajaxSetup({
		        contentType: "application/x-www-form-urlencoded;charset=utf-8",
		        cache: false,
		        complete: function(XHR, TS){
		            var resText = XHR.responseText;
		            var sessionstatus = XHR.getResponseHeader("sessionstatus");
		            var loginPath = XHR.getResponseHeader("loginPath");
		            if (911 == XHR.status && "timeout" == sessionstatus) {
		                // 也可以使用下面的原生js的确认框，如果确认则跳转
		                if(window.confirm('session过期', '您的会话已经过期，请重新登陆后继续操作！')) {
		                    window.location.replace(loginPath);
		                }
		                return;
		            }
		        }
		    });

找了好久都没找到那里设置的

**Comment by johntostring** [comment]
http://bootstrap-table.wenzhixin.net.cn/documentation/ 文档中的`ajaxOptions`是你想要的吗

**Comment by wenzhixin** [comment]
如 @johntostring 所说
