### ISSUE TITLE
A way to give Json Data as input to the Bootstrap table

### ISSUE THREAD

**Issue by divyamv** [wenzhixin/bootstrap-table#186]
I have Json Data in my JS .I want to populate my bootstraptable with "items"
items= #{ListPortletDefaultviewView.jsonList};

I am not getting the data from a remote request.how do i set that?

```
<table data-toggle="table"  id="table" class="table"  DATA-URL="" data-sort-name="PR_x0020_Spec" data-sort-order="desc">
    <thead>
        <tr>
        <th style="width:20%" data-sortable="true" data-field="PR_x0020_Spec"> PR Spec </th>
        <th data-sortable="true" >Revision</th>
        <th data-sortable="true">Product name</th>
        <th data-sortable="true" >Product Geographical Scope</th>
        <th data-sortable="true">ERP  Code</th>
        </tr>
     </thead>
</table>
```

**Comment by ChiragDhangar** [comment]
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1" import="java.sql.*"%>
<!DOCTYPE html>

<html lang="en">
<head>
<%@include file="Externalfiles.jsp" %>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      
<script>
var newDta
$.ajax({
    url: "listRequest",
    async: true,
    crossDomain: true,
    type: "post",
    dataType: "json",
    success: function (data) {
    	 var newDta = JSON.stringify(data); 
        call_table();
    	
    	
    }});
</script>
        
 
 </head>
 
  <body>

           <div id="pad-wrapper">

                        
                        
                        
                        

<div class="row">

<div class="table-responsive">
      <table
      id="table"
      data-cookie="true"
      data-url="data.json"
      data-click-to-select="true"
      data-cookie-id-table="depreciationReportTable">
        <thead>
            <tr role="row">
            <th class="col-sm-1">Enviorment_Name</th>
            <th class="col-sm-1">Total_Asset</th>
          <th class="col-sm-1">Total_Asset</th>
          <th class="col-sm-1">Total_Asset</th>
         
              </tr>
    </thead>
    <tbody>

                			
						


                
                      </tbody>
</table>

</div>

</div>

                </div>
           

  <script type="text/javascript">
  function call_table()
  {
    $('#table').bootstrapTable({
        classes: 'table table-responsive table-striped table-bordered',
        undefinedText: '',
        method:'POST',	
        url:'listRequest',
        iconsPrefix: 'fa',
        showRefresh: false,
        search: true,
        pageSize: 10,
        pagination: true,
        sidePagination: 'client',
        sortable: true,
        cookie: true,
        mobileResponsive: true,
        showExport: true,
        showColumns: true,
        exportDataType: 'all',
        exportTypes: ['csv', 'txt','json','xml','excel','sql','pdf'],
        maintainSelected: true,
        paginationFirstText: "First",
        paginationLastText: "Last",
        paginationPreText: "Previous",
        paginationNextText: "Next",
        pageList: ['10','25','50','100','150','200'],
        icons: {
            paginationSwitchDown: 'fa-caret-square-o-down',
            paginationSwitchUp: 'fa-caret-square-o-up',
            columns: 'fa-columns',
            refresh: 'fa-refresh'
        },
        columns: [
                  {field:'server_id'},
                  {field:'server_id'},
                  {field:'server_id'},
                  {field:'server_id'}
                  
                  
                  ]                  

    }); 
  }
</script>

    </body>
</html>

**Comment by anurag-daware** [comment]
Hey guys when I try this method at my end its isn't working at all, see following code, can you please help what I am missing:

bootstrap.min.css v.3.2
bootstrap-table.css v.1.8.1
jquery.min.js v.3.0
bootstrap.min.js v.3.2
bootstrap-table.js v.1.10.1

```
<!DOCTYPE html>
<html>
<head>
    <title>Table Data Addition</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="bootstrap.min.css">
    <link rel="stylesheet" href="bootstrap-table.css">
    <script src="jquery.min.js"></script>
    <script src="bootstrap.min.js"></script>
    <script src="bootstrap-table.js"></script>
</head>
<body>
    <div class="container">
        <table id="table"
        data-toggle="table"
               data-toolbar="#toolbar"
               data-height="460">
        <thead>
            <tr>
                <th data-field="id">Item ID</th>
                <th data-field="name">Item Name</th>
                <th data-field="price">Item Price</th>
            </tr>
        </thead>
    </table>
    </div>
<script>
    var $table = $('#table');
    var mydata = 
[
    {
        "id": 0,
        "name": "test0",
        "price": "$0"
    },
    {
        "id": 1,
        "name": "test1",
        "price": "$1"
    },
    {
        "id": 2,
        "name": "test2",
        "price": "$2"
    },
    {
        "id": 3,
        "name": "test3",
        "price": "$3"
    },
    {
        "id": 4,
        "name": "test4",
        "price": "$4"
    },
    {
        "id": 5,
        "name": "test5",
        "price": "$5"
    },
    {
        "id": 6,
        "name": "test6",
        "price": "$6"
    },
    {
        "id": 7,
        "name": "test7",
        "price": "$7"
    },
    {
        "id": 8,
        "name": "test8",
        "price": "$8"
    },
    {
        "id": 9,
        "name": "test9",
        "price": "$9"
    },
    {
        "id": 10,
        "name": "test10",
        "price": "$10"
    },
    {
        "id": 11,
        "name": "test11",
        "price": "$11"
    },
    {
        "id": 12,
        "name": "test12",
        "price": "$12"
    },
    {
        "id": 13,
        "name": "test13",
        "price": "$13"
    },
    {
        "id": 14,
        "name": "test14",
        "price": "$14"
    },
    {
        "id": 15,
        "name": "test15",
        "price": "$15"
    },
    {
        "id": 16,
        "name": "test16",
        "price": "$16"
    },
    {
        "id": 17,
        "name": "test17",
        "price": "$17"
    },
    {
        "id": 18,
        "name": "test18",
        "price": "$18"
    },
    {
        "id": 19,
        "name": "test19",
        "price": "$19"
    },
    {
        "id": 20,
        "name": "test20",
        "price": "$20"
    }
];

$(function () {
    $('#table').bootstrapTable({
        data: mydata
    });
    console.log(mydata);
});
</script>
</body>
</html>

```

**Comment by anurag-daware** [comment]
When I removed data-toggle="table"
               data-toolbar="#toolbar" properties, it started working, can someone please help understand why is this case?
Thanks/

**Comment by limingsheng** [comment]
me too, but don‘t know why：（

**Comment by ash-arora** [comment]
I am very pleased with this add-on table library but this is the first  time i have found a major issue with that I cannot seem to get my arms around.

@wenzhixin  - can you clarify please? I am sure we are doing something wrong here but we don't know.

**Comment by Tahiche** [comment]
Hi,
It seems that when "data-toggle='table'" is specified any calls to "$('#table').bootstrapTable()" are completely ignored. All options, etc are not rendered.
I beleive if you use "data-toggle='table'" you must set ALL options via data-* attributes (data-url="mydata.json",etc ....), not through the {options} object.
I haven´t thoroughly tested this or debugged the code, but through trial-and-error this seems to be the case. A console waring message would´ve been nice. 
BTW, are there any "debugging" options?. In cases like this where nothing is loaded it´d be nice to see what´s actually happening.
