### ISSUE TITLE
How do I use custom JSON data to Server Side Pagination?

### ISSUE THREAD

**Issue by liunewshine** [wenzhixin/bootstrap-table#1862]
{
    "total": 100,
    "rows": [
        {
            "github": {
                "name": "bootstrap-table",
                "count": {
                    "stargazers": 768,
                    "forks": 183
                },
                "description": "An extended Bootstrap table"
            }
        }
    ]
}

The example's json format is this,but my json is not this,how to custom "total","rows" name

**Comment by liunewshine** [comment]
I had ask this question yesterday,but its disappered,very puzzled to me

**Comment by dabros** [comment]
@liunewshine - you asked it in the wrong place, see recent activity your profile: https://github.com/liunewshine

Please close that issue in boostrap-table-examples, backlinking to here for ref

Now to the issue.

As seen in http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

<table>
<thead><tr><th style="" data-field="0" tabindex="0"><div class="th-inner ">Name</div><div class="fht-cell"></div></th><th style="" data-field="1" tabindex="0"><div class="th-inner ">Attribute</div><div class="fht-cell"></div></th><th style="" data-field="2" tabindex="0"><div class="th-inner ">Type</div><div class="fht-cell"></div></th><th style="" data-field="3" tabindex="0"><div class="th-inner ">Default</div><div class="fht-cell"></div></th><th style="" data-field="4" tabindex="0"><div class="th-inner ">Description</div><div class="fht-cell"></div></th></tr></thead>
<tr data-index="15"><td style="">url</td><td style="">data-url</td><td style="">String</td><td style="">undefined</td><td style="">
            A URL to request data from remote site.
            <br>Note that the required server response format is different depending on whether the 'sidePagination'
            option is specified. See the following examples:
            <ul>
                <li><a href="https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data1.json">Without server-side pagination</a></li>
                <li><a href="https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data2.json">With server-side pagination</a></li>
            </ul>
        </td></tr>
</tbody>
</table>


Server side pagination means that you already need to affect that json return to return the subset of rows, and while you can use `responseHandler` to tweak the return before loaded into table, this does NOT SOLVE your use case, as it cant possibly know the total.

You have to setup your server side pagination script to return that format, else you client-side pagination.

**Comment by dabros** [comment]
@liunewshine - looks like `responseHandler` should solve that issue, given what i see in the linked topic

Basically something like you see in the example i linked, but matching your incoming json - use console.log and ect to help you tweak it.
