### ISSUE TITLE
Filling table from a php file which retrieves data from mySQL

### ISSUE THREAD

**Issue by angelopaapa** [wenzhixin/bootstrap-table#1863]
Hello guys @wenzhixin and @dabros (I saw you many times on discussions that I viewed)
OK, here is the situation:
I have a .php file (let's say A) where I use jquery ajax call to fill a table from another .php file (let's say B) that retrieves data from mysql. 
It's working fine! 
Now, I want to adapt it to bootstrap-table so that I can have features such as "searching", "pagination" (at least) added. The problem is, I don't know how to modify my scripts for that sake.

A file
````
<body onload="display()">
    <div id="info"></div>
    <div id="feedback"></div>
</body>

<script>
    function display() {
        $.ajax({
            type: 'GET',
            url: 'getdata.php',
            success: function (data) {
                $('#feedback').html(data);
            }
        });
    }
</script>
````
B file
````
<?php
    require_once 'connection.php'; //my connexion infos
?>

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Employes
        </div>
        <div class="panel-body">
            <table class="table table-hover table-bordered ">
                <thead>
                <tr>
                    <th>Matricule</td>
                    <th>Nom et Prenoms</td>
                    <th>Fonction</td>
                    <th>Departement</td>
                </tr>
                </thead>
                <?php
                    $req = "SELECT * FROM employes";
                    if ($resultat = $connexion->query($req)) {
                        $ligne = $resultat->fetch_all(MYSQL_ASSOC);
                        foreach ($ligne as $list) {
                            ?>
                            <tr>
                                <td><?php echo stripslashes($list['code_emp']); ?></td>
                                <td><?php echo stripslashes($list['titre_emp']) ; ?></td>
                                <td><?php echo stripslashes($list['fonction_emp']); ?></td>
                                <td><?php echo stripslashes($list['departement_emp']); ?></td>
                            </tr>
                            <?php
                        }
                    }
                ?>
            </table>
        </div>
    </div>
</div>
````
Here is what I actually have
![1](https://cloud.githubusercontent.com/assets/6215471/12206302/0d3e1e0c-b638-11e5-9609-bbc8a1b8766b.JPG)

Here is what I get when I tried to change this ```` <table class="table table-hover table-bordered "> ```` to that ```` <table data-toggle="table" data-pagination="true" data-page-size="5" data-search="true">```` in the B file

![2](https://cloud.githubusercontent.com/assets/6215471/12206356/51bf767a-b638-11e5-8c97-289f87fb192b.JPG)

As you can see, it doesn't work like I was expected.

Can you please advise?

**Comment by djhvscf** [comment]
Have you checked the console (F12)?? @angelopaapa

**Comment by angelopaapa** [comment]
@djhvscf I've checked it, no error is shown

**Comment by wenzhixin** [comment]
Many issues related this: https://github.com/wenzhixin/bootstrap-table/search?q=php&type=Issues&utf8=%E2%9C%93

https://github.com/wenzhixin/bootstrap-table/issues/25
https://github.com/wenzhixin/bootstrap-table/issues/1070
