### ISSUE TITLE
Loading SharePoint List Data?

### ISSUE THREAD

**Issue by jmutk** [wenzhixin/bootstrap-table#1864]
Hello!

I have what I believe is a simple question, but again I am fairly new to this.

First, the plugin is awesome and want to make this work via javascript/jquery, so I'm hoping there is a way. On to the question...

I have a SharePoint 2013 list where I keep a list of projects.  I have been trying to use the REST API with OData to return the list data.  I've been able to retrieve the data with a straight forward AJAX request (I can see it in my console log). However, I can't seem to figure out how to get the data to the data option for the table.

I also tried loading the table via the options provided with the plugin.  However, even though I define the dataType to JSON it still returns atom-xml formatted data, I think this is probably the result of the api. 

Either way, I'm stuck any help would be greatly appreciated.

AJAX attempt code...
````
$(document).ready(function(){
    $.ajax({
		url: "http://.../_api/web/lists/getByTitle('Projects List')/items",
		method: "GET",
		headers: {"Accept": "application/json; odata=verbose"},
		success: function(data) {
			console.log(JSON.stringify(data.d)),
			alert('Request Successful'),
			$('#table').bootstrapTable({
				columns: [{
					field: 'Title',
					title: 'Description'
				}],
				data: data.d
			});
		}
	});
})
````

Plugin Options code....
````
$('#table').bootstrapTable({
		method: "get",
		url: "http://.../_api/web/lists/getByTitle('Projects List')/items",
		dataType: 'json',
		responseHandler: function(res){
                        return res.results, 
                },
		columns: [{
			field: 'Title',
			title: 'Description'
		}]
	});
````
Again the table loads but can't seem to load data...

**Comment by dabros** [comment]
@jmutk 

`responseHandler` allows you to configure whatever the data-url returns before it attempts to load it into the table.

So search for how to process that atom-whatever return into proper json as seen in `url` description on http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options, then put similar code into `responseHandler`

The only other real option would be searching for "export sharepoint 2013 as json" - a google search that showed a bunch of promising looking results to me.

**Comment by wenzhixin** [comment]
Thanks for @dabros, close the issue.
