### ISSUE TITLE
Custom input with editable

### ISSUE THREAD

**Issue by rajapulau** [wenzhixin/bootstrap-table#1865]
How about custom input if we using extension editable?
for example like https://vitalets.github.io/x-editable/demo-bs3.html#address

**Comment by dabros** [comment]
@rajapulau 

As has been repeated in the documentation, #1850, #1832, ect - the `editable` column option is an object, just use javascript to initiate the table and pass in a x-editable object that would achieve your outcome.

https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable


Absolutely nothing to do with bootstrapTable past that point, so search SO or elsewhere for x-editable topics if still unsure.

**Comment by wenzhixin** [comment]
http://jsfiddle.net/e3nk137y/4232/
