### ISSUE TITLE
Pagination Problem

### ISSUE THREAD

**Issue by Mitsaras1911** [wenzhixin/bootstrap-table#1866]
If i am on page one, and hit the check all checkbox, all the records are checked. But if i move to page 2 and then back to page 1, all the selected records are un-checked, i want to stay checked Is there any solution to this?
Thanks!!!

**Comment by dabros** [comment]
@Mitsaras1911 

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

`maintainSelected`

There were some bugs with its implementation, but they been fixed i believe, search github (removing 'is:open') for more info on that if desired.

**Comment by wenzhixin** [comment]
client: `maintainSelected`
server: 
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/917.html
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/1167.html
