### ISSUE TITLE
Unable to get the result from data-formatter when using the search

### ISSUE THREAD

**Issue by Feefty** [wenzhixin/bootstrap-table#1867]
Here's the code that I use to implement the table

    <table data-toggle="table" data-url="exam.json" data-pagination="true" data-search="true" data-show-refresh="true" data-toolbar="#toolbar">
	<thead>
		<tr>
			<th colspan="6" data-align="center">Exams</th>
		</tr>
		<tr>
			<th data-field="exam.title" data-formatter="examTitleFormatter" data-sortable="true">Title</th>
			<th data-field="exam.exam_type.name" data-sortable="true">Type</th>
			<th data-field="start" data-sortable="true">Start</th>
			<th data-field="end" data-sortable="true">End</th>
			<th data-field="created_at" data-sortable="true">Date Added</th>
		</tr>
	</thead>
</table>

So when I tried to search for the title of the exam it always returns the "No matching records found"

**Comment by dabros** [comment]
@Feefty - we need a fiddle to help you with this

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
http://bootstrap-table.wenzhixin.net.cn/examples/

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
