### ISSUE TITLE
Is there a method that i can trigger search manually in client side.

### ISSUE THREAD

**Issue by aisuhua** [wenzhixin/bootstrap-table#1868]
I use client search, but i don't like use the default toolbar search box. I put the search box in the other place of the page.

So, I want that the behaviors of  my search box is same as the default search box. But i cann't do this.

For that, i change the source code like that: (bootstrap-table.js lines 1058-1069)

```
//$search = this.$toolbar.find('.search input');

//below is my search box
$search = $('.mysearch input');

$search.off('keyup drop').on('keyup drop', function (event) {
	clearTimeout(timeoutId); // doesn't matter if it's 0
	timeoutId = setTimeout(function () {
		that.onSearch(event);
	}, that.options.searchTimeOut);
});
```
But is not a good solution. Is there any other method to do this.

Thinks !

**Comment by dabros** [comment]
@aisuhua 

There are ways to do this, but no super elegant one line solution for your exact use case, but see #1827 for inspiration on a **PR** or minimal base code mods. I also stumbled across #1810, maybe of interest in accessing search input, in unlikely case some issue with that.

See `filterBy` as a 'maybe' option, but unsure if you can pass generic search into there.

Same for `refresh`, it does allow you to pass in `query` object, and maybe 'search' (or similar) index works there, worth a try, but im doubtful

What your best bet is would be to use something like #1730. The example linked to from there is different from custom toolbar fiddle in #1765, but that or other fiddle should provide easy base for you to play with. It may be setup for server side, but there should be no difference to create your custom toolbar and use client side. 

Once you get client side working, remove search and 'ok' from the toolbar and use some selector to attach logic to it outside custom toolbar.

If you get stuck then share your progress here with working fiddle, but `queryParam` and that click event handler should work fine for client side i believe

**Comment by djhvscf** [comment]
Please use resetSearch method

**Comment by aisuhua** [comment]
Thinks ! 
@dabros  Thanks for your detailed answers. I check every cache in it. At the end, like the @djhvscf said. I use `resetSearch` method.
ps: `resetSearch`  method is not in document. So, It should be added.

In addition, I think `filterBy` method is also a good choice. But the problem is that It is strict search and has no Fuzzy search.

Because that I search  about 3000  data (everyone has 10 columns ) in client. 
If I use  `resetSearch` method search all the columns. It will be foreach 3000 * 10  = 6000.

But, if i concat the each row as a filed, and than filterBy the field. It will foreach only 3000 count. 
It will be fast doesn't it ?

Thinks !

**Comment by djhvscf** [comment]
-Yes, you are right.. But can you open a new PR un order to improve the filterBy función? @aisuhua

**Comment by aisuhua** [comment]
I want to improve this very much. But now my javascript skill is not very good. To write  good javascript code is hard work for me. Later I will strengthen this aspect. Thank.

**Comment by dabros** [comment]
@djhvscf - thanks for that, but yeh not in doco so i had feeling something existed but just couldnt find it

**Comment by aisuhua** [comment]
How about to add the "match exactly" option, not the strictSearch (it only match lowerCase or upperCase).

I think it can be used in some special situation.
Like the google search do:

![](http://7xj8ix.com1.z0.glb.clouddn.com/match-exactly.png)

**Comment by dabros** [comment]
@aisuhua - i cant speak for @djhvscf , but if you do a fiddle (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports) and use `onPostHeader` or similar callback you can emulate what you mean more easily, and how it might work.

You could also include bootstrap-table or filter-control plugin file inline and make changes to it to achieve functionality as well as look and feel. This would almost definetly be needed for it to become an approved **PR** anyway.
