### ISSUE TITLE
Selectize.js dropdown not visible in bootstrap-table header

### ISSUE THREAD

**Issue by wexwell** [wenzhixin/bootstrap-table#1871]
Here is the issue; I am using a selectize.js dropdown in the header to filter data. I did have a select2, BUT I am finding bugs where it does multiple json pulls from the server. The latest select2 update has helped the bug, but it still exists.

In attempting to use selectize.js I am running into a new problem. When you click on it, and it drops down it is behind the datatable (I do not have this problem with a 'normal' select box OR the select2. If search for the number of one of the items in the table and then click under the box it will select that item (so the selectize is initializing and functioning).

The code is honestly pretty simple.

$('#table').bootstrapTable({data: data});

$('#finditem').selectize({
    valueField: 'id',
    labelField: 'name',
    searchField: 'name',
    placeholder: 'Item Name',
    options: data
});

**Comment by wenzhixin** [comment]
please provide a jsfiddle, thanks

**Comment by dabros** [comment]
@wexwell - please provide a fiddle for this

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wexwell** [comment]
I apologize I forgot to include it (I had it ready) - here is the codeply. 

http://www.codeply.com/go/JZ58uYkbc5

**Comment by dabros** [comment]
@wexwell

So you made one typo, using `#master` instead of `#table`, but once i fixed that i saw what you were talking about.

Playing with css got me nowhere, and cant really of any other way despite trying to add more selectors or complimenting rules for positive or negative z-index for surrounding elements too
``` 
thead, th, .th-inner, .selectize-control, .selectize-input, .selectize-dropdown, .selectize-dropdown-content, .selectize-dropdown-content div{
z-index:999999;    
}
````

However, why are you fixed on using this awkward approach to selectivize?

Have a look at the **filter-control** extension

http://bootstrap-table.wenzhixin.net.cn/extensions/
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/filter-control
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html

That pretty much does what your wanting to do, and at very least could serve as inspiration as it wraps the select and applies some other rules.

Maybe you can even attach 'selectivize' type behaivour to them, you can save and reapply listeners/handlers/events via jquery even if you destroy and recreate the entire input - though only go that way if actual need.

But if you do enhance filter-control with selectivize type behaivour, whether via callbacks or even by your own fork of that plugin, please do share here :)

**Comment by wexwell** [comment]
I like the way this sets up and performs much better. These are cascading and autocomplete. Here is a mock up page I setup with some data that shows how it functions when it is 'all done' (this version is done with select2, which has some bugs).

http://tinkeringtester.com/swtor/stats/dps.html

**Comment by djhvscf** [comment]
It looks good.. Can you share with us the source code?? I would like to check it @wexwell

**Comment by wexwell** [comment]
you can do a 'view source' on the page and see all the source code. If you would like the php code to the server access pages I am more than willing to share that too.

**Comment by djhvscf** [comment]
Ok, thanks for your example @wexwell

**Comment by wexwell** [comment]
@djhvscf you're welcome

**Comment by wexwell** [comment]
after I got looking at the codeply I attached the wrong one (after the error was mentioned). I did not realize I had 2 of them for this same thing :(  (updated link in original comment, and it is also listed below).

http://www.codeply.com/go/FiMTCSTrEk

**Comment by dabros** [comment]
@wexwell @djhvscf @wenzhixin - i agree that http://tinkeringtester.com/swtor/stats/dps.html looks great, and doesnt appear to have so much custom code that a plugin (or update to filter plugin even, if thats desired) is impossible.

I have no time for it now, but please do attach resource label and bookmark if you think it useful and a possible optional feature for filter-control, though unsure of these 'bugs' refered to so maybe let it sit till stable release?

**Comment by wexwell** [comment]
OK - I thought this was a select2 problem. However I moved one of the boxes out the table and it is no longer submitting everything double. However, any box inside of the following statement still submits double each time. (I tried changing it so I am not initializing the event with a class and use the id instead. this made no difference)

Statement
$('#main').on('post-header.bs.table', function () {

Website
http://tinkeringtester.com/swtor/stats/dps.html

**Comment by dabros** [comment]
@wexwell - pls also link to related posts so clearer where actual answer should be posted - especially as this is closed issue that appears slightly different too

**Comment by wexwell** [comment]
The issue isn’t “slightly different” it is the exact same issue, with the exception that the problem is further isolate to prove the problem is not with select2.

**Comment by dabros** [comment]
@wexwell - i actually deleted that post as soon as i made it, as i re-read both issues as  i always do after posting. Pls delete your follow up comment too to remove clutter

thanks

**Comment by wexwell** [comment]
All the code is here, but data requests are not working. I have not found a service that will allow external URL calls (if they did everyone would just turn them into a hosting site). It is doing everything except actually loading the database requests.

http://plnkr.co/edit/hZDOXMMwFSTjf351LkIn?p=preview

**Comment by wenzhixin** [comment]
If the problem exists, reopen the issue.

**Comment by wexwell** [comment]
the issue was reopened in this post https://github.com/wenzhixin/bootstrap-table/issues/1998
