### ISSUE TITLE
Can't select export excel

### ISSUE THREAD

**Issue by kennedyzt** [wenzhixin/bootstrap-table#1877]
If you use sidePagination: 'client' can do it,but not 'service'

**Comment by dabros** [comment]
@kennedyzt - i assume you mean 'server', which has absolute 0 impact on bootstrap-export plugin.

Please create a fiddle showing this issue: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by kennedyzt** [comment]
Can you give me a case? I need a case implementation choice export using the 'server' .

**Comment by wenzhixin** [comment]
#1765

**Comment by dabros** [comment]
@kennedyzt - there is no fiddle atm for server, but thats because it absolutely no different than for client side-pagination.

See the examples and doco for server side-pagination, have it working, then add export
