### ISSUE TITLE
get data from particular field

### ISSUE THREAD

**Issue by the1994** [wenzhixin/bootstrap-table#1878]
I use `getData`. but it returns all data in pages. 
Is it possible to get data from checked row's particular field?

**Comment by djhvscf** [comment]
In this moment you can use the getRowByUniqueId method. See this example: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getRowByUniqueId.html and this is the code of the example: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/methods/getRowByUniqueId.html @the1994

**Comment by the1994** [comment]
Thank you!!
