### ISSUE TITLE
table 表头和表格不对齐，用了您给的方法后对齐了 ，可是JS打印表格时依然显示不全表头

### ISSUE THREAD

**Issue by suoutsky** [wenzhixin/bootstrap-table#1879]
table 表头和表格不对齐，用了您给的方法后对齐了 ，可是JS打印表格时依然显示不全表头

**Comment by djhvscf** [comment]
Can you translate to english? @suoutsky

**Comment by suoutsky** [comment]
The table header table   aligned with your method after alignment, but  when i Calling the browser print function with JS，the table header table not  aligned

**Comment by wenzhixin** [comment]
How do you print the table? @sdespont

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!

**Comment by xiongxin2oo8** [comment]
请问你是怎么对齐的，我也是表头和内容不能对齐。@suoutsky

**Comment by wenzhixin** [comment]
用 `resetView` @xiongxin2oo8

**Comment by navyjiang** [comment]
我想在加载完调用 resetView, 发现时机还是早了，显示alert时，发现数据并未填充在表格里，请问如何才能在填完表格后调用 resetView呢？@wenzhixin，否则即便监听了resize事件，初始时表头还是不对齐呀。
$('#orderTable').on('load-success.bs.table', function (e, data) {        
        alert("sssssss")
        $('#orderTable').bootstrapTable('resetView');
})

**Comment by navyjiang** [comment]
服务器删除一行数据，前端执行 refresh 之后，表头又对不齐了，必须再手工刷新一下页面才行，看来还是得在渲染完表格调用一次 resetView，请问我要监听哪个事件合适呢？@wenzhixin

**Comment by wenzhixin** [comment]
@navyjiang，用最新版本，这个问题已经解决了。
