### ISSUE TITLE
Export Button is not shown even after using data-show-export="true"

### ISSUE THREAD

**Issue by divyamv** [wenzhixin/bootstrap-table#188]
http://jsfiddle.net/433n91rd/

i do not see the export button enabled even after using data-show-export="true"

**Comment by havok2063** [comment]
How do I add a filename to my exported table?  Right now it's being being named 'download' automatically.  Thanks.

**Comment by jloncha** [comment]
Hello, I'm new in Bootstrap and JavaScript, I have the same problem, but I put all the dependecies, the data-show-export="true" and still doesnt appear the export button. I have download the last version of all dependencies. Can somebody help me
[sociedades.txt](https://github.com/wenzhixin/bootstrap-table/files/378303/sociedades.txt)

**Comment by wenzhixin** [comment]
Please checkout this example: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html @jloncha

**Comment by jloncha** [comment]
I built my code base in that example, but still doesn't appear the button. I' m missing some dependency?

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/export.html#L13

**Comment by jloncha** [comment]
I use all the dependencys that the example uses.  But still doesn't appear the button..

**Comment by wenzhixin** [comment]
what version of bootstrap-table?

**Comment by jloncha** [comment]
I found my error, I was using bootstrap-table.js and bootstrap-table.min.js. I deleted the reference to bootstrap-table.js and it works. Thank you for your help. Now I have a diferent problem, Always exports all the records of table, no matter if I chose some. But I think its my function the problem. Thanks again!

**Comment by priya171** [comment]
showExport and showColumn not wirking in bootstrapv4

**Comment by wenzhixin** [comment]
@priya171 https://live.bootstrap-table.com/code/wenzhixin/3194
