### ISSUE TITLE
Prepare bootstrap-table for boostrap v4

### ISSUE THREAD

**Issue by oschni** [wenzhixin/bootstrap-table#1881]
Hello,

I am already using Bootstrap v4-dev for a little project. V4 changed the pagination styles so the bootstrap-table for v3 is not really looking nice. I fixed it for me.

To use new pagination styles I changed some lines in bootstrap-table.js. What is the prefered way to show this changes for everyone else?

**Comment by djhvscf** [comment]
Please first provide a fiddle with your change and then open a new PR. @oschni

**Comment by dabros** [comment]
@oschni - like djhvscf said, create a fiddle and a **PR** please

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests 

Scroll up on that link to find some example fiddles too, or see fiddle examples page off main site.

A fiddle will let us play and see difference, and if there's anything we can recommend we will prob demo it using that for you, else straight endorse your **PR** for next release.

Thanks

**Comment by sh1omi** [comment]
Hey @oschni ,
Did you already posted your custom bootstrap-table.js ? or anyone know how to make this js work with v4?

**Comment by wenzhixin** [comment]
Supported now.
