### ISSUE TITLE
Memory leak when returning table from a field formatter

### ISSUE THREAD

**Issue by urban-1** [wenzhixin/bootstrap-table#1885]
Hi all,

I have a very weird problem and a huge memory leak with the following:

```
   ...
   {
        field: 'engName',
        title: 'Name',
        formatter: myFormatter,
        class: "outer-cell",
    },
    ...
```

Now the formatter:
```
function myFormatter(apiValue, apiRow, apiRowIndex) {
    return "<table><tr><td></td></tr></table>" // <---- problem is here
}
```

The line marked causes:

1. The refresh of the bootstrap-table being a lot slower
2. Multiple refreshes lead fast to memory usage of 500M+

The weird part is that replacing `return "<table>..."` with `return "<p>test</p>"` does not leak memory... I cannot figure this one out, am I doing something wrong? Is there another way of adding a table as cell value in bootstrap-table? Is this a bug? Any help would be appreciated.

Cheers,

Andreas

**Comment by djhvscf** [comment]
Can you provide a fiddle?? @urban-1

**Comment by urban-1** [comment]
@work atm, I will later today or tomorrow morning. Thanks for the quick response :)

**Comment by djhvscf** [comment]
Great @urban-1

**Comment by urban-1** [comment]
Hi again,

I tried a jsfiddle but I cannot reproduce this... (looking at heap snapshots and timeline in chrome). I think you can close this.

I am definitely using different versions of bootstrap/bootstrap-table so I am not sure whats going on. The current fiddle: https://jsfiddle.net/zj87vj37/30/. I will re-open if I manage to 

Sorry for the trouble :)
