### ISSUE TITLE
请问table里面的数据非常多的时候怎么办

### ISSUE THREAD

**Issue by flybird101** [wenzhixin/bootstrap-table#1888]
我们的表只有两行，一行title，一行数据，但其中两个单元格的数据可能非常多，当数据较少的时候正常导出，但数据非常多的时候（在浏览器里可以拖好几屏。。）点导出就没反应了。请问有什么办法吗？还是只能转后台做？

**Comment by wenzhixin** [comment]
这种情况请用分页来解决。

**Comment by flybird101** [comment]
只有两行数据怎么分页

**Comment by wenzhixin** [comment]
你是显示 `key: value`吗，是否可以竖着来做？

**Comment by flybird101** [comment]
差不多吧，几个key:value，竖着来做？
