### ISSUE TITLE
data-events="actionEvents" 事件不可用

### ISSUE THREAD

**Issue by Yeaseon** [wenzhixin/bootstrap-table#1889]
我加载本地json数据，对其进行操作。结果之前可用的data-events="actionEvents" 事件，点击无反应，浏览器提示“Uncaught TypeError: Cannot read property 'action' of undefined”，定位到的是 
value = row[that.header.fields[i]];   //bootstrap-table.js:1447 
![bs](https://cloud.githubusercontent.com/assets/16696563/12345393/2bb3ee7a-bb83-11e5-8683-35b7b7079d06.png)

**Comment by wenzhixin** [comment]
请提供 jsFiddle #1765

**Comment by Yeaseon** [comment]
@wenzhixin  不太会用jsFiddle，主要代码已经贴上去了，https://jsfiddle.net/#&togetherjs=sE6r8y6L4o
之前没有加载远程数据时，点击事件是可用的。

**Comment by wenzhixin** [comment]
你没保存吧？要点 update

**Comment by Yeaseon** [comment]
@wenzhixin 刚刚我升级了一下bootstrap-table的版本，之前是1.7。data-events="actionEvents" 事件已经可以生效了，但是有些json文件加载后，不能显示了。是不是json数据格式变了？
![etm1dp_k rj i2fj2p1i c2](https://cloud.githubusercontent.com/assets/16696563/12347544/c66c5e8c-bb99-11e5-92ff-a2702663ea38.png)

**Comment by wenzhixin** [comment]
检查下你自己的配置

**Comment by Yeaseon** [comment]
1.7.1 加载之后能显示，1.9.1加载之后就不显示了。如果返回的field少于表格的field，能显示么

**Comment by wenzhixin** [comment]
你可以试下 develop 的版本

**Comment by wenzhixin** [comment]
试过没问题，关闭该问题，假如存在再reopen
