### ISSUE TITLE
Exporting gives error if the data has unicode characters || Bootstrap Table export

### ISSUE THREAD

**Issue by divyamv** [wenzhixin/bootstrap-table#189]
Not able to export if the data has unicode characters.getting the below error 

Uncaught INVALID_CHARACTER_ERR: DOM Exception 5 VM2832 jquery.base64.js:136_getbyte VM2832 jquery.base64.js:136_encode VM2832 jquery.base64.js:160$.fn.extend.tableExport tableExport.js:121(anonymous function) bootstrap-table-export.js:73jQuery.event.dispatch jquery.js:4641jQuery.event.add.elemData.handle

**Comment by abeto** [comment]
It was working after changing  jquery.base64.js from the link https://gist.github.com/wenzhixin/09e218c884f4f380b68a for Amharic(አማርኛ) character

**Comment by pdxbug** [comment]
Error received DOM Exception 5 INVALID CHARACTER error on valid base64

Abeto's base64 fixed my issues trying to download to excel using 
Karthikeyan K's
Export HTML table to Excel / CSV / PDF / JSON / PNG using jQuery
http://demos.w3lessons.info/jquery-table-export

**Comment by jcomas** [comment]
Better use this fork: https://github.com/hhurz/tableExport.jquery.plugin

And you have to include the modules, for example:

        <script src="/modules/tableExport.jquery.plugin/libs/js-xlsx/xlsx.core.min.js"></script>
        <script src="/modules/tableExport.jquery.plugin/tableExport.min.js"></script>
        <script src="/modules/bootstrap-table/extensions/export/bootstrap-table-export.min.js"></script>

**Comment by zxkang** [comment]
@jcomas It's great, powerful plugin.
