### ISSUE TITLE
large/many columns horizontal scrolling body but not footer

### ISSUE THREAD

**Issue by carldai0106** [wenzhixin/bootstrap-table#1891]
Hi @wenzhixin ,
   Please help me to review my program.
  I want  my footer columns width to  fit table body columns width.
 How should I do?
Here is my table : https://jsfiddle.net/carldai0106/rr5d9sr4/3/

**Comment by dabros** [comment]
https://jsfiddle.net/dabros/751799qm/ (moved to init from data-x, added js desc)

@carldai0106 - update title to something like "large column scrolling body but not footer"

The issue appears to be `fixed-table-footer` keeping `overflow:hidden` when `fixed-table-body` does not, so lots of columns shows horizontal scrollbar, but hides footers for those scrollable columns.

Changing `overflow` on `fixed-table-footer` just causes seperate scrollbar, not a real solution in my mind.

I know there have been other column alignment questions, but ive never taken much part in them, so maybe @wenzhixin @djhvscf have some ideas, as i can only think of changing structure to move horizontal scroll to `fixed-table-container`, which may have undesired side-effects with respect especially to responsive layout.

**Comment by carldai0106** [comment]
@dabros 
Thanks for your reply.
My English is not so good. Maybe I can not express my mean.
I updated my jsfiddle and remove some columns , so it does not have horizontal scroll.
Width  of each column in the table body is not equal to width of each column in the footer of the table.

@wenzhixin 
我想知道当我有table footer作为总结的时候，footer 列的宽度与 table body的列的宽度不同，是否有办法可以设置。通过chrome开发工具，我看到它们不是属于一个元素。

**Comment by dabros** [comment]
@djhvscf @wenzhixin - i can only confirm this seems to happen when using the colspan and multiple field/columns arrays

Here it is with some fields removed: https://jsfiddle.net/751799qm/2/ (got '0' index error till added empty `[]` after first set)

**Comment by djhvscf** [comment]
Ok... let me check it @dabros

**Comment by djhvscf** [comment]
As you can see here: https://jsfiddle.net/carldai0106/rr5d9sr4/3/ this is solved in our latest release
