### ISSUE TITLE
Make two-phase AJAX load, list and items

### ISSUE THREAD

**Issue by mcd-php** [wenzhixin/bootstrap-table#1892]
The first phase loads only list of ID's accepting order, search etc, and the second phase asks for every ID on another URL.

Reason: small parts can be cached by browser and reverse proxy for long time, sorted and filtered lists can not. Also, the cached small parts can be reused for different views in client JS.

Example:
```json
{
    "ajax-2phase": {
        "list": {
            "url":"/app/v1/article/list"
        },
        "item": {
            "url":"/app/v1/article/item/{ID}"
        },
    }
}
```

I will now try to emulate it by `ajax` function.

Can you give me any directions to extend this software by external hooks ? I prefer load from CDN and not to adapt/fork projects.

If I finally fork and implement, will you accept it ? What guidelines will you give me on this task ?

**Comment by wenzhixin** [comment]
You can check out this file: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md

**Comment by dabros** [comment]
@mcd-php - as wenzhixin said, checkout that file

You can use fiddles there to demo this functionality, if need be emulating url request via dummy functions returning javascript arrays created in same file, or any other means.

If you feel this is required in core code, then include copy of that file inline in js block (turning off wrap in js panel settings) and make your mods there (with inline comments so we can easily find them)

If it looks good and you can explain use cases and why this is required as core code, then submit **PR** to develop branch.

But most functionality can be achieved using callbacks, or in some cases extending like you can see in official extensions.

If you make a working fiddle using whatever approach and explain your reasoning (and @ call in some more frequent posters if time sensitive) then you can usually get some good feedback and code help if needed.
