### ISSUE TITLE
caption cause issue

### ISSUE THREAD

**Issue by mctdi** [wenzhixin/bootstrap-table#1893]
Hi

when we use caption in the bootstrap table, that cause a strange problem, caption is not displayed and table header is showed two time.

i created a jsfiddle
http://jsfiddle.net/m3qvy2ge/

**Comment by mctdi** [comment]
another example: http://jsfiddle.net/cqk0oz7x/

**Comment by mctdi** [comment]
seem like if data-toggle="table" is removed... no problem

http://jsfiddle.net/o7705hny/

**Comment by mctdi** [comment]
Maybe if found the issue

At the beginning i was thinking issue was used: class instead of data-classes

Here that work
http://jsfiddle.net/a6jd30e1/

if i had theses element
style="min-height:200"
data-height="330px

Get head in double...
http://jsfiddle.net/2bdgzqp4/

If i add data-show-header="false", caption is displayed, but not header...

**Comment by wenzhixin** [comment]
we do not support caption.

**Comment by marccollin** [comment]
ah ok, good to know because i got the same problem... then @mctdi

**Comment by dabros** [comment]
related to #1630, same conclusion for both (captions not supported)

**Comment by wenzhixin** [comment]
Close this one, discuss in #1630.
