### ISSUE TITLE
date range filtering

### ISSUE THREAD

**Issue by andrew141414** [wenzhixin/bootstrap-table#1897]
is there any sample or works that has a date range filtering in searching a data using bootstrap table?

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

**Comment by andrew141414** [comment]
it only shows a number. any date format (YYYY-MM-DD)

**Comment by wenzhixin** [comment]
I mean you can custom your toolbar.
