### ISSUE TITLE
error events

### ISSUE THREAD

**Issue by hmykol20** [wenzhixin/bootstrap-table#1898]
hi, i have a error when used even... {
								field: 'operate',
								title:'Accion',
								align:'center',
								width:35,
							   events: commonEvents,
                            formatter: commonFormatter
							}]
![error-table](https://cloud.githubusercontent.com/assets/7131054/12374655/ce442576-bc67-11e5-8070-fb4353a679a2.JPG)

**Comment by wenzhixin** [comment]
You need to define by yourself. like this: `window.commonEvents = {};`
