### ISSUE TITLE
Change grunt from a dependency to a devDependency

### ISSUE THREAD

**Issue by kohenkatz** [wenzhixin/bootstrap-table#1902]
When you run `npm install bootstrap-table`, it also installs `grunt` (and a bunch of `grunt-contrib-*` stuff).  However, since Grunt is a build tool and not a real dependency, it (and its plugins) should be listed in the `devDependencies` options in `package.json` instead of in the main `dependencies`.  That way, those of us who use the files in the `dist` folder and/or use our own build scripts do not need to download Grunt.

Thanks!

**Comment by wenzhixin** [comment]
Any pull request is welcome.

**Comment by dabros** [comment]
@kohenkatz  - **PR** always welcome

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests
