### ISSUE TITLE
Is there a way to keep images in few columns

### ISSUE THREAD

**Issue by jeevanpulugu** [wenzhixin/bootstrap-table#1903]
Hi,

We are trying to keep images in few columns, is there a way to do that? Below is the screen shot of design image what we are trying to achieve.

![table](https://cloud.githubusercontent.com/assets/5284754/12398785/dc94581e-be3b-11e5-9c65-745ad585a9a6.JPG)

Thanks,
Jeevan Pulugu

**Comment by wenzhixin** [comment]
Use `formatter`: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/579.html
