### ISSUE TITLE
Click Row to open unique URL for each row.

### ISSUE THREAD

**Issue by jonbrown21** [wenzhixin/bootstrap-table#1905]
I have been working on this for hours and I can't seem to figure this out. I have a table with 2 columns. Name and ID. I have a PHP page that is keyed off of ID using $_GET so http://example.com?id=1010 goes to the users page. I need help or a little explanation on how to create an onclick event that will allow me to click on a row, and have it go to the unique page ID url based on the ID of the data in that row.

**Comment by wenzhixin** [comment]
Use `formatter` option: http://issues.wenzhixin.net.cn/bootstrap-table/#options/format.html

**Comment by dabros** [comment]
@jonbrown21 - please close as duplicate, post in linked topics if still need help

Same as #817, which is same as #877

Also, possibly related / of interest: #1089, #1204, #1300, #1785, https://github.com/wenzhixin/bootstrap-table/issues?q=is%3Aissue+click+row

**Comment by jonbrown21** [comment]
It was right in front of my face, thanks guys. Working like a charm!!
