### ISSUE TITLE
Remember Sort & Show-Columns with Cookie or Localstorage

### ISSUE THREAD

**Issue by nikmauro** [wenzhixin/bootstrap-table#191]
Hello how it possible to remember the state of sort, Show Columns Selections, Pagination and Records per page with Jquery Cookie or LocalStorage based on Table ID data-id-field="id"?

Suggestion params  data-state-save="true"

I have this Lib
https://github.com/carhartl/jquery-cookie

**Comment by djhvscf** [comment]
Hey!! @wenzhixin you can close his issue!!
