### ISSUE TITLE
data is not getting loaded from JSON example

### ISSUE THREAD

**Issue by BharatiL** [wenzhixin/bootstrap-table#1913]
JSON table is not getting loaded from data1.json file. It is loading the page but no table data.

Here is my example. Could you please help in this?

<!DOCTYPE html>
<html>
<head>
<head>
    <title>JSON Table</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../External/bootstrap-table-master/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../External/bootstrap-table-master/assets/bootstrap-table/src/bootstrap-table.css">
    <link rel="stylesheet" href="../External/bootstrap-table-master/assets/examples.css">
    <style>
       .update {
           color: #333;
           margin-right: 5px;
       }
       .remove {
           color: red;
           margin-left: 5px;
       }
       .alert {
           padding: 0 14px;
           margin-bottom: 0;
           display: inline-block;
       }
   </style>
    <script src="../External/bootstrap-table-master/assets/jquery.min.js"></script>
    <script src="../External/bootstrap-table-master/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="../External/bootstrap-table-master/assets/bootstrap-table/src/bootstrap-table.js"></script>
    <script src="../External/bootstrap-table-master/ga.js"></script>
</head>
<body>

<table id="table"   
	data-toggle="table"
	data-url="../External/bootstrap-table-master/json/data1.json" 
	data-sort-name="name"
    data-sort-order="desc"
    data-click-to-select="true"
    data-height="480"
    data-pagination="true"
    data-page-size="8"
    data-page-list="[5,8,10]"
    data-pagination-first-text="First"
    data-pagination-pre-text="Previous"
    data-pagination-next-text="Next"
    data-pagination-last-text="Last"
    data-unique-id="id">
    <thead>
    <tr>
    	<th data-field="state" data-checkbox="true"></th>
        <th data-field="id" data-sortable="true">ID</th>
		<th data-field="name" data-sortable="true">Item Name</th>
		<th data-field="price" data-sortable="true">Item Price</th>
    </tr>
    </thead>    
</table>
<script>              
</script>
</body>
</html>

**Comment by BharatiL** [comment]
Example is not getting paste. But all the examples take data from JSON file are not working at my end. Could you please help in this?

**Comment by wenzhixin** [comment]
format your code and provide a jsfiddle: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports

**Comment by BharatiL** [comment]
I am not able to login in jsfiddle and file uploading also has some problems. But below code I am adding in the table tag. tr and th tags are also there , but not adding here since it is showing the format and not the actual code. 
What should we pass to data-url? file or folder path? am i doing it correct?

< table id="table"   
	data-toggle="table"
	data-url="./data.json">
    
data.json has
[
	{
		"id": 0,
		"name": "Item 0",
		"price": "$0"
	},
	{
		"id": 1,
		"name": "Item 1",
		"price": "$1"
	},
	{
		"id": 2,
		"name": "Item 2",
		"price": "$2"
	}
]

**Comment by wenzhixin** [comment]
Here is the guides to use markdown in GitHub issue: https://guides.github.com/features/mastering-markdown/.

ref #1362, are you using `file://` to open the html file?

**Comment by BharatiL** [comment]
I am using file:// . I am trying to load a local JSON file.
I did F12 on the brower and can see below error
XMLHttpRequest cannot load file:///D:/table/WebContent/data.json?order=asc. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

GET file://www.google-analytics.com/analytics.js net::ERR_FILE_NOT_FOUND

**Comment by djhvscf** [comment]
To create a fiddle you don't need to be logged in.. @BharatiL

**Comment by dabros** [comment]
@BharatiL - just use one of the example fiddles provided, either at link you saw above (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports) or at fiddle examples page (http://bootstrap-table.wenzhixin.net.cn/examples/)

'Sign in' for jsfiddle just helps you track those you created or forked, it is NOT a requirement (but you should already have a googleid, so no need for extra login details anywhere)

**Comment by wenzhixin** [comment]
So we know this is a domain cross problem, close the issue.

**Comment by BharatiL** [comment]
Thanks everyone for help. 
Just one update, if anyone wants to local file just for testing they can start chrome with following option.
and open html file in that browser.
chrome --allow-file-access-from-files

To run on local JSON server install node.js and all other examples will also run.

**Comment by BharatiL** [comment]
To run on local server:
1. Install npm on your machin from location  "https://nodejs.org/en/download/"
2. Install JSON server. Open command prompt and run cmd "npm install -g json-server".
3. Start JSON server using json file, cmd :- "json-server --watch 'file path'"
   for eg :- json-server --watch data1.json
