### ISSUE TITLE
index序号列如何格式化为每页递增的值

### ISSUE THREAD

**Issue by xiegang666** [wenzhixin/bootstrap-table#1914]
如：
th data-field="" data-formatter="indexFormatter">序号</th

// 序号
function indexFormatter(value, row, index){
        return index+1;
}
这样每跳转一页，序号就又重新开始了。
需要下面这样的效果，这里是否有方法可以获取到分页的具体参数。
第一页 1,2,3,4,5
第二页 6,7,8,9,10

**Comment by xiegang666** [comment]
<th data-field="" data-formatter="indexFormatter">序号</th>

**Comment by wenzhixin** [comment]
通过下面的方式去获取：
```
var options = $table.bootstrapTable('getOptions');
// options.pageNumber;
// options. pageSize;
```

**Comment by xiegang666** [comment]
多谢，可以了。

**Comment by hy928302776** [comment]
不行呀，这个得不到
