### ISSUE TITLE
Many column and size

### ISSUE THREAD

**Issue by mctdi** [wenzhixin/bootstrap-table#1915]
Hi

is there any option to affect column size when we have many column like in 
https://jsfiddle.net/mfnjf1bh/

or we need to use br tag like

https://jsfiddle.net/kufx18rv/

**Comment by dabros** [comment]
@mctdi - http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

I fixed up some mistakes in your fiddle (if using data-toggle, dont need js init, its only either/or, never both)

https://jsfiddle.net/dabros/yeLwdw79/

@djhvscf - another width question for you, even though `data-width` appears applied to both TH and TD, the  width doesnt appear to apply if scrollbar required.

There is `th > .fht-cell` with inline `width: 63px;`, but removing or changing that from generated html didnt seem to affect it at all.
