### ISSUE TITLE
Create Grouped Headers using Columns-Object

### ISSUE THREAD

**Issue by DSigmund** [wenzhixin/bootstrap-table#1919]
Hi,

id like to create groupes Headers like in this example:
http://issues.wenzhixin.net.cn/bootstrap-table/#options/group-columns.html

But Only using the columns-object:
http://jsfiddle.net/e3nk137y/4317/

Does not work as i have it...
any ideas?

**Comment by wenzhixin** [comment]
examples:
http://issues.wenzhixin.net.cn/bootstrap-table/
http://jsfiddle.net/e3nk137y/4320/

**Comment by DSigmund** [comment]
Many Thanks!

**Comment by LuisAlejandroDuarte** [comment]
Hi, 
with the group header
to add more columns I have had problems,


var data = [{
  "name": "bootstrap-table",
  "counts": {
    "stargazers_count": "526",
    "forks_count": "122"
  }
}, {
  "name": "multiple-select",
  "counts": {
    "stargazers_count": "288",
    "forks_count": "150"
  }
}];
var columns = [
  [{
    "field": "name",
    "title": "Name",
    "colspan": 1,
    "rowspan": 2
  }, {
    "title": "counttitle",
    "colspan": 2,
    "rowspan": 1
  }], 
  [{
    "field": "counts.stargazers_count",
    "title": "Stars",
    "colspan": 1,
    "rowspan": 1
  }, {
    "field": "counts.forks_count",
    "title": "Forks",
    "colspan": 1,
    "rowspan": 1
  }],
   [{
    "title": "counttitle",
    "colspan": 2,
    "rowspan": 1
  }], 
  [{
    "field": "counts.stargazers_count",
    "title": "Stars",
    "colspan": 1,
    "rowspan": 1
  }, {
    "field": "counts.forks_count",
    "title": "Forks",
    "colspan": 1,
    "rowspan": 1
  }]
];

$(function() {
  $('#table').bootstrapTable({
    data: data,
    columns: columns
  });
});
![headergroup](https://cloud.githubusercontent.com/assets/9936927/18684452/db5019ce-7f39-11e6-9ee4-be4bfe42580e.png)
