### ISSUE TITLE
Hide column on card view state

### ISSUE THREAD

**Issue by nikmauro** [wenzhixin/bootstrap-table#192]
Suggestion to hide collumn on Card View state

Param on column data-card-visible="false"  [default:'true"]

**Comment by djhvscf** [comment]
@wenzhixin can we close this issue?

**Comment by andrea-schneider** [comment]
Hi
I have added this (data-card-visible="false") to two columns of my table, but the columns are still visible when card view is used. Is there anything else that have to be set to make it working?

I'm loading the data with an ajax request:

	$table.bootstrapTable({
	    url:  "<!WEM SCRIPTVAR.sUrl>",
		cache: false,
		dataType: 'json',
		method: 'post',
		idField: 'id',
		onLoadSuccess:function(jsonData) {
			if(initialLoad == true)
			{
				initialLoad = false;
			}
			else
			{
				$table.bootstrapTable('load', jsonData.pproducts);
			}
         }
    });		

Thanks a lot
Andrea

**Comment by wenzhixin** [comment]
Can you provide a jsfiddle to show your problem, if that is a bug, please create a new issue.

**Comment by andrea-schneider** [comment]
Hi
So far I cannot, because the data isn't available outside our internal system.
May I ask you a short other question. Is there a way to have the horizontal scrollbar on top and on the bottom of the table?

Thanks a lot
Andrea

**Comment by Friends4U** [comment]
And the other way around?
I want some data only visible on the cardview and not in normal view, is that posible?

**Comment by wenzhixin** [comment]
@Friends4U workaround example: https://live.bootstrap-table.com/code/wenzhixin/8887
