### ISSUE TITLE
Sorting link

### ISSUE THREAD

**Issue by jpchenel** [wenzhixin/bootstrap-table#1920]
Trying to sort link in bootstrap-table dont work. If I try with raw text it work perfectly (v 1.9.1).

![sort asc](https://cloud.githubusercontent.com/assets/15834917/12483881/613465ba-c025-11e5-901e-d1f94ef9c87b.jpg)

Also, i've took the before last version because 1.10 show all link and checkbox in raw html (not renderer). At loading, I see the checkbox, but when bootstrap-table is rendered, it convert back to raw html

![raw html](https://cloud.githubusercontent.com/assets/15834917/12483882/63e20b00-c025-11e5-805a-48234935671c.jpg)

Best regards,

**Comment by djhvscf** [comment]
See this example: http://jsfiddle.net/wenyi/e3nk137y/21/

**Comment by djhvscf** [comment]
And this one is sorting the data: http://jsfiddle.net/djhvscf/e3nk137y/4321/

**Comment by jpchenel** [comment]
Thank very much.
Now it work with the data-formater.
Here are the code:

            //HTML
            <th data-sortable="true" data-formatter="linkFormatter">
                @Html.DisplayNameFor(model => model.Courriel)
            </th>
            <th data-sortable="true" data-formatter="checkboxFormatter">
                @Html.DisplayNameFor(model => model.Actif)
            </th>

        //JS
        function linkFormatter(value) {
            return '<a href="@Url.Action("ModifierAdresse")' + '?courriel=' + value.trim() + '">' + value.trim() + '</a>';
        }

        function checkboxFormatter(value) {
            return '<input type="checkbox" ' + (value.trim().toLowerCase() === 'true' ? 'checked' : '') + ' disabled />';
        }
