### ISSUE TITLE
New method proposal

### ISSUE THREAD

**Issue by Real-Gecko** [wenzhixin/bootstrap-table#1922]
```javascript
    BootstrapTable.prototype.checkInvert = function () {
        var that = this;
        var rows = that.$selectItem.filter(':enabled');
        var checked = rows.filter(':checked');
        var unchecked = rows.filter(':not(:checked)');
        rows.each(function() {
            $(this).prop('checked', !$(this).prop('checked'));
        });
        that.updateRows();
        that.updateSelected();
        that.trigger('uncheck-some', checked);
        checked = that.getSelections();
        that.trigger('check-some', checked);
    };
```

**Comment by djhvscf** [comment]
Can tell us what is the main goal of this method?

**Comment by Real-Gecko** [comment]
Inverts checked rows, checked rows become unchecked while uncheked rows become checked.

**Comment by dabros** [comment]
@Real-Gecko - would this (in your mind) be triggered from UI, perhaps via ctr+click of 'select all' type button, or via code.

And would use cases would this actually hypothetically solve?

Its just no one ever asked for this before, and it can be done via custom function (`getSelections` combined with `check` or `checkBy` http://bootstrap-table.wenzhixin.net.cn/documentation/#methods) , so need clarification on how you see users calling to and needing this.

**Comment by Real-Gecko** [comment]
Well, it is just an extension to methods pair `checkAll`, `uncheckAll`, I've added this function to my project cause sometimes I need to invert selection even though it seems really illogical :)
I call this method in my code like this (usually on context-menu item click):
```javascript
$('#list-table').bootstrapTable('checkInvert');
```
I just thought someone else may find this method usefull :)

**Comment by wenzhixin** [comment]
When to call this method @Real-Gecko ?

**Comment by Real-Gecko** [comment]
Well manually from the code I guess, when programmer needs it
I call it like this:
```javascript
            .on('contextmenu-item.bs.table', function(ev, row, $el) {
                switch($el.data("item")) {
                    ...
                    case "select_all":
                        $('#list-table').bootstrapTable('checkAll');
                        break;
                    case "select_none":
                        $('#list-table').bootstrapTable('uncheckAll');
                        break;
                    case "select_inverse":
                        $('#list-table').bootstrapTable('checkInvert');
                        break;
                    ...
                }
```

**Comment by wenzhixin** [comment]
Any pull request is welcome:)

**Comment by Real-Gecko** [comment]
OK :)

**Comment by dabros** [comment]
@Real-Gecko :+1: for `contextMenu`, a great way to fit it in.

Also, I havent really seen any examples of `contextMenu` (though correct me if im wrong). 

So for extra credit it would be great if you could maybe add one to http://issues.wenzhixin.net.cn/bootstrap-table/index.html, under issues or in main list if tidy enough :)

**Comment by Real-Gecko** [comment]
Bootstrap table context menu has some nice [demos](http://www.prograhammer.com/demos/bootstrap-table-contextmenu/)
That was enough for me to deal with it.
I even added [new issue](https://github.com/prograhammer/bootstrap-table-contextmenu/issues/7) there :)

**Comment by wenzhixin** [comment]
Merged.
