### ISSUE TITLE
custom ajax not showing pagination

### ISSUE THREAD

**Issue by erick-chali** [wenzhixin/bootstrap-table#1923]
I am creating a table like this. 

    $tablaMovimientos.bootstrapTable({
				ajax: function (request) {
					$.ajax({
					      url: "CargarTiposPago",
					      method: "POST",
					      dataType: 'json',
					      success: function (data){
					    	  console.log('success');
					    	  console.log(JSON.stringify(data));
					    	  request.success({
					    		  rows : data
					    	  });
					      },
					      error: function(data) {
					    	  console.log(JSON.stringify(data));
							   var obj = JSON.parse(JSON.stringify(data));
							   $('#modalTiposPagoNotificacion').text(obj.responseText);
						  },
						  complete: function (){
							  request.complete();
						  }
					    });
				},
			    search: true,
			    height: 400,
			    pagination: true,
			    pageSize: 10,
			    pageList: [10,25,50,100],
			    sortable: true,
			    showRefresh: true,
			    sidePagination: 'server',
			    columns: [{
			        field: 'idPago',
			        title: 'ID'
			    },{
			        field: 'descripcion',
			        title: 'Descripcion Pago'
			    }]
			});

how ever when the table is filled, it shows more than 10 items per page, which is the pageSize, and also says: "showing 1 to 10 from UNDEFINIED", can you tell me what I'm doing wrong.
![screenshot 112](https://cloud.githubusercontent.com/assets/6502472/12498120/d176880e-c065-11e5-9fd0-dd30e8df9269.png)

**Comment by dabros** [comment]
@erick-chali - look at the doco for `url` http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options, notably the [with server pagination](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data2.json) example.

My best guess is that you are not returning a `total` index (Remember you can also use `responseHandler` to transform input if it passed under a different name and cant easily be changed)

If you believe you are then please create a fiddle: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
just like what @dabros said, you need to return `total` property.
