### ISSUE TITLE
How the change the content of detail view

### ISSUE THREAD

**Issue by eserco** [wenzhixin/bootstrap-table#1925]
Hi there!

I am new to JavaScript and JQuery so please be as clear as possible. I want to change the content of detail view so when I click the "+" button i want it to load another json file that is different from the json file I use for filling the table.

http://www.iskencecorbasi.com/site/decks.php --- This is the website
https://jsbin.com/milajikoqi/edit?html,output --- This is the code

I believe this part needs a change like "import this json file" before $.each function starts, but not very sure though.

    function detailFormatter(index, row) {
        var html = [];
        $.each(row, function (key, value) {
            html.push('<p><b>' + key + ':</b> ' + value + '</p>');
        });
        return html.join('');
    }	

I want to use json file looks like this:

     [
         {
           "card"  : "x"
         },
        {
           "card"  : "y"
        },
        {
           "card"  : "z"
        }
    ] 
So when user clicks "+" button to see details s/he will see corresponding card values.

**Comment by wenzhixin** [comment]
Example here: http://issues.wenzhixin.net.cn/bootstrap-table/, you can click "+"(Item ID: 1) to load a file content.
Source here: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/welcome.html#L132

**Comment by eserco** [comment]
Thanks for the reply wenzhixin! Now what if I want to load different content for , let's say 20 indexes, is the below method fine?

		var $table = $('#table')
        $table.on('expand-row.bs.table', function (e, index, row, $detail) {
            if (index == 0) {
                $detail.html('Loading from ajax request...');
                $.get('deck1.txt', function (res) {
                    $detail.html(res.replace(/\n/g, '<br>'));
                });
            }
		});
		var $table = $('#table')
        $table.on('expand-row.bs.table', function (e, index, row, $detail) {
            if (index == 1) {
                $detail.html('Loading from ajax request...');
                $.get('deck2.txt', function (res) {
                    $detail.html(res.replace(/\n/g, '<br>'));
                });
            }
		});   
...etc

I will have around 100 different content to be loaded. Is there a way to do it via a json file?

**Comment by wenzhixin** [comment]
You can use `row` param, for example: 
```
$.get(row.file, ...);
```
