### ISSUE TITLE
Export Button

### ISSUE THREAD

**Issue by Juandkpa** [wenzhixin/bootstrap-table#1926]
The export button is not showing, I've imported all the js showing in the example of http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html like it is recommended in previous issues, but my table still without working.
please help!

**Comment by wenzhixin** [comment]
Have you added these libs:
```html
    <script src="../assets/bootstrap-table/src/extensions/export/bootstrap-table-export.js"></script>
    <script src="//rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js"></script>
```

https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/export.html#L12

**Comment by Juandkpa** [comment]
Thank you for your reply, I've fixed the problem, seem that had a problem with jquery integration..
