### ISSUE TITLE
Button event not invoke while using onClickRow

### ISSUE THREAD

**Issue by kirubz** [wenzhixin/bootstrap-table#1927]
Hi,
Thanks for this plugin.
I am using grid functionality using this plugin.
http://jsfiddle.net/5739gofe/

In this I have an button at the last column to open the modal popup. but if I have onClickRow method then this will get invoke

I have tried with onClickCell, but when i tried to use the column hide its not working.
Can any one please help me on this.

**Comment by dabros** [comment]
@kirubz - and that is a problem how..?

Put this line into your button event: `console.log('test button clicked');`

Yes, `click-row.bs.table` and `click-cell.bs.table` are being triggered when you click that button. But your button handler is ALSO being triggered.

There are several issues (closed and open) regarding people using code in click-row that they dont want triggered on button click - but you dont seem to have that.

The button event IS triggered, up to you to figure out why expected output is not acheived.

**Comment by wenzhixin** [comment]
just like what @dabros said, using events instead.
