### ISSUE TITLE
selectPage runing endless

### ISSUE THREAD

**Issue by Fruchtgummi** [wenzhixin/bootstrap-table#1928]
Hi,

i use **$table.bootstrapTable('selectPage', 2);** in onLoadSuccess event, but never stop get data from server. 

Help!

**Comment by djhvscf** [comment]
Can you provide a fiddle with dummy data and your code??

**Comment by Fruchtgummi** [comment]
$('#table').bootstrapTable({
        queryParams: function (p) {
            
          // ....
           
        }, 
        onPageChange: function (r) {
            
            localStorage.setItem('katalog_page', r);
        },
        onLoadSuccess: function(e) {

            if($('ul.pagination li.active a').text() != localStorage.getItem('katalog_page')) {
                
               $('#table').bootstrapTable('selectPage', localStorage.getItem('katalog_page'));
                
            } 
             
            
        },
  });

**Comment by dabros** [comment]
@Fruchtgummi - we need a fiddle

You might need to pass in data via javascript array if url not accessible from here, so just grab a subset of your real data.

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
Maybe you can use cookie extension or restore your data in `queryParams` function Fruchtgummi

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
