### ISSUE TITLE
How can I make detail view to display a pop-up window

### ISSUE THREAD

**Issue by eserco** [wenzhixin/bootstrap-table#1930]
Hi there,
I have been trying to display a bootstrap pop-up windows that will show the details in the pop up, but no luck this far. Can you guys help me out?
Thanks!

**Comment by dabros** [comment]
@eserco 

Create a button in last column (see http://issues.wenzhixin.net.cn/bootstrap-table/index.html)

Define a `unique-id` key, then an event to that button that uses something like `$(this).parent('tr').data('unique-id')` (see generated html using F12) to retrieve the value needed to call `getRowByUniqueId()` (http://bootstrap-table.wenzhixin.net.cn/documentation/#methods).

Then call your modal, using that data you just received to create fields.

This is not automatic, you need to create a modal and define what its contents are and load them via the event. But this is not difficult, nor related in any real way to bootstrap-table, and so many modal examples out there.

---

And there is also the ever so popular option of searching for someone who has done it before (https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue+modal)

#1610 
#1851
#1759 **full CRUD example** (https://github.com/wenzhixin/bootstrap-table-examples/tree/master/crud)
#1927 (still open atm)
ect.
ect.
ect.

**Comment by wenzhixin** [comment]
just like what @dabros said.
