### ISSUE TITLE
请教单选模式下如何使用js选择行？

### ISSUE THREAD

**Issue by weianguo** [wenzhixin/bootstrap-table#1932]
我使用ajax加载数据，需要加载完成后自动选择上第一行，
当使用 radio：true 时，$table.bootstrapTable('check', 0);不起作用。

另外，如何在不启用 radio,checkbox的时候，使鼠标单击行的时候，CSS呈现选中样式？

**Comment by wenzhixin** [comment]
第一个问题提供下 jsfiddle，第二个问题看下例子 #1765

**Comment by wenzhixin** [comment]
第一个问题与 #1769 一样，先关闭该问题
