### ISSUE TITLE
Html in cells

### ISSUE THREAD

**Issue by neuhoffm** [wenzhixin/bootstrap-table#1933]
Version 1.10 seems to no longer handle html in cells nicely. Is there a way to escape it? Example: http://bootstrap-table.wenzhixin.net.cn/documentation/ (table options -> icon size)

**Comment by dabros** [comment]
@neuhoffm - the `escape` table option.

Incidently its what is currently breaking the format of the doco page itself ;)

#1924 

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by neuhoffm** [comment]
Is the escape option dependent on how the data is loaded? I have a previously built table that I am making fancy and even with escape set to true I can see the html being changed to unescaped as bootstrap table is applied. I can post the code tonight if that's helpful.

**Comment by neuhoffm** [comment]
html:
```
    <table class="fancy" data-link="admin/applicants/applicant/" data-idfield="Id">
        <thead>
            <tr>
                <th data-field="FirstName" data-sortable="true">
                    First Name
                </th>
                <th data-field="Step" data-sortable="true">
                    Application Progress
                </th>
                <th data-field="Id" data-visible="false"></th>
            </tr>
        </thead>
        <tbody>
                <tr>
                    <td>
                        Bob
                    </td>
                    <td>
                        <div class="progress compactProgress" data-toggle="tooltip">
                            <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%">
                                <span class="sr-only">75% Complete</span>
                            </div>
                        </div>
                    </td>
                    <td>
                        4
                    </td>
                </tr>
        </tbody>
    </table>
```
js:
```
function fancyTable(table) {
    var url = $(table).data("link");
    var id = $(table).data("idfield");
    $(table).bootstrapTable({
        pagination: true,
        pageSize: 25,
        pageList: [10, 25, 50, 100, 200],
        striped: true,
        escape: true,
        onClickRow: function (row) {
            if (url != undefined) {
                window.location.href = rootUrl + url + row[id].trim();
            }
        }
    });
}

$(document).ready(function () {
    $("table.fancy").each(function () {
        fancyTable(this);
    });
});
```

**Comment by mickyp** [comment]
I have same issue, I set `<table data-escape="false">` to solve this problem.

The document said its default value is false, but seems the 1.10 change `escape` to true??

**Comment by djhvscf** [comment]
The default value is false, see this: https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L295

Make sure that you have the latest version @neuhoffm @mickyp

**Comment by mahesh-ziffi** [comment]
I' also getting the same error. Anyway to escape ?

**Comment by wenzhixin** [comment]
set `<table data-escape="false">` to solve your problem. Consider to release a new version.

**Comment by edouardberthe** [comment]
Same problem, solved by <table data-escape="false"> too. Thanks

**Comment by djhvscf** [comment]
We are considering to release a new versión.. We will keep you posted

**Comment by wenzhixin** [comment]
released v1.10.1

**Comment by xidui** [comment]
the escape option is for the whole table? Is there an escape option in a data field?

**Comment by djhvscf** [comment]
It is for the whole tsble

**Comment by xidui** [comment]
@djhvscf 
How about I send a pull request for the column escape switch?

**Comment by djhvscf** [comment]
Yes, sure.. All the **PR** are welcome!
