### ISSUE TITLE
Footer does not scroll height == 0

### ISSUE THREAD

**Issue by MichaelSPB** [wenzhixin/bootstrap-table#1935]
Hi guys! If the options do not specify the height or height == 0 || height == 'undefined' footer does not scroll . For myself did:
The function _BootstrapTable.prototype.fitHeader_ code is found

``` javascript
        this.$tableBody.off('scroll').on('scroll', function () {
            that.$tableHeader.scrollLeft($(this).scrollLeft());

            if (that.options.showFooter && !that.options.cardView) {
                that.$tableFooter.scrollLeft($(this).scrollLeft());
            }
        });
```

and paste in function _BootstrapTable.prototype.fitFooter_.

**Comment by djhvscf** [comment]
Can you provide a fiddle when we can see this change ? @MichaelSPB

**Comment by dabros** [comment]
@MichaelSPB 

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

You can include any js files inside javascript panel if needed, then comment (something like `// CHANGED`) and have it working so we can confirm the change.

I actually suggest making this fiddle to support a **PR** (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests), to speed up the merge process if change works.

**Comment by MichaelSPB** [comment]
JSFiddle original version: https://jsfiddle.net/MikeSPB/xjyc55m6/
edit version: https://jsfiddle.net/MikeSPB/z1zLukby/

**Comment by amarildomm** [comment]
Hi Michael,

Have you solved this issue? I'm with the same problem. This issue causes the footer not to be responsive, when we use the boostratable in smartphones, we can't see all footer columns.

Thanks,

**Comment by amarildomm** [comment]
i don't know if is the same thing, but the solution for my issue is: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/639.html

about the height problem, i've used the getheight function to set it dynamically.

**Comment by MichaelSPB** [comment]
@amarildomm, hi! Table checked on a smartphone - it works. Sometimes the width of the column footer is greater than the header if I use the formatter column. Property height of the table does not use , because the height of the table is automatically selected

**Comment by wenzhixin** [comment]
@MichaelSPB any PR is welcome.

**Comment by djhvscf** [comment]
As you can see here: https://jsfiddle.net/MikeSPB/xjyc55m6/ this is solved in our latest version.
