### ISSUE TITLE
Allow to access getVisibleFields or making a method getVisibleColumns

### ISSUE THREAD

**Issue by enayet-repo** [wenzhixin/bootstrap-table#1941]
I am using bootstrap-table plugin - http://bootstrap-table.wenzhixin.net.cn

There is a method for accessing hidden columns - getHiddenColumns but there is no getVisibleColumns method. Actually I want to search on the visible columns only for this I need the visible column names. 

I think searching is meaning for the visible columns only, otherwise users may be confused with the searched result.

I have searched in the library and found there is a method - getVisibleFields. But it is not accessible. I think it should be allowed to make access.

Thank you...

Stackoverflow link - http://stackoverflow.com/questions/34981291/wenzhixin-bootstrap-table-getvisiblecolumns

**Comment by dabros** [comment]
@enayet-repo - there are ways around that, by using selectors to find hidden columns or using `GetOptions`['columns'], but i agree they not the easiest way.

If you do want to make it public accessible, look at how other methods have been made the same and make a **PR** using develop branch (https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L2111)

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

**Comment by djhvscf** [comment]
Ref #1943
