### ISSUE TITLE
Unable to resize column using header

### ISSUE THREAD

**Issue by shivashankar-ror** [wenzhixin/bootstrap-table#1944]
Hi,
 I am following the code using 
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/resizable.html

I am ok with the resizable functionality except that I am not able to resize the columns using header.
Please let me know how to do so.

**Comment by dabros** [comment]
@djhvscf - the live demo seems to show that resize handles are not applied to the TH, perhaps because of `sortable`?

https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/resizable

@shivashankar-ror - please create a fiddle to help confirm the root cause: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Data doesnt matter, just use resize extension and then toggle other settings like `sortable`. We can always include the source .js file inline and tweak it in fiddle if we have idea about base code needing change.

**Comment by djhvscf** [comment]
@dabros this extensión does not support header when data-height is set.. Remember that PR are welcome

**Comment by dabros** [comment]
@djhvscf - doubt id get chance to look at it till next week, but do you mind updating your extensions doco so it says that, least till a solution is found?

**Comment by shivashankar-ror** [comment]
@dabros
Sure. I will try as suggested and update.

**Comment by shivashankar-ror** [comment]
@dabros 
Issue is with "data-height" as @djhvscf mentioned. If we set data-height it does not allow resizable via header.

**Comment by dabros** [comment]
@shivashankar-ror - can you please make the fiddle so we can play with this when we get time

thanks

**Comment by shivashankar-ror** [comment]
@dabros 
Sure

**Comment by shivashankar-ror** [comment]
Fiddle:  http://jsfiddle.net/ovyv5jeb/4/

**Comment by dabros** [comment]
@shivashankar-ror - always hit F12 to debug when strangness occurs

I see this in chome console log:

> Refused to execute script from 'https://raw.githubusercontent.com/wenzhixin/bootstrap-table/master/src/extensions/resizable/bootstrap-table-resizable.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Inline js file should fix this, which is what we need anyway, so will fork and fix now.

**Comment by shivashankar-ror** [comment]
I will update as inline code. Time being you can check in firefox. It will work

**Comment by dabros** [comment]
@shivashankar-ror @djhvscf 

Was already making it, though found another issue that causes you to need to resize it to fix column lines if `data-sortable` is false on only some columns

http://jsfiddle.net/dabros/896z9k8c/2/

**Comment by shivashankar-ror** [comment]
Updated Forked Fiddle: http://jsfiddle.net/shivaaqua/sa66wgv4/1/

**Comment by dabros** [comment]
@shivashankar-ror - you didnt save changes i think, or version number old - no js i can see, but dont worry as i got it

**Comment by shivashankar-ror** [comment]
Updated one: http://jsfiddle.net/shivaaqua/sa66wgv4/2/

**Comment by dabros** [comment]
@shivashankar-ror - again, no js panel content and still 4 external files. thanks for trying but pls just delete both posts and links - i already said i was making earlier and my fiddle works fine.

**Comment by dabros** [comment]
@djhvscf - can you please elaborate on how it not supported, to get me head start?

**Comment by shivashankar-ror** [comment]
@dabros 
I have added all files required directly. 
I have used html template. i.e using data-toggle="table"

**Comment by dabros** [comment]
@shivashankar-ror  - look at my fiddle

'inline' means copy+paste into js block so you can make changes to extension without having to create new repo and link there - all changes are instantaneous and diff versions can easily contain diff copies of that js files contents.

**Comment by wenzhixin** [comment]
@dabros @shivashankar-ror you can use this tool: https://rawgit.com to create a jsfiddle

**Comment by dabros** [comment]
@wenzhixin - already have fiddle above
@shivashankar-ror - please delete your posts after my fiddle as they are off-topic

**Comment by 719media** [comment]
has any progress been made on this? i assume the resizable plugin just does not work, is that correct?

**Comment by djhvscf** [comment]
This plugin does not support the data-height option
