### ISSUE TITLE
exclude/prevent columns to be seen in the toolbar with showColumns

### ISSUE THREAD

**Issue by fas3r** [wenzhixin/bootstrap-table#1949]
Hello,

When using the toolbar and ShowColumns options in the table. Is there a way to exclude a column from been listed in the "select / LIsts"  ? 

I use visible : false on some columns and I would like to keep it that way. Unfortunately, with ShowColumns at true, it's possible to make them visible as they are listed there. 

Thank you by advance.

**Comment by dabros** [comment]
@fas3r - look at `onPostHeader` callback then use simple jquery selector to remove those you dont want.

You can define this as js array of names, or whatever convention, then iterate and `$.hide()` or similar.

**Comment by wenzhixin** [comment]
There is an option: `switchable`

**Comment by dabros** [comment]
@fas3r - that there is, in column options: http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options
