### ISSUE TITLE
How can I use pageNumber to backend,not offset

### ISSUE THREAD

**Issue by shenyun** [wenzhixin/bootstrap-table#1950]
as the title .
how can I use pageNumber to backend,not offset.

**Comment by dabros** [comment]
@shenyun - horrible explaination, but it sounds like you want to change the `queryParam` name from `offset` to `pageNumber` for server side pagination.

if so, see `queryParam` - there are plenty of uses here in github issues if you remove 'is:open' filter, as well as some examples using it: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

In that example it uses name of inputs, but you can define array yourself with whatever index, like:

```
'pageNumber': // get offset then X by number items
```

However, the doco seems to indicate it has a preset that includes 'pageNumber', read the description: http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by wenzhixin** [comment]
@dabros is right.
