### ISSUE TITLE
refresh方法调用，pageNumber没有重置为1,和问题#1647其实是一样的

### ISSUE THREAD

**Issue by mengyou658** [wenzhixin/bootstrap-table#1951]
这里有折衷的解决方式：
queryParams: function (params) {
               // 判断是否是refresh，重置pageNumber和offset
            },
看看需不需要在程序里面重置，还是说提供的refresh方法就是刷新当前页的，那我这里就没什么问题

**Comment by mengyou658** [comment]
我试过使用selectPage, 1 的方式，但是sidePagination: "server",的时候，如果之前查询到的数据是空的，这此selectPage就没有发出请求来从服务器请求数据。

**Comment by wenzhixin** [comment]
可以考虑加个属性

**Comment by wenzhixin** [comment]
关闭该问题 ，统一为 #1647

**Comment by wslpeter** [comment]
没看懂，到底这个问题是如何解决的，这里统一为#1647，而#1647中又说看这里...

**Comment by wslpeter** [comment]
没看懂，到底这个问题是如何解决的，这里统一为#1647，而#1647中又说看这里...
确定是以下这样解决吗？
$('#table').bootstrapTable('refresh', { silent: true, query: { pageNumber: 1 } });
$('#table').bootstrapTable('selectPage', 1);

**Comment by wenzhixin** [comment]
还没解决，统一放到 #1647 问题下，等有空一起解决。
