### ISSUE TITLE
hideRow method not working correctly with fixed columns

### ISSUE THREAD

**Issue by nicolaas19** [wenzhixin/bootstrap-table#1952]
THe showRow / hideRow methods (http://issues.wenzhixin.net.cn/bootstrap-table/#methods/showRow-hideRow.html) do not play nicely with a table with fixed colums (http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/fixed-columns.html).

The contents of the fixed columns always remain visible as-is, only the rows of the main table (i.e. the non-fixed columns) are shown / hidden as required by the showRow/hideRow methods.

**Comment by dabros** [comment]
@nicolaas19 - please create a fiddle showing this behaivour: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

thanks

**Comment by nicolaas19** [comment]
It's my first JSFiddle, so here it goes:
https://jsfiddle.net/e211v99k/3/

Default is all rows visible (the alignment somehow seems to be a bit off, but anyway). When you click the "Hide row" button, the second row in the table is hidden on the right hand side of the table, but not on the first fixed column.

**Comment by dabros** [comment]
@nicolaas19 - thanks

How i see it is that `toggleRow` is endpoint for hide/showrow actions, and needs override or extension in fixed-columns extension js file.

https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js
```javscript

    BootstrapTable.prototype.toggleRow = function (index, uniqueId, visible) {
        if (index === -1) {
            return;
        }

        this.$body.find(typeof index !== 'undefined' ?
            sprintf('tr[data-index="%s"]', index) :
            sprintf('tr[data-uniqueid="%s"]', uniqueId))
            [visible ? 'show' : 'hide']();
    };
```

Would be same or similar, with similar call to `this.$fixedBody` as well as `this.$body`, prob an extension using something like `_toggleRow.apply(...)`, if that is possible.

https://github.com/wenzhixin/bootstrap-table-fixed-columns/blob/master/bootstrap-table-fixed-columns.js

Might get chance to do test later, but anyone else feel free to create **PR** (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by dabros** [comment]
@nicolaas19 @wenzhixin @djhvscf  - tried solving this, cant seem to get fixed-columns working with 'table from html' approach at all.

Not sure if this is another bug or something you can do for me, but if you can get it working im happy to solve the original issue

http://jsfiddle.net/dabros/2ub1tr0h/2/

**Comment by dabros** [comment]
@nicolaas19 @wenzhixin @djhvscf

bump

**Comment by djhvscf** [comment]
@dabros I think we need to use an built-in array where we can "save" all rows that are hidden or visible but I don't know how to identify each one.. I mean if I hide some rows, how can I show a specific row if I don't have any unique value on those rows... Did I explain me?

**Comment by dabros** [comment]
@djhvscf - if you can rule out this 'table from html' bug and get the fiddle working, im happy to look again and explain. I just want to get a working fiddle without ignoring this other potential bug

**Comment by nicolaas19** [comment]
@dabros - could you describe what exactly you are trying to achieve with your fiddle ([http://jsfiddle.net/dabros/2ub1tr0h/2/](url))? I tried to have a look at it, but all that I could see is that you miss the fixed columns CSS part.

**Comment by dabros** [comment]
@nicolaas19 @djhvscf - as i stated, I came accross another bug while creating that fiddle, so stopped it there and posted to ask if an issue or solved already.

The 2nd bug is when creating from html, if you can fix that or provide another working jsfiddle with fixed-columns (which ive never used myself, nor am at all involved with js/html work atm) then im happy to look at original issue again

**Comment by wenzhixin** [comment]
Added new version fixed-columns extension: https://github.com/wenzhixin/bootstrap-table/commit/91977960a5705cd074067b2670483b5e9d5c1f44
Develop example: http://dev.bootstrap-table.com/examples/#extensions/fixed-columns.html
