### ISSUE TITLE
Can't extend Array because of use of for-in in Bootstrap Table

### ISSUE THREAD

**Issue by finkelm** [wenzhixin/bootstrap-table#1953]
Extension of Array objects (as in for example if I want a `Array.prototype.random` function) causes Bootstrap Table to break because of inclusion of `for - in` for example in 

```
    var getItemField = function (item, field) {
        var value = item;

        if (typeof field !== 'string' || item.hasOwnProperty(field)) {
            return item[field];
        }
        var props = field.split('.');
        for (var p in props) { <---- right here
            value = value[props[p]];
        }
        return value;
    };
```

See here for why this is a bad idea: http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea

**Comment by djhvscf** [comment]
Interesting.. Can you open a PR and share us an example with the change??
Thanks

**Comment by finkelm** [comment]
This occurs several times, and it might be appropriate at certain times. In `getItemField` it is not, however, and so `var p in props` should be replaced with `var i = 0; i < props.length; i++`, and `var p = props[i];` So the full function would be:

```
    var getItemField = function (item, field) {
        var value = item;

        if (typeof field !== 'string' || item.hasOwnProperty(field)) {
            return item[field];
        }
        var props = field.split('.');
        for (var i = 0; i < props.length; i++) {
            var p = props[i];
            value = value[props[p]];
        }
        return value;
    };
```

I'm not exactly sure where or how this function is being used, however, I am just noting that it breaks a programmer's ability to extend `Array` objects. And I do not think it should do that?

**Comment by djhvscf** [comment]
You're right.. I think that this change is a good improvement for our plugin

**Comment by djhvscf** [comment]
But also.. you can use this https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Object/defineProperty because if you use another library you can find the same error so I think that the solution is in your side.. Please take a look

**Comment by finkelm** [comment]
I don't think other libraries cause the same error (I have used this with many other libraries). Only Bootstrap Table causes this error. `defineProperty` covers a different usecase, for when you're creating a class. Here is an example of something that would fail with Bootstrap Table:

```
Array.prototype.addAndReturn = function(value) {
  var idx = this.indexOf(value);
  if (idx != -1) {
    return this;
  }
  this.push(value);
  return this;
};
```

This function, for example, creates a function for an array that adds a value to the array if it doesn't already exist and then returns the array, which allows chaining.

**Comment by wenzhixin** [comment]
Use for-of instead.
