### ISSUE TITLE
Multi Dimension data / cellStyle

### ISSUE THREAD

**Issue by altzone** [wenzhixin/bootstrap-table#1954]
Hi,

I might need some help / doc about passing some extra data with the value. 

I work on wit the Boostrap Table Example :http://issues.wenzhixin.net.cn/bootstrap-table/index.html 

My goal is to pass some extra parameters with data that will affect the cellStyle but not based on the value (which actually works fine with cellStyle calling a js function) but based on an extra info in the json reply.

Here is my json data sample :

{
"total":1,
"rows":[
	{
		"product":{
			"id":"2290",
			"name":"GREAT SHAMPOO"
		},
		"suppliers":{
			"sup1":{
				"price":"",
				"style":"secondary"
			},
			"sup2":{
				"price":"",
				"style":"secondary"
			},
			"sup3":{
				"price":"45.10",
				"style":"danger"
			},
			"sup4":{
				"price":"17.21",
				"style":"success"
			}
		}
	}
	]
} 

For all the tables I have a unknown and dynamic number of supplier (sup'x') and I use php to correctly setup the table but I am unable to get the style info working !

getting the data with supplier.supx.price is working fine but I have no way to get the supplier.supx.style passed to a cellStyle function so I could change the classes style based on this data.

Is there something I might not understood about the bootstrap-table or may you please tell me how to work with some extra datas present in the json knowing that we play with a dynamic number of columns.

Many thanks.

**Comment by altzone** [comment]
I found the solution to this issue...
Adding a cellStyle like this

                        cellStyle : function (value, row) {
                                return { classes: row.supplier.supX.style };
                        },
working like a charm !

**Comment by djhvscf** [comment]
Great!! Then I will close this issue @altzone

**Comment by hryamzik** [comment]
And for the whole row:

```javascript
    $('#table').bootstrapTable({
        url: 'table.json',
        rowStyle: function (row, index) { return { classes: row.style }; },
        style: "danger",
        columns: [{
            field: 'ID',
            title: 'id'
        }, {
            field: 'Name',
            title: 'name'
        }, ],
    });
```
