### ISSUE TITLE
Custom search function

### ISSUE THREAD

**Issue by Leprosy** [wenzhixin/bootstrap-table#1956]
Hi, great library...question: is there a way to explicit a custom function to do the search? I'm trying to implement a search like:

"<10" and filter all elements that are less than 10

I can't find any method/event related to this.

**Comment by dabros** [comment]
@Leprosy - there is likely more than one way, but i will recommend what i see as the easiest approach and suggest some flavours for you to look at and decide whether also needed.

**Server Side searches**

Use `data-side-pagination="server"` to use server side code for pagination, sorting and searches:
http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
http://issues.wenzhixin.net.cn/bootstrap-table/options/server-side-pagination.html

That would be easiest fix for allowing advanced searches by parsing the string for patterns like that. For the actual search logic, just google your server side language (php, ect) + "advanced search" or similar terms ("parse for advanced search", ect).

However, there are also ways for providing custom UI to help with this:

**Custom Toolbar**

You can create custom toolbar and provide UI (which will send extra param to your server script) to fine tune your search:
http://issues.wenzhixin.net.cn/bootstrap-table/options/custom-toolbar.html


---

**Extensions**

There are several extensions that i reccomend you look at. Mostly i see them complimenting server-side searches, but you might even make them work as desired entirely client-side.

http://bootstrap-table.wenzhixin.net.cn/extensions/

None of these 'appear' to provide custom search function, but your more than welcome to look at existing exposed options and make a **PR** to add in ability to override core search function (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests)

 **Filter Control** - provides nice UI for each column, havent used myself but assume will be able to integrate with server side code so you can use your custom parsing searches still (search open+closed issues here and google/SO for more examples if needed)


**Filter** - older filter plugin i believe, havent used, looks fairly simple to test though if you want to look at it.

**Multiple Search** - less relevant, as looks like just breaks up search terms by spaces to treat each as search term, but maybe of interest if you wanted to make **PR** or custom code for client-side.

**Toolbar** - quotes "advanced search", and example shows that you can use custom form (which it will automattically wrap in a modal for you if needed) to create advanced search UI. `onColumnAdvancedSearch` looks interesting, but most likely just a callback, not in charge of actual sort.

Those can all be used to enhance your UI, but as i said likely requires **PR** to expose option to override core client-side search behaivour, but easy enough to just use server-side pagination+search, which is what i know others have done in past.

**Comment by djhvscf** [comment]
I think you can use the filter control extension but in order to handle the "<10" string I think we need to develop a new extension in order to "understand" these queries.. Because the extensions mentioned by @dabros don't understand these queries

**Comment by Leprosy** [comment]
I'm using the filter control extension...it's great, but don't have a way to insert a custom search method.

I think that would be a nice core feature, being able to use a custom javascript function to do the filtering.
