### ISSUE TITLE
关于计算div高度的问题

### ISSUE THREAD

**Issue by Liu-xu-dong** [wenzhixin/bootstrap-table#1960]
我用的是服务器分页，这个是由ajax完成的。我现在想在页面加载的时候，让另一个div的高度等于table所在的div高度。但是ajax是异步的，我获取的时候，没有数据，获取到的高度是一个空table的高度。我能不能在ajax返回来执行success的时候，获取一下div高度？这一步该怎么处理？有没有关于callback的地方

**Comment by Liu-xu-dong** [comment]
暂时用定时处理了，0.7秒后计算div高度。但是总感觉不合适。就想找一下回调函数，ajax获取到值应该可以有

**Comment by wenzhixin** [comment]
你可以用事件去处理：http://bootstrap-table.wenzhixin.net.cn/zh-cn/documentation/#事件
例如 `load-success.bs.table`
