### ISSUE TITLE
Fixed-columns extension missing from doco

### ISSUE THREAD

**Issue by dabros** [wenzhixin/bootstrap-table#1963]
@wenzhixin - i looked around for a while but couldnt figure out how to add this extension that appears missing from that list.

There is no `i98e` file matching it, and `extensions.md` is maybe loading them via jquery, but im unsure how and from where.

http://bootstrap-table.wenzhixin.net.cn/extensions/
https://github.com/wenzhixin/bootstrap-table-fixed-columns/
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/fixed-columns.html

**Comment by wenzhixin** [comment]
Added new version fixed-columns extension: https://github.com/wenzhixin/bootstrap-table/commit/91977960a5705cd074067b2670483b5e9d5c1f44
