### ISSUE TITLE
updateByUniqueId should "rerender" the row

### ISSUE THREAD

**Issue by finkelm** [wenzhixin/bootstrap-table#1964]
I have a formatter set up for a column, it is called on table creation, on append, but not on update to make changes. Is there a workaround for this to have a row rerender (call the formatter to appropriately reflect its data state)?

**Comment by djhvscf** [comment]
Sorry, I'm not sure what the problem is.. Can you share a fiddle? Or give more explanation?

**Comment by finkelm** [comment]
Woops, I realized it was actually formatting correctly, my test was wrong.
