### ISSUE TITLE
关于ajax的两个问题

### ISSUE THREAD

**Issue by dxkrs** [wenzhixin/bootstrap-table#1965]
想通过ajax获取后台数据展示在table，碰碰撞撞地研究了一翻，最后搞出来，但存在疑问。
这是我通过重写ajax获取数据并成功显示在table的代码：
```
$('#table').bootstrapTable({
	ajax : function (request) {
		$.ajax({
			type : "POST",
			url : "http://localhost/hplustest/json.php",
			success : function (data) {
				console.log('success');
				console.log(JSON.parse(data));
				data = JSON.parse(data);
				request.success({
					row : data
				});
				$('#table').bootstrapTable('load', data);
			},
		});
	},
	columns : [{
			field : 'id',
			title : 'Item ID'
		}, {
			field : 'name',
			title : 'Item Name'
		}, {
			field : 'price',
			title : 'Item Price'
		},
	]
});
```
问题1：如果自己重写ajax，是否需要在success写
```
request.success({
      row : data
});
$('#table').bootstrapTable('load', data);
```
才能显示？我尝试把两句任意一句删除，table都不能显示数据。其中row改任意名字都可以显示。？？

问题2：如果我使用URL，实际也应该是ajax请求吧，这时候我使用ajaxOptions是否有效？我尝试这样写：
```
url:"xxxxxxx",
ajaxOptions:{type:"POST"}
```
但没有效果，调试窗口显示我还是用GET方法请求地址！

**Comment by dxkrs** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
不好意思，这么晚才回复。

第一个问题不用 `$('#table').bootstrapTable('load', data);` 不过要加上 `request.complete();`，这里有[例子](http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-ajax.html)和[源码](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/custom-ajax.html)。

第二个问题你可以直接设置 table 的 method 属性。文档有写：http://bootstrap-table.wenzhixin.net.cn/documentation/
