### ISSUE TITLE
Sort table with date dd MMM yyyy

### ISSUE THREAD

**Issue by carmcha** [wenzhixin/bootstrap-table#1967]
How can we sort the table with date 01 Jan 2014 formate? Thanks

**Comment by tannermccoleman** [comment]
I think you will have to make a [sorter function](http://jsfiddle.net/e3nk137y/4248/) that makes use of the [javascript Date object](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date), particularly the [getTime() Function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime)

**Comment by dabros** [comment]
@carmcha 

http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-sort.html
http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by djhvscf** [comment]
I think @tannermccoleman is rigth... Please use that option in order to sort the data as you want.. Also there is a PR where we are implementing an option "customSort" where it will be executed instead of built-in sort function..
