### ISSUE TITLE
bootstrap-table-editable didn't submit ajax requests

### ISSUE THREAD

**Issue by billzt** [wenzhixin/bootstrap-table#1968]
I set Column options "editable" like this: 
```html
<th data-field="name" id="name" data-editable="{type:'text', pk:1, url:'tmp/test.php', name:'name'}">Name</th>
```
The edit seems OK. But no data sent to test.php. And the Firefox console shows JS error like this:

```bash
TypeError: g[c] is undefined
```

**Comment by dabros** [comment]
@billzt - you gota trace that error down yourself, simply stating it here without line number or any referance point is useless.

Either make a fiddle (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports) or some other means of us seeing your code if you want help with that error msg.

But the core issue is that (so far as i can, and please feel free to correct me) editable extension doesnt automattically send anything to your server.

See this example: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html

Hit F12 and monitor network to see no network request sent.

By default the editable extension updates local data, up to you to place ajax call inside its callbacks. This is obvious when you look at the example.

https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable

This is also mentioned in #1939

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
