### ISSUE TITLE
The default value for table option 'escape' is 'false' in the document, but it is 'true' in real

### ISSUE THREAD

**Issue by RJHsiao** [wenzhixin/bootstrap-table#1970]
文件記載的 escape 默認值與實際的默認值不同...
麻煩處理一下吧～看是要改哪個

**Comment by djhvscf** [comment]
This issue is fixed.. Use the latest version please

**Comment by RJHsiao** [comment]
@djhvscf Oh, thanks your reply.
I create this issue just because the latest release version (v1.10.0) set option 'escape' true in default,
and I didn't realize that you already changed it after latest release version released.
Your document is in develop version, but most of user like me develop their project with using release version.

**Comment by djhvscf** [comment]
@wenzhixin can you create a new release with this change?? I think @RJHsiao is right

**Comment by wenzhixin** [comment]
OK, I will do it soon.

**Comment by wenzhixin** [comment]
released v1.10.1
