### ISSUE TITLE
Bootstraptable with data-filter-control="select" & export issue

### ISSUE THREAD

**Issue by sendilgan** [wenzhixin/bootstrap-table#1971]
If we have both export and data-filter-control="select" . When i try to export the data the header file has the title & filter values . Is there any ways to stop it while exporting the file?

**Comment by djhvscf** [comment]
Can you provide a fiddle with your issue, please?

**Comment by sendilgan** [comment]
thanks for replying.below is the fiddle
http://jsfiddle.net/4r6g4cfu/162/

you will be able to see the issue in the exported files header will be displaying ITEM ID12345678910

**Comment by sendilgan** [comment]
Are there any workarounds to quickly fix it ?

**Comment by djhvscf** [comment]
Yes, I know what is the problem, but I need to test the solution

**Comment by sendilgan** [comment]
if you need any help in testing i can help on it ..

**Comment by paltrot** [comment]
Hi.

I find a solution. Maybe it is not a good solution but is working for me in simple tables. If you change the function parseString in tableExport.js file like this:

function parseString(data){
                                    if(data.html().indexOf("<select") == -1){
					if(defaults.htmlContent == 'true'){
						content_data = data.html().trim();
					}else{
						content_data = data.text().trim();
					}
					
					if(defaults.escape == 'true'){
						content_data = escape(content_data);
					}
					
                                    }
					
					return content_data;
				}

Ismael.

**Comment by djhvscf** [comment]
Great!! You can use your code like this:

``` js
function parseString(data){
  if(data.html().indexOf("<select") === -1) {
    content_data = data.[defaults.htmlContent === "true" ? 'html' : 'text']().trim();
  }
```

@paltrot

**Comment by sendilgan** [comment]
Thanks for replying.
I am using the tablefilter.js thats used in the bootstrap master table example.Below if the file 

http://rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js

and i am not sure how i will be able to add this in this js file.
Can you help on it ? if you can give me a working fiddle  that will be really helpful.

**Comment by talatbaig** [comment]
Hi,

Is this going to be merged in dev/master?

Another solution could be to use 
<th data-tableexport-value="export title">title</th> -> "export title" instead of "title" will be exported

https://github.com/hhurz/tableExport.jquery.plugin#data-tableexport-value

**Comment by hollismaynell** [comment]
Hi,
i haved tried the solution,but didn't solve ......t will cry.... 
@paltrot

**Comment by djhvscf** [comment]
I think you have to open an issue here  https://github.com/hhurz/tableExport.jquery.plugin/

**Comment by hygu98** [comment]
I was able to get this working by updating the parseString function in tableExport.js:

`function parseString(data){
          if(data.html().indexOf("<select") === -1){
            if(defaults.htmlContent == 'true'){
              content_data = data.html().trim();
            } else {
              content_data = data.text().trim();
            }

  					if(defaults.escape == 'true'){
  						content_data = escape(content_data);
  					}
  				} else {
            content_data = data.children(":first").text().trim();
          }
          return content_data;
			   }`

**Comment by yousraelh** [comment]
@sendilgan you can check this if you want [https://jsfiddle.net/YousraElh/b3u7vpsy/](url)
