### ISSUE TITLE
Apply search on click or other event and disable auto refresh

### ISSUE THREAD

**Issue by Forsakenrox** [wenzhixin/bootstrap-table#1972]
I try all of the methods in docs , but did understand how to disable the dynamic update on search\filter\e.t.c. and make it a manual, like a on.click or somthing else. any ideas ?

**Comment by djhvscf** [comment]
Can you explain a little bit more and provide a fiddle??

Thanks

**Comment by dabros** [comment]
@Forsakenrox - there are many examples of manual triggered search, including in official doco.

http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

Maybe easiest when using server side, but not limited to it either - just search github issues and google (SO), custom toolbar, filterBy, ect.

Here are a few, but not all of them or neccessarily the best (as some not titled so well so harder to find):

Custom search function #1956
Is there a method that i can trigger search manually in client side. #1868
on click of refresh event #1838
Search after click key enter #1827
How to format the search input? #1810
Search form #1804
"search" by a search method? #1687

**Comment by Forsakenrox** [comment]
Thanks for help, but i stil try to find table filter extension example.
In your list of issues i find good example with search usage:

$tbl.bootstrapTable('resetSearch', 'the text to search')

This realy work, but how about something like:

$tbl.bootstrapTable('resetFilter', 'FilterName', 'the text to filter')

P.S. i use server side pagination and filter setting up by GET like *****%filter={id:20}.

So, i need method with this features. Thanks.

**Comment by dabros** [comment]
@Forsakenrox - well you didnt mention filter-control at all, though good to know your using server side

I havent used filter-control myself, but the obvious step is to get it working fine with filter-control+server side, with default search triggers ofcourse but you need to get it working to eliminate any other issues.

Once you confirmed that is working, create a fiddle (if need be switching to client-side, less important for this step, see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports for fiddle examples)

Then look at https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/filter-control/bootstrap-table-filter-control.js#L189, which at this time points to where keyevents for search triggers are added.

If still feel you 'need' manual trigger, copy the bootstrap-table-filter-control.js file into the contents of fiddle js panel (turning off onLoad using settings icon) and then change those lines to change key events, plus maybe the lines above to add whatever button/s you want to trigger this. 

"Enter" key events can be left in/added, new buttons, whatever tweaks you want in that `createControls` function. Get it looking like what you want, then we can look at that fiddle as proof for a **PR** (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests)

---

These steps are neccessary, as you want to change the core behaviour of filter-control, and are yet to confirm you have it working in a standard manner yet.

Myself or others will happily make **PR** if you proof concept of how you see this implemented, and our **PR** will most likely expose this different behaivour via an option, but you need the concept working first.

**Comment by wenzhixin** [comment]
I think the extension doesn't support the feature.
