### ISSUE TITLE
how to fire onLoadSuccess after data loaded from AJAX call ?

### ISSUE THREAD

**Issue by fas3r** [wenzhixin/bootstrap-table#1973]
Hello,

I'm using the following code to retrieve data from a DB with ajax when a button is fired. 

`$("#submitform").on("click", function(e)
			{
				e.preventDefault();
				var formSerialize = $("#formSearch").serializeArray();
		  	formSerialize.push({ name: "action", value: "submitsearch" });
		  	$.post(
		        "/table.php",
		         formSerialize,
		         "json"
		        ).done(function(data)
		    	{
		    		
		    		$('#my_table').bootstrapTable('load', jQuery.parseJSON(data));
		    	}
		  	) 
			});`

The data are loaded correctly from AJAX, however "OnloadSuccess" is not fired.

Thank you by advance.

**Comment by dabros** [comment]
@fas3r - well, your not loading from 'remote data', as the doco states that event requires, as your feeding in the array direct.

http://bootstrap-table.wenzhixin.net.cn/documentation/#events

Look at http://issues.wenzhixin.net.cn/bootstrap-table/ and use similar event `console.log` setup to figure out best fit for your callback.

It really depends on what it does, but as a rule of thumb, if it doesnt fit in that `done` handler (needs table body or header setup first) then use `postBody` or `postHeader` - which would be required if you need it to trigger on any body refresh action.

**Comment by fas3r** [comment]
Hello,

Thank you for your answer I will check. Yes the idea is to refresh the table after each click.

**Comment by wenzhixin** [comment]
If the problem exists, reopen the issue and provide a jsFiddle.
