### ISSUE TITLE
Pagination + Remove

### ISSUE THREAD

**Issue by gpassero** [wenzhixin/bootstrap-table#1975]
When I remove all rows from page 1 table won't go automatically to page 2 and pagination toolbar (with page number selection) is hidden.

**Comment by djhvscf** [comment]
Please provide a fiddle

**Comment by dabros** [comment]
@gpassero - https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
I think you need to call `refresh` method after removed all rows.
