### ISSUE TITLE
Angular Integration Doesn't Appear To Work

### ISSUE THREAD

**Issue by opticyclic** [wenzhixin/bootstrap-table#1978]
I have tried to duplicate the Angular Integration on Plunkr with no success.

http://plnkr.co/edit/T2AHwn?p=preview

Why isn't the grid showing? Are all the dependencies correct?

**Comment by strikerjjb** [comment]
@opticyclic you need to add the ng-app directive to your html tag in your plunkr.

Change <html> to <html ng-app="app">

**Comment by opticyclic** [comment]
Oops! Thanks for checking. I updated the plunkr and it now works.
http://plnkr.co/edit/T2AHwn?p=preview
