### ISSUE TITLE
server-side-pagination doesn't work again! help! 

### ISSUE THREAD

**Issue by Whale4** [wenzhixin/bootstrap-table#1980]
Hi all,

i know, this issue has been explain here, but it's no results for me, and i need to asking this question again. 

I tried to build the server-side-pagination for my table, and this is my steps:

first of all, server side:

![capture2](https://cloud.githubusercontent.com/assets/17048132/12889181/d03a3850-ce8e-11e5-942a-fd88d6ff7aed.JPG)

the second,  client side:

![capture](https://cloud.githubusercontent.com/assets/17048132/12889184/d69765b0-ce8e-11e5-9437-b582045b1e01.JPG)

The table get values, but pagination and search doesn't work!

Please help!

**Comment by Whale4** [comment]
Hi all,

i know, this issue has been explain here, but it's no results for me, and i need to asking this question again. 

I tried to build the server-side-pagination for my table, and this is my steps:

first of all, server side:


![capture2](https://cloud.githubusercontent.com/assets/17048132/12889181/d03a3850-ce8e-11e5-942a-fd88d6ff7aed.JPG)


the second,  client side:

![capture](https://cloud.githubusercontent.com/assets/17048132/12889184/d69765b0-ce8e-11e5-9437-b582045b1e01.JPG)

The table get values, but pagination and search doesn't work!

Please help!

**Comment by dabros** [comment]
@Whale4 - not enough detail sorry

Please include copy of your json return, whether youve carefully monitored any console or network errors, what you mean by "not working" (in exact detail).

---

However, i can guess the most likely cause.

You do know how pagination and search works right?

Bootstrap table sends param with the data request, and YOUR server code has to use that to return the new subset. Thats what the "server" in `side-pagination` means, it means your server code is what does the actual search/pagination.

You have no visible search code, nothing i can see that looks like your using those param to actually make a search or actually paginate.

Hit F12 and monitor network requests when you trigger search or paginate, you can see whats being sent, so use that to do whatever.

**Comment by Whale4** [comment]
**dabros**, thank you for your feedback! 

you are exatcly right! I don't quite understand how it actually works! 

And now i doesn't have any code for it..  :)

For me this type of plugins or libraries like the *magic*, where you need just include .js and .css files and past  respective html code.  Now I will try to understand this deeper.

Thank you!

**Comment by dabros** [comment]
@Whale4 - change to `client` for `side-pagination` then, all you need return is `rows` and not worry about search or pagination, the js *magic* will take care of it then.

`server-side` is mostly for when people want to tweak the search approach or have performance concerns with massive dataset (dont want to return it all in a single data request)

**Comment by jaydeepgiri** [comment]
hello @Whale4, 
for your information, when you want the data to be loaded automatically, the rows field of the data must be the nested array..
like
```

{
  "total": 800,
  "rows": [
    {
      "id": 0,
      "name": "Item 0",
      "price": "$0"
    },
    {
      "id": 1,
      "name": "Item 1",
      "price": "$1"
    },
    {
      "id": 2,
      "name": "Item 2",
      "price": "$2"
    }
  ]
}
```
confirm that your json output is like this..
