### ISSUE TITLE
Just one cookie at a time?

### ISSUE THREAD

**Issue by luisapuyen** [wenzhixin/bootstrap-table#1983]
Been testing this plugin, which is great, but there's this issue:

When I use both the search filter cookie (tableId.bs.table.pageNumber) and the page navigation cookie (tableId.bs.table.searchText), only the latter is applied to the bootstrap table.

Otherwise both of them work if I use them independently (if I filter on first page, or navigate to another page without any filter).

**Comment by djhvscf** [comment]
Provide a fiddle because I think this is an old issue but I would like to confirm it. @luisapuyen

**Comment by dabros** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by luisapuyen** [comment]
Ok, the jsFiddle here:

[Example code](https://jsfiddle.net/luis_apuyen/b7518dkf/)

Search for instance by "fer", go to the second page and re-run. It will display the first page.

If I remove the search text, the page cookie will work.

**Comment by dabros** [comment]
@luisapuyen - ill let @djhvscf  take this one, but i strongly recomend against using cookie plugin with jsfiddle, as ive noted issues with that for in #1840 (and elsewhere ages back i think)

Not saying there isnt an issue, but best to run in proper environment and confirm exact flow - cant rely on refresh or re-run of jsfiddle to accurately mimic behaivour in some cases like this.

**Comment by luisapuyen** [comment]
ok thank you! The exact same result is happening in my development environment. I don't think it's jsFiddle's fault in this case.

**Comment by Falseee** [comment]
The cookies will be created correct, i think a pagination refresh will fix it.
Also possible is that the search reset the current page number.
But i don't understand the full Code yet, so i cant fix it..

**Comment by Tulvia** [comment]
anything on this yet?

**Comment by djhvscf** [comment]
Please see this fiddle https://jsfiddle.net/djhvscf/b7518dkf/15/

**Comment by wenzhixin** [comment]
Fixed in develop
