### ISSUE TITLE
Table elements inside bootstrap table gets select also

### ISSUE THREAD

**Issue by ewsun** [wenzhixin/bootstrap-table#1984]
There is javascript error when table td cell contains other regular table elements( not bootstrap table elements ).  That is because in BootstrapTable.prototype.initTable function,  it selects all children elements not the immediate child.

Example:
<pre><code> this.$el.find(<b>'tbody tr'</b>).each(function () {
    var row = {};

    // save tr's id, class and data-* attributes
   ...
    $(this).find(<b>'td'</b>).each(function (i) {
        var field = that.options.columns[i].field;
        ...
    });
   ...
});</code></pre>
This will select all the tds which include the tds in its child elements.

It should use immediate selector:
<pre><code>
this.$el.find(<b>'>tbody>tr'</b>)<br>
$(this).find(<b>'>td'</b>)<br></code></pre>

**Comment by djhvscf** [comment]
Can you open a new **PR**, @ewsun ?

**Comment by ewsun** [comment]
Sorry, I am new to GitHub.  This is my first issue report. :).  Did you mean create a new Pull Requests?

**Comment by djhvscf** [comment]
Exactly.. Create it please and provide a fiddle with the issue and another one with the issue fixed

**Comment by dabros** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

**Comment by djhvscf** [comment]
@ewsun any update here?

**Comment by Falseee** [comment]
JsFiddle with issue : http://jsfiddle.net/1k715pjz/1/
JsFiddle without issue : http://jsfiddle.net/n9w053h5/1/

PullRequest: #2037

**Comment by wenzhixin** [comment]
Merged
