### ISSUE TITLE
Hide a column in a card view does not work correctly

### ISSUE THREAD

**Issue by juandasgandaras** [wenzhixin/bootstrap-table#1993]
Hi:

I have the the next code:

```
<table id="table" data-show-header="false" data-card-view="true">
    <thead>
        <tr>
            <th data-field="id">Item ID</th>
            <th data-field="name">Item Name</th>
            <th data-field="price" data-card-visible="false" >Item Price</th>
        </tr>
    </thead>
</table>
```

And I was trying to hide the column with data-field="price" in a card view but it is not working correctly.

I was trying to do it over the example:

[http://jsfiddle.net/wenyi/8svjf80g/41/](http://jsfiddle.net/wenyi/8svjf80g/41/)

But if I put:

 `<th  data-card-visible="false" data-field="price">Item Price</th>`

The result it is not as expected.

Thanks in advance

**Comment by wenzhixin** [comment]
Fixed: http://jsfiddle.net/wenyi/8svjf80g/313/
