### ISSUE TITLE
Bootstrap Table with meteor: Where to define detailFormatter

### ISSUE THREAD

**Issue by touch2hussain** [wenzhixin/bootstrap-table#1995]
I have tried  bootstrap table with simple HTML and Js pages there we difine `detailFormatter`anywhere in the included JS file. But in meteor project I tried putting the function in  `if (Meteor.isClient) {}` and  `Template.training.rendered = function(){}`block, But its not getting called.

```
if (Meteor.isClient) {
    function detailFormatter(index, row) {
       console.log("detailFormatter is called")
      //My stuffs here
  }
}

```

```
 Template.training.rendered = function(){
       function detailFormatter(index, row) {
       console.log("detailFormatter is called")
      //My stuffs here
  }
}


```

But in both place **`detailFormatter`** not getting called. How to do it in meteor

**Comment by djhvscf** [comment]
@touch2hussain can you provide a fiddle, please?

**Comment by touch2hussain** [comment]
Please be informed that there is no meteor version of Jsfiddle. Meteor not available as simple js file

@wenzhixin  need your intervention.

**Comment by djhvscf** [comment]
ok.. @touch2hussain thanks for the information.. @wenzhixin can help you

**Comment by wenzhixin** [comment]
@touch2hussain you can try to create a file (for example: `formatter.js`):
```js
Formatter = {
    detailFormatter: function () {}
};
```

and then use like:
```html
<th data-field="detail" data-formatter="Formatter.detailFormatter">
```

Hope to help you.

**Comment by touch2hussain** [comment]
No @wenzhixin  its not working, The method not being called.

**Comment by wenzhixin** [comment]
OK, let me have a try.

**Comment by touch2hussain** [comment]
Please !

**Comment by touch2hussain** [comment]
@wenzhixin  any progress? waiting !!

**Comment by wenzhixin** [comment]
Sorry, it's late to test this issue, what I suggest to you is to use `Via JavaScript` to solve the problem:

```
<table id="table"></table>
```
```
$('#table').bootstrapTable({
    columns: [{
        field: 'id',
        title: 'Item ID',
        formatter: function () {}
    }, {
        field: 'name',
        title: 'Item Name',
        formatter: function () {}
    }, {
        field: 'price',
        title: 'Item Price',
        formatter: function () {}
    }],
    data: [{
        id: 1,
        name: 'Item 1',
        price: '$1'
    }, {
        id: 2,
        name: 'Item 2',
        price: '$2'
    }]
});
```
