### ISSUE TITLE
Keep data sorting after table data refresh

### ISSUE THREAD

**Issue by monchoz** [wenzhixin/bootstrap-table#1997]
Hi

Having bootstrap-table getting data using `data-url`, is it possible to keep/hold a column filter state (asc, desc) **and data order** after a table refresh is done? Meaning a table refresh of the action triggered by clicking the native refresh button or (more what I'm really looking to accomplish) when filter by selecting a value on a `data-sortable` column.

Something like the `server-side` version of sorting.

Thanks!

**Comment by monchoz** [comment]
A method to sort data by column name and order could help, I've reviewed the docs but didn't found a method for that.

**Comment by monchoz** [comment]
This worked for me! https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/cookie

**Comment by wenzhixin** [comment]
OK, let's close this issue.
