### ISSUE TITLE
Pagination doesn't work on the table has sub tables

### ISSUE THREAD

**Issue by carmcha** [wenzhixin/bootstrap-table#2000]
Hi I have built a table with some subtables (like http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/sub-table.html but I have 15 rows at parent table). I have already added data-pagination="true" at <table> but the pagaination doesn't work. 

<table id="" class="table1" data-pagination="true">

Please kindly advise. Thanks

**Comment by dabros** [comment]
@carmcha - fiddle pls (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by carmcha** [comment]
@dabros Thanks for your reply. Here is the fiddle
https://jsfiddle.net/carmcha/esxk2fev/2/

**Comment by dabros** [comment]
@carmcha - your fiddle is broken in many ways

I started fixing but so many issues, beyond the fact you never setup the js panel options (cog icon), never called to setup initial table "#table", empty data-field values, ect.

Look at the link i gave you and the example fiddles there (i recommend "table from data" example as easier to debug, data can just be dummy array created using `for(var i;i < 10;i++)` style loops.

See the very few external resources actually needed (jquery loaded through js panel, absolutely no wrap as you use `$.document.ready` anyway, and wrap causes issues often) and work from bottom up, just adding what you need to meet minimal use case example, not trying to reverse more complex local code.

Get a working subtable, ignoring pagination, then add pagination option - then we can help you

**Comment by wenzhixin** [comment]
Please update the fiddle

**Comment by carmcha** [comment]
Please check. 
http://jsfiddle.net/carmcha/esxk2fev/7/

Thanks

**Comment by wenzhixin** [comment]
It seems that bootstrap table does not support the transition from html with sub table.

**Comment by dabros** [comment]
@carmcha - you need to check your fiddles

There is a console error because you havent made a working subtable WITHOUT pagination

Perhaps as @wenzhixin mentions, but then why do you post it with no comment???

You asked for help with a specific pagination issue, so get a table working without pagination so we can add it in then see what happens
