### ISSUE TITLE
Table heading not resizing properly

### ISSUE THREAD

**Issue by rpannell** [wenzhixin/bootstrap-table#2002]
I am seeing an issue where the table heading row isn't responding correctly to the window resizing.  If you load the table when the browser is not full screen and resize the browser to full screen the heading row isn't lining up the table content.  I can reproduce the error using the examples site as well, see the attached screen shot.  The reverse is a problem as well (from full screen to smaller).

![image](https://cloud.githubusercontent.com/assets/8668072/13114639/59bb146c-d562-11e5-9995-e4d3e8ed7328.png)

**Comment by dkijkuit** [comment]
It seems to correct the headers after you sort any column.

**Comment by djhvscf** [comment]
This issue is fixed on #2027
