### ISSUE TITLE
can't render html inside a <td> tag

### ISSUE THREAD

**Issue by lnxg33k** [wenzhixin/bootstrap-table#2003]
Hi, I am using the table with the following attributes `data-toggle="table" data-show-export="true" data-pagination="true" data-click-to-select="true" data-maintain-selected="true" data-show-export="true" data-show-pagination-switch="true" data-striped="true" data-toolbar="#toolbar"` and when I insert a HTML tag inside a `<td>` tag it doesn't get render and it shows me the tag instead.

`<td>{% if i|get:"_source"|get:"black" %}<a href="">True</a>{% else %}-{% endif %}</td>`

Result:
<img width="510" alt="screen shot 2016-02-16 at 5 12 10 pm" src="https://cloud.githubusercontent.com/assets/1170490/13078508/84f7a52e-d4d0-11e5-9a96-576b41eeefd8.png">

Using an old .js version would work fine but not the latest one.
Thanks

**Comment by sky93** [comment]
Add this in your `<table>` tag: `data-escape="false"`

**Comment by djhvscf** [comment]
Please use the latest version [10.0.1](https://github.com/wenzhixin/bootstrap-table/releases/tag/1.10.1)
