### ISSUE TITLE
如何•固定表头？

### ISSUE THREAD

**Issue by movieliang** [wenzhixin/bootstrap-table#2004]
你好：
1、在功能介绍说可以•固定表头，我找了很久很久也没找到怎么设置？
2、如何获取一个单元格的数据？
例如我双击一行，弹出窗口显示数据的详细信息。
弹出窗口的URL需要获取表格中的一个数据作为参数来显示不同的数据。
` 
    function dbclick(id) {<br>
            var client = $("#editUrl").attr("src");
            var newsrc = client + id;
        $("#editUrl").attr("src", newsrc);
            $('#myEdit').modal();
        };
 `
`$('#table1').bootstrapTable({
        onDblClickRow:function(){
           ..................// id为表格一个值，如何获取？？？
            dbclick(id)；
        }       
    });`

**Comment by wenzhixin** [comment]
加上 height 属性就可以固定表头了，点击事件有参数的

**Comment by movieliang** [comment]
点击事件有参数,有没示例双击或单击一行，获取当前行的数据。

**Comment by wenzhixin** [comment]
看文档：http://bootstrap-table.wenzhixin.net.cn/documentation/#events，有语法。

**Comment by khspace** [comment]
当表在 nav-Tab 中，加上data-height  ,表头也无法固定
