### ISSUE TITLE
there is an error about export when sidePagination is server

### ISSUE THREAD

**Issue by agesora** [wenzhixin/bootstrap-table#2005]
when sidePagination is server and  exportDataType is selected,it will export the datas that i choose basic.
so i check the code in bootstrap-table-export.js and rewrite.

i change 
``` javascript
 that.load(selectedData);
 doExport();
 that.load(data);
```
to
```javascript
  if(that.options.sidePagination === "server"){
     that.refreshOptions({sidePagination:"client"});
     that.load(selectedData);
      doExport();
      that.refreshOptions({sidePagination:"server"});
      that.load(data);
    }else {
      that.load(selectedData);
      doExport();
      that.load(data);
    }
```
in $menu.find('li').click

the result will be right

**Comment by djhvscf** [comment]
Great! Provide a fiddle please

**Comment by dabros** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

If you provide a fiddle then it can be used as proof for a **PR** (made by you or someone else) including that change.

If you do make the **PR**, pls include "Fix #2005" in title - but regardless of who it is we do need fiddle.

I usually just include inline copy of js file with changes, but you can see in #2006 that you can actually direct to a commit/PR version if you want.

**Comment by wenzhixin** [comment]
Any PR is welcome.

**Comment by vickyrathee** [comment]
Here is the JsFiddle http://jsfiddle.net/4r6g4cfu/207/
The export all option is exporting first page only. And paging is also removed when click on export but not rolled back after export.

**Comment by vickyrathee** [comment]
One more thing, how to ignore checkbox(state) column in export?

**Comment by nyarachm** [comment]
It seems that when setting server-side table data, many other features stop working! In my case pagination, check/uncheck rows, export selected, sort and the table search all stop working

**Comment by dabros** [comment]
@nyarachm - please delete your post here and contain this question to #2105 which you opened, as not in the scope of OP in this thread, and spamming same question in unrelated posts confuses issues.

**Comment by dabros** [comment]
@vickyrathee - this should gelp get you sorted with ignoring/skipping certain columns

#1551

**Comment by vickyrathee** [comment]
@dabros Thank for pointing me correct for ignoring column, the server side table data export is still a bug as the actual thread is about.


> The export all option is exporting first page only. And paging is also removed when click on export but not rolled back after export.
> Here is the JsFiddle http://jsfiddle.net/4r6g4cfu/207/

**Comment by djhvscf** [comment]
@vickyrathee see this: https://github.com/wenzhixin/bootstrap-table/pull/2106

**Comment by vickyrathee** [comment]
Not sure if you published the code on cdn or not, but this fiddle is still not working with export all http://jsfiddle.net/4r6g4cfu/207/

**Comment by djhvscf** [comment]
The PR is not merged so this is not published on any CDN.. you can see my develop branch https://github.com/djhvscf/bootstrap-table/blob/develop/src/bootstrap-table.js

**Comment by djhvscf** [comment]
You should wait until the PR is merged

**Comment by vickyrathee** [comment]
Okay thanks, i guess it's around a month you've not released the new version of table after 1.10 will help couple of bugs fixed if you could release soon.

**Comment by djhvscf** [comment]
@wenzhixin

**Comment by heenaMahajan** [comment]
@wenzhixin The export all option is exporting first page only. And paging is also removed when click on export but not rolled back after export.
