### ISSUE TITLE
How to search within row details? 

### ISSUE THREAD

**Issue by tomatow** [wenzhixin/bootstrap-table#2007]
Hi, 
I had a table with 5 columns with perfectly working search on whole data set. As project expands, I've decided to put content of 2 columns into row details, which is expandable by "+" sign. 

Since then using search doesn't find data which is in details view. What can I do to link this data with search scope? 

Thanks in advance.

**Comment by fsauter** [comment]
Hi, one way is to implement the search by yourself using the `customSearch` option.

See: [bootstrap-table.js#L1157](https://github.com/wenzhixin/bootstrap-table/blob/468169cde5bdbf2178a9299d288622fe93777aaa/src/bootstrap-table.js#L1157)

As an alternative you could try to include the columns but hide them using the `visible` column option but I didn't try that.

Cheers Flo

**Comment by dabros** [comment]
@tomatow - like @fsauter  said, if you want to stick to purely client-side pagination then those are the way to go.

If using `server-side` pagination (where search and pagination controlled by server side script) then this is irrelevant as you just define whatever search sql or similar in your server code, bootstrap table just sends your search param in a data request.

**Comment by djhvscf** [comment]
I will prepare a example for you @tomatow

**Comment by djhvscf** [comment]
After some test, I think this feature is not supported. This will be labeled as `Feature`

**Comment by djhvscf** [comment]
Duplicate #4287
