### ISSUE TITLE
How to show checkbox alternatively?

### ISSUE THREAD

**Issue by eshengsky** [wenzhixin/bootstrap-table#2008]
Now I want to show checkbox columns in some rows, and others not. 
I tried to use formatter: function (value, row) {...} in checkbox column, but it shows 2 checkbox in each column. Then I tried to use js to modify the checkbox column after table and data are all ready, but I don't know the event of ready.
Who can help me? Thx!

**Comment by djhvscf** [comment]
You can use the post-body event in order to know when the table is renderded but anyway I will prepare an example for you

**Comment by wenzhixin** [comment]
You can use `data-events` to register the event of the input.

**Comment by dabros** [comment]
@eshengsky - why dont you you look at https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports and produce fiddle that you can use the `onPostBody` event to disable the checkboxes how you are thinking of doing it

We can then help you out with refining the approach if needed, or even suggesting alternative approach

**Comment by eshengsky** [comment]
thanks all.
