### ISSUE TITLE
列宽度设置在chrome下不起作用，但是在firefox下没有问题

### ISSUE THREAD

**Issue by mogralee** [wenzhixin/bootstrap-table#2009]
列宽度设置在chrome下不起作用，但是在firefox下没有问题。不知道是不是因为，我在bootstrap table之外实现了分页功能，而没有使用bootstrap内置的数据加载及分页。
我看了一下HTML
`<th style="width: 100px; " data-field="sku" tabindex="0">
    <div class="th-inner ">SKU</div>
    <div class="fht-cell" style="width: 454px;"></div>
</th>`
感觉是第二行的div宽度出现了问题。正常的在firefox下这个宽度是99px请问有什么方法能解决呢，谢谢

**Comment by mogralee** [comment]
是<td style="width: 100px;">GET48302</td>的width设置没有起作用

**Comment by wenzhixin** [comment]
用 class 设置可以吗？是否你的 table 设置了布局？

**Comment by zhu915139481** [comment]
我也遇到这个问题了，请问你怎么解决的?

**Comment by hhguang** [comment]
我也遇到这个问题，应该是因为列标题不允许换行，我在bootstrap-table.css里去掉了
`white-space: nowrap`

> 
> .fixed-table-container tbody td .th-inner {
>     padding: 8px;
>     line-height: 24px;
>     vertical-align: top;
>     overflow: hidden;
>     text-overflow: ellipsis;
>     /*white-space: nowrap;*/
> }
>
