### ISSUE TITLE
updateCell - Documentation Incorrect

### ISSUE THREAD

**Issue by tierneykev** [wenzhixin/bootstrap-table#2010]
The docs list the params for updateCell as 

index: the row index.
field: the field name.
value: the new field value.

The correct parameters are
rowIndex
fieldName
fieldValue

**Comment by dabros** [comment]
@tierneykev - **PR** are always welcome :)

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

I believe the files would be under 

https://github.com/wenzhixin/bootstrap-table/tree/develop/docs/_i18n
https://github.com/wenzhixin/bootstrap-table/tree/develop/docs/_i18n/en/documentation
https://github.com/wenzhixin/bootstrap-table/tree/develop/docs/_i18n/es/documentation
https://github.com/wenzhixin/bootstrap-table/tree/develop/docs/_i18n/... ect.

**Comment by djhvscf** [comment]
I'm not sure about this issue... The documentation is correct about method's parameters
