### ISSUE TITLE
Is there a straight forward way to dynamically create columns after receiving remote data.

### ISSUE THREAD

**Issue by ivanoronee** [wenzhixin/bootstrap-table#2013]
I know it is possible to update the details of the various columns after receiving remote data, the problem i am facing is that this assumes the number of columns to be shown is already determined.

I have a scenario where i don't know how many columns will be shown before getting data from the remote server.

**Comment by djhvscf** [comment]
You can use load or refreshOptions methods

**Comment by dabros** [comment]
@ivanoronee - `load` new data, use `refreshOptions` to pass in revised options (which includes columns). 

You can derive these columns from a seperate ajax request OR from inside something like `responseHandler`. `responseHandler` is where you tweak returned data before its loaded, if needed, so if possible just pass in extra param with just column options (which you remove from the `return` of `responseHandler` and instead update an array you use to hold all options).

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
http://issues.wenzhixin.net.cn/bootstrap-table/ (many examples use `responseHandler`)

I cant provide entire use case here, especially as this doesnt fit under label of bug or specific feature request

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker

Post to SO and link from here (then close this issue).

I will check the SO link out later and if you have fiddle showing what you got so far im happy to give you tips on how to make this work.

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by ivanoronee** [comment]
Thanks everyone. Your explanations have helped point me in the right direction. I am currently not working on the project where i am using bootstrap-table but will try out the suggestions when i switch back to it.

Sorry i violated the terms of use as per https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker

I will post directly to SO next time.

Cheers.

**Comment by djhvscf** [comment]
Thanks @ivanoronee
