### ISSUE TITLE
"hideColumn" ignores columns with a numerical data-field

### ISSUE THREAD

**Issue by nhnb** [wenzhixin/bootstrap-table#2014]
I have a table with is filled with a two dimensional array. Therefore it uses data-field="0", data-field="1" in the column definition.

`$table.bootstrapTable('hideColumn', 'name');` works for tables with a name, but ignores columns with an index. 

Please see [jsfiddle](https://jsfiddle.net/s7a2gmfh/1/). It should only display the third column.

**Comment by dabros** [comment]
**PR** made, move discussion there if needed: #2023

**Comment by wenzhixin** [comment]
Merged the PR, thanks for @dabros
