### ISSUE TITLE
Please update examples to 1.10.1

### ISSUE THREAD

**Issue by theo222** [wenzhixin/bootstrap-table#2015]
Examples are still using 1.10.0
http://issues.wenzhixin.net.cn/bootstrap-table/assets/bootstrap-table/src/bootstrap-table.js

Here with 1.10.1 the table looks different and the Icons under "Item Operate" are not visible.

Thank you.

**Comment by theo222** [comment]
I found out, that it works if I add a dummy field "operate" to the json for 1.10.1
In 1.10.0, this field was not necessary for showing "Item Operate" fields.
http://issues.wenzhixin.net.cn/bootstrap-table/
http://issues.wenzhixin.net.cn/examples/bootstrap_table/data

**Comment by wenzhixin** [comment]
Updated.
