### ISSUE TITLE
bootstrap-table通过json来加载复杂表头

### ISSUE THREAD

**Issue by chunfeng0060** [wenzhixin/bootstrap-table#2016]
bootstrap-table可以通过json来加载标头和数据。我想问一下，有没有通过json生成复杂标头（多级标头）的方式？

**Comment by wenzhixin** [comment]
有，你看这里的例子：http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by chunfeng0060** [comment]
Group Columns是使用rowspan, colspan 标签实现的，没有找到json实现。

**Comment by wenzhixin** [comment]
不知道你说的 json 是什么意思。

**Comment by chunfeng0060** [comment]
http://www.cnblogs.com/nangong/p/ccdfabb7ccedbfa580acc6eeef286a27.html，类似于例子1中的实现，在bootstrap-table有没有类似的实现方式？

**Comment by wenzhixin** [comment]
给的例子你看下 source

**Comment by chunfeng0060** [comment]
非常感谢！

**Comment by wenzhixin** [comment]
关掉这个 issue 了，假如还有问题再 reopen
