### ISSUE TITLE
Table Export - TypeError: c.$el.tableExport is not a function

### ISSUE THREAD

**Issue by chebrami** [wenzhixin/bootstrap-table#2017]
Hi I am receiving this error when I try to export any format:
TypeError: c.$el.tableExport is not a function

How can I fix this?

`<script type="text/javascript" src="/assets/javascripts/bootstrap-table.js"></script> <script type="text/javascript" src="/assets/javascripts/locales/bootstrap-table-fr-BE.js"></script> <script type="text/javascript" src="/assets/javascripts/bootstrap-table-export.js"></script> <script type="text/javascript" src="/assets/javascripts/tableExport.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/jquery.base64.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/html2canvas.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/jspdf.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/jspdf.plugin.autotable.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/jspdf.plugin.addhtml.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/jspdf.plugin.addimage.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/FileSaver.min.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/split_text_to_size.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/jspdf.plugin.from_html.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/base64.js"></script> <script type="text/javascript" src="/assets/javascripts/jspdf/sprintf.js"></script>`

**Comment by diegotejadav** [comment]
Hi, I'm having the same problem, Did you fix it @chebrami?
