### ISSUE TITLE
bootstrapTable("load", data);

### ISSUE THREAD

**Issue by jieme** [wenzhixin/bootstrap-table#2018]
![image](https://cloud.githubusercontent.com/assets/5328234/13249658/75a4161c-da60-11e5-8aa1-d18e7377e055.png)
服务端返回的数据后拼接字段后非服务端的记录不显示。
   $table.bootstrapTable({
            pagination: true,
            sidePagination: "server",
            pageSize: 20,
            pageList: [10, 20, 50, 100],
            minimumCountColumns: 2,
            onPageChange: function (number, size) {
                parme.pageIndex = number;
                parme.pageSize = size;
                loaddata(parme);
            },
            columns: [{
                field: 'serverCode',
                title: '员工编号',
                align: 'center'
            }, {
                field: 'serverName',
                title: '员工姓名',
                align: 'center'
            }, {
                field: 'goodName',
                title: '商品1',
                align: 'center'
            }, {
                field: 'saleTotal',
                title: '销售量',
                align: 'center',
                clickToSelect: false,
                formatter: statisticsSalesFormatter,
                events: statisticsSalsesEvents
            }, {
                field: 'backTotal',
                title: '退货量',
                align: 'center',
                clickToSelect: false,
                formatter: statisticsBackFormatter,
                events: statisticsBackEvents
            }, {
                field: 'changeTotal',
                title: '换货量',
                align: 'center',
                clickToSelect: false,
                formatter: statisticsExchangeFormatter,
                events: statisticsExchangeEvents
            }]
        });

**Comment by wenzhixin** [comment]
返回的数据是怎样的

**Comment by wenzhixin** [comment]
没有回复？
