### ISSUE TITLE
How to change formatLoadingMessage?

### ISSUE THREAD

**Issue by HCMUC** [wenzhixin/bootstrap-table#2019]
I want to change the "Loading, please wait..." to an animated circle (<img src...)
This is what I tried so far but it ain't working:
```
$('#table').bootstrapTable({
    formatLoadingMessage: function () {
        return '<img src="ajax-loader.gif" />';
    }
});
```

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/e3nk137y/4839/? if this is not working for you, please provide a fiddle

**Comment by mpperez3** [comment]
I reopen this issue, because formatLoadingMessage still not working when a locale it is included. Please check the next fiddle

https://jsfiddle.net/7bovud18/1/

Many thanks for your work!

**Comment by UtechtDustin** [comment]
@mpperez3 Thanks for the report, as this issue was no bug report but a question please open a new issue.
Also it would be great if you could use our [editor](https://live.bootstrap-table.com/) to provide an example.
I can reproduce the bug btw.
