### ISSUE TITLE
load data by click

### ISSUE THREAD

**Issue by antonyboom** [wenzhixin/bootstrap-table#2021]
In your example http://issues.wenzhixin.net.cn/bootstrap-table/#methods/load.html table has been already rendered, and everything works fine but what if i need that tables has been showed only after click on button load? I've tried to set it up but table every time loads together with page

**Comment by djhvscf** [comment]
provide a fiddle with your code, please @antonyboom

**Comment by antonyboom** [comment]
if to be honest i have no idea how to do that in fiddle
this is my html
```
 <button id="button" class="btn-primary btn" onclick="load();">Load Table</button>
   <table id="table"></table>
```
this my script
```
var $table = $('#table'),

    $table.bootstrapTable({
        data: load(),
        columns: [{
            field: 'STUDY NAME',
            title: 'STUDY NAME',
            sortable: true
        }, {
            field: 'SITE NAME',
            title: 'SITE NAME',
            sortable: true }
        ]
    });

function load(){
    $('#table').bootstrapTable("load", data="data/events.json");
}
```
and this is part of json
```
[
  {
    "STUDY NAME":"Bayer_16132",
    "SITE NAME":14001
  }
]
```

**Comment by djhvscf** [comment]
See this example that I created for you: http://jsfiddle.net/djhvscf/e3nk137y/4841/

**Comment by antonyboom** [comment]
cool, thanks a lot!!!!!

**Comment by djhvscf** [comment]
:+1:

**Comment by antonyboom** [comment]
I’m sorry for annoying, what if my data comes from url?


On Feb 23, 2016, at 16:12, Dennis Hernández <notifications@github.com<mailto:notifications@github.com>> wrote:


[:+1:]

**Comment by antonyboom** [comment]
just for note if somebody will need to get data by url with using button, use this code: 

```
 $("#button").click(function () {
        $table.bootstrapTable(
            'refresh', {
                url: 'yourUrl'
            });
    });
```
