### ISSUE TITLE
Large data sets crashing browser with dynamic columns

### ISSUE THREAD

**Issue by statespindle** [wenzhixin/bootstrap-table#2022]
Javascript:

// DATA contains data.columns (dynamic) and data.data (actual data to show)

`$('#report-data').bootstrapTable('destroy').bootstrapTable({
                columns: JSON.parse(data.columns)
              });

              $('#report-data').bootstrapTable('load', JSON.parse(data.data));`

data.columns:

`[[{field:"location_name", width:"200px", title:"Location", rowspan:3},
  {colspan:6, rowspan:1, width:"650px", title:"January 20, 2016"},
  {colspan:6, rowspan:1, width:"650px", title:"January 21, 2016"},
  {colspan:6, rowspan:1, width:"650px", title:"January 22, 2016"},
  {colspan:6, rowspan:1, width:"650px", title:"January 23, 2016"},
  {colspan:6, rowspan:1, width:"650px", title:"January 24, 2016"},
  {colspan:6, rowspan:1, width:"650px", title:"January 25, 2016"},
  {colspan:6, rowspan:1, width:"650px", title:"January 26, 2016"},
  {colspan:6, rowspan:1, width:"650px", title:"January 27, 2016"}],
 [{colspan:3, rowspan:1, title:"Web"},
  {colspan:3, rowspan:1, title:"Physical"},
  {colspan:3, rowspan:1, title:"Web"},
  {colspan:3, rowspan:1, title:"Physical"},
  {colspan:3, rowspan:1, title:"Web"},
  {colspan:3, rowspan:1, title:"Physical"},
  {colspan:3, rowspan:1, title:"Web"},
  {colspan:3, rowspan:1, title:"Physical"},
  {colspan:3, rowspan:1, title:"Web"},
  {colspan:3, rowspan:1, title:"Physical"},
  {colspan:3, rowspan:1, title:"Web"},
  {colspan:3, rowspan:1, title:"Physical"},
  {colspan:3, rowspan:1, title:"Web"},
  {colspan:3, rowspan:1, title:"Physical"},
  {colspan:3, rowspan:1, title:"Web"},
  {colspan:3, rowspan:1, title:"Physical"}],
 [{field:"dt_01_20_2016_w_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_20_2016_w_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_20_2016_w_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_20_2016_m_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_20_2016_m_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_20_2016_m_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_21_2016_w_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_21_2016_w_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_21_2016_w_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_21_2016_m_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_21_2016_m_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_21_2016_m_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_22_2016_w_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_22_2016_w_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_22_2016_w_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_22_2016_m_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_22_2016_m_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_22_2016_m_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_23_2016_w_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_23_2016_w_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_23_2016_w_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_23_2016_m_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_23_2016_m_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_23_2016_m_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_24_2016_w_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_24_2016_w_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_24_2016_w_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_24_2016_m_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_24_2016_m_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_24_2016_m_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_25_2016_w_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_25_2016_w_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_25_2016_w_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_25_2016_m_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_25_2016_m_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_25_2016_m_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_26_2016_w_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_26_2016_w_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_26_2016_w_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_26_2016_m_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_26_2016_m_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_26_2016_m_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_27_2016_w_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_27_2016_w_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_27_2016_w_r", formatter:"countFormatter", title:"Fines Count"},
  {field:"dt_01_27_2016_m_i", formatter:"countFormatter", title:"Check Ins"},
  {field:"dt_01_27_2016_m_v", formatter:"countFormatter", title:"Check Outs"},
  {field:"dt_01_27_2016_m_r", formatter:"countFormatter", title:"Fines Count"}]]`

data.data:

`[{location_name:"NickName",
  dt_01_20_2016_w_i:0,
  dt_01_20_2016_w_v:0,
  dt_01_20_2016_w_r:0,
  dt_01_20_2016_m_i:0,
  dt_01_20_2016_m_v:0,
  dt_01_20_2016_m_r:0,
  dt_01_21_2016_w_i:3,
  dt_01_21_2016_w_v:9,
  dt_01_21_2016_w_r:11,
  dt_01_21_2016_m_i:9,
  dt_01_21_2016_m_v:8,
  dt_01_21_2016_m_r:5,
  dt_01_22_2016_w_i:0,
  dt_01_22_2016_w_v:0,
  dt_01_22_2016_w_r:0,
  dt_01_22_2016_m_i:0,
  dt_01_22_2016_m_v:0,
  dt_01_22_2016_m_r:0,
  dt_01_23_2016_w_i:7,
  dt_01_23_2016_w_v:0,
  dt_01_23_2016_w_r:0,
  dt_01_23_2016_m_i:8,
  dt_01_23_2016_m_v:0,
  dt_01_23_2016_m_r:0,
  dt_01_24_2016_w_i:0,
  dt_01_24_2016_w_v:0,
  dt_01_24_2016_w_r:0,
  dt_01_24_2016_m_i:0,
  dt_01_24_2016_m_v:0,
  dt_01_24_2016_m_r:0,
  dt_01_25_2016_w_i:0,
  dt_01_25_2016_w_v:0,
  dt_01_25_2016_w_r:0,
  dt_01_25_2016_m_i:0,
  dt_01_25_2016_m_v:0,
  dt_01_25_2016_m_r:0,
  dt_01_26_2016_w_i:0,
  dt_01_26_2016_w_v:0,
  dt_01_26_2016_w_r:0,
  dt_01_26_2016_m_i:0,
  dt_01_26_2016_m_v:0,
  dt_01_26_2016_m_r:0,
  dt_01_27_2016_w_i:0,
  dt_01_27_2016_w_v:0,
  dt_01_27_2016_w_r:0,
  dt_01_27_2016_m_i:0,
  dt_01_27_2016_m_v:0,
  dt_01_27_2016_m_r:0},
 {location_name:"Nickname 2",
  dt_01_20_2016_w_i:0,
  dt_01_20_2016_w_v:0,
  dt_01_20_2016_w_r:0,
  dt_01_20_2016_m_i:0,
  dt_01_20_2016_m_v:0,
  dt_01_20_2016_m_r:0,
  dt_01_21_2016_w_i:5,
  dt_01_21_2016_w_v:6,
  dt_01_21_2016_w_r:7,
  dt_01_21_2016_m_i:6,
  dt_01_21_2016_m_v:7,
  dt_01_21_2016_m_r:5,
  dt_01_22_2016_w_i:0,
  dt_01_22_2016_w_v:0,
  dt_01_22_2016_w_r:0,
  dt_01_22_2016_m_i:0,
  dt_01_22_2016_m_v:0,
  dt_01_22_2016_m_r:0,
  dt_01_23_2016_w_i:0,
  dt_01_23_2016_w_v:0,
  dt_01_23_2016_w_r:0,
  dt_01_23_2016_m_i:0,
  dt_01_23_2016_m_v:0,
  dt_01_23_2016_m_r:0,
  dt_01_24_2016_w_i:0,
  dt_01_24_2016_w_v:0,
  dt_01_24_2016_w_r:0,
  dt_01_24_2016_m_i:0,
  dt_01_24_2016_m_v:0,
  dt_01_24_2016_m_r:0,
  dt_01_25_2016_w_i:0,
  dt_01_25_2016_w_v:0,
  dt_01_25_2016_w_r:0,
  dt_01_25_2016_m_i:0,
  dt_01_25_2016_m_v:0,
  dt_01_25_2016_m_r:0,
  dt_01_26_2016_w_i:0,
  dt_01_26_2016_w_v:0,
  dt_01_26_2016_w_r:0,
  dt_01_26_2016_m_i:0,
  dt_01_26_2016_m_v:0,
  dt_01_26_2016_m_r:0,
  dt_01_27_2016_w_i:0,
  dt_01_27_2016_w_v:0,
  dt_01_27_2016_w_r:0,
  dt_01_27_2016_m_i:0,
  dt_01_27_2016_m_v:0,
  dt_01_27_2016_m_r:0}]`

countFormatter:

`function countFormatter(value) {
    return (value) ? value : 0;
  }`

The above is crashing chrome when applied to the table using the latest version of bootstrap table.

**Comment by statespindle** [comment]
I should point out that smaller datasets work fine...

**Comment by djhvscf** [comment]
Let me try to test this issue.. I'm going back to you when I have something new @statespindle

**Comment by statespindle** [comment]
Thanks!

**Comment by wenzhixin** [comment]
So have you solved your problem @statespindle ?

**Comment by statespindle** [comment]
No.  I'm still having issues with this.  I'm able to reduce the amount of date by about 1 day and the grid loads fine, adding an extra day of data causes it to crash.

**Comment by wenzhixin** [comment]
can you help to provide a jsfiddle?

**Comment by djhvscf** [comment]
Did you see this: https://jsfiddle.net/djhvscf/p9d2r77o/3/?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
