### ISSUE TITLE
Filter rows by range?

### ISSUE THREAD

**Issue by luisapuyen** [wenzhixin/bootstrap-table#2026]
This is not an issue or problem, just a question (is there any specific forum for this?):

My question is: Is there any implemented way to filter by ranges? i.e. more than, less than, more than or equal to...

As far as I know, the only similar way would be to use the "filterBy" method, but I think it only works with string matches, not number ranges.

**Comment by luisapuyen** [comment]
I've figured it out in this thread: [#553](https://github.com/wenzhixin/bootstrap-table/issues/553).

**Comment by djhvscf** [comment]
Did you see this example: http://jsfiddle.net/e3nk137y/1010/ @luisapuyen

**Comment by luisapuyen** [comment]
@djhvscf Yes, it's the example provided in the link I posted. It was very helpful :)

**Comment by wenzhixin** [comment]
Great, close this issue.
Added the example to #1765
