### ISSUE TITLE
Angular 2 integration/porting

### ISSUE THREAD

**Issue by zxxz** [wenzhixin/bootstrap-table#2028]
Hello guys,
Do you know if bootstrap-table can be integrated/ported to Angular 2?
Could you please give me some pointers?
Thanks!

**Comment by djhvscf** [comment]
This plugin works fine with angular js 1 but I think we have not tested with angular js 2... let me try!

**Comment by wenzhixin** [comment]
Any pull request is welcome @zxxz.
