### ISSUE TITLE
How to refresh pagination when update table?

### ISSUE THREAD

**Issue by tanobi92** [wenzhixin/bootstrap-table#2029]
I have a table and a button. I click button => bind data from table. The table change data but pagination not change.
Exg: 
click 1: table have 10 rows; Showing 1 to 10 of 10 rows;
click2: table have 21 rows; Showing 1 to 10 of 10 rows. Pagination not change. (True: Showing 1 to 10 of 21 rows);
How to refresh pagination?
Help me! Please! Thank you very much.
It same search data, table change data => pagination change.
 http://issues.wenzhixin.net.cn/bootstrap-table/integrate/angular/#

**Comment by djhvscf** [comment]
Please provide a fiddle in order to know how you are loading data to the table.. @tanobi92

**Comment by tanobi92** [comment]
HI @djhvscf! Thank you for rep!
My fiddle:
https://jsfiddle.net/TaNoBi/50ht0czq/5/
Help me, please!

**Comment by wenzhixin** [comment]
@tanobi92 I think in your case you can use `append` method to add your rows instead of using jQuery `html`: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/append.html

**Comment by tanobi92** [comment]
Hi @wenzhixin ! My case isn't append, data may increase, reduce.
I updated my fiddle:
https://jsfiddle.net/TaNoBi/50ht0czq/9/

**Comment by wenzhixin** [comment]
https://jsfiddle.net/wenyi/50ht0czq/10/

**Comment by tanobi92** [comment]
@wenzhixin thank you! I completed. :)
