### ISSUE TITLE
在小屏笔记本上当数据的列数太多时显示不全，又没有横向滚动条。

### ISSUE THREAD

**Issue by linjiaju8** [wenzhixin/bootstrap-table#2030]
如题，我找了下文档，没看到想关配置，请问能固定表格宽度，然后超过就显示横向滚动条吗？

**Comment by wenzhixin** [comment]
默认是有开启的，例如：http://issues.wenzhixin.net.cn/bootstrap-table/#options/large-columns.html，会不会你设置了 table 的布局

**Comment by linjiaju8** [comment]
谢谢回答，我看下啥原因。
