### ISSUE TITLE
Invisible the scroll-x

### ISSUE THREAD

**Issue by mingyuanzhu** [wenzhixin/bootstrap-table#2031]
When I use the extension function to fix some columns, if there are too many column, the scroll-x will be block by these fix column. Should let the position of scroll-x is begin from the unfix the columns?
Thanks

**Comment by mingyuanzhu** [comment]
Ok, I think the question is that the height of fixed column is equal to the table height. But the height should reduce the scroll-x height. I have a try to reduce the height 14px, the scroll-x display.
I have created a pull request for the repo bootstrap-table-fixed-columns. Please have a look.
Thanks

**Comment by djhvscf** [comment]
Provide an example, please @mingyuanzhu

**Comment by mingyuanzhu** [comment]
[https://jsfiddle.net/mingyuan/80pt2a7y/](url) This is use the bootstrap-table-fixed-columns.js
[https://jsfiddle.net/mingyuan/mLpydokp/](url) This is after my updated. 
Please have a look at scroll-x. If you use the mac book, I think you need a mouse to find them difference easily, thanks @djhvscf

**Comment by wenzhixin** [comment]
Merged in https://github.com/wenzhixin/bootstrap-table-fixed-columns/pull/13
