### ISSUE TITLE
Filter Control - Manual select options

### ISSUE THREAD

**Issue by fenichelar** [wenzhixin/bootstrap-table#2035]
Is it possible to specify the options in the dropdown if the filter type is select? I use server side pagination so I want to manually set them.

**Comment by djhvscf** [comment]
Right now it is not possible but it can be a good feature.. Any **PR** is welcome :+1: @fenichelar

**Comment by djhvscf** [comment]
Please this attachment
[filtercontrol-customselectoptions.zip](https://github.com/wenzhixin/bootstrap-table/files/149195/filtercontrol-customselectoptions.zip)

_Attached because in a fiddle it does not work as expected_
