### ISSUE TITLE
How To mergeCells footer

### ISSUE THREAD

**Issue by a40234023** [wenzhixin/bootstrap-table#2039]
Ask how to mergeCells footer??
THX

**Comment by Falseee** [comment]
I think it is not supported yet...

**Comment by djhvscf** [comment]
@a40234023 this feature is not supported yet but remember any **PR** is welcome

**Comment by a40234023** [comment]
Thank you

**Comment by dabros** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

**Comment by wenzhixin** [comment]
Duplicate of #2276, close this one.
