### ISSUE TITLE
When CardView is set to true the footer is shown

### ISSUE THREAD

**Issue by djhvscf** [wenzhixin/bootstrap-table#2041]
The footer should be hidden when the card view is set to true:

Example with the issue:
http://jsfiddle.net/djhvscf/9ymkp3tm/6/
Change the view of the table, when we have the card view we can see that the footer is shown.

Example with the issue fixed:
http://jsfiddle.net/djhvscf/9ymkp3tm/7/

**Comment by Falseee** [comment]
Your example worked for me, why didn´t you create a PR ?

**Comment by djhvscf** [comment]
The PR is created a days ago.. See this: https://github.com/wenzhixin/bootstrap-table/pull/2027
