### ISSUE TITLE
Column option "cardVisible" has no effect.

### ISSUE THREAD

**Issue by theo222** [wenzhixin/bootstrap-table#2045]
Setting cardVisible=false has no effect in versions 1.10.0 and 1.10.1 
```
...
{
  title: 'Item ID',
  field: 'Id',
  visible:false,
  cardVisible:false, //<---
  footerFormatter: totalTextFormatter
},
...
```

Please see also #1368 for a fiddle.

Thank you.

**Comment by wenzhixin** [comment]
Which fiddle?

**Comment by theo222** [comment]
Here is a fiddle:
http://jsfiddle.net/theo222/9gptp5kd/3/
It is my first, so please be gentle. ;-)

Shouldn't the "id" field be invisible in this case?

**Comment by wenzhixin** [comment]
Fixed in the develop branch: http://jsfiddle.net/wenyi/9gptp5kd/4/
You can use the develop src or wait for the next release.

**Comment by wenzhixin** [comment]
#1993

**Comment by theo222** [comment]
Thank you!
