### ISSUE TITLE
responseHandler more values

### ISSUE THREAD

**Issue by Fruchtgummi** [wenzhixin/bootstrap-table#2046]
Hi

i have a json from serverside 

hash: "cac3fa8b1720397f3802cab8ad2dc24c44ab8031"
result: {total: "2910",…}
   rows: [{f1: "1", id: "11270", number: null,  one: null, FPLZ: null,   …},…]
   total: "2910"

i set with the responseHandler the result to table and this works create. But i would like use the hash-key from the jsonarray, for example with the data-formatter then I know no possibility.

**Comment by dabros** [comment]
@Fruchtgummi - store it elsewhere

Declare some other variable and assign the hash or other values to that, should get refreshed each time table is refreshed too if set inside `responseHandler`

You can even attach to the `window` object, just ensure no conflict with existing keys (so some unique top level like `window.myTableData = { 'hash': data.hash, 'whatever': data.whatever }`

**Comment by Fruchtgummi** [comment]
Ok it's fine... It would be nice if commit the own Date automatically
from response to data-formatter and not only Rows & Index. But its running for my needs.

Thanx

**Comment by dabros** [comment]
@Fruchtgummi - if you wanted to make it a feature request, please be clearer in how you expect/want this to work and it will be read and considered.

Otherwise please close this issue if solved, optionally sharing some of your code to help others who find this due to similar needs.

thanks

**Comment by Fruchtgummi** [comment]
I set the important values undiluted in my result, in every index on my row-object.     

Example

```
function responseHandler(res) {


    if (res.hash && isset(res.result) && res.result['rows']) {
        for(i=0;i<res.result['rows'].length;i++) {
            res.result['rows'][i].hash=res.hash;
        } 
    }

    if (res.error) {
        setGlobalMessage('warning', res.error['message']);
    }

    if (!res.result) {
        var result = new Array();
        result['total']=0;
        result['rows']="";
        return result;
    }

    return res.result;

}
```
If more elegant, of course! ;)

**Comment by dabros** [comment]
@Fruchtgummi - still not clear what you wanting exactly

What your doing there is taking that extra param `res.hash` that is passed back from data source and storing it in each row.

If that answers your need, then ok, but why not just have a top level variable (or even something attached to another high level object like `window`, ie`window.hash = res.hash`) that you store it to for when its used.

You have no explanation why `hash` even exists or what your using it for.

If its for data-column then yes thats one way to answer it, though very odd if same value

If its for data-formatter, then store it somewhere else so your not bloating your data. Wouldnt make much difference with a single param, but if it never changes between rows then store it on higher level.

**Comment by Fruchtgummi** [comment]
@dabros 

The hash-value come from server and was generated for each link on frontend. My json-object from serversite has always a same structure which and is automatically generated. The Bootstrap-Table always takes `total & rows`, but all my other functions have a different structure.

But it's ok! I want each have value in a line, because when create a element with the data-formatter, can get the value on the current line.

A toplevel variable is not an option, because the can be different for each line value.
