### ISSUE TITLE
Integrate with vuejs

### ISSUE THREAD

**Issue by frankdors** [wenzhixin/bootstrap-table#2047]
VueJS trending
http://blog.evanyou.me/2015/12/20/vuejs-2015-in-review/

**Comment by wenzhixin** [comment]
any pull request is welcome!

**Comment by frankdors** [comment]
https://github.com/ratiw/vue-table

**Comment by wenzhixin** [comment]
I am trying on implementing bootstrap-table to Vue.js component: https://github.com/wenzhixin/vue-bootstrap-table. @frankdors

**Comment by wenzhixin** [comment]
Close this issue. Thanks for your advice, vue.js is awesome!

**Comment by amravazzi** [comment]
Support for Vue 2? :D

**Comment by djhvscf** [comment]
@amravazzi not at this moment
