### ISSUE TITLE
Two thead 

### ISSUE THREAD

**Issue by yokas** [wenzhixin/bootstrap-table#2048]
http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html

in class fixed-table-header, there is a table with only thead, and in class fixed-table-body, there is another table with same thead and tbody.

And the border between head and body is bigger.

**Comment by wenzhixin** [comment]
Because we need to achieve the fixed header feature, but the same `thead` is hidden.
What problem do you have? You can remove the `height` option.

**Comment by dabros** [comment]
@yokas - so?

Like wenzhixin said, what is the actual problem you have???

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
