### ISSUE TITLE
Feature Interest

### ISSUE THREAD

**Issue by hopglascock** [wenzhixin/bootstrap-table#2052]
Hi, I was wondering if there was any interest for a few features I developed for a client a little while back.
Specifically I wrote a extension which adds toolbar buttons for:

1. Hiding / Showing all Columns (columns to be shown / hidden configurable by the user and saved as a cookie)
2. Copying the contents of selected rows to the clipboard omitting hidden columns
3. Copying the contents of selected rows to the clipboard including hidden columns

If you guys like I am happy to do a little clean up and submit a pull request or throw it up on paste bin / jsfiddle.

**Comment by hopglascock** [comment]
Thinking about it these features don't really belong in the same extension... i'm happy to structure it however you'd like anyways...

**Comment by wenzhixin** [comment]
please provide a fiddle to show your extension.

**Comment by djhvscf** [comment]
Really this sounds great! Lets show us a fiddle!!

**Comment by hopglascock** [comment]
http://jsfiddle.net/Hopglascock/t2wkynrL/13/

just to note copy should work with the latest desktop browsers except safari

**Comment by djhvscf** [comment]
Good!! please create an extension with that :+1:

**Comment by wenzhixin** [comment]
Merged
