### ISSUE TITLE
Version of 'bootstrap-table-cookie.js'

### ISSUE THREAD

**Issue by Taewa** [wenzhixin/bootstrap-table#2053]
Hello.

Just little thing,

I saw [this issue #1531](https://github.com/wenzhixin/bootstrap-table/pull/1531)

I believe I had downloaded `bootstrap-table-cookie.js` file before above issue, when I compare with new `bootstrap-table-cookie.js`file, the verstion is still same as `v1.2.0`

Because it is minor issue?

Thank you.

**Comment by djhvscf** [comment]
Yes, we need to implement the best way to change the version
