### ISSUE TITLE
sort by date

### ISSUE THREAD

**Issue by joaorueda** [wenzhixin/bootstrap-table#2054]
Hi ! anybody can help me with this 

https://jsfiddle.net/joaorueda/kne8fcub/

I have a json returning data and mount the table , a column type date and I need put it ordered but date  field does not order correctly

I try set custom sorter but no success.

has any chance of type the columns with params type integer, string, date to order correctly 

thanks.
João Rueda

**Comment by wenzhixin** [comment]
Here is the custom sort example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-sort.html

**Comment by joaorueda** [comment]
I try put this lines 
      
      sorter: 'starsSorter',
      sortName:"date",
      sortOrder:"desc" 

into column date but Traduzir not changed the order 

https://jsfiddle.net/joaorueda/wz0nbfpz/

**Comment by wenzhixin** [comment]
You use in a wrong way, it is: `sorter: starsSorter`.

**Comment by erick485** [comment]
Como debería ser el sorter para hora y fecha a la vez
