### ISSUE TITLE
Sorting rows not working

### ISSUE THREAD

**Issue by luismartin** [wenzhixin/bootstrap-table#2057]
I'm having problems with arbitrary bs tables in my application in which their sort feature is not working. I've reduced their code to its minimal expression, removing extensions and other scripts, and it's still not working! 

No clue about where the problem is. Could you please help? 

This is the jsFiddle: [https://jsfiddle.net/luismartin/3f6xbaap/](https://jsfiddle.net/luismartin/3f6xbaap/)

I've tried with several jQuery versions with same result.

**Comment by djhvscf** [comment]
See this: https://jsfiddle.net/djhvscf/3f6xbaap/4/ 
Fixed on: #2050 

@luismartin

**Comment by luismartin** [comment]
Fantastic! Thank you!

**Comment by luismartin** [comment]
mmmm, I've just updated, but it seems that it has messed up the formatter option. All the action buttons in my lists have just disappeared. Nothing is displayed, not even the function name. 

I've tried to reflect it here: 

[https://jsfiddle.net/luismartin/3f6xbaap/5/](https://jsfiddle.net/luismartin/3f6xbaap/5/)

and it won't perform any format but the function name.

**Comment by luismartin** [comment]
Anything on this regard?

**Comment by huaishu** [comment]
sortname 无法获取 ,if (this.options.sortName === $this.data('field')) {导致

**Comment by luisapuyen** [comment]
@huaishu: could you please explain in English and in more detail? Thank you.

**Comment by luisapuyen** [comment]
@djhvscf: Hey, this issue is still unresolved. The fix you provided clashed with other BootstrapTable features like the cell formatter. Seems that @huaishu found where the error is located.

**Comment by huaishu** [comment]
BootstrapTable.prototype.onSort = function (event) {
        var $this = event.type === "keypress" ? $(event.currentTarget) : $(event.currentTarget).parent(),
            $this_ = this.$header.find('th').eq($this.index());

        this.$header.add(this.$header_).find('span.order').remove();

        if (this.options.sortName === $this.data('field')) {
            this.options.sortOrder = this.options.sortOrder === 'asc' ? 'desc' : 'asc';
        } else {
            this.options.sortName = $this.data('field');
            this.options.sortOrder = $this.data('order') === 'asc' ? 'desc' : 'asc';
        }

else code is problem，i think  “  this.options.sortName = $this.data('sortName');”

**Comment by huaishu** [comment]
i am china ，english is little。

**Comment by huaishu** [comment]
BootstrapTable.prototype.getCaret  maybe some problem

**Comment by luismartin** [comment]
@djhvscf @wenzhixin I think I found the ordering error was due to using a class called "bootstrap-table" to identify my BootstrapTables. Since BootstrapTable itself creates a div container with a "bootstrap-table" class too, then it will never reach the that.onSort(event) line in this chunk of code (line 770):

      ```
         this.$container.off('click', '.th-inner').on('click', '.th-inner', function (event) {
            var target = $(this);
            // here is where the code gets tangled up with my "bootstrap-table" class and the one self-created by BootstrapTable
            if (target.closest('.bootstrap-table')[0] !== that.$container[0])
                return false; 

            if (that.options.sortable && target.parent().data().sortable) {
                that.onSort(event);
            }
        });
       ```

I will change my class, but would be great to prevent class collisions.
