### ISSUE TITLE
InsertRow after reorder row doesnt work

### ISSUE THREAD

**Issue by francescomeloni** [wenzhixin/bootstrap-table#2058]
I use 
$table.bootstrapTable('insertRow', {index: riga.length, row: record});
where riga.length is a index number and record is the array to add 
it works always fine but when i change one or more rows position and try to insert a new row  nothing happened, no console error.

**Comment by djhvscf** [comment]
Provide an example, please @francescomeloni

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!

**Comment by Jingkun-Hu** [comment]
@francescomeloni  Have you soved the bug? i met the same one
