### ISSUE TITLE
selectPage doesn't set active class on pagination list item

### ISSUE THREAD

**Issue by martinburch** [wenzhixin/bootstrap-table#2060]
Here is a JSFiddle example:
http://jsfiddle.net/e3nk137y/5100/
The example listens for the `sort` event and then uses `selectPage` show the first page, so users don't end up in the middle of a re-sorted table. However, `selectPage` doesn't set the usual style to indicate page 1 has been selected. Expected behavior would be that
```
<li class="page-number"><a href="javascript:void(0)">1</a></li>
```
becomes
```
<li class="page-number active"><a href="javascript:void(0)">1</a></li>
```
with a call to `$('#data-table').bootstrapTable('selectPage', '1');`

**Comment by djhvscf** [comment]
You must past a **number** to the `selectPage` method instead of a **string**

See this: http://jsfiddle.net/djhvscf/e3nk137y/5147/

**Comment by martinburch** [comment]
@djhvscf thanks for your help
