### ISSUE TITLE
where are loading.jpg and clear.png??They are used in bootstrap-editable.css file.

### ISSUE THREAD

**Issue by chen1218chen** [wenzhixin/bootstrap-table#2065]
I can`t  find two images loading.jpg and clear.png , they are used in the bootstrap-editable.css file.

**Comment by dabros** [comment]
@chen1218chen - there is no bootstrap-editable.css file in src or dist folders of this plugin, meaning they maybe from an example or other plugin

Share exactly where you got this file from (link and description) the lines it tries to load this from too

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
