### ISSUE TITLE
Feature request: include field name in td (like data-index in tr)

### ISSUE THREAD

**Issue by duduklein** [wenzhixin/bootstrap-table#2067]
Hi, 

I've been using bootstrap table for a while and my content may be changed by the user. This would to work perfectly well until I included the search functionality. 
When search is used, the whole table is re-rendered based on the search terms and if search box is emptied, the whole table is also re-rendered.

I realized that changes made by users "disappeared" after every re-render of the table. I guess the problem is that I'm not updating the cells' contents with updateCell method (I was only updating what was already displayed.

I usually have a handler on a select or a button that is in a cell, so I should be able easily to call updateCell. The issue is that it received 3 parameters: the row's index, the column's field name and the new content. I have the content with $td.html() and the row's index doing $td.parent("tr").data("index"), but I can not find an easy way to get the field's name which seems to be only available at the thead level.

Would it be possible to have the field name (the one we pass to updateCell method) directly in the td, like data-field?

Thanks in advance

**Comment by dabros** [comment]
@duduklein - its quite easy to have it updating information to server and ect. and i cant quite see what your core issue is.

See the editable extension and please make a fiddle of your issue, if you are using server-side pagination just look at making your data source a url (or ip address) it can connect to, or at least include excerpt from that data source and related server side code in codeblock when you post fiddle.

http://bootstrap-table.wenzhixin.net.cn/extensions/
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by duduklein** [comment]
I'm not reporting a bug, but a feature request.

I did not know this extension, it may help. The extension uses the x-editable plugin which apparently has its development frozen: https://github.com/vitalets/x-editable

**Comment by dabros** [comment]
@duduklein - right now it seems to have no real issues, and to plug it in is increadibly simple, so i suggest using examples and if needed searching for closed issues here to see fiddles using it.

**Comment by djhvscf** [comment]
@duduklein if you are listening the click.cell event you should receive a parameter called `field `where you can know which was the cell clicked.

if you're listening `onEditableSave (field, row, oldValue, $el)`, `onEditableShown: (field, row, $el, editable)`

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
