### ISSUE TITLE
Add text before table

### ISSUE THREAD

**Issue by chebrami** [wenzhixin/bootstrap-table#2068]
Hello i would like to add some text before table and a title in my PDF but i don't know how i can make it.
There is my code

```
$('#table_div').bootstrapTable({
        exportOptions : {
            fileName : 'liste_deduction_patro',
            worksheetName : 'deductions_patro',
            jspdf : {
                orientation : 'l',
                autotable: {styles: {cellPadding: 2,
                                     rowHeight: 12,
                                     fontSize: 8,
                                     fillColor: 255,       
                                     textColor: 50,         
                                     fontStyle: 'normal',   
                                     overflow: 'ellipsize', 
                                     halign: 'left',        
                                     valign: 'middle'      
                                    },
                            headerStyles: {fillColor: [52, 73, 94],
                                           textColor: 255,
                                           fontStyle: 'bold',
                                           halign: 'center'
                                          },
                            alternateRowStyles: {fillColor: 245
                                                },
                                                createdHeaderCell: function (cell, data) {},
                            tableExport: {onAfterAutotable: null,
                                          onBeforeAutotable:null,
                                          onTable: null
                                         }
                           }
            },
            ignoreColumn : [0]
        }
    });
```

**Comment by dabros** [comment]
@chebrami - never used the export plugin myself, but looking at doco shows a few possible options

For example, most promising lead i can see is the extension telling you to look at the extensions it was built upon, notably [jsPDF-AutoTable](https://github.com/simonbengtsson/jsPDF-AutoTable)

http://bootstrap-table.wenzhixin.net.cn/extensions/
https://github.com/hhurz/tableExport.jquery.plugin#options
https://github.com/simonbengtsson/jsPDF-AutoTable#options

You can see those are the options used in the `autotable` subindex of `jspdf` and that there are options allowing you to use functions to define content before and after the table.

There is also the `tableName` and `displayTableName` options on the [tableExport.jquery.plugin](https://github.com/hhurz/tableExport.jquery.plugin#options) level.

Options exist, play with them then if you have tried and still cant figure it out please provide fiddle and state exactly what you tried yourself already: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
