### ISSUE TITLE
How to know  Request URL   

### ISSUE THREAD

**Issue by xerardoo** [wenzhixin/bootstrap-table#2069]
Hi, I set the table with my URL API,  but I need know the Request URL after apply query params..

URL:  `/api/customers`

After pagination or search: 
URL:  `/api/customers?search=foo&offset=10&limit=10`  I need get this URL.

**Comment by thornomad** [comment]
Can you provide an example? 

Did you set `queryParamsType: 'limit'` ?  That will use a RESTful style of query parameters.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
