### ISSUE TITLE
Changing the color of a specific row

### ISSUE THREAD

**Issue by ffkammer** [wenzhixin/bootstrap-table#2076]
Hi,

I'm using the `data-formatter` to enable/disable a checkbox based on a specific condition. I'd like to change the color of the font of all rows that have the checkbox disabled.

My `data-formatter` is:

`
    function statusFormatter(value, row, index) {
      if (value>0) {
        return {
          disabled: true
        }
      }
      return;
    }
`

Are there a way to do this?

Thanks

**Comment by dabros** [comment]
`rowStyle`?

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

Depends on what your checkbox is tied to, if its actual data then use that and post fiddle if doesnt update when your data does (which it should if your actually saving the change, use editable extension if issues with that, calling ajax to save actual change in `UpdateComplete` or similar callback, the row/table should be refreshed and pickup on `rowStyle`, but only worry if `rowStyle` doesnt update on value change in your code).

If your talking about the default selection checkbox, then see how http://issues.wenzhixin.net.cn/bootstrap-table/ atm already does that and just tweak the css rule it applies to get desired effect.

You could also always just add handler to all checkboxs via some selector like `$('table .my-checkbox').on('change',function(){})` (or whatever the event is actually called) and then something like `$(this).parent('tr').removeClass('blah')` or `addClass('blah')`.

Many options out there, not too hard to implement even if `rowStyle` proves not sufficient in itself.

**Comment by djhvscf** [comment]
See this example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/563.html

**Comment by SebastianPeredoM** [comment]
When you change the page and go back to the page where the row is, it goes back to white.
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/563.html

**Comment by dabros** [comment]
@SebastianPeredoM - that example is for selected row style, which ofcourse doesnt remember given the settings on that example

There are other posts here and good content above about persisting styles which can applied to variously config'd tables (with different data sources, pagination, ect)
