### ISSUE TITLE
Get table headings from JSON Data

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#2081]
How can i create table headings dynamically in Jquery instead hard coding in HTML. Because my JSON end point is dynamic and can result in any number of fields. For example the below JSON has 3 fields may change per client file. 

**Case 1 - 3 Fields**
```
{
  "total": 2,
  "rows": [
    {
      "id": 0,
      "name": "Item 0",
      "price": "$0"
    },
    {
      "id": 1,
      "name": "Item 1",
      "price": "$1"
    }
]
}
```
**Case 2 - 5 Fields**
```
{
  "total": 2,
  "rows": [
    {
      "id": 0,
      "name": "Item 0",
      "price": "$0"
      "name1": "Item 0",
      "price1": "$0"
    },
    {
      "id": 1,
      "name": "Item 1",
      "price": "$1"
      "name1": "Item 1",
      "price1": "$1"
    }
]
}
```

So if i hard-code the HTML like this will not show all fields to 1 case but not to 2nd one as the 2nd JSON has 5 fields
```
<table id="table">
    <thead>
        <tr>
            <th data-field="id">Item ID</th>
            <th data-field="name">Item Name</th>
            <th data-field="price">Item Price</th>
        </tr>
    </thead>
</table>
```

**Comment by dabros** [comment]
Is there a straight forward way to dynamically create columns after receiving remote data. #2013 

http://stackoverflow.com/questions/35611223/automatically-create-header-from-json-file-bootsrtap-table/35689906#35689906

The SO is maybe a little more detailed, but both have great info on this.

In short, it will take a little js knowledge on your part, but not really that much as the few steps you need to take are very simple and have comparable examples around the place.

**Comment by vickyrathee** [comment]
Okay thanks for pointing out, I end up creating this [http://jsfiddle.net/4r6g4cfu/192/](http://jsfiddle.net/4r6g4cfu/192/) with help of SO and more documentation.

**Comment by dabros** [comment]
@vickyrathee - Looks great :+1: 

Other variations exist but just making duplicate request (for a single record) on doc ready works well in this case.

Other thoughts include using `$('#table').bootstrapTable('refreshOptions',{'columns':columns})` (so that you can init table anytime and update) but they all around same core concept.

Nice work :)

**Comment by marcandrews** [comment]
So I am currently using `$('#table').bootstrapTable('refreshOptions', { 'columns': columns })` in my `responseHandler` to render my columns dynamically; however, I noticed that `refreshOptions` calls my AJAX again. Is this intended, or is there anyway to not have `refreshOptions` call my AJAX again?

**Comment by wenzhixin** [comment]
@marcandrews Please use data instead of url option.

**Comment by marcandrews** [comment]
@wenzhixin thanks for your response.

I am also using server-side pagination and searching. If I use `data`, wouldn't I have to build my own pagination and searching implementation to modify the `data` variable?

To me, the `refresh` method should call AJAX again, while `refreshOptions` should only refresh the options used to draw the table, no?

**Comment by wenzhixin** [comment]
Maybe you can provide some code you are using @marcandrews .
