### ISSUE TITLE
Input text going back to the beggining of filter-control

### ISSUE THREAD

**Issue by calvaradocl** [wenzhixin/bootstrap-table#2082]
Hello,

When using bootstrap-table with the filter-control plugin, and you write something on the column filter input text, after the filter is applied the cursor goes back to the beggining of the input element.

This issue happens when using Internet Explorer 11 11.0.9600.17801 (does not happen in chrome).

**Comment by calvaradocl** [comment]
Is there any workaround for this issue? The component works great but this issue is giving us a hard time.

**Comment by djhvscf** [comment]
See #2106
