### ISSUE TITLE
Help with buttons

### ISSUE THREAD

**Issue by netopvh** [wenzhixin/bootstrap-table#2084]
How can I add editing and deleting buttons on the line every record so I can make the edit or delete the selected record.

It is the first time I use the bootstrap -table and do not know how to do ... if someone can help me I thank you very much !

Ex: 

```php
<table id="table">
..
<tr>
<th>ID</th>
<th>Name</th>
<th colspan="2">Action</th>
</tr>
....
<tr>
<td>1</td>
<td>Master</td>
<td><a href="">Edit</a></td>
<td><a href="">Delete</a></td>
</tr>
</table>
```

**Comment by djhvscf** [comment]
See this example: http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by netopvh** [comment]
sorry friend , but I was in the documentation and could not understand the operation of the bootstrap -table , if someone can give me an example here I would appreciate

**Comment by djhvscf** [comment]
OK. . But in the ítem operate you can see the accions buttons
