### ISSUE TITLE
Footer rows for totals or custom operations

### ISSUE THREAD

**Issue by luisapuyen** [wenzhixin/bootstrap-table#2086]
Is it possible to implement footer rows which perform some kind of operation on all the elements of a column like an addition?

**Comment by dabros** [comment]
`footerFormatter` http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/639.html

**Comment by luisapuyen** [comment]
@dabros Thank you! I didn't notice it's in the documentation. Also I didn't know the reduce function (I would have used a bulky function instead), so your example comes in very handy :+1:

**Comment by luisapuyen** [comment]
By the way: Would it be possible to create a two lines footer, where the second line had merged cells in this fashion:

For instance, starting from 4 fixed columns with their corresponding sums in the footer, some way to add a second footer line in which columns 1 and 2 are merged in a cell that contains their total sum, and just the same for columns 3 and 4. 

Is this possible in some way?

**Comment by dabros** [comment]
@luisapuyen - not a bad question, though it does seem very much outside-use-case so maybe not as is...

**PR** are always welcome if you want to look into the code and think up some ideas on maybe how to do it, we always happy to help proof or collab on code if you have an honest swing at it and it wont break anything else or overcomplicate too much

**Comment by luisapuyen** [comment]
@dabros Thanks a lot for your tips! I will try to code it by myself, although most modern ninja-techniques in javascript like I've seen in the Bootstrap Table code are beyond my expertise yet. I will try anyway.
