### ISSUE TITLE
bug提交

### ISSUE THREAD

**Issue by shihuaidezhu** [wenzhixin/bootstrap-table#2094]
在initTable中设置了this.fromHtml = true,但在后续代码中未重置，使带有checkbox的tablle load的时候产生错乱

**Comment by wenzhixin** [comment]
能否提供下 jsfiddle，例如 #1765

**Comment by djhvscf** [comment]
@wenzhixin not sure what this issue says but I think the fromHTML should not be used in our code.. it is causing many bugs... see this one: http://jsfiddle.net/zafvbuwq/1/

**Comment by wenzhixin** [comment]
I think this problem has been solved now.
