### ISSUE TITLE
data-filter-control="datepicker" not firing

### ISSUE THREAD

**Issue by kiwina** [wenzhixin/bootstrap-table#2095]
hi i noticed that with server side data selecting the date is not fired. Only after clicking it it does prope filtering.
so untested using 
`$(e.currentTarget).keyup();`
use
`that.onColumnSearch(e);`

**Comment by wenzhixin** [comment]
Can you provide a fiddle to show your problem?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
