### ISSUE TITLE
checkbox 样式问题

### ISSUE THREAD

**Issue by qilifan** [wenzhixin/bootstrap-table#2096]
checkbox 在火狐浏览器下样式会丢失，变为没有样式的checkbox.如下图：
![checkbox_firefox](https://cloud.githubusercontent.com/assets/4359902/13940664/81be0bd6-f01a-11e5-99f6-8ba6f33eb31d.png)

而在chrome浏览器中，样式没有问题,如下图：

![checkbox_chrome](https://cloud.githubusercontent.com/assets/4359902/13940670/883fa5f0-f01a-11e5-8218-fca72c812e7e.png)

**Comment by wenzhixin** [comment]
用的是默认的 checkbox，不同浏览器的样式不一样，跟插件无关
