### ISSUE TITLE
Some problem when search data include "&"

### ISSUE THREAD

**Issue by RJHsiao** [wenzhixin/bootstrap-table#2098]
Hi all,

I have some problem about search function.
I make a example to explain this problem easily: https://jsfiddle.net/RJ_Hsiao/dsn41bt0/
You can see that there are some data include "`&`" character in the "Division" column, like "F&SS", "S&O".
In this case, I cannot get any result when I use "`F&SS`" into search input, I have to use "`F&amp;SS`" to get the result I want.

Is there any way to let me pre-process search text?

**Comment by dabros** [comment]
ref: Is there any accent neutralization plugin for the search feature? #1399 
- maybe strict search solve this too?

**Comment by RJHsiao** [comment]
@dabros 
No, problem isn't be solved even strict search is set to true.

**Comment by djhvscf** [comment]
See this **PR** @RJHsiao #2106

**Comment by RJHsiao** [comment]
Hi @djhvscf 

You got really good job!
Thank you! :smile:
