### ISSUE TITLE
Extend bootstrap-table-cookie with 2nd script

### ISSUE THREAD

**Issue by WilliTheSmith** [wenzhixin/bootstrap-table#2099]
Hi,
I wrote an extension to filter my data. I want to save the state of my extension with bootstrap-table-cookie.
Is there a possibility to access the get and setCookie functions from another script?

I don't want to edit the bootstrap-table-cookie source. I want to write a 2nd script called bootstrap-table-cookie-ext.js

**Comment by djhvscf** [comment]
See this: #2106 
Example: http://jsfiddle.net/djhvscf/e3nk137y/5415/
