### ISSUE TITLE
列参数visible的问题

### ISSUE THREAD

**Issue by Dre-amer** [wenzhixin/bootstrap-table#2100]
使用visible隐藏了列，但是编辑的时候隐藏的列（数据）会占用其它行显示出来，想问一下这个是因为什么

**Comment by wenzhixin** [comment]
能否提供下 jsFiddle，例如 #1765

**Comment by Dre-amer** [comment]
谢谢，已经解决了，是我给visible属性值加双引号造成的错误（使用失误）
Bad Example：
    visible : " false "
