### ISSUE TITLE
Check box styling

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#2103]
I'm using built-in check box field in a table, is there a way i can style the check box using [Magic check CSS](http://forsigner.com/magic-check/) 

```
<th data-field="state" data-checkbox="true"></th>
```
This is how the HTML looks like for styling and click on the link above to see the CSS.

```
 <input class="magic-checkbox" type="checkbox" name="layout" id="2" checked="checked">
            <label class="pull-right" for="2"></label>
```

**Comment by wenzhixin** [comment]
Please refer to this example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/383.html
