### ISSUE TITLE
Sort when table loaded

### ISSUE THREAD

**Issue by hanspoo** [wenzhixin/bootstrap-table#2104]
Hi,

Is it possible to make an automatic multisort (or sort) when the table is first loaded with data.

Thanks
Hans

**Comment by wenzhixin** [comment]
Try `sortName` and `sortOrder` options.

**Comment by deepfriedbrain** [comment]
`sortName` and `sortOrder` would work for single sort, but how do we get it to work for multiple sort on table load?

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/multiple-sort.html
