### ISSUE TITLE
Accessing features from a json file for data-side-pagination="server"

### ISSUE THREAD

**Issue by nyarachm** [wenzhixin/bootstrap-table#2105]
Hi,

I am testing out the table features on my localhost and successfully used the search, sort, pagination and export when using data-side-pagination="client" (and configuring the json file as shown in the documentation).

without server-side (works): https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data1.json
with server-side (NOT working): https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data2.json

When I change to server-side, I successfully get the data to output in the table but all the features do not work (search, sort, pagination and export). Export outputs the entire table.

I have had a look here http://jsfiddle.net/4r6g4cfu/3/light/ and when I replicate this example and use the data-url (http://mikepenz.com/jsfiddle/) provided it works. But my http://localhost/testtable/scripts/json/test.json doesnt.

NOTE: http://localhost/testtable/scripts/json/test.json is identical to http://mikepenz.com/jsfiddle. I copy/pasted

**Comment by dabros** [comment]
@nyarachm - you do know what "server-side" means?

#1980

"client-side" means js code doing most the grunt work, "server-side" is where you point to a server side SCRIPT (NOT a raw data file) that handles the param you send along with it and returns prepared results.

There is nothing bootstrap-table has to do with that process, except in the name and values of param sent, and you can even configure those to whatever you want.

Look through issues and ect for server side code or just google to find similar scripts in whatever language and database/datastore your using then change param to match standard names.

**Comment by dabros** [comment]
@nyarachm - I like that your looking at other issues, but you need to make better use of the search feature here and remember to remove "is:open" filter.

And please dont spam same question in barely related posts when it does fit far better here in its own thread (or in the duplicate thread i linked to above)

**Comment by nyarachm** [comment]
@dabros Hi, thanks for the quick advice! Sorry about asking all over. I have had a look at https://github.com/wenzhixin/bootstrap-table/issues/1980 as well as the other links previously and have successfully managed to fix the pagination issue. This is my first time using json as before I used to use ajax. 

However this did not fix the search, sort, and export functions. This issue only happens when I get data from server. I am still looking around the 'issues' area (and your links) for a possible solution and will report on my success or failure. Thanks

**Comment by nyarachm** [comment]
Positive Update! Massive thanks to @jaydeepgiri in https://github.com/wenzhixin/bootstrap-table/issues/617. I finally got the sort feature working. 

The 5 golden variables (the author of the documentation should really add these in):
$_GET['sort'] -->> gives you the column name of the table to sort
$_GET['order'] -->> specifies the order i.e, ASC or DESC 
$_GET['search']-->> gives the text to search into database
$_GET['limit']-->> specifies number of rows
$_GET['offset']-->> starting position / offset in table

For those in need of a guide make sure your php file that contains the sql queries makes use of these variables (depending on the situation i.e apply $_GET['sort'] and $_GET['order'] in your query  in the sql order: ORDER BY $sort $order) and run the query when the situation arises:

if (isset($_GET['sort'])) {
//sql sort query here
} else {
//return default table
}

...now for the search feature...

**Comment by dabros** [comment]
@nyarachm - those are in the documentation, very clearly and in multiple locations as appropriate

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

They are also in the data requests that I told you to hit F12 and view.

Glad that you got it working, but if you dont understand the steps someone tells you to find something then say that, so you can improve your ability to improve yourself

Web inspector/developer tools are critical to this kind of work, so make sure you get familiar with using them too.

**Comment by sampeka** [comment]
I'm also hitting the same problem with the export function not working with `data-side-pagination="server"`. It always exports the contents of the current rows in-view, rather than those that are selected. Do you know if there is there a way to resolve this or is it a known limitation of the export plugin?

Happy to provide a jsfiddle or open a new issue if needed.

**Comment by dabros** [comment]
@sampeka - please try not to post in other topics on same issue without linking

ref #2220

**Comment by sampeka** [comment]
@dabros, apologies - my bad,  I opened the new issue for a clearer title and a more focused subject, but if you'd rather track the issue here I'll close it.

**Comment by dabros** [comment]
@sampeka - its better you opened new issue, and i like the added clarity, just remember to backlink to related topics (from either side), especially if you posted same question : )

**Comment by wenzhixin** [comment]
Fixed in #3830
