### ISSUE TITLE
How to use editable Select2 (tags mode)?

### ISSUE THREAD

**Issue by adele2011** [wenzhixin/bootstrap-table#2109]
I want to use editable Select2 (tags mode) as shown in 
https://vitalets.github.io/x-editable/demo-bs3.html#

I set type to 'select2' and 'tags' to true, but it doesn't work. 

```
editable: {
    type: 'select2',
    source: [
              {id: 'gb', text: 'Great Britain'},
              {id: 'us', text: 'United States'},
              {id: 'ru', text: 'Russia'}
    ],
    select2: {
        tags: true
     }
 }
```
What's the right way to do it?  Thanks!

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/e3nk137y/6515/
