### ISSUE TITLE
why, the buttons are not the same

### ISSUE THREAD

**Issue by muyuer** [wenzhixin/bootstrap-table#2112]
![1](https://cloud.githubusercontent.com/assets/18065848/14039849/00277db2-f29c-11e5-8ff0-3f8bbfaac40f.png)

<script type="text/javascript" src="${contextPath}/static/js/jquery-1.12.0.min.js"></script>
	
	

<link rel="stylesheet" href="${contextPath}/static/bootstrap-3.3.5-dist/css/bootstrap.min.css">
<script type="text/javascript" src="${contextPath}/static/bootstrap-3.3.5-dist/js/bootstrap.min.js"></script>
	

<link rel="stylesheet" href="${contextPath}/static/bootstrap_table/css/bootstrap-table.min.css">
<script type="text/javascript" src="${contextPath}/static/bootstrap_table/js/bootstrap-table.min.js"></script>
<script type="text/javascript" src="${contextPath}/static/bootstrap_table/locale/bootstrap-table-zh-CN.js"></script>`

**Comment by djhvscf** [comment]
Please provide an example in order to see this issue, @muyuer

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
