### ISSUE TITLE
请问这个控件支持IE10吗

### ISSUE THREAD

**Issue by quzefeng** [wenzhixin/bootstrap-table#2113]
你好，请问这个控件支持IE10吗，我用谷歌浏览器测试都正常，但是换成IE10发现无法正常的显示。 @

**Comment by quzefeng** [comment]
另外，我增加了导出链接高级查找，后来发现多了1个导出按钮。我不知道如何发图片，因此只是文字描述。

**Comment by quzefeng** [comment]
还有就是我用IE11测试竟然是可以的。合适奇怪。

**Comment by wenzhixin** [comment]
支持的

**Comment by wenzhixin** [comment]
有问题的话提供下 fiddle

**Comment by quzefeng** [comment]
你好，我测试的IE版本是RTM版本，我对比了我的两个WIN8.1系统，他们的IE版本号都是10，但是子版本号不同，我把有问题的IP升级了一个IE补丁后就可以了，非常感谢您的回答。

**Comment by wenzhixin** [comment]
好的
