### ISSUE TITLE
Setting the option dataField not working when server side pagination is not used

### ISSUE THREAD

**Issue by pnm** [wenzhixin/bootstrap-table#2114]
Looks like the value set in option *_dataField *_ is ignored when the pagination is NOT _server _. In this scenario the json data (with dataField key configured) is not picked up and table shows no data.
eg dataField = 'datakey'

```
{
  "datakey": [
    {
      "param1": "value11",
      "param2": "value12"
    },
    {
      "param1": "value21",
      "param2": "value22"
    }
  ]
}
```

A quick look at the code indicates `BootstrapTable.prototype.load` function dataField  param if the pagination is NOT _server_ and sets data = data.data . This causes data not to be displayed in table.
The documentation indicates only the default value as 'rows' and has no mention of using it only in server side pagination.

Not sure if this is by design or an issue. 
Have done a quick fix/hack on my fork and moved on. 
- Set the dataField to '' by default
- If pagination is server and dataField is '' -> set it to 'rows' -> like before (BootstrapTable.prototype.updatePagination)
- In the load function do a check for dataField  and use the configured value if != ''

```
BootstrapTable.prototype.load = function (data) {
        var fixedScroll = false;

        // #431: support pagination
        if (this.options.sidePagination === 'server') {
            this.options.totalRows = data.total;
            fixedScroll = data.fixedScroll;
            data = data[this.options.dataField];
        } else if (!$.isArray(data)) { // support fixedScroll

            fixedScroll = data.fixedScroll;
            //data = data.data;
            if (this.options.dataField != '') //check if the dataField has beeb set default as row
            data = data[this.options.dataField];
            else 
            data = data.data;
        }

```

Can submit PR if required or the team can do a better fix.

Cheers !

**Comment by wenzhixin** [comment]
PR is welcome.

**Comment by wenzhixin** [comment]
This issue has been fixed in the latest version.
