### ISSUE TITLE
Export And Editable Plugin can't work together. Possible bug?

### ISSUE THREAD

**Issue by airtonjr** [wenzhixin/bootstrap-table#2116]
Hello All, 

When I am using the "Export" and "Editable" plugin in the same table it give me error when I select one item from the select:

```
<select class="form-control">                   
                     <option value="">Export Basic</option>
                     <option value="all">Export All</option>
                     <option value="selected">Export Selected</option>
                </select>
```

The error you can see below:

![errorcapture](https://cloud.githubusercontent.com/assets/7409463/14030632/9299a70e-f1d6-11e5-8abe-18f330b44eed.PNG)

Why this is happening? And every time when I switch the option it add: **">** to the column.

Could be a bug?

**Comment by djhvscf** [comment]
Same issue here #2120
