### ISSUE TITLE
Updating the server-side json to output filtered data

### ISSUE THREAD

**Issue by nyarachm** [wenzhixin/bootstrap-table#2117]
HI, Is it possible to update the server-side JSON file using AJAX in bootstrap-table? 

`data-url="scripts/users.php"`

I am using a PHP file to echo the output of the sql queries to the table.
First Name | Last Name | Category | Group

This works well, but I want to add 4 select tags each to filter a column. I have replicated the server-side JSON within users.php but this time it will echo the filtered rows to the JSON.

Can this be done? How can I switch to the filtered JSON?

NOTE: all this logic is within users.php (aside from the AJAX of course).

```

if (!empty($_POST['first_name'])) {
//code to create and return filtered JSON
} 

else if (!empty($_POST['last_name'])) {
//code to create and return filtered JSON
} 

else if (!empty($_POST['category'])) {
//code to create and return filtered JSON
} 

else if (!empty($_POST['group'])) {
//code to create and return filtered JSON
} 

else {
//code to create and return unfiltered JSON
/*THIS ALWAYS EXECUTES ONLOAD, BUT **I WANT IT TO GIVE WAY FOR THE FILTERED JSON  AND ONLY REACTIVATE ONLOAD OR IF ALL FILTERS ARE REMOVED***/
}


```

**Comment by dabros** [comment]
@nyarachm - you should really move this post to SO as its no longer a bug or feature request for bootstrap table itself

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker

But after you close this, and before you post there, you should search for "edit json file php" or similar.

Plugging that straight into google got a ton of useful results for me, most seem to be leaning towards loading json file into php array or simliar object, then adding new entry in that object, then saving to file.

But im sure there are also scripts/libraries out there that do most of this behinds the scenes for you, in case you interested in that approach, though it really doesnt feel needed unless that also exposes decent search logic/handlers too.
