### ISSUE TITLE
Multi sort Boot strap table

### ISSUE THREAD

**Issue by Prabhu-A** [wenzhixin/bootstrap-table#2119]
Hi,
My requirement is to do convert single column sort to multi sort in my boot strap table. But when I implement  the code, it is not working. Please find the sample code below.

var team = {
    actionUrl: '',
    detailUrl: '',
    tableTeam: $('#table-team-details'),
    loadTeamRecords: function () {
        this.tableTeam.bootstrapTable({
            method: 'get',
            url: this.actionUrl,
            cache: false,
            striped: false,
            pagination: false,
            sortable: true,
            //sortName: "OverallTeamCompletePercent",
            //sortOrder: "desc",
			showMultiSort:true,
			sortPriority: '[{"sortName": "OverallTeamCompletePercent","sortOrder":"desc"}]',
            toggle: 'table',
            showRefresh: false,
            search: false,
            lastSortedColumnName: 'OverallTeamCompletePercent',
            columns: [{
                field: 'TeamName',
                title: 'Team Name',
                sortable: true,
                //width:'30%'
                order: 'asc'
            },
            {
                field: 'LeaderName',
                title: 'Leader Name',
                sortable: true,
                //width: '30%'
                order: 'asc'
            },
            {
                field: 'CompletedTotal',
                title: 'Completed / Total',
                sortable: true,
                align: 'center',
                halign:'center',
                //width: '20%'
                order: 'asc',
				sorter: this.CompletedTotalSorter
            },
.......................

Please let me know what i should do to get multi sort on page load.

Thanks,
Prabhu

**Comment by djhvscf** [comment]
Provide an example please where we can see the issue

**Comment by dabros** [comment]
@Prabhu-A https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by Prabhu-A** [comment]
Hi,

Please find the files attached and the respective screen shot. I want to sort Percent completed  first and then by Team name on page load. When I implement the code for multi sort,  I am getting something like below.

Single column sort is working fine.

OrganizationReport.chtml has got tag for table with id  “table-team-details “.  The code for loading the table contains in team.js

[cid:image001.png@01D189D3.03F026B0]

Please do the needful.

Thanks,
Prabhu.

**Comment by djhvscf** [comment]
We can't see your attachments

**Comment by dabros** [comment]
@Prabhu-A - your email reply does not show us attachments, all I can see is referance that there was an image in message, but no method to view that.

Even if there was, we need a fiddle or similar, so please see the steps in the link i provided as examples/baselines are provided there too.

**Comment by Prabhu-A** [comment]
Please find the attachement.

Thanks.




[OrganizationReport.txt](https://github.com/wenzhixin/bootstrap-table/files/195133/OrganizationReport.txt)
[team.txt](https://github.com/wenzhixin/bootstrap-table/files/195134/team.txt)

**Comment by dabros** [comment]
@Prabhu-A - we cant run those as we dont have same environment, same urls, language or anything ect.

That doesnt suffice in place of a fiddle, especially for a case like this when it is very little work for you to take one of the example fiddles and tweak it to resemble yours

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
