### ISSUE TITLE
Add sortSide property to set 'server'

### ISSUE THREAD

**Issue by betonetotbo** [wenzhixin/bootstrap-table#212]
Please add sortSide options property, to "disable" the client-side sort.

In my case I want to add extra fields to sort, before request the server for reload the data, on the title column click.

My patch:

    BootstrapTable.prototype.initSort = function () {
        if (this.options.sortSide === 'server') {
            return;
        }
        ........
    }

**Comment by wenzhixin** [comment]
In current version, when the pagination is 'server' need to handle sort in Server.
