### ISSUE TITLE
nested tables 

### ISSUE THREAD

**Issue by antonyboom** [wenzhixin/bootstrap-table#2121]
I have multi level json file. The first level I'm rendering on page thru bootstrap table library, by click on row, user can see children objects. Is it possible to load children level in new table instead of parent table?

this is my [plunker](https://plnkr.co/edit/MCyxfOM1ctuDVZllkw04?p=preview)

**Comment by dabros** [comment]
@antonyboom - please make sure you always have a look through the examples, as there are plenty of great examples of functionality there. 

Right now the main example for this creates subtables dynamically, but it shouldnt be a stretch to take out that generation code and use your own data, just place the init code for your subtable in place of the examples subtable generator.

http://bootstrap-table.wenzhixin.net.cn/documentation/
http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html

They also often have complimenting descriptions and variations in issues or SO posts, just ensure you remove the 'is:open' filter when searching github issues.

Here is example search just using "subtable" keywork, and should include fiddles if stumbling on implementing this yourself.

https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue+subtable

**Comment by antonyboom** [comment]
Thanks for help, this answer is very useful for me, cause I even couldn't find any examples, but my point is how to open new table instead current, not subtable inside table row? Is it possible?

**Comment by djhvscf** [comment]
I am not sure what you mean. I am going to need some more information.

**Comment by dabros** [comment]
@antonyboom - you can attach to a click event for the row or even just a specific cell, or even use a formatter to include link in cell content that you add event to using jquery, or buttons in a button column.

If you want to create a 'new table' on a click, and not expand to a subtable, nothing to do with bootstrapTable itself except adding event handler (plenty of examples of that around, just search) and creating new table (exact same script you would have run in `OnExpandRow` or similar if it was nested).

You want to change current table, exact same thing just look at `refreshOptions` or dropping and remaking entirely.

See examples and doco, main link already shared above.

**Comment by antonyboom** [comment]
@dabros thank you so much for your dip answer. Now I see pretty much how to do what I need

**Comment by djhvscf** [comment]
@antonyboom can we close this issue?

**Comment by antonyboom** [comment]
yes, thanks a lot for help

**Comment by djhvscf** [comment]
Great!

**Comment by antonyboom** [comment]
I'm sorry guys, I still play with tables and can understand how to open draw subtables and get an access to inner element. With your examples everything works fine, cause it just randomly generates table, but how to do that this real data? 
[plunker](https://plnkr.co/edit/MCyxfOM1ctuDVZllkw04?p=preview)

**Comment by dabros** [comment]
@antonyboom - your plunker does NOT do subtables like you say, its just a copy paste of generic `detailView` example..???

http://jsfiddle.net/myvykf24/1/

There is a fiddle doing what you want, which was in one of the topics in the search i linked you to in the very first post.

See in `buildTable` where it creates random data?

Remove that code and instead pass whatever settings to the bootstraptable init there to create your subtable, with the `data` being a nested array.

Here is it done up for you: http://jsfiddle.net/dabros/vuLj1bcb/

**Comment by antonyboom** [comment]
@dabros  the problem was I couldn't understand how to generate this subtables and couldn't understand where I have to provide info about header, now I get it and fixed my [plunker](https://plnkr.co/edit/MCyxfOM1ctuDVZllkw04?p=preview). Thank you, Daniel!

**Comment by sunsande** [comment]
Thank you very much @dabros ! Your example (or similar) should be included in the official documentation. The official documentation does not have an example how to create a subtable based on children array data from the data source json.
