### ISSUE TITLE
求bootstrap-table 的可离线运行的demo

### ISSUE THREAD

**Issue by willkiy** [wenzhixin/bootstrap-table#2124]
你好楼主，今天刚发现了你的bootstrap-table,但example的代码下下来，本地不能直接演示，查了一下原因，是部分js和css以及data文件的路径不对，或者缺少部分js，本来不想麻烦你的，但想给别人演示的话，需要添加和修改不少东西，请问你那能提供一份完整的可以离线演示的Demo吗？不盛感激

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table-examples#download-from-zip

**Comment by wangjia2016** [comment]
很多js、css访问不了，
