### ISSUE TITLE
export to excel file too many rows cause browser crash

### ISSUE THREAD

**Issue by gy0624ww** [wenzhixin/bootstrap-table#2127]
when i export a table data with 30000+rows,  to export into a excel. then chrome crashed
is there any better method to solve the problem?
thanks ~
@wenzhixin

**Comment by gy0624ww** [comment]
@wenzhixin

**Comment by djhvscf** [comment]
Can you provide an example, please?

**Comment by dabros** [comment]
Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Example fiddles can be found there too, you can use simple `for(var i = 0; i < 9999999; i++)` type iterator to fill out rows and see if you can replicate issue.

**Comment by conorot** [comment]
I have noticed this too on as few as 1700 rows. It only seems to be a problem with exportType 'excel' - not a problem with CSV, JSON or XML. In my case, it doesn't crash the browser completely any more, just seems to timeout and the File Save interface never pops up. No console errors

**Comment by wenzhixin** [comment]
@hhurz

**Comment by hhurz** [comment]
@gy0624ww: Are you sure that chrome crashed or did it bring up a request dialog like this:
![chrome](https://cloud.githubusercontent.com/assets/4164372/14326328/b94c1092-fc2d-11e5-9193-24e63357c48a.png)
It tells you that a javascript is busy and asks if you want to wait to finish it. In my test case (30000 rows x 27 cols) that dialog came up 3 times after clicking the "Wait" button. But finally chrome saved the xls file after about 70 seconds successfully. The file size was over 125 mb! 
I know that doesn't help you. Actually I'm aware about that problem, but have not a quick solution for it. All in all perhaps it isn't a good idea to export such large tables on client site...

@conorot: I think the problem you have is not the same like gy0624ww's. Probably you did not include Filesaver.js into your sources or this plugin couldn't be found. Filesaver.js is needed to save an (large) export file using a Blob.

**Comment by conorot** [comment]
Ah yeah - I don't have the filesaver.js so that'd sort me out. Thanks

**Comment by capecape** [comment]
I've got a similar issue. I don't have a browser crash (chrome), but, the file doesn't download, instead, a file named "download - Failed - network Error" is what I have. But this only happen in Chrome, with Firefox it works. There isn't any error in console. 
@conorot , @hhurz What do you mean with a fileSaver.js?
Regards.

**Comment by maddy25** [comment]
I have filesaver js still it is crashing for large number of rows, when I am trying to export all.

**Comment by djhvscf** [comment]
https://github.com/wenzhixin/bootstrap-table/issues/3209

**Comment by XiaoPengProsper** [comment]
The following proved that exporting excel in Chrome didn't work.
https://jsfiddle.net/e3nk137y/20814/
Can you show us a example about export excel using **fileSaver.js**?
Regards

**Comment by XiaoPengProsper** [comment]
Exporting to Excel is too slow to wait when data is too large.
Is there anyway to export all data with out Rendering DOM?

**Comment by hhurz** [comment]
Try this option: ```exportHiddenCells: true``` See also this [issue](https://github.com/hhurz/tableExport.jquery.plugin/issues/195)

The tableexport plugin requires that the table to export exists in DOM. 
If the table is hidden you can export it by setting the html data attribute data-tableexport-display:
```<table style="display:none;" data-tableexport-display="always">...</table> -> A hidden table will be exported```

**Comment by jimgit** [comment]
Just a suggestion,   for large tables ,  do the export on the server side?
