### ISSUE TITLE
Filter for empty cells

### ISSUE THREAD

**Issue by TheCultist** [wenzhixin/bootstrap-table#2128]
Hello,
I am using bootstrap-table with the Filter Control extension for a project I'm working on. The necessity arose to filter the contents of a column for all the cells that contain a null value. Am I mistaken in assuming that it's not a supported feature as of now? 

It doesn't appear to be but I prefer to be sure before I start fiddling with the code.

Thanks a lot!

**Comment by djhvscf** [comment]
Exactly, this feature is not supported by the filter control

**Comment by djhvscf** [comment]
But, any **PR** is welcome
