### ISSUE TITLE
Supply json array to table

### ISSUE THREAD

**Issue by clovernave** [wenzhixin/bootstrap-table#2129]
how do you use the json array the data into the table. It doesn't seem to work in this fiddle?
http://jsfiddle.net/zafvbuwq/

**Comment by djhvscf** [comment]
I am not sure what you mean. I am going to need some more information. @clovernave

**Comment by clovernave** [comment]
sorry i meant this. I have edited it but it doesn't seem to show the data?
http://jsfiddle.net/bb8ryxLn/

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/bb8ryxLn/1/

**Comment by dabros** [comment]
ref: #2174
