### ISSUE TITLE
edit data in new rendered table comes from main table with getSelectedRow method

### ISSUE THREAD

**Issue by antonyboom** [wenzhixin/bootstrap-table#2130]
On my page, I'm rendering new table with data which I got by click on row of main table, is it possible to edit this data that main table data has been updated too?

Provide[ plunker example](https://plnkr.co/edit/MCyxfOM1ctuDVZllkw04?p=preview)

**Comment by djhvscf** [comment]
Can you explain a liittle bit more?? You mean when we update the first row, for example, you want to update the new table also? @antonyboom

**Comment by antonyboom** [comment]
@djhvscf so I want to add feature that user could edit field in new table on the bottom and this field will be automatically update in main table on the top.

**Comment by wenzhixin** [comment]
You can use `updateRow` method to do that @antonyboom

**Comment by antonyboom** [comment]
@wenzhixin could you show it my [plunker](https://plnkr.co/edit/MCyxfOM1ctuDVZllkw04?p=preview)?

**Comment by antonyboom** [comment]
@djhvscf @wenzhixin I've updated my **[plunker](https://plnkr.co/edit/K2zbz2mUhDRHIdJpDWIF?p=preview)**, I added input form for lower table how could I put this changes into the table?

**Comment by antonyboom** [comment]
I fix it, this [working plunk](https://plnkr.co/edit/hYKRWZPB6kUN9QFU4KFQ?p=preview)
The issue can be closed.
By the way, I think you can add it ti your extension pack. I believe this is comfortable feature
