### ISSUE TITLE
Pagination wraps around

### ISSUE THREAD

**Issue by martinburch** [wenzhixin/bootstrap-table#2134]
When on page 1, clicking the left arrow causes the pagination to jump to the last page.
When on the last page, clicking the right arrow causes the pagination to jump to the first page.

Can this feature be disabled with an option? I'm trapped on an infinite loop of pages!

**Comment by hurryzeng** [comment]
agree, is there an option to disabled the loop ?

**Comment by wenzhixin** [comment]
Fixed in #2414
