### ISSUE TITLE
has any effort been made to allow custom ordering of toolbar buttons?

### ISSUE THREAD

**Issue by 719media** [wenzhixin/bootstrap-table#2135]
has any effort been made to allow custom ordering of toolbar buttons?

i searched and did not see any. i can make pull request if desired but wanted to make sure that this hasn't been discussed/underway already.

thanks

**Comment by djhvscf** [comment]
This can be a good feature, so go ahead with your **PR**. @719media

**Comment by 719media** [comment]
OK see #2138

**Comment by UtechtDustin** [comment]
@719media Do you still want to help us with that ?
