### ISSUE TITLE
Reset sorting order

### ISSUE THREAD

**Issue by jonatanklosko** [wenzhixin/bootstrap-table#2141]
There's no option to provide the most natural behaviour. I mean the sort state should be reseted, so: user clicks first sort arrow that sorts let's say ascending, then clicks another arrow, and then the first one again; the user would expect that the sort order is ascending again. So only clicking two times on the same arrow sorts descensing in this case.
[That's code which I wrote to deal with this.](https://github.com/jonatanklosko/worldcubeassociation.org/blob/45cb3f0ab097b5e2f1fafcba0da4d9810038e608/WcaOnRails/app/assets/javascripts/application.js#L245-L256)

**Comment by djhvscf** [comment]
This solution looks good!! Lets open a new **PR**, please @jonatanklosko
