### ISSUE TITLE
Search while deleting selected Value

### ISSUE THREAD

**Issue by malik42** [wenzhixin/bootstrap-table#2142]
On the client side search query is refreshing challenge of selected values

can you help me ?

**Comment by djhvscf** [comment]
I am not sure what you mean. I am going to need some more information.

**Comment by malik42** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getAllSelections.html

In the example here
As I searched the selected values ​​are disappearing

**Comment by wenzhixin** [comment]
You can try the `maintainSelected` option.
