### ISSUE TITLE
Unable to Add Hyperlink to Bootstrap Table

### ISSUE THREAD

**Issue by senseitebbayo** [wenzhixin/bootstrap-table#2143]
I am nut entirely sure how to make BT display hyperlinks as content. I am using this data and this table structure. data.php prints out the json structure below.  The rest of the table displays properly but the <a> tag does not 
![capture](https://cloud.githubusercontent.com/assets/4208925/14217833/453b2f1e-f848-11e5-8df3-23946e98d159.JPG)

[
    {
        "id": 0,
        "name": "Item 0",
        "price": "$0",
        "column1": "C 10",
        "column2": "C 20",
        "column3": "C 30",
        "column4": "<a href=\'#\'> D</a>"
    }
]

        <table data-toggle="table" 
       	   data-search="true"
            data-url="data.php"
            data-show-export="true"
       	    data-show-refresh="true"
       	    data-show-toggle="true"
       	    data-show-columns="true">
    <thead>
        <tr>
            <th data-field="id">id</th>
            <th data-field="name">name</th>
            <th data-field="price">price</th>
            <th data-field="column1">column1</th>
            <th data-field="column2">column1</th>
            <th data-field="column3">column1</th>
            <th data-field="column4">column1</th>
        </tr>
    </thead>
    
</table>

Please any help is appreciated. I'm sure this is something very simple and obvious but I'm missing it!

**Comment by djhvscf** [comment]
See this example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/format.html

**Comment by senseitebbayo** [comment]
Wonderful! worked like a charm. Thank you. 

I have one more question though, can you send hidden values to accompany each row from the JSON source for example an ID from the database that populates the JSON? how do you access such in the table? lik

**Comment by wenzhixin** [comment]
You  can use `queryParams` option @senseitebbayo

**Comment by giacomomarchioro** [comment]
> See this example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/format.html

The link is broken.

**Comment by wenzhixin** [comment]
@giacomomarchioro   https://examples.bootstrap-table.com/index.html#column-options/formatter.html

**Comment by giacomomarchioro** [comment]
Thanks a lot! However I don't see any link in the example.

Il giorno mar 23 mar 2021 alle ore 09:28 文翼 ***@***.***> ha
scritto:

**Comment by djhvscf** [comment]
Just change the i element to a 'anchor' element

https://live.bootstrap-table.com/code/djhvscf/7003
