### ISSUE TITLE
Contributing Fix for Filter Control V1.0.0

### ISSUE THREAD

**Issue by jamesmikesell** [wenzhixin/bootstrap-table#2146]
I've made some changes/fixes to the bootstrap-table-filter-control.js v1.0.0 to:
1.) Populate select lists with all unique column values rather than just those on the first page(s) (if paging is enabled)
2.) Improved performance when creating select lists (large datasets took used to take several seconds)

My questions
1.) Are you interested in pulling these changes?
2.) Do they go against the wenzhixin/bootstrap-table repo (i didn't see a specific fork for the filter control)

Hope this is the right place to ask this question.  Also, bear with me, this will be my first contribution on github.

**Comment by djhvscf** [comment]
This is the right place where you can create the PR...so go a headset and create the PR

**Comment by jamesmikesell** [comment]
Created pull request #2147

**Comment by wenzhixin** [comment]
Merged
