### ISSUE TITLE
Group by - order of group

### ISSUE THREAD

**Issue by deepfriedbrain** [wenzhixin/bootstrap-table#2148]
I'm using the group-by-v2 extension. I've created a fiddle to demonstrate my issue:

http://jsfiddle.net/et9z85zv/3/

I want the order of groups to be decided based on the values of the Id field. In the example, I want 'groupC' to be the first group (which has rows with Id 1, 3 and 4), then 'groupB' and then 'groupA'. But by default, the order is being set by the alphabetical sorting of the group names. 

The default behavior doesn't work for me because the group names have some significance in my application and I need the groups to be in a particular order. Think of it like a calendar, where group names represent month names. Showing the months in alphabetical order April, August, December .. won't make any sense. I need a way to specify the order as January, February, March ..  

Is there a way I can specify the order of groups or have it pick the order based on the values of a particular field ('Id' field in my example)?

Thanks to the bootstrap-table team for creating a wonderful product.

**Comment by djhvscf** [comment]
This feature is not supported. Any **PR** is welcome.

**Comment by deepfriedbrain** [comment]
I'm able to make use of custom sort to get my groups to show up in the order that I want. But I noticed an issue with the group by v2 extension. My source data is in the order that I want to maintain.

1    groupA
2    groupA
3    groupB
4    groupB
5    groupB
6    groupC
7    groupC

After grouping, I want this:

groupA
-------------
1
2
groupB
-------------
3
4
5
groupC
-------------
6
7

But want I get is a random ordering:

groupA
-------------
2
1
groupB
-------------
5
3
4
groupC
-------------
6
7

I'll go through the code to see if I can figure out the problem myself (I'm still quite new to jQuery). If you can give some pointers that'll really help. Thanks.

**Comment by djhvscf** [comment]
@Knoxvillekm do you have any advice here?

**Comment by Knoxvillekm** [comment]
@deepfriedbrain show code
@djhvscf data-sortable="true" work fine with groupBy

**Comment by deepfriedbrain** [comment]
@Knoxvillekm

I have created a new fiddle to demonstrate the problem:

http://jsfiddle.net/et9z85zv/10/

If you scroll all the way down to groupP, you'll see the sorting problem. The order is 5.2, 5.3, 5.4, 4.2, and 5.1. The correct order should be 4.2, 5.1, 5.2, 5.3, and 5.4.

**Comment by deepfriedbrain** [comment]
The following piece of code causes the sorting problem:

    this.data.sort(function(a, b) {
        return a[that.options.groupByField].localeCompare(b[that.options.groupByField]);
    });

I had to change the logic to do a multi-field sort to get the order right. The final version is something on these lines, where sortName is my `id` field:

    this.data.sort(function(a, b) {
        if (a[that.options.groupByField] < b[that.options.groupByField]) return -1;
        if (a[that.options.groupByField] > b[that.options.groupByField]) return 1;
        if (a[that.options.sortName] < b[that.options.sortName]) return -1;
        if (a[that.options.sortName] > b[that.options.sortName]) return 1;
        return 0;
    });

Thanks.

**Comment by SvetOleg** [comment]
@deepfriedbrain 
Moreover if try to sort (toggle 'asc/desc') need to use something like this:
 this.options.data.sort(function(a, b) {
                    if (a[that.options.groupByField] < b[that.options.groupByField]) return -1;
                    if (a[that.options.groupByField] > b[that.options.groupByField]) return 1;
                    if (that.options.sortOrder === 'asc') {
                        if (a[that.options.sortName] < b[that.options.sortName]) return -1;
                        if (a[that.options.sortName] > b[that.options.sortName]) return 1;
                        return 0;
                    }
                    if (a[that.options.sortName] > b[that.options.sortName]) return -1;
                    if (a[that.options.sortName] < b[that.options.sortName]) return 1;
                    return 0;

                });

**Comment by gaspardip** [comment]
Now this is something you shouldn't really do, its kind of a hack, but for the sake of simplicity and saving time I solved this by prepending an incremental number to the groups name so the default sort works out of the box, and then using bootstrap 3/4 (`.hidden`, `.d-none`) built-in css classes to hide that number.

Example: http://jsfiddle.net/gaspardip/egu7oztw/
