### ISSUE TITLE
Need help with Multiple Sort extension

### ISSUE THREAD

**Issue by deepfriedbrain** [wenzhixin/bootstrap-table#2149]
I want the multiple sort to be applied on table load and not allow user to change it (it doesn't make sense for my use case). 
1. The multiple sort doesn't take effect when data-toggle is not set. I have to manually trigger the multiple sort after the page is loaded. How can I have the sorting applied on table load?
2. I need to set data-show-multi-sort="true" for multi-sort to work. But I don't want the sort button (that opens the modal dialog) to appear on my page. I just want to pre-define the sorting priority and not allow the user to change it. Is it possible to hide the sort button?

Please refer to this simple fiddle:

http://jsfiddle.net/et9z85zv/7/

I reduced the multiple sort priority to a single field to create the simplest test case. It behaves the same with multiple sort fields too.

Thanks for your awesome work!

**Comment by djhvscf** [comment]
This feature is not supported. Any **PR** is welcome
