### ISSUE TITLE
can't use checkbox and radio together

### ISSUE THREAD

**Issue by rjl493456442** [wenzhixin/bootstrap-table#2152]
when i put checkbox and radio  into separate column, i found i can't select multi-row via checkbox, which just act like a radio button, and when i click a checkbox to select the whole row, a radio will be select automatically.

**Comment by djhvscf** [comment]
Can you provide an example, please?

**Comment by rjl493456442** [comment]
<thead>
     <th data-field="mycheckbox" data-checkbox ="true"></th>
     <th data-field="myradio" data-radio ="true"></th>
 </thead>
 <tbody>                          
   <tr class = "clickable-row">
       <td></td>
       <td></td>
   </tr>
 </tbody>


That's my source code. And i found the checkbox just act like a radio, which means i can  select only one item in a table via clicking checkbox.
It there any error usage in source code? Hope get your help asap. Thanks a lot

**Comment by djhvscf** [comment]
@rjl493456442 ok, but we need a fiddle

**Comment by dabros** [comment]
@rjl493456442 Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
@rjl493456442 the plugin does not support to use `checkbox` and `radio` together. If you want to, please use only one and the other use `formatter` option.
