### ISSUE TITLE
Sort by custom data attribute 

### ISSUE THREAD

**Issue by moussa1** [wenzhixin/bootstrap-table#2153]
This is in regards to Issue #821 

Suppose I have my data stored in a JSON file. How could I set the data attribute on <td>? I tried my best to find an example but have no luck so far. Please advise. @wenzhixin 

I am generating my TR and TD with this, so I am having trouble adding data attributes to my TD.

$('#tableid').bootstrapTable({ 
                                data: ResultTable
                            })

**Comment by djhvscf** [comment]
Can you provide an example, please?

**Comment by dabros** [comment]
@moussa1  Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
@moussa1, because your data stored in a JSON file, I think it is easy to custom the sorting using `sorter` option: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-sort.html.

By we don't know what your data. So please provide a fiddle.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
