### ISSUE TITLE
Clicking links while using clickToSelect option

### ISSUE THREAD

**Issue by jonatanklosko** [wenzhixin/bootstrap-table#2154]
At the moment when we enable the clickToSelect option for checkboxes and have some links in our table, clicking them causes that a row is selected. It's a little bit confusing if a user for example middle-click on a link to open it in a new tab and the row gets selected. [Here's my workaround.] (https://github.com/jonatanklosko/worldcubeassociation.org/blob/sortable-registrations/WcaOnRails/app/assets/javascripts/application.js#L268-L271)

**Comment by wenzhixin** [comment]
https://jsfiddle.net/wenyi/20rxmcxt/1/

**Comment by jfly** [comment]
Why is this issue closed? The example you gave doesn't actually solve the problem, right? You're just turning off clickToSelect on the entire column, which is like throwing the baby out with the bathwater.

**Comment by wenzhixin** [comment]
@jfly  you can use the workaround @jonatanklosko provide:
```
  // Prevent bootstrap-table from selecting a row when a link is clicked
  $('table[data-toggle="table"] td a').on('click', function(e) {
    e.stopPropagation();
  });
```

**Comment by jonatanklosko** [comment]
@wenzhixin @djhvscf eventually, we experienced an issue with this workaround. It works fine for a normal link, but turns out problematic when you want to add some event handlers to it. For example, if you'd like to show an alert once the link gets clicked, the workaround breaks it by stopping propagation of the event. A simple and reasonable solution would involve extending this condition https://github.com/wenzhixin/bootstrap-table/blob/21ae6acc49fe0229597fa33793cb09e4753fbd2a/src/bootstrap-table.js#L1869-L1875
to check if the event target is neither link nor button. This way a checkbox gets selected when the corresponding row is clicked, unless the clicked element is a link/button. Thoughts?

**Comment by jfly** [comment]
Ping @wenzhixin. Any update here? We'd love to send a PR that makes bootstrap table ignore clicks on links and buttons.
