### ISSUE TITLE
Can i add a new button not to custom toolbar but fixed bootstrap-table toolbar ?

### ISSUE THREAD

**Issue by vingorius** [wenzhixin/bootstrap-table#2156]
For Design Integrity, I want to add new Button ("+" Button, for 'New Row') to current bootstrap-table. 
Of course, I can do it with jquery. But is there more clear way to do it?

**Comment by djhvscf** [comment]
Right now we just can add buttons using the data-toolbar option. See this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

If this is not working for you please give us more information about your case

**Comment by vingorius** [comment]
Thanks @djhvscf , your prompt reply. Using toolbar option, I must re-define all your default button on fly. for example i want to have button group "search", "refresh", "column selection" etc. and i want to add "add row" button also. and i want all this buttons into one button group(top right side of table).  How can i do that?

**Comment by dabros** [comment]
@vingorius - you dont need to redefine all standard buttons if using custom toolbar, look closely at the source for that example (click 'see source in github' in top right) and you'll see it adds any extra html from `#toolbar`

There are complimenting options like `toolbarAlign`, `buttonsAlign`, ect. and you can add wrappers with custom css to help align it close to those other buttons.

Give that a try, and if still issues make a fiddle with your progress so far (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by vingorius** [comment]
Thanks @dabros , toolbarAlign option works !!! but it can not be btn-group and vertical alignment is little bit low(1px). But it' ok, Anyway that's great.

**Comment by dabros** [comment]
@vingorius - :+1: 

But do look at wrappers (so extra div or similar layer) and some custom css (inline or via '#toolbar .btn-group') to fix any quirks

**Comment by Taewa** [comment]
It worked with using `toolbarAlign` option and some css modification. 
But if a custom button needs to be placed between built-in buttons (such as show/hide column button), then we should edit `BootstrapTable.prototype.initToolbar`. Am I understand correctly?

**Comment by dabros** [comment]
@Taewa - please be cautious posting to closed topics, if you still looking for a solution then create a new issue and link here

**Comment by lupsik** [comment]
I think you can add button which you don't need and use .replaceWith(your own button)

**Comment by jimgit** [comment]
You may want to try the [formatter (data-formatter)  - see this ](https://github.com/wenzhixin/bootstrap-table/issues/3605)
