### ISSUE TITLE
editable select not working in example (Editable select box(#986).)

### ISSUE THREAD

**Issue by nicro87** [wenzhixin/bootstrap-table#2158]
Hi,

when I try your example I get this error in my console:
"ReferenceError: assignment to undeclared variable success
success = deferred.then(function () {"

When I'm trying on my own I get the same error. Can you please post an working example?

It would be nice if you can post an example with select2 too.
I'm trying since many hours to get one of them working.

I posted already in the closed issue #986 

Thanks in advance
Nico

**Comment by gwjwin** [comment]
I also have this problem, I cannot find a way to set x-editable select options if using `data-url`. I need a working example, thanks.

`<th data-editable='true' data-editable-type='select' data-editable-source='[{"value":1,"text":"A"}]'>Chioce</th>`

**Comment by nicro87** [comment]
Yes I have the problem with ajax-data too. So I have no possibility to set the editor in the <td>-tag.

**Comment by wenzhixin** [comment]
fixed this bug: https://github.com/vitalets/x-editable/pull/898
