### ISSUE TITLE
Export excel when using toolbar has issue

### ISSUE THREAD

**Issue by sendilgan** [wenzhixin/bootstrap-table#2161]
couple of files being downloaded 
ways to replicate the issue 
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html

click export all drop down and then click export excel.
First xls file will be downloaded.
Now select the drop down back to export basic ..
issue : automatically second file will be downloaded and the pagination will be removed.

Can you please check to fix this issue ?

**Comment by sendilgan** [comment]
Hi .. as a short term workaround .. i just added and additional condition in the export all


                        that.$el.one('load-success.bs.table page-change.bs.table', function () {
                        	//alert(3);
                        	//console.log(that.options.exportDataType);
                        	if (that.options.exportDataType === 'all') {
                        		//console.log(that.options.exportDataType);
                        		//alert(4);
                            doExport();
                            that.togglePagination();
                        	}  
                        	else {
                        		 $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                        			   	//alert(22);
                        			       var $table = $($(e.target).attr('href') + '_table');
                        			       $table.bootstrapTable('resetView');
                        			   });
                        			      
                        			   $(window).resize(function (d) {
                        			   	var $table = $($(d.target).attr('href') + '_table');
                        			       $table.bootstrapTable('resetView', {
                        			           height: getHeight()
                        			       });
                        			   });
                        		}
                        });
                        that.togglePagination();

**Comment by wenzhixin** [comment]
This problem has been fixed in the latest version.
