### ISSUE TITLE
BootStrap-table not apply Problem In struts2 

### ISSUE THREAD

**Issue by ChiragDhangar** [wenzhixin/bootstrap-table#2162]
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"  import="java.sql.*"%> 
    
    <%@ taglib prefix="s" uri="/struts-tags"%>
<%@ taglib prefix="sb" uri="/struts-bootstrap-tags"%>
<%@ taglib prefix="sj" uri="/struts-jquery-tags"%>
  
<!DOCTYPE html>

<html lang="en">
    <head>

        
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta charset="utf-8" />
       <%@include file="Externalfiles.jsp"%> 
      
<%@include file="header3.jsp"%>
	 
<script type="text/javascript">

$(document).ready(function() {

   $.ajax({
       url : "listRequest",
       type : "POST",
       success : function(data) {
       alert(data);
        document.getElementById("body").innerHTML = data;
       }
   });
});
</script>

<style>
.hidden-xs {
  display: inline-block !important;
}
</style>

        
        
        
        
        </head><body id="body">

                        

             
		<div class="row">

		<div class="table-responsive">
			<table id="table"  data-cookie="true"
				data-click-to-select="true"
				data-cookie-id-table="depreciationReportTable">
				<thead>
					<tr role="row">
						<th data-sortable="true" class="col-sm-1">server_id </th>
								<th data-sortable="true" class="col-sm-1">server_make_model </th>
								<th data-sortable="true" class="col-sm-1">processor_speed </th>
								<th data-sortable="true" class="col-sm-1">no_of_physical_cpus </th>
								<th data-sortable="true" class="col-sm-1">cores_per_physical_cpus </th>
								<th data-sortable="true" class="col-sm-1">deployed_licenses </th>
								<th data-sortable="true" class="col-sm-1">machines_in_cluster </th>
								<th data-sortable="true" class="col-sm-1">domain_cluster_name </th>
								<th data-sortable="true" class="col-sm-1">server_purchase_date </th>
								<th data-sortable="true" class="col-sm-1">Expiry_date </th>
								<th data-sortable="true" class="col-sm-1">hyperthreading_enabled </th>
								<th data-sortable="true" class="col-sm-1">admin_server </th>
								<th data-sortable="true" class="col-sm-1">architecture </th>
					</tr>
				</thead>
				<tbody>
           
           		 
        			<s:iterator value="listRequests" var="servers">
        					<tr>
							
							
							<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="server_id"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="server_make_model"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="processor_speed"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="no_of_physical_cpus"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="cores_per_physical_cpus"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="deployed_licenses"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="machines_in_cluster"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="domain_cluster_name"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="server_purchase_date"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="Expiry_date"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="hyperthreading_enabled"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="admin_server"/></div>
											<div class="fht-cell"></div>
								</td>
								
								<td style="text-align:center;">
									<div class="th-inner sortable both"><s:property value="architecture"/></div>
											<div class="fht-cell"></div>
								</td>
								
								
							</tr>
			</s:iterator>

		
           
           </tbody>
			</table>

		</div>

	</div>
</div>
 
<script type="text/javascript">
	$('#table').bootstrapTable({
		classes : 'table table-responsive table-striped table-bordered',
		undefinedText : '',
		iconsPrefix : 'fa',
		showRefresh : false,
		search : true,
		pageSize : 10,
		pagination : true,
		sidePagination : 'client',
		sortable : true,
		cookie : true,
		mobileResponsive : true,
		showExport : true,
		showColumns : true,
		exportDataType : 'all',
		exportTypes : [ 'csv', 'txt', 'json', 'xml', 'excel', 'sql', 'pdf' ],
		maintainSelected : true,
		paginationFirstText : "First",
		paginationLastText : "Last",
		paginationPreText : "Previous",
		paginationNextText : "Next",
		pageList : [ '10', '25', '50', '100', '150', '200' ],
		icons : {
			paginationSwitchDown : 'fa-caret-square-o-down',
			paginationSwitchUp : 'fa-caret-square-o-up',
			columns : 'fa-columns',
			refresh : 'fa-refresh'
		},

	});
</script>

    </body>
</html>
 i am not getting output...
at starting it showing proper table format with all option 
bt when data actual loaded then only normal table appear.no bootrat table effect appear
so solve my problem

**Comment by ChiragDhangar** [comment]
<script type="text/javascript">
	$('#table').bootstrapTable({
		classes : 'table table-responsive table-striped table-bordered',
		undefinedText : '',
		iconsPrefix : 'fa',
		showRefresh : false,
		search : true,
		pageSize : 10,
		pagination : true,
		sidePagination : 'client',
		sortable : true,
		cookie : true,
		mobileResponsive : true,
		showExport : true,
		showColumns : true,
		exportDataType : 'all',
		exportTypes : [ 'csv', 'txt', 'json', 'xml', 'excel', 'sql', 'pdf' ],
		maintainSelected : true,
		paginationFirstText : "First",
		paginationLastText : "Last",
		paginationPreText : "Previous",
		paginationNextText : "Next",
		pageList : [ '10', '25', '50', '100', '150', '200' ],
		icons : {
			paginationSwitchDown : 'fa-caret-square-o-down',
			paginationSwitchUp : 'fa-caret-square-o-up',
			columns : 'fa-columns',
			refresh : 'fa-refresh'
		},

	});
</script>

i add this also

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
