### ISSUE TITLE
Filter Control - Unselecting a filter doesn't always return table to original state

### ISSUE THREAD

**Issue by jamesmikesell** [wenzhixin/bootstrap-table#2169]
Here's the fiddle with the error and steps to reproduce the error
https://jsfiddle.net/rider2112/ahooquhc/

I've fixed this with 3b5462363b491441caa9d3ad73fa41bd2b0e06e4, though the underlying reason for this bug is the way the onSearch method is constructed in the bootstratpTable source code (and not a problem with the filter-control.js).  As such, i'm not real happy with the fix i've made, however it gets the job done.

Fixed example:
https://jsfiddle.net/rider2112/wyny90d1/

**Comment by djhvscf** [comment]
It looks good.. @wenzhixin what do you think?

**Comment by wenzhixin** [comment]
Merged in #2166
