### ISSUE TITLE
Export excel toolbar and filter control issue 

### ISSUE THREAD

**Issue by sendilgan** [wenzhixin/bootstrap-table#2171]
below is the fiddle to replicate the issue.

http://fiddle.jshell.net/1xvbcefc/22/

steps to replicate : 
1. select any value in the drop down filter control (value :blog)
2.  We will see the screen changes and the pagination will be displaying (Showing 1 to 1 of 1 rows)
3. Now in the export tool bar select export all option
4. screen will change you will see that you have only (Showing 1 to 1 of 1 rows)
issue ( selected filter controls are removed during the above step and it looks like we have only one row in the table )
to get back all the data you need to select any value from the drop down and then select black field to get all the data.

and if the filter control input option is used.
after you type in the input filter and then export all ..the filter condition is removed and to get back the data you need to enter some random data and then remove it.

Can you please help on it ?

**Comment by Falseee** [comment]
Working Demo: https://jsfiddle.net/64Lvhr98/1/

**Comment by djhvscf** [comment]
Fixed in https://github.com/wenzhixin/bootstrap-table/pull/4279
