### ISSUE TITLE
Do tables support highlighting for search?

### ISSUE THREAD

**Issue by antonyboom** [wenzhixin/bootstrap-table#2172]
I was looked for highlighting thru issues, but didn't find anything.. Is there any way to highlight words while using search?

I was trying to implement this [jquery plugin](http://johannburkard.de/blog/programming/javascript/highlight-javascript-text-higlighting-jquery-plugin.html) and used for this ` $table.highlight($("search").val()); ` From f12 in console, I found  that trigger event  in boostrap-table js only on ('search'), also I've tried    
`$table.highlight($(".search.bs.table").val());` cause console shows that all events calling thru .search.bs.table but nothing happens. Can tables support others jquery plugins?
[Plunker with my code] (https://plnkr.co/edit/bNAB6xo1YTJ6D66cMUv7?p=preview)

**Comment by antonyboom** [comment]
@djhvscf I fixed it, can be closed 
code 
```
$table.highlight($(".search.bs.table").val());

$table.on('search.bs.table', function (e, text){

    $table.highlight(text);
    console.log(e);
    console.log(text);
});
```
css:
`.highlight {background-color: yellow}`

working [**plunker**](https://plnkr.co/edit/Th4T9TMHZATuiKAx8fak?p=preview)

**Comment by djhvscf** [comment]
Great!! Anyway I think this feature can be a good extension
