### ISSUE TITLE
Load Json data

### ISSUE THREAD

**Issue by ChiragDhangar** [wenzhixin/bootstrap-table#2174]
var newDta
$.ajax({
    url: "listRequest",
    async: true,
    crossDomain: true,
    type: "post",
    dataType: "json",
    success: function (data) {
    	 var newDta = JSON.stringify(data); 
    	
    	 $('#table').bootstrapTable({
    	        classes: 'table table-responsive table-striped table-bordered',
    	        undefinedText: '',
    	        data:data.json,
    	        iconsPrefix: 'fa',
    	        showRefresh: false,
    	        search: true,
    	        pageSize: 10,
    	        pagination: true,
    	        sidePagination: 'client',
    	        sortable: true,
    	        cookie: true,
    	        mobileResponsive: true,
    	        showExport: true,
    	        showColumns: true,
    	        exportDataType: 'all',
    	        exportTypes: ['csv', 'txt','json','xml','excel','sql','pdf'],
    	        maintainSelected: true,
    	        paginationFirstText: "First",
    	        paginationLastText: "Last",
    	        paginationPreText: "Previous",
    	        paginationNextText: "Next",
    	        pageList: ['10','25','50','100','150','200'],
    	        icons: {
    	            paginationSwitchDown: 'fa-caret-square-o-down',
    	            paginationSwitchUp: 'fa-caret-square-o-up',
    	            columns: 'fa-columns',
    	            refresh: 'fa-refresh'
    	        },
    	        columns: [
    	                  {field:'server_id'},
    	                  {field:'server_id'},
    	                  {field:'server_id'},
    	                  {field:'server_id'}
    	                  
    	                  
    	                  ]                  

    	    }); 
    
    	
    	
    }});
    Hello buddy ,
I am getting all json data into data variable,
I want to put this data inside boottrap table. i tried lot and lot but fail everything 
so please help me as soon as possible

**Comment by dabros** [comment]
@ChiragDhangar - look at the doco + examples and remove 'is:closed' filter then search here

http://bootstrap-table.wenzhixin.net.cn/getting-started/
http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options (see 'url' and 'responseHandler' in particular)
http://issues.wenzhixin.net.cn/bootstrap-table/ (examples)
https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue+json

And for fiddle links and guide to how you actually should ask for help:
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports


You look like you copy pasted code from 3 different places, not sure why you include it in ajax success (you can, but you certainly dont need to, see `url` option in examples and doco). You also got a `JSON.stringify` call that looks like it will give you an error (Use https://developers.google.com/web/tools/chrome-devtools/?hl=en or similar F12 tool to see errors produced)

Your columns all say 'server_id', no idea what thats about, but again just look at doco and examples

No idea what you data looks like, and ect ect ect

Look at the doco, follow the examples, search other issues

**Comment by ChiragDhangar** [comment]
my data look like
{"aaData":[{"admin_server":13,"approved":1,"architecture":"     ","cores_per_physical_cpus":4,"decommission":0,"deployed_licenses":4,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":2,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":13,"server_make_model":"PowerEdge R710 - Xeon(R) Proce","server_purchase_date":"0000-00-00"},{"admin_server":16,"approved":1,"architecture":"     ","cores_per_physical_cpus":2,"decommission":0,"deployed_licenses":2,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":2,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":16,"server_make_model":"PowerEdge 6850","server_purchase_date":"0000-00-00"},{"admin_server":19,"approved":1,"architecture":"     ","cores_per_physical_cpus":4,"decommission":0,"deployed_licenses":4,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":2,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":19,"server_make_model":"ProLiant BL460c G1 - Xeon","server_purchase_date":"0000-00-00"},{"admin_server":22,"approved":1,"architecture":"     ","cores_per_physical_cpus":4,"decommission":0,"deployed_licenses":6,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":2,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":22,"server_make_model":"Sun Fire E2900 - UltraSPARC™IV","server_purchase_date":"0000-00-00"},{"admin_server":23,"approved":1,"architecture":"     ","cores_per_physical_cpus":4,"decommission":0,"deployed_licenses":3,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":1,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":23,"server_make_model":"Sun Fire V440 - UltraSPARC III","server_purchase_date":"0000-00-00"},{"admin_server":26,"approved":1,"architecture":"     ","cores_per_physical_cpus":1,"decommission":0,"deployed_licenses":2,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":2,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":26,"server_make_model":"Sun Fire V490 - UltraSPARC IV","server_purchase_date":"0000-00-00"},{"admin_server":29,"approved":1,"architecture":"     ","cores_per_physical_cpus":2,"decommission":0,"deployed_licenses":12,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":8,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":29,"server_make_model":"Sun Fire E4900 - UltraSPARC II","server_purchase_date":"0000-00-00"},{"admin_server":34,"approved":1,"architecture":"     ","cores_per_physical_cpus":2,"decommission":0,"deployed_licenses":36,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":24,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":34,"server_make_model":"Sun Fire E6900 - UltraSPARC® I","server_purchase_date":"0000-00-00"},{"admin_server":35,"approved":1,"architecture":"     ","cores_per_physical_cpus":4,"decommission":0,"deployed_licenses":2,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":1,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":35,"server_make_model":"ProLiant DL380 G5 - Xeon","server_purchase_date":"0000-00-00"},{"admin_server":36,"approved":1,"architecture":"     ","cores_per_physical_cpus":8,"decommission":0,"deployed_licenses":16,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":4,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":36,"server_make_model":"PowerEdge R910","server_purchase_date":"0000-00-00"},{"admin_server":40,"approved":1,"architecture":"     ","cores_per_physical_cpus":2,"decommission":0,"deployed_licenses":4,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":4,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":40,"server_make_model":"ProLiant DL580 G5 - Xeon","server_purchase_date":"0000-00-00"},{"admin_server":41,"approved":1,"architecture":"     ","cores_per_physical_cpus":8,"decommission":0,"deployed_licenses":4,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":1,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":41,"server_make_model":"SPARC Enterprise T5220","server_purchase_date":"0000-00-00"},{"admin_server":44,"approved":1,"architecture":"     ","cores_per_physical_cpus":2,"decommission":0,"deployed_licenses":5,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":3,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":44,"server_make_model":"Sun Fire V480 - UltraSPARC III","server_purchase_date":"0000-00-00"},{"admin_server":48,"approved":1,"architecture":"     ","cores_per_physical_cpus":8,"decommission":0,"deployed_licenses":4,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":1,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":48,"server_make_model":"T5440","server_purchase_date":"0000-00-00"},{"admin_server":50,"approved":1,"architecture":"     ","cores_per_physical_cpus":2,"decommission":0,"deployed_licenses":2,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":1,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":50,"server_make_model":"Sun Fire V240 - UltraSPARC III","server_purchase_date":"0000-00-00"},{"admin_server":51,"approved":1,"architecture":"     ","cores_per_physical_cpus":8,"decommission":0,"deployed_licenses":6,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":1,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":51,"server_make_model":"SPARC Enterprise M5000 Server","server_purchase_date":"0000-00-00"},{"admin_server":53,"approved":1,"architecture":"     ","cores_per_physical_cpus":6,"decommission":0,"deployed_licenses":6,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":2,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":53,"server_make_model":"T5240","server_purchase_date":"0000-00-00"},{"admin_server":57,"approved":1,"architecture":"     ","cores_per_physical_cpus":2,"decommission":0,"deployed_licenses":78,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":52,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":57,"server_make_model":"Sun Fire E25K - UltraSPARC III","server_purchase_date":"0000-00-00"},{"admin_server":58,"approved":1,"architecture":"     ","cores_per_physical_cpus":1,"decommission":0,"deployed_licenses":3,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":4,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":58,"server_make_model":"Sun Enterprise 420R (4 X Ultra","server_purchase_date":"0000-00-00"},{"admin_server":59,"approved":1,"architecture":"     ","cores_per_physical_cpus":1,"decommission":0,"deployed_licenses":2,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":2,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":59,"server_make_model":"Sun Fire 280R (2 X UltraSPARC-","server_purchase_date":"0000-00-00"},{"admin_server":62,"approved":1,"architecture":"     ","cores_per_physical_cpus":1,"decommission":0,"deployed_licenses":5,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":7,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":62,"server_make_model":"Sun Fire V1280 - UltraSPARC¨ I","server_purchase_date":"0000-00-00"},{"admin_server":64,"approved":1,"architecture":"     ","cores_per_physical_cpus":2,"decommission":0,"deployed_licenses":1,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":1,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":64,"server_make_model":"PowerEdge 2950 - Xeon Processo","server_purchase_date":"0000-00-00"},{"admin_server":65,"approved":1,"architecture":"     ","cores_per_physical_cpus":4,"decommission":0,"deployed_licenses":4,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":2,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":65,"server_make_model":"Intel(R) Xeon(R) CPU E5410 @ 2","server_purchase_date":"0000-00-00"},{"admin_server":67,"approved":1,"architecture":"     ","cores_per_physical_cpus":6,"decommission":0,"deployed_licenses":6,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":2,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":67,"server_make_model":"Intel(R) Xeon(R) CPU L5640 @ 2","server_purchase_date":"0000-00-00"},{"admin_server":68,"approved":1,"architecture":"     ","cores_per_physical_cpus":8,"decommission":0,"deployed_licenses":16,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":4,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":68,"server_make_model":"Intel(R) Xeon(R) CPU X7560 @ 2","server_purchase_date":"0000-00-00"},{"admin_server":69,"approved":1,"architecture":"     ","cores_per_physical_cpus":4,"decommission":0,"deployed_licenses":2,"domain_cluster_name":"     ","hyperthreading_enabled":0,"machines_in_cluster":1,"no_of_physical_cpus":1,"oracle_processor_core_factor":1,"processor_speed":0,"server_id":69,"server_make_model":"Intel(R) Xeon(R) CPU E5-2680 0","server_purchase_date":"0000-00-00"},{"admin_server":72,"approved":1,"architecture":"     ","cores_per_physical_cpus":

**Comment by dabros** [comment]
@ChiragDhangar - read my last post, you have all the info you need

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!

**Comment by kghulami** [comment]
@dabros ;

Can you please put the correct form of  sample code (like first post here) in order to make it clear for me, on how to use Ajax, to put data into my #table.bootstrapTable.

**Comment by dabros** [comment]
@kghulami - i never provided code sample, read my posts then use that to research the steps required, thats all my posts were as thats all thats needed here

**Comment by kghulami** [comment]
Tnx; that is my method too. 

But, honestly i have been searching here for 3 days now, to come up with a final result but got lost completely now.

**Comment by dabros** [comment]
@kghulami - then the info in my posts apply to you, especially those links. If at all different than this issue, then create new issue using guide in contributing.md that i linked to, ensure you answer requirements for a proper question and fiddle so you can get working code.
