### ISSUE TITLE
Hide foot column when column data-visible="false"

### ISSUE THREAD

**Issue by zomannk** [wenzhixin/bootstrap-table#2175]
http://jsfiddle.net/e3nk137y/5726/

Hide f4 and other footers when column visible false.

**Comment by zomannk** [comment]
Is there a solution or a temporary fix????

**Comment by djhvscf** [comment]
You should use the footerFormatter function. See this: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/issues/639.html#L36
