### ISSUE TITLE
提交一个getRowByUniqueId功能

### ISSUE THREAD

**Issue by linziguan** [wenzhixin/bootstrap-table#2176]
$.fn.bootstrapTable.Constructor.prototype.getRowByUniqueId=function(index){
		var datas=this.getData();
		return datas[index];
	};
	$.fn.bootstrapTable.methods.push('getRowByUniqueId');

**Comment by djhvscf** [comment]
Can you translate this issue to english? @linziguan

**Comment by wenzhixin** [comment]
已经有这个方法：https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L2394
