### ISSUE TITLE
Documentation not available for filters

### ISSUE THREAD

**Issue by tarakeshwebdeveloper** [wenzhixin/bootstrap-table#2177]
Please create clear documentation for using filters

**Comment by djhvscf** [comment]
Can you specify what is the plugin that you are talking about? @tarakeshwebdeveloper

**Comment by djhvscf** [comment]
Any update here?

**Comment by nicolaeturcan** [comment]
Hey @djhvscf, I didn't want to create another issue just for that, but could you give me any advice about how could I do a custom filter on a toolbar which perfectly can be located on a sidebar like this?
![seleccio_120](https://cloud.githubusercontent.com/assets/7248811/14889143/d8339958-0d5d-11e6-92f3-fb3c94e0fd90.png)

The only example I found was this http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html which seems to use server side filtering, but I couldn't manage to adapt it to my needs.

**Comment by djhvscf** [comment]
Ok, you mean use the toolbar in a sidebar?? if must use the built-in methods.. like resetSearch, refreshOptions

**Comment by wenzhixin** [comment]
`filterBy` method maybe useful.

**Comment by nicolaeturcan** [comment]
@djhvscf I ended up doing it like in the example i posted above, passing params to the api and doing the query on the server side. 

@wenzhixin thanks you, I didn't see this in the examples but that's what I really was looking for. I'll try to switch to this method later.

**Comment by nicolaeturcan** [comment]
By the way @djhvscf @wenzhixin, toolbar is always appending to the table, is there a way to place it freely as I mentioned above in a sidebar for example? 

I placed it there already but when I set data-toolbar it gets moved automatically to the top-left of the table and if it isn't set the filter sets well but doesn't work.

**Comment by djhvscf** [comment]
If  you use the data-toolbar always it gets moved to the top-left... I think the solution is create your own toolbar without data-toolbar attribute and the use the `filterBy`, `resetSearch`, `refreshOptions` methods in order to filter your data

**Comment by nicolaeturcan** [comment]
Vale Dennis, creo que es lo que voy a intentar hacer, gracias!
