### ISSUE TITLE
和其他js插件冲突,有解决方案么

### ISSUE THREAD

**Issue by liyi0215** [wenzhixin/bootstrap-table#2178]
Uncaught TypeError: $table.bootstrapTable is not a function

**Comment by Farb** [comment]
I met the same problem!

 ![图片](https://dn-coding-net-production-pp.qbox.me/df220174-1442-47aa-b0e3-3905b133a168.png) 

The `bars` class in bootstrap-table.css file confilts with other css file,so the display result is what I don't want!Huh!

**Comment by Farb** [comment]
I met the same problem!

 ![图片](https://dn-coding-net-production-pp.qbox.me/df220174-1442-47aa-b0e3-3905b133a168.png) 

The `bars` class in bootstrap-table.css file confilts with other css file,so the display result is what I don't want!Huh!

**Comment by Farb** [comment]
I met the same problem!

 ![图片](https://dn-coding-net-production-pp.qbox.me/df220174-1442-47aa-b0e3-3905b133a168.png) 

The `bars` class in bootstrap-table.css file confilts with other css file,so the display result is what I don't want!Huh!

**Comment by Farb** [comment]
I met the same problem!

 ![图片](https://dn-coding-net-production-pp.qbox.me/df220174-1442-47aa-b0e3-3905b133a168.png) 

The `bars` class in bootstrap-table.css file confilts with other css file,so the display result is what I don't want!Huh!

**Comment by Farb** [comment]
I met the same problem!

 ![图片](https://dn-coding-net-production-pp.qbox.me/df220174-1442-47aa-b0e3-3905b133a168.png) 

The `bars` class in bootstrap-table.css file confilts with other css file,so the display result is what I don't want!Huh!

**Comment by Farb** [comment]
I met the same problem!

 ![图片](https://dn-coding-net-production-pp.qbox.me/df220174-1442-47aa-b0e3-3905b133a168.png) 

The `bars` class in bootstrap-table.css file confilts with other css file,so the display result is what I don't want!Huh!

**Comment by Farb** [comment]
I met the same problem!

 ![图片](https://dn-coding-net-production-pp.qbox.me/df220174-1442-47aa-b0e3-3905b133a168.png) 

The `bars` class in bootstrap-table.css file confilts with other css file,so the display result is what I don't want!Huh!

**Comment by Farb** [comment]
I met the same problem!

 ![图片](https://dn-coding-net-production-pp.qbox.me/df220174-1442-47aa-b0e3-3905b133a168.png) 

The `bars` class in bootstrap-table.css file confilts with other css file,so the display result is what I don't want!Huh!

**Comment by Farb** [comment]
I met the same problem!

 ![图片](https://dn-coding-net-production-pp.qbox.me/df220174-1442-47aa-b0e3-3905b133a168.png) 

The `bars` class in bootstrap-table.css file confilts with other css file,so the display result is what I don't want!Huh!

**Comment by liyi0215** [comment]
[
![Uploading 1.png…]()
](url)

**Comment by djhvscf** [comment]
Let me see what we can do with this issue

**Comment by liyi0215** [comment]
When used with other JS plug-ins, the

Uncaught TypeError: $table.bootstrapTable is not a function

**Comment by djhvscf** [comment]
See #2180
