### ISSUE TITLE
Bug Report About Bootstrap-table Filter control extension

### ISSUE THREAD

**Issue by Farb** [wenzhixin/bootstrap-table#2179]
I add the 'Clear Filters' button,and when I click the button,there is an error in the console.

![image](https://cloud.githubusercontent.com/assets/7587900/14452328/9939bb0a-00c0-11e6-8cc4-e17fd708d45b.png)

**Comment by djhvscf** [comment]
Can you provide an example, please? @Farb

**Comment by Farb** [comment]
@djhvscf https://jsfiddle.net/farb/fp25opbb/  .Open the console,and click the 'Clear Filters' button,you will get an error!

**Comment by Farb** [comment]
@djhvscf By the way,could we change the title of "Clear Filters" button?I want to change it into Chinese text!

**Comment by djhvscf** [comment]
See this #2180
Example: https://jsfiddle.net/djhvscf/fp25opbb/1/

**Comment by Farb** [comment]
@djhvscf Ok,thanks for your work!Could I change the title of the "Clear Filters" button?

**Comment by djhvscf** [comment]
Use just use the formatClearFilter function like formatClearFilter: function (){return "just text";}

**Comment by Farb** [comment]
@djhvscf The formatClearFilter belongs to API option?I did not find  it in the table option or column option.

**Comment by Farb** [comment]
@djhvscf And how to set the placeholder of the filter input?

**Comment by djhvscf** [comment]
It belongs to filterControl extension.. and related to placeholder that feature is not supported

**Comment by djhvscf** [comment]
@Farb See this #2189

**Comment by Farb** [comment]
@djhvscf  I know ‘It belongs to filterControl extension.’.But I still even don't know where I should set `formatClearFilter` option.Could you give me an example?Thanks in advance!

**Comment by djhvscf** [comment]
For example:

```js
$("#table").bootstrapTable({
 //your configuration here...
 filterControl: true, 
 formatClearFilter: function () {
  return "Your custom text";
 }
});
```

**Comment by Farb** [comment]
@djhvscf I am so sorry,that does not work!I have tried that today!:joy:

**Comment by djhvscf** [comment]
Sorry, it should be like

```js
formatClearFilters: function () {
            return 'Clear Filters';
}
```

**Comment by Farb** [comment]
@djhvscf I suggest you should update the document!Thanks a lot!
