### ISSUE TITLE
resetSearch method for Filter Control extension (reset all search fields and cookies)

### ISSUE THREAD

**Issue by bartosh44** [wenzhixin/bootstrap-table#2182]
resetSearch method works with search input, I would like to get same reset effect with "Filter Control" extension.

**Comment by bartosh44** [comment]
There is something like: BootstrapTable.prototype.clearFilterControl but I don`t know how to properly use it.

**Comment by djhvscf** [comment]
You can use the filterShowClear this will add a button where you can clear all the values in the controls created by the extension

**Comment by bartosh44** [comment]
But I would like to use it in external button. How to trigger it (filterShowClear)?

**Comment by djhvscf** [comment]
Ok, this feature is not supported at the moment! Please remember any **PR** is welcome

**Comment by djhvscf** [comment]
i'm going to open it again because we need to know that this can be a good feature!

**Comment by andyandox** [comment]
so, thie feature has be solved now？thanks @djhvscf

**Comment by Falseee** [comment]
@djhvscf There is already the function `clearFilterControl` to clear all inputs so the issue can be closed, or not ?
Btw. i opened a [PR](https://github.com/wenzhixin/bootstrap-table/pull/4223) to add the missing documentation about that function.

**Comment by djhvscf** [comment]
That is correct @Falseee let's close it
