### ISSUE TITLE
Filter Control Extension Checkbox problem

### ISSUE THREAD

**Issue by Farb** [wenzhixin/bootstrap-table#2184]
When I switch to  check the checkbox,I will get the following the error:

![image](https://cloud.githubusercontent.com/assets/7587900/14491116/916c4b1a-01a9-11e6-94fc-4c618dd18290.png)

Look at the code on the jsfiddle:

https://jsfiddle.net/farb/gwjkzr3x/

**Comment by djhvscf** [comment]
What are the steps to get this issue? @Farb

**Comment by Farb** [comment]
@djhvscf Open the console,check the "check all" check box or uncheck it.

**Comment by djhvscf** [comment]
I could not see the error n the console

**Comment by Farb** [comment]
Ok  it's a strange error
