### ISSUE TITLE
Repeat header in lines ? 

### ISSUE THREAD

**Issue by maxxyPhp** [wenzhixin/bootstrap-table#2185]
Hello,

I wonder if there is a solution to repeat the thead in the table, all the N lines ?
(like in phpMyAdmin)

Sorry for my english, i'm a french developer

Thanks

**Comment by djhvscf** [comment]
I am not sure what you mean. I am going to need some more information.

**Comment by maxxyPhp** [comment]
For example, in this table, the thead is show again in the middle of table :

![image](https://cloud.githubusercontent.com/assets/8862533/14494560/bb751cc0-018b-11e6-87bf-7abd4df21e96.png)

**Comment by djhvscf** [comment]
Ok, this feature is not supported but maybe you can use this extension: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/sticky-header.html

**Comment by wenzhixin** [comment]
Not support this feature.
