### ISSUE TITLE
Excel export doesn't work on Safari

### ISSUE THREAD

**Issue by RedPointMS** [wenzhixin/bootstrap-table#2187]
It seems that there is a problem with exporting table to Excel when using Safari browser. The example of the [extension](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html) returns file titled "Uknown" and without any extension, failing to open in Excel.

**Comment by wenzhixin** [comment]
Do you know why @hhurz?

**Comment by hhurz** [comment]
I confirm this issue: Safari will not let you generate a none text file (a blob). This extension ([tableexport.jquery.plugin](https://github.com/hhurz/tableExport.jquery.plugin)) uses another plugin ([FileSaver.js](https://github.com/eligrey/FileSaver.js)) to save files on client-side. You can find several issue reports on FileSaver.js's project side ([#12](https://github.com/eligrey/FileSaver.js/issues/12), [#129](https://github.com/eligrey/FileSaver.js/issues/129), [#189](https://github.com/eligrey/FileSaver.js/issues/189), [#196](https://github.com/eligrey/FileSaver.js/issues/196)), that complain about Safari and saving files. Finally it seems to be a problem of newer Safari and/or Webkit versions it uses. Actually there seems to be no workaround until Apple fixes it. See also this [comment](https://github.com/eligrey/FileSaver.js/issues/12#issuecomment-73781598)

**Comment by wenzhixin** [comment]
Thanks @hhurz
