### ISSUE TITLE
Browser console error with multiple search extension and show columns option

### ISSUE THREAD

**Issue by DiogoAlves92** [wenzhixin/bootstrap-table#2191]
I think that this problem was not reported yet.

Here is an example:
https://jsfiddle.net/d05axjb9/6/

And the error:
![captura de ecra de 2016-04-14 22-06-19](https://cloud.githubusercontent.com/assets/2064958/14544495/3c77058a-0291-11e6-8aab-280fd9ff744a.png)

The multiple search works well but does not show and hide columns

**Comment by djhvscf** [comment]
See this: https://jsfiddle.net/d05axjb9/9/

**Comment by DiogoAlves92** [comment]
Fixed, thanks
