### ISSUE TITLE
bootstrap-table don't work on ie 9 and prev version 

### ISSUE THREAD

**Issue by poweman** [wenzhixin/bootstrap-table#2193]
bootstrap-table version : 1.10.1 
jquery version : 1.8.1

line : bootstatp-table.js 1911
error content : the args is must ( I translate from Chinese)

**Comment by poweman** [comment]
pls help me resolve this issue.

**Comment by djhvscf** [comment]
Can you provide an example, please?

**Comment by poweman** [comment]
@djhvscf  i afraid i could not, my work pc could not connect the Internet. 
But  i believe this issue is very easy to reproduce.  My bootstrap-table is not a special example.

**Comment by poweman** [comment]
@djhvscf  code : 
<div id="test" style="overflow:hidden;">
    <legend><label>test1</label></legend>
    <table>
    <tr>
        <td>
            <label>test1</label>
        </td>
        <td>
            <label>test2</label>
        </td>
        <td>
            <label>test3</label>
        </td>					
    </tr>
    <td width="100%" height="200px" style="vertical-align:top;display:block;overflow-y:auto">
        <table id="example1">
        </table>
    </td>
    </table>
</div>

js code : 

$("#example1").bootstrapTable({
		classes: "table table-striped table-hover",
		selectItemName:"fileSelected",
		columns: [{
			checkbox: true
		}, {
			field: 'path',
			title: "path",
			sortable: true
		}, {
			field: "modify_time",
			title: "modify time",
			sortable: true			
		}, {
			field: "size",
			title: "size",
			formatter:"formatByte",
			sortable: true
		}, {
			field: "upload",
			visible: false
		}],
		formatNoMatches: function () {
			return "no record is match;
		}
	});

**Comment by poweman** [comment]
`<div id="test" style="overflow:hidden;">
    <legend><label>test1</label></legend>
    <table>
    <tr>
        <td>
            <label>test1</label>
        </td>
        <td>
            <label>test2</label>
        </td>
        <td>
            <label>test3</label>
        </td>					
    </tr>
    <td width="100%" height="200px" style="vertical-align:top;display:block;overflow-y:auto">
        <table id="example1">
        </table>
    </td>
    </table>
</div>
`

**Comment by djhvscf** [comment]
Sorry but I'm going to need the example or dummy data

**Comment by poweman** [comment]
@djhvscf   i have pasted the code ,  you don't see it ?

i append the data use js code like this : 
   $("#example1").bootstrapTable('append' , json.file);
I think you could  construct some object data , the object is simple .
but the error is init bootstrap-table!!

**Comment by wenzhixin** [comment]
Can you provide a screenshot of the error? @poweman

**Comment by poweman** [comment]
Thanks for you reply , the screenshot:
![error](https://cloud.githubusercontent.com/assets/3185849/14695404/56e00d64-07a4-11e6-95fa-63eab09515ec.jpg)
@wenzhixin

**Comment by poweman** [comment]
what about this issue ? @wenzhixin

**Comment by poweman** [comment]
this issue can not fix?

**Comment by poweman** [comment]
@wenzhixin  @djhvscf   there is the same issue on IE10 ,  could u fix it as soon as ?

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
