### ISSUE TITLE
how to use "onEditableInit"

### ISSUE THREAD

**Issue by a40234023** [wenzhixin/bootstrap-table#2197]
ask how to use "onEditableInit"
ex:
`onEditableInit: function () {`
 `mode='inline';`
`toggle='manual';`
`showbuttons=false;`
`onblur='submit';`
`inputclass='input-small';`
`return true;` 
`},`
THX

**Comment by wenzhixin** [comment]
`onEditableInit` is an event: https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/editable#oneditableiniteditable-initbstable. Do you want to set the options of the editable column?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
