### ISSUE TITLE
Table export with title

### ISSUE THREAD

**Issue by abazanvillanueva** [wenzhixin/bootstrap-table#2198]
Would like to know if it can be possible to set a title to the table to export ( not the file ). Thanks

**Comment by djhvscf** [comment]
I'm not sure what you mean with this. Can you explain us a little bit more?

**Comment by abazanvillanueva** [comment]
Ok. I mean, I have a table of products, its columns are {codprod, nameprod, price}, so, when I export to excel for example, I would like to see "List of Products" followed by the table with the data.

**Comment by dabros** [comment]
@abazanvillanueva - I would suggest looking at group columns: #1630

Simple to add, could hide via css on html page if you really wanted, but would be in export as part of table structure, and assumingly handled correct across all formats.

**Comment by wenzhixin** [comment]
Maybe we can add some events for example `onBeforeExport` and `onExport`, so you can handle the title before export and restore them after export.

**Comment by abazanvillanueva** [comment]
@dabros, I will take your suggestion. Thnks

**Comment by wenzhixin** [comment]
Close this issue.
