### ISSUE TITLE
询问问题

### ISSUE THREAD

**Issue by chunfeng0060** [wenzhixin/bootstrap-table#2199]
请问一下，有没有导出Excel的调用方法？

**Comment by wenzhixin** [comment]
有的，http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html

**Comment by chunfeng0060** [comment]
我只想要一个按钮，导出Excel的按钮，是不是需要改写bootstrap-table-export.js这个文件？

**Comment by wenzhixin** [comment]
是的，目前没有做的那么智能。欢迎提交 PR
