### ISSUE TITLE
Refresh static client-side table after cleared filter control search

### ISSUE THREAD

**Issue by bartosh44** [wenzhixin/bootstrap-table#2200]
How to refresh visible table and pagination on pure ordinary table (static client side table)?

I`ve create button for clearing filter control:
1) set value of all fields to null - $('.fht-cell .filterControl input').val(null);
2) clear filter control array data - $('table').bootstrapTable('getOptions').filterControls = [];
3) refresh cookies by using onSearch - e = jQuery.Event("keyup"); event = $( this ).trigger(e); $('table').bootstrapTable('getOptions').onSearch(event);

Now everything is fine but I need refresh site to see my actual rows list. I would like to refresh only table without refreshing whole site. Is it possible?

**Comment by djhvscf** [comment]
Use this option https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/filter-control#filtershowclear

In that way you will get a button with that functionality

**Comment by cgountanis** [comment]
What if you do not want a button and just want to call the clear from another object using bootstrapTable('clearFilterControl') clears the header filters but table no refreshy.
