### ISSUE TITLE
There is a problem when I use showLoading and fliter-control at the same time.

### ISSUE THREAD

**Issue by RickyHuo** [wenzhixin/bootstrap-table#2201]
I want to use `filter-control` and `Loading` in my page:

![qq 20160419182002](https://cloud.githubusercontent.com/assets/18550072/14635997/84dffcd2-065b-11e6-848f-f2e058bc3392.png)

But when I use `bootstrapTable('showLoading')`,it will be
![qq 20160419182025](https://cloud.githubusercontent.com/assets/18550072/14636026/ad399846-065b-11e6-8e4f-10a96a5014bb.png)
It seems that `this.$header.outerHeight()` can't get correct value when I use `filter-control`.

**Comment by djhvscf** [comment]
Can you provide an example, please?

The screenshots are very helpful but an example will be the best option

**Comment by RickyHuo** [comment]
My example is based on extensions/filter-control.html,but I add two buttons about `showLoading` and `hideLoading`

```
<!DOCTYPE html>
<html>
<head>
    <title>Filter Control</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../assets/bootstrap-table/src/bootstrap-table.css">
    <link rel="stylesheet" href="../assets/examples.css">
    <script src="../assets/jquery.min.js"></script>
    <script src="../assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="../assets/bootstrap-table/src/bootstrap-table.js"></script>
    <script src="../assets/bootstrap-table/src/extensions/filter-control/bootstrap-table-filter-control.js"></script>
    <script>
        //My function about "loading"        
        function show(){
            $( "#table" ).bootstrapTable('showLoading');
        }
        function hide(){
            $( "#table" ).bootstrapTable('hideLoading');
        }
    </script>
</head>
<body>
<div class="container">
     <!--
     The buttons of myslf.
    -->
    <button type="button" class="btn btn-default" onclick="show()">show</button>
    <button type="button" class="btn btn-default" onclick="hide()">hide</button>
    <h1>Filter Control</h1>
    <table id="table"
           data-toggle="table"
           data-url="../json/data1.json"
           data-filter-control="true">
        <thead>
        <tr>
            <th data-field="id">ID</th>
            <th data-field="name" data-filter-control="input">Item Name</th>
            <th data-field="price" data-filter-control="select">Item Price</th>
        </tr>
        </thead>
    </table>
</div>
</body>
</html>
```

**Comment by djhvscf** [comment]
Please provide an fiddle with that code

**Comment by dabros** [comment]
Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Fiddles and similar steps are needed for us to better help everyone, and for you to help yourself :)

**Comment by RickyHuo** [comment]
@djhvscf  @dabros  Thanks for help.
I build an fiddle just now.http://jsfiddle.net/e3nk137y/5959/

**Comment by dabros** [comment]
@djhvscf @wenzhixin - simple issue where `top:42px` is applied to that blocking element holding `show loading`. 

Not familiar with code responsible for creating it, so i will leave it to you guys to put out simple patch that overrides that when using filter extension, ideally with intelligent height detection of first `<tr>` actual height.

**Comment by Falseee** [comment]
example: http://jsfiddle.net/0m7rkh8j/2/
