### ISSUE TITLE
Problems with Filter Control and Formatter

### ISSUE THREAD

**Issue by DustinUtecht** [wenzhixin/bootstrap-table#2202]
If you use formatter and select and entry (in this example 'dog') it shows no data in the table.
Btw. the entry shows twice too.

The Jsfiddle
http://jsfiddle.net/fnvk8xwa/7/

**Comment by djhvscf** [comment]
See this example: http://jsfiddle.net/djhvscf/fnvk8xwa/9/ we are using `data-search-formatter="true"`

**Comment by DustinUtecht** [comment]
Okay, i saw it and think it is a bug from filter control because in the documentation from filter control is no 'data-search-formatter'.
I dont searched on the normal documentation :)
