### ISSUE TITLE
Filter-control and server side pagination

### ISSUE THREAD

**Issue by lpawlak** [wenzhixin/bootstrap-table#2203]
A have server side pagination grid with search control and I wan't to add filter control working on client-side (filter only what is visible). It's possible?
Now when add some text to input filter column, there is server side refresh and entered text is sended same as search text.

**Comment by djhvscf** [comment]
You can use the filter-control extension with server/client side pagination

**Comment by lpawlak** [comment]
I am using bootstrap-table-filter-control.js from https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/filter-control and my grid has attributes:
```
data-side-pagination="server"
data-query-params-type=""
data-query-params="queryParams"
```

What else to do?

**Comment by djhvscf** [comment]
What about the columns configuration?

**Comment by lpawlak** [comment]
Columns are configured correctly (data-filter-control="input/select").

It will be simpler to explain this behavior via jsfiddle example: http://jsfiddle.net/lukaszp/140r4748/1/
Just see. First I enter "test118" in search input, and there is query to server with parameter search=test118 (1.). Then I try to filter data entering "12" in filter input. After click enter there are 3! AJAX requests (2.) to server with parameter search=12, so search parameter is lost.
![bst_filter](https://cloud.githubusercontent.com/assets/8555321/14702350/2b214be2-07aa-11e6-999c-ee3d2fdc827c.png)

**Comment by djhvscf** [comment]
Ok, let me see it!

**Comment by lpawlak** [comment]
It's possible to fire onColumnSearch before queryParams refresh data? If yes, then I could get column name from filtered field and pass it into query params.

**Comment by lpawlak** [comment]
If I add comment in 476 line of bootstrap-table-filter-control.js it's not breaks search:
 //this.onSearch(event);
But is still request to data server.
