### ISSUE TITLE
custom style paging

### ISSUE THREAD

**Issue by sandeepfis** [wenzhixin/bootstrap-table#2204]
I want to implement paging with my custom html. I do need only Previous and next and jump to page and show dropdown with  my own css class and text. Can I modify paging as per my requirement? I also require subgrid functionality. Is this available in bootstrap table?

**Comment by djhvscf** [comment]
See this for the pagination: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/selectPage-prevPage-nextPage.html
See this for subtable functionality: http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html
