### ISSUE TITLE
Allow configuration for search string delimiter

### ISSUE THREAD

**Issue by samuelstein** [wenzhixin/bootstrap-table#2205]
would be great if there is an option to define an optional split delimiter if the default whitespace is not satisfying (feature request).

**Comment by djhvscf** [comment]
In the meantime you can use this extension: https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/multiple-search/bootstrap-table-multiple-search.js but we need to add the string delimiter option in that extension

**Comment by djhvscf** [comment]
Add `delimeter`option in the `multiple-search` extension

**Comment by samuelstein** [comment]
looks ok but i hardened the split function. see #2206
