### ISSUE TITLE
How to use cellStyle?

### ISSUE THREAD

**Issue by juanfernando** [wenzhixin/bootstrap-table#221]
Well, I don't know how to use the `cellStyle` propertie, I try using it like `rowStyle` but it doesn't work...

My columns array looks a little bit like this:

```
columns: [{
	field: 'status_pedidos',
	title: 'Status',
	align: 'left',
	sortable: true,
	cellStyle: function(value){
		if(value==1){
			return { classes: 'success' };
		}else{
			return { classes: 'danger' };
		}
		
	},
	formatter:function(value){
		return (value == 1) ? 'pagado' : 'por pagar';
	}
}]
```

Any suggestion? Thanks.

**Comment by wenzhixin** [comment]
Fixed this issue: http://issues.wenzhixin.net.cn/bootstrap-table/#221.html

**Comment by godshades** [comment]
> Fixed this issue: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/221.html

hi, I'm create column in js, how to use cellStyle property

```
$el.bootstrapTable('destroy').bootstrapTable({
                columns: [header, header2],
                data: data,
            })
```
