### ISSUE TITLE
Hide/show Columns does not work with table footer (tfoot)

### ISSUE THREAD

**Issue by gyermolenko** [wenzhixin/bootstrap-table#2210]
1. create table with footer and data-show-columns="true"
2. show/hide any column 
   http://jsfiddle.net/gyermolenko/a2sk4j2q/1/

Expected: corresponding footer elements should hide/show respectively
Actual: all footer cells are always visible

**Comment by chOOnz** [comment]
I noticed this, too. Is there a way to fix it until the lib has been updated?

**Comment by chOOnz** [comment]
Is this going to be fixed someday? Seems like a very small fix to me but I'm too lazy to look deeper into the JS.

**Comment by wenzhixin** [comment]
Any pull request is welcome

**Comment by JEkedorff** [comment]
In case someone can't wait until properly solved in the source.

I did a quick-fix in my project code by making a custom function to update the footer visibility:
```

function updateTableFooterVisibility(targetTable)
{
	var hiddenCols = targetTable.bootstrapTable('getHiddenColumns');
	if(!hiddenCols.length)
	{
		return;
	}
	
	var footerColumns = targetTable.find('tfoot td');
	if(!footerColumns.length)
	{
		return;
	}
	
	footerColumns.show(); //show all first
	
	$.each(hiddenCols, function(){
		
		var columnIndex = this.fieldIndex || null;
		if(columnIndex === null)
		{
			return;
		}
		
		//hide the corresponding footer column, if exists
		if(typeof footerColumns[columnIndex] !== 'undefined')
		{
			$(footerColumns[columnIndex]).hide();
		}

	});
}

```

Called from:

```
//initial hiding footers of pre-hidden columns
updateTableFooterVisibility(targetTable);

//update once user show/hide any column 
targetTable.on('column-switch.bs.table', function (event, field, checked) {

		updateTableFooterVisibility(targetTable);
		
});
```
