### ISSUE TITLE
Preserve a data attribute (i18n in this case)

### ISSUE THREAD

**Issue by mrv777** [wenzhixin/bootstrap-table#2212]
Hello,

I was looking and this was the best reference to what I'm looking for:
#1269

I'm looking to just preserve the data-i18n attribute for <th> elements.  I feel like this should be possible and be not too complicated.  I would think that would allow i18next to still work on column headers then which would be great!

Edit: Or if there could be a pre-header.bs.table event.  That way I can apply the translations with a page reload before the header is made

Thanks!

**Comment by djhvscf** [comment]
There is not a pre-header event, remember that any **PR** is welcome

**Comment by wenzhixin** [comment]
ref #2089

**Comment by wenzhixin** [comment]
#2089 the extension can help?

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/index.html#extensions/i18n-enhance.html
