### ISSUE TITLE
colspan in column header throws error

### ISSUE THREAD

**Issue by chrisch-hh** [wenzhixin/bootstrap-table#2213]
When creating a table from html with a colspan in one column header, I get an error:

> TypeError: that.columns[i] is undefined in var field = that.columns[i].field; Line 640 bootstrap-table.js

I'm using this html code:

```
<table data-toggle="table">
  <thead>
    <tr>
      <th colspan="2">Item ID</th>
      <th>Item Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Item 1</td>
      <td>$1</td>
    </tr>
  </tbody>
</table>
```

Am I missing something or is this a bug?

**Comment by wenzhixin** [comment]
You need two id field?

**Comment by chrisch-hh** [comment]
No I don't need two fields for an id. I've taken just the example code from the bootstrap-table website. 
But I need the colspan feature for my tables and the question is if the error destroys some of the bootstrap-table functionality or is the error message unimportant and has no further side effects?

**Comment by wenzhixin** [comment]
Try this?
```html
<table data-toggle="table">
  <thead>
    <tr>
      <th colspan="2">Item</th>
      <th>Item Price</th>
    </tr>
    <tr>
      <th data-field="id">Item ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Item 1</td>
      <td>$1</td>
    </tr>
  </tbody>
</table>
```

**Comment by DSynergy** [comment]
I've also run into this same issue when adding a colspan to the last <tr> row in the <thead>. The colspans work correctly in previous <tr>s in the <thead>

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by 1v** [comment]
http://jsfiddle.net/e3nk137y/7795/

**Comment by Luizgpp** [comment]
I still get this error. Any solution?

**Comment by 1v** [comment]
@Luizgpp there is no.

**Comment by wenzhixin** [comment]
We only support the field column with colspan="1".
