### ISSUE TITLE
Pagination & Custom Query Parameters

### ISSUE THREAD

**Issue by joshbenhamou** [wenzhixin/bootstrap-table#2214]
I'm using a server side filter system that is separate to the filter control plugin. When a user applies a filter, I update the table as follows:

`$table.bootstrapTable('refresh', {
                    silent: true,
                    query: {
                        filter: '',
                    }
                });`

The issue is as follows:
1. When changing page or page size the above configuration is lost
2. When the above configuration is applied, the offset stays on the previous page even though the data changes.

**Comment by joshbenhamou** [comment]
The current workaround for 1 is to set the parameters in the query params function supplied in the initial config. The custom config is not supplied in the parameters but by a namespace/global variable.
For 2, once any custom config is applied, force the move to the first page.
Neither are particularly elegant but fix the issues. I'll leave it open as these are just workarounds.

**Comment by Falseee** [comment]
I close this issue because its amlost 3 years old, if this issue still exists pls reopen this issue.

**Comment by freud14** [comment]
Hi, issue 1 is still there. I don't consider 2 to be an issue personally.
