### ISSUE TITLE
一个页面2张表会造成data源排序错乱

### ISSUE THREAD

**Issue by jackie88558** [wenzhixin/bootstrap-table#2215]
我在初始化table的时候设置了sortName，想让table以卡号进行排序，显示出来的排序也是完全正确的，但是当我使用
window.operateEvents = {
	'click .detailButn': function (e, value, row, index) {...}
}
获取行数据的时候，发现row的数据根本不是该行的数据。通过一段时间的研究我发现这里row的数据应该是执行了
$("#sheetTable").bootstrapTable('getData')
这样的代码获取了table数据源后，取数组第index个拿到该行数据的，那么问题就出在这个数据源上，通过调试我发现，第一次load完之后页面虽然显示排序了，但是我的数据源并没有排序，那么造成的问题是，我取第index个取的是未排序的第index个，当然就不是我点击行的数据了。
但是我发现如果在load之后，点击某列表头，让数据重新排序一下，那么
$("#sheetTable").bootstrapTable('getData')
取得的数据源的排序和显示的排序一致了。
不知道有什么办法可以解决这个问题？让表格第一次load排序的时候也把数据源排好序。

**Comment by jackie88558** [comment]
我将数据源先排了序，再load进去，怎么在取数据源的时候发现依然是非排序的？！！！这还怎么玩儿啊。。。哭晕在厕所啊。。。。

**Comment by jackie88558** [comment]
跟了一下源代码，发现了可能的问题
BootstrapTable.prototype.initData = function (data, type) {
        if (type === 'append') {
            this.data = this.data.concat(data);
        } else if (type === 'prepend') {
            this.data = [].concat(data).concat(this.data);
        } else {
            this.data = data || this.options.data;
        }

        // Fix #839 Records deleted when adding new row on filtered table
        if (type === 'append') {
            this.options.data = this.options.data.concat(data);
        } else if (type === 'prepend') {
            this.options.data = [].concat(data).concat(this.options.data);
        } else {
            this.options.data = this.data;
        }

        if (this.options.sidePagination === 'server') {
            return;
        }
        this.initSort();
    };
这个方法在load data的时候调用了2次，第一次完全正确，我数据源13条数据很正确地排了序。第二次调用的时候就出问题了，进来的data参数只有10条数据。页面上最终显示的是13条，是正确的，所以我怀疑就是第二次调用出了问题，这10条排序完了之后，剩下的3条又不知道哪里插入了进去，最终显示13条。
这边我开始怀疑是不是和分页有关（分页我没有设置，应该default是关闭的吧，页面上也没有显示分页相关的东西，我也不需要分页），因为似乎分页默认第一页是10条吧？是不是有点联系，我再看看。

**Comment by jackie88558** [comment]
我又做了一个尝试，之前我是先load详细table，然后load top10 table。现在我交换了一下load顺序，先load top10，这样就不会错了（应该是后表排序把前表给覆盖了，但是我前表没用排序，所以显示没有错），作者请看一下源码到底是为何影响的吧，我这边算是找了个旁门左道给弄好了，但是源代码一定是有bug的，我两张表两个数据源，并且表的id都是不一样的，甚至我的top10表禁用了排序（设置了sortable为false），为何会有排序互相影响的问题。

**Comment by wenzhixin** [comment]
能不能提供下 jsfiddle 例子呀？

**Comment by jackie88558** [comment]
https://jsfiddle.net/5h49dxfj/2/
因为是公司开发的项目，很抱歉我只能贴了js的部分代码，但是整个加载table的过程我都贴上了，按您的水平一定看得懂，请先看一下分析分析，谢谢。

**Comment by wenzhixin** [comment]
能不能提供可以运行的代码呢， ref #1765

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
