### ISSUE TITLE
how to set the footer format of the table?

### ISSUE THREAD

**Issue by gwjwin** [wenzhixin/bootstrap-table#2217]
Hi,
can somebody give me an example of how to use footer? I have tried this:
https://jsfiddle.net/zjhfh3p6/
but the footer is unformat, even I have used `data-falign='center'`
Thanks!

**Comment by jackie88558** [comment]
try setting falign in js
http://issues.wenzhixin.net.cn/bootstrap-table/
pay attention to var columns,set attribute like that.

**Comment by gwjwin** [comment]
Thanks, I haven't try this, but why `data-falign='center'` has no effect? I am using PHP to generate table contents, so I want to set attribute in <TAG> not in js.

**Comment by kolupaevri** [comment]
@gwjwin There is a small bug in your jsfiddle - it is not a `data-showFooter='true'`. It shoud be `data-show-footer='true'`.

As I understand there is no tfoot parse yet.

**Comment by gwjwin** [comment]
thanks kolupaevri, your fix works, 
but still has problems:
1. the tfoot looks like a normal row now, which has mouse hover effect. (I want tfoot looks like thead, bold & no hover effect)
2. the tfoot cell border not align with the td rows: https://jsfiddle.net/2okdmz61/2/

**Comment by wenzhixin** [comment]
Fixed in the latest version.
https://examples.bootstrap-table.com/index.html#options/show-footer.html
