### ISSUE TITLE
Export specific column

### ISSUE THREAD

**Issue by dobobaie** [wenzhixin/bootstrap-table#2218]
Hi,

Can i export a specific column?
I would like to export "name" and "description" from my table ("name", "price", "description", ...)

EDIT: I found 
`exportOptions: {
                ignoreColumn: [1],
            },`

But how i can export a column when visible = false ?

**Comment by oghenez** [comment]
Hello, was this eve solved?

**Comment by wenzhixin** [comment]
I think you can modify the export extension code to use showColumn before export.
