### ISSUE TITLE
Exporting selected rows does not work when data-pagination-side is set to server

### ISSUE THREAD

**Issue by sampeka** [wenzhixin/bootstrap-table#2220]
Experiencing a problem with the export plugin. The selected rows are not obeyed when data-side-pagination is set to server - here's a jsfiddle illustrating the issue: http://jsfiddle.net/e3nk137y/6074/. 

## Steps to reproduce
1. Select "Export Selected" in the dropdown menu at the top left.
2. Select some rows
3. Export as csv

**Comment by david2sim** [comment]
I have the same problem

**Comment by dabros** [comment]
So the core issue appears to be how server side pagination doesnt like `.load` of `getAllSelections`, in that I mean it seems to completely ignore it.

http://jsfiddle.net/dabros/axsuvcg1/

See `export` at https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/export/bootstrap-table-export.js#L99

See `getAllSelections` at https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L2578

See `load` at https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L2321

My fiddle shows current testing progress, and we can assume `load` works correctly with client side as seen in http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html (breakpoints in source panel would be all thats needed to completely confirm that)

I might get round to this again later, but busy schedule so anyone else feel free to pursue further :)

**Comment by sampeka** [comment]
Thanks @dabros, that was really helpful. If I get a chance tonight I'll try and put together a PR with your pointers, but feel free to beat me to it

**Comment by sampeka** [comment]
@dabros do you have any ideas how to fix the "export all" function when the `data-side-pagination` is set to server?

**Comment by dabros** [comment]
@sampeka - ive seen #2220, can you please provide a fiddle with changed file included in js panel (be sure to check the 'wrap' option) and all other conditions like `data-side-pagination` set for testing?

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

I can then take a look and ideally contain changes in js panel with `// CHANGED` comments so quicker testing process

**Comment by heenaMahajan** [comment]
how to "export all" function when the data-side-pagination is set to server?it current export current page records

**Comment by dabros** [comment]
@heenaMahajan - please be cautious posting to closed issues, if you still looking for a solution then create new issue and link it to here
