### ISSUE TITLE
Next Release Date ?

### ISSUE THREAD

**Issue by DustinUtecht** [wenzhixin/bootstrap-table#2221]
When will the next Master Version come out? 
I need it to fix #2091 (https://github.com/wenzhixin/bootstrap-table/pull/2106)

**Comment by wenzhixin** [comment]
You can first use the development version: https://github.com/wenzhixin/bootstrap-table/tree/develop/src first.

**Comment by DustinUtecht** [comment]
I dont want to use a dev Version from any libraries...
Dev is Dev (e.g. sometimes buggy)

**Comment by wenzhixin** [comment]
OK, now I am testing the dev version.

**Comment by DustinUtecht** [comment]
Sorry i mean some Dev version can be buggy

**Comment by DustinUtecht** [comment]
Some news ?

**Comment by DustinUtecht** [comment]
up

**Comment by fenichelar** [comment]
How's the testing going? ETA on release?

**Comment by DustinUtecht** [comment]
up

**Comment by raku** [comment]
@wenzhixin When will you make a new release?

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/releases/tag/1.11.0
