### ISSUE TITLE
How to cancel 'changing of value' in bootstrap-table editable

### ISSUE THREAD

**Issue by sominlee74** [wenzhixin/bootstrap-table#2222]
Hi, 

I am trying to make some code using Bootstrap-Table with editable. For some reason, I would like to put another 'confirmation' process before actually sending update request to server in "url"'s function part below. As you see, 'Type" column uses 'select' type, and use 'url' option to send update request.

My first try was to use 'bootbox.js (ref: bootboxjs.com) to make a decision on whether running $.ajax part or not. It just works partially. Sending request is stopped, but bootstrap-table's cell text was changed. I want to reset the change of cell text when I cancel in bootbox.confirm() code.

What am I supposed to do? Fortunately, I found the way to find out 'previous value' by using "$(this).text()", and new value is stored in 'params' object.  I just need to reset the change of cell text in 'table' in DOM object. 

(partial code)

```
   $table.bootstrapTable({
           url: '/routeList/' + curPrjCode,
           cache: false,
           columns: [
           {
                   title: 'Type',
                   field: 'type',
                   align: 'left',
                   editable: {
                       type: 'select',
                       source: function() {
                           var options = [];
                           var source = ['service','maintenance'];
                           for (var index in source) {
                               var value = source[index];
                               options.push({
                                   value: value,
                                   text: value
                               });
                           }
                           return options;
                       },
                       url: function (params) {
                           params['prjCode'] = chkPrjCode;
                           params['gameName'] = chkGameName;
                           params['version'] = chkVersion;

                           var previousValue = $(this).text();

                          bootbox.confirm("Are you sure?", function() {
                               $.ajax({
                                   method: "POST",
                                   url: "/routeUpdate",
                                   data: params
                               }).done(function (res) {
                                   $table.bootstrapTable('refresh');
                                   alertBox('success');
                               }).fail(function (err) {
                                   $table.bootstrapTable('refresh');
                                   alertBox('Error: ' + err.responseText);
                               });
                       }
                   }
              }] 
   });
```

**Comment by dabros** [comment]
@sominlee74 

As you can see in https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable, the editable extension just provides a bridge to use [X-Editable](http://vitalets.github.io/x-editable/docs.html) plugin, which is FAR more widely used than just this.

A quick google of "x-editable confirm javascript" showed many possible options for exactly your issue.

Also, do keep in mind that this (as i read it) is not a bug or core feature request (per say), rather a question for a completely third party plugin, the guidelines in https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker recommended such topics be pursued on [SO](http://stackoverflow.com).

I'd recommend researching what i suggested above, then adding any useful links here or even key code samples for others, but that this really belongs on [SO](http://stackoverflow.com) if still having further issues then, just linking to it from here (and visa-versa) to help others find it.

As I said, seems to have many solutions out there, at most I would expect you just pass extra `editable` param through (see https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable#editable-1).

**Comment by sominlee74** [comment]
@dabros 

Thanks for commenting. In fact, I already read the guide lines, and I tried to search about '`x-editable` and related things in StackOverflow and others. I found there might not be a clear explanation about the internal mechanism such as the processing procedures and how they works. 
(I only understood the processing steps between functions. They run as following steps; `validate -> params -> url -> source -> display` )

I also tried `validate` function, but it couldn't stop changing the text (in `type` column) in my trial. But, its value can be roll backed (I checked it with `$(this).edtiable('getValue',true)`.

However, I might make a mistake in using `validate`. I will try again, and I will post the result.

**Comment by sominlee74** [comment]
@dabros 

Hi, I think I need to change my question into different one (related, but slightly different). As you said, bootstrap-table's "editable" extension might be just a bridge.  As for now, I am not quite sure if I need to create an issue in bootstrapTable or in x-editable for my case.  If possible, I would like to get an response about if this is about bootstrap-table or about x-editable.

Here is my issue situation below.
When I tried below code, `data-value` is changed as my intention, but displayed text is not changed.

As you can see, this "type" is of select type. 
1. Original state had been "service"
 Table TD element was 
`<a href="javascript:void(0)" data-name="type" data-pk="undefined" data-value="service" class="editable editable-click">service</a>`
2. I changed it into "maintenacne" at web brower(Chrome)

3. the code below changes the value into "service" again with `'$(this).editable('setValue', 'service',true)`  but displayed text wasn't changed.

TD element shows `<a href="javascript:void(0)" data-name="type" data-pk="undefined" data-value="service" class="editable editable-click" data-original-title="" title="" style="background-color: rgba(0, 0, 0, 0);">maintenance</a>`

data-value is set as 'service, but inner text par is still 'maintenance'

console.log in the code shows 
```
before setValue
$(this).editable("getValue",true):  service
$(this).text():  service
After setValue
$(this).editable("getValue",true):  service
```

Conclusion: Please let me know if this is an bootstrapTable issue or not. If this is related x-editable, I will focus on x-editable. 

Thanks.
 
(code)
```
$table.bootstrapTable({
  url: '/routeList/' + curPrjCode,
  cache: false,
  columns: [{
    title: 'Type',
    field: 'type',
    align: 'left',
    editable: {
      type: 'select',
      source: function() {
       var options = [];
       var source = ['service','maintenance'];
       for (var index in source) {
           var value = source[index];
           options.push({
               value: value,
               text: value
           });
       }
       return options;
      },
      url: function (params) {
       params['prjCode'] = chkPrjCode;
       params['gameName'] = chkGameName;
       params['version'] = chkVersion;

       var previousValue = $(this).text();

       console.log('before setValue');
       console.log('$(this).editable("getValue",true): ', $(this).editable('getValue',true));
       console.log('$(this).text(): ', $(this).text());
       
       $(this).editable('setValue', 'service',true);
       
       console.log('After setValue');
       console.log('$(this).editable("getValue",true): ', $(this).editable('getValue',true));
      }
    }
  }]
});
```

**Comment by dabros** [comment]
@sominlee74 - i will try to look into this more, cant atm as busy schedule

But what your lacking is a jsfiddle showing editable with the validate solution that comes up first when searching for this "x-editable" issue.

Maybe bootstrap issue if reverting values, but we need a working fiddle showing bug

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Doesnt have to be your data, look at that editable example/s found at the following:

http://bootstrap-table.wenzhixin.net.cn/extensions/
http://issues.wenzhixin.net.cn/bootstrap-table/
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html

**Comment by sominlee74** [comment]
Thanks for commenting, @dabros. I will try with 'x-editable'  and 'bootstrap' for the time being.

If I would find the reason and solution, I will share it here for others.

Thanks again.

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by UtechtDustin** [comment]
I close the issue because we got no response from you. If you still need help pls reopen the issue.
