### ISSUE TITLE
如何定义表格查询框对应需要查询的列

### ISSUE THREAD

**Issue by mataoxf** [wenzhixin/bootstrap-table#2225]
由于后台做通用处理接口，因此，前端需要查询哪几个列值。
请问bs-table里哪个配置项对应查询的配置。

**Comment by wenzhixin** [comment]
现在的搜索框是全局的，不支持配置，你可以考虑自定义 toolbar：
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html
或者使用这个扩展：http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/toolbar.html
