### ISSUE TITLE
Method called on onPostBody event

### ISSUE THREAD

**Issue by Dimigergo** [wenzhixin/bootstrap-table#2226]
Hi!

I use the following code:
`onPostBody: function () {`
`    var rowData = $('#tblAccountList').bootstrapTable('getRowByUniqueId', 1);`
`    console.log("RowData: " + JSON.stringify(rowData));`
`},`
In this situation the JSON.stringify throw exception because the rowData is not the data, 
When I try to log with rowData.text() all of the table string will logged.

Thanks!

**Comment by wenzhixin** [comment]
Can you provide a jsfiddle to show your problem because [our example](http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getRowByUniqueId.html) is working well.

**Comment by Dimigergo** [comment]
Hi!

This is an example, with the bug:
[https://jsfiddle.net/fnwumtvg/5/](url)

In the console, you can see the rowData contains wrong data, instead of the first row from the JSON data (AcId=70).

Hope this helps!
Thank you very much.

**Comment by kolupaevri** [comment]
The thing is you are tryng to use bootstrapTable method inside it's own initilization.
You can use direct access to the data in your onPostBody.

```javascript
onPostBody: function () {
	var uniqueId = this.uniqueId;
	var rowData = $.grep(this.data, function(n,i) { return n[uniqueId] == 70;})[0];
	console.log(rowData); 
},
```

**Comment by wenzhixin** [comment]
Just like what @kolupaevri said, you can try the solution of @kolupaevri or try this: https://jsfiddle.net/fnwumtvg/7/

**Comment by Dimigergo** [comment]
Thanks, it worked! :)
