### ISSUE TITLE
Not all row has detailView

### ISSUE THREAD

**Issue by Dimigergo** [wenzhixin/bootstrap-table#2227]
Hi!

It is very comfortable to me that not all row must have detailView. If there is no detailView, the +/- icon doesn't need. 

I think, It is a good solution, if there is a possibility to style detailView cell with row data and index parameter.

Thanks in advance!

**Comment by dabros** [comment]
@Dimigergo - use web tools (F12, https://developer.chrome.com/devtools, all browsers have comparable) to see that index (and `data-unique-id` if passed as table param) is printed for each row, and row contents can be derived by using `getRowByUniqueId` (http://bootstrap-table.wenzhixin.net.cn/documentation/#methods)

I have no idea what you want, but whatever it is can be done easily via basic jquery inside the `onPostBody` event (http://bootstrap-table.wenzhixin.net.cn/documentation/#events).

Google and research what your actually trying to do, then place it there. 

If you need more help then this needs to be a core feature request or bug report, and absolutely needs a jsfiddle 

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by Dimigergo** [comment]
Hi! 

You absolutely all right, that is why I opened the #2226 issue. I would like to use the onPostBody event with the getRowByUniqueId method, but I had the mentioned problem.
It will be perfect for me, and I will make a jsFiddle example for the other issue, and close this issue.

Thank you!
