### ISSUE TITLE
about #1748 rowspan and colspan  show column

### ISSUE THREAD

**Issue by yangyachao** [wenzhixin/bootstrap-table#2230]
当合并列在其他列前面时出现此问题，需要重新计算合并列colspan
![1](https://cloud.githubusercontent.com/assets/4145688/14874291/34482c04-0d31-11e6-9ba3-e1a149df0750.png)
![default](https://cloud.githubusercontent.com/assets/4145688/14874290/33cfb7f6-0d31-11e6-8d0f-dd31574636fc.png)

**Comment by wenzhixin** [comment]
谢谢反馈，这个问题早上刚刚修复，develop 上

**Comment by yangyachao** [comment]
这个问题好像没有解决

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/ 你是指这里？

**Comment by yangyachao** [comment]
用最新的develop也是截图的效果，截图是我本机的，就把item id 那一列放在item detail 后面，然后在隐藏item price那列，就出现错位了

**Comment by wenzhixin** [comment]
OK, 有空试下。

**Comment by yangyachao** [comment]
我暂时的解决方案是： 
列配置中加入 colgroup 和 parent
![colgroup](https://cloud.githubusercontent.com/assets/4145688/14976864/06005da2-1142-11e6-8f9b-f7b48b54eb6f.png)

BootstrapTable.prototype.toggleColumn 中加入
` this.columns[index].visible = checked;

        var parent = this.columns[index].parent;

        if (parent != undefined) {
            //TODO:YYC 隐藏列
            $.each(this.options.columns, function (i, columns) {
                $.each(columns, function (j, column) {
                    if (column.colgroup == parent) {
                        if (checked) {
                            column.colspan = parseInt(column.colspan) + 1;
                        } else {
                            column.colspan = parseInt(column.colspan) - 1;
                        }

                        if (column.colspan <= 0) {
                            column.visible = false;
                        } else {
                            column.visible = true;
                        }

                        //alert(JSON.stringify(column));
                    }
                })
            });
        }

        this.initHeader();`

**Comment by bmrainc** [comment]
恩，你这只是改了在动态修改列数时的操作，当初始化列表时，colspan没有减去隐藏的列，这也是个问题啊，不知在哪里修改。
![image](https://cloud.githubusercontent.com/assets/7332588/17992736/9151fe26-6b7c-11e6-94a0-b4af611bdfc3.png)

**Comment by bmrainc** [comment]
@yangyachao

**Comment by yangyachao** [comment]
在 BootstrapTable.prototype.initHeader 里修改
![table](https://cloud.githubusercontent.com/assets/4145688/17993324/660fc05e-6b81-11e6-9172-3c828950ae16.png)

**Comment by yangyachao** [comment]
我这里好像没这个问题 试下我这个版本
[bootstrap-table.zip](https://github.com/wenzhixin/bootstrap-table/files/438488/bootstrap-table.zip)

**Comment by yangyachao** [comment]
那个暂时就只能在配置里修改了

**Comment by wenzhixin** [comment]
经过确认，这个问题与 #2051 应该是同个问题，先关掉这个问题，统一在 #2051 中修改。
