### ISSUE TITLE
Custom export links outside table or in Toolbar, How?

### ISSUE THREAD

**Issue by anupalusoft** [wenzhixin/bootstrap-table#2234]
Hi,

Just curious to learn that is it possible i can create custom links in toolbar with `data-type="json"` OR `data-type="excel"` to export directly ? I tried it but didn't work. 

Any way to do this?
Thanks

**Comment by djhvscf** [comment]
You mean something like a button?

**Comment by anupalusoft** [comment]
@djhvscf  Yeah kind of custom button outside the table or in toolbar. Is that possible?

**Comment by dabros** [comment]
@anupalusoft - custom toolbar is easy, and setting a click handle for new button would be a simple matter of `onPostHeader` or `onResetView` callback, though other approaches exist too.

The code to place in that click handle would be the trick, but just look at what export actually does for a second, as i explored lightly in #2220

Specifically, look at `doExport` and similar code here: https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/export/bootstrap-table-export.js#L84

`that.$el.tableExport()` is key function, with a call to `togglePagination` or `load` or similar needed to remove pagination or load just selections while export in progress, so exports desired subset.

Mimicing that code in a callback is entirely possible, all key functions are accessible from a callback using `this` or full `$table.BootstrapTable` and `$table.tableExport` accessors.

To force datatype, just pass in relevant [Export Options](https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/export) direct when calling `.tableExport`

Then done, not really that hard at all id imagine.

If you do try and get stuck (and do try first, 94% of the code you need is already there, and 5% a quick google search away) then please provide fiddle with matching conditions and your progress so far.

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
It is easy to do this, for example like this: http://jsfiddle.net/wenyi/wc0zLpef/1/.

**Comment by JonnyBananas** [comment]
hi wenzhixin, i have a problem i hope you can help me, the problem is the following.

I have a web application hosted in GAS, I have added all the data table plugins, but personally the plugin of data-show-export has not worked for me. this the code:

<div id="toolbar">
  <button id="export" class="btn btn-success">Excel</button>
</div>
<table id="table" class="table table-striped table-bordered table-hover" data-toggle="table" data-toolbar="#toolbar" data-sort-name="descripcion" 
                            data-sort-order="asc" data-show-export="true" data-url="/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data1/" 
                            data-row-style="rowStyle" data-search="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true"
                            data-sort-name="numerodeparte" data-sort-order="ubicacion" data-url="http://issues.wenzhixin.net.cn/examples/bootstrap_table/data"
                            data-url="/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data1/"
                            data-url="https://api.github.com/users/wenzhixin/repos" data-query-params="queryParams" data-pagination="true" data-height="600">
                            <thead>
                                <tr>
                                    <th data-field="state" data-checkbox="true"></th>
                                    <th data-field="numerodeparte" data-sortable="true">Numero de Parte</th>
                                    <th data-field="descripcion" data-sortable="true">Descripcion</th>
                                    <th data-field="especificacion" data-sortable="true">Especificacion</th>
                                    <th data-field="presentacion" data-sortable="true">Presentacion</th>
                                    <th data-field="cantidad" data-sortable="true">Cantidad</th>
                                    <th data-field="numerodeserie" data-sortable="true">Numero de Serie</th>
                                    <th data-field="fechadeentrada" data-sortable="true">Fecha de Entrada</th>
                                    <th data-field="ubicacion" data-sortable="true">Ubicacion</th>
                                </tr>
                            </thead>
                            <tbody>
                                <? for (var i = 0; i < data.length; i++) { ?>
                                    <tr>
                                        <? for (var j = 0; j < data[i].length; j++) { ?>
                                            <td>
                                                <?= data[i][j] ?>
                                            </td>
                                            <? } ?>
                                    </tr>
                                    <? } ?>
                            </tbody>
                    </table>



<script>
$(function () {
	var $table = $('#table');
	$('#export').click(function () {
  	$table.tableExport({
      type: 'excel',
      escape: false
    });
  });
});
</script>

remove a lot because it does not lack, as I mention this is the only plugin that does not work everything else excellent.

**Comment by dabros** [comment]
@JonnyBananas - that feels like a different issue, so no suprise no reply on closed topic. Please open new issue if still a problem, and be cautious with closed posts, often better to open a new one and just link using #[issue-id] or full url even :)

**Comment by JonnyBananas** [comment]
thank you very much, I already solved it.

**Comment by baihaqyaviq** [comment]
just call internal method from extension:
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/export/bootstrap-table-export.js#L179

`$('#export').on('click', function (e) {
			$table.bootstrapTable('exportTable', {
				type: 'excel',
				escape: false
			});
		});`
