### ISSUE TITLE
empty cell style

### ISSUE THREAD

**Issue by joefreire** [wenzhixin/bootstrap-table#2235]
Hi, how i can style a empty cell like a red style?

thank you for your help

**Comment by djhvscf** [comment]
You can use the cellStyle column option (data-cell-style or cellStyle it depends if you are use the data-* configuration or the javascript configuration) like this:

```js
function cellStyle(value, row, index) {
  return {
    classes: 'text-nowrap another-class',
    css: {"color": "blue", "font-size": "50px"}
  };
}
```
