### ISSUE TITLE
Get cookie to save toolbar advancedSearch

### ISSUE THREAD

**Issue by patrickpereira** [wenzhixin/bootstrap-table#2238]
I want to save my advancedSearch in the cookie, that's currently not possible - do you know an easy way I could accomplish this?

Best regards

**Comment by djhvscf** [comment]
Please include the cookie extension file in your page https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/cookie

And in your code use like this


```js
//this - > it is the bootstrap-table object
//you must set the **cookie** option to True
//you must set the **cookieIdTable** to your table name

//Set your cookie
$.fn.bootstrapTable.utils.setCookie(this, yourCookieNameVar, yourCookieValueVar)

//Get your cookie
$.fn.bootstrapTable.utils.getCookie(this, yourTableIdName, yourCookieName)
```

**Comment by djhvscf** [comment]
@patrickpereira the example code is edited
