### ISSUE TITLE
natural-sorting not work when data including numeric number, null or undefined.

### ISSUE THREAD

**Issue by t02uk** [wenzhixin/bootstrap-table#2239]
Hi.

The extension natural-sorting throw the following exception when the data including numeric number.
`bootstrap-table-natural-sorting.js:21 Uncaught TypeError: t.charAt is not a function`

And when the data including null or undefined, the plugin throws similar exception too.

Please confirm jsfiddle: 
https://jsfiddle.net/t02uk/dm8151ff/

Thank you.

**Comment by jjaroska** [comment]
I am having a problem applying natural sorting while defining the bootstrap table completely in javascript.  it does not seem to do anything.  here is a portion of the code.  And yes, I have included the natural sorting extension in the page.

$(function () {
			$('#docTable').bootstrapTable({
				url: '@Url.Action("GetDocuments")?projectId=0&documentTypeId=0',
				idField: 'PrimaryKey',
				uniqueId: 'PrimaryKey',
				sortName: 'UploadDate',
				sortOrder: 'desc',
				showRefresh: true,
				toolbar: '#docToolbar',
				search: true,
				height: 750,
				columns: [{
					field: 'Selection',
					checkbox: true,
					formatter: selectionFormatter
				}, {
					field: 'Filename',
					title: 'Filename',
					sorter: alphasort,
					formatter: filenameFormatter,
					sortable: true
				}, {
					field: 'Description',
					title: 'Description',
					sortable: true
				}, {
