### ISSUE TITLE
updateRow无法更新使用formatter的列的值

### ISSUE THREAD

**Issue by zhang852774731** [wenzhixin/bootstrap-table#2241]
```
$('#table').bootstrapTable({
            data:point_data,
            columns: [

                {
                    field: 'state',
                    checkbox: true,
                    align: 'center',
                    valign: 'middle'
                },

                {
                    field: 'name',
                    title: '城市'
                },
                {
                    field: 'lon',
                    title: '经度'
                },
                {
                    field: 'lat',
                    title: '纬度'
                },
                {
                    field: 'datetime',
                    title: '日期',
                    formatter: function(value,row){
                        return row.forecasts[0].datetime;
                    }
                },
            ]
        });
```
---------------------
使用formatter定义的datetime列，更新row数据使用updateRow方法，构造row对象为：
```
{
     index:1,
     row:{
         datetime:"20160101"
     }
}
```
无法更新，也没有报错信息。怎么处理，谢谢！

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by zhang852774731** [comment]
Sorry.
the format of my json just like:
`[
    "name":"shenzhen",
    "forecasts":[
          {
           "datetime":"20160503",
           "min":19,
           "max":27
          },
         {
           "datetime":"20160504",
           "min":23,
           "max":27
          }
    ]
]`
it's nested array. I want to make a table to show the 'name' column, and it's one day forecast in a line. 
Like this:
First Header | Second Header | Third Header

| name | datetime | min | max |
| ------------ | ------------- | ------------ |-------|
| shenzhen | 20160503  | 19 |27


Besides, add a button to select the  tomorrow's forecast. But I can't realize it when I read the document. Can you help me?Thanks!

**Comment by wenzhixin** [comment]
Please provide a fiddle example: #1765.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
