### ISSUE TITLE
Select column filter doesn't work due to class conflict (resolved).

### ISSUE THREAD

**Issue by m11gt** [wenzhixin/bootstrap-table#2242]
When using the column filter extension's select filter, I am getting the following error 
Uncaught TypeError: Cannot read property 'length' of undefined in line 41 of bootstrap-table-filter-control.js and the table stops rendering.

I did some digging and found out that name of the filtered column is applied to the select element as a class. When the filter is created, bootstrap-table-filter-control.js looks for elements with the class name matching the column name (Line 204), if you have another element using a class name similar to the column name you are filtering, all those elements will be pulled in and you'll end up with the error I specified above.
If you use console.log(selectControl) on line 204, you'll see the elements pulled in.

![conflict](https://cloud.githubusercontent.com/assets/5625425/14939119/3462420e-0eff-11e6-940f-7f3f47c50721.PNG)

To address this issue, you can narrow down the elements you select by changing 
`selectControl = $('.' + column.field);` to `selectControl = $('select.' + column.field);` on line 204

Here is an example of the issue, http://jsfiddle.net/9c7g64cr/2/

I tested it an it works well. :+1: 

![conflict_fixed](https://cloud.githubusercontent.com/assets/5625425/14939160/840b5952-0f00-11e6-85fe-276f2f1c11f6.PNG)

**Comment by wenzhixin** [comment]
@djhvscf Same error when using develop version: http://jsfiddle.net/wenyi/9c7g64cr/3/.

**Comment by djhvscf** [comment]
Using the fixed version of filter-control and the develop version of bootstrap-table 

http://jsfiddle.net/9c7g64cr/4/

@wenzhixin
