### ISSUE TITLE
apply filters before rendering table

### ISSUE THREAD

**Issue by antonyboom** [wenzhixin/bootstrap-table#2244]
Is there any way to apply filter to data with dot notation? 
For example in plunker I did an array with object where I need to get name thru dot notation, is there way to show filter select with this data?

[Plunker](https://plnkr.co/edit/8Zwebc7ss7bT6orYS0eG?p=preview)

**Comment by djhvscf** [comment]
I'm not sure what you mean about this... Can you explain a little bit more, please?

**Comment by antonyboom** [comment]
@djhvscf updated my post, please check it
