### ISSUE TITLE
filterLocal options no longer exists

### ISSUE THREAD

**Issue by raphaelriehl** [wenzhixin/bootstrap-table#2245]
Hi,

I'm interesting by filterLocal option ([commit c496531](https://github.com/wenzhixin/bootstrap-table/pull/1683)). But since the [commit deebc41](https://github.com/wenzhixin/bootstrap-table/commit/adee27d8da0e786424350fd52789cbcd2a20bd71) (18 january 2016), this option no longer exists.
It's probably because an old file has to merged. I think, another commits were lost.

Is it possible to fix this problem ? Thanks. :)

**Comment by djhvscf** [comment]
Ok, I think this option was causing some errors but let me think if we can add it again to our extension

**Comment by djhvscf** [comment]
We won't support this feature
