### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by Dre-amer** [wenzhixin/bootstrap-table#2246]
您好！
请问一下，Bootstrap加载数据源，只能把参数放到url中吗

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by Dre-amer** [comment]
Sorry, 
using URL to get the DataSource of Bootstrap need some parameters, but I don't know where to put them.
(If I put those parameters into the url, It will limit the style of those parameters)

**Comment by wenzhixin** [comment]
#1765 
* Table from html: http://jsfiddle.net/wenyi/e3nk137y/11/
* Table from data: http://jsfiddle.net/wenyi/e3nk137y/13/
* Table from url: http://jsfiddle.net/wenyi/e3nk137y/14/
