### ISSUE TITLE
Set own value & data-formatter?

### ISSUE THREAD

**Issue by Fruchtgummi** [wenzhixin/bootstrap-table#2247]
Hi,

Set own value on column and commit with data-formatter?

for example:

 `<th data-field="" class="norowclick" data-formatter="myFunction" data-events="operateEvents" data-myownvalue="myvalue">Optionen</th>`

get on js-function

```
function myFunction(value, row, index) {

   //get my own value?


```}

**Comment by djhvscf** [comment]
You mean that the function `myfunction` should receive all the `data-*` attributes used in the `th` declaration

**Comment by Fruchtgummi** [comment]
Yes! The value in myfunction ist UNDEFINE. The value row ist the row from my dataset.. I haven't access on data-* attributes in `<th>`

**Comment by Fruchtgummi** [comment]
AHHH okay `$(this).data()` give me my value... 

Finish
