### ISSUE TITLE
issue: cannot get table id from pagination module when changing page

### ISSUE THREAD

**Issue by MI53RE** [wenzhixin/bootstrap-table#2248]
I tried to look everywhere but I couldn't find a solution... :(

I'm having several tables in my page (of course using bootstrapTable) however I need to do some filtering operations that change the state of the current page in the table.

I need to do this when i'm changing page too but, as of now, I do it on every tables when I change page in any table (cannot specify from which table I accept to call the function, while I can target the table the function has to operate on).

That is because I cannot get the table id from the pagination module as it seem (for what I did understood) not being attached to the DOM tree so I cannot look into its ancestors to obtain it.

Could you please look into this one, and/or if anyone has a possible workaround/solution I would be very happy tu use it! :)

Cordialy

E.L.

**Comment by wenzhixin** [comment]
Please provide a fiddle.

**Comment by MI53RE** [comment]
sorry not a proper fiddle but just adding the js in your page should do the trick:
https://jsfiddle.net/MI53RE/r93dqc8u/1/
hope this will be enough for you.
You

**Comment by MI53RE** [comment]
I edited the fiddle so it should now work proprely with this example of yours:
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/client-side-pagination.html

(I did forgot that you used iframe in your page so my code couldn't be used anyway. But now it should work fine =) and show normaly what is going wrong)

**Comment by dabros** [comment]
@MI53RE - you didnt update fiddle link

There are jsfiddles linked from the main site and here, for example #1765 and https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Use one of these as your base, and remember the last URI (`/1/`) in link above is version/save number, but you can use 'set as base' (fork it, then may need to refresh page for button to appear) for any version and remove that number from the link.

**Comment by MI53RE** [comment]
@dabros, thank you for the help, I'm not really used of jsfiddle yet^^'
so here is the proper fiddle:

http://jsfiddle.net/MI53RE/k4gtLaxz/2/
with the recap of the comment
```
        console.log(stage1); // return <div class="pull-right pagination">
        var stage2 = stage1.parentNode.parentNode; // cast error because stage1.parentNode is null
        console.log(stage2); // code blocked from previous line so nothing
        var stage3 = stage2.getElementById(tabeId);
        console.log(stage3) // should not be seen because of expected stage2
```

**Comment by dabros** [comment]
@MI53RE

Do see the doco: http://bootstrap-table.wenzhixin.net.cn/documentation/
And examples: http://issues.wenzhixin.net.cn/bootstrap-table/

Here is an fiddle with mulitple tables, one single event handler and clear recognition of which table it was triggered for: http://jsfiddle.net/dabros/0q9rv0dq/

If the `onPageChange` event is not suitable, see doco and examples and find another, stop trying to scrape from DOM when easy methods already exist.

**Comment by MI53RE** [comment]
@dabros Thanks a lot, that is exactly what I was looking for! I did read the doco and example at the time I was asking but didn't see it :/ (maybe need to change my glasses...) 

So the `onPageChange` is definitely what's needed in my case! :)

Issue is then resolved! Thanks again!!!!

**Comment by dabros** [comment]
@MI53RE :+1: 

Please close this issue and do share a bit of your working solution if you dont mind, to help the next wanderer : )

**Comment by MI53RE** [comment]
@dabros Technicaly I merelly copy/pasted the solution you gave me on your last fiddle as it was the shortest way to get what I was needed :)

`$('table').on('page-change.bs.table', function(e,number, size){`
&nbsp;&nbsp;&nbsp;&nbsp;`var tableId = $(this)[0].id;   // where $(this)[0] allow direct access to elem porperties`
&nbsp;&nbsp;&nbsp;&nbsp;`myFunction(tableId); // or anything else you need to do with tableId`
`});`

closing the topic!
