### ISSUE TITLE
How can I set an a tag inside a td?

### ISSUE THREAD

**Issue by jmmolina796** [wenzhixin/bootstrap-table#2249]
I'm trying to put an a tag inside a td, like this:

`<td><a href="www.google.com">Cats</a></td>`

The problem is that when I want to filter something, bootstrap considers the link when I search.
Example: When I type in the input: href
Bootstrap finds all td tags because all of them have a href inside, but I want that only looks for the text inside the td tag, I mean (in this example) "Cats".

Is there any solution? Or I can only put text inside a td tag in Bootstrap table if I want that the search works?

**Comment by dabros** [comment]
@jmmolina796 - the column option `sortName` seems to maybe answer this.

But if that does only affect sorting, then see the `strictSearch` option mentioned #1157 and elsewhere, also there is a `searchFormatter` option but I know this has been answered in past without that, a more thorough search through existing solutions (and google search for stackoverflow posts) should provide more examples if still stuck.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!

**Comment by soiefmail** [comment]
Please reopen this issue.
Fiddle - https://jsfiddle.net/soiefmail/mo9a3cdn/37/
