### ISSUE TITLE
Are we going to support bootstrap v4?

### ISSUE THREAD

**Issue by boydc2014** [wenzhixin/bootstrap-table#2250]
Just start to use this awesome library and wondering are there plans to catch up with bootstrap v4?

**Comment by rpannell** [comment]
There was some talk earlier (https://github.com/wenzhixin/bootstrap-table/issues/1881) but looks like it fizzled out.  v4 is still alpha so I can see where the main developers will be waiting until v4 becomes beta and is getting closer to real version before updating to support it.

**Comment by djhvscf** [comment]
There is something about that: https://github.com/wenzhixin/bootstrap-table/pull/2136 please double check it and if you have any suggestion, please feel free to let us know

**Comment by wenzhixin** [comment]
Supported now.
