### ISSUE TITLE
Quick Quesiton:  search for function?

### ISSUE THREAD

**Issue by rpannell** [wenzhixin/bootstrap-table#2251]
I am not seeing it so I am going to assume no, but just double checking in case I am missing something.  Is there an extension for a function to "find" the data by a set of criteria?  kinda like the "filterBy" function but instead of filtering the data down it actually returns the rows (including the index) the developer is asking for.  I know I can use "getData" and search from that but checking to see if I am missing something.

Easy extension to create if not (working on it currently).

Thanks!

**Comment by djhvscf** [comment]
I think there is not any extension about that, @wenzhixin is that right?

**Comment by rpannell** [comment]
So I created something on our end that would work, but it's so small that it might be best as piece in the main file.  I had to add "searchForRows" in the methods but for what I needed this worked pretty well.  I took what was done for the filterBy and just returned the list of rows that triggered true.  The model would be  { index, row } so that the developer would have access to the index as well.

`BootstrapTable.prototype.searchForRows = function (columns) {
        var filter = $.isEmptyObject(columns) ? {} : columns;
        var filteredRows = [];
        if (filter) {
            $.each(this.options.data, function (index, value) {
                for (var key in filter) {
                    var isFound = false;
                    if ($.isArray(filter[key])) {
                        if ($.inArray(value[key], filter[key]) != -1) {
                            isFound = true;
                        }
                    } else if (value[key] === filter[key]) {
                        isFound = true;
                    }

                    if (isFound) {
                        filteredRows.push({
                            index: index,
                            row: value
                        });
                    }
                }
            });
        }

        return filteredRows;
    };`

I can create an extension or I PR the main project and add this if you think it's something others would use.

**Comment by djhvscf** [comment]
I think the best option is create an extension :) @rpannell

**Comment by dabros** [comment]
@rpannell - in case of help: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests
