### ISSUE TITLE
ID of Table in CalculateObjectValue

### ISSUE THREAD

**Issue by rfossella** [wenzhixin/bootstrap-table#2252]
The _calculateObjectValue_ method fires off the formatter for a column cell.  Is there a way to get the context of the table for which it's formatting?  - i.e. is there a way to (minimally) reference the ID of the table.

Use case: when my custom formatter method/functions fires off I need to reference data from another source based on the table (and ID) that it's formatting.

Thanks.
Rob

**Comment by djhvscf** [comment]
I think @wenzhixin can help you

**Comment by dabros** [comment]
@rfossella - try using `this` inside formatter, and if that doesnt work then pls create a fiddle and @wenzhixin can maybe help you more

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
