### ISSUE TITLE
server side paging value is not displayed

### ISSUE THREAD

**Issue by mctdi** [wenzhixin/bootstrap-table#2253]
I try to use bootstrap-table and do a server side paging
```
<table id="contractorTableResult" style="min-height:200" data-show-header="true" data-classes="table table-no-bordered" data-toggle="table"   data-pagination="true" data-height="230">
    <thead>
    <tr>
    <th data-field="contractorId">#</th>
    <th data-field="contractorName">Name</th>
    </tr>
    </thead>
</table>
```

When i show my tab i do

`$("#contractorTableResult"').bootstrapTable({url:"http://localhost:8080/rest/contractor", sidePagination:"server", responseHandler:"responseHandler"});`

I created a handler because i use spring data and pagination seem different then bootstrap-table
```
function responseHandler(res) {
        return {
            rows: res.content,
            total: res.totalElements,
            pageNumber: res.number+1,
            pageSize:res.size
        }
}
```

When i debug, i see the response have some data... but bootstrap table display: No matching records found

**Comment by dabros** [comment]
@mctdi - thats not enough info for us to do anything really

The only thing that jumps out is that `responseHandler` param is of type `function`, not `string`.

That and never use both `data-toggle` AND js init, doco quite clearly states (and every single example demonstrates) that its either one or the other, with `data-toggle` being a shortcut to avoid declaring anything else, but also in itself unreliable sometimes due to timing issues.

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by mctdi** [comment]
```
Ok i modified my code
```
<table id="contractorTableResult" 
        style="min-height:100" 
        data-show-header="true" 
	data-classes="table table-no-bordered" 
	data-id-field="id"
	data-height="600"
	data-pagination="true"
	data-side-pagination="server">
	<thead>
		 <tr>
			<th data-field="contractorId" data-sortable="true">#</th>
			<th data-field="name" data-sortable="true">Nom</th>
		 </tr>
	</thead>			
</table>
```

In the js part i do

            $("#contractorTableResult").bootstrapTable({
			url: getHostName() + "/contractors",
		         queryParams: "queryParams",
                        responseHandler: "responseHandler"
		});

             function queryParams(params) {
			console.log('queryParam', params);
			return {
				number: params.pageNumber,
				size: params.pageSize,
				sortName: params.sortName,
				sortOrder: params.sortOrder
			};
		};
		
		function responseHandler(res) {
			return {
				'rows': res.content,
				'total': res.totalElements,
				'pageNumber': res.number+1,
				'pageSize':res.size
			}
		}
```
I see my query is done on the server side;
There are some data, but the table stay empty.

**Comment by dabros** [comment]
@mctdi - read my post again, `responseHandler` is not a string, but the function itself, look at examples.

If using it as `data-response-handler` its a string, because its a data attribute and it will search for that function.

But look at the doco and other examples, all functions (responseHandler, formatter, ect) is set via js init with function definition, not a string - thats just a workaround for data attributes, and in my mind not very reliable due to scoping issues.

https://github.com/wenzhixin/bootstrap-table-examples/blob/master/issues/353.html

Your trying to mix and match code without looking more at the many working examples, and doing basic debugging.

This is why we always request fiddles, and why your supposed to use F12 and check console for error msgs, and actually debug by using `console.log`, breakpoints, ect.

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by mctdi** [comment]
bootstrap-table Example available on this site
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/welcome.html


```
 <table id="table"
           data-toolbar="#toolbar"
           data-search="true"
           data-show-refresh="true"
           data-show-toggle="true"
           data-show-columns="true"
           data-show-export="true"
           data-detail-view="true"
           data-detail-formatter="detailFormatter"
           data-minimum-count-columns="2"
           data-show-pagination-switch="true"
           data-pagination="true"
           data-id-field="id"
           data-page-list="[10, 25, 50, 100, ALL]"
           data-show-footer="false"
           data-side-pagination="server"
           data-url="/examples/bootstrap_table/data"
           data-response-handler="responseHandler">
    </table>
<script>
  function responseHandler(res) {
        $.each(res.rows, function (i, row) {
            row.state = $.inArray(row.id, selections) !== -1;
        });
        return res;
    }
</script>
```

**Comment by mctdi** [comment]
I created two exampe who work
[](http://jsfiddle.net/L8aqx2pm/)

```
<table id="table"
       data-pagination="true"
       data-side-pagination="server"
       data-height="300"
       data-show-export="true"
       data-click-to-select="true"
       data-response-Handler="responseHandler">
    <thead>
    <tr>
        <th data-field="bookId" >Book Id</th>
        <th data-field="Title" data-align="right" data-sortable="true">Title</th>
        <th data-field="author" data-align="center" data-sortable="true">Author</th>
        <th data-field="memberId" data-sortable="true">MemberId</th>
    </tr>
    </thead>
</table>

    function responseHandler(res) {
            return {
                rows: res.content,
                total: res.totalElements,
                pageNumber: res.number,
                pageSize:res.size
            }
        }
```

[](http://jsfiddle.net/g0009auk/)

```
<table id="table"
       data-pagination="true"
       data-side-pagination="server"
       data-height="300"
       data-show-export="true"
       data-click-to-select="true">
    <thead>
    <tr>
        <th data-field="bookId" >Book Id</th>
        <th data-field="Title" data-align="right" data-sortable="true">Title</th>
        <th data-field="author" data-align="center" data-sortable="true">Author</th>
        <th data-field="memberId" data-sortable="true">MemberId</th>
    </tr>
    </thead>
</table>

$('#table').bootstrapTable({
	url:"https://api.myjson.com/bins/tucu",
  responseHandler:"responseHandler"
});
    function responseHandler(res) {
            return {
                rows: res.content,
                total: res.totalElements,
                pageNumber: res.number,
                pageSize:res.size
            }
        }
```

just don't understand your thing about string and responseHandler... my example show that work.. ???

**Comment by marccollin** [comment]
second url it's: http://jsfiddle.net/0mgLxc19/

**Comment by dabros** [comment]
@marccollin - you can edit your posts and just use * word * (without spacing between char and *) to make *EDIT* note, easier to update links like that

Regarding `responseHandler` param, i stand corrected that the js init version can accept string name of function, im just used to it being declared inline there or using function name without quotations (which passes referance to actual function), this uses same approach for data-attributes as direct in this case (eval or equivalent i assume)

Thanks for providing fiddles, however all i can say now is the code in THOSE fiddles seem to work, can you provide more detail on your current blockers and ideally something i can actually test for your real use case?

You can mimic server side data using jsfiddle, there is `echo` and similar mechanics to acheive that, not too hard to use either: http://doc.jsfiddle.net/use/echo.html

**Comment by mctdi** [comment]
example in jsfiddle worked... but not in local... i changed to use the js way... like you said and worked.

**Comment by dabros** [comment]
@mctdi - if solved please close this issue, ideally sharing more detail (code sample and short explanation) as to what exactly solution was

thanks

**Comment by mctdi** [comment]
To work with spring data this code worked
```
$("#memberReportTableResult").bootstrapTable({
                url: getHostName() + "/members",
                queryParamsType: "",
                responseHandler: function (res) {
                    return {
                        rows: res.content,
                        total: res.totalElements,
                        pageNumber: res.number,
                        pageSize: res.size
                    };
                },
                queryParams: function (params) {
                    return {
                        number: params.pageNumber,
                        size: params.pageSize,
                    };
                }
            });
```

**Comment by YukunSun** [comment]
how can i use put the jsonp data into the bootstrap table
