### ISSUE TITLE
Proposal : collapse-row should be trigger before remove

### ISSUE THREAD

**Issue by gdoumenc** [wenzhixin/bootstrap-table#2254]
As you trigger `expand-row` after content added, you should call `collapse-row`before removing content... So we can perform tasks before removing DOM elements.

``` javascript
                that.trigger('collapse-row', index, row);
                $tr.next().remove();
```

**Comment by wenzhixin** [comment]
Any pull request is welcome!

**Comment by wenzhixin** [comment]
Fixed in the latest version.
