### ISSUE TITLE
Group-by and height do not work well together

### ISSUE THREAD

**Issue by deepfriedbrain** [wenzhixin/bootstrap-table#2257]
Hi,

If I have both group-by and height on a table, the first header's width stretches to occupy the full table width. Refer to this fiddle:

http://jsfiddle.net/deepfriedbrain/et9z85zv/11/

If I remove data-height attribute from the table, then the headers appear fine.

Is there a way to fix this issue?

**Comment by meganap** [comment]
👍  Also having this issue

**Comment by mwdowiak** [comment]
I'm also having this issue, how to fix this?

**Comment by javicaballero** [comment]
Please, any fix for this issue? Thanks

**Comment by UtechtDustin** [comment]
The group by extension will be merged/rewritten, this issue will be checked in #4413.
