### ISSUE TITLE
How do I pass parameters to the function of column event? 

### ISSUE THREAD

**Issue by rongsuema** [wenzhixin/bootstrap-table#226]
In your column event, we can use the code like that:

    window.eventName = {
        'click .buttonCss': function (e, value, row, index) {
            something here...;
        }
    }

    So is it possible that I use the code as following:
    window.eventName ={
        'click .buttonCss': customFunction 
    }
    And pass any parameters that I want?

**Comment by wenzhixin** [comment]
You can do it like this:
```js
window.eventName = {
    'click .buttonCss': function (e, value, row, index) {
        customFunction(...);
    }
}
```
The event won't work anymore is because the table row is rebuild, but you can use ```
$(document).on('click', '.buttonCss', function () {

});
```
to define you own events.

Close this issue.
