### ISSUE TITLE
Custom Toolbar, Custom Field and Cookies

### ISSUE THREAD

**Issue by dfmaxwell** [wenzhixin/bootstrap-table#2260]
Greetings,

I'd like a little guidance, if this is possible.  I'd like to use a custom toolbar - which I have working and a radio input with 3 choices.  When a radio is selected I'd like the table to filter and to save a cookie with the value.  Right now when the radio is clicked I have it do a bootstrapTable( 'selectpage', 1 ).  I also have data-query-params-type="custom" and data-query-params="queryParams" and a function that returns the conttype value and that is working as I expect.

I've looked at #2238 for guidance, but I'm definitely missing something if I'm on the right track.  I also looked at this jsfiddle http://jsfiddle.net/djhvscf/e3nk137y/5415/ but am not sure I'm able to do what I want or not.  My radio input name is conttype.  I have used both data-toggle="table" and a $table.bootstrapTable() to initialize the table.

Specifically I've added these lines in the $(function() { } section
//Set your cookie
		$.fn.bootstrapTable.utils.setCookie($('#contactstbl').data("bootstrap.table"), 'bs.table.conttype', $( 'input[name=conttype]:checked', '#toolbar' ).val() )

		//Get your cookie
		$.fn.bootstrapTable.utils.getCookie($('#contactstbl').data("bootstrap.table"), 'contactstbl', 'bs.table.conttype' )

as "this" or "$table" both brought up javascript errors in the console in my browser.

Thanks for any guidance you can provide.

**Comment by djhvscf** [comment]
Ok, let me create an example of this extension @dfmaxwell

**Comment by djhvscf** [comment]
Can you tell us what are the errors that you're getting from the console? @dfmaxwell

**Comment by djhvscf** [comment]
See this example: http://jsfiddle.net/djhvscf/e3nk137y/6400/ @dfmaxwell 

Please let us know if this is working for you

**Comment by dfmaxwell** [comment]
The error is not relevant, as I wasn't coding this effectively.  Your sample code was the key that I needed to get this finished.  I was so close, yet so far away.

Thank you once again for your assistance!
