### ISSUE TITLE
Save row data using input problem

### ISSUE THREAD

**Issue by endra89** [wenzhixin/bootstrap-table#2263]
dear @wenzhixin and @djhvscf 
i have same problem with  [#872](https://github.com/wenzhixin/bootstrap-table/issues/872), then i try [#987](https://github.com/wenzhixin/bootstrap-table/issues/987).
working correctly : [#demo here](https://jsfiddle.net/endra89/jzvhfeL4/2/)
my problem:
collum 1. only allow 1 checked, solved using getAllSelections
collum 2 and 3 allow multiple checked use [#987](https://github.com/wenzhixin/bootstrap-table/issues/987), failed get data like getAllSelections method
need litle help here, please.
thank you.

**Comment by djhvscf** [comment]
Your example is not working

**Comment by endra89** [comment]
thank you for replying, working only on "Utama" (first check box), need help to collect data on 2th checkbox, and 3th checkbox, like "getAllSelections" method

**Comment by wenzhixin** [comment]
I think you need to update the row data manually. ref #2325
