### ISSUE TITLE
使用bootstrap table 中checkbox 如何垂直居中

### ISSUE THREAD

**Issue by haormj** [wenzhixin/bootstrap-table#2264]
如题,我在使用bootstrap table的时候
{
field:'checkbox',
checkbox:true,
valign:'middle'
 }
我现在的需求是要将这个checkbox垂直居中,但是谢了 valign没有作用,求大神解答

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by haormj** [comment]
ok, I will use English
when use bootstrap table, I have the following question
 `{
field:'checkbox',
checkbox:true,
valign:'middle'
}`
althought I use valign tag let the checkbox Vertical centering, it is doesn't matter.

**Comment by haormj** [comment]
I also have another question, I see the document of Bootstrap Table. 
in table options,there is a 'rowStyle' attribute,I don't konw how to use it, can you use it well? please give 
me a demo, thinks!

**Comment by jackie88558** [comment]
```
$("#table").bootstrapTable({
	 		rowStyle: function (value, row, index) {
  return {
    classes: 'text-nowrap another-class',
    css: {"color": "blue", "font-size": "50px"}
  };
}
	 	});
```

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by wenzhixin** [comment]
Same with #2195.
