### ISSUE TITLE
Column Sort Class [solved]

### ISSUE THREAD

**Issue by talatbaig** [wenzhixin/bootstrap-table#2265]
Hi,

When you sort by a particular column, could you please add a class to the td elements of that column so that it can be styled to show that this is the column we are sorting by.

eg you can clearly see this table is being sorted by the third column.

![](http://www.jqueryscript.net/images/Flexible-Client-Side-Table-Sorting-Plugin-tablesorter.jpg)

Thanks

**Comment by djhvscf** [comment]
This can be a good feature

**Comment by djhvscf** [comment]
See this example: http://jsfiddle.net/djhvscf/e3nk137y/6452/

**Comment by djhvscf** [comment]
This is the **PR** https://github.com/wenzhixin/bootstrap-table/pull/2272

@talatbaig

**Comment by talatbaig** [comment]
great stuff

**Comment by dabros** [comment]
@talatbaig - please remember to close issues when solved

thanks
