### ISSUE TITLE
fixed columns right align 

### ISSUE THREAD

**Issue by talatbaig** [wenzhixin/bootstrap-table#2266]
Hi,

For bootstrap-table-fixed-columns can you allow an option to select to fix the columns on the right or the left.

Thanks

**Comment by dabros** [comment]
@wenzhixin @djhvscf  - maybe im just missing something, but i cant find fixed-columns file in src folder, dev or master, nor any doco in extensions or main doco page

I swear i helped with this in past, but cant see files...

**Comment by dabros** [comment]
@talatbaig - please be very clear in this request

1. Where were these columns originally?
2. Why do they need to be right aligned? (this is very unintuitive and uncommon use case)
3. What benifit does this new alignment give that might require it to be a core feature?

If you take a look at http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/fixed-columns.html and generated html, you can see how this is done currently.

In short, `.fixed-table-body-columns` and `.fixed-table-header-columns` are `position:absolute` and similar to force them to overlay, with other elements spaced out to make this fit well.

To change that is not so simple, you can hit F12 and play with the css yourself to prove it. I see it as maybe knowing width of main table, applying `left` or even negative `right` rule, but then issue with resizing, though events and handlers already exist, though that does mean alot of affected code.

**Comment by talatbaig** [comment]
Hi Dabros,

Apologies for the confusion, let me clarify my issue.
In the example link you gave I have the ability to fix columns from the left, eg
Col 0,
Col 0, Col 1,
Col 0, Col 1, Col 2
etc

but I cant fix columns from the left, eg
Col 19,
Col 18, Col 19
Col 17, Col 18, Col 19

The reason I would like to do this is my last column (Col 19) contains a button View (to view more details about that particular item on a different page) which is a standard design practice used by many people, but if I have a lot of columns that don't fit on the screen like in the example you sent without scrolling horizontally I as a user don't know that there is this View button. If Col 19 was "fixed" I would always see this button no matter how many columns there or how small my screen is.

I hope that clarifies the situation.

Thanks

**Comment by dabros** [comment]
@talatbaig - thanks for clarification

Cant really an easy solution, nor can i really see how to make that fixed-columns extension work well for right aligned columns, though @wenzhixin or @djhvscf  prob do

I did try messing with css on both fixed-columns demo and [large columns demo](http://issues.wenzhixin.net.cn/bootstrap-table/#options/large-columns.html) but seems no easy way, definetly possible but not a simple tweak maybe...

Maybe they can help you more

**Comment by talatbaig** [comment]
@wenzhixin @djhvscf  any thoughts on this issue?

**Comment by Falseee** [comment]
The issue is already 3 years old, if you still need this feature pls reopen it!

**Comment by wenzhixin** [comment]
@Falseee I think it is a good feature, I will implement it.

**Comment by Falseee** [comment]
My mistake i didnt saw there is already a feature label on it!

**Comment by wenzhixin** [comment]
Never mind.
