### ISSUE TITLE
why the '.page-list' and 'pagination' is 'disabled:none',but  pagination is true

### ISSUE THREAD

**Issue by chenhuwo** [wenzhixin/bootstrap-table#2269]
why the '.page-list' and 'pagination' is 'disabled:none',but  pagination is true

**Comment by dabros** [comment]
???

Read https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports and provide clear situation description, then clear expected output vs actual output

**Comment by djhvscf** [comment]
I am not sure what you mean. I am going to need some more information.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
