### ISSUE TITLE
How do i get Data from json array?

### ISSUE THREAD

**Issue by okgint** [wenzhixin/bootstrap-table#227]
I have a data:
[{"id":404,"description":"PowerEdge 6300","price":7500,"onhand":16,"supplierId":302,
"suppliers":[{"name":"DELL","webSite":"http://dell.com"}]}

i want to get suppliers.name field, how do i get that data field ?
![suppliers](https://cloud.githubusercontent.com/assets/9662548/4982685/bac0939c-6914-11e4-99e4-0ff6947e0e6e.png)

**Comment by wenzhixin** [comment]
Close this issue.

**Comment by cereblanco** [comment]
Hi,

Can I use the flatJSON plugin to display the content of an array in one column?
Example:

data.json
[{
        "id": 1,
        "name": "Group",
        "members": [{
                "id": 1,
                "name": "410041234567801",
                "callerid": "09278784217"
            },{
                "id": 1,
                "name": "410041234567802",
                "callerid": "09278784218"
            },{
                "id": 1,
                "name": "410041234567803",
                "callerid": "09278784219"
            }
         ]
}]

I wanted to display all members in one column
    <thead>
        <tr>
            <th data-field="name" data-align="center" data-sortable="true">Group</th>
            <th data-field="members" data-sortable="true">Members</th>
        </tr>
    </thead>

Thanks!

**Comment by djhvscf** [comment]
I think you can use this example in order to get your requirement: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/177.html

**Comment by goldnuggets24** [comment]
Just wanted to thank @djhvscf for the helpful comments here! This hugely came in handy for me. :+1:

**Comment by leohmoraes** [comment]
Hi, 

How I display the content of an array created by javascript. 
Modal->Form->(Array or Json)->Update DataTable

Thanks !
