### ISSUE TITLE
Fixed columns not working in IE 11

### ISSUE THREAD

**Issue by skumarfaruk** [wenzhixin/bootstrap-table#2270]
![image](https://cloud.githubusercontent.com/assets/11256224/15244496/0c75b954-191f-11e6-835b-45835c1d7665.png)

i have following the below link but the fixed column data not getting in ie 11.
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/fixed-columns.html

Please tell me how to fix it i want to implement in my web application.

Thank you

**Comment by skumarfaruk** [comment]
Any update?

**Comment by gutyril** [comment]
There is a fix here https://github.com/wenzhixin/bootstrap-table-fixed-columns/issues/4

**Comment by wenzhixin** [comment]
Added new version fixed-columns extension: https://github.com/wenzhixin/bootstrap-table/commit/91977960a5705cd074067b2670483b5e9d5c1f44
Develop example: http://dev.bootstrap-table.com/examples/#extensions/fixed-columns.html
