### ISSUE TITLE
export all data from server side has a bug, I got two half-baked CSV files.

### ISSUE THREAD

**Issue by hojas** [wenzhixin/bootstrap-table#2271]

**Comment by djhvscf** [comment]
I am not sure what you mean. I am going to need some more information.

**Comment by dabros** [comment]
@hojas - Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by hojas** [comment]
Sorry about my poor English. My table gets data from server side by url, and I want to export all data with Table Export extensition, but I just got two csv files, and the two files did not contain all data. After downloaded csv files, the table pagination was gone. And I was confused about the all things happened. 

My codes:

```
    $('a[href="#students"]').on('click', function() {
        $('#students table').bootstrapTable({
            striped: true,
            url: jdata.teacherUserListUrl,
            pagination: true,
            sidePagination: 'server',
            showExport: true,
            exportDataType: 'all',
            columns: [{
                title: '昵称',
                align: 'left',
                formatter: nameFormatter,
            }, {
                field: 'course_index',
                title: '完成率',
                align: 'left',
            }, {
                field: 'course_time',
                title: '有效学习时间(分钟)',
                align: 'left',
            }, {
                title: '实验桌面',
                align: 'left',
                formatter: desktopFormatter
            }]
        });
    });
```

**Comment by tonio** [comment]
@hojas try to use develop branch instead of latest release, that fixed the issue for me.

**Comment by wenzhixin** [comment]
Please update to the latest version: v.1.11.0
