### ISSUE TITLE
detailView outside of the table 

### ISSUE THREAD

**Issue by antonyboom** [wenzhixin/bootstrap-table#2273]
is it possible to show 'detailView' outside of the bs-table?
in [ plunker example](https://plnkr.co/edit/rfKKnZTuFow0TcOKHMsy?p=preview),
I've provided two divs and table with option detail view, as I can see detailView is rendering thru this code
 `function detailFormatter(index, row) {
    var html = [];
    $.each(row, function (key, value) {
        html.push('<p><b>' + key + ':</b> ' + value + '</p>');
    });
    return html.join('');
}`,
so I have tried multiple time something like this but in different configs 
 `function detailFormatter(index, row) {
    var $form = $('#form');
    $.each(row, function (key, value) {
        $form.push('<p><b>' + key + ':</b> ' + value + '</p>');
    });
    return $form.append('');
}` 
but always getting an error 

> Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

**Comment by dabros** [comment]
@antonyboom - that plunker has nothing about bootstrap in it

Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Fiddle examples are given there, and can be used to make something we can test and work with and is consistent with all other fiddle examples

**Comment by antonyboom** [comment]
@dabros I apologize for my empty plunker, It looks that I forgot to save it, this is working [link](https://plnkr.co/edit/rfKKnZTuFow0TcOKHMsy?p=preview)

**Comment by dabros** [comment]
@antonyboom - it helps to step back and re-examine core issue

Core issue, as i read it, is that you want (on a mouse click or similar action) to display extended information for a table row.

You do NOT (for whatever reason) want that to be presented in a drill-down type heirachy as presented by default `tr.detail-view`.

Possible solutions:

A. change detail view presentation (css, html and/or js code). 
For a simple example of what that might look like, add `tr.detail-view {position: absolute;top: 309px;}`  (for full screen 1690x1080 layout, adjust px if too high or low) as css rule in that plunker. Rough, but can give you good idea of what it would look like.

Issue with that is that you risk overcomplicating css, especially given bootstrap table is and should remain responsive. Also, why the '+' when not expanding in same element. Seems odd to me.


B. DONT USE detail view
Click and show extra data, why not `click-row.bs.table` and use those param (including `this`/`$(this)`) to load that data into some other DOM element.

Dont overcomplicate, always examine core issue

http://bootstrap-table.wenzhixin.net.cn/documentation/#events
http://issues.wenzhixin.net.cn/bootstrap-table/index.html (hit F12 and see console)

Also plenty of other issues here and prob SO posts as well regarding or using `click-row` event.

**Comment by antonyboom** [comment]
@dabros thank for you advice! I used option B, got value of row 
`      $('#table').on('click-row.bs.table', function (e, row, $element) {

                    $('.success').removeClass('success');
                    $($element).addClass('success');

                    var indexId = $table.find($element).data('index');
                    var rowData = $table.bootstrapTable('getData')[indexId];
});`

then just put it to scope variable inside ng-form with ng-submit and set angular watcher that to follow for changes. One more time, thank you so much!

**Comment by dabros** [comment]
@antonyboom :+1: 

Some thoughts from what you shared though, checkout the param like i recommended, you should have all that data (at least `rowData`) from passed param like `row`, `$table` could 'maybe' (if i recall correct) be `$(this)` (just a pattern preferance, means code is more modular and you use `$('#table')` above so not consistent).
