### ISSUE TITLE
Search in specific fields only

### ISSUE THREAD

**Issue by dfloresgonz** [wenzhixin/bootstrap-table#2274]
I have a status column and another column in which the name of the status is in along with other statuses. I need to apply the search to specific columns, in this example to my status column only.
I find this solution easier than using filter extension.

Basically I need the search event to ignore some columns.
Something like this:

`<th data-search-here="true">STATUS</th>`<br>
`<th data-search-here="false">SEARCH NOT APPLIED HERE</th>`

**Comment by djhvscf** [comment]
You should use the searchable column option...

http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

**Comment by dfloresgonz** [comment]
Thanks a lot sorry for missing that.
