### ISSUE TITLE
关于removeByUniqueId的问题

### ISSUE THREAD

**Issue by Kcher** [wenzhixin/bootstrap-table#2275]
你好！
我在使用Bootstrap Table遇到一个问题，情况如下
我先使用getSelections方法获取勾选的记录，
然后使用removeByUniqueId将勾选的记录从table中移除掉，
然后我试图再勾选移除其他记录的时候，
发现getSelections获取到的记录还包含着之前已经移除掉的记录，
请问这是我的使用方式不对呢，还是插件中存在着bug?
盼望你的解答，谢谢！

**Comment by wenzhixin** [comment]
修复了，你验证下。

**Comment by Kcher** [comment]
@wenzhixin 我刚刚试了1.10.1的版本，还是存在这个问题

**Comment by wenzhixin** [comment]
develop 版本
