### ISSUE TITLE
Slow loading tables

### ISSUE THREAD

**Issue by BenJule** [wenzhixin/bootstrap-table#2278]
Hi guys,

sometimes the page is loading very slow! First text and after view secs the table is loading!
**URL:** https://laravel.s3root.ovh/from-html

Any ideas?

Thx for help

**Comment by jackie88558** [comment]
You should set the table properties first, and then load the data. I'm not sure whether you write the code like this.
By the way, there are some js error on your page. See console of your develop tools(browser).

**Comment by BenJule** [comment]
Bonjour @jackie88558 ,
thanks for your reply.

My code atm: http://laravel.io/bin/1yD9J

Greetz

**Comment by jackie88558** [comment]
You need to see the source code sequence if everything is defined in tag. Maybe css will render the border after the table initial.
If you really care about this, please initail the table in JS. Properties first, load data next.

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
