### ISSUE TITLE
hi , May be able to do better !  some suggestions and requirements .

### ISSUE THREAD

**Issue by xianghongai** [wenzhixin/bootstrap-table#228]
hi, wenzhixin,
bootstrap-table , it's a great plugin ! nice !
i wanna with these features : 
1) fixed table thead and tfoot , just let the tbody scroll(x || Y), 
2) according to the characters, date or/add data range, filtering table data,

![demo](https://cloud.githubusercontent.com/assets/2075006/4988952/76b0f12e-69aa-11e4-9706-fafd875610df.png)

tbody height : window height minus other muddle layers height , tbody overflow , use 'iscroll 5' jquery plugin .

tfoot : statistics the current page, or all the pages data .

looking forward to your reply :)

**Comment by wenzhixin** [comment]
You can have these features now.

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/
