### ISSUE TITLE
column width not work when cell data is too long

### ISSUE THREAD

**Issue by tianyaxue** [wenzhixin/bootstrap-table#2281]
I set column width with percentage , but it not work when cell data is long,example is here:
https://jsfiddle.net/robin1987/dz1y6kkg/

**Comment by dabros** [comment]
@tianyaxue - css issue, nothing to do with that width option as a quick F12 and inspect shows it does just that

Off top of my head i went through css rules that might affect content wrapping, nothing changed till I used `word-break: break-word;`, thats the magic word it seems in this case

Next time, use basic debug (F12) and then search for underlying issue on google, that same title you show here, "column width not work when cell data is too long", has a bunch of useful hits

For referance:
```
td, th {
/*
    word-wrap: break-word!important;
    overflow-wrap: break-word!important;
    overflow: hidden!important;
    white-space: normal!important;
*/
    word-break: break-word;
}
```

**Comment by tianyaxue** [comment]
@dabros thks,it's work.

**Comment by Rex1021** [comment]
@dabros very well man
