### ISSUE TITLE
How to just delete the row not the JSON data

### ISSUE THREAD

**Issue by xyluet** [wenzhixin/bootstrap-table#2282]
how to just delete the row from the screen, not delete the JSON data ?

**Comment by wenzhixin** [comment]
you mean hide the row?

**Comment by xyluet** [comment]
i consider that option, but can I just delete it? because if hidden there is still in the HTML.
And other issue is when I add the row, it will make an array in my JSON. I just want to add and delete row only on the screen, not just add and delete from my JSON.

Thanks

**Comment by dabros** [comment]
@xyluet - look at http://issues.wenzhixin.net.cn/bootstrap-table/index.html#methods/showRow-hideRow.html and related options

If you need more help, we really need a fiddle (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports). You can just use js array for data and have 'add row' button that passes in some dummy object with `insertRow` or similar, just get key functionality working so you can replicate the issue if `showRow/hideRow` doesnt solve it

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by xyluet** [comment]
No i haven't. But finally i used manual table. It's okay. 

Thank you for help. Usefull plugin. You can close this issue

**Comment by wenzhixin** [comment]
OK @xyluet
