### ISSUE TITLE
export

### ISSUE THREAD

**Issue by HKhedr** [wenzhixin/bootstrap-table#2284]
I want to change Unicode export file to support Arabic..
I have column's Title "Header" in  Arabic Language when I export file i get column like that 
 ' D * 3 D 3 D ' D # 3 E ' D 9 F H ' F ' D E D ' - 8 ' * ' D 1 E 2   ' D ( . . . 1 B E   ' D E F 7 B ) ' D G ' * A ' D A ' C 3 ' D , H '   

Regards

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by HKhedr** [comment]
My table is in Arabic language when export I get Hash code
[jsfiddle](http://jsfiddle.net/Khedr/brjejv7z/4/)

Thank you

**Comment by HKhedr** [comment]
@wenzhixin

**Comment by dabros** [comment]
@wenzhixin @djhvscf

**Comment by wenzhixin** [comment]
Sorry I don't know why, maybe @hhurz know the problem. Please close this issue and submit to https://github.com/hhurz/tableExport.jquery.plugin/issues, thanks!

**Comment by hhurz** [comment]
FYI: You will find my answers to this issue [here](https://github.com/hhurz/tableExport.jquery.plugin/issues/84)

**Comment by wenzhixin** [comment]
Thanks @hhurz
