### ISSUE TITLE
Table editable selectbox

### ISSUE THREAD

**Issue by jankevinturado** [wenzhixin/bootstrap-table#2286]
Hi, how can I make the editable cell to select box and the option value loaded by database ? and how can I detect If the cell data was changed?

Thanks in advance.

**Comment by dabros** [comment]
ref: #2298

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by Falseee** [comment]
@wenzhixin I guess after almost 3years without any reaction the issue can be closed.

Also all informations can be found on the documentations ([bootstrap-table](https://bootstrap-table.com/docs/extensions/editable/#editable-1) and [X-editable](http://vitalets.github.io/x-editable/docs.html#editable) (option: type) ).
