### ISSUE TITLE
use bootstrap-table will make the "table-condensed" class doesn't work

### ISSUE THREAD

**Issue by zhangchunlin** [wenzhixin/bootstrap-table#2287]
http://getbootstrap.com/2.3.2/base-css.html#tables
table-condensed doesn't work, but table-striped works.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by zhangchunlin** [comment]
I test in http://runjs.cn/code/2bvu4wpr
and found that this issue happen in 1.8.1 but not happen in 1.10.1
