### ISSUE TITLE
Header and column border line not sync

### ISSUE THREAD

**Issue by chandrantwins** [wenzhixin/bootstrap-table#2288]
Hi wenzhixin,

Thanks for such wonderful bootstrap table. I am very satisfied about how it works except one thing,

when i have column with lenghty value that time i will get horizontal scrollbar, that is common, but in that case my header and column border line are not syncing. Please find attached screenshot

![chandran_2](https://cloud.githubusercontent.com/assets/5931321/15386832/266244a6-1daa-11e6-929b-09a9ab4b8e20.png)

Any help will be appreciable.
I wish you more success on your future project.

**Comment by chandrantwins** [comment]
one more hint :

I have observed that div "fixed-table-header" does not have proper value for margin-right: -183px;

I think margin-right calculation somehow collapsed...just guess

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by chandrantwins** [comment]
Thanks for quick response.

In my code i am setting height during resize and footer loading that was the problem for header and column border line not syncing. 
**OLD CODE**
 setTimeout(function () {
            $table.bootstrapTable('resetView', {height: 500});			
        }, 200);

 jQuery(window).resize(function () {
            $table.bootstrapTable('resetView', {
                height: getHeight()
            });
        });

Problem resolved using following code
**NEW CODE**
 setTimeout(function () {
            $table.bootstrapTable('resetView');			
        }, 200);

 jQuery(window).resize(function () {
            $table.bootstrapTable('resetView');
        });
But now i have to set fixed height for my table. How i can set ? Please Any help

**Comment by chandrantwins** [comment]
here is sample http://jsfiddle.net/yf0u35jL/162/

**Comment by wenzhixin** [comment]
I think your problem is cause by the code:
```
<div style="padding: 10px; ">
    <br>
```

Updated: http://jsfiddle.net/wenyi/yf0u35jL/163/

**Comment by chandrantwins** [comment]
Please check this condition.. i have lengthy column value 

http://jsfiddle.net/yf0u35jL/164/

**Comment by jackie88558** [comment]
I think you might need to set the width for div whose class is .fixed-table-container.
This div include thead and tbody all.

**Comment by jackie88558** [comment]
I suggest you set max-width by cellStyle.
```
cellStyle: function(value, row, index) {
    return {
       css: {"max-width": "350px", "text-overflow": "ellipsis", "overflow": "hidden"}
    };
}
```

**Comment by wenzhixin** [comment]
have you solved your problem?

**Comment by chandrantwins** [comment]
yes i just removed setting dynamic height..its work pefect

**Comment by chandrantwins** [comment]
Hi wenzhixin.. 

i have removed previously height method..but my requirement changes ..i need scrollbar in horizontal..Please help me to solve this problem

**Comment by wenzhixin** [comment]
@chandrantwins  Like this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/large-columns.html?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
