### ISSUE TITLE
Default Sort order is wrong if data-visible="false" is set on the field referenced by data-sort-name.

### ISSUE THREAD

**Issue by ethompsy** [wenzhixin/bootstrap-table#229]
I am getting really out of order sort row sorting results. I am trying to sort by an integer and the rows are ordered { 4, 4, 52, 0, 0 }. This makes no sense.

I set the 'data-sort-name="score"' and 'data-sort-order="desc"'. Score is just a column of integer values.

If I sort on any other row those are out of order too (alphabetical, etc...). But! If I click the header for the "Score" column then it sorts correctly.

Looking at this it seems to default to sorting by the first column (which is an alphabetical value). This is sorted correctly, but if I click the header on this row it is sorted wrong. Really wrong...

**Comment by wenzhixin** [comment]
@djhvscf can you help to check this issue if you have time?

**Comment by djhvscf** [comment]
Sure! :) @wenzhixin
