### ISSUE TITLE
Combine show columns and detail view [solved]

### ISSUE THREAD

**Issue by talatbaig** [wenzhixin/bootstrap-table#2290]
Hi,

Show columns currently allows you to show and hide columns: 
http://issues.wenzhixin.net.cn/bootstrap-table/#options/basic-columns.html

Detail View allows you to show more details about a particular row:
http://issues.wenzhixin.net.cn/bootstrap-table/options/detail-view.html

Is there a way to combine these 2 features into one:
if a column is disabled and hidden it only comes up in the detail view
if a column is enabled and shown it doesn't come up in the detail view

I'm assuming there would be a way to do this using the detailFormatter but not sure how

Thanks

**Comment by dabros** [comment]
@talatbaig - there are methods `getVisibleColumns` and `getHiddenColumns`, the only caveat being they are in doco though new and i only have old version fiddles with `detailView` to test so the following code i couldnt test well but should work

```
function detailFormatter(index, row) {
  
  // NOTE - getVisibleColumns may require latest develop release, but i confirmed getHiddenColumns is in 1.10.1 CDN version
  // NOTE - mostly untested, but methods are in doco, if issue just search github and StackOverflow
  // $(this).bootstrapTable('getVisibleColumns') 
  // console.log('debug',this,$(this).bootstrapTable('getHiddenColumns'))
  console.log('debug',$(this).bootstrapTable('getHiddenColumns'))
  
    var html = [];
    $.each(row, function (key, value) {
        // take the hidden columns list, then some part of that against the 'key' var
        html.push('<p><b>' + key + ':</b> ' + value + '</p>');
    });
    return html.join('');
}
```

Try out those methods, making sure to use latest version (develop if master doesnt suffice) then share your working code before closing please. The checking part is simple, just google if looking for super efficient way, else just direct `$.inArray` or similar should suffice (cant recall exact method).

**Comment by talatbaig** [comment]
Hi @dabros 

Thanks for the reply.
Do you know if there is a way to use npm to install the develop branch, the following don't methods don't work 

npm install bootstrap-table#develop
npm install bootstrap-table@develop

**Comment by talatbaig** [comment]
never mind the following seems to work :)
npm install git://github.com/wenzhixin/bootstrap-table#develop

**Comment by talatbaig** [comment]
I managed to get it working with the following, thanks!

```

detailFormatter: function(index, row) {
    
    var hidden_columns = [];
    $.each($('#table').bootstrapTable('getHiddenColumns'), function (key, column) {
        hidden_columns.push(column['field']);
    });
    
    var html = [];
    $.each(row, function (key, value) {
        if(hidden_columns.indexOf(key) >= 0) html.push('<p><b>' + key + ':</b> ' + value + '</p>');
    });
    return html.join('');
},
```

**Comment by dabros** [comment]
@talatbaig - :+1: 

If solved please close, ideally updating title with [solved] too (personal preferance, not at all requirement)

Thanks :)
