### ISSUE TITLE
Number of selected items

### ISSUE THREAD

**Issue by talatbaig** [wenzhixin/bootstrap-table#2291]
Hi,

Currently there is a getSelections function to provide the selected rows
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getSelections.html

Is it possible to have some text somewhere, maybe top left that says for example: "4 rows selected" when 4 rows are selected.

Thanks

**Comment by wenzhixin** [comment]
You can use `onCheck/onUncheck` or `onCheckAll/onUncheckAll` events to do what you want:
http://bootstrap-table.wenzhixin.net.cn/documentation/#events

**Comment by dabros** [comment]
@talatbaig - if this worked, please provide some more description on how it helped you and possibly some of your own code for the next wanderer, then close this issue

thanks
