### ISSUE TITLE
Regression: `data` removed from post-body trigger

### ISSUE THREAD

**Issue by thornomad** [wenzhixin/bootstrap-table#2293]
I just noticed that at some point, pull request #2012 somehow go reverted.  I can't find the commit that did it ... but it was merged, was working, and now the little line has been changed back!

Do you want me to re-submit a new pull request to fix it?

Here is the commit that added the `data`: 
https://github.com/wenzhixin/bootstrap-table/pull/2012/commits/ba8429b89d39b2194451e71210fa984f445fa639

But it's not there anymore!  Poof!
https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1772

Let me know!

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1903

**Comment by thornomad** [comment]
Ah - so it's still only in the `develop` branch?  I got confused because the [documentation](http://bootstrap-table.wenzhixin.net.cn/documentation/) shows the change ... is the documentation online based off of `develop` and not `master` ?  

That is what threw me off -- I installed the newest version and looked at the docs and assumed it should be working.

**Comment by wenzhixin** [comment]
Yes, you can use develop version. I will release a new version soon.

**Comment by thornomad** [comment]
Okay - I will close this issue and look forward to the next release!  Thanks!
