### ISSUE TITLE
请问有没有纯JS版本的示例，而不是html属性来书写功能，实际项目中难以灵活控制！

### ISSUE THREAD

**Issue by liululululu** [wenzhixin/bootstrap-table#2294]

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/getting-started/#usage-via-javascript

**Comment by liululululu** [comment]
@djhvscf http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/group-columns.html:
In **html** only the following content
```
<html>
<table id="this_table"></table>
</html>
```


Other written in **javascript** inside
otherwise difficult to flexibly control the actual project!

**Comment by liululululu** [comment]
I want a simple example only use jQuery in website, can't use html attribute!
