### ISSUE TITLE
How to abort AJAX call while refreshing table data

### ISSUE THREAD

**Issue by nimeshdolphin** [wenzhixin/bootstrap-table#2297]
How to abort AJAX call in-between while refreshing table data ? 
If I do refresh table 10 times quickly, I can see 10 Ajax calls. I want to abort all Previous calls and keep the latest one.

**Comment by wenzhixin** [comment]
#1977 https://github.com/wenzhixin/bootstrap-table/commit/f59677a6fa802612e2cd2d8da231ddd5b3aa6f0f
