### ISSUE TITLE
Populate editable select box by field value of table cell

### ISSUE THREAD

**Issue by jankevinturado** [wenzhixin/bootstrap-table#2298]
Help. I cant figure it out how do I read the value of table cell, anyway, on my table cell I have 2 select box which is editable but I want to populate the 2nd select box by selecting a value from 1st select box. the vaue of my 1st select box is the reference to my ajax which will give a option value to my 2nd select box. here is my code:

```
$("#table").boostraptable({
search: true,
idField: 'id',
columns:[
{field: 'id',
	title: 'ID',
	halign:'center',
	align:'center',
	sortable: true,
}},

{field: 'deparment',
	title: 'DEPARMENT',
	halign:'center',
	align:'center',
	sortable: true,
	editable:{
		type: 'select',
		source: 'path/to/php'
}},

{field: 'memberofthisdept',
	title: 'MEMBER.',
	halign:'center,
	align:'center',
	sortable: true,
	editable:{
		type: 'select',
	       source: 'path/to/php'
}}
]
});
```
so i have to select a DEPARMENT on may 1st select box first so I can select a MEMBER on 2nd select box.
 Do we have a feature of this? thanks!.

**Comment by dabros** [comment]
possible ref: #986

**Comment by wenzhixin** [comment]
Have you solved your problem? @jankevinturado

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
