### ISSUE TITLE
why the  pagination toolbar desn't show?

### ISSUE THREAD

**Issue by TellH** [wenzhixin/bootstrap-table#2299]
bootstrapTable:
`        pagination: true,
        sidePagination: "server",
        pageSize: 5,
        queryParams: getParams,
        responseHandler: responseHandler`
responseHandler:
`        return {
            "total": sourceData.totalPages,
            "rows": pageData
        }
`
getParams:
`    return {
        userId: userId,
        itemNum: params.limit,
        page: table.bootstrapTable('getOptions').pageNumber
    };`

actually, the table get the correct tatalPage number ,but it does't not show the pagination toolbar.
The situation is that, tatalPages=8, pageSIze=5. it does'n show the pagination toolbar; but when the pageSIze=2,  it show the pagination toolbar, but only tow pages!!!

![image](https://cloud.githubusercontent.com/assets/15800681/15476789/c550e5d0-2143-11e6-9360-63fe594b383b.png)

**Comment by dabros** [comment]
@TellH - i know it can be more tricky in cases like this, but we really need a fiddle where you replicate this issue.

You can use echo feature to mimic your exact data (as explained here, with official doco linked at top: http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery)

But where to start first is 

1. Use F12 (console and network panel) to examine working example like http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/server-side-pagination.html and compare very carefully to your own (also using button in top right of example to see source code). If something looks off you can search `queryParam` and `responseHandler` in issues to find possible issues with that, i dont know your datasource but just make sure return matches requirements for all requests (post `responseHandler` steps) and no errors at all.

2. If absolutely nothing jumps out at you, or something does and you want to investigate, then look at look at https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports and example fiddle for server side, get that working then add in your data via echo or similar.

We really cant help without you replicating the issue so we can fix it, but do thorough debug first to save you that hassle.

**Comment by TellH** [comment]
it is my fault,not this plugin bug, thanks for your help!
