### ISSUE TITLE
怎么自定义搜索参数，比如增加时间区间等。

### ISSUE THREAD

**Issue by cevin** [wenzhixin/bootstrap-table#2300]
怎么自定义搜索参数，比如增加时间区间等。

**Comment by wenzhixin** [comment]
这里有例子：
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/386.html
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.htm

**Comment by cevin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.htm
这个404了

**Comment by wenzhixin** [comment]
写错，是 .html
