### ISSUE TITLE
first row selected by default

### ISSUE THREAD

**Issue by antonyboom** [wenzhixin/bootstrap-table#2302]
I was trying to find something here in closed issues but have found only check method 
`$('#table').bootstrapTable('check', 0);`, but I don't use checkbox in my table and get an error
 `bootstrap-table.js:2483 Uncaught TypeError: Cannot set property 'undefined' of undefined`,
also I've checked documentation but found only `selectPage`. Is there something for row?

**Comment by dabros** [comment]
Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Fiddles and similar steps are needed for us to better help everyone, and for you to help yourself :)

All i can say without it is look at using callback that is run AFTER table data FINISHED loading and calls to `check` or `checkBy` (maybe `onLoadSuccess` or similar, optionally with a `var firstRun` defined on top level so you do this extra step only first time, if that event triggered by other actions, test to find out)

http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

Timing is everything, and if `'undefined' of undefined` you want to make sure that `$('#table')` matches YOUR table id, not just that copy paste. See the examples, such as http://issues.wenzhixin.net.cn/bootstrap-table/index.html#methods/check-uncheck.html

**Comment by antonyboom** [comment]
@dabros thank you again for good references!
