### ISSUE TITLE
why the column's content always be "-" Fill  ?

### ISSUE THREAD

**Issue by liululululu** [wenzhixin/bootstrap-table#2305]
I did not find out what the bug, but in the following figure, the data in a column will always be "-" Fill
![image](https://cloud.githubusercontent.com/assets/10783450/15529647/622de784-2281-11e6-9389-0e306e321160.png)

**my js:**
`                        var jqmaintenancetable = jq("#maintenance_set_table");
			  jqmaintenancetable.bootstrapTable({
				url:  'drugsMaintenance/data/jqmaintenance.json',
				pagination: true,
				pageNumber: 1,
				pageSize: 15,
				pageList: [10, 25, 30],
				search: true,
				showExport: true,                     //是否显示导出
				exportDataType: "basic",              //basic', 'all', 'selected'.
				exportTypes: [ 'txt','excel'],
				columns: [{
				  field: 'id',
				  title: 'NO.'
				},
				{
				  field: 'goods',
				  title: '商品编码/名称'
				},
				{
				  field: 'acceptType',
				  title: '验收分类'
				},
				{
				  field: 'spec',
				  title: '规格'
				},
				{
				  field: 'permit',
				  title: '批准文号'
				},
				{
				  field: 'lotNo',
				  title: '批号'
				},
				{
				  field: 'manufactureDate',
				  title: '生产日期'
				},
				{
				  field: 'updateexpiryDate',
				  title: '效期'
				},
				{
				  field: 'manufacturer',
				  title: '生产厂商'
				},
				{
				  field: 'place',
				  title: '产地'
				},
				{
				  field: 'trays',
				  title: '货位'
				},
				{
				  field: 'maintenanceNum',
				  title: '养护数量'
				},
				{
				  field: 'circumstance ',
				  title: '环境情况',
				  editable: {
					type :'select',
					source: [
						  {value: 1, text: '请选择'},
						  {value: 2, text: '良好'},
						  {value: 3, text: '差'}
					   ]
					}
				},
				{
				  field: 'maintenanceMeasure',
				  title: '养护措施',
				  editable: {
					type :'select',
					source: [
						  {value: 1, text: '请选择'},
						  {value: 2, text: '001'},
						  {value: 3, text: '002'}
					   ]
					}
				},
				{
				  field: 'maintenanceConclusion',
				  title: '养护结论',
				  editable: {
					type :'select',
					source: [
						  {value: 1, text: '请选择'},
						  {value: 2, text: '001'},
						  {value: 3, text: '002'}
					   ]
					}
				},
				{
				  field: 'unCheckQtyNum',
				  title: '不合格数量'
		
				},
				{
				  field: 'unQualifiedReason',
				  title: '不合格原因'
				},
				{
				  field: 'question',
				  title: '存在问题'
				},{
				  field: 'outlookQuality',
				  title: '外观质量',
				  editable: {
					type :'select',
					source: [
						  {value: 1, text: '请选择'},
						  {value: 2, text: '001'},
						  {value: 3, text: '002'}
					   ]
					}
				},{
				  field: 'packQuality',
				  title: '包装质量',
				  editable: {
					type :'select',
					source: [
						  {value: 1, text: '请选择'},
						  {value: 2, text: '001'},
						  {value: 3, text: '002'}
					   ]
					}
				},{
				  field: 'takesteps',
				  title: '采取措施'
				},{
				  field: 'preventiveMeasures',
				  title: '预防措施'
				}]
		
			  });`
---end

**jqmaintenance.json:**

`[
    {
        "id": 1,
        "goods": "001",
		"acceptType": "保健食品",
        "spec": "001",
        "permit": "001",
        "lotNo": "001",
        "manufactureDate": "001",
        "updateexpiryDate": "001",
        "manufacturer": "001",
        "place": "001",
		"trays":"货位01",
		"maintenanceNum":"1",
		"circumstance":"良好",
		"maintenanceMeasure":"重点观察",
		"maintenanceConclusion":"好",
        "question": "001",
        "outlookQuality": "001",
        "packQuality": "001",
		"takesteps": "001",
		"preventiveMeasures": "001"
    }
]`
---end

**Comment by jackie88558** [comment]
当然是“-”了，因为你的json数据源没有相应的column field，当找不到数据源的时候，表格自动给“-”，这个在column的document里有对应的属性。

**Comment by liululululu** [comment]
@jackie88558 

那么这种情况呢：

**html**
`  <table class="table" id="qualitycheck_set_table">
           <thead>
              <tr>
                 <th>NO.</th>
                 <th data-field="sourceSingle">来源单号</th>
                 <th>单据类型</th>
                 <th>创建时间</th>
                 <th>商品编码</th>
                 <th>商品名称</th>
                 <th>规格</th>
                 <th>单位</th>
                 <th>生产厂商</th>
                 <th>批号</th>
                 <th>效期</th>
                 <th>生产日期</th>
                 <th>操作</th>
              </tr>
           </thead>
           <tbody>
           	  <tr>
              <td  rowspan="1"  colspan="13"  class="background-gray"><h5>来源单号：10011132</h5></td>
              </tr>
              <tr>
                 <td>1</td>
                 <td>1008611</td>
                 <td>入库单</td>
                 <td>2016-01-10</td>
                 <td>000002</td>
                 <td>咽康滴丸</td>
                 <td>YNA0.05g*30丸</td>
                 <td>盒</td>
                 <td>上海海虹实业（集团）巢湖今辰药业有限公司</td>
                 <td>20130412</td>
                 <td>2001-10-21 15:10:10.0  </td>
                 <td></td>
                 <td>
                <a data-toggle="modal" data-target="#myModalfileinput" class="btn-trigger-modal">上传</a> | <a data-toggle="modal" data-target="#myModalTip" class="btn-trigger-modal">预览</a>
                </td>
              </tr>
           </tbody>
        </table>`

**js:**
`var jqsettable = jq("#qualitycheck_set_table");
jqsettable.bootstrapTable({
	pagination: true,
	pageNumber: 1,
	pageSize: 15,
	pageList: [10,25,30],
	search: true,
});
//列分组根本么用 can't use code
jqsettable.bootstrapTable('mergeCells',{
	index: 1,
	filed: 'sourceSingle',
	colspan: 13,
	rowspan: 1
});`

如下图所示：

**Comment by dabros** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
请提供 jsfiddle
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
