### ISSUE TITLE
Search not working in bootstrap Table

### ISSUE THREAD

**Issue by RavirajParab** [wenzhixin/bootstrap-table#2307]
<table id="tblByLead"></table>

jQuery('#tblByLead').bootstrapTable({
                striped: true,
                pagination: true,
                pageSize: 3,
                pageList: [10, 25, 50, 100, 200],
                search: true,
              columns: [{
                  field: '0',
                  title: 'Lead Name',
                  sortable: true
              }, {
                  field: '1',
                  title: 'Percentage',
                  sortable: true
              },  ],
              data: [{'0':'Ramesh','1':'55'},{'0':'Pavan','1':'55'},{'0':'Suresh','1':'57'}]
          });

**Comment by dabros** [comment]
Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Fiddles and similar steps are needed for us to better help everyone, and for you to help yourself :)

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by RavirajParab** [comment]
https://jsfiddle.net/e2swhg57/

I've created jsFiddle. Hope that helps

**Comment by wenzhixin** [comment]
Why do you use number as field? 
You can remove the field to solve your problem: https://jsfiddle.net/wenyi/e2swhg57/1/.

But we recommend to use string type as field.

**Comment by wenzhixin** [comment]
Close this issue, if the problem exists reopen it, thanks!
