### ISSUE TITLE
Custom export link with option: Export All

### ISSUE THREAD

**Issue by bartosh44** [wenzhixin/bootstrap-table#2308]
I would like to use custom button for excel export like in this case: http://jsfiddle.net/wenyi/wc0zLpef/1/
but to export all rows from all paginated pages (pagination is on).

**Comment by dabros** [comment]
@bartosh44 - that link is broken, in future just paste link as text, if you click link button know which side is the url and always check your post

As to that option, see the doco:
http://bootstrap-table.wenzhixin.net.cn/extensions/
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/export
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#extensions/export.html

Pass in `exportDataType:'all'` or similar to handle pagination, all those options documented there can be used in direct calls, such as demonstrated in that fiddle, just read description and try them out

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html
