### ISSUE TITLE
Consuming Asp.net Web Service

### ISSUE THREAD

**Issue by joekuzma** [wenzhixin/bootstrap-table#2309]
When I attempt to consume an Asp.net web-service via the Bootstrap-table, the web service's ASMX page spits out the JSON within the "d" entity:

```
{"d":"[{\"id\":5910,\"rule\":\"INCLUDE\",\"ipFrom\":\"187.1.2.1\",\"ipTo\":\"187.1.2.255\"},{\"id\":5911
,\"rule\":\"INCLUDE\",\"ipFrom\":\"214.10.1.1\",\"ipTo\":\"214.10.1.255\"}]"}
```

I am no explicitly requesting the web service to do this, but it does it by default.

how can I parse this data with Bootstrap table?

**Comment by dabros** [comment]
@joekuzma - `responseHandler`

Many examples in github issues, SO and in official doco

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
http://issues.wenzhixin.net.cn/bootstrap-table/index.html
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#issues/353.html
