### ISSUE TITLE
Save and restore multi column seach/filter.

### ISSUE THREAD

**Issue by IvanKharpalev** [wenzhixin/bootstrap-table#2310]
I use column search for different columns and than I need to save this search like 
[{columnId: valueWeLookUp}, ....].

And than "apply" this search to the table again.

I am sorry it is already implemented. Or may be it is easy to do manually.. Please suggest!

**Comment by dabros** [comment]
@wenzhixin @djhvscf

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
First of all, **Multi column search** = **Filter Control extensiion**
@IvanKharpalev

**Comment by wenzhixin** [comment]
I think in the latest version filter-control extension supports this feature.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
