### ISSUE TITLE
Custom 

### ISSUE THREAD

**Issue by darshit7** [wenzhixin/bootstrap-table#2313]
Can I use custom CSS with bootstrap-table?
I am using bootstra-table in Django application. I want bootstrap table to look like Django admin change list table.

**Comment by dabros** [comment]
Yes

**Comment by dabros** [comment]
The plugin is just a helper for creating a boostrap theme table, the bootstrap-table.css is designed to build upon the boostrap base themes, but just look at that file and compare rules, shouldnt be hard to make it match up by adding classname to give your desired rules greater weight, or placing bootstrap-table.css above your theme file, or ect.

**Comment by darshit7** [comment]
Thanks!!

**Comment by wenzhixin** [comment]
@dabros is right, you can custom the style you like: http://www.creative-tim.com/product/fresh-bootstrap-table
