### ISSUE TITLE
bootstrap-table does not load if using data-formatter and data-editable on same th

### ISSUE THREAD

**Issue by JTCE** [wenzhixin/bootstrap-table#2314]
First, thanks for the great plugin! I'll certainly contribute when feasible.

Is it the intended function for data-formatter and data-editable to work independently? Meaning, they cannot be used on the same table header element?

Unfortunately, when both are used, the table does not populate with json data. I've put break points in the javascript formatter functions and can confirm they are never executed if both data-* options are used together.

Here's an example of the html markup, json file and javascript:

[
    {
        "id": 0,
        "name": "Item 0",
        "price": "$0"
    },
    {
        "id": 1,
        "name": "Item 1",
        "price": "$1"
    }
]

```
<table class="table table-striped table-no-bordered table-hover" 
                        data-toggle="table"
                        data-striped="true"
                        data-url="/_bst/data/data2/demo.response.json" data-height="299">
                        <thead>
                            <tr>
                                <th data-field="id">Item ID</th>
                                <th data-field="name" data-formatter="nameFormatter">Item Name</th>
                                <th data-field="price" data-formatter="priceFormatter" data-editable="true">Item Price</th>
                            </tr>
                        </thead>
                    </table>
```

```
 <script>
    function nameFormatter(value, row) {
        var icon = row.id % 2 === 0 ? 'glyphicon-star' : 'glyphicon-star-empty'
        return '<i class="glyphicon ' + icon + '"></i> ' + value;
    }

    function priceFormatter(value) {
        var color = '#'+Math.floor(Math.random() * 6777215).toString(16);
        return '<div  style="color: ' + color + '">' +
                '<i class="glyphicon glyphicon-usd"></i>' +
                value.substring(1) +
                '</div>';
    }
</script>
```

**Comment by dabros** [comment]
Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

We really need to see this replicated in a fiddle so we can then proof workarounds or modifications

Thanks

**Comment by fsauter** [comment]
Hi @JTCE ,

I think it's not possible right now. We can not use a bootstrap-table formatter and x-editable at the same time.

However there is a "display" option from x-editable which allows you to change the displayed text. We can not set the display option via data attributes since x-editable does not eval strings so that we could pass a function name (see http://stackoverflow.com/a/32736986/1544645).

What we can do as a workaround is a bit messy but it works: We're overriding the default display function of x-editable and define a custom data attribute with our formatter's function name (and call it in the default display funtion). See:

https://jsfiddle.net/fsauter/5shvjxej/

Hope it helps. I would like to implement native support for that, but currently I do not have the time

**Comment by dabros** [comment]
@fsauter - as a small note on that, untested, but you can pass a full x-editable object via js in columns array, removing all use of data-attributes for x-editable properties

https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable

No need to overwrite defaults or any other workaround, format will be exactly same as direct x-editable param object

**Comment by fsauter** [comment]
@dabros true, if you initialize your table via javascript. However if we want to initialize our tables **only** via data-attributes it comes in handy to use this workaround instead of rewriting all initialization of our tables from data-attributes to javascript.

**Comment by JTCE** [comment]
@dabros @fsauter 
Thank you both for responding in such a timely manner! Thank you both for the feedback!

I'm completely new to bootstrap and all the related plugins but have read alot of documentation over the last couple months. I must say, very well documented!

Here is a jsfiddle where I was able to achieve my desired results without using X-editable. 
https://jsfiddle.net/JTCE/pun0La35/ 
*NOTE: all credits are noted in this jsfiddle as there were many examples on the web that guided me to the end result.

The editable plugin is great and has it's place but unfortunately I needed to show the results in a textarea without the extra clicks. 

Just to pass on some of my testing results, x-editable conflicts with bootstrap-table in relation to the "Search", results are not found, if both plugins are used and results displayed in an object other than an <a> tag. The results were the same regardless of scrip order.

If I've misused or misunderstood how these plugins are suppose to function together, please let me know so I can adjust accordingly.

Thank you kindly!

**Comment by JTCE** [comment]
Closing this issue as the answer was provided the plugins work as expected.

Thanks again for the quick turn-around!

**Comment by RupaliMahadik** [comment]
how to add two data field in one cell. Need to add type/subtype in one cell

**Comment by jimgit** [comment]
Try using the formatter function.  [See this JSFiddle](http://jsfiddle.net/jimkennelly/mu759ceL/)

**Comment by RupaliMahadik** [comment]
thank you so much it worked

**Comment by RupaliMahadik** [comment]
how to reduce extra space of the column or reduce the width of the column.
<img width="1661" alt="screen shot 2018-02-05 at 9 51 39 pm" src="https://user-images.githubusercontent.com/33363853/35839549-fc6a2b7e-0abe-11e8-9193-429841cb9624.png">

**Comment by dabros** [comment]
@RupaliMahadik -  that feels like a different issue, so no suprise no reply on closed topic. Please open new issue if still a problem, and be cautious with closed posts, often better to open a new one and include in description/first-post a link to here using #[issue-id] or full url :)
