### ISSUE TITLE
表格合并，并且需要分页，需要修改删除 搜索（从新渲染）怎么处理？

### ISSUE THREAD

**Issue by docikaci** [wenzhixin/bootstrap-table#2315]
![image](https://cloud.githubusercontent.com/assets/7788102/15597355/cefd6b42-2401-11e6-8e8f-8ab4a67b3d5c.png)

如果在html里定义结构， 搜索时怎么刷新表格呢？ 后台怎么给数据比较合理？谢谢

**Comment by jackie88558** [comment]
如果你数据量不大，可以把数据全部加载到页面再分页，不要使用服务器端分页，这样搜索就没问题，直接用控件的就能自动刷新。如果数据量大，那么分页就要在后台做，搜索的话也必须把搜索条件传到后台重新做sql查询，这个比较复杂，但是问题也不大。
表格合并的话有rowspan，分页有pagination。
具体怎么弄，多看document和demo。

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/mergeCells.html
http://bootstrap-table.wenzhixin.net.cn/zh-cn/faq/

**Comment by kaerwang** [comment]
你这个点击分页后 还能正常使用mergecells吗
