### ISSUE TITLE
is it possible not to load the data when init bootstrap table

### ISSUE THREAD

**Issue by william807803** [wenzhixin/bootstrap-table#2317]
is it possible not to load the data when init bootstrap table until invoke 'refresh' ? 
can i make it not request the url when bootstrap table inited ?

<pre>
&lt;table data-toggle=&quot;table&quot;
       data-url=&quot;/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data1/&quot;&gt;
    &lt;thead&gt;
    &lt;tr&gt;
        &lt;th data-field=&quot;name&quot;&gt;Name&lt;/th&gt;
        &lt;th data-field=&quot;stargazers_count&quot;&gt;Stars&lt;/th&gt;
        &lt;th data-field=&quot;forks_count&quot;&gt;Forks&lt;/th&gt;
        &lt;th data-field=&quot;description&quot;&gt;Description&lt;/th&gt;
    &lt;/tr&gt;
    &lt;/thead&gt;
&lt;/table&gt;  </pre>

**Comment by dabros** [comment]
@william807803 - yes it is, as seen in a great many examples and in the doco

http://bootstrap-table.wenzhixin.net.cn/getting-started/
http://issues.wenzhixin.net.cn/bootstrap-table/index.html

Why dont you open the console and network requests and check for errors, likely error with that data request, missing js file or some other error in your page thats stopping this

https://developers.google.com/web/tools/chrome-devtools/
https://developers.google.com/web/tools/chrome-devtools/debug/command-line/

**Comment by wenzhixin** [comment]
You can remove the `url` option. And then call `refresh` method with new url: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/409.html

**Comment by xyluet** [comment]
@wenzhixin if i remove the url from init and assign it from refresh method, server side pagination won't work. any idea ?

**Comment by HUSSTECH** [comment]
@xyluet 

I had this same issue, I could not get the url to trigger after I had assigned it using the `refresh` method or by using `$('#table').bootstrapTable.defaults.url = 'url'`. Instead I finally got it to work by refreshing the options of the table as follows:
```
table_options = $('#table').bootstrapTable('getOptions');
table_options .url = 'url';
$('#table').bootstrapTable('refreshOptions',table_options);
 ```
after this everything works again for me. 

So it seems like the table options are not dynamically checked, but loaded on table init. For me, I think reloading the options as I did is an acceptable workaround/solution. It did not mess with the current table view on the screen, and it happened pretty fast. 😄

**Comment by Zhiwei1996** [comment]
if you use method 'load'

```
    $('#table').bootstrapTable('load', data);
```

you should notice that， data must be array and JS object

example:

```
    data = "[{"a": 1}, {"a": 2}]"  # error
    JSON.parse(data)  # parse json string to JS object  
```
使用`load`方法时数据必须是数组对象，然而我从后端get过来的默认是json string格式，这导致数据一直无法加载到bootstraptable，官方API文档中并没有提示这点

**Comment by Leehuseung** [comment]
how to solve this?

**Comment by Kazmin87** [comment]
in my case i can use queryParams option. it you return "false" request stopped

```
function queryParams(params) {
    let configId = getConfigId();
    if (configId > 0){
        params.configId = configId;
        return params
    }
    return false;
} 
```

[https://bootstrap-table.com/docs/api/table-options/#queryparams](url)

**queryParams**
Attribute: data-query-params

Type: Function

Detail:

When requesting remote data, you can send additional parameters by modifying queryParams.

If queryParamsType = 'limit', the params object contains: limit, offset, search, sort, order.

Else, it contains: pageSize, pageNumber, searchText, sortName, sortOrder.

**Return false to stop request.**

Default: function(params) { return params }

Example: [Query Params](https://examples.bootstrap-table.com/#options/query-params.html)
