### ISSUE TITLE
Always show the 'All' in pagination choices

### ISSUE THREAD

**Issue by nicgravel** [wenzhixin/bootstrap-table#2318]
Currently, only the near choice is show in the list. If we have 10,20,30,All  and the table contains 19 we only see 10 and 20.

Can we Show 10 and 'All' instead of the nearest number ?
People not always see that the table is not long enough and don't understand it don't contain more than that. With the All, they are sure they see everything.
p.s: It's also a cool thing to have when you want to make tests with selenium because you always have the 'All'.

**Comment by dabros** [comment]
@nicgravel - thats the `pageList` param

You can overwrite it, but as you noted it will only print 'All' (or whatever you pass in) when it has all smaller values.

So it is an interesting idea to either:

A. have an optional boolean (`alwaysShowAllOption` or something similar) that allows this to be overriden, or 

B. We can take the assumption it is always going to be a word with similar meaning, and allow no override, just assume true

The change in functionality would be around ~ https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1334

**Comment by wenzhixin** [comment]
Hello @nicgravel , you can set `smartDisplay` option to `false`:
http://jsfiddle.net/wenyi/e3nk137y/6828/
