### ISSUE TITLE
请问bootstrap-table初始化的时候会向url请求数据的，有没有办法初始化的时候不请求数据，当点击搜索时才发出请求；

### ISSUE THREAD

**Issue by william807803** [wenzhixin/bootstrap-table#2319]
请问bootstrap-table默认初始化的时候会向url请求数据的，有没有办法初始化的时候不请求数据，当点击搜索（搜索里有refresh请求代码）时才发出请求；

**Comment by qiujie8092916** [comment]
Trying to set `showRefresh` to `true`. And set `data` to `[]`

**Comment by wenzhixin** [comment]
初始化的时候不要填 url，然后点击搜索的时候调用 `refresh` 方法。

**Comment by kenybao** [comment]
这个问题解决了吗？
