### ISSUE TITLE
Problem a showing second page data

### ISSUE THREAD

**Issue by sylargray** [wenzhixin/bootstrap-table#2320]
Hi, I have a problem with displaying html content on the 2st page.

If I turn from the first page to the second, the content of the second page is identical to the first, and so on every page - in the transition to the second.
[
![2016-05-29 08 55 33](https://cloud.githubusercontent.com/assets/19629425/15630968/e558cbae-257b-11e6-9fa1-fb237cde796d.jpg)
![2016-05-29 08 55 48](https://cloud.githubusercontent.com/assets/19629425/15630969/e5b32838-257b-11e6-80e1-8d219814597e.jpg)
![2016-05-29 08 56 02](https://cloud.githubusercontent.com/assets/19629425/15630970/e5b38b8e-257b-11e6-8005-6bd55c816744.jpg)
](url)

A localhost don't have a problem, only web.
Thanks!

**Comment by dabros** [comment]
@sylargray - without a fiddle or much more detail, all i can recommend is the following:

1. Check data requests

I would almost bet money that (if you are using `sidePagination='server'`) that the data request itself is returning the wrong data (for any param), maybe something as simple as `limit` or `pagenumber`, maybe some interim step before data returned, maybe code in your `queryParam` or `responseHandler` (if set) is at fault (or could be used to correct this without touching data source itself).

If using `sidePagination='client'`, still a possibility, use `responseHandler` to help diagnose.


2. Keep eye on console for any errors (https://developers.google.com/web/tools/chrome-devtools/ for chrome, also see network panel for help with point 1)


3. Replicate issue in a fiddle

If still havent solved it, replicate it. Either you get a fiddle that can demonstrate this issue OR by recreating the core steps you realise whats happening wrong.

See https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports for example fiddles, and if server side and unable to expose data-url then you can mimic data using jsfiddle echo (http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery) or even just data-url from that server-side fiddle example (and can insert more complex html data inside `responseHandler` if you think that at fault)

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
