### ISSUE TITLE
angular with nested ng-repeat

### ISSUE THREAD

**Issue by softos** [wenzhixin/bootstrap-table#2321]
Using of nested ng-repeat angular directive is not working. 

```
<table class="fixedlayout table table-bordered table-condensed bootstrap-table" bs-table-control="bsTableControl">
   <tbody>
      <tr ng-repeat="item in items">
         <td class="width400">{{item.val}}</td>
      </tr>
    </tbody>
</table>
```

**Comment by wenzhixin** [comment]
I think our plugin doesn't support like this, you can try angular extension: http://issues.wenzhixin.net.cn/bootstrap-table/#integrate/angular.

**Comment by softos** [comment]
As coul see from the code samle above, I use bsTableControl. But the problem of that directive, that it doesn't hande translusion correctly.

**Comment by wenzhixin** [comment]
Consider as a feature.

**Comment by gaurav22031987** [comment]
softos: Are you able to use ng-repeat. I tried but not able to do that.

**Comment by softos** [comment]
@gaurav22031987: no, since that plugin doesn't handle transclusion properly, and according to @wenzhixin there is no intention to support this.

**Comment by gaurav22031987** [comment]
![gridissue](https://cloud.githubusercontent.com/assets/3023558/21753836/97fc705a-d5ba-11e6-88be-bf71d494c8ce.png)
Softos: Can we render this with bootstrap plugin.

**Comment by softos** [comment]
@gaurav22031987: sorry, I was not able to answer your message earlier. At the end I rendered the table without that plugin.
