### ISSUE TITLE
merge & layout

### ISSUE THREAD

**Issue by qiujie8092916** [wenzhixin/bootstrap-table#2322]
![example](https://cloud.githubusercontent.com/assets/18651667/15647161/819d426a-2694-11e6-9123-5ce12d233dbc.png)
Can bt did this?
I need display layout like this, but how?

**Comment by dabros** [comment]
See the following:

Can bootstrap-table provide tree-table mode , thanks ! #2285

Also do a wider search for "subtable", "group row", "merge", ect in github and [SO](stackoverflow.com/questions/tagged/bootstrap-table)

In short, you can decide upon a 'seamless' sub-table design using css and .detail-view (see that link), a 'proper' subtable with +/- and its own table headers and ect, or you can use a formatter to achieve that desired look and feel in the middle cells, or you can use `mergeCells` and other options


If want to treat each "1,2,3" as the actual row (and not show/hide those mini-rows individually based on search text) then a `formatter` might even be your best option. The whole contents stay searchable, you can use a simple formatter to print it off in some specific style that either mimic the table or can even be completely custom and searching and sorting treats each grouping ("1,2,3") as the actual row

If you do DO want search and sort but DONT want each "1,2,3" grouping to be treated as the actual row, then look at that link I posted and consider using `onPostBody` to check for sequential "1,2,3" ect and call `mergeCell` on those rows. 

I know very little about `mergeCell` type approach, @djhvscf or @wenzhixin might know more, but the basic approach and example code is increadibly simple, just check from top to bottom inside `onPostBody`, recording the count for rows that match the last unique value, calling `mergeCells` on all previous rows when next unique value found.

http://issues.wenzhixin.net.cn/bootstrap-table/index.html#methods/mergeCells.html

---

**Important**

Shouldnt be too hard either way, depends on what is the actual 'row' (for searching and sorting purposes) in your situation.

**Comment by qiujie8092916** [comment]
@dabros Thank you firstly
`mergeCells ` needs params, `index, field, rowspan, colspan`
And I need every row in first column or other columns will be merged like picture I showed it above, param`index` is a number, not a list or something I can make every row merged.
Could you have some idea?:)

**Comment by dabros** [comment]
@qiujie8092916 - what you have merged in that image above is the "1,2,3" and the last column

Index is accessible via `data-index` printed on every row, so `$element.parent('tr').data('index')`. Just iterate through all html rows in `onPostBody` using `$table.find('tbody tr').each(function(..){}`, then store index of last unique value found (ie. "1") then when next unique value found (ie. "2") then call `mergeCells` on both fields/columns using rowspan calculated from difference in indexes.

Each step is very simple and can be easily googled for similar code if unsure (ie "iterate through all table rows jquery", "get data attribute jquery", ect). And read what i posted at end again if you seriously try but cant get it working (we do need that fiddle in that case)

**Comment by qiujie8092916** [comment]
@dabros sorry i think i should have said more details.
there it is 
------------------------------------------------------------------------
i drew a table before
![before](https://cloud.githubusercontent.com/assets/18651667/15735220/6a4fb0a2-28c9-11e6-8140-9804bd21e1c9.png)

but customers need a layout like this
![after](https://cloud.githubusercontent.com/assets/18651667/15735246/a8f09650-28c9-11e6-97cb-1e5bf128fa6a.png)
so i drew the table that they expected(called `mergeCells `)
and i find several issues.
e.g.

1. the pagination

2. the row after merged when i put the mouse hover a row

And the below is i expected exactly
![expected](https://cloud.githubusercontent.com/assets/18651667/15735456/9d529882-28cb-11e6-8161-6b1ec93e76ef.png)

...so.. do you have some ideas or solutions?
(i dont know whether i explain clearly)

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/faq/ may be help @qiujie8092916

**Comment by dabros** [comment]
@qiujie8092916 - i have nothing to add more than ive said before, read it again,  there are multiple other ways to present nested data if merging doesnt work (though i fail to see why that not sufficient, the merge would assumingly be removed automatically during sorting, searching assumingly will hide uneeded subrows, you can always call 'refresh' or similar inside callbacks if thats not currently true, no way to for me to tell unless you implement and post a fiddle like directed above)

Ive already gone into detail earlier, just read it again and follow directions

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
