### ISSUE TITLE
How to...

### ISSUE THREAD

**Issue by Fruchtgummi** [wenzhixin/bootstrap-table#2323]
... style the button on the #toolbar?

I can't override this buttons. How can I pass a separate class?

Screenshot: http://prntscr.com/ba7py2

**Comment by dabros** [comment]
@Fruchtgummi 

Please fix your title to include whole question, then repeat and elaborate in body text

As to changing **default** toolbar (as seen in this simple fiddle: http://jsfiddle.net/wenyi/e3nk137y/33/) look at the following options (and any related options, just ctrl+f "icon", "button", "toolbar", ect if unsure)

`iconsPrefix`, `icons`, `iconSize`, ect

These options provide absolute control over the default toolbar buttons, you can also instead pass in custom toolbar with similar buttons and right align them, adding handlers to mimic advanced table functionality, but that doesnt seem needed in this case.

`buttonsClass` is another option, though that seemed to have no effect on toolbar when i quickly tested, but likely i wasnt using it in right context.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
