### ISSUE TITLE
 Change Header style only export

### ISSUE THREAD

**Issue by lukinha91** [wenzhixin/bootstrap-table#2324]
I would like to change the style of only the export header , could only use the style already exists in the grid , however a custom could not, help?

**Comment by dabros** [comment]
@wenzhixin @djhvscf - i recall you answered something like this, but cant see via quick search

**Comment by wenzhixin** [comment]
I think our extension does not support this feature.

**Comment by dabros** [comment]
@wenzhixin - are you sure?

There are style options in the export plugin
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/export
https://github.com/hhurz/tableExport.jquery.plugin#options

Another thought (though is more html manipulation) is that you could affect the table during the export process, not unlike how you internally (inside export plugin) remove pagination temporarily to export 'all', but that would only be if other significant changes needed to be made.

**Comment by wenzhixin** [comment]
please try what @dabros said @lukinha91.

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
