### ISSUE TITLE
有隐藏列时，data-click-to-select触发列计算不正确

### ISSUE THREAD

**Issue by bfoxxxxx** [wenzhixin/bootstrap-table#2326]
版本1.10.1
在隐藏第一列的情况下，后面设置列的data-click-to-select会计算不正确，会错位。
index = $td[0].cellIndex 源码中获取选中列index的计算是否没考虑到隐藏列？

**Comment by wenzhixin** [comment]
麻烦提供下 jsfiddle 以便调试，谢谢。
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by bfoxxxxx** [comment]
i can not visit jsfiddle, but i write it in other site, pls to check it.
http://runjs.cn/code/dflts89w

**Comment by wenzhixin** [comment]
?

**Comment by bfoxxxxx** [comment]
我注册不了jsfiddle ，我在runjs里写了例子，麻烦查看一下，谢谢
http://runjs.cn/code/dflts89w

**Comment by wenzhixin** [comment]
你的例子我看到的是个 R的动画。。。

**Comment by bfoxxxxx** [comment]
不好意思，代码需要发布操作，现在可以了
http://runjs.cn/code/dflts89w

**Comment by bfoxxxxx** [comment]
你好， @wenzhixin ，问题能解决吗？

**Comment by wenzhixin** [comment]
这个问题在刚刚发布的新版 v1.11.0 已经解决了，你试下。
