### ISSUE TITLE
<caption> causes Header to be displayed incorrectly in fixed height table

### ISSUE THREAD

**Issue by CBarratt63** [wenzhixin/bootstrap-table#2327]
I found a problem today when I added the "data-height" option to a table which had a <caption> tag in it.
Depending on the size of the caption, it either showed the table header twice, or show the bottom half of the header row underneath the top header row.

I used the basic table example to create a jsfiddle...

https://jsfiddle.net/cbarratt/ezru65yx/7/

Remove the <caption> tag and it all displays correctly.

Cheers,
chris

**Comment by dabros** [comment]
@CBarratt63 - caption not supported by bootstrapTable

https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue+caption

You can use other html elements to achieve that desired look and feel, or even use grouped column (and possibly css) if want it part of the table for export purposes

**Comment by CBarratt63** [comment]
Yes, that's what I am doing. I was logging purely because I didn't find the issue when I searched for it yesterday...obviously I didn't search hard enough ! 
Thanks.
