### ISSUE TITLE
How to get total footer for current page?

### ISSUE THREAD

**Issue by katrina-engelbrecht** [wenzhixin/bootstrap-table#2328]
Hi,
I want to get total footer for the current page not all the rows. How can I attrieve that?

Best Regards,
Katrina

**Comment by dabros** [comment]
Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Please create a fiddle that has totals working normally, any datasource (including direct js array) is fine, using link above for base fiddles to work from

**Comment by katrina-engelbrecht** [comment]
Hello Daniel,
here is my fiddle. http://jsfiddle.net/38u7L3ep/4/ in the total footer I 
have written my question there. Hope can get your update/answer soon.

Best Regards,
Wei Engelbrecht



Von:    Daniel Brose <notifications@github.com>
An:     wenzhixin/bootstrap-table <bootstrap-table@noreply.github.com>
Kopie:  katrina-engelbrecht <W.Engelbrecht@wzl.rwth-aachen.de>, Author 
<author@noreply.github.com>
Datum:  01.06.2016 01:30
Betreff:        Re: [wenzhixin/bootstrap-table] How to get total footer 
for current page? (#2328)



Please see 
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
Please create a fiddle that has totals working normally, any datasource 
(including direct js array) is fine, using link above for base fiddles to 
work from

**Comment by wenzhixin** [comment]
Hello @katrina-engelbrecht , consider this issue to a new feature, may be we can add a parameter like this:
```
function (data, curData) {
    ...
}
```

Here is a workaround for your problem: http://jsfiddle.net/wenyi/38u7L3ep/5/.

**Comment by katrina-engelbrecht** [comment]
Thank you a lot!!!!

**Comment by dabros** [comment]
@wenzhixin - i was already doing a fiddle up with just that, but got stopped temporarily when `console.log($table.bootstrapTable('getOptions'))` and similar never showed options array, just the jquery object $table (even after saving to var, with $table or $('#table'), test with latest fiddle to prove). Any thoughts on why, and is that what you see?

**Comment by wenzhixin** [comment]
You are right @dabros , `$table.bootstrapTable('method')` will return jQuery object before the table initial.

**Comment by dabros** [comment]
@wenzhixin - so add console.log to part of your fiddle above:

```javascript

   var options = $table.bootstrapTable('getOptions');
   var pageSize = options.pageSize || 10; // init pageSize
   var pageNumber = options.pageNumber || 1;
   console.log(options,pageSize,pageNumber);

```

I get what your saying in that it must fit in with the chaining aspect, the method returns the jquery object so further operations can be performed, a consistent approach with other exposed methods. 

If you test it, you see the jquery object in options and actual values in the others, but how you can you debug the return of `getOptions` (as an example method) via console.log or similar then?

**Comment by wenzhixin** [comment]
The fisrt time to get options is error, then it is correct, so I use:
```
var pageSize = options.pageSize || 10; // init pageSize
var pageNumber = options.pageNumber || 1;
```

it is better to add a parameter to 
```
function (data, curData) {
    ...
}
```

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/
