### ISSUE TITLE
how to $('#table').bootstrapTable('SET__Options')

### ISSUE THREAD

**Issue by IvanKharpalev** [wenzhixin/bootstrap-table#2329]
I do 
var values = $('#table').bootstrapTable('getOptions').valuesFilterControl;
and than I need to update values and apply this changes to bs-table.
how can I $('#table').bootstrapTable('SET_Options') ??

Thank you to any advice or explanation.

**Comment by dabros** [comment]
Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

A Fiddle and more explanation is needed to help you with this

If using filter control or similar plugin, look at official example and try to incorperate working code into one of the example base fiddles (see link above)

Then explain more on your use case, when its needed, what it is needed to achieve, why this specific approach was decided upon

**Comment by wenzhixin** [comment]
`refreshOptions` maybe help you: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/refreshOptions.html
