### ISSUE TITLE
Detail table expanding bug

### ISSUE THREAD

**Issue by softos** [wenzhixin/bootstrap-table#2331]
There is a bug in expanding row code:

`$tr.after(sprintf('<tr class="detail-view"><td colspan="%s"></td></tr>', $tr.find('td').length));
`
shall contain 

`$tr.find(' > td');`, i.e. immediate child. The poblem can occur if you have subtable in any cell (e.g. in popup container).

**Comment by dabros** [comment]
@softos - thanks for spotting a potential issue, we do however need a fiddle to replicate and demonstrate it, which will also be used to test a fix before the PR can be approved

Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by softos** [comment]
@dabros : here you are https://plnkr.co/edit/bvSKLdX8dFzyEH1FFtZo?p=preview
If you click on **click me** cell before expanding the first row, then you will get mess.

if you don't have `table-layout: fixed!important;` styling, then everything is shown correctly, despite the colspan is calculated wrong.

**Comment by wenzhixin** [comment]
Why do you want to use `table-layout: fixed!important`?

**Comment by softos** [comment]
Because I need control over the cell width. Otherwise cell width is variable, depending on the content. 
e.g. cell with content "I" will have another width than cell with content "W".

**Comment by dabros** [comment]
@softos - then look at the `width` option for columns, or even `max-width`, `min-width` applied via css

There are many issues that touch on width of columns, just search for them

https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue+width

#2281 is just one example, but good if using long words and very strict on column widths

**Comment by softos** [comment]
The reason is, that I want to set fix width of the first two columns and distribute space evenly between the remaining columns. Without fixed layout it doesn't work properly. In any case it's a bug, if code calculates colspan="107" if I have only 17 columns.

**Comment by softos** [comment]
@wenzhixin: and just to clarify. It's not a CSS issue. It's wrong code, which has an impact with particular CSS settings

**Comment by wenzhixin** [comment]
other related issues: https://github.com/wenzhixin/bootstrap-table/issues?utf8=✓&q=table-layout+fixed
