### ISSUE TITLE
Uncaught Error: Unknown method: getVisibleColumns

### ISSUE THREAD

**Issue by yinzhili** [wenzhixin/bootstrap-table#2332]
I can find the getVisibleColumns method in the documentation, but in fact this method doesn't exist.

**Comment by dabros** [comment]
@yinzhili - as noted already in #2290, you might need the latest dev version for that, but `getHiddenColumns` is in latest official release

#2290 
https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue+getVisibleColumns

**Comment by yinzhili** [comment]
@dabros thanks.

**Comment by wenzhixin** [comment]
OK, I will do that @dabros.

**Comment by wenzhixin** [comment]
reverted the doco.
