### ISSUE TITLE
有 Group Columns 时, Cookie 加载的标头会混乱, 该隐藏的父级标头没有隐藏

### ISSUE THREAD

**Issue by shenyubao** [wenzhixin/bootstrap-table#2333]

**Comment by wenzhixin** [comment]
提供下 jsfiddle 例子，
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
@
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!
