### ISSUE TITLE
How to change a bootstrap-table prop?

### ISSUE THREAD

**Issue by NapChen** [wenzhixin/bootstrap-table#2334]
I have builded a table and now I want to change a prop of the table ,like `filterControl=false`.
I have tried 
`'filterFlag'=false;
$table.filterControl('filterFlag');
 $table.bootstrapTable('resetView');`
But it didn't work.
Any idea will be kind .

**Comment by wenzhixin** [comment]
You can use `refreshOptions`: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/refreshOptions.html

**Comment by NapChen** [comment]
@wenzhixin Thanks，its what i am looking for .
