### ISSUE TITLE
how update cell and don't refresh

### ISSUE THREAD

**Issue by pulert** [wenzhixin/bootstrap-table#2337]
when i update cell data, i not want refresh table, how?

**Comment by wenzhixin** [comment]
I think you can use `updateRow` method: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/updateRow.html

**Comment by Cure100061148** [comment]
Excuse me, how  could I use updateRow method without affecting checkbox behavior in Bootstrap table. 

Now every checkbox is in each row of my bootstrap table. and each checkbox has a formatter function like this:
 ```
function stateFormatter(value, row, index) {
      if (value === true)
    return {
      disabled: false
    };
  else
    return {
      disabled: true
    };
}
```

and this is how I define structure of bootstrap table using HTML:
```
<div id="tableToolBar"></div>
<table id="table"
           data-toolbar="#tableToolBar">
  <thead>
    <tr>
      <th data-checkbox="true" data-formatter="stateFormatter"></th>
      ......
    </tr>
  </thead>  
</table>
```

**Comment by wenzhixin** [comment]
@Cure100061148 Please create a new issue and provide jsfiddle, thanks.
