### ISSUE TITLE
How to keep table expanding after append a new row?

### ISSUE THREAD

**Issue by katrina-engelbrecht** [wenzhixin/bootstrap-table#2339]
Hello,
here is my fiddle: http://jsfiddle.net/Wei_Engelbrecht/odqftn1v/1/
by clicking button "Neue Kategorie" it will append a new row to table. But all the expanding rows will be collapsed. How to prevent it? If I set pagination to true, is it possible to keep expanded rows open after page to the previous/next?
Of course I can define an array to get all indexes when the row is expanded. But maybe there is a better way to do it?
Thanks a lot!
Best Regards,
Katrina

**Comment by wenzhixin** [comment]
The plugin doesn't support this feature.

**Comment by wenzhixin** [comment]
ref #1593
