### ISSUE TITLE
Bootstrap Table 冻结列功能IE浏览器兼容性

### ISSUE THREAD

**Issue by zyz** [wenzhixin/bootstrap-table#2340]
[http://www.th7.cn/web/js/201601/153832.shtml](url)

**Comment by wenzhixin** [comment]
目前不支持。

**Comment by zyz** [comment]
http://stackoverflow.com/questions/19737306/bootstrap-3-responsive-table-with-fixed-first-column
还有这个回答，参照修改下。
另外还有个功能，固定列（不能排序）
