### ISSUE TITLE
collapseAllRows/expandAllRows with togglePagination don't work

### ISSUE THREAD

**Issue by katrina-engelbrecht** [wenzhixin/bootstrap-table#2341]
Hello,
I have a bootstrap table with pagination. I want to use buttons to collapse/expand alll rows in the whole table not only the current page. But by using 
$('#table').bootstrapTable('togglePagination').bootstrapTable('collapseAllRows').bootstrapTable('togglePagination'); and
$('#table').bootstrapTable('togglePagination').bootstrapTable('expandAllRows').bootstrapTable('togglePagination');
the table makes no change. 
Can you have a look into this problem? 
This is my fiddle: http://jsfiddle.net/Wei_Engelbrecht/ot7pbujz/
Best Regards,
Katrina

**Comment by djhvscf** [comment]
This is a feature because the logic works only for the current page and in this moment expand/collapse all rows in all pages is not supported.
