### ISSUE TITLE
extra fields in detail view

### ISSUE THREAD

**Issue by yrg23** [wenzhixin/bootstrap-table#2342]
hi, firstly thank you for your awesome work.

i am fetching data from mysqli with php+html and i am trying to activate detail view section. but, i see there are extra fields in the section like these;

_id: undefined
_class: undefined
_data: [object Object]
id: 1 // I wanna see only this
_id_id: undefined
_id_class: undefined
_id_rowspan: undefined
_id_title: undefined
_id_data: [object Object]

what's the prob you think. thanks

**Comment by wenzhixin** [comment]
Table from html we will add some properties to the rows: http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-html.html. But I think in your case you can use restful API:
http://issues.wenzhixin.net.cn/bootstrap-table/#options/client-side-pagination.html
http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html
