### ISSUE TITLE
IE9以下（包含IE9）事件 KEY与脚本ALL冲突(jQuery1.7.2,Bootstrap-table V1.10.0)

### ISSUE THREAD

**Issue by bhwebxu** [wenzhixin/bootstrap-table#2345]
IE9以下（包含IE9）事件 KEY与脚本ALL冲突(jQuery1.7.2,Bootstrap-table V1.10.0)
![bstable error](https://cloud.githubusercontent.com/assets/1984499/15770226/7d62332e-2994-11e6-99e9-637bd933ab8c.png)
![error 2](https://cloud.githubusercontent.com/assets/1984499/15770227/7d6571b0-2994-11e6-9cb9-d674164896fa.png)
![error3](https://cloud.githubusercontent.com/assets/1984499/15770228/7d66cc04-2994-11e6-806e-0425079e66ff.png)

**Comment by wenzhixin** [comment]
请用 1.8.0 以上版本，另外现在不支持 IE9 以下浏览器，IE8下有 bug
