### ISSUE TITLE
Hidden row & search

### ISSUE THREAD

**Issue by jjboy91** [wenzhixin/bootstrap-table#2349]
Hi,

In a table I have few hidden rows. 
When I use the search bar, hidden rows that match the search are visible again.
Is it a normal behaviour ?

An example : http://jsfiddle.net/50ajnpnr/

Is there a way to ignore hidden rows on search ?

Thanks !

**Comment by wenzhixin** [comment]
I think it is a bug.

**Comment by jjboy91** [comment]
Hi,
Thanks for the reply.
Do you have an idea for the fix ?
I'm not an expert but maybe check for display:none in the search function ?

**Comment by wenzhixin** [comment]
ref #750, fixed in the client side, now does not support server side.
