### ISSUE TITLE
Style customization...

### ISSUE THREAD

**Issue by Juniornativa** [wenzhixin/bootstrap-table#2354]
Hi, i'd like to give a recommendation!
I've been using bootstrap table in all my projects, and i really think it's the best one!
I've tried jquery.datatable and i'm really in bootstrap table, it's easier to use, more lightweight, everything is easier to implement, but i think the option to change theme is missing, although bootstrap is the core of bootstrap table, that would be nice if we could give it an attribute like "Theme" where i could customize our style using others frameworks like Google Materialize, Semantic UI, Bootstrap 4, UIKit, Foundation and so on! This feature is the only thing that has attracted my ayes on jquery.datatables. Take a look at those links below:

https://getmdl.io/started/index.html
https://datatables.net/examples/styling/material.html

**Comment by AlphaJuliettOmega** [comment]
Ahw, I want to use Bootstrap-table's functionality with UiKit
Is the theming hard-coded into the core?
i'm going to dive into the styling of it now and see if I can repurpose it.

**Comment by Falseee** [comment]
Any Update here, is it possible to use semantic ui ?

**Comment by wenzhixin** [comment]
[CSS Frameworks ](https://bootstrap-table.com/themes/)

Added:
* Semantic UI
* Bulma
* Materialize
* Foundation
