### ISSUE TITLE
Show only some columns # Not all columns 

### ISSUE THREAD

**Issue by ChiragDhangar** [wenzhixin/bootstrap-table#2357]
How can i show only selected column at load of table 
Because bydefault table show all columns but i dont want all columns 
i want only some columns at load of tables 

how can i do it ?

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
Use data or url?

**Comment by ngocnv371** [comment]
@ChiragDhangar I think this is what you want
https://jsfiddle.net/ngocnv371/8rzr6ov5/6/

**Comment by ChiragDhangar** [comment]
@ngocnv371 

Yes you get my problem.
But i try your solution but it is not working in my case 
I dont know why 
@wenzhixin  refered https://jsfiddle.net/ngocnv371/8rzr6ov5/6/
to understand my problem
but it is not working.



please help us

**Comment by ngocnv371** [comment]
@ChiragDhangar what's not working? The table doesn't load? The column's still not hidden?

**Comment by ChiragDhangar** [comment]
"Loading please wait " the message is not coming
