### ISSUE TITLE
iconsPrefix for FontAwesome it dosen't work

### ISSUE THREAD

**Issue by torisoft** [wenzhixin/bootstrap-table#2358]
Hi
After set data-icons-prefix = "fa" icons not to change.
actually the change is do this:
class="fa glyphicon-th icon-th"

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/337.html
ref #337

**Comment by tylerecouture** [comment]
This is closed but doesn't appear to be working? using v1.10.1
I have: `data-icons-prefix='fa'`
But result is: `<i class="fa glyphicon-th icon-th"></i>`

**Comment by wenzhixin** [comment]
You need to set the icons:
```
window.icons = {
    refresh: 'fa-refresh',
    toggle: 'fa-toggle-on',
    columns: 'fa-th-list'
};
```

**Comment by slonob** [comment]
See: [How to use Font Awesome 5 on VueJS Project](https://medium.com/front-end-weekly/how-to-use-fon-awesome-5-on-vuejs-project-ff0f28310821)

Add this to script on the template or App.vue:
import { dom } from '@fortawesome/fontawesome-svg-core'

dom.watch()
