### ISSUE TITLE
How to set class for active row 

### ISSUE THREAD

**Issue by warwickfoster** [wenzhixin/bootstrap-table#2359]
When I click a row I want to add a class to this row to indicate that it is the active row.

$masterTable.on('click-row.bs.table', function (row, $element) {
    //what do I put here
    UpdateExpense($element);
});
$element is the data that the row is mapped too
Row is the object from the table but I am unsure which part of it references the active row.

Can anyone point me in the right direction?

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/563.html can help.

**Comment by warwickfoster** [comment]
Thank you wenzhixin

**Comment by dabros** [comment]
If this solution worked, please share some working code and/or tips on how you implemented, then close this issue

Thanks
