### ISSUE TITLE
data-events    

### ISSUE THREAD

**Issue by liululululu** [wenzhixin/bootstrap-table#2361]
1."data-format"、“data-events” i can't normal  use  
2.jsfiddle  i can't sign in

For example code:
《html》
`<table>
      	<thead>
          <tr>
          	  <th>NO.</th>
              <th>供应商编码</th>
              <th>供应商名称</th>
              <th>所属供应企业</th>
              <th data-editable="true">业务员</th>
              <th data-editable="true">身份证号</th>
              <th data-format="detailsdrugsFormat" data-events="detailsdrugsEvents">授权药品</th>
              <th>操作</th>
          </tr>
        </thead>
</table>`

《js in seaJs》
`function detailsdrugsFormat(value ,row ,index){
	return '<a class="authorize_drugs_details">管理授权药品</a>'
};
			
var detailsdrugsEvents = {
	'click .authorize_drugs_details': function( e, value ,row ,index){
		jq('#div_acas_content').load('firstcamp/supplier_authorize_addNew.html');
	}
};`

**Comment by wenzhixin** [comment]
请提供 jsFiddle
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by liululululu** [comment]
![image](https://cloud.githubusercontent.com/assets/10783450/15845460/ec247dee-2ca5-11e6-95c9-a0b0a9a1402c.png)
can't sign up   in eyery time,i not know why?

**Comment by dabros** [comment]
@liululululu - nothing to do with us, dont know and doesnt matter

You dont even need an account to create a fiddle, or fork and tweak an existing

Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Fiddles and similar steps are needed for us to better help everyone, and for you to help yourself :)

**Comment by wenzhixin** [comment]
Please see the example: http://issues.wenzhixin.net.cn/bootstrap-table/
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
