### ISSUE TITLE
how to create an event for wenzhixin bootstrap table

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#2362]
hello

can you give me some insights how to create an event for wenzhixin bootstrap table while i research on my own... 

i bet this would be like extending the plugin... 

an example event is like onClickSave... 
which would be used like:
$table.bootstrapTable({
    onClickSave : {
        //put codes here
    }
});

(this is my custom event...) which is triggered on click of my save button to save a row to database...

thanks i hope for your feedback and help....

**Comment by dabros** [comment]
@joomlaA1 

As we have explained many times before, you need to lay out the scenerio and go from the start

There is not a single new event needing to be added to bootstrap table to handle any custom action, just add event handler for the button you linking it to. Thats a simple step with many many many many examples online and step by step tutorials for that

The official examples even show a simple example of this for you: http://issues.wenzhixin.net.cn/bootstrap-table/index.html

Please research that and close this issue, using [SO](stackoverflow.com) or other proven research sources if issues implementing as has absolutely nothing to do with bootstrap table itself, you just adding a click handler for a button, see example and add handlers during `onPostBody` or similar event if needed.
