### ISSUE TITLE
sandywalker/webui-popover html not showing on page change or after column sorting

### ISSUE THREAD

**Issue by AdiFloDev** [wenzhixin/bootstrap-table#2363]
Hi,
I'm having a problem with using sandywalker/webui-popover and bootstrap table.
I read the issues regarding the use of bootstrap's tooltip and popover but I need to load html content in a popover which is why I'm trying to use webui-popover.
However, the following code works on initial table load but popovers don't show when changing page or sorting columns.
Can someone give me some clues to get through this ?

$('#table-js-activity').bootstrapTable({
	
	onLoadSuccess:function(row){
		
		//console.log(row[0]);	
		//$('.popover_inbox').webuiPopover();
		
		$.each(row, function (key, array) {
			
			//console.log(key + ' : ' + array['id']);	
			//console.log(value.content);	
			var row_designation = array['designation'];
			var row_content = array['details'];

			$('.popover_inbox_' + array['id']).webuiPopover(
// Parameters to be externalized later
{ 
				title: row_designation,
				content: row_content,
				placement:'auto',
				container: document.body, 
			    width:'800',
			    height:'350', 
			    trigger:'hover',
			    animation: 'fade', 
			    delay: {
			        show: null,
			        hide: 300
			    },
			    padding:true,
			    type: 'html'
			});
		});
	},
...

**Comment by dabros** [comment]
@AdiFloDev - if adding custom code to body content, use `onPostBody`, that way triggered every time table body is refreshed/paginated/ect.

You can see in the official examples when events are actually triggered, just watch console when using this example: http://issues.wenzhixin.net.cn/bootstrap-table/index.html

**Comment by AdiFloDev** [comment]
Hi,
Thank you for your answer but something is still unclear about how I can get rows data with onPostBody  as it doesn’t take any parameters as onLoadSuccess does.

Here is what I get when I use :

$('#table-js-activity').on('all.bs.table', function (e, name, args) {

	console.log(name, args);
});

post-body.bs.table array is empty.

**Comment by dabros** [comment]
@AdiFloDev - please setup a fiddle and we can look at this more, dummy data via js array is fine, just needs to replicate core issue (pagination breaking your tooltips)

Examples and guide: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
You can use `getData` method to get the data loaded.
Close this issue, if the problem exists reopen it, thanks!
