### ISSUE TITLE
Table Toolbar search issue with hidden columns

### ISSUE THREAD

**Issue by swarooppallapothu** [wenzhixin/bootstrap-table#2365]
Table rows filtered with hidden columns.

Step 1: Create table with hidden columns.
Step 2: search for some text related to hidden column text.
Result: row are filtered with queried text, text not there in any column for filtered rows but text is there in hidden columns.

**Comment by djhvscf** [comment]
Can you provide an example, please?

**Comment by harishmk** [comment]
https://jsfiddle.net/8mkpd3qd/61/
Cells in ID column are all hyperlinks to google.com
type google on the search, and all rows are displayed.
i think the search should be on visible text.
