### ISSUE TITLE
Loading Ajax data with nested Arrays

### ISSUE THREAD

**Issue by Physium** [wenzhixin/bootstrap-table#2366]
It seems like loading data from Ajax view will only work if the data is in a single array such as 
`var data = [
            {
                "id": 0,
                "name": "Item 0",
                "price": "$0"
            },
            {
                "id": 1,
                "name": "Item 1",
                "price": "$1"
            },
            {
                "id": 2,
                "name": "Item 2",
                "price": "$2"
            }
        ];`

Is it possible if
`var data = [
            {
                "id": 0,
                "name": "Item 0",
                "price": "$0",
"tags": [1,2,3,4]
            },
            {
                "id": 1,
                "name": "Item 1",
                "price": "$1",
"tags": [1,2,3,4]
            },
            {
                "id": 2,
                "name": "Item 2",
                "price": "$2",
"tags": [1,2,3,4]
            }
        ];`

and as a result shows the array values as part of a rowspan within the id.

![screen shot 2016-06-09 at 3 18 05 pm](https://cloud.githubusercontent.com/assets/7604837/15921639/56b9c1c2-2e55-11e6-84e0-4fbb0b4e645f.png)

**Comment by avbdr** [comment]
hello,
First of all thank you for a great library. its really great. 
Its appeared that I would need same functionality in my project as well. 
What i need to do represents following mockup: http://smarttechdo.com/~avb/cashflow.html
Wondering if there is a way to implement that using this library. 
Im getting lazy to build tables with php :)

**Comment by dabros** [comment]
Look at the `responseHandler` option

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
http://issues.wenzhixin.net.cn/bootstrap-table/index.html

There are many examples of this being used, and as doco states it is passed in your raw data and allows to tweak or change whatever to make it the exact format you want.

That can include dropping or adding indexes, drastically restructuring overall structure or even just calling `.join` or `.concat` or similar on that nested array

**Comment by Physium** [comment]
Hey @dabros  thanks for the reply! I dont really understand what the documentation states about response handler. All it says is that 
> Before load remote data, handler the response data format, the parameters object contains: 
res: the response data.

I really do not quite understand the english here.

**Comment by avbdr** [comment]
i have a feeling that reply is completely unrelated to the question

**Comment by dabros** [comment]
@Physium @avbdr - look at examples, like that link above

Add the `responseHandler` option as shown there and see that it is called AFTER data request but BEFORE its loaded into actual table, allowing you to do whatever you want to the data to make it match exact format you desire

**Comment by Physium** [comment]
@dabros hey thanks for taking time to explain. but that examples seems to be seriously all over the place with different ways to do things. Is there a simple demo on how responseHandler actually work? I cant seem to get it to work.

**Comment by dabros** [comment]
@Physium - go to example, click 'view source on github' in top right, ctrl+f "responseHandler"

There are only 2 bits of code related to it, and there is no further way to describe it then has already been said, just look at it and use it

https://github.com/wenzhixin/bootstrap-table-examples/blob/master/welcome.html


`data-response-handler="responseHandler"`

```javascript

    function responseHandler(res) {
        $.each(res.rows, function (i, row) {
            row.state = $.inArray(row.id, selections) !== -1;
        });
        return res;
    }

```

**Comment by Physium** [comment]
@dabros thanks alot for the explanation! how bout the handling of col-span / row-span?

**Comment by dabros** [comment]
@Physium - what handling???

You have stated no need for colspan or rowspan, what you have stated is data passed in with nested arrays is by default printed as nested rows. 

First time ive heard of that as an issue, but use `detailFormatter` or `responseHandler` to account for that, either by flattening that data array as formatted string in `responseHandler` (as seen above) or by using `detailFormatter` to print off same in that column

Both have same effect, both have examples, try them

**Comment by Physium** [comment]
@dabros thanks for the advice. I'll close this issue!
