### ISSUE TITLE
Unable to refresh Bootstrap table without data-toggle

### ISSUE THREAD

**Issue by baxhul** [wenzhixin/bootstrap-table#2367]
I am using bootstrap table with data from ajax call. So I am not using the data-toggle option for the table, as that one is used for building the table without JS. The problem is that I am not able to refresh the table in this case. $table.bootstrapTable('refresh'); doesn't work unless I add the data-toggle option which I don't need.

**Comment by dabros** [comment]
Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Fiddles and similar steps are needed for us to better help everyone, and for you to help yourself :)

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
