### ISSUE TITLE
Filter Control two columns hide one

### ISSUE THREAD

**Issue by dfmaxwell** [wenzhixin/bootstrap-table#2368]
I have two fields returned in my json array from the server: eventid and eventname.  I would prefer to hide eventid from display, but use a filter control with eventid as the value and the eventname as the text and allow the filter to go to the server with the eventid and fetch the search results.

I've tried this, if I render the filter control from the server with the eventid in the value and the eventname in the text of a select and put it on the eventid column it works just fine.  But I get the id of the event.  If I try this same technique on the eventname I can get the filter to bring back the results from the server, but they will not render.  I tried to use a column formatter to display the eventname and while I can get it to appear in the console I can't get it on screen.

I'm not sure how I can effectively make a jsFiddle because of the data lying in an internal system.

I am wondering if the way the filter works with the json array is filtering out everything since the eventid does not match the event name.

Thanks,
Daniel

**Comment by Falseee** [comment]
I close this issue because its almost 2years old.
If you still need help pls reopen the issue and provide us an example with fake/random data.
