### ISSUE TITLE
Multiple identical XHR requests sent during a filter-content operation

### ISSUE THREAD

**Issue by waspinator** [wenzhixin/bootstrap-table#2370]
Multiple identical XHR requests sent during a bootstrap-table-filter-control operation

Open developer tools
Type in a character into one of the filter-control boxes
Observe the XHR requests

![xhr](http://i.imgur.com/UdC4IES.png)

http://jsfiddle.net/waspinator/dLfw93z6/

**Comment by anujism** [comment]
I am also having the same issue.

**Comment by Falseee** [comment]
This issue is 3 years old, also i cant reproduce this issue on your jsfiddle.
Should this bug still exists pls reopen the issue.
