### ISSUE TITLE
localStorage or sessionStorage table state saving.

### ISSUE THREAD

**Issue by davellanedam** [wenzhixin/bootstrap-table#2371]
Awesome work! I know there is the cookie extension, but it would be great if the table state could be remembered on localStorage or sessionStorage also, how can I archive this for active page, column selection, number of rows per page, filter control, sort name and sort order based on table-id? Would be great to choose session or local storage for saving. Million thanks for your help :)

**Comment by dabros** [comment]
@davellanedam - given that this is a custom functionality request, not a bug report or a core feature request, id recommend reading https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker and instead posting to SO as directed there

**Comment by djhvscf** [comment]
I think we can improve the cookie extension adding an option where we can specify if we want to use the localStorage, sessionStorage or cookie

**Comment by davellanedam** [comment]
@djhvscf That would be just amazing! =)

**Comment by djhvscf** [comment]
Ok, I'm going to work on it :+1:

**Comment by djhvscf** [comment]
See this https://github.com/wenzhixin/bootstrap-table/pull/2463

**Comment by davellanedam** [comment]
This is great news! Any date for the release version?

**Comment by djhvscf** [comment]
Not sure @davellanedam, lets ask @wenzhixin

**Comment by pnm** [comment]
Looking forward for the localStorage option at the earliest (any dates?).

One problem we have encountered in cookie usage is that if there are multiple tables and large number of columns, size of cookie becomes high and  apache rejects the request as bad request (8KB limit ?)

**Comment by siblancoMember** [comment]
Hey folks, 

i have updated my bootstrap-table and the corresponding bootstrap-table-cookie plugin (from V1.15.3 to V1.19.1) and explored following bug?:

When i set the "data-cookie-storage" attribute to "sessionStorage" and at the same time "data-cookie" to true, it doesn't do anything. But when i remove the "data-cookie" attribute, it works.
Tested the same scenario with "localStorage". No problems with that.

Any ideas?
