### ISSUE TITLE
Best practices for utilizing server-side template?

### ISSUE THREAD

**Issue by niczak** [wenzhixin/bootstrap-table#2374]
Hello there!  I love this plugin but am struggling to see how I can use the ajax functionality. 

I am using a Twig template to render HTML (it's a very heavily styled table) but I know that this plugin doesn't support appending HTML directly via ajax calls.  Given that I can't be the only person using Twig/Blade/etc, what is the best way to leverage the ajax functionality of this plugin?

Twig Template: (this represents a single table row)
```
    <tr>
        <td class="centerCell">
            <img src="/images/social-icons/{{ review.type }}.png" style="height:32px;" title="{{ review.type }}"/>
        </td>
        <td data-rating="{{ review.rating }}" class="centerCell">
            <div class="starContainer" style="min-width: 72px">
                {% for i in 1..5 %}
                    <span class="gfsStar{% if i <= review.rating  %} on{% endif %}"></span>
                {% endfor %}
            </div>
            <div class="ratingBadge">{{ review.rating }} / 5</div>
        </td>
        <td>
            <div {% if review.content|length > 275 %} class="block-with-text" {% endif %}>{{ review.content }}</div>
            {% if review.content|length > 275 %} <div class="over-flow-indicator">[Read more]</div> {% endif %}
        </td>
        <td>{{ review.time }}</td>
        <td class="centerCell">{{ review.author }}</td>
        <td>
            <a class="viewButton" href="{{ review.url }}" target="_blank">View</a>
        </td>
    </tr>
```

**Comment by wenzhixin** [comment]
What data response from the server?
Maybe you can try [Transform from your render table](http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-html.html), but I think this way is not recommend.

**Comment by niczak** [comment]
@wenzhixin Thank you for the response.  I have instead gone with this approach: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/methods/append.html. I get the data back from the server and instead of having Twig render the HTML I wrote a JS function to do it.  I then use the append method but have seen a little oddity with styling.  I will update this thread when I have more concrete information.

**Comment by niczak** [comment]
Hey @wenzhixin -

Here is my JavaScript code, I was able to get all of the styling to work the way I needed.  One thing that I cannot figure out if it is a bug or not - after my JavaScript completes, the sorting is not functional on the table.

Is there anything I should do after the params.success() call?

```
function getReviewData(params) {
    console.log("ajax function fired");
    console.dir(params);

    $.post("/extended-review-monitor/reviews", {"test": "data", "moretest": "moredata"})
        .done(function (data) {
            console.dir(data);

            processedData = transformData(data.data);

            console.log("processed data");
            console.dir(processedData);

            $("#tblReviewDetails").data('offset', 420);

            setTimeout(function() {
                params.success({
                    total: data.data[0].total,
                    rows: processedData
                });

                // hide loading
                //params.complete();
            }, 1000);

        })
        .fail(function () {
            console.log("ajax error");
        });

    console.log("ajax complete");
}

function getQueryParams(params) {
    console.log("in getQueryParams");
    console.dir(params);

    params.offset = $("#tblReviewDetails").data('offset');

    return params;
}
```
