### ISSUE TITLE
Problems soft keyboard android filter control

### ISSUE THREAD

**Issue by davellanedam** [wenzhixin/bootstrap-table#2375]
Hello, when using mobileResponsive: true mixed with filtercontrol in android there is a problem, when I click the input filter (for each column) the soft keyboard hides again. If I set mobileResponsive: false or remove it then everything works ok. Searching the internet I´ve found this:

http://stackoverflow.com/questions/23757345/android-does-not-correctly-scroll-on-input-focus-if-not-body-element

Looks like a bug in android starting from version 4.

**Comment by Falseee** [comment]
I close this this issue, because ists almost 3 years old.
Maybe its already fixed, if not pls reopen the issue.
