### ISSUE TITLE
[Feature Request] filter-control, custom request submit action

### ISSUE THREAD

**Issue by waspinator** [wenzhixin/bootstrap-table#2376]
Add an customization option to filter-control to delay, or change the trigger for the XHR request

Currently, an XHR request is sent a few milliseconds after a character is input into a filter input. When a user is slow to type their query, multiple XHR requests are sent, which isn't great when requests take a relatively long time. 

There are also times when multiple filter fields need to be filled out before a query should be submitted. Adding an option for a custom call to the XHR request mechanism (for example a button click) can allow for a more flexible setup.

http://jsfiddle.net/waspinator/4jq06447/

**Comment by dabros** [comment]
@waspinator - @wenzhixin or @djhvscf prob know more, having dealt more with filter control (i havent at all)

But my scan of https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/filter-control/bootstrap-table-filter-control.js showed mention of `searchTimeOut` option, which could answer this for you

However, i would actually raise point that `searchOnEnterKey` (or a similar option) should be logically able to affect the filter control. Maybe filter control uses it like it does `searchTimeOut`, or provides similar option of its own (`filterOnEnterKey` or similar)

Look at doco for referance to these and other options, and checkout code as well
```javascript
            searchTimeOut:6000,
            search:true,
            searchOnEnterKey:true,
```

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
http://bootstrap-table.wenzhixin.net.cn/extensions/
https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/filter-control
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/filter-control/bootstrap-table-filter-control.js

**Comment by wenzhixin** [comment]
Have you tried what @dabros said?

**Comment by waspinator** [comment]
@wenzhixin @dabros searchTimeOut works to slow down the rate of XHR requests, but I haven't been able to find/understand how to disable a timeout and have another event (button press) trigger a search.

**Comment by UtechtDustin** [comment]
I close the issue because its older than 2 years, if you still need help pls reopen the issue.
