### ISSUE TITLE
Updating / Hiding rows

### ISSUE THREAD

**Issue by jjboy91** [wenzhixin/bootstrap-table#2377]
Hi,

In a bootstrapTable I have a column with some actions.
For the delete action I need to flag the rows that were deleted by the user in order to update a database later.
To do that I added a colum 'deleted' then when the 'deleteRow' function is called I update the row then hide it.

For one row it works great but if the user delete more than one row, the first one become visible again.

What is expected when two rows are hidden :
`<tr style="display: none;" data-index="0">`
`<tr style="display: none;" data-index="1">`
`<tr data-index="2">`

What happened :
`<tr data-index="0">`
`<tr style="display: none;" data-index="1">`
`<tr data-index="2">`

I remarked that If I remove the UpdateRow line it works as it should be.

Some problem occurs with updateCell.

Here is a link to test : http://jsfiddle.net/843qtwLw/2/

Hope there is a way to fix that.

Thanks for your help :)

**Comment by wenzhixin** [comment]
The same problem with #750
