### ISSUE TITLE
detailFormatter output in multiple columns

### ISSUE THREAD

**Issue by bounlu** [wenzhixin/bootstrap-table#2379]
By using the default detailFormatter function, the output html is given as many rows as the columns of the table. This may be very long for tables with many columns.

    function detailFormatter(index, row) {
        var html = [];
        $.each(row, function (key, value) {
            html.push('<p><b>' + key + ':</b> ' + value + '</p>');
        });
        return html.join('');
    }

**Default output:**
jobID: 1
jobStatus: running
userID: 1
userName: xxx
userEmail: xxx@yyy.com
userRole: admin
userGroup: xxx
projectName: xxx
projectDescription: test
submittedBy: xxx
species: Human
refGenome: hg19
dataType: RNA-Seq
inputFiles1: XXX_RNA_1.fq.gz
inputFiles2: XXX_RNA_2.fq.gz
inputDescription: no_description
submitDate: 2016-04-12 12:30:18
jobLog: bla bla

How can I change the function so that the html output is given in multiple columns (table?) so that detailed view uses all the space below the item:

**Desired output:**
jobID: 1 ................................................................................ jobLog: bla bla
jobStatus: running
userID: 1
userName: xxx
userEmail: xxx@yyy.com
userRole: admin
userGroup: xxx
projectName: xxx
projectDescription: test
submittedBy: xxx
species: Human
refGenome: hg19
dataType: RNA-Seq
inputFiles1: XXX_RNA_1.fq.gz
inputFiles2: XXX_RNA_2.fq.gz
inputDescription: no_description
submitDate: 2016-04-12 12:30:18

Notice that the "jobLog" is in the second column so that a long jobLog can occupy the space on the right handside.

**Comment by dabros** [comment]
@bounlu - that detailFormatter is just a Very simple example printing all rows wrapped in some extra html

If you want data in 2 columns, make 2 columns

If you want your detail view to have columns, put columns into your detail view (via `<div>` or `<table>` or whatever you want, literally no limit, you can even check each `key` to skip certain indexes

There are many examples that show different options, check them out and look elsewhere for basic jquery tutorials or SO posts to achieve a desired look for detailView, that literally has nothing to do with bootstrap-table itself, its just a function returning html

http://bootstrap-table.wenzhixin.net.cn/documentation/
http://issues.wenzhixin.net.cn/bootstrap-table/index.html

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by bounlu** [comment]
No I could not

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
