### ISSUE TITLE
Update main and examples .Readme to help direct issue requests

### ISSUE THREAD

**Issue by dabros** [wenzhixin/bootstrap-table#2380]
https://github.com/wenzhixin/bootstrap-table-examples
https://github.com/wenzhixin/bootstrap-table-examples/issues/

@wenzhixin @djhvscf - can we please update the readme for examples repo to be:

1. more consistent with main repo readme, and
2. be very clear on where to post issues, linking to contributing.md but also summarizing inline so cannot be missed

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker

This would help direct users to proper location, stop having 2 issue trackers where one is often black hole, ect

We already have this as policy, just not clear from both readme.md, especially if they go straight to examples repo, as users still often do

**Comment by wenzhixin** [comment]
Do you mean update: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/README.md?

**Comment by dabros** [comment]
@wenzhixin - yes please, so they both match basic approach and cover important points up front about WHERE to post issue requests, ect.

Lots of great simple rules layed out in contributing.md that I seem to be constantly reposting or linking to, and i can definetly see that we can improve that particular README.md (possibly also the main repo README.md) to make this clearer

**Comment by wenzhixin** [comment]
Added ISSUE_TEMPLATE: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by dabros** [comment]
@wenzhixin - great, wasnt ever aware you could do that. To make even easier, i also added small section to make even more obvious
