### ISSUE TITLE
关于bootstrap-table和angular一起使用，能给个演示吗，谢谢

### ISSUE THREAD

**Issue by iminfx** [wenzhixin/bootstrap-table#2381]
关于bootstrap-table和angular一起使用，能给个演示吗，谢谢

**Comment by wenzhixin** [comment]
这个有例子：http://issues.wenzhixin.net.cn/bootstrap-table/#integrate/angular

**Comment by iminfx** [comment]
非常感谢，这么快回复，但是为什么我打开的页面只显示“{{wk.name}}”

**Comment by iminfx** [comment]
非常感谢，我弄好了

**Comment by 7Light** [comment]
唉，用angular一堆BUG啊，算了
