### ISSUE TITLE
总页数

### ISSUE THREAD

**Issue by sharmun** [wenzhixin/bootstrap-table#2382]
用了load方法后，总页数显示undefined

**Comment by wenzhixin** [comment]
请提供 jsfiddle
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
