### ISSUE TITLE
Reorder columns - fix some column

### ISSUE THREAD

**Issue by javieerrubio11** [wenzhixin/bootstrap-table#2383]
Hi,

I'm using this plugin, however I don't find how I can fix a particular column.

Plugin [draggable ](https://akottr.github.io/dragtable/)has a solution but I can't use this solution.

Thanks for your help :)

**Comment by wenzhixin** [comment]
Which solution do you mean?

**Comment by javieerrubio11** [comment]
For example,

I want that when you define the columns options you can mark some column as don't draggable. As you can see in the previus page, that they mark the columns that are able draggable with a class.

Thanks.

**Comment by javieerrubio11** [comment]
Hi,

I reproduce one example with this plugin. [Example jsfiddle](https://jsfiddle.net/javierIntegra/gn78ozxh/11/) 
I want that you can't reorder the first column for example, I don't know if it's is possible.

Thanks for all.

**Comment by djhvscf** [comment]
You can use the dragaccept option in the available in our extension

**Comment by djhvscf** [comment]
See this example with the solution: https://jsfiddle.net/djhvscf/gn78ozxh/17/ 

@javieerrubio11 if the example does not solve your issue, please reopen it!
