### ISSUE TITLE
Add text in the td tag

### ISSUE THREAD

**Issue by mctdi** [wenzhixin/bootstrap-table#2384]
When the table is generated, in the td one column, i would like to add

`data-localize={{status}}`

tried without success

```
<table id="operationTable" 
   style="min-height:100" 
   data-search="true"
   data-show-header="true" 
   data-classes="table table-no-bordered" 
   data-height="600"
   data-pagination="true"
   data-side-pagination="server"
   data-sort-name="operationId">
   <thead>
      <tr>
         <th data-field="operationId"># Operation</th>
         <th data-field="status"  data-localize={{status}}>Status</th>
      </tr>
   </thead>
</table>
```

**Comment by wenzhixin** [comment]
Where do you want to use `data-localize`?

**Comment by mctdi** [comment]
where i display status field.

**Comment by dabros** [comment]
@mctdi - you need to explain your situation better

For example, but not limited to:

1. what is `{{status}}`, is it syntax for template engine or something? What is in this param? When is that value set? when is it read? what does it do? have you considered other approaches to pass it in (such as `detailFormatter` and local js var)?
2. how are you initializing table? there is no data toggle but you made no referance to how and when it is initialized. Share a fiddle or at least all relevant code with description on context
3. What is "without success"??? We need clear explanation of current use case vs expected use case, as well as proof this table works fine without that `data-localize={{status}}`

**Comment by mctdi** [comment]
in a html file i have

```
<table id="operationTable" 
   style="min-height:100" 
   data-search="true"
   data-show-header="true" 
   data-classes="table table-no-bordered" 
   data-height="600"
   data-pagination="true"
   data-side-pagination="server"
   data-sort-name="operationId">
   <thead>
      <tr>
         <th data-field="operationId"># Operation</th>
         <th data-field="status"  data-localize={{status}}>Status</th>
      </tr>
   </thead>
</table>
```

this table is initialized with this code

```
$("#operationTable").bootstrapTable({
                url: getHostName() + "/operations",
                queryParamsType: "",
                responseHandler: function (res) {
                    return {
                        rows: res.content,
                        total: res.totalElements,
                        pageNumber: res.number,
                        pageSize: res.size
                    };
                },
                queryParams: function (params) {
                    debugger;
                    return {
                        search: params.searchText,
                        page: params.pageNumber - 1,
                        size: params.pageSize,
                        sort: params.sortName + "," + params.sortOrder
                    };
                }
            });
```

when bootstrap-table generate the row for theses fields, i would like to add data-localize={{status}} for the column related to status.

i expect to get this for the status column

<td data-localize=ACTIVE>ACTIVE</td>

if status value is ACTIVE

**Comment by dabros** [comment]
@mctdi - thank you for that info, but didnt answer the `{{status}}` part enough

`data-localize={{status}}` is not pure html, so 

1. what is it?
2. where is this value being set from and when?
3. where is this value being used?

**Comment by mctdi** [comment]
remove {{}}... just want to have the value of status there....


is it possible to put 
data-localize=STATUS_VALUE_OF THE_FIELD 
in the td generated?

**Comment by dabros** [comment]
@mctdi 

1. Yes, `data-localise="status_value_of_the_field"`

2. WHY??

3. WHEN IS THIS UPDATED??

**Comment by mctdi** [comment]
hum no
if i put data-localise="STATUS" in the th, it's not added in the td
why because i want to translate the value

when after the table is displayed

**Comment by dabros** [comment]
Your still not explaining how and when translation needed, by what means, whether that data-localize will every change, ect.

But if you need to affect the TD or any other body content, run your code in `onPostBody`, simple jquery can determine the column and/or data-localize value

Until you explain better though, i cant provide a code sample and definetly cant say a better approach, as there absolutely is a better approach than using `onPostBody` and html data attributes. 

If i assume you just need to translate content based on the field/column, then use `detailsFormatter`, that gives you the field name and allows you to affect the content each time its rendered. If that status value changes, id actually say ignore data-attributes entirely, just make a local js array matching fields to status values (something like `{ 'col1':'status1A','col2':'status2C','col3':'status3A'}`) then use that to translate inside `detailsFormatter`

And please actually explain issues better, there are so many resources explaining how to ask a good question, and if you provide that info up front there is no back and forth and wasted time for both of us

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
