### ISSUE TITLE
CheckAll and data-formatter

### ISSUE THREAD

**Issue by torisoft** [wenzhixin/bootstrap-table#2385]
Hi
When use stateformatter for checkbox, checkall button it doesn't work.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by torisoft** [comment]
http://jsfiddle.net/e3nk137y/7129/

**Comment by wenzhixin** [comment]
Fixed in the develop branch.

**Comment by marceloavan** [comment]
I have tested locally and works fine for me, thanks for that. But it would good have an official release with this bug fix. Do you have any prediction to next official release?

Thank you.
