### ISSUE TITLE
Save Preferences between sessions.

### ISSUE THREAD

**Issue by network211** [wenzhixin/bootstrap-table#2386]
Is there anyway to save preferences / settings between sessions / refresh.

E.g., I give the user the option to select columns to view or which columns to sort on. The user makes changes to the default settings.

Is there a way to save these preferences and reload them when the user comes back to this page?

**Comment by wenzhixin** [comment]
You can use cookie extension: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html

**Comment by network211** [comment]
OK.
How do I access the settings like which columns are showing? E.g., User deselects 3 of 6 columns. How can I know which of these columns are now showing so I can save to the cookie?

**Comment by wenzhixin** [comment]
Added `getCookies` method in the develop branch.
