### ISSUE TITLE
Change total parameter. 

### ISSUE THREAD

**Issue by rhyre** [wenzhixin/bootstrap-table#2388]
Hi, my issue is that I can't change "total" parameter when using server side pagination. DjangoREST uses "count" parameter and you have hardcoded .total in line 2188. Maybe add it to defaults like 'dataField'. 
Thanks.

**Comment by wenzhixin** [comment]
You can use responseHandler:
```
responseHandler: function (res) {
    return {
        total: res.count,
        rows: res.rows
    };
}
```

**Comment by rhyre** [comment]
Thanks, that's some dark magic :), maybe add it to examples?

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/353.html
ref #353
