### ISSUE TITLE
Multi Sort & Server Side Sorting

### ISSUE THREAD

**Issue by dfmaxwell** [wenzhixin/bootstrap-table#2389]
I've implemented the Multi Sort Extension, and I get the toolbar icon, I can set the sorting, but I need it to send a request to the server to sort the data and return it.  I've watched the console and I don't see that happening.  I'm using the latest version of bootstrap-table and the multisort extension.  I've implemented the onMultipleSort and have it writing to the console console.log( this.sortPriority ); and I see the output so I know that it is being triggered.  What steps do I need to take to send the sorting to the server?

Thanks!

**Comment by wenzhixin** [comment]
I think it does not support this feature now.

**Comment by wenzhixin** [comment]
ref #2078

**Comment by dfmaxwell** [comment]
I looked over that and it seemed like it indicated that it supports server
side pagination, but it doesn't seem to work.

**Comment by wenzhixin** [comment]
Merged the pull request in v1.11.0, you can help to test that.

**Comment by Falseee** [comment]
I close this issue because its older than 2 years, if this issue is not fixed pls reopen the issue.

**Comment by MKKari** [comment]
Hi, I am trying to implement server side multi sort, but i can not make it work. This is console output, when I click on "Sort" in multi sort modal.

`bootstrap-table-multiple-sort.js:1758 Uncaught RangeError: Maximum call stack size exceeded
    at Object.options.queryParams (bootstrap-table-multiple-sort.js:1758)
    at Object.calculateObjectValue (bootstrap-table.min.js:10)
    at Object.options.queryParams (bootstrap-table-multiple-sort.js:1758)
    at Object.calculateObjectValue (bootstrap-table.min.js:10).......`

Is it even possible atm with this extension or I have to create my own solution and somehow extend "queryParams" to achieve this goal.
