### ISSUE TITLE
[Proposal] Sass format (scss) to preserve stylesheets

### ISSUE THREAD

**Issue by smgladkovskiy** [wenzhixin/bootstrap-table#239]
It would be good for contributing (and for saving your time) to keep styles and work with them using Sass CSS preprocessor (scss format). You are using gulp in you develop work, so it would be not so hard to add to gulp [cssmin work](https://github.com/wenzhixin/bootstrap-table/blob/master/Gruntfile.js#L36) also and sass converting.

I can help you to make initial converting if you wish.

Sass will help developers to easy extend or/and integrate styles of your product in their applications. Manage change and theming will be easier.

**Comment by wenzhixin** [comment]
Thank you for your suggestions, but I am not familiar with Sass, so do not do any modify now. I will study more knowledge about Sass in the future:) close this issue.
