### ISSUE TITLE
How can i hide pagination detail info?

### ISSUE THREAD

**Issue by thswldus94** [wenzhixin/bootstrap-table#2391]
Hi, I'm using bootstrap table in my project.(it is awesome)

How can i hide pagination detail info under table left side? 
(for example "Showing 1 to 15 of 350 rows 15 records per page")
is there any option that can hide?

Please answer to my question.
Thanks!

**Comment by dabros** [comment]
@thswldus94 - so you want pagination, but not that specific text info saying X to Y of M?

Go to http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options and ctrl+f "pag"

A number of pagination options, I cant say for sure if any disable that info (as you didnt provide [fiddle](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports)) but test each

You should also always get in habit of F12 (devtools) and inspect, that text is in div `.pagination-info`, so css could easily hide that and leave the pagesize dropdown be, but do checkout pagination options first.

https://developers.google.com/web/tools/chrome-devtools/

**Comment by thswldus94** [comment]
Thanks a lot!
it was helpful for me.
i solved this problem  by doing hide `.pagination-info`(css `display:none`)

**Comment by codingPao** [comment]
thank you very much！

**Comment by VRRmax** [comment]
When modifying css property is not suitable to your need, you should be able to use https://examples.bootstrap-table.com/#methods/toggle-pagination.html.
