### ISSUE TITLE
updateCellByUniqueId

### ISSUE THREAD

**Issue by Dimigergo** [wenzhixin/bootstrap-table#2392]
Hello!

I use the x-editable plugin to make changes in a table. When editable-save.bs.table event is raised, there is no row index, but I have the newValue.UId. When the user change a field I would like to update only one cell in this row. 
If I call updateByUniqueId the whole row will be updated, and the modification highlight (bold text) remove from the editable cell.

Is it possibly to add a method updateCellByUniqueId like updateByUniqueId (row)?

Or it is possible to get the row index from row UniqueId?

Thanks.

**Comment by wenzhixin** [comment]
After the user change a field, the row will be updated automatically, you do not have to manually update it.

**Comment by christlee1989** [comment]
@wenzhixin  I have the same issue , i have one custom hidden cell(visible:false) ,  when editable-save.bs.table triggered,i want to change this cell's value. I need row index too.. or 'updateByUniqueId'

**Comment by wenzhixin** [comment]
Merged.
