### ISSUE TITLE
editable + refreshOptions

### ISSUE THREAD

**Issue by AlunoTADS** [wenzhixin/bootstrap-table#2393]
I changed "bootstrap-table-editable.js" because when I used the method "refreshOptions" the editable fields became weird.

Bug example:
https://jsfiddle.net/go8uh0vq/

Solution:
`

            var _formatter =  column.formatter;
			
			if(!column.editableFormatter){
				column.formatter = function (value, row, index) {
					var result = column.preFormatter ? column.preFormatter(value, row, index) : value;

					$.each(column, processDataOptions);

					$.each(editableOptions, function (key, value) {
						editableDataMarkup.push(' ' + key + '="' + value + '"');
					});

					return ['<a href="javascript:void(0)"',
						' data-name="' + column.field + '"',
						' data-pk="' + row[that.options.idField] + '"',
						' data-value="' + result + '"',
						editableDataMarkup.join(''),
						'>' + '</a>'
					].join('');
				};
			}			
			column.editableFormatter = true;
`

**Comment by safiboss** [comment]
I can confirm this bug.

**Comment by wenzhixin** [comment]
Fixed: http://jsfiddle.net/e3nk137y/7505/
Same issue #2120
