### ISSUE TITLE
Chnage PDF library

### ISSUE THREAD

**Issue by ilicmarko** [wenzhixin/bootstrap-table#2395]
I think you need the change  the PDF library because jsPDF does not support UTF-8 nor planing too.. This is a big factor personally. I think using something as [PDF Make](http://pdfmake.org) would be great.

Thank you in advance hope you take my suggestion in consideration.

**Comment by wenzhixin** [comment]
Please submit to https://github.com/hhurz/tableExport.jquery.plugin/issues, thanks! @ilicmarko
