### ISSUE TITLE
[bug] editable + mobile together in android

### ISSUE THREAD

**Issue by Taewa** [wenzhixin/bootstrap-table#2396]
Test device : 
- Galaxy4s(4.4.2)
- iPhone5c(9.3.2)

JsFiddle : [Link](https://jsfiddle.net/ys4vt8ho/1/)

Hello.
I'd like to use editable and mobile together.

You can check the problem through jsFiddle above with android phone. (Must be real android phone. No such google chrome inspector emulator)
You aren't able to modify 'ala' on android (iOS works).

I assume that android native keyboard changes browser size and then `bootstrap-table-mobile.js` detect `resize` event, and reset the view. ( `$(window).on('resize orientationchange'` <- this part )

However, I can't find how to resolve the problem. 
Am I missing something?

Any idea will be very useful.

Thank you guys.

**Comment by UtechtDustin** [comment]
Fixed in #4669.
