### ISSUE TITLE
Angular wrapper for this js

### ISSUE THREAD

**Issue by amanagrawal9** [wenzhixin/bootstrap-table#2397]
I am using this tech stack in my application. Can i convert my app to angular using all following js.
Is there any angular wrapper created for this?

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

```
<script src="js/bootstrap.min.js"></script>
<script src="js/bootstrap-table.min.js"></script>
<script src="js/bootstrap-table-editable.js"></script>
<script src="http://rawgit.com/vitalets/x-editable/master/dist/bootstrap3-editable/js/bootstrap-editable.js"></script>
<script src="js/bootstrap-table-export.min.js"></script>
<script src="http://rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js"></script>
<script src="js/bootstrap-table-resizable.js"></script>
<script src="https://rawgit.com/wenzhixin/colResizable/master/source/colResizable-1.5.source.js"></script>
```

**Comment by dabros** [comment]
@amanagrawal9 

https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue%20angular

Never used it myself, but asked and answered many times before, also has official example

http://issues.wenzhixin.net.cn/bootstrap-table/index.html#integrate/angular

Always look and search first

**Comment by amanagrawal9** [comment]
I search this already. but this angular does not have the same UI as the original UI has.

**Comment by dabros** [comment]
@wenzhixin @djhvscf - any thoughts?

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
@amanagrawal9

**Comment by wenzhixin** [comment]
No longer support angular in the latest release version.

**Comment by pipiscrew** [comment]
Angular2+ alternative

https://www.pipiscrew.com/2019/06/from-wenzhixin-bootstrap-table-to-angular-akveo-ng2-smart-table/
