### ISSUE TITLE
bootstrap table inside modal does not fire x-editable

### ISSUE THREAD

**Issue by safiboss** [wenzhixin/bootstrap-table#2398]
Hello everyone, I tried everything but nothing seems to work. If I put the bootstrap table inside a modal and the table contains the editable option the plugin does not call or fire the select edit. All data is there but the edit option will not fire. 

If I put it outside the modal, for example in the landing page, the x-editable option is called.

Can someone confirm if this is an issue?

**Comment by dabros** [comment]
@safiboss 

Please see https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Fiddles (examples given) and similar steps are needed for us to better help everyone, and for you to help yourself :+1: )

Doesnt matter if it actually saves, dummy data from js array is fine, but we need to see editable call being triggered in one table and not the other

**Comment by safiboss** [comment]
Sorry, I never used jsfiddle. It took me sometime to prepare it. I was not able to pass a proper data-url but In my working page data is shown and url works fine.

The problem basically is that  the editable option is never called inside the modal but data is there. If it is not inside the modal the select editable option works fine.

AS I said the jsfiddle to recreate my problem:

https://jsfiddle.net/probando2/wkwoujpj/8/

**Comment by dabros** [comment]
@safiboss - dont use `data-toggle`, instead use what onShow type event (or whatever that dialog gives you) and initialize using js

`data-toggle` (as mentioned in many many other issues) removes your control of timing, and likely is the cause of this.

If that doesnt solve it in your real use case, then please provide what I asked for above and have a working editable outside a modal AND a editable attempt inside, dummy data from a js array is fine, the displayed values should still change if editable works (just obviously not save to db or whatever)

**Comment by wenzhixin** [comment]
Have you solved your problem? @safiboss

**Comment by safiboss** [comment]
Yes, I did thank you
