### ISSUE TITLE
Is there any onRefresh method?

### ISSUE THREAD

**Issue by jackie88558** [wenzhixin/bootstrap-table#2399]
I want to call js method by myself when I press the refresh button. But I didn't find 'onRefresh' method or something like that in document.

**Comment by dabros** [comment]
http://bootstrap-table.wenzhixin.net.cn/documentation/#events

You can see list of events there, i would look towards `onPostBody` if needing to affect html content, `onLoadSuccess` if just some extra data step when data refreshed, ect


See this example and watch console (F12) to see what events are triggered: http://issues.wenzhixin.net.cn/bootstrap-table/index.html

Pagination and other actions may sometimes trigger `onLoadSuccess` (though id imagine only if `side-pagination="server"`) and any view changing action will trigger `onPostBody`, but remember you can use simple js var (bool or whatever) as flags to trigger when certain conditions are met, such as for all refresh calls after table first created. There is also the custom toolbar option, just add your own refresh button with your own handler that calls whatever else Then calls the table refresh method.

**Comment by jackie88558** [comment]
Thank you for your help. Actually, I just need to refresh my table data by refresh button. But I don't use data-url to refresh it (the response from backend doesn't include just table data). So I'm going to call a js method which includes ajax request.
