### ISSUE TITLE
Range date filter in the table

### ISSUE THREAD

**Issue by Alex85651** [wenzhixin/bootstrap-table#2401]
Hi guys,
I'm looking for a way to filter the rows in my table by passing a date range.
Here is a jsFiddle of what I am trying to do : https://jsfiddle.net/54ay3pdv/9/

I tried different ways before coming here:
 - Custom toolbar by following #1897 and the provided example. The methods shown in it does not seem to work for me
 - `table.bootstrapTable('filterBy')` does not work too
 -  Also tried a custom solution made by myself. I compare every date in each row and then hide the rows which are not in the range given. It actually works only on one page so it's not a good solution until I found out another way

What do you guys think about that ?

**Comment by Alex85651** [comment]
After a lot of researches, I found something which fits perfectly 
`$table.bootstrapTable('load', $.grep(data, function (row) { return Date.parse(row.date).between(from, to);
 }));`

This returns only the rows which are between the two dates objects.

We could easily change the return instruction to make it work for any filter we want.
I hope this will help :)

**Comment by wenzhixin** [comment]
#2404
