### ISSUE TITLE
Filtering by string partials

### ISSUE THREAD

**Issue by kevin-quach** [wenzhixin/bootstrap-table#2404]
What I'm trying to achieve is being able to toggle selected tags for a "comments" table and searches through the rows that has the tags toggled. The challenge is that I've attempted it by trying to use the `filterby` method, however, it can only look for the exact string and cannot filter by partial string values.

Is such a feature even feasible? I'd like some insights around this, thanks!

I created an example to illustrate what I'm attempting to achieve. For simplicity, 

Here's the html:

    <table id="table">
        <thead>
        <tr>
            <th data-field="date">Date</th>
            <th data-field="desc">Description</th>
            <th data-field="tags">Tags</th>
        </tr>
        </thead>
    </table>
    <br>
    <button id="filter-general">General</button>
    <button id="filter-rotation">Rotation</button>
    <button id="clear">clear</button>

Javascript:

    var data = [{
      "date": "2016-05-10",
      "tags": "General, Research, Rotation",
      "desc": "Nunc velit lectus, ornare vitae fringilla eget, vestibulum quis tortor."
    },{
      "date": "2016-04-22",
      "tags": "General",
      "desc": "Nunc velit lectus, ornare vitae fringilla eget, vestibulum quis tortor."
    },{
      "date": "2016-03-23",
      "tags": "Research, Rotation",
      "desc": "Nunc velit lectus, ornare vitae fringilla eget, vestibulum quis tortor."
    },{
      "date": "2015-11-01",
      "tags": "Rotation",
      "desc": "Nunc velit lectus, ornare vitae fringilla eget, vestibulum quis tortor."
    },{
      "date": "2016-08-15",
      "tags": "General, Rotation",
      "desc": "Nunc velit lectus, ornare vitae fringilla eget, vestibulum quis tortor."
    }];
    
    $(function() {
      $table = $('#table');
      $table.bootstrapTable({
        data: data
      });
    
      $('#clear').click(function() {
        $table.bootstrapTable('filterBy', {});
      });
    
      $('#filter-general').click(function() {
        $table.bootstrapTable('filterBy', {
          tags: "General"
        });
      });
    
      $('#filter-rotation').click(function() {
        $table.bootstrapTable('filterBy', {
          tags: "Rotation"
        });
      });
    });

http://jsfiddle.net/zqxwr3uL/6/

**Comment by wenzhixin** [comment]
You can use `load` method instead: http://jsfiddle.net/zqxwr3uL/47/

**Comment by wenzhixin** [comment]
ref #2401
