### ISSUE TITLE
Table not working in Chrome

### ISSUE THREAD

**Issue by gcelano** [wenzhixin/bootstrap-table#2410]
My bootstrap-table works in Safari but not in Chrome. Is there a way to overcome the issue?

This is the format of my table data:

https://raw.githubusercontent.com/gcelano/OrderAdjectiveNoun/master/UD_Swedish-LinES.json

and this the opening tag of my table in the html:

<table data-toggle="table"
       data-url="https://raw.githubusercontent.com/gcelano/OrderAdjectiveNoun/master/UD_Swedish-LinES.json"
       data-query-params="queryParams"
       data-page-list="[5, 10, 20, 50, 100, 200]"
       data-pagination="true"
       data-search="true"
       data-height="400">

**Comment by dabros** [comment]
@gcelano 

What is "does not work"?

No one ever reported anything like this, so what you need to do is debug first.

Use devtools (F12, https://developers.google.com/web/tools/chrome-devtools/?hl=en) to look at console for any errors, as well as your data request (network panel) itself.

If you see nothing wrong, then you need to be very explicit about "expected output" vs "current output", be very clear on exactly what situation is and what is or isnt happening that expected to. Then along with that you need to replicate your issue with a [Fiddle ](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports)(examples provided). 

If you cant replicate, and you not getting any console or network errors, then we cant help. But absolutely every use case when someone has, they usually solved it themself by attempting to recreate it.

**Comment by wenzhixin** [comment]
[Cross domain](https://github.com/wenzhixin/bootstrap-table/search?q=Cross+domain&type=Issues&utf8=%E2%9C%93) problem.
