### ISSUE TITLE
How Do I Display Errors with Editable on Load

### ISSUE THREAD

**Issue by ebellefontaine** [wenzhixin/bootstrap-table#2411]
I am trying to populate a table with several editable fields using the editable extension. The fields are pulled in from a url. On the server side we run some validation checks and pass back an array of which fields contained errors. 

How can I display those errors on page load with the editable plug in? 

See example: [JSFiddle](http://jsfiddle.net/ebellefontaine/9p62op19/)

To give you another example of what I am trying to do. Lets say that the value 'newName' got saved to the 'name' field in our database. When we go to our page with the bootstrap table displaying all the names of users, the one with the value 'newName' would be highlighted red, and an error message would say something like "Error: newName is not valid".

**Comment by dabros** [comment]
@ebellefontaine 

Some thoughts:

1. Why not validate when saving?

Editable is just interface to x-editable plugin, as explained both in official doco and in detail in several other issues, #2222 https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue%20x-editable%20

Look at x-editable and see if maybe better to stop or immeditately flag/color incorrect values using proper x-editable function and/or callback. There is also the fact you would need to manually keep that `errors` index updated each time, or call a refresh on that row after every save request. 


2. Formatter

Look at previous point first, but even if you stop or flag errors immediately after save request, you might still need to account for previous errors passed from server.

My quick test showed that column `formatter` is NOT called after save request, but could be called inside `onSaveComplete` (or similar function) for consistent application of styling and detection logic, just mimicing the entire rows data or just `errors` index.


3. Why even perform validation server-side?

As raised above, seems odd you wouldnt just validate when saving, and if doing so why not just mimic that basic functionality in `formatter`. Not saying this is best approach, depends on code complexity, but it might be useful for you to greatly cut down on complexity.

**Comment by ebellefontaine** [comment]
@dabros 

Thanks for the suggestions, 

This web application I am building is tricky. Basically a user can save draft data, where we can run some validation checks against the dataon save, BUT not all validation checks can be run on save because a secondary system we validate against may not have been updated yet. 

So we allow users to enter potentially bad data. When the secondary system is updated we have users go back and "Finalize" their draft data, by running through some final validation checks. Which is where the above issue I am having is. The data itself can range from 1 row to 1000's of rows of data, and I need some way to display the original data the user uploaded, the errors (if there were any), and a way for the user to change that data in the same view, in a table form that's easy for the users to recognize and scroll through and edit.

It's ugly, I know. but this kind of data has been extremely difficult to work around.

**Comment by dabros** [comment]
@ebellefontaine - that answers point 3, but my other 2 points and the solution/s they describe still fully apply, so look again and try that

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by ebellefontaine** [comment]
Yes, see: http://stackoverflow.com/questions/38108304/how-to-display-data-errors-on-load-with-bootstrap-table-and-x-editable

I did a modified version of the listed solution to get the outcome I was looking for.

**Comment by ebellefontaine** [comment]
See: http://stackoverflow.com/questions/38108304/how-to-display-data-errors-on-load-with-bootstrap-table-and-x-editable
