### ISSUE TITLE
bootstrap table refresh throws "Uncaught TypeError: Cannot read property 'apply' of undefined"

### ISSUE THREAD

**Issue by abhsk1** [wenzhixin/bootstrap-table#2412]
Short and descriptive example bug report title
Getting error as "Uncaught TypeError: Cannot read property 'apply' of undefined" for every time refresh is happening on bootstrap table.

`
 function autoRefreshInstanceTabLoading(){
	    				sessionStorage.loadingInstTab = setInterval(function() {
 						//refresh the workflow table
							  $('#tableInstance').bootstrapTable('refresh', {
							  silent : 'true',
							  url: 'wf/Admin/simplifiedInstances'
							});	
				}, 30000);
	    }
`

In above code, I am getting error at "**$('#tableInstance').bootstrapTable('refresh', {"** 
Bootstrap table is defined as below :

`
<table id="**tableInstance**" data-toggle="table"
                       data-url="wf/Admin/simplifiedInstances" data-cache="false"
                       data-height="600" data-striped="true" data-pagination="true"
                       data-sort-order="desc" data-sort-name="createTime"
                       data-show-columns="true" data-page-size="50"
                       data-show-multi-sort="true" data-show-refresh="true"
                       data-sort-priority='[{"sortName":"createTime","sortOrder":"desc"},{"sortName":"createdBy","sortOrder":"asc"}]'
                       data-reorderable-columns="true" data-page-list='[50, 75, 100, 200, 300, 500]'>
                    <thead>
                        <tr>                            
                            <th data-field="check" data-checkbox="true"></th>
                             <th data-field="id" data-sortable="true"
                                data-formatter="tableFormatter">Id</th>
							<th data-field="callingParty" data-sortable="true"
                                data-formatter="tableFormatter">Calling Party</th>
                            <th data-field="calledParty" data-sortable="true"
                                data-formatter="tableFormatter">Called Party</th>
                            <th data-field="process" data-sortable="true"
                                data-formatter="tableFormatter">Workflow Name</th>
                            <th data-field="version" data-sortable="true"
                                data-searchable="false" data-formatter="tableFormatter">Version</th>
                            <th data-field="state" data-sortable="true"
                                data-formatter="tableFormatter">State</th>
                            <th data-field="createdBy" data-sortable="true"
                                data-formatter="tableFormatter">Created By</th>
                            <th data-field="createTime" data-sortable="true"
                                data-searchable="false" data-formatter="tableFormatter">
                                Created
                                At
                            </th>

                            <th data-field="endTime" data-sortable="true"
                                data-searchable="false" data-formatter="tableFormatter">
                                Completed
                                At
                            </th>
                        </tr>
                    </thead>
                </table>
`
A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

Below code is causing this issue :

`
$('#tableInstance').bootstrapTable('refresh', {
							  silent : 'true',
							  url: 'wf/Admin/simplifiedInstances'
							});
`

Stack of error trace in chrome :
bootstrap-table.js:1907 Uncaught TypeError: Cannot read property 'apply' of undefinedBootstrapTable.trigger @ bootstrap-table.js:1907BootstrapTable.refresh @ bootstrap-table.js:2550(anonymous function) @ bootstrap-table.js:2775each @ jquery-2.2.3.min.js:2each @ jquery-2.2.3.min.js:2$.fn.bootstrapTable @ bootstrap-table.js:2760(anonymous function) @ admin.html:3001

**I am seeking assistance and guidance on this issue as above errors is getting piled up for every refresh.**

**Comment by abhsk1** [comment]
Can somebody please guide me where I am doing wrong while refreshing the bootstrap table ?

**Comment by dabros** [comment]
@abhsk1 - please fix your links and fix your formatting, click the "Styling with Markdown is supported" button on bottom of issue text editor to find how to properly share large blocks of code

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by abhsk1** [comment]
I have added in jsfiddle -  https://jsfiddle.net/abhsk1/apffzLLv/4/

**Comment by wenzhixin** [comment]
Your fiddle does not work. ref #1765

**Comment by abhsk1** [comment]
Issue fixed after bootstrap update.
