### ISSUE TITLE
Column unFormatter when using filter control

### ISSUE THREAD

**Issue by davellanedam** [wenzhixin/bootstrap-table#2413]
I formatted a column with numbers as currency (with commas and symbols), then I want to search for a value, ex: 50000 but it can´t be found as column value is formatted, it finds up to "50", but not "50000" as the column is formatted like "$ 50,000.00"

Is there a way to unFormat a column when filtering with filter control?

**Comment by dabros** [comment]
@davellanedam - look at the `strictSearch` feature, as far as im aware it helps handle exactly that

Plenty of examples of it in issues: https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue%20strictSearch

**Comment by davellanedam** [comment]
I´m sorry, haven´t seen the "searchFormatter" column option, this solves my issue. Thanks a lot!. Very nice idea to update documentation.

**Comment by dabros** [comment]
@davellanedam - if that works, great, but do test the `strictSearch` as my understanding is that it allows searching against raw data, ignoring and `formatter` applied via column options

**Comment by davellanedam** [comment]
Oh, indeed it works, but needs exact value, and for me works for partial. Again, thank you!
