### ISSUE TITLE
what should I do to prevent the pagination's loop?

### ISSUE THREAD

**Issue by dzlishen** [wenzhixin/bootstrap-table#2414]

**Comment by dabros** [comment]
Buy a puppy

Say 5 holy Mary's in the mirror

Join an all male icelandic needlepoint group

</br>

</br>

</br>

Or...

Actually explain the problem

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

There are guidelines before we can help you, and they arnt much, so just read those links and update then

**Comment by wenzhixin** [comment]
Added `paginationLoop` option in develop branch.
