### ISSUE TITLE
Update `strictSearch` doco description

### ISSUE THREAD

**Issue by dabros** [wenzhixin/bootstrap-table#2416]
@wenzhixin @djhvscf 

Is there a reason `strictSearch` has such vague description? 

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options 

I would update it, but im not 100% clear on its scope, but it definetly does need more clarification in doco as has come up a few times now and entirely unclear from doco what it is
#2413

https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue%20strictSearch

**Comment by wenzhixin** [comment]
The scope of `strictSearch` option is the `search` input, but many times they want to use in the filter-control extension, the extension does not support this option.

**Comment by wenzhixin** [comment]
ref #2428

**Comment by djhvscf** [comment]
@dabros @wenzhixin you can use filterStrictSearch in the filter-control extension

**Comment by dabros** [comment]
@djhvscf - does that, or can that, inherit from the base `strictSearch` by default?

This would still allow it to be overwritten if desired, but if `strictSearch` is true (unless they specify otherwise) seems simpler if that carried across to `filterStrictSearch`

**Comment by djhvscf** [comment]
Good idea @dabros, lets create a **PR** @dabros  :)

**Comment by dabros** [comment]
@djhvscf 

I see https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/filter-control/bootstrap-table-filter-control.js#L429, but unsure how to make that inherit
