### ISSUE TITLE
Adding data-height makes filter control datepicker not display the selected date

### ISSUE THREAD

**Issue by ysiuu** [wenzhixin/bootstrap-table#2418]
Hi,

I'm trying to use the filter control with datepicker, but it turns out that for a non-trivial table the date does not appear inside the input after picking it even though it is passed to the backend on initial and subsequent filtering requests (when editing filters for other columns).

JSFiddle http://jsfiddle.net/ysiu/jdjn8d1z/2/

Click on input under 'Forks' - datepicker appears. Select a date. Refresh fires. After that - **no date in the input**

Remove the data-height="400". Run. Works now - after selecting date with datepicker it is displayed in the input.

I got similar issues with table without data-height specified - fails if data-url is specified, so the problem may be bigger, but for now I was able to fiddle-reproduce only this one.

Tested in Chrome, FF, IE under Windows

**Comment by djhvscf** [comment]
Example  http://jsfiddle.net/djhvscf/jdjn8d1z/3/

**Comment by labyrinth23232** [comment]
Hi, this is actually not fixed I am seeing three issues:
1. when adding height, datepicker does not show selected date and wont filter
2. adding multiselect to true stays as single select
3. adding native options to datepicker does nothing

Not sure if I need to opent three seperate issues. 


Please see my code:

<html>
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.5.0/css/perfect-scrollbar.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.css">

    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.css">




    <style>
        body {
            overflow: hidden; /* Hide scrollbars */
        }


    </style>
    <title></title>

</head>
<body>
    <script src="/webresources/hub_/js/commonWebAPI.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="/webresources/hub_/calendar/js/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.5.0/perfect-scrollbar.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.js"></script>


    <table id="table"
           data-filter-control="true"
           data-show-search-clear-button="true"
           data-single-select="true"
           data-click-to-select="true">
        <thead>
            <tr>
                <th data-field="state" data-checkbox="true"></th>
//mutiselect is set to true
                <th data-field="Day" data-filter-control="select" data-filter-control-multiple-select="true"> Filter Day</th>
                <th data-field="Date" data-visible="false">Filter Date</th>
                <th data-field="FormattedDate" data-filter-control="datepicker"></th>
                <th data-field="StartTime" data-visible="false"></th>
                <th data-field="FormattedStartTime"></th>
                <th data-field="EndTime" data-visible="false"></th>
                <th data-field="FormattedEndTime"></th>
            </tr>
        </thead>

    </table>
 <script type="text/javascript">
$(function () {
                    $('#table').bootstrapTable({
                        data: AvailableSessions,
                        //height
                        height: 500,
                        //adding native datepicker options
                        ['data-filter-datepicker-options']: '{"startDate":' + new Date(AvailableSessions[0].Date) + ', "endDate":' + new Date(AvailableSessions[AvailableSessions.length - 1].Date) + '}',
  })
                })
</script>

Thank you.

**Comment by labyrinth23232** [comment]
Hi, this is actually not fixed I am seeing three issues:

1.when adding height, datepicker does not show selected date and wont filter
2.adding multiselect to true stays as single select
3.adding native options to datepicker does nothing

Not sure if I need to opent three seperate issues.

Please see my code:

<link rel="stylesheet" href="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.css">
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<link rel="stylesheet" type="text/css" href="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.css">
<style>
    body {
        overflow: hidden; /* Hide scrollbars */
    }
</style>
<title></title>
<script src="/webresources/hub_/js/commonWebAPI.js"></script> <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> <script type="text/javascript" src="/webresources/hub_/calendar/js/moment.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.5.0/perfect-scrollbar.min.js"></script> <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script> <script src="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script> <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script> <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.js"></script>
<table id="table"
       data-filter-control="true"
       data-show-search-clear-button="true"
       data-single-select="true"
       data-click-to-select="true">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
                <th data-field="Day" data-filter-control="select" data-filter-control-multiple-select="true"> Filter Day</th>
                <th data-field="Date" data-visible="false">Filter Date</th>
                <th data-field="FormattedDate" data-filter-control="datepicker"></th>
                <th data-field="StartTime" data-visible="false"></th>
                <th data-field="FormattedStartTime"></th>
                <th data-field="EndTime" data-visible="false"></th>
                <th data-field="FormattedEndTime"></th>
            </tr>
        </thead>
</table>
<script>
(function () {
                 $'#table').bootstrapTable({
                        data: AvailableSessions,
                        //height
                        height: 500,
                        //adding native datepicker options
                        ['data-filter-datepicker-options']: '{"startDate":' + new Date(AvailableSessions[0].Date) + ', "endDate":' + new Date(AvailableSessions[AvailableSessions.length - 1].Date) + '}'
                    })
                })
</script>
Thank you.

**Comment by labyrinth23232** [comment]
Hi, this is actually not fixed I am seeing three issues:

1.when adding height, datepicker does not show selected date and wont filter
2.adding multiselect to true stays as single select
3.adding native options to datepicker does nothing

Not sure if I need to opent three seperate issues.

Please see my code:

<link rel="stylesheet" href="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.css">
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<link rel="stylesheet" type="text/css" href="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.css">
<style>
    body {
        overflow: hidden; /* Hide scrollbars */
    }
</style>
<title></title>
<script src="/webresources/hub_/js/commonWebAPI.js"></script> <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> <script type="text/javascript" src="/webresources/hub_/calendar/js/moment.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.5.0/perfect-scrollbar.min.js"></script> <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script> <script src="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script> <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script> <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.js"></script>
<table id="table"
       data-filter-control="true"
       data-show-search-clear-button="true"
       data-single-select="true"
       data-click-to-select="true">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
                <th data-field="Day" data-filter-control="select" data-filter-control-multiple-select="true">Day</th>
                <th data-field="Date" data-visible="false">Date</th>
                <th data-field="FormattedDate" data-filter-control="datepicker"></th>
                <th data-field="StartTime" data-visible="false"></th>
                <th data-field="FormattedStartTime"></th>
                <th data-field="EndTime" data-visible="false"></th>
                <th data-field="FormattedEndTime"></th>
            </tr>
        </thead>
</table>
<script>
(function () {
                 $'(#table').bootstrapTable({
                        data: AvailableSessions,
                        //height
                        height: 500,
                        //adding native datepicker options
                        ['data-filter-datepicker-options']: '{"startDate":' + new Date(AvailableSessions[0].Date) + ', "endDate":' + new Date(AvailableSessions[AvailableSessions.length - 1].Date) + '}'
                    })
                })
</script>
Thank you.

**Comment by labyrinth23232** [comment]
Hi, this is actually not fixed I am seeing three issues:

1.when adding height, datepicker does not show selected date and wont filter
2.adding multiselect to true stays as single select
3.adding native options to datepicker does nothing

Not sure if I need to opent three seperate issues.

Please see my code:

<link rel="stylesheet" href="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.css">
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<link rel="stylesheet" type="text/css" href="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.css">
<style>
    body {
        overflow: hidden; /* Hide scrollbars */
    }
</style>
<title></title>
<script src="/webresources/hub_/js/commonWebAPI.js"></script> <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> <script type="text/javascript" src="/webresources/hub_/calendar/js/moment.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.5.0/perfect-scrollbar.min.js"></script> <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script> <script src="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script> <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script> <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.js"></script>
<table id="table"
       data-filter-control="true"
       data-show-search-clear-button="true"
       data-single-select="true"
       data-click-to-select="true">
    <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
                <th data-field="Day" data-filter-control="select" data-filter-control-multiple-select="true">Day</th>
                <th data-field="Date" data-visible="false">Date</th>
                <th data-field="FormattedDate" data-filter-control="datepicker"></th>
                <th data-field="StartTime" data-visible="false"></th>
                <th data-field="FormattedStartTime"></th>
                <th data-field="EndTime" data-visible="false"></th>
                <th data-field="FormattedEndTime"></th>
            </tr>
        </thead>
</table>
<script>
(function () {
                 $'(#table').bootstrapTable({
                        data: AvailableSessions,
                        //height
                        height: 500,
                        //adding native datepicker options
                        ['data-filter-datepicker-options']: '{"startDate":' + new Date(AvailableSessions[0].Date) + ', "endDate":' + new Date(AvailableSessions[AvailableSessions.length - 1].Date) + '}'
                    })
                })
</script>
Thank you.

**Comment by labyrinth23232** [comment]
Hi, this is actually not fixed I am seeing three issues:

1.when adding height, datepicker does not show selected date and wont filter
2.adding multiselect to true stays as single select
3.adding native options to datepicker does nothing

Not sure if I need to open

 three seperate issues.

Please see my code



<html>
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.5.0/css/perfect-scrollbar.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.css">

    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.css">




    <style>
        body {
            overflow: hidden; /* Hide scrollbars */
        }
    </style>
    <title></title>

</head>
<body>
    <script src="/webresources/hub_/js/commonWebAPI.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="/webresources/hub_/calendar/js/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.5.0/perfect-scrollbar.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/filter-control/bootstrap-table-filter-control.js"></script>


    <table id="table"
           data-filter-control="true"
           data-show-search-clear-button="true"
           data-single-select="true"
           data-click-to-select="true">
        <thead>
            <tr>
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="Day" data-filter-control="select" data-filter-control-multiple-select="true"> Filter Day</th>
                <th data-field="Date" data-visible="false">Filter Date</th>
                <th data-field="FormattedDate" data-filter-control="datepicker"></th>
                <th data-field="StartTime" data-visible="false"></th>
                <th data-field="FormattedStartTime"></th>
                <th data-field="EndTime" data-visible="false"></th>
                <th data-field="FormattedEndTime"></th>
            </tr>
        </thead>

    </table>
    <script>
        (function () {
            $('#table').bootstrapTable({
                data: AvailableSessions,
                //height
                height: 500,
                //adding native datepicker options
                ['data-filter-datepicker-options']: '{"startDate":' + new Date(AvailableSessions[0].Date) + ', "endDate":' + new Date(AvailableSessions[AvailableSessions.length - 1].Date) + '}'
            })
        })
    </script>
    </body>
</html>
