### ISSUE TITLE
Refresh after clearing search form

### ISSUE THREAD

**Issue by jangrewe** [wenzhixin/bootstrap-table#242]
Thanks for this great project!

I have one minor issue when refreshing the data via AJAX: If i enter something in the search field, that search term get passed to the server. If i manually clear the search field, the query gets updated correctly (the term is removed). 
I added a small button to the search field for quickly clearing it (it sets .val('') for the input) and call .refresh(), but unfortunately the search term is kept as a parameter. 
The data also doesn't refresh if i don't trigger the refresh manually...

**Comment by wenzhixin** [comment]
Because in your case cannot trigger keyup event of search input, so you need to call the `refresh` method manually.
