### ISSUE TITLE
Issue getting unique id from table

### ISSUE THREAD

**Issue by wpanderson** [wenzhixin/bootstrap-table#2423]
Hey all,

I'm having an issue updating a specific table row i've selected from a given unique id. Long story short I have a page that gets server data through json then populates a selected row with the new updated server data. I have the data and I can get it to update if I give a specific row through the 'updateRow' method but there doesn't seem to be a way to get an index of selected rows. So I have been trying to use the 'updateByUniqueId' method. 

I have a table that I build in html through:
`<table class="mycalss" id="mytable" data-unique-id="id"></table>`I added the "data-unique-id" to try and specify a specific table column i have but it does not work.

I then build the table in javascript with all the values. In the javascript I have a value lets call "id" that I have created and would like to make the uniqueId. so i can use the method updateByUniqueId with my server data I do this by setting:
uniqueId: "id"

then in a method calling
`$("#my-table").bootstrapTable('updateByUniqueId', {id: id, row: rowData});`
This does not work.

Is there a way to easily get/set the uniqueId of a row in javascript or just get the index of selected rows? I looked through the documentation on http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options and couldn't see much that would help this issue.

Thanks

**Comment by wenzhixin** [comment]
Example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/415.html
