### ISSUE TITLE
Method getSelections or getAllSelections won't properly work if manually populating the tbody and pagination is true

### ISSUE THREAD

**Issue by efraimlorenzlongkines** [wenzhixin/bootstrap-table#2424]
Issue: getAllSelections  and getAllSelections  will return unselected rows when using table with pagination and when you manually populate your tbody.

I tried using getSelections and getAllSelections method with a table with pagination and it didn't work as expected. As i dig your code, I found that function `BootstrapTable.prototype.getSelections` is grepping `row[that.header.stateField]`. Based on my understanding a row that was selected will have a state = true. This wont work if you have a pagination because by default hidden data will have a `state = "<input id="some id" name="some name" onchange="countSelectedItem(this);" value="true" type="checkbox"><input name="some name" value="on" type="hidden">"`. Unselected row will be returned unless this is the expected behavior?

After updating the code from 

```
BootstrapTable.prototype.getSelections = function () {
        var that = this;

        return $.grep(this.data, function (row) {
            return row[that.header.stateField];
        });
 };
```
to
```
BootstrapTable.prototype.getSelections= function () {
        var that = this;

        return $.grep(this.data, function (row) {
            return row[that.header.stateField] === true;
        });
 };
```
it works as expected.

Hope this can help.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show the problem, thanks!

**Comment by efraimlorenzlongkines** [comment]
BTW, you will get this kind of issue if you manually populating your tbody, I already updated above post.

[jsfiddle](http://jsfiddle.net/swpez6mp/) for your reference. Just click directly the `Get Selected Row Count` button and you will see the issue

**Comment by efraimlorenzlongkines** [comment]
There are cases that check box is a must. As for me, im working on a spring java framework project and i need to bind the checkbox to a DTO property. I thnk the suggested fix will cater this scenario. Let me know on your thoughts on this.

**Comment by wenzhixin** [comment]
OK, PR is welcome.

**Comment by wenzhixin** [comment]
Fixed in develop branch.
