### ISSUE TITLE
关键词搜索的时候，ajax发送顺序不同导致结果覆盖问题

### ISSUE THREAD

**Issue by chenzhikang** [wenzhixin/bootstrap-table#2426]
举例：搜索保护套的时候有结果，但是baohutao却没有结果，在使用拼音输入法的时候，会同时发送这两个http请求到server，如果baohutao这个请求恰好pending，“保护套”请求先返回结果，就会造成搜索输入框中的文本为：“保护套”，但是搜索结果却为空（即baohutao的结果覆盖了“保护套”的结果）
请问：如何灵活控制这种ajax请求相互覆盖的情况？

**Comment by wenzhixin** [comment]
你可以开启按 enter 的时候再去搜索？

**Comment by chenzhikang** [comment]
@wenzhixin 开启点击 “搜索”再进行搜确实是一个这种的办法。如果最新版更新了这个问题，那就最好了。多谢答疑。抽时间去最新版查证一下。
