### ISSUE TITLE
Do not hit the server again if one request is already on the way.

### ISSUE THREAD

**Issue by anujism** [wenzhixin/bootstrap-table#2427]
The user should not be allowed to add any text in the filters when it is waiting for the data from server. For eg. if i search 'a' in a text box and server takes some time to respond and in the meantime if i press any key again, it will again hit once the first request is completed.

JS Fiddle: http://jsfiddle.net/e3nk137y/7118/

**Comment by anujism** [comment]
Even if we can just disable calling the server again when the previous filter value and current filter value is same, then it will resolved for now.

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/2979

**Comment by anujism** [comment]
Thanks. This is what I was expecting. You people are doing a good job.
