### ISSUE TITLE
Strict search for only 1 column

### ISSUE THREAD

**Issue by horsebuzz** [wenzhixin/bootstrap-table#2428]
I want to know if it is possible to have strict search enabled only for 1 column.
I have a field "gender" in my website and it is causing a problem with filter-search as male and female both has string "male" in it so it returns all data.

**Comment by wenzhixin** [comment]
You can set `strictSearch` option to `true`.

**Comment by horsebuzz** [comment]
I think thats for whole table right?

I am using filter for each column and i want to do strichSearch for only "gender" column and for all the other columns it should be to false.

I hope you can understand my question. I am adding the screenshot here so you can understand.

![screen shot 2016-07-05 at 12 25 36 pm](https://cloud.githubusercontent.com/assets/16217744/16572414/ace8ae7c-42ab-11e6-900f-568760088d0c.png)

So i need strichSearch="false" for  "firstname" and "lastname" but true for "gender".

**Comment by djhvscf** [comment]
@horsebuzz you can use the filterStrictSearch option, it will solve your problem
