### ISSUE TITLE
fixed-column issue

### ISSUE THREAD

**Issue by jankevinturado** [wenzhixin/bootstrap-table#2431]
hello, can someone help me with this? i have an issue on my fixed columns which is not align on my table. see attach screenshot. many thanks.

![fixedcolumns](https://cloud.githubusercontent.com/assets/18161991/16575611/4172cd6a-42bc-11e6-904b-ab3e2c36eefc.JPG)

**Comment by wenzhixin** [comment]
Fixed in the latest version: v.14.2
https://examples.bootstrap-table.com/#extensions/fixed-columns.html

**Comment by aloggnet** [comment]
Similar issue happening when clicking on a row to unfold advanced detailFormatter.
The rows of 2 fixed-columns become miss-aligned with the rest of the table (see below).

Plus I get the following error: 
> TypeError: undefined is not an object (evaluating 'e.attr("style").replace')

Screenshot:
<img width="1369" alt="Screenshot 2019-09-06 at 22 39 26" src="https://user-images.githubusercontent.com/35397278/64459234-aed1df00-d0f7-11e9-95d0-ee3058b88b1a.png">

Any clue ?

**BTW, GREAT TOOL !!!**

**Comment by djhvscf** [comment]
Please open a new bug and include a fiddle with your problem

@aloggnet

**Comment by aloggnet** [comment]
The issue can also be noticed on the following example: https://examples.bootstrap-table.com/index.html#extensions/fixed-columns.html

-> check row-1 and raw-3 
-> click "Hide Row" button
-> this results in a miss-alignement of the fixed-columns raws

The raws get aligned again after scrolling through the table.

@djhvscf

**Comment by wenzhixin** [comment]
Please create a new issue.

**Comment by aloggnet** [comment]
Here's the issue somehow related:
https://github.com/wenzhixin/bootstrap-table/issues/4587
Cheers,

@djhvscf
@wenzhixin
