### ISSUE TITLE
请教: 请问如果我想给tbody里面的tr/td添加colspan/rowspan要怎么添加

### ISSUE THREAD

**Issue by far21688504** [wenzhixin/bootstrap-table#2432]
如题, 现在的bootstrap-table好像只能在设置表头的时候添加colspan/rowspan, 如果我需要在bootstrap('load', data)的时候其中某个列需要跨三行该怎么办? @wenzhixin

**Comment by far21688504** [comment]
<table>
<thead>
<tr>
<th>Col one</th><th>Col two</th>
</tr>
</thead>
<tbody>
<tr><td>data one</td><td rowspan="3">data colspan 3</td></tr>
<tr><td>data two</td></tr>
<tr><td>data three</td></tr>
</tbody>
</table>

就像这样, 有什么办法可以做到吗?

**Comment by wenzhixin** [comment]
使用 `mergeCells` 方法：http://issues.wenzhixin.net.cn/bootstrap-table/#methods/mergeCells.html

**Comment by DimonHo** [comment]
对于[{"title":"aaa","psersion":[{"name":"tomg","age":19},{"name":"susan","age":18}]},{"title":"aaa","psersion":[{"name":"tomg2","age":19},{"name":"susan2","age":18},{"name":"susan2","age":17}]}]这样的数据，我的想法是如果可以支持:
data:[{ field: 'title', title: '标题'},
{ field: 'psersion.name', title: '姓名'},
{ field: 'psersion.age', title: '年龄'}]
就方便了。

**Comment by lianhr12** [comment]
@wenzhixin 这个针对tbody的td colspan，不能通过类型在DOM上来设置吗，类似<td data-colspan="2"></td>

**Comment by wenzhixin** [comment]
现版本不支持。
