### ISSUE TITLE
请问怎么在data-field里面用自定义标签呢

### ISSUE THREAD

**Issue by xusheng1987** [wenzhixin/bootstrap-table#2433]
如下:

`<th data-field="${fns:getDictLabel('1', 'sys_data_scope', '无')}">数据范围</th>`
其中fns:getDictLabel是我在jsp里面自定义的标签,可是却始终取不到值.请问该怎么处理

**Comment by wenzhixin** [comment]
利用 F12（chrome 浏览器）查看渲染后的代码是怎样的。

**Comment by xusheng1987** [comment]
渲染后是`<td style>-</td>`,我如果采用普通的方式
`
<tr>
<th>角色名称</th>
<td>${fns:getDictLabel(role.dataScope, 'sys_data_scope', '无')}</td>
</tr>
`
这么做是没问题的,用bootstrap-table不知该怎么办

**Comment by wenzhixin** [comment]
试过用 php 渲染是没有问题的，你可以先不使用 bootstrap-table，然后直接在 console 面板输入：
```
$('#table').bootstrapTable(); // table id 为 table
```

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!
