### ISSUE TITLE
求助，找不到表格导出功能的相关文档

### ISSUE THREAD

**Issue by lanten** [wenzhixin/bootstrap-table#2435]
只在例子中找到了data-show-export="true"，
却不知道JS中的初始化方法，
此外，例子中似乎不能导出全部分页

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/extensions/
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/export
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html
