### ISSUE TITLE
请教：为什么给表格列<th>设置宽度，无效果

### ISSUE THREAD

**Issue by tianjianwei1990** [wenzhixin/bootstrap-table#2436]
请教：为什么给表格列<th>设置宽度，无效果。需要如何给列设置固定宽度

**Comment by wenzhixin** [comment]
你可以使用 class 定义一个固定宽度。

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!
