### ISSUE TITLE
header cells width mistmatch columns width with table-condensed class and height option

### ISSUE THREAD

**Issue by crockstylie** [wenzhixin/bootstrap-table#2438]
Hi, and thank you so much for the time saved for me with your awesome plugin :)

When I add "table-condensed" class in the options, using a fixed height :
`<table id="bootstrapTable"
       data-toggle="table"
       data-height="300"
       data-classes="table-condensed">`
The fixed duplicated header cells width are bigger than the columns width :
![image](https://cloud.githubusercontent.com/assets/6499262/16613884/ac9f18de-436e-11e6-9b53-f84ae39f97a8.png)

Here I reproduced the behavior : [jsfiddle](http://jsfiddle.net/y4tk83k4/6/)

I am sorry for my approximative English ^^" have a great day

**Comment by dabros** [comment]
@crockstylie 

When you override a default, you replace it, not add to it. And as clearly stated in http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options, the default is currently `table table-hover`.

Look at your fiddle and remove that option, see the classes it adds to the table using F12 ([devtools for chrome ](https://developers.google.com/web/tools/chrome-devtools/?hl=en)for example). 

You need the `table` class at least to make it style right, if you want it `table-condensed` either make it `table table-hover table-condensed` or just `table table-condensed` if you dont want hover

ALWAYS inspect using F12 and compare to [working examples](http://issues.wenzhixin.net.cn/bootstrap-table/index.html), of which there are a great many

**Comment by crockstylie** [comment]
Oups ^^ OK, not an issue then.
I didn't check well enough. Thank you for pointing this out to me :)
