### ISSUE TITLE
1.11 : filterBy with array not working

### ISSUE THREAD

**Issue by vricard** [wenzhixin/bootstrap-table#2439]
Hi there,
Since the 1.10 to 1.11 maj, i can't filter with an array anymore : 
$('#table').bootstrapTable('filterBy', {id: [1,2,3]});
it only works with a single int
$('#table').bootstrapTable('filterBy', {id: 1});

thx for your work =3

**Comment by wenzhixin** [comment]
Fixed in develop branch.
