### ISSUE TITLE
Set SearchText on page-change event

### ISSUE THREAD

**Issue by iCeMAN020** [wenzhixin/bootstrap-table#2440]
Hi wenzhixin, thanks for the great plugin. 
I have a custom search whereby i have the search done on a button click. When the button is clicked, 
i'm retrieving the search text using : $('.fixed-table-toolbar').find('.search > :input').val() i'm then using the refresh event to post back to my controller: 
$table.bootstrapTable('refresh', {
                    url: '@Url.Action("Action", "ControllerName")',
                    query: { searchText: searchValue }
      }); 

I also have paging, so if the search results send back many results i need to page through those results with the same searchText but when it posts back to controller on page change then the searchText value is null. I tried using the : $table.on('page-change.bs.table') event and then have the refresh event like the one posted above but obviously that posts back twice to the controller, on the first call searchText is null and on the second it has the value set. How can i make the searchText value persist when paging ?

Thanks

**Comment by wenzhixin** [comment]
I think you can use `resetSearch` method to solve the problem.
