### ISSUE TITLE
使用 ajax 方式会向后台发起两次请求 请教下作者是不是我调用的姿势不对呢?

### ISSUE THREAD

**Issue by spencer-live** [wenzhixin/bootstrap-table#2442]
`BootstrapTable.prototype.init = function () {
 > this.initLocale();
    this.initContainer();
    this.initTable();
    this.initHeader();
    this.initData();
    this.initFooter();
    this.initToolbar();
    this.initPagination();
    this.initBody();
    this.initSearchText(); 
   // this.initServer();   **因为发现在onSort()中有调用initServer(),猜想是因为有排序所以调用了两次 ,目前注释掉此行,数据请求回来是正常的,只验证了ajax这种方式**
}`

> **调用方式如下**

> `var btOpts = {

        locale: 'zh-CN',

        // height: 650,

        pagination: true,
        sidePagination: 'server',
        pageNumber: 1,
        pageSize: 20,
        pageList: [10, 20, 50, 100],
        paginationPreText: '上一页',
        paginationNextText: '下一页',
        showRefresh: true,

        striped: true,

        search: true,
        searchText: 'ID / 名称',

        columns: columns,
        showColumns: true,

        // showFooter:true,
        // showToggle:true,

        url: GlobalUtil.action() + 'do_posGroup.jsp',
        method: 'POST',
        dataType: 'json',
        contentType: 'application/x-www-form-urlencoded; charset=UTF-8',

        idField: 'posGroupId'
    };

    $ctable.bootstrapTable($.extend(btOpts, {
        queryParams: function(params) {

            return $.extend({}, params, {
                method: 'list',
                nodeType: 1,
                search: params.search === btOpts.searchText ? '' : params.search
            });
        }
    }));`

由于图片总上传错误,这里直接发下network的请求
> do_posGroup.jsp	(canceled)	xhr	jquery.min.js:4	0 B	        2.16 s	
do_posGroup.jsp	200	                xhr	jquery.min.js:4	4.6 KB	115 ms

**Comment by wenzhixin** [comment]
麻烦提供下 jsfiddle
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by spencer-live** [comment]
不好意思.忘记回复了~ 找到原因我.是我给刷新按钮绑定了两次click事件. 谢谢
