### ISSUE TITLE
Any way of manually triggering the filter control search?

### ISSUE THREAD

**Issue by rickbarnsley** [wenzhixin/bootstrap-table#2443]
I would like to be able to manually trigger the filter-control search upon the click of a button.

i.e. users select all their filters within column headings (via the filter-control extension), and then click a button to trigger the update of the table based on the filter criteria they've selected.

I don't see a way of manually triggering that process... any ideas?

**Comment by lushuliang** [comment]
an example 


`
var $selectControl = $(".bootstrap-table-filter-control-"+field);
	$selectControl.val(value);
$selectControl.change();
`

**Comment by billbo99** [comment]
The above example does not work .. [fiddle](http://jsfiddle.net/billbo99/30xf2t8h/1/)

What I am looking for is a method to apply a bulk filter, and then reset to a blank state using JS.

**Comment by billbo99** [comment]
I am still an amateur JS coder,  but with a little hacking it looks  like you can trick things using keyup() instead of change().
http://jsfiddle.net/billbo99/30xf2t8h/2/

It would be nice if there was a method within the library that could be called instead, but for now I will go with this shortcut.

**Comment by djhvscf** [comment]
See this https://github.com/djhvscf/bootstrap-table/commit/227347f29d06d5acaa22f42372d21aa71f9ab761

I will create a new **PR** soon

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/2979
