### ISSUE TITLE
How to export subtable

### ISSUE THREAD

**Issue by drago1** [wenzhixin/bootstrap-table#2444]
Hi,
Can someone help me with exporting sub tables to Excel?
Is this possible to export sub table?

**Comment by wenzhixin** [comment]
I think the extension does not support this feature.

**Comment by dabros** [comment]
@drago1 - can you please provide a fiddle so we can try out some ideas

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

There are also others fiddles on similar issues, try searching "subtable" in github issues if want more example fiddles (which you can also fork to create your own)

**Comment by katrina-engelbrecht** [comment]
Hi,
I have the same question. I want to export table WITH its subtable in the detailview. How to do it?

**Comment by dabros** [comment]
@djhvscf @wenzhixin

**Comment by wenzhixin** [comment]
The extension does not support this feature
