### ISSUE TITLE
Bootstrap table shows hyphens for all the cells

### ISSUE THREAD

**Issue by krisrajz** [wenzhixin/bootstrap-table#2445]
<table id="tblSearch" class="table table-condensed table-hover table-striped">
                    <thead>
                        <tr>
                            <th data-column-id="Category">Category</th>
                            <th data-column-id="Report">Report</th>
                        </tr>
                    </thead>
               </table>

function bindSearchGrid() {
   
    var data =
        [
            { "Category": "Business", "Report": "Tours" },
            { "Category": "Admin", "Report": "Inventory" },
        ];
    console.log(data);
    $('#tblSearch').bootstrapTable({ data: data });
}

 
    <script src="~/Content/bootstrap-table/bootstrap-table.min.js" type="text/javascript"></script>
 

    <link href="~/Content/bootstrap-table/bootstrap-table.min.css" rel="stylesheet" type="text/css" />

I invoke the method on the click event of a button.

Really not sure of the problem

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/getting-started/#usage

`data-field`
