### ISSUE TITLE
Bug in editable sort  and search 

### ISSUE THREAD

**Issue by Janbsi** [wenzhixin/bootstrap-table#2446]
Good morning,
It happens something like what happens in the prime example

http://issues.wenzhixin.net.cn/bootstrap-table/

when editing a row and when you sort or search the table values are reset.

at this time the bug is reported and development?
or myself could develop!

**Comment by wenzhixin** [comment]
There are two sidePagination: `client` and `server` pagination, in our example, we use `server` side, when you edit the cell you need to post to server to update the data yourself.
So, this is not a bug.

**Comment by Janbsi** [comment]
In this case if I use side Pagination: the client could keep several rows sortable edited and then send them all to the server?

**Comment by wenzhixin** [comment]
Maybe you can add a button, click to save what you have changed.

**Comment by Janbsi** [comment]
Thanks already been solved, I've been working a long time with this framework, and I found interesting.

As suggestion would be good to have a way to assign a class to the rank of "No records found" as such could be sent error messages, or successful searches without results, things like that.


```
    if (!html.length) {
        html.push('<tr class="no-records-found '+this.options.formatClassNoMatches()+'">',
                sprintf('<td colspan="%s">%s</td>',
                    this.$header.find('th').length, this.options.formatNoMatches()),
                '</tr>');
        }
```


It would be great to send the class alert-danger  or something

I have not seen the way, if it already exists I would like to use.
