### ISSUE TITLE
Table with hyperlink

### ISSUE THREAD

**Issue by krisrajz** [wenzhixin/bootstrap-table#2447]
I need to create a column with hyperlink. The link should not display the URL but just some text and upon clicking the hyperlink it should open the link in a new page.

Any help would be appreciated.

The link looks like this:

<a href="http://www.blawblaw.com/Reports/V5.1.1/BusinessReport" target="_blank">Business Report</a>

**Comment by djhvscf** [comment]
See this example http://issues.wenzhixin.net.cn/bootstrap-table/#options/format.html
