### ISSUE TITLE
Filter control has embedded style

### ISSUE THREAD

**Issue by balen** [wenzhixin/bootstrap-table#2448]
This is more of a request rather than a bug. The filter control from the extension has embedded style:
```
style="margin: 0 2px 2px 2px;"
```
This prevents us from overriding the style for margin using the class "filterControl". Without overriding it appears that the filter control has no spacing between it and the adjacent search field to the right. It would be easier for people to override if the style was in a CSS file instead of being embedded.

btw - the older version of the filter control did not have this embedded style.

**Comment by djhvscf** [comment]
So, you mean we can use a new css file for filter-control?

**Comment by balen** [comment]
I was suggesting that it would be nice if we could over-ride the styles using a new CSS file.
But having the style embedded in the code for the element presents some complications. The margin style was not part of the element a few versions back...

**Comment by dabros** [comment]
@balen - you can still override using `!important` in your css, though i agree worth looking into for easily modability if we can remove some inline styling

**Comment by djhvscf** [comment]
See this **PR** https://github.com/wenzhixin/bootstrap-table/pull/2460
