### ISSUE TITLE
Boostrap table binding data

### ISSUE THREAD

**Issue by krisrajz** [wenzhixin/bootstrap-table#2449]
Binding static works:
   var data =
        [
            { "Category": "Accounts Payable", "Report": "AP Aged Balanced List","ReportPath":"abount:blank","IsSubscribed":"true"},
            { "Category": "Accounts Payable", "Report": "AP Matching Tolerance Hold", "ReportPath": "abount:blank", "IsSubscribed": "true" },
            { "Category": "Accounts Receivable", "Report": "AR Aged Balanced List", "ReportPath": "abount:blank", "IsSubscribed": "true" },
            { "Category": "Accounts Receivable", "Report": "AR Cash Commitment", "ReportPath": "abount:blank", "IsSubscribed": "true" },
            { "Category": "Accounts Payable", "Report": "AP Aged Balanced List", "ReportPath": "abount:blank", "IsSubscribed": "false" },
            { "Category": "Accounts Payable", "Report": "AP Matching Tolerance Hold", "ReportPath": "abount:blank", "IsSubscribed": "false" },
            { "Category": "Accounts Receivable", "Report": "AR Aged Balanced List", "ReportPath": "abount:blank", "IsSubscribed": "false" },
            { "Category": "Accounts Receivable", "Report": "AR Cash Commitment", "ReportPath": "abount:blank", "IsSubscribed": "false" },
            { "Category": "Accounts Payable", "Report": "AP Aged Balanced List", "ReportPath": "abount:blank", "IsSubscribed": "false" },
            { "Category": "Accounts Payable", "Report": "AP Matching Tolerance Hold", "ReportPath": "abount:blank", "IsSubscribed": "false" },
            { "Category": "Accounts Receivable", "Report": "AR Aged Balanced List", "ReportPath": "abount:blank", "IsSubscribed": "false" },
            { "Category": "Accounts Receivable", "Report": "AR Cash Commitment", "ReportPath": "abount:blank", "IsSubscribed": "true" }
        ];

Web Service returns:

{
   "$id": "1",
   "$values":    [
            {
         "$id": "2",
         "Category": "Accounts Payable",
         "Report": "AP Aged Balance List",
         "ReportURL": "http://dgreports_dev/APAgedBalancedList.aspx",
         "IsSubscribed": false
      }]}

Not sure whether this is issue with formatting.

**Comment by wenzhixin** [comment]
You can use `responseHandler` to solve your problem, example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/353.html.
