### ISSUE TITLE
latest version on npm is still 1.10.1

### ISSUE THREAD

**Issue by BenMann** [wenzhixin/bootstrap-table#2452]
Hey thanks for the library 🍰! 
I'm just wondering why the latest release available via npm is still on `1.10.1`, when `1.11.0` seems available.

**Comment by wenzhixin** [comment]
Thanks for your feedback, I will publish it soon.

**Comment by wenzhixin** [comment]
OK now: https://www.npmjs.com/package/bootstrap-table
