### ISSUE TITLE
Not loading data second time

### ISSUE THREAD

**Issue by krisrajz** [wenzhixin/bootstrap-table#2453]
HTML:
                <table id="tblSearch" class="table table-condensed table-hover table-striped">
                    <thead>
                        <tr>
                            <th data-field="Category" data-sortable="true">Category</th>
                            <th data-field="Report" data-sortable="true" data-formatter="ReportLinkFormatter">Report</th>
                        </tr>
                    </thead>
               </table>

Javascript:
$('#tblSearch').bootstrapTable(
           {
            url: DIServiceBaseURL + DIServiceURL,
               //data: data,
            dataType: 'json',
            cache: false,
            pageSize: 7,
            viewrecords: true,
            showHeader: true,
            pagination: true,
            success: function (data) {
                $('#tblSearch').bootstrapTable('hideLoading');
                $('#tblSearch').bootstrapTable('load', data);
                console.log("Service URL: " + DIServiceBaseURL + " Service Response : " +  data);
            },
            error: function (msg) {
                console.log(msg.responseText);
            }
        });
Everything seems working first time, however 2nd time the table is not binding to data.
Tried adding data-toggle="table" which results in not binding data for the first time too.
Any help would be much appreciated.
Thanks.

**Comment by djhvscf** [comment]
Can you provide an example? Fiddle? Please

**Comment by wenzhixin** [comment]
I think you are using in wrong way:
```
           success: function (data) {
                $('#tblSearch').bootstrapTable('hideLoading');
                $('#tblSearch').bootstrapTable('load', data);
                console.log("Service URL: " + DIServiceBaseURL + " Service Response : " +  data);
            }
```

**Comment by krisrajz** [comment]
Something like this:
https://jsfiddle.net/krisrajz/u5fa08mj/8/

**Comment by wenzhixin** [comment]
Your fiddle is broken, ref issues: #2021, #2317,  #1996 
https://github.com/wenzhixin/bootstrap-table/search?q=load&type=Issues&utf8=✓

**Comment by krisrajz** [comment]
Does this help
https://github.com/wenzhixin/bootstrap-table/issues/2453

**Comment by krisrajz** [comment]
Could you let me know what is wrong in there? I have referred various threads you replied in here and stackoverflow as well. Nothing helps so far.

**Comment by wenzhixin** [comment]
I want to help, but your fiddle does not work, please update it.

**Comment by krisrajz** [comment]
https://jsfiddle.net/krisrajz/6t1u5s83/3/

**Comment by wenzhixin** [comment]
base on these templates: #1765

**Comment by djhvscf** [comment]
@krisrajz I made an exception with this issue but we can't always be creating the fiddles.. See this: http://jsfiddle.net/djhvscf/e3nk137y/7585/ and let us know if this works for you

**Comment by krisrajz** [comment]
Just awesome! it works like plum!! You are setting new benchmarks on helping others!!! Many appreciations for both of you. I am closing this issue.
