### ISSUE TITLE
SearchText empty

### ISSUE THREAD

**Issue by mctdi** [wenzhixin/bootstrap-table#2456]
I init a table with this code

```
$("#paymentReportTableResult").bootstrapTable({
                url: getHostName() + "/payments",
                queryParamsType: "",
                responseHandler: function (res) {
                    return {
                        rows: res.content,
                        total: res.totalElements,
                        pageNumber: res.number,
                        pageSize: res.size
                    };
                },
                queryParams: function (params) {
                    debugger;
                    return {
                        search: params.searchText,
                        page: params.pageNumber - 1,
                        size: params.pageSize,
                        sort: params.sortName + "," + params.sortOrder
                    };
                }
            });
```

In the search zone, when i type a value and after i try to get the options of the table, the searchText is empty.

**Comment by djhvscf** [comment]
How are you trying to get the searchText? @mctdi

**Comment by mctdi** [comment]
yes

**Comment by mctdi** [comment]
i do $("#paymentReportTableResult").bootstrapTable('getOptions'); 
and i checked the searchText

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by mctdi** [comment]
basic example but bootstrapTable seem unknow...
http://jsfiddle.net/L45c3qfk/

**Comment by wenzhixin** [comment]
`searchText`?

**Comment by mctdi** [comment]
yes, better example: https://jsfiddle.net/teyymLua/

want to get sort and the text who is searched

**Comment by wenzhixin** [comment]
Not `$button`: https://jsfiddle.net/teyymLua/1/

**Comment by mctdi** [comment]
will try to put my example who don't work

**Comment by mctdi** [comment]
will newer version of bootstrap-table, that fixe the issue
