### ISSUE TITLE
miss 'resetSearch' method in Documentation

### ISSUE THREAD

**Issue by jackie88558** [wenzhixin/bootstrap-table#2457]
I found the 'resetSearch' method when reading the source code.
```
BootstrapTable.prototype.resetSearch = function (text) {
      var $search = this.$toolbar.find('.search input');
      $search.val(text || '');
      this.onSearch({currentTarget: $search});
};
```
But I didn't find anything about this method in [documentation](http://bootstrap-table.wenzhixin.net.cn/documentation/#methods)

I know how to use this method, but I think I should remind you if it really miss in the ducumentation.

**Comment by wenzhixin** [comment]
Thanks for your feedback, any pull request is welcome:)

**Comment by djhvscf** [comment]
@jackie88558 Thanks!

**Comment by wenzhixin** [comment]
Thanks
