### ISSUE TITLE
table resize after mergeCell

### ISSUE THREAD

**Issue by zoaeu12** [wenzhixin/bootstrap-table#2458]
hi.
table resize after first row mergecell then first column header auto resize
this is my code https://jsfiddle.net/n5wjx8h4/1/

**Comment by djhvscf** [comment]
Do you mean this?  @zoaeu12 
![capture](https://cloud.githubusercontent.com/assets/4496763/16790707/4854c3b8-4875-11e6-839b-7263efda0c74.PNG)

**Comment by zoaeu12** [comment]
yes exactly - @djhvscf
