### ISSUE TITLE
Table with filterBy and updateByUniqueId: Cannot read property '_data' of undefined

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#2461]
I've a bootstrap table where i load data from URL. The load load Ok.
Into the table they are enable and disable useres. When the page is load i filter the data with "**filterBy**" to see enable user.
I've into the toolbox two button:

1. "**Activate Only**" To see enable users
2. "**Desactivate Only**" To see disable users 

The two button aply de funtion with "**filterBy**"

If the table have data-pagination="true" and i click to the button "**Desactivate Only**" and click to the row button into the column action, they do nothing, and will return this error:

> Cannot read property '_data' of undefined
> bootstrap-table.js:1626

You can see the issue here: http://jsfiddle.net/hcbg3k8g/11/

But, if the page don't have pagination (data-pagination="false"), the script work like a charme.
You can see the script working here: http://jsfiddle.net/hcbg3k8g/12/

I'm ussing Chrome

Thank you for your help.

**Comment by djhvscf** [comment]
@manukieli I did not see the error in your fiddles, please double check them

**Comment by djhvscf** [comment]
Fixed in https://github.com/wenzhixin/bootstrap-table/pull/2460
See this example:

`data-pagination="false"`: http://jsfiddle.net/djhvscf/hcbg3k8g/14/
`data-pagination="true"`: http://jsfiddle.net/djhvscf/hcbg3k8g/13/

@manukieli

**Comment by manukieli** [comment]
OK, thank you very much.
It work like a charme.
But now, if i change the update method **updateByUniqueId** to **updateRow** y get the same issue:
> Cannot read property '_data' of undefined

**Comment by djhvscf** [comment]
@manukieli ok, it is the same bugfix... Adding `updatePagination()` call

**Comment by manukieli** [comment]
Ok, thank you so much.
