### ISSUE TITLE
jQuery.fn.bootstrapTable.defaults请问作者，是因为版本不对吗？为什么defaults没有那么多属性定义呢？

### ISSUE THREAD

**Issue by millionbug** [wenzhixin/bootstrap-table#2464]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by wenzhixin** [comment]
看清楚版本啊，现在最新是 v.1.11.0...

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/develop/dist/bootstrap-table.js#L3
