### ISSUE TITLE
Header alignement issue with group 

### ISSUE THREAD

**Issue by Bulsara** [wenzhixin/bootstrap-table#2465]
Hi all,

we have found an issue with the alignment of the header when the GroupBy extension is activated. 

Please see the picture.

![boostraptable-groupby-issue](https://cloud.githubusercontent.com/assets/2123492/16834601/df102c4e-49b4-11e6-8af1-e1e6a4666e6a.png)

We have solved the issue changing the method BootstrapTable.prototype.fitHeader (row 2120)

![boostraptable-groupby-issue-solved](https://cloud.githubusercontent.com/assets/2123492/16834829/e5e0f840-49b5-11e6-8433-486e4e394b29.png)

ORIGINAL: this.$body.find('>tr:first-child:not(.no-records-found) > *').each(function (i) {

PATCH: this.$body.find('>tr:not(.no-records-found, .groupBy)').first().children().each(function (i) {

Please check the patch and include it in the next version.

Regards.

Marco

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
I think this problem can be resolved in group-by extension instead of bootstrap-table, BTW, any pull request is welcome!

**Comment by Bulsara** [comment]
I have updated your jsFiddle: http://jsfiddle.net/e3nk137y/7600/

The issue happens when we set the height of the table. In this case the fixed-table-header element seems to be not correctly managed.

We have changed also boostrap-table-group-by.js in oder to manage the header in case of click on group row. 

Below the patch:

             this.$container.off("click", ".groupBy")
                .on("click", ".groupBy", function() {
                    $(this).toggleClass("expanded");
                    that.$body.find("tr[data-parent-index="+$(this).closest("tr").data("group-index")+"]").toggleClass("hidden");
					//Fix issue with header alignment with group by
					**that.fitHeader();**
                });

            this.$container.off("click", "[name="btSelectGroup"]")
                .on("click", "[name="btSelectGroup"]", function (event) {
                    event.stopImmediatePropagation();

                    var self = $(this);
                    var checked = self.prop("checked");
                    that[checked ? "checkGroup" : "uncheckGroup"]($(this).closest("tr").data("group-index"));
					//Fix issue with header alignment with group by
					**that.fitHeader();**
                });

I don't know how the groupby extension is activated, so the best solution that I found to solve the issue has been to work on the fitHeader method in the boostrap-table file.

Cheers,

Marco

**Comment by Falseee** [comment]
The groupby extension will be removed (#4281).
