### ISSUE TITLE
Bootstrap Modal vs Bootstrap Table - table body issue

### ISSUE THREAD

**Issue by koryun08** [wenzhixin/bootstrap-table#2466]
Hello!

I have an error with bootstrap table created via javascript in modal window. Please, tell me, what is wrong?
I already tested your [example](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/modal-table.html), but i need to created and fill table in modal dynamically.
Here is [jsFiddle](http://jsfiddle.net/8svjf80g/427/), where is issue presented.

![modalerror](https://cloud.githubusercontent.com/assets/7281137/16844327/28e99dc0-49fe-11e6-84aa-7dc64b26204c.PNG)

**Comment by wenzhixin** [comment]
Please update `div` to `table`:
```
<div id="tableDiv">      
</div>
```

```
<table id="tableDiv">      
</table>
```

http://jsfiddle.net/8svjf80g/428/

**Comment by koryun08** [comment]
Thank you very much!)
