### ISSUE TITLE
Hiding column

### ISSUE THREAD

**Issue by krisrajz** [wenzhixin/bootstrap-table#2468]
Is there a way to dynamically hide/unhide a column using jquery?

**Comment by djhvscf** [comment]
See this example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/basic-columns.html

**Comment by djhvscf** [comment]
@krisrajz Please double check the documentation: http://bootstrap-table.wenzhixin.net.cn/documentation/

**Comment by krisrajz** [comment]
My table does not have any column menu list

**Comment by djhvscf** [comment]
@krisrajz please provide a fiddle

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/showColumn-hideCoulumn.html

**Comment by lanten** [comment]
@wenzhixin 
Is there a way to manipulate multiple columns?

**Comment by wenzhixin** [comment]
I think it does not support manipulate multiple columns. @lanten

**Comment by krisrajz** [comment]
It does not work for me, hence I am trying to set columns and data fields dynamically.  I have set columns this way: columns: ["Category Description", "Report", "Report Description"] but not sure how to set data field? 

Any help would be appeciated.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by krisrajz** [comment]
http://jsfiddle.net/djhvscf/e3nk137y/7585/ (created by djhvscf some time ago for me, thanks djhvscf)

Or, is there a way to define the columns during runtime?

**Comment by wenzhixin** [comment]
Do you mean `refreshOptions` ?

**Comment by krisrajz** [comment]
I just want to select hide a particular column programmatically upon user choose different options. Only one boostrap table is used as almost all the columns are same except one column. Depending on the user's choice I want to hide the column. Since hideColumn does not work for me, I would like to know other workarounds such as defining columns based on user choice using juqery.

I don't want to define columns this way:
 <tr>
      <th data-field="Category" data-sortable="true">Category</th>
      <th data-field="Report" data-sortable="true" data-formatter="ReportLinkFormatter">Report</th>
    </tr>

I want to define them somewhere here:

$('#tblSearch').bootstrapTable("destroy").bootstrapTable(
           {
            //url: DIServiceBaseURL + DIServiceURL,
            data: data,
            dataType: 'json',
            cache: false,
            pageSize: 7,
            viewrecords: true,
            showHeader: true,
            pagination: true
          });

**Comment by krisrajz** [comment]
Here's the modified table I am using:

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Search Reports</h4>
            </div>
            <div class="modal-body">
                
                <div class="row" id="searchRow">
                    <table id="tblSearch" class="table table-condensed table-hover table-striped">
                    <thead>
                        <tr>
                            <th data-field="Category" class="col-md-2" data-sortable="true">Category</th>
                            <th data-field="CategoryDescription" class="col-md-3">Description</th>
                            <th data-field="Report"  class="col-md-2" data-sortable="true" data-formatter="ReportLinkFormatter">Report</th>
                            <th data-field="ReportDescription" class="col-md-3">Description</th>
                            <th data-field="Tags" class="col-md-2">Tags</th>
                        </tr>
                    </thead>
                </table>
              </div>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

**Comment by krisrajz** [comment]
I am looking out for something like this:
http://stackoverflow.com/questions/27915296/how-to-refresh-bootstrap-table-data

I do not know how to use refreshOptions
