### ISSUE TITLE
移动端浏览时，查询条件框输入文字后，好像没有触发search，导致没有结果，怎么破？

### ISSUE THREAD

**Issue by galaa2011** [wenzhixin/bootstrap-table#2469]
平台：移动端
配置：客户端查询、排序，client

1. 其实在手机键盘打字输入过程中，是有实时查询效果的
2. 但在选择文字到输入框后，却没有查询

**Comment by wenzhixin** [comment]
什么输入法？估计没有触发事件，你可以帮忙调试下这里，添加一些调试信息：https://github.com/wenzhixin/bootstrap-table/blob/develop/dist/bootstrap-table.js#L1176 ，看看是否触发。

**Comment by galaa2011** [comment]
苹果手机自带的输入法。
这块我调试过了，就是在拼音输入的过程，是可以触发查询的，但是当我选择字填充到输入框的那个时候，并没有触发查询。
而此时的查询结果，其实是输入时的拼音，而非我最终输到查询框中的字。

**Comment by galaa2011** [comment]
有临时解决方案不？

**Comment by wenzhixin** [comment]
没有苹果手机，暂时也没有环境。你假如熟悉 JavaScript 的话，欢迎提交 Pull Request.

**Comment by galaa2011** [comment]
一言不合，就pr 
---- 已提 ^_^
