### ISSUE TITLE
Table export does not export editable columns

### ISSUE THREAD

**Issue by bounlu** [wenzhixin/bootstrap-table#2471]
**Table export** does _**not**_ contain the entries from **editable** columns in the exported file.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by bounlu** [comment]
Here is the fiddle but table export and editable do not work on the fiddle although the same code does on my website:

https://jsfiddle.net/arkanion/fkaLzawe/

**Comment by dabros** [comment]
@bounlu 

Delete this duplicate topic, answered in #2470

**Comment by bounlu** [comment]
Well that's a different issue, I solved that one but I still have this problem.

**Comment by ggywebtech** [comment]
I have been having the same problems with editable as in #2470 but your answer has not worked for me.
I have made a fiddle hopefully showing how the select filters are blank but still work.

https://jsfiddle.net/ggywebtech/ywzm4sov/

**Comment by bounlu** [comment]
Thanks for this but I have no problem with the filtering. My issue is tableExport.js does not export editable fields although it does the header and the non-editable fixed columns (`data-editable = "false"`) in any format txt, csv, excel etc.

**Comment by bounlu** [comment]
I still have this problem after installing the latest version of the tableExport.js. tableExport does not export the typed or selected value of the editable fields in the exported file, it's just blank. any fix yet?

**Comment by bounlu** [comment]
I fixed this by removing the below function:

    function DoOnCellHtmlData(cell, row, col, data) {
        var result = "";
        if (data != "") {
          var html = $.parseHTML(data);

          $.each(html, function() {
              if (typeof $(this).html() === 'undefined')
                  result += $(this).text();
              else if (typeof $(this).attr('class') === 'undefined' || $(this).hasClass('th-inner') === true)
                  result += $(this).html();
          });
        }
        return result;
    }

    $(document).ready(function() {
        $('#table').bootstrapTable('refreshOptions', {
            exportOptions: {onCellHtmlData: DoOnCellHtmlData}
        });
