### ISSUE TITLE
父子表全选问题

### ISSUE THREAD

**Issue by zfqok** [wenzhixin/bootstrap-table#2473]
采用父子表的时候，子表全选时标题栏复选框不会被选中，因此只能全选而无法取消全选，请测试！
另外建议列增加自定义sortName排序字段名，特别是在采用Server分页排序字段和field字段不同的时候

**Comment by wenzhixin** [comment]
麻烦提供下jsfiddle
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by zfqok** [comment]
https://jsfiddle.net/9kjgdx1o/2/

**Comment by wenzhixin** [comment]
经过验证，该问题已经解决。
