### ISSUE TITLE
Multiselect dropdown on sort loses selected values and styles

### ISSUE THREAD

**Issue by srsharanya** [wenzhixin/bootstrap-table#2477]
When multiselect dropdrown is embedded in the coloumn, upon any action on the table. the selected values are lost and mutliselect style is lost.

https://jsfiddle.net/srsharanya/j80zhnwn/2/

**Comment by DustinUtecht** [comment]
Same for formatter which returns checkboxes (checked if row.value is xy).

**Comment by dabros** [comment]
@srsharanya - nothing to do with sort, everything to do with timing

Search, sort, refresh, paginate, ect. all update body content of table, so how is calling `$('select').multiselect();` ONE time on doc ready supposed to affect those..?

Look at the many [examples ](http://issues.wenzhixin.net.cn/bootstrap-table/index.html) and [doco](http://bootstrap-table.wenzhixin.net.cn/documentation/#events) and make use of `onPostBody` handler for the table, placing your extra table contents code in their will be called every time content update is made.


```javascript

 // debug for almost all events
 $table.on('all.bs.table', function (e, name, args) {
    console.log(name, args);
 });


 // just for onPostBody
 $table.on('post-body.bs.table', function (data) {
    console.log('onPostBody debug', [data,this]);
 });

```
