### ISSUE TITLE
Filter Table - with pagination

### ISSUE THREAD

**Issue by chandrantwins** [wenzhixin/bootstrap-table#2478]
Hi ,

Thanks for your good plugin. I need to filter table with pagination. once i filter pagination goes away. i know some old fix- make this change..any body have fix which will work filter and pagination. both

Thanks
Chandran Nepolean

**Comment by DustinUtecht** [comment]
Please provide a jsFiddle to show your problem!

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). 

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

**Comment by chandrantwins** [comment]
Hi ,

Thanks for your response problem solved...i have not send count from backend..that was the problem..

Thanks
Chandran Nepolean

**Comment by fish-fly** [comment]
Please close the issue.
