### ISSUE TITLE
advanced search form limit field example needed

### ISSUE THREAD

**Issue by quasiperfect** [wenzhixin/bootstrap-table#2479]
is there any way to limit the fields that appear in the advanced search form ?
can we use selects, radios or other fields ?

thanks in advance for any help

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by quasiperfect** [comment]
i'm not sure what i could show you in a fiddle
i just want to show specific fields in the advanced search form built by the toolbar plugin
and not use just simple inputs for those fields

**Comment by wenzhixin** [comment]
Do you mean toolbar extension? I think it does not support the features you want, any pull request is welcome.

**Comment by wenzhixin** [comment]
Close this because the extension does not support this feature, maybe we can use filter-control extension instead.
