### ISSUE TITLE
SelectAll with label:before checkbox styling

### ISSUE THREAD

**Issue by jraeruhl** [wenzhixin/bootstrap-table#248]
I've added a <label> to the checkbox inputs so I can hide the inputs and style via label:before. I can't seem to find a way to target the <tr> in .fixed-table-header in order to add the "selected" class to it (the selectAll checkbox). Even while trouble shooting with alerts it doesn't seem to recognize me clicking on anything nested within the .fixed-table-header.

**Comment by wenzhixin** [comment]
I don't know the exact problem mean and no reply, close this issue.
