### ISSUE TITLE
当字段的值是从其他列计算而来,sorter得到的值为undefined

### ISSUE THREAD

**Issue by LuffyChan888** [wenzhixin/bootstrap-table#2480]
页面显示pv,click,ctr三列数据，后台只返回两列数据， pv 和 click, ctr 的数据在formatter里用click*100/pv +“%” 计算得来，并给ctr 设置sorter:rateSorter

function rateSorter(a,b){
			 console.log(a,":",b)
			 if (parseFloat(a)){
				a = parseFloat(a);
			 }
			 if (parseFloat(b)){
				b = parseFloat(b);
			 }
			return (a >= b ? 1 : -1);
}

bootstrap-table.js
215行var getItemField = function (item, field, escape)
因为排序的值并不在item中，所以点击排序时，控制台打印的值为undefined:undefined
导致无法正常排序。

如果后台计算好ctr,返回三列数据，则rateSorter可以正常使用。

jsfiddle 链接 
https://jsfiddle.net/mef917sp/

**Comment by wenzhixin** [comment]
这种情况可以考虑使用 `responseHandler` 对数据进行输入，例如：
responseHandler: function (res) {
  $.each(res, function (i, row) {
    row.ctr = row.pv ? new Number(row.click * 100/row.pv).toFixed(2) + "%" : "0.00%"
  });
  return res;
}
```

**Comment by LuffyChan888** [comment]
嗯，了解，总之还是要预先处理好数据，谢谢啦...
