### ISSUE TITLE
Changing URL lost on pagination

### ISSUE THREAD

**Issue by achimha** [wenzhixin/bootstrap-table#2481]
With 1.11.0, there is a regression when using server side pagination and changing the URL. The URL is changed like this:

```
$("#table").bootstrapTable("refresh", {
    url: url
});
```

As soon as the page is changed, the URL for the request reverts to what is set in the initialization. It works fine with 1.10.1.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by achimha** [comment]
Here's a plunkr demo of the bug in version 1.11.0. It works fine in 1.10.1: https://plnkr.co/edit/szCdeSXYhNfnjDY8PQjH?p=preview

When you load it, you can see that it fetches the remote data using the URL `https://jsonplaceholder.typicode.com/posts?order=asc&offset=0&limit=10`. Then click on the button "Modify URL" which performs the following operation:

```
$("#testtable").bootstrapTable("refresh", {
    url: "https://jsonplaceholder.typicode.com/posts?testargument"
});
```
It changes the URL of the table and you can observe that it now performs the server request with the changed URL. Now click on the pagination control "say page 2" and you will see that the server request to fetch page 2 is using the old URL, thus missing the `?testargument`. This worked fine in 1.10.1.

**Comment by dabros** [comment]
@achimha - `queryParam` and similar used to handle param, so better to change actual url (not query param)

@wenzhixin 
I did rule out that as the issue though, checked https://jsonplaceholder.typicode.com/ and made changed url as https://jsonplaceholder.typicode.com/comments (no title index, but works) or https://jsonplaceholder.typicode.com/todos (with title index)

**Comment by achimha** [comment]
@dabros I don't change `queryParam` in the sample as you can see. I change the URL which is reset by the pagination. Just to be sure: It works fine up until 1.10.1 so it's a regression in 1.11.0 and master.

**Comment by dabros** [comment]
@achimha - you were using a GET query parameter as example, but thats not reliable as it risks being overriden or causing duplicate '?' as thats what bootstrapTable uses by default, just look at the network requests, 'queryParam` is just one of the methods for inserting custom query parameters.

In any case, I ruled that out, and thank you for testing and sharing version numbers

**Comment by achimha** [comment]
I've updated the plunk to change the base URL instead of adding a query parameter as suggested by you:

https://plnkr.co/edit/szCdeSXYhNfnjDY8PQjH?p=preview

**Comment by balen** [comment]
I have the same issue. I found a "fix" and that is to change the method BootstrapTable.prototype.refresh as follows:
```
    BootstrapTable.prototype.refresh = function (params) {
        if (params && params.url) {
            this.options.url = params.url;
            this.options.pageNumber = 1;
        }

        this.initServer(params && params.silent,
            params && params.query, params && params.url);
        this.trigger('refresh', params);
    };
```
i.e. put in the line assigning params.url to this.options.url

**Comment by wenzhixin** [comment]
#2740 This bug has been fixed in the latest version: https://github.com/wenzhixin/bootstrap-table/issues/2740
