### ISSUE TITLE
Problem with cookie extension 

### ISSUE THREAD

**Issue by turigeza** [wenzhixin/bootstrap-table#2483]
I can not get the cookie extension to work it will not call queryParams. But maybe it is its default behaviour ?

My code looks like this. 

```
$('#reorderingProductsTable').bootstrapTable({
        url: '{{path('gecorg_reordering_supplier_products_json')}}',
        classes: 'table table-no-bordered',
        showExport:true,
        clickToSelect:true,
        toolbar:'#reorderingProductsTableToolbar',
        showColumns: true,
        pageSize: 50,
        showMultiSort: true,
        filterControl: true,

       // if you uncomment the following three lines everything works fine
        cookie:true,
        cookieIdTable:'reorderingProductsTable',
        cookieStorage: 'localStorage',

        responseHandler:function responseHandler(res) {
            log('responseHandler');
            return res.rows;
        },

        queryParams:function queryParams(params) {
            log('yes');
            $('#reorderingProductsTableToolbar').find('input[name]').each(function () {
                params[$(this).attr('name')] = $(this).val();
            });
            log(params);
            return params;
        },

        columns: [
            {
                field: 'state',
                checkbox: true,
            },
            {
                field: 'id',
                sortable: 'true',
                title: 'ID',
                filterControl :'input'
            },
            {
```

And if cookies disabled everything works fine. But if 

```
        cookie:true,
        cookieIdTable:'reorderingProductsTable',
        cookieStorage: 'localStorage',

```

Then queryParams will never get called. Is this normal ?

Geza

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by turigeza** [comment]
Hi,

I have seen it but I am not sure if I can. The problem I have is with 

```
queryParams:function queryParams(params) {
            log('yes');
            $('#reorderingProductsTableToolbar').find('input[name]').each(function () {
                params[$(this).attr('name')] = $(this).val();
            });
            log(params);
            return params;
        },

```
which only used if remote json datasource is used. I don't think I can do that on sjFiddle or Can I ? Unfortunately my dev server is local as well otherwise I would show you there ...

I try and put it online somewhere but it will take me some time ... 

Thank you,

**Comment by turigeza** [comment]
I guess before I start hunting for the problem I just want ask does the cookie extension meant to work with remote datasource at all ?

Wouldn't it normally call 'queryParams' ?

**Comment by dabros** [comment]
@turigeza 

You can mimic data using jsfiddle echo (http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery) or even just data-url from certain [examples](http://issues.wenzhixin.net.cn/bootstrap-table/index.html), doesnt need to be fancy, just any data from remote url if thats what queryParam option needs to trigger

**Comment by turigeza** [comment]
@dabros Hey :) Thank you but the I am not sure how the json echo url would help me here ... 
Anyhow I found some other json data out there list of US presidents : )
So here is the jsfiddle:

https://jsfiddle.net/gezaatturigezacom/62wpstwb/

You can uncomment the cookies lines and you will see that queryParams will not be called.

**Comment by bolom** [comment]
@turigeza are you able to fix your problem bc i have got the same issue

**Comment by turigeza** [comment]
@bolom no I was not able to use the plugin after all. I have wrote a small plug in to save some of the settings in the server side instead as table views but it is rather bodged : )

**Comment by bolom** [comment]
craps @turigeza . so i will have to same thing

**Comment by djhvscf** [comment]
This issue is solved in: https://github.com/wenzhixin/bootstrap-table/pull/3184

Example: https://jsfiddle.net/djhvscf/62wpstwb/1/
