### ISSUE TITLE
Bootstrap-Table [wenzhixin] Filter-Control extension

### ISSUE THREAD

**Issue by lureg** [wenzhixin/bootstrap-table#2484]
I am using Filter-Control extension, but it does not work well with pagination. It seems that select options load as they are being shown in different pages. I actually gave up on that and decided to use **filterData:'var:section_options'** where section_options is a variable loaded from an ajax.

After having huge sync issues but kinda solving them, i got stuck again.

**QUESTION**: When i add a column, my filter disappears. Is there anything I can do? If I call the initTable function again the added column disappers (which is actually intended).

Filter loading function:

``` javascript
var section_options;
function get_sections(){
    $.ajax({
      type: 'POST',
      url: "/cgi-bin/switchmap/search-ngn.py",
      dataType: "json",
      data: {"action":"sections"}, 
      error: function(response) {
        alert("Error en section_options");
      },
      success: function(response) {
        section_options = response;
      },
      complete: function() {
      }
    });
    initDevTable();
  }

```

InitTable function:

``` javascript

function initDevTable() {

    $("#devtable").bootstrapTable({
        // height: getHeight(),
        columns: [
     {
      field: 'id',
      title: '',
      visible: false,
      sortable: true,
      align: 'center',
      valign: 'middle'
    }, {
      field: 'hostname',
      title: 'Hostname',
      sortable: true,
      align: 'center',
      valign: 'middle',
      footerFormatter: textFormatter,
      filterControl: 'input'
    }, {
      field: 'section',
      title: 'Section',
      sortable: true,
      align: 'center',
      valign: 'middle',
      filterStrictSearch: true,
      filterData: "var:section_options",
      filterControl: 'select'
    }, {
      field: 'devtype',
      title: 'Device Type',
      visible: false,
      sortable: true,
      align: 'center',
      valign: 'middle',
      filterControl: 'input'
    }, {
      field: 'total_ports',
      title: 'Number of ports',
      sortable: true,
      align: 'center',
      valign: 'middle',
      footerFormatter: totalFormatter,
      filterControl: 'input'
    }, {
      field: 'ip',
      title: 'IP',
      visible: false,
      align: 'center',
      valign: 'middle',
      filterControl: 'input'
    }, {
      field: 'domain',
      title: 'Domain',
      sortable: true,
      align: 'center',
      valign: 'middle',
      filterControl: 'input'
    }, {
      field: 'filiales',
      title: 'Filiales',
      visible: false,
      sortable: true,
      align: 'center',
      valign: 'middle',
      filterControl: 'input'
    }, {
      field: 'last_query',
      title: 'Last update',
      visible: false,
      sortable: true,
      align: 'center',
      valign: 'middle',
      filterControl: 'input'
    }, {
      field: 'automatic',
      title: 'Automatic',
      visible: false,
      sortable: true,
      align: 'center',
      valign: 'middle',
      formatter: autoFormatter,
      footerFormatter: autoFormatter,
      filterControl: 'input'
    }, {
      field: 'oper',
      title: '',
      align: 'center',
      valign: 'middle',
      formatter: actionFormatter,
      events: actionEvents
    }] 
    });
    select_devices();

  }

```

**Comment by DustinUtecht** [comment]
I think you have a old version of the Bootstrap Table, this bug is fixed in newest version.
(If i understand your problem correctly)

**Comment by dabros** [comment]
@wenzhixin @djhvscf - can you confirm @DustinUtecht comment?

**Comment by liuminlovedbymiao** [comment]
I found a bug when I use filterControl when I sort the <option>s when data is a numeric.
`sortSelectControl: function sortSelectControl(selectControl) {
        var $selectControl = $(selectControl.get(selectControl.length - 1));
        var $opts = $selectControl.find('option:gt(0)');

        $opts.sort(function (a, b) {
            
          var aa = $(a).text().toLowerCase();
          var bb = $(b).text().toLowerCase();
          if ($.isNumeric(aa) && $.isNumeric(bb)) {
            // Convert numerical values from string to float.
            aa = parseFloat(aa);
            bb = parseFloat(bb);
          }
          return aa > bb ? 1 : aa < bb ? -1 : 0;
        });

        $selectControl.find('option:gt(0)').remove();
        $selectControl.append($opts);
      },`
 should be "if ($.isNumeric(aa) && $.isNumeric(bb))" ,not "if ($.isNumeric(a) && $.isNumeric(b))" ,Just be Your writing error.By the way ,You are very “牛人”！

**Comment by liuminlovedbymiao** [comment]
I find a bug when I am using filterControl when I sort the <option>s when data is  numeric. It should be "if ($.isNumeric(aa) && $.isNumeric(bb))" ,not "if ($.isNumeric(a) && $.isNumeric(b))" ,Just be your writing error.

![image](https://user-images.githubusercontent.com/11011855/53233573-afa9a300-36c8-11e9-93ba-c3f9363cc621.png)

**Comment by UtechtDustin** [comment]
I close this issue because its already some years old, if there is still an issue with that please provide us an example(jsfiddle) and reopen the issue.

@liuminlovedbymiao 
If that bug still exists, please open your own issue and explain why that is an issue.
For me it looks fine, if is not numeric order by alphabet else by float.
