### ISSUE TITLE
Problem Bootstrap Table Method getSelections with search box [BUG]

### ISSUE THREAD

**Issue by ghost** [wenzhixin/bootstrap-table#2485]
I have a problem with bootstrap table, specifically the method GetSelections.
It happens that when you select a row in the table and then look at the box search bootstrap table and reselect the desired row, the method GetSelections concatenates the first row and the second row (the second row is searched in the box search ), and does not replace the data (object) as it should be.

Example 

![ejemplo](https://cloud.githubusercontent.com/assets/7819935/16965795/cc53a5d0-4dcf-11e6-976c-c7f65aad0045.PNG)

![ejemplo2](https://cloud.githubusercontent.com/assets/7819935/16965884/265e10ce-4dd0-11e6-848a-84d5aa4b2935.PNG)

![ejemplo3](https://cloud.githubusercontent.com/assets/7819935/16965883/265de770-4dd0-11e6-8d71-3e209ddf9e77.PNG)

![ejemplo4](https://cloud.githubusercontent.com/assets/7819935/16965886/26836ed2-4dd0-11e6-82fb-dbc8924da2f2.PNG)

![ejemplo5](https://cloud.githubusercontent.com/assets/7819935/16965885/267e972c-4dd0-11e6-8c86-c3faa45c018e.PNG)

select a row, press the button GetSelections, find another example value "3" and select a row .Finally press the button again.

the values are concatenated and are not updated or replaced as it should.

Here Example

https://jsfiddle.net/8bqrcLfk/24/

**Comment by abhsk1** [comment]
@B-Alvarez Did this problem gets resolved ?

**Comment by B-Alvarez** [comment]
oh no, I still have the error.

**Comment by B-Alvarez** [comment]
In the bootstrap-table.js set  "maintainSelected: false,"  and change the code 
if (that.options.maintainSelected && $(this).is(':radio')) {
to
if (!that.options.maintainSelected && $(this).is(':radio')) {

**Comment by LayGe** [comment]
I  use your method.But I still have the problem.Do you use the client paganition?

**Comment by LayGe** [comment]
It worked!Thanks!

**Comment by wenzhixin** [comment]
Fixed: http://jsfiddle.net/wenyi/e3nk137y/26120/
