### ISSUE TITLE
Looking to apply default filter with the 'filter-control' extention

### ISSUE THREAD

**Issue by billbo99** [wenzhixin/bootstrap-table#2487]
I am using 'filter-control' and I would like to find some method to apply a default column filters as the table is created.

Would be nice if I could put something on the column definition to set the default filter
`<th data-field="scope" data-filter-control="select" data-filter-control-default="live" >Scope</th>`

**Comment by djhvscf** [comment]
It is a good idea! Remember any **PR** is welcome

**Comment by YiiTing** [comment]
where can i find the method?
