### ISSUE TITLE
action attached to selector in table will not fire on page change

### ISSUE THREAD

**Issue by mariuscucuruz** [wenzhixin/bootstrap-table#2488]
If I have a selector (ie a link) with an action attached (eg on('click') ) in any of the cells, that action won't fire when page is changed, sorting is applied search is performed. 

Here's a short example: https://jsfiddle.net/L4h0gs4g/
The link will trigger the alert box at first, but if you sort the table it will not trigger again. It's like jQuery cannot _see_ that selector once the table's been changed / updated.

Is this a known bug or is there a workaround this at all?

Thanks

**Comment by dabros** [comment]
@mariuscucuruz 

Not a bug, always look at [examples ](http://issues.wenzhixin.net.cn/bootstrap-table/index.html)and [doco ](http://bootstrap-table.wenzhixin.net.cn/documentation/#events)when having issues, this is very clearly explained and demonstrated, as well as answered in dozens of other issues here

There are a few options for this:

1. Apply a `formatter` and add handler then, will work fine but not my personal pref, here is an [example ](http://issues.wenzhixin.net.cn/bootstrap-table/options/format.html)where you can see them attached, for custom handler add that inside the `formatter`

2. `onPostBody`, this is why this event exists, see #2477 for related issue and explanation

**Comment by wenzhixin** [comment]
Answer in: http://stackoverflow.com/questions/38486499/action-attached-to-selector-in-bootstrap-table-will-not-fire-on-page-change/38493964#38493964
