### ISSUE TITLE
It would be nice to expose `getData` interface.

### ISSUE THREAD

**Issue by ladjzero** [wenzhixin/bootstrap-table#249]
Hi, Wen. In my case, it is a must to fetch data through CORS. I have to modify the ajax request. Of course, there might be other more strange issues that bootstrap-table can not handle well. I think it is could be better to expose `getData` interface and focus on rendering table.

**Comment by wenzhixin** [comment]
Hi @ladjzero , in your case, you can use `ajaxOptions` or `queryParams` or `responseHandler` options to do what you need. Close this issue.
