### ISSUE TITLE
GetOptions for "Columns" has changed?

### ISSUE THREAD

**Issue by rfossella** [wenzhixin/bootstrap-table#2490]
Previous version of code (v1.70) defined 
```
BootstrapTable.DEFAULTS 
        columns: [],
```

It now defines it as `columns:[ [] ]`

This results in calls to **aTable.bootstrapTable("getOptions")["columns"]** to return different results than before.  Instead of getting straight-up array of column objects it is now contained within another array.  Is/was this desired behavior?

It broke some custom code I had written whereby I was certainly expecting columns as before.

Has anyone experienced this?  I wanted to know if I should change my code with this new implementation.

**Comment by wenzhixin** [comment]
After v1.7.0, we add to support group headers(`colspan` and `rowspan`), you can use:
`aTable.bootstrapTable("getOptions")["columns"][0]` to solve your problem.

https://github.com/wenzhixin/bootstrap-table/blob/develop/CHANGELOG.md

**Comment by rfossella** [comment]
This worked for me.  Thank you for clarification.
