### ISSUE TITLE
table上的data-data-field不支持多级

### ISSUE THREAD

**Issue by pengliang159** [wenzhixin/bootstrap-table#2491]
我返回的结果是result.list。所以使用data[this.options.dataField]获取值是undified。是否需要做个处理
var fields = this.options.dataField.split('.');
$(fields).each(function(){
data = data[this]
})
当然不使用在table上添加 data- 的方式是可以的。

**Comment by pengliang159** [comment]
还有分页参数的传参能否自己定义。看到默认的是offset和limit。参数名倒是没问题。但是值可以自定义不。后端有自己的分页处理，要的是页码和数量。

**Comment by wenzhixin** [comment]
`queryParams` 和 `responseHandler` 可以解决你的问题：http://bootstrap-table.wenzhixin.net.cn/documentation/ ，多看文档和例子。

**Comment by pengliang159** [comment]
嗯，是使用的responseHandler来处理的。就是用到queryParams的时候，好像排序没有用了，所以自己又在queryParams。通过getOptions()获取排序，又放了一遍排序的param

**Comment by wenzhixin** [comment]
queryParams 是有 order 和 sort 属性的，你可以看下文档。
