### ISSUE TITLE
请教作者，如果动态设置Get的url

### ISSUE THREAD

**Issue by YeaseonZhang** [wenzhixin/bootstrap-table#2492]
我现在是需要动态的获取`url`，然后改变table`get`到的数据，之前静态的时候通过在`table`标签中设置`data-url`就可以了，我看您在源码中默认属性有个`url`
```
$("#table").bootstrapTable({
        url: dir
    })
```
我就希望能这样动态设置，但是没有效果，是不是`url`这个属性不是用来获取远程数据的，请问您我这个情况怎么样才能动态设置？

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/409.html

**Comment by wenzhixin** [comment]
The same with #409.

**Comment by YeaseonZhang** [comment]
thanks
