### ISSUE TITLE
How to use a select in search

### ISSUE THREAD

**Issue by joefreire** [wenzhixin/bootstrap-table#2493]
I want to use a select instead of an input
how i can do that?

**Comment by wenzhixin** [comment]
Custom toolbar can be help: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

**Comment by joefreire** [comment]
thanks help me so much,
but i need find a way to past a field with a value (searchText) to queryParams , that is possible?

**Comment by wenzhixin** [comment]
You can define the `queryParams` option to send any params what you want.
