### ISSUE TITLE
data-sorter when no data-field 

### ISSUE THREAD

**Issue by nicgravel** [wenzhixin/bootstrap-table#2494]
On some field I need to use the data from two fields in the database so I use the data-formatter
With that, sorting is not working.
I try to use the data-sorter with a custom function but no value is sent to that function when not linked to a data-field.
Is there a way in the sorter function to have the row information ?

`function durationFormatter(value, row, index){
		var title = TF.getDiffTimeMinutesSeconds(row.start, row.end);
		var txt = TF.getDiffTimeSeconds(row.start, row.end)
		return '<div title="' + title + '" data-toggle="tooltip">' + txt + '</div>';
	}`

**Comment by wenzhixin** [comment]
It seems the same with #2480.

**Comment by dabros** [comment]
@nicgravel 

That linked issue has a fiddle, if a match please say so.

If NOT a match then please provide your own and we can help you more. Dummy data from js array is fine (just needs to replicate core issue), if you need data url then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

**Comment by nicgravel** [comment]
yes that works... sorry I didn't find it before writing a new issue...
