### ISSUE TITLE
Searching after dynamically setting cell value

### ISSUE THREAD

**Issue by rfossella** [wenzhixin/bootstrap-table#2495]
I started running into an odd searching issue which I believe may be related to my dynamic creation of anchor fields inside cells.

Scenario:
I have a table with 100's of rows that correspond to files that I track on a file system.  When a file is created I dynamically change the contents of the cell holding a file name to a hyperlink which links to/opens the contents of the file.

_Before_ I change the contents the search works fine.  _After_ the cell is updated the **same** search fails - i.e. I get no results.  I'm assuming that there's a cache that's holding on to the "flat" td value of the cell and now cannot see the anchor?  Does that sound feasible?

I use a cell renderer/function whereby _aRow.state_ is a boolean indicating if I should change to a live anchor.

```
function fileNameFormatter(aValue, aRow, anIndex) 
{
  var newValue = aValue;

  if (aRow)
  {
    var myPath = aRow.fullPath;
    if (myPath && aRow.state == "true")
    {  
      var regex = /\\/g;
      var myPath = myPath.replace(regex, "\\\\");
      newValue = [
          '<a class="spanCursor" href="javascript:setUpFileNameLink(\''  + myPath + '\')">' + newValue + '</a>'
            ]
    }
  }

  return newValue;
}
```

Should I be updating/refreshing local cache when the cell changes to anchor?  Any ideas I might follow up on?

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). If you need data url then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

The dynamic change function can be mimicked too, we just need to see demonstration of core issue on ANY data

**Comment by syedhassan** [comment]
@dabros check this [jsfiddle ](http://jsfiddle.net/x60aLcky/)

1. First select all rows that have the word "Cat" that is the first row and the second row.
2. Search for cat.
3. When you see filtered search with Cat in name you don't see the checkbox already checked which we did in step1.

How to make the checkbox appear checked even after searching.

**Comment by dabros** [comment]
Of course it acts that way.

You are not editing the row contents when you click the checkbox (via `updateRow` or similar), nor are you affected the original data source (via ajax or similar) and then refreshing from that.

If you want it to stick then you have to add handler for it, you havent bound that column to any field/row.index so why would it remember..?

You should be able to use `editable` plugin or even just direct `updateRow` to save state to table data, it will be lost on page or datasource refresh but will remain between searches and ect. Using ajax or similar is what you need if you want to persist that to original datasource, but that doesnt seem like what you are asking for.

Checkout `editable`, examples and doco for that online, and many good examples in other issues

That looks too much, checkout `updateRow` and adding a handler to those checkboxes

For both cases, get away from that awkward html declaration of row data, bind that checkbox column to a field. If using `updateRow` (and 'maybe' if not, test yourself) use the `checkbox` column option OR custom formatter to acheieve UI, event can be handled by the `onClickCell` (the `clickToSelect` option might make this easier) or custom handler, again look around for the many examples of adding handlers to cell or objects within.

http://bootstrap-table.wenzhixin.net.cn/documentation
http://issues.wenzhixin.net.cn/bootstrap-table/index.html

**Comment by rfossella** [comment]
Just following up on my original issue with searching for dynamically created anchors in table.

I assume there was one incarnation of the code that required the cell render function to return an array
e.g. from my code above
```
newValue = [
          '<a class="spanCursor" href="javascript:setUpFileNameLink(\''  + myPath + '\')">' + newValue + '</a>'
            ]
```
That single element array caused my search to fail.  When I changed it to this it worked:
`newValue =  '<a class="spanCursor" href="javascript:setUpFileNameLink(\''  + myPath + '\')">' + newValue + '</a>'`

**Comment by wenzhixin** [comment]
I think the `maintainSelected` option can solve the checked problem: https://examples.bootstrap-table.com/index.html#options/maintain-selected.html

The `searchFormatter` column option solve the search problem: https://bootstrap-table.com/docs/api/column-options/#searchformatter
