### ISSUE TITLE
我有一个json，制定dataField 不起作用。请帮助

### ISSUE THREAD

**Issue by liming84525** [wenzhixin/bootstrap-table#2496]
在 $("selector").bootstrapTable() 里面从服务器获取json 指定dataField是rows, 但是不能加载。 求助！
json 如下：
{
    "errcode": 100,
    "errmsg": "ok",
    "rows": [
        {
            "created": 1469117708000,
            "id": "67c30b7a-d41d-4c7b-aaf7-8ae8afaefc2e",
            "name": "阿萨德飞",
            "open": true,
            "unit": "大师傅 "
        },
        {
            "created": 1469160661000,
            "id": "6dc41fc7-cb3b-40be-8d70-e440042549e9",
            "name": "",
            "open": true,
            "unit": "啊圣诞节法拉利 "
        },
        {
            "created": 1469117152000,
            "id": "b8cf0f05-54a2-4f29-8349-6da6f24c6805",
            "name": "阿萨德飞",
            "open": false,
            "unit": "阿萨德飞"
        },
        {
            "created": 1469118730000,
            "id": "d98671aa-4a62-4b26-a3d7-949e9c924252",
            "name": "哈哈",
            "open": true,
            "unit": "哈哈"
        },
        {
            "created": 1469117967000,
            "id": "f6051526-354a-46b7-a068-9adc4b5c8a3d",
            "name": "撒旦法",
            "open": true,
            "unit": "sdf  fasdf "
        }
    ]
}

**Comment by wenzhixin** [comment]
用 responseHandler 处理，假如是 client 就
