### ISSUE TITLE
Multi Sort Giving same Columns 

### ISSUE THREAD

**Issue by Nikhilkapoor20** [wenzhixin/bootstrap-table#2497]
Hi 

I created Main table and on popup Another table , but i am getting same cloumns in multi sort property 

https://plnkr.co/edit/8xh5uBwOkCfeD4rDJyIB

Please check if anyone can help me out #urgent

**Comment by dabros** [comment]
@Nikhilkapoor20 - ive looked at this a few times now and still no idea what this is about

Your examples seems to have some issues with ui, not sure if that stopping me from seeing it, but you NEED to clarify better.

Namely, what is (in detail and step by step) expected output vs actual output?

Also, what have you done to try and rectify this?

**Comment by Lwazee** [comment]
When adding levels, they all default to "first option" in selecting sorting column to sort.  Is it possible for them to default to the next available column? 

If I add a level, and click cancel away from the page, then return, it holds the additional levels added even though I did not actually apply the sort. Would it be possible to hold the selection only when the sort button is applied?

**Comment by UtechtDustin** [comment]
I close the issue because its older than 2 years, also the bug seems to fixed in the newest version.
Your Example works fine for me.
