### ISSUE TITLE
Blocked cookies should not throw exception

### ISSUE THREAD

**Issue by JonasKress** [wenzhixin/bootstrap-table#2499]
In chrome in some cases cookies are blocked by default causing bootstrap table to throw an exception:

`Configuration error. Please review the cookieIdTable, cookieExpire properties, if those properties are ok, then this browser does not support the cookies`

**Comment by talatbaig** [comment]
getting the same error in safari and firefox

**Comment by talatbaig** [comment]
anyone know what is causing this?

**Comment by djhvscf** [comment]
See this https://github.com/djhvscf/bootstrap-table/commit/68fbc0f0ea126c44d16f42ba8fabc44ebf6cd3c2

I will create a **PR** soon

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/2979
