### ISSUE TITLE
bootstrap-table connection to mysql with php

### ISSUE THREAD

**Issue by LeonardoFonseca6** [wenzhixin/bootstrap-table#25]
Hi Bro,

I need your help, first tanks for your contribution is excelent. second i want show my data from mysql to your table with php, how can i do it? and i want fixed the first column, can you explain me how do that? thanks...

LeonardoF5
From: Colombia

**Comment by crynos** [comment]
I have the same problem of tiagoriba. 
No results...

here my "json.php" and the index. Can someone help me ?

json.php

<?php
include 'ARQUIVOS/functions/functions.php';

$query = "SELECT setor, nome, ramal FROM contatos ORDER BY setor ASC, nome ASC";
//Faz a conexão com o banco de dados e executa a query

$result = db_query($query);


while($r = mysqli_fetch_assoc($result)) {
    //$dados[]= $r['idcontatos'];
    $dados[]= $r;    
    }
    // free result set
    $result->close();
    
     
    // close connection
    mysqli_close($result);

     
    echo json_encode($dados);

And index.php:
```<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Manager</title>
<link href="ARQUIVOS/css/bootstrap.min.css" rel="stylesheet">
<link href="ARQUIVOS/css/estilo.css" type="text/css" rel="stylesheet" />



<script  src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="ARQUIVOS/js/bootstrap.min.js"></script>
<script src="ARQUIVOS/js/bootstrap-table/dist/bootstrap-table.js" type="text/javascript"></script>
<script src="ARQUIVOS/js/bootstrap-table/dist/locale/bootstrap-table-pt-BR.js" type="text/javascript"></script>


</head>

<body>
<table data-toggle="table"
       data-url="json.php"
       data-cache="false"
       data-side-pagination="server"
       data-height="300">
    <thead>
    <tr>
        <th data-field="setor">setor</th>
        <th data-field="nome" data-align="right">nome</th>
        <th data-field="ramal" data-align="center">ramal</th>

    </tr>
    </thead>
</table>

</body>
</html>```

**Comment by wenzhixin** [comment]
It seems you need to set `data-side-pagination="server"` to `data-side-pagination="client"` @crynos

**Comment by cafi** [comment]
@crynos how would be your functions.php?

**Comment by jacean** [comment]
@wenzhixin thanks,get method is ok ,but when i used post,table don't work.i don't konw why,please.
