### ISSUE TITLE
Please tell me how to use load 

### ISSUE THREAD

**Issue by faruk786** [wenzhixin/bootstrap-table#250]
$.ajax({
		  type: 'GET',
		  url: 'deviceGroup.do?_ajax=true&action=Json&Id=213&search="name"',
		  mimeType: "multipart/form-data",
		  async: false,
		  contentType : false,
		  cache : false,
		  dataType: 'json',
		  processData : false,
		  success: function(data) {
		   $('#bootTable').bootstrapTable('load',data);
		  }
	 });

i want to load table after getting search response but im unable to load please help me

**Comment by wenzhixin** [comment]
Close this issue.
