### ISSUE TITLE
支持不支持树形table？，可以展开收缩

### ISSUE THREAD

**Issue by zhouwenyang** [wenzhixin/bootstrap-table#2500]

**Comment by qiujie8092916** [comment]
能具体一点吗

**Comment by zhouwenyang** [comment]
是这样的我现在在使用你的bootstrap table做一个应用。
应用中有树型结构的场景。
我的意思能不能给一个json的树状结构，自动生成树？
我现在没办法只能给他一个普通的数组，然后通过样式控制树形的显示。
然后展开伸缩就特别麻烦。。。
有没有开发这个功能的打算。




 
 
------------------ Original ------------------

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/treegrid.html
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/tree-column.html
