### ISSUE TITLE
Can i use select2 plugin in x-editable Extension

### ISSUE THREAD

**Issue by ZenixFrost** [wenzhixin/bootstrap-table#2505]
I wanna use x-editable select and I can search data from dropdown. can i ?

like this
![image](https://cloud.githubusercontent.com/assets/20263725/17147967/52acbe90-538f-11e6-8fe1-48423cc96fa0.png)

**Comment by wenzhixin** [comment]
The same with #2109, please search the issues: https://github.com/wenzhixin/bootstrap-table/search?q=select2&type=Issues&utf8=%E2%9C%93 before create a new issue, thanks.
