### ISSUE TITLE
Isn't refreshing data-url when server-side pagination enabled

### ISSUE THREAD

**Issue by TechArts** [wenzhixin/bootstrap-table#2507]
When you have enabled server side pagination, provided data-url via data attributes, and then trying to refresh table with new data-url, then it's refreshed just for current view. Any next sorting, paging will use old/initial data-url.

How to reproduce:
1. create table via data attributes, specify server side for pagination, specify data-url
`<table id="postsMetricsDetails" class="table table-hover" data-toggle="table" data-pagination="true" data-side-pagination="server" data-url="http://127.0.0.1/1url">`
2. Load table with data by 
`$('#postsMetricsDetails').bootstrapTable('refresh', { url: "http://127.0.0.1/2_URL" });`
3. Table is represented, data refreshed. Click next page, or sorting - request will to old, initial data-url http://127.0.0.1/1url

**Comment by TechArts** [comment]
Seems like issue related to refresh method, because he doesn't set/refresh remote-url option, but just refresh data for current load.
`              $('#postsMetricsDetails').bootstrapTable('refreshOptions', {
                  url: new_url
              });` 
helps to fix the issue

**Comment by wenzhixin** [comment]
OK, close the issue.
