### ISSUE TITLE
ajax 加载数据的时候，能不能像extjs那样显示loading，优雅一点

### ISSUE THREAD

**Issue by hawind** [wenzhixin/bootstrap-table#2509]
ajax 加载数据的时候，能不能像extjs那样显示loading，优雅一点。
extjs目测做法是，先开启loading层，覆盖整个body区域，loading...显示在中间，等获取到数据后，再绘制，我发现bootstrap-table现在是加载开始就清空内容了，导致表格一闪，高度发生了变化，给人一种非常难受的感觉。

**Comment by wenzhixin** [comment]
麻烦提供下链接。

**Comment by wangat** [comment]
到处都是一艘一大把http://docs.sencha.com/extjs/4.2.1/#!/example/grid/paging.html
