### ISSUE TITLE
 data-response-handler="responseHandler"

### ISSUE THREAD

**Issue by lovezhl456** [wenzhixin/bootstrap-table#2510]
look
                 <table
                    id="table"
                    data-response-handler="responseHandler"
                >
if the function responseHandler(){}  is not  exists   would be  error

because 
    var calculateObjectValue = function (self, name, args, defaultValue) {
     .........
        if (!func && typeof name === 'string' && sprintf.apply(this, [name].concat(args))) {
            return sprintf.apply(this, [name].concat(args));
        }
        return defaultValue;
    };

**Comment by wenzhixin** [comment]
Why you define `data-response-handler="responseHandler"`, but `responseHandler` function does not exist?

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
