### ISSUE TITLE
点击下一下时之前填的查询条件被重置了

### ISSUE THREAD

**Issue by tbygg** [wenzhixin/bootstrap-table#2512]
`
define(function(require,exports,module){

    var template = require("/js/plugins/template/artTemplate/template");

    var TableTemplate = {
        initTable:function(queryUrl,tableSelector,toolbarSelector,columns,queryMap){
            $(tableSelector).bootstrapTable({
                columns: columns,
                toolbar: toolbarSelector,
                cache:false,
                pagination: true,
                pageSize: 10,
                pageNumber: 1,
                pageList: [10, 20, 30, 50],
                sidePagination: 'server',
                selectItemName: 'id',
                striped: true,
                showExport: false,
                showColumns: true,
                showRefresh: true,
                showToggle: false,
                idField: 'id',
                checkboxHeader: true,
                queryParams:function(params){
                    var query = {
                        page:params.offset/params.limit +1,
                        pageSize:params.limit,
                    };
                    $.extend(query,queryMap);
                    return query;
                },
                ajax: function (params) {
                    $.ajax({
                        type: "POST",
                        url: queryUrl,
                        dataType: 'json',
                        //data:postData,
                        data:params.data,
                        traditional:true,
                        success: function (result) {
                            if (result) {
                                if(result.code == 20001){
                                    window.parent.location.href = "/login";
                                    return false;
                                }
                                params.success(result);
                            } else {
                                $(tableSelector).bootstrapTable('removeAll');
                            }
                            //params.complete();
                        },
                        error: function () {

                        }
                    });
                },
                onLoadSuccess: function (data) {

                }

            });
        },
    };
    module.exports = TableTemplate;
});

`
上面是我使用的模板，使用1.11版本,可以设置一些查询出部分结果，但是点击一下时查询条件就会被重置，查询出来的是全部结果的分页数据,

**Comment by sugerlemon** [comment]
查询下一页的时候，是带参数到服务器的，search=xxx，你要把xxx传递给服务器，然后才能查询到你想要的。

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by tbygg** [comment]
`define(function(require,exports,module){
    var template = require("/js/plugins/template/artTemplate/template");

    var $table;
    var queryOptions;
    var _tableSelector
    var TableTemplate = {
        initTable:function(queryUrl,tableSelector,toolbarSelector,columns,queryMap){
            queryOptions = queryMap;
            _tableSelector = tableSelector;
           $talbe = $(tableSelector).bootstrapTable({
                columns: columns,
                toolbar: toolbarSelector,
                cache:false,
                pagination: true,
                pageSize: 10,
                pageNumber: 1,
                pageList: [10, 20, 30, 50],
                sidePagination: 'server',
                selectItemName: 'id',
                striped: true,
                showExport: false,
                showColumns: true,
                showRefresh: true,
                showToggle: false,
                idField: 'id',
                checkboxHeader: true,
                queryParams:function(params){
                    var query = {
                        page:params.offset/params.limit +1,
                        pageSize:params.limit,
                    };
                    $.extend(query,queryMap);
                    return query;
                },
                ajax: function (params) {
                    $.ajax({
                        type: "POST",
                        url: queryUrl,
                        dataType: 'json',
                        //data:postData,
                        data:params.data,
                        traditional:true,
                        success: function (result) {
                            if (result) {
                                if(result.code == 20001){
                                    window.parent.location.href = "/login";
                                    return false;
                                }
                                params.success(result);
                            } else {
                                $(tableSelector).bootstrapTable('removeAll');
                            }
                            //params.complete();
                        },
                        error: function () {

                        }
                    });
                },
                onLoadSuccess: function (data) {

                }

            });
        },
        modifyQueryParams:function(queryAdd){
           $(_tableSelector).bootstrapTable("refreshOptions",{
                queryParams:function(params){
                    var query = {
                        page:params.offset/params.limit +1,
                        pageSize:params.limit,
                    };
                    $.extend(query,queryOptions,queryAdd);
                    return query;
                }
           });
        },
    };
    module.exports = TableTemplate;
});

`
现在模板改成这样了，每次查询的时候调用 modifyQueryParams方法
在内部调用refreshOptions方法,把queryParams替换掉，然后点下一页时就可以保留之前的查询条件了

**Comment by wenzhixin** [comment]
这种也可以。

**Comment by liyang1987jay** [comment]
define(function() {
	var User = {
		userList: function() {
			var that = this;
			$('#usertable').bootstrapTable({
				locales: 'zh-CN',
				toolbar: '#toolbar', //工具按钮用哪个容器
				striped: true, //是否显示行间隔色
				pagination: true, //是否显示分页（*）
				sortable: true, //是否启用排序
				sortOrder: "asc", //排序方式
				queryParams: that.queryParams, //传递参数（*）
				queryParamsType: "limit",
				sidePagination: "client", //分页方式：client客户端分页，server服务端分页（*）
				pageNumber: 1, //初始化加载第一页，默认第一页
				strictSearch: true,
				showColumns: true, //是否显示所有的列
				showRefresh: true, //是否显示刷新按钮
				minimumCountColumns: 2, //最少允许的列数
				uniqueId: "sys_user_id", //每一行的唯一标识，一般为主键列
				showLoading: true,
				ajax: function(params) {
					$.ajax({
							url: URL.getUserListUrl,
							type: 'GET',
							dataType: 'json',
							//跨域请求
							xhrFields: {
								withCredentials: true
							},
						})
						.done(function(result) {
							 params.success(result.rows);
						})
						.fail(function() {
							console.log("error");
						})
						.always(function() {
							console.log("complete");
						});

				},
				columns: [{
					checkbox: true
				}, {
					field: 'sys_user_id',
					title: '用户ID',
					sortable: true,
				}, {
					field: 'sys_user_login_name',
					title: '登录名称',
				}, {
					field: 'sys_user_state',
					title: '用户状态',
				}]
			})
		},

		queryParams: function(params) {
			var temp = { //这里的键的名字和控制器的变量名必须一致，这边改动，控制器也需要改成一样的
				limit: params.limit, //页面大小
				offset: params.offset, //页码
			};
			return temp;
		}
	};

	require(['jquery', "config", "functions", "bootstrap", 'bootstrap-table', 'bootstrap-table-local'], function($, C, D) {
		$(function() {
			var act = D.get('act');
			switch (act) {
				case "userList":
					User.userList();
					break;
			}
		})
	});
});
我这样写的 但是不对

**Comment by liyang1987jay** [comment]
@tbygg 你的返回值是什么样的 我的是{"total":16,"rows":[{"sys_user_state":"正常","sys_user_id":1,"sys_user_login_name":"super"},{"sys_user_state":"正常","sys_user_id":2,"sys_user_login_name":"zhang"},{"sys_user_state":"正常","sys_user_phone":"13864039387","sys_user_id":7,"sys_user_login_name":"admin1","sys_user_name":"李四","sys_user_email":"sdsf@qq.com"},{"sys_user_state":"正常","sys_user_id":8,"sys_user_login_name":"admin"},{"sys_user_state":"正常","sys_user_id":9,"sys_user_login_name":"ddd"},{"sys_user_state":"禁用","sys_user_id":11,"sys_user_login_name":"as"},{"sys_user_state":"禁用","sys_user_id":12,"sys_user_login_name":"aed"},{"sys_user_state":"禁用","sys_user_id":13,"sys_user_login_name":"esdf"},{"sys_user_state":"禁用","sys_user_id":14,"sys_user_login_name":"ead"},{"sys_user_state":"禁用","sys_user_id":15,"sys_user_login_name":"adf"}]}
但是total怎么赋值呢
