### ISSUE TITLE
When used with the editable and filter-control, the value which can not be displayed by select

### ISSUE THREAD

**Issue by jackluck** [wenzhixin/bootstrap-table#2514]
When used with the editable and filter-control, the value which can not be displayed by select
![1](https://cloud.githubusercontent.com/assets/15390521/17243397/307633c0-55af-11e6-8ab4-b3982a859e03.png)
![2](https://cloud.githubusercontent.com/assets/15390521/17243398/30953b94-55af-11e6-9d4d-5403e808c6ae.png)

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). If you need data url then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

You need to replicate that issue before we can help you more, dummy data is fine, just needs to show the problem in a fiddle

**Comment by dougauerbach** [comment]
I am also encountering this same issue. Here is a new Fiddle to demonstrate it. 

https://jsfiddle.net/cd8u9qzw/1/
