### ISSUE TITLE
固定列的问题

### ISSUE THREAD

**Issue by lonelyclick** [wenzhixin/bootstrap-table#252]
请问能否实现这样的功能呢？
由于列数太多，能否实现前几列固定，后面几列在下面出现滚动条可以滚动？谢谢！
![qq 20141119111225](https://cloud.githubusercontent.com/assets/8056201/5100145/0f41eee2-6fdd-11e4-95b4-ad817b7f620a.png)

**Comment by wenzhixin** [comment]
与 #265 为同个 feature，关闭这个。
