### ISSUE TITLE
能够添加行编辑功能

### ISSUE THREAD

**Issue by lslvxy** [wenzhixin/bootstrap-table#2530]
能够添加行编辑和新增行的功能

**Comment by panxq5** [comment]
行编辑有插件
行新增也是有的

**Comment by wenzhixin** [comment]
这里有例子：https://github.com/wenzhixin/bootstrap-table-examples/tree/master/crud

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html

**Comment by lslvxy** [comment]
这个是针对单元格的编辑，我们需要的是一个整行的编辑功能，就像这样的效果，[示例图片](https://raw.githubusercontent.com/lslvxy/testWeb/master/20160804191209.png)，最后一列是根据配置有新增，编辑和删除。进行整行的新增和编辑

**Comment by panxq5** [comment]
@lslvxy 
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html 
用这个插件可以实现真行编辑，最后的新增编辑按钮，自己使用列的formatter功能来实现

建议 多看下API

**Comment by niuqiong** [comment]
有整行编辑的DEMO吗？想参考下。 @panxq5
