### ISSUE TITLE
使用服务器端分页，客户端无法一次导出全部查询数据

### ISSUE THREAD

**Issue by sugerlemon** [wenzhixin/bootstrap-table#2531]
已经使用最新版的bootstrap-table

是不是因为我用的server模式，然后查询数据每次返回的数据被limit了，所以在客户端使用export all 的时候，导出的也只能是limit数量的“”全部数据“”呢？

服务端的查询代码如下：

`SELECT * FROMtestORDER BY checkouttime desc LIMIT 0,20`

**Comment by wenzhixin** [comment]
全部数据的时候你服务器端要返回所以的数据呀。

**Comment by sugerlemon** [comment]
问题是，已经在js里面使用server模式分页了，那如果服务器返回所有数据，那客户端怎么进行分页的？

**Comment by wenzhixin** [comment]
这里有导出所有的例子：http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html
有一点需要后台支持，就是当你没有传 limit 的时候，后台要返回全部的数据。
