### ISSUE TITLE
获取不到pageNumber

### ISSUE THREAD

**Issue by izhijian** [wenzhixin/bootstrap-table#2538]
使用最新版本的bootstarp-table，我使用如下方式，怎么都无法获取到pageNumber这个参数：
	```
oTableInit.queryParams = function(params) {
		console.log(params);
		var temp = { 
					pageSize : params.limit, 
					currentPage : params.pageNumber 
		};
		return temp;
	};
```

请问这是为什么？ 是在新版本里面移出了吗？已经设置分页pagination为true，服务器分页，然后我吧整个params 参数打印出来也没有这个参数，只有这些参数：
Object {search: undefined, sort: undefined, order: "asc", offset: 0, limit: 100}

实在是费解

**Comment by panxq5** [comment]
可以这么获取
$table.bootstrapTable("getOptions").pageNumber

不知道会不会有点绕

**Comment by wenzhixin** [comment]
你可以设置 `queryParamsType` 不为 limit，或者像 @panxq5 所说的。
