### ISSUE TITLE
没有加载前事件来进行预加载处理

### ISSUE THREAD

**Issue by WinfredMao** [wenzhixin/bootstrap-table#2540]
预加载处理还是有必要的。

比如当前表格打开是默认加载的，如果我想阻止加载，可以使用预加载事件，设置cancel为true，取消加载。

或者自定义了查询面板，需要在查询前设置查询条件。

或者当前情况是不适合加载的。比如主子表的情况下，如果主表选择了一条数据，则对子表进行过滤加载，如果主表选择了更多的数据，则在预加载事件中进行判断，取消此次加载。

或者一些其他在新数据请求之前对旧数据进行处理的情况。

具体实现可以参见我的fork
https://github.com/WinfredMao/bootstrap-table/commit/1a313d81a2fad5e1150d32fc8e3ae57d4876686a

或者该特性可以通过已有的某些方式来实现，请告知。

**Comment by wenzhixin** [comment]
你可以自定义 extension 来实现。
