### ISSUE TITLE
insert Row after Click event and addClass doesn't work

### ISSUE THREAD

**Issue by panxq5** [wenzhixin/bootstrap-table#2541]
this donen't work for me
```
'click .move-up': function (e, value, row, index) {
    if (index != 0) {
                     $table.bootstrapTable("insertRow", {
                            index: index - 1,
                            row: row
                        });
                       $('.success').removeClass('success');
                       $(this).parent().parent().prev().addClass('success')
                    }
           }
```

remove insetRow event ,is work
```
'click .move-up': function (e, value, row, index) {
    if (index != 0) {
                       $('.success').removeClass('success');
                       $(this).parent().parent().prev().addClass('success')
                    }
           }
```

i don't know why?

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

It needs to replicate the core issue, actual data doesnt matter. Also ensure you are always debugging as you code, using F12 and console especially (to show errors generated by your code, which im willing to bet there is at least one of)

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by panxq5** [comment]
@wenzhixin @dabros 
![image](https://cloud.githubusercontent.com/assets/10496200/17391676/ad277ccc-5a4a-11e6-99e2-d9947fa61c5d.png)

**Comment by dabros** [comment]
@panxq5 - we need a fiddle to help more, examples and such are provided in my last post

**Comment by panxq5** [comment]
@dabros OK

**Comment by panxq5** [comment]
@wenzhixin @dabros 
http://jsfiddle.net/panxq5/bqz39omr/14/

this doesn't work for me,if i remove
`$("#table").bootstrapTable("insertRow", {
                            index: index - 1,
                            row: row
                        });`
it worked

**Comment by dabros** [comment]
@panxq5 

You really need to explain desired outcome vs actual outcome and steps taken already when asking for help

You description was almost useless, and no it didnt work if you removed that, and you obviously had not closely examined the official examples for those methods

Here is a working version where it shows how to properly `remove` the old row (though i would recommend having an actual 'id' or other unique field, which doesnt need to even have its own column, instead just be part of row data, i use `stargazers_count` as example only)

http://jsfiddle.net/dabros/qnryo3dy/

As shown, you can use `unique-id` if you wish for both `remove` and the `selected` css toggle, though thats entirely option, as shown and commented in the fiddle

**Comment by panxq5** [comment]
@dabros thank you!!
