### ISSUE TITLE
bug select and search on bootstrap table

### ISSUE THREAD

**Issue by B-Alvarez** [wenzhixin/bootstrap-table#2544]
I have a problem with bootstrap table, specifically the method GetSelections.
It happens that when you select a row in the table and then look at the box search bootstrap table and reselect the desired row, the method GetSelections concatenates the first row and the second row (the second row is searched in the box search ), and does not replace the data (object) as it should be.

Example 

![ejemplo](https://cloud.githubusercontent.com/assets/7819935/16965795/cc53a5d0-4dcf-11e6-976c-c7f65aad0045.PNG)

![ejemplo2](https://cloud.githubusercontent.com/assets/7819935/16965884/265e10ce-4dd0-11e6-848a-84d5aa4b2935.PNG)

![ejemplo3](https://cloud.githubusercontent.com/assets/7819935/16965883/265de770-4dd0-11e6-8d71-3e209ddf9e77.PNG)

![ejemplo4](https://cloud.githubusercontent.com/assets/7819935/16965886/26836ed2-4dd0-11e6-82fb-dbc8924da2f2.PNG)

![ejemplo5](https://cloud.githubusercontent.com/assets/7819935/16965885/267e972c-4dd0-11e6-8c86-c3faa45c018e.PNG)

select a row, press the button GetSelections, find another example value "3" and select a row .Finally press the button again.

the values are concatenated and are not updated or replaced as it should.

Here Example

https://jsfiddle.net/8bqrcLfk/24/

**Comment by panxq5** [comment]
i have the same problem,i have set `data-single-select="true"`, but when change page and click another,2 data was checked;

![image](https://cloud.githubusercontent.com/assets/10496200/17473432/0f8b2e46-5d83-11e6-8e42-34b71a6d7cb8.png)
![image](https://cloud.githubusercontent.com/assets/10496200/17473435/152ddd3a-5d83-11e6-8cd1-171e569cb982.png)

**Comment by abhsk1** [comment]
Even I am facing the same issue - When I **select**  some row in bootstrap table(with data-single-select="true") and then do search on table and select some other row. Then I found that both the rows are selected on bootstrap table.

**Comment by abhsk1** [comment]
@B-Alvarez Did this problem gets resolved to you ?

**Comment by B-Alvarez** [comment]
I have not managed to solve the problem because of time constraints. I hope
soon to have a solution, if I can inform you fix the error.

2016-08-09 9:05 GMT-04:00 abhsk1 <notifications@github.com>:

**Comment by abhsk1** [comment]
Mentioning here the exact issue - 
Lets assume bootstrap table has some rows and user has selected 1 row assuming(which is at data-index  3 i.e. row no. 4). Now user searched the rows based on some criteria which gives certain results and after that we have refreshed the table on back-end(using auto refresh customized written function) and then I observed that selection was getting selected to data-index 3 on any searched result. 

Please let me if further inputs is needed in order to make you understand it in better way. 
Due to time constraint , I could not be able to provide jsfiddle.

**Comment by B-Alvarez** [comment]
??

**Comment by B-Alvarez** [comment]
@abhsk1 The problem occurs as mention, any solution?

**Comment by B-Alvarez** [comment]
In the bootstrap-table.js set  "maintainSelected: false,"  and change the code 
if (that.options.maintainSelected && $(this).is(':radio')) {
to
if (!that.options.maintainSelected && $(this).is(':radio')) {

**Comment by wenzhixin** [comment]
Fixed: https://jsfiddle.net/wenyi/8bqrcLfk/29/
