### ISSUE TITLE
customSearch not triggering custom function

### ISSUE THREAD

**Issue by joshglenn** [wenzhixin/bootstrap-table#2545]
I am using bootstrap-table on osx. Trying to implement customSearch. However, when I set data-custom-search to `data-custom-search="customSearchFunction"` in the table attributes in the HTML, **_customSearchFunction_** does not get called. Instead I get this error:

```
bootstrap-table.js:1229 Uncaught TypeError: this.options.customSearch.apply is not a function
```

That's because the function name is being treated as a string. If I set a breakpoint before that line and enter this command in the console `this.options.customSearch = customSearchFunction`, then things work properly (temporarily).

How do I tell bootstrap-table to call my customSearchFunction (the right way)?

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

It could a timing/scoping issue where that function not reachable at `data-toggle` timing (as commented in several other issues here, the 'js init' is far more reliable)

If switching timing doesnt work provide a fiddle replicating core issue

thanks

**Comment by robertmarkevans** [comment]
Had exactly the same problem just.

Solution is to not use the data-custom-search option on the HTML, but instead to add this within the .bootstrapTable initialization js code

customSearch: function(text) {
   console.log(text)
}

Strangely before getting to this point, I had to replace the bootstrap-table-min-js  file as my copy didn't have any of the customSearch code ( no idea why, but one to check, old version presumably )

**Comment by 1kko** [comment]
I'm getting same error as @robertmarkevans 

here's my jsfiddle.
https://jsfiddle.net/1kko/u4r2osrr/

**Comment by eleweek** [comment]
I think you should set up your function from javascript, because bootstrap-table expects this attribute to be an actual function(and not a string with function name)

**Comment by jonatanklosko** [comment]
It is clearly a bug
https://github.com/wenzhixin/bootstrap-table/blob/4b6fd6b375b3678135cb8d3f20cca0793a32d9e1/src/bootstrap-table.js#L1326-L1329
This indicates that `options.customSearch` should be globally-reachable function name, not a function itself (as the documentation stands).

This is similar code for `customSort`, and calls the function as expected:
https://github.com/wenzhixin/bootstrap-table/blob/4b6fd6b375b3678135cb8d3f20cca0793a32d9e1/src/bootstrap-table.js#L998-L1001
