### ISSUE TITLE
Reorder rows with detail view bug

### ISSUE THREAD

**Issue by kritochin** [wenzhixin/bootstrap-table#2547]
Hi. I need to use the detailview and reorder extension at the same time, but there seems to be a bug. 
1. Row X is expanded
2. Row X is reorder
3 The detail view row is left behind:

![image](https://cloud.githubusercontent.com/assets/3598010/17423183/7bc77cca-5a7e-11e6-9194-eecab25c7834.png)

I know this is happening because the detail view row is just a row that is displayed below the row expanded... and is not inside the parent row

I would like to know is there a way this can be adjusted.

Thank you very much.

**Comment by UtechtDustin** [comment]
This issue is already older than 2 years, if the bug still exists please reopen and provide us an jsfiddle.
