### ISSUE TITLE
the project shows correct in Chrome but run in firefox browser the bootstrap table didnt show and the console shows the error "$('#table').bootstrapTable is undefined",i dont know why,the jquery.js is injected before bootstrap.table,can anybody help me ?

### ISSUE THREAD

**Issue by summerangel** [wenzhixin/bootstrap-table#2548]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by djhvscf** [comment]
I am not sure what you mean. I am going to need some more information. @summerangel

**Comment by summerangel** [comment]
the page is a table,and it can show the table in browser Chrome,but not show in browser Firefox,also the console shows the error "$('#..').bootstrapTable is undefined",but strangely it shows correctly in other computer using the Firefox,is some version of Firefox not support bootstrapTable?@djhvscf

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

If you can replicate this in a fiddle, then we can help, else its environmental and we cant fix something we cant see.

Id imagine its another js error or similar interfering, but cant tell without replication.
