### ISSUE TITLE
工具条的按钮一大一小，很多人遇到这问题

### ISSUE THREAD

**Issue by izhijian** [wenzhixin/bootstrap-table#2549]
![qq 20160805114705](https://cloud.githubusercontent.com/assets/18110266/17425654/6e448c4e-5b02-11e6-9cae-4844f5fbbfa6.png)
如图，在HTML里面是正常的，很奇怪，弄到JSP里面就这样，一大一小了，有时候是正常的，有时候一大一小，问了很多人，也遇到过，不知道什么问题，看样式看不出来是什么原因，求解，谢谢

**Comment by netvempive** [comment]
试试这个<!DOCTYPE html>。。

**Comment by Xiahl1990** [comment]
协议不对，看下是不是h5模板

**Comment by dabros** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
楼上正解。
