### ISSUE TITLE
how to intergrate angular2?

### ISSUE THREAD

**Issue by xchz** [wenzhixin/bootstrap-table#2552]
how to use in angular2? can you give some examples? thanks.

**Comment by panxq5** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#integrate/angular

**Comment by Xiahl1990** [comment]
ng2?not ng1

**Comment by xchz** [comment]
yes, angular2

**Comment by jredd** [comment]
yeah ng2 would be awesome...
