### ISSUE TITLE
data-url attribut only with .json files?

### ISSUE THREAD

**Issue by PeterPlanlos** [wenzhixin/bootstrap-table#2554]
Hey all,
i dont know if its supported or whatever i do wrong but i cant get work the data-url attribut of the table with a http api json call.

when i open my api 
as example:
www.xyz.aaa/api/test  
i get a blank page with data in json format.

if i add this url as data-url the table tell me
"No matching records found"

if i copy all content from the http request and save it to a new file called test.json and put this file on my webserver and i call it in the data-url attribut to 
www.xyz.aaa/api/test.json 
it work!

i not changed anything on the json format i got! just saved this as a file.
on the web request (the page where i copied the json string) its 
its typ: application/json

so my question: can i get it to work without saving this to a file every time i call it? 
it should work "on the fly" with the url call or iam completly wrong?

i have to use these attributes:..(here complete table):

`<table data-toggle="table"
       data-url="www.xyz.aaa/api/test/"
       data-data-field="test"
       data-side-pagination="server"
       data-pagination="true">
	<thead>
    <tr>
        <th data-field="id">#</th>
		<th data-field="title">Title</th>
		<th data-field="body">Body</th>
    </tr>
    </thead>
</table>
`

my json output is like this:
OUTPUT:
{"test":[{"userid":"1","id":"1","title":"test","body":"test"}]}

i dont know what i should add here for files to resolve this.. if you need any let me know.

Thank You all!

**Comment by panxq5** [comment]
use responseHandler

add attribute data-response-handler="responseHandler"

in js:
`function responseHandler(res){
    return res.test
}`

**Comment by PeterPlanlos** [comment]
Thank you!
I hoped i can do it without js.
Many Browsers here has deactivated js for security reasons. In this case the table will be clear, or?

Anyway..Is there a way to generalize the js function?
Because the name "test" change every time i call another api

Is something like  
{return res.this}
Work?

Kind Regards

**Comment by dabros** [comment]
@PeterPlanlos 

The entire plugin is a JS plugin, so your comment about disabled js makes absolutely no sense as it doesnt matter whether you add any extra code of your own, the whole thing is a js plugin and needs it to run regardless.

In regards to generalising the code, wherever you getting that url from, thats already been done when you used `data-data-field`. That should handle this for you without needing `responseHandler`, so the table 'not working' was NOT a matter of that, its something else at fault

You need to debug your application, with and without `data-data-field` and `responseHandler`. 

Where to start first is:

1. Use F12 (console and network panel) to examine working example like http://issues.wenzhixin.net.cn/bootstrap-table/ and compare very carefully to your own (also using button in top right of example to see source code). If something looks off you can search for relevant options in github and [StackOverflow](http://stackoverflow.com/questions/tagged/bootstrap-table) and such, plenty of resources out there that will get you quicker and more thorough response than creating a potential duplicate question/issue.

2. If absolutely nothing jumps out at you, or something does and you want to investigate, then look at look at https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports and example fiddle for side, get that working then add in your data via echo, direct array, ect. and add any other steps one at a time till you either cant make it any closer (though remain focused on replicating core issue as simply as possible).

If using server side, you can use echo feature to mimic your exact data (as explained here, with official doco linked at top: http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery)

For example, I expect you might see error about undefined functions or similiar if you use `data-toggle` and arnt careful about scoping. If you see that, then use the js init approach as described in [getting started](http://bootstrap-table.wenzhixin.net.cn/getting-started/). Other errors should be obvious and easy to fix, search yourself before posting here for more help, its something you have setup wrong in your bootstrapTable so always refer to working examples if in doubt.

**Comment by PeterPlanlos** [comment]
@dabros thank you much.
its true the js thing. forget it its ok for me. users who want use the app has to enable js. 

i finally found out whats up & wrong.
i try to describe it here since i didnt found a solution and on the example:
http://issues.wenzhixin.net.cn/bootstrap-table/
it has same behavior whats wrong on my api call.

i will try to describe it on the above example since its easier to understand what i mean i think:
Example:
http://issues.wenzhixin.net.cn/bootstrap-table/
it calls the api (on sourcecode):
data-url="/examples/bootstrap_table/data"
finally on the delivered website it calls
"http://issues.wenzhixin.net.cn/examples/bootstrap_table/data?order=asc&offset=0&limit=10"

my question:
what the hell is 
?order=asc&offset=0&limit=10
with the attribut
data-pagination="false"
i finally can remove the 
&offset=0&limit=10
but i end up with 
"?order=asc" and my api dontz support it it simply get a empty json back... 
i not relize that it adds something to the url api call. 
i can manage to get data-sort-order="desc" by set attribut 
data-sort-order="desc"
i end up with 
"?order="
when i try data-sort-order=""
when i dont set the data-sort-order attribut i end up with data-sort-order="asc" in the url api call ..

really maybe iam to stupid to remove this but i dont found any solution , iam sorry to consume your time bro.
but at least i wonder that all your APIs support these suffixes like  "?order=asc&offset=0&limit=10" ?!

thank you very much! at least i know its not a api error just a wrong call! thanks

**Comment by dabros** [comment]
@PeterPlanlos 

That is param passed through, everything after ? is a query parameter, just google and research that, it is NOT the url

Its not clear what this 'wrong call' causes for you as query parameters do NOTHING unless you want them to.

You need to take a step back and get a basic working example going, use a fiddle or whatever if need be, then step in with your own api, seeing what the difference is. Do basic research on individual steps, you absolutely have over a dozen great working examples where you have full access to data sources (json files and data sources) and fully functioning code, make use of them.

http://issues.wenzhixin.net.cn/bootstrap-table/#options/client-side-pagination.html

http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html

**Comment by PeterPlanlos** [comment]
thanks @dabros 
i had woking examples like i said on first post: if i save this as json and call the json file in the url attribut its fine.
on the example
http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html
its same behavior
the url attribut in the source code:
data-url="/examples/bootstrap_table/data"

the example call
GET http://issues.wenzhixin.net.cn/examples/bootstrap_table/data?order=asc&offset=0&limit=10

behind data
?order=asc&offset=0&limit=10
for my api its a wrong syntax thats all and simply it will send a empty json back. =( 
i can remove the offset=0&limit=10 when i set the attribut
data-pagination="false" or dont set the attribut but for a reason i cant remove this ?order=asc
or better i dont know how. in any examples it seems turned on, by default. and its simply break my api call.

hope you understand what i mean.

**Comment by dabros** [comment]
@PeterPlanlos 

Thanks for the clarification, but just look back at what I said, that '?' and everything following it is a query string. 

If you researched query string you would have seen that it only applies to GET requests.

So change the `data-method` from its default of "get" to "post". There are definitely other ways to affect the query parameters, but since you seem to just want them ignored then dont use a GET request.

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by PeterPlanlos** [comment]
@dabros 
thank you
i saw its only applied to GET request but simply its a GET Request i want to perform.
my api want another input on POST since my api can write and read and it want write on a post request.
it simply should not affect the data URL with something like a query parameter if not wanted.
its no other way for me to save every request in a json file and display this json file because of the query parameter.. i hate it :(

**Comment by dabros** [comment]
@PeterPlanlos

Your question was how to remove the entire `?` query string, if you dont specify your requirements, your environment or what you have already looked at then we cant help you. And as i already said, there is more than one way to handle the query string param.

Right below that option `method` in the doco i already pointed you to, there is a VERY obvious option called `queryParams`

`data-query-params="testFunction"`
`function testFunction(){return [];}`

Running those seems to stop it sending any query params, the reason is obvious if you read the doco.

Before declaring what is wrong with the world do actually research with official documentation, especially if someone has already pointed you directly towards it.

**Comment by PeterPlanlos** [comment]
For all who has the same problem, this will remove completly the query parameters.

HTML Attribute:

data-query-params="queryParams"

JS:

function queryParams() {
    return {
    };
