### ISSUE TITLE
Pagination display problem

### ISSUE THREAD

**Issue by RoyH** [wenzhixin/bootstrap-table#2555]
I have encountered a display problem with the pagination toolbar,  Image here ->
![pagination broken](https://cloud.githubusercontent.com/assets/3510331/17485687/4825ccf4-5d86-11e6-8db2-32d36ca1672c.png)

I am using bootstrap v4 and chrome, if you need any other details please ask!
Thank you in advance for your help!

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

For us to help you, we absolutely need this issue to be replicated in a fiddle where we can see it and test fixes or workarounds.

**Comment by RoyH** [comment]
Unfortunately I have tried to replicate the issue on jsfiddle with bootstrap v4 and I have been unable to. Copied and pasted my code straight whilst loading in sample data like the example that was linked. 

However when running the pagination examples on my own development environment I encounter the same problem. Functionally it works perfectly fine however the buttons for the pagination seems to have been replaced with a black dot (as shown in the previous photo). 

Does anyone have any hints on where to start even looking? It seems to only occur in my environment. 
Ruby on rails, Bootstrap v4, Font awesome icons

**Comment by dabros** [comment]
Check your dev tools, F12 https://developers.google.com/web/tools/chrome-devtools/?hl=en

All major browsers have their own versions of this, Check the network panel for errors loading resources, console panel for almost any other error, and 'inspect' the pagination elements to see the css that are ACTUALLY being applied (compare it to examples)

All it sounds like is css styles not being applied because of missing resource or more likely a style/css conflict, though malconfigured html can be at fault if script has errors due to something else on your page

**Comment by RoyH** [comment]
Just an update, I have isolated the problem! The problem is the difference between bootstrap 3 and bootstrap 4 and how the pagination function is called. Is it possible in a future update to address this?

**Comment by dabros** [comment]
@RoyH - any further clarification would be appreciated

@wenzhixin @djhvscf - ill pass this over to you and/or anyone else who wants to take a look at this

**Comment by wenzhixin** [comment]
http://bootstrap-table-examples.wenzhixin.net.cn/#options/v4.html
