### ISSUE TITLE
Translate error in bootstrap-table-it-IT.js

### ISSUE THREAD

**Issue by Francesko90** [wenzhixin/bootstrap-table#2558]
Wrong translate in line 24

**pageFrom** and **pageTo** not contains page number but contains record number:
- **pageFrom**:  number of first record show in table page
- **pageTo**: number of last record show in table page

The correct translate is

```
 'Record mostrati da ' + pageFrom + ' a ' + pageTo
                    + ' (Numero totale di record: ' + totalRows + ')';
```

**Comment by dabros** [comment]
@Francesko90 

PR always welcome :)

You can edit it direct in github, then just click 'commit' and 'make PR' (ensure you are editing the 'develop' branch though, not 'master'.

https://github.com/wenzhixin/bootstrap-table/blob/develop/src/locale/bootstrap-table-it-IT.js

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

**Comment by Francesko90** [comment]
Hi @dabros 

I had create a pull request and build is passed https://travis-ci.org/wenzhixin/bootstrap-table/builds/151184673
