### ISSUE TITLE
Is bootstrrap-table has ztree's solution

### ISSUE THREAD

**Issue by SoulFlys** [wenzhixin/bootstrap-table#2559]
bootstrap-table有树结构（比如ztree、jstree）的解决方案吗

**Comment by SoulFlys** [comment]
![1jg8ndt gwgno56x2u6_ebw](https://cloud.githubusercontent.com/assets/12166401/17549498/11fa1da8-5f23-11e6-82c1-a4aae2836341.png)

**Comment by SoulFlys** [comment]
like this

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/#extensions/tree-column.html
https://examples.bootstrap-table.com/#extensions/treegrid.html
