### ISSUE TITLE
How to place the Expand button on the right and not on the left side

### ISSUE THREAD

**Issue by povolev** [wenzhixin/bootstrap-table#2562]
Need help I use the expand detail button and everything is working as expected is it possible to place it on the right side of the table instead of the left side by default?

**Comment by dabros** [comment]
@povolev 

I would be dubious of cloning or other operations to shift generated html column, as that would risk losing handlers, but there are obvious solutions. You can hide that column via any means (simple jquery or css to affect `tr td:first-of-type` and `tr th:first-of-type`, or any other means, i know this been answered before here and elsewhere, just search for it)

Then add whatever UI you want in the column to the right and place a handler on it that calls to `expandRow`, the param `index` can be retrieved via something as simple as `$(this).parent('tr').data('index')` or similar code, its printed in each TR so simple jquery can get that for you.

The other option for the handler is the `onClickCell` event, which would allow you to determine if that `field` matches a desired action, and that action/code can access the `index` via the `element`. 

You would ofcourse either check for existence of sibling `tr.detail-view` via simple jquery (check if next TR has that class) or the class of the detail icon, or some other condition you can easily place yourself on that TR as a toggle (such as 'expanded' class). That would let you easily know whether to `expandRow` or `collapseRow`.

http://bootstrap-table.wenzhixin.net.cn/documentation/#methods
http://bootstrap-table.wenzhixin.net.cn/documentation/#events

**Comment by povolev** [comment]
Thank you very much
