### ISSUE TITLE
the demo with group-by or group-by-v2

### ISSUE THREAD

**Issue by SoulFlys** [wenzhixin/bootstrap-table#2565]
@djhvscf  Can you provide the demo group-by  #or group-by-v2 ? thanks

**Comment by Litalrok** [comment]
Join to this request! :+1: +1:

**Comment by djhvscf** [comment]
Example of **Group-by** http://jsfiddle.net/djhvscf/e3nk137y/2258/
Example of **Group-by-v2**  http://jsfiddle.net/Knoxvillekm/byv2pk24/

**Comment by claudneto** [comment]
Is it possible to have a multiple level table grouped, using jquery.treetable plugin?
