### ISSUE TITLE
怎么弄出一个树形表格，看了groupBy插件，不符合标准的树表，不满足需求

### ISSUE THREAD

**Issue by izhijian** [wenzhixin/bootstrap-table#2567]
![qq 20160812103637](https://cloud.githubusercontent.com/assets/18110266/17611307/c27e66e2-6078-11e6-80a0-8590060b36ff.png)

**Comment by dabros** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/tree-column.html
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/treegrid.html
