### ISSUE TITLE
ajax

### ISSUE THREAD

**Issue by liyang1987jay** [wenzhixin/bootstrap-table#2568]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).
如果通过ajax 我的ajax是跨域的 怎么赋值给total 跟rows
define(function() {
    var User = {
        userList: function() {
            var that = this;
            $.ajax({
                type: "get",
                url: URL.getUserListUrl,
                data: null,
                dataType: C.DATA_TYPE,
                //跨域请求
                xhrFields: {
                    withCredentials: true
                },
                success: function(result) {
                    $('#usertable').bootstrapTable({
                        data: result.rows,
                        locales:'zh-CN',
                        toolbar: '#toolbar', //工具按钮用哪个容器
                        striped: true, //是否显示行间隔色
                        cache: false, //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（_）
                        pagination: true, //是否显示分页（_）
                        sortable: true, //是否启用排序
                        sortOrder: "asc", //排序方式
                        queryParams: that.queryParams, //传递参数（_）
                        queryParamsType: "limit",
                        sidePagination: "server", //分页方式：client客户端分页，server服务端分页（_）
                        pageNumber: 1, //初始化加载第一页，默认第一页
                        pageSize: 10, //每页的记录行数（_）
                        pageList: [10, 25, 50, 100], //可供选择的每页的行数（_）
                        search: true, //是否显示表格搜索，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
                        strictSearch: true,
                        showColumns: true, //是否显示所有的列
                        showRefresh: true, //是否显示刷新按钮
                        minimumCountColumns: 2, //最少允许的列数
                        clickToSelect: true, //是否启用点击选中行
                        height: 700, //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
                        uniqueId: "sys_user_id", //每一行的唯一标识，一般为主键列
                        showToggle: true, //是否显示详细视图和列表视图的切换按钮
                        cardView: false, //是否显示详细视图
                        detailView: false, //是否显示父子表
                        showLoading:true,
                        //sidePagination: "server", //服务端处理分页
                        columns: [{
                            checkbox: true
                        }, {
                            field: 'sys_user_id',
                            title: '用户ID',
                            sortable: true,
                        }, {
                            field: 'sys_user_login_name',
                            title: '登录名称',
                        }, {
                            field: 'sys_user_state',
                            title: '用户状态',
                        }]
                    })
                },
                error: function() {
                    console.log("服务端无响应");
                }
            });
        },

```
    queryParams: function(params) {
        var temp = { //这里的键的名字和控制器的变量名必须一致，这边改动，控制器也需要改成一样的
            limit: params.limit, //页面大小
            offset: params.offset, //页码
        };
        return temp;
    }
};

require(['jquery', "config", "functions", "bootstrap", 'bootstrap-table', 'bootstrap-table-local'], function($, C, D) {
    $(function() {
        var act = D.get('act');
        switch (act) {
            case "userList":
                User.userList();
                break;
        }
    })
});
```

});

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

**Comment by liyang1987jay** [comment]
Hi~,this is the link http://jsfiddle.net/52_rabbit/u0980Lqc/6/

**Comment by dabros** [comment]
@liyang1987jay - you made quite a few errors that would have immediately obvious if you researched and compared to the many working examples here and any of the numerous tutorials and help resources for the jquery $.ajax function

I summarised some, and also there is absolutely no logical reason you should be using the $.ajax then js init in a seperate function like that, and WHY 'server-side' pagination if you not using a url, and why `data-toggle` if you using `js init`

Find a working example of what you want then go from there, and just use the `data-url` option to avoid any messy outside $.ajax code

**Comment by liyang1987jay** [comment]
@dabros define(function() {
	var User = {
		userList: function() {
			var that = this;
			$('#usertable').bootstrapTable({
				locales: 'zh-CN',
				toolbar: '#toolbar', //工具按钮用哪个容器
				striped: true, //是否显示行间隔色
				pagination: true, //是否显示分页（*）
				sortable: true, //是否启用排序
				sortOrder: "asc", //排序方式
				queryParams: that.queryParams, //传递参数（*）
				queryParamsType: "limit",
				sidePagination: "client", //分页方式：client客户端分页，server服务端分页（*）
				pageNumber: 1, //初始化加载第一页，默认第一页
				strictSearch: true,
				showColumns: true, //是否显示所有的列
				showRefresh: true, //是否显示刷新按钮
				minimumCountColumns: 2, //最少允许的列数
				uniqueId: "sys_user_id", //每一行的唯一标识，一般为主键列
				showLoading: true,
				ajax: function(params) {
					$.ajax({
							url: URL.getUserListUrl,
							type: 'GET',
							dataType: 'json',
							//跨域请求
							xhrFields: {
								withCredentials: true
							},
						})
						.done(function(result) {
							 params.success(result.rows);
						})
						.fail(function() {
							console.log("error");
						})
						.always(function() {
							console.log("complete");
						});

				},
				columns: [{
					checkbox: true
				}, {
					field: 'sys_user_id',
					title: '用户ID',
					sortable: true,
				}, {
					field: 'sys_user_login_name',
					title: '登录名称',
				}, {
					field: 'sys_user_state',
					title: '用户状态',
				}]
			})
		},

		queryParams: function(params) {
			var temp = { //这里的键的名字和控制器的变量名必须一致，这边改动，控制器也需要改成一样的
				limit: params.limit, //页面大小
				offset: params.offset, //页码
			};
			return temp;
		}
	};

	require(['jquery', "config", "functions", "bootstrap", 'bootstrap-table', 'bootstrap-table-local'], function($, C, D) {
		$(function() {
			var act = D.get('act');
			switch (act) {
				case "userList":
					User.userList();
					break;
			}
		})
	});
});
我现在改成这样了，但是total怎么赋值呢

**Comment by liyang1987jay** [comment]
@dabros 还有那个queryParams没有传啊

**Comment by dabros** [comment]
@liyang1987jay - your not helping anyone with your last 2 posts

I did realise the fiddle link got removed from last post somehow, my bad, here it is again

http://jsfiddle.net/dabros/era7tncp/

Look at that and my previous posts, spamming code without explanation or even proper formatting does nothing to help anyone.
