### ISSUE TITLE
Unwanted characters in search/filter box

### ISSUE THREAD

**Issue by aploessl** [wenzhixin/bootstrap-table#2569]
I set up the bootstrap table to retrieve data from JSON source, and it is working, but a thing I've noticed that when I had the filter/search functionality, the box for search entry is showing some characters (Chinese?) that have nothing to do with the data source. (See attached screenshot).
![2016-08-12_18-11-50](https://cloud.githubusercontent.com/assets/1882882/17639499/746eb174-60b8-11e6-867b-41408b6425ba.png)
![2016-08-12_18-12-11](https://cloud.githubusercontent.com/assets/1882882/17639502/7ae33782-60b8-11e6-9e9f-6f65f044a698.png)

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

**Comment by aploessl** [comment]
Resolved for this most part, the data-locale needed to be specified. I scanned through the source and saw and abundance of Asian characters in the implementation, so I am assuming that's the origin. 
No fiddle is needed, just create a table with an ajax pull and search without locale specified and I'm sure you'll see what I saw..

**Comment by dabros** [comment]
@aploessl - if you need more help then we do need a fiddle. For example, i havent worked web dev more than passingly for a year now and have no environment open to me, and even if i did, this is entirely volunteer based, so for that and accuracy reasons its on the questioner to produce a fiddle that not only replicates the issue but in same step allows a shared code base for possible solutions.

**Comment by aploessl** [comment]
Why would I need a fiddle when I explained in prior post the characters exist in the source code? One would think that it would be more efficient to keep the locales external and to add on an as needed basis and have english/latin/iso characters as default. I explained that the locale was the element which corrected what I was having trouble with. Anyone familiar with the plugin I guess would conceptually understand that if you create a table that's fed via ajax and do not set the locale, then you may encounter these characters because I assume that the default is Chinese? I don't really think a fiddle is required to read the source. It's not really practical to rewrite something to accommodate a site (fiddle) that would require major alterations to the code and would not be an exact replication of what I'm working with. If I could dump my source in there and get it to behave as it did on my servers, I would, but I can't because fiddle would require me to code differently.

**Comment by navneetnivu07** [comment]
You can remove the zh-TW locale file to solve your problem.
