### ISSUE TITLE
ajax

### ISSUE THREAD

**Issue by liyang1987jay** [wenzhixin/bootstrap-table#2572]
define(function() {
    var User = {
        userList: function() {
            var that = this;
            $('#usertable').bootstrapTable({
                locales: 'zh-CN',
                toolbar: '#toolbar', //工具按钮用哪个容器
                striped: true, //是否显示行间隔色
                pagination: true, //是否显示分页（_）
                sortable: true, //是否启用排序
                sortOrder: "asc", //排序方式
                queryParams:function(params) {
                    var query = {
                        page: params.offset / params.limit + 1,
                        pageSize: params.limit,
                    };
                    return query;
                },
                queryParamsType: "limit",
                sidePagination: "client", //分页方式：client客户端分页，server服务端分页（_）
                pageNumber: 1, //初始化加载第一页，默认第一页
                strictSearch: true,
                showColumns: true, //是否显示所有的列
                showRefresh: true, //是否显示刷新按钮
                minimumCountColumns: 2, //最少允许的列数
                uniqueId: "sys_user_id", //每一行的唯一标识，一般为主键列
                showLoading: true,
                ajax: function(request) {
                    console.log(request);
                    $.ajax({
                            url: URL.getUserListUrl,
                            type: 'GET',
                            dataType: 'json',
                            data:request.data,
                            //跨域请求
                            xhrFields: {
                                withCredentials: true
                            },
                        })
                        .done(function(result) {
                            request.success(result.rows);
                            request.success(result.total);
                        })
                        .fail(function() {
                            console.log("error");
                        })
                        .always(function() {
                            console.log("complete");
                        });

```
            },
            columns: [{
                checkbox: true
            }, {
                field: 'sys_user_id',
                title: '用户ID',
                sortable: true,
            }, {
                field: 'sys_user_login_name',
                title: '登录名称',
            }, {
                field: 'sys_user_state',
                title: '用户状态',
            }]
        })
    },

    queryParams: function(params) {
        var temp = { //这里的键的名字和控制器的变量名必须一致，这边改动，控制器也需要改成一样的
            limit: params.limit, //页面大小
            offset: params.offset, //页码
        };
        return temp;
    }
};

require(['jquery', "config", "functions", "bootstrap", 'bootstrap-table', 'bootstrap-table-local'], function($, C, D) {
    $(function() {
        var act = D.get('act');
        switch (act) {
            case "userList":
                User.userList();
                break;
        }
    })
});
```

});
我的返回值是{"total":16,"rows":[{"sys_user_state":"正常","sys_user_id":1,"sys_user_login_name":"super"},{"sys_user_state":"正常","sys_user_id":2,"sys_user_login_name":"zhang"},{"sys_user_state":"正常","sys_user_phone":"13864039387","sys_user_id":7,"sys_user_login_name":"admin1","sys_user_name":"李四","sys_user_email":"sdsf@qq.com"},{"sys_user_state":"正常","sys_user_id":8,"sys_user_login_name":"admin"},{"sys_user_state":"正常","sys_user_id":9,"sys_user_login_name":"ddd"},{"sys_user_state":"禁用","sys_user_id":11,"sys_user_login_name":"as"},{"sys_user_state":"禁用","sys_user_id":12,"sys_user_login_name":"aed"},{"sys_user_state":"禁用","sys_user_id":13,"sys_user_login_name":"esdf"},{"sys_user_state":"禁用","sys_user_id":14,"sys_user_login_name":"ead"},{"sys_user_state":"禁用","sys_user_id":15,"sys_user_login_name":"adf"}]}
total如何赋值呢
![qq 20160812184638](https://cloud.githubusercontent.com/assets/4651483/17660676/40b95bb6-630d-11e6-8b69-239e0ecd293c.png)
现在是这样的，没有总记录数

**Comment by liyang1987jay** [comment]
ajax: function(params) {
					console.log(params);
					$.ajax({
							url: URL.getUserListUrl,
							type: 'GET',
							dataType: 'json',
							data: params.data,
							//跨域请求
							xhrFields: {
								withCredentials: true
							},
						})
						.done(function(result) {
							params.success({
								total: result.total, //伪造的条数
								rows:result.rows
							});
						})
						.fail(function() {
							console.log("error");
						})
						.always(function() {
							console.log("complete");
						});

				},
params.success({
								total: result.total, 
								rows:result.rows
							});
这样写不行吗？我看别人是这样写的啊 @

**Comment by dabros** [comment]
@liyang1987jay - please stop making issues with duplicate titles and just pasting code and no real description of environment, current output vs desired output, previous research and failed attempts, ect.

And, again:

Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765
