### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by sbecerikli** [wenzhixin/bootstrap-table#2573]
Hello,
I am using your table example. And I have an issue.
I am taking data from mysql and turn it Json object for table. but when I use search box it does not work. If there any special things to do could you help me?

Thanks a lot..

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

**Comment by PeterPlanlos** [comment]
i want join this party here. :)
do you use 
data-side-pagination="client"
or
data-side-pagination="server"

client is deafult.

**Comment by gulshanasrani** [comment]
Hi,

i am getting below error (check attached screenshot).

![bootstrap-table-error](https://cloud.githubusercontent.com/assets/25425823/22412367/c08324f4-e6d3-11e6-9802-a65fd87b3fbd.PNG)
