### ISSUE TITLE
请问怎么设置固定列宽

### ISSUE THREAD

**Issue by jackboywu** [wenzhixin/bootstrap-table#2574]
wenzhixin，你好：
          我想请问一个问题，我在使用bootstrap-table时，有时列会比较多，这时表格就会变动行高，请问我要怎么设置固定行高在比较多列时显示左右滚动条呢？谢谢！

**Comment by dabros** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
#1608 Width problem: http://jsfiddle.net/wenyi/8jL67Lcx/11/
