### ISSUE TITLE
struggling with data-side-pagination="client"

### ISSUE THREAD

**Issue by PeterPlanlos** [wenzhixin/bootstrap-table#2575]
Hello,

how can i use `data-side-pagination="client"`
with this JSON Response:
```
{
"example_1":
[
{"id":‌​"1","nr":"1","code":"‌​0107SOC"},
{"id":"2","‌​nr":"2","code":"0108A‌​HD"}
]
}
```
i had tryed with 
`data-data-field="example_1" `
without success. is it possible or does i need transform this json?
if i need trsnaform it with JS would very greatful if someone could help me with that.

Thank you all!

**Comment by dabros** [comment]
@PeterPlanlos 

http://issues.wenzhixin.net.cn/bootstrap-table/index.html

http://bootstrap-table.wenzhixin.net.cn/examples/

If the examples doesnt state `data-side-pagination="server"` (or `options.sidePagination="server"`) then its client side, so look at any of those dozens of fully working examples.

You can use the fiddles to play with code, but also remember your dev tools, F12 https://developers.google.com/web/tools/chrome-devtools/?hl=en

All major browsers have their own versions of this, Check the network panel for errors loading resources, console panel for almost any other error, and 'inspect' any generated html

**Comment by PeterPlanlos** [comment]
Solution for the Example 
HTML Attribute:
```
data-response-handler="responseHandler"
data-side-pagination="client"
```


JS:
```
function responseHandler(res) { 
	
	return res.example_1
}
```

@wenzhixin Can you Close this please?

**Comment by dabros** [comment]
@PeterPlanlos - thanks for sharing solution, since you created issue you can close it yourself, should a button somewhere at top or bottom of page
