### ISSUE TITLE
add class to inputs

### ISSUE THREAD

**Issue by Syed-Ali** [wenzhixin/bootstrap-table#2577]
hello, first of all thank you. is there any way to set class to inputs? Like i want to set bootstrap "input-sm" class to input and select. thanks in advance.

**Comment by Syed-Ali** [comment]
in filter control extension.

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

That way we have something to show our suggestions with and test it on

**Comment by Syed-Ali** [comment]
hope below screen shot will help to understand.
# SNAP of code::
`var stickyHeaderOffset = $('.navbar-fixed-top').outerHeight() ;
apptable.bootstrapTable ({
	columns: [{"field":"id","title":"Id"},{"field":"evt","title":"Event"},{"field":"st","title":"Search Text","visible":false}],

	url: /some/url,
	cache: false,
	classes: 'table table-condensed table-striped table-hover',
	pagination: true,
	paginationLoop: true,
	pageSize: 10,
	pageList: [10, 25, 50, 100, 'ALL'],
	search: true,
	minimumCountColumns: 2,
	paginationVAlign: 'top',
	idField: 'id',
	uniqueId: 'id',
	cookie: true,
	cookieIdTable: 'sysavl',
	stickyHeader: true,
	stickyHeaderOffsetY: stickyHeaderOffset + 'px',
	filterControl: true,
	filterShowClear: true,
	iconSize: 'sm',
	buttonsClass: 'primary',
	detailView: true,
	showExport: true,
	toolbar: '#toolbar',
	responseHandler: function(res) {
		if (res.hasOwnProperty('err')) {
			var form_result_div = '#alert-body';
			$(form_result_div).removeClass().addClass('alert alert-danger').html(res.err).fadeIn('slow');
			setTimeout(function(){ $(form_result_div).fadeOut('slow') }, 3000);
			return [];
		} else {
			return res;
		}
	},
	detailFormatter: function(index, row) {
	},
	queryParams: function() {
		return $.extend(arguments[0], {
			filters: { "cat": $("#category").val() || [""], "date": start_date}
		});
	},
});

`



![image](https://cloud.githubusercontent.com/assets/14012898/18052488/f4fd8532-6dfa-11e6-9e0b-611abd1bff77.png)

**Comment by villainoustourist** [comment]
I agree, it would be great to add search classes the same way the existing "data-classes" work, but apply to the search input box.  Right now I'm finding the input box via javascript and adding classes, but it would be nice to have it a bit cleaner.

**Comment by wenzhixin** [comment]
The latest version supports this feature.

**Comment by marceloverdijk** [comment]
@wenzhixin I wanted to add a class to search input , but could not find a `data-*` class for it.
So I wondered in what manner this is supported.

Note, I found a way to do this with, but I'm not sure this is the supposed way to do it...

```
$.BootstrapTable = class extends $.BootstrapTable {
  initConstants () {
    super.initConstants()
    this.constants.classes.input = 'form-control form-control-light'
  }
}
```
