### ISSUE TITLE
Reorder columns programatically

### ISSUE THREAD

**Issue by Charles128** [wenzhixin/bootstrap-table#2578]
Hello. I've set up my table and have been using the column reordering extension so users can move columns by dragging and dropping. What I would like to do is reorder columns programmatically. I'm not seeing any way to do this in the documentation so has anyone had this use case and come up with a solution? I've been trying to use jquery to do it but haven't found a reliable way to consistently and continuously manipulate the column orders. Would I need to rerender the table each time to do this? Thanks.

**Comment by dabros** [comment]
@Charles128 

Please clarify more on your use case. "reorder programattically" says nothing of conditions or exact expected output.

Notably:

1. What action does user take to trigger this?
A. do you want some user action/button to set the column order to some predefined arrangement?
B. OR do you want to just provide some alternate UI (like buttons) vs the drag+drop
C. OR some other UI flow, if so please elaborate

2. How often is this triggered? Clarify first question to be clear the scenerio where this is required

3. Does this need to reapply sorting, searches, pagination, ect? Be specific in what conditions absolutely MUST be carried across, and what condition IDEALLY would be carried across. This is very dependent too on the trigger conditions.


Those are questions that if answered well should help decide exact approach. 

Some ideas for implementation dont actually impact reorder-rows at all, for example if predefined and can be safely coupled with reload of data then just `refreshOptions` with columns override, possibly storing some key variables (pagination, search, ect) to re-apply if those are not kept automatically.

If it is some other scenerio, then possibly just look at how code code and other extensions expose functionality and mimic that in a [PR ](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests) in the re-order rows extension.
