### ISSUE TITLE
标题栏单元格合并线条消失问题

### ISSUE THREAD

**Issue by aron10** [wenzhixin/bootstrap-table#2579]
测试发现在IE 11/edge,Firefox 会出现此问题；chrome 无此问题
![image](https://cloud.githubusercontent.com/assets/7115978/17759305/b2408ba2-6528-11e6-8d6d-4e9e3a73326d.png)

**Comment by dabros** [comment]
@wenzhixin

**Comment by streamone** [comment]
我也有同样的问题

**Comment by lhqiang** [comment]
bootstrap-table.css的76行注释掉就可以。
![image](https://cloud.githubusercontent.com/assets/2876380/25571319/1d1514fa-2e61-11e7-85a9-ba93835b8c3c.png)

**Comment by wenzhixin** [comment]
该问题已在最新版本中修复
