### ISSUE TITLE
Add auto-complete functionality to search field

### ISSUE THREAD

**Issue by webtrix** [wenzhixin/bootstrap-table#258]
Hi,

It would be a nice improvement if the search field would also have an auto-complete feature.  The auto-completion would be done on columns that have the data-tag e.g. data-auto-complete="true".

Thanks!

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/extensions/#table-filter

or:

http://bootstrap-table.wenzhixin.net.cn/extensions/#table-filter-control
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filtercontrol.html
