### ISSUE TITLE
Search but no matching records found.

### ISSUE THREAD

**Issue by mcc108** [wenzhixin/bootstrap-table#2583]
http://issues.wenzhixin.net.cn/bootstrap-table/

search $ ， But no matching records found.
why? How to solve it?

**Comment by dabros** [comment]
@mcc108 - look at source for that example and the [doco](http://bootstrap-table.wenzhixin.net.cn/documentation/). You will see that the '$' comes from a column formatter, you can look at the `strictSearch` option (description in doco and many examples in issues) 

Look at formatters and strictSearch and other examples, trial it in your code to see if that fixes YOUR issue, if it doesnt then next step is to provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765
