### ISSUE TITLE
Reset page number to 1 while making server-side sort request

### ISSUE THREAD

**Issue by martinburch** [wenzhixin/bootstrap-table#2584]
1. The original options object specifies sortName and sortOrder
2. The user advances the pagination to page 2
3. The user sorts by a different column or order
4. The pagination remains on page 2

Desired behavior: return the user to page 1.

This is what happens when searching, because the number of pages can't be known. This is also a desirable behavior when sorting, because it's likely the user is making a new query of the table. It's confusing to end up in the middle of the table, and it's an extra step to change the pagination back to page 1.

I've tried this code:

```
$('#table').on('sort.bs.table', function () {
    $('#table').bootstrapTable('selectPage', 1);
});
```

http://jsfiddle.net/4r6g4cfu/398/ 

The above code creates two server-side calls but they both have the correct request for `offset=0`. The usual result is that the first OPTIONS request is cancelled by the browser before it can complete. It would be good to suppress this extraneous request.

Also, I would like to this to be a table or column option, perhaps named `resetPaginationOnSort`.

**Comment by dabros** [comment]
@martinburch - that fiddles shows as broken to me, request for data times out. If you can fix that ill take look at an idea I have for a workaround, and it could also be used by anyone to proof addition of that `resetPaginationOnSort` option before submitting [PR](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests)

**Comment by martinburch** [comment]
@dabros the fiddle is working properly for me. The remote request is to http://mikepenz.com/jsfiddle/?order=asc&offset=0&limit=5 which is used in the official bootstrap-table examples.

**Comment by dabros** [comment]
@martinburch 

Still shows no records, error msg in console for that data request

>>XMLHttpRequest cannot load http://mikepenz.com/jsfiddle/?order=asc&offset=0&limit=5. Response for preflight is invalid (redirect)

Thats because of https redirect, changing the url made it work for me, looking at it now. I suggest you use a jsfiddle account too so you can make minor changes like that then 'set as base' so not needing to update urls

**Comment by dabros** [comment]
@wenzhixin @djhvscf - feature request, fiddle (change data-url to 'https') shows simple workaround that does however have that 2nd data request, does seem sensible to have option that allows reversion to page 1 automatically as part of same operation/request

I dont have time to do much on this myself atm, can try to look into it next week but encourage anyone else to have a peek too.

**Comment by wenzhixin** [comment]
ref #2188
