### ISSUE TITLE
how can i goto a specified page

### ISSUE THREAD

**Issue by hanliang1990** [wenzhixin/bootstrap-table#2585]
how can i goto a specified page,is there any parameter can setting?

**Comment by dabros** [comment]
@hanliang1990 - `selectPage`, `nextPage`, ect

http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

Look at doco and examples of that or other methods, they all called pretty much the same way so just mimic that with `selectPage` and proper timing (in custom button handler or whatever)

**Comment by hanliang1990** [comment]
what i mean is not call the method,on the page i can goto a specified page,not click next,next...

**Comment by martinburch** [comment]
You could make a custom toolbar with an input field to type the page number wanted:

https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/custom-toolbar.html
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

I don't think this is page-setting toolbar is a feature built into bootstrap-table. It doesn't make sense for many tables -- how would you know exactly which page you wanted to go to?

**Comment by wenzhixin** [comment]
Example: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/selectPage-prevPage-nextPage.html

**Comment by hanliang1990** [comment]
thank you for reply.
