### ISSUE TITLE
Remove diacritics from search

### ISSUE THREAD

**Issue by ramons03** [wenzhixin/bootstrap-table#2591]
Hi.
Please implement diacritics support for search.

This is implemented by selct2:
https://select2.github.io/examples.html#diacritics

Let me know if you want me to work on this or if it is already implemented in newer versions.

Thanks.
Regards.

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/#extensions/accent-neutralise.html
https://bootstrap-table.com/docs/extensions/accent-neutralise/
