### ISSUE TITLE
filter by date range

### ISSUE THREAD

**Issue by povolev** [wenzhixin/bootstrap-table#2592]
##Hi,

I need help that I spent so much time on that.
I have a table that one of the columns is date and there is an option to type a date-range and I would like to create a custom filter but the issue that I don't want to loose my original data in table and I don't want to loose also the the other filter that already exist

that what I tried , I tried to do onSearch
`onColumnSearch: function (column, valueSearched) {
                if(column == "date1" || column == "date2") {
                   var data = $('#table').bootstrapTable('getData');
                   var date1 = valueSearched.split("-")[1];
                   var date2 = valueSearched.split("-")[2];
                    $table.bootstrapTable('load', $.grep(data, function (row) {       
                    }));
                }
}`

I dont know what to do inside load and after load on my data gone 

I saw this example
http://jsfiddle.net/e3nk137y/1010/

**Comment by povolev** [comment]
someone can help me please?

**Comment by Falseee** [comment]
Your provided/linked jsfiddle loads only the filtered data.
You can use the [filterBy](https://bootstrap-table.com/docs/api/methods/#filterby) function in the next version (https://github.com/wenzhixin/bootstrap-table/pull/4230).
