### ISSUE TITLE
delete row by field which value type is numeric string failed.

### ISSUE THREAD

**Issue by leemem** [wenzhixin/bootstrap-table#2594]
I want to delete a row by field which value type is numeric string, when i pass the prameter with numeric string, it can't be deleted. the prameter must to be convert to integer. then the row can be deleted.

**Comment by holmes2136** [comment]
Could you provide your sample code

**Comment by leemem** [comment]
@holmes2136 I think i found where is the problem.
The data i get from server is like this:
`{
	"rows":[
		{"no":20160809256,"company_name":"test","contact":"Arvin","isavailable":1},
		{"no":20160810276,"company_name":"foo","contact":"Joy","isavailable":1}
	],
	"total":2
}`
the "no" field value isn't string
so , when i delete row :
`$table.bootstrapTable("remove",{"field":"no","values":['20160810276']});`

it can't be delete.

**Comment by wenzhixin** [comment]
Need to use the same type.
