### ISSUE TITLE
使用$table.bootstrapTable('append', ); 后的数据 用$table.bootstrapTable('remove', );有问题

### ISSUE THREAD

**Issue by lovezhl456** [wenzhixin/bootstrap-table#2596]
使用$table.bootstrapTable('append', );   加载数据到table  
再使用$table.bootstrapTable('remove', );   删除数据 有问题  先删除第一个后  后面的删除不了  
 'click .remove': function (e, value, row, index) {
       			console.log(row)
            $table.bootstrapTable('remove', {
                field: 'id',
                values: [row.id]
            });
        }’
这里的 row  获取的是已删除的行内容

**Comment by fightingm** [comment]
你好，我也遇到了这个问题，你是怎么解决的呢？
