### ISSUE TITLE
data tables are populating where is examples folder in project for page welcome.html at line data-url="/examples/bootstrap_table/data"

### ISSUE THREAD

**Issue by AjayTakur** [wenzhixin/bootstrap-table#2597]
I did try to replicate the same functionality by just downloading source code from github.I run the index.html page i got empty white screen under Delete button.

OS-Windows 10 Home -64 bit architecture
I3 core processor,Latest Firefox browser & Google Chrome

1)Download source code from top right corner [http://issues.wenzhixin.net.cn/bootstrap-table/](url) 2)Extract and run the index.html page
3)I see Blank white screen right under Delete button  [
![image](https://cloud.githubusercontent.com/assets/4033929/18034103/3adbff92-6d52-11e6-82ed-147f01cac74c.png)
](url)

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/app.js

https://github.com/wenzhixin/bootstrap-table-examples/blob/master/examples.js

run `node app`

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/
