### ISSUE TITLE
Is it possible to automatically locate modified rows

### ISSUE THREAD

**Issue by Apexblade** [wenzhixin/bootstrap-table#2598]
Is it possible to automatically locate modified rows while using bootstrap-table and editable extension?
If it is possible,how?

**Comment by Falseee** [comment]
If you mean to filter/show the edited Rows:
Update the Row with the function [updateRow](https://bootstrap-table.com/docs/api/methods/#updaterow) while the [onEditableSave](https://bootstrap-table.com/docs/extensions/editable/#oneditablesaveeditable-savebstable) is triggered.
Then filter the Rows with [filterBy](https://bootstrap-table.com/docs/api/methods/#filterby)
