### ISSUE TITLE
How to add a custom column

### ISSUE THREAD

**Issue by KayTokyo** [wenzhixin/bootstrap-table#2599]
Hi,

How do i add a custom column called "Edit" and "View" with just a button

```
<a href="{{route('event.show', $event->token)}}" target="_blank"
                                       class="btn btn-slim btn-success">View</a>
```

Then i want to pass in the ID or another variable of the row were on to link to another page.

**Comment by lovezhl456** [comment]
**like it**

<th data-field="operate" data-formatter="operateFormatter" data-events="operateEvents">OP</th>


function operateFormatter(value, row, index) {
        return [
        '<a class=\"edit ml10\" href=\"javascript:void(0)\" title=\"Edit\">',
            '<i class=\"glyphicon glyphicon-edit\"></i>',
        '</a>',
        '<a class=\"remove ml10\" href=\"javascript:void(0)\" title=\"Remove\">',
            '<i class=\"glyphicon glyphicon-remove\"></i>',
        '</a>'
        ].join('');
    }

    window.operateEvents = {
    'click .edit': function (e, value, row, index) {
    },
    'click .remove': function (e, value, row, index) {
        }
    }
    };

**Comment by mahenrique94** [comment]
I'm with the same issue

**Comment by Falseee** [comment]
Possible with formatter and window.operateEvents (see the contribution from @lovezhl456).
