### ISSUE TITLE
filter-control (boolean json value, duplicated filter select value)

### ISSUE THREAD

**Issue by Halynsky** [wenzhixin/bootstrap-table#2601]
hi
I have 2 problems with filter-control
1. If we give to the bootstrap-table JSON with Boolean values and we use  data-filter-control="select". This filter will not work at all.
   `Example: {"is_active":true}`
   So to fix it I must to do toString() for each Boolean value in JSON. Its really not nice.
2. If we use 2 different (other id) tables with same name of fields.
   Example:
   Each table have the next row:
   `<th data-field="is_active" data-halign="center" data-align="center"
      data-valign="middle" data-sortable="true" data-filter-control="select">Active
   </th>`

It will produce the bug in select:
![123](https://cloud.githubusercontent.com/assets/8502557/18083499/087297c2-6eac-11e6-808d-27479942443c.png)

**Comment by smollalex** [comment]
Hi, i have same bug, but in my JSOn dont have any boolian values, can you tell me how to fix it? thanks

**Comment by Falseee** [comment]
Opened a PR for Issue 1.
Issue 2 is not reporduceable in the newest version.
