### ISSUE TITLE
Table sticky-header doesn't work if table tag has no id

### ISSUE THREAD

**Issue by eddyLazar** [wenzhixin/bootstrap-table#2602]

**Comment by eleweek** [comment]
I've run into the same problem today

**Comment by wenzhixin** [comment]
Rewrote the code to fix this problem(https://github.com/wenzhixin/bootstrap-table/commit/2766e0074c2ddf863180549da336131b9615c65b) in develop branch.
Develop Example: http://dev.bootstrap-table.com/examples/#extensions/sticky-header.html
