### ISSUE TITLE
Attaching the search to a custom text box

### ISSUE THREAD

**Issue by adc90** [wenzhixin/bootstrap-table#2604]
I'm wanting to create a complex toolbar to go along with bootstrap table for a project I'm working on. However I'm having trouble integrating the built in search with my toolbar. My question is, is there any way to attach the built in search into a custom textbox. I've had issues getting anything going with the toolbar option.

[JS Fiddle](http://jsfiddle.net/61on7z5m/)

Edit: I was able to get around this by implementing a custom search and filtering through and reloading using getData/load, I'd still like to integrate it with the built in search if at all possible.

**Comment by Falseee** [comment]
Could be a good feature, what you think @wenzhixin @djhvscf ?

**Comment by wenzhixin** [comment]
I think https://examples.bootstrap-table.com/index.html#options/custom-toolbar.html or https://examples.bootstrap-table.com/index.html#options/custom-toolbar.html can solve the problem.

**Comment by wenzhixin** [comment]
Example: http://jsfiddle.net/wenyi/ks3ojcen/5/
