### ISSUE TITLE
希望能自定义server的分页参数和返回对象

### ISSUE THREAD

**Issue by lslvxy** [wenzhixin/bootstrap-table#2607]
默认的分页参数pageNumber和pageSize希望能修改为可以自定义的参数，返回的数据格式除了dataField希望再添加一个totalNumberField，这样可以自定义请求参数和返回对象。

**Comment by wenzhixin** [comment]
第一个问题可以用 `queryParams` 解决，第二个问题现在已增加了 `totalField` 属性
