### ISSUE TITLE
Filter Control组件当设置table高度的时候失效

### ISSUE THREAD

**Issue by lslvxy** [wenzhixin/bootstrap-table#2608]
table设置高度之后有两个问题，一个是table的thead会遮挡住fix-table-head的元素，第二个是下拉框选择之后表格重新加载，下拉框的值又变回默认值了

**Comment by Falseee** [comment]
Could you translate it to english and provide us a jsfiddle ?
Issue still exists in the newest version ?

**Comment by wenzhixin** [comment]
Close this issue(3 years), if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
