### ISSUE TITLE
data-height is not working when I use both twitter bootstrap and bootstrap table

### ISSUE THREAD

**Issue by HegdeSach** [wenzhixin/bootstrap-table#2609]
data-height is not working when I use both twitter bootstrap and bootstrap table

I am using twitter bootstrap tabs for my project. My fourth tab is "User list" and if you click on that tab a function is called to get ajax response and the proper values are filled in the table. I am using sort and pagination option for the table.

I have applied data-height to 450. But when the table displayed the height is different. If I do window resize, on window resize i have written resetView, so the height will get assigned to 450. If i do sort to the table then also height will change to 450.

I want to know why that issue coming and how to rectify it.

[jsfiddle](http://jsfiddle.net/Sachin_h/4rw0aawj/) - for the issue I am facing. Click on "User list" tab to see table height.

**Comment by Falseee** [comment]
[Jsfiddle](http://jsfiddle.net/4v7fu1kw/6/) for the newest version.

**Comment by wenzhixin** [comment]
It's the same problem with [bootstrap modal](https://examples.bootstrap-table.com/#welcomes/modal-table.html), need to listen the `callback` event and then call `resetView` method to reset the table height, for example:
```js
$('#modalTable').on('shown.bs.modal', function () {
  $table.bootstrapTable('resetView')
})
```

**Comment by Falseee** [comment]
@wenzhixin Can not we catch that in the code?

**Comment by wenzhixin** [comment]
No, currently we just listened to the `resize` event of the window.
