### ISSUE TITLE
How to refresh the source for editable column(type of select)

### ISSUE THREAD

**Issue by Water0** [wenzhixin/bootstrap-table#2610]
Hi Experts:

I'm working with bootstrap-table in a web project. There are a lot of cases in which I have some editale fields of type select whose list of value is dependent on another field or parameters. But I failed to update the source for these select fields afterthe table initialization.  Here is the case:
1. I create a interface template definition table('templateheader') , which has a field named 'defHeaderId'(interface code table primary key ).  A detail icon in each line is for the detail popup page, which contains the detail table('templateline') . One of the select field's definition is shown as below:
   
      {
               field: 'defLineId',
               title: 'Interface Line',
               sortable: true,
               class: '_defLineId',
               editable: {
                   type: 'select',
                   title: 'Interface Line',
                   source: getInterDefLineCols(),
                   sourceCache: false,
                   validate: function (value) {
                       if (checkNull(value)) {
                           return getMessage('inter.def.template.line.interfacelinecol.null');
                       }
                   }
               }
           }
   
   function getInterDefLineCols() {
         var result = null;
         $.ajax({
             url: '/manage/interdef/getinterdeflinecols/' + modal_header_id,
             async: false,
             type: 'post',
             dataType: 'json',
             contentType: "application/json;charset=utf-8",
             success: function (data) {
                 result = data;
             },
             error: function (data) {
                 result = null;
             }
         });
         return result;
     }
2. I intialize the detail table after the master one by passing defHeaderId as -1:
   modal_header_id = -1;
   initDetailTable();
   the function will return a empty ArrayList。
3. Before I open the model, I set the modal_header_id and try to refresh the source of the field by：

$('.$('._defLineId').editable('option','source',getInterDefLineCols());

but encounter error in google chrome :
bootstrap-editable.js:2143 Uncaught TypeError: Cannot read property 'apply' of undefined

I review the code of bootstrap-editable.js, It seems that   '$.fn.editable = function (option)'  only supports for 'validate','submit',getValue'.

Then I try to destroy the bootstrap-table after hide the model. and call the initialization method 'initDetailTble' to 'rebuild' the bootstrap-table  before the model shown. 

But it seems that each time I open the model(initalize each time), a new instance of the table is created.
the destroy method won't clear the old instance.  The field can list the correct values now but new problem comes. When I click the 'Add' btn to create a row, multilple rows will be created at a time, while the same popup message is shown as the same times when I click 'Delete' btn.

Is there any solution to update/reinit the source of editable select column, or clear the table instance so that only one table instance be keeped after install the bootstrap-table ?

Thanks very much!

**Comment by tiagoura** [comment]
Try 
`editable: {
sourceCache: false ...`
