### ISSUE TITLE
data-page-list attribute should display next array item if matching item is greater then row count only

### ISSUE THREAD

**Issue by abhsk1** [wenzhixin/bootstrap-table#2617]
I have some suggestion , data-page-list attribute of bootstrap table lists the next value if matching row is greater or equals, But condition should be greater than only. Let's assume a case wherein we have data-page-list as [50, 75, 100, 200, 300, 500] and we have total 100 rows in bootstrap table. Now we are getting drop down of 200 as well which is wrong. We must not show the option of 200 as we have total 100 rows only. We should show the 200 in drop down once we got a 101th entry in bootstrap table. So conditional check need to be corrected which check for greater than row count instead greater than or equal to.

Js fiddle is not needed as we can verify this issue in bootrap example
http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by abhsk1** [comment]
@wenzhixin 
I am still waiting for you comments on my suggestion. Do you see it a value point as i felt that it is needed as per user point of view
.

**Comment by abhsk1** [comment]
@wenzhixin This must be fixed by considering the boundary condition for data-page-list attribute. Please let me know if more clarity on issue is required.

**Comment by Falseee** [comment]
Implemented in a newer version of the bootstrap-table.
Working demo: http://jsfiddle.net/8n6kbaf9/3/
