### ISSUE TITLE
Using the component with webpack

### ISSUE THREAD

**Issue by achimha** [wenzhixin/bootstrap-table#2618]
Has anybody managed to bundle this component using webpack? It is on NPM but I have not been able to bundle it and could not find any information.

**Comment by joe44850** [comment]
Looks like package.json points to Gruntfile.js. Is there any intention of making this work with webpack?

**Comment by mickyyman** [comment]
Would love to know how to get this implemented!

**Comment by ducho** [comment]
Hi @achimha !
Any progress with this issue? I try to use webpack and add all bootstrap tables to config but I still get the error: **$table.bootstrapTable is not a function**
