### ISSUE TITLE
BUG? Data columns shifting to left when sorting

### ISSUE THREAD

**Issue by njoannin** [wenzhixin/bootstrap-table#2619]
Summary:

When I sort the data in the table with checkboxes using a sortable column header, the data in the table shifts by one column to the left.

I work on Mac OS. The issue appears both in Firefox and Chrome.

[jsfiddle](https://jsfiddle.net/njoannin/3shzp00b/)
- I have not found it reported before in another issue
- I have not tested master
- CDN for version 1.11.0

I cannot figure out what I am doing wrong. Could this be a bug?

**Comment by njoannin** [comment]
The issue is absent from CDN version 1.10.0:

[jsfiddle_1.10.0](https://jsfiddle.net/njoannin/xLor41v6/)

But version 1.10.0 has an issue with `<a>` elements within a cell.

**Comment by wenzhixin** [comment]
The problem has been fixed in the latest version:
https://bootstrap-table-examples.wenzhixin.net.cn/#issues/2619.html
