### ISSUE TITLE
JSON containing data-* attributes malformed when transformed from normal table

### ISSUE THREAD

**Issue by krassowski** [wenzhixin/bootstrap-table#2621]
This relates to #546 which resulted in implementation of code preserving data-\* attributes from normal HTML tables. It works well, but when the content of data-\* attribute is more advanced, i.e. represents JSON object, instead of preserving the object literal, `[object Object]` string is placed into each data-\* attribute.

This behavior was tested with Chrome 53.0.2785.92 (64-bit) and Firefox 48.0.1 on Linux (Fedora).

[jsfiddle with failing test](http://jsfiddle.net/7gad6sc2/1/) expected result: row is red, div below has new content, like in raw example below:
[jsfiddle with expected behavior](http://jsfiddle.net/7gad6sc2/2/)  (the same but without `data-toggle="table"`)

Line 1067 from 4da4fadab666edd467d88552daef1036ccb6ea67 seems to be responsible for this undesirable behavior.

A handy resource to read more about expected results of keeping JSON inside data-\* attribute is following topic on StackOverflow: [Store JSON object in data attribute in HTML jQuery](http://stackoverflow.com/questions/8542746/store-json-object-in-data-attribute-in-html-jquery).

Regards and thank you for all your great work!

**Comment by krassowski** [comment]
Moreover current implementation always changes single quotation marks surrounding value into double quotation marks which may cause troubles with strings passed in data-*, like `<tr data-mystring='And he said: "this test will fail".'>` (because it will be changed into `<tr data-mystring="And he said: "this test will fail".">`). This violates [W3C standard](https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.2):
> By default, SGML requires that all attribute values be delimited using either double quotation marks (ASCII decimal 34) or single quotation marks (ASCII decimal 39). Single quote marks can be included within the attribute value when the value is delimited by double quote marks, and vice versa.

[jsfiddle](http://jsfiddle.net/7gad6sc2/1/)

**Comment by wenzhixin** [comment]
Fixed in the develop branch.

**Comment by krassowski** [comment]
Thank you!
