### ISSUE TITLE
Can we implement advanced searching like multiplesearch in jqgrid ?

### ISSUE THREAD

**Issue by PerthCharles** [wenzhixin/bootstrap-table#2622]
I am using bootstrap-table to replace jqgrid for my website.
Most of the function of bootstrap-table works great besides the searching part.

Here is the wiki for advanced searching in jqgrid:http://www.trirand.com/jqgridwiki/doku.php?id=wiki:advanced_searching
and you can find the a live demo in http://www.trirand.com/blog/jqgrid/jqgrid.html.

I found that there are two way to implement something like this:  advanced toolbar and bootstrap-table-filter.
a. the advanced toolbar only supports logical "AND" for each columns. It's too simple for me compared with advanced searching in jqgrid.
b. the bootstrap-table-filter looks like more powerful, while the demo for bootstrap-table-filter in https://github.com/lukaskral/bootstrap-table-filter is not working as excepted.

My question: can we implement more powerful advanced searching in bootstrap-table ? if the bootstrap-table-filter can do the job, please give a valid demo. 
Thanks!

**Comment by Falseee** [comment]
https://bootstrap-table.com/docs/extensions/filter-control/
