### ISSUE TITLE
unfilter table filtered by 'filterBy'

### ISSUE THREAD

**Issue by alejandrofm** [wenzhixin/bootstrap-table#2623]
Hi, can't find a way to reset the filter, i'm using:
$('#btTable').bootstrapTable('filterBy', {cluster:5})
Now I want to unfilter (show all rows), can't find the method
Thank you!

**Comment by thornomad** [comment]
`$('#btTable').bootstrapTable('filterBy', {})`

**Comment by andie-chernysh** [comment]
@thornomad, `$('#btTable').bootstrapTable('filterBy', {})` didn't not work for me. It just cleared the table contents.

The workaround I found is to set `filterBy` explicitly for initial state of the table. But I tried that only for boolean values, and not sure if that will be helpful for more complex filtering.

**Comment by thornomad** [comment]
I believe that should work, play with it here:

http://jsfiddle.net/e3nk137y/11135/

**Comment by Falseee** [comment]
`$('table').bootstrapTable('filterBy', {})` works fine (see the demo from @thornomad).
