### ISSUE TITLE
cookie extension does not work with filterControl extension properly

### ISSUE THREAD

**Issue by hrigu** [wenzhixin/bootstrap-table#2624]
I have a combination of the filterControl and the cookie extension. I think this combination does not work together:
1) When reloading the page, the filter string is correctly shown in the filter input field, but the rows aren't filtered accordingly.
The pagination seems to work fine with the cookie extension, as well sorting the columns, 

2) when I have the pagination set in my cookie, and I make a filter, then the filter is displayed and the pagination is lost: correkt.
After reloading the page, the old page is displayed, the filter input as well, but the rows aren't filtered.

See http://jsfiddle.net/e3nk137y/8489/ for a demonstration

Christian

**Comment by Falseee** [comment]
Working demo: http://jsfiddle.net/vxjac65z/

**Comment by UtechtDustin** [comment]
Works fine in the latest version, please update !
Demo: https://live.bootstrap-table.com/code/UtechtDustin/43
