### ISSUE TITLE
hideColumn, showColumn, does not work with reorder-columns extension

### ISSUE THREAD

**Issue by turigeza** [wenzhixin/bootstrap-table#2625]
Step 1, 
Go to 
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-columns.html

Step 2, 
Drag the "Item Name" column to the left. 

Before:
<img width="804" alt="screen shot 2016-09-07 at 18 27 09" src="https://cloud.githubusercontent.com/assets/9335740/18322101/e2a19880-7528-11e6-974f-2efaf5b9ab34.png">

After:
<img width="764" alt="screen shot 2016-09-07 at 18 27 20" src="https://cloud.githubusercontent.com/assets/9335740/18322107/ecadd46a-7528-11e6-8c67-ca4f00bae028.png">

Step 3, 
Hide and then show the "Item Name" column.
<img width="299" alt="screen shot 2016-09-07 at 18 30 09" src="https://cloud.githubusercontent.com/assets/9335740/18322168/2d5918bc-7529-11e6-971b-a543ec090459.png">
<img width="307" alt="screen shot 2016-09-07 at 18 30 15" src="https://cloud.githubusercontent.com/assets/9335740/18322175/33f0c238-7529-11e6-9793-69a42364025d.png">

Step 4, 
See the problem ? Item Name column contains the wrong data.
<img width="1180" alt="screen shot 2016-09-07 at 18 30 22" src="https://cloud.githubusercontent.com/assets/9335740/18322189/47a29874-7529-11e6-98aa-8e005ce81467.png">

**Comment by nicholasrpb** [comment]
not only this, i try to put class for the column, and if it hidden then showed again, the class will be removed

**Comment by sfurey** [comment]
Has this been addressed?

**Comment by turigeza** [comment]
@sfurey I am not aware of it I no longer use this plugin sorry.

**Comment by Falseee** [comment]
Can be tested as soon as #4035 is resolved.

**Comment by UtechtDustin** [comment]
Its fixed in the latest version, there is still a problem with hide/show the correct column after reordering but this issue will be fixed with #4441.
So please update to the latest version.
