### ISSUE TITLE
When sort is clicked, checkbox column are gone

### ISSUE THREAD

**Issue by ohmyohmer** [wenzhixin/bootstrap-table#2627]
I have a table that sorts the data, and also, it has checkbox for my delete data purposes. This is the problem, I do not know if it is, but when I click the the table header to sort the column, checkbox column are gone and the next column move in to the column of the checkbox. I do not know if my doings are correct. 

https://jsfiddle.net/ohmyohmer/oLwjsj46/

**Comment by startovernow** [comment]
Looks like this is already reported in #2619

**Comment by wenzhixin** [comment]
The problem has been fixed in the latest version:
https://bootstrap-table-examples.wenzhixin.net.cn/#issues/2619.html
