### ISSUE TITLE
Is there a way to use detail method 'expandRow/collapseRow' without icon 'detail-icon' shown?

### ISSUE THREAD

**Issue by gjzhappy** [wenzhixin/bootstrap-table#2628]
My issue is as mentioned above ,I want to expand row in my java script manually,and I don't want to see the 'detail-icon' column,is there a solution?

**Comment by stevespringett** [comment]
@gjzhappy did you ever find an answer to this? I want to do the same thing.

**Comment by stevespringett** [comment]
@gjzhappy found an example here:
https://jsfiddle.net/dabros/6ony6cs2/1/

referenced in #964

**Comment by tianyaxue** [comment]
@stevespringett this example i get it ,but it has problem when you detail view is a table,it will display none first td in detail table!

**Comment by Falseee** [comment]
Could be a good feature, what do you think @wenzhixin @djhvscf ?

**Comment by djhvscf** [comment]
Yes it is.
