### ISSUE TITLE
Add prepend table method

### ISSUE THREAD

**Issue by Roquie** [wenzhixin/bootstrap-table#263]
http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#table-methods

Append - ok, how to add prepend row?

**Comment by vgoklani** [comment]
prepend doesn't work for me, in v1.6:

Uncaught TypeError: undefined is not a function

works fine when I replace "prepend" with "append"

**Comment by wenzhixin** [comment]
Hi @vgoklani , see this example: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/prepend.html

**Comment by vgoklani** [comment]
I see the issue, it looks like the API is inconsistent:

if data2 is a list of JSON objects, the following works:

// this works
    $('#table').bootstrapTable('prepend', [data2[0]]);
    $('#table').bootstrapTable('append', [data2[1]]);
    $('#table').bootstrapTable('append', data2[2]);
// this fails
    $('#table').bootstrapTable('prepend', data2[3]);

"prepend" requires a list of JSON objects, whereas "append" will accept an individual JSON object

see here for an example: http://jsfiddle.net/vgoklani/e3nk137y/539/

**Comment by wenzhixin** [comment]
Got it, added to support `prepend` object or array.
