### ISSUE TITLE
Typeahead or Select2 in Editable Extension

### ISSUE THREAD

**Issue by saktibuana** [wenzhixin/bootstrap-table#2631]
Is there any problem regarding using typeaheadjs? since I can't make it work aswell as the select2 when using the editable extension? It keep saying "undefined" although the GUI of the text and
the buttons is nicely formed. Probably there's something I mistype ...

**Comment by Falseee** [comment]
I close this issue because its older than 2 years, if you still need help with that pls provide us an example (jsfiddle).
