### ISSUE TITLE
bootstrap table 'load' function is not working (for me)

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#2635]
bootstrap table 'load' function is not working (for me)

I have a bootstrap-table:

    <table data-toggle="table" 
            id="tblRelation"
            data-click-to-select="true"
            class="table table-striped table-hover table-bordered" 
            style="margin-bottom:0px">
        <thead>
            <tr>
               <th data-field="Selected" data-checkbox="true"></th>
               <th data-field="Name">Customer Name</th>
               <th data-field="View">View DDA Account</th>
            </tr>
        </thead>
    </table>

Then in my javascript:

     $(function () {

        var names = 
        {
            {Name: "VILLAGE CAFE", View: "View", Selected: false},
            {Name: "CAFE", View: "View", Selected: false},
            {Name: "CITY", View: "View", Selected: false}
        }

        $('tblRelation').bootstrapTable('load', names);
        
    }

The table shows "No matching records found"

What I am doing wrong?

Many thanks!

**Comment by panxq5** [comment]
`$('#tblRelation').bootstrapTable('load', names);`

**Comment by startovernow** [comment]
I missed that one! Thanks much!

**Comment by ckulkarni77** [comment]
Hi, 
    I am able to load the new data but the font color seems to be resetting which i had set on load at first time using row style propery? any way to retain the previuos properties?
Thanks in advance!

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks! @ckulkarni77
