### ISSUE TITLE
How can I open detail view by click on a cell, instead of "+" icon

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#2636]
I have a table shown as below, I would like to show detail view when click on "View", without using "+" icon on the left side.

![image](https://cloud.githubusercontent.com/assets/18681747/18451703/9d3726e2-78fd-11e6-9b80-1eeee94657c1.png)

I am thinking I need an "operateFormatter", but how to trig "expand-row.bs.table" and how to display my information without set data-detail-view="true" (because I don't want "+" show up)?

Appreciate your help!

**Comment by startovernow** [comment]
Figured out using @dabros' example. Thanks

**Comment by dabros** [comment]
@startovernow - did you want to link to where you found the solution, just for future searches by other users

**Comment by stevespringett** [comment]
That would certainly be helpful ;-)
