### ISSUE TITLE
hideColumn shifts columns when grid has grouped column

### ISSUE THREAD

**Issue by e1xsd** [wenzhixin/bootstrap-table#2637]
Step 1:
load the grid with grouped columns

![image](https://cloud.githubusercontent.com/assets/18126329/18448954/f80e1b1e-78e1-11e6-93c2-611ca14af8e3.png)

Add function which will hide the Title column:
$('#table').bootstrapTable('hideColumn', 'Title');

After user hides the Title column the Author columns jumps from Group 2 to the Group 1
![image](https://cloud.githubusercontent.com/assets/18126329/18451946/e720e4a6-78ed-11e6-87ad-969f14bc1fb2.png)

Here is the code:

<table id="table" data-pagination="true" data-side-pagination="server" data-height="300" data-show-export="true" data-click-to-select="true" data-show-footer="true" data-response-Handler="responseHandler">
  <thead>
    <tr>
      <th colspan="2">Group 1</th>
      <th colspan="2">Group 2</th>
    </tr>
    <tr>
      <th data-field="bookId">Book Id</th>
      <th data-field="Title" data-align="right" data-sortable="true">Title</th>
      <th data-field="author" data-align="center" data-sortable="true" data-footer-Formatter="totalTextFormatter">Author</th>
      <th data-field="memberId" data-sortable="true" data-footer-Formatter=sumFormatter>Price</th>
    </tr>
  </thead>
</table>

<div id="toolbar">
  <button id="button" class="btn btn-default" onclick="testShow()">showColumn</button>
  <button id="button2" class="btn btn-default" onclick="testHide()">hideCoulumn</button>
</div>
# 

$('#table').bootstrapTable({
  data: "https://api.myjson.com/bins/tucu"
});

function testShow() {
  $('#table').bootstrapTable('showColumn', 'Title');
}

function testHide() {
  $('#table').bootstrapTable('hideColumn', 'Title');
}

function responseHandler(res) {
  return {
    rows: res.content,
    total: res.totalElements,
    pageNumber: res.number,
    pageSize: res.size
  }
}

**Comment by nicholasrpb** [comment]
waiting for answer for this as well, i have tried to make id for the  colspan and try to hide it but no luck

**Comment by Falseee** [comment]
One issue (#3183) is enough.
