### ISSUE TITLE
add support for html escape (danger when user input script)

### ISSUE THREAD

**Issue by zengfanfan** [wenzhixin/bootstrap-table#2640]
say if a column shows text that input by user,
someone post this:
`<script>alert(1)</script>`
the sample code does no harm, but as we all should know, it may.

allow user input executable script can be very dangerous.

can we add support for html escape? that can avoid this

thanks!

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/table-options/#escape
https://bootstrap-table.com/docs/api/column-options/#escape
https://examples.bootstrap-table.com/index.html#options/table-escape.html
