### ISSUE TITLE
'load' not working inside on('expand-row.bs.table', function (e, index, row, $detail)?

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#2642]
I have few places calling 'load' and it works perfectly, but it is not working inside expand-row.bs.table handler? 

I have a static html file I want to use from different pages as shown here (account.html):

```
<div class="panel panel-default" style="width:80%; align-content:center">
<div class="panel-body">
    <table data-toggle="table" id="table"
           class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th data-field="AccountNumber">Account Number</th>
                <th data-field="Name">Name</th>
                <th data-field="DateOpened">Date Opened</th>
            </tr>
        </thead>
        </table>
    </div>
</div>
```

I want to dynamically load data when detail view is displayed:

```
$tblCustomer.on('expand-row.bs.table', function (e, index, row, $detail) {
    //testing data 
    var accounts = [
        {"AccountNumber": "153600799701", "Name": "City Of Brookfield", "DateOpened": "11/19/2002"},
        {"AccountNumber": "153654488908", "Name": "City Of Brookfield", "DateOpened": "12/15/2008"},
        {"AccountNumber": "153789789009", "Name": "City Of Brookfield", "DateOpened": "05/28/2012"}
     ];

    $.get('/Views/Shared/account.html', function (data) {                
            $detail.html(data);
            $detail.find('#table').bootstrapTable('load', accounts);
     });
```

When I step through the code, I can see $detail.find('#table') return correct content, and 'account' looks fine too:

![image](https://cloud.githubusercontent.com/assets/18681747/18530677/49b990ee-7a98-11e6-83a3-f8c06ebdad50.png)

But when I further step into bootstap-table.js, at line# 2971, data is undefined, so it returned at line# 2980, so actual 'load' are not getting called. 

What I am missing? Any help greatly appreciated!

![image](https://cloud.githubusercontent.com/assets/18681747/18530837/fd5be7a0-7a98-11e6-9a50-9d0d810fe81d.png)

**Comment by mursang** [comment]
how did you solve this?
