### ISSUE TITLE
filterBy regression - no longer supporting arrays

### ISSUE THREAD

**Issue by thornomad** [wenzhixin/bootstrap-table#2643]
### `filterBy` no longer works with an array

```
$('#table').bootstrapTable("filterBy", {"forks_count": ["11","4"]});  // broken
```

See this example of it not working:

http://jsfiddle.net/thornomad/mqaybexx/
### code change at some point

It looks like the logic was changed at some point (can't find the specific commit).  I had originally submitted #1526 with a working solution but since then the code was refactored.  I am not sure if that was to fix something or just an attempt at cleanup.
### pull request submitted

http://jsfiddle.net/thornomad/9p854bm4/

**Comment by cspirito** [comment]
I just encountered this as well. When the array evaluation succeeded the conditional looked to the other part of the OR evaluation. For those who need this to work before the patch is submitted.

```
this.data = f ? $.grep(this.options.data, function (item, i) {
                for (var key in f) {
                    if ($.isArray(f[key]) && $.inArray(item[key], f[key]) === -1) {
                        return false;
                    }
                    if (!$.isArray(f[key]) && item[key] !== f[key]) {
                        return false;
                    }
                }
                return true;
            }) : this.options.data;
```

**Comment by wenzhixin** [comment]
#2439
