### ISSUE TITLE
It will be much better if it supports freezing columns and tableheads easily with extra parameters added to table

### ISSUE THREAD

**Issue by MeMadMan** [wenzhixin/bootstrap-table#2648]
It will be much better if it supports freezing columns and tableheads easily with extra parameters added to table

the current solution seems a little awkward and doesn't support IE.

http://www.tuicool.com/articles/QZnmUbv

**Comment by Falseee** [comment]
I close this issue because its already older than 2 years, if you still need help pls reopen the issue.
