### ISSUE TITLE
Add fix first Column feature

### ISSUE THREAD

**Issue by Pauldic** [wenzhixin/bootstrap-table#265]
For some large column table, it is often a requirement to maintain a visual sight about a row of interest. Often there is a need to fix the first two column (Serial No and Record Identifier Column) eg S/n and Name while one scroll from left to right.  Just something similar to http://jsfiddle.net/Pauldic/01hk2exp/

**Comment by samfb** [comment]
Are there any updates on this feature?

**Comment by mmoonzhu** [comment]
这确实是一个表格中比较有用和基本的特性，找解决方案找到这里了，看来这个需求提出已久了，希望@wenzhixin 能尽早实现 :）。

**Comment by Giorgionocera** [comment]
I'm waiting for this feature!! All the plugin it's fantastic!
This feature it's really important! Thank you @wenzhixin !

**Comment by jeevanpulugu** [comment]
Hi @wenzhixin is there any update on this feature and time line to expect?

Thanks @wenzhixin

**Comment by ediri** [comment]
wow, much requests on this feature! Hope to see it soon in your fantastic lib @wenzhixin !

**Comment by dabros** [comment]
Maybe related to #1332

**Comment by wenzhixin** [comment]
Added an extension: https://github.com/wenzhixin/bootstrap-table-fixed-columns
