### ISSUE TITLE
Sorting a column by its foreignKey-String-values, and not the id

### ISSUE THREAD

**Issue by peter12333** [wenzhixin/bootstrap-table#2650]
Hi,

i have a table in my application where i replaced one column of integer-ids with their corresponding string-values, since this column is a foreign key column, connecting to another entity. 
I did this with following peace of code:
`editable: {
                                type: 'select',
                                source: foreignKeyValues
                            }`

When i'm sorting this column, it unfortunately sorts by the "original value", which is the id of course. I'd like to be able to sort it by the strings instead, is there an easy way to do this?

Thank you in advance!

peter

**Comment by wenzhixin** [comment]
You can use `sorter` column option to define the custom sort: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-sort.html

**Comment by peter12333** [comment]
@wenzhixin that's exactly what i was looking for, thanks so much!
