### ISSUE TITLE
Cookie issue: data-url not loaded when using cookie extension

### ISSUE THREAD

**Issue by SystemF** [wenzhixin/bootstrap-table#2651]
When I try to use the cookie extension the data-url request won't fire, so there are no rows. When I put the data attribute inline (no request) then it do work.

Setting the cookie extension to false, bootstrap table will show all rows as intended.

Please take a look at http://dev1.puntxl.nl/ for a minimized working example.

Edit: When I use an older version of the bootstrap-table-cookie.js it works like expected.

**Comment by cyberbobjr** [comment]
Hi, same problem here

**Comment by SystemF** [comment]
I took it from a older CDN that I found after some search on the web. Maybe you can look for some older release tags here on Github too. Success!

**Comment by mmerian** [comment]
Hi guys,

Looks like this is a duplicate of issue #2582 

Cheers

**Comment by Falseee** [comment]
Issue is resolved, see #2582
