### ISSUE TITLE
How to remove or hide "icon plus" specific of subtable

### ISSUE THREAD

**Issue by RenanCristiano** [wenzhixin/bootstrap-table#2652]
I have a table structured tree.
I wish the icon was visible only to the node that has sub node
example:

![example](https://cloud.githubusercontent.com/assets/22276229/18616600/2f94efe2-7d95-11e6-9694-97d4f6bca723.png)

JSFiddle:
https://jsfiddle.net/vuLj1bcb/24/

**Comment by Falseee** [comment]
In the newer versions you can use the `detailFilter` option.
https://bootstrap-table.com/docs/api/table-options/#detailfilter
https://examples.bootstrap-table.com/index.html#options/detail-filter.html
