### ISSUE TITLE
Update database after every cell edit ... how to get data to backend?

### ISSUE THREAD

**Issue by peter12333** [wenzhixin/bootstrap-table#2653]
I'm trying to get data back to my backend from my bootstrap table. Unfortunately i spent a few hours today on this without any success.

What i have until now is the following:
on the frontend side i assigned the class "mycolumn" to every field/column in my table.

Furthermore when loading the page i'm doing the following:

```

function initSaveButton() {
    $('#carList_table').on('editable-save.bs.table', foo);
}

function foo(field, row, oldValue, $el) {

    $('.mycolumn').editable('submit', {
        type: "POST",
        contentType: "application/json",
        data: oldValue,
        pk: 1, // ???
        url: "/updateCar",
        ajaxOptions:{
            dataType: 'json',
            type:'post'
        }
        /*  success : function(resp) {
         console.log(resp);
         },
         error:function(resp){
         console.log("error:", resp)
         }*/
    });
}
```

My goal is to update an item everytime i'm editing a cell in my table.
At least it triggers everytime i'm editing a cell, but there is nothing getting to my backend.
Moreover, i don't understand the client side validation. I assigned a validation function to every field/column in my table, but after debugging for quite some time it seems to me that everytime, i'm editing a cell in the table, it tries to validate the whole row, right? But this doesn't work in my case, because only the currently edited column/field has a "value" when calling the validate() method, every other column is "undefined" or null. My current workaround was to modify my validate()-method in such a way so it everytime says "ok", by simply return null, no matter what. I will target this problem as soon as i manage to get data to my backend, which is more important to me at the moment. (But if you can help me here too, this would be awesome of course)

My java controller on the backend side looks like this (well it's just the one method inside the controller):

```

@RequestMapping(value = "/updateCar", method = RequestMethod.POST)
    public @ResponseBody String updateCar(@RequestParam(value="value") String value, HttpServletRequest request) {
        logger.info("Updating Car. DEBUG INFO:  "+value);
        return "";
    }
}
```

What am i doing wrong? What am i missing?
I don't have too much experience in this so sorry if those are stupid questions.. but i have been google-ing the whole day and did not have any success.

I'm looking forward to replies :)

Thank you!

peter

**Comment by Falseee** [comment]
I close this issue because its already older than 2 years, if you still need help pls reopen the issue.
