### ISSUE TITLE
How to export quiet great numbers of data by bootstrap-table-export.js

### ISSUE THREAD

**Issue by knightjbq** [wenzhixin/bootstrap-table#2654]
Here is the problem. When i try to use this to export all data (about 9k). The browser go disabled and cannot show any response for 2min. What shall i do if i wanna export so much data?

**Comment by djhvscf** [comment]
I think you can open an issue here: https://github.com/hhurz/tableExport.jquery.plugin

**Comment by wenzhixin** [comment]
In this case, I think it's better to use the server to export.
