### ISSUE TITLE
How to activate the table edit box

### ISSUE THREAD

**Issue by kyan54** [wenzhixin/bootstrap-table#2656]
After the call to the insert method
How to activate the table edit box？

（
英文不好，所以在写一下中文
在调用insert方法后，如何激活新增行的第1列的输入框？
English is not good, so write about Chinese
After the call to the insert method, how to activate the new line edit box the first one?
）

code：
$('#table').bootstrapTable('insertRow', {
            index: 0,
            row: {
                name: "",
                stargazers_count: "",
                forks_count: "",
                description: ""
            }
        })
        //$("#table tbody tr").eq(0).css("height",30);
        $("#table tbody tr").eq(0).find("td:eq(0)").trigger("click");？？

**Comment by wenzhixin** [comment]
Close this because it is more than 3 years if you still need help please reopen and provide a jsfiddle.
