### ISSUE TITLE
Card view with same field name but different column shows same label

### ISSUE THREAD

**Issue by ChristoforosKor** [wenzhixin/bootstrap-table#2657]
Card View for same field on different columns shows same label

I have a table on wich the first three columns gets data from the same json field. This filed is a json object with subvalues.
I use different cell formaters to each of these three cells. From these three different formaters I can distinguish the unique values.
On regular table view everything is ok. But in card view these three columns get the same label.

Below is the table definition:

`         data-detail-view="true" 
               data-height="800" 

```
           data-row-style="elgCoupon.rowFormatter">
        <thead>
            <tr>

                <th data-field="c" data-formatter="elgCoupon.idFrm"  data-class="coupon-matchcode" data-sortable="true" >Κωδ.</th>
                <th data-field="m"   data-class="coupon-match" data-formatter="elgCoupon.matchFrm" data-sortable="true">Ομάδες</th>
                <th data-field="cnt"  data-formatter="elgCoupon.mNoFrm" data-sortable="true" >Προβλ.</th>
                <th data-field="b0" data-formatter="elgCoupon.b01Frm" ><span class="label label-info" >1</span></th>
                <th data-field="b0" data-formatter="elgCoupon.b0xFrm" ><span class="label label-info" >X</span></th>
                <th data-field="b0" data-formatter="elgCoupon.b02Frm" ><span class="label label-info" >2</span></th>
                <th data-field="b1" data-formatter="elgCoupon.bFrm"  >Διπ. Ευκ.</th>
                <th data-field="b2" data-formatter="elgCoupon.bFrm"  >Απ. Ημ.</th>
                <th data-field="b3" data-formatter="elgCoupon.bFrm"  >Ημ./Τελ.</th>
                <th data-field="b4" data-formatter="elgCoupon.bFrm"  >U/O 2,5</th>
                <th data-field="b5" data-formatter="elgCoupon.bFrm"  >U/O 3,5</th>
                <th data-field="b6" data-formatter="elgCoupon.bFrm"  >Συν.Τερμ.</th>
                <th data-field="b7" data-formatter="elgCoupon.bFrm"  >G/NG</th>
                <th data-field="b254" data-formatter="elgCoupon.bFrm254"  >No Bet</th>
            </tr>
            <tr>

            </tr>
        </thead>
    </table>`
```

as you can see columns 3-6 have the same data-field "bo" but different formatters: elgCoupon.b01Frm,
elgCoupon.b02Frm, elgCoupon.b03Frm.

These columns come with label 1 on card view.

**Comment by windymedia** [comment]
I am also seeing the same behavior. I am using the data-field with the name "itemNumber" twice to show an Edit button in one column and the data in another. In grid view, both have the label of "Number".

`<th data-field="itemNumber">Number</th>`
`<th data-field="itemNumber" data-formatter="RowEdit">Edit Item</th>`

Seems like it would be trivial to resolve but not sure where to look...

**Comment by jimgit** [comment]
[Can you provide a jsfiddle.](http://jsfiddle.net/wenyi/e3nk137y/13/)

**Comment by windymedia** [comment]
http://jsfiddle.net/8dbmykuL/23/

See column/row heading for edit button when switching view.

Thanks.

**Comment by jimgit** [comment]
Yes - see it in your JSFiddle.  Not sure but [what's different between this JSFiddle](http://jsfiddle.net/jimkennelly/4bvjhqh9/) and yours?

**Comment by jimgit** [comment]
I use the pattern you mentioned all the time without a problem:

**_<th data-field="itemNumber">Number</th>
<th data-field="itemNumber" data-formatter="RowEdit">Edit Item</th>_**

**Comment by jimgit** [comment]
`<th data-field="itemNumber">Number</th>
<th data-field="itemNumber" data-formatter="RowEdit">Edit Item</th>`

**Comment by windymedia** [comment]
Thanks - this looks like a good workaround and seems to solve the issue.

I appreciate your help.

**Comment by Falseee** [comment]
@wenzhixin @djhvscf Not really a bug and he found a workaround for that, so the bug can be closed i guess.
