### ISSUE TITLE
table field html editor

### ISSUE THREAD

**Issue by kamov** [wenzhixin/bootstrap-table#2658]
Hi,
I am trying to use data-editable-type=wysihtml5 
but is not working.

I want to use bootstrap-wysihtml5 editor

thanks

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
Works fine in the newest version for me :-)
![ezgif-4-8540de8daf0c](https://user-images.githubusercontent.com/13292481/68999825-8409c100-08c6-11ea-9823-c19bdaac02ed.gif)
