### ISSUE TITLE
 How to remove rows using the data- index

### ISSUE THREAD

**Issue by mcruzm** [wenzhixin/bootstrap-table#2660]
You can do the following $ ( "table" ) bootstrapTable ( "remove " data- index { 1 } ) .

**Comment by Falseee** [comment]
There is no data-index option, you can assign unique ids and remove the rows with [removebyuniqueid](https://bootstrap-table.com/docs/api/methods/#removebyuniqueid)

**Comment by wenzhixin** [comment]
Duplicate of #564
