### ISSUE TITLE
Get Data Out After Editted Table

### ISSUE THREAD

**Issue by nicholasrpb** [wenzhixin/bootstrap-table#2663]
Hi i have editted table using 
onPostBody: 
$('#normal_window_limit_table').bootstrapTable({
                        data: window,
                        onPostBody: function () {
                            $('#normal_window_limit_table').editableTableWidget({

and i have another click button function to get the data of the table after editted
var after_edit= $('#normal_window_limit_table').bootstrapTable('getData', {useCurrentPage: true});

however, the data in after_edit variable still use old data before editted
is there a way to get the data as the latest updated from the table?

**Comment by wenzhixin** [comment]
Close this because it is more than 3 years if you still need help please reopen and provide a jsfiddle.
