### ISSUE TITLE
bootstrap-table show in IE

### ISSUE THREAD

**Issue by wzqiang1332** [wenzhixin/bootstrap-table#2664]
the table width Attribute is not effective in IE，and the column‘s attribute "width" is not effective in IE and chrome

**Comment by Falseee** [comment]
Could you provide us an example(jsfiddle), if the issue still exists ?

**Comment by wenzhixin** [comment]
Close this issue because it's about 3 years if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
