### ISSUE TITLE
Unable to reorder the row in card view

### ISSUE THREAD

**Issue by LostIndie** [wenzhixin/bootstrap-table#2665]
Hi,

I am currently using the bootstrap table to display the records. I used the bootstrap table reorder-row extension to reorder the row in table. The reorder row is not working when the browser size is resize to small like the mobile screen size. The table in screen become card view layout after resized browser and the reorder row is not working. How to solve it?

**Comment by Falseee** [comment]
Demo: http://jsfiddle.net/c9vbsqjh/4/

**Comment by UtechtDustin** [comment]
We could easy enable that, but the used plugin (TableDnD) can't handle html inside of the row.
So we have only a few pixels on the borders to drag it.

What do you think @djhvscf @wenzhixin ?
