### ISSUE TITLE
It's hard to read "description column" on documentation 

### ISSUE THREAD

**Issue by vingorius** [wenzhixin/bootstrap-table#2667]
When read a bootstrap-table documentation, the description column is hard to read because of unwraped.
Please refer the attached file.

My env is Firefox 49.0 on ubuntu 16.04 64 bit.

![2016-09-26 17-23-10](https://cloud.githubusercontent.com/assets/5274928/18827534/45c5878e-840e-11e6-904b-ff6516436b28.png)

**Comment by wenzhixin** [comment]
Fixed in the latest version: https://bootstrap-table.com/
