### ISSUE TITLE
It's contradictory when setting data-fixed="false" and data-width for column in resizable extension

### ISSUE THREAD

**Issue by Harry3014** [wenzhixin/bootstrap-table#2669]
It's contradictory when setting data-fixed="false" and data-width for column in resizable extension. I set width=100px for column and fixed=false, but the result of width is not 100px. @djhvscf 

[jsfiddle]() - a link to the reduced test case((https://jsfiddle.net/w3af6aj4/3/)).

**Comment by Falseee** [comment]
Cant find any column option `fixed`, cant reproduce the issue (http://jsfiddle.net/7brzpq3g/2/) and the issue is older than 2 years.
