### ISSUE TITLE
Use some functions of bootstrap-table in some events cause infinit loop.

### ISSUE THREAD

**Issue by emanoelqueiroz** [wenzhixin/bootstrap-table#2670]
When you use some functions like **showColumn** or **hideColumn** in some of the events like **onPostBody** or **onPostHeader** cause infinit loop because the plugin execute the trigger in the events when **initBody()** or **initHeader()** are executed for exemple.

I think if you create other function (**refreshBody()** for exemple) and this function not trigger those events (can be created other new triggers), the problem will be solved.

Thank you 

:dragon_face: :+1: :dancer: :dancers:

**Comment by Falseee** [comment]
Could you give us an example for this case ?
I think there is a other/better solution then a new function, i dont think that so much people need this function.

**Comment by Falseee** [comment]
I close this issue because we got no response/example within 7 days.

**Comment by emanoelqueiroz** [comment]
Ok, i don't got any response after 3 years ¯\_(ツ)_/¯

**Comment by Falseee** [comment]
This is not meant to be bad, but we are currently cleaning up the issues.
So if you still have this issue reopen the issue and we will check it, but dont forgett to add an example (jsfiddle).
