### ISSUE TITLE
Select2-filter + column sort doesn't work

### ISSUE THREAD

**Issue by LucasMarquesDePaula** [wenzhixin/bootstrap-table#2671]
Hi everyone.
First of all, congratulations for the API. It is awesome to work with Bootstrap Table.

Today I discovered the Select2-Filter extention but when I tried to use it I had some problems.

When I set the table to add Select2-Filter the column sorting didn't work. 
It starts working again if I type something in the select2 filter (eg. the letter b). When there are something typed in the select2 filter the sorting works as usual.

Example: http://jsfiddle.net/p7qkw4by/

Working:
![image](https://cloud.githubusercontent.com/assets/22457494/18886979/9f8ca1e8-84c8-11e6-8062-db1095828943.png)

Doesn't
![image](https://cloud.githubusercontent.com/assets/22457494/18886999/b73df5da-84c8-11e6-88ea-4442511b33ed.png)

I'll be gratefull if someone could help me.

Thanks.

**Comment by Dunstkreis** [comment]
Same problem here, thats why i am looking through the issues...
I first found this issue too while looking at select2-filter
Could chase the problem down to the `initSearch()` function. It gets called at many places. for example when calling `resetSearch` like this `$('#table').bootstrapTable('resetSearch');`
or after changing the input in the search box... many places.

But when the searchtext is "" (empty string) and `initSearch()` function is getting called, sorting stops working. Give it a try: fill in some search text, empty it and try to sort. doesn't work for me.
Also after loading new data in the background into the table, when search field is empty, sorting stops working right there.

**Comment by zagher** [comment]
same issue for me

**Comment by jewway** [comment]
Hi everyone,
I fixed this issue on bootstrap-select2-filter ver 1.1.0 , 
please reference this link  [https://github.com/wenzhixin/bootstrap-table/pull/3274](url)
