### ISSUE TITLE
Should be able to set the search input's placeholder text from data-* attributes

### ISSUE THREAD

**Issue by kraghavk** [wenzhixin/bootstrap-table#2673]
Hi,

First of all. Thanks for the great work and this plugin is truly awesome.

I think we should be able to specify the placeholder text for the search input through data attributes.

For now, I have the following workaround:

Define a data-search-placeholder attribute on the table as below:
`<table id='bootstrap-table-demo' data-search-placeholder'`

And on document ready, find the search input for the table and replace the placeholder, as below:

```
$(document).ready(function() {
    $("table[data-search-placeholder]").each(function () {
        $(this).parents("div.bootstrap-table")
            .find("input[placeholder='Search']")
            .attr("placeholder", $(this).data("search-placeholder"));
    });
});
```

On similar lines, it would be great if we could also somehow manipulate the width of the search input. Again, the workaround I have is to define a data-search-input-container-class on the table element. On document ready, I apply the css class defined in this attribute to the search input's parent div:

```
$(document).ready(function() {
            $("table[data-search-input-container-class]").each(function () {
                $(this).parents("div.bootstrap-table")
                       .find("div.search")
                       .addClass($(this).data("search-input-container-class"));
            });
});
```

Once again, thanks for the great work.

**Comment by Falseee** [comment]
https://bootstrap-table.com/docs/api/localizations/#formatsearch

**Comment by kevinsweeney84** [comment]
@UtechtDustin the format search works perfectly.

Is there a similar functionality for formatting the search boxes within the advanced search functionality?
