### ISSUE TITLE
DetailView and reorderableColumns have a bug

### ISSUE THREAD

**Issue by javieerrubio11** [wenzhixin/bootstrap-table#2674]
When I use the detailView and reorderableColumns plugin It produces the next error.

Chrome console log：
bootstrap-table.js:2256 Uncaught TypeError: Cannot read property 'visible' of undefined

[Example jsfiddle](https://jsfiddle.net/javierIntegra/gn78ozxh/11/)

In order to reproduce the error, you have to reorder some column and after that, you tray to order one column asc or desc for example.

Thanks for all.

**Comment by pozuelog** [comment]
Same bug is affecting me. Did yout find a solution?

**Comment by javieerrubio11** [comment]
Sorry, but I don't find a solution.

**Comment by UtechtDustin** [comment]
Cant reproduce it, also its almost 2 1/2 so i close the issue.
If this issue still exists please reopen the issue.
