### ISSUE TITLE
PaginationLoop set to false no effect

### ISSUE THREAD

**Issue by gzq0616** [wenzhixin/bootstrap-table#2675]
PaginationLoop set to false no effect

**Comment by martinburch** [comment]
The property is called `paginationLoop` with a lowercase `p`. Perhaps that was the problem?

It works for me. Working example:
http://jsfiddle.net/e3nk137y/13091/

```
$(function () {
    $('#table').bootstrapTable({
        data: data,
        pagination: true,
        paginationLoop: false
    });
});
```

**Comment by djhvscf** [comment]
@gzq0616 review the comment of @martinburch
