### ISSUE TITLE
Multiple tables in same page

### ISSUE THREAD

**Issue by JorgeCamarena** [wenzhixin/bootstrap-table#2676]
I had two tables working in different pages, but I need them to be in the same, but the problem is that just the last JavaScript imported is the one that works. If I place them like this:

<script src="modules/registrarRoles/tablaRoles.js"></script>

<script src="modules/registrarUsuarios/tablaUsuarios.js"></script>

If I change the order just the last script work
![captura de pantalla 2016-09-28 a la s 6 17 54 p m](https://cloud.githubusercontent.com/assets/20867695/18936826/f7383486-85a7-11e6-9b3b-63d5605cc8e5.png)
![captura de pantalla 2016-09-28 a la s 6 19 08 p m](https://cloud.githubusercontent.com/assets/20867695/18936837/185cc2a8-85a8-11e6-8ac5-ca520533c63c.png)

The last one will work but not the other one. 

I am using the example in this [page](http://issues.wenzhixin.net.cn/bootstrap-table/)
but instead of having my scripts in my HTML code, I created a JavaScript file.

I will attach my files (html where my tables are, and both scripts):
[git.zip](https://github.com/wenzhixin/bootstrap-table/files/499520/git.zip)

**Comment by moebaca** [comment]
No updates to this then?

**Comment by wenchun** [comment]
load before do anything.

**Comment by wenzhixin** [comment]
Working examples: https://examples.bootstrap-table.com/#welcomes/multiple-table.html
Close this because it is more than 3 years if you still need help please reopen and provide a jsfiddle.
