### ISSUE TITLE
click row and select radio,  row style(background) change.

### ISSUE THREAD

**Issue by liululululu** [wenzhixin/bootstrap-table#2677]
http://jsfiddle.net/wenyi/e3nk137y/3814/
http://jsfiddle.net/wenyi/e3nk137y/29/
I use two example code, but have 1 bug.
![image](https://cloud.githubusercontent.com/assets/10783450/18940629/91ad1fa6-863c-11e6-8bd3-2b99bd1bedbd.png)

**Comment by liululululu** [comment]
![image](https://cloud.githubusercontent.com/assets/10783450/18944417/19adda2e-8658-11e6-9a16-388280bf346a.png)
![image](https://cloud.githubusercontent.com/assets/10783450/18944420/1d07d472-8658-11e6-92e9-44462c18c695.png)
This is my code, when i  click the radio, this parents(tr) style can't change!

**Comment by grunmin** [comment]
bs-table没有监听td内的元素， 也没有做委托。因此需要自己监听checkbox的change事件

**Comment by wenzhixin** [comment]
经过测试，是可以的：https://examples.bootstrap-table.com/index.html?bootstrap3#issues/563.html
