### ISSUE TITLE
data-page-list

### ISSUE THREAD

**Issue by farhanwazir** [wenzhixin/bootstrap-table#2681]
If i add "data-page-list" attribute with values[10, 'All']; table showed me NaN instead All. What is best option to export all record dynamically?

**Comment by hifiveszu** [comment]
[10, All] is correct : )

**Comment by hifiveszu** [comment]
@farhanwazir, [10, All] is the right answer : )

**Comment by hifiveszu** [comment]
Hi @farhanwazir，as [documentation](http://bootstrap-table.wenzhixin.net.cn/es/documentation/) of bootstrap table mentioned, table option `pageList ` or `data-page-list` should be an array like [10, 25, 50, 100, All], so you can change your option to  [10, All] : )

**Comment by wenzhixin** [comment]
@hifiveszu is right.

**Comment by 6ril00** [comment]
Hello,
I give the solution i just found, for this problem (NaN issue with All value on pageList parameter).
I you use translation, and so have changed the formatAllRows string value from 'All' to another string, you have to use this another string for paginating. By example, if you have changed:

```
 $.fn.bootstrapTable.locales['fr-FR'] = {
 formatAllRows: function () {
            return 'Tous';
        }
    };
```
You have to write: 
`data-page-list="[10, 25, 50, 100, Tous]"`
or in js:
`pageList : [10,20,30,'Tous']`

 (tested in 1.11.1)

**Comment by zorgoz** [comment]
Same here. According to the post of @6ril00, I have added the string corresponding to All in the current locale. But this method does not support changing localization on the fly! `All` should be the value in `data-page-list` array, while the text in the dropdown should be taken from the locale.

**Comment by djhvscf** [comment]
@zorgoz could you open a new issue with this information?
