### ISSUE TITLE
Custom sort

### ISSUE THREAD

**Issue by corina10** [wenzhixin/bootstrap-table#2684]
I found this fiddle in one of your examples: 
http://jsfiddle.net/e3nk137y/4248/
I noticed that each time I sort by Stars in descending order, elements having the same value (zero) are returned in a different order.
I perform refresh operations on your table and this issue is bothering.
Is there a way to preserve the order? Maybe sorting by a second column?

Thank you!

**Comment by Falseee** [comment]
The issue already 2 years old, but here is your answer:
Your sort function (`starsSorter`) will get as third and fourth parameter the rows, so you can sort by stars AND by name.

Can be closed i guess @wenzhixin @djhvscf
