### ISSUE TITLE
idField not works properly

### ISSUE THREAD

**Issue by andig89** [wenzhixin/bootstrap-table#2685]
> idField   data-id-field   **String**  undefined   Indicate which field is an identity field.

Look at id attribute on "tr" tag.
http://jsfiddle.net/andig89/e3nk137y/9041/ - works, but why? It shouldn't.
http://jsfiddle.net/andig89/e3nk137y/9042/ - doesn't work
http://jsfiddle.net/andig89/e3nk137y/9043/ - doesn't work

**Comment by Falseee** [comment]
Show #4233, the idField is for the checkboxes/radioboxes.
I guess the first jsfiddle works because you use `_id` and overwrites an internal variable (https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L314).
