### ISSUE TITLE
TypeScript type definition - typings

### ISSUE THREAD

**Issue by talatbaig** [wenzhixin/bootstrap-table#2687]
Hi,

Does anyone know where I can find the TypeScript type definitions for this library, I couldn't find them on DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped

Thanks

**Comment by elliott-pd** [comment]
They are on DefinitelyTyped.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/4c76db9b47091930da087a41d0b02f316ead37b0/bootstrap-table

**Comment by katrina-engelbrecht** [comment]
I have the same question.

**Comment by ChobitsSP** [comment]
https://github.com/ChobitsSP/types-bootstrap-table
