### ISSUE TITLE
input field should allow disabled column option

### ISSUE THREAD

**Issue by cheizer** [wenzhixin/bootstrap-table#2688]
Setting "disabled" column option does not do anything. This should be allowed on all input fields. 

Example ... 
`columns: [{
            field: 'Enabled',
            checkbox: true,
            rowspan: 1,
            align: 'center',
            valign: 'middle',
            disabled: true
            }]`

For now, I have modified the my bootstrap-table.js for the checkbox to something like this 

`sprintf(' %s', (that.options.columns[j][0].disabled === true) ? 'disabled=disabled' : '') +`

**Comment by Falseee** [comment]
To disable checkboxes you can use the column option  `checkboxEnabled` or `data-checkbox-enabled`.

**Comment by djhvscf** [comment]
Merged in develop
