### ISSUE TITLE
Bug pagination in group-by v2 in multiple tables when change  data-group-by-field 

### ISSUE THREAD

**Issue by nando-San** [wenzhixin/bootstrap-table#2689]
Hi guys, i found bug in group by v2, only works in single table, multiple tables cause error if i change data-group-by-field, when click the pagination. 

http://jsfiddle.net/rma15xzm/3/

**Comment by akshairajendran** [comment]
Having the same issue...

**Comment by UtechtDustin** [comment]
The group by extension will be merged/rewritten, this issue will be checked in #4413.
