### ISSUE TITLE
if some or one of data-field is null search is not working 

### ISSUE THREAD

**Issue by ozturki** [wenzhixin/bootstrap-table#2690]
if data contains null fields search gives error

bootstrap-table.min.js:7 Uncaught TypeError: Cannot read property 'status' of null(anonymous function) @ bootstrap-table.min.js:7grep @ jquery.min.js:2p.initSearch @ bootstrap-table.min.js:7p.onSearch @ bootstrap-table.min.js:7(anonymous function) @ bootstrap-table.min.js:7

I am not good at javascript but following code starting with line 1256 worked for me 
I even dont know how to minify js code. If it is appropriate please add it to min.js 

`if (typeof key === 'string') {
    value = item;
    console.log(value);
    var props = key.split('.');
    for (var prop_index = 0; prop_index < props.length; prop_index++) {
        if (value[props[prop_index]] != null) {                             
            value = value[props[prop_index]];
        }
    }
    // Fix #142: respect searchForamtter boolean
    if (column && column.searchFormatter) {
        value = calculateObjectValue(column,
            that.header.formatters[j], [value, item, i], value);
    }
} else {
    value = item[key];
}`

**Comment by rodolfosouza** [comment]
+1 the same

**Comment by shows19** [comment]
i was also getting the same error and adding the lines on line 1268 solved the issue:

							if (value[props[prop_index]] != null) {
								value = value[props[prop_index]];
							}
Thanks @ozturki 

request @wenzhixin to update the code and merge

**Comment by djhvscf** [comment]
@ozturki / @shows19  could you please share a jsfiddle?

**Comment by shows19** [comment]
@djhvscf  i have created a jsfiddle which contains a null field. when u search it will through **"TypeError: value is null"** error

https://jsfiddle.net/u3wkt06g/1/

Please check

solution: 
 adding the lines on line 1268 solved the issue:

						if (value[props[prop_index]] != null) {
							value = value[props[prop_index]];
						}

**Comment by jimgit** [comment]
Change your data from the STARGAZERS field from -->
 
![image](https://user-images.githubusercontent.com/1921941/35101942-f88f7730-fc26-11e7-9d23-a0cf0e36dc2a.png)

to 

![image](https://user-images.githubusercontent.com/1921941/35101964-1017fc06-fc27-11e7-8422-d40b722ec64f.png)



[Fiddle with data revised](https://jsfiddle.net/jimkennelly/z9uqmjw8/)

**Comment by shows19** [comment]
@jimgit this data is there is to show null value error. data is like this for a reason. search is not working when data contains null object. the solution i have posted will resolve the issue and search will work on the data i have provided.

@djhvscf , @wenzhixin plz check. Thanks

**Comment by djhvscf** [comment]
@shows19 the fiddle provided is not working but please open a PR with an example

**Comment by rayterrill** [comment]
Running into this same issue. Is there a fix or we still need an example?

**Comment by rayterrill** [comment]
The fix specified above works for me too, @wenzhixin. Can we get this folded into the main?

**Comment by shows19** [comment]
@djhvscf 
The fiddle i specified before is still working, please check again

https://jsfiddle.net/u3wkt06g/1/
