### ISSUE TITLE
请教一下，怎么计算某个tr,要显示到可视区域，滚动条应该滚动到什么位置

### ISSUE THREAD

**Issue by weianguo** [wenzhixin/bootstrap-table#2691]
请教一下，怎么计算某个tr,要显示到可视区域，滚动条应该滚动到什么位置
最好是check方法执行后，能自动滚动到可视区域

**Comment by wenzhixin** [comment]
#1346: http://jsfiddle.net/wenyi/yf0u35jL/4/
