### ISSUE TITLE
getSelections Post data

### ISSUE THREAD

**Issue by martinetoye** [wenzhixin/bootstrap-table#2692]
I need a little help with the getSelections function.

I would like to be able to post the data back to a php file so that I can delete a record from the MySQL data base. Any help on how i could achieve this would be great.

**Comment by billzt** [comment]
Well, I was also wonder about this

**Comment by billzt** [comment]
I've found a solution: you should refer to JQuery's ajax post function:

http://www.w3schools.com/jquery/ajax_post.asp

**Comment by airtonjr** [comment]
@martinetoye Hi.

I am using the function below to send and receive from the PHP.

I get the "ids" or "id" for each row and after I just send it to my PHP file.

I am using Jquery/PHP, just to you know.

` function removeRow(table, id_table) {

        var selects = $('#id_' + table).bootstrapTable('getSelections');
        ids = $.map(selects, function (row) {
            var id = id_table;
            return row[id];
        });

        var url = './task.php?action=delete&table=' + table;
        var data = 'id=' + ids.join(',');

        $.ajax({
            url: url,
            data: data,
            cache: false,
            error: function (e) {
                alert(e);
            },
            success: function () {
                $('#id_' + table).bootstrapTable('remove', {
                    field: id_table,
                    values: ids
                });
                dlgSuccessRemove();
            }
        });
    }`

**Comment by martinetoye** [comment]
@airtonjr Apologies I just realised I didn't say thanks for the help. 
Totally worked for me. Cheers

**Comment by wenzhixin** [comment]
Cheers
