### ISSUE TITLE
Additional parameter in JSON source for select?

### ISSUE THREAD

**Issue by peter12333** [wenzhixin/bootstrap-table#2694]
Hi,

this is probably pretty easy to solve, but i can't get it to work.

I have a select field, getting the source data from server side like this:
[{value: 1, text: "someText"}]

Now i'd like to add another parameter:
[{value: 1, text: "someText", moreInfo: "a little bit more info"}]

When i do it like this, the select still works as before, but i can't find a way to access the moreInfo-value.
How would i do it, especially inside the select's success-function?

Thank you!

peter

**Comment by UtechtDustin** [comment]
I close this issue because its almost 3 years old, if you still need help with that please reopen the issue and give us an example where and how do you want to use the more informations.
