### ISSUE TITLE
Issue on italian translation 

### ISSUE THREAD

**Issue by trucall** [wenzhixin/bootstrap-table#2697]
http://jsfiddle.net/trucall/6osrb5qt/

Look at formatShowingRows

It should be

Visualizzazione da 1 a 10 di 30 elementi

I think this is correct:

```
    formatShowingRows: function (pageFrom, pageTo, totalRows) {
        return 'Visualizzazione da ' + pageFrom + ' a ' + pageTo + ' di ' + totalRows + ' elementi ';
    },
```

bye
Tru

**Comment by wenzhixin** [comment]
Can you help to create a PR: https://github.com/wenzhixin/bootstrap-table/tree/develop/src/locale
