### ISSUE TITLE
search and filter

### ISSUE THREAD

**Issue by kismnguz** [wenzhixin/bootstrap-table#2698]
Hi there!

I noticed, if I am using the search and the filter functions of bootstrap table with server side pagination, the request always sent twice, and the filtered text copied into search field.

![image](https://cloud.githubusercontent.com/assets/4705017/19251855/cd4bb44c-8f41-11e6-9084-0c6eafcbd448.png)

For this situation i suspect the 411 th line of  bootstrap-table-filter-control.js file. Could you please check it?
![image](https://cloud.githubusercontent.com/assets/4705017/19251919/16d4ea70-8f42-11e6-9da4-a4506b4419a4.png)

**Comment by ajendrex** [comment]
Hi kismnguz,

I'm having the exact same behaviour, did you manage to solve it? why did you close the issue?

Greetings, 
Hector.

**Comment by velkyel** [comment]
@ajendrex @kismnguz why is issue closed?  I have same issue - what is the solution?

**Comment by kismnguz** [comment]
Hi @ajendrex,

Sorry for the late answer... So I modified the filter-control extension for myself, because had need some other feature.

In your situation I suggest to update the plugin, or try to comment out the marked line.

Hope it helps,
Gergo
