### ISSUE TITLE
The bootstrapTable('destroy') remove all events?

### ISSUE THREAD

**Issue by mfandre** [wenzhixin/bootstrap-table#2703]
I have a question about bootstrapTable("destroy"), it remove all events?

$('#myTable').bootstrapTable('destroy').bootstrapTable({
        url: "someurl",
        locale: 'pt-BR',
        method: 'post',
    }).on('check.bs.table', function (e, row) {
        //code  
    }).on('check-all.bs.table', function (e) {
        //code
    }).on('uncheck-all.bs.table', function (e) {
        //code
    }).on('uncheck.bs.table', function (e, row) {
        //code
    });

Im asking this because when I recreate my events are firing multiple times.

**Comment by wenzhixin** [comment]
Sorry I don't know what events you have listened, you need to use `off` to remove them:
```
.off('check.bs.table').on('check.bs.table', function (e, row) {
//code
})
```

**Comment by Vity01** [comment]
Destroy method should also remove the registered event handlers.
