### ISSUE TITLE
Search terms with wildcards? [feature]

### ISSUE THREAD

**Issue by ZeroDotNet** [wenzhixin/bootstrap-table#2704]
Hi @wenzhixin, 
I'm wondering if it could possible to allow wildcard search using the client-side search, which is terrible good. 
I will try to prepare an extension following multiple-search extension guidelines. 
Should I be prepared to handle any special scenario? 
Thanks for your time.

**Comment by wenzhixin** [comment]
I think you can use `customSearch` option to solve your problem.
