### ISSUE TITLE
Display buggy because td colspan after fixed header

### ISSUE THREAD

**Issue by melvin-github** [wenzhixin/bootstrap-table#2705]
Hi, I want to create table with group for each rows, then I use colspan to merge table and add title which act as group of some rows, and it worked just fine like this
https://jsfiddle.net/vhur12vu/
Everything was OK until I want to make header table fixed with data-height, so it will be able scroll down, but the header just went wrong like this
https://jsfiddle.net/4g3joz6q/
I use latest google chrome if that really important

I use your library for long time, so it will really helpful if you can fix this bug, Thanks in advance

**Comment by wenzhixin** [comment]
Do not support your feature if you want to use height, some like this is supported: https://jsfiddle.net/wenyi/4g3joz6q/1/
