### ISSUE TITLE
Allowing nested fields in group-by-v2 extensions

### ISSUE THREAD

**Issue by kanashin** [wenzhixin/bootstrap-table#2706]
Sorry, after reading the contribution guide I didn't know where exactly to put that.

To allow access to nested fields of data I think we need these changes (based on your work):

I'm talking about this file: [https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/group-by-v2/bootstrap-table-group-by.js](url)
Where we have `a[that.options.groupByField]` (line 62) or `b[that.options.groupByField]` (line 62) or `item[that.options.groupByField]` (line 98) change for 

```
     var props = that.options.groupByField.split('.');
     for (var p in props) {
          if (props.hasOwnProperty(p)) {
              item = item && item[props[p]];
              // for line 62: a = a && a[props[p]];
              // for line 62: b = b && b[props[p]];
          }
     }
     return item;
     // for line 62: return a.localeCompare(b);
```

This is a feature I need so I will be very appreciated it can be inserted in the code, otherwise I will keep it offline.
Thank you and have a nice day.

**Comment by kanashin** [comment]
I see it is also necessary change your lib in order to allow height param.
However, I understand that is little invasive and I don't know how to do from the extension.
ATM I will keep my version offline but it would be cool if it could be in the repository.

line 2120      

    this.$body.find('>tr:first-child:not(.no-records-found) > *').each(function (i) { ...

to something like (I'm not a jQuery expert, so I think it can be done better):

    this.$body.find('>tr:not(.no-records-found):not(.groupBy)').first().find('> *').each(function (i) { ...

**Comment by rodolfosouza** [comment]
please push my fix on branch for nested fields

add this function
Object.resolve = function(path, obj) {
    return path.split('.').reduce(function(prev, curr) {
        return prev ? prev[curr] : undefined
    }, obj || self)
}

After that replace the lines 
from line 64 until 74
     if ((this.options.sortName != this.options.groupByField)) {
                this.data.sort(function(a, b) {
                	if (Object.resolve(that.options.groupByField,a) < Object.resolve(that.options.groupByField,b)) return -1;
            	    if (Object.resolve(that.options.groupByField,a) > Object.resolve(that.options.groupByField,b)) return 1;
            	    if (a[that.options.sortName] < b[that.options.sortName]) return -1;
            	    if (a[that.options.sortName] > b[that.options.sortName]) return 1;
            	    return 0;
                });
            }
and line 75 to 77
 var groups = groupBy(that.data, function (item) {
                return [Object.resolve(that.options.groupByField,item)];
            });

This will reorder correctly and group nested and not nested =)

**Comment by wenzhixin** [comment]
#2773 Please create a new PR

**Comment by kanashin** [comment]
#2987 Done

**Comment by Falseee** [comment]
Both PRs are closed and the issue is already 3 years old, if this feature is need (and is not implemented) pls reopen the issue.
