### ISSUE TITLE
Event handlers in Angular integration

### ISSUE THREAD

**Issue by diogoko** [wenzhixin/bootstrap-table#2707]
It would be useful to bind to events directly in the table element like:

``` html
<table bs-table-control="wk.bsTableControl"
    bs-table-click-row="openItem($event.row)">
</table>
```

This is better than setting `onClickRow` in the table's options because the event handler could execute inside the Angular digest cycle (without having to call `$apply()` explicitly).

I can make a pull request if there is interest.

**Comment by vickyrathee** [comment]
@diogoko  Not sure if owner is interested, but I wanted this to integrate this in my app for edit/delete buttons on each row and clicking on those button trigger the AngularJS function. can you please show an example on JsFiddle ?

**Comment by wenzhixin** [comment]
No longer support angular in the latest release version.
