### ISSUE TITLE
Fixed table inside modal miss calculation

### ISSUE THREAD

**Issue by xyluet** [wenzhixin/bootstrap-table#2710]
http://jsfiddle.net/sp4ek3mc/1/

Is this a bug or something else ? 

But after a search, all going right

**Comment by xyluet** [comment]
any comment ?

**Comment by grunmin** [comment]
try show modal after table been init?

**Comment by xyluet** [comment]
@grummin i have try the shown event modal and that fix the problem. But i consider to load the data first and after finish show the modal. Anyway it's okay, i just have to change my step. Thanks

**Comment by grunmin** [comment]
you may try this
```
  $('.modal-body').change(function(){
        if($('.modal').hasClass('in')){
            setTimeout(function(){
                $('.modal').modal('handleUpdate');
            }, 100);
        }
    });
```

but it's not recommand
