### ISSUE TITLE
data-formatter not working in AngularJS. 用 AngularJS 时 data-formatter 无法正常使用

### ISSUE THREAD

**Issue by shawnngtq** [wenzhixin/bootstrap-table#2713]
`data-formatter` not working when used together with `angular`. 
我用 `angular` 时, `data-formatter` 无法正常使用。

I prefer not to use `bootstrap-table-angular.js`.
如果可以， 我不想用 `bootstrap-table-angular.js`。

stackoverflow: http://stackoverflow.com/questions/40097582/bootstrap-table-data-formatter-not-working-in-angular

[fiddle](https://jsfiddle.net/Shawn_fiddle/3n444r17/)

Thanks. 谢谢。

**Comment by wenzhixin** [comment]
最新版本将不再对 angular 进行支持。
