### ISSUE TITLE
是否能添加treegrid形式的功能

### ISSUE THREAD

**Issue by zhourenfei17** [wenzhixin/bootstrap-table#2714]
如题，是否能开发一个treegrid的功能呢？这个功能用的地方还是蛮多的，类似菜单管理、省市区管理等，但是subgrid的效果对于这种不是特别好，是否能考虑增加一下这个功能呢？

**Comment by yuanrui** [comment]
+1
like this:
http://www.jeasyui.com/demo/main/index.php?plugin=TreeGrid&theme=default&dir=ltr&pitem=

**Comment by wenzhixin** [comment]
可以看下这个 extension：http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/tree-column.html
