### ISSUE TITLE
How to export checkbox value which is generated with data-formatter

### ISSUE THREAD

**Issue by katrina-engelbrecht** [wenzhixin/bootstrap-table#2718]
Hi I want to export table with a checkbox which is generated with data-formatter NOT checkbox setting. 
But in xls file this field is always empty. Can you help me to do that? I want to have "true" or "false" in the exported xls file for this field.

my fiddle:
http://jsfiddle.net/Wei_Engelbrecht/c99jcgom/1/

Thank you very much!

**Comment by CBarratt63** [comment]
I ran into this issue and finally worked out how to do it today. (Presumably you have already done so, but for anyone else searching, hopefully this will help).
The test index.html gives a useful example... https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/index.html  - look for "function DoOnCellHtmlData".

In my case, I had 4 columns with formatted checkboxes in and one column as a standard table checkbox. The code for my table was...

$('#dataRevProcListTable').bootstrapTable({
          showExport: true,
          exportDataType: "all",
          exportTypes: "['pdf','xlsx']",
          exportOptions: { 
                          onCellHtmlData: DoCellData,     // <--- line to setup preprocessing of cell data
                          jspdf: {orientation: "landscape",
                                   margins: {left:10, right:10, top:20, bottom:10 } //,
//                                   autotable: { // styles: {overflow: 'linebreak'},                                              
//                                               drawCell: DoCellData}
                                  }}, 
       etc, etc, etc.....

My DoCellData function was....

function DoCellData($cell, rowIndex, colIndex, htmlData) {
       var retVal = htmlData;
       if (rowIndex > 0) {            // don't process heading row
         if ((colIndex === 6) || (colIndex === 7) || (colIndex === 8) || (colIndex === 9) || (colIndex === 14)) {
           var chkd;
           if ((colIndex === 6) || (colIndex === 7) || (colIndex === 8) || (colIndex === 9)) {
             var chkd = $(htmlData).find('input:checkbox:first').attr('checked'); }
           else {
             chkd = $(htmlData).attr('checked'); }          // column 14 is just a straight textbox in table
           if (chkd) {
             retVal = "yes";  }
           else {
             retVal = " ";  }
           }
         }
       return retVal;
   }

I'll probably neaten this up, but this is now working for me.
Hope that's useful.
