### ISSUE TITLE
remove row table

### ISSUE THREAD

**Issue by LuisAlejandroDuarte** [wenzhixin/bootstrap-table#272]
Buen Dia, quisiera que e ayudaran cuando se elimina el registro de la tabla
$('#tablearea').bootstrapTable('remove', {
                     field: 'GAR_CODI',
                     values: id
            });            
solo elimina cuando id<10
only removed when id <10

**Comment by wenzhixin** [comment]
Sorry, cannot understand you, but I think you needn't to change the code, you can try:
```js
$('#tablearea').bootstrapTable('remove', {
    field: 'GAR_CODI',
    values: [id]
});
```
because values are an array.
