### ISSUE TITLE
GetSelections on sub-table using onExpandRow?

### ISSUE THREAD

**Issue by joekuzma** [wenzhixin/bootstrap-table#2720]
I have a bootstrap-table displaying a tree of two levels of sub-tables using the onExpandRow, but the getSelections only works on the main table.. anything under it, isn't retrievable via code.

Here's a JSFiddle: https://jsfiddle.net/jpkuzma/uag2qa90/3/

Is it possible to grab the selections when they are in a sub-table?

**Comment by trkaplan** [comment]
I've extended getAllSelections() method to find all selected rows in table data (including sub-tables). It has the same code block as getSelections() method. So I think this won't be a problem.
A working sample is here: https://jsfiddle.net/trkaplan/58az2rL5/1/

**Comment by wenzhixin** [comment]
@joekuzma You can use the solution @trkaplan provide.
