### ISSUE TITLE
分页为何没有第一页和最后一页

### ISSUE THREAD

**Issue by ycc3000** [wenzhixin/bootstrap-table#2721]
分页为何没有第一页和最后一页，目前到了最后一页还能继续翻页，但是却翻到了第一页，这个功能看起来很好，不过给用户一种错觉，非常容易出问题，我们需要一个正规的分页<< < 123...789 > >>。

**Comment by wenzhixin** [comment]
之前的版本是正常分页，后面改成现在这种了。看下是否需要保留原来的。

**Comment by chaikenao** [comment]
源码中方法有保留你可以看一下

**Comment by Falseee** [comment]
@wenzhixin i tried to translate it with google but i dont understand it, can you translate the new feature ?

**Comment by wenzhixin** [comment]
@Falseee To retain the functionality of the first and last pages of the previous version, consider adding and using an option to enable this feature.

**Comment by UtechtDustin** [comment]
I understand that the pagination was different in a previous version, but i don't know how it looked before.
Could you give me a  example ?
@wenzhixin @l7xx

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/e3nk137y/44387/

**Comment by UtechtDustin** [comment]
So the only difference are the `<<` and `>>` buttons, right ?

**Comment by wenzhixin** [comment]
Yes, @UtechtDustin .

**Comment by wenzhixin** [comment]
> 分页为何没有第一页和最后一页，目前到了最后一页还能继续翻页，但是却翻到了第一页

看了下，其实现在是有第一页和最后一页，只是用数字表示而已，而翻页的问题设置 `paginationLoop: false` 就可以解决问题了：https://live.bootstrap-table.com/code/wenzhixin/897。

---

In fact, there is the first page and the last page, just use the number to indicate it, and we can set `paginationLoop: false` to solve the problem of page jump.
