### ISSUE TITLE
How can I build a editable table and post the date with something else on the page.

### ISSUE THREAD

**Issue by yech1990** [wenzhixin/bootstrap-table#2722]
I follow the examples and build a editable bootstrap table, in which I can edit each cell and post the row to the server once the editing process was finished. 
However, I need to post the table with other form data on the same page. I try to write a function to get the date on the div(myTable), but I can't get the id for each cell. 
So, I want to know how can I render the current state of bootstraptable into json format.

**Comment by filipesrosa** [comment]
Doesn't `$("#table").bootstrapTable('getData')` retrieve the data?

**Comment by yech1990** [comment]
@filipesrosa  It works!! Thank you~
