### ISSUE TITLE
updateRow with active filter

### ISSUE THREAD

**Issue by filipesrosa** [wenzhixin/bootstrap-table#2723]
An error is thrown when I update a row and apply a filter. `Cannot read property _data of undefined`.

On `initBody()` function, line 1584, we have `data = this.getData();` 
By changing to `data = this.getOptions().data;` no error is thrown.

Is there any other way to solve the problem?

**Comment by filipesrosa** [comment]
@wenzhixin Usually the question is "Can I keep this way? Is it supported?" Thanks!

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!
