### ISSUE TITLE
filterBy method callback with filtered table data

### ISSUE THREAD

**Issue by coffy** [wenzhixin/bootstrap-table#2724]
Hi, 
It would be nice if filterBy could accept callback which would return filtered data
e.g.: 

```
$table.bootstrapTable('filterBy', { foo: 'bar' }, function(result){
    var filtered = result.rows;
});
```

**Comment by filipesrosa** [comment]
@coffy The `getData()` function returns the filtered data, but not as a callback.

`var filtered = $("#table").bootstrapTable('filterBy', {foo: 'bar'}).bootstrapTable('getData');`

**Comment by coffy** [comment]
Thanks, I thought it returns all the data

**Comment by wenzhixin** [comment]
@filipesrosa is right.
