### ISSUE TITLE
AngularJS ng-click on data-formatter button

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#2725]
I'm using angularJS to add, edit, delete rows in my table and the button is added using the built-in `data-formatter`

`
<th compile="details" data-formatter="deleteRowbyId">Action</th>
`

```
function deleteRowbyId(value, row) {
            var content = '<a ng-click="injectedFunction(' + row + ')" class="btn btn-default">Delete</a>';
            return content;
        }
```

But seems the injected HTML is not complied and AngularJS function is not firing when clicked on Delete button. Any suggestion?

**Comment by corneil** [comment]
use `onclick="angular.element(this).scope().injectedFunction('+row+')"`
or `angular.element(this).controller().injectedFunction(`
This depends on whether you assign function to scope or return in map from controller.

**Comment by Shawn-2016** [comment]
How do you use `data-formatter` with angular? I am unable to do that.
[(https://github.com/wenzhixin/bootstrap-table/issues/2713)]
Thanks.
