### ISSUE TITLE
There is any way to declare a CSS row style before insert it?

### ISSUE THREAD

**Issue by jesusignazio** [wenzhixin/bootstrap-table#2726]
```
var rows = [];

rows.push({
    id: id;
    name: name
    css: {"color": "blue", "font-size": "50px"} // <===== Something like this
});

$('#table').bootstrapTable('append', rows);
```

Thanks.

**Comment by dabros** [comment]
Use classnames and pick up on those, or use rowStyle function

Formatter is for columns/cells, http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/format.html, easy conditional styles

rowStyle (and some or all formatters too i think) use either one of the param or 'this' to access row data, so can be conditional too.

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by rahimtit179** [comment]
@dabros How to achieve row color only on duplicate values?

**Comment by wenzhixin** [comment]
@rahimtit179 http://issues.wenzhixin.net.cn/bootstrap-table/#options/table-style.html
```
function rowStyle(row) {
  return row.css;
}
```
