### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by perrin73** [wenzhixin/bootstrap-table#2727]
Hi

 Have you an example for usage of filterData column option ,i don´t know  how to set custom filter values for select...  have you an fiddle example? 

I see the doc but don't understand the way.

Thank you in advance ,sorry for my english.

**Comment by pipiscrew** [comment]
You mean, how to use the default **searchbox** ?

this one will call the predefined .php with the **search** variable

> data.php?offset=0&limit=5&search=t

so on your **server side** code, you have to set a validation like (PHP)

```php$where="";

if (isset($_GET["search"]) && !empty($_GET["search"])) {
   $where='where field_db = {$_GET["search"]}';
    echo "query dbase with the GET";    
}else{  
    echo "default select without where";
}

query_string = "select * from customers {$where}"

**Comment by perrin73** [comment]
thank you for answer but i'm talking about filter-control plugin, in this page you can see it:
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/filter-control

i need an example to understand how to add custom values for the filter select using the filterData column option, here the docu but i don't understand it:
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/filter-control#filterdata

Thanks for any feedback
