### ISSUE TITLE
UPDATE with empty rows

### ISSUE THREAD

**Issue by Fruchtgummi** [wenzhixin/bootstrap-table#2728]
If i update my filled table, with empty rows, will not clear the table and display "No matching records found"?! The old remains.

What I do not understand?

**Comment by pipiscrew** [comment]
use the JS method  **.bootstrapTable('removeAll');**

**Comment by wenzhixin** [comment]
`$table.bootstrapTable('load', []);` or `$table.bootstrapTable('removeAll');`
