### ISSUE TITLE
设置分页状态下,uncheckAll 失效

### ISSUE THREAD

**Issue by qdmall** [wenzhixin/bootstrap-table#2731]
你好,在使用bootstrap-table过程中,发现只要有分页,那么 **uncheckAll** 方法失效,无论是单选还是多选,只能取消掉当前页面的选中项,通过 **$table1.bootstrapTable('getSelections')** 仍然可以获取页面切换前哪一个页面的选中项内容.不知怎么处理? 谢谢!
现在为了这个问题,我已不用分页了.

**Comment by qdmall** [comment]
看了"混合中英文"的文档说明,才发现问题,建议官方中文文档全部是中文的,

**Comment by wenzhixin** [comment]
那你问题已经解决了？假如还有问题重新打开 issue 并提供 jsfiddle，谢谢。
