### ISSUE TITLE
How do I place content next to the 'search box'

### ISSUE THREAD

**Issue by corneil** [wenzhixin/bootstrap-table#2732]
There is a lot of space left to left or right of search box depending on alignment. 

How can I place custom content into that area? 

It would be useful for check boxes or other filter criteria.

**Comment by dabros** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/custom-toolbar.html

that one provides html for its own search box, which seems to get tied in automattically to the search logic (based on id or field name id guess) but you can use custom toolbar and just align it left or right and add some items, see doco for related options

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
