### ISSUE TITLE
can make unique id for row and cell?

### ISSUE THREAD

**Issue by rostyslavnikitin** [wenzhixin/bootstrap-table#2733]
something like that

```
<tr class="text-nowrap" data-index="0"  object-id="213222">
/* It would be great to do so  ->>> */
    <td data-id="somefield_id">value</td>
</tr>

```

i no have access to final html because i use ajax Json data

**Comment by pipiscrew** [comment]
no problem, you just have to fetch the JSON and build the tr+td by javascript then transform it to bootstrap-table, by calling the method **.bootstrapTable()**

provide an example, imagine that the PHP records can come from a ajax call and build there the table (add the HTML5 data attributes as per your need) :
`<?php
$db             = connect();
$recs = getSet($db,"select id,created,seller,total_cost,type from customers", null);
?>


<script>
    $(function() {
					 ///////////////////////////////////////////////////////////// FILL table
					 var jArray_recs =   <?php echo json_encode($recs); ?>;

					 var tbl_recs = "";
					 for (var i = 0; i < jArray_recs.length; i++)
					 {
					 	tbl_recs += "<tr>" +
						"<td>" + jArray_recs[i]["id"] + "</td>" + 
						"<td>" + jArray_recs[i]["created"] + "</td>" +
					 	"<td>" + jArray_recs[i]["seller"] + "</td>" + 
						"<td>" + jArray_recs[i]["total_cost"] + "</td>"
						"<td>" + jArray_recs[i]["type"] + "</td></tr>";
					 }

					 $("#tbl_rows").html(tbl_recs);
					 ///////////////////////////////////////////////////////////// FILL table



					 $("#tbl").bootstrapTable();
					 }) // jQuery ends
</script>

<table id="tbl" data-striped=true>
	<thead>
		<tr>
			<th data-field="id" data-visible="false">ID</th>
			<th data-sortable="true">Created</th>
			<th data-sortable="true">Seller</th>
			<th data-sortable="true">Total Cost</th>
			<th data-sortable="true">Type</th>
		</tr>
	</thead>

	<tbody id="tbl_rows"></tbody>
</table>`

**Comment by HiCodin** [comment]
How can I apply editable attributes to the `td` after adding them like in the code above ?

**Comment by Falseee** [comment]
In the current version its not possible, if you still need it pls reopen the issue and we can discuss if a feature makes sense or not.
