### ISSUE TITLE
bootstrap-table-editable对原有formatter的调用报错

### ISSUE THREAD

**Issue by WinfredMao** [wenzhixin/bootstrap-table#2734]
在我的原有实现中，对需要翻译的字段设置了formatter，表格正常显示：
`<th data-field="empLevel" data-align="center" data-vlign="middle" data-sortable="true" data-formatter="dictsFormatter" data-dict-data="${fn:getDictJson('emp_level_code')}">员工职级</th>`
其中dictsFormatter是定义在JS文件中的function。

在新的需求中，需要将表格转化为可编辑表格，添加`data-editable="true"`后发现报错，原因是在bootstrap-table-editable.js中对原有formatter的调用未考虑此种情况，仅取到了定义的名称字符串`"dictsFormatter"`。
![image](https://cloud.githubusercontent.com/assets/20467550/19756770/82c44278-9c51-11e6-966b-aec0bb5e55e4.png)
![qq 20161027143037](https://cloud.githubusercontent.com/assets/20467550/19756940/81a24fe2-9c52-11e6-926b-e12a23db770c.png)

希望可以修正这个BUG。

**Comment by wow4me** [comment]
我也碰到了这个问题，请问，这个问题现在有解决方案吗？

**Comment by Falseee** [comment]
@winnochan 
Could you provide us a example(jsfiddle) ?

**Comment by wenzhixin** [comment]
Duplicate of #3320
在#3320问题中进行统一处理
