### ISSUE TITLE
check方法不支持输入数据的id是string类型的情况

### ISSUE THREAD

**Issue by fanttm** [wenzhixin/bootstrap-table#2735]
输入数据的id是string类型时，check方法会报错，Uncaught TypeError: Cannot set property 'state' of undefined

http://issues.wenzhixin.net.cn/bootstrap-table/#methods/check-uncheck.html ，下载example后修改其中数据：
1、将data1.json中的id改为string类型，比如id: "1234567"
2、html代码相应修改，$table.bootstrapTable('check', "1234567");
执行即会报错。

**Comment by wenzhixin** [comment]
check/uncheck 的参数是 index，不是 id：
![image](https://cloud.githubusercontent.com/assets/2117018/23111118/6649dd04-f761-11e6-9d0b-5e5702c3c332.png)
http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

你要使用 id 的话需要先算出所在的 `index`

**Comment by fanttm** [comment]
OK
