### ISSUE TITLE
refresh新url翻页问题

### ISSUE THREAD

**Issue by lamzy** [wenzhixin/bootstrap-table#2740]
不知道是不是算bug？
使用了table.bootstrapTable('refresh', { url : newUrl});后，第一页显示的是newUrl查询出来的内容，但是点击第二页，查询地址又变回了原来的url

**Comment by flydrago** [comment]
## 问题吐槽
同样的问题
使用refresh方法设置的url以及参数，再点击第二页时候，都会便会之前的url和参数。
## 替代方案
> 使用refreshOptions方法
```javascript
$('#' + tabId + 'Table').bootstrapTable('refreshOptions', {
        url: refresh_url,
        queryParams: function(params) {
          params.start = start.format('YYYY-MM-DD');
          params.end = end.format('YYYY-MM-DD');
          return params;
        }
      });
```
@lamzy

**Comment by wenzhixin** [comment]
这个问题在最新版本已经修复了：http://jsfiddle.net/wenyi/e3nk137y/25389/
