### ISSUE TITLE
列勾选或取消后，希望浏览器默认保存住

### ISSUE THREAD

**Issue by geeyan** [wenzhixin/bootstrap-table#2741]
平台：Windows 10 64bit
浏览器：谷歌浏览器 54.0.2840.71 m (64-bit)
bootstrap-table版本：1.8.1

列表页，可能需要展示的列较多，且都需要支持展示（在屏幕尺寸有限的情况下，有一些列不需要展示，当前渲染页面时，写入部分列为`data-visible="false"`）。

希望在前台勾选或者取消列时，能保存住当前页面的展示列表，下一次刷新页面能自动勾选并呈现。
![image](https://cloud.githubusercontent.com/assets/4083759/19838006/b53efbce-9f00-11e6-9003-93015a0c70b8.png)

**Comment by grunmin** [comment]
用cookie插件即可

**Comment by geeyan** [comment]
赞。蟹蟹~~
