### ISSUE TITLE
filterBy不生效

### ISSUE THREAD

**Issue by princessJoanna** [wenzhixin/bootstrap-table#2743]

**Comment by wenzhixin** [comment]
没有任何描述？看下这个例子：http://issues.wenzhixin.net.cn/bootstrap-table/#methods/filterBy.html

**Comment by wenzhixin** [comment]
请先用 develop 版本的代码

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/e3nk137y/11682/
