### ISSUE TITLE
How do I chage pagesize with javascript?

### ISSUE THREAD

**Issue by roxma** [wenzhixin/bootstrap-table#2744]
I know I could change page number with `selectPage`. But how do I change the pageSize with javascript?

**Comment by grunmin** [comment]
table.bootstrapTable('refresh', { pageSize : newSize});

**Comment by roxma** [comment]
Not working for me. 

the `params.pageSize` for `queryParams` is still the old value after I trigger a refresh with `table.bootstrapTable('refresh', { pageSize : newSize});`

**Comment by grunmin** [comment]
how about table.bootstrapTable('refreshOptions', { pageSize : newSize});

**Comment by roxma** [comment]
It works! 

Thanks!
