### ISSUE TITLE
Consider the delegate event

### ISSUE THREAD

**Issue by grunmin** [wenzhixin/bootstrap-table#2745]
This is a suggestion, use delegated events may improve performance.

I notice that code like `$el.find('td').on('xxx')` use in many place, when number of rows up to hundreds of thousands, that may caught performance issues. Use `$el.on('xx', 'td')` maybe better?

**Comment by Falseee** [comment]
@djhvscf @wenzhixin 
Does one of you have experiences with it ?
I never benchmarked it or read anything about the performance difference.

**Comment by djhvscf** [comment]
@Falseee see this http://jsben.ch/YnmbR

Anyways, our plan is remove jquery
