### ISSUE TITLE
Editable在列中加入data-formatter报错

### ISSUE THREAD

**Issue by xfdukun** [wenzhixin/bootstrap-table#2748]
在editable的例子中，我在列中加入data-formatter后报错，column._formatter is not a function
`<table id="table"
               data-toggle="table"
               data-pagination="true"
               data-show-export="true"		   
               data-url="../json/data1.json">
            <thead>
            <tr>
                <th data-field="id">ID</th>
                <th data-field="name" data-editable="true">Item Name</th>
                <th data-field="price" data-editable="true" data-formatter="formatter1" data-editable="true" data-editable-emptytext="未设置"
                    data-editable-type="number" data-editable-step="0.01">Item Price</th>
            </tr>`

**Comment by wow4me** [comment]
我也遇到了这个问题，请问，你已经解决了吗？

**Comment by wenzhixin** [comment]
Duplicate of #2734, close this one.
