### ISSUE TITLE
what should I write if I want to fill in the blank in exportOptions?

### ISSUE THREAD

**Issue by xubangbang** [wenzhixin/bootstrap-table#2753]
> exportOptions
> 
> type: Object
> description: export options of tableExport.jquery.plugin
> default: {}

[https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/export#exportoptions](url)
Could you give me an example about how to fill the  _**defult**_?

**Comment by twhetzel** [comment]
One parameter that can used is "filename". 
```
exportOptions: {
        fileName: 'custom_file_name'
    }
```

**Comment by wenzhixin** [comment]
Docs: https://github.com/hhurz/tableExport.jquery.plugin
