### ISSUE TITLE
How to build custom card view?

### ISSUE THREAD

**Issue by TamalSaha** [wenzhixin/bootstrap-table#2754]
Hi,
I am trying to build a data table where I would like to use a custom card view. Essentially I would like a mode where a rowTemplate() function is called every time a row is to be displayed. That function rends the final html using the raw data and return the html. 
![card-view](https://cloud.githubusercontent.com/assets/94814/20051233/d9c37f88-a482-11e6-8cad-46d0fb2b232f.png)

I have attached an example card view. How can I achieve this with bootstrap-table?

**Comment by WalissonPires** [comment]
Today in my position that of the above colleague. There's nothing about it?

Something like a CardFormatter?

**Comment by MrGurns** [comment]
I don't know why this isn't more popular. Having a custom card view in conjunction with hiding the headers would be amazing .

**Comment by wenzhixin** [comment]
@UtechtDustin Can you help to add API and example for [custom-view](https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/custom-view) extension?

**Comment by UtechtDustin** [comment]
@wenzhixin what do you mean with api :-) ?

**Comment by MrGurns** [comment]
I was hoping for some sort of way to just inject straight HTML into the form, Ideally returned with the AJAX or URL response, perhaps put in the data object as data.customView.
This way when switching to the cardView or detail views, it would show custom views

**Comment by wenzhixin** [comment]
@UtechtDustin 
https://bootstrap-table.com/docs/extensions/addrbar/

**Comment by wenzhixin** [comment]
@UtechtDustin Added the docs and example:
* https://bootstrap-table.com/docs/extensions/custom-view/
* https://examples.bootstrap-table.com/#extensions/custom-view.html
