### ISSUE TITLE
Can you add a input field in pagination to manual input  page number

### ISSUE THREAD

**Issue by LuffyChan888** [wenzhixin/bootstrap-table#2755]
when there is too many pages, it is hart to chose the page I want.

eg:
1|2|3|4|5|...|600

if I want to go to page 300, it is hart to do. 

or is there any other better way ?

**Comment by Falseee** [comment]
Could be a good feature, what do you think @wenzhixin @djhvscf ?

**Comment by djhvscf** [comment]
See this example: https://examples.bootstrap-table.com/#methods/selectPage-prevPage-nextPage.html

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/extensions/page-jump-to/
