### ISSUE TITLE
Refresh formatNoMatches

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#2756]
Is there any option i can display a custom dynamic message from my API in "formatNoMatches" instead default 'No matching records found' using the option refresh.

For example ---
- No result found
- Request is in queue right now
- Request is new and never started.
...........
.,........

**Comment by pchaganti** [comment]
👍

**Comment by Falseee** [comment]
Please use [silentSort](https://bootstrap-table.com/docs/api/table-options/#silentsort), while loading the message `Loading, please wait` and a spinner.

**Comment by wenzhixin** [comment]
#1791
