### ISSUE TITLE
Method resetView not compatible with filterControl plugin

### ISSUE THREAD

**Issue by zhangyu911013** [wenzhixin/bootstrap-table#2762]
After successful table rendering with filtercontrol enabled,I trigger the resetView method and set table height to a specific value.
Then whenever I trigger the filter,two http requests are fired and the loading tip fails to show up.
I user server side pagination and filter.
Here's the code:
```
$('#dg').bootstrapTable({
    url:'xxxxxx',
    filterControl: true,
    sidePagination: 'server',
    onLoadSuccess:function(){
         $('#dg').bootstrapTable('resetView', {height: 1000});
    }
})
```
Thanks for reading!

**Comment by Falseee** [comment]
I close this issue because its older than 2 years, if this error still exists pls reopen the issue.
