### ISSUE TITLE
Editable cell according to data-value

### ISSUE THREAD

**Issue by perrin73** [wenzhixin/bootstrap-table#2763]
My question is how to make a non editable cell according a data-value , i need to disable cell editable option in case self  data-value="T" and set editable if data-value="X" .

Sorry for my bad english but i need some help,thanks in advance

**Comment by Falseee** [comment]
I close this issue because its older than 2 years now, if you still need this feature pls reopen the issue.
Then we can discuss if it makes sense to implement an `showEditableFilter`.
