### ISSUE TITLE
tableExport does not export editable fields

### ISSUE THREAD

**Issue by bounlu** [wenzhixin/bootstrap-table#2764]
When tableExport is used on an editable table, it does not export the editable fields`data-editable="true"`, but only the header and the `data-editable="false"` fields.

here is the fiddle: https://jsfiddle.net/arkanion/tutsq0ht/1/ 

any fix for this @wenzhixin ?

**Comment by wenzhixin** [comment]
Fixed in the latest version: https://stackoverflow.com/questions/38834167/values-are-empty-on-editable-columns-while-exporting-bootstraptable
