### ISSUE TITLE
折叠之后想把detail-view留下(隐藏就好)

### ISSUE THREAD

**Issue by chenchuxin** [wenzhixin/bootstrap-table#2765]
因为我的需求是这样的: 点了展开请求，点折叠隐藏，下次点展开的时候看到有请求过了就直接显示。
onCollapseRow事件并未完全控制detail-view，看了代码，是强制性remove~

**Comment by Falseee** [comment]
Does the error still exist ?
Could you provide an example/jsfiddle ?

Also pls translate the issue in english.

**Comment by wenzhixin** [comment]
I think it is the same feature as #1899.
