### ISSUE TITLE
remove row

### ISSUE THREAD

**Issue by fightingm** [wenzhixin/bootstrap-table#2766]
你好，我使用remove方法的时候从后向前删除没有问题，从前往后删除的时候每次还是删除第一个已经被删除的行
`'click .remove': function (e, value, row, index) {
                    var id = row.material_id;
                    $('#table').bootstrapTable('remove', {
                        field: 'material_id',
                        values: [id]
                    });
                    console.log(id);  //这里的id每次都是第行的id
                },`

**Comment by Falseee** [comment]
I close this issue because its older than 2 years now, if this issue still exists and you need help pls reopen it.
Also pls translate it on english.
