### ISSUE TITLE
Header column span cause the table not show in card view layout when browser resize

### ISSUE THREAD

**Issue by LostIndie** [wenzhixin/bootstrap-table#2767]
Hi,

I have a table with header column being merged. When resize browser, the table not show in card view layout. How to make the table show in card view layout with the header columns being merged?

**Comment by wenzhixin** [comment]
I think this issue fixed in the latest version: https://examples.bootstrap-table.com if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
