### ISSUE TITLE
Misaligned fields and title headers

### ISSUE THREAD

**Issue by Landslyde01** [wenzhixin/bootstrap-table#2769]
How can I fix this? Shows the same on Opera, Firefox and Chrome.

![selection_004](https://cloud.githubusercontent.com/assets/18239741/20376702/aa6396f0-ac4e-11e6-8463-5b6b8999b498.png)

To see this issue more in depth, please click [here](http://stackoverflow.com/questions/40644797/bootstarp-table-fields-misaligned-from-header-titles)

**Comment by B-Alvarez** [comment]
Can you help to provide a jsFiddle to show your problem, thanks!

**Comment by B-Alvarez** [comment]
Try: #91
$(function () {
    $('#table').bootstrapTable();
    $(window).resize(function () {
        $('#table').bootstrapTable('resetView');
    });
});

**Comment by Landslyde01** [comment]
Crazy thing! I uploaded the file (a partial file for testing) and it WORKS. Yet it won't work on my localhost. Take a [look](https://www.dfwit.co/bootstrap-table.php). Any idea why this might be failing on my local box and working on my website? THAT's a puzzler.

**Comment by B-Alvarez** [comment]
Try clear your browser's cache.
