### ISSUE TITLE
Feature: Hiding/showing empty rows when hiding/showing columns

### ISSUE THREAD

**Issue by vongdarakia** [wenzhixin/bootstrap-table#277]
When hiding columns, there may be rows with empty data. It would be nice to be able to hide these rows when if they don't apply to the current shown columns.

For example.

Table A : Original

       1  2  3  product
    1  x  -  -  1
    2  -  x  -  4
    3  -  -  x  9

Table B : Hiding Column 2 (What it currently looks like)

       1  3  product
    1  x  -  1
    2  -  -  4
    3  -  x  9

Table C : Hiding Column 2 (What the feature would do)

       1  3  product
    1  x  -  1
    3  -  x  9

And a method to get data of visible data would be awesome as well.

**Comment by wenzhixin** [comment]
Thanks for your advice, but I think this feature is better to handle manually. You can use `showRow` or `hideRow` now.
