### ISSUE TITLE
为什么添加一行刷新整个table，怎么处理这个刷新不让刷新。会把原有的数据刷新为原始数据。

### ISSUE THREAD

**Issue by kanggaoyang** [wenzhixin/bootstrap-table#2770]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by Falseee** [comment]
If i understand the translated title (google translator) correct, you ask why the whole table is relaoded after adding a row.
So the answer is that we need to refresh the table to apply formatters and sort the new row correct.

If i understand something wrong and you still need help then pls describe the issue in english and reopen the issue.
