### ISSUE TITLE
string of json fomat can't display normally

### ISSUE THREAD

**Issue by xiongsenlin** [wenzhixin/bootstrap-table#2775]
when use the bootstrap-table-editable.js， if a field's value is a string of json format, something like "{}",
it can't display normally, the display values is: [object Object]

**Comment by Falseee** [comment]
@wenzhixin @djhvscf Can one of you check if this is a error of the bootstrap-table or of the xeditable plugin ? I dont have so much experience with the editable extension.

**Comment by djhvscf** [comment]
@xiongsenlin Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Two working examples to fix this problem:
http://jsfiddle.net/wenyi/e3nk137y/44360/
http://jsfiddle.net/wenyi/e3nk137y/44362/

**Comment by wenzhixin** [comment]
If the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
