### ISSUE TITLE
Filter Control overwrites "search" parameter in API call

### ISSUE THREAD

**Issue by Bakke** [wenzhixin/bootstrap-table#2776]
With both "search" and Filter Control enabled, Filter Control will overwrite the "search" parameter sent to server/API.

Enable search and filterControl
Search for something (not using Filter Control)
Search for something using Filter Control

The last search will now populate both "filter" and "search" parameter sent to API/server. The original search is lost (but still populating the search input field).

**Comment by wenzhixin** [comment]
Fixed in #4624
