### ISSUE TITLE
sidePagination server, sort and pagination

### ISSUE THREAD

**Issue by developaspeur** [wenzhixin/bootstrap-table#2781]
Hello,

I have a problem between sidePagination: server option and the column sort and pagination.
Pages rows are charged only when the number is clicked.
The sort is wrong and is not applied normally...

That I want for asc : ["page 1": [1,2,3], "page 2": [4,5,6]]
That I want for desc : ["page 1": [51,50,49], "page 2": [48,47,46]]

Result for my asc (bad) : ["page 1": [49,50,51], "page 2": [46,47,48]]
Result for my desc (good) : ["page 1": [51,50,49], "page 2": [48,47,46]]

So, actually, the results for asc sort only works on the current page of pagination... strange, no?

I've tried to create a custom sorter, like the doc, but it's not called with server side option.

Thanks a lot for your help.

And sorry for my bad english, but i'm french :p

Edit : In asc and in desc, results are sorted page by page and not all the table

Edit 2 : on http://issues.wenzhixin.net.cn/bootstrap-table/ the problem is exactly the same (ex : sort on "Item Name")

**Comment by Falseee** [comment]
Works fine in the newest version (http://issues.wenzhixin.net.cn/bootstrap-table/).
If you still need hel with that pls reopen the issue.
