### ISSUE TITLE
refresh button is more small than oher

### ISSUE THREAD

**Issue by ns7381** [wenzhixin/bootstrap-table#2783]
![qq 20161123092345](https://cloud.githubusercontent.com/assets/5730585/20548461/9122ec8a-b15e-11e6-9c6f-0db0ebcaa230.png)

**Comment by martinburch** [comment]
It looks fine here: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html

I think you may have some other CSS on your page that's causing the problem. These are standard bootstrap icons, so if you are overriding bootstrap styles, that could be the issue.

**Comment by djhvscf** [comment]
@ns7381 review the comment of @martinburch
