### ISSUE TITLE
Creating table with vertical headings using JSON data

### ISSUE THREAD

**Issue by xennygrimmato** [wenzhixin/bootstrap-table#2784]
I want to create a table in which the headings are written on the left side - column 1 of the table represent the headings and the row represents the data of that heading.
This is what my table looks like: [jsFiddle](http://jsfiddle.net/nw1u4847/1/)
I have used `bootstrapTable({data: JSON_DATA})` to create tables before, but not of this format. 

How do I create such a table using bootstrap-table directly using JSON data?

**Comment by feganmeister** [comment]
Does [data-card-view](http://jsfiddle.net/wenyi/e3nk137y/27/) not meet this requirement?

**Comment by djhvscf** [comment]
@xennygrimmato  please check the @feganmeister's answer
