### ISSUE TITLE
Filter Control Length

### ISSUE THREAD

**Issue by nicholasrpb** [wenzhixin/bootstrap-table#2786]
Hi Expert,

What is the maximum filter control type select can take it?

I have this error message:
bootstrap-table-filter-control.min.js:7 Uncaught TypeError: Cannot read property 'length' of undefined(…)

Is there any workaround for this? Currently i change type to input but it will be useless since i have search function as well.

Regards,
Nicholas

**Comment by Falseee** [comment]
There is no limit, because we just add options to the select.
Also the error message didnt said that there is a limit, the real issue is that the javascript tried to call the length function on undefiend.

If you still (after 2 years) need help with that pls provide us an example(jsfiddle).
