### ISSUE TITLE
Is it possible to not render table after hiding column?

### ISSUE THREAD

**Issue by luisapuyen** [wenzhixin/bootstrap-table#2787]
I need to code something like this: just when I get json data loaded from server (anytime I use a filter), I need to programmatically hide columns where there are no values in its last row, which are totals (that indicates the whole column has no values).

I used these methods: showAllColumns, getVisibleColumns and hideColumn.
BTW: I got an error on line 2802, in method toggleAllColumns. I had to change:

```
        $.each(this.columns, function (i, column) {
            this.columns[i].visible = visible;
        });
```

to 

```
         $.each(this.columns, function (i, column) {
             column.visible = visible;
        });
```

The problem I have is everytime I hide a column, the table is re-rendered again. Since there are always many columns that must be shown or hidden, the browser gets eventually frozen.

This is the script I created to accomplish it:

```
"use strict";
+function($) {
	$(function() {
		var $tabla = $('table.tabla-bootstrap'),
			resetColumnas = function() {
				$tabla.bootstrapTable('showAllColumns');
			},
			ocultarColumnas = function(datosTotales) {
				var columnas = $tabla.bootstrapTable('getVisibleColumns');
				$.each(columnas, function(index, columna) {
					if (datosTotales[columna.field] === undefined) {
						$tabla.bootstrapTable('hideColumn', columna.field);
					}
				});
			};
		
		$tabla.on('load-success.bs.table', function(e, data) {
			try {
				// Restore all columns first
				resetColumnas();
				// Hide those without value in their last row (totals)
				ocultarColumnas(data[data.length - 1]);
			}
			catch(error) {
				console.log(error.message);
			}
		});
	});
}(jQuery);
```

Is there anything I can do, like not re-rendering the table until I explicitly run it?

**Comment by Falseee** [comment]
There is no way to disable the re-rendering of the table.
You could use the filterBy function with a custom filter alogorythm as soon as #4230 is merged.

If i understand something wrong or you have a other question pls reopen the issue.
