### ISSUE TITLE
页码部分，如何隐藏掉具体各页数字，只显示“上一页”、“下一页”按钮？

### ISSUE THREAD

**Issue by longnight** [wenzhixin/bootstrap-table#2788]
设置为服务器端分页。数据量小的时候，服务端计算总页码没什么问题，
当数据量上千万的时候，分页计算总量就太过昂贵了，但是仅给出 "has_next": true , "has_prev": false 也是可以接受的， 那么 bootstrap-table 应该如何设置才能做到如标题这样呢？

**Comment by wenzhixin** [comment]
目前不支持，不过你可以先通过css将分页的数字隐藏起来处理

**Comment by wenzhixin** [comment]
目前不支持，不过你可以先通过css将分页的数字隐藏起来处理

**Comment by lion1120lion** [comment]
请问这个解决了？
