### ISSUE TITLE
可以修改分页详细显示内容么？

### ISSUE THREAD

**Issue by cmdbdu** [wenzhixin/bootstrap-table#2789]
如图：
![image](https://cloud.githubusercontent.com/assets/2585719/20593925/24b20e3e-b26f-11e6-832f-a5c81006e354.png)

我想显示的格式是：

（1-20）/2709   每页显示20条记录
（21-40）/2709   每页显示20条记录

tks ：）

**Comment by wenzhixin** [comment]
可以的，你设置 `formatShowingRows(pageFrom, pageTo, totalRows)`就行，详细见文档或例子
