### ISSUE TITLE
超多列布局的问题

### ISSUE THREAD

**Issue by tianqiangly** [wenzhixin/bootstrap-table#279]
超多列时会出现水平滚动条，但是最后一列的内容会显示不全，大概只显示了60%，如果行也超多(出现垂直滚动条)时，最后一列的显示是没问题的。我使用的是最新版本(1.40)，不知是我测试的问题还是本身就存在这个问题，在此询问一下，谢谢。。

**Comment by wenzhixin** [comment]
该bug已经解决
