### ISSUE TITLE
使用 bootstrap-table  必须引入bootstrap的css吗？

### ISSUE THREAD

**Issue by liuyouth** [wenzhixin/bootstrap-table#2790]
http://bootstrap-table.wenzhixin.net.cn/zh-cn/getting-started/
 我单独引入了

 “//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css“

数据并不能显示出来，需要在引入 

 “ //cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css“
才能显示出来， 这样的话 会打乱我的样式，我并不需要 全部的bootstrap css

**Comment by wenzhixin** [comment]
要的，因为是基于bootstrap进行开发的
