### ISSUE TITLE
footerFormatter issue. function name is displayed instead of function output

### ISSUE THREAD

**Issue by rgogada** [wenzhixin/bootstrap-table#2793]
here is my relevant code. 

`$.get(url, function(response){  

              var data = response.split('~')

              var columns = JSON.parse(data[0])            
              var rows = JSON.parse(data[1])

              $("#table").bootstrapTable('refreshOptions',{
                columns: columns,
                data: rows,
                classes: "table table-striped",
                toolbar: "#toolbar",
                search:"true",
                showColumns:"true",
                showExport: "true",
                pagination:"true",
                pageSize:"15",
                showFooter: "true"
              })
            })
            
            function calTotals(data){
              field = this.field;
              var total_sum = data.reduce(function(sum, row) {
                  return (sum) + (row[field] || 0);
              }, 0);
              return total_sum;
            }`

`function ajaxResponse($sql){
    
    $result = mysql_query($sql) or die("Query - " . $sql . " failed. mysql_error says - " . mysql_error()); //Query execute 
    $num_rows = mysql_num_rows($result);
    $num_columns = mysql_num_fields($result); 
    $totals = [];
    $columns = '';
    $data = [];
    
    while ($row = mysql_fetch_array($result)) {
      
      $num_rows --;
      for ($i = 0; $i < $num_columns; $i++) {
        $totals[$i]  += $row[$i] ;
        
        if ($num_rows == 1) {
          $field = mysql_fetch_field($result, $i);
          $align = $field->type == "real" ? ', "align": "right"' : '';
          $footerFormatter = $align != '' ? ', "footerFormatter": "calTotals"': '';
          $columns .= '{"field": "' .$field->name. '", "title": "' .$field->name. '" ' .$align. $footerFormatter. "},";
        }
      }
    }
    
    mysql_data_seek($result, 0) ;
    
    while ($row = mysql_fetch_assoc($result)){
      $data[] = $row;
    }
    
    echo '['.substr($columns,0,-1).']';      
    echo  '~'. stripslashes(json_encode($data, JSON_NUMERIC_CHECK));
  }`

**Comment by bennyjo** [comment]
You might be experience the same issue as the one described here:
https://stackoverflow.com/questions/45190917/bootstrap-table-footer-functions-not-working-data-footer-formatter/45193022#45193022

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/#options/show-footer.html
