### ISSUE TITLE
Bootstrap Datepicker

### ISSUE THREAD

**Issue by Landslyde01** [wenzhixin/bootstrap-table#2797]
Is there a plugin to pull up a datepicker like calendar in bootstrap-table cells?

**Comment by B-Alvarez** [comment]
Example: http://jsfiddle.net/wenyi/e3nk137y/2435/

**Comment by Landslyde01** [comment]
To add to this, the answer is found [here](http://vitalets.github.io/x-editable/demo.html?c=inline).
