### ISSUE TITLE
Color individual cells?

### ISSUE THREAD

**Issue by Landslyde01** [wenzhixin/bootstrap-table#2798]
Using regular Bootstrap tables, I can easily alter the color of individual cells.

![selection_015](https://cloud.githubusercontent.com/assets/18239741/20662268/5e8a38f6-b518-11e6-9313-cd322e4e6185.png)

Is this possible with this bootstrap-table? If so, how can it be done? Thanks.

**Comment by B-Alvarez** [comment]
https://github.com/wenzhixin/bootstrap-table/issues/221

**Comment by Landslyde01** [comment]
Perfect.
