### ISSUE TITLE
Wrong group field values in group-by-v2

### ISSUE THREAD

**Issue by mabigo** [wenzhixin/bootstrap-table#2799]
When using 2 bootstrap-tables (with different json sources) on a single page with group-by-v2 extension, group field values are incorrect/mixed.

**To reproduce:**
1. create page with at least 2 bootstrap-table instances
2. enable group-by-v2 extension
3. use pagination or search for problem to occur.

**Example:**
https://s21.postimg.org/u5yhk723r/bootstraptable_groupbug.png

**Comment by Falseee** [comment]
I close this issue because its older than 2 years, if you still need help pls provide us an workding example(jsfiddle).
