### ISSUE TITLE
Bug in table header rendering

### ISSUE THREAD

**Issue by crazyguyonabike** [wenzhixin/bootstrap-table#280]
I have local nv.d3.css and nv.d3.min.js dated Aug 27. There is no version in the .css or .js. Using the local stuff, header renders fine:

![screen shot 2014-11-25 at 7 53 58 pm](https://cloud.githubusercontent.com/assets/648128/5196122/e0ec9b3c-74dc-11e4-842d-09011dbbb94e.png)

Pulling the latest from github does not render correctly:

![screen shot 2014-11-25 at 7 56 02 pm](https://cloud.githubusercontent.com/assets/648128/5196134/24d051fe-74dd-11e4-961e-0b9fe1b6fd14.png)

My table is defined as in the example:

    <table id="example" data-cache="true" data-height="299">
    <thead>
        <tr>
            <th data-field="domain">Domain</th>
    .
    .
    .
        </tr>
    </thead>
    </table>

And the contents of the `<th>` are `<img>`'s with local images.

**Comment by wenzhixin** [comment]
Update to the latest code and try it again, I think this issue would be fixed, close it.
