### ISSUE TITLE
What is wrong with this code?

### ISSUE THREAD

**Issue by Landslyde01** [wenzhixin/bootstrap-table#2800]
field: 'balance',
    title: 'Balance',
    align: 'left',
    valign: 'middle',
    sortable: true,
    editable: false,
    cellStyle: function(value) {
        if ( value >= 1 ){
            return {
                css: {
                     'background-color': 'red';
                }
            }
        };
    }
I want any cell with a value > 0 to be red. This code crashes.

**Comment by B-Alvarez** [comment]
function(value) {
    if ( value >= 1 ){
        return {
            css: {
                 'background-color': 'red'
            }
        };
    }
}

**Comment by Landslyde01** [comment]
Thanks, B-Alvarez. Removing the semi-colon solved the crashing, but no cells` >= 1 ` turn red.

**Comment by B-Alvarez** [comment]
Check the data type is numeric or string example: 1 or '1' or "1" .Impresses the data type.
This is just to discard.

**Comment by B-Alvarez** [comment]
cellStyle(value, row, index)

The function receive three parameters.

```
function(value, row, index) {
     if ( value >= 1 ){
         return {
             css: {
                  'background-color': 'red',
             }
         };
     }
 }
```

**Comment by Landslyde01** [comment]
My data type for that field is numeric. So I have it right. And i put in the `row` and `index` parameters with no luck. Still no red cells. 
I was really happy when i came across this bootstarpTable. It comes with a lot that works right out of the box: sorting, search, etc. But that I can't get a cell to color for me is disappointing. Very disappointing.

**Comment by B-Alvarez** [comment]
```
cellStyle: function(value, row, index){
if (value >= 1){
    return {
             css: {
                  'background-color': 'red',
              }
         }; yes here
     }; not here
}
```
Your problem is ";"
