### ISSUE TITLE
How to set page number on the basis of Limit and offset in Wenzhixin bootstrap table 

### ISSUE THREAD

**Issue by alok12p74** [wenzhixin/bootstrap-table#2803]
I have a editable table with  custom edit page .I  have problems in update page ,we set offset in session and before showing data get my offset value from session and show data of that page  .

Problem is that offset work fine and show data of that page **but pagination number is not that number** .

Example = i am at page 3 and and edit that column and update .After update it show same page but page number is always 1 .

Thank you for Any suggestion

**Comment by wenzhixin** [comment]
Have you solved your problem? If not, please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Falseee** [comment]
I close this issue because its older than 2 Years, also we got no response from you.
If you still need help pls reopen this issue.
