### ISSUE TITLE
Can't hideRow with uniqueID

### ISSUE THREAD

**Issue by tylerecouture** [wenzhixin/bootstrap-table#2807]
I'm trying to hide a row based on its id field, and I can't get it to work.  Docs say I shoudl be able to use `uniqueId`.

> Hide the specified row. The param must contain **at least one of** the following properties: index: the row index. **uniqueId: the value of the uniqueId for that row**.

Here's a fiddle showing the problem:
http://jsfiddle.net/43Tesseracts/3n5q7ax4/

**Comment by trkaplan** [comment]
You need to add unique id attribute to each row. 
Here is the working example:
http://jsfiddle.net/trkaplan/b3ogLfhm/1/ 
Documentation has `data-unique-id` value in the attribute column but this attribute doesn't work when you use it with `hideRow()` method. It must be changed with `data-uniqueid`

**Comment by Falseee** [comment]
https://bootstrap-table.com/docs/api/table-options/#uniqueid
