### ISSUE TITLE
Howto add a detailview without an external json datafile

### ISSUE THREAD

**Issue by Benevdw** [wenzhixin/bootstrap-table#2814]
I'm trying to use the detailview functionality to be able to publish a collapsable row in a table just in between the 'normal' table rows containing the regular data.
I'm trying to avoid the use of an external json file as I was able to view the normal table data as shown below (it's a twig example btw)
I though that adding another <tr> would fix the problem, but I cannot seem to get it working.  Any ideas?

					

```
{% for item in calendar %}
	<tr>
		<td>{{item.nameProject}}</td>
		<td><span class="label label-primary">{{ item.languagePubl }}&nbsp;</span></td>
		<td><a target="_blank" href="https://www.google.com/maps/place/{{item.streetCompany}}, {{item.postcodeCompany}}, {{item.countryCompany}}">{{item.nameCompany}}</a></td>
		<td>{{item.dBegin|date("d/m/Y")}}</td>
		<td><a href="{{entry.url}}/{{item.keyAction}}" class="btn btn-black btn-small">{{"Data"|t}}</a></td>
	</tr>
{% endfor %}
```

**Comment by Falseee** [comment]
Use the [detailFormatter](https://bootstrap-table.com/docs/api/table-options/#detailformatter).
