### ISSUE TITLE
Display none with pagination on server

### ISSUE THREAD

**Issue by torisoft** [wenzhixin/bootstrap-table#2815]
Hi
After i use pagination on server do not display all records. json data posted but display is none.

**Comment by amitkm2603** [comment]
hey @torisoft ,

Please make sure that the returned json is in the following format: 

{
"total": row_count,
 "rows": json_data
}

**Comment by torisoft** [comment]
Hi @amitkm2603 
Yes that is same format.

**Comment by LoganDepp** [comment]
Hi,I had this problem too.Did you solved the problem?

**Comment by torisoft** [comment]
Hi @amitkm2603 
Thanks. This is it. Actually with exactly name "total" and"rows".
