### ISSUE TITLE
IE11下refresh button点击无反应

### ISSUE THREAD

**Issue by CodingPandaKing** [wenzhixin/bootstrap-table#2816]
请在IE11 环境下查看 http://issues.wenzhixin.net.cn/bootstrap-table/

点击refresh button  ,  查看是否发送请求 ，重新加载数据

**Comment by wenzhixin** [comment]
IE下应该是缓存问题

**Comment by Wahitler** [comment]
那应该怎么解决呢？我在Url后边加随机时间戳不管用，即使加上了随机数或者时间戳，refresh的时候都是同一个url

**Comment by Wahitler** [comment]
哦，是在这里加啊，，，作者写的这个真好给赞
![qq 20161227175039](https://cloud.githubusercontent.com/assets/12858618/21496967/2ff26fca-cc5d-11e6-9b68-364b7895874b.png)

**Comment by wenzhixin** [comment]
你设置 `cache: false` 试试，或者后台设置 `cache-control: 'no-cache'`

**Comment by CodingPandaKing** [comment]
已解决 ， 谢谢 ， 设置 data-cache="false" 就可以
建议把官网例子 也加上

**Comment by Wahitler** [comment]
@wenzhixin 那就有问题了，文档写的有错误啊作者
![qq 20161228113206](https://cloud.githubusercontent.com/assets/12858618/21513272/7a4700a6-ccf1-11e6-97c4-753ae2c4e3c7.png)
