### ISSUE TITLE
分页栏无法显示

### ISSUE THREAD

**Issue by LoganDepp** [wenzhixin/bootstrap-table#2818]
我设置了pagination: true，但是下方的分页栏无法显示，并且找不到报错，参数传递也是正常的，数据也能获取，只是没法分页。
有人遇到过这个问题吗？

**Comment by jack-luj** [comment]
贴出代码看看

**Comment by LoganDepp** [comment]
这是初始化table。
var TableInit = function () {
 var oTableInit = new Object();
 //初始化Table
 oTableInit.Init = function () {
  $table.bootstrapTable({
   url: 'http://localhost:9888/cattle-webapp/admin/viewSharedOrder.do',   //请求后台的URL（*）
   method: 'post',      //请求方式（*）
   height: 600,
   contentType:"application/x-www-form-urlencoded",
   toolbar: '#toolbar',    //工具按钮用哪个容器
   striped: true,      //是否显示行间隔色
   dataType: "json",
   sortable: false,      //是否启用排序
   sortOrder: "asc",     //排序方式
   queryParams: oTableInit.queryParams,//传递参数（*）
   pagination: true,     //是否显示分页（*）
   sidePagination: "server",   //分页方式：client客户端分页，server服务端分页（*）
   cache: true,      //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
   pageNumber: 1,
   pageSize: 10,      //每页的记录行数（*）
   pageList: [10, 25, 50],  //可供选择的每页的行数（*）
   search: true,      //是否显示表格搜索，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
   strictSearch: true,
   showColumns: true,     //是否显示所有的列
   showRefresh: true,     //是否显示刷新按钮
   minimumCountColumns: 2,    //最少允许的列数
   clickToSelect: true,    //是否启用点击选中行
   uniqueId: "ID",      //每一行的唯一标识，一般为主键列
   showToggle:true,     //是否显示详细视图和列表视图的切换按钮
   cardView: false,     //是否显示详细视图
   detailView: false,     //是否显示父子表
   columns: [{
    checkbox: true

这是查询参数。
//得到查询的参数
 oTableInit.queryParams = function (params) {
  var temp = { //这里的键的名字和控制器的变量名必须一直，这边改动，控制器也需要改成一样的
   pageSize: params.limit, //页面大小
   pageIndex: params.offset, //页码

结果可以正常展示在表格里，只是右下方的分页条没有显示。大神帮忙看看！@jack-luj

**Comment by wenzhixin** [comment]
假如你的数据条数小于最小的分页数，会自动将分页栏隐藏起来，你可以设置smartDisplay为false，就会一直显示。

**Comment by LoganDepp** [comment]
设置smartDisplay为false就显示了，谢谢~

**Comment by Suntianbao** [comment]
您好，我是初学者～我这里是数据条数大雨最小的分页数，但是仍然不显示，而且就算数据很多也只会显示默认的10条

**Comment by wenzhixin** [comment]
@Suntianbao  提供下例子

**Comment by Suntianbao** [comment]
> @Suntianbao 提供下例子
> Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

 $('#bootstrap-table').bootstrapTable({
                    url: options.url,                                   // 请求后台的URL（*）
                    contentType: "application/x-www-form-urlencoded",   // 编码类型
                    method: 'post',                                     // 请求方式（*）
                    cache: false,                                       // 是否使用缓存
                    sortable: true,                                     // 是否启用排序
                    sortStable: true,                                   // 设置为 true 将获得稳定的排序
                    sortName: _sortName,                                // 排序列名称
                    sortOrder: _sortOrder,                              // 排序方式  asc 或者 desc
                    pagination: $.common.visible(options.pagination),   // 是否显示分页（*）
                    pageNumber: 1,                                      // 初始化加载第一页，默认第一页
                    pageSize: 10,                                       // 每页的记录行数（*） 
                    pageList: [10, 25, 50],                             // 可供选择的每页的行数（*）
                    iconSize: 'outline',                                // 图标大小：undefined默认的按钮尺寸 xs超小按钮sm小按钮lg大按钮
                    toolbar: '#toolbar',                                // 指定工作栏
                    sidePagination: "server",                           // 启用服务端分页
                    search: $.common.visible(options.search),           // 是否显示搜索框功能
                    showSearch: $.common.visible(options.showSearch),   // 是否显示检索信息
                    showRefresh: $.common.visible(options.showRefresh), // 是否显示刷新按钮
                    showColumns: $.common.visible(options.showColumns), // 是否显示隐藏某列下拉框
                    showToggle: $.common.visible(options.showToggle),   // 是否显示详细视图和列表视图的切换按钮
                    showExport: $.common.visible(options.showExport),   // 是否支持导出文件
                    queryParams: $.table._params,                       // 传递参数（*）
                    columns: options.columns,                           // 显示列信息（*）
                    responseHandler: $.table.responseHandler            // 回调函数
                });
            },
 // 请求获取数据后处理回调函数
            responseHandler: function (res) {
                if (res.code == 0) {
                    return {rows: res.rows, total: res.total};
                } else {
                    $.modal.alertWarning(res.msg);
                    return {rows: [], total: 0};
                }
            },

您好～将bootstrapTable封装后使用，设置的是在服务端分页，但是每次分页都不成功，我看了一下浏览器那里返回的数据，数据库里一共有15条数据，返回的total应该为15，但是每次返回的都是10，我猜测这才是不显示分页的原因，因为total 的值并没有大于10，当按下排序的图标时，会进行排序，并返回按正序或者倒序的的10条结果，这里怀疑可能是mapper.xml文件有问题，但是也没有找到具体是什么原因，可以的话请您帮忙分析一下，十分感谢

**Comment by Suntianbao** [comment]
> @Suntianbao 提供下例子
> Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

您好～问题已经解决了～原因我解释一下，也可以给搜索到这条消息的人一些启示，
@RequiresPermissions("system:patient:listUnConfirmed")
    @PostMapping("/listUnConfirmed")
    @ResponseBody
    public TableDataInfo listUnConfirmed(Patient patient) throws Exception {
        startPage();
        List<Patient> list = patientService.selectPatientList(patient);
        Iterator<Patient> iterator = list.iterator();
        //减少的
        int length = 0;
        while (iterator.hasNext()) {
            Patient temp = iterator.next();
            if(temp.getDepartment() != null){
                iterator.remove();
                length++;
            }
        }
        List<Patient> result = new ArrayList<>();
        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getDepartment() == null) {
                list.get(i).setDepartment("");
                result.add(list.get(i));
            }
        }
        System.out.println("listUnconfirmed length: "+length);
        return getDataTable(list,length);
    }

我这里之前返回的是getDataTable(result,length)，因为默认得到的数据最多是10条，当时为了方便省事而对原始数据list进行处理得到result，但是这样会改变返回的total的值，total是代表所有信息的条数的，比如某个表有100条数据，返回的就是total就应该是100，bootstrap只有大于默认值10才可以分页，此外如果新建一个result，那么这个result就不是属于page类了，就会走else的部分，最多有默认的10条数据，也就不会进行分页了，这里猜测分页多少就是利用total的值进行判断的，实测之后确实如此。所以不要轻易改变返回的内容，我是这样理解的，欢迎随时来问哈～
---------这是设置total的核心代码-------------
public PageSerializable(List<T> list) {
        this.list = list;
        if (list instanceof Page) {
            this.total = ((Page)list).getTotal();
        } else {
            this.total = (long)list.size();
        }
-------------------------------------------------

    }
