### ISSUE TITLE
how to make reset on offset when new filter is applied?

### ISSUE THREAD

**Issue by kirilmicev** [wenzhixin/bootstrap-table#282]
now when you apply new filter parameters for offset is send the current offset and if it is 20 the sql on server side can not be made correctly.
is it possible to reset the offset to 0 when this is clicked?

![](http://i.imgur.com/es6VWe7.png)

**Comment by maxgrass** [comment]
which offset do you mean? could you please try to rephrase the issue, provide steps to reproduce it or write a small jsfiddle?

**Comment by wenzhixin** [comment]
Hi @kirilmicev, I think you can use `queryParams` to rest the offset, close this issue.

**Comment by anupalusoft** [comment]
Can i reset the offset to 0 on Table refresh? `('refresh')`
