### ISSUE TITLE
Reordering columns and hide/showing through the data-columns=true hides the wrong table heading

### ISSUE THREAD

**Issue by aberkowgg** [wenzhixin/bootstrap-table#2820]
Reordering columns and hide/showing through the data-columns=true hides the wrong table heading

**This can be reproduced on your demo:** 
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-columns.html
(Any browser, but I tested on chrome)

**Setup on the code side: data-show-columns="true", data-reorderable-columns="true"**

Step 1 - Drag/Reorder 'Item Name' column one space to the left. The order will now be 'Item Name', 'ID', 'Item Price'.

Step 2 - Click on the dropdown-toggle and uncheck 'Item Name', to HIDE this column. The result will be the heading 'ID' will disappear, but the 'Item Name' heading will still display. Than the columns that belonged to Item Name in the table-body will disappear.

Step 3 - Click on the dropdown-toggle and uncheck 'Item Name', to SHOW this column. The result will be the first column displayed will have the heading 'Item Name', but the data will be the data for ID. The second column will have the heading 'ID', but have the data for Items Name.

Following these steps the expected result would be 'Item Name' heading and data to be in the first column, than 'ID' heading and data in the next column.

(https://github.com/wenzhixin/bootstrap-table/issues/1765)).

I noticed this bug on my companies application in all 3 major browsers. When I was able to reproduce on the demo you guys provide, I realized the bug must either be in the reorder-columns extension or the part of the base code that defines logic for data-columns=true.

Thank you guys for investigating this issue.

**Comment by aberkowgg** [comment]
Figured this one out, just needed to edit bootstrap-table-reordercolumn.js.

Add these lines to the end  of makeRowsReorderable.dragtable({beforeStop : function(){....}), function. 

....that.trigger('reorder-column', ths);
                that.initTable();
                that.initHeader();
                that.initToolbar();

**Comment by the-gigi** [comment]
Hello @aberkowgg ,
I ran into the same issue. Great job on figuring it out. Will you consider submitting pull request? There are 430 open issues and probably having a pull request will help getting this resolved and merged sooner (I'm not affiliated with the project,  just a user)

**Comment by sfurey** [comment]
Just ran into this, thanks for the fix.  Would be great if this was merged into the main code base.

**Comment by djhvscf** [comment]
Can any of you create a PR with this change including an example of this fix?
