### ISSUE TITLE
Return row data on checkbox checked/click.

### ISSUE THREAD

**Issue by cindymarie** [wenzhixin/bootstrap-table#2823]
Hi!

I have here a table with check box.
I want to get the row data whenever the checkbox is checked or click. But I'm having trouble solving it.
No, I don't want to do another clicking to call the getSelections().
Do you have any suggestions or solution to this?

Thanks!

**Comment by trkaplan** [comment]
Check this: http://jsfiddle.net/e3nk137y/2106/ 
(Can be found in Events part in [jsfiddle examples page](http://bootstrap-table.wenzhixin.net.cn/examples/))

**Comment by airtonjr** [comment]
@cindymarie 

Something like would help you?

`$("#table").on('check.bs.table uncheck.bs.table check-all.bs.table uncheck-all.bs.table', function () {
     var selects = $("#table").bootstrapTable('getSelections');
 console.log(selects);
});  `
