### ISSUE TITLE
bootstrap table refresh 

### ISSUE THREAD

**Issue by Landslyde01** [wenzhixin/bootstrap-table#2824]
I don't know how to catch the clicked bootstrap-table refresh button on the toolbar.  Everything else seems to be working fine. How do I catch this event?

**Comment by trkaplan** [comment]
If you create the table via data attributes, check this example:
http://jsfiddle.net/trkaplan/v2fh6zuz/1/
If you create it via javascript you can change your code as you can see in the documentation: http://bootstrap-table.wenzhixin.net.cn/documentation/#events

**Comment by Landslyde01** [comment]
I can't get it to work. Really frustrating!

    `echo "<table id='showdata' data-toggle='table'></table>
		<script>
          	$(function(){
            	$('#showdata').bootstrapTable({
			cache: false,
			striped: true,
			pagination: true,
			sortable: true,
			pageSize: 10,
			pageList: [10, 25, 50, 100, 200],
			search: true,
			editable: true,
			showColumns: false,
			showRefresh: true,
			showToggle: true,
			clickToSelect: true,
			on: true,
		        queryParamsType: '',
			minimumCountColumns: 2,
			data: ".json_encode($ret).",`

And my jQuery:

    `$('#showdata').on('refresh.bs.table', function (params) {
         console.log("Table refreshed!");
         console.log(params);
         alert("clicked for refresh");
      });`

The alert never shows. What in the world am I doing wrong?

**Comment by yinzhifang** [comment]
Your code seem no `problem,you` must be confirm invoke 'refresh' method when you refresh table.such as:`$('#searchBtn').on('click', function(){
    			$dataTable.bootstrapTable('refresh');
    		});`

**Comment by Landslyde01** [comment]
yinzhifang: thank you for responding. on the bootstrapTable toolbar, there's a refresh button. if i knew the name of that button, i cld wire that code in for refreshing. is there any way to determine the name of that toolbar refresh button?

**Comment by airtonjr** [comment]
@Landslyde01 - 

`<button class="btn btn-default" type="button" name="refresh" title="Refresh">`

**Comment by Landslyde01** [comment]
airtonjr: Thanks. But I know how to make a button. That's not what I'm asking. I want to know how to make this button work. Because right now it's dead.
![selection_037](https://cloud.githubusercontent.com/assets/18239741/21567724/ea4f4c9a-ce73-11e6-8f07-bfe377aa2f69.png)

**Comment by airtonjr** [comment]
@Landslyde01 

I know. You are looking for the "name" of the refresh button. 

If you see the name is "refresh". This is the button in the BootstrapTable.

**Comment by airtonjr** [comment]
@Landslyde01 

Could you put your code? I could help you.

**Comment by Landslyde01** [comment]
Hi airtonjr:

I don't have code for that button because I didn't know its name. Therefore, I cldn't catch the event. So, I've been using the Fetch button. And all that does is refetch the data, not refresh anything.

![selection_038](https://cloud.githubusercontent.com/assets/18239741/21568301/0c797f8e-ce79-11e6-87de-47da1bb4d88d.png)

The Search and Columns buttons work out of the box. I'd appreciate your help on this refresh button. I just don't know how to catch it without knowing its name.

**Comment by airtonjr** [comment]
@Landslyde01 

Ok. Let's start with the basic, so I can try to think about your code:

`<div id="myToolbar">
        <div class="form-inline" role="form">
            <div class="btn-group" role="group">
                       
                <button href="#" data-table="site" data-modal-title="New" class="ls-modal btn btn-primary">
                    <i class="glyphicon glyphicon-edit"></i>
                </button>
             
            </div>
            <div class="form-group">
                <select class="form-control">
                    <option value="">Export Screen</option>
                    <option value="all">Export All</option>
                    <option value="selected">Export Selected</option>
                </select>
            </div>
        </div>
    </div>
    <table 
        id="myTable"
        data-toggle="table" 
        data-show-export="true" 
        data-search="true" 
        data-show-refresh="true" 
        data-show-columns="true" 
        data-striped="true" data-hover="true" 
        data-click-to-select="true" 
        data-single-select="true" 
        data-pagination="true" 
        data-toolbar="#myToolbar" 
        data-url="./loadData.json">
        <thead>
            <tr>
                <th data-field="state"  data-checkbox="true"></th>  
                <th data-field="state_id" data-sortable="true" data-visible="false">ID</th>
                <th data-field="state_name" data-sortable="true">State</th>
            </tr>
        </thead>
    </table>
</div>`

The basic example below I am creating a table with "data-toolbar="#myToolbar"" personalized toolbar and I am saying that I want to have my refresh button:   data-show-refresh="true"  - in my toolbar.

Ok?

When I click on the button I will have a "GET" request with the URL (data-url="./loadData.json"), right?

I know, maybe you went through those steps but I am just trying to get where you are now since we don't have your code. 

Can you create a fake json to use in an example table?

**Comment by Landslyde01** [comment]
I have a better idea now of what you need to see.

    `echo "<table id='showdata' style='margin-top:0px'></table>
		<script>
			$(function(){
			$('#showdata').bootstrapTable({
			cache: false,
	                striped: true,
	                pagination: true,
	                sortable: true,
	                pageSize: 10,
	                pageList: [10, 25, 50, 100, 200],
	                search: true,
	                editable: true,
	                showColumns: true,
	                showRefresh: true,
	                showToggle: true,
	                clickToSelect: true,
	                queryParamsType: '',
	                minimumCountColumns: 2,
	                data: ".json_encode($ret).",

			columns:[{
				field: 'st8',
				title: 'check',
      				radio: true,
				align: 'left',
	          		valign: 'middle',
	          		visible: true
			},{
				field: 'clientid',
				title: 'Client ID',
				align: 'left',
	                        valign: 'middle',
	                        visible: false
			},{
				field: 'lname',
				title: 'Last',
				align: 'left',
	                        valign: 'middle',
	                        sortable: true,
                		editable: {
                                type: 'text',
                                url: 'sotp.wsviewclients.php',
                                params: {
                                     data:'editlastname',
                                     idd: function(value) {
                                          var selects = $('#showdata').bootstrapTable('getSelections');
                                          var clientid = $.map(selects, function(row){
                                               return row.clientid;
                                           });
                                           return clientid[0];
                                     }
                               },
                               ajaxOptions: {
                                type: 'post'
                              },
                              validate: function (value) {
                                return large_text(value);//Example of validation
                              }
                         }
			},{
				field: 'fname',
				title: 'First',
				align: 'left',
	                        valign: 'middle',
	                        sortable: true,
                                editable: {
                                            type: 'text',
                                            url: 'sotp.wsviewclients.php',
                                            params: {
                                                  data:'editname',
                                                  idd: function(value) {
                                	              var selects = $('#showdata').bootstrapTable('getSelections');
                                                      var clientid = $.map(selects, function(row){
                                    	             return row.clientid;
                                                });
                                    return clientid[0];
                                }
                          	},
                           	ajaxOptions: {
                            	type: 'post'
                          	},
                          	validate: function (value) {
                            	return large_text(value); //Example of validation
                          	}
                        }
			},{
				field: 'startdate',
				title: 'Start Date',
				align: 'left',
	                        valign: 'middle',
	                        sortable: true,
	                        editable: false
			},{
				field: 'field1',
				title: 'Group Time',
				align: 'left',
	                        valign: 'middle',
	                        sortable: false,
	                        formatter: function (value, row) {
			                    var a1 = [row.sYears + ' yrs '];
			                    var a2 = [row.sMonths + ' mos '];
			                    var a3 = [row.sDays + ' days'];
			                    var a4 = a1 + a2 + a3;
			                    return a4;
                        }
			},{
				field: 'disdate',
				title: 'Discharge Date',
				align: 'left',
	                        valign: 'middle',
	                        sortable: true,
	                        editable: false
			},{
				field: 'field2',
				title: 'Discharge Time',
				align: 'left',
	                        valign: 'middle',
	                        sortable: false,
	                        formatter: function (value, row) {
			                    var a1 = [row.dYears + ' yrs '];
			                    var a2 = [row.dMonths + ' mos '];
			                    var a3 = [row.dDays + ' days'];
			                    var a4 = a1 + a2 + a3;
			                    return a4;
                        }
			} ]
		});
	 });
    </script>";
return;`

The difference I see here is that I don't have a toolbar name set.

**Comment by airtonjr** [comment]
@Landslyde01 

I know what is missing!

Try put in the options:  url: "justatest.php" - And hit refresh! It will execute the GET 💃 

You did not set an URL to get data!

**Comment by Landslyde01** [comment]
Please view my update above. Is it still lacking?

**Comment by airtonjr** [comment]
@Landslyde01 

I had to add an URL to use the refresh button.

`<table id='showdata' style='margin-top:0px'></table>
    <script>
        $(function(){
        $('#showdata').bootstrapTable({

/* BEGIN - HERE */
 url: "justATest.php",
/* END - HERE */
        
        cache: false,
                striped: true,
                pagination: true,
                sortable: true,
                pageSize: 10,
                pageList: [10, 25, 50, 100, 200],
                search: true,
                editable: true,
                showColumns: true,
                showRefresh: true,
                showToggle: true,
                clickToSelect: true,
                queryParamsType: '',
                minimumCountColumns: 2,               
                data: ".json_encode($ret).",

        columns:[{
            field: 'st8',
            title: 'check',
                radio: true,
            align: 'left',
                valign: 'middle',
                visible: true
        },{
            field: 'clientid',
            title: 'Client ID',
            align: 'left',
                        valign: 'middle',
                        visible: false
        },{
            field: 'lname',
            title: 'Last',
            align: 'left',
                        valign: 'middle',
                        sortable: true,
                    editable: {
                            type: 'text',
                            url: 'sotp.wsviewclients.php',
                            params: {
                                 data:'editlastname',
                                 idd: function(value) {
                                      var selects = $('#showdata').bootstrapTable('getSelections');
                                      var clientid = $.map(selects, function(row){
                                           return row.clientid;
                                       });
                                       return clientid[0];
                                 }
                           },
                           ajaxOptions: {
                            type: 'post'
                          },
                          validate: function (value) {
                            return large_text(value);//Example of validation
                          }
                     }
        },{
            field: 'fname',
            title: 'First',
            align: 'left',
                        valign: 'middle',
                        sortable: true,
                            editable: {
                                        type: 'text',
                                        url: 'sotp.wsviewclients.php',
                                        params: {
                                              data:'editname',
                                              idd: function(value) {
                                              var selects = $('#showdata').bootstrapTable('getSelections');
                                                  var clientid = $.map(selects, function(row){
                                                 return row.clientid;
                                            });
                                return clientid[0];
                            }
                        },
                        ajaxOptions: {
                            type: 'post'
                        },
                        validate: function (value) {
                            return large_text(value); //Example of validation
                        }
                    }
        },{
            field: 'startdate',
            title: 'Start Date',
            align: 'left',
                        valign: 'middle',
                        sortable: true,
                        editable: false
        },{
            field: 'field1',
            title: 'Group Time',
            align: 'left',
                        valign: 'middle',
                        sortable: false,
                        formatter: function (value, row) {
                            var a1 = [row.sYears + ' yrs '];
                            var a2 = [row.sMonths + ' mos '];
                            var a3 = [row.sDays + ' days'];
                            var a4 = a1 + a2 + a3;
                            return a4;
                    }
        },{
            field: 'disdate',
            title: 'Discharge Date',
            align: 'left',
                        valign: 'middle',
                        sortable: true,
                        editable: false
        },{
            field: 'field2',
            title: 'Discharge Time',
            align: 'left',
                        valign: 'middle',
                        sortable: false,
                        formatter: function (value, row) {
                            var a1 = [row.dYears + ' yrs '];
                            var a2 = [row.dMonths + ' mos '];
                            var a3 = [row.dDays + ' days'];
                            var a4 = a1 + a2 + a3;
                            return a4;
                    }
        } ]
    });
 });`

**Comment by Landslyde01** [comment]
LOL! That did it! :-)

I'll name my next child after you, airtonjr! Many thanks. Much appreciated. And I used the same URL you gave me, "justattest.php". Completely non-existing file, yet I guess that's all it wants: a file name. That's crazy...but convenient. Thanks again.

**Comment by airtonjr** [comment]
@Landslyde01 Cool! This is why I was asking for your code! 💃 

Now you can relax! This kind thing stress out!

**Comment by Landslyde01** [comment]
I'm abt ready to roll out this website. Is a MONSTER! I may need some help down the line.

**Comment by airtonjr** [comment]
@Landslyde01 Well, if you need help to figure out something, just let me know! I am in a crusade as you were!

**Comment by Landslyde01** [comment]
landslyde @ mail dot com

**Comment by airtonjr** [comment]
@Landslyde01 @ mail or @ gmail ?

**Comment by Landslyde01** [comment]
mail

**Comment by airtonjr** [comment]
@Landslyde01  Done.  Sent you an email.

**Comment by Dunstkreis** [comment]
@Landslyde01 i simply added this one to the table-options:


`	    onRefresh: function(params) {
	    	/* do whatever you like to do */
	    },`

Its working fine for me.

**Comment by Landslyde01** [comment]
@ Dunstkreis

Thank you. I forgot to close this thread; airtonjr solved my issue. But his solution was a little different than yours. I'll try it.

Thanks.
