### ISSUE TITLE
data-events事件BUG

### ISSUE THREAD

**Issue by 501956430** [wenzhixin/bootstrap-table#2827]
**相同的field列引用多次且时结合data-events事件时，会导致事件失效。**

field: id 使用了多次，最后根据id的值显示不同的按钮，若想actionEvents事件有效，就得去掉field: id的重复引用。

是否是BUG期待官方解答。

<!DOCTYPE html>
<html>
<head>
    <title>from-data</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../assets/bootstrap-table/src/bootstrap-table.css">
    <link rel="stylesheet" href="../assets/examples.css">
    <script src="../assets/jquery.min.js"></script>
    <script src="../assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="../assets/bootstrap-table/src/bootstrap-table.js"></script>
    
</head>
<body>
    <div class="container">
        <h1>From data</h1>
        <p></p>
        <table id="table"  >
            <thead>
            <tr>
                <th data-field="id">ID</th>
                <th data-field="name">Item Name</th>
		<th data-field="price">Item Name</th>
                <th data-field="id" data-formatter="inputFormatter" data-events="actionEvents">Item Price</th>
            </tr>
            </thead>
        </table>
    </div>
<script>

    $(function () {
        var data = [
            {
                "id": 0,
                "name": "Item 0",
                "price": "$0"
            },
            {
                "id": 1,
                "name": "Item 1",
                "price": "$1"
            },
            {
                "id": 2,
                "name": "Item 2",
                "price": "$2"
            },
            {
                "id": 3,
                "name": "Item 3",
                "price": "$3"
            },
            {
                "id": 4,
                "name": "Item 4",
                "price": "$4"
            },
            {
                "id": 5,
                "name": "Item 5",
                "price": "$5"
            }
        ];
        $('#table').bootstrapTable({data: data});
    });
	function inputFormatter(value) {
        var html="";
		if(value==1){
			html+='<input type="button"  id="update"  value="修改"/>';
		}else if(value==2){
			html+='<input type="button" id="add" value="新增"/>';
		}else {
			html+='<input type="button" id="remove" value="删除"/>';
		}
        return html;
    }
	
	window.actionEvents = {
        'click #update': function (e, value, row, index) {
            alert(1);
        },
        'click #add': function (e, value, row, index) {
            alert(2);
        },
		'click #remove': function (e, value, row, index) {
            alert(3);
        }
    };
</script>
</body>
</html>
![qq 20161216130852](https://cloud.githubusercontent.com/assets/20204491/21252352/08a28862-c391-11e6-98f8-c148fdc5e3a6.png)
详情看见附件

**Comment by 501956430** [comment]
![qq 20161216130852](https://cloud.githubusercontent.com/assets/20204491/21252411/7a75a0aa-c391-11e6-93cd-7eea4f14a51a.png)

**Comment by xyluet** [comment]
jsfiddle please

**Comment by 501956430** [comment]
@xyluet 
jsfiddle[地址](http://jsbin.com/zinomanewi/1/edit?html,console,output)
 第一列data-field修改为 id ,问题出现

**Comment by xyluet** [comment]
i feel that we can't use data-field and data-event together. but in your case, you can use param inputFormatter(value, row, index) and use the row param as counter like row.id == bla bla bla

and you can't use multiple element with same id, it will only bind the first one. you can use class attribute

**Comment by 501956430** [comment]
@xyluet
Re-elaborate my question, the actual use of the existence of a single attribute attributes at the same time show different effects, such as the status field, which need to display the state according to its value, but also need to display different buttons.

jsfiddle demo update [address]("http://jsbin.com/ruxenomoqe/2/edit?html,console,output")

**Comment by 501956430** [comment]
jsfiddle demo update [address](http://jsbin.com/ruxenomoqe/2/edit?html,console,output)

**Comment by 501956430** [comment]
@xyluet
Change the ‘status’ bar to status1 to see the effect

**Comment by xyluet** [comment]
http://jsbin.com/fowopemepe/1/edit?html,console,output

you can use like this

**Comment by 501956430** [comment]
Thank you
