### ISSUE TITLE
How To Find Row Index With Row or Field?

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#2828]
I have an ID and i want get row index include this ID row.

There is a table example: https://jsfiddle.net/mehmetalidumlu/7103q8Lx/

How can i get row index where YILDIZ is 32?

Thanks...

**Comment by trkaplan** [comment]
I've created a method which returns row number(s) of found row(s) with given key-value pair. 
`getRowOrderByProperty("#table","stargazers_count","32"); `
This returns `[2] ` (order number of the row which has "32" in "Yildiz" colum.)

https://jsfiddle.net/trkaplan/9xcnfqmy/

**Comment by mehmetalidumlu** [comment]
Ooooooo, thanks. It works!
