### ISSUE TITLE
problem with queryParams

### ISSUE THREAD

**Issue by guoxiangwen** [wenzhixin/bootstrap-table#2830]
![image](https://cloud.githubusercontent.com/assets/7627191/21263044/85d15564-c3cf-11e6-9bf4-b06d42c5c29f.png)
i set this code and the table work well. But when i change the pageNumber it also be page one when send to server? how could i do?

**Comment by trkaplan** [comment]
It would be nice if you provide a fiddle
See this guide: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
If `queryParamsType = 'limit'`, the params object contains: 
`limit, offset, search, sort, order`
Else, it contains: 
`pageSize, pageNumber, searchText, sortName, sortOrder`.
