### ISSUE TITLE
In the same page, when multiple tables are loaded with the same data, selecting a row also selects the corresponding row in the other tables

### ISSUE THREAD

**Issue by oglavas** [wenzhixin/bootstrap-table#2832]
When a page contains more than one tables, loaded with the same data and a row is selected in one of them, the selection also gets applied to the other tables.

[jsfiddle](https://jsfiddle.net/o4r8n6eb/11/) 

In the aforementioned fiddle, a copy of the dataset has been created as data2. Simply switch data:data for data:data2 in one of the tables, and the problem goes away.

**Comment by oglavas** [comment]
Note, that in order to detect the propagation of the selection to the second table, an action may be needed, such as, for example, sorting a column

**Comment by wenzhixin** [comment]
Javascript passes objects by reference. Let me offer an example:
```
var a =[{selected: false}];
var b = a;

a[0].selected = true;
console.log(JSON.stringify(b));
// ouput [{"selected":true}]
```
This is why it's causing the problem, you can use jQuery's [extend](https://api.jquery.com/jquery.extend/#jQuery-extend-deep-target-object1-objectN) method:
```
$('#table').bootstrapTable({
    data: $.extend(true, [], data),
    columns: cols
});
$('#table2').bootstrapTable({
    data: $.extend(true, [], data),
    columns:cols
});
```
Example: https://jsfiddle.net/o4r8n6eb/16/
