### ISSUE TITLE
UniqueId Not Being Set When Using insertRow

### ISSUE THREAD

**Issue by pettechbytes** [wenzhixin/bootstrap-table#2833]
I'm using the insertRow method to add a new row to the table, and the resulting HTML doesn't match the other rows.  The problem with this is that when I attempt to retrieve that row, modify, and then save it, it adds a new row instead of updating the existing row since the uniqueid attribute is not set.

Example:
```
$('#rules-table').bootstrapTable('insertRow', 
    { 
        index: 99, 
        row: { uniqueId: res.id, 
        id: res.id, 
        statecode: rule.StateCode, 
        salesrep: rule.SalesRep, 
        llcclassname: rule.LLCClassName, 
        companyname: res.CompanyName, 
        companyid: rule.CompanyId, 
        targetclassname: rule.CompanyClassName, 
        rowactions: '<div class="btn-group"><a href="javascript:void(0)" class="btn btn-outline btn-default rule-edit" data-item="' + res + '"><i class="icon wb-edit" aria-hidden="true"></i></a><a href="javascript:void(0)" class="btn btn-outline btn-default rule-delete" data-ruleid="' + res.Id + '"><i class="icon wb-trash" aria-hidden="true"></i></a></div>' 
    } 
});
```

This adds the row to the table, but comparatively, it's missing the uniqueid attribute.  The resulting tr that was generated by the insertRow call:
```
<tr data-index="8">
    <td>MA</td>
    <td>MA TEST 1</td>
    <td>MA LLC TEST 1</td>
    <td>HPC of Mississippi</td>
    <td>MA TARGET TEST 1</td>
    <td style="width: 124px;">
        <div class="btn-group">
            <a class="btn btn-outline btn-default rule-edit" href="javascript:void(0)" data-item="[object Object]"><i class="icon wb-edit" aria-hidden="true"></i></a>
            <a class="btn btn-outline btn-default rule-delete" href="javascript:void(0)" data-ruleid="9e5a9c25-57d7-4aa2-94bc-88602c6ea23a"><i class="icon wb-trash" aria-hidden="true"></i></a>
        </div>
    </td>
</tr>
```

Compared to a row that was added via the creation of the table:
```
<tr data-uniqueid="8ff18d9b-5d07-4c65-b88d-fc08fe4b8e92" data-index="7">
    <td>HI</td>
    <td>KEITH 2</td>
    <td>KEITH LLC 2</td>
    <td>HPC Biologicals Inc</td>
    <td>KEITH TARGET 2</td>
    <td style="width: 124px;">
        <div class="btn-group">
            <a class="btn btn-outline btn-default rule-edit" href="javascript:void(0)" data-item="System.Data.Entity.DynamicProxies.BillingRule_FD50B7CB077781BA6E53E4FA67F338BF644E0A8B8226C7DCAADBB31E737F91D6"><i class="icon wb-edit" aria-hidden="true"></i></a>
            <a class="btn btn-outline btn-default rule-delete" href="javascript:void(0)" data-ruleid="8ff18d9b-5d07-4c65-b88d-fc08fe4b8e92"><i class="icon wb-trash" aria-hidden="true"></i></a>
        </div>
    </td>
</tr>
```

I have bound to the double-click event and "open" the row for edit in a dialog and then save it back.  The way I'm identifying this row in the table is the uniqueid attribute.  Am I doing something wrong?

If I need to reference a jsFiddle, I can, I just ran out of time this morning and wanted to go ahead and submit the bug report.

**UPDATE:**
It would seem as though maybe it's the way I'm loading the data.  Currently, I am looping through records in my view (ASP.NET MVC) and creating static TR elements for each record.  Then, I initialize the bootstrap-table.  Is this the preferred method or should I be dynamically loading the data?

**UPDATE 2:**
Not sure if this makes a difference, but our Id is a GUID.  Does that break this functionality?  I haven't tested this with a simple Integer Id.

**Comment by pettechbytes** [comment]
Oh, and just the opposite with `removeByUniqueId`, the table events are broken after I call it once:
`$('#rules-table').bootstrapTable('removeByUniqueId', id);`

I mean that I can't perform any other actions on the table after the remove.

**Comment by wenzhixin** [comment]
It would be nice if you provide a fiddle :)

**Comment by Falseee** [comment]
I close this issue because we got no response/example within 7 days.
