### ISSUE TITLE
Sub Table Missing First Header Column

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#2834]
Hi,
I used sub table in my project. But first header column is missing. I created JSFiddle project for this error. So always is true in there. I cant found problem.

This screenshot from my project. Attention, first header column missing!
![screenshot_2](https://cloud.githubusercontent.com/assets/15678340/21361928/d5c40f04-c6ee-11e6-8f66-13f6cfe23663.png)

There is JSFiddle link: https://jsfiddle.net/mehmetalidumlu/fgr92faf/

Have you ever faced this problem?

**Comment by sato002** [comment]
I have same issue. Please help
