### ISSUE TITLE
Sub Table: Mobile Responsive on Expend Row Error

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#2835]
Hi all,
Sub table works on large screen, but has error on mobile screen. **I cant expand row on mobile!**
I added "extensions/mobile/bootstrap-table-mobile.js" on project.

**JSFiddle Example is [HERE](https://jsfiddle.net/mehmetalidumlu/fgr92faf/3/)**

There are large and mobile scrrenshots

Large Screen:
![screenshot_4](https://cloud.githubusercontent.com/assets/15678340/21386753/01b30b22-c77d-11e6-8163-fa67890e0541.png)

Mobile Screen:
![screenshot_5](https://cloud.githubusercontent.com/assets/15678340/21386769/15ed9738-c77d-11e6-9de3-9e8a6fd350da.png)

Thanks...

**Comment by wenzhixin** [comment]
Because expand row is not supported under card view(`cardView: true`), let's consider implementing this feature in the mobile extension.

**Comment by UtechtDustin** [comment]
I close this issue because its already some years old, since Dec 2016 nobody nobody answered/asked for the same feature so i guess its not so necessary.
If you still need it we will consider to implement it, please reopen the issue then.
