### ISSUE TITLE
How to change Input to Textarea in Editable extension ?

### ISSUE THREAD

**Issue by HiCodin** [wenzhixin/bootstrap-table#2836]
Hi, as per the issue subject title, is there any way where I can change the popup input field to textarea ? I tried setting `data-type=textarea` according to the example but its not working as intended.

**Comment by HiCodin** [comment]
Sorry for opening this issue. I should've read the readme properly. I've found what I wanted.

**Comment by alamkaton** [comment]
HiCodin, What did you do? I am confused about that.
