### ISSUE TITLE
Refresh not working with Disabled Checkbox

### ISSUE THREAD

**Issue by bestprogramming** [wenzhixin/bootstrap-table#2839]
Hello. When working some disabled checkbox, btnSelectAll checkbox is not selected after page loaded.
But there is no problem when working client-side, check all, uncheck all. I see the problem when I use .bootstrapTable('refresh'). Is there a some binding problem?

Is it also possible hiding some checkbox without creating as disabled?

http://jsfiddle.net/bestprogramming/e3nk137y/10696/

**Comment by Falseee** [comment]
I close this issue because its older than 2 Years, if this issue still exists pls reopen this issue.
