### ISSUE TITLE
refreshOptions doesn't remove the toolbar

### ISSUE THREAD

**Issue by letientai299** [wenzhixin/bootstrap-table#2840]
# `refreshOptions` redraw whole table but doesn't remove the `toolbar`

Please go to this [jsfiddle](https://jsfiddle.net/wzq7Lkfd/), and click the button several times to see the issue.

- Bootstrap-Table version: 1.11.0

I use the `toolbar` option to add Table title in same row with search box. Don't know if there's any other way, would love to know about that also.

**Comment by letientai299** [comment]
My workaround for this issue: listen for the options refresh event and remove the table toolbar
manually, right after the table is rendered again.

```javascript
$("#tableId").on("refresh-options.bs.table", function(e, options) {
    setTimeout(function() {
    // The toolbar is left in the table container.
      $("#tableContainerId > #tableToolbarId").remove();
    }, 0);
});
```

It would be better if we can have some other events like: `onPreDestroy`,
`onPostDestroy` to listen, so we don't need `setTimeout`, but that is another story.

**Comment by wenzhixin** [comment]
Before use `refreshOptions`, you need to use 'destroy` method:
```
$table.bootstrapTable('destory').bootstrapTable('refreshOptions', {});
```
https://jsfiddle.net/wenyi/wzq7Lkfd/1/
