### ISSUE TITLE
Multi sorting a column shows hidden rows

### ISSUE THREAD

**Issue by choudharyabhinav15** [wenzhixin/bootstrap-table#2841]
I have similar issue where I am using a filter which filters the columns and hides the row similar as excel. I have created a demo on jsfiddle where I am hiding first row on click "Hide Row" button just for example. Then If I click on multi- sort option and give below cases it gives me hidden row also.

Multi Row Cases:
Sort By - Name - Descending
Sory by- Fork - Ascending

https://jsfiddle.net/h2c683cn/37/

Please let me know about your comments or solution on this. I liked this plugin but because of this issue I am not able to implement this. The uniqueId cannot be implemented as this is dynamically coming data and I am using my custom filter to filter the data just like excel.

**Comment by choudharyabhinav15** [comment]
@dabros @wenzhixin @djhvscf @sblinstein @mvollmer1 Please help me with this issue

**Comment by djhvscf** [comment]
Hi @choudharyabhinav15 that is an issue that we could not solve yet. it is a known issue, I will try to solve in these days

I will keep you posted

**Comment by choudharyabhinav15** [comment]
Thank you so much. But could you please tell me when I can expect the fix of this issue. As I need this functionality.

**Comment by choudharyabhinav15** [comment]
@dabros @wenzhixin @djhvscf @sblinstein @mvollmer1 Any idea on this? I will really appreciate if someone resolves this issue

**Comment by UtechtDustin** [comment]
You are using the `hide` function from `Jquery` which only change the `dom` not the data from the bootstrap table.
To hide a row please use the [hiderow method.](https://bootstrap-table.com/docs/api/methods/#hiderow).

Demo: https://live.bootstrap-table.com/code/UtechtDustin/66

**Comment by dabros** [comment]
@choudharyabhinav15 @djhvscf - what UtechtDustin shared above seems to work fine in your fiddle, when you replace the direct jquery hide (which ofcourse wouldnt retain its status, sicne your affecting the DOM outside of bootstrap-table) with:

 ` $("#mydemotable").bootstrapTable('hideRow', {index:1});`

Seems to work fine, no rows showing when sort is applied
