### ISSUE TITLE
Is there any way to show a message on the table if there is an error in API loading or API server?

### ISSUE THREAD

**Issue by smrrrazu** [wenzhixin/bootstrap-table#2842]
I want to use `onLoadError` event to show an error message on the table, if API server is down or an error occurred in the API page as follows.

`$('#my-table').bootstrapTable({
    pagination: true,
    paginationVAlign: 'both',
    pageSize:25,
    smartDisplay: true,
    sortName: 'regions',
    url: '/api/sources/',
    onResetView: function(){
        selectSources();
    },
    queryParams: function(){
        return {};
    },
}).on('load-error.bs.table', function (status, res) {
    // It works up to here
});

Now I want to show an error message instead of showing **No matching records found**.

**Comment by wenzhixin** [comment]
#1791 updateFormatText method: http://jsfiddle.net/e3nk137y/3876/
