### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prop' of undefined     at p.resetView (bootstrap-table.min.js:formatted:1254)

### ISSUE THREAD

**Issue by ll929** [wenzhixin/bootstrap-table#2845]
after set height（height: $(window).height() - 40,），console error “Uncaught TypeError: Cannot read property 'prop' of undefined     at p.resetView (bootstrap-table.min.js:formatted:1254)”

**Comment by airtonjr** [comment]
@ll929 You have a comma - （height: $(window).height() - 40# **_,_**）.

Can you show your code?

**Comment by ll929** [comment]
```js
$("#dataTable").bootstrapTable({
            url: "../productController/productDispay.do",
            //data:data.rows,
            height: $(window).height() - 40,
            pageSize: 10,
            pagination: true,
            sidePagination: 'server',
            pageList: [10, 25, 50, 100],
            classes: 'table',
            selectItemName: 'id',
            uniqueId: 'id',
            striped: true,
            queryParamsType: '',
            clickToSelect: true,
            singleSelect: false,
            showRefresh: true
//……
        });       
```

**Comment by wenzhixin** [comment]
Our example is working well: http://issues.wenzhixin.net.cn/bootstrap-table/.
Have you solved your problem? if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!

**Comment by ll929** [comment]
it‘s  normal when I use it in another project although I use the same version，including jquery and bootstrap is the same version.
