### ISSUE TITLE
queryParams can't pass to server when multiple sort server

### ISSUE THREAD

**Issue by weixiaohuster** [wenzhixin/bootstrap-table#2848]
when using multiple-sort extension, the ajax only pass original params(`{"sortName":"","sortOrder":"asc","pageSize":10,"pageNumber":1,"multiSort":[{"sortName":"flowPath","sortOrder":"asc"}]})` to server,  however the custom queryParams can't be send to server.
if custom params are passed by queryParams? if not, how to pass custom parameter to server when multiple sort in server?

Thanks!

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by LakshmiBalla** [comment]
Hi 
I'm also having issue with multi sort plugin, custom query params are overided when we use multisort plugin.

This is my sample code .
$('#requestsList-${param.filterId}').bootstrapTable({
--
--
--
queryParams: function (p){
		   var pageSize = ($('#requestsList-1}').bootstrapTable('getOptions')).pageSize;
		  <c:if test ="${data.massActions}">
		  		pageSize = ${data.pageSize > 0 ? data.pageSize : 20};
		   </c:if>
		      var pageNo ($('#requestsList-1').bootstrapTable('getOptions')).pageNo;
		       <c:if test ="${data.massActions}">
		        	  pageNo = ${data.pageNo > 1 ? data.pageNo : 1};
	        	 </c:if>
                           $.extend(p,{"_ajax":true,"action":"requestsData","filterId":'1'});
		        	   return p;
		           }
});
