### ISSUE TITLE
how to use cookie to save filterBy?

### ISSUE THREAD

**Issue by lvwzhen** [wenzhixin/bootstrap-table#2849]
@wenzhixin @djhvscf 
Cookie can save sortOrder, sortName, pageNumber, pageList, columns, searchText, filterControl,but can`t save filterBy.

This is my [jsfiddle](http://jsfiddle.net/lvwzh1991/mow64ndb/)

[Cookie](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html)
[filterBy](http://issues.wenzhixin.net.cn/bootstrap-table/#methods/filterBy.html)

**Comment by developaspeur** [comment]
Hello guys, is there an issue to solved this problem please? @wenzhixin

**Comment by juli1git** [comment]
Hi @wenzhixin ,
same issue for me.
