### ISSUE TITLE
和bootstrap的modal一起使用，会出现table表头重复出现问题

### ISSUE THREAD

**Issue by hao0111** [wenzhixin/bootstrap-table#285]
你好，和bootstrap V3.1.1的modal 采用href方式加载，table在主页面里，会出现table表头重复出现，如果拿掉data-toggle=“table”属性，就不会有这问题....如果不用href加载页面也不会有问题
恳请验证测试or有解决方法么..不胜感激..谢谢！！！

**Comment by wenzhixin** [comment]
更新到最新版本应该可以了，这个bug 改过了，或者使用 resetView 方法。

**Comment by weiminzhou** [comment]
你好！我的项目上也遇到这样的问题，可否告知一下怎么解决的这个问题，谢谢！

**Comment by wenzhixin** [comment]
监听 modal 的事件然后使用 `resetView` 方法去重置下表头应该就可以了
