### ISSUE TITLE
Exporting when "mobileResponsive: true" does not behave properly

### ISSUE THREAD

**Issue by migosantos** [wenzhixin/bootstrap-table#2851]
Exporting files from the bootstrap table works perfectly when done in the normal maximized desktop view. 

When I resize the browser into the mobile size (with option "mobileResponsive:true"), the table gets converted to the card-view type. Afterwards, when I click on the export to csv or pdf, the exported data contains all these html tags which are not supposed to be in the export.

Sample csv exported when in mobile/card-view:
![csv](https://cloud.githubusercontent.com/assets/5512190/21714308/40010a96-d439-11e6-8c42-97e5736531d4.png)

**Comment by wenzhixin** [comment]
Fixed in the latest version.
