### ISSUE TITLE
prevPage | nextPage | selectPage method not working

### ISSUE THREAD

**Issue by 953133667** [wenzhixin/bootstrap-table#2853]
### prevPage | nextPage | selectPage method not working

If i set `sidePagination: "server", //The server-side processing paging`,  prevPage | nextPage | selectPage method not working.
For examples : 
```
### Step 1.
$('#table').bootstrapTable({
//some code
sidePagination: "server", //The server-side processing paging
//some code
})

### Step 2.
$("#button").click(function(){
    $('#table').bootstrapTable("nextPage");  //This line code not working.
});

```

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/4r6g4cfu/548/
