### ISSUE TITLE
No sorting or pagination in sub table

### ISSUE THREAD

**Issue by techietravels** [wenzhixin/bootstrap-table#2856]
Sorting and pagination is not working when you create a subtable in the expanded details for the row.  When you click to sort, the expanded details closes.  No pagination appears at all.

https://jsfiddle.net/oc0j16ju/8/

**Comment by wenzhixin** [comment]
It seems that you use a wrong version, our example is working well: http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html
