### ISSUE TITLE
how to judge a row is checked or not checked

### ISSUE THREAD

**Issue by weituotian** [wenzhixin/bootstrap-table#2858]
i find check/uncheck method
is there a way to know a row is checked or not cheked?

**Comment by wenzhixin** [comment]
You can use `getSelections` method or this example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/415.html

**Comment by weituotian** [comment]
不不，这很浪费性能，我只想知道当前checkbox的状态，当前row的状态而已
不只是id，能不能给个方法扩展呢?

it is not because it is waste of performance.I just want to know the state of the current row.
Is it a way can be extend?

除了全选功能
比如我想做个反选功能，我不知道当前row的状态，我怎么反选呢？
![b1](https://cloud.githubusercontent.com/assets/7270968/22615093/35c51798-eac8-11e6-9ec6-843bca8102ea.jpeg)

**Comment by wenzhixin** [comment]
你可以直接使用 getData 获取所有列的数据，然后哪一列的状态就可以知道了，例如你的checkbox的field是state，那么row.state可以获取到当前row的状态
