### ISSUE TITLE
[mutilSort]springmvc could not accept the params!!!

### ISSUE THREAD

**Issue by weituotian** [wenzhixin/bootstrap-table#2861]
![q -20170112171728](https://cloud.githubusercontent.com/assets/7270968/21883874/f716339e-d8eb-11e6-95f6-14ddd5963e07.png)

![q -20170112171632](https://cloud.githubusercontent.com/assets/7270968/21883879/fd44cec4-d8eb-11e6-8e0a-3b109c99b217.png)

is there a way the defind how the sort array be passed?

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by weituotian** [comment]
@wenzhixin  ,not yet!  
and the other problen is The mutilSort plugin will overwrite the queryParams option ! so that i can not use my own queryParams option!
![image](https://cloud.githubusercontent.com/assets/7270968/22962987/4b084406-f38b-11e6-9755-d2ce6f51a0f7.png)

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by weituotian** [comment]
@wenzhixin 

i find the code in the [bootstrap-table/extensions/multiple-sort/bootstrap-table-multiple-sort.js](https://github.com/wenzhixin/bootstrap-table/blob/95a14868fffe2ee61bb29fd0fa536c04f3af91bf/src/extensions/multiple-sort/bootstrap-table-multiple-sort.js) 

in the line 127,it does override the queryParams options!!!


![image](https://cloud.githubusercontent.com/assets/7270968/23288381/4909a286-fa7e-11e6-8a36-3641963e2cd4.png)

**Comment by Flounn** [comment]
@weituotian @wenzhixin #2517 fix this bug.

**Comment by weituotian** [comment]
@Flounn @wenzhixin 
it is amazing!thank you!
you solve my problem! 厉害了我的哥
