### ISSUE TITLE
Creating Checkbox using data-formatter= is inconsistant. 

### ISSUE THREAD

**Issue by OldProgramCoder** [wenzhixin/bootstrap-table#2866]
Here is a fiddle.  http://jsfiddle.net/efqvt5v2/1/

I am trying to format a field using data-formatter="functionname"

When I do this I get a check box which I want to use as a selector for later processing.

The problem is that this check box is not always defined.

1. Trapping the event  click-cell.bs.table  and looking for the  check box I find it.

2. When I trigger a data export using 'getData'   I can not see the field.   It is undefined and I can not see the value of the check box.

How do I see the value of the checkbox on a 'getData' call.

**Comment by wenzhixin** [comment]
I think you need to update the row data manually. ref #2325 #2263
