### ISSUE TITLE
Event:dbl-click-row.bs.table Parameter [row] and [$element]  were put in the wrong order

### ISSUE THREAD

**Issue by haowangmeng** [wenzhixin/bootstrap-table#2868]
bootstrap-table version: 1.11.0
event: dbl-click-row.bs.table
The event's documentation is [row: the record corresponding to the clicked row,$element: the tr element],
but in fact [row] and [$element]  were put in the wrong order, the two parameters  were misplaced.

**Comment by djhvscf** [comment]
Can you create a **PR** changing that documentation? 

@haowangmeng

**Comment by wenzhixin** [comment]
When you use like this:
```js
$('#eventsTable').on('dbl-click-row.bs.table', function (event, row, $element) {

});
```
the first parameter is `event`: http://jsfiddle.net/wenyi/e3nk137y/11688/

and `onDblClickRow` option:
```js
onDblClickRow: function (row, $element) {

}
```

So I think it is not a bug.
