### ISSUE TITLE
how to get all data

### ISSUE THREAD

**Issue by joefreire** [wenzhixin/bootstrap-table#2869]
I need get alldata without filters to generate a report, thats possible?
 $table.bootstrapTable('getData') 
return only by the paginator

**Comment by djhvscf** [comment]
You can try 

```js
$table.bootstrapTable('getData', false)

And let me know if that works for you, please @joefreire

**Comment by algking** [comment]
I think `$table.bootstrapTable('getData', {useCurrentPage: false});` is not the right answer.
after I check the source code of bootstrap-table ,`$table.bootstrapTable('getData', false);` will work

**Comment by AtapX** [comment]
are this issue is updated?
This still not work for me, in 100 list items on one page, they still just return 90 item when there are 1000 items.

for information
I have used the lastest of bootstrap table.

and I have trying to in pagination all (https://github.com/wenzhixin/bootstrap-table/issues/2318), but its still not work

**Comment by v20100v** [comment]
I have the same problem. I can't get all data with data-url attribute...

This param (useCurrentPage, includeHiddenRows, or unfiltered) seem not to work.

```
$bootstrapTable.bootstrapTable('getData', {
        useCurrentPage: false,
        includeHiddenRows: true,
        unfiltered: true
});
```

How can i get all data with the method `getData` whatever the context: pagination, filters, data retrieved by request xhr ?

Thanks for your advices.

**Comment by UtechtDustin** [comment]
@v20100v 
could you please provide us an example ? (using our [Editor](https://live.bootstrap-table.com/))

**Comment by v20100v** [comment]
With the (simplified) example done in your editor ... 

https://live.bootstrap-table.com/code/v20100v/2125

I no longer have a problem with the getData method. It behaves as agreed. So the problem comes from my implementation... remains to be found where it bug ^^. Sorry
