### ISSUE TITLE
How can I add/remove classes of a row using UniqueId?

### ISSUE THREAD

**Issue by necto101** [wenzhixin/bootstrap-table#2871]
I want to change the class (to use danger, warning, ...) of a row, using the uniqueId. I've been trying with updateRow with no success. Somebody help me? Thanks!

**Comment by djhvscf** [comment]
Can you these example and let me know if those work for you?

http://issues.wenzhixin.net.cn/bootstrap-table/#issues/221.html
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/563.html

**Comment by wenzhixin** [comment]
Example for you: http://jsfiddle.net/wenyi/e3nk137y/11463/
