### ISSUE TITLE
How to add ng-show attribute in th and td?

### ISSUE THREAD

**Issue by slowaways** [wenzhixin/bootstrap-table#2874]
I am trying use angular-js ng-show attribute in the table.
The attribute "ng-show" is removed after init the table.

...

**Edit 1**
JSfiddle
https://jsfiddle.net/gocsvagt/3/
Inspect HTML Code to see ng-show removed after init the table.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by slowaways** [comment]
https://jsfiddle.net/gocsvagt/2/

**Comment by djhvscf** [comment]
This is not supported. Any PR is welcome
