### ISSUE TITLE
Boolean Variables Were Not Sorted Properly in the case of multiple sort.

### ISSUE THREAD

**Issue by rvats** [wenzhixin/bootstrap-table#2877]
Boolean Variables Were Not Sorted Properly in the case of multiple sort.
Change to fix the bug have been already proposed.

**Comment by djhvscf** [comment]
I have not seen your **PR**.

Can you provide an example? @rvats

**Comment by wenzhixin** [comment]
Any update?

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!
