### ISSUE TITLE
Can't disable multiple checkboxes

### ISSUE THREAD

**Issue by stash86** [wenzhixin/bootstrap-table#2878]
The example can be found here https://jsfiddle.net/stash_86/9mepdusw/8/

So everytime I want to disable multiple checkboxes, only the last one will be disabled. Any help?

---- Edit----

On another check, I found that the checkboxes are indeed disabled, but visual wise, only the last one is visualised correctly (grey box, the forbidden mouse cursor)

**Comment by Falseee** [comment]
Demo: https://jsfiddle.net/zo2Leyn0/

**Comment by Falseee** [comment]
Its a timing issue, so just reinit the table after the last change.
Demo: https://jsfiddle.net/wq29gx6e/1/
