### ISSUE TITLE
How to get Index to selected/clicked row

### ISSUE THREAD

**Issue by Blm0423** [wenzhixin/bootstrap-table#288]
When I click on a row, a dialog will show the data from the row, 
<code>
      $('#users-table').bootstrapTable({})
        .on('click-row.bs.table', function (e, row, $element) {
          ShowUserPopup(row);
        });
</code>

but in order to uodate the underlying data I would need the Index to the row, so I could update it correctly.

This example does not work (I guessed it should re-fetch underlying data, but it did not).
<code>
   $.ajax({type: 'POST'
  ...
        success: function (response, status, jqXHR) {
          if (jqXHR.status === 200) {  
            <b>$('#users-table').bootstrapTable('refresh', { silent: true });</b>
</code>

This method needs the index of the row, to update internal data

<code>
            $('#users-table').bootstrapTable('updateRow', {
              index: UsersNS.RowIndex ,
              row: {
                Username: dataRow.Username,
                Realm: dataRow.Realm,
                Mobile: dataRow.Mobile,
                EMail: dataRow.EMail
              }
            });
</code>

How can i set the <b>UsersNS.RowIndex</b> when clicking on a row?

**Comment by DavidKrupi** [comment]
Hello, I would like to ask how to toggle $detail view (expand-row.bs.table) by clicking on the row.
I mean the same behaviour as "detail-icon" object...
