### ISSUE TITLE
table-body overflows table-container in a tab or modal

### ISSUE THREAD

**Issue by tammo0** [wenzhixin/bootstrap-table#2880]
Hi!

I'm using bootstrap-table in bootstrap tabs and bootstrap modals and run into the same issue with both.

The height calculation seems to be wrong somehow. My bugfix calling resetView on onPostHeader was a stupid idea - it works for calculating the correct height but it will stuck in a loop and  e.g. columns won't be sortable, because resetView triggers onPostHeader.

1. Please take a look at the provided jsfiddle: [jsfiddle](http://jsfiddle.net/uvx17hfg/1/)
2. Click the Table-tab to see its overflowing.
3. Uncomment the onPostHeader and it will fix the height problem but ends in a loop: [jsfiddle](http://jsfiddle.net/uvx17hfg/2/)

wrapping the table in a div with a .row class and a div with a .col-md-12 class just expands the tab content, but not the height problem which you can see when you start sorting on a column: [jsfiddle](http://jsfiddle.net/uvx17hfg/3/)

Is there any other method i can call to recalculate the height? Or can i tell resetView not triggering the onPostHeader Event? Or am i mssing something?

Thanks and keep up the good work!

**Comment by tammo0** [comment]
this is a workaround for my problem, but still not a good solution:
[jsfiddle](http://jsfiddle.net/uvx17hfg/4/)

**Comment by wenzhixin** [comment]
Why don't you initialize your table after click the tab? 
http://jsfiddle.net/wenyi/uvx17hfg/5/

If the problem exists reopen it, thanks!
