### ISSUE TITLE
load data throws "Cannot read property 'fixedScroll'"

### ISSUE THREAD

**Issue by eltonk** [wenzhixin/bootstrap-table#2881]
When I try to load a local data, via an angular directive, the bootstrap-table component is throwing the following error on console:

```
> angular.js:10160 TypeError: Cannot read property 'fixedScroll' of undefined
>     at BootstrapTable.load (eval at <anonymous> (jquery.min.js:4), <anonymous>:2352:31)
>     at HTMLTableElement.eval (eval at <anonymous> (jquery.min.js:4), <anonymous>:2983:38)
>     at Function.each (jquery.min.js:4)
>     at init.each (jquery.min.js:4)
>     at init.$.fn.bootstrapTable (eval at <anonymous> (jquery.min.js:4), <anonymous>:2968:14)
>     at Object.fn (bsTable.directive.js:12)
>     at Scope.$digest (angular.js:12703)
>     at Scope.$apply (angular.js:12968)
>     at done (angular.js:8479)
>     at completeRequest (angular.js:8693)
```

Checking the JS code, I noted that the prototype load function is expecting this information on the "data" object:

```
> else if (!$.isArray(data)) { // support fixedScroll
>             fixedScroll = data.fixedScroll;
```

What I'm doing?

On my angular directive:

```
> link: function (scope, element, attr) {
>              
>                 scope.$watch('datasource', function(datasource) {
>                     $(element).bootstrapTable('load', datasource);
>                 
>                 });
```

My html:

```
> <table data-toggle="table"
>                        **data-datasource="view1Ctrl.users"**
>                        data-show-toggle="true" 
>                        data-show-columns="true" 
>                        data-search="true" 
>                        data-select-item-name="toolbar" 
>                        data-pagination="false"
>                        bs-table-control>
>                     <thead>
>                     <tr>
>                         <th data-field="id" data-checkbox="true" >User ID</th>
>                         <th data-field="name"  data-sortable="true">User Name</th>
>                         <th data-field="email" data-sortable="true">User email</th>
>                     </tr>
>                     </thead>
>                 </table>
```

My controller, using RestAngular:

```
> usersResource.getList()
>         .then(function(users) {
>           vm.users =  Restangular.stripRestangular(users);
> 
>         })
```

Questions:
Am I missing something?
Is really mandatory to add the "fixedScroll" property on the "data"?

Suggestion: If I'm not missing anything, the bootstrap-code could be changed to something like:
> else if (!$.isArray(data)) { // support fixedScroll
>             fixedScroll = data.fixedScroll ? data.fixedScroll : false;

Thanks!

**Comment by djhvscf** [comment]
I think you can create a **PR** with that change 

`fixedScroll = data.fixedScroll ? data.fixedScroll : false;`

@eltonk

**Comment by wenzhixin** [comment]
@eltonk @djhvscf `load` method is depend on `sidePagination` option:
> Defines the side pagination of table, can only be 'client' or 'server'. Using 'server' side requires either setting the 'url' or 'ajax' option. 
Note that the required server response format is different depending on whether the 'client' or 'server' option is specified. See the following examples:
[Without server-side pagination](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data1.json)
[With server-side pagination](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data2.json)

When you set to `client`, your load data must be an array:
```
bootstrapTable('load', array); // []
```

set to `server`, your load data must be an object:
```
bootstrapTable('load', object); // {total: 20, rows: []}
```

**Comment by wenzhixin** [comment]
Examples:
- Load(client): http://jsfiddle.net/wenyi/e3nk137y/11458/
- Load(server): http://jsfiddle.net/wenyi/e3nk137y/11459/

Close this issue, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
