### ISSUE TITLE
Change page size without re-render search block 

### ISSUE THREAD

**Issue by Shpartko** [wenzhixin/bootstrap-table#2883]
Hello!

When I try 
`$table.bootstrapTable('refreshOptions', {pageSize: 10})`
for change page size from x to 10 or any, all controls from div on the top right part of header table (search field, refresh button) is full recreated. And all of my modifications of this div was cleared.

How can i change pageSize without re-render search block?

**Comment by djhvscf** [comment]
I think we can create a new method in order to do that. @Shpartko this method can be the same as `selectpage` or `prevpage` or `nextpage`

**Comment by Shpartko** [comment]
It would be cool!
I do not know how to do it, so I will wait for the new version of bootstrap-table.
Thanks!

**Comment by wenzhixin** [comment]
There is a workaround for you:
```
function changePageSize($table, pageSize) {
    $table.closest('.bootstrap-table').find('.page-list a').each(function () {
        if (+$(this).text() === pageSize) {
            $(this).click();
            return false;
        }
    });
}

changePageSize($('#table'), 50);
```

example: http://jsfiddle.net/wenyi/e3nk137y/11687/

**Comment by Shpartko** [comment]
Bad example. Use refresh method with pageSize option 👍

**Comment by wenzhixin** [comment]
#2891
