### ISSUE TITLE
Feature Request - Select row on load

### ISSUE THREAD

**Issue by edmomot** [wenzhixin/bootstrap-table#2884]
Feature request for a way to programmatically select a row on load when using checkboxes or radio buttons.

A callback function similar to this would meet my use case:

```
function(row) { 
    var rowShouldBeSelected = doMyOwnLogic(row);
    return rowShouldBeSelected; 
}
```

This would be called on each row in the table.  It can be accepted as an option to be executed on initialization, or provided as a method to be called any time during the table's lifecycle.

The way I found to work around this limitation is to manually find the element I need in the table on load success, and do `.prop("checked", true)` and `.trigger("click")` to properly select the row and maintain the selection through sorting.

**Comment by wenzhixin** [comment]
The same with #2715
