### ISSUE TITLE
Detail View Option.

### ISSUE THREAD

**Issue by jokotingkir212** [wenzhixin/bootstrap-table#2886]
Hi. I have a question.

How to repeat detail view option for next row?

(sorry, i can't explain with word. i confused. So, i will used image to explain it)

![question](https://cloud.githubusercontent.com/assets/25635300/22733748/b1ffd3d8-ee25-11e6-89da-91a9f8ceee28.PNG)

first row is worked perfectly, but next row is not working. I used mysql database and php. How to fix it. Thanks. :)

**Comment by djhvscf** [comment]
Did you mean that the first row works but when you open the second one it shows "detailFormatter"?

**Comment by jokotingkir212** [comment]
Yes, that's what I mean. How to fix it?

**Comment by djhvscf** [comment]
Can you help us with an example in [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) 

Thanks

**Comment by jokotingkir212** [comment]
This is the code.
https://jsfiddle.net/hjq7fjj1/

**Comment by djhvscf** [comment]
It is loading just one row, I can't test the issue that you mentioned

**Comment by wenzhixin** [comment]
Examples:
http://issues.wenzhixin.net.cn/bootstrap-table/#options/detail-view.html
http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!

**Comment by fas3r** [comment]
Hello,

I get the same issue, here are the fiddles. 

1) It seems that the data-detail-formatter is interpreted as string only if the function detailFormatter is place in the $(document).ready. 
[https://jsfiddle.net/tfderg8b/4/](url)

2 ) if place outside of the $(document).ready, it's not providing the same result as in the example, it seems that the $.each over "row" object return all it's content.  
[https://jsfiddle.net/q7tc3k20/1/](url)

3 ) But the column name are accessible using "row.nameCol" instead of using the each..
[https://jsfiddle.net/xd75k2w7/1/](url)

Thank you.

**Comment by jaydeepgiri** [comment]
> Hello,
> 
> I get the same issue, here are the fiddles.
> 
> 1. It seems that the data-detail-formatter is interpreted as string only if the function detailFormatter is place in the $(document).ready.
>    https://jsfiddle.net/tfderg8b/4/
> 
> 2 ) if place outside of the $(document).ready, it's not providing the same result as in the example, it seems that the $.each over "row" object return all it's content.
> https://jsfiddle.net/q7tc3k20/1/
> 
> 3 ) But the column name are accessible using "row.nameCol" instead of using the each..
> https://jsfiddle.net/xd75k2w7/1/
> 
> Thank you.

Bro You are not passing the data to table in JSON format via jquery or via the server url.  You're facing an issue because you're putting the data directly in the table body.

**Comment by Falseee** [comment]
@jaydeepgiri 
If he load the table with html or with a json dont matter, the real issue is that the formatter dont exist on runtime (scope issue).

Its a scope issue so the issue can be closed, or not ? @wenzhixin @djhvscf

**Comment by wenzhixin** [comment]
Yes, when the `data-*` type is `Function`, it must be the property of the `window`.
