### ISSUE TITLE
How to integrate bootstrap table into Angular 2?

### ISSUE THREAD

**Issue by katrina-engelbrecht** [wenzhixin/bootstrap-table#2888]
Hallo!
I am trying to learn angular2 and typescript. And this bootstrap table is my favorite component. I have used it a lot in my JS-Java project. But how can I use it in Angular2 with typescript? Can anybody help me and put an example in Fiddle?
All peopel say that typescript and angular2 sind the future of web-program. So please try to implement this bootstrap table into angular2!

Regards,
Katrina

**Comment by djhvscf** [comment]
We will work on it! Remember that any Pull Request is welcome. @katrina-engelbrecht

**Comment by alvin0618** [comment]
Use typescript component to wrap bootstrap-table.
You can refer this with some info.
https://github.com/wenzhixin/bootstrap-table/issues/3437

**Comment by wenzhixin** [comment]
No longer support angular in the latest release version.
