### ISSUE TITLE
Override ActionFormatter href

### ISSUE THREAD

**Issue by bbyhuy** [wenzhixin/bootstrap-table#2892]
I'm using http://jsfiddle.net/wenyi/e3nk137y/6490/ as an example.
Is it possible to use modal to load a webpage?
Each row will have a different url that I want it to load. I tried modifying the actionEvent, however, it seems to be appending the url to the baseurl rather than replacing it.

**Comment by wenzhixin** [comment]
You can try the curd example: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/crud/index.html

**Comment by bbyhuy** [comment]
got it working thanks!
