### ISSUE TITLE
Data-filter-control and data-height issue

### ISSUE THREAD

**Issue by yvandupre** [wenzhixin/bootstrap-table#2896]
I use data-filter-control.
When i use this option with data-height, when we do a sort or we select items, control value is not good.
If we have 10 row, we will see 10 value in the control

Tested with chrome and firefox.

Choose an item in the CustomerName select (value are Cap Corp, Tel)

After if we check value in the CustomerName select we see

Cap Corp
Cap Corp
Cap Corp
Cap Corp
Tel
Tel
Tel
Tel

[jsfiddle]() - a link to the reduced test case([fiddle template](http://jsfiddle.net/7abcv2nq/)).

If data-height is not used, that work fine.

**Comment by frin88** [comment]
that happens to me as well...Any fix or workaround available?

**Comment by ggywebtech** [comment]
Hi Guys, Is there any update to this problem? Regards

**Comment by TCS-Taylor** [comment]
I am experiencing the same issue.  LOVE this code, would really like to be able to use data-height and data-filter-control at the same time :)

**Comment by TCS-Taylor** [comment]
User @dmiszkur posted code that fixed this issue in issue# #3241 
:D

**Comment by djhvscf** [comment]
This is fixed in latest version of filter-control
