### ISSUE TITLE
How to use with .net mvc, any examples?

### ISSUE THREAD

**Issue by haco3d** [wenzhixin/bootstrap-table#2897]
There is way to use with .net mvc, I can not implement it on my system. I get errors

**Comment by djhvscf** [comment]
Can you, @haco3d, share us the errors?

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/search?utf8=%E2%9C%93&q=asp.net&type=Issues other issues maybe help you

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table-examples/issues/218

**Comment by haco3d** [comment]
Muchas Gracias
