### ISSUE TITLE
How can I set export table csv name? （能设置导出文件的名称吗？）

### ISSUE THREAD

**Issue by aiyuchen** [wenzhixin/bootstrap-table#2898]
1.导出的文件没有后缀，比如csv没有后缀.csv，txt没有.txt
2.导出的文件名不能自定义

请问如何解决

**Comment by aiyuchen** [comment]
好像只有英文网页才能显示名称正确

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by aiyuchen** [comment]
@djhvscf  How can I set export table csv name？when I export table file in Chinese web page, the name is Garbled

**Comment by martinburch** [comment]
Chinese characters seem to reproduce OK setting the export name in
```
data-export-options='{"fileName": "导出的文件名不能自定义"}'
```
See this fiddle I hacked: http://jsfiddle.net/6gd9w79u/117/
Clicking on the export icon and CSV results in the following file being downloaded:
![image](https://cloud.githubusercontent.com/assets/2335284/22865500/a89a667e-f15d-11e6-89de-0a10095f50e3.png)
@aiyuchen could you provide a fiddle to show how it's broken for you?

**Comment by aiyuchen** [comment]
@martinburch thinks

I want to add attribute `data-tableexport-display="none"` at the `<td>`，How can I set up in js？

I try to set up like this，but no effect
```
{field: 'action', title: '操作',  align: 'center', valign: 'middle', width: 300, tableexportDisplay: 'none'}
```

**Comment by martinburch** [comment]
@aiyuchen this issue is resolved and you've opened a new issue #2904 for your questions about setting data-tableexport attributes, yes?

**Comment by aiyuchen** [comment]
@martinburch yes，is about setting `data-tableexport-display` attributes

**Comment by wenzhixin** [comment]
export name problem is resolved, close this issue.
