### ISSUE TITLE
How to set up fixed width for `<td>`?

### ISSUE THREAD

**Issue by aiyuchen** [wenzhixin/bootstrap-table#2901]
Write like this：
```
{field: 'action', title: '操作', align: 'center', valign: 'middle', width: 300}
```

and `HTML` print like this
```
<th style="text-align: center; vertical-align: middle; width: 300px; " data-field="action" tabindex="0">
    <div class="th-inner ">操作</div>
    <div class="fht-cell"></div>
</th>
```
but style no effect，how to do it？

**Comment by martinburch** [comment]
Try setting a class. It's pretty easy to get this working if all you need to do is set a width that's bigger than your data. If you need to set a width that's smaller, or do other fancy things with your table layout, then you'll need to start overriding parts of bootstrap css.

Here's a basic example: http://jsfiddle.net/30sx4h3t/335/

```
<th data-field="name" data-cell-style="cellStyle" class="fixedSizeRow">Name</th>
```
```
th.fixedSizeRow{
  width: 10px;
}
```

You can also set a large width in a column's `cellStyle`

I referenced this Stackoverflow question but not too sure about the answers: http://stackoverflow.com/questions/15115052/bootstrap-how-to-set-up-fixed-width-for-td?noredirect=1&lq=1

**Comment by aiyuchen** [comment]
thanks

**Comment by jcesar020** [comment]
Thank you brother
