### ISSUE TITLE
pageList 设置后不起作用

### ISSUE THREAD

**Issue by ShawSX** [wenzhixin/bootstrap-table#2903]
设置如下：           
               pageSize: 10,  
               pageList: [10, 25, 50, 100],
页面加载完成后，点击选择页面的条数按钮没用
![image](https://cloud.githubusercontent.com/assets/12692777/22878961/ba40bf9a-f216-11e6-9c1d-9e0e96d1888e.png)

pageList中的数据也没加载过来

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by ShawSX** [comment]
bootstrap-table seting list below
pageSize: 10,
pageList: [10, 25, 50, 100],
When the table is loaded ,click the pageList button it does not work, the pageList was not loaded by the table

**Comment by wenzhixin** [comment]
@ShawSX ，table 有个 `smartDisplay` 默认为 `true`，它会自动将大于总条数的列隐藏掉。例如：
http://jsfiddle.net/wenyi/e3nk137y/11657/
http://jsfiddle.net/wenyi/e3nk137y/11658/

**Comment by ShawSX** [comment]
解决了，样式冲突导致的。

**Comment by Shaun-Yao** [comment]
遇到同样的问题，pageList不能下拉选择，设置smartDisplay: false也没有效果，版本1.14.2，使用adminLTE 2.4.18 自带的bootstrap.min.css， bootstrap.min.js

**Comment by wenzhixin** [comment]
@Shaun-Yao 没有引入 bootstrap 依赖的 popup 包吧？

**Comment by Shaun-Yao** [comment]
@wenzhixin 谢谢，引入dropdown.js就解决了

**Comment by chenxumeng** [comment]
@Shaun-Yao 请问是如何引入dropdown.js的。项目中已经引入了bootstrap.js

**Comment by wenzhixin** [comment]
@chenxumeng bootstrap 4 依赖 popper.js，你可以看下文档： https://bootstrap-table.com/docs/getting-started/introduction/#starter-template

**Comment by hoxis** [comment]
> 解决了，样式冲突导致的。

能说下怎么解决的吗，遇到 了同样的问题

**Comment by JackFe** [comment]
js资源加载顺序错误导致报错（Cannot read properties of undefined (reading 'fn')），先后顺序是jquery、popper、bootstrap
![image](https://user-images.githubusercontent.com/24237673/134978875-300a3d11-fe0d-4940-beca-17ebd9017e84.png)
