### ISSUE TITLE
bootstrap-table filter control value in the select.

### ISSUE THREAD

**Issue by yvandupre** [wenzhixin/bootstrap-table#2905]
How to control value displayed in the select for filter?
I use i180n to translate my data.

After table is rendered, I translate data.

I search a way to use bootstrap-table filter control.
Actually value displayed in the select are the value who are not translated.

Is there any event i could access to change theses value

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by yvandupre** [comment]
I feed my table like that.

In the complete, i do the translation.

Issue it's seem bootstrap-table filter control have seem to have took original value (not translated) so when i do a filter, nothing is found.

```
var memberId = $('#memberId').val();
var deferredObject = $.Deferred();
$("#memberTableResult").bootstrapTable({
          method: 'get',
          url: getHostName() + "/members/" + memberId,
          ajaxOptions: {
               headers: {"Authorization": "Basic " + $.cookie('authorization')
          },
          complete: function (jqXHR) {
               $("[data-localize]").localize("i18n", {language: "fr", pathPrefix: "locales"});
          }
    }
});
```

**Comment by djhvscf** [comment]
@yvandupre we need an example in order to see your issue, please provide us a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports)
