### ISSUE TITLE
When filterControl is input, other columns' value were matched

### ISSUE THREAD

**Issue by cnahko** [wenzhixin/bootstrap-table#2906]
When i set iuput filter in column, to match values in current column is expected, but it filtered the rows which matched other columns, like the global search box.
e.g. now we have this table and we set iuput filter in 'age' column:

| name        | age (input filter is here)         |
| ------------- |:-------------:|
| a12      | 13 |
| b13      | 14      |
| c14 | 18     |

We input '4' to filter, the result is b13 and c14, but only b13 is expected

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by cnahko** [comment]
[jsFiddle here](https://jsfiddle.net/cyuqeghz/16/)
In example, 'namespace' is similar to 'id' and editable plugin is up, maybe related to this.

**Comment by djhvscf** [comment]
@cnahko please see this [fiddle](https://jsfiddle.net/djhvscf/cyuqeghz/21/) where the plugin filter-control is working as expected.. Can you modify that one in order to show us the issue?

**Comment by cnahko** [comment]
@djhvscf No need to modify the fiddle you provided, please input 'You' to 'value' column's textbox and then you can see the issue

**Comment by djhvscf** [comment]
See this example https://jsfiddle.net/cyuqeghz/24/ 
Explanation:

- We set the `searchFormatter: false` for the Value column.
- If you set the `searchFormatter: true` then the search functionality will use the entire HTML, in this case if we search "You" in the Value column it will search in this text: `<a href="javascript:void(0)" data-name="value" data-pk="id_YouSee" data-value="V1" class="editable editable-click">V1</a>`.
Yo can see that `data-pk="id_YouSee"` has You in the text.

Please review it and let me know if you have any more question or issue
