### ISSUE TITLE
table-filter-control 'select' can not update when the table's content changed

### ISSUE THREAD

**Issue by cnahko** [wenzhixin/bootstrap-table#2907]
When use 'select' filter control, the selector's content can't update when table's content changed.
e.g.
Original table:

| name(select filter control is here) | age |
| ------ | ---- |
| aa      | 21   |
| bb     | 22  |
| cc      | 33  |

and we know, the selector's content is aa, bb and cc, then we change the table:
~~~ javascript
tableOptions.url = theNewUrl; // change url
$("#table").bootstrapTable("refreshOptions", tableOptions);
$("#table").bootstrapTable("refresh"); // refresh
~~~
now the table is:

| name(select filter control is here) | age |
| ------ | ---- |
| cc      | 33   |

unexpected, the seletor's content is still aa, bb and cc

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by cnahko** [comment]
[jsFiddle here](http://jsfiddle.net/e3nk137y/11690/)
And am I use it incorrectly? I just want to change the table's url so it can load different content, but new content loaded, the filter control selector's options update failed.

**Comment by djhvscf** [comment]
Please provide a new example since the current one is broken.

**Comment by djhvscf** [comment]
Hi! There is not any reply, in that case we are going to close this PR. Remember to add an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!
