### ISSUE TITLE
How to change the loading message?

### ISSUE THREAD

**Issue by wagnerdracha** [wenzhixin/bootstrap-table#2908]
Hi, 

how to change the loading message for this: 

`<i class="fa fa-spinner fa-spin fa-fw" style="margin: 4px 0 0 8px;font-size:2.5rem;"></i>`

Thank's

**Comment by djhvscf** [comment]
This feature is not supported. You can pass as parameter a plain text.

http://bootstrap-table.wenzhixin.net.cn/documentation/#localizations

**Comment by djhvscf** [comment]
Close this issue. Ref: #2909

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/e3nk137y/11683/
http://jsfiddle.net/wenyi/e3nk137y/11685/
