### ISSUE TITLE
Loading message should support HTML

### ISSUE THREAD

**Issue by djhvscf** [wenzhixin/bootstrap-table#2909]
The loading message should support this:

```html
<i class="fa fa-spinner fa-spin fa-fw" style="margin: 4px 0 0 8px;font-size:2.5rem;"></i>
```
by @wagnerdracha
ref: #2908

**Comment by wenzhixin** [comment]
@djhvscf Supported this feature:
http://jsfiddle.net/wenyi/e3nk137y/11683/
http://jsfiddle.net/wenyi/e3nk137y/11685/
