### ISSUE TITLE
页面跳转后返回

### ISSUE THREAD

**Issue by hidsvip** [wenzhixin/bootstrap-table#2911]
使用js 的   history.back()  返回到表格页面， 无法保留之前看的页数，   看过文档没找到相应实现方法， 不知不是用modal有什么好的解决方案？  Table Editable 不是很合适。。。

**Comment by wenzhixin** [comment]
你可以考虑用 cookie 插件保存状态：http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html
