### ISSUE TITLE
Customize view of cell data, not value.

### ISSUE THREAD

**Issue by xoorath** [wenzhixin/bootstrap-table#2916]
Hey,

I'm building a json editor, a lot of features of bootstrap-table were attractive for this. Here's how it's looking:

![image](https://cloud.githubusercontent.com/assets/769014/23068411/91391b0a-f4f1-11e6-9e43-337d90f80b7d.png)

My issue is how I'm decorating the "tree" portion. Because the `formatter` option for a column changes the value itself, it doesn't seem appropriate for decorations. The reason is that the entire value would then contain a span for a prefix and a span for a postfix, making the value not easily re-serializable back into json. It also makes it so attributes on any of these tags I could put into a prefix such as `<span class="prefix">` would break the value attribute in the table `<a data-value="<span class="prefix"></span>text</a>"` obviously messes with the value attribute because there are quotes inside the attribute string.

Anyways, that's all to say I opted for decorating the table myself:

```
$nameDataEntry.prepend($('<span>').addClass('prefix').text(dataObj.GetPrefixText()));
$nameDataEntry.append($('<span>').addClass('postfix').text(dataObj.GetPostfixText()));
```

![image](https://cloud.githubusercontent.com/assets/769014/23068680/a1f221e8-f4f2-11e6-88b4-6055ade3ff0a.png) 
![image](https://cloud.githubusercontent.com/assets/769014/23068694/b3d7073e-f4f2-11e6-8e46-07b0369a16aa.png) 
![image](https://cloud.githubusercontent.com/assets/769014/23068710/bbbfe3d0-f4f2-11e6-9ba5-fa0df69ee20a.png)

The issue as it might jump out to you: any search or insertion I do into the table will clear this style from every cell.

Do you have any advice on decorating text in a cell? The desired effect is of course that I can modify just the values of these cells like so:

![image](https://cloud.githubusercontent.com/assets/769014/23068753/e09839f0-f4f2-11e6-9b11-91dc29a35370.png)

I appreciate any advice you might have for me.

**Comment by martinburch** [comment]
Perhaps you could set cellStyle on this column? You could use that to add CSS that would set the left margin/padding and attach the image with ::before as appropriate.

**Comment by wenzhixin** [comment]
Tree column http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/tree-column.html?

**Comment by pchaganti** [comment]
👍

**Comment by UtechtDustin** [comment]
I close this issue because its already 2 years old, if you still need help with that please reopen the issue.
