### ISSUE TITLE
bootstrap-table.js bug

### ISSUE THREAD

**Issue by ronaldoWang** [wenzhixin/bootstrap-table#2918]
js两处bug：
1、`html.push('<tr class="no-records-found">',
                sprintf('<td colspan="%s">%s</td>'+
                    this.$header.find('th').length, this.options.formatNoMatches()),
                '</tr>');`

应该改为 `html.push('<tr class="no-records-found">',
                sprintf('<td colspan="%s">%s</td>',
                    this.$header.find('th').length, this.options.formatNoMatches()),
                '</tr>');`
即'<td colspan="%s">%s</td>'后面是，而不是+，不然“没有找到匹配的记录”几个字无法在table显示
2、当table只有一条记录时，点击查询，如果后台未查到数据，前台table还是显示之前的那一条数据
```
`BootstrapTable.prototype.load = function (data) {
        var fixedScroll = false;

        // #431: support pagination
        if (this.options.sidePagination === 'server') {
            this.options.totalRows = data[this.options.totalField];
           //判断长度是否为0，如果为0，清空table原有的data数据
            if(0==this.options.totalRows){
            	this.options.data.splice(0, this.options.data.length);//
            }
            fixedScroll = data.fixedScroll;
            data = data[this.options.dataField];
        } else if (!$.isArray(data)) { // support fixedScroll
            fixedScroll = data.fixedScroll;
            data = data.data;
        }

        this.initData(data);
        this.initSearch();
        this.initPagination();
        this.initBody(fixedScroll);
    };`
```

需要判断返回的json里，data是否有row属性（通常未查询到集合，返回的json对象里并没有row），判断一下this.options.totalRows如果为0，则清除查询前table里的data，否则前台table还是显示之前的那一条数据

**Comment by wenzhixin** [comment]
第一个问题已经修复，第二个问题一般情况下，假如没有值，服务器应该是返回
```
{
    total: 0,
    rows: []
}
``
才是正确的，我们在用的系统都是这样的。即使返回的不是这样也可以通过 `responseHandler` 进行处理：
```
responseHandler(res) {
  return {
    total: res.total || 0,
    rows: res.rows || []
  };
}
```
