### ISSUE TITLE
When I Set "clickToSelect",I cann't click the "checkbox"

### ISSUE THREAD

**Issue by zaiting** [wenzhixin/bootstrap-table#2919]
带有Checkbox的table，我想实现点击行的时候勾中Checkbox，设置“clickToSelect”为true后，点击行可以选中Checkbox，但是当我直接点击Checkbox的时候却不能选中

I have a table with Checkbox，and i want to check the checkbox when i click the row.I set "clickToSelect" with true,and when i click the row i can check the checkbox,but when i click the checkbox immediatly, i cann't check the checkbox.

**Comment by aiyuchen** [comment]
这里要被中国攻城狮占领了

**Comment by wenzhixin** [comment]
没有你说的问题：http://jsfiddle.net/wenyi/e3nk137y/30/，假如问题还存在的话请提供 jsfiddle，谢谢。

**Comment by zaiting** [comment]
好的，谢谢。你的demo确实可以，我产品里面选不了，我这边再看看，感谢。

**Comment by wenzhixin** [comment]
* 看看版本是否是最新的
* 是否其他的代码冲突了
