### ISSUE TITLE
How to addeventlistener in the table was created over

### ISSUE THREAD

**Issue by aiyuchen** [wenzhixin/bootstrap-table#2920]
I want to do something in the table was created over. How to do it?

**Comment by wenzhixin** [comment]
[`onPostBody`](http://bootstrap-table.wenzhixin.net.cn/documentation/#events)

**Comment by aiyuchen** [comment]
若数据从服务器加载的，`onPostBody`会执行两次，第一次得到的是`undefined`，第二次获得的才是表格数据，不知道是不是BUG

好在还有一个方法`onLoadSuccess`，我使用这个了

**Comment by wenzhixin** [comment]
onPostBody 执行两次是因为首次初始化还没请求，你可以判断下，`onLoadSuccess` 也是OK的，不过不适用使用 `data` 的方式。
