### ISSUE TITLE
Group-by-v2 + editable dropdown

### ISSUE THREAD

**Issue by airtonjr** [wenzhixin/bootstrap-table#2922]
Hello ALL, 

I am using the editable plugin but I would like to use group-by-v2 but when I try to group by the column "Group" in the group title it shows the ID for the editable-dropdown. 

Would be possible to get the text instead the value?

Thank you. 

![groupcapture](https://cloud.githubusercontent.com/assets/7409463/23112001/2da91ccc-f6f2-11e6-973f-593cc4d2ed85.PNG)

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by airtonjr** [comment]
Hey @wenzhixin ,

Actually is pretty simple my question.

I have:
```

$("#table").bootstrapTable({
    idField: 'id',
    toggle: "table",
    search: true,
    showRefresh: true,
    showColumns: true,
    groupBy: true,
    groupByField:  "group_id",
    showExport: true,
    striped: true,
    hover: true,
    clickToSelect: true,
    singleSelect: true,
    pagination: true,
    toolbar: "#toolbar",
    editableUrl: "./process/edit=daily_entry",
    url: "./process/table=group",
    columns: [{
        field: 'state',
        title: '',
        checkbox: true
    }, {
        field: "group_id",
        title: "Group",
        editable: {
                    type: 'select',
                    sourceCache: false,
                    validate: function(value) {
                        if($.trim(value) == '') {
                        return 'This field is required';
                        }
                    },
                    source:  "../process/drop.php?t=group"
                }
    },  {
        field: "count",
        title: "Count",
        sortable: true,
          editable: {
                type: 'text',
                inputclass: 'number',
                display: function(value) {
                        $(this).number(value, 0);
                    },
                validate: function(value) {
                    if($.trim(value) == '') {
                    return 'This field is required';
                    }
                }                
            }
}]
```

I am using  **groupBy: true** and **groupByField:  "group_id"** and since the field "group_id" is editable I am loading the dropdown but I just need to know if is possible to use the option text "Group 001" instead the value "11" in the groupby title. 

Thank you

**Comment by UtechtDustin** [comment]
The group by extension will be merged/rewritten, this issue will be checked in #4413.
