### ISSUE TITLE
How to add Other content (like Header,, Footer) on pdf in bootstap table export extension.

### ISSUE THREAD

**Issue by vandaluri** [wenzhixin/bootstrap-table#2924]
I using Bootstrap table and Export PDF. I can able to download the pdf and working fine.
But, I wanted add some other content on pdf page how can i pass those details in **exportOptions** object. 

Can you please help me  here is my code
<pre>
 $('#document').ready(function () {
        
        $.ajax({
            url: '../api/UserApi/',
            type: 'GET',
            dataType: 'json',
            data: null,
            success: function (data) {
                $("#tblUsers").bootstrapTable('load', data);
            },
            error: function (xhr, textStatus, errorThrown) {
                console.log(textStatus);
            }
        });

        //
        $('#tblUsers').bootstrapTable({
            exportOptions: {
                fileName: 'Users',
                worksheetName: 'Users_o',
                jspdf: {

                    orientation: 'l',
                    autotable: {
                        startY: 50,
                        startX: 50,
                        showHeader: 'firstPage',
                        theme: 'grid',
                        styles: {
                            cellPadding: 2,
                            rowHeight: 12,
                            fontSize: 10,
                            fillColor: 255,
                            textColor: 50,
                            fontStyle: 'normal',
                            overflow: 'ellipsize',
                            halign: 'left',
                            valign: 'middle'
                        },
                        headerStyles: {
                            fillColor: [52, 73, 94],
                            textColor: 255,
                            fontStyle: 'bold',
                            halign: 'center'
                        },
                        alternateRowStyles: {
                            fillColor: 245
                        },
                        addPageContent: function (data) {

                        },

                        createdHeaderCell: function (cell, data) { },
                        tableExport: {
                            onAfterAutotable: null,
                            onBeforeAutotable: null,
                            onTable: null
                        }
                    }
                }
                //ignoreColumn: [0]
            }
        });
    });
</pre>

**Comment by ibraheemhlaiyil** [comment]
PR #2925 allows the table's footer to be included in the export.

I also tried to play with autotable PDF export to support exporting a complex header but it seems it's not easy to support more than one header row correctly (i.e. colspan/rowspan).

If you want to add a header above the actual table using the PDF doc object this would be straightforward.

**Comment by vandaluri** [comment]
In jsPDF we have straightforward object is add header in pdf.. using Bootstrap-table it is not supporting

**Comment by wenzhixin** [comment]
@vandaluri  Can you provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show the problem, thanks!

**Comment by Falseee** [comment]
I close this issue because its older than 2 years, pls reopen it if you still need help
