### ISSUE TITLE
How can I disable a row, or cell

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#2926]
How can I disable a row, or cell? I don't want to hide row, instead, I want to disable the whole row by unique id, or buttons inside a cell of that row?

Thanks much!

**Comment by wenzhixin** [comment]
I don't know what you mean, disable to click the row or change the color of the row?

**Comment by startovernow** [comment]
Thanks for your help, here are some more information, 

I have 3 columns with Edit, Save, Cancel button, at beginning, only Edit button column is shown, after Edit button is clicked, the Save and Cancel column are shown. But I only want to edit the first row, so I want to disable other rows' Save/Cancel button, or disable all other rows so they are not clickable.

How can I do this? Thanks!

![untitled](https://cloud.githubusercontent.com/assets/18681747/23148683/d1c775a0-f7ac-11e6-850b-659cb26c82b6.png)

**Comment by wenzhixin** [comment]
`formatter` can do what you want:
```js
formatter(value, row, index) {
    if (index === 0) {
        // return enable formatter
    } else {
        // return disable formatter
    }
}
```
