### ISSUE TITLE
Modal Table Inside Detail View with queryparams

### ISSUE THREAD

**Issue by bbyhuy** [wenzhixin/bootstrap-table#2931]
So currently the main html page holds a bootstrap table. 
Each row in the table has a detail view. 
Under the detail view, there is a clickable link which opens up a modal bootstrap table. 
I was able to get queryparams working with static variables. 

What i want to do is for example. 
Say the row id = 1 on main table.
When i click the modal table inside the detail view of that row, I want to pass the id = 1 to the queryParams function. Is there a way to do this?

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by bbyhuy** [comment]
http://jsfiddle.net/3hefyLfh/5/

Not a perfect example, because I don't  have a proper API to call. But, if you see the modal table.
It has data-url="/my/api/path" 

I would like queryparam to be able to append to the data-url during the call based on each unique cell on the original table.

For example, 

Table Row = 1
Modal Table data-url = "/my/api/path/?id=1&item=item1"

Table Row = 2
Modal Table data-url = "/my/api/path/?id=2&item=item2"

**Comment by wenzhixin** [comment]
Solution: http://jsfiddle.net/wenyi/3hefyLfh/6/

![image](https://cloud.githubusercontent.com/assets/2117018/23284900/e645f74a-fa68-11e6-9f2e-10cb62d864b4.png)

**Comment by bbyhuy** [comment]
perfect thanks @wenzhixin

**Comment by wenzhixin** [comment]
You are welcome!
