### ISSUE TITLE
表格里面显示是001，导出数据是1

### ISSUE THREAD

**Issue by guiy2** [wenzhixin/bootstrap-table#2935]
当导出的类型选择excel的时候，导出来显示是1

**Comment by guiy2** [comment]
当导出的类型是excel的时候

**Comment by wenzhixin** [comment]
https://github.com/hhurz/tableExport.jquery.plugin/issues/81

**Comment by CSGrandeur** [comment]
But how to add "data-tableexport-msonumberformat" option in bootstrap-table？

**Comment by hhurz** [comment]
Use the ```onMsoNumberFormat``` callback function when exporting in excel format. Something like that:
``` javascript
  $(document).ready(function()
  {
    $('#table').bootstrapTable('refreshOptions', {
        exportOptions: {onMsoNumberFormat: DoOnMsoNumberFormat}
    });
  });

  function DoOnMsoNumberFormat(cell, row, col) {
     return (row > 1 && col == 0) ? '\\@' : '';
  }

```

**Comment by wenzhixin** [comment]
Example: https://live.bootstrap-table.com/code/wenzhixin/1192
