### ISSUE TITLE
FilterControl input field don't show

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#2936]
With the version 1.11.1, when a table have a field with filtercontrol like "input", the input field is doen't showing.
To the next link, they is an example where the column Key and Value have filtercontrol like "input" and the input field it doesn't showing.
https://jsfiddle.net/cyuqeghz/20/

**Comment by manukieli** [comment]
I've add filterControlPlaceholder: "" and the input field is visible.
It's resolved.

**Comment by djhvscf** [comment]
See https://github.com/wenzhixin/bootstrap-table/pull/2938
