### ISSUE TITLE
Sorting by datetime issues

### ISSUE THREAD

**Issue by mlgwebiz** [wenzhixin/bootstrap-table#2937]
Hi I'm having an issue with sorting by datetime, it sorts the date correctly the time is not in order. Any quick fix for this?

my row is 
 `   <th data-field="CREATED_AT" data-sortable="true">LIST DATE</th>`

Example sort 

This is what I am getting, notice the last one should be the second on the list.

2/21/2017 12:45:16 PM	 
2/20/2017 10:54:25 AM	 
2/20/2017 10:38:29 AM	
2/20/2017 10:28:50 AM	
2/20/2017 10:19:27 AM	 
2/20/2017 10:04:54 AM	 
2/20/2017 1:46:35 PM

This is what it should be

2/21/2017 12:45:16 PM	 
2/20/2017 1:46:35 PM
2/20/2017 10:54:25 AM	 
2/20/2017 10:38:29 AM	
2/20/2017 10:28:50 AM	
2/20/2017 10:19:27 AM	 
2/20/2017 10:04:54 AM	 

any thoughts or suggestions on this?

**Comment by wenzhixin** [comment]
You can use `sorter` column option to solve your problem.

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-sort.html
