### ISSUE TITLE
latest dist version on npm is still 1.11.0 and not 1.11.1

### ISSUE THREAD

**Issue by yurii-polishchuk** [wenzhixin/bootstrap-table#2939]
Hi guys, thanks for delivering new 1.11.1 version. Appreciate your work!

Recently, I noticed, that bootstrap-table was updated on npm too, but it looks like that it was updated only partly. For example, when I do:

```
npm install
```

With my package.json:

  ```
"dependencies": {
    "bootstrap-table": "1.11.1"
  }
```

In node_modules/bootstrap-table/ dir I have two subfolders (and a lot of other stuff too):

/src/ with version 1.11.1
and /dist/ with version 1.11.0, it even contains header copyright comment, like:
```
/**
 * @author zhixin wen <wenzhixin2010@gmail.com>
 * version: 1.11.0
 * https://github.com/wenzhixin/bootstrap-table/
 */
```

I will appreciate if someone could re-update npm repo.

**Comment by wenzhixin** [comment]
I have republished the new version to: https://www.npmjs.com/package/bootstrap-table, thanks for your feedback.

**Comment by yurii-polishchuk** [comment]
@wenzhixin sorry to mention it again, but it looks like that npm repo still contains part of 1.11.0 for /dist/ folder.  The /src/ folder contains 1.11.1 version. I've cleared all the cache and run fresh ```npm install```

**Comment by yurii-polishchuk** [comment]
I've even tried to download it directly: [https://registry.npmjs.org/bootstrap-table/-/bootstrap-table-1.11.1.tgz"](https://registry.npmjs.org/bootstrap-table/-/bootstrap-table-1.11.1.tgz")
