### ISSUE TITLE
jsdelivr.com Support

### ISSUE THREAD

**Issue by nikmauro** [wenzhixin/bootstrap-table#294]
CDN lib for bootstrap table in http://www.jsdelivr.com/

**Comment by kokarn** [comment]
There is actually a good reason to add more CDNs, especially JSDelivr because of their generated javascript files.

**Comment by wenzhixin** [comment]
Can you help to add? @kokarn, @nikmauro

**Comment by kokarn** [comment]
Sure thing! 
You don't have to do anything, the pull request is here https://github.com/jsdelivr/jsdelivr/pull/4882

**Comment by wenzhixin** [comment]
Thanks @kokarn
