### ISSUE TITLE
Pagination border appears after upgrade to 1.11.1 from 1.11.0

### ISSUE THREAD

**Issue by fsauter** [wenzhixin/bootstrap-table#2940]
Hi together,

I've just updated to the latest bt version (1.11.1 from 1.11.0). 

Now the div with the class `fixed-table-pagination` has a border (didn't have it before). Am I the only one with this issue? I can not see any changes in the markup/css styles using Chrome Dev Tools **except** that `fixed-table-container`, which has the border css property, is using now the whole height including the `fixed-table-pagination` div.

Before |After
------------ | -------------
![1_11_0](https://cloud.githubusercontent.com/assets/536192/23238302/92615122-f961-11e6-915e-a8994dbb57aa.png) | ![1_11_1](https://cloud.githubusercontent.com/assets/536192/23238303/9261bd06-f961-11e6-8c5d-6d8e82e9887b.png)

**Comment by djhvscf** [comment]
Is it possible to share us a example? I couldn't reproduce it

**Comment by fsauter** [comment]
Seems like I can't reproduce it on jsfiddle... If I find a way I'll let you know. Thanks for the quick check!

**Comment by yurii-polishchuk** [comment]
@fsauter and @djhvscf could we reopen this? Here is an example via jsfiddle:

[https://jsfiddle.net/etj9hdbr/](https://jsfiddle.net/etj9hdbr/)

When you are not setting a data-height of a table or setting it to "" this CSS border is shown.

As @fsauter mentioned, there is added style: .fixed-table-toolbar:after, .fixed-table-pagination:after
Looks like this style ws added with #2405

**Comment by fsauter** [comment]
@yurii-polishchuk Thanks for your finding.  Do you have an idea how to fix this?

**Comment by zhangfy** [comment]
I met the same problem.How to fix it?

**Comment by zhangfy** [comment]
![image](https://cloud.githubusercontent.com/assets/2948502/25432045/8e06ebca-2ab5-11e7-806f-e44752458420.png)

**Comment by vingorius** [comment]
+1

**Comment by mtaylor091** [comment]
The css in 1.11.1 is: 

```
/* for get correct heights  */
.fixed-table-toolbar:after, .fixed-table-pagination:after {
    content: "";
    display: block;
    clear: both;
}
```

I am not a CSS expert at all. I just played with toggling each property individually and they all fix this issue. So I just chose to comment out clear: both for now...

**Comment by wenzhixin** [comment]
Fixed in develop: https://jsfiddle.net/wenyi/etj9hdbr/4/

**Comment by adambiggs** [comment]
I still have this problem with v1.11.2
