### ISSUE TITLE
Param not updated in the url of the boostrap table

### ISSUE THREAD

**Issue by yvandupre** [wenzhixin/bootstrap-table#2942]
I use bootstrap, jquery and bootstrap-table When i go to a tab , i call an js function.

In this function i init a bootstrap-table who use a param. First time i go to the tab, that work fine.

If i got to another tab, to change the param. when i come back to the tab, it's the old value of the param who are used.

If first time memberId = 5... I go to another tab... memberId is 2... but in the boostrapTable that continue to be 5

```
var initMemberPayment = function initMemberPaymentTable() {
    var memberId = $("#memberId").val();
    $("#memberPaymentTableResult").bootstrapTable({
        url: getHostName() + "/members/" + memberId + "/payments",
     ...
     });
     ...
};
```

I don't really understand why. https://paste.ofcode.org/PwUUTKyEQCin4VYx2swdKp

**Comment by djhvscf** [comment]
Mmm I think you can destroy it and recreate or use the `refreshOptions` method

**Comment by wenzhixin** [comment]
Now `refresh` method supports `pageNumber` and `pageSize` parameters.
