### ISSUE TITLE
Access detail view in onCollapseRow event

### ISSUE THREAD

**Issue by trudger123** [wenzhixin/bootstrap-table#2944]
Thanks for the great component !

I want to use detail view as editor for the row so I can change detail when it's expanded. Then, I want to update internal object when it's collapsed.  The problem is that the detail view has been removed in onCollapseRow event so I can't access the view anymore. Is there a way I can access the detail when it's collapsed? e.g. something like "onBeforeDetailviewRemoved". 

Thank you!

**Comment by Josh688** [comment]
Would adding 'before-detailview-removed.bs.table': 'onBeforeDetailviewRemoved' to BootstrapTable.EVENTS along with creating the function, then adding that.trigger('before-detailview-removed', row) just before $tr.next().remove(); work? I needed the same thing and this is what I did to get around the detailview data being removed before having a chance to read it.

**Comment by Falseee** [comment]
The third parameter contains the detailView, added missing documentation in #4277.
