### ISSUE TITLE
how can I get the data-title using detail-view?

### ISSUE THREAD

**Issue by vivianyeah** [wenzhixin/bootstrap-table#2946]
I would like to use the detail view like following, and I am editing the detailFormatter function, how can I get the data-title in the function(not the data-field name)? Thank you very much
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/detail-view.html

**Comment by Falseee** [comment]
If you use the [detailFormatter](https://bootstrap-table.com/docs/api/table-options/#detailformatter) you get as second parameter the whole row, so if the title is in the row just do `row.title`.

I close this issue because its older then 3 years, pls reopen it if you still need help with that.
