### ISSUE TITLE
text wrap - tooltip and fixed column height

### ISSUE THREAD

**Issue by manohards29** [wenzhixin/bootstrap-table#2947]
I like the idea of bootstrap wrapping the text inside each cell. But for some columns I do not want the text to get wrapped and increasing the cell height. Instead, it should show whatever the text that fits in cell and full text should be shown as a tool-tip on cell hover. Cell height should remain fixed(one line of text). Because wrapping in one column increases cell height for all columns. Is there a way to overcome this?

**Comment by wenzhixin** [comment]
You can use css style and tooltip to solve your problem.
ref #899
