### ISSUE TITLE
Hide columns

### ISSUE THREAD

**Issue by manohards29** [wenzhixin/bootstrap-table#2948]
Is there an option for the developer to pass list of columns to plug-in as and only those columns should be available for the end-user in column switcher. Because I am storing ids received from database in hidden column and I do not want the end user to know about that column at all. I did not find any way to remove that hidden column from column switcher. Is there an option that I am missing to achieve this?

**Comment by djhvscf** [comment]
Did you use the column option switchable?

**Comment by manohards29** [comment]
I had not set that option and it was taking default(switchable:true). Using it solved my problem. Thanks.

**Comment by djhvscf** [comment]
Great!
