### ISSUE TITLE
Sort using JavaScript

### ISSUE THREAD

**Issue by manohards29** [wenzhixin/bootstrap-table#2949]
Is it possible to do call a sort function to sort any column using JavaScript ?
For example: $table.bootstrapTable('sort', field, order);

**Comment by djhvscf** [comment]
No, this feature is not supported. You can use the `customSort` table option or the `sorter` column option

**Comment by manohards29** [comment]
Is there an example available for using customSort option?

**Comment by horkenw** [comment]
you can find out example here
http://jsfiddle.net/e3nk137y/4248/

In http://bootstrap-table.wenzhixin.net.cn/examples/  Sort

**Comment by manohards29** [comment]
@horkenw 
Thanks.
