### ISSUE TITLE
Localization question

### ISSUE THREAD

**Issue by henke-d** [wenzhixin/bootstrap-table#295]
I love your solution for bootstrap-table, just perfect! But how should the localization files be used? Pleas e advise, because w/o localization it can not be used at all.

Sorry, I dont know how to label it a question either? :-)
Br

/Henrik

**Comment by wild024** [comment]
how can I localize my bootstrap-table data with Bengali Language. please help me .........

**Comment by UtechtDustin** [comment]
@wild024 Its quite good documentated: https://bootstrap-table.com/docs/api/localizations/

**Comment by wild024** [comment]
@UtechtDustin yes I saw this before but there is no jar file which supports Bengali language

**Comment by UtechtDustin** [comment]
Then we currently dont support that language, feel free to create a file for that language (its quite easy).
We are happy about every pull request.

**Comment by wild024** [comment]
@UtechtDustin  trying and waiting for better support. thanks in advance my dear.

**Comment by UtechtDustin** [comment]
@wild024 i think there is a very small chance someone will translate it.
We can't translate all languages, so we need help from the community.
Its quite easy to create that file (copy the english version and rename it to the benali shortcode, change the text and commit it).

**Comment by wild024** [comment]
@UtechtDustin  Ok I will try with your advice,if i success i will share it to the community. thanks a lot
