### ISSUE TITLE
$table.bootstrapTable('insertRow' not work when useRowAttrFunc: true

### ISSUE THREAD

**Issue by AtuGao** [wenzhixin/bootstrap-table#2950]
$table.bootstrapTable({
            data: $shJson.params,
            columns: columns,
            showRefresh: false,
            showColumns: false,
            search: false,
            pagination: false,
            reorderableRows: true,
            useRowAttrFunc:true

        });
        $table.on('reorder-row.bs.table', function (e, data) {
            console.log(data);  //working
        })
...
     $table.bootstrapTable('insertRow', {index: 0, row: row});   // not work

**Comment by djhvscf** [comment]
Do you have any example with this issue?

**Comment by Falseee** [comment]
I close this issue because its older than 2 years and we got no response (example) from you.
If you still need help pls reopen the issue.
