### ISSUE TITLE
How to use the `data-show-footer` table option?

### ISSUE THREAD

**Issue by johnnymetz** [wenzhixin/bootstrap-table#2952]
I'd like to disable sorting on the last row in my table (which is a "Totals" row). I would normally achieve this by wrapping the last row in a `<tfoot>` tag; however, the `<tfoot>` tag doesn't work with column visibility functionality (e.g. the `<tfoot>` row doesn't disappear as it's supposed to).

I've seen this functionality in the "bootstrap-sortable" plug-in by adding the `data-disablesort="true"` attribute to the `<tr>` you're trying to disable sorting for.

Is there any way to do this? Am I using the `<tfoot>` tag incorrectly?

**Comment by jonathanmetz** [comment]
Figured out how to set a static footer row that works with the `data-show-columns` option. See my answer here: http://stackoverflow.com/questions/37670909/is-it-possible-to-fix-footer-in-bootstraptable/42497942#42497942

This may be a good example to include in the docs / examples!

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/#options/show-footer.html
