### ISSUE TITLE
TreeGrid cell lines

### ISSUE THREAD

**Issue by krosoftware** [wenzhixin/bootstrap-table#2953]
Hello
is it possible to display cell lines in TreeGrid example, like it is on normal table.
Currently, treegrid column is displayed without grid lines.
Thank you.

**Comment by krosoftware** [comment]
Anybody, please?

**Comment by djhvscf** [comment]
Do you have any example?

**Comment by krosoftware** [comment]
Hello, if you navigate here: http://imgur.com/2RYWsuG you can see that columns ID, PID and Item Price have all grid lines (horizontal and vertical) and tree column (Item Name) have not those grid lines so it does not look nice. What I need is that also tree column have horizontal and vertical grid lines, like all other columns. Thank you.

**Comment by krosoftware** [comment]
Hello @djhvscf , any idea how to get cell lines on tree area, please?

**Comment by Falseee** [comment]
I close this issue because its 2 years old, if you still need help pls provide us an [jsFiddle](https://jsfiddle.net/).
