### ISSUE TITLE
Incorrect pagination caret styling

### ISSUE THREAD

**Issue by deser** [wenzhixin/bootstrap-table#2954]
When pageList is closed: https://monosnap.com/file/1upolcOf4ykvcz2PdmXMdeGOe4dcHh
When open: https://monosnap.com/file/OxzbgiJf0Qd6Mt6swCD3loLPxE8Hxb

The same

**Comment by djhvscf** [comment]
This is a built-in feature. See this example https://getbootstrap.com/docs/3.3/components/#dropdowns
