### ISSUE TITLE
Issue with Cookie extension

### ISSUE THREAD

**Issue by carolgomesm** [wenzhixin/bootstrap-table#2955]
When using the Cookies extension, if you are on the last page and delete the row (by deleting a record on the database) you can't access the records on the previous pages.

**Comment by djhvscf** [comment]
@carolgomesm can you provide us an [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), please?

**Comment by Falseee** [comment]
I close this issue because its older than 2 years, if this error still exists pls reopen this issue and provide us an jsFiddle.
