### ISSUE TITLE
[pagination] click the the page twice (e.g. page 2), the location will be changed to document.baseURI + "#" 

### ISSUE THREAD

**Issue by zhou9197** [wenzhixin/bootstrap-table#2956]
as title

for all **'href="#"'** in pagination, changing **"#"** to **"javascript:void(0);"** can fix this problem.
other **&lt;a href="#"&gt;** may cause the same problem

**Comment by happymzw** [comment]
the latest version 1.11.1 has the problem, can fix?but 1.9.0 is javascript:void(0)

**Comment by Falseee** [comment]
Cant reproduce the issue on our [examples](https://examples.bootstrap-table.com/), if this is still a thing pls reopen the issue.
