### ISSUE TITLE
detailView展开column的宽度如何固定？

### ISSUE THREAD

**Issue by 2fumin** [wenzhixin/bootstrap-table#2957]
![qq 20170228170439](https://cloud.githubusercontent.com/assets/3716544/23398650/52e87914-fdd8-11e6-8cb2-52f99e7cd248.jpg)
如图所示

**Comment by Falseee** [comment]
Looks good for me (https://examples.bootstrap-table.com/index.html#welcomes/sub-table.html), pls update to the newest version.
If you still have the error, pls reopen the issue and prove an example (jsfiddle).
Also please write in english.
