### ISSUE TITLE
POST请求，Content-Type是application/json问题

### ISSUE THREAD

**Issue by 960339491** [wenzhixin/bootstrap-table#2958]
大神 你好  

我现在用bootstrap-table 这个表格的时候 发现个问题，不知道是我的问题  还是bootstrap-table的BUG

http://admin.qianxunclub.com/sys/user/list 

这个是我的数据接口，POST请求，Content-Type是application/json

http://asone.qianxunclub.com/ 

这个是调用的前端页面  会出现错误 

感谢大神  求助啊

（这里不能粘贴图片 好坑，我发邮件到<wenzhixin2010@gmail.com>了）

**Comment by wenzhixin** [comment]
这个问题应该解决了吧，在群上好像说过。
