### ISSUE TITLE
[cell width&height] How to set the width and height

### ISSUE THREAD

**Issue by zhou9197** [wenzhixin/bootstrap-table#2959]
**purpose**: i'd like to display a long text in **one line.**. let the width fit the length of the text with horizontal scrollbar shown.
**the fact:**: but when it is long enough, it will display in two or more lines and at the same time, other cells' width become short.
**bad methods**: i've tried to set width of each column in columns: [{field: 'eg',title: "eg",width:"1111px",}] or set the height of row in rowStyle: function() {return {css: {"height": "50px"}}}
**results**: but none works fine. the width is short and the height is long then what is expected.

please help me to fix it. many thanks.

**Comment by thomas-nguyen-3** [comment]
Try this:
 return {css: {'white-space': 'nowrap'}};

example in cellStyle: specify for grid.
{ title:'abc', field: 'abc', cellStyle: cellStyle,   sortable: true, visible: true}

and use function like this to add the css:
      function cellStyle() {
        return {css: {'white-space': 'nowrap'}};
      }

hopefully it works for you, I have not test the rowStyle yet. but cellStyle works for me. update how it goes !

**Comment by Marskey** [comment]
add style="table-layout:fixed;" to your table like `<table style="table-layout:fixed;"></table>`. should help

**Comment by marlenesco** [comment]
Look at this: https://github.com/wenzhixin/bootstrap-table/issues/3701#issuecomment-390940637

**Comment by Falseee** [comment]
#3701 
https://bootstrap-table.com/docs/api/column-options/#width
