### ISSUE TITLE
INSTALLLING WITH WINDOWS SERVER AND WAMP

### ISSUE THREAD

**Issue by mbsarino** [wenzhixin/bootstrap-table#296]
Hello everyone!  I would like to know if it is possible to install bootstrap table on a Windows server with WAMP 2.5?  Also. is it possible to connect bootstrap-table to an sql database?

I am not a programmer and have a bit of working knowledge on web development so I am hoping I can use bootstrap table to make things easier for me to modify our site.

Any feedback is greatly appreciated!!!

**Comment by wenzhixin** [comment]
It's possible! Just use it.
