### ISSUE TITLE
TypeError at Table Filter

### ISSUE THREAD

**Issue by talivan0009** [wenzhixin/bootstrap-table#2960]
Hi, thanks for the bootstrap table and the datepicker plugin. It's a wonderful job!

My java console throws me "Uncaught TypeError: Cannot read property 'filterStrictSearch' of undefined" at bootstrap-table-filter-control.js. The way I inserted the data was through JSP and recolecting the data from MySQL now() format (YYYY-MM-DD). I did change the date form if you see the attached Jsfiddle. 

Anything you need, I ll be in touch.

Jsfiddle([jsfiddle](http://jsfiddle.net/talivan0009/hbntvzzm/)).

**Comment by Insood** [comment]
Were you ever able to fix this? I have the same issue.

**Comment by Falseee** [comment]
Your example works for me, also the issue is already a year old.
If you still need help pls reopen the issue.
