### ISSUE TITLE
singleSelect + maintainSelected + pagination = bug

### ISSUE THREAD

**Issue by deser** [wenzhixin/bootstrap-table#2963]
Hello, I've noticed that when grid is configured to be `singleSelect ` + `maintainSelected ` and it has pagination then `singleSelect` option get's broken when you select on different pages. For example: I select on first page, then I go to the next page select here, then call `getSelections` and it returns array of 2.

Expected: whenever `singleSelect` is set up it should uncheck selections even on other pages.

**Comment by deser** [comment]
All in all the problem is in `singleSelect` when pagination is enabled: check some row on first page then go to the next page check some row again and `getSelections` will return 2 rows selected (expected 1)

**Comment by deser** [comment]
JSFiddle: https://jsfiddle.net/3mou92px/11/

**Comment by deser** [comment]
Guys, will fix of this bug appear in 0.11.2?
Thanks

**Comment by zyairzy** [comment]
I also find this bug(version 0.11.1).
Here are my work around, but i'm not sure whether cause other bug in this way.

1. change this.options.data to this.data in getSelections method:
    BootstrapTable.prototype.getSelections = function () {
        var that = this;
        return $.grep(this.data, function (row) {
            // fix #2424: from html with checkbox
            return row[that.header.stateField] === true;
        });
    };

2. change this.data to this.options.data in resetRows method: 
    BootstrapTable.prototype.resetRows = function () {
        var that = this;

        $.each(this.options.data, function (i, row) {
            that.$selectAll.prop('checked', false);
            that.$selectItem.prop('checked', false);
            if (that.header.stateField) {
                row[that.header.stateField] = false;
            }
        });
        this.initHiddenRows();
    };

**Comment by zyairzy** [comment]
Futher more, when maintainSelected = false, with singleSelect + searchText, also has bug.
Firstly, I select one row "ee" in table. 
Secondly, I add searchText "a" to get result with no row "ee".
Thirdly, I select another row "aa" with searchText "a", then I use getSelections, it will return 2 rows selected (expected 1)

jsfiddle example: https://jsfiddle.net/zyairzy/yxgbcavb/

**Comment by wenzhixin** [comment]
Fixed: https://jsfiddle.net/wenyi/yxgbcavb/2/

**Comment by mrprogramator** [comment]
Hey! the same bug when data-search="true":
1. Select a row
2. Search other row
3. Select other row from results
5. $('#my-table').bootstrapTable('getSelections') returns 2 items

**Comment by wenzhixin** [comment]
@mrprogramator Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by mrprogramator** [comment]
@wenzhixin :https://jsfiddle.net/8ho61zwg/1/

Using bootstrap-table  version 1.11.1
