### ISSUE TITLE
分页查询时的两个问题

### ISSUE THREAD

**Issue by ijLee** [wenzhixin/bootstrap-table#2964]
你好，使用你写的 bootstrap-table 挺久了，非常好用。但是也发现了两个问题，我自己使用中，我改了源代码，每次升级都要修改，很麻烦，所以把问题发给你，希望你能采纳。
--------------------------------------------------------

我对 bootstrap-table 的修改

分页参数：offset、limit
查询参数：其他参数，与分页参数一起传送到后台

1. 保存分页参数，用于点击上/下页时使用
关键代码

BootstrapTable.DEFAULTS{}
添加：
cacheQueryParams: undefined, // XXX 保存查询参数 2015-11-28 21:26

BootstrapTable.prototype.initServer()
添加/修改：
// XXX 输入查询参数时，保存查询参数；否则，使用原有的查询参数 2015-11-28 21:29
// XXX 分页时，点击上/下页，只传分页参数，没有查询参数，如果不保存查询参数，会查询所有数据。
if(query !== undefined) {
	this.options.cacheQueryParams = query;
}
// $.extend(data, query || {});
$.extend(data, query || this.options.cacheQueryParams); // XXX 使用已保存的查询参数

请查找 cacheQueryParams，查看相关代码。

2.当前有分页参数，但是输入新的查询参数时，应该重置分页参数。
比如，输入某个查询参数，查询结果有三页数据，点击了第二页，则此时
offset=10&limit=10
如果再输入新的查询参数，则应该将offset与limit的值重置，如下
offset=0&limit=10

关键代码
BootstrapTable.prototype.refresh()
添加：
this.options.pageNumber = 1; // XXX 刷新表格时，将表格页码重设为1（不判断） 2015-11-29 14:49

                                                        李远明
                                                        2017-03-03 10:14:01

**Comment by wenzhixin** [comment]
1. 其实使用 `queryParams` + 一个变量就可以实现你想要的效果了，没必要改源码。即使你所有页面都需要你也可以用插件的方式避免升级的问题。
2. 最新版本 `refresh` 方法支持传入 `pageNumber` 参数。

谢谢。

**Comment by ijLee** [comment]
哦，好的。多谢！我试试看。
2017年3月18日 上午1:24，文翼 <notifications@github.com>写道：其实使用 queryParams + 一个变量就可以实现你想要的效果了，没必要改源码。即使你所有页面都需要你也可以用插件的方式避免升级的问题。最新版本 refresh 方法支持传入 pageNumber 参数。
谢谢。
