### ISSUE TITLE
对分页和排序的server/client端分离设置的需求

### ISSUE THREAD

**Issue by CSGrandeur** [wenzhixin/bootstrap-table#2965]
类似issue: https://github.com/wenzhixin/bootstrap-table/issues/1507

“有 1-100 的记录，第一页显示 1-10，倒序是 10-1“，这样是相当对的，非常有这个需求啊。

**Comment by wenzhixin** [comment]
这个需求感觉不是很合理呢。。

**Comment by CSGrandeur** [comment]
需求在这里：
[`http://poj.org/problemlist?orderby=ratio&volume=2`](http://poj.org/problemlist?orderby=ratio&volume=2)

**Comment by Falseee** [comment]
@wenzhixin Can you translate it ?

**Comment by wenzhixin** [comment]
@Falseee Use `server` side pagination, and then sort in `client`.
