### ISSUE TITLE
getOptions.totalRows shows zero even if the records are visible/fetched

### ISSUE THREAD

**Issue by zeeshanyshaikh** [wenzhixin/bootstrap-table#2967]
I am getting records from MySQL database to show in tables and am showing the number of records in the toolbar using `getOptions` method. The problem is sometimes the count (totalRows) comes zero, however am getting proper records.

I tried was, refreshing the page it shows zero, so printed the count on console through javascript.
1. When i refreshed the page without opening the console (developer tools) it shows zero.
2. When i open the console and refresh the page it shows proper count

This issue occurs on Chrome 56 and IE 11, works on Firefox 51.

Attached is the screenshot. Below is the javascript code used.

`var $table = $('#mappingstable');`
    `$table.bootstrapTable('destroy').bootstrapTable({`
    	`height: getHeight()`
   ` });`
  ` $(function () {`
    	`console.log("total rows", $table.bootstrapTable('getOptions').totalRows);`
    	`$("#showcount").html("Total Question Count : " + $table.bootstrapTable('getOptions').totalRows);`
  });`

![image1](https://cloud.githubusercontent.com/assets/6223015/23554673/185dc0c6-004c-11e7-91d2-ab701f4e694d.jpg)
![image2](https://cloud.githubusercontent.com/assets/6223015/23554674/18628ea8-004c-11e7-878f-b4a52dcfe5b1.jpg)

**Comment by djhvscf** [comment]
Are you setting the totalField when you are returning the data from server? 

See this line of code: https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L2390

**Comment by zeeshanyshaikh** [comment]
Yes, used below code for table definition.

`<table id="mappingstable"`
           `data-toolbar="#toolbar"`
           `data-show-refresh="true"`
           `data-show-export="true"`
           `data-show-pagination-switch="false"`
           `data-pagination="false"`
           `data-only-info-pagination="false"`
           `data-id-field="id"`
	   `data-click-to-select="false"`
	   `data-show-columns="true"`
           `data-side-pagination="server"`
	   `data-search="true"`
           `data-url="showdata.php">`

**Comment by djhvscf** [comment]
I didn't see the data-total-field in that configuration

**Comment by zeeshanyshaikh** [comment]
Ohh I have mistaken it. However, I added `data-total-field='total'` in the table configuration, but still, I am facing the same issue.

**Comment by zeeshanyshaikh** [comment]
This is the output of my showdata.php

![image](https://cloud.githubusercontent.com/assets/6223015/23600182/447622e0-026b-11e7-8e98-3b7404929cab.png)

**Comment by zeeshanyshaikh** [comment]
Any update on this issue?

**Comment by wenzhixin** [comment]
You need to wait for the data to load completed, use `load-success` event solve your problem:
http://jsfiddle.net/wenyi/4r6g4cfu/583/

**Comment by zeeshanyshaikh** [comment]
That was cool & impressive, and I missed it :(
Load event worked. Thanks, @wenzhixin 👍
