### ISSUE TITLE
More displayed buttons for pagination.

### ISSUE THREAD

**Issue by Shpartko** [wenzhixin/bootstrap-table#2968]
Hello!
Is there a way to increase the number of displayed buttons for pagination?
How can I make this? Perhaps there is a ready solution?

**Now:** 1...4,5,6...20
**I want:** 1,2,3......9,10,11,12,13.....18,19,20

![pagination](http://joxi.ru/krD4XBXUDWpvrp.jpg)

**Comment by Shpartko** [comment]
Hey, @djhvscf !
I was create this at #3084  :)

Now can use few options for pagination for setup display out.

```
       data-pagination-successively-size="5"
       data-pagination-pages-by-side="3"
       data-pagination-use-intermediate="true"
```

![image](https://cloud.githubusercontent.com/assets/16976774/24999337/cbc7d084-2045-11e7-9df9-c90b867d1c7f.png)
or
![image](https://cloud.githubusercontent.com/assets/16976774/24999358/def552b2-2045-11e7-840a-14f4c9af5105.png)
or
![image](https://cloud.githubusercontent.com/assets/16976774/24999369/e73032f8-2045-11e7-8bdb-9c18533dbcb5.png)
or
![image](https://cloud.githubusercontent.com/assets/16976774/24999378/f4300bb8-2045-11e7-8ea6-d53d92abc227.png)
or
![image](https://cloud.githubusercontent.com/assets/16976774/24999387/fdd09dfe-2045-11e7-8b0e-f78e47a094e7.png)

Look nice?

**Comment by djhvscf** [comment]
It looks amazing!!

**Comment by djhvscf** [comment]
See #4094
