### ISSUE TITLE
After Sort Event

### ISSUE THREAD

**Issue by lacikacs** [wenzhixin/bootstrap-table#297]
Please add an event that is triggered after the sort has finished.

**Comment by wenzhixin** [comment]
Please use `onPostBody`(`post-body.bs.table`) event.

**Comment by 1534854467** [comment]
you can change line 671 in bootstarp-table.js
    BootstrapTable.prototype.onSort = function (event) {
        var $this = $(event.currentTarget).parent(),
            $this_ = this.$header.find('th').eq($this.index());

        this.$header.add(this.$header_).find('span.order').remove();

        if (this.options.sortName === $this.data('field')) {
            this.options.sortOrder = this.options.sortOrder === 'asc' ? 'desc' : 'asc';
        } else {
            this.options.sortName = $this.data('field');
            this.options.sortOrder = $this.data('order') === 'asc' ? 'desc' : 'asc';
        }
        this.trigger('sort', this.options.sortName, this.options.sortOrder);

        $this.add($this_).data('order', this.options.sortOrder)
            .find('.th-inner').append(this.getCaretHtml());

        if (this.options.sidePagination === 'server') {
            this.initServer();
            return;
        }

        this.initSort();
        this.initBody();
    };


to : 
    BootstrapTable.prototype.onSort = function (event) {
        this.initSort();
        this.initBody();
        
        var $this = $(event.currentTarget).parent(),
            $this_ = this.$header.find('th').eq($this.index());

        this.$header.add(this.$header_).find('span.order').remove();

        if (this.options.sortName === $this.data('field')) {
            this.options.sortOrder = this.options.sortOrder === 'asc' ? 'desc' : 'asc';
        } else {
            this.options.sortName = $this.data('field');
            this.options.sortOrder = $this.data('order') === 'asc' ? 'desc' : 'asc';
        }
        this.trigger('sort', this.options.sortName, this.options.sortOrder);

        $this.add($this_).data('order', this.options.sortOrder)
            .find('.th-inner').append(this.getCaretHtml());

        if (this.options.sidePagination === 'server') {
            this.initServer();
            return;
        }
    };

**Comment by guripong** [comment]
what about this way? 💃
                    `$('#mytableID').on('sort.bs.table', function(e,name,order){
                        console.log("sort start??");
                        $('#mytableID').on('post-body.bs.table', function(e,params){
                            console.log("sort finish");
                            $('#mytableID').unbind("post-body.bs.table");
                            //to do something after sort here
                        });
                    });`

**Comment by cgountanis** [comment]
This still is an issue, on sort you lose your tooltips? Any way to globally fix this on * tables used?
