### ISSUE TITLE
Formatter isn't playing well with React

### ISSUE THREAD

**Issue by scherrymomin** [wenzhixin/bootstrap-table#2970]
Column formatter isn't working with React

I'm trying to use the column formatter option. When I pass in a string to data-formatter, every cell in table gets replaced with the string I pass in.  Data-events also doesn't work. 

Is there an example of the formatter working with React? This is how I'm initializing the component:

```
  componentDidMount: function() {
    $(ReactDOM.findDOMNode(this)).bootstrapTable({
      columns: this.props.columns,
      data: this.props.data
    });
  }
```

This is how I'm rendering the JSX:

```
    return(
        <table data-sort-name="bbl" data-show-export="true" data-show-refresh="true" data-show-toggle="true" data-card-view="false" data-sort-order="desc" ref="table" id="#table" data-search="true" data-show-columns="true" data-toggle="table" >
          <BootstrapHead columns={this.props.columns} />
        </table>
    )
```

BootstrapHead render function: 

```
  render: function() {
    var colNames = this.props.columns;

    var colHeads = [];

    for (var i=0; i < colNames.length; i++) {
      colHeads.push(<th data-formatter={colNames[i].formatter} data-events={colNames[i].events}></th>);
    }

    return (
      <thead>
        <tr>
          {colHeads}
        </tr>
      </thead>
    )
  }
});
```

I tried to put the options inside of the initializer and it did not work. I had a prop for formatter and events inside of this.props.columns. 

If I did this with straight js without react AND without putting in data-formatter in the HTML, would it have worked? 

Thanks!

**Comment by mbugbee** [comment]
Did you have any luck finding a solution to this issue?

**Comment by Falseee** [comment]
I close this issue because its older than 2 years, if you still need help please reopen the issue.
