### ISSUE TITLE
Is there anyway to reset all the cell styles without reload data from server?

### ISSUE THREAD

**Issue by CSGrandeur** [wenzhixin/bootstrap-table#2971]
we can use cellStyle and `data-cell-style` to modify the cell style.
```
function cellStyle(value, row, index, field) {
  return {
    classes: 'text-nowrap another-class',
    css: {"color": "blue", "font-size": "50px"}
  };
}
```
But it only fires when the table is rendering.
So the queston could also be "could I re-render the table without load data again from server?"

**Comment by Falseee** [comment]
In which cases do you need the re-render of the table ?
Could you give us an example(jsfiddle) for this case?

**Comment by Falseee** [comment]
I close this issue because we got no response/example within 7 days.
