### ISSUE TITLE
cookie经常导致table变空、table导出问题

### ISSUE THREAD

**Issue by CSGrandeur** [wenzhixin/bootstrap-table#2972]
##### 问题一
举个例子，一个表在网站登录时比没登录时看到的内容多，登录时翻到第10页，退出登录，table变空了。这时候要serverside的排序、搜索，才能显示出内容。
最大问题是这种变空的情况下，页码按钮没了，不然的话好歹可以翻回有内容的页面。

建议cookie模块处理一下异常情况，比如遇到这类异常自动翻回第一页。
bootstrap-table对于这种异常，还保留一下页码，让用户能意识到是页码超出范围。
##### 问题二
1.11版本用了cookie可能导致页面打开之后不自动加载数据，搜索、排序之后才加载。
1.10版本没这个问题。

### table导出问题
很久以前用1.8版本的时候正常，现在1.10、1.11，都存在table导出不能设置文件名，都是默认的tableExport。

**Comment by wenzhixin** [comment]
麻烦提供下 jsfiddle 例子。
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
