### ISSUE TITLE
Instead of a toggle button, can I turn grid view on with a single button and detail view on with another button?

### ISSUE THREAD

**Issue by talena6** [wenzhixin/bootstrap-table#2974]
I want to have two buttons, a "Grid View" and "Detail View" that are visible at all times -- meaning it's not a single button that toggles views, but a button group to switch between. Is this possible?

**Comment by Falseee** [comment]
Use [buttonsToolbar](https://bootstrap-table.com/docs/api/table-options/#buttonstoolbar) to create custom Buttons in your Toolbar and then call [toggleView](https://bootstrap-table.com/docs/api/methods/#toggleview) if needed.
