### ISSUE TITLE
how to render custom data？

### ISSUE THREAD

**Issue by EvanLiu2968** [wenzhixin/bootstrap-table#2975]
url reponse data as:
```
msg:"",
code:"",
data:{
   rows:[],
   totals:200
}
```
can render it to table as this way?
how to define the data structure？

**Comment by snimavat** [comment]
I have same question

As of now, for server side pagination etc, the expected data format is fixed, and i dont find any option to specify a callback function which can convert the server returned data to data format expected by plugin.

It would be great if there was some way to provide a datasource, which can be used to hook between plugin and server api, so we can use plugin easily without needing to change the format returned by server.

**Comment by EvanLiu2968** [comment]
```
responseHandler:function(res){return res.data;}
```
forgot to close the issue,sorry,docs has the option to render data fotmat is fixed
