### ISSUE TITLE
[help need][example need] serverSide pagination with multi-search-condition

### ISSUE THREAD

**Issue by zhou9197** [wenzhixin/bootstrap-table#2976]
how can i search with 2 or more key words with custom controls?
it seems that i can pass the key words to queryParams but i do not know which event to trigger and what else should be done as default search only accept one para called "event".

BTW, what do the below events do ? there are detected when i change the searchText.
page-change.bs.table [1, 10]
search.bs.table ["1"]
pre-body.bs.table [Array[0]]
reset-view.bs.table []
post-body.bs.table [Array[0]]
load-success.bs.table [Object]
post-header.bs.table []

**Comment by Falseee** [comment]
The issue is older then 3 years, if you still need help pls reopen the issue and prove an example (jsfiddle).
