### ISSUE TITLE
怎么保留上一页的选中状态？

### ISSUE THREAD

**Issue by docikaci** [wenzhixin/bootstrap-table#2977]
或者把所有选中的存到一个数组里？ 然后每次分页渲染完遍历，怎么重新选中？

还有一个问题，怎么根据后台返回的某个字段，动态显示哪些列？也就是说columns是动态的？

非常感谢

**Comment by wenzhixin** [comment]
* 第一个问题，假如是 client 分页的话可以使用 maintainSelected 选项，假如是 server 分页的话看这个问题 #917
* 第二个问题，可以在初始化的时候设置 column 的 visible

**Comment by docikaci** [comment]
您好再打扰一下，这里的动态不是根据前端数据，是根据表格的ajax返回的数据，
目前先请求一次，拿到是否显示某些列的字段，在请求一次渲染表格，感觉非常不好！
怎么能发送一次请求，拿到后台某个字段，在渲染表格（根据字段动态显示columns）
 谢谢
![image](https://cloud.githubusercontent.com/assets/7788102/24036596/20e0387a-0b35-11e7-9c2a-40788733c9a0.png)

**Comment by wenzhixin** [comment]
一个请求也可以啊，你封装好 columns 后
```
bootstrapTable({
    columns: columns,
    data: data
})
```
