### ISSUE TITLE
[need examples] Battstrap-Table editable Plugin Write Back to the API/Database

### ISSUE THREAD

**Issue by PeterPlanlos** [wenzhixin/bootstrap-table#2978]
Hi all, 
_sorry for the typo on the Topic_ + thanks for reading my Text.

I use a Table with these **Options**:
data-toggle="table"
data-url="api/api.php/<?php echo $api_table; ?>"
data-side-pagination="client"
data-query-params="queryParams"
data-response-handler="responseHandler"
data-pagination="true"
data-page-list="[10, 25, 50, 100, ALL]"
data-page-size="20"
data-sort-name="nr"
data-sort-order="desc"
data-striped="true"
data-show-refresh="true"
data-show-columns="true"
data-height="720"  
data-detail-view="true"
data-detail-formatter="detailFormatter"     
data-sortable="true"
data-search="true"	   
data-show-export="true"
data-export-types="['excel']"

all does work very well. It receives the Data for Display the Table from my API in JSON.

Now to the **Problem**:
yet i want to add some editable fields. 
i included these stuff like i saw in an example:
_[example]_
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html
_[included stuff]_
JS:
- bootstrap-table/extensions/editable/bootstrap-table-editable.js
- http://rawgit.com/vitalets/x-editable/master/dist/bootstrap3-editable/js/bootstrap-editable.js
CSS:
- http://rawgit.com/vitalets/x-editable/master/dist/bootstrap3-editable/css/bootstrap-editable.css

i added for testing a "data-editable="true" Attribute to one of my fields on the table.
The result is that it optically change the field but it does not writeback to my api it only display the change on the browser. If i refresh the page the change is gone.

Till yet i dont use jquery, i think i need it yet? does i need define a PK anywhere on the Table or Tableoptions to get it work properly?
could someone give me an example how i can writeback(POST) to an API (URL) and format the JSON which should post to the API, _please_?

Sorry if something is not clear or i did wrong. iam not a developer.

Thank you all very much!

**Comment by PeterPlanlos** [comment]
Could someone tell me the correct eventname when i use the x-editable js and editiable bootstrap-table extension?
@ bootstrap-table.wenzhixin.net.cn/documentation/
i found this.. but i dont know the Eventname... please help me
```
$('#table').bootstrapTable({
    onEventName: function (arg1, arg2, ...) {
        // ...
    }
});

$('#table').on('event-name.bs.table', function (e, arg1, arg2, ...) {
    // ...
});
```

**Comment by sposs** [comment]
I'm having the same issue. I read the code as the doc is lacking. There is no callback to any server done (it's actually commented out). It's only visual changes now. What you need to do is to have a 'save' button that you click after having updated any number of rows and which then collects all the table info and sends it to the server.

**Comment by wenzhixin** [comment]
You can use `onEditableSave` event to solve your problem:
https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/editable#oneditablesaveeditable-savebstable

**Comment by PeterPlanlos** [comment]
my table id is **table**
the following JS code i addet to my table but i dont get any console.log it seems the function or event isnt called?! i tryed it with the parameter "e" and i tryed with 'onEditableSave' ... 

   ```
 `$('#table').on('editable-save.bs.table', function(e, field, row, oldValue, $el){
    console.log(e);
    console.log(field);
    console.log(row);
    console.log(oldValue);
    console.log($el);
});`
```
please could someone provide me a working example? 
thanks for you help!

**Comment by PeterPlanlos** [comment]
Found a solution!.... the above JS example works!
`need add JQUERY in header, mine was on the footer (body) part of html and this wont work.. `

**Comment by Prathvin** [comment]
@PeterPlanlos Could you please share your working example for this issue as I am trying to get the same fix. Thank you for the help!

**Comment by typo3ua** [comment]
Hi! ... exactly, where can I look example?
