### ISSUE TITLE
Events on Table Bootstrap

### ISSUE THREAD

**Issue by kramoj** [wenzhixin/bootstrap-table#2981]
Hi,

Currently, I am using my own jquery events on bootstrap table but I encountered errors. When I clicked any event from bootstrap table, my jquery event doesn't work anymore.

Here is my sample code:

$("tr").click(function(){
	console.log("edit");
	var color=$(this).css("background-color");
	if(color == 'rgb(245, 245, 245)')
	{
		$(this).css("background-color", "white");
	}
	else 
	{
		$(this).css("background-color", "#f5f5f5");
	}
});

This event will highlight the entire row which I clicked.

I was hoping to use the built-in event from bootstrap table. Thank you!

**Comment by wenzhixin** [comment]
http://stackoverflow.com/questions/26567867/bootstrap-table-cannot-add-click-event-on-tr/26580105#26580105
