### ISSUE TITLE
Documentation site is broken

### ISSUE THREAD

**Issue by mgrazulis** [wenzhixin/bootstrap-table#2983]
Where can i access documentation for this module. The URL thats provided has been broken for months.

**Comment by sposs** [comment]
http://bootstrap-table.wenzhixin.net.cn/

**Comment by djhvscf** [comment]
It is working as expected.

**Comment by yadejo** [comment]
+1 I cannot reach the documentation website

**Comment by djhvscf** [comment]
It is working as expected. Please review it and let us know if the site does not work for you
