### ISSUE TITLE
设置 paginationLoop 后仍然会循环翻页

### ISSUE THREAD

**Issue by hyjiacan** [wenzhixin/bootstrap-table#2985]
bootstrapTable： v1.11.0
jQuery: 1.12.4
Browser： Google Chrome 50.0.2661.87 m

初始化的时候传了参数
```
paginationLoop: false
```
，并且我使用`table.bt('getOptions').paginationLoop`查看，值也是`false`，可是仍然会循环翻页。

BTW, 多谢开源，这表格很强大！！

**Comment by wenzhixin** [comment]
用最新的版本测试，不会有问题：http://jsfiddle.net/wenyi/e3nk137y/12414/ ，验证下，有问题重新打开并提供 jsfiddle，谢谢。

**Comment by hyjiacan** [comment]
ok 解决了  多谢

**Comment by Ray0401** [comment]
请问一下 你是怎么解决的 我设置了paginationLoop:false 后也还是不好使

**Comment by hyjiacan** [comment]
@Ray0401  就是更新版本后就没问题了

**Comment by Ray0401** [comment]
@hyjiacan  更新版本后确实是没问题了,前几天忘记了回您,不好意思,谢谢了!
