### ISSUE TITLE
False on data-formatter inputs

### ISSUE THREAD

**Issue by iwoanton** [wenzhixin/bootstrap-table#2988]
Hello

I have this problem, i have a column that using data-formatter returns a link to edit page with the id of the "student" ex:(www.example.com/students/edit/[id]), [id] as number, the problem is when I do a change/event on the table like search, pagination or order.. this id converts to "false" getting www.example.com/students/edit/false on all...

Any suggestion??

Sorry for my english

Thanks

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!
