### ISSUE TITLE
Doc's are not correct

### ISSUE THREAD

**Issue by krosoftware** [wenzhixin/bootstrap-table#2991]
Hello
Event documentation is not correct:
http://bootstrap-table.wenzhixin.net.cn/documentation/#events
for Event "onClickRow" declared parameters are: 
row, $element, field
and correct parameters are (according this link from author:
http://stackoverflow.com/questions/26567867/bootstrap-table-cannot-add-click-event-on-tr : 
e, row, $element
not sure what are "e" and "$element" parameters but at least, "row" parameter is OK.

**Comment by wenzhixin** [comment]
The same with #2868

**Comment by wenzhixin** [comment]
Added FAQ: #3004
