### ISSUE TITLE
Multiple-sort extension is broken on jQuery 3.x

### ISSUE THREAD

**Issue by SasSam** [wenzhixin/bootstrap-table#2993]
The extension is using deprecated method at [line14](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/multiple-sort/bootstrap-table-multiple-sort.js#L14) which is `.selector()`. The method [was removed from jQuery 3.0](https://api.jquery.com/selector/).

If we try to use this with 3.x jQuery, the extension throws exception on console and just brake down everything.

**Comment by djhvscf** [comment]
@SasSam do you know how can we change that?

**Comment by SasSam** [comment]
@djhvscf yeah... I've made a PR (#2995) to fix this.

**Comment by djhvscf** [comment]
Great! Thanks
