### ISSUE TITLE
click-edit extension column.fieldIndex issue with invisible cols 

### ISSUE THREAD

**Issue by sposs** [wenzhixin/bootstrap-table#2994]
When a column has 'visible:false' the fieldIndex is not correct for the click-edit-row extension, leading to a shift in the columns. 

```javascript
columns: [{
field:'count',
title: 'count',
visible:false,
editable:false
},{
field:'name',
title: 'name',
editable: true
},{
field: "othername",
title: "Something",
editable:false
}]
```
yields that the last column becomes editable while the second is not. Commenting the 'visible' option of the first restores the proper behavior.

**Comment by Falseee** [comment]
It might the bug is fixed in an newer version.
Demo: http://jsfiddle.net/6d8np21c/
@wenzhixin @djhvscf
