### ISSUE TITLE
getselections or getallselections doens't work with nested bootstrap tables

### ISSUE THREAD

**Issue by rzendron** [wenzhixin/bootstrap-table#2996]
Hello.

I have nested boostrap-tables, onExpandRow I have a logic that will get data from a rest service and them populate a new table.

When I try to get all selected rows I am using the getSelections, but the return is only from the master table.

I have up to 4 level of nested table, is it possible to get all selected rows? See attached image.
![nestedtable_getselection](https://cloud.githubusercontent.com/assets/25914588/23873377/9be5120c-0810-11e7-8efb-ee05abd055e7.jpg)

**Comment by wenzhixin** [comment]
The same with #2720
