### ISSUE TITLE
Footer horizontal scrolling not synchronized with the table when height is not set

### ISSUE THREAD

**Issue by edp** [wenzhixin/bootstrap-table#2999]
This is related to issue #639 

When you don't set the height property on the table, the footer won't scroll correctly. This can be replicated by using the [#639 example](http://issues.wenzhixin.net.cn/bootstrap-table/#issues/639.html) and removing the "data-height" attribute.

While debugging, I noticed that without the height attribute, the function BootstrapTable.prototype.fitHeader is never called and this is where the scroll event is managed (and synced).

**Comment by edp** [comment]
I have fixed the issue by adding the scroll sync code to fitFooter as well. I don't know if we need to keep it in fitHeader or not. If this is the correct way to do it, I'll send a PR.

**Comment by wenzhixin** [comment]
Thanks for your feedback! Fixed in #3003
