### ISSUE TITLE
How to change the order of toolbar and buttons

### ISSUE THREAD

**Issue by CSGrandeur** [wenzhixin/bootstrap-table#3000]
```
data-show-refresh="true"
data-buttons-align="left"
data-toolbar-align="left"
```
I want both the button and toolbar align left, but I want refresh button on the left of the toobar. 

However, toobar seems always have priority.

![123](https://cloud.githubusercontent.com/assets/5326601/23985470/425c436c-0a5a-11e7-93a4-4439270d0d41.png)

**Comment by wenzhixin** [comment]
Do you mean: http://jsfiddle.net/wenyi/e3nk137y/12407/?

These options maybe help you:

```
searchAlign | data-search-align
buttonsAlign | data-buttons-align
toolbarAlign | data-toolbar-align
```

**Comment by CSGrandeur** [comment]
@wenzhixin Thank you. But I means that I've already set 
```
data-buttons-align="left"
data-toolbar-align="left"
```
And I want `buttons` "more left" than `toobar`. However, `toolbar` is always more left than `buttons`.

**Comment by wenzhixin** [comment]
```
.fixed-table-toolbar {
  display: flex
}
.fixed-table-toolbar .columns {
  order: -1;
}
```

http://jsfiddle.net/wenyi/e3nk137y/12410/

**Comment by CSGrandeur** [comment]
Thank you. That's what I want~~
