### ISSUE TITLE
checkAll, uncheckAll with Pagination

### ISSUE THREAD

**Issue by vveliu** [wenzhixin/bootstrap-table#3001]
Hi, 

I'm using a table with `checkBoxes` and Pagination (currently 2 pages 20 elements 10 per page). 

When `checkAll` if fired on first page  `$('#my-table).bootstrapTable('getSelections');` returns an array with all data, not only 10 (first page rows).

If I change page and return back to first page all works fine.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
