### ISSUE TITLE
Checking and unchecking cols from the Column selector dropdown throws null reference exception in bootstrap-table-multiple-sort

### ISSUE THREAD

**Issue by pyash** [wenzhixin/bootstrap-table#3002]
Checking and unchecking cols from the Column selector dropdown throws null reference exception in bootstrap-table-multiple-sort.

No issues in chrome, only happens in IE11. In IE11 I get the error 

`Error: Unable to get property 'length' of undefined or null reference`

The exception happens in the for loop when checking the length. I added an extra if check (commented out) to prevent the exception.
```
this.$el.on('column-switch.bs.table', function (field, checked) {
                // extra code added to prevent exception 
// if (that.options.sortPriority !== null && that.options.sortPriority.length >= 0) {
                    for (var i = 0; i < that.options.sortPriority.length; i++) {
                       ...
                    }
```
I set showMultiSort = true when I initialize bootstrap-table. No other multi-sort options are used. I also use the Export, and StickyHeader extensions.

**Comment by Falseee** [comment]
The issue is already 2 years old, if you still need help please reopen it.
