### ISSUE TITLE
当可多选的table属性里面使用了pagination：true之后，然后他就会默认选中当前页之后的所有条目，我用的版本是1.11.0

### ISSUE THREAD

**Issue by ThenBreeze** [wenzhixin/bootstrap-table#3008]
//展示所有设备信息（包括损坏设备）
        function showAllDevicesTable() {
            var reqUrl = _method_queryAllDevices + "?userNameCas=" + _myNameCas;

            getInvoke(reqUrl, function (result) {
                jsonRsp = result;
                ////从数组中删除不可用设备
                //for (var i = 0; i < jsonRsp.rows.length ; i++) {
                //    if (jsonRsp.rows[i].enable == 0) {
                //        jsonRsp.rows.splice(i, 1);
                //    }
                //}
                _table_allDeviceList.bootstrapTable('destroy');
                _table_allDeviceList.bootstrapTable({
                    width: 300,
                    striped: false,
                    cache: false,
                    hideLoading: true,
                    //pagination: true,//是否显示分页 bug
                    sortable: true,
                    sortOrder: "asc",
                    formatSearch: function (){
                        return '请输入搜索内容';
                    },
                    search: true,
                    searchAlign: 'right',
                    showColumns: true,
                    checkboxHeader: true,
                    clickToSelect: true,
                    maintainSelected: true,
                    rowStyle: function (row, index) {
                        //这里有5个取值代表5中颜色['active', 'success', 'info', 'warning', 'danger'];
                        var strclass = "";
                        if (row.borrowerNameZh > '') {
                            strclass = 'warning';
                        } else if (row.enable == 0) {
                            strclass = 'danger';
                        }
                        return { classes: strclass }
                    },
                    columns: [
                        {
                            checkbox: true,
                            field: ''
                        },
                        {
                            title: '设备ID',
                            field: 'deviceId',
                            align: 'center',
                            sortable: true,
                            valign: 'middle'
                        },
                        {
                            title: '设备名称',
                            halign: 'center',
                            field: 'deviceName',
                            align: 'left',
                            sortable: true,
                            valign: 'middle'
                        },
                        {
                            title: '设备IMEI号',
                            field: 'deviceImei',
                            align: 'center',
                            sortable: true,
                            valign: 'middle'
                        },
                        {
                            title: '设备资产编号',
                            field: 'deviceAssetId',
                            align: 'center',
                            sortable: true,
                            valign: 'middle'
                        },
                        {
                            title: '设备类型',
                            field: 'deviceTypeDescription',
                            align: 'center',
                            sortable: true,
                            valign: 'middle'
                        },
                        {
                            title: '借出人姓名',
                            field: 'borrowerNameZh',
                            align: 'center',
                            sortable: true,
                            valign: 'middle'
                        },
                        {
                            title: '借出人ID',
                            field: 'borrowerNameCas',
                            align: 'center',
                            sortable: true,
                            valign: 'middle'
                        },
                        {
                            title: '更新时间',
                            field: 'updateTimeStr',
                            align: 'center',
                            sortable: true,
                            valign: 'middle'
                        },
                        {
                            title: '更新操作者',
                            field: 'updateBy',
                            align: 'center',
                            sortable: true,
                            valign: 'middle'
                        }
                    ],
                    data: jsonRsp.rows
                });
                _table_allDeviceList.bootstrapTable('hideLoading');
                ////隐藏不可用设备
                //var data = _table_allDeviceList.bootstrapTable('getData');
                //for (var i = 0; i < data.length ; i++) {
                //    if (data[i].enable == 0) {
                //        _table_allDeviceList.bootstrapTable('hideRow', { index: i });
                //    }
                //}

            }, onErrorHandler, onCompleteHandler);
        }

**Comment by wenzhixin** [comment]
```
checkbox: true,
field: ''
```
这里的 field 不能为空啊，你可以写一个列表没有的属性，例如 `state`
