### ISSUE TITLE
sortStable is not stable

### ISSUE THREAD

**Issue by nicoden** [wenzhixin/bootstrap-table#3012]
The stable sort do not maintain the relative sort correctly.

Example: [https://jsfiddle.net/nicoden/qotyfmne/6/](https://jsfiddle.net/nicoden/qotyfmne/6/)

Step to reproduce:

  1. Sort by Category and see order of rows
  2. Toggle sort of Category and see that rows order is changed

Because Category is the same for all rows, the rows order should not change with a stable algorithm.

**Comment by wenzhixin** [comment]
Merged!
