### ISSUE TITLE
Can't sort table inside detailView

### ISSUE THREAD

**Issue by GuilhermeHideki** [wenzhixin/bootstrap-table#3013]
Steps:
- Click the + button to expand
- Click on the sortable row
- detailView closes

[jsfiddle](http://jsfiddle.net/agm0zgrn/1/) - a link to the reduced test case.

Tested on Win 8.1, on Chrome 56 and Firefox

**Comment by wenzhixin** [comment]
Remove this line:
```
// table.appendTo($detail);
```

http://jsfiddle.net/wenyi/agm0zgrn/2/
http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html

**Comment by GuilhermeHideki** [comment]
thanks!
