### ISSUE TITLE
Global filter is not applied when filter on column (filter-column extention)

### ISSUE THREAD

**Issue by nicoden** [wenzhixin/bootstrap-table#3015]
When filter with `.search` text box AND column filter, the result depend on the order we put text in search box.

Type data in column filter the in global search box is ok.

Type data in global search box then in column fllter: **Only the column filter is applied**

Step to reproduce in this [fiddle](https://jsfiddle.net/nicoden/qotyfmne/8/):

  1. Enter `Alice` in the global search box
    => Alice displayed, ok
  2. Enter `Bob` in the Name column filter
    => Bob displayed, **not ok**, no results should appear in this case

I patched temporarly my code with this:

Pass an `null` currentTarget to the onSearch event handler in `bootstrap-table-filter-control.js:onColumnSearch`
``` js
this.onSearch({ currentTarget: null });
```

In the onSearch event handler, use the global search text box if currentTarget is null:
``` js
        var text = $.trim($(event.currentTarget || this.$toolbar.find('.search input')).val());

        // trim search input
        if (this.options.trimOnSearch && event.currentTarget && $(event.currentTarget).val() !== text) {
```

This is not a perfect solution because it break the trimOnSearch for column filter.

**Comment by Falseee** [comment]
Duplicate #2776
