### ISSUE TITLE
Detail view lost data when second time expanded

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#3016]
Hello,

I have a questions:

How can I maintain detail view after first time? When first time it is expanded, I load a sub-table dynamically and populate the detail view with some user entered data, but after collapse and re-expand again, all data are lost.

Is there any way that I can prevent this happen, so I do not lose the data I entered in detail view?

Many Thanks!

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Hoppeduppeanut** [comment]
Not OP, but I'm having the same issue, though it looks to be because the detailview is removed on collapsing the row (as per #2944). 

[Quick and dirty jsFiddle to demonstrate](http://jsfiddle.net/x5gzvtju/).

**Comment by Falseee** [comment]
I close this issue because its older than 2 years, if you still need help pls reopen the issue.
But you could use a detailFormatter which use data from the table, after the user entered something update the row with that and it should work as expected.
