### ISSUE TITLE
Post data to PHP

### ISSUE THREAD

**Issue by basementmedia2** [wenzhixin/bootstrap-table#3017]
Hi,

the following code works perfectly:
```
     <table id="table"
               data-toggle="table"
               data-height="460"
               data-search="true"
               data-url="ajax_load_projekte.php"
               data-side-pagination="client"
               data-pagination="true"
               data-show-toggle="true"
               data-show-columns="true"
               data-sortable="true">
            <thead>
            <tr>
                <th data-field="nummer">Nummer</th>
                <th data-field="name">Name</th>
            </tr>
            </thead>
        </table>
```
But how can i send params to the PHP file (ajax_load_projekte.php)? 

When i use 'data-query-params="postQueryParams"' and the function 
```
     function postQueryParams(params) {
        params.test = "Hallo";
        return params; // body data
     }
```

How can i read out the variable "test" in my php file?
Using $_POST["test"] fails.

Best regards

Daniel

**Comment by wenzhixin** [comment]
Use `$_GET`

**Comment by qwe900** [comment]
I have the table in a Form with 
` <form class="form-horizontal" id="form" action="cube.php" method="GET">`
where the End has a hidden value table
`	<input type="hidden" id="timespans" name="timespans" value="">`
A Submit button called a function to send data
` <button type="button" name="btnSubmit"  onclick="sendme()" id="btnSubmit" class="btn btn-default btn-lg" aria-label="Left Align">`
`function sendme() {
		var arr = $table.bootstrapTable('getData');

if (arr.length == 0){
   alert("Keinen Intervall eingetragen!");
} else { 
		var data = JSON.stringify(arr);
	
		document.getElementById("timespans").value = data;
		document.getElementById("form").submit(); 
}`

in PHP you can retrieve it with
`$timespans =  json_decode($_GET['timespans'], true);`
