### ISSUE TITLE
showAllColumns / hideAllColumns not working

### ISSUE THREAD

**Issue by thomas-nguyen-3** [wenzhixin/bootstrap-table#3018]
This seem not working:
$('#table').bootstrapTable('hideAllColumns');

There is an error as follow when I apply that code
 "undefined is not an object (evaluating 'i')

I tested it here:
http://jsfiddle.net/e3nk137y/12301/

Anyone experienced same issue or am I doing something wrong?

**Comment by superphonic** [comment]
Has anyone looked at this yet? I am also receiving the same error. Thanks

**Comment by liuhetongzi** [comment]
I am also receiving the same error.  Has anyone solved this problem？Thanks

**Comment by djhvscf** [comment]
Fixed in #3132 
Example: http://jsfiddle.net/djhvscf/e3nk137y/13625/

**Comment by thomas-nguyen-3** [comment]
this does not seem to get updated into the Master version ?

**Comment by wenzhixin** [comment]
You can use develop version now.

**Comment by vidishanaresh** [comment]
Hi 

I followed the below code. it works well but pagination gone. any clue. why it happened.
Fixed in #3132
Example: http://jsfiddle.net/djhvscf/e3nk137y/13625/ 

Any suggestions??


Thanks
Rahul
