### ISSUE TITLE
Question about pagination 

### ISSUE THREAD

**Issue by agahe** [wenzhixin/bootstrap-table#302]
In order to present a list of videos I use a bootstrap-table on my website. The user can select a video from the table and run it in a player. But also he can use quick navigation (prev & next buttons).
How can I synchronize button's click event with pagination in a bootstrap-table?
How can I display page with number X after clicking button next/prev? How can I get "pageSize" of table which is displayed actually by user?

**Comment by djhvscf** [comment]
See this @agahe http://issues.wenzhixin.net.cn/bootstrap-table/#methods/selectPage-prevPage-nextPage.html

**Comment by dabros** [comment]
'kinda' related: #535

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/693
