### ISSUE TITLE
获取不到数据

### ISSUE THREAD

**Issue by anjir** [wenzhixin/bootstrap-table#3020]
data： [{
    id: 1,
    name: 'a',
    books: [{
            time: '2222'
        }，{
             time: '2222'
        }]
},{
    id: 1,
    name: 'a',
    books: [{
            time: '2222'
        }，{
             time: '2222'
        }]
},{
    id: 1,
    name: 'a',
    books: [{
            time: '2222'
        }，{
             time: '2222'
        }]
}]
表格上直接显示ID和name,点击查看详情的时候显示books列表里面的time数组，但是books数组获取不到，是怎么回事？

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by anjir** [comment]
i can not get 'books' when i click a row to get detail view ,only can get id and name . function detailFormatter return to me a 'row' which do not contains the array of  'books'

**Comment by fanshaoer** [comment]
你这是合法的json么，json要以大括号开始，大括号结束的。
`{"data":[{.....}]
}`
