### ISSUE TITLE
refresh事件有回调事件吗？

### ISSUE THREAD

**Issue by guangmang** [wenzhixin/bootstrap-table#3025]
$("#tb").bootstrapTable('refresh', { url: actionUrl });

这个方法应该是异步的，我想在refresh之后再操作表格，请问有回调事件吗？

**Comment by richlin2004** [comment]
可以写到 loadSuccess事件中吧？

**Comment by guangmang** [comment]
可以，thank you！

**Comment by liuxw888** [comment]
> 可以，thank you！

您好，我遇到了一个相同的问题，但是那个loadSuccess事件怎么写呢？

**Comment by wenzhixin** [comment]
@liuxw888 事件的语法在这里： https://bootstrap-table.com/docs/api/events/
