### ISSUE TITLE
使用的时候出现了一个 prop的错误

### ISSUE THREAD

**Issue by HuBeichen** [wenzhixin/bootstrap-table#3028]
bootstrap-table.min.js:8 Uncaught TypeError: Cannot read property 'prop' of undefined
    at o.resetView (bootstrap-table.min.js:8)
这个是从console 里面复制出来的，并不知道为什么会出现这个错误，jquery版本切换，也没有用，

**Comment by wenzhixin** [comment]
应该是用法不对，假如问题还存在请重新打开并提供[jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports)，谢谢。
