### ISSUE TITLE
Examples. 

### ISSUE THREAD

**Issue by SlyOne** [wenzhixin/bootstrap-table#303]
Using only one route in all your examples 
/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data1

means if it fails on local host. 
All examples FAIL. 

What is the exact specs for data-url?

**Comment by wenzhixin** [comment]
Added examples repo: https://github.com/wenzhixin/bootstrap-table-examples. just like the docs say, data-url is A URL to request data from remote site.
