### ISSUE TITLE
Cookie extension breaks paging post merging PR #2646

### ISSUE THREAD

**Issue by mayankgoyal** [wenzhixin/bootstrap-table#3032]
After merging PR  #2646, using cookie extension breaks page navigation via the pager as it encapsulates the page navigation functions onPage* and ignores the returned values from it. We need to just propagate the returns to jQuery for it to do the right thing.  

I will publish an PR and provide an fix as well.

**Comment by djhvscf** [comment]
Do you have any example??

**Comment by mayankgoyal** [comment]
Withdrawing as this has incorrect usage at my end and I finally figured out what I did incorrect.
