### ISSUE TITLE
Request to have success as a refresh option

### ISSUE THREAD

**Issue by bennyr103** [wenzhixin/bootstrap-table#3037]
This isn't a bug, just a change request

I want to automatically select a new row that I create after a refresh of the table.  On the Success of the create call I refresh the data in the table and I select the new row by the ID I get back from the back end.  The problem is refresh happens asynchronously so the call to select the row doesn't work because the row isn't there yet.  To get around it I'm doing a straight ajax call with async off and calling 'load' with the results.

I don't love using async off and I'd rather be able to capture the success of the 'refresh'.

I don't want to just listen for refresh events either because I want to do different things with each of the CRUD operations and I'd prefer not to have to code around that if I don't have to.

What do you think?

**Comment by djhvscf** [comment]
You can use the onLoadSuccess event in order to do that

**Comment by bennyr103** [comment]
I didn't want to do a cover it with a blanket listen event because I have different behaviors I wanted to implement when I refresh the table based on the CRUD method.  Sometimes I want to refresh it with the new item created selected and sometimes I want to select an existing item and sometimes I don't want to select any item and sometimes I want to select the first item.  I don't really want an onLoadSuccess event with a bunch of conditionals.  It would be a lot cleaner to just be able to access the success on the refresh.

I'll just keep doing it synchronously then.  Thanks.

**Comment by djhvscf** [comment]
Sorry I don't really understand.. you want to handle a, let's say, "onRefresh" event? I'm not sure why onLoadSuccess event doesn't work for you..

Can you give us a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!

**Comment by bennyr103** [comment]
Sorry, I was talking about the refresh method on bootstrapTable.

$table.bootstrapTable('refresh' {url: someurl, success: function(result, newId));

I make an ajax call to create a new row and then I refresh that table in the success of that ajax call using the refresh method.  Right after the refresh I try to add the selected class to the new row but I can't because refresh is asynchronous.  onLoadSuccess doesn't really work for me because I won't have the ID of the new row to add the selected class to. 

I'll get a jsfiddle in when I get a chance.

Thanks!

**Comment by wenzhixin** [comment]
I think `rowStyle` can solve your problem, for example:
```
var newId = ''

$table.bootstrapTable({
  ...
  rowStyle: function (row) {
    if (row.id === newId) {
      return {
        classes: 'success'
      }
    }
    return {}
  }
})

function createNew() {
  // $.ajax
  newId = theNewIdAjaxCreated
  $table.bootstrapTable('refresh')
}
```
