### ISSUE TITLE
How to change "data-single-select" between "true" and "false" in code

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#3039]
Hello,

At run time in my code, I need table's checkbox be single-select or multiple select based on some condition. How can I do this? I tried following but did not work:

```
 if (myConditon == true)
 {
   $tbl.data("single-select", "true");
   $tbl.data("checkbox-header", "false");
   // here I can still check multiple checkboxes and "check all" checkbox on header still shown
 }
 else
 {
    $tbl.data("single-select", "false");
    $tbl.data("checkbox-header", "true");
 }
```

Thanks much!

**Comment by djhvscf** [comment]
You can use the 'refreshOptions' method in order to change the options, this method will destroy and reinit the table
