### ISSUE TITLE
onPostTable event

### ISSUE THREAD

**Issue by wesleywong** [wenzhixin/bootstrap-table#3040]
I wonder is there a event fires after the full table is rendered and available in the DOM. I understand the existing onPostBody & onPostHeader, but i need a onPostTable event. Thanks

**Comment by wenzhixin** [comment]
I don't know why we need this event, can you provide a jsffidle to show the feature?

**Comment by wesleywong** [comment]
I think my intention (10 months ago) was rendered other library once your table fully render (regardless header or body). 

My works involve in table header & body, so it need to be called once your table render both header & body. I think full table rendered event callback is necessary, it can be benefit other purposes similar like this.

**Comment by Falseee** [comment]
I submitted a PR to add an `postFooter` event, but i think there is no need for an `postTable` because it would triggered instantly after the `postBody` event.

What do you Think @djhvscf @wenzhixin ?

**Comment by djhvscf** [comment]
Agree @Falseee. PostBody is the best solution
