### ISSUE TITLE
searchText is not working

### ISSUE THREAD

**Issue by Huan999888** [wenzhixin/bootstrap-table#3041]
Hi, Admin -

I'd like to initialize the search text to "school" below that whenever I load the page I can get the content filtered by "school", however, the value of "school" can not be passed, though. It seems the searchText is not working. Please help, thanks.

   $('#table').bootstrapTable({
        classes: 'table table-responsive table-no-bordered',
        undefinedText: '',
        iconsPrefix: 'fa',
        showRefresh: true,
        search: true,
        **searchText: 'School',**
        pageSize: 100,
        pagination: true,
        sidePagination: 'server',
        sortable: true,
        showMultiSort: true,
        cookie: true,
        cookieExpire: '2y',
        mobileResponsive: true,
        showExport: true,
        showColumns: true,
        exportDataType: 'all',
        exportTypes: ['csv', 'excel', 'txt','json', 'xml'],
        maintainSelected: true,
        paginationFirstText: "{{ trans('general.first') }}",
        paginationLastText: "{{ trans('general.last') }}",
        paginationPreText: "{{ trans('general.previous') }}",
        paginationNextText: "{{ trans('general.next') }}",
        pageList: ['10','25','50','100','150','200','500','1000'],
        exportOptions: {
            fileName: 'assets-export-' + (new Date()).toISOString().slice(0,10),
        },
        icons: {
            paginationSwitchDown: 'fa-caret-square-o-down',
            paginationSwitchUp: 'fa-caret-square-o-up',
            sort: 'fa fa-sort-amount-desc',
            plus: 'fa fa-plus',
            minus: 'fa fa-minus',
            columns: 'fa-columns',
            refresh: 'fa-refresh'
        },
    });

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Huan999888** [comment]
Hi, Admin -

Here is a jsFiddle example, whatever I change the value of searchText at Line 12, I could not get the search result filtered by the imputed value. Or is there any way that I can fire a text search with a value without typing anything in the search box?

https://jsfiddle.net/e3nk137y/12589/

**Comment by wenzhixin** [comment]
Solution: https://jsfiddle.net/wenyi/e3nk137y/18262/
