### ISSUE TITLE
filterBy function with <, <=, > and >= than

### ISSUE THREAD

**Issue by ManicPumpkin** [wenzhixin/bootstrap-table#3042]
Hey guys,

is there a way to filter values inside a column of the BS table with a filter greater or smaller than a given value? 

For example filtering the temperature, which is < 20°C in a column which has given values like [34, 20, 8, -6, 56, -24]. Currently I'm only able to filter for a temperature equal a given value.

**Comment by wenzhixin** [comment]
Merged in the develop branch.

**Comment by vossivossi** [comment]
> Merged in the develop branch.

Where can I download the develop branch?

**Comment by wenzhixin** [comment]
This feature has been released in the latest version.

**Comment by vossivossi** [comment]
Ok, thank you very much fpr the fast reply. I will give it a try!

**Comment by farayman3** [comment]
I believe this feature does not work for comparing negative values (E.g. "< -10" or "-10 >") or am I not doing this right?

**Comment by UtechtDustin** [comment]
@farayman3 your right, i created a PR which fix that issue!
