### ISSUE TITLE
Export to Excel with Title in First Two Rows

### ISSUE THREAD

**Issue by bitsincph** [wenzhixin/bootstrap-table#3049]
Hello,

How to export to XLS to include a title found in first two rows?

Example:

SAMPLE REPORT
DATE:

column1 | column2 | column3

your help is greatly appreciated.

Thanks.

**Comment by GiriB** [comment]
@bitsincph This is not a standard XLS layout. Can you explain your use case ?

**Comment by bitsincph** [comment]
@GiriB Thanks for reply.

Looking to insert a title on the downloaded xls file.. Example below: See Row 1 and 2.

This will allow users to generate their own report with headers to fit their company needs.

<a href="http://tinypic.com?ref=muzkf9" target="_blank"><img src="http://i67.tinypic.com/muzkf9.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by bitsincph** [comment]
Anyone?

**Comment by wenzhixin** [comment]
Not supported this feature, I think you can implement by server, for example php.
