### ISSUE TITLE
cookie 和 选择每页条数 同时使用

### ISSUE THREAD

**Issue by hidcc** [wenzhixin/bootstrap-table#3050]
当我同时使用`data-side-pagination="server" data-cookie="true" data-page-list="[10, 25, 50, 100, ALL]"` 时，修改pagesize后刷新并不会重置offset， 导致数据偏移不正确， onPageChange事件无法直接区分是哪个改动，不知有什么较好的解决方案？

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by hidsvip** [comment]
table attribute: `data-side-pagination="server" data-cookie="true" data-page-list="[10, 25, 50, 100, ALL]"` 
When I modified the pagesize and refresh the page, the param 'offset' is not be reset.

such as:
1. show page,  request: `order=asc&offset=0&limit=10`
2. next page, request:`order=asc&offset=10&limit=10`
3. change pagesize: request:`order=asc&offset=0&limit=25`
4. refresh page, request:`order=asc&offset=25&limit=25`

If the total is 11, the page is empty after refresh the page, and I can't choose the page number.

**Comment by guomaoqiu** [comment]
table attribute: data-side-pagination="server" data-cookie="true" data-page-list="[10, 25, 50, 100, ALL]"
When I modified the pagesize and refresh the page, the param 'offset' is not be reset.

such as:

show page, request: order=asc&offset=0&limit=10
next page, request:order=asc&offset=10&limit=10
change pagesize: request:order=asc&offset=0&limit=25
refresh page, request:order=asc&offset=25&limit=25
If the total is 11, the page is empty after refresh the page, and I can't choose the page number.

**Comment by hidsvip** [comment]
@djhvscf @wenzhixin These two plugins can't work well together

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by hidsvip** [comment]
@djhvscf  http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html
this demo has the problem too, 
You can see it in the following ways：
1. change page to 80
2. change pagesize to 100
3. refresh page

**Comment by hidsvip** [comment]
@djhvscf @wenzhixin  http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html
this demo has the problem too, 
You can see it in the following ways：
1. change page to 80
2. change pagesize to 100
3. refresh page

**Comment by petar313** [comment]
To solve this, I have added this line to /src/extensions/cookie/bootstrap-table-cookie.js after line 364

`setCookie(this, cookieIds.pageNumber, this.options.pageNumber);
`

It will reset page number to 1 (what is on screen).

There is at least one more place to add this line to solve some other issues with cookies (Like searching when pagenumber>1 leaves cookie on that page number)

**Comment by wenzhixin** [comment]
@petar313 PR is welcome.
