### ISSUE TITLE
在th 中设置 data-sort-name 无效果

### ISSUE THREAD

**Issue by qw3376803** [wenzhixin/bootstrap-table#3052]
server端分页好像直接忽略了th中设置的data-sort-name 。取到的永远是data-field的字段名称
[问题地址](https://segmentfault.com/q/1010000008863760)
:)

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
在最新的 develop 版本已修复。
