### ISSUE TITLE
多级表头下switchcolumn会导致上下级表头错位

### ISSUE THREAD

**Issue by anizephyr** [wenzhixin/bootstrap-table#3054]
首先非常感谢分享如此优秀的插件
在使用时发现一个小问题：
多级菜单的情况下，隐藏列会导致上下级菜单位置关系错误
![before1](https://cloud.githubusercontent.com/assets/26772673/24484404/96c16b0e-1530-11e7-8918-009f64882802.png)

1.上图是隐藏列之前的状态
![after1](https://cloud.githubusercontent.com/assets/26772673/24484407/9d116464-1530-11e7-9e47-b2d88c40f481.png)

2.上图是隐藏列 “年” 之后，会发现“月业务净收” 出现在了 “负债” 下面，他本应该属于 “净收”
请问有什么好的解决办法吗？感谢！

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by anizephyr** [comment]
here #2637
the same situation

**Comment by anizephyr** [comment]
the problem seems to be solved...
code changes as below:
///////////////////////////--Zephyr
    
    BootstrapTable.prototype.initHeader_zephyr = function () {
        var that = this,
            visibleColumns = {},
            $html = $('<thead></thead>');

        this.header = {
            fields: [],
            styles: [],
            classes: [],
            formatters: [],
            events: [],
            sorters: [],
            sortNames: [],
            cellStyles: [],
            searchables: []
        };
        $.each(this.options.columns, function (i, columns) {
            var $tr = $html.append('<tr></tr>').find('tr:last');
            
            if (i === 0 && !that.options.cardView && that.options.detailView) {
                var thistr = [sprintf('<th class="detail" rowspan="%s"><div class="fht-cell"></div></th>',
                        that.options.columns.length)];
                $tr.append(thistr.join(''));
            }

            $.each(columns, function (j, column) {
                var text = '',
                    halign = '', // header align style
                    align = '', // body align style
                    style = '',
                    class_ = sprintf(' class="%s"', column['class']),
                    order = that.options.sortOrder || column.order,
                    unitWidth = 'px',
                    width = column.width;

                if (column.width !== undefined && (!that.options.cardView)) {
                    if (typeof column.width === 'string') {
                        if (column.width.indexOf('%') !== -1) {
                            unitWidth = '%';
                        }
                    }
                }
                if (column.width && typeof column.width === 'string') {
                    width = column.width.replace('%', '').replace('px', '');
                }

                halign = sprintf('text-align: %s; ', column.halign ? column.halign : column.align);
                align = sprintf('text-align: %s; ', column.align);
                style = sprintf('vertical-align: %s; ', column.valign);
                style += sprintf('width: %s; ', (column.checkbox || column.radio) && !width ?
                    '36px' : (width ? width + unitWidth : undefined));

                if (typeof column.fieldIndex !== 'undefined') {
                    that.header.fields[column.fieldIndex] = column.field;
                    that.header.styles[column.fieldIndex] = align + style;
                    that.header.classes[column.fieldIndex] = class_;
                    that.header.formatters[column.fieldIndex] = column.formatter;
                    that.header.events[column.fieldIndex] = column.events;
                    that.header.sorters[column.fieldIndex] = column.sorter;
                    that.header.sortNames[column.fieldIndex] = column.sortName;
                    that.header.cellStyles[column.fieldIndex] = column.cellStyle;
                    that.header.searchables[column.fieldIndex] = column.searchable;

                    if (!column.visible) {
                    	$html.find('>tr').each(function(p){
                    		if(p<i){
                    			$(this).find("th").each(function(q){
                    				if($(this).hasClass(column.field)){
                    					var thiscolspan = $(this).attr('colspan')!=undefined?$(this).attr('colspan'):0;
                    					if(thiscolspan>2){
                    						$(this).attr('colspan',thiscolspan-1);
                    					}
                    					else if(thiscolspan==2){
                    						$(this).removeAttr('colspan');
                    					}
                    					else{
                    						$(this).remove();
                    					}
                    				}
                    			});
                    		}
                    	});
                        return;
                    }

                    if (that.options.cardView && (!column.cardVisible)) {
                        return;
                    }

                    visibleColumns[column.field] = column;
                }

                var thisth = ['<th' + sprintf(' title="%s"', column.titleTooltip),
                        column.checkbox || column.radio ?
                                sprintf(' class="bs-checkbox %s"', column['class'] || '') :
                                class_,
                            sprintf(' style="%s"', halign + style),
                            sprintf(' rowspan="%s"', column.rowspan),
                            sprintf(' colspan="%s"', column.colspan),
                            sprintf(' data-field="%s"', column.field),
                            '>'];
               
                var $th = $tr.append(thisth.join('')+'</th>').find('th:last');
                var thisdiv = [sprintf('<div class="th-inner %s">', that.options.sortable && column.sortable ?'sortable both' : '')];                
                text = that.options.escape ? escapeHTML(column.title) : column.title;

                if (column.checkbox) {
                    if (!that.options.singleSelect && that.options.checkboxHeader) {
                        text = '<input name="btSelectAll" type="checkbox" />';
                    }
                    that.header.stateField = column.field;
                }
                if (column.radio) {
                    text = '';
                    that.header.stateField = column.field;
                    that.options.singleSelect = true;
                }
                $th.append(thisdiv.join('')+text+'</div>');
                $th.append($('<div class="fht-cell"></div>'));
                
                //html.push('</div>');
            });
        });
        this.$header.html($html.html());
/////////////////////////////////--Zephyr
        this.$header.find('th[data-field]').each(function (i) {

then add parent column's class using field name:
$table.bootstrapTable({
        	data:data,
            height: getHeight(),
            columns: [
                [
                    {
                        title: 'col0',
                        field: 'col0',
                        rowspan: 2,
                        align: 'center',
                        valign: 'middle',
                        sortable: true,
                        footerFormatter: totalTextFormatter
                    }, {
                    	'class':'col1 col2',
                        title: 'col1&2',
                        colspan: 2,
                        align: 'center'
                    }, {
                    	'class':'col3 col4',
                        title: 'col3&4',
                        colspan: 2,
                        align: 'center'
                    }
                  
                ],
                [
                    {
                        field: 'col1',
                        title: 'col1',
                        align: 'center'
                    }, {
                        field: 'col2',
                        title: 'col2',
                        align: 'center',
                      
                    }, {
                        field: 'col3',
                        title: 'col3',
                        align: 'center',
                    },
                    {
                        field: 'col4',
                        title: 'col4',
                        align: 'center',
                    }
                ]
            ]
        });

**Comment by anizephyr** [comment]
then add parent column's class using field name:

$table.bootstrapTable({
        	data:data,
            height: getHeight(),
            columns: [
                [
                    {
                        title: 'col0',
                        field: 'col0',
                        rowspan: 2,
                        align: 'center',
                        valign: 'middle',
                        sortable: true,
                        footerFormatter: totalTextFormatter
                    }, {
                    	'class':'col1 col2',
                        title: 'col1&2',
                        colspan: 2,
                        align: 'center'
                    }, {
                    	'class':'col3 col4',
                        title: 'col3&4',
                        colspan: 2,
                        align: 'center'
                    }
                  
                ],
                [
                    {
                        field: 'col1',
                        title: 'col1',
                        align: 'center'
                    }, {
                        field: 'col2',
                        title: 'col2',
                        align: 'center',
                      
                    }, {
                        field: 'col3',
                        title: 'col3',
                        align: 'center',
                    },
                    {
                        field: 'col4',
                        title: 'col4',
                        align: 'center',
                    }
                ]
            ]
        });
