### ISSUE TITLE
数据不能同步维护,或者刷新,删除东西后,获取到的index是删除的数据,

### ISSUE THREAD

**Issue by langching** [wenzhixin/bootstrap-table#3055]
首先,感谢作者,东西很nice.
目前开发者中遇到了个问题,求解答下.谢谢.
1.首先我做了表格的新增,修改,删除,三个功能.
Q:当我从表单中用""append""新增数据到表格后(比如新增三条数据),在用remove方法删除其中第二个,在修改剩下的数据时,获取index时,会出现问题,会获取到已删除的那条数据的index,导致了用updateRow插入修改的数据时,会出现index位移,或者插入不进去,,不知道是不是数据本身维护没有同步还是其他什么问题,,作者能否帮忙解决下,谢谢.

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by toQhot** [comment]
我也碰到过类似的问题
你可以尝试设置属性
sidePagination: "client",
希望可以解决你的问题

**Comment by wenzhixin** [comment]
If the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
