### ISSUE TITLE
how to set bgcolor of the cell? 

### ISSUE THREAD

**Issue by rb8163** [wenzhixin/bootstrap-table#3056]
I'm using wenzhixin bootsrap table. How to set the bgcolor of the cell in table?
I get the bgcolor from server side based on some business logic, when i use this api as follows... it's not considering bgcolor specified in the html.
For Example, for the below example bgcolor attribute is not considered while rendering. 
Appreciate your inputs on this.
	<table 	    		    
		    id="table"		    
		    data-toggle="table" 
    		data-search="true"		 
    		data-toolbar="#toolbar"
    		data-height="500"
    		data-show-refresh="true"
    		data-show-toggle="true"		
    		 >		  			
		<thead>
			<tr>
				<th align=center>Colum1</th>
				<th align=center>Colum2 </th>
				<th align=center>Colum3</th>
				<th align=center>Colum4</th>
			</tr>
		</thead>
		<tbody>
		<tr>
					<td>data1 </td>
					<td bgcolor='red' align=center nowrap="nowrap"><b>data2</b></td>
					<td bgcolor='green' align=center nowrap="nowrap"><b>data3</b></td>
					<td bgcolor='blue' align=center nowrap="nowrap"><b>data4</b></td>
					<td bgcolor='white' align=center nowrap="nowrap"><b>data5</b></td>
				</tr>
					<tr>
					<td>data1 </td>
					<td bgcolor='yellow' align=center nowrap="nowrap"><b>data2</b></td>
					<td bgcolor='green' align=center nowrap="nowrap"><b>data3</b></td>
					<td bgcolor='pink' align=center nowrap="nowrap"><b>data4</b></td>
					<td bgcolor='white' align=center nowrap="nowrap"><b>data5</b></td>
				</tr>
		</tbody>		
	</table>

**Comment by hxnan** [comment]
You can try the param below:
formatter	
data-formatter	

Function	undefined	
The context (this) is the column Object. 
The cell formatter function, take three parameters: 

value: the field value. 
row: the row record data.
index: the row index.

the function return str is the html in the cell.
you can build the cell in html formate by the cell value .

**Comment by rb8163** [comment]
Thanks for quick response!! I'm getting the bg color of the cell from service side.Business logic associated to cell color is placed in server side. So, what ever the bgcolor i get it from server, i have to render it in client side. Actually it's struct based application. I can't change the bg color based on value or row or column.Appreciate if you advice some solution to this problem.

**Comment by martinburch** [comment]
@rb8163 maybe something like this?
http://jsfiddle.net/30sx4h3t/361/

```
function cellStyle(value, row, index) {
console.log(row.name_cell_color);
  return {css: 
  {"background-color": row.name_cell_color}
  };
}
```

This is just a quick example.

**Comment by djhvscf** [comment]
@rb8163 the example that @martinburch provided is working for you?

**Comment by rb8163** [comment]
Hi,
Thanks for response!
I'm not using the Json Object. working on legacy application(Using Structs). 
My sample UI code as follows..I'm setting the bg color dynamically. For the below code.
Bootstrap table is working fine. But, Bg color is not rendering.
In short, i need to set the bg color of the cell dynamically, not based on index or value of the cell, It's decided by business logic in server side. Appreciate your help in this regard.
	<s:if test="condition != null">
	<table  id="table"		    
		    data-toggle="table" data-search="true"     data-toolbar="#toolbar"
    		  data-height="500" data-show-refresh="true"	data-show-toggle="true" >	 	  			
	<thead> <tr>
				<th>Col1</th> <th>Col2</th> <th>Col3</th>
				<th>Col4</th><th>Col5</th>	
			</tr>
		</thead> 		<tbody>
			<s:iterator value="List" var="Stock">
			<tr>
		<td align=center nowrap="nowrap" ><b><s:property value="#Stock.Name" /></b></td><td bgcolor='<s:property value="#system.avg24hCpuColor" />' align=center nowrap="nowrap"><b><s:property value="#Stock.avg24h" /></b></td>				
<td bgcolor='<s:property value="#system.peak24hCpuColor" />' align=center nowrap="nowrap">         <b><s:property value="#Stock.peak24h" /></b></td>								
<td bgcolor='<s:property value="#system.avg90dCpuColor" />' align=center nowrap="nowrap">   <b><s:property value="#Stock.avg90d" /></b></td>
<td bgcolor='<s:property value="#system.peak90dCpuColor" />' 		
align=center nowrap="nowrap"><b><s:property value="#Stock.peak90d" /></b></td>						
				</tr>
			</s:iterator>
		</tbody>	
		</table>
	</s:if>

**Comment by martinburch** [comment]
So you're providing HTML tables to Bootstrap instead of using JS objects? Please provide an example table's HTML code ('view source' of the webpage). I don't understand what you're trying to show in the XML+markdown code.

**Comment by rb8163** [comment]
Hi,

Here is the updated link. 
http://jsfiddle.net/30sx4h3t/367/

**Comment by rb8163** [comment]
updated sample code. bg color will be changed based on some business logic which exists in server side code.I don't have control on it.i will have to set the bgcolor which received from server.

**Comment by martinburch** [comment]
Wow, I didn't realize it was possible to set the background color with a special tag.

Here's some documentation about this old property:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement/bgColor

We've had a similar issue before https://github.com/wenzhixin/bootstrap-table/issues/1378

I don't think the proposed solution, using a div, looks so good ...
![image](https://cloud.githubusercontent.com/assets/2335284/24714563/c6f3f09a-1a20-11e7-9281-36fea6457ca0.png)

I think it should look more like this, yes?
![image](https://cloud.githubusercontent.com/assets/2335284/24714497/9924cfe0-1a20-11e7-8f93-d32bdc17eb4b.png)

**Comment by martinburch** [comment]
@wenzhixin 
maybe we could capture the `style` HTML attribute of a cell (e.g. `<td style="background-color: red">data1</td>`) as other properties are being captured ...
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L711

... and render it to the DOM when the other cell properties are rendered:
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1709

Is there a good reason not to do this?

**Comment by rb8163** [comment]
As specified in other thread,I'm able to handle this issue with Div tag inside TD.Now Bg color is persisting. Thanks for help. You can close this.

**Comment by rb8163** [comment]
Hi, I agree to above comments by martinburch . Now, i'm able to set the bg color. But, it looks not good.

**Comment by rb8163** [comment]
Appreciate if you suggest any work around.

**Comment by martinburch** [comment]
@rb8163 yes, since you can modify your HTML output (to add `<div>`) you might also try making `bgcolor` a HTML5 data attribute. Then you can use the `data-bgcolor` values to set the colors with the bootstrap-table `cellStyle` [column option](http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options). Here's an example:

http://jsfiddle.net/30sx4h3t/369/

**Comment by rb8163** [comment]
@MartinBurch: It's working thanks you for help.
