### ISSUE TITLE
struts2 排序参数查询传递异常

### ISSUE THREAD

**Issue by 975545486** [wenzhixin/bootstrap-table#3057]
![default](https://cloud.githubusercontent.com/assets/18388391/24537844/ea791e26-1617-11e7-9adc-18bec69b6b1c.png)
![default](https://cloud.githubusercontent.com/assets/18388391/24537852/f64e474e-1617-11e7-8a5e-8e548a15690b.png)
![default](https://cloud.githubusercontent.com/assets/18388391/24537863/1753f060-1618-11e7-9f95-33a79cebf64e.png)

struts2 action注解后台代码
	if (StringUtil.isNotBlank(this.getSortName())) {
}
获得不到传递参数的值

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?
