### ISSUE TITLE
export导出全部时，导出数据只有当前页

### ISSUE THREAD

**Issue by apple5702** [wenzhixin/bootstrap-table#3059]
配置exoprt插件选择导出all类型时，发现导出代码
if (that.options.exportDataType === 'all' && that.options.pagination) {
                        that.$el.one(that.options.sidePagination === 'server' ? 'post-body.bs.table' : 'page-change.bs.table', function () {
                            doExport();
                            that.togglePagination();
                        });
                        that.togglePagination();
                    } 
执行完毕，发现excel中数据只有当前页，并没有导出所有的数据信息

**Comment by wppele** [comment]
清理缓存

**Comment by wenzhixin** [comment]
应该是服务器返回的数据不对，你看下 network，当没有传 limit 的时候，应该是返回全部的。

**Comment by TKDtiny** [comment]
并不是返回数据不对~  如果你仔细看network的话  你会发现 执行doExport(); 导出时，  并没有去服务器请求数据 而是在导出事件执行之后才去请求数据，所以始终导出的不是全部数据，我也碰到了这个问题，很想知道怎么解决。

**Comment by mollywp** [comment]
> 并不是返回数据不对~ 如果你仔细看network的话 你会发现 执行doExport(); 导出时， 并没有去服务器请求数据 而是在导出事件执行之后才去请求数据，所以始终导出的不是全部数据，我也碰到了这个问题，很想知道怎么解决。

我现在也遇到了这个问题,不知你解决了没有
