### ISSUE TITLE
Using datepicker filter-control on 2 identical tables causes both tables' datepicker field to be set

### ISSUE THREAD

**Issue by jvdmr** [wenzhixin/bootstrap-table#3063]
When putting two tables with identical column sets (but different data), both with filter-control, on the same page, then selecting a date using the datepicker from 1 table's filter, the date on the other table's filter is also set. The filter is not applied though.

https://jsfiddle.net/0yjj5r91/

This is caused by the fix for #2418, where the set of classes is used to select the field to be set.

**Comment by jvdmr** [comment]
Fixed with PR #3061 - https://jsfiddle.net/eo9tdbgg/1/

**Comment by ljw1264654273** [comment]
how to use id on datepicker fields to set value ?

**Comment by ljw1264654273** [comment]
这个问题解决了吗？我设置了data-height显示不了datepicker选择的时间，jsfiddle也看不出解决的样子

**Comment by jvdmr** [comment]
This issue is about using datepicker on different tables on the same page, when the tables have the same structure but different data.

The first jsFiddle shows the bug: focus on the input field for the first column. The datepicker appears below. Select a date. You'll see that the selected date is filled in in the input field you selected AND in the input field for the first column of the other table.

The second jsFiddle shows the fixed version: perform the same actions. You'll see that only the field you selected is now filled in, and the other table is left alone.

You don't need to do anything about this as a developer, the id field is filled in and used internally in the library. It is not an id on any input field.

This issue has nothing to do with putting a value in the filter fields programatically. To set the value of a datepicker field in the filter-control part, I suggest simply adding an id to your table, then using jQuery to get the filter-control field and set the value:
`$("#my-table-id th[data-field=description] .filter-control input.date-filter-control").val("new value");` (see https://jsfiddle.net/eo9tdbgg/5/).

There's currently no built-in way in bootstrap-table to do this as far as I know. If you think there should be, please check https://github.com/wenzhixin/bootstrap-table/issues for an existing feature request or create a new ticket. You may also implement it yourself and create a pull request.

This issue has nothing to do with data-height. Please either find the correct issue in https://github.com/wenzhixin/bootstrap-table/issues or create a new ticket.
