### ISSUE TITLE
How to make pagination work with ajax call

### ISSUE THREAD

**Issue by delockdown** [wenzhixin/bootstrap-table#3071]
Hi All,
How can I make the pagination without url option in bootstrap table. Without url pagination didn't work i wasn't able to find out way to do that. If I remove the **url** pagination is not working.

I have use following code 
```
               url: '/contacts',
                reorderableColumns: true,
                maxMovingRows: 1,
                showColumns: true,
                smartDisplay: false,
                sidePagination: 'server',
                pageSize: 50,
                pageList: [50, 75, 100],
                showRefresh: false,
                pagination: true,
                ajax: this.updateTable(),
                paginationVAlign: 'top',
                paginationHAlign: 'right',
```

In update table function, I have written my data retrieval promise function. I want to get the sorting and pagination values 

Regards,
Thank you.

**Comment by annabateman** [comment]
Have you tried removing the sidePagination: 'server'

**Comment by delockdown** [comment]
done using ajax option. Thanks guys.
