### ISSUE TITLE
How to change the arrow icon above the sort table???

### ISSUE THREAD

**Issue by Christian-Yang** [wenzhixin/bootstrap-table#3072]
How to change the arrow icon above the sort table???

Having checked the previous questions and answers, did not find a good solution.
![icon_proc](https://cloud.githubusercontent.com/assets/25613332/24639454/4cca7d6a-1922-11e7-9631-075aea7f10c1.jpg)

wish your  help   thank you !

**Comment by djhvscf** [comment]
You can change them here: 
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.css#L99-L109
