### ISSUE TITLE
After applying filter, sort is undone but still indicated

### ISSUE THREAD

**Issue by jvdmr** [wenzhixin/bootstrap-table#3073]
Using filter-control, when adding a filter, then sorting the column, sort is applied as expected.
After this, editing filter (or removing altogether) shows new filtered (or unfiltered) data, unsorted, although column header still shows sorting caret.

See jsfiddle: https://jsfiddle.net/ojhcmzLy/1/
Enter 'for' in first column filter -> only 2 entries
Sort ascending -> first entry "Redmine ...", second entry "Show/hide ..."
Make first column filter empty -> all data shown, unsorted, but column header still shows ascending caret

**Comment by Falseee** [comment]
New example: https://jsfiddle.net/dvhbr56z/7/
filter on description for b, sort asc, result :
```
bab
bbb
```
remove the s on search input and add it agai, new result
```
bbb
bab
```
but the asc "arrow" is still shown.
