### ISSUE TITLE
Server-side : showing the total entries filtered

### ISSUE THREAD

**Issue by jy95** [wenzhixin/bootstrap-table#3075]
Hello,

I come from Datatables and the only function I didn't retrieve in bootstrap-table is showing the total entries filtered.

For example : 
```
Showing 1 to 10 of 42 entries (filtered from 57 total entries)
```

If you prefer, here are a resume: 
```
Datatables|Bootstrap-table
recordsTotal | total
data | rows
recordsFiltered | ????
```

Any ideas to display this ? I have this information but just don't know how to pass it to Bootstrap-table with a custom ajax (Inside it, I choose what I want to send to the server and handle in my way the result, all is in POST requests (GET are reserved for templates) ).

Thanks

**Comment by Falseee** [comment]
#4226
