### ISSUE TITLE
Filter Control Extension shifts focus on IE 11

### ISSUE THREAD

**Issue by Opirat21** [wenzhixin/bootstrap-table#3078]
Hi,
I'm experiencing a bug of Bootstrap Table Filter-Control extension on Internet Explorer 11. When I digit in any filter control input, immediately the focus shifts always on the last input filter. Also if I try to delete the text in the input focus shifts on the last one
I made a fiddle of the issue.

https://jsfiddle.net/f7nb93m0/2/

On Google Chrome 57 works fine.

Best Regards

**Comment by Opirat21** [comment]
Any news about?

**Comment by cynisme** [comment]
Same issue here. Would love a solution.

**Comment by cynisme** [comment]
Do you know when the 1.12 milestone will be?

**Comment by Valery1991** [comment]
Figured out that there's an issue with the cursor position. probably  outdated?

see pull request, I know this fix is planned for 1.12 milestone but we have no word or update on that so maybe you can use this.
