### ISSUE TITLE
UpdateRow/updateByUniqueId only extended data.

### ISSUE THREAD

**Issue by andig89** [wenzhixin/bootstrap-table#3079]
Simple problem - updateRow and updateByUniqueId use $.extended which replace existing properties or add new but don't delete any properties!

http://jsfiddle.net/andig89/0y91abaL/

updateByUniqueId:
```
BootstrapTable.prototype.updateByUniqueId = function (params) {
        var that = this;
        var allParams = $.isArray(params) ? params : [ params ];

        $.each(allParams, function(i, params) {
            var rowId;

            if (!params.hasOwnProperty('id') || !params.hasOwnProperty('row')) {
                return;
            }

            rowId = $.inArray(that.getRowByUniqueId(params.id), that.options.data);

            if (rowId === -1) {
                return;
            }
            $.extend(that.options.data[rowId], params.row);
        });

        this.initSearch();
        this.initPagination();
        this.initSort();
        this.initBody(true);
    };
```
Problem:
`$.extend(that.options.data[rowId], params.row);`
Resolve:
I would add param "replace" and replace above code by:
```
if (params.hasOwnProperty('replace') && params.replace) {
    that.options.data[rowId] = params.row;
} else {
    $.extend(that.options.data[rowId], params.row);
}
```
updateRow:
```
BootstrapTable.prototype.updateRow = function(params) {
    var that = this;
    var allParams = $.isArray(params) ? params : [params];

    $.each(allParams, function(i, params) {
        if (!params.hasOwnProperty('index') || !params.hasOwnProperty('row')) {
            return;
        }
        $.extend(that.options.data[params.index], params.row);
    });

    this.initSearch();
    this.initPagination();
    this.initSort();
    this.initBody(true);
};
```
Problem:
`$.extend(that.options.data[params.index], params.row);`
Resolve:
I would add param "replace" and replace above code by:
```
if (params.hasOwnProperty('replace') && params.replace) {
    that.options.data[params.index] = params.row;
} else {
    $.extend(that.options.data[params.index], params.row);
}
```

**Comment by djhvscf** [comment]
@andig89 I you're right, can you create a new **PR** and an fiddle with this example?

**Comment by andig89** [comment]
Sure, I created PR. In terms of example:
http://jsfiddle.net/andig89/0y91abaL/
with manual add script:
http://jsfiddle.net/andig89/0y91abaL/5/

I suggest You make base version of examples in fiddle like I do. For example http://jsfiddle.net/andig89/0y91abaL/ === http://jsfiddle.net/andig89/0y91abaL/4/

**Comment by thornomad** [comment]
Just to add to this discussion, I was surprised by the behavior of `updateRow` myself today when the server returned a value of `undefinied` but `updateRow` kept the old populated value.  Of course, this is because of `$.extend`.  

I am curious though if `$.extend` is really necessary to be used at all ?  `updateRow`, to me, implies that when I give you a new `row` of data it all be used in redrawing that table row.  I know this would be a change in functionality (so maybe the pull request is better to add explicit request to `replace`) ... but for my own part, I would have expected `updateRow` to use an `undefined` value.

For reference: pull #3085

**Comment by UtechtDustin** [comment]
In my opinion the current functionality is correct.
The method `updateRow` will UPDATE the data, if only one data is given or all data does not matter.

If we implement something like that, we should do it like the PR #3085 (new column option or new function e.g. `replaceRow`).
