### ISSUE TITLE
Add the ability to not search specified columns

### ISSUE THREAD

**Issue by odannyboy000** [wenzhixin/bootstrap-table#308]
Some column data has complex html that gets searched (for example a button). Currently if one were to search for "button", every record that contains the button will be returned.

Adding a data-searchable attribute to the <th> tags can easily solve this problem.

NOTE: I'm doing all searches client-side.

**Comment by wenzhixin** [comment]
Added `searchable` column option: http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options
