### ISSUE TITLE
throw "Uncaught TypeError: Cannot read property 'settings' of undefined " exception when enable editable inside a form.

### ISSUE THREAD

**Issue by xiaoyc** [wenzhixin/bootstrap-table#3080]
The issue is when i enable  bootstraptable editable inside a form element, it will throw the 'Uncaught TypeError: Cannot read property 'settings' of undefined' exception ,because x-editable renders another form, it will have a form inside another form and it is causing the problem with the validation libraries. Unfortunately, I need to keep the validation libraries and I can't remove either the form or the validation.

The message displayed after clicking on the anchor is: Uncaught TypeError: Cannot read property 'settings' of undefined

**Comment by wenzhixin** [comment]
#1357 http://jsfiddle.net/wenyi/e3nk137y/6491/
If the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
