### ISSUE TITLE
Memory leak on table update

### ISSUE THREAD

**Issue by andyflury** [wenzhixin/bootstrap-table#3081]
There seems to be a memory leak in the updateByUniqueId. With the attached example (table.html) the table gets updated 10'000 times every time the button is clicked. In Google Chrome (v. 58) the DOM memory just grows linearly. After about 10 clicks memory consumption is at 500MB already

	    $(function () {
	        $button.click(function () {
	        	for (i = 0; i < 10000; i++) { 
	            	var randomId = 100 + ~~(Math.random() * 100);
	            	$table.bootstrapTable('updateByUniqueId', {
	                	id: 1,
	                	row: {
	                    	name: 'Item ' + randomId,
	                    	price: '$' + randomId
	                	}
	            	});        		
	        	}
	        });
	    });

[table.html.txt](https://github.com/wenzhixin/bootstrap-table/files/906611/table.html.txt)

**Comment by andyflury** [comment]
![image](https://cloud.githubusercontent.com/assets/4620920/24816305/7543cfe0-1bd8-11e7-9180-595e0bc54ad3.png)

**Comment by martinburch** [comment]
Here's a fiddle of @andyflury's demo file https://jsfiddle.net/tety3ktz/

I took a look at this in Firefox's Task Manager plugin. The largest memory growth is in DOM size, but after waiting for a while, this goes back down.

I think we're seeing the result of writing to the DOM too often, that is, pushing updates too often to the table, not a memory leak.

I'm not sure how to fix this within bootstrap-table, but if you stored your data in an array and called the `load` method every, say, 300 milliseconds, you could avoid reloading the table too often.

**Comment by andyflury** [comment]
Thanks @martinburch! We have a financial application that updates number based on market data, potentially millions of times per day. I though about re-loading the entire table on a regular basis as well, but this would be visible to the user and might cause other issues. We ended up using just a plain HTML table and updating the cells via JQuery. It is very fast and there is no memory problem this time. Obviously all the nice feaures of the bootstrap-table like sort, filtering and pagination are not usable anymore

**Comment by martinburch** [comment]
Since you are already updating the HTML of table cells via jQuery, you might try using bootstrap-table's `updateCell` with `{reinit: false}`.

**Comment by andyflury** [comment]
Currently I'm using a plain HTML table, but maybe that would be an option as well, using bootstrap-table on the initial load, then update the underlying HTML table directly (outside bootstrap-table) and at the same tame use updateCell with {reinit: false} to keep the table model up-to-date in case the user changes sorting, filtering, paginating etc. Thanks!

**Comment by wenzhixin** [comment]
Merged into develop branch.
