### ISSUE TITLE
点击第2页的时候服务端数据返回空....

### ISSUE THREAD

**Issue by guomaoqiu** [wenzhixin/bootstrap-table#3083]
楼主你好，使用了你的这个之后发现，当我分页每页显示10个数据的时候默认情况下是正常的，但是当我点击第二页的时候去发现服务器返回空的结果；
我看了下你线上的demo 跟我自己的配置基本一致；
请教下，是我哪里配置有问题吗？

**Comment by martinburch** [comment]
Server-side pagination is difficult to debug without being able to see what's being returned by the server. 

I suppose your server didn't return any usable data for page 2. Try checking in your browser's Developer Tools, Network tab to see the request generated by bootstrap-table and to see if any data is returned.

**Comment by guomaoqiu** [comment]
hey this is my server views.py:

def get_host(request):
    order = request.GET.get('order','')
    offset = request.GET.get('offset','')
    limit = request.GET.get('limit','')
    data_len = len(Hostinfo.objects.all())
    if order == "asc":
        host_list = Hostinfo.objects.order_by('id')[offset:limit]   
    else:
        host_list = Hostinfo.objects.order_by('-id')[offset:limit]   

plesea help me.....

**Comment by guomaoqiu** [comment]
this question same :https://zhidao.baidu.com/question/1239730111086540619.html

**Comment by wenzhixin** [comment]
应该是你后台返回的数据不对，用 network 调试下。
