### ISSUE TITLE
分页可以加一个指定跳转的input框吗

### ISSUE THREAD

**Issue by hct7511** [wenzhixin/bootstrap-table#3086]
如题。。

**Comment by martinburch** [comment]
Would you please translate this question into English?

Google Translate didn't help me understand what you want, sorry. 😬

**Comment by hct7511** [comment]
Could you add a input box with the specified jump to page number?

**Comment by martinburch** [comment]
@hct7511 yes, we have an example for that! 😃 
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/selectPage-prevPage-nextPage.html

**Comment by hct7511** [comment]
Yes,I see.Thank you very much!
