### ISSUE TITLE
server still recieves "limit=10" when using client side pagination

### ISSUE THREAD

**Issue by bluewuxi** [wenzhixin/bootstrap-table#3087]
When I set using client side pagination ( url  as data source), it still send pagination information parameter "limit=10" to the server, so that I am not able to use the same web api to deal with requests of server side and client side pagination.

Possible solution: when client side pagination, do not include "limit" parameter or set limit=null or set limit=0;
.

**Comment by martinburch** [comment]
Try using `queryParams` to override this behavior.

Here's a HTML-only example where `data-query-params=""` (empty string):
http://jsfiddle.net/e3nk137y/13078/

Here's a more complex official example (under [Pagination, Client Side](http://bootstrap-table.wenzhixin.net.cn/examples/#pagination)):
http://jsfiddle.net/wenyi/e3nk137y/42/
