### ISSUE TITLE
add jQuery as dependency and require it

### ISSUE THREAD

**Issue by mickmcgrath13** [wenzhixin/bootstrap-table#3088]
Bootstrap table is a jQuery plugin and should have a proper dependency on jQuery specified and used.

*1)* Add something like this to the [package.json](https://github.com/wenzhixin/bootstrap-table/blob/develop/package.json)
```
"dependencies": {
	"jquery": ">=1.9.0 <1.12.0 || >=2.1.0 <2.3.0"
},
```
(..should be a range of jQuery versions so apps can use their own version with less likelihood of collisions)

*2)* There should be a `var jQuery = require('jquery')` or `import jQuery from 'jquery';` instead of relying on  window.jQuery.  Something like this:
```js
var jQuery = require('jquery');
!function ($) {
}(jQuery);
```

This could either go in the [main file](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L6) or be provided via a new file like `bootstrap-table-require.js` or similar.

**Comment by wenzhixin** [comment]
I think bootstrap-table is just a JavaScript plug-in for bootstrap. The jQuery version has been checked at https://github.com/twbs/bootstrap/blob/master/dist/js/bootstrap.js so it's not necessary to add here. Thanks for your advice!
