### ISSUE TITLE
is there a demo about bootstrap-table  onLoadError ?

### ISSUE THREAD

**Issue by 15838028035** [wenzhixin/bootstrap-table#3089]
is there a demo about bootstrap-table  onLoadError ?

from web i see  some codes like this 
onLoadError: function (data) {
             		$('#tableList').bootstrapTable('removeAll');
             	},

Is there a good msg to show  tell about the onLoadError   function, what should i do ?

**Comment by liujie15838028035** [comment]
@djhvscf  Is there a good msg to show tell about the onLoadError function, what should i do ?

**Comment by djhvscf** [comment]
I'm not sure what you're asking, do you mean if there is any good message when the plugin executes the loadError event?

**Comment by liujie15838028035** [comment]
@djhvscf   , Yes  ,  When the bootstrap-table  load error from a url,

i want to show message in the bootstrap-table,

onLoadError: function (data) {
  //error msg in  bootstrap-table
}

**Comment by djhvscf** [comment]
Yes,

You should use like

```js
onLoadError: function (data) {
//error msg in bootstrap-table
}
```

**Comment by charliehewis** [comment]
Can we get a better example of the use of this event please? It would be good to see what kind of infomration we will get from the parameters of the onLoadError, e.g. does the following make sense?:
$('#table').bootstrapTable({
            onLoadError: (status: string, err: JQueryXHR) => {
                console.error('LicenceTable - error loading data. Error: ' + err.status + ' - ' + err.responseText);
                ErrorMessageDialog(err);
            })

When is the status parameter used instead of the err.status? Is it the same thing?

**Comment by wenzhixin** [comment]
@charliehewis Yes, it's the same.
