### ISSUE TITLE
Append doesn't work properly with server pagination

### ISSUE THREAD

**Issue by mrDoctorWho** [wenzhixin/bootstrap-table#3090]
Hi!

I'm using Firefox 52.0.2 on Linux. When I add an item to the table with "append" method, then remove with "remove" and append again, I'm unable to remove the row, as "getSelections" returns an empty array and the "check.bs.table" event is being called on an old row (old id).

Steps to reproduce:

1. Add a row to the table
2. Select the added row and delete it
3. Add another row
4. Repeat step 2
5. Done, you wouldn't be able to remove the selected row

[jsfiddle](http://jsfiddle.net/zb2vwwcz/6/)

Notes: I'm using BootstrapTable ver. 1.11.1 with server pagination, but without it all works perfectly.

**Comment by mrDoctorWho** [comment]
Using _insertRow_ instead of _append_ seem to solve this problem.

**Comment by UtechtDustin** [comment]
Fixed in the newest version (check with your jsfiddle).
