### ISSUE TITLE
When using group-by and detail-view there is an issue like after expanded a detailed row then after close the group this row  stay open

### ISSUE THREAD

**Issue by dvrnDB** [wenzhixin/bootstrap-table#3091]
When using group-by and detail-view extensions together there is an issue like after expanded a detailed row after close the group this row  stay open.

so to test this issue use **group-by** and **detail view** together. Expand any row. So then close group. You will see row detail.

like a fiddle here **http://jsfiddle.net/devranDB/byv2pk24/9/**

**Comment by UtechtDustin** [comment]
The group by extension will be merged/rewritten, this issue will be checked in #4413.
