### ISSUE TITLE
CDN url error

### ISSUE THREAD

**Issue by Zionus** [wenzhixin/bootstrap-table#3093]
on the page:
[getting started](http://bootstrap-table.wenzhixin.net.cn/zh-cn/getting-started/)

the CDN  URL provided can not be resolved,I suppose its wrong.

I was trying out a  demo,and get error in js statement:
 $('#table').bootstrapTable(),
saying: **$('*').bootstrapTable is not a function,**
I checked the jquery,bootstrap,bootstrap-table source,hence found the issue.
## 
here is my solution,
> > 	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.css" />

	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.js"</script>

someone please replace this CDN text,
this kind of issue is quite distrubing.

**Comment by djhvscf** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
Solved now, and in next version will solve the version bug.
#3404
