### ISSUE TITLE
Exclude TD from click-cell event

### ISSUE THREAD

**Issue by basementmedia2** [wenzhixin/bootstrap-table#3094]
Hi,

i've got a table that performs a click-cell event but i want the event not to be performed if the row "button_td" is clicked because in this row, several buttons are placed which perform other events.

```
$('[id^=notizen_table]').on('click-cell.bs.table', function (field, value, row, $element) {
	var data="notiz_id="+row.notiz_id;
	var url="ajax_load_notiz_content.php";
	alert ("TD clicked:"+value)
	if (value != "button_td"){
		$.getJSON(url,data,function(result){
			$.each(result, function(i, field){
				$('#pnummer').html(field.pnummer);
				$('#pname').html(field.pname);
				$('#ersteller').html(field.ersteller);
				$('#headline').html(field.headline);
				$('#inhalt').html(field.inhalt);
				$('#notiz_datum').html(field.datum);
			});
			$('#notiz').modal('show');
		});	
	} else {
		alert ("Button TD is clicked!");	
	}
});
```
the strange thing is that if the row "button_td" is clicked the first alert correctly puts out "TD clicked: button_td" but it seems that the following if  clause (if value != "button_td") doesn't recognize this because the second alert doesn't get fired.

Can anybody give me advice?

Best regards 
Daniel

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
