### ISSUE TITLE
Blur on search field destroys the table when using checkboxes 

### ISSUE THREAD

**Issue by vincentwinkel** [wenzhixin/bootstrap-table#3099]
This is a personal piece of code using checkboxes + search field.

When you click inside the search field and click again anywhere on the page, the table becomes ugly, because of checkboxes missing I guess.

This issue was obtained with v1.11.1, the same piece of code works perfectly with v1.11.0.

[jsfiddle](http://jsfiddle.net/e3nk137y/13136/)

**Comment by wenzhixin** [comment]
Fixed in develop branch: http://jsfiddle.net/wenyi/e3nk137y/18213/
