### ISSUE TITLE
need a callback event

### ISSUE THREAD

**Issue by apple5702** [wenzhixin/bootstrap-table#3103]
In the same page using load dynamic change of the bootstrap-table DOM element, you need to wait for the table to complete some other operation, there is no good solution. I used the HTML method to generate the bootstrap-table, seeking the help of the author

**Comment by djhvscf** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
I think you can use `onPostBody·(`post-body.bs.table`) event to do that.
