### ISSUE TITLE
DOM memory leak on "load" function

### ISSUE THREAD

**Issue by pwaivers** [wenzhixin/bootstrap-table#3105]
## DOM memory leak on bootstrapTable "load" function

After "load" is called on bootstrapTable, the old DOM elements are not dropped from memory.  As a result, the memory usage skyrockets after many different "load" calls.  This is happening on my Chrome browser Version 57.0 with boostrap-table.js version 1.11.0.

1) Open my JSFiddle below.
2) Open the Google Chrome Task Manager. [Shift + Esc]
3) Click the "load" button in JSFiddle 10 times. 
4) Watch the "Memory" in the Task Manager grow quickly and not drop back down.
5) [Extra Credit] Run the Timeline in Chrome's Developer Tools with "Memory" checked.  This will show the JS Heap being garbage collected correctly, while the DOM "Nodes" increase indefinitely. 

JSFiddle Link - https://jsfiddle.net/pwaivers/kd6p8zn9/

This is a major problem in a website I am working on right now. We refresh the data for the bootstrap table every 5 seconds, from an AJAX call.  When the new data is loaded, I want the old data to be completely gone.  After the webpage has been open for several hours, the page gets slow and eventually crashes from too much memory.

**Comment by pwaivers** [comment]
Here is a picture of the memory profile graph for automated version of the same JSFiddle code (so I don't need to click "load" 100 times).  The blue line is the JS Heap, being garbage collected correctly.  The green line is the DOM elements, and it is rising forever. 

![chart-mem](https://cloud.githubusercontent.com/assets/799438/25353455/40db2014-28fd-11e7-8a67-d1e8e9437ed1.jpg)

**Comment by rajlitalien** [comment]
I'm experiencing the same issue.  Was this problem resolved?  If yes, what steps should be taken?

**Comment by wenzhixin** [comment]
Please use pagination instead: https://jsfiddle.net/kd6p8zn9/1/
#3405

**Comment by pwaivers** [comment]
How does pagination fix the problem. Can you be more clear?
