### ISSUE TITLE
Server side pagination display issue

### ISSUE THREAD

**Issue by areeba88** [wenzhixin/bootstrap-table#3108]
> <table class="table order-list table-striped table-bordered table-hover "       
                        id="sampleTable"
                        data-toggle="table"
                        data-height="300"
                        data-search="true"
                        data-show-refresh="true"
                        data-toolbar="#toolbar"
                        data-show-pagination-switch="true"
                        data-pagination="true"
                        data-id-field="id"
                        data-page-list="[10, 25, 50, 100, ALL]"
                        data-show-footer="false"
                        data-side-pagination="server"
                        data-response-handler="responseHandler">
                     <thead>
                        <tr>
                            <th data-field="Action" data-checkbox="true">Action</th>
                            <th data-field="SNo" data-sortable="true">Sr. #</th>
                            <th data-field="UserName" data-sortable="true">Name</th>
                             <th data-field="UserId" data-sortable="true">User Id</th>
                           </tr>
                     </thead>
                                 <tbody>
                                         <tr>
                                               <td></td>
                                               <td>1</td>
                                                <td>Mr. Hawk Bill</td>
                                                 <td>bill_324</td> 
                                            </tr>
                                            <tr>
                                                  <td></td>
                                                   <td>2</td>
                                                   <td>Mr. Hayn Jo</td>
                                                    <td>usJo_54</td> 
                                            </tr>
                                            <tr>
                                                   <td></td>
                                                   <td>3</td>
                                                    <td>Mr. X Salazender</td>
                                                    <td>Xais99</td>
                                             </tr>
                                              <tr>
                                                     <td></td>
                                                      <td>4</td>
                                                      <td>Mr. Smith</td>
                                                      <td>smith_098</td> 
                                              </tr>
                                               <tr>
                                                     <td></td>
                                                     <td>1</td>
                                                     <td>Mr. Hawk Bill</td>
                                                     <td>bill_324</td> 
                                              </tr>
                                            <tr>
                                                    <td></td>
                                                    <td>2</td>
                                                    <td>Mr. Hayn Jo</td>
                                                     <td>usJo_54</td> 
                                            </tr>
                                            <tr>
                                                     <td></td>
                                                     <td>3</td>
                                                     <td>Mr. X Salazender</td>
                                                      <td>Xais99</td>
                                            </tr>
                                             <tr>
                                                      <td></td>
                                                       <td>4</td>
                                                       <td>Mr. Smith</td>
                                                       <td>smith_098</td> 
                                              </tr>
                                               <tr>
                                                      <td></td>
                                                      <td>1</td>
                                                      <td>Mr. Hawk Bill</td>
                                                      <td>bill_324</td> 
                                              </tr>
                                            <tr>
                                                     <td></td>
                                                     <td>2</td>
                                                     <td>Mr. Hayn Jo</td>
                                                     <td>usJo_54</td> 
                                              </tr>
                                               <tr>
                                                     <td></td>
                                                      <td>3</td>
                                                      <td>Mr. X Salazender</td>
                                                      <td>Xais99</td>
                                                </tr>
                                                 <tr>
                                                       <td></td>
                                                       <td>4</td>
                                                        <td>Mr. Smith</td>
                                                        <td>smith_098</td> 
                                                 </tr>
                                                 <tr>
                                                      <td></td>
                                                      <td>1</td>
                                                      <td>Mr. Hawk Bill</td>
                                                      <td>bill_324</td> 
                                                 </tr>
                                                 <tr>
                                                      <td></td>
                                                     <td>2</td>
                                                     <td>Mr. Hayn Jo</td>
                                                     <td>usJo_54</td> 
                                              </tr>
                                               <tr>
                                                      <td></td>
                                                      <td>3</td>
                                                      <td>Mr. X Salazender</td>
                                                      <td>Xais99</td>
                                               </tr>
                                               <tr>
                                                       <td></td>
                                                       <td>4</td>
                                                       <td>Mr. Smith</td>
                                                       <td>smith_098</td> 
                                                </tr>
                                                 <tr>
                                                      <td></td>
                                                      <td>1</td>
                                                      <td>Mr. Hawk Bill</td>
                                                      <td>bill_324</td> 
                                                </tr>
                                                <tr>
                                                     <td></td>
                                                     <td>2</td>
                                                     <td>Mr. Hayn Jo</td>
                                                     <td>usJo_54</td> 
                                              </tr>
                                               <tr>
                                                      <td></td>
                                                      <td>3</td>
                                                      <td>Mr. X Salazender</td>
                                                       <td>Xais99</td>
                                                </tr>
                                                 <tr>
                                                       <td></td>
                                                       <td>4</td>
                                                       <td>Mr. Smith</td>
                                                       <td>smith_098</td> 
                                                  </tr>
                                     </tbody>
                  </table>
Above is the sample table i am using in my code but when i give **data-side-pagination="server"**attribute in the table definition, the pagination bar is not display at bottom. Am i missing something?

Hoping for the assistance.

**Comment by gerardoprada** [comment]
It would be very helpful if you could include a JSFiddle with your code.

See [here](https://jsfiddle.net/wenyi/e3nk137y/11459/) for an example that includes server side pagination

**Comment by areeba88** [comment]
check [hear](https://jsfiddle.net/aar88/bm8ze3f2/) then i use the same code but still the pagination is not visible

**Comment by gerardoprada** [comment]
At the bottom of the table in that JSFiddle you provided, you should see this message 

> Showing 1 to 5 of 5 rows

This means that pagination is working. The reason why you're not seeing the "pagination bar" is because you have not set up the correct total number of table rows. Take a look at this function from you fiddle:

```
$(function() {
  $('#table').bootstrapTable('load', {
    total: 5,
    rows: data
  });
});
```

You are telling the table that you only have 5 rows of data when in reality you have more. So for example, if you have 20 rows of data, then the above function should say `total: 20`. Try updating the total number to the actual number of rows that you have. That should solve your issue.

**Comment by areeba88** [comment]
@gerardoprada  Check now the [fiddle ](https://jsfiddle.net/aar88/bm8ze3f2/1/) i am appending the data dynamically now, i don't know every time how many rows will be display in the table, Still the pagination toolbar is not visible.

**Comment by gerardoprada** [comment]
Regardless of how you add the data to the table, if you have your pagination set as `server-side`, your data will need to follow the required format. See [here](http://issues.wenzhixin.net.cn/examples/bootstrap_table/data) for an example. As with the previous fiddle, in the new one, when you click the `Add Data` button, I can see the message `Showing 1 to 0 of 0 rows` at the bottom of the table which tells me that the problem is still that the number of rows is not being specified. Since you don't know how many rows will be displayed, then a possible solution would be to count the rows whenever the `Add Data` button is pressed and use this to update the total number. Something like this:
```
var row_num = 0; // Update this value whenever data is added to the table
var data = [{
  "total": row_num,
  "rows": data
}]
```

**Comment by wujixialan** [comment]
分页怎么返回总页数呢

**Comment by wenzhixin** [comment]
@areeba88 you can set smartDisplay to false to show the pagination all the time.
@wujixialan 需要后台返回。
