### ISSUE TITLE
how to changed subtable styles with parent tr datas and move the collepse icon to last td.

### ISSUE THREAD

**Issue by xcondor** [wenzhixin/bootstrap-table#3109]
子表数据出来了，但是样式不能和父级保持一种状态
	
![timline 20170426160659](https://cloud.githubusercontent.com/assets/3349113/25424273/65e88b8c-2a9a-11e7-91b8-8643899e21cd.png)

我的目的是和父级的tr是在同一级。展开的也不希望是在最前面，而是要放在最后面父级的操作里 。该如何解决这两个问题呢

**Comment by wenzhixin** [comment]
应该不支持
