### ISSUE TITLE
How to load data without names of fields

### ISSUE THREAD

**Issue by joefreire** [wenzhixin/bootstrap-table#3110]
I have a table that dynamically generates via PHP + MYSQL the names of the rows and columns are dynamic and I was wondering if you have how to use this data in the bootstrap-table

**Comment by wenzhixin** [comment]
What is your data format? Please provide an example.

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!
