### ISSUE TITLE
Printing a table

### ISSUE THREAD

**Issue by basementmedia2** [wenzhixin/bootstrap-table#3112]
Hi,

when i use the standard browser print button the table head is not aligned with the content rows.
Is there a possibillity to execute a restView on the table when printing?

Another try was to use the print extension but also this doesn't work ;-)

In my header i have included 

```
<script src="js/extensions/print/bootstrap-table-print.js"></script>
```

and in my table i included the line "data-show-print='true'"

```
<table 
                id="monatsuebersicht_table"
                data-toggle="table"
		data-show-print="true"
                data-toolbar="#toolbar_monatsuebersicht"
                data-height="100%"
                data-search="true">
                <thead>
```

But unfortunately the print button of the extension is not shown.

Can you give me help to get the table printed out correctly?
By the way: i don't know how to create jsfiddles ;-(

Best regards
Daniel

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by basementmedia2** [comment]
I close the issue because meanwhile i solved the problem. i changed the order of the attributes in the table tag and now it works.
