### ISSUE TITLE
Search problem

### ISSUE THREAD

**Issue by onlyShadow** [wenzhixin/bootstrap-table#3114]
when I input search paramter a at 2 page,just like this 
[http://oaph9wwmm.bkt.clouddn.com/issue.gif](url)

please copy this gif address and paste Into browser ,thanks....

I can not stand up my poor english!!!!! fck!

**Comment by wenzhixin** [comment]
你自己自定义的搜索框没有实现 queryParams 吧，假如还有问题请提供 jsfiddle。
