### ISSUE TITLE
How to update database

### ISSUE THREAD

**Issue by flam3srock** [wenzhixin/bootstrap-table#3116]
Forgive my ignorance here, I'm new to ajax.

I have loaded information into the table by setting data-url="json.php". It would only work by setting            data-side-pagination="client". Works. Beautiful results. Now how do shuttle any changes back into the database after editing a cell?

Lets say I have a column:

                        {
                        title: 'Site Name',
                        field: 'site_name',
                        rowspan: 2,
                        align: 'center',
                        valign: 'middle',
                        sortable: true,
			editable: true,
                        footerFormatter: totalTextFormatter						
			}

Based on the main bootstrap-table example. I have edited the site name. What is the correct way to  update it? Is there a function inside bootstrap-table that can call another php file to POST it such as in a form? Lets say I already have post.php ready to accept parameters to update the row in mysql, how do I pass several parameters to this post file to update it?

-thanks kindly in advance,
flam3srock

**Comment by djhvscf** [comment]
@dabros can you help here?

**Comment by laughedelic** [comment]
Any updates/solutions?

**Comment by dabros** [comment]
@laughedelic @djhvscf 

Theres need to be a handler performing the server side update, using ajax is reccomended. Plenty of examples of this in issues and examples, i will refer to a post i made a while ago collating most of this

#1939 server-side update

also of possible interest:

#1814 Table Editable Extensions Question
#2978 [need examples] Battstrap-Table editable Plugin Write Back to the API/Database 
#1865 Custom input with editable
