### ISSUE TITLE
editable插件事件不生效

### ISSUE THREAD

**Issue by FreeceLian** [wenzhixin/bootstrap-table#3118]
table代码：
`<table id="params_table" data-classes="table table-no-bordered" data-toggle="table" data-toolbar="#toolbar" data-height="428">`
                            `<thead>`
                                `<tr>`
                                    `<th data-field="params_key" data-editable="true">Key</th>`
                                    `<th data-field="parmas_value" data-editable="true">Value</th>`
                                    `<th data-field="operate" data-events="operateEvents" data-formatter="operateFormatter"></th>`
                                `</tr>`
                           ` </thead>`
                            `<tbody>`
                                `<tr>`
                                    `<td>&nbsp;</td>`
                                    `<td>&nbsp;</td>`
                                    `<td>&nbsp;</td>`
                                `</tr>`
                            `</tbody>`
                        `</table>`

脚本：
`<script>`
      `var $paramsTable = $('#params_table');`
      `$(document).ready(function () {`
                `$paramsTable.bootstrapTable({`
                          `onEditableSave: function (field, row, oldValue, $el) {`
                                    `$paramsTable.bootstrapTable("resetView");`
                          `}`
            `});`
      `});`
`</script>`

**Comment by wenzhixin** [comment]
例子中：http://issues.wenzhixin.net.cn/bootstrap-table/ 是可以的，假如还有问题的话请提供下 [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports)。
