### ISSUE TITLE
It's possible to use with jqueryui sortable serialize()

### ISSUE THREAD

**Issue by pozzer1972** [wenzhixin/bootstrap-table#312]
I'm interesting in use bootstrap-table with sortable.serialize().

I found some problems. There a way to set the id of the tr ?

I need to set the id with the ids my records.

Maybe there's another way ?

Thank you for your help!

**Comment by wenzhixin** [comment]
There is an option: `uniqueId`: http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
