### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by HurricanGod** [wenzhixin/bootstrap-table#3121]
when I import the js file of bootstrap-table to my project, unfortunately, after running the project it threw as follows Exception: Uncaught TypeError: Cannot set property 'zh-CN' of undefined

![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by HurricanGod** [comment]
![Uploading 1.png…]()

**Comment by martinburch** [comment]
In addition to `bootstrap-table.js` you will also need `bootstrap-table-zh-CN.js` in your project

Check out http://bootstrap-table.wenzhixin.net.cn/documentation/#localizations ... especially the code examples below the table.

**Comment by Handsome-Beauty** [comment]
Could you tell me how to solve this problem?

**Comment by jimgit** [comment]
As @martinburch  stated - make sure you have the proper localization file - [See the getting started page](http://bootstrap-table.wenzhixin.net.cn/getting-started/)

To quickly test this,  include all 3 CDN files shown here:

![image](https://user-images.githubusercontent.com/1921941/43677171-25e84396-97c3-11e8-8250-11785dc86fc4.png)

**Comment by jimgit** [comment]
The files are located in the distribution folder - [you can see them here](https://github.com/wenzhixin/bootstrap-table/tree/develop/dist/locale)
