### ISSUE TITLE
How to refresh column title only ?

### ISSUE THREAD

**Issue by jy95** [wenzhixin/bootstrap-table#3126]
Hello,

Simple question (or feature request) : How to refresh columns title only ?
I have a web app where the interface can be translated to another language.
I have read this issue : https://github.com/wenzhixin/bootstrap-table/issues/233 and I find ugly to destroy() table only for changing the title ...

Thanks

PS: The "resetView" method may be working for this case but no more explanation about it about the param parameter

**Comment by djhvscf** [comment]
This is a new feature. Any **PR** is welcome

**Comment by jy95** [comment]
Currently, only the ugly way to directly manipulate the headers.
```js
// $table is whatever $("#tableId") , mapOldKeysToNewKeys is something like { "oldKey1": "newKey" }
function refreshBootstraptTableColumns($table, mapOldKeysToNewKeys) {
    $table.find('tr:first').find("th").filter("[data-field]").each(function(index) {
        // get its field
        let field = $(this).attr("data-field");
        // apply an new name for this field - else let it untouched
        if (mapOldKeysToNewKeys.hasOwnProperty(field)) {
            $($(this).find(".th-inner")[0]).text(mapOldKeysToNewKeys.field);
        }
    });
}
```

**Comment by djhvscf** [comment]
See this **PR** https://github.com/wenzhixin/bootstrap-table/pull/3132

**Comment by jy95** [comment]
Thanks for your work. (It looks very similar to my workaround function so I hope it didn't take you too much time to implement it) .

**Comment by djhvscf** [comment]
No, it didn't take me too much.. Your function was the base, so thank you
