### ISSUE TITLE
How to change the default style of input[name="btSelectItem"][type="checkbox"]?

### ISSUE THREAD

**Issue by chenhm01** [wenzhixin/bootstrap-table#3133]
我需要的情况是.psd稿对checkbox有样式要求，但框架中checkbox是用input[type="checkbox"]默认的样式，我尝试用formatter（）方法在该列插入span或div用来改变样式，但不成功，有没有可行的办法？

**Comment by chenhm01** [comment]
leave

**Comment by wenzhixin** [comment]
#383
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/383.html
