### ISSUE TITLE
为什么updateCell执行完会自动关闭子表

### ISSUE THREAD

**Issue by hugoren** [wenzhixin/bootstrap-table#3134]
执行完这条语句，原先展开的子表会关闭，照理解，只更换指定单元格的字段，不会关闭子表的。
$("#table").bootstrapTable('updateCell',{index: 0, field:'progress', value:Math.round(Math.random()*100)});

能否有别的方式，单元格自动刷新，但原来展开的子表不会关闭？

**Comment by wenzhixin** [comment]
现在对主表的操作都会导致子表关闭，因为重新渲染了。

**Comment by wenzhixin** [comment]
@UtechtDustin `updateCell` will collapse a detail view because we re-render the whole table, ref #1899. 

Consider it is the same problem with #3612, let's close this one.
