### ISSUE TITLE
How to refresh column title?

### ISSUE THREAD

**Issue by lazybonee** [wenzhixin/bootstrap-table#3135]
When I use javascript code like
 $('#table').bootstrapTable({
    columns: [{
        field: 'id',
        title: 'Item ID'
    }, {
        field: 'name',
        title: 'Item Name'
    }, {
        field: 'price',
        title: 'Item Price'
    }],
    data: [{
        id: 1,
        name: 'Item 1',
        price: '$1'
    }, {
        id: 2,
        name: 'Item 2',
        price: '$2'
    }]
});
mycode is $('#table').bootstrapTable({
    columns: columnValue
})

when value of columnValue refresh, the columns' title don't change?

**Comment by djhvscf** [comment]
If you want to change only the column title please see this **PR** https://github.com/wenzhixin/bootstrap-table/pull/3132 I hope it will be merged soon

**Comment by lazybonee** [comment]
Thank you for the hint,it helps.
