### ISSUE TITLE
How to use data-formatter in angular2?

### ISSUE THREAD

**Issue by Rameshvenkat** [wenzhixin/bootstrap-table#3136]
Hi I have used your bootstrap table in angular 2 and its working fine. But i would like to know how to make the click event bind in the data-formatter. Its throwing an error when an event click occurs. Below is my sample code.

`$('#tblCourseList').bootstrapTable({
                    columns: [{
                        field: 'color',
                        cellStyle: function formatColor(value, row, index) {
                            if (row.EventStatus == "Pass") {
                                return {
                                    css: {
                                        "background-color": "#5cb85c",
                                    }
                                };
                            }
                            else if (row.EventStatus == "Fail") {
                                return {
                                    css: {
                                        "background-color": "#d9534f",
                                    }
                                };
                            }
                            else {
                                return {
                                    css: {
                                        "background-color": "#f0ad4e",
                                    }
                                };
                            }
                        }
                    },
                    {
                        title: 'EmployeeId',
                        field: 'EmployeeId',
                        class: 'text-center',
                        formatter: self.formatEmployeeId
                    }, {
                        title: 'Name',
                        field: 'UserName',
                        class: 'text-center'
                    }, {
                        title: 'Base',
                        field: 'Base',
                        class: 'text-center'
                    }, {
                        title: 'Training',
                        field: 'TrainingProgramName',
                        class: 'text-center'

                    }, {
                        title: 'Seat',
                        field: 'Seat',
                        class: 'text-center'
                    }, {
                        title: 'Event Date',
                        field: 'EventDate',
                        class: 'text-center'
                    }, {
                        title: 'Event Name',
                        field: 'EventName',
                        class: 'text-center'
                    }, {
                        title: 'EventStatus',
                        field: 'EventStatus',
                        class: 'text-center',
                        formatter: function formatStatus(value, row, index) {
                            if (row.EventStatus == "Pass") {
                                return "<span class='label label-success'>" + row.EventStatus + "</span>";
                            }
                            else if (row.EventStatus == "Fail") {
                                return "<span class='label label-danger'>" + row.EventStatus + "</span>";
                            }
                            else {
                                return "<span class='label label-warning'>" + row.EventStatus + "</span>";

                            }
                        }
                    }, {
                        title: 'Training Status(TMS)',
                        field: 'TrainingCompletionInTMS',
                        class: 'text-center',
                        formatter: self.toggleCloseTP
                    }, {
                        title: 'Training Status(FOS)',
                        field: 'TrainingCompletionInFOS',
                        class: 'text-center',
                        // formatter: self.toggleCloseTP
                    }
                    ],
                    data: message.ResponseData
                });
                $(".loader").fadeOut("slow");
            }
            else {
                console.log('Failed');
                $(".loader").fadeOut("slow");

            }
        });
  
    clickable(EmpID, TrainingProgram_MasterPlanID, EventDate) {
        alert("heeeeeee");
        //return "<button type='button' class='btn btn-info btn-sm' data-toggle='modal' data-target='#modalTable'>Close TP</button>"
    }

    formatEmployeeId(value, row, index) {
        return "<a class='btn btn-primary btn-sm' (click)='clickable(1,2,3,)'>" + row.EmployeeId + "</a>"
    }

    toggleCloseTP(value, row, index) {
        if (row.TrainingProgramCompletionStatus == null) {
            return "<a href='/Course/ReportCompletion.aspx?CourseID=" + row.TrainingProgramId + "&UserIDs=" + row.UserId + "' target='_blank' role='button' class='btn btn-info btn-sm'>Close TP</a>"
        }`

Event does not bind with the formatter since its dynamically added. Please help me to resolve this asap.

**Comment by waincent** [comment]
@Rameshvenkat How you integration bootstrap table with angular 2? thank you

**Comment by wenzhixin** [comment]
```js
formatter: function () {
   ...
}
```
