### ISSUE TITLE
Unwanted characters in column title

### ISSUE THREAD

**Issue by NTrukhanovets** [wenzhixin/bootstrap-table#3137]
Unwanted characters in column title

```
html.push('<th' + sprintf(' title="%s"', column.titleTooltip),
    column.checkbox || column.radio ?
        sprintf(' class="bs-checkbox %s"', column['class'] || '') :
        class_,
    sprintf(' style="%s"', halign + style),
    sprintf(' rowspan="%s"', column.rowspan),
    sprintf(' colspan="%s"', column.colspan),
    sprintf(' data-field="%s"', column.field),
    '>');
```
Here at `src/bootstrap-table.js:806 (version: 1.11.1)` if `column.field` contains `">` it close `<th>` tag earlier that it should be and all text after it and real `">` will be visible in column title.

For example: if `column.field = 'Some "> text'` and `column.title = 'Some title'`, the column title we'll see will be ` text"> Some title`

Also you can find live example at [jsFiddle](http://jsfiddle.net/xpd0h4s8/5/)

**Comment by djhvscf** [comment]
This issue is solved in: https://github.com/djhvscf/bootstrap-table/commit/5d0cbcbaa7cc9ed6ff03e3e757cd45e14ae28296

Example: http://jsfiddle.net/djhvscf/xpd0h4s8/9/
