### ISSUE TITLE
如何使用配置ajaxOptions参数

### ISSUE THREAD

**Issue by lizongwen** [wenzhixin/bootstrap-table#3138]
如何使用配置ajaxOptions参数

**Comment by lakeoffaith** [comment]
@lizongwen
`
<table id="table"
               data-toggle="table"
               data-toolbar="#toolbar"
               data-height="460"
               data-side-pagination="server"
               data-pagination="true"
               data-ajax-options="t1"
               data-url="/examples/bootstrap_table/data">

in javascript 
<script type="text/javascript">
        var t1=function(){
            var data={};
            data.complete=function(){
                alert(12);
            }
            return data;
        }
    </script>
`

when the Ajax complete.the web will alert 12.

**Comment by keyeMyria** [comment]
+1

**Comment by wenzhixin** [comment]
#3483 有例子。
