### ISSUE TITLE
初始化页码时不显示active的问题

### ISSUE THREAD

**Issue by apcc4m** [wenzhixin/bootstrap-table#3139]
当有pageNumber参数时，会不显示页码active样式，

`                html.push('<li class="page-number' + (i == this.options.pageNumber ? ' active' : '') + '">',
                    '<a href="#">', i, '</a>',
                    '</li>');`

将改为===改为==可解决此问题

**Comment by wenzhixin** [comment]
应该是你设置的参数类型不对，应该是 Number
