### ISSUE TITLE
Cant get work rowStyle.

### ISSUE THREAD

**Issue by sunny222** [wenzhixin/bootstrap-table#314]
Hi, I'm trying to get work rowStyle but i can't success in any way. Actually I'm not able to give a color to any rows. 

I use: 

``` html
table id="events-table" data-toggle="table" data-pagination="true" data-page-size="20" data-search="true" data-show-toggle="true" data-url="objednavky.php" data-height="1167" data-row-style="rowStyle"
```

and 

``` js
function rowStyle(row, index) {
    return {
        classes: 'active'
    };
};
```

i tried every combination of rowStyle function which i found. But no one works at all. I tried update rowStyle function in bootstrap-table.js but still no success so i remove the changes.

**Comment by cindymarie** [comment]
Hi! I am having the same issue :(
I cannot view the said working solution here though.. T.T
