### ISSUE TITLE
单独设置 detailview class 问题

### ISSUE THREAD

**Issue by apchenjun** [wenzhixin/bootstrap-table#3145]
我主表设置了classes = table table-striped table-bordered table-advance table-hover
我单独设置detailview classes = table table-condensed table-hover
运行起来 detailview classes = table table-condensed table-hover table-striped
怎么后面跟了一个父表的样式名称
如何解决

**Comment by wenzhixin** [comment]
测试是正常的：http://jsfiddle.net/wenyi/e3nk137y/18139/
