### ISSUE TITLE
Problem with sum footer table

### ISSUE THREAD

**Issue by timeo211** [wenzhixin/bootstrap-table#3146]
Hello.

I'm sorry for my English (i'm from Poland). I need you help. I have footer on table bootsrtap and sum from row on table. My sum has a few decimal places. Data are from the sql database. I wish there were only two decimal places. Will you help me?
![przechwytywanie](https://cloud.githubusercontent.com/assets/26895581/26240112/2d5f7a12-3c80-11e7-83f3-becae84b624d.PNG)
`
function runningFormatter(value, row, index) {
    return index;
}

function totalTextFormatter(data) {
    return 'Total';
}

function totalFormatter(data) {
    return data.length;
}

function sumFormatter(data) {
    field = this.field;
    return data.reduce(function(sum, row) { 

        return sum + (+row[field]);

    }, 0);

}`

**Comment by djhvscf** [comment]
Let's try this: http://stackoverflow.com/a/1726662

**Comment by timeo211** [comment]
Hi.
I trying down method, but dosen't work
`function sumFormatter(data) {
    field = this.field;
    return data.reduce(function(sum, row) { 

        return round(sum + (+row[field]));

    }, 0);

}`

`var result=sum + (+row[field]);
return result.toFixed(2);`

**Comment by djhvscf** [comment]
Provide a fiddle please

**Comment by timeo211** [comment]
https://jsfiddle.net/t121kxoe/1/

**Comment by timeo211** [comment]
I update this fiddle

**Comment by djhvscf** [comment]
@timeo211 your fiddles are not working. Please provide a valid jsfiddle

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!
