### ISSUE TITLE
Unable to call events from custom column format

### ISSUE THREAD

**Issue by arthipesa** [wenzhixin/bootstrap-table#3147]
I have tried to using the custom formatted to display buttons on the first column, it worked well, but not the events, how exactly should we catch the event from the buttons? I have added event on the table

` function firstColumnFormatter (value, row, index){
      return [
            '<div class="row-actions visible" style="width:100%;">',
              '<div style="margin-bottom:10px;">',
                '<span style="font-weight:bold; text-decoration:underline;">',value,'</span>',
              '</div>',
              '<div class="btn-group btn btn-xs">',
                '<button class="btn btn-xs btn-success activate" aria-label="Activate ">Activate</button>',
                '<button class="btn btn-xs btn-warning edit" aria-label="Edit ">Edit</button>',
                '<button class="btn btn-xs btn-danger delete" aria-label="Delete ">Delete</button>',            
              '</div>',
        '</div>'
        ].join(''); 
    }`

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/e3nk137y/39/
