### ISSUE TITLE
onDblClickRow event not working on mobile device

### ISSUE THREAD

**Issue by hank123456** [wenzhixin/bootstrap-table#3149]
I have bootstrap-table and it has function on double click event. On my laptop it works fine, however on the mobile when I try double tap row nothing happens.

`$('#recordtable').bootstrapTable({
        dataType: "json",
        columns: [
        {
            field: 'time',
            title: 'time'
        },
        {
            field: 'record',
            searchable:true,
            title: 'record'
        }
        ],
        data:data,
        onDblClickRow:function(row, element){
            alert("DbClicked");
        },
        onClickRow:function(row, element){
            alert("Clicked")
        }
    });`

**Comment by bruceherrera** [comment]
I also have this issue.

**Comment by infomobi** [comment]
same here :-(

**Comment by wenzhixin** [comment]
Please use clickRow event instead:
https://stackoverflow.com/questions/27560653/jquery-on-double-click-event-dblclick-for-mobile
