### ISSUE TITLE
how to get all data by paginationed inserted

### ISSUE THREAD

**Issue by kpeng2016** [wenzhixin/bootstrap-table#3151]
I insert table data on front html page, it is more than 10 rows, and if I set 10 rows per page, than it will be more than 1 page, then I want to get all data, but it failed, it only get currentPage data(10 rows),
I use the method $table.bootstrapTable('getData',{useCurrentPage: false}), or ($table.bootstrapTable('getData',false), all is not working.
Is anyone can help me?
Thanks al lot

**Comment by wenzhixin** [comment]
Example: http://jsfiddle.net/wenyi/e3nk137y/18210/
If the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
