### ISSUE TITLE
Issue with Pagination button double clieck

### ISSUE THREAD

**Issue by nilanjan-dutta** [wenzhixin/bootstrap-table#3154]
When I double click on the pagination buttons, page reloads to home page.

I'm using Chrome Version 58.0.3029.110 (64-bit). 

Open the bootstrap table in a web page where it is client side pagination.
Double click on the page numbers.
My web app goes back to the home page.

I have hovered on the buttons, and I see my home page link in the browser hint (left-below). Is there something wrong in hooking up the table to the page. I use Angular 2 and TypeScript. 
I have obscured few details in the attached snapshot for confidentiality purpose.

![untitled](https://cloud.githubusercontent.com/assets/8955659/26405440/f1c664f2-40b2-11e7-9976-4bb223055de4.png)

**Comment by wenzhixin** [comment]
Fixed in #3095
