### ISSUE TITLE
Add more parameters on data-url

### ISSUE THREAD

**Issue by Ronen-dev** [wenzhixin/bootstrap-table#3157]
I'm using `data-url` to get data from my API, as well as `data-side-pagination="server"` for pagination.

So, currently, the parameters send to my API are : `?order=asc&offset=0&limit=10` (by defaut, at page 1).
Next to that, I have a form, with which I would like to add more params to `data-url` on submit :  `?order=asc&offset=0&limit=10&new_param_from_my_form=value`.

Is there an implemented way to do that ? 

Thank you.

**Comment by Ronen-dev** [comment]
I found the solution. I'm using `refresh` method :

    $table.bootstrapTable(
        'refresh',
        {
            query: {
	        foo: "bar"
	    }
       }
    );

**Comment by danielriveraayala** [comment]
How receive the var foo in php?

**Comment by Falseee** [comment]
Depends on the selected [method](https://bootstrap-table.com/docs/api/table-options/#method) `$_POST['foo'] or $_GET['foo']`.

**Comment by danielriveraayala** [comment]
I try send data to serve, i use method post but not work, i use zend framework but nothing

**Comment by Falseee** [comment]
Read the documentation of the zend framework. `$this->getRequest()->getPost('foo',null);`  should work.
If not, ask somewhere (maybe their have slack ?)

**Comment by danielriveraayala** [comment]
Ok, thanks!
