### ISSUE TITLE
"expandAllRows" and "expandRow" do not work when contained in $(document).ready

### ISSUE THREAD

**Issue by crindlisbacher** [wenzhixin/bootstrap-table#3158]
I'm really at a loss for what's going on here. I have a webpage that uses bootstrap-table, and I want all of the rows to be expanded once the webpage loads. So I included the following javascript code at the end of my html file:

			$(function() {
				$("#data_table").bootstrapTable("expandAllRows");
				console.log("document ready worked!2");
			});

The strange thing is that while the console error message is displayed (indicating that there's nothing wrong with the jquery code), the  bootstrap table function doesn't execute. I've tried this with `expandAllRows` and `expandRow`. I've tested this in Firefox and Microsoft Edge (both on Windows).

**Comment by martinburch** [comment]
The table is probably not ready when this code runs. Try listening for bootstrap-table's `onPostBody` event.

$('#data_table').on('post-body.bs.table', function (e, d) {
    console.log("table ready");
    $("#data_table").bootstrapTable("expandAllRows");
});

If you are creating the table using the `data-toggle` method, ensure the `<script src="bootstrap-table.min.js">` tag comes before your `expandAllRows` code.

**Comment by crindlisbacher** [comment]
@martinburch Thank you! It worked like a charm.
