### ISSUE TITLE
pageSize传值出错

### ISSUE THREAD

**Issue by jktantan** [wenzhixin/bootstrap-table#3162]
步骤：
1. 默认数据为空，默认pageSize 为10 ， 查询出来的数据为空。
2. 数据库增加数据，数据低于10条，使用“refresh"功能通过AJAX在后台查询数据。数据正常查询出来。
3. 删除数据，使得数据库数据为0，再使用”refresh"功能查询。
4. 数据库增加数据，再使用“refresh"功能，这时候找不出任务何数据，通过断点调试，发现pageSize为0。

**Comment by wenzhixin** [comment]
经过验证，没有出现你说的情况，请升级到最新的版本（develop）。
