### ISSUE TITLE
多个扩展的引入顺序导致Toolbar init时显示按钮有误

### ISSUE THREAD

**Issue by nubont** [wenzhixin/bootstrap-table#3163]
1. 如下，先引入filter-control， 再引入export
<script src="assets/bootstrap-table/src/extensions/filter-control/bootstrap-table-filter-control.js"></script>
<script src="assets/bootstrap-table/src/extensions/export/bootstrap-table-export.js"></script>

2.然后data-show-export="true"，此时如果filter-control在Toolbar上没有按钮， 就会导致export的按钮也显示不出来；

3.如果颠倒上面extension的引入顺序，即使filter-control在Toolbar上没有按钮，export的按钮也能显示出来；

4. 这是各个扩展在重写    BootstrapTable.prototype.initToolbar 时的逻辑有问题,
    是否用类似下面的逻辑就能不互相影响了？ 
        this.showToolbar = this.showToolbar?true:(this.options.showExport);

**Comment by wenzhixin** [comment]
已修复所有用到的 extensions：
https://jsfiddle.net/wenyi/e3nk137y/18167/
```
this.showToolbar = this.showToolbar || this.options.showExport;
```
