### ISSUE TITLE
easing with collapseRow and expandRow

### ISSUE THREAD

**Issue by tylerecouture** [wenzhixin/bootstrap-table#3168]
Is there a way to hook in to collapseRow and expandRow to make the detailed view ease in/out rather than just appear/disappear?  Thanks!

**Comment by djhvscf** [comment]
No, this feature is not supported at this moment. Any PR is welcome

**Comment by wenzhixin** [comment]
Animate with collapseRow and expandRow: http://jsfiddle.net/wenyi/e3nk137y/18137/
