### ISSUE TITLE
求助，行拖拽不管用啊! Help! reorder-table-rows not working!

### ISSUE THREAD

**Issue by Geolage** [wenzhixin/bootstrap-table#3169]
我已经用script标签引进了table-dnd和reorder-table-rows这两个插件，也在table标签里加了属性data-use-row-attr-func="true" data-reorderable-rows="true"，但为什么还是不能拖拽？是不是缺少初始化条件？求解！
I've already include plugins 'table-dnd' & 'reorder-table-rows', add another two attrs 'data-use-row-attr-func="true" ' &  ' data-reorderable-rows="true" ' to ' &lt table &gt ' as well. Why it still doesn't work?  Is there anything forgotten should be added to js file to initialise ? Coz I didn't put any code about reorder rows into js. Please help me as soon as possible. Thx a lot!

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
