### ISSUE TITLE
data-show-columns="true" not working

### ISSUE THREAD

**Issue by jackslova** [wenzhixin/bootstrap-table#3170]
hello ! when i use data-show-columns and i click on dropdown it show nothing.
how can i use toggle column on html data ? 
please help !
```
<table data-toggle='table' data-toolbar="#toolbox" data-search="true" data-show-toggle="true" data-show-columns="true">
	<thead>
	      <tr>
			<th>Id</th>
                       <th data-sortable="true">Title</th>
		       <th data-sortable="true">Post_status</th>
                       <th data-sortable="true">Post_author</th>
		       <th data-sortable="true">Post_order</th>
              </tr>
</thead>

```
![bandicam 2017-06-06 12-28-06-673](https://cloud.githubusercontent.com/assets/26815114/26814993/17ba703c-4abc-11e7-8863-86f2ae9968be.jpg)

thank for support

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
Provide an example an reopen this issue
