### ISSUE TITLE
tree-column第三方拓展现在可以用吗？有没有示例

### ISSUE THREAD

**Issue by mofeiwlj** [wenzhixin/bootstrap-table#3172]
看到拓展包中有 tree-column文件夹 但是官网上拓展中并没有显示这个拓展，目前这个拓展是能用的吗？有示例没有呢？之前想自己引入一个第三方插件展示树形结构但是发现需要在tr标签内添加可变的class，我尝试了下貌似使用js方法class的值不能用function return的方法返回变量值，而且貌似class给出的值会同时在tr 和 td标签内添加。

**Comment by hugoren** [comment]
解决了吗

**Comment by mofeiwlj** [comment]
@hugoren 没有呢

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/tree-column
是这个，因为是GitHub友友提供的PR，应该可以用，不过具体我也没有用过。你们可以自己查看文档或者代码。
