### ISSUE TITLE
[help needed] disable filter control when server search is going on

### ISSUE THREAD

**Issue by anujism** [wenzhixin/bootstrap-table#3173]
Is it possible to disable filter control (input/select/date) fields when server search is going on? Or may be when Loading is visible.

**Comment by djhvscf** [comment]
We already have this feature https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/filter-control#disablecontrolwhensearch

**Comment by anujism** [comment]
Thanks, Is there a data name for this. For eg. data-disable-control-when-search="true"

**Comment by djhvscf** [comment]
@anujism yes.. it is `data-disable-control-when-search="true"`

**Comment by anujism** [comment]
Thanks much.

**Comment by bobkov-evgeny** [comment]
Hello, i have a problem with this parameter. When data is loaded the inputs still disabled, can you please help me how to fix this issue? @djhvscf
