### ISSUE TITLE
pagination with python

### ISSUE THREAD

**Issue by mossonli** [wenzhixin/bootstrap-table#3174]
@wenzhixin @dabros I want to use it with my project but there was nothing i can get at the html side,
python view.py   
news_dict = {'rows': info_list, 'total': total}
'''
news_list = {"total": 85, "rows": [{"guideread": "\u8f6c\u571f", "status": 1, "id": 125, "pubtime": "2017-05-23 15:27:36", "title": "66\u7684\u4e13\u9898"}, {"guideread": "\u5bfc\u8bfb", "status": 2, "id": 124, "pubtime": null, "title": "20170503\u516c\u544a\u6d4b\u8bd5\u8df3\u8f6c"}, {"guideread": "20170503\u516c\u544a\u63a8\u9001\u6d4b\u8bd5\u5bfc\u8bfb", "status": 1, "id": 123, "pubtime": "2017-05-03 14:59:56", "title": "20170503\u516c\u544a\u63a8\u9001\u6d4b\u8bd5"}]}
'''
return render_template("operation_news_list.html",news_dict=json.dumps(news_dict,cls=CJsonEncoder))

html 
<table id="tb_departments"></table>
<script type="text/javascript">
$(function () {

    //1.初始化Table
    var oTable = new TableInit();
    oTable.Init();

    //2.初始化Button的点击事件
{#    var oButtonInit = new ButtonInit();#}
{#    oButtonInit.Init();#}

});
var TableInit = function () {
    var oTableInit = new Object();
    //初始化Table
    oTableInit.Init = function () {
        $('#tb_departments').bootstrapTable({
            url: '/get_news_list',         //请求后台的URL（*）
            method: 'get',                      //请求方式（*）
            toolbar: '#toolbar',                //工具按钮用哪个容器
            striped: true,                      //是否显示行间隔色
            cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
            pagination: true,                   //是否显示分页（*）
            sortable: false,                     //是否启用排序
            sortOrder: "asc",                   //排序方式
            queryParams: oTableInit.queryParams,//传递参数（*）
            responseHandler: oTableInit.responseHandler,
            sidePagination: "server",           //分页方式：client客户端分页，server服务端分页（*）
            pageNumber:1,                       //初始化加载第一页，默认第一页
            pageSize: 10,                       //每页的记录行数（*）
            pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
            search: true,                       //是否显示表格搜索，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
            strictSearch: true,
            showColumns: true,                  //是否显示所有的列
            showRefresh: true,                  //是否显示刷新按钮
            minimumCountColumns: 2,             //最少允许的列数
            clickToSelect: true,                //是否启用点击选中行
            height: 500,                        //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
            uniqueId: "ID",                     //每一行的唯一标识，一般为主键列
            showToggle:true,                    //是否显示详细视图和列表视图的切换按钮
            cardView: false,                    //是否显示详细视图
            detailView: false,                   //是否显示父子表
            columns:[
            {field:'id', title:'ID'},
            {field:'title', title:'标题'},
            {field:'guideread', title:'导读'},
            {field:'pubtime', title:'发布时间'},
            {field:'status', title:'状态'},
            {field:'', title:'操作'}
            ]
        });
    };

    //得到查询的参数
    oTableInit.queryParams = function (params) {
        var temp = {   //这里的键的名字和控制器的变量名必须一直，这边改动，控制器也需要改成一样的
            limit: params.limit,   //页面大小
            offset: params.offset,  //页码
            title: $("#search_title").val()
        };
        return temp;
    };
    oTableInit.responseHandler = function (res) {
        console.log(res)
        return {
            'rows':res.news_dict.rows,
            'total':res.news_dict.total
        }
    };
    return oTableInit;
};
</script>

finally i got nothing in the tables！
I need your help

**Comment by dabros** [comment]
@mossonli - really cant do much with this sorry

Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

Put python to the side at first, get a table working in a fiddle with the a js array or similar EXACTLY as its currently being output from your server

That will reveal issues, and a fiddle is what we need to be of any help

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
