### ISSUE TITLE
Issue in dragging column after scrolling horizontally 

### ISSUE THREAD

**Issue by anushkamahesh** [wenzhixin/bootstrap-table#3175]
Hi @wenzhixin,
This is relate to the issue #1314 which is closed at moment. It sort of fix the issue but the thing is as you can find in this [jsfiddel](http://jsfiddle.net/fhsqydu4/6/) example, if you scroll to right horizontally and try to grab a column after scrolling, that particular column is disappear. But when you start moving it, its appear. 

But if you try a column without scrolling, it works fine. It shows the column when you hold it and when you start dragging. 

See the clip below.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1327120/26911424-f0a241b2-4c2a-11e7-9cbc-73390332bdd6.gif)

Thank you.

**Comment by UtechtDustin** [comment]
Its an issue of plugin ([dragtable](https://github.com/akottr/dragtable)) which is used, the issue is known since 2015 and was sadly not fixed.
Buf ref of their bug: https://github.com/akottr/dragtable/issues/37

So we cant help here :-(
