### ISSUE TITLE
类NoticeEdit，类qiyeNoticeDelete绑定的noticeEvents没有触发，为什么啊？

### ISSUE THREAD

**Issue by littlePig-zzf** [wenzhixin/bootstrap-table#3176]
window.noticeEvents = {
    'click .NoticeEdit': function (e, value, row, index) {
        console.log(e);
        var urls = 'noticeLook.html?id='+row._id;
        window.location.href = pathname + urls;
    },
    'click .qiyeNoticeDelete': function (e, value, row, index) {
        var id = row._id;
        if (confirm("你确定要删除吗？")) {
            $.ajax({
                url: url + '/api/inform/delete',
                type: "post",
                data: {
                    id: id
                },
                cache: false,
                headers: {"Authorization": getStorage('c_token')},
                success: function (data) {
                    // console.log(data);
                    var urls = 'notice.html?id='+row._id;
                    window.location.href = pathname + urls;
                },
                error: function (data) {
                    console.log(data);
                }
            })
        }
    }
};
//维修企业站内通知
$('#qiyeNoticeTable').bootstrapTable({
    url: url+"/api/maintenaces/backend/list",
    type:'get',
    cache: false,
    responseHandler:GetresponseHandler,
    queryParams : getIndustryParams,
    ajaxOptions:{
        headers: { "authorization":  getStorage('c_token')}
    },
    columns: [
        {
            title: 'ID',
            field: 'Id',
            align: 'middle',
            formatter: IdFormatter
        },{
            field: 'name',
            title: '标题',
            align: 'middle'
        },{
            field: '',
            title: '发布对象'
        },{
            field: 'created',
            title: '创建时间',
            align: 'middle'
        },{
            field: '',
            title: '操作',
            align: 'middle',
            events: noticeEvents,
            formatter: qiyeNoticeFormatter
        }
    ]
}).on('load-error.bs.table', function(status, res) {
    tableAjaxError(res);
});

    function GetresponseHandler(res,rows) {
        console.log('------');
        console.log(res,rows);
        return res;
    }
function qiyeNoticeFormatter(value, row, index){
   return ['<a class="NoticeEdit" style="padding-right: 20px;">编辑</a>' +
        '<a class="qiyeNoticeDelete" href="javascript: void(0)">删除</a>'].join();
}

function getIndustryParams(params){
    Params(params);
    params['sort'] = 'desc';
    params['cate'] = 1;
    return params;
}

**Comment by wenzhixin** [comment]
Close this issue, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
假如还有问题提供下 jsffidle，因为是在不知道怎么帮你。
