### ISSUE TITLE
There may be a bug 

### ISSUE THREAD

**Issue by xixily** [wenzhixin/bootstrap-table#3187]
There may be a bug that when i used fixed column and scrolling to bottom you will find out the row spacing will more and more lager。

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
