### ISSUE TITLE
onCheck时间循环触发问题

### ISSUE THREAD

**Issue by sysecho** [wenzhixin/bootstrap-table#3188]
你好：
    我在使用onCheck事件选中其他行时同时会触发其它行触发该事件导致死循环，请问有什么方式可以避免此类情况？谢谢！

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!
