### ISSUE TITLE
Custom Search

### ISSUE THREAD

**Issue by ondino4ka** [wenzhixin/bootstrap-table#3193]
I need to implement a search between two dates. Here is my example
It's bad that it removes all the data in contrast to the standard search, how can you solve this problem?

`$table.bootstrapTable('load', $.grep(data, function (row) {                
                var myDate1 = new Date(parseInt(row.Дата_выполнения.substr(6)))
                if (myDate1 >= date1 && date2 >= myDate1) {
                    return row.Дата_выполнения
                }
            }));`

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
