### ISSUE TITLE
Infinity dragging of selected column 

### ISSUE THREAD

**Issue by anushkamahesh** [wenzhixin/bootstrap-table#3196]
Hi Guys,
This is also one critical thing found on scrolling tables. You can tested it out this [jsfiddle](http://jsfiddle.net/fhsqydu4/6/). It is going and keep going even though table ended. I thing because of this issue, it creates a obstacle to put a column in to the last column via dragging.
Refer the clip below.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1327120/27047134-94d0ef12-4fc4-11e7-960b-e77442d5b5a8.gif)

**Comment by UtechtDustin** [comment]
duplicate of #3175
