### ISSUE TITLE
issue when using data-formatter and boostrap tooltip

### ISSUE THREAD

**Issue by luischen** [wenzhixin/bootstrap-table#3198]
I use bootstrap tooltip to format specific column so that I can get a popup when hover on it.

Problem now is when I triggered search function or column filter function , the tooltip formatter will lose and I have no hook to init tooltip(step 3) after search or filter done.

Could you give any suggestion on this kind of case like two-step-format?
Sorry for not providing a jsFiddle example. I will try to make one if necessary

My steps:
1, config the table column as
   `<th data-field="name" data-formatter="equipNameFormatter">Equip Name</th>`
2, define the function equipNameFormatter
  ```
function equipNameFormatter(value, row){
	  var titleToShow = "<label>品牌：</label>"+wrapString(row.brand,20)+"<br/>";
	  titleToShow += "<label>规格：</label>"+wrapString(row.model,20)+"<br/>";
	  titleToShow += "<label>预估数量：</label>"+wrapString(row.quantity,20)+"<br/>";
	  titleToShow += "<label>单价：</label>"+wrapString(row.singleCost,20)+"<br/>";
	  titleToShow += "<label>使用描述：</label>"+wrapString(row.performance,20)+"<br/>";
	  titleToShow += "<label>供应商：</label>"+wrapString(row.provider,20)+"<br/>";
	  titleToShow += "<label>货期：</label>"+wrapString(row.deliverTime,20)+"<br/>";
	  
	  var returnHtml = '<a href="#" data-toggle="tooltip" data-placement="bottom" data-trigger="hover" data-html="true" data-title="'+titleToShow+'">'+value+'</a>';
	  return returnHtml;
  }
```
3 init tooltip after table load
```
$("#resourceEquipTable,#myEquipTable").on('load-success.bs.table',function(){
		  $("[data-toggle='tooltip']").tooltip();
	  });
```
Thanks a lot.

**Comment by djhvscf** [comment]
See this [fiddle](http://jsfiddle.net/djhvscf/8vgk5626/14/) and also please remember looking for the [issues opened](https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=tooltip)

**Comment by luischen** [comment]
thanks， it solved my problem.

**Comment by djhvscf** [comment]
@luischen it sounds good! 👍
