### ISSUE TITLE
When using the showColumns option, the last item should be disabled.

### ISSUE THREAD

**Issue by fish-fly** [wenzhixin/bootstrap-table#32]

**Comment by Jithinsiva** [comment]
hi,  is there any option for "maximumCountColumns" like "minimumCountColumns".?

I want to set only 2 Columns for mobile view. is that possible ?

**Comment by wenzhixin** [comment]
@Jithinsiva you can use `data-card-visible` option: http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

**Comment by Jithinsiva** [comment]
@wenzhixin  Thanks a lot  for your reply :)

 But, I don't want Card-VIew on Mobile. I want to use detailView with 2 Columns on Mobile and Tablet view. 
  I got detailView with this code:

  $.extend($.fn.bootstrapTable.defaults, {
        mobileResponsive: false,
        minWidth: 562,
        minHeight: undefined,
        checkOnInit: true,
        toggled: false,
		minimunCountColumns: 2,
		detailView: checkDevice()
		
		
		 
    });
function checkDevice(){
  if ( $(window).width() < 650 ) {return true;
}
else{
return false;
}
}

Now, I want to remove
Can u help me? I'm not much familiar with Javascript

**Comment by wenzhixin** [comment]
What do you want to remove?

**Comment by Jithinsiva** [comment]
I want to keep only 1st  two Columns.  hide other Columns from mobile view.

**Comment by Jithinsiva** [comment]
![image](https://cloud.githubusercontent.com/assets/8907116/8331134/430d7882-1aa4-11e5-8b6c-0067fed34943.png)
 like this

**Comment by Jithinsiva** [comment]
![screen shot 2015-06-24 at 7 06 51 pm](https://cloud.githubusercontent.com/assets/8907116/8331159/65313a02-1aa4-11e5-8274-929e982ce2e9.png)
LIke this

**Comment by Jithinsiva** [comment]
@wenzhixin can u  help me on this?

**Comment by wenzhixin** [comment]
Please open a new issue.

**Comment by Jithinsiva** [comment]
ok
