### ISSUE TITLE
How to get column width onresize

### ISSUE THREAD

**Issue by skumarfaruk** [wenzhixin/bootstrap-table#3200]
Hi, 
please provide a example How to get particular column width onresizable

Thank you,

**Comment by djhvscf** [comment]
Do you mean in the resizable extension?

**Comment by skumarfaruk** [comment]
yes, i need width of column after resizing the column. Pleas help me.

**Comment by djhvscf** [comment]
Ok. If you see [here](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/resizable/bootstrap-table-resizable.js#L35) there is a function called `onResizableResize` where you can get the current width of the columns.


Use it like this:

``` js
onResizableResize: function (e) {
   var columns = $(e.currentTarget).find("th");
   var width = columns[0].width();
}
```

**Comment by skumarfaruk** [comment]
Thank u
But getting TypeError: e is undefined error in console. Please help me..

**Comment by djhvscf** [comment]
Please share us your code or an example

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
