### ISSUE TITLE
data-sort-name没有效果

### ISSUE THREAD

**Issue by xusheng1987** [wenzhixin/bootstrap-table#3204]
`<th data-field="loginName" data-sortable="true" data-sort-name="login_name">登录名</th>`

传递到后台的仍旧是loginName，而不是我要的login_name

**Comment by wenzhixin** [comment]
`sidePagination: 'client'` 时没有问题，`server` 的时候是个 bug。

**Comment by wenzhixin** [comment]
已修复：http://jsfiddle.net/wenyi/4r6g4cfu/878/
点击 Name 排序，实际上传到后台是 id。

**Comment by xusheng1987** [comment]
这个修复来的好晚

**Comment by wenzhixin** [comment]
其实可以用 queryParams 来处理，例如：
```
queryParams: function (params) {
    if (params.sort === 'loginName') {
        params.sort = 'login_name';
    }
    return params;
}
```
