### ISSUE TITLE
Export all makes table lose pagination

### ISSUE THREAD

**Issue by Giovanni-Enrico** [wenzhixin/bootstrap-table#3206]
Hi.

Im creating a report with custom filters, one of the inputs is a dateTimePicker that I had to change the format of the date that was showed. Before, I was altering the format inside $(document).ready(function(),
but I dont know why that was disabling the export all option, so I started to change the date format in 

`document.onreadystatechange = function () {

    // check the value - if it's 'interactive' then the DOM has loaded
    if (document.readyState === "interactive") {
//code here
}
}`

After that, everything appeared to be fine, but after I use Export All, two things happens:
1 - If I click on the options of export menu (Export All, Export Basic, Export Selected) or on the button that I made to refresh the table data-url , the export is activated one more time, but this time only Exporting the current page;
2 - After the second export, the table loses pagination and all the data is shown in one page.

Obs: If I reload the page, everything comes back to normal. The solution that I was thinking would be to reload the page after the Export event, but I couldn't find this event on documentation.

Any response would be appreciated.

**Comment by djhvscf** [comment]
I think it is a issue with the export extension. Can you provide an example?

**Comment by Giovanni-Enrico** [comment]
Sure, I'm sorry that I dont know how to create a Fiddle with all the js Imports with my owns, so I'll put my HTML and Js that I have made, hope this is sufficient for a analysis.

- HTML

`<html>

<head>


<link
	href="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/a549aa8780dbda16f6cff545aeabc3d71073911e/build/css/bootstrap-datetimepicker.css"
	rel="stylesheet" />

<link rel="stylesheet" type="text/css" href="relatorio.css">



<link rel="stylesheet" type="text/css"
	href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css"
	href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.css" />

</head>

<body>

	<script type="text/javascript"
		src="http://code.jquery.com/jquery-latest.min.js"></script>
	

	
	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
	<script src="bootstrap-datetimepicker.js"></script>


	
	<script type="text/javascript"
		src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script type="text/javascript"
		src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.js"></script>
	<script type="text/javascript"
		src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/extensions/filter-control/bootstrap-table-filter-control.js"></script>
	<script
		src="//rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js"></script>
	<script type="text/javascript"
		src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/extensions/export/bootstrap-table-export.js"></script>
	<script type="text/javascript"
		src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/extensions/toolbar/bootstrap-table-toolbar.js"></script>


	<script type="text/javascript" src="JS/consultaDadosRelatorio.js"></script>
	<script type="text/javascript" src="JS/Testes.js"></script>


	
	<div class="container" id="Filtros">
		<div class="row">
			<div class="col-sm-1"></div>
			<div class="col-sm-10">
				<form id="convFilter" class="form-horizontal">
					<div class="col-md-6">
						<div class="form-group">
							<label class="col-sm-4 control-label" for="PC_TB">Cód. PC
								TB</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" name="PCTB" id="PC_TB"
									placeholder="Código PC TB" spellcheck="false">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label" for="PC_IF">Cód. PC
								IF</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" name="PCIF" id="PC_IF"
									placeholder="Códido PC IF" spellcheck="false">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label" for="Componente">Componente</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" name="Componente"
									id="Componente" placeholder="Componente">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label" for="Retorno">Retorno</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" name="Retorno"
									id="Retorno" placeholder="Retorno">
							</div>
						</div>

					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="col-sm-4 control-label" for="dateInicio">Data
								Inicio</label>
							<div class="col-sm-8">
								<div class='input-group date' id='dateInicio'>
									<input type='text' class="form-control" value=""
										name="Dt_Inicio" id="dateInicio" /> <span
										class="input-group-addon"> <span
										class="glyphicon glyphicon-calendar"></span>
									</span>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label" for="dateFim">Data
								Fim</label>
							<div class="col-sm-8">
								<div class='input-group date' id='dateFim'>
									<input type='text' class="form-control" name="Dt_Fim" /> <span
										class="input-group-addon"> <span
										class="glyphicon glyphicon-calendar"></span>
									</span>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label" for="Comando">Comando</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" name="Comando"
									id="Comando" placeholder="Comando">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label" for="Status">Status</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" name="Status"
									id="Status" placeholder="Status" spellcheck="false">
							</div>
						</div>
						<div class="col-sm-offset-4 col-sm-8">
							

							<button class="btn btn-primary btn-md" type="button"
								id="testbutton" onclick="javascript:testano()">Filtrar</button>
						</div>
					</div>
			</div>
			
			<script type="text/javascript">
				$(function() {
					$("#dateInicio").on("dp.change", function(e) {
						$('#dateFim').data("DateTimePicker").minDate(e.date);
					});
					$("#dateFim").on(
							"dp.change",
							function(e) {
								$('#dateInicio').data("DateTimePicker")
										.maxDate(e.date);
							});
				});

				$(function() {
					$('#toolbar').find('select').change(function() {
						$('#table').bootstrapTable('refreshOptions', {
							exportDataType : $(this).val()
						});
					});
				})
			</script>

			</form>
		</div>
	</div>
	</div>


	<div class="container">
		
		<img class="img-responsive col-md-11" src="Logo-Relatorio.png" alt="">

		<div id="toolbar">
			<select class="form-control">
				<option hidden value="">Export Basic</option>
				<option value="all">Export All</option>
				<option hidden value="selected">Export Selected</option>
			</select>
		</div>
		
		<table id="table" data-toggle="table" data-height="600"
			data-show-toggle="false" data-show-columns="false"
			data-show-export="true" data-click-to-select="false"
			data-toolbar="#toolbar" data-pagination="true" data-search="false"
			data-detail-view="false" data-detail-formatter="detailFormatter"
			data-filter-control="false"
			data-url="http://localhost:8080/jboss-as-greeter/Relatorio">
			<thead>
				<tr>
					<th data-field="codtb" data-sortable="true"
						data-filter-control="select" data-visible="true">Cód. PC TB</th>
					<th data-field="codif" data-sortable="true"
						data-filter-control="input" data-visible="true">Cód. PC IF</th>
					<th data-field="componente" data-sortable="true"
						data-filter-control="select" data-visible="true">Componente</th>
					<th data-field="comando" data-sortable="true"
						data-filter-control="select" data-visible="true">Comando</th>
					<th data-field="retorno" data-sortable="true"
						data-filter-control="select" data-visible="true">Retorno</th>
					<th data-field="gerado" data-sortable="true"
						data-filter-control="select" data-visible="true">Gerado em</th>
					<th data-field="armazenado" data-sortable="true"
						data-filter-control="select" data-visible="true">Armazenado
						em</th>
					<th data-field="status" data-sortable="true"
						data-filter-control="select" data-visible="true">Status</th>
				</tr>
			</thead>
		</table>

		
	</div>

</body>
</html>`

 - consultaDadosRelatorio.js
`var inicio = new Date();
inicio.setHours(0, 0, 1);

var fim = new Date();
fim.setHours(23, 59, 59);

//$(document).ready(function() {
	
document.onreadystatechange = function () {

    // check the value - if it's 'interactive' then the DOM has loaded
    if (document.readyState === "interactive") {
    	$('#dateInicio').datetimepicker({
			format : 'DD/MM/YYYY  HH:mm:ss',
			date : inicio,                   //seta valor de hoje as 00:00:01
			useCurrent : false,
		});

		$('#dateFim').datetimepicker({
			format : 'DD/MM/YYYY  HH:mm:ss',
			date : fim,                      //seta valor de hoje as 23:59:59
			useCurrent : false
		// Important! See issue #1075
		});
		
		$('#dateFim').data("DateTimePicker").minDate(inicio);  //Delimita data Fim no load
		$('#dateInicio').data("DateTimePicker").maxDate(fim);  // Delimita data Inicio no load

		$("#dateInicio").on("dp.change", function(e) {           //ao selecionar data Inicio no picker, delimita Data Fim para ser maior que Inicio 
			$('#dateFim').data("DateTimePicker").minDate(e.date);
			
		});
		
		$("#dateFim").on("dp.change", function(e) {		            //ao selecionar data Fim no picker, delimita Data Inicio para ser menor que Fim 
			$('#dateInicio').data("DateTimePicker").maxDate(e.date);
		});

    }
}`

-Testes.js
`Number.prototype.padLeft = function(base, chr) { // função pra adicionar 0 em
	// numeros < 10
	var len = (String(base || 10).length - String(this).length) + 1;
	return len > 0 ? new Array(len).join(chr || '0') + this : this;
}

function formataData(data) { // função para formatar a data e horario
	var d = data, dformat = [ d.getDate().padLeft(),
			(d.getMonth() + 1).padLeft(), d.getFullYear() ].join('/')
			+ ' '
			+ [ d.getHours().padLeft(), d.getMinutes().padLeft(),
					d.getSeconds().padLeft() ].join(':');
	return dformat;
}

function testano() {

	var PCTB = document.getElementById("PC_TB").value;
	var PCIF = document.getElementById("PC_IF").value;
	var Componente = document.getElementById("Componente").value;
	var Retorno = document.getElementById("Retorno").value;
	var Comando = document.getElementById("Comando").value;
	var Status = document.getElementById("Status").value;
	var Dt_Inicio = formataData(new Date($("#dateInicio")
			.data("DateTimePicker").date()));
	var Dt_Fim = formataData(new Date($("#dateFim").data("DateTimePicker")
			.date()));
	
	
	var url1 = "http://localhost:8080/jboss-as-greeter/Relatorio";

	if (PCTB != null && PCTB.length != 0) { // tem que ser o primeiro devido
		// ao ? na url
		url1 += "?PCTB=" + PCTB;
	} else {
		url1 += "?PCTB=";
	}

	
	if (Dt_Inicio != null && Dt_Inicio.length != 0) { // Tem que arrumar o
		// filtro aqui de data
		url1 += "&Dt_Inicio=" + Dt_Inicio;
	} else {
		url1 += "&Dt_Inicio=";
	}

	if (Dt_Fim != null && Dt_Fim.length != 0) { // Tem que arrumar o filtro
		// aqui de data
		url1 += "&Dt_Fim=" + Dt_Fim;
	} else {
		url1 += "&Dt_Fim=";
	}

	if (PCIF != null && PCIF.length != 0) {
		url1 += "&PCIF=" + PCIF;
	} else {
		url1 += "&PCIF=";
	}

	if (Componente != null && Componente.length != 0) {

		url1 += "&Componente=" + Componente;
	} else {
		url1 += "&Componente=";

	}

	if (Retorno != null && Retorno.length != 0) {

		url1 += "&Retorno=" + Retorno;
	} else {
		url1 += "&Retorno=";

	}

	if (Comando != null && Comando.length != 0) {

		url1 += "&Comando=" + Comando;
	} else {
		url1 += "&Comando=";

	}

	if (Status != null && Status.length != 0) {

		url1 += "&Status=" + Status;
	} else {
		url1 += "&Status=";

	}

	/*
	 * String scheme = request.getScheme(); String serverName =
	 * request.getServerName(); int serverPort = request.getServerPort();
	 * //String contextPath = request.getContextPath(); // includes leading //
	 * forward slash
	 * 
	 * String resultPath = scheme + "://" + serverName + ":" + serverPort +
	 * "/jboss-as-greeter/Relatorio" aqui vai o Servlet + url; //PrintWriter
	 * out1 = response.getWriter(); //out1.print(resultPath);
	 * 
	 * request.setAttribute("resultPath", resultPath);
	 * 
	 * //System.out.println("Result path: " + resultPath);
	 * 
	 */


	$("#table").bootstrapTable("refresh", {   //Atualiza a url que a tabela vai dar o get no json
		url : url1
	});

}`


If I can help or provide anything more, let me know.

**Comment by Giovanni-Enrico** [comment]
Hi, is there a onExport event or something similar? I'm still having the same problem and I think that it would be easier to reload the page after the export, since this avoids the error to occur.

**Comment by Giovanni-Enrico** [comment]
Made it work, I created a button  with the following code `$('#export').click(function() { $('#table').bootstrapTable('togglePagination'); $('#tableID').tableExport({type:'excel'}); $('#table').bootstrapTable('togglePagination'); });`


Basically instead of using the export all from bootstrap-table, the button just disables pagination, exports the data, then enables pagination again.

Obs: Im using the  hhurz/tableExport.jquery.plugin to make this, so it was needed to do some imports.
