### ISSUE TITLE
Export to excel file too many rows cause browser crash

### ISSUE THREAD

**Issue by djhvscf** [wenzhixin/bootstrap-table#3209]

**Comment by martinburch** [comment]
How many rows? The old excel format (XLS) can't handle more than 65536 rows per sheet.

**Comment by djhvscf** [comment]
See https://github.com/wenzhixin/bootstrap-table/issues/2127

**Comment by nchimera** [comment]
Was this issue ever addressed?
Fails in Chrome but OK in IE and Firefox.

**Comment by wenzhixin** [comment]
If problem exists please issue to export repo, thanks.
