### ISSUE TITLE
border-radius

### ISSUE THREAD

**Issue by maxgrass** [wenzhixin/bootstrap-table#321]
Hello,

many folks use 'metro' designs. I was trying to expunge rounded corners from the table, but it's not just table elements, it's th:first-child, last-child and so on.

There should be a option to use borders with or without radius.

I see as a solution adding classes to elements, which need be rounded instead specifiying them in css.

```
x.bootstrapTable({
 roundedCorners: true
});

if (options.roundedCorners){
th.first.addClass('th-first-rounded');
...
}
```

- css is fixed, even if it's 'less' it's hard for the users to follow up maintainer's updates.
- js is flexible and this technique is used widely across other plugins.

table.border-radius: 0 !important; doesn't help

**Comment by wenzhixin** [comment]
Please use css to fix.
