### ISSUE TITLE
怎么指定单元格不可编辑

### ISSUE THREAD

**Issue by zddapi** [wenzhixin/bootstrap-table#3210]
怎么指定单元格不可编辑？

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by zddapi** [comment]
Column settings editable. How do I set the specified cell? Not editable

**Comment by djhvscf** [comment]
Use like: `data-sortable="false"`

**Comment by zddapi** [comment]
<thead>
				<tr>				
					<th data-editable="true">city</th>					
				</tr>
			</thead>
			<tbody>
				<tr>			
					<td data-sortable="false">beijing</td>				
				</tr>
                               <tr>			
					<td>beijing1</td>				
				</tr>
                       </tbody>
i want set beijing cell  no-editable? thanks

**Comment by djhvscf** [comment]
it is `data-editable="false"`

**Comment by zddapi** [comment]
<td data-sortable="false">beijing</td>   edit  <td data-editable="false">beijing</td>		
?it is  invalid. u coulde try ,td no is th  5555555555555

**Comment by zddapi** [comment]
th data-editable="true"
td data-sortable="false"
