### ISSUE TITLE
bootstrap-table-filter-control: when column field contains jquery selector keyword,function not work

### ISSUE THREAD

**Issue by sweetOranges** [wenzhixin/bootstrap-table#3211]
when column field contains jquery selector keyword,filter function can not work!

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by sweetOranges** [comment]
http://jsfiddle.net/e3nk137y/14184/


you can see this proplem by this link, column Name has something proplem.

**Comment by sweetOranges** [comment]
this proplem is caused by used jquery selector to initlize the head column. when column's field contains jquery selector keyword, jquery selector can not select it correct

**Comment by djhvscf** [comment]
This issue is solved in: https://github.com/djhvscf/bootstrap-table/commit/e901bf4edf57e83ebc88f0e71efddea1f8f0088e
Example: http://jsfiddle.net/djhvscf/e3nk137y/14204/
