### ISSUE TITLE
The same data-fileds make data-events not working in v1.11.1

### ISSUE THREAD

**Issue by vladimirgrezin** [wenzhixin/bootstrap-table#3212]
Hello

I'm using bootstrap-table in my project and I have just updated it from from v1.8.1 to v1.11.1. Unfortunately it broke some parts in my code. After some research I found out that in v1.11.1 using the same `data-field` attribute in differrent th tags leads to `data-events` not working. But it worked fine in v1.8.1. 

You may see the example in fiddle: http://jsfiddle.net/kpsrdc7a/1/

As you can see, actions in 1st table don't work, but actions in 2nd do.
The reason I want to use the same `data-fields` is that I want to use one `data-events` handler in different tables and I don't know which specific field from row I should currently use.

I read Change Log but I didn't find changes connected with it. So the question is: is it correct behaviour or not?

**Comment by djhvscf** [comment]
Yes, it is the correct behavior. We did that change in order to improve the performance of our plugin. Now we can't set the same the data-fields.
