### ISSUE TITLE
Reorder Columns not working on my table

### ISSUE THREAD

**Issue by xien89** [wenzhixin/bootstrap-table#3214]
I followed the steps for this extension which i found here:
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/reorder-columns

1. Added the bootstrap-table-reorder-columns plugin
2. Added dragtable
3. Added jquery v1.12
4. On my table, i used data-toggle="table" data-reorderable-columns="true"

But it still doesnt show up. Is there an important step that im missing out here?
Thanks

**Comment by djhvscf** [comment]
First: please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

Second: If you are folowing the steps as you mentioned they are incorrect. They should be:

1. Add jquery ui
2. Add dragtable
3. Add the bootstrap-table-reorder-columns plugin
4. On my table, i used data-toggle="table" data-reorderable-columns="true"

See this https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/reorder-columns#usage

**Comment by megadruck** [comment]
Hi

I still have the same prob

`<!DOCTYPE html>
<html>
<head>
    <title>xxxxxxxxxxxxx</title>
    <link rel="stylesheet" href="resources/bootstrap-table-develop/docs/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-table.css">
    <link rel="stylesheet" href="css/dragtable.css">

    <script src="js/jquery.min.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
    <script src="js/bootstrap-table.js"></script>
    <script src="js/bootstrap-table-export.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="js/bootstrap-table-reorder-columns.js"></script>
    <script src="js/jquery.dragtable.js"></script>
    <script src="js/bootstrap-table-cookie.js"></script>
</head>
<body>
<div class="container-fluid">
    <table id="table"
           data-toggle="table"
           data-show-toggle="true"
           data-search="true"
           data-show-refresh="true"
           data-show-columns="true"
           data-editable-emptytext="Leer"
           data-show-export="true"
           data-id-field="id"
           data-cookie="true"
           data-cookie-id-table="stanzform"
           data-page-list="[25, 50, 100, ALL]"
           data-show-footer="false"
           data-url="json.php"
           data-reorderable-columns="true"
           data-row-style="rowStyle">
        <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="kunde" data-sortable="true">Kunde</th>
            <th data-field="auftragsnr" data-sortable="true">AuftragsNr</th>
            <th data-field="beschreibung">Beschreibung</th>
            <th data-field="besonderheit">Besonderheit</th>
            <th data-field="bemerkung">Bemerkung</th>
            <th data-field="nutzen">Nutzen</th>
            <th data-field="groesse">Größe</th>
            <th data-field="wolfnr" data-sortable="true">WolfNr</th>
            <th data-field="schrank" data-sortable="true">Schrank</th>
            <th data-field="regal" data-sortable="true">Regal</th>
        </tr>
        </thead>
    </table>
</div>
<script>

    var $table = $('#table'),
        $remove = $('#remove'),
        selections = [];

    $table.bootstrapTable({height: getHeight()});


    // sometimes footer render error.
    setTimeout(function () {
        $table.bootstrapTable('resetView');
    }, 200);

    function rowStyle(row, index) {
        var classes = ['odd', 'even'];
        if (index % 2 === 0) {
            return {
                classes: classes[0]
            };
        }
        return {classes: classes[1]};
    }

    function getHeight() {
        return $(window).height() - $('h1').outerHeight(true);
    }

    $table.on('check.bs.table uncheck.bs.table ' +
        'check-all.bs.table uncheck-all.bs.table', function () {
        $remove.prop('disabled', !$table.bootstrapTable('getSelections').length);
        // save your data, here just save the current page
        selections = getIdSelections();
        // push or splice the selections if you want to save all data selections
    });
</script>
</body>
</html>


After first reorder it stopped in
/js/bootstrap-table-reorder-columns.js`

the error looks like

Uncaught TypeError: Cannot read property 'state' of undefined
    at Object.beforeStop (bootstrap-table-reorder-columns.js:145)
    at jquery.dragtable.js:154

**Comment by megadruck** [comment]
I use the one from
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/extensions/reorder-columns/bootstrap-table-reorder-columns.js

now it is working

**Comment by xien89** [comment]
Same for me, I used the cdnjs links and its working now

**Comment by Hung-Yang** [comment]
i use the version 1.11.1 without detail is fine, but when i add the data-detail-view="true" to the table is broken.
compiler show error on "z.visible" is null

that's my jsFiddle ,but when put on jsFiddle it couldn't be drag for column, in my PC is fine.
http://jsfiddle.net/wkr8yjv6/
