### ISSUE TITLE
Strange first row style happen in print preview 

### ISSUE THREAD

**Issue by huzifa-terkawi** [wenzhixin/bootstrap-table#3216]
Create a long table ( span multi pages ) , hit print preview and observe the first row starting from page 2
i am using IE9

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) or screenshots, thanks!
