### ISSUE TITLE
hideRow/showRow are slow

### ISSUE THREAD

**Issue by dberke711** [wenzhixin/bootstrap-table#3217]
I've implemented my own filtering for table data that gets the table data using the getData method, then iterates over the data calling  hideRow/showRow based on the filter criteria.

I've done some benchmarking and discovered that the hideRow and showRow methods are really slow - each row takes anywhere from 25 to 120ms to execute.  Needless to say, when working on a table of a couple hundred rows, this is painfully slow.

Is there a way to bulk update the rows more quickly?

**Comment by djhvscf** [comment]
This is an performance issue in initBody function so I think you can get updates from this https://github.com/wenzhixin/bootstrap-table/issues/3167

We are working on it
