### ISSUE TITLE
When the BT is a ajax and the browser is resized, the Sticky Header is not aligned

### ISSUE THREAD

**Issue by ywang0701** [wenzhixin/bootstrap-table#3220]
Steps to recreate:

1 Create a BT and host it on a IIS so the BT is availaable as http://www.....com/BT.htm
2 Create a ajax pointing to http://www....com/BT.htm
3. Display the BT.htm correctly
4. Change the width of the browser 
5. The Header and the table is not in the same alignment

![image](https://user-images.githubusercontent.com/7120555/27319929-bc2f068c-5548-11e7-95a3-44376563fb64.png)

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/faq
