### ISSUE TITLE
Table resizing after refresh

### ISSUE THREAD

**Issue by flightsurvey** [wenzhixin/bootstrap-table#3221]
I have a table that is defined

`$('#plannerAccountsTable').bootstrapTable({
        height: 320,
        search: true,
        showFooter: false,
        showRefresh: true, 
        sortable: false,
        toolbar: '#plannerAccountsToolbar',
        url: '<url>',
        columns: [
 etc`

On refresh the height of the table decreases.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
