### ISSUE TITLE
bootstrap-table-filter-control.js:202  Uncaught TypeError

### ISSUE THREAD

**Issue by Eletch** [wenzhixin/bootstrap-table#3225]
I only imported the file
`<script src="../../../vendor/filter-control/bootstrap-table-filter-control.js"></script>`
`<link rel="stylesheet" type="text/css" href="../../../vendor/filter-control/bootstrap-table-filter-control.css">
`
and did nothing. When I refresh the page, brower report the error
`Uncaught TypeError: Cannot read property 'created_at' of undefined`

here's my code 
`<table id="data_table"`
`            data-pagination="true"`
`	    data-page-size="15"`
`	    data-page-list="[15, 20, 50, 100, 200]"`
`	    data-toolbar="#toolbar"`
`	    data-show-columns = "true"`
`	    data-search="true"`
`           data-filter-control="true">`
`	<thead>`
`		<tr>`
`			<th data-field="created_at" data-sortable="true">日期</th>`
`			<th data-field="id" data-sortable="true">id</th>`
`			<th data-field="app_id" data-sortable="true">app id</th>`
`		</tr>`
`	</thead>`
`</table>`

thanks.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Eletch** [comment]
it can run in the jsFiddle, but not in my project
we decide not to use the filter in the front-end
thanks
