### ISSUE TITLE
当列数达到30列以上时，设置每个列的宽度，不起作用，整个表格都错位了

### ISSUE THREAD

**Issue by zzone** [wenzhixin/bootstrap-table#3228]
当列数达到30列以上时，设置每个列的宽度，不起作用，整个表格都错位了。每个列宽都很小，而且自己设置的列宽不起作用。如何能按照自己设置的列宽展示，并且超过屏幕的宽度可以有滚条。[](url)

**Comment by yanbo0039** [comment]
真的么 ？求贴图哇 如果真这样那不适合大型数据

**Comment by wenzhixin** [comment]
与 #3327 为同个问题，这个关闭。
