### ISSUE TITLE
Question: Is there a way to make columns available but not visible by default? 

### ISSUE THREAD

**Issue by gurumark** [wenzhixin/bootstrap-table#3233]
I would like to make a list of columns available not visible. Users should be able to pick and choose the they want to see by clicking the checkbox from the dropdown. Is there any way to do this?

**Comment by djhvscf** [comment]
Does the `showColumns = "true"` work for you?

**Comment by gurumark** [comment]
When I use data-show-columns="true" then it shows the column in the table. What I'm looking for is the ability to classify columns as 
** primary (will show in table load) and
** secondary( will not show but will be available in the dropdown in unchecked state)
The idea is to present users an option to enable /disable column "after" the table is displayed. Does it make sense?

**Comment by wenzhixin** [comment]
Example: http://jsfiddle.net/wenyi/e3nk137y/24/
