### ISSUE TITLE
can't remove the same line after once

### ISSUE THREAD

**Issue by Eastcloudsea** [wenzhixin/bootstrap-table#3234]
after insert more than 3 line , remove one line (such as line2),  the 2 lines remain. when next remove line 2 , it don't work.

my resolve : 
     this.$selectItem.off('click').on('click', function (event){
              .................
             //that.updateSelected();                   //remove this          
             //that.trigger(checked ? 'check' : 'uncheck', row, $this); remove this
         checked ? that.check($this.data('index')) : that.uncheck($this.data('index')); //add this
})
    BootstrapTable.prototype.check_ = function (checked, index) {
  replay   ----- this.data[index][this.header.stateField] = checked;
   as  ------  this.options.data[index][this.header.stateField] = checked;
})

now it work, pls help to check this solution

**Comment by djhvscf** [comment]
can you provide us a jsfiddle?

**Comment by Eastcloudsea** [comment]
a sample ////////////////
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
	<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link href="https://cdn.bootcss.com/bootstrap-table/1.11.1/bootstrap-table.min.css" rel="stylesheet">
	<script src="https://cdn.bootcss.com/bootstrap-table/1.11.1/bootstrap-table.min.js"></script>
	<title>ttt</title>
</head>
<body>
      <div class="fit-body">
        <table id="list"></table>
      </div>
      <button id="add">add</button><button id="del">del select</button>
      <script>
$(function(){
var i=1;
var contlistData=[{"id":"i","A":"i","B":"i"}];
    contlist=$('#list');
    varcolModels=[
    {field: "select",checkbox: true,width: 20,align: "center",valign: "middle"},
	{title: 'id',field: 'id', visible: false, align: 'center',valign: 'middle'},
    {title:"A",field: "A",halign:"center"},
    {title:"B",field: "B",halign:"center"},
    ];

    jqGridNEW2={height:300,
    	data:contlistData,
      url:"",
  uniqueId:"id",
  singleSelect: false,
  columns: varcolModels,
          classs: "table",
        dataField: "rows",
        striped:true,
        iconSize:"sm",
        //buttonsClass:"success",
        selectItemName:"select",
        totalField:"total",
        smartDisplay:true,
 
        pagination: true,
        pageSize: 10,
        pageList: [10, 20, 50,100],
        sidePagination: "server",
        contentType: "application/x-www-form-urlencoded",
        //dataType: "json",
        method: "post",
        //searchAlign: "left",
        //buttonsClass:"sm success",
        queryParamsType: "limit",
        clickToSelect:true,
        //singleSelect: true,
        showFooter:true,
        //searchOnEnterKey: true,
        //buttonsAlign: "center",
   
        showToggle:true,
        showColumns: true,

        showExport:true,
        cardView: false,
};
contlist.bootstrapTable(jqGridNEW2);

$("#add").click(function(){
contlist.bootstrapTable('append', {"id":i,"A":i,"B":i});

})
$("#del").click(function(){
      var ids = $.map(contlist.bootstrapTable('getSelections'), function (row) {return row.id;});
      $.each(ids,function(index,value){
        contlist.bootstrapTable('removeByUniqueId',value);
      });
    });




})


      </script>
	
</body>
</html>
///////////////////////////

**Comment by Eastcloudsea** [comment]
push add  twice and select no 2 and remove , select 2 agin ,remove , the problem show.

**Comment by Eastcloudsea** [comment]
I have the real reason the local insert ,in the local insert a row you must  reset the option sidePagination between  "server" to "client",   so that you could remove any rows
