### ISSUE TITLE
Add tabindex to div class="th-inner" so that th's are selectable when a user tabs and the user can sort when the tab is selected

### ISSUE THREAD

**Issue by gward35** [wenzhixin/bootstrap-table#3236]
This is an accessibility issue, in the current source code there is no way a user can tab (pressing tab key) to the th content and sort on enter press. 

To fix this issue for my project I added `tabindex="0"` to the `<div class="th-inner %s">` element that is getting pushed on like 816

that line now looks like `<div class="th-inner %s" tabindex="0">` and has remedied my issue

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

**Comment by wenzhixin** [comment]
#2719

**Comment by Falseee** [comment]
I close this issue because its older than 2 years, if you still need this feature.
Pls provide us an example to show that this feature makes sense.

**Comment by edmunds22** [comment]
FYI you can use rowFormatter() to add tabindex="0" to rows: https://examples.bootstrap-table.com/#options/row-attributes.html

It doesnt fix your exact issue - but it allows tabbing through rows/passing WCAG checks - if it could be expanded to allow for headers, or a headerFormatter() function to be added that would be great!
