### ISSUE TITLE
When using server mode, group by is reported wrong

### ISSUE THREAD

**Issue by wanghayo** [wenzhixin/bootstrap-table#3238]
`groupBy: true,
groupByField:  "pid",`

return ： :
[{id: "17", pid: "0", name: "11111", title: "主页", type: "1", status: "0", condition: ""},…]
0
:
{id: "17", pid: "0", name: "11111", title: "主页", type: "1", status: "0", condition: ""}
1
:
{id: "18", pid: "0", name: "1111122", title: "主页2", type: "1", status: "1", condition: ""}
2
:
{id: "19", pid: "17", name: "2222", title: "222", type: "1", status: "1", condition: ""}
3
:
{id: "20", pid: "18", name: "2222223", title: "22233", type: "1", status: "1", condition: ""}
4
:
{id: "21", pid: "17", name: "23123", title: "123", type: "1", status: "1", condition: ""}

Uncaught TypeError: Cannot read property 'forEach' of undefined
at e.BootstrapTable.initBody()

`groupBy: true,
groupByField:  "level",`
and  return:   rows
:
[{id: "17", pid: "0", name: "11111", title: "主页", type: "1", status: "0", condition: "",…},…]
0
:
{id: "17", pid: "0", name: "11111", title: "主页", type: "1", status: "0", condition: "",…}
condition
:
""
id
:
"17"
level
:
[{id: "19", pid: "17", name: "2222", title: "222", type: "1", status: "1", condition: "", level: []},…]
name
:
"11111"
pid
:
"0"
status
:
"0"
title
:
"主页"
type
:
"1"
Uncaught TypeError: Cannot read property 'forEach' of undefined
at e.BootstrapTable.initBody()

` console.log(tableGroups)
 tableGroups.forEach(function(item){`   
tableGroups=undefined

How should the JSON returned by the server handle packets?
Or, in server mode, how do I use a grouping plug-in?
What are the requirements for the returned data?

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wanghayo** [comment]
`$tables=$('#rule_table').bootstrapTable({
        // url: 'http://www.phptwo.com/Api/Rule/getGroupList',         //请求后台的URL（*）
        sortable: true,                    //是否启用排序
        sortOrder: "asc",                   //排序方式
        sortName:"id",                          //排序字段
        queryParamsType: 'undefined', // undefined
        queryParams: queryParams,           //请求服务数据时所传参数
        sidePagination: "server",           //分页方式：client客户端分页，server服务端分页（*）
        pageNumber:1,                       //初始化加载第一页，默认第一页
        pageSize: 10,                       //每页的记录行数（*）
        pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
        ajax:tableAjax,
        clickToSelect: false,                //是否启用点击选中行
        uniqueId: "id",                     //每一行的唯一标识，一般为主键列
        groupBy: true,
        groupByField:  "pid",
        detailView: false,                   //是否显示父子表
        paginationPreText:'上一页',
        paginationNextText:'下一页',
        selectItemName:'id',                //check字段名
        showExport: true,                     //是否显示导出
        exportDataType:$('#exportType').val(),              //basic', 'all', 'selected'.
        columns: [{
            title: "全选",
            width: 60,//宽度
            align: "center",//水平
            valign: "middle",//垂直
            checkbox: true
        },{
            field: 'id',
            title: 'ID',
            width: 80,//宽度
            align:'center',
            sortable: true
        },{
            field: 'pid',
            title: '上级',
            width: 150,//宽度
            align:'center',
        },{
            field: 'title',
            title: '权限名称',
            align:'center',
            width: 150,
            editable:{
                type: 'text',
                title: '权限名称',
                disabled:true,
                validate: function (v) {
                    if (!v) return '权限名称不能为空！';
                }
            }
        },{
            field: 'name',
            title: '权限规则',
            align:'center',
            editable:{
                type: 'text',
                title: '权限规则',
                disabled:true,
                validate: function (v) {
                    if (!v) return '权限规则不能为空！';
                }
            }
        },{
            field: 'status',
            title: '状态',
            align:'center',
            width: 100,
            editable: {
                type: 'select',
                title: '修改状态',
                disabled:true,
                source:[{value:"1",text:"启用"},{value:"0",text:"停用"}],
                validate: function (v) {
                    if (!v) return '必须设置';
                }
            },

        },{
            field: 'sss',
            title: '操作',
            width: 200,//宽度
            align:'center',
            formatter: function(value, row, index){
                return [
                    '<a class="btn btn-sm btn-info" href="javascript:void(0)" onClick="editRule('+row.id+')">修改</a>',
                    '<a class="btn btn-sm btn-danger" href="javascript:void(0)" onClick="deleteAll('+row.id+')">删除</a>'
                ]
            }
        }],
        onEditableSave:function (field, row, oldValue, $el) {
            $('#rule_table').bootstrapTable('resetView');//修改后过长的话打开此方法
            $.ajax({
                type: "post",
                async: true,
                dataType: "json",
                url: apiUrl+"/Rule/editRule",
                data: {id:row.id,pid:row.pid,title:row.title,name:row.name,status:row.status},
                error: function(error) {
                    toastr.error('服务器繁忙，请稍后再试！','服务器忙');
                    return false;
                },
                success: function (ret) {
                    if (ret.status) {
                        // $tables.bootstrapTable('refresh');
                        toastr.success(ret.msg,'成功提示');
                    }else{
                        toastr.error(ret.msg,'错误提示');
                    }
                },
            });
        },
        rowStyle: function (row, index) {
                var strclass = "";
                if (row.status == 0) {
                    strclass = 'status_false';
                }
                return { classes: strclass }
        },
    });
    function queryParams(params){
        return {
            pageSize : params.pageSize,
            pageIndex : params.pageNumber,
            sortName : params.sortName,
            sortOrder : params.sortOrder,
            title:$('#title').val(),
            status:$('#status').val(),
            pid:$('#searchPid').val()
        }
    }

    function tableAjax(params){
        var data=$.parseJSON(params.data); 
        $.ajax({
            url:  apiUrl+"/Rule/getRuleList",
            type: "POST",
            async: true,
            dataType: "json",
            data:data,
            error: function(error) {
                toastr.error('服务器繁忙，请稍后再试！','服务器忙');
                return false;
            },
            success: function(ret) {
                params.success({
                total: ret.total,
                rows: ret.rows
            });
            },
        })
    }`

**Comment by wenzhixin** [comment]
Close this issue, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
