### ISSUE TITLE
New load data and pagination

### ISSUE THREAD

**Issue by torisoft** [wenzhixin/bootstrap-table#3239]
Hi
I added a button in toolbar for show some custom data except initial loading data. But with server pagination after click on button and load data when go to second page load initial data with default load data.
how can fix that ? I want server pagination work for new loaded data.

**Comment by torisoft** [comment]
Nothing ?!!

**Comment by sebako86** [comment]
I have the same issue and looking into it at the moment. I have custom query like this:

`$('.aycl-filter').click(function(){
        ot.bootstrapTable('refresh', {
            silent: true,
            query: {
                status: $(this).data('status')
            }
        });
    });`

this sends data to myurl.com/getData?status=1&offset=0&limit=25
however when I click on page 2 it sends myurl.com/getData?offset=0&limit=25

without the status, so it's not kept where it was. 

I get all data back properly, including total count, just my custom query is missing from second request,

**Comment by wenzhixin** [comment]
@torisoft @sebako86 use `queryParams` to solve your problem:
```javascript
queryParams: function (params) {
    params. status = $('.aycl-filter.active').data('status')
}
```
