### ISSUE TITLE
data-field pass multiple values to data-formatter

### ISSUE THREAD

**Issue by nikmauro** [wenzhixin/bootstrap-table#324]
I have this suggestion for passing multiple values in data-formatter from data-field 

``` html
<table data-url="data1.json" data-height="299" data-click-to-select="true">
    <thead>
    <tr>
        <th data-field="state | id | price" data-checkbox="true" data-formatter="stateFormatter"></th>
        <th data-field="id" data-align="right">Item ID</th>
        <th data-field="name" data-align="center">Item Name</th>
        <th data-field="price" data-align="">Item Price</th>
    </tr>
    </thead>
</table>
<script>
    function stateFormatter(value, row, index) {
       console.log(value.state);
       console.log(value.id);
       console.log(value.price);
    }
</script>
```

**Comment by stcho** [comment]
I also need to pass in a parameter to the formatter and tried making a new row for it however now I have to display that data in my table. I tried hiding the data with the "data-visible" => "false" however whenever I refresh the page the column data flashes on the page for a second. How can I get it to not show up at all?

**Comment by jimgit** [comment]
Add a column for the parameter and get it per the row parameter - you don't have to use the data column as a table column.  Let's say you have  a parameter multiplier of 1.3  -[ you could try this - see JSFIDDLE](http://jsfiddle.net/jimkennelly/x7t6tpot/)
