### ISSUE TITLE
Each column's width is not working

### ISSUE THREAD

**Issue by zzone** [wenzhixin/bootstrap-table#3240]
When the number of columns to more than 30 columns, set the width of each column, does not work, the entire table are dislocation. Each column width is very small, and their own set of column width does not work. How can we set the width of the screen in accordance with their own, and beyond the width of the screen can have a roll.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by zzone** [comment]
function initTable1() {
	$('#table1')
		.bootstrapTable(
			{
				method: 'post',
				url: 'Wellhead/findBsTable',
				cache: false,
				contentType: 'application/x-www-form-urlencoded',
				height: window.bsTableHeight,
				striped: true,
				pagination: true,
				pageSize: 10,
				pageList: [10, 25, 50],
				minimumCountColumns: 2,
				toolbar: '#toolbar',
				clickToSelect: true,
				sidePagination: 'server',
				queryParams: searchParam,
				sortName: "monitorTime",
				sortOrder:"desc",
				onPostBody: function () {
					// initBsTableSelect();
				},
				onDblClickRow: function (row, $element) {
					editMethod(row.id);
				},
				columns: [
					{
						//width : 2,
						checkbox: true
					}, {
						field: 'id',
						visible: false
					}, {
						field: 'index',
						title: '序号',
						width: 50,
						align: 'center',
						valign: 'top',
						formatter: function(value, row, index) {
							var pageNumber = $('#table1').bootstrapTable('getOptions')['pageNumber'];
							var pageSize = $('#table1').bootstrapTable('getOptions')['pageSize'];
							return (pageNumber - 1) * pageSize + index + 1;
						}
					}, {
						field: 'hadError',
						title: '是否超标',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true,
						formatter: function (value) {
							if (!!value) {
								return "<span class='text-danger'>是</span>";
							} else {
								return "<span class='text-info'>否</span>";
							}
						}
					}, {
						field: 'hadSubmit',
						title: '是否上报',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true,
						formatter: function (value) {
							if (!!value) {
								return "<span class='text-info'>是</span>";
							} else {
								return "<span class='text-danger'>否</span>";
							}
						}
					}, {
						field: 'province',
						title: '省份',
						align: 'left',
						valign: 'top',
						sortable: true
					}, {
						field: 'city',
						title: '所属市',
						align: 'left',
						valign: 'top',
						sortable: true
					}, {
						field: 'county',
						title: '县（区）',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'village',
						title: '村庄名称',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'sectionName',
						title: '点位名称',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'lng',
						title: '经度',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'lat',
						title: '纬度',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'monitorTime',
						title: '监测时间',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true,
						formatter: function (value) {
							if (!!value) {
								return value.substr(0,10);
							} else {
								return "-";
							}
						}
					}, {
						field: 'population',
						title: '服务人口数量',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'ph',
						title: 'ph',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'totalHardness',
						title: '总硬度',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'sulfate',
						title: '硫酸盐',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'chloride',
						title: '氯化物',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'fe',
						title: '铁',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'mn',
						title: '锰',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'cu',
						title: '铜',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'zn',
						title: '锌',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'volatilePhenols',
						title: '挥发酚',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'las',
						title: '阴离子合成洗涤剂',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'permanganate',
						title: '高锰酸盐指数',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'nitrateN',
						title: '硝酸盐氮',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'nitriteN',
						title: '亚硝酸氮',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'nh3N',
						title: '氨氮',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'fluoride',
						title: '氟化物',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'cyanide',
						title: '氰化物',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'hg',
						title: '汞',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'arsenic',
						title: '砷',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'se',
						title: '硒',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'cd',
						title: '镉',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'cr6',
						title: '铬六价',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'pb',
						title: '铅',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'totalColiforms',
						title: '总大肠菌群',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'waterQualityClassification',
						title: '水质类别',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'featureMonitorName',
						title: '特征污染物监测项目名称（工业型村庄）',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'featureMonitorValue',
						title: '特征污染物监测数值（工业型村庄）',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}, {
						field: 'remark',
						title: '备注',
						align: 'left',
						valign: 'top',
						sortable: true,
						visible: true
					}]
			})
}

**Comment by HyramTang** [comment]
Like this http://jsfiddle.net/shamiao/mGR6J/9/,
I seted outside div width,then table's column width not work
