### ISSUE TITLE
help please  bootstrap-table-filter-control probleme select double entry?

### ISSUE THREAD

**Issue by tooline** [wenzhixin/bootstrap-table#3241]
The number of entries in the double select each time I select an entry !
```
$(document).ready(function(e) {
      $('#Table_List_Produit').bootstrapTable({
                      method: 'get',
                      cache: false,
                      url: '../include/server-response_produit.php',
                      striped: true,
                      pageSize: 10,
                      pageList: [10, 25, 50, 100, 200],
                      filterControl: true,
                      singleSelect: true
      });
    });

<table id="Table_List_Produit"
   data-height="800"
   data-mobile-responsive="true"
   data-side-pagination="server"
   data-show-export="true"
   data-show-toggle="true"
   data-pagination="true"
   data-search="true">
<thead>
<tr>
    <th data-field="name">Name</th>
    <th data-field="description" data-filter-control="select" data-visible="true">Description</th>
</tr>
</thead>
```
Images screen : 
https://i.stack.imgur.com/WCAlo.png
https://i.stack.imgur.com/IoL5O.png

**Comment by avsb93** [comment]
Same issue. The entry in the select list get added once if I hide the column from the data-show-column dropdown and the same gets added twice if I select the column again. Please fix this asap.

**Comment by TCS-Taylor** [comment]
This sounds like the same issue that has already been reported and confirmed here

https://github.com/wenzhixin/bootstrap-table/issues/2896

It's an issue with data-filter-control and data-height.

**Comment by dmiszkur** [comment]
Problem is with line:  206, because when you set height for table it doubles elements .bootstrap-table-filter-control-* for specific ID
`selectControl = $('.bootstrap-table-filter-control-' + escapeID(column.field))`

i add this to code and it works:
`var column = that.columns[$.fn.bootstrapTable.utils.getFieldIndex(that.columns, field)],
                selectControl = $('.bootstrap-table-filter-control-' + escapeID(column.field));
            if (selectControl.length > 1){
                selectControl = $('.bootstrap-table-filter-control-' + escapeID(column.field)).eq(1);
            }`

**Comment by avsb93** [comment]
@dmiszkur
 
Thank you for the fix. It's working for me too.

**Comment by avsb93** [comment]
@dmiszkur 

Thank you for the fix. It's working now.

**Comment by TCS-Taylor** [comment]
Worked for me too, thanks @dmiszkur !

**Comment by tooline** [comment]
thanks @dmiszkur !
