### ISSUE TITLE
initial checked rows cannot be populated with getSelections

### ISSUE THREAD

**Issue by happytk** [wenzhixin/bootstrap-table#3242]
I've setuped the bootstrap-table with html. it has a checkbox with initial data (space or something).
but initial checked rows cannot populate with getSelections.

please check below link and let me know what was wrong.
http://jsfiddle.net/gkzb4oe4/

thank you in advance.

**Comment by happytk** [comment]
Initial checked row has 'undefined'. the others have '' (empty string).
so I've writed the code like this, but it's temporary. I think the better way might exist.

`           
            var $table = $("#subcode-instances-table");
            var items = $table.bootstrapTable('getData');
            var htmls = $.map(items, function(row, i) {
                if (row.index || row.index === undefined) {
                    return '<input type="hidden" name="super_code_instance_ids-' + i + '" value="' + row.inst_value + '">';
                }
                else {
                    return '';
                }
            });
`

**Comment by Eastcloudsea** [comment]
I have the same problem on my app

**Comment by wenzhixin** [comment]
Fixed: http://jsfiddle.net/wenyi/gkzb4oe4/3/
