### ISSUE TITLE
The locale not working at all

### ISSUE THREAD

**Issue by paway** [wenzhixin/bootstrap-table#3244]
No matter what lang.js put after bootstrap-table.js. Do not work at all.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by paway** [comment]
please close. Finally, I figure it out - with dynamic check and import js files - forgot to import language file. please close this issue.
