### ISSUE TITLE
父子表的按钮显示问题

### ISSUE THREAD

**Issue by baaicangzai** [wenzhixin/bootstrap-table#3246]
父子表显示的 + 按钮  怎么隐藏
因为我已经做了点击行展开子表的事件 所以不需要显示+号
或者 这个+号的位置能否改变 居中等

**Comment by wenzhixin** [comment]
暂时不支持吧，只能修改代码。

**Comment by wenzhixin** [comment]
#4259 最新 develop 已支持该 feature
