### ISSUE TITLE
能在多列上定义事件吗？

### ISSUE THREAD

**Issue by dzlishen** [wenzhixin/bootstrap-table#3248]
在一行上定义Events事件可以执行，但是当在两列上定义事件后，后面一列的事件不执行。

Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by wenzhixin** [comment]
可以的。
假如还有问题可以提供jsfiddle
