### ISSUE TITLE
when we want to delete one row or many rows of the table ,the table`s method "remove" ask us that we must select on field which can only flag of row.now i have a issue ,may table has no flag like this .how could i delete one row of the table?

### ISSUE THREAD

**Issue by hollismaynell** [wenzhixin/bootstrap-table#3249]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by djhvscf** [comment]
Please provide an example of your issue with steps of reproduce

**Comment by djhvscf** [comment]
in
