### ISSUE TITLE
Not removing last row when refreshing table

### ISSUE THREAD

**Issue by ojwebtech** [wenzhixin/bootstrap-table#325]
Hi

My table is loading remote data via the data-url attribute.
I'm deleting rows via ajax and then refreshing the table using $('#table').bootstrapTable('refresh');
It all works perfectly until im deleting the last row in the table.
When I'm deleting that last row it won't disappear from the table.
The remote JSON data is of course empty.

Anybody seen the same issue?

**Comment by iamthestreets** [comment]
@ojwebtech do you mind providing the code you used to delete rows via ajax and then refreshing the table?

**Comment by larabirabert** [comment]
It's ok for me with the update 1.5.0 it's work fine ! thanks ... 
sorry
