### ISSUE TITLE
column resizing - Cannot read property 'defaults'

### ISSUE THREAD

**Issue by nixks** [wenzhixin/bootstrap-table#3251]
Hello,

I am trying to enable the plugin but I get the error

> Uncaught TypeError: Cannot read property 'defaults' of undefined
>     at bootstrap-table-resizable.min.js:7
>     at bootstrap-table-resizable.min.js:7

I have tried moving the script either to head or footer but still can't make it work. I do have included jquery, bootstrap, bootstrap-table.

The only thing worth mentioning is that I have the table loaded through ajax from an external file to my content page. Do the includes break by doing this?

**Comment by wenzhixin** [comment]
Please use the latest version: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/resizable.html
