### ISSUE TITLE
Field events not working with table having checkbox

### ISSUE THREAD

**Issue by arjha** [wenzhixin/bootstrap-table#3253]
Hi

I am trying to write a code where field is having an event with table, having checkbox. In this case event is not working . If I remove checkbox then it works fine. clickToSelect is false here. Please help.
![untitled](https://user-images.githubusercontent.com/30006582/27988031-09736976-63de-11e7-8b18-5e3863114466.png)

**Comment by wenzhixin** [comment]
There is no problem in example: http://issues.wenzhixin.net.cn/bootstrap-table/, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
