### ISSUE TITLE
How to make bootstrap-table ‘s width auto fit container width？

### ISSUE THREAD

**Issue by shangyue1110** [wenzhixin/bootstrap-table#3254]
I write a page, left side is a tree , bootstrap class is col-md-3,
right side is a grid used bootstrap-table which width is col-md-9,
I write code with examples in tutorial, but  it can not auto fit all container width,
somebody can help me?
![效果](https://shangyue1110.github.io/issueAssets/images/6706fd99-64a4-11e7-a66f-507b9d9b00b1.png)

here is demo on jsfiddle [(demo)](https://jsfiddle.net/shangyue1110/jL46o5sg/)

**Comment by wenzhixin** [comment]
You need to use `<table id="qg-mgr-dict-simple-grid" ></table>` instead of `<div id="qg-mgr-dict-simple-grid" ></div>`: https://jsfiddle.net/wenyi/jL46o5sg/4/
