### ISSUE TITLE
How can I make the 'showCloumns' drop down menu width extended automatically?

### ISSUE THREAD

**Issue by xiaya1986** [wenzhixin/bootstrap-table#3257]
When I add "data-show-columns" to the table, the columns filter selector will be displayed, but if the columns name text is a bit longer, the text will be wrapped, it's looks a bit strange. 

You can see the issue with following html,

```
<table data-toggle="table" data-show-columns='true'>
    <thead>
    <tr>
        <th>Name</th>
        <th>Stars</th>
        <th>Forks</th>
        <th>Description test test test test test test</th>
    </tr>
    </thead>
</table>
```

Currently my workaround is change the css add "width:300px"
.bootstrap-table .pull-right .dropdown-menu{right:0;left:auto;**_width:300px_**}

Is there any way to make it extended automatically?

**Comment by wenzhixin** [comment]
Yes, you can overwrite the default css define to solve the problem.
