### ISSUE TITLE
x-editable populate select by row data

### ISSUE THREAD

**Issue by h-labaste** [wenzhixin/bootstrap-table#3258]
Hi everyone,
   i did not succeed to create an "cascade" select, i tried too with "select2" but no more succeed

   In fact, i have one column who the list depend on another column, but i don't know how i can do this.
   Because on the boostrapTable({columns:[{editable: { sourceOptions: /**/}}]}). i never have the row/data or anything else.
    i try this way too : "sourceOptions : catSourceOptions"

var catSourceOptions = function() {
    //here it's always return "{cat1: ''}"
    return { cat1 : getValueByColName("cat1") };
}

function getValueByColName(colName)
    {
        //#myTable .success = "current row";
        // this work fine in console explorer or direct call
        var s = document.querySelector("#myTable .success");
        var r = document.querySelector("#myTable .success a[data-name='"+colName+"']");
        if(r == null || r == undefined)
            return "";
        return r.getAttribute("data-value");
    }

a little jsfiddle sample: https://jsfiddle.net/21102fqk/1/

So, Any ideas ?

**Comment by airtonjr** [comment]
@h-labaste 

I have this same problem and my solution is below:
```
{
                field: "city",
                title: "City",
                sortable: true,
editable: {
                    type: 'select',
                    sourceCache: false,
                    sourceError: 'Please, select a State',                                                 
                    source: function(){
                            var state = $(this).closest('tr').find("[data-name='state']:first").data("value");
                            return "loadDropdown.php?id_state="+state
                    }
                  
                } 
}
```

I am looking in the table for the field "state" and later and get the value for it and with the value a load the city. 💃

**Comment by h-labaste** [comment]
Thanks i will try this.

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
