### ISSUE TITLE
regarding to improve this tool to Tree grid - Any plans? :)

### ISSUE THREAD

**Issue by gunaseelanra** [wenzhixin/bootstrap-table#326]
Is it possible to make tree structure with bootstrap-table?

**Comment by ashishsober** [comment]
is there any trick for that to make a tree structure which u have shown above.

**Comment by pipiscrew** [comment]
I wrote it as http://www.pipiscrew.com/2015/01/php-year-expenses-organizer/

**Comment by ashishsober** [comment]
I m not able to open this page

**Comment by pipiscrew** [comment]
to add the records to an array where have a property 'is_head'

using the following code : 
```javascript
                    if ( jArray[no]["is_head"] == 1)
                        {r+="<td><strong>"+jArray[no]["category"]+"</strong></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>";
                        continue;
                        }
                    else
                    {
                        r+="<td><div style='margin-left:20px'>"+jArray[no]["category"]+"</div></td>";
                    }
```

looks like : 

![alt text](http://i.imgur.com/C8zPTf4.png "Shot")

**Comment by ashishsober** [comment]
call this function by data-formatter attribute.and if the values are coming from server side then.

**Comment by pipiscrew** [comment]
^true, I mix up with PHP not even used data-formatter I add it as table rows 
aka <tr><td>X</td></tr> then .bootstraptable "$('#expenses_tbl').bootstrapTable();"

as per server side request, for **children** - try to merge the 
```javascript
<div style='margin-left:20px'>FIELD_VALUE_HERE</div>
```
at the first column, should be alright(?)

**Comment by wenzhixin** [comment]
The same with #499, close this.
