### ISSUE TITLE
Load bootstrap-table with html content

### ISSUE THREAD

**Issue by AriPal** [wenzhixin/bootstrap-table#3261]
I have seen many examples where people have mostly been using the JSON datatype to populate the bootstrap-table. However, my case is a bit different, instead of JSON, I am using html content with ajax GET call, $("").html(content). The problem is that the table does not search or use pagination properly, and if I type something in the search-field, it the rows get removed and it says "No matching records found". 

Anyway, is there a way I can load the html data as argument for instance $table.bootstrapTable(data)? For those that are wondering why I am not using JSON, the content is a mix of html and php. 

Please look at this example and you will understand what I am trying to achieve, https://gist.github.com/AriPal/e8977abdff6d6bc2cbd478941afc3ace.

**Comment by djhvscf** [comment]
Did you review this example: http://jsfiddle.net/wenyi/e3nk137y/11/light/?
