### ISSUE TITLE
load method doesn't fire a load-success.bs.table event, no sense

### ISSUE THREAD

**Issue by yongdi** [wenzhixin/bootstrap-table#3262]
1. js1: $('table').on('load-success.bs.table', function () {...}
2. js2: $("table").bootstrapTable('load', data);

when I reload table I cannot do sth with load-success.bs.table event

**Comment by wenzhixin** [comment]
`load-success` event is fires when **remote** data is loaded successfully.
If you use `load` method you can use `post-body.bs.table` event.
