### ISSUE TITLE
Fixed Column : Header and Row not aligned

### ISSUE THREAD

**Issue by frans019** [wenzhixin/bootstrap-table#3263]
Hi Everyone,

My issue is when i used Fixed Column extension header have long text and row data is short header and row are misaligned. Here's my sample 

[http://jsfiddle.net/e3nk137y/14722/]()

**Comment by jonathangreco** [comment]
This is a concrete screen that showing the difference when we have 100 - 150 lines in the working table... at the end there is a superfuous empty line on the fixed table column.
![decalage](https://user-images.githubusercontent.com/1587180/29415402-41c7ba08-8363-11e7-8786-f71951a0c8af.png)

**Comment by jonathangreco** [comment]
@wenzhixin  This is a concrete screen that showing the difference when we have 100 - 150 lines in the working table... at the end there is a superfuous empty line on the fixed table column.
![decalage](https://user-images.githubusercontent.com/1587180/29415402-41c7ba08-8363-11e7-8786-f71951a0c8af.png)


Also notice that the horizontal scroll on the left side is quite hidden by the end of the column fixed table

**Comment by banda13** [comment]
I am having this issue too, is there any solution?

**Comment by wenzhixin** [comment]
Fixed in the latest version: v1.14.2
https://examples.bootstrap-table.com/#extensions/fixed-columns.html
