### ISSUE TITLE
selecting an option from filter-control in one column does not effect the contents of filter-controls in other columns

### ISSUE THREAD

**Issue by TCS-Taylor** [wenzhixin/bootstrap-table#3266]
This issue happens on all browsers I have tested (chrome, ff, IE).  After filtering one column, the other columns in the table still have the entire data set in their filters (as opposed to a filtered set of options).

Is there a way to cause the other data-filter-controls to have their options filtered after the table has been filtered?

Here you see my table unfiltered, and you can see the contents of the sub-model in the data-filter-control box
![step1](https://user-images.githubusercontent.com/30178491/28215260-f048a36e-6872-11e7-9428-6a534c872c50.png)

Here, I have filtered the Model column to a model type that we only have one computer of, but the sub-model data-filter-control (and all the other data-filter-controls for that matter) have the full unfiltered set of options.
![step2](https://user-images.githubusercontent.com/30178491/28215259-f03c4862-6872-11e7-8e95-c5c204b28651.png)

**Comment by TCS-Taylor** [comment]
Here is a fiddle I have created demonstrating this issue

https://jsfiddle.net/j5bs6tyL/1/

I should note, if you click "toggle" twice (to toggle in and out of of the toggle view) the submodel and other data-filter-controls DO display a filtered set of options.

**Comment by djhvscf** [comment]
This is not supported right now. Any PR is welcome

**Comment by UtechtDustin** [comment]
Feature exists in the newest version, to toggle it use the [hideUnusedSelectOptions](https://bootstrap-table.com/docs/extensions/filter-control/#hideunusedselectoptions) Option.
