### ISSUE TITLE
Expand detail auto collapse other rows

### ISSUE THREAD

**Issue by ientrytech** [wenzhixin/bootstrap-table#3270]
Is there an easy way to have a detail expanded row auto close when another row is expanded (like an accordion), that way, only one row is expanded at once. For example, if row 5 is already expanded then it will close when you click on another row to open it.

**Comment by ientrytech** [comment]
Figured out a solution. 

this.$body.find('> tr[data-index] > td > .detail-icon').off('click').on('click', function () {
....

var trs = that.$body.find('tr.detail-view');
            for (var i = 0; i < trs.length; i++) {
                $(trs[i]).prev().find('i').attr('class', sprintf('%s %s', that.options.iconsPrefix, that.options.icons.detailOpen));
                trs[i].remove();
            }
...
}

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/e3nk137y/18029/

**Comment by BobClaerhout** [comment]
For somebody bumping into this issue in combination with `data-detail-view-icon="false"`, you can also use the following code snippet:

```
onExpandRow: function (index, row, $detail) {
      $("#table")
        .find(".detail-view")
        .each(function () {
          if (!$(this).is($detail.parent())) {
            $(this).remove();
          }
        });
    }
```
It doesn't rely on the icon to be there
