### ISSUE TITLE
filter-control extension: duplicate select option with fixed header and client pagination

### ISSUE THREAD

**Issue by Syed-Ali** [wenzhixin/bootstrap-table#3271]
**Filter Control extension is duplicating select option with bootstrap option fixed header and client side pagination.**

First of all, thanks for the lovely tool.

OS: Windows 7
Browser: Chrome59, IE11

jsfiddle: https://jsfiddle.net/6te5qxy1/2/

Step1: go to fiddle
Step2: make sure that fiddle result view height is less, scroll it to bottom so that table head crosses the viewport and sticky header is got created.
Step3: go to page 2 (pagination) and back to page 1, do it two, three times.
Step4: dropdown any of select filter control to see the duplicate options.

However I found the problem and solved. 

    var sortSelectControl = function (selectControl) {
		selectControl = $(selectControl.get(selectControl.length - 1)); **// this line solved the problem :: cause selectControl varibale has 2 object, one is from sticky header table, second one is from body table**
            var $opts = selectControl.find('option:gt(0)');
            $opts.sort(function (a, b) {
                a = $(a).text().toLowerCase();
                b = $(b).text().toLowerCase();
                if ($.isNumeric(a) && $.isNumeric(b)) {
                    // Convert numerical values from string to float.
                    a = parseFloat(a);
                    b = parseFloat(b);
                }
                return a > b ? 1 : a < b ? -1 : 0;
            });
            selectControl.find('option:gt(0)').remove();
            selectControl.append($opts);
    };

**Comment by James8808** [comment]
Thank you so much!!  that works!

**Comment by djhvscf** [comment]
See this working: https://jsfiddle.net/6te5qxy1/6/
