### ISSUE TITLE
how do i change or custom my <tr>

### ISSUE THREAD

**Issue by JiangYinyuan12** [wenzhixin/bootstrap-table#3275]
i want customization `<tr>` now `<tr>` lable is `<tr data-index="1"></tr> `
how can i change it?

**Comment by y1170328179s** [comment]
but I Need a special line, showing a different style,      table option    rowStyle     For all columns    this problem how i solve???

**Comment by JiangYinyuan12** [comment]
i think there is no way otherwise we should change sources code

**Comment by y1170328179s** [comment]
Has tried to change the source code , but changing source code not pull request to github

**Comment by mlbaquerizo** [comment]
You should give an example of your code and what you want to accomplish with it. Not sure what you want exactly.

**Comment by y1170328179s** [comment]
@mlbaquerizo  https://github.com/y1170328179s/Bootstrap-table/blob/develop/2.jpg   we want this effect ,but source code fail to achieve this effect   https://github.com/y1170328179s/Bootstrap-table/blob/develop/3.jpg

**Comment by mlbaquerizo** [comment]
Would setting your table td's CSS to `word-break: break-all;` or `word-break: break-word;` do what you want?

**Comment by y1170328179s** [comment]
@mlbaquerizo https://github.com/y1170328179s/Bootstrap-table/blob/develop/4.jpg

**Comment by mlbaquerizo** [comment]
I think instead of rowStyle you are maybe looking for cellStyle
Look at the author's example [here](http://jsfiddle.net/e3nk137y/15007/)
Set data-cell-style="cellStyle" to the column you want styled and define your function cellStyle(value, row, index).

**Comment by y1170328179s** [comment]
column special property use javascript how i can add ?     data-cell-style="cellStyle"     this is html way  my meaning :   use javascript???

**Comment by y1170328179s** [comment]
http://bootstrap-table.wenzhixin.net.cn/documentation/    data-cell-style   property  can't set through javascript  ????   Would  we provide this way????

**Comment by mlbaquerizo** [comment]
[http://jsfiddle.net/jkv3qmzo/3/](http://jsfiddle.net/jkv3qmzo/3/)
I adapted the above to what I think you want to accomplish.

Are you initializing the columns in JS? look [here](http://jsfiddle.net/mtm9ahmg/)

**Comment by y1170328179s** [comment]
@mlbaquerizo   https://github.com/y1170328179s/Bootstrap-table/blob/develop/5.jpg

**Comment by mlbaquerizo** [comment]
Check out the second link from my previous comment. Just set cellStyle: cellStyle to the column

**Comment by y1170328179s** [comment]
thank you very much
