### ISSUE TITLE
导出按钮是否可以支持服务器端导出？

### ISSUE THREAD

**Issue by allen3371** [wenzhixin/bootstrap-table#3276]
用户按下导出按钮后，bootstrap-table将 导出的格式，以及导出条件等参数通过某种方式传送到后台，后台将数据处理好后，直接回传文件流，然后前端弹出文件保存框。

当然我可以直接定义一个按钮，但是我觉得集成在bootstrap-table中更好，不知道是否可以实现这个功能？

**Comment by ChenLaosan** [comment]
bootstrap-table是前端产品，后端的东西与这个项目没有直接关系吧。要想有这个功能还要自己实现。

**Comment by wenzhixin** [comment]
不知道你说的 服务器端导出指什么，假如是 `sidePagination: 'server'`，那答案是可以的。假如不是的话，就像 @ChenLaosan 所说的。
