### ISSUE TITLE
Init function for bootstrap table in Angular 4 component is not defined correctly!

### ISSUE THREAD

**Issue by t3min4l** [wenzhixin/bootstrap-table#3280]
I have used bootstrap table with resizable extensions to create a resizable table in my component but when I invoked $("#table).BootstrapTable(el,options) and also tested with $("#table).BootstrapTable(), the brower console logged "ERROR TypeError: jQuery(...).BootstrapTable is not a function". It makes me a lot of trouble such as when I route from the other component to the component I used bootstrap table, the table did not work correctly but when I reload this page, it worked!

I developed my app on Linux 14.04 x64 and the app ran on Google Chrome Version 56.0.2924.87 (64-bit)

What did I did wrong? How can I fixed it?

**Comment by wenzhixin** [comment]
Please use `bootstrapTable` instead, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
