### ISSUE TITLE
table header on left side in Bootstrap?

### ISSUE THREAD

**Issue by KiaraWang** [wenzhixin/bootstrap-table#3284]
How to have a table header on the left side instead of showing it on the top ?
The effect is as picture：
![image](https://user-images.githubusercontent.com/30337402/28454618-7f4ff7ae-6e2e-11e7-9a93-1b00157aa5dc.png)

now I want to achieve following goals.

- I hope the left table header is align with the right tbody ,when scrolling the bar.

- And the tbody data is not static data, i want get the data from the controller. 

can this achieve with bootstrap-table? with what environment?

the environment I use now : 
../bootstrap/2.3.1/css_${not empty cookie.theme.value ? cookie.theme.value : 'cerulean'}/bootstrap.min.css
../bootstrap/3.3.5/js/bootstrap.js
../bootstrap/2.3.1/awesome/font-awesome.min.css
../bootstrap-table/bootstrap-table.css
../bootstrap-table/bootstrap-table.js
../bootstrap-table/locale/bootstrap-table-zh-CN.js

**Comment by alexandnpu** [comment]
+1

**Comment by wenzhixin** [comment]
```
[
  {title: '', text: ''}
]
```
使用这样的格式，然后隐藏 header，再对第一个 td 设置 class 加粗就可以实现你想要的功能了。

**Comment by alexandnpu** [comment]
@wenzhixin ，感觉这种方法只是一个workaround，能不能原生支持一下啊？

**Comment by wenzhixin** [comment]
不支持哦，table 原生就不支持吧

**Comment by charbelabikhalil** [comment]
@wenzhixin hi, can you give an example how can we rotate a bootstrap table (landscape view) ? Thanks !

**Comment by wenzhixin** [comment]
A workground: https://live.bootstrap-table.com/code/wenzhixin/497
