### ISSUE TITLE
What if I would like to sort the data already loaded in the table?

### ISSUE THREAD

**Issue by ycymio** [wenzhixin/bootstrap-table#3286]
Question 1:
If I got the data from the backend and set the sidePagination "server", and need the simple sort of this page's data(not send a request to the server), what will I do?
I set the column sortable and it did't work.

Question 2:
I'd like the search when I set the sidePagination "client", but if I choose three rows and after searching, there are only two could be seen, but the function 'getData' still gets three, what will I do so that I could just get the rows which are visible and are chosen?

**Comment by yanbo0039** [comment]
Chinese Please?

**Comment by ycymio** [comment]
问题1：
如果我想从后台拿数据，由于数据量大，sidePagination设为server，但是这时候我设置sortable为true，功能并不执行，为什么？怎么使它按下列头，可以简单的对当前页已加载的数据排序？要通过后台排序也可以，那怎么实现，有参数传到后台？

问题2：
如果我将sidePagination设为client，假设选择3行，再用search功能搜索以后，原来选择的3行只有两行可见，那么我如何取得这两行，而不是原先的3行？因为getData功能尝试的结果还是取得原先的三行

**Comment by wenzhixin** [comment]
1. 排序是有参数传到后台的，可以看文档或者network。
2. 你要用 getSelections 方法。
