### ISSUE TITLE
problem in empty table.

### ISSUE THREAD

**Issue by clicx** [wenzhixin/bootstrap-table#3287]
.bootstrapTable('getData').length
value is 1, and getData return many data.

Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by mlbaquerizo** [comment]
You need to call .bootstrapTable('getData') on a table that has been initialized with .bootstrapTable()
For example I have an empty table `<table id="table"></table>`

If I try to use getData on this table before it is initialized as a bootstrapTable :
`$('#table").bootstrapTable('getData');`
This will just return the jQuery object as if I called `$('#table')` which has a length of 1

However if the table has been initialized with .bootstrapTable():
`$('#table").bootstrapTable().bootstrapTable('getData');`
I will get and empty array which has a length of 0.
