### ISSUE TITLE
2个bootstrapTable在一个页面的问题

### ISSUE THREAD

**Issue by killturinG** [wenzhixin/bootstrap-table#3288]
如果有一个页面里有2个bootstrapTable，field相同的情况下，filterControl的下拉菜单会出现2个field相加的情况

2个columns结构一样， 数据不一样
```
{
	field: 'date',
	title: '年份',
	filterControl: 'select',
	filterControlDefault: '2005'
}
```

都开启bootstrapTable的filterControl选项
![111](https://user-images.githubusercontent.com/2275756/28603736-8ba79d40-71f8-11e7-87f8-5bfdf7a87ca9.png)

只开启第一个bootstrapTable的filterControl选项
![a](https://user-images.githubusercontent.com/2275756/28603812-f9bc62de-71f8-11e7-829a-768cab532d32.png)

只开启第二个bootstrapTable的filterControl选项
![b](https://user-images.githubusercontent.com/2275756/28603814-fcc44686-71f8-11e7-8392-f92aa73b904c.png)

**Comment by wenzhixin** [comment]
最新的 develop 已经修复了这个问题，请验证下。
