### ISSUE TITLE
[help-wanted] table-filter-control causing browser to hang

### ISSUE THREAD

**Issue by zerox1212** [wenzhixin/bootstrap-table#3290]
I have a table that is using `bootstrap-table-export` and `bootstrap-table-filter-control`.

For some reason every time I click a "select" filter drop down the browser hangs before opening the filter. If I click the drop down again the same thing happens. Everytime the drop down opens 4x more items are displayed.
![image](https://user-images.githubusercontent.com/13090472/28649922-e376fb20-723d-11e7-8c9e-5f90be4d8bab.png)

I really want to use filters, but this extensions is really giving me trouble while most of the other ones work perfectly. Thanks.

**Comment by 44326334** [comment]
@djhvscf Please fixed thx!!!  https://github.com/wenzhixin/bootstrap-table/issues/3255#issue-241551104

**Comment by djhvscf** [comment]
See this working: https://jsfiddle.net/6te5qxy1/6/
