### ISSUE TITLE
There is a fine head and body dislocation

### ISSUE THREAD

**Issue by ytzyangting** [wenzhixin/bootstrap-table#3294]
表头与表体有细微错位

如图：

![2017-07-28 22_24_28-bootstrap table examples](https://user-images.githubusercontent.com/13487970/28721817-2c9878c2-73e4-11e7-88e0-6c6712079348.png)

**Comment by radiantone** [comment]
I also notice that if the value of a cell changes after the table is created, the header and body rows no longer line up correctly. Is there a visual refresh method to re-align the table when contents change?

**Comment by hensing** [comment]
running into the same problem here:
You can reproduce the dislocation by reducing the zoom-factor of your browser < 100%:

![image](https://user-images.githubusercontent.com/1055581/31014363-be6c5d74-a51a-11e7-94b1-cc1a35b013cd.png)

**Comment by hensing** [comment]
seems like the table-hover element has a fixed widtth and does not consider browser zooming:

![image](https://user-images.githubusercontent.com/1055581/31015039-40ae49a2-a51e-11e7-95a5-9d8469fa5c37.png)

**Comment by wenzhixin** [comment]
Please update to the latest version, this issue is fixed in the develop version.
