### ISSUE TITLE
filterby for multiple columns with "OR" condition

### ISSUE THREAD

**Issue by thomas-nguyen-3** [wenzhixin/bootstrap-table#3295]
I am looking at the filterby example here: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/filterBy.html

and wonder if i can apply the filterby code for multiple columns in this way:

example: from the above filterby link. I would like to find the (item Name = Item 1) or (Item Price = $1 or $2)

I understand that for the "And" condition: (item Name = Item 1) AND (Item Price = $1 or $2)

I will use 
$table.bootstrapTable('filterBy', { name: "Item 1", price: [$1, $2] });

But is there a way to do the above with "OR" condition:
 (item Name = Item 1) OR (Item Price = $1 or $2)

**Comment by mlbaquerizo** [comment]
I would like this as well. I can only think of:
```
//get array of all table data
var fullTableData = $table.bootstrapTable('getData');

//filter using javascript built in array filter function
var filters = fullTableData.filter(function(item){
    return (item.name == "Item 1" || item.price == 1 || item.price == 2)
});

// reload bootstrapTable with filtered array
$table.bootstrapTable('load', filters);
```
Then to unfilter you would need to reload with `fullTableData`:
```
$table.bootstrapTable('load', fulltableData);
```
Kind of a hack since you would need to store the complete data somewhere and then refilter any time you want to do another OR filter...

**Comment by Falseee** [comment]
Its already implemented/merged the reopening was a mistake i guess ? @djhvscf
