### ISSUE TITLE
bootstrap-table客户端方式导出数据问题

### ISSUE THREAD

**Issue by wppele** [wenzhixin/bootstrap-table#3296]
bootstrap-table导出数据超过1000条时会响应一段时间，导出数据超过10000条的时候会无响应，请问有什么应对措施吗？

**Comment by fjfndfjf** [comment]
+1 @wenzhixin

**Comment by wenzhixin** [comment]
你假如知道前端导出的原理就知道原因了，太大数据量的话还是后台导出吧，前端支持不好，而且低版本IE也不支持。
