### ISSUE TITLE
Data-height being applied for "fixed-table-body" AND "fixed-table-container"

### ISSUE THREAD

**Issue by LeoGardel** [wenzhixin/bootstrap-table#3297]
HI,

When we specify the attribute `data-height="700"` in a table, this value is used to limit the size of the `fixed-table-container` element. However, the `fixed-table-body` is set with `height: 100%`, so, it becomes 700 of height as well.

In my code, there is a container with 700 of height, a header inside of it with 90 of height and a body with 698 of height right below.

This situation causes the table to cover the next element after the table, with almost a 90px "extra stripe".

This could be considered a bug?

**Comment by wenzhixin** [comment]
Have you solved your problem?
If the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
