### ISSUE TITLE
使用angular,"onLoadSuccess"在表格加载完成后没有触发事件

### ISSUE THREAD

**Issue by 7Light** [wenzhixin/bootstrap-table#3301]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by 7Light** [comment]
for (var x = 0; x < $scope.apps.length; x++) {
                for (var i = 0; i < $scope.apps[x].tables.length; i++) {
                    var tab = $scope.apps[x].tables[i];
                    tab.bsTableControl = {
                        options: {
                            data: tab.data,
                            rowStyle: function (row, index) {
                                return {
                                    classes: 'none'
                                };
                            },
                            cache: false,
                            // height: 400,
                            striped: true,
                            search: true,
                            showColumns: true,
                            showRefresh: false,
                            minimumCountColumns: 2,
                            clickToSelect: false,
                            showToggle: true,
                            maintainSelected: true,
                            columns: tab.col,
                            onDblClickCell: function (data) {
                                var data = $('#' + tab.id).bootstrapTable('getData', true)
                                //合并单元格
                                mergeCells(data, "docName", 1, $('#' + tab.id));
                            },
                            onLoadSuccess: function (data1) {
                                console.info(data1);
                                var data = $('#' + tab.id).bootstrapTable('getData', true)
                                //合并单元格
                                mergeCells(data, "docName", 1, $('#' + tab.id));
                            }
                        },
                    }
                }
            }

**Comment by 7Light** [comment]
并且，我不知道在angular下怎么调用table的各种方法，所以我还得给每个table加个id才能实现使用那些方法

**Comment by wenzhixin** [comment]
是的，需要增加 id 或者 class。
