### ISSUE TITLE
insertRow with another formatter for cell

### ISSUE THREAD

**Issue by szymjaw** [wenzhixin/bootstrap-table#3304]
If it possible to insert row with other formatter for one cell ?
My example : [https://jsfiddle.net/8o6rrnrk/2/](https://jsfiddle.net/8o6rrnrk/2/)

I need to insert row temporary with SAVE and CANCEL buttons in MENU column, when SAVE then datas from temporary row are save to database and table will refresh with operateFormatter2 in MENU column.

Now when I clicked Division button, insertRow function create row with operateFormatter2 but I need operateFormatter3.

Any help would be appreciated

**Comment by wenzhixin** [comment]
This example can solve your problem: https://jsfiddle.net/wenyi/8o6rrnrk/3/
