### ISSUE TITLE
Wrong direction of pagination numbers in rtl language

### ISSUE THREAD

**Issue by AliShahrivarian** [wenzhixin/bootstrap-table#3311]
Hi

I'm using bootstrapTable with pagination and "fa-IR" locale. Everything is OK except pagination number direction. They must be from right to left but They're ltr now.

**Comment by wenzhixin** [comment]
Any PR is welcome.

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days, please create a PR, thanks!
