### ISSUE TITLE
关于数据加载方式

### ISSUE THREAD

**Issue by YoLoveLife** [wenzhixin/bootstrap-table#3313]
我使用boostrap-table来构建我的项目。
一部分的页面使用boostrap-table来做ajax请求来构建table内的内容。
还有一部分页面希望近使用boostrap-table来在页面上进行数据的展示与保存
我使用boostrap-table的data参数来直接赋值
但是在显示上出现了问题 table上正确显示了数据 也持续显示Loading, please wait...
是否有方法直接加载静态数据而并不发起一个ajax的请求。

**Comment by klren0312** [comment]
我也遇到这个问题。。。。
就是一直显示
`No matching records found`

**Comment by YoLoveLife** [comment]
@klren0312 bootstrap-table好像是需要URL做AJAX请求来做数据载入的 我使用了API来解决这个问题

**Comment by klren0312** [comment]
那意思时后台必须要发送和它格式对应的json，是吗0.0

**Comment by YoLoveLife** [comment]
@klren0312 我的理解是这样的。本身在官网看data参数的确应该可以直接指定固定的数据格式就可以。但是bootstrap-table在指定了data数据的同时仍旧发起了ajax请求。也许会有个参数能够指定使用静态数据。这种使用方法虽然驳回我网站之前的数据传递方式，但是我觉得这种方式更加合理。

**Comment by wenzhixin** [comment]
不要指定 url 就行，有例子啊：http://jsfiddle.net/wenyi/e3nk137y/13/
http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-data.html

**Comment by YoLoveLife** [comment]
谢谢 可能是我的JSON格式有问题
