### ISSUE TITLE
设置height后表头和内容无法对齐

### ISSUE THREAD

**Issue by HeNanBing** [wenzhixin/bootstrap-table#3314]
设置了table的data-height之后，内容与表头错位
![tim 20170815171125](https://user-images.githubusercontent.com/13029560/29309579-da582326-81dc-11e7-93d7-2b96278ae2d5.png)
设置了resetView，还是错位
![tim 20170816175827](https://user-images.githubusercontent.com/13029560/29358141-9f6144e8-82ac-11e7-9819-4da952ec82d5.png)
![tim 20170816175846](https://user-images.githubusercontent.com/13029560/29358152-a68a74f6-82ac-11e7-8325-ec369e3cafc4.png)

**Comment by mowatermelon** [comment]
/*我同样遇见了这个问题，手动写了fixed-table-header，table数据加载完成之后，fixed-table-body中的数据和手写的table-header出现了列不对称情况。*/
I also met the problem, and manually wrote the `fixed-table-header`, table data loading completed, the data in `fixed-table-body` and `handwritten table-header` column asymmetry occurred.

**Comment by mqy1023** [comment]
同问这个问题怎么解决？

**Comment by jichiduo** [comment]
遇到同样的问题，但是点击表头排序后，表头和内容又可以对齐，一开始使用1.10.1版本，升级到1.11.1版本还是有同样的问题，取消data-height的设定之后恢复正常。

**Comment by wenzhixin** [comment]
能否提供下使用的 jsfiddle？方便调试问题，这边使用并没有出现不对齐的情况。

**Comment by chaikenao** [comment]
你可以尝试在onLoadSuccess内使用resetView，同样遇到此问题

**Comment by wenzhixin** [comment]
可以试试楼上的方法。另外这个问题自己在使用的过程中并没有遇到，假如还存在的话请提供下 jsfiddle 并 reopen 这个问题，谢谢。

**Comment by zhenwie** [comment]
![tablehead](https://user-images.githubusercontent.com/17755175/34466182-1cdd6170-ef06-11e7-8c92-803e30fb3fdd.png)

Hi, if you add "data-height" for your example extentions/group-by-v2.html, you can reproduce this issue.
@wenzhixin

**Comment by wenzhixin** [comment]
group-by 的问题，麻烦建个新的 issue
