### ISSUE TITLE
启用搜索按钮

### ISSUE THREAD

**Issue by freezyh** [wenzhixin/bootstrap-table#3315]
bootstrap-table在移动端使用的时候，如果启用搜索框以后想点击搜索按钮来进行搜索，可是没有搜索按钮，如果在搜索框右侧添加一个搜索按钮？

**Comment by wenzhixin** [comment]
现在默认是监听 keyup 来触发搜索的，[searchOnEnterKey](http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options)，你是不是设置为 `true` 了，另外移动端的输入法一般都有确定的。
