### ISSUE TITLE
How to use data-formatter and data-events in angular2?

### ISSUE THREAD

**Issue by alejamoreno94** [wenzhixin/bootstrap-table#3316]
Hi I have used your bootstrap table in angular 2 and its working fine. But I would like to know how to make the click event bind in the data-formatter. Its throwing an error when an event click occurs. Below is my sample code.

 let options: any = {
                    title: 'Opciones',
                    field: 'opciones',
                    align: 'center',
                    formatter: this.operateFormatter,
                    events: $(window).operateEvents = {
                        'click .like': function (e, value, row, index) {
                            alert('You click like icon, row: ' + JSON.stringify(row));
                            console.log(value, row, index);
                        },
                        'click .edit': function (e, value, row, index) {
                        },
                        'click .remove': function (e, value, row, index) {
                            /*$('#table').bootstrapTable('remove', {
                                field: '_id',
                                values: [row._id]
                            });*/
}
                    }
                };

 operateFormatter(value, row, index) {
        var sPermisos = "";
     if (row.delete) {
            sPermisos += `<button  class="btn btn-simple btn-danger btn-icon remove" rel="tooltip" title="close" data-placement="left">
                                                <i class="material-icons">close</i>
                          </button>`;
        }
        return sPermisos;
    }

Event does not bind with the formatter and events since its dynamically added and aditionally I need to put the route.navigate for angular. I want to work tables dynamically  is for this reason I need it. this is the error in Angular 2 (Cannot read property 'navigate' of undefined). Please help me to resolve this.

**Comment by Phattharawit** [comment]
What is $(window).operateEvents ? Actually you don't need it. try to remove it and let see whether it work or not.  Just  event:s{ /*here is what ever event you wish to put*/}

**Comment by wenzhixin** [comment]
@Phattharawit is right.
