### ISSUE TITLE
[group-by] indenter icon duplicated on destroy/reload of data

### ISSUE THREAD

**Issue by mlbaquerizo** [wenzhixin/bootstrap-table#3318]
Using the group-by extension (not v2), upon destroying and reloading the table again, i.e.
```
$table.bootstrapTable('destroy').bootstrapTable({
    groupBy: "true",
    groupByField: ["group"]
}).bootstrapTable('load', data);
```
the `<span class="indenter">` element is duplicated for each row each time. I think this is a bug.

See jsfiddle [here](http://jsfiddle.net/nd5usdn4/2/). In this example the reload button above the table does the above code.

Work around would be to use removeAll instead of destroy and not reinitialize bootstrapTable. But what if I wanted/needed to use destroy?

**Comment by wenzhixin** [comment]
Fixed: http://jsfiddle.net/wenyi/nd5usdn4/4/
