### ISSUE TITLE
Data Editable with display Formatter not working

### ISSUE THREAD

**Issue by jonathangreco** [wenzhixin/bootstrap-table#3320]
I have an issue in this context :
https://jsfiddle.net/02ep9mnk/10/

A more complete fiddle (wich not working well with fixed columns and cell style formatter)
https://jsfiddle.net/02ep9mnk/13/

My Columns are dynamic only for my items (I can have 3/4/5...X items) I generate my headers in PHP, and provide my lines with bootstrap table.

My Json in the fiddle is complete enought to present my issue.
The issue I'm facing is simple, I can't pass to my formatter the value of my object to show it, and make bootstrap-table-editable to work.

I achieved this with a workaround using the x-editable plugin directly yesterday, but the footer i've had didn't refresh on save.

So I know it's possible in a way to get my data, and make it editable, but without using Bootstrap-table-editable plugin and then no update on the footer when editable is done.. Wich is not what I want.

My data as provided in the fiddle is not a problem because some data formatter succeed to show it correctly. 
My only problem is to make all things work together....

I need to undestand if I can achieve this that way. Any help is very welcomed.

**Comment by rrajgor167** [comment]
hi here is the solution, I have tried
`,{
                        field:'exp_date',
                        title:'DATE',
                        visible:true,
                        sortable:true,
                        editable: {
                            type: 'combodate',
                            'title': 'Expense Date'
                            
                        },
                        filterControl:'datepicker',
                        //displayFormatter:'dateFormatter2'
                        editableDisplayFormatter:'dateFormatter'


                    }`

....
`var scope = this;

            scope.dateFormatter = function(value) {//alert(moment(value).format('YYYY-MM-DD'));
              //var icon = $(this).data('pk') % 2 === 0 ? 'glyphicon-star' : 'glyphicon-star-empty';
              var markup = changeFormat(moment(value).format('YYYY-MM-DD').split('-'),0);
              $(this).html(markup);
            };
            //$.fn.editable.defaults.mode = 'inline';
            $.fn.editable.defaults.display = function(value, sourceData) {
              var displayFormatterFunction = $(this).data('display-formatter');
              if (displayFormatterFunction) {
                scope[displayFormatterFunction].call(this, value, sourceData);
              } else {
                $(this).html(value);
              }
            };`

...
`function changeFormat(tt,format)
        {      
          
            var date = new Date(tt[0]+'-'+tt[1]+'-'+tt[2]);
          var newdate = new Date(date);      
            var dd = newdate.getDate();// -1 ;//change1
            var mm = newdate.getMonth() + 1;        
            var y =  newdate.getFullYear() ;
            //alert(date);
            if(isNaN(dd) || isNaN(mm) || isNaN(y))return '';
            if(dd<10)
              dd='0'+dd;
            if(mm<10)
              mm='0'+mm;
          //if(format===0)  
            return dd + '/' + mm + '/' + y;
          
        }`

**Comment by wenzhixin** [comment]
Have you solved your problem? @jonathangreco

**Comment by jonathangreco** [comment]
Not the way I wanted, but I found a workaround.

**Comment by wenzhixin** [comment]
Can you share your workaround?

**Comment by jonathangreco** [comment]
My workaround is to calc my footer values in PHP and construct a JSON like this pastebin (for my local data)

This pastebin represent my JSON data. Once this one compliant with your module, work with it is easy enought :
https://pastebin.com/w6Hd1Skz

My footer is calculated on each event that modify in any way the sum of columns.
This is before I save an editable cell
![11-12-2017 15-22-32](https://user-images.githubusercontent.com/1587180/33835877-1b34939a-de88-11e7-86b1-654f7e01e0d9.png)

After save we can see external components beeing refreshed
![after save](https://user-images.githubusercontent.com/1587180/33835878-1b4eb2b6-de88-11e7-81a9-a965958979c6.png)
