### ISSUE TITLE
how One column displays multiple data

### ISSUE THREAD

**Issue by leiyong316** [wenzhixin/bootstrap-table#3322]
normal
![image](https://user-images.githubusercontent.com/2143362/29417973-93cece88-839d-11e7-921f-230dd4cb4543.png)

I hope
![image](https://user-images.githubusercontent.com/2143362/29417996-a8ece2c8-839d-11e7-8eca-82da3cc82f64.png)

thanks

**Comment by jonathangreco** [comment]
You can use data formatter to achieve this.

**Comment by wenzhixin** [comment]
`formatter` column option can solve your problem.
