### ISSUE TITLE
列太多了之后，设置列的width无效

### ISSUE THREAD

**Issue by super3s1988** [wenzhixin/bootstrap-table#3327]
请问一下，我列太多，大概有30多列，但是设置width一点效果都没有

**Comment by fjfndfjf** [comment]
遇到同样的问题，求解决方法

**Comment by HyramTang** [comment]
Like this http://jsfiddle.net/shamiao/mGR6J/9/, please help resolve it. @djhvscf

**Comment by wenzhixin** [comment]
@HyramTang what do you mean？

**Comment by wenzhixin** [comment]
30多列？能否提供下有问题的 jsdiffle？

**Comment by HyramTang** [comment]
@wenzhixin 抱歉，鏈接不知道為什麼失效了，重新貼個鏈接：
http://jsfiddle.net/Hyram/0e3w817o/

**Comment by wenzhixin** [comment]
实际上已经有设置上了，不过确实没有生效。试试 google 下：https://stackoverflow.com/questions/5971208/th-width-not-working？

**Comment by wenzhixin** [comment]
> Though if the table is left responsive and sized too small this 'width' might be ignored (use min/max-width via class or such then)

已经在 https://bootstrap-table.com/docs/api/column-options/#width 文档中进行了说明，可以考虑使用 class 或者 min/max-width 来解决。
