### ISSUE TITLE
bootstrap-table-resizable.js与detailView

### ISSUE THREAD

**Issue by sunshinefull** [wenzhixin/bootstrap-table#3331]
bootstrap-table.js属性detailView设为true，当添加bootstrap-table-resizable.js插件。当resizable改变列大小时，detailView里面的列宽度不会跟着改变。如果要拖动bootstrap-table column列的大小时，detailView里面的列也跟着改变，js要怎么写。

**Comment by githubkyr** [comment]
你好，这个问题你解决了吗？怎么解决的

**Comment by wenzhixin** [comment]
detailView 的内容是需要自己控制的，不支持 resizable 改变后自动变。
