### ISSUE TITLE
Icons are disappeared when using the default example

### ISSUE THREAD

**Issue by jkathir** [wenzhixin/bootstrap-table#3332]
i downloaded and used the default example..however when i changed the path of javascript and css files to to point to local path and opened the html file..The grid is successfully shown but icons such as export, refresh are all gone..i am not sure where the icons folders path needs to be given...

http://issues.wenzhixin.net.cn/bootstrap-table/

need a working standalone html file for the above example

**Comment by jkathir** [comment]
Identified the reason..It is because the fonts folder is needed...when added the fonts folder ex: glyphicons-halflings-regular the icons are rendered successfully...it should be added with the example folder itself to run it as standalone

**Comment by djhvscf** [comment]
Close this issue since it's solved
