### ISSUE TITLE
Delete row after reorder bug

### ISSUE THREAD

**Issue by Jingkun-Hu** [wenzhixin/bootstrap-table#3333]
If I reordered the row, then delete one row, it would delete the row with original table order, incorrect row being deleted

Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by Jingkun-Hu** [comment]
Solved.

**Comment by Jingkun-Hu** [comment]
Use "load" method to "refresh" data in client side after reordering

**Comment by djhvscf** [comment]
Close this issue since it's solved
