### ISSUE TITLE
请问下怎么支持bootstrap4

### ISSUE THREAD

**Issue by zkning** [wenzhixin/bootstrap-table#3334]
how to support bootstrap4

**Comment by stevespringett** [comment]
+1 Bootstrap 4 is finally in beta. Time to support it.

**Comment by MathiasMeuleman** [comment]
+1 Is this already scheduled?

**Comment by macdoor** [comment]
bootstrap 4 support +1

**Comment by 332557712** [comment]
请问下怎么支持bootstrap4，谢谢！

**Comment by HarleyTan** [comment]
bootstrap 4 support +1

**Comment by wenzhixin** [comment]
Close ref #3428
