### ISSUE TITLE
有没有方法可以控制列表头的展示顺序!

### ISSUE THREAD

**Issue by For-ever21** [wenzhixin/bootstrap-table#3335]
在使用大大的bootstrap-table的时候,发现表头的展示顺序是在columns里默认的排序的,有没有一种方法可以控制他们的展示顺序...

**Comment by wenzhixin** [comment]
木有办法，因为 columns 是数组，你只能修改它的顺序。
或者你看看这个插件 http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-columns.html 是否有帮助。
