### ISSUE TITLE
Sort by custom data-field on td

### ISSUE THREAD

**Issue by jakobdo** [wenzhixin/bootstrap-table#3337]
Why is this code not working: https://jsfiddle.net/pgvuwy60/

I have tried to copy all code from this: http://jsfiddle.net/e3nk137y/1434/

But i don't understand why my code is not working.
Any advice?

**Comment by Mic2** [comment]
Det er JS settings i fiddle der gør det ikke virker.

Prøv:
FRAMEWORKS & EXTENSIONS = Jquey 2.1.3
og load type = No Wrap in <body>

Efter jeg satte de settings og trykkede på run, så virkede det.

**Comment by wenzhixin** [comment]
@Mic2 is right.

![image](https://user-images.githubusercontent.com/2117018/33792777-a16e91f0-dce3-11e7-9013-311463ffcb21.png)
