### ISSUE TITLE
No data return when use server side pagination with 'All' in page-list 

### ISSUE THREAD

**Issue by WisdomZheng** [wenzhixin/bootstrap-table#3342]
Hi, I found when using server side pagination with 'all' in page-list and extension cookie, there may return no data.
For example:
```
<table id='table'
    ...
    data-pagination="true"
    data-side-pagination="server"
    data-page-list="[20,50,100,All]"
    ...>
```
And data displayed normally when you first refresh the page.
Then select item 'All' in pagelist, table loaded all data from server normally, and set cookie bs.table.pageList="All"

And now comes the exception, when you refresh the page with cookie bs.table.pageList="All", there are no data return from server.

And I found the reason is:
in params post to server: params.limit=0
in bootstrap-table.js line 1999: 
```
if (this.options.pagination) {
    params.offset = this.options.pageSize === this.options.formatAllRows() ?
      0 : this.options.pageSize * (this.options.pageNumber - 1);
    params.limit = this.options.pageSize === this.options.formatAllRows() ?
      this.options.totalRows : this.options.pageSize;
}
```

this.options.totalRows=0

Can anyone give some advice on how to deal with this issue?
Thanks!

**Comment by danielbohnrs** [comment]
I have almost the same problem, except I dont use cookie extension.

When select 'All', no new data is loaded and at console got the error: "Cannot read property 'total' of null".
The server didn't receive a post request when option 'All' is selected.

**Comment by wenzhixin** [comment]
Remove limit param when it is 0, your server need to return all rows.
