### ISSUE TITLE
Ajax call for loading data:  stuck on "Please wait, Loading .....

### ISSUE THREAD

**Issue by kingmohd** [wenzhixin/bootstrap-table#3343]
The data-ajax seems not to be working.

It is stuck at loading message.

https://jsfiddle.net/bt2n3n08/

**Comment by wenzhixin** [comment]
You can change the `load type` to solve your problem: https://jsfiddle.net/wenyi/bt2n3n08/1/
![image](https://user-images.githubusercontent.com/2117018/33752103-8e4dccd6-dc1a-11e7-8f11-dbd0b10979e5.png)
