### ISSUE TITLE
checkbox 能不能不默认选中?

### ISSUE THREAD

**Issue by zkning** [wenzhixin/bootstrap-table#3344]
checkbox 能不能不默认选中?

    sprintf(' checked="%s"', value === true ||
                        (value_ || value && value.checked) ? 'checked' : undefined) +

**Comment by guozhen168** [comment]
你的field不设置值，就可以了呀，或者设置为空

**Comment by wenzhixin** [comment]
设置个不存在的 field，例如 `state`，假如是存在的 field 需要 `false` 值才不会选中。
