### ISSUE TITLE
While reordering the columns, column data is being sorted

### ISSUE THREAD

**Issue by BallaLakshmi** [wenzhixin/bootstrap-table#3350]
I don't want sorting, when i reorder the columns. but in firefox the column data is being sorted, whenever i try to reorder the columns. this is working fine with other browsers (chrome/safari/IE).
I don't know whats happening with firefox browser. Please help me

http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-columns.html

**Comment by Falseee** [comment]
@djhvscf Could you test if this issue still exists ?

**Comment by UtechtDustin** [comment]
Consider to change the plugin ([dragtable](https://github.com/akottr/dragtable)), the last update is 3 years ago.

What do you think ?
Do you maybe already now a other plugin ? (or should we implement without plugin?)
@wenzhixin @djhvscf

**Comment by djhvscf** [comment]
I prefer implement this without plugin since we have in our roadmap remove jQuery dependency

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf 
Removing Jquery as dependency is a huge task, so i guess we should still continue developing the table and remove jquery as sidetask.

So for that table we have to define a area for the drag handle, which means only on that area is sorting/dragging allowed. Also must be the order event restricted to anything except the draghandle.

Which kind of draghandle should we choose, vertical  or horizontal ?

![Screenshot_2019-11-03 Screenshot(1)](https://user-images.githubusercontent.com/13292481/68088897-e93fca00-fe63-11e9-9c65-a9da5eb64548.png)
![Screenshot_2019-11-03 Screenshot](https://user-images.githubusercontent.com/13292481/68088898-e93fca00-fe63-11e9-9955-6477a554ccd6.png)
