### ISSUE TITLE
row over

### ISSUE THREAD

**Issue by yvandupre79** [wenzhixin/bootstrap-table#3351]
i created a small example of jsfiddle
http://jsfiddle.net/bhrtkfjv/

when i pass mouse cursor over a row, there is not color over who is done automatically.

**Comment by jimgit** [comment]
Try removing:

data-classes="table table-no-bordered" 


See http://jsfiddle.net/jimkennelly/w1krd0ey/

**Comment by wenzhixin** [comment]
@jimgit is right: http://jsfiddle.net/wenyi/w1krd0ey/3/
