### ISSUE TITLE
How can I UpdateCell by UniqueId, instead of Row Index

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#3354]
Hello, 

I need to update a cell based on some run time logic, not triggered by row click event, so I don't have row index.

All I have is UniqueId.

Basically, "getRowByUniqueId" does not return row index, and "updateCell" needs row index.

It doesn't seem every efficient to use "getRowByUniqueId" to get the row data, then use "updateByUniqueId" to copy every column not changed, except one column with new value.

Any suggestions?

Any help greatly appreciated!

**Comment by luisbessa** [comment]
Hello,

You don't need to pass all column values in "updateByUniqueId". 

You can just do:

table.bootstrapTable('updateByUniqueId', {
          id: ID,
          row: {FIELD: VALUE}
        });

**Comment by startovernow** [comment]
Wow, thanks much! Will try out your solution

**Comment by wenzhixin** [comment]
`updateCellById` method can solve your problem.

**Comment by startovernow** [comment]
Hi @wenzhixin , current version v1.11.1 does not have "updateCellById", where can I get it?
Thanks!
