### ISSUE TITLE
拖拽排序显示错乱

### ISSUE THREAD

**Issue by HeNanBing** [wenzhixin/bootstrap-table#3357]
对表格列进行拖拽排序，拖拽的过程中表格样式错乱
如图，拖拽“日期”一列，表格的样式错乱了，排版都错了，
![tim 20170913115428](https://user-images.githubusercontent.com/13029560/30359117-35905cae-987b-11e7-91be-a39942d3d1c8.png)
其他的列有成了<li>样式，纵向排列开了:
![tim 20170913115409](https://user-images.githubusercontent.com/13029560/30359126-45ea8656-987b-11e7-89f1-8e329446dd3e.png)
之前对原表格做过一些样式调整，会影响到拖拽功能吗？

**Comment by wenzhixin** [comment]
有可能会有影响。拖拽现在是使用 extension 插件，相关的问题请到对应的 repo 上提，谢谢。
