### ISSUE TITLE
隐藏checkbox列同时保留clickToSelect功能

### ISSUE THREAD

**Issue by HeNanBing** [wenzhixin/bootstrap-table#3358]
现在想要隐藏checkbox一列，但hideColumn之后，clickToSelect功能就没效了，getSelections就没内容了，怎么可以隐藏的同时保留功能呢？
![tim 20170913152324](https://user-images.githubusercontent.com/13029560/30364701-e47b88da-9897-11e7-89b6-f8ea73c160ef.png)

**Comment by wenzhixin** [comment]
不支持呢，不过你可以自己通过 click 事件来实现， 这里有个点击改变颜色的例子：http://issues.wenzhixin.net.cn/bootstrap-table/#issues/563.html，你可以改成你想实现的功能，然后通过判断颜色变化去选择已经选中的列。

**Comment by feikeq** [comment]
有一种场景会有bug:选中一行进行编辑，编辑完后更新表格，选中的状态就消失了。

在使用bootstrapTable('updateCell') 更新单元格时自己写的样式会被重置，只有clickToSelect功能添加的selectd这样式会保留！ 所以不能用你说的这个方法 @wenzhixin

**Comment by wenzhixin** [comment]
@feikeq 你说的功能应该可以使用 `rowStyle` 来实现。

**Comment by feikeq** [comment]
rowStyle 不是在列头配置时的吗？请问怎么在 行的click时调用 rowStyle ？ 谢谢。 @wenzhixin

**Comment by feikeq** [comment]
/* 加个CSS隐藏第一个带复选框的TD */
.bs-checkbox {
	display: none;
}

还是这样简单，不用去定义中间变量来比值。。。。 @HeNanBing

**Comment by wenzhixin** [comment]
用这种方式可以实现也是可以的
