### ISSUE TITLE
Multiple “post-body.bs.table” events on table create - how to know which is the final one?

### ISSUE THREAD

**Issue by rajlitalien** [wenzhixin/bootstrap-table#3359]
Hello!

I have bound to the bootstrap table "post-body.bs.table" to display an HTML "card" with a summary of the first row of the table upon table create.  The data of the table is obtained via a data-url.   I need to know when the table has completed all its processing and is ready to the DOM so that I can select the first row of the table and display this card. 

However, I've noticed that upon the table create, there are two (2) "post-body.bs.table" events generated. I assume one is for the table create and the second is related to the data URL.  Is there a way to determine which of the "post-body.bs.table" is the "final last" post event?  

Currently, the data shown in the card switches between the table data from the first post-body event and then is quickly replaced by the table data from the second post-body event.   Not an elegant behaviour.  Is there a way to know how many post-body.bs.table events will be generated on one table (there may be more than 2 depending on operations on the table) and how to determine when the "Final-last" event will be received ?

Thank you in advance for your help!

To replicate, simply add the following to your jsFiddle example (http://jsfiddle.net/e3nk137y/16042/)

    $('#mytable').on('post-body.bs.table', function (data) {
        console.log('post-table event generated');
    });

**Comment by wenzhixin** [comment]
Check the final post-body event: http://jsfiddle.net/wenyi/e3nk137y/17778/

**Comment by NiteshKedia** [comment]
Hi,

I am facing a similar issue where the table DOM is rendered after I make call to post-body.bs.table
I am trying to implement a logic where I upload data to my table in background after I load the basic table.

$table.on('post-body.bs.table', function(e, data) {
        console.log("loading data in backend started....")
            for(row in data) {
                var input = {
                        rowKey: data[row].rowKey
                    };

                console.log("processing..", data[row].rowKey);
                data[row].eventTypeCountMap = getEventTypeCountMap(input);
            }
        console.log("loading data in backend ended....")
    });

But I see that my table is loaded only after the above processing is done. Am I making some mistake ?
