### ISSUE TITLE
Complex Header with rowspans and colspans

### ISSUE THREAD

**Issue by mileswest07** [wenzhixin/bootstrap-table#336]
Currently, when using Javascript to dynamically create the table definition, there is no functionality to create a table header `<thead>` element that has multiple column layers, using `rowspan` and `colspan` as properties, without going through the DOM and manually editing the HTML for the table every single time. And even this solution doesn't work when the table refreshes. 

Requesting an enhancement to include a possibility for non-standard table headers, while preserving the functions for Show/Hide Columns, Sort, Filter, etc.

**Comment by razmage** [comment]
I also have this issue. It would be nice if we could have multiple rows for our headers (http://jsfiddle.net/7pDqb/)

**Comment by DavidePastore** [comment]
:+1:

**Comment by xiaolai913** [comment]
Hi, I have faced the same problem

**Comment by Wexcode** [comment]
Would also like to support multiple rows in `<thead>`.

**Comment by rajapulau** [comment]
and can use rowspan and colspan with javascript method bootstrap table

**Comment by wenzhixin** [comment]
Consider example: http://drvic10k.github.io/bootstrap-sortable/

**Comment by SarahD** [comment]
Hi @wenzhixin! Do you plan on incorporating this multi-header functionality in the future? My company LOVES your extension and we really don't want to switch away from it just to have the multi-header functionality.

**Comment by djhvscf** [comment]
@SarahD Yes, we are thinking the best way to implement that in our plugin

**Comment by wenzhixin** [comment]
Added this feature. Examples: http://issues.wenzhixin.net.cn/bootstrap-table/ and http://issues.wenzhixin.net.cn/bootstrap-table/#options/group-columns.html

**Comment by djhvscf** [comment]
Wow!! @wenzhixin great job!!!

**Comment by wenzhixin** [comment]
@djhvscf help to update es docs: https://github.com/wenzhixin/bootstrap-table/blob/master/docs/_i18n/es/documentation/column-options.md

**Comment by djhvscf** [comment]
@wenzhixin it is done see this; https://github.com/wenzhixin/bootstrap-table/pull/1073

**Comment by jsiebach** [comment]
Is this possible using Javascript table method?  I cannot add a second `<tr>`

**Comment by emc2solutions** [comment]
I'm having an issue the header is not aligning with the data

![image](https://user-images.githubusercontent.com/32971995/178090380-20b3a3c3-0c27-4c9a-8e3b-e6839b50b291.png)
