### ISSUE TITLE
使用flatJson时筛选bug

### ISSUE THREAD

**Issue by xxbld** [wenzhixin/bootstrap-table#3362]
https://github.com/wenzhixin/bootstrap-table/blob/6350315fe6b568dfe24e98d8aa952387d57a1588/src/extensions/select2-filter/bootstrap-table-select2-filter.js#L229

**Comment by wenzhixin** [comment]
欢迎提 PR

**Comment by wenzhixin** [comment]
The select2-filter extension has a bug when using flat JSON data. 
I will check this bug.

**Comment by wenzhixin** [comment]
#4433 removed the select2-filter extension.
