### ISSUE TITLE
How to sidePagination: 'server' when using Table from data?

### ISSUE THREAD

**Issue by bustersg** [wenzhixin/bootstrap-table#3363]
i am using '**Table from data**' example from - [http://jsfiddle.net/wenyi/e3nk137y/13/](http://jsfiddle.net/wenyi/e3nk137y/13/)
my table is displayed **correctly** but however the jsfiddle does not show you how to use pagination.

my `<table>` tag is as follow:
`<table id="table_blocked" data-toolbar="#toolbar_blocked" data-show-export="true" data-search="true" data-sort-name="subject_id" data-sort-order="asc" data-side-pagination="server" data-pagination="true" data-page-size="25" data-page-list="[25, 50, 100, 200, All]" class="table table-hover table-condensed">`

my `<script>` is as follow:
`$(function () {
$('#table_blocked').bootstrapTable({
data: data,
sidePagination: 'server'
});});`

will appreciate any tips on adding the pagination or is not possible unless using data-url ?
thanks in advance.

**Comment by jimgit** [comment]
From your comment,  you are filling the table from the variable 'data'?   If so,  could you change that to 
data: getData(), 

from the new getData function you must provide pass the sort, take and search parameters 

so the function might look like 

function getData(search, take, sort){
}

Also note that the server pagination required a different layout of the json  - see the description column on this page [http://bootstrap-table.wenzhixin.net.cn/documentation/](url)

{
 "total": 200,
    "rows": [
        {
            "id": 0,
            "name": "Item 0",
            "price": "$0"
        },

**Comment by wenzhixin** [comment]
#1765 
Load(server): http://jsfiddle.net/wenyi/e3nk137y/11459/
