### ISSUE TITLE
singleSelect + searchText, bug happen when getSelections

### ISSUE THREAD

**Issue by zyairzy** [wenzhixin/bootstrap-table#3364]
singleSelect + searchText, bug happen when getSelections

Firstly, I select one row "ee" in table.
Secondly, I add searchText "a" to get result with no row "ee".
Thirdly, I select another row "aa" with searchText "a",
then I use getSelections, it will return 2 rows selected (expected 1)

I find this bug is similar to bug #2963 #2544 

jsfiddle example: https://jsfiddle.net/zyairzy/yxgbcavb/

**Comment by LayGe** [comment]
Hello.Do you resolve this problem?

**Comment by wenzhixin** [comment]
Fixed: https://jsfiddle.net/wenyi/yxgbcavb/1/
