### ISSUE TITLE
Have Data but .bootstrapTable shows No matching records found

### ISSUE THREAD

**Issue by lpeteet** [wenzhixin/bootstrap-table#3365]
Hope it is ok to post my issue here.  I have spent hours trying to fix it. 
Have Data but shows "No matching records found".

Environment:
  Windows 10,
  Chrome Version 61.0.3163.91 (Official Build) (64-bit),
  bootstrap/3.3.7/css/bootstrap.min.css
  bootstrap-table/1.11.1/bootstrap-table.min.css
  assets/css/reset.css
  bs4/jq-3.2.1/jq-3.2.1/dt-1.10.16/datatables.min.css
  rawgit.com/wenzhixin/bootstrap-table/master/src/bootstrap-table.css

  bs4/jq-3.2.1/jq-3.2.1/dt-1.10.16/datatables.min.js
  jquery/2.1.3/jquery.min.js
  wenzhixin/bootstrap-table/master/src/bootstrap-table.js
  bootstrap-table/1.11.1/bootstrap-table.min.js
  bootstrap-table/1.11.1/extensions/filter/bootstrap-table-filter.js

 AJAX API (GET): https://api.data.gov/ed/collegescorecard/v1/schools.json?

Code that Shows No Records:
        var mydata2 = [
            {
                "school.name":"" + name,
                "id":"" + id,
                "2013.student.size":"" + studentSize,
                "2013.admissions.sat_scores.average.overall":"" +  sat,
                // "rows":result.results.length
                "rows":"" + 1
            }
        ];
        console.log("mydata2", mydata2);

        $('#clienti').bootstrapTable({
            data: mydata2
        });

JSFiddle:
  https://jsfiddle.net/lpeteet/ac6v0bxc/1/

Thank YOU!!

**Comment by wenzhixin** [comment]
You need to use `load` method because you had initialized the table via `data-toggle="table"`.
```
$('#clienti').bootstrapTable('load', mydata2);
```
