### ISSUE TITLE
Label removed for checkbox in 1.11

### ISSUE THREAD

**Issue by waqasjaved160** [wenzhixin/bootstrap-table#3369]
How to add label to checkboxes to select single or all table rows.

In version 1.9 there is this line#740

`if (column.checkbox) {
                    if (!that.options.singleSelect && that.options.checkboxHeader) {
                        text = '<label class="mt-checkbox mt-checkbox-single mt-checkbox-outline"><input name="btSelectAll" type="checkbox" /><span></span></label>';
                    }
                    that.header.stateField = column.field;
                }`

but in version 1.11 it is changed to line#825

`if (column.checkbox) {
                    if (!that.options.singleSelect && that.options.checkboxHeader) {
                        text = '<input name="btSelectAll" type="checkbox" />';
                    }
                    that.header.stateField = column.field;
                }`

Is there a way to get it like 1.9 in version 1.11 without changing the library code.

**Comment by wenzhixin** [comment]
You can use jQuery [`wrap`](https://api.jquery.com/wrap/) method to solve your problem: http://jsfiddle.net/wenyi/e3nk137y/17732/
