### ISSUE TITLE
Extension "Table Editable" not working with Bootstrap 4

### ISSUE THREAD

**Issue by dzmitry-masko** [wenzhixin/bootstrap-table#3371]
I'm using Bootstrap 4. But the Editable extension does not work with it.

![editable](https://user-images.githubusercontent.com/11837753/30634071-7a28461c-9df6-11e7-9168-f4b0e9ec29d4.png)

**Comment by jesuspm** [comment]
Bootstrap-table actually isn't compatible with Bootstrap 4 style... we need it, please.

**Comment by aaronfhd** [comment]
can we get a request to make it compatible

**Comment by wenzhixin** [comment]
Now is compatible: #3428
