### ISSUE TITLE
Using onResize extension from colResizable

### ISSUE THREAD

**Issue by cindymarie** [wenzhixin/bootstrap-table#3372]
onResize is an unknown method

I'm having a hard time calling the onResize option.

This is my code snippet:
$(function () {
            $('#tableID').bootstrapTable('onResize', function (e) {
                console.log('Event:', e);
            });
});

And everytime I run the app, an error occurs in the console log:
Unknown method: onResize

**Comment by wenzhixin** [comment]
```
$('table').bootstrapTable({
  url: '',
  ...
  onResizableResize: function (e) {
    // ..
  }
})
```
