### ISSUE TITLE
Using the method of refresh URL "#" is filtered out

### ISSUE THREAD

**Issue by cchuangli** [wenzhixin/bootstrap-table#3379]
I searched in using the refresh method, the existence of "#" parameter I carried by URL, so it is filtered out.

My English is not good, so I can only say so much. In addition, I come to China and hope my problems can be solved.

**Comment by holmes2136** [comment]
It will nice if you provide your fiddle

**Comment by wenzhixin** [comment]
This is not a bug, the same with jQuery ajax: `$.get('json/data.json#test') `
![image](https://user-images.githubusercontent.com/2117018/33611213-830277d2-da08-11e7-83d4-089a977f522c.png)
