### ISSUE TITLE
Rordering / Resizing Columns

### ISSUE THREAD

**Issue by silvangithub** [wenzhixin/bootstrap-table#338]
Hi

Is it possible to reorder or resize the columns like:
http://mleibman.github.io/SlickGrid/examples/example2-formatters.html

Thanks

**Comment by saibaba03** [comment]
yeah it would be great feature to have it.

**Comment by djhvscf** [comment]
You can use the resizable extension to do that... And for reorder the columns we are working on it..

See this: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/resizable.html
and this: http://bootstrap-table.wenzhixin.net.cn/extensions/#table-resizable

**Comment by wenzhixin** [comment]
@djhvscf , can we consider add this PR as an extension: https://github.com/wenzhixin/bootstrap-table/pull/543

**Comment by djhvscf** [comment]
I think that PR is not completed.. because I try to use the code that there is but it is not working..

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/extensions/#table-reorder
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder.html
