### ISSUE TITLE
check-all was wrong with the sub-table

### ISSUE THREAD

**Issue by ttaratent** [wenzhixin/bootstrap-table#3380]
create a sub-table by the method of onExpandRow, and then set the sub-table's checkbox is true. when i'm checking all, something wrong with it.

[jsfiddle]() - a link to the reduced test case(https://jsfiddle.net/GameFF/vus5Lyov/).

I think maybe is the attribute name of the checkbox is the same. so the selector may have a wrong direction.

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/e3nk137y/17710/
