### ISSUE TITLE
点击表格某一行删除不起作用 下面是我的代码 

### ISSUE THREAD

**Issue by jyx12138** [wenzhixin/bootstrap-table#3381]
{  
      title: '操作',  
      field: 'state', 
      events: 'operateEvents', 
      align: 'center',  
      formatter: function (value, rows, index) { 
            return '<a  class="circle remove-client" removeClient(\''+rows.merchantId+'\') title="Remove">
                       '+ '<i class="fa fa-trash-o " aria-hidden="true"></i>'+
                    '</a> '+
                    '<a href="#" id="" class="circle client-refact">'+
                        '<i class="fa fa-pencil" aria-hidden="true"></i>'+
                    '</a> '; 
                }  
  
            },

 window.operateEvents = {
    'click .remove': function (e, value, rows, index) {
        console.log("111");
        var id = rows.rows.createTime; 
        $('#client-list').bootstrapTable('remove', { field: 'createTime', values: [id] }); console.log(id);
    }

数据格式如下
{"code":10001,"result":"成功","rows":{"page":1,"size":20,"total":1,"totalRecord":2,"rows":[{"merchantId":1,"account":"12222","password":"654321","accountName":"华业大","meals":3332.0,"roomss":44,"addresId":27,"address":"啊啊啊啊啊","state":1,"createTime":1506420925000,"modificationTime":1506420922000,"loginTime":1506420925000,"lastLoginTime":1506420925000},{"merchantId":2,"money":22222.0,"account":"admin","password":"123456","accountName":"华业大厦2","meals":100.0,"roomss":200,"addresId":27,"address":"地址详情000","createTime":1506420290000,"modificationTime":1506420290000,"loginTime":1506420290000,"lastLoginTime":1506420290000}]}}

**Comment by wenzhixin** [comment]
写的不对，你的 formatter 中都没有 .remove 这个类。
