### ISSUE TITLE
初始化完成后，建议增加一个事件或回调方法

### ISSUE THREAD

**Issue by ygzhang-cn** [wenzhixin/bootstrap-table#3383]
$(Table).bootstrapTable()初始化完成后，建议增加一个完成事件或回调方法，Ajax数据后便于前端后续的处理，要不监听的事件都是初始化过程中的，目前监听（onLoadSuccess）再加 timeout后处理，不是太友好...

**Comment by wenzhixin** [comment]
你可以使用 onPostBody 事件，这个事件是在表格数据渲染完成后触发。

**Comment by ygzhang-cn** [comment]
谢谢wenzhixin，很赞的表格插件，感谢你的分享与Open， 我们项目采用Ajax数据（Server分页），测试后onPostBody事件每次搜索、分页加载新数据或刷新都会再次触发，我提的那个不太成熟的意见（初始化完成后增加一个完成事件或回调方法）没有表达明确，应该是bootstrapTable插件全局初始化完成后（只要不destroy）增加一个（仅一次）初始化完成后增加一个完成事件或回调方法，实际项目中前端展现需求会遇到很多惰性加载初始化不定数量表格的情况，表格数量及布局如果首次初始化完成后有个事件或回调就会很方便UI布局进行绑定控制...

**Comment by wenzhixin** [comment]
仅一次的话可以考虑用一个变量，如 `hasInit = false`，然后在 `onPostBody` 判断  `if (!hasInit) hasInit = true`，你看这样行不行？

**Comment by ver007** [comment]
这个功能有了吗兄弟，我也很期待有这么一个功能
