### ISSUE TITLE
Hi Team,

### ISSUE THREAD

**Issue by DeveloperPK** [wenzhixin/bootstrap-table#3385]
Hi Team,

I am using server side pagination for bootstrap table. Here to fetch total number of records we are performing Count(*) from our database(10,00,000 records) which degrade the sql performance drastically. So do we have any method where we can achieve without getting Total parameter.

Thank you

**Comment by wenzhixin** [comment]
Sorry I don't know how to support server pagination without total parameter.

**Comment by DeveloperPK** [comment]
Is there any way we can show newest/oldest instead of page number details or we can show infinite scroll without getting total count ?

@wenzhixin  please share your inputs.
