### ISSUE TITLE
There is no example of that Click Edit Row in the extension

### ISSUE THREAD

**Issue by weixinxiaochengxukaifa** [wenzhixin/bootstrap-table#3388]
23/5000  
There is no example of that Click Edit Row in the extension

**Comment by weixinxiaochengxukaifa** [comment]
There is no example of that Click Edit Row in the extension，There is no code example when you download it

**Comment by wenzhixin** [comment]
This extension is in beta version, I will consider to remove it, I think you can use editable extension instead.
