### ISSUE TITLE
PDF Export Deprecations with jsPDF-AutoTable

### ISSUE THREAD

**Issue by aagp** [wenzhixin/bootstrap-table#3390]
Hi, just to point it out, tried exporting to pdf and could not do it, until a lot of mind breaking, and figure it out to change jsPDF-AutoTable, while downgrading its version finally the 2.1.0 its the very one, newer versions give me errors of deprecations.

**Comment by wenzhixin** [comment]
Please create issue in repo: https://github.com/hhurz/tableExport.jquery.plugin, thanks.
