### ISSUE TITLE
why I use formatter and editable with select in table,return Empty?

### ISSUE THREAD

**Issue by xuweiming** [wenzhixin/bootstrap-table#3392]
user bootstrap-table and bootstrap-table-edit ,formatter field and editable with select ,
formatter return Empty
 like this 
{
                field: 'onlineState',
                title: '是否在线',
                align: 'center',
                sortable: true,
                formatter: stateFormatter,
                editable: {
                    type: 'select',
                    title: '修改状态',
                    source: [{ value: "1", text: "在线" }, { value: "0", text: "已下线" }, { value: "-1", text: "未连接" }]
                }
            }

function stateFormatter(value) {
        if (value == 1) {
            //在线
            return '在线';
        } else {
            //下线
            return '已下线';
        }
   }

but when i change stateFormatter function like this 
 function stateFormatter(value) {
        if (value == 1) {
            //在线
            return "<button class=\"btn btn-success\">在线</button>";
        } else {
            //下线
            return "<button class=\"btn btn-default\">已下线</button>";
        }
    }

now return 已下线">

is this a bug?

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem and reopen this issue, thanks!
