### ISSUE TITLE
click and double click on row

### ISSUE THREAD

**Issue by francescomeloni** [wenzhixin/bootstrap-table#3393]
when i click on a row I fire a preview event and it works and when I double click on the same row I fire an edit event and it works too.
The problem is that  on teh double click i have a : click + click + double click ..so 
preview + preview + edit. 
How can i disable the single click on the double click? 
Is there an option to check the ms between clicks or something like that? 
thanks .
F.

**Comment by wenzhixin** [comment]
What do you mean/
> on teh double click

**Comment by francescomeloni** [comment]
it was "the" double click
hi, when i click on a row it triggers

$('#table_main').on('dbl-click-row.bs.table', function (e, row, $element) {
     console.log("DBL")
});

    $('#table_main').on('click-row.bs.table', function (e, row, $element) {
console.log("SINGLE")
}
and i have both message in console

**Comment by wenzhixin** [comment]
I think this answer can solve your problem: https://stackoverflow.com/questions/1067464/need-to-cancel-click-mouseup-events-when-double-click-event-detected
