### ISSUE TITLE
groupBy formatter

### ISSUE THREAD

**Issue by leipzig** [wenzhixin/bootstrap-table#3394]
I have most of my content uri-encoded. I use a formatter for these columns
```
    function decodeURIFormatter(value, row, index) {
        return decodeURIComponent(value);
    } 
```

For the groupBy rows there is no formatter, so I end up doing something like:
```
        $table.on('all.bs.table', function (e: Event) {
            $('.info td:nth-child(3)').each( function( index ){
                $(this).html(decodeURIComponent($(this).html()));
            });
        });
```

Is there a more elegant solution to applying a groupBy formatter?

**Comment by Falseee** [comment]
https://bootstrap-table.com/docs/extensions/group-by-v2/#groupbyformatter
#4109
