### ISSUE TITLE
中间只有三页，相当已经退化为上一页和下一页，中间五页或者六页比较好些吧

### ISSUE THREAD

**Issue by luwanlili** [wenzhixin/bootstrap-table#3401]

**Comment by Falseee** [comment]
If I understood this issue right (google translator - could you translate it next time @wenzhixin ?), then @djhvscf already fixed it in commit https://github.com/wenzhixin/bootstrap-table/commit/aab4f39715a7c7a6eb6c63724380c48593a54c83.

**Comment by wenzhixin** [comment]
Yes, supported this feature in the latest version.
https://bootstrap-table.com/docs/api/table-options/#paginationsuccessivelysize
https://examples.bootstrap-table.com/index.html#options/pagination-index-number.html
