### ISSUE TITLE
Using inside Qlik sense

### ISSUE THREAD

**Issue by puneetindersingh** [wenzhixin/bootstrap-table#3403]
Hey,
Used it inside Qlik sense 
Works perfectly fine, except one problem now i can't select values.
Before using this i was able to qlik on any item in the table for the software to pick it and filter data accordingly, now it does not let me click on any item and select 

Any idea why this is happening ?

Thanks

**Comment by wenzhixin** [comment]
Sorry I've never used Qlik, so label this issue `not-supported`, maybe you can provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem if possible.
