### ISSUE TITLE
Latest CDN links seem to be linking to the incorrect version

### ISSUE THREAD

**Issue by thenovices** [wenzhixin/bootstrap-table#3404]
I believe that the latest CDN links are for the incorrect version.

* https://cdn.bootcss.com/bootstrap-table/1.11.1/bootstrap-table.min.js
* https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js

Both show 1.11.0 (not 1.11.1)

https://cdn.jsdelivr.net/npm/bootstrap-table@1.11.2/dist/bootstrap-table.min.js does show 1.11.1 but the URL says version 1.11.2.

I'm guessing there might be many users who are using the latest cdn link but are actually using an older version.

**Comment by wenzhixin** [comment]
I don't know why...

**Comment by wenzhixin** [comment]
I will fix this in next version.

**Comment by benjsmi** [comment]
It's *not* just the version number that's wrong in the file!!  Indeed, the commit to provide the much-appreciated fix for #3428 is *only* on the develop branch.  [Check the source](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js) of the JavaScript file for proof.  This fix is also not in the `dist` folder [on master](https://github.com/wenzhixin/bootstrap-table/blob/master/dist/bootstrap-table.js), or even [on the v1.11.1 tag](https://github.com/wenzhixin/bootstrap-table/blob/1.11.1/dist/bootstrap-table.js) or [here](https://github.com/wenzhixin/bootstrap-table/blob/1.11.1/src/bootstrap-table.js).  

Good catch @thenovices. Thanks for fixing as usual @wenzhixin.

**Comment by timoline** [comment]
Will it be released soon?

**Comment by wenzhixin** [comment]
1.12.1 released
