### ISSUE TITLE
IE 11 Slow or Unresponsive with bootstrap-table that has 10000+ records

### ISSUE THREAD

**Issue by jedcmagenic** [wenzhixin/bootstrap-table#3405]
Hi,

We're using 1.11.0 version of the bootstrap-table loaded with about 10,000 records and we are experiencing a much degraded performance in IE 11 to a point that it's practically unusable.
Is there some kind of limit to the number of records the bootstrap-table can handle in IE?

Page behaves just fine with Chrome and FF.

I would appreciate any comments or suggestion you may have about this IE 11 issue. 

Thanks,

Jed

**Comment by wenzhixin** [comment]
Please use server side pagination instead of loaded so many records one-time, you can try use `ul`:
```
<ul>
<li>record 0</li>
...
<li>record 10,000</li>
</ul>
```
I think it is slow too.
