### ISSUE TITLE
X-editable Select with fieldFormatter

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#3406]
Short and descriptive example bug report title

I've a table where I can edit the field with x-editable.
The field **product** is a select editable field with a fieldFormatter's function (**productFormatter** in my example).
If the class of product is 1, the field have a text format and but if the class is 2 it's a select editable field.

The problem is when I select a produtc to the select editable field, they don't change the data to the data table. See the result to console.log or to alert message.

The other field **Power** and **Quantity**, when I change it, the result is save to the data table

You can see the resulta here:
http://jsfiddle.net/qxw7kcga/6/

Thank you for your help.

**Comment by wenzhixin** [comment]
In your case, you need to update the row data manually: http://jsfiddle.net/wenyi/qxw7kcga/8/
