### ISSUE TITLE
Not maintained anymore - Support abandoned

### ISSUE THREAD

**Issue by jonathangreco** [wenzhixin/bootstrap-table#3407]
Hi, it's been long time since the last answer from any contributors nor the creator itself on this amazing soft has been given.

It would be nice to have a roadmap on this module about support, pending pull requests, or new issues without any answer.

Is it the end about this ? Or it's just a dark period and in the future support will go back ?

**Comment by djhvscf** [comment]
Hi @jonathangreco 

We're planning to continue with this plugin but at this moment we don't have enough time. We think that by end of October we'll be back.

I'm sorry for any inconvenience.

**Comment by wenzhixin** [comment]
#3414
