### ISSUE TITLE
Bootstrap Table Examples cannot load JSON file

### ISSUE THREAD

**Issue by IceCrowNT** [wenzhixin/bootstrap-table#3409]
I can load table data from JSON file.
Browsers: Google Chrome, Microsoft Edge.
OS: win 10

First step: Download bootstrap-table-examples-master in https://github.com/wenzhixin/bootstrap-table-examples
Second step: Extract file
Third step: open example html files

![image](https://user-images.githubusercontent.com/32735875/31495013-00ba67c4-af80-11e7-90c0-0801aba67ca7.png)

I also tried to upload full of example file without do anything to my website, but it still not working.

**Comment by IceCrowNT** [comment]
solved

**Comment by kzlkz** [comment]
Can you tell me how did you solve this?
