### ISSUE TITLE
Column reordering through code (programatically) 

### ISSUE THREAD

**Issue by waqasjaved160** [wenzhixin/bootstrap-table#3410]
How to programmatically order the columns?

I need to reorder the columns and then save that ordering and apply that on page refresh or through some button.
I can save the columns that are ordered by a user but when I apply Bootstrap Table using those columns then only the headers are preserved but the data is retained that was initially loaded in html.

(https://github.com/wenzhixin/bootstrap-table/issues/1765)).

**Comment by jimgit** [comment]
If you use server side pagination - the server is sent the sort order field - this can be saved in a session variable for jumping to other pages to remember the sort order.

There is also an ONSORT event that you can wire up.

See the [documentation page ](http://bootstrap-table.wenzhixin.net.cn/documentation/) for details.

**Comment by waqasjaved160** [comment]
Just to be clear I am not asking about sorting but ordering of columns horizontaly. Onsort appears that it will sort data...

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-columns.html ?

**Comment by Falseee** [comment]
I close this issue because we got no response, if you still need help pls reopen this issue.
