### ISSUE TITLE
Thank you for your attention to this project

### ISSUE THREAD

**Issue by wenzhixin** [wenzhixin/bootstrap-table#3414]
Hello, first of all to apologize to all of you, this period of time I has gone through the marriage, moving, and have the first child in life, so there is no much time to maintain this open source project. 

My friend suggested that update the readme with "Not supported anymore. The new repo is "...."). I would like to thanks for all his contributions and time to the project.

For me, I love and have always been passionate about open source and GitHub. So for Bootstrap Table and other open source repos on GitHub, I do not want to give up them and I will continue to maintain and develop new repos or new features.

Thank you for your attention to this project.

**Comment by djhvscf** [comment]
@wenzhixin I really appreciate the opportunity that you gave me with this amazing project. I wish you the best with your marriage and your first baby!

Please let us know how we will continue working on this project. 

Thanks

**Comment by marccollin** [comment]
Somebody will take lead on project or do a fork?

otherwise we will need to migrate to datatable..

**Comment by djhvscf** [comment]
@marccollin  we're working on this actively
