### ISSUE TITLE
No table cells in html source code <td> ?

### ISSUE THREAD

**Issue by cborchmann** [wenzhixin/bootstrap-table#342]
Hallo,

i got bootstrap-table working. I like it!

But when viewing the html source of the page there are no table cells rendered. Is there a way to get them, because of search engines?

thanks

here is my example:

	<table class="table table-striped table-hover" data-toggle="table" data-url="query.php" data-height="400" data-sort-name="ev_start" data-sort-order="desc">

	
	<thead>
	<tr>
	<th data-field="id">ID</th>
	<th data-field="ev_name" data-sortable="true">Name</th>
	<th data-field="ev_start" data-sortable="true">Start</th>
	<th data-field="ev_ende" data-sortable="true">End</th>
	<th data-field="land_name" data-sortable="true">Location</th>
	<th data-field="ev_description">Description</th>
	</tr>
	</thead>
	</table>

**Comment by wenzhixin** [comment]
Because we js to render the table, so do not support.
