### ISSUE TITLE
sort bug on formate column

### ISSUE THREAD

**Issue by mohshraim** [wenzhixin/bootstrap-table#3420]
sort not working on formated column that not exist on original data

this example 
http://jsfiddle.net/mohshraim/pq5p4jgp/2/

where my data contain array for name and birth date, on table i added a new column called Age with formate function...
the result i sort not working on Age..

Thanks

**Comment by mohshraim** [comment]
any suggestion? work around?
thanks

**Comment by wenzhixin** [comment]
work around: http://jsfiddle.net/wenyi/pq5p4jgp/3/
Or you can use sorter column option: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-sort.html.
