### ISSUE TITLE
示例网站打不开

### ISSUE THREAD

**Issue by xiaokesong** [wenzhixin/bootstrap-table#3421]
http://issues.wenzhixin.net.cn/bootstrap-table 这个网址打不开，我下载下来也不行
1、http://rawgit.com/vitalets/x-editable/master/dist/bootstrap3-editable/js/bootstrap-editable.js （无法访问），换成 http://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js 可以，html一样

**Comment by wenzhixin** [comment]
被qiang了
