### ISSUE TITLE
How to use editable event ? It can't work for me

### ISSUE THREAD

**Issue by ihuangmx** [wenzhixin/bootstrap-table#3424]
`{
		            	field: "unit_price",
		                title: "单价",
		                editable: {
		                	onEditableSave(field, row, oldValue, $el){
		                		console.log(row);
		                	}
		                }
		            },

when i save the unit_price filed, i cant see the row on console

**Comment by ihuangmx** [comment]
@danielsharvey

**Comment by danielsharvey** [comment]
I've not used the editable extension.

Perhaps look at these references:

1. Issue https://github.com/wenzhixin/bootstrap-table/issues/1330

1. Issue https://github.com/wenzhixin/bootstrap-table-examples/issues/51

1. [Extension README](https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/editable/README.md)

**Comment by wenzhixin** [comment]
@ihuangmx the event is option of table: http://jsfiddle.net/wenyi/e3nk137y/17670/
