### ISSUE TITLE
导出类型为xlsx时，如何设置样式呢？

### ISSUE THREAD

**Issue by sergewu** [wenzhixin/bootstrap-table#3426]
现在导出xlsx时，都没有样式，我看tableExport.jquery.plugin文档中说导出xlsx就没有样式，这种有没有办法呢？

**Comment by wenzhixin** [comment]
具体的实现要看 tableExport.jquery.plugin 插件，这边这是桥接过去使用他的功能，假如没有的话请到对应的 repo 中提 issue。
