### ISSUE TITLE
Compatibility with bootstrap v4

### ISSUE THREAD

**Issue by alanlima** [wenzhixin/bootstrap-table#3428]
Hello everybody and @wenzhixin =)

I just discovered this library and found it amazingly simple and well documented. The only drawback is that I have one project that has been developing with Bootstrap v4, so I decided to start to adapt your project to Bootstrap v4.

I forked the project and created a branch in my repository to commit all the changes.

I still discovering all the features and options that this library can offer so I am migrating as soon as I see that something is broken.

The community can have a look what I'd had developed in **[my repository](https://github.com/alanlima/bootstrap-table/tree/bootstrap4-migration)**.

**What is done until now**:

* Update the class for the pagination.
* Update the class to show the drop-down to select the page size.
* Replaced the class `pull right/left` to `float right/left`.

I like to do small commits with short comments to let easy to see what had done.

Thanks =)

**Comment by wenzhixin** [comment]
Great @alanlima! What is broken?

**Comment by alanlima** [comment]
Hi @wenzhixin 

Some classes and the struct of some components are changed from v2/v3 to v4.

Like the alignment classes (pull right-left) are removed because there are duplicated with the classes float right/left.

The style for the dropdown and pagination also was changed.

I reckon that might be possible to do some few changes to let my changed compatible with the versions 2 and 3 of the bootstrap. Currently, I just got rid of the deprecated classes and used the v4 new standard, because I didn't have time to test the retro-compatibility.

I will try to do that soon so I can make a pull request.

**Comment by chrisw73** [comment]
Glyphicons no longer present in BS4.
Toolbars now have a small style, which should be setable for the bs-table toolbar aswell.

**Comment by wenzhixin** [comment]
Thanks @alanlima, I have modified the code to support bootstrap v4.0 base your code.
@chrisw73 We can use font-awesome instead.
Added example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/v4.html

**Comment by benjsmi** [comment]
Note that I would consider this *not* fixed because of #3404 -- the released, tagged, and CDN-ed v1.11.1 does not contain the fix for this problem.  However, if you [grab the code from develop branch](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js) and throw it in your project, you should be good to go using built-in buttons on Bootstrap 4.

**Comment by monaw** [comment]
I'm using Bootstrap 4 and can verify that there are problems with buttons.  Here is the default example page:

![screen shot 2018-03-06 at 12 16 57 pm](https://user-images.githubusercontent.com/18472048/37056197-82362e62-2138-11e8-95cd-0128b8955860.png)

However when I download the code and changed the bootstrap to 4.x, the example now looks like:

![screen shot 2018-03-06 at 12 17 28 pm](https://user-images.githubusercontent.com/18472048/37056232-99285c1c-2138-11e8-8986-2333fb034e18.png)

1. The button toolbars are missing
2. The grey drop down on the left shows nothing/doesn't work

Is there plan to get this working fully for Bootstrap 4.x?

**Comment by monaw** [comment]
My apologies, I just checked and I'm not using Bootstrap 4.x, sorry for the noise!  I will open another issue for my problem...

**Comment by wenzhixin** [comment]
@monaw use the latest version.
