### ISSUE TITLE
there is no fixed columns js in extention folder!

### ISSUE THREAD

**Issue by weituotian** [wenzhixin/bootstrap-table#3429]
how to find the fixed columns js extention?

does it not supported?

**Comment by robinvdijk** [comment]
It is [here](https://github.com/wenzhixin/bootstrap-table-fixed-columns)

**Comment by djhvscf** [comment]
Thanks, @robinvdijk

**Comment by weituotian** [comment]
Thanks, @robinvdijk 
why it is not in extension folder, @djhvscf

**Comment by wenzhixin** [comment]
Because the extension is beta version.
