### ISSUE TITLE
Save in variable session the number of elements

### ISSUE THREAD

**Issue by oscarruz** [wenzhixin/bootstrap-table#3430]
Hello,

I would like to save the number of elements to view in table[15, 25, 100, 200] if it's selected by user. My idea is save this value in the session variable with JS. 

Only I would need to know where and how past this value to JS to set into the current view.

Please Could you help me?

Thanks ;)

**Comment by jimgit** [comment]
Use the page-change event to save the page size

[jsFiddle page size change event](http://jsfiddle.net/jimkennelly/rbd909gu/)

**Comment by djhvscf** [comment]
You can use the [cookie extension](https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/cookie)
