### ISSUE TITLE
Click events should expose whether special keys (CTRL/ALT/META) are pressed for the event

### ISSUE THREAD

**Issue by geigel** [wenzhixin/bootstrap-table#3434]
Click events are currently exposed so the user can write custom functions do what they need based on the object clicked.

Unfortunately, the events do not also convey whether special keys such as the CTRL, ALT, and META keys are pressed during the event. Even in situations where events are wired-up using "on" such as:

`$table.on("click-row.bs.table", function(e)...`

the event object in the handler function does not expose whether those keys are pressed like one would normally see in a typical "click" event.

Requesting that this supported functionality be added to a future version. Thank you. This is a very nice table solution and I have been pleasantly surprised with how easy it is.

**Comment by wenzhixin** [comment]
#3917
