### ISSUE TITLE
Table Data Accessbility

### ISSUE THREAD

**Issue by aploessl** [wenzhixin/bootstrap-table#3435]
Not sure if this is really an issue per se, but I was trying to customize the filtering and was wondering when a table with client side pagination set up, are the hidden table rows accessible? 
For example I have a boostrap table set up with client side pagination (data-page-size = 5), and the data for the table totals 44 records. When I try to do a $('tbody > tr').length on the table I get a value of 5 and when I 'inspect' the page, it only shows the 5 rows (as designed). I was just wondering that if I wanted to look through the hidden rows, is the data stored somewhere I don't know about? I want to be able to search through the rows for partial text and perform operations on matching conditions...

**Comment by wenzhixin** [comment]
`$table.bootstrapTable('getData')`
