### ISSUE TITLE
How to add icon for export extension using fa?

### ISSUE THREAD

**Issue by tylerecouture** [wenzhixin/bootstrap-table#3436]
I'm using the [export extension](https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/export) but can't figure out how to get the icon to appear.

Here's my code:
```
<table data-toggle='table'
           data-show-columns='true'
           data-show-export="true"
           data-export-types="['csv']"
           data-icons='icons'
           data-icons-prefix='fa'
>
```
With this, I get a caret and drop down menu showing CSV.  But I', not sure how to ad the icon for the drop down list.  You docs say:

>     export: 'glyphicon-export icon-share'

How can I add this into the table's data attributes?

**Comment by wenzhixin** [comment]
[add icon for export extension using fa](http://jsfiddle.net/wenyi/e3nk137y/17639/)
