### ISSUE TITLE
bootstrap table Column options formatter function can not found the function in the component?

### ISSUE THREAD

**Issue by Christian-health** [wenzhixin/bootstrap-table#3437]
I have write a component use angular4 in angular cli project.Then i use bootstrap-table in this component . The code is like this:

```
import { ***  } from '@angular/core';


@Component({
  selector: 'app-template',
  templateUrl: './template.component.html',
  styleUrls: ['./template.component.less']
})
export class TemplateComponent implements OnInit , OnDestroy  {

   constructor() {
    const that = this;//the point is here
    that.showMessage('message');// run  correct ,can use that
  }
    columnDefs : any[] = [//defined the table column
    {
      checkbox: true
    },
    {
      title: this.translate.instant('template.template'),
      field: 'name',
      width: 200,
      sortable: true,
      events: 'operateEvents',
      formatter:  (value : any, row : any, index : any) =>  {
        that.showMessage(value);/// the point is here  ,// run  error ,can not use that    
      }
    }]

    gridOptions : {} = {//defined the table 
    pagination: true,
    escape: true,
    pageSize: 10,
    pageList: [10, 25, 50, 100],
    search: true,
    strictSearch: false,
    searchText: '',
    paginationDetailHAlign: 'left',
    paginationHAlign: 'left',
    clickToSelect: false,
    sortable: true,
    toolbar: '#toolbar-template-toolbar',
  };
  
  

 
  showMessage(value:any) {
     console.log('this.is a message ',value);
  } 
  ngOnInit() {
     $('#table-template').bootstrapTable($.extend(this.gridOptions, {
      columns: that.columnDefs,
      data: [],
    }));
  }


}
```
but the angular cli show error like this :

ERROR in /root/code/***/src/app/template/template.component.ts (106,9): Cannot find name 'that'.

The context (this) is the column Object. So to access showMessage ,i must use that .. 

but why ????? why the error occur ??? thanks for your help !!!!

# 中文的
您好，我的问题是这样的，我使用angular4在angular cli工程中写了一个组件，并且在这个组建中使用了bootstrap table。然后我想在列定义中使用一些组件中定义的函数。
![1111111](https://user-images.githubusercontent.com/29979200/32432084-c2eba14a-c29b-11e7-801e-2d4eb574b91f.jpg)
在您的文档中是这样写的formatter中的this是指向column Object.也就是说formatter函数中的this上下文是
column Object.而不是全局中的那个this。所以如果我想使用组件中的函数，那么我就要定义一个const  that = this;在构造函数中，这样在formatter函数中，我就可以使用that.functionName()来访问组建中的函数了，但是您看上面的代码，我大概就这样写的，这只是部分代码。但是angular cli报错，说不认识that这个东西。请问我是哪里做错了。我要怎样才能访问到组件中的函数那？？？？

angular  cli 报错：ERROR in /root/code/***/src/app/template/template.component.ts (106,9): Cannot find name 'that'.

**Comment by wenzhixin** [comment]
没有用过 angular4...

**Comment by ilaocai** [comment]
@Christian-health ngOnInit()中的处理放到ngAfterViewInit()试试

**Comment by alvin0618** [comment]
```
//get column def options here
getColumnDef() {
    return [//defined the table column
    {
      checkbox: true
    },
    {
      title: this.translate.instant('template.template'),
      field: 'name',
      width: 200,
      sortable: true,
      events: 'operateEvents',
      formatter:  (value : any, row : any, index : any) =>  {
        that.showMessage(value);/// the point is here  ,// run  error ,can not use that    
      }
    }]

    gridOptions : {} = {//defined the table 
    pagination: true,
    escape: true,
    pageSize: 10,
    pageList: [10, 25, 50, 100],
    search: true,
    strictSearch: false,
    searchText: '',
    paginationDetailHAlign: 'left',
    paginationHAlign: 'left',
    clickToSelect: false,
    sortable: true,
    toolbar: '#toolbar-template-toolbar',
  };
}

ngOnInit() {
     $('#table-template').bootstrapTable($.extend(this.gridOptions, {
      columns: that.getColumnDef(), //get function instead of variable directly
      data: [],
    }));
  }
```

**Comment by ChobitsSP** [comment]
`let i = 0;

function GetId() {
  return i++;
}

export function InitCallback(callback: Function) {
  const name = "btcb_" + GetId();
  window[name] = callback;
  return name;
}`

`import { InitCallback } from "src/utils/BtUtils";
const FuncKey = InitCallback(id: string) => {};
...
formatter: function(value, row) {
  return `<button type="button" onclick="${FuncKey}('${row.Id}')"></button>`;
}`

**Comment by djhvscf** [comment]
Please try again with the latest version in **dev**
