### ISSUE TITLE
请问可以动态加载列名（表头）吗

### ISSUE THREAD

**Issue by soliyell** [wenzhixin/bootstrap-table#3440]
我的表格的列数是不确定的，需要从服务端获取列的key和name
获取数据后直接填充thead后，发现tbody是在我填充之前就渲染好的，body无法正常显示
请问这种情况怎么处理呢？

**Comment by patrickpy** [comment]
1.创建表格
`<table id="table"></table>`
2.从服务器获取key，name后绑定，渲染之前要destroy
`
$('#table').bootstrapTable('destroy').bootstrapTable({
    columns: [{
        field: 'id',
        title: 'Item ID'
    }, {
        field: 'name',
        title: 'Item Name'
    }, {
        field: 'price',
        title: 'Item Price'
    }],
    data: [{
        id: 1,
        name: 'Item 1',
        price: '$1'
    }, {
        id: 2,
        name: 'Item 2',
        price: '$2'
    }]
});`

**Comment by wenzhixin** [comment]
楼上正解。

**Comment by panzhi** [comment]
这样的话后台数据添加了一个age字段，表格并不会显示不出来啊？问题还是没有解决啊！

**Comment by wenzhixin** [comment]
你的意思是后台返回什么key就显示什么？可以使用 `for (var key in object)` 去组装 `columns`。

**Comment by panzhi** [comment]
是的，但是我是在onLoadSuccess和onPreBody中处理的，这时候好像columns已经处理过了，组装后不能激活表格。就是我如果要使用for...in遍历key，要在什么阶段触发方法来处理columns呢，谢谢

**Comment by wenzhixin** [comment]
你可以使用普通的 ajax 请求，然后封装成 columns 和 data 后使用 `bootstrapTable({})` 去初始化。

**Comment by lzmzln** [comment]
> 你可以使用通用的ajax请求，然后封装成列和数据后使用`bootstrapTable({})`去初始化。

那这种方案，如何分页呢

**Comment by wenzhixin** [comment]
使用前端分页。
或者分2个请求。
