### ISSUE TITLE
Sum prices of selected column

### ISSUE THREAD

**Issue by torisoft** [wenzhixin/bootstrap-table#3442]
Hi
How can get just sum prices of selected column ?

**Comment by yangzming** [comment]
maybe use this ......$("#table").bootstrapTable('getSelections'), then count
OR you can look for footerFormatter...

**Comment by torisoft** [comment]
I know but can you take an example in jsfiddle ?

**Comment by wenzhixin** [comment]
[Get sum stars of selected column](http://jsfiddle.net/wenyi/e3nk137y/17636/)
