### ISSUE TITLE
Can pagination be added to the jump?(On the problem of selectPage)

### ISSUE THREAD

**Issue by yangzming** [wenzhixin/bootstrap-table#3443]
I  want to add the jump from the pagination. I've seen that example which is say selectPage/prevPage/nextPage, But I want to write it directly in the file, not to invoke it.

What does `BootstrapTable.prototype.selectPage` mean? and how to use?
but I don't know how to use the func of this.selectPage , like `$gotopage.off('click').on('click', $.proxy(this.selectPage, this))`??? 
how to pass params?

In the boostrap-table.js, I added some code 
Following I added some code:
`var that = this,
            html = [],
            $allSelected = false,
            i, from, to,
            $pageList,
            $first, $pre,
            $next, $last,
            $number,
            //20171108
            $gotopage,$jumppage,
            data = this.getData(),
            pageList = this.options.pageList;` //line 1305

`//20171108
        html.push('<div class="pagination goto-page"><input type="text" id="gotopage-num" value="'+this.options.pageNumber+'" min="1" style="width: 60px; height: 31px;line-height: 31px; border:1px solid #ddd;text-align: center;border-radius:5px" ><button type="button" style="height: 31px;line-height: 31px; padding:0 10px;margin-left: 5px" class="btn btn-sm btn-primary gotoPage">确定</button></div>');` //line 1491

`$pageList = this.$pagination.find('.page-list a');
            $first = this.$pagination.find('.page-first');
            $pre = this.$pagination.find('.page-pre');
            $next = this.$pagination.find('.page-next');
            $last = this.$pagination.find('.page-last');
            $number = this.$pagination.find('.page-number');
            //20171108
            $gotopage = this.$pagination.find('.gotoPage');
            $jumppage = this.$pagination.find('.goto-page input').attr('value');` //line 1502

`$pageList.off('click').on('click', $.proxy(this.onPageListChange, this));
            $first.off('click').on('click', $.proxy(this.onPageFirst, this));
            $pre.off('click').on('click', $.proxy(this.onPagePre, this));
            $next.off('click').on('click', $.proxy(this.onPageNext, this));
            $last.off('click').on('click', $.proxy(this.onPageLast, this));
            $number.off('click').on('click', $.proxy(this.onPageNumber, this));
            //20171108
            $gotopage.off('click').on('click', $.proxy(this.selectPage, this));` //line 1530

**Comment by djhvscf** [comment]
Please review this new extension: https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/page-jumpto if this does not work for you, please let us know
