### ISSUE TITLE
Problem loading data in bootstrap-table-editable

### ISSUE THREAD

**Issue by JManzanoA** [wenzhixin/bootstrap-table#3444]
Hi, I have the following issue. I generate my table dynamically, in the following way:

`newTable_al += '<table class="table table-condensed" id="asProfessor"><thead><tr>';`
`newTable_al += '<th data-field="nombre" >Usuario</th>'`
`$.each(listacriterios, function(index, value) {`
`	newTable_al += '<th data-field="criterio'+index+'" data-editable="true" >'+value["criterio"]+'</th>'`
`})`
`newTable_al += '</tr></thead></table>';`
`$('#lista').empty().append(newTable_al);`

But when loading the data, it does not show me the data (it does show me when my table is not editable) and it throws <a href="javascript:void(0)" data-name="criterio0" **data-pk="undefined"** data-value="7"></a>

And I have not found anything about how to fix data-pk = "undefined" 

How can I solve this? Thanks for your support.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
