### ISSUE TITLE
Filter on multivalued column

### ISSUE THREAD

**Issue by medwassim** [wenzhixin/bootstrap-table#3446]
hi,
how i can filter rows having multivalued column ? even use comparaison operator
example filter columns having value >= 10

filter value = 10
row 1 with column : [8,9,10,15,20]
row 2 with column : [5, 9]
row 3 with column : [10, 15]
row 4 with column : [2,18]

**Comment by wenzhixin** [comment]
Custom filter?

**Comment by medwassim** [comment]
Hi,
yes it was a custom filter. 
The best solution i found and it work , transform request and filter server side.
Thank you
