### ISSUE TITLE
表头和内容对不齐

### ISSUE THREAD

**Issue by solarisy** [wenzhixin/bootstrap-table#3448]
表头和内容对不齐
详细内容看这里：https://www.cnblogs.com/weichangyu/p/6269265.html

**Comment by wenzhixin** [comment]
你这样改也不对吧，目前在自己项目使用过程中并没有出现问题。

**Comment by chaikenao** [comment]
还是建议用resetview，如果不需要固定表头不要设置height就好了

**Comment by nn200433** [comment]
https://www.cnblogs.com/weichangyu/p/6269265.html
以这篇博客的改法,表头无法冻结
希望作者早日修复设置高度后,表头和内容无法对齐的bug @wenzhixin

**Comment by jacky1314** [comment]
我也遇到表头与表格数据错位的问题了：
现象1：
    IE11上，如果设置了 showColumns 错位问题必出。
现象2：
   Chrome上，有一定概率出现错位现象，不停刷新表格页面，出现的概率较大。

能否解决一下？目前我是在onloadSuccess里面单独写个JS，重新把表格数据的宽度修改一下解决的。

**Comment by songguoying** [comment]
我也遇到了这样的问题，版本是Chrome 63，对于有checkbox的表格，设置height后，表头和表格数据错位。没有checkbox的表格，是没有问题的。还是感谢作者的付出。 @wenzhixin

**Comment by igofind** [comment]
我的也遇到这个问题了，调试了一下，注意到我自己的表头列中有第一列【序号】不存在于返回的数据中。尝试着去掉了这个列（或者将这个列的field改成一个数据中存在的列名）就不错位了。

分析：
```
this.$body.find('>tr:first-child:not(.no-records-found) > *').each(function (i) {
            var $this = $(this),
                index = i;

            if (that.options.detailView && !that.options.cardView) {
                if (i === 0) {
                    that.$header_.find('th.detail').find('.fht-cell').width($this.innerWidth());
                }
                index = i - 1;
            }

            if (index === -1) {
                return;
            }

            var $th = that.$header_.find(sprintf('th[data-field="%s"]', visibleFields[index]));
            if ($th.length > 1) {
                $th = $($ths[$this[0].cellIndex]);
            }

            var zoomWidth = $th.width() - $th.find('.fht-cell').width();
            $th.find('.fht-cell').width($this.innerWidth() - zoomWidth);
        });
```
`var $th = that.$header_.find(sprintf('th[data-field="%s"]', visibleFields[index]));`

由于我自己加一个列（不存在于返回的数据中），这句代码匹配不到这个列，所以导致了表头错位的问题。

有问题的朋友可以参考一下，是不是列定义中出现了返回数据中不存在的列定义。

**Comment by wenzhixin** [comment]
这个问题在最新版本中已经修复了，需要升级到最新版本。

**Comment by liuyingqq123** [comment]
问题出在bootstrap-table-fixed-columns.js中

**Comment by libsgh** [comment]
···有没有不升级可以解决的办法，升级关联太大了，还要升级jquery，还有一些合并单元格的都无法使用了
我的版本是1.8.1 @wenzhixin

**Comment by wenzhixin** [comment]
低版本维护起来比较麻烦，可能要你自己看一下源码 @libsgh
