### ISSUE TITLE
表格自带的翻页按钮存在会在某些场景下导致页面跳转的问题

### ISSUE THREAD

**Issue by kobezhu** [wenzhixin/bootstrap-table#3451]
## 我遇到的问题

我在html页面上定于一个了`base`标签，例如这样：
```
<base href="/xxx/">
```
这样就设置了个相对URL解释基准。

然后页面上还带有个`iframe`标签，这个`iframe`标签引用了一个带有`bootstrap-table`的页面。

这个`bootstrap-table`表格开启了翻页。

这种场景下，**双击未选中的翻页按钮或者单击选中的翻页按钮，页面就会发生跳转**。

## 我的解决方法

我看了下翻页按钮使用的`a`标签，定义了`href="#"`，我把它改成`href="javascript:void"`，解决了问题。很有可能是`href="#"`代表意义（一个空锚点），而页面上又定了相对URL基准并且表格页面在`iframe`标签内导致的。

**然后我把全部`href="#"`都替换掉了，目前使用正常，特来告知情况。**

**Comment by Robot0111** [comment]
这个情况我最开始的时候 是客户发现的 客户点了一下分页后退出系统了0.0 其实你不用全部替换的 只需要在 active 后面加个 disabled就可以了,最好自己准备两套方案

**Comment by kobezhu** [comment]
@Robot0111 怎么可能，加disabled类只是禁用这个按钮……

**Comment by ZI-lIANG** [comment]
我也遇到了，用这个方法可以。

**Comment by wenzhixin** [comment]
#2646 #2645 #3095 
Fixed by https://github.com/wenzhixin/bootstrap-table/commit/3fd238ce8f5bde00af24289e554fe390d10f631f
