### ISSUE TITLE
invoke refresh fail when the url is invalid 

### ISSUE THREAD

**Issue by vip16** [wenzhixin/bootstrap-table#3452]
i invoke the method refresh with a url like '/***/***.json',when the json file is not exists,refresh invoke fail

**Comment by wenzhixin** [comment]
Because it will cause 404 error, you need to make sure that your URL is right.

**Comment by vip16** [comment]
为什么不能把文件不存在的情况当成没有数据的情况处理呢？比如说，我的数据源来自json文件，我有多个连接，分别对应不同的json文件，点击这些连接来刷新表格，如果某个连接的json文件不存在，调用失败感觉不太友好

**Comment by vip16** [comment]
@wenzhixin 为什么不能把文件不存在的情况当成没有数据的情况处理呢？比如说，我的数据源来自json文件，我有多个连接，分别对应不同的json文件，点击这些连接来刷新表格，如果某个连接的json文件不存在，调用失败感觉不太友好

**Comment by wenzhixin** [comment]
现在url 404 的情况，会显示没有数据吧？

**Comment by vip16** [comment]
@wenzhixin 不会呢。比如有一个包含了很多URL的集合树，对应一个table，每点击一下树上的url就调用一下refresh，更换url地址，当之前table中有数据，切换的url对应的json文件不存在时，table并不会清空，而是没有任何变化显示的还是之前的数据

**Comment by wenzhixin** [comment]
已修复。
