### ISSUE TITLE
Data formatter not working with jsfiddle and local json data?

### ISSUE THREAD

**Issue by jimgit** [wenzhixin/bootstrap-table#3453]
Can't get the formatID function to format a column.  Column data is the function name.

[JS Fiddle Example](http://jsfiddle.net/jimkennelly/e3nk137y/17304/)

I am trying to reproduce a column alignment issue but can't get the page to format a column using jsfiddle.  I believe the column alignment might be due to the format function changing the size of the field - seems to work on 0 % zoom but gets worse when magnified.  **Column alignment issue is only in Chrome and when the zoom level is less than 0.**

**Comment by wenzhixin** [comment]
You need to select this:
![image](https://user-images.githubusercontent.com/2117018/33449514-f9becf4c-d643-11e7-92b1-7527f5a7d34b.png)
http://jsfiddle.net/wenyi/e3nk137y/17630/
