### ISSUE TITLE
customSearch中调用load方法引起死循环

### ISSUE THREAD

**Issue by srcing** [wenzhixin/bootstrap-table#3454]
在自定义的customSearch方法中调用load方法将会引起死循环。

**Comment by wenzhixin** [comment]
什么情况下需要呢？能否提供 jsfiddle

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
