### ISSUE TITLE
How to insert/append row with attribute in td or tr?

### ISSUE THREAD

**Issue by supirhero** [wenzhixin/bootstrap-table#3455]
I know to insert row is use code below.
` var row = ({
                            name: "test name",
                            type: "Organisation",
                            status: 'Active',
                            action: ''
                        });
                        $('#table-home').bootstrapTable('append', row);`

But it's only add row only, how to add attribute to TR or TD  too? 
I am currently use jquery like below:
` 
  
                 var newRow = $('#table-home tr:last');
                    var firstTd = newRow.find('td:first');
                    var lastTd = newRow.find('td:last');
                    newRow.attr("data-catid",categoryName);
                    newRow.attr("data-assetdetail_id",data);
                    firstTd.attr("data-remove-link","#");
                    firstTd.attr("data-edit-link","#");
`

But that's attribute will lost after i insert/append new row again.  actually how to add attribute to new row of bootstrap-table?

**Comment by jimgit** [comment]
Use the data-formatter for the cell data and  data-row-attributes="rowAttr" - calls a function where you can customize the row attributes.

[jsfiddle - add data attribute to row and cell](http://jsfiddle.net/jimkennelly/1ucswfer/18/)

![notes marker](https://i.imgur.com/45IrHj6.png)
