### ISSUE TITLE
Clicking links with event handlers while using clickToSelect option

### ISSUE THREAD

**Issue by jonatanklosko** [wenzhixin/bootstrap-table#3457]
See #2154 for the initial discussion. Eventually, we experienced an issue with the workaround presented there. It works fine for a normal link, but turns out problematic when you want to add some event handlers to it. For example, if you'd like to show an alert once the link gets clicked, the workaround breaks it by stopping propagation of the event. A simple and reasonable solution would involve extending this condition https://github.com/wenzhixin/bootstrap-table/blob/21ae6acc49fe0229597fa33793cb09e4753fbd2a/src/bootstrap-table.js#L1869-L1875
to check if the event target is neither link nor button. This way a checkbox gets selected when the corresponding row is clicked, unless the clicked element is a link/button. Thoughts?

(I'm creating the issue as our comments on #2154 are left without any response.)

**Comment by wenzhixin** [comment]
PR is welcome @jonatanklosko
