### ISSUE TITLE
Search the column data without any spaces

### ISSUE THREAD

**Issue by sourabhshinde2007** [wenzhixin/bootstrap-table#3459]
Hello,

I am trying to find a solution to search the column data by removing spaces. 
Situation : 

I have a column with name "Status" and one of the data as "In Progress"

If i try to search as "np", i should get this data "In Progress" as if we remove spaces between this data then we have "np" in the data "In Progress".

Can anyone help me here. 

Thanks in advance.

**Comment by jimgit** [comment]
Probably better ways to do this but I accomplished this making a field on the server side where you concatonate the fields and remove the spaces -[ then use server side pagination](http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html)

Typical data row on server side looks like this:
{"id":"14",Customer:"IBM Corp",Address:"1234 New York Ave.", City:"New York",**SearchText**="14IBMCorp1234NewYorkAveNewYork"}

In Entity Framework it looks like 
return json(db.Customers.where.(**SearchText**.contains(SearchData).tolist)

Another way is to pass the SearchText to the client and [use the FILTER method.](http://issues.wenzhixin.net.cn/bootstrap-table/#methods/filterBy.html)

**Comment by djhvscf** [comment]
@sourabhshinde2007 this is not supported at this moment.
