### ISSUE TITLE
Custom data-attributes for each row lost after calling .bootstraptable()

### ISSUE THREAD

**Issue by jonayreyes** [wenzhixin/bootstrap-table#346]
I fill my table with a for-loop, filling several data-attributes properties for each row. When I call .bootstraptable(), all of them are lost

I don't think I can use data-row-attributes for this, since I have various hidden values that I want to store in data-attributes that don't come in the first parameter of the data-row-attributes function

How can I store these data-attributes?

Thanks in advance!

**Comment by wenzhixin** [comment]
Added this feature: Keep all data-* attributes when transform from normal table.
