### ISSUE TITLE
使用导出功能的时候文件大小超过1.5MB左右的时候就导不出了

### ISSUE THREAD

**Issue by wj0208** [wenzhixin/bootstrap-table#3460]
使用导出功能的时候文件大小超过1.5MB左右的时候就导不出了，显示错误，网络出错，文件小的时候没有问题，测试发现和导出行数无关，请问是JS哪里做限制了吗

**Comment by wenzhixin** [comment]
导出的问题看这里：https://github.com/huanz/tableExport#browsers，应该不会有你说的问题才对，有问题的话请到对应的 repo 中提问题。

**Comment by wj0208** [comment]
非常感谢，问题已经解决了，抱歉这么晚才回复
