### ISSUE TITLE
API for hiding multiple rows simulteneously?

### ISSUE THREAD

**Issue by eleweek** [wenzhixin/bootstrap-table#3461]
Hi,

Currently hiding one row seems to rebuild the whole table. For the "tree-column" extension this process is quite slow when table has a few hundred rows. Is there an API for hiding/showing multiple rows at a time?

**Comment by wenzhixin** [comment]
You can handle the table `data`: 
http://jsfiddle.net/wenyi/e3nk137y/17628/
http://jsfiddle.net/wenyi/e3nk137y/17629/
