### ISSUE TITLE
Problem with BootstrapTable.prototype.resetWidth

### ISSUE THREAD

**Issue by XYue** [wenzhixin/bootstrap-table#3463]
in bootstrap-table.js
BootstrapTable.prototype.resetWidth = function () {
        if (this.options.showHeader && this.options.height) {
            this.fitHeader();
        }
        if (this.options.showFooter && !that.options.cardView) {
            this.fitFooter();
        }
    };

when my script went through this function, an error showed that 'that is not define', which is in '!that.options.cardView'. Is 'that' a typo? cuz i can not find its declaration. Thanks.

**Comment by djhvscf** [comment]
Yes, this is a typo. Working on this.

**Comment by wenzhixin** [comment]
I have fixed this bug @XYue @djhvscf .
