### ISSUE TITLE
extension editable : set type dynamically from a column of the same row

### ISSUE THREAD

**Issue by fas3r** [wenzhixin/bootstrap-table#3464]
Hello,

I have a table with with three column : 
1 ) id, 
2 ) typeInput,
3 ) value

example : 

1; textarea; "this is a looooooooooooooooooooooooon msg"
2; text; "this is text"

is it possible with the editable extension to set the type of the "editable" from the value of the colum of the same row. 

thank you.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
@fas3r the editable extension does not support your feature.

**Comment by fas3r** [comment]
Hello,

Would it be possible to use the editable plugin with the onclickCells
function ?

Like create the editable when the user is clicking on the cells

Thanks by advance.

**Comment by UtechtDustin** [comment]
@wenzhixin 
Should this be a main feature of bootstrap table ?
As @fas3r already asked, he can implement it his self.

**Comment by djhvscf** [comment]
I think this needs to be implemented by the developer.
