### ISSUE TITLE
how to disable the“prev” or “next” pagination button?

### ISSUE THREAD

**Issue by pangniur** [wenzhixin/bootstrap-table#3467]
when there is no prev page or next page ，
1、when current page is 1 ，then there is no prev page.
2、when current page is the last page ，then there is no next page.
this moment ， i want to disable the“prev” or “next” pagination button，
i just want to get a solution of code logic .

![bttable](https://user-images.githubusercontent.com/21232662/33264783-fd95d698-d3a9-11e7-9400-936a7ab42249.png)

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
`paginationLoop: false` or `data-pagination-loop="false"` can solve your problem.
http://jsfiddle.net/e3nk137y/17627/

**Comment by pangniur** [comment]
thanks very much ~
