### ISSUE TITLE
change cell background color via json

### ISSUE THREAD

**Issue by alejandrofm** [wenzhixin/bootstrap-table#3471]
Hi! I'm loading a table via json, every row and every colum have a bussiness logic that determines the color. I was thinking doing it in the remote (ajax) call, so the json returns value and color.
Is any way to style the cell color like this? If now, have any idea?
Thanks!

**Comment by jimgit** [comment]
Use the cell-style as shown in [jsfiddle](http://jsfiddle.net/jimkennelly/30sx4h3t/423/)

You can do your logic on the client side as shown in the example, or you can create fields in your json data on the server side such as "name_color" and access that data using the row variable in your cell-style function.

function nameCellStyle(value, **row**, index) {


    return {

      css: {
        **"color": row.name_color,**
        "font-size": "50px"
      }
    };

}
