### ISSUE TITLE
How to change text-input value after page is loaded?

### ISSUE THREAD

**Issue by CodeCannibal** [wenzhixin/bootstrap-table#3473]
Hi together,

let's say I've got an HTML page with an table. Since there are several columns, I want to put a filter(-search) input field in the table's header.

So I made something like this:

```
<table id="myTable" class="bootstrap-table table-borderless table table-hover" 
       data-show-filter="true" data-toggle="table" data-search="false" data-filter-control="true" 	
	   data-show-export="false"  data-sort-name="date"	data-sort-order="asc" data-pagination="true"	
	   data-click-to-select="true" data-toolbar="#toolbar">

	<thead>
		<tr>
			<th data-field="field1" data-filter-control="input" data-sortable="true"> 
			<th data-field="field2" data-filter-control="input" data-sortable="true"> 
			<th data-field="field3" data-filter-control="input" data-sortable="true"> 
		</tr>
	</thead>
	<!-- here comes the rows -->
</table>
```

At the end of the page, I added an JavaScript, which changes the value of "field1":

```
<script type="text/javascript">
	jQuery(document).ready(function($) {
        $(".bootstrap-table-filter-control-field1").val("myFilterValue");
    });
</script>
```

After loading the page, the text input box changes it's value to "myFilterValue" - but no filter process has been activated. 
Why is that? Any suggestions?

**Comment by jimgit** [comment]
Or try the data-search-text property or resetSearch method - note the original search text is set to 'boot' but when the button is clicked, the new search text is password  - See - [jsfiddle - set initial search then change it with button click](http://jsfiddle.net/jimkennelly/e3nk137y/17562/)

**Comment by wenzhixin** [comment]
Have you solved your problem? @CodeCannibal

**Comment by CodeCannibal** [comment]
Unfortunately not. 
The examples won't help a lot, since there is only one(!) search field for the complete table.
Maybe I wasn't precise enough with my problem's description.
So I edited it - and as you can see there is more than one input field - and it is not placed (as in the example) in the table body. 
Maybe this makes things a little bit clearer ;)

**Comment by jimgit** [comment]
Did you try the FILTER CONTROL extension - see [Filter Control Extension](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html)

**Comment by wenzhixin** [comment]
Close this issue because there are about 2 years if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
