### ISSUE TITLE
Export data without hidden columns - bootstrap table

### ISSUE THREAD

**Issue by innoctive** [wenzhixin/bootstrap-table#3475]
Hi - I'm trying to export my table to csv format but it's showing me hidden columns also, how can we download without hidden columns ? Please assist.

Code snippets as below 
1) Bootstrap Table with data-show-export=true
`<table id="mybookings" class="table table-hover table-condensed" 
			                    data-toggle="table"
			                    data-toolbar="#toolbar"
			                    data-show-export="true"`
2) JS Function
`$(function () {
			var $table = $('#mybookings');
		    $table.bootstrapTable('refreshOptions', {
		      exportDataType: 'all'
		    });
		});`

This is working but it's also exporting the hidden columns in csv, would like to avoid that. Appreciate any help.

Thanks,
Deepesh

**Comment by wenzhixin** [comment]
Read the [docs of tableExport.jquery.plugin](https://github.com/hhurz/tableExport.jquery.plugin#options-default-settings).

**Comment by twhetzel** [comment]
You can ignore columns in the export using:
` ignoreColumn: ['my_column']`

Where the value of 'my_column' can either be the column name or index position.
