### ISSUE TITLE
Expand scrollTo function to scroll to specific row

### ISSUE THREAD

**Issue by ynnckstrm** [wenzhixin/bootstrap-table#3476]
What I'd like to suggest is to expand the **scrollTo** function to support to scroll to a _specific row_ in the table, maybe by using the unique Identifier.
Currently the **scrollTo** function only supports scrolling to a set amount of pixel in the row, or to the bottom. It would be nice to be able to use something like: 
`$('#table').bootstrapTable('scrollTo', uniqueId);`

I really like using Bootstrap-Tables, its a very convenient way to create good looking tables with a broad range of features.
I am not experienced using GitHub and want apologize if I broke any of the submitting rules.

Best wishes,
Yannick.

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/wenyi/yf0u35jL/4/ Any PR is welcome

**Comment by pchaganti** [comment]
👍
