### ISSUE TITLE
class is changing on column sort

### ISSUE THREAD

**Issue by alejandrofm** [wenzhixin/bootstrap-table#3479]
Hi, Im loading the table via ajax, for one of the fields I set an ID so it's easier to change the class later, like this:
`'<a class="like" href="javascript:void(0)" title="Like"><i id="heart'.$row['id'].'" class="fa fa-heart"></i></a>';`

Then, on cell click I change the class
`			$('#publicaciones').on("click-cell.bs.table", function(e, field, value, row, $element) {
				if(field=='top'){
					if ($("#heart"+row.id).attr('class')=="fa fa-heart-o"){
						$("#heart"+row.id).removeClass();
						$("#heart"+row.id).addClass('fa fa-heart')
					}
					else{
						$("#heart"+row.id).removeClass();
						$("#heart"+row.id).addClass('fa fa-heart-o')
					}
					//window.alert(value);
				}
			})`

That works perfectly, the problem is that when I click on one of the data-sortable="True" columns the classes reset.
is that a bug or I'm doing something wrong?
Thank you!!

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by jimgit** [comment]
Set the field in a -data-formatter so the data will be reformatted after sort or filter, etc

[See this fiddle based on the format function](http://jsfiddle.net/jimkennelly/3pbphyqs/)

**Comment by djhvscf** [comment]
@alejandrofm please check the example provided by @jimgit. If this is not solving your problem, then please open a new issue with an example.
