### ISSUE TITLE
Fixed column and detail view issue

### ISSUE THREAD

**Issue by thomas-nguyen-3** [wenzhixin/bootstrap-table#3480]
Fixed column extension does not seem to work with "detail view" feature.

I used "Fixed column" extension to freeze the first 2 column for example
When i add "Detail View" ( where I can click on the plux (+) sign to view extra detail), the detail view will get overlapped each other and shifted down, also the fixed column will cover the detail view area.

fiddle link
http://jsfiddle.net/e3nk137y/17730/

basically these table tag does not seem to function together:
       data-detail-view="true"
       data-fixed-columns="true"
       data-fixed-number="2"

Example: 
<code>
<table data-toggle="table" 
       data-url="/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data1/" 
       data-height="200"
       data-detail-view="true"
       data-fixed-columns="true"
       data-fixed-number="2">
    <thead>
    <tr>
        <th data-field="name">Name</th>
        <th data-field="stargazers_count">Stars</th>
        <th data-field="forks_count">Forks</th>
        <th data-field="description" class="description">Description</th>
    </tr>
    </thead>
</table>
</code>
I would be nice if they work together :)  ! . thanks,

**Comment by Tenfleques** [comment]
I also realised that for fixed columns, if the table width is less than the parent such that no x-scrolling is needed, the table breaks and behave weirdly if screen size changes. You can look at that, use the fixedColumns extension, then change screens in dev mode where larger screens won't need scrolling.

**Comment by Tenfleques** [comment]
`function buildTable($el, data, columns) {             
            loadTable();
            $(window).resize(loadTable);
            function loadTable(){
                var fixedNumber = 0;  
                draw(fixedNumber);              
                if($el.parent().width() < $el.width()){
                    fixedNumber = 1;
                    $el.bootstrapTable('refreshOptions', {fixedNumber: fixedNumber});
                }
                function draw(fixedNumber){
                    $el.bootstrapTable('destroy').bootstrapTable({
                        columns: columns,
                        data: data,
                        fixedColumns: true,
                        fixedNumber: fixedNumber,
                        classes: "table "
                    })
                }                
            }         
        }`
this was my way around the issues, would be lovely if it's extension could ship with the functionality already.
