### ISSUE TITLE
Nested Tables - How to use them?

### ISSUE THREAD

**Issue by BackStap** [wenzhixin/bootstrap-table#3482]
Hi Guys, i'm trying to do this
https://jsfiddle.net/dabros/vuLj1bcb/
https://jsfiddle.net/myvykf24/1/

At my .html file, but when i try, nothing happens
0 erros at my console
http://prntscr.com/hk68y7
Full loaded
http://prntscr.com/hk692i

I've tryied with other examples successfully, but not with this
Any ideas?
Thanks! :)

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your html, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
