### ISSUE TITLE
Need example ajaxOptions

### ISSUE THREAD

**Issue by xyluet** [wenzhixin/bootstrap-table#3483]
Need example for ajaxOptions.

I'm using server side pagination

I implement `refreshOptions` method to change `ajaxOptions` to override `success` options for ajax call.

But it's not working.

Another example to assign `url` for ajax call but using `ajaxOptions`

https://jsfiddle.net/fuxd7yy8/

**Comment by wenzhixin** [comment]
Why don't you use `responseHandler`?

**Comment by mygitnote** [comment]
No No No,what you do will cause hair two different request, an ajax, a refreshOptions, choose between the two

**Comment by wenzhixin** [comment]
Sorry I don't know what you want, maybe this example will help: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-ajax.html

**Comment by xyluet** [comment]
sorry for misunderstanding.

https://jsfiddle.net/ogyf3zxo/
look at the sample above.

how do i implement success, error, async, beforeSend, or anything in [http://api.jquery.com/jquery.ajax/](url) ?

I read the doc there is `ajaxOptions`. But i already tried something like this
https://jsfiddle.net/fuxd7yy8/1/
isn't working.

My question is `ajaxOptions` is for what i mean above ?

**Comment by wenzhixin** [comment]
Example: http://jsfiddle.net/wenyi/e3nk137y/17803/

**Comment by xyluet** [comment]
ok i got it.  ajaxOptions only for other options that bootstrap table does not define.

so i can't do somehing like this ? http://jsfiddle.net/uggo5mgf/ . right?

because it will be very useful to fully custom for server side pagination

**Comment by wenzhixin** [comment]
Yes, it does not support fully custom.
But I think you can use ajax to do what you want: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-ajax.html
