### ISSUE TITLE
请问如何获取columns，即表头title以及对应的data-field属性

### ISSUE THREAD

**Issue by tenglongwentian** [wenzhixin/bootstrap-table#3484]
请问如何获取columns，即表头title以及对应的data-field属性

**Comment by wenzhixin** [comment]
`$('#table').bootstrapTable('getOptions').columns`

**Comment by tenglongwentian** [comment]
谢谢，晚上回去试一下，昨天通过获取显示列取到的title以及data-field属性，$.each遍历过滤title。
