### ISSUE TITLE
点击删除最后一页的数据再调用刷新事件，但是数据刷新不了

### ISSUE THREAD

**Issue by hcraderGH** [wenzhixin/bootstrap-table#3488]
出现的现象：当点击删除某一页的全部数据后，调用refresh刷新，分页条最后页码-1，刷新正常，但是此页的数据不显示；当点击刷新按钮后，数据则可以显示了。
这是什么原因呢？导致refresh不了数据。

**Comment by wenzhixin** [comment]
麻烦提供下 jsfiddle 例子，谢谢。

**Comment by hcraderGH** [comment]
已经解决了，是自己程序逻辑有问题，并不是控件问题
