### ISSUE TITLE
Bootstrap 4 support when ?

### ISSUE THREAD

**Issue by Falseee** [wenzhixin/bootstrap-table#3491]
When the table supports bootstrap 4 ?
The fork is inaktive i think (last commit 2 month ago).
It cant be so hard to migrate :/

bootstrap 4 is already in beta (since 4months!).

**Comment by djhvscf** [comment]
See this https://github.com/wenzhixin/bootstrap-table/commit/46e6774a9283e0e43d967eac4881330cfab22061we're working on this repo actively again

**Comment by wenzhixin** [comment]
#3428
