### ISSUE TITLE
XLSX

### ISSUE THREAD

**Issue by rfossella** [wenzhixin/bootstrap-table#3492]
Hello,

I'm still unsure how to export an XLSX version of the table.  I have the latest published version of  bootstrap-table-export.js and all other exports work fine.  There is no option for XLSX

I tried to modify the code to this:
```
var TYPE_NAME = {
    json: 'JSON',
    xml: 'XML',
    png: 'PNG',
    csv: 'CSV',
    txt: 'TXT',
    sql: 'SQL',
    doc: 'MS-Word',
	excel: 'MS-Excel',
	xlsx: 'MS-Excel (OpenXML)',
    powerpoint: 'MS-Powerpoint',
    pdf: 'PDF',
  };

  $.extend($.fn.bootstrapTable.defaults, {
    showExport: false,
    exportDataType: 'all', // basic, all, selected
    // 'json', 'xml', 'png', 'csv', 'txt', 'sql', 'doc', 'excel', 'powerpoint', 'pdf'
    exportTypes: ['json', 'xml', 'csv', 'txt', 'sql', 'excel', 'xlsx'],
    exportOptions: {},
  })
```

Export **Failed to execute 'createObjectURL' on 'URL'**

My scripts are loaded as:
```
<script src="bootstrap-table.min.js"></script>
<script src="tableExport/libs/js-xlsx/xlsx.core.min.js"></script>
<script src="tableExport/tableExport.js"></script>
<script src="bootstrap-table-export.js"></script>
```

Is there something else I should be loading or another version of your code available?

Thanks for your help!

Rob

**Comment by rfossella** [comment]
Is this still an active board?

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by rfossella** [comment]
Hi.  Is there a way to export ALL table rows and not just the visible one - e.g. the first 50 shown in the table?

**Comment by wenzhixin** [comment]
Example: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by rfossella** [comment]
Hi.  That example only exports the **visible** rows in the table.  Is there an option to export the entire contents - e.g. I have 700 rows.  I need to export all the rows.

**Comment by wenzhixin** [comment]
This option can solve your problem: `exportDataType: 'all'`.

**Comment by rfossella** [comment]
Thanks for your response but this does not do it.  It only exports the visible rows.
`$('#my_table').tableExport({type:'excel', exportDataType: 'all',  worksheetName: 'MyDataSheet'});`

Is this not syntactically correct?

**Comment by wenzhixin** [comment]
Docs:
https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/export
https://github.com/hhurz/tableExport.jquery.plugin

**Comment by rfossella** [comment]
Yes, I looked through those docs many times.   It's just unclear.  I also tried the following, again getting only visible rows exported:
`$('#my_table').bootstrapTable({exportDataType: 'all'}).tableExport({type:'excel',  worksheetName: 'MyDataSheet'});`

FYI: The following gives me ALL JSON: `$('#my_table').bootstrapTable('getData')`

Anyway, thanks for your help.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem!

**Comment by halcon884** [comment]
> 
> 
> Hi. Is there a way to export ALL table rows and not just the visible ones - e.g. the first 50 shown in the table?

You can select All from the dropbox to show all records and then click export data
