### ISSUE TITLE
every  example in jsfiddle.net  can't not run well.

### ISSUE THREAD

**Issue by davidway** [wenzhixin/bootstrap-table#3494]
when i try to run example in  jsfiddle in ( http://jsfiddle.net/wenyi/e3nk137y/11/ )
i get these  problems  in every browser.
![image](https://user-images.githubusercontent.com/6014971/33814474-565eae88-de65-11e7-9d22-e30713343a4c.png)

(https://rawgit.com/wenzhixin/bootstrap-table/master/src/bootstrap-table.css ) is miss

BTW,i'm chinese

**Comment by wenzhixin** [comment]
可以呀，应该是你的网络被Q了。。。

**Comment by davidway** [comment]
要翻墙吗？

**Comment by davidway** [comment]
开了全局代理确实可以了，这国内的墙好高啊！！！！！

**Comment by wenzhixin** [comment]
有个代理列表的。
