### ISSUE TITLE
is there a demo for entery key for search ?

### ISSUE THREAD

**Issue by 15838028035** [wenzhixin/bootstrap-table#3495]
is there a demo for entery key for search ?

**Comment by jimgit** [comment]
Here's one - [jsfiddle search on enter](http://jsfiddle.net/jimkennelly/vymq0gx9/2/)

Top grid has search-on-enter-key enabled - bottom grid is disabled.

**Comment by 15838028035** [comment]
@wenzhixin , i have see it,   i use bootstrap-table , use by script style,   how can i config a key  to make search on entery event ?

**Comment by 15838028035** [comment]
@weixin  
style may be like this 
 $('#tb_departments').bootstrapTable({
            url: '/Home/GetDepartment',         //请求后台的URL（*）
            method: 'get',                      //请求方式（*）
            toolbar: '#toolbar',                //工具按钮用哪个容器
            striped: true,                      //是否显示行间隔色
            cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
            pagination: true,                   //是否显示分页（*）
            sortable: false,                     //是否启用排序
            sortOrder: "asc",                   //排序方式
            queryParams: oTableInit.queryParams,//传递参数（*）
            sidePagination: "server",           //分页方式：client客户端分页，server服务端分页（*）
            pageNumber:1,                       //初始化加载第一页，默认第一页
            pageSize: 10,                       //每页的记录行数（*）
            pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
            search: true,                       //是否显示表格搜索，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
            strictSearch: true,

**Comment by wenzhixin** [comment]
看文档

**Comment by 15838028035** [comment]
已经添加了这个属性, searchOnEnterKey:true, 在其他文本框中回车, 不会执行查询, 是否和服务器分页有关?

**Comment by wenzhixin** [comment]
应该没关系，其他文本框？

**Comment by 15838028035** [comment]
回车不会自动查询


发自我的 iPhone

**Comment by wenzhixin** [comment]
还有问题的话提供下jsfiddle 看看
