### ISSUE TITLE
bootstrap-table to support angular >=4

### ISSUE THREAD

**Issue by shopsoy** [wenzhixin/bootstrap-table#3496]
Hi,
Can you advance if its in the road map to be able to use this lib in Angular >= 4.

I now that this lib supports AngularJs but I need to know if will suppor angular.io (>= 4).

Thanks

**Comment by wenzhixin** [comment]
Sorry, we don't consider to support Angular4, but any PR is welcome.

**Comment by Eviato** [comment]
The support for Angular >=4 would be awesome. If I've some times I may take a look to provide a component bootstrap-table but it might take time.

**Comment by pipiscrew** [comment]
https://www.pipiscrew.com/2019/06/from-wenzhixin-bootstrap-table-to-angular-akveo-ng2-smart-table/
