### ISSUE TITLE
Data formatter

### ISSUE THREAD

**Issue by diego3g** [wenzhixin/bootstrap-table#35]
Hello,

The "data-formatter" has a bug. If i have "data-formatter" in one column, no matter what, and i change the visible columns in the "data-show-columns" menu, some columns changes the format with the "data-formatter" even without the "data-formatter" property.

**Comment by k--andrey** [comment]
@wenzhixin 
link http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#via-javascript-table
Does not work any more.
Please, can you provide example?

**Comment by wenzhixin** [comment]
Examples here: http://issues.wenzhixin.net.cn/bootstrap-table/ @k--andrey
