### ISSUE TITLE
Create Custom Row and Columns

### ISSUE THREAD

**Issue by cheizer** [wenzhixin/bootstrap-table#3500]
How do I create a custom row in using bootstrap-table with multiple values in each column? 

Any help would be much appreciated. Also, I can reorder/reformat the data if needed.

Example layout:
<table>
	<tr>
		<th>Info</th>
		<th>Platform</th>
		<th>User</th>
	</tr>
	<tr>
		<td>
			{{DeviceName}}<br>
			{{DeviceOS}}<br>
		</td>
		<td>
			{{DevicePlatform}}<br>
			{{DeviceModel}}<br>
			{{DeviceVersion}}<br>
		</td>
		<td>
			{{UserName}}<br>
			{{UserLoginName}}<br>
			{{UserEmail}}<br>
		</td>
	<tr>
</table>

Example Data:
`{
	rows: [
		{
			'DeviceName': 'BOB Phone',
			'DeviceOS': 'NA',
			'DevicePlatform': 'NA',
			'DeviceModel': 'NA',
			'DeviceVersion': 'NA',
			'UserName': 'NA',
			'UserLoginName': 'NA',
			'UserEmail': 'NA'
		},
		{
			'DeviceName': 'SUE Phone',
			'DeviceOS': 'NA',
			'DevicePlatform': 'NA',
			'DeviceModel': 'NA',
			'DeviceVersion': 'NA',
			'UserName': 'NA',
			'UserLoginName': 'NA',
			'UserEmail': 'NA'
		},
	]
}`

**Comment by jimgit** [comment]
Here is a [fiddle ](http://jsfiddle.net/jimkennelly/ax51z937/) - note how the formatter for the second column combines two of the fields in the same column.

![image](https://user-images.githubusercontent.com/1921941/33915882-854ac310-df6b-11e7-9494-f5d192e56132.png)

**Comment by cheizer** [comment]
Awesome, thanks!
