### ISSUE TITLE
Tried newest version, so i could try it out with Bootstrap 4

### ISSUE THREAD

**Issue by jakobdo** [wenzhixin/bootstrap-table#3502]
When "loading" the page, this message keeps hanging i upper left corner:

Loading, please wait...

Data is not loaded remote. Just a plain html table with data inside.

And i'm unsure how to get rid of this.

Any one ?

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
Example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/v4.html

**Comment by jakobdo** [comment]
https://jsfiddle.net/8bn9zpga/

**Comment by wenzhixin** [comment]
https://jsfiddle.net/wenyi/8bn9zpga/4/
Css file is necessary: http://bootstrap-table.wenzhixin.net.cn/getting-started/

**Comment by jakobdo** [comment]
Perfect, thanks. How could i forget that.. ;)
