### ISSUE TITLE
method "updateRow" doesn't work when "sortTable" is "desc"

### ISSUE THREAD

**Issue by blurstream** [wenzhixin/bootstrap-table#3503]
when you create an ordered table, "updateRow" function doesn't seems to work as expected updating records that aren't corresponding with index provided.

you can check this behavior here: [jsfiddle](https://jsfiddle.net/svmLjyvj/4)

**Comment by jimgit** [comment]
Take a look at [updateRow](http://issues.wenzhixin.net.cn/bootstrap-table/#methods/updateRow.html)

Click on the red diagonal bar on top right side to see the code

**Comment by blurstream** [comment]
yes, it works but if I am not wrong that isn't an ordered table

**Comment by djhvscf** [comment]
Please see this fiddle http://jsfiddle.net/e3nk137y/17955/ 

Could you please what is the expected behaviour for you?

**Comment by blurstream** [comment]
sure, I expect row with id 3 is updated, but it seems third row was updated.
if you try with `index : 1` neither the line with id 1 and the first line (i am assuming index starts at 0) are updated.
let me know if my explanation is unclear

**Comment by wenzhixin** [comment]
In your case, I think you can use `updateByUniqueId` method to solve your problem.

**Comment by djhvscf** [comment]
No, updateRow works with the index but Id. If you want to use id please see updateByUniqueId method

**Comment by blurstream** [comment]
thank you for your answers! if it works with indexes too it should be fine, actually in that example I can't understand which indexed row is updated by the method

**Comment by wenzhixin** [comment]
https://jsfiddle.net/wenyi/svmLjyvj/6/ this example may can help you understand

**Comment by blurstream** [comment]
it was my fault! i am sorry... it works like a charm! the fact is table gets automatically sort as soon as a row is updated
