### ISSUE TITLE
你们没有这个问题吗？官网要访问很久才能加载，基本访问不成功。

### ISSUE THREAD

**Issue by york3** [wenzhixin/bootstrap-table#3507]
![image](https://user-images.githubusercontent.com/33745473/34095742-90049988-e40d-11e7-9cb0-ccb09c4088f1.png)
@相关人员 可以解释下吗？

**Comment by york3** [comment]
![image](https://user-images.githubusercontent.com/33745473/34095792-cb536d5c-e40d-11e7-8c8f-9ecce2c532d3.png)
补充相关图片。。压根没法用。。
![image](https://user-images.githubusercontent.com/33745473/34095804-d9befdf2-e40d-11e7-9589-3429591b9a39.png)

**Comment by wenzhixin** [comment]
应该是墙的问题，在 #3227 中改。
