### ISSUE TITLE
data-height

### ISSUE THREAD

**Issue by YuppyChen** [wenzhixin/bootstrap-table#3508]
html=======>
<table id="exampleTableFromData" data-mobile-responsive="true">
                                <thead>
                                    <tr>
                                        <th data-field="state" data-checkbox="true"></th>
                                        <th data-field="Tid" data-sortable="true">ID</th>
                                        <th data-field="First" data-sortable="true">姓名</th>
                                        <th data-field="sex" data-sortable="true">性别</th>
                                    </tr>
                                </thead>
                            </table>

js============>
$('#exampleTableFromData').bootstrapTable({
        url: "js/json/table_base.json",
        height:100,//根据需求，开发人员自定义高度
        pagination : true,//是否显示分页（*）
        pageNumber: 1,
        pageSize : 10,
        pageList : [ 10, 20, 30 ]
    });

控制台报错信息：
bootstrap-table.js:2335 Uncaught TypeError: Cannot read property 'prop' of undefined
    at BootstrapTable.resetView (bootstrap-table.js:2335)

去掉height属性就不会报错，求解

**Comment by wenzhixin** [comment]
可以提供下 jsfiddle 吗？
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by YuppyChen** [comment]
https://jsfiddle.net/yuppy/j5wboues/8/

**Comment by YuppyChen** [comment]
发错了，这个链接才是
https://jsfiddle.net/yuppy/j5wboues/9/

**Comment by wenzhixin** [comment]
第2个问题监听 tab 的 shown 事件，然后调用 `resetView` 方法就可以了：https://jsfiddle.net/wenyi/j5wboues/10/

**Comment by YuppyChen** [comment]
/* 问题一：设置了height属性的时候，会出现以下错误
bootstrap-table.min.js:8 Uncaught TypeError: Cannot read property 'prop' of undefined
    at o.resetView (VM245 bootstrap-table.min.js:8) */


/* 问题二:bootstrap配合使用bootstrap的tabs组件时候，切换到表格2的时候表格会自动往下顶。 */


/* 问题一、当我去掉bootstrap-table-mobile.min.js的时候就不会报错。
   但是不加上这个文件，窗口变化时候，表格的theader和tbody的数据就不会对齐*/
代码演示：
https://jsfiddle.net/j5wboues/14/
