### ISSUE TITLE
table 的row显示json数据{"a":"b"},这样的格式时加上validate这个属性，前端自动转义了，请问是啥问题？

### ISSUE THREAD

**Issue by testerSunshine** [wenzhixin/bootstrap-table#3510]
<img width="200" alt="qq20171221-161710 2x" src="https://user-images.githubusercontent.com/20162049/34246705-a328a7a2-e66a-11e7-8a4f-b2744cc96b95.png">
<img width="932" alt="qq20171221-161720 2x" src="https://user-images.githubusercontent.com/20162049/34246708-a3e88892-e66a-11e7-82fe-8ae71949ec3d.png">

**Comment by wenzhixin** [comment]
请提供 jsfiddle 例子。
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by testerSunshine** [comment]
代码贴给你吧，没注册那个
` <div class="faq-content col-sm-12 col-md-12">
            <div class="row">
                <div class="table-box col-sm-12 col-md-12">
                    <table id="demo-table">
                    </table>
                </div>
            </div>
        </div>`
`function initTable(){
    $("#demo-table").bootstrapTable('destroy');
    $('#demo-table').bootstrapTable({
        method:'get',
        dataType:'json',
        contentType: "application/json;charset=UTF-8",
        cache: false,
        width:$(window).width(),
        minimumCountColumns:2,
        uniqueId: "id",                             //每一行的唯一标识，一般为主键列
        exportDataType: 'all',
        checkbox: true,
        pagination: true,
        pageNumber:1,                       //初始化加载第一页，默认第一页
        pageSize: 10,
        columns: [
            {
                checkbox: true
            },
            {
                field : 'test',
                title : 'ID',
                align : 'center',
                valign : 'middle',
                validate: function (value) {
                if (!$.trim(value)) {
                    return '不能为空';
                }
            }
                sortable : true
            }
        ],
    responseHandler:function (res) {
            {"data": [{"test": {"a": "b"}}]
}
        },
    });
}`

**Comment by wenzhixin** [comment]
不用注册的，代码贴给我我还要去复现你的问题啊。

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
