### ISSUE TITLE
导出带有子表的数据时，不该导出的导出了，不展开的导不出。

### ISSUE THREAD

**Issue by citystory** [wenzhixin/bootstrap-table#3513]
![tim 20171223235118](https://user-images.githubusercontent.com/20102694/34320904-f9910344-e83d-11e7-9066-60b59976cbf2.png)
![tim 20171223235308](https://user-images.githubusercontent.com/20102694/34320905-f9c542bc-e83d-11e7-8bd6-252c4aadc643.png)
如上面两图，上图是导出的结果，下图是应该导出的样子，并且在有明细表的情况下，如果没有点击展开是导出不了的。

**Comment by wenzhixin** [comment]
不支持导出带子表的表，这种情况请用后台去实现导出。
