### ISSUE TITLE
OnclickRow 事件和 editable 行事件冲突怎么解决

### ISSUE THREAD

**Issue by liuweiGit** [wenzhixin/bootstrap-table#3514]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by wenzhixin** [comment]
最新的 develop 应该已经修复了。

**Comment by liuweiGit** [comment]
您好,今天下载了最新的更新包,发现问题依然存在.

**Comment by wenzhixin** [comment]
对某一列进行设置就可以 ：http://jsfiddle.net/wenyi/e3nk137y/18030/

**Comment by liuweiGit** [comment]
{field: 'target', title: '目标字段列表'},
          {
            field: 'compare', title: '对应关系', clickToSelect: false, formatter: function (value, row, index) {
              if (fieldRelations[row.target] === row.target) {
                return row.compare = '相等';
              }
              return value;
            },
            editable: {    //编辑事件
              type: 'select',
              source: [
                {value: '相等', text: '相等'},
                {value: '求和', text: '求和'},
                {value: '起始值', text: '起始值'},
                {value: '计数', text: '计数'}
              ]
            },
          },

onClickRow: function (row) {  //单机行事件
          timer && clearTimeout(timer);
          timer = setTimeout(function () {
            var selectedData = getTableSelectedOneData('#source-filed-table');
            if (selectedData) {
              fieldRelations[row.target] = selectedData.source;
              $('#source-filed-table').bootstrapTable('refresh', {silent: true});
              $('#relation-field-table').bootstrapTable('refresh', {silent: true});
            }
          }, 300);
          return false;
        },

我按您所说的配置了,但是没效果,这是我的源代码,

**Comment by wenzhixin** [comment]
有问题的话麻烦提供下 jsfiddle。

**Comment by liuweiGit** [comment]
您好此bug还是存在的,
$(function () {
    $('#table').bootstrapTable({
        idField: 'name',
        url: '/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data1/',
        clickToSelect: true,
        columns: [{
            field: 'state',
            checkbox: true
        }, {
            field: 'name',
            title: 'Name'
        }, {
            field: 'stargazers_count',
            title: 'Stars',
            clickToSelect: false,
            editable: {
                type: 'text'
            }
        }, {
            field: 'forks_count',
            title: 'Forks',
            clickToSelect: false,
            editable: {
                type: 'text'
            }
        }, {
            field: 'description',
            title: 'Description',
            clickToSelect: false,
            editable: {
              type: 'select',
              source: [
                {value: '相等', text: '相等'},
                {value: '求和', text: '求和'},
                {value: '起始值', text: '起始值'},
                {value: '计数', text: '计数'}
              ]
            },
        }],onClickRow(row){

//此处事件与editable冲突
}

    });
});

**Comment by wenzhixin** [comment]
```
onClickRow (item, $tr, field) {
  if ([...].includes(field)) return
}
```

**Comment by liuweiGit** [comment]
可以了,谢谢

**Comment by liuweiGit** [comment]
clickToSelect: false 这个参数好像没起作用
