### ISSUE TITLE
[Table Resizable] The first resize after page loading does not work 

### ISSUE THREAD

**Issue by gautierderuette** [wenzhixin/bootstrap-table#3515]
After the page is loaded, the first time we try to resize a column does not work. The second time it is ok. 

Here is an example of the issue : [jsfiddle](http://jsfiddle.net/c7ckwph3/).

This is very strange.

**Comment by jimgit** [comment]
Definitely could reproduce your issue from your fiddle.   Check out your columns and/or data - I removed all but 3 columns and it works. By systematically removing / adding your columns and data back in you should be able to find the source of the problem

Here's a [jsfiddle to illustrate](https://jsfiddle.net/jimkennelly/kqzcjh8c/4/)

**Comment by gautierderuette** [comment]
I noticed that when there is less column it works. Actualy the issue appears when the columns seems to be to large : [jsfiddle with only three columns](https://jsfiddle.net/kqzcjh8c/6/)

**Comment by djhvscf** [comment]
@gautierderuette workaround can be use `liveDrag='true'`

http://jsfiddle.net/c7ckwph3/9/

**Comment by djhvscf** [comment]
Please refer to this issue opened: https://github.com/alvaro-prieto/colResizable/issues/92

**Comment by alvaro-prieto** [comment]
Hi @djhvscf 

All I can say is that I didn't even know that someone was using colResizable here, and I can not see my name anywhere. Then I guess I have nothing to do in here. Thank you anyway.

**Comment by djhvscf** [comment]
@alvaro-prieto you can see here https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/resizable we're referencing your repository. We don't have any modified version of your library.

**Comment by djhvscf** [comment]
@gautierderuette I will try to update our extension to use this https://github.com/dobtco/jquery-resizable-columns. I will keep you posted.

**Comment by alvaro-prieto** [comment]
Thank you @djhvscf   Try updating your dependency to colResizable 1.6  

I'm sorry if I sound rude...   sometimes I feel a bit bad when other projects gaing much more popularity than my project does. In the past I've found clones of my own repository removing my name and hosting the project as if it were developed by them with a different name, so sometimes I'm a bit too... 'picky'. Sorry about that. Anyhow, adding the name of the source contributors is always kind.

Feel free to change to resizable-columns or stay with colResizable if you wish. Good luck :-)

**Comment by gautierderuette** [comment]
@djhvscf That would be great ! Thanks !

**Comment by djhvscf** [comment]
Hi @gautierderuette in this commit we're removing the dependency of colResizable and now we're implmeneting a new jquery plugin, please check it out: https://github.com/djhvscf/bootstrap-table/commit/4dfb15a8d8e131baf931ce0441b254d428813209

**Comment by gautierderuette** [comment]
Actually I can't make it works. Do you have an example ?
