### ISSUE TITLE
**Suggest：**   Can  add amethod ,help for bacth commit!

### ISSUE THREAD

**Issue by chnpassion** [wenzhixin/bootstrap-table#3516]
**Suggest：**
        Can  add amethod,help for bacth commit：
        _Name_：getChanges
       _Parameter_：type
       _Description_：Get changed rows since the last commit or load. The type parameter indicate which type changed rows, possible value is: inserted,deleted,updated,etc. When the type parameter is not assigned, return all changed rows.
       **Thanks a lot!**

**Comment by jimgit** [comment]
I needed something like this before and used the following method
1.  Add a field to the data called STATUS - mark them as Original for initial load
2.  On the data load event - save a copy of the original data - call it originalRows
3. Each time a row is modified in the updateRow - mark the STATUS "modified"
4. For the delete row - this will delete a row in the bootstrap table rows but not in the originalRows
5. For inserted rows - this will be added to the bootstrap table data set
6. When user hits SAVE - array compare is run from bootstrapTable "getData" and the originalRows.  Deletes are in the originalRows but not in current,  Modified rows are marked "modified" and inserts are in the current rows but not in the original rows.
7. A json array is built with update rows, deleted rows and inserted rows and sent to the server

Will try to setup a jsfiddle when I have time but a built in feature like this would be nice especially with call types for just inserts , modified or deleted rows.

**Comment by jimgit** [comment]
Found enough samples to cobble together a [jsfiddle - still need to add the filtering / compare logic to get the inserted, modified and deleted.](http://jsfiddle.net/jimkennelly/wqscucqL/)

**Comment by jimgit** [comment]
You can try this -[ jsfiddle - mark rows deleted and inserted](https://jsfiddle.net/jimkennelly/aj8w6mhc/)

Hit the DELETE button on a few rows and hit the ADD button - then hit SAVE

**Comment by djhvscf** [comment]
This looks very good
