### ISSUE TITLE
bootstrap-table dropdown display with flask

### ISSUE THREAD

**Issue by pbosavage** [wenzhixin/bootstrap-table#3518]
bootstrap-table dropdown display with flask

I'm using bootstrap-table in a flask application running on a vagrant virtual environment. Due to corporate policy I am referencing bootstrap and all bootstrap-table locally, not from a CDN. It must be this way I have no option.

For example:

<script src="/static/js/jquery-2.1.4.js"></script>
<script src="/static/bootstrap-3.3.7/dist/js/bootstrap.js"></script>
<script src="/static/bootstrap-table-master/dist/bootstrap-table.js" type="text/javascript"></script>
<script src="/static/bootstrap-table-master/dist/extensions/sticky-header/bootstrap-table-sticky-header.js" type="text/javascript"></script>
<script src="/static/bootstrap-table-master/dist/extensions/export/bootstrap-table-export.js" type="text/javascript"></script>
<script src="/static/tableExport.jquery.plugin-master/tableExport.js" type="text/javascript"></script>
<script src="/static/bootstrap-table-master/dist/extensions/filter-control/bootstrap-table-filter-control.js" type="text/javascript"></script>
<script src="/static/bootstrap-table-master/dist/extensions/editable/bootstrap-table-editable.js" type="text/javascript"></script>
<script src="/static/bootstrap3-editable/js/bootstrap-editable.js" type="text/javascript"></script>

The bootstrap-table options I am using that require pops are show-columns, export and pagination page table:

  var $table = $('#proc-table');
  $(function() {
    $('#proc-table').bootstrapTable({
      exportTypes: ['json', 'xml', 'csv', 'txt'],
      showColumns: true,
      stickyHeader: true,
      filterControl: true,
    });
  });

...

<table id="proc-table"
           data-search="true"
           data-show-export="true"
           data-pagination="true"
           data-side-pagination="ajax"
           data-page-list="[5, 10, 20, 50, 100]"
           data-show-pagination-switch="true"
           data-toolbar="#toolbar"
           data-url="/api/myapi/v1/myapi_data">
    </table>

I do not get any javascript errors (as expected), however, the popus for show columns, export and the data page list do not display.

The interesting part. If I include an (incorrect) integrity and an anonymous crossorigin tag for boot strap:

<script src="/static/bootstrap-3.3.7/dist/js/bootstrap.js" integrity="sha256-5HcZKoitmDQeTbMSJwbFJvUOU1Oz2BphmBPi6vzc5xc=" crossorigin="anonymous"></script>

I get the following javascript errors:

Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:5000/static/bootstrap-3.3.7/dist/js/bootstrap.js' with computed SHA-256 integrity 'Cr6N6zNN4bp0OwTQOZ6Z66M2r+2dpy/EwKMCyZ+SOMg='. The resource has been blocked.
bootstrap-editable.js:4707 Uncaught TypeError: Cannot read property 'Constructor' of undefined
    at bootstrap-editable.js:4707
    at bootstrap-editable.js:4922

but the dropdowns for show columns, export and pagination page list all display and work correctly. If I provide a valid integrity value for bootstrap, I'm back to where I was before. No error messages but the dropdowns do not display. 

I'm uneasy moving forward with these errors. I'd like to understand what the issue is. Any help is much appreciated.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by pbosavage** [comment]
Thank you for responding and my apologies -  I'd like to close the issue - it seems like the process of writing out the problem led me to the solution - i upgraded jquery.
