### ISSUE TITLE
Anybody have a full example of all the options for bootstrap-table in a jsfiddle?

### ISSUE THREAD

**Issue by jimgit** [wenzhixin/bootstrap-table#3519]
When I create a new page,  I often copy a previous version  but sometimes I need different options and have to look them up.  Was wondering if somebody had a reference to a jsfiddle or example that could be saved with the project docs showing ALL options.  Would be nice to have with the <table data-*> and the javascript code version $table=bootstrapTable({ url,etc)  A column template would be handy too.

It would be easier to delete all the options I don't want than look them up - Other suggestions?

**Comment by djhvscf** [comment]
We have this https://github.com/wenzhixin/bootstrap-table/issues/1765 and also you can check http://issues.wenzhixin.net.cn/bootstrap-table/
