### ISSUE TITLE
Response data as a response object property

### ISSUE THREAD

**Issue by smgladkovskiy** [wenzhixin/bootstrap-table#352]
In my project I receive data to use in table grid as object property of a response:

    {
        status: 1,
        data: [...], // data array
        pagination: {...} // pagination object
    }
To interact with such response I had to made some changes to plugin. I add definition of remote data container name (null by defaults) and some workaround with server side pagination.

Would this changes be interesting to users? I can make a PR if it would be.

**Comment by wenzhixin** [comment]
Thanks anyway, close this issue.
