### ISSUE TITLE
align toolbar buttons with table buttons?

### ISSUE THREAD

**Issue by onykage** [wenzhixin/bootstrap-table#3521]
how is it possible to force the toolbar buttons/customs to align on the right side of the search bar against the default buttons on the toolbar at the top of the table?

http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html  this shows buttons on the left of the search not the right.

I saw some old closed topics where folks asked similar questions but I cant find anything anything even on slack or google about anykind of wrapper for making the buttons align to the right.

is this possible currently??

**Comment by djhvscf** [comment]
Since this is a custom toolbar you can order the buttons/inputs as you wish.

See this example: http://jsfiddle.net/e3nk137y/18103/embedded/

Also you can use these options:

```js
toolbarAlign: 'left' or 'right'
buttonsAlign:  'left' or 'right'
searchAlign:  'left' or 'right'
```
