### ISSUE TITLE
请问table在加载完远程数据后有没有办法对数据做一下过滤再渲染表格

### ISSUE THREAD

**Issue by king607267** [wenzhixin/bootstrap-table#3522]
比如我后台返回的json中有一个属性是表格数据载体（data）类似{success: true, code: "1000", message: "查询成功", data: {…}} 有没办法指定data属性来显示表格，类似以前用的EsayUI中的loadFilter事件，谢谢。

**Comment by wenzhixin** [comment]
`responseHandler` 可以解决你的问题。
