### ISSUE TITLE
一个可能问题的修复。

### ISSUE THREAD

**Issue by tanzx** [wenzhixin/bootstrap-table#3523]
问题场景：一个页面有两个BootstrapTable，其中一个可见，一个隐藏。在放大缩小浏览器页面时，那个可见的BootstrapTable的表头出现错位。
原因：BootstrapTable.prototype.initHeader方法中，
$(window).off('resize.bootstrap-table');
这行代码移除了事件监听。在同时有两个表格时，第一个表格的resize事件处理会被移除。
解决办法：
var resizeTag="resize.bootstrap-table."+this.$el.attr("id");
$(window).off(resizeTag);
对每个表格单独设置命名空间，用于绑定、解绑事件处理。
希望BootstrapTable作者确认一下这个问题。也希望BootstrapTable使用者遇到这个问题时顺利解决。

**Comment by wenzhixin** [comment]
浏览器放大缩小的问题已经解决了，你可以使用 develop 的版本进行验证，谢谢。

**Comment by wenzhixin** [comment]
不过我没试过两个表格的情况，我也验证下吧。

**Comment by Falseee** [comment]
I translated it with the google translator, if i understood it correct the issue is fixed in a newer version.
Can you check it ? @wenzhixin

**Comment by wenzhixin** [comment]
Same as #4203
