### ISSUE TITLE
Check/Uncheck All in all pages with server-side paging in VUE2.JS

### ISSUE THREAD

**Issue by zoharbarak** [wenzhixin/bootstrap-table#3524]
I tried using the checkall feature (as in #3445 ) in my Vue2 project and failed to do it because I can't use data-response-handler as it takes a function name and not a function pointer and inside the component html part the name that is this.methodName() (for example) isn't the method name after building everything with webpack.

Also using refreshOptions doesn't work in this case.
Is it possible for you to add an option to set that method (data-response-handler) in a way I can give it a fucntion pointer?

**Comment by wenzhixin** [comment]
You can use it via javascript:
```
mounted () {
  $('#table').bootstrapTable({
    ...
    responseHandler (res) {
    }
  })
}
```

**Comment by zoharbarak** [comment]
@wenzhixin Either I didn't do it right or it does not work.
Tried:

$('#table').bootstrapTable({ responseHandler (res) { 
res.rows.forEach(function (item) {
                item.state = checkAll;
            })
            return res;
}
  });
______________________________________________________________________
also tried:
$("#table").bootstrapTable('responseHandler', function (res) {
          res.rows.forEach(function (item) {
                item.state = checkAll;
            })
            return res;
        });
______________________________________________________________________
Both ways do not work.

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/getting-started/#usage via JavaScript.

**Comment by zoharbarak** [comment]
@wenzhixin 
Thanks for your reply,
I Understood that it's via Javascript.. that's also what I tried to do as you can see in my attempts earlier.
The documentation says that I can set it as an option but to do so is like my second attempt. but then I get an error: "Unknown method: responseHandler".
If i just put responseHandler (res) { } in $('#table').bootstrapTable({ < here > })  like you said -> also leads to an error.
My current code has:
```
$("#customers-table").bootstrapTable('load', customersList);
      $("#customers-table").bootstrapTable('refreshOptions', {
        exportDataType: "all"
      });
```
How do I add it to this code?

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show the problem, thanks!

**Comment by zoharbarak** [comment]
Not working for me in jsFiddle, but mostly because of many reasons, but the javascript part there indicates what I was trying to do

My failed attempt:
https://jsfiddle.net/azqorusg/8/

Also, I noticed that even if I somehow got it to work, even your example is working well (http://jsfiddle.net/4r6g4cfu/882/) because if I check all and then uncheck a specific one on page 1 and then go to page 2 and back to page 1, it becomes re-checked, which is not good.

**Comment by wenzhixin** [comment]
Solution: http://jsfiddle.net/wenyi/4r6g4cfu/1048/

**Comment by zoharbarak** [comment]
Thank you for your solution.
Although there is still a bug that prevents me from doing something like this:
When you check all and then uncheck one line and then go to an other page and go back it will be checked even though it was unchecked.
Is there a way to solve this?

**Comment by wenzhixin** [comment]
Maybe we can combine this example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/917.html

**Comment by jimgit** [comment]
You need to persist the check box data somewhere.  For example, you might want to post back via ajax or form submit to the server when a single (or all) checkboxes are checked.  If you are using some type of back end storage, you would save those values - the user (and others) would then be able to see the checkbox data later.

If you are just interested in the user session,  you could store the status of the records in a cookie or local storage or post back and remember the status of the checkboxes for the user session.
