### ISSUE TITLE
show-details-view  not word wrap when i input long  pure english character

### ISSUE THREAD

**Issue by davidway** [wenzhixin/bootstrap-table#3526]
when i input english character( like 'aaaaaaaabbbccceedddd '),show-details-view  not word wrap 
I try agin and found this situation(scroll bar isn't gone)  will display when i input pure '0123456789' number
Scroll bar isn't gone
here is the fidder
(http://jsfiddle.net/weekendzhu/4g2wdp2m)
![image](https://user-images.githubusercontent.com/6014971/34479677-2243b442-efe3-11e7-94d2-66986cf54233.png)

but you can see the detail -view is work well when i input contains or pure chinese character.
the Scroll bar is gone，that's what i want when i input pure english character
![image](https://user-images.githubusercontent.com/6014971/34479549-765d09b2-efe2-11e7-917b-12c7815e52d3.png)

forgive my poor english :)

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/4g2wdp2m/2/

**Comment by davidway** [comment]
thanks！！it works well
