### ISSUE TITLE
table1的行赋给table2，修改部分属性，多次操作table2对应被修改的属性会被完全替换为最后一次修改的值

### ISSUE THREAD

**Issue by linkjr** [wenzhixin/bootstrap-table#3527]
here is [jsfiddle](https://jsfiddle.net/4uxdzgg2/)

when get table data and change value then append to other table over and over, the whole data of other table will be updated to the last time changed, i don't think it's a good idea.

**Comment by wenzhixin** [comment]
JavaScript中的对象是索引，你不能直接修改啊，如：
```
var obj = {a: 1};
var obj2 = obj;
obj2.a = 2;
console.log(obj.a); // 2
```
用一个新的 Array 就可以了：
https://jsfiddle.net/wenyi/4uxdzgg2/1/

**Comment by linkjr** [comment]
我不确定你是否理解了我的意思，为了简便我才用的setInterval，事实上我是每次递增是点击的一个按钮，每次点击后重新取的table1的值给items，这个时候还有引用么？你这个例子明显是一次性赋值修改。

**Comment by wenzhixin** [comment]
是的
