### ISSUE TITLE
Table head field doesn't align to data cell after setting data-height and data-group-by-field.

### ISSUE THREAD

**Issue by zhenwie** [wenzhixin/bootstrap-table#3528]
![34466182-1cdd6170-ef06-11e7-8c92-803e30fb3fdd](https://user-images.githubusercontent.com/17755175/34527089-68415d12-f0df-11e7-80e9-b6cda97b6231.png)

If you add "data-height" for your example extentions/group-by-v2.html, you can reproduce this issue.
Chromium
Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by UtechtDustin** [comment]
The group by extension will be merged/rewritten, this issue will be checked in #4413.
