### ISSUE TITLE
How do I use nested JSON data to populate a table?

### ISSUE THREAD

**Issue by ethompsy** [wenzhixin/bootstrap-table#353]
Hello!

I have a question:

I have a rather complicated (and useful) JSON object that I want to use with your bootstrap-table. I have looked at the javascript example, but the data2.json object is a bit more simple than my json endpoint. Mine has nested data. I want to use the nested data in the table. Here is an example of my json object:

```
{
    "messages": [
        {
            "id": 652, 
            "session_id": 8965861649940144331, 
            "date": "2014-12-17T01:01:09Z", 
            "m_type": "Error", 
            "message": "could not find a matching MDF file for legacy SQL selection $SQL:\\(local)\\Adams", 
            "file_name": "$SQL:\\(local)\\Adams", 
            "msdn": 33
        }, 
        {
            "id": 653, 
            "session_id": 8965861649940144331, 
            "date": "2014-12-17T01:01:10Z", 
            "m_type": "Error", 
            "message": "could not find a matching MDF file for legacy SQL selection $SQL:\\(local)\\TRAINING", 
            "file_name": "$SQL:\\(local)\\TRAINING", 
            "msdn": 33
        }
    ], 
    "session_id": 8965861649940144331, 
    "date": "2014-12-17T01:55:14Z", 
    "client_date": "2014-12-16T19:55:14Z", 
    "actual_cpu": "", 
    "licensed_cpu": "", 
    "license": 1, 
    "brand": 2, 
    "account": 215, 
    "computer": 289, 
    "regcode": "1:2:215:289"
}
```

How would I display a table of just the "messages" data?

**Comment by Vijaeendra** [comment]
Hi I am trying to use the load a nested json object using the bootstrap-table. How do I make it work? I am not sure how and where to include the responseHandler . Can someone please explain. This library works like charm for all my other requirements, except the nested table one. Thanks in advance.

**Comment by djhvscf** [comment]
Please check the flat-json extension

**Comment by Vijaeendra** [comment]
I mean displaying the tree structure. My Json Object is something like this. 

{
  "children": [
    {
      "children": [
        {
          "children": [], 
          "expanded": "true", 
          "folder": "true", 
          "last_modified": "Thu Jul  9 17:13:48 2015", 
          "size": 4096, 
          "title": "child21"
        }
      ], 
      "expanded": "true", 
      "folder": "true", 
      "last_modified": "Thu Jul  9 17:13:48 2015", 
      "size": 4096, 
      "title": "Child2"
    }, 
    {
      "expanded": "false", 
      "folder": "false", 
      "last_modified": "Thu Jul  9 17:13:13 2015", 
      "size": 0, 
      "title": "test.txt.txt"
    }
  ], 
  "expanded": "true", 
  "folder": "true", 
  "last_modified": "Thu Jul  9 17:13:48 2015", 
  "size": 4096, 
  "title": "Node_Parent"
}


I want to have a look like the following.

![fodler_pic](https://cloud.githubusercontent.com/assets/8585349/8609744/45254f58-265e-11e5-8209-21bae30e51d0.PNG)


I tried using flatJSON. I could not use it here. Please help.

**Comment by wenzhixin** [comment]
It seems that our plugin do not support this feature @Vijaeendra

**Comment by Vijaeendra** [comment]
Okay. Thanks for clarifying. I am sure this feature will be very helpful if implemented.

**Comment by roxma** [comment]
In this case,  any idea how to place a detail icon or button in the cell?

**Comment by wenzhixin** [comment]
Use `formatter` column option @roxma

**Comment by roxma** [comment]
okay, thanks.
I'm currently stuck with displaying data with [nested field from elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/nested.html). Looks like the detail icon is the simplest way to get my job done currently.

**Comment by mossonli** [comment]
@wenzhixin I want to use it with my flask project, what i need to write at the python side
