### ISSUE TITLE
Custom field data input .

### ISSUE THREAD

**Issue by Daond** [wenzhixin/bootstrap-table#3530]
![untitled](https://user-images.githubusercontent.com/35087444/34548575-7258c618-f135-11e7-909e-2ee16effea4b.png)
Hi! I want custom field data ,because I have many array in one array.
I try using "field: 'LeftNavigation.Title'" but don't work.
Thanks

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Daond** [comment]
$('#table').bootstrapTable('destroy');
$('#table').bootstrapTable({
  data: data.LeftNavigation,
  fixedColumns: true,
  fixedNumber: 1,
  undefinedText: "",
  rowStyle: function (row, index) {
    return {
      classes: 'rowNavigation rowNavigation' + index,
      css: { "font-size": "13px", "border": "1px solid #d9d9d9" }
    };
  },
  columns: [
    [
      {
        field: 'LeftNavigation.Title',
        rowspan: 4,
        align: 'center',
        .............
I'M sorry ,because I using sharepoint online should data not get,i working on production.

**Comment by Daond** [comment]
I have refer :  http://jsfiddle.net/25jxxvhb/1/

**Comment by Daond** [comment]
![capture](https://user-images.githubusercontent.com/35087444/34555340-c89ce986-f163-11e7-85e5-4c6d973a8587.PNG)

**Comment by Daond** [comment]
This is my table!

**Comment by Daond** [comment]
I have many array in one array ,and I bind data for field

**Comment by Daond** [comment]
https://jsfiddle.net/7uu5syo4/ this is my demo

**Comment by wenzhixin** [comment]
I think your fiddle can not show your problem.

You can try to update:
```
data: arrayAllValue.LeftNavigation
```
and:
```
field: 'Title'
```

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/353.html
#353 maybe helpful

**Comment by Daond** [comment]
don't work with me!! 
https://github.com/wenzhixin/bootstrap-table/issues/353
 I want select field in array " field: "flatArray2.id" , " 
Please help me!

**Comment by wenzhixin** [comment]
What is your `arrayAllValue` data?
http://jsfiddle.net/wenyi/e3nk137y/13/

**Comment by Daond** [comment]
http://jsfiddle.net/e3nk137y/18175/ 
mutil array

**Comment by Daond** [comment]
http://jsfiddle.net/e3nk137y/18175/

**Comment by Daond** [comment]
Please guide me using responseHandler! not work with me!

**Comment by Daond** [comment]
http://jsfiddle.net/e3nk137y/18181/ responseHandler NOT WORK!

**Comment by jimgit** [comment]
Try [http://jsfiddle.net/jimkennelly/pn548r61/](http://jsfiddle.net/jimkennelly/pn548r61/)  - use the data 
property 


![image](https://user-images.githubusercontent.com/1921941/34590480-aba8ec76-f17c-11e7-9971-894fb96dff77.png)

**Comment by wenzhixin** [comment]
This example can solve your problem: http://jsfiddle.net/wenyi/e3nk137y/18196/

**Comment by Daond** [comment]
Thanks so much!!!
