### ISSUE TITLE
dynamic column data-title 

### ISSUE THREAD

**Issue by Daond** [wenzhixin/bootstrap-table#3531]
http://jsfiddle.net/e3nk137y/18201/
 Please help me! i don't no dynamic my table,I think difficult dynamic. it have support my case
  I wanna only dynamic Q1,Q2,Q3,Q4 on my table

**Comment by djhvscf** [comment]
I don't understand your issue but if you need change the title of the column then you can use this https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/i18n-enhance
