### ISSUE TITLE
我想使用列过滤的扩展功能，但是js报错

### ISSUE THREAD

**Issue by ljw1264654273** [wenzhixin/bootstrap-table#3533]
![image](https://user-images.githubusercontent.com/18202970/34610075-63745a10-f25a-11e7-826b-ce0ea86aefac.png)
![image](https://user-images.githubusercontent.com/18202970/34610099-7298bf2c-f25a-11e7-8b6d-744015494994.png)

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
请提供下 jsfiddle，谢谢。
