### ISSUE TITLE
Bootstrap-table sticky header extension js error

### ISSUE THREAD

**Issue by medwassim** [wenzhixin/bootstrap-table#3538]
Hi,
i have a javascript error when i load via ajax bootstrap-table from select box category(i have many table per category)
Uncaught TypeError: Cannot read property 'top' of undefined
    at render_sticky_header (bootstrap-table-sticky-header.js?p2aiwd:75)

i don't understand why, but it seem that i need to add this test before line 75.
if(!$("#"+anchor_begin_id).length)
    return;

can this test be a feature for eventually bugs like that ?

**Comment by cablegunmaster** [comment]
+1 this solution seems to work, question is if this should be made differently or in another place.

**Comment by wenzhixin** [comment]
Rewrote the code to fix this problem(https://github.com/wenzhixin/bootstrap-table/commit/2766e0074c2ddf863180549da336131b9615c65b) in develop branch.
Develop Example: http://dev.bootstrap-table.com/examples/#extensions/sticky-header.html
