### ISSUE TITLE
能否指定某一列是序号列

### ISSUE THREAD

**Issue by ylyxf** [wenzhixin/bootstrap-table#354]
一般表格的第一列显示为序号：1,2,3,4...，这个序号表示的是当前数据在第几行，不是数据库里面存储的值。在后端返回json数据的时候，在一些条件下，很难把这个值带在json数据中。

有没有什么办法能在某一列上显示序号:或者为th指定一个特殊的data-*，或者有什么办法能取到json数据这个数组的index?

**Comment by wenzhixin** [comment]
http://jsfiddle.net/e3nk137y/1194/
