### ISSUE TITLE
Data not loading...

### ISSUE THREAD

**Issue by ash1404** [wenzhixin/bootstrap-table#3541]
**Data not loading...**

Summary - When welcome.html is running, view is loading properly but data not loading.
Page is showing "No matching records found".
and in chrome console , I am getting 
"Failed to load resource: the server responded with a status of 404 (Not Found)".

browser/OS environment - Chrome/ Windows 7

**Comment by djhvscf** [comment]
Do you mean our website?

**Comment by ash1404** [comment]
No , I am trying this on my local environment in visual studio...
![issuescreenshot](https://user-images.githubusercontent.com/35324540/34815711-6618e402-f6d8-11e7-91f7-a80ecedab49d.PNG)

**Comment by jimgit** [comment]
Put your welcome page html and javascript in JSFIDDLE - if you are serving json data - put a small sample of the json data at Myjson.com and include the link in the JSFIDDLE  You might want to start with one of the jsfiddle examples at [http://bootstrap-table.wenzhixin.net.cn/examples/](http://bootstrap-table.wenzhixin.net.cn/examples/)

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table-examples/#usage
