### ISSUE TITLE
Bring the sort icon next to the text

### ISSUE THREAD

**Issue by Ronen-dev** [wenzhixin/bootstrap-table#3542]
Currently, the sort icon is placed by default to the right :

![capture d ecran 2018-01-11 a 19 28 05](https://user-images.githubusercontent.com/12510911/34840616-d8d058a4-f705-11e7-80f7-5ec6340801e2.png)

I'd like to know if there is an "easy" way to move this icon ? Next to the text at the right, for example.

Thank you.

**Comment by jimgit** [comment]
You can move it to the left of the text with 

![image](https://user-images.githubusercontent.com/1921941/34878873-e7d70dd2-f770-11e7-9939-949e0b5b404e.png)

**Comment by wenzhixin** [comment]
You can overwrite the default css define.

**Comment by wenzhixin** [comment]
ref #1809
