### ISSUE TITLE
固定列插件建议作者更新

### ISSUE THREAD

**Issue by apchenjun** [wenzhixin/bootstrap-table#3543]
固定列 现在存在 样式错位 插件用起来很久没有更新了 不好用 麻烦作者 修复 建议支持左右列固定 头部固定 
现在的固定列 是一个浮动层 漂浮在列的上面 加入自己的样式 很容易错位

**Comment by ihuangmx** [comment]
与 editable 插件不兼容，样式上会出现问题

**Comment by wenzhixin** [comment]
已更新到 https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/fixed-columns 中
