### ISSUE TITLE
Pagination layout problem

### ISSUE THREAD

**Issue by Peetbeest** [wenzhixin/bootstrap-table#3544]
On my jsfiddle you can see that there's something wrong with the layout of the pagination. It looks like the css file isn't loading. For two days I'm looking for a solution, without success. Can someone tell me what I'm doing wrong or point me in the right direction.
Many thanks.

My Js Fiddle Link:
https://jsfiddle.net/Peetbeest/netrvc4e/

**Comment by wenzhixin** [comment]
This feature has not been released: https://github.com/wenzhixin/bootstrap-table/blob/develop/CHANGELOG.md/ 
#3428 please use the develop version instead.
https://jsfiddle.net/wenyi/netrvc4e/2/
