### ISSUE TITLE
Printing extension prints columns that are not visible

### ISSUE THREAD

**Issue by dskilken** [wenzhixin/bootstrap-table#3546]
When using the print extension to print the table, it grabs the entire table, not just the visible columns.  If you have used the methods .bootstrapTable('hideColumn', thecolumnindex);  and .bootstrapTable('showColumn', thecolumnindex);  to add and remove columns from view, and then go to print the table, the entire table prints.   Is there a way to have it only print the visible columns.  I am not sure if dropping or adding columns is considered "filtering."

**Comment by riggzh** [comment]
It's use printIgnore in column options

**Comment by riggzh** [comment]
Maybe you can edit buildTable method judge showColumn to hide columns
`function buildTable(data, columnsArray) {
                        var out = "<table><thead>";
                        for(var k = 0; k < columnsArray.length; k++) {
                            var columns = columnsArray[k];
                            out += "<tr>";
                            for(var h = 0; h < columns.length; h++) {
                                if (!columns[h].printIgnore) {
                                    out += "<th ";
                                    if (columns[h].rowspan) {
                                        out += (" rowspan='" + columns[h].rowspan + "'");
                                    }
                                    if (columns[h].colspan) {
                                        out += (" colspan='" + columns[h].colspan + "'");
                                    }
                                    out += (">" + columns[h].title + "</>");
                                }
                            }
                            out += "</tr>";
                        }
                        out += "</thead><tbody>";
                        for(var i = 0; i < data.length; i++) {
                            out += "<tr>";
                            for(var l = 0; l < columnsArray.length; l++) {
                                var columns = columnsArray[l];
                                for(var j = 0; j < columns.length; j++) {
                                    if (!columns[j].printIgnore && columns[j].field) {
                                        out += ("<td>" + formatValue(data[i], i, columns[j]) + "</td>");
                                    }
                                }
                            }
                            out += "</tr>";
                        }
                        out += "</tbody></table>";
                        return out;
                    }`

**Comment by riggzh** [comment]
https://jsfiddle.net/RiggZh/yxyLurwL/2/

https://github.com/riggzh/bootstrap-table/tree/patch-1/src/extensions/print

You can see this js history to edit

**Comment by wenzhixin** [comment]
Merged.

**Comment by riggzh** [comment]
@wenzhixin 我没有讲这个合并进去，也许应该合？

**Comment by dskilken** [comment]
Thank you so much for the quick fix.   I am using bootstrap-table-fixed-columns, and this causes the first column to not be visible.  I modified the code on my site to print the first column and then use whether the other columns are visible to determine if they should print.

if (!columns[j].printIgnore && columns[j].field && columns[j].visible || j==0) {
                                        html.push('<td>', formatValue(data[i], i, columns[j]), '</td>');
                                    }


Thank you for your fantastic work.  This has really enhanced Bootstrap.
Best regards,
Dan

**Comment by wenzhixin** [comment]
@riggzh 以为你提 PR

**Comment by riggzh** [comment]
@wenzhixin 我提的是如果传值为0的情况下，打印插件会打印出“-”的bug

**Comment by wenzhixin** [comment]
哦哦，那这个问题解决了吗？
Have you solved your problem? @dskilken

**Comment by riggzh** [comment]
@wenzhixin 我告诉他如何改了，看上面回复应该是改好了

**Comment by dskilken** [comment]
Yes thank you.  It is printing well.  I changed it so that rather than printing a - for blank cells, it prints a space.  I had to adjust it to print the fixed column when using the fixed column plug-in.  If you want to make it compatible with the fixed column plug-in, you might want to test if they are using the plug-in, and then print the number of columns they have in the chart, as these are hidden by the code and they won't print without some minor changes to the code.   But my custom version of your code is working great now.  Thank you very much

**Comment by dskilken** [comment]
Hi,
I noticed what might be a bug.  I created a table that has multiple rows in the thead.   When you hide columns, it only hides the last row in the thead.   Please see this example below:
http://jsfiddle.net/dskilken/byLzphy2/ <http://jsfiddle.net/dskilken/byLzphy2/>
Thanks,
Dan

**Comment by riggzh** [comment]
emmmm.....tomorrow maybe i will fix print extra columns
@wenzhixin 隐藏的你看一下，他定义了一些html表头
hide bug please look

**Comment by dskilken** [comment]
Thank you very much for your help.  Support for multiple rows in the header is very helpful.  Need help with hideColumn to support multiple thead rows please.

**Comment by riggzh** [comment]
@dskilken I'm sorry,recently I was buzy. I forget this.
print error could add data-field="" in table head , but hidecolumn error please commit a new issus to @wenzhixin

**Comment by rakucmr** [comment]
@wenzhixin is this solved in current version of Bootstrap Table, I use 1.18.0 version and seems to not be resolved. I've extended this like this:
```javascript
/**
     * hide from print of hidden columns
     */

    $.BootstrapTable =
            /*#__PURE__*/
                    function (_$$BootstrapTable) {
                        _inherits(_class, _$$BootstrapTable);

                        function _class() {
                            _classCallCheck(this, _class);

                            return _possibleConstructorReturn(this, _getPrototypeOf(_class).apply(this, arguments));
                        }

                        _createClass(_class, [{
                                key: "showColumn",
                                value: function showColumn(field) {
                                    var that = this;
                                    var fields = Array.isArray(field) ? field : [field];
                                    fields.forEach(function (field) {
                                        that._toggleColumn(that.fieldsColumnsIndex[field], true, true);
                                        that.columns[that.fieldsColumnsIndex[field]].printIgnore = false;
                                    });
                                }
                            }, {
                                key: "hideColumn",
                                value: function hideColumn(field) {
                                    var that = this;

                                    var fields = Array.isArray(field) ? field : [field];
                                    fields.forEach(function (field) {
                                        that._toggleColumn(that.fieldsColumnsIndex[field], false, true);
                                        that.columns[that.fieldsColumnsIndex[field]].printIgnore = true;
                                    });
                                }
                            }, {
                                key: "showAllColumns",
                                value: function showAllColumns() {
                                    this._toggleAllColumns(true);
                                    this.columns.forEach(function (column) {
                                        column.printIgnore = false;
                                    });
                                }
                            }, {
                                key: "hideAllColumns",
                                value: function hideAllColumns() {
                                    this._toggleAllColumns(false);
                                    this.columns.forEach(function (column) {
                                        column.printIgnore = true;
                                    });
                                }
                            }]);

                        return _class;
                    }($.BootstrapTable);
```
