### ISSUE TITLE
When I have a lot of computing on the page,when it is hidden / show multi columns. have a problem of efficiency

### ISSUE THREAD

**Issue by ZengFanhui** [wenzhixin/bootstrap-table#3550]
当页面在渲染表格时，有大量的计算的时候，隐藏或者显示多列时，页面会卡顿很长时间。
发现的问题是当调用showColumn或者hideColumn时，toggleColumn方法里每次都会重新initHeader()、      initSearch()、initPagination()、initBody()。所以造成效率的问题，所以能否可以一次显示/隐藏多列，如下：
    BootstrapTable.prototype.showColumns = function (fields) {
    	var indexs = [];
    	for(var i in fields){
    		var index = getFieldIndex(this.columns, fields[i]);
    		indexs.push(index);
    	}
        this.toggleColumns(indexs, true, true);
    };

    BootstrapTable.prototype.hideColumns = function (fields) {
    	var indexs = [];
    	for(var i in fields){
    		var index = getFieldIndex(this.columns, fields[i]);
    		indexs.push(index);
    	}
        this.toggleColumns(indexs, false, true);
    };

    BootstrapTable.prototype.toggleColumns = function (indexs, checked, needUpdate) {
    	if(indexs.length === 0){
    		return;
    	}
    	
		for(var i in indexs){
			var index = indexs[i];
			if(index === -1){
				return;
			}
			this.columns[index].visible = checked;
		}
    	
        this.initHeader();
        this.initSearch();
        this.initPagination();
        this.initBody();

        if (this.options.showColumns) {
            var $items = this.$toolbar.find('.keep-open input').prop('disabled', false);

            if (needUpdate) {
            	for(var i in indexs){
            		$items.filter(sprintf('[value="%s"]', indexs[i])).prop('checked', checked);
            	}
            }

            if ($items.filter(':checked').length <= this.options.minimumCountColumns) {
                $items.filter(':checked').prop('disabled', true);
            }
        }
    };

这样，隐藏或显示多列之后，在统一进行渲染，测试过后发现，效率有显著的提升。

**Comment by pbosavage** [comment]
I implemented this and it is an EXCELLENT solution. Well done and thank you.

**Comment by wenzhixin** [comment]
Fixed in this PR: #4268.
