### ISSUE TITLE
How to make columns sortable when making a table from data?

### ISSUE THREAD

**Issue by woutervisee** [wenzhixin/bootstrap-table#3551]
I'm making my table this way:

```
$(function () {
    $('#table').bootstrapTable({
        data: data,
        sortable: true
    });
});
```

But to make it sortable of course the header of the table needs to look like:

`<th data-field="name" data-sortable="true">`

How can I do this? Is there an option in the bootstrapTable function to enable this for specific columns?

**Comment by jimgit** [comment]
Not sure if I understand but one way I uses is to specify each column I want sorted - [see this jsfiddle](http://jsfiddle.net/jimkennelly/znshqcLh/)

Note: I set column for FORKS as data-sortable="false" - note the orange highlighting - that column is setup NOT to sort

![image](https://user-images.githubusercontent.com/1921941/35159714-bbe48a7a-fd00-11e7-9545-7c752d3c7556.png)

**Comment by Falseee** [comment]
https://bootstrap-table.com/docs/api/table-options/#sortable
https://bootstrap-table.com/docs/api/column-options/#sortable
