### ISSUE TITLE
Multiple Rows in the thead are not picked up on hideColumn

### ISSUE THREAD

**Issue by dskilken** [wenzhixin/bootstrap-table#3553]
Hi,
I noticed what seems to be a bug.  I created a table that has multiple rows in the thead.   When you hide columns, it only hides the last row in the thead with the column in the tbody.   Please see this example below:
http://jsfiddle.net/dskilken/byLzphy2/

I am not sure if it is not picking up all the rows in the thead when it initializes the columns, or the problem is just in the hide and show column function.  Perhaps I am miss reading the code, but is there a chance that you are only picking up the last row of the thead because you over-write the other rows?  Here is the code from the initTable that picks up the thead.   I noticed that you don't save tr's id, class and data-* attributes as you do in the tbody of the table too.

BootstrapTable.prototype.initTable = function () {
        var that = this,
            columns = [],
            data = [];

        this.$header = this.$el.find('>thead');
        if (!this.$header.length) {
            this.$header = $('<thead></thead>').appendTo(this.$el);
        }
        this.$header.find('tr').each(function () {
            var column = [];

            $(this).find('th').each(function () {
                // Fix #2014 - getFieldIndex and elsewhere assume this is string, causes issues if not
                if (typeof $(this).data('field') !== 'undefined') {
                    $(this).data('field', $(this).data('field') + '');
                }
                column.push($.extend({}, {
                    title: $(this).html(),
                    'class': $(this).attr('class'),
                    titleTooltip: $(this).attr('title'),
                    rowspan: $(this).attr('rowspan') ? +$(this).attr('rowspan') : undefined,
                    colspan: $(this).attr('colspan') ? +$(this).attr('colspan') : undefined
                }, $(this).data()));
            });
            columns.push(column);
        });

Thank you again for all your fantastic work,
Dan

**Comment by jimgit** [comment]
Does your requirement absolutely need 3 rows at the top or are you trying to get three rows of headings?

[Does this JSFiddle help?](http://jsfiddle.net/jimkennelly/syteyktt/)

**Comment by dskilken** [comment]
Hi Jim,   It is nice of you to help.

I need three rows
I need a title (which varies in number of lines)
 price
and a Buy button in the header.
The buy button must be at the bottom and in a line with all other buy buttons in the column.  The price right above that should also be in a row with the other prices.   The name is aligned to the top of it's th so that the top of all the names lines up.  The easiest way to do this is a multi-row header on the table.    I could implement all of this with nested divs inside the th for the header, but I am also using sticky header and fixed column extensions, so the layout is already getting very complicated.   Sticky Header and Fixed Column extensions handle multiple row headers just fine.  I think this is a problem with the hide and show column functions, or the way the table initializes the header.  It looks like the developers are assume a single row of thead, when it could have multiple rows.   If it is impossible to fix this, then I could try formatting this with divs inside the head th table cells.
Thank you again for your help,
Dan
