### ISSUE TITLE
在total为0时 下一页也可以点击，首页尾页也可以点击，另外请教一下怎么在分页栏添加跳转

### ISSUE THREAD

**Issue by chaikenao** [wenzhixin/bootstrap-table#3554]
在total为0时 下一页也可以点击，首页尾页也可以点击，另外请教一下怎么在分页栏添加跳转

**Comment by wenzhixin** [comment]
total 为 0 时不会出现上分页组件吧？有的话提供下[jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports)。
跳转你可以使用这个 extension：https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/page-jumpto

https://github.com/wenzhixin/bootstrap-table/pull/3368

**Comment by 940374250** [comment]
server端分页，设置 smartDisplay 为 false，使用搜索在返回空数据时候，分页的页码还是最后一次查询到的.......  
responseHandler: function (res) {
	return {
		total: res.total || 0,
		rows: res.rows || [],
	};
},
添加了这个方法，试了对页码没效果
