### ISSUE TITLE
bootstraptable recreates itself using back history button.

### ISSUE THREAD

**Issue by cablegunmaster** [wenzhixin/bootstrap-table#3556]
Dear Issue resolvers,
I have found a bug regarding the recreation of the bootstraptable.

Steps to reproduce:
1. Create a Bootstraptable on a element. (works perfectly).
2. Go to any next page.
3. Go back in history using the arrows on your browser.

Result: The table is created two times, and the search inputs are generated,
double HTML ID elements are generated. The content is only displayed once.

- Go to any next page
- Go back in history and get a third search input.

Result: The table is created three times, and the search inputs are generated,
triple element ID's are generated. The content is only displayed once.

This issue seems to come in any browser, is there anyway to check if the bootstrap table element is already generated? 

Image explaining the issue:
http://i67.tinypic.com/11trhg1.png

Code used: 
```
           export class SomeClass { 
           $table: any;

                constructor(public gridId: string, public jsonData: any){
                     this.$table = $("#" + gridId);
                }

           init() {
             //some functions
              this.createTable();
           }
```

//createTable function.
```
             createTable() {
             //hoping this will destroy the table if its created, seems to do nothing.
             try {
                this.$table.bootstrapTable('destroy');
            } catch (e) {
            }

             this.$table.bootstrapTable({
                data: this.jsonData,
                sortName : firstColumnSortName
             });

            }
```

Ex execute:
SomeClass.init("overview", jsondata);

If I failed to give some information or is in the wrong repository, let me know.

**Comment by jimgit** [comment]
Can you provide a JSFIDDLE?

**Comment by cablegunmaster** [comment]
I later found out the page loading uses PJAX so i'm still debugging to get to the core of the issue.
