### ISSUE TITLE
Table won't refresh after hiding/showing rows.

### ISSUE THREAD

**Issue by faibistes** [wenzhixin/bootstrap-table#3559]
If I hide a row of an existing bootstraptable via any of these methods:

- `$("tr[id='20'").hide()`
- `$("#mytable").bootstrapTable("hideRow", { index: 20}) }`

The rows will hide but the table won't notice that, e.g. if I pagination is enabled and I go to another page, the row will appear no matter what, the row count will be incorrect... anything you do with the table (filter, sort, check column, go to page...) will not honour the row visibility state.
I'm hiding those rows because I need a custom filtering. Is there any proper way of filtering rows with a custom javascript function (e.g. a function with a moderately complex logic to decide if a row must be shown)? I don't want to remove rows from the data, because the user may want to activate/deactivate filters at any time.

**Comment by jimgit** [comment]
Have you tried the filter command?  Please post a JSFiddle of your results if you continue to have a problem.



![image](https://user-images.githubusercontent.com/1921941/35285753-d109fe00-0023-11e8-8525-f89548e0de08.png)

**Comment by faibistes** [comment]
filterBy isn't enough, I want to filter with startsWith, not with eq. In fact, in the future I may want to use a custom function for the filter. Isn't it possible?

**Comment by dskilken** [comment]
I have discovered that it is much better to use the built-in methods to hide rows or columns than to try to do it manually using jQuery.   This would let you create any custom logic you want, and then call the method to hide or display rows.   There are two methods that you can use to control which rows are displayed:  

showRow | params | Show the specified row. The param must contain at least one of the following properties: index: the row index. uniqueId: the value of the uniqueId for that row.

hideRow | params | Hide the specified row. The param must contain at least one of the following properties: index: the row index. uniqueId: the value of the uniqueId for that row.

There is also a method that will tell you which rows are hidden, and that will display all hidden rows.  Scroll down in the documentation to methods:
http://bootstrap-table.wenzhixin.net.cn/documentation/

$("#yourTableId").bootstrapTable('hideRow', theindex);
(Be careful of variable types. The index expects a number not a string so you may need to convert a string into a number.)

You can also get a row by unique ID - here is an example:  
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getRowByUniqueId.html

I recommend that if you are hiding columns or rows using the methods that you also immediately refresh the table formatting:
$("#yourTableID").bootstrapTable('resetWidth');
$("#yourTableID").bootstrapTable('resetView');	

Also, whenever the browser window is resized, also refresh the table view:
$(window).resize(function(){
           $("#yourTableID").bootstrapTable('resetWidth');
	   $("#yourTableID").bootstrapTable('resetView');
})

**Comment by Falseee** [comment]
> filterBy isn't enough, I want to filter with startsWith, not with eq. In fact, in the future I may want to use a custom function for the filter. Isn't it possible?

Custom filterBy algorythm are maybe soon avaible #4230.
Issue can be closed as soon as he PR is merged.
@wenzhixin @djhvscf

**Comment by wenzhixin** [comment]
ref #4230
