### ISSUE TITLE
How can I use the url attribute to access JSON endpoints outside the domain?

### ISSUE THREAD

**Issue by ethompsy** [wenzhixin/bootstrap-table#356]
Hey, I got another one:

```
  $messageTable = $('#message-table').bootstrapTable({
    classes: [ 'table-striped', 'table-condensed' ],
    method: 'get',
    url: '/triage/errors/{{object.connections.latest.session_id}}/.json',
...
```
That works fine assuming that I have an endpoint configured at `window.location.origin/trage/errors/`. This is great, but what if I wanted to create a table of data from outside my domain? Perhaps from an external API? 

How can we override this behavior?

**Comment by wenzhixin** [comment]
Hi, I think you can set 'Access-Control-Allow-Origin' header(google it) of your server to solve cross domain problem.
