### ISSUE TITLE
hideColumn does not hide multiple rows in the thead, only the last row

### ISSUE THREAD

**Issue by dskilken** [wenzhixin/bootstrap-table#3560]
Hi zhixin wen ,
Thank you again for your fantastic work!

I created a table that has multiple rows in the thead.   When you hide columns, it only hides the last row in the thead.  It leaves behind the other rows in the thead.    Please see this example below:
http://jsfiddle.net/dskilken/byLzphy2/
riggzh requested I send this to you as a new bug.

Is it a problem with the Bootstrap-Table initialization, when it defines the thead rows, or is it a problem with the hideColumn function not seeing the other rows in the head.   It really needs to hide all the rows in the thead when it hides a column.

When you initialize the table, do you pick up the formatting and IDs and classes on the tr for the thead?  You do it for the tbody, but I cannot tell if it is happening for thead.

Thank you again for all of your help,
Dan

Google translate:
嗨zhixin wen，
再次感谢您的出色工作！

我创建了一个包含多行的表格。 当你隐藏列时，它只隐藏了最后一行。 它留下了thead其他行。 请看下面的例子：
http://jsfiddle.net/dskilken/byLzphy2/
riggzh要求我把这个错误发送给你。
它是Bootstrap-Table初始化时的问题，它定义了行的行，还是hideColumn函数没有看到头中的其他行的问题。 当它隐藏一列时，确实需要隐藏所有的行。

当你初始化表格时，你是否拿起了格式化，ID和类的tr为thead？ 你是为了这件事而做的，但是我不知道这件事是否发生了。

再次感谢您的帮助，
Dan

**Comment by jimgit** [comment]
As a workaround until there is a fix, [does this JSFiddle help?](http://jsfiddle.net/jimkennelly/xkL3afLe/)

**Comment by riggzh** [comment]
@jimgit he has three table title , maybe he should manual hide. not bootstrapTable auto hide

**Comment by dskilken** [comment]
@jimgit  I am also using sticky-header and fixed-columns, so I have discovered that manually hiding and using bootstrap-table's methods to hide the columns is not a good strategy.  It is much cleaner to use bootstrap-table methods to hide the columns.  Yes, I could put a div inside the th in a single tr row to form the header, but when it is mixed with sticky-header and fixed -columns, the structure becomes a mess.    I will do some experiments to see what happens when I use data-field as you are doing in your example to see if I can pinpoint where the problem with hidingColumn is located.  Right now I am using the index to the column to hide them.

**Comment by dskilken** [comment]
I spent some time trying to debug what the problem is with multiple rows in the thead:

If you use data-field="someID" in the <th> to identify the column, it will only hideColumn and showColumn if the data-field is declared for the last row in the thead.  It does not store the data-field if defined in any upper row.   hideColumn and showColumn using an index will hide the column and the last row of the header, but not the upper rows of the header.

If you use multiple rows in the header, you cause other problems in other areas of the code because visible is not defined for the top rows of the header.  If you have multiple rows in the header, and try to drag the column to a new location using bootstrap-table-reorder-columns, it causes an error: 
bootstrap-table.js:1686 Uncaught TypeError: Cannot read property 'visible' of undefined
    at Number.<anonymous> (bootstrap-table.js:1686)
    at Function.each (jquery.min.js:2)
    at BootstrapTable.initRow (bootstrap-table.js:1668)
    at BootstrapTable.initBody (bootstrap-table.js:1820)
    at BootstrapTable.initBody (bootstrap-table-fixed-columns.js:62)
    at Object.beforeStop (bootstrap-table-reorder-columns.js:175)
    at jquery.dragtable.js:154
(anonymous)	@	bootstrap-table.js:1686
each	@	jquery.min.js:2
BootstrapTable.initRow	@	bootstrap-table.js:1668
BootstrapTable.initBody	@	bootstrap-table.js:1820
BootstrapTable.initBody	@	bootstrap-table-fixed-columns.js:62
beforeStop	@	bootstrap-table-reorder-columns.js:175
(anonymous)	@	jquery.dragtable.js:154
setTimeout (async)		
(anonymous)	@	jquery.dragtable.js:175
_trigger	@	jquery-ui.min.js:6
_trigger	@	jquery-ui.min.js:12
(anonymous)	@	jquery-ui.min.js:6
_clear	@	jquery-ui.min.js:12
(anonymous)	@	jquery-ui.min.js:6
_mouseStop	@	jquery-ui.min.js:12
(anonymous)	@	jquery-ui.min.js:6
_mouseUp	@	jquery-ui.min.js:6
(anonymous)	@	jquery-ui.min.js:6
n._mouseCapture._mouseDistanceMet._mouseDelayMet._mouseUpDelegate	@	jquery-ui.min.js:6
dispatch	@	jquery.min.js:3
r.handle	@	jquery.min.js:3

It looks like the table initialization needs to be checked to make sure it is properly picking up all rows in the thead.

Google Translate:
我花了一些时间试图调试问题是多行在thead：

如果在<th>中使用data-field =“someID”来标识列，则只有在为thead中的最后一行声明数据字段时，它才会隐藏列和showColumn。它不存储数据字段，如果在上面的行中定义的话。使用索引的hideColumn和showColumn将隐藏标题的列和最后一行，但不会隐藏标题的上一行。

如果在标题中使用多行，则会在代码的其他区域中导致其他问题，因为对于标题的顶部行没有定义可见性。如果头中有多行，并尝试使用bootstrap-table-reorder-columns将列拖到新位置，则会导致错误：
bootstrap-table.js:1686 Uncaught TypeError: Cannot read property 'visible' of undefined
    at Number.<anonymous> (bootstrap-table.js:1686)
    at Function.each (jquery.min.js:2)
    at BootstrapTable.initRow (bootstrap-table.js:1668)
    at BootstrapTable.initBody (bootstrap-table.js:1820)
    at BootstrapTable.initBody (bootstrap-table-fixed-columns.js:62)
    at Object.beforeStop (bootstrap-table-reorder-columns.js:175)
    at jquery.dragtable.js:154
(anonymous)	@	bootstrap-table.js:1686
each	@	jquery.min.js:2
BootstrapTable.initRow	@	bootstrap-table.js:1668
BootstrapTable.initBody	@	bootstrap-table.js:1820
BootstrapTable.initBody	@	bootstrap-table-fixed-columns.js:62
beforeStop	@	bootstrap-table-reorder-columns.js:175
(anonymous)	@	jquery.dragtable.js:154
setTimeout (async)		
(anonymous)	@	jquery.dragtable.js:175
_trigger	@	jquery-ui.min.js:6
_trigger	@	jquery-ui.min.js:12
(anonymous)	@	jquery-ui.min.js:6
_clear	@	jquery-ui.min.js:12
(anonymous)	@	jquery-ui.min.js:6
_mouseStop	@	jquery-ui.min.js:12
(anonymous)	@	jquery-ui.min.js:6
_mouseUp	@	jquery-ui.min.js:6
(anonymous)	@	jquery-ui.min.js:6
n._mouseCapture._mouseDistanceMet._mouseDelayMet._mouseUpDelegate	@	jquery-ui.min.js:6
dispatch	@	jquery.min.js:3
r.handle	@	jquery.min.js:3


它看起来像表初始化需要检查，以确保它正确地拿起所有的行中。

**Comment by wenzhixin** [comment]
To be exact, we are not supporting this kind of table title with one `colspan` three times, it's hard to implement.
you can check this PR: #4456 to see other examples we have supported.

But in your example case, there is a workaround for you: https://live.bootstrap-table.com/code/wenzhixin/112.
