### ISSUE TITLE
Treegrid extension missing from dist folder

### ISSUE THREAD

**Issue by Latiosu** [wenzhixin/bootstrap-table#3561]
### Issue
The Treegrid extension is present in the `develop` branch's `src/` folder ([evidence](https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions)) but is absent from the `develop` branch's `dist/` folder.

### Motivation
[Bootstrap Table Examples repo](https://github.com/wenzhixin/bootstrap-table-examples/tree/master/extensions) currently shows that Treegrid is an available extension for use but it is not present in `dist/` and thus requires the user to compile the repo before they can use the extension. I feel that the presence of the extension on the examples site implies that the extension is ready-for-use but actually isn't ([evidence](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/treegrid.html)).
I am unable to use the Treegrid extension with NPM unless I compile the repo first.

### Request
It would be very helpful to have a new version (such as v1.11.2) that includes Treegrid within the `dist/` folder.

**Comment by Falseee** [comment]
The [Treegridextension](https://github.com/wenzhixin/bootstrap-table/tree/develop/dist/extensions/treegrid) is no avaiable in in the dist folder
