### ISSUE TITLE
Simple json String Array as data source- Only showing first char

### ISSUE THREAD

**Issue by Siedlerchr** [wenzhixin/bootstrap-table#3562]
I have a very simple json Array like `["Test1","Test"] `as file Data.json
As I have no column name, I thought I could use the column index. It works, but only shows the first character.
See my post on SO for details:
https://stackoverflow.com/q/48401355/3450689

**Comment by jimgit** [comment]
It actually returns the character index - so if you put a 2 it shows you the third character.  Is there a reason you can't add field names?

**Comment by Siedlerchr** [comment]
Thanks for the info, I did not know what to add as column/field name. What should I add as field name?

**Comment by jimgit** [comment]
[Look at this example JSFiddle](url)

Change your data to be json array with a field name (I used myFieldName) that matches your table definition.


![image](https://user-images.githubusercontent.com/1921941/35353494-f9f7c0ba-010c-11e8-8fbc-a31ab5b7d43b.png)

var data = [{
  "myFieldName": "test"
}, {
  "myFieldName":
  "test1"
}];

**Comment by Siedlerchr** [comment]
Thanks for the tips. I think I will change the web service response to include a fieldname. Seems like the easiest option for me.
