### ISSUE TITLE
The page size drop down is not functioning after upgrading to Bootstrap v4

### ISSUE THREAD

**Issue by nimblejoe** [wenzhixin/bootstrap-table#3566]
After creating a new solution using Boostrap v4 and adding bootstrap-table, the drop down for selecting the number of rows to display on each page is not working.  Clicking on the drop down seems to have no effect now.

**Comment by timoline** [comment]
hmmm. it works for me....

**Comment by wenzhixin** [comment]
Example http://issues.wenzhixin.net.cn/bootstrap-table/#options/v4.html, please update to the latest version.
