### ISSUE TITLE
样例网址打不开，就算下载到本地也打不卡

### ISSUE THREAD

**Issue by tanshanli** [wenzhixin/bootstrap-table#3568]
bootstrap-editable.css
tableExport.js
这两个文件加载失败，提示一下内容
Provisional headers are shown

**Comment by wenzhixin** [comment]
你好，应该是被Q了，你可以直接使用这里的代码：
https://github.com/vitalets/x-editable
https://github.com/hhurz/tableExport.jquery.plugin
