### ISSUE TITLE
how to use "for" loop before populate data?

### ISSUE THREAD

**Issue by ceom123** [wenzhixin/bootstrap-table#3571]
Hey,
i need populate json data into table using like data[i].name,so i need "for" to loop.
How to do it?
Thanks

**Comment by jimgit** [comment]
You need to define your question / problem with more detail. [ Is JSFIDDLE this what you are looking for?](http://jsfiddle.net/wenyi/e3nk137y/13/)

**Comment by ceom123** [comment]
![example](https://user-images.githubusercontent.com/23051987/35442953-2ec836d4-02e4-11e8-8346-3563f08ccec8.jpg)
This is my json data example. Yes,i need array with a loop. Like root[i].id root[i].name etc.....How to do it?can anyone help me? thanks

**Comment by jimgit** [comment]
Put your data and whatever settings in JSFIDDLE and post the link - you need to do your part to help solve YOUR problem.

**Comment by ceom123** [comment]
http://jsfiddle.net/e3nk137y/18573/  
Now i have 2 problems:
1.why cant load data into table?
2.how to load data with "for" loop?

Thanks

**Comment by jimgit** [comment]
[Try this JSFIDDLE](http://jsfiddle.net/jimkennelly/dycqfm4n/)  - use d.root

**Comment by ceom123** [comment]
Thanks
