### ISSUE TITLE
Filter control (select) duplicate bug

### ISSUE THREAD

**Issue by SpinyMan** [wenzhixin/bootstrap-table#3573]
Problem with two tables on the page with the same column name:
```
$('#table1').bootstrapTable({
    columns: [
        {field: 'country.name', title: 'Country', filterControl: 'select', filterData: 'var:countries'},
    ],
    url: 'http://example.com/url1'
});
```

```
$('#table2').bootstrapTable({
    columns: [
        {field: 'country.name', title: 'Country', filterControl: 'select', filterData: 'var:countries'},
    ],
    url: 'http://example.com/url2'
});
```
This is because of next line of code that takes column needed from all tables!
`selectControl = $('.bootstrap-table-filter-control-' + escapeID(column.field));`
To resolve this problem try this:
`selectControl = header.find('.bootstrap-table-filter-control-' + escapeID(column.field));`

**Comment by jimgit** [comment]
Try being more specific with your first jquery select 
selectControl = $('#table1 .bootstrap-table-filter-control-' + escapeID(column.field));

Will select the filter control of the first table.  Not sure of your goal here could you explain what you are trying to accomplish and include a JSFiddle.

**Comment by SpinyMan** [comment]
> Try being more specific with your first jquery select

I can't modify source code, but you can.

I will try to explain again. if we use 2 or more tables and their columns have same name filter select duplicates data. And for fix it you should change source code (line 278 of bootstrap-table-filter-control.js) from:
`selectControl = $('.bootstrap-table-filter-control-' + escapeID(column.field));`
To this:
`selectControl = header.find('.bootstrap-table-filter-control-' + escapeID(column.field));`
And here is your recommendation:
> Try being more specific with jquery select

ta-taam)

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Falseee** [comment]
I close this issue because we got no response/example from you.
If you still need help pls reopen the issue and provide us a jsFiddle.

**Comment by SpinyMan** [comment]
I described the problem in details... if you didn't understand, so I couldn't help you...

**Comment by Falseee** [comment]
We want an jsFiddle as @djhvscf already said, to verify this bug still exists in the newest version.
For that kind of Bug a description is not enough.
