### ISSUE TITLE
data-unique-id 怎么使用表格数据datas的index来作为id？

### ISSUE THREAD

**Issue by kokorodo** [wenzhixin/bootstrap-table#3574]
data-unique-id 怎么使用表格数据datas的index来作为id？因为如果表格有新增操作的时候，无法获取唯一序列，很不方便。

**Comment by wenzhixin** [comment]
例如你的 datas 是：
```
[{index: 1, name: 1}, {index: 2, name: 2}]
```
那你设置 `data-unique-id="index"` 就可以了

**Comment by kokorodo** [comment]
哦。好像也可以这么玩哦。这样的话，应该就是相当于自己去管理这个index咯。
