### ISSUE TITLE
Bootstrap 4 Issues

### ISSUE THREAD

**Issue by cgountanis** [wenzhixin/bootstrap-table#3575]
Basic table setup, the pagination is not working and the number of records is stuck on 10. Is there something I am missing using the latest 1.11.1 version and the latest BS4.

```
                <table data-toggle="table"
                       data-search="true"
                       data-pagination="true"
                       data-show-footer="true"
                       data-striped="true"
                       data-cookie="true"
                       data-cookie-id-table="usercollection">
```

![image](https://user-images.githubusercontent.com/14899817/35534442-285db606-0506-11e8-884a-2fb8e63bb8ac.png)

**Comment by cgountanis** [comment]
![image](https://user-images.githubusercontent.com/14899817/35534721-ffc095d2-0506-11e8-9e78-a0879530ebc2.png)

**Comment by jimgit** [comment]
Please include a JSFIDDLE example.

**Comment by cgountanis** [comment]
Here you go, you can plainly see that the pagination is broken and the popper dropdown (record number 10,25) is barely working.

https://jsfiddle.net/qsapzxnr/

**Comment by jimgit** [comment]
What happens if you remove the   data-pagination-loop="false"

[JSFIDDLE](https://jsfiddle.net/jimkennelly/phx0rddt/1/)

**Comment by cgountanis** [comment]
You can see from your example it moves the pagination from right to bottom left but same issue no pagination style and the dropdown options via popper are not looking very boostrap-like.

**Comment by cgountanis** [comment]
You can see from the v4 example it should look like this? Do we just have to wait for v1.11.2?

![image](https://user-images.githubusercontent.com/14899817/35547793-e7e8e1aa-0540-11e8-8d34-f33c4a888f93.png)

**Comment by jimgit** [comment]
[How about this JSFiddle - ](http://jsfiddle.net/jimkennelly/d1ubtmfr/)copied from the jsfiddle examples with your table body

**Comment by cgountanis** [comment]
Interesting that seems to be working on my phone I'll check it out in the morning maybe it was the bootstrap card... The only real difference I see is you have the table by itself not inside of a card what used to be a panel.

**Comment by cgountanis** [comment]
Can you explain where you got those JS/CSS resources? Is that a newer version of the 1.11.1 released version?

**Comment by cgountanis** [comment]
@wenzhixin Just noticed the example http://issues.wenzhixin.net.cn/bootstrap-table/#options/v4.html is using bootstrap 3 as well. Anyway we can get a quick BS4 update, mainly looks like the pagination and dropdowns.

**Comment by jimgit** [comment]
I used one of the[ jsfiddles from the documentation pages](http://bootstrap-table.wenzhixin.net.cn/examples/)

![image](https://user-images.githubusercontent.com/1921941/35578096-bf52e46c-05a8-11e8-85fa-0c957967c699.png)

**Comment by olly79** [comment]
I can confirm the problems. Got them all ...
Fix would be nice ...

**Comment by chrisw73** [comment]
It would be nice to get a statement here from @wenzhixin  or any other comitter if there is a schedule for a bs4 release of bootstrap-table. Youre useres are waiting desperately for it...

**Comment by cgountanis** [comment]
It is best option for a simple table. With the new automatic col specification it could be really great.

**Comment by wenzhixin** [comment]
1.12.1 released

**Comment by cgountanis** [comment]
Thank you.
