### ISSUE TITLE
Can't use reoderRows with sortable

### ISSUE THREAD

**Issue by clempe** [wenzhixin/bootstrap-table#3578]
I build my table in the following steps.

1. Get the data for the header - which can change - and build the table. Then i load the table tag into a container.  _jsfiddle ->` buildTable()`_

2. I get the data from server and load it into the table with ` $('#table').bootstrapTable({
    data: data, ...});` and enable `reorderableRows`.  _jsfiddle ->` loadData()`_

By doing it that way, it's not possible to use the drag and drop functionality. Only the sorting of a column is possible.  

[jsfiddle](http://jsfiddle.net/clempe/k2yb1v5v/5/)

**Comment by jimgit** [comment]
You can define the columns with field names, sort , and other properties using the columns property.   Can't find an example right now but it's something like

$table.bootstrapTable({
url: "myurl",
columns: [{column1 settings, column2 settings)}

![image](https://user-images.githubusercontent.com/1921941/35575711-ba4568e2-05a2-11e8-8ef1-9d458bd58af4.png)

**Comment by jimgit** [comment]
Take a look at this example,  [field and title are defined dynamically.](http://jsfiddle.net/jimkennelly/7dzshbqp/)

Now look at this:[  JSFIDDLE adding the sortable property makes all the columns sortable](http://jsfiddle.net/jimkennelly/rgv38d6z/)



![image](https://user-images.githubusercontent.com/1921941/35577038-2cb006be-05a6-11e8-89f8-7dc1ee4b52e5.png)

**Comment by clempe** [comment]
Thanks for the quick reply.
Now it's possible to drag and drop the rows and use the sorting function by clicking on the header...

But when drag a row and drop it on a other position, the sorting by clicking the header isn't working anymore.

[http://jsfiddle.net/clempe/rgv38d6z/2/](http://jsfiddle.net/clempe/rgv38d6z/2/)
