### ISSUE TITLE
$table.bootstrapTable('getData', {useCurrentPage: false}); 无效

### ISSUE THREAD

**Issue by pczbq806** [wenzhixin/bootstrap-table#3579]
使用 getData 时，给定 useCurrentPage 参数也无法得到全部数据。

用 Firefox 或 Chrome 打开 http://issues.wenzhixin.net.cn/bootstrap-table/methods/getData.html 时，用开发者工具的 console  执行 $table.bootstrapTable('getData'); 返回 10 个 object，执行 $table.bootstrapTable('getData', {useCurrentPage: false}); 也返回 10 个 object。

**Comment by jimgit** [comment]
Are you using client or server pagination? [ Try this JSFiddle ](http://jsfiddle.net/jimkennelly/8rk5n2sb/)  Change the dropdown to display different page sizes and click the button to see the full data set row count and the visible data rows count.  Note the test data has 1226 rows.

![image](https://user-images.githubusercontent.com/1921941/35627454-938871ba-065e-11e8-80b3-4246cf37f190.png)

**Comment by wenzhixin** [comment]
使用方法不对吧，是 `$table.bootstrapTable('getData');` 和 `$table.bootstrapTable('getData', false);`

**Comment by nicewahson** [comment]
我的也不行 怎么解决呢
