### ISSUE TITLE
add class to row by index

### ISSUE THREAD

**Issue by dirtgambitcp** [wenzhixin/bootstrap-table#3580]
Hi, I love the table but I have a problem with updating cells, I select a row in the table and it highlights, then in another part of the screen I update one of the cells value, 
I use this code to update the cell

data = the json of the object which is an array of object that have properties ID, Week, ToDo
ToDo is an integer that is > 0, we have a formatter on property ToDo if its 0 its green if its more its red
```
$('#ChartCorrectionsWeekSelectTable').bootstrapTable('updateCell', {
            index: index,
            field: "ToDo",
            value: data.ToDo,
            reinit: true
        
        }); 
```
once updated th4e ToDo field changes, the formatting is correctly applied but the success class is removed from the row, I don't want it to do this. I want to keep the row selected.

any help would be appreciated

**Comment by jimgit** [comment]
use the formatter property on the column for class setup

**Comment by dirtgambitcp** [comment]
Hi, ok ive made a small fiddle, select a row in the grid, then increase the value by pressing the button, increase the value again, the table has lost is selected.

https://jsfiddle.net/mreodjdv/

**Comment by jimgit** [comment]
Couple of comments
- you don need the load/refresh - you are setting up the data
- look at the rowstyle function and map it to field you want to use success
- use the unique id setting and getrowbyunique id /updaterowbyid instead of the 'getDate').[index]

**Comment by jimgit** [comment]
Here's an example of the [rowStyle JSFIDDLE](http://jsfiddle.net/wenyi/e3nk137y/16/)

**Comment by dirtgambitcp** [comment]
I think maybe I have confused you because my original question wasn't clear enough, forget the row style for now please, focus on the "Click row", "press increase", "press increase again", the 2nd time you press increase the row isn't selected, why not? and how can I keep selection after pressing increase a 2nd time

**Comment by jimgit** [comment]
If you are using the success class as an indicator - I suggest you use the built in functions for bootstrapTable,  as you would see in other posted issues,  using jquery to modify the bootstrap table "fights" the functionality you really want.  Suggest you look at getselection, update row, and row style and use the native bootstrapTable  [methods](http://bootstrap-table.wenzhixin.net.cn/documentation/#methods).

**Comment by jimgit** [comment]
[Look at this JSFIDDLE](http://jsfiddle.net/jimkennelly/49q7dp94/)

**Comment by dirtgambitcp** [comment]
Ive implemented something like the fiddle you have put in, I removed my success class change in the click event, it keeps the selection now, but I now don't have the row highlighted except for the checkbox I want to hide the checkbox with data-visible


![week](https://user-images.githubusercontent.com/31621224/35679082-ae6512fa-074d-11e8-8a84-fba4d208641f.png)

**Comment by dirtgambitcp** [comment]
but I think you have helped me so thank you

**Comment by jimgit** [comment]
Look at the rowStyle function - this can highlight your row - you might have to combine it with a get selection or remember the selected index in a variable.

**Comment by jimgit** [comment]
[Look at this JSFiddle ](http://jsfiddle.net/jimkennelly/gta3e03g/).  You may want to use the row click event to set the lastNameSelected.

![image](https://user-images.githubusercontent.com/1921941/35682185-6384827a-0725-11e8-8c2d-fc1184089bb5.png)

**Comment by Falseee** [comment]
No response since more than 1 year, if you still need help pls reopen the issue.

**Comment by Internet-explorer-5-shap** [comment]
@dirtgambitcp https://fringed22.github.io/wniPwAz5/
