### ISSUE TITLE
分页怎么添加首页尾页和跳转呢

### ISSUE THREAD

**Issue by smj199265** [wenzhixin/bootstrap-table#3581]
分页怎么添加首页尾页和跳转呢

**Comment by jimgit** [comment]
Calculate the last page by using the number of rows and rows/page.  Then use the selectpage method 

[See documentation at this page](http://bootstrap-table.wenzhixin.net.cn/documentation/#methods)

![image](https://user-images.githubusercontent.com/1921941/35737255-885c97ba-07f0-11e8-95c1-b524ec8a75a2.png)
