### ISSUE TITLE
IE9 can not display data below the table, show no data, IE9 above display normal, not before using IE browser to load

### ISSUE THREAD

**Issue by smj199265** [wenzhixin/bootstrap-table#3582]
IE9 can not display data below the table, show no data, IE9 above display normal, not before using IE browser to load

**Comment by jimgit** [comment]
Please include a JSFIDDLE to demonstrate the problem.

**Comment by smj199265** [comment]
After the abnormal display on the modified page, the data still does not display the data below IE9

**Comment by jimgit** [comment]
Can't help without some demonstration of the problem - please include a jsfiddle or run some of the examples yourself to try to isolate the problem.

**Comment by Falseee** [comment]
No response since more than 1 year, if this issue still exists pls reopen.
