### ISSUE TITLE
No search text, show no data

### ISSUE THREAD

**Issue by timoline** [wenzhixin/bootstrap-table#3583]
currently when you do not have any text in the search box, all data is shown.
empty search = data

Is there an option to hide all that data when no text is in the search box ?
empty search = no data

**Comment by jimgit** [comment]
If I understand your question,  you want to show the table with no data and only show the user data that matches the search box.

You could initialize the bootstrap table using the FILTER method that you know will show no data - for example,  if you have a record id that is positive  - your filter could be something like:

{recordID: -1}   - this will show no data.




![image](https://user-images.githubusercontent.com/1921941/35745872-5f1b3a7c-080a-11e8-90ea-9688bcce6051.png)

Now use the search event  - to undo the filter and use the normal search text.

![image](https://user-images.githubusercontent.com/1921941/35745952-ae11f7a6-080a-11e8-942c-d0c75e7fcae8.png)

**Comment by jimgit** [comment]
You could also do server side pagination and initialize the search to something not found - so no records to start and then only the search causes a pull of data from the server.

**Comment by jimgit** [comment]
[Try this JSFiddle](http://jsfiddle.net/jimkennelly/uqat5nbm/)  Initializes the filter to something that won't be found then triggers on the search event and either clears the filter so the search finds something or restores the filter when user clears the filter.

![image](https://user-images.githubusercontent.com/1921941/35760148-ef321296-0843-11e8-868c-3a806e6af635.png)

**Comment by timoline** [comment]
thanks, i'll check it out!

**Comment by Falseee** [comment]
No response if you still need help since more than 1 year, if you still need help please reopen.
