### ISSUE TITLE
format value when show and when edit input

### ISSUE THREAD

**Issue by Daond** [wenzhixin/bootstrap-table#3584]
![capture](https://user-images.githubusercontent.com/35087444/35767003-e10ca230-0915-11e8-93c9-aacfbb88708b.PNG)
 

I do not know how to do it,i using bootstrap-table and x-editable
Thanks all

**Comment by jimgit** [comment]
[Here is a start - JSFiddle](http://jsfiddle.net/jimkennelly/qsbjnL2x/)

**Comment by Falseee** [comment]
No repsonse since more than 1 year, pls reopen the issue if you still have questions.
