### ISSUE TITLE
reading jason Pagination response stack

### ISSUE THREAD

**Issue by hsm61** [wenzhixin/bootstrap-table#3585]
{
content: [
{
id: 353,
name:"jon"

},
{
id: 354,
name:"mark"
},
],
totalPages: 1,
totalElements:2,
last: false,
size: 10,
number: 0,
sort: null,
first: true,
numberOfElements: 10
}

 how can i read jason Pagination response with header content[{},{},{} , .......] 
i tried   <th data-field="content.drfId"></th>
<th data-field=drfId"></th>
nothing working 
please help

**Comment by jimgit** [comment]
Make sure your json is VALID json - [check this site out](https://jsonlint.com/) and repost with valid json.

**Comment by hsm61** [comment]
a checked and give me error but that is the response of the following 
 @GetMapping(value = "draft/page")
    public Page<DraftV> draftPage(@RequestParam String order,@RequestParam(defaultValue = "0") int offset, @RequestParam(defaultValue = "10") int limit){

    return draftVRep.findAll( new PageRequest(offset, limit));}
so what

**Comment by Falseee** [comment]
No response since more then 1 year, if you still have issues (with a valid json) pls reopen the issue and provide us an example(jsfiddle).
