### ISSUE TITLE
data 刷新无效

### ISSUE THREAD

**Issue by zhou9197** [wenzhixin/bootstrap-table#3586]
如下代码，第一次调用正常加载数据，
当更改 data数据 workInfo时， 表数据没变，但是从console log中确实看到 workInfo的值变了

请问 如何在data: workInfo 改变时  同时更新表，（试过refresh 无效）
$('#workTable').bootstrapTable({
				showRefresh: true,
				data: (function () {
					console.log(workInfo);
					return workInfo;
				})(),
				columns: [{
					field: 'userId',
					title: '员工号',
				}, {
					field: 'userName',
					title: '姓名',
				}, {
					field: 'enterTime',
					title: '入职时间',
				}, {
					field: 'leaveTime',
					title: '离职时间'
				}, {
					field: 'departmentName',
					title: '部门'
				}, {
					field: 'positionName',
					title: '岗位'
				}, {
					field: 'description',
					title: '描述'
				}, {
					field: 'recordStatus',
					title: '状态',
					formatter: function (para) {
						if (para == '1') {
							return '在职'
						} else {
							return '离职'
						}
					}
				}]
			});

**Comment by wenzhixin** [comment]
表格初始化后请使用 `bootstrapTable('load', data)` 方法。
