### ISSUE TITLE
Issue with i18n Enhance

### ISSUE THREAD

**Issue by lowegreg** [wenzhixin/bootstrap-table#3587]
I found that if you only change the locale and do not change the header the placeholder text in the search box would not refresh.

Using this:
`$table.bootstrapTable("changeLocale", "zh-TW");`

Not this:
```
$table.bootstrapTable("changeLocale", "zh-TW");
$table.bootstrapTable("changeTitle", {
    id: "代碼",
    name: "項目名稱",
    price: "項目金額"
});
```
 
Take a look at this demo fiddle:
[https://jsfiddle.net/lowegreg/kukr5wqv/1/](https://jsfiddle.net/lowegreg/kukr5wqv/1/)

I was able to resolve it by changing the  changeLocale function to re init the body and toolbar.  Hope this helps others as I was stuck on it for awhile.

Cheers,
Greg

```
  BootstrapTable.prototype.changeLocale = function (localeId) {
    this.options.locale = localeId;
    this.initLocale();
    this.initPagination();
  };
```

```
  BootstrapTable.prototype.changeLocale = function (localeId) {
    this.options.locale = localeId;
    this.initLocale();
    this.initPagination();
    this.initBody();
    this.initToolbar();
  };
```

**Comment by shangxinbo** [comment]
how to change title of dataformat columns?
