### ISSUE TITLE
how do I set the height of cells?

### ISSUE THREAD

**Issue by Ericzhiluo** [wenzhixin/bootstrap-table#3588]
I would like to limit every cell's height max at 70px. How do I do that?
I tried using cell-style
`return {
      css: {"max-height": "50px", "overflow": "auto"}
 };`
but no help

**Comment by jimgit** [comment]
Try the rowStyle  [Here is a jsfiddle](http://jsfiddle.net/wenyi/e3nk137y/16/)


![image](https://user-images.githubusercontent.com/1921941/35817594-7cbeaec8-0a63-11e8-8407-6625904a331e.png)

**Comment by Ericzhiluo** [comment]
@jimgit thanks for your reply, but i tried your code and it does not work.
Instead, i added `data-formatter="fixedCellHeight"` to columns. 
```function fixedCellHeight(value) {
        if (value) {
            return "<div class='fixed-cell-height'>"+value+"</div>"
        } else {
            return ""
        }```

If anyone has a better method, please share with me :)

**Comment by Ericzhiluo** [comment]
@wenzhixin I hope this could be a feature in the future as you can adjust cell width, column width, table height, but not cell height

**Comment by jimgit** [comment]
But isn't cell height the [same on a table unless you do a rowspan?](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_td_rowspan)

**Comment by Falseee** [comment]
No answer to the question of @jimgit ans also inactive since more then one year.
Can be closed i guess. @wenzhixin @djhvscf.

**Comment by wenzhixin** [comment]
Close this issue, if the problem exists reopen it.
