### ISSUE TITLE
columns drop down list incorrect after hiding column in js

### ISSUE THREAD

**Issue by Ericzhiluo** [wenzhixin/bootstrap-table#3589]
columns drop down list still show the hidden column after calling (for example) `BTtable.bootstrapTable('showColumn', 'color');`

![image](https://user-images.githubusercontent.com/11272522/35820731-80f9456a-0ae1-11e8-9bb5-051f4e221064.png)

**Comment by jimgit** [comment]
Please add a JSFIDDLE that duplicates the problem.

**Comment by HMVJF** [comment]
http://jsfiddle.net/djhvscf/hcbg3k8g/13/
here ID is hidden but the dropdown still shows it.

**Comment by Falseee** [comment]
Please use the [visible](https://bootstrap-table.com/docs/api/column-options/#visible) column option ([working example](http://jsfiddle.net/1Lduvran/1/)).
