### ISSUE TITLE
Bind an 'Advanced Search' form to the BootstrapTable

### ISSUE THREAD

**Issue by webgodo** [wenzhixin/bootstrap-table#359]
Hi, TNX for your nice plugin.
I want to add an 'Advanced Search' Form above the table;
The user fills the form and clicks Submit button. Now the table should load AJAX response. How can we do this?
Note that I want the table to do it's correct job even on pagination and client-side search.

**Comment by maxgrass** [comment]
it's not a bug?
has you solved this?

**Comment by webgodo** [comment]
I did it using a trick, but not straightforward!

**Comment by maxgrass** [comment]
I think the author should close this, as this is not an issue or clearly defined feature.

**Comment by wenzhixin** [comment]
OK, close this.

**Comment by arvmohan** [comment]
@webgodo how did you solve this issue? 
@wenzhixin is there any solution for this out of the box?

**Comment by wenzhixin** [comment]
@arvmohan , we have added an extension: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/toolbar.html

**Comment by arvmohan** [comment]
@wenzhixin will this work with server side pagination also?
