### ISSUE TITLE
Cannot Sort Column after Drag Row

### ISSUE THREAD

**Issue by clempe** [wenzhixin/bootstrap-table#3593]
I'm dynamically create a table (headings and data). 
Sorting the Table by just clicking on the Heading is possible. 
If I drag a row and drop it somewhere else, then it is not possible anymore to sort the table by clicking on a heading. It works again, when I hide a column and make it visible again.

Here is an [example ](http://jsfiddle.net/clempe/rgv38d6z/2/)

**Comment by Falseee** [comment]
Your [example](http://jsfiddle.net/clempe/rgv38d6z/2/) works fine for me, the issue seems fixed in the newest version.
If you still have this issue please reopen and prove us an not working example.
