### ISSUE TITLE
when i use bootstrapTable("load", data)  to add data to table, i can not make a true pagination 

### ISSUE THREAD

**Issue by LoranMEI** [wenzhixin/bootstrap-table#3596]
when i use bootstrapTable("load", data)  to add data to table, i can not make a true pagination 
1: in easyui table:
//search data for page 1 , 5 item length
var grid = $('#dg').datagrid({
    columns: [...]
});
var pager = $("#dg").datagrid("getPager");
pager.pagination({
    total: data.total,
    pageSize: 5,
    onSelectPage: function (pageNo, pageSize) {
         //research pageNo data item ,5 item length
         //reload $("#dg").datagrid("loadData", data);
         //update page and new total(if data have changed)
    }
});
2: in bootstrap table : 
         because the spatial data  i have can not given through java/net url.i have to use bootstrapTable("load", data)  to add my data to the table ,but i can not get a true pagination like easyui.
       
Thanks!

**Comment by LeonardoMEI** [comment]
i have tried to use a plugin to solve this problen ,but it is complex than before 
![image](https://user-images.githubusercontent.com/27984075/36023645-16398e8a-0dc8-11e8-8287-087dbbb0686c.png)

**Comment by jimgit** [comment]
Can you provide a jsfiddle example.   [Here is a load from data example,  can you modify it to match your data?](http://jsfiddle.net/jimkennelly/9Lzjj5e4/)

**Comment by wenzhixin** [comment]
You can use `onPageChange (number, size)` event to solve your problem.
