### ISSUE TITLE
Localizations question.

### ISSUE THREAD

**Issue by technocode** [wenzhixin/bootstrap-table#360]
Hi..

thanks for great boothstrap plugin.. this is better and simple compare to datagrid...

but i have problem in Localization ... How to use formatShowingRows..

I need to change rows to another word..

Thanks..

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/documentation/#localizations

$table.bootstrapTable({
    formatShowingRows: function () {
        return 'another word';
    }
});

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/tree/master/src/locale
