### ISSUE TITLE
Fixed height table, hiding columns issue in Edge

### ISSUE THREAD

**Issue by euangordon** [wenzhixin/bootstrap-table#3601]
Spent a long time to get to the bottom of this, so just sharing information. I went through a lot of other fiddles which also are affected by the same issue.

On Chrome and Firefox everything was working fine, but on Edge when a column was hidden (either in code or via the "data-show-columns" menu, it disappeared but the other columns in the table did not resize. The header table did resize.

![Edge Screenshot](https://nauto.blob.core.windows.net/misc/Edge.PNG)

In the end the solution found on Edge was to set the th columns to width 100%.
```
th {
    width: 100%;
}
```
Now on all browsers when a column is hidden all columns resize correctly.
Please note that this issue did not happen unless my table had a fixed height.

Just hope this can help save anyone else the same pain.

**Comment by Falseee** [comment]
@djhvscf @wenzhixin I use Linux, so i cant test it... can you test it ?

**Comment by wenzhixin** [comment]
Me too, use Mac

**Comment by djhvscf** [comment]
I can test it.. I'm coming back to home today

**Comment by UtechtDustin** [comment]
The issue is already one Year old, since some days edge is based on chromium.
I tested it in VM and it works fine, please update your Browser.
