### ISSUE TITLE
Possible to filter row via html?

### ISSUE THREAD

**Issue by ALTELMA** [wenzhixin/bootstrap-table#3602]
I try to find any solution from you document, But It doesn't have option to filter row from click button.
When I use bootstrap table via html.

If anyone confirm no solution for this. I will load data from ajax instead of html.

**Comment by jimgit** [comment]
Have you tried the click event followed by the filter method?  Please include a JSFiddle to demonstrate your problem.

![image](https://user-images.githubusercontent.com/1921941/36210415-f69c7778-1163-11e8-89ad-35417edae727.png)

![image](https://user-images.githubusercontent.com/1921941/36210467-1af96b94-1164-11e8-9f01-f46b84dba976.png)

**Comment by ALTELMA** [comment]
Here my problem FilterBy doesn't wotk via html. It's work via javascript.

[](http://jsfiddle.net/e3nk137y/19164/)

**Comment by jimgit** [comment]
I normally don't use the embedded table data but noticed when I pull the data using the "getData",  the fields names are 1,2,3,etc.  So if you use a filter with the column name, it looks like it works.

[See this JSFiddle for an example, ](http://jsfiddle.net/jimkennelly/2cf5rtxc/) note the alert with the data  stringified.  Also note the filter is using a "2" for the column vs normally using "forks".


![image](https://user-images.githubusercontent.com/1921941/36238476-66057498-11c8-11e8-80d3-1da606edc897.png)

**Comment by ALTELMA** [comment]
And when data in row like this?
[http://jsfiddle.net/2cf5rtxc/16/](http://jsfiddle.net/2cf5rtxc/16)

**Comment by jimgit** [comment]
Your filter did not match your data.   [Try this JSFiddle](http://jsfiddle.net/jimkennelly/9p5yz7my/)

![image](https://user-images.githubusercontent.com/1921941/36268000-fcf8b442-123a-11e8-8eb9-8a308635d339.png)

**Comment by ALTELMA** [comment]
Ok, thank you.
