### ISSUE TITLE
Define placeholder for select option in filter control

### ISSUE THREAD

**Issue by alekbless** [wenzhixin/bootstrap-table#3603]
Hello,

We can set the placeholder value for input with filterControlPlaceholder.

Is this possible for select as well?

[jsFiddle](https://jsfiddle.net/vo8dL9ch/ )

**Comment by Falseee** [comment]
A select has no placeholder, do you mean the the value of the default option (the first option) ?

**Comment by Falseee** [comment]
Could be a good feature.
@djhvscf @wenzhixin

**Comment by Falseee** [comment]
Could be a good feature.
@wenzhixin @djhvscf

**Comment by UtechtDustin** [comment]
Its already implemented in the newest version
https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/filter-control/bootstrap-table-filter-control.js#L231
