### ISSUE TITLE
Cant refresh table 

### ISSUE THREAD

**Issue by ceom123** [wenzhixin/bootstrap-table#3604]
Hi,
my table get data via post method,like this:
```
$.post("1st/B/get", {}, function (data) {
			   var JSON = eval("(" + data + ")");
			   $('#tasktable').bootstrapTable({data: JSON.root});
		   }); 
```
i tried to use for refresh:
`$('#tasktable').bootstrapTable('refresh'); `
or 
 ```
  $.post("1st/B/get", {}, function (data) {
			   var JSON = eval("(" + data + ")");
			   $('#tasktable').bootstrapTable('refresh',JSON.root); 
		   }); 
```
but its doesnt work.
how to resolve? Thanks

**Comment by jimgit** [comment]
Can you include a JSFiddle - [here is a data example to build your example from ](http://jsfiddle.net/wenyi/e3nk137y/13/)

**Comment by ceom123** [comment]
thanks,resolved! changed to load data via data-url.
