### ISSUE TITLE
Table reloads on window resize

### ISSUE THREAD

**Issue by SanjanaPai** [wenzhixin/bootstrap-table#3605]
In my bootstrap-table I have a input field for quantity. However whenever the browser is resized or the console window is opened, the table reloads leading to the loss of the input data.

**Comment by jimgit** [comment]
Use the formatter property (data-format) to build your input html. [ See this JSFiddle](http://jsfiddle.net/jimkennelly/jw2xddnw/)

![image](https://user-images.githubusercontent.com/1921941/36270515-7f584974-1241-11e8-879d-f61c8605975d.png)

**Comment by SanjanaPai** [comment]
Thanks

**Comment by Ijacson** [comment]
I have a similar problem, but with html5 video. The video reloads on window resize. So I cannot play it in fullscreen. When I press the fullscreen video icon, the window changes its size, and imediately stops the video, coming back to previous size. What can I do?
