### ISSUE TITLE
Table not displaying data correctly

### ISSUE THREAD

**Issue by MB34** [wenzhixin/bootstrap-table#3608]
I have this data coming from an ajax call:

```
[
   {
      "NPI":"1234567890 ",
      "License":"12345",
      "FirstName":"Jane",
      "LastName":"Doe",
      "City":"Anywhere",
      "Specialty":"Dentist",
      "County":"Anderson"
   },
   {
      "NPI":"1234567890 ",
      "License":"12345",
      "FirstName":"John",
      "LastName":"Doe",
      "City":"Anywhere",
      "Specialty":"Dentist",
      "County":"Anderson"
   }
]
```

But it is showing like this:

![image](https://user-images.githubusercontent.com/377196/36330074-e3d92a84-132d-11e8-8815-ea2a6435d39d.png)

Here's my table HTML:

```
<table id="results_table" class="table table-bordered table-striped" data-detail-view="true" data-detail-formatter="detailFormatter">
    <thead>
        <th><input type="checkbox" id="checkall" /></th>
        <th data-field="Specialty" class="center">Provider Type</th>
        <th data-field="NPI" class="center">NPI</th>
        <th data-field="License" class="center">License</th>
        <th data-field="FirstName" class="center">First Name</th>
        <th data-field="LastName" class="center">Last Name</th>
        <th data-field="City" class="center">City</th>
        <th data-field="County" class="center">County</th>
        <th class="center">Edit</th>
        <th class="center">Delete</th>
    </thead>
</table>

```
I need the checkbox and edit/delete columns to be shown as well as the one to expand the row for detail view.

What am I doing wrong here?

**Comment by jimgit** [comment]
Can you provide a JSFiddle so we can help troubleshoot?

**Comment by MB34** [comment]
It will take a little while but I will.

**Comment by jimgit** [comment]
If you could[ modify this jsfiddle](http://jsfiddle.net/jimkennelly/go5njfp2/)

**Comment by MB34** [comment]
It works when I put it in the fiddle but returning the data from ajax, no..

**Comment by MB34** [comment]
Seems the JSON is coming over as a string from ajax but removing the leading and trailing quotes causes more issues. Also, the checkbox isn't showing either

**Comment by MB34** [comment]
I got it working by changing the result type of the function being called by ajax.
However, the checkboxes and Edit/Delete icons are not shown, just a dash in the column.

**Comment by jimgit** [comment]
Please submit a JSFIDDLE - you need to use the formater property (data-formatter) to convert your data to a checkbox , buttons/icons like[ this JSFiddle](http://jsfiddle.net/wenyi/e3nk137y/21/)
