### ISSUE TITLE
 freez header

### ISSUE THREAD

**Issue by RezaErfani67** [wenzhixin/bootstrap-table#3609]
hi all
how can i freez header?

**Comment by jimgit** [comment]
[Maybe this extension?](https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/sticky-header)

**Comment by RezaErfani67** [comment]
as you can see, i add extention but not work...
![image](https://user-images.githubusercontent.com/24381986/36367737-521d4ef2-1569-11e8-8921-8d449bfe59eb.png)

**Comment by Falseee** [comment]
Please provide us an example (jsfiddle).

**Comment by Falseee** [comment]
I close this issue because we got no response/example within 7 days.
