### ISSUE TITLE
onClickRow - disable for td

### ISSUE THREAD

**Issue by Fanda36** [wenzhixin/bootstrap-table#361]
Hi,

how can disable onClickRow event for some td in row? Is any param for td for set onClick false as witch checked (clickToSelect: false)? Or onClickRow have $element of tr and I don't can get index td for exception (if (index == 1) {return;} else {console.log("Clicked");}).

Thanks for answer

**Comment by wenzhixin** [comment]
Now you can set the column option: `clickToSelect` to `false`.
http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options
