### ISSUE TITLE
Third party tooltip integration (qtip2)

### ISSUE THREAD

**Issue by ghost** [wenzhixin/bootstrap-table#3610]
Hi,
I'm trying to use qtip2 as a third pary tooltip plugin but I have a hard time figuring where I should place the following call to Qtip so I can target each link "id" attribute linked to their "popover_qtip" class.

`$('a.popover_qtip').qtip({
	content: {
	       title: 'TEST',
	       text: 'TEST Content',
	       html: true
        }
});`
Initially, I wanted to place it within an "onPostBody" event. But I can't get row data from this.
Anyone to point me in the right direction ?
Thanks.

**Comment by AdiFloDev** [comment]
Hi,
So, what I've done so far and working 👍 
`$(function() {
    
    $('#table-js-activity').on('post-body.bs.table', function (data) {
       	
       	var table_data = $('#table-js-activity').bootstrapTable('getData');

        var popovers = $('#table-js-activity').find('tbody tr td a.popover_qtip');
		
		//console.log(popovers);
		
	    for (var i = 0; i < popovers.length; i++) {
	                  
	        var row_array = [];
	        var row_id = $(popovers[i]).attr('id');	
		       
		    row_array.id = row_id;
			   
			$.each(table_data, function($key, array){
			    	       
				if(array.id == row_id){
				        
					row_array.title = array.designation;
				   	row_array.content =	array.details;	
				}	
		    });

	    	//console.log(row_array);    
	        
	        $(popovers[i]).qtip({
			   
	            content: {
		            title: row_array.title,
		            text: row_array.content,
		            html: true
		        },
		        style: {
					classes: 'qtip-bootstrap',
					width: 800,
				},
				hide: {
			        event: 'unfocus',
			        effect: function() {
		                $(this).slideUp();
		            }
		            
				},
				show: {
					solo: true,
		            effect: function() {
		                $(this).slideDown();
		            }
		        },
		        position: {
			        my: 'bottom left',  // Position my top left...
			        at: 'top right', // at the bottom right of...
			        target: $('a.popover_qtip').attr('id') // my target
			    }
	        });
	     }; 
    });
});`

However, maybe there's a nicer or simpler solution ?

**Comment by jimgit** [comment]
Can you post your question with a JSFIDDLE exampl (http://bootstrap-table.wenzhixin.net.cn/examples/)` - makes it easier for people to answer when we don't have to spend time recreating your environment.

**Comment by wenzhixin** [comment]
```js
$('#table').on('post-body.bs.table', function () {
    $('.show-popover').each(function () {
        $(this).popover({
            content: $(this).data('title'),
            title: $(this).text(),
            trigger: 'hover'
        });
    });
});
```

http://jsfiddle.net/wenyi/e3nk137y/23016/
