### ISSUE TITLE
Bootstrap 4 Issues (CSS/Pagination)

### ISSUE THREAD

**Issue by cgountanis** [wenzhixin/bootstrap-table#3615]
Just wondering if the Bootstrap 4 update will be released soon. Just included a simple screen shot showing the search box taking over the world and the pagination style issues.

![2018-02-21 15_23_54-sso web - firefox developer edition](https://user-images.githubusercontent.com/14899817/36506147-54d8287a-171b-11e8-95f5-f6a599f94fcc.png)

**Comment by cgountanis** [comment]
![2018-02-21 15_25_03-sso web - firefox developer edition](https://user-images.githubusercontent.com/14899817/36506182-7013f538-171b-11e8-8ab0-b47ea9432c36.png)

![2018-02-21 15_25_13-sso web - firefox developer edition](https://user-images.githubusercontent.com/14899817/36506183-7023ed12-171b-11e8-9195-8ac1fe5f4c42.png)

**Comment by cgountanis** [comment]
Here is a JSFiddle to help.

https://jsfiddle.net/ucss0wu5/6/

**Comment by timoline** [comment]
the cdn you use is 1.11.0 in stead of 1.11.1

look inside
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.css

a small bug, hppefully fixed very soon

**Comment by cgountanis** [comment]
So even if I change the CDN from 1.11.1 to 1.11.0 is will not work till fixed? I am having the same issue when I grab all the files with BOWER ("bootstrap-table": "1.11.1") as well.

**Comment by cgountanis** [comment]
Confirmed same issue with the bower version and it does say 1.11.1 on that file.

![image](https://user-images.githubusercontent.com/14899817/36565532-5532ded4-17e6-11e8-8578-a75f4fc2e797.png)

**Comment by timoline** [comment]
sorry, can't reproduce. Can you update  the jsfiddle ?

**Comment by cgountanis** [comment]
The develop version seems to be working. Great!

When will this be available via bower?

https://jsfiddle.net/ucss0wu5/10/

**Comment by cgountanis** [comment]
Let me know if I can help in any way.

**Comment by wenzhixin** [comment]
1.12.0 released.
