### ISSUE TITLE
table如何做到单击一行的时候只选中一行，checkbox可以选中多行的效果？

### ISSUE THREAD

**Issue by zp8821138** [wenzhixin/bootstrap-table#3619]
我试着把singleSelect设置为true 这样会导致只能选中一行，我想要的效果是单击一行数据的时候只选中一行，下次再单击也只能选中一行，勾选checkbox的时候能选中多行，现在我单击了一行，再单击另一行会导致有多行选中，我编辑的时候一次只允许编辑一条记录，这样会导致问题，谢谢了啊

**Comment by wenzhixin** [comment]
你可以自己特殊处理，单击一行数据的时候将其他的行取消选择即可。
