### ISSUE TITLE
Can't encaspulate a row in a form

### ISSUE THREAD

**Issue by lio590** [wenzhixin/bootstrap-table#3625]
I'm trying to encapsulate a row in a form however it couldn't find a way to achieve this. Is this something that is planned for the future ?
In other words I would like to be able to insert HTML / form before <TR> is creted and after </TR>
`<form action="/upMacAddr" method="POST"><tr>...</tr></form>`

**Comment by wenzhixin** [comment]
Please use `<form action="/upMacAddr" method="POST"><table>...</table></form>` instead.
