### ISSUE TITLE
I want build and use my own pagination with this table plugin is it possible to do that ?

### ISSUE THREAD

**Issue by RupaliMahadik** [wenzhixin/bootstrap-table#3626]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by Falseee** [comment]
Currently you cant create your own pagination, if you have a good situation why you should use a custom pagination pls reopen the issue and explain it.

We have a lot of options to modify/configure the existing pagination: https://bootstrap-table.com/docs/api/table-options/#pagination
