### ISSUE TITLE
服务端分页，返回空数据，分页按钮还可以点击

### ISSUE THREAD

**Issue by wd16yuan** [wenzhixin/bootstrap-table#3628]
server端分页，设置 smartDisplay 为 false，使用搜索在返回空数据时候，分页的页码还是最后一次查询到的，显示为“上一页，下一页”，但都可以点击.......
responseHandler: function (res) {
return {
total: res.total || 0,
rows: res.rows || [],
};
},
添加了这个方法，试了没效果

**Comment by 940374250** [comment]
使用的版本是 v1.11.1

**Comment by wenzhixin** [comment]
应该是个bug：http://jsfiddle.net/4r6g4cfu/1028/

**Comment by 940374250** [comment]
@wenzhixin 最后，我设置了smartDisplay = true，空数据就隐藏了分页页码.

**Comment by wenzhixin** [comment]
Fixed in the develop branch.
