### ISSUE TITLE
refreshOptions to refresh the option only, not destroy and init table 

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#3629]
I am using bootstrap-table to load data from server. The data keeps changing on server as the background process is running and the progress of totalRows is pushed through SignalR which sent back the  `totalRows` available to read.

I don't want to refresh the entire table data to avoid thousands of GET requests on server. Is there any way, we can refresh the `totalRows` only and stop the destroy and init of table using `onRefreshOptions` ?

Here is the example JSFiddle - [http://jsfiddle.net/4r6g4cfu/972/](http://jsfiddle.net/4r6g4cfu/972/)

**Comment by jimgit** [comment]
Since you won't be refreshing the table - you could try writing the server information directly to the div tag.  See this[http://jsfiddle.net/ajejw4qL/]( jSFiddle - http://jsfiddle.net/ajejw4qL/)

**Comment by wenzhixin** [comment]
You can use `load` method to solve your problem @vickyrathee : http://jsfiddle.net/4r6g4cfu/1024/
