### ISSUE TITLE
How to get the change event for element inside td

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#3630]
I would like to put a html dropdown (select) element inside a table cell.

I need to get the value of that dropdown when it is changed, but I am not able to get the event "change" fired for that dropdown

Within "click-cell.bs.table", I am not be able to get dropdonw's selected value neither, when I inspect that dropdown, it shows plain html, with no one says "selected", even though it displays correct selected value on screen.

I tried editable extension, but editable extension prevent my another table cell to work with bootstrap datepicker, force me to not use editable

Any suggestions?
Thanks!

**Comment by jimgit** [comment]
Use the data-formatter to build the select statement.  Typically,  your data has id's and the select has the text you want to show the user.

Not a very good example, [but here is where the data-formatter makes the select statement from the data.](http://jsfiddle.net/jimkennelly/17sLeu4u/
)

**Comment by jimgit** [comment]
Sorry - if you want to do data entry via the bootstrapTable,  take a look at the [EDIT extension.](https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable)

**Comment by startovernow** [comment]
@jimgit , thanks for your response.
Sorry I didn't make it clearer, I need to to get the selected value from dropdown WHEN I am clicking on another column's table cell in the same row. I attached a screenshot here, when I click on "Customer A", I want to get that "5.5". Looking at the dropdown, it just plain html, no item is "selected".
The table-editable extension will not work for me because it does not work with bootstrap datepicker I am using in yet another column.
![untitled](https://user-images.githubusercontent.com/18681747/36814451-2b90229c-1c9d-11e8-93fe-d6f9ed9f4822.png)

**Comment by jimgit** [comment]
Take a[ look at the events ](http://bootstrap-table.wenzhixin.net.cn/documentation/#events)- there is a click cell and click row.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
