### ISSUE TITLE
How to set the value of a checkbox

### ISSUE THREAD

**Issue by katiemccann** [wenzhixin/bootstrap-table#3631]
I have a table with checkboxes that's wrapped in a form element. The 'value' of the checkbox that gets sent to the server needs to be the id of the row. I've been messing around with different options in the documentation and can't figure out for the life of me how to get the value of the checkbox to be the ID of the row. 
JSFiddle:
http://jsfiddle.net/katiemccann/0fp4uvpj/7/

**Comment by jimgit** [comment]
Look at this [http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getAllSelections.html](example http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getAllSelections.html)

**Comment by jimgit** [comment]
You can also use the data-formatter to create the html for the checkbox.  See this [http://jsfiddle.net/jimkennelly/4fgzf3qa/](JSFIDDLE http://jsfiddle.net/jimkennelly/4fgzf3qa/)

**Comment by katiemccann** [comment]
Thanks. So if I read these 2 suggestions correctly, the only way to submit the IDs is to write javascript to submit the form? Unfortunately that's probably a deal-breaker for using this plug-in, this is a Rails app and I really don't want to have to break the "rails way" of doing things to work around this. 

This just seems like such a basic thing to need to do, I'm surprised there isn't a much simpler way.

**Comment by jimgit** [comment]
You could wrap the table with a forms tag and it will submit the checked boxes.

**Comment by katiemccann** [comment]
It is wrapped in a form tag, but it's sending "on" as the value for every checked box, I need it to send an ID instead. 


 
 
  On Thu, Mar 1, 2018 at 9:33 AM, Jim<notifications@github.com> wrote:   
You could wrap the table with a forms tag and it will submit the checked boxes.

**Comment by jimgit** [comment]
Check the html - I think you need a name property to get the form to include in the submit?

[See this](http://jsfiddle.net/jimkennelly/0rohmgnv/)

If that doesn't work - post a JSFIDDLE showing your problem.

**Comment by katiemccann** [comment]
OK I got it working using a data-formatter, that was the missing piece. Thanks for the help.

**Comment by sphereweb83** [comment]
@katiemccann Do you mind sharing your fix?
