### ISSUE TITLE
Replacing bootstraptable doesn't call init

### ISSUE THREAD

**Issue by vasakt** [wenzhixin/bootstrap-table#3632]
Having problems replacing a bootstraptable.

Table is created initially and then at a certain point, we wish to destroy and recreate it by doing:

$("#mytable").bootstrapTable("destroy");
$("#mytable").bootstrapTable({
        url: "getpositions.json",
        method: "get",
        queryParams: function(){
        ....
});

While this works correctly in rebuilding the table, it fails to call the init() method again. This is a problem for me because I'm also using bootstrap-table-editable which has a hook into init() to correctly setup editable columns. So I'm not getting the editable columns to be editable any more after this call although they were fine previously.

Am I missing something.

**Comment by jimgit** [comment]
Please post a JSFIDDLE so we can help diagnose the problem.

**Comment by vasakt** [comment]
The app is quite complex. In the course of distilling the jsfiddle, I couldn't reproduce in a more simplified example and finally discovered the cause which was the bootstrap table js being reloaded.
Sorry to waste your time.
