### ISSUE TITLE
bootstrap-table limit number rows to display from mysql table

### ISSUE THREAD

**Issue by bhrochdi** [wenzhixin/bootstrap-table#3633]
Hello,
I use the bootstrap-table plguin to display data from a mysql DB it works perfectly. However my table-bootstrap does not show anything these last days. I have this error in my web console « **SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data** ».
number rows to displayed : 2348
I use echo  **json_encode($data)** to encode the data;
is my code to display the data from bootstap-table:

```
var url = "req.php";
$.get( url, function( data ) {
$.ajaxSetup({async:false});
$.ajaxSetup({ cache: false});
if(data!=null)
{
	$('#table').bootstrapTable('load',data);
	$('#table').bootstrapTable('refresh');
}
else
{
	$('#table').bootstrapTable('destroy'); //Destroy bootstrap table
	$('#table').bootstrapTable();
}
});

```
help me.

**Comment by jimgit** [comment]
Check that your json is valid - one test is to copy it into myjson.com and use the link as the url.  Here is an example.  Put the data into myjson.com - it will validate the json - then substitute the url[ into this example ](http://jsfiddle.net/jimkennelly/e3nk137y/21371/)and post the fiddle if it's still not working.

**Comment by bhrochdi** [comment]
Yes, it is true there is an error in the JSON, caused by a special character "ù" in the replacement by "u" the problem is solved.
Thanks for your help.
