### ISSUE TITLE
Uncaught TypeError when checking a checkbox created via a data-formatter

### ISSUE THREAD

**Issue by katiemccann** [wenzhixin/bootstrap-table#3635]
I have a checkbox column that i'm setting with a data-formatter function in order to set the checkbox value to what I need. 

<th data-field="state" data-formatter="formatCheckbox"></th>

You can see it here:
https://jsfiddle.net/katiemccann/9oaja4bz/3/

Every time I click a checkbox, I get: Uncaught TypeError: Cannot set property 'undefined' of undefined
Coming from this line:
row[that.header.stateField] = checked;

Looking at the code, it looks like the stateField is only getting set if the column type is 'checkbox', which doesn't seem to be the case when the checkbox gets created by a data-formatter function.

Doesn't see to actually break anything (but i'm not 100% sure) but generates a lot of console errors.

JSFiddle:
https://jsfiddle.net/katiemccann/9oaja4bz/3/

**Comment by jimgit** [comment]
Can you use the [data-checkbox property ](http://jsfiddle.net/wenyi/e3nk137y/30/)- this works with all the bootstrap function

**Comment by katiemccann** [comment]
No, because of https://github.com/wenzhixin/bootstrap-table/issues/3631
I needed to set the value of the checkbox to an ID and according to that issue, using a data-formatter seemed to be the only way. 

I tried combining the data-formatter with data-checkbox but ended up with 2 checkboxes in the column.

**Comment by jimgit** [comment]
[JSFIDDLE ](https://jsfiddle.net/jimkennelly/y0z2o8w5/)- remove the select properties from the table tag if you don't want to use them.  Just a suggestion,  look at separating the data from the presentation html.  It will make things much simpler.

**Comment by katiemccann** [comment]
OK that did the trick, thanks.
