### ISSUE TITLE
Search doesn't take into account the "selected" element 

### ISSUE THREAD

**Issue by lio590** [wenzhixin/bootstrap-table#3638]
Search doesn't take into account the "selected" element in a <select> box. When you try to search for a "selected option" it does select all the rows because of course it parses thru <options> and always find the searched value. The expected behavior is that search should take into account only the "selected" option

**Comment by jimgit** [comment]
Please post a JSFIDDLE to demonstrate the problem.

**Comment by lio590** [comment]
here it is https://jsfiddle.net/lio590/9po4u884/13/

**Comment by jimgit** [comment]
[Try this JSFIDDLE ](http://jsfiddle.net/jimkennelly/j2r8ws9d/)and search for yes,no, test, program

**Comment by lio590** [comment]
Correct so you confirmed the bug ;)

**Comment by jimgit** [comment]
No - maybe not implemented - I'll let other judge it as a bug.  @wenzhixin

**Comment by wenzhixin** [comment]
Ref #3648
