### ISSUE TITLE
Setting Bootstrap Table Filter error

### ISSUE THREAD

**Issue by jAddict7** [wenzhixin/bootstrap-table#364]
I have tried to setup bootstrap filter extension but unable to setup while using bootstrap-table-filter.min.js inside extension folder of master branch. Am getting this error, **TypeError: a(...).bootstrapTableFilter is not a function**, even if I include the extension js. What is the correct procedure to setup filters for my table?.
My table configuration,

```
<table id="bt-table" data-toggle="table" data-url="/resources/data.json" data-height="500" data-click-to-select="false" 
                        data-toolbar="#custom-toolbar" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" 
                        data-search="true" data-show-filter="true" data-show-export="true" data-export-types=['txt','excel']>

<script type="text/javascript" src="/resources/js/bootstrap-table.min.js"></script>
<script type="text/javascript" src="/resources/js/bootstrap-table-export.min.js"></script>
<script type="text/javascript" src="/resources/js/bootstrap-table-filter.min.js"></script>
```

As I dig [here](http://wenzhixin.net.cn/p/bootstrap-table/docs/extensions.html). Before bootstrap-table.min.js another filter js is included if I include it filter UI came without field in it? Any example would be appreciated.
**Thanks alot for this tremendous plugin.**

**Comment by nexiaz** [comment]
I am running into the same Error: `Uncaught TypeError: $(...).bootstrapTableFilter is not a function`

The JS Includes:

<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.8.1/bootstrap-table.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
<script src="http://mmogold.eu/assets/vendor/bootstrap-table/extensions/editable/bootstrap-table-editable.js"></script>
<script src="http://mmogold.eu/assets/vendor/bootstrap-table/extensions/filter/bootstrap-table-filter.js"></script>



$('#accountlist').bootstrapTable({
		
		pagination: true,
		showRefresh: true,
		showToggle: true,
		showColumns: true,
		search:true,
		pageSize:20,
		striped: true,
		showFilter: true,
		url: '

[...]

**Comment by wenzhixin** [comment]
Example here: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/561.html
