### ISSUE TITLE
refresh,columns button don`t have same line-height

### ISSUE THREAD

**Issue by huanqingdong** [wenzhixin/bootstrap-table#3640]
I use
jquery ver: 2.2.1
bootstrap ver:3.3.7
bootstrap table ver:1.11.1 

the question is also asked by some people at :http://bbs.csdn.net/topics/392233679?list=lz

**Comment by wenzhixin** [comment]
从来没出现过该问题，应该是没有加：
```
<!DOCTYPE html>
```

**Comment by huanqingdong** [comment]
确实是这个原因
