### ISSUE TITLE
Checkboxes all checked upon initial table load

### ISSUE THREAD

**Issue by katiemccann** [wenzhixin/bootstrap-table#3641]
See: https://jsfiddle.net/katiemccann/xbv2yhq2/

I've already tried the suggestion in https://github.com/wenzhixin/bootstrap-table/issues/3398 (setting data-field to "state" or "") and it hasn't solved it for me.

**Comment by jimgit** [comment]
Use the checkAll method.

[See this JSFiddle](http://jsfiddle.net/jimkennelly/vnjwpp5s/)

**Comment by katiemccann** [comment]
Sorry, not following - that JSFiddle checks all the boxes intentionally. My issue is that mine are all checked upon load, but I don't want them to be.

**Comment by katiemccann** [comment]
OK I finally figured this one out through trial and error. I was setting the initial value of the checkbox field to the ID of the object (ex: <td>1234</td>) which was for some reason causing the checkboxes to all be checked. Leaving it blank (ex: <td></td>) solved it.
