### ISSUE TITLE
能够获取到后台的数据，但是table的样式显示不完全

### ISSUE THREAD

**Issue by hcraderGH** [wenzhixin/bootstrap-table#3643]
![1](https://user-images.githubusercontent.com/19168124/36957897-cc40c97a-2072-11e8-9bd0-11923034a2b4.jpg)
如图片所示：能够显示获取的总数据条数，但是具体的数据信息显示不了

**Comment by wenzhixin** [comment]
查下返回的数据格式跟 column 的 field 是否能对应上

**Comment by wenzhixin** [comment]
假如还有问题的话重新打开问题并提供 jsfiddle，或者使用的代码和console信息，光截图没办法定位问题。
