### ISSUE TITLE
Is there a way to highlight row or value after update(edit)?

### ISSUE THREAD

**Issue by s961744** [wenzhixin/bootstrap-table#3644]
Is there a way to highlight row or value after the edit popover window closed if the value changed?
Thanks a lot.

**Comment by jimgit** [comment]
I had to do this for a previous project.  One way would be to create tracking field for each column you need to highlight.  
Let's say you have the following json:

[{id:1,amount:100}]

Add field with same name but "changed" on the end for each "tracking" field.
[{id:1,amount:100,AmountChanged:0}]

The amount changed field will be used for the CELLSTYLE function to show as normal when 0 but show highlighted when 1

When the user edits and saves the field,  trigger from the [onEditableSave(editable-save.bs.table) event](https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable)  -
 - change the AmountChanged value from 0 to 1.  This will allow the CELLSTYLE formatting to highlight the cell.





Use the table edit extension

**Comment by s961744** [comment]
Thank for your reply.
I tried this to change the value of another field and it worked.
`onEditableSave: function (field, row, oldValue, $el) {
                $table.bootstrapTable('updateRow', {
                    index: row.index,
                    row: {
                        date_s : '2018/03/06'
                    }
                });
            }`

But how to highlight a row?

**Comment by jimgit** [comment]
[Use the ROWSTYLE](http://jsfiddle.net/wenyi/e3nk137y/16/) .  Rowstyle has row as an agrument..  You have access to all values for that row. So it could be something like or'ing the change tracking fields 

if (row.AmountChanged || row.SalaryChanged || row.CostChanged).

**Comment by wenzhixin** [comment]
I think this feature is supported by default:
![image](https://user-images.githubusercontent.com/2117018/37291133-f9061344-2648-11e8-840e-43b1f44b4425.png)

http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!

**Comment by manukieli** [comment]
> Is there a way to highlight row or value after the edit popover window closed if the value changed?
> Thanks a lot.

Great idea.
How it's possible to do this??
