### ISSUE TITLE
Multiple tables initialized with javascript, only the first gets actvive se

### ISSUE THREAD

**Issue by rstubbe** [wenzhixin/bootstrap-table#3646]
I am using 2 bootstrap tables, in to tabs.
The scripts are loaded with the main page.
The actual page with the tables are in a page that is loaded via a ajax call.

When activating the two tables, only the first one gets active, the second one not. 
the console reports 

jQuery.Deferred exception: b.columns[d] is undefined o.prototype.initTable/</<@http://ronald-dev.go.esa.int/pearl/js/bootstrap-table.min.js:7:10947
.each@http://ronald-dev.go.esa.int/pearl/js/jquery-3.3.1.min.js:2:2571
w.prototype.each@http://ronald-dev.go.esa.int/pearl/js/jquery-3.3.1.min.js:2:1238
o.prototype.initTable/<@http://ronald-dev.go.esa.int/pearl/js/bootstrap-table.min.js:7:10754
.each@http://ronald-dev.go.esa.int/pearl/js/jquery-3.3.1.min.js:2:2571
w.prototype.each@http://ronald-dev.go.esa.int/pearl/js/jquery-3.3.1.min.js:2:1238
o.prototype.initTable@http://ronald-dev.go.esa.int/pearl/js/bootstrap-table.min.js:7:10619
o.prototype.init@http://ronald-dev.go.esa.int/pearl/js/bootstrap-table.min.js:7:7451
o@http://ronald-dev.go.esa.int/pearl/js/bootstrap-table.min.js:7:2730
a.fn.bootstrapTable/<@http://ronald-dev.go.esa.int/pearl/js/bootstrap-table.min.js:8:22032
.each@http://ronald-dev.go.esa.int/pearl/js/jquery-3.3.1.min.js:2:2571
w.prototype.each@http://ronald-dev.go.esa.int/pearl/js/jquery-3.3.1.min.js:2:1238
a.fn.bootstrapTable@http://ronald-dev.go.esa.int/pearl/js/bootstrap-table.min.js:8:21723
@http://ronald-dev.go.esa.int/pearl/:21:4
a/</l@http://ronald-dev.go.esa.int/pearl/js/jquery-3.3.1.min.js:2:29373
a/</c<@http://ronald-dev.go.esa.int/pearl/js/jquery-3.3.1.min.js:2:29677
 undefined

It works correctly if it is run on a single pc (server/client), it fails when running on a server/client configuration.
The network tools show that the javascripts are loaded approx 300 ms before the load of the html page begins.

The tables are in tabs "roles" and "geo target"
[jsfiddle]https://jsfiddle.net/rstubbe/cwrpgmbe/7/

**Comment by jimgit** [comment]
strip out everything except for your two table and submit another jsfiddle.   Start with just a few rows of data for each table - see if that works first - if not summit that as a jsfiddle.

**Comment by rstubbe** [comment]
I actually found the issue, one table generated more cells in a row that the header.
