### ISSUE TITLE
Search Disregard HTML in TD

### ISSUE THREAD

**Issue by cgountanis** [wenzhixin/bootstrap-table#3648]
I have a column with HTML data and I would like the search functionality to ignore HTML values and just parse the ABCDE value within the hyperlink. Is that possible?

If I search for "AB" in this example it pulls both records due to matching the href vales as well.

```
<tr>
<td>
<a href="/X/XX?AB=123&CD=Index&groupid=fdadd7e9">ABCDE</a>
</td>
</tr>
<tr>
<td>
<a href="/X/XX?AB=321&CD=Index&groupid=fdadd7e9">12345</a>
</td>
</tr>
```

**Comment by jimgit** [comment]
[Look at the customSearch on the documentation page.  ](http://bootstrap-table.wenzhixin.net.cn/documentation/)  

Here's a work around that worked well for me.  I had a similar problem and had about 20 fields for which I wanted search to work on about 20 and some were concatonations of two fields.  My solution was to create a custom field in my database view and use server side pagination.  When search runs, it passes the values to the server and you can use any custom search logic on the server side.

**Comment by cgountanis** [comment]
jQuery DataTable which we replaced with this awesome platform, has a tag that just smartly filters out the HTML on the data rows on specific columns. SO I had to ask. My work around is going to be an [Action] column and just leave the sorting/searching to static data.

**Comment by jimgit** [comment]
Not sure it can't be done the way you want - that's just what I did.  [You could also look at the filter extension which gives a "per column" search.](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html)

**Comment by wenzhixin** [comment]
If you are using `formatter` to format the column, I think you can set `searchFormatter` to `false` to solve your problem:
http://jsfiddle.net/e3nk137y/22751/
http://jsfiddle.net/e3nk137y/22753/

**Comment by cgountanis** [comment]
I just moved the actions to the left most column (search disabled), to match the rest of the site, was a good work around.
