### ISSUE TITLE
We need to custom the formatNoMatches message use bootstrapTable method.

### ISSUE THREAD

**Issue by wenzhixin** [wenzhixin/bootstrap-table#365]
"No matching records found", we can specify a custom message.

**Comment by djhvscf** [comment]
You should close this issue! @wenzhixin

**Comment by wenzhixin** [comment]
Close it.

**Comment by MonrealRyan** [comment]
Hi,
may i know how to set a custom ```formatNoMatches```  
e.g
from ```No matching records found``` to ````No data found``

thanks.

**Comment by wenzhixin** [comment]
```js
bootstrapTable({
    formatNoMatches: function () {
        return 'No data found';
    }
});
```
@MonrealRyan

**Comment by papakonstantinouko** [comment]
Hello, is it possible to hide the formatNoMatches messages?

**Comment by djhvscf** [comment]
```js
bootstrapTable({
    formatNoMatches: function () {
        return '';
    }
});
```
@papakonstantinouko

**Comment by papakonstantinouko** [comment]
Thank you Dennis

**Comment by MonrealRyan** [comment]
Thanks everyone. sorry for the late reply. it helps me a lot.

**Comment by jotasixto** [comment]
The function formatNoMatches is called two times if not matches or empty data.
I use a variable at bootstrap Table scope to check if called a second time. This way I know that I haven't data to show.
`	       ......
               var loadingData = true;
               $('#table_data').bootstrapTable({	
                        ......
                        formatLoadingMessage: function () {
			    	loadingData = true;
        			return '';
    			},
    			formatNoMatches: function () {
				    if (loadingData){
				    	loadingData = false;
				    	return 'Loading data, wait...';
				    }else{
				    	return 'No data found.';
				    }
    			},
               });
               ......
`

**Comment by alexandergantikow** [comment]
I need a different warning for each table when there is no data. I have written a solution that gets the 'no matches' message from a data attribute of the table. This has the advantage that the attribute can also be filled depending on the i18n localisation.

HTML:
`<table id="my-table" class="table" data-toggle="table" data-locale="de-DE"  data-no-match="Sorry, there are no results!">`

JavaScript:
```
$('.table').bootstrapTable({   
	formatNoMatches: function () {
		return this.noMatch;
	},
});
```

I would have expected this functionality to already be part of Bootstrap-Table.

**Comment by wenzhixin** [comment]
ref #7058
