### ISSUE TITLE
customSearch implementation

### ISSUE THREAD

**Issue by chrissharp80** [wenzhixin/bootstrap-table#3650]
This is not a bug report. I have implemented a client-side custom search using the `customSearch` attribute and wondered if this is something you would be interested in as a possible reference. This search is an "OR" search on any number of terms but it can easily be modified. Below is the code:

**Custom Search Code:**
```
/**
 * Overrides the default search of Bootstrap-table. This search
 * allows for complex input such as 'abc def'. The input is space
 * delimited. In this example any row that matches 'abc' or 'def'
 * will be displayed. If the search is empty then we want to
 * show all rows. Otherwise, we want to show only the rows that
 * have columns which contain the search input.
 *
 * @param $table
 * @param input
 */
function customTableSearch($table, input) {
    let rows = $table.bootstrapTable('getData');
    let keyterms = input.split(' ');

    // Hide all rows before showing filtered ones or show all if string is empty
    if (input) {
        toggleAllTableRows($table, rows, 'hideRow');
    } else {
        toggleAllTableRows($table, rows, 'showRow');
    }

    // Find rows that match the search input and display them
    for (let keyterm of keyterms) {
        for (let i = 0; i < rows.length; i++) {
            if (Object.keys(rows[i]).map(key => rows[i][key]).find( (e) => {
                return typeof e === 'string' && e.indexOf(keyterm) > -1;
            })) {
                $table.bootstrapTable('showRow', {index:i});
            }
        }
    }
}

/**
 * Shows or hides all table rows for the passed in table. This
 * is a helper for the custom search, which shows rows that match
 * the search criteria.
 *
 * @param $table
 * @param rows
 * @param action
 */
function toggleAllTableRows($table, rows, action) {
    for (let i = 0; i < rows.length; i++) {
        $table.bootstrapTable(action, {index:i});
    }
}
```

**Table Parameters:** 
```
 search: true,
 customSearch: function(text) {
    customTableSearch($('#example-table'), text);
 },
 maintainSelected: true,
 trimOnSearch: false,
```

**Comment by jimgit** [comment]
Thanks - will be using it .  

Then, I was thinking it might be nice to have search on a per column basis and relooked at the documentation and saw this already existed.

![image](https://user-images.githubusercontent.com/1921941/37248035-5ff8ea40-248c-11e8-8717-296c0fa1ab7e.png)

**Comment by chrissharp80** [comment]
It does exist already but I believe that option will place a search input field over each column. I wrote the above function avoid that and use the existing search input field.

**Comment by chrissharp80** [comment]
I hit a pretty big snag with showing the hidden rows once the search was cleared so I checked the docs for a way to show all hidden. There is a function called `getAllHidden()` which, if passed a boolean true, claims it will not only get the hidden rows but display them. Apparently, this was never implemented in the bootstrap-table code so I implemented that feature in my project and forked this project and created a PR with that fix. See it here to see what I did in case it hasn't been fixed and you need it: https://github.com/wenzhixin/bootstrap-table/pull/3655

Here is my modified code that restores the table almost instantly:

```
/**
 * Overrides the default search of Bootstrap-table. This search
 * allows for complex input such as 'abc def'. The input is space
 * delimited. In this example any row that matches 'abc' or 'def'
 * will be displayed. If the search is empty then we want to
 * show all rows. Otherwise, we want to hide only the rows which
 * do not meet any of the search input.
 *
 * @param $table
 * @param input
 */
function customTableSearch($table, input) {
  let rows = $table.bootstrapTable('getData');
  let keyterms = input.split(' ');

  // Hide all rows before showing filtered ones or show all if string is empty/undefined
  if (input) {
    hideAllTableRows($table, rows);
    // Find rows that match the search input and display them
    for (let keyterm of keyterms) {
      for (let i = 0; i < rows.length; i++) {
        if (Object.keys(rows[i]).map(key => rows[i][key]).find( (e) => {
            return typeof e === 'string' && e.indexOf(keyterm) > -1;
          })) {
          $table.bootstrapTable('showRow', {index:i});
        }
      }
    }
  } else {
    $table.bootstrapTable('getHiddenRows', true);
  }
}

/**
 * Shows or hides all table rows for the passed in table. This
 * is a helper for the custom search, which shows rows that match
 * the search criteria.
 *
 * @param $table
 * @param rows
 */
function hideAllTableRows($table, rows) {
  for (let i = 0; i < rows.length; i++) {
    $table.bootstrapTable('hideRow', {index:i});
  }
}
```

**Comment by pinkrrr** [comment]
Hello.
For my set of data this hide/show routine end up being major ineffective to the point of hanging up browser window for good couple of seconds. 
End up with creating temp array of data to which appropriate rows are pushed and using 'load' method on table likewise to an original script.

**Comment by chrissharp80** [comment]
Yes. I also found this to be extremely slow on large datasets. I'm currently using a server-side approach but am considering a new approach to client-side searching. If I find a way to do this that is more efficient then I'll post it. Just curious but how large is your dataset?

**Comment by pinkrrr** [comment]
Used it for a table of 107 rows. However, i think there was a lag with a smaller objects count as well.
Apparently API's more efficient working with chunk of rows instead of dealing with them by one, which is expected, considering that 'load' method updates a field in bootstrapTable object instead of making a call for every row. This way those 107 rows are getting filtered as soon as i enter a key.

**Comment by wenzhixin** [comment]
Supported this feature in the latest version: https://examples.bootstrap-table.com/index.html#options/custom-search.html
https://bootstrap-table.com/docs/api/table-options/#customsearch
