### ISSUE TITLE
Cant have two tables on the same page

### ISSUE THREAD

**Issue by MrPatrickHenry** [wenzhixin/bootstrap-table#3651]
Short and descriptive example bug report title

I can have one table display fine, but when I try for two its no go for the second just recieve 
TypeError: b.columns[d] is undefined
[Learn More] in the console 

Make one table confirm working as expected
copy and paste chnage the table id 
check table to no init

not sure why i can't show two tables on the same page if they are uniqu named

**Comment by jimgit** [comment]
You can have multiple bootstrapTables on the same page - please include a JSFIDDLE of your problem.   
 Here are many examples you can start with -[ add your second table and submit your JSFIDDLE](http://bootstrap-table.wenzhixin.net.cn/examples/)

**Comment by jimgit** [comment]
[Here's two tables](http://jsfiddle.net/jimkennelly/e3nk137y/22676/)

**Comment by wenzhixin** [comment]
Yes, I don't think it is a bug.
