### ISSUE TITLE
onCheckAll/onUncheckAll  sometimes get rows=[]

### ISSUE THREAD

**Issue by thurthday** [wenzhixin/bootstrap-table#3654]
when I click to checkAll or uncheckAll  , sometimes get rows = []

function onCheckAll(rows) {
     console.log(rows) // print [] when it is supposed to print an Array with a few items
}

**Comment by jimgit** [comment]
Thought that I had used that before but noticed the problem as you have stated- [see this JSFIDDLE](http://jsfiddle.net/jimkennelly/ddogjgeu/)

**Comment by wenzhixin** [comment]
http://jsfiddle.net/ddogjgeu/4/, `checkAll` you will get a selection array and `uncheckAll` you will get an empty array.
