### ISSUE TITLE
Error on toggle button

### ISSUE THREAD

**Issue by CherryAnt** [wenzhixin/bootstrap-table#3656]
Hi, 
You got an error on your code, you can see at your code that you are using:
                toggleOff: 'glyphicon-list-alt icon-list-alt',
                toggleOn: 'glyphicon-list-alt icon-list-alt',
But on button creation you are using:
        if (this.options.showToggle) {
            html.push(sprintf('<button class="btn' +
                    sprintf(' btn-%s', this.options.buttonsClass) +
                    sprintf(' btn-%s', this.options.iconSize) +
                    '" type="button" name="toggle" aria-label="toggle" title="%s">',
                    this.options.formatToggle()),
                sprintf('<i class="%s %s"></i>', this.options.iconsPrefix, this.options.icons.toggle),
                '</button>');
        }
You got an error there because this.options.icons.toggle doesnt exist

**Comment by mohshraim** [comment]
the toggle design incomplete 
this screen shot from bootstrap-table website documentation
![table](https://user-images.githubusercontent.com/16401732/37564438-aa992fca-2a9e-11e8-8579-be71c0b7c2c4.png)

**Comment by lpawlak** [comment]
I have the same problem as @mohshraim on latest version (1.12.1).
A quick fix is to add new icon definition called toggle in file bootstrap-table.js
toggle: 'glyphicon-list-alt icon-list-alt'
For me is 31 line:
![toggle](https://user-images.githubusercontent.com/8555321/38973844-f8db7806-43a7-11e8-83c4-c60d8765ef73.JPG)
