### ISSUE TITLE
Release 1.12.0 Issue : 'opencollective' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by smhnkmr** [wenzhixin/bootstrap-table#3657]
With the latest release of 1.12.0, I am getting the 'opencollective' is not recognized as an internal or external command error when deploying in production.

I see it's because of the latest addition of opencollective package. As mentioned in the opencollective-postinstall documentation (https://github.com/opencollective/opencollective-postinstall), the exit 0 flag should be added along with postinstall command to make it work in production.

> Why || exit 0 in scripts.postinstall?
> Since we are adding the dependency in devDependencies, the script ./node_modules/.bin/opencollective-postinstall won't be installed in production. Therefore, the postinstall script will return an error and will interrupt the npm install process. Adding || exit 0 makes sure that this postinstall script always returns true.

Can you add this fix please?

**Comment by wenzhixin** [comment]
Thanks for your feedback, I think we would release a new version to fix this problem.
