### ISSUE TITLE
表格的表头重复显示

### ISSUE THREAD

**Issue by liuweiGit** [wenzhixin/bootstrap-table#3659]
表格间切换太快就会出现表头重复现象
![bug](https://user-images.githubusercontent.com/19206107/37276714-875c8da2-261d-11e8-93a5-8cf9cd5b8bfb.png)

**Comment by wenzhixin** [comment]
不懂切换太快是什么意思，麻烦提供下 jsfiddle 和重现步骤。

**Comment by liuweiGit** [comment]
createDefaultTree({
          tree: '#data-tree',
          data: nodes,
          onNodeSelected: function (event, node) {
            if (!$.isEmptyObject(dataAuth.node) && dataAuth.node.id == node.id) {
              return;
            }
            dataAuth.node = node;
            $('#data-table').bootstrapTable('destroy');
            $('#file-table').bootstrapTable('destroy');
            $('#archives-table').bootstrapTable('destroy');
            if (node.sId === '0') {
              $('#data-table').html('<div class="folder-prompt">未设置结构！</div>');
              return;
            }
            $('#data-table').html('');
            post({ESArchivePermission: 'PreGetPackageRight'}, {path: node.path, treeid: node.treeId}, function (res) {
              if (!res.length) {
                return;
              }
              dataAuth.strus = res;
              switch (res.length) {
                case 1:
                  $('#data-tab li:eq(2)').show();
                  $('#data-tab li:eq(2) a').html('<span class="badge">3</span>' + dataAuth.strus[0].title);
                  $('#data-tab li:eq(3)').hide();
                  dataAuth.createTable({
                    table: '#data-table',
                    toolbarId: 'data-toolbar',
                    dataPath: dataAuth.strus[0].path
                  });
                  $('#data-tab li:eq(4)').show();
                  $('#data-tab li:eq(4) a').html('<span class="badge">4</span> 电子文件级');
                  dataAuth.createTable({
                    table: '#file-table',
                    toolbarId: 'file-toolbar',
                    dataPath: dataAuth.strus[0].path + '-@file'
                  });

                  break;
                case 2:
                  $('#data-tab li:eq(2)').show();
                  $('#data-tab li:eq(2) a').html('<span class="badge">3</span>' + dataAuth.strus[0].title);
                  dataAuth.createTable({
                    table: '#data-table',
                    toolbarId: 'data-toolbar',
                    dataPath: dataAuth.strus[0].path
                  });
                  $('#data-tab li:eq(3)').show();
                  $('#data-tab li:eq(3) a').html('<span class="badge">4</span>' + dataAuth.strus[1].title);
                  dataAuth.createTable({
                    table: '#archives-table',
                    toolbarId: 'archives-toolbar',
                    dataPath: dataAuth.strus[1].path
                  });

                  $('#data-tab li:eq(4)').show();
                  $('#data-tab li:eq(4) a').html('<span class="badge">5</span> 电子文件级');
                  dataAuth.createTable({
                    table: '#file-table',
                    toolbarId: 'file-toolbar',
                    dataPath: dataAuth.strus[0].path + '-@file'
                  });
                  break;
              }
            });
          }
        });
      });
代码大致这样,每次点击树节点,表格都重新创建表格,但是这几个表格之间在一个tab页中切换,就会出现上述问题,不知道您是否能明白我表达的意思

**Comment by wenzhixin** [comment]
不是很明白，不过我觉得你可以不要每次都去 destroy 表格。

**Comment by liuweiGit** [comment]
ok

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!

**Comment by UNshbush** [comment]
> createDefaultTree({
> tree: '#data-tree',
> data: nodes,
> onNodeSelected: function (event, node) {
> if (!$.isEmptyObject(dataAuth.node) && dataAuth.node.id == node.id) {
> return;
> }
> dataAuth.node = node;
> $('#data-table').bootstrapTable('destroy');
> $('#file-table').bootstrapTable('destroy');
> $('#archives-table').bootstrapTable('destroy');
> if (node.sId === '0') {
> $('#data-table').html('
> 
> 未设置结构！
> ');
> return;
> }
> $('#data-table').html('');
> post({ESArchivePermission: 'PreGetPackageRight'}, {path: node.path, treeid: node.treeId}, function (res) {
> if (!res.length) {
> return;
> }
> dataAuth.strus = res;
> switch (res.length) {
> case 1:
> $('#data-tab li:eq(2)').show();
> $('#data-tab li:eq(2) a').html('3' + dataAuth.strus[0].title);
> $('#data-tab li:eq(3)').hide();
> dataAuth.createTable({
> table: '#data-table',
> toolbarId: 'data-toolbar',
> dataPath: dataAuth.strus[0].path
> });
> $('#data-tab li:eq(4)').show();
> $('#data-tab li:eq(4) a').html('4 电子文件级');
> dataAuth.createTable({
> table: '#file-table',
> toolbarId: 'file-toolbar',
> dataPath: dataAuth.strus[0].path + '-@file'
> });
> ```
>               break;
>             case 2:
>               $('#data-tab li:eq(2)').show();
>               $('#data-tab li:eq(2) a').html('<span class="badge">3</span>' + dataAuth.strus[0].title);
>               dataAuth.createTable({
>                 table: '#data-table',
>                 toolbarId: 'data-toolbar',
>                 dataPath: dataAuth.strus[0].path
>               });
>               $('#data-tab li:eq(3)').show();
>               $('#data-tab li:eq(3) a').html('<span class="badge">4</span>' + dataAuth.strus[1].title);
>               dataAuth.createTable({
>                 table: '#archives-table',
>                 toolbarId: 'archives-toolbar',
>                 dataPath: dataAuth.strus[1].path
>               });
> 
>               $('#data-tab li:eq(4)').show();
>               $('#data-tab li:eq(4) a').html('<span class="badge">5</span> 电子文件级');
>               dataAuth.createTable({
>                 table: '#file-table',
>                 toolbarId: 'file-toolbar',
>                 dataPath: dataAuth.strus[0].path + '-@file'
>               });
>               break;
>           }
>         });
>       }
>     });
>   });
> ```
> 
> 代码大致这样,每次点击树节点,表格都重新创建表格,但是这几个表格之间在一个tab页中切换,就会出现上述问题,不知道您是否能明白我表达的意思

请问您解决了这个问题吗？我也是和您类似的情况，通过单击事件，重新加载bootstrap-table，然后出现了表头重复的问题。
