### ISSUE TITLE
bootstrap 4 and mobile extension

### ISSUE THREAD

**Issue by timoline** [wenzhixin/bootstrap-table#3661]
bt 1.12.0
on custom bar the icon to show detail view does not show

**Comment by wenzhixin** [comment]
We have released 1.12.1 to fixed this bug.

**Comment by timoline** [comment]
sorry, but 1.12.1 looks the same...am I doing something wrong?

using this cdn
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/extensions/mobile/bootstrap-table-mobile.js

**Comment by wenzhixin** [comment]
Have you updated the bootstrap-table.js?

**Comment by timoline** [comment]
Yes Both CSS and js

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by timoline** [comment]
So, it works for you.... can you please show an example it should work?

**Comment by wenzhixin** [comment]
Example: [Bootstrap4 and mobile extension](http://jsfiddle.net/wenyi/e3nk137y/24075/)

**Comment by timoline** [comment]
thx I found it...

when I use thid cdn it doesnt work
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.js

this one works fine
https://rawgit.com/wenzhixin/bootstrap-table/develop/src/bootstrap-table.js
