### ISSUE TITLE
bootstrap 4 and export extension

### ISSUE THREAD

**Issue by timoline** [wenzhixin/bootstrap-table#3662]
bt 1.12.0
on custom bar the export dropdown menu looks weird

**Comment by timoline** [comment]
http://jsfiddle.net/e3nk137y/24290/

**Comment by wenzhixin** [comment]
This bug fixed in the develop, and will release in next version.
Example here: http://jsfiddle.net/wenyi/e3nk137y/25378/

**Comment by timoline** [comment]
thanks!

**Comment by reinaldo-gomes** [comment]
May I ask why this haven't been released yet?

**Comment by wenzhixin** [comment]
Will be resolved in the next release.
