### ISSUE TITLE
Slow sorting on some columns

### ISSUE THREAD

**Issue by Langer911** [wenzhixin/bootstrap-table#3663]
Hi

I am working on a MVC (C#) project and I am using this version of bootstrap table (//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js) but I am having performance problems at the moment of sorting some columns. It takes almost 5 minutes for some columns and 5 seconds for others. Searching and pagination is fast on every column. This is my code:

<table id="randomTable"  data-pagination="true" data-search="true" data-height="auto" >
    <thead>
        <tr>
            <th data-field="TRANSACTIONID" data-align="center" data-sortable="true">TRANSACTIONID</th>
            <th data-field="MACGRP" data-align="center" data-sortable="true">MACGRP</th>
            <th data-field="MACID" data-align="center" data-sortable="true">MACID</th>
            <th data-field="ORDID" data-align="center" data-sortable="true">ORDID</th>
            <th data-field="ORDSPLIT" data-align="center" data-sortable="true">ORDSPLIT</th>
            <th data-field="LINID" data-align="center" data-sortable="true">LINID</th>     
            <th data-field="EVTDATETIME" data-align="center" data-sortable="true">EVTDATETIME</th>
            <th data-field="MATID" data-align="center" data-sortable="true">MATID</th>
            <th data-field="PRODID" data-align="center" data-sortable="true">PRODID</th>
            <th data-field="EVTDESC" data-align="center" data-sortable="true">EVTDESC</th>
            <th data-field="NUMATTR" data-align="center" data-sortable="true">NUMATTR</th>
        </tr>
    </thead>

</table>

var jsonDataCall;
            $(function () {
                $.getJSON("@Url.Action("Get", "Home")", function (result) {
                    jsonDataCall = result;
                    var $table = $('#randomTable').bootstrapTable({
                        data: jsonDataCall,
                        contentType: "application/json; charset=utf-8"
                    });
                });
            });

This is an example of my Json file:

[{"TRANSACTIONID":312,"MACGRP":"200","MACID":"201","ORDID":"92004496E","ORDSPLIT":"92004496E_01","LINID":"0010","EVTDATETIME":"2017-10-29T17:51:22.72","MATID":"11833SPL","PRODID":"01234568123454","EVTDESC":"Quantity (R)","NUMATTR":"2"},{"TRANSACTIONID":313,"MACGRP":"200","MACID":"202","ORDID":"92004496E","ORDSPLIT":"92004496E_01","LINID":"0020","EVTDATETIME":"2017-10-29T17:51:22.727","MATID":"11833SPL","PRODID":"11234568123451","EVTDESC":"Quantity (R)","NUMATTR":"2"},{"TRANSACTIONID":314,"MACGRP":"200","MACID":"203","ORDID":"92004496E","ORDSPLIT":"92004496E_01","LINID":"0030","EVTDATETIME":"2017-10-29T17:51:22.74","MATID":"11833SPL","PRODID":"21234568123458","EVTDESC":"Quantity (R)","NUMATTR":"2"},{"TRANSACTIONID":315,"MACGRP":"200","MACID":"204","ORDID":"92004496E","ORDSPLIT":"92004496E_01","LINID":"0040","EVTDATETIME":"2017-10-29T17:51:22.743","MATID":"11833SPL","PRODID":"31234568123455","EVTDESC":"Quantity (R)","NUMATTR":"2"}]

Any help would be appreciated it.

**Comment by jimgit** [comment]
[Here is a JSFIDDLE for](http://jsfiddle.net/wenyi/e3nk137y/13/) using local data - change it to your settings and see if you have the same problem.

**Comment by Langer911** [comment]
It works well with that data. The problem is with my data, there are 100000 records and I got an error on fiddle (413 error-entity too large).

**Comment by jimgit** [comment]
You should be using[ server side pagination for that many records.](http://issues.wenzhixin.net.cn/bootstrap-table/#issues/431.html)

**Comment by Langer911** [comment]
I tried to use the server side pagination, it returns me all the records but the sorting, searching and pagination is not working. I use this code (https://github.com/wenzhixin/bootstrap-table-examples/blob/master/issues/431.html). Do I need to create a logic for searching, sorting and pagination too?

**Comment by jimgit** [comment]
Yes - you need to get the number of records to return - in mvc/entity framework,  I use the "take" verb, the order by and the search parameters.  For example, if the user has selected 100 records per page, order by BirthDate and search for "abc" the results is something like

db.PeopleData.where (fields contain abc).orderby(Birthdate).take(100)

**Comment by wenzhixin** [comment]
Yes, you should be using server side pagination because your response data is so big.
Example: http://issues.wenzhixin.net.cn/bootstrap-table/, and the server url:
http://issues.wenzhixin.net.cn/examples/bootstrap_table/data?search=&order=asc&offset=0&limit=10
