### ISSUE TITLE
为何这么流行的一个js库，其文档做的这么差？

### ISSUE THREAD

**Issue by xuzhen1994** [wenzhixin/bootstrap-table#3664]
http://bootstrap-table.wenzhixin.net.cn/zh-cn/examples/
此页面加载要好久，且其中的example有70%左右都跑不起来。

**Comment by F4NNIU** [comment]
可能是因为网站带宽不够。
晚上还是可以打开的，白天非常慢。

**Comment by F4NNIU** [comment]
给 Bootstrap-Table 捐赠了 88.88 元，感谢。

![image](https://user-images.githubusercontent.com/3390878/37319334-aabea366-26a9-11e8-8069-704b8a1a9b9a.png)

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/zh-cn/examples/ 这里的例子是基于 jsfiddle 的，#1765，你打不开应该是网络问题！你可以看 http://issues.wenzhixin.net.cn/bootstrap-table/ 这里的例子。

**Comment by xuzhen1994** [comment]
已经选用jsGrid了，感谢！

**Comment by wenzhixin** [comment]
OK
