### ISSUE TITLE
`data-pagination-loop` does not give any effect

### ISSUE THREAD

**Issue by dieselburner** [wenzhixin/bootstrap-table#3667]
I'm trying to prevent pagination loop by setting the relevant option:

```html
<table id="table"
       ...
       data-pagination="true"
       data-pagination-loop="false"
       ...
       data-toggle="table">
```

However, this does not work.

Using v1.11.1 from Cloudflare CDN.

See #2414, 55059c508945bc17ab4f943e88e9b67e396487fb.

**Comment by jimgit** [comment]
Not sure if it will help but [try the latest version](http://bootstrap-table.wenzhixin.net.cn/getting-started/)

`
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.css">


<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>


<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/locale/bootstrap-table-zh-CN.min.js"></script>`

**Comment by dieselburner** [comment]
Works with v1.12.1. Thanks.
