### ISSUE TITLE
[Reorder Rows] Keep order after refresh

### ISSUE THREAD

**Issue by clempe** [wenzhixin/bootstrap-table#3668]
I created a table which is sortable and the rows can be reordered via drag and drop. The data is loaded via ajax. When I reorder the rows via drag & drop, then refresh the table, the order will be reset.
Is it possible, to maintain the order after refreshing?

Example [jsfiddle](https://jsfiddle.net/clempe/1ehuLmw0/88/)
1. Sort column e.g. id
2. Reorder with drag & drop
3. Refresh table
4. Table will be sorted by id

**Comment by djhvscf** [comment]
This feature is not supported since this extension does not work directly with server side

**Comment by UtechtDustin** [comment]
Use the [onReorderRow](https://bootstrap-table.com/docs/extensions/reorder-rows/#onreorderrowreorder-rowbstable) event to send the new order to your server and build your table with that order.
