### ISSUE TITLE
not able to get card view: version 1.12.1

### ISSUE THREAD

**Issue by Sanjana235** [wenzhixin/bootstrap-table#3670]
responsive: true,
 responsiveBreakPoint: 480,
 responsiveClass: "bootstrap-table-cardview",

I am using this to bring in responsive card view for mobile. this was working in version 1.10 but it's not working now that I have updated the bootstrap code. How I do this in either of the versions?

**Comment by uniwit** [comment]
sprintf('<i class="%s %s"></i>', this.options.iconsPrefix, this.options.icons.toggle),  这个地方没考虑好bootstrap 3  和 bootstrap 4 的icons设置的区别

bootstrap 3 的设置 icons {toggleOff 和  toggleOn }.

**Comment by wenzhixin** [comment]
最新版本已经修复改问题。
