### ISSUE TITLE
1.12.1表格table-toolbar有个小小问题

### ISSUE THREAD

**Issue by uniwit** [wenzhixin/bootstrap-table#3671]
sprintf('', this.options.iconsPrefix, this.options.icons.toggle), 这个地方没考虑好bootstrap 3 和 bootstrap 4 的icons设置的区别

bootstrap 3 的设置 icons {toggleOff 和 toggleOn }. 
在 bootstrap 3  下 切换按钮不显示

**Comment by wuxue107** [comment]
遇到相同问题

**Comment by wenzhixin** [comment]
已在 develop 中解决改问题，等待下个发版。
