### ISSUE TITLE
Bootstrap Dropdown Not Visible

### ISSUE THREAD

**Issue by cgountanis** [wenzhixin/bootstrap-table#3672]
Does anyone have a quick fix for something like this when the table is small?

https://jsfiddle.net/bshasvbp/2/

![image](https://user-images.githubusercontent.com/14899817/37430817-5a584c4e-27a1-11e8-9330-6ce889826d2d.png)

**Comment by cgountanis** [comment]
Anyway to have the dropdown which uses popper.js I believe show over the table when small?

**Comment by cgountanis** [comment]
Maybe a data-min-height?

**Comment by cgountanis** [comment]
Updated https://jsfiddle.net/bshasvbp/3/

**Comment by jimgit** [comment]
How about a modal popup?  [See this jsfiddle](http://jsfiddle.net/jjfzeqmd/)

**Comment by cgountanis** [comment]
Interesting workaround. If the table had a min-height I could solve this as well. Not really an issue with 2-3 records.

**Comment by cgountanis** [comment]
I found a simple solution using data-boundary="viewport".

https://github.com/twbs/bootstrap/issues/25850#issuecomment-373199401
