### ISSUE TITLE
How to simultaneously have different properties on the same column in the table vs insertRow?

### ISSUE THREAD

**Issue by joanvera** [wenzhixin/bootstrap-table#3677]
I have a column that needs to be read only for the existing record but editable when a row is added.
Is there a way to do this? I have poured through the documentation and cannot find additional options for the insertRow option for the bootstrapTable call.  Is there another way to set/change this?

**Comment by jimgit** [comment]
If you submit a jsfiddle with editable and new row addition - somebody may be able to figure out a way.

**Comment by Falseee** [comment]
I close this issue because its 1 year old and we got no example/jsfiddle, if you still need help with that pls provide us an example.
