### ISSUE TITLE
click event for multiple tables?

### ISSUE THREAD

**Issue by voordev** [wenzhixin/bootstrap-table#3678]
Im rendering multiple tables inside bootstrap tabs.
They all have the div name _table_ 

I would like to be able to have click row events for each table. 
Currently it only works for the first, open tab with table.

Using current javascript:

```
$( document ).ready(function() {
    $("#table").on("click-cell.bs.table", function (field, value, row, $el) {
        window.location.href = "/myurl/" + $el.uuid;
    });
});
```

How can I modify this so all tables work? So that I can click all the tables on any row and the click event is fired for all of them?

**Comment by jimgit** [comment]
I would suggest NOT having duplicate ids - use classes when you want common functionality.  I think you mean table id (not div id)?   If you are using DIV (but I don't think so) maybe something like 

$( "#table table:first-child" )

Please post a JSFIDDLE

**Comment by voordev** [comment]
@jimgit 
Its just a page with tabs and multiple tables. 
I indeed mean the DIV named "table"
Indeed each table has the same name.

Since we create the tabs with bootstrap dynamically I cannot hardcode the table id's. I have to use a 'catch all click event' somehow, would this be possible?

**Comment by voordev** [comment]
So I managed to create a unique ID for every table.


```
<div class="tab-pane " id="moderated"><table data-page-list='[500, 1000, 5000]' data-side-pagination='server' data-toggle='table' data-url='/moderated.json' div='table_moderated'>
```
Now I assume If im using some wildcard inside my jquery method the problem should be fixable

**Comment by jimgit** [comment]
div should be id

![image](https://user-images.githubusercontent.com/1921941/37471686-5cb5a0da-2838-11e8-9330-55d38ce482a1.png)

**Comment by jimgit** [comment]
If you continue to have problems, submit a JSFiddle.  Most people that do that usually find the problem on their own since it strips out lots of extra junk that clouds the problem. It takes time to make a jsfiddle that shows the problem but do you expect volunteers to do that for you?
  [Make a jsfiddle from the examples on this page -](http://bootstrap-table.wenzhixin.net.cn/examples/) once you know that works you can find the problem in your code.

**Comment by wenzhixin** [comment]
Just like @jimgit said, use classes can solve your problem: http://jsfiddle.net/ovcfv5y2/4/

**Comment by voordev** [comment]
Fixed this a few months ago indeed with the suggestions
