### ISSUE TITLE
reorder-columns extension stopped working in ver. 1.12.0

### ISSUE THREAD

**Issue by pmichna** [wenzhixin/bootstrap-table#3679]
The reorder-columns extension stopped working in version `1.12.0`.

The same code works in `1.11.1`. In `1.12.0` and `1.12.1` when you drop the column, everything goes back to initial positions.

JSFiddle: https://jsfiddle.net/7os91g7n/9/

**Comment by gautierderuette** [comment]
I have the same problem, which is also visible here : http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-columns.html

**Comment by cbielich** [comment]
Any fix on this?

**Comment by cbielich** [comment]
Solved it

Add `$('#table-javascript').dragtable('destroy').dragtable({});` in your `$table.on('all.bs.table', function (event) {`

**Comment by wenzhixin** [comment]
Fixed in the latest version: http://bootstrap-table-examples.wenzhixin.net.cn/#extensions/reorder-columns.html
