### ISSUE TITLE
queryParams removes page element!

### ISSUE THREAD

**Issue by nnmer** [wenzhixin/bootstrap-table#368]
If use custom queryParams fuction,
for example:
```
function paramFunction(params){
                params['days'] = 34;
                return params;
            }
```
then in the query **page** element is not in parameters ?!

**Comment by nnmer** [comment]
ZhiXin, can you please comment here. Possibly you can put in manual some information, how to modify query parameters, because the way how it should be (how I was trying to do that) doesn't work properly.

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/152.html

**Comment by nnmer** [comment]
Please, check yourself!

First (GET) is working properly.
But POST doesn't

**Comment by nnmer** [comment]
Looks that you change params, and do not supply *page* param anymore, and it is offset instead, so I switch my paginator to use *offset*

**Comment by nnmer** [comment]
not actual anymore
