### ISSUE TITLE
Can the multiple-sort extension use sorter functions, similar to the single-column sort?

### ISSUE THREAD

**Issue by jonoshuster** [wenzhixin/bootstrap-table#3680]
When sorting on single columns, you can specify a sorter function with the data-sorter tag.  We use this to sort date strings chronologically rather than alphabetically.

But it doesn't look like the multiple-sort extension uses the data-sorter tag, as any multiple sort using a field with my date sorter function still sorts the field alphabetically.

Is there a way to specify a sorter function with multiple sort?

If not ... that'd be a great addition.

I'm not sure I could quickly figure this out on my own, but if you can point me in the right direction, I'm willing to give it a try. Would appreciate your advice ... thanks!

**Comment by jonoshuster** [comment]
@jbarrineau06 That's awesome! I'm not an expert at contributing changes to someone else's repository, so I won't presume to advise you.  But it looks like there are pretty good guidelines on the pull request page.  If you get thoroughly stuck, and if I can help, let me know.

**Comment by twhetzel** [comment]
I'm also looking how to use a custom sort method with the Multiple Sort extension. @jbarrineau06 have you been able to submit a Pull Request and was it merged back into the project?

**Comment by UtechtDustin** [comment]
@jbarrineau06 
Do you still want to help us ?
If you cant submit an Pull Request just share your changes with us an we will implement it.

**Comment by jbarrineau06** [comment]
It's been awhile, I'll have to dig up the code and update it for the new version. I'll check on it next week.

**Comment by UtechtDustin** [comment]
thank you !

**Comment by UtechtDustin** [comment]
@jbarrineau06 any news ?

**Comment by jbarrineau06** [comment]
Sorry for the wait, I'm working on it tonight. Hopefully will have a PR tonight or tomorrow sometime.

**Comment by UtechtDustin** [comment]
@jbarrineau06 Thank you :-)
