### ISSUE TITLE
all update methods hang whole page

### ISSUE THREAD

**Issue by szczepanR** [wenzhixin/bootstrap-table#3681]
Hi,
I found problem during updating cell values in row. I checked all available methods for update:
updateRow
updateByUniqueId
updateCell
updateCellById 

I am developing SignalR frontend application. Some functions send information from server to client with high frequency. Inside these functions I put "updateByUniqueId" to update table with new information. SignalR function send new information for single row at one time. When  frequency  is really high i.e. 5 message per second in 10 minutes, the "updateByUniqueId" freezes whole page in browser for  10 minutes. The same result I got with rest functions available for updating value in the table. 
The workaround I found was:
 Table.find('[data-uniqueid="' + data.ID + '"]').find('td:eq(6)').html(data.newMessage);
above line gives me expecting results, rest of the page is responsive and  table has updated values in real time.
But I lose this value when I do any activity on the table i.e. when click sort.

**Comment by jimgit** [comment]
Wondering if you should put a separate timer loop to add all new rows received in a period.  Say the server is sending 50 rows per second into an INCOMING array  Your "table updater" could run at some reasonable frequency and update any new rows (maybe 0, 5, or even 100).  Once your update completes, the processed rows are removed (or marked complete) from the INCOMING array.

**Comment by szczepanR** [comment]
thanks for fast response. I don't have access to server code. I only  can recieve message from server.
Is there anything I can do on client side?
is there posiibility to save data in the table from below line?
Table.find('[data-uniqueid="' + data.ID + '"]').find('td:eq(6)').html(data.newMessage);

**Comment by jimgit** [comment]
Yes, decouple your incoming data from the bootstrapTable data.   An intermediate array can serve as queue of new entries.  Use a timer event to dequeue the messages and append to the bootstrap table.

**Comment by szczepanR** [comment]
thanks for hint, but I am not on that high level of developing :(

**Comment by wenzhixin** [comment]
Performance problem, fixed in #4268
