### ISSUE TITLE
reorder + resize + overflow = problem

### ISSUE THREAD

**Issue by pmichna** [wenzhixin/bootstrap-table#3687]
https://jsfiddle.net/7os91g7n/20/

Reproduction steps:
1. Extend manually columns, so the sum of their widths is larger than container size. The table becomes horizontally scrollable because of `resizeMode: 'overflow'`.
2. Scroll to the right till the end.
3. Drag the last column (`E`) to the left.

Existing behavior:
The transparent picture of the column is dragged with an offset from the dragging shadow.

Expected behavior:
The transparent picture of the column should be dragged just under the dragging cursor.

Possibly related to:
#3175

**Comment by UtechtDustin** [comment]
I cant reproduce this issue, if that issue still exists please comment :-)
