### ISSUE TITLE
The tail of the request has a parameter like “_=15xxxxxxxxxxxx”

### ISSUE THREAD

**Issue by KevinHades** [wenzhixin/bootstrap-table#3693]
http://localhost:4000/api/admin/menu/getall?level=2&parentId=5a5d9d0fa22b9d003f438145&order=asc& **_=1521526686730**

**Comment by wenzhixin** [comment]
I think you are using `data-cache="false"` option.

http://api.jquery.com/jquery.ajax/

> ache (default: true, false for dataType 'script' and 'jsonp')
Type: Boolean
If set to false, it will force requested pages not to be cached by the browser. Note: Setting cache to false will only work correctly with HEAD and GET requests. It works by appending "_={timestamp}" to the GET parameters. The parameter is not needed for other types of requests, except in IE8 when a POST is made to a URL that has already been requested by a GET.
