### ISSUE TITLE
Refresh with server-side pagination ignores pageNumber

### ISSUE THREAD

**Issue by eyalzo** [wenzhixin/bootstrap-table#3694]
When refreshing with server-side pagination, it is optional to set a new URL and/or page size and/or page number. The latter does not function at all (while the other two are fine).
Work arounds I have tried:

1. Setting the page before changing the URL is bad, because it makes another call  $('#table').bootstrapTable('selectPage', 1);

1. Adding the right page/offset parameter in the query does not help, because data is correct but the paging indicators remain in their previous position.

See doc:

> refresh | params | Refresh the remote server data, you can set {silent: true} to refresh the data silently, and set {url: newUrl, pageNumber: pageNumber, pageSize: pageSize} to change the url (optional), page number (optional) and page size (optional). To supply query params specific to this request, set {query: {foo: 'bar'}}.

**Comment by grex22** [comment]
Can confirm this bug (or the docs are incorrect)

**Comment by jinbatsu** [comment]
Is there any solution yet for this?
This make calling twice to server, and some server protect for flooding too fast.

So, dirty solution is make a delay like this:
``
		$('#tablegrid').bootstrapTable('refresh');
		setTimeout(function() {
			$('#tablegrid').bootstrapTable('selectPage', 1);
		}, 500);
``

**Comment by Falseee** [comment]
Fixed in https://github.com/wenzhixin/bootstrap-table/commit/cd96b11b41f29b03fde6c1ff13cce5c69f1534ad
#4195ä
