### ISSUE TITLE
V1.12.1兼容性，jquery最低需要什么版本？bootstrap最低需要什么版本？

### ISSUE THREAD

**Issue by tankxxl** [wenzhixin/bootstrap-table#3695]
我的jquery是1.8.3，bootstrap是2.3.1，用上最新的bootstrap-table后报错了。
请问这些依赖组件的最低版本是多少？

**Comment by wenzhixin** [comment]
主要看 bootstrap 依赖的 jquery，假如 bootstrap 能正常使用，那么 bootstrap-table 应该也可以正常用。
