### ISSUE TITLE
resizable extension - unnecessarily scrollable

### ISSUE THREAD

**Issue by pmichna** [wenzhixin/bootstrap-table#3699]
https://jsfiddle.net/7os91g7n/24/

Steps to reproduce bug:
1. Use resizable extension in `resizeMode: 'overflow'`.

Expected behavior:
- when not necesssary, table should not be horizontally scrollable

Actual behavior:
- Table is minimally scrollable, even if there are only two columns which could fit in the table container.

**Comment by UtechtDustin** [comment]
That is what the resizeMode overflow do, also the [examples](https://www.jqueryscript.net/demo/jQuery-Plugin-For-Draggable-Resizable-Table-Columns-colResizable/) of the plugin will create instantly a scrollbar.
So we cant do something there i guess.
