### ISSUE TITLE
Datatable content updation after filtering

### ISSUE THREAD

**Issue by corestore** [wenzhixin/bootstrap-table#370]
Hello Sir,

I am adding filter functionality by referring to the
extensions section - http://wenzhixin.net.cn/p/bootstrap-table/docs/extensions.html#filter

Through the code:

$('#log').prepend(d.toLocaleString() + ': ' + JSON.stringify(data) + "\n");

I get the log section updated with the current time and performed filter action but not able to identify how to update the table based on the applied filter. Request you to please guide on how the table can be updated based on the filter. Thank you for your time.

Sandeep.

**Comment by wenzhixin** [comment]
please go to issue #402 to discuss the problem, close this one.
