### ISSUE TITLE
data-search is not showing in boostrap 3 modal

### ISSUE THREAD

**Issue by jialei22** [wenzhixin/bootstrap-table#3700]
Toolbar (search input) is not showing up on top of the table in bootstrap 3 modal.
But it's showing up and working in regular MVC view page.
Could it be z-index?
Please help.   

<div id='myModal' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

 <div>
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title" id="myModalLabel">search</h4>
        </div>

        <div id="toolbar">
            <button id="btnAddFund" type="button" class="btn btn-success btn-mg">Add Fund</button>
        </div>

        <table id="addFundTable" 
               data-pagination="true"
               data-show-export="true"
               data-toolbar="#toolbar"
               data-search="true"
               data-show-refresh="true"
               data-show-toggle="true"
               data-show-columns="true"
               data-minimum-count-columns="2"
               data-show-pagination-switch="true"
               data-id-field="Decimal"
               data-page-list="[10, 25, 50, 100, ALL]"
               data-show-footer="false"
               class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" class="form-check-input" onclick="deleteCheckClick()" onchange="deleteCheckClick()" id="chkAddFund">
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].TickerSymbol)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].HexCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Decimal)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].FundName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].FundClass)
                    </th>
                    <th>Action</th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="form-check-input">
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TickerSymbol)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HexCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Decimal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FundName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FundClass)
                    </td>
                    <td>
                        <button type="button" class="btn btn-success btn-sm">Add</button>
                        @*@Html.ActionLink("Delete", "#", "", null, new { onclick = "DeleteUser(" + item.UserID + ");" })
                        <a id="idDeleteMenu" href="#">Delete</a>*@
                    </td>
                </tr>
            }
        </table>
    </div>

**Comment by jimgit** [comment]
Please submit a JSFIDDLE with your problem. [ Here is an example](http://jsfiddle.net/jimkennelly/g51oqhd4/)

**Comment by wenzhixin** [comment]
It seems that you miss the tbody element. 
Please check your code and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
