### ISSUE TITLE
column width is not working

### ISSUE THREAD

**Issue by Arthur-Z** [wenzhixin/bootstrap-table#3701]
version:1.11
 { field: 'Id', title: 'Id',width:400, sortable: false, visible: true, valign: 'middle' },
set width as below
but table column not change

**Comment by jimgit** [comment]
Please include a JSFIDDLE demonstrating the problem.

See this [example jsfiddle](http://jsfiddle.net/jimkennelly/2fbmos7p/)

![image](https://user-images.githubusercontent.com/1921941/37768412-83cff2ca-2d9b-11e8-8b15-29ccca3135c3.png)

**Comment by marlenesco** [comment]
@Arthur-Z I solved the issue using `max-width` in `cellStyle` method:

```
{
    field: 'someField',
    title: 'Column title',
    sortable: true,
    width: '100px',
    cellStyle: function (value, row) {
        return {
            css: {
                'max-width': '100px',
                'white-space': 'nowrap',
                'overflow': 'hidden',
                'text-overflow': 'ellipsis'
            }
        }
    }
}
```
I had to use ellipsis text because of a long string without blank space in that cell, you can also ignore this extra options.

I hope it works for you.

**Comment by n0n0t** [comment]
Its not working when total width exceed the window width:
http://jsfiddle.net/2fbmos7p/14/

**Comment by Falseee** [comment]
Seems to work fine, if you still need help with that pls reopen the issue and provide us an jsFiddle.
