### ISSUE TITLE
toggle icon doesn't appear

### ISSUE THREAD

**Issue by gyygyy32** [wenzhixin/bootstrap-table#3702]
this is test demo https://codepen.io/gyygyy32/pen/ZxyXWR

![image](https://user-images.githubusercontent.com/5733435/37779973-ab7723c4-2e28-11e8-98f6-1db9329468bf.png)

**Comment by gyygyy32** [comment]
i already use this cdn:"
`<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />`

code as below
`<table id="tbwipdetail"
                                    data-toggle="table"
                                    data-toolbar="#toolbar"
                                    data-search="true"
                                    data-show-refresh="true"
                                    data-show-toggle="true"
                                    data-show-columns="true"
                                    data-show-export="true"
                                    data-detail-formatter="detailFormatter"
                                    data-minimum-count-columns="2"
                                    data-show-pagination-switch="true"
                                    data-pagination="true"
                                    data-id-field="id"
                                    data-page-list="[10, 25, 50, 100, ALL]"
                                    data-show-footer="false"
                                    data-sort-name="id"
                                    class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th data-field="id" data-sortable="true">序号</th>
                                            <th data-field="lotid" data-sortable="true">批次号</th>
                                            <th data-field="length" data-sortable="true">米数</th>
                                            <th data-field="timeinterval" data-sortable="true">呆滞时间</th>
                                        </tr>
                                    </thead>


                                </table>`

**Comment by Chalema** [comment]
![image](https://user-images.githubusercontent.com/33573253/37820493-bcb7e6e4-2ebb-11e8-945f-8b8ade20fe4b.png)
官网上就是这样！！！

**Comment by timoline** [comment]
try this cdn
https://rawgit.com/wenzhixin/bootstrap-table/develop/src/bootstrap-table.js

#3661

**Comment by wenzhixin** [comment]
该问题已经在 develop分支中解决，要等下个版本：
Full example(v3): http://jsfiddle.net/wenyi/e3nk137y/25370/
Full example(v4): http://jsfiddle.net/wenyi/e3nk137y/25378/

**Comment by jitendersandhu** [comment]
@wenzhixin - Thanks for fixing the issue in the source code. Could you please update the CDN with latest minified JS (including this fix).

BTW, awesome library. 👍

Thanks,
Jitender Singh

**Comment by jitendersandhu** [comment]
@wenzhixin any update on this please?

**Comment by YassienW** [comment]
@jitendersandhu If you are looking for the minified updated file for local hosting, i minified it myself here 
[bootstrap-table.min.zip](https://github.com/wenzhixin/bootstrap-table/files/2522311/bootstrap-table.min.zip)

**Comment by YassienW** [comment]
@jitendersandhu If you are looking for the updated minified file I've minified it here
[bootstrap-table.min.zip](https://github.com/wenzhixin/bootstrap-table/files/2522314/bootstrap-table.min.zip)
