### ISSUE TITLE
Problem with filter Filter Control

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#3703]
I have a problem with filter-control.
I have several column, when I filter to the first column, they return the correct data table.
But when I filter to the first column and after to the second column, apparently they clean the first filtered and they filter only to the second column.

I'm using the bootstrap-table v.1.12.1 and filter-control 2.1.2

You can see the result here:
https://jsfiddle.net/e3nk137y/24574/

In the first column enter into the input "A" value and it filter well.
And into the second column, enter into the input "A" value and it give me a result where the data of the first column is "A" and "B".
They must return only one row.

**Comment by manukieli** [comment]
Ok, now work liek a charm.
Thank you so much.

**Comment by djhvscf** [comment]
Fix in #4090
