### ISSUE TITLE
table emptied on sort

### ISSUE THREAD

**Issue by hecko** [wenzhixin/bootstrap-table#3707]
Hie everyone, I have a noob question - I am loading the table using a separate JS request method and the data are loaded after the page is displayed and bootstrap-table loaded. I belive this is the reason to my problem which is that if I search or sort the table Im not actually sotring or searching the loaded table contant, but the original empty content of the table which was there when bootstrap-table was being loaded. 
Is there a way to tell bootstrap-table to reread the content of the table and properly search/sort? As currently as my title here suggests when I do sort or search (loaded table) it is actually emptied.

Thanks

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by pinkrrr** [comment]
Anything holding you back from initializing table post data request using corresponding bootstrapTable API's method?

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
