### ISSUE TITLE
Show only few hidden columns in bootstrap-table-toolbar

### ISSUE THREAD

**Issue by innoctive** [wenzhixin/bootstrap-table#3708]
Hi - I'm trying to keep only few columns in the bootstrap-table-toolbar however it shows me all the columns - both hidden and non hidden for search, attached is a screenshot.

Just need to keep only 3 columns that too hidden one's in my 'Advanced Search' pop up, as of now it shows all columns (as seen in screenshot below) can you please suggest how it can be done via this plugin (bootstrap-table-toolbar).

JS File - <script src="extensions/toolbar/bootstrap-table-toolbar.js"></script>
Reference - https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/toolbar

![image](https://user-images.githubusercontent.com/30370096/37911336-61a5cc7a-312d-11e8-8f42-6a2c35c89a1b.png)

Thanks,
Deepesh

**Comment by wenzhixin** [comment]
I think use `searchable` column option can solve your problem:

![image](https://user-images.githubusercontent.com/2117018/38222712-094fa7fc-3719-11e8-84f0-b36ef0fa90b3.png)
