### ISSUE TITLE
Advanced toolbar with Bootstrap 4 doesn't work

### ISSUE THREAD

**Issue by teoSalvetti** [wenzhixin/bootstrap-table#3709]
I'm using the version 1.12.1 with bootstrap 4 and thymleaf. In particular I'm trying to implement it with the Advanced toolbar.

So this is my code:

```
		<table 	data-toggle="table" 
			th:data-url="@{/fatture/list/data}" 
			data-striped="true" 
			data-pagination="true" 
			data-search="true" 
			data-sortable="true" 
			data-side-pagination="client"
			data-sort-name="dataFtt" 
			data-sort-order="asc" 
			data-id-table="listFatture" 
			data-advanced-search="true">
		    <thead>
		        <tr>
		            <th data-field="dataFtt" th:text="#{ragioneSociale}" data-sortable="true" data-formatter="dateFormatter"></th>
		            <th data-field="piva" th:text="#{piva}" data-sortable="true" ></th>
		            <th data-field="indirizzo" th:text="#{indirizzo}" data-sortable="true" ></th>
		            <th data-field="comune" th:text="#{comune}" data-sortable="true" ></th>
		        </tr>
		    </thead>
		</table>
```

but the results is different from the example:

![schermata del 2018-03-26 16-39-33](https://user-images.githubusercontent.com/8643236/37913207-a4d9a0b6-3114-11e8-8d0d-c84243450822.png)

as you can see on the left I have the "search field" while on the right and without icon, I find the button for  the advanced search.
why?

Then if I try to click it, nothing happen

**Comment by macdoor** [comment]
same problem. need an example for Bootstrap 4

**Comment by wenzhixin** [comment]
Fixed in develop, will release in next version.
