### ISSUE TITLE
Using table content in a HTML form

### ISSUE THREAD

**Issue by btran1802** [wenzhixin/bootstrap-table#371]
Hi,

I plan to send the contents of the table such as checkbox, radio button via HTML form.  Is it possible?  Can you show some sample codes?

Thanks,

**Comment by Synchunk** [comment]
Hey,

I had the same problem and managed to solve it by adding `data-id-field="id" data-select-item-name="abc"` to the `<table>` tag. That'll send a list of selected items that looks like this:

```
/page?abc=1&abc=2&abc=3
```

Bootstrap-Table is getting the values from the `id` column (you can change that by editing `data-id-field` in the code above). Obviously, you can also change the `abc` (`data-select-item-name`) above.

Obviously, you need to have a column with the name you specified in `data-id-field` for this to work, for example:

```
<th data-field="id">ID</th>
```

If you don't want to show the `id` column, you can use the following code. The `class="hidden"` is a fallback for users who disabled JavaScript.

```
<th data-field="id" data-visible="false" data-switchable="false" class="hidden">ID</th>
```

You can find a full list of variables you can add to the `<table>` tag in the [Table Properties Documentation](http://wenzhixin.net.cn/p/bootstrap-table/docs/documentation.html#properties)

I hope that your question is still relevant after 17 days, if not, hopefully it'll help someone else. It took me quite a while to figure out how everything works, so hopefully I can prevent that from happening to others. :smile:

If you need more help, just leave a comment!

**Comment by wenzhixin** [comment]
Thanks @Synchunk, your answer is very detailed.

**Comment by wenzhixin** [comment]
Added to [example list](https://github.com/wenzhixin/bootstrap-table-examples#examples-list): http://issues.wenzhixin.net.cn/bootstrap-table/371.html

**Comment by Synchunk** [comment]
:heart:

**Comment by havok2063** [comment]
Hi.  I'm having trouble with this example.  I've followed your example exactly and it isn't working.  I have 
data-id-field="id" data-select-item-name="input" inside my table
and my table is inside a form.  Inside my form I'm also passing some text input named fitsname.  However, during the submit, only the fitsname is getting passed, and my table data that I'm calling "input" (from data-select-item-name="input"), is not getting passed.  Any ideas?  Thanks.

**Comment by Synchunk** [comment]
@havok2063 Can you post the full code somewhere (you can obviously remove parts that aren't necessary to reproduce the issue)?

**Comment by havok2063** [comment]
Ok, I tried my best to convert it to a nice jsfiddle.  https://jsfiddle.net/havok2063/s4v9fbs4/
The form here keeps telling me to use a 'post' request, regardless of whether or not I switch the form method to 'post' or 'get'.  So that part isn't working.  However, in the real code, it submits the form to my action='writeFits', but only submits the input filename (?fitsname=) , but does not append the table data as (input=&input=...)

I tried to keep everything as much the same as I could.  I simplified the table, and changed the javascript so it could run in jsfiddle.

**Comment by havok2063** [comment]
Have you had a chance to look at this yet?  I still can't get it to work right.  Any help would be appreciated.  Thanks.

**Comment by Synchunk** [comment]
@havok2063 It works for me, after removing the `$(function(){ ... })` around the other functions. I try to avoid using JavaScript whereever possible, so I don't really know what that does...
When clicking on ***Write FITS***, it redirects me to
```
http://localhost:8081/writeFits?fitsname=test&btSelectAll=on&input=1&input=4
```
I would send you a link to the JSFiddle, but for some reason it decided to break completely...

**Comment by havok2063** [comment]
That's weird.  It doesn't work for me.  In the real code, I don't have the $(function(){..}) around the code either.  They just exist as standalone functions.  So it should work but it's not.  Where is the SelectAll=on coming from?  Can you somehow send me the snippets of this code that you got working?

**Comment by Synchunk** [comment]
Here's the code I used: [bootstrap-table-problem.html](https://gist.github.com/Synchunk/073bb3a614a1b0cb57d4)

Name | Version
---- | -------
Bootstrap | 3.3.1
bootstrap-table | 1.5.0
jQuery | 1.11.1
normalize.css | 3.0.2

**Note**: The code contains a few unnecessary dependencies (like jQuery UI), which is because I copied the base HTML from a different project. That shouldn't be related to the issue, though.

**Comment by havok2063** [comment]
Hmm.  Ok.  I just tried your code exactly, except linking it to my version of bootstrap, jquery, and bootstrap-table, and it doesn't work.  The url only returns fitsname=?  and no table parameters.  I'm using 
<table>
<thead>
<tr><th>Name</th><th>Version</th></tr>
</thead>
<tbody>
<tr><td>Bootstrap</td><td>3.3.2</td></tr>
<tr><td>Bootstrap-Table</td><td>1.6.0</td></tr>
<tr><td>Jquery</td><td>1.11.2</td></tr>
</tbody>
</table>

Could this be a bug introduced between bootstrap-table versions?

**Comment by Synchunk** [comment]
I upgraded bootstrap-table and jQuery, still working...

**Comment by havok2063** [comment]
Chrome Version 40.0.2214.111

**Comment by Synchunk** [comment]
Can you try using Firefox?

**Comment by havok2063** [comment]
Same problem.  Tried Firefox 23.01, then updated and tried 36.0.  Only returns writeFits?fitsname=first and nothing else.

**Comment by Synchunk** [comment]
I'm confused... are you using a web server or a file:/// URL?

**Comment by havok2063** [comment]
I just meant that I updated my Firefox browser to the latest version and tried again, and got the same results.  I'm loading your html code as a file:/// ; with the links to all the js and css pointing to my local versions.  Then running it to see what the returned link is when I click the Submit button.  

It tries to navigate to writeFits?fitsname=first  but since I don't have it plugged into my Flask web-app it doesn't recognize the writeFits method.  But it still is not passing anything other than fitsname.  Shouldn't it be something like 

writeFits?fitsname=first&input=a&input=b&input=c     etc..

**Comment by Synchunk** [comment]
I just tested it with file:/// (usually I'm using a web server), which works completely fine.
I'm out of ideas :frowning:

**Comment by havok2063** [comment]
Nooooo!  Haha..  Sigh.. I don't understand it. :frowning:  I'll try it on my laptop and see if that makes any difference.  Thanks for your help.  I really appreciate it.    

@wenzhixin Do you have any thoughts on this?

**Comment by havok2063** [comment]
I also just tried plugging in the same table from your code into my web server, and it also didn't work.  Still only requests the one fitsname parameter.

**Comment by wenzhixin** [comment]
Just said like @Synchunk, https://jsfiddle.net/s4v9fbs4/4/, we can see: 
![1](https://cloud.githubusercontent.com/assets/2117018/6456589/4aa9158a-c1a1-11e4-9cfc-cd443fd7ad1f.png)

**Comment by havok2063** [comment]
Well just showing me that it works for you doesn't really help me.   As @Synchunk and I have been discussing, we have been using the same code, which is the same as yours, and it does not work for me.   At least @Synchunk tried to help me.   I don't know what the problem is and I'm out of ideas.  What I was asking was if you had any ideas on why it might work for him and not for me?  Sorry for the confusion on my question.  

Also it looks like the table form only sends one column, the id, through the form?  Is this correct?  Presumably this is because data-id-field is used to specify which column to send?  I'm actually looking for a way to send the entire table to the server in the request so I can export it as a FITS file.  The response should just be the header to download the file via the browser.    

Ajax and Jquery don't work because it doesn't handle my file download response.  Thus my attempts at sending the data via a form.

**Comment by serlogo53** [comment]
hi wenzhixin 
i need your help.

https://jsfiddle.net/s4v9fbs4/4/

in this example (old post) used <td> </td> tag. i can use this wit jquery data table perfect. but 
in botstrap data table with jsondata datasource everything halt. please can you help me.

i am tring to do :+1: 
row selected or checked table with json data.
and when i select row with a button i want to make some function.
1. can edit row in modal page (with ajax(if i take this some value i can do everything))
2. alert(selected rows.field)
3. delete(selected row)

i think firstly i need selected row.field(...) value
later 
i will try to collect more selected row.field (with checkbox stye)

i hope i explained.

thank you.

i will wait your answer..

**Comment by wenzhixin** [comment]
Hi @serlogo53 , I think the examples: http://issues.wenzhixin.net.cn/bootstrap-table/ maybe can help you.

**Comment by serlogo53** [comment]
hi wenzhixin.
 i checked all your example and so hard for me. my wants very clear. if you make my example buttons events everything will very good. along 1 week i am working to fix but nothing. (if i not use json data and use <td></td> data source everything is ok. but it's not usefull.) in this example is it possible to make?

best regards.


        <button id="cikis_yap" class="btn btn-default btn-success"  data-toggle="modal" 
data-target="#myModal" >EDİT ROW</button>

        <button id="button1" class="btn btn-default btn-success"   >SHOW SELECTED ROW FIELD ..[].. </button>
        <button id="button1" class="btn btn-default btn-success"   >SHOW CHECKED ROWS FIELD ..[].. </button>

         <button id="button2" class="btn btn-default btn-success"   >DELETE SELECTED ROW</button>
 
         <table 
         id="table" 
           data-toggle="table"
           data-url="sample.json"
		   data-show-refresh="true"
      	   data-show-pagination-switch="true"
           data-page-size="50"
           data-page-list="[50, 100, 200]"  
           data-search="true"
           data-sort-name="tanim_adi" 
           data-sort-order="asc"
           data-click-to-select="true" 
           data-select-item-name="f_id"
 
               data-height="600"
             data-pagination="true"

                data-query-params-type=""
               data-query-params="queryParams"   >
            <thead>
            
            <tr>
            
					<th class="col-sm-1" data-field="hareket_id" data-checkbox="true" data-visible="true"></th>
 
                <th  class="col-sm-2" data-field="field1" data-sortable="true">f1</th>
                <th  class="col-sm-2" data-field="field2" data-sortable="true">f2</th>
                <th  class="col-sm-4" data-field="field3" data-sortable="true">f3</th>
                <th  class="col-sm-2" data-field="field4" data-sortable="true">f4</th>
                <th  class="col-sm-6" data-field="field5" data-sortable="true">f5</th>
            </tr>
            </thead>
        </table>

**Comment by wenzhixin** [comment]
You can try this:
* define your custom function `showModal(row);` to show the row form.
* use `getSelections` method.
* user `remove` method.
Hope to help.

**Comment by serlogo53** [comment]
i send a mail "wenzhixin2010@gmail.com". i will wait your help :-)

**Comment by serlogo53** [comment]
after getselections method i think we need to crop sentences. i think it's not possible to take just one field?

**Comment by serlogo53** [comment]
again me lord of the codes. 	
is it possible to convert this to json data source?


<? include_once("bag.php"); ?>

	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 


    <div class="container theme-showcase" role="main"  >


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        1
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">ÇIKIŞ YAPILACAK İŞLEM BİLGİSİ</h4>
      </div>
      <div class="modal-body">
        <input hidden type=text id="hareket_id">
        <table class="table" border="1" width="100%" height="45">
			<tr>
				<td class="col-sm-2" width="292" align="right">İSİM</td>
				<td class="col-sm-4"><span id="misim"></span></td>
			</tr>
			<tr>
				<td class="col-sm-1" width="292" align="right">PLAKA</td>
				<td><span id="mplaka"></td>
			</tr>
			<tr>
				<td class="col-sm-1"  width="292" align="right">GİRİŞ TARİHİ</td>
				<td><span id="mgiristarih"></td>
			</tr>
			<tr>
				<td class="col-sm-1" width="292" align="right">AÇIKLAMA</td>
				<td><span id="maciklama"></td>
			</tr>
		</table>
		<p>Yukarıdaki bilgilere ait kişi/araç için çıkış işlemi 
		yapılacaktır. Çıkış işlemini geri almak için ise &quot;ÇIKIŞ KAYIT&quot; menüsünü 
		kullanmanız gerekmektedir.
 
		  <div style="display: none" id="sonuc" class=""> 
    <strong>veri</strong> 
  </div>
 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" >İptal</button>
        <button id="kutu_cikis" type="button" class="btn btn-primary">Çıkışı Yap</button>
      </div>
    </div>
  </div>
</div>




    <div class="container theme-showcase" role="main">

      
 

 
 
 
 
 
  
 
 

 	<script type="text/javascript" language="javascript" src="js/jquery-1.11.3.min.js"></script>
	<script type="text/javascript" language="javascript" src="js/jquery.dataTables.min.js"></script>
  <link rel="stylesheet" type="text/css" href="css/jquery.dataTables.min.css">


 
  <style>
 
 

 
 
 
 

 .display{
font-size: 12px ;
font-weight: bold;
     table-layout: fixed;
    word-wrap: break-word
}


 



</style>

 

 
 
 
        <button id="cikis_yap" class="btn btn-default btn-success"  data-toggle="modal" data-target="#myModal" >ÇIKIŞ YAP</button>

        <button id="button1" class="btn btn-default btn-success"   >VERİ GÖSTER</button>

         <button id="button2" class="btn btn-default btn-success"   >BUTON1 İ TETIKLE</button>

 
  <p></p>

 
 
 
 
 
 
 
 
 <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th class="col-sm-1" width="16" style="display:none;"></th>
                <th class="col-sm-3">Giriş Tarihi</th>
                <th class="col-sm-3">Çıkış Tarihi</th>
                <th class="col-sm-8">Giriş Yapan</th>
                <th class="col-sm-3">Araç Plakası</th>
                <th class="col-sm-9">Açıklama</th>
            </tr>
        </thead>
 
        <tfoot>
            <tr>
                <th width="16" style="display:none;"> </th>
                <th>Giriş Tarihi</th>
                <th>Çıkış Tarihi</th>
                <th>Giriş Yapan</th>
                <th>Araç Plakası</th>
                <th>Açıklama</th>
            </tr>
        </tfoot>
 
        <tbody>
        
  <?
 include_once("bag.php");

$liste = mysql_query("SELECT hareket_id,hareket_giris_tik,hareket_cikis_tik,DATE_FORMAT(hareket_giris_tarih,'%d.%m.%Y %H:%i' ) as hareket_giris_tarih,DATE_FORMAT(hareket_cikis_tarih,'%d.%m.%Y %H:%i' ) as hareket_cikis_tarih,hareket_aciklama,hareket_plaka_id,plaka.tanim_adi as plaka_tanim_adi, hareket_giren_id,giren.tanim_adi as giren_tanim_adi, hareket_giris_kaydeden_id,kullanici_adi as hareket_giris_kaydeden_kullanici,hareket_cikis_kaydeden_id  from hareket left join tanimlar as giren on hareket.hareket_giren_id=giren.tanim_id left join tanimlar as plaka on hareket.hareket_plaka_id=plaka.tanim_id  left join kullanici on hareket.hareket_giris_kaydeden_id=kullanici.kullanici_id  where hareket_giris_tik=1 and hareket_cikis_tik=0");
while($db_veri = mysql_fetch_array($liste)){?>
 
       
            <tr>
                <td style="display:none;" ><?echo $db_veri['hareket_id']?></td>
                <td><?echo $db_veri['hareket_giris_tarih']?></td>
                <td><?echo $db_veri['hareket_cikis_tarih']?></td>
                <td><?echo $db_veri['giren_tanim_adi']?></td>
                <td><?echo $db_veri['plaka_tanim_adi']?></td>
                <td><?echo $db_veri['hareket_aciklama']?></td>
            </tr>
            
 <?
 }
 
?>
            
        </tbody>
    </table>
    
    
 



 <script>
 
 
 

 $(document).ready(function() {
    $('#example').DataTable( {
        "language": {
            "decimal":        "",
    "emptyTable":     "Herhangi Bir Kayıt Bulunamadı",
    "info":           "Gösterilen _START_ ile _END_ / Toplam _TOTAL_ Kayıt",
    "infoEmpty":      "Herhangi Bir Kayıt Bulunamadı.",
    "infoFiltered":   "(Filtrelenmiş _MAX_ Toplam Satır)",
    "infoPostFix":    "",
    "thousands":      ",",
    "lengthMenu":     "Gösterilecek _MENU_ Veri",
    "loadingRecords": "Yükleniyor...",
    "processing":     "İşleniyor...",
    "search":         "Ara:",
    "zeroRecords":    "Eşleşen Kayıt Bulunamadı",
    "paginate": {
        "first":      "İlk",
        "last":       "Son",
        "next":       "Sonraki",
        "previous":   "Önceki"
    },
    "aria": {
        "sortAscending":  ": A - Z ye Sırala",
        "sortDescending": ": Z - A ya Sırala"
    }      
    
  }
     }
);
} );

 
  $('#cikis_yap').prop('disabled', true);

$(document).ready(function() {
    var table = $('#example').DataTable();
 
    $('#example tbody').on( 'click', 'tr', function () {
        if ( $(this).hasClass('selected') ) {
 
             $('#cikis_yap').prop("disabled", true);
            $(this).removeClass('selected');

        }
        else {
            table.$('tr.selected').removeClass('selected');
 
                $('#cikis_yap').removeAttr('disabled');
       
 			$(this).addClass('selected');
        }
    });
 
    $('#button1').click( function () {
 table.row('.selected').remove().draw( false );
      //-> aradığımız bu hücreyi getiriyor.
              //  alert( table.cell('.selected', 0).data() )  
              } );




    
$('#cikis_yap').click( function () {
      //  table.row('.selected').remove().draw( false );
      //-> aradığımız bu hücreyi getiriyor.
$('#hareket_id').val(table.cell('.selected', 0).data() )  
  $('#misim').text(table.cell('.selected', 3).data() ) 
    $('#mplaka').text(table.cell('.selected', 4).data() ) 
  $('#mgiristarih').text(table.cell('.selected', 1).data() ) 
  $('#maciklama').text(table.cell('.selected', 5).data() ) 




 })
       
 

    

});


 



  
//modalın içindeki veriyi göndermek için kullanıyoruz.

$('#kutu_cikis').click(function(){  	//gönderene tıklama olayı
//gönderene bastıktan sonra yapılacak işlemler.
var vhareket_id=$('#hareket_id').val(); //isim idli kutudaki bilgiyi vgiren e aktardık.


var post_edilecek_veriler='hareket_id='+vhareket_id ; //post edilmeye hazir artık. yeni verileri bir değişkene atadık.
//ajax işlemi başlar.
$.ajax({
	type:'POST', // veri gönderme tipimiz.
	url:'cikis_proc.php', // gidecek adres
	data:post_edilecek_veriler, //gidecek veriler
	success:function(cevap){ // işlem başarılı ise
	$('#sonuc').html(cevap); // sonuç id li yere dönün bilgileri basıyoruz.
	}
	});
	});
	


 $('#button2').click( function () {; $( '#button1' ).trigger('click'); } ); 


</script>

**Comment by Lreus** [comment]
Answer is old but gold, thanks a lot
