### ISSUE TITLE
请问有没有适配V4.0的计划？

### ISSUE THREAD

**Issue by wayddmldbzz** [wenzhixin/bootstrap-table#3711]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by wenzhixin** [comment]
已经在做适配了，目前 table 和 export 插件已支持：
例子：http://jsfiddle.net/wenyi/e3nk137y/25378/
