### ISSUE TITLE
Localization support for data-page-list

### ISSUE THREAD

**Issue by zorgoz** [wenzhixin/bootstrap-table#3713]
Related to: [#2681](https://github.com/wenzhixin/bootstrap-table/issues/2681)

If localization is used, the `data-page-list="[10, 50, 100, All]"` is not valid, as it yields `NaN` in the list. Instead of `All` the same value has to be entered as the one returned by `formatAllRows` method of the localizer object.

**Problem:** this approach does not support changing localization on the fly! This text has to be changed when switching locale.

**Suggestion:** `All` should always (locale-agnostic) be the value in `data-page-list` array, while the text in the dropdown should be only taken from the locale. For backward compatibility add support for both `All` and its localized counterpart.

**Comment by wenzhixin** [comment]
Fixed in the develop branch.
