### ISSUE TITLE
No export icon and menu look awful in Bootstrap 4

### ISSUE THREAD

**Issue by exodia6666** [wenzhixin/bootstrap-table#3715]
I got some issue with export extensions, I'm using bootstrap 4 and i got couple of problem, the icon is missing since it using glyph and the menu is have no padding. 
![export-error](https://user-images.githubusercontent.com/10230139/38038262-c797529e-32d4-11e8-9ab4-75a2f2362bb5.JPG)

**Comment by timoline** [comment]
duplicate #3662
