### ISSUE TITLE
我的返回的集合里面嵌套子集合 我取数据时还要获取子集合内容 

### ISSUE THREAD

**Issue by xiaobin150** [wenzhixin/bootstrap-table#3716]
我的返回的集合里面嵌套子集合 我取数据时还要获取子集合内容 这种情形怎么办

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
麻烦提供下例子，不然不知道你说的是什么意思。

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
