### ISSUE TITLE
maintainSelected not working for server side pagination

### ISSUE THREAD

**Issue by mmochetti** [wenzhixin/bootstrap-table#372]
Checkbox/radiobuttons selections are not being preserved when the pagination is done on server side.
Would be great to be able to keep the state of the selections after the table is refreshed.

Use case:
1) Create table to use server side pagination and to maintain checkbox states across search and paginate:
           data-url="route/to/json" 
	   data-pagination="true"
	   data-side-pagination="server" 
           data-maintain-selected="true"
2) Check checkbox of first row
3) Search for something so that the first row is wiped out
4) Clear search so that first row appears again
5) Checkbox is shown unchecked.

For this I believe it's needed to keep an array of checked/selected "id's" and check them if they are present in the rendered rows and in this array. So the attribute "data-id-field" should be set to work properly.

**Comment by thedrewster** [comment]
I concur. It would be good for the state of the checkboxes to be saved upon page refresh. DataTables (datatables.net) achieves this using session and localstorage.

**Comment by wenzhixin** [comment]
I think we can handle this case manually, because we do not know when we need to save the state of the rows, and the `onSearch` and `onCheck` event can be help, do you think so?

**Comment by thedrewster** [comment]
Yes, you are right. I have handled this manually and it works. It's a great extension to Bootstrap. Well done and thanks.

**Comment by victorvasconcelosdeaquino** [comment]
How can I do this manually? I have the same problem...
Can you show me what you do to work?

**Comment by wenzhixin** [comment]
@victorvasconcelosdeaquino  #450

**Comment by wenzhixin** [comment]
Added example: Maintain selected on server side: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/917.html

**Comment by Junglefish** [comment]
Hi

I know this ticket is closed, but I'm having the same issue with **selectboxes**. I tried adapting the given example #917 tat is for checkboxes but can't get it to work. Does anyone have a similar solution for a simple single-select selectbox?
