### ISSUE TITLE
How to paginate if ajax response from server is not a json array

### ISSUE THREAD

**Issue by sooglejay** [wenzhixin/bootstrap-table#3721]
Description:

My server API responses not a json array as typically, so I have to handle the json manually and package a json array for bootstrap-table to use. Since I cannot do anything about the server api, how can I use the pagination feature of bootstrap-table as the data is not an array? 

Or, as titled, is there any way to get and handle the ajax response from server and then package it as a json array for bootstrap-table use?

Environment: Latest Version

**Comment by jimgit** [comment]
Please include a jsfiddle showing your problem.  You can put a subset of made up data at [myjson.com](http://myjson.com/) to simulate your server data format.  [Here is a jsfiddle  link to start with ](http://jsfiddle.net/jimkennelly/yvsauj8h/)  note the [data is coming from ](https://api.myjson.com/bins/1f717z)  You can create your own dummy data set at [myjson.com](http://myjson.com/) , then hit SAVE then  substitute the link it gives you into the JSFIDDLE.

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
