### ISSUE TITLE
Can not apply refresh on the table

### ISSUE THREAD

**Issue by ivanstefanov** [wenzhixin/bootstrap-table#3724]
My data is not refreshing after refresh, despite the fact the new data has been returned from the server. 

Here is what I have:

in the htm fille:

`<table id="projectGrid"></table>`

On document ready I am calling the grid initialize function

```
$(document).ready(function () {
...
     function fillProjectGrid() {
        $('#projectGrid').bootstrapTable({
            url: www.example.com,
            columns: [{
                field: 'Id',
                title: 'Id'
            } ... others columns... }]
        });
```
For the purpose of the example I have button, similar to provided examples where I am calling another url from which I receive the same data structure.  The following code is in document ready again:

```
            var $table = $('#projectGrid');
            $('#refresh').click(function () {
                $table.bootstrapTable('refresh', {
                    url: 'www.example.com?anotherUrl'
                });
            });
```
The new data has been retrieved correctly (according browser develop tools), the grid data seems to refresh (they are cleared and after that prefiled again) , but after the refresh the same data appears on the grid. Tried various alternatives, but the result is always the same.

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/e3nk137y/25389/

**Comment by ivanstefanov** [comment]
Thank you for the fast response :) You deserved your donation because of this :) The issue were because the data are included in additional 'rows' object (because of server side the pagination, which is not used in my case). I realized that, when wrote a function that binds the grid every time with different url and call this function wherever I need a refresh. Probably it is not possible to provide data array for the refresh function, instead of url.  

BTW can you explain about the 'silent' param that can specify for the refresh functionality. Tried to find examples, where it is used, but couldn't. 
I am talking about this:

> Refresh the remote server data, you can set **{silent: true}** to refresh the data silently, and set {url: newUrl, pageNumber: pageNumber, pageSize: pageSize} to change the url (optional), page number (optional) and page size (optional). To supply query params specific to this request, set {query: {foo: 'bar'}}.

**Comment by wenzhixin** [comment]
> Probably it is not possible to provide data array for the refresh function, instead of url.

Do you mean [the `load` method](http://issues.wenzhixin.net.cn/bootstrap-table/#methods/load.html)?

The response data format is depended on the `sidePagination` option:
> Defines the side pagination of table, can only be 'client' or 'server'. Using 'server' side requires either setting the 'url' or 'ajax' option. 
Note that the required server response format is different depending on whether the 'client' or 'server' option is specified. See the following examples:
[Without server-side pagination](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data1.json)
[With server-side pagination](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data2.json)

You can show more detail about the different from the first `url: www.example.com` and `url: 'www.example.com?anotherUrl'`.

**Comment by ivanstefanov** [comment]
Thank :)
