### ISSUE TITLE
1.12.1版本显示切换按钮错误 修复

### ISSUE THREAD

**Issue by lpyedge** [wenzhixin/bootstrap-table#3725]
在第1169行
把
sprintf('<i class="%s %s"></i>', this.options.iconsPrefix, this.options.icons.toggle),
替换为
sprintf('<i class="%s %s"></i>', this.options.iconsPrefix, (this.options.cardView ? this.options.icons.toggleOn : this.options.icons.toggleOff)),

**Comment by wenzhixin** [comment]
在 develop 中已修复，等下个版本发布。
