### ISSUE TITLE
Filter by multiple columns broken in ver. 12.0.0 #bootstrap-table-filter-control

### ISSUE THREAD

**Issue by sstyle** [wenzhixin/bootstrap-table#3729]
I have a table with 10 columns. I wish to filter by "age" and by "name" together. Now I can filter by age, then I typing a text to the filter by name, but age filter reset. Until ver.11.0.1 I could do that. But in ver.12.0.0 it was broken.

**Comment by djhvscf** [comment]
Fix in #4090
