### ISSUE TITLE
Column data in the wrong column with multiple header rows

### ISSUE THREAD

**Issue by davibr** [wenzhixin/bootstrap-table#3730]
I'm trying to create a table with 3 header rows with different colspan and rowspan. I've managed to set the headers the way that I wanted but the data in the table is getting mixed. The data from one of the columns get in the middle of others.

Here are the jsfiddle examples:
https://jsfiddle.net/davibrodrigues/xpvt214o/55958/ (columns configured via js)
https://jsfiddle.net/davibrodrigues/wbghyc68/ (columns configured via HTML)

The HTML one I couldn't set the cellStyle to work in jsfiddle

**Comment by UtechtDustin** [comment]
New Demo: https://live.bootstrap-table.com/code/UtechtDustin/110
