### ISSUE TITLE
啥时候解决一下超长Long做id,bt无法正常排序.

### ISSUE THREAD

**Issue by psgogogo** [wenzhixin/bootstrap-table#3731]
我在参考官方tree实例的时候,
后台传来17位超长Long整形json数据,数据无法展现!
数据如下
{"rows":[{"id":"1","intro":"1\t食品","name":"食品","pid":0,"shopId":1},{"id":"2","intro":"水果","name":"水果","pid":1,"shopId":1},{"id":"981710983850426370","intro":"","name":"苹果","pid":2,"shopId":1},{"id":"981710983883980802","intro":"","name":"鸭梨","pid":2,"shopId":1},{"id":"981710983888175105","intro":"","name":"香蕉","pid":2,"shopId":1},{"id":"981900076928532481","intro":"","name":"计算机","pid":1,"shopId":1},{"id":"981900077196967937","intro":"","name":"手机","pid":1,"shopId":1}]}

**Comment by cbfmai** [comment]
我也遇上这样的问题， @psgogogo  你解决了么？

**Comment by psgogogo** [comment]
没有.....


在2018年6月20日 21:32，Adam DENG<notifications@github.com> 写道：

我也遇上这样的问题， @psgogogo 你解决了么？

**Comment by cbfmai** [comment]
根据这位兄弟的留言 https://github.com/wenzhixin/bootstrap-table/issues/3498

我在后台把 `Long` 转成 `String` 传给前台， 解决了这个问题。

https://github.com/cbfmai/icecloud-manager/blob/master/src/main/java/com/mmtech/icecloud/manager/config/WebDataConvertConfig.java

不过我这是 spring-boot实现的 不知道适不适合你。

[demo](manager.imdnd.com)

用户名/密码 admin/123456

**Comment by cbfmai** [comment]
我看了一下 `bootstrap-table` 里面的源码， 里面有段代码说如果你的`id`是数字， 就会 `parseInt` 或者 `parseFloat`, 你可以在流浪器的 `console` 调试一下 就知道什么原因了

```js
if (typeof rowUniqueId === 'string') {
  id = id.toString()
} else if (typeof rowUniqueId === 'number') {
  if ((Number(rowUniqueId) === rowUniqueId) && (rowUniqueId % 1 === 0)) {
    id = parseInt(id)
  } else if ((rowUniqueId === Number(rowUniqueId)) && (rowUniqueId !== 0)) {
    id = parseFloat(id)
  }
}
```

`JavaScript` 的 [Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) 类型支持的最大正整数位 `253 - 1` , 也就是 `9007199254740991`, 如果超过这个数字就会丢失精度，

具体的原理， [这里](http://en.wikipedia.org/wiki/Double_precision_floating-point_format)

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
按照 @ cbfmai 的解决方案，可以在 `responseHandler`中处理。

**Comment by psgogogo** [comment]
辛苦,辛苦~


| |
zhang xisheng
|
|
psgogogo@163.com
|
签名由网易邮箱大师定制
在2019年3月12日 00:58，文翼<notifications@github.com> 写道：

Closed #3731.
