### ISSUE TITLE
bootstrap-table插件（v1.12.1）this.options.icons.toggle未赋值，导致showToggle: true的按钮很小

### ISSUE THREAD

**Issue by hllld** [wenzhixin/bootstrap-table#3734]
********************** 问题描述：**********************
        showToggle: true对应的toggle按钮很小。

********************** 原因：**********************
         bootstrap-table.js中，第1169行：
【sprintf('<i class="%s %s"></i>', this.options.iconsPrefix, this.options.icons.toggle),】的this.options.icons.toggle没有初始化赋值，导致button标签体内没有生成图标。

********************** 版本：**********************
    此版本号：bootstrap-table插件（v1.12.1）
    此版本链接：https://github.com/wenzhixin/bootstrap-table/tree/master。

********************** 目前处理方法：**********************
    方法一：在第25行初始化toggle并赋值。
    方法二：把第1169行：【sprintf('<i class="%s %s"></i>', this.options.iconsPrefix, this.options.icons.toggle),】中的【this.options.icons.toggle】置为【this.options.icons.toggleOff】。

   感谢！

**Comment by zbeboy** [comment]
使用v1.12.1 时发现，toggle不显示，后发现 sprintf('<i class="%s %s"></i>', this.options.iconsPrefix, this.options.icons.toggle) 1169行有问题，toggle无值,建议设置。

**Comment by wenzhixin** [comment]
Fixed in v1.12.2
