### ISSUE TITLE
Export table that includes a link?

### ISSUE THREAD

**Issue by ziedbf** [wenzhixin/bootstrap-table#3736]
Hi, 

I am trying to export table that includes a column for location with link for google map location, but what i get is the only text value for the link.

| Restaurant        | Rating           | Locations  |
| ------------- |:-------------:| -----:|
| xxxx    | 2  | [Google Map locations](https://www.google.com.sa/maps/place/Bootstrap+Brewing/@40.1615217,-105.1084042,17z/data=!3m1!4b1!4m5!3m4!1s0x876bf99ef4a8c213:0x846d9444ece77905!8m2!3d40.1615176!4d-105.1062102) |
| xxxx     | 3     |   [Google Map locations](https://www.google.com.sa/maps/place/Bootstrap+Brewing/@40.1615217,-105.1084042,17z/data=!3m1!4b1!4m5!3m4!1s0x876bf99ef4a8c213:0x846d9444ece77905!8m2!3d40.1615176!4d-105.1062102) |
| xxxx | 5      |  [Google Map locations](https://www.google.com.sa/maps/place/Bootstrap+Brewing/@40.1615217,-105.1084042,17z/data=!3m1!4b1!4m5!3m4!1s0x876bf99ef4a8c213:0x846d9444ece77905!8m2!3d40.1615176!4d-105.1062102)  |

 do i need to pass a specific options to the table or any way  to format data on the click event of export?

**Comment by twhetzel** [comment]
@ziedbf did you find a way to export the link? I'm also trying to sort out how to do this.

**Comment by wenzhixin** [comment]
Hello @hhurz, can we support this feature?

**Comment by ziedbf** [comment]
@twhetzel  sorry this was few months ago however i tried several method and i ended up by generating the export files on the backend.

**Comment by wenzhixin** [comment]
I think https://github.com/hhurz/tableExport.jquery.plugin does not support this feature, please use on the backend instead.

**Comment by Blaskyy** [comment]
@ziedbf 
try this...
```
exportTypes: ['excel'],
exportOptions: {
    htmlContent: true,
    onCellHtmlData: function(cell, row, col, data) { 
      if (col==2) {
        return '<a target="_blank" href=" + data + '">Google Map locations</a>'
      } else {
        return data;
    }
  },
```

**Comment by ziedbf** [comment]
Thanks @Blaskyy, this is was old and the code base was shipped, i think @hhurz tested already in https://github.com/hhurz/tableExport.jquery.plugin/issues/263 and seems to be working.

**Comment by hhurz** [comment]
FYI: New release v1.10.11 covers this issue. New options are available to control the export of `<a>` tags
