### ISSUE TITLE
hideColumn remove all my content rows

### ISSUE THREAD

**Issue by Corouna** [wenzhixin/bootstrap-table#3738]
No code to show here, because it came from official project of my company.

Anyway i've a table, where the header and rows are all declared and set using javascript instead of hardcoding it directly to the HTML. First i append the table header to the HTML, followed by appending the rows to the table, before i init it with bootstrap-table.

Problem here is that, when i tried to use the hideColumn on the table, it only hides the header column properly, but all the content rows went gone, totally removed from the DOM. When i use showColumn, the hid column is shown again, but the content rows are still missing. 

Is there anything that i can do for this?

**Comment by jimgit** [comment]
Modify one of the example JSFiddles to show your problem. [ Here are a bunch of examples to choose from.](http://bootstrap-table.wenzhixin.net.cn/examples/)

**Comment by Falseee** [comment]
I close the issue because we got no response/example, if you still need help with that pls reopen the issue.
