### ISSUE TITLE
Question: what is the minimum bundle size ? 

### ISSUE THREAD

**Issue by jeandat** [wenzhixin/bootstrap-table#3740]
I just want to ask: if I want to create a simple table, what is the minimum to add to my page ?

bootstrap-table.min.js and bootstrap-table.min.css?

Which means 59K + 6K = 65K.

Is there a way to reduce that? Maybe a smaller bundle?

**Comment by wenzhixin** [comment]
Sorry, currently does not support a small bundle.

**Comment by wenzhixin** [comment]
Maybe can use the history version: https://github.com/wenzhixin/bootstrap-table/tree/1.2.0/dist.
