### ISSUE TITLE
A little problem when I use treegrid extension

### ISSUE THREAD

**Issue by hongxf1990** [wenzhixin/bootstrap-table#3741]
I can create a table with treegrid successlly. But when I leave this page, I return to this page and find a "true" in the first column. Everytime I leave and  return again, more "true" appears. How can I fix this?

![image](https://user-images.githubusercontent.com/12297110/38684775-02cadb18-3ea3-11e8-904c-586f0abc479f.png)

**Comment by Falseee** [comment]
Is this still an issue ?
Can you provide us an example/jsfiddle ?

**Comment by UtechtDustin** [comment]
I close this issue because we got no example within 7 days, if you still need help please provide us an example and reopen the issue.
