### ISSUE TITLE
version

### ISSUE THREAD

**Issue by neil4dong** [wenzhixin/bootstrap-table#3743]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

**bootstrap 3.0.0** does contain “$.fn.dropdown.Constructor.VERSION ” , so the version detect  will fail.

bootstrap-table

![image](https://user-images.githubusercontent.com/16929939/38716087-60e7db60-3f11-11e8-90b6-50ab188395c4.png)

**Comment by li-guojiang** [comment]
我是删了这个才能用~~~

**Comment by Edison-Tian** [comment]
Bootstrap-3.2.0之后才开始支持这个属性，难道是舍弃了3.2.0之前的版本么？

**Comment by wenzhixin** [comment]
Fixed this problem in the latest version
