### ISSUE TITLE
resetting the Form in Modal is not resetting the Bootstrap validation event, valid sign.

### ISSUE THREAD

**Issue by mrighosh** [wenzhixin/bootstrap-table#3745]
Following Code resetting the Form in Modal, but not resetting the Bootstrap validation event, valid sign.

$('#login-modal').on('hidden.bs.modal', function () {
        $('#login_form').bootstrapValidator('resetForm', true);
        
        $('#login_form').bootstrapValidator('updateStatus', 'loginemail', 'NOT_VALIDATED')
       .bootstrapValidator('validateField', 'loginemail');
    });

**Comment by Falseee** [comment]
I guess you wrote the issue on the wrong repository, if i missunderstood something pls reopen the issue.
