### ISSUE TITLE
Resizing window with table does not adjust columns

### ISSUE THREAD

**Issue by radiantone** [wenzhixin/bootstrap-table#3746]
When resizing the parent container of a table the table will stretch width to fit (but strangely not the height), but the column do not adjust. This causes a mis alignment of rows and columns. This problem was reported before but I still see it in 1.12.1 under latest chrome. 

Attempts to add "resetWidth" or "resetView" to window resize event do not seem to do anything.

**Comment by zerox1212** [comment]
I have noticed the same issue. My use case is that I have a side navbar that can be hidden. I have also tried `resetView`, but I might not be triggering it at the right time due to my navbar animation.

**Comment by Falseee** [comment]
Since last year a lot resizing bugs was fixed, if this issue still exists pls reopen.
