### ISSUE TITLE
Bootstrap table height not responsive to window resizing

### ISSUE THREAD

**Issue by radiantone** [wenzhixin/bootstrap-table#3747]
When a parent container is fluid, bootstrap table does not adjust its height as that parent height changes. This prevents it from responding to window resize events in the vertical direction. 

Bootstrap table should offer a setting that allows it to internally manage its height by filling its parent container even when it changes.

https://jsfiddle.net/h6zLc5pp/10/

**Comment by UtechtDustin** [comment]
Could you describe us an scenario where the parent container will change his height ?
Currently i don't know a good reason to implement that.

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7days, if you still need help please reopen the issue.

**Comment by jcpy** [comment]
I use this code to refresh the page when resizing window

`$(document).ready(function () {
	$(window).bind('resize', function(e)
	{
	  if (window.RT) clearTimeout(window.RT);
	  window.RT = setTimeout(function()
	  {
		this.location.reload(false); /* false to get page from cache */
	  }, 100);
	});
});`

My table has automatic height according to the size of browser:

`$('#table').bootstrapTable({
		height: $(window).height()-90,
		pageSize: Math.floor(($(window).height()-90)/55),
		...`

**Comment by javicaballero** [comment]
I use this code to refresh the page when resizing window
`$(document).ready(function () {`
	`$(window).bind('resize', function(e)`
	`{`
	`  if (window.RT) clearTimeout(window.RT);`
`	  window.RT = setTimeout(function()`
	`  {`
`		this.location.reload(false); /* false to get page from cache */`
`	  }, 100);`
	`});`
`});`


My table has automatic height according to the size of browser:

`$('#table').bootstrapTable({`
`height: $(window).height()-90, `
`     pageSize: Math.floor(($(window).height()-90)/55),`
`...`
