### ISSUE TITLE
Search all columns

### ISSUE THREAD

**Issue by RazaGR** [wenzhixin/bootstrap-table#3749]
I am using filter control extension to search in all fields data which is returned by server ( http://issues.wenzhixin.net.cn/bootstrap-table/extensions/filter-control.html)

I wanted to search by pressing enter so I used event  `data-search-on-enter-key="true"`, so I am now able to search a column and auto search is disabled.

**1)** 
How can I search in all columns fields at same time when press enter in one column input? so if I enter in one column it should also search other columns which are not empty.

**2)**
sometimes when I hit enter my query is not being sent to server so I have to refresh the page to apply the search, but from console I can see `search.bs.table` event is being fired.

**3)**
when I enter search text in an input , I receive the result but input field goes empty, how to keep the search string in column field?

here my table config:
```
      <table id="MemberTable"  data-search="true" data-show-refresh="true" data-show-columns="true" data-filter-control="true" data-filter-show-clear="true"
         data-detail-formatter="detailFormatter" data-minimum-count-columns="2"
         data-pagination="true" data-id-field="id" data-page-list="[10, 25, 50, 100]" data-show-footer="false" data-search-on-enter-key="true" data-click-to-select="true" 
              data-resizable="true" data-row-style="rowStyle" 
         data-side-pagination="server" data-url="/get_members" data-response-handler="responseHandler" data-cookie="true"  data-cookie-id-table="MemberTable">
```

**Comment by zerox1212** [comment]
If you want to search all columns I think you just need to add this to your table config:
`data-search="true"`

The filter control is only for specific columns.

**Comment by djhvscf** [comment]
This is added to the latest release [1.13.2](https://github.com/wenzhixin/bootstrap-table/releases/tag/1.13.2)
