### ISSUE TITLE
Table data-url from webservice request

### ISSUE THREAD

**Issue by chokeholder** [wenzhixin/bootstrap-table#375]
I have my table who's data-url points to my service handler which fetches data from my Restfull service like this

    <table data-toggle="table" data-url="<? echo $letServiceHandler-    >getEmployees($_SESSION['api_key'],2); ?>" data-cache="false" data-height="299">
    <thead>
        <tr>
            <th data-field="id">Item ID</th>
            <th data-field="name">Item Name</th>
        </tr>
    </thead>
    </table>

getEmployee calls my rest webservice which will return a json array which looks like this:

[
 {"id":"33","name":"5yhjtyjyas 444","active":"0","user_id":"1","no_of_reports":"0"},
 {"id":"29","name":"AAA","active":"1","user_id":"1","no_of_reports":"0"},
 {"id":"20","name":"aasdasd","active":"1","user_id":"1","no_of_reports":"0"}
]

getEmployees looks like this

    // Gets employees
    public function getEmployees($api_key,$active)
    {
        $headers = array('Content-type: application/json','Authorization: '.$api_key,);

    if($active==0)
    {
        $curl = curl_init(GET_ALL_INACTIVE_EMPLOYEES);    
    }
    else if($active==1)
    {
        $curl = curl_init(GET_ALL_ACTIVE_EMPLOYEES);    
    }
    else
    {
        $curl = curl_init(GET_ALL_EMPLOYEES);    
    }

    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_HTTPGET, true);
    curl_setopt($curl, CURLOPT_USERPWD, $api_key);
    $curl_response = curl_exec($curl);

    if ($curl_response === false) 
    {
        $info = curl_getinfo($curl);
        curl_close($curl);
        die('error occured during curl exec. Additioanl info: ' . var_export($info));
    }

    curl_close($curl);
    $decoded = json_decode($curl_response,true);       

    return json_encode($decoded['employees']);
    }

Please note that Im decoding the response and then encoding it again selecting only the employees nested array.

I tried "echoing" json_encode($decoded['employees']) out and create a file of the data and put that into a file called data.json and insert that into my data-url. That worked perfectly..

a bit confused why it wont let me insert the requested data directly from my request, but putting the data into a file and using that will work ? :)

**Comment by docho** [comment]
I don't know, what the specific problem is with your service, but I use a PHP file as url which returns an array encoded as json using json_encode(). This works fine for me.
Maybe your service returns an empty first line or some invisible sign (like BOM in utf-8) which leads to your problem?

**Comment by wenzhixin** [comment]
Hi @chokeholder, `data-url` just support an url string, not the data. I think you can add a php file for example `employees.php` as url file:
```php
<?php
// Gets employees
public function getEmployees($api_key,$active)
{
    $headers = array('Content-type: application/json','Authorization: '.$api_key,);

    if($active==0)
    {
        $curl = curl_init(GET_ALL_INACTIVE_EMPLOYEES);    
    }
    else if($active==1)
    {
        $curl = curl_init(GET_ALL_ACTIVE_EMPLOYEES);    
    }
    else
    {
        $curl = curl_init(GET_ALL_EMPLOYEES);    
    }

    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_HTTPGET, true);
    curl_setopt($curl, CURLOPT_USERPWD, $api_key);
    $curl_response = curl_exec($curl);

    if ($curl_response === false) 
    {
        $info = curl_getinfo($curl);
        curl_close($curl);
        die('error occured during curl exec. Additioanl info: ' . var_export($info));
    }

    curl_close($curl);
    $decoded = json_decode($curl_response,true);       

    return json_encode($decoded['employees']);
}

echo getEmployees($_SESSION['api_key'], 2);
```

and then set `data-url="employees.php"`.


Or, maybe you can try it by javascript(not recommended):
```
var data = $.parseJSON('<?php echo getEmployees($_SESSION['api_key'], 2); ?>');
$('#table').bootstrapTable({
    data: data
});
```

**Comment by chokeholder** [comment]
@wenzhixin : Thanks .. as mentioned earlier, i moved my getEmployees function from my handler to a seperate php file called getEmployees and put that into the url, which works just fine. 

Thanks for the reply and this great bootstrap table

**Comment by wenzhixin** [comment]
You are welcome:)
