### ISSUE TITLE
bootstrap-table use bootstrap4 no extensions Export  buttons icons !

### ISSUE THREAD

**Issue by flashliao** [wenzhixin/bootstrap-table#3752]

**Comment by Dscholz911** [comment]
Bump. Also dropdown text is blue and underlines when you hover it

**Comment by Dscholz911** [comment]
Hey I found a way to fix this.
1. Install font awesome on your project. I used npm and I believe it was version 4 not 5
2. Navigate to the bootstrap-table-export.js file
Find line 32

Make this edit

$.extend($.fn.bootstrapTable.defaults.icons, {
        export: 'fa fa-share'
    });

This changes the default icon from the glyphicon to a font awesome. I'm still working on the second part with the drop down text
