### ISSUE TITLE
如何设置总页数?

### ISSUE THREAD

**Issue by sunjiaqing** [wenzhixin/bootstrap-table#3756]
如何设置总页数?
       responseHandler:function (result) {
            var temp={
                data : result.data,
                total : result.params.total //总页数,前面的key必须为"total
            }
                return temp;
         }

[demo](http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html)
给出的demo中返回的数据结构
{
  "total": 800,
  "rows": [... ]
}
当我设置成如上时,我的数据就无法显示了
我查了别人的方法 ,可是对我无效

**Comment by wenzhixin** [comment]
responseHandler:function (result) {
var temp={
rows : result.data,
total : result.params.total //总页数,前面的key必须为"total
}
return temp;
}

**Comment by sumulige** [comment]
啥意思
我怎么没懂这个patams是个什么 
厚度那不是直接是total是key result。total不是吗 写死都不行
