### ISSUE TITLE
Smart search - spaces disappearing

### ISSUE THREAD

**Issue by valentin-vincendon** [wenzhixin/bootstrap-table#3757]
When typing text into the smart search, end spaces disappear after a fraction of a second.

Examples:
"  x" -> "  x"
" x " -> " x"
"xx x x   " -> "xx x x"

**Comment by jimgit** [comment]
Try using the data-trim-on-search="false" 

[See this JSFIDDLE example.](http://jsfiddle.net/jimkennelly/ntqnbw2h/)


![image](https://user-images.githubusercontent.com/1921941/39125640-41689f20-46c5-11e8-8ead-7063db5a2515.png)

**Comment by valentin-vincendon** [comment]
Did the trick, obviously!
Thanks a lot @jimgit ! 🥁
