### ISSUE TITLE
Documentation Improvement: ID and Unique ID Fields

### ISSUE THREAD

**Issue by zerox1212** [wenzhixin/bootstrap-table#3758]
The documentation should be improved to clarify the usage of:

Name | Attribute | Type | Default | Description
-- | -- | -- | -- | --
idField | data-id-field | String | undefined | Indicate which field is an identity field.
uniqueId | data-unique-id | String | undefined | Indicate an unique identifier for each row.

I was using `idField` thinking it was unique, but much of the code requires the use of `uniqueId`. For example `getRowByUniqueId`. Now it seems obvious, but this makes me wonder when you would use the regular 'idField'?

What is regular 'idField' for? Is it possible to clarify that `uniqueId` is required for the corresponding methods?

**Comment by wenzhixin** [comment]
Merged.
