### ISSUE TITLE
UpdateCellById Exception on Filtered Table

### ISSUE THREAD

**Issue by zerox1212** [wenzhixin/bootstrap-table#3759]
If `UpdateCellById` is called on a table that is currently filtered an index exception can be raised. This is because the update is being performed on `that.data` instead of `that.data.options`.

Version is 1.11.1, but it's still in 1.12 (https://github.com/wenzhixin/bootstrap-table/blob/develop/dist/bootstrap-table.js#L2828)
Filter control is version 2.1.2

Steps:
Take a table with more than one row that is using `uniqueId`.
Apply a filter to show a row higher than 0.
Call `UpdateCellById` on the displayed row (for example from cell click event)
Exception occurs because row lookup is performed on entire data array, but is applied to displayed array.

no fiddle yet

Screenshot of debugger during error. Note line 2824 (rowId variable) and 2829.
![image](https://user-images.githubusercontent.com/13090472/39155631-637a0ae2-4718-11e8-8703-3543fd78208f.png)

I don't know if it's better to update `that.options.data` or if the row look up needs to be performed on `that.data`.  I'm assuming `that.options.data` always contains the entire data set, and that `that.data` is only what is currently displayed. In that case it makes sense that the update function has access to the entire data set, but if option data vs displayed data doesn't match (i.e. filtered) this is going to have issues.

My fix is to do the row look up on `that.data` because I will never update a cell that isn't displayed.
```js
rowId = $.inArray(that.getRowByUniqueId(params.id), that.data); // remove that.options.data
```

**Comment by lafual** [comment]
I get the same issue when using the global search `<table data-search="true">` and/or using the filter extension `<table data-filter-control="true">..<th data-filter-control="input"/>`

I am using v 1.14.2
