### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by tschaka1904** [wenzhixin/bootstrap-table#376]
Hi
I'm trying to use bootstrap in a node.js project using browserify. I do require jQuery and the bootstrap libary:

var jQuery = require('jquery');
require('bootstrap')

But after creating the bundled-file, bootstrap has a problem to find jQuery. 

ReferenceError: jQuery is not defined 
ReferenceError: require is not defined

When I don't require bootstrap, everything works fine (jQuery works perfectly), but only without bootstrap. Does anyone have a similar experience? 

Cheers and thanks

**Comment by wenzhixin** [comment]
Hi @tschaka1904, you can look this question: http://stackoverflow.com/questions/16259098/cant-load-bootstrap-with-requirejs, maybe it can help.
