### ISSUE TITLE
表格能否增加可拖动列宽功能

### ISSUE THREAD

**Issue by 1013785085** [wenzhixin/bootstrap-table#3761]
表格能否增加可拖动列宽功能，并且可以设置行数据不自动换行，过多的数据用···省略，然后拖动表格查看

**Comment by chaikenao** [comment]
css控制表格数据不换行就行，我记得有个插件是可拖拽改变列宽的，但是有bug需要自己填

**Comment by mengxiaoxu** [comment]
引入`bootstrap-table-resizable.js`插件就可以了，插件依赖于`colResizable v1.6`。

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/extensions/
