### ISSUE TITLE
toggleColumn Triggers a Rebuild of the Table

### ISSUE THREAD

**Issue by spyke01** [wenzhixin/bootstrap-table#3762]
Toggling column visibility creates a chain effect of rebuilding the entire table and in turn retriggering any formatters.

We have a large report that we are converting from DataTable to bootstrap-table where the user has toggles which will hide or show columns on the report. A typical report will have 150+ columns of which roughly 6 are visible by default. During page load these are all in the data and column options passed to datatable/bootstrap-table and the toggles are then processed for the show/hide effect. 

With Datatable we use the footerCallback option to generate a sum/avg footer of the visible data, the counterpart in bootstrap-table would be footerFormatter. The difference is that for bootstrap-table the entire table is detsroyed and rebuilt to perform the toggleColumn method and in turn the footerFormatter is recalled.

For a single row with 150+ datapoints you are looking at over 15000+ runs of the footerFormatter calls and other items.

I've create a JSFiddle of a small version of this issue.

[jsfiddle](https://jsfiddle.net/ekcq5m7d/1/)

Our work around right now will be to change out toggles from triggerring the toggleColumn method on the click event and instead add an Apply button which recreates the data/column for the table and rebuilds the bootstrap-table instance.

**Comment by syedhassan** [comment]
This has slowed down our table as well that has more than 200+ rows!

**Comment by dskilken** [comment]
I have noticed that if you are using the Fixed Column extension, and you hide and show columns, then the Fixed column is replicated again and again. (Cloned in the DOM) This really slows down the function and the initial display of the table.

**Comment by wenzhixin** [comment]
Fixed in PR: #4268
