### ISSUE TITLE
Question about bootstrap-table-resizable

### ISSUE THREAD

**Issue by StephaneKazmierczak** [wenzhixin/bootstrap-table#3764]
Hi, I have multiple tables on my page and it looks like the resizable feature doesn't activate correctly after the first table. I am not sure if it is the normal behavior but it seems to activate on other tables only after clicking on the "sorting columns" feature.

i am using bootstrap 3.3.7
1.12.1/bootstrap-table.min.js
bootstrap-table-resizable.js
colResizable-1.5.min.js
chrome Version 66.0.3359.117

**Comment by StephaneKazmierczak** [comment]
I think it is related to the bootstrap class hidden, by default my first table is visible and I toggle off the class for the other clicking on link. it seems to work if I use the class invisible instead but then the table area doesn't collapse.

**Comment by jimgit** [comment]
Please submit a jsfiddle that shows your problem.

**Comment by StephaneKazmierczak** [comment]
Yes, of course, I am not very good with jsfiddle, hope the link works: http://jsfiddle.net/ssLfkqye/2/

**Comment by UtechtDustin** [comment]
I close this issue because its already one year old, also it seems that the bug is fixed in the latest version.
Demo: https://live.bootstrap-table.com/code/UtechtDustin/50

If you still need help with that issue please reopen the issue.
