### ISSUE TITLE
action formatter not show in table

### ISSUE THREAD

**Issue by shahabes** [wenzhixin/bootstrap-table#3767]
hello, thanks for the Fantastic Table
i have an issue
 operators don't show on my table
![2018-04-28_1-00-10](https://user-images.githubusercontent.com/8515862/39383744-a5726bd2-4a7f-11e8-82d0-6ee9236c872b.png)
what should I do?

![2018-04-28_1-03-18](https://user-images.githubusercontent.com/8515862/39383841-04d9a77a-4a80-11e8-98bb-d72c63caaf31.png)
and this is my htm
![2018-04-28_1-05-08](https://user-images.githubusercontent.com/8515862/39383913-40040750-4a80-11e8-9cf4-550749ecf533.png)
thanks a lot

**Comment by shahabes** [comment]
thanks for your answer
i want item operator in my last column just like the below jsfiddle
http://jsfiddle.net/wenyi/e3nk137y/39/

and there is one error for the css and it ignored
thanks a lot

**Comment by wenzhixin** [comment]
Update to the latest version.
Example: https://examples.bootstrap-table.com/
Working fiddle: http://jsfiddle.net/wenyi/e3nk137y/44351/
