### ISSUE TITLE
Using "onClickCell" with jQuery "mouseout"

### ISSUE THREAD

**Issue by maththebuilder** [wenzhixin/bootstrap-table#3769]
I was recently having some issues trying to handle "mousedown" and "mouseout" events on a bootstrap table and managed to find a work around that might be useful for others and also bring up the potential to implement similar events in bootstrap-table.

My objective was to be able to "mousedown" on a truncated table element to display the full contents while the mouse is still hovering inside the cell frame. My code prior to implementing a table using this bootstrap table library looked like this:
 
jQuery:
`'$("tabletbody td a.badge-secondary").on("mousedown", function (e) {
    var cell = $(this).parent();
    if (!cell.hasClass("active")) {
          cell.addClass("active");
          cell.css({'top': (e.pageY-25)+"px", 'left': (e.pageX-125)+"px"});
    }
});
$("table tbody td").on("mouseleave", function () {
    $(this).removeClass("active");
});` 

CSS:
`td.active {
  user-select: none; white-space: normal; overflow: visible; position: absolute; background-color: var(--light);
  min-width: 250px; min-height: 50px; border: 3px solid var(--secondary);
}`

Once I implemented this library, however, I noticed the mouse events were not working the same as they had been before. So I found the onClickCell event in the bootstrap table documentation and rewrote the triggering event using onClickCell which got me half of the way there but I realized there was no equivalent in this library for "mouseleave" and my mouseleave event as previously written would not work once I made any on the fly modifications to my table like hiding columns or searching or switch paginated tabs.

My code now looked like this:
jQuery:

`$('#table').on('click', 'tbody > tr > td', function (e){
    var table = $table.data('bootstrap.table'),
        $element = $(this),
        $tr = $element.parent(),
        row = table.data[$tr.data('index')],
        cellIndex = $element[0].cellIndex,
        $headerCell = table.$header.find('th:eq(' + cellIndex + ')'),
        field = $headerCell.data('field'),
        value = row[field];

    table.$el.trigger($.Event('click-cell.bs.table'), [value, row, $element]);
});`

`$('#table').on('click-cell.bs.table', function(e, value, row, $element){
    if (!$element.hasClass("active")) {
        $element.addClass("active");
        $element.css({'top': (e.pageY-150)+"px", 'left': (e.pageX-300)+"px"});
    }
});
`

`$('table tbody td').on("mouseout", function(){
    $(this).removeClass("active");
});`

But a solution was found and maybe one of the authors can enlighten me as to why this works. When I moved my last little function which destroys the newly appended class inside of the function above it my issues with functionality breaking after dynamic page events went away and my "mouseout" worked great.

`$('#table').on('click-cell.bs.table', function(e, value, row, $element){
    if (!$element.hasClass("active")) {
        $element.addClass("active");
        $element.css({'top': (e.pageY-150)+"px", 'left': (e.pageX-300)+"px"});
    }
    $('table tbody td').on("mouseout", function(){
        $(this).removeClass("active");
    });
});`

Thought this might be useful for anyone else trying to do something similar and maybe a worthwhile addition to consider adding events like mouseover and mouseout to this library.

This library has been very useful, thanks!

**Comment by UtechtDustin** [comment]
I close this issue because it's already 1 year old, if you still need help please provide us an jsfiddle (instead of code snippets).
