### ISSUE TITLE
Loading doesnt hide duplicated headers

### ISSUE THREAD

**Issue by b62303411** [wenzhixin/bootstrap-table#3771]
The following code result in  a loading text that never goes and duplicated headers.

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.js"></script>
	<script th:inline="javascript">
			$(document).ready(function() {
				$("#test").bootstrapTable();
			});
		</script>
<table id="test">
	<thead>
		<tr><th>Name</th><th>Value</th><th>Options</th></tr>
        </thead>
	<tbody>
		<tr ><td>1</td><td>2</td><td>3</td></tr>
	</tbody>
</table>
```

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Tested on latest from chrome,  there is not the bug on firefox however it seems not to work at all.
With chrome the table is well formated with its value except that there is duplication of headers and the loading field that never goes away.

**Comment by wenzhixin** [comment]
Fixed in the latest version.
