### ISSUE TITLE
cookie.js cookie won't refresh when straightly jump to first page or last page？

### ISSUE THREAD

**Issue by w4lker** [wenzhixin/bootstrap-table#3772]
i'm using table-cookie.js to save table state . it worked when i click page numbers to jump to a certain page.after refreshing the page,the page will be restored.But when i click pagination to straightly jump to first page,it didn't work.i have checked the cookie,it didn't refresh.

**Comment by wenzhixin** [comment]
Fixed in the latest version: https://examples.bootstrap-table.com/#extensions/cookie.html
