### ISSUE TITLE
Column formatter  field parameter

### ISSUE THREAD

**Issue by elixom** [wenzhixin/bootstrap-table#3774]
In the documentation for column options the formatter function lists 4 parameters. The fourth is "field" in the code version 1.12.1 only the first 3 are actually passed. The documentation also says it has 3 parameters even though the syntax lists 4.

For reference the "field" can be determined in the function by `this.field` but either the documentation or the code need to be updated.

Issue exists in all browsers on all environment.

**Comment by wenzhixin** [comment]
Fixed
