### ISSUE TITLE
Retrieve response body even the response code of data loading call is not HTTP 200?

### ISSUE THREAD

**Issue by Wuaner** [wenzhixin/bootstrap-table#3775]
I put some custom error message on response body and return it as HTTP 400  if the http request was invalid.
But the **data-response-handler** function only invoked when the HTTP response code is 200, cause I cant handle the returned HTTP 400 within responseHandler function.

I noticed **load-error.bs.table** event will triggered if I return a HTTP 400, but I cant use it also because there are no way to retrieve the custom error message that I put into the response body in the event handler. 

Is this a bug, or I do it wrong? thanks.

**Comment by Wuaner** [comment]
Any response?

**Comment by jimgit** [comment]
Can you duplicate the problem in a jsfiddle?

**Comment by UtechtDustin** [comment]
I close this issue because its older then one year and we got no response from you.
if you still need help please provide us an example(jsfiddle).
