### ISSUE TITLE
Search : minimum input length

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#3776]
Is there a way to specify a minimum input length before starting a search (request data through AJAX)?

**Comment by djhvscf** [comment]
No, at this moment you can set the time before starting a search

**Comment by sdespont** [comment]
OK, thank you for your answer

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/table-options/#queryparams
> Return `false` to stop request.

`queryParams` option can improve this feature:
```js
queryParams: function (params) {
  if (params.search.lengh <= 5) {
    return false
  }
  return params
}
```
