### ISSUE TITLE
Load and RefreshColumnTitle Events

### ISSUE THREAD

**Issue by ghost** [wenzhixin/bootstrap-table#3778]
Hi! I'm trying to use both events to change the information to show. Change de columns title is working fine, but if I add the load event, the titles of columns are restored to default. I tried to change the order of execution, but only if Load event isn't fired the columns titles change. Can anyone help me?

**Comment by Falseee** [comment]
I close this issue because its older than 1 year, if you still need help pls reopen it and provive an [example](https://jsfiddle.net/).
