### ISSUE TITLE
The wenzhixin.net.cn documentation website is very slow

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#3779]
The documentation website wenzhixin.net.cn is very slow and sometime don't load even after 5 minutes. Can you transfer the documentation on Github instead?

**Comment by andrea-schneider** [comment]
We do have the same problem here in Europe. Is it not possible to make it working offline, as there is the bootstrap-table-examples-master.zip available already but it isn't working locally.

Thanks a lot

**Comment by djhvscf** [comment]
@wenzhixin what are our options here?

**Comment by wenzhixin** [comment]
Moved to Github page and used cdn instead.
