### ISSUE TITLE
Change CSS class if value is greater or equal to..  

### ISSUE THREAD

**Issue by f0u** [wenzhixin/bootstrap-table#378]
Hi!
Sorry if this question does not belong here. I didn't know where to ask it otherwise, and my knowledge in java is extremely limited :( 

My question is if it's possible to add a css class to a cell depending on if value in it, is -1 or less, and also another class if it's greater or equal to 0?.
After some goggling i have tried varius combination's like the example below.
```javascript
function cellStyle(value) {
   	if (value >= 0) {
		return 'value-plus'; 
	} else {
		return 'value-minus'; 
	}
}
```
thanks in advance

**Comment by wenzhixin** [comment]
Hi,

when you use cellStyle, I think you need to return an object, for example:

```js
function cellStyle(value) {
    if (value >= 0) {
        return {classes: 'value-plus'};
    } else {
        return {classes: 'value-plus'};
    }
}
```

you use the `<i>` element to solve it, it is OK, too.
