### ISSUE TITLE
How to overwrite table scrollbar?

### ISSUE THREAD

**Issue by camambeou** [wenzhixin/bootstrap-table#3784]
My clients complained and they order me to change kind of scrollbar.
I have implemented successfully the jquery.nicescroll on all divs, except bootstrap-tables.
How can I change or overwrite default table scrollbars with  jquery.nicescroll?
Sorry for request for other project issue.

**Comment by akkivarma10** [comment]
Hi @camambeou , you can use the onPostBody method hook to change the bootstrap-table scrollbar

**Comment by UtechtDustin** [comment]
Should this really a feature of the bootstrap-table ?
In my opinion just a few ppl will use it, its a custom feature which can implement by events as @akkivarma10 already wrote.

What do you think @wenzhixin @djhvscf ?

**Comment by djhvscf** [comment]
Yes, usually we recommend modify the scrollbar in the onPostBody event. I think this is not a good candidate for a feature label :)

**Comment by wenzhixin** [comment]
I agree with you. Added an example of this feature using [perfect-scrollbar](https://github.com/mdbootstrap/perfect-scrollbar).

Example: https://examples.bootstrap-table.com/index.html#issues/3784.html
Source: https://examples.bootstrap-table.com/index.html#issues/3784.html#view-source
