### ISSUE TITLE
I found a small bug on bootstrap-table.js at version 1.12.1

### ISSUE THREAD

**Issue by Run2948** [wenzhixin/bootstrap-table#3785]
**I try to trnslate myself  in english:**
when I use the version: 1.9.0 in my project, this isn't any problems. but once I upgraded to version 1.12.1: the style of the button
`<button class="btn btn-default" type="button" name="toggle" aria-label="toggle" title="切换">
</button>`
has no tablet 'i': `<i class="glyphicon glyphicon-list-alt icon-list-alt"></i> `
![Image text](https://images2015.cnblogs.com/blog/459756/201511/459756-20151125105634999-1118495771.png)(the switch button in this picture)

**中文说明：**
之前我使用bootstrap-table.js 1.9.0版本的时候，没有出现任何问题，但是当我更新到版本1.12.1后，部分按钮样式不能出现。我遇见的案例就是 切换按钮 没有icon图标，只出现了一个非常窄小的空白按钮。例如：
![Image text](https://images2015.cnblogs.com/blog/459756/201511/459756-20151125105634999-1118495771.png)(这个图片中的切换按钮)

**Comment by mdjaman** [comment]
Same bug maybe i should downgrade version

**Comment by gaptekupdate** [comment]
Add this to your Table Options

`data-icons="icons"`

And then, add this object anywhare in your footer

`<script>
    window.icons = {
               paginationSwitchDown: 'fa-toggle-down',
               paginationSwitchUp: 'fa-toggle-up',
               refresh: 'fa-refresh',
               toggleOff: 'fa-toggle-off',
               toggleOn: 'fa-toggle-on',
		  toggle: 'fa-list-alt',
                columns: 'fa-th-list',
                detailOpen: 'fa-plus',
                detailClose: 'fa-minus',
		  fullscreen: 'fa-arrows-alt'
    };
</script>`

**Comment by wenzhixin** [comment]
Fixed in v1.12.2

**Comment by mdjaman** [comment]
What about the share button? Still issue on it 🤕

**Comment by mdjaman** [comment]
![image](https://user-images.githubusercontent.com/803262/49233851-cd7baa80-f3ee-11e8-996d-8cf2dfcfdd0b.png)

Here a screenshot

**Comment by wenzhixin** [comment]
http://bootstrap-table-examples.wenzhixin.net.cn/#options/v4.html
