### ISSUE TITLE
Does anyone have a solution to order a column by date?

### ISSUE THREAD

**Issue by Agomezar** [wenzhixin/bootstrap-table#3786]
I have read some posts but I see that nobody has a real and effective solution

**Comment by jimgit** [comment]
Reply with a jsfiddle showing your problem - [here is a jsfiddle that should save you time getting started.](http://jsfiddle.net/wenyi/e3nk137y/18/)

One easy way is to send the data from the server in the yyyy-MM-dd format

Also look at these column settings:

![image](https://user-images.githubusercontent.com/1921941/39874140-95133764-5432-11e8-8669-6fd0198641b1.png)

also look at customSort - if you have a non-standard date requirement

![image](https://user-images.githubusercontent.com/1921941/39874113-80665166-5432-11e8-99d6-fe3432bb0d43.png)

**Comment by Agomezar** [comment]
My date is in "d-m-Y" format

**Comment by jimgit** [comment]
Can you include a yyyy-mm-dd in your data - if so use the following - you can display a field but sort it by a different column in your data.

If you can't do that you may have to use the custom sort.

![image](https://user-images.githubusercontent.com/1921941/39876987-494b6984-543a-11e8-9e68-a94bb9e8f2aa.png)

**Comment by jaydeepgiri** [comment]
Which server scripting are you using? @Agomezar if its PHP, 
You have to do it on .php file. 

here is my PHP side code 
```
         //Set default offset, limit, sort, order values
        $offset = 0; $limit = 10;
	$sort = 'date';  // Any field you want, example: 'id' or 'date'
        $order = 'DESC'; // Any order you want ASC
	$where = ''; //by default no value in where, if anything is searched than set the $where variable
	
        if(isset($_GET['offset'])) 
		$offset = $_GET['offset'];
	if(isset($_GET['limit']))
		$limit = $_GET['limit'];
		
	if(isset($_GET['sort']))
		$sort = $_GET['sort'];
	if(isset($_GET['order']))
		$order = $_GET['order'];
		
	if(isset($_GET['search'])){
		$search = $_GET['search'];
	        $where = " Where `id` like '%".$search."%' OR `title` like '%".$search."%' ";
	}
	//execute query for total number of rows
        $sql = "SELECT COUNT(*) as total FROM `orders` ".$where;
        // execute query for actual data.
        $sql = "SELECT * FROM `orders` ".$where." ORDER BY ".$sort." ".$order." LIMIT ".$offset.", ".$limit;	
        
```

Let me know if it works out.

**Comment by wenzhixin** [comment]
ref #1967, #2054
