### ISSUE TITLE
报告一个错误，关于服务器分页导出全部数据

### ISSUE THREAD

**Issue by 33881163** [wenzhixin/bootstrap-table#3790]
为了调试 "导出所有数据" 的功能， 发现无论如何设置，都无法使用  exportDataType: 'all' 把所有数据都导出。我这里是sidePagination: 'server'分页。

开始开源代码看，发现这里有个参数被增加了 #431: support pagination 在函数 BootstrapTable.prototype.load 中，
 if (this.options.pagination && this.options.sidePagination === 'server') 当 export 全部数据时， 触发 PaginationSwitch，然后Pagination = false ， 这样 造成 data = data.data， 而非 data = data[rows];

目前我暂时修改为  if ( this.options.sidePagination === 'server') ，调试后正常。希望您看后有更好的处理方式。

**Comment by 33881163** [comment]
也许我理解错误， 或者这样做？
传递了offset和limit，认为是服务端分页，返回的结果必须包含total、rows两个参数。
如果前台无offset和limit传入，返回一个集合对象到前端。

**Comment by wenzhixin** [comment]
@odinms 是对的
