### ISSUE TITLE
改变html font-size使toolbar变形

### ISSUE THREAD

**Issue by macdoor** [wenzhixin/bootstrap-table#3791]
通过style改变了html 的 font-size，使toolbar变形，refresh按钮似乎没有改变大小，而keep-open和export按钮变小了，search框的上下也无法对齐了
<img width="315" alt="2018-05-13 10 43 14" src="https://user-images.githubusercontent.com/29733517/39968414-11ebca98-56ff-11e8-83d8-695ed8016e17.png">

```
<style>
html {
    font-size: 12px;
}
</style>
```

jsfiddle还不太会用，后面加上

**Comment by wenzhixin** [comment]
试了下没有发现问题，应该是没有加上 DOCTYPE 吧：https://bootstrap-table.wenzhixin.net.cn/docs/getting-started/introduction/#html5-doctype
