### ISSUE TITLE
bootstrap 3 support breaks padding of tables in detailed view

### ISSUE THREAD

**Issue by mbystryantsev** [wenzhixin/bootstrap-table#3794]
Windows 7, Chrome 66.0.3359.139

Following lines set padding of all nested tables (e.g. in detailed view) to 0.
```
/* support bootstrap 3 */
.bootstrap-table .table thead > tr > th {
    padding: 0;
    margin: 0;
}
```

Reproducing: 
1. Create table with enabled `detailView`.
2. In `detailFormatter` return general table (not bootstrap-table) with header.

Result: Header's `th` have no padding.

**Comment by mbystryantsev** [comment]
Workaround:
```
.bootstrap-table .table .table thead > tr > th {
    padding: 8px;
}
```

**Comment by wenzhixin** [comment]
I think this issue fixed in the latest version.
