### ISSUE TITLE
post回来的数据变了 表格为什么不更新

### ISSUE THREAD

**Issue by 317073033** [wenzhixin/bootstrap-table#3795]
$.post({
        url: '/orders/search',
        data: 'searchData=' + JSON.stringify(searchData),
        success: function(data) {
          console.log(data)
            $table.bootstrapTable({data: data});
        }
      })

回来的数据变了 但是表格数据不更新啊

**Comment by 317073033** [comment]
$.post({
url: '/orders/search',
data: 'searchData=' + JSON.stringify(searchData),
success: function(data) {
console.log(data)
$table.bootstrapTable(load, data);
}
})

表格就没法显示了 

$table.bootstrapTable({data: data}); 第一次是可以加载的

**Comment by 317073033** [comment]
需要先加载一次数据$table.bootstrapTable({data:[]})

**Comment by wenzhixin** [comment]
对，使用方法之前需要初始化 table。
