### ISSUE TITLE
Browser freezes and prompts to stop script or continue when trying to render hundreds of rows in one page

### ISSUE THREAD

**Issue by luisapuyen** [wenzhixin/bootstrap-table#3796]
Is there any easy way to improve rendering Bootstraptable in cases like this? I need the table to have one page.

My research led me to this page:

[https://stackoverflow.com/questions/45875010/hanging-on-1000-or-5000-records-in-bootstrap-table?noredirect=1&lq=1
](https://stackoverflow.com/questions/45875010/hanging-on-1000-or-5000-records-in-bootstrap-table?noredirect=1&lq=1
)

I'm trying to set up clusterize.js along with Bootstraptable but I'm not sure how to do it. How do I prevent the table rows to be rendered by BootstrapTable, and get the results from it instead to pass them on to Clusterize.

Is there any other way to improve rendering large tables apart from server pagination?

Any plans on using some sort of virtual rendering in BootstrapTable?

**Comment by jimgit** [comment]
Please duplicate in a jsfiddle and post the link here.

**Comment by UtechtDustin** [comment]
We improved the performance of the table, so a lot of data should be a not huge probleme any more.
If you should have the same problems in the next version please reopen the issue !
