### ISSUE TITLE
boostarp-table-export导出报错

### ISSUE THREAD

**Issue by 756537479** [wenzhixin/bootstrap-table#3797]
boostrap-table-export.js报错如下：
Uncaught TypeError: that.$el.tableExport is not a function
我该怎么改

**Comment by yy1098029419** [comment]
I had faced this issue

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by 756537479** [comment]
源码的bug，换个版本，或者改源码的报错位置的js，不记得源码怎么改了，不过在贴子里有人回答过

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
