### ISSUE TITLE
Editable field type at runtime

### ISSUE THREAD

**Issue by gilbertoscruz** [wenzhixin/bootstrap-table#3798]
Hello how are you?

I'm using the component in a project and would like to know if it's possible to use the editable column option with the dynamic type.

For example, I have a column in the database that informs the type of the field, being: Text or Date. Is it possible to tell the type of the editable field type:" text" or type: "date" at runtime?

Thank you.

**Comment by UtechtDustin** [comment]
The column option [editable]() can be a function which get the row as parameter so you can choose the type based on the row which contains the data from the database.

Small example:
```
$('#table').bootstrapTable({
    editable: true,
    columns: [{
      field: 'id',
      title: 'Item ID',
    }, {
      field: 'name',
      editable: "editableOptions",
    }],
    data: [{
      id: 1,
      name: 'someName',
      editableType: 'text'
    }]
  });

function editableOptions(index, row, $element) {
    return {
      type: row.editableType
    }
  }
```
