### ISSUE TITLE
a little problem in boostrap-table-print.js

### ISSUE THREAD

**Issue by yueshouzhen** [wenzhixin/bootstrap-table#3799]
at line 78,revise  **if (!columns[h].printIgnore)** to **if (!columns[h].printIgnore && columns[h].field)**.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
