### ISSUE TITLE
can not export data to xlsx 

### ISSUE THREAD

**Issue by gyygyy32** [wenzhixin/bootstrap-table#3805]
i already show the code blow. 
http://jsfiddle.net/pfzhv6e4/1/   
setting like this:
`            
showExport: true,                     //是否显示导出
exportDataType: "all",              //basic', 'all', 'selected'.
exportTypes: ['json', 'xml', 'csv', 'txt', 'sql', 'xlsx'],
`

error screenshot
![image](https://user-images.githubusercontent.com/5733435/40306447-56e02882-5d31-11e8-8602-af52ec287820.png)

![image](https://user-images.githubusercontent.com/5733435/40279984-2426d7c2-5c7f-11e8-9027-a6dcc6a29d6a.png)

**Comment by dabros** [comment]
@gyygyy32 - always check supporting doco, the tableexport plugin this uses (and is linked in this extensions readme.md) shows for some file types additional files are needed

[extensions doco (just a sorted list with some links)](http://bootstrap-table.wenzhixin.net.cn/extensions/)

[extensions home pages / source + readme.md](https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions)

[tableExport.jquery.plugin ](https://github.com/hhurz/tableExport.jquery.plugin)

**Comment by wenzhixin** [comment]
https://github.com/hhurz/tableExport.jquery.plugin#installation
