### ISSUE TITLE
columns data-events  don't work

### ISSUE THREAD

**Issue by meloht** [wenzhixin/bootstrap-table#3806]
如果指定使用了events事件的列，field字段是字符串 例如 “name” ，click事件就不会响应，代码如下：

data.json

  [
    {
      "id": 1,
      "name": "bootstrap-table",
      "stargazers_count": 2156,
      "forks_count": 633,
      "description": "An extended Bootstrap table with radio, checkbox, sort, pagination, and other added features."
    }]

column js code:
{
                        field: 'name',
                        title: '操作',
                        formatter: actionFormatter,
                        events: actionEvents
                    }

    function actionFormatter(value) {
            return [
                '<a class="update" href="javascript:" title="Update Item"><i class="glyphicon glyphicon-edit"></i></a>',
                '<a class="remove" href="javascript:" title="Delete Item"><i class="glyphicon glyphicon-remove-circle"></i></a>',
            ].join('');
        }
        window.actionEvents = {
            'click .update': function (e, value, row) {
                alert("update");
            },
            'click .update': function (e, value, row) {
                alert("remove");
            }
        };

**Comment by dabros** [comment]
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

**Comment by meloht** [comment]
this is demo .
the columnsA click event don't work, but columnsB and columnsC  click events  work.

` 
        var $table = $("#tb_table");
        var json = [
            {
            StuId: "123",
            StuName: "hhhh",
            DataId: 1
        },
        {
            StuId: "555",
            StuName: "ddddd",
            DataId: 2
        },
        {
            StuId: "4444",
            StuName: "aaaaa",
            DataId: 3
        }
        ];

        function opFormatterA() {
            return [
                '<a class="updateA" href="javascript:" title="Update Item"><i class="glyphicon glyphicon-edit"></i>edit</a>',
                '<a class="removeA" href="javascript:" title="Delete Item"><i class="glyphicon glyphicon-remove-circle"></i>remove</a>',
            ].join('');
        };


        window.actionEventsA = {
            'click .updateA': function (e, value, row) {
                alert("update:" + value);
            },
            'click .removeA': function (e, value, row) {
                alert("remove:" + value);
            }
        };

        function opFormatterB() {
            return [
                '<a class="updateB" href="javascript:" title="Update Item"><i class="glyphicon glyphicon-edit"></i>edit</a>',
                '<a class="removeB" href="javascript:" title="Delete Item"><i class="glyphicon glyphicon-remove-circle"></i>remove</a>',
            ].join('');
        };


        window.actionEventsB = {
            'click .updateB': function (e, value, row) {
                alert("update:" + value);
            },
            'click .removeB': function (e, value, row) {
                alert("remove:" + value);
            }
        };
        function opFormatterC() {
            return [
                '<a class="updateC" href="javascript:" title="Update Item"><i class="glyphicon glyphicon-edit"></i>edit</a>',
                '<a class="removeC" href="javascript:" title="Delete Item"><i class="glyphicon glyphicon-remove-circle"></i>remove</a>',
            ].join('');
        };


        window.actionEventsC = {
            'click .updateC': function (e, value, row) {
                alert("update:" + value);
            },
            'click .removeC': function (e, value, row) {
                alert("remove:" + value);
            }
        };

        $(function () {
            initTable();
            $table.bootstrapTable('load',json);
        });



        function initTable() {
            $table.bootstrapTable({
                striped: true,
                cache: false,
                pagination: false,
                sortable: false,
                sortOrder: "asc",
                search: false,
                strictSearch: false,
                showColumns: false, 
                showRefresh: false, 
                minimumCountColumns: 2, 
                clickToSelect: false, 
                uniqueId: "DataId", 
                showToggle: false, 
                cardView: false, 
                detailView: false, 
                columns: [
                   
                    {
                        field: 'StuId',
                        title: 'StuId'

                    }, {
                        field: 'StuName',
                        title: 'StuName'

                    }, {
                        field: 'StuName',
                        title: 'columnsA',
                        formatter: opFormatterA,
                        events: actionEventsA

                    },
                    {
                        field: 'DataId',
                        title: 'columnsB',
                        formatter: opFormatterB,
                        events: actionEventsB

                    },
                    {
                        title: 'columnsC',
                        formatter: opFormatterC,
                        events: actionEventsC

                    }
                ]
                });
            };


    `

**Comment by meloht** [comment]
![20180529145712](https://user-images.githubusercontent.com/8925314/40643305-44f842d6-6352-11e8-9032-9d26e2e09aa5.png)

**Comment by dabros** [comment]
@meloht - please see the links and info and provide a fiddle. A fiddle is a gurenteed testing environment, i can promise you my current servers are setup very differently and a fiddle helps everyone

**Comment by wenzhixin** [comment]
I think the problem fixed in the latest version.

**Comment by he615686916** [comment]
`{
            field: "",
            title: "金额",
            width: "10%",
            align: "center",
            formatter:function (value, rowData, index, field) {
                if (rowData.feeType === '医疗费') {
                    rowData.feeAmount = rowData.invoiceAmount - rowData.NonMedicalInsuranceDeductions - rowData.UnreasonableFee;
                }
                return '<input class="form-control column0" field-name="feeAmount" type="text" value="' + rowData.feeAmount + '"/>'
            },
            events:{'blur .column0':function(){console.log(0)}}
        },
        {
            field:"",
            width:"5%",
            formatter:function () {
                return '';
            },
        },
        {
            field: "",
            title: "计算明细",
            width: "75%",
            align: "center",
            formatter: function (value, rowData, index, field) {
                return '<input field-name="invoiceAmount" class="form-control column1" type="text" value="' +rowData.invoiceAmount+'"/>';
                if (rowData.feeType === '医疗费') {
                    return '<label class="col-md-1 control-label">发票金额</label><div class="col-md-2"><input field-name="invoiceAmount" class="form-control column1" type="text" value="' +rowData.invoiceAmount+'"/></div>'+
                         '<label class="col-md-1 control-label" style="text-align: center">-</label><label class="col-md-1 control-label">非医保扣减</label>'+ '<div class="col-md-2"><input field-name="NonMedicalInsuranceDeductions" class="form-control" type="text" value="' +rowData.NonMedicalInsuranceDeductions+'"/></div>'+
                         '<label class="col-md-1 control-label" style="text-align: center">-</label><label class="col-md-1 control-label">不合理费用</label>'+'<div class="col-md-2"><input field-name="UnreasonableFee" class="form-control" type="text" value="' +rowData.UnreasonableFee+'"/></div>'
                } else if (rowData.feeType === '伙补费') {
                    return '<label class="col-md-1 control-label">伙食费标准</label><div class="col-md-2"><input  field-name="standardFoodSubsidies" class="form-control" type="text" value="' + rowData.standardFoodSubsidies + '"/></div>'+
                    '<label class="col-md-1 control-label" style="text-align: center">x</label><label class="col-md-1 control-label">住院时长</label>'+ '<div class="col-md-2"><input field-name="inpatientDay" class="form-control" type="text" value="' +rowData.inpatientDay+'"/></div>';
                } else {
                    return '';
                }
            },
            events:{'blur .column1':function(){console.log(1)}}
        }`


the column of  '计算明细'  events do not work.
