### ISSUE TITLE
resetRows函数问题

### ISSUE THREAD

**Issue by ycymio** [wenzhixin/bootstrap-table#3807]
出现问题如下：
如果选择了一些checkbox，之后进行查找，之前选中的依旧会被选中，getSelection并不起作用，因为search操作不会set checkbox的field为false。

我查看了一下bootstrap-table.js文件。

    BootstrapTable.prototype.resetRows = function () {
        var that = this;
        $.each(this.data, function (i, row) {
            that.$selectAll.prop('checked', false);
            that.$selectItem.prop('checked', false);
            if (that.header.stateField) {
                row[that.header.stateField] = false;
            }
        });
        this.initHiddenRows();
    };

这里的this.data只是search后的结果，而不是之前所有的行，所以未显示的行的stateField并没有设置为false。

这是个bug么？有什么解决方法么？

我看了之前https://github.com/wenzhixin/bootstrap-table/issues/2485 的问题，用到了的jsFiddler中把radio改成checkbox就能复现这个问题了。

**Comment by wenzhixin** [comment]
Fixed by #4406.
Working example: http://jsfiddle.net/wenyi/e3nk137y/44385/
