### ISSUE TITLE
show or hide rows in a jquery array of tr elements?

### ISSUE THREAD

**Issue by tylerecouture** [wenzhixin/bootstrap-table#3808]
If I have a jquery array of rows `$rows`, what is the easiest way to show or hide them?  The rows may also have bootstrap-table search filter applied, if that makes a difference.

for example, say I have a selector of rows containing specific text (distinct from the Bootstrap table search)
`$rows = $("tr:has(td:contains('some text'))";`

How can I do the equivalent of what this would do if it worked =)?
`$table.bootstrapTable('showRow', $rows );`

**Comment by Falseee** [comment]
@tylerecouture 
Do you still need help ?

Just use a for each on you array and then use [hideRow](https://bootstrap-table.com/docs/api/methods/#hiderow).

**Comment by Falseee** [comment]
I close this issue because we got no response within 7 days.
