### ISSUE TITLE
Manual sorting

### ISSUE THREAD

**Issue by Fanda36** [wenzhixin/bootstrap-table#381]
Hi,
I write manual sorting function:

function dateCompare(a, b){
	var x = getDate(a);
	var y = getDate(b);
	if (x > y) return 1;
    if (x < y) return -1;
    return 0;
}

If I set on column with this setting (formater, without formater work):

sortable: true,
sorter: 'dateCompare',
formatter:"dateInsertFormatter",

so my function dateCompare get param a and b = undefined (in cell is "28. 12. 2014   23:32:23").

Any idea? Thanks

**Comment by wenzhixin** [comment]
The same with #70, close this.
