### ISSUE TITLE
footerStyle does not support classes

### ISSUE THREAD

**Issue by gong-liu** [wenzhixin/bootstrap-table#3811]
Unlike rowStyle, footerStyle does not support css classes even though the document says so. 

Example:

function footerStyle(value, row, index) {
          return {
              classes: 'success',                      //this does not work
              css: { "font-weight": "bold" }      //this works
          };
}
The column's 'class' option works on the footer, but then it applies to the entire column, not just the footer. With current implementation, it's not possible, say, to have a column in one color and the corresponding footer in a different color.

Can we maybe do this:

Add this line above line# 2355:
class_ = sprintf(' class="%s"', style.classes || column['class']);

Thanks

**Comment by wenzhixin** [comment]
Fixed in v1.13.5.
https://examples.bootstrap-table.com/#options/footer-style.html
