### ISSUE TITLE
Docs site is down

### ISSUE THREAD

**Issue by cindymarie** [wenzhixin/bootstrap-table#3813]
I cannot connect to the following site:
http://bootstrap-table.wenzhixin.net.cn/

p.s. accessing from the philippines

**Comment by dabros** [comment]
@wenzhixin - its been a bit flaky, does load but most days i try to access it has long long load times, really is an issue as impacting any access to doco's while i implemented this after long time without use

fyi - accessing from queensland australia

**Comment by dabros** [comment]
@wenzhixin - this is becoming an issue when trying to find doco for my own project, and im reluctant to share doco link responding to help other users as its so slow as to actually time out on slow connections.

**Comment by wenzhixin** [comment]
Now the documentation is released in [gh_pages](https://github.com/wenzhixin/bootstrap-table/tree/gh-pages) branch and use GitHub Pages site.
