### ISSUE TITLE
Unexpected token: operator (>) Line 7 in src/bootstrap-table.js

### ISSUE THREAD

**Issue by si458** [wenzhixin/bootstrap-table#3814]
`Unexpected token: operator (>) Line 7 in src/bootstrap-table.js`

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

OSX 10.13.4

1. download zip of develop 
2. `npm install`
3. `npm run grunt`

Warning: Uglification failed.
Unexpected token: operator (>). 
Line 7 in src/bootstrap-table.js
 Use --force to continue.

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

only way around this issue seems to be to run   `grunt --force`

**Comment by wenzhixin** [comment]
Fixed in the latest version.
