### ISSUE TITLE
Export all records from custom button

### ISSUE THREAD

**Issue by yami12376** [wenzhixin/bootstrap-table#3815]
Consider this example:
http://jsfiddle.net/wc0zLpef/216/

How can i export all data records by click?
I tried adding:
```
    $('#export').bootstrapTable('refreshOptions',{
      exportDataType: 'all'
    });
```
or
```
      exportDataType: 'all',
      refreshOptions: { exportDataType: 'all'}
```

**Comment by djhvscf** [comment]
It looks like the example is working as expected. If not, please add steps to reproduce.

**Comment by yami12376** [comment]
@djhvscf "How can i export all data records by click?"
By all i mean not 2 elements - but "ALL" so "Showing 1 to 2 of 5 rows"
I want export 5, when showing only 2.

**Comment by Falseee** [comment]
https://examples.bootstrap-table.com/#extensions/export.html
You see only the first 10 Rows, but if you choose `Export All` and you export it you export all Rows.
If you still need help pls reopen the issue.
