### ISSUE TITLE
Filter control extension, not working as expected when populated programmatically

### ISSUE THREAD

**Issue by Junglefish** [wenzhixin/bootstrap-table#3816]
Imagine a simple bootstrap table with two columns, a bit like your example (http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html).

If you type a value in Field A, we filter on Field A. If you then type a value in Field B, we filter on both Fields A and B. This is all fine.

However, I have noticed that if I set the value of those filters programmatically, eg. something like this:
display.$mainPage.find(".certificates_table .bootstrap-table-filter-control-field_a").val('aaa');
display.$mainPage.find(".certificates_table .bootstrap-table-filter-control-field_b").val('bbb');

If you then manually change the value on Field A, we filter *only* on Field A. The expected behaviour should be to filter on both Fields A and B, because Field B has a value.

I have tried to figure out how to in some way "register" the value of the fields with the filter when I set them programmatically by also programmatically firing the 'change' and/or 'focus' events, but that makes no difference.

Is there a solution to this?

Also...
A secondary issue is that, by populating the filter values programatically, it now seems to take TWO clicks of the Clear Search icon for it to take effect.

**Comment by UtechtDustin** [comment]
I close this issue because its already 1 year old, if you still need help please provide us examples and reopen the issue.
