### ISSUE TITLE
Two Row Header -- merged header/colspan not updating when using Show-Column Filter 

### ISSUE THREAD

**Issue by esterkjuicepress** [wenzhixin/bootstrap-table#3817]
When a two level header contains a merged cell (colspan > 1) in the first row (index: 0) and no columns are to the right, the table displays properly. If the merged cell in the first row is not the last cell in that row, then it will not update its colspan as "sub-columns" are hidden.

I believe this is an issue, but I could just be misinformed.

Before any columns are hidden:
![image](https://user-images.githubusercontent.com/39343012/40503810-573af27a-5f5d-11e8-8c16-086842494b02.png)

After the Item Operate column is hidden:
![image](https://user-images.githubusercontent.com/39343012/40503980-d38dc96a-5f5d-11e8-90a8-607184db1114.png)

[jsfiddle](http://jsfiddle.net/L9w5L5oy/)

**Comment by esterkjuicepress** [comment]
Anyone?

**Comment by esterkjuicepress** [comment]
Thank you. What sort of timeframe for this? In the meantime, I am using a crude method by tracking colspan sizes on my own and adjusting whenever there is a ` column-switch.bs.table` event. Not a great workaround, but it's getting the job done while unfortunately causing a good amount of lag for large (+50 column) tables.

**Comment by esterkjuicepress** [comment]
No updates?

**Comment by djhvscf** [comment]
This is resolved in latest version.
