### ISSUE TITLE
ShowRefresh has refresh symbol with bootstrap 4

### ISSUE THREAD

**Issue by Blue1791** [wenzhixin/bootstrap-table#3818]
When I added showRefresh: true under bootstrap 4 the button appears and works correctly, but there is no refresh icon (it is just a button).  Is there code I can add to map it to font awesome?

**Comment by Blue1791** [comment]
the problem appears to be bootstrap 4.1.0 vs 4.0.0. the only thing I changed was I removed the bootstrap 4.0.0 resources and replaced with 4.1.0.

http://jsfiddle.net/wenyi/e3nk137y/25378/

**Comment by TantumLabs** [comment]
This has nothing to do with which version of bootstrap 4 you are using and everything to do with which version of FontAwesome you are using. As of FontAwesome version 5 fa-refresh has been replaced with fa-sync.
