### ISSUE TITLE
 Filter by multiple columns

### ISSUE THREAD

**Issue by ivanstefanov** [wenzhixin/bootstrap-table#3823]
Hello, I want to filter the grid by multiple columns as shown on https://jsfiddle.net/mwatz122/8mkpd3qd/ , but it doesn't work.

Found out couple of main differences between my code and the example above:

- My code is with the latest version of bootstrap-table grid
- I am loading my data using the data attribute and I am providing this data as json array 

Here is little bit more information about my implementation:

```
<link href="/bower_components/bootstrap-table/dist/bootstrap-table.min.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="/bower_components/bootstrap-table/dist/extensions/filter-control/bootstrap-table-filter-control.css">
<script src="/bower_components/bootstrap-table/dist/bootstrap-table.min.js"></script>
<script src="/bower_components/bootstrap-table/dist/extensions/filter-control/bootstrap-table-filter-control.js"></script>

```

This is how my grid has been configured:

```
        $('#grid').bootstrapTable({
            data: myData,
            pagination: 'true',
            pageList: "[5, 10, 20, 50, 100, 200]",
            pageNumber: 1,
            pageSize: 10,
            sortName: 'id',
            filterControl: true
        });
```

Here are example of grid columns:
```
<table id="grid">
    <thead>
        <tr>
<th data-field="someField" data-sortable="true" data-filter-control="input">Field Title</th>
....

```

Currently I have working filter by one column. When I decide to filter by another column on already filtered result, it do the whole filter again, despite to filter just the current data

**Comment by hebriels** [comment]
Hi! The same problem, how to solve it?

**Comment by grantemsley** [comment]
Same problem here.  Anyone find a solution?

**Comment by RrOoSsSsOo** [comment]
The last version that works is v1.10.1... the following ones no

**Comment by Blue1791** [comment]
same problem here, would love to see a solution for this.

**Comment by ktecho** [comment]
@ivanstefanov and anyone. Did you found a solution to this problem? Thanks!

**Comment by ivanstefanov** [comment]
I manage to do it by myself. I put text boxes above the grid columns and on keypress I am collecting their values and do the actual filtering over the grid datasource:

function customFilter() {        
        var filter1 = $("#filter1").val().toLowerCase();
		var filter2 = $("#filter2").val().toLowerCase();
		var filter3 = $("#filter3").val().toLowerCase();        

        $('#gridSelector').bootstrapTable('load', $.grep(gridDataSource, function (row) {
            return (
                columnFilterByInputValue(row['col1'], filter1)
                && columnFilterByInputValue(row['col1'], filter2)
                && columnFilterByInputValue(row['col3'], filter3)                
            );
        }));
    }

**Comment by Falseee** [comment]
Seems to works https://examples.bootstrap-table.com/#extensions/filter-control.html
If this issue still exists pls reopen the issue.
