### ISSUE TITLE
pagination of TreeGrid table does not work

### ISSUE THREAD

**Issue by ysguy** [wenzhixin/bootstrap-table#3829]
When using TreeGrid on a table pagination either client or server side fails. 

Your TreeGrid Example: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/treegrid.html

**If you choose server** regardless of the response from the server, the table will show no results. 
**If you choose client** the table will correctly split and show the first page of results, subsquent pages do not have the expand/collapse functionality and shows all records expanded. The pagination number of pages becomes wrong at that point. 

Please advise on solution.

**Comment by djhvscf** [comment]
@foreveryang321

**Comment by ysguy** [comment]
Update: I've found that Setting 
```
pagination: true,
sidePagination: 'client',
```

and then adding
```
onSearch: function(){ $status_table.bootstrapTable('removeAll'); }, //fixes search breaking with no results
onPageChange: function(){ $status_table.bootstrapTable('refresh'); }, //fixes pagination breaking collapse/expand function
```

Seems to fix the pagination issues. I haven't tried "Server Side Pagination" yet, but i suspect it will work with the additional refresh. More of a workaround than a fix. Seems treegrid might be firing too fast after results are paginated.

Additional issues found.

The item count is cumulative for all items and should only be for "Parent" items. 
The pagination [<][1][2][3][4][5][>] buttons are too many as they are created by taking the total # of items and dividing by the number of items / page. 

If i have 10 parent items each with 2 sub-items, that makes a total of 30 items. If i set pagination to 5 items per page, it should show  [<][1][2][>] as there are 10 collapsed items

However it currently shows  [<][1][2][3][4][5][6][>] for 30 total items. Selecting 3,4,5,6 yields blank results. 

Looking through the bootstrap-table.min.js I can't see how to fix this nicely as it simply counts the number of incoming JSON lines. What you'd need to do is to count all items with a pid = "0" which doesn't help 95% of your users who just use Bootstrap-tables without treeview. Perhaps treeview could utilize nested json OR have a way to feed the item count in as an option to override the internal row counting.

**Comment by Assiel** [comment]
Hi dear, can you provide me a complete example about your solution?
