### ISSUE TITLE
How do I style the checkboxes?

### ISSUE THREAD

**Issue by iamthestreets** [wenzhixin/bootstrap-table#383]
Hi,

I am using [Flat UI](http://designmodo.github.io/Flat-UI/) to style my page and wanted to know how i can use it to style my checkboxes?

Right now when I add the JS file I get this: 
![untitled](https://cloud.githubusercontent.com/assets/8740821/5582883/7ed38cb2-903e-11e4-99b3-a4b272ee1e77.png)

How do I get the styled checkboxes to appear in place of the regular checkboxes?

**Comment by wenzhixin** [comment]
Hi, I have added an example: http://issues.wenzhixin.net.cn/bootstrap-table/383.html

**Comment by iamthestreets** [comment]
Thanks! Everything worked except for the drop down to hide or show columns is not working. When I uncheck one box it unchecks all other boxes but only hides the column of the box I unchecked. It also continuously changes the size of the width every time I check or uncheck. 

Should I open another issue?

**Comment by cindymujica** [comment]
> [Aquí hay un jsfiddle con casilla de verificación:](http://jsfiddle.net/wenyi/e3nk137y/30/) cámbielo a lo que está tratando de hacer y envíe un enlace para que podamos ayudarlo.

So I'm using it and it still does not show me the boxes.

``<table id='table2' class='table table-responsive-md'
                       data-toggle='table'
                       data-pagination='true'
                       data-page-size='6'
                       data-pagination-first-text='<<|'
                       data-pagination-pre-text='Ant.'
                       data-pagination-next-text='Sig.'
                       data-pagination-last-text='|>>'
                       data-sort-name='id'
                       data-sort-order='desc'
                       data-filter-control="true" 
                       data-click-to-select="true"
                       data-maintain-selected="true"
                       data-selectable-highlight="true">
                       <thead>
                            <tr>
                                <th data-field="state" data-checkbox="true"></th>
                
                                <th data-field="codigo">CÓDIGO</th>
                                <th data-field="dni">DNI</th>
                                <th data-field="nombre">NOMBRE</th>
                                <th data-field="apellido">APELLIDO</th>
                                <th data-field="telefono">TELÉFONO</th>
                                <th data-field="cargo">CARGO</th>
                                <th data-field="sector">SECTOR</th>
                                <th data-field="centroCosto">CENTRO DE COSTO</th>
                                <th data-field="fecha_expiracion">FECHA EXPIRACIÓN</th>
                                <th data-field="estado">ESTADO</th>
                            </tr>
                        </thead>
                    </table>``

![image](https://user-images.githubusercontent.com/18073018/48208204-104ae500-e351-11e8-8b38-99f7783f6757.png)

**Comment by jimgit** [comment]
Please modify one of the jsfiddles that is close to what you are trying to do so we can reproduce the problem.   

I find two cases - you want to use the checkbox for selecting the record or you have one or more checkboxes with functionality such as CanSignChecks and CanPrintChecks.   In the second case, I find it easier to use the data-formatter to format/style the checkbox.   [Here is an example using the data-formatter ](http://jsfiddle.net/jimkennelly/5d2rpv4h/)


![image](https://user-images.githubusercontent.com/1921941/48212524-63b53700-e341-11e8-8b57-2de90d2fb372.png)

**Comment by GerryGe** [comment]
@iamthestreets How do you fix the drop down cannot been opened issues?
