### ISSUE TITLE
export table plugin is not exporting all records

### ISSUE THREAD

**Issue by shows19** [wenzhixin/bootstrap-table#3830]
export table plugin is not exporting all records. it was working fine before ver 1.12.1

Details:
- server side pagination
- data attribute: data-export-data-type="all"

see this jsfiddle (when u export only current page records are exported)

http://jsfiddle.net/p17r31L7/

**Comment by jimgit** [comment]
Wondering if it's related to server side pagination - did you you use server side pagination before with the export?
[See this client side pagination JSFIDDLE](http://jsfiddle.net/jimkennelly/cvje47p1/)

**Comment by shows19** [comment]
i have clearly mentioned server side pagination

Note:
- same code with previous version working fine

**Comment by shows19** [comment]
@wenzhixin plz take a look at it

**Comment by shows19** [comment]
@djhvscf request to kindly look into it.

**Comment by djhvscf** [comment]
@shows19 working in progress

**Comment by Jav3k** [comment]
@djhvscf, up

**Comment by shows19** [comment]
@wenzhixin is there any update?

**Comment by wenzhixin** [comment]
Fixed in v1.13.0, example: http://bootstrap-table-examples.wenzhixin.net.cn/#issues/3830.html
