### ISSUE TITLE
不能重现jsfiddle上的example

### ISSUE THREAD

**Issue by chy89310** [wenzhixin/bootstrap-table#3831]
我刚接触这个库，感觉功能很强大，然后想去jsfiddle试下，我能运行你提供的jsfiddle的example，但当我自己另外创建一个的时候，却不能显示数据，我甚至直接复制了你的example依然是不行，可以帮我看看哪里出错了么？

[jsfiddle链接](https://jsfiddle.net/kevinsum/unmmvr0u/5/)

**Comment by wenzhixin** [comment]
你可以使用最新的 http://bootstrap-table-examples.wenzhixin.net.cn
