### ISSUE TITLE
search can not work and multipleSearch cannot search one keyword

### ISSUE THREAD

**Issue by sunweihao** [wenzhixin/bootstrap-table#3832]
I have set the search true, but it doesn't work any more and when i use multipleSearch, it works in more than one keywords but if I use one, it doesn't work anymore
since the code is so easy, I think it needless to post it here

please help!

**Comment by UtechtDustin** [comment]
Normal search works fine: https://examples.bootstrap-table.com/index.html#options/table-search.html
Multi search also works fine: http://jsfiddle.net/e3nk137y/3046/
