### ISSUE TITLE
After calling refresh the pagination trys to stay on same page even if the data has changes.

### ISSUE THREAD

**Issue by BinaryVirus01** [wenzhixin/bootstrap-table#3833]
when calling .bootstrapTable("refresh") the table doesn't go to the 1st page, and if the # of pages change it tries to stay on  the page that inst available.

Step One. Change bootstrap data.
Step Two. Call refresh method.
Step Three. Watch bootstrap table not jump back to 1st page.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/3833)).

**Comment by rpannell** [comment]
Looks like somewhere down the line this was removed

 if (params && params.pageNumber) {
    this.options.pageNumber = params.pageNumber;
} else {
    this.options.pageNumber = 1;
}

**Comment by UtechtDustin** [comment]
If you wish to go back to page 1 or something else please use the [selectPage](https://bootstrap-table.com/docs/api/methods/#selectpage) method.
