### ISSUE TITLE
It is possible to insert a new row with a new data after some condition?

### ISSUE THREAD

**Issue by lukenotskywalker** [wenzhixin/bootstrap-table#3835]
Hi there!

I am developing a page that shows something like a bank statement, and i was wondering if it's possible i insert a new row with the balance at the end of each day. I don't want a solution, but if it's possible, i would like some ideas of how i can reach my target.

My best regards,
Luke

**Comment by jimgit** [comment]
[Look at the ADD ROW button in this example](http://jsfiddle.net/jimkennelly/a2p40csz/)

**Comment by dabros** [comment]
@lukenotskywalker - sounds like your looking for a configurable and computed footer, which is very easily handled

Look at these options: 

`showFooter`, `footerStyle` for table

 `footerFormatter`, `falign` for each column

http://bootstrap-table.wenzhixin.net.cn/documentation/

The footer would receive one param, `data`, which holds data for all rows (accounting for any filters). Not certain how that plays with pagination, but assumes it knows well how to go both ways.

Seems to be some server issues right now with doco hosting site, still loads though and you can grab source code for bunch of relevent examples from here: https://github.com/wenzhixin/bootstrap-table-examples

**Comment by lukenotskywalker** [comment]
@dabros @jimgit 
Thanks for the tips, unfortunately I and my labelmates decided to give up the bank statement part of the project, but i'll try to use the same code and your tips on another personal project.

Thanks so much!
