### ISSUE TITLE
bootstrap-table 源码语法问题

### ISSUE THREAD

**Issue by hlcgithub** [wenzhixin/bootstrap-table#3836]
![image](https://user-images.githubusercontent.com/16267895/41146906-7984f73c-6b37-11e8-97cb-332ff22c3ee6.png)

这是bootstrap-table源码刚开始的部分。看不懂，所以想请问一下，这种定义变量的语法是什么意思？

**Comment by wingmeng** [comment]
定义版本号用以处理 Bootstrap 3 和 4 的差异性，以便同时兼容 Bootstrap 3 和 4。
