### ISSUE TITLE
扩展bootstrap-table,使用服务代理获取数据时包含两次请求

### ISSUE THREAD

**Issue by 491134648** [wenzhixin/bootstrap-table#3838]
当通过一些服务函数去获取请求数据填充bootstrap时会碰到bootstrap请求两次的情况，不知是我的封装有问题还是，
![image](https://user-images.githubusercontent.com/9816794/41189749-4620dd42-6c05-11e8-9084-400e80340131.png)
求解,代码如下:
`(function ($) {
    'use strict';

    //debugger;
    //通过构造函数获取到bootstrapTable里面的初始化方法
    var BootstrapTable = $.fn.bootstrapTable.Constructor,
        _initData = BootstrapTable.prototype.initData,
        _initPagination = BootstrapTable.prototype.initPagination,
        _initBody = BootstrapTable.prototype.initBody,
        _initServer = BootstrapTable.prototype.initServer,
        _initContainer = BootstrapTable.prototype.initContainer;

    //重写
    BootstrapTable.prototype.initData = function () {
        _initData.apply(this, Array.prototype.slice.apply(arguments));
    };

    BootstrapTable.prototype.initPagination = function () {
        _initPagination.apply(this, Array.prototype.slice.apply(arguments));
    };

    BootstrapTable.prototype.initBody = function (fixedScroll) {
        _initBody.apply(this, Array.prototype.slice.apply(arguments));
    };

    BootstrapTable.prototype.initServer = function (silent, query) {
        //构造自定义参数
        for (var key in this.options.methodParams) {
            $.fn.bootstrapTable.defaults.methodParams[key] = this.options.methodParams[key];
        }
        //如果传了url，则走原来的逻辑
        if (this.options.url) {
            _initServer.apply(this, Array.prototype.slice.apply(arguments));
            return;
        }
        //如果定义了abpMethod，则走abpMethod的逻辑
        if (!this.options.abpMethod) {
            return;
        }
        var that = this,
            data = {},
            params = {
                pageSize: this.options.pageSize === this.options.formatAllRows() ?
                    this.options.totalRows : this.options.pageSize,
                pageNumber: this.options.pageNumber,
                searchText: this.searchText,
                sortName: this.options.sortName,
                sortOrder: this.options.sortOrder
            },
            request;

        
        //debugger;
        if (this.options.queryParamsType === 'limit') {
            params = {
                search: params.searchText,
                sort: params.sortName,
                order: params.sortOrder
            };
            if (this.options.pagination) {
                params.limit = this.options.pageSize === this.options.formatAllRows() ?
                    this.options.totalRows : this.options.pageSize;
                params.offset = this.options.pageSize === this.options.formatAllRows() ?0:this.options.pageSize * (this.options.pageNumber - 1);
            }
        }

        if (!($.isEmptyObject(this.filterColumnsPartial))) {
            params['filter'] = JSON.stringify(this.filterColumnsPartial, null);
        }

        data = $.fn.bootstrapTable.utils.calculateObjectValue(this.options, this.options.queryParams, [params], data);

        $.extend(data, query || {});

        // false to stop request
        if (data === false) {
            return;
        }

        if (!silent) {
            this.$tableLoading.show();
        }
        
        this.options.abpMethod(data).done(function (result) {
            result = $.fn.bootstrapTable.utils.calculateObjectValue(that.options, that.options.responseHandler, [result], result);
            that.load(result);
            that.trigger('load-success', result);
        });
        request = $.extend({}, $.fn.bootstrapTable.utils.calculateObjectValue(null, this.options.ajaxOptions), {
            type: this.options.method,
            url: this.options.url,
            data: this.options.contentType === 'application/json' && this.options.method === 'post' ?
                JSON.stringify(data) : data,
            cache: this.options.cache,
            contentType: this.options.contentType,
            dataType: this.options.dataType,
            success: function (res) {
                debugger;
                res = $.fn.bootstrapTable.utils.calculateObjectValue(that.options, that.options.responseHandler, [res], res);
                that.load(res);
                that.trigger('load-success', res);
            },
            error: function (res) {
                that.trigger('load-error', res.status, res);
            },
            complete: function () {
                if (!silent) {
                    that.$tableLoading.hide();
                }
            }
        });

        if (this.options.ajax) {
            $.fn.bootstrapTable.utils.calculateObjectValue(this, this.options.ajax, [request], null);
        } else {
            $.ajax(request);
        }
    }

    BootstrapTable.prototype.initContainer = function () {
        _initContainer.apply(this, Array.prototype.slice.apply(arguments));
    };

    abp.bootstrapTableDefaults = {
        striped: false,
        classes: 'table table-striped table-bordered table-advance table-hover',
        pagination: true,
        cache: false,
        sidePagination: 'server',
        uniqueId: 'id',
        showRefresh: false,
        search: false,
        method: 'post',
        //toolbar: '#toolbar',
        pageSize: 25,
        paginationPreText: '上一页',
        paginationNextText: '下一页',
        queryParams: function (param) {
            var abpParam = {
                Sorting: param.sort,
                filter: param.search,
                skipCount: param.offset,
                maxResultCount: param.limit
            };
            for (var key in $.fn.bootstrapTable.defaults.methodParams) {
                abpParam[key] = $.fn.bootstrapTable.defaults.methodParams[key];
            }
            return abpParam;
        },
        responseHandler: function (res) {
        	return { total: res.totalCount, rows: res.rows };
        },
        methodParams: {},
        abpMethod: function () { }
    };
    
    $.extend($.fn.bootstrapTable.defaults, abp.bootstrapTableDefaults);
})(jQuery);`
调用代码如下
`/**
 * 初始化bootstrap.table
 * @param {any} tb 表格元素
 * @param {any} abpmethod abp方法
 * @param {any} dbQueryParams 请求参数
 * @param {any} tbColumns  列
 * @param {any} actionUrl 请求链接
 * @param {any} uniqueId  主键id
 * @param {any} toolbar 工具栏
 * @param {any} method http method
 */
function InitTable(tb, abpmethod, dbQueryParams, tbColumns, actionUrl, uniqueId,toolbar,method) {
    $(tb).bootstrapTable({
        abpMethod: abpmethod,
        url: actionUrl,         //请求后台的URL（*）
        method: method ? method: 'post',                      //请求方式（*）
        toolbar: toolbar ? toolbar:'#toolbar',                //工具按钮用哪个容器
        striped: true,                      //是否显示行间隔色
        cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
        pagination: true,                   //是否显示分页（*）
        sortable: false,                     //是否启用排序
        sortOrder: "asc",                   //排序方式
        queryParams: dbQueryParams,//传递参数（*）
        sidePagination: "server",           //分页方式：client客户端分页，server服务端分页（*）
        pageNumber: 1,                       //初始化加载第一页，默认第一页
        pageSize: 15,                       //每页的记录行数（*）
        pageList: [15, 25, 50, 100],        //可供选择的每页的行数（*）
        search: false,                       //是否显示表格搜索，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
        strictSearch: true,
        showColumns: true,                  //是否显示所有的列
        showRefresh: true,                  //是否显示刷新按钮
        //minimumCountColumns: 2,             //最少允许的列数
        clickToSelect: true,                //是否启用点击选中行
        //height: 500,                        //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
        uniqueId: uniqueId?uniqueId:"Id",                     //每一行的唯一标识，一般为主键列
        showToggle: true,                    //是否显示详细视图和列表视图的切换按钮
        cardView: false,                    //是否显示详细视图
        detailView: false,                   //是否显示父子表
        columns: tbColumns,
        onPageChange: function (number, size) {
            m_pagerow = (number - 1) * size;
        }
    });
};`

**Comment by wenzhixin** [comment]
你好，测试了没有出现该问题，不知道你是否解决了问题。
