### ISSUE TITLE
formatter与x-editable 冲突

### ISSUE THREAD

**Issue by q349980363** [wenzhixin/bootstrap-table#3840]
data-editable="true"
之前formatter正常
data-editable="true"之后抛错

**Comment by q349980363** [comment]
![image](https://user-images.githubusercontent.com/4111244/41219714-c6747462-6d91-11e8-96fc-715e03209301.png)

**Comment by q349980363** [comment]
修复方式

**Comment by mdjaman** [comment]
Any update! Looking for same feature?

**Comment by wenzhixin** [comment]
Duplicate of #3320
在#3320问题中进行统一处理
