### ISSUE TITLE
Issues with bootstrap-table mobile

### ISSUE THREAD

**Issue by dl200010** [wenzhixin/bootstrap-table#3842]
I am using bootstrap-table v 1.11.1
I am also using bootstrap-table-mobile extention.
I have a large table (100+ data fields) and any time the window resizes ALL fields are reset. I disable mobile responsive and it works just fine, except the lack of mobile card view.
I have even tried to update to version 1.12.1, but I have the same issue.
The problem is my users are going to have this forum filled out with hundreds of fields and accidentally cause the phone to change orientation and wipe out all the fields. Is there a way to fix this? Some setting that I am missing?

**Comment by UtechtDustin** [comment]
Could you provide us an example ?

**Comment by dl200010** [comment]
Set up a bootstrap table, using JSON and loading the JSON on page load. With a bunch of input fields inside it. Check some fields and put in some text. Whatever is there change it. Resize the window. All fields reset to what they where when the page loaded. It is that simple. Even without using paging, it does this.

I am willing to help you with this, but as of this moment I am no longer working on that website where I saw the issue and no longer using Bootstrap Tables. Nothing wrong with it, I just changed jobs.

**Comment by UtechtDustin** [comment]
oh okay i understand.
This is not a bug then, its because we have to rerender the table if the device was rotated.
So its more an issue caused by the user, the user could lock the roation of the phone.

Consider to implement this @wenzhixin @djhvscf, but im not sure if it is worth (because of the uses/performance).

**Comment by dl200010** [comment]
Well, users are going to rotate, and telling them to lock rotation is a effort in futility. I would not ask them to.  Thanks anyways.

**Comment by wenzhixin** [comment]
You need to save the input value when changing it: https://live.bootstrap-table.com/code/wenzhixin/75. It can solve your problem.
