### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by gmauriello** [wenzhixin/bootstrap-table#3843]
Hi, how can I implement the Infinite scroll feature? I want that the page loads data when the scroll reaches the bottom of the page. Thanks a lot

**Comment by djhvscf** [comment]
The virtual scroll is implemented.

**Comment by ChaosEngine** [comment]
Is there a possibility to implement such infinite virtual scroll with server load on demand?
Like onBodyScroll with checking hitting bottom and loading more data on demand?

**Comment by ChaosEngine** [comment]
I was able to achieve the desired effect with the following snippets:

```
<div class="container-fluid">
	<table id="table"
		   data-unique-id="Key"
		   data-classes="table table-sm table-hover table-striped"
		   data-toggle="table"
		   data-side-pagination="server"
		   data-url="Load"
		   data-query-params="extraServerParams"
		   data-pagination="true"
		   data-pagination-use-intermediate="true"
		   data-show-refresh="true"
		   data-search="true"
		   data-toolbar="#toolbar"
		   data-icons-prefix="fa"
		   data-page-size="50"
		   data-page-list="[50,500,2000,10000]"
		   data-height="600"
		   >
		<thead>
			<tr>
				<th data-field="Key" data-sortable="true" data-halign="center" data-align="center">Key</th>
				<th data-field="HashMD5" data-sortable="true">HashMD5</th>
				<th data-field="HashSHA256" data-sortable="true">HashSHA256</th>
				<th data-field="Validate" data-sortable="false" data-halign="center" data-align="center" data-formatter="validateFormatter">Validate</th>
			</tr>
		</thead>
	</table>
</div>
```

```javascript
<script type="module" src="~/src/bootstrap-table.js"></script>

<script type="text/javascript">
var _startTime = null;
var _refreshClicked = "2";

function validateFormatter(value, row) {
	return (row.HashMD5 == null || row.HashSHA256 == null) ? ''
		: '<button class="btn btn-success btn-sm" title="Validate" value="Validate" onclick="clientValidate(this)">Validate</button>';
}

function extraServerParams(params) {
	_startTime = new Date().getTime();
	params.ExtraParam = _refreshClicked;
	_refreshClicked = "2";
	$('#spTimeToLoad').text('Loading...');
	return params;
}

function getId(element) {
	let result = $(element).closest('tr').data('uniqueid');
	return result;
}

$(document).ready(function () {
	const table = $('#table');
	let lastScroll = false;
	
	$('#exampleModal').on('show.bs.modal', function (event) {
		let tr = table.find('tr.highlight');
		let id = getId(tr);
		let msg = (id === undefined) ? 'No row selected' : 'Country code : ' + id;
		
		let modal = $(this);
		modal.find('.modal-body').text(msg);
	})

	$("button[name='refresh']").bindFirst('click', function (event) {
		_refreshClicked = "1";
	});
	table.on('refresh.bs.table', function (params) {
		//let opts = table.bootstrapTable('getOptions');
		params.ExtraParam = 1;
	});
	// register row-click event
	table.on('click-row.bs.table', function (element, row, tr) {
		tr.addClass('highlight').siblings().removeClass('highlight');
	});
	// load success
	table.on('load-success.bs.table', function (data) {
		$('#spTimeToLoad').text('Took ' + ((new Date().getTime() - _startTime) + 'ms!'));

		lastScroll = false;
		setTimeout(function() {
			//console.log('event bind');
			$('.fixed-table-body').scrollTop(2);
			
			$('.fixed-table-body').bind('scroll', function(event) {
				//console.log('scroll = ' + $('.fixed-table-body').scrollTop());

				if (lastScroll && $(this).scrollTop() + $(this).innerHeight() >= $(this)[0].scrollHeight)
				{
					console.log('end reached -> nextPage');
					lastScroll = true;
					table.bootstrapTable('nextPage');
					$(this).unbind('scroll');
				}
				else if (lastScroll && $(this).scrollTop() <= 0)
				{
					console.log('top reached <- prevPage');
					lastScroll = true;
					table.bootstrapTable('prevPage');
					$(this).unbind('scroll');
				}
				else
				{
					lastScroll = true;
				}
			});
		}, 0);
	});
	// load error
	table.on('load-error.bs.table', function (status, res) {
		$('#spTimeToLoad').text('error!');
	});
});
</script>
```

**Comment by UtechtDustin** [comment]
Its not working for me @ChaosEngine

**Comment by ChaosEngine** [comment]
> Its not working for me @ChaosEngine

Demo server? I didn't do any _jsfiddle_ example 'coz this demo relies mostly on server side pagination.

**Comment by UtechtDustin** [comment]
Yes your demo dont work for me, also please submit an Pullrequest please.

**Comment by ChaosEngine** [comment]
no need. Current implementation of `bootstrap-table` is sufficient enough. Possible informational improvement might be server side pagination example basing on http://dev.bootstrap-table.com/examples/#welcomes/large-data.html

**Comment by Friends4U** [comment]
> I was able to achieve the desired effect with the following snippets:
> 
> ```
> <div class="container-fluid">
> 	<table id="table"
> 		   data-unique-id="Key"
> 		   data-classes="table table-sm table-hover table-striped"
> 		   data-toggle="table"
> 		   data-side-pagination="server"
> 		   data-url="Load"
> 		   data-query-params="extraServerParams"
> 		   data-pagination="true"
> 		   data-pagination-use-intermediate="true"
> 		   data-show-refresh="true"
> 		   data-search="true"
> 		   data-toolbar="#toolbar"
> 		   data-icons-prefix="fa"
> 		   data-page-size="50"
> 		   data-page-list="[50,500,2000,10000]"
> 		   data-height="600"
> 		   >
> 		<thead>
> 			<tr>
> 				<th data-field="Key" data-sortable="true" data-halign="center" data-align="center">Key</th>
> 				<th data-field="HashMD5" data-sortable="true">HashMD5</th>
> 				<th data-field="HashSHA256" data-sortable="true">HashSHA256</th>
> 				<th data-field="Validate" data-sortable="false" data-halign="center" data-align="center" data-formatter="validateFormatter">Validate</th>
> 			</tr>
> 		</thead>
> 	</table>
> </div>
> ```
> 
> ```js
> <script type="module" src="~/src/bootstrap-table.js"></script>
> 
> <script type="text/javascript">
> var _startTime = null;
> var _refreshClicked = "2";
> 
> function validateFormatter(value, row) {
> 	return (row.HashMD5 == null || row.HashSHA256 == null) ? ''
> 		: '<button class="btn btn-success btn-sm" title="Validate" value="Validate" onclick="clientValidate(this)">Validate</button>';
> }
> 
> function extraServerParams(params) {
> 	_startTime = new Date().getTime();
> 	params.ExtraParam = _refreshClicked;
> 	_refreshClicked = "2";
> 	$('#spTimeToLoad').text('Loading...');
> 	return params;
> }
> 
> function getId(element) {
> 	let result = $(element).closest('tr').data('uniqueid');
> 	return result;
> }
> 
> $(document).ready(function () {
> 	const table = $('#table');
> 	let lastScroll = false;
> 	
> 	$('#exampleModal').on('show.bs.modal', function (event) {
> 		let tr = table.find('tr.highlight');
> 		let id = getId(tr);
> 		let msg = (id === undefined) ? 'No row selected' : 'Country code : ' + id;
> 		
> 		let modal = $(this);
> 		modal.find('.modal-body').text(msg);
> 	})
> 
> 	$("button[name='refresh']").bindFirst('click', function (event) {
> 		_refreshClicked = "1";
> 	});
> 	table.on('refresh.bs.table', function (params) {
> 		//let opts = table.bootstrapTable('getOptions');
> 		params.ExtraParam = 1;
> 	});
> 	// register row-click event
> 	table.on('click-row.bs.table', function (element, row, tr) {
> 		tr.addClass('highlight').siblings().removeClass('highlight');
> 	});
> 	// load success
> 	table.on('load-success.bs.table', function (data) {
> 		$('#spTimeToLoad').text('Took ' + ((new Date().getTime() - _startTime) + 'ms!'));
> 
> 		lastScroll = false;
> 		setTimeout(function() {
> 			//console.log('event bind');
> 			$('.fixed-table-body').scrollTop(2);
> 			
> 			$('.fixed-table-body').bind('scroll', function(event) {
> 				//console.log('scroll = ' + $('.fixed-table-body').scrollTop());
> 
> 				if (lastScroll && $(this).scrollTop() + $(this).innerHeight() >= $(this)[0].scrollHeight)
> 				{
> 					console.log('end reached -> nextPage');
> 					lastScroll = true;
> 					table.bootstrapTable('nextPage');
> 					$(this).unbind('scroll');
> 				}
> 				else if (lastScroll && $(this).scrollTop() <= 0)
> 				{
> 					console.log('top reached <- prevPage');
> 					lastScroll = true;
> 					table.bootstrapTable('prevPage');
> 					$(this).unbind('scroll');
> 				}
> 				else
> 				{
> 					lastScroll = true;
> 				}
> 			});
> 		}, 0);
> 	});
> 	// load error
> 	table.on('load-error.bs.table', function (status, res) {
> 		$('#spTimeToLoad').text('error!');
> 	});
> });
> </script>
> ```
> 
> I've added additional code that switches page next/prev when scroll reaches bottom and top of scroll area
> 
> Demo page can be observed here: https://haos.hopto.org/dotnet/VirtualScroll/

Lol! Now try to see the last record of a page :)

**Comment by hase123** [comment]
@ChaosEngine  can you please share above code for angular

**Comment by ChaosEngine** [comment]
> @ChaosEngine can you please share above code for angular

I never did any angular piece there.
