### ISSUE TITLE
Selected rows are not unselected before first search.

### ISSUE THREAD

**Issue by felix-the-real-cat** [wenzhixin/bootstrap-table#3844]
Hi, thanks for bootstrap-table !

Here is my bug report: 

Take a table with checkboxes (i.e. a column with data-checkbox="true").
Check one row. 
Call the getSelections or getAllSelections function and you get the correct data.
Search for something that makes the selected row disappear (hide). 
Call the getSelections or getAllSelections function again. You will get the same result.
The expected result was to get an empty array.

The problem exists on the example page http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getAllSelections.html
Check row 1 (ID = 1). Click the getAllSelections button, search for '2'. Row 1 disappears. If you click on the button, you don't get an empty array.

EDIT 1:
my workaround is to insert the following code at line 1324:
`if (!this.options.maintainSelected) {
      this.resetRows();
 }`

**Comment by djhvscf** [comment]
Hi, could you please create a PR for this?

**Comment by avnh** [comment]
Hi, i have another problem with selected row.
I want to keep selected rows being selected after search make them disappear.
ie:
- Take a table with checkbox
- select some rows
- do some search that make selected rows disappear
- clear search that make my selected rows appear again
-> I expect to keep my selected rows being selected

**Comment by UtechtDustin** [comment]
@avnh 
The table option [maintainSelected](https://bootstrap-table.com/docs/api/table-options/#maintainselected) should help you.

**Comment by avnh** [comment]
@UtechtDustin thank you, it was my fault when reading docs.
