### ISSUE TITLE
Export function's performance diverges on different version of importe jQuery libraries

### ISSUE THREAD

**Issue by yliu-xjtu** [wenzhixin/bootstrap-table#3845]
Thanks for developing bootstrap-table!

Here is my bug report:

When exporting large amount of data (e.g., exporting to "CSV" format under Chrome/Win10), the waiting time needed is very different after introducing different versions of jQuery.

This is a simple test case (table size: 1378 rows by 5 columns):
[jsfiddle](http://jsfiddle.net/yliusg/g0p7ryu2/) 

When you choose the jQuery v2.x.x.x (2.1.2 and 2.2.4), the waiting time is around 3s.
![image](https://user-images.githubusercontent.com/9999317/41403701-14a67474-6ff8-11e8-8b66-b55946ab4926.png)

When you choose the jQuery v3.x.x.x, the waiting time is around 12s.
![image](https://user-images.githubusercontent.com/9999317/41404176-1dada6c2-6ff9-11e8-8aee-1690d6c568dc.png)

In the local test case, I also find out that not all jQuery V2.x.x. works fast. For example, jQuery v2.2.1 also takes around 11s.

So what's the reason of this strange phenomenon? Dose some key function changes back and forth?

**Comment by yliu-xjtu** [comment]
I have just found out that when the rows is bigger, the export function cannot work. The web browser will stuck. So I give up using the export function provided in bootstrap. Since I can get the `json` data from web server (maybe already got at the client side), and what I need is just exporting all the data to `csv` format at the client side. My solution is based on this reference:
[Using javascript to download file as a.csv file](https://stackoverflow.com/a/48897777/6598755)

Maybe who find it too slow when exporting large tables may find it work.

My suggestion is that:
If users like me just want to exporting **all** the data to `json` or `csv` format, a quicker method could be provided.

**Comment by djhvscf** [comment]
Thanks @yliu-xjtu . This will labeled as "Feature"

**Comment by UtechtDustin** [comment]
@djhvscf 
What do you think how should we implement that ?
Add an new option show a new button to export all data ? or use the old one with a seperator ?

**Comment by wenzhixin** [comment]
In my opinion, if the exported data is too large, it is recommended to export it on the server side instead of through the client side.

**Comment by wenzhixin** [comment]
ref #2127, let's close this issue.
