### ISSUE TITLE
1.12.1版本工具栏布局错乱

### ISSUE THREAD

**Issue by GodLiang** [wenzhixin/bootstrap-table#3848]
使用1.12.1版本，工具栏布局有问题。搜索栏会单独占一行，显示列，切换视图，全屏会在左边，加float right无效，同时切换视图还没有图标。

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
请使用 1.13.0

**Comment by GodLiang** [comment]
thanks
