### ISSUE TITLE
Checkbox value changes when using data-show-columns

### ISSUE THREAD

**Issue by caliman** [wenzhixin/bootstrap-table#385]
When I use data-show-columns and data-id-field the checkbox value is set to the value of the field specified which is good. But after adding or removing columns the checked values becomes true instead of the field value making it hard to find selected rows for ajax post. Or is there any better way to get selected rows then taking from checkbox?

**Comment by caliman** [comment]
ok I now create a separate column for id that is not visible and one column only for the checkbox. Works good so you can remove this issue. Thanks.

**Comment by wenzhixin** [comment]
Close it.
