### ISSUE TITLE
How to make column field more flexible?

### ISSUE THREAD

**Issue by Hacksaurus** [wenzhixin/bootstrap-table#3851]
This is currently how I set the columns field when I create a Boostrap Table:
```
[{
		checkbox: true
	}, {
		field: "ID",
		title: "ID",
		sortable: true
	}, {
		field: "project",
		title: "Project",
		editable: {
			title: "Project",
			placeholder: "Project"
		}
	}, {
		field: "owner",
		title: "Owner",
		editable: {
			title: "Owner",
			placeholder: "Owner"
		}
	}, {
		field: "name_1",
		title: "Name #1",
		editable: {
			title: "Name #1",
			placeholder: "Name #1"
		}
	}, {
		field: "name_2",
		title: "Name #2",
		editable: {
			title: "Name #2",
			placeholder: "Name #2"
		}
	}, {
		field: "status",
		title: "Status",
		editable: {
			title: "Status",
			type: "select",
			source: [
				{ value: 0, text: "Not Selected" },
				{ value: 1, text: "Not Started" },
				{ value: 2, text: "WIP" },
				{ value: 3, text: "Completed" }
			],
			display: function(value, sourceData) {
				var colors     = { 0: "Gray", 1: "#E67C73", 2: "#F6B86B", 3: "#57BB8A" };
				var status_ele = $.grep(sourceData, function(ele){ return ele.value == value; });
				
				$(this).text(status_ele[0].text).css("color", colors[value]);
			},
			showbuttons: false
		}
	}]
```
I want to be able to dynamically add columns. I get my data from a my sql server, so my design plan is actually have this array stored in my sql server. But now the question is how? in my status field I have this function that I can't really turn into a json format...

Thanks for any help!

**Comment by jimgit** [comment]
If you create a .net object that "looks" like the json arrray - you should be able to use json serialization (newtonsoft).  You might even want to take a complex json like you have and convert that to a .net object .  [See this page - paste your column definition (must be valid json) ](http://json2csharp.com/)

**Comment by Hacksaurus** [comment]
@jimgit You see the problem is that there is no way that I can create valid json from this, again the function here breaks things to create things colors makes this a lot more complicated!

**Comment by jimgit** [comment]
Yes - it can get quite complex.  I would separate the data , formatting ,etc into separate callable custom written (via server side) javascript functions so your initial large json could be as small (and simple) as possible.

**Comment by jimgit** [comment]
Maybe you can explain why you need to do this - someone may know a better way.

**Comment by Hacksaurus** [comment]
@jimgit Sure, I'll explain my project:
![screenshot_2018-06-18_17-10-25](https://user-images.githubusercontent.com/24832107/41568447-8fff94aa-731a-11e8-8dec-e04a0b2b5ad2.png)
Essentially I'm creating a website where people can edit certain cells and add/delete rows. But I want to be able to have it so that it can be where people can add columns. The idea is that when u add a column  the user can have the option to add a range of different column types (Text input, list of items, etc.) and give a name to that column (and the website will auto create a SQL friendly name). From the way that bootstrap creates tables, u need to manually decide how each column will be styled, so this proves to be difficult! I hope this clears some confusion up.

**Comment by jimgit** [comment]
Yes - when you modify the schema on the fly it gets very complex.   Another option would be to abstract the data to generic column/data (you add "rows" in the data definition table when a user adds a column.  Does this have to be in sql? [ Maybe a json storage method might be better](https://www.sisense.com/blog/postgres-vs-mongodb-for-storing-json-data/)?

**Comment by Hacksaurus** [comment]
I'll try switching to a JSON storage method and see how that goes, for now I'll keep this open... Thank you for the help...

**Comment by Hacksaurus** [comment]
I've gotten a lot of progress done with mongodb! But I do have one main issue before I start completing my main task.

I've completely revamped my code. Instead of having php, I have node.js as my server side language. I've switched to mongodb as I've previously mentioned, and rewritten parts of my client side javascript. This is what my website currently looks like:
![screenshot_2018-06-21_22-31-38](https://user-images.githubusercontent.com/24832107/41759427-5328dbf0-75a3-11e8-9edb-061851beb391.png)
As you see the `Status` column data is not colored, as my previous website did. Even though I was able to store the function, but only as a string, meaning it does not mean a whole much in client side.
```
> show tables
projects
projects_columns
> db.projects.find()
{ "_id" : ObjectId("5b2bf4da13f57a61d95e1f90"), "Project" : "Project Alpha", "Owner" : "Bobby", "Name #1" : "Sandra", "Name #2" : "Smith", "Status" : "Not Started" }
{ "_id" : ObjectId("5b2bf4db13f57a61d95e1f91"), "Project" : "Project Beta", "Owner" : "James", "Name #1" : "Samantha", "Name #2" : "Sarah", "Status" : "WIP" }
{ "_id" : ObjectId("5b2bf4db13f57a61d95e1f92"), "Project" : "Project Gamma", "Owner" : "Bobby", "Name #1" : "Rahul", "Name #2" : "Vick", "Status" : "Completed" }
{ "_id" : ObjectId("5b2bf56fe62b5879f6a0b4d2"), "Project" : "Project Delta", "Owner" : "Mei", "Name #1" : "Blake", "Name #2" : "Tatum", "Status" : "WIP" }
{ "_id" : ObjectId("5b2bf56fe62b5879f6a0b4d3"), "Project" : "Project Epsilon", "Owner" : "Mei", "Name #1" : "Amanda", "Name #2" : "Eric", "Status" : "WIP" }
{ "_id" : ObjectId("5b2bf56fe62b5879f6a0b4d4"), "Project" : "Project Zeta", "Owner" : "Bobby", "Name #1" : "Bruce", "Name #2" : "Dave", "Status" : "Completed" }
{ "_id" : ObjectId("5b2bf570e62b5879f6a0b4d5"), "Project" : "Project Eta", "Owner" : "James", "Name #1" : "Luke", "Name #2" : "Aaron", "Status" : "WIP" }
{ "_id" : ObjectId("5b2c86a07de4c9074630bf80"), "Project" : "", "Owner" : "", "Name #1" : "", "Name #2" : "", "Status" : "" }
{ "_id" : ObjectId("5b2c86a27de4c9074630bf81"), "Project" : "", "Owner" : "", "Name #1" : "", "Name #2" : "", "Status" : "" }
{ "_id" : ObjectId("5b2c87aaedaea931c069396a"), "Project" : "", "Owner" : "", "Name #1" : "", "Name #2" : "", "Status" : "" }
> db.projects_columns.find()
{ "_id" : "5b28866a13311e44a82e4b8d", "checkbox" : true }
{ "_id" : "5b28866a13311e44a82e4b8e", "field" : "_id", "title" : "ID", "sortable" : true }
{ "_id" : "5b28866a13311e44a82e4b8f", "field" : "Project", "title" : "Project", "editable" : { "title" : "Project", "placeholder" : "Project" } }
{ "_id" : "5b28866a13311e44a82e4b90", "field" : "Owner", "title" : "Owner", "editable" : { "title" : "Owner", "placeholder" : "Owner" } }
{ "_id" : "5b28866a13311e44a82e4b91", "field" : "Name #1", "title" : "Name #1", "editable" : { "title" : "Name #1", "placeholder" : "Name #1" } }
{ "_id" : "5b28866a13311e44a82e4b92", "field" : "Name #2", "title" : "Name #2", "editable" : { "title" : "Name #2", "placeholder" : "Name #2" } }
{ "_id" : "5b28866a13311e44a82e4b93", "field" : "Status", "title" : "Status", "editable" : { "title" : "Status", "type" : "select", "source" : [ { "value" : "", "text" : "Not Selected" }, { "value" : "Not Started", "text" : "Not Started" }, { "value" : "WIP", "text" : "WIP" }, { "value" : "Completed", "text" : "Completed" } ], "display" : "function (value, sourceData) { var colors     = { 0: 'Gray', 1: '#E67C73', 2: '#F6B86B', 3: '#57BB8A' }; var status_ele = $.grep(sourceData, function(ele){ return ele.value == value; });  $(this).text(status_ele[0].text).css('color', colors[value]); }", "showbuttons" : false } }
``` 
In my database I have 2 tables, one for projects, and another for columns data. I first get the data from columns and then create my database with the other data. I just need a way to evaluate the function in the string, but I am lacking ideas.

**Comment by jimgit** [comment]
Maybe you could use the [javascript eval function](https://www.w3schools.com/Jsref/jsref_eval.asp) and treat the function as "data".

**Comment by Hacksaurus** [comment]
@jimgit That's the idea here, but the real question is... how exactly do I do that? I've searched up this kind of issue and so far I'm getting really no results...

**Comment by Hacksaurus** [comment]
My idea has.... semi worked @jimgit This is what my column data looks like:
```
{ "_id" : "5b28866a13311e44a82e4b8d", "checkbox" : true }
{ "_id" : "5b28866a13311e44a82e4b8e", "field" : "_id", "title" : "ID", "sortable" : true }
{ "_id" : "5b28866a13311e44a82e4b8f", "field" : "Project", "title" : "Project", "editable" : { "title" : "Project", "placeholder" : "Project" } }
{ "_id" : "5b28866a13311e44a82e4b90", "field" : "Owner", "title" : "Owner", "editable" : { "title" : "Owner", "placeholder" : "Owner" } }
{ "_id" : "5b28866a13311e44a82e4b91", "field" : "Name #1", "title" : "Name #1", "editable" : { "title" : "Name #1", "placeholder" : "Name #1" } }
{ "_id" : "5b28866a13311e44a82e4b92", "field" : "Name #2", "title" : "Name #2", "editable" : { "title" : "Name #2", "placeholder" : "Name #2" } }
{ "_id" : "5b28866a13311e44a82e4b93", "field" : "Status", "title" : "Status", "editable" : { "title" : "Status", "type" : "select", "source" : [ { "value" : "", "text" : "Not Selected" }, { "value" : "Not Started", "text" : "Not Started" }, { "value" : "WIP", "text" : "WIP" }, { "value" : "Completed", "text" : "Completed" } ], "display" : "func_color", "showbuttons" : false } }
```
Instead of having my logic stored server side, I have moved it client side. And my client will replace that particular string with the actual function, BUT there is one problem. This is currently the function for that display field.
```js
   66 
   67 //Func Color
   68 function func_color(value, sourceData) {
   69 ➡   var colors     = { 0: "Gray", 1: "#E67C73", 2: "#F6B86B", 3: "#57BB8A" };
   70 ➡   var status_ele = $.grep(sourceData, function(ele){ return ele.value == value; });
   71 ➡   
   72 ➡   $(this).text(status_ele[0].text).css("color", colors[value]);
   73 }
```
It uses the `this` keyword which means this function was meant for a local context! D: How to fix...

**Comment by jimgit** [comment]
If there was a way you could setup a jsfiddle it would be helpful.  You can serve the json from myjson.com

**Comment by Hacksaurus** [comment]
Ah I fixed it, the problem wasn't about `this` is my colors array!

**Comment by djhvscf** [comment]
Looks like this is resolved. If the issue still persists, please reopen it.
