### ISSUE TITLE
How to use with CodeIgniter URL scheme?

### ISSUE THREAD

**Issue by igittigitt** [wenzhixin/bootstrap-table#3852]
I use bootstrap-table with CodeIgniter 4. There is a special URL scheme, which incorporates the request parameters into the URL, e.g. http://domain/host/controller/method/param1/param2/...
bootstrap-table always sends GET-request in the classic form, using ampersant and questionmark to separate params.

**Comment by djhvscf** [comment]
You can use 'method' table option and set it to; 'post'
