### ISSUE TITLE
bootstrap-table-group-by Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by joinquan** [wenzhixin/bootstrap-table#3853]
it happens when I change sidePagination from 'client' to 'server', it works  with client.I  don't know how to fix it ,help me please .

the main code like this : 
<table class="table-hove table-bordered table-striped table"
                                       data-toolbar=".toolbar"
                                       data-pagination="true"
                                       data-maintain-selected="true"
                                       data-group-by="true"
                                       data-group-by-field="group"
                                       data-click-to-select="true" id="module" >
 </table>
$('#module').bootstrapTable({
            url: urls, 
            method: 'get', 
            toolbar: '', 
            striped: true, 
            pagination: true,
            sortable: true,
            pageSize: 50,
            pageList: [10, 25, 50, 100, "All"],
            queryParams: queryParams, 
            sidePagination: "server", 
            search: true,
            detailView:true,
            showColumns: true,
            showExport: true,                     
            exportDataType: "selected",              //basic', 'all', 'selected'.
            detailFormatter: function(index, row) {
                return '描述：' + row.remark ;
            },
            
            columns: [{
                field: 'name',
                title: '名称',
                sortable: true,
                width : '10px'

            },{
                field: 'property',
                title: '属性编码',
                sortable: true

            },{
                field: 'value',
                title: '值',
                sortable: true,
                formatter: 'valueFormatter',
                width : '20px'

            },{
                field: 'history',
                title: '上次修改值',
                width : '20px',
                visible: false,

            },{
                field: 'group',
                title: '分组',
                {#sortable: true,#}
                visible: false,

            },{
                field: 'update_time',
                title: '更新时间',
                sortable: true,
                width : '20px',

            },{
                field: 'remark',
                title: '描述',
                visible: false

            }]
        });
        });

**Comment by joinquan** [comment]
`                                <table class="table-hove table-bordered table-striped table"
                                       data-toolbar=".toolbar"
                                       data-pagination="true"
                                       data-maintain-selected="true"
                                       data-group-by="true"
                                       data-group-by-field="group"
                                       data-click-to-select="true" id="module" >
                                </table>
                            </div>`

`           $('#module').bootstrapTable({
            url: urls, //请求后台的URL（*）
            method: 'get', //请求方式（*）
            toolbar: '', //工具按钮用哪个容器
            striped: true, //是否显示行间隔色
            pagination: true,
            sortable: true,
            pageSize: 50,
            pageList: [10, 25, 50, 100, "All"],
            {#queryParams: queryParams,   ///传递参数（*）#}
            search: true,
            detailView:true,
            showColumns: true, //是否显示所有的列
            showExport: true,                     //是否显示导出
            exportDataType: "selected",              //basic', 'all', 'selected'.
            detailFormatter: function(index, row) {
                return '描述：' + row.remark ;
            },
            sidePagination: "server", //分页方式：client客户端分页，server服务端分页（*）
            columns: [{
                field: 'name',
                title: '名称',
                sortable: true,
                width : '10px'

            },{
                field: 'property',
                title: '属性编码',
                sortable: true

            },{
                field: 'value',
                title: '值',
                sortable: true,
                formatter: 'valueFormatter',
                width : '20px'

            },{
                field: 'history',
                title: '上次修改值',
                width : '20px',
                visible: false,


            },{
                field: 'group',
                title: '分组',
                {#sortable: true,#}
                visible: false,

            },{
                field: 'update_time',
                title: '更新时间',
                sortable: true,
                width : '20px',

            },{
                field: 'remark',
                title: '描述',

                visible: false

            }]
        });
        });`

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!

**Comment by feibaliang** [comment]
I have same problem ,I think it is because `sidePagination: "server"`, do not work with group by,am I right?

**Comment by UtechtDustin** [comment]
@feibaliang 
Please provide us an example(jsfiddle).

**Comment by feibaliang** [comment]
I debug in bootstrap-table and  find these 
`  initData (data, type) {
    if (type === 'append') {
      this.options.data = this.options.data.concat(data)
    } else if (type === 'prepend') {
      this.options.data = [].concat(data).concat(this.options.data)
    } else {
      this.options.data = data || this.options.data
    }

    this.data = this.options.data

    if (this.options.sidePagination === 'server') {
      return
    }
    this.initSort()
  }`
so `this.options.sidePagination === 'server'`  initData will return ,and initSort will not be called.but if initSort does't be called group-by will not init normally ,am I right?

**Comment by feibaliang** [comment]
I debug in bootstrap-table source code and  find these 
```
 initData (data, type) {
    if (type === 'append') {
      this.options.data = this.options.data.concat(data)
    } else if (type === 'prepend') {
      this.options.data = [].concat(data).concat(this.options.data)
    } else {
      this.options.data = data || this.options.data
    }
    this.data = this.options.data
    if (this.options.sidePagination === 'server') {
      return
    }
    this.initSort()
  }
```
so `this.options.sidePagination === 'server'`  initData will return ,and initSort will not be called.but if initSort does't be called group-by will not init normally ,am I right?

**Comment by UtechtDustin** [comment]
The group by extension will be merged/rewritten, this issue will be checked in #4413.
