### ISSUE TITLE
使用中遇到的问题

### ISSUE THREAD

**Issue by ryukasenn** [wenzhixin/bootstrap-table#3855]
第一次用Github交流,好激动.
说一下碰到的问题:
1.源码2137行,这里后台拿到数据后,load方法中的参数我打过log(res),发现不是json,只好在load方法中手动加入了json.parse(data),结果可行.
res = calculateObjectValue(that.options, that.options.responseHandler, [res], res);
that.load(res);
2.服务器端分页,POST方式提交时
2.1,开始的时候,个人习惯,都是用大写的POST,一直不成功,后来改了post
2.2,还有一个历史遗留问题,我的ajax提交时,当加入了dataType和contentType两个参数时,后台就是收不到post的参数,没办法加了两句在ajax提交之前加了delete request.dataType;delete request.contentType;两句代码,果然成功

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
这个问题在 `responseHandler` 中处理下即可。
