### ISSUE TITLE
filtering issue for null and undefined column values on filter-control v2.1.3 extension 

### ISSUE THREAD

**Issue by umurturetken** [wenzhixin/bootstrap-table#3856]

**Comment by umurturetken** [comment]
I solved my problem with below code blocks;

//Check partial column filter
        that.data = fp ? $.grep(that.data, function (item, i) {
            for (var key in fp) {
                var thisColumn = that.columns[that.fieldsColumnsIndex[key]];
                var fval = fp[key].toLowerCase();
                var value = item[key];

                // Fix #142: search use formated data
                if (thisColumn && thisColumn.searchFormatter) {
                    value = $.fn.bootstrapTable.utils.calculateObjectValue(that.header,
                        that.header.formatters[$.inArray(key, that.header.fields)],
                        [value, item, i], value);
                }

                if ($.inArray(key, that.header.fields) !== -1) {
                    if (typeof value === 'string' || typeof value === 'number') {
                        if (thisColumn.filterStrictSearch) {
                            if (value.toString().toLowerCase() !== fval.toString().toLowerCase()) {
                                return false;
                            }
                        } else if (thisColumn.filterStartsWithSearch) {
                            if ((value + '').toLowerCase().indexOf(fval) !== 0) {
                                return false;
                            }
                        } else {
                            if ((value + '').toLowerCase().indexOf(fval) === -1) {
                                return false;
                            }
                        }
                    }
                    // Fix #142: filter for undefined or null column values
                    else if (value === null || value === undefined) {
                        return false;
                    }
                }
            }

            return true;
        }) : that.data;

**Comment by djhvscf** [comment]
Hi @umurturetken could you create a PR with this fix?
