### ISSUE TITLE
getRowByUniqueId and removeByUniqueID are not working

### ISSUE THREAD

**Issue by arapocket** [wenzhixin/bootstrap-table#3857]
I can see that the **tr** has the attribute **data-unique-id** with a correct value. Even when hardcording the IDs, such as,
`$('#table').bootstrapTable('removeByUniqueId', 46002);`

nothing happens! However, the checkbox functions are working fine!

**getRowByUniqueID** gives me null even though I can see that the **data-unique-id** attribute is set.

**Comment by arapocket** [comment]
The [documentation](http://bootstrap-table.wenzhixin.net.cn/documentation/) seems to have an error. It lists the attribute as **data-unique-id** when it should be **data-uniqueid** but still nothing is working for me.

**Comment by jimgit** [comment]
[See this](https://github.com/wenzhixin/bootstrap-table/issues/3834)

**Comment by arapocket** [comment]
@jimgit Thank you. I got it working using your reference. Previously, I was trying to render the table rows using pug templating syntax. I guess it can only be done with a function call of append.
