### ISSUE TITLE
How to override default queryParam variables ?

### ISSUE THREAD

**Issue by sanjesh** [wenzhixin/bootstrap-table#386]
The server api's params are different than BT query params
Is there a way to rename BT queryParams ?

BT Query param | Server Side param
------------ | -------------
pageNumber | page
pageSize | pageLimit
searchText | searchRecord

**Comment by thinksea** [comment]
up up

**Comment by wenzhixin** [comment]
Hi, the default of queryParamsType option is 'limit', so,

queryParamsType(limit) | queryParamsType('') | Server Side param
--------------- | -------------- | -------------
limit |pageNumber | page
offset | pageSize | pageLimit
search | searchText | searchRecord
sort | sortName | sortName
order | sortOrder | 


queryParamsType: 'limit'
```js
queryParams: function (params) {
    limit: params.pageSize,
    offset: params.pageSize * (params.pageNumber - 1),
    search: params.searchText,
    sort: params.sortName,
    order: params.sortOrder
}
```

queryParamsType: ''
```js
queryParams: function (params) {
    pageSize: this.options.pageSize,
    pageNumber: this.options.pageNumber,
    searchText: this.searchText,
    sortName: this.options.sortName,
    sortOrder: this.options.sortOrder
}

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/386.html

**Comment by prakashcse** [comment]
how to pass additional parameters to boostrapTable via javascript, i want to pass startdate and enddate.

**Comment by ilyatuu** [comment]
Dear Wenzhixin,
How to get values for queryParams. For example, in my code below, I keep getting null value for p.pageSize and other qeryParams values. My table is defined in the html as <table id="table"></table>

$("#table").bootstrapTable({
				url: "../View",
				method: "post",
				sidePagination: "server",
				contentType: 'application/x-www-form-urlencoded',
				queryParams: function(p){
					return{
						limit : p.pageSize,
						offset: p.pageSize * (p.pageNumber - 1),
						search: p.searchText,
						sort:	p.sortName,
						order:  p.sortOrder
					}
				},
				showColumns: true,
				search: true,
				pagination: true,
				pageSize: 5,
                pageList: [5, 10, 25, 50, 100],
                showRefresh: true,
				columns: [{
			    	field: 'REGION',
			    	title: 'Region'
			    }]
			})
		}

**Comment by JackZhouMine** [comment]
> how to pass additional parameters to boostrapTable via javascript, i want to pass startdate and enddate.

Did you get any solutions?

**Comment by UtechtDustin** [comment]
@JackZhouMine 
Please checkout the [example](https://examples.bootstrap-table.com/index.html#issues/386.html).
