### ISSUE TITLE
无法用bootstrapTable('load', data)更新表格

### ISSUE THREAD

**Issue by kq7** [wenzhixin/bootstrap-table#3861]
已经在后台initialize了一个table

$("#mytable").bootstrapTable({
            toolbar: '#toolbar',
            striped: true,
            datatype: "json",
            url: "/datatable",
            responseHandler:response,
            //格式化
            async: 'true',
            columns: [
            [{"colspan": 5, "allign": "center"}],
            [
            {"field": "{{title[0]}}", "title": "\{{title[0]}}"  },
            {"field": "{{title[1]}}", "title": "\{{title[1]}}"  },
            {"field": "{{title[2]}}", "title": "\{{title[2]}}"  },
            {"field": "{{title[3]}}", "title": "\{{title[3]}}"  },
            {"field": "op", "title": "操作", "formatter": "operation"}
            ]
            ]
        });

自定义了一个load button用来call load 

$("body").delegate(".load", "click", function(){
        $.ajax({
             url: "/overwritedata",
             dataType:"json",
             success : function(json) {
                $("#mytable").bootstrapTable('load', json);
                //json = Object {col4: "row1", col5: "row1", col2: "row1", col3: "row1", col1: "row1"}               
            }
        });
    });

**Comment by wenzhixin** [comment]
http://bootstrap-table-examples.wenzhixin.net.cn/#methods/load.html
