### ISSUE TITLE
Sorting a nested table propagates to parent

### ISSUE THREAD

**Issue by analytics-bootcamp** [wenzhixin/bootstrap-table#3862]
I defined a table with inside one of its cells, another table. 

If I try to sort this table, either the following happens:

-the child table column exists in the parent table:

Only the parent table column is sorted.

-the child table column does not exist in the parent table:

The child column is properly sorted and then an error is thrown for the parent table:
Uncaught TypeError: Cannot read property 'order' of undefined

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Falseee** [comment]
I close this issue because we got no response/example from you.
If you still need help pls reopen the issue and provide us a jsFiddle.

**Comment by RolandJosuran** [comment]
I think I came across the same issue. I have a HTML table and want to use the functionalities of Bootstrap-Table. There is another table (sub table) in the collapsible detail view. This is similar to [this example]( https://examples.bootstrap-table.com/#welcomes/sub-table.html) and works fine. The sub table in the example is sortable. And that‘s what I want too. However, when I click to sort the column of the sub table, an error is thrown and the detail view Closes at the second click. I made a [jsFiddle](https://jsfiddle.net/nkj7qxes/). Am I doing something wrong?

**Comment by wenzhixin** [comment]
@RolandJosuran In your case, you need to use [onExpandRow](https://bootstrap-table.com/docs/api/events/#onexpandrow) instead, because `detailFormatter` is only handle the result as html **String**. 

Working example: https://live.bootstrap-table.com/code/wenzhixin/592.

**Comment by RolandJosuran** [comment]
Great, thank you!
I would suppose this also solves the OPs problem.
