### ISSUE TITLE
bootstrap-table 排序图标不见

### ISSUE THREAD

**Issue by lei159130** [wenzhixin/bootstrap-table#3863]
服务端分页，js加载table，需要排序的字段添加了sortable : true,实现了排序，但是没有图标，怎么回事？
bootstrap-version:v3.3.6;
bootstrap-table-version:v1.9.0

已解决!bootstrap-table的v1.9.0版本css文件没有sortable both asc desc 的class,更新最新版本就有了排序图标

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?
