### ISSUE TITLE
Pagination Area Issue

### ISSUE THREAD

**Issue by Anatolii-B** [wenzhixin/bootstrap-table#3865]
I faced with issue, when i have more then 1 grid on page, and only one in the same time is active (others are on separate tabs on page), when i make another visible (click on tab) there is a bug - scroll bar overlaying pagination area (Number of rows etc.)
![image](https://user-images.githubusercontent.com/13980088/41960787-4e4eb078-79f9-11e8-8491-6ede1d62d026.png)

Is there any way to avoid this problem?

**Comment by jimgit** [comment]
Can you submit a jsfiddle demonstrating the problem?

**Comment by Anatolii-B** [comment]
Yes, sorry i was a bit wrong, problem reproduces when at the begining area with grid is hidden, and when we show it - footer with pagination area is overlapping data. It couse problem - when on page we have several tabs on page, and on that tabs are this grids. I found a temporary solution - each time when i made some tab with grid visible  - i call "resetView" method, is there any other way to fix it? Thanks

Steps to reproduce - 
- open link http://jsfiddle.net/2xar57hw/3/ 
- wait a few seconds, make result view window small
- click "Show" button and scroll edge scrollbar down 

![image](https://user-images.githubusercontent.com/13980088/42223344-3b1f816c-7ee0-11e8-8d64-264d75cd0523.png)

**Comment by djhvscf** [comment]
Please see this example: http://jsfiddle.net/djhvscf/2xar57hw/11/

I just added this method

```js
$('#showGridButton').click(function(){
  $('#gridContainer').css('display','block');
  $table.bootstrapTable('resetView');
});
