### ISSUE TITLE
Field property is undefined in formatter

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#3867]
I was looking to get the field name in `formatter` function to Concatenate the value with field name. But getting undefined.

https://jsfiddle.net/hb1faqad/15/

```
		function Concat(value, row, index, field) {
		 return field + ' is ' + value;
		};
```

**Comment by jimgit** [comment]
[See this jsfiddle](http://jsfiddle.net/jimkennelly/v39tarux/)

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Comment by lianyuteng** [comment]
sorry，Ask how to solve it？

**Comment by wenzhixin** [comment]
@lianyuteng https://bootstrap-table.com/docs/api/column-options/#formatter
The last parameter of the `formatter` column option is `field`.

**Comment by lianyuteng** [comment]
@wenzhixin 
![image](https://user-images.githubusercontent.com/20927567/58218847-27748180-7d3b-11e9-89c9-998fa8bdadf0.png)
But the document says that there are only three parameters, while there are four function parameters.

**Comment by lianyuteng** [comment]
The current version is 1.11.0

**Comment by wenzhixin** [comment]
Please update to the latest version?
