### ISSUE TITLE
Add event to column, the data can not display

### ISSUE THREAD

**Issue by Hallo-Word** [wenzhixin/bootstrap-table#3868]
Hi, 
I am trying to use the event function, but once I add "events: actionEvent" to the column, the data can not display. when I remove the event option, the display is back to normal. Can anyone advise me what is the issue? 
![default](https://user-images.githubusercontent.com/37182089/42014040-c6350dc4-7ad2-11e8-8b6d-3b446f276958.JPG)
![default](https://user-images.githubusercontent.com/37182089/42014061-d88d0508-7ad2-11e8-9fca-b51cb26b69b9.JPG)

**Comment by Hallo-Word** [comment]
Hi sorry I gound the reason, I put the event function inisde the document.ready function, which caused this issue. after I put the event function outside the document.ready function. it works!

**Comment by shuqiangzhou** [comment]
你好，请问你是如何处理的，我这边也遇到这样的情况。按照你的说法，把这个放到文档被加载完毕以外就可以执行，可是我这边他并没有按照预期的去做
