### ISSUE TITLE
change row style from another method

### ISSUE THREAD

**Issue by omatic-hacker** [wenzhixin/bootstrap-table#387]
Hello

I was searching some tables with bootstrap style, and found this project. First of all thank you for you work here.

Reading of docs confused me a little bit, and i have a question to ask. Maybe someone could help me.

I am using jquery, and i need dynamically change style of rows, based on some data input.

That's how i changed row data with updateRow method. 

```html
    <table id="iptable">
    ...
    </table>
```

// some js code here...
```javascript
        $(document).ready(
            function () {

                Page.updateIpTablePingColumn();

            });
```
    var Page = {
            updateIpTablePingColumn: function() {
                var Ipv4BeanList = iptable.bootstrapTable('getData');

                for (var i in Ipv4BeanList) {
                    Ipv4Controller.getIpv4PingStatus(updateStatus.ping(i), Ipv4BeanList[i].ipv4);
                }

            }

        };

        function updateStatus() {
            this.ping = function(i) {
                return function(data) {
                    iptable.bootstrapTable('updateRow', {
                        index: i,
                        row: {
                            ping: data.successFlag === true ? data.rtt : ' - '
                        }
                    });
                };
            }
        }

```


But how to change style in updateIpTablePingColumn function? 
For example, apply classes: 'danger'. how can i apply rowStyle(row, index) function?

**Comment by omatic-hacker** [comment]
I found part of answer by myself:

just create table with JS
```javascript
iptable.bootstrapTable({
                    method: 'get',
                    url: '/getIpv4UniqueList',
                    showToggle: true,
                    showColumns: true,
                        columns: [ {
                            field: 'ipv4',
                            title: 'Ipv4',
                            align: 'center',
                            sortable: true,
                            cellStyle: this.pingStatus
                        }]
                });
```
and then just update use function, in this example for cellStyle, i think for row style will be similar:

```javascript
            pingStatus: function (value, row, index) {
                if (row.ping === ' - ') {
                    return {
                        classes: 'danger'
                    }
                } else if (row.ping >= 0) {
                    return {
                        classes: 'success'
                    }
                } else {
                    return {
                        classes: 'default'
                    }
                }
            }
```

but still don't know if it right

**Comment by wenzhixin** [comment]
:+1:

**Comment by mehmetalidumlu** [comment]
Hi,
Can i change row style external function?
For example;

```
function findInvalidRows(){

        $.each($userTable.bootstrapTable('getSelections'), function (index, item) {
            if (item["USERNAME"].length <= 0) {
                setColorInvalidRow(item)
            }
        });
}
```
