### ISSUE TITLE
Pagination text appears in chinese

### ISSUE THREAD

**Issue by AkshayChan** [wenzhixin/bootstrap-table#3870]
The pagination text on my web page appears in chinese instead of english

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

When I set the parameters for data pagination, the text appears as 显示第 1 到第 5 条记录，总共 7 条记录 instead of Showing 1 to 5 records of a total of 7.

My browser is firefox 52.8.1 (64 bit) and OS is Windows 10 Enterprise
 
My parameters are data-toggle="table" data-sortable="table" data-pagination="true" data-page-number="1" data-page-size="5"

Thanks

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Need to remove the zh-cn locale file.
