### ISSUE TITLE
Fill ListView ASP.NET C# with JSON and set server side pagination

### ISSUE THREAD

**Issue by rodsanchez86** [wenzhixin/bootstrap-table#3871]
I have been trying fill a ListView control using JSON and setting server side pagination but is not making the call to the server to fill the ListView, i did test with a simply <table> and in this case i can show the data on table to achieve this i have a webmethod  in my codebehind and it works after call this webmethod the data is showed in the table not like that in the list

this is the table where i have tested and i can show data

![image](https://user-images.githubusercontent.com/40700506/42118478-feb7357c-7bc8-11e8-8897-61edd3634f4c.png)

This is the ListView where i can't show the data

 
![image](https://user-images.githubusercontent.com/40700506/42118501-1bf23dbc-7bc9-11e8-93a9-bada7d119435.png)

This is my webmethod in codebehind:

 
![image](https://user-images.githubusercontent.com/40700506/42118515-30778bde-7bc9-11e8-94e8-abe6e7edacec.png)

**Comment by jimgit** [comment]
Please include a jsfiddle to demonstrate.  You can use something like myjson.com to simulate your json data sample.  Also check pagination is set to server.

![image](https://user-images.githubusercontent.com/1921941/42124825-986f2d58-7c2f-11e8-9654-592bc9b240b9.png)

**Comment by rodsanchez86** [comment]
The problem si not fill a simply <table> actually i can fill it now the problem is fill a ListView

![image](https://user-images.githubusercontent.com/40700506/42126836-8477d740-7c53-11e8-8447-3d95fffb5d65.png)

**Comment by jimgit** [comment]
I am still confused on what you are trying to do.   Can you include a [JSFiddle?](https://www.youtube.com/watch?v=80hi1sXuni4)  Here are [some examples that get you started.](http://bootstrap-table.wenzhixin.net.cn/examples/)

**Comment by rodsanchez86** [comment]
Simply i want to bind a ListView in c# asp.net using server side pagination

**Comment by Falseee** [comment]
If the table is not the issue, then pls ask in a ASP.NET forum/chat.
If i misunderstood something pls reopen the issue and provide us an jsfiddle.
