### ISSUE TITLE
Clear filterControl with Cookie

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#3874]
I use filterControl and Cookie that store to localstring.

When I filter some column data with input filter and reload the page, the talbe still filtered because the cookie is active. It's OK.
But if I click to "Clear Filter" button and after I reload the page, the filter still aply.
To Chrome console, when I click to "Clear Filter", I see bs.table.filterControl is deleted and  is recreated.
To resolve it, to <b>BootstrapTable.prototype.clearFilterControl</b> function, I've add this line `            $.each(that.options.filterControls, function (i, item) {
                item.text = '';
            });`
after this line:<br>`$.each(that.options.valuesFilterControl, function (i, item) {
                item.value = '';
            });`

I'dont' know if this lines I've added could create another problem, but it resolve my problem to clear filterControl.

I'm using filterControl v2.1.3 and cookie v.1.2.3

**Comment by djhvscf** [comment]
This is an issue in Cookie extension. Working in progress

**Comment by djhvscf** [comment]
Fixed in https://github.com/djhvscf/bootstrap-table/commit/fc5b29fec3ea7ae7b89226c81e8bdbb9eb02e6df

**Comment by djhvscf** [comment]
Fixed here https://github.com/wenzhixin/bootstrap-table/pull/3968

**Comment by manukieli** [comment]
The problem back again with the version v.13.3
You can see the issue here:
https://jsfiddle.net/2ot4d5r3/11/

**Comment by manukieli** [comment]
I've the same problem with the version v.1.13.4
I'm using localstorage to store filter data.
I've add this line into the file bootstrap-table-filter-control.js
After this lines (line 829):
`
            $.each(that.options.valuesFilterControl, function (i, item) {
              hasValues = hasValues ? true : item.value !== '';
              item.value = '';
            });
`
I've add this line:
`
            $.each(that.options.filterControls, function (i, item) {
              item.text = ''
            });
`
And the issue is fixed.

**Comment by manukieli** [comment]
I've the same problem with the version v.1.13.5
I'm using localstorage to store filter data.
I think it's because when your script invoke **function clearFilterControl()**, this function create the variable cookies with the function **UtilsFilterControl.collectBootstrapCookies()**.
And this function find only cookie and not into the localStorage.

**Comment by ktecho** [comment]
@djhvscf It's happening to me with 1.14.1 using default storage (cookieStorage).

When I click the "Clear filters" button, the filters are cleared and I can see all the registers. But if I reload the page, the filters are there again.

So @manukieli, it's not just about localstorage.

**Comment by ktecho** [comment]
I've been debugging it and I haven't come to a conclusion yet (I'm no expert in Bootstrap-Table), but I've seen that cookies gets deleted but then they're created again.

The browser starts executing `onColumnSearch` code after the cookies gets deleted, so I think that's what makes it create the cookies again.

**Comment by ktecho** [comment]
@manukieli solution seems to work.

I added his line after this block of code:

```
                        $.each(that.options.valuesFilterControl, function (i, item) {
                            hasValues = hasValues ? true : item.value !== '';
                            item.value = '';
                        });
```

**Comment by djhvscf** [comment]
@ktecho could you, please, create a new PR?

**Comment by djhvscf** [comment]
Fix on this PR https://github.com/wenzhixin/bootstrap-table/pull/4202

**Comment by wenzhixin** [comment]
Merged
