### ISSUE TITLE
How to add button if editable select field is empty

### ISSUE THREAD

**Issue by docholiday** [wenzhixin/bootstrap-table#3875]
Hi there,

any ideas or suggestions, how I could add a button into a column, if the value of an editable select field is empty? (see the second static table in the example)
Or more generally - how can I format an editable select field?

Example:
https://jsfiddle.net/rpxk29ub/35/

What I want to achieve is, that a user has the possibility, to either select one of the existing entries, or add a new one.

Regards, Doc

**Comment by djhvscf** [comment]
This is not supported by Bootstrap-table. You need to see this feature with [x-editable](https://github.com/vitalets/x-editable)
