### ISSUE TITLE
Is it possible request filter data to server with ajax?

### ISSUE THREAD

**Issue by rublevma** [wenzhixin/bootstrap-table#3876]
Need make filter using server side...

**Comment by rublevma** [comment]
Need make filter using server side...

**Comment by jimgit** [comment]
Use the URL property with [server side pagination.](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data2.json)

![image](https://user-images.githubusercontent.com/1921941/42216356-37fbc92c-7e87-11e8-8b73-8e33f0162ec5.png)

**Comment by rublevma** [comment]
I mean some thing like that, but server side
![image](https://user-images.githubusercontent.com/10795394/42224596-2d3d10ca-7ee3-11e8-8be1-093c701756c9.png)

**Comment by serlogo53** [comment]
also i have same problem. table is sending like "filter:{"paramx":"1","paramy":"2"}" but. in php file problem. when i try to decode or encode i have chracter problem. please help master.

**Comment by Falseee** [comment]
Yes its possible, fetch the filters on the server side and apply them on your query (e.g. mysql).
