### ISSUE TITLE
在table中监听了cell点击事件，如果隐藏了列，原来的列名对不上

### ISSUE THREAD

**Issue by zhenghuasheng** [wenzhixin/bootstrap-table#3879]
在table中监听了cell点击事件，如果隐藏了列，原来的列名对不上

**Comment by zhenghuasheng** [comment]
First,  I was listening to the cell click event in table！！！  However, if there are hidden columns, the columns and target columns can not match.

**Comment by djhvscf** [comment]
Thanks @zhenghuasheng do you have any jsfiddle where we can test this issue?

**Comment by wenzhixin** [comment]
Fixed in the latest version.
