### ISSUE TITLE
Background color on active (current) pagination number

### ISSUE THREAD

**Issue by toter** [wenzhixin/bootstrap-table#388]
Hi... I found this project recently and I must say... It is extremely useful and saved me a lot of time. Thank you.

I would like to know if it is possible to change the background color of the current pagination number. 

The default way is barely visible to quickly visualize on which page the user is at a particular moment. Only the foreground color of the number changes almost imperceptibly from blue to gray.

I'm a newbie, so... Where do I go to change the background color of the active pagination number to make it more visible?

Thank you again.

**Comment by wenzhixin** [comment]
Try this:
```html
<style>
.fixed-table-pagination li.active a {
    background: #000;
    color: #fff;
}
</style>
```
