### ISSUE TITLE
Loading table from ajax (not json)

### ISSUE THREAD

**Issue by dbnar2** [wenzhixin/bootstrap-table#3884]
I've looked through the issues and documentation and can't find anything similar. I am trying to load an html table through ajax. I basically get this data, format it into my desired table with php then pass the html table through ajax and put it inside a div. The table loads fine however it doesnt load as a bootstrap table just the regular html table I have. I tried adding data-toggle="table" to the attributes to the table but it does not seem to do anything. I don't really know how to provide a jsfiddle with this example.
But just to summarize.
I format an html table with php, I pass it with ajax to my desired page. And boostrap table doesn't load. Is there something I should do such as wait for ajax to pass the table first and then apply the data-toggle attribute?

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
