### ISSUE TITLE
Composite column head

### ISSUE THREAD

**Issue by ShawnShi666** [wenzhixin/bootstrap-table#3887]
1、the column head more than two rows   **"border-left:non"**

2、code in bootstrap-table.js:

html.push('<th' + sprintf(' title="%s"', column.titleTooltip),
                    column.checkbox || column.radio ?
                        sprintf(' class="bs-checkbox %s"', column['class'] || '') :
                        class_,
                    sprintf(' style="%s"', halign + style),
                    sprintf(' rowspan="%s"', column.rowspan),
                    sprintf(' colspan="%s"', column.colspan),
                    sprintf(' data-field="%s"', column.field),
                    j === 0 && column.fieldIndex ? ' data-not-first-th' : '',
                    '>');

3、i 'm try change "j === 0 && column.fieldIndex" to "j === 0 && i !== 0" as follows:

html.push('<th' + sprintf(' title="%s"', column.titleTooltip),
                    column.checkbox || column.radio ?
                        sprintf(' class="bs-checkbox %s"', column['class'] || '') :
                        class_,
                    sprintf(' style="%s"', halign + style),
                    sprintf(' rowspan="%s"', column.rowspan),
                    sprintf(' colspan="%s"', column.colspan),
                    sprintf(' data-field="%s"', column.field),
                    j === 0 && i !== 0 ? ' data-not-first-th' : '',
                    '>');
This change solved my problem.

What are the problems I'm not sure if my modification. so hope your support, thanks.(In the loacl modify )

**Comment by ShawnShi666** [comment]
this is my testing data:

columns: [[
                {
                    title: 'Team',
                    halign: 'center',
                    align: 'center',
                    rowspan: 3,
                    colspan: 1
                }, {
                    field: 'FAVORITE_PO',
                    title: 'Received',
                    align: 'center',
                    rowspan: 3,
                    colspan: 1
                }, {
                    field: 'Log_Issue',
                    title: 'Complete',
                    align: 'center',
                    rowspan: 3,
                    colspan: 1
                }, {
                    field: 'Cancel',
                    title: 'Cancel',
                    align: 'center',
                    rowspan: 3,
                    colspan: 1
                }, {
                    title: 'Open-Unclean Control',
                    align: 'center',
                    colspan: 5,
                    rowspan: 1
                }, {
                    title: 'Open-TAT Control',
                    align: 'center',
                    colspan: 3,
                    rowspan: 1
                }, {
                    title: 'Open-Urgent Mg',
                    align: 'center',
                    colspan: 2,
                    rowspan: 1
                }, {
                    title: 'Miss TAT Total',
                    align: 'center',
                    colspan: 1,
                    rowspan: 3
                }, {
                    title: 'Miss TAT%',
                    align: 'center',
                    colspan: 1,
                    rowspan: 3
                }, {
                    title: 'Unclean Total',
                    align: 'center',
                    colspan: 1,
                    rowspan: 3
                }, {
                    title: 'Unclean%',
                    align: 'center',
                    colspan: 1,
                    rowspan: 3
                }
            ],
            [
                {
                    title: 'Clean',
                    align: 'center',
                    colspan: 3,
                    rowspan: 1
                }, {
                    title: 'Unclean',
                    align: 'center',
                    colspan: 2,
                    rowspan: 1
                }, {
                    title: 'TAT no issue',
                    align: 'center',
                    colspan: 1,
                    rowspan: 2
                }, {
                    title: 'TAT Approach',
                    align: 'center',
                    colspan: 1,
                    rowspan: 2
                }, {
                    title: 'Miss TAT',
                    align: 'center',
                    colspan: 1,
                    rowspan: 2
                }, {
                    title: 'Urgent Order',
                    align: 'center',
                    colspan: 1,
                    rowspan: 2
                }, {
                    title: 'Non Urgent',
                    align: 'center',
                    colspan: 1,
                    rowspan: 2
                },
            ],
            [
                {
                    title: 'New',
                    align: 'center'
                }, {
                    title: 'Validating',
                    align: 'center'
                }, {
                    title: 'Order Processing',
                    align: 'center'
                }, {
                    title: 'On Track',
                    align: 'center'
                }, {
                    title: 'Need Action',
                    align: 'center'
                },
            ]
            ]

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Falseee** [comment]
I close this issue because we got no response/example from you.
If you still need help pls reopen the issue and provide us a jsFiddle.
