### ISSUE TITLE
After update, table view sort change

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#3888]
I've a table with **data-unique-id="id"** and the column can sort.
I want to update some data to table when I click to the row.
When I sort some column who have similar data and click to the row.
The table view sort change when it should not change.

You can view an example here: http://jsfiddle.net/e3nk137y/33573/
An try to click to row.

**Comment by djhvscf** [comment]
Example is not working. If this issue persists, please open new issue with corresponding jsfiddle
