### ISSUE TITLE
固定表头、多列表头只有第一列可拉伸，其余列不可拉伸宽度、表格底部会留出与表头相同高度空白。

### ISSUE THREAD

**Issue by Life-Winner** [wenzhixin/bootstrap-table#3889]
谢谢，作者提供此框架
1、三列表头固定（比较复杂数据展示）、设置了列拉伸只有第一行表头可拉伸。其余2行表头不可拉伸，设置了表格宽度也不生效。开始怀疑是列拉伸插件问题、尝试了更换1.4、1.5、1.6的情况差不多，没个版本会出现不同问题（目前使用1.6，table使用1.9.1）。
2、就是列拉伸问题：可拉伸了，表格内容底部会出现一处空白与表头一样大小；
谢谢，作者能留意看看。也可加QQ：972923987

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by Life-Winner** [comment]
Thank you. The problem is temporarily filtered.
