### ISSUE TITLE
Cannot read property 'order' of undefined on clear filter

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#3891]
I've this example in jsfiddle: http://jsfiddle.net/kkmwxr1t/11/
When you order some column and you click to "Clear Filter" button, to console, I've this error:<br>
![image](https://user-images.githubusercontent.com/14294794/42864135-aee7083c-8a65-11e8-8068-3ac2b92fddf5.png)

**Comment by djhvscf** [comment]
jsfiddle is not working

**Comment by manukieli** [comment]
For me it's working.
The icon is not visible, but is working.
Click to the icon you can see to image and see the console log.
![2018-07-23_17-53-48](https://user-images.githubusercontent.com/14294794/43088089-a1d36c18-8ea1-11e8-8661-b168f7add22d.png)

**Comment by djhvscf** [comment]
Could you use the latest version of the js files in development branch?

**Comment by manukieli** [comment]
Try this http://jsfiddle.net/kkmwxr1t/17/
I've the same issue.

**Comment by djhvscf** [comment]
Fix in https://github.com/djhvscf/bootstrap-table/commit/2a12d495746632cd13b63012a65a831f84e66566

**Comment by djhvscf** [comment]
http://jsfiddle.net/djhvscf/kkmwxr1t/21/

**Comment by djhvscf** [comment]
Fixed here https://github.com/wenzhixin/bootstrap-table/pull/3968
