### ISSUE TITLE
how to update the formatter column dynamically?

### ISSUE THREAD

**Issue by Leedorado** [wenzhixin/bootstrap-table#3894]
I'd like to implement an select box in the a column,and the options are from the server side through AJAX.However,if I don't set reinit as false,the table will keep posting data to the server side.Otherwise,the col value doesn't update at all.How can I fix the proble?Thx~
 Here is the related part in my implemention code:

{
                field : 'overtime_end',
                title : 'endtime',
                valign : 'center',
                align : 'center',
                halign : 'center',
                formatter : selectionFormatter,
            }

function selectionFormatter(value,row,index){
            $.ajax({
                type : 'POST',
                url : "{% url 'get_start_datetime' %}",
                contentType : 'application/x-www-form-urlencoded',
                data : {
                    'csrfmiddlewaretoken' : Cookies.get('csrftoken'),
                },
                dataType : 'json',
                success : function(data) {
                    select =  "<select><option>" + data.test + "</option></select>";
                    colValue = {
                        index : index,
                        field : "overtime_end",
                        value : select,  
                    }
                    $('#apply_to_approve_list_table').bootstrapTable('updateCell',colValue);
                },
                error : function(e) {
                }
            });
        }

**Comment by jimgit** [comment]
Can you post a JSFIDDLE example?

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/methods/#refreshoptions
https://examples.bootstrap-table.com/index.html#methods/refreshOptions.html
