### ISSUE TITLE
Group column in IE does not display correctly as non-IE browser

### ISSUE THREAD

**Issue by mushpop** [wenzhixin/bootstrap-table#3896]
With IE, multiple row and column groups do not display correctly. Everything will be in one row and repeated, in my case twice. Using IE for internal office application. 

Browser: IE 10
Environment: Windows 10

[jsfiddle]() - a link to the reduced test case([fiddle template](https://jsfiddle.net/gbpxnLz7)).

**Comment by mushpop** [comment]
For IE: You must use columns in the script to recreate the table header

**Comment by djhvscf** [comment]
jsfiddle is not working

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
