### ISSUE TITLE
resizable and fixedColumns extension cannot work together 固定列头和可拖动插件不能同时支持

### ISSUE THREAD

**Issue by LianJilu** [wenzhixin/bootstrap-table#3899]
When I try ues resizable and fixedColumns extension, it can work with one, but cannt work together

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Falseee** [comment]
I close this issue because we got no response/example from you.
If you still need help pls reopen the issue and provide us a jsFiddle.
