### ISSUE TITLE
Unable to get page number of a record

### ISSUE THREAD

**Issue by prosperva** [wenzhixin/bootstrap-table#3900]
Is there a function to get a row's page number? 

//this only returns data
listTable.bootstrapTable("getRowByUniqueId","Apple")

//This hides all but the found record
listTable.bootstrapTable('filterBy',{"Importer":"Apple"})

**Comment by djhvscf** [comment]
Do you mean for example: I need to know in which pages is Apple item?

If yes, that is not supported.

**Comment by prosperva** [comment]
Well Apple would be a distinct item and let's it is on page 2. So does this library have functions to look up a distinct item and then paginate to the page it is on?

**Comment by djhvscf** [comment]
Got it! But no @prosperva that is not supported at this moment. Any PR is welcome
