### ISSUE TITLE
Scrollbar when columns are grouped 

### ISSUE THREAD

**Issue by agmorpheus** [wenzhixin/bootstrap-table#3902]
I have noticed that grouped columns produce always a horizontal scrollbar at the bottom of the table. I think this could be fixed.

http://issues.wenzhixin.net.cn/bootstrap-table/#options/group-columns.html

**Comment by djhvscf** [comment]
Could you share us an example of that fix?

**Comment by agmorpheus** [comment]
I have not fixed it yet. I just noticed it while playing around. For my current project i do not need grouped columns.
