### ISSUE TITLE
Pre-Select Columns Checkboxes

### ISSUE THREAD

**Issue by tomherold** [wenzhixin/bootstrap-table#3904]
Is it possible to preselect the columns options? For example to have one or more columns not showing in the table by automatically uncheck the columns options.

**Comment by jimgit** [comment]
There is a HIDE COLUMNS method

http://bootstrap-table.wenzhixin.net.cn/documentation/#methods


![image](https://user-images.githubusercontent.com/1921941/43148251-875c0cd0-8f2a-11e8-968d-6e918e218f9d.png)

**Comment by tomherold** [comment]
Yes, but I want to change the checkbox in the column option to not checked.

**Comment by djhvscf** [comment]
Use visible column property for this
