### ISSUE TITLE
反馈期待支持的需求

### ISSUE THREAD

**Issue by thinksea** [wenzhixin/bootstrap-table#391]
我非常喜欢您的这个组件，准备在我的项目中应用时遇到几个困惑，请求给予帮助将不胜感激。
1、如何公开刷新按钮事件让我的javascript函数知道需要执行刷新操作？
2、简洁的格式化字符串，用于处理常见的格式化需求更简练
看起来类似于这种形式&lt;th data-field="id" data-formatestring="&lt;a href='modify.aspx?id={0}'>Edit&lt;/a>" data-htmlEncode="true“>XXX&lt;/th>
3、增加自动HTML转义定义
&lt;th data-field="id" data-htmlEncode="true“>XXX&lt;/th>
htmlEncode用于对表格内容自动进行HTML编码。
注意：当指定htmlEncode=true时，data-formatter应当传送未转码的原始数据。
4、分页导航需要一个快速页码定位的功能，可以让用户自己输入立即跳转到的页码。
在后台大量数据管理业务中，当多个用户需要分工处理不同页码的数据，如果能让用户很快找到自己需要处理的数据将是一件美好的事情。
5、如何实现可配置的参数，我的项目中数据服务提供的数据格式是写好的，可接受的查询参数(pageindex，pagesize)等是不可更改的命名，需要客户端可以配置查询参数名称。
6、如何同时将用户自定义筛选参数传递到后台？

**Comment by thinksea** [comment]
2、简洁的格式化字符串，用于处理常见的格式化需求更简练
看起来类似于这种形式<th data-field="id" data-formatestring="<a href='modify.aspx?id={0}'>Edit</a>" data-htmlEncode="true“>XXX</th>

**Comment by thinksea** [comment]
3、增加自动HTML转义定义
<th data-field="id" data-htmlEncode="true“>XXX</th>
htmlEncode用于对表格内容自动进行HTML编码。
注意：当指定htmlEncode=true时，data-formatter应当传送未转码的原始数据。

**Comment by neozhu** [comment]
你完全可以自己完成这些功能然后提交给作者，这是开源项目，别人已经无偿给你用了，你还好意思让作者给你开发功能！

**Comment by wenzhixin** [comment]
@thinksea 多谢你的建议，第 5 6 两点现在已经是有的，其他的会考虑。

**Comment by wenzhixin** [comment]
除了第四点，暂时不打算增加，可以自己扩展例如 http://issues.wenzhixin.net.cn/bootstrap-table/#methods/selectPage-prevPage-nextPage.html ，其他的都加了相应的功能了。

**Comment by thinksea** [comment]
非常感谢作者的辛勤努力，祝bootstrap-table越来越好

**Comment by apple5702** [comment]
感谢作者提供的这个插件，很好用，bootstrap-table自定义跳转分页功能，我写好了，可以分享给大家
