### ISSUE TITLE
Multiple Selection Row Extension Broken

### ISSUE THREAD

**Issue by ZiluckMichael** [wenzhixin/bootstrap-table#3911]
### Problem 1:
When you use the multiple-selection-row extension, it extends the default variables into the normal table defaults. However, the $.extend() method ignores variables set to undefined. This means that on line 39 when it tries to access multipleSelectRowLastSelectedRow, it throws up exceptions.

This could be fixed by either having it default to the header, or add in a check for when that value is undefined, and when it is, extend in the correct values and move from there.

The code in question:

`selectRowsBetweenIndexes([that.bootstrapTable("getOptions").multipleSelectRowLastSelectedRow.rowIndex, e.currentTarget.rowIndex], that)`

### Problem 2:
Additionally, Ctrl+Click does not work at all. There are two situations that can occur when the Ctrl key is held down and you click on a row.

1. **Situation:** There is already a row selected. **Result:** The original row is deselected, the new row is selected (only noticeable if you have a breakpoint), and the new row is immediately deselected.
2. **Situation** No rows are selected. **Result:** The new row is selected (only noticeable if you have a breakpoint), and the new row is immediately deselected.

Cause: the row is being selected and given the class used by the extension BEFORE it gets to the actual code block. I double checked to make sure and I definitely did not load/run the script twice as it occurs both in my application and the totally fresh jsfiddle I made for this issue. 

### Code:

My jsfiddle: https://jsfiddle.net/yxna6z45/

**Comment by ZiluckMichael** [comment]
Followup.
If the following occurs:

1. A user checks a single row or multiple rows.
2. They click the select all button.
3. They click the deselect all button.

Any rows that were given a class in step 1 still has that class after they have been unchecked.

**Comment by wenzhixin** [comment]
#4256
