### ISSUE TITLE
How to use editable Select2 (dropdown mode)?

### ISSUE THREAD

**Issue by ArtioDev** [wenzhixin/bootstrap-table#3915]
I want to use editable Select2 (dropdown mode) as shown in
https://vitalets.github.io/x-editable/demo-bs3.html#

I set type to 'select2' and 'dropdown' to true, but it doesn't work.
```
editable: {
 type: 'select2',
    source: [
              {id: '1, text: 'Item 0'},
              {id: '2', text: 'Item 1'},
              {id: '3', text: 'Item 2'}
    ],
    select2: {
        dropdown: true
     }
```
What's the right way to do it? Thanks!

**Comment by ktecho** [comment]
Hi @ArtioDev 

Did you manage to get a dropdown working with editable?

**Comment by ArtioDev** [comment]
Hi, @ktecho 
Yes, This is my code : 
`editable: {
                source: groups,
                type: 'select2',
                allowClear: true,
                showbuttons: false,
                select2: {
                    placeholder: 'Select Group',
                    minimumInputLength: 1,
                    width: 175
                }
            }`
Where groups is an object array like this :
`[{"id":1,text:"test"},{"id":2,text:"test2}]`

PS : You have to include select2.full.js and bootstrap-editable.js
