### ISSUE TITLE
Lose ctrl, shift, and other event modifiers with click()

### ISSUE THREAD

**Issue by ZiluckMichael** [wenzhixin/bootstrap-table#3917]
When you use the click() function in jQuery, it does not preserve any modifiers to the event. As such, if someone uses Ctrl+Click on a row, the fact that Ctrl was pressed when the row was clicked does not get passed down to events such as onCheck when clickToSelect is turned on.

[Here](https://stackoverflow.com/questions/9377046/jquery-trigger-ctrl-click) is an easy way to fix the problem.

[jsfiddle](https://jsfiddle.net/02pwkty5/1/).

**Comment by Falseee** [comment]
Thanks for the "bug" report, i tried your fix but it dont work for me.
Could you submit a working PR ?

**Comment by wenzhixin** [comment]
Fixed in #4256, added multipleSelectRow option: https://github.com/wenzhixin/bootstrap-table/commit/4881222a994f7348ea9b0e08dcd110307f89d177
