### ISSUE TITLE
Trying to modify the source of a select that is part of a Table

### ISSUE THREAD

**Issue by DocSeussMan** [wenzhixin/bootstrap-table#3918]
I have a table with a column that is x-editable of type select.
   ` {   title: 'Product',`
        `field: 'product',`
        `align: 'center',`
        `valign: 'middle'`,
       `width: '20%',`
        `editable: {`
            `           type: 'select',`
           ` source: testarray`
      ` }`
   ` }`
When the source testarray is modified I need to update this column in all the rows with the new available array values. Using something like this:
    `$('#tester').editable({type: 'select', source: testarray});`

But I can't seem to find a way to attach the id (tester) to the element

Can anyone point me in the right direction?

**Comment by UtechtDustin** [comment]
I close this issue because its already 2 years old.
I think you can do it with the [refreshOptions](https://bootstrap-table.com/docs/api/methods/#refreshoptions) method.

If you still need help, just write and we will reopen the issue.
