### ISSUE TITLE
onLoadError and the status is "200"

### ISSUE THREAD

**Issue by fengcheZt** [wenzhixin/bootstrap-table#3919]
The table is "sidePagination:'client'",the data from server is too many ,the count is 98000,then onLoadError and the status is "200"，I don't know why.
chrome response show "Failed to load response data".

**Comment by wenzhixin** [comment]
Does not support so much data, it should be that the returned data is truncated by the browser, causing the parsing of JSON to fail, it is recommended to use server-side pagination.
