### ISSUE TITLE
How can I order the data-formatter row?

### ISSUE THREAD

**Issue by lbelof** [wenzhixin/bootstrap-table#3925]
`<th data-width="40%" data-formatter="RetornaDescricao" data-sortable="true" data-sorter="alphanum">Descrição</th>`

I need to sort the description field but when I click to sort it change only the first 2 rows

**Comment by Falseee** [comment]
Create a second hidden Column for the description and use on the formatter description column the data-sort-name attribute ([more informations](http://bootstrap-table.wenzhixin.net.cn/documentation/))

From the documentation:
Provide a customizable sort-name, not the default sort-name in the header, or the field name of the column. For example, a column might display the value of fieldName of "html" such as "<b><span style="color:red">abc</span></b>", but a fieldName to sort is "content" with the value of "abc".
