### ISSUE TITLE
table content are missaligned after setting fixed headers

### ISSUE THREAD

**Issue by sdi2001** [wenzhixin/bootstrap-table#3928]
Hi,

I am struggeling to fix the headers of my table.
But after reading a lot of posts and FAQ i cant figure out what I am doing wrong.

On my developing machine I use windows 8.1 with chrome Version 67.0.3396.99

Accodrding to the attached picture you can see the missalignment of all table columns.

Further I attached also an example html file (AES_new.txt) to reproduze this issue.

Looking forward hearing from you.
Cheers Dieter

[AES_new.txt](https://github.com/wenzhixin/bootstrap-table/files/2254623/AES_new.txt)
![issuetable](https://user-images.githubusercontent.com/42043949/43602077-315cee46-968f-11e8-833d-16b9c332825a.JPG)

<!doctype html>
<html lang="en">
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="CSS/bootstrap-table.css" rel="stylesheet" type="text/css" />
    <script src="https://code.jquery.com/jquery-1.10.2.min.js" integrity="sha256-C6CB9UYIS9UJeqinPHWTHVqh/E1uhG5Twh+Y5qFQmYg=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script type="text/javascript" src="Scripts/bootstrap-table.js"></script>
</head>
<body>
    <div class="table_test_ScreenPlaceHolder" id="AESScreenPlaceholder">
    </div>
    <script>
        const $table = $('#AESScreenPlaceholder');

        function initTable(jsonObj)
        {
            var initData = {
                height: 300,
                columns: [{
                    field: 'timestamp',
                    title: 'Timestamp',
                    halign: 'center',
                    width: '10%'
                }, {
                    field: 'timeon',
                    title: 'Time On',
                    halign: 'center',
                    width: '10%'
                }, {
                    field: 'timeoff',
                    title: 'Time Off',
                    halign: 'center',
                    width: '10%'
                }, {
                    field: 'timeack',
                    title: 'Time ACK',
                    halign: 'center',
                    width: '10%'
                }, {
                    field: 'dpe',
                    title: 'DPE',
                    halign: 'center',
                    width: '30%'
                }, {
                    field: 'dpeval',
                    title: 'DPE Value',
                    halign: 'center',
                }, {
                    field: 'alerttext',
                    title: 'Alert Text',
                    halign: 'center',
                    width: '30%'
                }, {
                    field: 'alertstate',
                    title: 'Alert State',
                    halign: 'center',
                }],
                data: {}
            };
            var dataFromJson = {
                height: 300,
                columns: [{
                    field: 'timestamp',
                    title: 'Timestamp',
                    halign: 'center',
                    width: '10%'
                }, {
                    field: 'timeon',
                    title: 'Time On',
                    halign: 'center',
                    width: '10%'
                }, {
                    field: 'timeoff',
                    title: 'Time Off',
                    halign: 'center',
                    width: '10%'
                }, {
                    field: 'timeack',
                    title: 'Time ACK',
                    halign: 'center',
                    width: '10%'
                }, {
                    field: 'dpe',
                    title: 'DPE',
                    halign: 'center',
                    width: '30%'
                }, {
                    field: 'dpeval',
                    title: 'DPE Value',
                    halign: 'center',
                }, {
                    field: 'alerttext',
                    title: 'Alert Text',
                    halign: 'center',
                    width: '30%'
                }, {
                    field: 'alertstate',
                    title: 'Alert State',
                    halign: 'center',
                }],
                data: jsonObj
            };

            $table.bootstrapTable('destroy');
            $table.bootstrapTable(initData);
            $table.bootstrapTable("load", dataFromJson);
        }

        $(window).resize(() =>
        {
            $table.bootstrapTable('resetView');
        });

        function getHeight()
        {
            return $(window).height();// - $('h1').outerHeight(true);
        }

        $(() =>
        {
            var jsonData = [{ "timestamp": "18.08.2017 11:04:22", "timeon": "", "timeoff": "18.08.2017 11:04:22", "timeack": "", "dpe": "HomeScada.Devices.Watering.ConnState", "dpeval": "1", "alerttext": "no connection to WateringStation", "alertstate": "OFF" }, { "timestamp": "18.08.2017 19:03:27", "timeon": "18.08.2017 19:03:27", "timeoff": "", "timeack": "", "dpe": "HomeScada.Devices.Watering.ConnState", "dpeval": "0", "alerttext": "no connection to WateringStation", "alertstate": "ON" }, { "timestamp": "18.08.2017 19:04:27", "timeon": "", "timeoff": "18.08.2017 19:04:27", "timeack": "", "dpe": "HomeScada.Devices.Watering.ConnState", "dpeval": "1", "alerttext": "no connection to WateringStation", "alertstate": "OFF" }, { "timestamp": "18.08.2017 19:18:27", "timeon": "18.08.2017 19:18:27", "timeoff": "", "timeack": "", "dpe": "HomeScada.Devices.Watering.ConnState", "dpeval": "0", "alerttext": "no connection to WateringStation", "alertstate": "ON" }, { "timestamp": "18.08.2017 19:19:27", "timeon": "", "timeoff": "18.08.2017 19:19:27", "timeack": "", "dpe": "HomeScada.Devices.Watering.ConnState", "dpeval": "1", "alerttext": "no connection to WateringStation", "alertstate": "OFF" }, { "timestamp": "20.08.2017 05:00:32", "timeon": "20.08.2017 05:00:32", "timeoff": "", "timeack": "", "dpe": "HomeScada.Devices.Watering.ConnState", "dpeval": "0", "alerttext": "no connection to WateringStation", "alertstate": "ON" }, { "timestamp": "20.08.2017 05:01:32", "timeon": "", "timeoff": "20.08.2017 05:01:32", "timeack": "", "dpe": "HomeScada.Devices.Watering.ConnState", "dpeval": "1", "alerttext": "no connection to WateringStation", "alertstate": "OFF" }, { "timestamp": "20.08.2017 13:25:33", "timeon": "20.08.2017 13:25:33", "timeoff": "", "timeack": "", "dpe": "HomeScada.Devices.Watering.ConnState", "dpeval": "0", "alerttext": "no connection to WateringStation", "alertstate": "ON" }, { "timestamp": "20.08.2017 13:26:34", "timeon": "", "timeoff": "20.08.2017 13:26:34", "timeack": "", "dpe": "HomeScada.Devices.Watering.ConnState", "dpeval": "1", "alerttext": "no connection to WateringStation", "alertstate": "OFF" }, { "timestamp": "22.08.2017 03:00:31", "timeon": "", "timeoff": "22.08.2017 03:00:31", "timeack": "", "dpe": "HomeScada.Devices.Watering.Tanklevel", "dpeval": "39.8", "alerttext": "low water alert", "alertstate": "OFF" }];
            initTable(jsonData);
        })
    </script>
</body>
</html>

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by kelvin-ayonga** [comment]
I also have the same problem as @sdi2001 , the table columns are aligned properly in browsers on a mac, but are misalignment on browsers on windows. I have tested on Opera, and Chrome on both platforms cc @djhvscf

**Comment by Falseee** [comment]
I close this issue because we got no response/example from you.
If you still need help pls reopen the issue and provide us a jsFiddle.
