### ISSUE TITLE
bootstrap-table-filter-control backwards compatibility

### ISSUE THREAD

**Issue by Junglefish** [wenzhixin/bootstrap-table#3930]
Hi

Up until now I have been using:
bootstrap-table-1.10.1.js
bootstrap-table-filter-control-2.1.0.js

I want to make use of the new triggerSearch() feature in bootstrap-table-filter-control. So I upgraded to:
bootstrap-table-filter-control-2.1.2.js

However, this caused a lot of errors - see this image:
![capture1](https://user-images.githubusercontent.com/23358803/43645546-8be48d8a-9732-11e8-897b-8bf3167e56dc.PNG)

So, I upgraded the bootstrap-table file to:
bootstrap-table-1.12.1.js

However, this causes a set of similar, but not quite the same errors - see this image:
![capture2](https://user-images.githubusercontent.com/23358803/43645608-bc9227a8-9732-11e8-86af-03af519857c0.PNG)

Can you please advise as to what I have to do in order to use the new triggerSearch() method?

**Comment by Falseee** [comment]
If you still need help pls reopen the issue.
Why you dont update the bootstrap-table as well ?
