### ISSUE TITLE
Multiple level group by

### ISSUE THREAD

**Issue by claudneto** [wenzhixin/bootstrap-table#3931]
Is it possible to have multiple fields on any group by extension?
I'm using jquery.treetable (http://ludo.cubicphuse.nl/jquery-treetable/) to group table rows, but I must have a search feature and it's not possible with this plugin.

Bootstrap-table has all features I must have in my table, but two level grouping is missing.

**Comment by UtechtDustin** [comment]
I close this issue because its almost 1 year old, but we have a [tree grid](https://bootstrap-table.com/docs/extensions/treegrid/) maybe this will help you :-)
