### ISSUE TITLE
当前页要显示的数据{}会加上{0：undefined;...}

### ISSUE THREAD

**Issue by Handsome-Beauty** [wenzhixin/bootstrap-table#3932]
从后台获取到的数据res,在success: res => { }里进行处理，然后渲染到table里。success: res => { let Data=[]; 
 res[i]经过处理变成d;  再把Data.push(d);  每次d都是正确的{"ID":"111"; "time":"2018-01-012"}。期待的正确的Data是 [ {"ID":"111"; "time":"2018-01-01"},   {"ID":"222"; "time":"2018-01-01"}，{"ID":"333"; "time":"2018-01-01"}，{"ID":"444"; "time":"2018-01-01"}]。  但是最终Data就变成了类似[{ "ID":"111"; "time":"2018-01-01"},   {"ID":"222"; "time":"2018-01-01"}，{0：undefined; "ID":"333"; "time":"2018-01-01"}，{0：undefined; "ID":"444"; "time":"2018-01-01"}] 这样的，其他都对，就是当前页面渲染的数据{}每一个都多出了一个0：undefined，(比如现在第2页，每页有2个数据，那第3，4个数据会自动加上0：undefined,其他非当前页渲染的数据是正确的)。页面一直显示“正在努力地加载数据中，请稍候……”。

**Comment by Handsome-Beauty** [comment]
@wenzhixin 方便的时候麻烦您帮我看一下，谢谢您啦~我是新手，找不到原因，只好麻烦您了
![default](https://user-images.githubusercontent.com/33092773/43682164-abeb6218-989d-11e8-91ef-0bc9a2583ce4.PNG)

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by Handsome-Beauty** [comment]
@djhvscf I have solved this problem ,thank you all the same. The reason for this is that I accidentally deleted a line of code that is   if (!silent) this.$tableLoading.hide().
