### ISSUE TITLE
Advanced search option isn't displayed although I've added the table-toolbar.js extension? why?

### ISSUE THREAD

**Issue by rakeshshubhu** [wenzhixin/bootstrap-table#3933]
<table id="paymentTable"
           data-pagination = "true",
           data-page-size = "15",
           data-page-list = "[10,25,50,100]",
           data-search = "true",
           data-show-export="true",
           data-show-pagination-switch="true",
           data-show-refresh = "true",
           data-advanced-search = true,
           data-show-columns = "true",
           data-id-field="id",
           data-show-footer="true",
           data-show-export="true">

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by rakeshshubhu** [comment]
http://jsfiddle.net/ap6087jq/2/ ... I cannot get the advanced search.. option.. sir.. i"m missing something ..

**Comment by Falseee** [comment]
https://examples.bootstrap-table.com/index.html#extensions/tTbar.html
https://bootstrap-table.com/docs/extensions/toolbar/#advancedsearch

Works fine for me, pls reopen the issue if you still need help.
