### ISSUE TITLE
sprintf

### ISSUE THREAD

**Issue by MyJimmyZhou** [wenzhixin/bootstrap-table#3935]
var index = that.$header.find(sprintf('[data-field="%s"]',
                        that.options.sortName).index() + 1);

??

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by MyJimmyZhou** [comment]
Uncaught TypeError: sprintf(...).index is not a function
    at bootstrap-table.js:1071

**Comment by MyJimmyZhou** [comment]
var index = that.$header.find(sprintf('[data-field="%s"]',
                        that.options.sortName)).index() + 1;

**Comment by djhvscf** [comment]
@MyJimmyZhou I would need more information in this ticket. I'm not sure what is the problem

**Comment by wenzhixin** [comment]
Fixed in the latest version.
