### ISSUE TITLE
当列设置宽度时，设置页脚进行合计展示，页脚列的宽度无法与内容列宽对齐

### ISSUE THREAD

**Issue by 7neves** [wenzhixin/bootstrap-table#3937]
当设置列宽时，columns中设置width，再设置showFooter:true，此时页脚的列宽无法与内容的列宽对齐，请问如何解决？

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by 7neves** [comment]
sorry
When setting the width property, the width is set in the columns, and then the showFooter:true is set. At this time, the column width of the footer cannot be aligned with the column width of the content. How do you solve it?

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Fixed in v1.13.5.
https://examples.bootstrap-table.com/#options/show-footer.html
