### ISSUE TITLE
有偿求助：Bootstrap table实现一个报表查询功能（php+mysql）

### ISSUE THREAD

**Issue by tofindworld** [wenzhixin/bootstrap-table#3939]
正在做一个利用bootstrap table 做的报表查询平台，
后台用php+mysql，
由于时间紧，
请熟悉bootstrap table的大神联系我，帮我排除我代码的问题，必重金酬谢。

qq953485331

**Comment by wenzhixin** [comment]
不好意思，现在应该解决了吧。这个时间比较久了，关闭了。
