### ISSUE TITLE
Prepend new record to page 1 of table

### ISSUE THREAD

**Issue by crobinson42** [wenzhixin/bootstrap-table#394]
Hi, I'm wondering how to prepend a new row to the table if the user is on page 1 - the docs aren't clear to me on how to accomplish this. I notice there is only an append method to be used which adds to the bottom of the table.

I see using the 'refresh' method with {silent:true} but that is sending another request to update the table - I'd rather prepend if possible.

**Comment by wenzhixin** [comment]
Consider to add this method.
