### ISSUE TITLE
Sticky header does not horizontally scroll

### ISSUE THREAD

**Issue by rhefner** [wenzhixin/bootstrap-table#3941]
(Using the latest version of the plugin) 

I spent a while tracking this down, but it looks to me as if the scroll event listener that gets bound to the "fixed-table-body" by the sticky header extension gets overwritten by the default (?) scroll handler if treegrid is used.

The sticky header will still show up, but will not scroll horizontally. I guess the reason why it shows up because the $(window).scroll is bound to the render_sticky_header function from the plugin and gets called on scroll up/down. But, the handler for the table body gets pushed out. 

I managed to fix it by taking the plugin and dumbly creating an interval to reapply the handler (off/on) until I can figure out a better solution. Wondering if anyone else is experiencing the same and if there's a better solution out there!

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by rhefner** [comment]
@djhvscf I probably should've tried a fiddle first, that lead to the real issue, I believe - The sticky header plugin doesn't scroll horizontally with the rest of the table (`fixed-table-body`), if there's overflow on the x-axis, irrespective if it uses a treegrid or not.

Here's a fiddle:  https://jsfiddle.net/brassman/f751nuax/17/

Back to the original report -- Since it wasn't working, I had modified the sticky header's `match_position_x` scroll handler to use `fixed-table-body`'s `scrollLeft()` and sync it with the sticky header container id instead.  In that process, instead of including the extension from `node_modules/bootstrap-table/...`, I included my own fix.  When I did that, I did notice the observation in the initial report where the scroll handler on `fixed-table-body` would get overwritten by one from `bootstrap-table` directly IF the treegrid plugin was used.  Else, the modified handler code would work fine.

**Comment by wenzhixin** [comment]
Rewrited the code to fix this problem(https://github.com/wenzhixin/bootstrap-table/commit/2766e0074c2ddf863180549da336131b9615c65b) in develop branch.
Develop Example: http://dev.bootstrap-table.com/examples/#extensions/sticky-header.html
