### ISSUE TITLE
如何设置多行显示

### ISSUE THREAD

**Issue by zsy619** [wenzhixin/bootstrap-table#3942]
数据结构：id、内容、号码、产品、创建时间
如何设置，将 内容 单独一行，其他列放到一行？？
也就是一条数据，多行显示

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by zsy619** [comment]
Data structure: ID, content, number, product, creation time
How do I set up content a separate line and separate the other line?
That is, one data, multi line display.

**Comment by zsy619** [comment]
![Uploading 1534144407556.jpg…]()
Data structure: ID, content, number, product, creation time
How do I set up content a separate line and separate the other line?
That is, one data, multi line display.

**Comment by wenzhixin** [comment]
@zsy619 这个应该不支持，你要考虑普通的 table 是否支持。
