### ISSUE TITLE
Is there a way to include the show loading message using any of the callback event methods like sort etc.

### ISSUE THREAD

**Issue by sunilsr1986** [wenzhixin/bootstrap-table#3944]
Short and descriptive example bug report title
Is there a way to include the custom message using any of the callback event methods when large number of datas are being sorted using  $('.table').bootstrapTable('showLoading'); and 
$('.table').bootstrapTable('hideLoading');
Please let me a know a proper way of doing this avoiding the ajax call.
This is the first step
I did try this by invoking the loader  using the 'sort.bs.table' (when we click on sort) and  hiding the loader at 'post-body.bs.table'
This is the second step
	$('.table').on('sort.bs.table', function (e, arg1, arg2) {
		$('.table').bootstrapTable('showLoading');

	});
$('.table').on('post-body.bs.table', function (e, arg1, arg2) {
		$('.table').bootstrapTable('hideLoading');

});
But this doesn't give the desired output
Further steps, etc.
But I could see the "that"  which is used for calling the onSort as explained below was an issue . When I implemented the Loading in the following format that works (included the  that.onSort(event);) within the closure. Then I call the hidemethod from the postbody function again. 
===================================================
Line no: 917
this.$container.off('click', '.th-inner').on('click', '.th-inner', function (event) {
    var $this = $(this);

    if (that.options.detailView && !$this.parent().hasClass('bs-checkbox')) {
        if ($this.closest('.bootstrap-table')[0] !== that.$container[0]) {
            return false;
        }
    }

    if (that.options.sortable && $this.parent().data().sortable) {
        **$('.table1').bootstrapTable('showLoading');
        $(function(){
            that.onSort(event);
        })**
    }
});
=========================

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by djhvscf** [comment]
Please review the docs http://bootstrap-table.wenzhixin.net.cn/
