### ISSUE TITLE
Silently fails to load when pagination is disabled.

### ISSUE THREAD

**Issue by baratox** [wenzhixin/bootstrap-table#3947]
When pagination is disabled, method `load` ignores `dataField` options and assumes it is named `data`

https://github.com/wenzhixin/bootstrap-table/blob/322a673e1f4057f358dc1fa80bd82015b357a833/src/bootstrap-table.js#L2440-L2447

**Comment by djhvscf** [comment]
Hi, you're right. Could you create a new PR against dev?
