### ISSUE TITLE
group by extension v2 - sorting within groups

### ISSUE THREAD

**Issue by tfsmag** [wenzhixin/bootstrap-table#3948]
On the group by v2 extension, is there any way to do one of the following.

1: Allow sorting within the groups. IE: When the data is grouped, and I click on say a 'qty' header. Within each group I'd like to see the quantities get sorted, per group.

2: After the table is rendered, be able to set a default grouping. ie: your table loads the data, and then sorts (within the groups) to a default column and direction.

I hope I'm just missing something easy here, I'm sure I'm not the first to have this issue.

Thanks!

**Comment by UtechtDustin** [comment]
The group by extension will be merged/rewritten, this issue will be checked in #4413.
