### ISSUE TITLE
enable/disable button on click

### ISSUE THREAD

**Issue by iamthestreets** [wenzhixin/bootstrap-table#395]
Hi,

I have a delete button, but i want the button to be disabled until at least 1 checkbox is checked. Any ideas how I can do this?

**Comment by wenzhixin** [comment]
Added an example: http://issues.wenzhixin.net.cn/bootstrap-table/395.html

**Comment by iamthestreets** [comment]
Thanks! That worked!

**Comment by havok2063** [comment]
I can't seem to get this example working.  I've followed the source code, however it doesn't delete the rows.  I am able to successfully get the ids of the rows, however when I call bootstrap('remove'), this doesn't work.  But I can't tell what is different from the example that does work.   For the params, I'm passing in field:'id', and values: array of ids.

**Comment by wenzhixin** [comment]
I think it is bootstrapTable('remove', ...), not bootstrap('remove')?

**Comment by havok2063** [comment]
I am using bootstrapTable('remove').  That was a typo.  This is the javascript code I'm using.  

	var $table = $('.sastable');
	var $delete = $('#delete');
        $(function(){
	        $delete.click(function () {
                      var ids = $.map($table.bootstrapTable('getSelections'), function (row) {
                      return row.id
                });
            $table.bootstrapTable('remove', {
                  field: 'id',
                  values: ids
               });
        });

My table is recreated exactly the same way as yours.

**Comment by wenzhixin** [comment]
It seems a right way to use remove method, can you provide a jsFiddle?

**Comment by havok2063** [comment]
Well...here is a jsFiddle, but it's working now.  I my code straight into the fiddle, and then simplified it a bit and now it's working. However my original code still does not work.  I can't figure it out. 

https://jsfiddle.net/havok2063/u9n6gen9/

**Comment by havok2063** [comment]
I even just copied the working jsFiddle javascript and html code into my code, and that doesn't work either.

**Comment by havok2063** [comment]
I think I got it working.  It must have been something funky going on with my javascript.  My button wasn't registering any clicks.  So I just put the the script into a named function, and added a onClick='deleteRows()' onto my button.

**Comment by wenzhixin** [comment]
OK @havok2063 .
