### ISSUE TITLE
query data with the search param and the page number remain unchanged

### ISSUE THREAD

**Issue by niannianliu** [wenzhixin/bootstrap-table#3950]
$table.bootstrapTable({
		url: '${basePath}/manage/admin/list',
		height: getHeight(),
		striped: true,
		search: true,
		showRefresh: true,
		showColumns: true,
		minimumCountColumns: 2,
		clickToSelect: true,
		detailView: true,
		detailFormatter: 'detailFormatter',
		pagination: true,
		paginationLoop: false,
		sidePagination: 'server',
		silentSort: false,
		smartDisplay: false,
		escape: true,
		searchOnEnterKey: true,
		idField: 'userId',
		maintainSelected: true,
		toolbar: '#toolbar',
		columns: [
			{field: 'ck', checkbox: true},
			{field: 'adminId', title: '编号', sortable: true, align: 'center'},
            {field: 'username', title: '帐号'},
			{field: 'realname', title: '姓名'},			
			{field: 'mobile', title: '电话'},
			{field: 'email', title: '邮箱'},			
			{field: 'status', title: '状态', sortable: true, align: 'center', formatter: 'lockedFormatter'},
			{field: 'action', title: '操作', align: 'center', formatter: 'actionFormatter', events: 'actionEvents', clickToSelect: false}
		]
	});

用的table自带的search，比如总共有5页数据，搜索结果是1页，但是搜索后页数未更新还是5页

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by niannianliu** [comment]
$table.bootstrapTable({
	url: '${basePath}/manage/admin/list',
	height: getHeight(),
	striped: true,
	search: true,
	showRefresh: true,
	showColumns: true,
	minimumCountColumns: 2,
	clickToSelect: true,
	detailView: true,
	detailFormatter: 'detailFormatter',
	pagination: true,
	paginationLoop: false,
	sidePagination: 'server',
	silentSort: false,
	smartDisplay: false,
	escape: true,
	searchOnEnterKey: true,
	idField: 'userId',
	maintainSelected: true,
	toolbar: '#toolbar',
	columns: [
		{field: 'ck', checkbox: true},
		{field: 'adminId', title: 'ID', sortable: true, align: 'center'},
        {field: 'username', title: 'account'},
		{field: 'realname', title: 'realname'},			
		{field: 'mobile', title: 'mobile'},
		{field: 'email', title: 'email'},			
		{field: 'status', title: 'status', sortable: true, align: 'center', formatter: 'lockedFormatter'},
		{field: 'action', title: 'action', align: 'center', formatter: 'actionFormatter', events: 'actionEvents', clickToSelect: false}
	]
});
The config of bootstrap table is as indicated above.
e.g. there are five pages of data and the search result should be liminted in one page. In fact , there are five pages remained on the paging region after the search action. The paging should be refreshed when search.

**Comment by UtechtDustin** [comment]
Should be fixed in the newest version, if you still need help please reopen the issue.
