### ISSUE TITLE
1.12.0, 1.12.1版本中，showToogle图表无法正常显示

### ISSUE THREAD

**Issue by royal430** [wenzhixin/bootstrap-table#3951]
1.12.0, 1.12.1版本中，showToogle图表无法正常显示，所有浏览器都如此。
![image](https://user-images.githubusercontent.com/7113218/44323123-18e2fc00-a483-11e8-8ed9-4866e4aa734c.png)

将版本退回到1.11.1就正常，但是在官方的http://issues.wenzhixin.net.cn/bootstrap-table/#options/boolean-options.html 却是正常，不知是什么原因

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by SeifLee** [comment]
在代码中添加, 可以暂时解决这个问题
$("button[name='toggle']").html('<i class="glyphicon glyphicon-refresh icon-refresh glyphicon-list-alt icon-list-alt"></i>');

**Comment by SeifLee** [comment]
可以暂时这样解决: ![qq 20180822200507](https://user-images.githubusercontent.com/22840712/44462280-ba667b00-a646-11e8-8113-873e6383f873.png)

**Comment by wangjia2016** [comment]
这个是不是国人不维护了

**Comment by wenzhixin** [comment]
1.12.2 已修复
