### ISSUE TITLE
colspan with data-serach="true"  bug

### ISSUE THREAD

**Issue by aecuto** [wenzhixin/bootstrap-table#3952]
not work: http://jsfiddle.net/0gwyek2o/
work: http://jsfiddle.net/npozm5xy/
> <table data-toggle="table" data-search="true">
    <thead>
    <tr>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th data-colspan="3"></th>
    </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>Edit</td>
        <td>Show</td>
        <td>Delete</td>
      </tr>
      <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>Edit</td>
        <td>Show</td>
        <td>Delete</td>
      </tr>
    </tbody>
</table>

**Comment by wenzhixin** [comment]
Not supported.
