### ISSUE TITLE
Count rows with specific column value

### ISSUE THREAD

**Issue by rajahmad-mulani** [wenzhixin/bootstrap-table#3954]
Hi - I'm trying to get the count of rows with specific column value in the bootstrap table displayed in a label on top to show the status for e.g. in the below screenshot, need to show Available, On Trip and Assigned counts.
This should happen when the page loads, is there a way to access these counts from bootstrap table for me to then display in my page ? Pls help..

![screenshot from 2018-08-28 18-51-10](https://user-images.githubusercontent.com/42235285/44725813-e9239c00-aaf3-11e8-820b-233e6cec48f2.png)

**Comment by jimgit** [comment]
The event load success returns the data array

$('#table').bootstrapTable({
    onLoadSuccess: function (data) {
       var matchedData = data.filter(value => value.age === 23).length;
    }
});

**Comment by rajahmad-mulani** [comment]
Thank you.

**Comment by djhvscf** [comment]
@rajahmad-mulani if this is not solved, please comment here and we can reopen this issue

**Comment by rajahmad-mulani** [comment]
This is working correctly.
