### ISSUE TITLE
Bug in checkbox in some templates tht use plugin materialize

### ISSUE THREAD

**Issue by wagnerfillio** [wenzhixin/bootstrap-table#3956]
bug in the checkbox in some templates that use plugin materialize.

The checkbox was not visible.

The solution was to add a label in javascript.

Can you make it official?

`<input type="checkbox" id="btSelectAll" class="filled-in" name="btSelectAll" /><label for="btSelectAll" style="margin-bottom: 0px;height: 15px;"></label>`

`'<label style="margin-bottom: 0px;height: 15px;"' +
	 sprintf(' for="%s"', i) +
'</label>',`

**Comment by djhvscf** [comment]
Please create a Pull Request including an example.

**Comment by wenzhixin** [comment]
Support materialize framework in the latest version:
https://bootstrap-table.com/themes/materialize/
https://examples.bootstrap-table.com/index.html?materialize
