### ISSUE TITLE
The question of summation as a decimal

### ISSUE THREAD

**Issue by 7neves** [wenzhixin/bootstrap-table#3957]
If the total is a decimal, the string returning the decimal will report an error. What should you do?
`Uncaught TypeError: Cannot read property '1万元' of undefined`

**Comment by djhvscf** [comment]
Hi @7neves I think I don't understand the issue here. Could you please provide further information?

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
