### ISSUE TITLE
Question: Multi-item editing (rows, columns, cells)?

### ISSUE THREAD

**Issue by hubitor** [wenzhixin/bootstrap-table#3958]
Is multi-item editing (rows, columns, cells) like with DataTables possible?:
[https://editor.datatables.net/examples/advanced/multiItem.html](url)

**Comment by Falseee** [comment]
Currently not possible i guess, but might be a good new method.
@djhvscf @wenzhixin

**Comment by wenzhixin** [comment]
Not support this feature.
