### ISSUE TITLE
bootstrap-table How to fix the first column

### ISSUE THREAD

**Issue by horanly** [wenzhixin/bootstrap-table#3959]
For example, how to realize the function of freezing columns

**Comment by jimgit** [comment]
[Take a look at this page](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/fixed-columns.html)

**Comment by yusuke50** [comment]
Hi,

I can't find "bootstrap-table-fixed-columns" in 1.12.1.
Does it have other ways to fix the first column?

Thank you.
