### ISSUE TITLE
The Multiple Fields in Column from JSON (join data-field)

### ISSUE THREAD

**Issue by omatic-hacker** [wenzhixin/bootstrap-table#396]
Hello to all, can anybody help me:

I have json like: `id, name, field1, field2, field3`

how can i put in one column those three fields, i mean:

`id, name, field1+field2+field3`

Search on site documentation and found no examples.

I would appreciate any answer. Thanks.

similar to this with broken link on answer: issue:#177

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/177.html
