### ISSUE TITLE
通过jquery的.html()功能产生的表格内容，在点击排序或者搜索之后就会消失

### ISSUE THREAD

**Issue by zgli2011** [wenzhixin/bootstrap-table#3960]
通过jquery的$("#test").html(“task is finished”)功能，在表格的第二列显示一些内容，这些内容（“task is finished”）在点击排序或者在本地搜索框输入内容之后就会全部消失，且不能还原，这个问题如何解决
--------------------------------------------------------------------
I try to translate this issue to english.
when i use the bootstrap-table.
html code:

### **<td** id="test"></td>

jquery codes:

$("#test").html(“task is finished”)

when i try to use the data-search="true" or sort to filter data,"task is finished" is disappeared

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by zgli2011** [comment]
i had try to translate the issue  to english below the horizontal line .Please have a look.

**Comment by zgli2011** [comment]
我已经用这种方法实现了我要的功能，只是效率会低一些
I have implemented the function I want in this way, but the efficiency will be lower.

$('#' + tableName).bootstrapTable("updateCell", {index : index_list.indexOf(sid), field : "server_status",value : "已停止"});
