### ISSUE TITLE
这个是国人开发的吧？为什么官方demo国内都访问不了

### ISSUE THREAD

**Issue by wangjia2016** [wenzhixin/bootstrap-table#3964]
这个是国人开发的吧？为什么官方demo国内都访问不了

**Comment by jiemoon** [comment]
@wangjia2016 可以访问，你要点击 菜单栏目里的 options 来选择要展示的 demo

**Comment by wangjia2016** [comment]
@jiemoon 所以说啊 就是这点不方便

**Comment by wangjia2016** [comment]
科学上网，访问也非常非常慢 慢到几乎打不开

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by feixiangsmile** [comment]
> Can you translate this issue to english, please?

He may don't  understand how to use the demo. And I think  it is the problem of his network.

**Comment by wenzhixin** [comment]
@wangjia2016 是部署在阿里云上的，主要是有些国外 cdn 被 qiang 了，后面慢慢改进下吧。
