### ISSUE TITLE
When multiple heads are used, height is set and content is not aligned.

### ISSUE THREAD

**Issue by userlm** [wenzhixin/bootstrap-table#3965]
When multiple heads are used, height is set and content is not aligned.

Example: http://jsfiddle.net/boz25c9k/10/

**Comment by UtechtDustin** [comment]
@djhvscf You labeled this issue as In progress, can give us an update for that ?

**Comment by djhvscf** [comment]
This is not in progress. This was labeled by projects feature. Removing label

**Comment by wenzhixin** [comment]
I found the problem. Because the same field(`IPN`) is used.
Before: https://live.bootstrap-table.com/code/wenzhixin/1411
After: https://live.bootstrap-table.com/code/wenzhixin/1412
