### ISSUE TITLE
Extension filter-control, do not set search field

### ISSUE THREAD

**Issue by TiedtTech** [wenzhixin/bootstrap-table#3966]
I added the filter-control extension.
My grid is configured below.

As the data comes from the server, the `data-query-params="parametrosDaConsulta"` is configured like this:

```
function parametrosDaConsulta(params) {

    console.log(params);

    return {
        filtroCampos: params.filter,
        itensPorPagina: params.limit,
        itensParaIgnorar: params.offset,
        filtro: params.search,
        orderna: params.sort,
        ordernaTipo: params.order,
        tipoPesquisa: $(this).attr("tipopesquisa"),
        registroPaiID: $("#" + $(this).attr("registropaiid")).val()
    }; 
};
```

My problem, when filtering the column, the plugin correctly sends the data filter parameter being `"field": "value"`.

However in the `search `parameter, the `value `of the field value is sent.

### My question

**How do I make the `filter-control` plugin not set the `search `value?**

### My table config

```
<table id="table"
       data-toggle="table"
       data-url="/Ajax/Grid/"
       data-side-pagination="server"
       data-pagination="true"
       data-page-list="[5, 10, 20, 50, 100, 200, 500]"
       data-search="true"
       data-filter-control="true"
       data-show-refresh="true"
       data-show-toggle="true"
       data-show-columns="true"
       data-query-params="parametrosDaConsulta"
       data-locale="pt-BR"
       data-search-on-enter-key="true"
       data-row-style="estiloDaLinha"
       data-toolbar="#exportarGrid"
       data-tipopesquisa="OperacaoPlanoLocalidade">
    <thead>
        <tr>
            <th data-field="OperacaoPlanoLocalidadeID" data-sortable="true" data-visible="false" data-width="96px">ID</th>
            <th data-field="Nome" data-width="288px" data-sortable="true" data-filter-control="select" data-filter-data="var:clientes" data-search-on-enter-key="true">Cliente</th>
            <th data-field="Plano" data-sortable="true">Plano</th>
            <th data-field="Localidade" data-sortable="true">Localidade</th>
            @Html.Partial(@MTSys.Lib.Constantes.gridPadraoCamposFixos)
            <th data-field="botoes" data-width="48px" data-registroid="OperacaoPlanoLocalidadeID" data-controller="OperacaoPlanoLocalidade" data-formatter="adicionarBotaoEdicao" data-niveldeacesso="@nivelDeAcesso"></th>
        </tr>
    </thead>
</table>
```

**Comment by mriddle** [comment]
Related: https://github.com/wenzhixin/bootstrap-table-examples/issues/316#issue-344604091

**Comment by mriddle** [comment]
It's due to [`onColumnSearch`](https://github.com/wenzhixin/bootstrap-table/blob/1.12.1/src/extensions/filter-control/bootstrap-table-filter-control.js#L634) calling  [`this.onSearch(event)`](https://github.com/wenzhixin/bootstrap-table/blob/1.12.1/src/extensions/filter-control/bootstrap-table-filter-control.js#L661). The `search` text is [set to the value](https://github.com/wenzhixin/bootstrap-table/blob/1.12.1/src/bootstrap-table.js#L1297) of the column you're filtering on.

You can hack it by changing the target with

```js
event.currentTarget = this.$toolbar.find('.search input')[0]
this.onSearch(event);
```

or by using `customSearch`

**Comment by mriddle** [comment]
Related: https://github.com/wenzhixin/bootstrap-table/issues/3015

**Comment by mriddle** [comment]
Related: https://github.com/wenzhixin/bootstrap-table/issues/2776

**Comment by Falseee** [comment]
Duplicate #2776
