### ISSUE TITLE
Set a page other than 1 when using searchText

### ISSUE THREAD

**Issue by garfieldthecat13** [wenzhixin/bootstrap-table#3974]
When initializing the bootstrap-table, if I set { searchText: "some value", pageNumber: 2 } using serverSide pagination, I always get page 1 back.

I am also using queryParamsType: custom.

Looking at the headers going to the server, all my other values that come from the params object in the queryParams function call have the initial values I set like page size, sorting, the searchText, etc. but the pageNumber is always 1.

If I do not set the searchText. I will get page 2 data back.

I am trying to return the user to a previous state of the page where they searched for a value, moved to page 2 and then drilled into some data. When they click back to this page, I need it to reload to page 2 of the searched data.

**Comment by garfieldthecat13** [comment]
http://jsfiddle.net/garfield13/0358djay/

**Comment by djhvscf** [comment]
Thanks @garfieldthecat13

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/pull/4123#issuecomment-456873116
