### ISSUE TITLE
after setting the table height, the header and content are misplaced.

### ISSUE THREAD

**Issue by luats** [wenzhixin/bootstrap-table#3976]
设置高度后(有滚动条),表头与内容错位

操作系统:win10
浏览器:360 9.1 极速模式
bootstrap table版本:1.12.1

操作一:按住键盘ctrl,通过鼠标滚轮不停的变化页面大小,中间会偶发性出现错位.
操作二:停止“操作一”的操作,刷新页面,也会出现错位的情况.

试过在resize事件中resetView,没有反馈正确的结果.

谢谢作者解答!

**Comment by luats** [comment]
360浏览器9.1 极速模式下,修改页面百分比为除了100%的其他情况,然后刷新,表格必定错位.

chrome  68.0.3440.106 中这个问题也能正常重现.

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by luats** [comment]
> Can you translate this issue to english, please?

Already translated, thank you.

**Comment by luats** [comment]
Anybody here?

**Comment by tjh-financial-com** [comment]
Seems like they don't know the solution, me too facing the same issue

**Comment by wenzhixin** [comment]
使用最新版本，这个问题应该解决了。
