### ISSUE TITLE
dynamic column headers

### ISSUE THREAD

**Issue by b1ueb0y** [wenzhixin/bootstrap-table#3977]
bootstrap-table need to define column headers name as follows,then load data from server through url.
 columns: [{
                    checkbox: true
                }, {
                    field: 'id',
                    title: 'id',
                    align: 'center',
                    valign: 'middle',
                    sortable: true
                }, {
                    field: 'name',
                    title: 'name',
                    align: 'center',
                    valign: 'middle'
                }]
there have any way we need't define column headers name?we just get column name from server side,because i have many tables need to show in web page,the tables column numbers and names is not fixed.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by b1ueb0y** [comment]
@djhvscf no need example

**Comment by jimgit** [comment]
You can provide the column definition per json data - [see the example here.](http://jsfiddle.net/wenyi/e3nk137y/25378/).  Note the colDef variable - contains the column definition.  This can come from your server dynamically with matching data json.

![image](https://user-images.githubusercontent.com/1921941/45551593-0941a380-b7f4-11e8-94b1-ce73e6f2550d.png)

**Comment by b1ueb0y** [comment]
@jimgit more than one ajax request is not the best solution.

**Comment by UtechtDustin** [comment]
> i want request data from remote site and pagination by bootstrap-table himself.

Then you can use the [url](https://bootstrap-table.com/docs/api/table-options/#url) option and set the [sidePagination](https://bootstrap-table.com/docs/api/table-options/#sidepagination) to `client`.

If you also want to use the [columns](https://bootstrap-table.com/docs/api/table-options/#columns) options (suggested by jimgit) with only one request then fetch you data (table data and column data) with your own ajax request and use only the [columns](https://bootstrap-table.com/docs/api/table-options/#columns)  option and the [data](https://bootstrap-table.com/docs/api/table-options/#data) option.

If i understood something wrong or you sill need help please reopen the issue.

**Comment by khm-developer** [comment]
Same dynamic column header raised here too [https://stackoverflow.com/questions/72852396/how-to-add-json-data-for-header-and-body-for-bootstraptable-using-javascript](url)
