### ISSUE TITLE
Detail View '+' button in not creating a new column in the table heading

### ISSUE THREAD

**Issue by jaydeepgiri** [wenzhixin/bootstrap-table#3978]
Hello, I am using the data-detail-view and data-detail-formatter in the table. Everything is working fine except the layout of the table header. the '**+**' symbol occupies the column of ID instead of creating a separate column for the '+' .

### '+' Detail View Button behaving in strange view

![issue](https://user-images.githubusercontent.com/14834122/45624435-f5be6300-baa7-11e8-9488-3af7283f1742.jpg)

Data of ID is under Registration Number column, data of Registration Number is under Make column and so on, the data of every column is shifted on the right side of the column.

Here is my code for the table

>< table class='table-striped' id='cars_list'
>                                         data-toggle="table"
>                                         data-url="get-list.php?table=cars"
>                                         data-side-pagination="server"
>                                         data-pagination="true"
> 					   data-detail-view="true"
> 					   data-detail-formatter="detailFormatter"
>                                        data-sort-name="id" data-sort-order="
> 					   data-query-params="queryParams_1"
> 					>

and the jquery code

> <script>
> function detailFormatter(index, row) {
>        var html = [];
>        $.each(row, function (key, value) {
> 		html.push('<p><b>' + key + ':</b> ' + value + '</p>');
> 	});
> 	return html.join('');
> }
> </script>

please help.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by jaydeepgiri** [comment]
I don't know why but it works fine in the jsFiddle. I included every JS & CSS i'm using in my code. here is the one sample example Fiddle [jsFiddle](http://jsfiddle.net/6xr53zsa/32/). If possible can you have look into my code i'll provide you the access to it.

**Comment by Falseee** [comment]
I close this issue because its old enough, if you still need help pls reopen the issue.

**Comment by UtechtDustin** [comment]
@prowler0305 
You have `data-detail_view="true"` instead of `data-detail-view="true"`.
