### ISSUE TITLE
dbl-click-cell.bs.table event does not work well when columns are hidden

### ISSUE THREAD

**Issue by gautierderuette** [wenzhixin/bootstrap-table#3979]
Hello,

The option show-columns is activated and a column is hidden.

When I use the dbl-click-cell.bs.table event, the data value sent does not correspond to the clicked cell. It happens like the column is not hidden. 

Here is an example : (click on the second or the third column, you will see the wrong column name in an alert box) 

https://jsfiddle.net/vuwdkn5f/1/

**Comment by djhvscf** [comment]
You need to use the latest version.

See this example:
https://jsfiddle.net/vuwdkn5f/2/

**Comment by gautierderuette** [comment]
Thank you sorry, for this.
