### ISSUE TITLE
.bootstrapTable('nextPage') will remove group effect by extension of group-by-v2 

### ISSUE THREAD

**Issue by erikking** [wenzhixin/bootstrap-table#3980]

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Falseee** [comment]
I close this issue because we got no response/example from you.
If you still need help pls reopen the issue and provide us a jsFiddle.
