### ISSUE TITLE
Cannot get onResizableResize parameter when using resizable extension.

### ISSUE THREAD

**Issue by david553030** [wenzhixin/bootstrap-table#3982]
Hi,
There is a function called onResizableResize .

 onResizableResize: function(e) {
    alert(e);
  }
 However , e is undefined.

Just like #3200

[jsfiddle]() - ([fiddle template](https://jsfiddle.net/david553030/u7mhdbt6/)).

Please advise. 
Thanks.

**Comment by djhvscf** [comment]
As you can see there is a new jquery plugin for this extension. See this:

https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/resizable
https://github.com/wenzhixin/bootstrap-table/commit/bd42ce6755f8ecf9924c7b830989db02bfc07dbb
