### ISSUE TITLE
表格的toolbar有问题，按钮高度不一致

### ISSUE THREAD

**Issue by ChikyChan** [wenzhixin/bootstrap-table#3983]
表格的toolbar工具栏有问题，没有下拉列表的会比有下拉列表的按钮矮，导致并存时高度不一致

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by ChikyChan** [comment]
> 
> 
> Can you translate this issue to english, please?

The toolbar buttons size is not the same. The Button that have the dropdown list is higher than the others have no dropdown list. It makes me that when I use the 2 kind of the toolbar buttons, it looks different because the hiegth of the button.

**Comment by wenzhixin** [comment]
没有出现该问题，有的话请提供 JSFiddle 例如。另外有可能是你的 HTML 没有定义：
`<!DOCTYPE html>`

**Comment by GuoHM** [comment]
wenzhixin your answer is correct!!! Thank you so much!!!
Change your <!DOCTYPE> into <!DOCTYPE html>
wenzhixin 是正解，非常感謝！！！

**Comment by GuoHM** [comment]
> 没有出现该问题，有的话请提供 JSFiddle 例如。另外有可能是你的 HTML 没有定义：
> `<!DOCTYPE html>`
這是正解，謝謝！
This is the correct answer,thank you!
