### ISSUE TITLE
Marking Rows as Selected Before Table Render

### ISSUE THREAD

**Issue by Division4Studios** [wenzhixin/bootstrap-table#3984]
I have a table.  I want to pre-check certain rows.  However when I add class="selected" to my <tr> or table row, upon loading the table in, Bootstrap-Table removes the class selected and unchecks it.  How can I preserve the initial checkbox selected, before the table loads?

**Comment by jimgit** [comment]
Use the api instead of directly setting classes.

![image](https://user-images.githubusercontent.com/1921941/45961768-f9407580-bfe4-11e8-8a4f-8d515a79fd6c.png)

You may want to call the method when the data has been returned using the 
![image](https://user-images.githubusercontent.com/1921941/45961932-5805ef00-bfe5-11e8-8baa-4de5c613eb68.png)


http://bootstrap-table.wenzhixin.net.cn/documentation/#events

You can also send the data via json and format the data as a checkbox - use the data-formatter,   this is handy when you have multiple checkboxes.

Post a jsfiddle of what you are trying to do.

**Comment by Division4Studios** [comment]
This is a good answer, but how would this work with Pagination, as I have thousands of rows and pagination only returns about10 or so, will using checkBy cycle through ALL of my rows or just the rows displayed in pagination.  The goal ultimately is to have the checked rows sort to the top upon load.

**Comment by jimgit** [comment]
Question:  does the checkbox need to persist in your server side?   If so, you can have a 1/0 yes/no field in the json and render it as a checkbox using the data-formatter.  When the user checks the checkbox,  you can send an ajax message with the row or value/key up to the server to save the value to the database/storage.

**Comment by Division4Studios** [comment]
No it doesn't have to.  The values that will be checked are stored in a text string, as more of them are checked or unchecked it manipulates that data string.  But I need to check some of those initial rows based off of that text string.

**Comment by jimgit** [comment]
If you are "building the table"  i.e. building all the html for the table yourself or on the server side and pushing via html,  you might want to consider separating the data from the html presentation.   Bootstrap table has client and server side processing.  Server side is good for 1000's of rows and showing the user just the page of some of the row.  [Here is an example.](http://jsfiddle.net/wenyi/4r6g4cfu/582/)

![image](https://user-images.githubusercontent.com/1921941/45969588-c48ae900-bff9-11e8-8449-4a81e3a68d32.png)

**Comment by Division4Studios** [comment]
I figured it out.  Thanks for all the help.  I stumbled upon a way to set row status.

`    var checkSum = 0;
    function checkedFormatter(value, row, index) {
        var snList = [];
        snList = document.getElementById("inputsn").value.split("|");
        snList.forEach(function (element) {
            var checkSN = ((row.sn).toString()).trim();
            if (checkSN == element) {
                checkSum = 1;
            }
        })
        if (checkSum == 1) {
            checkSum = 0;
            return {
                checked: true
            }
        }
        return value;
        

    }`
