### ISSUE TITLE
Highlight a particular page

### ISSUE THREAD

**Issue by arunsathya1309** [wenzhixin/bootstrap-table#3985]
I use pagination in bootstrap tables and it always highlights the current page, however is there an option to hightligh any given page. For example if there is competition going on and there are 100 games and the table has 10 entries per page. If the current game is 52, the page wud be six and i can highlight it, however if i navigate to earlier page, i want the option to highlight page #6 in addition to #5

**Comment by djhvscf** [comment]
This is not supported
