### ISSUE TITLE
Wrong rows selected using checkBy on filtered table

### ISSUE THREAD

**Issue by zsigusd** [wenzhixin/bootstrap-table#3986]
When using the filter-control filtering, the function checkBy does not select or selects wrong rows on the table.

If no filters are applied to the table, the checkBy function works great.
If there are filters applied, the checkBy is not selecting the desired row, even if it is on the filtered table

[jsfiddle](https://jsfiddle.net/e3nk137y/42442)

Steps to reproduce with the fiddle:
1. click on the "Select row with notDefaultId=3" button
2. the row with notDefaultId=3 selected.
3. undo selection
4. apply filter "B" on the "First" column
5. click on the "Select row with notDefaultId=3" button
6. no rows are selected

Another scenario:
1. click on the "Select row with notDefaultId=3" button
2. the row with notDefaultId=3 selected.
3. undo selection
4. apply filter "apple" on the "Third" column
5. click on the "Select row with notDefaultId=3" button
6. the row with notDefaultId=5 is selected

**Comment by Falseee** [comment]
Working example: https://jsfiddle.net/20ocaugw/2/
