### ISSUE TITLE
Should filter combination work or only last used is active?

### ISSUE THREAD

**Issue by djordjedjukic** [wenzhixin/bootstrap-table#3987]
Hi, 
I am trying to use filter control extension but it has wrong behavior for me. I tried on your example it's the same. 

https://jsfiddle.net/wenyi/e3nk137y/18165/

If I check number 3 in 'Second' column and orange in 'Third' column, result should be empty, but filter returns result from last used filter, not the combination. I found working example (working for my case) on codepen, but it's using first version of extension.
Here is example from code pen:
https://codepen.io/AurelieT/pen/JGxMgo

Is there any configuration for that, or some fast workaround?
Thank you, great job.

**Comment by Falseee** [comment]
The jsfiddle example works fine in the newest version.
