### ISSUE TITLE
formatter dynamic arguments from PHP foreach (read MySQL table column name)

### ISSUE THREAD

**Issue by bustersg** [wenzhixin/bootstrap-table#3991]
`<th class="text-center fixed-col-widths" data-sortable="true" data-field="storage_id | storage_label" data-formatter="input_text">storage_label</th>`

`function input_text(value, row, index){`
    `console.log(row.storage_id);`
    `console.log(row.storage_label);`
    `return '<input type="text" name="storage['+row.storage_id+']['+row.storage_label+']" class="form-control" value="'+row.storage_label+'">';
}`

Above works nicely.
However the 'storage_label' is dynamic input (mysql column name) from PHP.
If user extend the SQL table with new column 'abc', my PHP foreach will loop new <th> row
`<th class="text-center fixed-col-widths" data-sortable="true" data-field="storage_id | storage_label" data-formatter="input_text">storage_label</th>`
`<th class="text-center fixed-col-widths" data-sortable="true" data-field="storage_id | abc" data-formatter="input_text">abc</th>`

How do I make the function input_text such that it takes in whatever value that comes after storage_id | (read this data-column name)

`function input_text(value, row, index){`
    `console.log(row.storage_id);`
    `console.log(row.xxxxx);`
    `return '<input type="text" name="storage['+row.storage_id+']['+row.xxxxx+']" class="form-control" value="'+row.xxxxx+'">';
}`

where xxxxx can be any column name.

**Comment by Falseee** [comment]
Could you provide us an example of you php output and an example (jsfiddle) of your desired result?

**Comment by UtechtDustin** [comment]
I close the issue because we got no response/example from you within 7days.
If you still need help pls provide us an jsfiddle.
