### ISSUE TITLE
How to search one column for bootstrap table

### ISSUE THREAD

**Issue by doantutai** [wenzhixin/bootstrap-table#3993]
Hey, I want search one column for table.Present bootstrap table search multi column other.
Thanks you.

**Comment by jimgit** [comment]
Try the data-searchable="true" on the column of interest and false for the other columns

![image](https://user-images.githubusercontent.com/1921941/46165490-63ac1c80-c256-11e8-9a04-b02a56a24956.png)

**Comment by jimgit** [comment]
See[ this jsfiddle](http://jsfiddle.net/jimkennelly/uznb6k32/)  Note if you search for the get number "1" you will find it in the forks column - but not in the stars column.

**Comment by doantutai** [comment]
No No, It search for all column, I want search for one column,
