### ISSUE TITLE
Match entire string in select filter-control

### ISSUE THREAD

**Issue by davidmoremad** [wenzhixin/bootstrap-table#3995]
In filter-control of the "select" type, the entire string should be checked, not all cases which contains that string.

If you are trying to filter by "fruit" category, if you filter by "apple", you'll get two fruits: apple and pineapple.

https://jsfiddle.net/rktb9Lfh/

**Comment by djhvscf** [comment]
Please check the documentation: https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/filter-control#filterstrictsearch
