### ISSUE TITLE
Add footer summery for aggregation  

### ISSUE THREAD

**Issue by mojtabakaviani** [wenzhixin/bootstrap-table#4]
please add footer that can show aggregation such as count,sum,avg and others functions for and calculate with custom function

**Comment by Philoow** [comment]
Some news ?

**Comment by yonjah** [comment]
:+1:

**Comment by wenzhixin** [comment]
Thanks for @yonjah.
Docs: http://bootstrap-table.wenzhixin.net.cn/documentation/, example: http://jsfiddle.net/L6tm1tt3/

**Comment by Tatoo988** [comment]
I'm still having some issues with sumFormatter when because I'm getting a number like this: 2179286.8500000015 despite any of the values of that column is 2 digits only. how can I make it round to 2 digits only?

Regards
