### ISSUE TITLE
Preventing hidden selections from counting as selections

### ISSUE THREAD

**Issue by inktype** [wenzhixin/bootstrap-table#4002]
I am trying to return all visible selections. If something is "checked" but is not visible because a search filter has been applied, it will still return the hidden selection.

This functionality happens with both the below functions. From reading the description, I understood it should only happen with 'getAllSelections.'  

http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getSelections.html
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getAllSelections.html

Perhaps that is not the case. Even so, I tried to bypass that by using this:

`$('#data-table').bootstrapTable({
        onSearch: function () {
            $('#data-table').bootstrapTable('uncheckAll');
        }
    });`

But it doesn't work most of the time. I think what is happening is it will only uncheck the rowif the rowis visible. So if you apply a filter, then the hidden row is still selected.

I cannot tell if these interactions are intended or bugs. The description of the functions has me a little confused, sorry.

**Comment by jimgit** [comment]
I would join the data to the results of the getData which you CAN specify visible items,  if the items are in the array of selected items AND are visible, that would be the results you want.

![image](https://user-images.githubusercontent.com/1921941/46540012-ba7cac00-c87d-11e8-9f1c-c3412fa0b608.png)

**Comment by DKanarsky** [comment]
The same thing.
