### ISSUE TITLE
onDblClickRow does not work on ios chrome or safari as is

### ISSUE THREAD

**Issue by rip057** [wenzhixin/bootstrap-table#4003]
example of table implementation simplified with key components... DOES NOT WORK.... i dont have a valid url to share with you just insert any kind of random data if you will, not even sure if the head is correct as i roll everything into a nice app.js through node.js...

    <!DOCTYPE html>
    <html>
    <head>
    <title>check/uncheck</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.csss">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.js"></script>
    </head>
    <body>
    	<div class="col-12 px-0" name="lists_elementlist" id="lists_elementlist">
		<table id="elementlist">
		</table>
	</div>
	<script>
		var elementlist = $('#elementlist');
		elementlist.bootstrapTable({
			showHeader: true,
			clickToSelect: true,
			url: '/url/' + table_id  ,
			queryParamsType: '',
			queryParams: function(params) {
				return {
					pagenumber: params.pageNumber,
					pagesize: params.pageSize,
				        order: params.sortOrder,
					sort: params.sortName,
				}
			},
			showRefresh: true,
			cache: false,
			pagination: true,
			pageNumber: 1,
			pageSize: 50,
			pageList: [50,100,250,500],
			sidePagination: 'server',
			sortable: true,
			onDblClickRow:  function (row, $element,field) {
				window.location.href = location.protocol + "//" + location.hostname + "/" + row.elementid;
			},
			columns: [{field: "elementid",
				title: "elementid",
				align: "center",
				halign: "center",
				valign: "middle",
				sortable: true,
				formatter: function formatter(value,row,index,field) {
					if (value !== null) { 
						var elementid_linked = row.elementid; 
						var modifiedcolumndata = "<a href=\"https://domain.org/link/" + elementid + "\"></a>"; 
						return modifiedcolumndata;
					};
				},
		        }],
		});
	</script>
    </body>
    </html>

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by rip057** [comment]
ive figured out to fix this on ios just use onclick with an addition to the bootstraptable as such

    onClickRow: function (row,$element,field) {
            if (touchtime == 0) {
                // set first click
                touchtime = new Date().getTime();
                onclickedrow = row.id;
            } else {
                // compare first click to this click and see if they occurred within double click threshold
                if ((((new Date().getTime()) - touchtime) < 800) && (onclickrow === row.id)) {
                    window.location.href = location.protocol + "//" + location.hostname + "/" + row.elementid;
                    touchtime = 0;
                    onclickedrow = 0;
                } else {
                    // not a double click so set as a new first click
                    touchtime = new Date().getTime();
                    onclickedrow = row.id;
                }
            }
        },
