### ISSUE TITLE
Export Bug with data-filter-control="select"

### ISSUE THREAD

**Issue by Division4Studios** [wenzhixin/bootstrap-table#4005]
Having Select Filtering on a Column when exporting will cause every option in the select filter to be placed in the title header for the column.

Example Can be seen Here in Date Column when exporting to MS-Excel.

https://codepen.io/jahid-webdev/pen/ObegKN

**Comment by timoline** [comment]
any progress on this one?

**Comment by timoline** [comment]
@djhvscf 
Hi, can you please have a look on this one, for us this is a really annoying bug

thanks in advance

**Comment by hhurz** [comment]
FYI: This issue should be fixed in v1.10.5 of the tableExport.jquery.plugin and should be available as soon as this version is adopted by BT.
@djhvscf, @wenzhixin; The problem would reapear as soon as the class name of the table cells containing fillter controls (currently fht-cell) changes.

**Comment by UtechtDustin** [comment]
@hhurz thank you for the information, we already saw its fixed (#4431).
