### ISSUE TITLE
Set ID for search field

### ISSUE THREAD

**Issue by basementmedia2** [wenzhixin/bootstrap-table#4007]
Good morning,

i've got just a little question and hope that this is the correct place to ask for:
If i create a new table using for example....
```
<table 
    id="test_table"
    data-toggle="table"
    data-search="true"
    data-url="ajax_test.php"
    data-side-pagination="client"
    data-pagination="true"
    data-show-toggle="true"
>
<thead>
    <tr>
        <th data-field="field_one">One</th>
        <th data-field="field_two">Two</th> 
</thead>
</table>
```
...i get a result table which has a field for searching (because i have set data-search to "true").
The generated HTML is
```
<input class="form-control" placeholder="suchen..." type="text">
```
Is it possible, to give the search field an ID so that i get
```
<input class="form-control" placeholder="suchen..." type="text" id="my_custom_id">
```

Best regards
Daniel

**Comment by jimgit** [comment]
What is your goal of having the id of the search box?   If the purpose is to get the text inside the search box, you can use the onSearch event to get the search text. [ See this JSFIDDLE
](http://jsfiddle.net/jimkennelly/ygkq4h5c/)


![image](https://user-images.githubusercontent.com/1921941/46804622-b7c00200-cd28-11e8-94d0-1be980c42532.png)


Note: this example fires on every keystroke - you can change the search to trigger on enter key by using


![image](https://user-images.githubusercontent.com/1921941/46804690-e6d67380-cd28-11e8-88b8-b5de75ac389d.png)

**Comment by basementmedia2** [comment]
Hi,
A co-worker of mine needs the ID to directly enter a value in the field with a Microsoft Script (I think ACCESS VBA). Do not ask me why or if that makes sense. He just needs some ID so that his script can find the field in the browser.

Best regards
Daniel

**Comment by jimgit** [comment]
Thank you for explaining.   Just wanted to make sure you couldn't accomplish with api.   [Try this JSFIDDLE - should find the text box for search and assign an id.](http://jsfiddle.net/jimkennelly/b1omtgj3/)

![image](https://user-images.githubusercontent.com/1921941/46869961-f91ce400-cdf2-11e8-9551-dbf843a67934.png)

**Comment by basementmedia2** [comment]
Perfect Thanx! Excactly what i wanted.
