### ISSUE TITLE
Rewrite styles

### ISSUE THREAD

**Issue by deser** [wenzhixin/bootstrap-table#4009]
Helllo,
currently this table is styling html elements which is very bad practice (like this `.fixed-table-container thead th`). Is there a plan to move away from that?

**Comment by djhvscf** [comment]
Could you let us know what is the best practice? Thanks

**Comment by deser** [comment]
Sure, but let me describe the issue first:
Styling html elements is bad due to cascading effect. For example, bootstrap-table allows using inside inline editors. Let's imagine that I use datepicker which droppanel of which contains <table>\<th>\<td>\etc... (https://github.com/uxsolutions/bootstrap-datepicker)

Then, due to cascading effect, styles of datepicker would be broken. 

Solution: style elements of table via css classes with namespace (.bt-cell\.bt-row\etc...) as mature grids do (like ag-grid)

**Comment by djhvscf** [comment]
Got it @deser . Are you planning to work on this?

**Comment by deser** [comment]
Not in the nearest feature :(

**Comment by wenzhixin** [comment]
In the latest version, we use `scss` instead of `css` and use .bootstrap-table as the root namespace. 

If the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
