### ISSUE TITLE
Saving input data while server side pagination ?

### ISSUE THREAD

**Issue by joicemjoseph** [wenzhixin/bootstrap-table#401]
Hi, 
when using server side pagination, how can i save data while paginating from one page to another ?

**Comment by wenzhixin** [comment]
Save data? Sorry, I am not very clear, do you mean how to get the loaded data by `getData` method?

**Comment by joicemjoseph** [comment]
thank you for your comment. I meant was how to save fields while I am using serverside pagination than loading complete json file. ?

**Comment by wenzhixin** [comment]
I am sorry, still do not understand.

**Comment by joicemjoseph** [comment]
Thank you for comments.. Let me check once more..

**Comment by wenzhixin** [comment]
Have you solved your problem? Close this issue.
