### ISSUE TITLE
Pagination with the 'nextpage' Token

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#4012]
Is there any way we can paginate the result using `nextpage` token? As most of the business are shifting to `NoSQL` and token based pagination is the need to display the data in tables.

Example responses : 

```
{
  "total": 10,
  "limit": 2,
  "nextpage": "asdjflkasyiuoqweruoncvlasdfyaiosy",
  "returned": 2,
  "result": [
    {
      "id": 1,
      "name": "Row 1",
      "created_at": "2018-09-13T09:34:23"
    },
   {
      "id": 2,
      "name": "Row 2",
      "created_at": "2018-09-13T09:34:23"
    }
]
}
```

What I need to do is use the `nextpage` token value as querystring to fetch 2nd page result and so on. So, just the `offset` needs to be replaced with nextpage I think? Please let me know if there is any working example(I can't find) or plugin already

**Comment by vickyrathee** [comment]
@wenzhixin Any suggestion will be highly appreciated.

**Comment by Falseee** [comment]
Could be a good feature for NoSql databases @wenzhixin @djhvscf.

**Comment by vickyrathee** [comment]
👍

**Comment by wenzhixin** [comment]
Save nextpage in responseHandler first, then send it in queryParams. Can this solve the problem?

**Comment by wenzhixin** [comment]
Any update?

**Comment by Falseee** [comment]
I close this issue because we got no response/example within 7 days.
