### ISSUE TITLE
Dependent Dynamic filter/chain filter using bootstrap table

### ISSUE THREAD

**Issue by divyajyothi1** [wenzhixin/bootstrap-table#4014]
link: https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=data-control-filter.
 
dependent data control filter using bootstrap table jquery not working.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Falseee** [comment]
I close this issue because we got no response/example from you.
If you still need help pls reopen the issue and provide us a jsFiddle.
