### ISSUE TITLE
Append records to existing table.

### ISSUE THREAD

**Issue by rajahmad-mulani** [wenzhixin/bootstrap-table#4016]
Hi - this is about a bootstrap table implementation, On page load we loaded 100 records (per page 10 records). When we reach 10th page i.e. 100th record, we want to append next 100 records to the existing table. 
![pagechangeevent](https://user-images.githubusercontent.com/42235285/47077308-48fa1180-d21e-11e8-9d36-65dbc706988a.png)

plz suggest on how we can achieve solution to this problem.

**Comment by djhvscf** [comment]
@rajahmad-mulani please see if @jimgit 's answer works for you
