### ISSUE TITLE
How can I get a footerFormatter - footerFormatter ?

### ISSUE THREAD

**Issue by shengkinng** [wenzhixin/bootstrap-table#4017]
### columns

```
columns:[ //欄位設定
		{checkbox:true, title:'#', align:'center'},
		{title: "序號", align:'center',formatter: function(value, row, index) {return index + 1;}},
	        {field:'t_monny', title:'金額', align:'center', width:60, visible:true, sortable:true,sortable: true,
	        footerFormatter: sumFormatter,},
		{field:'t_discount', title:'折扣', align:'center', width:50, visible:true, sortable:true},
	       {field:'t_sr', title:'SR', align:'center', width:60, visible:true, sortable:true,sortable: true,
		footerFormatter: sumFormatter},
	       {field:'t_fon', title:'狀態', align:'center', width:60, visible:true, sortable:true,
		 footerFormatter: subTotal},  
            ],
```

### footerFormatter: sumFormatter

```
function sumFormatter(data) {
                var field = this.field;
                var total_sum = data.reduce(function(sum, row) {
                        console.log(sum);
                    return (sum) + (parseInt(row[field]) || 0);
                }, 0);
                return total_sum;
};
```

```
 function subTotal(value,data,row){
    // How to achieve footer addition and subtraction here?
 };
```

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by shengkinng** [comment]
I don't know how to express it....

**Comment by shengkinng** [comment]
@djhvscf 
![47011690-17793b80-d175-11e8-9153-34552ec58993](https://user-images.githubusercontent.com/40712030/47287194-0a9c9200-d624-11e8-892d-18c0ce67934c.png)

Below footer

![2018-10-22_180052](https://user-images.githubusercontent.com/40712030/47287324-6f57ec80-d624-11e8-9847-3a68834cdfe7.png)

4549 - 1150 =??

**Comment by shengkinng** [comment]
`
	 function sumFormatter1(data) {
                var field = this.field;

                var total_sum = data.reduce(function(sum, row) {
                    return (sum) + (parseInt(row[field]) || 0);
                }, 0);
                return '<span id="total1" rel="' + total_sum +'">' + total_sum + '</span>' ;
            };

	 function sumFormatter2(data) {
                var field = this.field;

                var total_sum = data.reduce(function(sum, row) {
                    return (sum) + (parseInt(row[field]) || 0);
                }, 0);
                return '<span id="total2" rel="' + total_sum +'">' + total_sum + '</span>';
            };

function sumFormatter3(){
                var  na = $('#total1').attr("rel");
		        var  nb = $('#total2').attr("rel");
		        var  nc = na - nb;
                return '<span id="total">' + na + '</span>';
            };`

**Comment by wenzhixin** [comment]
```js
function sumFormatter1(data) {
  // ...
  return sum
}

function sumFormatter2(data) {
  // ...
  return sum
}

function sumFormatter3(data) {
  sumFormatter1(data) - sumFormatter2(data)
}
```
