### ISSUE TITLE
1.12.1分页和不分页两种情况下数据格式问题

### ISSUE THREAD

**Issue by zhoujun165** [wenzhixin/bootstrap-table#4018]
分页情况下要求服务端返回数据格式为 {rows:[],total:123}，
不分页情况下要求数据格式为：[]，
旧版本貌似不是这样的。为什么要做这样的改变呢？导致旧版本升级后就出问题了。

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
一直都是两种格式，不过不是你说的分页不分页的问题，而是分页类型的问题：
`sidePagination`：设置在哪里进行分页，可选值为 'client' 或者 'server'。
client 的话就需要 `[]`
server 的话需要 `{rows:[],total:123}`
