### ISSUE TITLE
ReorderColumns is not working on table

### ISSUE THREAD

**Issue by 123lyf123** [wenzhixin/bootstrap-table#4019]
I followed the steps for this extension which i found here:
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/reorder-columns
Using frame：JeePlus

This is the first step： Added the bootstrap-table-reorder-columns plugin
plugin vision:
   bootstrap-table-reorder-columns v1.1.0
   jquery-ui v1.11.4
   jquery.dragtable v2.0.15
  dragtable.css v2.0.14

`<link href="${ctxStatic}/plugin/bootstrapTable/extensions/reorder-columns/dragtable.css" rel="stylesheet" />
<link href="${ctxStatic}/plugin/bootstrapTable/bootstrap-table.css" rel="stylesheet" />

<script src="${ctxStatic}/plugin/bootstrap/bootstrap.js"></script>
<script src="${ctxStatic}/plugin/bootstrapTable/bootstrap-table.js"></script>
<script src="${ctxStatic}/plugin/bootstrapTable/bootstrap-table-zh-CN.js"></script> 
<script src="${ctxStatic}/plugin/bootstrapTable/bootstrap-table-contextmenu.js"></script> 
<script src="${ctxStatic}/plugin/bootstrapTable/bootstrap-table-export.js"></script> 
<script src="${ctxStatic}/plugin/bootstrapTable/tableExport.js"></script> 

<script src="${ctxStatic}/plugin/bootstrapTable/extensions/reorder-columns/bootstrap-table-reorder-columns.js"></script>
<script src="${ctxStatic}/plugin/jquery-ui/jquery-ui.js" type="text/javascript"></script>
<script src="${ctxStatic}/plugin/bootstrapTable/extensions/reorder-columns/jquery.dragtable.js" type="text/javascript"></script>`

This is the second step： jsp code
`<table id="bdPsndocTable" toolbar="#toolbar"></table>`

This is the third step：Initialization
`$(document).ready(function() {
	$('#bdPsndocTable').bootstrapTable({
	        ...
	        reorderableColumns: "true",
		...
	});
}`

But it can be dragged, but not sorted.

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by Falseee** [comment]
I close this issue because we got no response/example from you.
If you still need help pls reopen the issue and provide us a jsFiddle.
