### ISSUE TITLE
It is error when adding  bootstrap-table-filter-control.js 

### ISSUE THREAD

**Issue by 123lyf123** [wenzhixin/bootstrap-table#4020]
Using frame: JeePlus
It is error when adding  bootstrap-table-filter-control.js .
error messege: 
`Uncaught TypeError: Cannot read property '0' of undefined
    at Number.<anonymous> (bootstrap-table-filter-control.js:198)
    at Function.each (vendor.js?timestamp=20181006:2)
    at initFilterSelectControls (bootstrap-table-filter-control.js:197)
    at BootstrapTable.initBody (bootstrap-table-filter-control.js:571)
    at BootstrapTable.init (bootstrap-table.js:511)
    at BootstrapTable.init (bootstrap-table-filter.js:19)
    at BootstrapTable.init (bootstrap-table-filter-control.js:534)
    at new BootstrapTable (bootstrap-table.js:235)
    at HTMLTableElement.<anonymous> (bootstrap-table.js:2677)
    at Function.each (vendor.js?timestamp=20181006:2)
`

This is the first step： plugin JS files
`<script src="${ctxStatic}/plugin/bootstrapTable/extensions/filter-control/bootstrap-table-filter-control.js"></script>`

This is the second step： JSP code
`<table id="bdPsndocTable" toolbar="#toolbar"></table>`

This is the third step： Initialization
`columns: [{
    checkbox: true 
  },{
    field: 'empno',
    title: '员工编号',
    sortable: true,
    filterControl:"input",
    formatter:function(value, row , index){
      return "<a href='${ctx}/hr/bd/bdPsndoc/form?id="+row.id+"'>"+value+"</a>";
    }
  },{
    field: 'lastname',
    title: '姓名',
    sortable: true,
    filterControl:"input"
  }
]`

Is there any step wrong?

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by 123lyf123** [comment]
> Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

[this is my sources code URL]( https://github.com/123lyf123/my-test-code/tree/master)

**Comment by 123lyf123** [comment]
> Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!



> Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

this is my sources code: [https://github.com/123lyf123/my-test-code](https://github.com/123lyf123/my-test-code)

**Comment by jimgit** [comment]
We ask that ### you take the time,  **as we take the time to help you,** to setup the jsfiddle so we have a running example of your problem.  Do you expect volunteers to setup the testing required to demonstrate your problem?

**Comment by djhvscf** [comment]
Thanks @jimgit 

@123lyf123 please provide an update

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
