### ISSUE TITLE
Keep selected row after refresh or updating cell or row

### ISSUE THREAD

**Issue by r2d2h2o** [wenzhixin/bootstrap-table#4021]
After clicking a row I populate form fields with the values of the table. The row gets highlighted using the following code:
$('#table').on('click-row.bs.table', function (e, row, $element) {
        $('.success').removeClass('success');
        $($element).addClass('success');
});

After changing values in the form fields and storing the new values in the database I update the table by using this code:
$('#table).bootstrapTable('refresh', {url: dataurl, silent: true});

This works, however the selection gets lost and therefore I can't use this function to get the data from the selected row:
function getSelectedRow () {
    var index = $('#table').find('tr.success').data('index');
    return $('#table').bootstrapTable('getData')[index];
}

I tried to remember the selected index with the following code:
var selectedIndex=$('#table').find('tr.success').data('index');

Trying to select and highlight the row with the following code does not work:
$('#table.rows['+selectedIndex+']').addClass('success');
$('#table.rows['+selectedIndex+']').addClass('selected');

Any ideas?

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/index.html#issues/563.html
