### ISSUE TITLE
New option: Pagination index number

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4023]
I'm using your script to a website that users are using smartphone.
In some case, we are lot's data to showing and we are using the pagination option.
But, in some smartphone with small resolution, the pagination view is bad because is too large:
![image](https://user-images.githubusercontent.com/14294794/47265622-16585d80-d52b-11e8-8a91-c3f8daeae4d2.png)
Can you create an option to indicate the number of option to see to the pagination view?
For example if i've an option and i indicate the number 4, the pagination will return this view:
![image](https://user-images.githubusercontent.com/14294794/47265635-5e778000-d52b-11e8-9b6e-65fda04c54a1.png)
If I indicate to the option the number 2, the pagination will return this view:
![image](https://user-images.githubusercontent.com/14294794/47265642-8535b680-d52b-11e8-808e-72ed34e96442.png)

Or, another posibilities, the pagination option is calculate with the width of screen.

Thank you so much.

**Comment by djhvscf** [comment]
This is added to latest release [1.13.2](https://github.com/wenzhixin/bootstrap-table/releases/tag/1.13.2)
