### ISSUE TITLE
Hiding and displaying columns when using the Fixed Column Option clones the Fixed Column over and over

### ISSUE THREAD

**Issue by dskilken** [wenzhixin/bootstrap-table#4025]
When using Fixed Column Option, if you hide and display columns, the Fixed Column is replicated in the DOM each time.   After a while, the table becomes huge and really slows down.  Seems to be a problem with the initHeader function.

**Comment by dskilken** [comment]
Think I have figured out this bug.  In the Fixed Column Code, you are redefining initHeader.  Inside this function, you call this.InitFixedColumns(); every time you initialize the Header.  This causes it to clone the fixed column every time the header is initialized which happens every time you display or hide a column.      I added a variable outside the function:
var executed = false;

Inside the BootstrapTable.prototype.initHeader = function () code, I bracket the initFixedColumns with a test to make sure it is only initialized once:

     if (!executed){
        executed = true;
        this.initFixedColumns();
         }


Resulting code:   
var executed = false;
    BootstrapTable.prototype.initHeader = function () {
        _initHeader.apply(this, Array.prototype.slice.apply(arguments));

        if (!this.options.fixedColumns) {
            return;
        }
        if (!executed){
        executed = true;
        this.initFixedColumns();
         }
        var that = this, $trs = this.$header.find('tr').clone();
        $trs.each(function () {
            $(this).find('th:gt(' + that.options.fixedNumber + ')').remove();
        });
        this.$fixedHeaderColumns.html('').append($trs); 
    };

**Comment by wenzhixin** [comment]
Fixed in the latest version.
