### ISSUE TITLE
getCookies method

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4027]
How can I use the method getCookies of bootstrap-table-cookie.js extension, to get saved cookies??

**Comment by jimgit** [comment]
[http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html](url)

**Comment by manukieli** [comment]
The link you have publish have no result.

**Comment by jimgit** [comment]
Sorry - try this link [http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html](url)

**Comment by jimgit** [comment]
The code for that page is  here : [https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/cookie.html](https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/cookie.html)

**Comment by manukieli** [comment]
Thanks for you comment, but I don't want to configure cookie (because I had did done yet).
I want to get the cookie data.
This URL has resolve my issue: https://github.com/wenzhixin/bootstrap-table/issues/2238
