### ISSUE TITLE
onResetView vs 'reset-view.bs.table'

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4028]
When I use this code<br>`$('#my_table').bootstrapTable({
        url: "data.json",
        onResetView: function (evt) {
            console.log(evt);
        }
    });`
 The console log result is "undefined".
But when I use this code<br>`$('#my_table').bootstrapTable({
        url: "data.json"
    }).on('reset-view.bs.table', function (evt) {
        console.log(evt);
    });`
The console log result give the data of the "evt" variable.
Why they is this diference???

**Comment by jimgit** [comment]
Can you submit a jsfiddle to show this?  [Here are some jsfiddle examples to use as a template](http://bootstrap-table.wenzhixin.net.cn/examples/)

**Comment by manukieli** [comment]
You can view the example with this URL: https://jsfiddle.net/e3nk137y/42970/

**Comment by wenzhixin** [comment]
Please check out the documentation:
https://bootstrap-table.wenzhixin.net.cn/docs/api/events/
https://bootstrap-table.wenzhixin.net.cn/docs/faq/
