### ISSUE TITLE
Fix postion of table footer <tfoot> ?

### ISSUE THREAD

**Issue by yusiwen** [wenzhixin/bootstrap-table#403]
Sorry to bother, but I've got a problem I can't solve by my own:

I created a table like:

```html
<table id='resultTable'>
<thead>
  <tr>
     <th data-field="field1">Field1</th>
     <th data-field="field2">Field2</th>
     <th data-field="field3">Field3</th>
  </tr>
</thead>
<tfoot>
</tfoot>
</table>
```

Then, I load this table with data from ajax call:
```js
var array = data.responseData;
$('#resultTable').bootstrapTable('load', array);
```
And create the tfoot row with:
```js
var row = $("<tr />");
$("#resultTable tfoot").append(row);
row.append("<td>Count</td>");
row.append("<td></td>");
row.append("<td>" + data.summary + "</td>");
```
The table looks fine, but the table footer part can't stay fixed like table header, when scrolled down/up, the footer part is treated like tbody part.

Can you tell me how to make its position fixed, and only scroll within tbody.

Thx.

**Comment by wenzhixin** [comment]
referenced to #4: need to add tfoot feature of Bootstrap Table.

**Comment by wenzhixin** [comment]
Docs: http://bootstrap-table.wenzhixin.net.cn/documentation/, example: http://jsfiddle.net/L6tm1tt3/
