### ISSUE TITLE
Multiple editables in a cell

### ISSUE THREAD

**Issue by mtaylor091** [wenzhixin/bootstrap-table#4030]
I want to have a cell with a bunch of editable options. In my case, I have 3 note types and I want to have a cell called Notes with 3 icons that launch the popup textarea editable. 

Currently I don't see a way to provide multiple editable options when I am building the columns. 

Also, I am building the table by providing it a data array and just the headers so I dont have access to the contents in the TR if that makes sense.

**Comment by jimgit** [comment]
Look at the data formatter to setup icons and run your edit logic.  [See this JSFiddle to get started.](http://jsfiddle.net/wenyi/e3nk137y/21/)

**Comment by mtaylor091** [comment]
Thanks for the reply. I can do icons and formatting but currently I cannot create 2 editables in a single cell.

**Comment by UtechtDustin** [comment]
I'm not sure if this should be a feature of the editable extension, this feature could be implemented easy by @mtaylor091 himself.
What do you think @wenzhixin @djhvscf  ?

**Comment by wenzhixin** [comment]
Not considered as a feature, multiple editables in a cell I suggest using the form to edit.
