### ISSUE TITLE
there is a mistake in this line, so the toggle icon does not appear. the correction this.options.icons.toggleOff

### ISSUE THREAD

**Issue by Ghadeeres** [wenzhixin/bootstrap-table#4031]
https://github.com/wenzhixin/bootstrap-table/blob/701492f1378561f527b918c9228d2c1b0fa99c66/dist/bootstrap-table.js#L1169

**Comment by jimgit** [comment]
Are you talking about the SHOW-TOGGLE ? 

![image](https://user-images.githubusercontent.com/1921941/47720067-01f71d80-dc1b-11e8-9cd5-bf2bfe3c8c6e.png)


[See this JSFIDDLE - shows a toggle icon](http://jsfiddle.net/jimkennelly/9qvedrn0/)


![image](https://user-images.githubusercontent.com/1921941/47720023-eab83000-dc1a-11e8-9e74-1697b0ba164e.png)

**Comment by Ghadeeres** [comment]
No this problem is just in Bootstrap 4
I button comes without <i class="fa fa-toggle-off" />

![1](https://user-images.githubusercontent.com/15316476/47731996-14398180-dc44-11e8-980e-2d30ae96931f.JPG)
 I changed "toggle" to "toggleOff" it works fine
![2](https://user-images.githubusercontent.com/15316476/47732084-3501d700-dc44-11e8-8840-f5ec3bb45489.JPG)

**Comment by wenzhixin** [comment]
Fixed in v1.12.2
