### ISSUE TITLE
Export negative values without the quote at the beginning

### ISSUE THREAD

**Issue by madmanblues** [wenzhixin/bootstrap-table#4032]
When I export to excel or CSV a table with negative values on some fields, those fields start on the exported file with a quote.

In this cases I would have expected to have just the value with the minus and not the quote.

Load data on a table where values are negative and positive
Export the table on CSV or Excel
Open the exported file (negative values have a quote)

![image](https://user-images.githubusercontent.com/7707578/47802412-7a9bce00-dd30-11e8-964e-9064a895c7c7.png)

Notice the quote before -526 at row 1 and -150 at row 2

I've modified an existing JSFiddle with negative values http://jsfiddle.net/wenyi/e3nk137y/3365/

How can I export the data keeping negative values as numerical (without the quote)?

Thanks

**Comment by wenzhixin** [comment]
Tested your jsfiddle and I think this problem fixed in the latest version.

**Comment by JEkedorff** [comment]
I hade the same problem, even with the latest version 1.14.1. I found that it was the 'preventInjection' in tableExport.jquery.plugin that caused it. Disabled that feature by adding below to the init of my Bootstrap table solved it.
`exportOptions: {preventInjection: false}`

**Comment by beautah** [comment]
> I hade the same problem, even with the latest version 1.14.1. I found that it was the 'preventInjection' in tableExport.jquery.plugin that caused it. Disabled that feature by adding below to the init of my Bootstrap table solved it. `exportOptions: {preventInjection: false}`

This is still the case as of 10/5/21, thanks! was driving me nuts
