### ISSUE TITLE
Cookie + Filter Control lost select option on refresh browser

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4033]
I'm using:
bootstrap-table.js v1.12.1
bootstrap-table-filter-control.js v2.1.3
bootstrap-table-cookie v.1.2.3

I've the cookie active for the filter control and some field are using data-filter-control="select"
When I filter with the select, the filter is working well, but when I refresh the browser, the filter is applied correctly with the cookie data. But the select field is not showing data.

![select lost](https://user-images.githubusercontent.com/14294794/47853192-3535da00-ddde-11e8-8a8e-ac7273c1c663.gif)

To resolve this issue, to the file bootstrap-table-cookie.js, I've replace the line 185-187 with this code
`                            if (cookie.text !== '') {
                                $(element).val(cookie.text);
                                cachedFilters[cookie.field] = cookie.text;
                            }`

to this lines:
`                            if (cookie.text !== '' && $(element).is('input')) {
                                $(element).val(cookie.text);
                                cachedFilters[cookie.field] = cookie.text;
                            }else if(cookie.text !== '' && $(element).is('select')){
                                $(element).append($('<option>', {value: cookie.text, text: cookie.text}));
                                $(element).val(cookie.text);
                                cachedFilters[cookie.field] = cookie.text;
                            }`

And now is working well.
View the result:
![select not lost](https://user-images.githubusercontent.com/14294794/47853306-9b226180-ddde-11e8-9572-1775ae319830.gif)

To this if: `if(cookie.text !== '' && $(element).is('select'))`
If I apply this `$(element).val(cookie.text);` and return it to console.log, the value is null.

**Comment by jimgit** [comment]
What tool are you using for the screen video?  Very helpful.

**Comment by manukieli** [comment]
I'm using Camtasia and save to Gif.

**Comment by manukieli** [comment]
This issue persist with bootstrap-table version 1.13.5
And I resolve it with this same solution describe in the first post.

**Comment by wenzhixin** [comment]
PR is welcome.

**Comment by UtechtDustin** [comment]
#2624

**Comment by steinbachio** [comment]
This is neither duplicate nor is it resolved.
The Solution of manukieli is working.
I am working with `data-filter-data="url:/foo/bar/values"`
