### ISSUE TITLE
Can you please check this stackoverflow question? Can this be achieved?

### ISSUE THREAD

**Issue by rakeshshubhu** [wenzhixin/bootstrap-table#4034]
https://stackoverflow.com/questions/53103095/bootstrap-table-im-unable-to-achieve-give-background-to-first-of-the-rows-with/53104999#53104999

**Comment by jimgit** [comment]
Checkout the cell style examples on the documentation page.   If that doesn't work, post a JSFIDDLE example.

**Comment by rakeshshubhu** [comment]
already check that out.. Its kind of limited to its use. Just wanted to ask if there is another better option

**Comment by jimgit** [comment]
Post a jsfiddle and you will get help.

**Comment by wenzhixin** [comment]
Close this issue because there are answers in StackOverflow if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
