### ISSUE TITLE
When reordering columns they revert back to original order

### ISSUE THREAD

**Issue by cbielich** [wenzhixin/bootstrap-table#4035]
I was able to get the plugin to work. I can click on a column and drag it, but when I let go of the column it just jumps back to the original position.

What's weird is that even your example page here does the same thing. Am I missing something as to the functionality of this extension? It is my understanding that I should be able to reorder the columns.

http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-columns.html

**Comment by cbielich** [comment]
I figured it out. Seems like after the reorder you have to re-call the funtion like this

`        onLoadSuccess: function() {
            $table.on('all.bs.table', function (event) {
				$('#table-javascript').dragtable('destroy').dragtable({});
            });
        },
`

**Comment by 123liuyu123** [comment]
> 我想到了。似乎在重新排序之后你必须像这样重新调用这个函数
> 
> `onLoadSuccess：function（）{
> 
> ```
>         $table.on('all.bs.table', function (event) {
> 
> 			$('#table-javascript').dragtable('destroy').dragtable({});
> 
>         });
> 
>     },`
> ```
Hello, we are the same question. I added your code and it did work, but in case of a large number of pages, it would be confusing to click on the next page and drag the table header and the following column. Would you like to know where this code is added?Is here?
`<table id="table"
           data-show-columns="true"
           data-search="true"
           data-show-toggle="true"
           data-pagination="true"
           data-reorderable-columns="true">
        <thead>
        <tr>
            <th data-field="ID" data-sortable="true">ID</th>
            <th data-field="Item Name" data-sortable="true">Item Name</th>
            <th data-field="Item Price" data-sortable="true">Item Price</th>
        </tr>
        </thead>
    </table>

    <script type="text/javascript">
    $(function () {
    $table = $('#table');
    $table.bootstrapTable({
        pageSize: 10,
        pageNumber:1,
        pageList: [10, 20, 50, 100, 200, 500],
        search: true,
    data : [],
    });
        $table.on('all.bs.table', function (event) {

            $('#table').dragtable('destroy').dragtable({});

        });

    });
    </script>`

**Comment by UtechtDustin** [comment]
Im not sure but i guess this commit is wrong: https://github.com/wenzhixin/bootstrap-table/commit/9351cd13004c6d2e2d81b273f8a25e0a0c0e6ac3.
There is a variable which is called `ths`, `this.length` returns nothing.
@wenzhixin
