### ISSUE TITLE
append/insertRow methods to have an optional parameter to highlight new appended row

### ISSUE THREAD

**Issue by kwagdy** [wenzhixin/bootstrap-table#4036]
Short and descriptive example bug report title
On using **append** `$table.bootstrapTable('append', data);` or **insertRow** `$table.bootstrapTable('insertRow', index, row);` methods it should have an optional parameter to highlight the newly inserted row or a class to to be added to the new row.

This helps the user _see_ what changes has been done to the table and gives better feedback/UX

**Comment by kwagdy** [comment]
Should apply to removing rows as well. A fadeout would be nice

**Comment by jimgit** [comment]
Is this a bug?   Sounds like a feature?

I saw this implemented somewhere in the github comments where a user defined field holds the status - can't remember but thought that the field could contain "original",  "updated", "inserted" or "deleted" for row formatting or filtering to see modifications before a final commit/save back to the server side.   Rowstyle could give indication of status.

**Comment by kwagdy** [comment]
Yeah, more like a feature request. rowStyle applies on all rows even when loading the entire table. What I am referring to is when appending, prepending, inserting, or removing a row. It would be nice to show the user a simple highlight or slideUp/slideDown animation to have a nice visual feedback on which row was added/inserted/removed. I tried searching for an event onAppend, onInsert or onRemove but there seems to be none

**Comment by kwagdy** [comment]
I have used the below code to highlight the newly inserted row, but I think if there's an optional parameter to auto highlight or add a class it would be generally more convenient :)

`$('#table_id tbody tr[data-uniqueid='+myUniqueID+']').effect("highlight", {'color':'#7c1'}, 3000);`

**Comment by wenzhixin** [comment]
I found that we can use `rowStyle` option to implement this feature.
```js
function rowStyle(row) {
  return row.isNew ? {
    css: {'color':'#7c1'}
  } : {}
}
```

Online example: https://live.bootstrap-table.com/code/wenzhixin/1413

**Comment by UtechtDustin** [comment]
@wenzhixin 
Im not good with css, but i think we cant do that with the row style.
The goal is to highlight the row once with a animtion.

The following example works once, but the animation will retriggered each time.
https://live.bootstrap-table.com/code/UtechtDustin/1414

**Comment by wenzhixin** [comment]
We can use a variable to save the state:
https://live.bootstrap-table.com/code/wenzhixin/1415
https://live.bootstrap-table.com/code/wenzhixin/1416
