### ISSUE TITLE
sorting with dropdown makes page unresponsive

### ISSUE THREAD

**Issue by stacyjoseph** [wenzhixin/bootstrap-table#4038]
I am facing issues with data set (ranging from 100 - 1000). When I sort with dropdown, the entire page becomes unresponsive. I am using version 1.10.1.

It seems to work better though on local node server but absolutely fails when page is loaded from server.

**Comment by jimgit** [comment]
Please post a JSFIDDLE showing your problem - you can simulate the server side at MYJSON.com

[Here are a bunch of jsfiddle samples to get started.](http://bootstrap-table.wenzhixin.net.cn/examples/)

**Comment by wenzhixin** [comment]
I don't have the unresponsive problem: http://bootstrap-table-examples.wenzhixin.net.cn/
Select ALL rows per page, and then sort.
