### ISSUE TITLE
How does bootstrap-table freeze some columns and scroll through other columns?

### ISSUE THREAD

**Issue by yxgmagic** [wenzhixin/bootstrap-table#4039]
Hello, author, I have a bootstrap-table column freeze issue, I am using the Google Chrome / Springboot project.
My needs are: There are too many table columns, how can I freeze one or more columns on the right to let other columns scroll?
Because the rightmost column has an action button!!!! Author, I need help!
I follow the steps of [https://www.cnblogs.com/landeanfen/p/7095414.html](url)
When you open the static left freeze column demo vertical scroll, the frozen column does not follow the scroll;
Using the demo that is frozen on the right side, the style is messy. The frozen column is not displayed in the table but floats above.
Blog garden problem can see the picture description[https://q.cnblogs.com/q/110899/](url)

**Comment by jimgit** [comment]
Can you submit a jsfiddle showing the problem - your links don't go anywhere.

**Comment by wenzhixin** [comment]
Fixed in the latest version.
