### ISSUE TITLE
 bootstrap table.js bug

### ISSUE THREAD

**Issue by shoukaiseki** [wenzhixin/bootstrap-table#4041]
第1169行,需要将
 sprintf('<i class="%s %s"></i>', this.options.iconsPrefix, this.options.icons.toggle),
改为
 sprintf('<i class="%s %s"></i>', this.options.iconsPrefix, this.options.icons.toggleOff),
否则不显示'切换'图标

**Comment by wenzhixin** [comment]
Fixed in v1.12.2
