### ISSUE TITLE
group-by-v2 ,the columns titles is hidden other than the group by column

### ISSUE THREAD

**Issue by Eastcloudsea** [wenzhixin/bootstrap-table#4043]
I am using group-by-v2 ,the columns titles is hidden other than the group by column. I try to add this.$el.find('.info.groupBy').addClass('no-records-found'); the titles are shown , but the width is incorrect.

PLS Help Me ! thanks.

this is the jsfiddle

Please read: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports
and post issue to: https://github.com/wenzhixin/bootstrap-table/issues, thanks!

Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by Eastcloudsea** [comment]
[http://jsfiddle.net/3vos61xj/](http://jsfiddle.net/3vos61xj/  )

**Comment by Eastcloudsea** [comment]
the tmp solution for others 
[change the fitheader]
 this.$body.find('>tr:not(.no-records-found):not(.groupBy):last > *').each(function (i) {  //chinarma fix groupby header

/////////////////////////////////////////////
    BootstrapTable.prototype.fitHeader = function () {
        var that = this,
        fixedBody,
        scrollWidth,
        focused,
        focusedTemp;
        if (that.$el.is(':hidden')) {
            that.timeoutId_ = setTimeout($.proxy(that.fitHeader, that), 100);
            return;
        }
        fixedBody = this.$tableBody.get(0);
        scrollWidth = fixedBody.scrollWidth > fixedBody.clientWidth &&
        fixedBody.scrollHeight > fixedBody.clientHeight + this.$header.outerHeight() ?
        getScrollBarWidth() : 0;
        this.$el.css('margin-top', -this.$header.outerHeight());
        focused = $(':focus');
        if (focused.length > 0) {
            var $th = focused.parents('th');
            if ($th.length > 0) {
                var dataField = $th.attr('data-field');
                if (dataField !== undefined) {
                    var $headerTh = this.$header.find("[data-field='" + dataField + "']");
                    if ($headerTh.length > 0) {
                        $headerTh.find(":input").addClass("focus-temp");
                    }
                }
            }
        }
        this.$header_ = this.$header.clone(true, true);
        this.$selectAll_ = this.$header_.find('[name="btSelectAll"]');
        this.$tableHeader.css({
            'margin-right': scrollWidth
        }).find('table').css('width', this.$el.outerWidth())
        .html('').attr('class', this.$el.attr('class'))
        .append(this.$header_);
        focusedTemp = $('.focus-temp:visible:eq(0)');
        if (focusedTemp.length > 0) {
            focusedTemp.focus();
            this.$header.find('.focus-temp').removeClass('focus-temp');
        }
        // fix bug: $.data() is not working as expected after $.append()
        this.$header.find('th[data-field]').each(function (i) {
            that.$header_.find(sprintf('th[data-field="%s"]', $(this).data('field'))).data($(this).data());
        });
        var visibleFields = this.getVisibleFields(),
        $ths = this.$header_.find('th');
        this.$body.find('>tr:not(.no-records-found):not(.groupBy):last > *').each(function (i) {  //chinarma fix groupby header
            var $this = $(this),
            index = i;
            if (that.options.detailView && !that.options.cardView) {
                if (i === 0) {
                    that.$header_.find('th.detail').find('.fht-cell').width($this.innerWidth());
                }
                index = i - 1;
            }
            if (index === -1) {
                return;
            }
            var $th = that.$header_.find(sprintf('th[data-field="%s"]', visibleFields[index]));
            if ($th.length > 1) {
                $th = $($ths[$this[0].cellIndex]);
            }
            var zoomWidth = $th.width() - $th.find('.fht-cell').width();
            $th.find('.fht-cell').width($this.innerWidth() - zoomWidth);
        });
        this.horizontalScroll();
        this.trigger('post-header');
    };

**Comment by UtechtDustin** [comment]
The group by extension will be merged/rewritten, this issue will be checked in #4413.
