### ISSUE TITLE
how to disable auto-loading when user open the page the first time

### ISSUE THREAD

**Issue by dumbdonkey** [wenzhixin/bootstrap-table#4044]
if I add a remote  URL configuration and enable server-side pagination, bootstrap-table will try to load remote data automatically when I open the page the first time. I want to disable this feature. let the table load data only when I click the search button.

I've read all the documentation but cannot find any help. 
 
Does anyone have any suggestions?

**Comment by jimgit** [comment]
One way would be use the server side data - you can start the search default with something that will never be found,  then when the user types in something valid in the search box,  the search will find and display data only then.

**Comment by jimgit** [comment]
You could default the opening url to an empty set,  then the OnSearch event to change the url property to the proper url.

**Comment by Mobel123** [comment]
> One way would be use the server side data - you can start the search default with something that will never be found, then when the user types in something valid in the search box, the search will find and display data only then.

that's the approach I'm using now. well I think that is a little silly

**Comment by jimgit** [comment]
Does it work?  Does it cause performance problems?  If so, it's not silly.

**Comment by wenzhixin** [comment]
I think this extension can solve your problem: http://bootstrap-table-examples.wenzhixin.net.cn/#extensions/defer-url.html @dumbdonkey.
