### ISSUE TITLE
Boostrap table filter control - multiples

### ISSUE THREAD

**Issue by GRosay** [wenzhixin/bootstrap-table#4046]
Hi,

I have an issue using the filter-control plugin.
In fact, I want to filter multiples columns at the same time but it seems that the table is only filtered by the last modified filter.

Let's assume I have this table:

| ID        | Name | Firstname |
| ------------- |:-------------:| -----:|
| 1      | dupont | james |
| 2      | dupont | henry|
| 3      | marc | henry |
| 4      | dupont | raoul |
| 5      | marc | edouard |
| 6      | lafritte | john |
| 7      | dupuis | jo|
| 8      | lafayette | eric |

If I filter the name column by 'du' I'll have following lines returned:

| ID        | Name | Firstname |
| ------------- |:-------------:| -----:|
| 1      | dupont | james |
| 2      | dupont | henry|
| 4      | dupont | raoul |
| 7      | dupuis | jo|

But now, if I had a second filter on firstname, let's say 'h' to get only dupont henry, I'll have this result:

| ID        | Name | Firstname |
| ------------- |:-------------:| -----:|
| 2      | dupont | henry|
| 3      | marc | henry |
| 6      | lafritte | john |

instead of just having dupont henry

So my question is, is it possible to have a multiples filter ? And if yes, how can I do it ?

Many thanks

**Comment by GRosay** [comment]
I could reproduce the problem with the example. So I'm not sure if it's a bug or simply not supported (but in that case, there's no advantage of using filter control).

http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filter-control.html

On this exemple, select a price in the third column and then write "item" in the second...

**Comment by eitanmg** [comment]
I have found a workaround for that issue.

you can add **Table Toolbar** extension:

https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/toolbar

and to your bootstrap-table options, add `advancedSearch: true` , then the filter will work fine.

if you want to remove the advanced search button from the table toolbar, you can edit the js/css code and `display:none` the button element.

**Comment by GRosay** [comment]
Many thanks, this does the trick !
