### ISSUE TITLE
Sort on Checkbox Selection:

### ISSUE THREAD

**Issue by Division4Studios** [wenzhixin/bootstrap-table#4047]
I have generated a Checkbox in my table using.

`<th data-sortable="true" data-checkbox="true" data-field="checkboxSelect" data-formatter="checkedFormatter">`

I would like to instantly sort or send the row I selected Up to the top of the table.  Is there a way to do this?
The reason for this, is when working with large datasets, it is difficult to scroll down to see all of the rows you have selected.  Sending them to the top of the table would make it so that they could review their selections before finalizing any changes.

**Comment by jimgit** [comment]
I hope somebody has a better way but I haven't been able to sort the selection checkbox.  When I needed something like this,  I added a field from the server and made the checkbox with the data-formatter.  Unfortunately,  you have to add logic for updates to the table's data.  May also be able to use the [TABLE EDITOR extension](url) but I haven't looked into that.

[See this jsfiddle for just sortable checkboxes to see the idea.](http://jsfiddle.net/jimkennelly/Lcrb3pw9/1/)

![image](https://user-images.githubusercontent.com/1921941/48619650-c4a4c680-e962-11e8-8d22-13179e2e691d.png)

**Comment by wenzhixin** [comment]
Made the checkbox with the `data-formatter` instead.
