### ISSUE TITLE
bootstrap table中的所有上拉下拉列表全都显示不出来

### ISSUE THREAD

**Issue by YuFy1314** [wenzhixin/bootstrap-table#4048]
![](https://user-images.githubusercontent.com/24446694/48593871-81118300-e989-11e8-95c7-f5da3713410f.png)
点击上面的那个按钮, 一直显示aria-expanded="false", 并且下面的这个class一直是display:none
![](https://user-images.githubusercontent.com/24446694/48593886-9090cc00-e989-11e8-8735-4861b9c881bc.png)
这个问题困惑了快一天了, 要怎么解决, 麻烦给一个建议或者方案  谢谢啦 @wenzhixin

**Comment by YuFy1314** [comment]
我的这个不是直接写在html里面的, 而是用js自动生成的通过它: ```<table id='tab' class="table table-hover table-striped table-bordered" style='word-break:break-all;'>
                    </table>```
![](https://user-images.githubusercontent.com/24446694/48594180-b074bf80-e98a-11e8-97b3-40736d29b2ed.png)

**Comment by wenzhixin** [comment]
是不是因为没有引入 bootstrap.js？

**Comment by ChengXu2016** [comment]
我也遇到了这个问题，检查了一下，发现如果两个table前后同时构造，就会出现不能点击查看隐藏列；下图是先定义两个构造bootstrap table的对象，在调用。最后我改成定义一个就调用就没有问题
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/22406905/62262180-5a797680-b44a-11e9-9b10-72eba4d89c61.png">

**Comment by YuFy1314** [comment]
噢噢  谢谢   以后再用的时候我注意一下   现在那个项目已经不做了
