### ISSUE TITLE
pagination not working when the number of rows equals default-page-size

### ISSUE THREAD

**Issue by marioz82** [wenzhixin/bootstrap-table#4049]
Hi to all.
I populate a table using a subset of data, which is created by clicking on a plot: in this way, user selects a bin and populates the table with corresponding data.

When I click on a bin with a number of data equals to the default-page-size, immediately nothing happens, but table pagination disappears after clicking on another bin containing more data than the default-page-size.

I verified this behaviour changing the default-page-size in order to keep it always different from number of data to show. In this case the pagination always works.

Thanks in advance for the support and congratulation for your work.

**Comment by jimgit** [comment]
[Not seeing the problem in this JSFIDDLE ](http://jsfiddle.net/jimkennelly/3zwtLmqs/)

**Comment by marioz82** [comment]
I've been experiencing the problem when I loaded two dataset on the same table. 
The first whose rows equal to default page size and a second one whose size is different (bigger if possible).
Loading the second dataset, the  pagination disappear.

**Comment by jimgit** [comment]
This is why we ask that you submit a jsfiddle outlining the problem.  Please submit a jsfiddle duplicating the problem.

**Comment by jimgit** [comment]
Just a thought,  you might want to DESTROY the table before loading the new data.

![image](https://user-images.githubusercontent.com/1921941/49227722-625eb380-f3af-11e8-9b87-8044ad79c65f.png)

**Comment by marioz82** [comment]
It works!
In any case, I will try to create a fiddle to resproduce the problem.

Thank you!
