### ISSUE TITLE
i Want to export two Tables 

### ISSUE THREAD

**Issue by santhoshdonthi** [wenzhixin/bootstrap-table#4051]
Short and descriptive example bug report title its not bug development i think so or i dont no how to do.

i have two tables side by side  .i want to export two tables side by side in the pdf and excel also i use two tables 

`using (row3.GridColumn(6).Begin())
                    {
                        <div id="toolbar">
                            <div class="form-inline" role="form">
                            </div>
                        </div>
                        <table id="tbl_VendorPurchase"
                               data-search="false"
                               data-toggle="table"
                               data-mobile-responsive="true"
                               data-detail-view="false"
                               data-show-export="false"
                               data-click-to-select="true"
                               data-pagination="false"
                               data-height="400"
                               data-toolbar="#toolbar">
                            <thead>
                                <tr>
                                    @*<th data-field="VoucherTypeName">Voucher</th>
                                        <th data-field="PartyName">VendorName</th>*@
                                    <th data-field="PurchaseDate" data-formatter="WBootstrapDate">Purchase Date</th>
                                    <th data-field="PurchaseRefrence">Reference</th>
                                    <th data-field="PurchaseAmount" data-width="80"  data-align="right" data-formatter="priceFormatter">Total</th>
                                    @*<th data-field="PaymentDate" data-formatter="WBootstrapDate">Payment Date</th>
                                        <th data-field="PaymentRefrence">Reference</th>
                                         <th data-field="PaymentAmount">Total</th>*@
                                </tr>
                            </thead>
                            <tbody></tbody>
                            <tfoot>
                                <tr>
                                    <td>Total</td>
                                    <td></td>
                                    <td><label id="PurchaseTotal"></label></td>
                                </tr>
                            </tfoot>
                        </table>
                    }
                    using (row3.GridColumn(6).Begin())
                    {
                        <div id="toolbar">
                            <div class="form-inline" role="form">
                            </div>
                        </div>
                        <table id="tbl_VendorPayment"
                               data-search="false"
                               data-toggle="table"
                               data-mobile-responsive="true"
                               data-detail-view="false"
                               data-show-export="false"
                               data-click-to-select="true"
                               data-pagination="false"
                               data-height="400"
                               data-toolbar="#toolbar">
                            <thead>
                                <tr>
                                    @*<th data-field="VoucherTypeName">Voucher</th>
                                        <th data-field="PartyName">VendorName</th>
                                        <th data-field="PurchaseDate" data-formatter="WBootstrapDate">Purchase Date</th>
                                        <th data-field="PurchaseRefrence">Reference</th>
                                        <th data-field="PurchaseAmount">Total</th>*@
                                    <th data-field="PaymentDate" data-formatter="WBootstrapDate">Payment Date</th>
                                    <th data-field="PaymentRefrence">Reference</th>
                                    <th data-field="PaymentAmount" data-width="80" data-align="right" data-formatter="priceFormatter">Total</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                            <tfoot class="footer">
                                <tr>
                                    <td>Total</td>
                                    <td></td>
                                    <td><label id="PaymentTotal"></label></td>
                                </tr>
                            </tfoot>
                        </table>
                    }`

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

**Comment by wenzhixin** [comment]
Sorry, we don't support feature.
