### ISSUE TITLE
Group by version and source confusion

### ISSUE THREAD

**Issue by jimgit** [wenzhixin/bootstrap-table#4052]
Today I was adding group-by features to a bootstraptable.  Noticed the extensions pages refers to version 1 and version 1.1 but also see a V2 mentioned in issues.  Is V2 the version to use and where is it?

![image](https://user-images.githubusercontent.com/1921941/48853738-ca8d1400-ed75-11e8-9ea5-d23393166683.png)

**Comment by wenzhixin** [comment]
Because the extension name is an error, I have fixed the name.
