### ISSUE TITLE
treegrid multiRoot

### ISSUE THREAD

**Issue by jackbauer007007** [wenzhixin/bootstrap-table#4054]
TreeGrid
data like this 
id     pid           name
1      null          根节点1
2     nothere     节点1
3     nothere      节点2

treegrid will find pid=null  if not assign rootPid as root ,but 节点1 and 节点2 will not show,I want them show Rows when there is no Root

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
