### ISSUE TITLE
Ability to use remote data url but fallback to local cache

### ISSUE THREAD

**Issue by ericavijay** [wenzhixin/bootstrap-table#4055]
I have a situation where a feature would be very useful.  My data comes from a database and is collected via data-url due to a large number of rows.  However when connection fails I want to be able to use a local cache such as sessionStorage or localStorage to present to the user rows at least of the current page.  This is useful if my website is accessed via a wireless network or when present in bus/train on a mobile device and there is interrupted connections. The user cannot go to other pages of data but should be able to see the current page (unless those pages also can be cached in localstorage).  If you can recommend a good approach for this type of fallback it will be very helpful for my site.

Thanks

**Comment by jimgit** [comment]
I didn't have time to finish this completely but here are some ideas - maybe somebody can help with this.

Use the load / error events to determine when you get data
![image](https://user-images.githubusercontent.com/1921941/49090167-c43de280-f222-11e8-8793-15075b4cde3e.png)

[This url represents "good" data -](https://api.myjson.com/bins/omz7e) 



![image](https://user-images.githubusercontent.com/1921941/49090136-b4be9980-f222-11e8-94f0-90d967ba59f1.png)

[See if this jsfiddle on the track you are looking for:](http://jsfiddle.net/jimkennelly/b5j3ruep/)


![image](https://user-images.githubusercontent.com/1921941/49090295-036c3380-f223-11e8-8e76-26ff2deaaaa4.png)

**Comment by jimgit** [comment]
You might want to try DESTROYING the table or have two tables - use one for good data and the other when using the cached data.  Hide the table not needed.  Probably a better way but this should work.

**Comment by jimgit** [comment]
Since the connection can "come back later" you might want to set a time once you determine you have no connection for retrying.

**Comment by ericavijay** [comment]
Thanks Jim - you have been insightful and helpfu.
