### ISSUE TITLE
Change print css

### ISSUE THREAD

**Issue by amin7x** [wenzhixin/bootstrap-table#4056]
hi guys
how i can manage css or add some classes to print view of my table?
thanks.

**Comment by jimgit** [comment]
[Take a look at this JSFIDDLE for some ideas](http://jsfiddle.net/jimkennelly/xow02uh5/) - can't test since I don't have a printer attached.

**Comment by jimgit** [comment]
[Not seeing the problem in this jsfiddle](http://jsfiddle.net/jimkennelly/3zwtLmqs/)

**Comment by amin7x** [comment]
> 
> 
> [Take a look at this JSFIDDLE for some ideas](http://jsfiddle.net/jimkennelly/64fscLr0/) - can't test since I don't have a printer attached. If you come up with a solution, please repost the fiddle so others can benefit.

thanks for helping me.
This code works when I use the ctrl+ p key, but I need to work with the default bootstrap-table print button.

**Comment by jimgit** [comment]
I've never used the ### **default bootstrap-table print button**  Could you post a jsfiddle example?
