### ISSUE TITLE
Adding a new extension to the website

### ISSUE THREAD

**Issue by tupto** [wenzhixin/bootstrap-table#4058]
Hello I developed an extension for boostrap-table that you can find here: https://github.com/tupto/bootstrap-table-field-search

I would like to get it listed on the website but I do not know how to do this. Can anyone help me?

**Comment by tupto** [comment]
Perhaps but this is supposed to be a very simple extension. I did add support for the strictSearch option so now match exact case is an option available to you. Search-contains is the search it does by default. I have no plans to add matching for starts with and ends with. Next time please post issues and feature requests on my repo.

**Comment by wenzhixin** [comment]
Any example?

**Comment by UtechtDustin** [comment]
@tupto 
If you still want that we add your extension, please update it to the newest bootstrap-table version and submit an Pull Request (with examples(jsfiddle) and documentation).
