### ISSUE TITLE
How to format the toolbar and search input

### ISSUE THREAD

**Issue by kryptonianson** [wenzhixin/bootstrap-table#406]
I would like to format the search toolbar area as the image shown. Does anyone know how I can accomplish this properly? The built in options don't seem to allow me to do it exactly in this order with this alignment. Thank you so much for your help.

![toolbar](https://cloud.githubusercontent.com/assets/1218299/5651847/1c7e1dfc-9679-11e4-81f7-37a4c4824afa.png)

**Comment by wenzhixin** [comment]
You need to update to the latest source code: http://issues.wenzhixin.net.cn/bootstrap-table/#406.html

**Comment by kryptonianson** [comment]
I think there may be a misunderstanding here. I see no way to make the search box appear first in the far left, then the buttons. In fact I would like the filter button to appear right after the refresh button. Thanks for you patience.

**Comment by AndrewBS42** [comment]
The question was, "I'd like to do [this]".
The only answer was "download the latest source".
The answer did not explain how to do [this] once I had the latest source, or where to look for that particular feature.
Which option was added to allow me to placed the Search vs. the rest of the toolbar into the order I choose, and what are my choices?

**Comment by wenzhixin** [comment]
The examples' URL has been updated to https://examples.bootstrap-table.com/#issues/406.html, which is specifically for solving this issue. If you don't mind, you can just check the source code of the corresponding example to see how it is resolved. The critical code is as follows:

```html
  data-search-align="left"
  data-buttons-align="left"
  data-toolbar-align="right"
```

**Comment by AndrewBS42** [comment]
If this is a repeat, I apologize.

Thanks for the prompt response and details.  I did get the toolbar to arrange as I like.

I fixed up the alignment attributes to be

![image](https://github.com/user-attachments/assets/067f9f85-ffaf-47a8-b79b-672e102b5d1b)

This markup excerpt

![image](https://github.com/user-attachments/assets/726af072-25d3-4cf9-b8bc-9e515740f833)

displays as

![image](https://github.com/user-attachments/assets/7a00028d-fafe-46a7-b6e2-a5b34aaaf0b3)

But I'd like the search and buttons to be between the 2 horizontal rules and at the right margin.  So I added a data-buttons-toolbar attribute, and specified that class on a div.  The ViewData["Action"] is set to "Lists".

This markup excerpt

![image](https://github.com/user-attachments/assets/a306917c-fe8b-4a0b-a2b0-2aaee8b780d2)

displays as

![image](https://github.com/user-attachments/assets/fead0158-b9eb-434b-8397-0882e5483baa)

The search field and toolbar now appear at the proper place on the page, but the arrangement has changed.
Is there a way to maintain the previous arrangement in the new div?
What am I missing?

**Comment by wenzhixin** [comment]
Currently, the table only supports the settings mentioned above. If you need more complex displays, then you can only override the settings by rewriting them with CSS. I hope you can solve the problem.
