### ISSUE TITLE
Can I use the extensions without downloading the source code?

### ISSUE THREAD

**Issue by IronCrystal** [wenzhixin/bootstrap-table#4060]
I am currently using this plugin using the CDN links, but I'd like to use the editable extension.

Everywhere I see the source code that uses the file refers to a local file, as if it had been locally downloaded.

Is it possible to reference the file from the CDN link somehow?  Or am I required to download the source code?

**Comment by IronCrystal** [comment]
Nevermind, I figured it out.

I can make a reference directly to the rawgit url.

`script(src="https://rawgit.com/wenzhixin/bootstrap-table/master/src/extensions/editable/bootstrap-table-editable.js")`

**Comment by wenzhixin** [comment]
You can use CDN: https://cdnjs.com/libraries/bootstrap-table
