### ISSUE TITLE
data-search cannot find item in json list

### ISSUE THREAD

**Issue by andrew8062** [wenzhixin/bootstrap-table#4061]
I notice that data-search is unable to find element if it is in a list in JSON.
example:
http://jsfiddle.net/472ncmb0/

not sure if I did something wrong or not support this?

**Comment by reinaldo-gomes** [comment]
Looks like your JSON is not what the jQuery expects.

The search works if you modify to the following:

var data =[{"Name":"abc"},{"Name":"123"}]

**Comment by andrew8062** [comment]
> Looks like your JSON is not what the jQuery expects.
> The search works if you modify to the following:
> var data =[{"Name":"abc"},{"Name":"123"}]

You are correct, but I lost the feature of list in JSON. 
I could do a pre-data processing to translate all list to string as workaround. 
I guess it is probably a bug or new feature need to be supported.

**Comment by wenzhixin** [comment]
You can use `data-formatter` to solve your problem: http://jsfiddle.net/wenyi/69L7kxgj/1/

**Comment by andrew8062** [comment]
Life saver. Thanks!
