### ISSUE TITLE
Display JSON string in table cell

### ISSUE THREAD

**Issue by cheizer** [wenzhixin/bootstrap-table#4063]
Hello,
I would like to display a pretty formatted json string in a table cell. Is this possible? If so how? I keep getting a EOF error.

Thanks!

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by jimgit** [comment]
You could stringify the row/table [- here is an example JSFIDDLE.  Please modify the JSFIDDLE ](http://jsfiddle.net/jimkennelly/vnezxjg9/)to show what you are trying to do.

**Comment by wenzhixin** [comment]
I think the solution @jimgit  provided can solve your problem.
