### ISSUE TITLE
insert/updateRow

### ISSUE THREAD

**Issue by zqr95518** [wenzhixin/bootstrap-table#4064]
How about add a method of mergeRow?
Sometimes I need to check if the index exist, update it. Or, insert it.

**Comment by jimgit** [comment]
You might want to just try to get row by unique id and if it returns nothing, do the insert if something insert the row.

**Comment by wenzhixin** [comment]
Use `unique id` is a good idea:
```
var data = $table.bootstrapTable('getData')
var index = data.findIndex(row => row.id === 1)
```
