### ISSUE TITLE
Filter-control comma seperated values

### ISSUE THREAD

**Issue by UtechtDustin** [wenzhixin/bootstrap-table#4070]
Hello,

i have a column "tags" with a comma seperated list of tags.
This tags will be displayed  with a formatter as bootstrap [pill-badges](https://getbootstrap.com/docs/4.1/components/badge/#pill-badges).
How i filter the tags with the filter-control extension ?

**Comment by UtechtDustin** [comment]
Should we implement an custom search function for columns ?
@wenzhixin @djhvscf

**Comment by djhvscf** [comment]
This is a feature request for filter control extension.

Anyways please remember that you can use searchFormatter for this.

**Comment by pchaganti** [comment]
👍

**Comment by UtechtDustin** [comment]
@pchaganti 
I often saw your comment with a thumb up, but often im not sure what this refers to (the last comment, the issue ?).
It would pretty if could write something or give the thumb up to the refered comment :-)
