### ISSUE TITLE
Checkbox and radio auto-checked

### ISSUE THREAD

**Issue by vincentwinkel** [wenzhixin/bootstrap-table#4072]
When we use data ajax-requested, checkboxes and radios work well, following the official jsfiddle example.
But when we write the table directly in html, all the checkboxes / radios are checked.
I use bootstrap-table 1.12.2 on Chrome, OS X El Capitan.

[jsfiddle](http://jsfiddle.net/dvkefsxm/2/)

**Comment by Falseee** [comment]
You have to remove the `0` from the state fields

http://jsfiddle.net/dvkefsxm/14/

**Comment by wenzhixin** [comment]
Because `0` is treated as a string in HTML, it is judged as `true` when converting.
Just like @Falseee said. You can remove the `0` when rendering your HTML to solve the problem.

**Comment by wenzhixin** [comment]
If you use data or json, you can use `formatter` to do this, example here: http://bootstrap-table-examples.wenzhixin.net.cn/index.html#options/disabled-checkbox.html. 

But from html, I think there is no better solution.

> Because 0 is treated as a string in HTML, it is judged as true when converting.

**Comment by vincentwinkel** [comment]
Can we consider it's a bug?
In my opinion, the `formatter` attribute should be applied each time a cell is rendered, no matter the source type (html, json, ajax).

**Comment by wenzhixin** [comment]
OK, reopen. If I have time, I will debug how to solve this problem.
Any pull request is welcome.
