### ISSUE TITLE
固定列无法添加点击

### ISSUE THREAD

**Issue by CherishLyx** [wenzhixin/bootstrap-table#4073]
events给固定列里的内容添加点击事件，会被新生成的固定部分盖住，心诚成的 并不会绑定点击事件

**Comment by ComputerWizard2** [comment]
我也遇到这个问题，请问解决了吗？

**Comment by flashliao** [comment]
我也遇到这个问题！
  columns: [
                {
                    field: 'operate',//域值
                    title: '操作',//标题
                    visible: true,//false表示不显示
                    width : '15%',
                    formatter :operateFormatter,
                    **events: window.operateEvent**
                },
    window.operateEvents = {
      'click .like': function (e, value, row) {
        alert('You click like action, row: ' + JSON.stringify(row))
      },
      'click .remove': function (e, value, row) {
        alert('You click remove action, row: ' + JSON.stringify(row))
      }
    }
    function operateFormatter(value, row, index) {
      return [
        '<div class="pull-left">',
        '<a href="https://github.com/wenzhixin/' + value + '" target="_blank">' + value + '</a>',
        '</div>',
        '<div class="pull-right">',
        '<a class="like" href="javascript:void(0)" title="Like">',
        '<i class="fa fa-search"></i>',
        '</a>  ',
        '<a class="remove" href="javascript:void(0)" title="Remove">',
        '<i class="glyphicon glyphicon-remove"></i>',
        '</a>',
        '</div>'
      ].join('')
    }
操作列里面的按钮点击没反应啊

**Comment by CherishLyx** [comment]
> 我也遇到这个问题，请问解决了吗？
在列上介个class  在加载完之后又用JQ绑定的事件

**Comment by ComputerWizard2** [comment]
我的解决了，主要是给冻结列一个点击事件：https://computerwizard2.github.io/2019/01/08/bootstraptable%E7%9A%84%E5%86%BB%E7%BB%93%E5%88%97check-%E6%97%A0%E6%B3%95%E9%80%89%E4%B8%AD%E7%9A%84%E9%97%AE%E9%A2%98/

**Comment by wenzhixin** [comment]
最新版本已解决该问题。
