### ISSUE TITLE
Filter-control overwrite filter - shows also all values after filtering

### ISSUE THREAD

**Issue by Falseee** [wenzhixin/bootstrap-table#4074]
Hello,

i use the v1.12.2 and the filter-control extension v2.1.2.
I have the issue that if i filter two columns, the second filter overwrite the first one..
So if i have the following table:
ID X   Y
1   A   B
2  B   S
3  A   S

And i filter the column X with A i see row 1 and 3  (that is correct), but if i now also filter column Y with S i see the rows 2 and 3.

Also i have the issue if i filter the colum X with B the filter select of Y contains B AND S instead of only S (There is no combination of X = B and Y = B)

**Comment by Falseee** [comment]
Example for http://bootstrap-table-examples.wenzhixin.net.cn/index.html#extensions/filter-control.html

If i select $18 on the select i see only one row, but if i also write "item" in the Item Name input i saw all entries because the $18 filter will be ignored.

**Comment by eitanmg** [comment]
Hi, there is a workaround for that bug. See my answer here:

https://github.com/wenzhixin/bootstrap-table/issues/4046

**Comment by Falseee** [comment]
Works in the newest version (https://examples.bootstrap-table.com/index.html#extensions/filter-control.html).
