### ISSUE TITLE
Editable extension + Search select type

### ISSUE THREAD

**Issue by airtonjr** [wenzhixin/bootstrap-table#4078]
Hello all,

I can see that in the documentation for the editable extension has the warning:

**_The editable extension does not support searchable in the select type._**

But this is a warning from 2015. Any development in this matter? Is it still not working the search in editable (type select)? Or any working around it?

Thank you!

**Comment by wenzhixin** [comment]
ref #569

**Comment by wenzhixin** [comment]
Any pull request is welcome.

**Comment by UtechtDustin** [comment]
Can we implement that ?
I dont think so because we render/call the editable extension while rendering the table, if we only see one page we only have some selects..
I think the user should add the select options to the data so he can search it.
@wenzhixin @djhvscf

**Comment by wenzhixin** [comment]
> I think the user should add the select options to the data so he can search it.

@UtechtDustin I agree with you, in the current version is hard to implement that.

**Comment by UtechtDustin** [comment]
@airtonjr
Please add the select options to the data so you can search for them.
Currently we will not implement that, if some ppl. will ask for the same feature we will consider how we can implement it.
