### ISSUE TITLE
Can a column be excluded from the dropdown for multi sort?

### ISSUE THREAD

**Issue by twhetzel** [wenzhixin/bootstrap-table#4082]
I am using the multi sort extension and have been asked to exclude one table column from the multi sort, but still allow this column to be sorted with single sort. This column uses a custom sort method with single sort and I can not find out how to use the multi sort option with this custom sort method so am now trying to remove this column from the multi sort dropdown.

Is there a parameter to do this _or_ any suggestions to do this via jQuery?

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
