### ISSUE TITLE
removeByUniqueId删除前面N行后，getSelections取不到剩下的前N行数据

### ISSUE THREAD

**Issue by zhoujun165** [wenzhixin/bootstrap-table#4083]
版本号 1.11.1

如题

**Comment by wenzhixin** [comment]
刚刚测试了，没有问题，请提供 jsFiddle 吧。
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by TANZAME** [comment]
@wenzhixin bootstraptable 有进一步提升性能的版本计划吗，比如像ag-grid,handsontable这些表格插件，能支持一页上十万条数据界面都不卡顿。

**Comment by wenzhixin** [comment]
性能问题后面再看下，有时间的话会改进的，这个问题关闭。
