### ISSUE TITLE
多个空格显示问题，貌似未修复

### ISSUE THREAD

**Issue by lazzyfu** [wenzhixin/bootstrap-table#4085]
如下图：
![image](https://user-images.githubusercontent.com/14190782/50464373-59232f80-09cb-11e9-9e67-e613b58c8238.png)

我使用的版本是：bootstrap-table-1.12.2

请问如何修复，谢谢

**Comment by lazzyfu** [comment]
在线等，急，谢谢

**Comment by wenzhixin** [comment]
这个跟 table 没有关系的，你可以自己试验下 `<div>你好                    欢迎</div>`就知道了。
你可以考虑使用 `formatter` 然后加上 `margin` 来实现。

**Comment by lazzyfu** [comment]
恩恩，收到，谢谢，已经解决了
