### ISSUE TITLE
Max Height

### ISSUE THREAD

**Issue by liusvel90** [wenzhixin/bootstrap-table#410]
Happy new year for every one !!!
i wonder if i cant set a max height for a table, because I want the table to grow according to the data inserted until some specific point, thks

**Comment by wenzhixin** [comment]
Happy new year @liusvel90 , you can try to remove the `height` option?

**Comment by liusvel90** [comment]
i already do that but i need to handle the max height taken by the table, could you suggest some way to do it, thks in advance

**Comment by dabros** [comment]
@liusvel90 - please state whether this is still an issue for you, or you found a workaround?

**Comment by djhvscf** [comment]
@liusvel90 See this: http://stackoverflow.com/questions/20293492/max-height-in-html-table
