### ISSUE TITLE
can't Display Data that more than 400 row and getting No matching records found

### ISSUE THREAD

**Issue by aahmedfouad** [wenzhixin/bootstrap-table#4100]
I'm getting JSON data from a server .. and see it in the console
but the table cant display the data that more than 400 
I tried another url with 100 row and its work 

any help 

`<table data-toggle="table"
													data-url="the url"
													data-search="true"
													data-pagination="true"
													data-show-refresh="true">
														<thead>
															<tr>
																	<th data-field="id" class="w50" data-cell-style="cellStyle">ID</th>
																	<th data-field="first_name" data-sortable="true">First Name</th>
																	<th data-field="last_name" data-sortable="true">Last Name</th>
																	<th data-field="area_name" data-sortable="true">Area</th>
																	<th data-field="hosp_name" data-sortable="true">Hospital</th>
																	<th data-field="clinic_name" data-sortable="true">Clinic</th>
																	<th data-field="spec" data-sortable="true">Specialization</th>
																	<th data-field="qualifications" data-sortable="true">Qualifications</th>
																	<th data-field="join_date" data-sortable="true">Created on</th>
																	<th data-field="insurance_companies">Insurance Companies</th>
																	<th class="w0" data-field="action" data-formatter="actionFormatter" data-events="actionEvents">Action</th>
															</tr>
														</thead>
													</table>`

**Comment by jimgit** [comment]
Please provide a jsfiddle - you can use myjson.com to simulate some test data for your json feed.

**Comment by aahmedfouad** [comment]
I fixed 
I was getting an object of arrays not array of objects
