### ISSUE TITLE
Pagination examples don't work

### ISSUE THREAD

**Issue by vstruchkov** [wenzhixin/bootstrap-table#4101]
I  look this page with server-side pagination (https://github.com/wenzhixin/bootstrap-table/issues/1765)
But this examples http://jsfiddle.net/wenyi/4r6g4cfu/582/ and http://jsfiddle.net/wenyi/4r6g4cfu/848/ don't work. Because parameter "data-url" generate 404 error

**Comment by wenzhixin** [comment]
Use our examples site instead:
https://bootstrap-table-examples.wenzhixin.net.cn/#options/client-side-pagination.html
https://bootstrap-table-examples.wenzhixin.net.cn/#options/server-side-pagination.html
