### ISSUE TITLE
How to do  re-sizable column in bootstrap-table (wenzhixin)

### ISSUE THREAD

**Issue by kuldip1490** [wenzhixin/bootstrap-table#4102]
Here i m using bootstrap-table (wenzhixin) which is working fine but i need to add one feature like resize column by dragging over there 

**please help how to use extension in bootstrap-table** 

@wenzhixin  and @djhvscf

**Comment by wenzhixin** [comment]
Example: https://bootstrap-table-examples.wenzhixin.net.cn/#extensions/resizable.html
Source: https://bootstrap-table-examples.wenzhixin.net.cn/index.html?view-source#extensions/resizable.html

**Comment by kuldip1490** [comment]
i did everything as per guidance but column head were not moving with row    
var $table = $('#table');

	$table.bootstrapTable("destroy");
	$table.bootstrapTable({		
		method: 'POST',
		height: getHeight() + 50,
		contentType: "application/json;charset=utf-8",
		url: apiURL + "Service.asmx/getList",
		dataType: "json",
		sidePagination: 'server',
		pageNumber: 1,		
		pageList: [25, 50, 100, 200],
		sortOrder: 'desc',
		pagination: true,
		queryParamsType: 'limit',
		queryParams: queryParams,
		pageSize: 25,
		pagination: true,
		silentSort: false,
		sortName: 'Doc No',
		resizable:true,
		minimumCountColumns: 2,

this is the problems 
![untitled](https://user-images.githubusercontent.com/22524273/51425739-12a9a500-1c06-11e9-9774-132b471032e1.png)

**Comment by guizhou-feng** [comment]
> This plugin does not work when data-height is set.
https://bootstrap-table.com/docs/extensions/resizable/
As documented here, the resizable plugin cannot work with **height** option
