### ISSUE TITLE
Vertical Table Headers - Bootstrap 4 | no <thead>, <th> scope in <tbody>

### ISSUE THREAD

**Issue by evanmeier** [wenzhixin/bootstrap-table#4108]
I am looking to have vertical headers in a table that reflects an account overview. The <thead> isn't particularly necessary at this point since each scope is unique to one (1) particular value.

If I don't load a `<thead>` it throws an error. Alternatively, I was able to find another users issue (_that I can't seem to locate now_) that resulted in feedback stating that a _<thead>_ HAD to be loading. Based of this I included a blank _<thead>_.

In bootstrap 4 you are able to specify a scope based on "col" or "row" [(https://getbootstrap.com/docs/4.0/content/tables/#examples),](https://getbootstrap.com/docs/4.0/content/tables/#examples) however every-time I try to call a `<th>` in the `<tbody>` it removed the tag all together which gives me the following result:
[https://jsfiddle.net/evanmeier/Lpy4b8eo/](https://jsfiddle.net/evanmeier/Lpy4b8eo)

The desired output I am looking for is the following:
[https://jsfiddle.net/evanmeier/6ck9p3ya/](https://jsfiddle.net/evanmeier/6ck9p3ya/)

Thank you in advance; any help or guidance is appreciated.

**Comment by wenzhixin** [comment]
The feature is not supported now.

**Comment by evanmeier** [comment]
> The feature is not supported now.

I appreciate you response. Please keep me posted to when this feature might me supported.

**Comment by UtechtDustin** [comment]
@wenzhixin 
Isn't his example basicly the card view ?
So does we rly need that feature ?

**Comment by wenzhixin** [comment]
Now that we have supported multiple themes, this can also be considered not implemented because it only supports Bootstrap 4.

**Comment by UtechtDustin** [comment]
@djhvscf what do you think about that ?

**Comment by djhvscf** [comment]
From my point of view this is almost fully supported by card view feature.

**Comment by UtechtDustin** [comment]
Okay, then we can close this issue.
