### ISSUE TITLE
自定义查询时如何重新设置页码为第一页

### ISSUE THREAD

**Issue by thinksea** [wenzhixin/bootstrap-table#411]
大家好，我想在执行自定义查询时将页码重置为第一页，如何解决？
谢谢！

**Comment by fvzone** [comment]
不太明白你说的是什么意思，可以描述清楚一点吗

**Comment by thinksea** [comment]
有一个迂回的方法，调用刷新方法，并且同时传递查询地址。
    $('#grid').bootstrapTable("refresh", {
        url: "......." //这个参数只是为了将分页索引设置为首页
    });

**Comment by wenzhixin** [comment]
增加了 `selectPage` 方法，使用 `$table.bootstrapTable('selectPage', 1);`
例子：http://issues.wenzhixin.net.cn/bootstrap-table/#methods/selectPage-prevPage-nextPage.html
