### ISSUE TITLE
bootstrap-table v1.13.1 的queryParams 不生效呢？代码如下：

### ISSUE THREAD

**Issue by sailsoft** [wenzhixin/bootstrap-table#4111]
function search(formId){
            var params = $("#bootstrap-table").bootstrapTable('getOptions');
            params.queryParams = function(params) {
                var search = {};
                $.each($("#" + formId).serializeArray(), function(i, field) {
                    search[field.name] = field.value;
                });
                search.pageSize = params.limit;
                search.pageNum = params.offset / params.limit + 1;
                search.searchValue = params.search;
                search.orderByColumn = params.sort;
                search.isAsc = params.order;
                return search;
            }
            $("#bootstrap-table").bootstrapTable('refresh', params);
   }

**Comment by wenzhixin** [comment]
用法不对哦，例子：
https://bootstrap-table-examples.wenzhixin.net.cn/index.html#options/custom-toolbar.html
https://bootstrap-table-examples.wenzhixin.net.cn/index.html#issues/152.html
