### ISSUE TITLE
How to kill a running ajax-request (and the corresponding mysql-query process)?

### ISSUE THREAD

**Issue by basementmedia2** [wenzhixin/bootstrap-table#4112]
How to kill a running ajax-request (and the corresponding mysql-query process)?

It's not a bug but a question:
I have a page, where the user can built a custom SQL Query which then is send to a bootstrap table (ajax request). Depending on the built query sometimes the MYSQL-database process remains very long or runs in an endless loop. Thus i want to offer a button which kills the running query.
Are there any built-in solutions in bootstrap-table which can kill the mysql request (by "$mysqli->kill($process_id);"?

**Comment by wenzhixin** [comment]
I think you can use an Ajax API to do this, for example:
```html
<button id="kill-request">Kill Request</button>
```

```js
$('#kill-request').click(function () {
  $.post('kill-request.php')
})
```

**Comment by basementmedia2** [comment]
Hi wenzhixin,

the problem is: the kill-request.php needs the ID of the MYSQL-Process.
This can be get by $mysqli->thread_id in the ajax.php of my table request.

But how could i "transfer" the thread_id to the Kill-Button?

Best regards

Daniel

**Comment by wenzhixin** [comment]
> sometimes the MYSQL-database process remains very long or runs in an endless loop

Because your service is not responding, it seems that you can't get thread_id.

Can you save the thread_id to the database or file?

**Comment by basementmedia2** [comment]
Hi,

Problem is, that - as soon as i start the request (which makes the responding-problems) - writing to the database is not possible not before the request is finished.

My plan was:
1. Press "Go"-button at main page --> ajax_req.php is triggered to fill the bootstrap table
2. In ajax_req.php: Start request and get thread_id (by $mysqli->thread_id) and write it to the database or a textfile 
3. Start a second ajax-request from main page (no idea if this is possible before the first request is finished?? Which bootstrap table-event would be the best here?) which gets the thread_id and builds the Kill-Button.

But unfortunately the plan stops in step "2." --> the thread_id is only available as soon as the request is finished..

Do you have further ideas?
Wouldn't it be nice to have a built in solution for bootstrap table to stop running requests?
Am i the only person which has such problems (with not responding mysql) ;-( ?

Best regards
Daniel

**Comment by wenzhixin** [comment]
Ref #1977, it supports to cancel the previous XHR request in the latest version.

**Comment by basementmedia2** [comment]
Hi,

sorry, i'm still not sure how to proceed in my particular case.

In my main page (index.php) i have the following table (shorted version for this example):
```
<table 
       id="projektverwaltung_table"
       data-url="ajax_load.php"          
       data-side-pagination="client"
       data-pagination="true"
       data-query-params="load_p_params"
>
  <thead>
    <tr>
       <th data-field="dataset_id" data-visible="false">Projekt-ID</th>
       <th data-sortable="true" data-field="pname">Projectname</th>
     </tr>
    </thead>
</table>
```

also on index.php i have the "load_p_params"-function (which is much larger in the real file..also shortend for this example)
```
function load_p_params(params) {
  //function returns values of some fields, needed for the ajax_request
  params.filter_keyword=$('#filter_keyword').val();
  return params;
}
```

And finally i've got the ajax_load.php himself which is build up like this
```
<?php
header('Access-Control-Allow-Origin: *');
include_once 'include/db_connect.php';
include_once 'include/functions.inc.php'; 
sec_session_start(); 

$keyword=$_GET["keyword"];

// there comes the query (emptied for this example)
$query=".....";
$data=array();
// +++++++++++++++++++++++++++++++++ AJAX-Variante 
while ($row=$result->fetch_object()){
	$row->thread_id=$thread_id;
 	$data[]=$row;
}
echo json_encode($data);
```

But where could i put these lines (shown in the linked references of you):
```
if (this._xhr && this._xhr.readyState !== 4) {
    // and how to kill the process?
}
```

Could you provide a more detailed example...please ;-(

Best regards
Daniel
