### ISSUE TITLE
How to add class "highlight" to row which is expanded?

### ISSUE THREAD

**Issue by krosoftware** [wenzhixin/bootstrap-table#4116]
I'm using selected row feature like this:

   $('#myTable').on('click', 'tbody tr', function(event) {    
        $(this).addClass('highlight').siblings().removeClass('highlight');    
    });     

now I need to remove highlited class and select only row which is expanded.
I'm using onExpandRow event, like this:

function onExpandRowMyTable(index, row, $detail) {    
    $('tr').removeClass('highlight');  // remove highlited row if selected    
    $($detail).addClass("highlight"); // select row which is expanded    
}    

but it does not work :(
Any help, please?

**Comment by krosoftware** [comment]
Please?

**Comment by djhvscf** [comment]
See this example: https://github.com/wenzhixin/bootstrap-table/issues/563#issuecomment-233029636

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by krosoftware** [comment]
Here is it: http://jsfiddle.net/vkL15x72/
but formatter is not working, don't know why not?
There is complete code which (I think) should work - when user clicked on expand icon, that row need to be selected. Thank you.

**Comment by krosoftware** [comment]
Anybody, please?

**Comment by wenzhixin** [comment]
@krosoftware Try this:
```
function onExpandRowMyTable(index, row, $detail) {
    $('tr').removeClass('highlight'); // remove highlited row if selected
    $detail.parent().prev().addClass('table-active'); // select row which is expanded
}
```

**Comment by wenzhixin** [comment]
@krosoftware You are welcome :)
