### ISSUE TITLE
data-page-list All 的问题

### ISSUE THREAD

**Issue by lifeXHY** [wenzhixin/bootstrap-table#4117]
先进行了一次数据较少的查询，返回了182笔记录，此时table对数据进行了分页处理，然后我选择了All  查看全部数据；然后我再进行一次 数据较多的查询，返回了298行数据，但是实际上列表上只显示了182笔，显示的是之前一次查询的行数，当我再次查询或者刷新列表之后，才返回了正确的数据！
请问这是什么情况。

样图如下：
[
![image](https://user-images.githubusercontent.com/30490352/51290432-ce1fdd00-1a3e-11e9-93ce-c7f9dd51e24e.png)
](url)
[
![image](https://user-images.githubusercontent.com/30490352/51290632-3bcc0900-1a3f-11e9-94ec-07715945c5c7.png)
](url)

页面配置：
[
![image](https://user-images.githubusercontent.com/30490352/51290702-746be280-1a3f-11e9-8c81-e80e1ab6c4b5.png)
](url)

js 查询：
[
![image](https://user-images.githubusercontent.com/30490352/51290734-8f3e5700-1a3f-11e9-893c-c52e906268cc.png)
](url)
[
![image](https://user-images.githubusercontent.com/30490352/51290771-a8470800-1a3f-11e9-9fee-2f458243a0fd.png)
](url)

**Comment by wenzhixin** [comment]
不需要额外调用 js 方法吧，例如例子：https://examples.bootstrap-table.com/ 就有 ALL 的选择，这里没有问题，应该是你的用法有误。
