### ISSUE TITLE
Switching from version 1.11.1 to 1.13.1 --> not working anymore

### ISSUE THREAD

**Issue by basementmedia2** [wenzhixin/bootstrap-table#4118]
Because of an previously issued problem (server-side-pagination does not work correctly) i tried switching from 1.11.1 to 1.13.1 to see if this is the solution.

But when i use 1.13.1 all tables are empty. The content is not loaded anymore.
When i switch back to 1.11.1 everything works fine.
Did you make major changes in 1.13.1 which force to update some custom code?

**Comment by basementmedia2** [comment]
Solved. The Extension bootstrap-table-filter-control seems to be the problem.
When i remove it, everything works perfect again.

**Comment by djhvscf** [comment]
Which is the version of filter-control that you have?
