### ISSUE TITLE
editable table option or any other option changing with button

### ISSUE THREAD

**Issue by omatic-hacker** [wenzhixin/bootstrap-table#412]
Hello,

how can i change editable mode with button? Or any other table option "on a fly".
I included bootstrap-editable and bootstrap-table-editable. Everything is ok when i create table with {editable: true}.

But what if I want to change editable mode with button in toolbar? Can I do that?

I supposed i can do it with tablename.bootstrapTable({editable.false}); and then some how refresh it?

I found one method. But I think it's kind a creepy way;)

By default table is created with editable true. I want to disable it with button, so on click:
1. tablename.bootstrapTable('destroy');
2. Changing var TABLE_EDITABLE = true;
3. iptable.bootstrapTable({editable: TABLE_EDITABLE});

And new table is displayed.

So is this right? It's ok for edit mode, but if I want to change only cellStyle or rowStyle, is it good to rebuild all ?

**Comment by wenzhixin** [comment]
Found a work around to solve your problem:
```
// disable row 2
$('tr[data-index="2"]').find('.editable').editable('disable');

// disable row 2, name field.
$('tr[data-index="2"]').find('.editable[data-name="name"]').editable('disable')
```

**Comment by omatic-hacker** [comment]
Thanks!
