### ISSUE TITLE
Column that don't exist to data - Error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4125]
I've a column with the data-field="actions" to the table with button for different actions.
For that I'm using data-formatter and data-events.
This column don't exist to data source.
With the boostrap-table version 1.12.1, it work well.
You can see it in action to this link:
https://jsfiddle.net/pqvu7e2d/15/

But with bootstrap-table version 1.13.2, it doesn't work.
You can see it in action to this link:
https://jsfiddle.net/pqvu7e2d/14/

With the version 1.13.2 the console return me this error message:
`Uncaught TypeError: Cannot convert undefined or null to object`

![image](https://user-images.githubusercontent.com/14294794/51459999-95dc0f80-1d5a-11e9-82a1-1d48bdaee6e6.png)

Thank you so much for this very good library.

**Comment by wenzhixin** [comment]
You need to define `operateFormatter` before:
```js
$('#table').bootstrapTable({data: data});
```

https://jsfiddle.net/wenyi/xfm39yvc/

**Comment by manukieli** [comment]
Ok, thank you so much for your answer, they resolve my problem.
