### ISSUE TITLE
Filter-control: get all data

### ISSUE THREAD

**Issue by emarcovaldi** [wenzhixin/bootstrap-table#4127]
I'm trying to get all data using filter control extension and client side pagination.
If I use the statement 
**$table.bootstrapTable('getData', false)**
I get only the filtered data.
Is it possible to get all the data also when I use the filter extension?
Thanks al lot

jsfiddle: [http://jsfiddle.net/emarcovaldi/k35Lacuj/](url)

**Comment by djhvscf** [comment]
By design if there is any filter applied in the table, the `getData` method will return the data with the filter.

**Comment by wenzhixin** [comment]
You can use variables to save all the data what you need.
