### ISSUE TITLE
sticky header can not scroll horizontally

### ISSUE THREAD

**Issue by macdoor** [wenzhixin/bootstrap-table#4128]
Scroll tbody horizontally, thead will not follow.

<img width="1021" alt="2019-01-22 9 24 23" src="https://user-images.githubusercontent.com/29733517/51506558-d190db00-1e27-11e9-90c4-a65d6c3605b3.png">

**Comment by wenzhixin** [comment]
Rewrited the code to fix this problem(https://github.com/wenzhixin/bootstrap-table/commit/2766e0074c2ddf863180549da336131b9615c65b) in develop branch.
Develop Example: http://dev.bootstrap-table.com/examples/#extensions/sticky-header.html
