### ISSUE TITLE
How to  Made Re-sizable Column in Bootstrap version 3.3.7 (bootstrap-table [wenzhixin])

### ISSUE THREAD

**Issue by kuldip1490** [wenzhixin/bootstrap-table#4129]
1. I did everything as per wenzhixin 
[https://github.com/wenzhixin/bootstrap-table/issues/4102#issuecomment-452342288](url)

2. but i can't resize column header  by dragging  
[https://github.com/wenzhixin/bootstrap-table/issues/4102#issuecomment-455769620](url)

3. here is my CSS sequence
`<link href="css/jquery.resizableColumns.css" rel="stylesheet" />`
`<link href="css/bootstrap-table.min.css" rel="stylesheet" />`

4. here is my JS sequence
    `<script src="js/jquery.resizableColumns.min.js"></script>`
`<script src="js/bootstrap-table.min.js"></script>`
`<script src="js/bootstrap-table-resizable.min.js"></script>`

5. Code
   `var $table = $('#table');`

   `$table.bootstrapTable("destroy");`

   `$table.bootstrapTable({`		
	`	method: 'POST'`,
	`	height: getHeight() + 50,`
	`	contentType: "application/json;charset=utf-8",`
	`	url: apiURL + "Service.asmx/getList",`
	`	dataType: "json",`
		`sidePagination: 'server',`
		`pageNumber: 1,`		
	`	pageList: [25, 50, 100, 200],`
	`	sortOrder: 'desc',`
	`	pagination: true,`
	`	queryParamsType: 'limit',`
	`	queryParams: queryParams,`
	`	pageSize: 25,`
	`	pagination: true,`
	`	silentSort: false,`
	`	sortName: 'Doc No',`
	`	resizable:true,`
	`	minimumCountColumns: 2,`

**Comment by wenzhixin** [comment]
Example and source:
https://bootstrap-table-examples3.wenzhixin.net.cn/index.html#extensions/resizable.html
https://bootstrap-table-examples3.wenzhixin.net.cn/index.html?view-source#extensions/resizable.html

**Comment by wenzhixin** [comment]
You need to remove the `height` option because this plugin does not work when data-height is set. https://bootstrap-table.com/docs/extensions/resizable/#known-issues

**Comment by kuldip1490** [comment]
Thank you for replay and it's working but  my page size are 200,100,50  and i have to scroll too long in bottom ,
there is a solution for height equally for all page size???

**Comment by kuldip1490** [comment]
OK ,let me try first then i will inform you

**Comment by kuldip1490** [comment]
i changed version from 1.13.2 to 1.12.2 but i was getting this error


```
Uncaught TypeError: that.$el.colResizable is not a function
    at initResizable (bootstrap-table-resizable.js:12)
    at bootstrap-table-resizable.js:65
```

**Comment by wenzhixin** [comment]
You need to update the dependence @kuldip1490.

> Dependence: [colResizable](https://github.com/alvaro-prieto/colResizable) v1.6

**Comment by kuldip1490** [comment]
ok let me check

**Comment by Falseee** [comment]
Please provide us an jsFiddle.

**Comment by UtechtDustin** [comment]
I close this issue because we got no example within 7 days, if you still need help please provide us an example and reopen the issue.
