### ISSUE TITLE
Improve for AngularJS

### ISSUE THREAD

**Issue by k010** [wenzhixin/bootstrap-table#413]
Hi, thanks for the plugin nice work !
I wonder if you can add a new functionality to the plugin so that instead of using $.ajax in initServer function, call an external function (if declared) that returns the same results, but with different behavior.
It would be helpful if you add this functionality in AngularJS, because i can call this FN form another ajax request provider.

Eg.

```javascript
var OPTIONS = {
serverCall: function(pageNumber, pageSize, searchText, sortName, sortOrder, filters) {
  // server call login with the options
  ...
  // more stuff
  ... 
  var result = {
    data: data.items
    totalRows: data.totalItems
  }
  return result
}
data: [],
cache: false,
height: 400,
striped: true,
pagination: true,
sidePagination: 'server',
pageSize: 5,
pageList: [5, 10, 20, 50],
search: true,
showColumns: true,
showRefresh: true,
minimumCountColumns: 2,
...
}
var elem = $('#table');
elem.bootstrapTable(OPTIONS);
```

Do you think it's posible ???
Thank !!

**Comment by djhvscf** [comment]
This sounds great! :+1:

**Comment by wenzhixin** [comment]
Use `ajax` option. Added an example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-ajax.html
