### ISSUE TITLE
bootstrap-table是否支持固定分页栏到浏览器的下方？

### ISSUE THREAD

**Issue by LittleSkylight** [wenzhixin/bootstrap-table#4132]
对于一页50条、100条数据的情况来说，只有翻到末尾的数据才能进行翻页操作，所以我想问下bootstrap-table是否支持固定分页栏到浏览器的下方？就像固定表头那样。

**Comment by wenzhixin** [comment]
不支持，需要自己扩展，你可以参考固定表头的写法。
欢迎提交 Pull Request。
