### ISSUE TITLE
1.13.2版本当表格设置footer时，隐藏某column时footer对应列不能隐藏。

### ISSUE THREAD

**Issue by jwang0512** [wenzhixin/bootstrap-table#4133]
开启showColumns为true，设置column的footer，
当取消勾选Column中的某一列，让其隐藏时，footer对应列不能正常隐藏。导致表格的列和footer的列对应不上。

发现问题的版本：1.13.2
经测试在1.11.1版本中正常。

**Comment by wenzhixin** [comment]
Fixed in v1.13.5.
https://examples.bootstrap-table.com/#options/show-footer.html
