### ISSUE TITLE
Export in PDF changing orientation landscape or portrait

### ISSUE THREAD

**Issue by Aragorn2004** [wenzhixin/bootstrap-table#4134]
Hi, i would know if it is possible changing orientation (landascape or portrait) on PDF export.

I've a large table and when i try to export files produced is always in portrait mode.

I've seen that the first Param is for landscape in jsPDF() which is l for landscape.
var pdf = new jsPDF('l', 'mm', [297, 210]); //The first Param is for landscape or portrait

but i don't know where i can do this implementation.
Thanks for your support.

bootstrap 3.3.7
bootstrap-table 1.13.2
tableExport.jquery.plugin Version 1.10.2

**Comment by wenzhixin** [comment]
Please check out the [tableExport.jquery.plugin](https://github.com/hhurz/tableExport.jquery.plugin/issues) repo. 
If you have a problem you can create an issue, thanks.
