### ISSUE TITLE
First Heading ROW not exported only in PDF format

### ISSUE THREAD

**Issue by Aragorn2004** [wenzhixin/bootstrap-table#4135]
Hi, i've a table where heading has two rows. The first row is not exported in PDF file in others format has exported well.  

is it a bug or i made a mistake?

<table id="datisede" class="table">
                        <thead>
                            <tr>
                                <th class="col-xs-12" colspan="6">HEAD</th>
                            </tr>
                            <tr>
                                <th class="col-xs-2" data-field="ID">ID</th>
                                <th class="col-xs-4" data-field="NAME">NAME</th>
                                <th class="col-xs-1" data-field="DATAPERS">DatePers</th>
                                <th class="col-xs-1 text-center" data-field="Level1">Level1</th>
                                <th class="col-xs-3" data-field="Level2">Level2</th>
                                <th class="col-xs-1" data-field="Level3">Level3</th>
                            </tr>
                         </thead>
</table> 

> <table id="datisede" class="table">
                        <thead>
                            <tr>
                                <th class="col-xs-12" colspan="6">HEAD</th>
                            </tr>
                            <tr>
                                <th class="col-xs-2" data-field="ID">ID</th>
                                <th class="col-xs-4" data-field="NAME">NAME</th>
                                <th class="col-xs-1" data-field="DATAPERS">DatePers</th>
                                <th class="col-xs-1 text-center" data-field="Level1">Level1</th>
                                <th class="col-xs-3" data-field="Level2">Level2</th>
                                <th class="col-xs-1" data-field="Level3">Level3</th>
                            </tr>
                         </thead>
</table> 

bootstrap 3.3.7
bootstrap-table 1.13.2
tableExport.jquery.plugin Version 1.10.2

**Comment by wenzhixin** [comment]
Please create an [issue](https://github.com/hhurz/tableExport.jquery.plugin/issues) to tableExport.jquery.plugin repo.
