### ISSUE TITLE
[EXT] group by working?

### ISSUE THREAD

**Issue by timoline** [wenzhixin/bootstrap-table#4138]
Hi,
just wondering, is the group by extension working with the latest?
I don't see an example on your website? only for v2....
https://examples.bootstrap-table.com/#extensions/group-by-v2.html

Do you have an example?

**Comment by Falseee** [comment]
In the documentation of the group-by extension i found this link/repository github.com/djhvscf/bootstrap-table-group-by.
Repository is not avaible, is the plugin still in development?
@djhvscf

**Comment by Falseee** [comment]
The groupby extension will be removed (#4281).
