### ISSUE TITLE
Cannot read property 'forEach' of undefined -Groupbyv2 and serverside pagination

### ISSUE THREAD

**Issue by soltani-azadeh** [wenzhixin/bootstrap-table#4139]
Hi
I have problem in using groupbyv2 extension with server side pagination but there is no problem whitout pagination.I tried a lot to create jsfiddle exmaple but it has problem in fetching data from server.
 now the error is the same both in my source and jsfiddle example(still has problem in fetching data from server):'Cannot read property 'forEach' of undefined' in line 119 of groupbyv2 source
jsfiddle Link:
http://jsfiddle.net/quahsgtn/3/
here is my data format :
{
"total":7,
"rows":[
{"shape":"circle","color":"red","area":"30"},
{"shape":"circle","color":"blue","area":"20"},
{"shape":"triangle","color":"yellow","area":"15"},
{"shape":"quadrangle","color":"pink","area":"40"},
{"shape":"quadrangle","color":"blue","area":"60"},
{"shape":"circle","color":"red","area":"70"},
{"shape":"sqaure","color":"white","area":"37"}
]
}
i use bootstrap-table version: 1.10.0,bootstrap-table-group-by version:1.0.0.
i know my issue is duplicate but i cant find any solution for this problem
Please Check it.
Thanks
@djhvscf 
@wenzhixin

**Comment by soltani-azadeh** [comment]
here is a working example with server side pagination (with out group by):
http://jsfiddle.net/adw076u3/
i just added group by and it doset work(Cannot read property 'forEach' of undefined error):
http://jsfiddle.net/evfwrmgd/
@djhvscf 
@wenzhixin

**Comment by UtechtDustin** [comment]
The group by extension will be merged/rewritten, this issue will be checked in #4413.

**Comment by mhnatt** [comment]
Hi @UtechtDustin , release 1.15.2 still does not fix the inability to "group by" when **data-side-pagination**  property is "_server_". It works when "_client_" but as soon as it is changed to "_server_", no data will load.

Fiddle by soltani-azadeh above (Jan 27) illustrates this.

Thank you!

**Comment by UtechtDustin** [comment]
Hi @mhnatt the extension(s) will be rewritten, so there is no new fix in the newest update.
See #4413

**Comment by rakucmr** [comment]
Hi, is this fixed?

**Comment by muratcakmaksoftware** [comment]
@wenzhixin this problem have been continued. That is a joke 😅 noooo 😄
Why client is work but isn't work server-side because broken backend 😄
