### ISSUE TITLE
1.13.3 Breaking Changes

### ISSUE THREAD

**Issue by TantumLabs** [wenzhixin/bootstrap-table#4141]
I installed 1.13.3 this morning and client-side search and showColumns both stopped working.

client-side search never fired any events regarless if the table came from HTML or url. 

showColumns said that the column was undefined.

**Comment by TantumLabs** [comment]
I figued it out. If you use the new version of the Cookie extension then what I mentioned doesn't work.

https://codepen.io/TantumLabs/pen/vbKVxV

**Comment by manukieli** [comment]
Ok, the version of develop branch work well for me.
Thank you.
