### ISSUE TITLE
Footer not shown if first column data-visible="false"

### ISSUE THREAD

**Issue by basementmedia2** [wenzhixin/bootstrap-table#4143]
I have created an example table with a footer.
The footer is not shown.
When i set the not visible column to visible the footer is shown.
Is this a bug? If yes is there a solution to workaround the bug?

Here's my jsfiddle

https://jsfiddle.net/u3Lbz1xf/1/

In the existing Issues i have only found the solution to use data-footer-formatter="myFunction".
But i use this and it doesn't work anyway ;-(

**Comment by dabcorp** [comment]
Hello,

I confirm, it's the same for me

**Comment by floriaus** [comment]
I have had the same issue. The resetFooter function is returning, when the first not visible column is found. For my purpose just replacing return with continue solved this issue for me (for now. didn't test further).

**Comment by wenzhixin** [comment]
Fixed in v1.13.5.
https://examples.bootstrap-table.com/#options/show-footer.html
