### ISSUE TITLE
Server side not recive the filter.

### ISSUE THREAD

**Issue by Fruchtgummi** [wenzhixin/bootstrap-table#4147]
Hi,

the the table send the filter values as Request Payload with POST. See the screenshot from chrome-console:

![image](https://user-images.githubusercontent.com/2059888/52077676-d9701e00-2591-11e9-8313-6237e29fb144.png)

How I get the order, offset, search & limit value on backend? This is not a Form-Object... 

Here the Request-Object, server side reciving.

```
&{POST /ajax/table/personen/get/all HTTP/1.1 1 1 map[Content-Length:[71] 
Accept:[application/json, text/javascript, */*; q=0.01] 
Referer:[http://localhost/persons-groups] 
Accept-Language:[de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6] 
Cookie: XXXXX 
User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36] 
Pragma:[no-cache] 
Origin:[http://localhost] 
Connection:[keep-alive] 
Cache-Control:[no-cache] X-Requested-With:[XMLHttpRequest] 
Content-Type:[application/json] Accept-Encoding:[gzip, deflate, br]] 0xc00002c980 <nil> 71 [] false localhost map[] map[] <nil> map[] [::1]:64161 /ajax/table/personen/get/all <nil> <nil> <nil> 0xc000236810}
```

**Comment by Falseee** [comment]
Its a simple POST request, how you get the values depends on the programming language.
As example for php to get the limit:
```php
<?php

$limit = $_POST['limit'];
```

So we cant help with that, read the documentation of the programming langue of your chooise.
***
Es ist ein einfacher POST request, wie du die Werte bekommst hängt von der Programmiersprache ab.
Wie du das limit in php bekommst kannst du oben dem Beispiel entnehmen.

Leider können wir dir damit nicht helfen, lies dir bitte die Dokumentation deiner ausgewählten Sprache durch.
