### ISSUE TITLE
get checked row index

### ISSUE THREAD

**Issue by omatic-hacker** [wenzhixin/bootstrap-table#415]
Hello

Is it possible to get "checked row" index? Maybe with getSelections ? Because it just return row data, and nothing about index of row that was selected

I tried such way, but it's kind of redundant:

```javascript
var allData = iptable.bootstrapTable('getData');
$.each(allData, function (i, rowData) {
                    if (rowData.checkBox === true) {
                        // do something with row, for example update by index;
                        // i -> is a index of selected row (checked box)
                        });
                    }
                });
```
Thank you for your time. I appreciate it very much.

**Comment by wenzhixin** [comment]
You can do it by this way:
```
$('input[name="selectItemName"]:checked').each(function () {
    // $(this).data('index');
});
```

Example: http://issues.wenzhixin.net.cn/bootstrap-table/#415.html

**Comment by omatic-hacker** [comment]
Thanks, i always do engineeringon bootstrap-table level forgeting about clean js ;)

**Comment by rahulmuraliqllabscom** [comment]
Hi I am having a column with a button. On click of that button I do some modification to the element of that row, for the purpose of updating that row I am collecting row index as follows
            var row = $(this).parent().parent();
            var rowindex = row.index();
but this works fine in the first page only. Like when I press a button on row 2 in second page(pagination) I am getting the row index as 2 itself but actually it is different. So when I update table row using update method and row index a  different row is getting updated
