### ISSUE TITLE
Does not work when adding to bundle

### ISSUE THREAD

**Issue by bmills74** [wenzhixin/bootstrap-table#4150]
When adding to the bundle I get console errors on load (jquery and boostrap occur before bsTable in the bundle and bundle is being rendered in the head tag ):

![image](https://user-images.githubusercontent.com/8238067/52123710-d3744e80-261e-11e9-95a1-1d45d4099ef4.png)

![image](https://user-images.githubusercontent.com/8238067/52123735-e424c480-261e-11e9-9d67-b93a2f210fe1.png)

Bundle looks like this:
![image](https://user-images.githubusercontent.com/8238067/52123799-13d3cc80-261f-11e9-880c-30e7470f2efd.png)

Only way to get it working is to load scripts including jquery in the view file. eg:
![image](https://user-images.githubusercontent.com/8238067/52123899-5f867600-261f-11e9-85a2-993701d6ed5d.png)

 What am i doing wrong please?

**Comment by bmills74** [comment]
I did that and still get the same error, and when trying to add it to an element get bootstraptable is not a function.

![image](https://user-images.githubusercontent.com/8238067/52130650-ad58a980-2632-11e9-95de-4f30d4da77b3.png)

Looking at page source it shows it's loaded though:
![image](https://user-images.githubusercontent.com/8238067/52130732-de38de80-2632-11e9-89e9-ba973a073f1c.png)

**Comment by wenzhixin** [comment]
Try this: https://bootstrap-table.com/docs/getting-started/introduction/

**Comment by bmills74** [comment]
Must be some strange conflict, just using the explicit declaration in the view file.
