### ISSUE TITLE
Example "Cookie" not working properly

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4151]
Your example link is not working properly when I want to hide some column:
**https://examples.bootstrap-table.com/index.html#extensions/cookie.html**

They return this error message:
![image](https://user-images.githubusercontent.com/14294794/52162943-0e3bbc80-26db-11e9-92d7-994c7b9cdcad.png)

**Comment by wenzhixin** [comment]
Fixed in v1.13.4: https://examples.bootstrap-table.com/#extensions/cookie.html
