### ISSUE TITLE
Search don't work with Filter Control with V.1.13.3

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4152]
With bootstrap-table V.1.13.3, when you put data to search input with Filter Control plugin, they don't search.
You can see the issue here: https://jsfiddle.net/2ot4d5r3/11/

In other way, if I put data to the search field and want to clean it with the button, they don't work.

![filter_control](https://user-images.githubusercontent.com/14294794/52163585-4a274f80-26e4-11e9-89c4-d453068423f7.gif)

**Comment by Falseee** [comment]
@wenzhixin or @djhvscf can be closed, is fixed in cookie extension version 1.14.2!
Working jsfiddle: https://jsfiddle.net/r9p2wLb7/
