### ISSUE TITLE
Footer sum current page not showing data

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4156]
I've using bootstrap-table V.1.13.4
I'm using footer into the table to calculate the total of the column of the current page, but the data are not showing.
You can view the result to this link:
http://jsfiddle.net/d7uh51k2/5/

**Comment by manukieli** [comment]
Waiting answer.
Thank you.

**Comment by wenzhixin** [comment]
Fixed in v1.13.5.
https://examples.bootstrap-table.com/#options/show-footer.html

**Comment by manukieli** [comment]
Yes, now run well.
Thank you so much.
