### ISSUE TITLE
Datepicker filter-control does not work correctly

### ISSUE THREAD

**Issue by SEModer** [wenzhixin/bootstrap-table#4157]
When you select a date, the search event does not occur until you yourself press the Enter button in the date selection field.
To fix this problem, i'm temporarily change the lines:
[Line 495 $(currentTarget).keyup();](https://github.com/wenzhixin/bootstrap-table/blob/078a0e3ca279e48f226cf9cac1e0e5f614eeccd0/dist/extensions/filter-control/bootstrap-table-filter-control.js#L495)
To that.onColumnSearch(_ref7);
May be it's incorrect, but work for me...

[JSFiddle ](http://jsfiddle.net/j70gmcvL/1/)

**Comment by Falseee** [comment]
The fixed version will be avaible in the next update.
