### ISSUE TITLE
Sticky / fixed header + sticky / fixed toolbar

### ISSUE THREAD

**Issue by LichtiMC** [wenzhixin/bootstrap-table#4159]
Anybody may have an idea on how to get the toolbar and the header to stay fixed on top of the table data?
Thank you very much in advance.

**Comment by wenzhixin** [comment]
Only support sticky header: https://examples.bootstrap-table.com/#extensions/sticky-header.html
If you want to sticky toolbar I think you can improve our extension or write a new extension.
Any PR is welcome.
