### ISSUE TITLE
Export Table CSS Issue?

### ISSUE THREAD

**Issue by Ka7ut0** [wenzhixin/bootstrap-table#4160]
Dear @wenzhixin 

Are there guidelines or documentation about which dependencies should be installed to make everything work together well? Currently, I've managed to assemble a mix of versions that more or less working together by trial and error, but as soon as one component gets replaced by a newer release, other problem are introduced.

I'm facing a few minor issues using bootstrap-table-export in which the icon & dropdown menu aren't rendered correctly. The icon could be fixed using the example code you wrote & shared on [JSFiddle](http://jsfiddle.net/wenyi/e3nk137y/17639/), which I'm gratefully added into my app. 

However, I can't wrap my head around the problem of CSS not being applied to the bootstrap-table-export dropdown menu,

![menu2](https://user-images.githubusercontent.com/47562131/52641617-8d01d800-2ed9-11e9-8c2d-922f9fe47cdd.png)

while it does get applied correctly to the dropdown menu that comes with the button created by `data-show-columns="true"`.

![menu1](https://user-images.githubusercontent.com/47562131/52641613-88d5ba80-2ed9-11e9-84e5-38b94a7caff3.png)

Basically, I am seeing the same as in the closed issue #3715.

Currently, the following is in use:
```
<link rel="stylesheet" type="text/css" href="/libs/bootstrap-4.2.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/libs/Font-Awesome-4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/libs/bootstrap-table-1.12.2/bootstrap-table.min.css">        

<script type="text/javascript" src="/libs/jquery-3.1.0/jquery-3.1.0.min.js"></script>
<script type="text/javascript" src="/libs/popper/umd/popper.min.js"></script>
<script type="text/javascript" src="/libs/bootstrap-4.2.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/libs/core-js-2.6.3/client/core.min.js"></script>
<script type="text/javascript" src="/libs/tableExport/tableExport.js"></script>
<script type="text/javascript" src="/libs/tableExport/jquery.base64.js"></script>
<script type="text/javascript" src="/libs/bootstrap-table-1.12.2/bootstrap-table.min.js"></script>
<script type="text/javascript" src="/libs/bootstrap-table-1.12.2/extensions/export/bootstrap-table-export.js"></script>
```
Updating bootstrap-table to the latest release breaks my application as certain tables won't even get filled after it successfully requested JSON-formatted data through an API.

Looking forward to solutions & work-arounds :+1:

**Comment by wenzhixin** [comment]
This bug fixed in [v1.13.0](https://github.com/wenzhixin/bootstrap-table/blob/develop/CHANGELOG.md#1130), I think you need to update to the latest version.

What's a problem when updating to the latest?

**Comment by Ka7ut0** [comment]
Thank you for your reply.

When updating v1.13.0 or later, the table itself doesn't get populated. The JSON response is correct, but it doesn't get showed in my UI any more. There are no errors in Firefox' Developer Tools console and it's not related to the data not getting received from the server. It's really strange.

I can't get to the child modal since there's no row visble to click on:

![screenshot-2019-2-22 catalog - vulnerability management](https://user-images.githubusercontent.com/47562131/53248968-2d64b300-36b7-11e9-9f19-fddbbb33e8d5.png)

Using v1.12.2 it gets populated (but it has the small cosmetic error with the export menu) 

![screenshot-2019-2-22 catalog - vulnerability management 1](https://user-images.githubusercontent.com/47562131/53249382-3d30c700-36b8-11e9-85bf-d8c16f653350.png)

It's hard to troubleshoot what exactly happened to get this different result.

![spectacle ns7366](https://user-images.githubusercontent.com/47562131/53249097-93513a80-36b7-11e9-8c81-0dd2b363179f.png)

**Comment by wenzhixin** [comment]
What is the format of your service response?

**Comment by Ka7ut0** [comment]
The response is structured like this:
```
{
  "data": [
    {
      "Highest": "9.3000000000", 
      "Id": 296, 
      "Manufacturer": "MICROSOFT", 
      "Name": "Designer (Sharepoint)", 
      "Version": "SharePoint 2013 (15.0)", 
      "Vulnerabilities": 6
    }, 
    {
      "Highest": "9.3000000000", 
      "Id": 259, 
      "Manufacturer": "MICROSOFT", 
      "Name": "Silverlight", 
      "Version": "", 
      "Vulnerabilities": 32
    }, 
    {
      "Highest": "9.3000000000", 
      "Id": 995, 
      "Manufacturer": "MICROSOFT", 
      "Name": "Office Viewer - Excel", 
      "Version": "", 
      "Vulnerabilities": 15
    }
  ]
}
```

**Comment by wenzhixin** [comment]
I think this example: https://examples.bootstrap-table.com/index.html#options/total-data-field.html can solve your problem.

**Comment by Ka7ut0** [comment]
I moved to 1.13.5 and no its "No matching records found".
Throughout the issues, I read I have to add `data-side-pagination="server"` when fetching JSON using `data-url`.

An example showed this as JSON: https://examples.wenzhixin.net.cn/examples/bootstrap_table/data
Is the "total" field in the JSON mandatory for this to work?

**Comment by wenzhixin** [comment]
If you are using the 'client' side pagination, you can use `reponseHandler`: https://examples.bootstrap-table.com/index.html#options/response-handler.html.

If you are using the 'server' side pagination, you can define the `total` field:  
https://examples.bootstrap-table.com/index.html#options/total-data-field.html#view-source    https://examples.bootstrap-table.com/json/data8.json

**Comment by Ka7ut0** [comment]
It works using the responseHandler! Thank you very much for your help :+1: 

```
<table id="scVulnsDetailsTable"
    data-height="450"
    data-toggle="table" 
    data-show-export="true" 
    data-icons-prefix="fa" 
    data-icons="icons" 
    data-show-columns="true" 
    data-show-refresh="true" 
    data-row-style="rowStyleForProduct"
    data-id-field="id" 
    data-pagination="true"
    data-response-handler="responseHandler" 
    data-page-size="10"
    data-page-list="[10, 25, 50, 100, All]"
    data-search="true">
    <thead>
        <tr>
            <th data-field="CVE" data-sortable="true">CVE</th>
            <th data-field="CVSS" data-sortable="true" data-formatter="cvssFormatter">CVSS</th>
            <th data-field="Summary">Summary</th>
            <th data-field="Status">Tag</th>
            <th data-checkbox="true" ></th>
        </tr>
    </thead>
</table>
```

```
function responseHandler(res) {
    return res['data']
}
```
![screenshot-2019-2-26 catalog - vulnerability management](https://user-images.githubusercontent.com/47562131/53399792-e6273c80-39ac-11e9-86e9-93547c6c9745.png)

The CSS is also applied to export menu using your latest release.

**Comment by wenzhixin** [comment]
Great! Close this issue.
If you like Bootstrap Table, give us a star! ⭐️⭐️⭐️ Thanks!

**Comment by mdjaman** [comment]
Sorry to bump this post but there is an issue with the refresh since it uses the alias "fa fa-sync" which is not updated in **font-awesome:4.7.0**. So can you change it by "fa fa-refresh"
