### ISSUE TITLE
showFullscreen button click does nothing

### ISSUE THREAD

**Issue by earlseay** [wenzhixin/bootstrap-table#4161]
showFullscreen button click does nothing

Any browser. The click event is not firing for the showFullscreen button effectively doing nothing. The button is there, but there is no event attached.

1. set showFullscreen: true
2. render the table
3. click the ful screen button
4. nothing happens

I believe this is because the fullscreen button click event was attempted to be attached to a button that wasn't created yet. You just need to move the event handler attachment down about 20-40 lines where the rest of them are.

**Comment by earlseay** [comment]
Pull request open for fix: #4162

**Comment by wenzhixin** [comment]
Merged into develop branch :)
