### ISSUE TITLE
Multiple tables don't seem to work when using HTML tags to create tables.

### ISSUE THREAD

**Issue by ragingdemon1357** [wenzhixin/bootstrap-table#4163]
For some reason the multiple tables do not work when using the HTML tags to create a table/row
Here is an example, i'm not sure if i'm missing something in my code as im pretty new to HTML in general, but i've tried everything i could think of. When you remove the <tr></tr> tags the multiple tables seems to work fine though. 

http://jsfiddle.net/7hv0xekw/

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/index.html#options/multiple-table.html

**Comment by ragingdemon1357** [comment]
> https://examples.bootstrap-table.com/index.html#options/multiple-table.html

this is exactly the source i was using, which was giving me issues which is why i was posting this. unless you had fixed the previous bug?

**Comment by wenzhixin** [comment]
```html
<table data-toggle="table">
  <thead>
    <tr>
      <th colspan="2" class="text-center">Basic Info</th>
    </tr>
  </thead>
</table>
```

Does not support only one column with `colspan = 2` because at least one `field` needs to be defined, otherwise, we don't know which column is corresponding.

http://jsfiddle.net/wenyi/fL1eah2z/2/
