### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by dskilken** [wenzhixin/bootstrap-table#4164]
Unfortunately I just pulled bootstrap-table out of my site because of performance issues. Using bootstrap table adds 12 seconds to the page load time. My table is only 27 columns and 200 rows. It does not involve server-side generated content. It is static, well-formed HTML on the page at load time. You cannot use column classes to hide columns, but instead have to use bootstrap-table's facility to hide and reveal columns. If you don't use bootstrap-table's facility, then you run the risk of blowing errors. In jQuery, if you use a selector that does not exist, the operation is ignored. In bootstrap-table if you use an index that does not exist, the code blows an error. Any changes to the table require a table refresh that takes over 4-5 seconds to complete. So hiding and revealing table columns or rows is way too slow using boot-strap table. I recommend the development team start profiling the code to figure out where the performance issues are. I believe one of the major slow functions is the table initialization. You should not have this kind of impact on page load time. I recommend you test to see if an index exists before trying to do an operation to avoid javascript errors.  - This would allow users to manipulate the table and delete data from it without causing indexing errors if you then use boot-strap table functions on the table.    I found another plugin that would let me lock the header and first column, and then used other plugins to add print and search capabilities. This took my 14 second load time with bootstrap-table down to one and a half seconds.

**Comment by timoline** [comment]
can't agree, 
5000+ rows in just a matter of seconds over here

**Comment by wenzhixin** [comment]
Merged into develop branch.
