### ISSUE TITLE
fixed headers not working with fixed heigth

### ISSUE THREAD

**Issue by rtohtmldev** [wenzhixin/bootstrap-table#4166]
if I set the table height, the table headers columns not equal to the data rows. I need a fixed height because I use more then one table on my site

**Comment by wenzhixin** [comment]
Do you mean: https://examples.bootstrap-table.com/#extensions/sticky-header.html extension?

**Comment by rtohtmldev** [comment]
No, I mean I set the Table height in the initialisation process so that the table header get fixed and the table heigth is 25% from the page. If I set this property in jquery the column width from header and body not equals look at this sample picture:
![image](https://user-images.githubusercontent.com/47448002/52783593-b003c780-3052-11e9-89b5-5a7f1126ac98.png)

**Comment by wenzhixin** [comment]
Example: https://examples.bootstrap-table.com/index.html#issues/283.html
Have you solved your problem? If not please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by kuldip1490** [comment]
still not working  , i have same issued since updated latest version "bootstrap-table@1.13.5"

**Comment by talarcon** [comment]
hi, i think this is because cloning only the header somehow loses width of columns
i added the next line, inside "fix bug: $.data() is not working as expected after $.append()" loop.
that.$header_.find(sprintf('th[data-field="%s"]', $(this).data('field'))).width($(this).width());

**Comment by UtechtDustin** [comment]
@talarcon 
If your Fix works, please submit a pull request :-)

**Comment by aducom** [comment]
Can you share where the fix should be applied? I have a similar issue and would like to verify if this fix works.

**Comment by UtechtDustin** [comment]
@aducom @talarcon @rtohtmldev 

Our [example](https://examples.bootstrap-table.com/#options/table-height.html) works fine, can somebody provide us an example (use our [online Editor](https://live.bootstrap-table.com/)).
---
Unser [Beispiel](https://examples.bootstrap-table.com/#options/table-height.html) funktioniert ohne Probleme, kann einer von euch ein Beispiel bereitstellen ? (Bitte unseren [online Editor](https://live.bootstrap-table.com/) benutzen).

**Comment by UtechtDustin** [comment]
I close the issue because we got no response within 7 days, if you still need help please reopen the issue and provide us an example.
