### ISSUE TITLE
showColumns cannot scroll down the sidebar in IE11

### ISSUE THREAD

**Issue by abdulshawakri** [wenzhixin/bootstrap-table#4167]
By creating a bootstrap table with `showColumns: true` table option, user cannot scroll down the sidebar in Internet explorer 11 browser.

Try to scroll by dragging the bar, it won't work. Only by clicking the arrows or using mouse wheel.

**Comment by djhvscf** [comment]
@abdulshawakri did you test this [example](https://examples.bootstrap-table.com/index.html#options/basic-columns.html) in IE? It is working for me

**Comment by UtechtDustin** [comment]
Also works for me fine with IE(11.379.17763.0), tested in a VM.

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 Day, if you still have the issue please reopen it.

**Comment by abdulshawakri** [comment]
I'm sorry for the late response @djhvscf @UtechtDustin, however, the issue is still valid maybe not in your example, but please check this one [Large Columns](https://examples.bootstrap-table.com/index.html#options/large-columns.html)

How to navigate the issue is by clicking the `show-columns` drop down and try to scroll using the sidebar, it will be interrupted and the drop down will close automatically.

**Comment by djhvscf** [comment]
This looks like a IE bug
