### ISSUE TITLE
Bootstrap-table.css v13.4 is not loading in ASP.NET 4.6

### ISSUE THREAD

**Issue by mnswiftone** [wenzhixin/bootstrap-table#4168]
I updated from 1.13.2 to 1.13.4 and now with version 1.13.4 the table header row shows only column names - no styling or icons.

The first thing I noticed was styling was gone for the table, and no longer shows sort icons.
From what I can see in IE or Chrome, the **bootstrap-table.css** version 1.13.4 does not load in a VS2017/ASP.NET 4.6 .aspx web page.

Reproduce:
Viewing the web-page in VS 2017, with versions 1.13.2:
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.13.2/bootstrap-table.css
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.13.2/bootstrap-table.min.js

1. Load page
2. The table shows with selected styling - showing the bootstrap-table sort icons.
3. In the IE Debugger DOM Explorer, Pick a column Header - it will show as this for example:
`   <div class="th-inner sortable both">Id</div>`
4. Viewing in the right-pane with Styles tab selected, it will show the respective classes that apply: 
`   .fixed-table-container thead th .both`   and other bootstrap-table css styles are shown.

Changing the bootstrap-table versions to 1.13.4 for CSS and JS:
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.13.4/bootstrap-table.css
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.13.4/bootstrap-table.min.js
Repeat after changing the versions to 1.13.4
1. Reloading the page,  Styling and sort icons are missing.
2. Selecting a table column in the DOM Explorer
3. Viewing the Styles tab - there are NO entries for bootstrap-table anywhere on styles tab for column names or anywhere on the page.

I created a VS2017 to test the respective versioned pages - but it was too big to upload here.
I did upload the .aspx pages:  Create an empty ASP.NET Forms website in Visual Studio*, and add the attached pages to it.  Right-click on one page, and set as default startup and run site.  
*(Visual Studio Community edition is a free download at https://visualstudio.microsoft.com/downloads/)
These Test pages Test1_13_2.aspx and Test1_13_4.aspx are code identical except for the version of bootstrap-table referenced as above, and clearly show the Test1_13_4.aspx page does not load the bootstrap-table.css file.
[SampleASP.NETTestPages.zip](https://github.com/wenzhixin/bootstrap-table/files/2870688/SampleASP.NETTestPages.zip)

Update - I created and uploaded the project to my repository so you can run it provided you have VS2017 or newer... (might load on older, not sure - but as mentioned above, VS2017 Community version is free) - and I deleted a MS package component, too big to upload - use package manager to re-install it... 
[https://github.com/mnswiftone/BootstrapTableVersionTest](https://github.com/mnswiftone/BootstrapTableVersionTest) 

Thanks!
Todd

**Comment by wenzhixin** [comment]
Sorry, I am not familiar with ASP.NET, 
can you provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem?

**Comment by TantumLabs** [comment]
In the example provided data-classes does not include .table which is why the table isn't rendering correctly. Previous to 1.13.4 it looks like everything still rendered correctly without .table. 

1.13.2
`.fixed-table-container thead th .both {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAQAAADYWf5HAAAAkElEQ…YSV17OatFC4euts6z39GYMKRPCTKY9UnPQ6P+GtMRfGtPnBCiqhAeJPmkqAAAAAElFTkSuQmCC);
}`

1.13.4
`.bootstrap-table .fixed-table-container .table thead th .both {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAQAAADYWf5HAAAAkElEQ…YSV17OatFC4euts6z39GYMKRPCTKY9UnPQ6P+GtMRfGtPnBCiqhAeJPmkqAAAAAElFTkSuQmCC);
}`

The solution is to include .table in your data-classes
`<table id="table" style="width:80%;"
                    data-toggle="table" 
                    data-search="true"
                    data-classes="table table-sm table-bordered table-striped table-hover"
                    data-thead-classes="thead-light"
                    data-url="https://examples.wenzhixin.net.cn/examples/bootstrap_table/data"
                    data-query-params="queryParams"
                    data-side-pagination="server"
                    data-pagination="true"
                    data-page-size="20"
                    data-page-list="[20, 50, 100, 200, 500]"
                    data-height="555">`

**Comment by mnswiftone** [comment]
Thanks Greg, 

For like a year now I've been coding tables as <table class="table-sm"... and not "table table-sm". On some I had found adding "table" in there too _increased_ the row height, defeating the purpose, so got by without it. I am betting it was poor design of other tools that messed it up back then.
Glad to see wenzhixin added table then, so it better matches bootstrap's design.
Sorry about the confusion - just never hit me it was that simple... and well, it did work in 1.13.2... LOL

**Comment by wenzhixin** [comment]
Great @mnswiftone. 
If you like Bootstrap Table, give us a star! ⭐️⭐️⭐️ Thanks!
