### ISSUE TITLE
Data-height and Filter control seems to break each other does not work with cookies nor saving data-show-columns

### ISSUE THREAD

**Issue by ragingdemon1357** [wenzhixin/bootstrap-table#4171]
The example will show you exactly what it looks like on my page, the Data height breaks the Filter control, one other thing is that the cookies no longer work when using  
"data-show-columns" any workarounds?
https://jsfiddle.net/L8zhjb0w/

**Comment by UtechtDustin** [comment]
Fixed in #4640
