### ISSUE TITLE
Export data with one dynamic column

### ISSUE THREAD

**Issue by guillermoizqgar** [wenzhixin/bootstrap-table#4172]
Hi, 

I would like to export my table to excel just like it does, but with one of my columns being dynamic, I give you an example:

I have 
customers | dish 1 | dish 2 | price

I'm able to export this table perfectly but what I would like to accomplish is that customers instead of displaying all the names of the customers let me choose in a select in excel the name of the client, like dynamic columns in excel, do I explain myself??

Thanks in advance.

**Comment by wenzhixin** [comment]
Sorry, I don't quite understand what you mean, can you attach a screenshot?

**Comment by guillermoizqgar** [comment]
Yep,
 
when I export the table it looks like that on excel:

![image](https://user-images.githubusercontent.com/3856494/53150888-fb1d5d80-35b1-11e9-8c87-2ff44f47907f.png)


what I would like to accomplish is that the column "nombre" be like a select inside excel to select just a name and show me all the information about that name, like that:

![image](https://user-images.githubusercontent.com/3856494/53151284-18066080-35b3-11e9-8764-8b8f6d9c93c1.png)

Where I can choose just a name for the column and see the information like that:

![image](https://user-images.githubusercontent.com/3856494/53151371-5865de80-35b3-11e9-970a-c209884ff3bf.png)
![image](https://user-images.githubusercontent.com/3856494/53151381-6156b000-35b3-11e9-9138-4f7b1b47e06c.png)

I hope is more clear now.

Thanks in advance.

**Comment by wenzhixin** [comment]
Can this feature be supported? @hhurz

**Comment by hhurz** [comment]
I'm sorry, but I don't know how you could do that. That's a very specific requirement...
