### ISSUE TITLE
How to filter date range without json data?

### ISSUE THREAD

**Issue by ragingdemon1357** [wenzhixin/bootstrap-table#4173]
Hello i've created a table using the HTML tags and not loading through JSON i'm wondering if theres a way to use the custom toolbar to search and filter by date range?

**Comment by wenzhixin** [comment]
Some feature like [this example](https://examples.bootstrap-table.com/#options/custom-toolbar.html)?

**Comment by ragingdemon1357** [comment]
> Some feature like [this example](https://examples.bootstrap-table.com/#options/custom-toolbar.html)?

Something like that, yes, i actually created a script using the moment.js to try and using the filterby option, but i can't seem to get it to work, i have 2 input boxes selecting the dates. I use Moment.js to get the date range in an array to use for the FilterBy. But when i click the button the table goes blank and empty, When i input the dates manually it filters it correctly. . 

```

<script>
    $(function() 
  {
    $('#table').bootstrapTable()
  }
  )
//Moment.JS Return Date Ranges
function getDates(startDate, stopDate) {
    var dateArray = [];
    var currentDate = moment(startDate);
    var stopDate = moment(stopDate);
    while (currentDate <= stopDate) {
        dateArray.push( '"'+moment(currentDate).format('YYYY-MM-DD')+'"' )
        currentDate = moment(currentDate).add(1, 'days');
    }
    return dateArray;
}
 
  
  $('#run').click( function() 
  { 
    var $table = $('#table')
    //var from=$("input[type=date][name=date1]" ).val();
    //var to=$("input[type=date][name=date2]" ).val();
    $table.bootstrapTable('filterBy',{ ETA:[getDates( $("input[type=date][name=date1]" ).val(), $("input[type=date][name=date2]" ).val() )] }) 

})


</script>
```

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/methods/#filterby
https://examples.bootstrap-table.com/index.html#methods/filterBy.html

The error code need to update:
```
/*
<td id="td-id-1" class="td-class-1">
  2019-02-01
</td>
*/
<td id="td-id-1" class="td-class-1">2019-02-01</td>

// dateArray.push( '"'+moment(currentDate).format('YYYY-MM-DD')+'"' )
dateArray.push(moment(currentDate).format('YYYY-MM-DD'))

// $table.bootstrapTable('filterBy',{ ETA:[getDates(from,to )] })
$table.bootstrapTable('filterBy',{ ETA: getDates(from,to ) })
```

The first error fixed by https://github.com/wenzhixin/bootstrap-table/commit/934513207160d7dd15b5da7dc5bd331f0f900997.
https://jsfiddle.net/wenyi/06pg2wms/11/
