### ISSUE TITLE
Retrieving number of rows after applying filter dynamically

### ISSUE THREAD

**Issue by dasguptahirak** [wenzhixin/bootstrap-table#4175]
I am using **bootstrap-table-filter-control.js** for applying column wise filter. I want to show the number of rows at the table header. And the number of rows need to be changed dynamically with respect to the filters and search applied. 

![image](https://user-images.githubusercontent.com/7932509/53159423-dcd45380-35eb-11e9-8fe0-6472a7b4a9c2.png)

As you can see the total count is 56. I am populating the complete json on load and then filters and search are applied at client side. 

My question is which event should I use to capture the filter and search event, so that I can update the value of Total Count accordingly.

**Comment by pchaganti** [comment]
👍

**Comment by Falseee** [comment]
Use the [onSearch](https://bootstrap-table.com/docs/api/events/#onsearch) Event, then calculate the rowcount with the [getData](https://bootstrap-table.com/docs/api/methods/#getdata) method.

Example: http://jsfiddle.net/3udfacm4/1/
