### ISSUE TITLE
Is there anyway to include Hyperlinks elements when loading data through json?

### ISSUE THREAD

**Issue by ragingdemon1357** [wenzhixin/bootstrap-table#4176]
As the tile mentions, when using the json data loading, can i define certain hyperlink for specific columns? My table contains hyperlinks that leads to other pages when clicking. My inital Table is created through HTML with PHP echo, due to Pagination the full data is not returned so i had to turn on pagination after i saved my current table as a json to load later on. the issue is that the <a></a>  styles i have set up for the colums are gone. Is there a way to use the current rows data as well such as
site.com/newpage?value=cell1&value2=cell5

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/column-options/#formatter
https://examples.bootstrap-table.com/index.html#options/format.html
