### ISSUE TITLE
detailView and colspan calculation issue

### ISSUE THREAD

**Issue by ericavijay** [wenzhixin/bootstrap-table#4177]
I have a little problem using both detailView and the way my table is setup. One of my column formatter sends back a child table for icons such as actions to be taken on the current row information.  However when I click on detailView the table gets jumbled as it tries to find all td elements in the current tr , including the children tables td elements. My fix is simple and can be a good suggestion for the current work. Instead of doing $.find("td") use $.children("td") - so in case someone else uses a columformatter function that creates child tables the detailview Colspan is not calculated incorrectly.

Here is my suggestion line - 1958 in code bootstrap-table.js v 1.13.4

`  $tr.after(Utils.sprintf('<tr class="detail-view"><td colspan="%s"></td></tr>', $tr.find('td').length))`
change to 
      ` $tr.after(Utils.sprintf('<tr class="detail-view"><td colspan="%s"></td></tr>', $tr.children('td').length))`

Thanks
Vijay

**Comment by wenzhixin** [comment]
Thanks for your feedback. 
If you like Bootstrap Table, give us a star! ⭐️⭐️⭐️ Thanks!
