### ISSUE TITLE
how to use flatJSON extension

### ISSUE THREAD

**Issue by yungwei** [wenzhixin/bootstrap-table#418]
I have a piece of code that pretty much the same as [Via JavaScript] (http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#via-javascript-table) except that I set sidePagination to true in my case. I want to use the flatJSON extension for the column below. How can I do that? Thanks.
```javascript
....
{
    field: 'branch.name',
    title: 'Branch',
    align: 'left',
    valign: 'middle',
    sortable: true
}
```
I tried the following based on [Flat JSON object] (http://wenzhixin.net.cn/p/bootstrap-table/docs/extensions.html#flatJSON), but it doesn't work.
```javascript
...
responseHandler: function adaptData(res) {
    return {
        rows: $.flatJSON({data:res.content, flat:true}),
        total: res.totalElements
    };
},
```

**Comment by omatic-hacker** [comment]
Hello

Show your Json pls. And re inspect flatJson extension include.
You just need to include flatJson extension, and create bootstrapTable with flat:true (JS) or data-flat="true" (HTML). Then just in field use: 'branch.name', that's all.

**Comment by yungwei** [comment]
Here's what the json string looks like. Thanks.

```json
{"content":[{"id":10,"englishName":"aaa","chineseName":"bbb","shortName":"ccc","location":"xxxxxxxxxxxxxxxxxxxxxx","branch":{"id":14,"code":"B0","name":"xxx"},"displayStartTime":"2014-04-01 09:00","displayEndTime":"2014-04-08 09:00","wholeDayActivity":true,"displayName":"aaa/bbb"},{"id":13,"englishName":"eee","chineseName":"fff","shortName":"002","location":"Maine","branch":{"id":8,"code":"E0","name":"www"},"displayStartTime":"2014-11-29 00:00","displayEndTime":"2014-12-03 00:00","wholeDayActivity":true,"displayName":"eee/fff"}],"sort":null,"totalPages":2,"numberOfElements":10,"totalElements":16,"firstPage":true,"lastPage":false,"size":10,"number":0}
```

**Comment by omatic-hacker** [comment]
do you have many items in content array ? If only one, you can just remove your responseHandlerand  use: 

```javascript
field: 'content.0.branch.name',
```

if array is more then one. you must figure out how to parse it with responseHandler

**Comment by yt8jbe7q63** [comment]
The content array is expected to have multiple items. 
What does a flatJSON-accepted json string with nested data look like? Thanks for your feedback.

**Comment by omatic-hacker** [comment]
Take a look for more information about flatJsonLook here: https://github.com/djhvscf/bootstrap-table-flatJSON

But I think that you can try to do this without flat JSON, for example

```javascript
    responseHandler: function (res) {
      return res.content;
    }
```

and then, for your field, use formatter:
```javascript
{
    field: 'branch',
    title: 'Branch',
    align: 'left',
    valign: 'middle',
    sortable: true,
    formatter: function (value, row) {
        return branch.name;
    }
}

**Comment by yt8jbe7q63** [comment]
I'll give it a try tonight. Thanks.

**Comment by wenzhixin** [comment]
Hi, you can see this example: http://issues.wenzhixin.net.cn/bootstrap-table/350.html

**Comment by yungwei** [comment]
I tried the approach provided by omatic-hacker and it works. Thanks.

**Comment by wenzhixin** [comment]
OK, close this issue.
