### ISSUE TITLE
Can I change the checkbox style?

### ISSUE THREAD

**Issue by crazyfan438** [wenzhixin/bootstrap-table#4180]
I need to change the checkbox to my own images.
I modify the code in bootstrap-table.js like this.
![checkbox1](https://user-images.githubusercontent.com/16830078/53282090-da9a0280-376d-11e9-932a-06cc4058ad1a.png)
and
![checkbox2](https://user-images.githubusercontent.com/16830078/53282102-1208af00-376e-11e9-9a0b-7f22789d4d1a.png)

then use the css to change the checkbox style

input[type=checkbox] {
    display: none;
}
input[type=checkbox] + label {
    background: url("images/check_normal.png");
    height: 15px;
    width: 15px;
    display:inline-block;
    padding: 0 0 0 0px;
}
input[type=checkbox]:checked + label {
    background: url("images/check_pressed.png");
    height: 15px;
    width: 15px;
    display:inline-block;
    padding: 0 0 0 0px;
}

Finally, I can see the checkbox with different style.
When I click the checkbox, only the checkbox in header will be checked.
I click the checkboxs in body, it just expand the row, and did not make the checkboxs checked.
How can I change the checkbox style??
Thanks.

**Comment by wenzhixin** [comment]
Not recommend modifying the source code, consider the process in `post-body` event.

Example:
https://examples.bootstrap-table.com/index.html#issues/383.html
https://examples.bootstrap-table.com/index.html#issues/383.html#view-source
