### ISSUE TITLE
No prompt when no rows are selected while exporting data

### ISSUE THREAD

**Issue by ly1989abc** [wenzhixin/bootstrap-table#4182]
No prompt when no rows are selected while exporting data

I would like to set the exportDataType to ‘selected’ and find that there are no any prompts in chinese when clicking the Export button without selected rows. At the same time, I want to add the current date to the exported filename, then I think the event method is needed for exporting data, thank you!

**Comment by wenzhixin** [comment]
Consider disabling the `export` button when setting `exportDataType: 'selected '` and selected rows are empty.
