### ISSUE TITLE
TreeGrid 选择自定义显示列字段后，无法展示树结构

### ISSUE THREAD

**Issue by leshalv** [wenzhixin/bootstrap-table#4183]
这是正常情况
![image](https://user-images.githubusercontent.com/30397655/53462966-84d09d80-3a80-11e9-8ee2-b9677fdb7b25.png)

自定义列以后：
![image](https://user-images.githubusercontent.com/30397655/53462884-4e931e00-3a80-11e9-8f4d-b3eedf12650a.png)

使用的当前版本 1.13.5

**Comment by wenzhixin** [comment]
修改了例子的代码：https://examples.bootstrap-table.com/index.html#extensions/treegrid.html
