### ISSUE TITLE
How do i get the count of selected rows?

### ISSUE THREAD

**Issue by ragingdemon1357** [wenzhixin/bootstrap-table#4184]
I want to only return selected rows column data.
Ex: 
row 1-Selected :Value 1 , **Value2**
row 2-NotSelected:Value1, **Value2**
row3-Selected : value1,value2

Row 1 and 3 are selected and i only want value 2's data but i don't want them to be in an array, i want to be able to concatenate them for later use for my SQl  query
aka ('Value1|Value2')

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/index.html#methods/getSelections.html

```
var selections = $table.bootstrapTable('getSelections')
selections.map(function (row) {
  return row.value2
}).join('|')
```

**Comment by ragingdemon1357** [comment]
Hello this did not work @wenzhixin do you have an example where i can get specific rows column values?
Again i just want to be able to get specific values 
row 1- Selected: **Value1** ,Value 2 , **Value3**

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
