### ISSUE TITLE
is there any way to append data from ajax ?

### ISSUE THREAD

**Issue by ragingdemon1357** [wenzhixin/bootstrap-table#4185]
As the above title says. i have an ajax code which returns json data from php 
```

   $(document).ready(function(){
  $.ajax({
       url: 'test.php',
       type: 'post',
       data:{query:query},
       dataType: 'json',
       success: function(data) 
       {
           $('#table2').bootstrapTable({
              data: data
           });
       },
       error: function(e) {
           console.log(e.responseText);
       }
    });
 });
   ```

This is how i'm doing it right now, and it seems to work, but when i use "append" the data is all blank

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/index.html#methods/append.html
You can use `append` method: 
```
$('#table2').bootstrapTable('append', data)
```

**Comment by ragingdemon1357** [comment]
> https://examples.bootstrap-table.com/index.html#methods/append.html
> You can use `append` method:
> 
> ```
> $('#table2').bootstrapTable('append', data)
> ```

This is exactly what i did but this is what ends up happening all the time...
![image](https://user-images.githubusercontent.com/46006821/53544945-d404e580-3af5-11e9-925f-9231bd747c9e.png)

**Comment by wenzhixin** [comment]
What's your response data format?

**Comment by ragingdemon1357** [comment]
> What's your response data format? I encode the array back as Json 

In my php script 
```$rows = array();

   while($r = mysqli_fetch_assoc($result)) 
   {
     $rows[] = $r;
   }

echo json_encode($rows);```
Back on my page  I also have to Json it again otherwise the above returned data comes back as "Object" if just return $rows it'll come back as Array.

```  $('#table2').bootstrapTable('append',{data: JSON.stringify(data)});```

**Comment by ragingdemon1357** [comment]
Yeah i think this is broken, i've tried converting the Json string back into an array in the format of the "insertData()" function like the append tutorial but it's not working, still showing up as blank.

**Comment by wenzhixin** [comment]
`$('#table2').bootstrapTable('append', data)`

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by wenzhixin** [comment]
Close this issue if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
