### ISSUE TITLE
Toggle columns halted issue

### ISSUE THREAD

**Issue by AliSultanKhan** [wenzhixin/bootstrap-table#4189]
if data not much then working fine but if i have more data in my table then halted. 
I tried to toggle some columns in the my report table, and everything halted for a good 15+ seconds.

**Comment by wenzhixin** [comment]
Consider to use 'server' side pagination instead?

**Comment by AliSultanKhan** [comment]
> Consider to use 'server' side pagination instead?

Brother, I am not asking about pagination I am asking about toggle columns option an image is attached. 

![image](https://user-images.githubusercontent.com/33395254/53721884-162b7f80-3e86-11e9-9b3a-73d27625c640.png)

**Comment by wenzhixin** [comment]
Is there a lot of rows of data?
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
