### ISSUE TITLE
the hide columns display in the filter menu droplist 

### ISSUE THREAD

**Issue by lj52man** [wenzhixin/bootstrap-table#419]
I set some columns hide (visible : false),but I use the filter plugin in the extension. But these columns also display in the  filter menu droplist, I don't hope this happen.Beg your help.3ks

**Comment by omatic-hacker** [comment]
Hello

Just remove title of the column from creation (in JS) or try to use <th data-field=".."/> without title (in HTML)

**Comment by lj52man** [comment]
@omatic-hacker I remove the title option, but the hide field display ‘undefined’ in the filter droplist .
![image](https://cloud.githubusercontent.com/assets/8624600/5703411/3b108cec-9aa1-11e4-8b29-400bb2da0554.png)
![image](https://cloud.githubusercontent.com/assets/8624600/5703416/45bcc1b0-9aa1-11e4-804c-48d7ee3ac1de.png)

**Comment by omatic-hacker** [comment]
Sorry I misunderstand your question.

go ahead with your normal title and just config filter

```javascript
        $('#filter-bar').bootstrapTableFilter({
            filters:[
                {
                    field: 'id',
                    label: 'ID',
                    type: 'range'
                    enabled: false// filter is visible by default
                }
            ]
});
```
