### ISSUE TITLE
Toggle Pagination halted issue 

### ISSUE THREAD

**Issue by AliSultanKhan** [wenzhixin/bootstrap-table#4190]
if data not much then working fine but if I have more data in my table then halted.
I tried to toggle pagination(Show/Hide Pagination button)  in my report table, and everything halted for a good 20+ seconds.

**Comment by wenzhixin** [comment]
ref #3998

**Comment by AliSultanKhan** [comment]
> ref #3998

Brother, I am talking about toggle pagination button. image is attached 

![image](https://user-images.githubusercontent.com/33395254/53790730-78998400-3f49-11e9-8f06-8f58cfa9b4f1.png)

**Comment by wenzhixin** [comment]
Consider improving performance issues that render too much data in a future release.

**Comment by wenzhixin** [comment]
Close this issue because it's duplicated with other issues.
