### ISSUE TITLE
使用Treegrid扩展时会报Uncaught RangeError: Maximum call stack size exceeded错。附解决方法

### ISSUE THREAD

**Issue by phper666** [wenzhixin/bootstrap-table#4191]
bootstrap-table版本为v1.12.1
treegrid扩展版本为v1.0.0 @author为YL
如图：
![image](https://user-images.githubusercontent.com/26764098/53793730-6cbdba00-3f69-11e9-8edc-07d125b0af71.png)
在使用treegrid初始化完成时，调用bootstrap-table的配置会报Uncaught RangeError: Maximum call stack size exceeded。
经过跟踪查询，是因为下图中圈红的地方合并时报错。
![image](https://user-images.githubusercontent.com/26764098/53793670-53b50900-3f69-11e9-9fa7-66c545ecf250.png)
原因：在插件treegrid/bootstrap-table-treegrid.js 中的initTr函数中，里面存在死循环，这个问题例如https://segmentfault.com/q/1010000010399965
解决方法如下图圈红代码，把item初始化一个默认值，不要直接赋值引用：
![image](https://user-images.githubusercontent.com/26764098/53793998-05ecd080-3f6a-11e9-9276-ebc08c680c61.png)

**Comment by wenzhixin** [comment]
谢谢你的反馈和解决方案，我试了下 v1.12.1，确实存在你说的问题，不过现在最新版本 v1.14.1 问题已经修复了。假如你喜欢 Bootstrap Table，麻烦给我们加个 **Star** ⭐️⭐️⭐️，谢谢。
