### ISSUE TITLE
PDF export does not show all rows with img tags

### ISSUE THREAD

**Issue by sebj54** [wenzhixin/bootstrap-table#4193]
Hi! 😃

# Description
When performing a PDF export with client side pagination, sometimes all rows are not in the PDF. I reproduce this issue every time I add a `<img>` tag in a cell (via a formatter)

It happens at least in Firefox (not tested with other browsers actually).

# Reproduction
[![Edit static](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9pjoxwmno?fontsize=14)

You'll see two tables in my reproduction example. The first table is working correctly (raw data) while the second has a special formatter:

```html
<th data-field="url" data-sortable="true" data-formatter="urlFormatter">URL</th>
```

```javascript
var urlFormatter = function(value) {
    return '<img src="https://img.icons8.com/color/24/000000/link.png" width="24" height="24"> ' + value
}
```

It seems that only images are the cause of the issue. I replaced the `<img>` tag by a `<strong>` tag and the `<strong>` is not rendered in PDF.

Let me know if I can provide more information or if I can help in any way!

**Comment by wenzhixin** [comment]
Please submit this issue to https://github.com/hhurz/tableExport.jquery.plugin/issues, thanks.

**Comment by wenzhixin** [comment]
Maybe this issue can solve your problem: https://github.com/hhurz/tableExport.jquery.plugin/issues/177

**Comment by sebj54** [comment]
Hi @wenzhixin, I am not sure the problem comes from the tableExport plugin because if I select a pagination size which will contain all rows (ie. selecting the `100` pagination size if I have less than 100 rows), my table is exported very well (with the pictures also).

I am not complaining for picture size, but for the number of rows in the PDF. It seems that Bootstrap table's script does not show all rows before the "screenshot" is made.

Do you see what I mean?

**Comment by wenzhixin** [comment]
OK, I will test the problem.

**Comment by sebj54** [comment]
Thanks! Don't miss my codesandbox link, you'll be able to see the problem there :)
Let me know if I can help!

**Comment by wenzhixin** [comment]
@hhurz Can we add a `callback` event after `downloadFile`? For example:
https://github.com/hhurz/tableExport.jquery.plugin/blob/master/tableExport.js#L1004

**Comment by hhurz** [comment]
@wenzhixin Please try last release v1.10.2. I added two new callback functions 'onAfterSaveToFile' and 'onBeforeSaveToFile'

**Comment by wenzhixin** [comment]
@hhurz Thank you for supporting so quickly, but I see that the version on [npm](https://www.npmjs.com/package/tableexport.jquery.plugin) does not seem to be updated.

**Comment by hhurz** [comment]
@wenzhixin Thanks for your reminder. I just published the new version on npm.

**Comment by wenzhixin** [comment]
Thanks for @hhurz, fixed this bug in the develop branch.

**Comment by sebj54** [comment]
Thanks to both of you for this quick fix!
