### ISSUE TITLE
hi,请问有什么方法可以更新'总共 1025 条记录'中的1025这个数字吗?

### ISSUE THREAD

**Issue by szwss** [wenzhixin/bootstrap-table#4198]
是这样的,我的程序在新添加数据时通过AJAX添加,成功后调用insertRow插入一行数据,然后removeByUniqueId删除了最后一条数据,整个过程完美解决,唯一有点瑕疵是,页角的>>显示第 1 到第 10 条记录，总共 1025 条记录,,中的1025数字没有改变,实际上这里应该+1,我试了几种方法,包括load,和totalRows选项指定+1,但是没有任何改变,我尽量不想调用接口再获取数据就能达到更新的目的,请问我该怎么做?

`
     formatShowingRows: function (pageFrom, pageTo, totalRows) {
            return '显示第 '+pageFrom+' 到第 '+pageTo+' 条记录，总共 '+totalRows+1+' 条记录sss'
        }
`
这样也试了,都不行.

**Comment by szwss** [comment]
这个插件太强大了,我想利用它的强大,尽量减少对服务器的请求数,所以refresh,和refreshOptions都不行,这两个方法有没有更新表的参数时不请求网络的方法吗?

**Comment by szwss** [comment]
使用load,倒是不会重新请求数据,但是,页脚的1025总数量,会变成undefined...

**Comment by wenzhixin** [comment]
你这个需求比较特殊，可以直接用 jQuery 对 dom 进行操作即可，例如：
```js
var options = $('#table').bootstrapTable('getOptions') // 使用 options 中去计算
$('#table').clostest('bootstrap-table').find('.pagination-info').text('xxx, 总共 xxx 条记录')
```

**Comment by szwss** [comment]
> 你这个需求比较特殊，可以直接用 jQuery 对 dom 进行操作即可，例如：
> 
> ```js
> var options = $('#table').bootstrapTable('getOptions') // 使用 options 中去计算
> $('#table').clostest('bootstrap-table').find('.pagination-info').text('xxx, 总共 xxx 条记录')
> ```

非常感谢,这方法可行,谢谢

**Comment by wenzhixin** [comment]
不用客气，假如喜欢 bootstrap-table，可以给我们加颗星 Star ⭐️⭐️⭐️ 谢谢 :)

**Comment by szwss** [comment]
> 不用客气，假如喜欢 bootstrap-table，可以给我们加颗星 Star ⭐️⭐️⭐️ 谢谢 :)

加啦,:)
