### ISSUE TITLE
Addrbar extension issue

### ISSUE THREAD

**Issue by pchaganti** [wenzhixin/bootstrap-table#4199]
Unable to get the addrbar extension to work. Using the develop branch. Tried the latest release too. Using Jquery latest - 3.3.1 and BS latest - 4.3.1. 

I can see the examples page does work. Is there an issue with the latest versions of the libs or am I not configuring something? Any help appreciated. Thanks!

JSFiddle with the search query param passed
https://jsfiddle.net/pchaganti/xvs3ohgm/11/show?search=123

JSFiddle itself
https://jsfiddle.net/pchaganti/xvs3ohgm/11/

**Comment by pchaganti** [comment]
Update : Got this to work. 

thx!

**Comment by pchaganti** [comment]
There is a bug associated with this extension. If you have a hash in the URL, when the Address bar is changed, it drops the hash.

In the Bootstrap examples, you can see this if you add a hash at the end of the URl. Then change the text in the search field. The URL changes correctly, but it drops the hash.

**Comment by wenzhixin** [comment]
Fixed in the develop branch.
