### ISSUE TITLE
[materialized]  and extensions

### ISSUE THREAD

**Issue by timoline** [wenzhixin/bootstrap-table#4200]
I converted my pages to the materialized theme.
But what about the extensions, like filter control or export, they are not working correct atm?

Custom filter buttons with filterby also not working...

Are you working on this...?

**Comment by wenzhixin** [comment]
Yes, I am working on this. But mainly in my spare time, and there are many features want to be added, so time will not be very fast.

**Comment by timoline** [comment]
ok,
i appriciate your hard work andI hope you fix this very soon
but you should place it somewhere on your website, i didn't know ...

**Comment by djhvscf** [comment]
Working on filter-control support

@wenzhixin
@timoline

**Comment by wenzhixin** [comment]
Export has supported #4278

**Comment by UtechtDustin** [comment]
Any news here @djhvscf ?

**Comment by UtechtDustin** [comment]
We will check all extensions with themes in #4239
