### ISSUE TITLE
Table draw complete callback event

### ISSUE THREAD

**Issue by pchaganti** [wenzhixin/bootstrap-table#4201]
Need to highlight rows in the table once a search is complete. The search is done either by typing into the search input or using the addrbar to autopopulate the search input from the URL.

Is there anyway to know when the search is complete and all the matching rows are drawn in the table. The loadSuccess and postBody fire before the data is drawn and visible in the table. Any way to plugin into this?

thanks!

**Comment by wenzhixin** [comment]
Can't `postBody` event solve the problem?

**Comment by pchaganti** [comment]
Not sure. Will look into this further.

thanks!

**Comment by pchaganti** [comment]
Was able to get this to work using the _postBody_ event.

thanks!
