### ISSUE TITLE
在同一个页面出现多个table后，都设置height属性后，缩放浏览器表头和内容无法对齐

### ISSUE THREAD

**Issue by 0zhouquan0** [wenzhixin/bootstrap-table#4203]
在同一个页面出现多个table后，都设置height属性后，缩放浏览器表头和内容无法对齐

**Comment by 0zhouquan0** [comment]
就第一个table会出现这个问题，表头的宽度固定了，不会随着浏览器的缩放而自动缩放

**Comment by Falseee** [comment]
@wenzhixin Translation pls..
Can't we require a english description of issues ? :/

**Comment by 0zhouquan0** [comment]
@Falseee   
In the same page of the browser, when two table tags appear and both are set to the height property, when the browser size is scaled, the first table will be out of alignment with the content.

**Comment by wenzhixin** [comment]
It's a bug because the table listens to the same resize event: `resize.bootstrap-table`.
I haven't found a better solution yet.

A workaround example to solve the problem: http://jsfiddle.net/wenyi/e3nk137y/44367/
FAQ: https://bootstrap-table.com/docs/faq/

**Comment by wenzhixin** [comment]
> Note that if there are multiple tables on a page and the height option is set at the same time, you need to add the `id` attribute to each table, otherwise, the window resize will not work properly.

 #4278 https://github.com/wenzhixin/bootstrap-table/pull/4278/commits/b64fff8ddf0bf0470f9754307cba793886dc5d22
