### ISSUE TITLE
Icon is not changing when expanding the detail view

### ISSUE THREAD

**Issue by iaxyz** [wenzhixin/bootstrap-table#4204]
When the detailView of a row is expanding, I would expect the Icon to change from 'detailOpen' to 'detailClose'. For me this is not working it stays the same icon.

https://jsfiddle.net/yLbnzwc7/3/

**Comment by Falseee** [comment]
I think the bug is fixed in 1.14.1!
Just replace the javascript file and your code works fine.

**Comment by wenzhixin** [comment]
@Falseee is right! The example here: https://examples.bootstrap-table.com/index.html#options/table-icons.html. 
If you like Bootstrap Table, give us a star! ⭐️⭐️⭐️ Thanks!
