### ISSUE TITLE
How to update selected row values

### ISSUE THREAD

**Issue by ragingdemon1357** [wenzhixin/bootstrap-table#4205]
Hello, i want to updated selected row values but, i don't want to change the entire row, only for a specific column.

An example would be 
[X]Value1|Value2|**Value3**
[ ]Value1|value2|**Value3**
[X]Value1|Value2|**Value3** 

The X are selected and the Bold are the columns i want to update.

**Comment by Falseee** [comment]
Set the [uniqueid](https://bootstrap-table.com/do

1. cs/api/table-options/#uniqueid) for each row.
2. Use the [getAllSelections](https://bootstrap-table.com/docs/api/methods/#getallselections) function to get the Rows which are selected.
3. Iterate through all fetched rows and use the function [updateByUniqueId](https://bootstrap-table.com/docs/api/methods/#updatebyuniqueid) or better use the functin [updateCellById](https://bootstrap-table.com/docs/api/methods/#updatecellbyid) to update them.

**Comment by ragingdemon1357** [comment]
> 1.Set the [uniqueid](https://bootstrap-table.com/docs/api/table-options/#uniqueid) for each row.
> 2. Use the [getAllSelections](https://bootstrap-table.com/docs/api/methods/#getallselections) function to get the Rows which are selected.
> 3. Iterate through all fetched rows and use the function [updateByUniqueId](https://bootstrap-table.com/docs/api/methods/#updatebyuniqueid) or better [updateCellById](https://bootstrap-table.com/docs/api/methods/#updatecellbyid) to update them.

Is there an example i can possibly follow for this? I'm not understanding the concept, mainly because the Getallselections returns  values seperated by Commas right? and doesn't updateCellByID only update 1 at a time? if i have 5 selected i don't know how that will help.

**Comment by Falseee** [comment]
The Function getAllSelections returns an object not a string with comma seperated values.
Here is your example:
https://jsfiddle.net/8u1gpk5w/1/

**Comment by Falseee** [comment]
Close this issue because there is no response since 11 days, if your problem still exists please reopen it, thanks!
