### ISSUE TITLE
change column width after load server side data

### ISSUE THREAD

**Issue by twu2** [wenzhixin/bootstrap-table#4206]
when use server side data, the table column width will depend on the header, not depend on the data (because it's not loaded).

Is this a bug?

Right now, I use a workaround for this issue, I need to do toggleView twice in post-body.bs.table event to force it change column width.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by twu2** [comment]
I found the issue only happen if using bootstrap-table-resizable extension:
https://jsfiddle.net/wxdy923h/

workaround: increase the setTimeout value in bootstrap-table-resizable will avoid this issue.

**Comment by UtechtDustin** [comment]
The columns has a normal width in your example, did i miss something ?

**Comment by twu2** [comment]
if without resizable extension, the column width is depend on the data.
if with resizable extension, the column width is not adjust.

I make a patch to fix this issue.

```
--- bootstrap-table-resizable.orig.js   2019-03-18 09:13:02.000000000 +0800
+++ bootstrap-table-resizable.patch.js  2019-06-12 10:37:11.873485478 +0800
@@ -7,6 +7,8 @@
 (function($) {
   "use strict";

+  var bInitBodyDone = false;
+
   var initResizable = function(that) {
     if (that.options.resizable && !that.options.cardView && !isInit(that)) {
       that.$el.resizableColumns();
@@ -46,6 +48,8 @@
       .on("column-switch.bs.table, page-change.bs.table", function() {
         reInitResizable(that);
       });
+
+    bInitBodyDone = true;
   };

   BootstrapTable.prototype.toggleView = function() {
@@ -63,10 +67,9 @@
     _resetView.apply(this, Array.prototype.slice.apply(arguments));

     if (this.options.resizable) {
-      // because in fitHeader function, we use setTimeout(func, 100);
-      setTimeout(function() {
+      if (bInitBodyDone) {
         initResizable(that);
-      }, 100);
+      }
     }
   };
 })(jQuery);
```

**Comment by UtechtDustin** [comment]
@twu2 
Thank you for your patch, could you submit a PR with a working demo (jsfiddle) ?

**Comment by UtechtDustin** [comment]
Seems fixed in the newest version.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3418

If this issue still exists please comment and we will reopen the issue.

**Comment by N0tMy4cc0unt** [comment]
Hi,

I do not think it's resolved yet, even on provided example https://live.bootstrap-table.com/code/UtechtDustin/3418 it is still present:

1. on initial load, you can notice 3rd column is not wide enough for content - it looks like column width determination is based only on column header content

![image](https://github.com/user-attachments/assets/65c12707-6282-4b71-bb00-e24da365247e)

2. if you click first button above table ("toggle") and again to restore grid view - now you will notice how column width is much better determined

![image](https://github.com/user-attachments/assets/25c50554-7ddb-4726-ad86-686157ec2726)
