### ISSUE TITLE
multiple-sort not working with data-query-params="functionName"

### ISSUE THREAD

**Issue by twu2** [wenzhixin/bootstrap-table#4207]
If we assign queryParams with data-query-params="functionName", then the queryParams is a string, not a function.
It will make multiple-sort not working.

This patch will fix this issue.

[multiple-sort-data-query-params.zip](https://github.com/wenzhixin/bootstrap-table/files/2964652/multiple-sort-data-query-params.zip)

**Comment by twu2** [comment]
example for this bug:
https://jsfiddle.net/c9bfay0g/1/

**Comment by wenzhixin** [comment]
Merged in the develop branch.
