### ISSUE TITLE
how to export all the data for the table not only current page.

### ISSUE THREAD

**Issue by lj52man** [wenzhixin/bootstrap-table#421]
I use the extensions/export plugin, and I use the client pageination(sidePagination : "client").I want to export all the data include the data which in the other page. For example I has 3 pages data, but I can only export the current displayed page data.

**Comment by wenzhixin** [comment]
Hi, I think you can use the new feature to do that: http://issues.wenzhixin.net.cn/bootstrap-table/#424.html

**Comment by wenzhixin** [comment]
Close this issue.

**Comment by bbrock171** [comment]
The link above is broken. What new feature?

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html

**Comment by imeleges** [comment]
I have the same issue, and if I understand you @wenzhixin correct there's only one option to export all the data for the table is to toggle pagination?
I have v.1.14.2 of bootstrap-table

**Comment by Falseee** [comment]
No, you can set [exportDataType](https://bootstrap-table.com/docs/extensions/export/#exportdatatype) to `all`.

**Comment by emileroy** [comment]
Hi, i had the same issue having to export the table's data for more than the current page and didn't want the user to select 'All' in pagelist. Pretty sure i could've done way better but maybe it could help someone with the same issue...

```
var $table = $('#table');
var seeAll = false;                            // Boolean to veridy if we're exporting
var myLimit = 10;
var previousLimit = 10;
// Function triggered but a button
function exportExcel() {
    seeAll = true;                                //Sets that we are exporting

    // this is where it's a little sketchy, i'm getting the text from
    // the table where it show the number of rows in total (class pagination-info)
    var rowsHtml = ($('.pagination-info')[0].innerHTML).trim();

   // Then spliting it in a array
    var arrRows = rowsHtml.split(" ");

     // sets the actual pagelimit, exemple : 'Showing 1 to 10 of 156 rows' => 10 - 1 + 1 = 10
     previousLimit = arrRows[3] - arrRows[1] + 1;

     //now sets the new limit, so with the example we take 156
     var newLimit = arrRows[5];

    //sets the limit we want to send in pramater to the new one
    myLimit = newLimit;

     //refresh the table, triggering the queryParams ( our table's dataQueryParams )
    $table.bootstrapTable('refresh');

}

function queryParams(params) {
   // if we are exporting
    if (seeAll){
        //sets the limit parameter
        params.limit = myLimit;
    }

    return params;
}

//on the event of the successful loading of the table, needed otherwise the table wont be done 
// generating before the export goes on
$table.on('load-success.bs.table', function (data) {
    
   //if again we are in exportation, not just a normal generation of the table
    if (seeAll){

        //your export of the table, in any way you'd like
        $table.tableExport({type:'excel',
            mso:{fileFormat:'xlsx'}
        });

       // sets the new limit parameter to the previous one before showing all rows, in our case '10'
        myLimit = previousLimit;

        //refresh the table with new limit parameter
        $table.bootstrapTable('refresh');

        // end the "export mode"
        seeAll = false;
    }
});
```

So basically generate table with the total number of row with limit parameter, exporting it and then reverting it tho the previous limit parameter.

Apparently you can use the exportDataType in Bootstrap v4, but for some reason i need to stay in v3, so here's a little work around  for people with older versions :)

I hope this could help someone !
