### ISSUE TITLE
How to Get QueryParam from Table?

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#4210]
Hi all,
I created a table with using odata. Now, i must get this table url which created by query params. But i cant get it. 

Table params:

```
$('#tableid').bootstrapTable({
url:'http://localhost/project/odata/model',
queryParams:function(e){
return urlwithparams;
},
...,
...,
other options...
})
```

How can i get this table full url like this :'http://localhost/project/odata/model?id=1&name=test

Thanks...

**Comment by wenzhixin** [comment]
Added an example for you: https://examples.bootstrap-table.com/#issues/4210.html

**Comment by softuse** [comment]
在哪里？ 简单一点 介绍比较好吧？下面这个？
  var $table = $('#table')
  var params = {}

  function queryParams(_params) {
    params = _params
    return _params
  }

  function mounted() {
    $('button').click(function () {
      alert($table.bootstrapTable('getOptions').url + '?' + $.param(params))
    })
  }
