### ISSUE TITLE
Export all records server side pagination(#3830) fails on javascript instantiated table

### ISSUE THREAD

**Issue by mnswiftone** [wenzhixin/bootstrap-table#4211]
I cannot get the fix for #3830 to work for a javascript defined/created bootstrap-table i.e. `$table.bootstrapTable({ ... });`
Thought this might be an important issue since [#3830 is on the main site examples issue page](https://examples.bootstrap-table.com/#issues/3830.html) with an example - for which the html version works, but as javascript it won't. 

I have tested in Chrome and Mozilla using jsfiddle - and both exhibit the same problems.
### Code used (shortened version shown below from my [jsfiddle example](https://jsfiddle.net/MNSwiftOne/7aqj42d5)):

Problems I am seeing with #3830 :
1. the **!options.pagination** part causes the table first load to load all rows when the table is initially created, since options.pagination is undefined (confirmed via alert popup below).
options.pagination has a value of undefined when the bootstrap-table is created via javascript. Apparently **!options.pagination** evaluates as !undefined which equates to true, resulting in table loading all rows even though the drop-down shows it is supposed to show 5 rows.
A work-around I added was to just test for undefined within the Queryparams call
changing
`   if (!options.pagination) {`
to
`   if (options.pagination != undefined && !options.pagination) {`

2. When used with a MS .NET Web API - I also discovered that on export, the params parameter set does not contain all it's usual parameters - which causes problems for .NET WebAPI calls. Even if defined as optional in the WebAPI - if the parameters are missing from the Request - it does not work unless all parameters are present.  Adding **offset**, **sort**, and **order** with valid empty values fixes that bug (see sample below).

Other issues I cannot figure out - possibly related to javascript initiated bootstrap-table design:

3. My example uses a custom Toolbar Export link copied from 
#2234: Custom export link: [http://jsfiddle.net/wenyi/wc0zLpef/1/](http://jsfiddle.net/wenyi/wc0zLpef/1/). 
From what I understand - **the toolbar should not show the export drop-down when a toolbar export button** is defined - but it does.
4. My **toolbar custom Export button does NOT export all rows** - probably as it doesn't use bootstrap-table-export functionality.

HOW to get this to work? Should there be a custom event added when bootstrap-table-export is loaded? So when it is loaded, it would add a new method like $table.bootstrapTable('Export') - and thus use the nice bootstrap-table-export all rows server-side pagination support to exporting?

Am I not understanding this correctly - or did I find new bugs?
Thanks

### References:
```
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>
<link href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"/>
<link href="https://unpkg.com/bootstrap-table@1.14.1/dist/bootstrap-table.min.css"/>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/bootstrap-table@1.14.1/dist/bootstrap-table.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/bootstrap-table@1.14.1/dist/extensions/export/bootstrap-table-export.js"></script>
```
### HTML:
```
<div id="toolbar">
    <button id="export" class="btn btn-sm btn-primary">Export</button>
</div>
<table id="table"></table>
```
### Javascript:
```
 var $table = $('#table');
 var newcolumns = [];

 $(function() {
   $("#btnLoad").on('click', function() {
     setupTable();
     loadTable();
   });

   $('#export').click(function() {
     $table.tableExport({
       type: 'csv',
       escape: false,
       exportDataType: 'all',
       refreshOptions: {
         exportDataType: 'all'
       }
     });
   });

   $("#table").on('load-success.bs.table', function(e, data) {
     $table.bootstrapTable("hideLoading");
   });
 });

 function setupTable() {
   newcolumms = [{
       title: 'Item ID',
       field: 'id',
       align: 'center',
       valign: 'middle',
       sortable: true,
       footerFormatter: totalTextFormatter
     },
     {
       field: 'name',
       title: 'Item Name',
       sortable: true,
       footerFormatter: totalNameFormatter,
       align: 'center'
     },
     {
       field: 'price',
       title: 'Item Price',
       sortable: true,
       align: 'center',
       footerFormatter: totalPriceFormatter
     }
   ];
 }


 function loadTable() {
   $("#divStart").hide();
   $("#divResults").show();
   $table.bootstrapTable({
     url: "https://examples.wenzhixin.net.cn/examples/bootstrap_table/data",
     method: "GET",
     queryParams: myQueryParams,
     columns: newcolumms,
     classes: "table table-sm table-bordered table-striped table-hover",
     theadClasses: "thead-light",
     toolbar: "#toolbar",
     pagination: true,
     sidePagination: "server",
     pageSize: "5",
     pageList: "[5, 10, All]",
     search: false,
     height: "500",
     showExport: true,
     exportTypes: ['csv'],
     exportDataType: 'all',
     showFooter: true,
     exportFooter: true
   });
   $table.bootstrapTable('showLoading');
 }


 function myQueryParams(params) {
   var options = $table.bootstrapTable('getOptions');
   //alert('in queryparams');
   if (options.pagination === undefined) {
     alert('options.pagination is undefined on initial load')
   }
   if (options.pagination != undefined && !options.pagination) {
     // sample data only contains 20 items - so replace limit = options.totalRows;
     params.limit = 20;
     // .NET API fails if these params are unset
     // if they = undefined  they are not passed to server
     // for some reason all params must be present when submitted to a .NET Web API
     // even if defined as optional in .NET method - call fails if not present
     params.offset = 0;
     params.sort = '';
     params.order = 'asc';
   }
   var p = {
     limit: params.limit,
     offset: params.offset,
     order: params.order,
     sort: params.sort
   }
   return p;
 }

 function totalTextFormatter(data) {
   return 'Total'
 }

 function totalNameFormatter(data) {
   return data.length
 }

 function totalPriceFormatter(data) {
   var field = this.field
   return '$' + data.map(function(row) {
     return +row[field].substring(1)
   }).reduce(function(sum, i) {
     return sum + i
   }, 0)
 }
```

**Comment by Falseee** [comment]
1. At first glance I can not see any errors (without testing)
2. Does `MS .NET Web API` requires "new" fields and this is the cause of the error or does thes export Button sends not all parameters ? (could you provide an example?)
3. On your [jsfiddle](http://jsfiddle.net/wenyi/wc0zLpef/1/) i cant see any export drop down.
4. You custom export Button exports all 800 columns for me. ([Exmaple](http://jsfiddle.net/f7x8nmuh/1/))

**Comment by mnswiftone** [comment]
> 1. At first glance I can not see any errors (without testing)

Sorry - I had my sample code with the 'work-around' on it.  I updated my sample to his original sample and commented out mine. 
His:
`if (!options.pagination) {`
Mine:
`if (options.pagination != undefined && !options.pagination) {`

If you compare to the original sample @wenzhixin released - his fix does not work for javascript initialized tables - the when you click **Load** on mine - you will see a pop-up called because the variable that he is using to determine whether to send all rows - is undefined, and !undefined = true - so it loads all the rows.

> 2. Does `MS .NET Web API` requires "new" fields and this is the cause of the error or does thes export Button sends not all parameters ? (could you provide an example?)

Again - I copied from his samples - and he states it should export all rows from the **exportDataType: 'all'**, I guess:
```
$('#export').click(function() {
     $table.tableExport({
       type: 'csv',
       escape: false,
       exportDataType: 'all',
       refreshOptions: {
         exportDataType: 'all'
       }
     });
```
I provided the example to prove what fails - has nothing to do with .NET - as I demonstrate in my example.  .NET javascript is the same as all javascript - no "new" keywords.
I designed using a dynamically created bootstrapTable because I am sharing the table key on the page between multiple data-sets - all downloaded via the bootstrapTable initialization after the user chooses the data to display - that is how I discovered this problem.
The alternative was to put 6 table tags for bootstrapTable on the page and swap divs - making the page immensely larger, and it is not possible to load all the tables as the data can be large.
Loading dynamically works - it does load the data - just doesn't show correctly or export correctly.
I did not need to provide that functionality here to demonstrate this problem. If you want to understand why I did my design this way - just imagine a drop-down, and on selection:  it assigns the columns to the bootstrapTable to match the expected data, then it loads the data from a remote API by passing parameters to select which data, and filter (paging) it, then returning it to the page.  Also on selection,

> 3. On your [jsfiddle](http://jsfiddle.net/**wenyi**/wc0zLpef/1/) i cant see any export drop down.

The url you typed is Wenyi's example - not my jsfiddle. 
Mine is at 
[https://jsfiddle.net/MNSwiftOne/7aqj42d5](https://jsfiddle.net/MNSwiftOne/7aqj42d5)
As shown in Wenyi's example (what I based mine on), **there is no drop-down shown** - correct.
But on my example - it does **show both the drop-down and my export button**.
It should only show my Export button - and not the drop-down.

> 4. You custom export Button exports all 800 columns for me. ([Exmaple](http://jsfiddle.net/f7x8nmuh/1/))

Again - no idea where you got that link from - it is not my example.
My example only exports **the 5 visible rows** - not all in the sample (which is actually 20, not 800).  Don't know why mine only does visible, something about the fact my table is not present when page loads possibly - that is why I reported this...

**Comment by mnswiftone** [comment]
Update on the 4 issues of my original post - Now Tested on 1.14.2

1. The **options.pagination being undefined** issue still exists - resulting in display of all rows with pagination enabled when it should only show the page size selected.  

2. I have not tested this - need to debug a session and being new to jsfiddle - no idea how to do that. . Reading, I didn't make it very clear - the issue was that when calling the built-in Export via drop-down - the params collection sent with the API call (passed into  `function myQueryParams(params) {...}`
When the $table.bootstrapTable built-in code to export calls the params function to get the data total size to export - i**t is missing all the normal pagination parameters offset, sort, and order** - and the MS API requires them to be present. They should be passed with offset=0, sort='', order='asc' defaults as I did in my jsfiddle - see the myQueryParams function there.
 
3. The showing 'both' the Export custom button and the drop-down list **HAS BEEN FIXED** - 👍 
 
4. If I put my fix in to test for !options.pagination===undefined, **the Export button still only exports the visible (page-size) row list and not the entire 800 rows**. I still only get 5 items exported when I click my export button.

@wenzhixin (Thanks for updating your sample data to really be 800 rows instead of 20)

Here is a screenshot showing, after scrolling to the bottom on Page 1 with 5 items per page selected - showing item 799... this is not right, and caused by issue 1 above.
![20190327myjsfiddlebug](https://user-images.githubusercontent.com/33492971/55119533-3d115600-50c0-11e9-9d8f-ba17a839fb6f.jpg)

**Comment by UtechtDustin** [comment]
This issue is already very old so please recomment if the issues still exists and we will reopen the issue.

But it seems its working fine out of the box right now!
Example: https://live.bootstrap-table.com/code/UtechtDustin/1743
- Javascript instantiated
- The first page shows only the selected pageSize (in that example: 10)
- The export, fetch the whole data from the server and also exports all 800 entries.
