### ISSUE TITLE
Bootstrap Table 1.14.1 not on cdnjs

### ISSUE THREAD

**Issue by olafcm** [wenzhixin/bootstrap-table#4212]
Latest release does not show up on the cdnjs.com CDN: https://cdnjs.com/libraries/bootstrap-table/1.14.1
Can this be fixed?
Thanks 😊

**Comment by wenzhixin** [comment]
You can use UNPKG:
https://bootstrap-table.com/docs/getting-started/introduction/#quick-start

**Comment by olafcm** [comment]
Yes, jsDelivr and UNPKG would probably also do but I prefer cdnjs since I load all my libs from their CDN.
I will ask cdnjs to resolve the issue on their side.
Thanks!

**Comment by wenzhixin** [comment]
v1.14.2 released, close this issue because it is a bug: https://github.com/cdnjs/cdnjs/issues/13288.
