### ISSUE TITLE
Bootstrap-Table not updated to v1.14.1

### ISSUE THREAD

**Issue by olafcm** [wenzhixin/bootstrap-table#4213]
Git auto-update for this popular library seems to have failed.
Latest release is 1.14.1: https://github.com/wenzhixin/bootstrap-table/releases
Not available on cdnjs: https://cdnjs.com/libraries/bootstrap-table/1.14.1
Author has no clue: https://github.com/wenzhixin/bootstrap-table/issues/4212
Used to work.
Thanks for checking 😊

**Comment by wenzhixin** [comment]
You can submit an issue to https://github.com/cdnjs/cdnjs.

**Comment by olafcm** [comment]
Sorry, wanted to open it there - my mistake 🙄
