### ISSUE TITLE
Serial No column option in Grid

### ISSUE THREAD

**Issue by sadafr** [wenzhixin/bootstrap-table#4214]
Is there any option in the latest version(Bootstrap Table 1.14.1) to add serial no column in grid which will work for all actions like sorting and searching (Server Side).

It would be really great if anyone can help in this regard.

Thanks.

**Comment by wenzhixin** [comment]
Do you mean to add an index field? #1914

**Comment by sadafr** [comment]
yes, will this behave same for search, sorting and export (all server side )

**Comment by wenzhixin** [comment]
Added an example for you: https://examples.bootstrap-table.com/index.html#issues/4214.html

**Comment by sadafr** [comment]
Thanks @wenzhixin for providing an example.

**Comment by Cybernonk404** [comment]
> Added an example for you: https://examples.bootstrap-table.com/index.html#issues/4214.html

Your answer and example still helpfull until now! Big thanks for you!
