### ISSUE TITLE
Importing JS from package problem

### ISSUE THREAD

**Issue by SupremeSalvatore** [wenzhixin/bootstrap-table#4215]
First I install bootstrap-table from npm install bootstrap-table, then I want to import 'bootstrap-table' , and it doesnt work for javascript I'm getting error:
Plugin 0 specified in "PATH/node_modules/bootstrap-table/.babelrc" was expected to return an object when invoked but returned "boolean"PATH/node_modules/bootstrap-table/.babelrc0
Any help or suggestion how to work with bootstrap-table via package?

**Comment by Falseee** [comment]
@wenzhixin Fixed by  #4268 ?

**Comment by wenzhixin** [comment]
#4272
