### ISSUE TITLE
Resizing the inline edit 

### ISSUE THREAD

**Issue by rajeshbtlit** [wenzhixin/bootstrap-table#4217]
Bootstrap table inline edit of column, option for resizing the edit pop over.

1) Create a bootstap table
2) Make the column editable, making value column as editable
```
<tr>
                        <th style="width:25%" data-field="attributeName" data-sortable="true">Name</th>
                        <th style="width:25%" data-field="attributeValue" data-editable="true">Value</th>
                    </tr>
```
3) Suppose the column value is very big, on edit , the pop over is very small
4) This makes very difficult to edit

[jsfiddle]:http://jsfiddle.net/wmp074eb/

Screenshot of the edit column,
![image](https://user-images.githubusercontent.com/11829880/54583562-929f9000-4a3a-11e9-8f47-4802f1e41eff.png)

**Comment by Falseee** [comment]
Quote from the [bootstrap-table documentation](https://bootstrap-table.com/docs/extensions/editable/#editable-1):
```
Configuration of x-editable. Full list of options: http://vitalets.github.io/x-editable/docs.html#editable.
[...]
All options can be defined via data-editable-* HTML attributes. Table wide options are used for every column but can be overridden:
```
On the [x-ediable documentation](http://vitalets.github.io/x-editable/docs.html#editable) you can find the option `type` so i guess you have to add `data-editable-type="textarea"`

**Comment by zaidmir5** [comment]
When i write a long attribute in edit box, left column value comes down
It should remain static .

**Comment by wenzhixin** [comment]
Close this issue if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
