### ISSUE TITLE
insert new row --> value of input field set back to default

### ISSUE THREAD

**Issue by basementmedia2** [wenzhixin/bootstrap-table#4221]
When inserting a new row, contents of the input fields contained in the existing rows get lost (set to default value)

When i change the value of the input field from 'daniel' to 'michael' for example and then press the ADD button, a new row is inserted, but 'michael' switches back to 'daniel'.

Here's a jsfiddle
https://jsfiddle.net/a0sydwnp/

**Comment by Falseee** [comment]
I guess this behavior is correct, if you add a new Row the table will be rerendered with the internal saved data.   
If want that your data persist, then you can use the [updatebyuniqueid](https://bootstrap-table.com/docs/api/methods/#updatebyuniqueid) or the [updaterow](https://bootstrap-table.com/docs/api/methods/#updaterow) function to update the data after changed the value of the input.
The maybe easier way is to use the [editable](https://bootstrap-table.com/docs/extensions/editable/) extension.

**Comment by wenzhixin** [comment]
Yes, you need to update the row, example: https://examples.bootstrap-table.com/index.html#issues/987.html.
ref #987
