### ISSUE TITLE
totalNumber of rows always 0 after inserting new row

### ISSUE THREAD

**Issue by basementmedia2** [wenzhixin/bootstrap-table#4227]
I want a new row to be inserted at the end of the table.
So my plan was to get the total number of rows and then insert the new row at index = totalNumRows+1.

But i always get total number of rows = 0...

Here's a jsfiddle
https://jsfiddle.net/7v13agyc/

**Comment by wenzhixin** [comment]
It seems that your fiddle cannot show the problem.

**Comment by basementmedia2** [comment]
Hi,

shouldn't the event  

```
$("#test_table").on('post-body.bs.table', function () {
  console.log($("#test_table").bootstrapTable('getOptions').totalRows);
})
```

which is in the fiddle log the number of total rows in the console?

**Comment by Falseee** [comment]
I agree that `.bootstrapTable('getOptions').totalRows` should return the count of all row (same count as shown in pagination).
As workaround you can use `$("#test_table").bootstrapTable('getData').length`.
Example for the workaroung: https://jsfiddle.net/btLoaj1p/

**Comment by wenzhixin** [comment]
Merged in the develop branch.
