### ISSUE TITLE
get rows index/data from a certain or showed page

### ISSUE THREAD

**Issue by omatic-hacker** [wenzhixin/bootstrap-table#423]
Hello

Is there any method or maybe someone has an idea how to get rows index and data from certain page. For example, I have 254 rows, pagination is 50 rows per page. So how can i get only those 4 left rows, i mean their  indexes and data , so i can update them, for example with updateRow, etc.

Thanks.

**Comment by wenzhixin** [comment]
You can try 'getData' method.

**Comment by omatic-hacker** [comment]
getData returned me all rows in table, am i right? but i need data/indexes only from page that showed to user right now.

Now my code is:
```javascript

var PAGE_SIZE = 10;
var PAGE_NUMBER = 1;

// some code...

var Ipv4List = iptable.bootstrapTable('getData');
var Ipv4ListPage = [];
var toPageElement = PAGE_NUMBER * PAGE_SIZE;
var fromPageElement = toPageElement - PAGE_SIZE;
for (var i = fromPageElement; i < toPageElement; i++) {
     Ipv4ListPage.push(Ipv4List[i]);
}

// do something with elements on page --> Ipv4ListPage 
```

But on last page there is only 4 elements, so rest elements on array are undefined, etc ... don't know if it's clear way ;)

**Comment by dabros** [comment]
'kinda' related: #535 

Whatever fix for finding page of given row might apply indirectly to solving this

Though, this problem is simpler in that all you need to know is current pagination param (number of page, records per page) and you can just slice the data array

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/693
