### ISSUE TITLE
Cleaning up Github issues

### ISSUE THREAD

**Issue by Falseee** [wenzhixin/bootstrap-table#4234]
As you maybe noticed I worked through some issues and saw that a lot of issues are old and without any reaction for the last months/years.

As example the user @nicholasrpb has two issues open from 2016 (3 years ago):
- #2786
- #2663

Also the User was not active since 3 Years, so in my opinion the repository should automaticly close issues after x days without reactions.
Excluded are Issues with bug reports, feature request (e.g. issues with feature label), the exact list would have to be considered.

The problem that I see is that i could answer to many issues but:
  - the user would not see it because there are inactive on github
  - the errors are already fixed in newer versions
  - the features are already implemented

Do you agree with that or do you have a better solution for this ?
@wenzhixin @djhvscf

**Comment by pchaganti** [comment]
If an issue is open more than 6 months without reactions, it might be better to close it. Thanks for cleaning up the old issues.

**Comment by djhvscf** [comment]
Hi, actually we have been closing bugs after 7 days of 'no response'.. but what we need to do is review the old ones again because some of them are still bugs on our plugin.. the way you propose is good to me

**Comment by Falseee** [comment]
For some issues i should ask the user for more informations.. but e.g. the examle user above was 3 years not active.. so i would got no response..

How should we/i handle that ?

**Comment by djhvscf** [comment]
My proposal:

If user is inactive and the issue is not confirmed -> Close it

If user is inactive and the issue is confirmed -> prioritize the bug

If user is active and the issue is not confirmed -> ask for more information and wait for 7 days

If user is active and the issue is confirmed -> prioritize the bug

**Comment by Falseee** [comment]
Sounds good, when do we say that a user is inactive ?

**Comment by djhvscf** [comment]
Good question.. I would say 2 months

**Comment by Falseee** [comment]
2 months are fine, if @wenzhixin dont have a objection the issue can be closed.
