### ISSUE TITLE
Give all cells in column an ID?

### ISSUE THREAD

**Issue by Bosskee** [wenzhixin/bootstrap-table#4237]
This amazing library has blessed my projects, but I'm wondering if there's any way to give all CELLS in a COLUMN an ID? Would looks something like this in my mind: https://i.gyazo.com/3d28a59e0dccdefa01ff43beab923b6a.png

The unique-id function does not work like this if I have understood it correctly. My goal here is to make every cell of this column clickable(only the cells!).

**Comment by wenzhixin** [comment]
I think [`onClickCell`](https://bootstrap-table.com/docs/api/events/#onclickcell) event can solve the problem.

**Comment by Bosskee** [comment]
> I think [`onClickCell`](https://bootstrap-table.com/docs/api/events/#onclickcell) event can solve the problem.

Thank you! That event is what I was looking for 👍
