### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by wenzhixin** [wenzhixin/bootstrap-table#4239]
What I want to do in the future or have already completed.

- [x] Rebuild all source code to ES6.
   - [x] Extensions
     - [x] accent-neutralise
     - [x] addrbar
     - [x] auto-refresh
     - [x] cookie
     - [x] copy-rows
     - [x] defer-url
     - [x] editable
     - [x] export
     - [x] filter-control
     - [x] fixed-columns
     - [x] ~~group-by~~
     - [x] group-by-v2
     - [x] i18n-enhance
     - [x] key-events
     - [x] mobile
     - [x] ~~multi-column-toggle~~
     - [x] ~~multiple-search~~
     - [x] ~~multiple-selection-row~~
     - [x] multiple-sort
     - [x] natural-sorting
     - [x] page-jump-to
     - [x] pipeline
     - [x] print
     - [x] reorder-columns
     - [x] reorder-rows
     - [x] resizable
     - [x] ~~select2-filter~~
     - [x] sticky-header
     - [x] toolbar
     - [x] ~~tree-column~~
     - [x] treegrid
   - [x] Locales
   - [x] bootstrap-table.js
- [x] Rebuild the website, deploy to GitHub Pages and add Algolia search support. (100%)
- [x] [Add some of the most widely used CSS frameworks](https://github.com/wenzhixin/bootstrap-table/tree/develop/src/themes). (100%)
- [x] Check all [table options](https://github.com/wenzhixin/bootstrap-table/blob/develop/site/docs/api/table-options.md) are working and add [examples](https://github.com/wenzhixin/bootstrap-table-examples/tree/develop/options). (100%)
- [x] Check all [column options](https://github.com/wenzhixin/bootstrap-table/blob/develop/site/docs/api/column-options.md) are working and add [examples](https://github.com/wenzhixin/bootstrap-table-examples/tree/develop/column-options). (100%)
- [x] Check all methods are working and add examples. (100%)
- [x] Check all locales https://github.com/wenzhixin/bootstrap-table/commit/13624d984b410ea4436bfb234ef3addb6fc9833b. (100%)
- [x] Check all events are working. (100%)
- [x] Check all extensions are working, remove extensions that don't need or don't work. (100%)
- [x] Review and clean up all PR.
- [x] #4234: Clean up most of the remaining issues.
- [x] Use the module to refactor the code to remove IIFE.
- [x] Use virtual scrolling to improve performance. Trying to have been basically implemented, for example, 20,000 data can work properly.
- [x] Support vue.js.
- [ ] Released version 1.15.0.

---
- [ ] Add examples for all Extensions (20%)
- [ ] Remove the dependency on jQuery.
   - [ ] Extensions
     - [ ] accent-neutralise
     - [ ] addrbar
     - [ ] auto-refresh
     - [ ] cookie
     - [ ] copy-rows
     - [ ] defer-url
     - [ ] editable
     - [ ] export
     - [ ] filter-control
     - [ ] fixed-columns
     - [x] ~~group-by~~
     - [ ] group-by-v2
     - [ ] i18n-enhance
     - [ ] key-events
     - [ ] mobile
     - [x] ~~multi-column-toggle~~
     - [x] ~~multiple-search~~
     - [x] ~~multiple-selection-row~~
     - [ ] multiple-sort
     - [x] natural-sorting
     - [ ] page-jump-to
     - [ ] pipeline
     - [ ] print
     - [ ] reorder-columns
     - [ ] reorder-rows
     - [ ] resizable
     - [x] ~~select2-filter~~
     - [ ] sticky-header
     - [ ] toolbar
     - [ ] ~~tree-column~~
     - [ ] treegrid
   - [ ] Locales
   - [ ] bootstrap-table.js
- [ ] Released version 2.0, now many people have reported that the bootstrap-table is often not searchable, so consider changing the name, such as `ui-table` or other better name.
- [ ] Consider whether to support react and angular, not very familiar.

**Comment by djhvscf** [comment]
What about to 'Support stackoverflow'?

**Comment by Falseee** [comment]
What do you mean with 'Support stackoverflow' ?

**Comment by djhvscf** [comment]
Also we should add unit test.. mochajs for example

**Comment by Falseee** [comment]
What is the new default Theme ? (Bootstrap needs jquery so it makes no sense to use it as default, maybe custom design ?)

**Comment by wenzhixin** [comment]
https://www.reddit.com/r/webdev/comments/aq3zu4/bootstrap_5_will_remove_jquery_as_a_dependency/
bootstrap has removed jQuery.

**Comment by Falseee** [comment]
Okay, so we wait until bootstrap 5 is released.

**Comment by djhvscf** [comment]
Review and clean up all PR. Done

**Comment by dimbslmh** [comment]
Perhaps separate the bootstrap 5 constants for the new version? (like the other css frameworks)

**Comment by Falseee** [comment]
> remove extensions that don't need or don't work
In my opinin the extension multipleSearch can be removed, beacuse its basicly just a [customSearch](https://bootstrap-table.com/docs/api/table-options/#customsearch) with splitted text.

**Comment by nam-co** [comment]
vue support please

**Comment by Falseee** [comment]
@nam-co Its already on the list.

**Comment by wenzhixin** [comment]
> In my opinion, the extension multipleSearch can be removed because it's basically just a `customSearch` with split text.

#4256

**Comment by wenzhixin** [comment]
ref #4256

**Comment by Falseee** [comment]
I just want to say thank you for the good work!
Almost 300 closed Issues in the last month (https://github.com/wenzhixin/bootstrap-table/pulse/monthly).
@wenzhixin @djhvscf

**Comment by djhvscf** [comment]
Thank you @Falseee @wenzhixin  awesome work

**Comment by djhvscf** [comment]
@wenzhixin @Falseee 

Going to remove Group-By extension

**Comment by djhvscf** [comment]
Considering remove reorder-rows extension since this has a jquery pugin dependency and it is not working after the search is executed

@wenzhixin @Falseee

**Comment by wenzhixin** [comment]
I think at the moment to delete jQuery dependencies still requires a lot of work, because like our extensions and themes are required jQuery.

**Comment by wenzhixin** [comment]
Working well vue.js + Materialize ^_^

![image](https://user-images.githubusercontent.com/2117018/55740911-aac56680-5a5e-11e9-9e2f-e539a7307dcf.png)

![image](https://user-images.githubusercontent.com/2117018/55740935-b3b63800-5a5e-11e9-8874-a4a222e868d6.png)

**Comment by Falseee** [comment]
I dont like the javascript frameworks stuff.. but for other ppl's its good..
Good work @wenzhixin

**Comment by djhvscf** [comment]
@wenzhixin excellent work!!

**Comment by djhvscf** [comment]
@wenzhixin @UtechtDustin Removing jquery

$.extend is removed
 https://github.com/wenzhixin/bootstrap-table/tree/feature/remove_jquery

**Comment by wenzhixin** [comment]
Consider to remove the `tree-column` extension and improve `treegrid` instead.

**Comment by djhvscf** [comment]
> Consider to remove the `tree-column` extension and improve `treegrid` instead.

Agree

**Comment by luylucas10** [comment]
how can I use with vue.js? which branch?

**Comment by UtechtDustin** [comment]
@luylucas10 https://github.com/wenzhixin/bootstrap-table/pull/4299#issuecomment-486630314

**Comment by luylucas10** [comment]
@UtechtDustin Thanks! 
I'll try to use. I want to replace jquery code to vue, and I use this plugin a lot of parts of my app.
I'll understand if it is not complete.

**Comment by UtechtDustin** [comment]
`Check all column options are working and add examples.`
Updated from 20% to 95%.
https://github.com/wenzhixin/bootstrap-table-examples/pull/365
#4374

**Comment by wenzhixin** [comment]
> Check all column options are working and add examples.
> Updated from 20% to 95%.

I am woking on this.

**Comment by UtechtDustin** [comment]
> Check all events are working.
I will start with that later !

**Comment by UtechtDustin** [comment]
> Check all events are working.

Done

**Comment by wenzhixin** [comment]
> Check all methods are working and add examples.

Done

**Comment by UtechtDustin** [comment]
>Check all extensions are working and add examples, remove extensions that don't need or don't work

The last one will be the hardest/annoying one.

**Comment by wenzhixin** [comment]
TODO: `showSearchButton` and `showSearchClearButton` need to add other CSS frameworks support.

**Comment by wenzhixin** [comment]
> Check all extensions are working and add examples, remove extensions that don't need or don't work

Working on this.

**Comment by UtechtDustin** [comment]
> TODO: showSearchButton and showSearchClearButton need to add other CSS frameworks support.     

I can do it, but i need some time i guess because i never used that frameworks.

**Comment by UtechtDustin** [comment]
Can be closed 1.15.0 is release, if we continue to remove jquery we can open a new "plan issue".
