### ISSUE TITLE
How to handle errors when using data-url?

### ISSUE THREAD

**Issue by cocowalla** [wenzhixin/bootstrap-table#4243]
I'm using `data-url` to load data into a table from a remote endpoint, which works great.

My question is how to handle errors in the response - for example, when the server returns error 500. At present, the table simply remains empty if that happens.

I've had a look at the [docs](https://bootstrap-table.com/docs/api/table-options/), but I don't see any way to add an error handler?

**Comment by Falseee** [comment]
Use the [onLoadError](https://bootstrap-table.com/docs/api/events/#onloaderror) Event.

**Comment by cocowalla** [comment]
Perfect, thank you!
