### ISSUE TITLE
Editing textarea after ReOrder (Extension)

### ISSUE THREAD

**Issue by basementmedia2** [wenzhixin/bootstrap-table#4246]
I have a custom function, which adds a new table row.
Each new row contains a textarea and an input field.
The rows can be reordered using the reorder extension.

The strange behaviour: 
1. I add two rows, input some content and reorder them (drag row 2 to position 1).
2. I change the content of row 1's  textarea and click into row 2's textarea (which triggers the updateRow event)
3. The row 2's textarea gets the same content as the row 1's textarea...??

Here's a jsfiddle:

https://jsfiddle.net/29dt0jn4/14/

Please help ;-( What's the fault.

And another question: In the actual code, the updateRow event is only triggered, when clicking somewhere outside the last changed input field/textarea. But i want the updateRow is also triggered when the textarea of a row is edited and the row is reordered directly.
Means: When reordering the table, the last edited row should be updated.

**Comment by Falseee** [comment]
Its not a bug, if you pass an object through a function its call by reference.
Example: https://jsfiddle.net/rk5dt1as/
The problem is that you directly change the row AND use the updateRow function.
To fix ist, create a new variable with the old data of the row, then overwrite the cols in the new variable and update with that.
***
Das ist kein Bug, wenn ein Object in Javascript als parameter durchgereicht wird dann it es call by reference, sprich wenn du in der Funktion die variable änderst wird diese auch "außerhalb" geändert.
Beispiel: https://jsfiddle.net/rk5dt1as/
Das Problem ist das du im change Event direkt auf die row zugreifst/sie überschreibst.
Um das zu behben leg dir einfach eine neue Variable an mit den werden aus der row und überschreib dann das neue Object und nutz dieses auch um die Row zu updaten.

**Comment by basementmedia2** [comment]
Hi,

but also in your fiddle there's one problem left: Only one of the two fields is saved correctly when reOrdering/updating.

Example:
If I insert two rows, fill out textarea and input field of both rows, drag row 2 upwards, then edit textarea of row 1 (formerly row 2) and click somewhere outside (so that updateRow-operation is performed) only the data of the textarea keeps the change value. The data of the other field overtakes the value of the reference ;-(

Do you have further tips?
And what if i have not only two rows but 10 or more?
And the strange thing is:
The problem exists only if I reorder the lines.
If I only add new lines, everything runs correctly.

**Comment by dimbslmh** [comment]
this works: https://jsfiddle.net/dimbslmh/qgdw7832/1/

**Comment by UtechtDustin** [comment]
@basementmedia2 do you tried the example from @dimbslmh ?

**Comment by basementmedia2** [comment]
Yes it worked for meVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Dustin Utecht <notifications@github.com> Datum: 07.06.19  23:40  (GMT+01:00) An: wenzhixin/bootstrap-table <bootstrap-table@noreply.github.com> Cc: basementmedia2 <mail@basement-media.de>, Mention <mention@noreply.github.com> Betreff: Re: [wenzhixin/bootstrap-table] Editing textarea after ReOrder
  (Extension) (#4246) @basementmedia2 do you tried the example from @dimbslmh ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wenzhixin/bootstrap-table/issues/4246?email_source=notifications\u0026email_token=AFTEKANAJMFLLPN7T6SHKADPZLIURA5CNFSM4HAZNIWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXHCAJQ#issuecomment-500047910",
"url": "https://github.com/wenzhixin/bootstrap-table/issues/4246?email_source=notifications\u0026email_token=AFTEKANAJMFLLPN7T6SHKADPZLIURA5CNFSM4HAZNIWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXHCAJQ#issuecomment-500047910",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
