### ISSUE TITLE
After Undeploying or delete say at 4th page it should remian on the same page but it comes back to first page

### ISSUE THREAD

**Issue by zaidmir5** [wenzhixin/bootstrap-table#4247]
Bootstrap table pagination,delete any list say for eg; at 4th page it should remain at 4th page 
but it comes to 1 page.
1. Create a bootstrap table.
2. Make 3,4 pages. 
3.select any list from any page and delete it , after delete it should remain on the same page after refresh the current page.
![image](https://user-images.githubusercontent.com/48056293/54917825-ace9da00-4f22-11e9-81ba-ef2100709a19.png)

**Comment by zaidmir5** [comment]
![image](https://user-images.githubusercontent.com/48056293/54915667-b290f100-4f1d-11e9-9b43-463c7889ec33.png)

**Comment by wenzhixin** [comment]
Same feature as #2188?

**Comment by zaidmir5** [comment]
No it's not the same feature.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by zaidmir5** [comment]
i will not be able to provide the fiddle as i am working on a live project. The problem i am facing is that i am not retain the same page while deleting an entry from the table.

**Comment by Falseee** [comment]
You dont have to use your real data, just use some placeholder/fake/test data.

**Comment by wenzhixin** [comment]
Save `nextpage` in `responseHandler` first, then send it in `queryParams`. Can this solve the problem?

**Comment by zaidmir5** [comment]
var pageNumber = $('#tableWfd').bootstrapTable('getOptions').currentPageNumber
									alert(currentPageNumber)
 $('#tableWfd').bootstrapTable('selectPage', currentPageNumber);

**Comment by zaidmir5** [comment]
var pageNumber = $('#table').bootstrapTable('getOptions').pageNumber
alert(pageNumber)
  $('#table').bootstrapTable('selectPage', pageNumber);

Still shows the same problem

**Comment by wenzhixin** [comment]
Without an example, we don't know what problem do you have. 
You can use http://myjson.com/ to set your fake/test data.

**Comment by Falseee** [comment]
I close this issue because we got no response/example within 7 days.
