### ISSUE TITLE
Update github labels.

### ISSUE THREAD

**Issue by Falseee** [wenzhixin/bootstrap-table#4248]
Are the [descriptions of the labels](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md) up to date ?

Maybe it makes also sense to set the description of the label on Github itself.

**Comment by djhvscf** [comment]
No, i think they are not up to date.

What do you mean by set the description of the label on GitHub itself?

**Comment by Falseee** [comment]
https://github.com/wenzhixin/bootstrap-table/labels => Edit Label => Description.

**Comment by wenzhixin** [comment]
Updated: https://github.com/wenzhixin/bootstrap-table/labels
