### ISSUE TITLE
Is bootstrap-table incompatible with ThinkPHP3.2

### ISSUE THREAD

**Issue by Jairs** [wenzhixin/bootstrap-table#4249]
Is bootstrap-table incompatible with ThinkPHP3.2?
I cannot show data.
![image](https://user-images.githubusercontent.com/30263041/54971175-36031e80-4fc0-11e9-9f3a-ddeb8c4d7f58.png)
![image](https://user-images.githubusercontent.com/30263041/54971178-3996a580-4fc0-11e9-9f1d-052511232dbd.png)

**Comment by wenzhixin** [comment]
You can use `responseHandler` to solve your problem:
https://examples.bootstrap-table.com/index.html#options/response-handler.html

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by dimbslmh** [comment]
@Jairs Add the responseHandler like @wenzhixin said and it should work:
http://jsfiddle.net/dimbslmh/y83xwkj7/14/

**Comment by Jairs** [comment]
Thanks,I solved the problem
