### ISSUE TITLE
Custom row content

### ISSUE THREAD

**Issue by Abdel-Aziem** [wenzhixin/bootstrap-table#425]
I need to custom row cell content, for example: I want to make last column as a container for some buttons like:

id                         name                      description                    --
1                          John                        any desc...                  (Message Icon) (Edit Icon) (Delete Icon)

Thank you.

**Comment by DominikAngerer** [comment]
Use something like this in your table header:
```html
<th data-field="import" data-formatter="rowImportFormatter" data-events="rowImportEvents" >Import</th>
```
And some own formatter ore something:
```javascript
function rowImportFormatter(value, row, index) {
    return [
        '<a class="import" style="font-size:25px;" href="javascript:void(0)" title="Import">',
            '<i class="glyphicon glyphicon-import"></i>',
        '</a>'
    ].join('');
}
```
Also register an on click event on this th.
```javascript
window.rowImportEvents = {
    'click .import': function (e, value, row, index) {
        alert(row);
    }
};
```

There is an example for this on the old documentation: http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#column-events-table :)

**Comment by Abdel-Aziem** [comment]
Thanks Dominik :+1:

**Comment by SivalingaamorthySage** [comment]
I tried to delete the row, but the row is not getting removed, can someone help me.

   var $table = $('#MachineryListTable').bootstrapTable();

                $table.bootstrapTable('remove', {
                    field: 'id',
                    values: 8
                });

**Comment by wenzhixin** [comment]
values: [8]

**Comment by DominikAngerer** [comment]
@SivalingaamorthySage This would be a question and has nothing to do with Custom Row content. Next time you should open a new issue so it gets tracked + indexed the right way from google & other user also find the answer provided by @wenzhixin
