### ISSUE TITLE
Table Treegrid example not loading

### ISSUE THREAD

**Issue by pchaganti** [wenzhixin/bootstrap-table#4254]
Trying to load https://examples.bootstrap-table.com/#extensions/treegrid.html results in an error in the Chrome console : Uncaught TypeError: Converting circular structure to JSON

Scre
![Screen Shot 2019-03-26 at 7 24 13 PM](https://user-images.githubusercontent.com/6500/55040050-31a92680-4ffd-11e9-8152-991b21231690.png)
enshot attached

**Comment by wenzhixin** [comment]
Fixed: https://github.com/wenzhixin/bootstrap-table/commit/4ae907f73b29c4fcd14fc64f8fc6b6c3a5ff78ef
