### ISSUE TITLE
bootstrap-table-treegrid

### ISSUE THREAD

**Issue by wangjiawei9816** [wenzhixin/bootstrap-table#4255]
bootstrap-table-treegrid这个插件数据量达到300的时候就会卡了，非常严重了 可以说是

**Comment by Falseee** [comment]
Pls provide us an example.

**Comment by wangjiawei9816** [comment]
the problem is used jquery.treegrid.min.js.it use too much time

**Comment by wangjiawei9816** [comment]
> Pls provide us an example.

the problem is used jquery.treegrid.min.js.it use too much time

**Comment by Falseee** [comment]
I understand your issue (with google translator), but also for that you could provide us an example.
Its not an issue of the bootstrap-table, its a issue from the jquery.treegrid.
The [example](http://maxazan.github.io/jquery-treegrid/examples/example-huge.html) from the plugin also loads 44 seconds for me, so pls report this issue on their [repository](https://github.com/maxazan/jquery-treegrid).

**Comment by henu5972** [comment]
是我太笨了吗？运行了一下午，示例运行不起来
