### ISSUE TITLE
Bootstrap 4 Multi Sort Support

### ISSUE THREAD

**Issue by ryankane** [wenzhixin/bootstrap-table#4258]
The ["Multiple Sort"](https://examples.bootstrap-table.com/index.html#extensions/multiple-sort.html) plugin (`showMultiSort`) for Bootstrap Tables is broken for Boostrap 4. The demo on the linked page is visibly broken. The button is visible in the DOM, but it appears "hidden" to the user.

## Workaround

I posted a self-answered question on Stackoverflow that provides a possible workaround.

>https://stackoverflow.com/questions/55401039/bootstrap-tables-multiple-sort-broken-for-bootstrap-4

```js
(function($) {
  $.fixBootstrapMultisort = function() {
    let $button = $('.multi-sort'),
      $modal = $('div[id^="sortModal_"].modal'),
      $toolbar = $modal.find('.modal-dialog #toolbar');
    // Wrap the button in a button group element.
    $button.addClass('btn-secondary').wrap($('<div>').addClass('btn-group'));
    // Fix modal title alignment.
    $modal.find('.modal-dialog .modal-content .modal-header .modal-title').css({ position: 'absolute', lineHeight: 1 });
    // Fix the icons.
    $button.find('.fa.glyphicon-sort').removeClass('glyphicon-sort').addClass('fa-sort').css('width', '1em');
    $toolbar.find('i.glyphicon-plus').removeClass('glyphicon-plus').addClass('fa-plus');
    $toolbar.find('i.glyphicon-minus').removeClass('glyphicon-minus').addClass('fa-minus');
  };
})(jQuery);
```

There were a few things I had to fix.

- The `.multi-sort` button was not wrapped in a `div.btn-group` element.
- The icon was a `.glyphicon-sort` rather than `.fa-sort`.
- I set the width of the button to `1em`, because it was defaulting to the width of the icon.
- The modal window title was not on the left.

Call it after your table creation.

```js
$('#table').bootstrapTable({
  showMultiSort: true
});
$.fixBootstrapMultisort();
```

**Comment by ryankane** [comment]
When I get a chance, I will attempt to create a pull request to fix the issue in:

> https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/multiple-sort/bootstrap-table-multiple-sort.js

**Comment by wenzhixin** [comment]
Thank you for your feedback, now the extension author is rewriting a new version to support all CSS frameworks. @dimbslmh

**Comment by UtechtDustin** [comment]
Any news here @dimbslmh ?
