### ISSUE TITLE
onClickCell: Get value of another cell in same row?

### ISSUE THREAD

**Issue by Bosskee** [wenzhixin/bootstrap-table#4266]
I'm using the onClickCell event and it works wonderfully. I have a question though: Is it possible to get the value of another cell that's in the same row when a certain cell is clicked?

Like this:
[![Screenshot from Gyazo](https://gyazo.com/9d17dd86c633407ca1f4e3e14003a0cd/raw)](https://gyazo.com/9d17dd86c633407ca1f4e3e14003a0cd)

Is this possible through onClickCell or any other event? :)

**Comment by Falseee** [comment]
The third paramter of the event is the row (see the documentation [onClickCell](https://bootstrap-table.com/docs/api/events/#onclickcell))

**Comment by Bosskee** [comment]
> The third paramter of the event is the row (see the documentation [onClickCell](https://bootstrap-table.com/docs/api/events/#onclickcell))

Yes I see, but what is the row data? Array?

**Comment by Falseee** [comment]
Its an object, to get data of a other cell use `row.fieldName`.
To debug you can also use `console.log(row)`
