### ISSUE TITLE
After refreshing checkbox should get unchecked

### ISSUE THREAD

**Issue by zaidmir5** [wenzhixin/bootstrap-table#4269]
After refresh the table the checkbox should be unchecked.

![image](https://user-images.githubusercontent.com/48056293/55460487-bdc7d900-560f-11e9-8721-2339b9ea3c7b.png)

**Comment by wenzhixin** [comment]
In our example, we use `selections` to save the checkbox state: https://examples.bootstrap-table.com/index.html#welcome.html#view-source.
By default, after refreshing the table the checkbox should be unchecked.

**Comment by zaidmir5** [comment]
It remains same 
cam you tell me what i hsve to add it

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/z50x2d7t/1/

**Comment by zaidmir5** [comment]
<table id="tableWorkflow" data-toggle="table" data-toolbar="#toolbarTableWorkflow"
           data-maintain-selected="true" data-unique-id="id"
           data-url="wf/Admin/simplifiedProcesses/true"
           data-response-handler="responseHandlerWorkflow" data-cache="false"
            data-click-to-select="true" data-striped="true"
           data-pagination="true" data-search="true" data-sort-order="desc"
           data-sort-name="creationTime" data-show-columns="true"
           data-show-refresh="true" data-show-multi-sort="true"
           data-sort-priority='[{"sortName":"creationTime","sortOrder":"desc"},{"sortName":"wfdName","sortOrder":"desc"},{"sortName":"wfdVersion","sortOrder":"asc"}]'
           data-page-size="10" data-page-list='[10, 25, 50, 75, 100, 200, 300, 500]'>
        <thead>
        <tr>
            <th data-width="2%" data-field="state"  data-checkbox="true"></th>
            <th data-field="wfdName" data-sortable="true" data-width="20%">Workflow
                Name</th>
            <th data-field="wfdVersion" data-sortable="true"
                data-width="5%">Version</th>
            <th data-field="description" data-sortable="true"
                data-width="22%">Description</th>
            <th data-field="username" data-sortable="true"
                data-width="10%">Deployed By</th>
            <th data-field="creationTime" data-sortable="true"
                data-width="10%">Deployed On</th>
            <th data-field="id" data-sortable="false" data-click-to-select="false" data-formatter="tableWorkflowActionsFormatter"
                data-searchable="false" data-width="30%">Actions</th>
            <th data-field="smgr" data-visible="false">smgr</th>
        </tr>
        </thead>
    </table>

**Comment by zaidmir5** [comment]
You can see the above comment 
where i can make a change so that after refresh it become uncheck..

**Comment by Falseee** [comment]
Please provide us an jsfiddle with your "not working" code, instead of posting your code.

**Comment by zaidmir5** [comment]
I am working on the live project i share some line of code in the above comment

**Comment by Falseee** [comment]
Just provide us an jsfiddle with fake data or we cant help.

**Comment by zaidmir5** [comment]
![image](https://user-images.githubusercontent.com/48056293/55522000-ca484200-56a0-11e9-9998-2e215f261ddc.png)
I Hope you will get from this image.

**Comment by wenzhixin** [comment]
`maintainSelected` option:
https://bootstrap-table.com/docs/api/table-options/#maintainselected
https://examples.bootstrap-table.com/index.html#options/maintain-selected.html

**Comment by zaidmir5** [comment]
$('#tableWfd').bootstrapTable('onRefresh', {
		                                                $('#tableWfd').bootstrapTable('uncheckAll');
								});

i tried this one but nothing happens

**Comment by wenzhixin** [comment]
Set maintainSelected to false

**Comment by zaidmir5** [comment]
I already did that  data-maintain-selected="false",but it shows same after i refresh the table .
