### ISSUE TITLE
Column Width Not Working on BootstrapTable 3.3.7

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#4270]
Hi all,
There are too many columns in the data. Some of these are great, like the address. It is not possible to fit all the columns on the screen. I want to show it with the scroll bar. I entered a length value on some columns. But they are automatically changed. You can review the following JSFiddle example, and view the original screenshot. Thank you so much.

Example JSFiddle: https://jsfiddle.net/mehmetalidumlu/1wxop0hm/13/
ScreenShot From Live Project:
![image](https://user-images.githubusercontent.com/15678340/55475893-caebc480-561d-11e9-8cae-5e9d3e4cc374.png)

**Comment by Falseee** [comment]
https://bootstrap-table.com/docs/api/column-options/#width
Please read the Description, with a class and min-width it works finde.

Exmaple: https://jsfiddle.net/g1056ynr/2/
