### ISSUE TITLE
Table Export - TypeError: c.$el.tableExport is not a function

### ISSUE THREAD

**Issue by iamthestreets** [wenzhixin/bootstrap-table#428]
Hi I am receiving this error when I try to export any format:
`TypeError: c.$el.tableExport is not a function`

How can I fix this?

**Comment by wenzhixin** [comment]
Have you imported the dependent library: https://github.com/kayalshri/tableExport.jquery.plugin?

**Comment by iamthestreets** [comment]
No, but I have them now.

I'm not sure if these questions can be answered by you, but I do have some questions:
1. Why does csv not save as csv?
* I have to rename the file and add .csv
* same with txt, sql, and word

Also when choosing to export as PDF it looks like this:
![pdfgrid](https://cloud.githubusercontent.com/assets/8740821/5784270/ae742a14-9d98-11e4-92b7-ab74b6e20174.png)

**Comment by wenzhixin** [comment]
Hi @iamthestreets, your problem is decided by this plugin: [tableExport.jquery.plugin](https://github.com/kayalshri/tableExport.jquery.plugin), because this plugin is not my maintenance and development, I think there are problems of this plugin need to be more perfect, but I don't know the author if can help to improve. If you can help to improve, any pull requests are welcome!
Close this issue here.

**Comment by iamthestreets** [comment]
Thanks! I will submit an issue there.

**Comment by chebrami** [comment]
Hello, i have the same problem but i have import all js :+1: 

`<script type="text/javascript" src="@routes.Assets.at("javascripts/bootstrap-table.js")"></script>
	    <script type="text/javascript" src="@routes.Assets.at("javascripts/locales/bootstrap-table-fr-BE.js")"></script>
	    <script type="text/javascript" src="@routes.Assets.at("javascripts/bootstrap-table-export.js")"></script>
		<script type="text/javascript" src="@routes.Assets.at("javascripts/tableExport.js")"></script>
		<script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/jquery.base64.js")"></script>
		<script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/html2canvas.js")"></script>
		<script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/jspdf.js")"></script>
        <script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/jspdf.plugin.autotable.js")"></script>
        <script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/jspdf.plugin.addhtml.js")"></script>
		<script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/jspdf.plugin.addimage.js")"></script>
		<script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/FileSaver.min.js")"></script>
        <script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/split_text_to_size.js")"></script>
		<script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/jspdf.plugin.from_html.js")"></script>
		<script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/base64.js")"></script>
		<script type="text/javascript" src="@routes.Assets.at("javascripts/jspdf/sprintf.js")"></script>`

**Comment by GustavoCarvalho** [comment]
How to fix: _elm.tableExport is not a function_
