### ISSUE TITLE
TypeError: Cannot read property 'append' of undefined

### ISSUE THREAD

**Issue by pchaganti** [wenzhixin/bootstrap-table#4282]
Using the develop branch, as we need the virtual scroll enhancements. The tree grid plugin is not working with latest changes. Getting "TypeError: Cannot read property 'append' of undefined" when trying to append data to the table which is using treegrid.

The code works just fine with (1.14.2) version. Not sure where to even debug this. Anyone have any thoughts? Found this one issue back from October - https://github.com/wenzhixin/bootstrap-table/issues/4004

It says this issue was fixed, but looks like it is back with the latest changes in the develop branch.

Here are the source files I am using:

> <script src="https://rawgit.com/wenzhixin/bootstrap-table/develop/src/bootstrap-table.js" type="module"></script>

> <script src="https://rawgit.com/wenzhixin/bootstrap-table/develop/src/extensions/cookie/bootstrap-table-cookie.js" type="module"></script>

> <script src="https://rawgit.com/wenzhixin/bootstrap-table/develop/src/extensions/addrbar/bootstrap-table-addrbar.js" type="module"></script>

> <script src="https://rawgit.com/wenzhixin/bootstrap-table/develop/src/extensions/treegrid/bootstrap-table-treegrid.js" type="module"></script>

thanks for any info!

**Comment by Falseee** [comment]
The current develop Branch has a lot of changes, is currently not stable see #4268.
So maybe the bug is because of the instable state of the branch, but to be sure please provide us an [jsfiddle](https://jsfiddle.net/).

**Comment by pchaganti** [comment]
Ok. Thanks!

**Comment by wenzhixin** [comment]
I am working on #4278

**Comment by pchaganti** [comment]
Confirming that I am not getting this error with this latest version.

thanks!
