### ISSUE TITLE
Set Row Color depending of an attribute value,  inside cell

### ISSUE THREAD

**Issue by alexisfch** [wenzhixin/bootstrap-table#4284]
How can I set row color, depending of an attribute value, inside cell , my attribute is "data-id" and for example if that value is equal to $lastid value, set the entire row, with red color

Regards

**Comment by wenzhixin** [comment]
I think `rowStyle` can solve the problem:
```
function rowStyle(row) {
  if (row.id === lastid) {
    return {
      css: {
        color: 'red'
      }
    }
  }
}
```

https://examples.bootstrap-table.com/index.html#options/row-style.html

**Comment by alexisfch** [comment]
yes, but I have different attributes inside my variable,  isn't a clear value
`$lastid = $rowList['id'];`

`$name['coment'] = '<a class="btn btn-small btn-primary" data-toggle="modal" data-target="#coment" data-id="'.$rowList['id'].'"><i class="far fa-edit"></i></a>'`

then i need to change the color, when this attribute "data-id" (inside of a cell, with other attributes) it's equal to $lastid

**Comment by alexisfch** [comment]
for example I have a td like this:
`<td style="text-align: center; "><a class="btn btn-small btn-success" href="http://www.google.com" target="_blank" data-whatever="wsp" data-tipo="auto" data-id="2136"><i class="fab fa-whatsapp"></i></a></td>`

And usig RowStyle, i need to change the row color, when data-id=`$lastid`

**Comment by wenzhixin** [comment]
Use `$(row.coment).data('id')` to get the `id` value.

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by wenzhixin** [comment]
Hi! There is not any reply, in that case, we are going to close this PR. Remember to add an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!
