### ISSUE TITLE
Search in Nested Table

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#4287]
Hi all,
I create a new nested table. But search isn't working for nested rows. Filter control does not loading. How can i search text in nested table? Ineed to search by "ÖLÇÜM NO"

There is JSFiddle: http://jsfiddle.net/mehmetalidumlu/fgr92faf/5/

Thanks.

**Comment by djhvscf** [comment]
This is not supported in latest version v1.14.2

**Comment by UtechtDustin** [comment]
Im not sure if this should be a part of the core code.
It can be easily done with the [onSearch](https://bootstrap-table.com/docs/api/events/#onsearch) event and the [resetSearch](https://bootstrap-table.com/docs/api/methods/#resetsearch) method.

What do you think @wenzhixin @djhvscf ?

**Comment by djhvscf** [comment]
I think at least the "nomal" search should lookup into the nested tables which are opened.

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf 
But nested tables are not even a main feature of the bootstrap table.
Also while searching the table will be recreated, which means the detail view will be closed.

Its quiet simple to create that : https://live.bootstrap-table.com/code/UtechtDustin/1707

**Comment by wenzhixin** [comment]
Agree with @UtechtDustin
