### ISSUE TITLE
toolbar button title error 

### ISSUE THREAD

**Issue by skillnull** [wenzhixin/bootstrap-table#4289]
不是Fullscreen的按钮的title显示的也是Fullscreen。
![image](https://user-images.githubusercontent.com/19986684/56011839-2b64bb00-5d1c-11e9-8110-9d6c58e8cd31.png)

**Comment by wenzhixin** [comment]
谢谢反馈，已在 develop 中修复。

**Comment by skillnull** [comment]
谢谢

**Comment by skillnull** [comment]
请问能不能开一个能自定义title的功能方法，因为遇到一个需求是悬浮提示，让用户知道这个按钮的功能，一直没有找到好的方法去改变悬浮提示

**Comment by wenzhixin** [comment]
你可以自定义的，如：
```
$table.bootstrapTable({
  formatSearch: function () {
    return '自定义搜索'
  }
})
```
https://bootstrap-table.com/docs/api/localizations/
全局的话可以修改 i18n 的配置。
