### ISSUE TITLE
只有一个showColumns=true参数的时候，html的title属性却是fullscreen

### ISSUE THREAD

**Issue by songyuantai** [wenzhixin/bootstrap-table#4291]
如图，一来显示出错了，二来没有随语言包变成汉语
`$('#DataTable').bootstrapTable({
                    showColumns: true,
                    buttonsClass:'light'
                })`
![QQ截图20190412142246](https://user-images.githubusercontent.com/12009645/56016593-59072f80-5d2f-11e9-91c0-35877a0f8e94.png)

**Comment by wenzhixin** [comment]
Duplicate of #4289

已在 #4289 中修复。
