### ISSUE TITLE
When add a new variable in very long list, added variable should get auto focused.

### ISSUE THREAD

**Issue by zaidmir5** [wenzhixin/bootstrap-table#4292]
![image](https://user-images.githubusercontent.com/48056293/56056062-c7241480-5d78-11e9-93e3-cfef1850fd36.png)

Actual Result - After some time, new variable added is not getting autofocussed(scrollbar is not dynamically working here).
Expected Result - New variable should get autofocussed.

**Comment by wenzhixin** [comment]
Are you using bootstrap-table?

**Comment by zaidmir5** [comment]
JSON Editor

**Comment by wenzhixin** [comment]
Sorry, please create an issue to JSON Editor repo, thanks.
