### ISSUE TITLE
Server-Side Search still shows previous records when resulted json has no rows

### ISSUE THREAD

**Issue by nasserfuzion** [wenzhixin/bootstrap-table#4293]
Hello all,

when i set pagination to server, even if i input some bogus string in the search box, it stills shows the last record.

I tested the json and it resulting like this, {"offset":0,"limit":10,"total":0,"rows":0} but the last row still apears, like its not refreshing properly.

I noticed that it also happens when i delete all records, it still displays the records though the json returns {"offset":0,"limit":10,"total":0,"rows":0}.

**Comment by UtechtDustin** [comment]
Could you provide us an Jsfiddle for that ?
I cant reproduce it on the examples: https://examples.bootstrap-table.com/

**Comment by nasserfuzion** [comment]
@UtechtDustin , 
thank you for the prompt reply,
I am not able to do the fiddle. below the codes,

**test.php**
css : bootstrap, bootsrap-table
js : jquery, bootstrap,boostrap-table

<table 
`	id="test" 
	data-search="true"
    data-pagination="true"
    data-side-pagination="server"
    data-show-columns="true" 
    data-select-item-name="id" 
    data-id-field="id"
>
	<thead>
		<th 
			data-field="name" 
			data-visible="true" 
			data-sortable ="true" 
		>Name</th>
		<th 
			data-field="alias" 
			data-visible="true" 
			data-sortable ="true" 
		>Alias</th>
		</tr>
		</thead>
</table>

<script>
$( document ).ready(function() 
{
	$('#test').bootstrapTable(
	{
		url: 'test_response.php',
	});
});
</script>

**test_response.php**
{"offset":0,"limit":10,"total":2,"rows":[{"id":"9","name":"test","alias":"test","status":"1","mystatus":"ion-checkmark-circled text-success","idn":1}]}

if i remove the server die, client side search works fine, it displays the "no matching records found"

**Comment by wenzhixin** [comment]
http://www.nasserfuzion.com/test_response.php?search=123&order=asc&offset=0&limit=10

When I search `123`, it returns one row.

**Comment by nasserfuzion** [comment]
@wenzhixin 
Thank you for the reply.

it will indeed return 1 row because test_response.php has the json result instead of the mysql result.
I did it quickly just to provide an example.

I have modified the script to pull from the sql db and now if you go to the url 
http://www.nasserfuzion.com/test_response.php?search=123&order=asc&offset=0&limit=10
the mysql response will behave normally because 123 doesn't exist.

**Comment by wenzhixin** [comment]
You need to set `rows: []` because it's an array.

**Comment by nasserfuzion** [comment]
@wenzhixin , Thank you very much. 

replaced my response.class.php to result like below if no records found.
{"offset":0,"limit":10,"total":0,"rows":[]}

Its working fine now.

**Comment by wenzhixin** [comment]
You're welcome, if you like Bootstrap Table, give us a star! ⭐️⭐️⭐️ Thanks!
