### ISSUE TITLE
Hide Column On Initialization

### ISSUE THREAD

**Issue by danielnjoo** [wenzhixin/bootstrap-table#4298]
Hide Column On Initialization

Sorry, quite a basic question but have been looking through the docs for nearly an hour and can't find a solution. 

Using `data-show-columns=true` for the column checkboxes, but would like to hide one on initialization (but not permanently).

I've tried selecting the checkbox and removing the attribute / setting the 'checked' prop to false, but neither work, e.g.

```
$(":checkbox").filter(function(){
          return this.value == "3";
}).prop("checked", false)
```

This does uncheck the box but it does not hide the column, thanks!

I'm new to JQuery which doesn't help. Also as I noted in the [examples list](https://github.com/wenzhixin/bootstrap-table/issues/1765), the examples page [here](https://bootstrap-table.com/examples/) is no longer accessible which made finding the examples really difficult!

**Comment by djhvscf** [comment]
You can use column.visible=false

**Comment by danielnjoo** [comment]
Not sure exactly how I'd do that, here's a [fiddle](http://jsfiddle.net/danielnjoo/zxk1t6uy/)

**Comment by danielnjoo** [comment]
Oh OK got it, can set in any of the table headers: `<th data-visible="false">`
