### ISSUE TITLE
Pagination conflicting with Flat UI style

### ISSUE THREAD

**Issue by iamthestreets** [wenzhixin/bootstrap-table#430]
Hi,

I am using Flat UI and I am having some styling issues with the pagination - see screenshot below:
![pagination](https://cloud.githubusercontent.com/assets/8740821/5761184/b65eb010-9ca7-11e4-89c2-08540cc46aac.png)
How do I have the Flat UI styled used for the pagination?

**Comment by wenzhixin** [comment]
Look this example: http://issues.wenzhixin.net.cn/bootstrap-table/#383.html

**Comment by iamthestreets** [comment]
Thanks, that worked great!

**Comment by iamthestreets** [comment]
Hi, the suggested changes for this pagination stopped working. Can you please take a look and let me know how I can fix it? You can click the link above and you will see the issue.

**Comment by iamthestreets** [comment]
Thanks! Although this fixed the issue for me it no longer shows the checkboxes with the Flat UI.
