### ISSUE TITLE
Search in Custom AJAX

### ISSUE THREAD

**Issue by andrew1011111** [wenzhixin/bootstrap-table#4300]
Hi!

I am trying to use the search function in "Custom AJAX" and it does not work. For example, if you are looking for an item that does not exist, simply reload all the data, you can review the "Custom AJAX" example
This only happens with Ajax with paging on the server side.

PS: In advance, thanks.

**Comment by UtechtDustin** [comment]
I dont understand what do you mean, also i dont know which example do you mean.
Please provide us an example, i used this example http://jsfiddle.net/wenyi/z50x2d7t/1/.

I searched for "fasdgasdgsd" got no results and clicked on refresh, the Ajax call is correct and after the refresh also no rows are shown. Looks good!

**Comment by andrew1011111** [comment]
Hi, thanks for answering.

I refer to this example https://examples.bootstrap-table.com/#options/table-ajax.html, your data uploads from URL, I try to load them from AJAX but with the search function working.
If you look for anything with this example you will notice that it only reloads the data and does not look for the one specified in Input

**Comment by UtechtDustin** [comment]
If i saw it correct we currently dont add the the search parameters...
So i agree, we should add it.

As workaround you could maybe use [ajaxOptions](https://bootstrap-table.com/docs/api/table-options/#ajaxoptions) [ajaxOptions Example](https://examples.bootstrap-table.com/index.html#options/ajax-options.html).

**Comment by andrew1011111** [comment]
Hi, I understand.
Thank you very much for responding and for your suggestion.

**Comment by UtechtDustin** [comment]
Please let the issue open, so we can find easier and dont forgott to add it :)

**Comment by andrew1011111** [comment]
Ok, sorry...  (๑≧౪≦)

**Comment by wenzhixin** [comment]
I have improved the example: https://examples.bootstrap-table.com/#options/table-ajax.html
https://github.com/wenzhixin/bootstrap-table-examples/commit/04f3961383e8653c46bf43da4ca3ce5c18abc994

**Comment by UtechtDustin** [comment]
in my opinion we should add it in the source code, because its not "custom data" (the data is needed to use the table normal).
@wenzhixin

**Comment by wenzhixin** [comment]
@UtechtDustin I don't think so, because the `ajax` option is a jQuery method. Custom Ajax is just only to replace the default Ajax call.

> This only happens with Ajax with paging on the server side.

With paging on the server side, we need to handle `search`, `limit`, `offset`... in the server instead of in the source code.
