### ISSUE TITLE
大神，在使用stickyheader的时候能否使fixedColumn的设置也起作用呢，或者有什么思路可以提供吗

### ISSUE THREAD

**Issue by Gybggyy** [wenzhixin/bootstrap-table#4302]
大神你好，我使用了stickyheader的设置的同时使用了fixedColumn的设置，有没有什么方法可以使stickyHeader的某些列也冻结呢。
`$el.bootstrapTable('destroy').bootstrapTable({
      columns: columns,
      data: data,
      stickyHeader: true,
	  fixedColumns: true,
	  fixedNumber: 3
    })`

**Comment by wenzhixin** [comment]
现阶段不支持该需求。

**Comment by Gybggyy** [comment]
好的谢谢，使用stickyheader这种设计，如果表格功能设计的复杂的话还真是为难自己。

**Comment by wenzhixin** [comment]
已在 #4899 中增加支持。

**Comment by Gybggyy** [comment]
大神辛苦了，大神6666



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "文翼"<notifications@github.com&gt;; 
发送时间: 2020年2月22日(星期六) 上午9:27
收件人: "wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com&gt;; 
抄送: "Gyb"<572149579@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wenzhixin/bootstrap-table] 大神，在使用stickyheader的时候能否使fixedColumn的设置也起作用呢，或者有什么思路可以提供吗 (#4302)




已在 #4899 中增加支持。
