### ISSUE TITLE
表格编辑的Examples有问题.

### ISSUE THREAD

**Issue by testyt24** [wenzhixin/bootstrap-table#4304]
这是地址：https://examples.bootstrap-table.com/#issues/986.html

**Comment by wenzhixin** [comment]
现在 Bootstrap v4 还不支持，v3 的可以用：https://examples.bootstrap-table.com/index.html?bootstrap3#issues/986.html

**Comment by testyt24** [comment]
好的,




------------------ 原始邮件 ------------------
发件人: "文翼"<notifications@github.com>;
发送时间: 2019年4月17日(星期三) 下午3:59
收件人: "wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com>;
抄送: "じ箜戀"<1543054674@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wenzhixin/bootstrap-table] 表格编辑的Examples有问题. (#4304)




现在 Bootstrap v4 还不支持，v3 的可以用：https://examples.bootstrap-table.com/index.html?bootstrap3#issues/986.html
