### ISSUE TITLE
get value of 2 cell 1 time || set id or class to each cell

### ISSUE THREAD

**Issue by godshades** [wenzhixin/bootstrap-table#4306]
```
           | 20190401 |
        | Progress | Note |
 NameA  |   80%    | OK   |

```
I want click to cell "80%" or "OK" then open modal dialog to edit both, how I can get both value when click 1 of 2
Or how to set id or class for each cell, I think can get data by id or class

**Comment by UtechtDustin** [comment]
Use the event [onClickRow](https://bootstrap-table.com/docs/api/events/#onclickrow) and check the field (third parameter) if its the field of the progress or the note.
Then you get the data from the first parameter `row`.
