### ISSUE TITLE
Can't export all rows when set exportDataType: 'all' at bootstrapTable.

### ISSUE THREAD

**Issue by lveaa** [wenzhixin/bootstrap-table#4308]
When I set the sidePagination: 'service', I only can export the first page rows or the filter rows even if I set exportDataType: 'all' at bootstrapTable. The php page return all rows with jason format.
 I can't find the reason, Can you do me a favor to help me, thanks.

**Comment by UtechtDustin** [comment]
I tested it with this issue https://examples.bootstrap-table.com/.
I know this issue use the export type `basic` but the export Script will just show all rows if the export type is set to `all`.
So i set the pagesize to all and exported the data, which works fine for me.

Could you provide us an jsfiddle ?

**Comment by wenzhixin** [comment]
* Set `sidePagination: 'server'`
* When the request without `limit` need to return all data: https://examples.wenzhixin.net.cn/examples/bootstrap_table/data?offset=0
* Working example: http://dev.bootstrap-table.com/examples/#extensions/export.html
