### ISSUE TITLE
load method not honoring pagination...

### ISSUE THREAD

**Issue by state99** [wenzhixin/bootstrap-table#431]
I am calling the load method like:

$('#table').bootstrapTable('load', myData);

myData is a json object with 2 properties:  total and rows.  When I use the load method, it is not loading the table with the data.

Total contains the number 62.
Rows contains 50 rows of data.

However, if I call:

$('#table').bootstrapTable('load', myData.rows)

This works fine.

**Comment by omatic-hacker** [comment]
how you init your table? I mean how you describe fields name and format for them to show? provide your code... it's not clear right now

**Comment by DanJoeHa** [comment]
I've exactly the same problem. Loading the data through the data-url attribute works just fine. Loading it via 
$('#table').bootstrapTable('load', myData);
doesn't.

The content of "myData" is like this: http://wenzhixin.net.cn/examples/bootstrap_table/data?offset=0&limit=10

**Comment by wenzhixin** [comment]
Hi , `load` method does not support server side pagination now.

**Comment by DanJoeHa** [comment]
Hi, 

thank you for your answer. Will the load method support server side pagination in the future? I would realy appreciate it.

**Comment by state99** [comment]
Yes.  I'm having the same issue has DanJoeHa.

Until this is supported, is there a work around that will accomplish the same thing?

**Comment by state99** [comment]
Is there a way to set the total rows so pagination can be honored than a capture event for each pagination change so that I can call the appropriate ajax call... return that data for that page (and pagesize) and load the grid (with it still showing the page and pagesize that was clicked)?  The reason is we already have some custom code setup for going through each row of data and doing security checking  (for some compliance issues we have to live with) on the data before sending it to the grid (we use to use a different grid with similar events)....

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#431.html

**Comment by DanJoeHa** [comment]
Thanks a lot! Nice work you're doing!

**Comment by slavensaka** [comment]
I'm having this issue. Can this be supported any time soon. 
echo json_encode(['total' => count($myData), 'totalNotFiltered' => count($myData), 'rows' => $myData]);

table.bootstrapTable('load', data.rows) This loads the data 
but i need the pagination rendered also.
