### ISSUE TITLE
服务端分页url请求报错Uncaught TypeError: s.ajax is not a function

### ISSUE THREAD

**Issue by skillnull** [wenzhixin/bootstrap-table#4310]
![image](https://user-images.githubusercontent.com/19986684/56480862-a719f100-64ee-11e9-85c5-577c6561f7da.png)
![image](https://user-images.githubusercontent.com/19986684/56480881-ba2cc100-64ee-11e9-8f0c-6f9275014bdf.png)
各位大佬知道是什么原因吗

**Comment by UtechtDustin** [comment]
Please provide us an jsfiddle.

**Comment by wenzhixin** [comment]
Use `jquery` instead of `jquery slim`.

**Comment by skillnull** [comment]
换成jquery后可以请求了，但是报错
![image](https://user-images.githubusercontent.com/19986684/56481449-a171da80-64f1-11e9-9cfe-e772cf4d8e4c.png)
是要做什么处理吗

**Comment by skillnull** [comment]
使用jquery问题解决了
