### ISSUE TITLE
Pagination Question / Possible Issue

### ISSUE THREAD

**Issue by statesman4** [wenzhixin/bootstrap-table#4316]
Hello, first Thank you for the enhancements you've made to bootstrap table. I have a question about pagination. When there are multiple pages and there is an ellipse in between (...), if you click on the ellipse (even though it is disabled), and then click on Next or Previous, the paging doesn't work. If you click on a page #, it works fine, but clicking on Next or Previous immediately after clicking on ellipse doesn't work. I guess the params are getting cleared when ellipse is clicked. Any workaround?
Thank you.

**Comment by UtechtDustin** [comment]
@statesman4 
Could you provide us an example ?
Its working fine for me with this [example](http://jsfiddle.net/szty28we/1/).

If the example also dont work for you then please tell us your browser (and version)

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days, please reopen the issue if you still need help.

**Comment by statesman4** [comment]
Sorry for the delayed reply. We got is resolved by adding

$('.page-first-separator').off("click"); 

under OnLoadSuccess event.

Thanks

**Comment by UtechtDustin** [comment]
As you can see in my example i cant reproduce your issue.
If you provide us an example where we can reproduce it we could fix it in the source code.

**Comment by statesman4** [comment]
I will provide an example.
Thanks

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days, please reopen the issue if you still need help.
