### ISSUE TITLE
New Build

### ISSUE THREAD

**Issue by scottgrobinson** [wenzhixin/bootstrap-table#4317]
Is it possible to get a new release? :) Specifically I'm looking for https://github.com/wenzhixin/bootstrap-table/pull/4268/files

I know I can do a custom build, but I've not had to do that with my project yet so it would be useful to avoid it. If needed - I could, but thought I'd ask here first :)

**Comment by wenzhixin** [comment]
2.0 @beta version？

**Comment by pchaganti** [comment]
Yes. Once people start using the @beta version for a bit, it will expand the number of people trying all the recent changes, and hopefully find any lingering issues quickly before an actual 2.0 release.

**Comment by UtechtDustin** [comment]
I thought #4239 is the version 2.0 ?
So it should be version 1.15 in my opinion.
