### ISSUE TITLE
Printing RTL

### ISSUE THREAD

**Issue by kwagdy** [wenzhixin/bootstrap-table#4318]
We have an RTL table (in Arabic) with hidden columns by default, we'd like to enable printing, but 

1. It generates a page with an LTR table rather than RTL as originally shown on page
2. It shows the hidden columns!
3. It prints a title on top of the page in English "**Printed on: Tue Apr 23 2019 12:15:37 GMT+0400....**"

Is there a way to:
1. Force RTL as shown on original page? 
2. Keep hidden columns hidden
3. Remove the English date title, or replace with a custom message, maybe also logo or website title?
4. Control printing CSS in general?

Demo: https://jsfiddle.net/k78c6meo/11/

**Comment by UtechtDustin** [comment]
Could you provide us an jsfiddle please ?

**Comment by kwagdy** [comment]
@UtechtDustin thanks for feedback, I'm trying to build one here [https://jsfiddle.net/svm49fb8/1/](https://jsfiddle.net/svm49fb8/1/) but it I am not able to show the print button for some reason 🤔 !

**Comment by UtechtDustin** [comment]
@kwagdy you used wrong links for the dependencies e.g. https://jsfiddle.net/svm49fb8/4/cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.14.2/extensions/print/bootstrap-table-print.min.js
You can alos see it if you open the develop console :-)

Working Demo: https://jsfiddle.net/k78c6meo/11/

**Comment by kwagdy** [comment]
Oh, thank you for the heads up =) btw, it works on prod with the same dependencies!
