### ISSUE TITLE
同时使用editable 和 undefinedText时 undefinedText 不生效

### ISSUE THREAD

**Issue by eye1121** [wenzhixin/bootstrap-table#4319]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by UtechtDustin** [comment]
Please translate it to english @eye1121 or @wenzhixin, the translated version from google makes no sense for me.

**Comment by UtechtDustin** [comment]
I translated word for word, now i understand the issue.
The issue that if you use the undefinedText option and the editable extension the undefinedText option will be ignored and undefined text will be displayed with the default `-`.

**Comment by wenzhixin** [comment]
Thanks @UtechtDustin

**Comment by eye1121** [comment]
Sorry I did’t see this.I think you understand wrong.The problem is
that if you use the undefinedText option and the editable extension the undefinedText option will be ignored and undefined text will be displayed with the text ‘undefine’ instead of the default -.Sorry if I did not express the problem clearly.

________________________________
发件人: Dustin Utecht <notifications@github.com>
发送时间: Friday, April 26, 2019 9:12:40 AM
收件人: wenzhixin/bootstrap-table
抄送: eye1121; Mention
主题: Re: [wenzhixin/bootstrap-table] 同时使用editable 和 undefinedText时 undefinedText 不生效 (#4319)


I translated word for word, now i understand the issue.
The issue that if you use the undefinedText option and the editable extension the undefinedText option will be ignored and undefined text will be displayed with the default -.

―

**Comment by UtechtDustin** [comment]
@eye1121 
I understood you, the fix already in our develop branch.
[Working Example](https://jsfiddle.net/x8qasofp/2/) with my fix and the `undefinedText` option.

**Comment by eye1121** [comment]
Thank you very much!


________________________________
发件人: Dustin Utecht <notifications@github.com>
发送时间: Saturday, April 27, 2019 6:14:39 PM
收件人: wenzhixin/bootstrap-table
抄送: eye1121; Mention
主题: Re: [wenzhixin/bootstrap-table] 同时使用editable 和 undefinedText时 undefinedText 不生效 (#4319)


@eye1121<https://github.com/eye1121>
I understood you, the fix already in our develop branch.
Working Example<https://jsfiddle.net/x8qasofp/2/> with my fix and the undefinedText option.

―
