### ISSUE TITLE
Import locale files with Webpack

### ISSUE THREAD

**Issue by luylucas10** [wenzhixin/bootstrap-table#4323]
I try to import the locale file from node-modules, but It doesn't work or I did correctly. So I had to copy the file from node directory and make a relative import:
`import "bootstrap-table";`
`import "../../util/bootstrap-table-locale-all";`

I try to do that:
`import "bootstrap-table-locale-all";`
but with no success.

Is it possible to do making a import statement to take from node-modules directory?

**Comment by UtechtDustin** [comment]
The support of Webpack is currently only in our develop branch not in an official release.

**Comment by luylucas10** [comment]
Well, I installed the npm stable version of this package and It works fine.
