### ISSUE TITLE
There should be tooltip for Url on global variable pane

### ISSUE THREAD

**Issue by zaidmir5** [wenzhixin/bootstrap-table#4326]
![image](https://user-images.githubusercontent.com/48056293/56783970-ece6fa00-680b-11e9-975c-b5ad0d5b60bf.png)

There should be tooltip for url,but this table comes dynamically..
How can i add tooltip for this.

**Comment by zaidmir5** [comment]
<th data-field="url" class="table-column-ellipsis" data-sortable="true" data-width="34%">URL</th>

**Comment by zaidmir5** [comment]
![image](https://user-images.githubusercontent.com/48056293/56784081-7eef0280-680c-11e9-96cc-fd77096e32ac.png)
This is the code for it

**Comment by wenzhixin** [comment]
You can use `formatter` column option to do what you want: https://bootstrap-table.com/docs/api/column-options/#formatter.

**Comment by zaidmir5** [comment]
![image](https://user-images.githubusercontent.com/48056293/56891502-511eed80-6a9a-11e9-8156-83e0852eb8bf.png)
How cam i change the value of this drop-down to another value or i can use a tooltip here.
Right now it is showing me FullScreen

**Comment by UtechtDustin** [comment]
@zaidmir5 
This Bug is already fixed in the develop branch, so in the next version it shows the correct title.

**Comment by zaidmir5** [comment]
@UtechtDustin I can't wait for the next version please provide a small fix for now.

**Comment by UtechtDustin** [comment]
@zaidmir5 
Then apply the commit/fix your self on the sourde code.
https://github.com/wenzhixin/bootstrap-table/commit/78465c7eac29a51645a6e4917fb5e5d58a63dc21
