### ISSUE TITLE
Filtering by column gets interrupted by load/append data

### ISSUE THREAD

**Issue by metinc** [wenzhixin/bootstrap-table#4327]
I have a table that gets updated every second. I want to use an extension to filter by column but as I enter the search text some input is lost when the table updates. However the default search box outside of the table does not show this problem.
To recreate it open my fiddle and try to enter a long word into the column filter box.

[jsfiddle](http://jsfiddle.net/cvbdxej3/1/)

I tried the extensions bootstrap-table-select2-filter and filter-control/bootstrap-table-filter-control and both show the same behaviour.

**Comment by UtechtDustin** [comment]
Could you explain why you update the table any second o.O ?

**Comment by metinc** [comment]
In my case the table is showing sensor values that keep changing.

**Comment by UtechtDustin** [comment]
Should we try to fix that ? @wenzhixin @djhvscf 
I think its an edge case, the "issue" can be reduced by using [searchTimeOut](https://bootstrap-table.com/docs/api/table-options/#searchtimeout)=0.
It would be hard to fix that because we rerender the table...

**Comment by djhvscf** [comment]
I think at this moment we can use the searchTimeout=0 since as @UtechtDustin this is an edge case

**Comment by UtechtDustin** [comment]
@wenzhixin if you agree please close the issue :-)
