### ISSUE TITLE
Help needed: bootstrap-table + custom x-editable value update

### ISSUE THREAD

**Issue by panthernet** [wenzhixin/bootstrap-table#4329]
Here's the fiddle: https://codepen.io/panthernet/pen/qwQvpM
I want to implement x-editable 'select' type (combobox) inside table cell. So far I made it work visually but changing value using the combobox won't change it inside the table cell  when I use `getData` method.

Bootstrap3, X-editable

Steps:
1. Run fiddle
2. Press Add Entry
3. Enter values (click) for 3 fields. Second field (Group) is combobox.
4. Press F12 to open console
5. Press Save button
6. Debugger will stop before save query. You can run: `$table.bootstrapTable('getData')` command in console to see that second field (Group) has empty value. Simple text fields has correct values.

PS: Group editable is configured using `$('.groupValue').editable` in JS. I use `groupFormatter` to add custom editable inside the table cell.

Is there any way I can make it work? Just need to update cell value after the selection is complete (editable `success:` method).

**Comment by panthernet** [comment]
Maybe someone can give me a clue how `bootstrap-table` catches/stores the values? I'm not as good with frontend compared to backend so any tips might be helpful. I see that table entry has new value in every tag/attribute but still `getData` fetches an old value.

**Comment by panthernet** [comment]
Sadly, no help from here. I've managed to solve it a bit heavy way:
```

function updateEditables() {
    $('.groupValue').editable({
        type: 'select',
        source: "{saGroupList}",
        success: function (a, newValue) {
	        debugger;
            $(this).attr("data-value", newValue);
            var pk = $(this)[0].getAttribute("data-pk");
            var row = $table.bootstrapTable('getRowByUniqueId', pk);
            row.Group = newValue;
            $table.bootstrapTable('updateByUniqueId',
	            {
		            id: pk,
		            row: row
	            });
        }
    });
}
```

**Comment by UtechtDustin** [comment]
You created the issue one day ago, please be patient its not our work its our leisure/free time.

**Comment by UtechtDustin** [comment]
The function `getData` will return the data of the Table, NOT the data of the DOM so your idea using a `update[..]` method is correct !
