### ISSUE TITLE
table header does not moving with the body while having large no. of columns?

### ISSUE THREAD

**Issue by ashishsober** [wenzhixin/bootstrap-table#433]
having data from server side and trying to show 15 columns ,but the header is not moving with the data
tried this,

 $(function () {
              buildTable($('#events-result'), 15, 50);
         });

**Comment by omatic-hacker** [comment]
```javascript
$(function () {
    $('#tableId').bootstrapTable(); // init via javascript

    $(window).resize(function () {
        $('#tableId').bootstrapTable('resetView');
    });
});
```

**Comment by ashishsober** [comment]
thank you for your help ,but the code is not working.

 $('#tableId').bootstrapTable('resetView');// actually i did not understand whats conclude 'resetView here.

or otherwise i have to include any js file for that because I already added these files
<script src="content/js/jquery.min.js"></script>
<script src="content/js/bootstrap-table.js"></script>
<script src="content/js/bootstrap-table.min.js"></script>
<script src="content/js/bootstrap.js"></script>

please put your suggestion,

**Comment by ashishsober** [comment]
thank you for your help ,but the code is not working.

          $('#tableId').bootstrapTable('resetView');// actually i did not understand whats conclude 'resetView here.

or otherwise i have to include any js file for that because I already added these files

      jquery.min.js
      bootstrap-table.js
      bootstrap-table.min.js
      bootstrap.js

please put your suggestion,

**Comment by omatic-hacker** [comment]
show your code pls

Here you can look up at example (Use resetView to reset the header width): 

http://issues.wenzhixin.net.cn/bootstrap-table/#283.html

**Comment by ashishsober** [comment]
Here is my code:
        
         <link rel="stylesheet" href="content/css/bootstrap.css">
         <link rel="stylesheet" href="content/css/bootstrap-table.css">

          <table id="table-pagination1" data-toggle="table" data-url="/getIncludeDel"?offset=offset"&search="active"&limit=limit
                             data-height="3850"
				             data-side-pagination="server" 
				             data-pagination="true" 
				             data-page-list="[5,10,20]" 
				             data-search="true" 
				             data-query-params="queryParams">
							    <thead>
								     <tr>
								        <th data-field="user" data-align="left" data-sortable="true">User</th>
								        <th data-field="Year" data-align="left" data-sortable="true">Date</th>
								        <th data-field="Vacation" data-align="left" data-sortable="true">Vacation Holiday</th>
								        <th data-field="Floating" data-align="left" data-sortable="true">Floating Holiday</th>
								        <th data-field="Company" data-align="left" data-sortable="true">Company Holiday</th>
								        <th data-field="Development" data-align="left" data-sortable="true">Development Holiday</th>
								        <th data-field="Bank" data-align="left" data-sortable="true">Bank Holiday</th>
								        <th data-field="Out" data-align="left" data-sortable="true">Out of Office</th>
								        <th data-field="Others" data-align="left" data-sortable="true">Others</th>
								        <th data-field="Status" data-align="left" data-sortable="true">Status</th>
								        <th data-field="Total" data-align="left" data-sortable="true">Total</th>
								        <th data-field="key" data-align="left" data-sortable="true">Update</th>
								     </tr>
								</thead>
							</table> 

          <script src="content/js/jquery.min.js"></script>
          <script src="content/js/bootstrap-table.js"></script>
         <script src="content/js/bootstrap-table.min.js"></script>
         <script src="content/js/bootstrap.js"></script>


        <script>
            function queryParams(params) {
            return {
            limit: params.pageSize,
            offset: params.pageSize * (params.pageNumber - 1), 
            search:params.searchText,
            name: params.sortName,
           order: params.sortOrder 
        };
     }
    </script>

so if u need anything on that,then ask me.
thank you

**Comment by omatic-hacker** [comment]
Could you provide example on  [jsfiddle](http://jsfiddle.net/) with data that show the bug ? Because code is ok.

**Comment by ashishsober** [comment]
In fiddle it is working u can see here :[fiddle link](http://jsfiddle.net/wenyi/e3nk137y/26/light/)
but i m getting values from server side as i have shown u above,but in this fiddle ex: it is inserting values in buildtable function.

**Comment by ashishsober** [comment]
thanks alot your reset view is working now ,I found the[code](http://jsfiddle.net/wenyi/e3nk137y/40/light/)

**Comment by wenzhixin** [comment]
OK, close this issue.
