### ISSUE TITLE
Getting error while trying to use filter-control extension

### ISSUE THREAD

**Issue by Sourabh25** [wenzhixin/bootstrap-table#4331]
I am getting the below error while trying to use the filter-control-extension

Uncaught TypeError: Class extends value undefined is not a constructor or null
    at bootstrap-table-filter-control.js:595
    at bootstrap-table-filter-control.js:917

Could you please updater how can i resolve this

**Comment by UtechtDustin** [comment]
We cant help without a example, please provide us an jsfiddle.

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days.
