### ISSUE TITLE
列属性 escape 设置 true 不生效,有全局设置 文本渲染的么, XSS隐患

### ISSUE THREAD

**Issue by free-luy** [wenzhixin/bootstrap-table#4332]
{
									field : 'remark', 
									title : '描述' ,
									escape: true
								}

**Comment by free-luy** [comment]
/*
* bootstrap-table - v1.9.0 - 2015-09-30
* https://github.com/wenzhixin/bootstrap-table
* Copyright (c) 2015 zhixin wen
* Licensed MIT License
*/

**Comment by wenzhixin** [comment]
Please update to the latest version.
