### ISSUE TITLE
npm install bootstrap-table is not working 

### ISSUE THREAD

**Issue by Sourabh25** [wenzhixin/bootstrap-table#4333]
Hi I am getting the below error when I am executing the following  npm cpmmand
npm install bootstrap-table

HQSML-152086:bootstrap-grid sroy107$ npm install bootstrap-table
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "bootstrap-table" under a package
npm ERR! also called "bootstrap-table". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sroy107/.npm/_logs/2019-04-29T17_24_58_206Z-debug.log
HQSML-152086:bootstrap-grid sroy107$ 

Could you please let me know what I am doing wrong here?

**Comment by UtechtDustin** [comment]
`also called "bootstrap-table". Did you name your project the same`
Do you named your project also `bootstra-table` ?

**Comment by Sourabh25** [comment]
Yeah. I got this resolved by changing the name in the package.json . Thanks for looking in to it.

But after this when I am trying npm run build, I am getting the below error:

sudo npm run build
Password:

> bootstrap-grid@1.14.2 build /Library/WebServer/Documents/bootstrap-dashboard/bower_components/bootstrap-table
> run-s lint clean *:build

sh: run-s: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bootstrap-grid@1.14.2 build: `run-s lint clean *:build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bootstrap-grid@1.14.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sroy107/.npm/_logs/2019-04-29T17_54_13_309Z-debug.log

Could you please help me on this

**Comment by UtechtDustin** [comment]
It fails on the `bootstrap-grid` not on our `bootstrap-table`, so please ask on their repository.

**Comment by Sourabh25** [comment]
@UtechtDustin  I used the same code. I only changed the name in the package-json to bootstrap-grid

**Comment by UtechtDustin** [comment]
Okay, so it would be better to use a name which not already exists (as popular package).

**Comment by Sourabh25** [comment]
@UtechtDustin okay. Could you please help me on the npm run build issue?

**Comment by UtechtDustin** [comment]
Im not so familar with npm, but i found this [issue](https://github.com/0xProject/0x-starter-project/issues/10) which has the same error.
Try the suggested fix.

Btw. before you ask for help try to search the issue some minutes :)

**Comment by wenzhixin** [comment]
try to run `npm run build` without `sudo`?

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days, please reopen the issue if you still need help with that.
