### ISSUE TITLE
Implement a version number

### ISSUE THREAD

**Issue by tangram67** [wenzhixin/bootstrap-table#4334]
Hi to all.

Is it possible to implement a version number like this:

```
--- bootstrap-table.js	2019-03-18 17:13:02.000000000 +0100
+++ bootstrap-table-versioned.js	2019-04-29 20:47:31.865557373 +0200
@@ -498,6 +498,7 @@
 
     // BOOTSTRAP TABLE CLASS DEFINITION
     // ======================
+    var VERSION = '1.14.2';
 
     var DEFAULTS = {
       height: undefined,
@@ -3709,6 +3710,7 @@
     BootstrapTable.LOCALES = LOCALES;
     BootstrapTable.COLUMN_DEFAULTS = COLUMN_DEFAULTS;
     BootstrapTable.EVENTS = EVENTS;
+    BootstrapTable.VERSION = VERSION;
 
     // BOOTSTRAP TABLE PLUGIN DEFINITION
     // =======================
@@ -3757,6 +3759,7 @@
     $.fn.bootstrapTable.defaults = BootstrapTable.DEFAULTS;
     $.fn.bootstrapTable.columnDefaults = BootstrapTable.COLUMN_DEFAULTS;
     $.fn.bootstrapTable.locales = BootstrapTable.LOCALES;
+    $.fn.bootstrapTable.version = BootstrapTable.VERSION;
     $.fn.bootstrapTable.methods = allowedMethods;
     $.fn.bootstrapTable.utils = Utils;
 
@@ -3767,4 +3770,4 @@
       $('[data-toggle="table"]').bootstrapTable();
     });
   })(jQuery);
-});
\ Kein Zeilenumbruch am Dateiende.
+});
```
So one can use the following code to get the version string:

```
function getBootstrapTableVersion() {
	return $.fn.bootstrapTable.version;
};
```
Thanks in advance,
Dirk.

**Comment by UtechtDustin** [comment]
Sure its possible, could you explain for what you need the version ?

Möglich ist es natürlich, kannst du uns erklären wofür genau diese Funktion brauchst ?

**Comment by UtechtDustin** [comment]
Makes sense i guess, also other populare Libs has the version as constant/getter.
Pull Requests are welcome :-)
****
Macht Sinn, sollte implementiert werden. Haben auch einige andere beliebte Libs.
Kannst gerne ein Pull Request stellen.

**Comment by tangram67** [comment]
The idea behind the version was to display it in the web interface. So I do not have to compare the file version to a newly released bootstrap-table version to decide when to use a new version. I also find it nice to have jQuery, Bootstrap, bootstrap-table and other components versions in an summerized overview.

Regarding the implemantation itself, I looked at what Bootstrap is doing. They use a similar method to get the version of each component. I will more likely see the decision of the "real world" implementation is up to you since the version(-getter) does not break any functionality.

**Comment by tangram67** [comment]
Just saw that development branch had some major changes, so I tried to setup a pull request on the current files:

#4336

**Comment by wenzhixin** [comment]
Merged, thanks!
