### ISSUE TITLE
Bootstrap-table-flat + data-side-pagination="server" + search not working

### ISSUE THREAD

**Issue by binottoeduardo** [wenzhixin/bootstrap-table#434]
Hello,
After fix "Fix #389 Bootstrap-table-flatJSON is not working" a search doesn't working, same error which "fix#389" but with  search add

![table](https://cloud.githubusercontent.com/assets/10564853/5781478/3aa198e0-9d9a-11e4-9e33-2ed501319e33.JPG)

**Comment by wenzhixin** [comment]
Hi, can you provide jsFiddle?

**Comment by binottoeduardo** [comment]
I cannot provide in jsFiddle, I dont profile in have jsFiddle.

**Comment by SimaoLiu** [comment]
Hi I have encountered the same problem.
the flat JSON is not working when displaying the search results.

**Comment by wenzhixin** [comment]
Please update `src/extensions/flatJSON/bootstrap-table-flatJSON.js` to fix this issue.

**Comment by SimaoLiu** [comment]
Thanks! It's working well now with the fix.

**Comment by binottoeduardo** [comment]
Thanks!
