### ISSUE TITLE
showColumns menu toggle problem inside bootstrap tabs

### ISSUE THREAD

**Issue by hbtsmith** [wenzhixin/bootstrap-table#4341]
When bootstrap-table is placed inside a bootstrap tab content, showColumn menu does not work.

The problem is, the select menu to choose what columns to present is always open, always visible, and there is nothing it can be done to restore the behavior of hide/show as far as I know.

<div class="tab-content">
                            <div id="mocu_notas_tab" class="tab-pane fade show active" role="tabpanel" aria-labelledby="mocu_notas_tab_link">
</div>

These are the settings of the table:

$mocuTablePedidosAbertos.bootstrapTable({
            toolbar: ".mocuToolbar",
            clickToSelect: true,
            showRefresh: true,
            search: true,
            showToggle: true,
            showColumns: true,
            pagination: true,
            searchAlign: 'left',
            pageSize: 10,
            clickToSelect: false,
            pageList: [10, 25, 50, 100],
            url: 'url_blablablab_customer='+id_customer,
            sidePagination: 'server', 

            formatShowingRows: function(pageFrom, pageTo, totalRows) {
                //do nothing here, we don't want to show the text "showing x of y from..."
            },
            formatRecordsPerPage: function(pageNumber) {
                return pageNumber + " registros";
            },
            icons: {
                refresh: 'fa fa-refresh',
                toggle: 'fa fa-th-list',
                columns: 'fa fa-columns',
                detailOpen: 'fa fa-plus-circle',
                detailClose: 'fa fa-minus-circle'
            }
        });
I am using version: 1.8.1

Is that a known bug?

I can send  prints if wanted hbt.vieira@gmail.com

**Comment by UtechtDustin** [comment]
The last version is the 1.14.2, so you are using a very old version.
Please test it with the newest version, if you still have the issue please provide us an example(using jsfiddle).

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days, if you still need help with that please reopen the issue and provide us an example.
