### ISSUE TITLE
能够提供一个vue.js的使用示例？

### ISSUE THREAD

**Issue by macdoor** [wenzhixin/bootstrap-table#4342]
前端转向vue.js，打算继续使用bootstrap-table，希望能提供提供一个vue.js的使用示例，后面改不要紧

**Comment by wenzhixin** [comment]
Added VueJS docs into develop branch: http://dev.bootstrap-table.com/docs/vuejs/introduction/

* Browser: http://dev.bootstrap-table.com/docs/vuejs/browser/
* Webpack: http://dev.bootstrap-table.com/docs/vuejs/webpack/
* Component: http://dev.bootstrap-table.com/docs/vuejs/component/

**Comment by UtechtDustin** [comment]
@wenzhixin 
Good to know that we have a dev subdomain, is that always the develop branch ?

**Comment by wenzhixin** [comment]
Yes @UtechtDustin, but the sub domain is only for preview.

**Comment by wenzhixin** [comment]
Added examples:

* https://examples.bootstrap-table.com/#welcomes/vue-component.html
* https://live.bootstrap-table.com/example/welcomes/vue-component.html
* https://github.com/wenzhixin/bootstrap-table-examples/tree/develop/vue-starter
