### ISSUE TITLE
export part shows strangely in Bootstrap3

### ISSUE THREAD

**Issue by Jane-Eyre** [wenzhixin/bootstrap-table#4343]
when I set showExport is true and import bootstrap3 in my html page, this export part is not shown correctly, it looks like this:

<img width="1237" alt="Screen Shot 2019-05-05 at 4 05 49 PM" src="https://user-images.githubusercontent.com/16831031/57190689-e402d080-6f4f-11e9-9421-194d1b619e23.png">

if I import bootstrap4:

<img width="1177" alt="Screen Shot 2019-05-05 at 4 09 08 PM" src="https://user-images.githubusercontent.com/16831031/57190707-288e6c00-6f50-11e9-8522-f7e188e90c17.png">

the export part looks correctly, but my navigation bar is based on bootstrap3, so it looks like bad.
what can I do to make export part correct in bootstrap3?

**Comment by Jane-Eyre** [comment]
BTW, the starter template in [https://bootstrap-table.com/docs/getting-started/introduction/](url)
is based on bootstrap 4.2.1.

**Comment by wenzhixin** [comment]
Examples:
https://examples.bootstrap-table.com/index.html?bootstrap3
https://examples.bootstrap-table.com/index.html?bootstrap3#extensions/export.html

**Comment by Jane-Eyre** [comment]
I have read these examples, but still it doesn't work.
Is there something wrong with my codes or just export part do not support Bootstrap3 well?

**Comment by UtechtDustin** [comment]
Please provide us an example(using jsfiddle).

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days, if you still need help please reopen the issue and provide us an example.
