### ISSUE TITLE
Bootstrap Custom Checkbox in column selector

### ISSUE THREAD

**Issue by earlseay** [wenzhixin/bootstrap-table#4344]
Bootstrap Custom Checkbox in column selector

is it possible to get a custom bootsrap checkbox in the columns selector?

[Link to my SO question](https://stackoverflow.com/questions/56044509/bootstrap-table-plugin-display-bootstrap-custom-checkbox-in-column-selection-dro)

Also, where should I ask questions like this? I don't want to litter you gitHub with these "issues" but I don't know how to contact you guys about this, so I took to SO first.

**Comment by earlseay** [comment]
I'm also looking at adding a "Toggle All" to that drop down if possible. I see you have the js function for that already, any reason not to add an option for it?

**Comment by UtechtDustin** [comment]
Could you explain what do you mean with custom checkbox ? (style ? functionality?)

>  any reason not to add an option for it

There is no reason to not implement an "Toggle All" option, Pull Requests are welcome :)

**Comment by earlseay** [comment]
I'll look at adding the toggle all. For the Bootstrap custom checkboxes I was talking about this
https://getbootstrap.com/docs/4.3/components/forms/#checkboxes instead of just a generic html input checkbox.

I've modified my local copy, but I don't know if you guys have a better way to do it.

**Comment by UtechtDustin** [comment]
Oh okay i thought you want to add/change something else then the `toggle all`.
We should consider to add that thing (as option) @wenzhixin @djhvscf.

**Comment by djhvscf** [comment]
You mean add 'toggle all' method? I'm sorry I'm not clear about this issue..

**Comment by UtechtDustin** [comment]
Yes, he wants an checkbox which toogles all other checkboxes in the columns dropdown.

**Comment by earlseay** [comment]
Do you guys have a discord or a Facebook group or some way to chat about stuff?

**Comment by UtechtDustin** [comment]
For what do you need it ?
We just have a "internal" chat.

**Comment by earlseay** [comment]
Awesome! Thanks for getting to this so quickly. Do you guys have a release planned for some of these minor things or are you past the point of no return for a minor version and I need to wait for the 2.0 version?

**Comment by UtechtDustin** [comment]
We will release the next version (1.15.0) soon, you can see the last todo here #4239.
