### ISSUE TITLE
关于treegrid的问题

### ISSUE THREAD

**Issue by wengxiuhao** [wenzhixin/bootstrap-table#4345]
treegrid的src和dist似乎不匹配？
/src/extensions/treegrid/bootstrap-table-treegrid.js 中48行

const defaultItem = $.extend(true, {}, item)
node._level = defaultItem._level + 1
node._parent = defaultItem

这里的 $.extend(**true**, {}, item) 会引起浏览器假死

而在 /dist/extensions/treegrid/bootstrap-table-treegrid.js 中相关代码已被改成
var node = nodes[i];
node._level = item._level + 1;
node._parent = item;
不会出现浏览器假死

为何src和dist的代码不同？

**Comment by wenzhixin** [comment]
你说的是 master 还是 develop 分支呢？正式发版是 master，develop 是开发版本，等发布版本的时候才会更新 dist 文件夹。

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days, please reopen the issue and answer the question of @wenzhixin if you still need help.
