### ISSUE TITLE
small icon issue

### ISSUE THREAD

**Issue by aducom** [wenzhixin/bootstrap-table#4348]
In the source code, the icon fa fa-sync is used. In fact, this causes a blank icon. In fontawesome 4 this should be fa-refresh, in font-awesome 5 the prefix is fas and thus should be fas fa-sync (for the solid version). Didn't want to make a pull request for this as it is a very tiny issue.

**Comment by UtechtDustin** [comment]
Please discribe the issue and provide us an issue, as described in the example issue text.

**Comment by aducom** [comment]
In the source code, the icon fa fa-sync is used. In fact, this causes a blank icon. In fontawesome 4 this should be fa-refresh, in font-awesome 5 the prefix is fas and thus should be fas fa-sync (for the solid version). Didn't want to make a pull request for this as it is a very tiny issue.

**Comment by aducom** [comment]
Sorry, you where too quick in your response ;-)

**Comment by UtechtDustin** [comment]
As you can see in our examples both works fine:
bootstrap3: https://examples.bootstrap-table.com/index.html?bootstrap3 ([glyphicon glyphicon-refresh icon-refresh](https://getbootstrap.com/docs/3.3/components/))
bootstrap4: https://examples.bootstrap-table.com/  ([fa fa-sync](https://fontawesome.com/v4.7.0/icon/refresh))
Please provide us an example for bootstrap 3.

@wenzhixin @djhvscf 
Consider to implement an icon prefix option (for fontawesome (`fa`/`fas`))

**Comment by aducom** [comment]
I am working in Bootstrap 4. This is a font-awesome 'issue'. Easy to fix so it's a minor issue for me. google for fa fa-sync, and you will not find it ;-)

**Comment by aducom** [comment]
Found a similar issue with caret-square-down/up which is in Font Awsome 5, counterpart in 4 is .fa-caret-square-o-down/up. 

Perhaps this can be solved by adding a parameter to select font version 4 or 5. Not all bootstrap components are ready for the latest FA version yet and there could arise problems if you need to load both icon sets.

**Comment by UtechtDustin** [comment]
As  already written in my last post, we (@wenzhixin, @djhvscf  and me) will consider to implement an option to select between the icon set.

**Comment by aducom** [comment]
Didn't meant to be abusive. Sorry.

**Comment by UtechtDustin** [comment]
No problem, just give us some time :-)

**Comment by wenzhixin** [comment]
@aducom You can custom define the [iconsPrefix](https://bootstrap-table.com/docs/api/table-options/#iconsprefix) and [icons](https://bootstrap-table.com/docs/api/table-options/#icons) options to solve the problem. 
Examples:
https://examples.bootstrap-table.com/#options/table-icons.html
https://examples.bootstrap-table.com/#options/icons-prefix.html

As you can see, in the example we use `ionicons` instead of `font-awesome`.
https://examples.bootstrap-table.com/#options/icons-prefix.html#view-source

**Comment by UtechtDustin** [comment]
Didnt knew that we already have an option for that :D

**Comment by aducom** [comment]
Need to look into this. I hacked the dist version ;-)
