### ISSUE TITLE
data-maintain-selected does not work when data-side-pagination is server

### ISSUE THREAD

**Issue by aducom** [wenzhixin/bootstrap-table#4349]
In a way, I can understand why; as data is retrieved from the server on each page request, but I could not find it in the docs. So I'm not sure if this is a feature request, a bug, or not implemented.

**Comment by UtechtDustin** [comment]
Use the [onCheck](https://bootstrap-table.com/docs/api/events/#oncheck) event to send the id(or something else) to your server, so for the next request your server knew that this row was checked and you can send the right data for the checkbox.

**Comment by aducom** [comment]
That's a good option. Still learning ;-) Thnx.

**Comment by wenzhixin** [comment]
You can checkout this example: https://examples.bootstrap-table.com/index.html#issues/917.html
ref #917
