### ISSUE TITLE
How to append a variable to queryParam?

### ISSUE THREAD

**Issue by aducom** [wenzhixin/bootstrap-table#4350]
I found an item regarding this from 2014 but it gave me no solution.

![image](https://user-images.githubusercontent.com/5610893/57653660-a4348c80-75d2-11e9-96cb-407924c5e4c2.png)

The get gives me:

![image](https://user-images.githubusercontent.com/5610893/57653709-bd3d3d80-75d2-11e9-9cc1-3cbf0fb32e86.png)

Besides that the value is empty I don't get the other params. I guess I'm doing something wrong, but what is the most simple way to append an extra parameter (in my case a csrf token)?

**Comment by UtechtDustin** [comment]
Please use the table option [queryParams](https://bootstrap-table.com/docs/api/table-options/#queryparams), you can find an example [here](https://examples.bootstrap-table.com/index.html#options/query-params.html).

As you can see in the example we add the new parameter to the params (given as first argument) and return this back (you return a **new** object).

If still need help please provide us an example([jsfiddle](https://jsfiddle.net/)).

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by aducom** [comment]
Yes, I managed ;-)
