### ISSUE TITLE
Export Issue with footer & sorting

### ISSUE THREAD

**Issue by sebj54** [wenzhixin/bootstrap-table#4351]
Hi there,

I figured a strange bug when exporting a table with a footer while having a column sorted.
This issue occurs when we define a footer for a given column while having the same column sorted. 

**What is happening?**
A row is replaced with the footer content and the footer is also appended to the end of the exported file (any export type).

![image](https://user-images.githubusercontent.com/5880435/57697832-68420b80-7654-11e9-8e46-992c119e0632.png)

If I remove the sorting from the table options, the footer is only appended at the end of the exported file, there is no replacement.

![image](https://user-images.githubusercontent.com/5880435/57697818-611afd80-7654-11e9-88a5-97d6b97c6746.png)

I made a codesandbox for you to experiment the issue:

[![Edit static](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yvxn9vz309?fontsize=14)

To me, the expected behavior would be to have rows sorted but with only one footer (appended).

I hesitated to post this issue here or on tableExport plugin's repo but could not figured it out. 
I posted it here because the sorting options are causing the issue.

Thanks for your help and let me know if I can help in any way! :)

**Comment by djhvscf** [comment]
Thanks @sebj54. We're looking into it
