### ISSUE TITLE
bootstrap-table-filter-control options sorting

### ISSUE THREAD

**Issue by kentenzer** [wenzhixin/bootstrap-table#4353]
Using Boostrap table by whenzhixin with filter-control extension. http://bootstrap-table.wenzhixin.net.cn/extensions/#table-filter-control

I would like the options display in the select to be sorted in numerical order.

Code is available at: https://jsfiddle.net/yd75psoc/4

You will see that options are shown in the following order: 1, 10, 2.
<img width="271" alt="Screen Shot 2019-05-15 at 10 40 14" src="https://user-images.githubusercontent.com/11169160/57786223-1a371180-7701-11e9-95e3-32e1f4c55839.png">

I need these values to be displayed in numerical order: 1, 2, 10.

**Comment by kentenzer** [comment]
Adding cross-reference: 
https://stackoverflow.com/questions/56152288/bootstrap-table-filter-control-options-sorting/56205977

**Comment by UtechtDustin** [comment]
I dont know who/what, but something already sort it  :)
Demo with our develop Branch: https://jsfiddle.net/6Lmv73p8/2/

@kentenzer In the next version it will be sorted.
