### ISSUE TITLE
Grid is retrieving data twice when using classes

### ISSUE THREAD

**Issue by aducom** [wenzhixin/bootstrap-table#4355]
I have a strange issue. I used the sample https://examples.bootstrap-table.com/#options/table-classes.html#view-source. In this sample there is the next javascript:
![image](https://user-images.githubusercontent.com/5610893/57880495-316c2100-781f-11e9-811a-da95150bedcf.png)

As I already know the classes I want I made the next javascript
![image](https://user-images.githubusercontent.com/5610893/57880238-8c514880-781e-11e9-8e6b-e5fbbbaaf286.png)

If I run my program I can see that my data is retrieved twice, on each bootstraptable line:
![image](https://user-images.githubusercontent.com/5610893/57880346-cd495d00-781e-11e9-92a0-b20ed8a31888.png)

If I remove the refresh options line the data is retrieved only once.

I stepped through the javascript code and could see that the first time a formatnomatches is displayed and then the data appears in the second pass, although both calls have returned a full set of data.

I wonder what is happening here. Am I doing something wrong, is this expected behaviour or a bug? 

btw, if I remove the first bootstraptable line I also get one call, but the classes are not applied:
![image](https://user-images.githubusercontent.com/5610893/57881095-b0158e00-7820-11e9-9d41-a1117f30112e.png)

I have no idea how to make a fiddle of this.

**Comment by aducom** [comment]
The reason why I can't make a fiddle is that I'm using a php backend and use xdebug to see what's going on. I receive the data request, it's being processed and returned. Single if there's only one $table.boostrapTable() or ('refreshOptions'); twice if there are two. I suspect that I have to change or add an option to refreshoptions but I can't seem to find the correct way to do it.

**Comment by wenzhixin** [comment]
```
$table.boostrapTable() // <-- init the table

$table.boostrapTable('refreshOptions') // <-- destroy the table and reinit
```

So you can see the table is retrieving data twice.
In our example, because we need to refresh the `classes` option, but In your case I think you can use this to solve the problem:
```
$table.boostrapTable({
  classes: ''
})
```

**Comment by aducom** [comment]
Thank you for your reply, I understand. I solved the issue by adding the options to data-classes.
