### ISSUE TITLE
js控制单元格内HTML标签css样式

### ISSUE THREAD

**Issue by from-wpj** [wenzhixin/bootstrap-table#4356]
假如我在formatter中return 一段字符串，字符串中含有html标签，例如：

![image](https://user-images.githubusercontent.com/32906455/57898717-d1ac5f00-788c-11e9-843a-61b96de4e33a.png)

那么我该如何用js控制 outer 中 p 的css样式呢？

**Comment by wenzhixin** [comment]
You can use CSS to define the style of `outer` (recommend), or write `style="..."` directly.

---

你可以直接使用 CSS 定义  `outer` 的样式（建议），或者直接写 `style="..."`。

**Comment by from-wpj** [comment]
> 您可以使用CSS来定义`outer`（推荐）的样式，或`style="..."`直接书写。
> 
> 你可以直接使用CSS定义`outer`的样式 （建议），或者直接写`style="..."`。

直接用css是可以改变它的样式，但是如果遇到非要用js处理的问题呢。
events 里面可以处理js，不过好像支持的事件只有click，假如我要用js 鼠标移入移出事件来控制它（p）的css却没有效果，也不知道有什么方法可以解决

**Comment by wenzhixin** [comment]
Example: http://jsfiddle.net/wenyi/e3nk137y/44380/

**Comment by from-wpj** [comment]
> Example: http://jsfiddle.net/wenyi/e3nk137y/44380/

这个链接在墙外也看不到它的真容！！！ ><

**Comment by wenzhixin** [comment]
```js
function descriptionFormatter(value, row, index) {
    return '<p>' + value + '</p>';
}

window.descriptionEvents = {
    'mouseover p': function (e, value, row, index) {
        $(e.currentTarget).css('background', 'red');
    },
    'mouseout p': function (e, value, row, index) {
        $(e.currentTarget).css('background', 'white');
    }
};
```

**Comment by from-wpj** [comment]
> ```js
> function descriptionFormatter(value, row, index) {
>     return '<p>' + value + '</p>';
> }
> 
> window.descriptionEvents = {
>     'mouseover p': function (e, value, row, index) {
>         $(e.currentTarget).css('background', 'red');
>     },
>     'mouseout p': function (e, value, row, index) {
>         $(e.currentTarget).css('background', 'white');
>     }
> };
> ```

原来onmouseover这种是无效的，我也刚发现一种方法，用它的onAll事件，
![image](https://user-images.githubusercontent.com/32906455/57902680-10e2ac00-789d-11e9-92e3-cbde88ecd2d7.png)

谢谢你的帮助。 （^-^）

**Comment by wenzhixin** [comment]
建议放在 `onPostBody` 中，`onAll` 是所有事件都会触发。

**Comment by from-wpj** [comment]
> 建议放在 `onPostBody` 中，`onAll` 是所有事件都会触发。

ok
