### ISSUE TITLE
filter-control on two tables

### ISSUE THREAD

**Issue by develover-vn** [wenzhixin/bootstrap-table#4359]
Hello,

I'm using BT v1.12.2 and filter-control extension v2.1.2.
I have two tables (difference ID, same data structure, same columns data-field) in one page.

My problem is when I use filter-control on these tables, just only the second table has value in select's option
Table 1:
![Screenshot (6)](https://user-images.githubusercontent.com/50762028/58067562-e9028980-7bb7-11e9-8109-e1475f765659.png)

Table 2:
![Screenshot (5)](https://user-images.githubusercontent.com/50762028/58067571-f4ee4b80-7bb7-11e9-92b4-eb6c983c8028.png)

How can I fix it without change data structure or data-field? Because I want to use one data structure for all of my tables.
Thank you!

**Comment by UtechtDustin** [comment]
Please provide us an example (jsfiddle).

**Comment by UtechtDustin** [comment]
I close this issue because we got no response from you within 7 days, if you still need help please provide us an example(jsfiddle).
