### ISSUE TITLE
Update table content the second time does not work

### ISSUE THREAD

**Issue by chokeholder** [wenzhixin/bootstrap-table#436]
I have a problem with my tables .. 

I have 2 tables on one page .. one page where i select an employee, triggers the other table to update its content by POST method to a PHP file. Looking at the result i can see that i get the correct reply from my webservice. The first time i select an employee the second table is updatede correctly, using the data property. But when i select a new employee after that (i still see the reply from my service is correct) it does not update the second table any more, the old data is still present. As if setting the data property the second time does not trigger an update of the table ??

Here's the interesting part of my function:

```js
$('#report-table').bootstrapTable('showLoading');				
$.ajax({
    type: "POST",
    url: "getReportsForEmployee.php",
    data: "id=" + row['id'],
    dataType:"json",
    success : function(data) 
    {	
        $('#report-table').bootstrapTable('hideLoading');
        $('#notification').hide();	
        $('#report-table').bootstrapTable({
            data: data
        });
    }
});
```

As mentioned i have reviewed the respons from my webservice, and it is OK. First time it updates the table, the second (third.. . . .. .) it doesnt... ?

**Comment by wenzhixin** [comment]
Hi, you can try to use `load` method:

```
$('#report-table').bootstrapTable('showLoading');               
$.ajax({
    type: "POST",
    url: "getReportsForEmployee.php",
    data: "id=" + row['id'],
    dataType:"json",
    success : function(data) 
    {   
        $('#report-table').bootstrapTable('hideLoading');
        $('#notification').hide();  
        $('#report-table').bootstrapTable('load', data);
    }
});
```

hope to help you.

**Comment by chokeholder** [comment]
Hi wenzhixin

Calling the load function did work, but i had to KEEP the part where i set the data property of my table, if not it does not work at all. As if the table is not initialized before i set the data property ? 

So now i set the data property first and after that i call the load function with my data. If i leave out the part where i set the data property, it does not show anything in my table. Please let me now if you want me to post more code to elaborate :) .. 

Another thing is (i could create this as a seperate question) is there a "clever" way of clearing the table before each load of new data. Or should i just create an empty array ?

**Comment by wenzhixin** [comment]
Yes, before you use the methods you need to init the table, like this:
```html
<table id="report-table" data-toggle="table">
</table>
```

and the second question, you are right just set an empty array to do that.

**Comment by chokeholder** [comment]
I did init the table as you mentioned above. Maybe the problem occur because the whole thing is loaded dynamically using ajax and the element (table) has not been initialized because of that ? .. If that is the case, I need to make some "clever" init functionality which is called only once.

**Comment by wenzhixin** [comment]
In the first time to init the table, you needn't to set `data-url` or `data` of the table, and it will be empty: http://jsfiddle.net/e3nk137y/348/, and then you use `load` method to update your second table.

Hope to help, close this issue.

**Comment by chokeholder** [comment]
that makes sense ... Thanks a lot for a great module and the quick response :)

**Comment by James8808** [comment]
遇到相似问题 终于找到解决办法！太感谢了!

**Comment by rahulcherry** [comment]
I have the same issue. Table data not getting changed on second submit.
data-toggle="table" not working.

**Comment by rahulcherry** [comment]
Ajax code:
`	$
			.ajax({
				type : "POST",
				contentType : "application/json",
				url : "http://localhost:8080/search",
				data : JSON.stringify(search),
				dataType : 'json',
				crossDomain: true,
				cache : false,
				timeout : 600000,
				success : function(data) {
					$('#logTable').show();
					$('#error').hide();
					$('#homeImage').hide();
					$('#clienti').bootstrapTable({
						data : data
					});

					console.log("SUCCESS : ", data);
					$("#btn-search").prop("disabled", false);

				},`

html
`				<table class="table table-striped table-bordered table-hover"
					id="clienti" data-url='#' data-search="true"
					data-show-refresh="false" data-show-toggle="true"
					data-show-pagination-switch="true" data-sort-order="asc"
					data-show-export="true" data-pagination="true">`

**Comment by svanniman2** [comment]
Glad I ran across this article.  Had same problem and solved with data-toggle="table".

Is there a way we can contribute to the documentation, thus future users don't have to hunt for solutions?
