### ISSUE TITLE
QueryParams 传递数组数据时，数据格式有误

### ISSUE THREAD

**Issue by litao11046** [wenzhixin/bootstrap-table#4360]
我使用多选的select作为查询条件控件，使用jquery获取这个控件的value值会得到一个数组对象。代码如下：
        function queryParamsfunc(params) {
            var temp = {   
            	type: $("select[name='type']").val(), //多选下拉框		
                search:params.searchText,	//搜索条件 
                size: params.pageSize,   //每页大小
                pagenum: params.pageNumber,  //当前页码
                sort: params.sortName,		//排序字段名
                sortOrder: params.sortOrder	//排序类型 asc升序 desc降序
            };
            return temp;
        };

这种情况下，Bootstrap table向后台发起的query string parameters为：(选择了3个选项：t1 t2 t3)
**type[]: t1
type[]: t2
type[]: t3**
search: 
size: 30
pagenum: 1
sortOrder: asc
_: 1558414223009

也就是说，会传递多个名字带[]后缀的数据，这种数据无法后端不方便获取到。

请问这个是不是bug

**Comment by wenzhixin** [comment]
可以使用字符串代替数组：`$("select[name='type']").val().join(',')`？

**Comment by litao11046** [comment]
> 可以使用字符串代替数组：`$("select[name='type']").val().join(',')`？

可以通过这种方式，但，如果bootstrap table能支持的话，就更好了

**Comment by wenzhixin** [comment]
这里本来就是自定义参数，要怎样的格式是你自己定义的。
