### ISSUE TITLE
How to specify column formatter programmatically, not as attribute

### ISSUE THREAD

**Issue by zorgoz** [wenzhixin/bootstrap-table#4361]
I am using RiotJs for my app. It makes possible to keep all functions local to their usage. I can specify on initialization `detialFormatter` for example as function/method directly and not only by name as an attribute in the table element. 
But I haven't found any way to do the same for the column. I have found only the `data-formatter` attribute which needs to contain the name of a global function.

Riotjs would simply assign a method with such a syntax, but unfortunately, it has no effect, probably because the code is looking for a function name and not a function:
`<th data-field="field" data-formatter={ myFormatter }>Column</th>`

Anyway, I would be glad if there were any vanilla JS or Jquery way to assign a function/method to a column as formatter instead of a function name.

**Comment by UtechtDustin** [comment]
You can add the formatter(and almost any attribute) to the [columns](https://examples.bootstrap-table.com/#options/table-columns.html).

**Comment by zorgoz** [comment]
@UtechtDustin Thank you, I have just found that and it is working. Although it is not exactly what I was looking for, as this way I have to specify all of the columns in that array, and not only the ones I want. Anyway, it is a usable solution for my needs.
