### ISSUE TITLE
Screenreader support pagination

### ISSUE THREAD

**Issue by KaptnDieter** [wenzhixin/bootstrap-table#4362]
Hi,
I use the table plugin together with Bootstrap 4 and the results are really impressive :)
But, websites have to be barrier-free these days and I have some stomach ache here when paginating tables.

The button to choose how many rows to show doesn't seem to be a real drop-down. At least Jaws (popular screenreader) can't explain the handling.

But more important is the control to jump between the paginated pages. A title attribute or aria-label would have to be added.
Currently Jaws reads the following: Link: 1, link: 2, Link: 3...
Much more helpful would be: Link: to page 1, Link: to page 2, Link: to page 3...

The whole thing is certainly only a small thing, and for someone who knows how to implement it easily.
I've already tried to adapt the code accordingly, but honestly I can't get an overview.

It would be cool if someone could help.

**Comment by wenzhixin** [comment]
Any pull request is welcome.
