### ISSUE TITLE
Usage without any framework

### ISSUE THREAD

**Issue by gurumark** [wenzhixin/bootstrap-table#4364]
Is there anyway to use library without including bootstrap js or css? These files are very heavy and I am not sure what percentage of the code included in these files are really used by bootstrap tables?
Thanks in advance.

**Comment by wenzhixin** [comment]
Here is the list of the integration with some of the most widely used CSS frameworks: https://bootstrap-table.com/themes/. You can use another CSS framework instead of bootstrap.

**Comment by gurumark** [comment]
How about no framework?
I see:
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" 
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" 

in this page. Will it work if I don't include these 2 files?

**Comment by UtechtDustin** [comment]
I also thin we should add a version without a requirement of a whole css framework.
What do you think about a basic css implementation for the bootstrap table ?
@wenzhixin @djhvscf

**Comment by UtechtDustin** [comment]
We could use the generator from [icomoon.io](https://icomoon.io/app/#/select) with the icon pack Feather (its MIT).
I will generate the css and the svgs for us, also it will generate a json with the select icons so we could reimport it to icomoon if we would add new icons.
What do you think @wenzhixin @djhvscf ?

**Comment by wenzhixin** [comment]
It’s great @UtechtDustin.

**Comment by djhvscf** [comment]
@UtechtDustin it is a very very good idea!! 🥇

**Comment by gurumark** [comment]
@UtechtDustin Thanks much!!

**Comment by pipiscrew** [comment]
@wenzhixin  @djhvscf @UtechtDustin 

+ http://fontello.com/

**Comment by pattishih** [comment]
One comment on this—the current CSS selectors for Bootstrap Table are a bit too selective, making it difficult to override property values that I would like to customize to my page without using !important or using just as many selectors in my custom CSS. These characters in the file can add up and increase the time for a page to load (particularly for slower mobile data connections).

An example:
`.bootstrap-table .fixed-table-container .table tbody tr.selected td {
  background-color: rgba(0, 0, 0, 0.075);
}`

This can probably be reduced to ".bootstrap-table .selected td"

**Comment by pipiscrew** [comment]
**Bootstrap 5.0 alpha arrives, sans jQuery**
https://www.infoworld.com/article/3563416/bootstrap-50-alpha-arrives-sans-jquery.html
