### ISSUE TITLE
Unable to export all table data with php server side pagination

### ISSUE THREAD

**Issue by somunath** [wenzhixin/bootstrap-table#4367]
I have using bootstrap-table.js version 1.11.1. Everything is working fine except the export parts. It only exports the visible rows in the page but it doesn't exports "all" and "selected" as well.

Below is my php server side code:

```
<?php
	$servername = "localhost";
	$username = "root";
	$password = "";
	$dbname = "dbname";

	// Create connection
	$conn = new mysqli($servername, $username, $password, $dbname);

	// Check connection
	if ($conn->connect_error) {
	    die("Connection failed: " . $conn->connect_error);
	}else{
		$a_json = array();
	    $temp = array();
	    $a_json_row = array();

	    if (isset($_GET['search'])) {
	        $WHERE = ' WHERE first_name LIKE "%'.$_GET['search'].'%" ';
	    } else {
	        $WHERE = NULL;
	    }


		$sql = "SELECT labour_id, first_name, last_name FROM labour_details ".$WHERE." ORDER BY labour_id LIMIT ".$_GET['offset'].",".$_GET['limit']."";
		$result = $conn->query($sql);
		if ($result->num_rows > 0) {
		    while($row = $result->fetch_assoc()) {
		    	$a_json_row["Labour_Id"] = $row["labour_id"];
        		$a_json_row["First_Name"] = $row["first_name"];
        		$a_json_row["Last_Name"] = $row["last_name"];
        		array_push($temp, $a_json_row);
		    }
		} else {
		    echo "0 results";
		}

		$sql2 = "SELECT count(*) as total FROM labour_details ".$WHERE."";
		$result2 = $conn->query($sql2);
		$data = $result2->fetch_assoc();
		$conn->close();


	    echo json_encode(array(
		    'total' => $data['total'], // total numbers
		    'rows' => $temp
		));
	}
```
	

And here is the html table part:

```
<table id="table" data-toggle="table" data-url="getdata.php" data-side-pagination="server" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true" data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                 <thead>
                 <tr>
                  <th data-field="state" data-checkbox="true"></th>
                  <th data-field="Labour_Id">Labour ID</th>
                   <th data-field="First_Name" data-editable="true">First Name</th>
                   <th data-field="Last_Name" data-editable="true">Last Name</th>
                                               
                  </tr>
                  </thead>
</table>
```

And in the bootstrap-table.js file i have set the line 311 to server as

```
sidePagination: 'server', // client or server
```

Please, help me solve the problem. I just need the export part to work well as per my need.

**Comment by wenzhixin** [comment]
Transferred this issue, @somunath please test it in the latest version.
In our example: https://examples.bootstrap-table.com/#extensions/export.html, it works well.

**Comment by somunath** [comment]
Could You Please tell me which are the js and css files i need to update

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/#welcome.html#view-source

**Comment by UtechtDustin** [comment]
All js and css files your currently using from the bootstrap-table :-)

**Comment by somunath** [comment]
OK.. thanks. Let me try first. will respond back. And Thank you both so much for your help.

**Comment by wenzhixin** [comment]
You need to return all data without `offset` and `limit` params, for example, https://examples.wenzhixin.net.cn/examples/bootstrap_table/data.

**Comment by somunath** [comment]
Under such case my above php code isn't going to work right?

**Comment by somunath** [comment]
The data-url always sends offset and limit to the server script. How do i prevent it from sending offset and limit in case export event is clicked or is there a way to send addition parameter when export is clicked.

**Comment by somunath** [comment]
Could you plz tell me how to send an additional parameter to data-url if export is invoked?

**Comment by UtechtDustin** [comment]
I guess you can use the [queryParams](https://bootstrap-table.com/docs/api/table-options/#queryparams) option.

Btw. we have a [documentation](https://bootstrap-table.com/docs/getting-started/introduction/) (the link above can be found easily by searching in the documentation).

**Comment by somunath** [comment]
Could you please provide me a sample code on how to send an additional parameter when and only when the excel or csv export is invoked

**Comment by UtechtDustin** [comment]
There is a sample code on the documentation, just click on the `</>` on the example page.
I don think its  currently possible to send it only if th export event is invoked.
But there should no problem to send it on every event, just ignore it on the server side.

**Comment by somunath** [comment]
Hello, I want to try this example given here https://examples.bootstrap-table.com/#issues/3830.html#view-source. I can't get it to work. Please tell me what are the additional js and css files in need.   

as of now i have tried as bellow:
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Dashboard v.1.0 | Adminpro - Admin Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.css@7.1.0/themes/reset-min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.css@7.1.0/themes/algolia-min.css">
<link href="docs.min.css" rel="stylesheet">
  <link href="index.css?v=80" rel="stylesheet">

<link href="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.css" rel="stylesheet">

<script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.14.2/dist/extensions/export/bootstrap-table-export.min.js"></script>
</head>
<body>

<table
  id="table"
  data-height="460"
  data-url="https://examples.wenzhixin.net.cn/examples/bootstrap_table/data"
  data-search="true"
  data-pagination="true"
  data-side-pagination="server"
  data-show-export="true"
  data-export-data-type="all"
  data-query-params="queryParams">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
</table>

<script>
  var $table = $('#table')

  $(function() {
    $table.bootstrapTable()
  })

  function queryParams(params) {
    var options = $table.bootstrapTable('getOptions')
    if (!options.pagination) {
      params.limit = options.totalRows
    }
    return params
  }
</script>
 <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <script>$.browser = {}</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-hashchange/1.3/jquery.ba-hashchange.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/algoliasearch@3.32.0/dist/algoliasearchLite.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@3.0.0/dist/instantsearch.production.min.js"></script>
  <script src="docs.min.js"></script>
  <script src="index.js?v=80"></script>
</body>
</html>

**Comment by UtechtDustin** [comment]
You can see the required js/css files in the example.
If you need help please provide us an example(jsfiddle!) of your not working test instead or pasting your code without any formatting.

**Comment by somunath** [comment]
Thanks guys for your help.  By the way i have solved the problem. Now its working fine. I have integrated it in laravel. Thank you again.

**Comment by UtechtDustin** [comment]
Your welcome!

**Comment by somunath** [comment]
The bootstrap-table library is awesome. The author's work is highly appreciated
