### ISSUE TITLE
json text/event-stream

### ISSUE THREAD

**Issue by lafual** [wenzhixin/bootstrap-table#4370]
When using `data-url` on a source which has media type `application/json` my table is correctly built.

When the media type is `text/event-stream` containing JSON objects, I get `Loading, please wait ...` . The stream contains the base data, followed by updates in real-time, which I would intend to use to update individual cells depending on a primary key. I was hoping that there would be some _magic_ that would identify an existing row and at least replace it. However, I assume that Bootstrap Table (using `data-url`) is waiting for an end-of-stream and isn't designed to deal with updating row.

Using plain Bootstrap and JQuery (using `EventSource`) I can get the incoming data and update the relevant cells.

How would I do this using Bootstrap Table? (The API on the official home page does not give code-snippets and the examples, when opened in Chrome Developer tools do really clarify).

**Comment by wenzhixin** [comment]
I think you can use the `append` method to append the data to the table after your data return.

Docs: https://bootstrap-table.com/docs/api/methods/#append
Example: https://examples.bootstrap-table.com/index.html#methods/append.html

**Comment by lafual** [comment]
Thanks for the quick response. How do I get around the `Loading, please wait..` . I assume that using `data-url` is not suitable in this scenario.

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by lafual** [comment]
I see what I was missing. I needed to remove the `data-url` attribute, then have my JQuery call the `append` or `updateRow` where necessary.

So just to confirm; is `data-url` designed to expect a finite JSON array (i.e. not an open-end `text/event-stream`)?

**Comment by UtechtDustin** [comment]
Yes, currently the bootstrap-table cant handle streams (`text/event-stream`).
