### ISSUE TITLE
Feature request: Broader support for data- attribute evaluation.

### ISSUE THREAD

**Issue by patrickguenther** [wenzhixin/bootstrap-table#4371]
The use case for this is having the data-ajax function call an object method for instance. The naive approach, is just using: `data-ajax="myObject.request"` which will of course fail, if the request method wants to access myObject's fields using the `this` operator.
Another use case would be to supply an arrow function `data-ajax="(params) => myObject.request(params)"`, which also would fail, because the calculateObjectValue function tries to access `window['(params) => myObject']['request(params']`.

The first case could be implemented essentially by using a smarter implementation of `Utils.calculateObjectValue`: While going through the for-loop, one could also save the second to last object, and bind the last function to the second to last one before returning.
If the arrow function or inline function declaration should also be supported, one could use the trick, that is essentially used in the Knockoutjs library all over the place, by instantiating a new Function object with the attribute value as source and calling it immediately:
`(new Function('return ' + <sourceString> + ';'))()` (I might be wrong about the exact syntax in that case).

I could submit a pull request, if you think, that would be useful. Or are there any issues ahead so this basically can't be done this way?

**Comment by wenzhixin** [comment]
I think can support this case `data-ajax="myObject.request"`:

```js
window.myObject = {
  request: function () {}
}
```

But the arrow function doesn't support old browser.

**Comment by patrickguenther** [comment]
@wenzhixin: Yes, that case is already supported. Now, my argument is, that if `request` tries to access some method or property of myObject, this will fail:

```javascript
class MyTable {
  constructor() {
    this.onLoadHandler = [];
  }

  onLoad(f) {
    this.onLoadHandler.push(f);
  }

  request(params) {
    // ... do the request, maybe set some more headers, based on constructor parameters
    for(var h of this.onLoadHandler) {
      h('whatever');
    }
    // ...
  }
}
var myTable = new MyTable()
```
I'm using the class keyword here for brevity, but some people (like me :) ) already did object oriented programming in javascript long before the class keyword was a thing.
```
data-ajax="myTable.request"
```
Now this will of course fail, because `this` inside the request method is just the window object. This is expected by seasoned javascript developers, but might stump others. The way how you get around this in knockoutjs for example, is to just use an arrow function or an inline function inside the data attribute:
```
data-ajax="params => myTable.request(params)"
```
or for backwards compatibility:
```
data-ajax="function(params) { myTable.request(params); }"
```
Now, if you say: "The knockoutjs way is just a glorified eval", you are actually right about it. If someone still wants to support this however, the next best solution is to just bind the last object in a dot separated path to the second to last object, or for backwards compatibility again, return a function that calls the last method as a method of the second to last property.

```javascript
var path = name.split('.');
var secondToLast, current = window;
for(var i = 0; i != path.length; ++i) {
  secondToLast = current;
  current = current[path[i]];
}
return current.bind(secondToLast);
// or: return function() {current.apply(secondToLast, arguments);};
// Maybe even rewrap arguments into an actual array, you get my point.
```

**Comment by UtechtDustin** [comment]
Could you provide us an example for that case  ?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days, if you still want that feature, please provide us an example(jsfiddle) and reopen the issue.
