### ISSUE TITLE
Refresh table method does not work in IE 11 (Windows 7/10)

### ISSUE THREAD

**Issue by cody-at-centare** [wenzhixin/bootstrap-table#4372]
After adding a record and calling the bootstrap-table `refresh` method, bootstrap-table is not updating with latest records in IE11 in Windows 7 and 10.

Here is the Javascript being called after a new record is added to the back-end.

`$(".bootstrap-table table").bootstrapTable("refresh");`

[This issue](https://github.com/wenzhixin/bootstrap-table/issues/1102) seems to be the exact same scenario but when setting the `data-cache` attribute to `false` on the table, the error persists.

**Comment by UtechtDustin** [comment]
Could you provide us an example(jsfiddle)?
