### ISSUE TITLE
Multi Column

### ISSUE THREAD

**Issue by ArturVidal** [wenzhixin/bootstrap-table#4373]
![img](https://user-images.githubusercontent.com/15653697/58649529-3db6aa80-8304-11e9-8f4d-949228025f73.png)
i can´t have 3 filters in the same time?

when I do one search, and when I go to the other it erases the first one

**Comment by UtechtDustin** [comment]
Please provide an example of your problem in any issue!
You can filter by multiple stuff with the [filterBy](https://bootstrap-table.com/docs/api/methods/#filterby) method.

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days, if you still need help please provide us an example (jsfiddle) and reopen the issue.
