### ISSUE TITLE
filtering does not work json sub-object

### ISSUE THREAD

**Issue by lafual** [wenzhixin/bootstrap-table#4375]
Hi,

If my `data-field` is a top level item e.g. `<th data-field='x'>` the filtering works. If my item happens to be a sub-object (for example) `<th data-field='x.y'>` filtering does **not** work.

I have tried it by loading by Ajax and using `append` and also using `data-url`.

**Comment by UtechtDustin** [comment]
Could you provide us an example(jsfiddle) for that ?

**Comment by lafual** [comment]
Thanks for the quick response.
It will take me a few hours. I have never added code to JSFiddle before.
While I have your attention; what is the best way to read the examples on the official website? We get a demo output, but no source. Should I go into 'Developer Mode' and read from there? I ask, because by doing it this way, it is very unclear what the original HTML would have looked like, or where the JS is being called from.

**Comment by UtechtDustin** [comment]
Its easy to create a example on JsFiddle, let you time but we need an example to see your problem in realtime.

There is source code on the example pages, just click on the `</>` Text (next to the title).
Fot the Welcome Example the source url would be https://examples.bootstrap-table.com/#view-source.
@wenzhixin we should implement the source code button in a other way, i have read that question often.

**Comment by lafual** [comment]
doh - I can't believe I didn't try that !  (-- insert icon here for slapping my head for being stupid)

FYI - `<table data-search='true'>` does work!

**Comment by UtechtDustin** [comment]
As you can see in the [example](https://examples.bootstrap-table.com/index.html#options/table-search.html) `data-search` works well.

So we need an example from you :-)

**Comment by lafual** [comment]
[https://jsfiddle.net/lafual/d7a8pLyg/14/](https://jsfiddle.net/lafual/d7a8pLyg/14/)

Here is an example. I coped it from official page's example, but just sub-classed `name` to be within `x`.

**Comment by wenzhixin** [comment]
> We get a demo output, but no source.

Thanks for the feedback. Updated `View Source`(`View Example`) to use `corner-ribbon` instead: https://examples.bootstrap-table.com.

**Comment by lafual** [comment]
@wenzhixin Nice! Thanks :)

**Comment by lafual** [comment]
The same issue of sub-objects also occurs for the tag `<table data-unique-id="">` . If the object is a top level, I get `<tr data-unique-id="">`. If the object in `<table>` is defined as a 2nd or lower level, the `data-unique-id` is not applied to `<tr>`. 

I have update the JSFiddle (see version 21).

**Comment by UtechtDustin** [comment]
@wenzhixin much better, thanks a lot !
