### ISSUE TITLE
Format cell depending on previous value

### ISSUE THREAD

**Issue by lafual** [wenzhixin/bootstrap-table#4377]
How can I discover the previous value?

I want to do something like;

```
function myFormatter(value, row, index, field) {
  oldValue = // ????
  if (oldValue < value) {
     return ("<div style='color:green;'>" + value + "</div">);
 } else ...
}
```

**Comment by wenzhixin** [comment]
What the previous value mean?

**Comment by lafual** [comment]
I assume that this function is called when the cell is created or updated and that “value” is the new value of the cell. However, i would like to know the previous value of the cell in order to determine the format. For example, if the cell’s value is increased, it will be formatted green and if decreased, formatted to red.

**Comment by UtechtDustin** [comment]
Just fetch the row data (getData or getRowByUniqueId) and after that call  the updateCell method.

**Comment by lafual** [comment]
I could not do this in the `formatter` as the `get` already has the newer data.

So I removed the `formatter` and did as you said; in the JS code which calls `updateByCellId`, I first call `getRowByUniqueId` - remove the previous formatting (I had a `<span>` with icon), then compared the data, the called `updateByCellId` with the corrected `<span>` and it works.
