### ISSUE TITLE
Filter-control does not filter null value.

### ISSUE THREAD

**Issue by 2000calories** [wenzhixin/bootstrap-table#4378]
Filter-control does not filter null value.

for example, a column with three records, [null,1,2], when enter 1 in the filter input field, both [null, 1] are returned.

https://jsfiddle.net/b9er6hfq/3/

![image](https://user-images.githubusercontent.com/25191098/58849353-98615500-86bc-11e9-970d-02868685faac.png)

**Comment by UtechtDustin** [comment]
Thank you for the bug report !

Same for `undefined`.
