### ISSUE TITLE
Pagination/totalRows not updated on hideRow

### ISSUE THREAD

**Issue by mshoestrng** [wenzhixin/bootstrap-table#4379]
I have a Bootstrap-Table with data passed in as JS object. On certain occasions I need to hide some rows via hideRow.

However, when the rows are hidden, the pagination info (X) in the footer is not updated: "Showing 1 to X of X rows".

See Fiddle at https://jsfiddle.net/trxpy84q/2/

After hiding one row the pagination in the footer should be updated to "Showing 1 to **1** of **1** rows".

Why is the pagination data not updated?

Environment: Chrome Version 74.0.3729.169 (Offizieller Build) (64-Bit) on Windows 10 Pro.

**Comment by UtechtDustin** [comment]
Thank you for the bug report, we will check/fix that bug !

**Comment by mshoestrng** [comment]
In which release will this fix be included?

**Comment by djhvscf** [comment]
Next release 1.15.0
