### ISSUE TITLE
Mixed content HTTPS error

### ISSUE THREAD

**Issue by radiantone** [wenzhixin/bootstrap-table#4393]
Hi,
  I'm using 1.12.1 version of bootstrap-table. Can't upgrade for now.

On our https site. ONe of our tables is using relative path "/abc/xyz" yet we see a console error (in chrome) showing full URL to the resource but with http, not https. Since we use relative URL paths inside our tables for remote data, this seems very unexpected.

**Comment by UtechtDustin** [comment]
First of all, why you cant use the newest version of the bootstrap table ?
We cant support each version of the table.

Also need an example(jsfiddle) to help you.

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7days, if you still need help please reopen the issue.
