### ISSUE TITLE
How to show below data (format) from database?

### ISSUE THREAD

**Issue by ravi-ku** [wenzhixin/bootstrap-table#4409]
![image](https://user-images.githubusercontent.com/11146609/59269134-eef60280-8c6b-11e9-9740-9f776607ba5b.png)

Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by UtechtDustin** [comment]
Our example [From Url](https://examples.bootstrap-table.com/#welcomes/from-url.html) with the [json](https://examples.bootstrap-table.com/json/data1.json) should show you how to configure it.
So you dont found the example ord did i miss something ?

**Comment by wenzhixin** [comment]
Refs #3977 and 1178

**Comment by UtechtDustin** [comment]
I close this issue because we got not response from you, if you still need help please reopen the issue.
