### ISSUE TITLE
Display row number

### ISSUE THREAD

**Issue by berdesos** [wenzhixin/bootstrap-table#441]
Any idea on how to display static incremental row numbers (not ids in json, generally not included in json)? I need to have each table-element's row easily recognisable by a static incremental number. Thanks

**Comment by DominikAngerer** [comment]
Here is an simple jsfiddle for you: http://jsfiddle.net/DominikAngerer/yx275pyd/2/

Here for you again not as fiddle:
```html
<table data-toggle="table"
       data-url="/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data1/">
    <thead>
    <tr>
        <th data-formatter="runningFormatter">Index</th>
        <th data-field="name">Name</th>
        <th data-field="stargazers_count">Stars</th>
        <th data-field="forks_count">Forks</th>
        <th data-field="description">Description</th>
    </tr>
    </thead>
</table>

```
```javascript
function runningFormatter(value, row, index) {
    return index;
}
```

**Comment by DominikAngerer** [comment]
Added PullRequest so this can be found in the documentation.

**Comment by berdesos** [comment]
That's perfect! and this is an adjustment of the function for counting from 1...

<script>
function runningFormatter(value, row, index) {
    index++; {
        return index;
    }
}
</script>

**Comment by DominikAngerer** [comment]
i would do that like this:
 
```javascript
function runningFormatter(value, row, index) {
    return 1+index;
}
```

So you don't really update the index - just to be safe ;)

**Comment by berdesos** [comment]
thats better. thanks

**Comment by jorgecarleitao** [comment]
Note that this value is not the "rank" of a given row and a given ordering because if you "search" the rows, the first value will be the first after the search, not before the search.

**Comment by wenzhixin** [comment]
@jorgecarleitao, You can handle your response data, for example:
```
responseHandler: function (data) {
    $.each(res, function (i, row) {
        row.index = i + 1;
    });
    return res;
}
```
and then, use in the field: `<th data-field="index">`.

**Comment by zeeshanyshaikh** [comment]
How to get index increment on next page as well. If clicked on next page the counter (index) set to 0.

**Comment by wenzhixin** [comment]
You can use `bootstrapTable('getOptions')` to get the page information.

**Comment by enayet-repo** [comment]
You can use the following -

this.runningFormatter = function (value, row, index) {
            var tableOptions = $table.bootstrapTable('getOptions');
            return ((tableOptions.pageNumber-1) * tableOptions.pageSize)+(1 + index);
        };

**Comment by lio590** [comment]
Hi Enayet thx for the snippet however it seems that we can't get the row "id"  when we call $table.bootstrapTable('getSelections') any clue on what's happening ?

**Comment by Alperen2558** [comment]
asd

**Comment by jinbatsu** [comment]
> 
> 
> Hi Enayet thx for the snippet however it seems that we can't get the row "id" when we call $table.bootstrapTable('getSelections') any clue on what's happening ?

just add your table id element before, like this
```
this.runningFormatter = function (value, row, index) {
        $table = $('#tablegrid'); // your tablegrid id
        var tableOptions = $table.bootstrapTable('getOptions');
        return ((tableOptions.pageNumber-1) * tableOptions.pageSize)+(1 + index);
   };
```
