### ISSUE TITLE
Tooltip should be in the input box

### ISSUE THREAD

**Issue by zaidmir5** [wenzhixin/bootstrap-table#4410]
![image](https://user-images.githubusercontent.com/48056293/59344819-70ad6500-8d2c-11e9-987b-c4b14d299bfb.png)
Tooltip should be there in the input box
Code is:
<input type="text" id="advancedValue" placeholder="Advanced Editor Content" class="customForm" style="width: 320px; margin-right:15px;" readonly>
![image](https://user-images.githubusercontent.com/48056293/59345191-37c1c000-8d2d-11e9-8cae-41a415cbd03c.png)

**Comment by zaidmir5** [comment]
![image](https://user-images.githubusercontent.com/48056293/59345070-fcbf8c80-8d2c-11e9-9a63-c21c67b26b27.png)
<input type="text" id="advancedValue" placeholder="Advanced Editor Content" class="customForm" style="width: 320px; margin-right:15px;" readonly>

**Comment by UtechtDustin** [comment]
Please provide us an example(jsfiddle) and explain what do you mean, i dont understand it with your screenshots.

**Comment by UtechtDustin** [comment]
I close this issue because we got not response from you, if you still need help please reopen the issue and provide us an example (with our [editor](https://live.bootstrap-table.com/)).
