### ISSUE TITLE
Error on export

### ISSUE THREAD

**Issue by runnerer** [wenzhixin/bootstrap-table#4411]
Hello,

Whe you export data from table you get:

> bootstrap-table-export.min.js:10 Uncaught TypeError: a is not a function
>     at Object.onAfterSaveToFile (bootstrap-table-export.min.js:10)
>     at tableExport.min.js:40

**Found at the Welcome example.**

Best Regards!

**Comment by UtechtDustin** [comment]
Thanks for your report, the bug is already known and fixed in the develop Branch and will be fixed for the public in the next release.
