### ISSUE TITLE
Styling the toolbar elements

### ISSUE THREAD

**Issue by runnerer** [wenzhixin/bootstrap-table#4415]
Hello,

Is there a way to style the toolbar elements or change them?
For example change the export button to custom one, adding style to the search input(like background-image and etc.), also is there a way to change/style the pagination buttons?
I searched in the js file but didn't found where these elements html is defined.

Thanks for your help.
Keep up the good work!

**Comment by UtechtDustin** [comment]
You can change the icons (see [documentation](icons)), also you can change some html (just checkout the javascript files for the [themes](https://github.com/wenzhixin/bootstrap-table/tree/develop/src/themes).
The last option is to overwrite the css with your own css.
