### ISSUE TITLE
How to set a Search string by a data attribute?

### ISSUE THREAD

**Issue by maxvergelli** [wenzhixin/bootstrap-table#442]
it's possible to pass pageSize, pageNumber, sortName, sortOrder as data attribute to the html table but there is not a "data-search-text" attribute to set a search string in the input text.

Exists only a "data-search" attribute to enable the search input, but this doesn't valorize it.

**Comment by wenzhixin** [comment]
Now it is not support set by data attribute, you can via JavaScript:
```
bootstrapTable({
    formatSearch: function () {
        return 'Your search string';
    }
});
```

**Comment by djhvscf** [comment]
@wenzhixin can we close this issue?
