### ISSUE TITLE
1.11.1升到到1.14.2出现的问题，表格导出一直报错

### ISSUE THREAD

**Issue by wanna0222** [wenzhixin/bootstrap-table#4422]
bootstrap-table.js:86 Uncaught TypeError: Cannot convert undefined or null to object

 at Function.from (<anonymous>)
    at _toConsumableArray (bootstrap-table.js:86)
    at Object.calculateObjectValue (bootstrap-table.js:364)
    at bootstrap-table.js:2241
    at Array.forEach (<anonymous>)
    at BootstrapTable.initBody (bootstrap-table.js:2234)
    at BootstrapTable.init (bootstrap-table.js:810)
    at new BootstrapTable (bootstrap-table.js:794)
    at HTMLTableElement.<anonymous> (bootstrap-table.js:3709)
    at Function.each (jquery.js?id=0b4d15c99133a79c2443:444)

**Comment by UtechtDustin** [comment]
Please translate it into english and provide us an example(jsfiddle) .
@wenzhixin

**Comment by wanna0222** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>表格导出</title>
    
    <script src="../../chajian/jquery/jquery.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.14.7/umd/popper.min.js"></script>
    
    <link href="../../chajian/bootstrap/css/bootstrap.css" rel="stylesheet">
    <script src="../../chajian/bootstrap/js/bootstrap.js"></script>
    
    
    <link rel="stylesheet" href="../../chajian/font-awesome//css/font-awesome.min.css">
    
    
     
     <link href="https://cdn.bootcss.com/bootstrap-table/1.11.1/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/bootstrap-table/1.11.1/bootstrap-table.min.js"></script>
    <script src="../../chajian/bootstrap-table/js/bootstrap-table-zh-CN.js"></script>
    
    
    <script src="https://cdn.bootcss.com/bootstrap-table/1.11.1/extensions/export/bootstrap-table-export.min.js"></script>
    <script src="../../chajian/bootstrap-table/js/tableExport.js"></script>
  
</head>
<body>
<div class="panel-body" style="padding-bottom:0px;">
   

    
    <table id="tb_departments">
    </table>
    <script>
        var $table;
        $(function () {
           

            $.getJSON('../../resource/data1.json', function (result) {
                initBootstrapTable(result);
            });


            function initBootstrapTable(jsonArray) {
                $table = $('#tb_departments').bootstrapTable({
                    data: jsonArray,
                //    url: '../../resource/data1.json',
                    striped: true,                      //是否显示行间隔色
                    cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
                    pagination: true,                   //是否显示分页（*）
                    sortable: true,                     //是否启用排序
                    search: true,
                    sortOrder: "asc",                   //排序方式
                    sidePagination: "client",           //分页方式：client客户端分页，server服务端分页（*）
                    pageNumber: 1,                       //初始化加载第一页，默认第一页
                    pageSize: 10,                       //每页的记录行数（*）
                    pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
                    clickToSelect: true,
                    showToggle: true,//显示切换按钮来切换列表/卡片视图
                    showColumns: true,//显示所有列
                    showRefresh: true,//显示刷新按钮
                    pagination: true,//显示分页
                    showExport: true,                     //是否显示导出
                    exportDataType: "all",              //basic', 'all', 'selected'.
                    exportTypes: ['excel'],
                    exportOptions:{
                        ignoreColumn: [0]
                    },
                    rowStyle: function (row, index) {
                        var strclass = "";
                        // console.log(row);
                        if (row.outWeight === undefined) {
                            strclass = 'info';//还有一个active
                        }
                        return {classes: strclass}
                    },
                    columns: [
                [
                    {
                        field: 'checkbox',
                        title: '',
                        align: "center",
                        width: "3%",
                        checkbox: true,
                      
                    }, {
                        field: "totalcapacity",
                        title: "总容量",
                        align: "center",
                        width: "6%",
                        editable: {
                            mode: 'inline',
                        },
                        // formatter: formatterCell

                    },  {
                        field: "usedcapacity",
                        title: "已用容量",
                        align: "center",
                        width: "6%",
                        editable: {
                            mode: 'inline'
                        }
                    }, {
                        field: "usedcapacitypercent",
                        title: "已用百分比",
                        align: "center",
                        width: "10%",
                        sortable: true,
                        formatter:persentFormatter
                       
                    },{
                        field: "department",    
                        title: "所属部门",
                        align: "center",
                        width: "8%",
                        editable: {
                            type: 'select',//下拉框 
                            emptytext:"选择部门",
                            source: [{ value: 1, text: '行政部',selected:'true' }, { value: 2, text: '开发部' }, { value: 3, text: '运维部' }],
                            valueField: 'id',
                            onSelect: function (val, rec) {
                                console.log(val, rec);
                            }
                        },
                    }, {
                        field: "confstate",
                        title: "状态",
                        width:"5%",
                        align: "center",
                        // width: "200px",
                        formatter:stateFormatter,
                        visible:false
                    }, {
                        field: "detail",
                        width: "32%",
                        title: "详情",
                        sortable: true,
                        visible:false
                    },{
                        field: "time",
                        title: "时间",
                        align: "center",
                        sortable: true,
                        width: "15%",
                        editable: {
                            // type:'date',//日期
                            type: 'text',//日期
                            required: true,
                            click: function () {
                            }
                        },
                    }, 
                    {
                        field: 'editer',
                        title: '操作',
                        width: "15%",
                        formatter:actionFormatter,
                        events:'confirmEvents'
                    }

                ]]
                })
            }
        });
    </script>
    <script>
     // 状态字段格式化
     function stateFormatter(value){
            var result = '';
            switch(value){
                case 'updating':
                result+='<div style="display:none;">updating</div><font color="orange" ><i class="fa fa-spinner fa-spin" title="正在更新"></i></font>'
                break;
                case 'success':
                result+='<div style="display:none;">success</div><font color="green" ><i class="fa fa-check" title="收集成功"></i></font>'
                break;
                case 'failed':
                result+='<div style="display:none;">failed</div><font color="red" ><i class="fa fa-times" title="收集失败"></i></font>'
                break;
                case 'stopped':
                result+='<div style="display:none;">stopped</div><font color="orange" ><i class="fa fa-stop" title="禁用收集"></i></font>'
                break;
                default:
                result+='<div style="display:none;">unknown</div><font color="orange"><i class="fa fa-question" title="未知状态"></i></font>'
            }
            return result;
        }

        function persentFormatter(value,row,index,filed){
                            var result = ''

                            var percent = (Math.round(row.usedcapacity/row.totalcapacity*10000)/100).toFixed(2)+'%';
                            var currentWidth = (Math.round(row.usedcapacity/row.totalcapacity*10000)/100).toFixed(2);
                           
                            if(currentWidth>90){
                                result+='<span>'+percent+'</span><div style="width:100px;height:6px;border:1px solid #f1f1f1;background-color:#fff;border-radius:3px"><span class="statebar" style="width:'+currentWidth+'px;height:5px;background-color:orange;display:block;border-radius:2px"></span></div>'
                            }else if(currentWidth<90&&currentWidth>80){
                                result+='<span>'+percent+'</span><div style="width:100px;height:6px;border:1px solid #f1f1f1;background-color:#fff;border-radius:3px"><span class="statebar" style="width:'+currentWidth+'px;height:5px;background-color:#7266BA;display:block;border-radius:2px"></span></div>'
                            }else if(currentWidth<80){
                                result+='<span>'+percent+'</span><div style="width:100px;height:6px;border:1px solid #f1f1f1;background-color: #fff;border-radius:3px"><span class="statebar" style="width:'+currentWidth+'px;height:5px;background-color:#37BC9B;display:block;border-radius:2px"></span></div>'
                            }
                   
                            return  result;

                        }
                         //操作栏的格式化
        function actionFormatter(value, row, index) {
                    var id = value;
                    var result = "";
                    // result += "&nbsp;&nbsp;<a href='javascript:;' class='btn btn-primary btn-xs' onclick=\"EditViewById('" + id + "', view='view')\" title='查看'><span class='glyphicon glyphicon-search'></span></a>";
                    result += '&nbsp;&nbsp;<a class="btn btn-warning btn-xs" href="#" mce_href="#" title="编辑" value="编辑" data-row=\'' + JSON.stringify(row) + '\'  onclick=\'openMode("update",this)\'><span class="glyphicon glyphicon-pencil"></span></a>';
                    result += "&nbsp;&nbsp<a href='javascript:;' value='删除' class='btn btn-primary btn-xs' onclick=\"DeleteByIds()\" title='删除'><span class='glyphicon glyphicon-remove'></span></a>";

                    return result;
                }

            /*加载数据*/
            $('#loadData').click(function () {
                        var data = [
                            {"age": "17",
                            "gender": "男",
                            "id": "1",
                            "name": "pride",
                            "time": "2017-08-09 10:33:57"
                            },
                            {
                            "age": "16",
                            "gender": "女",
                            "id": "1",
                            "name": "pride",
                            "time": "2018-08-09 10:33:57"
                            }]
                        $('#reportTable').bootstrapTable('load', data);
                    });
    </script>
</div>
</body>
</html>

**Comment by UtechtDustin** [comment]
@wanna0222 Please use [jsfiddle](https://jsfiddle.net/) to create an example for us.

**Comment by wenzhixin** [comment]
@wanna0222 Please use [online editor](https://live.bootstrap-table.com/) to create an example for us.

**Comment by wenzhixin** [comment]
This line has error:
```
events:'confirmEvents'
```

Remove and it works well: https://live.bootstrap-table.com/code/wenzhixin/7

**Comment by UtechtDustin** [comment]
I close this issue because we got no response from you within 7 days, also @wenzhixin posted the solution.   
If you still need help with that, please reopen the issue and provide us an example.
