### ISSUE TITLE
for in 遍历数组

### ISSUE THREAD

**Issue by hzdjulytech** [wenzhixin/bootstrap-table#4423]
使用 for in 遍历数组 会导致 Array.prototype 拓展方法无法添加 
一旦存在拓展 for in 循环无法得到正确结果

**Comment by UtechtDustin** [comment]
Please give us also an english translation.
@wenzhixin

**Comment by wenzhixin** [comment]
@hzdjulytech Please use [Online Editor](https://live.bootstrap-table.com/) to create an example for us.

I don't know what problem do you have.

**Comment by hzdjulytech** [comment]
Array.prototype.test=function(){
}
则bootstrap-table 内部 采用for-in 遍历 数组的地方必定出错 例如 
220行附近
var props = field.split('.');
        for (var p in props) {
            value = value[props[p]];
        }

**Comment by wenzhixin** [comment]
是因为扩展了 Array 的属性？

**Comment by hzdjulytech** [comment]
对 只要有人拓展了 Array 就会出错

**Comment by wenzhixin** [comment]
测试了下，没有出现你说的问题呢：https://live.bootstrap-table.com/code/wenzhixin/4

**Comment by hzdjulytech** [comment]
那是因为你的 field 没有 a.b 这种写法 没有触发到 for- in 循环 只看着一段就知道了
我搜了一下里面不止220行一处用了for in 每个地方的触发条件不一样 没细看 
220行是我踩了一次坑发现的
   Array.prototype.test=function(){ }
  var field="a.z"
  var value={a:{z:"x"}};
  var props = field.split('.');
	for (var p in props) {
	value = value[props[p]];
	}
	alert(value)

**Comment by wenzhixin** [comment]
你看我发的例子 field 是有 a.b 这种的，你用的不是最新版本吧？

**Comment by hzdjulytech** [comment]
不是 那就应该是后来的版本改了  我搜了下没人提相同的问题 1

**Comment by wenzhixin** [comment]
看下你是用什么版本

**Comment by hzdjulytech** [comment]
比较老了 1.9.1

**Comment by hzdjulytech** [comment]
中间升级过一次 掉  getOptions  中data 存在循环引用
的坑里面去了 后来就没折腾了

**Comment by wenzhixin** [comment]
你这个问题假如不升级的话可以先修改代码解决下。
可以考虑升级到最新版本，我们即将发布 1.15.0 版本。
