### ISSUE TITLE
Table styles disappear on 'load' new data

### ISSUE THREAD

**Issue by HaritDivyesh** [wenzhixin/bootstrap-table#4424]
Hi,
I have a table with some data and pre-applied styles using classes directly to the table such as `table table-hover table-dark text-center table_styler`.

I am updating some cell values on a separate button click. Once I update it using `$(tableID).bootstrapTable("load", newTableData);`, the table loses the abovementioned styles. console logging the table element shows the styles are still there (with the updated cell values), but visually they disappear. The table turns to a white table with none of the pre-applied styles.

What might I be doing wrong? I tried resetting the styles using `$(tableID).bootstrapTable("refreshOptions", {
    classes: "table table-hover table-dark text-center table_styler"
  });`, but it seems to have no effect.

Unfortunately I can't share the relevant snippet due to company policies, but I'm attaching a .gif of the said action.
![bootstrap_table_style](https://user-images.githubusercontent.com/17729206/59609835-250d0980-90e6-11e9-8ace-3a9b644fda4a.gif)

**Comment by UtechtDustin** [comment]
Without example we cant help, please provide us an example.
You can use fake data (e.g. Lorem ipsum) for the example.

**Comment by HaritDivyesh** [comment]
Turned out to be an issue with my internal code and not something related to bootstrap-table.
