### ISSUE TITLE
Ignore some rows with a specific class / id

### ISSUE THREAD

**Issue by algorys** [wenzhixin/bootstrap-table#4425]
Hello,

I want to know if there is a way to remove some specific row from row count ? I explain my case:

- I have 2 `tr` for each of my item.
- One has a ``data-toggle="collapse"`` to collapse the second

Which gives the following code:

```html
<tr class="collapsed" data-toggle="collapse" data-target="id_one" ...>
    <td>Value 1</td>
    <td>Value 2</td>
    <td>Value 3</td>
</tr>
<tr id="id_one" class="collapse" colspan="3">
   <td>More HTML elements with more informations </td>
</tr>
<tr class="collapsed" data-toggle="collapse" data-target="id_two" ...>
    <td>Value 1</td>
    <td>Value 2</td>
    <td>Value 3</td>
</tr>
<tr id="id_two" class="collapse" colspan="3">
   <td>More HTML elements with more informations </td>
</tr>
```

Problem here is pagination count 2 rows (normal behavior, I know...), but only one is displayed. And I want that `tr` with `collapse` is not count in pagination. 

Is there a way to achieve that please, by giving class for example ?

**Comment by UtechtDustin** [comment]
You try to implement a detail view, which is already implemented, see [here](https://examples.bootstrap-table.com/index.html#options/detail-view.html).

**Comment by algorys** [comment]
@UtechtDustin ok, I've it, but I can't find an example to pass data to function... because I use `expressjs` and `pug` to generate my html pages.

So I'll have (for each row,) this kind of data:

```json
{
 "_id" : "xxxxxx-xxx-xxxx-xxxxxxxx",
  "login": "mylogin",
  "type": 2,
  "user.first_name": "N/A",
  "user.last_name": "N/A",
  "validity_begin": "2019-06-13T09:32Z",
  "validity_end": "2019-06-18T12:47Z" 
}
```

Its data should only appear in the detailed view. So for the html, I can manage and generate it with the javascript, but how I pass my data to the detailView function

While searching the source code of the [page](https://examples.bootstrap-table.com/index.html#options/detail-view.html), I saw that there was a function called `detailFormatter` who take index and row as arg:

```js
function detailFormatter(index, row) {
    let html = [];
    $.each(row, function (key, value) {
        html.push('<p><b>' + key + ':</b> ' + value + '</p>')
    })

    return html.join('');
}
```

Is there a trick to do the same but taking an object instead ?

**Comment by algorys** [comment]
Ok, I found a solution, I move my details in a column of the row then  add d-none on this column and row of details.

After only to return value of column and row:

```html
<table data-detail-view="true" data-detail-formatter="detailFormatter">
    <thead>
        <tr>
            <td>Col 0</td>
            <td>Col 1</td>
            <td>Col 2</td>
            <td class="d-none">Col 3</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Value 1</td>
            <td>Value 2</td>
            <td>Value 3</td>
            <td class="d-none">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <!-- Some other HTML elements-->
                    </div>
                </div>
            </td>
        </tr>
    </tbody>
</table>
```
And javascript only return the key `3`:

```js
function detailFormatter(index, row) {
    let html = [];
    $.each(row, function (key, value) {
        if(key === "3")
            html.push('<p>' + value + '</p>')
    })
    return html.join('');
}
```

I do not know if it's the best way, but it works :tada:
