### ISSUE TITLE
No error displayed if ajax request fails

### ISSUE THREAD

**Issue by carlfischerjba** [wenzhixin/bootstrap-table#4427]
My data URL was returning a gateway error (502) because the application server was timing out due to a poorly optimised database query. Users were seeing "No matching records found" and had no idea that something had gone wrong.

I've had to add a bit of javascript to display a more accurate message in the table in case of error retrieving data. [JSFiddle](https://jsfiddle.net/0cktr3ga/2/)

Perhaps this could be integrated into bootstrap-table?

**Comment by UtechtDustin** [comment]
You can overwrite the [ajax](https://bootstrap-table.com/docs/api/table-options/#ajax) to have a better solution, but i agree we should implement that !

**Comment by carlfischerjba** [comment]
Good point about using the `ajax` option. It still feels like a bit of a hack because there's no direct access to the "no records" message within the table. Perhaps a new method called `setMessage` would make this a bit neater.

**Comment by djhvscf** [comment]
You can use [formatNomatches](https://bootstrap-table.com/docs/api/localizations/#formatnomatches)

**Comment by UtechtDustin** [comment]
@djhvscf 
Sure, but we still should add an option for the error function of the ajax request, because there are a lot of potential errors.

**Comment by wenzhixin** [comment]
This feature has improved in the develop branch.
[`updateFormatText `](https://github.com/wenzhixin/bootstrap-table/blob/develop/site/docs/api/methods.md#updateformattext) method can solve this problem:
https://live.bootstrap-table.com/code/wenzhixin/33

**Comment by UtechtDustin** [comment]
The [updateFormatText](https://github.com/wenzhixin/bootstrap-table/blob/develop/site/docs/api/methods.md#updateformattext) function should be enough.
In the next version (will be released soon) you can use it.
