### ISSUE TITLE
How to do pagination right?

### ISSUE THREAD

**Issue by davidgatti** [wenzhixin/bootstrap-table#4428]
All the examples out there, rely on fixed JSON files, that don't show how you can do pagination by using JS.

I'm working with DynamoDB, and when I query for the data, I'm adding the data to the table like so:

```javascript
//
//  ->  Execute the command
//
obj.ddb.query(params, function(error, data) {

    //
    //  1.  Check if there was an internal error
    //
    if(error)
    {
        console.info(params);
        return console.error(error);
    }

    data.Items.forEach(function(item) {

        //
        //
        //
        $('#table').bootstrapTable('insertRow', {
            index: 1,
            row: item
        });

    });

});
```

This works fine, but there isn't a clear explanation how to go about doing the pagination. My questions are:

- How can I add the total amount of items with JS?

**Comment by UtechtDustin** [comment]
You can fetch the data from your database and create an array.
The array can be used in some ways, e.g. pass the array while init the dable with javascript (see [here](https://examples.bootstrap-table.com/#welcomes/from-data.html)) or you can init the table and then load the array with the method [load](https://examples.bootstrap-table.com/index.html#methods/load.html).

**Comment by davidgatti** [comment]
Both examples don't work. Plus they don't explain how to add the amount of rows in total.

**Comment by UtechtDustin** [comment]
Both examples works fine for me, please provide us an example (jsfiddle).
What do you mean with "add the amount of rows in total" ?
With both methods you will add all rows at once and you can use the pagination.

**Comment by davidgatti** [comment]
That is fantastic that it works for you, but when I copy and paste the JS code provided in the example, nothing happens:

- the `data` dose nothing
- `load` dose nothing

The only method that works per documentation is `insertRow`. 

And when I mean add the total rows, I mean: if in the db I have 20 rows, but only getting 10, how can I tell the table that it should show the `>` arrow, so the user knows that there is more stuff? Since I don't want to pull 1TB off data to the user in one go.

The whole file: https://gist.github.com/davidgatti/2dbbfdd38c0c236409c971aa1c28f661

**Comment by UtechtDustin** [comment]
Sorry you are the first person who says that the examples are not working.
Also the examples working, checkout our online editor:
from data: https://live.bootstrap-table.com/example/welcomes/from-data.html
load: https://live.bootstrap-table.com/example/methods/load.html

But back to topic, to show the pagination you have to use the table option [pagination](https://bootstrap-table.com/docs/api/table-options/#pagination).
If you have to much data to load it at once (e.g. via from-data or with the load method) you should use ajax ([url](https://bootstrap-table.com/docs/api/table-options/#url)).

**Comment by davidgatti** [comment]
Ehh... @UtechtDustin, if you were to check my code that I linked to, I'm not using Ajax, nor I can use it, because I'm querying data directly to AWS DynamoDB, using the AWS SDK for the Browser, and thus I'm looking for a way to tell the table myself what to do, and how to behave. 

Maybe this is just not possible.

**Comment by UtechtDustin** [comment]
I never used the AWS DynamoDB, so i gave you some ways how to do it maybe.

If you cant use ajax, so you can only load all data at once (the 2 examples above).
Will also work with DynamoDB, because you can still create the array in javascript.

**Comment by davidgatti** [comment]
But how then I tell the table there is more data that the user can get? Aaaaaaa 🤪

**Comment by UtechtDustin** [comment]
As already explaint its only possible to load the data in chunks with ajax.

So your only option is to load the whole data into the table and then use the pagination option to only display some rows per page.
The next version (will be released soon) can handle a lot of data without ajax, the current version have some perfocmance issues with large datasets, so you can only try if that is a way for you or not.
