### ISSUE TITLE
在使用bootstrap-table插件时，如何使用ClipBoard.js插件

### ISSUE THREAD

**Issue by hajtjh** [wenzhixin/bootstrap-table#4429]
![屏幕快照 2019-06-19 18 53 00](https://user-images.githubusercontent.com/2658104/59759836-850cd700-92c3-11e9-8320-cd3251568706.png)
![屏幕快照 2019-06-19 18 55 57](https://user-images.githubusercontent.com/2658104/59760018-e46ae700-92c3-11e9-983b-d9a23bf40c6c.png)

我想用ClipBoard.js插件  实现点击“复制”按钮，将“红色文字”复制下来，可ClipBoard插件先于BootStrap-Table插件运行，请问有什么办法改变执行顺序吗？

**Comment by hajtjh** [comment]
I want to use ClipBoard.js plug-in to click the "copy" button and copy the "red text", but the ClipBoard plug-in runs before the BootStrap-Table plug-in. Is there any way to change the execution order?

**Comment by wenzhixin** [comment]
Please provide an [Online Exmple](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
As @wenzhixin already said, please provide us an example, but there should be multiple ways to solve that.
You can use one of our [Events](https://bootstrap-table.com/docs/api/events/) to initialize the clipboard.js plugin or you initialize it within an on click event.

**Comment by hajtjh** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<title>BootStrap-Table And ClipBoard.js </title>
  
      <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.css">
      <link href="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
  
</head>
<body>
		<table id="tableElement" class="table">
        <thead>
        <tr>
            <th data-field="name" data-sortable="true">Name</th>
            <th data-field="price" data-formatter="CopyThis">Price</th>
            <th data-field="id" data-formatter="tableActions">Action</th>
        </tr>
        </thead>
    </table>

  <script src="http://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
  <script src="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
  
  <script type="text/javascript">
    var $table = $('#tableElement');
		
		$(function(){
          var table_data = [
              {
                "id": 0,
                "name": "Item 0",
                "price": "$0"
              },
              {
                "id": 1,
                "name": "Item 1",
                "price": "$1"
              },
              {
                "id": 2,
                "name": "Item 2",
                "price": "$2"
              },
              {
                "id": 3,
                "name": "Item 3",
                "price": "$3"
              },
              {
                "id": 4,
                "name": "Item 4",
                "price": "$4"
              },
              {
                "id": 5,
                "name": "Item 5",
                "price": "$5"
              }
        ];
    
    		$table.bootstrapTable({data:table_data});
      
    });
    
    function CopyThis(value) 
    {
      return '<span id="copy_' + value + '" class="text-danger">{:config("'+value+'")}</span>';
    }

    function tableActions(data, row, index)
    {
      return '<button type="button" class="btn btn-xs btn-success" data-clipboard-target="#copy_' + data.name + '">Copy</button>'
    }
  </script>
  </body>
</html>`

**Comment by UtechtDustin** [comment]
Please use our  [Online Editor](https://live.bootstrap-table.com) to provide us an example instead of posting the code....

**Comment by hajtjh** [comment]
> Please use our [Online Editor](https://live.bootstrap-table.com) to provide us an example instead of posting the code....

Thank you very much. I'm going to do research.

**Comment by hajtjh** [comment]
> As @wenzhixin already said, please provide us an example, but there should be multiple ways to solve that.
> You can use one of our [Events](https://bootstrap-table.com/docs/api/events/) to initialize the clipboard.js plugin or you initialize it within an on click event.

Thank you very much. I'm going to do research.

**Comment by UtechtDustin** [comment]
@hajekj 
Any news here ?

**Comment by UtechtDustin** [comment]
I close this issue because we got no example within 7 days, if you still need help please reopen the issue.
