### ISSUE TITLE
Filter on a column with formatControl "select" and formatter does not work

### ISSUE THREAD

**Issue by PotatoTroll** [wenzhixin/bootstrap-table#4430]
You cannot filter a column that has formatControl "select" and a formatter.

Example on CodePen: https://codepen.io/anon/pen/BgQRRL

**Comment by UtechtDustin** [comment]
Please use our [editor](https://live.bootstrap-table.com/) to provide us an demo of the issue.

**Comment by UtechtDustin** [comment]
I can confirm that issue, we will check that!

For Development:
The issue that the option of the select have always the "base" value and not the formatted value (also with the [searchFormatter](https://bootstrap-table.com/docs/api/column-options/#searchformatter) option).
There is also a second Bug, the shown text is the formatted text also if the [searchFormatter](https://bootstrap-table.com/docs/api/column-options/#searchformatter)  option is not used.

**Comment by PotatoTroll** [comment]
To fix this I changed this line in `bootstrap-table-filter-control.js`:
`const text = $.trim($(event.currentTarget).val())`

to
```
const text = $.trim(event.currentTarget.tagName == "SELECT"
  ? event.currentTarget.options[event.currentTarget.selectedIndex].text
  : event.currentTarget.value)
```

**Comment by UtechtDustin** [comment]
Its a workaround but we should fix it in a better way (we should change the value of the option).
But thank you for sharing a workaround.
