### ISSUE TITLE
Export with data-filter-control="select" error in Excel and PDF header sheet and UTF-8 encoding fail

### ISSUE THREAD

**Issue by jordiribes** [wenzhixin/bootstrap-table#4431]
Hello, 

Bootstrap-table with bootstrap 4 does not work.  Export + Filter Select option fail as **thiazzz** says. The items in the dropdown appear in the exported excel sheet

In the new online editor, [In the new online editor](https://live.bootstrap-table.com/), it doesn't work either.

<img width="1388" alt="34796716-aeccc114-f656-11e7-86e6-1e9999db3857" src="https://user-images.githubusercontent.com/51998260/59783735-1d558c80-92c1-11e9-960b-5034bc615d52.png">

[XLS Result with error](https://github.com/kayalshri/tableExport.jquery.plugin/files/3307085/tableExport-5.1.xlsx)

**Comment by jordiribes** [comment]
Example in new online editor

https://live.bootstrap-table.com/code/jordiribes/18

When exporting to PDF or XLS you will see the error 

We also have the **UTF-8 encoding error**.

![imatge](https://user-images.githubusercontent.com/51998260/59784864-c00f0a80-92c3-11e9-817a-06c9b795e4af.jpg)

**Comment by UtechtDustin** [comment]
Thank you for your bug report, the bug is already fixed in our develop branch.
That means the next version will not export the options of the select.

The encoding issue is a issue of the export plugin, we cant fix that because our table shows the correct data.

Demo: https://live.bootstrap-table.com/code/UtechtDustin/19

**Comment by jordiribes** [comment]
Thanks !!!!!



Regards  ;-)









[image: pixel12]

[image: Salesians] <http://www.salesianssarria.com/>



*JORDI RIBES CASTELLS*
*FORMACIÓ CONTINUA – BORSA DE TREBALL*
*SALESIANS SARRIÀ *



Pg. Sant Joan Bosco, 42
08017 - BARCELONA
T 932 031 100    F 932 800 130



[image: Facebook] <https://www.facebook.com/cursos.salesians.sarria>

[image: Twitter] <https://twitter.com/salesianssarria>

[image: Linkedin] <https://www.linkedin.com/in/salesianssarria>

[image: Youtube] <https://www.youtube.com/user/websalesianssarria/videos>

[image: caminoRosas2]

[image: cid:image008.gif@01D460CF.9798B050]SIGUEM SOSTENIBLES. NO HO
IMPRIMEIXIS SI NO ÉS NECESSARI.
*AVÍS LEGAL. En compliment de la Llei Orgànica 15/1999 de Protecció de
Dades de Caràcter Personal, us informem que les seves dades formen part
d'un fitxer responsabilitat de SALESIANS SARRIÀ Si voleu cancel·lar la
subscripció poden fer-ho per correu electrònic a
**protecciodades.sarria@salesians.cat
<protecciodades.sarria@salesians.cat>** amb el tema la paraula BAIXA, o si
desitja exercir els drets d'accés, rectificació, cancel·lació i oposició,
ho pot fer per sol·licitar-ho per escrit a SALESIANS SARRIÀ Passeig Sant
Joan Bosco, 42 08017 BARCELONA, juntament amb una fotocòpia del DNI i
indicant en el tema "PROTECCIÓ DE DADES"*

*A*VISO LEGAL. En cumplimiento de la Ley Orgánica 15/1999 de Protección de
Datos de Carácter Personal, le informamos que sus datos forman parte de un
fichero responsabilidad de SALESIANS SARRIÀ. Si desea darse de baja puede
hacerlo por correo electrónico a protecciodades.sarria@salesians.cat
indicando en el asunto la palabra BAJA, o si desea ejercitar sus derechos
de acceso, rectificación, cancelación u oposición, puede hacerlo
solicitándolo por escrito a SALESIANS SARRIÀ Passeig Sant Joan Bosco, 42
08017 BARCELONA, junto con la fotocopia del D.N.I. e indicando en el asunto
"PROTECCIÓN DE DATOS”







*De:* Dustin Utecht [mailto:notifications@github.com]
*Enviado el:* miércoles, 19 de junio de 2019 19:04
*Para:* wenzhixin/bootstrap-table <bootstrap-table@noreply.github.com>
*CC:* jordiribes <jordi.ribes@salesians.cat>; Author <
author@noreply.github.com>
*Asunto:* Re: [wenzhixin/bootstrap-table] Export with
data-filter-control="select" error in Excel and PDF header sheet and UTF-8
encoding fail (#4431)



Thank you for your bug report, the bug is already fixed in our develop
branch.
That means the next version will not export the options of the select.

The encoding issue is a issue of the export plugin, we cant fix that
because our table shows the correct data.

Demo: https://live.bootstrap-table.com/code/UtechtDustin/19

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wenzhixin/bootstrap-table/issues/4431?email_source=notifications&email_token=AMMW4NHCN5AJWEHONFR4GVLP3JRJFA5CNFSM4HZLP2MKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYCQSKI#issuecomment-503646505>,
or mute the thread
