### ISSUE TITLE
Only export 200 lines of table in v 1.15

### ISSUE THREAD

**Issue by macdoor** [wenzhixin/bootstrap-table#4442]
When I export a table with pagination into Microsoft Excel and this table has 3404 lines.  Only export 200 lines of table in v 1.15. I scrolled to table, exported different content, but alway 200 lines.

My code runs properly with v 1.14.2.

**Comment by UtechtDustin** [comment]
Please provide us an example (use our [Editor](https://live.bootstrap-table.com/)).

**Comment by wenzhixin** [comment]
It's support in our example: https://examples.bootstrap-table.com/#extensions/export.html

**Comment by macdoor** [comment]
brasdownreport1d.htm.zip is my source file
BRAS下联流量日分析-2019年06月09日.xls.zip is my exported file


[BRAS下联流量日分析-2019年06月09日.xls.zip](https://github.com/wenzhixin/bootstrap-table/files/3321102/BRAS.-2019.06.09.xls.zip)


[brasdownreport1d.htm.zip](https://github.com/wenzhixin/bootstrap-table/files/3321099/brasdownreport1d.htm.zip)

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/29733517/60024219-fd133c80-96c9-11e9-818c-7c7e517c0c67.png">

**Comment by wenzhixin** [comment]
What side pagination are you using? `server` side or `client` side?

**Comment by macdoor** [comment]
> What side pagination are you using? `server` side or `client` side?
> I think you can upgrade to v1.15.2 to solve the problem.

I did not apply pagination, I grep all data at one time.

I just upgraded to v1.15.2. I got this error with same code

<img width="374" alt="image" src="https://user-images.githubusercontent.com/29733517/60025333-000f2c80-96cc-11e9-9978-145973efff64.png">

**Comment by macdoor** [comment]
[brasdownreport1d.json.zip](https://github.com/wenzhixin/bootstrap-table/files/3321244/brasdownreport1d.json.zip) json data

**Comment by wenzhixin** [comment]
Can you help to provide us an example (use our [Online Editor](http://live.bootstrap-table.com))?

**Comment by macdoor** [comment]
> Can you help to provide us an example (use our [Online Editor](http://live.bootstrap-table.com))?

I have put my data at http://hd1.ggddoo.com:8000/brasdownreport1d.json. But I cannot access it in online editor.

Is it possible to upload my json data file with online editor?

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/29733517/60166180-3dda9500-9833-11e9-8d15-1cba3b730f7f.png">

**Comment by wenzhixin** [comment]
You can use http://myjson.com/ to save the JSON data.

**Comment by macdoor** [comment]
has been fixed in v1.15.2
