### ISSUE TITLE
hyperLink

### ISSUE THREAD

**Issue by FIVIL** [wenzhixin/bootstrap-table#4447]
Hi, is there any way to use A Tag inside the generated table, i want to make a hyperlink and use it as one of the columns but, instead of hyperlink it keeps showing raw html code

**Comment by UtechtDustin** [comment]
Do you use the [escape](https://bootstrap-table.com/docs/api/column-options/#escape) option ?
The default is `false` so hypelinks should work.

Please provide us an example wiht our [Online Editor](https://live.bootstrap-table.com/).

**Comment by FIVIL** [comment]
I tried to regenerate the problem using your editor and everything worked fine, so i examined my code and it turned out i was using an older version, i updated and now it works just fine.
tnx for your investigation

**Comment by UtechtDustin** [comment]
your welcome, thank you for the feedback !
