### ISSUE TITLE
Sorting within the current page only

### ISSUE THREAD

**Issue by alchermd** [wenzhixin/bootstrap-table#4448]
Hello!

I'm just wondering, is it possible to run the sort (or a `customSort`) function _only on the active pagination page_? Any help or direction would be really appreciated.

Kind regards.

**Comment by UtechtDustin** [comment]
No its currently not possible because we always sort the whole data.
Could you give us an example why you want to sort only the current page ?

@djhvscf @wenzhixin does it makes sense to implement that ?

**Comment by wenzhixin** [comment]
I think it is the same feature as #2965.

**Comment by wenzhixin** [comment]
Close this and we will consider implementing this feature in the future version in #2965.
