### ISSUE TITLE
Doubled rows on treegrid

### ISSUE THREAD

**Issue by SEModer** [wenzhixin/bootstrap-table#4449]
When i'm use new version 1.15.2,  I get this problem, like copies of rows in treegrid. 1.14.2 nothing have this bug...
https://live.bootstrap-table.com/code/SEModer/73

**Comment by UtechtDustin** [comment]
Why are you using an external Library instead of our buildin Features (e.g. [detailView](https://examples.bootstrap-table.com/index.html#options/detail-view.html) or one of our plugins e.g. [Treegrid](https://examples.bootstrap-table.com/#extensions/treegrid.html) ?)

**Comment by SEModer** [comment]
Im use treegrid example for work view tree...
https://live.bootstrap-table.com/example/extensions/treegrid.html

Example have this bug on version 1.15.2

**Comment by SEModer** [comment]
You can see changes on tree, if choose library version 1.14.2 and 1.15.2

**Comment by UtechtDustin** [comment]
Oh okay, my failure never used the the extension i thought we have a real extension insteaf of an example.
We will check that, thank you for the bug report.

**Comment by wenzhixin** [comment]
Fixed in the develop branch.
