### ISSUE TITLE
Question : how can i send selected parms like pageno, page size  to url request for restfull service

### ISSUE THREAD

**Issue by RaghavendraG** [wenzhixin/bootstrap-table#445]
Dear Team,

Please give me an example how to send params to restfull service using server side paginataion. How i get selected pageNo and pagesize to send request along with url.

**Comment by wenzhixin** [comment]
I guess you can use `queryParams` option to send params.

**Comment by RaghavendraG** [comment]
I got the results . Thank you so much.
