### ISSUE TITLE
chrome和火狐显示不一致

### ISSUE THREAD

**Issue by JackZhouMine** [wenzhixin/bootstrap-table#4454]
chrom 的表现
![in](https://user-images.githubusercontent.com/21340150/60153716-ba5f7a80-9817-11e9-9700-ac33809e83e9.png)
Google Chrome	75.0.3770.100 (正式版本) （64 位） (cohort: Stable)
修订版本	cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
操作系统	Windows 7 Service Pack 1 (Build 7601)
JavaScript	V8 7.5.288.23

火狐的表现正常
![good](https://user-images.githubusercontent.com/21340150/60153758-d19e6800-9817-11e9-8cfe-54d306ce0afe.png)

**Comment by wenzhixin** [comment]
Can you help to provide use an [Online Example](https://live.bootstrap-table.com) to show your problem?

**Comment by UtechtDustin** [comment]
I close this issue, because we got no example from you within 7 days.
If you still need help, please reopen the issue and provide us an example (using our Editor).
