### ISSUE TITLE
"TypeError: Symbol.toPrimitive returned an object" when load bootstrap-table.js

### ISSUE THREAD

**Issue by macdoor** [wenzhixin/bootstrap-table#4455]
in v1.15.2
"TypeError: Symbol.toPrimitive returned an object" when load bootstrap-table.js 
Everything is ok when load bootstrap-table.min.js

in v1.14.2, both .js file are ok

<img width="355" alt="image" src="https://user-images.githubusercontent.com/29733517/60174867-95cdc780-9844-11e9-8724-888dd676b7c7.png">

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issue, because we got no example from you within 7 days.
If you still need help, please reopen the issue and provide us an example (using our Editor).
