### ISSUE TITLE
IE11 minify bug 

### ISSUE THREAD

**Issue by SEModer** [wenzhixin/bootstrap-table#4459]
On IE 11.765.17134 when i'm try use bootstrap-table.min.js, there is a problem
![image](https://user-images.githubusercontent.com/789171/60256657-66be6100-98eb-11e9-8d8a-dc12975d692a.png)
When re'minify bootstrap-table.js via https://jscompress.com/ all good and work. Only i'm have this issue?

**Comment by UtechtDustin** [comment]
Do you used the latest version ?

**Comment by wenzhixin** [comment]
I think it's caused by the `rollup-plugin-babel-minify` plugin.

**Comment by BrayamsRamos** [comment]
Habing the same issue:
![bootstrap issue](https://user-images.githubusercontent.com/21320102/60285650-af6a2000-98d3-11e9-9d84-cd65a879b7a1.PNG)
No data is displayed in any table.

IE v11.503.17763.0
bootstrap-table v1.15.2
