### ISSUE TITLE
How use VUE router-link to update data table having a custom link?

### ISSUE THREAD

**Issue by ascweb** [wenzhixin/bootstrap-table#4460]
Hello, I have read the contributing guidelines and I'm not sure to be in the right place. If I'm not, please... delete the post.

I'm working with VUE and boostrap-table works very well!

In my component I have:

`  <BootstrapTable :columns="table.columns" :data="table.data"
                                    :options="table.options"></BootstrapTable>`

Then axios populated the table. It works good.

I'm getting issues updating the table with calculated data received by axios. And I was wondering if there is "a best practices" for this. Basically, I need to create a custom link in first column using the id received by axios, but I would like to use the vue router.

When I got the axios data I create a custom array **newData** and then I update the table with:

`this.$nextTick(function () {
                    this.table.data = newData
                });`

The array has a custom link like
> link: '<a v-bind:href="club/'+team.id+'">'+team.team+'</a>',

or

> link: "<router-link :to=\"{'name': 'team',\'params\': { 'id':"+ team.id+" }}\">"+ team.team+"</router-link>",

But this is paste as plain text and not rendered.

At moment I'm using 

`  link: "<a href='/club/" + team.id + "'>" + team.team + "</a>",`

It works but it reload the whole page instead of using the VUE router

Any suggetsion?

**Comment by wenzhixin** [comment]
@ascweb in the current version, the formatter column option does not support to render the Vue component. We can use `router.push` instead.
A workaround: https://live.bootstrap-table.com/code/wenzhixin/127

**Comment by ascweb** [comment]
yes thanks!

Just lka a custom dataset in JSON HTML code to be processed by a Listener in mounted() just like:

`mounted() {
            window.addEventListener('click', event => {
                let target = event.target;
                if (target && target.href && target.dataset.to) {
                    event.preventDefault();
                    const url = JSON.parse(target.dataset.to);
                    //router.push({ name: 'user', params: { userId: '123' } })
                    this.$router.push(url);
                }
            });
        }`

**Comment by wenzhixin** [comment]
OK, I recommend you to use the `events` column option instead.
https://bootstrap-table.com/docs/api/column-options/#events
https://examples.bootstrap-table.com/index.html#column-options/events.html
https://live.bootstrap-table.com/code/wenzhixin/127

**Comment by ascweb** [comment]
Yes! Your suggestion is perfect in bootstrap-table! I really appreciated it! It works like a charm!

`                        ...
                         {
                            field: 'match',
                            title: 'Match',
                            formatter (value, row) {
                                return `<a href="/matches/${row.pos}">${value}</a>`
                            },
                            events: {
                                'click a': (e, value, row, index) => {
                                   e.preventDefault();
                                    this.$router.push(`/matches/${row.pos}`)
                                }
                            }
                        },`

My solution is good only in case of JSON having links to be processed not in the table but in custom data.

Thanks again!
