### ISSUE TITLE
How to make the table fill the parent element (always show pagination at the bottom)

### ISSUE THREAD

**Issue by yoogie27** [wenzhixin/bootstrap-table#4461]
The height of the table cannot be set to a percentage so it fills the parent.
The reasons why I want to do this:
  - I want to always see the pagination at the bottom (not at the top)
  - I need the table to start at a relative point (as the page header is dynamic)
  - I always want to see the top row (yellow block in my example)

I can't set the position to absolute as the top point is relative..

Online example: https://live.bootstrap-table.com/code/yoogie27/121

**Comment by UtechtDustin** [comment]
We should add a unit option for the height like for the width ([widthUnit](https://bootstrap-table.com/docs/api/column-options/#widthunit)).

**Comment by wenzhixin** [comment]
It's hard to implement this, but there is a workaround for you: https://live.bootstrap-table.com/code/wenzhixin/122

**Comment by yoogie27** [comment]
Thanks guys. The only problem with JS resizing is in my specific case:
I have lazy loading of button elements in my table. Whenever they "scroll" into view, a background task is fetching data from the server and replacing a button with something else.
Resetting the view like this will revert those buttons to the default..

**Comment by UtechtDustin** [comment]
Then provide us an example with that case (you can use fake data).

**Comment by yoogie27** [comment]
Sorry, you guys are fantastic. I was using refreshOptions to manipulate the height instead of resetView.
Thanks a lot, you really helped me
