### ISSUE TITLE
Filter Control select not populated when there is a null/undefined

### ISSUE THREAD

**Issue by dalibor-dev** [wenzhixin/bootstrap-table#4462]
Filter Control select is not completely populated and exception is thrown if there is a null/undefined in data. It works in 1.14.2, but not in 1.15.2.

[Example](https://live.bootstrap-table.com/code/dalibor-dev/123)

**Comment by wenzhixin** [comment]
Merged: https://live.bootstrap-table.com/code/wenzhixin/271
