### ISSUE TITLE
data-filter-control  = 'input' Multi-column filtering is not possible

### ISSUE THREAD

**Issue by 18829218929** [wenzhixin/bootstrap-table#4464]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by djhvscf** [comment]
Please provide us an example with our editor

**Comment by UtechtDustin** [comment]
I close this issue because we got no response/example from you within 7day, if you still need please provide us an example and reopen the issue.

**Comment by timoline** [comment]
Can you reaopen this issue?
I have the same issue with multiple colums and select.

I'll provide an example as soon as possible

**Comment by wenzhixin** [comment]
It's hard to find what problem it is if we can't reproduce the bug.

**Comment by UtechtDustin** [comment]
@timoline 
Could you provide us an example on a other way (e.g. upload a example as file) ?

**Comment by timoline** [comment]
hmm, i'll try.

One bug is in this peace of code.

    $('#table').bootstrapTable({
        hideUnusedSelectOptions: true
    });

is it changed or not available anymore?

**Comment by timoline** [comment]
I'm sorry I still cant use bt in production if this is not fixed, can you help please?
