### ISSUE TITLE
Export all data with client side for more than 2000+ data, it takes longer time and pagination is destroyed

### ISSUE THREAD

**Issue by ksodari** [wenzhixin/bootstrap-table#4465]
### **Issue Scenario**
_**table options used are as below**_
```
searchTimeOut: 300,
pagination: true,
refresh: true,
showRefresh: true,
showExport: true,
exportDataType: "all",
//refreshOptions: {
   //    exportDataType:'all',
//},
exportTypes: ['csv'],
exportOptions: {
      ignoreColumn: [6], // Ignore index arrays for some columns
      fileName: "sampleCsvFile",
},
url: "some_url_route",
method: "get",
dataType: "json",
dataField: "search_result",
```

**_Actual Scenario for the issue_**
Data in the table are around 5000 plus. When clicking the CSV Export button, it takes really long time to compile csv file and after export is done, pagination row is destroyed along with table info row on the bottom of the table. In fact there is no pagination implemented on the page, the whole rows of data are shown there in the single page which we can see just by scrolling down
We have to refresh whole page to toggle back the pagination in such case. 

**_Querry:_**
1. Can you please help me understand this issue. I would like to get pagination toggle back right away the export all is done without any such issues
2. I would also like to know how can I swipe the positions for refresh button and Export button?
![image](https://user-images.githubusercontent.com/5551062/60479501-0485a780-9cc1-11e9-8b49-1dc2aa8730d2.png)

Thanks a lot in advance.

**Comment by wenzhixin** [comment]
1. If you export `all`, we need to hide the pagination to show all data, and after exporting file show it again. A working example: https://live.bootstrap-table.com/code/wenzhixin/136.
2. Not supported. ref #2135

**Comment by ksodari** [comment]
@wenzhixin It is not working on mine. And that example shows server side pagination mode. Mine is client side pagination with more than 6000 data and I have like 6-7 columns of data. When I click CSV export, the page hangs and take long time to process csv compilation. and if you click other tab and back to the export table tab on your browser, you will see a blank page only until export is completed. And I don't understand in the example given by you, how and where is the pagination toggled after export?

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by ksodari** [comment]
> Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Please check this out. how I am trying to do it. 
[Online Example](https://live.bootstrap-table.com/code/ksodari/166)

**Comment by UtechtDustin** [comment]
Your Example works for me fine.
I can download all 8000 Rows, also the pagination is not broken.

Downloaded file: https://www.file-upload.net/download-13653232/mySampleData.csv.html

I'm using Firefox, which Browser do you use ?

**Comment by ksodari** [comment]
@UtechtDustin 
I am using opera as well as firefox. Didn't you notice it hangs our browser for a while right after you click export CSV button??

I tried doing it with server sidePagination on my device but it doesn't work for export all. 
Do we need to do anything on backend side? I mean in controller method?? Do we need to specify download parameters and initialize something for export all option with server side pagination??

**Comment by UtechtDustin** [comment]
Sure i noticed that the browser hangs up for some seconds, thats because of the 8000 (!!) Rows.
For larger Datasets we suggest to export it by the server not by the client(browser).

**Comment by wenzhixin** [comment]
I agree with @UtechtDustin

**Comment by ksodari** [comment]
> Sure i noticed that the browser hangs up for some seconds, thats because of the 8000 (!!) Rows.
> For larger Datasets we suggest to export it by the server not by the client(browser).
@UtechtDustin @wenzhixin 
I agree with you there. That's the major reason I need help here 😃 Could you help me how can I implement server side download for when I click Export All button it downloads from api call instead of client side in the same online example. 
Thanks!

**Comment by UtechtDustin** [comment]
As already explaint large data should be exported by the Server not by the client(browser).
If you still need help please reopen the issue.

**Comment by Shaun-Yao** [comment]
https://live.bootstrap-table.com/code/wenzhixin/136.
@wenzhixin This example just work for client sidePagination ?

**Comment by wenzhixin** [comment]
@Shaun-Yao The example is for `data-side-pagination="server"`.

**Comment by Shaun-Yao** [comment]
@wenzhixin 只要设置total就会自动完成导出所有数据吗？我设置了total没有作用，不知道这当中是什么原理

**Comment by wenzhixin** [comment]
最主要是你后台的接口返回的数据是对的，例如你导出所有的时候是不传 limit 的。
上面的例子只是为了说明可以导出 5000 条数据而已，你自己 F12 看到导出所有的请求以及返回，默认是 800 条： https://examples.wenzhixin.net.cn/examples/bootstrap_table/data

**Comment by Shaun-Yao** [comment]
@wenzhixin 谢谢！我使用下面这段来导出全部数据
```
queryParams: function (params) {
                if (typeof(params.limit) == "undefined") {//导出全部数据没有传limit给后台, 把limit
                    params.limit = this.totalRows;
                }
                return params;
            }
```
