### ISSUE TITLE
Filter-control and Cookie do not work for the first time. Issue #4158 is not fixed.

### ISSUE THREAD

**Issue by SEModer** [wenzhixin/bootstrap-table#4466]
This bug remained in version 1.15.2 when sidePagination="server"
To simulate this bug, you need:
-Open example
-Clear storage on https://live.bootstrap-table.com (cookies, chache e.t.c)
-Press Run
-Input any information in any field for the filter.
-Change filter
Result: The table is not worked =( 

My example https://live.bootstrap-table.com/code/SEModer/134
Example UtechtDustin from issue [4158](https://github.com/wenzhixin/bootstrap-table/issues/4158), just added sidePagination="server" https://live.bootstrap-table.com/code/SEModer/135

**Comment by wslpeter** [comment]
v1.16.0,问题依旧？
