### ISSUE TITLE
filterBy Array not showing results in 1.15.2

### ISSUE THREAD

**Issue by uruar** [wenzhixin/bootstrap-table#4467]
I was trying to give an array to the table to filter the results, I did this by using this code:

      online.click(function () {
        table.bootstrapTable('filterBy', {
          Id: onlineObjects
        });
      });

    offline.click(function () {
      table.bootstrapTable('filterBy', {
        Id: offlineObjects
      });
    });

    all.click(function () {
      table.bootstrapTable('filterBy', {
      })
    });

However when I use online.click and offline.click I get no objects found, When if I do all.click I indeed get all results. This was working in version 1.14.2 but since version 1.15.2 this has stopped working.

**Comment by UtechtDustin** [comment]
Please provide us an example with our [Online Editor](https://live.bootstrap-table.com/).

**Comment by uruar** [comment]
https://live.bootstrap-table.com/code/uruar/140

This is where I created the example

**Comment by UtechtDustin** [comment]
Here is the working Code: https://live.bootstrap-table.com/code/UtechtDustin/142

You tried to bind a event on the Arrays instead of the buttons.
Also you used `table` instead of `$table` for the `offline` and `all` code.
