### ISSUE TITLE
Remember Page

### ISSUE THREAD

**Issue by austinstudio** [wenzhixin/bootstrap-table#447]
I have a situation where I want to save the page that the user is viewing so that when the user returns to the page I can take them back to the page that they were previously on.

An example would be a search page.  A user searches for a list of things, pages a few pages to find the thing they are looking for and then navigates to the details page of that thing.  They realize that the thing that they clicked on wasn't the one they were looking for and use the back button we have provided on the page to get back to the search with the search results.  We want the search page to load with the page that they were already on before they left the page.  Is there a way to do this?

Thank you.

**Comment by cdomkokao** [comment]
Anyone?  This is important for our project that we can jump to a page in the table when the page loads.

**Comment by wenzhixin** [comment]
You can use the cookie extension: 
http://bootstrap-table.wenzhixin.net.cn/extensions/#table-cookie
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html
