### ISSUE TITLE
Upgrading from Version 1.13.4 to Version 1.15.2, Method'getOptions' doesn't work very well

### ISSUE THREAD

**Issue by moonhow007** [wenzhixin/bootstrap-table#4470]
My English is so poor,Forgive me.

environment：win7/10 x64 Google Chrome v75

e.g. 
`var options = $('#mytable').bootstrapTable('getOptions');`
`options.hasOwnProperty('onLoadSuccess');`
`options.onLoadSuccess({'total': rows.length,'rows': rows});`
v1.13.4: return true
v1.15.2: return false, Browser Console：options.onLoadSuccess is not a function.

ps: In version 1.15.2, all event functions were not added to 'options' Object.
onAll: ƒ ()
onCheck: ƒ ()
onCheckAll: ƒ ()
onCheckSome: ƒ ()
onClickCell: ƒ ()
onClickRow: ƒ ()
onCollapseRow: ƒ ()
onColumnSwitch: ƒ ()
onDblClickCell: ƒ ()
onDblClickRow: ƒ ()
onExpandRow: ƒ ()
onLoadError: ƒ ()
onLoadSuccess: ƒ (data)
onPageChange: ƒ (number,size)
onPostBody: ƒ ()
onPostHeader: ƒ ()
onPreBody: ƒ ()
onRefresh: ƒ ()
onRefreshOptions: ƒ ()
onResetView: ƒ ()
onScrollBody: ƒ ()
onSearch: ƒ ()
onSort: ƒ ()
onToggle: ƒ ()
onUncheck: ƒ ()
onUncheckAll: ƒ ()
onUncheckSome: ƒ ()

**Comment by UtechtDustin** [comment]
Please help us an provide us an example with our [Online Editor](https://live.bootstrap-table.com/).

**Comment by moonhow007** [comment]
> Please help us an provide us an example with our [Online Editor](https://live.bootstrap-table.com/).

example url:[https://live.bootstrap-table.com/code/moonhow007/179](url)
