### ISSUE TITLE
1.15.2版本 getOptions 会丢失回调方法

### ISSUE THREAD

**Issue by hzdjulytech** [wenzhixin/bootstrap-table#4471]
1.15.2 版本 会丢失 回调方法  同时存在 data 循环引用问题
var options = JSON.parse(JSON.stringify(this.options));
  delete options.data;
1.12.2 版本 写法 
$.extend(true, {}, opt);
opt.data 为了使用方便坑会外挂 循环数据

我的修改方式
var opt= $.extend({}, this.options);
    	var data=opt.data;
    	delete opt.data;
    	opt= $.extend(true, {}, opt);
    	opt.data=data;
    	return opt;

**Comment by hzdjulytech** [comment]
函数丢失 不利于 自定义拓展

**Comment by UtechtDustin** [comment]
same as #4470?
@wenzhixin

**Comment by wenzhixin** [comment]
#4473
If you need the `options.data` please use `getData` instead.
