### ISSUE TITLE
Cookies not storing on 1.15.2

### ISSUE THREAD

**Issue by wtluke** [wenzhixin/bootstrap-table#4476]
After a lot of diagnosing, we think we've found a bug with bookstrap-table-cookie. On 1.15.2, columns aren't being saved, either as cookies or in localstorage.

https://jsfiddle.net/7cs3d5j4/

E.g. ```<table id="table"
data-show-columns="true"
  data-cookie="true"
  data-cookie-id-table="saveId"
  data-search="true"
  data-cookie-storage="localStorage">```

Changing the following to use 1.14.2 makes it work.

`<script type="module" src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.js"></script>`

`<script type="module" src="https://unpkg.com/bootstrap-table@1.14.2/dist/extensions/cookie/bootstrap-table-cookie.min.js"></script>`

I haven't been able to find out why - it's beyond me - but hopefully this helps.

Thanks

**Comment by UtechtDustin** [comment]
Our [Example](https://examples.bootstrap-table.com/index.html#extensions/cookie.html) works fine, could you provide us an example of your not working code with our [Editor](https://live.bootstrap-table.com/) ?
Your Jsfiddle example works for me.
