### ISSUE TITLE
filterShowClear is no longer available?

### ISSUE THREAD

**Issue by colistro123** [wenzhixin/bootstrap-table#4483]
Hi, I just pulled the latest changes from master and it seems that filterShowClear is no longer an option when initing the table? A trash icon used to show in the toolbox pane to the upper right, which allowed you to clear filters. Not sure if there's a way to easily replicate this feature if it was removed since it's really useful.

https://i.imgur.com/hw3eBeK.png

Thanks in advance.

**Comment by UtechtDustin** [comment]
filterShowClear was removed because of the new option [showSearchClearButton](https://bootstrap-table.com/docs/api/table-options/#showsearchclearbutton).

**Comment by colistro123** [comment]
Solved by using `toolbar: "#toolbar" to make my own toolbar,` in conjunction with `$("#table").bootstrapTable('clearFilterControl');`

Thanks.
