### ISSUE TITLE
bootstrap-table 不加载有null值的数据

### ISSUE THREAD

**Issue by wzx-boot** [wenzhixin/bootstrap-table#4484]
bootstrap-table 不加载有null值的数据
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by wenzhixin** [comment]
请提供例子

**Comment by UtechtDustin** [comment]
I close this issue because we got now response/example from you within 7 days.
If you still need help please reopen the issue and provide us an example.
