### ISSUE TITLE
formatter function execute before table init well

### ISSUE THREAD

**Issue by Justmysteriousman** [wenzhixin/bootstrap-table#4486]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by Justmysteriousman** [comment]
in my situation，i hava a tree view ,every node of it,i need to redraw the table,so i call destroy,my formatter use the bootstrapTable('getOptions') method,but it return a object or like a object named 'init' and then i cannot get options like pageSize and pageNumber and so on,then i try to click next page(not destory and redraw),it works

**Comment by Justmysteriousman** [comment]
how can i make the formatter execute after the table init well

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issue because we got no example/response from you, if you still need help please reopen the issue and provide us an example.
