### ISSUE TITLE
Ref #4243  How to handle errors when using data-url?

### ISSUE THREAD

**Issue by ravi-ku** [wenzhixin/bootstrap-table#4487]
How to handle errors in the response - for example, if there is some server side error occurred then it will show on UI using alert. But below function always returns 500 NOT actual error.

**Use the onLoadError event.**
```
 onLoadError: function (status) {
                    debugger;
                    $.notify({ title: '<strong>Error!</strong>', message: 'Some error is occurred. Please try again.' }, { type: 'danger' });
                }
```

**Server Side Code**
 catch (Exception ex)
            {
                return Json(new { success = false, errors = ex.Message });
            }

**Comment by wenzhixin** [comment]
https://live.bootstrap-table.com/code/wenzhixin/248

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by ravi-ku** [comment]
No... try to show server error/ actual error coming from web api

**Comment by ravi-ku** [comment]
Any updates on this?

**Comment by wenzhixin** [comment]
I don't know what problem do you have? Can you provide an [Online Example](https://live.bootstrap-table.com) to show the problem?

**Comment by wenzhixin** [comment]
I think the [onLoadError](https://bootstrap-table.com/docs/api/events/#onloaderror) can solve the probelm: https://stackoverflow.com/questions/1637019/how-to-get-the-jquery-ajax-error-response-text.

If the problem exists reopen it, thanks!
