### ISSUE TITLE
updateCell会导致整个列表数据从新加载，那其他行的formatter也都执行一遍，合理吗

### ISSUE THREAD

**Issue by yang354540079** [wenzhixin/bootstrap-table#4489]
updateCell updateRow 不能只刷新当前id或者当前行码，需要整个列表数据都重新init？

**Comment by wenzhixin** [comment]
Duplicate of #3612

**Comment by wenzhixin** [comment]
目前的版本确实存在这个问题，后续版本会改进。

**Comment by sunhk25** [comment]
@wenzhixin 
updateCell更新导致整体重新int而引发的慢的问题，在1.18.2版本中仍然存在，有什么解决方案吗
(我自定义了一个checkbox列，在整体反转时更新很慢)

**Comment by wenzhixin** [comment]
暂时还不支持，估计可以暂时先用 jQuery 的方法手动更新
