### ISSUE TITLE
creating two tables in sub-table?

### ISSUE THREAD

**Issue by myronzylka** [wenzhixin/bootstrap-table#4490]
Is it possible to create two tables inside subTable in the same row with both different set of data for row and column currently  when I use the same onexpandrow event it overwrites the table I want to create two tables inside one row

**Comment by wenzhixin** [comment]
Do you mean: https://live.bootstrap-table.com/code/wenzhixin/249?

**Comment by myronzylka** [comment]
yes but i am not sure how many table will be there it has to be dynamic.

**Comment by myronzylka** [comment]
i achieved this by doing 
 $detail.append('<div><table id=\"div' +colKey+'\"></table></div>');
  var $table = $('#div'+ colKey);
by using append and giving  dynamic id to the table.

**Comment by myronzylka** [comment]
I want to freeze single column so that it don't scroll and how to add cell style to that column through javascript method

**Comment by UtechtDustin** [comment]
Example for cell styling: https://live.bootstrap-table.com/example/issues/221.html
Example for fixed columns: https://live.bootstrap-table.com/example/extensions/fixed-columns.html

I close this issue, because its already some month old, if you still need (more) help please reopen the issue.
