### ISSUE TITLE
content-editable td's revert to original after sorting

### ISSUE THREAD

**Issue by bsolomon1124** [wenzhixin/bootstrap-table#4491]
### Summary

`<th>` with `data-sortable="true"`, which have `<td contenteditable="true">`, will revert to the "original" cell value after the table is sorted based on that column.

Browsers this occurs on: Firefox, Chrome.

### Reproducing

See the HTML in the comment below.

### Things I've Tried

I've tried the [editable](https://bootstrap-table.com/docs/extensions/editable/) extension but am having the same problem there.  ([JSFiddle](https://jsfiddle.net/c7zrskhq/))  Is there a simpler way about this?

### Example

The table originally looks like this:

![Screen Shot 2019-07-11 at 2 10 19 PM](https://user-images.githubusercontent.com/25164676/61074395-a73ad600-a3e5-11e9-80ca-0c06ceca2908.png)

After editing:

![Screen Shot 2019-07-11 at 2 10 52 PM](https://user-images.githubusercontent.com/25164676/61074432-b7eb4c00-a3e5-11e9-8e08-4ce97787f339.png)

After sorting:

![Screen Shot 2019-07-11 at 2 10 19 PM](https://user-images.githubusercontent.com/25164676/61074395-a73ad600-a3e5-11e9-80ca-0c06ceca2908.png)

### Update

I've started focusing on the classes and event listener for the header cells.  They look like this:

![Screen Shot 2019-07-11 at 9 00 01 PM](https://user-images.githubusercontent.com/25164676/61094867-0406b280-a41f-11e9-8b9f-a0e379ef6d7a.jpg)

On the cell there is a single `keypress` [event from bootstrap-table.js](https://github.com/wenzhixin/bootstrap-table/blob/develop/dist/bootstrap-table.js):

```javascript
function(o) {
  if (t.options.sortable && s(o.currentTarget).data().sortable) {
    var e = o.keyCode || o.which;
    13 === e && t.onSort(o)
  }
}
```

That led me to the [events API](https://bootstrap-table.com/docs/api/events/), which would seem to imply something like:
```javascript
    $("table.table").bootstrapTable({
      onSort: function (name, order) {
        // ...?
      }
    });
```

...but I'm pretty stuck there.

**Comment by bsolomon1124** [comment]
HTML:

```html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hello, Bootstrap Table!</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">
  </head>
  <body>
    <table data-toggle="table">
      <thead>
        <tr>
          <th data-sortable="true">Item ID</th>
          <th data-sortable="true">Item Name</th>
          <th data-sortable="true">Item Price</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td>Item 1</td>
          <td>$1</td>
        </tr>
        <tr>
          <td>2</td>
          <td>Item 2</td>
          <td>$2</td>
        </tr>
      </tbody>
    </table>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.js"></script>

    <!-- bootstrap-table ignores contenteditable="true" when set directly in HTML -->
    <script>
      $(document).ready(function () {
        $("td").each(function () {
          console.log($(this));
          $(this).prop("contenteditable", "true");
        });
      });
    </script>
  </body>
</html>
```

**Comment by UtechtDustin** [comment]
The Browser attribute contenteditable will only edit the DOM, not the data in the bootstrap-table.
Please use one of our update methods e.g. [updateCell](contenteditable).

**Comment by UtechtDustin** [comment]
We got no response from you, so i guess your issue is solved.
If you still need help please reopen the issue :-)
