### ISSUE TITLE
queryParams不能添加数组参数

### ISSUE THREAD

**Issue by jsAdore** [wenzhixin/bootstrap-table#4493]
$("#table_" + uniqueId).bootstrapTable("refreshOptions",{
        queryParams:function (params) {
            params.a=["123","oop"]
            debugger
            return params;
        }
    });
结果发送的请求参数是这样：sortOrder=asc&pageSize=10&pageNumber=1&a%5B%5D=123&a%5B%5D=oop

可以考虑$.ajax添加traditional = true

**Comment by jsAdore** [comment]
预期参数是这样：?sortOrder=asc&pageSize=10&pageNumber=1&a=123&a=oop

**Comment by wenzhixin** [comment]
你可以使用 ajaxOptions 进行设置。

**Comment by jsAdore** [comment]
好好，我再看看
