### ISSUE TITLE
No matching records for values in hidden columns

### ISSUE THREAD

**Issue by olafcm** [wenzhixin/bootstrap-table#4496]
Since v1.15.3 the search function is broken when the matching value is in a hidden column.
This used to work before.

Example URL: https://examples.bootstrap-table.com/#welcomes/from-html.html
Example search query: 8827 (correctly shows the "bootstrap-table" row)

But when the column is being deselected to be hidden, the search result(s) dissapears.
The same behaviour occurs when a column was already set to hidden (no results at first, and the results appear when the column with the matching value is visually activated).

**Comment by wenzhixin** [comment]
Thanks for the feedback, fixed in #4497.

**Comment by olafcm** [comment]
Thank you for the quick fix 😊
