### ISSUE TITLE
js初始化bootstrap-table后想在单元格中使用jquery.raty

### ISSUE THREAD

**Issue by jianghong3** [wenzhixin/bootstrap-table#4498]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.
想在bootstrap-table加载完数据后使用jquery.raty显示星星，但没有效果
function initTable() {
        $table.bootstrapTable('destroy').bootstrapTable({
          locale: $('#locale').val(),
          columns: [

               [{
                    field: 'tool_name',
                    title: '工具名称',
                    formatter: linkFormatter
                }, {
                    field: 'result',
                    title: '成果举证',
                    align: 'center',
                }],

          ],
             onLoadSuccess: function (data) {
                console.log($("#star").length);
                $('#star').raty({
                    readOnly: true,
                    score:4,
                    path: "../../static/assets/plugins/raty-images",
            })
          }
        });
This is the first step
This is the second step
Further steps, etc.

Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

麻烦提供下例子。

**Comment by jianghong3** [comment]
function initTable() {
        $table.bootstrapTable('destroy').bootstrapTable({
          locale: $('#locale').val(),
          columns: [

               [{
                    field: 'tool_name',
                    title: '工具名称',
                    formatter: linkFormatter
                }, {
                    field: 'tool_type',
                    title: '工具类型',
                    align: 'center',
                },  {
                    field: 'dev_activity',
                    title: '开发活跃度',
                    align: 'center',
                    sortable: 'true',
                    formatter: starFormatter,
                }, {
                    field: 'user_evaluation',
                    title: '用户评价',
                    align: 'center',
                }, {
                    field: 'result',
                    title: '成果举证',
                    align: 'center',
                }],
       ]
      onLoadSuccess: function (data) {
            console.log($("#star").length);
            $('#star').raty({
                readOnly: true,
                score:4,
                path: "../../static/assets/plugins/raty-images",
        })
      }
}
function starFormatter(value, row, index) {
          var star = "<div id='star'></div>";
          return star;
      }


就是想在开发活跃度这列使用jquery.raty显示星星评分

**Comment by jianghong3** [comment]
function starFormatter(value, row, index) {
var star = "<div id='star'></div>";
return star;
}

**Comment by jianghong3** [comment]
function starFormatter(value, row, index) {
var star = “”“<div id='star'></div>”“”;
return star;
}

**Comment by jianghong3** [comment]
star的双引号里是一个id为star的空div

**Comment by wenzhixin** [comment]
http://live.bootstrap-table.com 不能用吗？

**Comment by jianghong3** [comment]
报错：$(...).raty({}) is not a function

**Comment by wenzhixin** [comment]
你需要引入对应的库

**Comment by jianghong3** [comment]
引入了，在bootstrap-table外面可以显示星星，应该是bootstrap-table的问题

**Comment by wenzhixin** [comment]
应该是用 postBody 这个事件：https://live.bootstrap-table.com/code/wenzhixin/288

**Comment by jianghong3** [comment]
onPostBody:function(data){
     $(.display).raty({})
}

Uncaught TypeError: $(...).raty is not a function
