### ISSUE TITLE
No sort icons in sortable headers.

### ISSUE THREAD

**Issue by aducom** [wenzhixin/bootstrap-table#4499]
I'm sure I overlook something as the samples do work. But I can't find differences between the sample code and my code. I don't get the icons to show the sortable fields and/or the order sequence. I get all the other icons so it's not a matter of font awesome, but something simple. Does someone has an idea where I need to look at?

Ok, I found the issue. I'm using table-classes to set a striping on my table:
    <table width="100%" id="id_dbgrid_dbgrid_1" name="dbgrid_dbgrid_1"
      data-classes="table-bordered table-hover table-striped table-sm table-borderless"

Using data-classes causes the sort icons not to be displayed. The sample application uses a live event to set properties, so that's after rendering the table. How to correct this? I would prefer not to use an event to set these properties. Sorting on name does work 

![afbeelding](https://user-images.githubusercontent.com/5610893/61301564-6a575080-a7e4-11e9-9f45-25d2110d699e.png)

**Comment by wenzhixin** [comment]
You need to add the `table` class: https://live.bootstrap-table.com/code/wenzhixin/289
