### ISSUE TITLE
Question : how can I maintain selected data for sidepagination : server

### ISSUE THREAD

**Issue by RaghavendraG** [wenzhixin/bootstrap-table#450]
Dear Team,

  I need to maintain the the selected checkbox on pagination and search in server side pagination,
how can i achieve it .

Regards,
Raghavendra G

**Comment by wenzhixin** [comment]
referenced to #372

**Comment by wenzhixin** [comment]
Need to handle it manually, for example:
```js
var selections = [];

$table.on('check.bs.table uncheck.bs.table check-all.bs.table uncheck-all.bs.table', function () {
    // save your data, here just save the current page
    selections = $.map($table.bootstrapTable('getSelections'), function (row) {
        return row.id
    });
    // push or splice the selections if you want to save all data selections
});

function responseHandler(res) {
    $.each(res.rows, function (i, row) {
        // init your state value
        row.state = $.inArray(row.id, selections) !== -1;
    });
    return res;
}
```
Detail example: http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by wenzhixin** [comment]
Added example: Maintain selected on server side: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/917.html

**Comment by provivo** [comment]
should this also work with **client** side pagination? I tried it and the checkbox state isn't preserved

thank you
