### ISSUE TITLE
Multiple search extension replacement

### ISSUE THREAD

**Issue by ghiringh** [wenzhixin/bootstrap-table#4500]
`Hi!`

As I understand it, you made the choice not to support the multiple search extension as it can be replaced by a custom search. This make sens to me and I profoundly agree. I am now trying to replace the extension by a custom search function but I'm having some troubles. I think multi word search is very convenient for the users and is a must have for the whole bootstrap-table community

The goal is to have something like this:

```
function customSearch(data, text) {
    return data.filter(function (row) {
        if(contains any word in text and compatible with filters){
            return true;
        }else{
            return false;
        }
    })
}
```

Which means it is not just a question of adding a split(' '). We have to take filters into account. My problem is I don't know how to ensure that the filters will work with the text search. (Whether they are selected before or after text entry.)

To your knowledge, is there anyone who has already written such a function?

Thanks for your advises.

Exemple of custom search : https://live.bootstrap-table.com/example/options/custom-search.html

**Comment by ghiringh** [comment]
UPDATE 1: 

I decided to return with version 1.14.2 for more simplicity. But there is still a problem : If search query has multiple words, filters no longer applies... 

Does anybody have a customSearch function taking filters into account?

**Comment by ghiringh** [comment]
Hi, thanks for your interest. Here is what i mean by taking the filters into account.
### Context
Let's say we have the following data :

Product ID | Ingredients | Group
------------ | ------------- | -------------
1 | Apple, Banana, Egg, Sugar | A
2 | Butter, Potato, Salt | A
3 | Butter, Beer, Egg, Rice | B
4 | Apple, Beer, Salt, Sugar | B
5 | Banana, Chicken, Egg, Rice | C
6 | Apple, Butter, Pepper, Vinegar | C

Next to that we have the search bar and a checkbox filter for the groups. The search trigger the customSearch function and the filter trigger ```$table.bootstraptable("filterBy",{group:[...]})```
#### Expected behaviour
For exemple if I search :
"Apple"  (simple search)
[x] A,  [ ] B,  [x] C  (filter)
I expect the result [1,6] because [1,4,6] have apple but [4] is in the unselected group B.

As well if i search : 
"Banana Egg" (multi seach)
[ ] A,  [ ] B,  [x] C (filter)
I expect the result [5].

#### Experienced behaviour

If I have a customSearch set up, than the  ```$table.bootstraptable("filterBy",{group:[...]})``` has no influence on the data shown anymore. So if I search : 
"Apple"  (simple search)
[x] A,  [ ] B,  [x] C  (filter)
it returns [1,4,6]

and : 
"Banana Egg" (multi seach)
[ ] A,  [ ] B,  [x] C (filter)
returns [1,5]

I'll try to make a example on the online editor so you can experience the issue live.

**Comment by wenzhixin** [comment]
Fixed in #4533

**Comment by ghiringh** [comment]
Very good thank you!

**Comment by wenzhixin** [comment]
A workaround in the current version: https://live.bootstrap-table.com/code/wenzhixin/400

**Comment by ghiringh** [comment]
Yes, but if $filters is not already set (on pageload for example), search won't work. You can update $filters in customSearch function to make it work. like so https://live.bootstrap-table.com/code/ghiringh/401

**Comment by ghiringh** [comment]
Hi,

Here is the custom search function I ended with.
Maybe it will be useful for someone else too.

```javascript
function customSearch(data, query, filter) {
    opt=$table.bootstrapTable('getOptions');
    columns=[]
    opt.columns[0].forEach(function(column){
        if(column['searchable']){
            columns.push(column['field'])
        }
    });
    query = query.toLowerCase().split(' ');
    text='';
    query.forEach(function(word){
        text+='(?=.*'+word+')';
    })
    re=new RegExp(text,'i')
    return data.filter(function (row){
        check = true
        $.each(filter,function(key){
            if(!filter[key].includes(row[key])){
                check = false;
                return false;
            }
        })
        if(!check){
            return false;
        }
        values=''
        columns.forEach(function(field){
            values+=JSON.stringify(row[field]).replace(/(<[^>]*>|("|\|)|\\n)/g,'').replace(/( +)/g,' ').toLowerCase()
        })
        if(!values.match(re)){
            return false;
        }
        return true;
    })
}
```
