### ISSUE TITLE
Filter Control Cannot read property 'field' of undefined

### ISSUE THREAD

**Issue by SEModer** [wenzhixin/bootstrap-table#4503]
In release v1.15.3 there was a bug with Filter Control. Only when sidePagination: 'server'
Uncaught TypeError: Cannot read property 'field' of undefined
    at bootstrap-table-filter-control.js:1882

https://live.bootstrap-table.com/code/SEModer/295
![image](https://user-images.githubusercontent.com/789171/61441863-e88c3200-a95f-11e9-91a0-1b9373e16b4b.png)

**Comment by Redeemer1001** [comment]
I temporarily use this method to fix it. Add a new line at bootstrap-table-filter-control.js between 1880 and 1881.
> `...`
> `1880> $.each(that.header.fields, function (j, field) {`
> `*new> if (field == undefined) return;`
> `1881> var column = that.columns[that.fieldsColumnsIndex[field]];`
> `...`

**Comment by UtechtDustin** [comment]
Seems fixed since v1.15.4, as your example works with v1.15.4 and above.
If this issue still exists, please reopen the issue!
