### ISSUE TITLE
Сlear filter field, the table is not do query for update.

### ISSUE THREAD

**Issue by SEModer** [wenzhixin/bootstrap-table#4504]
In release v1.15.3 and 1.15.2 there was a bug with Filter Control. Only when sidePagination: 'server'
When I clear filter field, the table is not updated. 

https://live.bootstrap-table.com/code/SEModer/295

**Comment by wenzhixin** [comment]
Seems to work well: https://live.bootstrap-table.com/code/wenzhixin/360

**Comment by SEModer** [comment]
Sorry, this bug from cookies. Duplicate of #4158 #4466

**Comment by crochut** [comment]
> Seems to work well: https://live.bootstrap-table.com/code/wenzhixin/360

Hi, wenzhixin, it doesn't work if you add cookie extention !
The problem is these combined cases :
- filter control extention
- cookie extention 
- data-search = true

**Comment by UtechtDustin** [comment]
duplicate of #4158
