### ISSUE TITLE
在bootstrap-table加载渲染完后初始化equerry.raty有问题

### ISSUE THREAD

**Issue by jianghong3** [wenzhixin/bootstrap-table#4505]
Short and descriptive example bug report title

onPostBody:function(data){
$(.display).raty({})
}

Uncaught TypeError: $(...).raty is not a function

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by wenzhixin** [comment]
`$('.display').raty({})`

**Comment by wenzhixin** [comment]
在 #4498 这个问题已经给出了例子：https://live.bootstrap-table.com/code/wenzhixin/288
