### ISSUE TITLE
Issue : Checkbox value id is replacing to true

### ISSUE THREAD

**Issue by RaghavendraG** [wenzhixin/bootstrap-table#451]
I am using server side pagination and on select of checkbox event[onCheck]. In row parameter , data-field set for checkbox is reseting to true or false. As a result I'm not able to get the value set for the check box.

![oneventraised](https://cloud.githubusercontent.com/assets/10609084/5832100/bda245d6-a165-11e4-9f23-0aa553456a30.JPG)
![beforeselecting](https://cloud.githubusercontent.com/assets/10609084/5832101/bdd6a63c-a165-11e4-8032-42fe68c164aa.JPG)

**Comment by wenzhixin** [comment]
Hi, to solve your problem, you can set an non-exist `field` (for example `state`) to the checkbox column:
```html
<table ... data-id-field="WorkFlowStageMaserID" ...>
<th data-field="state" data-checkbox="true"></th>
```
