### ISSUE TITLE
Demo code doesnt work properly. #917

### ISSUE THREAD

**Issue by bkd** [wenzhixin/bootstrap-table#4512]
Ive checked that the demo doesnt work properly. #917

Goto page 1 of the list of results. If you check the very top checkbox, it selects all. As expected. Uncheck this and then it unselects all. As expected.

Goto the next page in the pagination navigation, then browse back to the same page and the list is still checked - we should expect the list to be Unchecked. 

If you select a single item, and unselect - this is done correctly, its just with the Unselect all - the rows are not removed from the selections array.

_Originally posted by @bkd in https://github.com/wenzhixin/bootstrap-table/issues/917#issuecomment-514750801_

**Comment by bkd** [comment]
Assuming that the column that is first to the right of the checkbox is the ID, something like this works

There is probably a better way but a quick hack for now works if we get the unchecked ids 			      

    $(function() {
      $table.on('check.bs.table check-all.bs.table ' +
        'uncheck.bs.table uncheck-all.bs.table',

        function(e, rows) {
          var ids = $.map(!$.isArray(rows) ? [rows] : rows, function(row) {
            record_type = row.obj_type;
            return row.id
          })
          if (e.type == 'uncheck-all') {
            ids = []
            $('input[name="selectItemName"]:not(:checked)').each(function(a, b) {
              ids.push(parseInt($table.find('tr[data-index="' + $(b).data('index') + '"]')
                                      .find('td')[1].innerText))
            })
          }
          var func = $.inArray(e.type, ['check', 'check-all']) > -1 ? 'union' : 'difference'
          ...
        })
    })

**Comment by wenzhixin** [comment]
Thanks for your feedback, that's because of the parameters of [checkAll and onUncheckAll](https://bootstrap-table.com/docs/api/events/#oncheckall) events have changed from v1.15.0, updated the example: https://examples.bootstrap-table.com/index.html#issues/917.html

**Comment by bkd** [comment]
Great that makes things easier ;-)
