### ISSUE TITLE
使用ajaxsetup遇到的问题

### ISSUE THREAD

**Issue by caifenglin** [wenzhixin/bootstrap-table#4513]
你好，我使用ajaxSetup给ajax请求默认值。在其他ajax请求都没问题，在bootstrap-table这里发现，ajax可以调用到ajaxSetup中的beforeSend、dataFilter但是，complete怎么都调用不到，请问是什么问题呢，有什么好的解决方法

**Comment by wenzhixin** [comment]
看看这里的答案：https://stackoverflow.com/questions/2279823/load-doesnt-trigger-ajaxsetup-complete-handler-on-complete
