### ISSUE TITLE
语言包 ie

### ISSUE THREAD

**Issue by mysmlz** [wenzhixin/bootstrap-table#4517]
![TIM截图20190730090037](https://user-images.githubusercontent.com/38951157/62092706-c3c18400-b2a8-11e9-92c5-8cec2442270f.png)
语言包的IE兼容问题,大佬看一下吧
![TIM截图20190730090317](https://user-images.githubusercontent.com/38951157/62092745-e94e8d80-b2a8-11e9-84bf-bc6a347753e3.png)

**Comment by wenzhixin** [comment]
你应该使用 dist 下的文件

**Comment by mysmlz** [comment]
> 你应该使用 dist 下的文件

谢辽,大佬
