### ISSUE TITLE
When i create new event it should be sorted as sorted as DESC modified time.

### ISSUE THREAD

**Issue by zaidmir5** [wenzhixin/bootstrap-table#4518]
<table id="tableEventCatalog" data-toggle="table" data-toolbar="#toolbarTableEventCatalog"
           data-maintain-selected="true"
           data-cache="false"  data-click-to-select="true"
           data-striped="true" data-pagination="true" data-search="true"
           data-sort-order="desc" data-sort-name="createTime"
           data-show-columns="true" data-show-refresh="true"
           data-page-size="50"
           data-response-handler="responseHandlerEventCat"
           data-page-list='[10, 20, 30, 50, 100, 200]'>

![image](https://user-images.githubusercontent.com/48056293/62107068-74894c80-b2c4-11e9-9ca2-5ce34383c43e.png)

**Comment by zaidmir5** [comment]
![image](https://user-images.githubusercontent.com/48056293/62107107-8965e000-b2c4-11e9-9790-d752e0911d45.png)

**Comment by zaidmir5** [comment]
Actual result:It is coming in random order.
Expected Resulr:  It should be  on the top of table.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Our example is working well: https://examples.bootstrap-table.com/index.html#options/sort-name-order.html.
If the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!
