### ISSUE TITLE
多列布局水平滚动条问题?

### ISSUE THREAD

**Issue by leidesen** [wenzhixin/bootstrap-table#4519]
采用H5方式初始化很多列表格时, 水平滚动条不会出现, 而采用JS方式初始化就正常, 这什么原因?

**Comment by wenzhixin** [comment]
测试了下，并没有出现你的问题哦：https://live.bootstrap-table.com/code/wenzhixin/376
或者你提供下在线运行例子？

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days if the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
