### ISSUE TITLE
Params of method resetView

### ISSUE THREAD

**Issue by DanJoeHa** [wenzhixin/bootstrap-table#452]
In the [documentation](http://bootstrap-table.wenzhixin.net.cn/documentation/#methods) of bootstrap-table the method "resetView" awaits some parameters. Could you please tell me which?

**Comment by wenzhixin** [comment]
Hi @DanJoeHa , now it can only support `height` param, for example:
```
bootstrapTable('resetView', {
    height: 400 // new height
});
```
