### ISSUE TITLE
是否有考虑移除jQuery的计划

### ISSUE THREAD

**Issue by angelfind** [wenzhixin/bootstrap-table#4521]
Bootstrap V5 正在紧锣密鼓的构建中，Bootstrap V5中已经移除了jQuery。不知道Bootstrap-Table，BootstrapTable-Vue将来会不会考虑移除jQuery。

**Comment by wenzhixin** [comment]
ref #4239 一直有计划，不过工作量比较大，等 Bootstrap V5 发布了后，我们会不断改进的。
