### ISSUE TITLE
Append method resets scroll position to top

### ISSUE THREAD

**Issue by taleteller** [wenzhixin/bootstrap-table#4524]
Calling the Append Method resets the scroll View

Assume you want to create a virtual scrolling table of unknown length that appends rows while you scroll down the visible ones. In this case you would call `bootstrapTable('append',data)` somewhat when the user scrolles towards the end. However if you do so, the visible area will jump to the start. 

This behavior can be reproduced on the [Large Data Example](https://examples.bootstrap-table.com/index.html#welcomes/large-data.html): Hit the "Append 10000 Rows" button, scroll down to the bottom. Hit the "Append 10000 Rows" again, and your view will reset to the top of the table. This is not an useful behavior for an virtual table, because you don't want the view to change for the user. 

It is possible to mitigate the issue by adding code like following, but it may cause visual issues: 
```
$scrollPos = $tab.bootstrapTable('getScrollPosition');
$tab.bootstrapTable('append', data);
$tab.bootstrapTable('scrollTo', {unit: 'px', value: $scrollPos});
```

**Comment by wenzhixin** [comment]
Fixed in #4615
