### ISSUE TITLE
Get DOM-object of current cell in column-formatter closure function?

### ISSUE THREAD

**Issue by mshoestrng** [wenzhixin/bootstrap-table#4525]
I would like to get the DOM-element of the current cell the formatter is working on from within the column formatter function.

In my case this is because I use the same options-object for two similar bootstrapTables() on the same page. It would be very convenient if I could somehow find out within the formatter in which table the formatter is currently working to change the output of the formatter function accordingly.

A possible solution in my opinion would be that you provide the DOM-Object of the current cell in the this-scope within the column formatter function (or as an argument to the formatter function), e.g. as this.cellObj. **Then** one could use it as such:

```
// ...
formatter: function() {
  var currentTable = $(this.cellObj).closest('table');

  if (currentTable[0].id == 'myTable1') {
    // ...
  }
  else {
    // ...
  }
}
// ...
```

Or is there already such a feature in bootstrapTable?

**Comment by UtechtDustin** [comment]
Should be easy to implement.
Do you think we should add the table as last parameter for each method/function or only for this one ?
@wenzhixin @djhvscf

**Comment by wenzhixin** [comment]
@UtechtDustin I don't think add the table as last parameter is a good idea.

I have tried some methods for the problem of @mshoestrng , but since our `formatter` column option returns a string and finally loads it into the body, there is no way to get the corresponding dom attribute.

A workaround: https://live.bootstrap-table.com/code/wenzhixin/790

**Comment by UtechtDustin** [comment]
@wenzhixin 
It was just a idea, i also was not sure that this is a good idea.
Then we should add the table object as parameter for the formatter, so he can add custom data attributes to the table DOM or just read the table id.

**Comment by wenzhixin** [comment]
@UtechtDustin OK, I know what you mean.

Close the issue, if the workaround can not solve the problem reopen it.
