### ISSUE TITLE
Suggestions to improve the documentation

### ISSUE THREAD

**Issue by mshoestrng** [wenzhixin/bootstrap-table#4526]
Some suggestions to improve the documentation of bootstrapTable:

- column option "sorter": please include expected return values for custom sorter function (it was only through guessing that I found out it's actually -1, 0, 1)
- table options/column options/events/methods: please sort the options/methods in alphabetical order - also in the index in the right column (it's very tedious to scan for a certain option in random order)
- add to each option/method in which version it was added. Also if additional parameters were added in later versions please note accordingly (it has happened more than once that I tried for ages to use a certain option only to finally look into the bootstrapTable source code to find out that it is not yet included in the version we use)

Much appreciated!

**Comment by djhvscf** [comment]
Thanks a lot for your feedback

**Comment by UtechtDustin** [comment]
Thanks for the feedback, but i guess we should not show the version where the option/method was added. Instead of that we should have a select which shows the documentation for the selected version.

@djhvscf @wenzhixin 
Should be possible through the git tags or not ?
