### ISSUE TITLE
Hide table, then onload show table, Resizable doesnt work

### ISSUE THREAD

**Issue by bkd** [wenzhixin/bootstrap-table#4527]
I'd finding that if I have say 50 cols, when I load the table I get an unclean table header all across the page, then when the table loads it formats. 

I dont want to show the preloaded table at all, so opted for the "d-none" or "display:none" then 
` <table id='people' class='d-none'....`

used 
`       $table.on('load-success.bs.table', function (){
           $(this).removeClass('d-none')
         }); 
 `

but seems to break the Resizable columns.

**Comment by bkd** [comment]
A workaround is to apply the d-none to the <th> element text instead 
```
<div class="d-none">
   First name
</div>
```

then remove this on the load

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!
