### ISSUE TITLE
$.load()  bootstrap-table  html. the showColumns button sometimes useless

### ISSUE THREAD

**Issue by ChengXu2016** [wenzhixin/bootstrap-table#4529]
please help me
When I use the jquery.load() method to dynamically load a page, the showtrap-table's show/hide columns are sometimes not clickable, and the drop-down list is unrealistic. Call load() repeatedly, dropdown list dropdown-menu the previous time if the display is successful, the next time will not work, and so on.

当我用jquery.load()方法动态加载页面时，bootstrap-table的显示/隐藏列有事后不能点击，下拉列表不现实。 反复调用load()，下拉列表dropdown-menu前一次如果显示成功，后一次就不行，如此反复。
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/22406905/62408895-0c0ed800-b602-11e9-9e1f-36c42f2ef779.png">
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/22406905/62408920-509a7380-b602-11e9-8981-786a3de84039.png">
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/22406905/62408951-d6b6ba00-b602-11e9-9830-5deaa5e191bd.png">

**Comment by wenzhixin** [comment]
platform/test 的完整代码是怎样的呢？

**Comment by ChengXu2016** [comment]
就是图二，图一动态加载图二，bootstrap-table的显示/隐藏列有时候不能点击显示下拉列，一次可以一次不可以，如此反复。   如果我不用load加载，直接打开那个页面没有这个问题。  说明是load()与bootstrap-table之间的问题。 感谢🙏你的回复

**Comment by wenzhixin** [comment]
使用 `$.load` 的话，你试下把引入的 js 和 css 放在外面（也就是使用 load 的页面）

**Comment by ChengXu2016** [comment]
thanks,感谢你的回复

**Comment by ChengXu2016** [comment]
问题解决了，谢谢
