### ISSUE TITLE
print extension : toolbar print button appears twice if search is also active

### ISSUE THREAD

**Issue by yodine** [wenzhixin/bootstrap-table#4530]
Hi,

If you use both search and print in your table :
```
<table  id="table"
data-search="true"
data-show-print="true"
...
```

Then the print button appears twice : one at the end of the search input (bug) and the other one in the toolbar (as expected).

It seems that it searches all elements with class btn-group and the search field also contains one.
I solved by changing line 1807 of file bootstrap-table-print.js to :
`var $btnGroup = this.$toolbar.find('>.btn-group').first();`

That might not work in all cases. First I added .not('.search') but saw the same trouble in multi sort that was solved by first(). But I wonder if the correct button place will always be the first.

Thanks

**Comment by wenzhixin** [comment]
Fixed in #4531
