### ISSUE TITLE
data-visible -- Cannot read property 'field' of undefined

### ISSUE THREAD

**Issue by jmm13** [wenzhixin/bootstrap-table#4532]
Hello- 

I just upgraded to 1.15.3 from 1.14.2. I am noticing an issue when using the data-visible column option with the bootstrap-table-filter-control extension.

If you're referencing the bootstrap-table-filter-control extension, any columns you designate as data-visible=false will throw an "Uncaught TypeError: Cannot read property 'field' of undefined".

I made an [Example](https://live.bootstrap-table.com/code/jmm13/395) to show the problem.

I'm not sure if I'm doing something else wrong, or if there's perhaps a conflict/bug in the extension. Any advice would be appreciated, because I have an application that uses both the filter-controls and hides some columns. It worked fine in 1.14.2.

Thanks!

**Comment by jmm13** [comment]
Couple of updates that I've found:

- It only seems to happen when you have a column with data-visible=false followed by columns that are displayed.  If you data-visible=false the last column, the error doesn't occur. 
- It does not seem to be related to #4503 -- I'm not using server-side pagination and still encountering the error

**Comment by wenzhixin** [comment]
Thanks for the feedback, this bug has been fixed in the develop branch.
CDN: https://live.bootstrap-table.com/example/extensions/filter-control.html
develop: https://live.bootstrap-table.com/code/wenzhixin/396
