### ISSUE TITLE
Feature: allow Extensions to add request parameters

### ISSUE THREAD

**Issue by taleteller** [wenzhixin/bootstrap-table#4535]
Assuming I want to write an extension with server paging / searching that has a more detailed searching functionality. For example a dropdown to specify the column I want to search in or a checkbox flag that is not part of the returned data. This information has to be incorporated into the query parameters. 

Now on a finished `.bootstrapTable()` instance I can manipulate the parameters prior request by specifying `options.queryParams`. But for an extension this is not a valid way. The parameters are getting compiled and requested within `bootstrapTable.initServer()`. There is no way to intercept them from an Extension at all. 

As a Workaround I incorporate parameters via `filterColumnsPartial` since they get passed over as `filter`. However this is not ideal, my proposal would be to add something like this into `initServer()`:

```
$.extend(params,this.$requestParams);
```
Where `this.$requestParams` initializes as `{}`. The more complex solution would be to move the preparation of the query parameters to an own method that can be overridden prior issuing the ajax request.

**Comment by wenzhixin** [comment]
The `initServer` method has `query` parameter, I think this can solve your problem.
```
initServer (silent, query, url)
```

**Comment by taleteller** [comment]
Thanks, now i see how `query` is processed. I think we can close this.
