### ISSUE TITLE
buttonsClass doesn't apply classes to serach buttons (searchButton, clearSearchButton)

### ISSUE THREAD

**Issue by DSpade-r** [wenzhixin/bootstrap-table#4536]
I want to change button classes to outline-secondary for example.
Option 'buttonsClass' works fine for basic buttons for 'showColumn', 'showToggle' etc., but doesn't change classes for 'searchClearButton' 'searchButton'. 
Can I do it somehow from js?

**Comment by wenzhixin** [comment]
Fixed in #4537
