### ISSUE TITLE
search without class and div 

### ISSUE THREAD

**Issue by anneyangyue** [wenzhixin/bootstrap-table#4539]
when td container 'div' or 'class', onSearch fuction will match 'div' and 'class' not only data

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/column-options/#searchformatter
https://examples.bootstrap-table.com/index.html#column-options/search-formatter.html

**Comment by anneyangyue** [comment]
Thank you very much. The problem has been solved.
