### ISSUE TITLE
filter-control劫走焦点，x-ediable失效，

### ISSUE THREAD

**Issue by zhiyuazo** [wenzhixin/bootstrap-table#4543]
bootstrap-table 实现父子表，父表和子表的每行都支持编辑。
引入filter-controll插件后， 可以筛选出感兴趣的父表行数据，
选择一行展开查看此行子表，
单击子表单元格，弹出编辑对话框，焦点自动被filter-control劫走..
不能编辑，
奇怪的是，这种情况只有 filter-control 插件进行了一次filter,然后对子表编辑会产生影响..

-----------

I use bootstrap-table to achieve parent-children table...
Both ROWs in parent-table and children-table can be editable via X-editable plugin.
things gone well until :

    I use filter-control-plugin to choose some special ROWs of parent-table..
    Then I expand one row to display its children-table
    I click the editable in children-table
    The 's modify-dailog was popup...
    finally, the dialog lose focus, the filter-conrol grab the focus...
    I can not edit the in children-table ,
    how to resolve this?

**Comment by wenzhixin** [comment]
麻烦提供下例子。
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by zhiyuazo** [comment]
唉，得今晚回去手敲.....

**Comment by zhiyuazo** [comment]
@wenzhixin   Hi,  
https://live.bootstrap-table.com/code/zhiyuazo/438    this is online demo 
please use filter-contol to get one row of parent , the expand this row, to show it's child-table , 
then , edit the <td> in  child-table, the issue will appear.... 
as summary, 3 scenarios ,  
1, If  no use filter-control, the editable function for both parent-table and child-table
如果不使用filter-control, 编辑功能没有问题
2. Select One row of parent-table with filter-control, the editable function is OK with parent-table   
如果使用filter功能，再筛选出来的父表行上, 进行编辑没有问题。
**3. Select One row of parent-table, then expand it to show it's child-table, the editable function not Work OK  with child-table....**    
如果使用filter功能，展开筛选的父表行数据，然后编辑子表内容，工作失败， filter-control插件会一直获取焦点，导致编辑内容失效....

**Comment by zhiyuazo** [comment]
@wenzhixin   ,  
源码里面有这么一段：好像是5046还是3056行（记不清了） bootstrap-table-editable.js 中
`	if (e.type === 'click' && _this8.options.detailViewByClick) {
          _this8.toggleDetailView(rowIndex, _this8.header.detailFormatters[index]);
}`

然后我在子表options里面 设置`detailViewByClick=false`
问题消失....
或者源码方面有必要改进吗？

**Comment by wenzhixin** [comment]
那应该不是问题，`detailViewByClick` 默认是 `false`，你子表没有 `detailView` 不应该设置这个值的：https://live.bootstrap-table.com/code/wenzhixin/443

**Comment by zhiyuazo** [comment]
@wenzhixin   ,  
好的  issue can be resolved ...非常感谢！
