### ISSUE TITLE
关于bootstrap-table(vue)中的column options -> formatter的问题

### ISSUE THREAD

**Issue by ss7424Refar** [wenzhixin/bootstrap-table#4544]
你好，大佬。
问下我想在自定义的一列【操作】中添加一个【取消申请】的按钮，这个按钮有个onclick方法，调用的是自定义的cancel方法，我试着把这个cancel加载methods中和mount里面，也定义全局的方法引入这个cancel方法，
但是在vuecli3中提示找不到Uncaught ReferenceError: cancel is not defined，at HTMLAnchorElement.onclick (VM6774 main:1)

有什么方法可以自定义列中引入这个cancel方法吗?

代码如下:
```
    <BootstrapTable ref="table" :columns="columns" :options="options" @onDblClickRow="onDblClickRow"></BootstrapTable>
```

```
  export default {
    data () {
      return {
          columns: [
           ...
            {
             field: 'op',
             title: '操作',
             formatter: function (value, row) {
               var flag = row['op'];
               if ('apply' === flag) {
                  return '<a onclick="cancel()">取消申请</a>'
               }else {
                 return '<a href="#">-</a>'
              }
            }
          }
        ],
      }
  
```

**Comment by wenzhixin** [comment]
用 events 可以解决问题：
https://live.bootstrap-table.com/code/wenzhixin/415

**Comment by ss7424Refar** [comment]
好的，谢谢。

顺便问下， 我引入了[bootstrap-vue](https://bootstrap-vue.js.org/)的一个`<b-button>`[组件](https://bootstrap-vue.js.org/docs/components/button)想加入这个column中, 但是F12打开浏览器的时候看到的还是原原本本的`<b-button>...</button>`。

请问有什么方法吗?

代码如下
```
formatter: function (value, row) {
    var flag = row['op'];
    if ('apply' === flag) {
        return  '<b-button href="javascript:" class="cancel"><i>取消申请</i></b-button>'
    }else {
        return '<a href="#">-</a>'
    }
}
```

**Comment by wenzhixin** [comment]
目前还不支持，不过你可以参考下这篇文章： https://segmentfault.com/a/1190000019115038

**Comment by wenzhixin** [comment]
针对你的问题进行了研究和试验，发现是可行的： https://blog.wenzhixin.net.cn/2019/08/10/formatter-use-vue-component/

**Comment by wenzhixin** [comment]
Add an English blog: https://blog.bootstrap-table.com/2019/08/10/formatter-use-vue-component/

**Comment by ss7424Refar** [comment]
不好意思, 回晚了. 那天看到了, 想过几天回的, 现在才从坑里面爬出来。

我一开始用的vuecli3， 它安装好的时候在App.vue中使用的是如下代码.
`import Vue from 'vue'`

这个我刚查看了环境变量vue$别名成了`vue/dist/vue.runtime.esm.js`.

而你这边提交在[vue-starter](https://github.com/wenzhixin/bootstrap-table-examples/tree/develop/vue-starter)中的代码引入是`vue/dist/vue.esm.js`

然后我把`main.js`, `router.js`, `mixins/table.js`, `plugins/table.js`中的 `import Vue from 'vue'`改成`import vue/dist/vue.esm.js` , <b-button>按钮才出现了。。

不过bootstrap-vue会在控制台报一个warning `(Multiple instances of Vue detected)`。当点击按钮的时候会报`$attr and $listeners is readonly`,
这个将vue$ alias就可以了, [Aliasing Vue import](https://bootstrap-vue.js.org/docs/#using-module-bundlers)

### vuecli3设定 (vue.config.js)
```
 module.exports = {
   ...
    configureWebpack:{  // 覆盖webpack默认配置的都在这里
        resolve:{   // 配置解析别名
            alias:{
                vue$:'vue/dist/vue.esm.js'
            }
        }
    }
}

```

**Comment by wenzhixin** [comment]
是的，在那篇文章的最后也写了：

> *需要注意的是：*

> 由于 `new Vue({ template })` 需要 `full` 版本，假如在 `webpack` 中使用的话，需要修改所有的 `vue` 的导入：`import Vue from 'vue/dist/vue.esm.js'`

不过你提供的在 `vue.config.js` 中配置的方法更方便，已经更新到例子中去了，谢谢。
