### ISSUE TITLE
data buttons are duplicated when using filter control & hiding columns

### ISSUE THREAD

**Issue by dathor-ghub** [wenzhixin/bootstrap-table#4546]
data buttons are duplicated when using filter control & hiding columns.

I have recently updated bootstrap-table versions to v1.15.3 and i find that data buttons on a table are duplicated (they are shown twice).

I have traced this to an interaction between the filter extension and hiding columns using data-visible = false.  If i do not hide any columns the buttons are not duplicated.  As soon as i hide any column the buttons are duplicated.

I have replicated the problem here in a live example.
online example -> https://live.bootstrap-table.com/code/dathor-ghub/444

**Comment by wenzhixin** [comment]
Thanks for your feedback, this bug has been fixed in the develop branch:
https://live.bootstrap-table.com/code/wenzhixin/445
We will release a new version soon.

**Comment by wenzhixin** [comment]
[v1.15.4](https://bootstrap-table.com/news/#bootstrap-table-1154) released.
