### ISSUE TITLE
How can I use the data-url with codeigniter

### ISSUE THREAD

**Issue by lynxnomad** [wenzhixin/bootstrap-table#455]
Can I use url=data passing a  using codeiginter passing my controller/method?

**Comment by wenzhixin** [comment]
Sorry @lynxnomad , it seems do not support, referenced to #375.

**Comment by lynxnomad** [comment]
Understand, but when u said to (on referenced #375) to write a separate php file u meant just a regular text file or putting the function inside that file ?And if is a regular txt inside a php is any format it has to have the same format as your JSON files in the examples?
