### ISSUE TITLE
vue-bootstrap-table sortable and advanced search not working 

### ISSUE THREAD

**Issue by JKRomero** [wenzhixin/bootstrap-table#4551]
Ive been using vue-bootstrap-table and I set the sortable=true in options object. Same thing can be said on advancedSearch which is set to true.

here is my code for the option object :
      options: {
        search: true,
        showColumns: true,
        height: "500",
        sortable: true,
        pagination: true,
        clickToSelect: true,
        detailView: false,
        detailViewIcon: false,
        detailViewByClick: true,
        advancedSearch: true,
        idForm: "advancedTable",
        toolbar: "#toolbar",
        buttonsAlign: "left",
        buttonsClass: "primary",
        toolbarAlign: "left",
        detailFormatter: this.detailFormatter(),
        classes: "table table-sm table-hover",
      }

 and here is the output. As you can see on screenshot, There is no sort button on each columns and advancedSearch button is not displayed.

![Screen Shot 2019-08-22 at 10 48 54 AM](https://user-images.githubusercontent.com/29651638/63482175-837dac00-c4ca-11e9-9850-fba4f8321b22.png)

am I missing something that causes the sortable and advancedSearch not to work?

**Comment by wenzhixin** [comment]
[sortable](https://bootstrap-table.com/docs/api/column-options/#sortable) is column option: https://examples.bootstrap-table.com/index.html#options/table-sortable.html

**Comment by JKRomero** [comment]
> [sortable](https://bootstrap-table.com/docs/api/column-options/#sortable) is column option: https://examples.bootstrap-table.com/index.html#options/table-sortable.html
> 
> Live example: https://live.bootstrap-table.com/code/wenzhixin/494

Your example worked. Also the advanced toolbar/search worked now on my end. Ive added 'import 'bootstrap-table/dist/extensions/toolbar/bootstrap-table-toolbar.js' on main.js

Thanks!
