### ISSUE TITLE
how to change header when print table

### ISSUE THREAD

**Issue by AhmedHelal90** [wenzhixin/bootstrap-table#4556]
hi there , i face a problem while printing the table when click on print Icon  on table 
there is a default header appear on report  like this 
Printed on: Mon Aug 26 2019 10:24:43 GMT+0200 (Eastern European Standard Time)

 i need to remove this line and add a custom header in print page 

thanks in advance

**Comment by wenzhixin** [comment]
You can use `printPageBuilder` option to custom your print page builder.
Example: https://live.bootstrap-table.com/code/wenzhixin/510

**Comment by AhmedHelal90** [comment]
thanks for your reply , 

its worked now very well , i really see this function in tutorials , but they don't explain example for how to use it , 
so your code is very helpful , thank you very much

**Comment by rmarzocchi84** [comment]
Solved. 

i like to change my title on the basis of a select in the page. 

So I add this javascript before defining the 
var table 


```
var materiale1='';

  $('#materiale').change(function() {
    materiale1= $( "#materiale option:selected" ).text();
});

var $table = $('#percorso');

                $(function() {
                    $table.bootstrapTable({
                    printPageBuilder: function (table) {
                        return `
                <html>
                <head>
```
[...]

```
<body>
<div id="titolo_stampa"> <h3>Stampa percorso bilaterale - Rifiuto `+materiale1+` </H3></div>
<div class="bs-table-print">${table}</div>
</body>
```

**Comment by davidbarman** [comment]
Any thoughts how to print the heading on each page, instead of only the first one?
