### ISSUE TITLE
data-height - UI glitch with more than one table?

### ISSUE THREAD

**Issue by Ka7ut0** [wenzhixin/bootstrap-table#4558]
Hello 

I've noticed a small glitch when using tabs to display different bootstrap-table objects
In short, the first table renders correctly, but all the others don't respect the data-height and the bottom parts overflowing the table cells and a scrollbar coming out of nowhere when the table is empty.

The additional tables only render correctly after 'opening' the tab a second time.

Basically this behavior: 

![ezgif-3-d15d17805a33](https://user-images.githubusercontent.com/47562131/63746799-ecd43500-c8a5-11e9-93de-dfeabbab3cb0.gif)

Here is the corresponding [JSFiddle](https://jsfiddle.net/qf5wzt02/)

**Comment by wenzhixin** [comment]
You need to use [navs events](https://getbootstrap.com/docs/4.3/components/navs/#events) to solve the problem:

Before: https://live.bootstrap-table.com/code/wenzhixin/512
After: https://live.bootstrap-table.com/code/wenzhixin/513

**Comment by Ka7ut0** [comment]
Thank you very much Mr. wenzhixin
I was completely ignorant about using nav events instead.
