### ISSUE TITLE
does filter-control plugin support custom-filter-algorithm?

### ISSUE THREAD

**Issue by zhiyuazo** [wenzhixin/bootstrap-table#4559]
Hi WenZhiXin, 
i read filter-control Doc, 
and not found the custom-filter-algorithm support, 
is right?

**Comment by UtechtDustin** [comment]
Currently there is no method which allows filtering with a custom algorithm.
But maybe the [filterBy](https://bootstrap-table.com/docs/api/methods/#filterby) method is enough ?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 Days, if you still need help please reopen the issue.
