### ISSUE TITLE
space on table header and static scrollbar appearing in windows (chrome)

### ISSUE THREAD

**Issue by ischyron** [wenzhixin/bootstrap-table#456]
see the visual
![image](https://cloud.githubusercontent.com/assets/8192892/5851390/74f910ae-a22c-11e4-8ab0-3560d048c8f4.png)

this was tested in windows on chrome

**Comment by wenzhixin** [comment]
Hi @ischyron , this problem is not a bug, because we need to fix the table header.

If you change the `th` background, you just only to set the same background color of `.fixed-table-header` to solve this problem.
