### ISSUE TITLE
Page List

### ISSUE THREAD

**Issue by Vadyanga** [wenzhixin/bootstrap-table#4560]
Hello

`$('#bstable').bootstrapTable({`
`pageSize: 5,`
1. pageList: [20,50,200,2000],
1. pageList: [10, 25, 50, 100, 200, 'All'],
1. pageList: '[10, 25, 50, 100, 200, All]',
1. "pageList":"[10, 25, 50, 100, 200, All]",

`pagination: true`
`});`

I can't set the value above 100. The table takes a value greater than 100 as the last one, and does not read the array further. I'm running code by this (code above) variation. I want set pageList to [10, 20, 50, 200, 400, 1000, 2000, 'All'], is there any way I can do that with this datatable?

[photo1 + redLine + photo2](https://imgur.com/NRhXSvY)
photo1 = Options from [here](https://live.bootstrap-table.com/example/options/page-list.html)
photo2 = Above code running (on my side\site)

**Comment by wenzhixin** [comment]
What is the total number of your table? 
I think it should be less than 100, so our table will hide `200, 400, 1000, 2000, 'All'` list smartly.
https://bootstrap-table.com/docs/api/table-options/#smartdisplay
https://examples.bootstrap-table.com/#options/smart-display.html

**Comment by Vadyanga** [comment]
Thanks

Solution is: 
`smartDisplay: false,`

I think, would be good to refer to this feature in 'pageList'
