### ISSUE TITLE
How to set default page number in bootstrap-table plugin

### ISSUE THREAD

**Issue by umairakhtar52** [wenzhixin/bootstrap-table#4561]
How to set default page number in bootstrap-table plugin

I want to set default page number in bootstrap-table plugin so that if i have made some changes on specific page and after change pages refereshes the pagination should take to the desired page .

**Comment by wenzhixin** [comment]
Do you mean `[pageSize](https://bootstrap-table.com/docs/api/table-options/#pagesize)` option?
Example: https://examples.bootstrap-table.com/index.html#options/page-size.html

**Comment by martinbarilik** [comment]
I think he meant what he have written, page number. Something linke table.bootstrapTable({pageNumber: 2}) -> this is not currently working

**Comment by wenzhixin** [comment]
`pageNumber`: https://examples.bootstrap-table.com/index.html#options/page-number.html
