### ISSUE TITLE
how to use with jquery-generated table

### ISSUE THREAD

**Issue by pneumatic-b** [wenzhixin/bootstrap-table#4569]
I'm populating the table with data, using $('#tbody').append('some html table rows')
when I try to sort or change columns, the table ignores the data and displays "No matching records found"

here's the simple fiddle https://jsfiddle.net/9jnwdyc6/1/

I don't want to refactor data formatting to use json instead of .append().
What should I do to make the table sortable and searchable? Please provide usage example
I've searched older issues and found several similar cases unanswered, for example 
https://github.com/wenzhixin/bootstrap-table/issues/3261

thanks

**Comment by wenzhixin** [comment]
@pneumatic-b you use [`load`](https://bootstrap-table.com/docs/api/methods/#load) and [`apeend`](https://bootstrap-table.com/docs/api/methods/#append) methods to do what you want, examples: https://live.bootstrap-table.com/code/wenzhixin/629 and https://live.bootstrap-table.com/code/wenzhixin/630.

**Comment by pneumatic-b** [comment]
this solution works, but it equals to total refactoring of the server-side code to pass arrays of objects to the table, instead of passing the html of the table rows. I ended up doing that, but I wish there was a different solution.

**Comment by wenzhixin** [comment]
In fact, using table rows is much more efficient than using html generated.
