### ISSUE TITLE
Table defaults are being ignored

### ISSUE THREAD

**Issue by Furburger** [wenzhixin/bootstrap-table#457]
I have set the global defaults for the table, but they seem to be ignored.

If I set them like this:

    $.fn.bootstrapTable.defaults = $.extend({}, $.fn.bootstrapTable.defaults, {
		method:				"post",
		sidePagination:		"server",
		contentType:		"application/x-www-form-urlencoded; charset=UTF-8"
    });	

It still sends a GET instead of a POST. In fact all settings in the global defaults seem to be ignored.

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#457.html

**Comment by Furburger** [comment]
Awesome - thanks
