### ISSUE TITLE
detailViewByClick without detailViewIcon conflicts with custom action buttons

### ISSUE THREAD

**Issue by mkbit** [wenzhixin/bootstrap-table#4570]
I have a table that has enable detailViewByClick and one column contains buttons with events for custom actions. The detailViewIcon is disabled to meet my design requirements.

One column contains buttons and has events attached to them like this.
```
<button type="button" class="remove" href="javascript:void(0)" title="Remove">Remove</button>'
```
```
events: {
    'click .remove': function(e,...){
       e.stopPropagation() // prevent detail view toggle on action
    }
}
```

If the detailViewIcon option is set to false the click event of the button is never triggered. With detailViewIcon set to true it works.
The reason it works with detailViewIcon is this code
 ``` 
if ($td.find('.detail-icon').length) {
  return
}
```

As a solution to this problem is suggest a new option for each column that disables detailViewByClick for this column. e.g. column.detailViewByClickEnabled which is true by default, but still requires detailViewByClick  to be true.

If this is a good way to solve this problem, i will create a pull request.

**Comment by UtechtDustin** [comment]
Would be nice if you could provide an example of the issue (using our [Editor](https://live.bootstrap-table.com/).

**Comment by UtechtDustin** [comment]
I close this issue because we got no response/example within 7 days.
If you still need help please reopen the issue.
