### ISSUE TITLE
how to add features of export using bootstrap version 1.8.1

### ISSUE THREAD

**Issue by AhmedHelal90** [wenzhixin/bootstrap-table#4573]
i using old version of bootstrap table v1.81 
i need to add export options in tag of table like this 

data-export-options='{
         "fileName": "Devices", 
         "ignoreColumn": ["state"],
          "exportDataType": "all"
       }'
to export all records of table not just viewed in pagination 
and for this 
data-export-options='{
         "fileName": "Devices", 
         "ignoreColumn": ["state"],
          "exportDataType": "all"
       }'

it only apply filename change but not export all fields and not ignore column "state"

**Comment by wenzhixin** [comment]
The [latest version](https://bootstrap-table.com/news/) is 1.15.4, we are no longer maintained for the too old version, can you upgrade the version?

**Comment by AhmedHelal90** [comment]
its hard to upgrade to last version for me , is there any way to make this

**Comment by djhvscf** [comment]
We are no longer maintained for the too old version. Please upgrade to the latest version

**Comment by AhmedHelal90** [comment]
i upgraded to new version and i have a problem   in table alignment 
please check case below 
https://github.com/wenzhixin/bootstrap-table/issues/4622

**Comment by wenzhixin** [comment]
@AhmedHelal90 I am working on that issue.
