### ISSUE TITLE
a bootstrap-table inside a form doesn't maintain changed values on sort

### ISSUE THREAD

**Issue by andyp05** [wenzhixin/bootstrap-table#4574]
I embedded a html table inside a form and make it a BT:

```
<form id="entryform" action="" method="post">
  <div class="bootstrap-table bootstrap4">
    <table id="table" data-sortable="true" data-sort-stable="true" data-toggle="table">
``` 
The body contains input fields.

```
<tbody>
  <tr data-index="0">
    <td style=""><input type="text" name="form-0-label" value="N29" maxlength="25" id="id_form-0-label"></td>
    <td style=""><textarea name="form-0-desc" cols="40" rows="4" maxlength="500" id="id_form-0-desc">Enrolled at 18 weeks</textarea></td>
    <td style=""><input type="text" name="form-0-location" value="Room 261" maxlength="50" id="id_form-0-location"></td>
```

If the values are sent in to the html on page load, the sort works fine. 
If I enter new values into a blank form or edit existing values and then sort, all edits are lost. 

Thanks for you help.

**Comment by djhvscf** [comment]
It happens because the table is recreated

**Comment by andyp05** [comment]
Right now:
1. The html table is rendered and boostrap-table does it's magic.
2. The user enters some data.
3. The user sorts a column.
4. The data the user entered disappears.

How do I update the bootstrap-table internal data storage to reflect user input? So that when the user sorts on a column the data they entered is preserved.

**Comment by djhvscf** [comment]
I think you can save the values (local storage, session storage) and after the sort action is completed you set the values again

**Comment by wenzhixin** [comment]
You need to save the value after input changed, ref: #987, #4221.
Example: https://examples.bootstrap-table.com/index.html#issues/987.html
