### ISSUE TITLE
Event name should be lowercase in the file named bootstrap-table-vue.js?

### ISSUE THREAD

**Issue by li1075183214** [wenzhixin/bootstrap-table#4575]
I find your example can't run normal !
![227](https://user-images.githubusercontent.com/31616577/64308291-51407400-cfcb-11e9-8275-e4f88fbe5071.jpg)
![229](https://user-images.githubusercontent.com/31616577/64308552-3de1d880-cfcc-11e9-8495-63262ed5a87f.jpg)

**Comment by BarryHauser** [comment]
I have the same issue it dosent work im trying to do the onCheck event the method never gets called

**Comment by BarryHauser** [comment]
I saw a place that you added the vueFormatter but it seemed to be that you only need it if your adding a formatted html. But with listening to the built in events you should be able to listen to them using the `@onEvent="func"` syntex

**Comment by wenzhixin** [comment]
Fixed in #4638
