### ISSUE TITLE
change the position of the filter

### ISSUE THREAD

**Issue by buptchk** [wenzhixin/bootstrap-table#4576]
Hello
I'am using bootstrap-table-filter-control,but i want to change the position of the filter input or filter select , what should i do?

**Comment by djhvscf** [comment]
What do you mean for position? Instead of header table in a different place?

**Comment by buptchk** [comment]
yes. I m in trouble with it

**Comment by djhvscf** [comment]
This is not supported. Marked as feature

**Comment by UtechtDustin** [comment]
Im working on it, somestuff already work (https://live.bootstrap-table.com/code/UtechtDustin/1015).
