### ISSUE TITLE
Default search and filterControl search bug

### ISSUE THREAD

**Issue by gumacuk15** [wenzhixin/bootstrap-table#4578]
Hello

FilterControl (filterControl: true) works correctly without default search (search: false)

FilterControl (filterControl: true) works incorrectly with default search (search: true) : 

**When I remove search text / selected values from filtercontrol inputs (empty all), then data is not changed back, but still filtered by prev search text from filtercontrol (bug only with search: true, else it changes data back on empty inputs correctly)**, also problem with cursor changing automatically position from default search to filtercontrol inputs (if you search first by filter inputs and then go to default search it will change cursor back to filter input)...

Tested on latest Chrome.

**Comment by gumacuk15** [comment]
Also, please update file bootstrap-table.js, because it has an errors:
Cannot convert object to primitive value and so on...

bootstrap-table.min.js - works correctly.

**Comment by djhvscf** [comment]
Please provide an example of this problem

**Comment by wenzhixin** [comment]
No problems found through testing, please provide a complete example.

**Comment by gumacuk15** [comment]
While testing I found that with extension "cookie" is that bug...

https://live.bootstrap-table.com/code/gumacuk15/535

**Comment by gumacuk15** [comment]
Also please look bug with cursor change automatically its position...

![bug](https://user-images.githubusercontent.com/10724655/64506733-46deec80-d2e1-11e9-94f9-9c57e73017e4.gif)

**Comment by manukieli** [comment]
I've the same issue.

**Comment by UtechtDustin** [comment]
https://github.com/wenzhixin/bootstrap-table/commit/62dfe6a3
This commit is the cause of the issue, @wenzhixin any idea ?

**Comment by Lucipher** [comment]
The same issue~~ @wenzhixin
