### ISSUE TITLE
Jumping to a newly inserted row 

### ISSUE THREAD

**Issue by Furburger** [wenzhixin/bootstrap-table#458]
When I add a new row to the table, there is no method to jump to the newly inserted row.

Most JQuery tables have a “Find” method or something similar to select a row (even if it may be on another page).

Please can you add this method to the API? 

I think you will find many users will need something like this.

**Comment by wenzhixin** [comment]
Try this: `$table.bootstrapTable('scrollTo', 'bottom');`, but it doesn't support pagination.

**Comment by Furburger** [comment]
Hi

That won’t help, but I can solve it on the server side – thanks anyway.

Rick

**Comment by dabros** [comment]
related: #535

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/693
