### ISSUE TITLE
Click row on virtual scroll

### ISSUE THREAD

**Issue by nomorna** [wenzhixin/bootstrap-table#4580]
I used the "LargeData" example, I added this line all the time, I noticed that all the mouse commands do not work.

$table.bootstrapTable({
      data: getData(20),
      onClickRow: function () {
        alert('click');        
      }
}) 

this example does not work after adding rows.

thank you.

**Comment by djhvscf** [comment]
Could you please add an fiddle with your problem?

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/533

**Comment by nomorna** [comment]
Hi wenzhixin,

I tried a working example, but I think there is a problem, or the problem is me.

try this:

1) Run your example (https://live.bootstrap-table.com/code/wenzhixin/533)
2)Click on row in tenth position (work ok)
3)load 10000 row
4)scroll to bottom
5)click any row (not work in my example)
6)scroll to top
7)Click on row in tenth position (not work)

I use edge in windows and safari on macOS 

Thank You.

**Comment by wenzhixin** [comment]
Fixed in #4617
