### ISSUE TITLE
Resize table responsively as the parent size changes

### ISSUE THREAD

**Issue by gmagno** [wenzhixin/bootstrap-table#4583]
Hi,

Is there any way I can make the table resize responsively? I have a table inside a card, and would like the table to resize as the card size changes. Here's the lower left-hand corner of my page:

![image](https://user-images.githubusercontent.com/46817915/64481251-af797c80-d1ae-11e9-8900-b90bc474833e.png)

When using "standard" bootstrap everything works fine:

```html
<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>
```

But adding `data-toggle="table"` breaks it.

Cheers,

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close the issue because we got no response within 7 days, if you still need help please reopen the issue and provide us an example.
