### ISSUE TITLE
fixed columns select all problem

### ISSUE THREAD

**Issue by twtyjvkg** [wenzhixin/bootstrap-table#4584]
![image](https://user-images.githubusercontent.com/26063786/64498534-7264d580-d2e7-11e9-9ccd-dc254d605863.png)

click the selectAll checkBox of fixed header, all rows has been selected, but the checkBox doesn't change

**Comment by djhvscf** [comment]
Which version are you using?
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by twtyjvkg** [comment]
the version is 1.15.4, demo:https://examples.bootstrap-table.com/#extensions/fixed-columns.html
