### ISSUE TITLE
Bootstrap-table multiple-sort

### ISSUE THREAD

**Issue by gumacuk15** [wenzhixin/bootstrap-table#4585]
Hello

bootstrap-table-multiple-sort extension.

Can you add method something like: 
doMultipleSort([{sortName: “name”,sortOrder:”desc”},{sortName:”last_name”,sortOrder:”desc”}]); //so people can make own popups and so on...

That extension cannot be used without bootstrap.js and bootstrap.css added (why? too bad solution). Can you make it more flexible, it should work without default bootstrap too...

**Comment by wenzhixin** [comment]
> it should work without default bootstrap too

Do you mean use other themes?

**Comment by gumacuk15** [comment]
> > it should work without default bootstrap too
> 
> Do you mean use other themes?

Not themes.
It should have own simple style to work, not using bootstrap.css ja bootstrap.js.

Now it's work depends only on whether you've added bootstrap.css and bootstrap.js. But for example, I don't want to use all bootstrap.css and js on the page, only bootstrap-grid.css. Only this plugin has such dependencies.

**Comment by wenzhixin** [comment]
Yes, bootstrap-table now only support these themes: https://bootstrap-table.com/themes/
ref #4364
