### ISSUE TITLE
fixed-columns -> row mismatch on expand when scrollPosition <> 0

### ISSUE THREAD

**Issue by aloggnet** [wenzhixin/bootstrap-table#4587]
Using fixed-columns extension, if scrollPosition <> 0, the fixed columns mismatch the rest of the table. 

To reproduce the issue, scroll vertically through the table and click on a row.

The rows simply get back aligned when scrolling.

https://jsfiddle.net/alogg/fje895rv/26/

Additionally, an error is thrown by fixed-columns extension.
> TypeError: undefined is not an object (evaluating '$tr.attr('style').replace')

(An idea would be to refresh the table that contains the fixed columns on expand.)

Any help most appreciated, thanks in advance!
**GREAT TOOL GENTS !**

**Comment by UtechtDustin** [comment]
Can confirm that bug, i also saw that the hover effect is not correct.
![Peek 2019-09-29 01-12](https://user-images.githubusercontent.com/13292481/65823424-57d2ac00-e256-11e9-8f13-3e83bf49f8a9.gif)

**Comment by erichacker** [comment]
any progress on this issue?

**Comment by wenzhixin** [comment]
Fixed-columns extension does not support `detailView` option.
