### ISSUE TITLE
BS 3 Infinite scrolling extension

### ISSUE THREAD

**Issue by rafasashi** [wenzhixin/bootstrap-table#4588]
Is there any infinite scrolling extension for the Bs 3 version out there?

If not please put me on the track to start developing such extension.

Thanks in advance.

**Comment by UtechtDustin** [comment]
If you mean ajax requests (which load new data) while scrolling down, no there isnt.
But feel free to start developing on that :-)

**Comment by rafasashi** [comment]
Thanks Dustin! Yes I will start a module soon. I need to figure out a way to manage both pagination of pre-loaded data and data requested from paginated source url. Because the logic to receive and stack the new entries is different.

**Comment by UtechtDustin** [comment]
@rafasashi Do you have any news ?

**Comment by rafasashi** [comment]
I dont know how to do this the right way because there is multiple scenarios to consider when it come to collect the need data and append it to the current list: 

- with/without ajax for the first call
- pagination based on full dataset or partial

My actual workflow is to call the full dataset via ajax and use paginate to show more lines.

In order to show more lines on scroll we need to override the behavior of the paginate function to append the new lines instead of refreshing the table but it would be nice to make it compatible with implementations loading the dataset with ajax...

Therefore I dont know where it is best to plug the infinite scroll logic... any idea?

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf 
This issue is almost 1 year old, no one else asked for that extension. Also this extension would be incompatible with a lot of features/extensions. 
Should we really consider to implement it ?

**Comment by djhvscf** [comment]
We already have the [virtual scroll](https://bootstrap-table.com/docs/api/table-options/#virtualscroll).

**Comment by UtechtDustin** [comment]
Its more or less the same, so we can close it or not ?

**Comment by djhvscf** [comment]
For me, close it
