### ISSUE TITLE
Sorting by visible content rather than code contained in cell

### ISSUE THREAD

**Issue by Melisunde** [wenzhixin/bootstrap-table#4591]
When using Bootstrap Table to sort columns it sorts by the HTML content of the cell rather than the visible content. For example, if you have a column that contains links, I'd think you'd want to be able to sort by link text, not href content. 

[For Example](https://jsfiddle.net/melisunde/edkz6cv2/11/) 

In the example it loads as C, A, B. After hitting the sort button I'd expect it to be A, B, C but it sorts as C, B, A (corresponding to 1, 2, 3 in the links.)

Is there a way to have Bootstrap Table ignore the link? This doesn't appear to be addressed in the site's examples, unless this is considered to be something that should be handled by the Column Formatter function.

**Comment by wenzhixin** [comment]
[sorter](https://bootstrap-table.com/docs/api/column-options/#sorter) column option can solve your problem: https://examples.bootstrap-table.com/#column-options/column-sorter.html.

Your case: https://live.bootstrap-table.com/code/wenzhixin/570
