### ISSUE TITLE
Using bootstrap-table with input fields

### ISSUE THREAD

**Issue by balderman1** [wenzhixin/bootstrap-table#4592]
Hi
I have table that contains input fields (select,date input).
I would like to make it a bootstrap-table.
When the user changes the value of the input field I would like to:

1. Check if the input field belongs to the actively sorted column
2. Call the table "sort" API if the answer to the previous question is positive.

Is it possible with the current bootstrap-table?

More details and a working code example in [stackoverflow](https://stackoverflow.com/questions/57923391/using-bootstrap-table-with-input-fields).

Thanks

**Comment by wenzhixin** [comment]
Same as #987, you need to call `updateRow` to save the change to the table `data`: https://live.bootstrap-table.com/code/wenzhixin/737.
