### ISSUE TITLE
Refresh with data not working

### ISSUE THREAD

**Issue by Espritk** [wenzhixin/bootstrap-table#4593]
I want to refresh the table with the refresh option using data but it doenst work.
$table.bootstrapTable('refresh', {data: data})

it only works with url 
  $table.bootstrapTable('refresh', {url: 'json/data1.json'})

view example here:

https://live.bootstrap-table.com/code/Espritk/586

**Comment by wenzhixin** [comment]
You can use [`load`](https://bootstrap-table.com/docs/api/methods/#load) method instead: https://live.bootstrap-table.com/code/wenzhixin/589
