### ISSUE TITLE
Dynamic loading of bootstrap tree-table when expanding data

### ISSUE THREAD

**Issue by zhujkgithub** [wenzhixin/bootstrap-table#4595]
![image](https://user-images.githubusercontent.com/32259718/65313092-62da6c00-dbc6-11e9-9e9d-0ba14d008989.png)

能先展示一级节点，点击“一级节点”发送请求到后台获取“子节点”？

**Comment by wenzhixin** [comment]
目前应该不支持

**Comment by wenzhixin** [comment]
ref #5068
