### ISSUE TITLE
Minify with webpack V1.15.4 failed

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4597]
I am currently using version 1.14.2 and I have minimized the file with webpack without problem.
But I have updated to version 1.15.4 and when using the minimized file, I receive the following error message: `$(...).bootstrapTable is not a function`
I tried it with version 1.15.2 and I receive the same error message.
How can I minimize the file with Webpack???

**Comment by wenzhixin** [comment]
Added a new blog: https://blog.bootstrap-table.com/2019/09/22/bootstrap-table-in-webpack/ and I found it works well.

**Comment by manukieli** [comment]
Ok, thank you so much.
Your example has been very useful to me.
