### ISSUE TITLE
官网实例的单元格错位

### ISSUE THREAD

**Issue by ambit-tsai** [wenzhixin/bootstrap-table#4599]
![微信截图_20190924133742](https://user-images.githubusercontent.com/42671189/65484176-2f9f2200-ded1-11e9-87e3-128be3ac9a7c.png)

**Comment by wenzhixin** [comment]
是什么浏览器？按刷新可以正常使用不

**Comment by ambit-tsai** [comment]
> 是什么浏览器？按刷新可以正常使用不

刷新还是有错位，其他的倒不影响

**Comment by ambit-tsai** [comment]
Win10，360浏览器 11，Chrome 76

**Comment by UtechtDustin** [comment]
Cant reproduce it on Chrome 80.0.3987.87 and Chromium 79.0.3945.130.
Could you please test it ? @wenzhixin @djhvscf

**Comment by UtechtDustin** [comment]
@djhvscf Do you have time to test it :-) ?

**Comment by djhvscf** [comment]
Loos good for me. But I can reproduce this issue when I resize the window. @wenzhixin @UtechtDustin

**Comment by wenzhixin** [comment]
I think the latest version has fixed this bug.
https://examples.bootstrap-table.com/#welcome.html
