### ISSUE TITLE
Export selected data

### ISSUE THREAD

**Issue by pedrosalpr** [wenzhixin/bootstrap-table#460]
I use the extensions / export plugin.
How do I export only the selected data with checkbox?

**Comment by simkeyur** [comment]
did you find any solution yet?

**Comment by tmorehouse** [comment]
You would need to find a way to hide the unchecked rows temporarily (`display:none;`) just before the export happens, and then unhide them after the export is complete.

**Comment by wenzhixin** [comment]
Added `exportDataType` option: http://bootstrap-table.wenzhixin.net.cn/extensions/#table-export
Example: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html

**Comment by nandooliveira** [comment]
It should work with ajax pagination?

**Comment by GillBill** [comment]
I can't get it working with ajax when Export All (or Export Selected) is selected, then no records are exported. It only works with the option Export Basic for the current displayed records.
