### ISSUE TITLE
Enabling 'search: true' in bootstrapTable causes the 'triggerSearch' method to not refresh the search. [1.15.4]

### ISSUE THREAD

**Issue by colistro123** [wenzhixin/bootstrap-table#4604]
I hope I'm not the only one getting this issue, anyway, here are the steps to reproduce this.

**Steps to reproduce:**

1. Enable 'search: true' in the bootstrapTable initializer.
2. Call `$('#table').bootstrapTable('triggerSearch');`
3. The table no longer refreshes, now if you disable `search: true`, it works just fine, which confuses me.

Thanks in advance.

**Comment by UtechtDustin** [comment]
I cant reproduce the bug, maybe i dont understood it correct.
Could you provide an example (using our [Editor](https://live.bootstrap-table.com/)) ?

**Comment by wenzhixin** [comment]
@UtechtDustin `triggerSearch` is the method of the filter-control extension, I found a bug of `triggerSearch`, but I don't know why to enable `search: true` mean.

Bug: https://live.bootstrap-table.com/code/wenzhixin/856

**Comment by colistro123** [comment]
I'm sorry, I couldn't reproduce this bug either  on your editor.
