### ISSUE TITLE
Auto-refresh autoRefreshInterval random

### ISSUE THREAD

**Issue by rmarzocchi84** [wenzhixin/bootstrap-table#4608]
I am testintg the auto-refresh plugin with the following options:
 
```
<table id="table" 
	data-toggle="table"
	autoRefresh="true"
	autoRefreshStatus="true"
	data-show-refresh="true" 
	data-auto-refresh="true" 
	data-pagination="true" 
	data-url="./geojson2.php" 
	autoRefreshInterval="3"
	>
```

The refresh works, but I do not understand the interval which seem random

**Comment by wenzhixin** [comment]
you need to use `data-auto-refresh-interval` attribute option: https://live.bootstrap-table.com/code/wenzhixin/758.

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days if the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
