### ISSUE TITLE
Table escaping from div when resetView is called in latest version on Chrome (77.0.3865.90) on Windows,

### ISSUE THREAD

**Issue by euangordon** [wenzhixin/bootstrap-table#4609]
This week, we started noticing that the latest version of Chrome has an unusual behaviour when resetView is called on bootstrapTables. In our UI, if the div containing a table changes height then we call resetView on the tables with the new height that they have available. At this point, in the latest Chrome the table escaped from the div it was in:

![image](https://user-images.githubusercontent.com/32622054/65760441-ee974f80-e114-11e9-99c9-2f507a698800.png)

Prior to the latest version of Chrome everything was working as expected, also at the moment other browsers are ok (FF, Edge, Chrome on Mac, Safari). I will be continuing investigating the issue and will create an example if I don't get anywhere, but I am interested to know if anyone can shed any light on the issue / or are having the issue themselves.

Any help or pointers would be greatly appreciated.

bootstrap-table version: 1.11.0

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by euangordon** [comment]
Hi @wenzhixin ,

Not got an online example but will get there.

The issue actually seems to be a Chrome bug (also affecting Wordpress):
https://bugs.chromium.org/p/chromium/issues/detail?id=1003556

Long story short, we are resizing the div that the table is in, then calling resetViewer. This Chrome bug overruling our CSS and setting heights for divs with no height... 

For now, I have managed to work around the issue sufficiently until Chrome release a new version with this bug rolled back.

**Comment by euangordon** [comment]
Another update: The latest beta version of chrome is working fine, so just need to wait for that to be released. Won't waste any more time on this.

**Comment by UtechtDustin** [comment]
Thank you for the update
