### ISSUE TITLE
Form Submit on Search Enter

### ISSUE THREAD

**Issue by cgountanis** [wenzhixin/bootstrap-table#4610]
Is there a way to disable form submit when {ENTER} is pressed on a search input if a table is within a FORM tag?

**Comment by wenzhixin** [comment]
https://live.bootstrap-table.com/code/wenzhixin/762

**Comment by cgountanis** [comment]
If you do not want to use JS, this works as well.

<form action="...">
  
  <button type="submit" disabled style="display: none" aria-hidden="true"></button>
