### ISSUE TITLE
Need searchStyle Option

### ISSUE THREAD

**Issue by stevewoolley** [wenzhixin/bootstrap-table#4612]
Request to add searchStyle. Need way to style search box (bold, color, size, font, etc.).

**Comment by UtechtDustin** [comment]
Im not sure if we should add a style option for each ui element (#4611).
This could be also done with css easily i guess, what do you think @wenzhixin @djhvscf  ?

**Comment by stevewoolley** [comment]
I agree. I also opened https://github.com/wenzhixin/bootstrap-table/issues/4611 concerning the headerStyle. The way I might justify headerStyle being outside of css is when the header style would be calculated/dynamic (based on other criteria). I don't see the search box being dynamically styled.

**Comment by wenzhixin** [comment]
I think it's better to use css to solve this problem: https://live.bootstrap-table.com/code/wenzhixin/766. Because by default, we use the input box style of the theme.

**Comment by wenzhixin** [comment]
There is search input size bug with `iconSize` option, fixed in #4613
