### ISSUE TITLE
Multiple-sort extension dont work (only update the icons)

### ISSUE THREAD

**Issue by tafadzwagonera** [wenzhixin/bootstrap-table#4616]
I followed the instructions here https://bootstrap-table.com/docs/extensions/multiple-sort/#multiplesort to create a table with multiple sortable columns. I've minified the js I found here https://github.com/dimbslmh/bootstrap-table/tree/master/src/extensions/multiple-sort using various tools online.

HTML
```
<table 
    id="js-bootcamp-list"
    data-search="true"
    data-toolbar="#toolbar"
    data-show-toggle="true"
    data-show-fullscreen="true"
    data-click-to-select="true"
    data-show-columns="true"
    data-detail-view="true"
    data-page-list="[25, 50, 100, 200, All]"
    data-show-multi-sort="true"
    data-show-multi-sort-button="true"
    class="table-striped table-condensed">
    <thead>
        <tr>
            <th 
            data-field="logo"
            data-sortable="false"
            data-align="center"
            data-valign="middle"></th>
            <th 
            data-field="name"
            data-sortable="true"
            data-align="center"
            data-valign="middle">School/College</th>
            <th 
            data-field="description"
            data-visible="false">Description</th>
            <th 
            data-field="reviews"
            data-sortable="true"
            data-align="center"
            data-valign="middle">Aggregate reviews</th>
            <th 
            data-field="duration"
            data-sortable="true"
            data-align="center"
            data-valign="middle">Duration</th>
        </tr>
  </thead>  
</table>
```

JS
```
var init = function (args) {
    // body...
    $bootcampList.bootstrapTable({
        sortPriority: [
            {'sortName':'reviews', 'sortOrder':'desc'}, 
            {'sortName':'duration', 'sortOrder':'desc'}
        ],
        data: data,
        detailFormatter: detailFormatter,
        rowAttributes: rowAttributes,
        undefinedText: "N/A"
    });
}
```

Unfortanetly on page load when init function is fired up. The table doesn't sort data in reviews and duration columns.

**Comment by UtechtDustin** [comment]
Please provide us an example using our [online editor](https://live.bootstrap-table.com/) instead of posting some code.

**Comment by wenzhixin** [comment]
@tafadzwagonera working example: https://live.bootstrap-table.com/code/wenzhixin/853

**Comment by wenzhixin** [comment]
Updated the docs: https://bootstrap-table.com/docs/extensions/multiple-sort/
Example: https://examples.bootstrap-table.com/#extensions/multiple-sort.html

Please use our released version: https://github.com/wenzhixin/bootstrap-table/tree/develop/dist/extensions/multiple-sort instead.

**Comment by vivek-kandhvar** [comment]
> @tafadzwagonera working example: https://live.bootstrap-table.com/code/wenzhixin/853

Multi-sort extension never works! I don't know how others are even using this. The example you claim which is working above, doesn't work if I change 'desc' to 'asc' and run it!

It also doesn't work if I change it from the multi sort modal options!

So just wanted to understand, if the functionality of this library is to only update the sort icon?

**Comment by vivek-kandhvar** [comment]
Any update on this issue yet? Appreciate your quick response.

**Comment by UtechtDustin** [comment]
@vivek-kandhvar No new news, sorry.
If there is a update we will write it in this isue or we will link the pull request which fix this issue.

**Comment by vivek-kandhvar** [comment]
Ah ok! Was really looking forward to use this feature in my product. Sad it's broken. 
Will look forward for the fix.

Thanks

**Comment by wenzhixin** [comment]
@UtechtDustin  Has the PR (#5329) fixed this problem?

**Comment by UtechtDustin** [comment]
@wenzhixin no

**Comment by Naruto-kyun** [comment]
Took me some hours, to find out, but seconds to fix...
the extention update this.data, then this.initBody() load this.options.data, so reorder this.options.data instead fix the issue
