### ISSUE TITLE
onClickCell returns wrong field name when using 'detailView' (since v1.15.3)

### ISSUE THREAD

**Issue by mi2git** [wenzhixin/bootstrap-table#4618]
When using the event handler onClickCell in conjuction with detailView, you'll get the field name of the next column and not the current one.

Example:
https://live.bootstrap-table.com/code/mi2git/787

Works fine in versions before 1.15.3

Many thanks for having a look at it.

**Comment by wenzhixin** [comment]
This bug has been fixed in #4568: https://live.bootstrap-table.com/code/wenzhixin/788.

Will consider to release a new version soon.

**Comment by UtechtDustin** [comment]
Damit 30 seconds to late.. :D
(https://live.bootstrap-table.com/code/UtechtDustin/789)
