### ISSUE TITLE
Disable Scroll Block Table to Display All Columns in Browser

### ISSUE THREAD

**Issue by Au2laDeNosReves** [wenzhixin/bootstrap-table#4619]
Hi

French : 
J'ai un soucis, j'ai un scroll entre ma table et ma Pagination car j'ai trop de column.

hors je voudrais que toute les colonnes soient affiché pour que le scroll du navigateur soit affiché au lieu du block table.

Google Translate :

I have a problem, I have a scroll between my table and my Pagination because I have too much column.

off I would like all the columns to be displayed so that the scroll of the browser is displayed instead of the block table.

![Sans titre](https://user-images.githubusercontent.com/10676275/65901002-8916bd80-e3b7-11e9-9548-4806b336b62e.jpg)

**Comment by wenzhixin** [comment]
I don't think this is a problem with bootstrap-table, for ecample https://live.bootstrap-table.com/code/wenzhixin/852, you can use `$(window).height()` to set the `height` option.
Maybe the probelm is caused by your custom css style?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days from you.
if you still need help please reopen the issue.

**Comment by Au2laDeNosReves** [comment]
Bonjour

Veuillez m'excuser du retard, j'étais en déplacement. J'ai abandonné le projet pour le moment.

Je vous remercie de vos retour.

Cordialement,

GoogleTranslate : 

Hello

I apologize for the delay, I was traveling. I abandoned the project for the moment.

I thank you for your return.

Regards,

**Comment by UtechtDustin** [comment]
@Au2laDeNosReves 
So welcome back :)
Let us know if the answer from @wenzhixin helps.

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days from you.
if you still need help please reopen the issue.
