### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience

### ISSUE THREAD

**Issue by ang3lx** [wenzhixin/bootstrap-table#462]
I've this error when load json db 

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

Chrome 40

**Comment by wenzhixin** [comment]
Hi @ang3lx , bootstrap table use [jQuery.ajax](api.jquery.com/jQuery.ajax/) to request the server, so it is dependent on jQuery. I think this is a warning, not a error, close this issue.

**Comment by ang3lx** [comment]
you can resolve adding at .ajax command

async: true,

**Comment by wenzhixin** [comment]
You can use 'ajaxOptions' option to do what you want.
