### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by rame0** [wenzhixin/bootstrap-table#4620]
After updating to 1.15.4 from 1.14.2 i'm getting error while building project with gulp + browserify + babel:
```
'import' and 'export' may appear only with 'sourceType: module' (7:0) while parsing
..../node_modules/bootstrap-table/src/bootstrap-table.js while parsing file: 
.../node_modules/bootstrap-table/src/bootstrap-table.js
```

Build script:
```js
browserify({
                entries: filepath,
                debug: true
            })
                .transform(babelify, {
                    global: true,
                    ignore: [],
                    presets: ["@babel/preset-env"],
                    plugins: [
                        [
                            "@babel/plugin-proposal-class-properties"
                        ]
                    ]
                })
                .bundle()
                .on('error', function (err) {
                    // print the error (can replace with gulp-util)
                    console.error(err.message);
                    // end this stream
                    this.emit('end');
                })
                .pipe(source(file))
                .pipe(gulp.dest(build_path.js))
                .pipe(touch()); /* fix to update modified time */
        }
```

I'm using:
```
    "@babel/core": "^7.6.2",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/preset-env": "^7.6.2",
    "babelify": "^10.0.0",
    "browserify": "^16.5.0",
```

**Comment by UtechtDustin** [comment]
I never used gulp before, so i cant help you.
Im sure @wenzhixin will help out.

Do you tried to search for solutions ?
For me as none gulp user it looks, that this is a configuration thing (https://stackoverflow.com/questions/40029113/syntaxerror-import-and-export-may-appear-only-with-sourcetype-module-w).

**Comment by rame0** [comment]
> I never used gulp before, so i cant help you.
> Im sure @wenzhixin will help out.
> 
> Do you tried to search for solutions ?
> For me as none gulp user it looks, that this is a configuration thing (https://stackoverflow.com/questions/40029113/syntaxerror-import-and-export-may-appear-only-with-sourcetype-module-w).

Yes. I tried using different presets. But they were causing even more errors.

**Comment by rame0** [comment]
I just realized that most solutions was outdated.
But in thread provided linked by @UtechtDustin was one answer which helped: https://stackoverflow.com/a/56608843/513723

> So, I updated my packages and then used global option to run babelify as a global transform excluding all node modules but the one I was interested in as indicated on the babelify repo page:

```js
...    
browserify.transform("babelify", 
    {
        presets: ["@babel/preset-env"], 
        sourceMaps: true, 
        global: true, 
        ignore: [/\/node_modules\/(?!your module folder\/)/]
    }).bundle()
...
```

Many thanks for help.
