### ISSUE TITLE
Number of rows per page list not displaying. 

### ISSUE THREAD

**Issue by ashishvermapu** [wenzhixin/bootstrap-table#4625]
Bootstrap-Table bootstrap-table.min.js 1.15.4 Bootstrap bootstrap.min.js 4.3.1 Jquery jquery-min.js 3.4.1

Page is loading just fine. However, the drop-down list to select number of rows per page is not working. Table code is working fine on online editor of bootstrap-table. I've already tried using different tables and its not working.

https://jsfiddle.net/ashishvermapu/f54jweyc/1/

**Comment by wenzhixin** [comment]
Your fiddle cannot work. Online editable is working well: https://live.bootstrap-table.com/code/wenzhixin/861

**Comment by ashishvermapu** [comment]
The fiddle is now working. This not a issue with bootstrap-table. Closing.

Bootstrap 4 needs pooper.js.

<script src="webjars/popper.js/1.14.7/umd/popper.min.js"></script>
