### ISSUE TITLE
Android Input lost focus on bootstrap table (cardview)

### ISSUE THREAD

**Issue by AndreaAnto90** [wenzhixin/bootstrap-table#4627]
Hello
in android devices in cardview mode if I try to insert text into the input the keyboard disappears and the control loses focus.
If I don't load the js bootstrap-table-mobile.js and remove the mobileResponsive property I don't have the problem.

jsfiddle: https://jsfiddle.net/Martin90/9p8zxvob/26/
Could be a issue?
Thanks
Andrea

**Comment by UtechtDustin** [comment]
The issue is that if you click on the input, the keyboard will be displayed and resize event will be triggered (lesser height). Because of the resetView the input will be recreated and the keyboard disappears.
