### ISSUE TITLE
invisible column should be searchable when i set it to true.

### ISSUE THREAD

**Issue by shangdiyisi** [wenzhixin/bootstrap-table#463]
I think invisible column should be searchable when i set it to true.

**Comment by djhvscf** [comment]
I think if you put invisible a column you can't search by that column.. or .. For what are you putting invisible that column?

**Comment by wenzhixin** [comment]
Added an example: http://issues.wenzhixin.net.cn/bootstrap-table/#463.html

**Comment by shangdiyisi** [comment]
Thanks!!!

**Comment by havok2063** [comment]
I'm trying to implement this, but I can't seem to get it working.  I've added class='hidden' to my columns that are not visible, and all that does is make them always not visible.  When I click to display them they no longer show up.  And they still don't turn up in my search results.  I've looked at the example but it's not clear to how it's working.   Can you flesh out the example page a bit more?

**Comment by wenzhixin** [comment]
What detail function do you want to implement? You can view the source of the example on https://github.com/wenzhixin/bootstrap-table-examples/blob/master/463.html.

**Comment by havok2063** [comment]
Update posted above.

**Comment by uzi0espil** [comment]
Thanks for the fix, but this doesn't hide it in cardView. it seems when the row turns to div>span it strip the class hidden from the td. is there a workaround for this?

**Comment by blomdahldaniel** [comment]
Hi guys, I want the exact thing as @havok2063 but the link @wenzhixin posted seems to be broken.
Is this feature solved?

**Comment by wenzhixin** [comment]
OK, reopen it

**Comment by wenzhixin** [comment]
In our latest version, we can support this feature now.

**Comment by blomdahldaniel** [comment]
Yeah!  @wenzhixin that is great! Now i will be very pleased to use your stuff. Awesome!
