### ISSUE TITLE
Page jump to extension typo

### ISSUE THREAD

**Issue by kanazir** [wenzhixin/bootstrap-table#4630]
**showJumpTo** typo

There is a difference between official extension documentation and the real life. In the documentation, you have to set **showJumpTo** to true to show page jump field. But, in the reality, you have to set **showJumpto** to true.
I discovered this by reading the source of the extension (line 26):

```javascript
showJumpto: false,
```

**Comment by UtechtDustin** [comment]
Line 26 is empty, also in the source its `showJumpTo` see https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/page-jump-to/bootstrap-table-page-jump-to.js#L9.
Do you maybe have a old version ?

**Comment by kanazir** [comment]
Ah yes, my version is 1.14.2. Sorry :(

**Comment by UtechtDustin** [comment]
No problem, but thank you for your willingness to help.
