### ISSUE TITLE
Vue Component + JsPanel

### ISSUE THREAD

**Issue by toozgu** [wenzhixin/bootstrap-table#4632]
Hi guys
I want to use the BootstrapTable Vue Component together in JsPanel. But I can't render it in  
         
       jsPanel.create({
              theme:       'primary',
              headerTitle: 'BS jsPanel',
              contentSize: '450 250',
              content:     '<p>Example panel ...</p><bootstrap-table :columns="columns" :data="data" :options="options"></bootstrap-table>',
              callback: function () {
                  this.content.style.padding = '20px';
                  
                  new Vue({
                    el:this.content[0],
                    components: {
                      'BootstrapTable': BootstrapTable
                    },
                    render: h => h(Child)
                  })
              },
              onbeforeclose: function () {
                  return confirm('Really?');
              }
          });

Can you help me?

https://jsfiddle.net/qs10mkg7/11/

**Comment by yasinkuyu** [comment]
You can do it with **Vue.compile**.

in a nutshell;

	// Assign the component to a variable.
	var template = '<bootstrap-table ...> </bootstrap-table>';

	// Use vue compile
	const compiledTemplate = Vue.compile(template);

	// Add the html tag for vue instance to the jsPanel content.
	content: '<div id="app_table"> </div>',

	Now...
	new Vue({
	// Run Vue
	el: '#app_table',
	// Call Bootstrap
	components {
	     'BootstrapTable': BootstrapTable
	},
	// Now render and add to jsPanel content.
	render (createElement) {
	     return compiledTemplate.render.call(this, createElement);
	},

That is all

**Comment by wenzhixin** [comment]
@toozgu  Have you solved your problem?

**Comment by wenzhixin** [comment]
Example: https://live.bootstrap-table.com/code/wenzhixin/893
