### ISSUE TITLE
Show all rows 

### ISSUE THREAD

**Issue by hectorcapulin** [wenzhixin/bootstrap-table#4635]
First I got to thank you for this component, is very useful. 
I have one question about it, I would like to show all rows of my bootstrap table. The way I fill this table is with a json with ajax+jquery+php. I create the table dinamically with jquery.

**Comment by UtechtDustin** [comment]
Could you explain the problem ?   
If you dont use the pagination it shows the whole data (if your response from php is correct).

Example with pagination: https://live.bootstrap-table.com/example/options/table-ajax.html
Example without pagination: https://live.bootstrap-table.com/code/UtechtDustin/884

**Comment by hectorcapulin** [comment]
@UtechtDustin that was just my problem, I didn´t know how to show all my data without the pagination. You have answer my question, removing pagination it shows all the data, thank you.
