### ISSUE TITLE
官方示例网站上面的例子怎么都不提供示范代码？

### ISSUE THREAD

**Issue by happydaily** [wenzhixin/bootstrap-table#4639]
如题啊

**Comment by wenzhixin** [comment]
左上角有个 View Source：https://examples.bootstrap-table.com/#view-source

**Comment by happydaily** [comment]
这个view source能做成一个正常的按钮吗，我找了很久用Ctrl+f才找到，真亮瞎了我的狗眼。

**Comment by wenzhixin** [comment]
那么明显看不到吗。。。我看看怎么改进下吧，或者加个首次使用帮忙啥的。

**Comment by happydaily** [comment]
做的像个装饰品，太没有违和感。
