### ISSUE TITLE
How do I get an instance of the table?

### ISSUE THREAD

**Issue by Furburger** [wenzhixin/bootstrap-table#464]
If I do this . . 

var thisTable = $('#myTable').bootstrapTable({});

. . .then thisTable is a table element, not an object

How do I get an instance of the table?

**Comment by wenzhixin** [comment]
Hi, I think it is no need to get an instance of the table, because the methods and the events are base on table element, for example:
```js
var $table = $('#myTable').bootstrapTable({});
$table.on('events', function () {
    // ...
});
$table.bootstrapTable('methodName');
```

**Comment by side-by-side** [comment]
I need to get Bootstrap Table **instance** too. It is very useful in many cases.
For example, i had create separate “class” for hold all initialization logic for the table and need to get Bootstrap Table instance to pass around method and easy call native functions.
