### ISSUE TITLE
Addrbar not populating search box

### ISSUE THREAD

**Issue by pchaganti** [wenzhixin/bootstrap-table#4643]
Having issues with addrbar extension. The search parameter from the URL is not being populated in the table's searchbox. This used to work a few versions ago. Unable to check the live editor's example page as it is blank.

**Comment by wenzhixin** [comment]
Working example: https://examples.bootstrap-table.com/template.html?v=107&url=extensions/addrbar-page.html&page=1&size=10&order=asc&sort=undefined&search=123

**Comment by pchaganti** [comment]
Was able to get this to work. Thanks!
