### ISSUE TITLE
export按钮没有反应

### ISSUE THREAD

**Issue by jianghong3** [wenzhixin/bootstrap-table#4645]
点击export按钮后发送了表格的URL，而且没有下载任何文件

**Comment by wenzhixin** [comment]
麻烦提供下在线的例子。
我们的例子是可以的：
https://examples.bootstrap-table.com/
https://examples.bootstrap-table.com/index.html#extensions/export.html

**Comment by jianghong3** [comment]
整个例子有点大，不好拷过来。我是按你们第二个例子写的，导入js文件和顺序都一样，现在能够下载文件了，但是点击导出按钮后又重新发送了表格的URL，但这个URL不完整，导致请求失败，这个可能是什么问题？另外，请问下，正常情况下点击导出按钮会发送具体怎样的请求(URL)?

**Comment by jianghong3** [comment]
如果exportDataType设置为basic，它能正常导出当页数据；如果设置为all，它会发送表格的URL（xxxx?search=crm&order=asc）, 请求返回500，下载的文件为空，请问会是什么原因？

**Comment by wenzhixin** [comment]
返回 500，应该是你的后台实现有问题，你要查下后台的日志，确认问题。

**Comment by jianghong3** [comment]
谢谢，已经解决了
