### ISSUE TITLE
Negative values transform to values with double minus on exporting

### ISSUE THREAD

**Issue by leyman0111** [wenzhixin/bootstrap-table#4646]
I have problem on exporting table with negative values.

There is my export options.
`exportOptions: {
                numbers: {
                    output: {
                        decimalMark: '.',
                        thousandsSeparator: false
                    }
                },
            },`

And when I export my table into excel, txt - any format - I get something like this: 
![Безымянный](https://user-images.githubusercontent.com/46149300/67286073-63c22e80-f4e1-11e9-93f2-21392834ff20.png)

But in a table I have correct values.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close the issue because i can't produce it (https://live.bootstrap-table.com/code/UtechtDustin/1003).
Also we got no response/example within 7days from you. If you still need help, please reopen the issue and provide us an example.
