### ISSUE TITLE
dropdown冲突

### ISSUE THREAD

**Issue by jianghong3** [wenzhixin/bootstrap-table#4647]
自己在导航栏加了一个dropdown的功能，然后bootstrap-table自带的下拉功能比如每页显示几条记录和show columns按钮点击就没有效果了，手动开启($('xxx').dropdown())也不行，请问可能是哪里出问题了？

**Comment by wenzhixin** [comment]
麻烦提供下在线运行代码，不然不知道是什么问题呀

**Comment by jianghong3** [comment]
点击show columns按钮时aria-expanded仍然是false,想问下这个切换true或false在源码里是怎么实现，具体在哪些行？

**Comment by wenzhixin** [comment]
是不是没有引入 bootstrap.js 相关的包。

**Comment by jianghong3** [comment]
已经引入了，包括bootstrap.js和bootstrap-table.js。原来表格的下拉功能是可以的，是我自己在页面其他地方加了下拉框然后就不行了，所以不清楚到底哪里冲突了？

**Comment by jianghong3** [comment]
我把bootstrap.js删除后发现可以下拉了，就是样式不太好看，图标显示不了

**Comment by wenzhixin** [comment]
应该是你自己的实现跟 bootstrap.js 的下拉功能冲突了。
