### ISSUE TITLE
Purpose of data-content-type

### ISSUE THREAD

**Issue by mibollma** [wenzhixin/bootstrap-table#465]
When I place a custom mime content type in the *data-content-type* attribute the headers of the request look like this:

`Accept:"application/json, text/javascript, */*; q=0.01"`
`Content-Type:"application/vnd.XYZ.bootstrap-table+json"`

Shouldn't the custom content type be in the accept header field to signal the server which data format to send back? Instead it is in the content type header field even though GET requests do not contain a body.

**Comment by wenzhixin** [comment]
Sorry @mibollma , I am not very clear with your problem, but I think you can set the `ajaxOptions` option to do what you want(call [jQuery.ajax](http://api.jquery.com/jQuery.ajax/) method to request the server).

**Comment by mibollma** [comment]
Thanks for the info @wenzhixin.
Nevertheless i'll try to clarify my point.

The bootstrap-table docs state:
*data-content-type: The contentType of request remote data.*
Which I understand as:
*The contentType of the data that lies on the remote server, is requested by bootstrap-table and is displayed by bootstrap-table.*

So when bootstrap-table requests data from the server it should tell the server it wants this kind of content and the server delivers this kind of content instead of xml or html or whatever.
What bootstrap-table actually does is to use this contentType as *Content-Type* header of the GET request which requests data from the server.
To me that doesn't make much sense. Here the *Content-Type* header doesn't seem to make sense, but the *Accept* header would enable bootstrap-table to specify which kind of data it expects the server to send.

or to quote the spec...

**Content-Type**
The Content-Type entity-header field indicates the media type of the entity-body sent to the recipient or, in the case of the HEAD method, the media type that would have been sent had the request been a GET.

**Accept**
The Accept request-header field can be used to specify certain media types which are acceptable for the response. Accept headers can be used to indicate that the request is specifically limited to a small set of desired types, as in the case of a request for an in-line image.

I hope this makes it a little clearer.

**Comment by cocowalla** [comment]
@mibollma did you find a way to prevent the `Content-Type` header being set? It is indeed not valid to set the `Content-Type` header if there is no content of that type - so since this script is making GET requests (which have no body), no `Content-Type` (should be set([http://stackoverflow.com/questions/5661596/do-i-need-a-content-type-for-http-get-requests].

@wenzhixin I vote to reopen this issue. Some servers (e.g. Nancy), adhere to the HTTP spec more strictly than others, and will throw an exception when they receive a GET request with `Content-Type` set.

**Comment by cocowalla** [comment]
So I found a workaround for the meantime:

`data-content-type=""

This makes no `Content-Type` header be sent for the GET requests that are made.
