### ISSUE TITLE
Groupby: radio button

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#4652]
Hi,

is there a way of using group-by and radio buttons but have the radio button selection be based on the groupby sections(so allow radio selection for every group)? Thank you.

**Comment by Scnck** [comment]
radio selection is based on entire table not the individual groupby sections, in less there is a setting I'm over looking.

**Comment by UtechtDustin** [comment]
I think the extension cant handle it yet.

**Comment by Scnck** [comment]
wonder if I did this what is preventing it from working?

```
onCheck: function onCheck(row) {
	$table.find('input[type="radio"]').each(function(i,e) {
		var p = $(e).closest('tr').attr('data-parent-index');
		if (p) {
			$(e).attr("name", p);
		}
		 
	});
}
```

**Comment by UtechtDustin** [comment]
@Scnck 
First of all, we dont answer faster your question if you post it in multiple issues.
Also as written in the issue templates, provide us a example of your problem (using our [Editor](https://live.bootstrap-table.com/) )or we cant help.

**Comment by Scnck** [comment]
sorry about the double post...didn't really I already posted to that other ticket...

I was able to implement this functionality... is there a better approach?

https://live.bootstrap-table.com/code/Scnck/4176

**Comment by UtechtDustin** [comment]
Looks good i guess

**Comment by JS-E** [comment]
Is this still an issue or can this be resolved? Trying to do the same with tables and radio buttons within each table.

**Comment by djhvscf** [comment]
You can use the @Scnck example: https://live.bootstrap-table.com/code/Scnck/4176
