### ISSUE TITLE
bootstrap-table单列筛选

### ISSUE THREAD

**Issue by jianghong3** [wenzhixin/bootstrap-table#4653]
现在需要对某列进行筛选，具体是输入关键字，查找到该列所有包含关键字的所在数据行，请问bootstrap-table支持这个功能吗

Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by wenzhixin** [comment]
你可以使用 Filter Control 扩展插件：
* https://bootstrap-table.com/docs/extensions/filter-control/
* https://examples.bootstrap-table.com/#extensions/filter-control.html

**Comment by jianghong3** [comment]
这个也是整个表格内搜索吗，我在某列上设置filterControl为input，但搜索后仍然包含其他列的关键字。另外，有一列设置后根本不在该列中搜索，这是为什么呢

**Comment by wenzhixin** [comment]
提供下例子？

**Comment by jianghong3** [comment]
好像不是单列筛选，单列的搜索框与表格上方的搜索框功能是一样的，仍然是在整个表格内搜索， 是要后端自己实现搜索功能吗？

**Comment by jianghong3** [comment]
<table id="improve" data-url="improvedata" data-search="true" data-filter-control="true" data-show-search-clear-button="true">

$("#improve").bootstrapTable('destory').bootstrapTable({
columns: [{field: 'field', title:'领域', filterControl:'input'}, 
                 {field: 'team', title:'项目组', filterControl:'input'}
]
})

**Comment by jianghong3** [comment]
<table id="improve" data-url="improvedata" data-search="true" data-filter-control="true" data-show-search-clear-button="true"></table>

**Comment by wenzhixin** [comment]
试下在线编辑器： https://live.bootstrap-table.com/example/extensions/filter-control.html

**Comment by jianghong3** [comment]
data-search设为true后，表格的搜索功能是前端还是后端实现

**Comment by jianghong3** [comment]
我的搜索、排序和分页都是后端实现，所以单列筛选和搜索功能冲突是不是这个原因？

在线试了个小例子没问题，但在我的项目里情况有点复杂。前端搜索时会发生请求(xxx?search=ggg&order.......)，如果加了单列筛选的话， 请求参数会多一个filter， 那不是要在后端自己处理这个功能？

**Comment by wenzhixin** [comment]
是的，后端分页的话是需要自己实现的。

**Comment by jianghong3** [comment]
所以要单列筛选和搜索同时实现是必须前端完成，后端不做任何操作？

**Comment by wenzhixin** [comment]
都是后台处理呀，例如 search 参数是匹配所有字段，指定的参数就是通过 filter ，如：
<pre>
search: 3
order: asc
offset: 0
limit: 10
filter: {"name":"1"}
</pre>

**Comment by jianghong3** [comment]
但如果我在单列筛选输入a, 搜索框不输入，那么就是
search: 'a'
order: asc
offset: 0
limit: 10
filter: {"name":"a"}

**Comment by wenzhixin** [comment]
那估计是 bug，你需要两个都开启的情况吗？

**Comment by jianghong3** [comment]
需要，这个bug怎么解决呢

**Comment by wenzhixin** [comment]
测试了下，没有出现你说的问题：https://live.bootstrap-table.com/code/wenzhixin/982

**Comment by jianghong3** [comment]
你给的链接进去无论单列筛选还是搜索都不成功啊，无论输入什么都显示全部数据

**Comment by wenzhixin** [comment]
后台没有处理，但是你 F12 看参数是对的。

**Comment by jianghong3** [comment]
我这边search的值是所有输入框中最后输入的那个框中的值，源码里search取值是在哪里，具体怎么实现的

**Comment by jianghong3** [comment]
他是不是根据类名为form-control来获取搜索框内的值

**Comment by wenzhixin** [comment]
使用最新的版本
