### ISSUE TITLE
detailViewIcon  = false 时字段单击事件无法响应

### ISSUE THREAD

**Issue by zeroone2005** [wenzhixin/bootstrap-table#4654]
detailViewIcon  = false时字段单击事件无法响应，detailView我是上根据表里的单击事件来显示。

**Comment by wenzhixin** [comment]
这两种方式都是可以的：
* https://live.bootstrap-table.com/example/options/detail-view-icon.html
* https://live.bootstrap-table.com/code/wenzhixin/965
