### ISSUE TITLE
Set number of pages programmatically

### ISSUE THREAD

**Issue by prosperva** [wenzhixin/bootstrap-table#4655]
Is there a way to set the number of pages on pagination without letting the bootstraptable do the pages based on the record count and page size?

**Comment by UtechtDustin** [comment]
Im not sure if i understand it right...
If i have 100 entries and a page shows 10 entries you have 10 pages.
So you want to display only 5 page ? (which means you cant see the last 50 entries)

**Comment by UtechtDustin** [comment]
Oh okay, then your searching for the [sidePagination](https://bootstrap-table.com/docs/api/table-options/#sidepagination) Option.
Example: https://live.bootstrap-table.com/example/options/server-side-pagination.html

**Comment by UtechtDustin** [comment]
I close the issue because we got no response from you within 7 days.
I think the sidePagination Option should do the job.
