### ISSUE TITLE
Sticky header doesn't adjust to max width 

### ISSUE THREAD

**Issue by vinnesc** [wenzhixin/bootstrap-table#4661]
Bootstrap-Table version: v1.15.5
Browsers: Chrome and Firefox

I'm using Bootstrap-Table with Bootstrap 4. My html composition is like this:

```
<div id="content-main">
   <div class="container" id="accordion">
            <div class="row">
                <div class="col-12"><table id="table" class="table order-list table-striped"></table>               
                </div>
            </div>
    </div>
</div>
```

I'm trying to use the sticky header extension in my table. Before scrolling, everything looks like this. Please note I'm also using the fixed columns extension so in the hours columns you can't see all of them.
![Screenshot 2019-10-30 at 10 35 30](https://user-images.githubusercontent.com/54041995/67846430-84057500-fb01-11e9-84ba-c2588e6517a2.png)
Now when I scroll down, the header stretches to fit the entire window, which is not what I want.
![Screenshot 2019-10-30 at 10 36 47](https://user-images.githubusercontent.com/54041995/67846512-a4cdca80-fb01-11e9-82ae-399f0a066795.png)
I know there's the stickyHeaderOffsetLeft and stickyHeaderOffsetRight options, but those don't work since I need it to be responsive and adjust dynamically along the rest of the page.

I don't know if this is the result of combining sticky header and fixed columns or if it's a bug from the sticky header itself.

**Comment by UtechtDustin** [comment]
Please provide us an example with our [Editor](https://live.bootstrap-table.com/).

**Comment by UtechtDustin** [comment]
I close this issue because we got no response/example within 7 Days, if you still need help please reopen the issue.
