### ISSUE TITLE
printFormatter不起作用？

### ISSUE THREAD

**Issue by yanhuRicoh** [wenzhixin/bootstrap-table#4666]
代码如下：

javascript代码：

function meetingTimeFormatter(value, row, index) {
        var startDate = row.startDate;
        var endDate = row.endDate;
        var content = startDate + ' - ' + endDate;
        return content;
}

function meetingTimePrintFormatter(value, row, index) {
        var startDate = row.startDate;
        var endDate = row.endDate;
        var content = startDate + ' - ' + endDate;
        return content;
}

$("#table").bootstrapTable({
                data: data,
                classes: 'table',
                pagination: false,
                striped: true,
                customSort: customSort,
                columns: [
                    {
                        title: '時間',
                        sortable: true,
                        cellStyle: timeCellStyle,
                        printFormatter: meetingTimePrintFormatter,
                        formatter: meetingTimeFormatter,
                        width: '8%'
                    }, ...
                 ]
})

<table id="table" class="table table-bordered table-striped" data-row-style="rowStyle" data-show-print="true"></table>

看到文档里写printFormatter与formatter的用法相同，但是formatter显示正常，printFormatter却不起作用，打印的预览页也没有显示出想要的效果，是使用的方法不对吗，麻烦看一下，谢谢。

**Comment by wenzhixin** [comment]
试了下，是可以的：https://live.bootstrap-table.com/code/wenzhixin/996

**Comment by yanhuRicoh** [comment]
好的，谢谢。

**Comment by wenzhixin** [comment]
Added #4673 

* Added undefinedText option supported.
* Added printFormatter data-attribute supported.
