### ISSUE TITLE
 treegrid扩展出错 Super expression must either be null or a function

### ISSUE THREAD

**Issue by yuxin5156** [wenzhixin/bootstrap-table#4670]
这是我的引用，为什么bootstrap-table-treegrid.js会报这个错啊？

 <link href="~/Content/bootstrap-table/bootstrap-table.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-v3.7/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/treegrid/jquery.treegrid.css" rel="stylesheet" />
    <link href="~/Content/jstree/themes/default/style.css" rel="stylesheet" />
    <script src="~/Content/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/bootstrap-v3.7/js/bootstrap.js"></script>
    <script src="~/Content/jstree/jstree.js"></script>
    <script src="~/Content/treegrid/jquery.treegrid.js"></script>
    <script src="~/Content/bootstrap-table/bootstrap-table.js"></script>
    <script src="~/Content/bootstrap-table/locale/bootstrap-table-zh-CN.js"></script>
    <script src="~/Content/bootstrap-table/extensions/treegrid/bootstrap-table-treegrid.js"></script>

**Comment by wenzhixin** [comment]
可以提供例子吗？

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days if the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
