### ISSUE TITLE
the bottom border bug with height option is still there

### ISSUE THREAD

**Issue by jackbauer007007** [wenzhixin/bootstrap-table#4671]
fix method: padding += this.$header.outerHeight(true) + 1
but in my project ,this problem is still there,when the option contains height,the bottom border donot show

```
var columnArray = [{
					checkbox: true,
					radio:false,
					formatter:function actionFormatter(value, row, index) {
			                }
				},
				{
					field: 'id',
					title: 'id',
					align: 'center', // 横向居中
					valign: 'middle', // 纵向居中
					visible: false,
					sortable: false,
					searchable: false,
					events: {}
				},
				{
					field: 'text',
					title: "文本",
					align: 'center', // 横向居中
					valign: 'middle', // 纵向居中
					visible: true,
					sortable: false,
					events: {}
				}];
$(unit_table).bootstrapTable({
				clickToSelect: true,
				singleSelect: false,
				striped: true,
				columns: columnArray,
				height: 500,
				search: true,
				searchText: "",
				formatSearch: function() {
					return "输入搜索";
				},
				searchAlign: "left",
				onDblClickRow: function (item) {
		                }
			});
```

and the fix problem example link, the before link can show the table,but the after link the table do not show

https://live.bootstrap-table.com/code/wenzhixin/880

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
fixed in #4640 i guess.

**Comment by jackbauer007007** [comment]
https://live.bootstrap-table.com/code/jackbauer007007/1045

**Comment by UtechtDustin** [comment]
@jackbauer007007 
The Editor always use the last (released) version of the bootstrap-table, but you change it to the last development version.
Click on Libraries then select on the Bootstrap Table source drop down "From GitHub src".

Working Exmaple: https://live.bootstrap-table.com/code/UtechtDustin/1048

**Comment by wenzhixin** [comment]
Improved this in #4687 4687

**Comment by jackbauer007007** [comment]
I see,the last (released) version contains the problem,the development version fix it
