### ISSUE TITLE
UI glitch when data-height is set

### ISSUE THREAD

**Issue by uksreejith** [wenzhixin/bootstrap-table#4682]
Without the height setting it looks fine as the below screenshot:
![image](https://user-images.githubusercontent.com/5095586/68125683-1bbaf700-ff38-11e9-9d9d-dbee3beaa32e.png)

When I set the height of the table I am getting a weird UI glitch. Please refer below screenshots:
Height = 400 
![image](https://user-images.githubusercontent.com/5095586/68125637-ffb75580-ff37-11e9-96e2-1a24c7bc6e59.png)

Height = 200
![image](https://user-images.githubusercontent.com/5095586/68125715-2ecdc700-ff38-11e9-8568-dc7baf3599b1.png)

This is my JS code:
`tblRecords.bootstrapTable({
            pagination: true,
            pageSize: 5,
            height: 200,
        });`

Please help. Thanks.

**Comment by UtechtDustin** [comment]
Maybe fixed in #4640, please provide us an example using our [Editor](https://live.bootstrap-table.com/).

**Comment by uksreejith** [comment]
I tried in your editor but was not able to reproduce. I retried in my project code and was unable to reproduce again since the code had changed quite a bit since then. Maybe it was an issue with my project's code. Will keep an eye out for this if it happens again. Sorry for your troubles.

**Comment by UtechtDustin** [comment]
Thank you for the feedback, your welcome :)
