### ISSUE TITLE
No data in cell, if data-field are not in the last line of the header

### ISSUE THREAD

**Issue by SEModer** [wenzhixin/bootstrap-table#4683]
Example https://live.bootstrap-table.com/code/SEModer/1052

If swap line2 and line3, be good.
On show-columns, showed last line header cols....

How to fix this so that only columns with data-field are used? Or is it a bug in this case?

**Comment by UtechtDustin** [comment]
This should work for you: https://live.bootstrap-table.com/code/UtechtDustin/1053

**Comment by SEModer** [comment]
> This should work for you: https://live.bootstrap-table.com/code/UtechtDustin/1053

Yes, i'm know, but:
![image](https://user-images.githubusercontent.com/789171/68296494-9447c200-00b6-11ea-909e-7e12cb0b3fb9.png)

**Comment by UtechtDustin** [comment]
Oh okay i understand...
Never worked with colspans, also i dont know how the code works for that..
So @wenzhixin could you help him ?

**Comment by djhvscf** [comment]
For me this is a bug. @UtechtDustin @wenzhixin

**Comment by akkivarma10** [comment]
Hi, I am looking into fixing this issue, any suggestions @djhvscf @wenzhixin @UtechtDustin

**Comment by wenzhixin** [comment]
@akkivarma10 As currently designed, your case is not supported.

**Comment by akkivarma10** [comment]
Hi @wenzhixin , I have fixed this issue on local, will be submitting a Pull request in some time.

**Comment by wenzhixin** [comment]
I found a workaround for your case: https://live.bootstrap-table.com/code/wenzhixin/1364.

PR is welcome.

**Comment by akkivarma10** [comment]
Hi @wenzhixin , I have submitted the Pull request. Please review it & let me know if any changes needs to be done. Thanks

**Comment by wenzhixin** [comment]
ref #3213

**Comment by wenzhixin** [comment]
I think it's hard to implement this feature. 
You can use the workaround.
