### ISSUE TITLE
Filtering does not work when values are undefined

### ISSUE THREAD

**Issue by mgluhak** [wenzhixin/bootstrap-table#4685]
This issue concerns the "filter-control" extension.

I am trying to to use the "select" filtering option on a specific column that contains many undefined values (shown as "-") among the others. The problem is that when using the filter, it does remove the real values that aren't the same as the searched term, but it fails to remove the undefined ones. So the results is many undefined rows and a few real ones. 
I have tried using strict search option, but it had no effect on this problem.
The workaround that I've been using is to actually assign the string "-" to undefined rows - and then the filter works correctly. The problem with that workaround is that it leads to more complications, as it then breaks the sorting features.

The issue occurs when using the "input" filter control as well.

Issue occurred in Chrome and Windows 10  - not tested in other environments

**Comment by UtechtDustin** [comment]
Please provide us an example with out [Editor](https://live.bootstrap-table.com/).

**Comment by mgluhak** [comment]
Here is an example
https://live.bootstrap-table.com/code/mgluhak/1151

The relevant column is "Letter"

**Comment by wenzhixin** [comment]
Fixed in #4699
