### ISSUE TITLE
Extension natural-sorting not working when applied to bootstrap-table starter template

### ISSUE THREAD

**Issue by GCru** [wenzhixin/bootstrap-table#4686]
I was testing the natural-sorting extension with the bootstrap-table starter template, but it does not work.

https://live.bootstrap-table.com/code/GCru/1066

(In the editor it does not show the rows but when publishing the file they are shown.)

Thank you

**Comment by UtechtDustin** [comment]
Will test it tomorrow, but i think we dont need that extension.
It only contains 2 Functions which will be used on the data-sorter attribute.

Can we remove it, what do you think @wenzhixin @djhvscf

**Comment by djhvscf** [comment]
Maybe we can remove it as extension but added as example/resource

**Comment by GCru** [comment]
Could these be added to the customSort example?

**Comment by wenzhixin** [comment]
Fixed in #4692 
Example: https://live.bootstrap-table.com/code/wenzhixin/1172

Custom sort example: https://live.bootstrap-table.com/code/wenzhixin/1173

**Comment by wenzhixin** [comment]
Moved to example repo: https://github.com/wenzhixin/bootstrap-table-examples/tree/master/utils/natural-sorting
Example: https://examples.bootstrap-table.com/index.html#column-options/natural-sorting.html
