### ISSUE TITLE
pageSize changed to all

### ISSUE THREAD

**Issue by lemoatom** [wenzhixin/bootstrap-table#4688]
When I used the filterBy method, I found a problem. 
When the number of filtered data is equal to pageSize, pageSize will be changed to all. 
This will cause trouble for subsequent operations.

Please click to see the example:
https://live.bootstrap-table.com/code/lemoatom/1119
You can follow the step in the code comment.

Thanks you!

**Comment by djhvscf** [comment]
Not sure if this is a bug. It is working as design

**Comment by lemoatom** [comment]
> Not sure if this is a bug. It is working as design

pageSize should always be fixed unless the user changes it. It's unbelievable the value of pageSize could be changed when the length of data changed.

**Comment by djhvscf** [comment]
Marked as confirmed.

**Comment by wenzhixin** [comment]
Fixed in #4689

**Comment by lemoatom** [comment]
> Fixed in #4689

It is working. Thanks a lot.

**Comment by djhvscf** [comment]
Thanks @wenzhixin
