### ISSUE TITLE
Doesn't work on ng-include template in AngularJS

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#4690]
I have separate `template.html` files in my app to load different tabs with table, but the the bootstrap table doesn't load when I put the code on `template.html`

Any suggestion?

JsFiddle - https://jsfiddle.net/croaqmdz/

![image](https://user-images.githubusercontent.com/6106479/68447194-1e9e3c00-0205-11ea-8e57-870ae4d0ce41.png)

**Comment by wenzhixin** [comment]
Working example: https://jsfiddle.net/wenyi/bsvqt7xg/5/

**Comment by vickyrathee** [comment]
thanks.
