### ISSUE TITLE
pre-rows/post-rows not in dist sources?

### ISSUE THREAD

**Issue by cmacfarl** [wenzhixin/bootstrap-table#4695]
This commit for pre and post-rows

  https://github.com/wenzhixin/bootstrap-table/commit/6ad2b63ac0f715dea45b8b8c34272234e3ea07ee

Does not appear to be in the 1.15.5 dist sources.

https://github.com/wenzhixin/bootstrap-table/blob/develop/dist/bootstrap-table.js

Am I missing something?

**Comment by UtechtDustin** [comment]
12 Days later the events was removed in the commit https://github.com/wenzhixin/bootstrap-table/commit/2b9f4ba987491807184f22c030c33d14834f5ea0.
The explanation can be found here: https://github.com/wenzhixin/bootstrap-table/issues/832

Why do you need this Events ?
What is your goal ? (How can we help you?)

**Comment by cmacfarl** [comment]
Well that's what I get for attempting to google the answer.  :-)

I have a table with one column of checkboxes, and N columns of other stuff.  I am populating the table with json and I have a list of rows that should be checked and I have a criteria for determining if it should be checked or not.  Ideally, a callback after each row is populated that would allow me to check, or not, that row would be ideal.

Or even more ideally, some way to tell bootstrap-table that a property in the json represents the checkbox and if it's true it should be checked. (No post-processing required in that case).

**Comment by cmacfarl** [comment]
So this...

```
<table data-select-item-name="participant" ... >
```
Along with
```
<th data-field="participant" data-checkbox="true"  ... >
```
Seems to do what I want if the json I'm dropping into bootstrapTable() has a participant property with any value.

**Comment by wenzhixin** [comment]
[responseHandler](https://bootstrap-table.com/docs/api/table-options/#responsehandler) can solve your problem: https://live.bootstrap-table.com/code/wenzhixin/1178

**Comment by cmacfarl** [comment]
Thanks @wenzhixin I would have never discovered row had a state member from the documentation referenced alone.  The example was illustrative.

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/column-options/#checkbox

> If a value is given the Checkbox is automatically checked. Its also possible to check/uncheck the checkbox by use an formatter (return `true` to check, return `false` to uncheck).

It's according to your checkbox `field` option, in your case, you just need to set the `participant` field instead of `state`.
