### ISSUE TITLE
Response Handler

### ISSUE THREAD

**Issue by ibnerafiq** [wenzhixin/bootstrap-table#47]
Dear Wenzhixin,

Would you like to explain in detail the response handler function, if you could do this with ASP.Net MVC, this will be a plus.

Regards,

**Comment by naimhiq** [comment]
Hi @wenzhixin, 

I have a question regarding to response handler. In my bootstrap table I would like to implement a custom toolbar search but when I pass the responseHandler function I am getting an 'undefined', I am able to see the query search from the search field as an object but not able to search in the table for data. I really will appreciate if you can have a look here http://growtogether.se/iklart/ and help with with any tips to resolve this issue. I can also provide with jsfiddle if needed. 

Thanks in advanced !
