### ISSUE TITLE
1.15.x search not always trigger in IE11

### ISSUE THREAD

**Issue by twu2** [wenzhixin/bootstrap-table#4700]
the example like this:
https://examples.bootstrap-table.com/#options/search-time-out.html

input data in the search box, it's not always trigger.
for example, input 1, wait 1 second, it will refresh the data, then input 2 after 1, it won't refresh again. (move focus from search box then focus it again might trigger the search)

work fine in other browser.

and same example also work fine for 1.14.2.

**Comment by zacharyparrish** [comment]
I've actually found that my search isn't executed onKeyUp like other browsers, but onMouseUp

**Comment by sorxrob** [comment]
Anybody got a quick fix on this?
