### ISSUE TITLE
Print功能在IE 11上用不了

### ISSUE THREAD

**Issue by yanhuRicoh** [wenzhixin/bootstrap-table#4701]
https://examples.bootstrap-table.com/index.html#extensions/print.html
以上的例子在IE 11上用不了，是不支持IE浏览器吗？

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by yanhuRicoh** [comment]
https://examples.bootstrap-table.com/index.html#extensions/print.html
The example cannot work in IE 11, does bootstraptable print feature support IE browser?
