### ISSUE TITLE
Column formatter doesn't support for VUE component

### ISSUE THREAD

**Issue by cw1427** [wenzhixin/bootstrap-table#4702]
It is not a issue, just want to know if we have plan when we could have this feature.

Column formatter doesn't support for VUE component

**Comment by UtechtDustin** [comment]
The formatter should work, check our example: https://examples.bootstrap-table.com/index.html#welcomes/vue-component.html

**Comment by wenzhixin** [comment]
https://blog.bootstrap-table.com/2019/08/10/formatter-use-vue-component/
https://stackoverflow.com/questions/58773459/bootstrap-table-vuejs-onexpandrow-event-integration/58780532#58780532

**Comment by cw1427** [comment]
Thanks @wenzhixin.  Although it looks like not the same directlly implement as a render function  called back by VUE to render an VNode generated from h() funtion,  it seems like a way to achieve the goal.  Will have try. Thanks again, close the CR.

**Comment by wenzhixin** [comment]
Yes in the current version, we cannot implement as a render function directlly.
We will try to support in the future.
