### ISSUE TITLE
Reorder Column with Detail View not working correctly

### ISSUE THREAD

**Issue by dirric** [wenzhixin/bootstrap-table#4703]
See example:
https://live.bootstrap-table.com/code/dirric/1186

After the reorder takes place, an exception is thrown and no longer allows column to be reordered.
Output:
(anonymous) @ content.min.js:2
bootstrap-table-reorder-columns.min.js:10 Uncaught TypeError: Cannot set property 'fieldIndex' of undefined
    at Object.beforeStop (bootstrap-table-reorder-columns.min.js:10)
    at jquery.dragtable.js:154
beforeStop @ bootstrap-table-reorder-columns.min.js:10
(anonymous) @ jquery.dragtable.js:154
setTimeout (async)
(anonymous) @ jquery.dragtable.js:175
_trigger @ jquery-ui.min.js:6
_trigger @ jquery-ui.min.js:13
(anonymous) @ jquery-ui.min.js:6
_clear @ jquery-ui.min.js:13
(anonymous) @ jquery-ui.min.js:6
_mouseStop @ jquery-ui.min.js:12
(anonymous) @ jquery-ui.min.js:6
_mouseUp @ jquery-ui.min.js:9
(anonymous) @ jquery-ui.min.js:6
n._mouseCapture._mouseDistanceMet._mouseDelayMet._mouseUpDelegate @ jquery-ui.min.js:9
dispatch @ jquery-3.3.1.min.js:2
y.handle @ jquery-3.3.1.min.js:2

![image](https://user-images.githubusercontent.com/3699988/68893969-e5296d00-06eb-11ea-90e2-0207cca424fb.png)

**Comment by wenzhixin** [comment]
Fixed in #4679
