### ISSUE TITLE
updateByUniqueId导致<tr>的class丢失

### ISSUE THREAD

**Issue by xd404015353** [wenzhixin/bootstrap-table#4704]
我的需求是表格中的一行在被双击后添加一个样式作为标记，但是使用updateByUniqueId方法更新该行数据后class样式就不见了，请问有没有什么好的方法，在一行数据更新后不会丢失样式

> Could you please translate the issue ?

I wanted to use updateByUniqueId to update a row data,but I found the css class of the row has been changed also,Is there anyway that only update the data，thank you

**Comment by UtechtDustin** [comment]
Could you please translate the issue ?

**Comment by UtechtDustin** [comment]
@xd404015353 which css class do you mean?
While using updateByUniqueId the table will be recreated so any formatter etc. will be triggered again.

**Comment by UtechtDustin** [comment]
I close this issue, because we got no response from you within 7 days.
If you still need help please comment and we will reopen the issue.
