### ISSUE TITLE
CSV export garbled text in IE 11

### ISSUE THREAD

**Issue by yanhuRicoh** [wenzhixin/bootstrap-table#4707]
Bootstraptable CSV export feature works find in Google Chrome and Firefox, but it export garbled text(Original text is Japanese) in IE11 browser.    

Below is the exported csv file in Google Chrome and Firefox:
![data list google](https://user-images.githubusercontent.com/19463064/69029676-9f80e300-0a10-11ea-8881-87343662d976.png)

Below is the exported csv file in IE11:
![data list ie](https://user-images.githubusercontent.com/19463064/69028815-1ec0e780-0a0e-11ea-96de-8d298b495b48.png)

**Comment by wenzhixin** [comment]
Please create an issue in https://github.com/hhurz/tableExport.jquery.plugin repo.

**Comment by yanhuRicoh** [comment]
I have created an issue in https://github.com/hhurz/tableExport.jquery.plugin repo, thank you.

**Comment by djhvscf** [comment]
Ref #[tableExport.jquery.plugin/283](https://github.com/hhurz/tableExport.jquery.plugin/issues/283)
