### ISSUE TITLE
Need Example : How to load a new datatable in DetailFormatter

### ISSUE THREAD

**Issue by FranckPWK** [wenzhixin/bootstrap-table#4709]
Hello everyone,
I've got a table with a detailFormatter in it. When I click on the plus icon, it loads in ajax anoter file which itself contains a dataTable :

>   function detailFormatter(index, row, $detail) {
	var ETABID = row.ETABID;
	$detail.html('Chargement des données en ajax...');
	$.ajax({
		url: "./10-ADMINISTRATION/02-APPLIS/Reportings_Consultation/PHP/ajax01.php?ETAB="+ETABID+"&DATE_DEBUT=<?php echo $DATE_DEBUT_REPORTING;?>&DATE_FIN=<?php echo $DATE_FIN_DERNIER_MOIS_REPORTING;?>",
		method: 'GET',
		dataType: 'html'
		}).done(function(data){ $detail.html(data)
		})
  }

Problem : The second loaded Table doesnt format itself, any idea ?

Thank you for your help ;)

**Comment by wenzhixin** [comment]
Example: https://examples.bootstrap-table.com/index.html#welcomes/sub-table.html

**Comment by FranckPWK** [comment]
Thank you for your reply. That's exactly what i want but though, i dont manage to make it work in my case (i'got a very poor level in javascript...)
Franck

**Comment by wenzhixin** [comment]
You just need to use `onExpandRow`.
