### ISSUE TITLE
Column with numbers and empty values breaks

### ISSUE THREAD

**Issue by smenzer** [wenzhixin/bootstrap-table#471]
If you have a column that contains some numbers and some empty cells, sorting fails.  This is because on these lines (around 498)
```javascript
// Convert numerical values form string to float.
if ($.isNumeric(aa)) {
    aa = parseFloat(aa);
}
if ($.isNumeric(bb)) {
    bb = parseFloat(bb);
}
```
the numeric value gets converted to a float while the empty cell remains a string.  The next several conditions fail, so it falls through to line 523
```javascript
if (aa.localeCompare(bb) === -1) {
```
which fails because aa.localeCompare is undefined.  I believe that the aa and bb values should only be converted to floats if ($.isNumeric(aa) && $.isNumeric(bb)) is true

**Comment by djhvscf** [comment]
:+1:

**Comment by wenzhixin** [comment]
Please update the source and try it again: https://github.com/wenzhixin/bootstrap-table/pull/541

**Comment by bragma** [comment]
@smenzer  I'm not sure about the value used for "empty cell" in your code, but it should be fixed now. Please try:

https://jsfiddle.net/e3nk137y/820/

**Comment by wenzhixin** [comment]
Thanks for your test @bragma , close this issue.
