### ISSUE TITLE
关于onclickcell的一些问题？

### ISSUE THREAD

**Issue by JJ120706** [wenzhixin/bootstrap-table#4711]
我希望点击单元格，然后监听到相应的键盘动作后增加一行，但当我点击两次或多次某一格时，执行键盘动作，却增加了两行或者多行，而不是我想要的只增加一行，所以想问问onclickcell函数是怎么运行的？

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

---

麻烦提供下栗子？

**Comment by wenzhixin** [comment]
你可以判断增加的一行是否已经存在，是的话直接 return 掉，不要增加即可。
假如还有问题重新打开并提供例子。
