### ISSUE TITLE
requirement for BootstrapTable click method

### ISSUE THREAD

**Issue by wck821829906** [wenzhixin/bootstrap-table#4712]
as we know, BootstrapTable has onClickRow event, so I think the click method is resonable, mybe $('#container').bootstrapTable.click(row)

**Comment by wenzhixin** [comment]
```js
const data = $('#table').bootstrapTable('getData')
$('#table').find(`[data-index="${data.indexOf(row)}"]`).click()
```

https://live.bootstrap-table.com/code/wenzhixin/1211

**Comment by wck821829906** [comment]
@wenzhixin, above method can not trigger bootstrapTable onClickRow event

https://live.bootstrap-table.com/code/wck821829906/1216

**Comment by wenzhixin** [comment]
If you want to trigger the `click-row` event, you need to select the `td` element: https://live.bootstrap-table.com/code/wenzhixin/1263

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days.
If you still need help please reopen this issue.
