### ISSUE TITLE
Sticky header doesnt work with fullscreen

### ISSUE THREAD

**Issue by debuti** [wenzhixin/bootstrap-table#4716]
The extension sticky header doesnt work with fullscreen, to see the problem go to
https://live.bootstrap-table.com/code/debuti/1251

then try to use the sticky header while in fullscreen mode.

**Comment by wenzhixin** [comment]
You need to set the `stickyHeaderOffsetLeft` and `stickyHeaderOffsetRight` options:
https://live.bootstrap-table.com/code/wenzhixin/1252

**Comment by debuti** [comment]
Hi

I tried that, and even with your provided example, it is still not working. What I did is opening up your link, clicked on fullscreen to remove the editor side of the playground, then clicked on the **fullscreen icon of the table** and finally scrolled down.

Regards

**Comment by wenzhixin** [comment]
OK, thank you for the steps to reproduce the problem.

**Comment by wenzhixin** [comment]
Fixed in #4717
