### ISSUE TITLE
Cannot read property 'docs' of undefined

### ISSUE THREAD

**Issue by ComlOnline** [wenzhixin/bootstrap-table#4718]
Hi All, 
I love bootstrap table, but currently having an issue accessing data. 

The JSON is example output from apache solr
Live example:
https://live.bootstrap-table.com/code/ComlOnline/1261

As you can see the console here shows that all the values exist.
![image](https://user-images.githubusercontent.com/25977690/69649057-56f6a480-1064-11ea-996a-be438786ea72.png)

I hope it's not something stupid as I've been banging my head against a wall for a few hours and couldn't find an issue related to the same problem.

Many thanks!

**Comment by wenzhixin** [comment]
Typo: `responce` -> `response`

https://live.bootstrap-table.com/code/wenzhixin/1262

**Comment by ComlOnline** [comment]
...I cannot believe myself. Thank you
