### ISSUE TITLE
Sort: ignore href attributes

### ISSUE THREAD

**Issue by hjrb** [wenzhixin/bootstrap-table#4719]
Hello,

i think that boostrap-table is OUTSTANDING!! Love it. Thank you for maintaining it!

I'm having a small issue. When sorting, the InnerHTML of the <td> element is used.
But if you have an achor elment inside the cell the href attribute appears before the content.
This causes the href attribute to be the first significant text when sorting. 
Example `<td><a href="Users/Edit/4711">Smith Joe</a></td>`
As you can see the users ID 4711 is now dominating the sort.
I know there are custom sort functions, and I have a working workaround (<span style="display:none>Smith Joe<span>) for the issue, but it would be great if the sort would be smarter in using the displayed string for sorting instead of the innerHTML.

**Comment by wenzhixin** [comment]
If you are using `data` or from `url`, I think it is working well: https://live.bootstrap-table.com/code/wenzhixin/1264.

If you are using from `html`, you need to define a custom `sorter`.

Before: https://live.bootstrap-table.com/code/wenzhixin/1266
After: https://live.bootstrap-table.com/code/wenzhixin/1265.

**Comment by hjrb** [comment]
Hello,

Thank for your support.
I have implemented something similar to https://live.bootstrap-table.com/code/wenzhixin/1265.
But I still learned something from your post ☺ I’ll try using you code, except that I will compare the strings using localCompare

Mit freundlichem Gruß / Best regards
Hansjörg Reister
CI/OSE1
+49 160 7026596

Please consider to use the new excellent enterprise search (https://content.inside-share.bosch.com/Pages/results.aspx) to find the information you are looking for.

Von: 文翼 <notifications@github.com>
Gesendet: Mittwoch, 27. November 2019 10:46
An: wenzhixin/bootstrap-table <bootstrap-table@noreply.github.com>
Cc: Reister Hansjoerg (CI/OSE1) <Hansjoerg.Reister@de.bosch.com>; Author <author@noreply.github.com>
Betreff: Re: [wenzhixin/bootstrap-table] Sort: ignore href attributes (#4719)


If you are using data or from url, I think it is working well: https://live.bootstrap-table.com/code/wenzhixin/1264.

If you are using from html, you need to define a custom sorter.

Before: https://live.bootstrap-table.com/code/wenzhixin/1266
After: https://live.bootstrap-table.com/code/wenzhixin/1265.

**Comment by djhvscf** [comment]
@hjrb can this bug be closed?

**Comment by hjrb** [comment]
I wouldn’t consider this a bug but an improvement request.
If you want to implement it --> great
If not --> all good ☺

Mit freundlichem Gruß / Best regards
Hansjörg Reister
CI/OSE1
+49 160 7026596

Please consider to use the new excellent enterprise search (https://content.inside-share.bosch.com/Pages/results.aspx) to find the information you are looking for.

Von: Dennis Hernández <notifications@github.com>
Gesendet: Mittwoch, 27. November 2019 16:02
An: wenzhixin/bootstrap-table <bootstrap-table@noreply.github.com>
Cc: Reister Hansjoerg (CI/OSE1) <Hansjoerg.Reister@de.bosch.com>; Mention <mention@noreply.github.com>
Betreff: Re: [wenzhixin/bootstrap-table] Sort: ignore href attributes (#4719)


@hjrb<https://github.com/hjrb> can this bug be closed?

**Comment by wenzhixin** [comment]
I think it's better to use custom `sorter` than consider as a new feature.
