### ISSUE TITLE
Footer row cell merge

### ISSUE THREAD

**Issue by MemoryStealer** [wenzhixin/bootstrap-table#4723]
Footer row cells cannot be merged. Too much content will result in insufficient column width.

The table option parameters are configured as follows:
showFooter : true,
footerStyle : function(column){
return {
                    css : {'border-right': 'hidden'}
                }
}

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by MemoryStealer** [comment]
translated

**Comment by djhvscf** [comment]
Thanks. Now please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issue because we got no feedback/example from you.
If you still need help please reopen the issue.
