### ISSUE TITLE
Cannot trigger clearFilterControl without button rendered

### ISSUE THREAD

**Issue by bemueller** [wenzhixin/bootstrap-table#4724]
Hi,

for my project, I need to trigger clearance of FilterControl fields from special-styled Button somewhere else on the page. I tired to trigger `clearFilterControl` on the bootstrap table but it only works if the option `data-show-refresh` set to `true`, which also renders the button I don't want to have.
Is this an intended behaviour?

**Comment by djhvscf** [comment]
This is already implemented. See this [docs](https://bootstrap-table.com/docs/extensions/filter-control/#methods)
