### ISSUE TITLE
group by v2   group sort  problem

### ISSUE THREAD

**Issue by NaturalTravele** [wenzhixin/bootstrap-table#4727]
Hello, my English is not good, please forgive me.
After I use bootstrap-table-group-by-v2, there is a problem with sorting the group data. Not in the order shown in my linked list. I checked the information for #4413, but didn't see the solution I needed. I would like to ask how the group data is sorted?
My system is windows and uses 360 browser. You can also view the attached picture for specific situations.
[https://drive.google.com/open?id=19P1wuZW2QlDyHheloAbHUild81XIJyFH](url)

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!
For example: https://live.bootstrap-table.com/example/extensions/group-by-v2.html

**Comment by NaturalTravele** [comment]
> Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!
> For example: https://live.bootstrap-table.com/example/extensions/group-by-v2.html

Please linke url:https://live.bootstrap-table.com/code/NaturalTravele/1339

**Comment by UtechtDustin** [comment]
You can solve this issue with the a custom [sorter](https://bootstrap-table.com/docs/api/column-options/#sorter).   
Check if the row is a "total" row, then sort it down.

**Comment by UtechtDustin** [comment]
If you still need help please just ask and we will reopen the issue.

**Comment by KananSrank** [comment]
Hi , the issue is not resolved yet. 

https://live.bootstrap-table.com/code/KananSrank/6710

**Comment by wenzhixin** [comment]
@UtechtDustin please help to check this.

**Comment by UtechtDustin** [comment]
@wenzhixin i'm busy right now, i wil check that as soon i have time.
@KananSrank if i dont answered in a week please remind me.

**Comment by wenzhixin** [comment]
issue #5596
