### ISSUE TITLE
bootstrap-table-filter extension usage

### ISSUE THREAD

**Issue by utoPiC** [wenzhixin/bootstrap-table#473]
Hi!

I'm trying to make work bootstrap-table-filter extension. I've seen that since version 1.4.0 its been included to bootstrap-table. I don't know how I can define with columns must be filtered and how table date is updated depending on filter selection. Is there any documentation? 

Thanks! Congrats for your great job!

**Comment by djhvscf** [comment]
This documentation is not updated but here you can find some help.. http://wenzhixin.net.cn/p/bootstrap-table/docs/extensions.html#filter

And here is the repo https://github.com/lukaskral/bootstrap-table-filter

**Comment by ethompsy** [comment]
I am struggling with this as well. I cannot get the filter control to show using 'showFilter: true' on the Javascript declaration of the bootstrap-table.

It seems in the HTML example that a placeholder div needs to be defined and specified. How would we do this in Javascript? Why not just add it to the default toolbar?

**Comment by djhvscf** [comment]
@ethompsy  I don't know what @wenzhixin thinks about add this filter to the default toolbar

**Comment by ethompsy** [comment]
@djhvscf Do you know where I can find a working example? 
The filter extension example made me believe this would work, but it is not working. I can make a div to target. I even injected my own div into the default toolbar that pulls left like in the example. But the bigger problem that both myself and @utoPiC are having is that the usage documentation is very sparse.

**Comment by djhvscf** [comment]
I am not sure.. But let me create an example and share it with you. @ethompsy

**Comment by djhvscf** [comment]
And if you have the code that you are using.. It would be excellent.. @ethompsy

**Comment by tombedor** [comment]
Just chiming in that a working JS Fiddle would really be great. Looking around, the filter functionality from the former example is really cool!

**Comment by wenzhixin** [comment]
Same issue with #402, close this one.
