### ISSUE TITLE
Show selected state of checkbox if loaded from server

### ISSUE THREAD

**Issue by omeryounus** [wenzhixin/bootstrap-table#4730]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.
 
If you load table with radio buttons true, table will be loaded and last radio will have state set true.

Here is the code.
`<table id="table"
                           class="table-bordered"
                           data-toggle="table"
                           data-click-to-select="true"
                           data-toolbar=".btn-primary"
                           data-id-field="id"
                           data-select-item-name="id">
                        <thead>
                            <tr>
                                <th data-field="id" data-radio="true">ID</th>
                                <th data-field="name">Name</th>
                            </tr>
                        </thead>
                        <tbody>
                     <tr>
                            <td >id</td>
                            <td>name</td>
                          /tr>
                        <tr>
                            <td >id2</td>
                            <td>name2</td>
                          /tr>
                        </tbody>
                    </table>
`
The output for the table will include radio button and name column. Let's say you loaded data with 10 rows. It will then show the radio button enabled for last row and there is no way to show selected state of radio based on the data loaded from server.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by omeryounus** [comment]
Hi, Thanks for your reply.

Here is the link example that showing table with checkbox set to true in last row which I want to control.

https://live.bootstrap-table.com/code/omeryounus/1311

Let's say I want to set the checkbox true to first row. How is it possible?

**Comment by wenzhixin** [comment]
A workaround: https://live.bootstrap-table.com/code/wenzhixin/1312

**Comment by omeryounus** [comment]
I like this work around. But how can we manage the state. For instance loading the data from server which include the state value to true for the row number two. How can I preserve the state based on data coming from the server.

**Comment by wenzhixin** [comment]
You can use a non-existent field.

**Comment by omeryounus** [comment]
Can you share some example on how to do it?

**Comment by wenzhixin** [comment]
> For instance loading the data from server which include the state value to true for the row number two.

Can you show an example of what you said?

**Comment by omeryounus** [comment]
Here is the example....

loading the data from server and it setting the checkbox to last, I want to control the position of checkbox to be show true to row number 3.

https://live.bootstrap-table.com/code/omeryounus/1341

**Comment by wenzhixin** [comment]
Like this: https://live.bootstrap-table.com/code/wenzhixin/1342?

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by omeryounus** [comment]
Nope, I applied your changes, but can not get into responseHandler() function. Is this method available to newer version. 
I am using the following.
https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.js

**Comment by omeryounus** [comment]
Also, In my case, I'm rendering the rows using the template function not loading data from URL as in this example. (json/data.json)

**Comment by wenzhixin** [comment]
`responseHandler` is available in the latest version, are you using it wrong?

**Comment by UtechtDustin** [comment]
Since almost 2 month we got no response from you, if you still need help with that please reopen the issue.

**Comment by omeryounus** [comment]
Its seems to be working fine now.

**Comment by UtechtDustin** [comment]
Thank you for the feedback :-)
