### ISSUE TITLE
How to adapt the json data from rest?

### ISSUE THREAD

**Issue by billysAnna** [wenzhixin/bootstrap-table#4731]
The json from rest does not have format like 
`https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data2.json`.

What should i do?

**Comment by wenzhixin** [comment]
[`responseHandler`](https://bootstrap-table.com/docs/api/table-options/#responsehandler) can help you.

**Comment by billysAnna** [comment]
Good! That is what i want. 
I should have read the document fully. :+1:  :)
