### ISSUE TITLE
customSearch function runs but not applied when search text is empty

### ISSUE THREAD

**Issue by baaase** [wenzhixin/bootstrap-table#4733]
Hi, I think I hit a bug.

I'm trying to use the customSearch for some custom options when the value is empty, and it seems to run as expected, but it is not filtering the results.

## Example

This code uses the `customSearch` function. It displays an alert when it runs, and then should empty the table as it returns an empty array.

### Expected Result

No matter the search `text` contents, should: show the alert, and display an **empty** table.

### Actual Result

- When the search `text` is not empty, works as expected: shows the alert, and displays an **empty** table.
- When the search `text` is empty, odd result: shows the alert, and displays **all the data** in the table.

### Code
Demo code tried on the [online editor](https://live.bootstrap-table.com/):
```html
<link href="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.css" rel="stylesheet">

<script src="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.js"></script>

<table
  id="table"
  data-search="true"
  data-custom-search="customSearch"
  data-url="json/data1.json">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
</table>

<script>
  $(function() {
    $('#table').bootstrapTable({
      formatSearch: function () {
        return 'Search Item Price'
      }
    })
  })

  function customSearch(data, text) {
    alert('filter applied!');
    return [];
  }
</script>
```

**Comment by wenzhixin** [comment]
Fixed in #4739
