### ISSUE TITLE
Dropdown button on toolbar of bootstrap-table (v. 1.15.5) remain closed.

### ISSUE THREAD

**Issue by Aragorn2004** [wenzhixin/bootstrap-table#4734]
I've added bootstrap-select from [here](https://developer.snapappointments.com/bootstrap-select/) to my project (Bootstrap 3.3.7 based) to have a select tag with extended property.

But now dropdown button on toolbar (bootstrap-table v. 1.15.5) remains closed.

The problem is dropdown.js (bootstrap 3.3.37) is a dependency needed by bootstrap-select.

I've bypassed this issue with

` var ctl = $(".export.btn-group").find(".btn.btn-default.dropdown-toggle");`
`    $(".export.btn-group").find(".btn.btn-default.dropdown-toggle").click(function (d) {`
`        d.stopPropagation();`
`        var c = $(".export.btn-group").find(".dropdown-toggle")`
`        var a = $(".export.btn-group")`
`        if ($(a).find('.dropdown-menu').is(":hidden")) {`
`           if (kD1 == 0) { $(c).dropdown('toggle'); kD1 += 1 };`
`           $(c).dropdown();`
`    }`
`    return false;`
`    });`

But now the problem is for List Columns (showColumns). The Columns appears (in overflow)  but if you click on checkbox (to show or hidden column) nothing happens.

Inspecting code i see that click event on 
`<li role="menuitem">` has not been added.

Any suggestions ?

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by Aragorn2004** [comment]
Problem solved for what refer to Columns List simply removing piece of code that added a personal button to toolbar and replacing that piece with an 'insertbefore' method.
For what concerning "dropdown button on toolbar (bootstrap-table v. 1.15.5) remains closed"
confrim that problem but i've bypassed now in over reported. Thank so much.
