### ISSUE TITLE
could there add a "controllable show hide columns" feature?

### ISSUE THREAD

**Issue by chubbyerror** [wenzhixin/bootstrap-table#4735]
https://github.com/wenzhixin/bootstrap-table/blob/849470729bb19198e616d9a987f040708989b464/src/bootstrap-table.js#L558

add a new column property  , and at here add a new condition judgment that property .

well ,don't forgot the  COLUMN_DEFAULTS .

**Comment by UtechtDustin** [comment]
I think your searching for our [hideColumn](https://bootstrap-table.com/docs/api/methods/#hidecolumn) method.

**Comment by chubbyerror** [comment]
> I think your searching for our [hideColumn](https://bootstrap-table.com/docs/api/methods/#hidecolumn) method or our [showColumns](https://bootstrap-table.com/docs/api/table-options/#showcolumns) option.

no, it's not.
i wanna a feature that can control which column while in hidecolumns list. 
example:
operate mostly doesn't need show in hidecolumns list, but there's nothing can control it.

**Comment by wenzhixin** [comment]
Can you provide an [Online Example](https://live.bootstrap-table.com) to show your problem?

**Comment by chubbyerror** [comment]
is this helpful?
[https://live.bootstrap-table.com/code/chubbyerror/1371](Example)

**Comment by UtechtDustin** [comment]
Oh okay!
As example you want that "optinal" columns can be hidden, but "important" columns cant be hidden!
Sounds like a good feature, but unfortunately its not supportet right now.

For a quick workaround you can use our events, after the table is loaded you remove the options from the dropdown.

**Comment by wenzhixin** [comment]
@chubbyerror  Do you mean [switchable](https://bootstrap-table.com/docs/api/column-options/#switchable) column option: https://live.bootstrap-table.com/code/wenzhixin/1398?

**Comment by UtechtDustin** [comment]
Oh we already have a option for that ?
I guess the name is not good to find.

**Comment by chubbyerror** [comment]
> @chubbyerror Do you mean [switchable](https://bootstrap-table.com/docs/api/column-options/#switchable) column option: https://live.bootstrap-table.com/code/wenzhixin/1398?

Sorry that switchable column option is useful. it was my mistake that i haven't search enough.

**Comment by chubbyerror** [comment]
> Oh we already have a option for that ?
> I guess the name is not good to find.

i think maby add some desc at [here](https://bootstrap-table.com/docs/api/table-options/#showcolumns) will helpful,

**Comment by wenzhixin** [comment]
Updated, thanks for your suggestions.
