### ISSUE TITLE
Sort not case insensitive

### ISSUE THREAD

**Issue by SleeveShirtholes** [wenzhixin/bootstrap-table#4736]
Sorting takes capital letters into account. For example if somebody puts Steve@me.com and apple@me.com, Steve@me.com will come first because it is capitalized.

Is there currently a way to make it just sort base off the letter and not take the case of the letter into account?

**Comment by wenzhixin** [comment]
The [`sorter`](https://bootstrap-table.com/docs/api/column-options/#sorter) column option can help you.

**Comment by SleeveShirtholes** [comment]
Evidently, this turned out to be an issue with the multiple sort extension. I have include an example to help display what the issue is. As you can see there are two name's that have the same category but the difference is one name is capitalized and one name is not. This causes them to not be ordered correctly.

Example:
https://live.bootstrap-table.com/code/SleeveShirtholes/1345

Is this a bug or is there a way to get this to sort correctly?

**Comment by UtechtDustin** [comment]
Can confirm that, it seems for the first sort the sorter will be ignored.
After that the sorting works fine.

**Comment by UtechtDustin** [comment]
@djhvscf 
Which PR fixed that ?

**Comment by djhvscf** [comment]
Labeled by error. Sorry

**Comment by UtechtDustin** [comment]
@djhvscf figured out this was no mistake.
The Issue was fixed in #4807.
