### ISSUE TITLE
Tooltip with image on data 

### ISSUE THREAD

**Issue by billato** [wenzhixin/bootstrap-table#4740]
I have a column in the wenzhixin table that contains < a > that links to an image.

I need the following action:
When i hover over the < a > link, i need to show a thumbnail of the image into a tooltip. 

Any suggestions?

<table
  data-toggle="table"
  data-search="true"
  data-show-columns="true">
  <thead>
    <tr>
      <th>Thumb</th>
    </tr>
  </thead>
  <tbody>
    <tr id="tr-id-1" class="tr-class-1" data-title="bootstrap table" data-object='{"key": "value"}'>
      <td id="td-id-1" class="td-class-1" data-title="bootstrap table">
        <a href="https://pngimage.net/wp-content/uploads/2018/06/small-logo-png-1.png" target="_blank">img</a>
      </td>
    </tr>
  </tbody>
</table>

I want something like the following example but within a wenzixin table cell.
http://cssglobe.com/lab/tooltip/03/

**Comment by UtechtDustin** [comment]
Hi @billato, you can use any kind of tooltip library you want.
E.g. you could use bootstrap (https://github.com/wenzhixin/bootstrap-table/issues/4740).

Just all the tooltip functions after the table is rendered (using our events).

**Comment by wenzhixin** [comment]
I think https://github.com/wenzhixin/hint-css can help you.

**Comment by wenzhixin** [comment]
Close this issue, if the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
