### ISSUE TITLE
onUncheckAll returns (rows) instead of (rowsBefore, rowsAfter) when unchecking a group

### ISSUE THREAD

**Issue by marcosg** [wenzhixin/bootstrap-table#4741]
The onUncheckAll event returns a different number of parameters depending on if you click on a btSelectGroup checkbox or the btSelectAll checkbox. This bug only materializes when using data-group-by and data-checkbox features together.

Also, the onUncheckSome and onCheckSome events do not fire when clicking on btSelectGroup checkboxes. 

**Expected**
When I uncheck a btSelectGroup checkbox I expect onUncheckAll to return the same number of parameters as when I uncheck the btSelectAll checkbox. 
OR
When I uncheck a btSelectGroup checkbox, I expect for the onUncheckAll event not to fire and for the onUncheckSome event to fire and to return one parameter containing the affected rows.

**Actual**
When I uncheck a btSelectGroup checkbox, onUncheckAll returns one parameter containing the affected rows instead of the documented parameters (rowsAfter, rowsBefore). The onUncheckSome event is never fired.

When I uncheck the btSelectAll checkbox onUncheckAll returns the documented parameters (rowsAfter, rowsBefore), as expected.

```
<table id="table"
  data-group-by="true"
  data-group-by-field="shape"
  data-url="json/data6.json">
  <thead>
    <tr>
      <th data-checkbox=true>selected</th>
      <th data-field="shape">Shape</th>
      <th data-field="color">Color</th>
      <th data-field="area">Area</th>
    </tr>
  </thead>
</table>

<script>
  $(function() {
    $('#table').bootstrapTable()
  })
  $('#table').on('check-all.bs.table', function(e, rowsAfter, rowsBefore){
      const colorsAfter =  $.map(rowsAfter, function(row){ return row.color; });
      const colorsBefore = $.map(rowsBefore, function(row){ return row.color; });
      alert('check-all\n' + 'colorsAfter: ' + colorsAfter + '\n' + 'colorsBefore: ' + colorsBefore )
  });
  
  $('#table').on('uncheck-all.bs.table', function(e, rowsAfter, rowsBefore){
      const colorsAfter =  $.map(rowsAfter, function(row){ return row.color; });
      const colorsBefore = $.map(rowsBefore, function(row){ return row.color; });
      alert('uncheck-all\n' + 'colorsAfter: ' + colorsAfter + '\n' + 'colorsBefore: ' + colorsBefore )
  });
  
  $('#table').on('check-some.bs.table', function(e, rows){
      const colorsAfter =  $.map(rows, function(row){ return row.color; });
      const colorsBefore = $.map(rows, function(row){ return row.color; });
      alert('check-some\n' + 'colorsAfter: ' + colorsAfter + '\n' + 'colorsBefore: ' + colorsBefore )
  });

  $('#table').on('uncheck-some.bs.table', function(e, rows){
      const colorsAfter =  $.map(rows, function(row){ return row.color; });
      const colorsBefore = $.map(rows, function(row){ return row.color; });
      alert('uncheck-some\n' + 'colorsAfter: ' + colorsAfter + '\n' + 'colorsBefore: ' + colorsBefore )
  });
</script>
```

**Comment by wenzhixin** [comment]
Online example: https://live.bootstrap-table.com/code/wenzhixin/1365

**Comment by UtechtDustin** [comment]
The provided example from @wenzhixin works fine.
If you still have problems with that, please reopen the issue.

**Comment by marcosg** [comment]
Be sure that all items are selected before testing because the behavior only occurs when you unselect.  The key is in the alert that comes up to show the returned parameters. 

Notice that when you uncheck the first row that says circle (the checkbox for the circle group named btSelectGroup) you get nothing back in the colorsBefore parameter.  If you uncheck the first checkbox on the page (named btSelectAll) you get the previously selected rows in the colorsBefore parameter. The colorsBefore parameter should be populated both times.
