### ISSUE TITLE
Detailed Row after clicking on +

### ISSUE THREAD

**Issue by delios85** [wenzhixin/bootstrap-table#4744]
Good Morning I'm facing some issues using detail view in a table.
I'm loading from a json data totals for every category and, when clicking on +, I want to show detailed rows for that category. But i don't know how to mantain same formatting of the table. Could someone help me? Thanks. In the screenshot you can see the scenario mentioned above.

![image](https://user-images.githubusercontent.com/58730902/70525323-5f141100-1b47-11ea-8edc-430b5b8f3c90.png)

**Comment by delios85** [comment]
![image](https://user-images.githubusercontent.com/58730902/70527059-4d346d00-1b4b-11ea-8946-7f1b125e3d4f.png)

**Comment by wenzhixin** [comment]
You can try the treegrid extension: https://live.bootstrap-table.com/code/wenzhixin/1369

**Comment by delios85** [comment]
I've added the code to mine ( including css and js ) but Expand does not work. I've change title of columns

![image](https://user-images.githubusercontent.com/58730902/70608496-867ae480-1c00-11ea-8eb7-9ae0fcae4318.png)

**Comment by isdsava** [comment]
If this is kind of what you are after I can look back on how I did this. I think I used a closure to populate the data(from memory) and appending to the $element some divs and then appending a new table shell to those divs ( eg col-md-2 for buffer and col-md-10 for table shell) then I populated the table in the usual manner
![formattedExpand](https://user-images.githubusercontent.com/14867710/70778590-968bf300-1dbd-11ea-9cf0-52e96829bdf4.gif)

Apologies if I have misunderstood what you are after.

**Comment by delios85** [comment]
Now I've another problem, I think it's a bug of treegrid.

This is my code

var $table = $('#riepilogo-table');
    $table.bootstrapTable({
      //url:"script/buffer_budget_roll_riepilogo.php?mese="+mese+"&anno="+anno+"&clinica="+clinica,  
      url:'budget.json',
      dataType:"json",
      striped: true,
      sidePagination: 'server',
      idField: 'id',
      showColumns: true,
      columns: [
                    { field: 'Famiglia', title: 'Famiglia' },
                    { field: '#B', title: 'Period n.', align: 'center' },
                    { field: 'SB', title: 'Period €', align: 'center', formatter: 'moneyFormatter' },
                    { field: 'AB', title: 'Period €/n', align: 'center', formatter: 'moneyFormatter' },
                    { field: '#E', title: 'Actual n.', align: 'center' },
                    { field: 'SE', title: 'Actual €', align: 'center', formatter: 'moneyFormatter' },
                    { field: 'AE', title: 'Actual €/n', align: 'center', formatter: 'moneyFormatter' },
                    { field: 'DA#', title: 'Delta ABS n', align: 'center' },
                    { field: 'DAS', title: 'Delta ABS €', align: 'center', formatter: 'moneyFormatter' },
                    { field: 'DP#', title: 'Delta % n', align: 'center', formatter: 'percentualeFormatter' },
                    { field: 'DPS"', title: 'Delta % €', align: 'center', formatter: 'percentualeFormatter' }
      
      ],
      treeShowField: 'Famiglia',
      parentIdField: 'pid',
      onPostBody: function() {
        var columns = $table.bootstrapTable('getOptions').columns

        if (columns && columns[0][1].visible) {
          $table.treegrid({
            treeColumn: 0,
            onChange: function() {
              $table.bootstrapTable('resetWidth');
              //$('#riepilogo-table').bootstrapTable('hideLoading');
              $("#new-div-35").text('Budget');
              
            }
          })
        }
      }
    });


data are not showed: they appear only if I Change treeShowField value ( inserting even a casual name)

**Comment by wenzhixin** [comment]
@delios85 Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by delios85** [comment]
https://live.bootstrap-table.com/code/delios85/1405

**Comment by wenzhixin** [comment]
Your example cannot work.

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days, if you still need help please reopen the issue.
