### ISSUE TITLE
Feature Request: Selectable Rows without Checkbox column requirement.

### ISSUE THREAD

**Issue by dirric** [wenzhixin/bootstrap-table#4745]
Example:
https://live.bootstrap-table.com/code/dirric/1370

Is it feasible to allow the selection of rows without having to have a checkbox column visible.  In some data grids, the requirement to have a column enabled to select rows takes up valuable real=estate.

In the above example I tried keeping the checkbox column for selection but allowing click to select.  Hiding the checkbox column seems to be required to maintain the selection status

**Comment by wenzhixin** [comment]
I think you can use `class` to hide the `checkbox` field: https://live.bootstrap-table.com/code/wenzhixin/1399

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by dirric** [comment]
Yep that fixes it.  Thank you for the reply!
