### ISSUE TITLE
Help please, can't compile version 1.15.5

### ISSUE THREAD

**Issue by edwyn-amador** [wenzhixin/bootstrap-table#4751]
Help please, I've been having several problems on trying to compile master repository ...

After running **npm run build** command I noticed some problems due to the integration of this file (.stylelintrc) it was related to some syntax rules so I figured it out how to continue the command execution by adding the following rules exceptions:

{
  'extends': 'stylelint-config-standard',
  "rules": {
    "indentation": null,
    "selector-pseudo-element-colon-notation": null,
    "function-comma-space-after": null,
    "no-descending-specificity": null,
    "declaration-bang-space-before": null,
    "number-leading-zero": null,
    "rule-empty-line-before": null
  }
}

However stills some errors more almost in the end of the command execution and have no idea how to solve this.. this is what I'm getting, please take a look:

![GINhQquLQw (NPM Error)](https://user-images.githubusercontent.com/36249854/70849069-79dbd380-1e2e-11ea-8f17-a67a01d8eb95.png)

As you can see  above this is trying with the develop branch but I tried with the master one first and still having the same problem on both..

Thanks in advance for any help.

**Comment by UtechtDustin** [comment]
Why do you try to compile the maste branch ?
You can download it compiled :D

**Comment by edwyn-amador** [comment]
> Why do you try to compile the maste branch ?
> You can download it compiled :D

Hello, thanks for your answer @UtechtDustin , however the main reason is because I added some custom functionality to the search input on version 1.14.2 as I pay much attention to every single detail related to design/ux, an input clear button on a search input is a must for me, and because of the lack of this one on the official version, I added it for a chrome extension I worked on and now I'm updating it and also the 3rd party libs as well, so yup that's the reason.

Hope someone could help me with this as I really want to keep this chrome extension (as much as I can) always up to date.

Again, thanks for answer :)

**Comment by UtechtDustin** [comment]
So why you dont update to the neweset version which already has a clear search button buildin ?
example: https://examples.bootstrap-table.com/#options/show-search-clear-button.html

**Comment by edwyn-amador** [comment]
> So why you dont update to the neweset version which already has a clear search button build in ?
> example: https://examples.bootstrap-table.com/#options/show-search-clear-button.html

Again because the design of it, (I would prefer not to say it but well, personally I don't consider it attractive at all), my version is more minimalist and better UX on my opinion, the icon/button is embedded inside the input (not outside) and is only visible after user types and hides itself when is empty, also the search input can be cleared by pressing Esc when the input is being focused, so I still want to keep my clear button version..

However thank you, I really appreciate your help @UtechtDustin :)

**Comment by UtechtDustin** [comment]
Okay, i never build the project so @wenzhixin has to help out here.

**Comment by wenzhixin** [comment]
I can't reproduce the problem you said. What is your config? @edwyn-amador

**Comment by edwyn-amador** [comment]
Hello @wenzhixin thank you for your reply,

I'm not so much familiarized with npm so i'm not sure how can i see my config, i just downloaded the repos as I did previously on version 1.14.2 and run the commands npm install and npm run build, but without success this time.

I noticed on that "require" line (from the screenshot) copied the path of the extracted repo but without the slashes, i assume the problem is something related to that in some way.

**Comment by UtechtDustin** [comment]
@edwyn-amador 
Please try
```
npm run js:build
npm run css:build
```

**Comment by edwyn-amador** [comment]
Thank you for caring @UtechtDustin , I just did and the problem stills there.. I get this after running "npm run js:build" .. same issue

![mintty_TyPjXgeHjA (NPM RUN ERR)](https://user-images.githubusercontent.com/36249854/70861511-caf9cf00-1ee3-11ea-8354-d7885af911d8.png)

**Comment by UtechtDustin** [comment]
Then its a issue on windows i guess.
I use linux and @wenzhixin mac (i guess).
@djhvscf could you test it ?

**Comment by edwyn-amador** [comment]
@UtechtDustin  Yes, actually that's what I thought, well I mean a issue that only can be reproduced on Windows apparently, but It should exists some way to fix this, maybe is the way the files are set for compilation.. Thank you again btw.

Hope @wenzhixin could help me on this.

**Comment by lemoatom** [comment]
Same issue on windows, but i compile success on mac.

**Comment by wenzhixin** [comment]
@edwyn-amador if you don't need Vue components, you can use a workaround to solve the problem.

**Comment by edwyn-amador** [comment]
@wenzhixin That would be fine, so far I don't need the Vue component, how can I apply this workaround?

Thank you.

**Comment by wenzhixin** [comment]
You can try to remove the code form https://github.com/wenzhixin/bootstrap-table/blob/develop/rollup.config.js#L83 to 116 line.

**Comment by edwyn-amador** [comment]
Thank you @wenzhixin however I did a clean new try and now I'm getting this error after removing those lines ..

![mintty_K6yt5dpOWy (NPM Error)](https://user-images.githubusercontent.com/36249854/71085558-a94f5080-214c-11ea-8b56-1adabe5fe2a8.png)

**Comment by wenzhixin** [comment]
@edwyn-amador supported all platforms in #4766.

**Comment by edwyn-amador** [comment]
> @edwyn-amador supported all platforms in #4766.
> You can check out this branch to solve your problem.


Yup, It is working perfectly fine now :)
Thank you for the fix and support @wenzhixin!

**Comment by wenzhixin** [comment]
You're welcome. If you like Bootstrap Table, give us a star! ⭐️⭐️⭐️ Thanks!

**Comment by edwyn-amador** [comment]
Done! :D
