### ISSUE TITLE
pull #4678 data-hide-unused-select-options

### ISSUE THREAD

**Issue by timoline** [wenzhixin/bootstrap-table#4752]
https://github.com/wenzhixin/bootstrap-table/pull/4678

data-hide-unused-select-options does not work for me, also the included live examples  doesnt work

Can you please have a look?

Or isnt't it released yet?

**Comment by wenzhixin** [comment]
Yes, this PR is not released yet.

**Comment by timoline** [comment]
ok that makes a lot of sence

**Comment by wenzhixin** [comment]
Consider releasing a new version these days.
