### ISSUE TITLE
Lit-element and Formatter compatibility

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#4756]
It seems returning a [lit-html](https://lit-element.polymer-project.org/) element in a Bootstrap-table formatter causes the printing of `[object Object]`, which is the expected behaviour since lit-html aren't strings. Is there a way to make formatter functions support lit-html template strings?

https://jsfiddle.net/alfredopacino/fqnr87v6/

**Comment by djhvscf** [comment]
I'm not very familiar with lit elements. Is there any "to string" method?

**Comment by wenzhixin** [comment]
Not supported, you can use the `events` column option to handle the events: https://live.bootstrap-table.com/code/wenzhixin/1447.

**Comment by antonioaltamura** [comment]
Is there a way to make the same in a column header?
