### ISSUE TITLE
State column data conflicts with state checkbox

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#4757]
I have a state column in my data, which have value like running, completed etc for particular tasks.
But the BS table seems conflicting this column with state checkbox and instead of the actual data, it show `true` and all rows checked on page load.

https://jsfiddle.net/951wa2zr/

![image](https://user-images.githubusercontent.com/6106479/71146558-ba32bb80-224b-11ea-87c6-5d81c13415e2.png)

**Comment by wenzhixin** [comment]
You can use another non-existed field (`checked` or `state_`), online example: https://live.bootstrap-table.com/code/wenzhixin/1446.
