### ISSUE TITLE
如何让bootsstrap-table不执行字符串中的JavaScript代码，也就是恶意脚本

### ISSUE THREAD

**Issue by Linoonphan** [wenzhixin/bootstrap-table#4758]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by wenzhixin** [comment]
Do you mean `escape` option: https://bootstrap-table.com/docs/api/column-options/#escape?

**Comment by wenzhixin** [comment]
Close this issue, if the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
