### ISSUE TITLE
Reset search with text doesn't work when the extension filter-control is involved

### ISSUE THREAD

**Issue by kelvinchoi** [wenzhixin/bootstrap-table#4759]
The functionality works fine without filter control.  Looks like the function resetSearch has been redefined in the extension but the input text is missing as the parameter.

Here is the [Example](https://live.bootstrap-table.com/code/kelvinchoi/1457).

Browser: Chrome
Version of bootstrap-table: 1.15.5

Thanks.

**Comment by UtechtDustin** [comment]
Thank your for the bug report.
The issue is already fixed in our development branch.
Example: https://live.bootstrap-table.com/code/UtechtDustin/1460

That means the bug will be fixed in the next update ! :-)
