### ISSUE TITLE
The refresh method of bootstrap-table-vue, no query parameters in the request body

### ISSUE THREAD

**Issue by duanluan** [wenzhixin/bootstrap-table#4760]
After clicking the search button, there are no query parameters in the request body. (Whether the URL can be used or not, clicking the search button can also show my problem)

[https://jsfiddle.net/duanluan/gwuc9d84/23/](https://jsfiddle.net/duanluan/gwuc9d84/23/)

**Comment by wenzhixin** [comment]
You are using in a wrong way: https://live.bootstrap-table.com/code/wenzhixin/1461

**Comment by duanluan** [comment]
> You are using in a wrong way: https://live.bootstrap-table.com/code/wenzhixin/1461

Thank you very much for your prompt reply. I wrote it wrong.
