### ISSUE TITLE
Image inside table broken

### ISSUE THREAD

**Issue by oitsuki** [wenzhixin/bootstrap-table#4769]
Hello,

With this approach, my image are broken inside the table, The first time it's ok, but if I refresh, the image are broken.
I tested without `data-src` and works fine. 
If I remove `data-toggle="table"`, I saw the image with` data-src`.

Have any idea to resolve that ?
Thank you.

example
```

 <table
    id="table"
    data-toggle="table"
    data-sort-name="sort_order"
    data-sort-order="desc"
    data-toolbar="#toolbar"
    data-buttons-class="primary"
    data-show-toggle="true"
    data-show-columns="true"
    class="table table-lg table-hover table-striped"
   >
    <thead class="dataTableHeadingRow">
      <tr>
        <th data-field="action" class="text-md-right">Action</th>
      </tr>
    </thead>
    <tbody>
<td class="text-md-right" style=""><a href="http://localhost/shop/Admin/index.php?A&Categories&cID=14"><img data-src="http://localhost/shop/images/Admin/icons/edit.gif" alt="Editer" title="Editer" class="lozad media-object img-fluid"></a>&nbsp;<a href="http://localhost/shop/Admin/index.php?A&Categories&cID=14"><img data-src="http://localhost/shop/images/Admin/icons/move.gif" alt="Déplacer" title="Déplacer" class="lozad media-object img-fluid"></a>&nbsp;<a href="http://localhost/shop/Admin/index.php?AA&Categories&cID=14"><img data-src="http://localhost/shop/images/Admin/icons/delete.gif" alt="Supprimer" title="Supprimer" class="lozad media-object img-fluid"></a>&nbsp;</td>
   </tbody>
</table>
```

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by oitsuki** [comment]
https://live.bootstrap-table.com/code/oitsuki/1495

**Comment by wenzhixin** [comment]
![image](https://user-images.githubusercontent.com/2117018/71539079-d92efd00-2971-11ea-823f-16d16d7d64cf.png)

**Comment by oitsuki** [comment]
Nobody has an idea about that ?

**Comment by UtechtDustin** [comment]
@oitsuki 
The issue was already marked by @wenzhixin, you used data-src instead of src.
Example without data-src: https://live.bootstrap-table.com/code/UtechtDustin/1534

**Comment by oitsuki** [comment]
Ok (that's I showed in my example) but with data-src, what is the solution?

**Comment by UtechtDustin** [comment]
data-src is no attribute for a image source, why you need it ?
Better explanation: https://stackoverflow.com/a/15320346
