### ISSUE TITLE
Both use customSearch() and filterby() function, filterby() can't work in 1.15.5

### ISSUE THREAD

**Issue by ppkliu** [wenzhixin/bootstrap-table#4770]
As title,
my example is below, bootstarp-table 1.15.5, chrome browser
https://live.bootstrap-table.com/code/ppkliu/1491

I traced this issue, filterby() will enter customSearch() with filter object.
But customSearch() didn't handle this filterby() caller.
The filterby() function didn't work when implement customSearch() function.

1. Setup customSearch() function
2. Run $table.bootstrapTable('filterBy', {
        id: [1, 2, 3]
      })
3. It will enter customSearch() , but I don't know how to handle filter object in customSearch().

**Comment by ppkliu** [comment]
It seem to return data by customSearch and not run default filterby() as below:

https://github.com/wenzhixin/bootstrap-table/blob/b51b655d95027ac33bdb6d5661847f36ee6634ce/dist/bootstrap-table.js
 
```

key: "initSearch",
	    value: function initSearch() {
	      var _this5 = this;
	      this.filterOptions = this.filterOptions || this.options.filterOptions;

	      if (this.options.sidePagination !== 'server') {
	        **if (this.options.customSearch) {
	          this.data = Utils.calculateObjectValue(this.options, this.options.customSearch, [this.options.data, this.searchText, this.filterColumns]);
	          return;
	        }**
```

**Comment by wenzhixin** [comment]
You need to handle the `filterBy` in the `customSearch` function, for example:
```js
      if (filter) {
        let match = false
        for (const key in filter) {
          if (filter[key].includes(+row[key])) {
            match = true
          }
        }
        return match
      }
```

Online example: https://live.bootstrap-table.com/code/wenzhixin/1497

**Comment by ppkliu** [comment]
The same issue is in #4783

**Comment by UtechtDustin** [comment]
@ppkliu 
I dont find a issue with your example.

If i uncheck group b, group be will be hidden.
After that i search for `butter` i dont see the row with id 3 because its hidden (Its group b).
If i check group b again, i also see the row with id 3.

Did i miss something ?
Could you explain it better maybe ?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response from you within 7days, if you still need help please answer my questions above.
