### ISSUE TITLE
table, checkbox, form not send all the data, just one

### ISSUE THREAD

**Issue by oitsuki** [wenzhixin/bootstrap-table#4771]
Hello,
I created a table with a checkbox to remove all on one product. 
My problem when I post the data, I receive only one data, the last data of the table.
Note with : `alert($(this).serialize())` I saw all the data. : `btSelectAll=on&id=5&id=6&id=7&id=14`
but on result on `$ _POST : array(2) { ["btSelectAll"]=> string(2) "on" ["id"]=> string(2) "14" }`  

How to resolve that ?
Below the short code

Thank you.

```
<?php
  echo HTML::form('delete_all', $this->Products->link('Products&DeleteAll&cPath=' . $current_category_id));
?>
  <div id="toolbar">
    <button id="button" class="btn btn-secondary">remove</button>
  </div>
  <script>
    var $table = $('#table')
    var $button = $('#button')

    $(function() {
      $button.click(function () {
        $('form').submit(function () {
          if (!window.confirm('Are you sure?')) return false        
        })
      })
    })
  </script>

  <table
    id="table"
    data-toggle="table"
    data-id-field="id"
    data-select-item-name="id">

   <thead>
    <tr>
      <th data-checkbox="true"></th>
      <th data-field="id" class="text-md-center" data-sortable="true"><?php echo $this->Products->getDef('id'); ?></th>
      <th></th>
     </thead>
<tbody>
<?php 
  while ...... {
<tr>
  <td></td>
   <td><?php echo $Qproducts->valueInt('products_id'); ?><td>
   <td><?php echo $Qproducts->value('products_model'); ?></td>
</tr>
<?php
}
?>
</tbody>
</form>

```

**Comment by UtechtDustin** [comment]
The table was/is not designed to be used in a form.
Please use our methods/events to get the necessary data and the submit it as ajax or the data on a existing form (then the user can press the button).

**Comment by oitsuki** [comment]
Do you have a concrete example in PHP to do that (if possible not with ajax). I am not very good in javascript.

On this : 
`$ _POST : array(2) { ["btSelectAll"]=> string(2) "on" ["id"]=> string(2) "14" }`
find a solution with that inside the table : `data-select-item-name[]="id"`
give : `btSelectAll=on&btSelectItem=5&btSelectItem=6&btSelectItem=7&btSelectItem=14`
Now just to find a solution to take $_POST data in my delete.php files
Thank you.
