### ISSUE TITLE
Server side no matches error message

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#4772]
Can I define a custom key to show server side error messages on table instead the static "no matching records found".

**Example error response 1**
```
{
 "status_code" : 408,
 "error_message" : "Request time out"
}
```

**Example error response 2**
```
{
 "status_code" : 404,
 "error_message" : "No data found."
 "help_link" : "Learn more about this error - https://domain.com/api/docs?search=404"
}
```

**Example error response 3**
```
{
 "status_code" : 500,
 "error_message" : "The API is temporary down, try refresh in few minutes"
}
```

If not already? Can I request a feature to add `data-error-key` similar to `data-data-field`  which can be used to display the error automatically and fallback to `no matching records` if no key defined or empty response.

```
<table id="table" class="table-borderless" 
 data-url="https://domain.com/v1/api"
 data-toggle="table"
 data-method="get"
 data-side-pagination="server"
 data-data-field="result"
 data-error-key="error_message"></table>
```

**Comment by vickyrathee** [comment]
Anyone?

**Comment by UtechtDustin** [comment]
@vickyrathee 
Yes its possible using the [updateFormatText](https://bootstrap-table.com/docs/api/methods/#updateformattext) method.
Example: https://live.bootstrap-table.com/code/UtechtDustin/1631

**Comment by wenzhixin** [comment]
If the problem exists reopen it.

**Comment by vickyrathee** [comment]
@UtechtDustin It seems the `onLoadError` doesn't read the server response on error? I see `undefined` on `e.data`. I don't want to define custom message on JavaScript based on status code. 

```
if (status === 404) {
        message = 'Not Found!'
      } else if (status === 502) {
        message = 'Timeout!'
      }
```

I am looking for a way to read server response key `error_message` and display that in error message.

{
 "status_code" : 408,
 "error_message" : "Request time out"
}

**Comment by wenzhixin** [comment]
You can use the `jqXHR` parameter.
https://live.bootstrap-table.com/code/wenzhixin/1640
