### ISSUE TITLE
Build the project to 1.15.6

### ISSUE THREAD

**Issue by yanhuRicoh** [wenzhixin/bootstrap-table#4773]
Could you please build your project to 1.15.6, I want to get the newest version of bootstrap-table-print.min.js, but I don't know how to build it. Thank you.

**Comment by UtechtDustin** [comment]
@wenzhixin 
The last Release is 4 month ago, could we release a new version ?

**Comment by djhvscf** [comment]
Agree

**Comment by UtechtDustin** [comment]
We will release a new version (1.16) in the next days, so this issue can be closed.
