### ISSUE TITLE
checkbox always selected

### ISSUE THREAD

**Issue by oitsuki** [wenzhixin/bootstrap-table#4774]
Hello,

I made an example to show you.
The checkbox is always automatically selected.
How to have a checkbox unselected. When You use a button, it's easy to make an error when the checkbox is selected in this case.
I do not see inside the document to make something to include an option; unselected box.

`https://live.bootstrap-table.com/code/oitsuki/1504`

**Comment by wenzhixin** [comment]
You need to remove the input[checkbox]: https://live.bootstrap-table.com/code/wenzhixin/1505

![image](https://user-images.githubusercontent.com/2117018/71618005-af3b3c00-2bf8-11ea-9230-eb694a3ffc8d.png)

**Comment by oitsuki** [comment]
Thank you
