### ISSUE TITLE
Node Js + Socket IO + Crontab + Bootstrap-table LOAD

### ISSUE THREAD

**Issue by hapvlz** [wenzhixin/bootstrap-table#4779]
Hello,

I have question, is it possible to keep current user view while doing bootstrapTable load?
For ex. when user expand detailed view for row, or change page to 2 and the table is being loaded with new actual data the view is reset and user is moved back to initial view.

`svrTable.bootstrapTable('load', list);`

Load happens every 1-2 minutes and it cause issues when user is checking the table cause everything on load is going to initial state.

Thank you in advance.

**Comment by UtechtDustin** [comment]
Its possible, but just with a workaround.
You could save the data in a array, then you can select the timestamp from e.g. a select and using the load function you can load the old data.
Which means you CANT use Ajax (execpt you handle the array thing on the serverside).

**Comment by hapvlz** [comment]
I think my question was not fully clear.
The concept of loading data is already fully working, it emit the data from serverside using Socket IO, and on client side when emit from server arrive, bootstraptable load function is triggered and then data is being pushed to table <- This fully works, data is being updated live without page refresh.

The problem is that during load current view that user has is being reset on every load.
For ex. I am user.

I open detailed view for a row, and load data is triggered and table taking latest data and then my opened detailed view for row gone.

What I want to achieve is to keep having current view just with updated data.
I think it might be hard to achieve :/

**Comment by UtechtDustin** [comment]
Maybe i dont understand it... but if you load the new data you have the latest version + the updated data or not ?

So if you see on the first load:

X Y Z
A B C

then the data was changed e.g. X Y Z to  X X Z
After a load of the new data you will see the old data + the change of X Y Z -> X X Z, which results in:

X X Z
A B C

Or is your issue that the detail view will be closed while load the new data ?

**Comment by hapvlz** [comment]
"Or is your issue that the detail view will be closed while load the new data ?"
Exactly that's my problem.

Data is loaded fully correctly as per my needs.

**Comment by hapvlz** [comment]
![test_close](https://user-images.githubusercontent.com/34927858/71644012-c560ff00-2cc1-11ea-83f9-f188a20d3808.png)

Uploaded also image, as you see on the screen.
While loading new data the opened detailed view, and also the treegrid expanded nodes are going back to initial state.

And the code that load the data is just this so there is nothing that can cause this behavior -

socket.on('serverlist', function (list) {
        svrTable.bootstrapTable('load', list);
    });

**Comment by UtechtDustin** [comment]
Oh then im sorry, we already have a issue for that #1899.
Currently the table will be re-rendered on any load, refresh, etc. , that means its hard to refactor/to add that feature.

We will hope some day that feature is working.
