### ISSUE TITLE
No matches message after double click on column with sorting

### ISSUE THREAD

**Issue by monumatik** [wenzhixin/bootstrap-table#4780]
Data fetching works well it's a little bug :)
I need to sort my column descending, so i have to double click on my column and  i can see 'no matches' message on row field for a while.
I have got 'server-side-pagination'.

**Comment by UtechtDustin** [comment]
Could you give us an example ?
It sounds like the server returns nothing.

**Comment by monumatik** [comment]
1. Data AJAX request - data returns correctly, i can see data in table.
2. Click one of column (i have got 26000 records, so server sorting and recieve sorted data back takes ~3-4 seconds).
Between click column and recieve data back i can see "no matches message".

**Comment by UtechtDustin** [comment]
Yea i understood that, but we need an example to figure out the issue!

**Comment by monumatik** [comment]
You have this issue i your documentation.
https://examples.bootstrap-table.com/#welcome.html
Double click on of column.

**Comment by UtechtDustin** [comment]
So the issue is that while loading the `no match` text willl be displayed instead of the `loading` text.

**Comment by UtechtDustin** [comment]
Please disable the [silent sort](https://bootstrap-table.com/docs/api/table-options/#silentsort) option, then the loading message will be displayed instead fo the no records text.
