### ISSUE TITLE
Improvement : Columns : A search string

### ISSUE THREAD

**Issue by FranckPWK** [wenzhixin/bootstrap-table#4781]
Hi,
Is there a way to add a search string in the colums show button ?
![image](https://user-images.githubusercontent.com/57941683/71828744-3f6afc80-30a3-11ea-9e43-de63597ee217.png)

**Comment by UtechtDustin** [comment]
No, curently its not possible to enable a search.
But it would make sense to have a feature like that.

What do you think @wenzhixin @djhvscf ?

**Comment by djhvscf** [comment]
I like the idea. But I think this should be handled as a extension. What do you think?

**Comment by FranckPWK** [comment]
As far as i can give you my point of view, it should be enabled out of the box.
But i'm not the developper :) 
Thank you for your interest !
Regards,
Franck (from France with a poor english.)
