### ISSUE TITLE
How to bypass filter in customSearch(data, text,filter) with checkbox 1.15.5

### ISSUE THREAD

**Issue by ppkliu** [wenzhixin/bootstrap-table#4783]
How to bypass filter in customSearch(data, text,filter) with checkbox 

I click checkbox in my bootstrap table, and run with customSearch.
It will run customSearch() and send filter undefiend.
It will show the following error message.

```
Uncaught TypeError: Cannot set property 'selected' of undefined
    at BootstrapTable._toggleCheck (bootstrap-table.js:6513)
    at HTMLInputElement.<anonymous> (bootstrap-table.js:5283)
    at HTMLInputElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLInputElement.y.handle (jquery-3.3.1.min.js:2)
```

I traced the bootstrap table code
```
	    key: "_toggleCheck",
	    value: function _toggleCheck(checked, index) {
	      var $el = this.$selectItem.filter("[data-index=\"".concat(index, "\"]"));
	      var row = this.data[index];

	        this.$selectItem.filter(':checked').not($el).prop('checked', false);
	      }
             // error in this line
	      row[this.header.stateField] = checked; // error in this line, row is
```

I print filter in my customSearch() function like this:

`filter undefined undefined`

I assume filter() is bootstrap-table build-in function. If we use customSearch()
it will meet so many errors with fitler().
Please give me a solution to disable filter and no affect build-in function

Thank you very much!

I add these code in my bootstrap-table
```
 { field: 'selected',
    align: 'center',
    valign: 'middle',
    checkbox: true
  },
```

**Comment by ppkliu** [comment]
It also show these error message

```
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.getItemField (bootstrap-table.js:3497)
    at HTMLTableCellElement.<anonymous> (bootstrap-table.js:5244)
    at HTMLTableCellElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLTableCellElement.y.handle (jquery-3.3.1.min.js:2)
```

```
> 	  getItemField: function getItemField(item, field, escape) {
> 	    var value = item;
> 
> 	    if (typeof field !== 'string' || item.hasOwnProperty(field)) {
> 	      return escape ? this.escapeHTML(item[field]) : item[field];
> 	    }
```

**Comment by ppkliu** [comment]
I found 1.14.2 doesn't have this checkbox toggle error issue.
The issue start from 1.15.2.
The customSearch() API maybe be changed in 1.15.2

https://bootstrap-table.com/docs/api/table-options/#customsearch

**Comment by ppkliu** [comment]
I found root cause and give it a work around solution.
The root cause is bootstarpt-table will always call initSearch() for some reasons, but in my customSearch() don't handle the case filter == null/undefined or text.length == 0.  
The workaround solution is add the following code process table itself
initSearch() and filterby() call. 
It must return  correct "data" when table self call initSearch() and filterby().

**The total solution is table self function call (initSearch() and filterby()) need to 
handle text or filter is empty case**

```
  if(IsNull(filter) && text.length == 0 ){return data;}

  if(filter && (text.length == 0)){
    let keys   = Object.keys(filter);
    let values = Object.values(filter);
    text = values;
    return data.filter(function (row) {
      return (row[keys]+"").indexOf(text) > -1
   }) }
function IsNull(Obj){
    return (Obj ==null || Obj==undefined);
}
```

#Bootstrap code
```
	    key: "initSearch",
	    value: function initSearch() {
	      var _this5 = this;

	      this.filterOptions = this.filterOptions || this.options.filterOptions;

	      if (this.options.sidePagination !== 'server') {
	        if (this.options.customSearch) {
	          this.data = Utils.calculateObjectValue(this.options, this.options.customSearch, [this.options.data, this.searchText, this.filterColumns]);
			  return;
	        }
```

**Comment by ppkliu** [comment]
The silmar issue is in #4770

**Comment by UtechtDustin** [comment]
This is no error of the bootstrap-table.
We have to call the initSearch function, because its possible to set a default search string.
So your way is correct (check if filters exists).
