### ISSUE TITLE
Replacement for TreeGrid

### ISSUE THREAD

**Issue by hapvlz** [wenzhixin/bootstrap-table#4785]
Hello Guys,

I would like to ask if there is something like TreeGrid that we can use together with Bootstrap-table?
As we all know TreeGrid in your documentation is not developed anymore since 6 years I think

**Comment by djhvscf** [comment]
We have this extension https://bootstrap-table.com/docs/extensions/treegrid/
Let us know if this is what you're looking for

**Comment by hapvlz** [comment]
Sorry seems I wasn't clear by saying "something like TreeGrid" I mean I used the extension that you mentioned. However it's not developed anymore and also not that much popular so it's hard to find any good adjustments for it or nice usages.

**Comment by UtechtDustin** [comment]
Yes, its an old lib, but its still works fine.
Is there any reason why do you request a change of the treegrid librarie ?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response from you.
If we still have to discuss about that please write a comment :-)
