### ISSUE TITLE
Multiple Column sort doesn't work with booleans

### ISSUE THREAD

**Issue by AlexSikilinda** [wenzhixin/bootstrap-table#4788]
If you include a boolean column in multiple sort condition, the column is basically ignored.

Live example: https://live.bootstrap-table.com/code/AlexSikilinda/1539

This happens because of this code:

     if (typeof aa !== 'string') {
         aa = aa.toString();
     }

from onMultipleSort:

    BootstrapTable.prototype.onMultipleSort = function() {
        var that = this;

        var cmp = function(x, y) {
            return x > y ? 1 : x < y ? -1 : 0;
        };

        var arrayCmp = function(a, b) {
            var arr1 = [],
                arr2 = [];

            for (var i = 0; i < that.options.sortPriority.length; i++) {
                var order = that.options.sortPriority[i].sortOrder === 'desc' ? -1 : 1,
                    aa = a[that.options.sortPriority[i].sortName],
                    bb = b[that.options.sortPriority[i].sortName];

                if (aa === undefined || aa === null) {
                    aa = '';
                }
                if (bb === undefined || bb === null) {
                    bb = '';
                }
                if ($.isNumeric(aa) && $.isNumeric(bb)) {
                    aa = parseFloat(aa);
                    bb = parseFloat(bb);
                }
                if (typeof aa !== 'string') {
                    aa = aa.toString();
                }

                arr1.push(
                    order * cmp(aa, bb));
                arr2.push(
                    order * cmp(bb, aa));
            }

            return cmp(arr1, arr2);
        };

        this.data.sort(function(a, b) {
            return arrayCmp(a, b);
        });

        this.initBody();
        this.assignSortableArrows();
        this.trigger('multiple-sort');
    };

So it converts one bool to a string, and then compare the string with other boolean which causes compare function to always return 0.

**Comment by djhvscf** [comment]
This is resolve here https://github.com/wenzhixin/bootstrap-table/pull/4807
