### ISSUE TITLE
客户端分页时,后台的数据只支持数组格式了吗?

### ISSUE THREAD

**Issue by jave-joe** [wenzhixin/bootstrap-table#4789]
客户端分页时,后台的数据只支持数组格式了吗?

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

使用的最新的1.15.5版本,
使用之前版本,如果是前端分页sidePagination: "client",的话,
url里接口返回来的数据可以是数组也可以是对象{data:[]},这种格式的,
现在好像之前所有返回的data对象这样的话,前端不展示数据了.
必须要后台改成返回数组才行.
还是说有地方可以进行这样的配置呢?
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by wenzhixin** [comment]
是支持的： https://live.bootstrap-table.com/code/wenzhixin/1575
假如不行的话也可以通过 `responseHandler` 来处理，不需要修改后台。
