### ISSUE TITLE
Does BootstrapTable supports more compact data format?

### ISSUE THREAD

**Issue by gahoo** [wenzhixin/bootstrap-table#479]
For example,

    var data = [
        {
            "name": "bootstrap-table",
            "stargazers_count": "526",
            "forks_count": "122"
        },
        {
            "name": "multiple-select",
            "stargazers_count": "288",
            "forks_count": "150"
        },
        {
            "name": "bootstrap-show-password",
            "stargazers_count": "32",
            "forks_count": "11"
        },
        {
            "name": "blog",
            "stargazers_count": "13",
            "forks_count": "4"
        },
        {
            "name": "scutech-redmine",
            "stargazers_count": "6",
            "forks_count": "3"
        }
    ];

Could be transform into a more compact way like this:

    var data = {
        "name": ["bootstrap-table", "multiple-select", "bootstrap-show-password", "blog", "scutech-redmine"],
        "stargazers_count": ["526", "288", "32", "13", "6"],
        "forks_count": ["122", "150", "11", "4", "3"]
    }

When loading large datasets, compact format should be more efficient.

**Comment by wenzhixin** [comment]
Hi, now it does not support, you need to transform the data manual.

**Comment by wenzhixin** [comment]
Support the way like this: 
```
[
    ["bootstrap-table", "526", "122"],
    ["multiple-select", "288", "150"],
    ...
]
```

This issue is set to `wontfix`, close it.

**Comment by ajck** [comment]
> [
>     ["bootstrap-table", "526", "122"],
>     ["multiple-select", "288", "150"],
>     ...
> ]

I tried this compact format and it doesn't seem to work - is it still supported in the code?

Or, is there another way to specify a large data set in the code, but using a compact format so the column names do not need specifying for every item in the table?

I can't use JSON as I'm relying on a server API in a corporate environment that I don't have control over, I'm getting data by AJAX, processing it locally in the browser and then want to supply it to bootstrap-table in a compact form, like the above example or similar.

Thanks.
