### ISSUE TITLE
table-bordered and bootstrap 3

### ISSUE THREAD

**Issue by ktodyruik** [wenzhixin/bootstrap-table#4790]
Hi,

I'm trying bootstrap-table out for the first time. Retrofitting it into an older app that uses bootstrap 3.

I'm having an issue with the table-bordered class. It adds some space to the left of the table, and introduces a horizontal scrollbar. See screenshot. Any suggestions on a quick fix for this? 

![2020-01-14 09_03_03-APR - Home](https://user-images.githubusercontent.com/6691649/72360371-1652f900-36ad-11ea-8cb5-0d67989c8969.png)

Thanks

**Comment by djhvscf** [comment]
Please provide us an example

**Comment by wenzhixin** [comment]
Test with `table-bordered` and it's working well in bootstrap3: https://live.bootstrap-table.com/code/wenzhixin/1574.

Close this issue because there is no response in 7 days if the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
