### ISSUE TITLE
How to submit all pages form data (issue: pagination and forms)

### ISSUE THREAD

**Issue by aflogit** [wenzhixin/bootstrap-table#4791]
Hello everyone, 

I would like to switch from DataTables to Bootstrap Table, but my unexistent knowledge of JavaScript is holding me back. I am not able to submit all pages of a paginated Bootstrap Table, which is part of a form.

With DataTables this guide: [https://www.gyrocode.com/articles/jquery-datatables-how-to-submit-all-pages-form-data/](url) helped me out, specifically the following code took care of posting the whole form / table:

      var table = $('#example').DataTable();

      // Handle form submission event 
      $('#frm-example').on('submit', function(e){
      // Prevent actual form submission
      e.preventDefault();

      // Serialize form data
      var data = table.$('input,select,textarea').serialize();

      // Submit form data via Ajax
      $.ajax({
         url: '/echo/jsonp/',
         data: data,
         success: function(data){
            console.log('Server response', data);
         }
      });

Unfortunately the line

      // Serialize form data
      var data = table.$('input,select,textarea').serialize();

doesn't seem to work with Bootstrap Table. Chrome is reporting: 
> Uncaught TypeError: table.$ is not a function

Please find here a fiddle with the original DataTables solution: [https://jsfiddle.net/gyrocode/ma0gyy28/](url) and here a fiddle with the exact same situation with Bootstrap Table: [https://jsfiddle.net/xqh7mypa/](url)

Could anybody point out, how the not working "serialise form data" line can be adapted for Bootstrap Table?

**Comment by wenzhixin** [comment]
It's very easy to do this: 

```js
// first line
var $table = $('#example').bootstrapTable();

// second line
var data = $table.find('input,select,textarea').serialize();
```

Online Example: https://live.bootstrap-table.com/code/wenzhixin/1611

**Comment by aflogit** [comment]
Thank you very much!

**Comment by UtechtDustin** [comment]
You can use the `refreshOptions` method to disable the pagination, then serialize the form data and turn pagination back on.

Example: https://live.bootstrap-table.com/code/UtechtDustin/1682

**Comment by aflogit** [comment]
Thank you, but this raises another issue: if you edit data and change, all changed data is lost.
Replication: change something on page 1, go to page 2, then back to page one and the edit is gone.
E.g. change age of Colleen Hurst from 39 to 40, go to page two (ids 11 and 12) and back to page one. Colleen has again age 39.

Please let me know if this is off-topic and I should move it to another issue.

**Comment by UtechtDustin** [comment]
Yea that is because your data was not saved back to the bootstraptable date.
You can use the [editable](https://bootstrap-table.com/docs/extensions/editable/) or the cell input (currently not documentated) extension.

**Comment by itt427** [comment]
hello,
have u figure it out?
I'm facing the same problem.
