### ISSUE TITLE
when i updata data(include columns),multiple sort‘s  drop-down list options are not updated synchronously

### ISSUE THREAD

**Issue by Peng0529** [wenzhixin/bootstrap-table#4795]
code:
`$table.bootstrapTable('refreshOptions',{columns:columns,data:data});`

Can anyone tell me how to synchronize the multiple sort options with the columns of the data? Thank you

**Comment by djhvscf** [comment]
At this moment, you can use [Destroy](https://examples.bootstrap-table.com/index.html#methods/destroy.html) method every time you need to reinit the multiple sort extension

**Comment by Peng0529** [comment]
> At this moment, you can use [Destroy](https://examples.bootstrap-table.com/index.html#methods/destroy.html) method every time you need to reinit the multiple sort extension
thank you for your reply，
Do you mean like this?
```
$table.bootstrapTable('destroy');
$table.bootstrapTable({
            columns:columns,
            data:data,
            classes:'table table-bordered table-hover table-striped',
            ....
});
```
I tried it,but nothing worked.
