### ISSUE TITLE
Bootstraptable Cookie

### ISSUE THREAD

**Issue by florianeichin** [wenzhixin/bootstrap-table#4798]
We have a Bootstraptable in our application, using the filter-control and cookie plugin. We explicitly define which cookies the table should use, but it uses almost all cookies.
So we only want the bs.table.columns cookie, but the bs.table.filterControl one is saved as well.

This is part of our code:
```
    <table id="table" 
        data-cookie="true" 
        data-cookie-cookies-enabled="['bs.table.columns']" 
        data-cookie-id-table="saveId" 
        data-pagination="true"
```

and this is a working fiddle:
https://jsfiddle.net/bvpy51L3/

**Comment by wenzhixin** [comment]
You are using the wrong way: https://live.bootstrap-table.com/code/wenzhixin/1601.
