### ISSUE TITLE
colspan dependent on rowspan

### ISSUE THREAD

**Issue by trenttownsendnsi** [wenzhixin/bootstrap-table#4799]
Colspan doesn't work without rowspan set

It seems this code in MergeCell has a bug:

    for (i = row; i < row + rowspan; i++) {
      for (j = col; j < col + colspan; j++) {
        $tr.eq(i).find('>td').eq(j).hide()
      }
    
If I want to just use colspan without having the cells filled with "-" and throwing off the entire table, I have to set rowspan to at least 2.  

I'll be glad to answer whatever questions you may have.

**Comment by trenttownsendnsi** [comment]
Well, I'm not sure about that but whatever the case, colspan isn't working properly.

**Comment by wenzhixin** [comment]
It seems working well: https://live.bootstrap-table.com/code/wenzhixin/1600.
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
Please reopen the issue if your still need help with that.

**Comment by trenttownsendnsi** [comment]
Hello.  Sorry for the delay.

I’m trying to use the info on this link:

https://examples.bootstrap-table.com/index.html#column-options/rowspan-colspan.html

Online example:  https://live.bootstrap-table.com/code/trenttownsendnsi/1702

**Comment by trenttownsendnsi** [comment]
The code in the bootstrap-table.com example link above shows this:

<table
        id="table"
        data-toggle="table"
        data-url="json/data1.json">
    <thead>
    <tr>
        <th colspan="2">Item Detail</th>
        <th data-field="id" rowspan="2" data-valign="middle">Item ID</th>
    </tr>
    <tr>
        <th data-field="name">Item Name</th>
        <th data-field="price">Item Price</th>
    </tr>
    </thead>
</table>

**Comment by wenzhixin** [comment]
https://live.bootstrap-table.com/code/wenzhixin/1703

**Comment by trenttownsendnsi** [comment]
I see that works but what do I do to make the colspan work outside of the <thead> block:

<table id="table" 
       data-classes="table table-bordered table-hover table-striped">        
  <thead>
    <tr>
      <th data-field="number">Number</th>
      <th data-field="manuf">Manuf</th>
    </tr>
  </thead>        
  <tbody>
    <tr><td colspan=2>data</td></td></tr>
    <tr>
      <td>1</td>
      <td>3Com</td>
    </tr>       
		<tr>
      <td colspan=2>data</td>
		</tr>
		<tr>
      <td>1</td>
      <td>3Com</td>
    </tr>  
  </tbody>      
</table>

<script>
  $(function() {
    $('#table').bootstrapTable()
  })
</script>

**Comment by wenzhixin** [comment]
I think it's the same problem as #4562.
ref #3462

**Comment by trenttownsendnsi** [comment]
I agree.  Same as #4562.  Has there been a solution to this?  Or do you prefer I close this and add a response to #4562?
