### ISSUE TITLE
Table not responsive design... ?

### ISSUE THREAD

**Issue by zagloo** [wenzhixin/bootstrap-table#480]
Hello,

I have the impression that table are not responsive... Is it the case ??

When I resize my window smaller, my table overflows the window....

```
<table class="table table-bordered table-striped table-responsive"
       data-toggle="table"
       data-sort-name="date"
       data-sort-order="desc"
       data-search="true"
       data-show-refresh="true">
    <thead>
```

![overflow](https://cloud.githubusercontent.com/assets/8613226/5915662/b34163e0-a608-11e4-9b43-ba786219e193.JPG)

**Comment by dinatih** [comment]
Hi, ```.table-responsive``` is a container for table.

http://getbootstrap.com/css/#tables-responsive
```
<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>
```

**Comment by wenzhixin** [comment]
Hi @zagloo , in your case, you need to use resetView method, look at the FAQ here: http://bootstrap-table.wenzhixin.net.cn/faq/. And here is an example to show you how to solve your problem: http://issues.wenzhixin.net.cn/bootstrap-table/#283.html

**Comment by zagloo** [comment]
Hi, 

@dinatih , I rectified the table-responsive container :) , but always the same problem...

@wenzhixin ,Your solution doesn't work for me :'( ...

**Comment by zagloo** [comment]
I have several problems and not just with the table ... It's not bootstrap-table I think...

**Comment by zagloo** [comment]
Hi !

I fixed my problem ! 
it was some bullshits in css prents div (display:table...) !
