### ISSUE TITLE
Columns resizing not working

### ISSUE THREAD

**Issue by pavlalexandr** [wenzhixin/bootstrap-table#4803]
Columns resizing not working after change columns visible via the toolbox. 
After first initialization table columns resizing working great. But if I hide/show any columns from the toolbox the resizing not working.
If there is a paging extension included then if I change the page then resizing become working again. 
Also if there is a big columns amount then resizing not working even from the table initialization. It can be viewed from the jsFiddle example with all columns displayed. 

The issue can be even viewed at the https://bootstrap-table.com/docs/extensions/resizable/ example. 
I have created jsFiddle for another example: https://jsfiddle.net/4cLvra1g/9/

**Comment by pavlalexandr** [comment]
I think I found the problem in bootstrap-table-resizable.js at 40 line:

```
that.$el
    .off('column-switch.bs.table, page-change.bs.table')
    .on('column-switch.bs.table, page-change.bs.table', () => {
      reInitResizable(that)
    })
```

There shouldn't be a ',' sign between 'column-switch.bs.table' and 'page-change.bs.table' events inside event binding declaration. 

Pull-request?

**Comment by wenzhixin** [comment]
Need to remove the `,`, PR is welcome.

**Comment by djhvscf** [comment]
Thanks
