### ISSUE TITLE
Only ONE Tabele. Two Tables can't be loaded

### ISSUE THREAD

**Issue by MatneX** [wenzhixin/bootstrap-table#481]
If i init tables using:
<table class="table table-bordered table-striped" data-toggle="table">

only one table will be formated. The second table will be a normal bootstrap table.

And another problem is the table header. Your script needs a table header.
When i create a table without a thead, the script throws an error.
It only works with tables with a header, but sometimes a header isn’t needed to list what’s wanted.

So it would be nice to fix that bugs.

**Comment by MatneX** [comment]
Next error is, when i init the tables with the javascript, the data-show-header="false" won't work.
You allways should pares the data-options. Sometimes it is necassary to init a script with java, but the options will be set via data-attribute.

**Comment by wenzhixin** [comment]
Hi, when you need to hide the header, you need to set table thead also, and then set the showHeader option to false, here is an example: http://bootstrap-table.wenzhixin.net.cn/examples/#hide-header

And the second problem, via javascript is different from via data attribute: http://bootstrap-table.wenzhixin.net.cn/getting-started/#usage

**Comment by MatneX** [comment]
Thx, but i know it is different. But why don't accept data attributes, when i init it via javascript? The data attribute is the easiest way to set options. And on this way the PHP can decide which options are needed.
So, showHeader won't work on javascript calls. Only on the autoload. That's sad.

But the biggest problem still is, that you can't init two tables on one page. Have you ever tried it?

And why i can't use tables without a thead? I don't want to hide them via JS. I just want no thead. But if i don't instert a thead, your script throws an error.

**Comment by MatneX** [comment]
Here is what you should change for the header problem:

change 318-324 to this:
        this.$header = this.$el.find('thead');
        if (!this.$header.length) {
            this.$header = $('<thead style="display: none"></thead>').prependTo(this.$el);
        }
        if (!this.$header.find('tr').length) {
            this.$header.append('<tr></tr>');
        }
		if (!this.$header.find('th').length) {
			for (var i = 1; i <= this.$header.next().find('tr').first().find('td').length; i++) {
				this.$header.find('tr').append('<th></th>');
			}
		}



line 457 change this:
if (!this.options.showHeader || this.options.cardView) {
to this:
if (this.$header.css('display') == 'none' || !this.options.showHeader || this.options.cardView) {



From now on, there will be only a header if a header is wanted and the js won't throw a error.



So the only Problem from now on, is that two tables can't be inited.

**Comment by wenzhixin** [comment]
In this example: http://issues.wenzhixin.net.cn/bootstrap-table/#152.html, we init two tables.

**Comment by MatneX** [comment]
You are right. It seems to work now.
The new script i have submitted, seems to fix this problem, too. On my page the second table was inited wrong, because the first was without headers. So if you include the new lines, the script will work without pre defined headers, adds new headers correctly and will hide them if they wasn't wanted.
