### ISSUE TITLE
how to autofocus in the search field when loading the page?

### ISSUE THREAD

**Issue by adonet** [wenzhixin/bootstrap-table#4817]
how to autofocus in the search field when loading the page?

there is an option to make autofocus automatic?

**Comment by djhvscf** [comment]
You can listen the [post-body event](https://bootstrap-table.com/docs/api/events/#onpostbody) and using jquery you can find the search textbox in the dom and then assign it the [focus](https://api.jquery.com/focus/)

**Comment by adonet** [comment]
thanks! but the search textbox don't have and id, I don't locate it in jquery. how can I point it?

**Comment by adonet** [comment]
> You can listen the [post-body event](https://bootstrap-table.com/docs/api/events/#onpostbody) and using jquery you can find the search textbox in the dom and then assign it the [focus](https://api.jquery.com/focus/)

thanks! but the search textbox don't have and id or name, I don't locate it in jquery. how can I point it?

**Comment by djhvscf** [comment]
Something like $(".fixed-table-toolbar .search")

**Comment by adonet** [comment]
> $(".fixed-table-toolbar .search .search-input")

don't locate it:

$('#tabla').bootstrapTable({
  onPostBody: function () {
    $(".fixed-table-toolbar .search .search-input").focus()
  }
})

I can't aim at the field

**Comment by UtechtDustin** [comment]
https://live.bootstrap-table.com/code/UtechtDustin/1618

Your example works fine for me :-)

**Comment by djhvscf** [comment]
The selector is ok. If the problem persist, please provide an example where we can see why this is not working.

**Comment by adonet** [comment]
the problem was the version of bootstrap-table, upgrade to 1.15 ... and complete! thanks!
