### ISSUE TITLE
showFullscreen: When toggle(true) doesn't make table max width/height for current window

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#4823]
when toggling "showFullscreen" I would expect the table to be enlarge to max width/height for current window...currently it keeps current size prior to being shown as full screen.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by Scnck** [comment]
I would expect the table width/height to be expanded. when first loaded you see ids 0-6. I would expect to view more rows when toggled.

https://live.bootstrap-table.com/example/methods/toggle-fullscreen.html

**Comment by UtechtDustin** [comment]
@Scnck 
Your Table already use the full width of the page so the fullscreen button dont make much sense.
As example if you use the `container` class from bootstrap the table use ~ 50% of the page width.
If you now click on the fullscreen button the Table use the full width.

Example: https://live.bootstrap-table.com/code/UtechtDustin/1633

**Comment by Scnck** [comment]
but the height should also change.

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf 
What do you think about that? 
In some situations i can agree that the width should be unset, but in the most cases the usecase just needs a fullscreen width.

**Comment by wenzhixin** [comment]
@UtechtDustin I think the `height` should be unset. 

> but in the most cases the usecase just needs a fullscreen width.

Is it possible to give some examples?

**Comment by UtechtDustin** [comment]
Im fine with unset the height, i just mean in the most cases the width is more important as the height.
