### ISSUE TITLE
JSON view (feature request)

### ISSUE THREAD

**Issue by vickyrathee** [wenzhixin/bootstrap-table#4826]
@wenzhixin  Can I request to add a feature to show data as JSON? Similar to card view. It will just show the data as JSON in `<pre><code>` and I think it will be helpful for many use cases.

![image](https://user-images.githubusercontent.com/6106479/73593677-9d68f380-452c-11ea-9978-c3a378352de1.png)

**Comment by UtechtDustin** [comment]
You can already do that with the detailFormatter or did i understood something wrong ?

**Comment by vickyrathee** [comment]
detailFormatter execute for each row and return single row only. I'd need something which can return the complete JSON like

``<pre><code>{{json here}} </code></pre>`` 

highlighted with highlight.js https://github.com/highlightjs/highlight.js/

**Comment by UtechtDustin** [comment]
@vickyrathee 
You mean like that: https://live.bootstrap-table.com/code/UtechtDustin/1639 ?

**Comment by wenzhixin** [comment]
Like this: https://live.bootstrap-table.com/code/wenzhixin/1641 ?

**Comment by vickyrathee** [comment]
@wenzhixin exactly. But the pagination is also expected to work in JSON view instead keep switching between table and json view to paginate etc.

https://live.bootstrap-table.com/code/vickyrathee/1659

**Comment by UtechtDustin** [comment]
Something like this: https://live.bootstrap-table.com/code/UtechtDustin/1661 ?

**Comment by vickyrathee** [comment]
@UtechtDustin  Not on modal dialog. We need to inject it into table itself to allow pagination on same JSON view instead closing modal and then go to next page and open model again to view json.

Similar to cardview.

**Comment by vickyrathee** [comment]
Like this - https://live.bootstrap-table.com/code/vickyrathee/1662
But for some reason the next page pagination doesn't refresh JSON data

**Comment by UtechtDustin** [comment]
That the page change dont refresh the data is logical.
You fetch the data ONCE when you click on the Button.
To always fetch the current Data you have to listen to the [onPageChange](https://bootstrap-table.com/docs/api/events/#onpagechange) Event.

But that will also not work how you do it right now, because you destroy the table!

You can create a div which will positioned above the table, that would work.

**Comment by vickyrathee** [comment]
If I use another div tag. Do I need to write separate code for pagination?
I really don't need to destroy table. I can hide it and add another div beside to show JSON while table is hidden.

Can't we make it function like card view does?

**Comment by UtechtDustin** [comment]
Just a quick idea: https://live.bootstrap-table.com/code/UtechtDustin/1663
It possible that some functions of the table will break, so you maybe have to listen to some more events (e.g. search if you will use it). Maybe you also have to reappend the template in some cases.
You have to test it :-)

**Comment by vickyrathee** [comment]
Sounds good, I will try it in my app. I believe we should add it as a native feature in future version - Card view, JSON view and Table view

It will be amazing with 3 views as most of developer use/see JSON these days because data loading from NoSQL(MongoDB, DynamoDB etc) doesn't have fixed columns to bind with table and we need to see everything loaded as JSON Document.

**Comment by UtechtDustin** [comment]
I dont think we have to add that this as native feature, beacuse this is a special usecase.
I dont ever heard that somebody(except you) want to show the json of the table data with pagination.
For the most usecases the getData Function should be enough.

We could consider about a "custom view", which is basicly a blank container.
So anybody could format it as they wish.

What do you think about that ? @wenzhixin @djhvscf

**Comment by wenzhixin** [comment]
Agree with you @UtechtDustin, if it is necessary, can consider a custom extension to implement this feature.

**Comment by vickyrathee** [comment]
Blank container will also be interesting as we will be able to customize it as table, list, code etc.

**Comment by djhvscf** [comment]
Agree with you @UtechtDustin

**Comment by UtechtDustin** [comment]
@vickyrathee im working on it (#4904).
Here is a first example (in that case for a card box view of users): https://live.bootstrap-table.com/code/UtechtDustin/1948

**Comment by vickyrathee** [comment]
@UtechtDustin Awesome, I will use it in my app as soon it's available. thanks again 👍
