### ISSUE TITLE
X-editable: save data as number rather than string/format data prior to save...

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#4827]
is there a way of save the data as a number {"Qty": 1] rather than a string {"Qty": "1")

```
{ field: "Qty", title: "Qty", editable: {
		type: 'number',
		savenochange: false,
		validate: function(num) {
			num = $.trim(num);
			if (!num.match(/^\d+$/)) {
				return 'Please enter Qty';
			}
		},
	}
},
```

**Comment by UtechtDustin** [comment]
I think this is no issue/question related to the bootstrap table.
Its more a issue/question for this repository: https://github.com/vitalets/x-editable
If i understood something wrong, please explain it :-)

**Comment by wenzhixin** [comment]
Yes, it's a issue for x-editable. https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#using-the-issue-tracker

**Comment by whitetiger21022014** [comment]
I used as below and it works

 $('#table').bootstrapTable({
              ....................
              onEditableSave: function (field, row, oldValue, $el) {
                    if (typeof oldValue === 'number') {
                        row[field] = Number(row[field]);
                    }
            }
}
