### ISSUE TITLE
Table Page List does not showed up

### ISSUE THREAD

**Issue by asuireng** [wenzhixin/bootstrap-table#483]
Hi All,

I have initialized a table using javascript as below ;

$('#mytable').bootstrapTable(
                    {
                        classes: 'table table-bordered',
                        rowStyle: 'rowStyle',
                        method: 'GET',
                        stripped: 'false',
                        url: '/User/GetData',
                        pagination: true,
                        pageList: [20, 50, 100],
                        showRefresh: true,
                        columns: [{
                            field: 'username',
                            title: 'Username',
                            sortable: true
                        }, {
                            field: "fullName",
                            title: "Full Name",
                            sortable: true
                        }]
                    });
 
my problem is that the page list option only available when number of row exceed that threshold.

For example page list will only show "20 option" when my number of row is 25, or the page list will show at all if number of row is below 20.

Does anybody know a way to still display the pagelist regardless the current number of row ?

Thank you,

**Comment by wenzhixin** [comment]
I think it is a bug, and have fixed, you can update the source code. Or set the smartDisplay option to false.

**Comment by asuireng** [comment]
Hi wenzhixin,
I set the smartDisplay to false and update the source.
Unfortunately the problem still persist.
