### ISSUE TITLE
Is it possible to disable rotating behavior of bootstrap-table pagination? 

### ISSUE THREAD

**Issue by HoomanBahreini** [wenzhixin/bootstrap-table#4830]
Firstly, I must say this plugin is really great, thanks for the great work.

This is a question: In the picture below, the table is on page 1. If user clicks prev, he would jump to the last page (i.e. the pagination is rotating)

![image](https://user-images.githubusercontent.com/32623734/73604114-59d7bd80-45f0-11ea-8bd5-9d60426f7e42.png)

Is it possible to disable this rotating behavior?

**Comment by djhvscf** [comment]
Use pagination loop for this

https://bootstrap-table.com/docs/api/table-options/#paginationloop
