### ISSUE TITLE
How to User printIgnore in table 

### ISSUE THREAD

**Issue by saurabhandroapps** [wenzhixin/bootstrap-table#4831]
i am printing table but want to ignore particular columns in print. i found printIgnore but dont know how to use it.

**Comment by UtechtDustin** [comment]
You have to set `data-print-ignore="true"` on the column.
Example: https://live.bootstrap-table.com/code/UtechtDustin/1642

**Comment by saurabhandroapps** [comment]
@UtechtDustin thank you it worked like charm
but in documentation https://bootstrap-table.com/docs/extensions/print/#printignore it says printignore only
