### ISSUE TITLE
客户端排序如何监测排序状态

### ISSUE THREAD

**Issue by skillnull** [wenzhixin/bootstrap-table#4837]
由于业务需求，需要在客户端排序添加loading，但是在onSort方法里添加loading后，无法监测什么时候排序完成，请问如何监测客户端排序完成，从而关闭自定义添加的loading。

**Comment by skillnull** [comment]
Due to business requirements, loading needs to be added in the client sorting, but after loading is added in the onSort method, it is impossible to monitor when the sorting is completed. I would like to ask how to monitor the completion of the client sorting, so as to close the loading added by the custom.

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/index.html#methods/show-hide-loading.html

**Comment by skillnull** [comment]
> https://examples.bootstrap-table.com/index.html#methods/show-hide-loading.html

可能理解错我的意思了，现在遇到的情况是，在客户端添加自定义排序的时候，无法监测什么时候排序完成，所以想问有没有方法监测客户端排序的状态。

**Comment by skillnull** [comment]
例如：
` onSort: function () {
            createLoading()
        },`
我在onSort方法里添加了一个自定义loading，我想在排序结束的时候关闭这个自定义的loading，应该怎么做。

**Comment by wenzhixin** [comment]
你的排序会很久？你可以试试使用 `onPostBody` 事件。

**Comment by skillnull** [comment]
> 你的排序会很久？你可以试试使用 `onPostBody` 事件。

1.几千条数据的时候，要等待很久。
2.在customSort里实现了关闭。
但是出现了另一个问题，就是在onSort方法里自定义添加的loading，不能立马显示，要等到排序的箭头变换的时候才显示，这时候相当于排序已经完成了，然后customSort里又立马关闭了，实际上看不到loading。
我在源码里试了一下，打印一串数字的时候，可以立马打印出来，但是当我动态改变e.target.innerText的时候，也要等待箭头变换的时候才能变换掉，请大佬这个问题该怎么解决。
` key: 'onSort', value: function (e) {

                    e.target.innerText = '999'

                    var t = e.type, o = e.currentTarget, a = 'keypress' === t ? s(o) : s(o).parent(), i = this.$header.find('th').eq(a.index());
                    return this.$header.add(this.$header_).find('span.order').remove(), this.options.sortName === a.data('field') ? this.options.sortOrder = 'asc' === this.options.sortOrder ? 'desc' : 'asc' : (this.options.sortName = a.data('field'), this.options.sortOrder = this.options.rememberOrder ? 'asc' === a.data('order') ? 'desc' : 'asc' : this.columns[this.fieldsColumnsIndex[a.data('field')]].order), this.trigger('sort', this.options.sortName, this.options.sortOrder), a.add(i).data('order', this.options.sortOrder), this.getCaret(), 'server' === this.options.sidePagination ? void this.initServer(this.options.silentSort) : void (this.initSort(), this.initBody())
                }`

**Comment by wenzhixin** [comment]
可否提供下例子？

**Comment by skillnull** [comment]
> 可否提供下例子？
> Please provide an [Online Example](https://live.bootstrap-table.com) to show the problem, thanks!

实在不好意思，由于都是内部报表数据，不方便拿来做例子。

**Comment by wenzhixin** [comment]
可以使用模拟数据？

**Comment by UtechtDustin** [comment]
I close this issue, because we got not no response from you within 7 days.
If you still need help please provide us an example.
