### ISSUE TITLE
Avoid any sorting when using data-url

### ISSUE THREAD

**Issue by frameworker2019** [wenzhixin/bootstrap-table#4838]
When using the data-url option, the url will be appended always with "order=asc".
Is there a way to switch off sorting completely to pass the url as it is to the REST device?

**Comment by UtechtDustin** [comment]
You can overwrite the [queryParams](https://bootstrap-table.com/docs/api/table-options/#queryparams) Function.
Example: https://live.bootstrap-table.com/code/UtechtDustin/1664

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days from you, if you still have a question about this issue please comment it and we will reopen the issue.
