### ISSUE TITLE
【紧急求助】pagination显示不了，求帮助，谢谢.

### ISSUE THREAD

**Issue by junneyang** [wenzhixin/bootstrap-table#484]
table定义如下：
<table data-toggle="table" 
				data-url="/queryTableData/" 
				data-classes="table table-hover table-condensed" 
				data-striped="true" 
				data-row-style="rowStyle" 
				data-sort-name="name" 
				data-sort-order="desc" 
				data-show-header="true" 
				data-query-params="queryParams" 
				data-query-params-type="limit" 
				data-show-pagination-switch="true" 
				data-pagination="true" 
				data-side-pagination="client" 
				data-page-number="1" 
				data-page-size="5" 
				data-page-list="[5, 10, 20, 50, 100, 200]" 
				data-search="true" 
				data-show-refresh="true" 
				data-show-toggle="true" 
				data-show-columns="true" 
				data-click-to-select="true" 
				data-select-item-name="myRadioName" 
				data-single-select="true" 
				data-toolbar="#toolbar" >
				
				<thead>
					<tr>
						
						<th data-field="state" data-checkbox="true" data-formatter="stateFormatter"></th>
						<th data-formatter="runningFormatter" data-halign="center" data-align="left" data-switchable="false">Index</th>
						<th data-field="name" data-sortable="true" data-halign="center" data-align="left">Name</th>
						<th data-field="stargazers_count" data-sortable="true" data-halign="center" data-align="left">Stars</th>
						<th data-field="forks_count" data-sortable="true" data-halign="center" data-align="left">Forks</th>
						<th data-field="description" data-sortable="true" data-halign="center" data-align="left">Description</th>
						<th data-field="operation" data-halign="center" data-align="center" data-formatter="operationFormatter" data-visible="false">Operation</th>
					</tr>
				</thead>
			</table>

其中, data-pagination="true" , 但是最终的页面显示是这样！

![001](https://cloud.githubusercontent.com/assets/6802322/5938398/a36b0d94-a735-11e4-91f7-24c651b348cb.jpg)

**Comment by junneyang** [comment]
<thead>
					<tr>
						
						<th data-field="state" data-checkbox="true" data-formatter="stateFormatter"></th>
						<th data-formatter="runningFormatter" data-halign="center" data-align="left" data-switchable="false">Index</th>
						<th data-field="name" data-sortable="true" data-halign="center" data-align="left">Name</th>
						<th data-field="stargazers_count" data-sortable="true" data-halign="center" data-align="left">Stars</th>
						<th data-field="forks_count" data-sortable="true" data-halign="center" data-align="left">Forks</th>
						<th data-field="description" data-sortable="true" data-halign="center" data-align="left">Description</th>
						<th data-field="operation" data-halign="center" data-align="center" data-formatter="operationFormatter" data-visible="false">Operation</th>
					</tr>
				</thead>
			</table>
-->

**Comment by wenzhixin** [comment]
数据太少，会自动隐藏分页信息，你可以设置smartDisplay为false
