### ISSUE TITLE
Saving table save state in database (Add custom save/load handler)

### ISSUE THREAD

**Issue by saurabhandroapps** [wenzhixin/bootstrap-table#4840]
i am trying to save the table save state in Database and use it again after next login.
any example

**Comment by djhvscf** [comment]
Maybe you can use the cookie extension and then do not save anything

**Comment by saurabhandroapps** [comment]
@djhvscf thank you for replying,
but cookie will clear after session expire. but want the same state if logged in again

**Comment by UtechtDustin** [comment]
The extension is called cookie but it can handle the following the storages (https://bootstrap-table.com/docs/extensions/cookie/#cookiestorage):

- cookieStorage
- localStorage
- sessionStorage

I guess localeStorage should work for you :-)

**Comment by saurabhandroapps** [comment]
but i want the settings in database, so if logged in from some other PC, will get the same filters

**Comment by UtechtDustin** [comment]
This is currently not supported, as workaround you can still use cookies and manually save/load it to the databse.
