### ISSUE TITLE
Group By - Count rows in a group

### ISSUE THREAD

**Issue by Shwela** [wenzhixin/bootstrap-table#4842]
I am using group-by-v2 extension in my Bootstrap Data table. So, the grouping is working as required.
However, I want to display the count of rows in each group in the group header itself. 
So for example, table is grouped by services: such as electrical, civil.
Electrical services group lists 3 rows while Civil group lists 2 rows.
I would want 3 displayed next to Electrical and 2 displayed next to Civil.
How can I do that?

**Comment by UtechtDustin** [comment]
You can use the [groupByFormatter](https://bootstrap-table.com/docs/extensions/group-by-v2/#groupbyformatter) for that.

Example: https://live.bootstrap-table.com/code/UtechtDustin/1669

**Comment by Shwela** [comment]
Sorry, I am new to this. It is not working when I load my data like this:
[https://live.bootstrap-table.com/code/Shwela/1670](url)

**Comment by UtechtDustin** [comment]
Because you called the bootstraptable function twice.

Working example with your data: https://live.bootstrap-table.com/code/UtechtDustin/1671

**Comment by Shwela** [comment]
Thank you. It worked. I had actually used that in permutation combination. However, I had missed a comma after data. That's why it failed. So, in my example, I left the function as is.
