### ISSUE TITLE
data-minimum-count-columns not working with cookie enabled

### ISSUE THREAD

**Issue by sunnyandroapps** [wenzhixin/bootstrap-table#4849]
i has set data-minimum-count-columns="2" and enabled cookies
scenario:
deselect all the column except last 2;
refresh the page
deselect first
refresh the page
deselect last one

**Comment by UtechtDustin** [comment]
Could you please create a example with our [editor](https://live.bootstrap-table.com/)?

**Comment by saurabhsharma2u** [comment]
example https://live.bootstrap-table.com/code/saurabhsharma2u/1720
step to produce issue
1. unselect 1 check box click run
2. unselect again and click on run
3. unselect last one and click on run

**Comment by UtechtDustin** [comment]
@saurabhsharma2u Thank you for reporting that issue, we try to fix that :-)

**Comment by sunnyandroapps** [comment]
![image](https://user-images.githubusercontent.com/20933758/74123059-5eedcb80-4bf3-11ea-8dd7-d079099667a4.png)

i am getting above error after changing the code from #4852 

also the example not working
https://live.bootstrap-table.com/code/UtechtDustin/1722

**Comment by wenzhixin** [comment]
@sunnyandroapps Because we have merged the PR, so you need to use the develop branch: https://live.bootstrap-table.com/code/wenzhixin/1754.

**Comment by sunnyandroapps** [comment]
@wenzhixin thank you the example is working.
can you please share complied version of bootstrap-table.js. i am getting error while using develop branch bootstrap-table.js

**Comment by UtechtDustin** [comment]
@sunnyandroapps we will release the next version in the next days.
