### ISSUE TITLE
POST data 

### ISSUE THREAD

**Issue by babbomaria** [wenzhixin/bootstrap-table#486]
Hi i have a question about POST capabilities when using server side pagination.

when i usually do a POST i have 

1) 
```javascript
var datavalue=  { username: usernameV, pass: passV,pass2: pass2V,isAdmin:isAdminV,isUser:isUserV,isAccount:isAccountV, submit:"Add" };
```
2)
```javascript
$.ajax({
                    type: "POST",
                    url: "adduserBE.php",
                    data: datavalue,
                    cache: false,
                    dataType: "json",
```
With the table I need to POST value in the same way so I enabled 

| | | | | |
------------ | ------------- | ------------- | ------------- | ------------- |
method | data-method | String	| 'get' |The method type to request remote data.
url | data-url | undefined |	- |A URL to request data from remote site
cache | data-cache | Boolean | true | False to disable caching of AJAX requests.
So I have 
```HTML
 <table data-toggle="table"
                                               data-url="./listCustomerBE.php"
                                               data-method="post"
                                               data-pagination="true"
                                               data-side-pagination="server"
                                               data-page-list="[5, 10, 20, 50, 100, 200]"
                                               data-search="true"
                                               data-show-refresh="true"
                                               data-show-toggle="true"
                                               data-show-columns="true"
                                               data-height="300">
```
My data is transmitted not as usual post key value but like a get string.

On server side in PHP i look at get array with 
```HTML
filter_has_var(INPUT_POST, $postVariableName)
filter_input(INPUT_POST, $postVariableName,FILTER_SANITIZE_STRING);
```
But my array $_POST is empty.
I can see the difference with firebug or chrome  when i do standard post i have all couple key value, wht i see post from table I see a string.

Is there a way to post correct key value automatically or I have to pass thru a reimplementation of the ajax call? if so HOW??

**Comment by wenzhixin** [comment]
You need to set the contentType, because the default is application/json.

**Comment by babbomaria** [comment]
What is the correct value? I think
'application/x-www-form-urlencoded'

This evening I'll try it. I use the data table, for my spare time project; so when i finish work I'll try it and I update the issue

**Comment by aiyuchen** [comment]
```
json_decode(file_get_contents('php://input')
```
