### ISSUE TITLE
(Need example) disable columns toggle checkboxes if the minimum count is reached 

### ISSUE THREAD

**Issue by sunnyandroapps** [wenzhixin/bootstrap-table#4861]
![image](https://user-images.githubusercontent.com/20933758/74123115-8b094c80-4bf3-11ea-9f06-42d659926643.png)
 i am getting above error after changing the code from #4852

also the example not working
https://live.bootstrap-table.com/code/UtechtDustin/1722

**Comment by UtechtDustin** [comment]
I guess this issue can be close, because of #4849.
