### ISSUE TITLE
v1.15.4 bug提醒

### ISSUE THREAD

**Issue by fuqqqq** [wenzhixin/bootstrap-table#4867]
版本 1.15.4，文件 bootstrap-table.js 第 1447 行
this.detailViewIcon 应为 this.options.detailViewIcon
版本 1.15.5中已经得到修正，但很多CDN网站没有更新到 1.15.5 版本，特此备注

**Comment by UtechtDustin** [comment]
Does this bug also exists in the latest verison ?
If not, please update to the latest version.

**Comment by wenzhixin** [comment]
已发布 [v1.16.0](https://bootstrap-table.com/docs/getting-started/download/#unpkg).
