### ISSUE TITLE
Get Filter-Control Values

### ISSUE THREAD

**Issue by florianeichin** [wenzhixin/bootstrap-table#4868]
I Use BT with the filter-control extension. 
I need to get the values of the active filter-controls. We used the cookie extension till now and loaded the data from the cookie. But as we want to get rid of all the cookies, we need to get the data in a different manner. Is there any builtin function to achieve this?

I expect to get back an object more or less like this:

`[{"field":"example control","text":"example value"}]`

**Comment by UtechtDustin** [comment]
No its currently not possible to get the values, what would you use instead of the cookies ?

**Comment by florianeichin** [comment]
We want to do nothing instead, we just want to have the data of the filter fields, but not store them anywhere.

**Comment by UtechtDustin** [comment]
Oh okay, so for what do you need the filter data then ?
Maybe we find a other solution/workaround.

**Comment by florianeichin** [comment]
we implemented kind of a selectAllFilteredOverPages() so we run a custom query against the backend, containing the filters.

**Comment by UtechtDustin** [comment]
Oh okay, then you can just fetch the data yourself.
As pseudo-code:
```
const $nameFilter = $('#tablename thead th:eq(0) input').val()
```
Something like that.

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by florianeichin** [comment]
Yes, I solved it with some custom code, thanks @UtechtDustin and @wenzhixin
