### ISSUE TITLE
Column filters not showing when using table fixed height

### ISSUE THREAD

**Issue by EtienneTLM** [wenzhixin/bootstrap-table#4869]
Hi, it seems there is a bug with the Filter Control extension when using the 'data-height' attribute on the table element. Tested on Chrome and Firefox.

You can see it in action by going on the online editor page for the Filter Control : https://live.bootstrap-table.com/example/extensions/filter-control.html and then adding a 'data-height' attribute to the table element (example: data-height="400")

It gives something like this :

![image](https://user-images.githubusercontent.com/18191493/74379077-1a119280-4db5-11ea-8299-2f2a7b26a9b6.png)

Thanks for your help!

**Comment by fabiawrc** [comment]
Same problem

**Comment by dougauerbach** [comment]
I concur.

**Comment by gumacuk15** [comment]
Same bug. Please fix it.

**Comment by gumacuk15** [comment]
Also in "**Full screen**" height is not working!

**Comment by djhvscf** [comment]
We need to add fitHeader override to support this. Working on it

**Comment by AntoineMam** [comment]
Hi There. Any update for this Issue? #4869 ? thanks

**Comment by UtechtDustin** [comment]
@AntoineMam Currently not, but a PR is welcome (if you have a bugfix).

**Comment by AntoineMam** [comment]
> @AntoineMam Currently not, but a PR is welcome (if you have a bugfix).

Thanks, I'have calling <script type="text/javascript" src="https://unpkg.com/bootstrap-table@1.15.5/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script> and height from last version 1.6.0 and this CDN running good, I'm not a JS dev but You can do a dif between you're twice version. I think hat you've done this way but... If I can help.
