### ISSUE TITLE
Switch to a page with JS

### ISSUE THREAD

**Issue by cdomkokao** [wenzhixin/bootstrap-table#487]
I have another question that I posted in number #447 that I didn't get an answer to.  I need to change to a certain page when my page loads and I can't figure out how to do it.  Please advise.

**Comment by wenzhixin** [comment]
#411

**Comment by djhvscf** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/selectPage-prevPage-nextPage.html
