### ISSUE TITLE
Disable columns autocalc width & Resiziable + Fixed table height

### ISSUE THREAD

**Issue by blacksheriff** [wenzhixin/bootstrap-table#4871]
Thanx for greate component.
I've to quastions:
1. How I can disable auto column width recalc? I've set fixed column width 43px for expamle style in browser showing right  "width, but computed width after load data is 59, or 65 or anything else...
![image](https://user-images.githubusercontent.com/57944588/74534966-ed40b500-4f45-11ea-86b7-050d799bf379.png)

2.  Is it possible to work with resizable columns when height of table is set to fixed value?

**Comment by wenzhixin** [comment]
1. You can use the [`class`](https://bootstrap-table.com/docs/api/column-options/#class) column option to solve your problem: https://live.bootstrap-table.com/code/wenzhixin/1830

2. Not support: https://bootstrap-table.com/docs/extensions/resizable/#known-issues

**Comment by blacksheriff** [comment]
> 1. You can use the [`class`](https://bootstrap-table.com/docs/api/column-options/#class) column option to solve your problem: https://live.bootstrap-table.com/code/wenzhixin/1830
> 2. Not support: https://bootstrap-table.com/docs/extensions/resizable/#known-issues
1. Thanx a lot for reply.  It's very difficult to make it vith class names, because a have a hundred of tables with hundred of columns. It'l be nice to have a disableRecalc flag in table options if it possible. I have a fixed width in my every column may be i can write smth in inline style?

**Comment by blacksheriff** [comment]
> 1. You can use the [`class`](https://bootstrap-table.com/docs/api/column-options/#class) column option to solve your problem: https://live.bootstrap-table.com/code/wenzhixin/1830
Unfortunatelly it doesn't help. It recalcs th and td automatically:
![image](https://user-images.githubusercontent.com/57944588/74652640-8581a880-5197-11ea-82e4-3c506e2ca805.png)

**Comment by blacksheriff** [comment]
If I not mistaken, it can be simple solve with change "width" to "min-width" for bootstrap4 respect that. 
in line 4199 bootstrap-table.js: 
`style += Utils.sprintf('width: %s; ', (column.checkbox || column.radio) && !width ? !column.showSelectTitle ? '36px' : undefined : width ? width + unitWidth : undefined);`
Referenced to https://stackoverflow.com/a/23509701:

**Comment by wenzhixin** [comment]
I think we can overwrite the CSS style for this problem.
For example:
```
td.bs-checkbox {
  width: 36px !important;
  min-width: 36px;
}
```

**Comment by blacksheriff** [comment]
> I think we can overwrite the CSS style for this problem.
> For example:
> 
> ```
> td.bs-checkbox {
>   width: 36px !important;
>   min-width: 36px;
> }
> ```

It should be set for every column for take effect. if column count over 50 it'l be large css file

**Comment by wenzhixin** [comment]
You can try to set table layout: https://live.bootstrap-table.com/code/wenzhixin/1861

**Comment by blacksheriff** [comment]
> You can try to set table layout: https://live.bootstrap-table.com/code/wenzhixin/1861

It works with "width: auto !important" in .table class
Without it, ,<th> looks fine, but <td> of 50 columns, trying to fit screen border respecting "width 100%" from bootstrap table class css.
![image](https://user-images.githubusercontent.com/57944588/74714485-ab608900-523b-11ea-9a67-f7de0550a71f.png)

**Comment by blacksheriff** [comment]
I've saved my example to show you about "table-layout: fixed; ":
https://live.bootstrap-table.com/code/blacksheriff/1865

**Comment by blacksheriff** [comment]
So what about min-width?

**Comment by blacksheriff** [comment]
?

**Comment by UtechtDustin** [comment]
@djhvscf i guess your more familiar with css :)

**Comment by blacksheriff** [comment]
> @djhvscf i guess your more familiar with css :)

My css knowledges is not critical here.
Once again, I have many dynamic tables in which from 3 to 50 fields of a given width. Auto-recalculation randomly changes this width, which is not bad, but bootstrap spoils everything - changing width randomly to fit screen, respecting "width 100%". How can I turn off auto-recalculation of columns width, or change the column style in line 4199 of bootstrap-table.js "width" to "min-width". That would help too.

**Comment by UtechtDustin** [comment]
@blacksheriff i dont mean your css knowledges :)

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by blacksheriff** [comment]
No, I'm still waiting for )

**Comment by thetphoongon** [comment]
td {
  min-width: 200px !important;
}

**Comment by mak1A4** [comment]
I solved the issue with javascript give th a class `<th class="th-min-width"></th>` and then do
```javascript
document.querySelectorAll(".th-min-width").forEach(function (el) {
  el.style.minWidth = el.style.width;
});
```
