### ISSUE TITLE
Colspan colums not showing properly with invisible child colum

### ISSUE THREAD

**Issue by YueLengM** [wenzhixin/bootstrap-table#4872]
There is some wrong with colspan colum and invisible colum.

[Online Example](https://live.bootstrap-table.com/code/YueLengM/1799)

**Comment by wenzhixin** [comment]
ref #3213, but I think it's hard to implement.

**Comment by djhvscf** [comment]
Hi! There is not any reply, in that case we are going to close this PR. Remember to add an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!
