### ISSUE TITLE
Colspan to header not showing properly

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4874]
BootstrapTable V.1.16.0

I have colspan to header and is not working properly.
You see the resulta to this link: https://live.bootstrap-table.com/code/manukieli/1811

To the browser console, they return this error: Cannot read property 'field' of undefined

**Comment by wenzhixin** [comment]
Not support this feature, there is a workaround: https://live.bootstrap-table.com/code/wenzhixin/1831.
