### ISSUE TITLE
detail View: editing data?

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#4877]
is there a built-in to allow for the x-editable functionality to be used within the detailView pane otherwise what would be the best approach to modify the data?

* subset children items of parent.

**Comment by wenzhixin** [comment]
You can use `onExpandRow` event:
https://live.bootstrap-table.com/code/wenzhixin/1866

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by Scnck** [comment]
was trying to have the changes automatically saved like if the data what in the table vs detail view
