### ISSUE TITLE
After updatiing version from 1.15.5 => 1.16, all click handlers are malfunctions

### ISSUE THREAD

**Issue by blacksheriff** [wenzhixin/bootstrap-table#4878]
After updatiing version from 1.15.5 => 1.16, all click handlers are malfunctions. OnClickRow, OnDblClickRow

**Comment by wenzhixin** [comment]
Are you using vue component?

> [Update: Updated event name to lowercase hyphen format for vue component](https://bootstrap-table.com/news/)

Need to use `lowercase + hyphen format` instead: https://bootstrap-table.com/docs/vuejs/component/#events

**Comment by UtechtDustin** [comment]
Its working on our examples: https://live.bootstrap-table.com/example/welcome.html

Please provide us an example.

**Comment by blacksheriff** [comment]
Sorry, overlocked
![image](https://user-images.githubusercontent.com/57944588/74637018-3711e100-517a-11ea-9f0d-d1066aab0bf7.png)
