### ISSUE TITLE
Filter Control Clear not Working when multiple Tables initialized

### ISSUE THREAD

**Issue by florianeichin** [wenzhixin/bootstrap-table#4879]
Filter Control is working perfectly, when only one Table is initialized. But when there are multiple ones, just the cookie is deleted. The UI doesn't update.

here is a working fiddle:
https://jsfiddle.net/jvmk92w3/

**Comment by wenzhixin** [comment]
Bug with multiple table: https://live.bootstrap-table.com/code/pwill2/1788
