### ISSUE TITLE
There is an undefined method for Table Reorder Columns

### ISSUE THREAD

**Issue by Peng0529** [wenzhixin/bootstrap-table#4880]
This error is triggered when you try to reorder columns.
[examples](https://examples.bootstrap-table.com/#extensions/reorder-columns.html)
![image](https://user-images.githubusercontent.com/39209283/74653347-f4282b80-51c2-11ea-8913-7a9ad14db1fc.png)

**Comment by UtechtDustin** [comment]
I know the reason, will fix it later.

**Comment by djhvscf** [comment]
Fix https://github.com/wenzhixin/bootstrap-table/pull/4889
