### ISSUE TITLE
group-by-v2 extension not working

### ISSUE THREAD

**Issue by ravivedantam** [wenzhixin/bootstrap-table#4881]
Group by V2 extension adds a grouping row, but does not display show/hide icons and does not minimize and maximize. The behavior is same as found in example here: https://examples.bootstrap-table.com/#extensions/group-by-v2.html, as well as the latest code I took from github (develop branch as of Feb 18 2020). 

The behavior is that it adds a grouping row (which is not in JSON data), but it does not display show / hide icons.

Live example of bootstrap-table here also has the same issue:
https://live.bootstrap-table.com/example/extensions/group-by-v2.html

--------------
On local, I am also getting this exception:
Uncaught TypeError: Super expression must either be null or a function
    at _inherits (bootstrap-table-group-by.js:1506)
    at bootstrap-table-group-by.js:1832
    at bootstrap-table-group-by.js:1872
    at bootstrap-table-group-by.js:4
    at bootstrap-table-group-by.js:5

any pointers on this exception will also be helpful.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by ravivedantam** [comment]
The example is on second link (https://live.bootstrap-table.com/example/extensions/group-by-v2.html). 
I am attaching the screenshot
![Screen Shot 2020-02-19 at 8 29 27 AM](https://user-images.githubusercontent.com/61172641/74838762-1d93a500-52f2-11ea-83d9-b02fab910021.png)

**Comment by wenzhixin** [comment]
It seems that this feature has not been implemented in this extension.

**Comment by ravivedantam** [comment]
ok. I am going to look at tree-grid extension (https://live.bootstrap-table.com/example/extensions/treegrid.html). I hesitated initially as that was in a different github repo (maxazan)

**Comment by ravivedantam** [comment]
I am closing the issue.
