### ISSUE TITLE
delete rows: on dynamically created tables

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#4883]
How/ what is the best approach to delete rows on dynamically created tables?

```
			window.operateEvents = {
				'click .remove': function (e, value, row, index) {
					$table.bootstrapTable('remove', {  <== don't know the parent table by default this in this example.
						field: 'lngTagSetNumber',
						values: [row.lngTagSetNumber]
					})
				}
			}
```

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by Scnck** [comment]
https://jsfiddle.net/apwmc9pp/

**Comment by wenzhixin** [comment]
Can you use our Online Editor? (I cannot open jsfiddle...)

**Comment by Scnck** [comment]
https://live.bootstrap-table.com/code/Scnck/1991

**Comment by UtechtDustin** [comment]
@Scnck do you mean like this: https://live.bootstrap-table.com/code/UtechtDustin/2030 ?

**Comment by Scnck** [comment]
was trying to use window.operateEvents is this possible?

**Comment by UtechtDustin** [comment]
Like this: https://live.bootstrap-table.com/code/UtechtDustin/2032 ?
