### ISSUE TITLE
fixed-columns: loading message is hanging

### ISSUE THREAD

**Issue by petahathub** [wenzhixin/bootstrap-table#4884]
Hi,

I use fixed-columns extension, two columns from left are fixed. 

Current state:
When loading data from URL, there is waiting dialog (Loading, please wait...). After loading is done, waiting dialog disappers in non-fixed columns, but in fixed columns area there is still waiting dialog. It disappers only after an action, such as clicking on table header for sorting.

Expected state:
After loading is done, waiting dialog disappers in the whole table.

You can see example at 

https://live.bootstrap-table.com/code/petahathub/1873

It shows you bug if you have horizontal scrollbar in right panel, of course, and fixed columns are in the game.

Thanks.

**Comment by wenzhixin** [comment]
Fixed in #4885
