### ISSUE TITLE
Editable plugin + table formatter

### ISSUE THREAD

**Issue by Autoflow** [wenzhixin/bootstrap-table#4886]
After saving data using editable plugin the formatter function is not applied to the updated data.
Is there a chance to get this issue fixed? If yes, i will try to setup a jsfiddle.

(i'm using a fork of x-editable which supports bootstrap 4 (popper.js) and latest bootstrap-table)

**Comment by wenzhixin** [comment]
Ref #4859 #4859
https://live.bootstrap-table.com/code/wenzhixin/1881

**Comment by Autoflow** [comment]
Ah, i see. Thanks very much.

>> This PR will check if a cell was already edited, if that is the case the display 
>> formatter will be skipped.

Doesn't make sense for my usecase. I had to remove this PR locally.

**Comment by UtechtDustin** [comment]
Could you provide us an example with your usecase ?
If that usecase makes sense we could add a option wich allows to enable/disable the formatter after a cell was edited.

**Comment by Autoflow** [comment]
Here the fiddle https://live.bootstrap-table.com/code/Autoflow/1922 of my use case.
Have to say that i can't reproduce my local issue within the fiddle.

Local issues are:
1) (cause formatter is not applied after saving) editing "ID 001" will  not be converted back to "001" after saving. ID 1 will be formatted as simply "1".
2) Bootstrap table cache will internally have "ID 001" formatted back to "ID 1) after editing. Searching for "001" will display no results.

As said this my local situation. The fiddle doesn't behave as my local environment. Sadly i have less time to debug the situation ...

**Comment by UtechtDustin** [comment]
Okay, i understand what do you mean.
That kind of usecases makes sense, so a switch for the "always use formatter" makes sense!
