### ISSUE TITLE
Column filter does not working with formatted first column row number

### ISSUE THREAD

**Issue by interloper10** [wenzhixin/bootstrap-table#4887]
I need a row number number column to help identify row contents, so I used a formatter to produce the row number.

To reproduce this, I use a basic table definition that includes three columns; a row # column, a select filter (column), and an input filter (column).  The select filter works fine, but the input filter is unresponsive.  

If I remove the row number column, the input filter will work.  

The table definition is:
```
<table style="width: 350px;"
  id="someTable"
  data-checkbox-header="false"
  data-click-to-select="true"
  data-filter-control="true"
  data-show-columns="false"
  data-sortable="false"
  data-resizable="false"
  class="table table-striped table table-bordered table-sm">
  <thead class="thead-light">
    <tr>
      <th data-formatter="runningFormatter">#</th>
      <th data-filter-control="select" data-checkbox="true" data-formatter="someAssignFormatter" data-search-formatter="false" data-filter-data="var:someAssignFilterOptions" data-show-select-title="true" data-width="150px">Assigned</th>
      <th data-field="somefield" data-filter-control="input">Org Name</th>
    </tr>
  </thead>
</table>
```

I used a runningFormatter which I pulled from a how-to example.  My scripting that includes my runningFormatter:

```
<script>
  var someAssignFilterOptions = { true: "Assigned", false: "Unassigned" };
  var someData = [{"somefield": "abc"},{"somefield": "def"},{"somefield": "hij"},{"somefield": "klm"},{"somefield": "nop"},{"somefield": "qrs"},{"somefield": "tuv"},{"somefield": "wxy"},{"somefield": "z"}];
  var someMap = new Map();

  $(document).ready(function () {
    $('#someTable').bootstrapTable({data: someData});
  });
  $('#someTable').on('check.bs.table', function ($element, row) {
    someMap.set(row.somefield, row.somefield);
  });

  function someAssignFormatter(value, row, index) {
    if (someMap.has(row.somefield)) {
      return true;
    }
    return false;
  }
  function runningFormatter(value, row, index) {
    return 1+index;
  }
</script>
```
It would be nice if bootstrap-table had a built-in option to have a row number column as the first column, but that might be difficult for extensions like this to handle - so I realize why its not there.

This is using bootstrap-table 1.15.5 and filter-control 1.15.5.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by interloper10** [comment]
Thank for fast response - I hope I saved that correctly for you.

**Comment by wenzhixin** [comment]
Like this: https://live.bootstrap-table.com/code/wenzhixin/1886 ?

**Comment by interloper10** [comment]
Yes - perfect! I should have tried with the 1.16.0.  Its only issue with older versions.
Thank you!!

**Comment by UtechtDustin** [comment]
Thank you for the feedback!
