### ISSUE TITLE
No icons to view source and browse in editor

### ISSUE THREAD

**Issue by blacksheriff** [wenzhixin/bootstrap-table#4888]
In new site examples.bootstrap-table.com no icons to  view source and browse in editor.
It's very complicate to see this link icons
![image](https://user-images.githubusercontent.com/57944588/74924436-89096f80-53e3-11ea-853a-e83c802bb480.png)

**Comment by wenzhixin** [comment]
Thanks for your feedback, I forgot to import the font-awesome CSS.
