### ISSUE TITLE
Checkbox selections are removed when interacting with pagination

### ISSUE THREAD

**Issue by bgottschall** [wenzhixin/bootstrap-table#4893]
A Bootstrap Table with checkboxes looses all selections as soon as one interacts with the pagination (no server side pagination used).  This happens since 1.15 and is also present in the current 1.16. 1.14 for example correctly maintains all selected items when navigating through pagination.

Here is an JSFiddle example with the different versions of Bootstrap Table to comment in. As soon as one switches to page 2 all items will be deselected when returning to page 1.

[JSFiddle Example](https://jsfiddle.net/a2osprLg/4/)

**Comment by UtechtDustin** [comment]
Please use the [maintainmetadata](https://bootstrap-table.com/docs/api/table-options/#maintainmetadata) option.

Example: https://examples.bootstrap-table.com/#options/maintain-meta-data.html
