### ISSUE TITLE
Problem with toggleView METHOD

### ISSUE THREAD

**Issue by zagloo** [wenzhixin/bootstrap-table#490]
Hi,

I want to use the toggleView METHOD when I load or resize my webpage but in the console I've got this error message:

```Uncaught Unknown method: toggleView``` in ```bootstrap-table.min_2.js:7 Uncaught Unknown method: toggleView```

My code :

```$(document).ready(function () {
      $('#mediaInProgressTable').bootstrapTable('toggleView');
});```

![bugmethod](https://cloud.githubusercontent.com/assets/8613226/5975346/f24d256e-a87f-11e4-8c6d-36cb8cad3298.JPG)

An idea ? thanx

**Comment by wenzhixin** [comment]
this method just added to src/bootstrap-table.js

**Comment by wenzhixin** [comment]
I will release a new version soon.

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/releases/tag/1.6.0

**Comment by zagloo** [comment]
Well done !
