### ISSUE TITLE
numPages()

### ISSUE THREAD

**Issue by Autoflow** [wenzhixin/bootstrap-table#4902]
Just wanted to implement this after appending new data:

`lastPage = $table.bootstrapTable('numPages')
$table.bootstrapTable('selectPage', lastPage)
$table.bootstrapTable('scrollTo', 'bottom');`

After reading the manual it turned out that s.th. like numPages does not exist yet.
Can you plz give me a hint how to get the number of rendered pages?

**Comment by UtechtDustin** [comment]
Your right, i also dont know why we dont have that methods.
I added them (#4903).

**Comment by UtechtDustin** [comment]
We decided to dont implement methods for that, because the values are already accessible with the `getOptions` method.

Example: https://live.bootstrap-table.com/code/UtechtDustin/1958
