### ISSUE TITLE
editable: maxlength

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#4908]
How do you dynamically assign the maxlength based on row data?
```
{ field: "Text", title: "Text",
editable: {
	type: "text",
        placement: "right",
	tpl: '<input type="text" maxlength="8">',
	},
 },
```

**Comment by wenzhixin** [comment]
I think this is an extension plugin dependency issue.
ref https://github.com/vitalets/x-editable/pull/990

**Comment by Scnck** [comment]
ok thx I updated my version but how would I set dynamic data using other row data?
