### ISSUE TITLE
maxlength: dynamically change per cell

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#4910]
Ok I was able to add the feature but how would you dynamically change the maxlength for a individual cell rather the entire column?

I think this is an extension plugin dependency issue.
ref https://github.com/vitalets/x-editable/pull/990

_Originally posted by @wenzhixin in https://github.com/wenzhixin/bootstrap-table/issues/4908#issuecomment-590625817_

**Comment by UtechtDustin** [comment]
Change based on what ?
As example you can change the template (and maxlength) based on the current content/text.
Example: https://live.bootstrap-table.com/code/UtechtDustin/2029

**Comment by Scnck** [comment]
I will, but just looking for the ability to have the maxlength change on an individual cells within the column, when applied currently it seems to apply to the entire column if set.

**Comment by UtechtDustin** [comment]
Check out my example it will change the maxlength based on the current text.
So the question is based on what do you want to change the maxlength ? (in my example its the current text)

**Comment by Scnck** [comment]
Thank you...

**Comment by UtechtDustin** [comment]
No problem, your welcome.
