### ISSUE TITLE
'.table-relax' adds '.table-bordered' class to '.table-borderless' table

### ISSUE THREAD

**Issue by hasanlsn** [wenzhixin/bootstrap-table#4911]
Hi, 
I tried to remove borders from table but i found that when i use .table-relax class, it also adds .table-bordered class too. Is this intended behaviour? if it is not, i think it has to be fixed.

**Comment by UtechtDustin** [comment]
Its working fine for me with the `classes` attribute.
Example: https://live.bootstrap-table.com/code/UtechtDustin/2021

**Comment by hasanlsn** [comment]
Oki, then it does not work with ```class``` attribute. I am going to update my code. Issue can now be closed.

Thanks
