### ISSUE TITLE
Plugins Filter Control Selector wrong table

### ISSUE THREAD

**Issue by slmint** [wenzhixin/bootstrap-table#4912]
- Firefox/73.0

trigger table's showColumns, append `<div class="no-filter-control"></div>` to table1

break function createControls , that Selector is table1 header

[Online Example](https://live.bootstrap-table.com/code/slmint/2036)

**Comment by UtechtDustin** [comment]
Thanks for the report, in our develop Branch the issue is already fixed (https://live.bootstrap-table.com/code/UtechtDustin/2047).
