### ISSUE TITLE
Header row: icon/operateEvents

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#4913]
Trying to add icon to first column header with window.operateEvents any help would be appreciated.

https://live.bootstrap-table.com/code/Scnck/2049

**Comment by wenzhixin** [comment]
The `events` does not support in the header, you can use jQuery to do this:
https://live.bootstrap-table.com/code/wenzhixin/2050

**Comment by Scnck** [comment]
why isn't this return the table id?

    $(document).on('click', '.add', function (event) {
      alert($(event.target).closest('table').attr('id'))
    })

**Comment by wenzhixin** [comment]
```
.closest('.bootstrap-table').find('table[id]')
```
https://live.bootstrap-table.com/code/wenzhixin/2052
