### ISSUE TITLE
Proxy get/Set

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#4914]
wondering why I'm not able to see when the data is set but can on the get.  I want to create some logic for the set to refresh items on my screen

https://live.bootstrap-table.com/code/Scnck/2053

**Comment by UtechtDustin** [comment]
So why do you use a proxy instead of the [onEditableSave](https://bootstrap-table.com/docs/extensions/editable/#oneditablesaveeditable-savebstable) event ?

**Comment by Scnck** [comment]
I'm trying to detect changes to the entire table on insert/deletion of rows, etc.  also I have data being changed out side of tables I want a basic trigger on changes to the JSON source object.

**Comment by UtechtDustin** [comment]
I understand that.. but with the onEditableSave event you can detect changes.
I dont think you can use the proxy because of the internal data handling of the bootstrap-table.

**Comment by Scnck** [comment]
in less I'm missing something that is on the the cell level nothing on the row level correct insert/delete, etc?

**Comment by UtechtDustin** [comment]
Yes that Event is triggerd while editing a text of a cell.
But if you also want the insert/delete of new rows, then please provide us an exmaple with that and we try to help you.

**Comment by Scnck** [comment]
trying to update on a treeview on insert/delete to show current total row count...here is what I have now.. be nice if there was a event trigger on insert/delete/any change to table
```
onPostBody: function (data) {
	var currentNode = $('#tree').jstree('get_selected', true);
	$('#tree').jstree('rename_node', currentNode, "Items ({0})".format(data.length));
	
	return false;
},
```

**Comment by UtechtDustin** [comment]
Please provide us an example(using our online editor) where you use the treeview and also where you insert/delete stuff :-)

**Comment by UtechtDustin** [comment]
I close this issue because we got no response/example from you within 7 days.
If you still need help please provide us an example (using our online editor).
