### ISSUE TITLE
在使用1.16.0的版本中，使用bootstrap-table-treegrid报RangeError:MaxiMum call stack size exceeded错误

### ISSUE THREAD

**Issue by Mrchengcj** [wenzhixin/bootstrap-table#4915]
在使用1.16.0的版本中，使用bootstrap-table-treegrid报**RangeError:MaxiMum call stack size exceeded**错误，请问什么原因？

以下是bootstrap-table-treegrid.js中57行代码（就是这段代码在报错）：
      // jquery.treegrid.js
      this.options.rowStyle = (item, idx) => {
        const res = this._rowStyle(item, idx)
        const id = item[this.options.idField] ? item[this.options.idField] : 0
        const pid = item[this.options.parentIdField] ? item[this.options.parentIdField] : 0
        res.classes = [
          res.classes || '',
          `treegrid-${id}`,
          `treegrid-parent-${pid}`
        ].join(' ')
        return res
      }
      this.initTr(node, $.inArray(node, data), data, parentDom)
    }

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/#extensions/treegrid.html
例子是可以的，麻烦提供下在线运行例子。

Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by Mrchengcj** [comment]
这个地址：http://www.zcff-soft.com/test/bootstrap-table-test/bootstrap-table-develop/test-03.html

，多点击几次查询按钮。我用的chrome浏览器测试。

**Comment by wenzhixin** [comment]
Fixed in #4940
