### ISSUE TITLE
editable edits?

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#4916]
what is the correct syntax  for the following logic.

editable: function (i, row) {
				if (!row.bool) {
					return  //not editable ....everything I do it still editable
				} else {
					return {
						type: "number",
						placement: "right",
						min: row.min,
						max: row.max,
					}
				}
			},

**Comment by Scnck** [comment]
I saw that but how do you then set the min/max ranges based on the row data?

**Comment by UtechtDustin** [comment]
We already explained how you can set the max attribute, same is possible for the min attribute.
ref #4910.

Also please always provide us an example with your problem/try!

**Comment by UtechtDustin** [comment]
I close this issue because we got no response/example from you within 7 days.
If you still need help please provide us an example using our editor!
