### ISSUE TITLE
Feature Request: Click + hold multi-select

### ISSUE THREAD

**Issue by dirric** [wenzhixin/bootstrap-table#4917]
Ability to click + hold selection for multiple rows.  This would be a great addition for the workflows I'm using bootstrap-table for.

My user base is hell-bent on having excel like functionality on the table so I'm trying to incorporate a little bit of functionality.

**Comment by UtechtDustin** [comment]
I think this feature is a edge case so you should implement it by your self.

But a feature which would make sense is to select multiple checkboxes while holding the shift.
Would this be enough for you ?

**Comment by dirric** [comment]
Okay no problem and thanks for considering.

My use case for this I have already hidden the check box column to conserve real-estate.  Right now I'm using the click-to select feature in my workflow, and am already able to select multiple rows, so the shift key would not help in this instance.

**Comment by wenzhixin** [comment]
I think you can try the [`multipleSelectRow`](https://bootstrap-table.com/docs/api/table-options/#multipleselectrow) option.
