### ISSUE TITLE
Vue Update Data bug:  Row -> Property update triggers entire table re-render.

### ISSUE THREAD

**Issue by dirric** [wenzhixin/bootstrap-table#4918]
Updating a row causes the entire table to refresh.  This is causing a lot of extra maintenance on the UI and can be detrimental to the performance.

See:
https://live.bootstrap-table.com/code/dirric/2067

In this example, I am adding an input box on to one of the columns to replace the formatting of the cell.  The update row changes the name of the first row, and that change triggers a refresh of the entire grid.

**Comment by UtechtDustin** [comment]
This is no bug, because of the design of table we rerender the Table on any action (update Data, sorting, etc.).

See #3612
