### ISSUE TITLE
Extension: Exporting with selected mode cannot export data rows exceed the number of page limit (Client side)

### ISSUE THREAD

**Issue by DingkunLiu** [wenzhixin/bootstrap-table#4920]
The correct number of rows cannot be successfully exported **when the total number of rows exceeds the page limit**. 

I have turned on the ``maintain-meta-data`` and ``client-side pagination``.

I have created an example [here](https://live.bootstrap-table.com/code/DingkunLiu/2077).  

For example, I can **check all items on the first page**, and **switch to the next page and check another three more**. Then when I export the table, **I can only get the three rows on the second page**, which is the current page I'm on.

This issue seems to be related to the issue #3377.

**Comment by DingkunLiu** [comment]
What happened? The live-bootstrap-table seems broken.

**Comment by UtechtDustin** [comment]
@wenzhixin Please check the live editor.

**Comment by wenzhixin** [comment]
Fixed in #4940
