### ISSUE TITLE
Auto expand for onExpandRow 

### ISSUE THREAD

**Issue by myosotisgit** [wenzhixin/bootstrap-table#4922]
I found this issue #3270 discussing a way to collapse all other rows when expanding 1 row.

But I'm looking these options:
- On page load auto expand all rows
- option (or button) that will  expand/collapse ALL rows in the table.

In the Examples i find this button called "hide/display pagination. So the auto expand works in a similar way... Is this already possible?

**Comment by UtechtDustin** [comment]
Something like that: https://live.bootstrap-table.com/code/UtechtDustin/2095 ?
Same is possible with a Button, to collpase the detail view use the [collpaseRow](https://bootstrap-table.com/docs/api/methods/#collapserow) method.

**Comment by myosotisgit** [comment]
That looks about right what is needed. But i have no clue how the proposed code is making the trick work.......
Im guessing this part does the magic?

```
$(() => {
    const $table = $('table');
    $table.on('post-body.bs.table', (e) => {
      const $trs = $(e.currentTarget).find('tbody tr')
      $.each($trs, function (key, tr) {
      	$table.bootstrapTable('expandRow', $(tr).data('index'));  
    	})
    })
  })
```

Im not a programmer although i can try to understand the code....

**Comment by UtechtDustin** [comment]
The code do the following:

- Waits until the table is rendered
- Fetchs all rows on the current page
- Goes trough all rows
  - Fetchs the row index
  - Opens the Detailview with the row index

**Comment by myosotisgit** [comment]
Does bootstrap-table already have a button that will expand /collapse tables row?
If so would it use similar code to yours ?

**Comment by UtechtDustin** [comment]
No there is no button build in, but if you can program you should search for someone who can program.

Yes its easy to use with a custom button.
