### ISSUE TITLE
手机端“正在努力的加载数据中，请稍后。”文字没有自适应错位

### ISSUE THREAD

**Issue by apchenjun** [wenzhixin/bootstrap-table#4924]
最新版本，当我启用手机端模式后“正在努力的加载数据中，请稍后。”这段文字没有自适应手机端样式
![image](https://user-images.githubusercontent.com/4964551/76280693-a4beb200-62cd-11ea-878f-28844f094def.png)

**Comment by wenzhixin** [comment]
Fixed in #5029
