### ISSUE TITLE
Column Reorder

### ISSUE THREAD

**Issue by malanfcm** [wenzhixin/bootstrap-table#4925]
Hi,

So I don't know if i'm being an idiot but i'm stuck with [Column Reorder](https://examples.bootstrap-table.com/index.html#extensions/reorder-columns.html)

You can reoder a column once but once that's done you cant reorder any other columns.

Dev tools specifies:
**_"Uncaught TypeError: e.persistReorderColumnsState is not a function
    at Object.beforeStop"_**

To reproduce this issue, simply:
1) Navigate to [Column Reorder](https://examples.bootstrap-table.com/index.html#extensions/reorder-columns.html)
2) Reorder a column
3) Try to reorder another column.

If you download the source and **comment out line 1319 on bootstrap-table-reorder-columns.js**
then the reorder works multiple times.

_Lastly, I don't know if by commenting out the above line breaks functionality down the line but it seems that once you reorder columns, export no longer works and breaks both the export as well as the grid._

Anyway,
Thanks for looking into this and apologies if i'm being an idiot.

**Comment by malanfcm** [comment]
Oh wait,

You need to add
<script src="~/BootstrapTable/extensions/cookie/bootstrap-table-cookie.js"></script>

On
https://bootstrap-table.com/docs/extensions/reorder-columns/
Usage doesn't mention that you need to add  the above.

Nor on the live example
https://live.bootstrap-table.com/example/extensions/reorder-columns.html

Anyway, it's fixed now.

**Comment by UtechtDustin** [comment]
@malanfcm 
The live editor will include that automatically, check on themenu the button "Libaries".

**Comment by djhvscf** [comment]
Hi @malanfcm i think it shouldn't be required to add the cookie extension. For my point of view this is a bug

**Comment by UtechtDustin** [comment]
@djhvscf its already fixed in the develop branch.

**Comment by malanfcm** [comment]
Thanks @UtechtDustin & @djhvscf 

I really appreciate the clarification and explanation.
