### ISSUE TITLE
doesn't fire "on-all" event in vue component

### ISSUE THREAD

**Issue by blacksheriff** [wenzhixin/bootstrap-table#4927]
Can't catch "on-all" event from vue component, but any other works fine: 
on-options-refresh, on-reset-view, on-dbl-click-row etc.

template:
`<bootstrap-table` ref="table" :columns="tblData.columns" :data="tblData.rows" :options="tableData.options" @on-all="UpdateColumnWidth" @on-dbl-click-row="onDblClickModalRow" @on-check="onCheckModalRow"></bootstrap-table>\'`

**Comment by UtechtDustin** [comment]
```
Update: Updated event name to lowercase hyphen format for vue component.
``
https://github.com/wenzhixin/bootstrap-table/releases

I guess you have to use `on-all` instead of `On-all`.

**Comment by blacksheriff** [comment]
It's github code autolinkcompleter ) i wrote "on-all"

**Comment by UtechtDustin** [comment]
Oh, okay then @wenzhixin have to check this issue :-)

**Comment by blacksheriff** [comment]
?

**Comment by UtechtDustin** [comment]
Please wait until @wenzhixin had time to check that.

**Comment by wenzhixin** [comment]
> Events
The calling method syntax: @on-event="onEvent".
>
> All events (without onAll) are defined in Events API.

The `onAll` method is not implemented in the Vue component. Is it necessary?
