### ISSUE TITLE
First time issue with cookie and filter-control

### ISSUE THREAD

**Issue by wollistik** [wenzhixin/bootstrap-table#4929]
I have encountered some very strange behavior when cookie + filter-control was enabled and visiting the page the first time.

My setup:
* using v0.16.0
* using webpacker
* FilterControl has a Select input
* Select options come from url
* Enabled Server side filtering

When selecting a value, the first time filtering works as expected. I also see the the cookie gets created with the current filter selection. Subsequent selections will cause the cookie to be updated, but no more requests to the server are performed.
When doing a page reload, everything works now properly.
Deleting the cookie and doing a page reload will cause again the above issue.

I tracked down the issue and created a pull request:
https://github.com/wenzhixin/bootstrap-table/pull/4928
This seems to fix the issue for me.

**Comment by UtechtDustin** [comment]
> Hi, sorry for the long time with no response. I really tried to get a working example, but could not get some working to show you the issue.
> I encountered a strange behavior, which might be the root cause.
> When you have a look at the following example, you will encounter following behavior:
>
>    open the page
    table gets initialized
    cookies for filtering/pagination will be created short time (< 1 second) after the table is displayed, even if nothing is filtered for
> 
> https://live.bootstrap-table.com/code/wollistik/2343
> The last point is where the issue - in my case the cookies do not get created in my site. I have looked through the code, but I couldn't figure out why and when this happens in the demo. It seems like this callback does not get executed when using with webpack - and therefore filtering hangs after the first time the cookie is created with filter values.

Could you send us a url where you used webpack, so we can reproduce/check the issue ?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days from you.
