### ISSUE TITLE
Wrong parsing in data-page-list 

### ISSUE THREAD

**Issue by ZeroDotNet** [wenzhixin/bootstrap-table#493]
If the value being used for data-page-list doesn't contains '[' and ']' the parsing fails and wrong page sizes are displayed. See example url.
JSFiddle example: http://jsfiddle.net/e3nk137y/457/
For `data-page-size="5, 10, 25, 50, 100, 200, 500"` the dropdown of records per page shows: 0, 10, 25, 50, 100, 200, 50

I know that the documentation says that data-page-list should be defined as an array like `[10, 25, 50 100]` but you can also allow a string definition like `"10, 25, 50, 100"` (without [ and ]) to support different scenarios.

**Comment by wenzhixin** [comment]
Merged, thanks.
