### ISSUE TITLE
icon of button can`t display

### ISSUE THREAD

**Issue by EdQzz** [wenzhixin/bootstrap-table#4931]
when I set data-show-search-button="true", the icon of button can`t display.
And when I run the example in ["Show Search Button",](https://live.bootstrap-table.com/example/options/show-search-button.html)  this issue is happend again

**Comment by UtechtDustin** [comment]
Works fine for me, which Browser (and version) do you use ?

![Bildschirmfoto 2020-03-13 um 09 34 19](https://user-images.githubusercontent.com/13292481/76603762-d8881a80-650d-11ea-99e2-df171f6bed49.png)

**Comment by EdQzz** [comment]
&nbsp;Google Chrome&nbsp; &nbsp;80.0.3987.132（正式版本） （64 位）





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dustin Utecht"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 下午4:35
收件人:&nbsp;"wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com&gt;;
抄送:&nbsp;"秦泽政"<781136776@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wenzhixin/bootstrap-table] icon of button can`t display (#4931)





 
Works fine for me, which Browser (and version) do you use ?

**Comment by UtechtDustin** [comment]
Its also working with Google Chrome (80.0.3987.132) for me.
It seems a browser addon or something else is the cause of the issue.

**Comment by EdQzz** [comment]
https://live.bootstrap-table.com/example/welcome.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dustin Utecht"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 下午4:53
收件人:&nbsp;"wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com&gt;;
抄送:&nbsp;"秦泽政"<781136776@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wenzhixin/bootstrap-table] icon of button can`t display (#4931)





 
Its also working with Google Chrome (80.0.3987.132) for me.
 It seems a browser addon or something else is the cause of the issue.

**Comment by EdQzz** [comment]
with Google Chrome(80.0.3987.132)&nbsp;&nbsp;, addon removed&nbsp;
in this web page(https://live.bootstrap-table.com/example/welcome.html),icon can`t display


------------------ 原始邮件 ------------------
发件人:&nbsp;"Dustin Utecht"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 下午4:53
收件人:&nbsp;"wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com&gt;;
抄送:&nbsp;"秦泽政"<781136776@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wenzhixin/bootstrap-table] icon of button can`t display (#4931)





 
Its also working with Google Chrome (80.0.3987.132) for me.
 It seems a browser addon or something else is the cause of the issue.

**Comment by UtechtDustin** [comment]
The welcome example will not display the search button because the option (`data-show-search-button="true"`) is not set.

**Comment by EdQzz** [comment]
I know
in my case, icon of all of buttons couldn`t display&nbsp;
The welcome example also not display&nbsp; icon of refresh button and icon of export data and icon of columns and rest of other buttons




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dustin Utecht"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 下午5:41
收件人:&nbsp;"wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com&gt;;
抄送:&nbsp;"秦泽政"<781136776@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wenzhixin/bootstrap-table] icon of button can`t display (#4931)





 
The welcome example will not display the search button because the option (data-show-search-button="true") is not set.

**Comment by UtechtDustin** [comment]
Could you please make a screenshot ?
As i already said it seems its a browser addon which cause the issue.
Try it again after disable all addons.

**Comment by EdQzz** [comment]
all addons has been removed, all icons also can`t display


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dustin Utecht"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 下午5:55
收件人:&nbsp;"wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com&gt;;
抄送:&nbsp;"秦泽政"<781136776@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wenzhixin/bootstrap-table] icon of button can`t display (#4931)





 
Could you please make a screenshot ?
 As i already said it seems its a browser addon which cause the issue.
 Try it again after disable all addons.

**Comment by UtechtDustin** [comment]
Which OS(-version) do you use ?

**Comment by EdQzz** [comment]
windows10&nbsp;专业版


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dustin Utecht"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 晚上6:19
收件人:&nbsp;"wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com&gt;;
抄送:&nbsp;"秦泽政"<781136776@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wenzhixin/bootstrap-table] icon of button can`t display (#4931)





 
Which OS(-version) do you use ?

**Comment by UtechtDustin** [comment]
@djhvscf 
Could you please check if you have the same issue on Windows 10 ?
I currently have no VM for tests.

**Comment by EdQzz** [comment]
this&nbsp;picture is my case, icon display well





this picture is welcome example(https://live.bootstrap-table.com/example/welcome.html),icon can`t display





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dustin Utecht"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 下午4:11
收件人:&nbsp;"wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com&gt;;
抄送:&nbsp;"秦泽政"<781136776@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wenzhixin/bootstrap-table] icon of button can`t display (#4931)





 
@djhvscf
 Could you please check if you have the same issue on Windows 10 ?
 I currently have no VM for tests.

**Comment by wenzhixin** [comment]
I think it's the network problem. Can you open this link: https://kit-free.fontawesome.com/releases/latest/css/free.min.css?

**Comment by djhvscf** [comment]
This is working right for me.

**Comment by CSGrandeur** [comment]
the same situation.

![](https://user-images.githubusercontent.com/5326601/125184201-58cba680-e24e-11eb-8132-e5a08c9282b1.png)

tried with the newest chrome, edge, ie.

However, the icons could show up in the Online Editor.
