### ISSUE TITLE
editable插件保存数据后会初始化设置

### ISSUE THREAD

**Issue by hongyan6012** [wenzhixin/bootstrap-table#4933]
我使用insertRow方法创建新行，并对新行内的a.editable设置{option, send, never}
当我编辑完任意一个单元格后，bootstrap-table-editable.js#1587的initBody()导致了对a.editable的设置自动被初始值覆盖，从而使得下一次编辑时会向server端提交数据，这并不是我希望的！

Bootstrap3.3.7+BootstrapTable1.16.0+jquery2.1.1
Edge(Chrome)

**Comment by wenzhixin** [comment]
麻烦提供下例子。
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by hongyan6012** [comment]
附件以最精简的方式再现了这个现象。
[example.zip](https://github.com/wenzhixin/bootstrap-table/files/4363880/example.zip)
I have no online website so i upload a single file that could reappearance this problem.

**Comment by UtechtDustin** [comment]
@hongyan6012 you dont need a website to provide us an example.
Please follow the link from the online example (see the post from @wenzhixin), there you can rebuild your example and save it. After that post the url of that example here.

**Comment by hongyan6012** [comment]
@UtechtDustin Thank you for your explanation. Here is my [Online Example](https://live.bootstrap-table.com/code/hongyan6012/2226).

**Comment by UtechtDustin** [comment]
You can set `send` to `never` while creating the table.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3410

If you still need help, please explain why you need to set that option after adding the row.
I guess your setup would also break on page change, etc.
