### ISSUE TITLE
table class="table table-sm" and Table Sticky Header,found Sticky Header is not class="table table-sm"

### ISSUE THREAD

**Issue by flashliao** [wenzhixin/bootstrap-table#4934]
I use the table class="table table-sm" and Table Sticky Header,But When I scroll down,I found Sticky Header is not class="table table-sm".

 [Online Example]
https://live.bootstrap-table.com/code/flashliao/2156

**Comment by wenzhixin** [comment]
Please use our [`classes`](https://bootstrap-table.com/docs/api/table-options/#classes) option instead of `class`.
https://live.bootstrap-table.com/code/wenzhixin/2212
