### ISSUE TITLE
bootstrap-table-filter-control with no strict search

### ISSUE THREAD

**Issue by EdQzz** [wenzhixin/bootstrap-table#4935]
in this web page [Filter Control](https://examples.bootstrap-table.com/index.html#extensions/filter-control.html), when I choose Item Price  with $2, I get 2 records ('$2' and '$20') as result. I realize that the function with filter is not strict. Well, how could I get a strict filter?
also,the content of  the drop-down menu of Item Price is ordered  asc.I want it  ordered desc,how could I deal with

**Comment by UtechtDustin** [comment]
Hello EdQzz,

do you searched in the documentation ?
Because its documented there, please use the [filterstrictsearch](https://bootstrap-table.com/docs/extensions/filter-control/#filterstrictsearch) option.

**Comment by EdQzz** [comment]
Thanks
I just browse the example web page. Sorry for your trouble.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dustin Utecht"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 下午4:10
收件人:&nbsp;"wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com&gt;;
抄送:&nbsp;"秦泽政"<781136776@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wenzhixin/bootstrap-table] bootstrap-table-filter-control with no strict search (#4935)





 
Hello EdQzz,
 
do you searched in the documentation ?
 Because its documented there, please use the filterstrictsearch option.

**Comment by UtechtDustin** [comment]
No Problem your welcome.
Is it working now ? (Then please close the issue :-) )

**Comment by EdQzz** [comment]
Sorry to open this issue again
in this example page [filter control](https://live.bootstrap-table.com/example/extensions/filter-control.html), i add ' data-filter-strict-search="true" ',but I don`t get strict search

**Comment by EdQzz** [comment]
set data-filter-strict-search to 'true',but it doesn`t work
this web page in "https://live.bootstrap-table.com/example/extensions/filter-control.html"



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dustin Utecht"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 下午4:17
收件人:&nbsp;"wenzhixin/bootstrap-table"<bootstrap-table@noreply.github.com&gt;;
抄送:&nbsp;"秦泽政"<781136776@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wenzhixin/bootstrap-table] bootstrap-table-filter-control with no strict search (#4935)





 
No Problem your welcome.
 Is it working now ? (Then please close the issue :-) )
