### ISSUE TITLE
Ajax request is executed before onPageChange handler

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#4936]
In case of [custom ajax request](https://examples.bootstrap-table.com/index.html#options/table-ajax.html), the handler [`onPageChange()`](https://bootstrap-table.com/docs/api/events/#onpagechange), which is supposed to be used to adjust the parameters of the ajax request, is executed after the new request. That makes basically `onPageChange()` useless for this use case.

Steps to reproduce:
1. Change the pageSize
2. Observe the two prints in the console: the body of the ajax request function is executed before the one of the `onPageChange()`.

https://live.bootstrap-table.com/code/antonioaltamura/2172

**Comment by wenzhixin** [comment]
I don't think it is necessary to save the page info, you can use the `getOptions` method to get it directly.
https://live.bootstrap-table.com/code/wenzhixin/2205

**Comment by antonioaltamura** [comment]
`elm.bootstrapTable('getOptions')` solves my issue, but I still think it's a weird behavior and it shouldn't act like that.

**Comment by wenzhixin** [comment]
Fixed in #4950
