### ISSUE TITLE
In Vue component - Cell Formatter function doesn't take "field" parameter. Only value, row and index.

### ISSUE THREAD

**Issue by blacksheriff** [wenzhixin/bootstrap-table#4939]
Only in Vue, but in online editor - all works fine
So, it should be three or four?
![image](https://user-images.githubusercontent.com/57944588/76959772-5774bd00-692b-11ea-90da-4495fb24464a.png)

**Comment by wenzhixin** [comment]
It's four parameters.
https://live.bootstrap-table.com/code/wenzhixin/2204
