### ISSUE TITLE
Reset table height fail when calling bootstrapTable(resetView）if there are colspan settings in table header

### ISSUE THREAD

**Issue by powerliredsky** [wenzhixin/bootstrap-table#4941]
Unzip the sample.zip and open the estimateDetail2.html file, I get a js error.
Something wrong when I call the resetView method if I use colspan in table header.

```
Uncaught TypeError: Cannot read property 'field' of undefined
    at HTMLTableCellElement.<anonymous> (bootstrap-table.js:3771)
    at Function.each (jquery-3.4.1.js:367)
    at jQuery.fn.init.each (jquery-3.4.1.js:202)
    at HTMLTableRowElement.<anonymous> (bootstrap-table.js:3751)
    at Function.each (jquery-3.4.1.js:367)
    at jQuery.fn.init.each (jquery-3.4.1.js:202)
    at Object.trToData (bootstrap-table.js:3745)
    at BootstrapTable.initTable (bootstrap-table.js:4146)
    at BootstrapTable.init (bootstrap-table.js:4010)
    at new BootstrapTable (bootstrap-table.js:4001)
```

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by powerliredsky** [comment]
I had uploaded a online sample for this issue(#4941). Can you see it? By the way, I saved the sample in online editor, but I can not find it anywhere....

**Comment by powerliredsky** [comment]
I had reuploaded the sample here. Can you see it?  @wenzhixin
https://live.bootstrap-table.com/code/powerliredsky/2260

**Comment by UtechtDustin** [comment]
@powerliredsky 
Could you please provide a example which only contains the table ? (not the whole website :D )

**Comment by powerliredsky** [comment]
> @powerliredsky
> Could you please provide a example which only contains the table ? (not the whole website :D )

@UtechtDustin 
Hi, UtechtDustin
This bug will be happened when update the height of the table.
And the calculation of the height should use serval component in the page.
So the whole source code of page will be useful for bug happeness. 
Thank your advice, I remove sample special info from sourcecode and save it again here. 
https://live.bootstrap-table.com/code/powerliredsky/2285
Would you please check it again? Thank you so much.

**Comment by powerliredsky** [comment]
@wenzhixin 
I need a solution for this issue in my project as soon as possible.
Would you like to help me?

**Comment by wenzhixin** [comment]
Because the field must be unique, I think cannot support your case.
A working example: https://live.bootstrap-table.com/code/wenzhixin/2370
