### ISSUE TITLE
Size of .no-records-found div is too big when table-layout is fixed and there are two rows of headers in thead

### ISSUE THREAD

**Issue by ethanvu** [wenzhixin/bootstrap-table#4946]
When there is a searchable table, with two `tr`'s in the `thead` and the style `table-layout: fixed`, and you search for something with no matches, the resulting `div.no-records-found`'s `colspan` equals the total number of `th`'s in `thead` (i.e. it's too wide).

If instead `table-layout: auto`, `div.no-records-found` has the correct `colspan`.

This problem occurred with Firefox and Chrome.

Here is an example of the problem, just type "test" into the search box: https://live.bootstrap-table.com/code/ethanvu/2233

I think [this line](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1471) and [this line](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L137) will be relevant to the potential fix.

Here is a related issue I found: #2331

**Comment by wenzhixin** [comment]
Fixed in #4950
