### ISSUE TITLE
data-cell-style not call function

### ISSUE THREAD

**Issue by hebeto** [wenzhixin/bootstrap-table#4952]
Need help. I´m using bootstrap-table v 1.7 and i need fill cell background color, but the data-cell-style don´t call the function.

<th data-field="LimitDate" data-cell-style="StyleDataLimite" data-sortable="true" data-align="left">Limit Date</th>

function StyleDataLimite(value, t, e) {
        debugger;
        return { css: { 'background-color': 'green' }}
}

The debugging not stop in debugger;

The Issue #221 not fix.

Someone can help me?
Thanks.

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/index.html#column-options/cell-style.html

**Comment by hebeto** [comment]
If you can see. The prop data-cell-style not appear in intelisense. Version problem may be? What class i can see this prop?
![image](https://user-images.githubusercontent.com/40807914/77910576-bc061500-7265-11ea-87b8-4c7cf0df37cd.png)
My version: 
/**
 * @author zhixin wen <wenzhixin2010@gmail.com>
 * version: 1.7.0
 * https://github.com/wenzhixin/bootstrap-table/
 */
Thanks.

**Comment by wenzhixin** [comment]
Sorry, I'm not familiar with nuget, maybe @djhvscf can help you.
Or you can use `npm`.

**Comment by djhvscf** [comment]
You can run this command

Update-Package -reinstall

**Comment by hebeto** [comment]
Well, i can´t update because others grids become unconfigured. To resolve my issue, used $('#table').on('post-body.bs.table', function () {

Thanks for all.
