### ISSUE TITLE
Filter Control does not work with formatter / icons

### ISSUE THREAD

**Issue by sebastiangehrt** [wenzhixin/bootstrap-table#4955]
If you are using a custom formatter for a column which uses icons, the filter control does not work correct. 

1. The filter controll can not show the icons oder text
2. If you choose an value their will be no result

Simple Example
https://live.bootstrap-table.com/code/sebastiangehrt/2301

I'm using version 1.16 with chrome browser

**Comment by wenzhixin** [comment]
Not support this feature with the `select` element.
ref #3298

**Comment by sebastiangehrt** [comment]
Hi #3298 is an other topic - this topic is a problem with a normal select using a formatter. Could you please check it again

**Comment by wenzhixin** [comment]
The problem is a normal `select` cannot support `<i>`:
https://live.bootstrap-table.com/code/wenzhixin/2414

**Comment by sebastiangehrt** [comment]
Thx for the hint with <i> tag in <select>

It try it without using the <i> tag: 
https://live.bootstrap-table.com/code/sebastiangehrt/2416

At the moment their are some problems with the format of the table and the select.

Would it possible to support icons in select using class="fa" ?

**Comment by wenzhixin** [comment]
Cannot work in my browser: 
![image](https://user-images.githubusercontent.com/2117018/78637493-08dc9200-78dd-11ea-8c2a-7c433bbfe947.png)

**Comment by sebastiangehrt** [comment]
Please see the select over the table - every `<option>` Tag needs the ` class="fa"`

**Comment by wenzhixin** [comment]
https://live.bootstrap-table.com/code/wenzhixin/2417 ?

**Comment by sebastiangehrt** [comment]
https://live.bootstrap-table.com/code/sebastiangehrt/2418

Select and table-rows have now the correct format, but filter does not work:

- duplicates in the filter
- no results when using filter

**Comment by sebastiangehrt** [comment]
Example without FA5
https://live.bootstrap-table.com/code/sebastiangehrt/2425
