### ISSUE TITLE
$table.bootstrapTable('destroy').确定执行成功了，但是页面数据不变

### ISSUE THREAD

**Issue by lxc345** [wenzhixin/bootstrap-table#4956]
做搜索功能的时候，queryBtn点击之后，通过console.log看到销毁重建都执行了，但是并不起作用。单独写一个销毁的点击事件，发现明明执行了销毁的代码，但是页面里的数据都还在。代码如下
	var operateEvents = {
		'click #tableEditor': function (e, value, row, index) {},
		'click #tableDelete': function (e, value, row, index) {}
	}
	function addFunctionAlty(value,row,index,field){
		return [
			'<button id="tableEditor" class="btn btn-success">编辑</button>',
			'<button id="tableDelete" class="btn btn-danger">删除</button>'
		].join("");
	}
	function initTable(){
		//先销毁表格
		$('#myTable').bootstrapTable('destroy');
		//创建表格
		$('#mytable').bootstrapTable({
			url: "../conn/web/getmembers.php", //请求地址
			method: 'GET', //请求
			striped: true,
			cache: false,
			pagination: true,//是否分页
			sortable: true,
			showToggle: true,//是否显示 切换试图（table/card）按钮
			showColumns: true,//是否显示 内容列下拉框
			showHeader : true,
			showRefresh: true,//刷新按钮
			clickToSelect: true,
			sidePagination: "server", //server:服务器端分页|client：前端分页
			search: false, //是否显示表格搜索,bootstrap-table服务器分页不能使用搜索功能，可以自定义搜索框
			clickToSelect: true,  //是否启用点击选中行
			pageNumber: 1,
			pageList: [10,15,20],//可选择单页记录数
			// queryParamsType : "limit",//设置为 ‘limit’ 则会发送符合 RESTFul 格式的参数.
			queryParams: function (params) {
				return {
					offset: params.offset,  //页码 0开始
					limit: params.limit,   //页面大小
					username: $("#search_username").val(),
				};
			},
			responseHandler: function (res) {
　　	　　　　	//如果后台返回的json格式不是{rows:[{...},{...}],total:100},可以在这块处理成这样的格式
　　　　　　	return res;
			},
			onLoadError: function () {
				alert("数据加载失败！");
			},
			columns: [{
				field: 'username',
				title: '用户名',
			}, {
				field: 'mobile',
				title: '手机号',
			},  {
				field: 'credit3',
				title: '余额'
			},  {
				field: 'yj',
				title: '费率（万分比）',
			}, {
				field: 'superior',
				title: '上级',
			}, {
				field: 'realname',
				title: '姓名',
			}, {
				field: 'button',
				title: '操作',
				events:operateEvents,
				formatter:addFunctionAlty
			}]
		});
	}
    $(document).ready(function () {
		initTable();
		$("#queryBtn").click(function(){
			initTable();
			
		});
		
    })

**Comment by wenzhixin** [comment]
麻烦提供下在线例子。
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issue because we got no response from you within 7days.
If you still need help please provide us an example and we will reopen the issue.

**Comment by HOHMLn** [comment]
> 做搜索功能的时候，queryBtn点击之后，通过console.log看到销毁重建都执行了，但是并不起作用。单独写一个销毁的点击事件，发现明明执行了销毁的代码，但是页面里的数据都还在。代码如下
> var operationEvents = {
> 'click #tableEditor'：函数（例如，值，行，索引）{}，
> 'click #tableDelete'：函数（例如，值，行，索引）{}
> }
> function addFunctionAlty（ value，row，index，field）{
> return [
> '编辑'，
> '删除'
> ] .join（“”）;
> }
> 函数initTable（）{
> //先销毁表格
> $（'＃myTable'）。bootstrapTable（'destroy'）;
> //创建表格
> $（'＃mytable'）。bootstrapTable（{
> url：“ ../conn/web/getmembers.php”，//请求地址
> 方法：'GET'，//请求
> 条带化：true，
> 缓存：false ，
> 分页：正确，
> 
> showToggle：true，///是否显示切换尝试（表/卡）按钮
> showColumns：true，//是否显示内容列拖放框
> showHeader：true，
> showRefresh：true，///刷新按钮
> clickToSelect：true，
> sidePagination：“服务器”， //服务器：服务器端分页|客户端：前端分页
> 搜索：false，//是否显示表格搜索，bootstrap-table服务器分页不能使用搜索功能，可以自定义搜索框
> clickToSelect：true，//是否启用点击替换行
> pageNumber ：1，
> pageList：[10,15,20]，//可选单页记录数
> // queryParamsType：“ limit”，//设置为'limit'可以发送符合RESTFul格式的参数。
> queryParams：function（params）{
> return {
> offset：params.offset，//
> 页面码0开始限制：params.limit，//页面大小
> 用户名：$（“＃search_username”）。val（），
> };
> }，
> responseHandler：函数（res）{
> 　　 　　　　 //如果后台返回的json格式不是{行：[{......，{...}]，总计：100}，可以在这块处理成这样的格式
> 　　　　　　 return res;
> }，
> onLoadError：function（）{
> alert（“数据加载失败！”）;
> }，
> 列：[{
> 字段：'username'，
> 标题：'用户名'，
> }，{
> 字段：'mobile'，
> 标题：'手机号'，
> }，{
> 字段：'credit3'，
> 标题：'余额'
> } ，{
> 字段：'yj'，
> 标题：'费率（万分比）'，
> }，{
> 字段：'superior'，
> 标题：'上级'，
> }，{
> 字段：'realname'，
> 标题：'姓名'，
> } ，{
> 字段：“按钮”，
> 标题：“操作”，
> 事件：
> 
> 
> }）;
> }
> $（document）.ready（function（）{
> initTable（）;
> $（“＃queryBtn”）。click（function（）{
> initTable（）;
> 
> ```
> 	});
> 	
> })
> ```

检查一下你的html元素是否写了<table/>,正确写法应该是<table></table>

**Comment by HOHMLn** [comment]
> 做搜索功能的时候，queryBtn点击之后，通过console.log看到销毁重建都执行了，但是并不起作用。单独写一个销毁的点击事件，发现明明执行了销毁的代码，但是页面里的数据都还在。代码如下
> var operationEvents = {
> 'click #tableEditor'：函数（例如，值，行，索引）{}，
> 'click #tableDelete'：函数（例如，值，行，索引）{}
> }
> function addFunctionAlty（ value，row，index，field）{
> return [
> '编辑'，
> '删除'
> ] .join（“”）;
> }
> 函数initTable（）{
> //先销毁表格
> $（'＃myTable'）。bootstrapTable（'destroy'）;
> //创建表格
> $（'＃mytable'）。bootstrapTable（{
> url：“ ../conn/web/getmembers.php”，//请求地址
> 方法：'GET'，//请求
> 条带化：true，
> 缓存：false ，
> 分页：正确，
> 
> showToggle：true，///是否显示切换尝试（表/卡）按钮
> showColumns：true，//是否显示内容列拖放框
> showHeader：true，
> showRefresh：true，///刷新按钮
> clickToSelect：true，
> sidePagination：“服务器”， //服务器：服务器端分页|客户端：前端分页
> 搜索：false，//是否显示表格搜索，bootstrap-table服务器分页不能使用搜索功能，可以自定义搜索框
> clickToSelect：true，//是否启用点击替换行
> pageNumber ：1，
> pageList：[10,15,20]，//可选单页记录数
> // queryParamsType：“ limit”，//设置为'limit'可以发送符合RESTFul格式的参数。
> queryParams：function（params）{
> return {
> offset：params.offset，//
> 页面码0开始限制：params.limit，//页面大小
> 用户名：$（“＃search_username”）。val（），
> };
> }，
> responseHandler：函数（res）{
> 　　 　　　　 //如果后台返回的json格式不是{行：[{......，{...}]，总计：100}，可以在这块处理成这样的格式
> 　　　　　　 return res;
> }，
> onLoadError：function（）{
> alert（“数据加载失败！”）;
> }，
> 列：[{
> 字段：'username'，
> 标题：'用户名'，
> }，{
> 字段：'mobile'，
> 标题：'手机号'，
> }，{
> 字段：'credit3'，
> 标题：'余额'
> } ，{
> 字段：'yj'，
> 标题：'费率（万分比）'，
> }，{
> 字段：'superior'，
> 标题：'上级'，
> }，{
> 字段：'realname'，
> 标题：'姓名'，
> } ，{
> 字段：“按钮”，
> 标题：“操作”，
> 事件：
> 
> 
> }）;
> }
> $（document）.ready（function（）{
> initTable（）;
> $（“＃queryBtn”）。click（function（）{
> initTable（）;
> 
> ```
> 	});
> 	
> })
> ```

> 检查一下html元素是否携程了`<table/>`,正确写法应该是`<table></table>` ,这个写错将会出现你描述的问题

**Comment by HOHMLn** [comment]
> 做搜索功能的时候，queryBtn点击之后，通过console.log看到销毁重建都执行了，但是并不起作用。单独写一个销毁的点击事件，发现明明执行了销毁的代码，但是页面里的数据都还在。代码如下
> var operationEvents = {
> 'click #tableEditor'：函数（例如，值，行，索引）{}，
> 'click #tableDelete'：函数（例如，值，行，索引）{}
> }
> function addFunctionAlty（ value，row，index，field）{
> return [
> '编辑'，
> '删除'
> ] .join（“”）;
> }
> 函数initTable（）{
> //先销毁表格
> $（'＃myTable'）。bootstrapTable（'destroy'）;
> //创建表格
> $（'＃mytable'）。bootstrapTable（{
> url：“ ../conn/web/getmembers.php”，//请求地址
> 方法：'GET'，//请求
> 条带化：true，
> 缓存：false ，
> 分页：正确，
> 
> showToggle：true，///是否显示切换尝试（表/卡）按钮
> showColumns：true，//是否显示内容列拖放框
> showHeader：true，
> showRefresh：true，///刷新按钮
> clickToSelect：true，
> sidePagination：“服务器”， //服务器：服务器端分页|客户端：前端分页
> 搜索：false，//是否显示表格搜索，bootstrap-table服务器分页不能使用搜索功能，可以自定义搜索框
> clickToSelect：true，//是否启用点击替换行
> pageNumber ：1，
> pageList：[10,15,20]，//可选单页记录数
> // queryParamsType：“ limit”，//设置为'limit'可以发送符合RESTFul格式的参数。
> queryParams：function（params）{
> return {
> offset：params.offset，//
> 页面码0开始限制：params.limit，//页面大小
> 用户名：$（“＃search_username”）。val（），
> };
> }，
> responseHandler：函数（res）{
> 　　 　　　　 //如果后台返回的json格式不是{行：[{......，{...}]，总计：100}，可以在这块处理成这样的格式
> 　　　　　　 return res;
> }，
> onLoadError：function（）{
> alert（“数据加载失败！”）;
> }，
> 列：[{
> 字段：'username'，
> 标题：'用户名'，
> }，{
> 字段：'mobile'，
> 标题：'手机号'，
> }，{
> 字段：'credit3'，
> 标题：'余额'
> } ，{
> 字段：'yj'，
> 标题：'费率（万分比）'，
> }，{
> 字段：'superior'，
> 标题：'上级'，
> }，{
> 字段：'realname'，
> 标题：'姓名'，
> } ，{
> 字段：“按钮”，
> 标题：“操作”，
> 事件：
> 
> 
> }）;
> }
> $（document）.ready（function（）{
> initTable（）;
> $（“＃queryBtn”）。click（function（）{
> initTable（）;
> 
> ```
> 	});
> 	
> })
> ```

检查一下html元素是否写了<table/>，正确写法应该是<table></table>，这个写错将会出现你描述的问题

> 做搜索功能的时候，queryBtn点击之后，通过console.log看到销毁重建都执行了，但是并不起作用。单独写一个销毁的点击事件，发现明明执行了销毁的代码，但是页面里的数据都还在。代码如下
> var operationEvents = {
> 'click #tableEditor'：函数（例如，值，行，索引）{}，
> 'click #tableDelete'：函数（例如，值，行，索引）{}
> }
> function addFunctionAlty（ value，row，index，field）{
> return [
> '编辑'，
> '删除'
> ] .join（“”）;
> }
> 函数initTable（）{
> //先销毁表格
> $（'＃myTable'）。bootstrapTable（'destroy'）;
> //创建表格
> $（'＃mytable'）。bootstrapTable（{
> url：“ ../conn/web/getmembers.php”，//请求地址
> 方法：'GET'，//请求
> 条带化：true，
> 缓存：false ，
> 分页：正确，
> 
> showToggle：true，///是否显示切换尝试（表/卡）按钮
> showColumns：true，//是否显示内容列拖放框
> showHeader：true，
> showRefresh：true，///刷新按钮
> clickToSelect：true，
> sidePagination：“服务器”， //服务器：服务器端分页|客户端：前端分页
> 搜索：false，//是否显示表格搜索，bootstrap-table服务器分页不能使用搜索功能，可以自定义搜索框
> clickToSelect：true，//是否启用点击替换行
> pageNumber ：1，
> pageList：[10,15,20]，//可选单页记录数
> // queryParamsType：“ limit”，//设置为'limit'可以发送符合RESTFul格式的参数。
> queryParams：function（params）{
> return {
> offset：params.offset，//
> 页面码0开始限制：params.limit，//页面大小
> 用户名：$（“＃search_username”）。val（），
> };
> }，
> responseHandler：函数（res）{
> 　　 　　　　 //如果后台返回的json格式不是{行：[{......，{...}]，总计：100}，可以在这块处理成这样的格式
> 　　　　　　 return res;
> }，
> onLoadError：function（）{
> alert（“数据加载失败！”）;
> }，
> 列：[{
> 字段：'username'，
> 标题：'用户名'，
> }，{
> 字段：'mobile'，
> 标题：'手机号'，
> }，{
> 字段：'credit3'，
> 标题：'余额'
> } ，{
> 字段：'yj'，
> 标题：'费率（万分比）'，
> }，{
> 字段：'superior'，
> 标题：'上级'，
> }，{
> 字段：'realname'，
> 标题：'姓名'，
> } ，{
> 字段：“按钮”，
> 标题：“操作”，
> 事件：
> 
> 
> }）;
> }
> $（document）.ready（function（）{
> initTable（）;
> $（“＃queryBtn”）。click（function（）{
> initTable（）;
> 
> ```
> 	});
> 	
> })
> ```

`检查一下html元素是否写了

> 做搜索功能的时候，queryBtn点击之后，通过console.log看到销毁重建都执行了，但是并不起作用。单独写一个销毁的点击事件，发现明明执行了销毁的代码，但是页面里的数据都还在。代码如下
> var operateEvents = {
> 'click #tableEditor': function (e, value, row, index) {},
> 'click #tableDelete': function (e, value, row, index) {}
> }
> function addFunctionAlty(value,row,index,field){
> return [
> '编辑',
> '删除'
> ].join("");
> }
> function initTable(){
> //先销毁表格
> $('#myTable').bootstrapTable('destroy');
> //创建表格
> $('#mytable').bootstrapTable({
> url: "../conn/web/getmembers.php", //请求地址
> method: 'GET', //请求
> striped: true,
> cache: false,
> pagination: true,//是否分页
> sortable: true,
> showToggle: true,//是否显示 切换试图（table/card）按钮
> showColumns: true,//是否显示 内容列下拉框
> showHeader : true,
> showRefresh: true,//刷新按钮
> clickToSelect: true,
> sidePagination: "server", //server:服务器端分页|client：前端分页
> search: false, //是否显示表格搜索,bootstrap-table服务器分页不能使用搜索功能，可以自定义搜索框
> clickToSelect: true, //是否启用点击选中行
> pageNumber: 1,
> pageList: [10,15,20],//可选择单页记录数
> // queryParamsType : "limit",//设置为 ‘limit’ 则会发送符合 RESTFul 格式的参数.
> queryParams: function (params) {
> return {
> offset: params.offset, //页码 0开始
> limit: params.limit, //页面大小
> username: $("#search_username").val(),
> };
> },
> responseHandler: function (res) {
> 　　 　　　　 //如果后台返回的json格式不是{rows:[{...},{...}],total:100},可以在这块处理成这样的格式
> 　　　　　　 return res;
> },
> onLoadError: function () {
> alert("数据加载失败！");
> },
> columns: [{
> field: 'username',
> title: '用户名',
> }, {
> field: 'mobile',
> title: '手机号',
> }, {
> field: 'credit3',
> title: '余额'
> }, {
> field: 'yj',
> title: '费率（万分比）',
> }, {
> field: 'superior',
> title: '上级',
> }, {
> field: 'realname',
> title: '姓名',
> }, {
> field: 'button',
> title: '操作',
> events:operateEvents,
> formatter:addFunctionAlty
> }]
> });
> }
> $(document).ready(function () {
> initTable();
> $("#queryBtn").click(function(){
> initTable();
> 
> ```
> 	});
> 	
> })
> ```

检查一下你的html元素是否写成了`<table/>`，正确写法应该是`<table></table>`,这个写错将会出现你描述的问题

**Comment by HOHMLn** [comment]
> 做搜索功能的时候，queryBtn点击之后，通过console.log看到销毁重建都执行了，但是并不起作用。单独写一个销毁的点击事件，发现明明执行了销毁的代码，但是页面里的数据都还在。代码如下
> var operateEvents = {
> 'click #tableEditor': function (e, value, row, index) {},
> 'click #tableDelete': function (e, value, row, index) {}
> }
> function addFunctionAlty(value,row,index,field){
> return [
> '编辑',
> '删除'
> ].join("");
> }
> function initTable(){
> //先销毁表格
> $('#myTable').bootstrapTable('destroy');
> //创建表格
> $('#mytable').bootstrapTable({
> url: "../conn/web/getmembers.php", //请求地址
> method: 'GET', //请求
> striped: true,
> cache: false,
> pagination: true,//是否分页
> sortable: true,
> showToggle: true,//是否显示 切换试图（table/card）按钮
> showColumns: true,//是否显示 内容列下拉框
> showHeader : true,
> showRefresh: true,//刷新按钮
> clickToSelect: true,
> sidePagination: "server", //server:服务器端分页|client：前端分页
> search: false, //是否显示表格搜索,bootstrap-table服务器分页不能使用搜索功能，可以自定义搜索框
> clickToSelect: true, //是否启用点击选中行
> pageNumber: 1,
> pageList: [10,15,20],//可选择单页记录数
> // queryParamsType : "limit",//设置为 ‘limit’ 则会发送符合 RESTFul 格式的参数.
> queryParams: function (params) {
> return {
> offset: params.offset, //页码 0开始
> limit: params.limit, //页面大小
> username: $("#search_username").val(),
> };
> },
> responseHandler: function (res) {
> 　　 　　　　 //如果后台返回的json格式不是{rows:[{...},{...}],total:100},可以在这块处理成这样的格式
> 　　　　　　 return res;
> },
> onLoadError: function () {
> alert("数据加载失败！");
> },
> columns: [{
> field: 'username',
> title: '用户名',
> }, {
> field: 'mobile',
> title: '手机号',
> }, {
> field: 'credit3',
> title: '余额'
> }, {
> field: 'yj',
> title: '费率（万分比）',
> }, {
> field: 'superior',
> title: '上级',
> }, {
> field: 'realname',
> title: '姓名',
> }, {
> field: 'button',
> title: '操作',
> events:operateEvents,
> formatter:addFunctionAlty
> }]
> });
> }
> $(document).ready(function () {
> initTable();
> $("#queryBtn").click(function(){
> initTable();
> 
> ```
> 	});
> 	
> })
> ```

检查一下html元素是否写成了`<table/>`，正确写法应该是`<table></table>`，这个写错将出现你描述的问题
