### ISSUE TITLE
Print extension do not works on chrome

### ISSUE THREAD

**Issue by rmarzocchi84** [wenzhixin/bootstrap-table#4958]
Print extension (also on public website) https://examples.bootstrap-table.com/#extensions/print.html do not works on chrome 

Chrome version 80.0.3987.149 

Works fine on firefox (v. 74.0)
Works fine on Edge (v. ??)

**Comment by rmarzocchi84** [comment]
I solved without using the extension (perhaps can be useful for other users or to solve the issue) using a jquery function:

```
function printClass(className) {
	//it is an array so i using only the first element
     var printContents = document.getElementsByClassName(className)[0].innerHTML;
     var originalContents = document.body.innerHTML;

     document.body.innerHTML = printContents;

     window.print();

     document.body.innerHTML = originalContents;
}
</script>
```

which I call from HTML

```
<button class="btn btn-info noprint" onclick="printClass('fixed-table-container')"> <i class="fa fa-print" aria-hidden="true"></i> Stampa tabella </button>
```

!!WARNING!!:  This solution works only for a page with one table `getElementsByClassName(className)[0]`

**Comment by wenzhixin** [comment]
It's working for me.
Mac chrome version 80.0.3987.162 (Official Build) (64-bit)

**Comment by UtechtDustin** [comment]
Works also fine on Linux  - Version 80.0.3987.162 (Offizieller Build) snap (64-Bit)

**Comment by rmarzocchi84** [comment]
I have tested it on windows. unfortunately my linux PC is in office and I am working at home for covid19

**Comment by UtechtDustin** [comment]
@djhvscf could you test it please ?

**Comment by djhvscf** [comment]
It is working as expected for me. Using windows 10, Chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by djhvscf** [comment]
> It is working as expected for me. Using windows 10, Chrome Version 80.0.3987.149 (Official Build) (64-bit)

Also it is working with latest version of Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by UtechtDustin** [comment]
@rmarzocchi84 
So it seems its an issue of your setup, maybe a browser plugin or something like that.
