### ISSUE TITLE
CPU Spiking

### ISSUE THREAD

**Issue by rfossella** [wenzhixin/bootstrap-table#496]
I recently started using bootstrap-table (version: 1.5.0) in a web app.  

I have 20 tables on a page that have all been "bootstraptabled()"  
The tables are hidden behind bootstrap TABS.  Collections of TABS are behind ACCORDIONS.  (see attachement)

The options I use for all tables is
height: 450,
striped: true,
pagination: true,
pageSize: 50,
pageList: [10, 50, 100, 200, 500],
search: true,
showColumns: true,
showLoading:true,
showToggle:true

One column (on all tables) has a formatter option to convert booleans to checkmark image.  

Each table holds roughly 100-400 rows.

After defining them as bootstraptables I noticed that Chrome (and FF) started consistently spiking CPU to about 9% and holding.  
Memory also consistently rose.  I checked a number of other features on my page and none stopped the spike.  I then removed the option to bootsraptable -i.e. they are back to regular HTML tables.  CPU went to 0 and no obvious extra memory consumption

Again, I systematically removed different features from the web app/page but only the bootstrap-table is spiking CPU.

Has anyone else seen this behavior?  Can anyone point to something I might be missing?

Any issues with using bootstrap-table with other widgets?  Issues using with tabs or accordions?

I'm using jquery-1.10.2, Bootstrap v3.0.2

Any help or direction would be greatly appreciated.

Thanks.
Rob

![image](https://cloud.githubusercontent.com/assets/1350182/5990871/0a352ee4-a996-11e4-83e8-5c33878b3c24.png)

![image](https://cloud.githubusercontent.com/assets/1350182/5990883/9db98214-a996-11e4-9011-fbfa53d4beae.png)

**Comment by wenzhixin** [comment]
Hi @rfossella , you can solve your problem by active bootstrap-table when active the tabs or accordions:
```js
$('.tabs, .accordions').click(function () {
    if ($('.your-table-class:visible').data('bootstrap.table')) {
        $('.your-table-class:visible').bootstrapTable({...});
    }
});
```

**Comment by rfossella** [comment]
Hi,
This worked.  I also added another step to remove the click event on tabs once the tab has been clicked / initialized. 
Thank you for your time!
Robert
