### ISSUE TITLE
bootstrap-table-reorder-rows throws exception in 1.16.0

### ISSUE THREAD

**Issue by tangram67** [wenzhixin/bootstrap-table#4960]
Hi.
I updated from 1.15.5 to 1.16.0 and I got a problem with the reorder row plugin "bootstrap-table-reorder-rows.js". I do set a context menu when the page is loaded with the following code:

>function setTablePopupMenu() {
	$('#data-table').bootstrapTable({
		onDragClass: 'table_drag_and_drop',
		contextMenu: '#songs-context-menu',
		contextMenuTrigger: 'both',
		onContextMenuItem: onContextMenuAction,
		reorderableRows: false,
		useRowAttrFunc: false,
		dragHandle: 'dnd-disabled'
	});
}; 

So usually the context menu is shown on a toble row click.
To reorder rows I use the following code to enable the "reorder mode" and disable the context menu:

>function enableTableEditMode() {
	$('#data-table').bootstrapTable('refreshOptions', {
		contextMenu: null,
		contextMenuTrigger: 'none',
		onContextMenuItem: null,
		reorderableRows: true,
		useRowAttrFunc: true,
		dragHandle: null
	});
};

Then reordering  rows is possible an after reordering some rows I disable the "reorder mode" and also re-enable the context menu again by refreshing the options again:

>function disableTableEditMode() {
	$('#data-table').bootstrapTable('refreshOptions', {
		contextMenu: '#songs-context-menu',
		contextMenuTrigger: 'both',
		onContextMenuItem: onContextMenuAction,
		reorderableRows: false,
		useRowAttrFunc: false,
		dragHandle: 'dnd-disabled'
	});
};

During the refresh options call the following error is thrown:

>TypeError: item is undefined bootstrap-table.js:5223:12
    initRow http://localhost:8099/comp/bootstrap-table/1.16.0/dist/bootstrap-table.js:5223
    initBody http://localhost:8099/comp/bootstrap-table/1.16.0/dist/bootstrap-table.js:5407
    initBody http://localhost:8099/comp/bootstrap-table-contextmenu/dist/js/bootstrap-table-contextmenu.min.js:3
    init http://localhost:8099/comp/bootstrap-table/1.16.0/dist/bootstrap-table.js:4016
    value http://localhost:8099/comp/bootstrap-table/1.16.0/dist/extensions/reorder-rows/bootstrap-table-reorder-rows.min.js:10
    refreshOptions http://localhost:8099/comp/bootstrap-table/1.16.0/dist/bootstrap-table.js:6093
    bootstrapTable http://localhost:8099/comp/bootstrap-table/1.16.0/dist/bootstrap-table.js:7181
    jQuery 2
    bootstrapTable http://localhost:8099/comp/bootstrap-table/1.16.0/dist/bootstrap-table.js:7166
    disableTableEditMode http://localhost:8099/app/dist/js/playlist.min.js:42
    setEditMode http://localhost:8099/app/dist/js/playlist.min.js:39
    onToggleEditClick http://localhost:8099/app/dist/js/playlist.min.js:37
    onclick http://localhost:8099/app/playlist/playlist.html?prepare=yes&title=playlist&name=Test Playlist:1

This is used in a more or less complex environment. So I do not have a simple example. But I can gain access to someone to the website if needed.

Thanks in advance,
Dirk.

**Comment by wenzhixin** [comment]
The example is working well: https://examples.bootstrap-table.com/#extensions/reorder-rows.html.
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by tangram67** [comment]
Hi wenzhixin.

I setup a testpage in my environment. I hope that helps to see track down the problem:

In the online example reordering is enabled by default and therefore never disables. In this static environment the rorder row plugin works well.
I my application you can enable the reordering by clicking on the three dots button.
Once you did that you have no longer a context menu for the table, so you can drag and drop some rows. To get back to the normal behavior with the context menu enable, you have to click the three dots button again. During the refresh options call on disable the reorder mode the exception is thrown.

The URL to test this is:
http:/dbrinkmeier.ddns.net/app/playlist/playlist-1-16-0.html?prepare=yes&title=playlist&name=01%20Dummylist

I setup a temporary user to access the page:
Username bt
Password ((Bt12345))

Please let me know if that doesn't help and will try to setup a less complex example.

Regards,
Dirk

**Comment by wenzhixin** [comment]
You can try to use `dragHandle: '>tbody>tr>td'` instead of `dragHandle: null`.

**Comment by tangram67** [comment]
Many thanks and yes, you're right. It is working now :-)
But I do not really understand why:
What is the meaning of using `'>tbody>tr>td'` as the drag handle?

**Comment by wenzhixin** [comment]
This option is mainly used to adapt to the `TableDnD` plugin.
Fixed in #4962
