### ISSUE TITLE
Table Header width and Table Body width mismatch and unaligned

### ISSUE THREAD

**Issue by salman3030** [wenzhixin/bootstrap-table#4961]
Table Header width and Table Body width mismatch and unaligned when set the height of table,please share any idea related to this issue

![image](https://user-images.githubusercontent.com/5642413/78400877-92077680-7608-11ea-922e-1b5423b08764.png)

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by salman3030** [comment]
thanks you just i updated jquery to v3.3.1 version and fixed the issue

**Comment by UtechtDustin** [comment]
Thank you for the feedback.
