### ISSUE TITLE
How to change detail-view icon to button and align last in table.

### ISSUE THREAD

**Issue by akashnri** [wenzhixin/bootstrap-table#4967]
Please provide guidance regarding. above issue asap.

**Comment by UtechtDustin** [comment]
Should work like this: https://live.bootstrap-table.com/code/UtechtDustin/2435
But it seems that `data-detail-view-icon="false"` will break the `events` option.

Example without `data-detail-view-icon`: https://live.bootstrap-table.com/code/UtechtDustin/2436

**Comment by wenzhixin** [comment]
@UtechtDustin is right.
But we need to use the develop branch: https://live.bootstrap-table.com/code/wenzhixin/2446.

ref #4926 #4940

**Comment by djhvscf** [comment]
> @UtechtDustin is right.
> But we need to use the develop branch: https://live.bootstrap-table.com/code/wenzhixin/2446.
> 
> ref #4926 #4940
> 
> Should we add detailViewIconAlign as an option?

I think yes, since we have this behaviors with others options like pagination, search bar, etc.
