### ISSUE TITLE
tfoot Print Problem > We urgently tfoot want print support

### ISSUE THREAD

**Issue by Erdal-Arslan** [wenzhixin/bootstrap-table#4968]
Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by djhvscf** [comment]
please provide an example and a more descritive information about the bug / feature request

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days from you, please provide us an example if you still need help.
