### ISSUE TITLE
Addrbar extension ignores options.

### ISSUE THREAD

**Issue by mac89** [wenzhixin/bootstrap-table#4969]
The addrbar extension ignores the options since this change was made: 
https://github.com/wenzhixin/bootstrap-table/blame/develop/src/extensions/addrbar/bootstrap-table-addrbar.js#L83-L87

Where before you would check the provided options first:
https://github.com/wenzhixin/bootstrap-table/blame/04a94d08d543f5e9533c6a335582377d1cbc1ecb/src/extensions/addrbar/bootstrap-table-addrbar.js#L75

The comment above it states:

> Priority order: The value specified by the user has the highest priority. If it is not specified, it will be obtained from the address bar. If it is not obtained, the default value will be used.

So I feel this is a bug rather than intended. Returning this piece of code for example should resolve the issue:
`this.options.pageSize ||`

**Comment by UtechtDustin** [comment]
@wenzhixin do you remember why do you changed the priority ?

**Comment by wenzhixin** [comment]
It's a bug. Because of the default value of `this.options.pageNumber` is `1`, when we go to page 2 and then refresh the page will go back to the first page.

```
this.options.pageNumber = this.options.pageNumber || (
  _GET(`${_prefix}page`) ? parseInt(_GET(`${_prefix}page`)) : $.BootstrapTable.DEFAULTS.pageNumber
)
```

**Comment by wenzhixin** [comment]
Created a PR to improve the problem.
