### ISSUE TITLE
When doing a table load '?order=asc' is getting tagged to the end of the url

### ISSUE THREAD

**Issue by Bengreen** [wenzhixin/bootstrap-table#497]
When doing a table load '?order=asc' is getting tagged to the end of the url

How do i stop this behaviour.

I am calling inside JS with the following.

$('#company').bootstrapTable({
        idField: 'id',
        url: '/json/company',

But the url /json/company?order=asc is getting requested.

IS this supposed to happen as default behaviour or is there a way i can stop this and just request the url passed in.

**Comment by wenzhixin** [comment]
You can use `queryParams` option to do what you want:
```js
function queryParams(params) {
    return {};
}
```
