### ISSUE TITLE
Table Filter Control Server Side Sorting

### ISSUE THREAD

**Issue by mattosaurus** [wenzhixin/bootstrap-table#4970]
This is a feature request rather than a bug request.

I'm using the Table Filter Control extension with a server side data source and I'm populating the select filter values from an API which all works as expected.

One of the filters is for day names (Monday, Tuesday, etc.), these are sorted on the server side and are returned in the correct order to the url function. This then sorts the options using sortSelectControl which [defaults to sorting in ascending order](https://github.com/wenzhixin/bootstrap-table/blob/2e5ee01111c7357c5696778301ec309c5e93c6f1/src/extensions/filter-control/bootstrap-table-filter-control.js#L63) if filterOrderBy is not 'desc'.

I realise it might not be a good idea to stop sorting by asc as a default as this would change behaviour for others so would it be possible to add a server side sort option which then doesn't sort the data?

Something like this perhaps for the [sortSelectControl](https://github.com/wenzhixin/bootstrap-table/blob/2e5ee01111c7357c5696778301ec309c5e93c6f1/src/extensions/filter-control/bootstrap-table-filter-control.js#L58-L68) function?

```
sortSelectControl: function sortSelectControl(selectControl, orderBy) {
	var $selectControl = $(selectControl.get(selectControl.length - 1));
	var $opts = $selectControl.find('option:gt(0)');
	if (orderBy !== 'server') {
		$opts.sort(function (a, b) {
			return Utils.sort(a.textContent, b.textContent, orderBy === 'desc' ? -1 : 1);
		});
	}

	$selectControl.find('option:gt(0)').remove();
	$selectControl.append($opts);
},
```

I can submit this as a PR if you'd like but you may have a more elegant way of doing this.

Thanks

**Comment by djhvscf** [comment]
I like the idea. Please open the PR

**Comment by mattosaurus** [comment]
I've submitted a PR with the above changes, let me know if there's anything else I can do to help this along.

Thanks

**Comment by djhvscf** [comment]
Thanks @mattosaurus
