### ISSUE TITLE
Edit table column value after exporting

### ISSUE THREAD

**Issue by cabikhalil** [wenzhixin/bootstrap-table#4971]
I want to be able to edit the table column value after exporting.

My bootstrap-table has a column that contains my fisrtname and my lastname like this: 
firstname <br> lastname.

When exporting the table I have: firstname \<br> lastname

I want to export the table and have only: firstname in my excel/csv file or putting lastname in another column but, at least I want to remove it.

Is it possible ? Thank you :)

**Comment by UtechtDustin** [comment]
You could set the [exportdatatype](https://bootstrap-table.com/docs/extensions/export/#exportdatatype) option to `selected`.
Im not sure if this works in you usecase, but i guess this is your only way.
