### ISSUE TITLE
example  error：https://examples.bootstrap-table.com/#extensions/reorder-columns.html

### ISSUE THREAD

**Issue by tanghf0403** [wenzhixin/bootstrap-table#4973]
如题

**Comment by tanghf0403** [comment]
官网的例子报错：https://examples.bootstrap-table.com/#extensions/reorder-columns.html

**Comment by UtechtDustin** [comment]
Thank you for the issue reporting, this issue is already resolved in our develop branch.
Working Example: https://live.bootstrap-table.com/code/UtechtDustin/2454
