### ISSUE TITLE
DateTime Strings don't sort in the correct order in "dd/mm/YYYY" format

### ISSUE THREAD

**Issue by Agomezar** [wenzhixin/bootstrap-table#4978]
I have one date column in european "dd/mm/YYYY" format and I don't get to order correctly. Any idea?

**Comment by UtechtDustin** [comment]
You have to use the sort-name option and must use on that field the YYYY-mm-dd or YYYY/mm/dd format.

The issue is that we compare number/char for number/char, which means the table thinks this is a text not a date.

Example:https://live.bootstrap-table.com/code/UtechtDustin/2478

**Comment by jynxy** [comment]
Hi,

I have tried this and not working, i am using custom view so using div rather than tables.

%START_DATE% is the format i wish and %START_DATE2% is the format you mention above.


`<table id="table"
						data-toggle="table"
						data-search="true"
						data-pagination="true"
						data-page-size="10"
						data-show-custom-view="true"
						data-custom-view="customViewFormatter"
						data-show-search-button="true"
						data-search-selector="#customSearch"
						data-buttons-class="primary"
						data-strict-search="false"
						data-pagination-v-align="both"
						data-url="
						<?= $data_json;	?>">
						<thead>
							<tr>
								<th data-field="colleague_name">Colleague Name</th>
								<th data-field=""></th>
								<th data-field=""></th>
								<th data-field="first_day" data-sort-name="dateSorting">First Day Absence</th>
								<th data-field="dateSorting" data-visible="false">First Day Absence</th>
								<th data-field="phone_number">Phone Number</th>
								<th data-field="csp_stopped">CSP Stopped</th>
								<th data-field="sn_expiry">Sick Note Expiry</th>
								<th data-field="last_action">Last Action</th>
								<th data-field="dna_required">DNA Required</th>
								<th data-field="a_rtw">Anticipated RTW</th>
								<th data-field="next_action">Next Action</th>
								<th data-field="action_type">Action Type</th>
								<th data-field="c_rtw">Confirmed RTW</th>
								<th data-field="ticket">Ticket Number</th>
								<th data-field="walmart">Walmart Number</th>
								<th data-field="shift">Shift</th>
								<th data-field="och_referal">OCH Referal</th>
								<th data-field="och_app">OCH Appointment</th>
								<th data-field="team_manager">My Team Manager</th>
								<th data-field="last_update">Last Updated</th>
								<th data-field="last_update_by">Last Updated By</th>
								<th data-field="reason">Reason</th>
							</tr>
						</thead>
					</table>
					<template id="profileTemplate">
						<div class="card-body data-group card-bg">
							<div class="row">
								<div class="col mb-3">
									<b>Colleague Name: </b>%NAME%<br>
								</div>
								<div class="col mb-3">
									<b>Phone Number: </b>%PHONE%<br>
								</div>
								<div class="col mb-3">
								</div>
							</div>
							<div class="row mb-3">
								<div class="col">
									<b>First Day of Absence: </b>%START_DATE%<br>%START_DATE2%
									<b>CSP Stopped: </b>%CSP_STOPPED%<br>
									<b>Sick Note Expiry: </b>%SN_EXPIRY%<br>
								</div>
								<div class="col">
									<b>Last Action: </b>%LAST_ACTION%<br>
									<b>DNA Required: </b>%DNA_REQUIRED%<br>
									<b>Anticipated RTW: </b>%A_RTW%<br>
								</div>
								<div class="col">
									<b>Next Action: </b>%NEXT_ACTION%<br>
									<b>Action Type: </b>%ACTION_TYPE%<br>
									<b>Confirmed RTW: </b>%C_RTW%<br>
								</div>
							</div>
							<div class="row">
								<div class="col">
									<b>Ticket Number: </b>#%TICKET%<br>
									<b>Walmart Number: </b>%WALMART%<br>
									<b>Shift: </b>%SHIFT%<br>
								</div>
								<div class="col">
									<b>OCH Referal: </b>%OCH_REFERAL%<br>
									<b>OCH Appointment: </b>%OCH_APP%<br>
									<b>My Team Manager: </b>%TEAM_MANAGER%<br>
								</div>
								<div class="col">
									<b>Last Updated: </b>%LAST_UPDATE%<br>
									<b>Last Updated By: </b>%UPDATED_BY%
								</div>
							</div>
							<?php
							if($this->uri->segment(3) == "history")
							{
							?>
							<div class="row mt-3">
								<div class="col">
									<b>Return to Work Date: </b>%RTW_DATE%<br>
								</div>
								<div class="col">
									<b>Sanction: </b>%SANCTION%<br>
								</div>
								<div class="col">
									<b>Returned on WM1: </b>%RETURNED_WM1%<br>
								</div>
							</div>
							<div class="row">
								<div class="col">
									<b>Return Description: </b>%DESCRIPTION%<br>
								</div>
							</div>
							<?php
							}
							?>
							<div class="row">
								<div class="col mt-3"><b>Reason: </b>%REASON%</div>
								<div class="col-3 mt-3 text-end">
									<?php
									if($this->uri->segment(3) == "history")
									{
									?>
													%H_DETAILS_LINK%
									<?php
									}
									else
									{
									?>
													%DETAILS_LINK%
									<?php
									}
									?>
								</div>
							</div>
						</div>
					</template>`

**Comment by UtechtDustin** [comment]
@jynxy please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by jynxy** [comment]
@UtechtDustin im off to work now so rushed this, but can you see if you can get this to work and i can figure it out from there,

https://live.bootstrap-table.com/code/jynxy/9725

Thanks

**Comment by jynxy** [comment]
@UtechtDustin ive tried to get this to work and still cant, can you please advise, 

https://live.bootstrap-table.com/code/jynxy/9739

**Comment by UtechtDustin** [comment]
@jynxy You are trying to sort by `dateSorting` but your dataset don't even have `dateSorting`.
So if you rename `date2` to `dateSorting` it's working fine.

Working example: https://live.bootstrap-table.com/code/UtechtDustin/9757

**Comment by jynxy** [comment]
thanks @UtechtDustin your help is much appreciated.
