### ISSUE TITLE
bootstrap-table with extension Filter

### ISSUE THREAD

**Issue by DinoRavasi** [wenzhixin/bootstrap-table#4981]
Ciao I've this problem.
I have a page with a table with filterControl : truewhen i change the page to another and come back to the first page the thead contain the filter duplicated. If change the page and come back ... i saw 3 timer the field for filter.
Thank.

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by DinoRavasi** [comment]
I solved the issue ... the page is  built in angular and i've inserted the .js  (filter-control/bootstrap-table-filter-control) in the both view page ..
i move it in the index page ... and now works.
Thanks for support
