### ISSUE TITLE
Invalid setting total

### ISSUE THREAD

**Issue by sunkaixuan** [wenzhixin/bootstrap-table#4982]
var data={
columns: (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
data: (5) [{…}, {…}, {…}, {…}, {…}]
pageList: (4) [10, 25, 50, 100]
pageNumber: 1
pageSize: 10
pagination: true
total: 1000//want to set total in this way，Do not want to use 'server' and 'client'
}
$(element).bootstrapTable(data);

The current total number of grid is invalid，Don't know if support is not supported，I hope to support this，

**Comment by djhvscf** [comment]
If I'm not wrong this is not supported. We have totalField option which defines the total field name in the request object (when using server data fetch).

**Comment by sunkaixuan** [comment]
Or  like this
var data={...};
 $(element).bootstrapTable(data);
 $(element).bootstrapTable({total:1000});

**Comment by UtechtDustin** [comment]
I dont think the bootstrap table can do that.
Could you please explain your use case, if that use case makes sense we can implement that feature.

**Comment by wenzhixin** [comment]
You can use `.bootstrapTable('load', {total: 1000, rows: data})`: https://live.bootstrap-table.com/code/wenzhixin/2500. But I don't think it makes sense.

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days if the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
