### ISSUE TITLE
table 高度问题

### ISSUE THREAD

**Issue by 65style** [wenzhixin/bootstrap-table#4983]
当设置 table 高度时 数据少没有滚动条的情况下 
![image](https://user-images.githubusercontent.com/27438189/79527948-67eb9500-809b-11ea-8a7f-1048ef5678f4.png)

**Comment by CalmLong** [comment]
我也遇到这个问题了，貌似是个 Bug，#4869

**Comment by Zhangjin1993** [comment]
你用的数据源格式不对，data2.json的格式是服务端分页的格式`{ total:200,rows:[.....]}`
