### ISSUE TITLE
Cookie extension should not override data-search-text property value

### ISSUE THREAD

**Issue by Vity01** [wenzhixin/bootstrap-table#4984]
When I set initial value for the input search, the result input value is always set to the empty string.
(eventhough I don't want the searchInput text cookie to be used)
Table properties:
```
data-search-text="mySearchValue"
data-cookies-enabled="['bs.table.columns']"
```

The core of the problem resides in the cookie extension. It always passes empty string no matter other property (cookie is not defined, data-search-text is set)
```
  // this.options.searchText ... mySearchValue
  // searchTextCookie  is null
   this.options.searchText = searchTextCookie ? searchTextCookie : '';
```
I suppose that correct behavior should be something like this (pseudocode):
```
  if (cookieEnabled('bs.table.searchText') && this.options.searchText == '') {
        this.options.searchText = searchTextCookie ? searchTextCookie : '';
  }
```

Used version: 1.16.0

**Comment by UtechtDustin** [comment]
Thank you for the report.
I dont checked the whole code for now but i guess the best solution is to check if a search from cookie exists, if not it should be check if a the searchText option is used.
If that option is used the text from that option should be used, if not -> emptystring
Example Code:

```javascript
let searchText = '';
if (searchTextCookie != '') {
   searchText = searchTextCookie
}

if (this.options.searchText !== '') {
   searchText = this.options.searchText
}

//set the searchtext
```

**Comment by Vity01** [comment]
@UtechtDustin You should ignore the cookie value even it already exists if the table options (data-cookies-enabled) ignore it as well.

**Comment by UtechtDustin** [comment]
I dont think so, because if somebody use a default value he want to filter for a default dataset.
If somebody change that filter he has a reason for that.
Maybe we could add an option to switch between cookie > default and default > cookie.
@wenzhixin @djhvscf what do you think ?

**Comment by Vity01** [comment]
@UtechtDustin I don't understand your example with filters. If I don't want a cookie support for the given property (search-text in this case) why it should be the cookie used?

**Comment by 365dayes** [comment]
Able to replicate as well with cookies. Doesn't respect the data-search-text value. Also data-filter-control as well also exhibits this issue.

**Comment by djhvscf** [comment]
> I dont think so, because if somebody use a default value he want to filter for a default dataset.
> If somebody change that filter he has a reason for that.
> Maybe we could add an option to switch between cookie > default and default > cookie.
> @wenzhixin @djhvscf what do you think ?

I think we can add an option like `data-cookie-override-search='true'` or something in order to define the precedence

**Comment by 365dayes** [comment]
Looks like reverting to 1.15.5 for data filter control minimizes the issue. if that helps thanks guys 
https://unpkg.com/bootstrap-table@1.15.5/dist/extensions/filter-control/bootstrap-table-filter-control.min.js

**Comment by djhvscf** [comment]
Thanks @365dayes will compare the current and old versions.

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9692
