### ISSUE TITLE
Child Rows to show extra/detailed information on click

### ISSUE THREAD

**Issue by kitarafrei** [wenzhixin/bootstrap-table#499]
Hello,

I'm wondering if something like this is possible and if it is where should I start to make it work?
http://datatables.net/examples/api/row_details.html
I guess that's the only thing I didn't see on the examples. I was using this on a page of a site and I'm changing to your project. I like yours better, it's more flexible and easier to use.

Thank you again!!

**Comment by djhvscf** [comment]
:+1:

**Comment by kitarafrei** [comment]
Yeah, but it is possible? Do you think?

**Comment by djhvscf** [comment]
I think it is possible of course.. But @wenzhixin what do you think?

**Comment by velmuruganvelayutham** [comment]
it is really a needed one.. nice to have it..

**Comment by zagloo** [comment]
It will be veryyy nice in fact !!

**Comment by murdav** [comment]
Yes, it will be great to have this feature!

**Comment by wenzhixin** [comment]
Added: http://gotogurudev.wynconnections.co.uk/tpl/gotoguru/test.html

https://github.com/wenzhixin/bootstrap-table-examples/issues/5

**Comment by wenzhixin** [comment]
Added this feature, use `detailView` option, [docs](http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options), [example 1](http://issues.wenzhixin.net.cn/bootstrap-table/), [example 2](http://issues.wenzhixin.net.cn/bootstrap-table/#options/detail-view.html), [example 3](http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html).

**Comment by brauliobo** [comment]
beautiful, perfect, thanks!
