### ISSUE TITLE
filter-control does not work in 1.16.0 when cells contain HTML mark-up, used to work in 1.11.0 and 1.15.5

### ISSUE THREAD

**Issue by driehle** [wenzhixin/bootstrap-table#4991]
Hello everyone,

I just tried to update a website from boostrap-table 1.11.0 to the latest version 1.16.0 and ran into a strange issue. In the old version, bootstrap-table seems to have no problems with HTML mark-up in cells of the table. However, in the latest version, this leads to 

 1) delays in page loading, i.e. 1.16.0 is significantly slower than 1.11.0 (especially for larger tables, the live demo only has 100 rows, as the editor cannot save larger HTML snippents, I use about 500 rows)
 2) the browser freezing when the user clicks the filter select box for the first time (not so much which 100 rows, but for sure with 500 rows)
 3) the select box shows some weird filter entries with broken HTML snippets (see screenshots below)

Here is the live example: https://live.bootstrap-table.com/code/driehle/2565

Here is a gist with 1000 rows and the PHP script I used for data generation: https://gist.github.com/driehle/bcae719633446cf5c32ccd55c51e1371 (copying this data in the live editor works, but storing it there gives an "entity too large" error).

Here is a screenshot with boostrap-table 1.16.0:

![grafik](https://user-images.githubusercontent.com/1586788/79897207-a79edd80-8409-11ea-934b-4ac154dc8f4c.png)

And here is a screenshot with bootstrap-table 1.11.0, but it looks the same in 1.15.5 (I tried both 1.11.0 and 1.15.5 in the live example via libraries setting):

![grafik](https://user-images.githubusercontent.com/1586788/79897274-c0a78e80-8409-11ea-8f76-9d18d7f4c69e.png)

To me this clearly looks like a bug, but maybe I am doing something wrong. I have checked existing GitHub issues as well as the documentation, but unfortunatly, I was not able to find any related information.

Thanks!

**Comment by driehle** [comment]
@wenzhixin Any idea how to get the good performance of v1.11.0 back into v1.16.0?

**Comment by dabcorp** [comment]
yes , filter not work with select and data formater HTML like this :

```
	function Etat(value, row) {
		if ( value == 'En cours') {
			return '<div style="background-color:orange"><i>En cours</i></div>';
		}
		else {
			return '<div class="bg-warning"><i>'+value+'</i></div>';
		}
	};
```

**Comment by driehle** [comment]
@UtechtDustin Could you please link the ticket of which this one is supposed to be a duplicate?

**Comment by UtechtDustin** [comment]
#5076

**Comment by driehle** [comment]
@UtechtDustin @wenzhixin The bug is still present in boostrap-table 1.18.1. You can still refer to the same example I posted above: https://live.bootstrap-table.com/code/driehle/2565.

Can you please re-open the ticket?

**Comment by UtechtDustin** [comment]
@driehle there is a open issue for that #5146.

**Comment by driehle** [comment]
@UtechtDustin @wenzhixin To me it seems to be weird that this ticket is a duplicate of #5076, because this ticket has been there first, so #5076 should be a duplicate a not vice versa. Besides, I am wondering how #5146 relates to this issue, because #5146 is marked as a feature request, while this ticket clearly refers to a reproducible bug in bootstrap-table. Nevertheless, I have added a comment in #5146 to link this ticket.

**Comment by UtechtDustin** [comment]
@driehle #5146 With the `data-search-formatter` you can format the search text, so you can prevent the html issues.
