### ISSUE TITLE
Client side sorting is applied on server-side-pagination and server-sort

### ISSUE THREAD

**Issue by Shawn8901** [wenzhixin/bootstrap-table#4992]
Hi everyone,

I am currently using v1.16.0 on a project which uses Django Rest Framework as backend.
As DRF supports additional features like server side sortings via OrderingFilter i am trying to setup a configuration for bootstrap-table which uses the pre-sorted data.

If i get the documentation right the parameters to set are:

- data-side-pagination="server" 
- data-server-sort="true"

while the second parameter should be the default.

From my observation the client side sorting is applied even if server pagination and server sort is enabled.
My current solution is to provide a "noop" function and set it as customSort, which works fine for me.

My sorting behind the scene is a bit "tricky" as i have wrapped the data within an anchor as i am trying to archive clickable elements to "detail views" within my application.
That's the reason why i am seeing, that the client-side sorting is still applied, as the client side includes the href attribute of the anchor.

The field without the html code is not returned to bootstrap-table(in my example its returned for better comparison)

Please find the following example, https://live.bootstrap-table.com/code/Shawn8901/2566
For server side example code i have used the following site: https://repl.it/languages/nodejs
You may have to adjust the data-url.

Following snipped it the related code:

```js
  data = [{
      id:1,
      name: "<a href=\"/1\">a</a>",
      name_raw: "a"
    },
    {
      id:2,
      name: "<a href=\"/2\">c</a>",
      name_raw: "c"
    },
    {
      id:3,
      name: "<a href=\"/3\">b</a>",
      name_raw: "b"
    },
    {
      id:4,
      name: "<a href=\"/4\">d</a>",
      name_raw: "d"
    },
  ]
  
var http = require('http');
var url = require('url');

var app = http.createServer(function(req,res){
	res.setHeader('Access-Control-Allow-Origin', '*');
	res.setHeader('Access-Control-Request-Method', '*');
	res.setHeader('Access-Control-Allow-Methods', 'OPTIONS, GET');
	res.setHeader('Access-Control-Allow-Headers', '*');
	if ( req.method === 'OPTIONS' ) {
		res.writeHead(200);
		res.end();
		return;
	}

  res.setHeader('Content-Type', 'application/json');
    var url_parts = url.parse(req.url, true);
    var query = url_parts.query;
    sort = query["sort"];
    order = query["order"];
    if (order == null) {
      order = "asc";
    }
    if (sort != null) {
      sortOrder = order == "asc" ? 1 : -1
      data.sort((a,b) => {
        console.log(a)
        a = a[sort+"_raw"].toLowerCase();
        b = b[sort+"_raw"].toLowerCase();
        if (a < b) return sortOrder*1;
        if (a > b) return sortOrder*-1;
        return 0;
      })
    }
    console.log(data)
    res.end(JSON.stringify(data));
});

app.listen(3000);
```

If i add my noop function as data-custom-sort attribute on the table - element to override the client side sorting, sorting is working like expected.

Please let me know if i am doing something wrong or missing something for you to reproduce the issue.

**Comment by VaaL2004** [comment]
Same problem.. Please, let me see you "noop" function?

**Comment by wenzhixin** [comment]
Ref #4919, #4940.
