### ISSUE TITLE
Filter Control Don't work when we have 2 tables

### ISSUE THREAD

**Issue by rayenmhamdi** [wenzhixin/bootstrap-table#4996]
Hi,

When I have 2 tables with filter-controls
one of them work just fine,
but the other doesn't work (input and select filter controls)

this is the live example (the first table controls fails)
https://live.bootstrap-table.com/code/rayenmhamdi/2591

**Comment by wenzhixin** [comment]
The same problem as #4879.
https://live.bootstrap-table.com/code/wenzhixin/2955
