### ISSUE TITLE
最新版本1.16.0 当字段列部分设置data-width属性时，未设置的列会将其他列挤掉

### ISSUE THREAD

**Issue by litao11046** [wenzhixin/bootstrap-table#4997]
最新版本1.16.0 当字段列部分设置data-width属性时，未设置的列会将其他列挤掉

我在使用时，表格中的字段，存在几个隐藏列未设置data-width属性。当将这几个隐藏列切换显示时，会将其他列挤掉，效果如下：
![Snipaste_2020-04-23_22-13-10](https://user-images.githubusercontent.com/35892806/80123278-77de0a00-85b0-11ea-83d8-d6ca44299f3d.png)

说明：历史版本不存在这个问题

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

麻烦提供下在线例子？

**Comment by litao11046** [comment]
例子：https://live.bootstrap-table.com/code/litao11046/2643
其中，table-layout-fixed这个样式是我自定义的。
这个例子，在最新版本1.16会有问题，历史版本1.14没问题。

**Comment by wenzhixin** [comment]
因为在 [1.15.2](https://bootstrap-table.com/news/#bootstrap-table-1152) 中增加了 `widthUnit` 属性：

> **New:** Added `widthUnit` option to allow any unit.

例子： https://examples.bootstrap-table.com/#column-options/width-unit.html

因为默认为 `px`，你需要加上 `widthUnit: '%'` 来解决问题： https://live.bootstrap-table.com/code/wenzhixin/2645

**Comment by litao11046** [comment]
好的 非常感谢
