### ISSUE TITLE
filter-control dont save page number with cookie

### ISSUE THREAD

**Issue by alaintm79** [wenzhixin/bootstrap-table#4998]
Hello everyone.

Sorry for my English. I am using version 1.16.0 and the filter-control extension together with cookie and filtering does not keep the page active in the results.

This is the live example:
https://live.bootstrap-table.com/code/alaintm79/2625

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf
could you please test this (devlop branch) on your computer ?
I cant reproduce it on my computer, maybe its a "bug" of the online editor ?

![Peek 2020-06-15 22-16](https://user-images.githubusercontent.com/13292481/84701846-fd998880-af55-11ea-892e-164fc84681c5.gif)

**Comment by patremb** [comment]
I can confirm that it's a bug and can easily reproduce it. The page number always return to 1 when you add a data-filter-control="select". If you remove the filter, it works perfectly.

**Comment by jmarco** [comment]
I can confirm that it's a bug

**Comment by djhvscf** [comment]
Example with the fix: https://live.bootstrap-table.com/code/djhvscf/9667

**Comment by UtechtDustin** [comment]
@djhvscf the fix don't work for me.
If i filter for `$1` then selct the second page and refresh the example page `$1' is still set but i get `No matching records found`.

**Comment by djhvscf** [comment]
Hmm.. that's weird.. let me review that

**Comment by djhvscf** [comment]
I can't reproduce it locally. Can you double check @UtechtDustin ?

**Comment by wenzhixin** [comment]
I can reproduce the problem that @UtechtDustin said.

**Comment by djhvscf** [comment]
I can't reproduce it locally. 
![aabb1d22-f941-4054-8bea-c9106df8dcd6](https://user-images.githubusercontent.com/4496763/143724746-43f364e7-19ac-4a17-8736-93f35843eebb.gif)

@wenzhixin @UtechtDustin

**Comment by UtechtDustin** [comment]
I guess the cdn cache has been refreshed, i can no longer reproduce it on the live editor and locally.
