### ISSUE TITLE
Buttons -toolbar does not work. The official example is not complete. Request help

### ISSUE THREAD

**Issue by sunframe** [wenzhixin/bootstrap-table#4999]
<body>
	<div class="buttons-toolbar" id = "buttons-toolbar" >
		<button onclick="alert(1)">del</button>
	</div>

  
 
    <div class="table-demo">
        <table id="table"
                   data-toggle="table"
  data-height="460"
  data-search="true"
  data-show-refresh="true"
  data-show-columns="true"
  data-buttons-toolbar=".buttons-toolbar"
  data-url="json/data1.json">
 <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
  </table>
    </div>

</body>

**Comment by wenzhixin** [comment]
Like this?
https://live.bootstrap-table.com/code/wenzhixin/2638
https://live.bootstrap-table.com/code/wenzhixin/2639

**Comment by sunframe** [comment]
> Like this?
> https://live.bootstrap-table.com/code/wenzhixin/2638
> https://live.bootstrap-table.com/code/wenzhixin/2639
no,I want to add a button, similar to the refresh button, in the button bar.How do I create my own button toolbar

**Comment by UtechtDustin** [comment]
@sunframe 
You have to use `data-toolbar` (as described in our documentation), not `data-buttons-toolbar`.

**Comment by sunframe** [comment]
> @sunframe
> You have to use `data-toolbar` (as described in our documentation), not `data-buttons-toolbar`.

Thank you for your answer, but my question has not been solved. So what does the buttonToolbar do? I want two toolbars, one on the left, one on the right, and two view toggle buttons in the right toolbar.

**Comment by wenzhixin** [comment]
ref #2801

**Comment by sunframe** [comment]
https://live.bootstrap-table.com/code/sunframe/2647

**Comment by wenzhixin** [comment]
I don't know what you want to achieve?

**Comment by chrisfw791127** [comment]
您好,我也有一樣的問題
我想用buttonsToolbar功能新增一個有下拉選單的按鈕到Toolbar中
但官方範例像ghost說的那樣有問題
