### ISSUE TITLE
Methods i feel are missing or inconsistent (Removing row by index,Expand/Collapse row by unique id)

### ISSUE THREAD

**Issue by MagnificientLlama** [wenzhixin/bootstrap-table#5000]
I might be missing these methods, or easy implementation but I just can't seem to find them in the documentation and examples.

Removing row by index. - You insert and update row by index, however removing row is suddenly by definite field and value or unique Id. I often missed ability to remove a row by its index instead of having to look for a value in that one specific row so that i can remove it.

Get specific cell data by Column name and index - There might be a way to achieve this through getData but I haven't found a way yet.

Expand/Collapse row by unique id.

If all of these are already implemented but i just can't understand them from examples then I am sorry.

**Comment by wenzhixin** [comment]
ref #4909
