### ISSUE TITLE
How to use iCheck change checkbox style

### ISSUE THREAD

**Issue by GerryGe** [wenzhixin/bootstrap-table#5002]
I have followed the Issue #383 to change checkbox style wiht iCheck, but it doesn't work. I cannot click.
https://examples.bootstrap-table.com/index.html#issues/383.html

OS: Win10

````javascript
var _option = $.extend({}, $.fn.dyTable.defaults, option || {});
        var target = $(this);

        _option.onPostBody = function () {
            $(':checkbox').each(function () {
                if (!$(this).parent().hasClass('check-box')) {
                    $(this).wrap('<label class="check-box"></label>')
                        .iCheck({
                        checkboxClass: 'icheckbox-blue',
                        radioClass: 'iradio-blue',
                        //increaseArea: '20%' // optional
                    });
                    //.radiocheck()
                }
            });
            //$('.dropdown-toggle').dropdown();
        }

        target.bootstrapTable(_option);
````

![bt](https://user-images.githubusercontent.com/6952917/80349243-8c1c5280-88a1-11ea-8a46-c8c2b3324f04.gif)

Comment onPostBody event:
![bt1](https://user-images.githubusercontent.com/6952917/80343562-b4ec1a00-8898-11ea-9570-3e274e2d8058.gif)

Can you give me some advice how to integrate with iCheck?

https://live.bootstrap-table.com/code/GerryGe/2657

**Comment by djhvscf** [comment]
Did you review this example https://github.com/wenzhixin/bootstrap-table/issues/3981?

**Comment by GerryGe** [comment]
> Did you review this example #3981?

Yes, the answer is  #383. I think the author is recommend to use onPostBody event to rewrite the checkbox. but this is not work iCheck. Because iCheck wraps each input with div.

By the way, the demo of #383 have the issue of toggle dropdown. You can try to find.

**Comment by GerryGe** [comment]
@djhvscf @wenzhixin 
Can you help to fix the drop down cannot been opened of issue #383 ?
If you can provide a demo that integrates iCheck will be appreciated.

**Comment by UtechtDustin** [comment]
Why do you try to use a library which is some years old and dead ?

**Comment by GerryGe** [comment]
@UtechtDustin For some legacy projects.

**Comment by UtechtDustin** [comment]
I guess then its make more sense to use the default checkbox or use a lib which is not dead.
It dont make sense for us to support or add a feature of a not maintained lib.

What do you think @wenzhixin @djhvscf ?

**Comment by djhvscf** [comment]
Yes. You could use the default checkbox. If this is not possible please follow this example https://github.com/wenzhixin/bootstrap-table-examples/blob/master/issues/383.html
