### ISSUE TITLE
Custom filter control container doesn't work with radio buttons

### ISSUE THREAD

**Issue by jdhenry08** [wenzhixin/bootstrap-table#5004]
**Custom filter control container doesn't work with radio buttons**

I'm using the filter control extension and trying to create a custom filter control for one of my columns using radio buttons. It seems this does not work (although I was able to get it working by using a `<select>` control instead of radio buttons).

Here is a [live example](https://live.bootstrap-table.com/code/jdhenry08/2676).

**Comment by UtechtDustin** [comment]
@djhvscf Thsi is not a bug, we dont support radio buttons right now.
But i think it would be greate to support them :-)
