### ISSUE TITLE
Send searchable fields in ajax data

### ISSUE THREAD

**Issue by nicojmb** [wenzhixin/bootstrap-table#5005]
I'm writing dynamic php script to receive "bootstrap-table" parameters and generate json result.

The problem is that i receive "search" with searchString but not searchable fields to add in where query.

¿It's is possible to send in request? all elements with this attribut "data-searchable="true""???  or manualy adding in new data attribute???

Regards!

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by nicojmb** [comment]
i'dont know how showyou the reposnse in server but here are an basic examplem code:

https://live.bootstrap-table.com/code/nicojmb/2694

and showyou my server response:

![image](https://user-images.githubusercontent.com/5610392/80500207-2fd33480-896e-11ea-967a-4ac40ba0f24f.png)

The JSON receiven only has "search" field, i need in this example the two searchable fields:

- github.count.forks
- github.description

This fields i use to compose mysql query to fielter in backend.

**Comment by wenzhixin** [comment]
The [`queryParams`](https://bootstrap-table.com/docs/api/table-options/#queryparams) can be help: https://live.bootstrap-table.com/code/wenzhixin/2697

**Comment by nicojmb** [comment]
Hi, 
Nop, because i need to get this fields dinamically i do no want a lot of queryParams function to every table instance.

I think that this fields must send always in ajax request if pagination = server, it's very useful in server side.

**Comment by wenzhixin** [comment]
I understand your problem, `searchable` currently only available for `client` side pagination, consider adding support for `server` side pagination.

**Comment by nicojmb** [comment]
> I understand your problem, `searchable` currently only available for `client` side pagination, consider adding support for `server` side pagination.

Hi, adding this code after line 1653 do the trick:

https://github.com/wenzhixin/bootstrap-table/blob/dedc0e4b7ed0910990ae017796dcef7400318edb/src/bootstrap-table.js#L1653
```
if (this.options.search) {
	params.searchable = [];
	for (const column of this.columns) {
		if (!column.checkbox && column.searchable && ((this.options.visibleSearch && column.visible) || !this.options.visibleSearch)) {
			params.searchable.push(column.field);
		}
	}
}
```
