### ISSUE TITLE
Add logo and business details to PDF file only when exporting.

### ISSUE THREAD

**Issue by robertkingkira** [wenzhixin/bootstrap-table#5006]
Hi , how can i add a logo and business details to show only when i export the PDF ?
I want my table to have at the top a logo and some business details like Address, business name, phone , email... but to show only on the pdf not on the page view.
Anyone done this before ?

**Comment by wenzhixin** [comment]
I think the plugin should not support this feature.
* https://github.com/hhurz/tableExport.jquery.plugin/issues/118
* https://github.com/hhurz/tableExport.jquery.plugin/issues/228
* https://github.com/hhurz/tableExport.jquery.plugin/issues/231
