### ISSUE TITLE
filterBy not working with a select element

### ISSUE THREAD

**Issue by sonicdm** [wenzhixin/bootstrap-table#5008]
When using a dropdown select to create a filter. there is either no results found or it doesnt filter anything at all. 
```javascript
   $filter.change(function(){
      let filter_value = this.selectedOptions[0].value
      $('#selectval').html(filter_value)
      $table.bootstrapTable('filterBy', {
        id: [filter_value]                    
      })
    })
```
I included this fiddle to show it. Its using mostly the defaults for the filterBy method example. 
 [Online Example](https://live.bootstrap-table.com/code/sonicdm/2716)

**Comment by UtechtDustin** [comment]
The issue is that your `filter_value` has a other data type as the internal data.
If you parse it to a int it works fine.
But i agree it should be work with both (int, string) data types, i will create a fix.

**Comment by sonicdm** [comment]
Ah that makes a lot of sense. Thanks!

**Comment by wenzhixin** [comment]
I don't think it's a good idea to support both int and string. In this case, just only need to update this line to solve the problem:

```js
let filter_value = +this.selectedOptions[0].value
```

Example: https://live.bootstrap-table.com/code/wenzhixin/3361

**Comment by UtechtDustin** [comment]
@wenzhixin i dont thin this is a good way to solve this issue.
It should be done in the lib and should not be a problem for the developer.
