### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by chok68** [wenzhixin/bootstrap-table#5009]
Hi there!

I'm trying to implement a bootstrap-table with complex and long layout. Some headers need to have colspan=3 (to cluster months in quarters) and I also specify some columns to have 2 rowspan.

The layout problem happens in some of the quarterly columns.

[Online Example](https://live.bootstrap-table.com/code/chok68/2724) to show problem

I'm also pasting an example made with Excel of the layout I'm trying to build.

https://ibb.co/n6qHjTx

Thanks!

**Comment by GerryGe** [comment]
Hi @chok68 
I have fixed your problem, please make sure you field value is unique, cannot all value is id.
https://live.bootstrap-table.com/code/GerryGe/2831

**Comment by chok68** [comment]
> Hi @chok68
> I have fixed your problem, please make sure your field value is unique, cannot all value is id.
> https://live.bootstrap-table.com/code/GerryGe/2831

That's great!

Thanks

**Comment by wenzhixin** [comment]
> The column field name. This field must be unique, or some unknown problems may occur.

@GerryGe is right. You can checkout our documentation: https://bootstrap-table.com/docs/api/column-options/#field

**Comment by lghasemzadeh** [comment]
> Hi there!
> 
> I'm trying to implement a bootstrap-table with complex and long layout. Some headers need to have colspan=3 (to cluster months in quarters) and I also specify some columns to have 2 rowspan.
> 
> The layout problem happens in some of the quarterly columns.
> 
> [Online Example](https://live.bootstrap-table.com/code/chok68/2724) to show problem
> 
> I'm also pasting an example made with Excel of the layout I'm trying to build.
> 
> https://ibb.co/n6qHjTx
> 
> Thanks!

Hello @chok68,
I am trying to run your smoking detection script available on GitHub. Since I don't have windows I was wondering if you have the version for Ubuntu/linux of that code?
Thank you
