### ISSUE TITLE
checkbox column not linked to row record property after searching

### ISSUE THREAD

**Issue by morfin** [wenzhixin/bootstrap-table#501]
I have a checkbox column with name: "isIncluded".

My table records are initially loaded with that property as true, and so the table correctly shows the checked checkbox for those rows with isIncluded:true.

After a search, those initial checked checkboxes are gone.

**Comment by wenzhixin** [comment]
Hi @morfin , can you help to provide jsFiddle?

**Comment by morfin** [comment]
Sorry, I found the solution: maintainSelected: true

:)

**Comment by wenzhixin** [comment]
OK, close this issue.
