### ISSUE TITLE
selected detail view

### ISSUE THREAD

**Issue by francescomeloni** [wenzhixin/bootstrap-table#5010]
Hi, is there a way to activate the detailview only in some rows and not in other? 
if some array of data is present in the row  detailview:true  else detailview:false 
thanks

**Comment by UtechtDustin** [comment]
Yes, you can use the [detail filter](https://bootstrap-table.com/docs/api/table-options/#detailfilter) option.

**Comment by francescomeloni** [comment]
thanks
