### ISSUE TITLE
v.1.16.0 incorrect column format if many colummns displayed

### ISSUE THREAD

**Issue by frameworker2019** [wenzhixin/bootstrap-table#5015]
If I compose a table with many columns the header columns are not formatted correctly:
![grafik](https://user-images.githubusercontent.com/55428040/80910551-72ab5880-8d30-11ea-9183-57044b414f98.png)

If I reduce the visible columns via the column selector, BT will format  the table correctly.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by frameworker2019** [comment]
[Fiddle](http://jsfiddle.net/zmcutsk8/)

**Comment by UtechtDustin** [comment]
@frameworker2019 As @djhvscf already said, please use our Online Editor :-)

**Comment by frameworker2019** [comment]
I've tried that. But currently I cannot save the example. I'm obv. not signed, despite in the right upper corner my github user is displayed.

**Comment by UtechtDustin** [comment]
Oh okay, @wenzhixin could you check why he cant use the online editor ?

**Comment by frameworker2019** [comment]
Short example:
[Online Editor Example](https://live.bootstrap-table.com/code/frameworker2019/2809)

**Comment by frameworker2019** [comment]
> Oh okay, @wenzhixin could you check why he cant use the online editor ?

The example had more than 10000 lines. It seems that was the reason for the error. Because the displaced behavior of headers could also be proved by one table row I change the example table to be have one header row and one content row. Then I was able to save the content. 
The error message "Please sign in " will  obv. displayed in any case of error it seems.

**Comment by sekarpdkt** [comment]
Hi in `thead` and `tbody` try to add `style="font-size:12px" `

https://live.bootstrap-table.com/code/sekarpdkt/2829

**Comment by frameworker2019** [comment]
> Hi in `thead` and `tbody` try to add `style="font-size:12px" `
> 
> https://live.bootstrap-table.com/code/sekarpdkt/2829

Thx, yes this works. So the same effect can be reached by removing the font-size attribute from the table tag. And this was the error here. 
So what is the right way to define the font-size for the entire table? I thought it must be defined for the table tag only.

**Comment by wenzhixin** [comment]
You can use the `<style> to define the font-size:
```
<style>
  table {font-size: 12px;}
</style>
```
https://live.bootstrap-table.com/code/wenzhixin/2903
