### ISSUE TITLE
Filter Plugin with select-field possibly interferes with other select-fields on page

### ISSUE THREAD

**Issue by pau33** [wenzhixin/bootstrap-table#5016]
Hi,
I'm trying to use bootstrap table for a dashboard page.
I currently have the following problem and am not sure if it is a bug:

If I use the filter-control plugin (without cookies), as a select field, and if I go back one page in the browser, then the select entries are deleted (possibly overwritten with an empty entries?). That's OK.

Now I have another select field on the page that does not belong to the table. And obviously an empty field is also added there. This doesn't happen without a select field (input field) in the filter plugin.

Can it be that the filter control influences all select fields when navigating back, not just those belonging to the table.

If so, is this a bug or is there an easy way to prevent it?
My browser is the newest Chrome 81.

Thanks in advance.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

maybe ref #4977#issuecomment-614444687

**Comment by pau33** [comment]
I was not able to reproduce this behavior in the Online Example Editor.
But you pointed me to the right direction with #4977.

I jumped back and forward on the page. Without filter control this worked but with activated filter control it looks like the values were not cached. It behaves, like a new load of the page.
So I took your advice in #4977 and cached some values in the session storage. This works. Thank You very much.

Is this your general advice, or is there a simple way supported by bootstrap-table to store/restore all selected filter values?

**Comment by UtechtDustin** [comment]
@pau33 Im not sure if #4977 is the same issue as you have because of the following sentence:

> Now I have another select field on the page that does not belong to the table. And obviously an empty field is also added there. This doesn't happen without a select field (input field) in the filter plugin.

Could you please provide us a short example ? (If you cant reproduce it on the editor, please upload your code and we have to check it on our local machine)

**Comment by pau33** [comment]
Ok, let me try.

I am attaching a very simplified HTML file for you.
I have now found that Firefox V76 does not show the error (if it is one), but Chrome V81 does.

If you open the file in Chrome, you will see a select-filed in the top left with 2019, 2020. If you go to any other website and then return with back, then the number in the select-field has disappeared and an additional empty entry has been selected.

But if you comment out the filtercontrol (line 154) and do the same thing again, the browser keeps the number in the select-filed.

I don't know if this is a mistake or not, but the page behaves differently with or without a filter control.

As suggested by wenzhixin, I used local storage and turned off the behavior with me, but the observation may help you anyway.


[table.zip](https://github.com/wenzhixin/bootstrap-table/files/4678395/table.zip)

**Comment by UtechtDustin** [comment]
I can reproduce the issue with chrome, it seems that this is a issue of chrome.
After i reproduced the issue i inspected (using the development tools) the select and there is no new (empty) option (tag). This means chrome fails to set/show the selected option.

**Comment by pau33** [comment]
Thank You for your reply.

Do you know, why the behavior ist different with and without the filter control?

**Comment by UtechtDustin** [comment]
Not really, i tried to figure it out (e.g. i commented out the parts which interact with the select) but i don`t found it.
