### ISSUE TITLE
Can column formatter add additional parameters

### ISSUE THREAD

**Issue by kangarooxin** [wenzhixin/bootstrap-table#5019]
Can column formatter add additional parameters

Or config some parameters through `data-` on the column, which can be obtained in the formatter

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/column-options/#formatter

> The context (this) is the column Object.

You can use `this` context to solve your problem: https://live.bootstrap-table.com/code/wenzhixin/2792
