### ISSUE TITLE
Value type DateTime for some Data-Field give same value for all row

### ISSUE THREAD

**Issue by handarueri** [wenzhixin/bootstrap-table#502]
Hi, i use bootstrap table for my website project. When the data url give some data json that contain value with datetime type, the value that shown in table is give same value in all row. This is the value from my database
![image](https://cloud.githubusercontent.com/assets/10350870/6019771/dd43ac60-abd6-11e4-8bf8-b72d1d40822b.png)
but ,when it generate to table, the value become 
![image](https://cloud.githubusercontent.com/assets/10350870/6019782/f3efb36e-abd6-11e4-83fa-04d82256121a.png)
 How to fix this problem ? Thank you

**Comment by djhvscf** [comment]
Hi @handarueri  I think you can use the **formatter**  function ( http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options ) because you are getting the ticks of the date and you have to convert it to a new Date.. So I think you can have something like this:

```javascript
function(value, row, index) {
 var date = new Date(value);
 var mm = date.getMonth()+1;
 var dd = date.getdate();
 var yy = new String(date.getFullYear()).substring(2);
 if (mm < 10) { 
    mm = "0"+mm;
 }
 if (dd < 10) {
    dd = "0"+dd;
  }
 return ""+mm+dd+yy;
};
```

**Comment by handarueri** [comment]
Thank you for your reply @djhvscf

**Comment by djhvscf** [comment]
@handarueri  Did it work?

**Comment by k--andrey** [comment]
@djhvscf 
Can uoy explain how to use this function?
How it's called on page load?

**Comment by djhvscf** [comment]
ok, there is a column option called: *data-formatter*.. there is where you have to set the function name of you formatter attribute.. see this example in order to know how to use the formatter function: http://jsfiddle.net/wenyi/e3nk137y/21/light/ and also please review the documentation: http://bootstrap-table.wenzhixin.net.cn/documentation/ @k--andrey

**Comment by k--andrey** [comment]
@djhvscf 
Thanks for answer I have just found solution:
Income data:
```
[{"DDM":"\/Date(1447200000257)\/","TEXT_S":"текст 1"},
{"DDM":"\/Date(1447300000257)\/","TEXT_S":"текст 2"}]
```
HTML:
```
<div class="container">
<table id="table" data-locale="uk-UA"><thead><tr>
<th data-field="DDM" data-formatter="winLOSSFormatter">Дата</th>
<th data-field="TEXT_S">Опис</th>
</tr> </thead> </table> </div>
```
js:
```
function winLOSSFormatter(value) {
	var date = new Date(parseInt(value.slice(6, -2)));
	return date.toLocaleDateString("uk");
}
$('#table').bootstrapTable({
	url:"testData.json"
});
```

**Comment by djhvscf** [comment]
Great! @k--andrey

**Comment by WeiB71** [comment]
how can i do it in dynamically created rows that <th> is not written
