### ISSUE TITLE
Fixed header not portable when using dragtable

### ISSUE THREAD

**Issue by leyman0111** [wenzhixin/bootstrap-table#5026]
I try to make the bootstraptable with draggable columns using dragtable, but fixed header not portable. Here is code: https://live.bootstrap-table.com/code/leyman0111/2853

**Comment by wenzhixin** [comment]
You can use the bootstrap-table-reorder-columns extension(the develop branch): https://live.bootstrap-table.com/code/wenzhixin/2856.
