### ISSUE TITLE
filter-control + cookie + serverSide

### ISSUE THREAD

**Issue by licaricristian** [wenzhixin/bootstrap-table#5027]
With filterControl enabled, combined with cookie and serverSide pagination, table doesnt apply filters properly.

The issue it seems to exists in two extensions file:

- bootstrap-table-filter-control.js: event onColumnSearch (general filtering issue, on server cookie has always the previous value)
- bootstrap-table-cookie.js: method initServer (filtering issue on first request)

In order to apply in the correct sequence the file **bootstrap-table-filter-control.js** has been patched as follow.
We noticed that the table set cookie only onColumnSearch, that is triggered after onSearch, if you have a very slow client ajax request requires time to start, this allow to onColumnSearch event set cookie and collect it on the request. But if you have a normal client this doesnt happen.
The result is that sometimes server receive cookie and filter properly and sometimes no.
So inverting the triggering this doesn't happen.

It is impossible provide an online example, cause only if you have a ServerSide pagination with a "slowly" server response combined with "slowly" client it happens.

In order to be able to filter the table at first loading we patched file **bootstrap-table-cookie.js** erasing the if statement that exists from the function if cookie are enable.

Best regards
Cristian

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!
@UtechtDustin Have we fixed this issue in `develop` branch?

**Comment by UtechtDustin** [comment]
Could be possible, let wait for the example.
I will check if that is already fixed in our develop branch.

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days from you.
