### ISSUE TITLE
Card view external formatter instead of default

### ISSUE THREAD

**Issue by sekarpdkt** [wenzhixin/bootstrap-table#5031]
Hi

Like `    data-detail-formatter="tableManager_detailFormatter"` is there any option for card-view-formatter?

If not, will you be able to add. I did following changes and it is working. in `key: "initRow",`, I modified
```
	  if (this.options.cardView) {
	        html.push("<td colspan=\"".concat(this.header.fields.length, "\"><div class=\"card-views\">"));
                  }

```
as

```
	if (this.options.cardView) {
	    html.push("<td colspan=\"".concat(this.header.fields.length, "\"><div class=\"card-views\">"));
            if ( this.options.cardViewFormatter!=undefined){
                const thisRowData=this.options.cardViewFormatter(i,item)
                html.push(thisRowData)
                html.push("</div></td></tr>")
                return html.join('');
            }
        }
```
Keeping different options for detailed and card view will allow us to have two different types of view for card / detailed view.

**Comment by wenzhixin** [comment]
Added `detailView` support in #5032, you can use like this: https://live.bootstrap-table.com/code/wenzhixin/2912 .
