### ISSUE TITLE
Can column headings be translated？

### ISSUE THREAD

**Issue by vuvivian** [wenzhixin/bootstrap-table#5035]
when I define an english column title, i want to translate the title to chinese,  What should I do?
`
   column = [{{
      title: 'billNo',
      field: 'bill_number',
    }]
`
I put it under the translation file, but it doesn't work

`
$.fn.bootstrapTable.locales['zh-CN'] = {
  billNo () {
    return '单据编号'
  },
}
`

**Comment by wenzhixin** [comment]
You can use the [`i18n Enhance`](https://bootstrap-table.com/docs/extensions/i18n-enhance/) extension: https://examples.bootstrap-table.com/#extensions/i18n-enhance.html
