### ISSUE TITLE
获取选择行数据 getAllSelections 的问题

### ISSUE THREAD

**Issue by luhuaitong** [wenzhixin/bootstrap-table#5037]
你好，我在使用的过程中，当我的数据源选择data 方式去取的话，我的数据是从服务器查出放到了全局变量中取，然后点查看的时候取加载这个变量中的数据，然后这个获取所选中行的方法就失效了，如果不点任何checkbox 的话，就没有一条被选中，但是点击任何一个checkbox的，获取所选数据就会获取到全部的数据，请问怎么解决，在线等啊挺着急的

**Comment by wenzhixin** [comment]
麻烦提供下在线例子 [Online Example](https://live.bootstrap-table.com)。

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days from you.
