### ISSUE TITLE
Add button to filter specific field and content?

### ISSUE THREAD

**Issue by docho** [wenzhixin/bootstrap-table#504]
Hi wenzhixin,

I really like your script as it makes working with data tables much easier!

But there's something I don't know, how to do:
I would like to add one or two buttons, that are used as "filter switches":
Say I have a table with some columns.
If I click the button, I want only those entries shown that have a specific value (let's say "testvalue") in a specific column (e.g. "testcol").
How would I accomplish that?

**Comment by docho** [comment]
Never mind, I hadn't seen the filterBy-method. It's working right the way it should :-)

**Comment by dabros** [comment]
Just in case anyone looking to do something with filterBy but cant find examples, im currently looking at http://bootsnipp.com/snippets/featured/panel-table-with-filters-per-column and maybe adapting code from there

**Comment by djhvscf** [comment]
You should use the filterControl column option to do that

**Comment by dabros** [comment]
Link to #528
