### ISSUE TITLE
关于竖向滚动条的样式问题

### ISSUE THREAD

**Issue by xusheng1987** [wenzhixin/bootstrap-table#5043]
经反复试验，从1.13.3开始，竖向滚动条变成了这种样式：
![宇信通截图未命名](https://user-images.githubusercontent.com/10825412/82771517-e98acb80-9e6e-11ea-96e8-67cacab87017.png)
怎么能修改成以前的竖向滚动条在表格内的那种样式

**Comment by UtechtDustin** [comment]
@wenzhixin could you please translate it ?

**Comment by wenzhixin** [comment]
Due to the code implementation change, the style of scroll bar in the latest version has changed. He wants to use the original style of scroll bar.

**Comment by UtechtDustin** [comment]
^
