### ISSUE TITLE
Data-filter-controls disappear on Column-switch.bs.table

### ISSUE THREAD

**Issue by rayoray** [wenzhixin/bootstrap-table#5045]
"Inside the detail view, when i trigger "Get" function sub table, then perform column-switch, the data filter controls disappear."

**Step 1** when i expend the detail view, i see the "Get" button loaded. 
**Step 2** when i click the "Get" button, the Sub-table is loaded into the detail view.
**Step 3** when I try to perform Column-switch, i lose all the Data-filter controls.

 _see codepen example_:  https://codepen.io/rayzoray/pen/abvxgog

any help on how i can keep the data-filter controls would be much appreciated.

**Comment by UtechtDustin** [comment]
Demo on our live editor: https://live.bootstrap-table.com/code/UtechtDustin/3091

**Comment by djhvscf** [comment]
This is fixed in develop branch

https://live.bootstrap-table.com/code/djhvscf/3646

**Comment by UtechtDustin** [comment]
@djhvscf Your example dont work for me, also if this is already fixed in the develop branch why is the issue still open :D ?

**Comment by djhvscf** [comment]
Fixed in this PR https://github.com/wenzhixin/bootstrap-table/pull/5129
