### ISSUE TITLE
Cookie extension does not work with custom filter control container

### ISSUE THREAD

**Issue by jdhenry08** [wenzhixin/bootstrap-table#5048]
Cookie extension does not work with custom filter control container

When using cookie extension and filter control extension with a custom container (see live example below), the custom filter is not applied on page refresh, even though the cookie is stored correctly.

1. Select value to filter by
2. See that filter is applied correctly
3. Refresh page
4. See that filter is no longer applied
5. Check cookies - the filter cookie exists with the correct value

[Online Example](https://live.bootstrap-table.com/code/jdhenry08/3149)

This seems to be a problem with both the released 1.16.0 version as well as the develop branch.

**Comment by UtechtDustin** [comment]
Maybe related to #5076.

**Comment by jdhenry08** [comment]
This still doesn't work with custom filter controls if they are radio buttons:
[https://live.bootstrap-table.com/code/jdhenry08/3446](https://live.bootstrap-table.com/code/jdhenry08/3446)

**Comment by UtechtDustin** [comment]
Please open a new Issue for that problem, thanks :-)
