### ISSUE TITLE
Create table without table-hover by default

### ISSUE THREAD

**Issue by frameworker2019** [wenzhixin/bootstrap-table#5049]
Request that BT disables table-hover by default. 
There's a workaround [here](https://github.com/wenzhixin/bootstrap-table/issues/2989
)

Reason: It's easier to enable table-hover if needed, than to remove it, especially if the table was created by PHP for example.

**Comment by UtechtDustin** [comment]
Its easy to remove the table-hover class, just use the [classes](https://bootstrap-table.com/docs/api/table-options/#classes) option.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3165

**Comment by frameworker2019** [comment]
Yes, this did the job.
