### ISSUE TITLE
group-by-v2的问题

### ISSUE THREAD

**Issue by moocin** [wenzhixin/bootstrap-table#5055]
你好，我在使用group-by-v2时，通过后台获取的数据在js文件里面进行渲染时出现Cannot read property 'forEach' of undefined，这个数据渲染只能通过页面定义data-url来渲染吗？
`<div class="matertabbox">
                    <table id="equipmentTable" data-group-by="true" data-group-by-field="equipmentName"
                           class="table table-bordered table-striped" data-mobile-responsive="true">
                    </table>
                </div>`
![TPY$C1`36QDCIU72HEM6CQB](https://user-images.githubusercontent.com/54888786/83246068-2ee32c00-a1d4-11ea-8e31-aff1c481e3a0.png)

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
@moocin 你是如何使用的，麻烦提供下在线的例子。

Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issue because we got no response/example from you within 7 days.
