### ISSUE TITLE
detailView & getSelections

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#5057]
Hello!

I have a table with sub table - detailView, both have a selected checkbox on first column for each row. For example, top level is a list of person with ID, the detailView displays persons related to this top level person, each with his or hers own ID.

'getSelections' only give me first level selected.

How can I get all selected person, including selected in detailView?

Thanks!

**Comment by UtechtDustin** [comment]
Hey @startovernow, please provide us an example using our [onlin editor](live.bootstrap-table.com/);

**Comment by UtechtDustin** [comment]
I close this issue because we got no response from your within 7 days.
If you still need help please provide us an example and we will reopen the issue.
