### ISSUE TITLE
Undefined/null to bottom

### ISSUE THREAD

**Issue by initialize** [wenzhixin/bootstrap-table#506]
Hello. It would be nice with a suppressUndefined: (true|false) or such for sorting, so that rows with selected column undefined are excluded from sorting and automatically pushed to bottom of list.  

Example:
```
source: [ 3, undefined, 1, undefined, 2 ]
sort asc: [ 1, 2, 3, undefined, undefined ]
sort dec: [ 3, 2, 1, undefined, undefined ]
```
As opposed to current sort:
```
source: [ 3, undefined, 1, undefined, 2 ]
sort asc: [ undefined, undefined, 1, 2, 3 ]
sort dec: [ 3, 2, 1, undefined, undefined ]
```

**Comment by djhvscf** [comment]
:+1:

**Comment by wenzhixin** [comment]
Now fixed: http://jsfiddle.net/e3nk137y/1256/

**Comment by martinburch** [comment]
According to the fiddle from @wenzhixin this doesn't seem to have been fixed. The idea is to put all undefined at the bottom no matter the sort direction. Here's a screenshot of the ascending sort:

![image](https://cloud.githubusercontent.com/assets/2335284/17671791/c81790fe-62e6-11e6-9446-ce78d6a00832.png)
