### ISSUE TITLE
Introduce property to hide the pagination info

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5062]
It would be nice to have a `data-` property to hide the pagination info.

I'm currently doing:

```
      formatRecordsPerPage: function formatRecordsPerPage(pageNumber) {
          return ''; // ''.concat(pageNumber, " items per page");
      }
```

Note I want keep page navigation controls.

**Comment by UtechtDustin** [comment]
Do you mean something like that: https://live.bootstrap-table.com/example/options/only-info-pagination.html
Just with the page controls ?

**Comment by marceloverdijk** [comment]
Hi @UtechtDustin 

Something similar but then the other way around.

So I want to hide the `Showing 21 rows` but want navigation links to prev, next and other pages.

**Comment by UtechtDustin** [comment]
Oh okay i understand.
Could i ask why do you try to hide the information about the rows ?
It's not a common use case i guess, im not sure if it makes sense to implement a feature for that if you already found a solution for that.

**Comment by marceloverdijk** [comment]
formatRecordsPerPage: function formatRecordsPerPage(pageNumber) {
          return ''; // ''.concat(pageNumber, " items per page");
      }

indeed works so there is a solution.
But a `data-*` option would be cleaner imo.

My use case is similar as Github in terms of pagination:

![image](https://user-images.githubusercontent.com/197004/83923962-accea680-a783-11ea-9978-4db32bfef1a0.png)

They also only show the navigation buttons, but no info about how many records there are.

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf what do you think about that ?
We maybe could remove the onlyInfoPagination option and add a new option wich accept a array.
On that array we could define which parts of the pagination should be (not) displayed.

**Comment by wenzhixin** [comment]
OK, label as a feature.
