### ISSUE TITLE
Filter Control & Search not working together

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5063]
See: https://live.bootstrap-table.com/code/marceloverdijk/3244

- Filter item price on e.g. `$0`
- This will show only `Item 0` in the table
- In the top right Search input type `Foo`
- Nothing changes in the table.
- Expected behaviour was that no record was not displayed anymore as the `Item 0` record did not match `Foo`.

**Comment by UtechtDustin** [comment]
This issue is already fixed in our develop Branch.
You can check if something is fixed in our develop branch by set `Bootstrap Table Source` to `From Github src` and `GitHub src branc` to `develop`.
Working Example: https://live.bootstrap-table.com/code/UtechtDustin/3311

**Comment by marceloverdijk** [comment]
Thx looking forward to the next release with the 🐛 fix
