### ISSUE TITLE
Add showFilterControlSwitch to show/hide filter control from toolbar

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5065]
It would be nice to have an option like `data-show-filter-control-switch`: `true` to show/hide the filter controls dynamically and have a button for it in the toolbar.

Similar as the show pagination switch.

**Comment by marceloverdijk** [comment]
Maybe it could use the fa toggle-on/toggle-off icons?

**Comment by marceloverdijk** [comment]
Related to #5061

**Comment by marceloverdijk** [comment]
This is a working example: https://live.bootstrap-table.com/code/marceloverdijk/3277

Wdyt?

**Comment by UtechtDustin** [comment]
Looks good, but i think we should first fix and merge #5061.
After that we can use the new method for the new toggle button.

**Comment by marceloverdijk** [comment]
@UtechtDustin Yes I agree to fix #5061 first. I have looked at it but can't find it yet.
This example was just to get feedback, it should off course be integrated in the filter control extension.

Btw maybe the approach in #5061 by calling `refreshOptions` is maybe not the good way to do it?

```
toggleFilterControl () {
    this.refreshOptions({
      filterControl: !this.getOptions().filterControl
    })
  }
```

**Comment by UtechtDustin** [comment]
I also think this not the best way to solve it, because its a method which is designed for external usage not for internal.

Im currently busy to check that, but as soon i have some freetime i will check that!

**Comment by marceloverdijk** [comment]
@djhvscf Once #5061 is solved and merged I will create a PR asap for the adding a switch button in the toolbar.
