### ISSUE TITLE
Attribute customSearch not working #customSearch #attribute

### ISSUE THREAD

**Issue by rodi189** [wenzhixin/bootstrap-table#5067]
Using customSearch attribute but is ignoring by table
`$('#table').bootstrapTable({
      customSearch:customSearch,
data: data2,
          locale: "es-PY",
          pagination: true,
        clickToSelect: true,    
        showColumns: true,
        paginationVAlign: "both",
        pageList: "[10, 25, 50, 100, 200, All]",
        showButtonText: true,
        buttonAlign: "right",
        search: true,
          showSearchClearButton: true,
          showPrint: true,
          detailView: true,
          detailFormatter: 'detailFormatter2',
          showRefresh: true,
          stickyHeader: true,
          stickyHeaderOffsetLeft: "30px",
            stickyHeaderOffsetRight: "30px",
            multipleSelectRow: true,
            toolbar: "#toolbar2",
            mobileResponsive: true,
            showToggle: true,
            showExport: true,
            searchAccentNeutralise: true,
            exportDataType: $('#selectExportType2').val(),
            exportTypes: ['excel', 'pdf', 'json', 'txt', 'csv', 'sql', 'xml'],
            filterControl: true,
    })

function customSearch(data, text) {
    console.log("exe");
    return data.filter(function (row) {
      var resultRow;
      var rowPrice = row.price.indexOf(text);
      var rowName = row.name.indexOf(text);
      
      if(rowPrice > -1){
         resultRow = row;
      }else{
        if(rowName > -1){
           resultRow = row;
        }else{
          //NOTHING
        }
      }
      
      
      return resultRow;
    })
  }
`

**Comment by rodi189** [comment]
Using this imports
`<link href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
  	<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


  	<link href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css" rel="stylesheet">
	<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
	

	
	
	
	<script src="bootstrap-table-es-PY.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/multiple-sort/bootstrap-table-multiple-sort.js"></script>

	<link href="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/sticky-header/bootstrap-table-sticky-header.css" rel="stylesheet">
	<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/sticky-header/bootstrap-table-sticky-header.min.js"></script>

	<link href="https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.1/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet">

	<script src="https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.1/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/editable/bootstrap-table-editable.min.js"></script>
	<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/accent-neutralise/bootstrap-table-accent-neutralise.min.js"></script>
	


<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/mobile/bootstrap-table-mobile.min.js"></script>

<link href="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/fixed-columns/bootstrap-table-fixed-columns.min.css" rel="stylesheet">

<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/fixed-columns/bootstrap-table-fixed-columns.min.js"></script>

<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/auto-refresh/bootstrap-table-auto-refresh.min.js"></script>
	
	

<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/export/bootstrap-table-export.min.js"></script>
<script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
<script src="https://unpkg.com/tableexport.jquery.plugin/libs/jsPDF/jspdf.min.js"></script>
<script src="https://unpkg.com/tableexport.jquery.plugin/libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/print/bootstrap-table-print.min.js"></script>
`

**Comment by rodi189** [comment]
Only in test from an example is working:

https://live.bootstrap-table.com/code/rodi1:89/3253

**Comment by UtechtDustin** [comment]
Could you please describe your issue instead of posting the source code ?
If i understand it correctly the custom search is not working for you, but on your example the custom search works fine.

So please give us more informations, do you use the newest bootstrap-table version (as in your example) ?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days, if you still need help please answer the questions above then we will reopen the issue.

**Comment by rodi189** [comment]
`<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/accent-neutralise/bootstrap-table-accent-neutralise.min.js"></script>`

remove this work for me
