### ISSUE TITLE
data-filter-data not loading data from [object array].key

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5070]
As can be shown here: https://live.bootstrap-table.com/code/marceloverdijk/3267
the `data-filter-data` does not load from `[object array].key`.

E.g. having:

```
  var data = [
    { id: 1, name: 'John Doe', country: 'UK' },
    { id: 2, name: 'Jane Doe', country: 'UK' },
    { id: 3, name: 'Alice', country: 'US' },
    { id: 4, name: 'Bob', country: 'US' },
  ]
```

then using `data-filter-data="obj:data.country"` does not work (the filter select has no values).

I think because the lib expects the `country` in `obj:data.country` to be an array?
So probably this is not an issue but more a feature request.

Maybe both `var` and `obj` could support a notation like `var:[object_array_variable].key` and `obj:[object_array_variable.in.object].key` (note the square brackets) to loop over the object array and get the value from the key.
So with above `data` var this would look like: `var:[data].country`.

**Comment by marceloverdijk** [comment]
I found out in https://github.com/wenzhixin/bootstrap-table/issues/5071 that the `data-filter-data` expects an key/value object and not simply an array.
So it is probably not so simple as mentioned above.

**Comment by marceloverdijk** [comment]
For others interested I used a `data-filter-data` function to reduce the required values from the table data:

```
  var data = [
    { id: 1, name: 'John Doe', country: 'UK' },
    { id: 2, name: 'Jane Doe', country: 'UK' },
    { id: 3, name: 'Alice', country: 'US' },
    { id: 4, name: 'Bob', country: 'US' },
  ]
  
  function countryFilterData() {
    return data.reduce(function(o, row) {
      o[row.country] = row.country;
      return o;
    }, {})
  }
```

Full example here: https://live.bootstrap-table.com/code/marceloverdijk/3272

**Comment by UtechtDustin** [comment]
As you already found out you can use a function, i guess the issue is resolved.
