### ISSUE TITLE
Problems filtering through with "filterBy" method (Version: 1.16.0)

### ISSUE THREAD

**Issue by fhariano** [wenzhixin/bootstrap-table#5072]
I'm trying to apply my own date range filter by using the "filterBy" method, but it's not working. The workaround I implemented to use it was to pass each and every date from the start date to the end date to the filter.
{
   dateField: [
    '2020-03-01',
    '2020-03-02',
    '2020-03-03',
    ]
}
like example: [https://jsfiddle.net/wenyi/06pg2wms/11/](url)
Now, if add bootstrap-table-accent-neutralise extension the filter stop worked and wokrs only with single query:

{
   dateField: '2020-03-01'
}

Can you help me?! I need of the bootstrap-table-accent-neutralise extension, because I am using Portuguese language.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issue because we got no response from your within 7 days.
If you still need help please provide us an example and we will reopen the issue.

**Comment by fhariano** [comment]
Sorry! 
Please, reopen the issue.
Follow the example: [https://jsfiddle.net/fhariano/sw3o6cpn/3/](url)

**Comment by UtechtDustin** [comment]
@fhariano 
As wenzhixin said, please use our Online Editor to create the example.

**Comment by fhariano** [comment]
This is my Online Editor: https://jsfiddle.net/fhariano/sw3o6cpn/3/  (FHARIANO)

**Comment by UtechtDustin** [comment]
As said, please use our [Online Editor](https://live.bootstrap-table.com/), not jsfiddle!
If you need help with the editor, please check the [wiki page](https://github.com/wenzhixin/bootstrap-table/wiki/Online-Editor-Explanation).

**Comment by fhariano** [comment]
Sorry!
Follows: https://live.bootstrap-table.com/code/fhariano/3467

The bootstrap-table-accent-neutralise extension is activated!

Try to filter for example: 01/02/2020 to 02/02/2020 will not work, but if you to remove the bootstrap-table-accent-neutralise extension and try again, it is work succefully.
