### ISSUE TITLE
getData and formtatted fields

### ISSUE THREAD

**Issue by angelinux-slack** [wenzhixin/bootstrap-table#5073]
In getData method, I can 't get all formatter values.

Example
getData is returning field but it have formatted.

There is a way to fetch formatted values?

https://live.bootstrap-table.com/code/angelinux-slack/3279

Thanks

**Comment by wenzhixin** [comment]
You can define a new field that you want, a workaround example: https://live.bootstrap-table.com/code/wenzhixin/3306.

**Comment by UtechtDustin** [comment]
@wenzhixin Maybe we should add a option which allows to get the formatted data ?
