### ISSUE TITLE
Page List fails

### ISSUE THREAD

**Issue by kikyoluka** [wenzhixin/bootstrap-table#5074]
When I use data from `$table.bootstrapTable({ data: data })` instead of `data-url`, the page list option doesn't work, it doesn't appear below my table, including paging options.

I make sure I use all the correct configuration because when I put `$table.bootstrapTable({ data: data })` method is replaced by the `data-url` method, it works as well as the official website case.

like this ,I created an allData object , which is the same as the data of the data-url. When I use $table.bootstrapTable({data: alldata.rows}), the page-list and the paging bar will not be displayed :

[Online Editor](https://live.bootstrap-table.com/code/kikyoluka/3294)

**Comment by marceloverdijk** [comment]
@kikyoluka you have set a `data-side-pagination="server"`. Remove it and it works.

**Comment by kikyoluka** [comment]
> @kikyoluka您已设置一个`data-side-pagination="server"`。删除它，它可以工作。
> 
> 请参阅https://live.bootstrap-table.com/code/marceloverdijk/3299
> 注意，由于页面大小少于25，因此您只会看到5、10和25。

Thanks, I also tried to delete some configuration items at first but it didn't work, now it is solved with your help.
