### ISSUE TITLE
Problems with the use of bootstrap4 modal

### ISSUE THREAD

**Issue by kikyoluka** [wenzhixin/bootstrap-table#5075]
I want to use bootstrap-table in the bootstrap4 mode, but I encountered a problem. When I refresh the webpage and click the button to pop up the modal box, the bottom of the table becomes messy. When I select a page list or paging option it will return to normal and then keep it normal until the next time I refresh the page.

I tried deleting the `data-height` attribute, but I can’t do that because the sidebar of the table disappears.

Is there any way to display it normally every time I refresh the webpage and enter?

see: [Online Editor](https://live.bootstrap-table.com/code/kikyoluka/3301)
Thanks

**Comment by wenzhixin** [comment]
This problem has been fixed in #4640.
Working Example: https://live.bootstrap-table.com/code/wenzhixin/3305.
