### ISSUE TITLE
Filter-control is broken while using the cookie extension.

### ISSUE THREAD

**Issue by UtechtDustin** [wenzhixin/bootstrap-table#5076]
The Cookie extension has some issues.
On the following example i use the cookie extension and the filter-control extension.
The filter-control is broken (e.g. if you searach for '555' on the `VE` column the from column will be filtered).

Also the Html in the select is broken (worked in the 15.5).

Example: https://live.bootstrap-table.com/code/UtechtDustin/3304

**Comment by marceloverdijk** [comment]
@UtechtDustin You mean the select for the `state` field?

I encountered a similar issue and solved it by using a `data-filter-data="var:countries"` on the field.
See https://github.com/wenzhixin/bootstrap-table/issues/5071 | https://live.bootstrap-table.com/code/marceloverdijk/3271

Would be great if that is not needed.

**Comment by UtechtDustin** [comment]
Yes, if i have time later i will check that.

**Comment by marceloverdijk** [comment]
Another thing to note is the following.

I have a table where the first column is rendered as a link.
So it has a formatter like:
```
  function nameFormatter(name, driver) {
    return '<a href="/drivers/' + driver.id + '">' + name + '</a>';
  }

```
Now when I serach for `vers` all drivers are matched as the search uses the `<a href="/drivers/` part.

**Comment by UtechtDustin** [comment]
@marceloverdijk 
This is not a bug, you use a formatter so we also search in the formatted value.
Do search for the normal value please use the [searchFormatter option](https://bootstrap-table.com/docs/api/column-options/#searchformatter).
Example: https://live.bootstrap-table.com/code/UtechtDustin/3310

**Comment by marceloverdijk** [comment]
Nice, I wasn’t aware of the property, thx 👍

**Comment by UtechtDustin** [comment]
@djhvscf @wenzhixin does it make sense to add a "selectFormatter" ?
As example the column data contains `0` or `1`, in the table should be displayed `i.o.` for `0` and `fault` for  `1`.
The `i.o.` and `fault` should be displayed with a formatter (bootstrap badge).
Now the select contains 0 and 1 or the html (which breaks the select), in the selecht should be `i.o.` and `fault` visible.

**Comment by djhvscf** [comment]
> @djhvscf @wenzhixin does it make sense to add a "selectFormatter" ?
> As example the column data contains `0` or `1`, in the table should be displayed `i.o.` for `0` and `fault` for `1`.
> The `i.o.` and `fault` should be displayed with a formatter (bootstrap badge).
> Now the select contains 0 and 1 or the html (which breaks the select), in the select should be `i.o.` and `fault` visible.

I think it does make sense to add that new option. And actually for me it should be the default behavior

**Comment by UtechtDustin** [comment]
> > @djhvscf @wenzhixin does it make sense to add a "selectFormatter" ?
> > As example the column data contains `0` or `1`, in the table should be displayed `i.o.` for `0` and `fault` for `1`.
> > The `i.o.` and `fault` should be displayed with a formatter (bootstrap badge).
> > Now the select contains 0 and 1 or the html (which breaks the select), in the select should be `i.o.` and `fault` visible.
> 
> I think it does make sense to add that new option. And actually for me it should be the default behavior

There was a other issue for something similar, but i cant find that...
On that Issue i asked if it would make sense to use the `.text()`  function.
What do you think ?

**Comment by djhvscf** [comment]
> > > @djhvscf @wenzhixin does it make sense to add a "selectFormatter" ?
> > > As example the column data contains `0` or `1`, in the table should be displayed `i.o.` for `0` and `fault` for `1`.
> > > The `i.o.` and `fault` should be displayed with a formatter (bootstrap badge).
> > > Now the select contains 0 and 1 or the html (which breaks the select), in the select should be `i.o.` and `fault` visible.
> > 
> > 
> > I think it does make sense to add that new option. And actually for me it should be the default behavior
> 
> There was a other issue for something similar, but i cant find that...
> On that Issue i asked if it would make sense to use the `.text()` function.
> What do you think ?

Oh, I don't really recall that one. It is related to this? https://stackoverflow.com/a/807908/4817348

**Comment by UtechtDustin** [comment]
Yes, the .text() function will fetch all Text without the Html part.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3409

**Comment by UtechtDustin** [comment]
@djhvscf reminder

**Comment by UtechtDustin** [comment]
As #5146 is marked as feature we can close this issue.
