### ISSUE TITLE
Editable and Checklist won‘t push multiple Values

### ISSUE THREAD

**Issue by FuRIOuZ197** [wenzhixin/bootstrap-table#5078]
When i uses the editable Extension in checklist mode and i selected multiple Values, just the first value will be Push to „onEditableSave“ Event.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issue because we got no response/example from you, if you still need help please provide us an example using our Online Editor.
