### ISSUE TITLE
last visited pageNumber (or) track pageNumber

### ISSUE THREAD

**Issue by hariannem** [wenzhixin/bootstrap-table#508]
How can i get the last visited pageNumber?
$table.bootstrapTable('selectPage',1). Here, instead of 1 , i want to pass the last visited page in the pagination. All i want is , How to track the pageNumber or how to  get the last visited pageNumber. Please help me out and this is my urgent requirement in the current project.

**Comment by djhvscf** [comment]
@hariannem  Well you can use a global variable for that.. maybe?? 

```javascript
//Get the options and there is the page number
var options = $table.bootstrapTable('getOptions');

//Get the page number
var pageNumber = options[pageNumber];;

//In your global variable set the pageNumber
var globalPageNumber = pageNumber;

```
Maybe something like that?

Here some examples: 
http://issues.wenzhixin.net.cn/bootstrap-table/methods/options.html

http://issues.wenzhixin.net.cn/bootstrap-table/#methods/selectPage-prevPage-nextPage.html

**Comment by hariannem** [comment]
@djhvscf  var pageNumber=options.pageNumber 
 This worked for me. Thanks a lot for your reply

**Comment by djhvscf** [comment]
@hariannem  Sounds great!
