### ISSUE TITLE
vue component table - select filter only populates on ONE table when using multiple tables on one page.

### ISSUE THREAD

**Issue by dathor-ghub** [wenzhixin/bootstrap-table#5087]
when using bootstrap-table vue component, the select filter only populates on ONE table when i have multiple tables one one page.

I have two separate tables located on one page. Both tables use select filters but only ONE table populates the select filters.  It is always the second table as declared in the html that gets populated.

example here -> https://live.bootstrap-table.com/code/dathor-ghub/3396

**Comment by ssayre** [comment]
I have experienced the same issue without using Vue.  The last table initialized gets the operable filter, regardless of the table order in the html.

The issue presents when using filterControl inline with a table, or using a filterControlContainer.  Only the last table initialized works.

**Comment by UtechtDustin** [comment]
@ssayre could you provide us an example (using our [editor](live.bootstrap-table.com/) ) ? :-)

**Comment by dathor-ghub** [comment]
I provided an example above. Or again here -> https://live.bootstrap-table.com/code/dathor-ghub/3834

**Comment by UtechtDustin** [comment]
@dathor-ghub sorry didnt saw it :D

**Comment by UtechtDustin** [comment]
Seems the bug is fixed in our develop branch, which means the next update will fix that issue.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3835
