### ISSUE TITLE
Change detailViewIcon to custom glyphicon

### ISSUE THREAD

**Issue by charliehewis** [wenzhixin/bootstrap-table#5088]
It would be useful to more easily choose to replace the plus/minus with, say, right chevron/down chevron or something else

In our project, we have a plus symbol on a button which leads to a page to add a record to the table. I need to use a workaround like ref #4967 at the moment, which could be made simpler by a formatter with usage like formatLoadingMessage.

**Comment by UtechtDustin** [comment]
Its already quite easey, just [overwrite the icons](https://bootstrap-table.com/docs/api/table-options/#icons).

Example: https://live.bootstrap-table.com/code/UtechtDustin/3370

**Comment by charliehewis** [comment]
Perfect, thankyou!
