### ISSUE TITLE
First column expands everytime table refreshes

### ISSUE THREAD

**Issue by iamthestreets** [wenzhixin/bootstrap-table#509]
Hi,

Every time the table refreshes the first column which is checkboxes expand a few pixels to the right.

This is how it looks before anything is refreshed:
![normalcolumn](https://cloud.githubusercontent.com/assets/8740821/6050687/b6e9fbdc-ac8f-11e4-9386-dde3ec97613b.png)
Here is how the table looks after a few refreshes:
![columnsize](https://cloud.githubusercontent.com/assets/8740821/6050666/86198838-ac8f-11e4-8973-e1ff24035097.png)

Why is it doing that and do you know how to fix it?

**Comment by djhvscf** [comment]
Do you have a JSFiddle or some code? @iamthestreets

**Comment by wenzhixin** [comment]
Please review the guidelines for contributing to this repo: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports, close this issue.
