### ISSUE TITLE
clickToSelect not working with Pagination

### ISSUE THREAD

**Issue by yanike** [wenzhixin/bootstrap-table#5092]
**Bootstraptable version(s) affected**:
I'm using 3.4.1

**Description**  
clickToSelect is not keeping the selected items when using pagination. It should keep them highlighted.

**Example**  
https://live.bootstrap-table.com/code/yanike/3422

**Comment by djhvscf** [comment]
You need to use [maintainMetaData](https://bootstrap-table.com/docs/api/table-options/#maintainmetadata)

Example here: https://live.bootstrap-table.com/code/djhvscf/3423

**Comment by yanike** [comment]
THANK YOU SO MUCH! Works amazing :)
