### ISSUE TITLE
Cookie extension still does not work with radio button custom filter controls

### ISSUE THREAD

**Issue by jdhenry08** [wenzhixin/bootstrap-table#5095]
See this previous issue: [https://github.com/wenzhixin/bootstrap-table/issues/5048](https://github.com/wenzhixin/bootstrap-table/issues/5048)

The cookie extension still doesn't work with custom filter controls if they are radio buttons. The filter is saved and loaded correctly, but the appropriate radio button is not selected:
[https://live.bootstrap-table.com/code/jdhenry08/3446](https://live.bootstrap-table.com/code/jdhenry08/3446)

**Comment by UtechtDustin** [comment]
The main issue here is that the filter-control dont support radio buttons.
As you can see, while loading all 3 radio buttons gets the same value.

@wenzhixin @djhvscf 
What do you think, should we support radio buttons or is this a edge case which can easily be implemented with the filterBy function ?

**Comment by jdhenry08** [comment]
Radio buttons are supported in the develop branch, are they not? See [https://github.com/wenzhixin/bootstrap-table/issues/5004](https://github.com/wenzhixin/bootstrap-table/issues/5004)

**Comment by UtechtDustin** [comment]
Your right, the problem of this issue is easy to fix.
Then we have to think about how we solve the issue with the values.
I will check that later after work!
