### ISSUE TITLE
The Fields in the option `Detail View`

### ISSUE THREAD

**Issue by typo3ua** [wenzhixin/bootstrap-table#5096]
I use the option `Detail View`
![Detail_View_Title](https://user-images.githubusercontent.com/638022/84790240-d0061b00-aff9-11ea-84eb-d471b1764996.png)
```
<table
  id="table"
  data-toggle="table"
  data-height="460"
  data-detail-view="true"
  data-detail-formatter="detailFormatter"
  data-url="json/data1.json">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
</table>

<script>
  function detailFormatter(index, row) {
    var html = []
    $.each(row, function (key, value) {
      html.push('<p><b>' + key + ':</b> ' + value + '</p>')
    })
    return html.join('')
  }
</script>
```
I want to see not the name of the field

**id**: 0
**name**: Item 0
**price**: $0
**amount**: 3

I want to see the title for this field, for example: 

**My title id**: 0
**My title name**: Item 0
**My title price**: $0
**My title amount**: 3

How in the frontend page to show not the `name` of the `field` and  only the `title` of the `field` into the option `Detail View`?

It is possible? 

If it is possible, that i can get example how is it do it?

Thanks!

**Comment by UtechtDustin** [comment]
You could do something like this: https://live.bootstrap-table.com/code/UtechtDustin/3463

**Comment by typo3ua** [comment]
Thanks! yeah really not bad but has one one but... the fields which not in the tag `<thead>...` do not have own 'title'
![d_v](https://user-images.githubusercontent.com/638022/84802903-e87e3180-b009-11ea-9334-dc608448e438.png)
What if i add only two fields in the tag `<thead>...` or one? I need something without but...

**Comment by UtechtDustin** [comment]
Like this: https://live.bootstrap-table.com/code/UtechtDustin/3464 ?

**Comment by typo3ua** [comment]
oh yeah,, it is that what i need.. you cool ... thank you so much.

**Comment by UtechtDustin** [comment]
No problem, your welcome :-)
