### ISSUE TITLE
onCheck/onUncheck events not working with methods

### ISSUE THREAD

**Issue by macias3** [wenzhixin/bootstrap-table#510]
Hi,
I've discovered some inconsistency.

Events 'onCheck' and 'onUncheck' are not firing when using method 'check' or 'uncheck'.
Events 'onCheckAll' and 'onUncheckAll' do their job when method 'checkAll' or 'uncheckAll' is called.

Take a look:
http://jsfiddle.net/L78kzfxs/2/

Thanks

**Comment by wenzhixin** [comment]
Merged, close this issue.
