### ISSUE TITLE
checkbox value for submiting form

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5107]
Hi

Is it possible to set for checkbox name like btSelectItem[] and set value for checkbox?
https://i.imgur.com/qL4TwPs.png

I need to submit form with selected rows.

Thanks a lot!

**Comment by UtechtDustin** [comment]
You can use the method `getAllSelctions` to get the data from the selected rows.
After that you can submit it.

Example: https://examples.bootstrap-table.com/#methods/get-all-selections.html

**Comment by urtvs** [comment]
@UtechtDustin ok! I think there was some way to create array field.
GetAllSelection will use!
Thanks a lot!

**Comment by UtechtDustin** [comment]
Your welcome ! :-)

**Comment by wenzhixin** [comment]
@urtvs @UtechtDustin 
https://live.bootstrap-table.com/code/wenzhixin/3535

**Comment by UtechtDustin** [comment]
@wenzhixin Didnt knew that we have that method 👍

**Comment by urtvs** [comment]
wow! super thanks!
