### ISSUE TITLE
$("#table").bootstrapTable('getSelections') with specific text

### ISSUE THREAD

**Issue by hebeto** [wenzhixin/bootstrap-table#5108]
Hi.
I need getSelections with specific texts. Something like ('getSelections').Where. Status == 'OK'.
It´s possible?

Thanks.

**Comment by UtechtDustin** [comment]
Use the `filter` method on the result from `getSelections`.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3537

**Comment by hebeto** [comment]
Work fine. Thanks
