### ISSUE TITLE
How did I change the loading?

### ISSUE THREAD

**Issue by marcelod** [wenzhixin/bootstrap-table#5110]
Hi,
It's not just changing the message but making a call to a created loading, for example, calling a helper.startLoading();

**Comment by UtechtDustin** [comment]
As you can see [here](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L2772-L2785) we currently call no functions, also we have no event for that.

As workaroun you could listen on the loading element (changes on the display css prop).

@wenzhixin @djhvscf 
What do you think, i think it could be a good feature to show custom spinner (overlays) on the whole table not just on the table itself.

**Comment by wenzhixin** [comment]
We can use `$table.bootstrapTable('showLoading')` to show the loading message.
https://examples.bootstrap-table.com/#methods/show-hide-loading.html
What do you mean like this? @marcelod

**Comment by UtechtDustin** [comment]
@wenzhixin 
He want to use a function which is called when the loading starts/ends.
To show a external spinner as example: https://ihatetomatoes.net/demos/css3-preloader-transition/

**Comment by marcelod** [comment]
@wenzhixin I need is what the @UtechtDustin  showed

**Comment by djhvscf** [comment]
My opinion is that we already have that functionality using showLoading / hideLoading. In the case this is needed then we can create a new option where we can define if the loading message overlays the whole table or it is inside the table.

**Comment by UtechtDustin** [comment]
@djhvscf I guess you understand it wrong..
He wants two options where he can define a methods (like the defailformatter).
The method of the first option e.g. `data-table-load-start`  will be called while the table start to load the data.
The second method of the second option e.g. `data-table-load-end` will be called while the table has loaded the data.

So he has show his own spinner/preloader or what ever he want to do while loading.

**Comment by marcelod** [comment]
Exactly what the @UtechtDustin said

**Comment by djhvscf** [comment]
Ok. Got it now. What about to listen the onprebody / onpostbody events?

**Comment by djhvscf** [comment]
What I mean is.. this is for me an edge case

**Comment by marcelod** [comment]
@djhvscf I understood what you said, but trying to use events didn't work

**Comment by djhvscf** [comment]
Why the events didn't work for you?

**Comment by wenzhixin** [comment]
A workaround: https://live.bootstrap-table.com/code/wenzhixin/3546

**Comment by marcelod** [comment]
Hi, this way it still doesn't start loading the way I need it, only on success.

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by marcelod** [comment]
It has not yet solved the problem, because the way it showed only makes an action on success and not on the call, I keep testing.

**Comment by marcelod** [comment]
I managed using ajaxOptions

`window.ajaxOptions = {
        beforeSend: function (xhr) {
            console.log('beforeSend')
            helper.startLoading();
        },
        complete: function () {
            console.log('complete')
            helper.stopLoading();
        }
    }`

**Comment by UtechtDustin** [comment]
Thanks for the solution.
