### ISSUE TITLE
Event onPostBody does not work

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5113]
Hi
I am creatin simple html table in page with attributes below. And make JS code.

I dont know why, but event onPostBody does not work and there is no errors in console.
If i write this code manualy in console it returns data
https://i.imgur.com/ShPJ67A.png

What can be wrong?
Thanks a lot

```
$('#tblMainData').on('onPostBody', function (d) {
  console.log('ok');
});
```

```
`class="table table-bordered table-responsive table-hover table-striped table-sm table-borderless"
		data-toggle="table"
		data-search="true"
		data-locale="ru-ru"
		data-show-columns="true"
		data-sortable="true"
		data-remember-order="true"
		data-click-to-select="true"
		data-show-columns-search="true"
		data-search-align="left"
		data-filter-control="true"
		data-show-search-clear-button="true"
		data-search-on-enter-key="true"`
```

**Comment by UtechtDustin** [comment]
Please provide us an example using our [online editor](https://live.bootstrap-table.com).

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/events/

To use event syntax:

```js
$('#table').bootstrapTable({
  onEventName: function (arg1, arg2, ...) {
    // ...
  }
})

$('#table').on('event-name.bs.table', function (e, arg1, arg2, ...) {
  // ...
})
```

**Comment by urtvs** [comment]
If my table creates from html (i did not call bootstrapTable) what syntax i need to use?
Because for example with checkbox it work like this
$('#tblMainData').on('check.bs.table', function (e, row) {});

So maybe i need in data attribute to tell bootstrapTable that i need to call event?
Thanks

**Comment by wenzhixin** [comment]
$('#tblMainData').on('post-body.bs.table', function (d) {
  console.log('ok');
})

**Comment by UtechtDustin** [comment]
@wenzhixin already told you how to use the events.
```
$('#table').on('EVENT-NAME.bs.table', function (e, arg1, arg2, ...) {
  // ...
})
```
which means you have to use `post-body.bs.table`.
