### ISSUE TITLE
Copy rows error

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5115]
Hi

When i make link to bootstrap-table-copy-rows.min.js immediatelly i get error

Why it happens? Thanks a lot!
https://i.imgur.com/OcJlnQC.png

`<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/copy-rows/bootstrap-table-copy-rows.min.js"></script>`

**Comment by UtechtDustin** [comment]
Please provide us an example using our [online editor](https://live.bootstrap-table.com).

**Comment by urtvs** [comment]
https://live.bootstrap-table.com/code/urtvs/3571

Done

**Comment by UtechtDustin** [comment]
Please add `data-field="state"` to your checkbox column, then its working fine.
Working example: https://live.bootstrap-table.com/code/UtechtDustin/3572

**Comment by urtvs** [comment]
@UtechtDustin i cant find in docs what does this data-field mean? 

PS: And can i ask here about JSON data loading - i have also problem, but when i add example and set up URL from external web source there is error with CORS.
How can i fix this error, because with this error i can create example on online editor.

Thanks!

**Comment by wenzhixin** [comment]
You can use the `data` option instead of `url`: https://live.bootstrap-table.com/example/welcomes/from-data.html
