### ISSUE TITLE
select2 inside cell

### ISSUE THREAD

**Issue by jamesRUS52** [wenzhixin/bootstrap-table#5116]
**Bootstraptable version(s) affected**:
1.16

**Description**  
Select2 component not initialyzed or not working at all inside cell 

**Example**  
https://live.bootstrap-table.com/code/jamesRUS52/3560

**Comment by wenzhixin** [comment]
You need to init the select after the `post-body` event:
* https://live.bootstrap-table.com/code/wenzhixin/3603
* https://live.bootstrap-table.com/example/options/row-attributes.html

**Comment by jamesRUS52** [comment]
Thank you
