### ISSUE TITLE
bootstrap-table-cookie doesn't work with data-filter-control="true"

### ISSUE THREAD

**Issue by 365dayes** [wenzhixin/bootstrap-table#5118]
**Bootstraptable version(s) affected**:

Bootstrap version 3.4.1
**Description**  

When enabling data-filter-control="true" the search cookie is removed with a hard refresh. The refresh button in toolbar keeps the search cookie. The local environment doesn't create two search boxes as seen in live editor. 

**Example**  

https://live.bootstrap-table.com/code/365dayes/3521

**Possible  (optional)**  

**Additional context**  

Also reported by another user here:
https://github.com/wenzhixin/bootstrap-table/issues/1840

**Comment by UtechtDustin** [comment]
After the commit [9aacb5dd](https://github.com/wenzhixin/bootstrap-table/commit/9aacb5dd) the bug exists.
The commit before works as expected.
I dont debugged it yet.

**Comment by UtechtDustin** [comment]
@djhvscf Could you check this, it was you commit and i currenty canf finde the cause of the issue.

**Comment by 365dayes** [comment]
Hey guys came across a random workaround, it seems setting an extremely long data-search-time-out will delay the cookie from being overwritten.

**Comment by djhvscf** [comment]
This is already fixed. https://live.bootstrap-table.com/code/djhvscf/5276

**Comment by bad-pooh** [comment]
A similar problem
The first time the page is loaded, cookies are not saved and the filter does not work until the first value is entered in the filter field and the page is reloaded.

Example:
https://live.bootstrap-table.com/code/bad-pooh/6991
