### ISSUE TITLE
I am looking for a working example - "Expand detail auto collapse other rows with detail view"

### ISSUE THREAD

**Issue by typo3ua** [wenzhixin/bootstrap-table#5119]
I have example which i use https://live.bootstrap-table.com/example/options/detail-view-icon.html - here i do test

I had read https://bootstrap-table.com/docs/api/events/#onexpandrow

I had saw it http://jsfiddle.net/wenyi/e3nk137y/18029/

all of it not helped me

I have that what i need http://jsfiddle.net/2Dj7Y/1582/ (the example not with `bootstrap-table`)

how are their put together?

thank you for advance

**Comment by UtechtDustin** [comment]
Something like this: https://live.bootstrap-table.com/code/UtechtDustin/3597 ?

**Comment by typo3ua** [comment]
yeah it is ... that is what i need... thank you so much.

**Comment by typo3ua** [comment]
I have problem.. when i click on the same row he is open but when i do it respite he is not opened...

For example click on the row two (he is opened)... click on the row two again (he is closed) ... click on the row two again (he already is not opening)

**Comment by UtechtDustin** [comment]
The Example above was just a way how you could do it, i dont tested it completly.
Just check if the current index is equal to the saved index (expandedRow), then ignore it.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3598

**Comment by typo3ua** [comment]
Yes, It does works. Thanks!
