### ISSUE TITLE
why i can't show BootstrapTable in partial view ?

### ISSUE THREAD

**Issue by handarueri** [wenzhixin/bootstrap-table#512]
hi i have a partial view that contain bootstrapTable, but when the partial view load in modal body, the bootstrap table cannot worked. This is the screenshot
![image](https://cloud.githubusercontent.com/assets/10350870/6058874/34155a88-ad5e-11e4-8430-451696fd6eb5.png)

this is my code
![image](https://cloud.githubusercontent.com/assets/10350870/6058880/4b328448-ad5e-11e4-8f6b-f4224a71da1d.png)

what's wrong in my code, in shown modal i just add the refresh tabel method and set the url , but it never called
![image](https://cloud.githubusercontent.com/assets/10350870/6058900/7283bdb4-ad5e-11e4-9f33-92234e5a93e2.png)

I hope anyone can help me. Thank you before

**Comment by djhvscf** [comment]
Maybe in F12 there are errors

**Comment by wenzhixin** [comment]
Can you provide jsFiddle @handarueri ?

**Comment by djhvscf** [comment]
Any update here??

**Comment by wenzhixin** [comment]
Added example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/modal-table.html
