### ISSUE TITLE
Cookie httpOnly

### ISSUE THREAD

**Issue by cgountanis** [wenzhixin/bootstrap-table#5121]
I see no way of setting the cookie to httpOnly to satisfy pen testing results.

**Comment by UtechtDustin** [comment]
Im not sure why this should be a bug or a problem ?
The `httpOnly` just disallow scripts(javascript) to read the cookie.
But the only use of the cookie is to write/read it on the client side with javascript.

Would you explain why you need httpOnly ?

**Comment by cgountanis** [comment]
Good point.
