### ISSUE TITLE
Input field size

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5123]
Hi
Is it possible to make input filter field with size as colum header?
Input element have got witdth 100% and on big screens make table to big
https://i.imgur.com/qHMKuii.png
https://i.imgur.com/b5i8EAX.gifv

**Comment by UtechtDustin** [comment]
The width of the inputs of the filter-control extension are always 100% of the column width.
If you want to change that you can easily change the width with css, just overwrite the class `bootstrap-table-filter-control-<COLUMN NAME>`.

Example: https://live.bootstrap-table.com/code/UtechtDustin/3840
