### ISSUE TITLE
Fixed Columns tables on Bootstrap tabs do not work without resizing window

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5124]
**Bootstraptable version(s) affected**: 
1.16.0

**Description**  
Fixed Columns tables on Bootstrap tabs do not work without resizing window.

As in the example shown I have a simple Bootstrap nav component with 3 tabs.
It uses the default Bootstrap JavaScript to navigate between the tabs bases on the data attributes (no custom js).

For the first active tab when the page loaded the fixed columns **do** work.
When you navigate to the second tab, for that table the fixed columns are **not** working.
However, when resizing the window then the fixed columns **do** kick in.

I especially use the fixed columns for mobile devices with limited horizontal space, but due to this the fixed columns do work work for the tabs unfortunately. Should I somehow refresh the table on change of tab as a workaround, and if so which method could I used best then?

**Example**  
https://live.bootstrap-table.com/code/marceloverdijk/3632

**Possible  (optional)**  
Maybe it's because the tables on the 2nd and 3th tab are not visible and therefore the fixed columns are not enabled?

**Additional context**  
MacOS, Chrome.

**Comment by wenzhixin** [comment]
You need to init the fixed column table after the tab is shown: https://live.bootstrap-table.com/code/wenzhixin/3873.
