### ISSUE TITLE
filters doesn't show in angular 9

### ISSUE THREAD

**Issue by FrancescoPaci** [wenzhixin/bootstrap-table#5125]
**Bootstraptable version(s) affected**:
1.16.0, but i tryed almost all version

**Description**  
i had import js e css file in angular json, but i can't see the select or input of filter
ex in js: 
dataTable = [{prioState: 1}, {prioState: 2}, {prioState: 3},
{prioState: 1}, {prioState: 2}, {prioState: 3}]
  ngOnInit() {
  $('#table').bootstrapTable({data: this.dataTable })
}
in html (i have to remove some < to show the html):
'table id="table"
             data-filter-control="true"
             data-pagination="true"
             data-page-size="2"
             data-page-list="[10, 20, 30, ALL]">
        thead>
            tr>
              th data-field="prioState" data-filter-control="input">prioState</th>
              th data-field="prioState" data-filter-control="select">prioState</th>
            </tr
        </thead
      </table'

i see the table with all features, but i can't see the filters

**Example**  
i don't have example because in the example box i can't put angular so i think is useless

**Possible  (optional)**  
in angular i import:
import 'bootstrap'
import 'bootstrap-table'

maybe i should import also the filter?

**Additional context**  
Angular 9

**Comment by UtechtDustin** [comment]
Correct, you have to import the `filter-control` extension also.
Something like `import '../../node_modules/bootstrap-table/dist/extensions/filter-control/bootstrap-table-filter-control.min.js'` (same for css :-) )
