### ISSUE TITLE
Is it possible to define individual rowspan's when using a table from data?

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5128]
This is probably an edge case but I thought let's check if it's possible.

When using Bootstrap-Table with content form data, like:

```
<table id="table">
  <thead>
    <tr>
      <th data-field="place">Place</th>
      <th data-field="address">Address</th>
      <th data-field="resident">Resident</th>
    </tr>
  </thead>
</table>

<script>
  var $table = $('#table')

  $(function() {
    var data = [
      {
        'place': 'Atlanta',
        'address': 'Street 1',
        'resident': 'Sarah'
      },
      {
        'place': 'Boston',
        'address': 'Street 1',
        'resident': 'Ben'
      },
      {
        'place': 'Boston',
        'address': 'Street 2',
        'resident': 'John Doe'
      },
      {
        'place': 'Boston',
        'address': 'Street 2',
        'resident': 'Jane Doe'
      }
    ]
    $table.bootstrapTable({data: data})
  })
</script>
``` 

I wonder if it's possible to set the `rowspan` on certain fields (which I will compute upfront).
So to only display once Atlanta and Boston for place name, and only once Street 2 for Boston.

I believe my best option is to use a table from HTML in this case, or are there other options?

Something like https://live.bootstrap-table.com/code/marceloverdijk/3645

**Comment by wenzhixin** [comment]
The `mergeCells` method can help you: https://live.bootstrap-table.com/code/wenzhixin/3874

**Comment by UtechtDustin** [comment]
@wenzhixin could be a workaround, but this should not be a solution.
Some tables have dynamic data, so mergeCells ist not that easy.
Also if there are a lot of row/colspan there are a lot of mergecells calls.
