### ISSUE TITLE
boostrap - table中嵌入select如何把select值跟当前行的值绑定，以及如何添加chang事件

### ISSUE THREAD

**Issue by ghostsatan** [wenzhixin/bootstrap-table#5130]
`
  	{
			field: 'auditStatus',
			title: '审核状态',
			align: "center",
			formatter: function (value, row, index) {
				var strHtml = "";
				if (value == 0) {
					strHtml = '<select id="select" disabled="true"><option value="0" selected="true" disabled="true">当前状态不可选</option></select>';
				} else {
					strHtml = "<select class='select'><option value='1'> 通过审核</option><option value='2'>未审核</option><option value='3'>审核未通过</option></select>";
				}
				return strHtml;
			}

		},
`

1.如何让当前每行数据的auditStatus 为不同值的时候 显示不同的对应状态

2.每行select 添加chang事件  触发并改变值

**Comment by wenzhixin** [comment]
看下文档和例子：
https://bootstrap-table.com/docs/api/column-options/#formatter
https://bootstrap-table.com/docs/api/column-options/#events

**Comment by UtechtDustin** [comment]
If you need more help with that, please comment :-)
