### ISSUE TITLE
Allow array filter

### ISSUE THREAD

**Issue by DiogoMarques29** [wenzhixin/bootstrap-table#5131]
Hello,

When we have a column cell data as a array, the filter control does not work. I believe it is only necessary to add ` || Array.isArray(value)` to this line:
https://github.com/wenzhixin/bootstrap-table/blob/7e1009930016c6b63e82c76ed608e4615562e254/src/extensions/filter-control/bootstrap-table-filter-control.js#L769

Cheers

**Comment by DiogoMarques29** [comment]
Example of json:
{"username":"1000","date":"2020-06-26","delegations":["Norte","Centro"],"groups":["Distribuidor"],"name":"Saber Moderno_3060_3070"}
Example of table:
<table
          id="active-users-list"
          data-toggle="table"
          data-url="{{ history_url }}"
          data-query-params="date={% now "Y-m-d" %}"
          data-pagination="true"
          data-page-list="[10, 20, 50, ALL]"
          data-response-handler="handleResponse"
          data-filter-control="true"
          data-icons="bootstrapTableIcons"
          data-click-to-select="true"
          data-maintain-selected="true"
      >
        <thead>
        <tr>
          <th data-field="username" data-filter-control="input">UserName</th>
          <th data-field="name" data-filter-control="input">Nome</th>
          <th data-field="groups">Perfis</th>
          <th
            data-field="delegations"
            data-filter-control="select"
          >
            Delegações
          </th>
          <th
            data-field="date"
            data-filter-control="datepicker"
            data-filter-datepicker-options='{
              "autoclose": true,
              "clearBtn": true,
              "todayHighlight": true,
              "language": "pt",
              "weekStart": 1,
              "format": "yyyy-mm-dd"
            }'.
          >
            Data
          </th>
          <th data-checkbox="true" data-sortable="true"></th>
        </tr>
        </thead>
        <tbody></tbody>
      </table>

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your idea, thanks!

**Comment by DiogoMarques29** [comment]
Example here:
https://live.bootstrap-table.com/code/DiogoMarques29/3684

**Comment by UtechtDustin** [comment]
Could you explain why do you need to use Arrays ?
Without its working fine, you just have to cast the arrays to strings.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3698

But i think its easy to implement and a good new feature.
