### ISSUE TITLE
在合并表头单元格时，不同行之间都有绑定过 field， field数据绑定逻辑错误

### ISSUE THREAD

**Issue by wuhao4399** [wenzhixin/bootstrap-table#5133]
当我使用以下options时，图表绑定数据乱序,绑定的field如下例:
例子中仅有标题为testX的列有绑定fieldX，其余标题为titleX的部分不绑定 field,
部分field绑定在第一行，部分在第二行，部分在第3行，此时数据展示时绑定的列错误。

例子：https://live.bootstrap-table.com/code/wuhao4399/3683

**Comment by wuhao4399** [comment]
The table is set as the above example, but the order of data columns is wrong.Is this a bug or does it not support the following settings?
Thanks a lot.

**Comment by UtechtDustin** [comment]
I think it's a bug, @wenzhixin @djhvscf could you check that also ?
I never used that before :)

**Comment by djhvscf** [comment]
The column distribution is right but how the data is displayed under those column is wrong. For me this is a bug
