### ISSUE TITLE
表格对不齐

### ISSUE THREAD

**Issue by newoul** [wenzhixin/bootstrap-table#5135]
**Description**  

表格对不齐
https://examples.bootstrap-table.com/#column-options/field.html
![image](https://user-images.githubusercontent.com/45955858/86121526-b8a25400-bb08-11ea-9024-3d0fe291c746.png)

**Comment by UtechtDustin** [comment]
Which setup do you use (browser, os, etc.), for me its working fine (Ubuntu, Firefox 77.0.1).

**Comment by UtechtDustin** [comment]
I close this issue because we got no response within 7 days from you, if the issue still exists please comment (and write your setup) and we will reopen the issue.

**Comment by newoul** [comment]
我用的Google（83.0.4103.106），当你设置很长的多表头或者浏览器窗体大小改变时会出现表格对不齐的情况，表格内容和表头完全偏移了

**Comment by wenzhixin** [comment]
假如你还有问题的话麻烦提供下在线例子。
