### ISSUE TITLE
Data attribute for sorting field

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5136]
Hi
In table i print value(datetime) in my own formating and sorting working not correct(because of formating)
I want in html set up data attribute for sorting value. Is it possible?

Thanks a lot.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by urtvs** [comment]
Colum 3
https://live.bootstrap-table.com/code/urtvs/3724

**Comment by wenzhixin** [comment]
The [sorter column option](https://bootstrap-table.com/docs/api/column-options/#sorter) can help you.

**Comment by urtvs** [comment]
So as i understan from source code example 
https://examples.bootstrap-table.com/#column-options/sorter.html#view-source
You recommend to write JS function for each colum?

Its not possible to set up data attribute with value for sorting? 
For example cell value i format as i need, and in data attribute for sorting i write timestamp time.
Is it possible to do like that?

**Comment by wenzhixin** [comment]
A working example: https://live.bootstrap-table.com/code/wenzhixin/3727

**Comment by urtvs** [comment]
Thank you very much! i undestand!

**Comment by urtvs** [comment]
As i see in code you use contact linking to table colum
3 - is thirt colum
if (rowA._3_data.datetime < rowB._3_data.datetime) return 1

When i am clicking on colum row is it possible to understand on what colum number i click?
https://i.imgur.com/xVRMCVa.png
I want to make universal sorting func
Thanks a lot

**Comment by UtechtDustin** [comment]
@urtvs no its not possible, why do you want to implement a unsiversal sorting function.
This is in the most cases a bad idea.
