### ISSUE TITLE
Set timeout for Data-Url 

### ISSUE THREAD

**Issue by neexs** [wenzhixin/bootstrap-table#5138]
**Description**  
Hi,

I want to know if there's a way to set the timeout when fetching data from url ? My request towards the "data-url" finishes abruptly although I know I can get data after the (default) 10 seconds ?

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/extensions/defer-url/   maybe help?

**Comment by neexs** [comment]
Thank you, it wasn't what I expected but it completely fit my needs.
