### ISSUE TITLE
Input search field size

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5139]
Hi
When field content is small and filter-control is activated input field makes cell much bigger then its content.
Is there any way to activate this input search field when for example pressed Search icon in toolbar?
I need search input fields on each colum, but default hidden. 
https://i.imgur.com/UTvKRxk.png
https://live.bootstrap-table.com/code/urtvs/3723

**Comment by UtechtDustin** [comment]
The next version (will be released in 1-2 day(s))  will have that feature.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3731

Added in #5065

**Comment by urtvs** [comment]
Sorry cant find in source code what attribute is for width in new version?
https://i.imgur.com/KnAZJpL.png

**Comment by UtechtDustin** [comment]
There is no width attribute, there is a new button which allows to show/hide the filter.
