### ISSUE TITLE
Toolbar does not support col-md-auto?

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5140]
Hi
I create table inside div with col-md-auto
Table fits for content
But header goes to 100% width of screen
Is it possible to set up toolbar width fits for table content size? Thanks a lot! 
https://i.imgur.com/ADzKgq7.png
https://live.bootstrap-table.com/code/urtvs/3726

**Comment by wenzhixin** [comment]
It does not support this feature now.
