### ISSUE TITLE
Is there any way to select data for table using "selector"

### ISSUE THREAD

**Issue by typo3ua** [wenzhixin/bootstrap-table#5141]
I need to select or change data in the `data-url`

`data-url="json/*.json">`

Is there any way to do it?

I did something... but what to do next I do not know.. I need your help

https://live.bootstrap-table.com/code/typo3ua/3748

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/3774

**Comment by typo3ua** [comment]
you are just magician... thank you so much
