### ISSUE TITLE
Custom search, search first few letters

### ISSUE THREAD

**Issue by Gamestarplayer41** [wenzhixin/bootstrap-table#5142]
**Description**  
I want to make a custom search, where column "foo" get searched. And the requirement is, that for example only the first 3 letters will be compared,

**Example (optional)**  
Search string = "Fooobar";

column data:
1. Fooobar
2. Foo
3. Fob

The first 3 letters compared-> result 1 and 2 displayed.

**Comment by UtechtDustin** [comment]
Next time it would help if you show a example what do you already tried.
It should quite easy to implement when you read the documentation about the custom search (there is also a example).

Example for your usecase: https://live.bootstrap-table.com/code/UtechtDustin/3775

**Comment by Gamestarplayer41** [comment]
@UtechtDustin Thanks! I was really confused by the example because of the use of Index etc.
