### ISSUE TITLE
How add array of images (Flat Json) into `data detail formatter`?

### ISSUE THREAD

**Issue by typo3ua** [wenzhixin/bootstrap-table#5143]
I need to add images into `detail formatter` but i do not know, how  to do it.

І created my example here https://live.bootstrap-table.com/code/typo3ua/3780

I know that i can to add `+ row.images[1] +`  but I need to add formatted array something like  `<img src="' + row.images[...all images...] + '" alt="image">` if image is there...

I need your help...

thank you for advance

**Comment by UtechtDustin** [comment]
> but I need to add formatted array something like <img src="' + row.images[...all images...] + '" alt="image"> if image is there...
Im not sure what do you mean with that.

If you try to display all images in the array, then just use a for each on `row.images` and build(+append) the img tags.

**Comment by typo3ua** [comment]
Thank you for reply...
now I can to display images as each separately
```
<img src=" + row.images[1] + " alt="image">
<img src=" + row.images[2] + " alt="image">
<img src=" + row.images[3] + " alt="image">
```
when i to add just 
```
<img src=" + row.images + " alt="image">
```
I get nothing 

I just see only  `[object Object]`

**Comment by UtechtDustin** [comment]
row.images is an object so it makes sense that you get `[object Object]`, you cant convert a object to a string.
That is the reason why i said you should use a for each e.g. https://live.bootstrap-table.com/code/UtechtDustin/3781

**Comment by typo3ua** [comment]
Yes it is already better but  I get problem if images is not existing
![image_detail](https://user-images.githubusercontent.com/638022/86534236-88c7c780-bedf-11ea-9c78-773b050fcb2e.png)
as in your example so as and in my example
![image_detail_0](https://user-images.githubusercontent.com/638022/86534305-1b686680-bee0-11ea-9cc9-1db89a98b415.png)

**Comment by UtechtDustin** [comment]
This was just a example..

If you need help then please describe exactly what you need and what you tried.

The issues above are simple to solve, just replace the images which not exists with the urls which i added on the first row...
for the rows without images you just have to check if there are images or not, if there are image use my example and if there are no images skip the image part..

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/3783

**Comment by typo3ua** [comment]
If images exists then there need to add if not exists then do not add? for example

**If images not exists** 
```
 '<p><strong>ID</strong>: ' + row.id + '</p>',
 '<p><strong>Name</strong>: ' + row.name + '</p>',
 '<p><strong>Price</strong>: ' + row.price + '</p>',

### Add images after this line... ###

 '<hr>',
 '<span class="row">',
    '<span class="col"><img src="' + row.images[all] + '" alt="image"></span>',
 '</span>',
```
**If images exists** 
```
 '<p><strong>ID</strong>: ' + row.id + '</p>',
 '<p><strong>Name</strong>: ' + row.name + '</p>',
 '<p><strong>Price</strong>: ' + row.price + '</p>',
```

**Comment by typo3ua** [comment]
yes it іs already closer .. but ,,, If images not exists .... blank tags remain
![image_detail_1](https://user-images.githubusercontent.com/638022/86534642-8dda4600-bee2-11ea-9155-684047634617.png)

**Comment by wenzhixin** [comment]
https://live.bootstrap-table.com/code/wenzhixin/3784

**Comment by UtechtDustin** [comment]
@typo3ua 
Maybe you should read the basiscs of html and javascript, before you try to use libraries.
This is no issue of the bootstrap-table, the problems which appears are easy to fix (as i already told).
Just use a if and if there are no images in the data dont append the images AND the <hr> tag to the html.

**Comment by typo3ua** [comment]
Yes I know ... you are right i do not have deep knowledge in JS ...but I thank all so much
