### ISSUE TITLE
Detail Formatter for Table From HTML

### ISSUE THREAD

**Issue by typo3ua** [wenzhixin/bootstrap-table#5144]
I created an example https://live.bootstrap-table.com/code/typo3ua/3785

I see data which do not exists in table

```
_id: undefined
_class: undefined
_data: [object Object]
id: ID 1
_id_id: undefined
_id_class: undefined
_id_rowspan: undefined
_id_colspan: undefined
_id_title: undefined
_id_data: [object Object]
```
Why is not only?

`id: ID 1`

I do not understand, what is I missed?

**Comment by djhvscf** [comment]
The data with a underscore prefix is for internal purposes. Definitly this is a bug since this should be included when passing the data to the events.

What do you think @wenzhixin @UtechtDustin ?

**Comment by wenzhixin** [comment]
I don't think it's a bug. The underscore prefix variable is used to store some additional data, such as `id`, `class`, or `data-*` attributes, if not used, it can be ignored.

![image](https://user-images.githubusercontent.com/2117018/86550045-e86fb280-bf73-11ea-8f0e-aa78c5fb3ca7.png)

https://live.bootstrap-table.com/code/wenzhixin/3786
Another example: https://examples.bootstrap-table.com/#welcomes/from-html.html

**Comment by typo3ua** [comment]
I tried and with ...
```
    <tr id="tr-id-1" class="tr-class-1">
      <td id="td-id-1" class="td-class-1">ID 1</td>
      <td>Item Name 1</td>
      <td>Item Price 1</td>
      <td>Item Amount 1</td>
    </tr>
```
...without change.

I see you added the condition `if (!key.startsWith('_')) {...`

I think that then needs to write about it in the documentation... if it is not bug

**Comment by UtechtDustin** [comment]
As @djhvscf already wrote the attributes which starts with a underscore (`_`) are internal attributes.
Sometimes it makes sense to use them on external code. I dont think it makes sense to documentate edge cases (this would also flood our documentation).
