### ISSUE TITLE
Woud it be possible to use a function for the data-search-formatter?

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5146]
My use case is that I have a bootstrap-tables based on javascript array.
This javascript array contains a date of birth and a date of death like this example: https://live.bootstrap-table.com/code/marceloverdijk/3794

If the person is deceased a dagger is displayed behind the age.
But the filter control is broken, and the searching does not seem to work.

Would it be possible to define a data-search-function to return per row a value to compare the search with?

**Comment by UtechtDustin** [comment]
@djhvscf Any news here ?

**Comment by djhvscf** [comment]
No news, but this is under my radar.

**Comment by typo3ua** [comment]
... is will be good feature I hope it is will be released

**Comment by driehle** [comment]
If you look at #4991 this seems to be a but and not a feature request!

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9694

**Comment by typo3ua** [comment]
Thank you a lot...

**Comment by redtide** [comment]
> Example with fix: https://live.bootstrap-table.com/code/djhvscf/9694

Probably unrelated to this issue but I tried to update to 1.21.2 from 1.20.2 and my "jsonless" table data is not working anymore in a column with links and the above example seems not working anymore neither.
