### ISSUE TITLE
your official website failed to load jquery

### ISSUE THREAD

**Issue by Arryboom** [wenzhixin/bootstrap-table#5147]
Hi I think the jquery js resource on your official site is broken,make the documention and example on your website isn't avaiable. 

sample like https://www.bootstrap-table.com.cn/examples/methods/refresh/

got error below in both chrome and firefox console
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
hm.baidu.com/hm.js?4495d730792efb25485d2aeab057e7f3:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
11.0.1.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
zz.bdstatic.com/linksubmit/push.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
jquery-3.3.1.min.js:1 Failed to load resource: net::ERR_CONNECTION_CLOSED
util.js:55 Uncaught TypeError: Cannot read property 'fn' of undefined
    at util.js:55
    at bootstrap.min.js:6
    at bootstrap.min.js:6
template.js?v=VERSION:163 Uncaught ReferenceError: $ is not defined
    at template.js?v=VERSION:163
```

**Description**

**Comment by UtechtDustin** [comment]
As written in the error message it seems a browser plugin blocks jquery `ERR_BLOCKED_BY_CLIENT`.
It works fine for me :-)

**Comment by Arryboom** [comment]
> As written in the error message it seems a browser plugin blocks jquery `ERR_BLOCKED_BY_CLIENT`.
> It works fine for me :-)

if so my situation it's blocked by both firefox and chrome default settings,seems like some cors policy related problem

**Comment by UtechtDustin** [comment]
For me its working fine with default setting.
Is this site also dont work for you: https://bootstrap-table.com/docs/getting-started/introduction/?

**Comment by Arryboom** [comment]
> For me its working fine with default settings (Firefox).
> Is this site also dont work for you: https://bootstrap-table.com/docs/getting-started/introduction/?
> 
> Edit: I think the chinese version is also not up2date.

hi thanks,bootstrap-table.com didn't show this issue gonna using .com site now,chinese site still broken

**Comment by UtechtDustin** [comment]
@wenzhixin
