### ISSUE TITLE
Add own buttons to toolbar

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5149]
Hi
What i right way to add my own buttons to toolbar header?
https://i.imgur.com/P2CYD97.png
Now i am doing it i think not a proper way(
$('#tblMainData-div>.bootstrap-table>.fixed-table-toolbar').append('MY button');

**Comment by UtechtDustin** [comment]
You can use the [toolbar](https://bootstrap-table.com/docs/api/table-options/#toolbar) option :-)

Example: https://live.bootstrap-table.com/example/options/custom-toolbar.html

**Comment by urtvs** [comment]
Thanks a lot! Wonderful!
