### ISSUE TITLE
sorting fails on big figures/numbers

### ISSUE THREAD

**Issue by c-pohl** [wenzhixin/bootstrap-table#515]
Hello Folks,

I am facing a big issue using this great plugin.
Whenever I try to sort a column by a given ID (order_id) the sorting fails, maybe because of the big numbers.

Take a closer look at the figures/numbers, the sorting is wrong.
*252161* should follow *111111111262*, following *95331* …

Example on jsfiddle:
http://jsfiddle.net/e3nk137y/554/

**Comment by babbomaria** [comment]
Under JSFIDDLE you obtain an ALPHABETICAL order if you need NATURAL sorting you need another algo, or some trick  with 0 char
   
http://stackoverflow.com/questions/5167928/what-is-natural-ordering-when-we-talk-about-sorting
http://blog.codinghorror.com/sorting-for-humans-natural-sort-order/

A tool for test

http://textmechanic.com/Sort-Text-Lines.html

**Comment by c-pohl** [comment]
Thank you very much, **Natural Sorting** did the trick!

I used the following JS:
```javascript
function alphanum(a, b) {
  function chunkify(t) {
    var tz = [], x = 0, y = -1, n = 0, i, j;

    while (i = (j = t.charAt(x++)).charCodeAt(0)) {
      var m = (i == 46 || (i >=48 && i <= 57));
      if (m !== n) {
        tz[++y] = "";
        n = m;
      }
      tz[y] += j;
    }
    return tz;
  }

  var aa = chunkify(a);
  var bb = chunkify(b);

  for (x = 0; aa[x] && bb[x]; x++) {
    if (aa[x] !== bb[x]) {
      var c = Number(aa[x]), d = Number(bb[x]);
      if (c == aa[x] && d == bb[x]) {
        return c - d;
      } else return (aa[x] > bb[x]) ? 1 : -1;
    }
  }
  return aa.length - bb.length;
}
```
