### ISSUE TITLE
Accent Neutralise dont working with Filter Columns

### ISSUE THREAD

**Issue by alaintm79** [wenzhixin/bootstrap-table#5158]
**Bootstraptable version(s) affected**: 1.16 - 1.17.0

**Description**  
Sorry for my English. The Accent Neutralize plugin when active does not allow filtering by columns with the filter columns plugin.

Regards

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by alaintm79** [comment]
https://live.bootstrap-table.com/code/alaintm79/3872

**Comment by ME-at-GH** [comment]
I have the same issue and can confirm accent neutral is blocking filter control to do its job

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf lets consider to remove the neutralise accent extension and implement it as core feature.
Its a quite small extension which can be rewritten, we can use the function `localeCompare` instead of replacing all chars.

Example: 
```
var accent = 'José';
console.log('Jose', accent.localeCompare('Jose'), 'returns 1');
console.log('Josea', accent.localeCompare('Josea'), 'returns 1');
```

**Comment by djhvscf** [comment]
If the extension is a overkill, we can remove it.

**Comment by UtechtDustin** [comment]
In my opinion its a overkill, as we just need `localeCompare` and some if statements to check if accent neutralise is enabled.

**Comment by wenzhixin** [comment]
I agree with you @UtechtDustin

**Comment by francogp** [comment]
it does not work anymore in core.

**Comment by UtechtDustin** [comment]
@francogp it's working fine..
1.20.2: https://live.bootstrap-table.com/example/options/search-accent-neutralise.html
Dev-Branch: https://live.bootstrap-table.com/code/UtechtDustin/12097
