### ISSUE TITLE
Loading message doesn't hide unless data-url is used

### ISSUE THREAD

**Issue by atroxmavenia** [wenzhixin/bootstrap-table#516]
When using the examples from the docs, it always shows "Loading, please wait...". The data loads correctly and the table displays properly, other than this message not going away.

**Comment by mwaldron74** [comment]
I am having the same problem, had to add "data-url='x'" as a temporary fix.

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle?

**Comment by thiagof** [comment]
seems to be missing css file..

my problem was in production build

**Comment by wenzhixin** [comment]
Maybe you missing css file just like @thiagof said. There is no problem in these examples: http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-html.html and http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-data.html

**Comment by fippu82** [comment]
Had the same problem. This helped me! It was bootstrap-table.css missing to include. Thank you

**Comment by b62303411** [comment]
have the same issue and the css is well loaded
<link rel="stylesheet"
			href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script
			src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script
			src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
		<script
			src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.js"></script>

**Comment by adamgis2000** [comment]
Same issues still! I have downloaded the min files and still does not work!

**Comment by R3tr0Lif3** [comment]
add;   data-url="#myTable" and ok

**Comment by joicy** [comment]
Same issue. I have tried everything all of you said here and the problem persists. If I inspect the code the data is there, but the load message doesn't disappear


![image](https://user-images.githubusercontent.com/3669784/93539576-98c04680-f927-11ea-8cc6-a5e55ddb2630.png)

**Comment by djhvscf** [comment]
This is probably a CSS issue. Please make sure your importing the CSS file and it is in the correct order

**Comment by eliteprox** [comment]
Ultimately was missing `bootstrap-table.min.css`
