### ISSUE TITLE
Dropdown does not work with Bootstrap v5

### ISSUE THREAD

**Issue by ME-at-GH** [wenzhixin/bootstrap-table#5161]
Hi guys, I want to say that the dropdown buttons are not working on Bootstrap v5.
Dropdown buttons like rows per page and Export list.

**Comment by UtechtDustin** [comment]
Works fine for me on my locale machine, could provide us an example ?

@wenzhixin the Editor has issues with the getTemplate method while using bootstrap5

**Comment by ME-at-GH** [comment]
Yeah are totally right man, rechecked scripts in the html header, one script caused an issue for the drop downs. I had checked, but not good enough, my mistake.

**Comment by wenzhixin** [comment]
> the Editor has issues with the getTemplate method while using bootstrap5

@UtechtDustin Fixed
