### ISSUE TITLE
data-width works not properly?

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5166]
Hi

Here is example
https://live.bootstrap-table.com/code/urtvs/3900

I am trying to make narrow 1-colum but its big. 
data-width="50" - why this option not make col 1 with width 50px?
Thanks

**Comment by UtechtDustin** [comment]
The problem are the classes `table-responsive` and `table-sm`.
Exameple without this classes: https://live.bootstrap-table.com/code/UtechtDustin/3904

**Comment by djhvscf** [comment]
If you need any extra help, please reopen this issue

**Comment by urtvs** [comment]
Thanks a lot!

**Comment by urtvs** [comment]
What you recommend to do with long content with not spaces if its bigger then size of colum
You see table bigger than i need: https://i.imgur.com/h2dQKYF.png
