### ISSUE TITLE
get the ID of the "hosting" element

### ISSUE THREAD

**Issue by snoopy72** [wenzhixin/bootstrap-table#5167]
I tried to find an answer with searching in the docs and here - without solution.

I would like to read the ID or name of the table-hosting html element.

`<table id="tbl-test" class="table table-striped"></table>`

called with:

`$("#tbl-test").bootstrapTable({ ...`

how can i get the name "tbl-test" in the table events ?

Edit: I really need the way from INSIDE the event fct, not the "$("#tbl-test")" way.

**Comment by UtechtDustin** [comment]
You can e.g. get the target of the event and then get the id.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3911

If that dont work for your event, then please create us an example using our [editor](https://live.bootstrap-table.com)

**Comment by snoopy72** [comment]
Hello Dustin,

thanks for your quick and helpful reply. hopefully not unpolite, i changed your example to my request:

https://live.bootstrap-table.com/code/snoopy72/3912

it's inside the "onPageChange" event.

`<table id="table111">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
</table>

<script>
  var $table = $('#table111');

  $(function() {
    var data = [
      {
        'id': 0,
        'name': 'Item 0',
        'price': '$0'
      },
      {
        'id': 1,
        'name': 'Item 1',
        'price': '$1'
      },
      {
        'id': 2,
        'name': 'Item 2',
        'price': '$2'
      },
      {
        'id': 3,
        'name': 'Item 3',
        'price': '$3'
      },
      {
        'id': 4,
        'name': 'Item 4',
        'price': '$4'
      },
      {
        'id': 5,
        'name': 'Item 5',
        'price': '$5'
      }
    ];
    $table.bootstrapTable({
      data: data, 
      pageSize: 2, 
      pagination: true, 
      onPageChange: function(number,size) {
        // here i need the id "table111", pls
      }
    });
  })
  
</script>`

**Comment by UtechtDustin** [comment]
It seems there are only the two paramters as you already found out.
But if you listen on the event outsite of the bootstrap-table options, you also can get the target.
Example: https://live.bootstrap-table.com/code/UtechtDustin/3913

@wenzhixin @djhvscf 
I think we should update our events to provide more informations, as example we could add the table as last parameter to each event. (Just a quick idea, we should think about that)

**Comment by wenzhixin** [comment]
@snoopy72 It's easy to solve this: https://live.bootstrap-table.com/code/wenzhixin/3914.
@UtechtDustin I think it's unnecessary to add an event parameter.

**Comment by djhvscf** [comment]
I also think it is not necessary to add a new event parameter. 

When the event is fired you have access to `this` which is the bootstrap-table object itself that contains all the configuration of the table.

What I think is that `this` should include the html object information in order to access more easily to it, for example:

`this.$container` or `this.$el` or `this.$body`

See https://live.bootstrap-table.com/code/djhvscf/3915

**Comment by snoopy72** [comment]
Hello,

thanks for all the infos, but the example of @wenzhixin is no solution.
using the trick with "mass creation" is not the way i use it (or i could use it).

in my app the event is defined in a central definition of the locales, incl. formatLoadingMessage etc.

if i change the example to my requirements, it's again not working:
`$('table').each(function () {
      $(this).bootstrapTable({
        data: data, 
        pageSize: 2, 
        pagination: true, 
        onPageChange: function(number,size) {
          alert($(this).attr('id'))
        }
      });
    })`

@UtechtDustin @djhvscf
i agree with your idea to add some more details to the events. most other components i use have methods like "getId" or "getName" etc. i miss helpful methods like these in the bootstrap-table. even if there might be a workaround or complex solution ... as you see, it's not easy to use (find) and so breaks the delevopment process. your component is good - add some helpful fetures and make it perfect.

**Comment by snoopy72** [comment]
After a lot of searching i found a solution (in german):
[https://www.yourhelpcenter.de/2020/07/bootstraptable-hauptelement-im-event-erhalten/](url)

It's also understandable for non-germans, because the example shows the trigger expansion.
obviously there is a need for those helpful functions in bootstrap-table.

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf 
As we all know this has often a weired scope in javascript, which means we dont always have `this` as solution.

**Comment by djhvscf** [comment]
Mark this as feature because it is important to provide the correct context. Thanks @snoopy72
