### ISSUE TITLE
Using select on an editable table

### ISSUE THREAD

**Issue by Bengreen** [wenzhixin/bootstrap-table#517]
I was trying to use the select type for a  table to make it editable.

the column i want to edit stores an integer that is used to reference an item in another table. i.e. the other table is two columns (1 with integers one with text fields).

i want to use the text elements to choose which item i want to select in my table.
The editing works fine and after i change a value it works fine..... BUT when the table first loads it does not work, it shows the integer number not the text equivalent.

I setup a test without tables and found that the best way is to set the variable data-value for the <a> (anchor) element.
BUT in the editable implementation the value is provided by placing the data between the open and close of the anchor elements (which unfortunately does not work of the initialisation).

I made the following change to the file: bootstrap-table-editable.js

                return ['<a href="javascript:void(0)"',
                    ' data-name="' + column.field + '"',
                    ' data-pk="' + row[that.options.idField] + '"',
                    ' data-value="' + result + '"',
                    '>'  + '</a>'

Which now seems to give the correct result. Can you consider this as a potential update?

PS. i find the table VERY good and appreciate your work. Combined with editable this is a great solution.

**Comment by wenzhixin** [comment]
pull requests are welcome:)

**Comment by Bengreen** [comment]
i have created as a pull request. Sorry this is the first time i have done a pull request so if you have any comments that i need to change things or modify the pull request then please let me know.

**Comment by thibaultvanc** [comment]
Hello there
Wanted to use a select type during hours.
I saw the exemple for textarea on the page http://bootstrap-table.wenzhixin.net.cn/extensions/

My question is : 
how to pass the data to populate the select ?

**Comment by wenzhixin** [comment]
#626 , close this issue.
