### ISSUE TITLE
Compact view for mobile devices

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5173]
Hi!
Is there any way to set up compacked view for mobile phones?
https://i.imgur.com/vvG9wUk.png
I think it can be more pretty if
1 - size of text on mobile phones will be smaller
2 - margin between colums will be smaller

Meybe there is some trick or theme to make more compack on mobile devices?
Thanks a lot!

**Comment by UtechtDustin** [comment]
You can use the [mobile extension](https://bootstrap-table.com/docs/extensions/mobile/).

**Comment by UtechtDustin** [comment]
If you need more help, just ask/comment here :-)
