### ISSUE TITLE
add an own event to bootstrap-table

### ISSUE THREAD

**Issue by snoopy72** [wenzhixin/bootstrap-table#5174]
Hello,

i would like to add an own (new) event to the bootstrap-table:.

it should be namend "onCreated" and should be triggered right before the "initserver" call.

therefor i added the declaration:

```
onCreated: function onCreated(element) {
   return false;
},
```
f.eg right below the "onClickRow: function onClickRow(item, $element) {" line

And i added the following line to the EVENTS var:
`'created.bs.table' : 'onCreated',`

Finally i tried to trigger my new event (without success):
```
_createClass(BootstrapTable, [{
	    key: "init",
	    value: function init() {
	      this.initConstants();
	      this.initLocale();
	      this.initContainer();
	      this.initTable();
	      this.initHeader();
	      this.initData();
	      this.initHiddenRows();
	      this.initToolbar();
	      this.initPagination();
	      this.initBody();
	      this.initSearchText();
              
              console.log("trigger 1");
              this.trigger('created', this.$el);
              
	      this.initServer();
	    }
	  },
```

The "trigger 1" info is displayed in the console, but my event "catcher" is not reacting.
i declared the event catcher in my JS code:
```
onCreated: function(element) {
            console.log("created !!!");
            console.log(element);
        }
```

What is missing or what am i doing wrong, pls ?

**Comment by UtechtDustin** [comment]
First of all the question: Why do you cant use the existing event(s) ?
What do you try to archieve ?

Also you try to add the event to the dist file, which makes it harder, use the src file(s) and build the project.

**Comment by snoopy72** [comment]
Hello,

because there is not matching event. I am using a lot of tables in my application and they are created in a lot of view. Due to this i created a central handler, which defined the "formatLoadingMessage", "formatShowingRows", etc. and reacts on all events like "onPageChange".

Because those central handler should change some settings of tables individually, i must set some options after the creating, but before the server init / request. Those are f.eg options like PageNumber, pageSize etc.

I will not build the project, because it will cost too much time and i need to create extra development environments for those small changes (in comparison to my main app). i have a "ganeral problem" (sound too big, but hopefully you understand what i mean) with bootstrap-table, because there are way too less events, paramters and details for developers (pls note my last ticket #5167 with the "get name problem"). i have my focus on my app (of course) and paying too much time into building or debugging other components is not effective. In this case i am only doing this, because the bootstrap-tables are used very often and it would be even more time consumpting to replace the component.

**Comment by UtechtDustin** [comment]
So why you can use the [postBody](https://bootstrap-table.com/docs/api/events/#onpostbody) event ?
Its triggered when the table is rendered and befor the `initServer`.

Until now we never got the feedback that we have to less events, after the issue #5167 is implement you will have the table object in each event.

**Comment by snoopy72** [comment]
You are quick in responsing ;o)
Thank you very much. It's a pleasure to have a qualified communication nearly in realtime.

I will check postBody again and write back asap after the check.

**Comment by snoopy72** [comment]
I rechecked the postBody Event and it seems to work if i check against data.length == 0.
So i can detect, weather i am before or after the data processing.

> So i guess there are enough options.

Pls note, that it make a component MUCH more easier to implement, if i have easy to use and predefined events and handlers. For bigger projects and apps it's one of the biggest decision points not to spend time into a component / plugin. I use components (comparable to BT) with nearly 100 events ... which make it easy like nothing to react to control the components as my users requires it. Of course (as seen in this example) there are solutions, but the documentation is very short and not clear enough. On my 1st test i only saw the event with all those data (which matched to my interpretation of the docs) and so i cancelled that option.

**Comment by snoopy72** [comment]
Closed because the idea of @UtechtDustin solved my problem.

**Comment by UtechtDustin** [comment]
What do you think which events should we add ?
Until now nobody told us that we have to less events, if you check the documentation you will also get some ways to solve it ( e.g. postBody event or replacing the ajax call).

We try our best, but you cant forgot we are a small team which will not payed for this project.
If you want to help us, feel free to submit a pullrequest for the core code or for the documentation.
Also ideas for (usefull) events could help, we will check if that events make sense (if yes we will add them).

**Comment by snoopy72** [comment]
Hello Dustin,

pls do not misunderstand me, i am not angry or nerved by you or the component !

It's just a central decision point for a lot of developers of big software. I am for 30+ years developing now and i watch more and more senior developers deciding exactly on those criteria. Not because there might be other ways to solve the problem - just because it's easier to develop a main app (in which your "main project" is only a component). Currently i use nearly 30 plugins and i i would like to find the special way for each plugin to adapt the component to my (better my customers) requirements, i would not be able to work efficiently. Due to this a lot of available events, methods and options makes components more attractive and a lot easier to handle. That's only my two cents ...

I would like to join your team and help. I founded a lot of projects and app the last years (30+ *smile*) and i see a problem in most smaller project founded by one person. Here it was "wenzhixin" i think. In most cases there is too much discussion about features and what-to-do ... quite often those discussions exceeds the required time for implementing or solving the problem. If you take a look into my last ticket, wenzhixin quickly replied: "not required". Those founders (of course) lost their heart to "their" project and that blocks the process. 

Again: I am absolutly not irritaed. You deliver a fabulous component which is used heavly in my app !

I simply see (due to my experience and job position) the propects of your component better with more features (see above)

**Comment by UtechtDustin** [comment]
> Those founders (of course) lost their heart to "their" project and that blocks the process.

I dont think wenzhixin lost "their heart" for the bootstrap-table.
The thing is, we as develop of the component sometimes also sometimes dont see all posible situations, are stuck or have a blockade.
That is the reason why it is great that there are three core developers on that project, if someone of us is stuck, have a blockade or some other stuff a other core develop can help.

The main thing on your request is that your event handling was quite easy to handle with the existing event, that is the reason why i currently dont think we need more events.
I also work as web develop for a few years and i also have to read documentations and have to think like "how could i implement it on this plugin". I mean, sure sometimes you spend some minutes to figure out how to implement something on a plugin but the plugin itself saves a lot of time!

If you have (usefull) events tell them to us, but we should not "flood" the plugin with events for edge cases".

**Comment by snoopy72** [comment]
That you are an experienced developer is clearly visible in your qualified responses.

Take this ticket f.eg. - of course there is a way (which i did not see during my first test and reading the docs). the PostBody event is able to solve my problem ... but not in the easiest way. this event is triggered twice during the component creation, which forces me into extra condition-checks (like "are there data or not". also the "prebody" event is fired twice (which makes sense). 

In my case it would be much easier to have one "oncreated" event, which is once triggered if the component is created and ready (just before requesting data).

My app has several hundrets of events and methods for other developers. sounds a lot (and it is) but allows each developer (customer) do request and read exactly what they needs within seconds and without any further reading and testing. I have more than 500 BT tables usages in my views (of course not in one view ;) ) - and so i reorganized those process to allow a much more efficient way to control them (for me).

Thanks for your support and qualified feedback !

**Comment by UtechtDustin** [comment]
>  but not in the easiest way. this event is triggered twice during the component creation, which forces me into extra condition-checks (like "are there data or not". also the "prebody" event is fired twice (which makes sense).
> In my case it would be much easier to have one "oncreated" event, which is once triggered if the component is created and ready (just before requesting data).

The problem is that the bootstrap-table is grown historically which means there are some parts which are not perfect.
For a lot of reasons the bootstrap-table will be rerendered which means the events will be triggerd twice (which also means if we implement new events this would be also called twice).

The reason why we dont fix that yet, is that this would be require a LOT of time, because we have to rewrite a lot of the plugin.
There is btw. already a issue about that what i described above.

Currently our priority is to fix bugs and optimize the table, as soon we have time we will try to optimize/implement also the time intensive issues. I think we are on a good way, some months ago we had more then 200  open issues which are down to 38 right now.
