### ISSUE TITLE
How to use 'filterby' with nested fields?

### ISSUE THREAD

**Issue by joicy** [wenzhixin/bootstrap-table#5180]
**Description**  
Hello everyone! 
I'm trying to create a multiple columns filter and some of these columns have a child on JSON data. I have created a dictionary to manage each column but didn't work when I have dots on the field. Do you have any idea how I can do this?

**Example**  
Check a small example of this: https://live.bootstrap-table.com/code/joicy/3991
The problem is in the _Name_ field.

**Comment by UtechtDustin** [comment]
You can write a custom filter algorithm, which is documentated on our [documentation](https://bootstrap-table.com/docs/api/methods/#filterby).
This would also mean you have to filter the other columns in that funciton!
Example: https://live.bootstrap-table.com/code/UtechtDustin/3996

The easier, faster and less code (you dont need your event listener etc.) way is to use our [filter-control extension](https://bootstrap-table.com/docs/extensions/filter-control/). If you need the filter outsite of the table you can user [filterControlContainer](https://bootstrap-table.com/docs/extensions/filter-control/#filtercontrolcontainer)
https://live.bootstrap-table.com/code/UtechtDustin/3998
