### ISSUE TITLE
bootstrap-table-group-by-v2 collapse/expand default setting

### ISSUE THREAD

**Issue by timoline** [wenzhixin/bootstrap-table#5181]
please add a default behaviour setting for bootstrap-table-group-by-v2 collapse/expand 

#5007

thx

**Comment by timoline** [comment]
Hi any progress?
We really need this ;-)

**Comment by UtechtDustin** [comment]
@timoline Currently no new progress, feel free to create a Pull request :-)

**Comment by UtechtDustin** [comment]
Hey @timoline, do you have a idea how the configuration could look like ?
Maybe a function which gets the group(name) as parameter(s) and decide if this should be collapsed/exapned via returning `true` or `false` ?

**Comment by timoline** [comment]
That would be great,
or/and just a "global" setting

**Comment by timoline** [comment]
many many rhx!!!

**Comment by UtechtDustin** [comment]
@timoline no problem, is this a solution which would work for you :-) ?

**Comment by timoline** [comment]
Little question,
do you have an example of how to collapse all by default, without knowing the group names/keys?

tia

**Comment by UtechtDustin** [comment]
No sorry, you need the keys.
But why you dont know the keys, you can fetch it from your data or not ?

**Comment by timoline** [comment]
Maybe that's my problem
How can I do that :-)
