### ISSUE TITLE
1.17.1版本 Bug

### ISSUE THREAD

**Issue by JupiterMx** [wenzhixin/bootstrap-table#5184]
**Bootstraptable version(s) affected**:

**Description**  

启用 detailView，并添加操作列，当数据为空时，表格显示错位，详细如图
1.16.0 版本不存在该问题
**Example**  

![image](https://user-images.githubusercontent.com/5134140/87665684-e4286e00-c799-11ea-8284-e2d7eb7c5ba7.png)

**Possible  (optional)**  

**Additional context**

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by JupiterMx** [comment]
> Please provide us an example using our [editor](https://live.bootstrap-table.com/).

https://live.bootstrap-table.com/code/JupiterMx/4015

**Comment by UtechtDustin** [comment]
Minimum example: https://live.bootstrap-table.com/code/UtechtDustin/4016
