### ISSUE TITLE
Sticky Header does not work with 2 Tables on the same page

### ISSUE THREAD

**Issue by Diagonir** [wenzhixin/bootstrap-table#5186]
**Bootstraptable version(s) affected**:
version: 1.16.0

**Description**  
The sticky header works only on the last initialized table. 

For example: While debugging the extension one can see that the `this` value in the `initHeader` function is correct when each table initializes, but when inspecting the value for `_this` in the triggered events ("resize.sticky-header-table", "scroll.sticky-header-table", and "scroll"), the value always refers to the last initialized table. 

This problem probably affects all other triggered events but I haven't looked that at them

**Example**  
I used the Sticky header example as base: https://live.bootstrap-table.com/code/Diagonir/4022
Two tables are initialized and one expectes that each table has sticky headers, but after scrolling down one can see that only the second table's headers stick

*edit: improved markdown

**Comment by Diagonir** [comment]
After testing some more, it seems that the problem lies in the `.off` and `.on` calls, now I understand why only the last `this` is maintained: because all other have been discarded through the `.off` calls. 

Here, for example:
```javascript
  $(window).off('scroll.sticky-header-table').on('scroll.sticky-header-table', function () {
	        return _this.renderStickyHeader();
  });
```

After removing the .off part, the event triggers for all tables. It solves the multi-table + sticky headers problem, but these events are quite expensive and the .off calls are there to prevent performance problems. 

Some of my webpages can contain up to 10 bootstrap tables and the performance hit is quite noticeable when the event triggers 10 times for each scroll. Since not all these tables are visible at  a given time, adding a visible check helped mitigate the problem: 
```javascript
$(window).on('scroll.sticky-header-table', function () {
	if (_this.$el.is(':visible')) {
		return _this.renderStickyHeader();
	}
});
```
Would that be an acceptable solution? I bet there's much better and better-performing ways to solve this problem. Any suggestions?

**Comment by UtechtDustin** [comment]
@Diagonir 
Thanks for checking whats the cause of the problem.
I like the idea of the visible check, but i dont like the idea to remove the `.off` part.
Instead of removing the `off` we should adjust the selector to the correct table instead of using a `window` selector.

Pullrequests are welcome :-)
