### ISSUE TITLE
how to listen pagedown click event?

### ISSUE THREAD

**Issue by vipkouyu** [wenzhixin/bootstrap-table#5190]
my table is front-end paging

I don't find any class or id  that related with pagination, the pagination HTML as follows in F12 chrome

```
<div class="clearfix">
     ::after
</div>
```

How to listen the pagedown click event?

**Comment by UtechtDustin** [comment]
What do you mean with `pagedown click event`?
If search for a event which will be triggered when a page was changed, you can use the [onpagechange event](https://bootstrap-table.com/docs/api/events/#onpagechange)

**Comment by UtechtDustin** [comment]
I close this issue, because we got not response from you within 7 days.
