### ISSUE TITLE
how to search main-table and sub-table ?

### ISSUE THREAD

**Issue by hasuikhs** [wenzhixin/bootstrap-table#5192]
**Description**  
i was applied to both the table and the sub-table.

but I want to search both tables and sub-tables with a single input & button.

bootstrap-table support this?

**Comment by UtechtDustin** [comment]
Please provide us an example (using our [Editor](https://live.bootstrap-table.com/)) of your setup!

**Comment by UtechtDustin** [comment]
I close this issue because we got no response from you within 7 days, if you still need help provide us an example of your setup and we will reopen the issue.

**Comment by wenzhixin** [comment]
I think `bootstrap-table` does not support this feature.
