### ISSUE TITLE
Sticky Header only firing on last table where multiple tables

### ISSUE THREAD

**Issue by valoukh** [wenzhixin/bootstrap-table#5193]
Perhaps this is beyond Sticky Header's capacity, but I have 2 tabs (bootstrap nav) with a table in each, and the Sticky Header only seems to work on the last table it is called on.

I tested this by using `setTimeout` on table 2 to delay the `bootstrapTable` call, and the result was that table 1 fired perfectly, but when table 2 was fired, the Sticky Header was removed from table 1.

**Comment by UtechtDustin** [comment]
I guess its fixed (#5191) in our develop branch.
Example for two tables: https://live.bootstrap-table.com/code/UtechtDustin/4051

Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by valoukh** [comment]
My setup uses HTML rather than JavaScript so I've created a similar example, but for some reason it's not firing even against 1 table! So I am now convinced it's something strange I'm doing...
Example: [https://live.bootstrap-table.com/code/valoukh/4053](url)

**Comment by UtechtDustin** [comment]
In your example you dont enabled the sticky-header extension (check the libraries tab).
For mor informations please read the wiki page: https://github.com/wenzhixin/bootstrap-table/wiki/Online-Editor-Explanation

**Comment by valoukh** [comment]
My bad! Thanks for the tip.

So this seems to demonstrate the issue without me needing to create tabs:
Example: https://live.bootstrap-table.com/code/valoukh/4054

Again, I'm sure it's the way I'm implementing it...

**Comment by UtechtDustin** [comment]
You implemented it in the correct way, as ia already thought it was a bug which is fixed in our develop branch.
Example (with our develop branch): https://live.bootstrap-table.com/code/UtechtDustin/4055

That means, the next version of the bootstrap-table will include the fix for that issue :-)

**Comment by valoukh** [comment]
Brilliant! Thanks so much for your help Dustin.

**Comment by UtechtDustin** [comment]
No problem, your welcome.
