### ISSUE TITLE
Printing does not work in Chrome

### ISSUE THREAD

**Issue by eugenelee0420** [wenzhixin/bootstrap-table#5195]
**Bootstraptable version(s) affected**:
1.17

**Description**  
The print plugin does not work on Chrome. The print window appears momentarily then closes immediately without showing the print dialogue.

**Example**  
https://live.bootstrap-table.com/example/extensions/print.html

**Possible  (optional)**  
Chrome does not use the OS native print dialogue. It is possible that the window closed before the dialogue can appear.
Fix: don't close the printing window (created by `window.open()`)

bootstrap-table-print.js: (near the bottom of the file)
```js
var newWin = window.open('', '');
newWin.document.write(this.options.printPageBuilder.call(this, table));
newWin.document.close();
newWin.focus();
newWin.print();
// Do not close the window
// newWin.close();
```

**Additional context**  
Chrome 84.0.4147.89 (64-bit) on Windows 10 (build 19042)

**Comment by UtechtDustin** [comment]
Should be a issue of the new version of chrome, it worked fine for the old version(s).
I will check that as soon i have time, maybe a `setTimeout` for the `newwin.close()` could help.

**Comment by UtechtDustin** [comment]
Works fine for me with 84.0.4147.89, so it seems its a problem of your setup.

![Bildschirmfoto von 2020-07-22 17-55-34](https://user-images.githubusercontent.com/13292481/88198973-93ef5700-cc44-11ea-827c-eda688a93db8.png)
![Bildschirmfoto von 2020-07-22 17-55-14](https://user-images.githubusercontent.com/13292481/88198977-9487ed80-cc44-11ea-9f49-e2778155c6ae.png)

**Comment by djhvscf** [comment]
Same here 
![image](https://user-images.githubusercontent.com/4496763/88561619-e20dad00-cfec-11ea-87f2-3ecc82afbda3.png)

Using Windows 10

**Comment by djhvscf** [comment]
Please review your setup since this does not look like a bootstrap-table issue

**Comment by MentYy** [comment]
Apologies for the late contribution however I thought I might add some insight to something I found. Print function was not working for me either.. found that the Grammarly chrome extension was the cause. As soon as it was disabled I was able to use the print function perfectly fine.

**Comment by MentYy** [comment]
Chrome extension Adblock Plus - free ad blocker 3.10.1 causes print function not to work as well.

**Comment by la1monas** [comment]
...few years later.... was having same issue and then saw a comment about Grammarly chrome extension. For me it was Adbock.. Once disabled, everything started working as expected. Hope this helps.
