### ISSUE TITLE
Get row data array onClickRow event

### ISSUE THREAD

**Issue by Siqsuruq** [wenzhixin/bootstrap-table#5198]
**Description**  
Hello, Im using onClickRow event to highlight selected row, Im not using checkboxes for data, and I need actual data from row to send to server with Ajax request. My question how do I get actual data array from $row?
In format key: value? Tables are dynamic so i don't know columns names.
```
<script>
$(document).ready(function(){
	$('#trns').on("click-row.bs.table", function (e, row, $element) {
		$('.highlight').removeClass('highlight');
                $($element).addClass('highlight');

		var array = $.map(row, function(value, index){
			return [value];
		});
		
		console.log(array);
		
	});
});
</script>
```
Thank you

**Comment by wenzhixin** [comment]
> get actual data array from $row

Sorry, I don't know what you want. Maybe you can provide an [Online Example](https://live.bootstrap-table.com) to show your problem.

**Comment by Siqsuruq** [comment]
Sorry JavaScript is not my strongest. For now Ive come up with this solution:
[https://live.bootstrap-table.com/code/Siqsuruq/4096](url)

On onClickRow event I highlight a row, on the same event I need values of this row (they need to be send to server), 
This row object has a lot of keys starting with _keyname.
For example my columns are id,name,atd,address etc. and in row object i have keys _id, _class  _data, id, _id_id, _id_class,_id_rowspan,_id_colspan,_id_title,_id_data etc., and I actually need only id key and its value. So im doing a loop and checking if key starts with "_" character I ignore it, if not I adding this key and value to my string (which im going to send to server, its in the online example code printed out in console).
My question is, what are those _ keys and values? If there is some more simple and elegant way to get keys->values (array) from selected row, but without using this column with checkboxes (like in [https://examples.bootstrap-table.com/index.html#methods/get-selections.html](url)  )?
My code works, but im pretty sure Im doing it wrong and its not how its suppose to work.
Thanks

**Comment by UtechtDustin** [comment]
@Siqsuruq 
The `_` keys is for internal purposes, but sometimes its usefull for external purposes.
Example which should solve your issue: https://live.bootstrap-table.com/code/UtechtDustin/4098

**Comment by UtechtDustin** [comment]
If still have questions or need help with that just ask and we will reopen the issue.
