### ISSUE TITLE
Pagination: current page should be "active", no "disabled"

### ISSUE THREAD

**Issue by geeyan** [wenzhixin/bootstrap-table#520]
- this will be more interactive: 

    <img src="https://dn-static-geeyan.qbox.me/images/e7/ff/c55712398b03b36db315fbb40543.png">

- file: src/bootstrap-table.js
- line: 857

    <img src="https://dn-static-geeyan.qbox.me/images/21/47/6149963b801f274444adea74f466.png">

**Comment by djhvscf** [comment]
Actually the current page is dsabled because you should no able to click again the current page. That is the reason because we use active and disable the current page. Does it make sense? @geeyan

**Comment by geeyan** [comment]
I don't think so.
If you don't set disabled to the current page element, it is also could not be clicked.
If you set active together with disabled, active has no visual effects to the element. @djhvscf

**Comment by djhvscf** [comment]
Well... I think you are right.. I think we don't need the disabled class for the pagination section. @geeyan  Would you like do that modification and then do a pull request? If not, I can do it

**Comment by geeyan** [comment]
Thank you for your understanding~
I have not done a pull request yet...Let me have a try.

**Comment by djhvscf** [comment]
Ok, If you need some help.. just ask for it! @geeyan

**Comment by wenzhixin** [comment]
Merged, close this issue.
