### ISSUE TITLE
About Angular 8/9  support

### ISSUE THREAD

**Issue by wcc526** [wenzhixin/bootstrap-table#5200]
About Angular 8/9  support. Is there any examples?

bootstrap-table 支持 angular8或9的使用吗？能给下示例吗？谢谢！

**Comment by UtechtDustin** [comment]
I'm not sure if someone of us use angular.
@wenzhixin @djhvscf  ?

**Comment by djhvscf** [comment]
I think we need to create a extension for it. Like the vue component that we have maybe

**Comment by wenzhixin** [comment]
We have removed the angular extension in #4239.
History version: https://github.com/wenzhixin/bootstrap-table/blob/1.13.1/src/extensions/angular/bootstrap-table-angular.js
