### ISSUE TITLE
groupby: not allowing collapse on "groupByFormatter" row

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#5202]
groupby: not allowing collapse 

https://live.bootstrap-table.com/code/Scnck/4101

**Comment by UtechtDustin** [comment]
The current version dont support collapsing/expanding the groups.
This features was merged 10 days before (#5177), that means the next version will support that.

**Comment by Scnck** [comment]
is there a way to keep the expanded/collapse status on a table refresh?

$table.bootstrapTable('load', data);

**Comment by UtechtDustin** [comment]
No its not possible because of way how the bootstrap-table works, similar to #1899

**Comment by Scnck** [comment]
this is what I'm currently doing...it works but is there a better approach?
```
onCheck: function onCheck(row) {
	var getCollapsed = $.map($("table > tbody > tr.groupBy.collapsed"), function(element) {return $(element).attr("data-group-index");});
	var scrollpx = $table.bootstrapTable('getScrollPosition');
	
	$table.bootstrapTable('load', jData);
	getCollapsed.forEach(index => $table.find('tr[data-group-index={0}]'.format(index)).click());
	
	$table.bootstrapTable('scrollTo', {unit: 'px', value: scrollpx})
	return false;
}
```

**Comment by UtechtDustin** [comment]
I guess this is fine as workaround.

**Comment by Scnck** [comment]
? when I collapse a few groups than make selection the table is reloaded/state is re-applied but I noticed now the header row widths change any idea what i'm doing wrong?
