### ISSUE TITLE
onclick event

### ISSUE THREAD

**Issue by jesussuarz** [wenzhixin/bootstrap-table#5203]
Hello

I hope you can help me.

I am trying to use an onclick event

however the event works fine if I don't use bootstrap-table.

I am using a php foreach to display some data in bootstrap-table.

I need to put something like this:

<tr data-href="#"  onclick="PickDomain(\''.$tbldomainpricing_todos[$keyX1]['extension'].'\')">
<td>data</td>
</tr>

the var $tbldomainpricing_todos[$keyX1]['extension'] will load different data.

example: .com, net, org
onclick seems to disappear in the browser. (or does not load).
my function in javascript is:

<script>
  function PickDomain(valor){
        document.getElementById("tld").value = valor;
        $(".selectpicker").selectpicker("refresh");
        }
</script>

to explain how it works.
I need that when the user selects the contents of the tr, the content (only what the variable prints) will be pasted into an input.

I'm not good with English, so I hope you understand what I'm trying to do.

**Comment by Elhamassi** [comment]
hello,
do you want to load your data with your example: .com, .net, .org, using php
when you click in button? this is what you want to main ?

**Comment by jesussuarz** [comment]
this is the path i am following:  http://jsfiddle.net/7qaw9ds1/1/

I need to load the data that goes through a vars into an input.
Look at my example, I don't know if I'm on the right track.

**Comment by jesussuarz** [comment]
my example still doesn't work but it's an thought.

**Comment by Elhamassi** [comment]
ok, i'm trying to exec your exemple.

**Comment by jesussuarz** [comment]
what updated to make you see better ... click the link again

**Comment by Elhamassi** [comment]
as i can see, when the event click in row, its not work, i think you should have to load  all library  of bootstraps ,
now im trying to start an example with your code. just give me few minutes.

**Comment by jesussuarz** [comment]
I will be attentive. I have all night trying to figure this out. thank you.

**Comment by UtechtDustin** [comment]
> I will be attentive. I have all night trying to figure this out. thank you.

@jesussuarz Does this means you issue is resolved ? :-)

**Comment by jesussuarz** [comment]
When I see the link, and what works I will say that. hahaha

**Comment by UtechtDustin** [comment]
Example using our editor: https://live.bootstrap-table.com/code/UtechtDustin/4106

**Comment by jesussuarz** [comment]
Now I can say it, you are a genius, thank you very much.

One last question, is there a way to use the rounded bootstrap class for rounded edges?

**Comment by Elhamassi** [comment]
@jesussuarz  can you check it, https://jsfiddle.net/YousraElh/b3u7vpsy/85/

**Comment by jesussuarz** [comment]
I really thank you. spend the night trying to do this. thank you very much my friend.

**Comment by jesussuarz** [comment]
is there a way to use the bootstrap round border class? or bootstrap-table have some similar class?

**Comment by UtechtDustin** [comment]
Sure you can use all classes, which bootstrp class du you mean ?

**Comment by jesussuarz** [comment]
Hello

I see I found another problem.

I have this code:

 <script>
  jQuery(document).ready(function ($) {
      $("[data-href]").click(function () {
          window.location = $(this).data("href");
      });
  });
  </script>

Basically he goes to the section where the domain has been selected.

this has a problem.

when you click on the he goes to another url, example to: url.com/.com

of course i don't understand how to solve this.

could you help me one more time

**Comment by jesussuarz** [comment]
So my final script is like this.

with this I have solved all my problem.

Thank you.

<script>
$("#table").on("click-row.bs.table", function (row, $element, field) {
    document.getElementById("tld").value = $element._data.href;
   $(".selectpicker").selectpicker("refresh");
});

  jQuery(document).ready(function ($) {
   $("[data-href]").click(function () {
//  window.scrollTo(0, 1);
$("html, body").animate({
    scrollTop: $("#tld").offset().top-350
}, 1000);

});
  });
<script>
