### ISSUE TITLE
How to set maximumcountcolumns ?

### ISSUE THREAD

**Issue by UltimatumGamer** [wenzhixin/bootstrap-table#5204]
Hey. Is there a way to set the maximum Columns Count?
Like this [example](https://bootstrap-table.com/docs/api/table-options/#minimumcountcolumns) but I want to set the maximum number and not the minimum number.

**Comment by UtechtDustin** [comment]
Currently there is no option to set a maximum columns count, could you explain why you need that ?
A example (using our editor) with your usecase would be great too.

**Comment by UtechtDustin** [comment]
I close that issue because we got no response from you within 7 days.
If your still interested please comment.
