### ISSUE TITLE
Printing not working correctly for grouped columns

### ISSUE THREAD

**Issue by GCru** [wenzhixin/bootstrap-table#5206]
**Bootstraptable version(s) affected**: 17.1

**Description**  
When the table has a group column, the print output fills in a  '-' for the first group column and extends the table by one column. 

**Example**  
https://live.bootstrap-table.com/code/GCru/4115

**Comment by UtechtDustin** [comment]
Additional info: The order of the data is also wrong.
The correct order would be:

- 0
- My
- Name
- 100

While printing the order is:
- 0
- 100
- My
- Name
