### ISSUE TITLE
源码中虚拟列表的计算逻辑中的参数是干啥的

### ISSUE THREAD

**Issue by vuvivian** [wenzhixin/bootstrap-table#5207]
**What are the parameters in the calculation logic of the virtual list in the source code？for example:**

              this.blockHeight = this.itemHeight * BLOCK_ROWS;
	      this.clusterRows = BLOCK_ROWS * CLUSTER_BLOCKS;
	      this.clusterHeight = this.blockHeight * CLUSTER_BLOCKS;

**What are the rules for defining constants? for example:**

             var BLOCK_ROWS = 50;
             var CLUSTER_BLOCKS = 4;

**Comment by djhvscf** [comment]
@wenzhixin please take a look at this issue

**Comment by wenzhixin** [comment]
`BLOCK_ROWS`: set a fixed number of `tr` rows, used to calculate the `start` and `end` of the virtual list.
`this.clusterRows = BLOCK_ROWS * CLUSTER_BLOCKS`: used to calculate the total number of displayed virtual lists.
`this.blockHeight` and `this.clusterHeight`: used to determine the position of the scroll bar and calculate the `top` and `bottom` of the virtual list.

```
const start = Math.max((this.clusterRows - BLOCK_ROWS) * num, 0)
const end = start + this.clusterRows
```

For example, at the beginning, rows 0-199 (50 * 4 = 200) are displayed. After scrolling to rows 150, it will recalculate and display rows 150-349, and so on.

Of course, 50 and 4 here are more suitable parameters based on the comparison, and they can also be modified.

![image](https://user-images.githubusercontent.com/2117018/88606754-1a29f400-d0b0-11ea-9f4b-f5833f21b7c2.png)
![image](https://user-images.githubusercontent.com/2117018/88606785-2ca42d80-d0b0-11ea-8433-378efb1a1bef.png)

---

`BLOCK_ROWS`：设置 `tr` 的固定行数，用于计算虚拟列表的 `start` 和 `end`。
`this.clusterRows = BLOCK_ROWS * CLUSTER_BLOCKS`：主要是用于计算显示的虚拟列表的总数。
`this.blockHeight` 和 `this.clusterHeight`：主要用于判断滚动条位置，以及计算虚拟列表的 `top` 和 `bottom`。

```
const start = Math.max((this.clusterRows - BLOCK_ROWS) * num, 0)
const end = start + this.clusterRows
```

例如最开始是显示 0-199 行（50 * 4 = 200），当滚动到 150 行后，便会重新计算并显示 150-349 行，以此类推。

当然这里的 50 跟 4 是我根据对比得出的比较适合的参数，也可以对其进行修改。

![image](https://user-images.githubusercontent.com/2117018/88606754-1a29f400-d0b0-11ea-9f4b-f5833f21b7c2.png)
![image](https://user-images.githubusercontent.com/2117018/88606785-2ca42d80-d0b0-11ea-8433-378efb1a1bef.png)
