### ISSUE TITLE
Add custom buttons in Buttons Toolbar

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#5208]
**Description**  
I would like to add some custom buttons on the right on the bootstrap-table ones. I see you can add custom html [below the buttons](https://examples.bootstrap-table.com/index.html#options/buttons-toolbar.html), I'm asking if it is possible to add buttons on the same line. 

**Example**  
Please see screenshot
![Bootstrap-Table-Examples](https://user-images.githubusercontent.com/6325475/88535596-22c3f100-d002-11ea-98dc-c649cce1e303.png)

**Comment by UtechtDustin** [comment]
Currently its not possible, but i think we should add that feature because there a some requests for that feature.
Until the feature is not implement you can use the buttonToolbar or the normal [toolbar](https://examples.bootstrap-table.com/index.html#extensions/toolbar.html).

**Comment by antonioaltamura** [comment]
Thanks.
Strictly related question: if I use https://examples.bootstrap-table.com/#options/custom-toolbar.html#view-source is there a way to keep `pagination-detail` content?

**Comment by UtechtDustin** [comment]
The example dont has pagination activated, that is the reason why no pagination will be displayed.
You can enable it, example: https://live.bootstrap-table.com/code/UtechtDustin/4118

**Comment by antonioaltamura** [comment]
I was thinking of having everything (my custom html and the pagination info) on a single line, but I guess it is not strictly necessary. Thanks.

**Comment by UtechtDustin** [comment]
@antonioaltamura im working on it.
The PR is still work in progress, but it would be greate if you could checkout the example in the PR to give us feedback.

**Comment by mdjaman** [comment]
Any update on the PR? Really need this feature

**Comment by UtechtDustin** [comment]
@mdjaman The PR is almost done. @djhvscf will check the last issue, because i have currently less time.
But if i find some time and @djhvscf dont did the last thing i will do it asap.

**Comment by djhvscf** [comment]
Working on it at this very moment FYI :)

**Comment by djhvscf** [comment]
Waiting for @UtechtDustin @wenzhixin  approval. See #5227

**Comment by mdjaman** [comment]
@UtechtDustin a schedule?

**Comment by UtechtDustin** [comment]
@wenzhixin i already agreed the PR, @wenzhixin has to check it or @djhvscf have to merge it :-)

**Comment by marceloverdijk** [comment]
Cool this being merged! Any plan for an official release including this?

**Comment by UtechtDustin** [comment]
This weekend we will release the new version.

**Comment by UtechtDustin** [comment]
@marceloverdijk @mdjaman 
New Version is released :-)

**Comment by marceloverdijk** [comment]
Upgraded ;-)
