### ISSUE TITLE
Addrbar Not Working

### ISSUE THREAD

**Issue by 365dayes** [wenzhixin/bootstrap-table#5213]
**Bootstraptable version(s) affected**:
Tested on latest version. 

**Description**  
Query parameters are not getting populated. Also when manually supplying the values nothing is respected. Is there a way to manually parse the url parameters and feed into the search field? 

**Example**  
https://live.bootstrap-table.com/code/365dayes/4149
loaded from data.json

**Possible  (optional)**  
No idea, perhaps I'm doing something wrong, but I can't figure out how to get this to work. 

**Additional context**  
Doesn't work on any browser type.

**Comment by UtechtDustin** [comment]
Could you please explain the issue more detailed ?
Our example works fine for me: https://examples.bootstrap-table.com/template.html?v=126&url=extensions/addrbar-page.html

Also please dont provide that kind of example, its to much. It would more help to provide minimal (just that feature which cause the issue) example.

**Comment by 365dayes** [comment]
@UtechtDustin sometimes it seems that multiple extensions might cause issues to one another. But for this case none of the features for addrbar are working. Bootstrap example is loaded. I would test with all those parameters. Here is a recording of my local environment that shows values aren't getting appended to the url. Also adding values to the url doesn't work either. ie. ?search=test

**Comment by 365dayes** [comment]
https://drive.google.com/file/d/1x-f_XGi_Zfjeq90jv4YRXNFyh2Fwxwyv/view?usp=sharing

**Comment by UtechtDustin** [comment]
We dont have access to that files, so please upload it with public access.

**Comment by 365dayes** [comment]
https://live.bootstrap-table.com/code/365dayes/4156
Should be publicly accessible.

**Comment by UtechtDustin** [comment]
I mean you google drive link, also: 
> Also please dont provide that kind of example, its to much. It would more help to provide minimal (just that feature which cause the issue) example.

**Comment by 365dayes** [comment]
Here is a more simplified version uploaded. Still unable to get addrbar values to properly populate. 

https://live.bootstrap-table.com/code/365dayes/4182

**Comment by UtechtDustin** [comment]
The current Version only works with server side pagination (which is btw. [documentated](https://bootstrap-table.com/docs/extensions/addrbar/#note)).

There is a PR #5232 which supports client side pagination, that means you have to wait for that PR (or you manually apply the patch).
