### ISSUE TITLE
Change of url arguments for sorting

### ISSUE THREAD

**Issue by JakeMana** [wenzhixin/bootstrap-table#5214]
**Description**  
I'm trying to implement bootstrap table with django rest framework as a backend. 
Problem im facing is that Django sorts data by accepting url such as "...?sort=foo" for ascending sort and "...?sort=-foo" for descending sort. So Django does not use additional argument "order=desc" but the direction of sorting is determined by using "-" before column name.
Is there any option or way to modify bootstrap table so it will generate url without "order=desc" and adding "-" (ex: sort=-foo" in case of descending order? 

**Example (optional)**  
Django url: /api/acceptance/?sort=title (asc) | /api/acceptance/?sort=-title (desc)

**Comment by UtechtDustin** [comment]
Should be possible with [queryparams](https://bootstrap-table.com/docs/api/table-options/#queryparams).

**Comment by wenzhixin** [comment]
@UtechtDustin is right, the `queryParams` can help you: https://live.bootstrap-table.com/code/wenzhixin/4157.

![image](https://user-images.githubusercontent.com/2117018/88748617-0a7bdf80-d184-11ea-908a-90d9dc49aaf6.png)
