### ISSUE TITLE
sortable column breaks starting in v1.17.0

### ISSUE THREAD

**Issue by mikewertheim** [wenzhixin/bootstrap-table#5217]
**Bootstraptable version(s) affected**:
The issue happens in 1.17.0 and 1.17.1. (It works fine in 1.16.0.)

**Description**  

Some sortable columns are unable to sort

**Example**  
The web site that demonstrates the problem is at the URL: http://www.showskimmer.com/?t=Pixar+movies&btv=1.17.1
Note that you can specify the version of bootstrap-table in the "btv" parameter. If that parameter is omitted, it defaults to 1.16.0, which is the working version.

To reproduce the problem... Note that the table has 3 sortable columns: Year, Rating and Title. The Rating and Title columns work fine. If you click the Rating column header twice, the table will respond by being sorted on the ratings in ascending order on the first click and descending order on the second click. Similarly, if you click the Title column header twice, the table will respond by being sorted on the titles in ascending order on the first click and descending order on the second click. But, if you click the Year column header twice, the first click sorts the table by year in ascending order, and the second click makes all of the sort column headers unresponsive (which is the bug).

I have reproduced this bug on the most recent versions of Safari/Mac, Chrome/Windows and Firefox/Windows.

**Comment by UtechtDustin** [comment]
Hey @mikewertheim, thanks for the detailed issue description.
Please provide us the example using our [Editor](https://live.bootstrap-table.com/), so we can clearly see which options do you use and how the data looks.

**Comment by mikewertheim** [comment]
@UtechtDustin This mostly reproduces the problem -- https://live.bootstrap-table.com/code/mikewertheim/4160
The difference between the stripped-down version at this link and the full version on showskimmer.com is: In the stripped-down version, the second click on the Year header just causes the Year column header to become unresponsive to further clicks. In the full version on showskimmer.com, the second click on the Year header causes all 3 column headers to become unresponsive to further clicks.

**Comment by UtechtDustin** [comment]
@mikewertheim 
As workaround until the bug is fixed, you can use the field column option.
Example: https://live.bootstrap-table.com/code/UtechtDustin/4162
