### ISSUE TITLE
Change cell value

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5218]
Hi
I found method updatecell. It can modify cell value if i know index of field
https://bootstrap-table.com/docs/api/methods/#updatecell

In my table i use select-combobox to select some value and after selecting i need to change value in cell.
Each row in table have got unique id
<tr id="tr-id-'.$i.'">

What is right way to change content in cell? 

Thanks a lot!

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/) of your current setup.

**Comment by djhvscf** [comment]
If this issue persists reopen it and provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!
