### ISSUE TITLE
extensions-filter-control-filterDefault support server search/refresh post data

### ISSUE THREAD

**Issue by RelicOfTesla** [wenzhixin/bootstrap-table#5219]
1. 
Why filterDefault not init bootstrapTable.filterColumnsPartial  .
I will fill property "filterDefault"(from URL param variable) to fill queryParam / filerParam in page first load,  was can not support it..

```ts
createControls()

// why only column.filterControl==false??
 if (!column.filterControl && '' !== column.filterDefault && 'undefined' !== typeof column.filterDefault) {
      if ($.isEmptyObject(that.filterColumnsPartial)) {
        that.filterColumnsPartial = {}
      }

      that.filterColumnsPartial[column.field] = column.filterDefault
    }
```

2. How can i replace OnSearch/OnRefresh => filterControl.Search???

3. [BUG]When i open "searchOnEnterKey"=true,
  * The httpPost "filter" field it is not fill all column field, only fill keyup's input-control when i am inputed multiple input-control
  * Can't trigger xx.bootstrapTable("triggerSearch").  because keyup is not 13, be ignore...

**Comment by UtechtDustin** [comment]
I dont understand what do you try to ask:

1. you can overwrite the queryParams and then can fetch a url parameter.
2. What do you try to archieve, why do you want to replace OnSearch/OnRefresh ?
3. Please provide us an example using our [editor](https://live.bootstrap-table.com/)

**Comment by UtechtDustin** [comment]
I close this issue as we got no more response from you, if still need help please answer the questions.
