### ISSUE TITLE
Adding data-show-footer="true" causes auto resizing of width to fail

### ISSUE THREAD

**Issue by zlace** [wenzhixin/bootstrap-table#5220]
**Bootstraptable version(s) affected**:
1.17.1
**Description**  
Having two tables of equal width side by side, with one hidden initially. 
Auto resizing of table width fails when data-show-footer is enabled

**Example**  
Toggle data-show-footer field to see the difference.
Works as intended when data-show-footer is false
https://live.bootstrap-table.com/code/zlace/4159

**Possible  (optional)**  

**Additional context**

**Comment by wenzhixin** [comment]
You need to use `resetView` method after our fixed version: https://live.bootstrap-table.com/code/wenzhixin/4166
