### ISSUE TITLE
groupby: grouping radio/check buttons

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#5221]
Hi,

I need to start to investigate the best approach to allow radio selection limited to a "groupBy" selection and allow both check/radio buttons to be shown on the same table. Any help would be greatly be appreciated. Thank you.

**Comment by UtechtDustin** [comment]
Currently not possible: #4652

**Comment by Scnck** [comment]
what is preventing this from working?

```
onCheck: function onCheck(row) {
	$table.find('input[type="radio"]').each(function(i,e) {
		var p = $(e).closest('tr').attr('data-parent-index');
		if (p) {
			$(e).attr("name", p);
		}
	});
	
	return false;
},
```
