### ISSUE TITLE
Bind custom function on column header 

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#5226]
**Description**  
I appreciate you can use `events` column option to handle events in a formatter. Is there a way I can do the same in a column header? Please note I'm using LitElement.

**Example**  
https://live.bootstrap-table.com/code/antonioaltamura/4172

**Comment by UtechtDustin** [comment]
There is no eventhandling for the header, because the header is not designed for html content.
But you can bind a event with pure javascript (or with jquery).
Example: https://live.bootstrap-table.com/code/antonioaltamura/4172
