### ISSUE TITLE
Add support addrbar extension with client side pagination

### ISSUE THREAD

**Issue by kerog** [wenzhixin/bootstrap-table#5228]
**Description**  
Current addbar exception works only with server side pagination. it will be great if addrbar works with client side pagination.

For my local enviroment I changed the addrbar extension like in https://github.com/wenzhixin/bootstrap-table/compare/develop...kerog:patch-1?expand=1#diff-f0040788ccc5c5ef468d259cbb8d5853

I used onPageChange event to get data from query (limit, page, search, sort) and this works

**Comment by djhvscf** [comment]
@kerog if this works for you, please create a PR with the corresponding example

**Comment by kerog** [comment]
Ok, I add this PR: https://github.com/wenzhixin/bootstrap-table/pull/5232

**Comment by wenzhixin** [comment]
Merged into develop
