### ISSUE TITLE
noeditFormatter: not working in latest version of plugin

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#5229]
noeditFormatter: not working in latest version of plugin

https://live.bootstrap-table.com/code/Scnck/4205

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/news/#bootstrap-table-1171

> Update(editable): Updated noeditFormatter to noEditFormatter.

https://live.bootstrap-table.com/code/wenzhixin/4206
