### ISSUE TITLE
Events stay bound on document when bootstrap table is no longer in view

### ISSUE THREAD

**Issue by crobinson42** [wenzhixin/bootstrap-table#523]
I discovered that the event listeners stay bound to the document after a view is removed.

You can see this by typing in your console:
$._data(document, 'events').click

It appears there is 10+ event listeners "sticking around".

**Comment by wenzhixin** [comment]
How to remove the view?

**Comment by djhvscf** [comment]
Maybe this works: http://stackoverflow.com/questions/12528049/if-a-dom-element-is-removed-are-its-listeners-also-removed-from-memory
