### ISSUE TITLE
Check checkboxes via JavaScript

### ISSUE THREAD

**Issue by Gamestarplayer41** [wenzhixin/bootstrap-table#5230]
**Description**  
I need to have a table with checkboxes. The checkboxes work as intended with mouse click.
Is there a way to check rows via JavaScript? So I can check specific rows?
For example check all with the amount>0

**Comment by UtechtDustin** [comment]
You can check it with the [check method](https://bootstrap-table.com/docs/api/methods/#check).

**Comment by Gamestarplayer41** [comment]
Is there a way to access all rows, to know which index i want to check?

**Comment by UtechtDustin** [comment]
Sure, you can fetch data using the [getData function](https://bootstrap-table.com/docs/api/methods/#getdata).

**Comment by wenzhixin** [comment]
https://live.bootstrap-table.com/code/wenzhixin/4214
