### ISSUE TITLE
Resize is incorrect with multiple columns

### ISSUE THREAD

**Issue by kuan2019** [wenzhixin/bootstrap-table#5234]
Hi,
  I have a  bootstrapTable with multiple columns (over the screen size with y-scrolling), I implemented the extension plug-in "bootstrap-table-resizable.js" with bootstrapTable, unfortunately I encounter resize is not working and nothing to happend with table.

best regards,
Eric Hu

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by kuan2019** [comment]
Hi,
   My example  be as below,

** Plug-in ** 
- jQuery v3.3.1 
- Bootstrap v4.0
- bootstrapTable  v1.17.1 & Extensions(bootstrap-table-resizable, bootstrap-table-editable)

**HTML **
<div class="col-md-12 mt-2">
    <lable for="asm_order_table">OrderList</lable>
    <table id="asm_order_table"
           data-toggle="table"
           data-url="/FetchOrderData"
           data-sort-name="order_oid" data-sort-order="asc"
           data-pagination="false"
           data-resizable="true">
        <thead>
            <tr>
                <th data-checkbox="true" data-field="chk_state"></th> 
                <th data-field="comp_01" data-editable="true">
                	<input type="checkbox" id="cb_comp_01" checked />
                </th>
                 <th data-field="comp_02" data-editable="true">
                	<input type="checkbox" id="cb_comp_02" checked />
                </th>
                 <th data-field="comp_03" data-editable="true">
                	<input type="checkbox" id="cb_comp_03" checked />
                </th>
                 <th data-field="comp_04" data-editable="true">
                	<input type="checkbox" id="cb_comp_04" checked />
                </th>
                 <th data-field="comp_05" data-editable="true">
                	<input type="checkbox" id="cb_comp_05" checked />
                </th>
                <th data-field="order_mid">order_mid</th>
                <th data-field="order_oid">order_oid</th>
                <th data-field="prod_name">prod_name</th>
                <th data-field="pkg_name">pkg_name</th>
                <th data-field="sku_name" class="text-nowrap">sku_name</th>
                <th data-field="prod_s_date" class="text-nowrap">prod_s_date</th>
                <th data-field="event_time">event_time</th>
                <th data-field="pax_name" class="text-nowrap">pax_name</th>
                <th data-field="country">country</th>
                <th data-field="passport" class="text-nowrap">passport</th>
                <th data-field="app_name">App Name</th>
                <th data-field="app_id">App ID</th>
                <th data-field="contact_tel" class="text-nowrap">contact_tel</th>
                <th data-field="pax_count">pax_count</th>
                <th data-field="first_name" class="text-nowrap">first_name</th>
                <th data-field="last_name" class="text-nowrap">last_name</th>
                <th data-field="birth" class="text-nowrap">birth</th>
                <th data-field="gender">gender</th>
                <th data-field="age">age</th>
                <th data-field="native_first_name" class="text-nowrap">native_first_name</th>
                <th data-field="native_last_name" class="text-nowrap">native_last_name</th>
                <th data-field="tw_id">tw_id </th>
                <th data-field="pick_htl">pick_htl</th>
                <th data-field="pick_addr">pick_addr</th>
                <th data-field="guide_lang">guide_lang</th>
                <th data-field="pick_time">pick_time</th>
                <th data-field="op_note">op_note</th>
            </tr>
        </thead>
    </table>
</div>

<script>
 var jsonData = {
    "seq": 1,
    "asm_xid": 102,
    "op_note": "",
    "sku_name": "Default",
    "prod_oid": 9912,
    "pkg_oid": 44666,
    "item_oid": 30001,
    "cus_oid": 3360288,
    "sku_oid": "9a8b621bdc2e911bacc5391e8f7c3016",
    "prod_s_date": "20200801",
    "event_time": "0830",
    "order_mid": "20KK072368384",
    "order_oid": 3068384,
    "prod_name": "Product Name",
    "pkg_name": "Package Name",
    "pax_name": "Peter Willison",
    "first_name": "Peter",
    "last_name": "Willison",
    "birth": "2009-01-13",
    "gender": "M",
    "age": 11,
    "native_last_name": "Peter",
    "native_first_name": "Willison",
    "tw_id": "ABC124107222",
    "country": "TW",
    "passport": "D11233",
    "app_name": "Line",
    "app_id": "hihiline",
    "contact_tel": "",
    "pax_count": 1,
    "spec1": "Default",
    "spec2": null,
    "spec3": null,
    "pick_htl": "Pickup Place...",
    "pick_addr": "Your city and address",
    "guide_lang": "en",
    "comp_01": "Component_01",
    "comp_02": "Component_02",
    "comp_03": "Component_03",
    "comp_04": "Component_04",
    "comp_05": "Component_05",   
    "pick_time": ""
  };

 </script>

**Comment by UtechtDustin** [comment]
@kuan2019 as wenzhixin already wrote, please use our online editor (linked in the post from wenzhixin).

**Comment by kuan2019** [comment]
Updated! https://live.bootstrap-table.com/code/kuan2019/4250

**Comment by wenzhixin** [comment]
Updated: https://live.bootstrap-table.com/code/wenzhixin/4253

**Comment by UtechtDustin** [comment]
This is a issue of the [jquery-resizable-columns](https://github.com/dobtco/jquery-resizable-columns) plugin.
You can test it on their [example](http://dobtco.github.io/jquery-resizable-columns/), as soon the width of the site is smaller then the page itself the plugin dont work.

So please open a issue on their [repository](https://github.com/dobtco/jquery-resizable-columns).

**Comment by takeAction** [comment]
@UtechtDustin i think multiple columns with horizontal scroll bar is a general case, it seems that there is nobody maintain jquery-resizable-columns any more and this problem haven't solved until now from 4 years ago.

if jquery-resizable-columns plugin will not solve this problem, do we have any workaround when using bootstrap-table?

**Comment by thetbw** [comment]
I have fixed it, but the result of my fix may not be universal, maybe he will enlighten you
see this [https://github.com/thetbw/jquery-resizable-columns](https://github.com/thetbw/jquery-resizable-columns/commit/d7e0e4d9ef429dc035a69a9940786be3576a4207)
