### ISSUE TITLE
Support filterDefault for select-controls

### ISSUE THREAD

**Issue by steinbachio** [wenzhixin/bootstrap-table#5238]
**Description**  
Setting `data-filter-default` does not work for selectcontrols atm.
This is caused by the current behaviour of `addOptionToSelectControl`. When adapting it like below, it will work.

```
function addOptionToSelectControl(selectControl, _value, text, selected) {
    var value = _value === undefined || _value === null ? '' : _value.toString().trim();
    var $selectControl = $(selectControl.get(selectControl.length - 1));

    if (!existOptionInSelectControl(selectControl, value)) {
        var option = $("<option value=\"".concat(value, "\">").concat(text, "</option>"));
        // +++ comparing value and selected as strings so possible type differences wont make a problem 
        if (value.toString() === selected.toString()) {
            option.attr('selected', true);
        }

        $selectControl.append(option);
        // +++ triggering new filter if a non empy defaultFilter is set.
        if (value.toString() === selected.toString() && selected !== '') {
            selectControl.change()
        }
    }
}
```

I'm not used to contributing to foreign projects. so should I just clone, create new branch, commit and create a merge request?

**Comment by UtechtDustin** [comment]
> I'm not used to contributing to foreign projects. so should I just clone, create new branch, commit and create a merge request?

Correct, clone the project, commit the changes create a mergerequest (with examples using our editor).

**Comment by UtechtDustin** [comment]
I close this issue as we got no response from you within 7 days, if you still want to help please open a PR with examples.
