### ISSUE TITLE
additional columns with action buttons

### ISSUE THREAD

**Issue by locito54** [wenzhixin/bootstrap-table#524]
is it possible to add an addtional column with extra buttons per row?

**Comment by velmuruganvelayutham** [comment]
Hi, 

Use formatter, events column option to define the custom events.

http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#column-events-table


![formatter_events](https://cloud.githubusercontent.com/assets/3096918/6123427/8778c07a-b128-11e4-86c9-5ca53c42862c.png)

**Comment by locito54** [comment]
thx works great
