### ISSUE TITLE
中文网例子加载不了

### ISSUE THREAD

**Issue by zcstatham** [wenzhixin/bootstrap-table#5240]
adsbygoogle.js:112 GET https://adservice.google.co.jp/adsid/integrator.js?domain=www.bootstrap-table.com.cn net::ERR_CONNECTION_TIMED_OUT
Vi @ adsbygoogle.js:112
b @ adsbygoogle.js:160
Pa @ adsbygoogle.js:161
rk @ adsbygoogle.js:163
El @ adsbygoogle.js:222
m.ba @ adsbygoogle.js:70
Nf @ adsbygoogle.js:78
pl @ adsbygoogle.js:221
(anonymous) @ adsbygoogle.js:228
(anonymous) @ adsbygoogle.js:228
template.html:20 GET https://code.jquery.com/jquery-3.3.1.min.js net::ERR_TIMED_OUT
template.html:14 GET https://use.fontawesome.com/releases/v5.6.3/css/all.css net::ERR_TIMED_OUT
util.js:55 Uncaught TypeError: Cannot read property 'fn' of undefined
    at util.js:55
    at bootstrap.min.js:6
    at bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6
template.js?v=VERSION:163 Uncaught ReferenceError: $ is not defined
    at template.js?v=VERSION:163
(anonymous) @ template.js?v=VERSION:163

**Comment by wenzhixin** [comment]
可以用英文网站：

* https://bootstrap-table.com/
* https://examples.bootstrap-table.com/
