### ISSUE TITLE
本地数据显示为“-”

### ISSUE THREAD

**Issue by dhxsy1994** [wenzhixin/bootstrap-table#5241]
**Description**  

按照官网的数据设置测试数据

以下为html页面：
    <script>
        $(document).ready(function () {
            $('#review-table').bootstrapTable('destroy');
            console.log("destroy")

            var responseHandler = function (e) {
                console.log(e);
                if (e.data && e.data.length > 0) {
                    return {"rows": e.data, "total": e.count};
                } else {
                    return {"rows": [], "total": 0};
                }
            }

            var queryParams = function (params) {
                var param = {
                    pageIndex: Math.ceil(params.offset / params.limit) + 1,
                    pageSize: params.limit,
                    order: params.order,
                    ordername: params.sort,
                };
                return param;
            }

            $("#review-table").bootstrapTable({
                method: 'get',
                url: "{{ url_for('static', filename="test.json") }}", // 请求路径

                //dataType: "json",//期待返回数据类型
                //maintainSelected: true,               //设置为 true 在点击分页按钮或搜索按钮时，将记住checkbox的选择项
                cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
                //pagination: true,                   //是否显示分页（*）
                sidePagination: 'client', // server:服务器端分页|client：前端分页
                //pageNumber: 1,                       //初始化加载第一页，默认第一页
                //pageSize: 5,                       //每页的记录行数（*）
                //pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
                //minimumCountColumns: 2,             //最少允许的列数
                clickToSelect: true,                //是否启用点击选中行
                //height: 500,                        //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
                //uniqueId: "id",                     //每一行的唯一标识，一般为主键列
                showToggle: false,                    //是否显示详细视图和列表视图的切换按钮
                contentType: 'application/json,charset=utf-8',
                //*************正确的数据也无法加载
                //responseHandler:responseHandler,
                {#queryParams: function (params) { // 上传服务器的参数#}
                {#    //params obj#}
                {#    var queryData = {};#}
                {##}
                {#    queryData.limit = params.limit;#}
                {#    queryData.offset = params.offset;#}
                {#    return queryData;#}
                queryParams:queryParams,

                columns: [{
                    checkbox: true
                }, {
                    title: '#',
                    filed: "id"
                }, {
                    title: 'Cluster Name',
                    filed: "cluster_name",
                }, {
                    title: 'Package Type',
                    filed: "package_type"
                }, {
                    title: 'Package Name',
                    filed: "package_name"
                }, {
                    title: 'Package Version',
                    filed: "package_version"
                }, {
                    title: '提交人',
                    filed: "commiter_name"
                }, {
                    title: '通过',
                    filed: 'id',
                    formatter: option_y
                }, {
                    title: '拒绝',
                    filed: 'id',
                    formatter: option_n
                }],
                onLoadSuccess: function (data) { //加载成功时执行
                    console.log("fetch success")
                    console.log(data);
                },
                onLoadError: function (res) { //加载失败时执行
                    console.log("fetch failed")
                    console.log(res);
                }
            })

            function option_y(value, row, index) {
                var htm = "";
                //点击事件未绑定
                htm += '<button id="yes" class="btn btn-primary"' + value +
                    '>通过</button>'
                return htm;
            }

            function option_n(value, row, index) {
                var htm = "";
                htm += '<button id="yes" class="btn btn-danger"' + value +
                    '>拒绝</button>'
                return htm;
            }

        })
    </script>

json数据：
[{"id": "123",
  "cluster_name": "all",
  "package_type": "pip",
  "package_name": "numpy",
  "package_version": "1x.xx",
  "commiter_name": "test"
},{
  "id": "124",
  "cluster_name": "all",
  "package_type": "pip",
  "package_name": "numpy",
  "package_version": "1x.xx",
  "commiter_name": "test2"
},{
  "id": "125",
  "cluster_name": "all",
  "package_type": "pip",
  "package_name": "numpy",
  "package_version": "1x.xx",
  "commiter_name": "tesx"
},{
  "id": "126",
  "cluster_name": "all",
  "package_type": "pip",
  "package_name": "numpy",
  "package_version": "1x.xx",
  "commiter_name": "test"
},{
  "id": "127",
  "cluster_name": "all",
  "package_type": "pip",
  "package_name": "numpy",
  "package_version": "1x.xx",
  "commiter_name": "test"
},{
  "id": "128",
  "cluster_name": "all",
  "package_type": "pip",
  "package_name": "numpy",
  "package_version": "1x.xx",
  "commiter_name": "test"
}

]

现在显示是不正确的，从渲染F12看是-这个字符，但是console是正确的json数据，不知道问题出在哪
我是使用bootstrap-flask的，加载的bootstrap版本4.3，jquery3.4版本
使用bootstraptable17.1 15.4都是同样的情况，浏览器无缓存
**Example (optional)**  

![image](https://user-images.githubusercontent.com/9987632/89631644-a53a9380-d8d3-11ea-868c-c5d3ea4aee1f.png)

**Comment by UtechtDustin** [comment]
Please use our [editor](https://live.bootstrap-table.com/) for examples!

**Comment by dhxsy1994** [comment]
> Please use our [editor](https://live.bootstrap-table.com/) for examples!

well, the vue example, the editor not working, I write html with flask-bootstrap, and js script to generate html

**Comment by wenzhixin** [comment]
@dhxsy1994 
It is `field`, you wrote it as `filed`.

----

是 `field`， 你写成了 `filed`。
