### ISSUE TITLE
Question: What might prevent data pagination from showing?

### ISSUE THREAD

**Issue by atoaugustyn** [wenzhixin/bootstrap-table#5242]
I am using Laravel and showing the data using client-side, I noticed when I set `data-side-pagination="server"` in the options `data-pagination="true"` doesn't work, the rows per page all shows only 10. Need help understanding why it behaves likes.

**Comment by UtechtDustin** [comment]
As you can see in our [example](https://live.bootstrap-table.com/example/options/server-side-pagination.html) it should work fine.   
We can help you if you create a example using our [editor](https://live.bootstrap-table.com/).

**Comment by atoaugustyn** [comment]
https://live.bootstrap-table.com/code/atoaugustyn/4291
@UtechtDustin please I have provided an example.

**Comment by UtechtDustin** [comment]
There is a `>` missing for the opening `table` tag.
Example with the missing `>` works fine: https://live.bootstrap-table.com/code/UtechtDustin/4292

**Comment by atoaugustyn** [comment]
Okay thanks, I think I have seen the problem. If the data passed in the URL is not json the rows and pagination don't load.
