### ISSUE TITLE
How can I render a React component in each row's actions column

### ISSUE THREAD

**Issue by hewby** [wenzhixin/bootstrap-table#5244]
I have a bootstrap table sitting in an application using ReactJS. I want the final column of my table to be a React component such as, say, a group of two buttons, edit and delete, which may take you to a different page or open a dialog with information specific to the row. In a previous project, we finally achieved this by doing the following:

Within componentDidMount -
`$('#myTable').bootstrapTable({`
`. . columns: [`
`. . . . { field: 'id', title: 'Id' },`
`. . . . { field: 'name', title: 'Name' },`
`. . . . { title: 'Actions', formatter: myFormatter,`
`. . . . . . . . events: {`
`. . . . . . . . . . . . 'click #btnSomewhereInComponent': (e, value, row) => {`
`. . . . . . . . . . . . . . . . this.handleClick(row.id);`
`. . . . . . . . . . . . }`
`. . . . . . . . } // events` 
`. . . . }`
`. . ]`
`});`

Elsewhere in the file -
`function myFormatter(value, row) {`
`. . const vDiv = document.createElement('div');`
`. . ReactDOM.render(<MyComponent row={row} />, vDiv, () => { });`
`. . return vDiv.innerHTML;`
`}`

This works but it requires hardcoding the id of the button we want to affect. Any button click is also registered as a click on the row which means any row details will expand as a side effect.

Trying to return an element in JSX from the formatter just fills the column with the string '[object Object]'.
Using the formatter but not the events and giving the React component an onClick or onChange method doesn't work because the method doesn't get called.

Do you have any ideas how this can be achieved in a cleaner way?

**Comment by UtechtDustin** [comment]
Im not sue if one of us core maintainer use react, so im not sure if we can help with that (@djhvscf @wenzhixin ?).
Why do you cant hardcode the id of the buttons ? :-)

**Comment by djhvscf** [comment]
Can you use classes instead of an id?

**Comment by UtechtDustin** [comment]
I'm closing this issue, because we got no response from you within the last 7 days.
If you still need help, please answer our questions.
