### ISSUE TITLE
exportDataType: 'all' does not export all data with pagination

### ISSUE THREAD

**Issue by Jendker** [wenzhixin/bootstrap-table#5245]
**Bootstraptable version(s) affected**:
1.17.1

**Description**  
The `exportDataType: 'all'` does not export all the data, only the visible list.

**Example**  
https://live.bootstrap-table.com/code/Jendker/4306

**Additional context**  
I was searching for viable options to solve this issue on the internet. Do I have to specify `sidePagination: 'server'` to make this work?

**Comment by AnselmC** [comment]
Hi thanks for the all your work.
Do you have any ETA for this fix to be released (using 1.18.1 currently).
Thanks!
