### ISSUE TITLE
Row selector checkboxes disappear on the demo site using Edge 44+ after export button option click

### ISSUE THREAD

**Issue by gurumark** [wenzhixin/bootstrap-table#5246]
**Bootstraptable version(s) affected**:
The latest version installed on the demo site.

**Description**  

After I clicked on Export button on any option, the checkboxes that are used to select table rows disappear on the following page:
https://examples.bootstrap-table.com/#welcome.html

I used the following browser:
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

Thank you.

**Comment by djhvscf** [comment]
I can't reproduce this issue. The checkboxes are hidden when exporting but then they are visible again

**Comment by UtechtDustin** [comment]
As i also cant reproduce this issue and we got no more response from you, we will clsoe this issue.
If think this issue still exists please comment with some more information.
