### ISSUE TITLE
updateRow without auto-sorting on sorted column

### ISSUE THREAD

**Issue by Torikiji** [wenzhixin/bootstrap-table#5248]
Is there a way to disable a column sort on a sorted column when calling updateRow? I have a column I want to be able to sort, but only when the column header is clicked. The table seems to auto sort if I update the sorted columns row value.

Using the below example... it will re-sort the table if you sort by itemName and then press updateRow.

https://live.bootstrap-table.com/code/Torikiji/4307

**Comment by UtechtDustin** [comment]
Currently not possible, for more informations check [this issue](https://github.com/wenzhixin/bootstrap-table/issues/3612#issuecomment-476378893).
