### ISSUE TITLE
How to set the sub column width of composite table header in bootstrap table

### ISSUE THREAD

**Issue by yuankaifan** [wenzhixin/bootstrap-table#5250]
**Description**  

**Example (optional)**  

How to set the sub column width of composite table header in bootstrap table

**Comment by wenzhixin** [comment]
I don't know what you want, can you provide more information? For example, provide an [Online Example](https://live.bootstrap-table.com).

**Comment by yuankaifan** [comment]
For example, a table is a combined header. I set the sub header, that is, the width of the second column header is invalid, but the width attribute value is on it, but it is not effective

**Comment by UtechtDustin** [comment]
@yuankaifan as wenzhixin already asked, please provide us an example using our editor!

**Comment by UtechtDustin** [comment]
I close this issue, because we got no response/example form you within 7 days.
If you still need help, please provide us an example using our editor!
