### ISSUE TITLE
不设置checkbox列，如何实现多选效果？

### ISSUE THREAD

**Issue by yatingkun** [wenzhixin/bootstrap-table#5254]
**Description**  

不设置checkbox列，如何实现多选效果？比如我按住并拖动鼠标就能选中多行，大哥能提供一些思路吗？
**Example (optional)**

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
`multipleSelectRow` option can be help:
https://examples.bootstrap-table.com/index.html#options/multiple-select-row.html
Hide checkbox: https://live.bootstrap-table.com/code/wenzhixin/4373

**Comment by UtechtDustin** [comment]
I close this issue, because we got no response from you within 7 days.
If you still need help, just ask and we will reopen the issue.
