### ISSUE TITLE
Question about server side pagination and search

### ISSUE THREAD

**Issue by jarodium** [wenzhixin/bootstrap-table#5255]
**Description**  
I would like to confirm the following scenario with server side pagination and search. This scenario is not answered in anywhere as I can find.

The scenario is to page search results as they come filtered from server side. Because, while search and pagination works, page numbers do not update according to given results.

**Example (optional)**  
HTML:

```html

table class="table table-striped"
  | data-toolbar="#toolbar"
  | data-search="true"
  | data-show-refresh="true"
  | data-show-toggle="true"
  | data-show-columns="true"
  | data-show-export="true"
  | data-minimum-count-columns="4"
  | data-show-pagination-switch="true"
  | data-pagination="true"
  | data-side-pagination="server"
  | data-detail-view="false"
  | data-id-field="id"
  | data-page-list="[10, 25, 50, 100, 200]"
  | data-show-footer="false"
  | data-locale="pt-Pt"
  | data-url="somepage.php"
```
My output from the server
```json
{
  "rows" : {[]}
  "total" : 500,
  "totalNotFiltered": 400
}
```

What I fail to understand is this:
What is the total? All records in the database before searching and pagination? or All records after searching and pagination?
What is the totalNotFiltered? Is the remainder of the total of records minus the filtered records? 

Bootstrap Table seems to kill pagination to display all search results and does it while I fiddle with the totalNotFiltered. It would be great I could display paginated search results from server side.

I see no problem with client-side search.

I would like to have an example explaining how to properly output the json ( total and totalNotFiltered fields ) assuming server side pagination with search.

Best regards

**Comment by UtechtDustin** [comment]
Without `data-side-pagination="server"` the table will expect the whole data from the server and do pagination on the client.
With `data-side-pagination="server"` the table will expect the data matching to the current page and the search (you get both as GET parameter).

Example: https://live.bootstrap-table.com/example/options/server-side-pagination.html
(Check the Networktab in your browser developer tools).

The option `totalNotFiltered` is btw. quite good documentated here:
- [showExtendedPagination](https://bootstrap-table.com/docs/api/table-options/#showextendedpagination)
- [totalNotFilteredField](https://bootstrap-table.com/docs/api/table-options/#totalnotfilteredfield)
Example: https://live.bootstrap-table.com/example/options/show-extended-pagination.html
(Search for `1`)

**Comment by jarodium** [comment]
Hi

From what I can infer from the example, total is the field which counts how many records are available with the current search options. totalnotfiltered is the full count of the records.

This is a little but confusing, but I will change my code report back ASAP.

Thank you @UtechtDustin

**Comment by jarodium** [comment]
I have fixed this.

For anyone who encounters the same issue you can do this in your algorithm with records from database:

1) Make a query to count all records with your initial query and put that count into 'total' and 'totalnotfiltered'
2) If there is a search, you must count all records that will yield from your query with search and put that count into 'total'
2.1) After the count, add the pagination code to your sql search query.
3) If there is no search you just need to add the pagination code to your sql query.

Best regards

**Comment by djhvscf** [comment]
Thanks @jarodium
