### ISSUE TITLE
Formatting the text of the options in the showColumns drop-down menu

### ISSUE THREAD

**Issue by GCru** [wenzhixin/bootstrap-table#5256]
**Description**  
As one of my column titles, I use a button that can open a modal. I am also using showColumns. The button formatting is shown along with the text in the showColumns drop-down menu. Can I just have the plain text contained in the button, instead? 

**Example (optional)**  
https://live.bootstrap-table.com/code/GCru/4361

Thank you

**Comment by UtechtDustin** [comment]
I dont think so, the header are not planned for html content.
What do you think @wenzhixin @djhvscf ?

**Comment by GCru** [comment]
I found a solution but in a roundabout way. I put a see-through button on top of the column title.

See code: https://live.bootstrap-table.com/code/GCru/4366

**Comment by GCru** [comment]
I found a solution in a roundabout way. I put a see-through button on top of the column title.

See my code: https://live.bootstrap-table.com/code/GCru/4366.

I then used headerStyle to format the column title so that it looks like a button.

There might however be a better way of doing this?

**Comment by djhvscf** [comment]
I think this is a edge case and also you found a workaround. Thanks.
