### ISSUE TITLE
First column does not sort using statically defined tables.

### ISSUE THREAD

**Issue by philjb** [wenzhixin/bootstrap-table#5257]
**Bootstraptable version(s) affected**: 
1.17.1

**Description**  

The first column does not sort without the `data-field` attribute. Run the example in the online editor.
**Example**  

```
<table data-toggle="table">
	<thead>
		<tr>
          		<th data-sortable="true">1</th>
			<th data-sortable="true">2</th>
		</tr>
	</thead>
	<tbody>
		<tr>
            		<th>1</th>
			<th>3</th>
		</tr>  
		<tr>
            		<th>2</th>
			<th>1</th>
		</tr>  
		<tr>
		         <th>5</th>
			 <th>2</th>
		</tr>
	</tbody>
</table>
```
The online editor demonstrates the problem

**Possible  (optional)**  

If you change the first column header definition to `<th data-field="foobar" data-sortable="true">1</th>` it will sort on the first column correctly.

The attribute `data-field` is not needed in this situation because a data url for a json document is not being used.

**Additional context**

**Comment by UtechtDustin** [comment]
Thank you for reporting this issue, we already fixed it in our develop Branch. ([Example](https://live.bootstrap-table.com/code/UtechtDustin/4362)).
That means the next version will contains the fix!
