### ISSUE TITLE
Cookie is invalid because its size is too big

### ISSUE THREAD

**Issue by knight-of-ni** [wenzhixin/bootstrap-table#5259]
**Description**  

I have a table with 15 columns of data and the cookie extension enabled. The pagination and search bar cookies work as expected, but the show/hide column cookie does not save. On Chrome this silently fails with no messages in the console. However, Firefox is more verbose and explains the problem:
`Cookie “saveId.bs.table.columns” is invalid because its size is too big. Max size is 4096 B.`

Not sure if this limitation can be addressed by the dev team, or if there is something I can do on my end to work around this.  This limit does not appear to be changeable on the browser side. I could change storage, but does that open up security risks?
Please advise.

**Example (optional)**  

The problem can be observed when using the following example on Firefox:
https://live.bootstrap-table.com/code/knight-of-ni/4375

**Comment by knight-of-ni** [comment]
![image](https://user-images.githubusercontent.com/5150042/90339776-b1e87700-dfb8-11ea-97e6-85afa5f7c2f0.png)

**Comment by UtechtDustin** [comment]
Thanks for the bug report, i submitted a PR which fix this issue.

First i thought you have weired long header columns, because it must be a lot of text for over 4096 Bytes.
Then i looked into the code and so are saving the whole columns object including internal data which makes no sense.
With this fix we only save the `field` attribute :-)

**Comment by knight-of-ni** [comment]
I applied pr #5260 to my project and the column state is now being saved between sessions. Tested on both Firefox and Chrome. Thank you very much for the fast turnaround!

**Comment by knight-of-ni** [comment]
@UtechtDustin There may be a regression associated with #5260 
As soon as the new cookie `zmEventsTable.bs.table.column` is created the checkbox column in my table disappears (completely from the DOM, not just hidden). Select on click functionality goes away as well. If I delete the cookie and refresh the page, the checkbox column comes back.

I can create a new issue if you want. Please advise.

**Comment by UtechtDustin** [comment]
@knight-of-ni no new issue necessary.
Im not able to reproduce it on the [example](https://live.bootstrap-table.com/code/UtechtDustin/4396), could you please explain how we can reproduce it ?

**Comment by djhvscf** [comment]
@knight-of-ni any update?

**Comment by knight-of-ni** [comment]
@djhvscf this was addressed in #5262
