### ISSUE TITLE
Checkbox column disappears with Cookie extension

### ISSUE THREAD

**Issue by knight-of-ni** [wenzhixin/bootstrap-table#5262]
**Bootstraptable version(s) affected**:
Latest master branch git 72dc5583474623d43547775b9126c856d7ed4c4a with cookie extension 

**Description**  
The checkbox column disappears from the table after saveId.bs.table.column cookie is created and the browser is refreshed. The column appears to be removed from the DOM, not just hidden.

**Example**  

Steps to reproduce:
- Load https://live.bootstrap-table.com/code/knight-of-ni/4395
- Trigger something to create the new cookie saveId.bs.table.column, such as hiding a few columns
- refresh the browser
- observe the checkbox column is gone
- From the browser console, delete saveId.bs.table.column cookie
- refresh the browser
- observe the checkbox column has returned

**Possible  (optional)**  

**Additional context**

**Comment by UtechtDustin** [comment]
Just as hint: This issue is not caused by the commit referenced above.
This Bug is also in 1.17.1.

We will check that!

**Comment by knight-of-ni** [comment]
Understood. Let me know if there is anything I can do to help.
