### ISSUE TITLE
How can I sort table by input value?

### ISSUE THREAD

**Issue by CapAllen** [wenzhixin/bootstrap-table#5265]
> Thanks for your awesome work!

I use jinja and flask to generate table, when I click the column's name, the table is sorted by `id` of `input` element in `td`, but I want it sort by the `value` of `input`.

Here is the screen shot of html:
![图片](https://user-images.githubusercontent.com/35265537/90495461-3d0f6b80-e177-11ea-8f94-3a262b656e74.png)

And here is the code:
```python
<table id="events" class="table table-hover" data-toggle="table" data-search="true" data-height="500">
        <thead>
            <tr>
                <th>标记删除</th>
                {% for col in result_data.columns.tolist()[1:] %}
                <th data-sortable="true">
                    {{database_info[table_name]['c_c_dict'][col]}}
                </th>
                {% endfor %}
            </tr>
        </thead>

        <tbody id="event-info">
            {% for i in result_data.index %}
            <tr>
                <td><span><input type='checkbox' name='select' id='select' value={{result_data.loc[i,'id']}}></span></td>

                {% for col in result_data.columns.tolist()[1:] %}
                <td><input id="{{result_data.loc[i,'id']}}&{{col}}" name="{{result_data.loc[i,'id']}}&{{col}}" value="{{result_data.loc[i,col]}}"></td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
```

Thanks for your help!

**Comment by UtechtDustin** [comment]
Instead of directly rendering the input, you should use a [formatter](https://bootstrap-table.com/docs/api/column-options/#formatter) or using the [editable extension](https://bootstrap-table.com/docs/extensions/editable/).

If you still want to render the input directyl, you have to write a custom [sorter](https://bootstrap-table.com/docs/api/column-options/#sorter) which parse the value from the input and comparse them to each other.

**Comment by CapAllen** [comment]
> 
> 
> Instead of directly rendering the input, you should use a [formatter](https://bootstrap-table.com/docs/api/column-options/#formatter) or using the [editable extension](https://bootstrap-table.com/docs/extensions/editable/).
> 
> If you still want to render the input directly, you have to write a custom [sorter](https://bootstrap-table.com/docs/api/column-options/#sorter) which parse the value from the input and comparse them to each other.

Thanks.
