### ISSUE TITLE
how we can do if jquery-resizable-columns plugin will not fix its issue

### ISSUE THREAD

**Issue by takeAction** [wenzhixin/bootstrap-table#5266]
**Description**  

there is issue [Resize is incorrect with multiple columns](https://github.com/wenzhixin/bootstrap-table/issues/5234), i encounter this problem too. And i found that even there is no horizontal scroll bar, if there are more columns enough, the resize feature is not smooth.

i think multiple columns with or without horizontal scroll bar is a general case, and it seems that there is nobody maintain jquery-resizable-columns any more, and this problem haven't been solved until now from 4 years ago.

if jquery-resizable-columns plugin will not solve this problem, do we have any workaround when using bootstrap-table?

Thanks!

**Comment by djhvscf** [comment]
Well, I think we have two options:

1. Use a different resizable column plugin and rewrite our extension
2. Create a resizable column plugin from scratch.

@takeAction  do you have any good plugin that we can use?

**Comment by UtechtDustin** [comment]
I close this issue, because we got no example and/or response from you within the last ~30 days!
If you still want to help please provide a example and answer question from djhvscf.

**Comment by shubh0294** [comment]
I am also facing same issue till now will you provide a solution

**Comment by takeAction** [comment]
I haven't found the solution in bootstrap-table yet, you could check another plugin/framework, e.g. https://www.datatables.net
________________________________
