### ISSUE TITLE
uncheckAll取消选中行时未联动取消背景颜色

### ISSUE THREAD

**Issue by litao11046** [wenzhixin/bootstrap-table#5268]
$table.bootstrapTable('uncheckAll') 取消选中的行时，没有自动将选中的背景色去掉。使用官方例子可以复现该问题：https://examples.bootstrap-table.com/#methods/check-uncheck-all.html

使用$table.bootstrapTable('uncheck', 1)就不存在这个问题

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by UtechtDustin** [comment]
I used a translator for that, the problem is if you check a row there is a style (backgroundcolor) applied.
If you use `uncheckAll` the style will not be removed, for `uncheck` its working fine.
