### ISSUE TITLE
Table pagination help

### ISSUE THREAD

**Issue by Crusader2010** [wenzhixin/bootstrap-table#5269]
Hi,

I would like a way to make the table skip one or more  `<tr>`s when the pagination events trigger.
For example, I want to have 3 rows in the `<tbody>` but pagination to only count 1 (when setting the visible elements within the table). This results in showing 30 items if I selected 10.

Another way to accomplish this is by providing a way to change the values shown in the dropdown to select the number of rows on a page. I want to be able to set the value, e.g. show me **30** elements, but the display text inside the dropdown to be **10**.

I need this because of the pagination not working properly with the "collapse" class and accordion tables. In my case I want to have a second `<tr>` which expands or collapses below the main `<tr>`. The problem is that the pagination also counts this `<tr>` and I cannot avoid it.

Thanks

**Comment by djhvscf** [comment]
Hi, do you mean that if we use subtables the pagination is taking into the account those subtables?

**Comment by Crusader2010** [comment]
I'm not talking necessarily about subtables but about more than one `<tr>` inside `<tbody>`, and the fact that I want to exclude some of those `<tr>`s from the pagination counting.

**Comment by djhvscf** [comment]
@Crusader2010 this is a super edge case since I think you may need to create a workaround for it. Marked as Not supported
