### ISSUE TITLE
Fixed table header

### ISSUE THREAD

**Issue by masterdany88** [wenzhixin/bootstrap-table#527]
Hey. Is it possible to make table header to stay on screen while user scrolls down?

**Comment by wenzhixin** [comment]
Hi, you can set 'height' option.

**Comment by masterdany88** [comment]
Hey. I mean something like this:
http://www.fixedheadertable.com/
As You can see, the table header stays on top always...

**Comment by wenzhixin** [comment]
We does not support this feature, if you want you need to implement by yourself.
