### ISSUE TITLE
How to keep table element attributes after launching bootstraptable?

### ISSUE THREAD

**Issue by aiming0420** [wenzhixin/bootstrap-table#5270]
Hi, I'm encountering a small issue referring table element attributes. It's simple like this:

[html file]
`<thead> ... </thead>`
`<tbody>`
`...`
`<td style="background-color:red">...</td>`
`...`
`</tbody>`
`</table>`

[js file]
`$("#mytable").bootstrapTable();`

This js script will actually remove the background color of that td, and I'd like to keep it.

Any help would be appreciated!

**Comment by wenzhixin** [comment]
Not support the `style` attribute, but you can use `class` instead, for example https://live.bootstrap-table.com/code/wenzhixin/4465.

**Comment by aiming0420** [comment]
> Not support the `style` attribute, but you can use `class` instead, for example https://live.bootstrap-table.com/code/wenzhixin/4465.

Thanks for helping!

The gb-color of `<td>`s are dynamically set based on the data from server when creating the DOM tree,  I can't know the bg-color in advance. So, it is not possible for me to create a `class` (colors are hex values from server with `<td>` indexes).

I just expect bootstraptable to keep my original `<td>` attributes hopefully with a option like 'keep-origion'. If there is not such an option, I'd like to dive into the code for customization. 

It would be much appreciated if there is a guide on such customizations.

(BTY, Why would bootstraptable remove td attributes, what's the intention of doing that?)

Best Regards!

**Comment by wenzhixin** [comment]
OK, consider as `feature`.
Workaround example: https://live.bootstrap-table.com/code/wenzhixin/4473 , maybe help you.

**Comment by aiming0420** [comment]
> OK, consider as `feature`.
> Workaround example: https://live.bootstrap-table.com/code/wenzhixin/4473 , maybe help you.

Thanks so much for the help! it works out!
