### ISSUE TITLE
Get table cell with input field

### ISSUE THREAD

**Issue by DangChien** [wenzhixin/bootstrap-table#5273]
**Description**  

I have a table with a customized column and this column uses a formatter to generate an input field HTML. I want to collect data that users put into that input field when users hit submit button. How can I do that? Thanks a lot.

**Example (optional)**  

```html
        function formFormatter(value, row, index, field) {
            let items = calculateRemainingItems(row);
            return '<input type="text" value="' + items + '">'
        }
```

**Comment by DangChien** [comment]
Thanks for your suggestion. Initially I thought bootstrap-table has some built-in method to get those data.

I ended up with the following solution:

- Add the id to each input field.
```
function cellFormatter(value, row, index, field) {
    let count = calculate(row);
    return '<input id="item-' + row['id'] + '" type="text" value="' + count + '">'
}
```
- Then retrieve its value using jQuery selector.
```
let count = $('input#item-' + value['id']).val()
```

**Comment by UtechtDustin** [comment]
You also can use the [editable](https://bootstrap-table.com/docs/extensions/editable/) extension.

**Comment by DangChien** [comment]
Nice. I will try it out.
