### ISSUE TITLE
When trying to export a pdf file with Chinese titles, those Chinese titles will become garbled words

### ISSUE THREAD

**Issue by litao11046** [wenzhixin/bootstrap-table#5275]
**Example**  
https://live.bootstrap-table.com/code/litao11046/4434

the pdf file will be like this:
![image](https://user-images.githubusercontent.com/35892806/90988721-d3e48980-e5b6-11ea-85ec-c4005b889bf0.png)

**Comment by wenzhixin** [comment]
ref https://github.com/hhurz/tableExport.jquery.plugin/issues/303

Working example: https://live.bootstrap-table.com/code/wenzhixin/4464
