### ISSUE TITLE
Initial filter of table data possible?

### ISSUE THREAD

**Issue by johnsonk** [wenzhixin/bootstrap-table#5276]
I would like to apply a filter when the bootstrap table is initially displayed but haven't been able to make that work.  I can define the filterOptions containing a filterAlgorithm when initializing the bootstrap table.  This works fine when I call filterBy at a later time.  However, I'd like to be able to apply the filterBy when the bootstrap table is initially displayed.  Is this possible?

For example, all data is provided for the table but I may want to initially filter to just the rows where one column value is true and allow the user to change the filter to display all rows.

**Comment by UtechtDustin** [comment]
I guess you are using the filter-control extension ?
Then you can use the column option [filterDefault](https://bootstrap-table.com/docs/extensions/filter-control/#filterdefault).
does that solve your problem?

**Comment by johnsonk** [comment]
I'm only using bootstrap-table and my own javascript. If a default filter can't be set that way, I can look at using the extension.

**Comment by johnsonk** [comment]
I'm not sure what I did different today but it seems to work by simply calling the filterBy method immediately after initializing the bootstrapTable.

So:

$myTable.bootstrapTable({
     // my init options
});

if (defaultFilterValue)
     $myTable.bootstrapTable('filterBy', defaultFilterValue);

**Comment by UtechtDustin** [comment]
> I'm only using bootstrap-table and my own javascript. If a default filter can't be set that way, I can look at using the extension.
> I'm not sure what I did different today but it seems to work by simply calling the filterBy method immediately after initializing the bootstrapTable.

I guess its a timing issue, you should use a event e.g. [onPostBody](https://bootstrap-table.com/docs/api/events/#onpostbody).

**Comment by johnsonk** [comment]
I'll give that a try.  Thanks.
