### ISSUE TITLE
Table with detail-view and no records found, colspan short 1 col

### ISSUE THREAD

**Issue by togrady01** [wenzhixin/bootstrap-table#5277]
**Bootstraptable version(s) affected**:
1.17.1

**Description**  
Table with detail-view enabled, and N columns, meaning N+1 total columns with detail-view toggle column.  When there is no data to display in the table, the "no-records-found" indicator is colspan N cols, not N+1 cols.  This creates a gap that you get a blank cell in col N+1 (see img).  If the background behind the table is a different color than the row, it is very apparent.
<img width="452" alt="example img of colspan issue" src="https://user-images.githubusercontent.com/47083646/91646711-2b07b580-ea20-11ea-9252-ea7e7c7b69bc.png">

**Example**  
https://live.bootstrap-table.com/code/togrady01/4486

**Possible  (optional)**  
Possibly related to #5185 ?

**Additional context**  
My use case is inside Electron v9+, however replicating with online editor and MS Edge (Chromium).

**Comment by UtechtDustin** [comment]
Thanks for your bug report, this bug is already fixed in our develop branch.
The next version will contain this fix.

Example including the fix: https://live.bootstrap-table.com/code/UtechtDustin/4488
