### ISSUE TITLE
Fixed column widths

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5279]
**Description**  
I'm trying to implement fixed column width without success so far when the screen side is to small.

Now I read in the `data-width` the following:

> The width of column. If not defined, the width will auto expand to fit its contents. Though if the table is left responsive and sized too small this 'width' might be ignored (use min/max-width via class or such then). The default used Unit is ‘px’, use widthUnit to change it!

Is there an example for **"Though if the table is left responsive and sized too small this 'width' might be ignored (use min/max-width via class or such then)"** as I don't understand what is meant here.

**Comment by UtechtDustin** [comment]
> Is there an example for "Though if the table is left responsive and sized too small this 'width' might be ignored (use min/max-width via class or such then)" as I don't understand what is meant here.

Its quite simple, it means if you define `data-width=20` but the header text needs at least a width of 50 the width attribute will be ignored. If you want to force the width you have to use a own class which defines the `min-width` css option.

**Comment by marceloverdijk** [comment]
So something like `data-thead-classes="min-width-100"`

```
.min-with-100 {
  min-width: 100px;
}
```

**Comment by zeroone2005** [comment]
one table, it's good idear,but mulit tables
