### ISSUE TITLE
Filterable extension for bootstrap table

### ISSUE THREAD

**Issue by masterdany88** [wenzhixin/bootstrap-table#528]
Hey. I remember that some time ago You had table example with filters, but I cant find it. Is it still possible? How can I achive this. I found in extension dir of bootstrap table dist where I can find this screen. But there isnt any word about it in documentation. Can You help?

**Comment by djhvscf** [comment]
Is this one?? http://wenzhixin.net.cn/p/bootstrap-table/docs/extensions.html#filter

**Comment by masterdany88** [comment]
Yeah. Exacly

**Comment by djhvscf** [comment]
So, Can we close the issue? @masterdany88

**Comment by masterdany88** [comment]
No. This dosnt work for me. Is it supported in new version.

**Comment by dabros** [comment]
@masterdany88 

The #466 filterBy method was created, though i found it rather limited so went and reworked it and tied it into my ui so each column had a nicely presented filter.

I shared this part of my code here: #678

**Comment by djhvscf** [comment]
@dabros we have an option filterControl to do that

**Comment by dabros** [comment]
@djhvscf 

You must have just done that, because i downloaded stable 1.6.0 at start of week and no such function

**Comment by dabros** [comment]
@djhvscf 

Im looking at release 1.7.0 (just yesterday, when i was making this code) but i cant see any referance to this in changelog itself, though i see entry in documention page

Can you please provide link to that commit :)

https://github.com/wenzhixin/bootstrap-table/commit/33de0ac8b2600ed4283bc18bbc197d212ef5d88d

**Comment by dabros** [comment]
@djhvscf - i see a bootstrap-table-filter.js file in that commit - isnt that deprecated?

**Comment by djhvscf** [comment]
Yeah.. You're rigth.. @wenzhixin please add the filterControl column option to the changelog.. And see this: https://github.com/wenzhixin/bootstrap-table/pull/603 and this: https://github.com/wenzhixin/bootstrap-table/pull/306

**Comment by djhvscf** [comment]
And you can see this also: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/filter-control.html

**Comment by dabros** [comment]
@djhvscf - thanks for that, my filterable is working fine though i will need to add some code to carry across the filters for server-side filtering sometime, but still fleshing out other parts of my demo atm, so prob post alpha for that

That options/filter-control.html not existing yet, but i assume it will soon

If you have time to look at maybe merging that with my suggestions in #678 then great, as is i will prob stick with my modded 1.6.0 till least out of alpha for the webapp - got a bunch of tweaks on it though im trying to keep most inside callbacks

**Comment by djhvscf** [comment]
Yeah.. The filerControl now is an extension because we have to implement the datapicker and things like that :)

See: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filtercontrol.html
and this: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/filtercontrol

**Comment by wenzhixin** [comment]
OK! close this issue.

**Comment by masterdany88** [comment]
Great. Thanks
