### ISSUE TITLE
Sort date/datetime columns

### ISSUE THREAD

**Issue by faran-mw** [wenzhixin/bootstrap-table#5280]
I have noticed that date columns are treated as string and sorted accordingly. It would be great to set a data type on columns so sort can work for non string columns as well.

**Comment by UtechtDustin** [comment]
You can use [customSort](https://bootstrap-table.com/docs/api/table-options/#customsort).   
Example: https://examples.bootstrap-table.com/#options/custom-sort.html

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/#column-options/sorter.html
Duplicate of ##65
