### ISSUE TITLE
scrollTo: detailView not considered

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#5281]
current plugin doesn't account for a row that implements a detailView and doesn't fully show row info.

**Comment by UtechtDustin** [comment]
You already opened a few issues, you should know that we need a example using our [editor](https://live.bootstrap-table.com/).

**Comment by djhvscf** [comment]
Hi! There is not any reply, in that case we are going to close this issue. Remember to add an [example](https://live.bootstrap-table.com/). Thanks!
