### ISSUE TITLE
Problem to create multiple tables resizables

### ISSUE THREAD

**Issue by MaximilianoAlarcon** [wenzhixin/bootstrap-table#5284]
In my page there are multiple tables inside TABS, all the tables are configured as resizables.
When i load the page i can only resize the first table in ouput, if i go to another tab i can't resize the table inside it

**Comment by djhvscf** [comment]
What if you init the table when the tab is clicked?

**Comment by jimgit** [comment]
@MaximilianoAlarcon  Something [like this](https://live.bootstrap-table.com/code/jimgit/4601)?

**Comment by UtechtDustin** [comment]
@jimgit i guess that he want's to use the resize column extension.

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
