### ISSUE TITLE
Single Row View or Vertical Field Table

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#5286]
Hi all,
I have a question for table view. 

This is a sql result for standart view. i can show this data on table.
![image](https://user-images.githubusercontent.com/15678340/92720481-54540a00-f36d-11ea-96ce-7e69df9cef5f.png)

How can i show data like below

![image](https://user-images.githubusercontent.com/15678340/92722288-01c81d00-f370-11ea-9b97-da004202b120.png)

Thanks..

**Comment by djhvscf** [comment]
Not sure about your question, you can show both data formats. The only thing is that you need to return it as you want and also configure the table with the appropriate columns

**Comment by jimgit** [comment]
@mehmetalidumlu Your data columns and the data values each look identical.   It is difficult to see what you are trying to do.  Are you trying to do a pivot on the [data to transform it from horizontal to vertical?](https://www.mssqltips.com/sqlservertip/1019/crosstab-queries-using-pivot-in-sql-server/).   Could put your data into an example [such as this?](https://live.bootstrap-table.com/example/welcomes/from-data.html)

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
