### ISSUE TITLE
Pagination is not like it is meant to be

### ISSUE THREAD

**Issue by saraycodes** [wenzhixin/bootstrap-table#5287]
Suppose i have 800 records to show in table, i have to fetch all records and then pagination is applied. what if i want to fetch only first 10 records for first page?
I have done this job but now i am unable to use features like search , export data in excel and data filter etc, that is because i have implemented the record fetching method by sending pageSize and pageNo. 

Please read: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports
and post issue to: https://github.com/wenzhixin/bootstrap-table/issues, thanks!

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/), it should work fine using the table option [sidePagination](https://bootstrap-table.com/docs/api/table-options/#sidepagination).

**Comment by UtechtDustin** [comment]
I'm closing this issue, because we got no response from you within the last 7 days.
If you still need help with that please provide us an example.
