### ISSUE TITLE
(ask) how use xeditable event at bootstrap-table?

### ISSUE THREAD

**Issue by wandyirawan** [wenzhixin/bootstrap-table#529]
hi, how use event in xeditable on bootstrap-table? i want after edit column my app next to other editable column? 

Thanks

**Comment by Muzical84** [comment]
I wish I could up-vote this; the documentation doesn't help at all, and the given JS Fiddle, http://jsfiddle.net/wenyi/e3nk137y/28/light/ , doesn't actually allow editing, at least in Chrome.

**Comment by wandyirawan** [comment]
hi @Muzical84 , 
i have done with code like this:
`
$('#table').bootstrapTable({
//some code
})
.on('editable-init.bs.table', function(e){
    
    $('.editable').on('save',function(e, params){
      //do some
    });
});
`

hope this help any body

**Comment by wenzhixin** [comment]
hi, you can use this event: 'editable-save.bs.table': 'onEditableSave'

**Comment by Muzical84** [comment]
OK I was trying to use the on load success event for the Bootstrap Table itself.  That was where I seem to have strayed.

**Comment by mastermike14** [comment]
huh? This still doesn't make sense. Can someone post an example where the data is actually submitted? All the examples I can only show to make a field editable which is friggin useless if you can't submit the data.
