### ISSUE TITLE
How can I use search input outside the toolbar?

### ISSUE THREAD

**Issue by joicy** [wenzhixin/bootstrap-table#5290]
Hi everyone!
I would like to know if it's possible to use a search input outside the toolbar. I did the search with jquery but is filtering just visible fields, I would like to use the bootstrap-table engine.

An example: https://live.bootstrap-table.com/code/joicy/4610

**Comment by UtechtDustin** [comment]
Currently its not possible with the default search input, but we should implemebt this!
But we have that support for the filter-control extension, maybe [this](https://bootstrap-table.com/docs/extensions/filter-control/#filtercontrolcontainer) helps :-)

**Comment by joicy** [comment]
Thank you @UtechtDustin! I would appreciate it. The problem of filter-control is because it works just for one field and I need this input working like the default search input.
