### ISSUE TITLE
$table.bootstrapTable('getData') not returning modified values

### ISSUE THREAD

**Issue by guilherme-grf** [wenzhixin/bootstrap-table#5297]
Bootstraptable version(s) affected:
1.17.1

Description
getData not retourning elements where the value was changed, for example: using a formater to transform the field in a input, when the user changes the data on the input the getData return the original data only. 

How to get the new data?

I tried modifing the outerHTML, the defaultValue and the value but neither worked.

**Comment by UtechtDustin** [comment]
You have to update the data manually (listen on the input(s) then use the [updateRow](https://bootstrap-table.com/docs/api/methods/#updaterow) method or you can use the [editable extension](https://bootstrap-table.com/docs/extensions/editable/).

**Comment by guilherme-grf** [comment]
Thank you UtechDustin, I endup using the updateCell and that worked.

**Comment by UtechtDustin** [comment]
Your welcome, thank you for the feedback :-)
