### ISSUE TITLE
import extension error

### ISSUE THREAD

**Issue by Shaun-Yao** [wenzhixin/bootstrap-table#5300]
I am using v3.3.7
when i import bootstrap-table-sticky-header.js, like
<script src="/webjars/bootstrap-table/src/extensions/sticky-header/bootstrap-table-sticky-header.js"></script>
there is an error in the web console:
bootstrap-table-export.min.js:10 Uncaught TypeError: Class constructors cannot be invoked without 'new'
at new n (bootstrap-table-export.min.js:10)
at HTMLTableElement.<anonymous> (bootstrap-table.min.js:10)
<img width="258" alt="bootstrap-table-error" src="https://user-images.githubusercontent.com/18024481/93189884-47705580-f775-11ea-821c-8d5e641005ec.png">

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by wenzhixin** [comment]
Please use the `dist` file: `dist/extensions/sticky-header/bootstrap-table-sticky-header.min.js`
