### ISSUE TITLE
filter controle & cookies bug select

### ISSUE THREAD

**Issue by flaajimi** [wenzhixin/bootstrap-table#5301]
**Description**  

When I use the select with filter control and cookies with a format variable, it stores the format variable and not the value.

![image](https://user-images.githubusercontent.com/22789071/93209906-0ff6ae80-f75f-11ea-91e9-8d9e50888b9d.png)

![image](https://user-images.githubusercontent.com/22789071/93210227-87c4d900-f75f-11ea-8222-c8c86c13cb76.png)

`
 {field: "fk_priority",title: "{{ 'label.priority'|trans }}",valign: 'middle',sortable: true,visible: true,filterControl: "select",filterStrictSearch: true,
                            formatter:function(value,row) {
                                return '<a class="priority label label-' + row.fk_priority_color + '">' + row.fk_priority + '</a>';
                            },events: "operateEvents",
                        },
`

Thank you for your help

**Comment by UtechtDustin** [comment]
Dupliacte of #5076
