### ISSUE TITLE
latest fix broke writing to empty array source

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#5305]
latest fix broke writing to empty array source

https://live.bootstrap-table.com/code/Scnck/4784

**Comment by djhvscf** [comment]
Which change are you referring to?

**Comment by UtechtDustin** [comment]
Ref #5302 / 7d38b524ebe7a7747ed7e30ceebef0a4912b6f06

@wenzhixin please check this.

**Comment by Scnck** [comment]
yes this Ref #5302 / 7d38b52 was the fix that broke the functionality shown in my example.

**Comment by djhvscf** [comment]
Not sure about your example, since your trying to print an empty array always. What happen if the button3 event calls the getdata method?

**Comment by UtechtDustin** [comment]
I also dont understand the example, it works fine for me.
Inserting some data work, `getData`  works and the `srcData` always returns the empty array which is correct.
So i remove the bug label because it dont seems to break anything.

**Comment by Scnck** [comment]
Not sure why you don't think this a bug, its not writing data back to the source object...This is a bug for sure...

https://live.bootstrap-table.com/code/Scnck/4802 this show it being written back to the source object

**Comment by UtechtDustin** [comment]
No the bug (which was fixed in the commit above) was that we wrote back to the source array (or better we used the array).
If you want to get the current data you can use the function `getData`.

**Comment by Scnck** [comment]
so you're now saying I have to manual sync data back to the source data on changes...

**Comment by UtechtDustin** [comment]
Yes, that is what the `getData` function is for.
99% of the usecases of the bootstrap-table dont need a sync between table and source array.

Also its pretty easy to implement, just execute the getData method after you updated the table.

**Comment by Scnck** [comment]
I guess I would make the a feature option to use src data rather than internal memory on insert/update, etc.

**Comment by UtechtDustin** [comment]
Lets see what @wenzhixin and @djhvscf think about that, because this can cause issues with some features/extensions (that was the reason for the fix).

**Comment by Scnck** [comment]
if you first do an 'update' the src object is written/synced to then if you 'insert' than table starts to using internal memory.
https://live.bootstrap-table.com/code/Scnck/4805

**Comment by djhvscf** [comment]
The thing is that if we keep the previous behaviors we can cause some many bugs when there are more than one table initialized. So, I think we need to isolated the data, events, methods per table.

In fact, for me is not correct to have a source array affected by our table, looks like buggy for me. What happen if you need to work on that source array but as it is (without modifications)?

**Comment by wenzhixin** [comment]
I agree with @djhvscf and @UtechtDustin.
`bootstrap-table` don't need a sync between table and source array.
The update problem fixed in #5307.
