### ISSUE TITLE
Export stopped working

### ISSUE THREAD

**Issue by snoopy72** [wenzhixin/bootstrap-table#5306]
**Bootstraptable version(s) affected**:
Current sources downloaded (with git clone ...) and compiled them.

i only replaced the datatables files (copied from the dist folder after compiling); the "tableExport.min.js" script has been left untouched.

**Description**  
The export functionality of the table data has stopped working. With version 1.17.1 i got a CSV file - with the current sources i only get the headline (= column names) but no data. tried with and without checking rows before exporting.

**Additional context**  

Sorry, if my comment may be in the wrong ticket, but i downloaded the current sources and compiled them ~ 1 hour ago. 

i am waiting for ticket #5167 and wanted to check the new feature.
Also i am waiting or ticket #5227, so I know that you're planning a new build - so this report just FYI.

**Comment by snoopy72** [comment]
Additional details:

It seems, that the *limit value* is not passed in the request for reading the export-data.
Due to this, my (normally working) server-function crashes with an sql error .. because the limit value is not given.
the same table is working normal (incl. paging, select columns, etc) with "pagination" and "sidePagination = server".

**Comment by UtechtDustin** [comment]
If i understand it correct you compiled the newest version and mixed two versions ? 
This can cause errors.

If this is not the case please provide us an example using our [editor](https://live.bootstrap-table.com/).
Working example with our develop branch: https://live.bootstrap-table.com/code/UtechtDustin/4818

**Comment by snoopy72** [comment]
No, i completly removed the previous version and copied the freshly compiled version instead.
of course not both versions as a mix !

problem seems to be somewhere else - i debugged some times more and i'll try to explain:

our tables requests their data via POST request from a server. due to the server-paging, that requests automatically are submitting additional data like "offset" and "limit".

debugging the normal request with the browser developing tools, the request contains all data, so the server-script can read and return the data. no problems so far.

when i try to export the data, the request sent to the server is missing those additional data. the server script cannot grab them and fails. of couse, you can expect to change all our scripts to catch this problem (which we wont).

problem is, that all existing requests (several thousands) expects those limit/offset params to work properly. otherwise users could read millions of data in one rush, which would kill their browser and (due to memory) our script. your export option (exportDataType = all) seems to use the request without those params (which makes sense), but that sudden change in behaviour (sidePagination: "server"  ==> those parameters are normally essential) kills our scripts. why is the script in case of server-pagination not sending the offset = 0 and limit = "count of items" automatically.

this problem may not hit all developers, but in big apps like our one, hugh data masses are handled and we have problems with suddenly missing parameters/informations.

**Comment by UtechtDustin** [comment]
> why is the script in case of server-pagination not sending the offset = 0 and limit = "count of items" automatically.

I guess the parameter `all` (of the option `exportDataType`) already explains it, we will export ALL rows.
Just use the noraml export (in the example its called `export basic`, which works quite good in the example.
With that export type we also dont send a new ajax request, as we already have the data in the table (which was requested with limit and offset).

**Comment by snoopy72** [comment]
I can easily live with that (and understand your decision and way of thinking).

So, we'll use an own export function with the upcoming new version and the own buttons. waiting very long time for that.

Hopefully your new version will be ready for download soon :)

Ticket closed.

**Comment by UtechtDustin** [comment]
We're working on it :-)
