### ISSUE TITLE
How to globally overwrite/extend a toolbar icon

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5311]
I believe I have done this before but can't seem to get it working anymore.

I'm trying to globally change an icon like:

```
    $.extend($.fn.bootstrapTable.icons, {
      clearSearch: 'fa-times',
    });
```
but it doesn't change the icon. What would be the proper way to do this?

Example: https://live.bootstrap-table.com/code/marceloverdijk/4828

**Comment by marceloverdijk** [comment]
🙈  https://stackoverflow.com/questions/62224717/how-to-change-the-clearsearch-icon-with-bootstrap-table

It should have been:

``` 
 $.extend($.fn.bootstrapTable.defaults.icons, {
    clearSearch: 'fa-undo'
  });
```

**Comment by UtechtDustin** [comment]
Just as hint, you also can use the [icons option](https://bootstrap-table.com/docs/api/table-options/#icons).
Example: https://live.bootstrap-table.com/code/UtechtDustin/4829
