### ISSUE TITLE
new button feature has problems with uppercases in names

### ISSUE THREAD

**Issue by snoopy72** [wenzhixin/bootstrap-table#5312]
**Description**  

trying to implement your new button feature (VERY BIG THANKS FOR THAT !!!), i am struggeling about some (smaller) issues.

using camelcase names for the buttons, the button sorting won't work as i would expect. due to your usage of camelcases in the docs and examples (and because it much easier to read) we used those form of naming too.

Example:
https://live.bootstrap-table.com/code/snoopy72/4831

When you rename both names "btnTest" into "btntest" (all lower case), then the button sorting is working fine.

Did i miss something (found nothing in the docs right now) or is it a (small) bug ?

**Comment by UtechtDustin** [comment]
Yeah we also found that, its on our todo we was not sure how we handle it internal.
We decided to release the feature/the new version first and improve that later.
So its a small "bug".

**Comment by wenzhixin** [comment]
In JavaScript, it is not very good to use a `string` in option like `Array` or `Function`.
https://live.bootstrap-table.com/code/wenzhixin/4839
