### ISSUE TITLE
strange behaviour using the new button feature

### ISSUE THREAD

**Issue by snoopy72** [wenzhixin/bootstrap-table#5313]
**Description**  

trying to implement your new feature (buttons in the upper right section), i am struggeling about this problem.

of course only the new version (v1.18.0) is used and caches have been cleared.

i am not able to reconstruct this problem in your example-code-system, but my local example with this problem is similar to https://live.bootstrap-table.com/code/snoopy72/4831, so i tried nothing too special :)

i am using these settings for the following screenshot (rest of code like in my example 4831):

```js
buttons: "buttonsFunction",
buttonsOrder: "['btntest','refresh','columns','export','autoRefresh']",
```
![bt001](https://user-images.githubusercontent.com/10332064/93706566-dbe90800-fb27-11ea-90d5-cd1e4e0a87d4.jpg)

reading the html with the browser developer tools i get:

```html
<div class="columns columns-right btn-group pull-right">
   <button class="btn btn-default" type="button" name="refresh" aria-label="Ansicht neu laden" title="Ansicht neu laden"><i class=" las la-sync"></i> </button>
   <div class="keep-open btn-group" title="Spalten auswählen">
      <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-label="Columns" title="Spalten auswählen">
        <i class=" las la-columns"></i>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
         <li class="dropdown-item-marker" role="menuitem"><label>[cut the 10 field to shorten code]</label></li>
      </ul>
   </div>
   <div class="export btn-group">
      <button class="btn btn-default dropdown-toggle" aria-label="Export" data-toggle="dropdown" type="button" title="Daten exportieren">
        <i class=" las la-download"></i>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
         <li role="menuitem" class="" data-type="csv"><a href="#">CSV</a></li>
         <li role="menuitem" class="" data-type="txt"><a href="#">TXT</a></li>
         <li role="menuitem" class="" data-type="excel"><a href="#">MS-Excel</a></li>
         <li role="menuitem" class="" data-type="xml"><a href="#">XML</a></li>
      </ul>
   </div>
   <button class="btn btn-default" type="button" name="0"></button>
   <button class="btn btn-default" type="button" name="1"></button>
   <button class="btn btn-default" type="button" name="2"></button>
   <button class="btn btn-default" type="button" name="3"></button>
   <button class="btn btn-default" type="button" name="4"></button>
   <button class="btn btn-default" type="button" name="5"></button>
   <button class="btn btn-default" type="button" name="6"></button>
   <button class="btn btn-default" type="button" name="7"></button>
   <button class="btn btn-default" type="button" name="8"></button>
   <button class="btn btn-default" type="button" name="9"></button>
   <button class="btn btn-default" type="button" name="10"></button>
   <button class="btn btn-default" type="button" name="11"></button>
   <button class="btn btn-default" type="button" name="12"></button>
   <button class="btn btn-default" type="button" name="13"></button>
   <button class="btn btn-default" type="button" name="14"></button>
   <button class="auto-refresh btn btn-default" type="button" name="autoRefresh" title="Auto"><i class=" las la-clock"></i></button>
</div>
```

that list of 15 times `<button class="btn btn-default" type="button" name="0"></button>` is irritation for me.

disabling the table-options "buttons" and "buttonsOrder", the buttons are displayed like normal (then of course without my new button ...). so this behaviour seems to has its origin within the button feature.

disabling only the option "buttonsOrder" keeps that strange buttons and only changes the ordering (what is not wondering):
![bt002](https://user-images.githubusercontent.com/10332064/93706781-24a1c080-fb2a-11ea-8d17-6605e4eb658c.jpg)

my fault ?

**Comment by UtechtDustin** [comment]
As you cant reproduce it on the editor i guess its  a problem of your environment.
But to be sure, please upload somewhere a zip file with a minimal example.

**Comment by snoopy72** [comment]
I would agree, if there would not be created those `<button class="btn btn-default" type="button" name="10"></button>` buttons, which are not from my source - then they would not disappear on disableing the "buttons".

They are created somewhere inside BT.

**Comment by UtechtDustin** [comment]
Sure its possible that BT create it, but maybe its a Cache issue or something like that.
We cant fix it if we cant reproduce it, so please upload a example and we will fix it.

**Comment by snoopy72** [comment]
No Cache, but i tested a bit deeper:

to avoid conflicts by duplicate names (if there could be a 2nd function "buttonsFunction") i renamed the function to something stupid but surely single: "abc12345".

```js
buttons: "abc12345",
```

```js
function abc12345() {
        return {
            btntest: {
```

Et voila:

![bt003](https://user-images.githubusercontent.com/10332064/93712165-62b3da00-fb54-11ea-9944-879c65ece672.jpg)

Do you also see the problem ? No ?

I changed the name to "abc". Result:

![bt004](https://user-images.githubusercontent.com/10332064/93712194-9db60d80-fb54-11ea-8d18-87de6a46ed70.jpg)

How should I with my sources provocate THAT stange behaviour ?
There are exact as many buttons as the function name is charaters long.

**Comment by UtechtDustin** [comment]
So there is no "bug", you just use a wronge scope.
Example with wrong scope: https://live.bootstrap-table.com/code/UtechtDustin/4832

So i agree we should not create that weired buttons if someone use the wrong scope.
Thanks for analyze that!

**Comment by snoopy72** [comment]
Your're right.

Pulling the definition inside the creation, it is working:

```js
buttons: function() {
            return {
                btntest: {
                    icon: 'las la-search-plus',
                    text: "Erweiterte Suche",
                    attributes: {
                        title: 'Search all users which has logged in the last week'
                    },
                    event: function btnTestFunction () {
                        alert("test");
                    }
                }
            };
        },
```
