### ISSUE TITLE
Allow custom icons

### ISSUE THREAD

**Issue by minsis** [wenzhixin/bootstrap-table#5317]
**Description**  
I dont like, nor use font awesome, but here you force users to font awesome. Because of this I have to import two different icon libraries.

**Comment by UtechtDustin** [comment]
You can overwrite the [icons](https://bootstrap-table.com/docs/api/table-options/#icons), which means you already can use your own icons.

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/#options/icons-prefix.html

**Comment by minsis** [comment]
Apologies, I had missed this in the docs despite me searching. Appreciate the info however, the icons dont seem to load. In inspection the correct class is now specified, but the icon doesn't load into the builtin toolbar. I made sure the exact code that bootstrap-table build for the icon works by adding it randomly somewhere on the page. So I'm not sure what might be causing this.

![image](https://user-images.githubusercontent.com/11248197/93812853-ca7f2900-fc17-11ea-883d-8e50689e67df.png)


This shows that the icon does show up when loaded in html outside the bootstrap table.
![image](https://user-images.githubusercontent.com/11248197/93813043-1e8a0d80-fc18-11ea-9eec-dea3bcaf69ea.png)

**Comment by UtechtDustin** [comment]
If the html is correct it can't be an issue with the bootstrap-table i guess.
Please provide us an example using our [editor](https://live.bootstrap-table.com/), then we can try to help.

**Comment by minsis** [comment]
[Here is the example](https://live.bootstrap-table.com/code/minsis/4866)

You can see inside inspection window that the HTML for the button is there for the icon, but the icon doesn't display inside the button. However, using the same HTML outside of the bootstrap table the same set of icons will show up.

**Comment by UtechtDustin** [comment]
I guess the problem is that your icon library only add icons to elements which exists when the document is ready.
Which means it cant add icons to new created elements (in that case the buttons).
So its an issue of the used library not of the bootstrap-table.

**Comment by minsis** [comment]
Thanks I appreciate your taking the time to look at this. Just wanted to update this if anyone finds themselves with the same issue using friconix library. I spoke with the developers of the icon library and all icons on the page can be refreshed using ```friconix_update();```.

So I used this into an bootstrap-table event for load success:

```javascript
$datatable.on('load-success.bs.table', () => {
  friconix_update();
})
```
