### ISSUE TITLE
when enabling data-buttons it adds additional blank buttons

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#5320]
when enabling data-buttons it adds additional blank buttons

https://live.bootstrap-table.com/example/options/buttons-prefix.html

**Comment by UtechtDustin** [comment]
I guess you should read the [documentation](https://bootstrap-table.com/docs/api/table-options/#buttons)..
You defined css classes as string (?!), but it need a function or a function name which returns an object?

**Comment by wenzhixin** [comment]
@UtechtDustin it's the example error, I have fixed this error.

**Comment by UtechtDustin** [comment]
@wenzhixin oh okay, i didnt checkt it. I was to confused because he wrote about `buttons` and `buttons-prefix` at the same time :D
