### ISSUE TITLE
data-cell-style apply in cardview

### ISSUE THREAD

**Issue by i-m-d** [wenzhixin/bootstrap-table#5324]
**Description**  

The attribute data-cell-style is working perfect in table-view but when change to card-view the spplied style disapeared, for example:

in table view function cellStyle works, add class "hecha" or "desconocida" to corresponding cell

`1) <td class="hecha" style="">Realizada</td>`

`2) <td class="desconocida" style="">Desconocida</td>`

but if i change to card view, this class is not applied to the corresponding cell so the data has no style:

`1) <div class="card-view"><span class="card-view-title" style="">Estado</span><span class="card-view-value">Realizada</span></div>`
`2) <div class="card-view"><span class="card-view-title" style="">Estado</span><span class="card-view-value">Desconocida</span></div>`

It would be very interesting that the cell-style would be applied to the data in both views, so the data with css style will look same.

NOTE: sorry for my bad English.

**Comment by UtechtDustin** [comment]
Example: https://live.bootstrap-table.com/code/UtechtDustin/4886
