### ISSUE TITLE
MultiSort not allowing to change order

### ISSUE THREAD

**Issue by snoopy72** [wenzhixin/bootstrap-table#5326]
**Bootstraptable version(s) affected**:
Current version (1.18.0)

**Description**  
when i initialized the multisort, there are two problems:

1. the sorting is not displayed (f.eg. by icons) in the columns
2. the user is not able to change or set the sorting (click on the icpn and the modal is without function)

**Example**  
https://live.bootstrap-table.com/code/snoopy72/4873

**Possible  (optional)**  

1. show the current sorting (semi prio)
2. allow the user to change to sorting / columns / ordering winthin the modal (high prio)

**Comment by UtechtDustin** [comment]
Please dont use the bug issue template, as this is not a bug just a "missing" feature.

**Comment by snoopy72** [comment]
When the user can open a modal by clicking the button and then there is not functionality ... that is a "new feature" request ? ;)

ok, then it was using the wrong template.
So, currently this function is not usable ?

**Comment by UtechtDustin** [comment]
Oh okay, i misread that.
I have read that the user is not able to sort the sorting (like with arrow down/top buttons).

With html init it works: https://live.bootstrap-table.com/code/UtechtDustin/4890
We will check that!

**Comment by snoopy72** [comment]
Sometimes it is fun to develop software, right ?
Working is not working - and the user always find the not working way ;) we know it well, too.

We use the js init and are not able to change it, because the BT is defined basically in the central init script and then pnly modified within the subscripts. Thansk for your recheck.

**Comment by UtechtDustin** [comment]
@snoopy72 
You defined the sortPriority as string not as array, also your columns are not sortable (missing `sortable: true`).
Example: https://live.bootstrap-table.com/code/UtechtDustin/4891

There is still a issue with `sidePagination: "server"`, i also try to figure it out!

**Comment by snoopy72** [comment]
@UtechtDustin 
> also your columns are not sortable (missing sortable: true).

I'll check and update that in our sources. I think it would be easier to users if BT set that option automatically when the column is used within the multisort array, not ?
