### ISSUE TITLE
Filter by tag

### ISSUE THREAD

**Issue by CamilleHUmusic** [wenzhixin/bootstrap-table#5328]
Hello everyone,

I'm trying to filter my table with filterBy method. First i have 2 selects to filter my rows.
I have no problem with my first select because he match exactly with the content of a column (artist name).
But my second select is a list of tag, and on my tag's column sometimes i have something like "tag1, tag2, tag3".

I don't know what method i can use to filter by only one tag on a column where sometimes there is a lot of tags ?

Thank you for your help and have a nice day :)

Cheeeers :)

**Comment by UtechtDustin** [comment]
Should be possible with a [customSearch](https://bootstrap-table.com/docs/api/table-options/#customsearch).

**Comment by CamilleHUmusic** [comment]
Hello, i tried a lot of things with no result, i think i need help :)

customSearch works fine, i can search a tag in my tag column. But in the example customSearch is trigger with the input search. I'm trying to trigger customSearch when i change my custom select and i don't find the eventlistener who do that :/

**Comment by UtechtDustin** [comment]
I create a basic [example](https://live.bootstrap-table.com/code/UtechtDustin/4911) for you.
I hope it helps you, to test it just filter first for  `stars > 200` and `dog` then you see 3 rows, now filter for `stars > 1000` then you only see 2 rows.

This example is made only with the `filterBy` method with the `filterAlgorithm: custom`.

**Comment by djhvscf** [comment]
The previous example of @UtechtDustin is very good but has a typo in the dropdowns. Please see this example which is almost the same https://live.bootstrap-table.com/code/djhvscf/4913

**Comment by UtechtDustin** [comment]
I close this issue, because we got no more response from you.
Also we provided an example for you.
If you still need help, just ask.

**Comment by typo3ua** [comment]
@UtechtDustin ... @djhvscf ... 
:( ...these examples do not work
