### ISSUE TITLE
both search and column sort enabled but not working

### ISSUE THREAD

**Issue by tamirh67** [wenzhixin/bootstrap-table#533]
I get the full list everytime, unsorted...anyone has an idea why?

here is a row from the data (fake data ofcourse)
{"id":54,"customer_id":1,"first_name":"Larry","last_name":"Smith","mobile_phone":"1 765 483 4832","work_phone":"1 232 320 8822","home_phone":"1 768 938 3211","email1":"Larry@larry.com","email2":"","fax":"","address1":"brook boulevard 240","address2":"","city":"Boston","state":"MA","country":"United States","zipcode":"76543","itin":"3092384234","drivers_license":"","website":null,"birth_date":"1965-01-05","notes":null,"created_at":"2015-01-16 17:50:27","updated_at":"2015-01-16 17:50:27","profilePictID":0,"middle_name":"","company":null,"displayName":null,"openingBalance":null,"since":null,"facebook":null,"linkedin":null,"OID":5,"ReportingDatePref":0,"PaymentMethodPref":0,"PaymentPrefDate":0}

**Comment by djhvscf** [comment]
Can you share us your code??

**Comment by wenzhixin** [comment]
can you provide jsfiddle?

**Comment by x3uqm4** [comment]
I have same issue.

JSON Data:
{"total":"3","rows":[{"id":"2","ad_soyad":"Burak Hurata","tcno":"11111111111","firma":"Nokvir Yaz\u0131l\u0131m","santiye":"Eski\u015fehir","sorumlu":"Alper","gorev":"SEO","kan_grubu":"B RH(-)","tel_no":"053333333333","giris_tarih":"2015-03-13","cikis_tarih":"","ozluk_url":"..\/img\/ozluk\/5182_burakhurata_ozluk_4.jpg","saglik_url":"..\/img\/sagliktetkik\/5985_burakhurata_sagliktetkik_10962249_10204893265684951_530266068_n.jpg","isg_url":"..\/img\/isg\/7269_burakhurata_igs_10962249_10204893265684951_530266068_n.jpg","saglik_tarih":"2015-03-13","resim_url":"..\/img\/fotograflar\/5969_burakhurata_foto_10962249_10204893265684951_530266068_n.jpg","aktif":"0"},{"id":"6","ad_soyad":"Alper Sapan","tcno":"12345678911","firma":"Nokvir Yaz\u0131l\u0131m","santiye":"Yaz\u0131l\u0131m","sorumlu":"Burak Hurata","gorev":"PHP Developer","kan_grubu":"0 RH(+)","tel_no":"05396972833","giris_tarih":"2015-03-27","cikis_tarih":"2015-03-09","ozluk_url":"..\/img\/ozluk\/4852_alpersapan_ozluk_10935612_1607718906106138_714285264_o.jpg","saglik_url":"..\/img\/sagliktetkik\/561_alpersapan_sagliktetkik_10935612_1607718906106138_714285264_o.jpg","isg_url":"..\/img\/isg\/9279_alpersapan_igs_10935612_1607718906106138_714285264_o.jpg","saglik_tarih":"2015-03-12","resim_url":"..\/img\/fotograflar\/1150_alpersapan_foto_10935612_1607718906106138_714285264_o.jpg","aktif":"1"},{"id":"7","ad_soyad":"Atakan ","tcno":"12345678911","firma":"Nokvir Yaz\u0131l\u0131m","santiye":"Grafik","sorumlu":"Burak Hurata","gorev":"Grafik ","kan_grubu":"0 RH(+)","tel_no":"1451564564564","giris_tarih":"2015-04-04","cikis_tarih":"2015-04-25","ozluk_url":"..\/img\/ozluk\/2759_atakan_ozluk_10935612_1607718906106138_714285264_o.jpg","saglik_url":"..\/img\/sagliktetkik\/9895_atakan_sagliktetkik_10935612_1607718906106138_714285264_o.jpg","isg_url":"..\/img\/isg\/5544_atakan_igs_10935612_1607718906106138_714285264_o.jpg","saglik_tarih":"2015-03-10","resim_url":"..\/img\/fotograflar\/1344_atakan_foto_10935612_1607718906106138_714285264_o.jpg","aktif":"1"}]}

json.php:
$calisanlar = SQL::query("SELECT * FROM calisanlar");
$count= SQL::getVar("SELECT COUNT(id) FROM calisanlar");
$result= $calisanlar->fetchAll();
$test= array(
    'total' => $count, 
    'rows' => $result,
    );

echo json_encode($test);

and main.php

<?php
$limit = $_GET['limit'];
$offset = $_GET['offset'];
?>

<table id="table" 
           data-toggle="table" 
           data-toolbar="#toolbar" 
           data-search="true" 
           data-show-refresh="true" 
           data-show-toggle="true" 
           data-show-columns="true" 
           data-show-export="true" 
           data-show-pagination-switch="true" 
           data-pagination="true" 
           data-side-pagination="server" 
           data-url="json.php">
        <thead>
        <tr>
        	<th data-field="id" data-sortable="true">#</th>
        	<th data-field="ad_soyad" data-sortable="true">Ad Soyad</th>
        	<th data-field="tcno" data-sortable="true">TC Kimlik No</th>
        	<th data-field="firma" data-sortable="true">Firma</th>
        	<th data-field="santiye" data-sortable="true">Şantiye</th>
        	<th data-field="sorumlu" data-sortable="true">Sorumlu</th>
        	<th data-field="sorumlu" data-sortable="true">Görev</th>
        	<th data-field="kan_grubu" data-sortable="true">Kan Grubu</th>
        	<th data-field="giris_tarih" data-sortable="true">Giriş Tarihi</th>
        	<th data-field="cikis_tarih" data-sortable="true">Çıkış tarihi</th>
        	<th data-field="saglik_tarih" data-sortable="true">Sağlık Raporu Tarihi</th>
        	<th data-field="aktif" data-sortable="true">Durum</th>
        	<?php if (session::getSession("nvfw_yetki") >= 2) echo "<th data-field=\"operate\"
                data-formatter=\"operateFormatter\"
                data-events=\"operateEvents\">İşlem</th>"; ?>
        </tr>
        </thead>
    </table>


    <script>
    var $table = $('#table'),
        $remove = $('#remove');
    $(function () {
        $table.on('check.bs.table uncheck.bs.table check-all.bs.table uncheck-all.bs.table', function () {
            $remove.prop('disabled', !$table.bootstrapTable('getSelections').length);
        });
        $remove.click(function () {
            var ids = $.map($table.bootstrapTable('getSelections'), function (row) {
                return row.id
            });
            $table.bootstrapTable('remove', {
                field: 'id',
                values: ids
            });
            $remove.prop('disabled', true);
        });
    });
    function operateFormatter(value, row, index) {
        return [
            '   <a href="calisanislem.php?id=' + row.id + '&islem=duzenle"><span class="glyphicon glyphicon-pencil"></span></a>',
            '   <a href="calisanislem.php?id=' + row.id + '&islem=sil" onclick="return confirm(\' ' + row.id + ' numaralı personel silinsin mi? \')"><span class="glyphicon glyphicon-trash"></span></a>',
        ].join('');
    }
</script>


header.php includes this;

<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="../js/bootstrap.min.js"></script>
<script src="../js/bootstrap-table.js"></script>
<script src="../js/extensions/filter/bootstrap-table-filter.js"></script>
<script src="../js/extensions/sorting/bootstrap-table_natural-sorting.js"></script>

**Comment by wenzhixin** [comment]
Help to convert it to a jsFiddle pls @x3uqm4 , I want to help but I have no enough time to test everyone's problem.
templates: http://bootstrap-table.wenzhixin.net.cn/examples/#basic

**Comment by djhvscf** [comment]
Any update here??

**Comment by wenzhixin** [comment]
In our example: http://issues.wenzhixin.net.cn/bootstrap-table/, both search and column sort enabled is working OK. Close this issue.
