### ISSUE TITLE
TreeGrid only working on 1.18.0 ?

### ISSUE THREAD

**Issue by athorr** [wenzhixin/bootstrap-table#5330]
**Bootstraptable version(s) affected**: 1.15.5

**Description**  I cannot make treegrid extension work

Hi everybody.
First thank you for your amazing plugin, i love it.

I have a problem with the treegrid extension. When i try to make it work, nothing happens. When i put the last version of bootstrap table (1.18.0). I tried with the online example, and even with the 1.17.0 or the 1.16.0, the tree grid dont load (the bootstrap table still works fine)

If i had no choice, i will upgrade my version of the plugin, but i would prefer not have to do it.

Is there something i do wrong ?

**Comment by UtechtDustin** [comment]
The treegrid extension works fine for me for 

- 1.15.5 ([example](https://live.bootstrap-table.com/code/UtechtDustin/4884))
- 1.16 ([example](https://github.com/wenzhixin/bootstrap-table/issues/5330))
- 1.17.1 ([example](https://live.bootstrap-table.com/code/UtechtDustin/4883))

So it seems its an issue of your setup, please provide us an example using our editor.

**Comment by athorr** [comment]
Hello UtechtDustin 
Thanks for the quick answser.

Here is an [example ](https://live.bootstrap-table.com/code/athorr/4903) of my setup

I just took the code in the doc. The only difference is that I load data with data parameter directly in the code, and not with the url parameter (with an external json)
When I switch to version 1.18.0 it works.

**Comment by UtechtDustin** [comment]
As we dont support/update older version we cant help with that.
Can i ask why you dont want to update a newer (or the newest) version ?

**Comment by athorr** [comment]
I work on an extranet which is based on a html/css/js theme.
A lot of plugins are packed in a minified js. If I upgrade bootstrap-table, I need to upgrade all the packed plugins. And I would have to verify if all the developped functionalities still work. 

I managed to resolve my problem. Instead of making one big request, then filter the data and use data parameter in BT, I just make one request by table using url parameter.
