### ISSUE TITLE
getSelections() returns wrong data if search query

### ISSUE THREAD

**Issue by BarryHauser** [wenzhixin/bootstrap-table#5332]
**Bootstraptable version(s) affected**:
Using the https://unpkg.com/bootstrap-table@1.18.0 for vuejs

**Description**  
I'm getting wrong data when I use the search bar, I get the index of what it would be if no search query. 

**Example**  
If I type "MD" into search and select the first one. The `getSelections()` will return the data of the first row if there was no selection.

![image](https://user-images.githubusercontent.com/40282988/94034316-de4d9b00-fd8f-11ea-9c63-bbf8fb416a57.png)

**Possible  (optional)**  

I guess you are querying the index and returning the index of the data in the table. Really you should be querying the `getData()` function that returns the data displayed.

**Comment by UtechtDustin** [comment]
It seems its a vue depended issue, as the [example](https://live.bootstrap-table.com/example/methods/get-selections.html) works fine.
@wenzhixin please check that.

**Comment by BarryHauser** [comment]
![image](https://user-images.githubusercontent.com/40282988/94038951-1c00f280-fd95-11ea-9590-07493993d581.png)
Example dosent work

**Comment by UtechtDustin** [comment]
Youre right, after a cache clear i also have the issue!

**Comment by BarryHauser** [comment]
Last version works! 1.17.1! So it a bug in 1.18.0

**Comment by gabbdias** [comment]
it's still broken!

**Comment by UtechtDustin** [comment]
@gabbdias its currently in the develop branch, its not released yet!
