### ISSUE TITLE
Extension "Group By V2" should use the field formatted value, not the raw value

### ISSUE THREAD

**Issue by snoopy72** [wenzhixin/bootstrap-table#5336]
**Description**  

Using the extension "Group By V2", i can define the grouping field:
```js
groupBy: true,
groupByField: "type",
```

In this example, the field "type" reads an integer and has a formatter function, to translate those integer into a human readable code:
```js
field: "type",
title: "Example",
formatter: function(value,row) {
     return "Example translation into something different: " + value);
}
```

Unfortunately the extension is using the integer to label the grouping row, which looks weird and confuses the (final) users.

I created an example (not with int, but with strings) to show the problem:
https://live.bootstrap-table.com/code/snoopy72/4895

**Comment by UtechtDustin** [comment]
Its already possible with the [groupByFormatter option](https://bootstrap-table.com/docs/extensions/group-by-v2/#groupbyformatter).

Examples:
- https://live.bootstrap-table.com/code/UtechtDustin/4908
- https://live.bootstrap-table.com/code/UtechtDustin/4909

**Comment by snoopy72** [comment]
@UtechtDustin 
Thank you. i overread that feature.

**Comment by snoopy72** [comment]
@UtechtDustin 
But something seems not to work with data requested from a server.

following example from our application:

the column "Tarif" is assigned to the field "type", which contains short text. 
that value is being translated in the columns field formatter. no very complex.
i wrote the content 1st, followed by "=" and then the translation:

![ex001](https://user-images.githubusercontent.com/10332064/94463831-dc377200-01bd-11eb-9a2b-844d48328930.jpg)

```js
groupBy: true,
groupByField: "type",
groupByFormatter: function(value,index,data) { 
  return translate(value); // which returns for "freight" = "Fracht"
},

[...]

},{
  field: "type",
  title: "Tarif",
  formatter: function(value,row) {
    return translate(value); // same as above
  }
},{
```

to be honest, i expected something more "grouped" and not three groups with the same name / id / value.

**Comment by UtechtDustin** [comment]
I'm not sure what do you mean, maybe you can explain it in a other way?
(Optional kannst du es natürlich auch auf deutsch erklären)

**Comment by snoopy72** [comment]
Thanks for your offer to explain it in german, but i would like to keep issues in english, so that everybody can follow later.

the app requests data from our server in json. works fine and no problems so far.

defining the "groupBy" in one table (the example from above) brings that multiple grouping for the same value:

field "type" always contains "freight" (translated for all others: Fracht) in the readable lines (photo above)
so i would expect, that all those four lines in this example would be written below the grouping "Fracht".

but instead one line is grouped, then the next two and line line at the end.
i think, "grouping" (and i think that's how the extension works) should show one group "Fracht" with all four lines below.

-- the content above in a shorter german version --
Die vom Server gelesenen JSON Daten enthalten im Feld "type" vier Mal den Wert "freight", welcher dann in "Fracht" übersetzt wird. Anstatt das die Extension alle vier Zeilen in eine Gruppe fasst, habe ich drei Gruppen zu je 1,2 und 1 Zeile.

**Comment by UtechtDustin** [comment]
Could you create an example (using our editor) for that usecase ?
Normaly it should work fine, the extension should group the rows based on one column (or more based on value of that column).

Example: https://live.bootstrap-table.com/example/extensions/group-by-v2.html
As you can see its grouped using the shape column.

**Comment by snoopy72** [comment]
https://live.bootstrap-table.com/code/snoopy72/4962

```js
<table id="table"></table>
<script>
  $(function() {
    $("#table").bootstrapTable({
      url: "json/data6.json",
      groupBy: true,
      groupByField: "color",
      columns: [{
        field: "shape",
      },{
      	field: "color",
        formatter: function(value,row) {
            return "Color: " + value;
        }
      },{
      	field: "area",
      }],
    })
  })
</script>
```

BTW: Do you have an json delivering server for your examples ?

**Comment by snoopy72** [comment]
Ticket is closed. OK or shall i create a new one ?
