### ISSUE TITLE
Group By v2 Collapsing does not collapse detail view expanded row

### ISSUE THREAD

**Issue by togradywk** [wenzhixin/bootstrap-table#5339]
**Bootstraptable version(s) affected**:
1.18.0

**Description**  
Utilizing detail view and group by v2 extension, if a row detail view is expanded, and then the group by row is clicked to collapse, the detail row is not collapsed

**Example**  
https://live.bootstrap-table.com/code/togradywk/4905

**Possible  (optional)**  
I resolved this issue by amending line 7639 in bootstrap-table.js:
        `if ($tr.attr('data-parent-index')) {
          $tr.after('<tr class="detail-view" data-parent-index="${$tr.attr('data-parent-index')}"><td 
                      colspan="${$tr.children('td').length}"></td></tr>');
        } else {
          $tr.after(Utils.sprintf('<tr class="detail-view"><td colspan="%s"></td></tr>', $tr.children('td').length));
        }`
Not sure if its acceptable to accommodate extensions in the primary bootstrap-table js.  

**Additional context**  
Chromium 83

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf what do you think, should we collapse the detail view if the group was collapsed or not ?
Im not sure about that.

**Comment by togradywk** [comment]
Just to clarify a bit, by collapse detail view, I just mean hide that row when the others are hidden.  I agree that the detail view itself should remain on the page, just hidden.  

To me, the detail view is a child to the parent row that created it, so it makes sense to hide that detail view in the grouping when the group itself is collapsed.

**Comment by UtechtDustin** [comment]
I understand what do mean, im just thinking if it makes sense to also close the detail views :-)

**Comment by djhvscf** [comment]
I think we should close all detail views under the collapsed group
