### ISSUE TITLE
(Question): How can I use bootstrap-table to ajax load data from Struts2 action?

### ISSUE THREAD

**Issue by davidgjm** [wenzhixin/bootstrap-table#534]
Hi,

How can I use bootstrap-table to ajax-load data from Struts2 action? I tried to use method within my callback function, but it turned out a mess. Could you share such an example? I'm not aware of such example in your public examples set. Thank you.

//The above is for non-Chinese users.
我的问题就是怎么从 Struts2 action 异步加载数据，如果能够公布一个类似用到 struts2 上的例子，对我这样的新手来说会节省不少痛苦。尝试了好几次了，每一次成功的，还有服务器端的分页怎么在 bootstrap-table 上配置？谢谢！

**Comment by wenzhixin** [comment]
I am not familiar with struts2, but i guess you can handle the .do request as RESTful interfaces. If you have any examples, you can send to this repo: https://github.com/wenzhixin/bootstrap-table-examples.

**Comment by wenzhixin** [comment]
你看下那些例子以及通过 Chrome 的 Network 来查看发送的请求是什么，然后服务器处理一样就可以了，希望可以帮到你。
