### ISSUE TITLE
How to make a sticky footer?

### ISSUE THREAD

**Issue by Shaun-Yao** [wenzhixin/bootstrap-table#5341]
Is there a extendtion that can fix the footer and the scroll-x.

**Comment by djhvscf** [comment]
We have this [extension](https://bootstrap-table.com/docs/extensions/sticky-header/) which will sticky the header. At this moment we don't support sticky footer.

For scroll-x we have this [extension](https://bootstrap-table.com/docs/extensions/fixed-columns/)

**Comment by Shaun-Yao** [comment]
I set the height to meet my needs .

**Comment by Shaun-Yao** [comment]
It turns out that I only need to set the height to meet my needs.
