### ISSUE TITLE
Problem with post-body.bs.table event and showRow/hideRow methods...

### ISSUE THREAD

**Issue by sipi41** [wenzhixin/bootstrap-table#5347]
Hello and thank you for your attention to a problem I have.  I'm a newbie :-) and first, I would like to congratulate you for this amazing work! every time I see a project like yours I think I will need 2 lives to study all these!  I have been using your product for the first time the whole past week, at the beginning, it was a little scary but it's very intuitive. Ok, let's work! :-)

**I think I found a problem** with the result of an event, let me explain.  Basically, I have a list of distribution locations, (called points), some of these are active, others are inactive. I did generate the list, then using the "post-body.bs.table" event I used something like this to hide the "inactive" ones...:

`$('#tablaLocations').on('post-body.bs.table', function () {               

                var datos = $(this).bootstrapTable('getData');

                for (var i = 0; i < datos.length; i++) {
                    var row = datos[i];
                    var boton = $('#ActiveBtn-' + row.id);
                    var currentStatus = boton.attr('data-dev-currentstatus');

                    if (currentStatus == 'inactive') $(this).bootstrapTable('hideRow', { index: i });
                }
            });` 
Basically using the event, I loop through all my rows, if found its inactive then it hides the row. So far so good.  Now I built a button on top of my table called "all location / active only" which is basically a switch, and when I click this button, it almost do the same thing as before, except this time if the button is on, then it tries to show and/or hide the row.

The problem is, I have 45 locations, the last one is inactive, so when the pages loads I get 44 locations.  When I try to show the hidden location again using
 
`$('#tablaLocations').bootstrapTable('showRow', { index: 44 });`

it does not show any error or the row, it just does nothing, like it never fires. I did notice that if I don't use the event **post-body.bs.table** to hide the rows at the page load, then everything works as supposed, I can use the button on top to show or hide inactive locations.

Would you please help me? am I using the right event at the beginning? I tried to look for another option other than "post-body.bs.table" but did not see any other option... or is this a bug? how can I share my HTML code with you so you can make a test?  

Thank you very much for all your help!

**TEMPORARY WORKAROUND**: What I did is come back to my old css... I did mark each row <TR> with the database ID, so I did call the **$('#1234').css('display', 'none');** to hide it and **$('#1234').css('display', 'table-row');** to show it again, it works but the question is, why is not working as expected?

**Comment by UtechtDustin** [comment]
I'm closing this issue as we dont got an example from you within 7 days.
If you still need help please provide us an example (using our [editor](https://live.bootstrap-table.com/)) and we will reopen the issue.
