### ISSUE TITLE
Q: Scroll to a specific entry in the table when pagination active?

### ISSUE THREAD

**Issue by fallingrock** [wenzhixin/bootstrap-table#535]
*Sorry if this isn't the right place to ask a question ... but I couldn't find a better place.*

I have a table with client side pagination ... when the table loads, I would like it to position the table to a specific entry in the table.  Before I was using pagination, I just tagged each row with a &lt;a name="xxx"&gt; and it positioned correctly.  Now, obviously, the specific tagged row may not be on the current page.

Thanks!

**Comment by wenzhixin** [comment]
I think you can see the methods examples, maybe these will help.issues. http://wenzhixin.net.cn/bootstrap-table

**Comment by fallingrock** [comment]
I've looked at the examples ... but I couldn't find one that used the position method.

**Comment by wenzhixin** [comment]
Got it, it seems that bootstrap table does not support  what you want when you active pagination feature.

**Comment by wenzhixin** [comment]
Maybe you can use `selectPage` method to go to your data page first.

**Comment by dabros** [comment]
I know this is closed, but im trying to make up a public function in bootstrap-table.js or even just callback code to do something similar to this.

At the very least i want to be able to find the page number to go to. I have a function to find matching data row, but cant figure out how to get pageNumber from that.

My current idea is use my onPostPagination() function, called anytime pagination is updated, and check there by calling to a function like:

``` javascript
BootstrapTable.prototype.getRowByItemId = function (row_itemid) {
        console.info('BootstrapTable.selectRowByItemId started', { row_itemid: row_itemid, data: this.options.data });

        if (this.options.itemId !== undefined ) {
            $.each(this.options.data, function(d_i, d_val){
                console.log('data row', [d_i, d_val]);
                if (d_val[this.options.itemId] == row_itemid)
                    return dval;
            });
        }
        else
            console.error('BootstrapTable.selectRowByItemId error: itemId must be defined', { 'row_itemid': row_itemid, 'this.options.itemId': this.options.itemId });

        return null;
    };
```

But obviously this doesnt do anything for pagination index. Now, i could assume that d_i (the index in this.options.data) is the row number (assuming also this accounts for sorting) then try to find pagination number_per_page and assume page number from that.

Does this sound like best idea, or is there a better idea out there?
