### ISSUE TITLE
Question about shorted lacale

### ISSUE THREAD

**Issue by kerog** [wenzhixin/bootstrap-table#5351]
**Description**  
Hi, in PR#1033 (https://github.com/wenzhixin/bootstrap-table/pull/1033) was introduced shorted way to set locale instead of 
`locale: 'en-US'`
 just simple 
`locale: 'en'`
In version 1.18.0 I cannot set shorted version of locale eg. 'pl' instead 'pl-PL'.

**Example (optional)**  
Can't provide example (in sandbox locale is not loading (always in English))

**Comment by UtechtDustin** [comment]
In #1033 and in the current sourcecode (https://github.com/wenzhixin/bootstrap-table/blob/develop/src/constants/index.js#L585-L588) you can see that it the shorted locale was implemented only for 'en-US'.

**Comment by kerog** [comment]
@UtechtDustin 
Do you think, if I add to all language files something like bellow example for polish (line 6)
```
$.fn.bootstrapTable.locales['pl-PL'] = {
```
to this
```
$.fn.bootstrapTable.locales['pl-PL'] = $.fn.bootstrapTable.locales['pl'] {
```
?

**Comment by UtechtDustin** [comment]
Yes something like this should work.

**Comment by kerog** [comment]
Ok, I would try.
