### ISSUE TITLE
Advanced tooltips

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5361]
I'm building my bootstrap-tables with javascript, so basically only have `table` element with an id without a `thead` or other details.

Now to some of the columns I would like to add additional `data` attributes like `data-toggle="tooltip" data-placement="top" title="Tooltip on top"`. Is that possible?

**Comment by djhvscf** [comment]
It should. Let me find an example

**Comment by UtechtDustin** [comment]
Sure its possible, you can set the key `_data` with an array of the data attributes you want.

Example: https://live.bootstrap-table.com/code/UtechtDustin/5004

**Comment by marceloverdijk** [comment]
@UtechtDustin thx, but I'm looking to put on the actual header (not on a data row), e.g.:

https://live.bootstrap-table.com/code/marceloverdijk/5011

**Comment by UtechtDustin** [comment]
Oh okay, i thought you want it for the rows because you wrote `without a thead`.
So i thinks we dont have a feature for that, yet.
As you can see [here](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L318-L328) we only add some "normal" attributes to the `<th`.

As workaround you can listen to the `postBody` event and then add your tooltip.

**Comment by marceloverdijk** [comment]
OK, yes I was expecting that as I didn't find anything.

https://live.bootstrap-table.com/code/marceloverdijk/5015 I can use the `onPostHeader` event I guess but don't understand how to set the data attributes then..

**Comment by UtechtDustin** [comment]
@marceloverdijk 
Here you have an example (hover over the "item name" column header): https://live.bootstrap-table.com/code/UtechtDustin/5017

**Comment by marceloverdijk** [comment]
Thx @UtechtDustin for the example.

Note one thing is strange, your example contains `$th.attr('data-placement', 'top');` but the actual tooltip is displayed at the bottom.
Also if I change it to `left` it is displayed at the right side. Weird...

**Comment by UtechtDustin** [comment]
The top dont worked because there was not enough space for the tooltip, after adding a `margin-top` it works fine.
Changing it to `left` works for me for both examples.

Example: https://live.bootstrap-table.com/code/UtechtDustin/5018

**Comment by marceloverdijk** [comment]
Thx a lot indeed it was not enough margin. Let's close it now. Cheers M.
