### ISSUE TITLE
Table resizing is not working when the height of table is defined.

### ISSUE THREAD

**Issue by AndreyBarzukov** [wenzhixin/bootstrap-table#5363]
The code
`
$myTable.bootstrapTable('destroy').bootstrapTable({
    height: 380,
    locale: 'RU-ru',
    exportTypes: ['csv', 'excel'],
    data: $data,

    columns: [
      {
        field: 'ItemOperate',
        switchable: false,
        align: 'center',

        events: window.operateEvents,
        formatter: operateFormatter,
      },
      {
        field: 'id',
        title: '&#8470;',
        switchable: false,
        align: 'center',
        valign: 'middle',
        sortable: true,
      },

<...>

    ],
  });
`
When the "height: 380" is deleted it works.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I'm closing this issue as we dont got an example (using our editor) from you.
If this bug still persists, please create an example using our editor and we will reopen the issue.

**Comment by wenzhixin** [comment]
Maybe it's the known issue: https://bootstrap-table.com/docs/extensions/resizable/#known-issues
