### ISSUE TITLE
Serverside pagination not working as expected

### ISSUE THREAD

**Issue by dtolj** [wenzhixin/bootstrap-table#5365]
**Bootstraptable version(s) affected**:
1.18.0

**Description**  
I am setting up serverside pagination. Enabled flags data-pagination="true" and data-side-pagination="server" 
Set data-url="customer/json" as well as data-page-size="25"

my data looks like this: (yes I am duplicated the example)
```
{
  "total": 800, 
  "totalNotFiltered": 800, 
  "rows": [
    {
      "id": 0, 
      "name": "Item 0", 
      "price": "$3"
    }, 
    {
      "id": 1, 
      "name": "Item 1", 
      "price": "$3"
    }...
```
and my Response header. The only difference between my data and example data is that I see a different header.
```
Content-Length: 63043
Content-Type: application/json
Date: Tue, 06 Oct 2020 19:34:40 GMT
Server: Werkzeug/1.0.1 Python/3.6.1
```

*Output:*
All the data loads in the table with correct pagination at the bottom and row count. However when I click on next page, it reloads the entire dataset.

*Expected output:*
Only display 25 rows at a time.

Also: when I load the example data in my code, it works as expected. so there is something going on in the data.
https://examples.wenzhixin.net.cn/examples/bootstrap_table/data

**Comment by UtechtDustin** [comment]
> All the data loads in the table with correct pagination at the bottom and row count. However when I click on next page, it reloads the entire dataset.

What do you mean with "reloads the entire dataset" ?
You're server has to decide which data he sends back to the browser.

Please provide us an example (using our [editor](https://live.bootstrap-table.com/)).

**Comment by dtolj** [comment]
Here is the edit: https://live.bootstrap-table.com/code/dtolj/5045
Thanks.

**Comment by dtolj** [comment]
OK, its making more sense now. I updated the server code to handle query strings.
Thanks.

**Comment by UtechtDustin** [comment]
No problem your welcome :-)
