### ISSUE TITLE
filter-control combined with fixed height gives incorrect layout with non-standard font-size (minified version only)

### ISSUE THREAD

**Issue by david-oscarsson** [wenzhixin/bootstrap-table#5367]
Bootstrap table version: 1.18.0

First of all, this issue seems to be solved already, but only if I use the non-minified version "bootstrap-table-filter-control.js". Using the minified version, "bootstrap-table-filter-control.min,js", still contains this issue.  
EDIT: Although the non-minified version is different, the same issue still occurs with the non-minified version.

When using a bootstrap table using fixed height, and using the "filter-control" extension, the fixed table body panel gets the incorrect position, if using text styling that overrides Bootstrap defaults, e.g. a different font-size.
In my case, I use a smaller font size than the default. This results in a blank gap between the table header and the table body, and the bottom border of the fixed table body is placed incorrectly, striking through the last visible row in the table data.

Example in the Online editor:
https://live.bootstrap-table.com/code/david-oscarsson/5044

My guess is that it has to do with a fixed pixel size defined in "bootstrap-table-filter-control.js" row 135 (beginning with ".on('post-body.bs.table'," - the header height is set as "$tableHeader.css("height","89px")". But as I previously mentioned, this is only in the minified JS, the non-minified version contains a fix, although the same problem occurs using this version.

Confirmed in browsers: Chrome 85, Edge 85, Internet Explorer 11 (all on Windows 10)

**Comment by UtechtDustin** [comment]
This issue is fixed in the newest version.
Example: https://live.bootstrap-table.com/code/UtechtDustin/12278
