### ISSUE TITLE
Option to switch column group on and off in a table with complex header

### ISSUE THREAD

**Issue by jonm01** [wenzhixin/bootstrap-table#5368]
**Description**  

As of now it is not possible to hide entire column group when there is a multi level table header 

https://bootstrap-table.com/docs/api/column-options/#switchable

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I'm closing this issue, because we got no example within 7 days.
If you still need help, please provide us an example.
