### ISSUE TITLE
Binding to functions loaded with requireJS

### ISSUE THREAD

**Issue by bragma** [wenzhixin/bootstrap-table#537]
Hi,
I am non a JavaScript guru so pardon me if the question is trivial. I'm using bootstrap-table with sorters and formatters. The functions I use for formatting and sorting are defined on an external js file, and loaded with requireJS. If I define the columns in the code, using the "sorter" and "formatter" properties, everything works.
I'd like to move some of the table definition to the html file instead, but I am not able to bind sorting and formatting to the functions because I don't know how to specify the function names in the "data-formatter" and "data-sorter" fields. It seems to me that bootstrap-table looks for functions defined on window only.
Is there any trick you can suggest? I'd rather avoid to define the functions globally.
Thanks!

**Comment by djhvscf** [comment]
I think you can check this.. http://bootstrap-table.wenzhixin.net.cn/ @bragma

**Comment by bragma** [comment]
@djhvscf Can you please point me to the relevant section? I know that page well, and it seems to me that all examples bind to global functions. In my case, I am using the tables inside a knockout component. I'd rather avoid defining globals just for that.
Thanks!

**Comment by wenzhixin** [comment]
Hi @bragma, you are right, bootstrap-table looks for functions defined on window only, it supports namespace also, but I do not know whether that can help. In your case, I think you can via JavaScript instead of data-attribute, I will consider this case. If you have any advice, you can tell me.
