### ISSUE TITLE
Table not showing Font Awesome icons when using formatter and filter-control for the same column

### ISSUE THREAD

**Issue by martinbarilik** [wenzhixin/bootstrap-table#5371]
**Bootstraptable version(s) affected**: Tested only with lastest version 

**Description** : When using Font Awesome in custom column formatter and filter-control for the same colum, filter won't show icons of FA

**Example**: https://live.bootstrap-table.com/code/martinbarilik/5061

**Possible  (optional)** : would be nice, if we could have formatted filter acording to values ( etc. icons )

**Comment by wenzhixin** [comment]
Updated example: https://live.bootstrap-table.com/code/wenzhixin/11483

**Comment by wenzhixin** [comment]
Because the native select does not support font-awesome icons. 
A workaround example: https://live.bootstrap-table.com/code/wenzhixin/11484
So let's close this issue.
