### ISSUE TITLE
Set dynamically strict column search on click

### ISSUE THREAD

**Issue by ghost** [wenzhixin/bootstrap-table#5372]
Hi @wenzhixin,

Currently, I am looking for a way where I can set a strict/non-strict search to the specific column dynamically on the click of two different buttons.

below is my code :

 if (data != 'user') {
        $("#table_div").bootstrapTable({
            filterStrictSearch: true,
         });
    } else{
         $("#table_div").bootstrapTable({
            filterStrictSearch: false
         })
    }

Can you please help me out with this?

Thank you :)

**Comment by wenzhixin** [comment]
The [`refreshOptions` option](https://bootstrap-table.com/docs/api/methods/#refreshoptions) can solve your problem.
https://examples.bootstrap-table.com/#methods/refresh-options.html
