### ISSUE TITLE
Method getSelection return wrong row when using search

### ISSUE THREAD

**Issue by uralmetal** [wenzhixin/bootstrap-table#5374]
**Bootstraptable version(s) affected**:

1.18.0

**Example**  

![image](https://user-images.githubusercontent.com/43093017/95594773-132a4500-0a54-11eb-8e17-0d26bb21915c.png)
https://examples.bootstrap-table.com/#methods/get-selections.html

**Comment by UtechtDustin** [comment]
Thank you for the bug report, we already fixed that bug (#5346) and the bugfix is in our develop branch.
