### ISSUE TITLE
border on tbody not match with theader

### ISSUE THREAD

**Issue by wandyirawan** [wenzhixin/bootstrap-table#538]
hi, i have issue again. i have 11 column and i create that with js.
my column editable, so value base input. in example header size also match with body.
but in my table not like that.. so header auto size not work.. and after edit done.. my border header and  body not match.. 

how i can fix this? thanks before.

**Comment by wenzhixin** [comment]
Hi, you can try to use editable extension or `resetView` method to solve your problem.

**Comment by wandyirawan** [comment]
thanks wenzhixin... Close
