### ISSUE TITLE
ajax and url

### ISSUE THREAD

**Issue by alonbn22** [wenzhixin/bootstrap-table#5382]
Hey,
I use bootstrap table to show information from MSSQL table using PHP.
I currently use a PHP script to import the data to the table but I want to use the data-url and data-ajax for this.
how can I connect my DB to the table?
in your examples you use a static JSON file or anther site.

thanks
Alon

**Comment by UtechtDustin** [comment]
There are some example in the documentation, do you checked them ?
You have to use the [url](https://bootstrap-table.com/docs/api/table-options/#url) option which is a path to your json file OR to your PHP script which fetch the data from your MSSQL Database and returns  it as json.

**Comment by alonbn22** [comment]
I did try putting my script  as the url but it didn't worked. I'll try convert it to JSON.
thank you

**Comment by UtechtDustin** [comment]
What do you mean ?
You just have to use a json (in the correct structure), please provide us an example what do you tried!

**Comment by alonbn22** [comment]
I don't have the conde because it's in a close environment, but I pulled the data from sql, and than echo it to the table (this is the static way I did it).
when I tried to make it dynamic I converted the data to JSON and tried to  echo it in the end. (data-url="SCRIPT_NAME.PHP")

**Comment by UtechtDustin** [comment]
As i already said provide us an example, you also can post (a censord) the json which will be returned by you php script.

**Comment by UtechtDustin** [comment]
I close this issue as we got no example. If still need help, please provide us an example.
