### ISSUE TITLE
how to merge cells into data-url(JSON)?

### ISSUE THREAD

**Issue by Yangchanhyo** [wenzhixin/bootstrap-table#5383]
I'm importing data from the table into the data-url command.
A situation in which the value changes fluidly, not fixed, depending on the situation.
Therefore, if the table is drawn, the function of automatically merging is needed if the top and bottom are the same.
`[{rows=[
             {
              reg_num=770909-2, 
              sqno=1, 
              **name = Kim,** 
              aptitude_point=100
              },
              {              
              reg_num=801009-1, 
              sqno=2, 
              **name = Kim,** 
              aptitude_point=23
             }]}]`

If there is a json like this, I would like to merge names.
![mergecellshelp](https://user-images.githubusercontent.com/19181743/96116069-da421280-0f22-11eb-8c1c-9fad2c34b305.png)

Because, depending on the situation, if someone updates or deletes it, the order changes the order. I don't know how.
If the values above and below the column are the same, I would like to ask if there is any way to merge automatically.

**Comment by wenzhixin** [comment]
I think there is no automatically merging function. You can merge the cells by yourself.
Example: https://live.bootstrap-table.com/code/wenzhixin/11548
