### ISSUE TITLE
Issue with server-side data when columns have special characters

### ISSUE THREAD

**Issue by nwong44** [wenzhixin/bootstrap-table#5387]
**Bootstraptable version(s) affected**:

1.80
**Description**  

UPDATE: It seems like this is an issue with some other special characters as well, such as '/'
After the initial load, the table doesn't rerender for subsequent queries if a column title has a round bracket
The data I used was from https://examples.wenzhixin.net.cn/examples/bootstrap_table/data, however, I just added a bracket to the "Item Name" header in the CSV so it's "Item Name (Foobar)"

I then convert the CSV to JSON like this
` {
            "ID": 40,
            "Item Name (Foobar)": "Item 40",
            "Item Price": "$40 "
        },
        {
            "ID": 41,
            "Item Name (Foobar)": "Item 41",
            "Item Price": "$41 "
        },
` 

How I pass in the JSON to create the column fields
I get the column headers and create the column objects
`
0: {title: "ID", field: "ID"}
1: {title: "Item Name (Foobar)", field: "Item Name (Foobar)"}
2: {title: "Item Price", field: "Item Price"}
`
I use 'refreshOptions' to initialize the columns
`
$('#table-test').bootstrapTable('refreshOptions',{
            columns: columns_objs
        })
`
On load:
![image](https://user-images.githubusercontent.com/62078378/96325590-d7582800-0fdd-11eb-9e42-b39aafc1c921.png)

Here I try to go to the second page with no avail.
![image](https://user-images.githubusercontent.com/62078378/96325599-eccd5200-0fdd-11eb-85a5-e8dc86adecc4.png)
 

**Example**  

**Possible  (optional)**  

**Additional context**

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by djhvscf** [comment]
Hi! There is not any reply, in that case we are going to close this issue. Remember to add an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports).
