### ISSUE TITLE
Javascript 'disabled' when event in my table

### ISSUE THREAD

**Issue by zagloo** [wenzhixin/bootstrap-table#539]
Hello !

In my .js I do some actions when click is detected on td or tr (ajax request for example...or whatever...). 

When I load the page, everything works, but if I do some actions on my bootstrap table like sort the table or change the page of the table, when I click on tr or td, my .js does not work anymore, nothing happened...

What can I do ?

**Comment by wenzhixin** [comment]
You can use the events of the bootstrap table: http://bootstrap-table.wenzhixin.net.cn/documentation/#events to solve your problem.

**Comment by zagloo** [comment]
Hum, I do not understand how it can help me ...?

How to keep active the javascript on the table when whatever is do with bootstrap-table...?

For example, if I do a simple action with javascript like an "alert" when I click on a "td". It works nice when I load the page at begining and  if I do nothing like sort or reserach or change page of table, but if I do one of these action on the table and after I click on the "td", nothing happened...

Sorry for this question but I don't understand...

**Comment by zagloo** [comment]
Am I the only one in this case ?
