### ISSUE TITLE
always export two files

### ISSUE THREAD

**Issue by Shaun-Yao** [wenzhixin/bootstrap-table#5390]
**Bootstraptable version(s) affected**:

1.18.0
**Description**  

always export two files when use bootstrap-table-export extension
**Example**  

        showExport: true,
        exportDataType: "all",
        exportTypes: ['xlsx'],
        exportOptions: {
            ignoreColumn: [0],
            fileName: function () {
                return 'deposit'
            }
        }
**Possible  (optional)**  

**Additional context**  

It is normal to use v1.15.5.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I'm going to close this issue as we don't got a example from you.
