### ISSUE TITLE
Export hidden columns

### ISSUE THREAD

**Issue by senobarii** [wenzhixin/bootstrap-table#5391]
I need to export hidden columns. kindly could someone guide me how to do it? Thanks in advance.

**Comment by UtechtDustin** [comment]
Hey, i think you are searching for the column option [forceExport](https://bootstrap-table.com/docs/extensions/export/#forceexport) :-)

**Comment by senobarii** [comment]
I have created a new custom button for export but it does not export hidden column. I have tested  forceExport  not working. kindly advice?
