### ISSUE TITLE
Set FilterBy, SearchText and pageNumber all at once ?

### ISSUE THREAD

**Issue by martinbarilik** [wenzhixin/bootstrap-table#5392]
Cookie doesn't save filterBy value so i am willing to implement it myself, but i can't see any solution to set filterBy, searchText and pageNumber all at once. I can do  
`
table.bootstrapTable({ pageNumber: 2, searchText: 'text' });`

but when i do 
```
let table = $('#table');
table.bootstrapTable({ pageNumber: 2, searchText: 'text' });
table.bootstrapTable('filterBy', { status: 'not_registered' });
```

the pageNumber and searchText are ignored or reset ( one of those ) 

Is there any possible solution to set it on initialization of BS table ? Something like 

`
table.bootstrapTable({ pageNumber: 2, searchText: 'text', filterBy: {status: 'not_registered'})  
`
this?

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by martinbarilik** [comment]
I had to move on. Closing it. Sorry to bother
