### ISSUE TITLE
implement parent-child

### ISSUE THREAD

**Issue by senobarii** [wenzhixin/bootstrap-table#5394]
how to implement parent-child table that search and export working on them? if share me an example I really appreciate it. Thanks

**Comment by senobarii** [comment]
any update or response? I am really confused how is the best way to implement parent-child structure using bootstrap table that both search and export function work. 

search: user must able to search that displays all possible entries under its parent.
export: user must able to export all rows either parent or child.

I tried a lots seems a bit tricky to have these functionalities together. Thanks.

**Comment by UtechtDustin** [comment]
I close this issue because it's quite old.
If you still need help please let us know and we try to help you.
