### ISSUE TITLE
UI issue with dropdown inside a cell

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#5395]
I noticed this problem in case a cell has a dropdown (see screenshot). The dropdown in the last row overflows the table div and causes the scrollbar to appear. The problem is caused by the overflow in this CSS rule

```
.bootstrap-table .fixed-table-container .fixed-table-body {
    overflow-x: auto;
    overflow-y: auto;
    height: 100%;
}
```
What is the right way to solve this? I would avoid overriding that rule.

https://live.bootstrap-table.com/code/antonioaltamura/5148

![Online-Editor-Bootstrap-Table](https://user-images.githubusercontent.com/6325475/96991606-9f426f00-1520-11eb-9004-d4b2264e0bbf.png)

**Comment by wenzhixin** [comment]
These links may be helpful:
https://github.com/wenzhixin/bootstrap-table/issues/472#issuecomment-317806274
https://stackoverflow.com/questions/31029300/how-to-append-a-single-dropdown-menu-to-body-in-bootstrap

**Comment by wenzhixin** [comment]
Working well in bootstrap v4: https://live.bootstrap-table.com/code/wenzhixin/5218

**Comment by macoto-liu** [comment]
Hi this still not work for dropdown rendered in fixed columns. even I use bootstrap v4

See https://www.loom.com/share/99062c019a344f8e9b9d7544d2a2c841?from_recorder=1

Any workaround?

**Comment by wenzhixin** [comment]
The option `boundary: 'window'` or `data-boundary="window"` can solve the problem.
https://live.bootstrap-table.com/code/wenzhixin/5271
