### ISSUE TITLE
Default sorting fails with strings containing numbers

### ISSUE THREAD

**Issue by bragma** [wenzhixin/bootstrap-table#540]
Hi,
I'm trying to sort a column but I receive an error:

SCRIPT438: Object doesn't support property or method 'localeCompare'
File: bootstrap-table.js, Line: 531, Column: 17

The cause is the default sorting function, which tries to convert a value to a number, but then when comparing it tries to use "localeCompare" on the converted value.

This happens if the other comparison member is not a function. Consider this dataset:

var data = [
    {
        "name": "myname"
    },
    {
        "name": "1234"
    }
];

In this case "1234" is converted to a number but then, when comparing "myname" and 1234, it assumes that both are string because "myname" is not a number.

https://jsfiddle.net/e3nk137y/650/

**Comment by bragma** [comment]
Please review the PR. :)

**Comment by wenzhixin** [comment]
OK, I will check it out as soon as possible.

**Comment by wenzhixin** [comment]
Merged.
