### ISSUE TITLE
Incorrect row unchecked on unchecking after applying search filter.

### ISSUE THREAD

**Issue by supmanyu** [wenzhixin/bootstrap-table#5403]
**Bootstraptable version(s) affected**: v1.18.0

**Description**  
Steps to reproduce: 
1. Select all rows using checkbox.
2. Search for some keyword.
3. Uncheck a row from the search results.
4. Clear search box.
5. The table unchecks using index, not value. So, if first row was unchecked from search results, then first row is also unchecked from selections made in Step 1.

**Example**  
https://live.bootstrap-table.com/code/supmanyu/5191

**Comment by supmanyu** [comment]
Fixed label has been added, but the PR hasnt been merged yet.

**Comment by A-Costa** [comment]
Having a related issue:
selecting a row after doing a search, then deleting the search, results in the wrong row selected.
The rows get selected based on their index at time of selection (which changes when doing a search, sorting or filtering in any other way).

Also #5420 seems related.

That feels like a major bug. Will follow this conversation about a solution. I personally like #5414 approach of having a UID for each row.
