### ISSUE TITLE
bootstrap Table after page refresh sorted columns filter are not stored in cookies

### ISSUE THREAD

**Issue by srujan1729** [wenzhixin/bootstrap-table#5407]
I have tried below method for to save bootstrap cookies table date after page refresh(https://live.bootstrap-table.com/example/extensions/cookie.html) 

but I could able to store the sorted data after page refresh.` setTimeout(function() {
		getSubrackOpticalChassis(document.getElementById("subrack").value);
	}, 60000);`

**Comment by srujan1729** [comment]
<table class="table config-table" 
								id="optical-link-listing" data-show-columns="true" data-cookie="true" data-cookie-id-table="saveId" data-pagination="true" data-search="true" >
								
									<thead>
										<tr>
											<th class="warning-col"></th>
											<th data-sortable="true">Device A</th>
											<th data-sortable="true">Location A</th>
											<th data-sortable="true">Optical Status A</th>
											<th class="no-border"></th>
											<th class="warning-col"></th>
											<th data-sortable="true">Device B</th>
											<th data-sortable="true">Location B</th>
											<th data-sortable="true">Optical Status B</th>
										</tr>
									</thead>
									<tbody>
                              {{#PROG_DATA}}
                              <tr id="{{linkNum}}">
                                 <td id="{{linkNum}}-alarmA" class="text-center">{{LocPortAlarm}}</td>
                                 <td id="{{linkNum}}-deviceA">{{device_a}} <span>{{ResetButton}}</span></td>
                                 <td id="{{linkNum}}-deviceALoc">{{device_a_loc}}</td>
                                 <td id="{{linkNum}}-deviceARange">{{power_range_a}}</td>
								 <td class="no-border text-center">
								  <a id="{{linkNum}}-details" href="#" onclick="{{DynamicLink}}" class="btn btn-sm btn-default btn-circle tipper" title="Click for link performance details">
                                    <i class="fa fa-arrows-h"></i>
								  </a>
								 </td>
                                 <td id="{{linkNum}}-alarmB" class="text-center">{{RmtPortAlarm}}</td>
                                 <td id="{{linkNum}}-deviceB">{{device_b}}</td>
                                 <td id="{{linkNum}}-deviceBLoc">{{device_b_loc}}</td>
                                 <td id="{{linkNum}}-deviceBRange">{{power_range_b}}</td>
							  </tr>
                              {{/PROG_DATA}}
									</tbody>
  
  
  $(document).ready(function(){

   //
   // Tooltips
   //
   $('.tipper').tipsy({fade: true, gravity: 'n'});
    

   var max = 0;
   $(".settings-group-label").each(function(){
      if ($(this).width() > max)
      max = $(this).width();    
   });
   $(".settings-group-label").width(max);


	
	$('#optical-link-listing').bootstrapTable({
	    pagination: true,
        search: true,
        trimOnSearch: false,
		stateSave: true
 
    });
	
	setTimeout(function() {
		getSubrackOpticalChassis(document.getElementById("subrack").value);
	}, 60000);
    
    $('#link-performance-details').bootstrapTable({
        pagination: true
    });

	
});

**Comment by djhvscf** [comment]
@srujan1729 we need an example using that we could execute easily

**Comment by UtechtDustin** [comment]
I close this issue as we dont got an example (using our Editor).
If you still need help please provide us an example and we will reopen the issue.
