### ISSUE TITLE
Center checkbox when row on multiple line

### ISSUE THREAD

**Issue by david-ieong** [wenzhixin/bootstrap-table#5409]
**Description**  

Center the checkbox selector like the '+' button to open detail view.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by david-ieong** [comment]
![image](https://user-images.githubusercontent.com/6533573/97457929-824fd680-193a-11eb-8ecd-815c310364e2.png)


Here a screen example

**Comment by david-ieong** [comment]
Problem from my code sry :) I close the ticket
