### ISSUE TITLE
Javascript file not injecting in the Angular project.

### ISSUE THREAD

**Issue by DatIsNiels** [wenzhixin/bootstrap-table#5412]
**Bootstraptable version(s) affected**:

1.18.0
**Description**  

I am experiencing issues with installing bootstrap-table on my Angular project. It looks like the javascript does not inject into my project. I was able to fix the issue by injecting the js file to my body when loading in an Angular component. But the next issue was that after i tried using an click event to something in the table it did not execute the function defined in my component. It looks like the table is not reactive after creating it.

**Possible  (optional)**  
There should be a way to properly injecting the javascript file into my application

**Additional context**  
Angular version: 10.1.0
Bootstrap version: 4.5.0
Jquery version: 3.5.1
Popper version: 1.16.1

**Comment by UtechtDustin** [comment]
I'm sorry but we currently dont support angular, see the duplication #5200.
