### ISSUE TITLE
Option to not htmlSafe column or leave the content as it was 

### ISSUE THREAD

**Issue by martinbarilik** [wenzhixin/bootstrap-table#5415]
**Description**  
I am trying to implement my own actions column in EMBERjs, what is my goal is to have button with action on every row. The button will open bootstrap modal with ember-google-maps element specific to the row.

What is my problem is that the initialization of bootstrap-table is removing action of button when rendered.

```
<link href="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.css" rel="stylesheet">

<div class="row">
    <div class="col mx-0 mx-md-3 box">
        <div class="toolbar mt-2">
            <h2>Waiting List</h2>
        </div>

         <table id="table" data-toggle="table">
            <thead>
                <tr>
                    <th data-align="center" data-sortable="true" data-field="id">ID</th>
                    <th data-align="center" data-sortable="true" data-field="email">Email</th>
                    <th data-align="center" data-sortable="true" data-field="hasDevice">Device</th>
                    <th data-align="center">Actions</th>
                </tr>
            </thead>
            <tbody>
                {{#each @list as |object|}}
                <tr>
                    <td>{{object.id}}</td>
                    <td>{{object.email}}</td>
                    <td>{{object.hasDevice}}</td>
                    <td><button class="btn btn-success" type='button' {{on 'click' (fn @showPosition 1)}}>{{concat 'Show ' object.id}}</button></td>
                </tr>
                {{/each}}
            </tbody>
        </table>

        <button class="btn btn-success" type='button' {{on 'click' (fn @showPosition 1)}}>Show</button>
        <button class="btn btn-success" type='button' {{on 'click' (fn @showPosition 2)}}>Show</button>
    </div>
</div>
```

I have this simple table but can't figure out to leave the actions column as it is. I can't use data-formatter, i need to have a reference to id of element. Is there an option to not format the column ( i think the initialization is doing htmlSafe on every column) so the action stays there? If i remove data-toggle="table" from code above, it obviously works as intended.

Thanks for reply

**Comment by UtechtDustin** [comment]
I'm sorry this is not possible (with the emberjs syntax), the bootstrap table collect the data from your table, saves it internal and then renders the bootstrap-table.
For events you have to use the [events](https://bootstrap-table.com/docs/api/column-options/#events) option.
