### ISSUE TITLE
toolbar search includes detail view

### ISSUE THREAD

**Issue by senobarii** [wenzhixin/bootstrap-table#5418]
Hi, I am trying to implement customSearch to able search detailview as well, could share me some idea on how to implement it? Thanks.

**Comment by UtechtDustin** [comment]
You have to use the [customSearch](https://bootstrap-table.com/docs/api/table-options/#customsearch) option, which means you have to implement the search by yourself.

**Comment by wenzhixin** [comment]
Example: https://live.bootstrap-table.com/code/wenzhixin/5296

**Comment by senobarii** [comment]
> You have to use the [customSearch](https://bootstrap-table.com/docs/api/table-options/#customsearch) option, which means you have to implement the search by yourself.

yes i already researched on it but i need some examples that give me clear picture how to do it ...
