### ISSUE TITLE
there is no example available for custom-view extension

### ISSUE THREAD

**Issue by nesoler** [wenzhixin/bootstrap-table#5419]
is it possible to post a usage example?

**Comment by UtechtDustin** [comment]
Sure we will add an example, as soon we have time for that.
Thank you for reporting the missing example.

**Comment by wenzhixin** [comment]
Added docs and example:
https://bootstrap-table.com/docs/extensions/custom-view/
https://examples.bootstrap-table.com/#extensions/custom-view.html
