### ISSUE TITLE
Provide data via ajax call directly

### ISSUE THREAD

**Issue by KarstenD** [wenzhixin/bootstrap-table#542]
HI,

I hope anyone can help as I am new to this ... :)
atm i receive data for the bstable via an ajax call of a php script which returns the data as needed:

	var ajax_data = "action=list";

	$.ajax({
		type : "post",
		url : "php/admin/admin_user.php",
		data : ajax_data,
		success : function(response) {

			$(html_object).bootstrapTable({
				data : $.parseJSON(response)
			});

			$(html_object).bootstrapTable('hideLoading');

		},
		async : false
	});

The php return the data as an array from a db table:
    $rows = array();
    while ($row = mysql_fetch_array($result, MYSQLI_ASSOC)) {
        $rows[] = $row;
    }
    echo json_encode($rows);
...

Is it possible to do this directly as in the samples without the seperate ajax call ?

            $('#table').bootstrapTable({
                method: 'post',
                url: 'ajax/book.ajax.php',
 .....

In my solution I have to do the "refresh" manually by recalling the ajax call and a "load", the refresh can't do anything the way i went ... :) 

Sorry if this is anywhere in the docs and I didn't see it.
Any help would be appreciated.

Karsten

**Comment by bragma** [comment]
Yes, it's possibile. You don't need to parse the json data unless it is encoded as a string. Bootstrap-table expects a JSON with format: [{...},{...},...]. I think you need to call $.parseJSON only if you send a string containing the actual JSON, such as "[{...},{...},...]" (mind the double quote).

**Comment by KarstenD** [comment]
HI Bragma,
thanks for the reply. I retired and finaly I just had to set the method to "GET" as i need to pass parameters to the php function, so now ...
	
    $('#tblUser').bootstrapTable({
        method: 'get',
		url : "php/admin/admin_user.php?action=list",
        cache: false,
        striped: true,
        pagination: true, ...

works fine.

**Comment by bragma** [comment]
Good! :+1: 
I think you can keep your url "clean" and pass the "action=list" parameter using the "queryParams" option.

**Comment by KarstenD** [comment]
To be sincere, I have no idea how to use (code) it as it should be a function ?

**Comment by wenzhixin** [comment]
Yes @KarstenD , it is a funtion, you can look at the documentation: http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by cafi** [comment]
@KarstenD 
Do you mind providing me the necessary files/scripts as an example?
