### ISSUE TITLE
getSelections doesn't work as expected

### ISSUE THREAD

**Issue by renardudezert** [wenzhixin/bootstrap-table#5420]
**Bootstraptable version(s) affected**:
1.18.0

**Description**  
When using data-search on table or data-sortable on column, the returned value(s) is/are not correct.

**Example**  
On the [getSelections example](https://live.bootstrap-table.com/example/methods/get-selections.html), just enter 5 on the search input, select the first line (5) and click on getSelections button. 
It will display id 0 (and not 5 as expected)

**Comment by tapainc** [comment]
If it helps, I have also found this when using the filterBy method produces a similar effect.

**Comment by mathendr** [comment]
I just found this problem today. v 1.16.0 this is not an issue but 1.18.0 it is. If you select the checkbox before sorting it works fine, but if you sort then check a checkbox, the selected element does not stay checked with the correct rows. it shifts around. It even shifted the selected row to a checkbox that was disabled when it was sorting the table.

**Comment by manukieli** [comment]
I have the same issue with version 1.18
You can see example to this link:
- Without uniqueId:  https://live.bootstrap-table.com/code/manukieli/5302
- With uniqueId: https://live.bootstrap-table.com/code/manukieli/5301

In both example is not working.

![Getselection](https://user-images.githubusercontent.com/14294794/98216942-0d882800-1f4a-11eb-9d7e-c65c69fa4a40.gif)

**Comment by djhvscf** [comment]
This could be solve with https://github.com/wenzhixin/bootstrap-table/pull/5414

**Comment by empouras** [comment]
I have the same issue with the latest version. Is the problem fixed after all? And in that case how do we get the fix? It is a bit unclear to me :)

**Comment by jorgeforero** [comment]
(version 1.18) I have the same issue using filterBy.  The getSelections returns wrongs ids values (the returned ids do not corresponds with the checked ones.)

**Comment by jorgeforero** [comment]
(version 1.18) Doing a deep test, I found that if you order the rows by a column tittle, check one row, and get the id, the getSelections returns wrong id as well.
![bug1](https://user-images.githubusercontent.com/14019063/98972581-9bcb5380-24e0-11eb-95cc-1919eb974fd0.png)
Then
![bug2](https://user-images.githubusercontent.com/14019063/98972616-aa196f80-24e0-11eb-8758-9aa301d89e31.png)
