### ISSUE TITLE
表格参数buttonsToolbar，设计的是否为不能自定义

### ISSUE THREAD

**Issue by wxkxklmyt** [wenzhixin/bootstrap-table#5421]
版本：1.18
例如：{buttonsToolbar:'.buttons-toolbar'}会导致整个工具栏实例化失败，但控制台并没有报错。

**Comment by wenzhixin** [comment]
可能用法不对， `.buttons-toolbar` 需要一个空的 div ，用于定义 buttonsToolbar 是位于哪里，例子如下：
https://examples.bootstrap-table.com/#options/buttons-toolbar.html
https://live.bootstrap-table.com/example/options/buttons-toolbar.html
