### ISSUE TITLE
Get Selected row id using search 

### ISSUE THREAD

**Issue by alphasil** [wenzhixin/bootstrap-table#5422]
Hello
I'm having a probelm using search function, i want to search a name, then when i click in that row, i want to have is id, but it gives id from first page pagination, my case, the user is 7º page, the second row using search, when i click in that row it gives the id of fisrt page, record nº2

This is my table
` <table  id="table"
                        data-toggle="table"
                        data-ajax="ajaxUsers"
                        data-search="true"
                        data-pagination="true"
                        data-show-export="true"
                        data-filter-control="true"
                        data-show-refresh="true"
                        data-click-to-select="true"
                        data-maintain-meta-data="true"
                        data-show-toggle="true"
                        data-export-types="['excel','doc']">`

And the way i'm getting the ids

` let selections = [];
        let profId=[];
        function getIdSelections() {
            let $table = $('#table');
            return $.map($table.bootstrapTable('getSelections'), function (row) {
                selections = row.idProfessor;
                console.log(selections);
                return selections;
            });
        }`

![image](https://user-images.githubusercontent.com/5500660/98396880-5decac00-2056-11eb-90a4-8f57ce8fb080.png)

**Comment by UtechtDustin** [comment]
This issue has the same source of error as #5420.
