### ISSUE TITLE
pagination neglect hidden rows

### ISSUE THREAD

**Issue by senobarii** [wenzhixin/bootstrap-table#5423]
Hello

I have some hidden rows that pagination includes them. How can configure it that pagination neglects hidden rows?

**Comment by UtechtDustin** [comment]
I'm not sure what do you try to achieve, please provide us an example (using our [editor](https://live.bootstrap-table.com/)).

**Comment by UtechtDustin** [comment]
I'm closing this issue because we got no example from you within 7 days.
If you still need help please provid us an example.
