### ISSUE TITLE
replacement for getAllSelections ?

### ISSUE THREAD

**Issue by alicocomo** [wenzhixin/bootstrap-table#5429]
**Bootstraptable version(s) affected**:
>1.18.0

**Description**  
getSelections doesn't return correct rows when the table is filtered by the search field. My solution was getAllSelections but this method was removed with 1.18.0. Is there any replacement or workaround ?

**Example**  

**Possible  (optional)**  

**Additional context**

**Comment by alicocomo** [comment]
it is supposed to be question and not a bug - didn't manage to set the label correctly

**Comment by UtechtDustin** [comment]
I guess the option [maintainmetadata](https://bootstrap-table.com/docs/api/table-options/#maintainmetadata) should help you :-)

**Comment by alicocomo** [comment]
maintainmetadata unfortunately doesn't help. even not on the https://examples.bootstrap-table.com/#options/maintain-meta-data.html. 

- search for e.g. "3"
- check both appearing rows
- clear the search field
- the first two rows in the table are checked and not the rows from the previous selection
