### ISSUE TITLE
The searchText contains an old value when searchOnEnterKey is enabled.

### ISSUE THREAD

**Issue by davidvandertuijn** [wenzhixin/bootstrap-table#5430]
**Bootstraptable version(s) affected**:
1.18.0

**Description**  
The searchText contains an old value when searchOnEnterKey is enabled.

**Example**  
Replace "wrong" with your search term (e.g. "test"), and press the Refresh button:

https://live.bootstrap-table.com/code/davidvandertuijn/5392
Example when searchOnEnterKey is **enabled**
Result: "**wrong**"

https://live.bootstrap-table.com/code/davidvandertuijn/5393
Example when searchOnEnterKey is **disabled**
Result "**test**"

**Comment by UtechtDustin** [comment]
I cant reproduce this bug, if i enter `test`, press enter and then press reload the alert shows `test`.

**Comment by davidvandertuijn** [comment]
@UtechtDustin don't press Enter, but click the Refresh button after typing "test".
It should update the searchText by listening to any key, not only enter.

**Comment by UtechtDustin** [comment]
It should only update (and search) after you pressed the enter key.
The option [searchOnEnterKey](https://bootstrap-table.com/docs/api/table-options/#searchonenterkey) is designed for exactly that.

From the Documentation: `The search method will be executed until the Enter key is pressed.`

**Comment by davidvandertuijn** [comment]
In practice the user change the search term, but does not press Enter, instead it press the Refresh button.
The table results would still show the initial results, because the Refresh method does not POST the new .search-input value.

**Comment by UtechtDustin** [comment]
Without a custom implemenation you have 2 ways:

- Use the `searchOnEnterKey` option, then the user have to press enter
- Dont use the Option and the user also dont have to use the refresh button, as the table will search while typing.

But you can also can resolve your problem while using the [buttons](https://bootstrap-table.com/docs/api/table-options/#buttons) option to create a custom "refresh" button which basically only trigger the enter key.

**Comment by davidvandertuijn** [comment]
How do i trigger the Enter search in the button event ?

**Comment by UtechtDustin** [comment]
You have to trigger the event youre self as the table has no method to trigger that (in 99% of the usecases the method is also not needed).

If you need some informations how to trigger a event: https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events
