### ISSUE TITLE
Question: Table with Action buttons / Server Side processing

### ISSUE THREAD

**Issue by jxmccall** [wenzhixin/bootstrap-table#544]
Hi there,
 I am learning, so forgive my ignorance. I want to use the bootstrap tables with the action buttons ( Edit / Remove)  to load and delete data from the server. 

Has anyone integrated this with Laravel php ?

when I click on the edit or delete icon, it correctly shows the row ID in the Alert box. I need to be able to send the row ID back to the server. If anyone has any examples I would greatly appreciate them 

Jeff

**Comment by djhvscf** [comment]
Well @jxmccall I think you can see this issue ( https://github.com/wenzhixin/bootstrap-table/issues/152 ) and then you can see this example ( http://issues.wenzhixin.net.cn/bootstrap-table/#152.html )

**Comment by wenzhixin** [comment]
You can use ajax to handle your actions, after that refresh the table.

**Comment by jxmccall** [comment]
@djhvscf Thank you for your response. I am not seeing how this will work with laravel (most likely lack of knowledge on my part )

@wenzhixin do you have a example of this ?

**Comment by alciakng** [comment]
우왕

**Comment by wenzhixin** [comment]
For example like this:
```js
$.ajax({
    url: 'your url',
    method: 'delete',
    data: {id: selectedId},
    success: function () {
        // ...
    }
});
```
