### ISSUE TITLE
enable editable with click in cell

### ISSUE THREAD

**Issue by WpSlt** [wenzhixin/bootstrap-table#5441]
Hello!
I like your work and I use Table Editable extension as well.
I would like to enable cell value editing by clicking some where in the that cell.
I have found this solution via css:
a.editable, a.editable-click {display:flex; border-bottom: unset }

is there a better way to get the same feature?

Thk!

**Comment by UtechtDustin** [comment]
I close this issue because it's almost 2 years old and the editable extension is kind of deprecated.
If you still need help please provide us an example using our [editor](https://live.bootstrap-table.com/) and we will reopen the issue.
