### ISSUE TITLE
Click Event on detailFormatter area

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#5444]
I want to handle the click event in some elements in `detailFormatter`
See this example:
https://live.bootstrap-table.com/code/antonioaltamura/5422

`onClick()` function on the rows of the table is correctly called.
`onDetailClick` function is not.

Is that supported somehow?

**Comment by UtechtDustin** [comment]
The events options can be used to bind events within the COLUMNS, so its not designed for detailFormatter.
You can listen to the [onExpandRow](https://bootstrap-table.com/docs/api/events/#onexpandrow) and bind a event with jquery/javascript.

**Comment by UtechtDustin** [comment]
I close this issue because we got no more response from you, if you still need help just ask.
