### ISSUE TITLE
data-show-search-clear-button not work with data-height

### ISSUE THREAD

**Issue by JingYongWang** [wenzhixin/bootstrap-table#5446]
**Bootstraptable version(s) affected**:
Online editor

**Description**  
When I search  "Item 0", search input will not clear after click "clear filters" 
If I remove data-height attribute, it will be fine.

**Example**  

https://live.bootstrap-table.com/code/JingYongWang/5430

**Additional context**

**Comment by djhvscf** [comment]
It is fixed here https://live.bootstrap-table.com/code/djhvscf/7411

This is the PR in progress: https://github.com/wenzhixin/bootstrap-table/pull/5583

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/7411
