### ISSUE TITLE
Server side multisort

### ISSUE THREAD

**Issue by MKKari** [wenzhixin/bootstrap-table#5447]
Hi. I am trying to make this multisort extension of bootstrap-table work on server side. It should be possible according to latest information that i have found [here,](https://github.com/wenzhixin/bootstrap-table/issues/2389) yet it throws this error and I can not find any solution.

Thank you in advance!
![image](https://user-images.githubusercontent.com/10134780/99507517-c0fa0f00-2983-11eb-9016-9cd8fe0e41d0.png)

**Comment by wenzhixin** [comment]
Fixed in the develop branch.
Before: https://live.bootstrap-table.com/code/wenzhixin/5466
After: https://live.bootstrap-table.com/code/wenzhixin/5467

Consider releasing a new version soon.
