### ISSUE TITLE
stop sorting table

### ISSUE THREAD

**Issue by alesavelli** [wenzhixin/bootstrap-table#5453]
**Description**  
I'd like to stop my table sorting automatically after setting sortable:false. If I had a sorting set on a column and set sortable:false, the table will go on sorting after values changings. 
If I try setting { sortable:false, sortName:null } at the same time there's still a straightaway sorting (and it will be ok on values changings). So, how can I completely freeze sorting ? Is it a bug ?

**Example (optional)**  
https://live.bootstrap-table.com/code/alesavelli/5509

Check sortable -> sort by name -> uncheck sortable -> click UpdateLine  : lines order change

**Comment by djhvscf** [comment]
So, to understand this.. The expected behavior should be:

Check sortable
Sort by name
Uncheck sortable **Here the table shouldn't sort the data??**

**Comment by alesavelli** [comment]
Yes, that's what I'd like to : completely stop automatic lines reordering.

**Comment by djhvscf** [comment]
Could you elaborate a little bit more about this? Why is your scenario? Since I think this is like an edge case

**Comment by alesavelli** [comment]
Sure, that's my scenario : I have a readonly table users can order as they like. They can also switch to edit mode, and that's where I'd like the table to stop reordering and stay as it is, in order to prevent reordering after values modifications. Otherwise, when a user edits a line by changing the value of the column sorted on, he has its line automatically moved up or down, and this is too much confusing.
Maybe it is an edge case, but isn't there any workaround to switch off reordering once it has been set ?

**Comment by UtechtDustin** [comment]
@djhvscf I guess we are missing a check in the code.
As he enables the sorting, then sorts (which sets the internal sort to DESC or ASC) and then disable the sorting.
After disabling the sorting the internal sort variable should be ignored or not ?

**Comment by UtechtDustin** [comment]
This issue is quite old, i read it again and i think it makes sense to persists the order state after disabling the sort feature.
If you still need this "feature" please let us know your usecase and we will reopen the issue.
