### ISSUE TITLE
Can not sort with background-color

### ISSUE THREAD

**Issue by godofmars** [wenzhixin/bootstrap-table#5454]
I make the "th" red by self, but lost the style after sort

**Comment by djhvscf** [comment]
I think you should use post-header event in order to apply those changes via javascript or using css. Since every time the table is sorted it will recreate the entire table.

Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days if the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
