### ISSUE TITLE
The search does not see a value in the HTML tags

### ISSUE THREAD

**Issue by typo3ua** [wenzhixin/bootstrap-table#5455]
**Bootstraptable version(s) affected**:
- Last version

**Description**  
If i wrap value in the HTML tag then the search does not see a value in the HTML tags if not, then the search work well

**For example:**
```
  function nameFormatter(value, row) {
    var icon = row.id % 2 === 0 ? 'fa-star' : 'fa-star-and-crescent'
    if (row.id === 3) {
      return '<i class="fa ' + icon + '"></i> Price ' + row.price + '00 ' + value + ' amount ' + row.id + ' 1'
    } else if (row.id === 5){
      return '<i class="fa ' + icon + '"></i> Amount ' + row.price + '0<b>0</b> ' + value + '<b>2</b>'
    } else {
      return '<i class="fa ' + icon + '"></i> ' + value
    }
  }
```

**Live example:**    https://live.bootstrap-table.com/code/typo3ua/5519

I do not know is it normal? 

I think it is not good and the search has to search anywhere within fields of the table.

**Comment by wenzhixin** [comment]
The [`searchFormatter`](https://bootstrap-table.com/docs/api/column-options/#searchformatter) column option can solve your problem:
https://live.bootstrap-table.com/code/wenzhixin/6770
