### ISSUE TITLE
refresh 方法带参数无效

### ISSUE THREAD

**Issue by wingson** [wenzhixin/bootstrap-table#5457]
**Bootstraptable version(s) affected**:

从1.5.3 升级到1.18.0，回退到1.17,也一样问题
**Description**  

1、 .bootstrapTable("refresh",{query:{'year':searchYear}});
后台获取到的year一直是 初始化值，更改无效
2、print extension 多行表头下，打印获取的数据顺序会发生错乱。但有可能是设置不符
**Example**  
```html
<button type="button" id="refresh-btn">
  refresh
</button>
<table
  id="table"
  data-toggle="table"
  data-height="460"
  data-pagination="true"
  data-side-pagination="server"
  data-query-params="queryParams"
  data-url="https://examples.wenzhixin.net.cn/examples/bootstrap_table/data">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
</table>

<script>
  function queryParams(params) {
    params.search = 8;
    params.year = 2020;
    return params
  }
  $(function(){
       $("#refresh-btn").click(function(){
         		console.log("dddd");
             $("#table").bootstrapTable("refresh",{query:{year:2019}});
       })
  })
</script>
```

**Possible  (optional)**  

**Additional context**

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wingson** [comment]
init bootstrapTable({
 queryParam:{"year":"2020"}
})
use method refresh
 .bootstrapTable("refresh",{query:{'year':'2019'}});
  in server side can not get param year= 2019,
it is still init value 2020

**Comment by wenzhixin** [comment]
Same as #4596, in your case you need to update the `queryParams` option to solve your problem: https://live.bootstrap-table.com/code/wenzhixin/5838.

---

1.5.4 开始修改了实现方式，你需要修改为使用 `queryParams` 属性来修复你的问题：https://live.bootstrap-table.com/code/wenzhixin/5838
