### ISSUE TITLE
Wrong checkbox behavior in sorted table

### ISSUE THREAD

**Issue by hhutmqiy** [wenzhixin/bootstrap-table#5458]
**Bootstraptable version(s) affected**: 1.18.0

**Description**  

In a sorted table, a checkbox changes the value of a data field in other row as if sorting didn't happen.

**Example**  

A test snippet: https://live.bootstrap-table.com/code/hhutmqiy/5533
When the table is unsorted the checkbox in the row A changes the value field of the row A.
When the table is sorted ascending, it changes the value field of the row B.
When the table is sorted descending, it changes the value field of the row C.

**Possible  (optional)**  

I'm not very familiar with your code, but this fix works for me:
```diff
--- bootstrap-table-orig.js
+++ bootstrap-table.js
@@ -7296,7 +7296,7 @@
 	    key: "_toggleCheck",
 	    value: function _toggleCheck(checked, index) {
 	      var $el = this.$selectItem.filter("[data-index=\"".concat(index, "\"]"));
-	      var row = this.options.data[index];
+	      var row = this.data[index];
 
 	      if ($el.is(':radio') || this.options.singleSelect || this.options.multipleSelectRow && !this.multipleSelectRowCtrlKey && !this.multipleSelectRowShiftKey) {
 	        var _iteratorNormalCompletion10 = true;
```

**Additional context**

**Comment by djhvscf** [comment]
This is fixed in develop branch

**Comment by sunhk25** [comment]
I found this bug still exists.
--- Build 1.18.2
