### ISSUE TITLE
resizable-column doesn't work inside bootstrap modal

### ISSUE THREAD

**Issue by rahulpattanshetty** [wenzhixin/bootstrap-table#5459]
**Bootstraptable version(s) affected**:
1.18

**Description**  
I'm trying to load the bootstrap table inside the bootstrap modal. Bootstrap table loads well but the resizable-column extension won't work here

**Example**  
https://live.bootstrap-table.com/code/rahulpattanshetty/5541

**Comment by djhvscf** [comment]
Your example is working for me. Please review it

**Comment by rahulpattanshetty** [comment]
@djhvscf when you try to resize the columns it won't work in the modal.
