### ISSUE TITLE
Try to keep all data-* attributes when transform from normal table.

### ISSUE THREAD

**Issue by wenzhixin** [wenzhixin/bootstrap-table#546]
#119

**Comment by vicentor** [comment]
We have a case where we use custom attributes on our TRs, but they are removed automatically.

Would `data-href` and `data-uid` be supported? I downloaded the latest version but it still seems to remove all attributes.

Exemple: `<tr href="http://google.ca/" uid="1">`

**Comment by wenzhixin** [comment]
Hi @vicentor , just support data-*.

**Comment by vicentor** [comment]
Hi!
I tried this:
`<tr data-href="users-input.php?id_account=1" data-uid="1">`

And it ends up like this:
`<tr data-index="0">`

**Comment by wenzhixin** [comment]
I think this feature is not release to bootstrap table 1.6 @vicentor. Please use this in next version, I will release a new version soon.

**Comment by vicentor** [comment]
Alright!! Thanks a lot. :)
