### ISSUE TITLE
How to set height via js to enable fixed header?

### ISSUE THREAD

**Issue by evilcousin** [wenzhixin/bootstrap-table#5460]
I would like to display a fixed header in the table. Therefore I set the parameter data-height. so far ok.

How can i set this parameter dynamically with java script, for example after getting the height of the window and adjusting the height of the table dynamically?

Or do i think wrong? i am not the js professional... thank you!

**Comment by djhvscf** [comment]
You could use this method https://bootstrap-table.com/docs/api/methods/#refreshoptions
