### ISSUE TITLE
Editable ext with row action bad action order

### ISSUE THREAD

**Issue by WpSlt** [wenzhixin/bootstrap-table#5461]
Hello!
Very good work realy!
Bu I found an issue using editable extension and click action in row.
windows.operateEvents = { 'click ...
start before onblur of editable field
so we lose modified input value in click action.

Do you have any workarounds?

Thx!

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by WpSlt** [comment]
here you can see that clicking on button in action column when quantity input is on focus get old quantity value in row data
[https://live.bootstrap-table.com/code/WpSlt/5735](url)

**Comment by WpSlt** [comment]
some help please...

**Comment by djhvscf** [comment]
Well, reviewing the behavior I think that is the normal behavior of the editable [plugin](https://vitalets.github.io/x-editable/docs.html)

**Comment by UtechtDustin** [comment]
> Well, reviewing the behavior I think that is the default behavior of the editable [plugin](https://vitalets.github.io/x-editable/docs.html)

^ this.
As workaround you could trigger the blur event you're self.
