### ISSUE TITLE
Filter values wants to be processed with text() function

### ISSUE THREAD

**Issue by Jie-Geng** [wenzhixin/bootstrap-table#5462]
I use extensions/filter function for my page. 
For the table's visualization, I filled every cell with html tags such as 
&lt;a href='some ref'&gt;link&lt;/a&gt;,
or 
&lt;label class='blue-label'&gt;label&lt;/label&gt;

When I use input/select filter, it works awkwardly. 
In my poor opinion, if it processes data through text() function when build filter controls, this can be processed properly without any influence to the normal text-based data. It wouldn't need any other attributes nor methods.

Thanks.

**Comment by UtechtDustin** [comment]
I close this issue, because its almost 2 years old.
Also is this issue easy solvable while using formatters and set the option [searchFormatter](https://bootstrap-table.com/docs/api/column-options/#searchformatter) to `false`.
