### ISSUE TITLE
How do I keep the merged cell when downloading All?

### ISSUE THREAD

**Issue by Yangchanhyo** [wenzhixin/bootstrap-table#5463]
I am writing as an extension plug-in for bootstrap.

Options in the table :
`data-export-types="['excel']"
data-export-data-type="all"`

Merge is being used in the following ways.
`$table.on('load-success.bs.table column-switch.bs.table 
page-change.bs.table', function () {
$(table).bootstrapTable('mergeCells',{
index:index, field:fieldName, 
colspan: colspan, rowspan: count});
})`

When options are all(data-export-data-type="all"),
it won't merge. All merges are cancelled and printed as Excel.
But, data-export-data-type="basic"
Outputs to Excel in merged state.

For all downloads, I want to download them in a merged state.
I would like to ask if there is an option to resolve this issue.?
![100528042-9af22b80-321b-11eb-9b04-79bcf6afeed1](https://user-images.githubusercontent.com/19181743/100677389-416e3600-33ae-11eb-9e38-478e058a903d.png)

**Comment by wenzhixin** [comment]
> Merge is being used in the following ways.
$table.on('load-success.bs.table column-switch.bs.table page-change.bs.table', function () { $(table).bootstrapTable('mergeCells',{ index:index, field:fieldName, colspan: colspan, rowspan: count}); })

In the latest version, you can use `toggle-pagination.bs.table` event to solve your problem:

```js
$table.on('load-success.bs.table column-switch.bs.table page-change.bs.table toggle-pagination.bs.table', function () { 
  $(table).bootstrapTable('mergeCells',{ index:index, field:fieldName, colspan: colspan, rowspan: count}); 
})
```

Working example: https://live.bootstrap-table.com/code/wenzhixin/11489

**Comment by Yangchanhyo** [comment]
@wenzhixin 
Thank you! I'm glad it's updated.
