### ISSUE TITLE
Server Side Footer data

### ISSUE THREAD

**Issue by jarodium** [wenzhixin/bootstrap-table#5465]
**Description**  
My goal is to calculate footer values server side, without having a formatter function on the client side making calculations, regardless of pagination ( my use case is with no pagination whatsoever ). It will just fetch the default "footer" key from the server and render it, in one or two columns I require ( lets say **columnA** and **columnB** )

What should my server issue in order to read the values from the footer, without having them to go through a formatter function?

The example at [](https://examples.bootstrap-table.com/#options/footer-field.html#view-source) and the docs at [](https://bootstrap-table.com/docs/api/table-options/#footerfield) do not supply any hint on which the columns I should supply bootstrap table so, I would like to have some hints on how to achieve this.

My output is something like this:

```json
{
    "count": 1,
    "rows": [
        {
          "id": "1",
          "pr1": "6.00",
          "pr2": "8.00",
        },
        {
          "id": "2",
          "pr1": "6.00",
          "pr2": "8.00",
        }
    ],
    "footer": {
        "total_pr1": "12",
        "total_pr2": "16"
    }
}

```

As you can see, I would like to map **total_pr1** and **total_pr2** to the footer. Do I need something like the "aggs" key in issue #3046 ? Or, at this time, i'm completely dependent on the footerFormatter functions to achieve this?

**Comment by UtechtDustin** [comment]
Should be possible with [footerField](https://bootstrap-table.com/docs/api/table-options/#footerfield).
If you need more help, please let us know!
