### ISSUE TITLE
filter-control doesn't reset filter when select none with cookie activated

### ISSUE THREAD

**Issue by slefol** [wenzhixin/bootstrap-table#5468]
**Bootstraptable version(s) affected**:
1.18.0

**Description**  
With filter-control select, when select none form select, the filter not reset.
(only if includes bootstrap-table-cookie.js)

not issue with previous versions (1.17.1, 1.16.0).

**Example**  
https://live.bootstrap-table.com/code/slefol/5622

**Comment by slefol** [comment]
The same problem occurs with multiple filters. Only removing the first filter works. When deleting a second filter, the table does not update.
(problem also with version 1.18.1.)

**Comment by slefol** [comment]
> The same problem occurs with multiple filters. Only removing the first filter works. When deleting a second filter, the table does not update.
> (problem also with version 1.18.1.)

The problem is still present in version 1.18.2.

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9690

**Comment by slefol** [comment]
> Example with fix: https://live.bootstrap-table.com/code/djhvscf/9690

I confirm that the correction solves the problem

**Comment by francogp** [comment]
This problem is present on 1.20.2

**Comment by UtechtDustin** [comment]
@francogp the fix is not released yet, please wait for the next version.
