### ISSUE TITLE
 data-virtual-scroll

### ISSUE THREAD

**Issue by carles9000** [wenzhixin/bootstrap-table#5472]
Hi masters,

What is the objective of data-virtual-scroll?  If it is faster loading data, then if I set it to true, it is the best performance.  there is something that I do not understand, excuse me.  Maybe the right question is, How does the use of data-virtual-scroll affect me?

Regards and nice weekend.
C.

**Comment by wenzhixin** [comment]
You can compare this two example:

* without virtual-scroll: https://live.bootstrap-table.com/code/wenzhixin/5701
* with virtual-scroll: https://live.bootstrap-table.com/code/wenzhixin/5702
