### ISSUE TITLE
how to custom checkbox inner attributes

### ISSUE THREAD

**Issue by caoguangyao** [wenzhixin/bootstrap-table#5473]
i want to add some attr to checkbox ,then use the follow option 
```
...
columns: [
                {
                    align: 'center',
                    checkbox: true,
                    width: 42,                          // 显示复选框
                    formatter: function (value, row, index) {
                        return '<input data-index="0" name="btSelectItem" type="checkbox" name="order" data-row-name="order" value="'+row.id+'">';
                    }
                }
...
```
how ever shows 2 checkboxes in colums

**Comment by wenzhixin** [comment]
You can use `[idField](https://bootstrap-table.com/docs/api/table-options/#idfield)` and `[selectItemName](https://bootstrap-table.com/docs/api/table-options/#selectitemname)` to achieve the functionality you want.
Example: https://live.bootstrap-table.com/code/wenzhixin/5698
