### ISSUE TITLE
Scroll Position State

### ISSUE THREAD

**Issue by linolacha** [wenzhixin/bootstrap-table#5478]
Say the bootstrap table is on the index page, when I select a row to edit (which takes me to another page) and return to index page the scroll position of the table is set to the top. Would it be possible to have a feature to save the state of the table/ scroll position?

**Comment by wenzhixin** [comment]
* [`getScrollPosition`](https://bootstrap-table.com/docs/api/methods/#getscrollposition): https://examples.bootstrap-table.com/#methods/get-scroll-position.html
* [`scrollTo`](https://bootstrap-table.com/docs/api/methods/#scrollto): https://examples.bootstrap-table.com/#methods/scroll-to.html
