### ISSUE TITLE
how can I update the paging with server data?

### ISSUE THREAD

**Issue by Gilgamesh1** [wenzhixin/bootstrap-table#5479]
from my web service i receive the following
```
{
"evaluations":[ {...
}],
"page": {
        "size": 10,
        "totalElements: 14,
        "totalPages: 2,
        "number: 0
    }
}
```
I can update the table data but not the page data (totalPage, TotalRows)

**Comment by wenzhixin** [comment]
The [`responseHandler`](https://bootstrap-table.com/docs/api/table-options/#responsehandler) option can solve your problem, example:
```js
responseHandler (res) {
  return {
    rows: res.evaluations,
    total: res.page.totalElements
  }
}
```
