### ISSUE TITLE
How to Refresh/Reload the Bootstrap-table treegrid

### ISSUE THREAD

**Issue by pkbijarane** [wenzhixin/bootstrap-table#5480]
we are using the library https://examples.bootstrap-table.com/#extensions/treegrid.html#view-source
Here we want to Reload the grid. How to achieve that?

**Comment by kaperusov** [comment]
Maybe the option `showRefresh: true` will help you?
https://bootstrap-table.com/docs/api/table-options/#showrefresh

There is also an extension for automatic grid updates: 
https://examples.bootstrap-table.com/index.html#extensions/auto-refresh.html
