### ISSUE TITLE
Bootstrap-table with bootstrap 4 and export doesn't work

### ISSUE THREAD

**Issue by paipaipaipai** [wenzhixin/bootstrap-table#5483]
![image](https://user-images.githubusercontent.com/30950645/102117935-f0fcdb00-3e79-11eb-86f3-6d5e16ee5fe9.png)

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/#extensions/export.html
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days if the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
