### ISSUE TITLE
Group by v2 collapses - not the desired actions

### ISSUE THREAD

**Issue by scottaadt** [wenzhixin/bootstrap-table#5485]
I'm using bootstrap-table group by v2. Using group-by-collapsed-groups to default groups to collapsed, whenever I update a table row or perform a search any expanded rows collapse again. Any ideas how I can prevent this?

  	data-group-by="true"
  	data-group-by-field="page"
  	data-group-by-toggle="true"
  	data-group-by-show-toggle-icon="true"
  	data-group-by-collapsed-groups=["Main"]

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by scottaadt** [comment]
Another function was interferring.

**Comment by scottaadt** [comment]
> Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

example added

**Comment by wenzhixin** [comment]
Live Example: https://live.bootstrap-table.com/code/wenzhixin/6768
