### ISSUE TITLE
Empty row displaying at top or bottom of table, despite not being in SQL or JSON results

### ISSUE THREAD

**Issue by Muzical84** [wenzhixin/bootstrap-table#549]
![capture](https://cloud.githubusercontent.com/assets/775601/6252572/f927bf8a-b760-11e4-940d-da947813f363.PNG)

Obviously had to censor out private data, but yeah, I've never had this occur in the table before.

The table is created like thus:

````javascript

    $.ajax({
        url:"/apiCall.cfc?wsdl",
        type:"GET",
        cache:false,
        dataType:'json',
        data:{method:"getUsers"}
    }).then(function(json){
        $("#userTable").bootstrapTable({
            data:json,
            classes:"table table-hover table-bordered",
            cache:false,
            sortable:true,
            pagination:true,
            pageSize: 10,
            pageList: [10, 20, 30, 40, 50, 75, 100],
            striped:true,
            search:true,
            showRefresh:true,
            idField:"ID",
            columns: [{
```
and etc.

**Comment by wenzhixin** [comment]
Can you provide your json data? Is the first row empty?

**Comment by Muzical84** [comment]
The data contains private addresses and etc., but there are no blank rows, whether I run the Stored Procedure on its own or if I hit the WSDL with a REST client.

**Comment by NaughtyMC** [comment]
@Muzical84 
Have you tried changing ' data: json ' to ' data: json.d '? I use a slightly different AJAX call, but that's what works for me.

Let me know if that works for you.

**Comment by Muzical84** [comment]
I'm using this syntax elsewhere without error.

**Comment by Muzical84** [comment]
Problem solved!  It turned out to be an error in the WSDL; I have to write my WSDLs in ColdFusion, which is 1-based; I was thinking in every OTHER language, which is 0-based.  I had to change the WSDL to build the JSON return at 1 instead of zero.
