### ISSUE TITLE
Duplicate headers when using data to initilize the table

### ISSUE THREAD

**Issue by beeeper** [wenzhixin/bootstrap-table#55]
When using data instead of url to load the data, the table will have duplicate headers.

**Comment by endra89** [comment]
@beeeper  @wenzhixin 
how about remove duplicate row, any plugin for it?
ex : http://issues.wenzhixin.net.cn/bootstrap-table/
i will remove all data have same value, any example ?

**Comment by wenzhixin** [comment]
You can delete the duplicate data row and then update the table. @endra89

**Comment by endra89** [comment]
thank for replay @wenzhixin ,  
found some code here : https://bytes.com/topic/javascript/answers/563330-remove-duplicate-object-values-array 
then : http://jsfiddle.net/endra89/pufuo7ne/2/
