### ISSUE TITLE
Install with npm

### ISSUE THREAD

**Issue by gtmn** [wenzhixin/bootstrap-table#550]
Would be great if you could publish it to npm as well ;)

**Comment by wenzhixin** [comment]
How can I do?

**Comment by gtmn** [comment]
Hope that's helpful:
https://docs.npmjs.com/getting-started/publishing-npm-packages
https://gist.github.com/coolaj86/1318304

**Comment by wenzhixin** [comment]
Thanks, I will have a try.

**Comment by wenzhixin** [comment]
Published: https://www.npmjs.com/package/bootstrap-table
