### ISSUE TITLE
中文官方网站的实例一直打不开

### ISSUE THREAD

**Issue by jacky8466** [wenzhixin/bootstrap-table#5500]
中文官方网站的实例一直打不开，显示不了信息，报错，应该是引用的js文件，在国内访问不了
https://www.bootstrap-table.com.cn/examples/welcome/index/

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
其实这个中文网站不是由我们维护的~
