### ISSUE TITLE
Search highlight error due to error of  this.searchText ?

### ISSUE THREAD

**Issue by hs749** [wenzhixin/bootstrap-table#5501]
**Bootstraptable version(s) affected**:

1.18.1
**Description**  
Search highlight error due to **searchText**  option?

**Example** 
The online [official search highlight example](https://examples.bootstrap-table.com/#options/search-highlight.html) works as expected.  
The following example is constructed based on the official example: the bootstrap-table is initialized via JavaScript codes and the same set of data is retrieved through $.getJSON
https://live.bootstrap-table.com/code/hs749/5932
If opened in Firefox, Console panel of Developer Tools displays the following error msg:
> Uncaught TypeError: o.searchText is undefined
    value https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js:10
    value https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js:10
    value https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js:10
    value https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js:10
    bootstrapTable https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js:10
    jQuery 2
    bootstrapTable https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js:10
    <anonymous> https://live.bootstrap-table.com/example/options/search-highlight.html:32
    jQuery 8
    <anonymous> https://live.bootstrap-table.com/example/options/search-highlight.html:31

**Possible  (optional)**  
After replacing all the occurrences of **this.searchText** with **this.options.searchText** in line [1570](https://github.com/wenzhixin/bootstrap-table/blob/f638add58e5cf1f2c0251b2783aad861a6cc5f94/src/bootstrap-table.js#L1570) & 1571 in bootstrap-table.js (local copy), the error disappeared.

A quick search on **this.searchText** in [bootstrap-table.js](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js) returns 13 matches. Maybe a close examination on those 13 matches is warranted.

**Additional context**

**Comment by djhvscf** [comment]
Are you completely sure that you have the latest version? https://live.bootstrap-table.com/code/djhvscf/5934 this is working with 1.18.1

**Comment by hs749** [comment]
@djhvscf thank you for the quick response. The version of bootstrap-table being used is specified in the [source code](https://live.bootstrap-table.com/code/hs749/5932), which can be confirmed by looking at the **Network** panel of  Firefox **Developer Tools** (F12)
![bt_version](https://user-images.githubusercontent.com/38709889/102842379-d627ea80-43d4-11eb-9411-0dce4d6e2bfe.png)

The bootstrap-table in your [example](https://live.bootstrap-table.com/code/djhvscf/5934) is constructed via data-* attributes, while in the [example](https://live.bootstrap-table.com/code/hs749/5932) I provided, the bootstrap-table is initialized via JavaScript codes. 
I'm just starting using bootstrap-table library and not familiar with the code base. I suspect the way how bootstrap-table is constructed running on different code path, which causes the bug.

**Comment by djhvscf** [comment]
ok, let me do that and I will get back to you

**Comment by hs749** [comment]
@djhvscf I just created a [debugging example](https://live.bootstrap-table.com/code/hs749/5957) to illustrate the bug. The only different is that the link to bootstrap-table library is not minimized (<script src="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.js"></script>).
The following are the screenshots from Chrome DevTools:

Initial loading of the page:
![error1](https://user-images.githubusercontent.com/38709889/102902583-33578680-443d-11eb-8753-f2355b2f085e.png)

After setting the breakpoint on line 5841, refresh the page:
![error2](https://user-images.githubusercontent.com/38709889/102902722-584bf980-443d-11eb-8cf8-9d15dd0eea69.png)
Notice that the two watch values in the upper right corner:
-  _this7.searchText: undefined
-  _this7.options.searchText: ""

Step over the breakpoint:
![error3](https://user-images.githubusercontent.com/38709889/102903203-ff309580-443d-11eb-94ea-13cd810c8366.png)

**Comment by djhvscf** [comment]
Good catch.. Could you create the corresponding PR with this fix? Please include the example before and after

**Comment by hs749** [comment]
@djhvscf What's PR ? pull request ? I've never done that before in Github. I may try.
But honestly, I really don't think I'm in good position to fix the problem. I'm not familiar with the code base and just recently learn to use bootstrap-table. I don't see any unit testing codes in the project repos, which make me uneasy to provide any solid fix. I'm afraid that some quick and dirty fix would cause some problem down the road. 
Previously, I raised the [issue](https://github.com/wenzhixin/bootstrap-table/issues/5396) related to search highlight with version 1.18 on Oct. 23, 2020. Now it seems there is another bug lurking around.
As I mention in the initial bug report, "A quick search on this.searchText in bootstrap-table.js returns 13 matches. Maybe a close examination on those 13 matches is warranted.". 
So I think it would be better for someone with an intimate knowledge of code base to take over this issue and take a close look at those 'this.searchText'.

**Comment by UtechtDustin** [comment]
@hs749 Thanks for the research and the detailed information.
I create a PR (#5507) which fix the bug, you can test it with this [example](https://live.bootstrap-table.com/code/UtechtDustin/5968).
Just as information, we are working on tests on a other PR (#5120).

Btw. you dont have to include the bootstrap-table as script tag, its already included automatically.
You can change the version and also if it should use the src/dist version, more information [here](https://github.com/wenzhixin/bootstrap-table/wiki/Online-Editor-Explanation).

**Comment by hs749** [comment]
@UtechtDustin Thank you very much for the Wiki link on how to use online editor. I've tested the [example](https://live.bootstrap-table.com/code/UtechtDustin/5968) linked to PR #5507 and it works. 
I've spent some time reading through the src code of bootstrap-table.js. I think the error might be caused by the uninitialized field this.searchText when this.initBody() in line [30](https://github.com/wenzhixin/bootstrap-table/blob/13ebc7e4a5bb95f8c6fbf0a1fc792ea71080f5b5/src/bootstrap-table.js#L30) is called. We probably need to move the line 31: this.initSearchText() ahead of this.initBody(). But doing so would throw error when this.searchText is not empty string. 
this.initSearchText() does two things: 

1. initialize this.searchText 
2. call search function based on this.searchText

Base on the SoC (Separation of Concerns) principle, should we break this.initSearchText() into two functions instead ? Just my two cents.

@djhvscf As a practice, I tried to create a PR by following this online [article](https://opensource.com/article/19/7/create-pull-request-github). 
- cloned the project from github to my local machine
- created a new branch 'fix/5501_1'; made some changes on bootstrap-table.js; git add & commit 
- git push -u origin fix/5501_1
After input github username & password in two pop-up windows, I got the following error msg:
      **remote: Permission to wenzhixin/bootstrap-table.git denied to hs749.**
So do I have the permission to create a PR for bootstrap-table project ?

**Comment by UtechtDustin** [comment]
@hs749 You have to fork this repository, then you can crate a branch on your (forked) repository.
After that you write and commit the changes, now your able to select the branch from your (forked) repository while creating the PR.

So you basicly missed the step of forking this repository.

**Comment by hs749** [comment]
@UtechtDustin Thank you for your help on how to create PR. 
I've created a forked repos, cloned the forked repos to my local machine, created a new branch 'fix/5502', made some changes, add & commit & push newly-created branch to my forked repos, created the pull request. But I couldn't see the branch 'fix/5502' shown in branch dropdown list of wenzhixin/bootstrap-table repos. I can see the branch 'fix/5501' for your pull request so you can link the branch 'fix/5501' to you online example. 
Did I miss some step to have branch 'fix/5502' appear in wexnzhixin/bootstrap-table repos ? I really appreciate your help.
