### ISSUE TITLE
Mobile card view doesn't like data-widths

### ISSUE THREAD

**Issue by agilealtitude** [wenzhixin/bootstrap-table#5502]
If I have data-width attributes set for any column, the mobile card view displays with offset value column text. Is there a way to have the table disregard data-width properties when in card view?

**Comment by agilealtitude** [comment]
I'm using this as a work-around for now:

@media all and (max-width: 562px) {
	.card-view-title, .card-view-value {
		width: auto !important;
	}
}

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by agilealtitude** [comment]
The online sample has been updated, although I'm not sure if it can demonstrate small screen sizes?

https://live.bootstrap-table.com/code/agilealtitude/5969

Here is a screenshot of what occurs in my app when column widths are specified.

![Screen Shot 2020-12-23 at 1 47 16 PM](https://user-images.githubusercontent.com/47539548/103035832-61b09100-4525-11eb-9263-52af75a0540b.png)
