### ISSUE TITLE
Extension filter-control: Automatic population of select input column filters doesn't work woth flat JSON

### ISSUE THREAD

**Issue by ch1lln** [wenzhixin/bootstrap-table#5503]
**Bootstraptable version(s) affected**:
1.18.1 with bootstrap v4.5.3

**Description**  
When using nested JSON objects as input data (flat JSON mode) for the bootstrap table filter control does not automatically populate the select input of the filter control in the column heading. The select stays empty. It does work fine with 'normal' JSON data as evidenced by the filter-control example.

**Example**  
https://live.bootstrap-table.com/code/ch1lln/5930

**Cause**  
The problem is caused by line 251 in src\extensions\filter-control\utils.js
`let fieldValue = data[i][field]`

Here field will contain the flat JSON 'path' like 'object.value' and this will not work with the above code. I will try to whip up a quick fix.

**Comment by djhvscf** [comment]
I posted some comments in your PR.
