### ISSUE TITLE
expandAll exclude hidden rows

### ISSUE THREAD

**Issue by senobarii** [wenzhixin/bootstrap-table#5505]
Hello,

I have a table with hidden rows when I apply expandAll per your provided example http://jsfiddle.net/dq43uypw/12/ it shows empty rows for hidden rows as well. how can i ignore to display anything about hidden rows? appreciate your speedy reply in advance.

**Comment by djhvscf** [comment]
The example is using 1.8.1 version. Please test this with latest version 1.18.1

**Comment by UtechtDustin** [comment]
As @djhvscf already said its working pretty fine on the newest Version.
Example: https://live.bootstrap-table.com/code/UtechtDustin/5967

**Comment by wenzhixin** [comment]
Fixed in the latest version: https://live.bootstrap-table.com/code/wenzhixin/6761
