### ISSUE TITLE
Bootstrap data-table is not working when using data-filter-control-container

### ISSUE THREAD

**Issue by bwcr** [wenzhixin/bootstrap-table#5512]
**Bootstraptable version(s) affected**:
1.18.0

**Description**  
I was wondering why my filter is not working when I use data-filter-control-container. When I disable it it was working successfully. But I don't want the select option located on below the table head, so I used the data-filter-control-container but it doesn't work.

**Example**
https://live.bootstrap-table.com/code/bwcr/6063

**Additional context**  
I don't think any of context that I could say regarding the issues here.

**Comment by UtechtDustin** [comment]
Thank you for reporting this issue, i create a PR which will fix that!

**Comment by bwcr** [comment]
Thank you! Anyway how can I use the git version instead of current ver on CDN? @UtechtDustin
