### ISSUE TITLE
Example documentation display blank page

### ISSUE THREAD

**Issue by hexabyte23** [wenzhixin/bootstrap-table#5514]
Hello,

Doc pages seems to be empty, from this URL https://examples.bootstrap-table.com/#welcome.html

Thanks,

**Comment by UtechtDustin** [comment]
![Bildschirmfoto von 2020-12-30 16-46-05](https://user-images.githubusercontent.com/13292481/103364615-86c17880-4abe-11eb-86a1-ebde02daf4ba.png)

It's working fine for me, which browser do you use ?
I guess a plugin of your Browser will break the page, could this be possible?

**Comment by hexabyte23** [comment]
Sorry about that,
You are right, doc pages are ok, seems to be an issue with my proxy provider...
