### ISSUE TITLE
Boostrap 5 integration

### ISSUE THREAD

**Issue by oitsuki** [wenzhixin/bootstrap-table#5515]
**Description**  
Do you have a date to use bootstrap table with boostrap 5 ! 
tk

**Comment by UtechtDustin** [comment]
The Bootstrap-table already works with bootstrap 5, you also can check the examples with bootstrap5 (You can choose the css framework on the top right menu).

Example: https://examples.bootstrap-table.com/index.html?bootstrap5

**Comment by wenzhixin** [comment]
Added theme: https://bootstrap-table.com/themes/bootstrap5/

**Comment by oitsuki** [comment]
Hello,

Tk for your answer, You can see there : https://www.clicshopping.com/ClicShoppingAdmin835 a version with boostrap5 and bootstrap table 1.18.1. It do not work completly else maybe I make a little mistake, not sur.
look (summay I used inside different table ex products or report fo export)
<table
    id="table"
    data-bs-toggle="table" ====> add bs as new table syntax bootstrap 5
    data-id-field="selected" ===> ok
    data-select-item-name="selected[]" ====> ok
    data-click-to-select="true" 
    data-sort-order="asc" ===> ok
    data-sort-name="sort_order" ===> ok
    data-toolbar="#toolbar" ===> design 
    data-buttons-class="primary"
    data-show-toggle="true" =====> see a little pb on button aligment
    data-show-columns="true"  ====> not ok
    data-mobile-responsive="true"
   data-show-export="true" ===> not ok
>

Suggestion, if you can remove Jquery (bootstrap 5 do use jquery anymore), it will be better
