### ISSUE TITLE
Load data into one bootstrap-table from another

### ISSUE THREAD

**Issue by RossAWaddell** [wenzhixin/bootstrap-table#5518]
I need to load a 2nd bootstrap-table from another and am using this code:

```
var data = JSON.stringify($("#modelEntries1").bootstrapTable("getData"));
console.log(data);
                        
/ Update 2nd bootstrap-table with the contents of this one
$("#modelEntries2").bootstrapTable({
    data: data
}); 
```

But the table shows no records. The 2nd table definition is as follows:

```
<table id="modelEntries2" data-row-style="rowStyle" class="table table-condensed table-hover table-striped" 
    data-toggle="table" data-checkbox-header="false">
    <thead>
            <tr>
                    <th data-field="id" data-align="center">#</th>
                     <th data-field="modelName" data-align="left">Model Name</th>
                     <th data-field="remarks" data-align="left">Remarks</th> 
                     <th data-field="htmlRemarks" data-align="left" data-class='hidden'>htmlRemarks</th>
                     <th data-field="category" data-align="left">Category</th>
                     <th data-field="catID" data-align="left" data-class='hidden'>catID</th>
                     <th data-field="attachedToBase" data-align="center">Attached to Base?</th>
                    <th data-field="oversized" data-align="center">Oversized?</th>
             </tr>
      </thead>
</table> 
```

I can see the data in console, so I know getData() is working. What am I doing wrong? I tried looking for anything similar on stackflow but no luck.

**Comment by UtechtDustin** [comment]
Why do you use `JSON.stringify` ?
The `data` option dont accept strings, without that `stringify` call it works fine.

Example: https://live.bootstrap-table.com/code/UtechtDustin/6075

**Comment by RossAWaddell** [comment]
Thanks, but I had also tried that and it still doesn't work. Could it be that the first table contains 2 hidden columns, or the last column has buttons?

<img width="708" alt="Screen Shot 2021-01-02 at 10 14 01 AM" src="https://user-images.githubusercontent.com/29708900/103460336-63c3de00-4ce3-11eb-9fde-068232b30ee0.png">

From the console:

```
0:
attachedToBase: "Yes"
catID: "186"
category: "Junior (age 12 & under)"
htmlRemarks: ""
id: 1
modelName: "name"
oversized: "No"
remarks: ""
__proto__: Object
length: 1
__proto__: Array(0)
```
﻿

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/), then we can try to help you!

**Comment by RossAWaddell** [comment]
Here's what I came up with:

[https://live.bootstrap-table.com/code/RossAWaddell/6078](url)

Note that the hidden columns aren't ... hidden.

**Comment by UtechtDustin** [comment]
@RossAWaddell 
The problem is that the second table is already initialised, so you have to use the  `load` method  e.g. `$('#modelEntries2').bootstrapTable('load', data)` instead of trying to initialise the table again (`$('#modelEntries2').bootstrapTable({data: data})`), click [here](https://live.bootstrap-table.com/code/UtechtDustin/6082) for the example.
You also could initialise the table while using the data from the first table. For that you only have to remove `data-toggle="table"` from the second table. Example: https://live.bootstrap-table.com/code/UtechtDustin/6083

**Comment by UtechtDustin** [comment]
Forgot to tell you why the classes are not hidden.
You are using a css class to hide them, this css style is missing in the example.
Also i would recommend you to use the [visible](https://bootstrap-table.com/docs/api/column-options/#visible) column option.

**Comment by RossAWaddell** [comment]
> Forgot to tell you why the classes are not hidden.
> You are using a css class to hide them, this css style is missing in the example.
> Also i would recommend you to use the [visible](https://bootstrap-table.com/docs/api/column-options/#visible) column option instead of the css.

If I switch to the visible column option, will that remove the column from the DOM? I want to eventually submit this table when posting the form (don't know how to do that yet) and I need the column values in those hidden columns.

**Comment by UtechtDustin** [comment]
Yes the column will not be created in the dom, if you have to submit a form maybe it makes sense to get the data from the table and submit the form manually, depends on your usecase.

But manually hiding the column could _maybe_ cause bugs in the bootstrap-table, im not sure.

**Comment by RossAWaddell** [comment]
> @RossAWaddell
> The problem is that the second table is already initialised, so you have to use the `load` method e.g. `$('#modelEntries2').bootstrapTable('load', data)` instead of trying to initialise the table again (`$('#modelEntries2').bootstrapTable({data: data})`), click [here](https://live.bootstrap-table.com/code/UtechtDustin/6082) for the example.
> 
> You also could initialise the table while using the data from the first table. For that you only have to remove `data-toggle="table"` from the second table. Example: https://live.bootstrap-table.com/code/UtechtDustin/6083
> 
> I hope this helps :-)

Using 'load' works - thank you!

If I may ask a follow-up question: I don't want the 'Action' column in the 2nd table - can I still use 'load' if I remove that column def from the 2nd table?

**Comment by RossAWaddell** [comment]
> Yes the column will not be created in the dom, if you have to submit a form maybe it makes sense to get the data from the table and submit the form manually, depends on your usecase.
> 
> But manually hiding the column could _maybe_ cause bugs in the bootstrap-table, im not sure.

Will the column data still be included in getData() if I use data-visible=false?

**Comment by UtechtDustin** [comment]
Sure, you can provide the bootstrap-table more data as needed. The table will ignore that data.
Example: https://live.bootstrap-table.com/code/UtechtDustin/6087

**Comment by UtechtDustin** [comment]
> > Yes the column will not be created in the dom, if you have to submit a form maybe it makes sense to get the data from the table and submit the form manually, depends on your usecase.
> > But manually hiding the column could _maybe_ cause bugs in the bootstrap-table, im not sure.
> Will the column data still be included in getData() if I use data-visible=false?

Thats also a yes: https://live.bootstrap-table.com/code/UtechtDustin/6088

**Comment by RossAWaddell** [comment]
Thanks for all your help - much appreciated.

**Comment by UtechtDustin** [comment]
Your welcome!
