### ISSUE TITLE
Full height ?

### ISSUE THREAD

**Issue by Philoow** [wenzhixin/bootstrap-table#552]
It's possible to display the table in full height without breaking css ? I don't want to see the scroll bar !
I already try to compute the size but i never success ! 

}).on('page-change.bs.table', function(e, size, number) {
        height = 41 * parseInt(number - 1);
}).on('load-success.bs.table', function (e, data) {
        $bsTable.bootstrapTable( 'resetView' , {height: height} );

And another question. It's possible to put a bottom row independent from the other rows ? I woul like to make row like Total : etc ...

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/
