### ISSUE TITLE
sticky header + datepicker / filter-control extensions

### ISSUE THREAD

**Issue by atomkind** [wenzhixin/bootstrap-table#5521]
**Bootstraptable version(s) affected**:

Bootstrap v4.3.1
Bootstrap-table v1.18.1

**Description**  

If I use stickyHeader + filterControl with datepicker, the sticky-header overlap the datepicker
when header is sticked to the top.
sticky-header has CSS `z-index: 100;`
datepicker has CSS `z-index: 10;`

**Example**  

Load Example, scroll down until header is sticked to the top and then click on datepicker in last column-header.
Or click first on datepicker and scroll after clicking..
[https://live.bootstrap-table.com/code/atomkind/6111](https://live.bootstrap-table.com/code/atomkind/6111)

**Possible  (optional)**  

give datepicker CSS `z-index: 101;`

**Additional context**

**Comment by djhvscf** [comment]
with the new version of Filter-Control extension the support for Bootstrap Datepicker is deprecated. We're going to work with the native datepicker html5 control.
