### ISSUE TITLE
Add support for sorting non-ASCII characters

### ISSUE THREAD

**Issue by perriard** [wenzhixin/bootstrap-table#5523]
**Description**  
Please consider implementing localeCompare in the sorting function to support ie. scandinavian languages, which have extra characters in the alphabet. :-)

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/index.html#column-options/natural-sorting.html
https://github.com/wenzhixin/bootstrap-table-examples/tree/master/utils/natural-sorting

**Comment by perriard** [comment]
I have tried that feature already before creating the issue, it doesn't support the extra characters in the (ie.) scandinavian languages.

https://live.bootstrap-table.com/code/perriard/6521

The correct sorting order for column 3 would be
aa
b
c
æ
ø
å

Please reopen my feature request :-)

**Comment by wenzhixin** [comment]
You need to use `sorter: window.alphanum`: https://live.bootstrap-table.com/code/wenzhixin/6534

**Comment by perriard** [comment]
No, theres nothing wrong with the alphanum sorting - but it's not a numerical sorting I'm looking for.

The danish language have 3 extra characters in the alphabet in the end; A B C .... X Y Z Æ Ø Å - So I'm looking for a feature to support proper sorting of other languages than english, which have special characters. All the scandinavian languages have extra characters - german has as well. :-)

**Comment by wenzhixin** [comment]
@UtechtDustin @djhvscf What do you think?

**Comment by djhvscf** [comment]
From my perspective this should be overridden by the developer. So we can provide the sort function to be used.

**Comment by UtechtDustin** [comment]
@perriard does javascript has a build in method which can figure it out ?
I tested localeCompare, but it says `Ø` should be before `Z`.

If there is no build in method i agree @djhvscf that you should implement it yourself.
If there is a build in method (which dont break other languages) i would say we could implement that, depending on the performance.

**Comment by perriard** [comment]
@UtechtDustin I'm not a javascript expert, so I can't answer that for sure - google told me it was localeCompare to use, but that might not be the best option. But I'm pretty sure it'n not the first time ever, that someone wants to sort and array in another language than english, so there must be something build in :-)

**Comment by perriard** [comment]
If anyone else with the same problem, ends up in here looking for a solution; I found my solution here: https://datatables.net/blog/2017-02-28#Standarisation :-)

**Comment by kjlibsol** [comment]
@perriard You did not manage to solve it using bootstrap-tables, is that correct? :)
