### ISSUE TITLE
Function name collision between Sticked header and Fixed columns extensions

### ISSUE THREAD

**Issue by mkyral** [wenzhixin/bootstrap-table#5527]
**Bootstraptable version(s) affected**:
latest

**Description**  
Both extensions Sticked header and Fixed columns are using function matchPositionX(). It is not a problem when you use only one extension. But if you load both, one of them will not work correctly as latest loaded definition wins.

**Example**  
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/fixed-columns/bootstrap-table-fixed-columns.js#L397

https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/sticky-header/bootstrap-table-sticky-header.js#L126

**Possible  (optional)**  
Make function name unique.

**Comment by djhvscf** [comment]
Looks like this is a problem, but please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by mkyral** [comment]
I have no Idea how to switch extension order in this editor. I need to load fixed-columns after sticky-header. But can't.

**Comment by UtechtDustin** [comment]
@mkyral it's not possible, because normally you dont have to switch the order.
Could you please provide us a example as raw html code and/or provide us an example using jsfiddle ?

**Comment by mkyral** [comment]
https://jsfiddle.net/mkyral/py302e7v/

1. Scroll down, so sticky header is shown. 
2. Then try scroll left. Table will move, sticked header not.
3. Remove fixed-column extension
4. Try scrolling again - should work correctly

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/extensions/fixed-columns/#note

Need to import after sticky-header when using with sticky-header extension. For example:
```html
<link rel="stylesheet" href="extensions/sticky-header/bootstrap-table-sticky-header.css">
<link rel="stylesheet" href="extensions/fixed-columns/bootstrap-table-fixed-columns.css">
<script src="extensions/sticky-header/bootstrap-table-sticky-header.js"></script>
<script src="extensions/fixed-columns/bootstrap-table-fixed-columns.js"></script>
```

**Comment by wenzhixin** [comment]
Updated the live editor: https://live.bootstrap-table.com/code/wenzhixin/6758

**Comment by sawirricardo** [comment]
> https://bootstrap-table.com/docs/extensions/fixed-columns/#note
> 
> Need to import after sticky-header when using with sticky-header extension. For example:
> 
> ```
> <link rel="stylesheet" href="extensions/sticky-header/bootstrap-table-sticky-header.css">
> <link rel="stylesheet" href="extensions/fixed-columns/bootstrap-table-fixed-columns.css">
> <script src="extensions/sticky-header/bootstrap-table-sticky-header.js"></script>
> <script src="extensions/fixed-columns/bootstrap-table-fixed-columns.js"></script>
> ```

Hi @wenzhixin , I thought it would be nice to put this in the documentation. So people won't spend hours just to find their import order is wrong.

**Comment by wenzhixin** [comment]
Now it's in the document: https://bootstrap-table.com/docs/extensions/fixed-columns/#note
