### ISSUE TITLE
fiterBy range?

### ISSUE THREAD

**Issue by vgoklani** [wenzhixin/bootstrap-table#553]
Is it possible to filterBy a range, i.e. age > 10 as opposed to {'age':10}

if not directly, I can write my own function via jquery, but what's the best method for hiding/removing the rows that are not satisfied by the query?

**Comment by djhvscf** [comment]
There is a show/hide row method to do that

**Comment by wenzhixin** [comment]
ref #583, jsFiddle: http://jsfiddle.net/e3nk137y/1010/
