### ISSUE TITLE
Append Table Data to Form Data for POST

### ISSUE THREAD

**Issue by RossAWaddell** [wenzhixin/bootstrap-table#5530]
I have standard HTML inputs to capture some user information, and then a bootstrap-table which they can add rows of models to submit for a contest. I want to append the table data to the form's before sending the Ajax request.

Example: [https://live.bootstrap-table.com/code/RossAWaddell/6135](url)

How would I do that? My current Ajax request (without adding the table) looks like this:

```
    // Put the form data into a serialized string and make Ajax call
    var formData = $("#entryForm").serialize();
    $.ajax({
        method: "POST",
        url: "/contest/entry/php/formSubmit.php",
        data: formData,
        global: true,   // SHOW MODAL FOR THIS AJAX REQUEST VIA AJAX START/STOP
        success: function (result){
            if (result === 'SUCCESS') {
                location.href = "/contest/entry/php/printout.php";
            } else {
                jqUIAlert(result, false);
            }
        },
        error: function (jqXHR, textStatus, errorThrown) {
            jqUIAlert('Error processing Ajax request (formSubmit): ' + jqXHR.status + ' ' + errorThrown, false);
        },
        complete: function (jqXHR, textStatus) {
            $("input[type=submit]").removeAttr("disabled");
            $("input[type=submit]").val('Submit');            
        }
    });
```

Do I use JSON.stringify() and do something like this?

`data: formData + "&modelListing" + JSON.stringify(tblData);`

**Comment by atomkind** [comment]
If you want to attach the table-data to your ajax-request, just expand your 'formData' variable:
`
var formData = {
  'dataFromInputs': $('#form').serialize(),
  'dataFromTable': $('#modelEntries1').bootstrapTable('getData'),
  'someUseless': 'or maybe usefull informations',
  'and thats': 'it'
}`

You'll get $_POST['dataFromInputs'] and $_POST['dataFromTable'] and so on in your formSubmit.php. 




If you want to add the input values to your table:
build the new row as object, push it into your getData object an load it into the table:
`
      var newEntry = {
        modelName: 'test'
        // and so on..
      };
      modelListing.push( newEntry );
      $('#modelEntries1').bootstrapTable('load',modelListing);`
(put this code after your console.log and alerts)

**Comment by RossAWaddell** [comment]
Fantastic! I've never seen that before. Thank you!
