### ISSUE TITLE
sticky-header offsetY ignores value

### ISSUE THREAD

**Issue by atomkind** [wenzhixin/bootstrap-table#5532]
**Bootstraptable version(s) affected**:

v1.18.1

**Description**  

if sticky-header offsetY has any value > 0 it just put the header about 55px y-offset from the top and not with the value given in `stickyHeaderOffsetY: '2'`
regardles of the value, it put the sticky-header always on the same position.

**Example**  

[https://live.bootstrap-table.com/code/atomkind/6154](https://live.bootstrap-table.com/code/atomkind/6154)

**Possible  (optional)**  

**Additional context**

**Comment by syedsanahassan** [comment]
@wenzhixin needs to add a "px" at this line for this offset to work properly

https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/sticky-header/bootstrap-table-sticky-header.js#L111

Why?
```top: 0``` works but if it's a number other than 0 then we need a ```top: 60px```
