### ISSUE TITLE
Response Handler - nested JSON

### ISSUE THREAD

**Issue by pawelszroeder** [wenzhixin/bootstrap-table#5533]
Hello,  I found that I can use response handler:

<pre> responseHandler: function (res) {
        return res.messages
}</pre> 

for data like here:

<pre> {
    "messages": [
        {
            "id": 652,
            "session_id": 8965861649940144331,
        },
        {
            "id": 653,
            "session_id": 8965861649940144331,
        }
    ],
    "id": 1
}</pre> 

What if my JSON looks like that:

<pre>[
  {
      "messages": [
          {
              "id": 652,
              "session_id": 8965861649940144331,
          },
          {
              "id": 653,
              "session_id": 8965861649940144331,
          }
      ],
      "id": 1
  },
  {
      "messages": [
          {
              "id": 652,
              "session_id": 8965861649940144331,
          },
          {
              "id": 653,
              "session_id": 8965861649940144331,
          }
      ],
      "id": 2
  }
]</pre> 

I found that is not working when there is more than 1 object. 
I would like to use messages from id 1 using bootstrapTable('filterBy', {'id': 1}) but when JSON starts with "[" it is not possible. Is there any solution?

Thanks!

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/6757
