### ISSUE TITLE
Filter inactive elements?

### ISSUE THREAD

**Issue by drauch** [wenzhixin/bootstrap-table#5535]
We have tables with `data-inactive="true/false"` data attributes on the `td` elements. There is a checkbox on the page which should filter out inactive elements if selected. We don't want to interfere with the "Search" filter the user is currently using.

We tried the following:

```

var table = ...;
var indices = $.map($("[data-inactive=true]"), function(e) { return $(e).data("index"); });

checkbox.change(function(){
    var isChecked = checkbox.prop("checked");
    var command = isChecked ? "showRow" : "hideRow";
    $(indices).each(function(_, e) {
        table.bootstrapTable(command, { index: e });
    });
});
```

This kinda works, but it doesn't fill up the table to n elements anymore. E.g., if there are 5 inactive elements in the first 10, then the table only shows 5 elements anymore (while still saying 10 elements are shown in the pagination controls). Is there a special "refresh" function we need to call afterwards? Are we using the wrong feature?

Best regards,
D.R.

**Comment by drauch** [comment]
I just realized that using a different Search term is re-showing the hidden rows if they match the filter. So probably hide/showRow is not what we want to do.

Is there a way to add an additional filter to the one used by the user?

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I'm closing this issue because we got no example from you within 7 days.
If you still need help please provid us an example.
