### ISSUE TITLE
Limiting amount of text visible in a column

### ISSUE THREAD

**Issue by RossAWaddell** [wenzhixin/bootstrap-table#5537]
How can I limit the amount of text shown in a column? My form allows users to enter up to 1024 characters in a Remarks field which I can use CSS styling elsewhere on an input field to add an ellipsis (...) before overflowing (hidden). Can I do something similar with a table column?

This is what it looks like now:
<img width="703" alt="Screen Shot 2021-01-11 at 11 33 18 AM" src="https://user-images.githubusercontent.com/29708900/104213526-6372c380-5404-11eb-8eda-853a103a38d5.png">

This is what I'd like to do:
<img width="701" alt="Screen Shot 2021-01-11 at 11 34 47 AM" src="https://user-images.githubusercontent.com/29708900/104213583-75ecfd00-5404-11eb-88ca-8701412dc8fc.png">

I use CSS like this on my input fields:

```
.truncate {
  width: 250px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

I don't think the data-width attribute is sufficient, and I can't trim the text as the field includes HTML markup and I don't want to lose any formatting tags.

**Comment by RossAWaddell** [comment]
Found an example (finally) - does this make sense?

[https://live.bootstrap-table.com/code/RossAWaddell/6166](url)

**Comment by UtechtDustin** [comment]
@RossAWaddell you can use a [formatter](https://bootstrap-table.com/docs/api/column-options/#formatter).
Example: https://live.bootstrap-table.com/code/UtechtDustin/6167

Will this help you ?

**Comment by atomkind** [comment]
Does make sense.

Just question a search enginge for CSS solutions, they are similar:

[Google "css ellipsis table cell"](https://www.google.com/search?q=css+ellipsis+table+cell)

[W3C Answer](https://www.w3docs.com/snippets/css/how-to-make-css-ellipsis-work-on-a-table-cell.html)

**Comment by RossAWaddell** [comment]
> @RossAWaddell you can use a [formatter](https://bootstrap-table.com/docs/api/column-options/#formatter).
> Example: https://live.bootstrap-table.com/code/UtechtDustin/6167
> 
> Will this help you ?

That truncates text, doesn’t it? I can’t do that in case I miss a closing HTML formatting tag.

**Comment by RossAWaddell** [comment]
In my example I'm using the `data-width` property but with the CSS it's using max-width. Can I use that on the table column def instead? That way, the column wouldn't start off so wide and only expand to 250px when needed. But I don't see that column property listed for bootstrap-tables.

```
<style>
  .tblColEllipsis {
    max-width: 250px; /* Customise it accordingly */
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  } 
</style>
```

**Comment by atomkind** [comment]
If you want it always the same width, juste just `width: 250px` in your CSS.
If you want to be sure and safe, use all you can like `min-width: 250px; max-width: 250px; width: 250px;`. Thats overpowered but will also work ;-)
Or you want this column(s) to have a range use `min-width: 100px; max-width: 250px;` 

If you have a CSS class for ellipse, just use the class in the header-th column where you need it.
And you dont need `data-width` because you declare the whidth in the css class `tblColEllipsis`.

All table-cells in this column will have the same class:
[https://live.bootstrap-table.com/code/atomkind/6182](https://live.bootstrap-table.com/code/atomkind/6182)

**Comment by RossAWaddell** [comment]
> If you want it always the same width, juste just `width: 250px` in your CSS.
> If you want to be sure and safe, use all you can like `min-width: 250px; max-width: 250px; width: 250px;`. Thats overpowered but will also work ;-)
> Or you want this column(s) to have a range use `min-width: 100px; max-width: 250px;`
> 
> If you have a CSS class for ellipse, just use the class in the header-th column where you need it.
> And you dont need `data-width` because you declare the whidth in the css class `tblColEllipsis`.
> 
> All table-cells in this column will have the same class:
> https://live.bootstrap-table.com/code/atomkind/6182

Thanks! I’ll try using a range like you suggested.
