### ISSUE TITLE
Fixed columns

### ISSUE THREAD

**Issue by bencummins** [wenzhixin/bootstrap-table#554]
Hi, 

I have looked but can't see a way to do it - I'd like to fix the first two columns of a table so they dont move when the table scrolls horizontally.

Thanks,

Ben

**Comment by djhvscf** [comment]
I think this thing can be a good feature @bencummins

**Comment by afbruno** [comment]
Will be Great!

**Comment by thibaultvanc** [comment]
++ GOOD feature ++

**Comment by djhvscf** [comment]
Any pull request is welcome!!

**Comment by djhvscf** [comment]
The same of https://github.com/wenzhixin/bootstrap-table/issues/265
