### ISSUE TITLE
White space between header and row, using filter control and table-height

### ISSUE THREAD

**Issue by DataSupplier** [wenzhixin/bootstrap-table#5541]
**Bootstraptable version(s) affected**:
Bootstrap 5 + Bootstrap-Table 1.81 and below.

**Description**  
Visually table is not showing correctly, having a white space between the column header and the row.
The last row is not readable. 

Using the same setup disabling the table-height option, the table works and shows fine.
Using the same setup disabling the filter-control extension, the table works and shows fine.

**Example**  
https://live.bootstrap-table.com/code/DataSupplier/6195

**Comment by UtechtDustin** [comment]
For the developer which will fix this bug: the problem is the `table-sm` (Changes the heights).
Minimal example: https://live.bootstrap-table.com/code/UtechtDustin/6274

**Comment by fabiawrc** [comment]
confirm the same problem

**Comment by djhvscf** [comment]
Working on it

**Comment by djhvscf** [comment]
Fixed in https://github.com/wenzhixin/bootstrap-table/pull/5583

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9665

**Comment by UtechtDustin** [comment]
@djhvscf 
If i use the example from @DataSupplier and your branch the fix won't work: https://live.bootstrap-table.com/code/UtechtDustin/9668

**Comment by wenzhixin** [comment]
I think the problem is `data-filter-control=""`.

**Comment by UtechtDustin** [comment]
@wenzhixin i don't think so. If you change it to e.g. `data-filter-control="select"` there is still a space between the header and the table.
The footer also looks odd.
