### ISSUE TITLE
sticky-header does not work correctly with multirow (rowspan/colspan) header

### ISSUE THREAD

**Issue by mkyral** [wenzhixin/bootstrap-table#5542]
**Bootstraptable version(s) affected**:
All

**Description**  
Sticky header extension copies columns width only for first row. So for multiple rows header could Sticked header look different. Some cols have different sizes.

**Example**  
https://live.bootstrap-table.com/code/mkyral/6199

Caused by `eq(0)`

```
      // ensure clone and source column widths are the same
      this.$stickyHeader.find('tr:eq(0)').find('th').each((index, el) => {
        $(el).css('min-width', this.$header.find('tr:eq(0)').find('th').eq(index).css('width'))
      })

```

Proposed solution - process all rows:
```
      // ensure clone and source column widths are the same
      this.$stickyHeader.find('tr').each(ridx => {
        this.$stickyHeader.find(''.concat('tr:eq(', ridx, ')')).find('th').each((index, el) => {
          $(el).css('min-width', this.$header.find(''.concat('tr:eq(', ridx, ')')).find('th').eq(index).css('width'))
        })
      })
```

![obrazek](https://user-images.githubusercontent.com/155542/104692960-1e52d800-5709-11eb-8521-d5e7e7a738cd.png)

**Comment by c-viswanath** [comment]
While recreating this issue I found that the issue has been fixed.

**Comment by UtechtDustin** [comment]
You're right, thanks for the hint @c-viswanath.
