### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by vlatro** [wenzhixin/bootstrap-table#5543]
When will there be a bootstrap-table version compatible with Bootstrap 5?

The bootstrap-table is working pretty well, but unfortunately some bootstrap utilities have changed:
_Renamed .float-left and .float-right to .float-start and .float-end._
This causes for example incorrect placement of the search box and the pagination control

**Comment by wenzhixin** [comment]
Fixed in #5536

**Comment by vlatro** [comment]
But I downloaded the last version of bootstrap-table and it's not working for me?

**Comment by UtechtDustin** [comment]
@vlatro the newest version dont contains the fix.
Please wait for a new release :-)
