### ISSUE TITLE
Custom toolbar and buttons both right, but buttons most right

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#5546]
**Description**  

I'm creating a table with a custom toolbar containing a dropdown.
I'm also showing some default buttons and I want them both on the right side.

However the default buttons are displayed left from the toolbar.

Is there a way to display the buttons (pagination-switch, toggle) complete right?

**Example (optional)**  

https://live.bootstrap-table.com/code/marceloverdijk/6209

![image](https://user-images.githubusercontent.com/197004/104778538-cacea180-577d-11eb-82e9-f749e0a495b1.png)

**Comment by UtechtDustin** [comment]
No its not possible, you could use the [custom buttons](https://bootstrap-table.com/docs/api/table-options/#buttons) option. But this option was designed for buttons not for other html elements, so it maybe could break in newer versions.
Example: https://live.bootstrap-table.com/code/UtechtDustin/6273

In my option it makes no sense to display other html content in the top right of the table.
You also could add a button which opens a modal with additional (sort) options.

**Comment by wenzhixin** [comment]
You can use the `display: flex` to solve your problem: https://live.bootstrap-table.com/code/wenzhixin/6277
