### ISSUE TITLE
Drop downs not working in Bootstrap@5.0.0-beta1

### ISSUE THREAD

**Issue by SoarinFerret** [wenzhixin/bootstrap-table#5547]
**Bootstraptable version(s) affected**:
1.18.1

**Description**  
Drop downs do not work with Bootstrap@5.0.0-beta1

**Example**  

Unable to reproduce in live environment (it loads the wrong version of bootstrap js)

EDIT: Here is a jsfiddle showing the issue: https://jsfiddle.net/ympwv21b/

**Possible  (optional)**  

Need to change from `data-toggle` to `data-bs-toggle`.  I have confirmed if I change that option name, everything works like it did before.

**Additional context**  

Tested in Firefox, Chromium, and Edge (Dev) on Ubuntu 20.04.

The change was introduced in the latest release, see the release notes here: https://blog.getbootstrap.com/2020/12/07/bootstrap-5-beta-1/

**Comment by wenzhixin** [comment]
Fixed in #5536
