### ISSUE TITLE
Sort Name Order does not work with Custom Search enabled

### ISSUE THREAD

**Issue by emugerman** [wenzhixin/bootstrap-table#5549]
**Bootstraptable version(s) affected**:
1.18.1

**Description**  
When i set the `Sort Name Order` for a specific column, together with a `Custom Search`, When the table loads, it is not sorted by the column i provided. 

**Example** 

It supposed to be sorted by `Item Name` by `desc` order, but its not:

https://live.bootstrap-table.com/code/emugerman/6214

And when removing the line `data-custom-search="customSearch"` the table is sorted correctly:

https://live.bootstrap-table.com/code/emugerman/6215

**Comment by rvaandrager** [comment]
The following code snippet in bootstrap-table.js (around line 4956 in version 1.19.1) causes this bug:
```
if (this.options.customSearch) {
  this.data = Utils.calculateObjectValue(this.options, this.options.customSearch, [this.options.data, this.searchText, this.filterColumns]);

  if (this.options.sortReset) {
    this.unsortedData = _toConsumableArray(this.data);
  }

  return;
}
```

At the end of the whole initSearch function, a call to `this.initSort()` is performed. This is not called in the customSearch part of this function. Solution: add `this.initSort()` just before the return statement:
```
if (this.options.customSearch) {
  this.data = Utils.calculateObjectValue(this.options, this.options.customSearch, [this.options.data, this.searchText, this.filterColumns]);

  if (this.options.sortReset) {
    this.unsortedData = _toConsumableArray(this.data);
  }

  this.initSort();
  return;
}
```
