### ISSUE TITLE
Recalculate summary footer on onCheck or onCheckAll event

### ISSUE THREAD

**Issue by hidonguyen** [wenzhixin/bootstrap-table#5552]
Hi,

I want to recalculate summary footer when I check/uncheck some rows, please help me.

Thank all

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by hidonguyen** [comment]
Hi @djhvscf,
Thank for your response, here is my example https://live.bootstrap-table.com/code/hidonguyen/6552

**Comment by wenzhixin** [comment]
Workaround: https://live.bootstrap-table.com/code/wenzhixin/6741

**Comment by hidonguyen** [comment]
Thanks @wenzhixin
