### ISSUE TITLE
Column custom title in the visibility dropdown

### ISSUE THREAD

**Issue by gui55gui** [wenzhixin/bootstrap-table#5553]
**Description**  
Implement a property that allows you to customize the title that will appear in the dropdown of show / hide column.

If my explanation is not clear, I have attached an image of the code part, the information I would like to be able to customize is where the column.title is, put something as if it were column.dropdownToggleTitle.

![bootstraptabledropdown](https://user-images.githubusercontent.com/48228970/105057973-84ff2b00-5a54-11eb-9bee-f1eb9fc17c1e.png)

**Comment by UtechtDustin** [comment]
Do you mean something like that: https://live.bootstrap-table.com/code/UtechtDustin/6271?

**Comment by gui55gui** [comment]
No, I need to have two titles for the same column, one title that will display in the table and another title to display in the show / hide dropdown.

**Comment by UtechtDustin** [comment]
This is currently not possible, could you explain me the usecase ?
That would make the UX worser i guess.

**Comment by wenzhixin** [comment]
Workaround: https://live.bootstrap-table.com/code/wenzhixin/6278

**Comment by gui55gui** [comment]
Thank  you very much @wenzhixin and @UtechtDustin.

My use case is: we have a table with two sections: Buy and Sell, both have the same columns, but are visually separated by the background color of the title, and in the dropdown we will separate with an identifier, example: Column1 (B) | Column2 (S)

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days if the problem exists reopen it, thanks!
