### ISSUE TITLE
disable checkbox on a row

### ISSUE THREAD

**Issue by atomkind** [wenzhixin/bootstrap-table#5555]
Is there a way to disable checkbox on a row from data?

I load table-data via ajax or json file and there could be a setting to disable checkbox for row?

[https://live.bootstrap-table.com/code/atomkind/6284](https://live.bootstrap-table.com/code/atomkind/6284)

**Comment by wenzhixin** [comment]
Examples:
* https://examples.bootstrap-table.com/#column-options/checkbox-disabled.html
* https://live.bootstrap-table.com/code/wenzhixin/6362
