### ISSUE TITLE
custom classes for table-cell tds, loaded from data with ajax/json

### ISSUE THREAD

**Issue by atomkind** [wenzhixin/bootstrap-table#5559]
How can i give table-cells custom classes?

[https://live.bootstrap-table.com/code/atomkind/6336](https://live.bootstrap-table.com/code/atomkind/6336)

> var data = [
>   {id:"0",name:"name0",price:"pr"},
>   {id:"1",name:"name1",price:"0"},
>  //	maybe?
>   {classes:{name:"green-background"},id:"2",name:"name2",price:"pr"},
>   {id:"3",name:"name3",price:"pr"},
>   {id:"4",name:"name4",price:"pr"},
> //	or so?
>   {id:"5",{classes:"green-background",name:"name5"},price:"pr"},
>   {id:"6",name:"name6",price:"0"}
> ]

I know i can give classes th the whole column, but how do i do it for single cells?

**Comment by UtechtDustin** [comment]
Using the [cellStyle option](https://bootstrap-table.com/docs/api/column-options/#cellstyle).
Example: https://live.bootstrap-table.com/example/column-options/cell-style.html

**Comment by atomkind** [comment]
Tanks! Did not see this Option :)
