### ISSUE TITLE
Multisort - Missing classes

### ISSUE THREAD

**Issue by sebastiangehrt** [wenzhixin/bootstrap-table#5563]
When using the Multisort plugin, the button is not created analogously to the other buttons in the toolbar. On the one hand the class "btn" is missing and on the other hand "data-icon-size" is not considered. 

https://live.bootstrap-table.com/code/sebastiangehrt/6355

![image](https://user-images.githubusercontent.com/31999180/105573709-baab5900-5d5f-11eb-9553-e8a538510117.png)

**Comment by UtechtDustin** [comment]
I agree the class for the icon size is missing, but the class "btn" is not missing.
You also can see it on you're screenshot (the second class).

**Comment by sebastiangehrt** [comment]
Sorry you are right, btn is not missing
