### ISSUE TITLE
Put label to to search field

### ISSUE THREAD

**Issue by morfin** [wenzhixin/bootstrap-table#557]
Hi, 

I would like to put a label on the left side to search field.

Is there any option for that ?

**Comment by nahuelsantos** [comment]
I don't know if this is a valid solution, but in file bootstrap-table.js you have some functions that returns texts that table uses (for example Search text is in function "formatSearch" or the text that is shown when data is being loaded is in "formatLoadingMessage" function), you can change these values.

**Comment by morfin** [comment]
Well, I'm actually looking to add field label. By default, the search field comes with a placeholder text. In addition to that, I need a label next to the combo, left side.

**Comment by wenzhixin** [comment]
Hi @morfin, now it does not support any option or method to do this, if you want you need to modify the source code.
