### ISSUE TITLE
bootstrap-table-export custom icon

### ISSUE THREAD

**Issue by kozolpl** [wenzhixin/bootstrap-table#5571]
**Bootstraptable version(s) affected**:
bootstrap-table@1.18.0

**Description**  
If You set up your own data-icons-prefix and data-icons:
data-icons-prefix="bi"
data-icons="icons"
export icon is not displayed even if you defined window.icons:
window.icons = { export: 'bi-test' }

I think that this is caused missing entry in bootstrap-table-export.js After corrected script everything working fine

**Possible  (optional)**  
I added this lines:
  
![obraz](https://user-images.githubusercontent.com/78235748/106330139-0344a400-6283-11eb-9904-f47e2f4fbd60.png)

before line 2502 
  
![obraz](https://user-images.githubusercontent.com/78235748/106330205-1c4d5500-6283-11eb-8cb9-20537ac71a15.png)

I think that the same problem could be in version 1.18.2.

**Comment by UtechtDustin** [comment]
Works quite good on 1.18.2, so please update to the latest version.
Example: https://live.bootstrap-table.com/code/UtechtDustin/6444
