### ISSUE TITLE
Clear Filter while using cookie ext. or search 

### ISSUE THREAD

**Issue by sebastiangehrt** [wenzhixin/bootstrap-table#5572]
**Bootstraptable version(s) affected**:
1.18.2

**Description**  
When using different settings, the filter is no longer reset cleanly. 

Variant a) 
If the cookie extension is used, the value cannot be reset via the filter. This can then only be removed via Clear Filter.
https://live.bootstrap-table.com/code/sebastiangehrt/6447

Variant b) 
If the search field is also used in addition to the cookie extension, the filter cannot be reset via Clear Filter.
https://live.bootstrap-table.com/code/sebastiangehrt/6448

**Comment by djhvscf** [comment]
Working on this since. I have been working on create the filter control from scratch

**Comment by djhvscf** [comment]
Thanks @wenzhixin.. Catching up everything

**Comment by djhvscf** [comment]
@sebastiangehrt I'm not sure about this error. Can you give us the repro steps?

**Comment by sebastiangehrt** [comment]
Variant A: 
Choose Price 1$, Click on Clear Button => Filter is reset
Choose Price 1$, Choose "blank" Entry => Filter is still on 1$

Variant B:
Choose Price 1$, Click on Clear Button => Filter is still on 1$
Choose Price 1$, Choose "blank" Entry => Filter is still on 1$

**Comment by djhvscf** [comment]
Fix: https://live.bootstrap-table.com/code/djhvscf/7445
Fix: https://live.bootstrap-table.com/code/djhvscf/7446

PR: https://github.com/wenzhixin/bootstrap-table/pull/5583

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/7445
