### ISSUE TITLE
How to hide field from show columns button?

### ISSUE THREAD

**Issue by yujinyuz** [wenzhixin/bootstrap-table#5577]
**Description**  

I'm trying to hide this empty checkbox but I can't seem to find any `data-*` option to pass

![image](https://user-images.githubusercontent.com/10972027/106903871-8196bf80-6735-11eb-9c4f-103797231407.png)

**Example (optional)**  

Here's a sample https://live.bootstrap-table.com/code/yujinyuz/6471

**Comment by UtechtDustin** [comment]
I guess you found a bug!
We will check that, thank you for the example!

**Comment by wenzhixin** [comment]
You need to set the `switchable` column option to `false`: https://live.bootstrap-table.com/code/wenzhixin/6484
https://bootstrap-table.com/docs/api/column-options/#switchable
