### ISSUE TITLE
Get data from PHP function

### ISSUE THREAD

**Issue by iamthestreets** [wenzhixin/bootstrap-table#558]
Hi,

I have re-written some of my php to utilze functions more, but i can get the table to load any data. So basically i have a php function like this:
```php
//Retrieve information for all users
function fetchAllUsersJson() {
	global $mysqli,$db_table_prefix; 
	$stmt = $mysqli->prepare("SELECT 
		id,
		user_name,
		display_name,
		email,
		active,
		title,
		sign_up_stamp,
		last_sign_in_stamp
		FROM ".$db_table_prefix."users");
	$stmt->execute();
	$stmt->bind_result($id, $user, $display, $email, $active, $title, $signUp, $signIn);
	
	while ($stmt->fetch()){
		$row[] = array('id' => $id, 'user_name' => $user, 'display_name' => $display, 'email' => $email, 'active' => $active, 'title' => $title, 'sign_up_stamp' => $signUp, 'last_sign_in_stamp' => $signIn);
	}
	$stmt->close();
	echo json_encode($row);
}
```
When I try to use this inside the function it just returns the data I need. So I put the function name like this `data-url="<?php fetchAllUsersJson(); //Fetch information for all users ?>"`

If I remove the code out of the function and add it to its own php page it works fine and data is loaded in the table. Can you help load the data using a php function?

If you need more detail let me know.

**Comment by wenzhixin** [comment]
#375
