### ISSUE TITLE
Non-conform HTML-Standard: <div> not allowed as child of <span>

### ISSUE THREAD

**Issue by atomkind** [wenzhixin/bootstrap-table#5584]
**Bootstraptable version(s) affected**:
v1.18.1

**Description**  
Non-conform HTML-Standard:
`<div>` not allowed as child of `<span>`

**Example**  
> <span class="page-list">
	<span class="btn-group dropdown dropup">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">
        	<span class="page-size">10</span>
        	<span class="caret"></span>
        </button>
        <div class="dropdown-menu">
	        <a class="dropdown-item active" href="#">10</a>
	        <a class="dropdown-item " href="#">25</a>
	        <a class="dropdown-item " href="#">50</a>
	        <a class="dropdown-item " href="#">100</a>
	        <a class="dropdown-item " href="#">200</a>
        </div>
	</span>
	rows per site.</span>

**Possible  (optional)**  
Replace the page-list `<span>` with `<div>`

**Comment by atomkind** [comment]
Also an empty table-footer triggers w3c error "Error: Row 1 of a row group established by a thead element has no cells beginning on it."

> `<div class="fixed-table-footer">`
`<table>`
`<thead>`
`<tr>`
`</tr>`
`</thead>`
`</table>`
`</div>`

**Comment by atomkind** [comment]
Last but not least ... The filter-control with option "select": If there is an option for "empty" it also triggers w3c error, maybe there could be "(empty)" as option?
"Error: Element option without attribute label must not be empty."

> `<select class="form-control bootstrap-table-filter-control-sparte" style="width: 100%;" dir="ltr">`
`<option value="" selected="selected"></option>`
`<option value="cell-not-empty">cell-not-empty</option>`
`</select>`

**Comment by wenzhixin** [comment]
Not found the **empty table-footer** problem, please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by atomkind** [comment]
The Example for filter-control
[https://live.bootstrap-table.com/example/extensions/filter-control.html](https://live.bootstrap-table.com/example/extensions/filter-control.html)

Copied the html to w3c validator
gives error
> Error: Element option without attribute label must not be empty.
From line 35, column 671; to line 35, column 679

<img width="1359" alt="w3c" src="https://user-images.githubusercontent.com/76743347/109386966-a4fcf680-78fe-11eb-9982-ce4bef53bb7f.png">

Because of the empty `<option value="" selected="selected"></option>`


`<th style="" data-field="price">
         <div class="th-inner ">Item Price</div>
         <div class="fht-cell">
            <div class="filter-control">
               <select class="form-control bootstrap-table-filter-control-price" style="width: 100%;" dir="ltr">
                  <option value="" selected="selected"></option>
                  <option value="$0">$0</option>
                  <option value="$1">$1</option>
                  <option value="$10">$10</option>
                  <option value="$11">$11</option>
                  <option value="$12">$12</option>
                  <option value="$13">$13</option>
                  <option value="$14">$14</option>
                  <option value="$15">$15</option>
                  <option value="$16">$16</option>
                  <option value="$17">$17</option>
                  <option value="$18">$18</option>
                  <option value="$19">$19</option>
                  <option value="$2">$2</option>
                  <option value="$20">$20</option>
                  <option value="$3">$3</option>
                  <option value="$4">$4</option>
                  <option value="$5">$5</option>
                  <option value="$6">$6</option>
                  <option value="$7">$7</option>
                  <option value="$8">$8</option>
                  <option value="$9">$9</option>
               </select>
            </div>
         </div>
      </th>`

**Comment by atomkind** [comment]
Any example without table-footer creates
`<div class="fixed-table-footer" style="display: none;"><table><thead><tr></tr></thead></table></div>`

And this gives w3c validation error
"Error: Row 1 of a row group established by a thead element has no cells beginning on it.
From line 6, column 76; to line 6, column 80"

<img width="1365" alt="w3c" src="https://user-images.githubusercontent.com/76743347/109387188-2c973500-7900-11eb-8091-fa6ec1f92ab7.png">

**Comment by wenzhixin** [comment]
OK, fixed in #5601
