### ISSUE TITLE
Long string in table

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5585]
Hi

Some times i have long string in tables with our spaces between works.
Each cell have data attribute data-width="300" for example
But if string very big - cell become bigger too.

Is it possible to make auto line break when content too long.
Thanks a lot

PS: Load examples in online editor does not work
https://live.bootstrap-table.com/
Also view source here does not work 
https://examples.bootstrap-table.com/#welcomes/from-html.html#view-source

**Comment by wenzhixin** [comment]
Not work? Sorry I'm not sure exactly what you're asking.

**Comment by urtvs** [comment]
Look when i have long string with no space between words, for example such


111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

My table colum become bigger then i told in data atribute
data-width="20".

Understand what i mean? 

And here
https://live.bootstrap-table.com/example/welcomes/from-html.html
Load examples does not work:(

Here also
https://examples.bootstrap-table.com/#welcomes/from-html.html#view-source
https://i.imgur.com/zai9Pfi.png

**Comment by UtechtDustin** [comment]
@urtvs The example pages works fine for me, it seems your browser will broke it.
Maybe a browser plugin will cause it. Please fix that issue on your side and provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by urtvs** [comment]
Look what i mean
https://drive.google.com/file/d/18QQ33VnDkvAmj8uJkwFYulGVhDVPqx0G/view?usp=drivesdk

**Comment by urtvs** [comment]
Look why its teling that no matching record find?
https://live.bootstrap-table.com/code/urtvs/6642

**Comment by wenzhixin** [comment]
Example: https://live.bootstrap-table.com/code/wenzhixin/6732
But I don't know what you mean.

**Comment by djhvscf** [comment]
For me the example from @wenzhixin is working just right

**Comment by UtechtDustin** [comment]
I'm closing this issue because we got no more response from you.
If you still need help please please explain what kind of issue left.
