### ISSUE TITLE
Table filter control with cell content having links <a> is no longer working

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#5588]
**Bootstraptable version(s) affected**:
1.8.2

**Description**  
bootstrap-table-filter-control using data-filter-control="select" with cell content having links <a> is no longer working
![image](https://user-images.githubusercontent.com/646632/108187304-9ba9a800-710e-11eb-95a3-479ade928057.png)

![image](https://user-images.githubusercontent.com/646632/108187264-90ef1300-710e-11eb-9ecf-83451ebffdad.png)

**Example**  
https://jsfiddle.net/8aw4ox96/

**Possible  (optional)**  

**Additional context**

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by sdespont** [comment]
@djhvscf @wenzhixin Sure : https://live.bootstrap-table.com/code/sdespont/6739

**Comment by djhvscf** [comment]
@sdespont got it. I'm working on filter control rewrite

**Comment by nl492k** [comment]
Experienced this issue today.  Worked around issue with filterData and passing a list of options.   I did do enough investigating to find that it was related to " and ' in the href attribute of the anchor tag.

**Comment by djhvscf** [comment]
Fixed in https://github.com/wenzhixin/bootstrap-table/pull/5583

**Comment by sdespont** [comment]
@djhvscf any chance to have a merge in next weeks?

**Comment by UtechtDustin** [comment]
@wenzhixin ?

**Comment by djhvscf** [comment]
This is still in progress.

**Comment by sdespont** [comment]
@djhvscf any news/plans about when the fix will be released?

**Comment by sdespont** [comment]
Hi @djhvscf , version 1.9.0 has been released 3 days ago, can we expect a new version of the filter control plugin? A lot of bug have been fixed in #5583 (thanks for this!) and this one is a real problem for some people.

**Comment by UtechtDustin** [comment]
@sdespont As you can see in the latest post (https://github.com/wenzhixin/bootstrap-table/pull/5583#issuecomment-963888463) @djhvscf will create a few examples and tests and then we are (hopefully) ready to merge.

**Comment by sdespont** [comment]
@UtechtDustin Oh right, thanks for the answer

**Comment by djhvscf** [comment]
I'm working on improving the rendering process

**Comment by djhvscf** [comment]
Example with the fix: https://live.bootstrap-table.com/code/djhvscf/9666

**Comment by UtechtDustin** [comment]
@djhvscf 
The fix works, but i don't think it makes sense like that.
None dev users don't understand the html stuff, some kind of bad UX i guess. We should use/show only the visible text (maybe we could implement it with a filterFormatter or something like that, which is overwritable by the dev).

**Comment by djhvscf** [comment]
But it is the raw text 
![image](https://user-images.githubusercontent.com/4496763/142752725-47d69115-e143-4977-80e7-a3d2483013be.png)
What do you mean? @UtechtDustin

**Comment by sdespont** [comment]
@djhvscf In fact, I also have full <a> tag with https://live.bootstrap-table.com/code/djhvscf/9666 and Chrome :
![image](https://user-images.githubusercontent.com/646632/142756526-7fb926dc-a7b1-44cf-9548-a011f4ccb11b.png)

**Comment by UtechtDustin** [comment]
@djhvscf check the screenshot from @sdespont.
That is the issue i mean, i'm using Firefox 94.0

**Comment by djhvscf** [comment]
I think the online example may have cache problems.. @wenzhixin

**Comment by sdespont** [comment]
@djhvscf, it had to because it is working well now 

![image](https://user-images.githubusercontent.com/646632/142817729-7c8a004c-4e27-4b47-aecd-61e9be320ed3.png)

Thanks for the fix!

**Comment by UtechtDustin** [comment]
Works well for me too!
Thanks @djhvscf

**Comment by i-m-d** [comment]
When will this fix be available to download ?

**Comment by djhvscf** [comment]
@i-m-d we're working on the last issue that that PR is going to cover.. After that we can release a new version.

**Comment by sdespont** [comment]
@djhvscf This problem appears again since 1.21.0 (OK in 1.20.2).

Do you have any idea why ?

The filter is not working if the link is containing a html link. Here is a sample to reproduce the problem : https://live.bootstrap-table.com/code/sdespont/13443
