### ISSUE TITLE
data-sorter="alphanum" sorts incorrectly when columns contain positive and negative numbers

### ISSUE THREAD

**Issue by pajz** [wenzhixin/bootstrap-table#559]
<thead>
        <tr>
            <th data-sortable="true"> a </th>
            <th data-sortable="true" data-sorter="alphanum"> b </th>
        </tr>
    </thead>
    <tbody>
        <tr> <td>A</td> <td>5</td> </tr>
        <tr> <td>B</td> <td>30</td> </tr>
        <tr> <td>C</td> <td>-2.25</td> </tr>
        <tr> <td>D</td> <td>-7</td> </tr>
        <tr> <td>E</td> <td>-75</td> </tr>
    </tbody>

sorts incorrectly because it mishandles the positive and negative numbers. When sorting by the second column, this gives me the following order: (30,5,-75,-7,-2.25), so the negative parts are positioned the wrong way around.

**Comment by wenzhixin** [comment]
Hi @pajz , please help to provide a jsFiddle, thanks: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
It seems you needn't to use `alphanum`: http://jsfiddle.net/xushv6q0/
