### ISSUE TITLE
Load the data to table and reset pagination

### ISSUE THREAD

**Issue by MedEIP** [wenzhixin/bootstrap-table#5597]
dear all,

i'm using a bootstrap table and need to load new data each time I click on a button, I don't want to keep old data.
my problem is when new data is loaded, I keep the content of the other pages (2,3....), my need is to replace all content by the new one and  pagination should be adapted to the new content, i noticed also that nothing happen if a click on the button again.

javascript code :
`var rows = $("<tr><td style=\"display:none;\">1</td><td>E</td><td>E</td><td>E</td></tr>");
$("#Mybutton").click(function() 
  $('#matable tbody').html(rows);
});`

**Comment by wenzhixin** [comment]
You need to use the [`load`](https://bootstrap-table.com/docs/api/methods/#load) method instead of `html()` function.
Example: https://examples.bootstrap-table.com/index.html#methods/load.html
