### ISSUE TITLE
Loading table has wrong width set

### ISSUE THREAD

**Issue by mschoettle** [wenzhixin/bootstrap-table#5598]
**Bootstraptable version(s) affected**:
`v1.18.1`

**Description**  

I have a table with more columns than fit on the screen. The table can be horizontally scrolled to deal with that.
However, the page width is bigger than it should be.

![Screen Shot 2021-02-24 at 16 05 30](https://user-images.githubusercontent.com/9328433/109066272-d7b6ad00-76ba-11eb-84a4-137626f5c186.png)

I figured out that this is because of the hidden loading table which has an absolute width set in its `style` attribute:

```html
[...]
<div class="fixed-table-body">
      <div class="fixed-table-loading table table-bordered table-hover fixed-table-border" style="top: 30.59375px; width: 2269.34375px;">
      <span class="loading-wrap">
[...]
```

If I remove this width in the inspector the page width is correct and everything seems to be working fine.

Is it possible to remove this fixed width or is there a reason that this is set?

**Comment by mschoettle** [comment]
It is set here https://github.com/wenzhixin/bootstrap-table/blob/87609636cfe4766fdb9072dfff37b39ff2059404/dist/bootstrap-table.js#L6051 using `outerWidth()`. According to the jQuery documentation on [outerWidth](https://api.jquery.com/outerWidth/)

> Although `.outerWidth()` can be used on table elements, it may give unexpected results on tables using the `border-collapse: collapse` CSS property.

In my case it has `collapse` and without the `width` set it seems to work fine.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by mschoettle** [comment]
I was able to reproduce it on the online editor: https://live.bootstrap-table.com/code/mschoettle/6748

**Comment by wenzhixin** [comment]
Fixed in the develop branch: https://live.bootstrap-table.com/code/wenzhixin/10775
