### ISSUE TITLE
Get date value on button

### ISSUE THREAD

**Issue by diegcarlos** [wenzhixin/bootstrap-table#5599]
**Description**  
I'm trying to get the value of data-basedados and data-client that is in button, and I'm also trying to open a modal but it doesn't appear on the console, I don't know if I'm doing something wrong

**Example (optional)**  
https://live.bootstrap-table.com/code/diegcarlos/6726

**Comment by wenzhixin** [comment]
You can use the column `events` option: https://bootstrap-table.com/docs/api/column-options/#events
Example: https://live.bootstrap-table.com/code/wenzhixin/6727
