### ISSUE TITLE
Firefox and $(document).ready(function ()

### ISSUE THREAD

**Issue by promogest** [wenzhixin/bootstrap-table#560]
When i put this function inside the document ready in firefox nothing happen. Chrome, midori and web ( gnome browser ) are ok. 
```javascript
$('#mytable').on('load-success.bs.table', function() {
alert("ok")
})
```
Any help?

Thanks

**Comment by wenzhixin** [comment]
What's your data url?

**Comment by wenzhixin** [comment]
Test on FireFox 37.0 : http://issues.wenzhixin.net.cn/bootstrap-table/
The event can be trigger
```
 load-success.bs.table [Object { total=800,  rows=[10]}]
```
