### ISSUE TITLE
toggle strict search?

### ISSUE THREAD

**Issue by nandoblanco** [wenzhixin/bootstrap-table#5600]
Is it possible to toggle strict search on and off the whole table on the fly? via button click?  

Thanks in advance, all help is appreciated!

**Comment by UtechtDustin** [comment]
Hey, you can use the method [refreshOptions](https://bootstrap-table.com/docs/api/methods/#refreshoptions) to refresh the options, you can fetch the current strict search state with the method [getOptions](https://bootstrap-table.com/docs/api/methods/#getoptions).

Example: https://live.bootstrap-table.com/code/UtechtDustin/6728

Will that help ?

**Comment by nandoblanco** [comment]
perfect, thank you!
