### ISSUE TITLE
When data-search="true", search parameter is added to the GET request

### ISSUE THREAD

**Issue by mamisoa** [wenzhixin/bootstrap-table#5602]
Hi,

Using this table configuration:

```
<table id="table"
            data-toolbar="#toolbar"
            data-id-field="id"
            data-toggle="table"
            data-show-refresh="true"
            data-pagination="true"
            data-side-pagination="client"
            data-page-size="20"
            data-show-columns="true"
            data-search="true"
            data-data-field="items"
            >
            <thead class="thead-dark">
                <th data-field="id" data-sortable="true">ID</th>
                <th data-field="uid" data-sortable="true">UID</th>
                <th data-field="first_name" data-title="First name" data-sortable="true">First name:</th>
                <th data-field="last_name" data-sortable="true">Last name:</th>
                <th data-field="gender.sex" data-searchable= "true" data-sortable="true">Gender:</th>
                <th data-field="dob" data-sortable="true">Date of birth:</th>
            </thead>
</table>
```
initialization:
```
var API_USER_LIST="http://localhost:8000/myapp/api/auth_user?membership.eq=6&@lookup=gender:gender[sex]&@limit=100&@order=last_name"
var $table = $('#table').bootstrapTable({
        url: API_USER_LIST
    });
```

the GET request add a "&search=" at the end of the url getting a response failure:

http://localhost:8000/myapp/api/auth_user?membership.eq=6&@lookup=gender:gender[sex]&@limit=100&@order=last_name&search=

When data-search is set to "false", data are displayed in table.

Questions:
1) Is it possible not to trigger the "&search=" parameter? I think it was not present on previous version.
2) I think the search is done within the table data with javascript? Not with a new GET request on each key press?

Thanks for your help.

Mamisoa

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).
I can't reproduce it, as you example above uses `data-side-pagination="client"` it also should not happen.
It should only happen with `data-side-pagination="server"`.

**Comment by mamisoa** [comment]
Hi,

Long time experimenting finally made me understand how the search is done when using data from url.

Using data-side-pagination="client", bootstrap-table takes all the data and calculate the pagination. If data-search is set to true, without any queryParams parameter, it adds "?search=" at the end of the request at first call. To avoid that, one should use either 1) data-query-params="" or 2) define a function queryParams which return an empty string, which is more elegant.

Using data-side-pagination="server", if data-search is set to true, it still add "?search=" at the end of the request. The request is repeated each time a key is pressed in the search field which goes in the params.search. To customize the request, one should use a queryParams function. For example, in my example, I used this code to override the "?search=":

```
function queryParams(params) {
    search = params.search.split(",");
    if (search == [""]) {
        s =""
    } else {
        if (search[0]!= undefined) {
            s = "last_name.startswith=" + search[0];
        } else {
            s = "";
        }
        if (search[1]!= undefined) {
            s += "&first_name.startswith=" + search[1];
        } else {
            s +="";
        }
        if (search[2] != undefined) {
            s += "&gender.sex.startswith=" + search[2];
        } else {
            s += "";
        }
    }
    return s;
}
```
Hope it helps.

Mamisoa
