### ISSUE TITLE
Uncaught TypeError & data-mobile-responsive="true"  did not working!

### ISSUE THREAD

**Issue by bubublik** [wenzhixin/bootstrap-table#5603]
**Description**  
Tryed to use bootstrap-table with data-mobile-responsive extension.
Everything works as it should and folds into the card for mobile devices. Except for this example:

1. Error in the console 
2.  The table does not turn into cards

**Example**  

[My broken table](https://live.bootstrap-table.com/code/bubublik/6743)

**Error**
  `Uncaught TypeError: t[u] is undefined
    trToData https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js:10
    jQuery 2
    trToData https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js:10
    jQuery 2
    trToData https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js:10
    value https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js:10
    value https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js:10
    value https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/mobile/bootstrap-table-mobile.min.js:10
    bootstrapTable https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js:10
    jQuery 2
    bootstrapTable https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js:10
    <anonymous> http://localhost:8000/watchlist/:622
    jQuery 13
`

**Any help and advice is greatly needed. Thanks in advance!**

**Comment by UtechtDustin** [comment]
Your `caption` tag within the `thead` is the problem. Without it works fine.
Example: https://live.bootstrap-table.com/code/UtechtDustin/6745
