### ISSUE TITLE
How to sort german floating numbers (separated with comma, instead of point)?

### ISSUE THREAD

**Issue by JackHewson** [wenzhixin/bootstrap-table#5605]
**Description**  
I want to make a column with german floating numbers sortable.

Lets have these numbers: 2,73 | 3,8 | 20,18

**Expected sorting (from low to high):**
2,73
3,8
20,18

**Actual sorting (from low to high):**
2,73
20,18
3,8

I'm using v1.18.2 with german locale 
```
<script src="bootstrap-table.min.js"></script>
<script src="locale/bootstrap-table-de-DE.min.js"></script>	
```
and annotate the `<th>` like this:
`<th data-sortable="true">`

Thank you!

**Comment by UtechtDustin** [comment]
You have to implement a custom sorter using the [sorter option](https://bootstrap-table.com/docs/api/column-options/#sorter).

Example: https://live.bootstrap-table.com/code/UtechtDustin/6746


---------------------------

Moin, damit das funktioniert musst du eine eigne sortier Funktion implementieren.
Du kannst dafür die option [sorter option](https://bootstrap-table.com/docs/api/column-options/#sorter) nutzen.

Beispiel: https://live.bootstrap-table.com/code/UtechtDustin/6746
