### ISSUE TITLE
Date Picker options not working with filter control plugin

### ISSUE THREAD

**Issue by SleeveShirtholes** [wenzhixin/bootstrap-table#5608]
**Bootstraptable version(s) affected**:
1.18.1

**Description**  
When passing in options to data-filter-datepicker-options it doesn't work.

**Example**  
https://live.bootstrap-table.com/code/SleeveShirtholes/6774

**Possible  (optional)**  

**Additional context**

**Comment by UtechtDustin** [comment]
Could you explain what do you mean ?
The datepicker shos the clear button as defined.

**Comment by UtechtDustin** [comment]
You have to switch the qoutes `"` and `'`, as you also can see in the [documentation](https://bootstrap-table.com/docs/extensions/filter-control/#filterdatepickeroptions).
Example: https://live.bootstrap-table.com/code/UtechtDustin/6775

**Comment by SleeveShirtholes** [comment]
Ugh...rookie mistake. Thanks for your help!
