### ISSUE TITLE
How to maintain detail view icon in card view?

### ISSUE THREAD

**Issue by shanni33** [wenzhixin/bootstrap-table#5609]
I have a table that has sort function and detail view icon. When I switch in card view mode , the sort function and detail view icon do not work. 
I want to know how to  maintain detail view icon and sort function in card view.
Any suggested solution? 
Thanks!

**Comment by UtechtDustin** [comment]
Both is not supported currently, i'm unsure if that would makes sense.
@wenzhixin @djhvscf what do you think ?

**Comment by wenzhixin** [comment]
Card view not support `detailViewIcon` option, but you can use `detailViewByClick` option in the card view. 
https://examples.bootstrap-table.com/#options/detail-view-icon.html

**Comment by djhvscf** [comment]
I don't think that the sort control should be there when the card view is active. If the card view respects the sort define, that's enough
