### ISSUE TITLE
Possible Filter-Content bug?

### ISSUE THREAD

**Issue by SleeveShirtholes** [wenzhixin/bootstrap-table#5610]
**Bootstraptable version(s) affected**:
v1.18.2

**Description**  
Web Page timing out with filter-control set on and will not load the page correctly. If I turn off filter-control then everything loads just fine. Once the page finally loads the console shows the error below. I can't get it to replicate in a live example but I have attached one anyway. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/34148154/109855145-2a411d80-7c15-11eb-929b-b260d633f1d3.png)

**Example**  
https://live.bootstrap-table.com/code/SleeveShirtholes/6779

**Comment by djhvscf** [comment]
Looks like this is causing an error: `data-search-highlight="true"`

See this example without that property https://live.bootstrap-table.com/code/djhvscf/6807

**Comment by UtechtDustin** [comment]
It seems this issue is fixed in the newest version, if you still have issues with that please provide a new example with the newest version.
Version on the newest version: https://live.bootstrap-table.com/code/UtechtDustin/9779
