### ISSUE TITLE
The Table Export exportFooter bug

### ISSUE THREAD

**Issue by anqingkang** [wenzhixin/bootstrap-table#5611]
**WhenTable Export Wiht footer and Table Options "height" not set,Two rows of the same footer data are exported.**
When the height is not defined and exportFooter is false,exportFooter is displayed in Table > tFoot. When exportFooter is false, tFoot content can also be exported. When exportFooter is true, it will be generate in div.fixed-table-footer and export.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by anqingkang** [comment]
[https://live.bootstrap-table.com/code/anqingkang/6785](url)
