### ISSUE TITLE
Javascript in the data is executed

### ISSUE THREAD

**Issue by steinbachio** [wenzhixin/bootstrap-table#5612]
**Bootstraptable version(s) affected**:
* 1.18.2

**Description**  
Javascript in the data is executed.

**Example**  
https://live.bootstrap-table.com/code/steinbachio/6799

**Additional context**  
If conent is editable by endusers, they can inject js to every other user that is visiting the site with the table.

**Comment by UtechtDustin** [comment]
This is not a bug, set the column option [escape](https://bootstrap-table.com/docs/api/column-options/#escape) to `true`.
Example: https://live.bootstrap-table.com/code/UtechtDustin/6804

**Comment by UtechtDustin** [comment]
ref: #5017
