### ISSUE TITLE
no elements found on json

### ISSUE THREAD

**Issue by ghiboz** [wenzhixin/bootstrap-table#5613]
**Bootstraptable version(s) affected**:
1.18.2 

**Description**  
the json file is not loaded

**Example**  
```html
<table
    id="table"
    data-toggle="table"
    data-url="https://www.ghiboz.com/move.json">
    <thead>
        <tr>
            <th data-field="sCll">sCll</th>
            <th data-field="sCllDst">sCllDst</th>
            <th data-field="sMtrCod">sMtrCod</th>
        </tr>
    </thead>
</table>
```

**Additional context**  
I tried to read the data from my url (at the moment is a fixed json, but also in the dyn the issues are the same
it's possible show a log of what's happen?

**Comment by djhvscf** [comment]
This is what I got from the live example: https://live.bootstrap-table.com/code/djhvscf/6808 Looks like there are some cors problems.. Please verify if that's your issue

**Comment by ghiboz** [comment]
thank you @djhvscf , I tried everything in the same server and seems to be good!
thank you!
