### ISSUE TITLE
Search parameters with accent

### ISSUE THREAD

**Issue by mamisoa** [wenzhixin/bootstrap-table#5614]
**Bootstraptable version(s) affected**:
from CDN

**Description**  
Returned string from queryParams function contains an accent like : `?first_name.startswith=José`
Get request is not encoded correctly `?first_name.startswith=Jos%C3%A9` and then no match is found.
Html file is recorded in utf-8. Meta tag utf-8 is set.
Same issue using or not `data-search-accent-neutralise`.

**Possible  (optional)**  
Is is possible the form is not utf-8 encoded when submitting?

Mamisoa

**Comment by wenzhixin** [comment]
It works after testing: https://live.bootstrap-table.com/code/wenzhixin/7318 
`data?offset=0&limit=10&first_name.startswith=Jos%C3%A9`
If the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
