### ISSUE TITLE
Click to call function

### ISSUE THREAD

**Issue by chrs944** [wenzhixin/bootstrap-table#5615]
I'm trying to figure out if this is possible.

I'd like to be able to click on a table row and have it call a function, passing in the row data as a parameter that I can then use in that function.

**Comment by chrs944** [comment]
I tried clicking on that link but it takes me to Datepicker issue example

**Comment by djhvscf** [comment]
Yes, it was my mistake.. This is the link https://bootstrap-table.com/docs/api/events/#onclickrow
