### ISSUE TITLE
data-show-columns icon isn't coming out properly 

### ISSUE THREAD

**Issue by Adersh97** [wenzhixin/bootstrap-table#5616]
**Bootstraptable version(s) affected**:
1.18.2

**Description**  
I was trying to use data-show-columns attribute for my table and the toggle icon isn't coming out properly. it felt like there was some problem with my header so I tried to change the version of my bootstrap css and js, but it didn't help either. 

**Example**  
https://live.bootstrap-table.com/code/Adersh97/6833
The code of my HTML in bootstraptable online editor . here the column toggle looks fine but if I paste the same code in jsfiddle , it isn't toggling properly the link for js fiddle is mentioned below , the same with my local too.
https://jsfiddle.net/adersh97/4smpxo0q/
**Possible  (optional)**  

**Additional context**  

The icon comes out to be something like this
![image](https://user-images.githubusercontent.com/36945281/110193243-2a494500-7df0-11eb-999e-247b0dbaeee2.png)

**Comment by UtechtDustin** [comment]
Your example is not working, please provide a working example.
It seems this is a issue with you setup, as you can see in the example its working fine in all 3 Bootstrap versions:
Example: https://live.bootstrap-table.com/example/options/basic-columns.html

**Comment by Adersh97** [comment]
> Your example is not working, please provide a working example.
> It seems this is a issue with you setup, as you can see in the example its working fine in all 3 Bootstrap versions:
> Example: https://live.bootstrap-table.com/example/options/basic-columns.html

I have updated the example and added the same code run in jsfiddle too. please help me out.

**Comment by UtechtDustin** [comment]
Your example works fine for me, the icon is shown.
Please check your Browser extensions.

**Comment by Adersh97** [comment]
only in the live.boostrap-table its working , in js fiddle link the icon isn't coming out properly, I checked with edge too where I haven't installed any extensions

**Comment by UtechtDustin** [comment]
It can't work on jsfiddle, because you don't load fontawesome (which is the lib for the icons).
Our editor will load it automatically fontawesome.

Which means, add the css file(s) of fontawesome and it also works on jsfiddle.

**Comment by Adersh97** [comment]
could you please share me the css header which I need to include?

**Comment by UtechtDustin** [comment]
I could, but if you not able to include it or to google for the fontawesome homepage (or fontawesome cdn) you maybe should learn that first.

**Comment by Adersh97** [comment]
thank you for being so kind with your replies to beginners.

**Comment by UtechtDustin** [comment]
If i provide you the solution, you will not learn it, its quite easy.
Google for "how to include a css file" after that you search for "fontawesome cdn".
You should learn it within a few minutes.

**Comment by Adersh97** [comment]
ofcourse i know how to include css file , I was importing wrong css file , so wanted to know which css file were you importing
