### ISSUE TITLE
Title of columns are double

### ISSUE THREAD

**Issue by camustre** [wenzhixin/bootstrap-table#562]
Hi i have a problem the title of the first column is ok but all other columns the title is in double like this :
![bootstrap-table](https://cloud.githubusercontent.com/assets/11190696/6368088/a4e5f5da-bcd9-11e4-84bc-33575f929b24.gif)

I testing this in firefox and internet explorer same result.
I hope your help :+1:

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle or some code?

**Comment by camustre** [comment]
like this ?

<table data-toggle="table" data-url="secouristes.json" data-cache="false" data-height="20" data-show-header="false">
    <thead>
        <tr>
            <th data-width="250" data-field="NOM">Nom</th>
            <th data-width="40" data-field="SERVICE">Service</th>
            <th data-width="40" data-field="ETAGE">Etage</th>
			<th data-width="40" data-field="NUMERO">Numero</th>
        </tr>
    </thead>
	</table>
	<script src="bootstrap/js/jquery-2.1.1.js"></script>
	<script src="bootstrap/js/bootstrap.min.js"></script>
	<script src="bootstrap/js/bootstrap-table.min.js"></script>

**Comment by camustre** [comment]
like this ?
![code](https://cloud.githubusercontent.com/assets/11190696/6388292/9c67948a-bd98-11e4-9e73-14886c3bdd87.gif)

**Comment by wenzhixin** [comment]
Have you imported the css files?

**Comment by camustre** [comment]
hello ! yes i do 
![css import](https://cloud.githubusercontent.com/assets/11190696/6436764/ed3a5702-c0b4-11e4-9849-b5f5ee3b3fb7.gif)

**Comment by wenzhixin** [comment]
Hi @camustre, please update to the latest version and test this issue again.

**Comment by wenzhixin** [comment]
This bug have been fixed.
