### ISSUE TITLE
data-checkbox: Pagination resets checkboxes

### ISSUE THREAD

**Issue by FloU65** [wenzhixin/bootstrap-table#5620]
**Bootstraptable version(s) affected**:
1.18.2

**Description**  
A data-checkbox column combined with pagination only works if the data-checkbox column is the tables **first** column. Otherwise the selected checkboxes get resetted on changing the page.

**Example**  
https://live.bootstrap-table.com/code/FloU65/6845

**Comment by UtechtDustin** [comment]
This is not a bug, please use the option [maintainMetaData](https://bootstrap-table.com/docs/api/table-options/#maintainmetadata).

Example: https://live.bootstrap-table.com/code/UtechtDustin/6846

**Comment by FloU65** [comment]
Thank you for your support and quick response.
