### ISSUE TITLE
How to hold the state of checkbox when I refresh the table multiple times?

### ISSUE THREAD

**Issue by NandiniDas** [wenzhixin/bootstrap-table#5622]
I have a bootstrap table with a checkbox column. I can check individual rows and all the rows of the table. The issue is whenever I am clicking the refresh button of the table rapidly multiple times, I am losing the checked state of the check boxes.

**Comment by UtechtDustin** [comment]
@djhvscf I don't think we need a example.
This feature is currently not supported, we have a extension which use e.g. cookies to persists data/configuration after a page reload. But this extension currently don't save the checkbox states.

I'm not sure if we should support that, what do you think @djhvscf @wenzhixin ?

**Comment by NandiniDas** [comment]
Hi,

My table code is given below:

<table id="tableGlVariables" data-toggle="table"
						data-toolbar="#toolbarTableGlVariables"
						data-maintain-selected="true" data-unique-id="id"
						data-response-handler="responseHandlerGlVariables"
						data-cache="false" data-click-to-select="true" data-striped="true"
						data-pagination="true" data-search="true" data-show-columns="true"
						data-show-refresh="true" data-show-multi-sort="true"
						data-sort-priority='[{"sortName":"name","sortOrder":"asc"}]'
						data-page-size="10" data-page-list='[10, 25, 50, 75, 100, 200]'>
						<thead>
							<tr>
								<th data-width="4%" data-field="state" data-checkbox="true"></th>
								<th data-field="name" class="table-column-ellipsis"
									data-sortable="true" data-width="18%">Variable Name</th>
								<th data-field="typeDisplayValue" data-sortable="true"
									data-width="10%">Type</th>
								<th data-field="value" class="table-column-ellipsis"
									data-sortable="true" data-width="34%">Value</th>
								<th data-field="url" class="table-column-ellipsis"
									data-sortable="true" data-width="34%">URL</th>
								
							</tr>
						</thead>
					</table>


       function getIdSelectionsGlVariables() {
        return $.map($('#tableGlVariables').bootstrapTable('getSelections'), function (row) {
            return row.id;
        });
    }


 function responseHandlerGlVariables(res) {
        var selections = getIdSelectionsGlVariables();
        $.each(res, function (i, row) {
            row.state = $.inArray(row.id, selections) !== -1;
        });
        return res;



My problem is when I am clicking the table refresh button multiple times rapidly, the checked/selected rows becomes unchecked. Please suggest a solution to retain the checked status of the rows on refresh.

Thanks

**Comment by djhvscf** [comment]
Hi, we need an example using our online editor

**Comment by djhvscf** [comment]
How did you resolve the issue?
