### ISSUE TITLE
Form Field values disappear when going to a different page or sorting the column

### ISSUE THREAD

**Issue by SleeveShirtholes** [wenzhixin/bootstrap-table#5624]
**Bootstraptable version(s) affected**:
1.18.2

**Description**  
When entering data into form fields the values disappear when going to a different page or when sorting the columns.

**Example**  
https://live.bootstrap-table.com/code/SleeveShirtholes/6861

**Additional context**  
In order to replicate this just enter something in the first row and then either sort the column or got to the next page and go back and the value will disappear.

**Comment by UtechtDustin** [comment]
I'm sorry, but we can't support any use-case.
Right now the table is recreated on every action (page switch, search, etc.) which means the input values are destroyed.

As workaround you can save the values and add them back after a page switch.
