### ISSUE TITLE
'queryParams' doesn't work

### ISSUE THREAD

**Issue by JojoZhangxinye** [wenzhixin/bootstrap-table#5626]
**Bootstraptable version(s) affected**:
4.3.1

**Description**  
For example, I want to screen out the data where Gene ID is G1. 
I used the following code, But it still shows all the data.

`
<script>
  $(document).ready(function(){
    $('#search-table').bootstrapTable({
      url:'../trans/Ni.json',
      pagination:true,
      search:true,
      showColumns: true,
      paginationPreText: "Previous",
      paginationNextText: "Next",
      pageSize: 10,
      pageList: [10, 25, 50, 100],
      queryParams: function(params) {
        var temp = {
          gene_id:'G1'};
        return temp; },
      columns:[
        [
          {
            field:'gene_id',
            title:'Gene ID',
            sortable:true,
            align: 'center',
            valign:'middle',
            rowspan:2
          },
...

`

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by JojoZhangxinye** [comment]
I don't know how to add the json file in this website, so I just use some example data. In this case, I want to creen out the data where City is Pune.
https://live.bootstrap-table.com/code/JojoZhangxinye/6875

**Comment by wenzhixin** [comment]
If you use `client` side pagination, you can use the `filterBy` method to do what you want: https://live.bootstrap-table.com/code/wenzhixin/6878

**Comment by JojoZhangxinye** [comment]
Could I use regexp in the **filterBy** ? If two Cities are included, I cannot retrieve them correctly.
https://live.bootstrap-table.com/code/JojoZhangxinye/6879

**Comment by wenzhixin** [comment]
You can use the `searchText` option: https://live.bootstrap-table.com/code/wenzhixin/6881

**Comment by JojoZhangxinye** [comment]
If I use *searchText* , I will not be able to search further on this result by the search button

**Comment by UtechtDustin** [comment]
@JojoZhangxinye You can write acustom filter algorithm function (using regex) with the filterBy function.
Please check the documentation, do you need more help ?

**Comment by JojoZhangxinye** [comment]
No,thanks for your patience.
