### ISSUE TITLE
Bootstrap 5: Toolbar is aligned left in stead of right and breaks line with button

### ISSUE THREAD

**Issue by aducom** [wenzhixin/bootstrap-table#5627]
Using current version from git

Under bootstrap 5 the small toolbar including the search field shifts to the left. 

**Description**  

**Example**
bootstrap 4:
![image](https://user-images.githubusercontent.com/5610893/110537801-77485680-8123-11eb-9336-04f8f3adacf0.png)

bootstrap 5:
![image](https://user-images.githubusercontent.com/5610893/110537878-90510780-8123-11eb-9e1a-596118dd3fe6.png)

**Comment by aducom** [comment]
Issue was caused by another error, so this one can close.

**Comment by wenzhixin** [comment]
This bug has been fixed in the latest version.
latest(v1.18.2): https://examples.bootstrap-table.com/index.html?bootstrap5
v1.18.1: https://live.bootstrap-table.com/code/wenzhixin/6872
