### ISSUE TITLE
操作列修改row无法引用到原对象

### ISSUE THREAD

**Issue by YSZeng** [wenzhixin/bootstrap-table#5629]
**Bootstraptable version(s) affected**: 
 bootstrap-table-1.18.2

**Description**  
在操作事件中改变row的属性值时，无法引用到我提供的数据源的变量上。

**Example**   
https://live.bootstrap-table.com/code/YSZeng/6894

**Possible  (optional)**  
猜测问题是 版本1.8.0时，Update: Fixed default data shared bug with multiple tables. 这个的改变造成的，我的项目原本是1.6.0版本，升级后遇到当前问题。

**Additional context**

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by YSZeng** [comment]
Description: Changing the property value of "row" during the action event cannot refer to the variable of the data source I provided.
Possible: V1.8.0-->"Update: Fixed default data shared bug with multiple tables."  It was this change that caused the problem.（I was using V1.6.0, Encountering the current problem after upgrading.）

**Comment by YSZeng** [comment]
New:
https://live.bootstrap-table.com/code/YSZeng/7265

**Comment by wenzhixin** [comment]
@YSZeng 直接引用的话确实存在许多问题，所以在最新版本修改了实现，你的问题确实需要重新赋值来同步数据。
```js
dataSource[index] = row
```
或者通过 `getData` 方法来获取：
```js
var dataSource = $("#table").bootstrapTable('getData')
```

例子： https://live.bootstrap-table.com/code/wenzhixin/7315
