### ISSUE TITLE
Selected row color background

### ISSUE THREAD

**Issue by promogest** [wenzhixin/bootstrap-table#563]
I am sorry if this is a trivial question but how can i change the selected row background?
i also need a "singleSelect :true" effect with only one or none rows selected. is it possibile? 
```javascript 
$('#mytable').on('click-row.bs.table', function (e, row, $element) {
        $("#edit_button").removeAttr("disabled");
        $("#delete_button").removeAttr("disabled");
        console.log(row);
        console.log($element);
        $($element).addClass('danger');
    })
```
with this code i can catch the event, make some changes to toggles and make danger the row but i can go further and i have 
TypeError: $tr.find(...)[0] is undefined bootstrap-table.js:1124
in the console.
thanks

**Comment by djhvscf** [comment]
Do you have a JSFiddle?

**Comment by promogest** [comment]
http://jsfiddle.net/promogest/e3nk137y/766/
it change background color on the selected row but i can't restore original color when change the new selected and make the new one green

**Comment by haideraliarain** [comment]
@promogest  i have updated js script (removed class if already there) and it will do as u require.

**Comment by djhvscf** [comment]
@promogest  I think there is a solution now! Thanks @haideraliarain

**Comment by djhvscf** [comment]
@wenzhixin This can be an example for issues page, isn't it?

**Comment by promogest** [comment]
Fantastic. Simple and beautifull
thanks

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#563.html

**Comment by christiansum** [comment]
Good day Guys ! I want to do this, but verifying the information given by $element. This variable don't have the TR ID, shows only a Json with the row data. Someone can help me with that ?
 Thank you !

![image](https://cloud.githubusercontent.com/assets/12927336/16880310/dd9b58c6-4a71-11e6-8c92-5bc17a23fd53.png)

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/documentation/#events
@christiansum

**Comment by christiansum** [comment]
Actually I used this information, but when I catch the event does not work.
    
![image](https://cloud.githubusercontent.com/assets/12927336/16881658/74460eaa-4a78-11e6-9a60-10e364aac6c4.png)

![image](https://cloud.githubusercontent.com/assets/12927336/16881746/dd53f1b4-4a78-11e6-8e6a-3f37b13842dd.png)

**Comment by djhvscf** [comment]
![sdfasdf](https://cloud.githubusercontent.com/assets/4496763/16884493/fc8b8a66-4a86-11e6-804e-334af5a3a524.PNG)

if you see the function receives three parameters

@christiansum

**Comment by christiansum** [comment]
Holy Cow ! I feel a little dummy but... It works ! Thank you too much !
