### ISSUE TITLE
Filter Contol "data-filter-default"

### ISSUE THREAD

**Issue by monumatik** [wenzhixin/bootstrap-table#5630]
**Bootstraptable version(s) affected**:
https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js
https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js

**Description**  
Problem with Filter Control extension:
1. When i use integer as key in data-filter-default (e.g. data-filter-default="1") default value is not set:
    https://live.bootstrap-table.com/code/monumatik/6906
2. "filter" data are not sending in request after page reload (i have set data-filter-default like in example)
![image](https://user-images.githubusercontent.com/40207400/110966935-1bb1df00-8356-11eb-9d35-21b98edcc29a.png)
it works only when i select filter value manually
![image](https://user-images.githubusercontent.com/40207400/110967696-f83b6400-8356-11eb-8c69-3faec50c9d10.png)

https://live.bootstrap-table.com/code/monumatik/6904

**Comment by yeezy69** [comment]
The filter-control column option data-filter-default="string" is ignored at all when bootstrap-table option data-side-pagination=server with an ajax-datasource is used. 

If you call up the live-demo, you will see "Item 55" in the input field, but the search will not start. 

https://live.bootstrap-table.com/code/yeezy69/7439

However, if you remove data-side-pagination="server" and click the "Run" button again, the default search works as expected.

Tested with 1.18.3.

Thank you!

**Comment by yeezy69** [comment]
Just a tip: I looked into source and i found in bootstrap-table-filter-control.js (v1.18.3) round about line 2550 this:

```
if (that.options.sidePagination !== 'server' && !that.options.height) {
    that.triggerSearch();
}
```

When i remove "that.options.sidePagination !== 'server'" the data-filter-default option works for me, when bootstrap-table option data-side-pagination=server with an ajax-datasource is used. However, I don't know if removing it will break something else. For some reason the if-query will have been built in i think.

**Comment by djhvscf** [comment]
This is fixed here: https://github.com/wenzhixin/bootstrap-table/pull/5583

Example with fix: https://live.bootstrap-table.com/code/yeezy69/7439

**Comment by UtechtDustin** [comment]
@djhvscf if i use the example from @monumatik and use your branch the example is broken (select will not be displayed) and there is a error message in the console `Uncaught TypeError: r.default.fn.bootstrapTable is undefined`.

Example:https://live.bootstrap-table.com/code/UtechtDustin/9729

**Comment by djhvscf** [comment]
it is not displayed because you are not selecting the filter control extension

<img width="622" alt="Screen Shot 2021-11-25 at 14 40 43" src="https://user-images.githubusercontent.com/4496763/143498136-3139034e-5e1a-423c-bb91-4a98d4678191.png">

**Comment by UtechtDustin** [comment]
You're right, i just opened the example of @monumatik and changed the branch/source.
He used a cdn instead of libraries option of the editor.
