### ISSUE TITLE
Export options 'XLSX' no working 

### ISSUE THREAD

**Issue by PhHitachi** [wenzhixin/bootstrap-table#5631]
Hi, 

i have problem when exporting table to  xlsx this working on latest version just goto https://live.bootstrap-table.com/example/extensions/export.html

and add 'xlsx' to exportTypes and click it.

![Untitled](https://user-images.githubusercontent.com/44565442/111028389-52a8f300-8431-11eb-90b2-5ed9a4bc81a1.png)

**Comment by UtechtDustin** [comment]
This is not a bug, you have to include the javascript file for xlsx.
This is also documentated on the github page of the [tableExport plugin](https://github.com/hhurz/tableExport.jquery.plugin).

Example: https://live.bootstrap-table.com/code/UtechtDustin/6920
