### ISSUE TITLE
Exporting PDF with long text not properly read text in exported PDF

### ISSUE THREAD

**Issue by PhHitachi** [wenzhixin/bootstrap-table#5632]
when i try to export pdf with long address not full text can read

![Untitled](https://user-images.githubusercontent.com/44565442/111028512-1033e600-8432-11eb-9bed-7ca6ad402b71.png)

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
Just as hint: this could be a issue/bug of the underlaying export lib.

**Comment by PhHitachi** [comment]
sure here:
https://live.bootstrap-table.com/code/PhHitachi/6952

**Comment by PhHitachi** [comment]
as you can see the text overflow return to "..."

**Comment by UtechtDustin** [comment]
You have to configure the export plugin, as example i c&p from there [github repository](https://github.com/hhurz/tableExport.jquery.plugin) some options.
So please check the options of the export plugin :-)

Example: https://live.bootstrap-table.com/code/UtechtDustin/6967
