### ISSUE TITLE
sorter not sorting when columns have  indentical field names

### ISSUE THREAD

**Issue by markzv** [wenzhixin/bootstrap-table#5633]
I have a bootstrapTable with source data being a nested json structure and the table uses  identical column fields , each with their own formatter and sorter.

Column sorting of such fields does not work as expected.

When clicking on column name to perform sort, multiple columns widgets (arrows up and down) are highlighted at the same time and the rows are always sorted by the first column with identical field value. In example image below I clicked the "started" column, but 3 columns widgets were highlighted and rows were sorted by Name column
![Selection_180](https://user-images.githubusercontent.com/37646661/111053491-677c9980-84b8-11eb-8048-7e91d281700a.png)

Example of three such table rows
```
, { sorter:"nameSorter", sortable: true, field: 'status.containerStatuses',  title: 'Name' ,   formatter:"podName"         }
, { sorter:"containerSorter", sortable: true, field: 'status.containerStatuses',  title: 'Image' ,  formatter:"podContainers"   }
, { sorter:"dateSorter", sortable: true,   field: 'status.containerStatuses',  title: 'started', formatter:"podStart"        } //
```

```
function podStart(value, row, index, field) {
  var podContainerStarts = '';
  for (var index = 0; index < value.length; index++) {
    if (value[index].state.running != null) {
      podContainerStarts += value[index].state.running.startedAt;
    } else {
      podContainerStarts += 'NOT running';
    }
    if (index < (value.length - 1)) {
      podContainerStarts += '<br/>';
    }
  }
  return podContainerStarts;
}

function dateSorter (a,b) {
  var val1 = podStart(a);
  var val2 = podStart(b);
  console.log(val1 + ' ' + val2);
  if (val1 < val2) return 1;
  if (val1 > val2) return -1;
  return 0;
}

function podName(value, row, index, field) {
  var podContainerName = '';
  for (var index = 0; index < value.length; index++) {
    podContainerName += value[index].name;
    if (index < (value.length - 1)) {
      podContainerName += '<br/>';
    }
  }
  return podContainerName;
}

function nameSorter (a,b){
  var val1 = podName(a);
  var val2 = podName(b);
  if (val1 < val2) return 1;
  if (val1 > val2) return -1;
  return 0;
}

```

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issue, because we got no example from you.
If you still need help, please let us know and provide us an example.
