### ISSUE TITLE
Misaligned colums in footer

### ISSUE THREAD

**Issue by mtngnn** [wenzhixin/bootstrap-table#5634]
I've seen on several pages that there is a bug about alignin footer when you make the screen small.
İf the length of text written in footer is bigger than the length of the row above then footer stays wider. This issue is still remaining.

**I am using 1.18.2 ( The last version )**

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issues, as we got no response from you within 7 days.
If you still need help, please provide us an example.
