### ISSUE TITLE
Toggle Columns in grouped headers

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#5637]
**Description**  
When a grouped header (aka nested) has 1 nested level (like "Price" and "Total" in the example) there is a strange behaviour: I would expect a way to hide the whole column, yet when I hide "Total", "Price" remains visible. Is there a way to hide that?
You can see it works fine in case the 2nd level header has more than 1 element: I hide `Id` and `Name` and `Key` is automatically hidden.

**Expected behaviour**  
"Price" header being hidden when I hide "Total".

**Actual behaviour**  
"Price" stays visible.

**Example**  
https://live.bootstrap-table.com/code/antonioaltamura/6940

**Comment by ko22009** [comment]
![image](https://user-images.githubusercontent.com/11016041/112558140-de3a6080-8def-11eb-8023-d6d755cd53b5.png)
colspanIndex: 2, fieldIndex: 2, duplicated

**Comment by wenzhixin** [comment]
Same as #5656

**Comment by antonioaltamura** [comment]
I'm not clear whether this issue has been solved

**Comment by wenzhixin** [comment]
We do not support the case where the `colspan` and `rowspan` of two fields of the same column are both 1.
Workaround for your example: https://live.bootstrap-table.com/code/wenzhixin/10395
