### ISSUE TITLE
表格打印格式化的对象时不显示值

### ISSUE THREAD

**Issue by xiongtete0519** [wenzhixin/bootstrap-table#5638]
Please read: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports
and post issue to: https://github.com/wenzhixin/bootstrap-table/issues, thanks!
# 问题描述：
**表格打印碰到对象的时候出现object问题，我在js里面是用formatter格式化显示的(表格里面我显示的是对象的属性)，但是打印就会出现object**
## 打印之前的界面:
**圈起来那两个都是对象，我只取了其中一个属性**
![HDH2N(NS9B@TDPF@G4~O )U](https://user-images.githubusercontent.com/66518135/111319924-74a8ac80-86a1-11eb-9e1f-7dea54e12990.png)
## 点击打印之后:
![QHK_YED%( 5}%UHP7U9 OKN](https://user-images.githubusercontent.com/66518135/111319987-82f6c880-86a1-11eb-9ff0-b3d694fac34e.png)
这个怎么解决？
## 我的table标签：
` <table id="table" class="table" data-click-to-select="true"
                data-show-print="true">
            </table>`

**Comment by wenzhixin** [comment]
麻烦提供下在线例子。
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by xiongtete0519** [comment]
# 1、我的代码如下，主要是wellInfo和alarmInfo这两个字段打印的时候出现问题了
 $('#table').bootstrapTable({
            url:'/opms/oilDaily/listByMonthReport',
            toolbar:'#toolbar',
            dataType:'json',            //服务器返回的数据类型
            method:'post',              //请求方式
            contentType: "application/x-www-form-urlencoded;charset=UTF-8",//发送到服务器的数据编码类型
            pagination:true,    //是否显示分页
            pageSize:8,         //设置每页的记录行数
            pageList: [8,16,32,64,256,'All'],  //可供选择的每页的行数
            pageNumber:1,       //设置首页页码
            singleSelect:false, //设置是否单选
            checkboxHeader: true,
            sortable:true,      //是否启用排序
            sortOrder:'asc',    //排序方式
            showRefresh:true,   //是否显示刷新按钮
            showToggle:true,    //是否显示详细视图和列表视图的切换按钮
            showColumns:true,   //选择要显示的列
            striped: true,      //是否显示行间隔色
            clickToSelect:true, //是否启用点击选中行
            cache:false,            //禁用AJAX数据缓存
            sidePagination:'server',   //服务端处理分页
            queryParamsType:"undefined",    //设置参数格式
            showExport: true,           //是否显示导出按钮
            buttonsAlign: "right",//按钮位置
            exportDataType:"basic", //导出的数据类型，支持basic、all 、selected
            exportOptions:{
                ignoreColumn:[0],      //导出数据忽略第一列
                fileName:'油井月报表',     //导出数据的文件名
                worksheetName:'sheet1',//表格工作区名称
                tableName:'油井月报表',
                excelstyles:['background-color','color','font-size','font-weight']
            },
            Icons:'glyphicon glyphicon-export',                         //出示
            exportTypes:['json','xml','csv','xlsx','txt','sql','excel','pdf'], //导出类型
            queryParams:function queryParams(params) {//设置查询参数
                var param={
                    page:params.pageNumber,     //首页页码
                    rows:params.pageSize,       //每页的记录数
                    "wellInfo.wellId":$('#wellId').val(),   //井编号
                    oilTimeFrom:$('#oilTimeFrom').val(),    //开始日期
                    oilTimeTo:$('#oilTimeTo').val(),         //截止日期
                    "area.areaId":$('#areaId option:selected').val()//作业区编号
                };
                return param;
            },
            columns:[/*{
                checkbox:true
            },*/{
                title:'序号',
                field:'oilId',
                align:'center'
            },{
                title:'油井编号',
                field:'wellInfo',
                align:'center',
                formatter:function (value,row,index) {
                    if (row.wellInfo){
                        return row.wellInfo.wellId;
                    }else{
                        return value;
                    }
                }
            },{
                title:'生产日期',
                field:'oilTime',
                align:'center'
            },{
                title:'日产油量(t)',
                field:'outOil',
                align:'center'
            },{
                title:'日产液量(t)',
                field:'outFluid',
                align:'center'
            },{
                title:'日产水量(t)',
                field:'outWater',
                align:'center'
            },{
                title:'日产气量(立方米)',
                field:'outGas',
                align:'center',
            },{
                title:'含水率(%)',
                field:'waterContent',
                align:'center'
            },{
                title:'油气比(%)',
                field:'oilGasRatio',
                align:'center'
            },{
                title:'含盐量(mg/L)',
                field:'oilSalinity',
                align:'center'
            },{
                title:'动液面(m)',
                field:'oilDynamic',
                align:'center'
            },{
                title:'报警级别编号',
                field:'alarmInfo',
                align:'center',
                formatter:function (value,row,index) {
                    if (row.alarmInfo){
                        return row.alarmInfo.alarmId;
                    }else{
                        return value;
                    }
                }
            },{
                title:'油压(MPa)',
                field:'oilPress',
                align:'center'
            },{
                title:'套压(MPa)',
                field:'casingPress',
                align:'center'
            },{
                title:'回压(Mpa)',
                field:'backPress',
                align:'center'
            },{
                title:'报警备注',
                field:'oilRemark',
                align:'center'
            }]
        });
# 2、后端传回来的json格式为:
{
  "rows": [
    {
      "oilId": 1,
      "wellInfo": {
        "wellId": "庆10-001",
        "wellType": "1",
        "abandonWell": "否"
      },
      "oilTime": "2021-02-08",
      "outOil": 100,
      "outFluid": 200,
      "outWater": 100,
      "outGas": 20,
      "waterContent": 50,
      "oilGasRatio": 20,
      "oilSalinity": 100,
      "oilDynamic": 12000,
      "alarmInfo": {
        "alarmId": 1,
        "alarmName": "正常"
      },
      "oilPress": 6,
      "casingPress": 6,
      "backPress": 6
    },
    {
      "oilId": 5,
      "wellInfo": {
        "wellId": "庆10-001",
        "wellType": "1",
        "abandonWell": "否"
      },
      "oilTime": "2021-02-09",
      "outOil": 100,
      "outFluid": 200,
      "outWater": 100,
      "outGas": 20,
      "waterContent": 50,
      "oilGasRatio": 20,
      "oilSalinity": 100,
      "oilDynamic": 12000,
      "alarmInfo": {
        "alarmId": 1,
        "alarmName": "正常"
      },
      "oilPress": 2,
      "casingPress": 2,
      "backPress": 2
    },
    {
      "oilId": 9,
      "wellInfo": {
        "wellId": "庆10-001",
        "wellType": "1",
        "abandonWell": "否"
      },
      "oilTime": "2021-02-10",
      "outOil": 70,
      "outFluid": 100,
      "outWater": 30,
      "outGas": 8,
      "waterContent": 30,
      "oilGasRatio": 11,
      "oilSalinity": 9,
      "oilDynamic": 10000,
      "alarmInfo": {
        "alarmId": 1,
        "alarmName": "正常"
      },
      "oilPress": 2,
      "casingPress": 3,
      "backPress": 4
    },
    {
      "oilId": 10,
      "wellInfo": {
        "wellId": "庆10-001",
        "wellType": "1",
        "abandonWell": "否"
      },
      "oilTime": "2021-02-11",
      "outOil": 80,
      "outFluid": 100,
      "outWater": 20,
      "outGas": 8,
      "waterContent": 20,
      "oilGasRatio": 10,
      "oilSalinity": 9,
      "oilDynamic": 12000,
      "alarmInfo": {
        "alarmId": 1,
        "alarmName": "正常"
      },
      "oilPress": 2,
      "casingPress": 3,
      "backPress": 4
    },
    {
      "oilId": 11,
      "wellInfo": {
        "wellId": "庆10-001",
        "wellType": "1",
        "abandonWell": "否"
      },
      "oilTime": "2021-02-12",
      "outOil": 68,
      "outFluid": 100,
      "outWater": 32,
      "outGas": 8,
      "waterContent": 32,
      "oilGasRatio": 0.12,
      "oilSalinity": 9,
      "oilDynamic": 12000,
      "alarmInfo": {
        "alarmId": 1,
        "alarmName": "正常"
      },
      "oilPress": 2,
      "casingPress": 3,
      "backPress": 4
    },
    {
      "oilId": 14,
      "wellInfo": {
        "wellId": "庆10-001",
        "wellType": "1",
        "abandonWell": "否"
      },
      "oilTime": "2021-02-13",
      "outOil": 71,
      "outFluid": 102,
      "outWater": 31,
      "outGas": 10,
      "waterContent": 30.39,
      "oilGasRatio": 14,
      "oilSalinity": 9,
      "oilDynamic": 12000,
      "alarmInfo": {
        "alarmId": 1,
        "alarmName": "正常"
      },
      "oilPress": 2,
      "casingPress": 3,
      "backPress": 4
    },
    {
      "oilId": 15,
      "wellInfo": {
        "wellId": "庆10-001",
        "wellType": "1",
        "abandonWell": "否"
      },
      "oilTime": "2021-02-14",
      "outOil": 69,
      "outFluid": 102,
      "outWater": 33,
      "outGas": 8,
      "waterContent": 32.35,
      "oilGasRatio": 12,
      "oilSalinity": 9,
      "oilDynamic": 12000,
      "alarmInfo": {
        "alarmId": 1,
        "alarmName": "正常"
      },
      "oilPress": 2,
      "casingPress": 3,
      "backPress": 4
    },
    {
      "oilId": 16,
      "wellInfo": {
        "wellId": "庆10-001",
        "wellType": "1",
        "abandonWell": "否"
      },
      "oilTime": "2021-02-15",
      "outOil": 68,
      "outFluid": 100,
      "outWater": 32,
      "outGas": 8,
      "waterContent": 32,
      "oilGasRatio": 0.12,
      "oilSalinity": 9,
      "oilDynamic": 12000,
      "alarmInfo": {
        "alarmId": 1,
        "alarmName": "正常"
      },
      "oilPress": 2,
      "casingPress": 3,
      "backPress": 4
    }
  ],
  "total": 59
}

**Comment by ko22009** [comment]
@xiongtete0519, He means write your example in https://live.bootstrap-table.com/

**Comment by xiongtete0519** [comment]
An online example is as follows：
https://live.bootstrap-table.com/code/xiongtete0519/7034

**Comment by ko22009** [comment]
@xiongtete0519 
I doesn't see your problem:
![image](https://user-images.githubusercontent.com/11016041/112684846-750d2880-8e95-11eb-9990-569fd97676c7.png)

**Comment by xiongtete0519** [comment]
@ko22009 
Thank you very much for your reply. I will go and check it again
