### ISSUE TITLE
data-response-handler属性不生效

### ISSUE THREAD

**Issue by travelcode** [wenzhixin/bootstrap-table#5639]
通过js回调函数response-handler能够生效,但是通过data-response-handler属性引用不生效

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
@travelcode 请确认是否已经定义了对应的方法，例子： https://live.bootstrap-table.com/code/wenzhixin/6970

**Comment by travelcode** [comment]
i had forget this question&nbsp; &nbsp;how to happend,so please close this issue,maybe caused this issue because of another issue or wrong settings,but the bootstrap-table frame&nbsp; is silence when error happend.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dennis ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午2:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wenzhixin/bootstrap-table] data-response-handler属性不生效 (#5639)





 
Can you translate this issue to english, please?
