### ISSUE TITLE
how did remove row By index

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#564]
my row data not id value,

**Comment by neozhu** [comment]
please，help me ，have any solution?

**Comment by djhvscf** [comment]
Do you have some example of your code?? I think I can help you but I have to know how is your table @neozhu

**Comment by neozhu** [comment]
我有一张表的ID是自增的int，我需要用户一次性新增多条，然后一次性提交到Server端保存，判断ID为0的表示新增，非0表示更新，因此在页面部分用户新增了3条这时没有ID或ID=0，但肯定需要给用户删除的功能，所以我要根据选择的行或是当前行的删除操作 删掉当前行的记录

**Comment by djhvscf** [comment]
@neozhu  You can use something like this:

```javascript
var $table = $('#table'),
function() {
       var rows = $table.bootstrapTable('getSelections'),
	rowsIds = [],
	data = $table.bootstrapTable('getData'),
	i = 0;
		
	for(; i < rows.length; i++) {
		rowsIds[i] = data.indexOf(rows[i]);
	}
	return rowsIds;
};
```

But for use this function you have to add this to your **th**s 
```html
<th data-checkbox="true"></th>
```

**Comment by neozhu** [comment]
你看是否能这样
'click .remove': function (e, value, row, index) {
 $('#table').bootstrapTable('remove', {
                    field: 'index',
                    values: [index]
                });
}

**Comment by wenzhixin** [comment]
Do not support remove by index, but you can handle the response to add a field like index, for example:
```
responseHandler: function (res) {
    $.each(res, function (i, row) {
        row.index = i;
    });
}
```
And then, you can use the methods mentioned above.

**Comment by neozhu** [comment]
BootstrapTable.prototype.remove = function (params) {
        var len = this.options.data.length,
            i, row;

        if (!params.hasOwnProperty('field') || !params.hasOwnProperty('values')) {
            return;
        }

        for (i = len - 1; i >= 0; i--) {
            row = this.options.data[i];

            if (!row.hasOwnProperty(params.field)) {
                return;
            }
            if ($.inArray(row[params.field], params.values) !== -1) {
                this.options.data.splice(i, 1);
            }
        }

        if (len === this.options.data.length) {
            return;
        }

        this.initSearch();
        this.initPagination();
        this.initBody(true);
    };

在这里把filed:index,或$index作为参数 在把values 传入 应该修改起来不困难吧

**Comment by wenzhixin** [comment]
但是，当 row 本身有 index 这个属性的时候就会冲突了。

**Comment by neozhu** [comment]
所以用field:$index做为特殊字段的参数，但row index 还得考虑一下分页的情况要加上当前页来  计算出真正所在的index。

**Comment by neozhu** [comment]
因为实际情况很多表示有2个以上的字段组合成关键字的。这是用你提供的方法就不好办了，还得通过当前行来进行删除更新操作会更佳简单

**Comment by wenzhixin** [comment]
OK，我会考虑你所说的情况的。

**Comment by neozhu** [comment]
好，多谢了

**Comment by neozhu** [comment]
BootstrapTable.prototype.remove = function (params) {
        //console.log(params);
        //console.log(this.options);
        var len = this.options.data.length,
            i, row;
       
        if (!params.hasOwnProperty('field') || !params.hasOwnProperty('values')) {
            return;
        }
        if (params.field == '$index') {
            $.each(params.values, function (idx, ivalue) {
                this.options.data.splice(ivalue, 1);
            })
            
        } else {
            for (i = len - 1; i >= 0; i--) {
                row = this.options.data[i];

                if (!row.hasOwnProperty(params.field)) {
                    return;
                }
                if ($.inArray(row[params.field], params.values) !== -1) {
                    this.options.data.splice(i, 1);
                }
            }
        }

        if (len === this.options.data.length) {
            return;
        }

        this.initSearch();
        this.initPagination();
        this.initBody(true);
    };

我暂时先这样修改一下

**Comment by wenzhixin** [comment]
OK

**Comment by panxq5** [comment]
@wenzhixin have you add this function?

**Comment by wenzhixin** [comment]
No @panxq5

**Comment by boyongjiong** [comment]
@neozhu  我有个问题呀，你这儿的param.values  传递的是什么值呀，如果是当前行的值的话，

$.each(foo, function (idx, value) { ... this })   

这里面的this不是指向了 foo 吗？  不好意思，没看懂-。- ，能不能说一下

**Comment by DThorDFT** [comment]
I thought @neozhu's suggestion was a good addition to the remove function.  I am using it to remove the last row of the table.

**Comment by amedeogautiero** [comment]
in rowClick event... add a fictitious field, in my case **todelete**.
Update the row by index with new field and than delete the same row

rowClick = (row, $element, field) => {
    var index = $element.attr("data-index");
    row.todelete = true;   // todelete  is new field
   
    $("#table").bootstrapTable('updateRow', {
        index: index,
        row: row,
        replace: true
    });

    $("#table").bootstrapTable('remove', {
        field: 'todelete',
         values: [true]
     });
}
