### ISSUE TITLE
Filter Control searchOnEnterKey bug: Only current field included in AJAX payload

### ISSUE THREAD

**Issue by Maximilian-L** [wenzhixin/bootstrap-table#5640]
Hey there,

When using the Filter Control extension and enabling the searchOnEnterKey option, Bootstrap Table will only include in the Ajax payload the field that had focus while the Enter key was clicked.

For instance, let's assume the following:
- I have two fields, firstName and lastName
- I'll go ahead and enter firstName, then lastName and then press Enter
-> The filter JSON sent via AJAX will be {lastName: "whatever lastName was entered"} 

Instead, I would expect it to include all other fields, in this case the firstName, as well.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by djhvscf** [comment]
@Maximilian-L  This is not reproducible in this PR https://github.com/wenzhixin/bootstrap-table/pull/5583. Please review it again and if it is still hapenning, please open a new issue and provide an online example

**Comment by tblima** [comment]
I have the same problem. In the example below, I tried to fill the column 'Item Name' with 'Item 0' (without pressing enter) and then fill the 'Item Price' with '$' and finally pressing enter. Only the last input (the focused one) is added to filter. Is it possible to filter by all the columns at once?

[https://live.bootstrap-table.com/code/tblima/8112](https://live.bootstrap-table.com/code/tblima/8112)

Thanks in advance
