### ISSUE TITLE
Filter Control Inputs Issue When Using AJAX

### ISSUE THREAD

**Issue by Maximilian-L** [wenzhixin/bootstrap-table#5641]
Hey there,

I'm currently experiencing the issue that once Bootstrap Table receives an AJAX response, the whole table appears to be regenerated, including the table head containing the Filter Control input elements.
This causes trouble when the user is still typing as the AJAX response arrives since the input loses focus and/or the last few letters typed into the input fields are removed.
I have already added debouncing, however, depending on the timing, the issue still appears.
I have also tried implementing the searchOnEnterKey feature so the AJAX call is only made when the user finished typing, however, that option seems to only include the last edited field on the filter JSON that is part of the AJAX payload.

What I would expect is that only the table contents are refreshed, without the header row.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issues, as we got no response from you within 7 days.
If you still need help, please provide us an example.
