### ISSUE TITLE
Sort does not work for fields that have been formatted

### ISSUE THREAD

**Issue by lachie-92** [wenzhixin/bootstrap-table#5642]
Please read: https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports
and post issue to: https://github.com/wenzhixin/bootstrap-table/issues, thanks!

Hi, im having a problem getting my colums that have been formated to sort in my table, just wondeing if this is a bug or its not meant to be done? Code below:

<html>

<body>

<table id="table"
       data-search="true"
       data-show-columns="true"
       data-pagination="true"
       data-page-list="[10, 25, 50, 100, all]"
       data-show-refresh="true"
       data-export-data-type="all"
       data-show-export="true"
       data-url="getdata">
</table>

</body>
</html>

<script>
    var $table = $('#table')

    $(function() {
        $table.bootstrapTable({
            columns: [{
                title: 'Customer Name',
                field: 'customer_name',
                sortable: true,
                formatter: function (value, row) {
                    return '<a href = "/nova/resources/unleashed-customers/' + row.customer_guid +'" target="_blank">' + row.trading_name + ' [' + row.customer_code + ']</a>'
                }
            }, {
                title: 'Brand',
                field: 'brand',
                sortable: true,
            }, {
                title: 'State',
                field: 'secondary_classifications',
                sortable: true,
            }, {
                title: 'Channel',
                field: 'primary_channel',
                sortable: true,
            }, {
                title: 'Tier',
                field: 'tier',
                sortable: true,
            }, {
                title: 'Last Purchase Date',
                field: 'last_purchase_date',
                sortable: true,
            }, {
                title: 'Last 30 Days',
                field: '30_days',
                formatter: function (value, row) {
                    var color = (row.previous_30_days_sales - row.last_30_days_sales) > 0 ? 'green' : 'red'
                    return '<p style="color: ' + color + '">' + [row.previous_30_days_sales - row.last_30_days_sales] + '</p>'
                },
                sortable: true,
            }, {
                title: 'Last 90 Days',
                field: '90_days',
                formatter: function (value, row) {
                    var color = (row.previous_3_months_sales - row.last_3_months_sales) > 0 ? 'green' : 'red'
                    return '<p style="color: ' + color + '">' + [row.previous_3_months_sales - row.last_3_months_sales] + '</p>'
                },
                sortable: true,
            }, {
                title: 'Last 180 Days',
                field: '180_days',
                formatter: function (value, row) {
                    var color = (row.previous_6_months_sales - row.last_6_months_sales) > 0 ? 'green' : 'red'
                    return '<p style="color: ' + color + '">' + [row.previous_6_months_sales - row.last_6_months_sales] + '</p>'
                },
                sortable: true,
            }, {
                title: 'Last 365 Days',
                field: '365_days',
                formatter: function (value, row) {
                    var color = (row.previous_12_months_sales - row.last_12_months_sales) > 0 ? 'green' : 'red'
                    return '<p style="color: ' + color + '">' + [row.previous_12_months_sales - row.last_12_months_sales] + '</p>'
                },
                sortable: true,
            }, ]
        })

    })

</script>

**Comment by lachie-92** [comment]
https://live.bootstrap-table.com/code/lachie-92/6945

**Comment by lachie-92** [comment]
test.json contains the following:
`[
    {
        "id": 1,
        "customer_code": "C0000001",
        "customer_guid": "1234567",
        "brand": "VMS",
        "tier": 4,
        "last_rep_visit_date": null,
        "next_rep_visit_date": null,
        "last_purchase_date": "2019-05-21",
        "last_30_days_sales": "1.00",
        "previous_30_days_sales": "1.00",
        "last_3_months_sales": "1.00",
        "previous_3_months_sales": "1.00",
        "last_6_months_sales": "1.00",
        "previous_6_months_sales": "1.00",
        "last_12_months_sales": "1.00",
        "previous_12_months_sales": "1.00",
        "created_at": "2021-03-15 15:45:00",
        "updated_at": "2021-03-15 15:45:00",
        "primary_classifications": "Australia",
        "secondary_classifications": "NSW",
        "primary_channel": "Allied Healthcare",
        "secondary_channel": "Naturopath",
        "trading_name": "Company 1"
    },
    {
        "id": 2,
        "customer_code": "C0000002",
        "customer_guid": "1234567",
        "brand": "VMS",
        "tier": 4,
        "last_rep_visit_date": null,
        "next_rep_visit_date": null,
        "last_purchase_date": "2019-05-21",
        "last_30_days_sales": "2.00",
        "previous_30_days_sales": "2.00",
        "last_3_months_sales": "2.00",
        "previous_3_months_sales": "2.00",
        "last_6_months_sales": "2.00",
        "previous_6_months_sales": "2.00",
        "last_12_months_sales": "2.00",
        "previous_12_months_sales": "2.00",
        "created_at": "2021-03-15 15:45:00",
        "updated_at": "2021-03-15 15:45:00",
        "primary_classifications": "Australia",
        "secondary_classifications": "VIC",
        "primary_channel": "Allied Healthcare",
        "secondary_channel": "Naturopath",
        "trading_name": "Company 2"
    },
    {
        "id": 3,
        "customer_code": "C0000003",
        "customer_guid": "1234567",
        "brand": "VMS",
        "tier": 4,
        "last_rep_visit_date": null,
        "next_rep_visit_date": null,
        "last_purchase_date": "2019-05-21",
        "last_30_days_sales": "3.00",
        "previous_30_days_sales": "3.00",
        "last_3_months_sales": "3.00",
        "previous_3_months_sales": "3.00",
        "last_6_months_sales": "3.00",
        "previous_6_months_sales": "3.00",
        "last_12_months_sales": "3.00",
        "previous_12_months_sales": "3.00",
        "created_at": "2021-03-15 15:45:00",
        "updated_at": "2021-03-15 15:45:00",
        "primary_classifications": "Australia",
        "secondary_classifications": "QLD",
        "primary_channel": "Allied Healthcare",
        "secondary_channel": "Naturopath",
        "trading_name": "Company 3"
    },
    {
        "id": 4,
        "customer_code": "C0000004",
        "customer_guid": "1234567",
        "brand": "VMS",
        "tier": 4,
        "last_rep_visit_date": null,
        "next_rep_visit_date": null,
        "last_purchase_date": "2019-05-21",
        "last_30_days_sales": "4.00",
        "previous_30_days_sales": "4.00",
        "last_3_months_sales": "4.00",
        "previous_3_months_sales": "4.00",
        "last_6_months_sales": "4.00",
        "previous_6_months_sales": "4.00",
        "last_12_months_sales": "4.00",
        "previous_12_months_sales": "4.00",
        "created_at": "2021-03-15 15:45:00",
        "updated_at": "2021-03-15 15:45:00",
        "primary_classifications": "Australia",
        "secondary_classifications": "TAS",
        "primary_channel": "Distributor",
        "secondary_channel": "Naturopath",
        "trading_name": "Company 4"
    },
    {
        "id": 5,
        "customer_code": "C0000005",
        "customer_guid": "1234567",
        "brand": "VMS",
        "tier": 4,
        "last_rep_visit_date": null,
        "next_rep_visit_date": null,
        "last_purchase_date": "2019-05-21",
        "last_30_days_sales": "5.00",
        "previous_30_days_sales": "5.00",
        "last_3_months_sales": "5.00",
        "previous_3_months_sales": "5.00",
        "last_6_months_sales": "5.00",
        "previous_6_months_sales": "5.00",
        "last_12_months_sales": "5.00",
        "previous_12_months_sales": "5.00",
        "created_at": "2021-03-15 15:45:00",
        "updated_at": "2021-03-15 15:45:00",
        "primary_classifications": "Australia",
        "secondary_classifications": "SA",
        "primary_channel": "Allied Healthcare",
        "secondary_channel": "Naturopath",
        "trading_name": "Company 5"
    },
    {
        "id": 6,
        "customer_code": "C0000002",
        "customer_guid": "1234567",
        "brand": "VMS",
        "tier": 4,
        "last_rep_visit_date": null,
        "next_rep_visit_date": null,
        "last_purchase_date": "2019-05-21",
        "last_30_days_sales": "6.00",
        "previous_30_days_sales": "6.00",
        "last_3_months_sales": "6.00",
        "previous_3_months_sales": "6.00",
        "last_6_months_sales": "6.00",
        "previous_6_months_sales": "6.00",
        "last_12_months_sales": "6.00",
        "previous_12_months_sales": "6.00",
        "created_at": "2021-03-15 15:45:00",
        "updated_at": "2021-03-15 15:45:00",
        "primary_classifications": "Australia",
        "secondary_classifications": "NSW",
        "primary_channel": "Pharmacy",
        "secondary_channel": "Naturopath",
        "trading_name": "Company 6"
    }
]
`

**Comment by wenzhixin** [comment]
You need to use the [`sorter` column option](https://bootstrap-table.com/docs/api/column-options/#sorter) to custom your own sort.
Working example: https://live.bootstrap-table.com/code/wenzhixin/6948
