### ISSUE TITLE
Dropdowns in do not work in bootstrap v5 example

### ISSUE THREAD

**Issue by Mertsch** [wenzhixin/bootstrap-table#5643]
**Bootstraptable version(s) affected**:
Version used in https://examples.bootstrap-table.com/index.html?bootstrap5

**Description**  
When opening https://examples.bootstrap-table.com/index.html?bootstrap5
The `Showing 1 to 10 of 800 rows` `10 rows per page` dropdown to select a different page size other then `10` does not work

It works fine with v4 https://examples.bootstrap-table.com/index.html?bootstrap4

Also the `Columns` and `Export data` dropdowns do not work either. Maybe a `popper.js` issue?

**Example**  
https://examples.bootstrap-table.com/index.html?bootstrap5

**Comment by wenzhixin** [comment]
Updated: https://github.com/wenzhixin/bootstrap-table-examples/commit/5a09eb34c35a381481f4044502a48648437e106c

https://examples.bootstrap-table.com/index.html?bootstrap5
