### ISSUE TITLE
Sticky header broken in Bootstrap grids

### ISSUE THREAD

**Issue by saitho** [wenzhixin/bootstrap-table#5646]
**Bootstraptable version(s) affected**:

latest? (used the demo)

**Description**  

When placing a table with sticky header in a Bootstrap grid, it takes the full width.
Expected behaviour is that the sticky header stays within the grid area.

**Example**  

https://live.bootstrap-table.com/code/saitho/6954

**Comment by ko22009** [comment]
@saitho, position fixed apply to the window.
If you want set correctly width of the header, you need set by javascript.
By the way you put table to col of the container. you need pass width of the container too.

**Comment by ko22009** [comment]
Subscribe to event scroll down and calculate width from fixed-table-body and position left and set to the fixed-table-container.

![image](https://user-images.githubusercontent.com/11016041/112217416-6e3ba700-8c44-11eb-90c6-c3e31e186eda.png)

**Comment by ko22009** [comment]
#5652
