### ISSUE TITLE
getSelections didnt return all selected rows, 

### ISSUE THREAD

**Issue by saurabhsharma2u** [wenzhixin/bootstrap-table#5647]
**Bootstraptable version(s) affected**:
1.18.2

**Description**  
getSelections didnt return all selected rows, when they are checked and paginated.

**Example**  
https://live.bootstrap-table.com/code/saurabhsharma2u/6963

**Comment by UtechtDustin** [comment]
Works fine for me, i guess your issue is that your using a formatter.
Your Json should contains the "checked: true".

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/6969

**Comment by saurabhsharma2u** [comment]
@wenzhixin @UtechtDustin thank you this work with `data-response-handler="responseHandler"`
you can close the issue.

**Comment by UtechtDustin** [comment]
No problem, your welcome.
