### ISSUE TITLE
Method 'getData' to include Footer data

### ISSUE THREAD

**Issue by rayoray** [wenzhixin/bootstrap-table#5649]
**Description**  
What method can be used to get all the data in the table? $table.bootstrapTable('getData') returns tbody, how can i include tfoot data also?

**Example (optional)**  
$table.bootstrapTable('getData')

**Comment by UtechtDustin** [comment]
We should add an option to get the current footerData similar to the `getData` function.

**Comment by xanish** [comment]
Hey @UtechtDustin can I pick this issue up for contribution? Im assuming I would have to add a function getFooterData() which uses the footerData property  just returns those rows.
