### ISSUE TITLE
Bower fetching 1.5.0 even when 1.6.0 is specified in bower.json

### ISSUE THREAD

**Issue by mwakerman** [wenzhixin/bootstrap-table#565]
I was excited to see the new checkBy and uncheckBy methods so I ran `bower update bootstrap-table` and got the latest version with the following output.

```
bower resolve       git://github.com/wenzhixin/bootstrap-table.git#*
bower download      https://github.com/wenzhixin/bootstrap-table/archive/1.6.0.tar.gz
openbower extract       bootstrap-table#* archive.tar.gz
bower resolved      git://github.com/wenzhixin/bootstrap-table.git#1.6.0
bower install       bootstrap-table#1.6.0
```

However I appear to still have the 1.5.0 files. I confirmed by installing bootstrap-table in another directory and still got the old files.

**Comment by mwakerman** [comment]
Ah I've checked it and it looks like the latest src/bootstrap-table.js has not been built into the latest dist/bootstrap-table.min.js.

Please fix :)

**Comment by wenzhixin** [comment]
Yes @mwakerman, you can look at the changelog file: https://github.com/wenzhixin/bootstrap-table/blob/master/CHANGELOG.md, the dist dir is built when we release a new version, so you can not use the checkBy or uncheckBy method in 1.6.0. But I think you can use src/bootstrap-table.js first.

**Comment by mwakerman** [comment]
Thanks for the information. Can I ask why you do it this way? I would think you would always want the dist the match the src dir? It kind of breaks bower dependencies when 1.6.0 could meen different things.
