### ISSUE TITLE
Better control on paginationItems

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#5650]
In case you have millions of pages you don't want to let the users go to the last page.

**Description**  
I would like to hide the last `paginationItem`.

**Example**  
Original pagination
![page1](https://user-images.githubusercontent.com/6325475/112161575-30f2fd00-8be3-11eb-8d6b-84a6e5bd037f.png)

Last item hidden
![page2](https://user-images.githubusercontent.com/6325475/112161609-36e8de00-8be3-11eb-921e-be07a3535363.png)

Alternatively, a custom text, like "many", Gmail style
![page3](https://user-images.githubusercontent.com/6325475/112161655-410adc80-8be3-11eb-9033-28026d650815.png)

It seems BT doesn't expose APIs to override that. Is there a simple way to accomplish that?

**Comment by ko22009** [comment]
@antonioaltamura, you can pass optional arguments and don't execute this line, which output last element:
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1298
for example
```bash
if (this.options.offLastPaginationItem) {
...
}
```
And after that add pull-request.

**Comment by wenzhixin** [comment]
You can define it yourself with css: https://live.bootstrap-table.com/code/wenzhixin/7054

**Comment by antonioaltamura** [comment]
@wenzhixin the whole point of the ticket is to hide the button only in case the number of the pages is above a defined threshold.

**Comment by wenzhixin** [comment]
for example?

**Comment by antonioaltamura** [comment]
What do you mean? The example is in my first post. I want to hide the last page iff the total number of pages is above a fixed number.
