### ISSUE TITLE
markup bootstrap broken

### ISSUE THREAD

**Issue by ko22009** [wenzhixin/bootstrap-table#5651]
version: 1.18.2

![image](https://user-images.githubusercontent.com/11016041/112215322-13a14b80-8c42-11eb-8fa2-21f1c052a112.png)

I fixed by add style css:

.bootstrap-table .fixed-table-container .fixed-table-body .fixed-table-loading {
  display: none;
}

It was because element just set visible: none, but it is not enough. Need remove from document flow.

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/), we have to see an example with your setup.

**Comment by ko22009** [comment]
@UtechtDustin, https://live.bootstrap-table.com/code/ko22009/7009

**Comment by UtechtDustin** [comment]
Your "fix" don't work proper e.g. the loading text is always hidden.

This is a duplicate of #5439, so i will close this issue.
