### ISSUE TITLE
Optional compile js for development

### ISSUE THREAD

**Issue by ko22009** [wenzhixin/bootstrap-table#5653]
Add feature to config optional compiling scr js files.
Manually I commented and rename path to specific file.
It will be useful pass by arguments

**Comment by UtechtDustin** [comment]
I'm not sure what do you mean with this issue, could you explain it further ?

**Comment by ko22009** [comment]
For example, in development I don't want compile everytime vue js wrapper and another files (locales, extensions).
I changed one file and want compile only one.

**Comment by ko22009** [comment]
#5655

**Comment by UtechtDustin** [comment]
But you can use the src's files for the development enviroment, we only have to compile if we release a new version.
So i'm not sure if we need this feature.

**Comment by ko22009** [comment]
@djhvscf, How I can compile with watching specific file? How I can create example file? But I have not looked for example folder.

**Comment by wenzhixin** [comment]
Added readme: https://github.com/wenzhixin/bootstrap-table/pull/5674/commits/7533354af13423e843ff9593700a59976138a214
