### ISSUE TITLE
The height of each row of the table will become very high

### ISSUE THREAD

**Issue by ilxyil** [wenzhixin/bootstrap-table#5659]
bootstrap-table设置表格height属性以后实现了固定表头，但是当数据量较少的时候，单行数据的高度会被拉的很开，有没有办法解决这个问题。

When I set the height property of the table，I can realize the function of fixed header。but，when the amount of data in the table is small, for example, there is only one data。The height of each row of the table will become very high。

Is there any way to solve this problem？

![Image_20210326132737](https://user-images.githubusercontent.com/81404532/112587971-904a4a80-8e39-11eb-942c-56f56656355f.png)

**Comment by ilxyil** [comment]
When I set the height property of the table，I can realize the function of fixed header。but，when the amount of data in the table is small, for example, there is only one data。The height of each row of the table will become very high。

Is there any way to solve this problem？

**Comment by ko22009** [comment]
@ilxyil, upload your example, please here https://live.bootstrap-table.com/

**Comment by ilxyil** [comment]
I have found the cause of the problem，it's my own problem。

**Comment by ilxyil** [comment]
I have found the cause of the problem，it's my own problem。
