### ISSUE TITLE
The height of each row of the table will become very high

### ISSUE THREAD

**Issue by ilxyil** [wenzhixin/bootstrap-table#5660]
When I set the height property of the table，I can realize the function of fixed header。but，when the amount of data in the table is small, for example, there is only one data。The height of each row of the table will become very high。

Is there any way to solve this problem？

![Image_20210326132737](https://user-images.githubusercontent.com/81404532/112587971-904a4a80-8e39-11eb-942c-56f56656355f.png)

**Comment by UtechtDustin** [comment]
#5660
