### ISSUE TITLE
1.18.3 Vue Component can not working

### ISSUE THREAD

**Issue by angelfind** [wenzhixin/bootstrap-table#5663]
**Bootstraptable version(s) affected**:

1.18.3 -> Vue Component

**Description**  

I use this new version on my project. Vue Component can not working fine. I check example from example's page.  It doesn't work...

**Example**  
https://examples.bootstrap-table.com/#welcomes/vue-component.html

**Comment by wenzhixin** [comment]
It appears to be caused by upgrading `rollup-plugin-vue` to 6.0: #5593
You can temporarily use v1.18.2 to resolve the issue.

**Comment by angelfind** [comment]
Ok, Thank you.

**Comment by A-Projects** [comment]
Error still exists if roll back to version **1.18.2** if download fresh package from NPM. Package in local cache does not contain error.

![изображение](https://user-images.githubusercontent.com/38563625/113383368-72766b80-938c-11eb-90f9-a12aabd6ea36.png)

![изображение](https://user-images.githubusercontent.com/38563625/113383438-9934a200-938c-11eb-9796-c52f63ea2bbe.png)

**Comment by djhvscf** [comment]
@wenzhixin

**Comment by wenzhixin** [comment]
https://examples.bootstrap-table.com/index.html#welcomes/vue-component.html
https://examples.bootstrap-table.com/index.html#welcomes/vue-component.html#view-source
