### ISSUE TITLE
data-filter-control="select"

### ISSUE THREAD

**Issue by cgountanis** [wenzhixin/bootstrap-table#5664]
Does not seem to refresh when empty selection is made. Client side, html generated dynamically, no external JS used. I swear this used to work just fine. Any tips, maybe I missed something.

![image](https://user-images.githubusercontent.com/14899817/113190967-9b7aed00-9222-11eb-96cb-24aa8afc9fc7.png)

![image](https://user-images.githubusercontent.com/14899817/113190903-830ad280-9222-11eb-86f1-248e903b9d13.png)

![image](https://user-images.githubusercontent.com/14899817/113190934-8dc56780-9222-11eb-9eea-0d6c01f725e5.png)

Nothing crazy going on here.
![image](https://user-images.githubusercontent.com/14899817/113191171-daa93e00-9222-11eb-8f09-8069ceec9b1b.png)

The TBODY is filled in with TR/TD via loop. HTML is complete as far as the client sees.

**Comment by cgountanis** [comment]
Even `$('#summaryHomeIndexTable').bootstrapTable('clearFilterControl');` does not work, clears the dropdown but the table does not refresh, zero JS errors in console.

**Comment by djhvscf** [comment]
@UtechtDustin @cgountanis  it is fixed in that PR.

**Comment by cgountanis** [comment]
@UtechtDustin thank you!

**Comment by cgountanis** [comment]
@djhvscf thanks.
