### ISSUE TITLE
filterBy continues to fire off custom algorithm if replaced by implicit 'and'

### ISSUE THREAD

**Issue by plweller3** [wenzhixin/bootstrap-table#5665]
If you run a custom filter, such as:

table.bootstrapTable('filterBy', {type: [0, 1, 3]}, {'filterAlgorithm': myFilter});

then you later call a different filter using an implied "and", such as:

table.bootstrapTable('filterBy', {type: [1, 2]});

The myFilter function will continue to fire off in addition to the new filter.  If you explicitly add the 'and', such as:

table.bootstrapTable('filterBy', {type: [1, 2]}, {'filterAlgoritthm': 'and'});

then the new filter will replace the previous one, as expected.

**Comment by UtechtDustin** [comment]
Please provide us an example using our [online editor](https://live.bootstrap-table.com/).

**Comment by UtechtDustin** [comment]
I'm closing this issue, because we got no response/example from you within 7 days.
If you still need help please provide us an example and we will reopen the issue.
