### ISSUE TITLE
How i can trigger function by clicking pagination button?

### ISSUE THREAD

**Issue by PhHitachi** [wenzhixin/bootstrap-table#5668]
Hi,

How i can trigger function by clicking page button?

like for example:
https://live.bootstrap-table.com/code/PhHitachi/7178

**Comment by djhvscf** [comment]
That is not going ot work since we're preventing the event so it is not bubbling up

https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1410

**Comment by UtechtDustin** [comment]
You can listen to a event of the bootstrap table e.g. onPageChange and then execute your function or if you need to create listener to one button not to all you can listen to the onPostBody event and then setup your own listener.
