### ISSUE TITLE
How can I inject a query params before I sort a column

### ISSUE THREAD

**Issue by Jamesxql** [wenzhixin/bootstrap-table#567]
I can use ('refresh', {query: {xxx: xxx}}) to inject a query param before request the data from the remote server, but how can I inject a query param before I sort a column, the 'onSort' event is not working, do you have any idear?

**Comment by wenzhixin** [comment]
Are you using remote sort?

**Comment by Jamesxql** [comment]
yes, I need inject a query param when I sort the column

**Comment by wenzhixin** [comment]
you can try to use `queryParams` to do that.

**Comment by Jamesxql** [comment]
excellent, thank you very much
