### ISSUE TITLE
Can I use it with EJS and give it a strigify json or just the object?

### ISSUE THREAD

**Issue by eliezra236** [wenzhixin/bootstrap-table#5670]
Hi,
I got really lost with the how to use it with JSON part, couldn't make it work really no matter how much I tried, I just don't understand how to give it a json file.

But I wanted to know if there's a way to give it the object itself with EJS or a stringify json, again, with EJS?
I can write in manually with a loop to add all the lines but then if I want to make any change I will need to re-write the order.
Is there any way to do it?

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by eliezra236** [comment]
> Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

Hi,
first of all, thanks a lot for this API, it's really helpful.
My question is, if there's an option to give the JSON as a raw stringify JSON string. 
Becuase I am using EJS I have the option to import the JSON as an actual object or string into the HTML. And use it in the script tag. But it seems the JSON support only works with an actual JSON file, or so it seems to me.

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/7325

**Comment by eliezra236** [comment]
> Working example: https://live.bootstrap-table.com/code/wenzhixin/7325

Thanks a lot!
Would be great if you would include it in the docs.

Took me a little while to figure out to exactly execute it with EJS but here is a working example. Keep the JSON as object and not and stringify and it will work properly

```
<%- include('header'); -%>

<div class="container-fluid">
  <table id="table">
    <thead>
      <tr>
        <th data-field="id">ID</th>
        <th data-field="name">Item Name</th>
        <th data-field="price">Added on</th>
      </tr>
    </thead>
  </table>
</div>

<%- include('footer'); -%>

<script type='text/javascript'>
  var $table = $("#table");
  const rows =<%-JSON.stringify(data)%>

  $(function () {
    $table.bootstrapTable({
      data: rows,
    });
  });
</script>
```
