### ISSUE TITLE
Wrong pagination metadata from the server causes an infinite loop

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#5672]
**Description**  
I notice a weird problem in case pagination metadata from the server is wrong. For instance:
```
{
    total:1,
    rows: []
}
```
This is clearly a wrong response, but the way BT acts is even weirder. It starts an infinite loop of remote requests.

**Example**  
https://live.bootstrap-table.com/code/antonioaltamura/7282

**Steps to reproduce**  
Replace `resolve(results)` with `resolve(results1)` in the function `ServerMock`.

**Comment by wenzhixin** [comment]
ref #4762
