### ISSUE TITLE
bootstrap-table.min.js:10 Uncaught TypeError: Cannot read property 'fixedScroll' of null

### ISSUE THREAD

**Issue by juniorgeba** [wenzhixin/bootstrap-table#5675]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
This error appears on the console when the data is null.
In the user's view, always wait for loading.

**Comment by UtechtDustin** [comment]
I'm not sure what do you mean, the data should never be null it should be an empty array instead.
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by juniorgeba** [comment]
If my empty date was set to null
just define if empty []
Thank you very much!!
