### ISSUE TITLE
文档中希望注明哪些函数需要提供返回值。

### ISSUE THREAD

**Issue by YSZeng** [wenzhixin/bootstrap-table#5678]
文档中希望注明哪些函数需要提供返回值。使用更方便。

**Comment by CarsonSlovoka** [comment]
> 文档中希望注明哪些函数需要提供返回值。使用更方便。

Type不是已經說明了這件事情嗎？ 您能舉一個實際的例子嗎？

----

我會這麼說是因為

[![image](https://user-images.githubusercontent.com/17170765/115514441-ad4a3000-a2b6-11eb-90f9-997ebff78650.png)](https://bootstrap-table.com/docs/api/table-options/#buttons)

我會覺得這樣就已經說明了此東西需要的是一個function，應該和您指的返回值是同樣的東西

**Comment by ShreeKrishna1590** [comment]
> The document hopes to indicate which functions need to provide a return value. It is more convenient to use.

Hasn't Type already explained this? Can you give a practical example?
--------------------------------------------------------------------------------------------------
I would say this because
![115514441-ad4a3000-a2b6-11eb-90f9-997ebff78650](https://user-images.githubusercontent.com/86765422/131606939-b2fdaa48-7749-4c2c-b75e-316ced59a1fb.png)

I think this has already explained that this thing needs a function, which should be the same thing as the return value you are referring to. 

**Translation of issue no. 5678 (https://github.com/wenzhixin/bootstrap-table/issues/5678)**

**Comment by YSZeng** [comment]
你好，我在使用文档的过程中，看到了Function类型，但是，这个function需要返回值，并且未在文档中写明，让我在使用的时候不知道需要返回什么类型的值。

**Comment by UtechtDustin** [comment]
I will close this issue, because we got no response from you within 7 days.
If you still need help please provide us the needed information and we will reopen this issue.

**Comment by YSZeng** [comment]
I mean: you should tell me what format this function should return.&nbsp;
You just tell me that you need to provide a function, but you don't specify what format of data to return when you use the function.&nbsp;
Note: This problem is so old that I can't remember which attribute WAS used before.&nbsp;(A few indicate the existence of this problem)&nbsp;
Thanks for your answer!&nbsp;




我的意思是:你应该告诉我这个函数应该返回什么格式。&nbsp;
您只是告诉我您需要提供一个函数，但是您没有指定在使用该函数时返回什么格式的数据。&nbsp;
注意:这个问题太老了，以至于我不记得以前使用了哪个属性。(少部分属性文档有这样的问题)&nbsp;
谢谢你的回答!&nbsp;







曾勇
职员
美康医药软件


 联系我









&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wenzhixin/bootstrap-table"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月12日(星期五) 凌晨3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wenzhixin/bootstrap-table] 文档中希望注明哪些函数需要提供返回值。 (#5678)





 
I will close this issue, because we got no response from you within 7 days.
 If you still need help please provide us the needed information and we will reopen this issue.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
