### ISSUE TITLE
希望在ajax返回值之后，提供动态修改columns的函数。

### ISSUE THREAD

**Issue by YSZeng** [wenzhixin/bootstrap-table#5679]
**Description**  
希望在ajax返回值之后，提供动态修改columns的函数。从而支持动态列增加（做统计报表时会用到）。译文
translate：We hope to provide a function that dynamically modifies columns after the Ajax return value to support dynamic column addition (used in statistical reports).

**Comment by BHdear** [comment]
动态列可以通过refreshTableOptioins来实现

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
可以通过后初始化： https://live.bootstrap-table.com/code/wenzhixin/7810
当然使用 `refreshOptions` 方法也是可以的。
