### ISSUE TITLE
[Question] Get table data from Google Spreadsheet

### ISSUE THREAD

**Issue by IrfanFza** [wenzhixin/bootstrap-table#568]
Hi, is it possible to have my table data from Google Spreadsheet? If it's possible, how can I do that? I've go through all the documentation, even Googling around, but return zero result.

**Comment by wenzhixin** [comment]
How to use Google Spreadsheet?

**Comment by IrfanFza** [comment]
What do you mean? I just want to display my Google Spreadsheet data with your wonderful table plugin. Is there a way to do that? It's like reading the spreadsheet data as a JSon instead of providing json file.

**Comment by wenzhixin** [comment]
I think it is possible, for example like this: http://wenzhixin.net.cn/examples/bootstrap_table/data

**Comment by IrfanFza** [comment]
Hey, that's great. Where can I get the source example? It seems not on the repo.

**Comment by wenzhixin** [comment]
Here is the source: https://github.com/wenzhixin/blog/blob/master/routes/examples.js

**Comment by wenzhixin** [comment]
The url can be a standard JSON interface, not only a JSON file. 

Hope to help, close this issue.

**Comment by M0unir** [comment]
Hi, Same thing here. I'm getting a Json array of data in a javascript variable from a google spreadsheet using a jquery plugin. I was wondering if we could just specify a javascript variable $data as an option in your plugin instead of creating an external data.json file.

**Comment by wenzhixin** [comment]
@M0unir, you can use the `load` method:
```js
$table.bootstrapTable('load', data);
```

**Comment by M0unir** [comment]
Thank you @wenzhixin !!
