### ISSUE TITLE
Focus is shifting to last used input with filter control on android

### ISSUE THREAD

**Issue by Matthew2000** [wenzhixin/bootstrap-table#5684]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
When using the filter control extension on android the focus keeps going back to the last used input making it unusable.
**Example**  
https://examples.bootstrap-table.com/#extensions/filter-control.html

**Additional context**  
I have tested using chrome and firefox on a moto g6 running android 9 and pixel 3 running android 11, so I don't think it is the browser or android version. I also tested it on an Ipad and their weren't any problems.

**Comment by djhvscf** [comment]
@Matthew2000  you said that testing that  on an Ipad, it works as expected?

**Comment by Matthew2000** [comment]
Yes, it worked on the iPad.

**Comment by djhvscf** [comment]
Well, it looks like a browser issue. Let me check it

**Comment by UtechtDustin** [comment]
I tested it on android an can reproduce the issue.

**Comment by UtechtDustin** [comment]
It seems this bug is fixed in the PR #5583, could you test it @Matthew2000 ?

Example: https://live.bootstrap-table.com/code/UtechtDustin/7409

**Comment by Matthew2000** [comment]
@UtechtDustin in your example it works except that the select control isn't populating. I also tested that branch on my website and it worked perfectly.

When do you think that might get into an official release?

**Comment by UtechtDustin** [comment]
That sounds good, the select don't populate because this PR is not done yet (WIP).
@djhvscf is developing that PR, so he can tell you more about that :-)

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9691
