### ISSUE TITLE
filterControl

### ISSUE THREAD

**Issue by Federico-Luna** [wenzhixin/bootstrap-table#5685]
First of nothing, great work !!!

**Bootstraptable version(s) affected**:
Bootstrap-table v1.18.3

**Description**  
Using the filterControl extension and setting height the SearchClearButton button does not clear filter inputs. If not set height all work fine.

**Example**  
https://live.bootstrap-table.com/code/Federico-Luna/7412

**Additional context**  
This occurs in all current browsers (edge, chrome and firefox)

**Comment by djhvscf** [comment]
This PR is going to fix it https://github.com/wenzhixin/bootstrap-table/pull/5583

**Comment by Federico-Luna** [comment]
Thanks.

**Comment by UtechtDustin** [comment]
Fixed in #5583
