### ISSUE TITLE
First time ajax-search with cookie and filter-control didn't start

### ISSUE THREAD

**Issue by yeezy69** [wenzhixin/bootstrap-table#5687]
I have a problem like #4929 that the ajax search-function didn't start searching, when visit the website for the first time and the search-cookie not yet set.

Reproduce:

- start private browser window
- https://live.bootstrap-table.com/code/yeezy69/7426
- put in some text in search input fields
- => nothing happend
- reload page
- => cookie is set
- put in some text in search input fields
- => searching works

Demo:

![ezgif-7-7173d8746432](https://user-images.githubusercontent.com/22444686/115303780-55031900-a164-11eb-93ba-6a232e27e614.gif)

Temporary fix for me: If I create the cookie in php before, I can start a search the first time:
```
if(!isset($_COOKIE['saveId_bs_table_filterControl']))
    setcookie('saveId.bs.table.filterControl', '[{"field":"id","text":""}]');
```

Bootstraptable version 1.18.3

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9863
