### ISSUE TITLE
Editable select items not searchable

### ISSUE THREAD

**Issue by wjglerum** [wenzhixin/bootstrap-table#569]
I build a table with JavaScript using AJAX to fill the table. The items which are editable, using dropdowns, they are not searchable. The other editable items, such as text are searchable using the search toolbar. How should I fix this?

**Comment by wenzhixin** [comment]
Have you use formatter function to format your column?

**Comment by wjglerum** [comment]
No I do not use formatter functions.

**Comment by wenzhixin** [comment]
Can you provide jsFiddle or some code what you use?

**Comment by wjglerum** [comment]
$(function() {
	$('#table').bootstrapTable({
		idField : 'id',
		url : '/data/persons',
		sortName : 'name',
		sortOrder : 'asc',
		search : true,
		columns : [ {
			field : 'id',
			title : '#'
		}, {
			field : 'name',
			title : 'Name',
			sortable : true,
			editable : {
				name : 'name',
				type : 'text',
				pk : '*[@id="table"]/tbody/tr/td[1]'
			}
		}, {
			field : 'surname',
			title : 'Surname',
			sortable : true,
			editable : {
				name : 'surname',
				type : 'text',
				pk : '*[@id="table-persons"]/tbody/tr/td[1]'
			}
		},  {
			field : 'categorie',
			title : 'Categorie',
			sortable : true,
			editable : {
				name : 'categorie',
				type : 'select',
				pk : '*[@id="table-persons"]/tbody/tr/td[1]',
				source : 'data/categories'
			}
		}
       });
});

**Comment by wenzhixin** [comment]
Hi, it seems not support searchable in the select type.

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/editable/README.md

**Comment by wjglerum** [comment]
Too bad it is not supported, any ideas how to add this?

**Comment by tiagoura** [comment]
I created an invisible column with the value for each column that contained "select" and this worked for search.
