### ISSUE TITLE
select-field didn't remember with filterData, ajax-search, cookie and filter-control

### ISSUE THREAD

**Issue by yeezy69** [wenzhixin/bootstrap-table#5690]
Using Bootstraptable 1.18.3 with cookie and filter-control has following problem:

The table with ajax data-source, a column with data-filter-control=select and data-filter-data=var or data-filter-data=url didn't remember the selected fields after reload the page.

I was able to reproduce it in the test environment: https://live.bootstrap-table.com/code/yeezy69/7437

![ezgif-7-4382894d51e1](https://user-images.githubusercontent.com/22444686/115291967-aa83f980-a155-11eb-91b4-3c03493f53bc.gif)

In the video you can see: First, data-filter-data is deactivated. I choose a value from the select field. The filter is retained after a reload (run button). Now I activate data-filter-data with a variable of two values. I choose a select-field value again, reload the table (run button) and the filter is lost. This value is still in the select field, but it is no longer used in the ajax request.

**Comment by djhvscf** [comment]
@yeezy69 Probably this issue will be addressed here https://github.com/wenzhixin/bootstrap-table/pull/5583

**Comment by djhvscf** [comment]
It is fixed now. https://github.com/wenzhixin/bootstrap-table/pull/5583
