### ISSUE TITLE
Uncaught TypeError: Cannot read property 'price' of undefined

### ISSUE THREAD

**Issue by JupiterMx** [wenzhixin/bootstrap-table#5691]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
![image](https://user-images.githubusercontent.com/5134140/115375355-49fdc680-a200-11eb-8e7e-8b328d463706.png)
**Example**  
https://live.bootstrap-table.com/code/JupiterMx/7447

**Possible  (optional)**  

**Additional context**

**Comment by djhvscf** [comment]
Well, the data1.json doesn't have a test.price. What is your expected behavior?

**Comment by JupiterMx** [comment]
> Well, the data1.json doesn't have a test.price. What is your expected behavior?

In some cases, json data such as waterMeter.latestData.meteringTime, in which waterMeter may be null, then enter the search box and search will throw an exception. I think there should be no exceptions here, so that the search can be executed normally

**Comment by UtechtDustin** [comment]
If the data contains null it should work, but in your example the json dont even contains test.price, so its not null its undefined.
But i agree it could make sense to set the data to `null` if the key was not found.

**Comment by JupiterMx** [comment]
> If the data contains null it should work, but in your example the json dont even contains test.price, so its not null its undefined.
> But i agree it could make sense to set the data to `null` if the key was not found.

I modified the example, you can look at it again 
[https://live.bootstrap-table.com/code/JupiterMx/7458](url)
![image](https://user-images.githubusercontent.com/5134140/115511846-e7660280-a2b3-11eb-80cf-65be153d2028.png)

**Comment by UtechtDustin** [comment]
`waterMeter.latestData.meteringTime` ist still undefined because `waterMeter` is null. This means `latestData` and `meteringtime` are undefined.
Example with defined (as `null`): https://live.bootstrap-table.com/code/UtechtDustin/7459

**Comment by wenzhixin** [comment]
I don't think it's a bug, the return of background data should ensure data consistency, that is, no data should also need to return empty Object(`{}`).
If consistency cannot be ensured, you can be handle by `responseHandler`: https://live.bootstrap-table.com/code/wenzhixin/7555
