### ISSUE TITLE
[docs] attributes: missing prefix ``data-``

### ISSUE THREAD

**Issue by CarsonSlovoka** [wenzhixin/bootstrap-table#5693]
I view below page

![image](https://user-images.githubusercontent.com/17170765/115517522-cb655f80-a2b9-11eb-8cc7-9e2a14de9b5c.png)

and click it (green border)

I think both of these prefixes are missing the ``data-``

![image](https://user-images.githubusercontent.com/17170765/115517046-542fcb80-a2b9-11eb-8fe9-3caba9592dd6.png)

https://github.com/wenzhixin/bootstrap-table-examples/blob/f9e6618564a97ba13dd5898d4508afd3d133b2cc/options/show-button-text.html#L13

**Comment by wenzhixin** [comment]
Pull Request is welcome.

**Comment by CarsonSlovoka** [comment]
Okay, I'll send a pull request🙂 . But I am looking for an automatic check mechanism to avoid this type of error. (I think Github Action may help, but I am learning now.)

----

So far, I use the regular expression(``- \*\*Attribute:\*\* `(?!data)``) and found a total of three omissions on the [contents](https://raw.githubusercontent.com/wenzhixin/bootstrap-table/021768e/site/docs/api/table-options.md).

![image](https://user-images.githubusercontent.com/17170765/115646443-ba1d6100-a354-11eb-8376-fd5e81843699.png)

1. show-button-text: https://github.com/wenzhixin/bootstrap-table-examples/blob/f9e6618564a97ba13dd5898d4508afd3d133b2cc/options/show-button-text.html#L13
2. visible-search: https://github.com/wenzhixin/bootstrap-table-examples/blob/d3c8ec2/options/visible-search.html#L10
3. show-button-icons https://github.com/wenzhixin/bootstrap-table-examples/blob/d3c8ec2/options/show-button-icons.html#L13

**Comment by UtechtDustin** [comment]
@CarsonSlovoka we already have a few checks for the documentation.
We can add this check here: https://github.com/wenzhixin/bootstrap-table/blob/develop/tools/check-api.js
