### ISSUE TITLE
[docs] provide a button for IMPROVE THIS PAGE

### ISSUE THREAD

**Issue by CarsonSlovoka** [wenzhixin/bootstrap-table#5694]
## Motivation

#5693 is not a big problem in the [Hugo] docs that provide a button (IMPROVE THIS PAGE) for the user to help them fix.

## Wish
It's wonderful if you can provide a button for IMPROVE THIS PAGE, like below.

[![image](https://user-images.githubusercontent.com/17170765/115515278-8e986900-a2b7-11eb-8855-ad9b05d1acb0.png)](https://gohugo.io/templates/introduction/)
(👆 click above picture, and scroll down, in the end, you will see it.)

## Other
In fact, I have thought about fixing [#5963](https://github.com/wenzhixin/bootstrap-table/issues/5693) by myself, but I don't know what the Github page creation relies on. 

Can you tell me which [static site generator](https://jamstack.org/generators/) are you use❓

[Hugo]: https://gohugo.io/

**Comment by UtechtDustin** [comment]
I like that idea, let us check that !
The docs are within the folder `site/docs`, for #5693 you have to edit https://github.com/wenzhixin/bootstrap-table/blob/develop/site/docs/api/table-options.md#showbuttonicons

**Comment by wenzhixin** [comment]
Added "View on GitHub"(View and edit this file on GitHub) button: https://bootstrap-table.com/docs/api/table-options/
