### ISSUE TITLE
Race condition render

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#5695]
**Description**  
When you perform 2 remote requests for data via `ajax` fn rapidly one after another, if the first one is slower you will reach an inconsistent state between data shown in the table (wrong) and pagination info (right) 

**Steps to reproduce**  
https://live.bootstrap-table.com/code/antonioaltamura/7470
- Click on "1st req" button and then quickly "2st req".
- You see first the data from the 2nd request, which is faster
- then you will see the data from the 1st request, but the pagination info will stay the same. 

**Expected behavior**  
"1st request" response should be discarded.

My first attempt was trying to "sign" my last request in the `ajax` function and use `responseHandler` to decide whether to discard or not, but the latter is not the right place as I cannot discard responses in there. 

https://user-images.githubusercontent.com/6325475/115590570-06bb5a80-a2c9-11eb-9c40-dd1446322de3.mp4

**Comment by wenzhixin** [comment]
You need to abort the first request by yourself if you use the custom `ajax` option.
For example: https://live.bootstrap-table.com/code/wenzhixin/7554
Code: 
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1970

**Comment by antonioaltamura** [comment]
How using `queryParams` would help in this case?

**Comment by wenzhixin** [comment]
![image](https://user-images.githubusercontent.com/2117018/120919601-077b4500-c6ed-11eb-934c-8564e66b1088.png)
No, the `queryParams` is just to demonstrate that the first request is canceled when the request waits too long.

**Comment by antonioaltamura** [comment]
Got it. Checking the `readyState` in my case is impossible as I use a "service" design pattern for my remote calls, I don't expose the raw xhr/jqXHR object.
My ajax functions look like this:
```
ajax: async params => {
      try {
          const response = await myClient.query({q: "seach"})
          params.success(response);
      } catch (e) {
          params.error(e);
      }
},
```

As I said in the first post, `responseHandler` must return data, so it is not the right place to discard a response. Is there a callback function executed between the `params.success` and `responseHandler` in which I can choose whether discard or not a response based on my criteria?
