### ISSUE TITLE
How do I change the style of the jump button

### ISSUE THREAD

**Issue by xiongtete0519** [wenzhixin/bootstrap-table#5700]
I use bootstrapv3 version, do not know how to modify the style of the page jump button
![image](https://user-images.githubusercontent.com/66518135/115844222-347fdb00-a452-11eb-9399-21bbd477b46d.png)

**Comment by xiongtete0519** [comment]
I noticed that in the bootstrapv3 version, the styles in your documentation are not quite the same as in the online examples.
- Bootstrap Table Examples:
![image](https://user-images.githubusercontent.com/66518135/115845721-b9b7bf80-a453-11eb-9bf8-34ab9e04292f.png)
- Online Editor:
![image](https://user-images.githubusercontent.com/66518135/115845827-d94ee800-a453-11eb-8b28-84d84db8496d.png)

**Comment by xiongtete0519** [comment]
I have solved this problem

**Comment by wenzhixin** [comment]
Fixed in #5674
