### ISSUE TITLE
post-body.bs.table event not fired on custom-view table ?

### ISSUE THREAD

**Issue by admin-genX** [wenzhixin/bootstrap-table#5701]
Hello. I am new to BT table and I try to use it with data-custom-view. I followed the example and the rendering works fine.
However I need to integrate some popovers in the template used for the custom view, which require some javascript initialization.

So I tried to listen to the 'post-body.bs.table' event and add the ad-hoc callback to init the popovers. But this doesn't work.
I noticed that in case of data-custom-view the table is fully replaced by  generated code, and then I have no clue which DOM object (if any) can listen to this  'post-body.bs.table' event, and I could't find any doc nor example related to this topic.

Thx for your help!

Here is my code:

<-table id="myTableId" data-toggle="table" data-locale="fr-FR" data-sortable="true" data-pagination="true" data-page-size="10" 
    data-url="/workspace/tasks?status=open"
    data-custom-view="customTaskFormatter"
    class="table table-sm table-hover table-borderless mt-1">
<thead>...</thead>
</table>
<script>
    $(function() {
      $('#myTableId').on('post-body.bs.table', function (e) {
          console.log('updating popovers');
        $('[data-toggle="popover"]').popover()
      })
  })
</script>

**Comment by admin-genX** [comment]
After some investigation, it seems that the post-body.bs.table is fired BUT before the custom view rendering function has been called.

**Comment by admin-genX** [comment]
So if the 'post-body.bs.table' event is only available for the table body, what is the event that informs that the custom view is renderded and available in the DOM, unless I implement it myself ?

**Comment by UtechtDustin** [comment]
You're right, thanks for the report. We will check and fix it!

**Comment by UtechtDustin** [comment]
I checked it and its right how it works right now.
The `post-body.bs.table` event is for the table, for the custom view you have to use the [onCustomViewPostBody](https://bootstrap-table.com/docs/extensions/custom-view/#oncustomviewpostbodycustom-view-post-bodybstable) event.
Example: https://live.bootstrap-table.com/code/UtechtDustin/7520

**Comment by admin-genX** [comment]
Thx, this is exactly the info I was looking for ('custom-view-post-body.bs.table'). I have just updated my code and it works perfectly now!
