### ISSUE TITLE
PULL_REQUEST_TEMPLATE.md use task list instead of yes/no

### ISSUE THREAD

**Issue by CarsonSlovoka** [wenzhixin/bootstrap-table#5704]
I want to improve [PULL_REQUEST_TEMPLATE.md](https://github.com/wenzhixin/bootstrap-table/blob/develop/.github/PULL_REQUEST_TEMPLATE.md)

Does this way is better than the original one?

## original
**Bug fix?**

**New Feature?**

## Suggestion
- [x] **Bug fix**

- [ ] **New Feature**

### code
```
- [X] **Bug fix**
<!-- [X]/[ ] -->

- [ ] **New Feature**
<!-- [X]/[ ] -->
```

**Comment by djhvscf** [comment]
I like the idea.. The PR is welcome

**Comment by UtechtDustin** [comment]
I also had that idea, as @djhvscf already said the PR is welcome.
We also should add `docs` and `others` as option.
