### ISSUE TITLE
Remove Row by field string

### ISSUE THREAD

**Issue by PhHitachi** [wenzhixin/bootstrap-table#5705]
Hi guys, 

i want to know how can remove the custom field like remove by 'name'  in my case i want to remove by ID but the ID is not String (e-code) i used already removeByUniqueId but now working.

just for example:
https://live.bootstrap-table.com/code/PhHitachi/7546

**Comment by PhHitachi** [comment]
I forgot this my actual code on my website, i use the code on `line 245 `

![image](https://user-images.githubusercontent.com/44565442/116215404-3a3f2e80-a77a-11eb-9016-2b4b74965d1f.png)

**Comment by SiddharthShyniben** [comment]
You know @PhHitachi, you should really paste the code, not take a photo. It makes it easier to try out the code

**Comment by wenzhixin** [comment]
> values: the array of values for rows which should be removed.

@PhHitachi The type of values is `Array`: https://bootstrap-table.com/docs/api/methods/#remove
Working example: https://live.bootstrap-table.com/code/wenzhixin/7552

**Comment by PhHitachi** [comment]
@SiddharthShyniben noted,

Thanks @wenzhixin
