### ISSUE TITLE
Filter Control, Filter Type For Column

### ISSUE THREAD

**Issue by mehmetalidumlu** [wenzhixin/bootstrap-table#5708]
Hi,
When filtering, can we have a chance to determine the filter type? This is a rough example, but it will tell what I want to say.
Thanks.

**Example:** https://live.bootstrap-table.com/code/mehmetalidumlu/7560

**Comment by djhvscf** [comment]
You mean something like this https://bootstrap-table.com/docs/api/methods/#filterby?

**Comment by mehmetalidumlu** [comment]
Hi @djhvscf ,
Actually, it's not exactly like this example. I took the screenshot below from a project prepared by my friend. Pressing the search icon next to the column opens a menu where we can set the search criteria. The content of this Menu varies according to the type of column. My friend uses a library called "DevExtreme" in this application he has prepared.

![Screenshot_1](https://user-images.githubusercontent.com/15678340/116518994-a1bfc000-a8d9-11eb-8dd8-bbe95e17251c.png)
![Screenshot_2](https://user-images.githubusercontent.com/15678340/116519352-10048280-a8da-11eb-9bc2-ce22fd3378e8.png)

**Comment by UtechtDustin** [comment]
No the filter-control extension don't support that kind of filter select.
But it could be possible to implement yourself with [filterControlContainer](https://bootstrap-table.com/docs/extensions/filter-control/#filtercontrolcontainer) and [filterCustomSearch](https://bootstrap-table.com/docs/extensions/filter-control/#filtercustomsearch).

But a few features of the screenshot above are already build in, e.g. you can search for `>= 10`.
Example for testing: https://live.bootstrap-table.com/code/UtechtDustin/7614
