### ISSUE TITLE
Diversified checking system: Github/action for check

### ISSUE THREAD

**Issue by CarsonSlovoka** [wenzhixin/bootstrap-table#5710]
## What do I want? 

I want to add a new go<sup>[golang](https://golang.org/)</sup> folder to [tools](https://github.com/wenzhixin/bootstrap-table/tree/ebb4aa5/tools).

This is where the tools implemented in the go language are stored

I got this idea because of #5693 

And in it, I learned that the project has already written a check tool through [Travis](https://travis-ci.com/)<sup>#5165, [.travis](https://github.com/wenzhixin/bootstrap-table/blob/67c5c5b39779f4307e025e5ef4b8bef01024999a/.travis.yml#L13-L14)</sup>, which is great.

It's just that not everyone is familiar with the CI tool (I'm not mean that maliciously)

In fact, no one can be proficient in all CI tools.

So my suggestion is to let the person who is interested in improving it implement it in a language he is familiar with (Github action provide a lot template for kind of language, and most importantly everyone who visits Github can see the workflow)

I understand that the core of the project is JavaScript.

So the use of other tools is not related to the core, it's just for checking things out and so on.

I have completed something here, mainly for #5693 and [example-link](https://github.com/wenzhixin/bootstrap-table/blob/01dffd47dce0444751/tools/check-api.js#L48)

I found some parts that look like they could be improved as follows

all from [column-options.md](https://github.com/wenzhixin/bootstrap-table/blob/develop/site/docs/api/column-options.md)
1. [**Attribute:** `class | data-class`](https://github.com/wenzhixin/bootstrap-table/blame/121c201ae01104b32c997768a4ecfad6be0a34ca/site/docs/api/column-options.md#L93)  | [Online Doc](https://bootstrap-table.com/docs/api/column-options/#class#:~:text=class%20|%20data-class)
2. [**Attribute:** `colspan | data-colspan`](https://github.com/wenzhixin/bootstrap-table/blame/121c201ae01104b32c997768a4ecfad6be0a34ca/site/docs/api/column-options.md#L121) | [Online Doc](https://bootstrap-table.com/docs/api/column-options/#colspan#:~:text=colspan%20|%20data-colspan)
3. [**Attribute:** `rowspan | data-rowspan`](https://github.com/wenzhixin/bootstrap-table/blame/121c201ae01104b32c997768a4ecfad6be0a34ca/site/docs/api/column-options.md#L309) | [Online Doc](https://bootstrap-table.com/docs/api/column-options/#rowspan#:~:text=rowspan%20|%20data-rowspan)

``class |`` is redundant?

> ~~class|~~ data-class
> ~~class|~~ data-colspan
> ~~rowspan|~~ data-rowspan

![image](https://user-images.githubusercontent.com/17170765/116512720-093a3780-a8fb-11eb-8afc-acfb9097fecf.png)
(👆see it on [workflows](https://github.com/CarsonSlovoka/bootstrap-table/runs/2463433045?check_suite_focus=true#step:5:43))

Although this [script](https://github.com/CarsonSlovoka/bootstrap-table/blob/github-action/tools/go/check/api.go#L50-L74) seems to be very easy now. But if necessary I think it can become more powerful, such as checking invalid links (including issues)

anyway, I hope you can adopt it.

If my [commit](https://github.com/CarsonSlovoka/bootstrap-table/commits/github-action) doesn't meet your format, or if you need me to subdivide the issue, please let me know and I will create a new issue.

If it works then I will make a pull request

## explain the [5991107a1d](https://github.com/CarsonSlovoka/bootstrap-table/commit/5991107a1d3929203b4475c16b4259e3e5bd4884) and [952b6afea7054](https://github.com/CarsonSlovoka/bootstrap-table/commit/952b6afea7054b55bb371e5aaf56a96b30deeff1)

I notice that 

> [Usage limits for GitHub Actions](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration)

and you mention it [before](https://github.com/wenzhixin/bootstrap-table/pull/5165#:~:text=but%20the%20api%20has%20a%20limit%20of%2060%20requests)

so I add some [constraint](https://github.com/CarsonSlovoka/bootstrap-table/commit/5991107a1d3929203b4475c16b4259e3e5bd4884#diff-d18fd47418b3c4f65ea97cde36981dfc09db85a520a9b5f178eb02371f0f229dR3-R10)

```yml
on:
  push:
    paths:
      - "site/docs/api/*.md" 
```
It doesn't bother you the most time. Only if these files change, the workflow is run.

### go script

1. I glob all the file on the [site/docs/api](https://github.com/wenzhixin/bootstrap-table/tree/57c9dce/site/docs/api) with
    > [collectFiles](https://github.com/CarsonSlovoka/bootstrap-table/commit/5991107a1d3929203b4475c16b4259e3e5bd4884#diff-704534964c1c0fa7f176d3fe91c8b78fe91bfa052996ffa301f3e1b435d05fe7R53)

2. and then [start check](https://github.com/CarsonSlovoka/bootstrap-table/commit/5991107a1d3929203b4475c16b4259e3e5bd4884#diff-704534964c1c0fa7f176d3fe91c8b78fe91bfa052996ffa301f3e1b435d05fe7R54)

3. [main code](https://github.com/CarsonSlovoka/bootstrap-table/blob/952b6afea7054b55bb371e5aaf56a96b30deeff1/tools/go/check/api.go#L50-L78) <sup>with [regex](https://github.com/CarsonSlovoka/bootstrap-table/blob/952b6afea7054b55bb371e5aaf56a96b30deeff1/tools/go/check/api.go#L30)</sup> of check function
    > [explain regex](https://regex101.com/r/62LqIi/2)

    - [test main code](https://github.com/CarsonSlovoka/bootstrap-table/blob/952b6afea7054b55bb371e5aaf56a96b30deeff1/tools/go/check/api_test.go#L52-L59)

### growing up together

If you want, we can video conference, share some Golang stuff<sup>but need Chinese, or communicate in text on the StackOverflow-chat: [231724/bootstrap-table](https://chat.stackoverflow.com/rooms/231724/bootstrap-table)</sup>, and take you about 30 minutes to start from the beginning.

Thanks for you share the time to watch🙂

**Comment by UtechtDustin** [comment]
@CarsonSlovoka Thanks for the idea, but i guess you misunderstand something.
TravisCI just execute our test, which means everybody can easy execute that test without any knowledge about Travis.
So as example you can navigate to the `tools` folder and run `node check-api.js`, this script as example would check the documentation (existing example, prefixed `data-` attribute etc.).
So we already have that implement, just with javascript instead of golang (which makes sense because its a javascript lib => we don't have another dependency).

**Comment by CarsonSlovoka** [comment]
Yes, I found that I did misunderstand😆. I found that the pull request check will be able to [view](https://github.com/wenzhixin/bootstrap-table/pull/5583/checks?check_run_id=2428917620).

Code is only used on GitHub action and does check only, will not affect the user (do not need to install Golang). The only affect is a size increase of about 7.25KB.

well, I respect your decision.

----

one more question

attributes is redundant?

> ~~class|~~ data-class
> ~~class|~~ data-colspan
> ~~rowspan|~~ data-rowspan

**Comment by UtechtDustin** [comment]
@CarsonSlovoka thats right, the develop who use the table is not affected. But the develops who maintain the bootstra-table has to use golang also, which means we have a new dependency. Also i don't think anybody who can write javascript can write go.

If you have ideas for improvements you cann implement it in javascript. PR's are always welcome.

Yes a few attributes are redundant because that are attributes which also exists in html(5).
