### ISSUE TITLE
drag twice cause error order

### ISSUE THREAD

**Issue by cahhbwy** [wenzhixin/bootstrap-table#5712]
when I use plugin table-reorder-rows, I drag twice on the table, and use bootstrapTable("getData"), find the order is not what I expect. I fixed it by add options onReorderRow a function
function () {
    $("#table").bootstrapTable('load', $("#table").bootstrapTable('getData'));
}
please fix it....

**Comment by wenzhixin** [comment]
Fixed in #5682
