### ISSUE TITLE
FilterControl input bug with cursor, if table has height + FIX

### ISSUE THREAD

**Issue by gumacuk15** [wenzhixin/bootstrap-table#5713]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
If table has no height, so it works fine. But if you set height to table > 0, it will work with incorrect header.

**Example**  
https://live.bootstrap-table.com/code/Federico-Luna/7412

**Possible  (optional)**  
You can fix this bug by adding code to bootstrap-table-filter-control.js in function setValues():
```
if (that.options.height) {
    var elementClass = getElementClass($this);
    $this = $__default['default'](".fixed-table-header .".concat(elementClass));
}
```

Full example:

```
function setValues(that) {
    var field = null;
    var result = [];
    var searchControls = getSearchControls(that);
    if (that.options.valuesFilterControl.length > 0) {
      //  Callback to apply after settings fields values
      var fieldToFocusCallback = null;
      searchControls.each(function (i, el) {
        var $this = $__default['default'](el);

        if (that.options.height) {
           var elementClass = getElementClass($this);
           $this = $__default['default'](".fixed-table-header .".concat(elementClass));
        }

        field = $this.closest('[data-field]').data('field');
        result = that.options.valuesFilterControl.filter(function (valueObj) {
          return valueObj.field === field;
        });

        if (result.length > 0) {
          if ($this.is('[type=radio]')) {
            return;
          }

          $this.val(result[0].value);

          if (result[0].hasFocus && result[0].value !== '') {
            // set callback if the field had the focus.
            fieldToFocusCallback = function (fieldToFocus, carretPosition) {
              // Closure here to capture the field and cursor position
              var closedCallback = function closedCallback() {
                fieldToFocus.focus();
                setCursorPosition(fieldToFocus);
              };

              return closedCallback;
            }($this.get(0), result[0].position);
          }
        }
      }); // Callback call.

      if (fieldToFocusCallback !== null) {
        fieldToFocusCallback();
      }
    }
 } 
```
  
Also I have changed function setCursorPosition() (because my table sets cursor at start of string, not end):

```
function setCursorPosition(el) {
     var v = el.value;
     $__default['default'](el).val("");
     $__default['default'](el).val(v);
}
```

**Comment by UtechtDustin** [comment]
Could you please explain the bug further, i tested the example and the filter worked fine for me.
You suggestion for the fix is in the dist code instead of the src code, which means we cant use it in that form.
But if you wan't to help us, you can fix the bug in the source code (src folder) and submit a PR.

**Comment by gumacuk15** [comment]
> Could you please explain the bug further, i tested the example and the filter worked fine for me.
> You suggestion for the fix is in the dist code instead of the src code, which means we cant use it in that form.
> But if you wan't to help us, you can fix the bug in the source code (src folder) and submit a PR.

Remove data-height=600 and compare filter input with and without height. Problem is with cursor, not filtering! With height cursor disappears and input is not active.

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9695

**Comment by rsperumal** [comment]
Looks like the issue has appeared again? the last example still produces the error. If I type something on the column search field, the cursor returns back to start position. this does not happen if I remove data-height=600

**Comment by vuvtdhh** [comment]
Temporary fix for bootstrap-table version 1.22.1
`if ($this[0] === document.activeElement) {
setCaretPosition($this[0], $this[0].value.length);
}`

**Comment by SimoBotin89** [comment]
Where has the code for the temporary fix to be inserted?

**Comment by vuvtdhh** [comment]
> Where has the code for the temporary fix to be inserted?
Put it at line 4401, inside setValues function. I have create a repo, you can visit to get the full code.

`function setValues(that) {
    var field = null;
    var result = [];
    var searchControls = getSearchControls(that);
    if (that._valuesFilterControl.length > 0) {
      //  Callback to apply after settings fields values
      var callbacks = [];
      searchControls.each(function (i, el) {
        var $this = $$l(el);

        field = $this.closest('[data-field]').data('field');
        result = that._valuesFilterControl.filter(function (valueObj) {
          return valueObj.field === field;
        });

        if (result.length > 0) {
          if (result[0].hasFocus || result[0].value) {
            var fieldToFocusCallback = function (element, cacheElementInfo) {
              // Closure here to capture the field information
              var closedCallback = function closedCallback() {
                if (cacheElementInfo.hasFocus) {
                  element.focus();
                }
                if (Array.isArray(cacheElementInfo.value)) {
                  var $element = $$l(element);
                  $$l.each(cacheElementInfo.value, function (i, e) {
                    $element.find(Utils$1.sprintf('option[value=\'%s\']', e)).prop('selected', true);
                  });
                } else {
                  element.value = cacheElementInfo.value;
                }
                setCaretPosition(element, cacheElementInfo.position);
              };
              return closedCallback;
            }($this.get(0), result[0]);
            callbacks.push(fieldToFocusCallback);
          }
        }
        // vuvtdhh
        if ($this[0] === document.activeElement) {
          setCaretPosition($this[0], $this[0].value.length);
        }
      });

      // Callback call.
      if (callbacks.length > 0) {
        callbacks.forEach(function (callback) {
          return callback();
        });
      }
    }
  }`
