### ISSUE TITLE
Event uncheck.bs.table not working

### ISSUE THREAD

**Issue by urtvs** [wenzhixin/bootstrap-table#5716]
Hi

$('.t').on('check.bs.table', function (e, row)  - works when checked certail row or uncheck.
$('.t').on('check-all.bs.table', function (rowsBefore, rowsAfter)  - works when check ALL rows.

$('.t').on('uncheck.bs.table', function (e, row)  - did not work:(

How can i can debug what events fired when i click on checkbox button to uncheck all rows?
Can understand why event did not fired(

**Comment by UtechtDustin** [comment]
Both events are working fine, please check [this example](https://live.bootstrap-table.com/code/UtechtDustin/7613).
If you need more help with your usecase please provide us an example using the [editor](https://live.bootstrap-table.com/).
