### ISSUE TITLE
sticky header doesn't copy a dropdown filter as header

### ISSUE THREAD

**Issue by eliezra236** [wenzhixin/bootstrap-table#5717]
**Description**  

I tried adding an option to quick filter, doing "excel like" filter where you can click on the collum name and then view the data inside the table, and option to select the checkbox to "only show X".
And it works fine, until I am trying to use the sticky header addon. 
If I try to use it before scrolling to activate the sticky header, it works fine, but if I try to scroll and the sticky header kicks in then I can't use it, not with sticky header and not when I scroll back up to show the regular header.

**Example**  

https://live.bootstrap-table.com/code/eliezra236/7586

**Possible  (optional)**  

If you could explain to me what's happened in the background with the sticky header then maybe I'll be able to identify what happened.
Or if there is other way to use sticky header, like here:
https://css-tricks.com/position-sticky-and-table-headers/

where he doesn't create a new header, only sticking it to the top by making the table relative. But I couldn't find a way to apply it here

**Comment by UtechtDustin** [comment]
There are two problems:
- If you scroll down and the sticky header is shown your dropdown list is behind the table (position/z-index issue).
- The sticky header is a copy of the original header, that also means your dropdown was cloned and there multiple elements with the same id which breaks your filter because the wrong list was selected.

Solution:
- You have to modify your onclick function so you also use the correct dropdown list
- Sync the filter state for the second dropdown list
- Find a solution for the css issue (position/z-index).

So as conclusion this is not a bug of the bootstrap-table, i hope i could help you.

**Comment by eliezra236** [comment]
> There are two problems:
> 
> * If you scroll down and the sticky header is shown your dropdown list is behind the table (position/z-index issue).
> * The sticky header is a copy of the original header, that also means your dropdown was cloned and there multiple elements with the same id which breaks your filter because the wrong list was selected.
> 
> Solution:
> 
> * You have to modify your onclick function so you also use the correct dropdown list
> * Sync the filter state for the second dropdown list
> * Find a solution for the css issue (position/z-index).
> 
> So as conclusion this is not a bug of the bootstrap-table, i hope i could help you.

Hi,
thanks for the reply.
I did manage to solve the Z-index problem and to make the filter apply.
But now it "resets" every time I open it.
Here's an example
https://live.bootstrap-table.com/code/eliezra236/7589

The filter is applied and working, but then after I close the dropdown when I open it again it reset to the state it was before the sticky header was applied.
So how exactly the sticky header works is the question, does it sync it every time I scroll or it copy it once and then reset to that position? I didn't find a way to overcome this.

**Comment by UtechtDustin** [comment]
Do you still need help ?

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we got no response from you.
If you still nee dhelp please let us know.
