### ISSUE TITLE
Support for Bootstrap v5?

### ISSUE THREAD

**Issue by n01337** [wenzhixin/bootstrap-table#5718]
Are there plans to support the latest bootstrap iteration (v5)? If so: Is there a roadmap?

**Comment by LinkedForest** [comment]
I Need To Know to ..

**Comment by angelfind** [comment]
The biggest problem is how to support bootstrap V5 without jQuery?

**Comment by n01337** [comment]
I suppose most BT users would not object to using jQuery with a refurbished release, but even _with_ jQuery, BT is incompatible with the upcoming iteration of Bootstrap. Therefore let me repeat my inquiry: Are there plans to support the latest bootstrap iteration (v5)? If so: Is there a roadmap?

**Comment by UtechtDustin** [comment]
We already support Bootstrap 5 (beta): https://examples.bootstrap-table.com/index.html?bootstrap5
I don't tested the newest Bootstrap 5 version yet, if i have later some time i will check that.

@angelfind 
Bootstrap 5 is also working with jQuery.

@n01337 
Could you explain why the BT would be incompatible with the upcoming Bootstrap 5 Versions ?
We have to use jQuery right now. We will rewrite the bootstrap table and drop the jQuery dependency, but its a LOT of work and as we maintaince the BT in your spare time its hard to do that that quickly.

**Comment by n01337** [comment]
@UtechtDustin: No offense meant! Of course I understand that fully supporting Bootstrap 5 (without jQuery) is not something to do in an evening. I did not want to press things, just was interested, if there is a general roadmap for full support.
Regarding the supposed incompatibility: What I meant was more along the lines of "not officially supported", i.e., at the moment, BT still mentions Bootstrap 4 as target "platform" exclusively.

**Comment by UtechtDustin** [comment]
I didn't think you were offending me, it was just a explanation :-)
I guess @wenzhixin set bootstrap 4 as target, because bootstrap 5 was still in alpha/beta.

I will check if bootstrap 5 works fine with the BT, if that is done we can change the "target" Bootstrap version :-)

**Comment by n01337** [comment]
@UtechtDustin: Thank you!

> because bootstrap 5 was still in alpha/beta.

Not anymore: 5.0.0 is officially out now.

**Comment by UtechtDustin** [comment]
Thats the reason why i wrote `was` insteaf of `is` :-)
I tested it and for me its working fine with the newest bootstrap 5 version.
I created a PR #5722 for using bootstrap icons instead of font-awesome.

**Comment by ZhangGaoxing** [comment]
If it is used in bootstrap 5, do I need to add jQuery reference?
![image](https://user-images.githubusercontent.com/15957347/120575813-50649c80-c454-11eb-94d8-2ae705a3d715.png)

**Comment by UtechtDustin** [comment]
@ZhangGaoxing yes, the bootstrap-table needs jQuery.
