### ISSUE TITLE
export -> ignore column formatter

### ISSUE THREAD

**Issue by s72817** [wenzhixin/bootstrap-table#5719]
Hi,
how can I ignore a column formatter if I would like to export?

There is a trimFormatter:
`trimFormatter(value) {
        return value ? value.substring(150, length) + '...' : 'No Description';
    }`
but in export I would like to have the entire string.

Thanks in advanced

**Comment by s72817** [comment]
Is there any way now?

**Comment by wenzhixin** [comment]
According to the docs of [tableExport](https://github.com/hhurz/tableExport.jquery.plugin#data-tableexport-value).

A workaround for you: https://live.bootstrap-table.com/code/wenzhixin/10530
```js
formatter: function (value, row) {
  row._description_data = {
    'tableexport-value': value
  }
  return value.substring(0, 80) + '...'
}
```

**Comment by s72817** [comment]
Muchas gracias @wenzhixin !
