### ISSUE TITLE
Bootstrap tooltip not working inside table

### ISSUE THREAD

**Issue by iamthestreets** [wenzhixin/bootstrap-table#572]
Hi I am using a function that I saw from one of your example which is to display action buttons. I am having a problem with the bootstrap tooltip working on these buttons.

Here is the JS:
```javascript
function actionsFormatter(value, row, index) {
        if (row.id == 1 || row.id == 2) {
			 return [
	            '<a class="btn btn-primary btn-xs mr10" data-tooltip="true" data-placement="bottom" href="admin_permission.php?id='+row.id+'" title="Edit">',
	                '<i class="glyphicon glyphicon-pencil"></i>',
	            '</a>',
	            '<a class="btn btn-danger btn-xs disabled" data-tooltip="true" data-placement="bottom" href="#" title="Remove">',
	                '<i class="glyphicon glyphicon-trash"></i>',
	            '</a>',
	        ].join('');	
		} else {
			    return [
		            '<a class="btn btn-primary btn-xs mr10" data-tooltip="true" data-placement="bottom" href="admin_permission.php?id='+row.id+'" title="Edit">',
		                '<i class="glyphicon glyphicon-pencil"></i>',
		            '</a>',
		            '<a class="btn btn-danger btn-xs remove" data-tooltip="true" data-placement="bottom" href="#" title="Remove">',
		                '<i class="glyphicon glyphicon-trash"></i>',
		            '</a>',
	        	].join('');
		}
	}
window.actionsEvents = {
        'click .remove': function (e, value, row, index) {
        	// Open modal on click
        	$('#deleteModal').modal();
        	// Add permission names to modal
        	$('#permission-name').text('Are you sure you want to delete: ' + row.name + '?');
        	// Create a hidden input to use when submitting form
	        var input = document.createElement("input");
            input.setAttribute('type', 'hidden');           
            input.setAttribute('name', 'delete['+row.id+']');
            input.setAttribute("id", 'delete['+row.id+']');            
            input.setAttribute('value', row.id);         
            //append to form element that you want .
            document.getElementById("deleteModalForm").appendChild(input);  
        	        	          
            console.log(value, row, index);
        }
    };
```
And the I have this to activate the tooltips:
```javascript
$('[data-tooltip="true"]').tooltip({
    	container: 'body'
	});
```

The tooltip works fine on the toolbar, but does not work for these buttons. Can you see why this doesn't work?
Here is a [JSFiddle](http://jsfiddle.net/e3nk137y/790/). Notice that the top let button has the bootstrap tooltip, but the action buttons in the table does not work.

**Comment by wenzhixin** [comment]
You need to active the `tooltip` after table body is rendered: http://jsfiddle.net/e3nk137y/791/.

**Comment by PlippiePlop** [comment]
bootstrap table is messing around with items inside table TH/TD tags. It removes 'title' or changes the 'data-original-title' to  data-originaltitle'. 

See example here with bootstrap tables: (inspect the TH and TD elements all items removed)
https://jsfiddle.net/zac8z18m/1/

And without bootstrap tables here:
https://jsfiddle.net/8dou6d7u/1/

**Comment by rwitchell** [comment]
this is still an issue. @wenzhixin, could you please offer advice?
data-toggle does not render as a property on the <th> in the DOM.

```
<th data-field="incomplete"
            data-sortable="true"
            data-halign="center"
            data-align="center"
            data-toggle="tooltip"
            data-title-tooltip="Incomplete">I
        </th>
```

```
$(function () {
        // Initiate table once page has rendered
        $('#activeReportDataTable').bootstrapTable({
            
        }).on('post-body.bs.table', function () {
            // need to re-render tooltip when table is modified/sorted
            activateTooltips();
        });

        activateTooltips();
    });
```


```
function activateTooltips() {
        var opt = {
            container: 'body'
        };
        $('[name="refresh"]').tooltip(opt);
        $('div.btn-group > [title="Columns"]').tooltip(opt);
        $('div.btn-group > [title="Export data"]').tooltip(opt);
        $('th[data-toggle="tooltip"]').tooltip(opt);
        return true;
    }
```

**Comment by JTCE** [comment]
@rwitchell @wenzhixin I run into this the other day and it is indeed an issue but appears directly related with data-toggle="table" and the post.body... events. After diving into the source code, it looks like the data-* attribute logic, similar to that in the rows, is missing from the header.

Unfortunately I had to work around this by using a "class" as that was being maintained in the headers. Here's a working fiddle: [Bootstrap Table Tooltip Example](https://jsfiddle.net/JoshEllis/scqd9v7e/2/)
Note: the logic for updating textarea tooltip (live changes) within each table row is not functioning but I left the code there anyway. I can assure you it's the exact version I'm using right now in live projects but for whatever reason, jsFiddle is not working with :hover inside a table. Mind-boggling!

Always open for feedback and hope this helps!

**Comment by rwitchell** [comment]
Until this is fixed in the source, the easiest work around for the time being is placing a div inside your header:
````
<th>
<div data-tooltip="this will show as a tooltip"></div>
</th>
````

**Comment by sylvain-farnault** [comment]
I went through this problem today
If you want tooltips to be back, you need to fire them again, (or regenerate them) via a `$('[data-tooltip="true"]').tooltip();`

When they're gone, or you think they should be there, if you execute `$('[data-tooltip="true"]').tooltip();` from your browser console, they should be back

I tried using `click` or `mouseup` events. Event `post-body.bs.table` or `all.bs.table` weren't enougth

My situation: In a sortable table, when clicking on a column header, tooltips presents on table cells were then off. Weel, something was broken!  
Here is my solution, or mostly a hack
`
$(function () {
    $('[data-tooltip="true"]').tooltip();
    $('#table-id th').click(function(e) {
        setTimeout(function() {
            $('[data-tooltip="true"]').tooltip();
        }, 200);
    });
});
`
For the @iamthestreets original problem, i think you could fire again tooltips at the end of your `actionsFormatter` function with setTimeout as I showed
`
     setTimeout(function() {
          $('[data-tooltip="true"]').tooltip();
     }, 200);
`

I hope it helps

**Comment by vletoux** [comment]
I had also the same problem but I don't think is the best answer.
I started as suggested to add code for the event post-body.bs.table but not all events were covered.
Then I added the code suggested above with the click handler.
But my tooltip is on a column (a question mark item) and when clicking on it, the tooltip does not disappear.

After some time, I think the best is to use the "selector" feature.
See https://getbootstrap.com/docs/5.0/components/tooltips/#options

instead of adding data-bs-tooltip to tooltips, the best is to add a new class (like `has-tooltip`) and to use the following js:
```
new bootstrap.Tooltip(document.body, {
        selector: '.has-tooltip'
    });
```
Automatically created and destroyed tooltip are handled automatically. No additional code is needed.

**Comment by CosmoFox** [comment]
> I had also the same problem but I don't think is the best answer. I started as suggested to add code for the event post-body.bs.table but not all events were covered. Then I added the code suggested above with the click handler. But my tooltip is on a column (a question mark item) and when clicking on it, the tooltip does not disappear.
> 
> After some time, I think the best is to use the "selector" feature. See https://getbootstrap.com/docs/5.0/components/tooltips/#options
> 
> instead of adding data-bs-tooltip to tooltips, the best is to add a new class (like `has-tooltip`) and to use the following js:
> 
> ```
> new bootstrap.Tooltip(document.body, {
>         selector: '.has-tooltip'
>     });
> ```
> 
> Automatically created and destroyed tooltip are handled automatically. No additional code is needed.

7 years of this bug.. and your solution is best
