### ISSUE TITLE
bootstrap table editable

### ISSUE THREAD

**Issue by netcy** [wenzhixin/bootstrap-table#5727]
bootstrap table表格不支持编辑功能，写了个简单插件 https://gitee.com/netcy/bootstrap-table-editor ，不知道后续是否会支持？

**Comment by ShreeKrishna1590** [comment]
The bootstrap table table does not support the editing function. I wrote a simple plug-in https://gitee.com/netcy/bootstrap-table-editor, I wonder if it will be supported in the future?


**Translation of issue no. 5727 (https://github.com/wenzhixin/bootstrap-table/issues/5727)**

**Comment by djhvscf** [comment]
Do you have an example of that editor?
