### ISSUE TITLE
Problem while updating cell of "parent" table

### ISSUE THREAD

**Issue by thedoudou07** [wenzhixin/bootstrap-table#5729]
Hello,

The context is as follow : I have parent table containing subtables which can also contain subtables, etc... It is a multi levels table.
When I change a cell value of a subtable, I want to update the parents cell with a custom calculation.

I tried :
$('#table').bootstrapTable('updateCell', {index: 0, field: 'risk_comment', value: '5'  });
-> all opened subtables are collapsed (I want to keep them opened/detailed as previously).

I also tried : 
$('#table').bootstrapTable('updateCell', {index: 0, field: 'risk_comment', value: '5' , reinit: false });
-> all subtables remain opened but the parent cell is not updated

If you have any suggestion on this point, thank you.

**Comment by UtechtDustin** [comment]
I guess that issue is not solvable yet, because of the history the bootstrap-table the table will be recreated each time a value has changed or other events happens.
The `reinit: false`  stops the table from recreating and just change the dataset of the table, which also means the value will not be displayed instantly (after the table will be redrawn, the value should be visible).

**Comment by thedoudou07** [comment]
Thank you for your answer, even if it is the one I was afraid of.

I was thinking of a workaround which consists in auto-expand the subtables just after the redraw of the main table.
It could be "acceptable".
But untill now it does not work as I expected :
for example when I use : $("#table").bootstrapTable('expandAllRows'); on the main table
-> all subtables display the same "child" information from the last subtable as shown in the picture

Do you have an explanation please ?

![pb](https://user-images.githubusercontent.com/83972659/117699909-a6cc1b80-b1c5-11eb-9076-6393ef913739.jpg)

**Comment by thedoudou07** [comment]
I am building the table like this with the Expand Row event attached.
///////////////////////////////////////////////////////////////////////////

	var $current_level = 1;
	buildTable($table, json_data, $current_level);


	function expandTable($detail, level)
	{
		$current_level++;
		$.ajax({
			type: "GET",
			url: "php/get_data.php",
			dataType: 'json',
			contentType: "application/json; charset=utf-8",
			success: function(response)
			{
				buildTable($detail.html('<table></table>').find('table'), response, $current_level);
			},
			error: function(response)
			{
				alert("Error loading data");
			}
		});
	}
/////////////////////////////////////////////////////////////////////////
	function buildTable($el, jsonData, level)
	{
		var row, columns = [], data = [];

		// COLUMNS
		columns.push({ field: "type", title: "Type", align: "left", ....... },
                             { field: "impact", title: "Impact", ................ },
                             { field: "expo", title: "Expo", .......... },...........
		});

		// DATA
		for (var j = 0; j < jsonData.length; j++)
		{
			if ($current_level < $max_levels)	$has_child = true;

			if (((jsonData[j]["risk_level"] == "1") && ($current_level == "1")) || (jsonData[j]["parent_id"] == $current_parent_id))
			{
				row = {};
				Object.keys(jsonData[j]).forEach( (k) => {
					row[k] = jsonData[j][k];
				})
				data.push(row);
			}
		}

		$el.bootstrapTable({
			uniqueId: "risk_id",
			columns: columns,
			data: data,
			undefinedText: '',
			editable: true,
			showHeader: $current_level == 1,
			detailView: $has_child,
			fixedColumns: true,
			fixedNumber: 6,
			onExpandRow: function (index, row, $detail) {
				$current_level = row["risk_level"];
				$current_parent_id = row["risk_id"];
				expandTable($detail, $current_level);
			}
		})
	}

**Comment by thedoudou07** [comment]
Or is it possible to access to the HTML cell element to change the value, because the table is a simple view for me. The real data are stored in the database ?

**Comment by UtechtDustin** [comment]
@thedoudou07 As i wrote, we need a example using our editor (no raw html in the issue).

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we got no response and no example from you within 7days.
If you still need help plesae provide us an example!
