### ISSUE TITLE
How to get index of select row

### ISSUE THREAD

**Issue by wenger66** [wenzhixin/bootstrap-table#573]
How to get index of select row? help me

**Comment by djhvscf** [comment]
Hello @wenger66 you have to use something like this:

With this function you can get the selected row object:

```javascript
var $table = $('#yourTableID');
    $(function () {
        $table.on('click-row.bs.table', function (e, row, $element) {

        });
    });
```

Does it make sense?

**Comment by wenzhixin** [comment]
#415 
Example: http://issues.wenzhixin.net.cn/bootstrap-table/#415.html

**Comment by jayeshtank** [comment]
I think you can do it by response handler.

function responseHandler(res) {
	$.each(res.rows, function (i, row) {
		row.index = i;
	});
	return res;
}

<table id="table-pagination"   data-response-handler="responseHandler">
var data = $("#table-pagination").bootstrapTable('getSelections');
