### ISSUE TITLE
Sort with custom button / how to call 'sort' method / using sort in custom and card view?

### ISSUE THREAD

**Issue by eliezra236** [wenzhixin/bootstrap-table#5732]
Hi,
I am trying to create a sort to be used directly from the card mode (custom mode in my case).

I created the button myself but I can't find a method to call sort on a field when not in table view.
Like the option to filter, I am looking for something like:

```
$("#gamesTable").bootstrapTable("filterBy", filter, {
    sortAlgorithm: sorter }
```

**Comment by eliezra236** [comment]
I found a way to solve this. You can use $('#table').bootstrapTable("refreshOptions", {}) to change the sort options and it will take effect.

In the above example you can use:

```
<button onclick="sorter()">
  Sort by name
</button>

<script>

  function sorter() {
    console.log("here")
    $("#table").bootstrapTable("refreshOptions", {
    sortName: "name",
    sortOrder: "desc",
  });
  }
</script>
```
of course, you can modify it to sort on whichever collum you want and change the order.

Hope it helps whoever stumbles here on the future

**Comment by jynxy** [comment]
just tried this, it reverses then puts it back ?
