### ISSUE TITLE
Inline edit a cell without x-editable

### ISSUE THREAD

**Issue by Federico-Luna** [wenzhixin/bootstrap-table#5733]
Hello Wenzhixin.

I would like to be able to inline edit a cell content or all cells of a row without using the editable extension. Is it possible to get the id of a cell (td) to put an input or a select as needed?

Thank you very much.

**Comment by CarsonSlovoka** [comment]
You can use [td.contentEditable=true](https://www.w3schools.com/tags/att_global_contenteditable.asp)

below is an example from my project for your reference

> https://github.com/CarsonSlovoka/excel/blob/4ffe8ecf4556cc74541860bef19f76c926305a2b/app/urls/static/js/src/file/file.js#L137

👆 set ``td.contentEditable=true`` when [onclickcell](https://bootstrap-table.com/docs/api/events/#onclickcell)

**Comment by wenzhixin** [comment]
Examples:
* https://live.bootstrap-table.com/code/wenzhixin/7813
* https://examples.bootstrap-table.com/#issues/987.html
