### ISSUE TITLE
使用onPageChange时，不触发mergeCells，怎么办

### ISSUE THREAD

**Issue by kaerwang** [wenzhixin/bootstrap-table#5734]
默认第一页已经显示合并效果，点击右下角的第二页，合并的方法又没有作用了，并且再返回第一页也没有合并效果了

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by MrLhr** [comment]
translate ： The default first page already shows the merge effect, click the second page in the lower right corner, the merge method has no effect again, and return to the first page also has no merge effect

**Comment by kaerwang** [comment]
> Can you translate this issue to english, please?

sry.  My English is poor.  You can try Google translate.

**Comment by wenzhixin** [comment]
https://live.bootstrap-table.com/code/wenzhixin/7737
