### ISSUE TITLE
When the server loads the table, click on the paged table and the data flashes, giving the impression that it is refreshin

### ISSUE THREAD

**Issue by MrLhr** [wenzhixin/bootstrap-table#5735]
When the server loads the table, click on the paged table and the data flashes, giving the impression that it is refreshin。

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by MrLhr** [comment]
With this CSS style, it turns off the visual refresh effect .



 /* Increase time of opacity transition effect */
 .bootstrap-table .fixed-table-container .fixed-table-body .fixed-table-loading {
    display: flex;
    transition: visibility 0s, opacity 0.5s ease-in-out;
    opacity: 0;
    visibility: hidden;
  }
  
  /* Decrease opacity, so we can see the table content while it loads  opacity: 0.75;  */
  .bootstrap-table .fixed-table-container .fixed-table-body .fixed-table-loading.open {
    visibility: visible;
    opacity: 0;
  }
