### ISSUE TITLE
get exception when click row in card view 

### ISSUE THREAD

**Issue by wenger66** [wenzhixin/bootstrap-table#574]
Uncaught TypeError: Cannot call method 'click' of undefined
h.initBody.$selectItem.off.on.dbootstrap-table.min.js:7
n.event.dispatchjquery.min.js:3
n.event.add.k.r.handle

**Comment by wenzhixin** [comment]
Please provide a jsFiddle that is base on these [examples](http://bootstrap-table.wenzhixin.net.cn/examples/#basic), thanks.

**Comment by wenzhixin** [comment]
I have done a test, but do not have this problem, please update to the latest and try it again.
If exists please help to provide a jsFiddle.
