### ISSUE TITLE
GetData and updateRow

### ISSUE THREAD

**Issue by promotux** [wenzhixin/bootstrap-table#5740]
if i work on a row and not updateRow after some modication  but i call all the data with getData i have the row modified though the tabel show the "original" data. 
is there a way to flush before to getData o to be sure to get the data aligned with what the table shows ? 
thanks

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by promotux** [comment]
https://live.bootstrap-table.com/code/promotux/7807
looking in console ...you can see that getData shows the modifed rwo but table ( without updateRow is stille with item-1) ...

**Comment by wenzhixin** [comment]
I think you can clone the row to solve your problem: https://live.bootstrap-table.com/code/wenzhixin/7808.

**Comment by promotux** [comment]
it works ... thanks i still think it is a strange behavior that getData and table return different rows .

**Comment by wenzhixin** [comment]
That's because the `getData` method returns the original rows instead of the deep clone rows.

**Comment by carlos-gomez-espinosa** [comment]
In relation with this issue, i've found the next 'error'

https://live.bootstrap-table.com/code/carlos-gomez-espinosa/7925

having a table with data-sort-name and order properties set, when using the reorder row plugin, method getData not return the data in the order i've set moving my rows.

Thanks!

**Comment by wenzhixin** [comment]
ref #5682 
@carlos-gomez-espinosa please help to test the `develop` branch have solved your problem?
https://live.bootstrap-table.com/code/wenzhixin/7943

**Comment by carlos-gomez-espinosa** [comment]
I've just test it with develop branch JS and still failing. It's easy to test, only add the data-sort-name and order and you can see the reorder getData method returns the rows, but not in the order you can set it

**Comment by UtechtDustin** [comment]
As @wenzhixin already said the method `getData` returns det ORIGINAL data of the table.
So if you modify the data e.g. while reordering the rows the internal data will not be changed.

This issue is quite old, if you still need help please let us know and please provide us an usecase for that.

**Comment by promotux** [comment]
i don't know why close a bug that is still there 
it is a problem if you change a row but getData give you the wrong data .

**Comment by UtechtDustin** [comment]
@promotux 
As @wenzhixin and me already said, the method `getData` returns the ORIGNAL data, so its not a bug.
It works as designed.
Please also read the documentation, the description of the function also explains this.
```
Get the loaded(!!!) data of table[...]
```

I also wrote, if someone still need help with that we can reopen the issue.
So please explain us why do you need the modified data and we could consider to implement a method which returns the current/modified data.

**Comment by promotux** [comment]
Because getData return different data of the data show in the table. i think that i can expect to get the same data that i can see in the table not the original data that i load in the the table originally. it is confusing and prone to error . Sorry but "clone" the row is not a solution for me but just a work around. I load a data in the table, i get a row, change some data, update the row and getData to save to the database and i GET the old data,  it makes sense to you ? sorry but i can't grasp the logic.  it create prblems with reoarder rows and with modified data. Thanks

**Comment by UtechtDustin** [comment]
As the document clearly says its the loaded data not the current data, it's not a problem of the BT, it's more a problem of the developer.
So this it's only confusing if the develop don't read the documentation.

If you want to save the data back to the database you maybe should update the data while updating the data in the table:
Which should be a better solution or a user could the whole table data and you would save it.
If you update  the data row by row (after a row has changed) you can check on the backend if the saved data is valid.

I guess we could still implement a method which returns the saved data, but the implementation could be a bit harder i guess.
In my opinion we have other issues which has a higher priority.
What do you think @wenzhixin @djhvscf ?

@promotux 
Please be a bit more kind the next time, we only explaint the current behavior.
