### ISSUE TITLE
bootstrap-table, ajax, server side

### ISSUE THREAD

**Issue by xmbohx** [wenzhixin/bootstrap-table#5741]
Hi, I am looking for documentation as subjected and found many posts to come to 
`http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/custom-ajax.html).`
but this site is not available. Could anyone advise the alternative?

**Comment by huygens545** [comment]
Yes, all the examples moved to : https://examples.bootstrap-table.com/

I've found something about custom AJAX here: https://examples.bootstrap-table.com/index.html#options/ajax-options.html
