### ISSUE TITLE
Bug? 'getData' with 'useCurrentPage' set to 'false' not working with server-side pagination

### ISSUE THREAD

**Issue by huygens545** [wenzhixin/bootstrap-table#5743]
**Description**  

I'm trying to get all the data of my server-side paginated table.

the syntax apparently is: 
`$table.bootstrapTable('getData', false)`
but it does seem to work (see live example below)

**Example (optional)**  
https://live.bootstrap-table.com/code/huygens545/7793

**Comment by dafi-mcisse** [comment]
hello @huygens545, did you find a solution to your problem?

**Comment by huygens545** [comment]
Yes, but the problem was due to my bad understanding of how server side pagination works, `bootstrap-table` has nothing to do with it...
In fact, in server-side pagination, it is the server (i.e **yourself**), who needs to take care of it: i.e in my case of `getData`, the server needs to provide all these data.
