### ISSUE TITLE
Error while searching when highlight & maintain metadata are enabled

### ISSUE THREAD

**Issue by kwridan** [wenzhixin/bootstrap-table#5747]
**Bootstraptable version(s) affected**:
version 1.18.3

**Description**  
An error occurs while searching when search highlight and maintain metadata are enabled.

```
TypeError: undefined is not an object (evaluating 'h.toString')
```

**Example**  

https://live.bootstrap-table.com/code/kwridan/7888

```html
<table
  id="table"
  data-toggle="table"
  data-search="true"
  data-search-highlight="true"
  data-maintain-meta-data="true"
  data-url="json/data1.json">
  <thead>
    <tr>
      <th data-field="state" data-checkbox="true"></th>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
</table>
```

- Type a term in the search box
- Notice an error occurs _(in the web inspector)_ and search doesn't work

**Additional Context**

I believe the source is [`defValue = value.toString().replace(regExp, marker)`](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1590).

From experimenting, I found a workaround to the issue by marking the checkbox field as non searchable:

```diff
 <tr>
-     <th data-field="state" data-checkbox="true"></th>
+     <th data-field="state" data-checkbox="true" data-searchable="false"></th>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
 </tr>
```

**Comment by UtechtDustin** [comment]
Thank you for the report, i create a PR which will fix that problem! :-)
