### ISSUE TITLE
单选按钮不选择的情况下getSelections返回所有值而非空

### ISSUE THREAD

**Issue by fifsky** [wenzhixin/bootstrap-table#575]
不选中任何单选按钮的情况下
var select = $('#_select_store_table').bootstrapTable('getSelections');
console.log(select);
[Object, Object, Object, Object,  Object, Object, Object]

如果选中的情况是返回选中的一个Object

**Comment by wenzhixin** [comment]
Please provide a jsFiddle that is base on these [examples](http://bootstrap-table.wenzhixin.net.cn/examples/#basic), thanks.

**Comment by fifsky** [comment]
https://jsfiddle.net/4Lrx26pt/embedded/result/

错误主要是由于 <th data-field="name" data-radio="true"></th>  这一行的data-field导致的

**Comment by wenzhixin** [comment]
你用个没有的 field 就可以了，例如 data-field="state"，因为用 name 的话，有值初始化的时候默认是选中的。
