### ISSUE TITLE
Bootstrap table inbuilt search not working for boolean values. On searching boolean value, it is showing non-matching rows.

### ISSUE THREAD

**Issue by NandiniDas** [wenzhixin/bootstrap-table#5754]
The enabled column/field in my table contains boolean value, true or false. When I try to search boolean values, e.g. true or false., the bootstrap table search does not show matching rows, instead it is showing non-matching rows. Since the inbuilt search was not working for boolean values, I tried to make it work using jquery but that is also not working because when I am trying to retrieve the value of search input with javascript/jquery, it is showing strange results, showing '1', sometimes 'on'. Any suggestion/solution would be helpful.

Below is my code.

**My table:**

<table id="Routing" data-toggle="table" 
						data-toolbar="#Routing" data-maintain-selected="true"
						data-url="wf/xx/xx" data-cache="false"
						data-click-to-select="true" data-striped="true"
						data-pagination="true" data-search="true"  data-show-toggle="true" data-sort-order="desc"
						data-sort-name="id" data-show-columns="true"
						data-show-refresh="true" data-page-size="50" data-unique-id="id"
						data-response-handler="responseHandlerRouting"
						data-page-list='[10, 20, 30, 50, 100, 200]'>
						<thead>
							<tr>
								<th data-field="state" data-width="2%" data-checkbox="true"></th>
								<th data-field="id" data-width="5%" data-visible="false">Id</th>
								<th data-field="description" data-width="15%"
									data-sortable="true">Name</th>
								<th data-field="rule" data-width="15%" data-sortable="true"
									data-formatter="ruleValueFormatter" data-visible="false">
									Value</th>
								<th data-field="workflows" data-width="15%" data-sortable="true">flow</th>
								<th data-field="family" data-width="15%" data-sortable="true">
									Family</th>
								<th data-field="type" data-width="10%" data-sortable="true">
									Type</th>
								<th data-field="version" data-width="10%" data-sortable="true">
									Version</th>
								<th data-field="enabled" data-width="10%" data-searchable="true" data-sortable="true">Enabled</th>
								<th data-field="priority" data-width="10%" data-sortable="true">Priority</th>

							</tr>
						</thead>
					</table>

[Table code.docx](https://github.com/wenzhixin/bootstrap-table/files/6586636/Table.code.docx)

**Javascript/Jquery code**:

  $('#Routing').on('all.bs.table', function (e, name, args) {
                 var val1= $(this).find('input:text').val();
                   console.log("value......", val1);                     // <-- Whatever I write in search, I am getting either 1 or on as the value

                   $(this).find('input:text').on("keyup", function() {
         	         console.log("inside search.....");
         	         var value = $(this).val();

         	       $("#Routing tr").each(function(index) {
         	          if (index !== 0) {
         	            $row = $(this);
         	            var id = $row.find("td").text();
         	            if (id.indexOf(value) !== 0) {
         	                $row.hide();
         	           }
         	           else {
         	                $row.show();
         	            }
         	        }
         	    });
         	});
          }
         	       
	     )

**Comment by NandiniDas** [comment]
Table code:

<table id="Routing" data-toggle="table" 
data-toolbar="#Routing" data-maintain-selected="true"
data-url="wf/xx/xx" data-cache="false"
data-click-to-select="true" data-striped="true"
data-pagination="true" data-search="true"  data-show-toggle="true" data-sort-order="desc"
data-sort-name="id" data-show-columns="true"
data-show-refresh="true" data-page-size="50" data-unique-id="id"
data-response-handler="responseHandlerRouting"
data-page-list='[10, 20, 30, 50, 100, 200]'>
<thead>
<tr>
<th data-field="state" data-width="2%" data-checkbox="true"></th>
<th data-field="id" data-width="5%" data-visible="false">Id</th>
<th data-field="description" data-width="15%"
data-sortable="true">Name</th>
<th data-field="rule" data-width="15%" data-sortable="true"
data-formatter="ruleValueFormatter" data-visible="false">
Value</th>
<th data-field="workflows" data-width="15%" data-sortable="true">flow</th>
<th data-field="family" data-width="15%" data-sortable="true">
Family</th>
<th data-field="type" data-width="10%" data-sortable="true">
Type</th>
<th data-field="version" data-width="10%" data-sortable="true">
Version</th>
<th data-field="enabled" data-width="10%" data-searchable="true" data-sortable="true">Enabled</th>
<th data-field="priority" data-width="10%" data-sortable="true">Priority</th>

</tr>
</thead>
</table>

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I close this issues, as we got no response from you within 7 days.
If you still need help, please provide us an example.
