### ISSUE TITLE
bootstraptable Front end search problem

### ISSUE THREAD

**Issue by aganlove** [wenzhixin/bootstrap-table#5755]
Hello, please consult me. I always use the bootstartable framework to display the data returned by the background, and the front-end search and export buttons are also in normal use.
您好，麻烦咨询一下，我一直用的bootstarptable框架来展示后台返回的数据，前端的搜索、导出等按钮也正常使用。

![image](https://user-images.githubusercontent.com/18565928/120571332-71c18a80-c44c-11eb-999c-76e345a7b21d.png)

Question: 
     before, the search box was a front-end search, which filtered the data of the table on this page, and then upgraded the framework. Now the search box becomes a background search. The background search workload is too large, or would you like to use the front-end search function. Is there any configuration to be configured? Or what switch can make the search box not to ask the background to obtain data, only filter the data of this page, please take time to answer, I would be grateful.

问题：以前搜索框是前端搜索，过滤本页面表格的数据，后面升级了框架，现在搜索框就变成了后台搜索，后台搜索工作量太大，还是想用回前端搜索功能。是有什么配置需要配吗？或者有什么开关能直接使得搜索框不去请求后台获取数据，只过滤本页面的数据，麻烦抽空解答一下，不胜感激。

**Comment by aganlove** [comment]
@wenzhixin 大佬，麻烦解答一下

**Comment by wenzhixin** [comment]
你是不是设置了 [`sidePagination`](https://bootstrap-table.com/docs/api/table-options/#sidepagination)，不设置默认就是进行客户端搜索的。

**Comment by aganlove** [comment]
是设置了 data-side-pagination="server"，但是我还想在客户端搜索，分页数据是从后台查询的，但是查询过滤可以只过滤当前页面，有没有办法配置，还是只能去改源码了？

**Comment by wenzhixin** [comment]
是的，不支持这个功能，你可以写扩展去增加这个功能。

**Comment by aganlove** [comment]
好的，感谢您的回答！
