### ISSUE TITLE
Problem with second thead

### ISSUE THREAD

**Issue by payambordbar** [wenzhixin/bootstrap-table#5756]
Hi
I use [smooth-scrollbar](https://github.com/idiotWu/smooth-scrollbar) next to this library
Due to the existence of the second thead, this library can not work properly
Is there a way to delete the second thead?

![Screenshot 2021-06-03 225732](https://user-images.githubusercontent.com/45229646/120694232-31e7bb00-c4bf-11eb-9121-4c8b5874d340.png)

Example:
line 3, 234 
https://live.bootstrap-table.com/code/payambordbar/7930

Also Thanks for this library.

**Comment by djhvscf** [comment]
Looks like this is an issue related to a third party library.  Without that library it is working as expected

https://live.bootstrap-table.com/code/djhvscf/8145
