### ISSUE TITLE
Headers row is not showing in internet explorer 11 after forcing search, sort and pagination in order to bring the table back to its previous state

### ISSUE THREAD

**Issue by pvlastaridis** [wenzhixin/bootstrap-table#576]
In order to get table back to its state (pagination, search and sort) after update or delete I introduced in your code one more allowedMethod. Everything works OK in chrome, firefox but in IE the Headers row disappears. If you change page everything reappears. Has anyone had similar problems. Unlikely but in hope!!

    BootstrapTable.prototype.forceSearch = function (params) {
        var text = params.text;
        // trim search input
        if(this.options.trimOnSearch) {
            this.$toolbar.find('.search input').val(text);
        }

        if (text === this.searchText) {
            return;
        }
        this.searchText = text;
        this.options.sortName = params.sortName;
        this.options.sortOrder = params.sortOrder;
        this.options.pageNumber = params.pageNumber;
        this.initSort();
        this.initSearch();
        this.updatePagination();
        this.trigger('search', text);
    };

Also added this in allowed methods 

    var allowedMethods = [
        'getOptions',
        .........,
        'forceSearch'];

Calling this in javascript is sth like this: 

    var options = $('#table-methods-table').bootstrapTable('getOptions');                                 
    var filtby = $('.search input').val();
    $.post('/elke/logic/create.php', data)
       .done(
           function (data) {                                                                                 
                   $.get("/elke/logic/loadtablejson.php")
                       .done(function (data) {                                        
                               $('#table-methods-table').bootstrapTable('destroy').bootstrapTable({data: data});
                               $('#table-methods-table').bootstrapTable('forceSearch', 
                                                        {
                                                            text: filtby, 
                                                            pageNumber: options.pageNumber,
                                                            sortName: options.sortName,
                                                            sortOrder: options.sortOrder
                                                        });
                                                    });                                        
                                              });

**Comment by djhvscf** [comment]
Can you provide a jsfiddle??

**Comment by wenzhixin** [comment]
Maybe you can use the [cookie extension](http://bootstrap-table.wenzhixin.net.cn/extensions/#table-cookie)?

**Comment by pvlastaridis** [comment]
I did not know there is a similar feature in cookies extension thanks
