### ISSUE TITLE
Server sort doesn't show the loading message

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#5761]
**Description**  
Server sort doesn't show the loading message.
This could be a problem for the people trying to automate tests over tables.

https://examples.bootstrap-table.com/index.html#options/server-sort.html#view-source

Desired state:
On click on the "sort" icon, show the loading message to give the user a proper visual feedback.

Actual state:
On click on the "sort" icon, nothing suggests a remote request has been fired.

By sort icon I mean this one
![Bootstrap-Table-Examples](https://user-images.githubusercontent.com/6325475/121499072-f2e0ca80-c9d4-11eb-9faa-611d1aa8c5e0.png)

**Comment by UtechtDustin** [comment]
As default the table sort is silent, you disable that feature using the [silentSort](https://bootstrap-table.com/docs/api/table-options/#silentsort) option.

Example: https://live.bootstrap-table.com/example/options/silent-sort.html
