### ISSUE TITLE
Can I change minimum length of search to 2?

### ISSUE THREAD

**Issue by eliezra236** [wenzhixin/bootstrap-table#5762]
Hi,
The minimum search length is 3, is there an option to set it to 2?
There are Asian names in my table such as "yu" that can't be searched because of it.

**Comment by eliezra236** [comment]
> I'm not sure what do you mean, the search has no minimum length restriction.
> As you can see in [this example](https://live.bootstrap-table.com/example/options/table-search.html) the table will update on the first entered letter.

That's weird, as I am using the same code and it won't trigger if it's shorter than 3 letters

**Comment by UtechtDustin** [comment]
Could you please create a example with your code using our [editor](https://live.bootstrap-table.com/) ?

**Comment by UtechtDustin** [comment]
I close this issues, as we got no response from you within 7 days.
If you still need help, please provide us an example.
