### ISSUE TITLE
Issues with filtering 

### ISSUE THREAD

**Issue by labyrinth23232** [wenzhixin/bootstrap-table#5763]
**Bootstraptable version(s) affected**:

4.6.0
**Description**  

I had three filtering issues, was not sure if I need to open seperate ticket for each

1.when adding height to table, datepicker filter does not show selected date and wont filter rows

2.setting multiselect filter to true, still stays as single select

3.adding native options to datepicker, as per docs, does nothing

While the example below has the issues I mentioned on my application, in the online editor it wont have any filtering even though I am adding the correct files, and parameters to the table. But on my application it will have filtering, but will still have the issues mentioned above.

Thank you.

**Example**  

[Filtering Issue.txt](https://github.com/wenzhixin/bootstrap-table/files/6635541/Filtering.Issue.txt)

**Possible  (optional)**  

**Additional context**

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I'm closing this issue, because we got no response/example from you within 7 days. If you still need help please provide us an example.
