### ISSUE TITLE
Print images

### ISSUE THREAD

**Issue by rakucmr** [wenzhixin/bootstrap-table#5766]
**Bootstraptable version(s) affected**:
1.18.3 (All versions on plugin)

**Description**  
If you modify printPageBuilder and include in response images will not be printed because the page is not completed loaded.
This happens in Chrome / Opera / Mozila / Edge, on IE is ok.

**Possible  (optional)**  
You can fix this by modifying bootstrap-table-print.js from:
```
...
newWin.document.write(this.options.printPageBuilder.call(this, table))
newWin.document.close()
newWin.focus()
newWin.print()
newWin.close()
...
```

to this:

```
...
newWin.document.write(this.options.printPageBuilder.call(this, table))
newWin.document.close()
newWin.focus()
if(document.documentMode){ // IE direct print
      newWin.print()
      newWin.close()
}else{
      newWin.onload = function(){ // Not IE wait to load and print
            newWin.print()
            newWin.close()
      };
}
...
```

**Comment by UtechtDustin** [comment]
Thanks for the report, could you please provide us an example using our [online editor](https://live.bootstrap-table.com/)?

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
