### ISSUE TITLE
BS5: `input-group-append` does not exist anymore

### ISSUE THREAD

**Issue by lukasjuhrich** [wenzhixin/bootstrap-table#5767]
**Description**  
In v1.18.3, `src/constants/index.js`, the Bootstrap 5 section features the following:

```js
  inputGroup: '<div class="input-group">%s<div class="input-group-append">%s</div></div>'
```

However, in Bootstrap 5, that class [does not exist anymore](https://getbootstrap.com/docs/5.0/migration/#forms). Elements can just be added as children of the `form-group` element (see [the example in the docs](https://getbootstrap.com/docs/5.0/forms/input-group/#basic-example)).

**Comment by UtechtDustin** [comment]
Thanks for reporting that, we will adjust that!
