### ISSUE TITLE
No matching records found 

### ISSUE THREAD

**Issue by JouberthAndrade** [wenzhixin/bootstrap-table#5768]
Hello, I realy need a help! =)

I'm use bootstrap table to show dynamically my tables, but when I call the load method, the browser show me 'No matching records found " even with records.

I search my record from controller..

Here is part of my code with the problem...

 $.ajax({
            type: "POST",
            timeout: 120000,
            async: true, 
            url: BASE_SITE + "/WorkOrderProgramming/JsonGridWorkOrder",
            data: {
                Registration: registration, SearchWO: searchWO
            },
            success: function (data) {
                if (data.length > 0) {
                    $.each(data, function (key, listaMain) {
                        console.log('key:', key);
                        console.log('listaMain:', listaMain);
                        var table = GetTableProgramming(key);
                        $("#divGridProgramming").append(table);

                        console.log('dados:', listaMain.Lista);

                        $('#tbGridWO-'+key).bootstrapTable();
                        $('#tbGridWO'+key).bootstrapTable('destroy');
                        $('#tbGridWO'+key).bootstrapTable();
                        $('#tbGridWO'+key).bootstrapTable('load', {
                            data: listaMain.Lista
                        });

                    });
                }
}, error: function (xhr, textStatus, error) {
                if (xhr.statusText == 'timeout') 
                    $.fn.ModalInformacao("Erro", "The query has timeout, please try again.");
                else
                    $.fn.ModalErroSistema('Erro no sistema', xhr.statusText + ' - ' + xhr.responseText);
            }
        });
        
        
![image](https://user-images.githubusercontent.com/38113094/122238999-f5409a00-ce96-11eb-8746-6b1701095781.png)

**Comment by UtechtDustin** [comment]
Hey, please provide us an example using our [https://live.bootstrap-table.com/](online editor).

**Comment by djhvscf** [comment]
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!
