### ISSUE TITLE
table height not working

### ISSUE THREAD

**Issue by ajendrex** [wenzhixin/bootstrap-table#577]
Hello,

I have this:

    <table class="table" data-toggle="table" data-height=500>
        <thead> a row... </thead>
        <tbody> some rows... </tbody>
    </table>

However, the table's height keeps being 888. I was expecting to see a vertical scroll bar in it, with 500 pixels in table's height. Also, on the console I have this error:

TypeError: that.options.columns[i] is undefined  (bootstrap-table.js:354:20)

Any idea what could I be doing wrong?

Thanks,
Hector.

**Comment by wenzhixin** [comment]
Please provide a jsFiddle that is base on these [examples](http://bootstrap-table.wenzhixin.net.cn/examples/#basic), thanks.

**Comment by ajendrex** [comment]
I just realized what the problem was. I had a table before this one, witn no thead section, with some <th> cells and with data-toggle="table", that was a mistake and removing the data-toggle part solved the error.

Thanks,
H.
