### ISSUE TITLE
Why data-formatter is being executed every time the options are refreshed?

### ISSUE THREAD

**Issue by eliezra236** [wenzhixin/bootstrap-table#5771]
Hi,
I was wondering if this slows the performance and if there is maybe a way to prevent it?
My data is not changing after initial load, but there are things like date formatter or name formatter that are being called for 700+ items every time I sort / search / apply filter.

Can I cancel it so it keeps the same value and doesn't re-calculate them every time?

**Comment by UtechtDustin** [comment]
Hey, the bootstrap-table was developed for year now and month for month there are new features added.
So this is how the table works right now, after each action (sort, search, etc.) the whole table will recreated which means all functions (also the formatter) will be called again.
Our goal for the future is that we only update the data/elements which must be updated. But that will take a while, as its hard to rewrite the whole table featureset.

What are you doing inside the formatter that this is bad for you ?
