### ISSUE TITLE
On Safari on desktop with fixed columns and data height, .fixed-columns class gets a width set, but not on chrome

### ISSUE THREAD

**Issue by finologytech** [wenzhixin/bootstrap-table#5773]
Safari on desktop mac 
![image](https://user-images.githubusercontent.com/65877411/123498530-1e5aea80-d64e-11eb-93c8-32d82b979aff.png)

Same code on chrome
![image](https://user-images.githubusercontent.com/65877411/123498544-3599d800-d64e-11eb-86ec-2120e72578d1.png)

Due to this bug, on safari browsers the fixed table feature gets activated on desktops and displays the duplicate cloned elements.

As a Current workaround we are trying to reverse that after loading. May be something related to **needFixedColumns** being wrongly reported.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I'm closing this issue, because we got no example within 7 days.
I also tested it on chrome and the width will be set (and will be recalculated while changing the size of the browser).
If you still think this is a bug, please provide us an example.
