### ISSUE TITLE
FilterControl bug when using searchOnEnterKey option

### ISSUE THREAD

**Issue by tblima** [wenzhixin/bootstrap-table#5774]
I am facing problems using searchOnEnterKey option in FilterControl extension.

In the example below, I tried to fill the column 'Item Name' with 'Item 0' (without pressing enter) and then fill the 'Item Price' with '$' and finally pressing enter. Only the last input (the focused one) is added to filter.

Is it possible to filter by all the columns at once?

[https://live.bootstrap-table.com/code/tblima/8112](https://live.bootstrap-table.com/code/tblima/8112)

Thanks in advance

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9719

**Comment by djhvscf** [comment]
This issue is fixed here: https://github.com/wenzhixin/bootstrap-table/pull/5583

**Comment by UtechtDustin** [comment]
> Example with fix: https://live.bootstrap-table.com/code/djhvscf/9719
I guess we have a cache issue of the editor.... This example also don't work for me.
If i enter `Item 0` in `Item Name` and `$` ind `Item Price` and press enter in the `Item Price filter` the table will be recreated and nothing happens, but if i press enter in the  `Item Name` input it works.

**Comment by djhvscf** [comment]
@wenzhixin how can we force the editor to use the latest version?
