### ISSUE TITLE
Clear Filters removes all cookies

### ISSUE THREAD

**Issue by chollingsworth** [wenzhixin/bootstrap-table#5776]
Hi,

Version 1.18.3.    I have the "data-show-search-clear-button" set to true to clear filters.   I am using the cookies extension, just to store columns layout: 
data-cookies-enabled = ['bs.table.columns']

The clear button seems to remove all of the cookies.

**Comment by djhvscf** [comment]
That's the expected behavior

**Comment by UtechtDustin** [comment]
@djhvscf I'dont think this is a bug at all.
As the documentation also say's:
```
Set true to show a clear Button behind the search input which will clear the search input (also all filter from filter-control (if enabled)).
```
This button should clear the inputs and should not delete all cookies.

**Comment by djhvscf** [comment]
But why should we keep the cookies? I mean if the behavior is that every time we set a value in filter control, the cookie is also set.. Why this could be different? Maybe we need to modify the docs

**Comment by UtechtDustin** [comment]
Maybe you missunderstood something (or maybe i), but he don't mean the filter cookies at all.
He mean the other Cookies e.g. the custom ordering of columns, which means  the order of the columns would be resettet every time you want to clear the filter.

Example: https://live.bootstrap-table.com/code/UtechtDustin/8404
You can reproduce with this steps:

1. Order the Column `Item Name` before the column `ID`
2. Refresh the page and you see the order is still there.
3. Click the FILTER Clear Button
4. Refresh the page and the custom order of the columns are gone.

So in practice nobody would say "Oh, that looks like a "reset every customization i made"-Button. Instead everybody would see it as clear Filter Button.

**Comment by djhvscf** [comment]
Thanks for that explanation. Then definitely this is an issue
