### ISSUE TITLE
Pagination, Page Info and Page Size Custom Location

### ISSUE THREAD

**Issue by jynxy** [wenzhixin/bootstrap-table#5778]
Hi,

How do i go about having Pagination, Page Info and Page Size to Custom Location's ?

I'm looking to have Page size as a dropdown button in the toolbar next to Sort By Button (which i have working)

Page info i want to the right of pagination, and both pagination and page info in a custom location.

Is there any examples or code ? im looking through to find the answers to these and currently stuck.

Late one im looking to research next is to reset back to normal when using sort by button.

Thanks

**Comment by jynxy** [comment]
i have figured out how to reset the sort.

**Comment by djhvscf** [comment]
Awesome @jynxy

**Comment by jynxy** [comment]
Hi @djhvscf 

I still need help with the first part,  "How do i go about having Pagination, Page Info and Page Size to Custom Location's ?"

Thanks

**Comment by wenzhixin** [comment]
@jynxy  https://bootstrap-table.com/docs/api/localizations/

**Comment by jynxy** [comment]
Hi @wenzhixin i dont want to change the text or language, i want to put the pagination sections into a card header, not the card body,

This is how it currently looks

![image](https://user-images.githubusercontent.com/697606/124382253-569da100-dcbe-11eb-9286-de2cd18a36d5.png)

This is what im looking to achieve

![image](https://user-images.githubusercontent.com/697606/124382245-4daccf80-dcbe-11eb-9c7a-4accca7a7c51.png)

i just need a way to move them to the locations then i can style.

Thanks

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your settings currently.

**Comment by jynxy** [comment]
Dont see how the example will help, i cant add the data, i only need code on where i can put the pagination in a custom location, but needs to be split down,

https://live.bootstrap-table.com/code/jynxy/8156

**Comment by jynxy** [comment]
@wenzhixin @djhvscf any help please ? thanks

**Comment by sunhk25** [comment]
@wenzhixin @djhvscf 
is there any way to only hide "Showing....page" in pagination? thanks
https://bootstrap-table.com/docs/api/localizations/

**Comment by djhvscf** [comment]
See this https://live.bootstrap-table.com/code/djhvscf/8307 @sunhk25

**Comment by djhvscf** [comment]
@jynxy if you go to the documentation https://bootstrap-table.com/docs/api/table-options/#pagination you can double check what's supported at this moment
