### ISSUE TITLE
For Fixed Columns, Not able view scrollbar in Safari.

### ISSUE THREAD

**Issue by KrishMutyala** [wenzhixin/bootstrap-table#5780]
**Bootstraptable version(s) affected**: 4.6.0

**Description**  
For Fixed Columns, Not able view scrollbar in Safari.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by wenzhixin** [comment]
It's working well in Safari:
![image](https://user-images.githubusercontent.com/2117018/127008695-ac49aeba-a0f8-4bde-b3d3-709334fa556b.png)

**Comment by UtechtDustin** [comment]
As @wenzhixin said, it works well.
I also tested it on a iphone and a ipad.

If you think the bug still exists, please let us know.
