### ISSUE TITLE
Invert saved columns in cookie extentions

### ISSUE THREAD

**Issue by Naruto-kyun** [wenzhixin/bootstrap-table#5781]
**Description**  
Today, when you use the cookie plugin to save current visible columns, you should ask all users to check the visibility of new columns inside an already saved table.
The idea is to save hidden columns and not visible columns. So in case of new column, it will be visible by default.

I can do the PR quickly, but before i just want to know if the idea have a sense to you.

**Comment by djhvscf** [comment]
Hi @Naruto-kyun that does make sense. Please open the PR and let's review it.
