### ISSUE TITLE
footer customed 

### ISSUE THREAD

**Issue by npltr62** [wenzhixin/bootstrap-table#5782]
first an [sample](https://live.bootstrap-table.com/code/npltr62/8158)
I would like to custom a footer with colspan and rowspan properties. i tried to set it in tfoot tag but the behavior could be improve.
also i want add formatter unction
thanks

**Comment by djhvscf** [comment]
@npltr62 can you elaborate more about your issue? To be honest I don't understand what's your need

**Comment by wenzhixin** [comment]
Example: https://live.bootstrap-table.com/code/wenzhixin/8398

**Comment by UtechtDustin** [comment]
The example from @wenzhixin should solve your issue.
Please let us know if this don't resolve you're issue and you need more help.
