### ISSUE TITLE
showButtonIcons dont work

### ISSUE THREAD

**Issue by damirqa** [wenzhixin/bootstrap-table#5783]
**Bootstraptable version(s) affected**: 1.18.3

**Description**  
showButtonIcons dont work in javascript code, its work only attr of table

**Example** : [example](https://live.bootstrap-table.com/code/damirqa/8163)

**Comment by wenzhixin** [comment]
You need to use `true/false` instead of `'true'/'false'`, it's `Boolean` type.
https://live.bootstrap-table.com/code/wenzhixin/8164
