### ISSUE TITLE
Filter Control Extension: Data-Searchable Not Mentioned

### ISSUE THREAD

**Issue by Ajohn10** [wenzhixin/bootstrap-table#5784]
**Description**  
Through my own discovery by stepping through the code and nearly creating a new function, I found out that by setting data-searchable to true/false and then updating options for the bootstrap table, I could toggle a specific filter control off and on.  However, in the documentation for data-searchable, there is no mention of controlling anything in Filter Control, and vice versa as well.

**Comment by UtechtDustin** [comment]
I'm not sure if we should add information about that.
The "normal" options are global options and the options of the extensions are specific for the extensions.
If we would add a reference for each option which is also used in extensions, the documentation would blow up quiet fast.

What do you think @wenzhixin @djhvscf ?

**Comment by wenzhixin** [comment]
I think we can add a note for this option in the filter-control docs.

**Comment by djhvscf** [comment]
I agree

**Comment by UtechtDustin** [comment]
I guess anything is said here, PR's are welcome.
