### ISSUE TITLE
that.options.filterControls undefined in clearFilterControl

### ISSUE THREAD

**Issue by kwsz** [wenzhixin/bootstrap-table#5785]
**Description**  
I'm trying to use the clearFilterControl method but finally got _Uncaught TypeError: Cannot read property 'length' of undefined_.
I traced the codes and found it's because that.options.filterControls is undefined when running into [this line](https://github.com/wenzhixin/bootstrap-table/blob/f22f7a5e711f576cb562370a4ad062e52ae9f77f/src/extensions/filter-control/bootstrap-table-filter-control.js#L383).
As I didn't see _filterControls_ neither in _Options_ nor _Column options_ section in [the doc](https://bootstrap-table.com/docs/extensions/filter-control/), please help me figure out how to solve this problem.

Thanks in advance.

**Example**
It works well on the online Editor but not on my local side. 
https://live.bootstrap-table.com/code/kwsz/8190

Local side version:
bootstrap: 3.3.5
bootstrap-table: 1.18.3
bootstrap-table-filter-control: 1.18.3

**Comment by kwsz** [comment]
Solved by importing `bootstrap-table-cookie.js`.

I guess bootstrap-table-cookie.js is considered an optional file because it's in the extension directory.
so it might be a bug in clearFilterControl. Keep the issue open to be discussed.

**Comment by djhvscf** [comment]
It is fixed here: https://github.com/wenzhixin/bootstrap-table/pull/5583
