### ISSUE TITLE
Regex/Boolean search in filter fields

### ISSUE THREAD

**Issue by gladsonvm** [wenzhixin/bootstrap-table#5786]
**Regex/Boolean search in filterfields**  

Thanks for the wonderful framework!! I explored bootstrap-table and been using this awesome framework for quite a while.

It would be nice if regex search for filter field is implemented. Use case as below

- column in table contains strings 1asdf45_0099 and 25asd45_1888
- search on filter should return all strings with characters '45' (both of the above strings)

I can see some regex parsing/search in the code of bootstrap-tables but not for this use case.

**Comment by UtechtDustin** [comment]
I mark this issue as feature, as it would be good feature :-)
