### ISSUE TITLE
Custom View, doesnt show No matching records found

### ISSUE THREAD

**Issue by jynxy** [wenzhixin/bootstrap-table#5787]
Hi,

When using custom view with search, if no matches are found it doesn't show anything, as per your online example.

https://examples.bootstrap-table.com/#extensions/custom-view.html

how do i show no matches found ?

**Comment by jynxy** [comment]
any fix for this ? thanks

**Comment by UtechtDustin** [comment]
I checked that issue again and this is not a bug.
As the extension is already called "CUSTOM View", you can and have to implement the view your self.
That also includes the "No record found" message.

It's quite easy to implement, within your custom view formatter you check the length of the data.
Is the length equals to 0 return your html which contains the "no record found" message.

Example: https://live.bootstrap-table.com/code/UtechtDustin/8410
