### ISSUE TITLE
client side Pagination and server side Searching

### ISSUE THREAD

**Issue by kwsz** [wenzhixin/bootstrap-table#5788]
**Description** 
As far as I know, _data-side-pagination=server_ do the pagination and searching on the server side, is there any way to do the client side pagination and server side searching?

I've tried a way that

1. don't set _data-side-pagination_
2. use event handler to handle the search action and then reload the table

it works well on data-search but wrong on data-filter-control
- in the first time loading, it sends get request multiple times rather than once.
- when searching on the column, params.data shown in the alert popup is wrong - looks like previous search inputs.

Thanks in advance.

**Example**  
[data-search](https://live.bootstrap-table.com/code/kwsz/8201)
[data-filter-control](https://live.bootstrap-table.com/code/kwsz/8200)

**Comment by djhvscf** [comment]
I was reviewing this issue but  to be honest the examples are not very clear.. Please provide new ones.
