### ISSUE TITLE
Custom View can not set Default view as Grid

### ISSUE THREAD

**Issue by jinbatsu** [wenzhixin/bootstrap-table#5789]
**Description**  
Custom View Extention
Can not set grid as default view.
If I set to false, button is disapear.

From the documentation:
```
showCustomView
    Attribute: data-show-custom-view
    Type: Boolean
    Detail: Set to true to show the custom view as default view.
    Default: false
```

**Example (optional)**  
Here is live example:
https://live.bootstrap-table.com/code/jinbatsu/8210

**Comment by jinbatsu** [comment]
OK, I did it with firing toggleCustomView.
showCustomView is still the default true.
Here is the code sample:
```
// fire toggleCustomView
$table.bootstrapTable('toggleCustomView')
```
And here is the Live Code sample:
https://live.bootstrap-table.com/code/jinbatsu/8217

**Comment by djhvscf** [comment]
I think it is working as designed

**Comment by jinbatsu** [comment]
Yes, I missunderstand about default view as Grid or Custome View.
So, to make it default as Grid, we should manually trigger `$table.bootstrapTable('toggleCustomView')`

I will close this issue.
