### ISSUE TITLE
Rowspan,colspan and image in cell

### ISSUE THREAD

**Issue by jbperrin88** [wenzhixin/bootstrap-table#579]
Hello ,

First of all , I need to tell you all thank.

Your work is amazing ! 

I'm creating my own web site to control my xbmc system and some other thinks .

I'm using bootstrap and at the beginning , i use javascript to dynamically load content to tables.

At least , it was working well , but with Bootstrap table is much more easy and have a lot of functionalities !

This was my working site before using bootstrap table :

![capture](https://cloud.githubusercontent.com/assets/11284940/6455809/8d54c2d2-c159-11e4-8cba-d4cf01b8c1fe.PNG)

I want to have the same look but with bootstrap table and now i got this :
![capture2](https://cloud.githubusercontent.com/assets/11284940/6455836/e3785566-c159-11e4-9530-6a0c19be9ad9.PNG)

So i wonder if it's possible to use some rowspan and colspan?

And also can'I use the content of a cell to display a picture ?

Thanks a lot and have a nice day !

**Comment by wenzhixin** [comment]
Hi, I think you can try to use `formatter` function and set `showHeader` option to false to display your table.

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#579.html

**Comment by CarsonSlovoka** [comment]
> http://issues.wenzhixin.net.cn/bootstrap-table/#issues/579.html

link is not working
