### ISSUE TITLE
If using select element in the table data, selected options in select element is lost after appending a row

### ISSUE THREAD

**Issue by lmetkar** [wenzhixin/bootstrap-table#5790]
Versions: v1.18.0
Description: 

There is one Select HTML element in each row.
If I add a new row to the Bootstrap-Table using $table.bootstrapTable('append', rows);
Then the option from the select is lost.

Example:
https://live.bootstrap-table.com/code/lmetkar/8233

whenever I append a row using the append method the Selected options in various select are lost.

**Comment by djhvscf** [comment]
Yes, that is because every time a row is appended the whole table is re-rendered. Let's say it is working as designed but it is not a good design

**Comment by wenzhixin** [comment]
ref #987 
https://examples.bootstrap-table.com/#issues/987.html

You need to save the row data after changed.
