### ISSUE TITLE
Custom Advanced Search

### ISSUE THREAD

**Issue by damirqa** [wenzhixin/bootstrap-table#5792]
Hi! How can I create a custom advanced search? For example, I need to use three fields instead of ten and two checkboxes. I thought to create a form in advance and only then hang an event on it, but I do not know how. Can I have an example?

**Comment by djhvscf** [comment]
See this example: https://examples.bootstrap-table.com/index.html#extensions/toolbar.html

**Comment by UtechtDustin** [comment]
@djhvscf he want's to use a custom advanced search i guess.
You can use your custom form/inputs with the [filterBy](https://bootstrap-table.com/docs/api/methods/#filterby) method in the custom mode i guess.

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by damirqa** [comment]
No

**Comment by wenzhixin** [comment]
Can you provide an [Online Example](https://live.bootstrap-table.com) to show your problem?

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we got no example from you.
Please let us know if you still ne help.

**Comment by s72817** [comment]
How can I disable columns for advanced search? (maybe its what he asked?!)
I dont want to see all columns e.g. actions column with buttons and so on makes no sense to have it in advanced search list. Also I have a picture column, makes also no sense, to have this column in advanced search.

Thanks for help :)
Richard
