### ISSUE TITLE
insertRow after changing table sort order

### ISSUE THREAD

**Issue by Polm90** [wenzhixin/bootstrap-table#5793]
I'm using bootstrap-table version 1.18.3.

I'm trying to insert a row in the table after that the user has changed the sort order.

I expect that the table would keep the current sorting. But, instead, the table restores its sorting order to the default one (in both scenarios when I do not specify a starting sort order and when I specify a starting sort order for the table).

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by Polm90** [comment]
Sorry, I've found it was my mistake :(
