### ISSUE TITLE
Bootstrap table - Custom View Extension not loading in template view

### ISSUE THREAD

**Issue by mageshapr** [wenzhixin/bootstrap-table#5794]
While using bootstrap table came across Custom View extension and tried to implement the same in my project. I'm using Spring boot with Thymeleaf in my project. Included bootstrap, Jquery and bootstrap-table libraries to my project. 

https://examples.bootstrap-table.com/index.html?bootstrap5#extensions/custom-view.html#view-source

Followed exactly the same way defined in above url example. However my UI didnt load the template view rather it just loaded the bootstrap table default view. What am I missing. Any help to understand this example is much appreciated!

**Comment by wenzhixin** [comment]
Have you included the `custom-view` extension? 
And enable the custom view option:
```html
  data-show-custom-view="true"
  data-custom-view="customViewFormatter"
  data-show-custom-view-button="true"
```

**Comment by wenzhixin** [comment]
Hi! There is not any reply, in that case, we are going to close this PR. Remember to add an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!
