### ISSUE TITLE
Table pagination on `v1.18.3`

### ISSUE THREAD

**Issue by b5414** [wenzhixin/bootstrap-table#5795]
**Bootstraptable version(s) affected**:

`version v1.18.3` with bug
`version v1.18.2` is good

**Description**  

I just updated the library to a new version and ran into the problem

Table with only two lines has the page selector(pagination dropdown button) active/showed, when I clicked on it, an error appears in the console

https://imgur.com/ygljZyx

**Example**  

```javascript
$('#bstable').bootstrapTable({
	columns: [...],
	virtualScroll: false,
	smartDisplay: true,
	pagination: true,
	data: data,
	scrollX: false,
	scrollY: false,
	scrollCollapse: false,
	pageList: [100, 200, 300, 400, 500, 'All'],
	pageSize: size,
	sortName: 'addedUnix',
	sortOrder: 'desc',
});
```

**Possible  (optional)**  

**Additional context**  

I am creating a table dynamically and using the `bootstrap-table.min.js` file

Also with bootstrap 441 I had another issue, but I have update all libs to latest, so bootstrap now is 460

**Comment by wenzhixin** [comment]
I cannot open the URL: https://imgur.com/ygljZyx.
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I created a [example](https://live.bootstrap-table.com/code/UtechtDustin/8320) using your options and i can't reproduce the issue you described. As @wenzhixin said, please provide us an example.

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we got no response/example from you. If you still need help please provide us an example using our [Online Editor](https://live.bootstrap-table.com/).

**Comment by b5414** [comment]
@UtechtDustin hello, sorry for the delay 🙂

I don't want to log into your service, please, just copy&paste the following code:

```html
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<div id="bstable"></div>
<script>
    (async()=>{
        await new Promise((done)=>setTimeout(done, 100));
        $('#bstable').bootstrapTable({
            columns: [{sortable: true, align: 'left', field: 'name', title: 'AName'}],
            virtualScroll: false,
            smartDisplay: true,
            pagination: true,
            data: [{name: 'Lord'}, {name: 'NotLord'}],
            scrollX: false,
            scrollY: false,
            scrollCollapse: false,
            pageList: [100, 200, 300, 400, 500, 'All'],
            pageSize: 100,
            sortName: 'addedUnix',
            sortOrder: 'desc',
        });
    })();
</script>
```

ps. the problem is still relevant with version 3, and not with v2

**Comment by b5414** [comment]
@wenzhixin

**Comment by b5414** [comment]
@wenzhixin there is the double `smartDisplay`

`smartDisplay: true` is working with < 1183, not with 1183

---

1. https://live.bootstrap-table.com/example/options/smart-display.html
2. Change `data1.json` to `data3.json`
3. Test it with 1183 and 1182

https://imgur.com/EzwDhWY
