### ISSUE TITLE
Refresh button should empty the data-search and data-filter-control before making request

### ISSUE THREAD

**Issue by rahulpattanshetty** [wenzhixin/bootstrap-table#5797]
**Description**  
I have added data-show-refresh in my bootstrap-table along with data-search and data-filter-control. When i used search box or filter-control to filter the data so here when i press the refresh button is it possible to empty the search text and filter-control data and then make request to server because here it is sending the search text or filter-control keys to the server.

Steps:-
1) type a text in search box and filter-control
2) Press a refresh button ( need to reset the search and filter-control to empty state) 

**Example (optional)**  
https://live.bootstrap-table.com/code/rahulpattanshetty/8310

**Comment by UtechtDustin** [comment]
I'm not quite sure what do you mean, the provided example works fine for me.
If i seach for something (in the normal search and in the filter control search) and then press on refresh the table will be refreshed but no search will be cleared.
Also the request to the server looks good, could you please explain that more detailed ?

**Comment by rahulpattanshetty** [comment]
@UtechtDustin Is it possible to clear the search box and filter-control box and then make the request to the server when refresh button is pressed

**Comment by rahulpattanshetty** [comment]
@UtechtDustin When i pressed refresh button i need to clear search box and filter-control box and then it should make request to the server. Is it possible to customize the refresh functionality.

**Comment by wenzhixin** [comment]
I think the Search Clear Button can solve the problem: https://examples.bootstrap-table.com/index.html#options/show-search-clear-button.html

**Comment by UtechtDustin** [comment]
As @wenzhixin already said the `showSearchClearButton` option should solve the issue.
Please let us know if you still need help!
