### ISSUE TITLE
mergeCells cannot be correctly displayed

### ISSUE THREAD

**Issue by Darksky1991** [wenzhixin/bootstrap-table#5798]
when two left merged cells has same value at right cells, after searching left cells only display top merged cells' value.
eg.
col1|col2
----|----
c1v1|c2v1
-|c2v2
c1v2|c2v2
-|c2v3

after search c2v2, it shows as below.
col1|col2
----|----
c1v1|c2v2
-|c2v2

but c1v2 at the left of second row is expected. 
which looks like:
col1|col2
----|----
c1v1|c2v2
c1v2|c2v2

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by Darksky1991** [comment]
Hi, thanks for your replay.
I have saved an example named '5798. mergeCells cannot be correctly displayed'.
And I suddenly realized that this is not a bug.
I should recalculate rowspan and colspan after refresh event triggered.(such as pagechange search and so on)
Is there any way we can auto recalculate rowspan and colspan and merge correctly after refresh when full data's rowspan and colspan has been setted?
Or we can add an auto same value merge API.

**Comment by wenzhixin** [comment]
The FAQ: https://bootstrap-table.com/docs/faq/#how-to-better-merge-cells mybe help.

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we got no response from you.
If you still need help, please let us know!
