### ISSUE TITLE
 The vertical border of thead and tbody out of position problem

### ISSUE THREAD

**Issue by sunhk25** [wenzhixin/bootstrap-table#5799]
**Description**  
table using rowspan colspan and set data-height attribute,
(resize window) the vertical border of thead and tbody out of position problem.
Is there some solution to fix this? thanks

**Example (optional)**  
Live demo https://live.bootstrap-table.com/code/sunhk25/8316

**Comment by djhvscf** [comment]
See this: https://live.bootstrap-table.com/code/djhvscf/8381

**Comment by wenzhixin** [comment]
> This field must be unique, or some unknown problems may occur.
https://bootstrap-table.com/docs/api/column-options/#field

You need to remove the `field` column option and update the `NO` field to be unique.
Working example: https://live.bootstrap-table.com/code/sunhk25/8316

**Comment by sunhk25** [comment]
@djhvscf @wenzhixin 
Thanks, it works!
