### ISSUE TITLE
How to use this bootstrap table with jade

### ISSUE THREAD

**Issue by samsfisher** [wenzhixin/bootstrap-table#580]
Hi

I m passing the data.json to a jade template. While i am able to access the json in jade the table is  no matching queries found.

- i can see the JSON data under the table header in data-uri as well as data. 
- How can I use this with JADE?

**Comment by wenzhixin** [comment]
Maybe you can render a normal table and then transform it: http://bootstrap-table.wenzhixin.net.cn/examples/#table-from-html.

ref: #375
