### ISSUE TITLE
Custom Locations of content

### ISSUE THREAD

**Issue by jynxy** [wenzhixin/bootstrap-table#5805]
Hi,

I previously used jplist and was a great plugin, but no longer made, this plugin looks just as good if not better, the downside is you cannot customise where you want content to be. i.e pagination. sort buttons etc. on jplist i had the following.

Can you look at jplist and see if you can incorporate similar custom features. this would make this the ultimate plugin.

https://github.com/1rosehip/jplist-es6

Thanks

`<div class="card card-fluid">
<div class="card-header rem-1">
<div class="row">
<nav data-jplist-control="pagination" data-group="group1" data-items-per-page="20" data-current-page="0" data-disabled-class="disabled" data-selected-class="active" data-jump="top" data-name="pagination1" class="float-left mb-0 mr-0" style="width:100%;">
<div class="col-12 mb-3">
<div class="dropdown d-inline-flex">

<?php echo $data['reset']; ?> // Shows reset button here clears serach, sortby etc.

</div>
<div class="dropdown d-inline-flex" data-type="items-per-page-dd" data-opened-class="show">

// add a button to show how many items per page (overrides Dropdown Button text)
<button	data-type="panel" class="btn btn-primary dropdown-toggle" type="button">Dropdown button</button>
<div data-type="content" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
<a class="dropdown-item" href="#" data-value="20">20 per page</a>
<a class="dropdown-item" href="#" data-value="40">40 per page</a>
<a class="dropdown-item" href="#" data-value="60">60 per page</a>
<a class="dropdown-item" href="#" data-value="0">View All</a>
</div>

</div>
<div class="dropdown d-inline-flex" data-jplist-control="dropdown-sort" data-opened-class="show" data-group="group1" data-name="sort1">

// another button allows you to sort data using the class attribute with data-xxx, for example name would be
// <div class="col"><b>Colleague Name: </b><span class="data-name"><?php echo $csp->colleague_name;?></span></div>
// notice the data-name

<button data-type="panel" class="btn btn-primary dropdown-toggle" type="button">Sort by</button>
<div data-type="content" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
<?php echo $data['sortby']; ?>
<a class="dropdown-item" href="#" data-path=".data-name">Default</a>
<a class="dropdown-item" href="#" data-path=".data-name" data-order="asc" data-type="text">Name A-Z</a>
<a class="dropdown-item" href="#" data-path=".data-name" data-order="desc" data-type="text">Name Z-A</a>
</div>

</div>
</div>
</nav>
<div class="col-md-4 float-left">
<div class="input-group" style="margin-bottom: 5px;">

// search bar
// again using the class attribute to determine what it allowed to be searched, which is great when using custom view.
<input data-jplist-control="textbox-filter" data-group="group1" data-name="my-filter-2" data-path=".data-start, .data-name, .data-end" type="text" value="" placeholder="Search..." data-clear-btn-id="author-clear-btn" class="form-control" />

<div class="input-group-append">

// clear search
<button class="btn btn-outline-secondary" type="button" id="author-clear-btn">Clear</button>

</div>
</div>
</div>
<div class="col-md-8 text-right">

// create custom pagination location anywhere on the page.
// allows you customise text and content easily using a smarty type template.

<nav data-jplist-control="pagination" data-group="group1" data-items-per-page="20" data-current-page="0" data-disabled-class="disabled" data-selected-class="active" data-jump="top" data-name="pagination1" class="mb-0" style="margin-top:2px;">
<ul class="pagination d-inline-flex mb-0">
<li class="page-item d-none d-sm-none d-lg-inline-block" data-type="first"><a class="page-link" href="#"><i class="far fa-chevron-double-left"></i></a></li>
<li class="page-item" data-type="prev"><a class="page-link" href="#"><i class="far fa-chevron-left"></i></a></li>
</ul>
<ul class="pagination d-none d-sm-none d-lg-inline-flex mb-0" data-type="pages">
<li class="page-item" data-type="page"><a class="page-link" href="#">{pageNumber}</a></li>
</ul>
<ul class="pagination d-inline-flex mb-0">
<li class="page-item" data-type="next"><a class="page-link" href="#"><i class="far fa-chevron-right"></i></a></li>
<li class="page-item d-none d-sm-none d-lg-inline-block" data-type="last"><a class="page-link" href="#"><i class="far fa-chevron-double-right"></i></a></li>
</ul>
<span data-type="info" class="d-none d-sm-none d-md-inline-flex badge badge-secondary ml-3 p-2" style="vertical-align:top;">
Showing {startItem} to {endItem} of {itemsNumber} entries
</span>
</nav>

</div>
</div>
</div>`

**Comment by wenzhixin** [comment]
Sorry, I don't know what you want.

**Comment by jynxy** [comment]
i would like to be able to put button in custom locations on the page not fixed as they currently are, the same also with pagination there is no way to change its location without a bunch of JS overrides.

look at how customisable jplist is https://github.com/1rosehip/jplist-es6/blob/master/build/site/templates/examples/cars.html

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) with jplist-es6 to show your problem, thanks!

**Comment by jynxy** [comment]
i need a way to display pagination and the buttons outside of the container for bs-table, i cannot create a live example, as i cant move the buttons or pagination outside of the container.

for example this code for jplist i can put anywhere i want on the page.

<nav
                                data-jplist-control="pagination"
                                data-group="group1"
                                data-items-per-page="3"
                                data-current-page="0"
                                data-disabled-class="disabled"
                                data-selected-class="active"
                                data-jump="top"
                                data-name="pagination1"
                                class="mb-2 mb-lg-0">

                            
                            <ul class="pagination d-inline-flex">
                                <li class="page-item d-none d-sm-none d-lg-inline-block" data-type="first"><a class="page-link" href="#">«</a></li>
                                <li class="page-item" data-type="prev"><a class="page-link" href="#">‹</a></li>
                            </ul>

                            
                            <ul class="pagination d-none d-sm-none d-lg-inline-flex" data-type="pages">
                                <li class="page-item" data-type="page"><a class="page-link" href="#">{pageNumber}</a></li>
                            </ul>

                            
                            <ul class="pagination d-inline-flex">
                                <li class="page-item" data-type="next"><a class="page-link" href="#">›</a></li>
                                <li class="page-item d-none d-sm-none d-lg-inline-block" data-type="last"><a class="page-link" href="#">»</a></li>
                            </ul>

                            
                            <span data-type="info" class="d-none d-sm-none d-lg-inline-flex badge badge-secondary ml-3 p-2">
                                {startItem} - {endItem} of {itemsNumber}
                            </span>

                            
                            <div class="dropdown d-inline-flex ml-3"
                                 data-type="items-per-page-dd"
                                 data-opened-class="show">

                                <button
                                        data-type="panel"
                                        class="btn btn-primary dropdown-toggle"
                                        type="button">Items per page</button>

                                <div
                                        data-type="content"
                                        class="dropdown-menu"
                                        aria-labelledby="dropdownMenuButton">

                                    <a class="dropdown-item" href="#" data-value="3">3 per page</a>
                                    <a class="dropdown-item" href="#" data-value="6">6 per page</a>
                                    <a class="dropdown-item" href="#" data-value="9">9 per page</a>
                                    <a class="dropdown-item" href="#" data-value="0">View All</a>

                                </div>
                            </div>

                        </nav>

**Comment by wenzhixin** [comment]
Sorry, the plugin currently does not support this feature.
