### ISSUE TITLE
When using data-search-selector it doesn't detect search-text

### ISSUE THREAD

**Issue by eliezra236** [wenzhixin/bootstrap-table#5812]
**Bootstraptable version(s) affected**:
All? tried on 5 and on the live editor.

**Description**  
I am setting up a data-search-selector to use sticky search and search-text just change the value of that input, but doesn't execute the search.

**Example**  
https://live.bootstrap-table.com/code/eliezra236/8439

**Possible  (optional)**  

I made some attempts of changing it way later (trough button that execute:   
```
$("#table").bootstrapTable("refreshOptions", {
    searchText: "testing",
  });
```
And it does the same thing, changes the text in the input but doesn't execute the search.

**Comment by eliezra236** [comment]
A work-around I found is using 

```
$("#table").one("pre-body.bs.table", () => $('#customSearch').trigger("blur"););
```

**Comment by UtechtDustin** [comment]
Works fine for me on Firefox and Chrome, which browser do you use ?

**Comment by eliezra236** [comment]
> Works fine for me on Firefox and Chrome, which browser do you use ?

I am using chrome. What I mean is that it won't execute the first search like in this image
https://imgur.com/a/5NpBRQm

**Comment by UtechtDustin** [comment]
Oh okay, you mean the initial search (`data-search-text="item 2"`) dont work ?
I can reproduce that, do you also have issues while searching a other value manually ?

**Comment by eliezra236** [comment]
> Oh okay, you mean the initial search (`data-search-text="item 2"`) dont work ?
> I can reproduce that, do you also have issues while searching a other value manually ?

By manually you mean to change the value inside the text field manually? that works.
If you mean to change the data-search-text with something like refreshOption then no it still doesn't work.

The bug is that changing search-text won't affect the search-selector, not initially when first loaded and not when changed using refreshOption
