### ISSUE TITLE
Column FilterData function example

### ISSUE THREAD

**Issue by matheusilario** [wenzhixin/bootstrap-table#5813]
I'm using the data-filter-data attribute to customize the select filter values of a column through a function but the select values don't work.

I would like an example to use the function on this attribute.

**data-filter-data=func:functionName**

**Comment by UtechtDustin** [comment]
It's quite simple, the function just return a object with key (will be searched) and a name (will be shown in the select).
Example: https://live.bootstrap-table.com/code/UtechtDustin/8441

**Comment by matheusilario** [comment]
Thanks for the feedback.

I checked your example and it worked. But when I try to return the data from the function the select is empty.

My code:

```
function selectFilter(){
     let data = $("#table").bootstrapTable('getData');

     let filters= {};
     $.each(data, function(key, value){
         Object.assign(filters, {[value.value]: value.title});
     });

     return filters;
}

```

Object returned: {1102: "1102", 1403: "1403", 1556: "1556", 1910: "1910", 1949: "1949"}

**Comment by djhvscf** [comment]
That is because that example uses the server side.. If you use the data in the client side that works as expected: https://live.bootstrap-table.com/code/djhvscf/8445

**Comment by matheusilario** [comment]
I tried that way and it still doesn't work.

![Sem-Título-1](https://user-images.githubusercontent.com/4631228/127648366-f66d4eb9-34ae-4a3a-af14-97e8789998fc.jpg)

**Comment by UtechtDustin** [comment]
Okay, then please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by matheusilario** [comment]
Follow an example https://live.bootstrap-table.com/code/matheusilario/8504

**Comment by UtechtDustin** [comment]
It seems the error occurs while using the `load` method.

Minimal examples: 
Not working: https://live.bootstrap-table.com/code/UtechtDustin/8508
Working: https://live.bootstrap-table.com/code/UtechtDustin/8507

**Comment by UtechtDustin** [comment]
@matheusilario 
As workaround you can load the data using the `data` option instead of the `load` method.

**Comment by matheusilario** [comment]
thanks, i will test it
