### ISSUE TITLE
Copy Rows without html code

### ISSUE THREAD

**Issue by levyaugustoriosaude** [wenzhixin/bootstrap-table#5815]
The Copy-Rows extension brings all the value of the cell even if it is an html code, for example when I create a column for the operations using `OperateFormatter`, the html code is copied to the clipboard. 
**Here is an example**
[Example1](https://live.bootstrap-table.com/code/levyaugustoriosaude/8460)

There had to be an option that excludes a column from being copied. Looking at other extensions like **export** or **print,** it has the functions `data-print-ignore="true"` or `data-force-hide="true"`. Is there a similar option for copy-rows?
Could you have a new function `copy-ignore = “false”` as default value, to make this function?

In my attempts to avoid this I realized that using colspan and rowspan, copy rows only takes the column that is doing the rowspan, however it only behaves like this if it has at least two columns inside the colspan, as in the example below:
[Example2](https://live.bootstrap-table.com/code/levyaugustoriosaude/8459)

And in case there is a `<a href=” ”>` tag in the cell and it is not a column of operations, I could use the `text()` functionality, so as not to copy the html code and just get the text

**Comment by UtechtDustin** [comment]
Thanks for the quite good issue description.
But sadly there is no option yet, but i agree we should a option like that!
