### ISSUE TITLE
Submit id of iterator element using html source

### ISSUE THREAD

**Issue by hanspoo** [wenzhixin/bootstrap-table#582]
Hi, thanks for your work, it's great, 

I'm using the table building it from html with the checkbox funcionality, not json, and need the store the id of the Package (may be any thing, the element i'm iterating) in every row, the idea is to capture it with getSelections, or with jQuery directly before submit, but can't find the way, i've manually added data-package-id to tr's and td's, but they disappeared, i guess you are building the whole html again. 

Thank you,
Hans Poo

**Comment by djhvscf** [comment]
Do you have some code? or JSFiddle example?? (you can use the templates http://bootstrap-table.wenzhixin.net.cn/examples/#basic) @hanspoo

**Comment by hanspoo** [comment]
Hello thanks for answering, our consultation is specifically about chekbox usage to mark rows.
We usually place the identifier of the item id we are iterating over, as the value attribute on the checkbox field, in general our html code is something like this :

<table>
	<thead>
		<tr>
			<th><input type="checkbox" id="toggleAll" /></th>
			<th># Sale Number</th>
			<th>...</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><input value="19547" name="ids" /></td>
			<td>...</td>
		</tr>
		<tr>
			<td><input value="20000" name="ids" /></td>
			<td>..</td>
		</tr>
	</tbody>
</table>>

You see, the id number, or sale number identifier, is placed as the value atribute of the form field in this case named ids, so when you submit the form, ids arrive ready for processing at the server side as a collection of Longs (we are actually using Java Play Framework).

By the way we have found a wortk around with bootstrap table, placing the identifier as a hidden column that can be recovered processed using the GetSelections() in any jquery handler, here is an example implementing a custom delete button with the id as second column of the table:


		$("#delete-button").click(function() {
			var data = $("table").bootstrapTable('getSelections');
			var ids = $.map(data, function (item) {
			    return item[1];
			});
			$.post("/deleteSelected", { ids: ids.join(",") }, function() {
				location.reload();	
			})
			
			return false;
		});

**Comment by djhvscf** [comment]
Can you share us your table bootstrap configuration, please? @hanspoo

**Comment by hanspoo** [comment]
Hi,

I've created a fiddle, is our current solution using the hidden column workaround, http://jsfiddle.net/drnjL5fb/1/
I didn't find a way to make without the hidden column to store the id, and the jquery handler in case of submission... The first thing i tried was adding data attributes to the row (tr), but they get lost.

**Comment by djhvscf** [comment]
Ok, I already test your fiddle.. but you don't want to use the id in the table?? Rigth? @hanspoo

**Comment by hanspoo** [comment]
¿ How can i do that ? i just want to submit selected elements ids to the server for processing, if there is a better (or normal) way than using a hidden column and a jquery handler, it would be great.

**Comment by djhvscf** [comment]
Something like this?? http://jsfiddle.net/x3c9wbc9/ @hanspoo

**Comment by hanspoo** [comment]
I appreciate your example, but it's json based and requires an  jquery callback to work, it seems that with html source the only solution is the hidden column, it's really strange that nobody has request a solution that sets the value attribute on the checkbox of each row with the id of the iterated element, this will simplify things a lot, i think it's a common pattern.

**Comment by wenzhixin** [comment]
Hi, please use the hidden column workaround.
