### ISSUE TITLE
maintainMetaData + FilterControl + AJAX bug

### ISSUE THREAD

**Issue by wpicinato** [wenzhixin/bootstrap-table#5820]
**Bootstraptable version(s) affected**:
1.18.3
 
**Description** 
When table is loaded by AJAX, FilterControl and MaintainMetaData are set, the method check first row from AJAX, even if we didn't do it.
Problem appears when we select Filter table data and check a row.
 
**Example** 
https://live.bootstrap-table.com/code/wpicinato/8534

**Additional context** 
This bug does not appear when the table is loaded from the data option (https://live.bootstrap-table.com/code/wpicinato/8535), also when the FilterControl is unset (https://live.bootstrap-table.com/code/wpicinato/8536).

![](https://media.giphy.com/media/WXD4mbDnq7RIcH4ym2/giphy.gif)

**Comment by wpicinato** [comment]
https://github.com/wpicinato/home/blob/main/Gravação-de-Tela-2021-08-04-às-10.38.59.gif

**Comment by djhvscf** [comment]
This is fixed here: https://github.com/wenzhixin/bootstrap-table/pull/5583

Example with the fix: https://live.bootstrap-table.com/code/djhvscf/9720
