### ISSUE TITLE
Multi sort modal wasn't reloaded after a new bootstrap table created.

### ISSUE THREAD

**Issue by Agnes12180** [wenzhixin/bootstrap-table#5822]
I need to create bootstrap tables dynamically with multi sort options, and I used  $('#table').bootstrapTable('destroy') before I created a new table, but columns in the multi sort modal were not updated, it shows columns of the previous table which has been destroyed. It seems the multi-sort modal didn't be destroyed and recreated successfully. Do u have any good suggestions about that? Thx in advance.
the multi sort modal is from /extensions/multiple-sort/bootstrap-table-multiple-sort.js

**Comment by wenzhixin** [comment]
Fixed in #4811
