### ISSUE TITLE
Can I use CDN to reduce loading time? (1000+ table)

### ISSUE THREAD

**Issue by eliezra236** [wenzhixin/bootstrap-table#5824]
Hi,
I am using bootstrap-table on my website to manage a pretty big table of about 1000+ entries with images, and the initial loading take pretty long time.

Can I use CDN or load it in the backend to reduce the initial load time?

**Comment by djhvscf** [comment]
You can use this CDN: https://unpkg.com/browse/bootstrap-table@1.18.3/dist/

**Comment by UtechtDustin** [comment]
@djhvscf i guess you missunderstood the question (or maybe me ?)

@eliezra236 for that large amount of data you should load the data from the server, instead of using static html or a object.
That means you should use the server side functions as example `sidePagination: 'server'` (https://bootstrap-table.com/docs/api/table-options/#sidepagination).
The table will ask the server for e.g. 10 entries for the current page instead of the 1000+ entries.

**Comment by eliezra236** [comment]
> @djhvscf i guess you missunderstood the question (or maybe me ?)
> 
> @eliezra236 for that large amount of data you should load the data from the server, instead of using static html or a object.
> That means you should use the server side functions as example `sidePagination: 'server'` (https://bootstrap-table.com/docs/api/table-options/#sidepagination).
> The table will ask the server for e.g. 10 entries for the current page instead of the 1000+ entries.

Hi, thank you for the reply, I think @djhvscf missed the point here; I got a CDN service (using CloudFlare) but the problem is that the CDN loads the HTML, and the bootstrap-table modification is done using JS after the page loads, so it slows the loading time.

Your solution of using pages can work, but I prefer to load them all into one page as I find it as a better user experience because he can also use CTRL + F (altrough I did implement sticky search), and easier to browse, especially since I am using custom view.

**Comment by UtechtDustin** [comment]
Okay, then the last option would be virtual-scroll i guess.
Example: https://live.bootstrap-table.com/code/UtechtDustin/8603

But i'm not sure if all extension are compatible with virutal scroll. (especially the custom view extension)
For a large amount of entries, we always prefere the server side pagination.

**Comment by eliezra236** [comment]
> Okay, then the last option would be virtual-scroll i guess.
> Example: https://live.bootstrap-table.com/code/UtechtDustin/8603
> 
> But i'm not sure if all extension are compatible with virutal scroll. (especially the custom view extension)
> For a large amount of entries, we always prefere the server side pagination.

I am actually not a fan of inner scrolling myself.
I implemented a sticky search (in the hard way), I also made a post here with the code I use (altrough I changed it to something else).
I hope it's ok that I share a link - but here is what I am talking about in my websitte - https://www.gamepasscompare.com/games/AllGames

You can see that the initial scroll takes long time, I thought it's because the large images but as I now expiriment with smaller images on the staging area I realize it's a problem of bootstrap-table loading time.

**Comment by UtechtDustin** [comment]
I'm not sure how we could help you without the server side pagination.
@djhvscf @wenzhixin do you have any ideas ?

**Comment by wenzhixin** [comment]
I think client paging can also help.
