### ISSUE TITLE
The filter-control input is clearing while searching

### ISSUE THREAD

**Issue by matheusilario** [wenzhixin/bootstrap-table#5828]
The filter-control input is clearing while searching and the filter cannot be cleared.

Tried to change table settings but it persists.

![screencast](https://user-images.githubusercontent.com/4631228/129202845-2fb2803d-55ff-49e6-914c-485c6d4adaf6.gif)

An example of my table configuration:

https://live.bootstrap-table.com/code/matheusilario/8621

This example works perfectly. But in the image you can see that in the application no.

**Comment by UtechtDustin** [comment]
Example: https://live.bootstrap-table.com/code/yeezy69/9585

**Comment by djhvscf** [comment]
I think this is because we're removing the controls and then recreating them.. We need to dig deeper on this

**Comment by yeezy69** [comment]
I compared version 1.19.1 with 1.18.3 in browser dev-tools. In version 1.19.1 the whole tablehead will be removed and recreated after a search is performed.

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9721
