### ISSUE TITLE
Compact data format?

### ISSUE THREAD

**Issue by ajck** [wenzhixin/bootstrap-table#5829]
Referring to this closed issue:
[https://github.com/wenzhixin/bootstrap-table/issues/479](https://github.com/wenzhixin/bootstrap-table/issues/479)

[
["bootstrap-table", "526", "122"],
["multiple-select", "288", "150"],
...
]

I tried this compact format and it doesn't seem to work - is it still supported in the code?

Or, is there another way to specify a large data set in the code, but using a compact format so the column names do not need specifying for every item in the table?

I can't use JSON as I'm relying on a server API in a corporate environment that I don't have control over, I'm getting data by AJAX, processing it locally in the browser and then want to supply it to bootstrap-table in a compact form, like the above example or similar.

Thanks.

**Comment by wenzhixin** [comment]
https://live.bootstrap-table.com/code/wenzhixin/8625
