### ISSUE TITLE
How to hide / filter rows?

### ISSUE THREAD

**Issue by vgoklani** [wenzhixin/bootstrap-table#583]
Which method should we use for hiding (or filtering) specific rows?

**Comment by djhvscf** [comment]
Maybe this example works.. http://issues.wenzhixin.net.cn/bootstrap-table/#methods/remove.html if not you tell us! @vgoklani

**Comment by vgoklani** [comment]
I can delete the rows, but if i want to unhide them, i have to rebuild the table. Is there a faster solution?

**Comment by djhvscf** [comment]
Here is the new method for this issue https://github.com/wenzhixin/bootstrap-table/pull/584

**Comment by vgoklani** [comment]
thank you! 

is it possible to reference a row_id (defined by the data) as opposed to the row number. The table is being used in a live data stream, where we are prepending new rows constantly.

**Comment by djhvscf** [comment]
Do you mean use the the row **idField**? @vgoklani

**Comment by djhvscf** [comment]
How are you inserting the new rows?? @vgoklani  like this: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/insertRow.html??

**Comment by vgoklani** [comment]
I prepend new rows, since I want them to be on top. Is that the best approach?

**Comment by djhvscf** [comment]
I think you can do that in the both ways.. @vgoklani

**Comment by vgoklani** [comment]
How do I use the idField parameter? I need to define an absolute reference to a row, which stays constant as I prepend/append rows. I was looking at this example: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/insertRow.html
and the html is referenced by the data-index field, which changes whenever I append a new row. If the index is changing, it's unclear how I should hide/unhide rows.

**Comment by djhvscf** [comment]
@vgoklani this is the PR that contains the change to show/hide row by index or IdField
Ref to: https://github.com/wenzhixin/bootstrap-table/pull/603

**Comment by vgoklani** [comment]
Do you have an example on how to set the idField parameter?

**Comment by djhvscf** [comment]
Sure.. @vgoklani 

```javascript
(function() {
        $('#button').click(function () {
            $('#table').bootstrapTable('showRow',{index: 1, isIdField:  true});
        });
        $('#button2').click(function () {
            $('#table').bootstrapTable('hideRow',{index: 1, isIdField:  true});
        });
})();
```

**Comment by djhvscf** [comment]
it works for you? @vgoklani

**Comment by vgoklani** [comment]
Sorry, It's still not clear. Suppose I have the following:

jsonData = [ {"name":"A", "age":0},
             {"name":"B", "age":1},
             {"name":"C", "age":2}
            ]

$('#table').bootstrapTable({data: jsonData});

1. How do I query the table to find all ages >= 1?
2. How do I then hide all rows >= 1?
3. How do I then show all the hidden rows?

I know you have search & filter boxes that do this, and a filter extension. But how do I do this directly via your bootstrapTable library (API)?

Are you querying the JSON array directly, finding the relevant objects, destroying the old table, and then building a new one each time you run the search query? Or are you hiding the rows (and leaving the table in the dom, and keeping it hidden?). I can obviously do the latter, but it's unclear how to do the former.

Thanks :)

**Comment by djhvscf** [comment]
Search table option: We are searching into the JSON array and filter with the search text and then we build again the body.

Show/Hide row method: We are getting the index or the idField of the row and then we hide it, and we don't build the table again

And for show all the rows hidden we don't have any method to do that.

@vgoklani

**Comment by vgoklani** [comment]
Thanks for the quick response! For the example I gave above: $('#table').bootstrapTable({data: jsonData});, how do you get the index or idField? Is this the same value as the "data-index" value stored in the "tr" tag?

When I prepend a row, it seems that all the "data-index" values change throughout the table. For the prepend operation, are you destroying the table and then rebuilding it, or are you incrementing all the "data-index" values in the "tr" tags? 

Is prepend an expensive operation for 10k rows?

Thanks :+1:

**Comment by djhvscf** [comment]
When you use the idField is when you specified it in your table options if not you have to use the "data-index"... And yes with prepend and append method we are building again the body.. @vgoklani

**Comment by vgoklani** [comment]
Thanks for the reply! 

I've been using idField like this:

$('#table').bootstrapTable({data: jsonData, idField:"name, ...});

but I still see "data-index" displayed in the DOM. Am I doing something wrong?

Rebuilding the entire table-body for each prepend sounds expensive. I've attached the table to a real-time data stream, where each new message gets prepended to the top of the table. Is there a more direct way to prepend the row to the body without destroying all the rows and rebuilding each time?

**Comment by djhvscf** [comment]
The data-index is not optional, it always will be adding in the 'tr' tag... I think you are right with that and I think we have to review some methods in our code. Let me talk with @wenzhixin .. ok?? @vgoklani

**Comment by vgoklani** [comment]
Thank You!

Quick question, I don't see the idField in the "tr" element, am I initializing it correctly?

Thanks again for everything!

btw, infinite scroll is on my wish-list too :)

**Comment by djhvscf** [comment]
ok, for add the idField you have to use this in:

```html
<th data-checkbox="true"></th>
```

and the table option:

```html
data-id-field="YOUR_ID"
```

**Comment by djhvscf** [comment]
And your infinte scroll will be an excelent feature! :+1:

**Comment by wenzhixin** [comment]
Hi @vgoklani , I think in your case you can handle the data first and then use `load` method instead of rebuild the table, for example: http://jsfiddle.net/e3nk137y/1010/.

**Comment by vgoklani** [comment]
Thanks - I'm using load, and your example is very insightful.

**Comment by vgoklani** [comment]
Is it possible for the prepend operation to simply create a new row, as opposed to rebuilding the entire table? I am using the table in a real-time data stream, so I am constantly prepending rows to the top, and I have to reset all my event listeners at every update too (since you're destroying the DOM).

What would be the simplest way for me to manually create a row and place it on top of the table (and simultaneously utilize my column formatters)?

**Comment by achaffman** [comment]
I can't seem to hide/show rows using the ID field.  What am I doing wrong?  Here is an example of what I am doing:

```
$("#myButton").click(function (e) {
  var badges = $("#tblBadges").bootstrapTable('getSelections');
   $.each(badges, function (k, v) {
     $("#tblBadges").bootstrapTable('hideRow', { index: v.id, isIdField: true });
    });
});
```

if i reference by the row number and set isIdField to false/or omit it, that works as expected, however   the getSelections method doesn't return the the row numbers.

**Comment by iTouchTheSky** [comment]
@achaffman Same thing here for me, I was trying to find out why, well it's seems like there's a bug.
@wenzhixin Can you check that out ?

**Comment by djhvscf** [comment]
Can you provide a fiddle please?

**Comment by iTouchTheSky** [comment]
@djhvscf  https://jsfiddle.net/w50myezm/

**Comment by iTouchTheSky** [comment]
Note that in the fiddle, the idField is not reflected on the TR element.
In my personal code, I do have a checkbox and the idField goes to the value of that checkbox, but still no luck for the hideRow function with idField.

**Comment by djhvscf** [comment]
Hmm.. I think we have to improve that function.. let me try

**Comment by achaffman** [comment]
i tried with the idField defined, a column called "id", both hidden and visible - didn't work in either case.  As @iTouchTheSky said, it does show up as a value for the checkbox input in the column bs-checkbox.

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/760 you have to set the data-unique-id table option to show/hide a row by id

**Comment by wenzhixin** [comment]
Merged #761

**Comment by Sicky** [comment]
Based on this example https://github.com/wenzhixin/bootstrap-table-examples/blob/master/methods/showRow-hideRow.html I think this is way easier:
$button2.click(function () {
	var data = $table.bootstrapTable('getData');
	for (i = 0; i < data.length; i++) {
		if (typeof data[i].mapping !== 'undefined') $table.bootstrapTable('hideRow', {index: i});
	}
});
I used this to hide rows where a specific column (mapping) may or may not has a value. But this method can be easily applied to those age things as well.

**Comment by jaydeepgiri** [comment]
I am performing some delete operation via ajax after the successful delete operation instead of refreshing the whole page i just want to remove the row. to do this i am coding like this but it is not working : 

`
$(document).on('click','.delete',function(){
		var bt = $(this).closest('table').attr('id'); //table id
		var no=$(this).data("no");//to get row number when we remove it
		$.ajax({
			type:'POST',
			url:'delete-operation.php',
			data:dataString,
			cache:false,
			success:function(data){
				if(data){
					$('#'+bt).bootstrapTable('remove', {field: 'no', values: no});
					alert('data : '+data);
				}else
					alert('Oops! Something went wrong');
			}
		});
	});
`

please show me the right way.. and let me know why it is not working..

**Comment by wenzhixin** [comment]
hi @jaydeepgiri 
```
$('#'+bt).bootstrapTable('remove', {field: 'no', values: no}); // is no an array?
```

**Comment by jaydeepgiri** [comment]
No its not an array.. 
Its just a javascript variable, declared as 
```javascript
var no=$(this).data("no");
```

**Comment by wenzhixin** [comment]
> Remove data from table, the params contains two properties: 
field: the field name of remove rows. 
values: the array of values for rows which should be removed.

**Comment by jaydeepgiri** [comment]
Let me show you the table struture

```
<table class='table-striped' id="table-pagination" data-page-list="[15, 25, 50, 100, All]" data-pagination="true" data-search="true" data-show-columns="true">
	<thead>
		<tr>
			<th data-field="no" data-sortable="true">No</th>
			<th data-sortable="true">Name</th>
			<th data-sortable="true">Status</th>
		</tr>
	</thead>
        <tbody>
            <tr>
               <td>1</td>
               <td>item1</td>
               <td>active</td>
            </tr>
            <tr>
                <td>2</td>
                <td>item2</td>
                <td>active</td>
           </tr>
        </tbody>
</table>
```

in the above table what if i want to remove the row where No = 2

how can i achieve that

**Comment by wenzhixin** [comment]
Can you provide a jsfiddle? https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports

**Comment by jaydeepgiri** [comment]
I have tried to make it as simple as possible

check it out here on jsFiddle 
[https://jsfiddle.net/dq7Lustv/8/](url)

**Comment by jaydeepgiri** [comment]
hello or else you try this second one
[jsFiddle 2 ](http://jsfiddle.net/e3nk137y/4836/)

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/e3nk137y/4952/  @jaydeepgiri

**Comment by jaydeepgiri** [comment]
Brother its working but remove is working only one time, second time it does not remove the row.. 
Please check and update..

Thank you for your hard work..

**Comment by jaydeepgiri** [comment]
Thank you so much for your hard work.. its working now.. 
:+1:
