### ISSUE TITLE
Bootstrap-Table v1.18.3 loads Bootstrap 4 constants when Boostrap 5.1.0 is available on Ungoogled Chromium

### ISSUE THREAD

**Issue by TropicalRaisel** [wenzhixin/bootstrap-table#5830]
**Bootstraptable version(s) affected**:

v1.18.3

**Description**  

When loaded alongside the latest Bootstrap 5 release, Bootstrap Table should load with 5-Constants.
However, it loads using 4-Constants.

**Example**  

Run the example, and inspect the table. The theme is set as "boostrap4."

https://live.bootstrap-table.com/code/TropicalRaisel/8628

**Suggestions (optional)**  
Try to find Bootstrap constant variables that reliably change with the Bootstrap release version.

**Comment by UtechtDustin** [comment]
The table has the class `bootstrap5` in your example, which looks corect for me.
Could you share us some more informations ?

**Comment by TropicalRaisel** [comment]
@UtechtDustin Apparently on Ungoogled Chromium it comes out as `bootstrap4`, and on Firefox it's `bootstrap5`. UC is what I use to test web apps, and this is the first time something weird like this has happened.

**Comment by UtechtDustin** [comment]
Which chromium version do you use ?
I tested it with `Version 92.0.4515.131` and it also has the `bootstrap5` class.

**Comment by TropicalRaisel** [comment]
Well after re-running the example it works. In my main project I'm using webpack, and guess things are getting loaded in the wrong order somehow. That's on my end then.

**Comment by UtechtDustin** [comment]
Thanks for sharing the issue cause :-)
