### ISSUE TITLE
Custom ID field (no integer)

### ISSUE THREAD

**Issue by enriquepiatti** [wenzhixin/bootstrap-table#5832]
I have a table with names, and I want to use the names as ID, is that possible?    
I've tried this:
```
<table
        id="table"
        data-toggle="table"
        data-sort-class="table-active"
        data-sortable="true"
        data-id-field="name"
        >
    <thead>
        <tr>
            <th data-field="name" data-sortable="true">NAME</th>
       ...
```
But this this is not working:   

`$table.bootstrapTable('updateCellByUniqueId', {name: 'someName', field: 'anotherColumn', value: newValue})`

and this does not find anything:

`$table.bootstrapTable('getRowByUniqueId', 'someName')`

**Comment by UtechtDustin** [comment]
Do you mean the table option [uniqueId](https://bootstrap-table.com/docs/api/table-options/#uniqueid)?

**Comment by enriquepiatti** [comment]
Yes, that works! thanks @UtechtDustin
