### ISSUE TITLE
Filter Control with Column Sort and Search on Enter Key - filter not applied, but column sort is toggled

### ISSUE THREAD

**Issue by dougauerbach** [wenzhixin/bootstrap-table#5833]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
When the table uses the bootstrap-table-filter-control extension, and the column is also sortable, with "input" column filter and searchOnEnterKey is true, the filter is not applied, but instead the column sort is toggled.  

It would be awesome if the filter were applied and the enter key did not toggle nor fire the column sort, under this scenario.

**Example**  
https://live.bootstrap-table.com/code/dougauerbach/8686

**Comment by yeezy69** [comment]
I would be happy if this bug would be fixed soon.

**Comment by matheusilario** [comment]
I'm also going through this. I use the table in several screens but in only 1 this is happening.

I'm following the way it's configured in the other tables but the problem persists.

**Comment by djhvscf** [comment]
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9722
