### ISSUE TITLE
Use bootstrap-table with bootstrap v5

### ISSUE THREAD

**Issue by olivier47adrian** [wenzhixin/bootstrap-table#5837]
Hello,
despite my research i couldn't find how to tell bootstrap-table that i'm using bootstrap version 5.
Is there a conf to give?

**Comment by UtechtDustin** [comment]
No need to tell the bootstrap-table which bootstrap version do you use.
The table will check a few constants which only exists in just one version at a time.

Which kinf of errors do you have ?
Is bootstrap-table loaded after bootstrap ?

If you have issues, please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by olivier47adrian** [comment]
Thank you for your reply.
That's what I understood about how bootstrap-table works.
Unfortunately this one always tells me that my bootstrapVersion is 4.
As I use bootsrap v5 well, this poses a problem, especially on dropdowns (bs-toggle) and side effects on the grid.

I am using laravel 8 and laravel-mix to compile the assets.
I have downloaded bootstrap and bootstrap-table with npm.
In my app.js I import theese libraries like this:

```javascript
import jQuery from 'jquery';
window.jQuery = jQuery;
import 'bootstrap';
import 'bootstrap-table/dist/bootstrap-table.js';

```

If I try to load bootstrap + bootstrap-table through a cdn it works correctly (good detection of bootstrap v5).

So I guess the problem is my comprehension.
On what is the detection of the bootstrap version based?

I also tried (to understand) to load bootstrap through a CDN and bootstrap-table by npm + laravel-mix. 
And inversely bootstrap-table through a cdn and bootstrap by npm + laravel-mix.

Any ideas?

**Comment by UtechtDustin** [comment]
The dedection is quite simple, we use the constants `$.fn.dropdown.Constructor.VERSION` and `bootstrap.Tooltip.VERSION` to detect the version. See here: https://github.com/wenzhixin/bootstrap-table/blob/develop/src/constants/index.js#L6-L27

Maybe the laravel-mix will cause this issue, could you test it without ?

**Comment by cocowalla** [comment]
I'm having a similar problem, with a framework (CoreUI) that is _based on_ Bootstrap 5.

What would be really useful is to have a way to override Bootstrap Table's auto-detection, to force it to use Bootstrap 5 semantics?

**Comment by cocowalla** [comment]
OK, I've managed to force it to add the `bootstrap5` class insteadl of `bootstrap4`, by including this before loading the Bootstrap Table JS:

```javascript
const bootstrap = {
    Tooltip: {
        VERSION: "5"
    }
}
```

It doesn't appear to be fixing the styles for me, but I'll save that for another issues if I can't figure it out - hope the stuff above helps others.

**Comment by FelixOutta** [comment]
hey I have the same problem with rails6 and webpacker. 

It detects as class bootstrap4 
![image](https://user-images.githubusercontent.com/79710091/135095996-c5c95e9d-c281-4c8c-91c3-4df1c0810ede.png)
and some styles are messed up, when I change to 'bootstrap5' styles are working again. 

Dropdown fails in both cases even though dropdowns from bootstrap5 are working for me outside of datatables. 

adding 

```
const bootstrap = {
    Tooltip: {
        VERSION: "5"
    }
}
```
to `application.js` actually is not working for me. 
Any ideas how to force bootstrap5 over 4 here and to get dropdown working?

**Comment by cocowalla** [comment]
@FelixOutta are you sure you're adding the snippet _before_ loading the Bootstrap-Table JavaScript file?

**Comment by FelixOutta** [comment]
> @FelixOutta are you sure you're adding the snippet _before_ loading the Bootstrap-Table JavaScript file?

yes I have tried

**Comment by FelixOutta** [comment]
> Currently experiencing a similar issue with my Vue3 app. Dependencies versions:
> 
> * bootstrap: **5.0.2**
> * bootstrap-table: **1.18.3**
> * jquery: **3.6.0**
> 
> Importing libraries in main.js as follow:
> 
> ```js
> import jQuery from 'jquery'
> window.jQuery = jQuery
> import "bootstrap/dist/css/bootstrap.min.css"
> import 'bootstrap-table/dist/bootstrap-table.min.css'
> import "bootstrap"
> import 'bootstrap-table/dist/bootstrap-table.js'
> import BootstrapTable from 'bootstrap-table/dist/bootstrap-table-vue.esm.js'
> ```
> 
> > The dedection is quite simple, we use the constants `$.fn.dropdown.Constructor.VERSION` and `bootstrap.Tooltip.VERSION` to detect the version. See here: https://github.com/wenzhixin/bootstrap-table/blob/develop/src/constants/index.js#L6-L27
> > Maybe the laravel-mix will cause this issue, could you test it without ?
> 
> From my understanding and deduction, the two `rawVersion` checks mentioned, which seem to basis bootstrap's version from bootstrap's `BaseComponent`'s `VERSION` static variable, either return `undefined` which then uses `bootstrapVersion` default of 4, or the `rawVersion` receives '4' from `VERSION`.
> 
> Attaching a screenshot from my Chrome devtools inspection, which reveals `bootstrap4` as the initialized class. Upon manually adjusting it to `bootstrap5`, my styling issues were resolved:
> 
> <img alt="Screen Shot 2021-08-26 at 16 26 54" width="349" src="https://user-images.githubusercontent.com/6127483/130970892-942851d9-079a-40f1-9c59-307709e6e324.png">
> 
> Tried providing an example using your editor, but seems like your base **Vue Component** example is already broken as it is... https://live.bootstrap-table.com/example/welcomes/vue-component.html

for some reason 

`$.fn.dropdown.Constructor.VERSION` is undefined in my case.

**Comment by FelixOutta** [comment]
@lielvan for some reason the detection must be failing in my case, because

$.fn.dropdown.Constructor.VERSION is undefined. Not sure why, but bootstrap5 is working fine. Any ideas how to fix this?

**Comment by olivier47adrian** [comment]
@FelixOutta 
This is a library loading order issue. 
Try to wait until bootstrap 5 is fully loaded. You can play on the priorities of your scripts for example.
https://addyosmani.com/blog/script-priorities/
That solved the problem for me.

**Comment by UtechtDustin** [comment]
I can reproduce the issue with symfony encore (webpack).
@FelixOutta as workaround you can use
```
window.bootstrap = {
  Tooltip: {
    VERSION: "5"
  }
}
```

**Comment by riskersen** [comment]
I'm also experiencing issues with using bootstrap5+table+webpack encore. After impleting mentioned fix above, basic functionality is given, but stuff like

- group by toggle
- cellstyle function

isn't working..

**Comment by wenzhixin** [comment]
Updated to use bootstrap v5 as the default theme.
