### ISSUE TITLE
Problem with columns order after refresh

### ISSUE THREAD

**Issue by amir-reyhan** [wenzhixin/bootstrap-table#5840]
Hey guys.

so I'm using bootstrap 5 and when I scroll the horizontal scroll and click the refresh button 
table columns will be disorganized 
![01](https://user-images.githubusercontent.com/82934296/130407500-49e0ff26-3bb2-4065-9ba0-b0d048ccc22c.png)

here's what happens

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by amir-reyhan** [comment]
https://live.bootstrap-table.com/code/amir-reyhan/8935
Here .!

**Comment by UtechtDustin** [comment]
Thanks for the example, but sadly it's not working.
Please provide us an working example (optimally in english).

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we got no response and no example from you within 7days.
If you still need help plesae provide us an example!
