### ISSUE TITLE
Save State

### ISSUE THREAD

**Issue by riteshkawadkar** [wenzhixin/bootstrap-table#5842]
**Description**  
Is it possible to save the state of the table, let say if I have toggled a few columns visibility, then after the refresh I would like to maintain that state?

**Comment by djhvscf** [comment]
You can use the cookie extension

https://bootstrap-table.com/docs/extensions/cookie/#example

**Comment by riteshkawadkar** [comment]
But this saves at browser, how will I save the same at the server level.
I want the user to save the table state, he can log in from various browsers and system

One such example is stateSaveCallback from DataTables - https://datatables.net/examples/basic_init/state_save.html
