### ISSUE TITLE
detailView

### ISSUE THREAD

**Issue by Friends4U** [wenzhixin/bootstrap-table#5844]
How can I view the hidden columns in detailview?

I was experimenting a bit and asked a question on StackOverflow also (https://stackoverflow.com/questions/68958617/bootstrap-table-gethiddencolumns), but perhaps someone here can help me.

I want the hidden columns to be seen in the detailview, and when I unhide a column it should not be in de detailview anymore.

I hope you understand, sorry for my bad English.

**Comment by djhvscf** [comment]
I think that scenario is not supported. Can you explain a little bit more what's your scenario?

**Comment by Friends4U** [comment]
I chose another direction, so the question is now obsolete.

What I meant was, I want some data on the detailsview that is not visible on normal view :)
