### ISSUE TITLE
column body are not be align to  head  when table has a great many columns

### ISSUE THREAD

**Issue by joytom0591** [wenzhixin/bootstrap-table#5845]
**Bootstraptable version(s) affected**:
v1.18.3

**Description**  
column body are not be align to  head  when table has a great many columns because of jquery width() is integer

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
We will close this issue, because we got no response and no example from you.
If you still need help please provide us an example.

**Comment by IM-possilbe** [comment]
**have a try . in bootstrap-table.js just add** 

`if (fixedBody.scrollHeight > fixedBody.clientHeight) {
              scrollWidth = Utils.getScrollBarWidth();
          } else {
              scrollWidth = 0;
          }`
**before**
` this.$tableHeader.css('margin-right', scrollWidth).find('table').css('width', this.$el.outerWidth()).html('').attr('class', this.$el.attr('class')).append(this.$header_);`
