### ISSUE TITLE
column body are not be align to head when sort

### ISSUE THREAD

**Issue by joytom0591** [wenzhixin/bootstrap-table#5846]
**Bootstraptable version(s) affected**:
v1.18.3

**Description**  
when I use fixed column and set some column sortable, 
column body are not be align to head when sort,
I fixed it with a addition code like this:
`key: "horizontalScroll",
value: function horizontalScroll() {
       ......
      this.$tableBody.off('scroll').on('scroll', function () { 
       ......
      }
      
     //to fix: 修复排序后，滚动条位置不对，导致列对不齐问题
     this.$tableBody.trigger("scroll")
}
`

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
We will close this issue, because we got no response and no example from you.
If you still need help please provide us an example.
