### ISSUE TITLE
add a event before refresh

### ISSUE THREAD

**Issue by joytom0591** [wenzhixin/bootstrap-table#5847]
**Description**  
v1.18.3

before refresh, I want to validate the query condition, when condition is not right, I want it do not refresh and alert user,  but there is no way to stop refresh button(showRefresh: true).

**Comment by wenzhixin** [comment]
> Return false to stop request.

https://bootstrap-table.com/docs/api/table-options/#queryparams

Example: https://live.bootstrap-table.com/code/wenzhixin/8888
