### ISSUE TITLE
Save State of table - not by cookie but at server side

### ISSUE THREAD

**Issue by riteshkawadkar** [wenzhixin/bootstrap-table#5849]
**Description**  
Is it possible to save the state of the table, let say if I have toggled a few columns visibility, then after the refresh I would like to maintain that state?

I want the user to save the table state, he can log in from various browsers and system

One such example is stateSaveCallback from DataTables - https://datatables.net/examples/basic_init/state_save.html

**Comment by djhvscf** [comment]
I think you can retrieve the cookies values from the browser.. Save those values in the database and then when the user logs in from a different browser you can set those cookies again

**Comment by UtechtDustin** [comment]
It's possible with the methods [cookieCustomStorageGet](https://bootstrap-table.com/docs/extensions/cookie/#cookiecustomstorageget) and [cookieCustomStorageSet](https://bootstrap-table.com/docs/extensions/cookie/#cookiecustomstorageset).

If you still need help please let us know!

**Comment by tooliload** [comment]
Hey, its easy to save Cookies with StorageSet Function, but hard to handle the StorageGet and read out, the saved cookies. Can you explain an example to handle with PHP? 

If have try the following output (to read in with StorageGet), without success: 
`
# Single Cookie Value
{"searchText":"easy text to search"}     or
[{"searchText":"easy text to search"}]

# Single Cookie Value by Full Table Name
{"tableid.bs.table.searchText":"easy text to search"}   or
[{"tableid.bs.table.searchText":"easy text to search"}]

# Multiple Cookie-Settings at one
{"pageNumber":"2","tableid.bs.table.searchText":"easy text to search"}  or
[{"pageNumber":"2","tableid.bs.table.searchText":"easy text to search"}]
`

The Attribut filterBy, hiddenColumns, sortPriority i allways set to "null" or {}, to handle the function. Any ideas or examples?
