### ISSUE TITLE
Icons to indicate sortable columns

### ISSUE THREAD

**Issue by shuangg** [wenzhixin/bootstrap-table#585]
Could we please have a sortable icon next to each sortable column heading? Grey colour up and down arrows similar to what is displayed here http://www.datatables.net/examples/basic_init/table_sorting.html. 
Otherwise I have to keep reminding my users that if and which columns are sortable. Many thanks.

**Comment by djhvscf** [comment]
:+1:

**Comment by djhvscf** [comment]
Working on it! @shuangg

**Comment by shuangg** [comment]
@djhvscf Thank you very much!

**Comment by shuangg** [comment]
@djhvscf Is there an ETA?

**Comment by djhvscf** [comment]
ok, I already have the icons and the logic! I'm testing because when I put the icons in the column header, the column becomes a little bit more big!

**Comment by shuangg** [comment]
Would this feature be included in the next relase?

**Comment by haideraliarain** [comment]
@djhvscf  any update on this?

**Comment by djhvscf** [comment]
Refer to: https://github.com/wenzhixin/bootstrap-table/pull/793

**Comment by wenzhixin** [comment]
Thanks for @djhvscf
