### ISSUE TITLE
pivottable.js and multi-fact pivot table. 

### ISSUE THREAD

**Issue by BBBhatt** [wenzhixin/bootstrap-table#5852]
I have used pivottable.js and multi-fact pivot table to use multiple aggregators.. 

How to use bootstrap-table after applying pivottable.js method pivot() or pivotUI() with multiple aggregators???
my code looks like: 
('#tblData').pivotUI(.,,,)

**Comment by wenzhixin** [comment]
Sorry, I don't know what you mean.

**Comment by UtechtDustin** [comment]
I close this issue, because we don't get any response from you.
If you still need help, just examplain what do you mean and we will reopen the issue.
