### ISSUE TITLE
Export to excel with css doesn't work properly

### ISSUE THREAD

**Issue by leGnacq** [wenzhixin/bootstrap-table#5856]
Bootstrap table 1.18.2

I want to export my html table to excel, xls or xlsx but when i do that, not all css is keeped.
I have all font-family and font-weight. I have background for header but not on row.

And only when i export in xls, in xlsx i havo no css.

Some css for classes is keeped and some for inline is not, why ?

Can someone help me ? Thank you.

**Comment by wenzhixin** [comment]
Please post the issue to https://github.com/hhurz/tableExport.jquery.plugin.
