### ISSUE TITLE
Using data-filter-default with data-filter-control="select" is not working

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#5859]
**Bootstraptable version(s) affected:**
1.8.3

**Description**
`bootstrap-table-filter-control` using` data-filter-control="select"` with default data set with `data-filter-default="Item 0"` is not working.

Check exemple : the field "name" has no default value and I don't understand why.
https://live.bootstrap-table.com/code/sdespont/8910

The expected behavior is using the select filter with server side data.

**Comment by sdespont** [comment]
@djhvscf Is there any workaround to "pre-filter" server side data with filter-control ?

**Comment by sdespont** [comment]
@djhvscf Is there a chance to fix this issue in the next version? I have a large list loaded using server side data, and having a default filter value set would avoid a long loading time for my users.

**Comment by djhvscf** [comment]
This issue is fixed here: https://github.com/wenzhixin/bootstrap-table/pull/5583

Example with fix: https://live.bootstrap-table.com/code/djhvscf/9723

**Comment by UtechtDustin** [comment]
@djhvscf 
The table will be filtered, but the default selected filter is not selected.
Cache issue ?
@wenzhixin could you check if we have possible cache issues with the editor ?

**Comment by sdespont** [comment]
@djhvscf Thank you so much ! 

FYI, I also have the default selected filter not selected.

**Comment by sdespont** [comment]
@djhvscf It is working well now : thank you very much!

![image](https://user-images.githubusercontent.com/646632/144022832-f1ec0644-c0e7-4756-a983-eeff3a80e964.png)

Can we expect a release in the next days?
