### ISSUE TITLE
assign response parameter as data attribute?

### ISSUE THREAD

**Issue by jms82** [wenzhixin/bootstrap-table#586]
[{"pid":"2","teamID":"4","teamscore":"0","points":"0","rebounds":"0","assists":"0","steals":"0","blocks":"0","turnovers":"0"}]

for example is there a way i can assign the teamID as a data attribute to a row instead of just bring it in as a column?

ex.

<tr data-teamid='teamID from json"   ??

**Comment by wenzhixin** [comment]
Sorry, we do not support this feature.
