### ISSUE TITLE
Unable To Hide Table Border

### ISSUE THREAD

**Issue by g000ze** [wenzhixin/bootstrap-table#5860]
**Bootstraptable version(s) affected**:
1.18.0

**Description**  
Trying to hide the outer table border with "class" does not work for some reason. As the [documentation](https://bootstrap-table.com/docs/api/table-options/#classes) says, the default value is `'table table-bordered table-hover'`, so I assume that `'table table-hover'` is supposed to hide the border.

**Example**  
https://live.bootstrap-table.com/code/g000ze/8948

**Comment by djhvscf** [comment]
![Screen Shot 2021-09-10 at 15 14 57](https://user-images.githubusercontent.com/4496763/132918443-e1ecb9ff-73a8-47bd-bf27-3757470afc40.png)
As you can see we're adding the table-bordered class.. So this is a bug.

**Comment by djhvscf** [comment]
See this example: https://live.bootstrap-table.com/code/djhvscf/8953
