### ISSUE TITLE
Card view problem with operate events (bug in cookie plugin)

### ISSUE THREAD

**Issue by Friends4U** [wenzhixin/bootstrap-table#5863]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
Same as here: https://github.com/wenzhixin/bootstrap-table/issues/160

When you use: showColumns: true and you add or remove a column from view, after that the window.operateEvents do not work anymore from card view.

**Comment by Friends4U** [comment]
After testing, it looks like this is when using multiple tables on one page (and perhaps when the other tables are hidden).

**Comment by Friends4U** [comment]
Ok, I have tested some more, and this problem only occurs when the cookie plugin is used!

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com).
I can't reproduce it with my [example](https://live.bootstrap-table.com/code/UtechtDustin/9153).

**Comment by Friends4U** [comment]
I will try to create an example, it works in yours I see...

**Comment by Friends4U** [comment]
Sorry, I am not able to build an example in your builder :(
I can give you access to my DEV.

When I set the cookie to false the actions work in cardview.
I tried to disable all other plugins but to no avail...

**Comment by UtechtDustin** [comment]
Why are you not able to build an example ?
Do you checked the [help page](https://github.com/wenzhixin/bootstrap-table/wiki/Online-Editor-Explanation) for the online editor ?

**Comment by UtechtDustin** [comment]
We will close this issue, because we got no response from you within 7 days.
If you still need help please provide us an example and we will reopen this issue.
