### ISSUE TITLE
翻页问题求助！！！

### ISSUE THREAD

**Issue by lumengda** [wenzhixin/bootstrap-table#5869]
**Description**  
$("#table").bootstrapTable('nextPage');进行下一页跳转时候，不发请求是怎么回事啊，同样的方法，我换了个其他接口就可以进行跳转，用现在这个接口就连Network中都没有请求的，而且在bootstrapTable的queryParams函数中加alert，没有请求的接口这个alert也不弹，有请求的会有alert弹出。这里要去哪里查这个问题，求大佬指路

**Example (optional)**  

![1632736229581](https://user-images.githubusercontent.com/53165426/134887092-18c90aa0-5e03-4eb2-90b7-334810cd19f1.jpg)
![1632736080171](https://user-images.githubusercontent.com/53165426/134886808-45404f76-a4f1-41e5-b7da-75d18c90d795.jpg)
使用注释的代码，alert可以弹出，并且翻页正常跳转，现在的不能跳转，并且没有请求

**Comment by vonch** [comment]
贴代码

**Comment by lumengda** [comment]
发现问题，是解析回参的时候出错了，该传值给total，传了个对象
