### ISSUE TITLE
Error on export large amount of data

### ISSUE THREAD

**Issue by RMkuzmi** [wenzhixin/bootstrap-table#5872]
My table has 150 th. rows (with 2000 rows it still doesn't work).<br>
When I running export (e.g. to Excel) it tries to do something, after some seconds it throws this messages in Chrome developer concole:
> [Violation] 'load' handler took 15381ms
> [Violation] Forced reflow while executing JavaScript took 7709ms

After all page is disappearing and the only thing that i can to do with it - is to close it (reloading doesn't working)

**Comment by UtechtDustin** [comment]
The [export plugin](https://github.com/hhurz/tableExport.jquery.plugin) should not be used for tables with a huge dataset.
Instead you should consider to export the data in the backend.
If you still need help with that please, open a issue in the repository of the pugin (link above).

**Comment by RMkuzmi** [comment]
Actually I fixed this issue. I just have changed the server timeout
