### ISSUE TITLE
Column width using percentage?

### ISSUE THREAD

**Issue by ricyoca** [wenzhixin/bootstrap-table#588]
Hi,

Is there any way to define column width using percentage?

Thank you

**Comment by djhvscf** [comment]
Just add the '%' in the end of your number like: '50%' and the bootstrap table will use percentage. :) Ref to: https://github.com/wenzhixin/bootstrap-table/pull/603

**Comment by alvin0618** [comment]
hi djhvscf, I use jquery to init the bootstrap-table, however if I set 50% it will show 50%px in styling.

columns: [ {title: 'Column A', width: '50%'}]

<th style="width: 50%px; " class=""><div class="th-inner sortable">Column A</div><div class="fht-cell"></div></th>

**Comment by djhvscf** [comment]
It depends on the version that you are using.. but please wait for the next release.. :+1:  @alvin0618

**Comment by wenzhixin** [comment]
Merged.

**Comment by alvin0618** [comment]
Hi, I have downloaded the 1.7.0 version
Same version version one is dist min another one is src code, however they are not the same.

bootstrap-table.js
style += sprintf('width: %s'+ unitWidth +'; ', column.checkbox || column.radio ? 36 : column.width);

bootstrap-table.min.js
("width: %spx; ",f.checkbox||f.radio?36:f.width)

**Comment by alvin0618** [comment]
hi wenzhixin,
your rawgit link as below, both are fine. I will use this version.

https://rawgit.com/wenzhixin/bootstrap-table/master/dist/bootstrap-table.min.js
https://rawgit.com/wenzhixin/bootstrap-table/master/src/bootstrap-table.js

**Comment by djhvscf** [comment]
Exc! @alvin0618
