### ISSUE TITLE
updateCell updating all tables...

### ISSUE THREAD

**Issue by Friends4U** [wenzhixin/bootstrap-table#5880]
Hi, 

I have a problem, I hope you can help me.

**Description**  
I use multiple tables on one page and created a modal to edit the entries in a table.
When I use updateCell and I edit the second cell of the first table, all other tables also change their second cell.

How do I fix this?

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/)
