### ISSUE TITLE
Retrieve the table id when clicking on an operator

### ISSUE THREAD

**Issue by Friends4U** [wenzhixin/bootstrap-table#5883]
Hi,

How can I get the table ID when clicking on an operator?

**Comment by UtechtDustin** [comment]
You provided an example which contains almost every feature of the bootstrap-table, so it's not a good example..
Next time please provide an (minimal) example with the EDITOR not from the examples page.

But i guess you mean the events option (https://examples.bootstrap-table.com/index.html#column-options/events.html) ?
Example to get the id of the table: https://live.bootstrap-table.com/code/UtechtDustin/9212

**Comment by Friends4U** [comment]
I am very sorry, I am not trying to annoy you guys!
As for the other example, I still need to find where the problem lays before I can make one.

As for your answer, thanks! It works! I wish I could hire you if I had questions ;) I would gladly pay.
