### ISSUE TITLE
bootstrap-tables and x-editable

### ISSUE THREAD

**Issue by xmbohx** [wenzhixin/bootstrap-table#5895]
I am trying to understand how x-editable works with bootstrap tables, especially when saving the edited cell.

I created fiddle here [https://jsfiddle.net/xmbohx/tpxr9u17/40/](https://jsfiddle.net/xmbohx/tpxr9u17/40/)

Above fiddle encounters error when I click on the cell to edit. My offline code is working fine.

The question is, how to catch (or create function then call an ajax save) whenever there is cell new value is saved?

**Comment by UtechtDustin** [comment]
I will close this issue, because it is already quite old.
If you still need help please let us know and provide us an example using our [editor](https://live.bootstrap-table.com/).
