### ISSUE TITLE
autoRefresh

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#5898]
it seems you need to have "autoRefresh: true" for auto refresh to work but according to the documentation it's not required?

**Comment by UtechtDustin** [comment]
Because of our [buttons](https://bootstrap-table.com/docs/api/table-options/#buttons) feature (which also will be used internally), this is already implemented.
You can disable the button using `data-show-auto-refresh="false"`.
Example: https://live.bootstrap-table.com/code/UtechtDustin/9602
