### ISSUE TITLE
Expanding detail view jumps/scrolls page to top when table is filtered

### ISSUE THREAD

**Issue by davidcarlin-ap** [wenzhixin/bootstrap-table#5899]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
When I have my table filtered with data-filter-control="true", then I scroll to the bottom of the page and expand the details view on a row, my page jumps to the top again. This is super frustrating. 

Any ideas what I'm doing wrong? Thanks

**Comment by davidcarlin-ap** [comment]
It looks like the filter control gains focus immediately after expanding a detail view.

**Comment by UtechtDustin** [comment]
As written in the issue template, please provide us an example using our [editor](live.bootstrap-table.com/).

**Comment by UtechtDustin** [comment]
We will close this issue, because we got no response from you within 7 days.
If you still need help please provide us an example and we will reopen this issue.
