### ISSUE TITLE
Client Side Translations

### ISSUE THREAD

**Issue by wodka** [wenzhixin/bootstrap-table#59]
Right now it is not possible to only supply the client one file and then choose there which language to choose.

I think this could be added by storing the translation callbacks in sub objects

BootstrapTable.DEFAULTS.languages = "en";

and then to store the translation callbacks in another array

**Comment by talos** [comment]
:+1: Is this referenced in the docs anywhere? I haven't been able to find it.

**Comment by wenzhixin** [comment]
OK, I will add it to the docs if I have time.

**Comment by talos** [comment]
Thank you!
