### ISSUE TITLE
pagination options

### ISSUE THREAD

**Issue by systemchef** [wenzhixin/bootstrap-table#590]
A nice plugin, I was wondering if there are any options on placement of pagination?
Like
Place pagination on top or bottom of table? or place both on top and bottom.
Align left or right ?
That will enable to place pagination on top right/top left/bottom right /bottom left

I did acheive it via css hack but it would be nice to add it as an option in the plugin

also, the pageNumber and totalPages should be added as boolean to show or hide along with where to show like top or bottom.

Thanks for good effort though.

**Comment by wenzhixin** [comment]
Thanks for your advice, but now have not enough time to add this feature, any pull request is welcome.

**Comment by djhvscf** [comment]
@systemchef  can you share us your solution to put on top the pagination??

**Comment by systemchef** [comment]
just sent a pull request, please check the main JS file (bootstrap-table.js)

**Comment by djhvscf** [comment]
Ok... Waiting for your PR @systemchef

**Comment by djhvscf** [comment]
Hey! @wenzhixin you can close this one
