### ISSUE TITLE
通过新增行添加的行不能勾选

### ISSUE THREAD

**Issue by tanwei1** [wenzhixin/bootstrap-table#5901]
1.71之后的版本都有这个问题

![image](https://user-images.githubusercontent.com/40681568/137874406-589137bf-bc5b-4ee5-9ce8-e7d137614391.png)

**Comment by UtechtDustin** [comment]
We will close this issue, because we got no response from you within 7 days.
If you still need help please provide us an example and we will reopen this issue.
