### ISSUE TITLE
data-detail-formatter with sub Table 

### ISSUE THREAD

**Issue by pipiscrew** [wenzhixin/bootstrap-table#5903]
**Description**  
v1.18.3

[edit]
hmm, sure is not possible with **data-detail-formatter**, no 'compatible' with AJAX (even with **async** property).... 

any example with **real time fetch** and **sub table**?

-------

**Example (optional)**  
On bootstrap-table there are rows, and I would like, when user click the **expand** icon > Query the API > display the result data as child bootstrap date.

I'm using these properties on table HTML
```
    data-detail-view="true"
    data-detail-formatter="detailFormatter"
--
    data-url="entities/<?= $entity ?>Helper.php"
    data-side-pagination="server"
    data-pagination="true"
    data-query-params="queryParams"
```

the plus icon appear - fine

specifically, on the **detailFormatter** function can get the record ID - fine 
drawing a table, with the following code
```
function detailFormatter(index, row) {
    console.log(row.id);
    var html =  "<table border=1><tr><td>1</td><td>2</td></tr></table>"
    return html;
}
```

![snap522](https://user-images.githubusercontent.com/3852762/137938285-a68ef3a2-3cd6-4766-93fa-300c109b5dad.png)

the question how can I transform it to **bootstrap-table** ? 

Using the method `.bootstrapTable()` is not possible there, needs an element.

Or the only way to achieve this, is the **Sub Table** ref examples.bootstrap-table.com/index.html#welcomes/sub-table.html
?

**Comment by UtechtDustin** [comment]
No it's not possible through the detailFormatter.
Use the `onExpandRow` Event (like in the sub-table example), do you api request and render the table.

**Comment by pipiscrew** [comment]
complete example 
https://www.pipiscrew.com/2021/10/bootstrap-table-use-of-child-table/
