### ISSUE TITLE
expanding sub table, push all base table columns to right

### ISSUE THREAD

**Issue by pipiscrew** [wenzhixin/bootstrap-table#5904]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
when expanding the **sub table**, on **base table** all columns **squeezed on right side**

**Example**  
on the following example the sub table has 18 fields and the base 4 fields
![testBT2](https://user-images.githubusercontent.com/3852762/137967786-bcd47307-397d-46de-9a01-1424d4d60740.gif)

code for **sub table**
https://github.com/wenzhixin/bootstrap-table/issues

**Comment by pipiscrew** [comment]
https://jsfiddle.net/no1c3fxq/3/

**Comment by UtechtDustin** [comment]
As i asked for, please use our editor for examples.
