### ISSUE TITLE
resize problem with nav-tabs

### ISSUE THREAD

**Issue by pipiscrew** [wenzhixin/bootstrap-table#5906]
**Description**  
1.18.3

**Example (optional)**  
using bootstrap5 nav-tabs, each tab has a grid, when browsing the page on for example tab1, resize/minimize the browser, then maximize it, when navigate to other tabs getting 

![snap525](https://user-images.githubusercontent.com/3852762/137999928-65509b29-2abf-45f0-a34d-de2d3e5ea828.png)

sample
https://jsfiddle.net/26cjanhf/

**Comment by wenzhixin** [comment]
You can use the `resetView` method to solve the problem: https://live.bootstrap-table.com/code/wenzhixin/9328

**Comment by pipiscrew** [comment]
@wenzhixin 
**Vue2 CRUD** template added :100: 
https://github.com/pipiscrew/DBManager
