### ISSUE TITLE
Weird error suddenly - TS2702 JQuery ASP.NET Core MVC Visual Studio

### ISSUE THREAD

**Issue by vlatro** [wenzhixin/bootstrap-table#5907]
Hi,

I use bootstap-table in my ASP.NET Core MVC application.
Today suddenly I got a build error saying:

Build started...
1>------ Build started: Project: xxxx, Configuration: Debug Any CPU ------
1>\wwwroot\lib\bootstrap-table-master\index.d.ts(170,20): error TS2702: Build:'JQuery' only refers to a type, but is being used as a namespace here.
1>\wwwroot\lib\bootstrap-table-master\index.d.ts(171,58): error TS2702: Build:'JQuery' only refers to a type, but is being used as a namespace here.
1>Done building project "xxxx.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

These are the lines of code:
![image](https://user-images.githubusercontent.com/24847194/138043021-51070489-5316-432f-966a-3d7cd496a563.png)

I did some googling but I can't find out what the problem is.

**Comment by WoLpH** [comment]
I think one of my other libraries somehow had this reference which made it work. In a brand new project it did cause errors, so I've created a fix :)

https://github.com/wenzhixin/bootstrap-table/pull/5923
