### ISSUE TITLE
updateRow does not work as expected after sorting

### ISSUE THREAD

**Issue by Friends4U** [wenzhixin/bootstrap-table#5917]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
When sorting a table and using updateRow the wrong index is changed

**Example**  
https://live.bootstrap-table.com/code/Friends4U/9365
https://live.bootstrap-table.com/code/Friends4U/9367 (with cookie after sorting once)

**Comment by Friends4U** [comment]
By the way, the problem is also with search. Search for "1", and click the heart of the second item.

https://live.bootstrap-table.com/code/Friends4U/9435

**Comment by Friends4U** [comment]
@UtechtDustin, Is this fixed in 1.19.0?

**Comment by UtechtDustin** [comment]
As you can see the PR is still open, because there is a issue which i don't understand right now.

**Comment by Friends4U** [comment]
Sorry @UtechtDustin, I am new to this (and GIT). 
Is there a workaround I can use for my customer?

**Comment by UtechtDustin** [comment]
I don't know a workaround yet, sorry.

**Comment by Friends4U** [comment]
Is it unfixable?

**Comment by djhvscf** [comment]
We're working on this issue @Friends4U . We'll let you know any update

**Comment by Friends4U** [comment]
If it's not going to be fixed please let me know. 
Then I need to reload the table (which is very big so it costs a few minutes each time).

**Comment by SBaudrant** [comment]
@Friends4U 
Is it possible for you to go with "updateByUniqueId" instead of "updateRow" event ? 
i'm having the same issue, and it seems to do the job

https://live.bootstrap-table.com/code/SBaudrant/10155

**Comment by Friends4U** [comment]
You are my hero! Tnx!

**Comment by Friends4U** [comment]
I wish I could hire you @SBaudrant

**Comment by Friends4U** [comment]
P.S. The latest version of table-fixed-columns.min.js also makes updateRow not update the row entirely...
