### ISSUE TITLE
filterDefault on a select filter doesn't mark the default value as selected

### ISSUE THREAD

**Issue by Guistoff081** [wenzhixin/bootstrap-table#5919]
**Bootstraptable version(s) affected**:
1.16.0

**Description**  
Hi, guys!
I'm using filterDefault to set the default filter value on a select filter and filterData to set the options values. When my table loads  data from ajax, i get the filtered rows by the default value but the select input doesn't show the default option as selected.

**Example**
  
* Table header column
`<th data-field="active" data-filter-control="select" data-filter-default="Ativada" data-filter data="var:activeFilterValues">Status</th>`

* Custom filterData values
`<script>
var activeFilterValues = {
        '':'',
        Ativada: 'Ativada',
        Desativada: 'Desativada'
    };
</script>`

It does brings all 'Ativadas' by default but doesn't show as selected.
![scrshottableroutes](https://user-images.githubusercontent.com/55218750/139337705-bc63b86c-d4e2-4927-85b6-9979b9a1e795.png)

**Additional context**  
I tried everything, even forcing change the selected option onload, but it doesn't seemed ok.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
We will close this issue, because we got no response from you within 7 days.
If you still need help please provide us an example and we will reopen this issue.

Also you are using a old version, do you tried to use the newest version ?
