### ISSUE TITLE
Merge cell性能

### ISSUE THREAD

**Issue by PH8919** [wenzhixin/bootstrap-table#5920]
你好，
最近我在使用bootstrap-table，实现我的应用，我的数据量比较大，需要构造10000行，33列的table，而且不能分页展示，每行数据中都会有需要merge的列，而且每行merge的列是不相同的。目前我的做法是加载完数据，使用mergeCells方法进行单元格合并。我统计了下，我大概调用了40000次这个方法，耗时6s左右。请问：针对我的应用场景，有没有提升性能的方法。

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
You can use the virtual scroll to solve your problem(你可以使用虚拟列表的功能): https://live.bootstrap-table.com/code/wenzhixin/9416, PR: #5920

**Comment by PH8919** [comment]
@wenzhixin @djhvscf 
I have used online editor check my application. The performance was improved significantly. But this feature is newly-added, I used latest released version 1.18.3. So what is the release schedule for next version?
