### ISSUE TITLE
Problem sorting percentages inside tags

### ISSUE THREAD

**Issue by sungkhum** [wenzhixin/bootstrap-table#5925]
### Bootstraptable version(s) affected

1.18.0

### Description

I was having trouble sorting with the default sort when a table had a percentage (with a percent sign) inside of a span.
I fixed it by doing a custom sort function, but I feel like there should be an easier way. Am I missing something?

### Example(s)

https://desodeals.com/

### Possible Solutions

A way to sort by data-text instead of the value of the td? <td data-text="-23.34"><span>-23.34%</span></td>

**Comment by UtechtDustin** [comment]
Add a new invisible column with the percent (raw number) and then use the [sortName](https://bootstrap-table.com/docs/api/column-options/#sortname) option to use the new column for sorting!

Example: https://examples.bootstrap-table.com/#column-options/sort-name-order.html
