### ISSUE TITLE
Columns sorting not working on "href" tag

### ISSUE THREAD

**Issue by quoidautre** [wenzhixin/bootstrap-table#5927]
### Bootstraptable version(s) affected

1.18.3

### Description

Hi,

Maybe I've poorly explained this [issue ](https://github.com/wenzhixin/bootstrap-table/issues/5908) but the solution (if it's a bug :) ), is not working.
I'va made an example [here](https://live.bootstrap-table.com/code/quoidautre/9459). If I click on the "ID" colums, the sorting is not good (eg : 1,10,2,3,4,5,... instead of 1,2,3,...,9,10,11))

If a remove the link href, it's working

Can you help me please ?
Thanks,
F.

### Example(s)

https://live.bootstrap-table.com/code/quoidautre/9459

**Comment by UtechtDustin** [comment]
Please check the issue https://github.com/wenzhixin/bootstrap-table/issues/5925#issuecomment-957188977

**Comment by quoidautre** [comment]
Hi, 

Thanks :-)

The [solution ](https://live.bootstrap-table.com/code/quoidautre/9483) is working, but when the page is loading, ir's seems that sorting is not available.

How can I do that.
F.

**Comment by UtechtDustin** [comment]
Please provide us an example :-)

**Comment by quoidautre** [comment]
The exemple below (https://github.com/wenzhixin/bootstrap-table/issues/5927#issuecomment-961148041) show the problem. When the page is loaded, the datas aren't sorted. 

But, maybe I've misunderstading :)
F.

**Comment by UtechtDustin** [comment]
There are a few issues with your example:

- The option `data-sort-order` is a table option not a column option
- You need also the second table option `data-sort-name`
- Don't use a hiding class, instead use the `data-visible` column option

Fixed example: https://live.bootstrap-table.com/code/UtechtDustin/9497

**Comment by quoidautre** [comment]
Hi,
Thanks  :) , it's working 👍 

Have a nice day.
F.
