### ISSUE TITLE
Modal table is not working without the button

### ISSUE THREAD

**Issue by DominiqueBenoliel** [wenzhixin/bootstrap-table#5928]
### Bootstraptable version(s) affected

1.18.3

### Description

Hello,
i have tried using Modal table with bootstrap 5 but that doesn't work. Is is impossible to open the modal windows.
I have tested the Modal table with bootstrap 4. That works with a button with data-target like the example. But i don't want to use a button. Instead i would like to click on a bootstrap-table cell to open the modal windows to show detail/additional informations about the row. How to fix ?
Dominique.

### Example(s)

Tested with this code:

<div id="jda_details" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal table</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table id="tabledetail"
          data-toggle="table"
          data-height="299"
          data-url="json/data1.json">
          <thead>
            <tr>
              <th data-field="id">ID</th>
              <th data-field="name">Item Name</th>
              <th data-field="price">Item Price</th>
            </tr>
          </thead>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

$table.on('click-cell.bs.table', function (element, field, value, row) {
var myModal = new bootstrap.Modal(document.getElementById('jda_details'), {keyboard: false, focus: true}); 
$('#jda_details').modal('show')
$('#tabledetail').bootstrapTable('resetView')
})

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/), as written in the issue form/template!

**Comment by DominiqueBenoliel** [comment]
Hi,
https://live.bootstrap-table.com/code/DominiqueBenoliel/9531
Work with bootstrap4. Not working on my project, so have to analyse in details. Maybe a conflict with a parent class but  difficult to find the cause.
With bootstrap5, partially works. The Close button doesn't fire the action to close the modal windows.
Dominique.

**Comment by UtechtDustin** [comment]
You don't used the modal html from bootstrap 5, so it can't work.
Example with fixed html: https://live.bootstrap-table.com/code/UtechtDustin/9532

So both (bootstrap 4 & 5) works fine in the editor, right ?
It seems it is a conflict on your project, which means we can't help or fix a bug on the bootstrap-table.
So i think the issue can be closed, or ? :-)

**Comment by DominiqueBenoliel** [comment]
Hi,
thanks for the fix about the close button. All is now working fine and perfect with bootstrap 4 and 5.
The same, my project is working now.
Previously, i have replaced the HTML code corresponding to the modal table without success using a dynamic method:
   document.getElementById('div_jda_details').innerHTML = html;

with <div> coded just after the <body>
  <div id="div_jda_details"></div>

Now i have just added the HTML modal table code into the current page (not using innerHTML) and that works.

Thanks.
Dominique.

**Comment by UtechtDustin** [comment]
Nice to hear you was able to fix the issue!
