### ISSUE TITLE
Using Search with server-side pagination and pagesize 'all' sends wrong limit

### ISSUE THREAD

**Issue by twelve-cgn** [wenzhixin/bootstrap-table#5931]
### Bootstraptable version(s) affected

1.18.3

### Description

I have a list with 30 rows and a pagesize of All set. Then I execute the search and get only one hit back. If I now delete the search pattern again, then the number of the last hits (here 1) is still transmitted as limit.

If I use a real number instead of 'All' (e.g. 50) then it works.

**Comment by UtechtDustin** [comment]
This issue is already fixed in the newest version, please update to the latest version.
ref #5896
