### ISSUE TITLE
Highlighting causes "Invalid regular expression" when text contains brackets or points

### ISSUE THREAD

**Issue by twelve-cgn** [wenzhixin/bootstrap-table#5932]
### Bootstraptable version(s) affected

1.19.0

### Description

If the highlighter is used on columns that contain parentheses ( "[", "]", "(" or ")"), then an exception occurs. This seems to happen only with isHTML, because there a replace is done with the TextContent. This TextContent contains the brackets and therefore this is part of the RegEx. The TextContent would have to escape the brackets and perhaps also points before.

In code it's line 1602: 
`defValue = value.replace(new RegExp('(>\\s*)(${textContent})(\\s*)', 'gm'), '$1${textReplaced}$3')`

Excpetion:
bootstrap-table.js:5609 Uncaught SyntaxError: Invalid regular expression: /(>\s*)(Executed DbCommand (0ms) [Parameters=[@__id_0='2'], CommandType='Text', CommandTimeout='30'] SELECT TOP(1) [k].[KundenId], [k].[ContactPersonName], [k].[ContactPersonPhone], [k].[CurrentUserCount], [...)(\s*)/: Unterminated character class
    at new RegExp (<anonymous>)
    at bootstrap-table.js:5609
    at Array.forEach (<anonymous>)
    at _class.initRow (bootstrap-table.js:5504)
    at _class.initBody (bootstrap-table.js:5693)
    at _class.load (bootstrap-table.js:6498)
    at Object.success (bootstrap-table.js:5968)
    at y (bundle.min.js?v=hNhfPDGCO8NKbO5bs-qED6Kq9wSl5PxyUBi_3SCDFgs:2)
    at Object.fireWith [as resolveWith] (bundle.min.js?v=hNhfPDGCO8NKbO5bs-qED6Kq9wSl5PxyUBi_3SCDFgs:2)
    at b (bundle.min.js?v=hNhfPDGCO8NKbO5bs-qED6Kq9wSl5PxyUBi_3SCDFgs:2)
(anonym) @ bootstrap-table.js:5609
initRow @ bootstrap-table.js:5504
initBody @ bootstrap-table.js:5693
load @ bootstrap-table.js:6498
success @ bootstrap-table.js:5968

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
Works fine for me: https://live.bootstrap-table.com/code/UtechtDustin/9548
Please provide an example as @djhvscf said and also requested in the issue template.

**Comment by twelve-cgn** [comment]
When using the Online Editor i can not reproduce it, because in my case i use server side pagination  and i use a data-formatter and data-search-formatter="false" for the specific column.

**Comment by UtechtDustin** [comment]
You can't reproduce it without server side pagination ?
That's strange, because the highlighting is client side and how the bootstrap-table get the data of the table shouldn't matter.

If that is the case we still need a example, without we can't help.
You can use server side pagination also on the editor, just use your url as data source (you can use a example source/dataset).
If you have CORS issues, please set the header [Access-Control-Allow-Origin: *](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) to allow the CORS request.

**Comment by twelve-cgn** [comment]
I will give it a try today.

**Comment by twelve-cgn** [comment]
That was quick 😄 

[https://live.bootstrap-table.com/code/twelve-cgn/9567](url)

**Comment by UtechtDustin** [comment]
Thanks, we will check that!

**Comment by twelve-cgn** [comment]
Oh i know now. When closing the value in the nameFormatter with ]]
`    value = "Executed DbCommand (3ms) [Parameters=[@p10='1', @p0='app.buspronet.de' (Nullable = false) (Size = 4000), @p1='1', @p2='Standardserver' (Nullable = false) (Size = 4000), @p3='11230', @p4='0', @p5='2021]]...";`

then the exception does not appear. But the highlighten doesn not work either because the regex pattern is total wrong. The variable `textContent `in line 1602 must be escaped before using it in regex.

**Comment by twelve-cgn** [comment]
Changing 
`defValue = value.replace(new RegExp('(>\\s*)(${textContent})(\\s*)', 'gm'), '$1${textReplaced}$3')`
to
`defValue = value.replace(new RegExp('(>\\s*)(${textContent.replace(/([\[\]\.\(\)\\])/g, "\\$1")})(\\s*)', 'gm'), '$1${textReplaced}$3')`
should fix it for the characters "`[]().\`".
The characterlist can be extended, i don't know which one is making trouble.

**Comment by UtechtDustin** [comment]
I guess there are some more chars which should be escaped.
The following should do the job.
```javascript
value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
```

Example: https://regex101.com/r/b1d1p4/1
