### ISSUE TITLE
Filter Control broken in 1.19.0

### ISSUE THREAD

**Issue by yeezy69** [wenzhixin/bootstrap-table#5933]
### Bootstraptable version(s) affected

1.19.0

### Description

After Update to 1.19.0 my Filter Control Tables are broken. Only at the last Cell the Filter Control will be shown.

![Screenshot_002](https://user-images.githubusercontent.com/22444686/141010489-d1bcab2d-7e06-405c-8054-e4979b1f926a.png)

In online Editor it is broken, too.

### Example(s)

https://live.bootstrap-table.com/code/yeezy69/9550

**Comment by UtechtDustin** [comment]
@djhvscf could check that? Its a quite critical issue.

**Comment by djhvscf** [comment]
Working on it

**Comment by yeezy69** [comment]
I tried with changes from commit 1c2a475, but it didn't work for me :(

**Comment by UtechtDustin** [comment]
@yeezy69 it should work.
Here is your example with the fix: https://live.bootstrap-table.com/code/UtechtDustin/9578

**Comment by yeezy69** [comment]
Can i use the changes from commit 1c2a475 in 1.19.0 or must i use the complete dev version?

**Comment by UtechtDustin** [comment]
To be sure, you should use the compiled 1.19.0 + fix version.
@wenzhixin could you release the fixed vesion 1.19.1 ?

**Comment by yeezy69** [comment]
Strange. I checked again but this change doesn't work for me. Now i'm waiting for 1.19.1.
```
--- /tmp/utils.js	2021-11-10 03:33:58.000000000 +0100
+++ /mnt/nfs/beta/js/utils-1.19.0-fix.js	2021-11-10 22:02:41.733730888 +0100
@@ -2150,9 +2150,9 @@
 
       $__default['default'].each(header.find('th'), function (i, th) {
         var $th = $__default['default'](th);
-        $th.find('.filter-control').remove();
 
         if ($th.data('field') === column.field) {
+          $th.find('.filter-control').remove();
           $th.find('.fht-cell').append(html.join(''));
           return false;
         }
```

**Comment by yeezy69** [comment]
another bug or maybe that's related: with server-side data, the input-fields are empty after searching.

See this example: https://live.bootstrap-table.com/code/yeezy69/9585

Type a number into "price" field, wait for search, all datasets with number will shown but the number is deleted from the input field.

**Comment by wenzhixin** [comment]
> To be sure, you should use the compiled 1.19.0 + fix version. @wenzhixin could you release the fixed vesion 1.19.1 ?

OK.

**Comment by yeezy69** [comment]
Please can you check the problem that the input-fields are empty after searching, as i described above? or should I better open a new ticket?

**Comment by UtechtDustin** [comment]
ref #5828
