### ISSUE TITLE
data-filter-control does not style correctly

### ISSUE THREAD

**Issue by msmeldrum** [wenzhixin/bootstrap-table#5934]
### Bootstraptable version(s) affected

1.18.0

### Description

When using Bootstrap V5 and using the data-filter-control, if you add a data filter to a table header using data-filter-control="select", the dropdown arrow does not show up in the rendered HTML.  This is because Bootstrap V5 changed the class for a select element to "form-select" and the data-filter-control creates the select element using the Bootstrap V4-compatible "form-control" class.

### Example(s)

https://live.bootstrap-table.com/code/msmeldrum/9596

### Possible Solutions

Change /src/extensions/filter-control/bootstrap-table-filter-control.js to render the select element with the form-select class instead of the form-control class when the target Bootstrap version is V5

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by msmeldrum** [comment]
Live example referenced

**Comment by UtechtDustin** [comment]
The cause is that the placeholder elemtn `no-filter-control` will be added multiple times.
I'm not sure if we really need it, i guess we can use `vertical-align` instead.
