### ISSUE TITLE
Table display bug when open in responsive mode (Mobile)

### ISSUE THREAD

**Issue by cpx2017** [wenzhixin/bootstrap-table#5936]
### Bootstraptable version(s) affected

1.19.0

### Description

[See Screenshot](https://ik.imagekit.io/cpxstorage/Bug/Capture_qf5a_TQB-.PNG?updatedAt=1636534721795)

When I test responsive mode (phone size). Webpage will be display like this. What's a problem?
Also you can test it at [This link](https://cpxpreordersim.azurewebsites.net/shop/list). Please open on mobile size to see problem clearly.

**Comment by UtechtDustin** [comment]
Thank you for the report, it seems there is a missing `overflow: hidden`.
We will check that!

**Comment by cpx2017** [comment]
Okay, I use this library with CDN link. If problem is solved. Please let me know.

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/), your example is not avaible.

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we get no response from you. If you still need help please just provide the example and we will reopen the issue.
