### ISSUE TITLE
Event handler on detail view element not working

### ISSUE THREAD

**Issue by amhassen97** [wenzhixin/bootstrap-table#5937]
### Description

I have an event handler for a button click. However, the button is only part of the detail view when expanded.

The event handler is declared correctly, however when the button inside the detail view is clicked, nothing happens.. please assist.

Thank you

### Example(s)

https://live.bootstrap-table.com/code/amhassen97/9573

**Comment by UtechtDustin** [comment]
The button is not rendered yet, which means you can't bind a event on it directly.
You have two options:

- Use the [expandRow](https://bootstrap-table.com/docs/api/events/#onexpandrow) event and then add a event.
- Bind the event to the table with a listener to a selector, as example: https://live.bootstrap-table.com/code/UtechtDustin/9577

Depending on your usecase one of the two option could be better then the other one.

**Comment by amhassen97** [comment]
Cool thanks for the explanation and help! The second option was better for me and worked.

I unintentionally also realized by binding the event inside the detail formatter function, the event also gets triggered.

**Comment by UtechtDustin** [comment]
No problem, your welcome!
