### ISSUE TITLE
Filter-control extension is broken

### ISSUE THREAD

**Issue by zhaoou** [wenzhixin/bootstrap-table#5938]
### Bootstraptable version(s) affected

1.19.0

### Description

The data-filter-control="input" doesn't work again

It's not generating the input field, not even on the official example page. The select option is working fine. The container for the filter input is missing

<tr>
      <th data-field="id">ID</th>
      <th data-field="name" data-filter-control="input">Item Name</th>
      <th data-field="price" data-filter-control="select">Item Price</th>
    </tr>

I'm using the latest release (1.19.0).

### Example(s)

https://live.bootstrap-table.com/example/extensions/filter-control.html

**Comment by yeezy69** [comment]
see #5933

**Comment by UtechtDustin** [comment]
@wenzhixin will release a new version with the fix.
ref #5933
