### ISSUE TITLE
Broken filter-control extension in latest version

### ISSUE THREAD

**Issue by martinbarilik** [wenzhixin/bootstrap-table#5940]
### Bootstraptable version(s) affected

1.19.0

### Description

The latest update have broken filter-control extension, multiple filter controls won't work in table ( only one is working ). Also "input" value is not supported. 

Some serious issue, can't say what is up, but it's not good even in docs

### Example(s)

In dosc, filter control is set to name and price, only price is working.

https://examples.bootstrap-table.com/index.html#extensions/filter-control.html

live demo also, two columns set, only select working:

https://live.bootstrap-table.com/code/martinbarilik/9593

**Comment by UtechtDustin** [comment]
@wenzhixin

ref #5938
ref #5933

**Comment by UtechtDustin** [comment]
Thank you for the report, this issue is already fixed and @wenzhixin will release a new version soon!

**Comment by martinbarilik** [comment]
ah thanks, i was searching in open bugs, it's already closed that's why i didn't see it

**Comment by martinbarilik** [comment]
What "soon" means exactly ? ;) waiting for 3 months already

**Comment by UtechtDustin** [comment]
The [new Version](https://github.com/wenzhixin/bootstrap-table/releases/tag/1.19.1) was released 1 day after i said we release a new version soon.

You're example with the newest version also seems working fine or do i miss something ?
Example: https://live.bootstrap-table.com/code/UtechtDustin/10547

**Comment by martinbarilik** [comment]
I am trully sorry, you are right.
