### ISSUE TITLE
grouping and summary

### ISSUE THREAD

**Issue by fgvicente** [wenzhixin/bootstrap-table#595]
Is there any way to do grouping and summing values? now or in the future?

**Comment by djhvscf** [comment]
Do you mean something like this: http://jsfiddle.net/L6tm1tt3/ ? (See this PR: https://github.com/wenzhixin/bootstrap-table/pull/587 ) @fgvicente

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/index.html

**Comment by fgvicente** [comment]
excelent
