### ISSUE TITLE
Is there a way to select items in a table by URL?

### ISSUE THREAD

**Issue by typo3ua** [wenzhixin/bootstrap-table#5950]
### Description

I need to display the data in the table at the current URL

### Example(s)

For example ... I have the table something like this...

```
<table
  id="table"
  data-toggle="table"
  data-height="460"
  data-pagination="true"
  data-url="data/all.json">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
</table>
```
...and when I go to this link
https://www.bootstrap.table/index.html?id=1 
or 
https://www.bootstrap.table/my-table/?id=1
I expect to see table with item where ID=1... something like this...
```
---------------------------
| Id | Name       | Price |
---------------------------
| 1  | Item name  | $100  |
---------------------------
```

**Comment by djhvscf** [comment]
At this moment that is not supported.

What's your idea when the page loads? The row is highlighted?

**Comment by wenzhixin** [comment]
`check` method can solve your problem: https://live.bootstrap-table.com/code/wenzhixin/9615
