### ISSUE TITLE
Secure Cookie Attribute

### ISSUE THREAD

**Issue by narfk** [wenzhixin/bootstrap-table#5956]
### Description

Is it possible to set the attribute secure: true when HTTPS is active if Cookie (https://examples.bootstrap-table.com/index.html?bootstrap5#extensions/cookie.html) is used?

@see https://owasp.org/www-community/controls/SecureCookieAttribute
@see https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

Thanx
narfk

**Comment by UtechtDustin** [comment]
We already have this feature implement, just set [cookieSecure](https://bootstrap-table.com/docs/extensions/cookie/#cookiesecure) to `true`.
Example: https://live.bootstrap-table.com/code/UtechtDustin/9732
