### ISSUE TITLE
Change page after refresh does not keep query

### ISSUE THREAD

**Issue by lfrodrigues** [wenzhixin/bootstrap-table#596]
First thanks for your great component!

I'm using the table to show results of a database table query with a filter. If I do 
```$('#application-table').bootstrapTable('refresh', {query: query});``` the table shows the 1st page and correct number of pages but if I change page it uses standard url and not my query. 

Can you please help me to do this?

**Comment by wenzhixin** [comment]
You can use the `requestParams` function.

**Comment by lfrodrigues** [comment]
Thanks for you fast reply!
Just in case somebody finds this ticket the correct name is queryParams

**Comment by wenzhixin** [comment]
Updated.

**Comment by priyaVikas** [comment]
Hi,

I am trying to refresh my page by sending parameters to the url.
The user can pick a date range and click on refresh.

 $table.bootstrapTable('refresh', {
                url: 'api/book/salesrep/count',
                queryParams: {from: '03/01/2015', to: '03/01/2015'}

This doesnt seem to work. What am I doing wrong?

**Comment by wenzhixin** [comment]
Hi @priyaVikas , the param is `query`, not `queryParams`: http://bootstrap-table.wenzhixin.net.cn/documentation/#methods
