### ISSUE TITLE
cookie + filter-control extension

### ISSUE THREAD

**Issue by yeezy69** [wenzhixin/bootstrap-table#5960]
### Bootstraptable version(s) affected

1.19.1

### Description

With commit a4d2918 from pull request #5959 the filter-control extension works again. Before this commit, the input-fields lost the text entered, and select-fields lost the selected value. See bug #5828.

But now in conjunction with the cookie-extension, the select-fields didn't remember his value:

![2021-11-21 15-48-40](https://user-images.githubusercontent.com/22444686/142766793-edbd7514-59ab-44aa-99bd-d975ecaa9479.gif)

In my Online-Editor Example you have to input "a4d2918" as GitHub src branch in Libaries.

### Example(s)

https://live.bootstrap-table.com/code/yeezy69/9673

**Comment by djhvscf** [comment]
This is fixed in: https://github.com/wenzhixin/bootstrap-table/pull/5583

Example with fix: https://live.bootstrap-table.com/code/djhvscf/9696

**Comment by albfan** [comment]
I found a corner case for this:

If you reuse the table to show different data (like toggling with a dropdown)

![filter+cookie+reuse-table](https://user-images.githubusercontent.com/220968/164115198-c4d1665e-f9d2-4883-ae0d-07dba9b0bcd1.gif)

https://live.bootstrap-table.com/code/albfan/11219

you can see that search text is correctly handling on change, but filter columns are always stored as last value set. There're some timeouts triggered on off event handlers that trigger cookies for all tables to store last value

here I use same columns and data, but it fails just if column is the same.


You can see search text changes from 19 and 21 between tables, but columns filter name which is 8 for tableA, once modified to 5 in tableB keeps that value after return to tableA
