### ISSUE TITLE
Do not process attribute?

### ISSUE THREAD

**Issue by LeadMagnet** [wenzhixin/bootstrap-table#5961]
### Description

I'm integrating this into a project that has third-party plugins which use tables for layout.

If I use boostrap-table, I get a javascript error because these table are strangely structured. There's nothing I can do to change this.

Is there an attribute that tells bootstrap table "don't do anything to this table"?

**Comment by UtechtDustin** [comment]
I'm quite confused what do you try to achieve.
If you want to tell the bootstrap-table to do nothing, why do you use the BT ?

We need more information and a example (using our [editor](https://live.bootstrap-table.com/)) would also help.

**Comment by LeadMagnet** [comment]
Basically, the company uses DevExpress navigation controls in a WebForms environment. The way DX structures their nav menus us using multi-nested tables, which when rendered first, causes an issue with boostrap in general.

Managed to convince "the powers that be" to stop using DevExpress in favor of bootstrap.

Problem solved :D
