### ISSUE TITLE
Enable/disable GroupBy Extension via button

### ISSUE THREAD

**Issue by riskersen** [wenzhixin/bootstrap-table#5965]
### Description

Disclaimer: I couldnt find an option for that in the documentation and I'm not really experienced with JS, so I'm just asking..

I would like to give the user the possibility to enable/disable grouping of columns, e.g. with the help of a button.

Is that possible somehow?

**Comment by UtechtDustin** [comment]
Do you mean something like this: https://live.bootstrap-table.com/code/UtechtDustin/9772 ?

**Comment by riskersen** [comment]
I see, you are simply disabling the groupby option.. thanks, that would work!
