### ISSUE TITLE
Change ajaxOptions Header on refresh

### ISSUE THREAD

**Issue by MathiasCClausen** [wenzhixin/bootstrap-table#5972]
### Description

Hi,

I am trying to change the header in ajaxOptions when refreshing since I want to refresh the old token, but Bootstrap Table keeps sending the old token as authorization parameter.
How can I change the ajaxOptions before refreshing?

**Comment by UtechtDustin** [comment]
Please provide an example (using our [editor](https://live.bootstrap-table.com/)) what do you tried.
It should work fine if you write the token in a hidden input and in the ajaxOptions function you read the token from the hidden input.

**Comment by MathiasCClausen** [comment]
I am reading/setting the token from session storage and I can see that the token is updating, however the table keeps refreshing with the old token. I am calling a method to get the id token from session storage when loading the bootstrap table

**Comment by UtechtDustin** [comment]
As i said, please provide us an example.

**Comment by MathiasCClausen** [comment]
I am sorry, but I can't really provide an example due to security concerns..
However I can see now that the reason that the token is not getting updated, is because the refresh method takes the parameters from when the table was initialized. I can force the table to use the updated auth token, however it requires that i attach an onRefresh handler with jquery and then call refreshOptions on the table. This makes the table do requests, which is not favorable.. If there was any way I could make the table use the new token when refreshing would be great!

    $('#' + table).on('refresh.bs.table', function (params) {
        $('#' + table).bootstrapTable('refreshOptions',{
            ajaxOptions: { headers: { 'Authorization': 'Bearer ' + getIDToken()} }
        });        
    });

**Comment by UtechtDustin** [comment]
Just as hint, you don't need to use production data for an example.

Please check this example: https://live.bootstrap-table.com/code/UtechtDustin/9784
Open the network tab and check the first request, the token `token_old` will be send on the header `X-CustomHeader` (Replace this with your `Authorization` header, just a placeholder for the example).
Now click on the `change token` button and the  on the refresh button.
Check again the network tab and the new request, the new token `token_changed` will be send.

**Comment by MathiasCClausen** [comment]
Oh! I did try that, but I didn't delete the ajaxOptions defined when initializing the table. Which meant that the table kept refreshing with the old ajaxOptions i had defined.. doh!
Thanks for the help!
