### ISSUE TITLE
How to add value and change name of checkbox?

### ISSUE THREAD

**Issue by hy-net** [wenzhixin/bootstrap-table#5975]
### Description

```
	$("#myTable").bootstrapTable({
		pagination: false,
		data: myData,
		columns: [
			{ field: 'orderID',			title: '',						sortable: false,	width: "25px",	checkbox: true },
			{ field: 'orderNumber',		title: '@RRes.Rst_OrderNo',		sortable: true,		width: "100px" }
		]
	});
```

And it creates a checkbox like this:

```
	<td class="bs-checkbox " style="width: 25px; "><label>
		<input data-index="0" name="btSelectItem" type="checkbox">
		<span></span>
		</label>
	</td>
```

However, I would like to change the name of btSelectItem to something else, and also add a value attribute to the input element.

Thanks

**Comment by hy-net** [comment]
I have more than one Bootstrap Table in my page, so that I need to have different name for checkbox.

Besides, I need to have a value='my-value' so that I can get what the use has selected easily.

The document below says that it is possible.

https://bootstrap-table.com/docs/api/column-options/

It says

"If a value is given the Checkbox is automatically checked" <= is this referring to the value attribute?

**Comment by wenzhixin** [comment]
The [`selectItemName`](https://bootstrap-table.com/docs/api/table-options/#selectitemname) option can solve your problem.
Example: https://examples.bootstrap-table.com/#options/id-field.html

**Comment by UtechtDustin** [comment]
@hy-net oh okay, then i missunderstood you're use-case.
As @wenzhixin already wrote, you can use the `selectItemName` option.
Just as hint: we also have a method called [getSelections](https://bootstrap-table.com/docs/api/methods/#getselections) which returns the selected rows.

**Comment by hy-net** [comment]
@wenzhixin @UtechtDustin Thanks for the info. It works as expected.
