### ISSUE TITLE
Double headers for 1.6.0

### ISSUE THREAD

**Issue by Ajitweb** [wenzhixin/bootstrap-table#598]
I was using version 1.0.6 without any problem. 
I upgraded to 1.6.0 and I am getting double headers

I am using ASP.NET MVC, modal windows, with latest bootstrap.

**Comment by djhvscf** [comment]
Do you have any fiddle? @Ajitweb

**Comment by Ajitweb** [comment]
I am using Dmitry's TwitterbootstrapMVC to generate the HTML - so it will be difficult to fiddle it.
The Double headers do not appear in 1.0.6 version. But it appears from the next version onwards.
Whats strange is the headers appear normal when the modal is first loaded. Any subsequent attempts to bring up the modal will show the double headers. I also feel that the screen flickers a bit at the header. There is something going on there.

As nobody else seems to be having this problem - it is obvious that I screwed it up somewhere..

I was perfectly ok with 1.0.6 version - but I needed the cellStyle functionality which is not there in 1.0.6.
If I can get the js code to implement the cellStyle in 1.0.6 then I can continue with my rest of my development till I get time and come back to visit this double header problem.

**Comment by Ajitweb** [comment]
Ok - So I have implemented the cellStyle functionality in 1.0.6 - that will help me for the time being in my project.

Here is the fiddle for 1.0.6 for cell colors.

http://jsfiddle.net/epn70s0y/3/

**Comment by rpo6ap** [comment]
same here, 1.6.0. double headers in firefox, all normal in chrome
![header_chrome](https://cloud.githubusercontent.com/assets/5356513/6687199/d5ba6f04-cca8-11e4-99ed-1e5e42a59d65.png)
![header_firefox](https://cloud.githubusercontent.com/assets/5356513/6687200/d5bd99ae-cca8-11e4-9c3a-e7dd4c35b3f7.png)
