### ISSUE TITLE
Switching data between two rows

### ISSUE THREAD

**Issue by amhassen97** [wenzhixin/bootstrap-table#5985]
### Description

Hi

I am trying to switch data between two rows in order to implement a sorting feature (i.e. to move data in the table up and down on button clicks)

I manage to grab the data from the table correctly, however when I attempt to update the rows being changed or moved around, it either only updates one row, or both rows that are updated get appended as duplicates at the index.

I have attempted this with remove row by unique id as well as update row but the behaviour is not consistent. I have attached an example using update row since that is more concise and simple.

### Example(s)

https://live.bootstrap-table.com/code/amhassen97/9882

**Comment by wenzhixin** [comment]
You need to copy the row data instead. 
https://live.bootstrap-table.com/code/wenzhixin/10808
