### ISSUE TITLE
Unnecessary horizontal scrollbar when result set is smaller than fixed height

### ISSUE THREAD

**Issue by mariokehl** [wenzhixin/bootstrap-table#5986]
### Bootstraptable version(s) affected

1.19.1

### Description

If the table contains a static tbody or from data/URL and not enough data is fetched the latest version of Bootstrap Table shows a horizontal scrollbar, even the data could fit into the viewport easily. Loading the data via API method `$bsTable.bootstrapTable("load", data.rows);` causes the problem, too. As soon as i set the attribute `data-url="json/data1.json"` in the example the problem disappears (because there is a large amount of rows in this example file).

**UPDATE:** Another discovery i made right now is that if the row count exceeds the fixed height the scrollbar will disappear. So maybe the problem occurs only if there are minor rows in the result set apart from the retrieval method.

<img width="826" alt="scrollbar" src="https://user-images.githubusercontent.com/8313644/145207526-4302a576-6ef3-4893-8f27-697262dc4971.png">

### Example(s)

Scrollbar (tbody, no remote URL): https://live.bootstrap-table.com/code/mariokehl/9890
Scrollbar (from data): https://live.bootstrap-table.com/code/mariokehl/9892
No scollbar (large number of results + remote URL is used, set `data-height="1000"` and the scrollbar will apear again): https://live.bootstrap-table.com/code/mariokehl/9891

### Additional Context

This affects only Windows systems, browser version doesn't matter. I've checked latest versions of Firefox 94, Chrome 96 running on Windows 10. Personally i'm using macOS Monterey 12.0.1 where the problem doesn't occur anywhere.

**Comment by UtechtDustin** [comment]
I close this issue because its already more than a half year old and it also seems that bug is fixed in the newest version.
If the issue still persists please provide a example with the scrollbar.

**Comment by markushiller1985** [comment]
The problem still exists in the newest version. In order to solve it, add these classes to the refreshOptions

$(id).bootstrapTable('refreshOptions', {
            classes: 'table table-striped table-sm table-hover'
        });

Now the scrollbars do not appear anymore.
