### ISSUE TITLE
Filtering (if we delete one filtering column and it isn't confirmed by enter -> filter conditions are not changed)

### ISSUE THREAD

**Issue by doupov** [wenzhixin/bootstrap-table#5987]
https://user-images.githubusercontent.com/9618521/146459819-eab5d7c1-59b6-4de0-9749-860ccda1b41c.mov

### Description

Filtering (if we delete one filtering column and it isn't confirmed by enter -> filter conditions are not changed)
I using table-filter-control
My configuration
data-side-pagination="server"
data-search-on-enter-key="true"
Is possible send request to server on enter key all filters?

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by UtechtDustin** [comment]
I'm closing this issue, because we got no example from you.
Also i can't reproduce the issue, its working fine for me (see the video).
If you still need help with this, please let us know.

https://user-images.githubusercontent.com/13292481/168389652-463c8356-0d84-4189-85ef-56e080605343.mp4
