### ISSUE TITLE
cellStyle

### ISSUE THREAD

**Issue by Ajitweb** [wenzhixin/bootstrap-table#599]
http://jsfiddle.net/wenyi/e3nk137y/9/
works!

But when I put it in my project, it does not call the cell style function. I put a alert in the function which is not being called. 
I am using the formatter function which is being called correctly. but cell-style does not work.

I tried it both in 1.0.6    and 1.6.0   and in all browsers.
Any clues?

**Comment by Ajitweb** [comment]
Update : It now works with the 1.6.0. I am not sure the exact reason why it was not working yesterday. Maybe a restart of the PC solved it.

Thanks.

**Comment by wenzhixin** [comment]
Have fixed this issue: https://github.com/wenzhixin/bootstrap-table/issues/221
