### ISSUE TITLE
Server side templating

### ISSUE THREAD

**Issue by decebals** [wenzhixin/bootstrap-table#5990]
### Description

My question is related somehow with https://github.com/wenzhixin/bootstrap-table/issues/2374.
The problem domain is the same: I am using a server side template engine to render HTML (conditional formatting, ..) and I want to use ajax for server side pagination.
The final solution presented in https://github.com/wenzhixin/bootstrap-table/issues/2374 is particular in my opinion and it doesn't respect the initial domain problem ("instead of having Twig render the HTML I wrote a JS function to do it").
Is it a possibility to use the the HTML fragment returned by server (list of <tr>s ) in ajax?
I prefer to not move the rendering task from server side on the client side.
Other question (probably not so smart :)) is it a possibility to use a non ajax pagination (a compromise)?

Thanks!

**Comment by wenzhixin** [comment]
Maybe this extension can help.
https://bootstrap-table.com/docs/extensions/defer-url/

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by UtechtDustin** [comment]
We don't got any response from you.
We will close this issue for now. If you still need help and the defer-url extension don't help, please let us now.
