### ISSUE TITLE
Function to execute before placing data in table

### ISSUE THREAD

**Issue by saleh-esmaili** [wenzhixin/bootstrap-table#5995]
Function to execute before placing data in table. I have a column that contains 0's and 1's that they should map to enable and desable. is there any feature that can do this?! Thanks!

**Comment by UtechtDustin** [comment]
I assume you are searching for the column option [formatter](https://bootstrap-table.com/docs/api/column-options/#formatter).

**Comment by saleh-esmaili** [comment]
Thanks! That is what I was looking for!
