### ISSUE TITLE
virtual-scroll.bs.table ERROR

### ISSUE THREAD

**Issue by szpetny** [wenzhixin/bootstrap-table#5997]
### Bootstraptable version(s) affected

1.19.1

### Description

Having virtual scroll enabled in table and scrolling down, beyond number of already generated rows, you can see errors in the browser console:

(this stacktrace comes from Firefox, Windows OS)
Uncaught TypeError: this.options[t.EVENTS[a]] is undefined
    value https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10
    callback https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10
    n https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10
    t https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10
    value https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10
    value https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10
    bootstrapTable https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10
    jQuery 2
    bootstrapTable https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10
    <anonymous> https://live.bootstrap-table.com/code/szpetny/8639:86
    jQuery 9
    <anonymous> https://live.bootstrap-table.com/code/szpetny/8639:85
    jQuery 13

### Example(s)

How to reproduce:

1. Press 'Load 10000 rows' button
2. Grab the scrollbar and move it completely down
3. Check browser console

https://live.bootstrap-table.com/code/szpetny/9988

### Additional Context

perhaps this is related to another bug regarding virtual scroll I reported:
https://github.com/wenzhixin/bootstrap-table/issues/5831

**Comment by ChaosEngine** [comment]
I see the same behavior

**Comment by ChaosEngine** [comment]
On page https://examples.bootstrap-table.com/index.html#welcomes/large-data.html after appending 10000 rwos
it manifests like this:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'apply')
    at t.value (bootstrap-table.min.js:10:96413)
    at t.callback (bootstrap-table.min.js:10:89567)
    at HTMLDivElement.n (bootstrap-table.min.js:10:50414)
value @ bootstrap-table.min.js:10
callback @ bootstrap-table.min.js:10
n @ bootstrap-table.min.js:10
```
![image](https://user-images.githubusercontent.com/1271428/151667587-72804079-dc82-4e9b-8a7d-76f16195396e.png)
