### ISSUE TITLE
自动判断如果是date类型默认格式输出

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#600]
默认/Date(1424016000000)/这类格式实在无法接受，虽然可以自动formate来实现，但日期类型的字段太常用了，建议把格式化输出集成进去

**Comment by wenzhixin** [comment]
可以考虑增加插件，欢迎 PR：https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/sorting

**Comment by neozhu** [comment]
那如果我要加一个data-formate=‘datetime’ or ‘date’ or ‘mony’ Tag 要怎么扩展 ，有样列吗，让我参考一下，

**Comment by wenzhixin** [comment]
还是先用 moment.js 来处理吧，#612
