### ISSUE TITLE
Memory leakage for detached DOM

### ISSUE THREAD

**Issue by PH8919** [wenzhixin/bootstrap-table#6000]
### Description

Hi,
I used this lib in my application. When I analyze the memory usage, I found there are some abnormal reference for the detached Div.  I construct a table,  then I destroy it with `$table.bootstrapTable('destroy')`. At this time, I took a snapshot of memory in DevTools of Google broswer(Sorry to that I can't upload the detailed picture). There are some detached DIV which are referred by the 'resize' event of jquery through bootstrap table. Then I checked the source code and found below snap:

`var resizeEvent = Utils.getEventName('resize.bootstrap-table', this.$el.attr('id'));
	      $(window).off(resizeEvent);
	      if (!this.options.showHeader || this.options.cardView) {
	        this.$header.hide();
	        this.$tableHeader.hide();
	        this.$tableLoading.css('top', 0);
	      } else {
	        this.$header.show();
	        this.$tableHeader.show();
	        this.$tableLoading.css('top', this.$header.outerHeight() + 1); // Assign the correct sortable arrow

	        this.getCaret();
	        $(window).on(resizeEvent, function () {
	          return _this2.resetView();
	        });
	      }`
There name space of 'resize.bootstrap-table' is used and register 'resize' event on window if the showHeader in option is true and cardView is false(or null). But when the table is destroy, the event on this name space isn't deregistered.
Plz check it!

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by UtechtDustin** [comment]
The PR #6155 will fix this, but i don't know how do you find that.
It's only ONE even't which is not unregistered, so there is no huge memory leak.

**Comment by PH8919** [comment]
Hi guys,
You can use https://live.bootstrap-table.com/example/methods/destroy.html to check this issue. After you click the 'destroy' button. you can capture the memory snapshoot under chrome or edge in development tool. Then you search the "Detached HTMLTableCellElement". In my application, there are two referenced paths:
One refrenced path is:
_[8] at Detached HTMLTableCellElement@788813✀
[6] at Detached HTMLTableRowElement@788839✀
[5] at Detached HTMLTableSectionElement@789429✀
[0] at k.fn.init@946899jquery-3.4.1.min.js
$body at d@814001bootstrap-table-fixed-columns.min.js
t at system / Context@816115
context at ()@816821🗖bootstrap-table.min.js
handler at Object@814735🗖 
[0] at Array@814733🗖
resize at Object@820637🗖
events at Object@820635🗖 
jQuery341098747506602789351 atWindow_
The other is(this is same to the official path):
_[8] at Detached HTMLTableCellElement@788813✀
[6] at Detached HTMLTableRowElement@788839✀ 
[5] at Detached HTMLTableSectionElement@789429✀
[0] at k.fn.init@946899jquery-3.4.1.min.js
$body at d@814001bootstrap-table-fixed-columns.min.js
t at system / Context@816115 
e at system / Context@813999 
context at html()@817923🗖bootstrap-table.min.js
html at Object@814005🗖 
columns at Object@818175🗖
buttons at Object@854595🗖 
DEFAULTS at t()@820891🗖bootstrap-table.min.js
BootstrapTable at Window_

Thanks
BR

**Comment by PH8919** [comment]
> Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

Hi guys,
You can use https://live.bootstrap-table.com/example/methods/destroy.html to check this issue. After you click the 'destroy' button. you can capture the memory snapshoot under chrome or edge in development tool. Then you search the "Detached HTMLTableCellElement". In my application, there are two referenced paths:
One refrenced path is:
[8] at Detached HTMLTableCellElement@788813✀
[6] at Detached HTMLTableRowElement@788839✀
[5] at Detached HTMLTableSectionElement@789429✀
[0] at [k.fn.init@946899jquery-3.4.1.min.js](mailto:k.fn.init@946899jquery-3.4.1.min.js)
$body at [d@814001bootstrap-table-fixed-columns.min.js](mailto:d@814001bootstrap-table-fixed-columns.min.js)
t at system / Context@816115
context at ()@816821🗖bootstrap-table.min.js
handler at Object@814735🗖
[0] at Array@814733🗖
resize at Object@820637🗖
events at Object@820635🗖
jQuery341098747506602789351 atWindow

The other is(this is similar to the official path):
[8] at Detached HTMLTableCellElement@788813✀
[6] at Detached HTMLTableRowElement@788839✀
[5] at Detached HTMLTableSectionElement@789429✀
[0] at [k.fn.init@946899jquery-3.4.1.min.js](mailto:k.fn.init@946899jquery-3.4.1.min.js)
$body at [d@814001bootstrap-table-fixed-columns.min.js](mailto:d@814001bootstrap-table-fixed-columns.min.js)
e at system / Context@813999 
context at html()@817923🗖bootstrap-table.min.js
html at Object@814005🗖
columns at Object@818175🗖
buttons at Object@854595🗖
DEFAULTS at t()@820891🗖bootstrap-table.min.js
BootstrapTable at Window

@Version v1.21.0

Thanks
BR
