### ISSUE TITLE
Table Toolbar extension top-right "X" button: wrong look and not responsive with Bootstrap 5

### ISSUE THREAD

**Issue by realraec** [wenzhixin/bootstrap-table#6001]
### Bootstraptable version(s) affected

1.19.1

### Description

(First bug report, I hope I'm doing this right. If not, my apologies, and please let me know.)

The Table Toolbar extension of BootstrapTable is not fully compatible with Bootstrap 5 since the top-right "X" (close) button does not look right, and does nothing when clicked.

### Example(s)

No need for a custom live example, the bug happens on the live demo on the official website:
https://examples.bootstrap-table.com/index.html?bootstrap5#extensions/toolbar.html

### Possible Solutions

No idea exactly, but the button looks right and performs the desired action with Bootstrap 4:
https://examples.bootstrap-table.com/index.html#extensions/toolbar.html

**Comment by UtechtDustin** [comment]
> (First bug report, I hope I'm doing this right. If not, my apologies, and please let me know.)

You did anything correct, thansk for your bug report.
We will check that!

**Comment by wenzhixin** [comment]
Fixed in #6070
