### ISSUE TITLE
Filter select controls do not populate when data height defined 

### ISSUE THREAD

**Issue by willbjones** [wenzhixin/bootstrap-table#6004]
### Bootstraptable version(s) affected

1.19.1

### Description

When specifying a height, the select elements in filter controls appear empty.

### Example(s)

[](https://live.bootstrap-table.com/code/willbjones/10037)
https://live.bootstrap-table.com/code/willbjones/10037

**Comment by UtechtDustin** [comment]
Thank you for the report, the bug is fixed in #5583
Example: https://live.bootstrap-table.com/code/UtechtDustin/10038
