### ISSUE TITLE
Usage of clearFilterControl method in filter control extension

### ISSUE THREAD

**Issue by RMkuzmi** [wenzhixin/bootstrap-table#6009]
### Description

Here you say about it:
https://github.com/wenzhixin/bootstrap-table/blob/develop/site/docs/extensions/filter-control.md#clearfiltercontrol

But I doesn't understand how to use this method. Can you provide some example?

**Comment by UtechtDustin** [comment]
Example: https://live.bootstrap-table.com/code/UtechtDustin/10101
Write something in the filters and click on the `clear filter`  button.
