### ISSUE TITLE
How can I filter search child info  with treegrid？

### ISSUE THREAD

**Issue by IM-possilbe** [wenzhixin/bootstrap-table#6019]
### Description

I use bootstrap-table treegrid  and enable search in toolbar 
and all child node expand by default ,but when I input key word in search-input on toolbar , can only search root node row,
how can I get all row include child node row ?
Thanks

![image](https://user-images.githubusercontent.com/36387531/148346404-e2c42068-e157-4ae0-aa8a-4208937f12ba.png)

**Comment by wenzhixin** [comment]
You can use the `customSearch` to search the child node row: https://live.bootstrap-table.com/code/wenzhixin/10402
