### ISSUE TITLE
Filter-Control select option css problem with BS5

### ISSUE THREAD

**Issue by chsteiner** [wenzhixin/bootstrap-table#6020]
### Bootstraptable version(s) affected

1.19.1

### Description

With Bootstrap 5 and data-filter-control="select" the input field does not show the dropdown-arrow

### Example(s)

https://examples.bootstrap-table.com/index.html?bootstrap5#extensions/filter-control.html

**Comment by jmm13** [comment]
Looking at the code, it seems the select option inserts `<select class="form-control bootstrap-table-filter-control-..."` where it should be `<select class="form-select bootstrap-table-filter-control-..."`

form-select was one of the new form classes in Bootstrap 5. May have just overlooked here. By changing it as above, it worked for me.

**Comment by UtechtDustin** [comment]
@jmm13 Thank you for debuggin this issue.
