### ISSUE TITLE
sorting by number not working correctly

### ISSUE THREAD

**Issue by Orik22** [wenzhixin/bootstrap-table#6021]
### Bootstraptable version(s) affected

version: 1.3.0

### Description

when i sorting data on table where i have 3 values : 100 99 and 1 first showed 99 then 100 and 1 how get sorts corectly with numeric data?

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by Orik22** [comment]
it's not needed
https://examples.bootstrap-table.com/index.html?bootstrap-tablel
there when if switch to russian language your can see same situation

**Comment by Orik22** [comment]
![screenshot_bootstrap_table](https://user-images.githubusercontent.com/93426733/148902527-70cea6a9-8b08-4b3d-95c5-5c61a747610e.png)

**Comment by Orik22** [comment]
as on screenshot 11 placed beetween 109 and 110

**Comment by wenzhixin** [comment]
It is not a bug. You need to use the `sorter` column option to sort by yourself.
https://live.bootstrap-table.com/example/column-options/sorter.html
https://live.bootstrap-table.com/code/wenzhixin/10397
