### ISSUE TITLE
TypeScript definition has set all icons to mandatory rather than optional

### ISSUE THREAD

**Issue by JJ-M** [wenzhixin/bootstrap-table#6023]
### Bootstraptable version(s) affected

1.19.1

### Description

The TypeScript definition (index.d.ts) has set all icons to mandatory rather than optional, so if you try to add one icon, the TypeScript compiler insists on a reference for all of them. Was this intentional?

Also, in the BootstrapTableLocale interface formatRecordsPerPage is set as mandatory but should also probably be optional.

### Example(s)

From index.d.ts:

interface BootstrapTableIcons{
    toggleOff: string;
    clearSearch: string;
    detailOpen: string;
    search: string;
    fullscreen: string;
    columns: string;
    detailClose: string;
    refresh: string;
    paginationSwitchDown: string;
    paginationSwitchUp: string;
    toggleOn: string
}

### Possible Solutions

interface BootstrapTableIcons{
    toggleOff?: string;
    clearSearch?: string;
    detailOpen?: string;
    search?: string;
    fullscreen?: string;
    columns?: string;
    detailClose?: string;
    refresh?: string;
    paginationSwitchDown?: string;
    paginationSwitchUp?: string;
    toggleOn?: string
}

**Comment by JJ-M** [comment]
I should have added, in the way TypeScript definitions work it is not possible to override the definition that is provided!

**Comment by JJ-M** [comment]
Just hit the same issue with BootstrapTableEvents - all 24 are mandatory, so if you want to add a table column event you have to add all of them so that the TypeScript will compile. I think they should all be optional.

**Comment by wenzhixin** [comment]
@JJ-M PR is welcome.

**Comment by wenzhixin** [comment]
Fixed in #6123
