### ISSUE TITLE
How to select several checkboxes without using ctrl using Multiple Select Row?

### ISSUE THREAD

**Issue by AlexByte** [wenzhixin/bootstrap-table#6026]
### Description

I want to select checkboxes just by clinking on them, as usual, i only want shift+click functionality from multipleSelectRow option.

**Comment by wenzhixin** [comment]
Does the `multipleSelectRow` option maybe solve your problem?
https://examples.bootstrap-table.com/index.html#options/multiple-select-row.html

**Comment by AlexByte** [comment]
I wrote that I want to select multiple rows without the ctrl key.

**Comment by UtechtDustin** [comment]
Duplicate of  #5389.
