### ISSUE TITLE
Toggle Columns in grouped headers

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#6027]
### Bootstraptable version(s) affected

1.18.0

### Description

I'm sorry to duplicate this, but the original ticket has been closed and after months the bug is still there. No PR has been merged apparently.
https://github.com/wenzhixin/bootstrap-table/issues/5637

**Comment by wenzhixin** [comment]
We do not support the case where the `colspan` and `rowspan` of two fields of the same column are both 1.
Workaround for your example: https://live.bootstrap-table.com/code/wenzhixin/10395

**Comment by antonioaltamura** [comment]
Thanks, but that is not really a workaround. To keep it simple and stick with the example, the number of prices available are dynamic in my case. There could be more than one currency, it depends on the product. The `columns` array and consequently `colspan` and `rowspan` are generated dynamically based on the data available.
You can see how this is a problem if the togglability of columns breaks only in case of one currency available.
Also please note this is a simplified example, and this issue is a real pain for us, as we have quite complex and dynamic tables.
