### ISSUE TITLE
Is there a possibility to address the filter via URL? 

### ISSUE THREAD

**Issue by d-brauer** [wenzhixin/bootstrap-table#6031]
### Description

Is there a possibility to address the filter via URL? Or to write in the browser URL when selected?

for example here:
https://examples.bootstrap-table.com/index.html#extensions/filter-control.html

in this form:
https://examples.bootstrap-table.com/index.html#extensions/filter-control.html?search=14&price=12

Also for a donation.

**Comment by wenzhixin** [comment]
Does the addrbar extension maybe help?
https://examples.bootstrap-table.com/#extensions/addrbar.html

**Comment by UtechtDustin** [comment]
I close this issue, because we got no response from you within 7 days.
The `addrbar` extension should help you, as @wenzhixin already wrote.
