### ISSUE TITLE
cosmetic bugs with bs5.1

### ISSUE THREAD

**Issue by mbunal** [wenzhixin/bootstrap-table#6033]
### Bootstraptable version(s) affected

1.19.1

### Description

There are some cosmetic bugs with bs5.1. Table styles are not rendering as they should in bs5.1. When will you fix this bug?

**Comment by UtechtDustin** [comment]
Would be good if you could improve the description of the issue.
You wrote that the styles are not rendering as it should, but which style, with which setup, in which browser(s) ?
Also please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by mbunal** [comment]
https://live.bootstrap-table.com/code/mbunal/10359

**Comment by UtechtDustin** [comment]
As i already said, we need more information about the issue.
The tables in you're example looks good for me.

**Comment by mbunal** [comment]
these are in bs5.1 table:
there is no vertical line.
first 2 column is bold.
there is no border line.

in bsTable with bs5.1:
there are vertical line.
no bold column.
there is border line.

if i use bs4.x or bs5.0 there is no problem. both of table same.

**Comment by UtechtDustin** [comment]
You can overwrite the classes with `data-classes`, you can find a example here: https://live.bootstrap-table.com/code/UtechtDustin/10392

The bootstrap-table always use `<tr>`, so the first 2 columns are not bold.
But you could use some css or the option [cellStyle](https://bootstrap-table.com/docs/api/column-options/#cellstyle) to fix that! :-)

**Comment by wenzhixin** [comment]
You can use `td` and [`.fw-bold`](https://getbootstrap.com/docs/5.1/utilities/text/#font-weight-and-italics) to solve your problem.
https://live.bootstrap-table.com/code/wenzhixin/10393
