### ISSUE TITLE
Pagination First,Prev,Next,Last

### ISSUE THREAD

**Issue by DusanSenior** [wenzhixin/bootstrap-table#604]
Hello,
great work, congratulation. Would you consider changing brands for the first,prev,next and last button on the pagination component? Would be nice to have possibility change "&lt;&lt;" to "&laquo;", "&lt;" to "&lsaquo;"....
Thank you for answer
Best Regards
Dusan sen.

**Comment by djhvscf** [comment]
Ok, it is possible of course, but why should we change it? @DusanSenior

**Comment by DusanSenior** [comment]
In my opinion it looks bit better (one character only), and maybe someone will want to change brands on something completely different - arrows, glyphicons... I know, it has low priority.

**Comment by djhvscf** [comment]
Good idea!! @DusanSenior

**Comment by djhvscf** [comment]
Let me think about it! @DusanSenior but really it is a good idea

**Comment by DusanSenior** [comment]
Thank you.

**Comment by djhvscf** [comment]
Ref to: https://github.com/wenzhixin/bootstrap-table/pull/677
