### ISSUE TITLE
Method to get filtered fields

### ISSUE THREAD

**Issue by simonsolutions** [wenzhixin/bootstrap-table#6040]
### Description

When I filter the data, how can I later get the filtered fields?

$('#table').bootstrapTable('filterBy', {
            fieldName: filterValues,
        });

How to get the fieldName and the Values later again in a different javascript function?

**Comment by wenzhixin** [comment]
I think you can save the filter option in a variable by yourself: https://live.bootstrap-table.com/code/wenzhixin/10415.

**Comment by simonsolutions** [comment]
Okay that is possible until the page reload. when using cookie extension the filter is loaded on page reload but the variable is empty. Is there an event when applying a filter to put the filter condition in the variable?

**Comment by wenzhixin** [comment]
localStorage or sessionStorage?
