### ISSUE TITLE
 column events only apply to first row when row span is set

### ISSUE THREAD

**Issue by tryyoung** [wenzhixin/bootstrap-table#6051]
### Bootstraptable version(s) affected

1.18

### Description

This is my column setting
  {
    field: 'client',
    title: 'Client'
  },{
    field: 'actions',
    formatter: 'actionsFormatter',
    events: {
        'click .delete-host': function (e, value, row, index) {
            var cfg = {title: 'Confirm Deletion', text: 'Are you sure to delete host [' + row['description']  + ']?', ajax: {url: row['urlDelete'], func: hostDeleted}}
            showConfirmDialog(cfg)
        }
    },
    title: 'Actions'
  }

The data of field client has _client_rowspan set, 
finally for every single client, only first row was binded to event.
Is there a workaround?  
Thanks a lot

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by wenzhixin** [comment]
Close this issue. If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!
