### ISSUE TITLE
It looks like fixed-table-body width px with decimal point will cause fixed-table-border height calculation error after setting table height.

### ISSUE THREAD

**Issue by zhangzihang** [wenzhixin/bootstrap-table#6053]
### Bootstraptable version(s) affected

1.19.1

### Description

看起来fixed-table-body的宽度px带小数点会导致设置表高度后fixed-table-border高度计算错误
我查了下网上资料，说scrollWidth的值是四舍五入后的，这样的话，当innerWidth为小数时，即使没有横向滚动条，
innerWidth和scrollWidth的值也不会相同，因为一个带小数一个不带小数，My English is poor，Here is the machine translation.

It looks like fixed-table-body width px with decimal point will cause fixed-table-border height calculation error after setting table height.
I looked it up on the Internet, and it says that scrollWidth is rounded, so that when the innerWidth is a decimal, even without the horizontal scroll bar,
The innerWidth and scrollWidth values are also not the same, because one has a decimal and one doesn't

### Example(s)

https://live.bootstrap-table.com/code/zhangzihang/10531

### Possible Solutions

或许试试element.getBoundingClientRect?

**Comment by wenzhixin** [comment]
看下 PR #6046 是否已经解决了你的问题？

**Comment by zhangzihang** [comment]
> 看下 PR #6046 是否已经解决了你的问题？

解决了，谢谢
