### ISSUE TITLE
Onclick events in the table cells are lost

### ISSUE THREAD

**Issue by nmpetkov** [wenzhixin/bootstrap-table#6054]
### Bootstraptable version(s) affected

1.19.1

### Description

Onclick event specified in the table cells is lost.
Please click in cells in "Stars" column in provided example (noting happens), and see the code - click event works if the table is not hadled by the bootstrap-table plugin.

### Example(s)

https://live.bootstrap-table.com/code/nmpetkov/10540

**Comment by UtechtDustin** [comment]
Please use the [events option](https://bootstrap-table.com/docs/api/column-options/#events).

**Comment by UtechtDustin** [comment]
As i said please use the events option, here is aexample: https://examples.bootstrap-table.com/#column-options/events.html.
The Bootstrap-table don't rebind event's which was binded before.
