### ISSUE TITLE
Footer override page navigation

### ISSUE THREAD

**Issue by magostinelli** [wenzhixin/bootstrap-table#6055]
### Bootstraptable version(s) affected

1.19.1

### Description

If I use a footer fixed at bottom, on mobile view, the footer overlap the page navigation, look at the example

### Example(s)

https://live.bootstrap-table.com/code/magostinelli/10545

**Comment by wenzhixin** [comment]
You can set style to solve the problem: https://live.bootstrap-table.com/code/wenzhixin/10787
