### ISSUE TITLE
data-mobile-responsive not working after destroying the table

### ISSUE THREAD

**Issue by GuilhermeSenna** [wenzhixin/bootstrap-table#6056]
### Bootstraptable version(s) affected

1.19.1

### Description

By applying an external filter for a server side treatment, I need to use .destroy(). After rebuilding the table, it doesn't become more responsive when changing the screen size (flipping Card when shrinking the screen).

This bug only happens when I use .destroy(), after some change that changes the table but doesn't use .destroy, like changing the page or changing the number of records per page, the responsiveness goes back to normal.

### Possible Solutions

Change the view based on the screen size by manipulating the DOM.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by GuilhermeSenna** [comment]
Solved using:

$("#table").bootstrapTable('selectPage', 1)
