### ISSUE TITLE
Unable to set sortable flag via updateColumnTitle()

### ISSUE THREAD

**Issue by antonioaltamura** [wenzhixin/bootstrap-table#6058]
### Description

I would like to be able to enable the `sortable` option in a specific column _after_ I got the results (from the server).
To give a bit of context, I want to enable `sortable` only if the number of results is below a threshold.
It seems `updateColumnTitle` is not the right way, as it doesn't update the `sortable` option.
https://live.bootstrap-table.com/code/antonioaltamura/10565

I also tried `refreshOptions()`, which actually works, but it forces a refresh of the whole table, and that includes an extra remote request to fetch the data, and I would like to avoid that. As a side, if you use `refreshOptions` in `responseHandler` or `onLoadSuccess` you create an endless loop.
https://live.bootstrap-table.com/code/antonioaltamura/10567

### Example(s)

https://live.bootstrap-table.com/code/antonioaltamura/10565

https://live.bootstrap-table.com/code/antonioaltamura/10567

**Comment by antonioaltamura** [comment]
This used to have some discussion going on, not sure what happened since then. Will this be fixed?

**Comment by wenzhixin** [comment]
After the discussion, the `updateColumnTitle` method only updates the column title and is not recommended for adding updates for other configurations. 

Currently, the configuration information of columns can be modified using the `refreshOptions` method, so there is no need to change this method.
