### ISSUE TITLE
live editor is throwing a phishing alert

### ISSUE THREAD

**Issue by djhvscf** [wenzhixin/bootstrap-table#6061]
### Bootstraptable version(s) affected

N/A

### Description

When accessing the live editor the antivirus is throwing a phishing alert

![image](https://user-images.githubusercontent.com/4496763/154808201-4f8da7a6-91df-4b24-9a3e-4f6220425b77.png)

**Comment by UtechtDustin** [comment]
Which antivirus software do you use ?

It seems that the most (important) one dont see any threat there.
https://www.virustotal.com/gui/url/4911ea0acf3ab3972c7a7c954eb3e2af02d5bdd303a0f675d6714929d67eaa7b?nocache=1

**Comment by djhvscf** [comment]
It is not happening anymore. So we can close this issue.
