### ISSUE TITLE
Selecting a radio in one table affects another

### ISSUE THREAD

**Issue by GuilhermeSenna** [wenzhixin/bootstrap-table#6063]
### Bootstraptable version(s) affected

1.19.1

### Description

I have an application where I need to show two tables and both have radio input to select.

When selecting the radio in a table with another already selected, the radio of the other is also deselected.

This shouldn't happen since the tables have different ID's. The CSS when selected remains, but the radio is deselected.

### Example(s)

https://live.bootstrap-table.com/code/GuilhermeSenna/10624

**Comment by MassiGy** [comment]
Hey @GuilhermeSenna ,
I suggest that you first check that your tables are not within the same HTML form.
Massiles.

**Comment by UtechtDustin** [comment]
Please use the option [selectItemName](https://bootstrap-table.com/docs/api/table-options/#selectitemname) to change the names of the radio inputs.
Example: https://live.bootstrap-table.com/code/UtechtDustin/10633

**Comment by GuilhermeSenna** [comment]
Thanks for the help.
