### ISSUE TITLE
Load method removes event handlers from detail view

### ISSUE THREAD

**Issue by kkozlik** [wenzhixin/bootstrap-table#6065]
### Bootstraptable version(s) affected

1.19.1

### Description

When [load function](https://bootstrap-table.com/docs/api/methods/#load) is executed, all event handlers from elements in expanded detail-view stop working.

### Example(s)

https://live.bootstrap-table.com/code/kkozlik/10685

In the example:
- first expand some rows
- than click on the 'Click me' link. You can see that an alert window is displayed
- click the 'Load Data' link
- click on the 'Click me' link again. This time the alert window is NOT displayed

### Possible Solutions

I think that this is because `initBody` function copy expanded rows from the old table to new table just as text html:
https://github.com/wenzhixin/bootstrap-table/blob/1.19.1/dist/bootstrap-table.js#L5708
```js
                if (!updatedUid || itemUniqueId !== updatedUid) {
                  tr += oldTrNext[0].outerHTML;
                }
```
Maybe it would be much better to copy the whole DOM node in this step.

**Comment by wenzhixin** [comment]
I think it's hard to copy the whole DOM node under the current implementation. 
We can use `$(document).on('click', element, fn)` to bind your event to solve the problem.
https://live.bootstrap-table.com/code/wenzhixin/10786
