### ISSUE TITLE
treegrid not supported via data attributes

### ISSUE THREAD

**Issue by ccerrillo** [wenzhixin/bootstrap-table#6068]
### Bootstraptable version(s) affected

1.19.1

### Description

If the table is built from html with data attributes, the extensión treegrid doesn't work

### Example(s)

https://live.bootstrap-table.com/code/ccerrillo/10700

**Comment by wenzhixin** [comment]
Like our example: https://live.bootstrap-table.com/example/extensions/treegrid.html.
You need to init the tree after the `post-body` event. 
https://live.bootstrap-table.com/code/wenzhixin/10764

**Comment by osterchrisi** [comment]
@wenzhixin Is it possible, this is broken right now (again)? The above linked example doesn't work and I myself cannot get treegrid to work either.

**Comment by wenzhixin** [comment]
@osterchrisi the working example: https://live.bootstrap-table.com/code/wenzhixin/15538

Because in this commit: https://github.com/wenzhixin/bootstrap-table/commit/5d80db6bb24e89a6ea84c79d8fc66dd99a5561b1, we fix the treegrid not working bug when the id is text
