### ISSUE TITLE
After the filter, execute the next page, and then execute the updaterow operation to create a new one

### ISSUE THREAD

**Issue by ziqiming** [wenzhixin/bootstrap-table#6069]
### Bootstraptable version(s) affected

1.9.1

### Description

client ：

 After the filter, execute the next page, and then execute the updaterow operation to create a new one

filterBy -> next page -> updateRow -> index(bug)

**Comment by ziqiming** [comment]
client

**Comment by ziqiming** [comment]
I have used the updatebyuniqueid scheme

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by wenzhixin** [comment]
If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!
