### ISSUE TITLE
Empty header

### ISSUE THREAD

**Issue by eco3** [wenzhixin/bootstrap-table#607]
I have a problem with the table header. is there any way to fix that?

```html
    <table data-toggle='table'
           data-class='table table-hover table-condensed'
           data-striped='true'
           data-pagination='true'
           data-page-list="[50, 100, 200, 500]"
           data-page-size="50"
           data-url="<?php echo $url . "func/json.php?search_term=" . $search_term . "&search_type=" . $search_type ?>">
        <thead>
            <tr>
                <th data-field='ID' data-sortable='true'>ID</th>
                <th data-field='Autor' data-sortable='true'>Autor</th>
                <th data-field='Titel' data-sortable='true'>Titel</th>
                <th data-field='Untertitel'>Untertitel</th>
                <th data-field='Aushleihdatum' data-sortable='true'>Aushleihdatum</th>
                <th data-field='Ausleiher' data-sortable='true'>Ausleiher/in</th>
            </tr>
        </thead>
    </table>
```
![bootstraptable_emptyheader](https://cloud.githubusercontent.com/assets/9336616/6586236/4d573e9c-c778-11e4-9cb5-bd16bfa715a1.png)

**Comment by djhvscf** [comment]
Sorry but I don't understand what is the problem. @eco3

**Comment by eco3** [comment]
@djhvscf I postet a picture with it:

https://cloud.githubusercontent.com/assets/9336616/6586236/4d573e9c-c778-11e4-9cb5-bd16bfa715a1.png

If you have look closely you'll see that the header isn't in the first row, but there is still a empty header area.

**Comment by wenzhixin** [comment]
Use `Elements`(like: Chrome, press F12) panel to have a check?

**Comment by djhvscf** [comment]
I think you have to set the showHeader table option to false @eco3

**Comment by wenzhixin** [comment]
This issue is a bug.

**Comment by djhvscf** [comment]
What is the function of the fixed-table-header div?? @wenzhixin

**Comment by eco3** [comment]
@wenzhixin Here is the Elements from Firefox

![FirefoxElements](https://cloud.githubusercontent.com/assets/9336616/6690607/d6ac5eb8-ccc1-11e4-8d52-97d7a421c6f5.png)

**Comment by djhvscf** [comment]
Yes, correct @eco3 I dunno why that DIV is there...  fixed-table-header

**Comment by adamncsu** [comment]
Setting showHeader to false gets rid of it, but it also hides the column names. Alternatively, if you explicitly set data-height, the bug goes away. That's not an option for me, so I just manually hide .fixed-table-header when the table loads. Either way, it's definitely a bug. It shows up on all the examples where data-height isn't set.

**Comment by wenzhixin** [comment]
You can use the [release version](https://github.com/wenzhixin/bootstrap-table/releases) first.
