### ISSUE TITLE
Next version release date?

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#6086]
### Description

More than 4 months since the last release. A lot of bugs have been fixed since, specially for the filter-control plugin. Is there a date plan for the next release ?

**Comment by UtechtDustin** [comment]
@wenzhixin It's you're job :-)
I still think we should release a new version every week/month (maybe via github action or something like that).

**Comment by sdespont** [comment]
@wenzhixin please, could you tell me if you do you plan to release a new version soon?

**Comment by ccerrillo** [comment]
@wenzhixin any update with this?

**Comment by snipe** [comment]
Just chiming in on this one - we’d also love a new release or a way to patch the column cookie issue. 

Thanks so much for an *incredible* library. <3 We’re huge fans over at @grokability!

**Comment by UselessGuru** [comment]
@wenzhixin any update with this?

**Comment by martinbarilik** [comment]
Every day i wake up and say to myself: "This is the day, it must be", but then the day goes by and ... nope.

**Comment by snipe** [comment]
@martinbarilik Don’t do that. Please.

I maintain open source projects and every time someone says something like that on one of my repos, it just sucks the wind out of my sails. 

We’re all trying our best, and if you think you can do better, you can always fork and maintain your own version. We all get a ton of value out of this library and we get it for free. My company sponsors this project via GitHub, and we still don’t do this to them. We’re anxious and excited for a new version, but this isn’t helping.

**Comment by martinbarilik** [comment]
@snipe it was a joke, we all are waiting anxiously to see the update, but until then, we can joke around in here, can't we? 

chill out a bit ;-)

**Comment by snipe** [comment]
Ah, Sorry! Jokes are typically identifiable by them being funny.

These kinds of comments aren’t funny. They’re toxic, and over time can lead to devs not wanting to support their own packages anymore.

Maybe you find it hilarious - a lot of people don’t. Keep the snark to yourself next time.

**Comment by martinbarilik** [comment]
I can feel out of the chars you've written, you aren't having a good day. I leave it here. Have a great easter and better rest of the day.

Team ! Hope to see an update soon, great easter to all contributors ! <3

**Comment by wenzhixin** [comment]
Sorry, I'm busy during this time and don't have much time to check out GitHub. But I'm back now and thank you for your continued interest in the project.

**Comment by wenzhixin** [comment]
v1.20.0 released!

**Comment by snipe** [comment]
Thanks so much, @wenzhixin!
