### ISSUE TITLE
Filter hidden columns

### ISSUE THREAD

**Issue by chsteiner** [wenzhixin/bootstrap-table#6088]
### Description

This almost works but there is one drawback: If you hide a column right away via the data-visible attribute the filter will not work. It will however work if you hide it via the columns toggle button.

Example: https://live.bootstrap-table.com/code/chsteiner/10893

**Comment by wenzhixin** [comment]
Please help check if this issue still exists in the latest version? @djhvscf

**Comment by UtechtDustin** [comment]
If you try to filter the name (in this case the input `surname`) nothing happens.
But if you show and hide the name column and filter the name column afterthat it works fine.
So the bug still exists.

**Comment by djhvscf** [comment]
I don't think this is still happening. In this example it works as expected https://live.bootstrap-table.com/code/djhvscf/11359

**Comment by UtechtDustin** [comment]
@djhvscf i think the bug still exists.
You or me missunderstood the issue.

I understood it as followed: If you have external search input(s) (check his example) and you try to filter the HIDDEN column it don't work. But if you show, then hide the hidden row you can filter the hidden column fine.
So this issue only exists if the column was hidden via data attribute.

You're example don't event filters a hidden column :-)

**Comment by chsteiner** [comment]
@UtechtDustin has got it exactly right. The bug still exists and should definitely be considered as a bug.

**Comment by djhvscf** [comment]
I got it! Yes, I could reproduce it
