### ISSUE TITLE
請問如何使用data-buttons新增一個下拉選單按鈕

### ISSUE THREAD

**Issue by chrisfw791127** [wenzhixin/bootstrap-table#6089]
### Description

我想做一個下拉選單按鈕(如範例)

但我希望它不要在左邊, 而是跟預設的工具列連在一起

雖然data-toolbar-align="right"可以靠右,但中間會有縫隙,怪怪的

試了很久都try不出來 ,請問有辦法達成嗎?

### Example(s)

https://live.bootstrap-table.com/code/chrisfw791127/10935

**Comment by djhvscf** [comment]
Can you translate this issue to english, please?

**Comment by wenzhixin** [comment]
I think the example of @UtechtDustin can solve the problem.
