### ISSUE TITLE
I need to send parameters to refresh a url 

### ISSUE THREAD

**Issue by priyaVikas** [wenzhixin/bootstrap-table#609]
Hi,

I need to be able to refresh a url based on the date range the user enters. This is how my code looks.

$(function () {
        $button.click(function () {
           $table.bootstrapTable('refresh', {
                url: 'api/book/salesrep/count',
                queryParams: {from: '03/01/2015', to: '03/01/2015'}
        });
    });
    });

My java controller code looks like this
@GET
	@Path("/salesrep/count")
	@Produces(MediaType.APPLICATION_JSON)
	public Response getRenewRetentionStats(@Context HttpHeaders headers,
			@QueryParam("from") String startYear,
			@QueryParam("to") String endYear) throws SQLException, ParseException {
		
		Gson gson = new Gson();
		String json = gson.toJson(SalesRepManager.getSalesRepStats(startYear, endYear));
		return Response.ok(json).build();

	}

The values for to and from are always null.
What am i doing incorrectly here?

**Comment by djhvscf** [comment]
What about your table configuration? @priyaVikas

**Comment by djhvscf** [comment]
Please see this example: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/386.html @priyaVikas

**Comment by wenzhixin** [comment]
The docs: http://bootstrap-table.wenzhixin.net.cn/documentation/, I think this issue can be close now.
