### ISSUE TITLE
The search input field trimming trailing space

### ISSUE THREAD

**Issue by rgaufman** [wenzhixin/bootstrap-table#6090]
### Bootstraptable version(s) affected

1.19.1

### Description

When I try searching for something if I add a space, the space is trimmed away.

### Example(s)

https://user-images.githubusercontent.com/33842342/160236406-7d609374-89b9-4c2e-925f-d604e662c0a3.mov

I can also see the search request sent to the server does not have the trailing space I typed, the URL is:

```
https://localhost:3001/agents/table?search=office&offset=0&limit=10&...
```

Any ideas?

**Comment by UtechtDustin** [comment]
Set the [trimOnSearch](https://bootstrap-table.com/docs/api/table-options/#trimonsearch) option to `false` to prevent trimming of the search value.

**Comment by rgaufman** [comment]
Thank you, I changed the code to remove this trim, but your solution is better! 
<img width="865" alt="Screenshot 2022-03-26 at 13 36 08" src="https://user-images.githubusercontent.com/33842342/160249221-accc2319-7400-4047-b90e-fdd47fa6564e.png">
<
