### ISSUE TITLE
"No matching records found" even when there is data

### ISSUE THREAD

**Issue by keslerm** [wenzhixin/bootstrap-table#6092]
### Bootstraptable version(s) affected

1.19.1

### Description

I'm seeing the top message say "No matching records found" even when there is data.

I think it's possibly related to the fact the data load and HTML generation is happening with Mithril.js and the DOM elements are not available already when transforming the table into a bootstrap table?

### Example(s)

https://codepen.io/keslerm/pen/LYeLmGY

**Comment by djhvscf** [comment]
Please use our [Online Editor](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by keslerm** [comment]
@djhvscf I included one for codepen but i copied and pasted it here as well https://live.bootstrap-table.com/code/keslerm/10992

**Comment by UtechtDustin** [comment]
@keslerm can you reproduce it without mithril.js ?
Because we don't support mithril.js right now and im not sure if it popular enough (we can't support every framework).

**Comment by wenzhixin** [comment]
You need to via JavaScript after the view rendering.
Example: https://live.bootstrap-table.com/code/wenzhixin/11332
