### ISSUE TITLE
Sort control in table from HTML with two header rows

### ISSUE THREAD

**Issue by nmpetkov** [wenzhixin/bootstrap-table#6094]
### Description

I enable bootstrap-table from HTML via $('table'). BootstrapTable ().
The HTML code in the header has two lines, the first being the column headers and the second the filtering controls.
Column sorting is on and working, but covers both rows, and should only be in the first row, where the column headings are.
How to sort by clicking only in the cells of the first row in the header?

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by nmpetkov** [comment]
Here is an example:
https://live.bootstrap-table.com/code/nmpetkov/11034

Now I see the problem, which we can divide into two:
1. As you can see, if we provide ```data-sortable="true"``` only in the first header row, sorting does not work in these columns. The first 3 columns are provided in the example.
2. If we provide ```data-sortable="true"``` only in the second header row, then sorting works fine, but the problem is that clicking on the cell in the first header row also sorts (it shouldn't be sorted at all when clicking).
I like to see first 3 columns to sort if click in cells in first header row, and cells in second header row to be as is - not clickable for sorting.

Thak you for your responce!

**Comment by wenzhixin** [comment]
> *field*
> This field must be unique, or some unknown problems may occur.

The plugin does not support this case with the same `colspan` and `rowspan`.
A workaround example: https://live.bootstrap-table.com/code/wenzhixin/11331

**Comment by PedroAugustoRamalhoDuarte** [comment]
@nmpetkov I was facing the same problem, i get a solution with a few extra css and js:
https://live.bootstrap-table.com/code/PedroAugustoRamalhoDuarte/12251
