### ISSUE TITLE
Request body when sending request to get data

### ISSUE THREAD

**Issue by mageshapr** [wenzhixin/bootstrap-table#6095]
### Description

Is is possible to pass in some json in request body when bootstrap table making a request to get data? I'm in need of passing in json object to get the data.

**Comment by UtechtDustin** [comment]
You can overwrite the ajax request [ajax](https://bootstrap-table.com/docs/api/table-options/#ajax).
I guess this should help, right ?

**Comment by wenzhixin** [comment]
Example: https://live.bootstrap-table.com/code/wenzhixin/11327
```js
  data-method="post"
  data-query-params="queryParams"
```
