### ISSUE TITLE
Bootsrtaptable cookie columns dont remember visible:false column, after select from columns options 

### ISSUE THREAD

**Issue by AbdullahKilicarslan** [wenzhixin/bootstrap-table#6098]
### Bootstraptable version(s) affected

1.19.1

### Description

when columns first visible value is false. after select to show column from column options. dont remember last visibile columns

### Example(s)

https://live.bootstrap-table.com/code/AbdullahKilicarslan/11047

### Possible Solutions

bootstrap-table-cookie.js
line 2574
              column.visible = (filteredColumns.length > 0 && column.switchable);

**Comment by wenzhixin** [comment]
Fixed in v1.20.0
https://live.bootstrap-table.com/code/wenzhixin/11326
