### ISSUE TITLE
cannot load json data

### ISSUE THREAD

**Issue by BenJule** [wenzhixin/bootstrap-table#610]
Hi togeher,

# My Files########################################
nodes.json:           http://paste.debian.net/hidden/85d8c632/
getData.html:   http://paste.debian.net/hidden/b9df2a32/
welcome.html   http://paste.debian.net/hidden/10c94b9b/

# Problem ###################################
No matching records found! 

Anyone ideas?

**Comment by djhvscf** [comment]
Ok, let me check! @BenJule

**Comment by BenJule** [comment]
Thanks, for helping. The file "nodes.json" is automatically generated. I can not change the structure.

**Comment by djhvscf** [comment]
I think the problem is that your ,json file is not a flat json.. you can use this extension to do that https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/flatJSON and here is the example: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/flatJSON.html

@BenJule

**Comment by BenJule** [comment]
TypeError: $.fn.bootstrapTable is undefined

@djhvscf

**Comment by djhvscf** [comment]
Ok, let me check again! @BenJule

**Comment by BenJule** [comment]
@djhvscf i have find the trouble. Please check my nodes.json:

2. line "nodes": [

Were can i change the option from "rows": [ to "nodes": [ ?

**Comment by djhvscf** [comment]
I think the flatJSON extension works for you. @BenJule

**Comment by BenJule** [comment]
not realy. i need to change the read option from "rows": [ to "nodes": [ but i dount know, were can i find it :/

**Comment by djhvscf** [comment]
Do you mean change the word "rows" to "nodes" and no change the struture of the json?

**Comment by BenJule** [comment]
:+1:

**Comment by djhvscf** [comment]
Am I correct?

**Comment by BenJule** [comment]
yes

**Comment by djhvscf** [comment]
ok, got it.. let me think what we can do with this problem

**Comment by BenJule** [comment]
the funktion "rows" is not hardcoded?

**Comment by djhvscf** [comment]
Now I'm understanding the problem is related to this line..

data = data.rows;

**Comment by BenJule** [comment]
in file?

**Comment by djhvscf** [comment]
I think is related to this function:

```javascript
BootstrapTable.prototype.load = function (data) {
        var fixedScroll = false;

        // #431: support pagination
        if (this.options.sidePagination === 'server') {
            this.options.totalRows = data.total;
            fixedScroll = data.fixedScroll;
            data = data.rows;
        } else if (!$.isArray(data)) { // support fixedScroll
            fixedScroll = data.fixedScroll;
            data = data.data;
        }

        this.initData(data);
        this.initSearch();
        this.initPagination();
        this.initBody(fixedScroll);
    };
```

**Comment by BenJule** [comment]
ahhh thanks @djhvscf , i have found the solution.

**Comment by djhvscf** [comment]
Can you tell us what is your solution? @BenJule

**Comment by BenJule** [comment]
I was change the line data = data.rows; -> data = data.nodes;
```css
BootstrapTable.prototype.load = function (data) {
        var fixedScroll = false;

        // #431: support pagination
        if (this.options.sidePagination === 'server') {
            this.options.totalRows = data.total;
            fixedScroll = data.fixedScroll;
            data = data.rows; // <-- related this function
        } else if (!$.isArray(data)) { // support fixedScroll
            fixedScroll = data.fixedScroll;
            data = data.data;
        }

        this.initData(data);
        this.initSearch();
        this.initPagination();
        this.initBody(fixedScroll);
    };
```

**Comment by djhvscf** [comment]
Ok, I think we have to review that method because is not a common solution for all us! Thank you!

**Comment by wenzhixin** [comment]
There is an option: `responseHandler`, and it can easy to resolve your problem:
```
responseHandler: function (res) {
    return res.nodes;
}
```

PS: it is not recommended to modify the source code.
Here is the [Docs](http://bootstrap-table.wenzhixin.net.cn/documentation/).
The example: http://issues.wenzhixin.net.cn/bootstrap-table/#353.html.
The json: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/353.json.

**Comment by BenJule** [comment]
Hi @djhvscf & @wenzhixin 

The option ```responseHandler``` isnt working!
```js
responseHandler: function (res) {
    return res.nodes;
}
```
Please check my Site: http://benjule.github.io/project-categories/bootstrap-table-test/
and my github.io: https://github.com/BenJule/benjule.github.io

**Comment by djhvscf** [comment]
What exactly do we have to see??

**Comment by wenzhixin** [comment]
I have the same problem.

**Comment by BenJule** [comment]
@djhvscf please see, http://benjule.github.io/project-categories/bootstrap-table-test/

there is no output with tables!

**Comment by djhvscf** [comment]
First error.. No including the jQuery reference..

Review this, please.

![nojquery](https://cloud.githubusercontent.com/assets/4496763/6667277/a8d94b48-cbb0-11e4-9bb0-d4624fbb408a.PNG)

**Comment by BenJule** [comment]
omg, thanks @djhvscf

**Comment by BenJule** [comment]
@wenzhixin @djhvscf my json format was changed :-1: New Format: https://gist.github.com/BenJule/06c23346bc6995f82333. Its possible to read this format?

**Comment by djhvscf** [comment]
Of course.. you can use the flatJSON extension to read the JSON.. See this: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/flatJSON.html and this: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/flatJSON

**Comment by BenJule** [comment]
@djhvscf there isnt working, see http://gw3.ff3l.fr/?page=test

**Comment by djhvscf** [comment]
What about your table config?

**Comment by BenJule** [comment]
'''html
        <table id="table"
               data-toggle="table"
               data-flat="true"
               data-search="true"
               data-url="./db/ff3l.json">
            <thead>
            <tr>
                <th data-field="hostname" data-sortable="true">Hostname</th>
                <th data-field="uptime" data-sortable="true">Uptime</th>
                <th data-field="tx" data-sortable="true">TX(MB)</th>
                <th data-field="rx" data-sortable="true">RX(MB)</th>
                <th data-field="firmware" data-sortable="true">Firmware</th>
                <th data-field="model" data-sortable="true">Model</th>
                <th data-field="autoupdate" data-sortable="true">Autoupdate</th>
                <th data-field="loadavg" data-sortable="true">Load AVG</th>
                <th data-field="memfree" data-sortable="true">Mem Free</th>
            </tr>
            </thead>
        </table>
'''

**Comment by BenJule** [comment]
```html
        <table id="table"
               data-toggle="table"
               data-flat="true"
               data-search="true"
               data-url="./db/ff3l.json">
            <thead>
            <tr>
                <th data-field="hostname" data-sortable="true">Hostname</th>
                <th data-field="uptime" data-sortable="true">Uptime</th>
                <th data-field="tx" data-sortable="true">TX(MB)</th>
                <th data-field="rx" data-sortable="true">RX(MB)</th>
                <th data-field="firmware" data-sortable="true">Firmware</th>
                <th data-field="model" data-sortable="true">Model</th>
                <th data-field="autoupdate" data-sortable="true">Autoupdate</th>
                <th data-field="loadavg" data-sortable="true">Load AVG</th>
                <th data-field="memfree" data-sortable="true">Mem Free</th>
            </tr>
            </thead>
        </table>
```

**Comment by djhvscf** [comment]
Let me check it
