### ISSUE TITLE
Grand Total from Footer

### ISSUE THREAD

**Issue by xmbohx** [wenzhixin/bootstrap-table#6102]
### Description

Hi,

I am learning from this example `https://examples.bootstrap-table.com/index.html#options/footer-style.html#view-source`

and wanted to have an additional row underneath the total by summing ` function nameFormatter(data)` and `function nameFormatter(data, footerValue)`

Please help

### Example(s)

![Untitled](https://user-images.githubusercontent.com/84425431/163141133-c1406263-e41e-47c5-94f8-12955037833e.png)

**Comment by wenzhixin** [comment]
Workaround may be help you: https://live.bootstrap-table.com/code/wenzhixin/11325

**Comment by UtechtDustin** [comment]
I'm closing this issue, because we got no response from you within 7 days.
If you still need help and the workaround of @wenzhixin don't help please let us now and we will reopen the issue.
