### ISSUE TITLE
How to change the csv delimiter

### ISSUE THREAD

**Issue by santocch** [wenzhixin/bootstrap-table#6107]
### Description

Hello,

I tried to find a simple way to change the character used as csv delimiter but I didn't find any option to do it... it would be great to have this option: in my country (Italy) the standard is to use the semicolon (see wikipedia: Semicolons are often used instead of commas in many European in order to use the comma as the decimal separator and, possibly, the period as a decimal grouping character.)

The dirty trick to solve this problem is simple (change the character in the hard coded csvSeparator variable in tableExport.min.js) but that's not right way to do things...

Thanks

**Comment by santocch** [comment]
I asked this question in https://github.com/hhurz/tableExport.jquery.plugin/issues/351 and I got a solution which works as code but using the same solution as a table attribute doesn't look to work:

`data-export-options='{type:"csv", csvSeparator: ";"}'`

so I'm back here... is this the correct use of the data-export-options attribute? And if this is correct why it doesn't work?

**Comment by UtechtDustin** [comment]
It seems it's currently don't work with the data attribute.
Via JS it works fine: https://live.bootstrap-table.com/code/UtechtDustin/11321
