### ISSUE TITLE
Acute accent in Spanish locale file.

### ISSUE THREAD

**Issue by anpegar** [wenzhixin/bootstrap-table#611]
Hi !!

I've built a file with Spanish (España) translation (bootstrap-table-es-SP.js) but the accent symbols doesn't appears correctly, What's wrong? (have a look the attach).

I don't have a "pull request" of "bootstrap-table-es-SP.js" file because I've never used Github and I don't know how I have to do it ... sorry ;-)

Thanks in advance.

![captura2](https://cloud.githubusercontent.com/assets/8124520/6617794/c6fed526-c8bc-11e4-9903-6c0bb5e2bec1.PNG)

![captura](https://cloud.githubusercontent.com/assets/8124520/6617771/770efafa-c8bc-11e4-8eae-ada4f0f72b82.PNG)

**Comment by djhvscf** [comment]
I think you can use the HTML codes to do that.. Here the list.. http://character-code.com/ use the ones that is similar to &aacute; @anpegar

**Comment by anpegar** [comment]
Hi djhvscf,

Thanks for your fast reply.
I've done this change and it works fine but I don't understand why I have to put char code instead of just char, could you explain it?

.....
formatRecordsPerPage: function (pageNumber) {
            return pageNumber + ' registros por p&#225;gina.';
}
.....

Thx.
Toni.

**Comment by anpegar** [comment]
The change was this ...

formatRecordsPerPage: function (pageNumber) {
            return pageNumber + ' registros por p`&#225;`gina.';
        }

**Comment by djhvscf** [comment]
Yes this is because our pages not always have this declaration
```html
<head>
<meta charset="UTF-8">
</head>
```
Ref to: http://www.w3schools.com/tags/att_meta_charset.asp

@anpegar

**Comment by djhvscf** [comment]
And how to do a pull request? Ref to: https://help.github.com/articles/creating-a-pull-request/

@anpegar

**Comment by djhvscf** [comment]
Can you do the pull request? @anpegar

**Comment by anpegar** [comment]
Hi !!

Thank you so much for your info, it's very useful.
The tag "chartset" I had already known but in this case it doesn't work.

Tomorrow, I'll make a pull request with my Spanish translation.

By the way, I would like to modify the class of some objects like combobox of pagination but I would like to do it without modifying bootstrap-table.js, How can I do it? Is there some type of extend method?

I've seen that input search don't have id so I have to access with something like this $("#mytable .search [data-toggle="dropdown"]).addClass("btn-xs"); but it doesn't work. 
I've also seen that pagination block an pagination-detail block are not aligned, this can be fixed by removing the class pagination of block "pagination". I'll do pull request.

Thanks for all.
Cheers.

**Comment by djhvscf** [comment]
ok, related to pagination blocks alignment there is update where we include the option to align 'left' or 'right'.. And the other thing yes you can do the PR related to add an Id to the search textvox...

**Comment by wenzhixin** [comment]
Welcome your locale file PR(when you do, pls ref this issue) @anpegar , and I think we needn't an Id to the element. You can access id like this: `$('#table').parents('.bootstrap-table').find('.search')`.

**Comment by anpegar** [comment]
I've done the "pull request", is ok?
Thanks.
