### ISSUE TITLE
Missing docs for bootstrap 4 theme

### ISSUE THREAD

**Issue by martinbarilik** [wenzhixin/bootstrap-table#6113]
### Description

https://github.com/wenzhixin/bootstrap-table/commit/3774e75a9d548bd133f8b9174d6b9dae17bfaf0c

We have default bootstrap 5 css in 1.20, but how are we supposed to use it with 4.x ? Select element is not formatted for those. 

I don't see any theme docs as well.

Thanks ;)

**Comment by UtechtDustin** [comment]
The bootstrap-table will figure out the version itself, so no configuration/documentation is needed.

**Comment by martinbarilik** [comment]
Okay, it is then bug i suppose ?

**Comment by martinbarilik** [comment]
https://jsfiddle.net/mArtinko5MB/r4j3oxs2/15/ fiddle with bootstrap 4

**Comment by UtechtDustin** [comment]
Could you please provide us an example using our [editor](https://live.bootstrap-table.com/) ?

I didn't know you have an issue, you tagged it as `docs`-issue, so i closed it as my anweser solves your question.
Now i know you have an issue and of course i will reopen the issue.

**Comment by UtechtDustin** [comment]
@wenzhixin Could you please check the editor ?
The search for the extensions is broken.

**Comment by martinbarilik** [comment]
It is working in the editor 

https://live.bootstrap-table.com/code/martinbarilik/11328

question is, do editor really changes bootstrap to version 4 ?

**Comment by UtechtDustin** [comment]
Yes, you can check the network tab of the developer tools of your Browser.
The editor will use `https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js` as cdn.

**Comment by martinbarilik** [comment]
you were faster :) 

it seems it does ... What am i missing in jsfiddle ( and in my code ) then ? Any hints?

**Comment by UtechtDustin** [comment]
Do you also have the issue on your local pc ?

**Comment by martinbarilik** [comment]
Yes i do ;)

**Comment by UtechtDustin** [comment]
If i don't forget it, i will check it in the evening (i'm not at home).
It should work fine on the local pc if it works on the editor.

**Comment by martinbarilik** [comment]
Thanks for effort

**Comment by wenzhixin** [comment]
Do you mean https://bootstrap-table.com/themes/ ?
https://bootstrap-table.com/themes/bootstrap4/

**Comment by UtechtDustin** [comment]
@wenzhixin 
Check the resources tab, bootstrap will be loaded (You also can see that the table classes of bootstrap works fine)

**Comment by wenzhixin** [comment]
I mean the fiddle @martinbarilik provided: https://jsfiddle.net/mArtinko5MB/r4j3oxs2/15/

**Comment by wenzhixin** [comment]
I think we can close this issue.

**Comment by martinbarilik** [comment]
Thanks for the hint.
