### ISSUE TITLE
v1.20.1 plan

### ISSUE THREAD

**Issue by wenzhixin** [wenzhixin/bootstrap-table#6115]
### Core

- **Update:** Fixed toggle column bug with complex headers. #6124
- **Update:** Fixed icons option cannot work bug when it's a string. #6137
- **Update:** Updated TypeScript definitions. #6123

##### Extensions

- **Update(cookie):** Fixed cookie extension error with multiple-sort. #6139
- **Update(export):** Fixed the `exportOptions` option cannot support the data attribute. #6112
- **Update(reorder-rows):**  Fixed reorder-rows cannot work because of missing default functions.  #6114

**Comment by sdespont** [comment]
@wenzhixin because "reorder-rows" plugin is no longer working in 1.20.0, would it be possible to release the next version with the fixes already merged?

**Comment by wenzhixin** [comment]
1.20.1 released!

**Comment by sdespont** [comment]
@wenzhixin Thank you so much !
