### ISSUE TITLE
How to get row index in formatter

### ISSUE THREAD

**Issue by franky920920** [wenzhixin/bootstrap-table#6118]
### Description

How to get the row index (`data-index` in each tr tag) in the formatter? 

### Example(s)

https://live.bootstrap-table.com/code/franky920920/11340

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/column-options/#formatter
https://live.bootstrap-table.com/code/wenzhixin/11343

**Comment by franky920920** [comment]
Thanks a lot!
