### ISSUE TITLE
CustomSort for date type programmatically

### ISSUE THREAD

**Issue by frameworker2019** [wenzhixin/bootstrap-table#6119]
### Description

I have problems to call the custom sort when I incorporate the appropriate option like this:

```	
    $('#t1').bootstrapTable('refreshOptions', {
    	sortName:sortName,
    	sortOrder:sortOrder,
    	customSort: myDateSort
    });

function myDateSort(sortName, sortOrder, data) {

    if(sortName == 'scrapdate') {

	console.log(sortOrder);
	
	var order = (sortOrder === 'desc') ? -1 : 1;

	var tParser = d3.timeParse('%d.%m.%Y');

	data.sort(function(d1,d2) {

	    var _d1 = tParser(d1.scrapdate);
	    var _d2 = tParser(d2.scrapdate);

	    if((_d1 === null) || (_d2 === null))
		return(1);
	    
	    if(_d1 < _d2)
		console.log(d1.scrapdate + ' < ' + d2.scrapdate);
		return(order * -1);

	    if(_d1 > _d2)
		console.log(d1.scrapdate + ' > ' + d2.scrapdate);
		return(order);

	    console.log(d1.scrapdate + ' = ' + d2.scrapdate);
	    return(0);
	});
}
```

It seems the custom sort function will not honored, the date columns are not sorted correctly.
For example data is empty despite t1 has data.
However, the default sorting mechanism of BT works.

**Comment by UtechtDustin** [comment]
Please provide us an example using our [Editor](https://live.bootstrap-table.com/).
The example should contain some datasets.

**Comment by UtechtDustin** [comment]
We don't get a example from you, we will close this issue until we got an response.
Let us know if you still need help.
