### ISSUE TITLE
Data-Date

### ISSUE THREAD

**Issue by gogliko** [wenzhixin/bootstrap-table#612]
i Use Bootstrap-Table  and use Mongodb

my code : 

```
<th data-halign="left" data-field="RentClient">Client</th>
	                        <th data-halign="left" data-field="###">#</th>
	          
	                        <th data-halign="left" data-field="#">#</th>
	                        <th data-halign="left" data-field="#">#</th>
	                       
	                        <th data-halign="left" data-field="#">#</th>
	                        <th data-halign="left" data-field="#">#</th>
	                        <th data-field="operate" data-formatter="operateFormatter" data-events="#">#</th>
```

u Receive date from mongodb : 2015-03-25T20:00:00.000Z   need change date  time , like this : 2015-03-25 how i can do this format?

**Comment by djhvscf** [comment]
Let see this https://github.com/wenzhixin/bootstrap-table/issues/502,  if it does not work, just tell us! @gogliko

**Comment by djhvscf** [comment]
Does it work for you? @gogliko

**Comment by wenzhixin** [comment]
Thanks for @djhvscf , you can also use the [Moment.js](http://momentjs.com/) to format(data-formatter) you date time. close this issue.

**Comment by gogliko** [comment]
tnx
