### ISSUE TITLE
data-filter-control select control is cleared after selecting entry when using server side data

### ISSUE THREAD

**Issue by coshlo** [wenzhixin/bootstrap-table#6125]
### Bootstraptable version(s) affected

1.20.0

### Description

This is a related issue to [#6110](https://github.com/wenzhixin/bootstrap-table/issues/6110); with server side pagination, when an entry is selected on a filterable column with a select box, the table is filtered and updated correctly but the select box is cleared.

The select box works fine when clent side pagination is used.

See examples...

### Example(s)

Server side example:
[https://live.bootstrap-table.com/code/coshlo/11382](https://live.bootstrap-table.com/code/coshlo/11382)

Client side example:
[https://live.bootstrap-table.com/code/coshlo/11381](https://live.bootstrap-table.com/code/coshlo/11381)

### Additional Context

I've tried these examples on Firefox and Chrome with the same results.

**Comment by gokhansaroglu** [comment]
Same problem here.

**Comment by RedsergBo** [comment]
Hi.
After adding a fixed header issue exist. I add only data-height="500".
`data-height="500"`
https://live.bootstrap-table.com/code/RedsergBo/14357

**Comment by vuvtdhh** [comment]
Same problem with @RedsergBo, but on client side.
When set data-height for the table, select filter cleared after selecting entry.
