### ISSUE TITLE
Toggle Detail View exception

### ISSUE THREAD

**Issue by szpetny** [wenzhixin/bootstrap-table#6126]
### Bootstraptable version(s) affected

1.20.0

### Description

When toggle detail view and click outside of the icon (+/-) the exception is thrown:
`Uncaught TypeError: column is undefined`
![image](https://user-images.githubusercontent.com/12716399/166671787-3db57936-7e20-49b6-899c-a8a899dd7397.png)

### Example(s)

You can reproduce it on the demo page:
https://examples.bootstrap-table.com/#options/detail-view.html

**Comment by UtechtDustin** [comment]
Thank you for the report!
