### ISSUE TITLE
How can I keep a filter, after table refresh

### ISSUE THREAD

**Issue by hoonsub-um** [wenzhixin/bootstrap-table#6127]
### Description

Hi,

I have problem using bootstrap-table filter-control.

I want to keep filter, after table refresh.

But for now, when I refresh, the filter is reset.

Please help me guys

**Comment by djhvscf** [comment]
I think you could use the [cookie](https://bootstrap-table.com/docs/extensions/cookie/) extension.

**Comment by UtechtDustin** [comment]
I assume you're issue was resolved, because we got no response form you.
If you still need help and the anser from @djhvscf don't fixed your issue, please let us know and we will reopen the issue.
