### ISSUE TITLE
Filter Control of input type - Filter by various values

### ISSUE THREAD

**Issue by AndresConpas** [wenzhixin/bootstrap-table#6128]
### Description

I have a bootstrap table which has like 4 columns.

Imagine one of those columns is called 'car type' and I want to search both sedans and coupes.

What combination of chars should I insert in the search input so it looks for those two? Is this even possible?

### Example(s)

`sedan|coupe` `sedan&coupe` `sedan,coupe` `sedan, coupe`

![imagen](https://user-images.githubusercontent.com/98953651/166915090-53a74891-8fad-4d97-8e0d-f142d9d42941.png)

**Comment by djhvscf** [comment]
That's not supported at this moment. Marked as feature

**Comment by AndresConpas** [comment]
Thanks for commenting, looking forward to see it added in the future!
