### ISSUE TITLE
bootstrap table thead change height BiG problem ??

### ISSUE THREAD

**Issue by Dhruuva** [wenzhixin/bootstrap-table#613]
Hi guys
 I'm trying to change the height of the table header
 and it does not work
Please give it a try

.table { border: 2px solid #2980B9; }
.table thead > tr > th {padding:0px !important; background-color: green;  height:50%; color:pink}

put it in the css section at http://jsfiddle.net/wenyi/30sx4h3t/light/
What am I doing wrong?
Best Regards..

**Comment by djhvscf** [comment]
For this problem use the data-height table option @Dhruuva

**Comment by Dhruuva** [comment]
Thanks 
it does not help 
Please see the pic:  http://tinypic.com/r/2nretep/8
This works as I expected. You can try it  go at http://jsfiddle.net/4tdS2/
put this css code:
.table { border: 2px solid #2980B9; }
.table thead > tr > th {padding:0px !important; background-color: green; height:15px; color:pink; font-size: 0.7em}
And see all is fine.  Header height is  15 px .
But if I try to  do this with bootstrap-table 
I get this http://i58.tinypic.com/evct20.jpg
No change the height of the header
You can check it yourself
http://jsfiddle.net/wenyi/30sx4h3t/light/
add to html data-height="450" for your advice
and css code:
.table { border: 2px solid #2980B9; }
.table thead > tr > th {padding:0px !important; background-color: green; height:15px; color:pink; font-size: 0.7em}
you'll upset by the result
Best Regards.

**Comment by djhvscf** [comment]
Please see this http://stackoverflow.com/questions/5657964/css-why-doesn-t-percentage-height-work @Dhruuva

**Comment by wenzhixin** [comment]
Hi @Dhruuva , maybe you can try to change the css and js file:
https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.css#L25
https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L10

**Comment by Dhruuva** [comment]
ok Thank You 
p.s. it is tedious to do it every time you want to change the height of the header

**Comment by wenzhixin** [comment]
Maybe we can consider to add this as an option.

**Comment by Dhruuva** [comment]
This will be great ! Thank you in advance
