### ISSUE TITLE
Bug filter-control when using & in value

### ISSUE THREAD

**Issue by Zecrum** [wenzhixin/bootstrap-table#6130]
### Bootstraptable version(s) affected

1.20.0

### Description

Since the version 1.20.0 when we use "&", the select filter control does not work.

### Example(s)

With 1.19.1 (work) : https://live.bootstrap-table.com/code/Zecrum/11402
With 1.20.0 (don't work) : https://live.bootstrap-table.com/code/Zecrum/11400

### Possible Solutions

Fix in issue #5385

**Comment by sdespont** [comment]
@UtechtDustin PR provided : https://github.com/wenzhixin/bootstrap-table/pull/6323

**Comment by djhvscf** [comment]
@sdespont merged
