### ISSUE TITLE
The sub table cannot be added or deleted

### ISSUE THREAD

**Issue by lishuangcheng2021** [wenzhixin/bootstrap-table#6136]
### Bootstraptable version(s) affected

最新版

### Description

最新版本：对应子表 无法添加，删除，等操作。

**Comment by lishuangcheng2021** [comment]
key: "append",key: "remove",key: "load",等方法均无效。

**Comment by wenzhixin** [comment]
请提供例子。
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by lishuangcheng2021** [comment]
就是制作一个父子表，父表通过下面这种方式可以追加数据。
$('#Table').bootstrapTable('append', Row);
但是子表通过这种方式不能追加，debug后发现：子表通过上面方法追加数据时，无法触发bootstrap-table.js的 key: "append"方法。

但是1.15.3版本的bootstrap-table.js，父子表追加数据都是完全没有问题的。
