### ISSUE TITLE
Allow printed data (on <tbody>) to parse and be a bootstrap-table

### ISSUE THREAD

**Issue by thiagof** [wenzhixin/bootstrap-table#614]
Currently, it seems the plugin can't deal with datasets already printed in the html tbody tag.

A nice feature would be to construct `columns` on the-fly, with defaults and data guessing.

**Comment by djhvscf** [comment]
Do you mean this? http://bootstrap-table.wenzhixin.net.cn/examples/#table-from-html @thiagof

**Comment by thiagof** [comment]
Yep.. think I was with some markup bug in my generator. Switched to ajax
already.

Good work!

2015-03-13 14:27 GMT-03:00 Dennis Hernández <notifications@github.com>:

> Do you mean this?
> http://bootstrap-table.wenzhixin.net.cn/examples/#table-from-html @thiagof
> <https://github.com/thiagof>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wenzhixin/bootstrap-table/issues/614#issuecomment-79160624>
> .
>



-- 
*Thiago Fernandes*
Analista de Processos
34 9176- 4055 | thiago@internetbudi.com.br

**Comment by djhvscf** [comment]
Great! Can you close this issue please?? @thiagof  or  @wenzhixin
