### ISSUE TITLE
Filter control select and formatter with strict search set to true not working

### ISSUE THREAD

**Issue by itsensellc** [wenzhixin/bootstrap-table#6149]
### Bootstraptable version(s) affected

1.20.0

### Description

When using the filter extension with filter control set to select and filter strict search set to true with a formatter no results are returned. The workaround for a similar issue has been to use data-filter-data but this only works when strict search is set to false.

### Example(s)

https://live.bootstrap-table.com/code/itsensellc/11446

**Comment by UtechtDustin** [comment]
I don't think this is a bug @djhvscf.
He modifies the data via formatter (add an icon) but his search data don't contains the icon which means we can't match them.
If he set the [searchFormatter](https://bootstrap-table.com/docs/api/column-options/#searchformatter) option to `false` which means we comapre the raw data (without icon) it works fine.

Example: https://live.bootstrap-table.com/code/UtechtDustin/12073

**Comment by UtechtDustin** [comment]
I close this issue because of the explanation of the last post.
If you still think this is a bug, please explain us your point of view.
