### ISSUE TITLE
Using datepicker filter with JSON data from URL

### ISSUE THREAD

**Issue by itsensellc** [wenzhixin/bootstrap-table#6152]
### Description

I am not having any success getting the datepicker filter control to work. I'm attempting to filter dates delivered from AJAX in standard database format - yyyy-mm-dd. I add the datepicker filter control as such:

`<th data-field="date" data-filter-control="datepicker" data-sortable="true">Date</th>`

The datepicker control shows fine, however upon selecting a date known to be in the data, the results come back empty. This is with client side filtering and sorting. I've tried different date formats as well but have not gotten anything to hit. 1.2.0

Thank you.

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by itsensellc** [comment]
> Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

No problem - checkout https://live.bootstrap-table.com/code/itsensellc/11463.
