### ISSUE TITLE
on('load-success.bs.table'  does not work 

### ISSUE THREAD

**Issue by Dhruuva** [wenzhixin/bootstrap-table#616]
Hi! 
load-success.bs.table event does not respond after loading data
Can you explain why?
http://jsfiddle.net/dhruuva/kmbqx5jg/ 
Maybe it's bug ??

**Comment by djhvscf** [comment]
Well the load.success.bs.table is an event that it fires only when the data-side-pagination is set to 'server'

**Comment by Dhruuva** [comment]
Thank You !

**Comment by wenzhixin** [comment]
Correct it, `load.success.bs.table` is an event` is an event that it fires when need to send ajax to an url from server, both client and server side.
https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1413
https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1425
