### ISSUE TITLE
export in VueJS

### ISSUE THREAD

**Issue by redaabdellah21** [wenzhixin/bootstrap-table#6161]
### Description

Hi, 
i am trying to work with bootstrapTable in VueJS, but i think that not all methods are supported. for ex: when i add the showColumns or search options, it works and i can do that. but when i add a showExport oprtion, there is no dropdown that shows on top of the table. 

here are my options

 options: {
        onPostBody: this.initializeTooltips,
        search: true,
        showColumns: true,
        showRefresh: true,
        showExport: true,
        pagination: true,
        silentSort: false,
        sidePagination: 'server',
        queryParamsType: 'pageSize',
        pageList: '[10, 25, 50, 1000]',
        pageSize: 10,
        icons: {
          refresh: 'fa-refresh',
          export: 'fa-refresh',    // just to show something
        },

is there a way to export data directly when using VueJS? or it is not implimented yet?

i would appreciate the help or some doc, there isn't really a lot of doc about bootstrap table when used in VueJS

**Comment by wenzhixin** [comment]
docs: https://bootstrap-table.com/docs/vuejs/webpack/
You need to import the extension.

**Comment by redaabdellah21** [comment]
thank you so much, it works now. 

Ps: PDF export not working

**Comment by wenzhixin** [comment]
Checkout the docs: https://github.com/hhurz/tableExport.jquery.plugin#installation

**Comment by redaabdellah21** [comment]
thank you. it is nice of you to respond in such short time.

Please, any help with the issue #6162

**Comment by wenzhixin** [comment]
OK. Close this issue.
