### ISSUE TITLE
prevent bootstrap table from showing some rows

### ISSUE THREAD

**Issue by redaabdellah21** [wenzhixin/bootstrap-table#6162]
### Description

hi, 
i am using bootstrap table with VueJS, i want to do a sort of filtering so that bootstrap doesn't shoq some rows, i want t do it directly. meaning that i don't have to click a button to execute a method or something like that, but to filter it directly when using bootstrap table. is this possible? if not, is it possible to share some doc about filtering when using VueJS? i can't find a lot of doc concerning bootstrap table used with VueJS.

thnak you so much for your help in advenced

**Comment by wenzhixin** [comment]
Online example: https://live.bootstrap-table.com/code/wenzhixin/11513

**Comment by redaabdellah21** [comment]
thank you for your help.
in your example the data is in a variable called json. when we get data from a URL where is it stocked? i am asking because we are suppoed to apply the filter method on the data. but i can't figure out where it is stocked. i have tried:

columns.filter
data.filter
this.$refs.table.filter
this.data().filter

but nothing seems to work.

**Comment by wenzhixin** [comment]
You can use the getData method.
