### ISSUE TITLE
Select (but not check) a row

### ISSUE THREAD

**Issue by stokito** [wenzhixin/bootstrap-table#6165]
### Description

I want to make a table where I can select a row and on the toolbar above press Edit, Delete etc.
As far I understood with the BT it's not possible. Or maybe there is some option to implement this?
Thank you

**Comment by wenzhixin** [comment]
Example: https://examples.bootstrap-table.com/index.html#issues/563.html

**Comment by wenzhixin** [comment]
Online Example: https://live.bootstrap-table.com/code/wenzhixin/11512
