### ISSUE TITLE
Filter control : searching text disappears when 2 tables or more are displayed on the same view

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#6166]
### Bootstraptable version(s) affected

1.20.1

### Description

I use a page with two tables. The tables have columns with identical names.

The search in the first table works fine. When searching in the second (zones) table for "ID" and "User", the search-string disappears from the input fields.

![screen-recording-2022-05-18-09 3A52 webm](https://user-images.githubusercontent.com/646632/168987305-0a16da8c-c3ef-479f-9578-3af93f14e2a2.gif)

_Originally posted by @yeezy69 in https://github.com/wenzhixin/bootstrap-table/issues/5583#issuecomment-986095348_

### Example(s)

The example provided permits to reproduce the problem. The table is well sorted, but the searching string disappear :

https://live.bootstrap-table.com/code/sdespont/11515

### Possible Solutions

Because the problem occurs **ONLY** if the table fields have same name, I suspect this is missing a table-id check?

**Comment by Blue3957** [comment]
If I'm not mistaken, it's the `cacheValue` function that caches the wrong values.
I managed to get it working by replacing
```
if (that.options.height && !that.options.filterControlContainer) {
  $field = $__default["default"](".fixed-table-header .".concat(fieldClass));
} else if (that.options.filterControlContainer) {
  $field = $__default["default"]("".concat(that.options.filterControlContainer, " .").concat(fieldClass));
} else {
  $field = $__default["default"](".".concat(fieldClass));
}
```
with
```
if (that.options.height && !that.options.filterControlContainer) {
  $field = that.$el.find(".fixed-table-header .".concat(fieldClass));
} else if (that.options.filterControlContainer) {
  $field = that.$el.find("".concat(that.options.filterControlContainer, " .").concat(fieldClass));
} else {
  $field = that.$el.find(".".concat(fieldClass));
}
```
But it's a dirty fix, i'm not clever nor familiar enough with the codebase to properly solve the issue.

**Comment by UtechtDustin** [comment]
@Blue3957 Thank you for figuring out the issue, i created a PR for that which fix the source files instead of the dist files :-)
