### ISSUE TITLE
Filter control not updating table after selection

### ISSUE THREAD

**Issue by jjboy91** [wenzhixin/bootstrap-table#6167]
### Description

Hi,

I am using the filter control (select). It's loading and being displayed properly but when I select a value, the table is not updated.
I have matched the data-filed to the json attribute. What else do I need for it to refresh the table's content ?

 `<table ref="mainTable" class="table table-striped table-bordered table-hover" cellSpacing="0"
                            id="mainTable" data-toggle="table" data-show-toggle="true" data-show-columns="true"
                            data-search="true" data-pagination="true" data-filter-control="true"
                            data-url="{{.urlBase}}/admin/api/data.json">
                            <thead>
                                <tr>
                                    <th data-field="reference" data-filter-control="select">ID</th>
                                    <th data-field="publication" data-filter-control="input">Item Name</th>
                                    <th data-field="flux" data-filter-control="select">Flux</th>
                                </tr>
                            </thead>
                        </table>`

Thanks

**Comment by UtechtDustin** [comment]
As written in the issue template, a example created with our [editor](live.bootstrap-table.com/) is required.
Please provide is a example.

**Comment by UtechtDustin** [comment]
I will close this issue, because we got no response from you.
If you still need help, please provide us an example.
