### ISSUE TITLE
Changing label of select filter blank value?

### ISSUE THREAD

**Issue by itsensellc** [wenzhixin/bootstrap-table#6171]
### Description

Hello

`<th data-field="trans_type" data-filter-control="select" data-sortable="true">Transaction Type</th>`

Is there a non-hacky way on a field with data filter control of type select applied that I can change the default empty label to something like "All Transactions" instead of just blank?

<img width="782" alt="image" src="https://user-images.githubusercontent.com/3731933/169670654-065769d8-318d-4cbc-bfe8-0c7e7a869229.png">

**Comment by UtechtDustin** [comment]
You can use the [filterControlPlaceholder Option](https://bootstrap-table.com/docs/extensions/filter-control/#filtercontrolplaceholder).
Example: https://live.bootstrap-table.com/code/UtechtDustin/11584
