### ISSUE TITLE
Freeze header

### ISSUE THREAD

**Issue by rfossella** [wenzhixin/bootstrap-table#618]
Hi,
is there an option or a way to freeze the header so that only the content scrolls and not the entire table?

Thanks.
Robert

**Comment by djhvscf** [comment]
What do you mean with freeze header?? Can you explain a little bit more?

**Comment by rfossella** [comment]
Hi - currently when the table has many rows, and you scroll, the table header scrolls out of view.  I want to know if there's a way to keep the header stationary, so that when you scroll you will always see the header row.
![image](https://cloud.githubusercontent.com/assets/1350182/6659094/812cc514-cb53-11e4-81f1-0ec0d2776155.png)

![image](https://cloud.githubusercontent.com/assets/1350182/6659099/a9f4d20c-cb53-11e4-8627-6ee5ee65aff6.png)

**Comment by djhvscf** [comment]
It can be a really good feature!

**Comment by wenzhixin** [comment]
Set the `height` option is easy to solve your problem @rfossella.

**Comment by rfossella** [comment]
hi - thanks for your comment.  Problem is I have a screen with multiple tables with hundred of rows.  I do set the height to about 300px per table but the header still scrolls out of view when scrolling through tables.

**Comment by rfossella** [comment]
hi - i noticed that when I set the height it will keep header row in view, however, the resize of window still causes misalignment - so I was forced to removed the height option so no misalignment occurs.   Note: I do use code below, but it doesn't work **all** the time.
$(window).resize(function () 
                    {
                        mytable.bootstrapTable('resetView');
                    });

**Example**
![image](https://cloud.githubusercontent.com/assets/1350182/6676367/927a3e46-cbfd-11e4-8c14-7ec7d40413fb.png)


I **VERY MUCH** appreciate your time!!
thanks!

**Comment by wenzhixin** [comment]
What version do you use?

**Comment by rfossella** [comment]
v1.6.0 - lastest

**Comment by wenzhixin** [comment]
OK, I will it check it soon.

**Comment by rfossella** [comment]
Hi. I was wondering if you were able to check this issue?
To recap, I'm trying to keep headers fixed using data-height but resize causes misalignment. 
Thank you for your time!

**Comment by djhvscf** [comment]
You have to use the resetView method to fix that..

**Comment by rfossella** [comment]
Hi.  Thanks for your response, but as I mentioned above, I have a resetView attached to window resize event but it doesn't trigger table reset consistently. The console logs indicate a window resize event but you can see that table columns remain misaligned. Sometimes there is a very noticeable shift/realignment, sometimes it doesn't occur at all

**Comment by wenzhixin** [comment]
Maybe you can provide a jsFiddle or a example. Here is the example: http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by RahulSisodia** [comment]
Is there any solution to this issue. I am facing it too.

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle @RahulSisodia

**Comment by rfossella** [comment]
Hi. Using bootstrap-table v1.7 

I recently set up my bootstrap-table to again use the fixed header using a height.  I ran into the same issue I described above with respect to the misalignment of columns.  (Please see my previous pic)

Hopefully this additional info will help in resolving the issue. The latest thing I noticed is that this does not appear to happening on a *WINDOW RESIZE* event as I am using *'resetView*'.  I notice the issue when **BOOTSTRAP** does a **responsive resize event**.  In my case (as many other bootstrap implementations) I have a side-bar that gets hidden when the window hits a certain width (<768)  It seems the window resize event gets triggered but there is an additional **responsive "resize"** that occurs and the bootstrap table does not get a chance to do another resetView.  Additionally, this seems to be present when the table DOES NOT have a horizontal scrollbar - interesting... (See new pic)

So, is there another event we can trap in the case of a BOOTSTRAP event that may hide elements that are adjacent to the bootstrap-table?  Is there something else that may need to be addressed regarding the horizontal scrollbar?

Hopefully this gives you useful information.  Thank you for your time!

![bootstraptable-bug](https://cloud.githubusercontent.com/assets/1350182/10501932/87842e44-72b4-11e5-8d81-89ca2639a39d.jpg)

**Comment by erick-chali** [comment]
Try to place the table inside a div with class="table-responsive" or class="container", that helped me to fix the issue.
