### ISSUE TITLE
Data filter searches in html, how to prevent?

### ISSUE THREAD

**Issue by ingermaa** [wenzhixin/bootstrap-table#6187]
### Description

If i use a `data-filter-control="input`" on a column it searches not just for text, it also searches in `<tags>`

Is there an option to prevent this or do i need to write a custom filter?

Example, both rows will be returned if the column is filtered "tester"
```
<tr>
<td>Tester</td>
</tr>
<tr>
<td>Test<span class="tester">!</span></td>
</tr>
```

See example and filter for "target" in Name column

Is there a way to force a column to only search in specified text? Maybe `data-filter-?`

### Example(s)

Enter "target" in Name filter.

https://live.bootstrap-table.com/code/ingermaa/11642

**Comment by UtechtDustin** [comment]
There is no feature like that build in, you have to use the option [filterCustomSearch](https://bootstrap-table.com/docs/extensions/filter-control/#filtercustomsearch).
