### ISSUE TITLE
Retrieve all the filter control variables search texts

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#6188]
### Description

Hello,

In version 1.18, to retrieve the current filter search texts, I used this code : `var valuesFilterControl = $('#table').bootstrapTable('getOptions').valuesFilterControl;`

In version 1.20, `valuesFilterControl` option no longer exists. Looking in the code, the variable is now named `_valuesFilterControl` but is always empty and is not defined as an option.

How can I retrieve all the filters like I used to with `valuesFilterControl `?

**Comment by UtechtDustin** [comment]
The variable `valuesFilterControl` is a internal variable.
Could you please explain your usecase ?

**Comment by UtechtDustin** [comment]
I close this issue, becuase we got no response from you.
If you still need help, please provide us more information.
