### ISSUE TITLE
bootstrap-table row style does not triggered

### ISSUE THREAD

**Issue by Dhruuva** [wenzhixin/bootstrap-table#619]
Hi !
please see my sample http://jsfiddle.net/dhruuva/a5qt6sg3/
Why this feature is dead in my code

**Comment by djhvscf** [comment]
See this.. http://jsfiddle.net/e3nk137y/1003/

**Comment by Dhruuva** [comment]
Ok,Thank You 
But.....hm... There is another way to work row-style and cell style 
without exception, from the project dependency bootstrap.min.css,bootstrap.min.js?
Bets regards

**Comment by Dhruuva** [comment]
I'm sorry first time I have not notice that problem was with jsFiddle option must be selected (no wrap in <head>)
please ignore comment before
Thank You
