### ISSUE TITLE
调用insertRow之后，再选中这条记录报空指针

### ISSUE THREAD

**Issue by zhaohuihua** [wenzhixin/bootstrap-table#6192]
### Bootstraptable version(s) affected

1.20.2

### Description

原因是，老版本中 this.data与this.options.data 指向同一数组
新版本中，this.data = _toConsumableArray(this.options.data); 不是指向同一数组了
insertRow/updateRow/remove/removeAll等方法操作的都是this.options.data
但initBodyEvent操作的是this.data
导致Utils.getItemField方法中item为undefined

**Comment by UtechtDustin** [comment]
Please translate this issue in english or only @wenzhixin can help you.
