### ISSUE TITLE
data-height and data-filter-control not working together

### ISSUE THREAD

**Issue by joaplopess** [wenzhixin/bootstrap-table#6194]
### Bootstraptable version(s) affected

1.20.2

### Description

Using the filterControl extension, setting data-height and data-filter-control="select", the table does not refresh when selecting a empty filter.

### Example(s)

https://live.bootstrap-table.com/code/joaplopess/11662

### Additional Context

Using Bootstrap v5

**Comment by UtechtDustin** [comment]
Thank you for the report, this issue is already fixed in our `develop` Branch.
Example: https://live.bootstrap-table.com/code/UtechtDustin/12071
