### ISSUE TITLE
Show a loader/event on table export 

### ISSUE THREAD

**Issue by amhassen97** [wenzhixin/bootstrap-table#6198]
### Description

Hi

Is it possible to add the option to show a loader of some sort when the table is exported using the table export extension? This would be useful for larger datasets to improve user experience. 

Or alternatively, an event when the export is started, since there is an onExportSaved event already.

Love the library!

Much appreciated. Thanks.

**Comment by wenzhixin** [comment]
Maybe we can add an `onExportStarted` event.

**Comment by mattsayers** [comment]
I too would find an exporting modal or export started event to be helpful.
