### ISSUE TITLE
Json doesn't load in bootstrap table

### ISSUE THREAD

**Issue by sychoow007** [wenzhixin/bootstrap-table#62]
Hi,

I'm trying to use this bootstrap table plugin for server side data. I have this table:

<'t'able 
id="tpOrderStatusTable" data-toggle="table" data-method="post" data-url="/Astel/Test"
    data-page-list="[5, 10, 20, 50, 100, 200]" data-side-pagination="server" data-pagination="true" data-search="true" data-query-params="queryParams">"
    <'t'head>
       <'t'r>
            <'t'h></th>
            <'t'h data-field="orderid" data-sortable="true">Order ID</th>
           <'t'h data-field="firstname" data-sortable="true">Firstname</th>
            <'t'h data-field="lastname" data-sortable="true">Lastname</th>
            <'t'h data-field="gender" data-sortable="true">Gender</th>"
            <'t'h data-field="language" data-sortable="true">Language</th>
       </'t'r>
    </'t'head>
</'t'able>"

And get this json back from the server:
[{"orderid":"123456","firstname":"foo","lastname":"foo","gender":"M","language":"nl"},{"orderid":"456789","firstname":"test","lastname":"test","gender":"f","language":"nl"}]

This is in the same format as the .json files in the examples folder. 

Sorry for the malformed table tags but otherwise you can't see the table code.

What am i doing wrong?

**Comment by wenzhixin** [comment]
hi @suyanNone, I think you can set `sidePagination` option to `'client'`.
