### ISSUE TITLE
Date-Formater Invalid Date? bug?

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#620]
Json:
0: Object
{Age: 4
Brithday: "/Date(1425830400000)/"
CompanyId: 6
CompanyName: "444"
Id: 1
Name: "444"
Sex: "44"}

//You can format the date as you want
    function dateformat(value, row, index) {
        return new Date(value);
        //var date = new Date(value);
        //console.log(value);
        //console.log(date);
        //return  jQuery.format.prettyDate(new Date()) 
    };

table show
“Invalid Date”

**Comment by djhvscf** [comment]
See this https://github.com/wenzhixin/bootstrap-table/issues/502

**Comment by neozhu** [comment]
没看懂，
 <th data-field="Brithday" data-formatter="dateformat">
                                Brithday
                            </th>
后台
 return Json(employee.Select( n => new { CompanyName = n.Company.Name , Id = n.Id , Name = n.Name , Sex = n.Sex , Age = n.Age , Brithday = n.Brithday , CompanyId = n.CompanyId }),JsonRequestBehavior.AllowGet);

**Comment by wenzhixin** [comment]
#612

**Comment by wenzhixin** [comment]
不是bug，你自己查一下。
