### ISSUE TITLE
Filtering the tables column based on the another column selected

### ISSUE THREAD

**Issue by sankagirirajeev** [wenzhixin/bootstrap-table#6200]
### Description

**I have used bootstrap table filter control option for the table like below,**

```
<tr class="header">
         <th data-field="datecrawledUpdated">Date Crawled</th>
         <th data-field="titleUpdated" data-filter-control="select" >Title</th>
         <th data-field="childtitleUpdated" data-filter-control="select">Child Title</th>
         <th data-field="GuidelineUpdated">Guideline</th>
         <th data-field="yearUpdated" data-filter-order-by="desc" data-filter-control="select" data-sortable="true">Publication Year</th>
         <th data-field="parentchildUpdated">Parent/Child</th>
         <th data-field="linkUpdated">URL</th>


       </tr>
```

**Problem:Is it possible to load the child title in select drop down based on the Title value using Bootstrap functions?**

Currently Child title column dropdown is displaying all data irrespective ah the Title column

**Comment by UtechtDustin** [comment]
Please provide us an example using the [online editor](https://live.bootstrap-table.com/).

**Comment by UtechtDustin** [comment]
I close this issue, because we got no example from you within 7 days.
If you still need help please provide us an example and we will reopen the issue, thanks!

**Comment by TomTurtle** [comment]
I have exactly the same question, and an example can be found directly on the examples page https://examples.bootstrap-table.com/#extensions/filter-control.html. e.g.: when you enter '5' in the column Item Name you see only 2 items in the list. But the dropdown menu of the item price shows all prices, not just the 2 different prices of the displayed rows (which I would like).
