### ISSUE TITLE
Detail View column exception when using Detail Filter

### ISSUE THREAD

**Issue by szpetny** [wenzhixin/bootstrap-table#6207]
### Bootstraptable version(s) affected

1.20.2

### Description

This issue is probably related to:
https://github.com/wenzhixin/bootstrap-table/issues/6126

Currently the reported bug is fixed, but can be still observed when using detail filter feature:
https://examples.bootstrap-table.com/#options/detail-filter.html

When you click on a cell in the first column which does not contain a plus icon you get an exception.
![image](https://user-images.githubusercontent.com/12716399/172378427-6987e6b5-1215-4c79-80f0-dd419c103e08.png)

### Example(s)

It can be reproduced here:
https://examples.bootstrap-table.com/#options/detail-filter.html

**Comment by wenzhixin** [comment]
Thanks for your feedback.

**Comment by wenzhixin** [comment]
https://live.bootstrap-table.com/code/wenzhixin/11754
