### ISSUE TITLE
how can i change pagination toggle tip

### ISSUE THREAD

**Issue by kaenry** [wenzhixin/bootstrap-table#621]
how can i change pagination toggle tip :'Showing how many records....' or remove it? Thanks.

**Comment by wenzhixin** [comment]
Can you provide more detail for your problem, for example a screenshot?

**Comment by kaenry** [comment]
![image](https://cloud.githubusercontent.com/assets/1326636/6663144/a06d24fe-cbfe-11e4-93c9-1a4a3941e6b2.png)
I want to change the text.

**Comment by wenzhixin** [comment]
You can try to define the `formatShowingRows` function: http://bootstrap-table.wenzhixin.net.cn/documentation/#localizations

**Comment by kaenry** [comment]
Thanks, it works.

**Comment by jbarrineau06** [comment]
Is there a way to change this programmatically, instead of just changing the source? I would like it to say different things on different pages.

**Comment by wenzhixin** [comment]
@jbarrineau06, use it as an option:
```js
$table.bootstrapTable({
    formatShowingRows: function () {
        // ...
    }
});
```
