### ISSUE TITLE
Bootstrap Dropdown  inside 1 row table - popup hidden

### ISSUE THREAD

**Issue by devorama** [wenzhixin/bootstrap-table#6217]
### Description

Good day
For those that stuggle using bootstrap Dropdown with bootstrap-table when you have 1 or 2 rows and the dropdown hides behind the table. 
This javascript can help solve that for you as a quick fix

```
	  $('.dropdown').unbind('show.bs.dropdown');
	  $('.dropdown').unbind('hide.bs.dropdown');
	  $('.dropdown').bind('show.bs.dropdown',function(){
		  $('.fixed-table-body').css( "overflow", "inherit" );
	  });
	  $('.dropdown').bind('hide.bs.dropdown',function(){
		  $('.fixed-table-body').css( "overflow", "auto" );
	  });
```
this is  done in jQuery, but the logic around it should be simple for alternative ways.
Hope it helps somebody

Note I have the unbinds as my contents of the table is html and dynamic, thus I link the contents events each time after loading the data , thus the unbind just to keep it clean.

Hope it helps somebody

**Comment by UtechtDustin** [comment]
Could you please provide us an example using our [online editor](https://live.bootstrap-table.com/) ?

**Comment by thiagozils** [comment]
Hey, im facing the same issue

If you click on the second row you can see the problem:

https://live.bootstrap-table.com/code/thiagozils/12089

**Comment by djhvscf** [comment]
I think this is not a BT issue perse. @UtechtDustin

**Comment by UtechtDustin** [comment]
@djhvscf why do you think that ?
I understand the usecase that somebody uses dropdowns in the table (e.g. for a longer list of options for the dataset), and this should possible do use a dropdown within the table or what is your opinion ?
Isn't it "just" a overflow problem ?

**Comment by djhvscf** [comment]
I mean that using dropdowns in the table is not a core feature of BT. So, yes, probably is just a overflow problem but the BT table is working as expected.

**Comment by UtechtDustin** [comment]
Okay i agree that point!
@thiagozils you can fix it by adding the `position-static` class to the `dropdown` div.
Example: https://live.bootstrap-table.com/code/UtechtDustin/12322

**Comment by thiagozils** [comment]
It worked for me @UtechtDustin, thanks

**Comment by fantasyinfo** [comment]
a quick fix 

.dt-scroll-body{
    min-height: 400px;
}

**Comment by tsirosgeorge** [comment]
In my case, I’m using the latest Bootstrap and initializing my table with DataTables. I found @zulmarij solution very helpful.
Here’s how I implemented it in my case:

```
initializeDropdowns(tableId) {
    try {
        const table = $(`#${tableId}`).DataTable();

        let dropdownColumnIndex = null;

        const rowCount = table.rows().count();
        if (rowCount > 0) {

            const firstRow = table.row(0).node();
            const cells = $(firstRow).find('td');


            cells.each(function (index) {
                if ($(this).find('.dropdown').length > 0) {
                    dropdownColumnIndex = index;
                    return false;
                }
            });
        }

        let dropdowns;
        if (dropdownColumnIndex !== null) {

            dropdowns = $('.dropdown .btn', table.cells(null, dropdownColumnIndex).nodes());
        } else {

            dropdowns = $(`#${tableId} .dropdown .btn`);
        }

        dropdowns.each((index, dropdownToggleEl) => {

            const existingInstance = bootstrap.Dropdown.getInstance(dropdownToggleEl);
            if (existingInstance) {
                existingInstance.dispose();
            }

            new bootstrap.Dropdown(dropdownToggleEl, {
                popperConfig(defaultBsPopperConfig) {
                    return { ...defaultBsPopperConfig, strategy: "fixed" };
                },
            });

            $(dropdownToggleEl).off('show.bs.dropdown hide.bs.dropdown');

            dropdownToggleEl.addEventListener("show.bs.dropdown", function (event) {
                $(event.target).closest("td").addClass("z-index-3");
            });

            dropdownToggleEl.addEventListener("hide.bs.dropdown", function (event) {
                $(event.target).closest("td").removeClass("z-index-3");
            });
        });
    } catch (e) {
        console.warn('initializeDropdowns failed:', e);
    }
}
```
