### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by NaNYeYuan** [wenzhixin/bootstrap-table#6219]
### Description

Any js files from extensions will report
Uncaught TypeError: Super expression must either be null or a function at _inherits(bootstrap-table-....js)

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by NaNYeYuan** [comment]
![image](https://user-images.githubusercontent.com/96454722/175006950-733287de-6ea8-4642-a9d3-4dede8422ab5.png)

**Comment by NaNYeYuan** [comment]
![image](https://user-images.githubusercontent.com/96454722/175008205-05aa77b1-ff68-433a-87f7-6f53fce4192c.png)

**Comment by stokito** [comment]
This happens when the `colspan` is bigger than real count of columns e.g.
```html
        <table class="bootstrap-table">
            <thead>
            <tr>
                <th colspan="14"></th>
            </tr>
            <tr>
                <th data-field="Id">ID</th>
                <th data-field="Name">Name</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
```

This is almost clear from the stack trace provided. Please reopen the bug.
At least we need a proper error reporting and check for undefined before getting of the `visible` field.

**Comment by wenzhixin** [comment]
This kind of case is the wrong usage; don't deal with this kind of case for the time.

**Comment by maximbashevoy** [comment]
I have the same error in version 1.20.2, it's a different problem I can't really pin down. Here is a quick "fix" for anyone landing up here from google like me:

Add `|| !this.columns[index]` to line 8259:

```js
if (index === -1 || !this.columns[index] || this.columns[index].visible === checked) {
```

Then minify:

```bash
uglifyjs -o bootstrap-table.min.js  -c drop_console=true --mangle --source-map --ie8 --verbose --warn -- bootstrap-table.js
```

and table export should now work correctly.

---

More code so it's easier to find the line:

```js
    }, {
      key: "_toggleColumn",
      value: function _toggleColumn(index, checked, needUpdate) {
        if (index === -1 || !this.columns[index] || this.columns[index].visible === checked) {
          return;
        }

        this.columns[index].visible = checked;
        this.initHeader();
        this.initSearch();
        this.initPagination();
        this.initBody();
```
