### ISSUE TITLE
Columns hidden via JS are not saved in cookie when they are selected to be shown

### ISSUE THREAD

**Issue by ShaneBekker-OT** [wenzhixin/bootstrap-table#6220]
### Bootstraptable version(s) affected

1.20.2

### Description

When hiding a column by default using JQuery and then setting it to display via the 'data-show-columns' drop-down, the column selected to display does show but is not saved to cookie to keep displaying. 

It appears that when default hiding columns via code their state when selected to show or hide via the show columns drop down is not remembered.

### Example(s)

https://live.bootstrap-table.com/code/ShaneBekker-OT/11787

### Possible Solutions

Although set by code ignore if set in cookie?

**Comment by UtechtDustin** [comment]
@ShaneBekker-OT 
Maybe i missunderstand something...
But for me it works fine, if i open your example the cookie contains `name` and `price`.
As soon i show the `id` column via dropdown the cookie also contains `id`.

Could this maybe a browser issue ?
Which Browser(version) do you use ?

**Comment by ionultd** [comment]
@UtechtDustin 
Simply, if in that example you select to show the ID column and refresh you page it does not remember to show it no matter what the cookie says.
Have tried in:
Edge: Version 103.0.1264.49 (Official build) (64-bit)
Firefox: 102.0.1 (64-bit
Chrome: 102.0.1 (64-bitVersion 103.0.5060.114 (Official Build) (64-bit)

**Comment by UtechtDustin** [comment]
The table remember that the id was visible, but you instantly hide the id after the table is shown.
```
$('#table').bootstrapTable("hideColumn","id");
```
If you hide the `id` column via `data-visible="false"`, then it works how you want it.
Example: https://live.bootstrap-table.com/code/UtechtDustin/12076

**Comment by ionultd** [comment]
Right, I see now. Thanks for providing that insight and  solution.

**Comment by UtechtDustin** [comment]
There are a lot of usecases, but as example you have a button `Show business Data` or something like that which one show relevant columns for business (e.g. hiding created at, updated at, etc.).

Is your issue resolved ?

**Comment by UtechtDustin** [comment]
I close this issue because we got no more response from you, if you still need help just ask!
