### ISSUE TITLE
bootstrap-table-filter-control versions >= 1.20.0 are much slower

### ISSUE THREAD

**Issue by UselessGuru** [wenzhixin/bootstrap-table#6222]
### Bootstraptable version(s) affected

\>=1.20.0

### Description

All bootstrap-table-filter-control versions newer than 1.18.3 are very slow.
I takes a few seconds to fill in the filter control. V 1.18.3 (and older) are much faster.
Furthermore the filter control values are not sorted.

Can anyone confirm?
What am I doing wrong? All sources can be found here: https://github.com/Minerx117/NemosMiner/tree/master/Web

**Comment by UselessGuru** [comment]
Seems related to
https://github.com/wenzhixin/bootstrap-table/issues/6201 https://github.com/wenzhixin/bootstrap-table/issues/6201
However in my case the dropdown data get sorted. I assume this is the case for the performance impact.

Maybe re-adding the pre-1.20.x code will fix this.

**Comment by djhvscf** [comment]
@UselessGuru we need to continue working on the performance of this extension. Do you have any examples where we can play with the performance issue that you're facing?

**Comment by djhvscf** [comment]
Working on this PR https://github.com/wenzhixin/bootstrap-table/pull/6309

**Comment by djhvscf** [comment]
Duplicated #https://github.com/wenzhixin/bootstrap-table/issues/5777
