### ISSUE TITLE
Header and Row data does not center correctly for Sortable columns

### ISSUE THREAD

**Issue by rconnaug** [wenzhixin/bootstrap-table#6228]
### Bootstraptable version(s) affected

1.20.2

### Description

When a column is defined with options to align to the center (halign="center" and align="center") and the column is then marked as sortable, a right-padding is applied to the header to accommodate the sort-arrow -- however the same padding is not applied to the row contents, causing the content to be misaligned to the header.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/44000827/175378762-f3f30a85-2407-4b70-9603-963ca7ae0803.png">

### Example(s)

https://live.bootstrap-table.com/code/rconnaug/11822

### Possible Solutions

I would think the same padding-right value should be applied to the `<td>`s in the table.

**Comment by wenzhixin** [comment]
Fixed example: https://live.bootstrap-table.com/code/wenzhixin/11852
