### ISSUE TITLE
Losing the object state

### ISSUE THREAD

**Issue by victorvasconcelosdeaquino** [wenzhixin/bootstrap-table#623]
Assuming I have populated the table with 20 records on the first page and I have three records that are checked, then when I change to the second page and then return to the first page, the records are no longer checked. There is some property that I can keep the states of objects when I am moving between pages?

**Comment by djhvscf** [comment]
See this issue: https://github.com/wenzhixin/bootstrap-table/issues/191 and this PR: https://github.com/wenzhixin/bootstrap-table/pull/603.. In the PR we are saving the sort order, sort name, page number, page list in a cookie.. I think we can add the option to save the rows checked.. or is there an option to keep the rows checked, @wenzhixin ??

**Comment by wenzhixin** [comment]
There is an option name `maintainSelected`, you can try that @victorvasconcelosdeaquino. And thanks for you PR @djhvscf, because change too much, now I have no enough time to check that out.

**Comment by djhvscf** [comment]
Sure! no problem @wenzhixin

**Comment by victorvasconcelosdeaquino** [comment]
Yes men! Just what I needed!
Thanx!

**Comment by xyluet** [comment]
it it can be apply for server side pagination ? I already tried it, but it won't work
