### ISSUE TITLE
advancedSearch Modal isn't updated after showColumns modifications

### ISSUE THREAD

**Issue by mohamedbouzaien** [wenzhixin/bootstrap-table#6235]
### Bootstraptable version(s) affected

1.20.2

### Description

I was trying to work with the advancedSearch module when i noticed that every time i activate an unvisible column using the showColumns button that after that the modal doesn't get updated with a new field for the shown column. Is there a work around for this?

### Example(s)

I created an  [jsfiddle](https://jsfiddle.net/yg6v14pb/4/) and a  [live bootstrap-table](https://live.bootstrap-table.com/code/mohamedbouzaien/11869)

**Comment by UtechtDustin** [comment]
You're right this is a bug, either the advencedSearch should show all colums regardless of visible or not or it should be in sync with the visible columnds.
I think it would make sense to sync the column states but add a option to always show/filter all columns (often you want to see just a few columns but filter them all).
