### ISSUE TITLE
Can I simulate a filtered search?

### ISSUE THREAD

**Issue by AndresConpas** [wenzhixin/bootstrap-table#6239]
### Description

I am using `server side pagination` and `filter-control`.

I have some buttons that make it easier for the user to search some 'usual' parameters.
When I press them, I make a generic search with their value, and this works well, is just a way of creating a shortcut for some usual searches.

But I don't want this to happen in the generic search bar but in a particular filter instead. 

I have managed to make the button set the value of the filter input to the one I want when pressed, but this doesn't fire the correct event since the URL generated by this action only comes with the `search` query param.

I have tried to trigger the event that provokes the URL where I retrieve the data to have the `filter` query parameter, but I haven't been successful so far.

Do you know of any way to accomplish this?

**Comment by UtechtDustin** [comment]
Write the filter to a object and append them to the query via [queryParams](https://bootstrap-table.com/docs/api/table-options/#queryparams).
To force the refresh you can use the [refresh](https://bootstrap-table.com/docs/api/methods/#refresh) method.

**Comment by UtechtDustin** [comment]
I close this issue, because we got no reply from you.
If you still need help let us know.
