### ISSUE TITLE
how can I get columns in 'onSort' function instead of only 'field' or 'order'

### ISSUE THREAD

**Issue by kaenry** [wenzhixin/bootstrap-table#625]
Because my sort column name is not the same as field name defined in columns

**Comment by wenzhixin** [comment]
可以的话还是用英文吧，因为很多时候是别人帮忙看问题。

**Comment by wenzhixin** [comment]
This problem, you can use `sortName` column option to do what you want: http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options
