### ISSUE TITLE
[Feature Request] Search Panes

### ISSUE THREAD

**Issue by roniemartinez** [wenzhixin/bootstrap-table#6254]
### Description

Similar to https://datatables.net/extensions/searchpanes/examples/

**Comment by UtechtDustin** [comment]
I'm not sure if we should add a new filter extension as we already have others to maintain.
This extension should also be possible to create with the existing options/methods like [filterControlContainer](https://bootstrap-table.com/docs/extensions/filter-control/#filtercontrolcontainer).

What do you think @wenzhixin @djhvscf  ?

**Comment by djhvscf** [comment]
Yes, definitely it could be done via filterControlContainer option also since there are too much extensions to maintain, I think, at this moment is not good idea to create new extensions.
