### ISSUE TITLE
有没有兼容安卓4.2的版本呢

### ISSUE THREAD

**Issue by RRRRAAAAYYYY** [wenzhixin/bootstrap-table#6259]
### Description

目前在做低安卓版本的混合开发，但是尝试了下在这个版本下不能正常显示，有没有兼容安卓4.2.2webview的版本呢？

**Comment by RRRRAAAAYYYY** [comment]
Is there a version compatible with Android 4.2.2?

**Comment by UtechtDustin** [comment]
I'm not sure which browser version will be used on that version.
But if it don't work it's not compatible and we will also not support it.
Android 4.2 was released 10 Years ago and is eol.

**Comment by RRRRAAAAYYYY** [comment]
the browser is android browser,the version information should be consistent with the Android version

**Comment by UtechtDustin** [comment]
As i said, if it don't work it's not compatible and we will not support it.
It's end of life and was released 10 years ago.

**Comment by RRRRAAAAYYYY** [comment]
> As i said, if it don't work it's not compatible and we will not support it. It's end of life and was released 10 years ago.

OK,ths
