### ISSUE TITLE
Personnalize the editable input

### ISSUE THREAD

**Issue by thibaultvanc** [wenzhixin/bootstrap-table#626]
Hello there
Wanted to use a select type  for editable
I saw the exemple for textarea on the page http://bootstrap-table.wenzhixin.net.cn/extensions/

My question is : 
how to pass the data to populate the select ?

Many Thanks

**Comment by djhvscf** [comment]
Have you seen this http://vitalets.github.io/x-editable/docs.html#editable?

**Comment by thibaultvanc** [comment]
Hello Dennis, 
Yes I saw this page,
but i don't know how to pass the data (from bootstrap table -> editable) to fill the select . 

Here is my javascript : 

$(function () {
    $('#table<?= $idcolonne ;?>').bootstrapTable({
    
        idField: 'id',
       search:true,
        url: '<?= pathy() ?>itblockit/block_passif_presentation/<?= $prefix ?>/data.json',
        columns: [{
            field: 'state',
            title: '',
            checkbox : true

        },{
            field: 'id',
            title: 'id',
            sortable : true,
        }, {
            field: 'name',
            title: 'name',
            sortable : true,
            editable: {
                type: 'text'
            }
        }, {
            field: 'price',
            title: 'Prix',
            sortable : true,
             editable: {
                type: 'select',
               /****************************************************/
                I think it should go there
              /****************************************************/  
                
               
            }
        }, {
            field: 'email',
            title: 'Mail',
            sortable : true,
            visible : false,
            radio : true,
            editable: {
                type: 'date',
                format: 'YYYY-MM-DD',    //rajouter les tags dans le fichierbootstrao_editable.js
                viewformat: 'DD.MM.YYYY',   //rajouter les tags dans le fichierbootstrao_editable.js 
                template: 'D / MMMM / YYYY',    
                combodate: {//rajouter les tags dans le fichierbootstrao_editable.js
                minYear: 2000,//rajouter les tags dans le fichierbootstrao_editable.js
                maxYear: 2015,//rajouter les tags dans le fichierbootstrao_editable.js
                minuteStep: 1//rajouter les tags dans le fichierbootstrao_editable.js
                }
            }
        }, {
            field: 'operate',
            title: 'Action',
            sortable : true,
            editable: false,
            formatter: "operateFormatter<?= $idcolonne ?>",
            events : "operateEvents<?= $idcolonne ?>",

        }]
    });
});

**Comment by djhvscf** [comment]
And have you seen this?? http://vitalets.github.io/x-editable/docs.html#select

**Comment by thibaultvanc** [comment]
yes .....

here is my column : 


{
            field: 'name',
            title: 'name',
            sortable : true,
            switchable : true,
            editable: {
                type: 'select',
                source: [
              {value: 1, text: 'Active'},
              {value: 2, text: 'Blocked'},
              {value: 3, text: 'Deleted'}
           ]
            }
        }

**Comment by thibaultvanc** [comment]
Do you have an idea or an example ?

**Comment by djhvscf** [comment]
ok, let me check something..

**Comment by djhvscf** [comment]
@thibaultvanc I think that feature is not implemented yet..

**Comment by thibaultvanc** [comment]
thanks  but in his issue, the guy seem to have succed, no ?
https://github.com/wenzhixin/bootstrap-table/issues/569

**Comment by Bengreen** [comment]
This is the table i use 
'editable': {
                        'type': 'select',
                        'title': 'Herd Tag',
                        'source': '/selector/animal/id/herd_tag',
                        'url': "/json/%s/id" % table,
                        'showbuttons': False,
                        'prepend': {None: "not selected",},
                        }

I find using a string is great and then using this to trigger an ajax call to the JSON data that i want to use for the select.
Then prepend adds some additional items that i dont have in the retrieved JSON.

**Comment by djhvscf** [comment]
Good! :+1:

**Comment by thibaultvanc** [comment]
It doesn't work for me :[
When I choose the "select" or "checklist" type, the table colums replaces all the value with the word "Empty" (as if it cannot read the JSON file)  , but if I switch the type to "text", the values are ok !!

![image](https://cloud.githubusercontent.com/assets/10731886/6706146/4acfa69e-cd5b-11e4-9407-ee4eec309e96.png)

Any idea, would be great !!

**Comment by thibaultvanc** [comment]
OK !!! :+1: 
I finally get it work
Thanks

**Comment by wenzhixin** [comment]
OK @thibaultvanc , close this issue.

**Comment by kodeine** [comment]
@wenzhixin @thibaultvanc 
i still get `empty` using the following column.

```
{
            field: 'name',
            title: 'Name',
            sortable: true,
            editable: {
                name: 'name',
                type: 'select',
                pk: '*[@id="table"]/tbody/tr/td[1]',
                source: [
                    {value: 1, text: 'Active'},
                    {value: 2, text: 'Blocked'},
                    {value: 3, text: 'Deleted'}
                ]
                //source: 'data'
            }
        }
```
