### ISSUE TITLE
Not able to apply style on XLSX export format using JS

### ISSUE THREAD

**Issue by vinaysavner** [wenzhixin/bootstrap-table#6262]
### Bootstraptable version(s) affected

1.20.2

### Description

Hi, actually I want to apply bg color on some column on export to excel with format XLSX,
And I am using the from data method to show the data.
I am using this plugin https://github.com/hhurz/tableExport.jquery.plugin as suggested in Table Export page.
please help me to do this.
Thanks

**Comment by UtechtDustin** [comment]
Please provide us an example (using our [editor](https://live.bootstrap-table.com/)), im not sure what you do right now.
Also im not sure if this is possible with this plugin.

**Comment by vinaysavner** [comment]
@UtechtDustin thanks for the reply,
Please check this example I have created. I have to add bg color or any there kind of style to separate some columns.
[Example](https://live.bootstrap-table.com/code/vinaysavner/12140)

**Comment by UtechtDustin** [comment]
At first it would be great if you could provide an minimal example. Your examplemis quite bloated.
Could you please also link us the documentation of the export plugin which describes the options for bg color ?
I also have to tell you that you don't used our export extension, you used the export plugin within you're own functions, so im not sure if your issue is on the correct repository.

**Comment by vinaysavner** [comment]
For the minimal example I have removed the lengthy object from the current example.
Here is the link of bootstrap-table export plugin suggested in the by bootstrap-table.com.
[export pligin](https://examples.bootstrap-table.com/index.html#extensions/export.html) This is awesome plugin to fulfill my requirements but only one this is not available there that is the styling with the XLSX excel format.
And Yes I have used bootstrap plugin already mentioned in the description of this issue.
May be my issue is not for the current repository but this export plugin I found in the bootstrap-table documentation.

**Comment by UtechtDustin** [comment]
Sorry, but you don't provided a new minimal example.
Also i don't think we can help here, we just use the export Plugin within our export extensions (which you don't even use...).
I saw you already opened a [issue](https://github.com/hhurz/tableExport.jquery.plugin/issues/354) in the repository of the export plugin.
They can maybe help you.
