### ISSUE TITLE
Toolbar tabbing order is wrong for 508 compliance

### ISSUE THREAD

**Issue by bsherman101** [wenzhixin/bootstrap-table#6263]
### Description

I am using bootstrap-table extensively and my application needs to be 508 compliant.

The search text field in the toolbar is displayed to the left of the button toolbar but in the html it is rendered afterwards.

This causes the search field to be skipped over when tabbing from one to the next.  It first cycles through all the buttons in the toolbar and then jumps back to the search field.

I'd like to keep the layout as is and simply have the toolbar render first so it tabs first.

**Comment by UtechtDustin** [comment]
Could you please provide us an example using our [editor](https://live.bootstrap-table.com/) ?

**Comment by UtechtDustin** [comment]
I close this issue, because we got no example from you within 7 days.
If you still need help please provide us an example and we will reopen the issue, thanks!
