### ISSUE TITLE
Question - any known compatibility issues with BST1.18.3 & iOS v13+ ?

### ISSUE THREAD

**Issue by michaelresser** [wenzhixin/bootstrap-table#6271]
### Description

Hello! fantastic product! 

We are running into an odd issue with BST not generating tables off existing HTML in any browsers running on iOS devices v13+ 

Feature works fine on Windows, Android and OSx, using all browsers.

Just a query to see if there are any known compatibility issues with this legacy release and the more modern iOS releases (13, 14 15.x) ?

Thank you.

**Comment by UtechtDustin** [comment]
I can only test it on IOS 15.5 and it works fine.
@wenzhixin or @djhvscf do you maybe a have a older version ?

**Comment by wenzhixin** [comment]
Sorry, I don't have an older version device.

**Comment by djhvscf** [comment]
I don't have a IOS device at all. Did you test it in Safari only? @michaelresser

**Comment by michaelresser** [comment]
Hi team thanks so much for your quick response. Love your product.

We were testing using Browserstack an noticed an issue with certain tables
not rendering on iOS devices only, for iOS v13 & up.

We did find that it wasn't in fact bootstrap table, it was a caching issue
with another library.

You may close this ticket.

Michael R. Esser
e: ***@***.***
m: 404-556-0084

**Comment by UtechtDustin** [comment]
Thank you for the feedback!
