### ISSUE TITLE
Multi sort extension: showMultiSortButton default behavior

### ISSUE THREAD

**Issue by tomalla5120x** [wenzhixin/bootstrap-table#6274]
### Bootstraptable version(s) affected

1.18.0 and above

### Description

Version 1.18.0 introduced a (faulty in my opinion) behavior of the multi-sort extension:

https://github.com/wenzhixin/bootstrap-table/commit/93c4b0f5e6bd0799b01b0e92f2533a3fee9b2e9a#diff-72b9dc228479d427dd79d91fc54c0ee5558df0d5ef969dad6c73a3f693b02669R595

The code responsible for adding the multi-sort button was moved outside the `if (this.options.showMultiSort)` statement. As a consequence all bootstrap tables with the multi sorting disabled (parameter `data-show-multi-sort` set to false) have the multi-sort button visible (unless explicitly hidden with the `data-show-multi-sort-button` parameter set to false). Although visible the button doesn't have any onclick handlers attached so it doesn't work anyways.

The last bootstrap-table version which works as expected is 1.16.0 (for some reason version 1.17.1 is producing a javascript runtime error, even in the fiddle above).

I've found the following issue back from 2020 which mentions this problem: https://github.com/wenzhixin/bootstrap-table/issues/5343 however the main focus there was that the `data-show-multi-sort-button` parameter was **ignored** altogether. The issue was fixed by allowing you to explicitly hide the button. Unfortunately the default behavior of showing the button even when the multi sort is disabled remained as it was. I have found no other issues mentioning the problem.

### Example(s)

Here's the fiddle to recreate the error (version 1.18.0, but any version greater than that still works):

https://live.bootstrap-table.com/code/tomalla5120x/12120

Change the bootstrap-table version to 1.16.0 to see the problem disappear.

### Possible Solutions

I've fixed the problem temporarily by guarding the code for adding the multi sort button with the following if statement: `if (this.options.showMultiSort && this.options.showMultiSortButton)` (i.e. adding the `this.options.showMultiSort` condition suffices).

**Comment by UtechtDustin** [comment]
Good catch!
Thank you for the well described issue.
