### ISSUE TITLE
能否调整cell的padding?

### ISSUE THREAD

**Issue by hahahoosh** [wenzhixin/bootstrap-table#628]
![qq 20150318161950](https://cloud.githubusercontent.com/assets/11534797/6704982/f74ce25e-cd8a-11e4-9c78-d673a4c4e1be.png)
按钮把表格行顶的太高了，能否调整一下padding的尺寸

谢谢

**Comment by wenzhixin** [comment]
加上这个 class：http://getbootstrap.com/css/#tables-condensed 应该就可以了
