### ISSUE TITLE
Problem with version 1.6 data null fixScroll

### ISSUE THREAD

**Issue by angelfangulo** [wenzhixin/bootstrap-table#629]
I have a problem with this version when de json is null:

TypeError: data is null

fixedScroll = data.fixedScroll;

	
bootstr...able.js (línea 1645, col 12)
```
 BootstrapTable.prototype.load = function (data) {
        var fixedScroll = false;

        // #431: support pagination
        if (this.options.sidePagination === 'server') {
            this.options.totalRows = data.total;
            fixedScroll = data.fixedScroll;
            data = data.rows;
        } else if (!$.isArray(data)) { // support fixedScroll
            fixedScroll = data.fixedScroll;
            data = data.data;
        }

        this.initData(data);
        this.initSearch();
        this.initPagination();
        this.initBody(fixedScroll);
    };
```
This problem in version 1.3 did not have it

I modified the line and I have added and I've fixed:

        if(data){
	        // #431: support pagination
	        if (this.options.sidePagination === 'server') {
	            this.options.totalRows = data.total;
	            fixedScroll = data.fixedScroll;
	            data = data.rows;
	        } else if (!$.isArray(data)) { // support fixedScroll
	            fixedScroll = data.fixedScroll;
	            data = data.data;
	        }
	
	        this.initData(data);
	        this.initSearch();
	        this.initPagination();
	        this.initBody(fixedScroll);
        }

**Comment by djhvscf** [comment]
Did you add the "If (data)" validation, right?

**Comment by wenzhixin** [comment]
Hi @angelfangulo , before you use `load` method, you need to ensure the rationality of the data.
```
if (data) {
    $table.bootstrapTable('load', data);
}
```
