### ISSUE TITLE
How to dynamically modify custom buttons on bootstrap table？

### ISSUE THREAD

**Issue by yikang729** [wenzhixin/bootstrap-table#6292]
### Description

I use bootstrap table kit to render backend data. 

There is no problem to show data to my website.But I have a requirement that when the user presses the refresh button, it is possible to hide some custom buttons, and when the user presses the refresh button again, the custom button will be presented again. I am very confuse the final result is that it will be presented according to the initial settings at the beginning. When the user presses refresh, the custom button will not change....

This is the relevant information I found (ref:https://bootstrap-table.com/docs/api/table-options/#buttons)

below is my code:
```javascript
<table
  id="table"
  data-toggle="table"
  data-height="460"
  data-show-refresh="true"
  data-buttons="buttons">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
</table>

<script>
   var isShow = true;
  
  $('#table').on('refresh.bs.table', function (e, params) {
    console.log('123')
      $('#table').bootstrapTable('refreshOptions', {
        buttons: buttons,
      });
    });
  
  function buttons () {
    var showornot = isShow;
    isShow = !isShow;
    console.log(`showornot: ${showornot}, isShow: ${isShow}`)
    
    return {
      btnUsersAdd: {
        text: 'Highlight Users',
        icon: 'fa-users',
        render: showornot,
        event: function () {
          alert('Do some stuff to e.g. search all users which has logged in the last week')
        },
        attributes: {
          title: 'Search all users which has logged in the last week'
        }
      },
      btnAdd: {
        text: 'Add new row',
        icon: 'fa-plus',
        render: showornot,
        event: function () {
          alert('Do some stuff to e.g. add a new row')
        },
        attributes: {
          title: 'Add a new row to the table'
        }
      }
    }
  }
</script>
```

### Example(s)

https://live.bootstrap-table.com/code/yikang729/12225

**Comment by yikang729** [comment]
Later, I switched to this method to achieve my goal, but I still don’t understand why the above approach doesn’t work

```
<table
  id="table"
  data-toggle="table"
  data-height="460"
  data-show-refresh="true"
  data-buttons="buttons">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
</table>

<script>
   var i = 1;
  
  $('#table').on('refresh.bs.table', function (e, params) {
    console.log('123')
      $('#table').bootstrapTable('refreshOptions', {
        buttons: buttons,
      });
    });
  
  function buttons () {
    
    if(i%2===0) {
    i++;
    return {
      btnUsersAdd: {
        text: 'Highlight Users',
        icon: 'fa-users',
        render: true,
        event: function () {
          alert('Do some stuff to e.g. search all users which has logged in the last week')
        },
        attributes: {
          title: 'Search all users which has logged in the last week'
        }
      },
      btnAdd: {
        text: 'Add new row',
        icon: 'fa-plus',
        render: true,
        event: function () {
          alert('Do some stuff to e.g. add a new row')
        },
        attributes: {
          title: 'Add a new row to the table'
        }
      }
    }
    }
    else {
      i++;
      return {}
    }
  }
</script>
```

link: https://live.bootstrap-table.com/code/yikang729/12232

**Comment by UtechtDustin** [comment]
The buttons options should only be used to add new buttons and not to show/hide the buttons.
After the custom buttons was added the first time, the table adds a new option called `show<ButtonName>`.
This option decides if the button will be rendered or not, if you just update the buttons function this option will never be changed.

The `render` option just decide if the `show<ButtonName>` option has as default value `true` or `false` (as described in the documentation.

That means you have to do the following steps:
- Add the custom buttons via `buttons option` as before
- Listen for the refresh event
- Update show options, in your case `showBtnAdd` and `showBtnUsersAdd`.

Example: https://live.bootstrap-table.com/code/UtechtDustin/12258
