### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by pmtk** [wenzhixin/bootstrap-table#6293]
### Description

Hello

There were 3 releases around April-May and nothing since then. When can we expect another release?
Current develop branch contains relevant fixes which lack of is blocking.

Thanks!

**Comment by UtechtDustin** [comment]
@wenzhixin please check it!

**Comment by wenzhixin** [comment]
new release ref PRs:

* #6190
* #6203
* #6211
* #6223
* #6231
* #6232
* #6234
* #6247
* #6255
* #6256
* #6257
* #6260
* #6275
* #6283
* #6287
* #6298
* #6299
* #6300
* #6301
* #6302
* #6303
* #6310
* #6311

**Comment by UtechtDustin** [comment]
@wenzhixin any updates ?
I think a release should not last 5 days, can we (@djhvscf or me) help out ?

**Comment by djhvscf** [comment]
Sure. We could schedule a call in order to transfer the knowledge about how to create a release version. @wenzhixin @UtechtDustin

**Comment by UselessGuru** [comment]
Any news?

**Comment by UtechtDustin** [comment]
Again 6 days later, any news @wenzhixin  ?

**Comment by wenzhixin** [comment]
> @wenzhixin any updates ? I think a release should not last 5 days, can we (@djhvscf or me) help out ?

Since there are several steps to releasing a new version that requires manual operation, I am currently writing an automation script.

**Comment by wenzhixin** [comment]
> @wenzhixin any updates ? I think a release should not last 5 days, can we (@djhvscf or me) help out ?

Since there are several steps to releasing a new version that requires manual operation, I am currently writing an automation script.

**Comment by wenzhixin** [comment]
Done! Bootstrap Table v1.21.0 released!
