### ISSUE TITLE
Filter Control on api call 

### ISSUE THREAD

**Issue by piccio123** [wenzhixin/bootstrap-table#6294]
### Description

Hi,
I'm using django (4.0.6) bootstrap (5.2) jquery (3.6.0) and bootstrap-table (1.20.2) and i'd like to use the extension "filer control" to a table generated on an api call. I read that I would use "filterDataCollector".

I'm a newbee, I need more info or some example because I didn't found anything on the net.

Could someone give me an example?

Thanks

**Comment by UtechtDustin** [comment]
I'm not sure if i understand your question correctly.
Do you ask how you can fill the select options from data which come from a api request ?

**Comment by piccio123** [comment]
I need to use the extension "filter control" in a table generated with an api request.
How can i?

**Comment by UtechtDustin** [comment]
I still don't understand you question...
What does the api request returns, data for filtering, data for the table or the table as html ?
Without more information we can't help.

**Comment by piccio123** [comment]
Ok, I'm very sorry, and I thanks you very much.

The api returns data for the table (i hope)
I put here the code I use. The page i generated as expected (but without filter), and all file (js, css and so on) are sucesfully loaded  (seen from Firefox Developer Tools)

model.py
======================
from django.db import models

class TestTable(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    name = models.CharField(db_column='NAME', max_length=100)
    descr = models.TextField(db_column='DESCR')
    type = models.CharField(db_column='TYPE', max_length=50)

  class Meta:
        managed = False
        db_table = 'TEST_TABLE'
======================

view.py
======================
from django.views.generic import ListView

from .models import TestTable

###Test
class TestTableListV(ListView):
    title = "Test Table"
    model = TestTable
    template_name = "trama/list.html"
======================

list.html
======================
{%extends  'base.html'%}
{%load static%}

{%block title%}
    {{view.title}}
{%endblock%}

{%block heading%}
    {{view.title}}
{%endblock%}

{%block content%}
    <table class="table table-striped" 
            id="table"
            data-filter-control="true"
            data-show-search-clear-button="true"
            data-searchable="true">
        <thead>
            <tr>
                <th data-field="id">ID</th>
                <th data-filed="title" data-filter-control="input">Title</th>
                <th data-filed="descrizione" data-filter-control="input">Descrizione</th>
                <th data-filed="tipologia" data-filter-control="select">Tipologia</th>
            </tr>
        </thead>
        <tbody>
            {%for a in object_list%}
            <tr>
                <th>{{a.id}}</th>
                <th>{{a.name}}</th>
                <th>{{a.descr|linebreaks}}</th>
                <th>{{a.type}}</th>
            </tr>
            {%endfor%}
        </tbody>
    </table>
{%endblock%}
======================

base.html
======================
{%load static%}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>
            {%block title%}
            {%endblock%}
        </title>
        <link rel="stylesheet" href="{% static 'bootstrap-table/bootstrap-table.css'%}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css'%}">
        <link rel="stylesheet" href="{% static 'fonts/default.css'%}">

        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico'%}">
        <style>
            body {font-family: 'Quattrocento';font-size: 22px;}
        </style>
    </head>

    <body>
        <div class="text-center">
            <h1>
                {%block heading%}
                {%endblock%}
            </h1>
        </div>

        <div class="container mt-3">
            {%block content%}
            {%endblock%}
        </div>
      
    <script src="{% static 'jquery/jquery.js'%}"></script>
    <script src="{% static 'popper/popper.js'%}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js'%}"></script>
    <script src="{% static 'bootstrap-table/bootstrap-table.js'%}"></script>
    <script src="{% static 'bootstrap-table/extensions/filter-control/bootstrap-table-filter-control.js'%}"></script>
    </body>
</html>
======================

**Comment by UtechtDustin** [comment]
There are a lot off issues.
At first i don't see 
```
data-toggle="table"
```
or
```
$('#table').bootstrapTable()
```
which means the bootstrap-table was never used/activated.

You used the `column option` `searchable` on the `table` itself not on the `columns`.
There are typos `data-filed` instead of `data-field`.
You also used `th` instead of `td` for the tbody columns, which will not break the functionality but is odd :D 

In the following example you can see how the html should/could look like after it was rendered by django.
Example: https://live.bootstrap-table.com/code/UtechtDustin/12257

**Comment by piccio123** [comment]
It works!
Thank you very much!

**Comment by piccio123** [comment]
it works!
Thank you very much!
