### ISSUE TITLE
[Editor] Extensions search is broken

### ISSUE THREAD

**Issue by UtechtDustin** [wenzhixin/bootstrap-table#6297]
### Description

If you search for a extension e.g. `filter-control` the extensions will not be filtered and the following error appeared in the console.
```
Uncaught TypeError: t.includes is not a function
```

**Comment by djhvscf** [comment]
I can confirm that it is happening to me also

**Comment by UtechtDustin** [comment]
I also often have the issue that i get the message `Please sign in first!`, but in the top right it shows that im still logged in.

**Comment by wenzhixin** [comment]
> ### Description
> If you search for a extension e.g. `filter-control` the extensions will not be filtered and the following error appeared in the console.
> 
> ```
> Uncaught TypeError: t.includes is not a function
> ```

![image](https://user-images.githubusercontent.com/2117018/183074114-4b948602-ca25-420c-a3fd-34bc6e98d58d.png)
Fixed!

**Comment by wenzhixin** [comment]
> I also often have the issue that i get the message `Please sign in first!`, but in the top right it shows that im still logged in.

Please help to check the Console.
What status code when you get the message `Please sign in first!`?
https://github.com/wenzhixin/bootstrap-table/issues/6297#issuecomment-1204488840

**Comment by UtechtDustin** [comment]
@wenzhixin 
Thanks for the fix of the extension search!
Currently i don't get the `Please sign in first!` error, as soon i get it i will note some more information and open a seperate issue for it.
