### ISSUE TITLE
Trying to build from source but getting TypeError

### ISSUE THREAD

**Issue by maxsupermanhd** [wenzhixin/bootstrap-table#6308]
### Bootstraptable version(s) affected

develop 2125004

### Description

So I cloned repository, run `npm run build` and it failed with `sh: 1: run-s: not found`

First thing that I did is I searched here for any issues, found one that suggested to do `yarn add npm-run-all --dev`

After I did that I am getting following error wall:
```
Oops! Something went wrong! :(

ESLint: 8.21.0

TypeError: Module.createRequire is not a function
    at Object.<anonymous> (/home/max/p/bootstrap-table/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2383:26)
    at Module._compile (/home/max/p/bootstrap-table/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/max/p/bootstrap-table/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/max/p/bootstrap-table/node_modules/eslint/lib/cli-engine/cli-engine.js:33:5)
    at Module._compile (/home/max/p/bootstrap-table/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bootstrap-table@1.20.2 lint:js: `eslint src`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bootstrap-table@1.20.2 lint:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/max/.npm/_logs/2022-08-02T22_28_16_563Z-debug.log
ERROR: "lint:js" exited with 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap-table@1.20.2 lint: `run-s lint:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap-table@1.20.2 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/max/.npm/_logs/2022-08-02T22_28_16_593Z-debug.log
ERROR: "lint" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap-table@1.20.2 build: `run-s lint clean *:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap-table@1.20.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/max/.npm/_logs/2022-08-02T22_28_16_630Z-debug.log
```

I really want filters to be fixed but don't want to wait for next release...

**Comment by djhvscf** [comment]
Did you run npm install?

**Comment by maxsupermanhd** [comment]
No, should I? It is not mentioned in local [build section of readme](https://github.com/wenzhixin/bootstrap-table#local-build) so why would I do that? Also I am no javascript nor npm expert.
So I did what you suggested and it said `found 4 vulnerabilities (3 moderate, 1 high)`, probably a bad thing but anyhow, rerunning `npm run build` resulted in same error.

**Comment by UtechtDustin** [comment]
I think `npm install` is not written down, because its a command which every (javascript) developer instantly run before he starts working on a project.
`run-s` is part of the [npm-run-all](https://www.npmjs.com/package/npm-run-all) package, which will be installed while execute `npm install`.

But i guess we can add `npm install` to the readme :-)
I quickly checked the vulnerabilities. Which seems don't be relevant for the BT, but we will update the dependencies to resolve this issue.

**Comment by maxsupermanhd** [comment]
But still after doing `npm install` it seems to fail with initial error...

**Comment by UtechtDustin** [comment]
I don't miss that part, just don't had time to check it.
Which node version do you use, it seems this issue is related to older node versions.
For me the building works fine with `node v16.14.0`

**Comment by maxsupermanhd** [comment]
```
$ node --version
v10.19.0
```

**Comment by maxsupermanhd** [comment]
Is there any way to download latest master builds from somewhere without building them by yourself?

**Comment by UtechtDustin** [comment]
No, but you could update your node version or if you need this version you could use [nvm](https://github.com/nvm-sh/nvm) to temporary switch to a newer version.
