### ISSUE TITLE
Add icon and link based on data which is passed in bootstrapTable function

### ISSUE THREAD

**Issue by Thomas5588** [wenzhixin/bootstrap-table#6314]
### Description

Hi,

I'm using Bootstrap-Table Treegrid to show the folders and files in tree view structure. Here I want to add Icons and links to the file item, do we have any options to add icons and add link based on the data (like the data item has property type and based on this type value) which is passed in bootstrapTable function?

**Comment by UtechtDustin** [comment]
You can use a [formatter](https://bootstrap-table.com/docs/api/column-options/#formatter) for this.

**Comment by Thomas5588** [comment]
Thanks
