### ISSUE TITLE
How we can remove treegrid-expander span element in TreeGrid

### ISSUE THREAD

**Issue by Thomas5588** [wenzhixin/bootstrap-table#6316]
### Description

Hi Team,

I'm using Treegrid to build data in tree view and treegrid-expander option is added when a item has no children. I want to remove the treegrid-expander option when there is no child for an item.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by Thomas5588** [comment]
Hi,

I have submitted my example, please take a look. In this you can see the Expander click option is available for the item (File1.txt, File2.txt) has no child.
If there is no child item then I think we don't need expander clickable option.

**Comment by UtechtDustin** [comment]
Hi @Thomas5588, you don't posted the url to the example ;)

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we don't got any response from you.
If you still need help, let us now and provide us an example.
