### ISSUE TITLE
Error while sorting a column with numbers and strings

### ISSUE THREAD

**Issue by kaumasse** [wenzhixin/bootstrap-table#632]
I use the 1.6 release and I got an error while sorting a column with numbers and strings.

If the column contains only strings e.g. "a,b,c" or only numbers e.g. "1,2,3" sorting works. But if you have both you got a comparer error "aa.localeCompare is not a function" in "BootstrapTable.prototype.initSort".

Thank you.

**Comment by djhvscf** [comment]
We have this https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/sorting/bootstrap-table_natural-sorting.js .. test it and let us know

**Comment by kaumasse** [comment]
It worked, thanks a lot! It would be cool if you could define a column sorter as default, which will be overridden if you define it on column level.

**Comment by Shobana16** [comment]
only two columns are working fine for sorting and searching. But rest two are not working. can you please check and help? Options i used are below: 
data-pagination="true" 
data-page-size="10" data-page-list="[10, 20, 50, All]"
data-search="true" data-hover="true" data-striped="true" data-sort-order="asc" data-sort-name="create_time"
data-field="create_time" data-align="center" data-formatter="formatCreateTime" data-sortable="true">Request Time
data-field="url" data-align="left" data-formatter="formatUrl" data-sortable="true" data-events="clickUrlEvent">Resource
data-field="method" data-align="center" data-formatter="formatMethod" data-sortable="true" >Method
data-field="status" data-align="center" data-formatter="formatStatus" data-sortable="true" >HTTP Status
data-field="id" data-align="center" data-sortable="true" data-visible="false">Id

**Comment by djhvscf** [comment]
Please provide a fiddle in order to test this issue

**Comment by Shobana16** [comment]
Sure will send it in few mins. Can you please tell what are the necessary library js has to be included for this functionality?

**Comment by djhvscf** [comment]
This is the link https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/natural-sorting/bootstrap-table-natural-sorting.js

**Comment by Shobana16** [comment]
Thank you for the link. Do i need to include the functionality in bootstrap-table.js itself? i see that version is 1.0, will it work in latest version of bootstrap-table.js?

**Comment by Shobana16** [comment]
hi,

I have a data formatter for two columns. 
function formatCreateTime(value, row, index) {
        return [
            row['create_time'].replace('T','  ').replace('Z',' GMT'),,''
        ].join('');
    }
function formatMethod(value, row, index) {
        return [
            row['api_request']['method'],,''
        ].join('');
    }
    function formatStatus(value, row, index) {
        return [
            '',row['api_response']['status'],''
        ].join('');
    }

if this is the case, then only first one was able to be filtered because in initisearch(), the filetring is done based on the key and their value. 
So here in first method, key is create_time and the value is direct one with timestamp where it can be filtered. 
but if you take next method formatMethod or formatStatus, the key will be taken as api_request or api_response. but the values are not straight forward and that will be like below. 
![image](https://cloud.githubusercontent.com/assets/15118561/10816600/f110a6ac-7e59-11e5-85da-a6f2a677be66.png)

So value is object(...), inside that only we have method = "POST", so this is not filtered in table. 

can you please tell how can we filter the value inside the object?

**Comment by Shobana16** [comment]
In short, traversing to next level if key is an object is not done. So when key is taken as api_request, value is Object. Inside Object we have more no of keys which is not taken into consideration? Can you please tell what can be done to search along all objects ? 

I am just trying to change something for now. But please tell what will be the best way.

**Comment by Shobana16** [comment]
It will be very helpful if this issue is resolved soon. Because unfortunately we planned to push filtering for our tool tomorrow and these two columns are not filtered due to this reason :(

**Comment by Shobana16** [comment]
Got it. It worked now. !!!! Just made some changes in my js code. bootstrap is fine!

**Comment by lbelof** [comment]
@Shobana16 Hi, I have the same problem.
How did you solve it?
