### ISSUE TITLE
FilterControl is not working with filterDefault and a second field

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#6324]
### Bootstraptable version(s) affected

1.20.2

### Description

The problem is that the rows are not filtered when the value in the select box in not the default one and another field is used to specify a value to filter

### Example(s)

https://live.bootstrap-table.com/code/sdespont/12383

![screen-recording-2022-08-09-09_37 (1)](https://user-images.githubusercontent.com/646632/183596208-f4f11be8-5309-4333-a50e-7315ba96d1a9.gif)

**Comment by UtechtDustin** [comment]
Fixed in #6325
