### ISSUE TITLE
Fixed rows or multiple th headers rows

### ISSUE THREAD

**Issue by caholt** [wenzhixin/bootstrap-table#633]
Hello, 
is it possible to have fixed rows that always show when scrolling like the header or maybe have multiple header rows?

I have tried multiple header rows but it combines all the header rows into one row.

Thank you.

**Comment by thibaultvanc** [comment]
Hello, I am not an expert with this fabulous pluggin, but see here : 
(set a height option)
http://bootstrap-table.wenzhixin.net.cn/examples/#columns

(no idea to have multiple header rows)

**Comment by caholt** [comment]
The height is not really the problem,
From what I can see the code always assumes that there is one header row and does not account for multiple header rows.

The result I am trying to achieve is to have multiple fixed rows along with the header row. So there would be 6 rows at the top and then the rest of the table scrolling.

Thank you.

**Comment by wenzhixin** [comment]
res #363, I will consider to add this feature.

**Comment by wenzhixin** [comment]
The same issue, close this one.
