### ISSUE TITLE
chosing page list "All" option while data-cookie is enabled crashes the table.

### ISSUE THREAD

**Issue by Nao-30** [wenzhixin/bootstrap-table#6336]
@wenzhixin 
### Bootstraptable version(s) affected

1.19.1

### Description

When the pagination side is from server.
and have the `data-cookie="true".
when i change the pagination page size and choose "All", the table works as expected displaying all the row.
the parameters also correct, the "offset" and "limit" exists.

But when i refresh the web page i got an error from the sql engine, then i realized there was no limit parameter sent.

the request contained only 
offset: 0
![image](https://user-images.githubusercontent.com/71417548/184964826-3380c625-393d-4b28-89e9-d71cfcc4cb3f.png)

causing an error in my query and it won't work till i clear the cookies from my browser.

that's why i was kind of sure it is bcuz of the cookies feature along with using the All page size.

is there any fix already or??? i really need to solve it. thx in advance.

### Example(s)

[example1](https://live.bootstrap-table.com/code/Nao-30/12454)

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by Nao-30** [comment]
> Please provide us an example using our [editor](https://live.bootstrap-table.com/).

@UtechtDustin 
i updated the issue and provided an [example](https://live.bootstrap-table.com/code/Nao-30/12450).

in the editor it works normal sometimes but i guess because the url is loading data from a json file, so i don't think missing the limit parameter can cause a problem it depends how the table is handling the data.
 for me when i'm using it with php and mysql, it causes some issues to the query. of-course i can do some back-end check and only do pagination if both offset and limit exist but, i still think the cookie should still save the status of the table correctly when the page list size "All"  is selected.

**Comment by UtechtDustin** [comment]
In your example the cookie extension is not enabled.
But even if i enable the cookie extension anything works fine.

I'm not sure if i understand the issue, because we don't send the `limit` parameter with or without the cookie extension if the option `ALL` was selected.
See here: https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1945-L1947

**Comment by Nao-30** [comment]
@UtechtDustin 
yes actually i don't know why it's not enabled but that's clarify the issue,
I didn't know that because when i'm using it in my laravel project it still sends the limit parameter
here you can see with the debugger tho,
![image](https://user-images.githubusercontent.com/71417548/185081607-34922c70-667f-43cd-898a-1e3205c6ac2d.png)
it shows 1 to 10 out of 21 record

when i chose the 'All' option 
![image](https://user-images.githubusercontent.com/71417548/185081884-42485352-7496-4388-8e3b-436c9e401f65.png)
it shows 1-21 out of 21 and the request is as follow
![image](https://user-images.githubusercontent.com/71417548/185082028-7bc95ef3-59f1-40a8-a0b3-15b209851711.png)
there is no issue yet, till i reload the page i get an error in my query
![image](https://user-images.githubusercontent.com/71417548/185082298-9e71238c-2692-4682-b751-bfbae4c45fa6.png)
and here's the reason in the debugger 
![image](https://user-images.githubusercontent.com/71417548/185082413-beb53cd8-8c36-4c6b-8724-da4771bdea85.png)

that's why i thought it was a mistake because the table still sends the limit parameter when i chose the All option, but if i reload the page, the cookie handles the view of the table but it does not send the limit parameter and so i thought it might be a bug, what do u think.

**Comment by UtechtDustin** [comment]
The cookie extension is not enabled, because you don't selected it as extension in the editor.
Your example with enabled cookie extension: https://live.bootstrap-table.com/code/UtechtDustin/12453

We only append the limit parameter if needed and its only needed if we have a limit which is not the case if `All` is selected.
You have to check if the limit param exists, if yes you have to modify your mysql query.

**Comment by Nao-30** [comment]
i know i already updated the [examples](https://live.bootstrap-table.com/code/Nao-30/12454) above, and enabled the cookie extension.
you r right it does not send the limit parameter in the editor but why in my project the limit parameter is passed as well when i chose the All option ,as provided in the pictures above.

i saw the [code](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1945-L1947) you sent
it makes now. if the cookie extension does not save the limit parameter value in case of choosing All option , then everything makes sense now that it is not sending the limit.

i guess for now i can only check the request and do a pagination if both offset and limit exists.

now that i remember i had similar issue when exporting the table using the export all option, always exported empty file, after debugging the issue was from the request, sometimes contained the offset and sometimes no parameter is sent at all.

if they are working the same way somehow then it's all clear now.

although i think it would be better to handle it all using these two parameters, i'll try to work on it.
for now i'll change my backend code and manipulate the query a lil bit.

thanks anw tho.
