### ISSUE TITLE
how to add some other conditions to fetch the data from server? 

### ISSUE THREAD

**Issue by davidmeng** [wenzhixin/bootstrap-table#634]
Hi,
I want to add more conditions to fetch the data, such as some drop list or other input text area. Now I add a method in the bootstrap-table.js to set url manually. 
Many thanks.

**Comment by djhvscf** [comment]
Do you have some code ?? I need to see what you need

**Comment by davidmeng** [comment]
I don't have code, For example, data-url="/examples/bootstrap_table/data".
What I want to submit is /examples/bootstrap_table/data?categoryId=1&subCategory=1&userId=1
What should I do?
All the parameters are editable.
Thanks

**Comment by davidmeng** [comment]
And I am know whether all these parameters are existed.

**Comment by djhvscf** [comment]
But in your commet you say that you add a method to the source code.. Can we see it?

**Comment by davidmeng** [comment]
BootstrapTable.prototype.setUrl = function(url){
    	
    	this.options.url = url;
    }

It's my way, I can set the parameters in the url and I know it's not elegant.

**Comment by davidmeng** [comment]
Is there any other methods to add the parameters?
Thanks.

**Comment by djhvscf** [comment]
Maybe this: http://issues.wenzhixin.net.cn/bootstrap-table/#386.html

**Comment by wenzhixin** [comment]
use `queryParams` option
