### ISSUE TITLE
Add a checkbox to filter lines

### ISSUE THREAD

**Issue by Zazou49** [wenzhixin/bootstrap-table#6343]
### Description

Hello,
Is it possible to add a checkbox which, when checked, hides the lines whose term was found in it? I think I found the option but I don't quite understand how to do the script. 

### Example(s)

https://live.bootstrap-table.com/code/Zazou49/12509

Update: I tested something, it doesn't work but I feel I'm close. Any ideas?

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/12511

**Comment by Zazou49** [comment]
Hello @wenzhixin,
Thank you for your answer, in your example it returns only "Blacklist" rows if checked, I want to hide these lines if checked. Is it possible to do this ? Thank you !

**Comment by UtechtDustin** [comment]
That is correct!
Example: https://live.bootstrap-table.com/code/UtechtDustin/12513

**Comment by Zazou49** [comment]
Thank you @UtechtDustin, 
I take the liberty of abusing your kindness, is it possible to have the box checked by default and if I uncheck, it hides the lines with the word "Blacklist". I tried to edit my example but I can't get it to work.

**Comment by UtechtDustin** [comment]
Seems working, except that the checkbox label is now inversed.
It should be `Show Blacklist`.

**Comment by Zazou49** [comment]
Yes you're right ! Thank you :)
