### ISSUE TITLE
Exclude formatting / html from search

### ISSUE THREAD

**Issue by Zazou49** [wenzhixin/bootstrap-table#6347]
### Description

Hello,

I'm using HTML and formatting option in my table, but when I'm doing a search, it also search in HTLM formatting, is it possible to exclude HTML formatting from search ? 

### Example(s)

Example if you search `example` or `imgur` it returns results. I don't want this.

https://live.bootstrap-table.com/code/Zazou49/12517

**Comment by UtechtDustin** [comment]
Like that ?
https://live.bootstrap-table.com/code/UtechtDustin/12518

**Comment by Zazou49** [comment]
Hello,
No sorry, because for example, for name, it doesn't return `item 1` or `item 2` if searched.
https://live.bootstrap-table.com/code/Zazou49/12519

**Comment by UtechtDustin** [comment]
Then you have to use [filterCustomSearch](https://bootstrap-table.com/docs/extensions/filter-control/#filtercustomsearch) or you can create the html elements with a [formatter](https://bootstrap-table.com/docs/api/column-options/#formatter) and then ignore the result from the formatter using [searchFormatter](https://bootstrap-table.com/docs/api/column-options/#searchformatter).

You also can search on the closed issues, there are a lot of examples.

**Comment by Zazou49** [comment]
Thank you @UtechtDustin I'll check that !
