### ISSUE TITLE
Add export extension to cdnjs

### ISSUE THREAD

**Issue by alexz707** [wenzhixin/bootstrap-table#635]
Hi!
Can someone please add the export extension to the cdnjs site ( https://cdnjs.com/ )?
I don't know how to do it...
thanks a lot!
regards alex

**Comment by djhvscf** [comment]
@wenzhixin can you this, right?

**Comment by wenzhixin** [comment]
I will try to add the extensions in next version.

**Comment by wenzhixin** [comment]
https://github.com/cdnjs/cdnjs/pull/4510
