### ISSUE TITLE
The filter-control with type datepicker does not filter if the date column is formatted

### ISSUE THREAD

**Issue by manhart** [wenzhixin/bootstrap-table#6358]
### Bootstraptable version(s) affected

1.21.0

### Description

In my opinion the filter control for the type datepicker should filter independent of the formatting. Because the HTML element input type="date" always returns the date in English (this is the default) or as timestamp/number. The data for the table column is passed as a string in English format by default.

The filter control element takes the formatted data instead of the original data. This can be applied to all other filters except the datepicker. Because we have no influence on the HTML element (as an option) that the date should be returned e.g. in German.

### Example(s)

https://live.bootstrap-table.com/code/manhart/12535

### Possible Solutions

Automatically handle the filter control type "datepicker" with the original value (and if the original is a number, work with the timestamp).
Or add a new option for the column to control the value to filter by: formatted data or original.

**Comment by UtechtDustin** [comment]
You're possible solution describes the [searchFormatter option](https://bootstrap-table.com/docs/api/column-options/#searchformatter).

Example: https://live.bootstrap-table.com/code/UtechtDustin/13869
