### ISSUE TITLE
1.21.0分页的时候,使用ALL的时候,传到后台的limit为0

### ISSUE THREAD

**Issue by allen3371** [wenzhixin/bootstrap-table#6362]
### Bootstraptable version(s) affected

1.21.0

### Description

Hi:
  thank you for your great work,
  i update to the version 1.21.0 ,when i select the 'ALL' item in the combobox ,my server receive the parament 'limit" is zero
the old version is good ,is this a bug?

 thanks!

**Comment by djhvscf** [comment]
Probably is a bug. Please provide an example
