### ISSUE TITLE
Sorting with null values crash (1.6.0)

### ISSUE THREAD

**Issue by Joralf** [wenzhixin/bootstrap-table#637]
Hi there,

Firstly: great addon for bootstrap. Simple and clean, well done!

For version 1.6.0 the sorting function does not work with null data (displayed as - in table). In the previous version, 1.5.0, this is not the case.

I get the following error in console:

Uncaught TypeError: undefined is not a function
bootstrap-table.min.js:7 (anonymous function)
bootstrap-table.min.js:7 h.initSort
bootstrap-table.min.js:7 h.onSort
bootstrap-table.min.js:7 (anonymous function)
jquery-1.11.2.min.js:3 m.event.dispatch
jquery-1.11.2.min.js:3 r.handle

I'll try and debug a bit, but my js knowledge is not that great unfortunatly.

**Comment by djhvscf** [comment]
Maybe this can help you https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/sorting

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle @Joralf
