### ISSUE TITLE
UpdateRow fails when data-formatter is set

### ISSUE THREAD

**Issue by Sisytec** [wenzhixin/bootstrap-table#6378]
### Description

When I set a function with data-formatter, "UpdateRow" doesn't works.
Are we doing something wrong?

Regards,
Emilio CS

### Example(s)

data-formatter empty, UpdateRow works fine:

[https://live.bootstrap-table.com/code/Sisytec/12772](https://live.bootstrap-table.com/code/Sisytec/12772)

data-formatter with function, UpdateRow doesn't works:

[https://live.bootstrap-table.com/code/Sisytec/12774](https://live.bootstrap-table.com/code/Sisytec/12774)

**Comment by UtechtDustin** [comment]
It's not an bug.
You're `formatter` depends on the property `status`, but the status will never be updated (via `updateRow`).
Also you formatter if/else is the wrong way round.

Working example: https://live.bootstrap-table.com/code/UtechtDustin/13015
Minimal example: https://live.bootstrap-table.com/code/UtechtDustin/13017
