### ISSUE TITLE
总行数在110-160之间的时候虚拟滚动无法滚动到底部

### ISSUE THREAD

**Issue by Still4** [wenzhixin/bootstrap-table#6379]
### Bootstraptable version(s) affected

1.19.1

### Description

监听了下虚拟滚动的事件，发现当滚动到100行以后会预加载下一页，也就是150-350行的数据，加载出来的数据似乎判定为无效，会再次加载0-200行的数据，表现上就是最后100以后的行无法显示，滚动条到对应位置会短暂白屏，然后跳回100行的位置

**Comment by Still4** [comment]
更新下，临界行数不是110-160，跟页面可显示行数有关，应该是100+x和150+x

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!
麻烦提供下例子。

**Comment by Still4** [comment]
出现问题的表格比较复杂，尝试做了下简化

简化的过程中发现问题原因在第二列，有些行折行了，似乎影响了高度的计算？

https://live.bootstrap-table.com/code/Still4/12781

**Comment by wenzhixin** [comment]
目前是基于每一行相同的高度实现的，你可以增加 `td { white-space: nowrap; }` 来解决问题。
https://live.bootstrap-table.com/code/wenzhixin/18243

增加说明到文档中：

> Currently, the implementation assumes that each line has the same height. If the heights of the lines vary, unpredictable bugs may occur. Please ensure that the height of each line is consistent, or apply the style `td { white-space: nowrap; }` to address this issue.
