### ISSUE TITLE
Footer code issue

### ISSUE THREAD

**Issue by alcordier** [wenzhixin/bootstrap-table#638]
There is a typo in BootstrapTable.prototype.resetFooter at line 564:

`            if (that.options.cardView && (!column.cardVisible)) {
                return;
            }`

should be :

`            if (bt.options.cardView && (!column.cardVisible)) {
                return;
            }`

**Comment by djhvscf** [comment]
yes, you are right @alcordier I think this is a potential issue

**Comment by djhvscf** [comment]
@wenzhixin This is already fixed

**Comment by wenzhixin** [comment]
Fixed
