### ISSUE TITLE
Dropdown for bootstrap 4

### ISSUE THREAD

**Issue by SuperBoy17** [wenzhixin/bootstrap-table#6380]
### Bootstraptable version(s) affected

1.19.1

### Description

你好，能不能帮我解决这个问题呢？
![Capture1](https://user-images.githubusercontent.com/112933534/189097445-2ccf3670-a520-43c0-8a92-be7026749e22.JPG)
![Capture](https://user-images.githubusercontent.com/112933534/189097449-f1ea0df7-e405-40fd-95b0-f371635ed08c.JPG)

谢谢

**Comment by wenzhixin** [comment]
应该是引入库不全，自己看下：https://bootstrap-table.com/docs/getting-started/introduction/#starter-template
或者 https://bootstrap-table.com/themes/bootstrap4/#starter-template

**Comment by SuperBoy17** [comment]
谢谢你的回答，但有个疑问，如果改css或js file都无法改变吗？

**Comment by wenzhixin** [comment]
无法改变是什么意思呢？

**Comment by SuperBoy17** [comment]
比方说我找到这些source code在bootstrap-table.min.js里，我尝试改一些关于这问题的地方，但改了都没什么变化，所以想问就算改了也没变化吗？

**Comment by SuperBoy17** [comment]
顺便一提，我用着v2.3.1的bootstrap，如果升级以上的话，其他地方会影响，能的话有方法改吗？非常感谢
