### ISSUE TITLE
Localization files in DIST and SRC folder

### ISSUE THREAD

**Issue by dpastov** [wenzhixin/bootstrap-table#6387]
### Description

I have a few questions in regards in locale files.

1) Why files in ditst/locale are way bigger than in src/locale? What is more proper to use? I could see that origianlly (version 1.13 file were smaller while starting from 1.15 file become bigger x6 times and within time it grew even more.

2) If I only need 3 locale (and want to concatenate them into 1 file) is it OK just to copy/paste code from src/locale files into 1 file?

### Example(s)

This one contains only translation
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.13.0/locale/bootstrap-table-zh-CN.min.js

While this one become much bigger.
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.15.0/locale/bootstrap-table-zh-CN.min.js

**Comment by UtechtDustin** [comment]
1. The source code is the raw code for (internal) development purposes (And should never be used for production applications).
    While releasing a new Version of the BT, we use some Tools to optimize and minimize the source code.
    That the files becomes (6x) bigger could have a lot of reasons, one reason is that the locale files has more (complex) translations. Another reason is that we maybe support more browsers, which means the source code will be optimized for multiple browser.
    @wenzhixin  maybe you can describe this better, it's your part :-)
2. Should be okay i guess :-)

**Comment by wenzhixin** [comment]
Because of 1.15, we modified the source code from ES5 to ES6 and then compiled it to a dist file using babel, which needed to fit all popular browsers, resulting in the final compiled file will be larger than the original.

> If I only need 3 locale (and want to concatenate them into 1 file) is it OK just to copy/paste code from src/locale files into 1 file?

It's OK if you don't need to support older browsers.
