### ISSUE TITLE
need an example for filtercustomsearch

### ISSUE THREAD

**Issue by rsperumal** [wenzhixin/bootstrap-table#6389]
### Description

I want to use the "filtercustomsearch" option on column filters. Can I see an example of how this is used?

https://bootstrap-table.com/docs/extensions/filter-control/#filtercustomsearch

**Comment by UtechtDustin** [comment]
Here is an example: https://live.bootstrap-table.com/code/UtechtDustin/12835
In this example you can search in the `Item Name` just the `number`, the `Item ` prefix will be added in the `filter custom search`-method.

Is this fine for you or do you have another question ?

**Comment by rsperumal** [comment]
Thank you!
It really helped.
Not sure if you can help further but I'm trying to use it in combination
with fixed columns and headers but encountering below errors while
searching inside a column that is static (Eg: Item name)

https://live.bootstrap-table.com/code/rsperumal/12853

It still returns the results but while using in my own environment with
large data, it freezes the page. I have raised it as a bug  but wondering
if there are workarounds to overcome this?
https://github.com/wenzhixin/bootstrap-table/issues/6386

[image: image.png]
jquery.min.js:2

       Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at Function.se [as find] (jquery.min.js:2:7093)
    at HTMLTableSectionElement.handlers (jquery.min.js:2:43552)
    at HTMLTableSectionElement.dispatch (jquery.min.js:2:42777)
    at v.handle (jquery.min.js:2:41074)
    at Object.trigger (jquery.min.js:2:71513)
    at HTMLInputElement.<anonymous> (jquery.min.js:2:72108)
    at Function.each (jquery.min.js:2:2976)
se @ jquery.min.js:2
handlers @ jquery.min.js:2
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ bootstrap-table-filter-control.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
value @ bootstrap-table-filter-control.min.js:10
(anonymous) @ bootstrap-table-fixed-columns.min.js:10
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
Show 167 more frames
jquery.min.js:2

       Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at se (jquery.min.js:2:7093)
    at se.matchesSelector (jquery.min.js:2:13178)
    at S.filter (jquery.min.js:2:24704)
    at D (jquery.min.js:2:24590)
    at S.fn.init.is (jquery.min.js:2:25199)
    at HTMLInputElement.<anonymous>
(bootstrap-table-filter-control.min.js:10:46946)
    at HTMLTableSectionElement.dispatch (jquery.min.js:2:43090)

**Comment by UtechtDustin** [comment]
I don't think there is a workaround for that, right now.
