### ISSUE TITLE
Footer resizing problem

### ISSUE THREAD

**Issue by alcordier** [wenzhixin/bootstrap-table#639]
When using a footer, the columns are not resizing properly in the footer, at least on Firefox 36 and IE 11 (Chrome 41 and 42 (beta) seem to be Ok.

See http://jsfiddle.net/L6tm1tt3/ and resize the browser's window (lower the width) => the footer's columns are not aligned any more.

![alignment](https://cloud.githubusercontent.com/assets/8088404/6733034/d3299654-ce4f-11e4-8cd7-25415357adbf.png)

**Comment by djhvscf** [comment]
For now I think you can cal the resetView  method in your resize event! @alcordier

**Comment by djhvscf** [comment]
See this http://issues.wenzhixin.net.cn/bootstrap-table/#methods/resetView.html

**Comment by alcordier** [comment]
You're right, this works but not when it is so small that a scrollbar appears.
Footer continues to be displayed beyond table limits.

**Comment by djhvscf** [comment]
This code works.. Please check it out! http://jsfiddle.net/djhvscf/L6tm1tt3/4/

**Comment by alcordier** [comment]
- It does not works on Forefox.
- The scrollbar does not apply to Footer
- Here is what we get in our environment (where the table does not occupy the whole page):
![footer](https://cloud.githubusercontent.com/assets/8088404/6753396/e27f01fe-cf15-11e4-8dae-6b3e2224cbff.jpg)

I will try to reproduce on a fiddle...

**Comment by djhvscf** [comment]
Mmm.. yes, let me check it again! And when you have the fiddle, just tell us!

**Comment by djhvscf** [comment]
Do you have the jsfiddle??

**Comment by alcordier** [comment]
No, sorry, I was unable to reproduce on jsfiddle...

**Comment by wenzhixin** [comment]
Any update here?

**Comment by meetraz** [comment]
Running into this problem also

**Comment by djhvscf** [comment]
Can you provide a fiddle?? @meetraz

**Comment by meetraz** [comment]
I can't get the sums to appear in the fiddle for some reason, but you can still see the alignment is off:  http://jsfiddle.net/zaggyfed/2/

**Comment by meetraz** [comment]
Also, when the table is wide enough to need a scrollbar, the scroll appears between the data and footer, and scrolling the data does nothing to the footer.

**Comment by meetraz** [comment]
Some more info... If you set the height of the table vs. using pagination, both the header and footer have a resize problem.   If you use pagination instead of height, the header works fine but footer is still broken.    You can see how the header is broken here when you change the width of the window:  http://jsfiddle.net/zaggyfed/3/

**Comment by djhvscf** [comment]
Yes, this is a bug... We will work on it as soon as possible. Remember any pull request is welcome

**Comment by apuestokid** [comment]
You can use this to sinconize the scroll
$( document ).ready(function(){

   $('.fixed-table-body').scroll(function(){
        $('.fixed-table-footer').scrollLeft($(this).scrollLeft());    
    });

});

**Comment by meetraz** [comment]
This does not seem to have any effect.

**Comment by meetraz** [comment]
This change has had no effect on the problem for me.   The scrolling is still broken.

**Comment by wenzhixin** [comment]
Do you mean :http://jsfiddle.net/zaggyfed/10/? @meetraz

**Comment by meetraz** [comment]
Here's a new fiddle:  http://jsfiddle.net/735aq8d2/

1. The fields in the footer are not aligned with the data columns.
2.  If you scroll the table, the footer does not move.
3.  If you make the window very wide, the footer does not resize.

![image](https://cloud.githubusercontent.com/assets/1972728/8740159/0fb02818-2c0b-11e5-9915-820cd77c6e15.png)

![image](https://cloud.githubusercontent.com/assets/1972728/8740166/1f982ca8-2c0b-11e5-9a1e-285778ec3ec3.png)

![image](https://cloud.githubusercontent.com/assets/1972728/8740177/2d1710ce-2c0b-11e5-9c79-4757b84ec23b.png)

**Comment by meetraz** [comment]
Another example where the header + footer are broken:

http://jsfiddle.net/16uye7wq/2/

![image](https://cloud.githubusercontent.com/assets/1972728/8740253/d0da98ca-2c0b-11e5-97b3-1b521c8423c9.png)

**Comment by wenzhixin** [comment]
OK, I will check it.

**Comment by wenzhixin** [comment]
Added an example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/639.html

**Comment by wayne555** [comment]
The fix doesn't work if we don't set the height attribute

**Comment by wenzhixin** [comment]
@wayne555, you can submit a new issue for your problem, thanks.

**Comment by jcangel82julios** [comment]
Apply the following change to the function : BootstrapTable.prototype.fitFooter
 
1. Add the Variable fixedBody
2. Change the line: 

scrollWidth = elWidth > This $ tableBody.width (). ? getScrollBarWidth () : 0; 
by
scrollWidth = fixedBody.scrollWidth > fixedBody.clientWidth &&
            fixedBody.scrollHeight > esta fixedBody.clientHeight + . $ header.outerHeight () ?
            getScrollBarWidth () : 0;

3. reset the table view when the window is resized : 
$ (window ) .resize (function ( ) {
                Report.table.bootstrapTable ( ' resetView ' ) ;
   } ) ;

4. The function should be as follows:

BootstrapTable.prototype.fitFooter = function () {
        var that = this,
            $footerTd,
            fixedBody,
            elWidth,
            scrollWidth;

        clearTimeout(this.timeoutFooter_);
        if (this.$el.is(':hidden')) {
            this.timeoutFooter_ = setTimeout($.proxy(this.fitFooter, this), 100);
            return;
        }
        fixedBody = this.$tableBody.get(0);

        elWidth = this.$el.css('width');
        //scrollWidth = elWidth > this.$tableBody.width() ? getScrollBarWidth() : 0;      
        scrollWidth = fixedBody.scrollWidth > fixedBody.clientWidth &&
            fixedBody.scrollHeight > fixedBody.clientHeight + this.$header.outerHeight() ?
            getScrollBarWidth() : 0;
     
        this.$tableFooter.css({
            'margin-right': scrollWidth
        }).find('table').css('width', elWidth)
          .attr('class', this.$el.attr('class'));
       
        $footerTd = this.$tableFooter.find('td');

        this.$body.find('tr:first-child:not(.no-records-found) > *').each(function (i) {
            var $this = $(this);

            $footerTd.eq(i).find('.fht-cell').width($this.innerWidth());
        });
    };

**Comment by Seaheart** [comment]
If I want the table can fixed in front of a few columns when the table sliding left and right,what should I do?

**Comment by B-Alvarez** [comment]
You can use this: https://github.com/wenzhixin/bootstrap-table-fixed-columns

**Comment by xupeihong** [comment]
How to export excel or CSV?

**Comment by starskys** [comment]
> You can use this to sinconize the scroll
> $( document ).ready(function(){
> 
> $('.fixed-table-body').scroll(function(){
> $('.fixed-table-footer').scrollLeft($(this).scrollLeft());
> });
> 
> });

Thanks,this works for me.
