### ISSUE TITLE
Export Event to generate custom pdf

### ISSUE THREAD

**Issue by SimonMaoZC** [wenzhixin/bootstrap-table#6394]
### Description

Currently, we can use export PDF function to generate PDF, but we need to add some header and footer during the pdf generation.

we found there is 1 event called onExportSaved which can get the exported data.

we want to use this event to generate custom pdf based on exported data instead of current function.

Tried to add "return false" in the onExportSaved event, it can't block original pdf generation.

Do you know how to block or prevent original pdf generation?

**Comment by UtechtDustin** [comment]
Not possible right now, similiar to #6396.
