### ISSUE TITLE
How to change remote url?

### ISSUE THREAD

**Issue by sbellani** [wenzhixin/bootstrap-table#64]
Hi, 
I'm going to test your library.
I cannot found a method to change url, after first table bind.
Setting another url don't change visualized data.
I'm trying successfully this add:

```
BootstrapTable.prototype.refreshUrl = function (options) {
    this.options.url = options.url;
    this.initServer();
};
```

Any suggestions?

Thank you. Regards.

**Comment by ywqyuan** [comment]
$('#table').bootstrapTable('refresh', {url: 'new url'});  no work ,数据还是来自旧的url查询条件没有了

**Comment by Vity01** [comment]
I can confirm, that @wenzhixin solution does not work. It does not change data-url permanently. Defined URL is changed just for 1 data load. 
This is how I did it for now:

    var $detailTable = $('#appsDetailTable');
    var options = $detailTable.bootstrapTable('getOptions');
    options.url = '/apps/detailData2';
    $detailTable.bootstrapTable('refreshOptions', options);
    $detailTable.bootstrapTable('refresh');
