### ISSUE TITLE
problem with formatted columns and export

### ISSUE THREAD

**Issue by docholiday** [wenzhixin/bootstrap-table#640]
Hi, I use some formatters for specific columns to show images instead of text (like in the examples). However I also use the export function. Unfortunately the columns with images are empty in the exported file. Is it possible to use the title or alt-text for the export?

**Comment by wenzhixin** [comment]
Hi @docholiday , you can try to set the `exportOptions`: 
```
exportOptions: {
    htmlContent: 'true'
}
```
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/export
https://github.com/kayalshri/tableExport.jquery.plugin#options

Or, you can try to modify the implement of the plugin: https://github.com/kayalshri/tableExport.jquery.plugin/blob/master/tableExport.js
