### ISSUE TITLE
Reset page number to 1 while making a client side sort

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6402]
### Bootstraptable version(s) affected

1.21.0

### Description

When making a sort, I would expect the table to reset to page number 1 automatically.
But this is not the case.

Steps to reproduce:
- https://live.bootstrap-table.com/code/marceloverdijk/12864
- Go to page 2
- Sot on any of the columns
- Actual result: Table stays on page 2
- Expected result: Reset page number to 1

The interesting part is that for **server side** sort the page number **is** reset.
This was implemented by @UtechtDustin in 2019 with this PR: https://github.com/wenzhixin/bootstrap-table/pull/4414

Client vs Server side sorting does not seem to have consistent behaviour.

### Example(s)

https://live.bootstrap-table.com/code/marceloverdijk/12864

**Comment by UtechtDustin** [comment]
I don't would call it a `bug`, because its a matter of opinion what the right way is.
But i agree, if i'm on page X and change the sort i can't know which data i will see after the sort (the larger the dataset is, the more likely it is that we have the problem).

So i would mark it as feature if you're fine @wenzhixin @djhvscf.
What do you think ?

**Comment by marceloverdijk** [comment]
Yes, I agree it is an opinion, so yes a feature request makes sense (although it already works like this for server side sorting via #4414)

**Comment by marceloverdijk** [comment]
@UtechtDustin @wenzhixin @djhvscf I can try to provide a PR , do you think it's oke apply to reset page number when sorting by default (might be breaking for existing users) or to introduce an option for this?

**Comment by wenzhixin** [comment]
Add a new option, for example: `sortResetPage` ?

**Comment by marceloverdijk** [comment]
Hi @wenzhixin it absolutely makes sense to keep the current behaviour as default and introduce a `sortResetPage` option.
I will update the existing PR or probably just create a new one.

Funny regarding the stars feature on Github preserving the page numbers when sorting.
Other tables - like issue table - on Github reset the page number on sorting... ;-)

**Comment by marceloverdijk** [comment]
@wenzhixin I've created a new PR: https://github.com/wenzhixin/bootstrap-table/pull/6445
