### ISSUE TITLE
When `data-sort-reset="true"` and `data-order="desc"` it is not possible to sort ascending anymore

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6403]
### Bootstraptable version(s) affected

1.21.1

### Description

Using `data-sort-reset="true"` and `data-order="desc"` together makes column cannot be sorted `"asc"` anymore.

```
<table id="table"
  data-toggle="table"
  data-url="json/data1.json"
  data-height="400"
  data-sort-reset="true">
  <thead>
    <tr>
      <th data-field="id" data-sortable="true" data-order="desc">Item ID</th>
      <th data-field="name" data-sortable="true">Item Name</th>
      <th data-field="price" data-sortable="true">Item Price</th>
    </tr>
  </thead>
</table>
```

Steps to reproduce:

- https://live.bootstrap-table.com/code/marceloverdijk/12865
- Click on header field "Item ID" to sort
- Expected/Actual result: Item ID sorted high to low 👍 
- Click again on header field "Item ID" to sort other way 
- Expected result: Sort `asc`
- Actual result: Sort is reset

Note I: when sorting again, the field is again sorted `desc` (expected after reset) but so there is no way to sort on `asc` anymore.

Note II: when setting `data-sort-reset="false"` the field can be sorted `desc` --> `asc` --> `desc` etc. but it cannot be reset anymore.

### Example(s)

https://live.bootstrap-table.com/code/marceloverdijk/12865

### Possible Solutions

I think the reset functionality is not taking into account the `data-oder` and `data-sort-order` attributes.

(ps: I don't quite understand the difference between `data-oder` and `data-sort-order` but they both give this issue)

**Comment by UtechtDustin** [comment]
I can reproduce the main issue.

> Note II: when setting data-sort-reset="false" the field can be sorted desc --> asc --> desc etc. but it cannot be reset anymore.

Would be the expected result or not ?
You deactivated the rest option.

> (ps: I don't quite understand the difference between data-oder and data-sort-order but they both give this issue)

`data-order` is a column option and `data-sort-order` is a table option.
I'm not sure why someone decided to use a other option name.

**Comment by marceloverdijk** [comment]
> > Note II: when setting data-sort-reset="false" the field can be sorted desc --> asc --> desc etc. but it cannot be reset anymore.

> Would be the expected result or not ?
> You deactivated the rest option.

What I meant is with `data-sort-reset="false"` and `data-order="desc"` the sorting for that field starts with `"desc"` as expected and that cycles like `"desc"` --> `"asc"` --> `"desc"` --> `"asc"` etc. as expected.
So that is indeed fully expected result.

I only wanted to point out that it does not work together with `data-sort-reset="true"`, but maybe that note caused a bit of confusion instead 😬 


> > (ps: I don't quite understand the difference between data-oder and data-sort-order but they both give this issue)

> `data-order` is a column option and `data-sort-order` is a table option.
> I'm not sure why someone decided to use a other option name.

Yes makes sense now, with `data-sort-order` the default table order can be set.
