### ISSUE TITLE
Add `sortBy` method (similar as `filterBy`)

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6405]
### Description

Similar as `filterBy` it would be nice to have a `sortBy` method feature.

This way a table header could look like below:

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/197004/191095478-c8ab835e-612b-466b-88a8-6af7705af760.png">

The "Sort by:" dropdown could call this `sortBy` method and the "Category:" dropdown would call the `filterBy` method.

**Comment by marceloverdijk** [comment]
Related to this, is there a current workaround to trigger a sort manually?
I checked the docs but there seems not to be a method to d that unfortunately...

My use case is have the following table.
I want to remove the sort capability by clicking on the table headers.
Instead I want to execute the sort by select an order in the select dropdown (like name asc, name desc, etc)

<img width="905" alt="image" src="https://user-images.githubusercontent.com/197004/204011018-6cb005e8-fedf-40c8-9ab6-ba4b40660a0e.png">

This as I also have a custom view, and to be able to sort that I need a dropdown or something, as there are not table headers.

<img width="901" alt="image" src="https://user-images.githubusercontent.com/197004/204011068-6281a206-a72d-4d80-9faa-4729a7d79fc1.png">

I don't mind writing custom js to act when selecting a different value from the sort by select.

@wenzhixin any idea what I can do best?

**Comment by wenzhixin** [comment]
@marceloverdijk PR is welcome.
