### ISSUE TITLE
Search and find record from Ajax dataset when column in not in table

### ISSUE THREAD

**Issue by simonsolutions** [wenzhixin/bootstrap-table#6409]
### Description

I have a bootstrap table with Ajax dataset. in the Ajax dataset are fields that do not match to columns, so are not displayed.

But in the search field I'd like to find these records too. (For example a multiline description displayed as detail formatter).

### Example(s)

https://live.bootstrap-table.com/example/options/table-search.html

In the dataset is one record in the column amount = 76. When entering search field with "76", no record appears. when adding the column amount it appears.

**Comment by UtechtDustin** [comment]
You can create a [customSearch](https://bootstrap-table.com/docs/api/table-options/#customsearch) method to solve that.
Basic example: https://live.bootstrap-table.com/code/UtechtDustin/13013

**Comment by simonsolutions** [comment]
Thanks for the sample. I have one little problem, maybe a bug (?), I don't know.

If I add to your sample the following code:

`  $(document).ready(function() {
  	$('#table').bootstrapTable('filterBy', {
        id: [1, 2, 3]
      })
  });
`

then the filter doesn't work. So does the customSearch function have to be different or is it an issue within the bootstrap table's code?

**Comment by UtechtDustin** [comment]
Please provide us an example.

**Comment by simonsolutions** [comment]
https://live.bootstrap-table.com/code/simonsolutions/13200

This example doesn't filter on document load. When you remove the custom search (line 4: data-custom-search="customSearch") then the filter works again.
