### ISSUE TITLE
Cookie extention unhide data-switchable="false" data-visible="false" columns

### ISSUE THREAD

**Issue by habiboolean** [wenzhixin/bootstrap-table#6412]
### Bootstraptable version(s) affected

1.21.0

### Description

I have a hidden, non switchable columns needed to fill the card view (not using json, just html). When i try to use **Cookie Extension**, it breaks the logic of **data-switchable="false" data-visible="false"** parameters. It reveals columns that should stay hidden.

### Example(s)

https://live.bootstrap-table.com/code/habiboolean/12922
Try to hide some column(to trigger cookie save), then click run again, to refresh the page and you will see Item Name column. And you cant hide it until delete cookies.

**Comment by Taikono-Himazin** [comment]
i am also facing the same issue.
Any progress? Or is there a workaround for now?

**Comment by wenzhixin** [comment]
Fixed in #7112
