### ISSUE TITLE
Header/Cell formatter

### ISSUE THREAD

**Issue by afbruno** [wenzhixin/bootstrap-table#642]
It would be possible to format the column headers? (I would like to include some filters just like MS EXCEL)
It would be great also the possibility to return a javascript object to the "table formatter" functions rather than just HTML strings.

Thank you a lot!

**Comment by dabros** [comment]
@afbruno 

There are some good examples of the column 'formatter' attribute to be found at http://bootstrap-table.wenzhixin.net.cn/examples/#format . 

I personally use a generic formatter and changed bootstrap-table.js to pass this.header.fieldname through were needed, but its perfectly usable without that - i just prefer a switch(context) to multiple functions.

Also, you 'could' use the onPostHeader() callback and manipulate the headers <th> themselves even more (though you may need to add the this.trigger() call in the bootstrap-table.js file, depending on version, 2sec job with many examples in other functions). I do something similar in #678 where i use that for my column filters.

**Comment by wenzhixin** [comment]
It is not supported, but I think you can use the extension to do this.
http://bootstrap-table.wenzhixin.net.cn/extensions/#table-filter-control
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filtercontrol.html
