### ISSUE TITLE
Performance is very low when update batch dynamic table data 

### ISSUE THREAD

**Issue by csswl** [wenzhixin/bootstrap-table#6420]
### Description

In my application, I use table with ajax to get initial table data, it is about 230 items. then use websocket to update the table data.
I use bootstrap table version 1.21.1

The web socket will send about 200 item per second, if I use the updateByUniqueId, the page will very slow to update the data while the initializing is very fast. I monitoring the updating time, it is about 60s to update all data.

Then I modified the bootstrap-table.js, add the batch update flag to disable the corresponding init* functions in the updateByUniqueId function,  after all the dynamic data updated, I remove the batch update flag and call the resetView function. By do so, the update time now is about 0.6s.

So, I doubt whether we can add the batch update function, in this function the page rendering will be disabled, after that re-rendering the table.

**Comment by UtechtDustin** [comment]
So you execute `updateByUniqueId` 200 times per second ?
Then we can't do anything right now, because of the history of the BT and how it growed, we have one larger issue.
The bootstrap-table will rerender and execute almost all internal functions for any change you do (in your case 200times per second).

Our goal for the further is to improve it, but for now it's not that easy.

**Comment by csswl** [comment]
OK, understand.  but it is really a good software, I like it.
Thanks a lot.

**Comment by UtechtDustin** [comment]
Thank you, your welcome!
I close this issue, because we have some mor issues about that :)

**Comment by wenzhixin** [comment]
> Improved `updateCell` to update one HTML cell only.

https://bootstrap-table.com/news/#bootstrap-table-1211

@UtechtDustin I have improved this in v1.21.1.

@csswl I think you can use `updateCellByUniqueId` to solve your problem.
Example: https://live.bootstrap-table.com/code/wenzhixin/13117
