### ISSUE TITLE
how can I send query parameters with multiple same name like query?sort=abc,desc&sort=123,asc

### ISSUE THREAD

**Issue by takeAction** [wenzhixin/bootstrap-table#6427]
### Description

bootstrap-table 1.19.0.

I am using server pagination(spring mvc), for sorting, I have to use something like `query?sort=field1,desc&sort=field2,asc` for multiple columns sort and user cannot change the sort setting(that is the sort only can be field1 desc and field2 asc).

1. I tried `data-query-params="queryParams"` and do something like `return {"sort":["field1,desc", "field2,asc"]}` in `queryParams`, but it doesn't work(the generated query parameters is query?sort[]=field1,desc&sort[]=field2,asc)。how can I achieve my goal？
2. I also tried `bootstrap-table-multiple-sort.js`, however, it throws : t is not a function, queryParams bootstrap-table-multiple-sort.js:1577, so if multiple sort extension can achieve my goal? if it can, how can I solve this error?

**Comment by UtechtDustin** [comment]
Simple answer: you can't.
You can't have the same key twice and it's  not limited to the bootstrap-table.
The only way to add multiple values with one key is to use an array which would look like this `?sort[]=field1,desc&sort[]=field2,asc`.
In already used the correct return syntax for an array `return {"sort":["field1,desc", "field2,asc"]}`.

**Comment by takeAction** [comment]
@UtechtDustin Thanks for your reply. Yes, it is limited by the json, and `data-query-params` only can generate something like `?sort[]=field1,desc&sort[]=field2,asc` instead of `?sort=field1,desc&sort=field2,asc`.
However, spring sort only accept `?sort=field1,desc&sort=field2,asc` and will ignore `?sort[]=field1,desc&sort[]=field2,asc`.

or for `data-query-params`, could we change the url manually after it generated the request parameters and before sending the request? e.g. if `data-query-params` generate request like `query?name=123`, then we change it to `query?name=123&sort=field1&sort=field2`, then send the request to server.

**Comment by UtechtDustin** [comment]
TIL: There is no definition how to define multiple values for one key on HTTP-Requests.
BUT the standard is still `bar[]=foo&bar[]=foo1` instead of `bar=foo&bar=foo1`.

Should be solvable by replacing the ajax call via the [ajax](https://bootstrap-table.com/docs/api/table-options/#ajax) option.
While Ajax also use the standard `bar[]=foo&bar[]=foo1`, you have to use the `traditional` option there.

(Not tested)

**Comment by wenzhixin** [comment]
`query?sort=field1,desc|field2,asc` ?

**Comment by takeAction** [comment]
> `query?sort=field1,desc|field2,asc` ?

@wenzhixin this result in `Invalid character found in the request target . The valid characters are defined in RFC 7230 and RFC 3986`

**Comment by takeAction** [comment]
@UtechtDustin `data-ajax` works, it seems that this is the only solution. Thanks!

**Comment by UtechtDustin** [comment]
No problem, your welcome.
