### ISSUE TITLE
search limited

### ISSUE THREAD

**Issue by JBossBC** [wenzhixin/bootstrap-table#6428]
### Bootstraptable version(s) affected

1.11.0

### Description

you data filed contains the english full stop when you use the search function,absolutely,you can catch a bug. I can't know you design idea in this processing logic.In my view,this is the bug ,but you can completely avoid the bug.Why did you add an additional statement(In the bootstrap-table.min.js 477 line) to cause this bug?

### Example(s)

![8c49b433fd4564dffadc08dcae21878](https://user-images.githubusercontent.com/90125263/192773219-f9cf7b2c-3c01-46ea-854c-2fdc5179bcea.jpg)

When the data source includes special field which contains the  english full shop,such as "vm.name"

### Possible Solutions

the programming can separate the "vm.name"  into vm and name.next,the programming will search the "vm" and name in the data source,which dont exist in data source,the right answer is search "vm.name"

**Comment by UtechtDustin** [comment]
Sorry, i don't understand what do you mean.
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we don't got any response from you.
If you still need help, let us now and provide us an example.
