### ISSUE TITLE
Table height in vh

### ISSUE THREAD

**Issue by MathieuSaintes** [wenzhixin/bootstrap-table#6437]
### Description

I would like to be able to define the table data-height option in vh units. By defining data-height=100vh I would expect to have the table taking exactly the size of my browser, no matter the size of my browser window.

**Comment by wenzhixin** [comment]
Not support this feature.
You can use the resetView method to implement this feature. [height: 100%](https://live.bootstrap-table.com/code/wenzhixin/13080)
