### ISSUE TITLE
bootstrap-table.js and bootstrap-table.min.js different source 

### ISSUE THREAD

**Issue by alvin0618** [wenzhixin/bootstrap-table#644]
Both source code is not same.
1) bootstrap-table.js
  - when using jquery to init the table, header shows twice (incorrect)
  - jquery table option (showFooter : true) is working (correct)

2) bootstrap-table.min.js
  - when using jquery to init the table, header shows once (correct)
  - jquery table option (showFooter : true) is not working (incorrect)

**Comment by djhvscf** [comment]
Let me check! But you should use the lastest release https://github.com/wenzhixin/bootstrap-table/releases/tag/1.6.0

**Comment by alvin0618** [comment]
hi, the URL you gave is not the master version? I found that there is a lots of functions are missing from your given source.

**Comment by djhvscf** [comment]
No, the url that I gave you is for the lastest release.. That version is the lastest stable version because in the máster branch we are developing new features and maybe we can develop some issues por something like that

**Comment by alvin0618** [comment]
how about showRow and hideRow functions? the official website already listed this functions however the URL you gave doesn't come with the functions?

**Comment by djhvscf** [comment]
Please wait for the next release :) @alvin0618

**Comment by tzahari** [comment]
Hi,
showFooter is not working with the bootstrap-table.min.js.
It is working with the bootstrap-table.js
Regards
Thomas

**Comment by djhvscf** [comment]
Yes, becuase the min version is not updated until the next version.. Please wait for the next version! :) @tzahari

**Comment by wenzhixin** [comment]
New version released: https://github.com/wenzhixin/bootstrap-table/releases
