### ISSUE TITLE
Table in email

### ISSUE THREAD

**Issue by sabatale** [wenzhixin/bootstrap-table#6440]
### Description

Great app!

Is there an easy way to send the table in an email as opposed to export it in a separate file?

E.g., 1) Click button send email; 2) Table is copied to body, ready to be sent.

Thanks!

**Comment by wenzhixin** [comment]
You can use the print extension to save the table to a pdf file and send it to your email.
https://examples.bootstrap-table.com/#extensions/print.html

**Comment by sabatale** [comment]
Thanks but we were looking at sending it directly in the body without a need for external files, as this is often inconvenient.

I guess we'll be looking into to copy paste the table automatically.

**Comment by UtechtDustin** [comment]
That is not possible, because BT is a client library.
You can get the data of the table and send it to the server, which generates and sends the email.
