### ISSUE TITLE
V2 Bootstrap

### ISSUE THREAD

**Issue by SuperBoy17** [wenzhixin/bootstrap-table#6441]
### Description

您好，这关于https://github.com/wenzhixin/bootstrap-table/issues/6380 的，V2能不能解决到问题吗?谢谢
Hello there, this issue was related in https://github.com/wenzhixin/bootstrap-table/issues/6380 , could V2 bootstrap able to solve my issue? Thank you

**Comment by SuperBoy17** [comment]
Hi, already translated

**Comment by UtechtDustin** [comment]
I'm sorry, but bootstrap v2 is not supported.
Bootstrap 2 is EOL since 9 years!

**Comment by SuperBoy17** [comment]
Understood, but there's one question on last row in https://github.com/wenzhixin/bootstrap-table/issues/6380 ,is about able I change any JS or CSS file to update my view?

**Comment by UtechtDustin** [comment]
Sure, you can fork the project and update the source code to support bootstrap v2.

**Comment by SuperBoy17** [comment]
Sorry, a bit confuse here, can I edit one of those script file to get effect on my project?
![Capture](https://user-images.githubusercontent.com/112933534/194007935-20e357f9-0cd2-467c-a497-a8c59ff79a5f.JPG)
