### ISSUE TITLE
Cookie + Filter-control + lots of rows

### ISSUE THREAD

**Issue by MathieuSaintes** [wenzhixin/bootstrap-table#6442]
### Bootstraptable version(s) affected

1.21.1

### Description

![Screen Shot 2022-10-04 at 10 59 44 AM](https://user-images.githubusercontent.com/20236271/193725267-02d5cd81-9134-4a7a-93dd-35ee22933c8d.png)

The blank selection at the top of the filter control select disappears after reload when the table has more than a certain amount of rows. 

-> Unable to unselect individual filters, can only remove all the filters at once with a search clear button.

### Example(s)

https://live.bootstrap-table.com/code/MathieuSaintes/13068

**Comment by UtechtDustin** [comment]
Can't reproduce the issue with your example, which Browser(version) do you use ?

**Comment by MathieuSaintes** [comment]
This indeed only appears on my older MacBook running Catalina (10.15.7), with Safari (Version 15.6.1 (15613.3.9.1.16, 15613)) and Chrome (106.0.5249.119).

**Comment by UtechtDustin** [comment]
With macOS Monterey (12.6) and Chrome (106.0.5249.119), i can't reproduce it.
I'm not sure how the OS could affect this, but catalina is no more in support so i don't think we should support this case.
Also we don't have a device to debug/test it, i'm sorry.
