### ISSUE TITLE
ResetView after table initialized 

### ISSUE THREAD

**Issue by alvin0618** [wenzhixin/bootstrap-table#645]
May I know how to resetView after table init?

**Comment by djhvscf** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/resetView.html

**Comment by alvin0618** [comment]
this need to click the button in order to trigger reset view. I mean do bootstrap-table has any inticallback function can do this reset view?

**Comment by cherhui** [comment]
its stated at the site: $('tableID').bootstrapTable('resetView');
