### ISSUE TITLE
mongodb data field

### ISSUE THREAD

**Issue by gogliko** [wenzhixin/bootstrap-table#646]
Hello, i have mongodb schema

var ContrySchema = mongoose.Schema({
	name : {type : String, required : true},
	Description : String,
	City:{

		name:String,
		altName:String

	},
	State:{
		name:String,
		altName:String

..

i can't printing data into field 

   th data-field="City.name" data-formatter="CityName".

 i use also data-formatter how can fix this problem? tnx

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/flatJSON.html

**Comment by gogliko** [comment]
tnx but can't understand

**Comment by gogliko** [comment]
tnx done

**Comment by djhvscf** [comment]
Great! @gogliko
