### ISSUE TITLE
How can I disable reorderable rows?

### ISSUE THREAD

**Issue by njalbuero** [wenzhixin/bootstrap-table#6460]
### Description

'data-reorderable-rows' is initially set to true. I tried this and it doesn't work.
`const data = $('#tbl_items').bootstrapTable('getData');

 $('#tbl_items').attr("data-reorderable-rows", "false");
 $("#tbl_items").bootstrapTable('destroy');
 $('#tbl_items').bootstrapTable({ data });`

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by UtechtDustin** [comment]
I'm closing this issue, because we got no response from you.
If you still need help, please let us know and provide us an example.
