### ISSUE TITLE
How to set table height on checked checkbox event

### ISSUE THREAD

**Issue by Priyanka-6024** [wenzhixin/bootstrap-table#6461]
### Description

Hello,
I want set table height on checked checkbox on bootstrap table.
![Capture](https://user-images.githubusercontent.com/115613976/195270407-288aa17b-7725-42b6-9cea-cedd0cdc0e65.PNG)

Please suggest.
Thank you

**Comment by wenzhixin** [comment]
`refreshOptions` can solve your problem: https://live.bootstrap-table.com/code/wenzhixin/13145
