### ISSUE TITLE
Multiple table header fro table

### ISSUE THREAD

**Issue by ionultd** [wenzhixin/bootstrap-table#6462]
### Bootstraptable version(s) affected

1.21.1

### Description

I have a a table that is created by PHP template which I have integrated the bootstrap-table into. I am unable to share most of the relevant code as it is sensitive.

Any ideas to why the table might be doing this?

![image](https://user-images.githubusercontent.com/24327887/195433910-f043ed06-b232-4e78-ab2f-c251fd0230de.png)

Thanks

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](live.bootstrap-table.com/).
If you current setup has sensitive code, please create an minimal example using fake data.

**Comment by ionultd** [comment]
This has somehow resolved itself.
