### ISSUE TITLE
Sorting and searching exclude html content (such as link url)

### ISSUE THREAD

**Issue by vletoux** [wenzhixin/bootstrap-table#6468]
### Description

First thanks for this excellent plugin and for the time you are spending for the community.

I’m using bootstraptable in a 100% client side project because I’m generating html that could be loaded without JavaScript enabled. So I’m using sorting and searching performed at client side.
I think your other users are using service side filtering and sorting so this is not an issue here.

I’m building code where there are links to items. For example in the first column you have `<a href=« /edit/1 »>entity1</a>`
My code is sorting this column so I didn’t spot this problem the first time: bootstrap table orders the cell using its full content (including html). So when the user sort on a column and the resort it again, all links are sorted by the id (the alphabetical sort of the html cell content) and not the names as he would expect (what the user see on screen). 
For example, He’ll get:

`<a href=« /edit/1 »>entity9</a>`

`<a href=« /edit/2 »>entity2</a>`

`<a href=« /edit/3 »>entity6</a>`
In this case it is alphabetically ordered while the user see same random sort. The program sorts 1,2,3 while the user see 9,2,6

Same with filter. The search expression « edit » includes all the cells in the example above. Same for « / ».

I manage to have a workaround with custom sort and custom search implementation.

I think the current behavior is not what should be a default (what the user see on screen) that’s why I’m reporting it.
I’ve also spotted a similar issue #6187

**Comment by scottydevine** [comment]
Hi [vletoux](https://github.com/vletoux) any chance of you sharing the workaround with custom sort and custom search implementation?

**Comment by vletoux** [comment]
Here is what I wrote for myself.
Maybe not as optimized at it should be but the number of rows displayed in my tables are limited.

```
function noHtmlSorter(a, b) {
    return strip(a).localeCompare(strip(b));
}

function noHtmlSearch(data, text) {
    if (!text) {
        return data;
    }
    return data.filter(function (row) {
        return Object.entries(row).some(([key, value]) => {
            return (strip(value).indexOf(text) > -1);
        });
    });
}

function strip(html) {
    // Create a new div element
    var temporalDivEl = document.createElement("div");
    // Set HTML content using provider
    temporalDivEl.innerHTML = html;
    // Get the text property of the element (browser support)
    return temporalDivEl.textContent || temporalDivEl.innerText || "";
}
```

**Comment by scottydevine** [comment]
Hi [vletoux](https://github.com/vletoux)

Many thank, but I have tried using your code and failing to get this working 
any chance you could take a look for me?

Cut down example here
https://live.bootstrap-table.com/code/scottydevine/13556

**Comment by vletoux** [comment]
1) filter works
It's just case sensitive
![image](https://user-images.githubusercontent.com/10632326/204975838-3e5dbc21-0351-4453-af53-c45560e3782e.png)

2) for the sort I don't think i copy pasted the right function

**Comment by scottydevine** [comment]
Sorry - linked to the wrong one 

this one works with sorting and searching
https://live.bootstrap-table.com/code/scottydevine/13599

**Comment by wenzhixin** [comment]
Thanks for @scottydevine 
https://live.bootstrap-table.com/code/wenzhixin/15810 (Example from https://codepen.io/scoddy/pen/JjZmMBy)
