### ISSUE TITLE
Execute a search from other function.

### ISSUE THREAD

**Issue by anpegar** [wenzhixin/bootstrap-table#647]
Hi !!

I'm making a extension to create an advanced search but I don't know how to trigger the search event from another function.

For example, I have this :
.....
<button type="button" id="btnSearchAvd" class="btn btn-default" >Search</button>
.....
$("#btnSearchAvd").click(function() {
  // I want to trigger the search.
  BootstrapTable.prototype.onSearch($.Event('keyup')); // I've tried this but not working.  
}

Thanks in advance.

All my code:

` /**
 * @author aperez <aperez@datadec.es>
 * Añade los iconos de buscador y buscador avanzado detrás del campo search.
 */

! function($) {

    'use strict';

    var sprintf = function(str) {
        var args = arguments,
            flag = true,
            i = 1;

        str = str.replace(/%s/g, function() {
            var arg = args[i++];

            if (typeof arg === 'undefined') {
                flag = false;
                return '';
            }
            return arg;
        });
        return flag ? str : '';
    };

    var showAvdSearch = function(pColumns, pObjSearch) {

        if (!$("#avdSearchModal").hasClass("modal")) {
            var vModal = "<div id=\"avdSearchModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\" aria-hidden=\"true\">";
            vModal += "<div class=\"modal-dialog modal-xs\">";
            vModal += " <div class=\"modal-content\">";
            vModal += "  <div class=\"modal-header\">";
            vModal += "   <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\" >&times;</button>";
            vModal += "   <h4 class=\"modal-title\">Buscador Avanzado</h4>";
            vModal += "  </div>";
            vModal += "  <div class=\"modal-body modal-body-custom\">";
            vModal += "   <div class=\"container-fluid\" id=\"avdSearchModalContent\" style=\"padding-right: 0px;padding-left: 0px;\" >";
            vModal += "   </div>";
            vModal += "  </div>";
            vModal += "  </div>";
            vModal += " </div>";
            vModal += "</div>";

            $("body").append($(vModal));
            var vFormAvd = createFormAvd(pColumns, pObjSearch);
            $('#avdSearchModalContent').append(vFormAvd.join(''));
            //

            $("#btnSearchAvd").click(function() {
                var vFormData = $("#" + pObjSearch.idForm).serializeJSON();
                var vText = $('#' + pObjSearch.idTable).parents('.bootstrap-table').find('.search input').val();

                $.extend(vFormData, {
                    searchText: vText
                });
                var sFunctionData = JSON.stringify(vFormData);
                BootstrapTable.DEFAULTS.searchText = sFunctionData;
                
                //BootstrapTable.prototype.onSearch(this,$.Event('keyup'));
                /*********************

                  * Here, I want to call the method onSearch.

                ***********************/
                

            });

            $("#avdSearchModal").modal();
        } else {
            $("#avdSearchModal").modal();
        }

    };

    var createFormAvd = function(pColumns, pObjSearch) {
        var htmlForm = [];
        htmlForm.push('<form class="form-horizontal" id="' + pObjSearch.idForm + '" action="' + pObjSearch.actionForm + '" >');

        for (var i in pColumns) {
            var vObjCol = pColumns[i];
            if (!vObjCol.checkbox && vObjCol.visible && vObjCol.searchable) {
                htmlForm.push('<div class="form-group">',
                    '<label class="col-sm-4 control-label">' + vObjCol.title + '</label>',
                    '<div class="col-sm-6">',
                    '<input type = "text" class="form-control input-md" name="' + vObjCol.field + '" placeholder="Email">',
                    '</div>',
                    '</div>');
            }
        }

        htmlForm.push('<div class="form-group">',
            '<div class="col-sm-offset-9 col-sm-3">',
            '<button type="button" id="btnSearchAvd" class="btn btn-default" >Buscar</button>',
            '</div>',
            '</div>',
            '</form>');

        return htmlForm;
    }

    $.extend($.fn.bootstrapTable.defaults, {
        advancedSearch: undefined
    });

    $.extend($.fn.bootstrapTable.defaults.icons, {
        avdSearch: 'glyphicon-chevron-down'
    });

    $.extend($.fn.bootstrapTable.locales, {
        formatAvancedSearch: function() {
            return 'Buscador Avanzado';
        }
    });

    $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales);

    var BootstrapTable = $.fn.bootstrapTable.Constructor,
        _initToolbar = BootstrapTable.prototype.initToolbar;

    BootstrapTable.prototype.initToolbar = function() {
        var that = this,
            htmlBtns = [],
            $search,
            advSearch = {
                active: false,
                idTable: '',
                idForm: '',
                actionForm: '',
                funcSearch: ''
            };

        _initToolbar.apply(this, Array.prototype.slice.apply(arguments));

        if (typeof this.options.advancedSearch !== 'undefined') {
            advSearch = this.options.advancedSearch;
        }

        if (advSearch.active) {
            htmlBtns.push(sprintf('<div class="btn-group" role="group"><button class="btn btn-default' + (that.options.iconSize === undefined ? '' : ' btn-' + that.options.iconSize) + '" type="button" name="avdSearch" title="%s">',
                    that.options.formatAvancedSearch()),
                sprintf('<i class="%s %s"></i>', that.options.iconsPrefix, that.options.icons.avdSearch),
                '</button></div>');

            // Añadimos el botón al toolbar.
            that.$toolbar.find('.columns').prepend(htmlBtns.join(''));

            // Creamos el onclick para el booton            
            that.$toolbar.find('button[name="avdSearch"]')
                .off('click').on('click', function() {
                    showAvdSearch(that.options.columns, advSearch);
                });
        }

        // Anulamos la búsqueda automática
        if (that.options.searchTimeOut === -1) {
            $search = that.$toolbar.find('.search input');
            $search.off('keyup').on('keyup', function(event) {
                var text = $.trim($(event.currentTarget).val());
                // Al pulsar Enter realizamos la búsqueda.
                if (event.which === 13) {
                    that.onSearch(event);
                }

            });
        }

    };

}(jQuery); `

**Comment by djhvscf** [comment]
Ok, let me try to understand what you want to do... 
You want to trigger the onSearch event when the user clicks the advance search button?

**Comment by anpegar** [comment]
More or less ... when the user click the advance search button appears a modal with a form, from here I want to trigger the onSearch event, although your solution would be ok for me.

**Comment by anpegar** [comment]
It would be similar to put a search button next to search input that it'll trigger the onSearch event.
Thanks.

**Comment by djhvscf** [comment]
Can you provide a fiddle please.. I think I can help you with that.. It's very quick

**Comment by anpegar** [comment]
Sorry, but what's a fiddle? How can I provide it to you?

**Comment by djhvscf** [comment]
Ok, a fiddle it's an example when we can run the plugin and see the results.. Here is the template that you can use for the example: http://jsfiddle.net/wenyi/e3nk137y/13/light/

**Comment by anpegar** [comment]
Forgive my clumsiness :-( ... but I don't know how do it correctly. 
I've commited bootstrap-table-toolbar.js (it's an extension for bootstrap-table) in my repository but in jsfiddle my extension doesn't work, the advance search button doesn't appears.

I think that I'm complicating the thing, I just need a button to call onSearch event without push any key.

Check out my fiddle
http://jsfiddle.net/e3nk137y/1117/

**Comment by djhvscf** [comment]
Ok, Please see this: http://jsfiddle.net/e3nk137y/1118/ and now I'm checking your code.. We will find a solutions soon.. don't worry!

**Comment by anpegar** [comment]
Wow ... it works fine !! How did you do that? 
As you can see my code hasn't finished yet but what I want to do is trigger the search when I push "buscar" button. 
First, I get all the values of my advance form (i use serializeJSON library https://github.com/marioizquierdo/jquery.serializeJSON), I build a JSON with this fields plus input search value and then I want to call the ajax function that is within Bootstrap.prototype.initserver(). (.. I hope I explained correctly )

Thanks so much for your patience :-)

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/e3nk137y/1119/ I think you have to review if you can use the serializeJSON for search because with the search textbox we can search just by one field.. Let me know if it works for you

**Comment by anpegar** [comment]
Thank you so much for your solution but it isn't valid for me.Your information has been very useful because It has given me an idea of how to do it. 

1. With this code, I can trigger the search whether if searchTimeOut == -1 or not.

<b>var $search = $('.bootstrap-table').find('.search input');                    
var e = $.Event("keyup");
if (pOptions.searchTimeOut === -1){                                   
   (document.all) ? e.keyCode = 13 : e.which = 13;                     
}
$search.trigger(e);</b>

2. I've had to overwrite onSearch function because I need to send a JSON with all form fields plus search input and the original function only sends the search input value. I am clear that it works fine but I don't know if this is the best way to do it (any help will be appreciated)

Again, thanks for your help.

Check out my fiddle
http://jsfiddle.net/e3nk137y/1122/

The picture shown what I want to send with advanced search.

![captura](https://cloud.githubusercontent.com/assets/8124520/6821130/ff6ceaa2-d2d4-11e4-902f-2b80b9b99ba6.PNG)

**Comment by djhvscf** [comment]
Exc!! @anpegar
