### ISSUE TITLE
Data-filter-control with data-mobile-responsive

### ISSUE THREAD

**Issue by mausol** [wenzhixin/bootstrap-table#6471]
### Bootstraptable version(s) affected

1.21.1

### Description

If I try to combine data-filter-control="true" with data-mobile-responsive="true", 
the filter controls don't appear when the table first opens.

If the web page is resized and then reopened to full screen, 
the filter controls appear.

### Example(s)

<table class="table table-sm"
           data-filter-control="true"
           data-height="500"
           data-toggle="table"
       		 data-mobile-responsive="true"
           id="table">
        <thead>
        <tr>
            <th data-field="code" data-filter-control="input" data-sortable="true">Code</th>
            <th data-field="description" data-filter-control="input" data-sortable="true">Description</th>
        </tr>
        </thead>

        
            <tr>
                <td>1</td>
                <td>First</td>
            </tr>
        		 <tr>
                <td>2</td>
                <td>Second</td>
            </tr>
  					<tr>
                <td>3</td>
                <td>Third</td>
            </tr>
    </table>

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](live.bootstrap-table.com/), if you still need help.

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we got no example from you.
If you still need help, please let us know and provide us an example.
