### ISSUE TITLE
Click on a table link does not execute js function

### ISSUE THREAD

**Issue by ionultd** [wenzhixin/bootstrap-table#6473]
### Bootstraptable version(s) affected

1.21.1

### Description

When I have a link in a table with a JQuery function targeting the links class it does not fire the on click event.

### Example(s)

[Codepen](https://codepen.io/shanebekker-ot/pen/abGrGKJ)
[Live](https://live.bootstrap-table.com/code/ionultd/13205)

**Comment by UtechtDustin** [comment]
This is not a bug, you bind an event on an element which is don't exist on that moment.
So you have multiple ways to solve that.
You could listen to a event of the BT and then bind the event.
You could add  the lister to the body and use a second selector (example: https://live.bootstrap-table.com/code/UtechtDustin/13207).
Or you could use the [events option](https://bootstrap-table.com/docs/api/column-options/#events) which was made for that (example: https://live.bootstrap-table.com/example/column-options/events.html)
