### ISSUE TITLE
Pre-rendered detail view?

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6479]
### Description

Is it possible to use a `data-detail-view="true"` without a javascript formatter (`data-detail-formatter="theFormatter"`).
E.g. using a pre-rendered column that is hidden, but its content used for the detail view?

**Comment by marceloverdijk** [comment]
This is the closest I came up with my self:

https://live.bootstrap-table.com/code/marceloverdijk/13263

**Comment by marceloverdijk** [comment]
I updated the example to a generic solution which could be useful if someone stumbles on this as well:

https://live.bootstrap-table.com/code/marceloverdijk/13272

It basically changes the BT default detail formatter:

```
$.extend($.fn.bootstrapTable.defaults, {
  detailFormatter: function(index, row) {
    return row.detail_view ? row.detail_view : ''
  }
})
```

Maybe this could be even added to core, with some pre-defined field is like `detail_view`.

@wenzhixin @DustinUtecht if you think that could be useful I can create a PR.

**Comment by wenzhixin** [comment]
> ```
> $.extend($.fn.bootstrapTable.defaults, {
>   detailFormatter: function(index, row) {
>     return row.detail_view ? row.detail_view : ''
>   }
> })
> ```

I don't think it's a pre-rendered feature, because in practice, we can set different default properties by extending this way.

Thanks for your advice.
