### ISSUE TITLE
Add helper class for laravel

### ISSUE THREAD

**Issue by franklupo** [wenzhixin/bootstrap-table#648]
I have created class helper to generate code in laravel.
Is very very simple

https://github.com/franklupo/BootstrapTableHelper

Best regards

**Comment by djhvscf** [comment]
Great!! This is an important resource!! Thanks @franklupo

**Comment by franklupo** [comment]
New reimplementation on BootstrapTableHelper 
https://github.com/franklupo/BootstrapTableHelper
