### ISSUE TITLE
create image element inside a div with detailFormatter

### ISSUE THREAD

**Issue by ProgramerPen** [wenzhixin/bootstrap-table#6487]
### Description

I've been able to parse img from JSON and push it into html via detailFormatter's function. 
I tried to create a div and append img to it but all my tries went down. all what i was is to control position of the image.

![image](https://user-images.githubusercontent.com/91367331/197305133-d209f407-6895-45da-8257-98fad56b3c75.png)

(the header works weirdly on the online editor but works fine on local); 

### Example(s)

https://live.bootstrap-table.com/code/ProgramerPen/13271

**Comment by ProgramerPen** [comment]
also i want to append <div class="col-md-6"> to the class row
![image](https://user-images.githubusercontent.com/91367331/197326134-5255b924-bf17-4d54-8f37-c435b136f9a6.png)

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/13384
