### ISSUE TITLE
Multiple tables using the same searchSelector

### ISSUE THREAD

**Issue by BobClaerhout** [wenzhixin/bootstrap-table#6490]
### Description

Hi,

First of all, I'm a huge fan of this table implementation! Great job!
In my case, I have multiple tables on the same page and I want to use the same search input. I was hoping to use the searchSelector for this. However, when I use the same searchSelector for multiple tables, only the last table using that searchSelector actually uses the search input. I see 2 options:
- This gets fixed and multiple tables can use the same searchinput
- I observe the searchinput myself and search in the tables using javascript

Does anyone have an example of observing the searchinput myself and updating the tables?

**Comment by wenzhixin** [comment]
> I observe the search input myself and search in the tables using javascript

Example with this option: https://live.bootstrap-table.com/code/wenzhixin/13383.
