### ISSUE TITLE
filterControl button in toolbar, icon not change when toggle filter

### ISSUE THREAD

**Issue by csswl** [wenzhixin/bootstrap-table#6493]
### Bootstraptable version(s) affected

1.21.1

### Description

When use filterControl, the button icon in toolbar don't change when toggle the filterControl even I have supplied two icons.
icons: {
...
filterControlSwitchHide: 'fa-search-plus',
filterControlSwitchShow: 'fa-search-minus',
...
}
I see the toggle method use find('.filter-control-switch') in line 5323, but I can not find where this class is set, and also find no where to set it, because it use autogenerated code for this button. Is somewhere user can set the specific individule button's class?

By Sun Lin

### Possible Solutions

Suggest to use html in button config with class .filter-control-switch, or use name=filterControlSwitch to find this button.

code:
 var icon = this.options.showButtonIcons ? this.options.filterControlVisible ? this.options.icons.filterControlSwitchHide : this.options.icons.filterControlSwitchShow : '';
        var text = this.options.showButtonText ? this.options.filterControlVisible ? this.options.formatFilterControlSwitchHide() : this.options.formatFilterControlSwitchShow() : '';
        //this.$toolbar.find('>.columns').find('.filter-control-switch').html("".concat(Utils.sprintf(this.constants.html.icon, this.options.iconsPrefix, icon), " ").concat(text));
        this.$toolbar.find('>.columns').find('[name="filterControlSwitch"]').html("".concat(Utils.sprintf(this.constants.html.icon, this.options.iconsPrefix, icon), " ").concat(text));

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we don't got any response from you.
If you still need help, let us now and provide us an example.
