### ISSUE TITLE
Custom Search and Filter problem

### ISSUE THREAD

**Issue by simonsolutions** [wenzhixin/bootstrap-table#6494]
### Bootstraptable version(s) affected

1.21.1

### Description

Like in the Sample:
https://live.bootstrap-table.com/code/simonsolutions/13200

If the custom search is set, the filter doesn't work. This example doesn't filter on document load. When you remove the custom search (line 4: data-custom-search="customSearch") then the filter works again.

So it seems like a problem with filterBy and custom Search.

### Example(s)

https://live.bootstrap-table.com/code/simonsolutions/13200

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/table-options/#customsearch

> The custom search function is executed instead of the built-in search function, takes three parameters:

> * data: the table data.
> * text: the search text.
> * filter: the filter object from `filterBy` method.

It would be best to improve the `filterBy` logic in the `customSearch`: https://live.bootstrap-table.com/code/wenzhixin/13382.
