### ISSUE TITLE
How do I get the controls next to each other in custom toolbar

### ISSUE THREAD

**Issue by ionultd** [wenzhixin/bootstrap-table#6495]
### Description

I need the custom toolbar controls in the example below to be inline and inline with the search box. Nothing I have tried so far is able to do it.

### Example(s)

[Example](https://live.bootstrap-table.com/code/ionultd/13353)

**Comment by wenzhixin** [comment]
Do you mean the CSS style like this: https://live.bootstrap-table.com/code/wenzhixin/13381?

**Comment by ionultd** [comment]
Thx for replying. Yes that is it! But next to the search box or buttons on the right.

**Comment by mmaravillo** [comment]
Like this?  https://live.bootstrap-table.com/code/mmaravillo/13685

**Comment by ionultd** [comment]
Thanks for the reply and effort :-) but it needs to be on to top right of the table where the other buttons are by default.

**Comment by ionultd** [comment]
Oh wow that was a fast reply. Thank you.

**Comment by ionultd** [comment]
Oh wow that was a fast reply. Thank you.
