### ISSUE TITLE
exclude columns of advancedsearch

### ISSUE THREAD

**Issue by s72817** [wenzhixin/bootstrap-table#6497]
### Description

Hi, 
how can I exclude columns from advancedSearch?
For example I have image and action column and I want to exclude both.

I tried also with data-sortable="false" but isnt working.
https://live.bootstrap-table.com/code/s72817/13363

Thanks in advanced
Richard

**Comment by wenzhixin** [comment]
You can set the `search` column option to improve this feature.
Example: https://live.bootstrap-table.com/code/wenzhixin/13379
