### ISSUE TITLE
Sorting Date Data type

### ISSUE THREAD

**Issue by zubair2irfan** [wenzhixin/bootstrap-table#65]
How to sort the Date in ascending and descending order. We are only able to sort depending on the alphabets. It is a question rather that an issue.

**Comment by WagoL** [comment]
zubair2irfan, Any chance you could share the JS you wrote to accomplish this? Thanks in advance.

**Comment by SirDre** [comment]
Does this works for dates with this "**2016-05-03 12:52:37 PM**"(Y-m-d g:i:s A) format?

**Comment by bmatalus** [comment]
Doesn't seem like anyone is offering up their code, so here's mine:

Step 1. Add this attribute to the <th> tag:  data-sorter="dateSorter"

Step 2. Add this to any script block:

    function dateSorter(a, b) {
      var d1 = new Date(a);
      var d2 = new Date(b);

      if (d1 < d2) return -1;
      if (d1 > d2) return 1;
      return 0;
    }

Cheers!

**Comment by gvidhi** [comment]
> Doesn't seem like anyone is offering up their code, so here's mine:
> 
> Step 1. Add this attribute to the tag: data-sorter="dateSorter"
> 
> Step 2. Add this to any script block:
> 
> ```
> function dateSorter(a, b) {
>   var d1 = new Date(a);
>   var d2 = new Date(b);
> 
>   if (d1 < d2) return -1;
>   if (d1 > d2) return 1;
>   return 0;
> }
> ```
> Cheers!

I added this inside tag having date picker and JS too, i want to do it based on desc order.

**Comment by pavanbangaloreraju** [comment]
> You're welcome.

can u please share it again , i'm trying to access the link http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#custom-sort-table but received 404 error

**Comment by pavanbangaloreraju** [comment]
> You can use `sorter` option.
> for example: http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#custom-sort-table

this link doesn't work

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/api/column-options/#sorter

**Comment by pavanbangaloreraju** [comment]
> https://bootstrap-table.com/docs/api/column-options/#sorter

thanks , but i'm trying to sort the date time column in bootstrap table. i tried using sorter but still no luck

**Comment by wenzhixin** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
