### ISSUE TITLE
Does *not* work inside an angular view

### ISSUE THREAD

**Issue by okigan** [wenzhixin/bootstrap-table#650]
Oddly enough it works an angular app main page, but does not work (and no visible errors) inside of a view.

Here is plunker to reproduce the issue: http://plnkr.co/edit/n0J91B?p=preview.

In the plunker there shall be two tables, but only the top one shows up, the bottom one only the header shows up:

![screen shot 2015-03-24 at 9 49 17 pm](https://cloud.githubusercontent.com/assets/478302/6818586/c96c458e-d26f-11e4-9224-4b53e4355ac8.png)

**Comment by djhvscf** [comment]
I love angularjs.. let me check your example

**Comment by okigan** [comment]
bump ;)

**Comment by djhvscf** [comment]
I'm trying to figure out why it is not working

**Comment by okigan** [comment]
cool, yeah, I gave it a shot, but nothing jumped out (no error ether), hope you have better luck

**Comment by cherhui** [comment]
will it work if you set the table with a id and call $('#tableID').bootstrapTable(); after loading your view?

**Comment by okigan** [comment]
@cherhui ok that lead to the idea: 

it works on init page because bootstrap-table file has following init code (sneaky, but i guess logical):

    // BOOTSTRAP TABLE INIT
    // =======================

    $(function () {
        $('[data-toggle="table"]').bootstrapTable();
    });

so adding a controller for that ui-router-state [view] and calling the same initialization makes it work:

        // HOME STATES AND NESTED VIEWS ========================================
        .state('home', {
            url: '/home',
            templateUrl: 'partial-home.html',
            controller: function($scope) {
              $(function () {
                $('[data-toggle="table"]').bootstrapTable();
              });
            }
        })

**Comment by wenzhixin** [comment]
#165 may help.

**Comment by k1ng440** [comment]
`
    .directive('bsTable', ['$compile', function ($compile) {
        return {
            restrict: 'A',
            scope: {
                'bsTable': '='
            },
            link: function ($scope, $element, attrs) {
                var options = $scope.$eval(attrs.bsTable); // evaluate config from controller
                $($element[0]).bootstrapTable(options);
                $scope.$watch($element, function () {
                    $compile($element.contents())($scope);
                });

                $($element[0]).on('post-body.bs.table', function () {
                    var body = $element.find('tbody')[0];
                    $compile(body)($scope);
                });
            }
        };
    }])
`

works for me

**Comment by gokman** [comment]
In controller I needed to wait for DOM ready. Then below code worked for me:

 $timeout(function(){
        $('[data-toggle="table"]').bootstrapTable();
    });

**Comment by pacozevallos** [comment]
@gokman I have the same problem. Where do I add this code?

**Comment by gokman** [comment]
I have added that code at the begining of the related controller.
Good luck
