### ISSUE TITLE
Callback function with Reorder Rows Extension

### ISSUE THREAD

**Issue by alsanmorph** [wenzhixin/bootstrap-table#6505]
### Description

Hi! I added the Reorder Rows extension to my table, i can reorder the rows successfully, but I can't get the new order parameters with the callback function (onReorderRow(reorder-row.bs.table))

I'm using this code with jquery, but I can't make the alert work.

```
$("#table").on('reorder-row.bs.table', function (e, data){
    alert('test')
});
```

I'm not a Javascript expert, could someone explain how to make the event work? Thanks!

**Comment by UtechtDustin** [comment]
I'm not sure what do you mean with `new order parameters`, could you please explain it ?
You can get the following parameters in the event (as described in the [documentation](https://bootstrap-table.com/docs/extensions/reorder-rows/#onreorderrowreorder-rowbstable)):
- The new table data
- The dropped row
- The row of the old position

**Comment by UtechtDustin** [comment]
I close this issue because we got no response and the issues is a few month's old.   
If you still need help, please check my latest comment.
