### ISSUE TITLE
add aria options to checkboxes

### ISSUE THREAD

**Issue by kilgorejd** [wenzhixin/bootstrap-table#6507]
### Description

When adding checkbox columns, would be great for accessibility to have an option to add aria labels or titles that describe what the checkbox is for to screen readers.

**Comment by UtechtDustin** [comment]
How would you solve that @kilgorejd  ?
I'm not sure what we should use as value, just `checkbox` and `radio button` ?

**Comment by UtechtDustin** [comment]
I'm closing this PR as wen don't get any response from you.
If you still want to help, please let us know.
