### ISSUE TITLE
Using nested array for data field

### ISSUE THREAD

**Issue by cherhui** [wenzhixin/bootstrap-table#651]
Hi,

Is it possible to use nested JSON/array element for the table data field, for example:

Server JSON response:
```[{"1": "1", "2": "2", "array": { "key": "value" } }]```

Table HTML:
```
<th data-field="1" data-align="center">1</th>
<th data-field="2" data-align="center">2</th>
<th data-field="array['key']" data-align="center">Key</th>
```

It will be useful for pivot table results.

**Comment by djhvscf** [comment]
Use the Flat JSON option.. See this: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/flatJSON.html

**Comment by djhvscf** [comment]
It works for you?

**Comment by cherhui** [comment]
yes its working =)
