### ISSUE TITLE
Table Options "escape" And Column Options "formatter" conflict

### ISSUE THREAD

**Issue by imyuyu** [wenzhixin/bootstrap-table#6512]
### Bootstraptable version(s) affected

1.21.1

### Description

Recently, I want to upgrade the bootstrap table. The current version is 1.18.3.

After upgrading the version, it is found that the object type field value obtained by the column attribute formatter is `[object object] ` of string type. After tracing the source code, it is found that "escape: true" is set.

The following code is in the `initRow` method
```javascript
{
      key: "initRow",
      value: function initRow(item, i, data, trFragments) {

               this.header.fields.forEach(function (field, j) {
                   var text = '';
                   var value_ = Utils.getItemField(item, field, _this7.options.escape); // right here
              }
      }
}

```

There is no problem in '1.18.3'. What is the reason for this change?

### Example(s)

[Online Example](https://live.bootstrap-table.com/code/imyuyu/13424)

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by imyuyu** [comment]
> Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

examples：[Online Example](https://live.bootstrap-table.com/code/imyuyu/13424)

**Comment by UtechtDustin** [comment]
I don't think this is a bug, you used for the`data-field` option an `object`.
As [documented](https://bootstrap-table.com/docs/api/column-options/#field)  a `String` are required.

But you can rewrite you're code like that: https://live.bootstrap-table.com/code/UtechtDustin/13776

**Comment by wrteam-sagar** [comment]
But when I don't use the data-escape in table tag then formatter is gets the object in field name. Object is not accessible only when data-escape is true. Is there any specific reason behind that ?
