### ISSUE TITLE
How to find out, which view is active?

### ISSUE THREAD

**Issue by s72817** [wenzhixin/bootstrap-table#6514]
### Description

Hi, how can I find out, which view is active? e.g. custom view or default view?
Background is: I want to save whish view is active, to load this view next time. I thought to do it with an event?!
Thanks in advanced
Richard

**Comment by UtechtDustin** [comment]
You could listen for this [events](https://bootstrap-table.com/docs/extensions/custom-view/#events), if the event is fired the custom-view was used.

**Comment by s72817** [comment]
switch to custom view, I can use this event - but what is, if user switch back to normal view? Because reset-view.bs.table or post-body.bs.table is fired always.

**Comment by UtechtDustin** [comment]
If one of this events was NOT triggered but `post-body.bs.table`  was triggered, customView is not enabled.

**Comment by s72817** [comment]
Solved:
```
this.table.on('reset-view.bs.table custom-view-post-body.bs.table', (name, args) => {
            if (name && args) {
                console.log('custom view')
            } else {
                console.log('normal view');
            }
        });
```

**Comment by wenzhixin** [comment]
OK, let's close this issue.
