### ISSUE TITLE
Making an existing column checkboxes

### ISSUE THREAD

**Issue by ionultd** [wenzhixin/bootstrap-table#6516]
### Description

Hi,

I need to create a Send and Delete column with check boxes so individual items rows can be chosen and when submitted all the chosen item can be deleted or sent.

The existing checkbox data attributes would work but it hides the column name.

Any suggestions?

Thx

### Example(s)

https://live.bootstrap-table.com/code/ionultd/13418

**Comment by ionultd** [comment]
Any suggestion anyone :-) ?

**Comment by wenzhixin** [comment]
I think `formatter` column option can help you: https://live.bootstrap-table.com/example/column-options/formatter.html

**Comment by ionultd** [comment]
Thanks for the reply.
Yes that would help but I also need the column header to contain a check all checkbox. Any ideas?

**Comment by wenzhixin** [comment]
ref #987, example: https://live.bootstrap-table.com/code/wenzhixin/13728
