### ISSUE TITLE
Filter control not working on mobile / tablet.

### ISSUE THREAD

**Issue by matata86** [wenzhixin/bootstrap-table#6517]
### Bootstraptable version(s) affected

1.21.1

### Description

If I first filter select and then I want to filter via input. It does not work.

### Example(s)

https://user-images.githubusercontent.com/28623294/201762869-e2867270-314c-418b-82f0-8eefaba3963c.mp4

**Comment by UtechtDustin** [comment]
@matata86 are you still affected by this ?
I tested it with iOS and iPadOS and it works fine for me, maybe a bug in your tablet browser ?

@wenzhixin @djhvscf could you please test it ?

**Comment by UtechtDustin** [comment]
I close this issue because we got no response and the issues is a few month's old.   
If you still need help, please check my latest comment.
