### ISSUE TITLE
How to set data-width in large amount of columns?

### ISSUE THREAD

**Issue by ShreeSoftech-Rupesh** [wenzhixin/bootstrap-table#6526]
### Description

when i add large amount of columns in bootstrap table then data-width not working

![image](https://user-images.githubusercontent.com/92097236/203051919-07f9eaf9-b5d1-460c-949c-0e581d181fbe.png)

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](live.bootstrap-table.com/).

**Comment by ShreeSoftech-Rupesh** [comment]
here Live example : https://live.bootstrap-table.com/code/ShreeSoftech-Rupesh/13786

**Comment by DataSupplier** [comment]
I've added the following:
`<th class="text-nowrap" >`
Based on the content of the cell the column will have the (auto) maximum width, which suits my needs. The format of the table will get wider.

**Comment by ShreeSoftech-Rupesh** [comment]
> class="text-nowrap"

it works,thank you
