### ISSUE TITLE
Update cell color (class list) in Bootstrap Table

### ISSUE THREAD

**Issue by RMkuzmi** [wenzhixin/bootstrap-table#6527]
### Description

How can i change bg color of the cell via js?

What method of bootstrap-table should I use for updating ClassList of some cell in the table?

Here is same question on stackoverflow: https://stackoverflow.com/questions/37636292/update-color-cell-on-bootstrap-table

### Example(s)

I changing color over js for some cell. Then I change table structure and color is dissapeared.

What method of bootstrap-table should I use for actions like this?

https://live.bootstrap-table.com/code/RMkuzmi/13486

**Comment by UtechtDustin** [comment]
To modify the table you have to listen on events of thable in this case you can use the `postBody` event.
The table will be rerendered after some actions, so the styling must be applied again.

Example: https://live.bootstrap-table.com/code/UtechtDustin/13775
