### ISSUE TITLE
Table filter control with cell content having links <a> is no longer working (second issue)

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#6528]
### Bootstraptable version(s) affected

1.21.1

### Description

@djhvscf Since version 1.21.0, filtering rows by `select` form with cells content having links <a> is no longer working because of too restrinctive check :

https://github.com/wenzhixin/bootstrap-table/compare/1.20.2...1.21.1#diff-19b0a896e93a7995e54d6243a8edf1fa9a1ac4d59a6d5516b05d41821f3ca4b3L5072
![image](https://user-images.githubusercontent.com/646632/203271599-54195577-aae0-4e99-9325-b12bc99df63a.png)

### Example(s)

The filter is not working if the link is containing an html link. Here is a sample to reproduce the problem : https://live.bootstrap-table.com/code/sdespont/13443

### Possible Solutions

I don't know the best way to fix that. I would suggest to remove HTML is all cases before comparing values like this in case of using `select` form in https://github.com/wenzhixin/bootstrap-table/blob/2a15d88ed6d5b789db366e246bd0357e4ac0f2c1/src/extensions/filter-control/bootstrap-table-filter-control.js#L297-L314

Like this :
```
if (column.filterStrictSearch || column.filterControl === 'select' && column.passed.filterStrictSearch !== false) {
    if (column.filterControl === 'select') {
        // Remove HTML before comparing values
        tmpItemIsExpected = Utils.removeHTML(value.toString().toLowerCase()) === searchValue.toString().toLowerCase();
    } else {
        tmpItemIsExpected = value.toString().toLowerCase() === searchValue.toString().toLowerCase();
    }
}
```

**Comment by sdespont** [comment]
I can fix it in a PR if my approach is OK for you ?

**Comment by sdespont** [comment]
Any decision about this?

**Comment by UweKubosch** [comment]
We are having the same problem.  Any chance you could accept a PR from @sdespont ?

**Comment by UtechtDustin** [comment]
Thank  you for the hint @sdespont, i modified your fix so it will also apply to the other search options.
