### ISSUE TITLE
Is it possible to use a standard html `<select>` as pagesize control?

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6530]
### Description

By default BT uses a BS5 `.btn-group .dropdown > button` control for selecting the pagesize.

Is it possible to use standard html `<select>` instead of a BS Button Group ?

### Example(s)

https://live.bootstrap-table.com/example/options/table-pagination.html

**Comment by wenzhixin** [comment]
@marceloverdijk you can implement an extension by yourself.
Example: https://live.bootstrap-table.com/code/wenzhixin/13721
```js
$.BootstrapTable = class extends $.BootstrapTable {
  initPagination () {
    super.initPagination()
    const html = this.options.pageList.map(i => `<option value="${i}">${i}</option>`)
    this.$pagination.find('.page-list').html(`<select>${html}</select>`)
    const $select = this.$pagination.find('select')
    $select.val(this.options.pageSize).off('change').on('change', e => {
      this.options.pageSize = +$select.val()
      this.updatePagination(e)
    })
  } 
}
```
