### ISSUE TITLE
[custom-view] Support for on/off open/close icon

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6532]
### Description

I would like to use 2 separates icons for the custom view extension.
E.g. a grid icon when showing the table, and a table icon when showing the the custom view.
Similar as the toggle pagination and detail view also have 2 icons for different states.

The custom view has only one option for the icon right now:

`customView`: `bi-eye` (for bs5)

It would be nice to have:

- `customViewOn`
- `customViewOff`

or use 

- `customView`
- `customViewOff`

for backwards compatibility.

@UtechtDustin what do you think, I can create a PR.

**Comment by UtechtDustin** [comment]
Makes sense and sounds good, i guess we should go with `customViewOn` and `customViewOff`.
It's a quite small BC and also it's not so likely that somebody overwrote the icons.
You're PR's are welcome :)

**Comment by marceloverdijk** [comment]
Sounds good! I will create a PR this evening.

**Comment by marceloverdijk** [comment]
Could you maybe first look into PR https://github.com/wenzhixin/bootstrap-table/pull/6531 ?
Otherwise it might interfere a bit with this on/of changes.

**Comment by marceloverdijk** [comment]
@UtechtDustin PR created ;-)

**Comment by marceloverdijk** [comment]
Closed by #6534
