### ISSUE TITLE
query outer side

### ISSUE THREAD

**Issue by hinditutorpoint** [wenzhixin/bootstrap-table#6533]
### Description

hello how can i append search query from outer side like i have three combo box
select and filter by server side without affected exiting configuration.

**Comment by hinditutorpoint** [comment]
![Screenshot 2022-11-25 002936](https://user-images.githubusercontent.com/42866845/203851285-c536a1c4-5d6c-4ab8-bc34-9ea16baaed1d.png)

**Comment by hinditutorpoint** [comment]
another question is how to export some expect column.

**Comment by wenzhixin** [comment]
I think these links can help you:
* https://examples.bootstrap-table.com/index.html#options/custom-toolbar.html
* https://bootstrap-table.com/docs/extensions/export/#column-options
