### ISSUE TITLE
How to user the load method to re-load data in Vue

### ISSUE THREAD

**Issue by SimonMaoZC** [wenzhixin/bootstrap-table#6535]
### Description

Currently, I am using Vue.js to load bootstrap table and want to  load data triggered by button.

From Load method in document(https://examples.bootstrap-table.com/#methods/load.html#view-source), this is working for Jquery, but how to make it work in Vue, actually API is working and get the response, but data can't be inserted into table.

![image](https://user-images.githubusercontent.com/113584254/203894339-b1ba9bea-417b-4b44-87fd-920b7f68a0cb.png)

**Comment by wenzhixin** [comment]
`this.$refs.table.load(...)`

Online example: https://live.bootstrap-table.com/code/wenzhixin/13631
