### ISSUE TITLE
Filter extension

### ISSUE THREAD

**Issue by mrtruebeliever** [wenzhixin/bootstrap-table#654]
Hi I am having trouble enabling the filter extension. Does it only work when you load data in the table via JSON?

**Comment by djhvscf** [comment]
it works vía json ir not.. Can you provide a fiddle?

**Comment by mrtruebeliever** [comment]
I've never worked with fiddle before, but tried it :)
https://jsfiddle.net/m8aw5v07/

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/71x4x5qo/24/ @mrtruebeliever

**Comment by djhvscf** [comment]
Please double check the reference order, it is very important, and also the version of each js file.. @mrtruebeliever

**Comment by vicentor** [comment]
I tried to get it to work desperately, it works when I fork your JSFiddle but not on my actual website. I get an empty filter box.
![image 1](https://cloud.githubusercontent.com/assets/2099885/6871089/9fed09a6-d476-11e4-9fe1-f30f45098541.png)

I include the files in this order:
(CSS before in the code)
`<script src="utilities/js/bootstrap-table/bootstrap-table.min.js"></script>
<script src="utilities/js/bootstrap-table-filter/bootstrap-table-filter.js"></script>
<script src="utilities/js/bootstrap-table-filter/ext/bs-table.js"></script>
<script src="utilities/js/bootstrap-table/extensions/filter/bootstrap-table-filter.min.js"></script>`

I can't seem to find the proper documentation that explains how to integrate it properly with Bootstrap Table without initializing every single filter options.

**Comment by cherhui** [comment]
we need to see your html and javascript source to help troubleshoot

**Comment by djhvscf** [comment]
Let me find the legacy documentation about this extension

**Comment by djhvscf** [comment]
See this: http://wenzhixin.net.cn/p/bootstrap-table/docs/extensions.html#filter

**Comment by mrtruebeliever** [comment]
This is working for me, thank you! I forgot to include the bs-table.js file.

**Comment by djhvscf** [comment]
Great! @mrtruebeliever
