### ISSUE TITLE
treegrid level error caused by id length

### ISSUE THREAD

**Issue by 18682788952** [wenzhixin/bootstrap-table#6540]
### Bootstraptable version(s) affected

1.21.1

### Description

[
  {
    "id": "222",
    "pId": "",
    "name": "系统权限"
  },
  {
    "id": "F65C70B7AA9CC2A7",
    "pId": "222",
    "name": "用户"
  },
  {
    "id": "2604389FA62B4A6367E5F24F14A7D1C3",
    "pId": "F65C70B7AA9CC2A7",
    "name": "重置密码"
  }
]

 url: '/data/ddd.json',
                parentIdField: 'pId',
                method:"get",
                columns: [
                    {
                        field: 'ck',
                        checkbox: true
                    },
                    { field: 'name', title: '模块', width: 350 },
                    { field: 'sort', title: '排序' }
                ]

![image](https://user-images.githubusercontent.com/31786261/204813017-526a7344-4ef5-4324-985a-fae653f74a56.png)

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!
请提供在线例子。

**Comment by wenzhixin** [comment]
在 #6550 修改。
