### ISSUE TITLE
Reorder Columns does not work

### ISSUE THREAD

**Issue by francogp** [wenzhixin/bootstrap-table#6545]
### Bootstraptable version(s) affected

1.21.1

### Description

https://examples.bootstrap-table.com/#extensions/reorder-columns.html#view-source
does not work with bootstrap 1.21.1. Tried updating jquery-ui to 1.13.2 but now dragtable lib fails (too old)

### Example(s)

https://live.bootstrap-table.com/example/extensions/reorder-columns.html

**Comment by UtechtDustin** [comment]
Seems fixed in our `develop` branch, please wait for the next release :-)
Example: https://live.bootstrap-table.com/code/UtechtDustin/14298
