### ISSUE TITLE
添加了remve by $index的功能

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#655]
BootstrapTable.prototype.remove = function (params) {
        //console.log(params);
        //console.log(this.options.data);
        var len = this.options.data.length,
            i, row;
   
        if (!params.hasOwnProperty('field') || !params.hasOwnProperty('values')) {
            return;
        }
        if (params.field == '$index') {   
            for (var vi = params.values.length - 1 ; vi >= 0;vi--)
                this.options.data.splice(params.values[vi], 1);
        } else {
            for (i = len - 1; i >= 0; i--) {
                row = this.options.data[i];

                if (!row.hasOwnProperty(params.field)) {
                    return;
                }
                if ($.inArray(row[params.field], params.values) !== -1) {
                    this.options.data.splice(i, 1);
                }
            }
        }

        if (len === this.options.data.length) {
            return;
        }

        this.initSearch();
        this.initPagination();
        this.initBody(true);
    };

**Comment by neozhu** [comment]
仅供参考

**Comment by chenchuxin** [comment]
老铁，怎么用？下面的代码没作用。。。还要把你的代码copy到我的代码中吗
```
$table.bootstrapTable('remove', {field: '$index', values: [index]});
```

**Comment by chenchuxin** [comment]
感谢老铁
