### ISSUE TITLE
Multiple tables using data-ajax="ajaxRequest"

### ISSUE THREAD

**Issue by DataSupplier** [wenzhixin/bootstrap-table#6564]
### Description

Hi guys, I dunno if it possible to feed multiple tables using Ajax with a single javascript function.
I can pass dynamic urls (per table) to the ajax call, but the last result set will be applied to all tables. 

[The code in the example page](https://examples.bootstrap-table.com/#options/table-ajax.html#view-source)  does not have a reference to a table element. I've tried to add it, but it did not work out as using it along with params.success(res).

**The main question: Is there a way to provide and return the result set to a specific table id?** 

Thanks!

(p.s. having a specific javascript function per table works, but it is not the preferred way)

### Example(s)

Example from: https://examples.bootstrap-table.com/#options/table-ajax.html#view-source

<script>
  // your custom ajax request here
  function ajaxRequest(params) {
    var url = 'dynamic_url
    $.get(url + '?' + $.param(params.data)).then(function (res) {
      params.success(res)
    })
  }
</script>

**Comment by UtechtDustin** [comment]
There is a reference between the the function and the table.
On the table you have the `data-ajax` attribute which value is the name of the function (in this case `ajaxRequest`).
So if you want one "base" ajax method for multiple tables with different endpoints, you have to use multiple methods which pass the url to the "base" ajax method.

Example: https://live.bootstrap-table.com/code/UtechtDustin/13769
Does this solve your Issue ?

**Comment by DataSupplier** [comment]
Hi mate, thanks for your reply and for providing an example that gives me clarity.
Yes, with this answer my question is answered.
