### ISSUE TITLE
Export type `excel` creates files which appear corrupt to Excel

### ISSUE THREAD

**Issue by JonasR** [wenzhixin/bootstrap-table#6569]
### Bootstraptable version(s) affected

1.21.2

### Description

Any file exported with type `excel` yields the following error when I try to open it
![image](https://user-images.githubusercontent.com/307785/208957665-1cf76300-d918-471d-8769-afbaef80447e.png)

It looks fine when opening it anyway, but might deter users from actually using it.

### Example(s)

This can be reproduced with the [official example](https://examples.bootstrap-table.com/#extensions/export.html) for the export feature.

### Possible Solutions

I don't know what exactly needs to be done to make this work. I tried adding [SheetJS/js-xlsx](https://github.com/SheetJS/js-xlsx) but that has no effect on it. It shouldn't either because it's only for .xlsx exports. Exporting as .xlsx works fine but then the styling is bad / non-existing.

After reading https://github.com/hhurz/tableExport.jquery.plugin/issues/49 I'm not sure if this is 'intended behavior of the underlying plugin and there simply is no fix.

### Additional Context

I'm trying to open these files in Office 365 Version 2210.

**Comment by UtechtDustin** [comment]
As @hhurz wrote in https://github.com/hhurz/tableExport.jquery.plugin/issues/49 it's kind of "intended behavior".
The way how the tableExport plugin export the table as xls file is deprecaded.
The xls contains just html elements with a few tags.

So on our side we can't fix anything, sorry about that!

**Comment by JonasR** [comment]
Alright, thanks a lot for confirming!
