### ISSUE TITLE
Table does not follow Addrbar

### ISSUE THREAD

**Issue by DataSupplier** [wenzhixin/bootstrap-table#6580]
### Description

The extension for Addrbar is added and enabled. Next, when switching pages on the pagination the parameters in the url are changing, but clicking on return (go back or forward button) the table does not change accordingly, stays static unless the page is refreshed with F5. (Auto)-refresh also doesn't follow the Addrbar.

I'm using server side processing. Maybe I missed something. But I dunno what. (added extension in scripts, enabled addrbar by stating true, I guess this is all?)
I've put the table options which I tried in the example.

Thanks for your time in advance!

### Example(s)

https://live.bootstrap-table.com/code/DataSupplier/13882

**Comment by UtechtDustin** [comment]
I don't think you miss something, the plugin was never designed to listening to the url changes.
It was designed that you can share/save a link to specific "location" on the table.

But i guess it would be nice if we would listen to the navigation changes.

**Comment by DataSupplier** [comment]
Ah, good to know, thanks for the info.
The feature would be powerful, looking forward to it!

Additional info, using it along with auto-refresh will stack-up the url changes. Would it be possible to have an intelligence build in which prevents the addition of the url to the url if the url does not changes?

**Comment by wenzhixin** [comment]
Support this feature in the latest version:
https://examples.bootstrap-table.com/#extensions/addrbar.html

**Comment by wenzhixin** [comment]
Support this feature in the latest version:
https://examples.bootstrap-table.com/#extensions/addrbar.html
