### ISSUE TITLE
Using data-cell-style and data-formatter on the same cell/column

### ISSUE THREAD

**Issue by kwagdy** [wenzhixin/bootstrap-table#6586]
### Bootstraptable version(s) affected

1.21.2

### Description

I have a table with multiple columns where cell in column C = cell in column B - cell in column A. This is established using [data-formatter](https://examples.bootstrap-table.com/index.html#column-options/formatter.html) and returning the difference between cell A & B. I also use [Cell-Style](https://examples.bootstrap-table.com/#column-options/cell-style.html) to add a class to the cell in case the value is greater than 0.

The problem is that it seems that **cell-style function** runs before **data-formatter function** which means at the time the check of value within the cell is greater than zero happens before the cell content is calculated via **data-formatter function**

### Example(s)

Using data-cell-style and data-formatter on the same cell/column

### Possible Solutions

Is there a way to ensure **cell-style function** runs only after the **data-formatter function** and the cell content is populated?

Thank you

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by UtechtDustin** [comment]
I will close this issue because we got no response from you, if you still need help please provide us an example.
