### ISSUE TITLE
export cant support chinese 

### ISSUE THREAD

**Issue by zsj1029** [wenzhixin/bootstrap-table#659]
when i use chinese report： Uncaught INVALID_CHARACTER_ERR: DOM Exception 5

1、use yckart/jquery.base64.js replace rawgit.com/kayalshri/tableExport.jquery.plugin/master/jquery.base64.js
2、//rawgit.com/kayalshri/tableExport.jquery.plugin/master/tableExport.js
url ：like data:application/xml;filename=exportData
change ： data:application/xml;charset=utf-8;filename=exportData
charset=utf-8 is very important ,be sure good show ,no strange code

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/faq/
