### ISSUE TITLE
Column event doesn't work after 4 levels of detail view

### ISSUE THREAD

**Issue by luylucas10** [wenzhixin/bootstrap-table#6591]
### Bootstraptable version(s) affected

1.21.1

### Description

I needed to create multiple levels of detail view with event on row buttons. After fourth level, columns events don't work anymore, I tried with tag selector, class selector but no success, I needed to use onPostBody event to register click event.

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by UtechtDustin** [comment]
I'm going to close this issue, because we got no example from you.
If you still need help, please let us know and provide us an example.
