### ISSUE TITLE
Cell values containing apostrophes do not appear in searches with an apostrophe

### ISSUE THREAD

**Issue by jnosek** [wenzhixin/bootstrap-table#6594]
### Bootstraptable version(s) affected

1.21.2

### Description

When table data values are loaded from HTML and contain apostrophes (&#39;), any search looking to find rows with values that contain apostrophes do not work. The behavior works correctly when data is loaded via non-html methods, like via javascript/json. 

### Example(s)

https://live.bootstrap-table.com/code/jnosek/13917

A search entered for a single apostrophe `'` would result in no results found.
It should return only Item 5.

### Possible Solutions

The `Util.trToData` function uses `.html()` to return the content of each td. jQuery use the `innerHtml` DOM property provided by the browser. This will return characters like ampersand (&) as an html escaped sequence, but apostrophe is not. The search code currently html escapes the string entered by the user and assumes that apostrophes returned for `Util.trToData` will be escaped.

Apostrophe can be removed from the `Util.escapeHTML()` function, but it is unclear how that would affect other callers, and if table cell contents that need to contain html would be impacted.

### Additional Context

Browser: Microsoft Edge Version 108.0.1462.54 (Official build) (64-bit)
OS: Windows 10.0.19045 Build 19045 (64 bit)

**Comment by UtechtDustin** [comment]
This was a tough issue to figure out the cause!
But to clearify it, in the example the values in the html are not escaped which means the browser escape it.
Except for the apostrophes (if used in td's), which means we compare the escaped values from the browser and the escaped search value.
So we compared `John's Beer`  and `John&#39;s Beer`.
