### ISSUE TITLE
导出excel丢失精度

### ISSUE THREAD

**Issue by Still4** [wenzhixin/bootstrap-table#6595]
### Bootstraptable version(s) affected

1.21.2

### Description

数字只能保留15位，后续会截断

### Example(s)

https://live.bootstrap-table.com/code/Still4/13929

![image](https://user-images.githubusercontent.com/13746605/211742060-74baf0f5-7818-444e-811a-bd5d9d5f55d7.png)

![image](https://user-images.githubusercontent.com/13746605/211741985-24ef776b-718a-4387-85bc-9e909b6ef181.png)

**Comment by fish-fly** [comment]
你可以看下相关问题 #2935
你的问题：https://live.bootstrap-table.com/code/fish-fly/14088
