### ISSUE TITLE
Export Table show only the last "tr"

### ISSUE THREAD

**Issue by cedispindev** [wenzhixin/bootstrap-table#6596]
### Description

Hi

I created the bootstrap-table with two  "tr", but when I export this table only last  "tr" is exported! Do I need create a special configuration to export multiples  "tr"  the my table?

**Comment by UtechtDustin** [comment]
It should export the whole table, please provide us an example using our [editor](live.bootstrap-table.com/).

**Comment by UtechtDustin** [comment]
I'm closing this PR as wen don't get any response/example from you.
If you still think there is a bug please provide us an example.
