### ISSUE TITLE
Cookie-Ext: bs.table.columns is not working

### ISSUE THREAD

**Issue by squeakyflamingo** [wenzhixin/bootstrap-table#6599]
### Bootstraptable version(s) affected

1.21.2

### Description

Using cookie-extension, the documentation shows, that the cookie "bs.table.columns" will save the visible columns. This does not happen.

### Possible Solutions

Reason: https://github.com/wenzhixin/bootstrap-table/commit/a96b85cbd97e1ae29a1742691ffa35396e9f150c

This commit supposedly adds a new cookie "bs.table.hiddenColumns" to replace "bs.table.columns" in a few versions. It actually changes all the logic corresponding to setting "bs.table.columns" to setting "bs.table.hiddenColumns" instead. So the columns-cookie is only read, but never set.

Two possible solution: Make the code use "columns" as an alias to "hiddenColumns" (therefore removing breaking changes) or change the documentation to reflect current behaviour.

**Comment by UtechtDustin** [comment]
You're right, it seems there is some old dead code and documentation.
But the extension for itself should work fine.

Thanks for reporting it.

Example: https://live.bootstrap-table.com/example/extensions/cookie.html
![Bildschirmfoto von 2023-01-16 17-20-49](https://user-images.githubusercontent.com/13292481/212724555-a4942e8a-69aa-4a86-83a8-5fa85d7e2abd.png)
