### ISSUE TITLE
tableExport with custom data

### ISSUE THREAD

**Issue by Cristian9828** [wenzhixin/bootstrap-table#6603]
### Description

Hi everyone,
is there a way to use the method "tableExport" to export custom data with the functions of this plugin?
Like the code below:

Let me know if you can help me!
Thank you very much!

### Example(s)

var tableData = $('#tableArticoli').bootstrapTable('getData');
$('#tableArticoli').tableExport({
    data: tableData,
    type: 'excel',
    exportOptions: {
        fileName: 'some_file_name',
        exportDataType: 'selected'
    }
});

**Comment by UtechtDustin** [comment]
No there is no way to do it with BT directly, but there are a few ways how you could do it with help of a few BT options.
You could use the [buttons option](https://bootstrap-table.com/docs/api/table-options/#buttons) to create you're own export button which triggers the [export plugin](https://github.com/hhurz/tableExport.jquery.plugin) (or a other function which exports the data) for custom data.
You also could temporary load the custom data to the table, but this seems like a "dirty" workaround.
I hope you will find a solution for that, let us know! :)
