### ISSUE TITLE
Update Cell for all raws in a table

### ISSUE THREAD

**Issue by magostinelli** [wenzhixin/bootstrap-table#6609]
### Description

I want to update all values for a field in all table, I discovere the  UpdateCell function:
https://examples.bootstrap-table.com/index.html#methods/update-cell.html

I'm looking for a function like that:

  $(function() {
    $button.click(function () {
        $table.bootstrapTable('updateCell', {
          index: all,
          field: 'Price',
          value: '10$',
          reinit: false
        })
      }

Otherwise, instead of using index: all (that is not working), how can I implement a for cycle to update all the rows in the table?

Regards.

**Comment by UtechtDustin** [comment]
You can get the data with the method [getData](https://bootstrap-table.com/docs/api/methods/#getdata) and then loop through it and use the `updateCellByUniqueId` method or you could just modify the array and load it again using the [load](https://bootstrap-table.com/docs/api/methods/#load) method.
