### ISSUE TITLE
Can't download merged version with bower

### ISSUE THREAD

**Issue by Lotuashvili** [wenzhixin/bootstrap-table#661]
I've sent georgian locale pull request, but I can't install merged version with bower. Tried to clean bower cache, but nothing changed. Can you update 1.6.0 version to 1.6.1?

**Comment by wenzhixin** [comment]
Yes, I think bower is cached in version 1.6.0, I will consider to release a new version after I finish the new feature.

**Comment by wenzhixin** [comment]
New version released: https://github.com/wenzhixin/bootstrap-table/releases

**Comment by Lotuashvili** [comment]
Thanks ! :+1:
