### ISSUE TITLE
filter-control with cell content having links <a> is no longer working - 1.21 regression

### ISSUE THREAD

**Issue by alreay** [wenzhixin/bootstrap-table#6613]
### Bootstraptable version(s) affected

1.21.2, 1.21.1, 1.21

### Description

In release 1.20.2 we are able to filter select cells that contain urls . In release 1.21, and later, we get no results when using the filter.

There were lots of changes in the 1.21 release for filter-control. I'm not sure which of these has caused this problem. Have tested on releases 1.21 and later, all of them have the same problem

### Example(s)

https://live.bootstrap-table.com/code/alreay/14017 v1.21 fails
https://live.bootstrap-table.com/code/alreay/14018 v1.20.2 succeeds

Verify by selecting 'MyLink' in the 'Status' column filter

**Comment by wenzhixin** [comment]
Fixed in the latest version: https://live.bootstrap-table.com/code/wenzhixin/15808
