### ISSUE TITLE
Print does not print the first column in table body. 

### ISSUE THREAD

**Issue by vstarsal** [wenzhixin/bootstrap-table#6616]
### Description

Header has the correct amounts of <th>  elements, but the first <td> in each row of the body does not print. This makes the entire table body shift left, which leaves the last header column with no matching columns in the body and footer.

Also, there is no footer printing. Am I missing something or doing something wrong? I have spent many hours searching for an answer online and am stumped.

Thanks for any help you can give.

This is a laravel site. I have these, included in my opening table tag, on my index.blade.php.
data-show-export="true"
                                                                          data-pagination="true"
                                                                          data-side-pagination="server"
                                                                          data-click-to-select="true"
                                                                          data-toolbar="#toolbar"
                                                                          data-show-toggle="true"
                                                                          data-show-columns="true"
                                                                          data-show-print="true"

I have imported the following scripts
<script src="https://unpkg.com/bootstrap-table@1.21.2/dist/extensions/export/bootstrap-table-export.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.21.2/dist/extensions/print/bootstrap-table-print.min.js"></script>

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by UtechtDustin** [comment]
I close this issue, because we got no example.
If you still need help with this, please provide us an example!
