### ISSUE TITLE
(Search) Caret jumps to the end when symbol is typed

### ISSUE THREAD

**Issue by maxgrass** [wenzhixin/bootstrap-table#662]
Repro:
Type 1 symbo in search.
[ 1|  ]
Set caret/cursor BEFORE the first letter
[  |1 ]
Type 2nd symbol.
[ 2|1 ]

Expected:
search done with cursor after first symbol:
[ 2|1 ]

Happens:
[ 12| ]

It is imposible to add symbols at any position except on the end.

**Comment by djhvscf** [comment]
Just put the table option searchTimeOut with 1

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/e3nk137y/1148/

**Comment by maxgrass** [comment]
Thank you for such dynamic collab! :7

I found out that
The cursor still jumps, I think it might be a browser thing.
Jumps on Chrome 49 64bit,
Works OK (doesn't jump) on FF + IE

**Comment by djhvscf** [comment]
On sorry.. I had some errors in my comment.. I hope this help you...

**Comment by maxgrass** [comment]
Which comment do you mean? I see you are a collaborator, you know what the problem is, can you reproduce this?

**Comment by djhvscf** [comment]
Let me test it!

**Comment by djhvscf** [comment]
Can you provide an example with your problem?? The example above is working on IE, Chrome and FF..

**Comment by wenzhixin** [comment]
This is a bug, fixed it.

**Comment by maxgrass** [comment]
Thank you, need version bump for bug fixes to commit on bower. Could you do this please?

**Comment by wenzhixin** [comment]
Please wait the next version to release.

**Comment by maxgrass** [comment]
Are you releasing them on scedule? I reference the commit for now and check
the release later.
