### ISSUE TITLE
Height属性和Filter Control有冲突

### ISSUE THREAD

**Issue by JohnLucky** [wenzhixin/bootstrap-table#6621]
### Bootstraptable version(s) affected

1.21.0+

### Description

在启用filterControl时指定table的height属性值，会导致select搜索框的值丢失、input搜索框的光标移到最左侧

### Example(s)

https://live.bootstrap-table.com/code/JohnLucky/14095

**Comment by CalmLong** [comment]
same to me

**Comment by CalmLong** [comment]
我也遇到了

而且，在使用 ajax 模式时, filter control 的 input 会丢失已输入的内容，并且我取消设置 table 的 height 之后也会这样

**Comment by UtechtDustin** [comment]
Duplication of #6434
