### ISSUE TITLE
Method getSelections dont return correct data with using pagination and ajax to load table

### ISSUE THREAD

**Issue by Overliest** [wenzhixin/bootstrap-table#6622]
### Description

Hi, I could not find the answer to my question in the existing issues.
My question is why getSelections dont remember "checked" rows and when I change page and set row "checked", getSelections return only row(s) which are on current page.
For example, if you select row with Id = 2, change page and select row with Id = 12, getSelections return only one row with Id = 12, but Id = 2 needed too.
I would be grateful if you could help me resolve this question!

### Example(s)

https://live.bootstrap-table.com/code/Overliest/14101

**Comment by wenzhixin** [comment]
Examples:

- Client-side pagination example: https://live.bootstrap-table.com/example/options/maintain-meta-data.html
- Server-side pagination example: https://live.bootstrap-table.com/example/issues/917.html
