### ISSUE TITLE
ACL/Permissions to hide a column depending on a user role

### ISSUE THREAD

**Issue by stokito** [wenzhixin/bootstrap-table#6627]
### Description

I need to make a table that will show all columns for admin users and hide some columns if a user doesn't have a permission.

I implemented this by adding a separate data attribute `data-acl-cols` that has a list of columns to hide for a usual non-admin user:

```
        <table
               data-toggle="table"
               data-acl-cols="Price,Amount"
        >
```

And added window.onload event hook that finds all bootstrap tables, takes the `data-acl-cols` field, splits by comma to get list of cols and hides them all:  
```js
    let bootstrapTables = document.querySelectorAll('[data-toggle="table"]')
    console.log(bootstrapTables)
    for (let bootstrapTableEl of bootstrapTables) {
        let $table = $(bootstrapTableEl).bootstrapTable()
        let aclCols = bootstrapTableEl.dataset.aclCols
        if (!aclCols) {
            continue
        }
        let fields = aclCols.split(',')
        for (let field of fields) {
            $table.bootstrapTable('hideColumn', field)
            console.log('hideColumn ' + field)
        }
    }
``` 

The code works but maybe this is something that can be implemented in the BT itself?
Also still a user can enable the column manually. So ideally I need to just hide the column but disable it completely.

**Comment by wenzhixin** [comment]
I think a better way is to control the column options(`visible` and `switchable`).

- Admin role: https://live.bootstrap-table.com/code/wenzhixin/14117
- User role: https://live.bootstrap-table.com/code/wenzhixin/14118

**Comment by stokito** [comment]
thank you. It also would be great to have out of the box sonething like `data-acl-cols` or `data-hidden-cols` to specify hidden rows on a table level. If anyone needs this too please vote
