### ISSUE TITLE
如何在使用jQuery的.bootstrapTable()函数创建表格时进行空数据处理

### ISSUE THREAD

**Issue by RosterMouch** [wenzhixin/bootstrap-table#6628]
### Description

如题，我的代码先在是这样的：
```javascript
if (response.data.data != null) {
    $course_table.bootstrapTable({
        data: response.data.data,
        columns: columns,
    })
} else {
    $course_table.bootstrapTable({
        data: ["不可用"],
        columns: columns,
    })
}
```
我使用axios先从后端获取到数据后，但是发现返回值为null，那么我应该如何进行修改以实现示例中no data的效果呢？
以下是我的Tauri APP中加载的效果：
![image](https://user-images.githubusercontent.com/75596885/216644670-d338f674-16e0-404e-b334-7d37fd09be1c.png)
而我预期的是如同no data示例中的效果：
![image](https://user-images.githubusercontent.com/75596885/216644779-ce588d54-0907-4c97-95fa-e386b22e12c1.png)
请问该如何操作，求指教，谢谢了！

**Comment by fish-fly** [comment]
使用空数组就可以了：
```js
if (response.data.data != null) {
    $course_table.bootstrapTable({
        data: response.data.data,
        columns: columns,
    })
} else {
    $course_table.bootstrapTable({
        data: [],
        columns: columns,
    })
}
```
或者优化为：
```js
$course_table.bootstrapTable({
    data: response.data.data || [],
    columns: columns,
})
```
https://live.bootstrap-table.com/code/fish-fly/14116
