### ISSUE TITLE
CSP Violations - bootstrapTable() function adds empty style element to table headers when no styles are defined

### ISSUE THREAD

**Issue by timothymowens** [wenzhixin/bootstrap-table#6632]
### Bootstraptable version(s) affected

1.21.2

### Description

Executing the bootstrapTable() method on a table to instantiate it will create table headers that have empty style elements. These empty style tags trigger CSP violations just for being there without any styles defined.

There are 2 offending lines of code, causing this CSP violation (lines 347 and 2269):

```
(347)    Utils.sprintf(' style="%s"', halign + style + csses.join('; ')),

(2269)    html.push('<th', class_, Utils.sprintf(' style="%s"', falign + valign + csses.concat().join('; ')))

```

These lines should only concatenate the style element to the <th> tag if there are in fact styles defined.  However, when there are no styles specified, this is inserting an empty "style" element.

### Example(s)

Please view the source code of the table here: https://examples.bootstrap-table.com/#methods/append.html

You can see the empty style elements that have been added by the bootstrapTable() method, as shown below:

```
<table class="table table-bordered table-hover" style="width: 1440px;">
    <thead>
        <tr>
            <th style data-field="id">
                <div class="th-inner ">ID</div>
                <div class="fht-cell" style="width: 238.578px;"></div>
            </th>
            <th style data-field="name">
                <div class="th-inner ">Item Name</div>
                <div class="fht-cell" style="width: 619.938px;"></div>
            </th>
            <th style data-field="price">
                <div class="th-inner ">Item Price</div>
                <div class="fht-cell" style="width: 577.484px;"></div>
            </th>
        </tr>
    </thead>
</table>
```

You can also see these empty style elements added to the <th> tags in the attached image, demonstrating this empty element added to the <th> tags on an example on the bootstrap-table.com website:

![boostrap-tables-empty-style-tag](https://user-images.githubusercontent.com/3083890/217106639-a22e1c8c-48e0-4399-94e6-b42104487b42.jpg)

### Possible Solutions

Only add the style element if there are indeed styles defined for the <th> element.  The best solution would be to use classes instead of styles, but I understand the complexity involved with that.  In order to not violate CSP, the style can be changed in Javascript by manipulating the element, but actually setting the inline style element on a tag will violate CSP.  For example:

Change line 347 from:
```
Utils.sprintf(' style="%s"', halign + style + csses.join('; ')),
```
to:
```
(halign + style + csses.join('; ')) ?? Utils.sprintf(' style="%s"', halign + style + csses.join('; ')),
```
And change line 2269 from:
```
html.push('<th', class_, Utils.sprintf(' style="%s"', falign + valign + csses.concat().join('; ')))
```
to:
```
html.push('<th', class_, (falign + valign + csses.concat().join('; ')) ?? Utils.sprintf(' style="%s"', falign + valign + csses.concat().join('; ')))
```

### Additional Context

Please note, these suggestions are only bandaids to a much larger issue.  These styles should not be assigned inline as they violate CSP.  They should either have classes assigned or the style should be adjusted in Javascript (ie. `document.getElementById('test').style.Foo = 'Bar'`).

**Comment by gsmethells** [comment]
@UtechtDustin will CSP changes be on this project's radar anytime soon?
