### ISSUE TITLE
Export Plugin Export options not properly functioning 

### ISSUE THREAD

**Issue by HariharanUmapathi** [wenzhixin/bootstrap-table#6641]
### Bootstraptable version(s) affected

1.21.1,1.21.2

### Description

I have configured bootstrap-table with the following options 

var $table = $('#table')

  $(function() {
    $('#toolbar').find('select').change(function () {
      $table.bootstrapTable('destroy').bootstrapTable({
        exportDataType: $(this).val(),
        exportTypes: ['csv', 'excel'],
        exportOptions:{
          filename:"Export"
},
        columns: [
          {
            field: 'state',
            checkbox: true,
            visible: $(this).val() === 'selected'
          },
          {
            field: 'id',
            title: 'ID'
          }, {
            field: 'name',
            title: 'Item Name'
          }, {
            field: 'price',
            title: 'Item Price'
          }
        ]
      })
    }).trigger('change')
  })
1.File name is not changed after saving and running 
Expected Result: exported file should has name 'Export'.{file_extension}
Actual Result : Exported file has name 'tableExport'

2.Export data type set to csv and excel but it show 
some other options 
Expected Result: export file type expected 2 
Actual Result: export file type 6 types

REF-1
![image](https://user-images.githubusercontent.com/62648127/218492503-13a04b32-0598-47a9-8b75-497d1858b157.png)

### Example(s)

https://live.bootstrap-table.com/code/HariharanUmapathi/14268

### Additional Context

Windows 10 ,
Latest Chrome Browser V 110.0.5481.77

**Comment by UtechtDustin** [comment]
1. You're option key is `filename` insteaf of `fileName`.
    Working filename example: https://live.bootstrap-table.com/code/UtechtDustin/14289
2. It seems there is a weired bug, as soon we add `data-export-types` to the table tag (no need for a value) it works fine.
    We will check that.
    Example: https://live.bootstrap-table.com/code/UtechtDustin/14296
