### ISSUE TITLE
how to set font family/size when exporting excel

### ISSUE THREAD

**Issue by takeAction** [wenzhixin/bootstrap-table#6646]
### Description

When exporting to `.xlsx`, I hope that the  excel file has customize font family/size and text is wrapped, how can I do that?

**Comment by UtechtDustin** [comment]
I seems this is not possible, we are limited to the possibilities of the used [export plugin](https://github.com/hhurz/tableExport.jquery.plugin).  
As far i saw in the documenation, you can only set a font for pdf's.  
Please check the documentation of the export plugin.
