### ISSUE TITLE
Selecting checkboxes while sorting a column duplicates entries

### ISSUE THREAD

**Issue by lucs100** [wenzhixin/bootstrap-table#6654]
### Bootstraptable version(s) affected

1.21.2

### Description

When creating a table with a column of sortable checkboxes, selecting checkboxes while their column is being sorted causes very buggy behaviour, most notably by duplicating some rows. This occurs on my current implementation but I was able to recreate it using one of the example files.

I used the example code in https://github.com/wenzhixin/bootstrap-table/issues/987#issuecomment-115065241 with the only modification being to add the option `data-sortable="true"` to the Selling (checkbox) column. Note this isn't necessary, but my implementation uses it - you can also reproduce this bug with [this code](https://live.bootstrap-table.com/code/wenzhixin/13728) for example, which **does not implement sortable checkboxes**. My code is [here](https://live.bootstrap-table.com/code/lucs100/14411). I ran this code locally with different JSON (to fit on one screen) with the same behaviour, shown in the gif below:

![tableSortIssue](https://user-images.githubusercontent.com/59773132/221030918-27c00f6a-73b9-44e9-ade9-e4e8878ed257.gif)

To reproduce:
1. Sort any column
2. Select checkboxes
3. Buggy behaviour occurs:
    * Duplicate entries are created
    * Selecting/unselecting entries with duplicates sometimes selects/unselects their duplicates

**Comment by UtechtDustin** [comment]
I'm not sure if this is a bug, the example ist 7 1/2 years old and outdatet i guess.
We now have the [checkbox](https://bootstrap-table.com/docs/api/column-options/#checkbox) option, which should work.
Could you please check if this bug exists if you use the latest methods/events ?
If it don't work, please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by lucs100** [comment]
**The native checkbox option does seem to fix this issue. I meant to include context and totally forgot - sorry for turning this into an XY problem.**  I have opened a new issue regarding this (#6669) and will close this one now, thank you.
