### ISSUE TITLE
Issue with pre-rendered tables having rowspan and style display: none

### ISSUE THREAD

**Issue by papersaltserver** [wenzhixin/bootstrap-table#6656]
### Bootstraptable version(s) affected

1.21.2

### Description

Hello,
there is an issue with trToData function, it suggests that if html has td element, then it is visible. https://github.com/wenzhixin/bootstrap-table/blob/b9dbe9e6b36fa2ca822f5ce3f41a5f4278a27357/src/utils/index.js#L521 here for the first tr of the example you fill mask matrix allowing to "skip" those positions in matrix:
|td0|td1|td2|td3|td4|td5|
|---|---|---|---|---|---|
|true|true|true|true|true|true|
|true|true|undefined|undefined|true|true|
|true|undefined|undefined|undefined|undefined|true|

which causes 2nd tr to be interpreted incorrectly, first found td is treated as field[2], second td is field[3], third td is field[6] - which does not even exist.

### Example(s)

https://live.bootstrap-table.com/code/papersaltserver/14531

### Possible Solutions

When we're parsing html table we could check if processed cell is visible or not

**Comment by UtechtDustin** [comment]
I'm not sure if this is a bug, could you please explain us you're setup and usecase ?   
I don't know why you would have a table with a few `style="display: none"` on the td's and then try to render the table via BT-Table.

**Comment by papersaltserver** [comment]
If there is no td with style="display: none", then filtering extenstion is not working properly, if there are tds with display: none, then BT is not working.
I want to create static table on server side with as little as possible dom modifications on the client.

**Comment by wenzhixin** [comment]
I think `<td style='display: none'>` is not a standard table, so it's normal not to support it because it's hard to tell if a custom class is `display: none`.
