### ISSUE TITLE
Django's inplaceedit compatibility

### ISSUE THREAD

**Issue by ajendrex** [wenzhixin/bootstrap-table#666]
Hello,

I find bootstrap-table of great value. I'm trying to use it together with django-inplaceedit, which allows to edit values by double-clicking on them. Everything works fine, until the user sorts the rows of a table, then the inplaceedit functionality is lost...

Anyone could look at this or tell me what could I try, please?

thanks,
Hector.

**Comment by djhvscf** [comment]
@ajendrex  can you provide some code?? or fiddle?? And check this out: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable

**Comment by wenzhixin** [comment]
Please use editable extension first, if you finish your django-inplaceedit version, any pull request is welcome.
