### ISSUE TITLE
the selection hidden when use Filter Control and  data-height

### ISSUE THREAD

**Issue by goczen** [wenzhixin/bootstrap-table#6665]
### Bootstraptable version(s) affected

1.21.1

### Description

If I use the data-height attribute the selecton hidden after select a value  in filter control extension.

https://live.bootstrap-table.com/example/extensions/filter-control.html
Select a price and the selected value disappers after selection.  

### Example(s)

<table
  id="table"
  data-url="json/data1.json"
  data-filter-control="true"
  data-show-search-clear-button="true"
  data-height="300">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name" data-filter-control="input">Item Name</th>
      <th data-field="price" data-filter-control="select">Item Price</th>
    </tr>
  </thead>
</table>

<script>
  $(function() {
    $('#table').bootstrapTable()
  })
</script>

**Comment by UtechtDustin** [comment]
Duplication of https://github.com/wenzhixin/bootstrap-table/issues/6434
