### ISSUE TITLE
Table with pagination, multiple pages and a search that matches to one page throws exception

### ISSUE THREAD

**Issue by tzahari** [wenzhixin/bootstrap-table#667]
Hi There,
I have a table with pagination and multiple pages.
If I search for a term with a exact result of 10 rows (1 page).
Then a exception in the console log occurs and the table is not refreshed:
```javascript
[Error] TypeError: undefined is not a function (evaluating 'this.options.pageList.replace('[', '')')
	initPagination (bootstrap-table.js, line 991)
	updatePagination (bootstrap-table.js, line 1139)
	onSearch (bootstrap-table.js, line 876)
	(anonyme Funktion) (bootstrap-table.js, line 847)
```
I found out that the .replace is not possible on a array.
So a fix could be possible to change it first toString().

```javascript
var pageLst = this.options.pageList.toString().replace('[', '').replace(']', '').replace(/ /g, '').toLowerCase().split(',');
```
~~Hint: there are more than one place where this is done.~~

Best regards
Thomas

**Comment by djhvscf** [comment]
Can you provide your table configuration??

**Comment by qq239962399** [comment]
I found the solution, just update JQuery to 2.X

**Comment by djhvscf** [comment]
Well, sounds good but it is not a common solution for all us. @qq239962399

**Comment by qq239962399** [comment]
Pro-test available. XD @djhvscf

**Comment by djhvscf** [comment]
Sure.

**Comment by tzahari** [comment]
Hi @qq239962399,
I am using jQuery 2.1.3.
I'll try to setup a jiddle..

**Comment by tzahari** [comment]
Here is a working Bug example: 
https://jsfiddle.net/jwhcp41z/28/
In the console of the browser appears the top posted error.

**Comment by djhvscf** [comment]
Ref to: https://github.com/djhvscf/bootstrap-table/commit/9dde6b3e13e35db1db9ea11328c7577c16ff4af5

**Comment by tzahari** [comment]
Thanks to all.
