### ISSUE TITLE
is v1.21.2 with bootstrap-table-editable.js compatible with Bootstrap V5?

### ISSUE THREAD

**Issue by diegofazio** [wenzhixin/bootstrap-table#6671]
### Description

I can't find an example of extension bootstrap-table-editable.js

is v1.21.2 with bootstrap-table-editable.js compatible with Bootstrap V5?

Thanks
Diego.

**Comment by dieggoesteban** [comment]
x-editable has support up to Bootstrap 3, so no. It is no longer supported. There are some forks that allow using x-editable with bootstrap 4 and 5, but I couldn't get it to work properly and haven't found any viable alternative plugins yet.

**Comment by UtechtDustin** [comment]
As @dieggoesteban said x-editable only support BT two and three.
