### ISSUE TITLE
how can i add extra search condition？

### ISSUE THREAD

**Issue by zsj1029** [wenzhixin/bootstrap-table#668]
how to add another search "input"?
or how to get search url like "&search=234&order=asc&limit=10&offset=0"  before pass into the webserver? 
I want to add extra search condition.
I found "onSearch" Events,but how to use it?  it have a Parameter like "text" ,but  i cant find search condition

thanks

**Comment by zsj1029** [comment]
ok,i found it in the issue history. 
the example in doc is too simple,please add an complete example.
for example：
1、like:   
   <input type='text' id='userCode' />
    <table id="table"
                   data-query-params-type="limit"
                   data-query-params="queryParams"
                   data-url="index.php?_url=/admin/courseData">
                <thead>
                <tr>
                    <th data-field="state" data-checkbox="true"></th>
                    <th data-field="id" data-sortable="true">ID</th>
                </tr>
                </thead>
            </table>
add: data-query-params-type="limit"
       data-query-params="queryParams"

2、add js:    function queryParams(params){
        params['user_code']=$('#userCode').val();
        return params;
    }
3、refresh page , u will found ajax url have extra condition.
like index.php?_url=/admin/courseData&search=123&order=asc&limit=10&offset=0&user_code=admin

**Comment by djhvscf** [comment]
Sounds great!! Any pull request is welcome! @zsj1029
