### ISSUE TITLE
data-sortable fails on numbers that are links

### ISSUE THREAD

**Issue by osterchrisi** [wenzhixin/bootstrap-table#6680]
### Bootstraptable version(s) affected

5.3

### Description

The "data-sortable='true'" functionality fails on table data that represents a link. In my case, I am showing stock levels for parts and I render my table data like this:
`echo "<td><a href='show-stock.php?part_id=$part_id'>" . $total_stock . "</a></td>";`
If I do this in a sortable column, the sorting goes for the $part_id in the link, not the actual $total_stock number.

If I remove the links, like so:
`echo "<td>$total_stock</td>";`
It works like expected.

### Example(s)

<table
  id="table"
  data-toggle="table"
  data-height="460">
  <thead>
  <tr>
    <th data-field="id" data-sortable="true">ID</th>
    <th data-field="name" data-sortable="true">Item Name</th>
    <th data-field="price" data-sortable="true">Item Price</th>
  </tr>
  </thead>
  <tbody>
  	<tr>
    	<td><a href="show-stock.php?part_id=999">1</a></td>
    	<td><a href="show-stock.php?part_id=999">1</a></td>
    	<td><a href="show-stock.php?part_id=999">1</a></td>
    </tr>
      	<tr>
    	<td><a href="show-stock.php?part_id=777">2</a></td>
    	<td><a href="show-stock.php?part_id=777">2</a></td>
    	<td><a href="show-stock.php?part_id=777">2</a></td>
    </tr>
      	<tr>
    	<td><a href="show-stock.php?part_id=888">3</a></td>
    	<td><a href="show-stock.php?part_id=888">3</a></td>
    	<td><a href="show-stock.php?part_id=888">3</a></td>
    </tr>
  </tbody>
</table>

**Comment by osterchrisi** [comment]
Use this example code: https://pastebin.com/7Z8zGAsK

**Comment by osterchrisi** [comment]
Actually now when I look at the example provided: https://examples.bootstrap-table.com/#options/table-sortable.html It doesn't even really work there. I mean, it _does_ sort the columns but it also doesn't really sort them correctly. Try to sort by columns "Item Name" and "Item Price". It's just wrong. Sorting by "ID" on the other hand seems to work correctly.

**Comment by osterchrisi** [comment]
Found a way to make it sort URLs, with the BT sorter functionality (data-sorter). This works:
`echo "<th data-sortable='true' data-sorter='NumberURLSorter'>$column_header</th>";`

```
  function NumberURLSorter(a, b) {
    // This regex takes the '>' and any amount of numbers that come afterwards
    const regex = />\d+/gm;

    // Regex both cell contents as strings
    const m = String((new RegExp(regex)).exec(b));
    const n = String((new RegExp(regex)).exec(a));

    // Remove the '>'
    const aa = m.replace('>', '');
    const bb = n.replace('>', '');

    return aa - bb;
```

**Comment by wenzhixin** [comment]
This may help you.
```js
function NumberURLSorter(a, b) {
  return $(a).text() - $(b).text()
}
```
Example: https://live.bootstrap-table.com/code/wenzhixin/14638
