### ISSUE TITLE
Filter-control select não funciona para mesma data-field em tabelas diferentes.

### ISSUE THREAD

**Issue by matheusilario** [wenzhixin/bootstrap-table#6684]
### Description

Olá, tive um problema em utilizar o filter-control select em 2 tabelas diferentes que possuem uma coluna com mesmo nome. Na primeira tabela aparece as opções no select, na segunda tabela não. Em outras colunas o select funciona.

Corrigi utilizando um data-field diferente na segunda tabela e utilizando o data-formatter para exibir o valor correto.

Teria alguma opção para fazer funcionar?

**Comment by cwh42** [comment]
Hello, I had a problem using the filter-control select in 2 different tables that have a column with the same name. In the first table the options appear in the select, in the second table they don't. In other columns the select works.


I fixed it by using a different data-field in the second table and using data-formatter to display the correct value.


Would you have any option to make it work?

Translated using https://www.deepl.com/translator

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days. If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!
