### ISSUE TITLE
How can i get the null data?

### ISSUE THREAD

**Issue by wangzhifeng** [wenzhixin/bootstrap-table#669]
When i searched something with conditions, and then displayed in the bootstrap-table, if there is no data, I return to the format is "{totla: 0, rows: null}", but in the "initData" method, "this.data = data || this.options.data;" will assigned the last data to "this.data", it do not matched. So how the result just like or what should i configure ? Thank you

**Comment by djhvscf** [comment]
Can you translate it, please? @wangzhifeng

**Comment by zsj1029** [comment]
data-cache="false"？

**Comment by zsj1029** [comment]
if null 
return {"total":0,"rows":[]}
it‘s ok.

**Comment by wangzhifeng** [comment]
@djhvscf  When I searched for something, I want to show the result in the bootstrap-table. But, If there is no results, how can i get the return value? I used  '{total: 0, rows: null}', but it concat the last data in the "bootstrap-table.js", so I do not know where the problem was.

**Comment by wangzhifeng** [comment]
@zsj1029  Thanks, it worked.
