### ISSUE TITLE
Data Search Selector plus search field

### ISSUE THREAD

**Issue by ionultd** [wenzhixin/bootstrap-table#6691]
### Description

I would like to be able to have the a dropdown select option plus the search field in combination.

Thank you

### Example(s)

https://live.bootstrap-table.com/code/ionultd/14713

**Comment by UtechtDustin** [comment]
@wenzhixin @fish-fly i don't think #6712 fixed this issue.
He asked for an combination of a select AND a search input.

Also his select works fine for me, why we need the changes in the PR ?
![Bildschirmfoto von 2023-03-28 19-30-32](https://user-images.githubusercontent.com/13292481/228320981-1b79fb6c-fd28-4df8-8f0e-d7924820f24f.png)

**Comment by wenzhixin** [comment]
You don't leave the focus after you change the value of the select, and you can see what the problem is.
![image](https://user-images.githubusercontent.com/2117018/228415839-8afeeb10-39e6-454b-8864-b277cda61359.png)

**Comment by UtechtDustin** [comment]
> You don't leave the focus after you change the value of the select, and you can see what the problem is

Which Browser do you use ?   
I can't reproduce it on Firefox (Ubuntu) 111.0

**Comment by wenzhixin** [comment]
Chrome

**Comment by wenzhixin** [comment]
@UtechtDustin 
Firefox also has problems. You can click the select and then use the keyboard to select up and down and press enter.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/2117018/229158616-12fbcfec-bf6b-4a78-a273-de564f4f7696.png">

**Comment by UtechtDustin** [comment]
@wenzhixin Strange i can't reproduce it...
So if you can reproduce it the PR is fine for me, but the PR still don't fix this issue!
As i already wrote he asked for an combination of a select AND a search input.

**Comment by wenzhixin** [comment]
Can you describe your specific needs? @ionultd
