### ISSUE TITLE
How do I update the table columns from server side response from ajax method?

### ISSUE THREAD

**Issue by epicwhale** [wenzhixin/bootstrap-table#6695]
### Description

My table's output (both columns and rows) are derived from a REST API.

I read that the best way to recreate the table with new columns is by using the 'refreshOptions' method. But when I do this inside the 'ajax' method for the table, it goes into an infinite loop - as it looks like it completely destroys the table, rebuilds it and triggers the ajax load again.

This causes an infinite recursive loop of ajax calls.

What is an elegant way to recreate the columns based on the response data before loading the rows?

I have created a live example to demonstrate this scenario

### Example(s)

Live example here: https://live.bootstrap-table.com/code/epicwhale/14790

**Comment by wenzhixin** [comment]
ref issues:
* #5679
* #1178

example: https://live.bootstrap-table.com/code/wenzhixin/7810

**Comment by wenzhixin** [comment]
We are going to close this PR. If the problem exists, reopen it. Thanks!
