### ISSUE TITLE
Webpack Encore broken since 1.21.3

### ISSUE THREAD

**Issue by simonsolutions** [wenzhixin/bootstrap-table#6696]
### Bootstraptable version(s) affected

1.21.3

### Description

I used the bootstrap table library within a webpack encore setup (symfony based).
With upgrading to 1.21.3 bootstrap table breaks to javascript function with raising the following error:

TypeError: undefined is not an object (evaluating '$$o.BootstrapTable = BootstrapTable')

![image](https://user-images.githubusercontent.com/20499623/226141494-2b3c889f-3c90-45a0-a2dd-234d8760974c.png)

### Example(s)

There is no easy way to provide a complete example as it is part of a web pack encore configuration

**Comment by wenzhixin** [comment]
You can check out this example: https://github.com/wenzhixin/bootstrap-table-examples/tree/develop/webpack-starter

**Comment by wenzhixin** [comment]
If the problem exists, reopen it. Thanks!

**Comment by simonsolutions** [comment]
The problem still exists. The sample can't be used directly as it es a symfony webpack encore configuration of the project. 
The break starts with the new version 1.21.3 as mentioned above. With the forced version 1.21.2 everything works fine.

**Comment by wenzhixin** [comment]
Can you provide some codes to show your problem?

**Comment by simonsolutions** [comment]
This is the webpack.config.js of a basic symfony project with twig and web pack encore configured:

`let Encore = require('@symfony/webpack-encore');
let CopyWebpackPlugin = require('copy-webpack-plugin');
const path = require('path');

// Manually configure the runtime environment if not already configured yet by the "encore" command.
// It's useful when you use tools that rely on webpack.config.js file.
if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

Encore
    // directory where compiled assets will be stored
    .setOutputPath('public/build/')
    // public path used by the web server to access the output path
    .setPublicPath('/build')
    // only needed for CDN's or subdirectory deploy
    .setManifestKeyPrefix('build/')

    .addEntry('app', './assets/app.js')

    // enables the Symfony UX Stimulus bridge (used in assets/bootapp.js)
    .enableStimulusBridge('./assets/controllers.json')

    // When enabled, Webpack "splits" your files into smaller pieces for greater optimization.
    .splitEntryChunks()

    // will require an extra script tag for runtime.js
    // but, you probably want this, unless you're building a single-page app
    .disableSingleRuntimeChunk()

    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    // enables hashed filenames (e.g. app.abc123.css)
    .enableVersioning(Encore.isProduction())

    .configureBabel((config) => {
        config.plugins.push('@babel/plugin-proposal-class-properties');
    })

    // enables @babel/preset-env polyfills
    .configureBabelPresetEnv((config) => {
        config.useBuiltIns = 'usage';
        config.corejs = 3;
    })

    // enables Sass/SCSS support
    .enableSassLoader()

    // uncomment if you use TypeScript
    //.enableTypeScriptLoader()

    // uncomment if you use React
    //.enableReactPreset()

    // uncomment to get integrity="..." attributes on your script & link tags
    // requires WebpackEncoreBundle 1.4 or higher
    .enableIntegrityHashes(Encore.isProduction())

    // uncomment if you're having problems with a jQuery plugin
    .autoProvidejQuery()
    .autoProvideVariables({
        $: 'jquery',
        'jQuery': 'jquery',
        'window.jQuery': 'jquery',
    })
;

module.exports = Encore.getWebpackConfig();
`

Which imports the assets/js/runmagix_js.js
`
'use strict';

global.$ = global.jQuery = $ = require('jquery');
//.... more imports

import 'bootstrap-table/dist/bootstrap-table.js'
import 'bootstrap-table/dist/extensions/mobile/bootstrap-table-mobile.js'
import 'bootstrap-table/dist/extensions/export/bootstrap-table-export.js'
import 'bootstrap-table/dist/extensions/print/bootstrap-table-print.js'
import 'bootstrap-table/dist/extensions/cookie/bootstrap-table-cookie.js'
import 'bootstrap-table/dist/extensions/group-by-v2/bootstrap-table-group-by.js'
import 'bootstrap-table/dist/locale/bootstrap-table-en-US.js'
import 'bootstrap-table/dist/locale/bootstrap-table-de-DE.js'

import 'bootstrap-table/dist/bootstrap-table.css';
import 'bootstrap-table/dist/extensions/group-by-v2/bootstrap-table-group-by.css';
`

**Comment by Zerogiven** [comment]
I have the same problem and my first thought was that i depends on the webpack version. I have the same error like @simonsolutions at my silverstripe project with custom gulp tasks registry. However, i realy don't get it why this happens, but i bet if you are upgrading the example to webpack >=5 you would get the same error.

I tried using the latest webpack and bootrstap table with bootstrap 4.

**Comment by Zerogiven** [comment]
Oh and yes, i have provided jquery via provide plugin from webpack (https://webpack.js.org/plugins/provide-plugin/#usage-jquery)
Cause other things from my project need that global jQuery thing too :/ 

```
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
        //     // jQuery: 'jquery',
        //     // $: 'jquery',
        //     // 'window.jQuery': 'jquery',
        //     // 'window.$': 'jquery',
        //     // 'global.jQuery': 'jquery',
        //     // 'global.$': 'jquery',
        //     // // 'globalThis.jQuery': 'jquery',
        //     // // 'globalThis.$': 'jquery',
        //     // Buffer: ['buffer', 'Buffer'],
        }),
    ],
```

**Comment by Zerogiven** [comment]
Yes, i tried it now and at your examples @wenzhixin you have the same problem if you are using latest webpack

Error:
```
caught TypeError: Cannot set properties of undefined (setting 'BootstrapTable')
    at v (main.js:2:484155)
    at main.js:2:485407
```

I only changed package.json to this:
```json
{
  "name": "webpack-bootstrap-table",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "css-loader": "^6.7.3",
    "style-loader": "^3.3.2",
    "webpack": "^5.79.0",
    "webpack-cli": "^5.0.1",
    "webpack-dev-server": "^4.13.3"
  },
  "dependencies": {
    "bootstrap": "^4.5.0",
    "bootstrap-table": "^1.21.4",
    "jquery": "^3.6.4",
    "popper.js": "^1.16.1"
  },
  "scripts": {
    "build": "webpack",
    "dev": "webpack-dev-server --inline --progress"
  }
}
```

Run
- npm install
- npm run build
- open dist/index.html
- See the error ;-)

**Comment by Zerogiven** [comment]
One last thing i've noticed is that if i downgrade bootstrap table to 1.21.2 it looks like all things are working :)

I thought i would find the diff between the two versions but there are 178 commits between them :D

However, hope the with the information we can find out the problem between the two versions so we can use latest webpack :)

**Comment by UtechtDustin** [comment]
Could you please create an minimal repository for testing ?
I never had this issue at work and my main framework is symfony with encore.

Btw. encore has an option called `autoProvidejQuery` to provide jQuery, please check the documentation: https://symfony.com/doc/current/frontend/encore/installation.html.

**Comment by DaDeather** [comment]
For those guys having issues here. You're probably importing the wrong files.

As written in the [comment](https://github.com/wenzhixin/bootstrap-table/issues/6696#issuecomment-1493410756) the used files there are the `dist` files.

There should be no problem when using the `src` files and using the `autoProvidejQuery()` configuration in WebpackEncore.

We're using the following with this configuration enabled:
```
import 'bootstrap-table/src/bootstrap-table.js';
import 'bootstrap-table/src/locale/bootstrap-table-de-DE.js';
import 'bootstrap-table/src/extensions/group-by-v2/bootstrap-table-group-by.js';
```
