### ISSUE TITLE
data-side-pagination="server" and reorder row

### ISSUE THREAD

**Issue by Framelony** [wenzhixin/bootstrap-table#6698]
### Bootstraptable version(s) affected

1.21.3

### Description

after a long investigation a found the reason because reorder row was not working in my app and it was related of that attribute data-side-pagination="server". 
there is  a reason ? 
can you note in the doc please for other users ? 
thanks 

### Possible Solutions

remove data-side-pagination="server" os use "client"

**Comment by wenzhixin** [comment]
What does it mean that it doesn't work? Can you provide an online example?

**Comment by Framelony** [comment]
with        
data-side-pagination="server"
ids  in the getData are not correct:
[https://live.bootstrap-table.com/code/promotux/14826](url)

with        data-side-pagination="client" are
