### ISSUE TITLE
How to Scroll bootstrap table horizontally programmatically

### ISSUE THREAD

**Issue by raj1127** [wenzhixin/bootstrap-table#671]
In my webpage I have a hyperlink. On clicking this hyperlink, I am showing a bootstrap table with number of columns populated. I can scroll horizontally or vertically through horizontal and vertical scorllbars. But what is happening is that when I am again clicking the hyperlink to see the updated contents in the bootstrap table, it is retaining the previous scroll position horizontally and vertically. So my question is how do I reset the scroll bars position horizontally when clicking on the hyperlink to display the bootstrap table? I want the bootstrap table horizontal scrollbars to be positioned at initial scroll position.

**Comment by djhvscf** [comment]
Something like this? http://issues.wenzhixin.net.cn/bootstrap-table/#methods/scrollTo.html

**Comment by raj1127** [comment]
Thanks for your reply. I know that we can do it vertically using ScrollTo method BUT I want to scroll Horizontally from left to right using some method.

**Comment by djhvscf** [comment]
Yeah.. It was just to be sure.. I think it is not a feature supported by our plugin.. but you can do that for a while with this https://api.jquery.com/scrollleft/

**Comment by wenzhixin** [comment]
Do not support this feature.
