### ISSUE TITLE
Save Column Resizable Configuration In Cookie

### ISSUE THREAD

**Issue by solutions-simplified** [wenzhixin/bootstrap-table#6718]
### Description

This is similar to Issue #2889, however I'm using the resizable extension and I wanted to know if there would be able to save the column size in the configuration so if I refreshed the screen it would maintain the column widths I had previous set.

If this is already supported can you verify the version of the extension I need to use as well as any attributes I need to add.

I'm seeing the column reorder to persist but it's not doing it for me on the resize.

**Comment by wenzhixin** [comment]
@UtechtDustin Does PR #4829 already support this feature?

**Comment by UtechtDustin** [comment]
This PR has added the support for that yes, but not with cookie but with the localstorage (using store.js) as suggested by the resizable plugin (http://dobtco.github.io/jquery-resizable-columns/).
Example: https://live.bootstrap-table.com/code/UtechtDustin/14914
But it seems something broke it in the last updates as the key is always `undefined-undefined` in the localstorage.

**Comment by laundmo** [comment]
i found that it works when you manually add the correct IDs which jquery-resizable-columns expects and manually include store.js

```html
 <table id="table" data-resizable-columns-id="table" data-resizable="true">
  <thead>
    <tr>
      <th data-field="field1" data-resizable-column-id="field1">Field 1</th>
      <th data-field="field2" data-resizable-column-id="field2">Field 2</th>
      <th data-field="field3" data-resizable-column-id="field3">Field 3</th>
    </tr>
  </thead>
</table>
<script src="js/store.modern.min.js"></script>
<script src="js/jquery.resizableColumns.min.js"></script>
...
```

**Comment by wenzhixin** [comment]
@laundmo Great, thanks for your feedback.

**Comment by laundmo** [comment]
I don't feel like this issue is resolved - what I posted is a workaround, not a solution
