### ISSUE TITLE
Column Fixed Width in Percentage Problem

### ISSUE THREAD

**Issue by alvin0618** [wenzhixin/bootstrap-table#672]
I defined the column using percentage, however when switch to card view and switch back to table view.
The column width from % change back px.

jsfiddle:
https://jsfiddle.net/alvin_ng0618/8eh2t597/3/

**Comment by djhvscf** [comment]
Fixed: Ref to: https://github.com/wenzhixin/bootstrap-table/pull/673 and to: https://github.com/wenzhixin/bootstrap-table/commit/62a92ec47c936031f78a0523185c2b5e606bef93

**Comment by wenzhixin** [comment]
https://jsfiddle.net/alvin_ng0618/8eh2t597/3/

**Comment by alvin0618** [comment]
I'm sorry that may be I didn't state the problem clearly.
Yes, with the code when inti the table is column width is working perfectly. 
However, the problem is when I click the "toggle" button change to card view, the column width transform the unit width from % to px.

**Comment by alvin0618** [comment]
Please try to click the toggle button (change to card view table and then click again change back to table view). and you will see the problem that the column will refer back the px unit width.

**Comment by djhvscf** [comment]
Yes, the problem is still there.. let me ckeck it

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/691 and this: https://jsfiddle.net/8eh2t597/6/

**Comment by alvin0618** [comment]
Hi djhvsccf,
Thank you for the response.
May I know the solution you gave, it will be integrated into the next version?

**Comment by djhvscf** [comment]
It will be intgrated into the next official release.. for now it is into the development file

**Comment by alvin0618** [comment]
alright, tqtq
