### ISSUE TITLE
Error in onClickCell dcoumentation

### ISSUE THREAD

**Issue by AluminumPirate** [wenzhixin/bootstrap-table#6724]
### Description

https://bootstrap-table.com/docs/api/events/#onclickcell

Found and error In above event documentation.
Documentation specifies that the parameters are: field, value, row, $element
When in fact it is missing a parameter (the first one):   $event, fieldName, value, rowData, $tdElement

**Comment by UtechtDustin** [comment]
Hey, thanks for creating the issue.
I guess you listen to the event like the following example, right ?
```
$('#table').on('event-name.bs.table', function (e, arg1, arg2, ...) {
  // ...
})
```

If you use the `.on` method, the first parameter is always the event (that is jquery specific).   
But if you define the event method within the table initialisation the event param is gone.

```

$('#table').bootstrapTable({
  onEventName: function (arg1, arg2, ...) {
    // ...
  }
})
```

The documented parameters are without the event parameter.   
On the events documentation page on the first section it's also recognizable.

**Comment by AluminumPirate** [comment]
I believe you are correct 👍 
I used the '.on' method.

Thank you for pointing it out!
