### ISSUE TITLE
Use different classes for `<th>` and `<td>` elements?

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6730]
### Bootstraptable version(s) affected

1.21.4

### Description

I would like to specify different classes for the `th` header and `td` row elements.

When having:

```
<th data-field="price" data-class="numbers">Price</th>
```

the `numbers` class is used in both the `th` and `td` elements.

### Example(s)

https://live.bootstrap-table.com/code/marceloverdijk/14911

### Possible Solutions

Use `<th class="numbers">` only for header.
And `<th data-class="numbers">` to pass to `<td>` element.

Introduce new attribute?

### Additional Context

.

**Comment by wenzhixin** [comment]
What case do you want to use it for? Currently not supported, but I think different effects can be achieved through css selectors, such as:
```html
<style>
th.success {
  background: blue !important;
  color: white;
}
td.success {
  background: green !important;
  color: white;
}
</style>
```

https://live.bootstrap-table.com/code/wenzhixin/14912

**Comment by marceloverdijk** [comment]
Indeed, this is how I solved it now using typical css selectors.

My use case is I have a `.numbers` class that I wanted to apply to column values containing numbers.
In theory that can be `<th>`s and `<td>`s but in general it are only `<td>`s.

This `.numbers` class has `font-variant-numeric: tabular-nums;` to show numbers a fixed width, which is quite useful in tabular data.
