### ISSUE TITLE
Filter control and pagination server side bug

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#6735]
### Bootstraptable version(s) affected

1.21.4

### Description

When pagination server side is enabled with filter control, the searching text diseapear after searching

### Example(s)

https://live.bootstrap-table.com/code/sdespont/14933

![screen-recording-2023-04-06-15_3A02 webm](https://user-images.githubusercontent.com/646632/230387170-4d2c0092-5fb2-4f25-a614-046b0385171a.gif)

**Comment by sdespont** [comment]
@djhvscf I can help if you give me a hint where to search this bug

**Comment by sdespont** [comment]
After trying and looking at the code, I am not able to find where and why the searching text diseapears after searching 😪

**Comment by sdespont** [comment]
After some tests, I can confirm that the problem doesn't appear if parameters `data-icon-size="xxx"` and `data-height="xxx"` are removed.

https://live.bootstrap-table.com/code/sdespont/15534

**Comment by UtechtDustin** [comment]
`data-icon-size` should not be the cause of this issue.  
The issue could be caused by the `height` option.  
If the`height` option is used, we use a other tabler header.   
After an search the table will be rebuilded,  i guess the value will be set to the wrong header ?

**Comment by sdespont** [comment]
@UtechtDustin `data-icon-size` is probably setting the height of the header, so your point make sense. Could you share the link to the code where you find out that the table is rebuilded please?

**Comment by UtechtDustin** [comment]
`data-icon-size` just change the classes for the icons as described in the [documentation](https://bootstrap-table.com/docs/api/table-options/#iconsize).

There is no specific link, the bootstrap-table rebuild for every action (page change, search, etc.).

**Comment by sdespont** [comment]
@UtechtDustin I understand that you are doubtful but have a look at the code :

- Not working : https://live.bootstrap-table.com/code/sdespont/15561
- Working : https://live.bootstrap-table.com/code/sdespont/15562

**Comment by UtechtDustin** [comment]
That is strange, it should only decide which css class should be used i guess.
Let me check that, maybe i find something quickly.

**Comment by UtechtDustin** [comment]
Found it!  The element selector for the input was broken because of the css class for the small icons.  
To be honest the method which should figure outh the selector for the input was quite impractical.
