### ISSUE TITLE
count rowspan from ajax response

### ISSUE THREAD

**Issue by h1realneo** [wenzhixin/bootstrap-table#6741]
### Description

I kind of read all the documentation, but I didn’t find a way to specify rowspan for each cell when the response comes from the server, as I understand it, at least the columnAttributes method is needed

to create something like https://live.bootstrap-table.com/code/h1realneo/14975 with ajax response

_No response_

**Comment by wenzhixin** [comment]
An online example: https://live.bootstrap-table.com/code/wenzhixin/15807
