### ISSUE TITLE
X-Editable is not working as expected.

### ISSUE THREAD

**Issue by prasadchitti** [wenzhixin/bootstrap-table#6744]
### Bootstraptable version(s) affected

4

### Description

X-editable plugin is not working and not providing an option to edit the table inside bootstrap. on click of row does nothing.
Please help me achieve the solution for this. 

### Example(s)

https://examples.bootstrap-table.com/index.html#extensions/editable.html

**Comment by UtechtDustin** [comment]
As you can see on the [x-editable homepage](https://vitalets.github.io/x-editable/) the plugin online works for BT 2 and 3.
