### ISSUE TITLE
Options, Methods without jQuery

### ISSUE THREAD

**Issue by vzlabiom** [wenzhixin/bootstrap-table#6747]
### Description

All methods defned for JQuery object, i.e. it must be used $(#table).bootstrapTable('method', parameter).
Its it possible to exclude JQuery and use merhods for NodeElement (i.e. element which is defined with document.querySelector(...)).

**Comment by marceloverdijk** [comment]
Related to https://github.com/wenzhixin/bootstrap-table/issues/6717
I think more people are interested in this.

**Comment by UtechtDustin** [comment]
Duplicate of #4796   
We also want to remove jQuery, but other issues have a higher priority.   
Pull requests are welcome :)
