### ISSUE TITLE
Exclude column from printing

### ISSUE THREAD

**Issue by vzlabiom** [wenzhixin/bootstrap-table#6752]
### Description

How to exclude column from printing (for example, added check-box column).
Same question for export (pdf, excel)

**Comment by UtechtDustin** [comment]
You can hide the columns with the following column options:
printing: [printIgnore](https://bootstrap-table.com/docs/extensions/print/#printignore)
export: [forceHide](https://bootstrap-table.com/docs/extensions/export/#forcehide)
