### ISSUE TITLE
filter control: event when initialized

### ISSUE THREAD

**Issue by oliver681** [wenzhixin/bootstrap-table#6756]
### Description

It would be nice to have an event that fires when the filters are completely initialized. 

Concrete problem that I'm trying to solve:  I need to initialize bootstrap popovers inside table cells after the filters are initialized because I'm running into some problems if they are initialized before. For purposes like that such an event would be helpful.

**Comment by UtechtDustin** [comment]
The [onPostHeader](https://bootstrap-table.com/docs/api/events/#onpostheader) will be triggered as soon the header is rendered and available in the DOM.   
So this event should be the way to go for you.
