### ISSUE TITLE
new feature request: preserve search value cookie (?)

### ISSUE THREAD

**Issue by ang3lx** [wenzhixin/bootstrap-table#676]
Example:
I write "pippo" into search box, click on one result and leave page with table
if I back on table page, input text is already filled with "pippo" and data filtered

is possible?

**Comment by wenzhixin** [comment]
Need to improve the cookie extension: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/cookie
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html

**Comment by djhvscf** [comment]
Ref to: https://github.com/wenzhixin/bootstrap-table/pull/677

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html
