### ISSUE TITLE
Maximum call stack size exceeded  

### ISSUE THREAD

**Issue by trzhou** [wenzhixin/bootstrap-table#6767]
### Bootstraptable version(s) affected

1.21.4

### Description

Error Message: 
caught (in promise) RangeError: Maximum call stack size exceeded
![捕捉-1](https://user-images.githubusercontent.com/3705816/234753182-f2bcdff3-1418-4b68-9170-e029746ff918.jpg)

Code at:
extend: function() { 
 for (var t = this, i = arguments.length, n = new Array(i), o = 0; o < i; o++)
                n[o] = arguments[o];
      ......
  }
![捕捉-2](https://user-images.githubusercontent.com/3705816/234753241-b47daaf6-68ad-4e1e-9743-9ba958f7267d.jpg)

**Comment by jonm01** [comment]
I have the same issue when I reinitialize the table after I destroy

$table.bootstrapTable("destroy");
$table.bootstrapTable();

**Comment by jonm01** [comment]
I have the same issue when I reinitialize the table after I destroy (version 1.21.4)

$table.bootstrapTable("destroy");
$table.bootstrapTable();

**Comment by tbatista** [comment]
I have the same issue when I reinitialize the table after a destroy (version 1.21.4 and 1.21.3). It works with version 1.21.2

**Comment by UtechtDustin** [comment]
I can't reproduce it @tbatista @subject-de1ta @jonm01 @trzhou.  
Can someone please provide us an example using our [editor](https://live.bootstrap-table.com/) ?  
Destroy and reinitialize the table works fine for me.
Example: https://live.bootstrap-table.com/code/UtechtDustin/15553

**Comment by trzhou** [comment]
The bug occurred when update Bootstrap-Table in my project from 1.21.2  to 1.21.4 or 1.22.0.  Version 1.21.2 works good.  Jquery version is 3.7.0. Bootstrap version is 5.1.0.

**Comment by tbatista** [comment]
After caling $(table).bootstrapTable("destroy") the jquery element $(table) has these jQuery3600... array items that point to the table. As we try to clone the table element we get an endless loop. 
![image](https://github.com/wenzhixin/bootstrap-table/assets/10884724/ae669d17-f9fb-4035-a95e-2b5b5f1e0268)
![image](https://github.com/wenzhixin/bootstrap-table/assets/10884724/2830d7d9-fafe-45b5-88da-024132a1726b)
As a workaround setting these jquery array items to undefined fixed the endless loop:
table[Object.keys(fkTable)[0]] = undefined;
table[Object.keys(fkTable)[1]] = undefined;
table[Object.keys(fkTable)[2]] = undefined;
table[Object.keys(fkTable)[3]] = undefined;
