### ISSUE TITLE
Filter Control: MessageChannel is not a constructor

### ISSUE THREAD

**Issue by DarthSonic** [wenzhixin/bootstrap-table#6768]
### Bootstraptable version(s) affected

1.21.4

### Description

When trying to use filter-control, it throws exception "MessageChannel is not a constructor" on page load.

### Example(s)

```
<table id="leads-table" data-toggle="table" data-classes="cm-pos-table table" data-locale="de" data-search="true" data-silent-sort="false" data-filter-control="true">
<thead>
<th class="classification text-center" data-field="classification" data-searchable="true" data-filter-control="select">
```

**Comment by UtechtDustin** [comment]
We don't use the `MessageChannel` Api for the bootstrap-table.   
You're example is also broken, please provide us an example using our [live editor](https://live.bootstrap-table.com/).

**Comment by wenzhixin** [comment]
Close this issue because there is no response in 7 days. If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!
