### ISSUE TITLE
Footer information

### ISSUE THREAD

**Issue by atpsolucoes** [wenzhixin/bootstrap-table#6777]
### Description

Hello friends.
How can I grab custom information from JSON server response
and make it available in the footer.

### Example(s)

![Captura de tela 2023-05-04 104256](https://user-images.githubusercontent.com/88142595/236224198-e4ede630-45b6-4555-bd08-7cbeb6adbee5.png)

This is the JSON return.
I need to take the values ​​that are circled and put them in the footer

**Comment by UtechtDustin** [comment]
I guess you are searching for the [footerField](https://bootstrap-table.com/docs/api/table-options/#footerfield) option which also you to define the footer values.

**Comment by wenzhixin** [comment]
You can use the `responseHandler` and `footerField` to solve the problem.
