### ISSUE TITLE
Switchable columns rendered in custom dropdown element?

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6780]
### Description

I have a table with a custom sortby, custom search input and custom view as can be seen in below screenshot.

There is also a custom settings icon with a dropdown to enable filters and reset them.
Now I want to include in that settings dropdown the ability to (`switchable`) show/hide particular columns.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/197004/236610360-ec638240-b174-4072-bfd3-ceaaaf694e29.png">

Would it be possible with a custom extension to use `data-switchable` and render the actual switch options in that existing dropdown?

### Example(s)

https://live.bootstrap-table.com/code/marceloverdijk/15194

**Comment by marceloverdijk** [comment]
I was able to solve this by overriding some BT constants and html.

**Comment by typo3ua** [comment]
Hi! @marceloverdijk can you provide example [here](https://live.bootstrap-table.com/) ... please?
