### ISSUE TITLE
关于Editable扩展的问题

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#679]
默认在 TH 中 data-editable="true" 可以实现编辑功能
但如果我想实现自定义的poup或selector的样式，是不是就必须使用javascript 创建 boostrap-table 的每个列，在javascript中去定义
还是可以通过 TH 中 data-editable="true" 添加 tag 就可以实现一个自动以的popup编辑样式

**Comment by wenzhixin** [comment]
是的，现在不支持使用 tag，只能用 js

**Comment by wenzhixin** [comment]
Consider to support via data attributes.

**Comment by liuwenfeng554** [comment]
你是如何实现列单元格编辑的，为何在api中没有data-editable="true" 这个属性呢？你使用的版本是最新版吗？

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/extensions/ @liuwenfeng554

**Comment by liuwenfeng554** [comment]
谢谢
