### ISSUE TITLE
Bootstrap table initialization crashes if table element $.data() contain a recursive object

### ISSUE THREAD

**Issue by kkozlik** [wenzhixin/bootstrap-table#6797]
### Bootstraptable version(s) affected

1.21.3, 1.21.4

### Description

When I assign an object with a recursion to the `.data()` of `<table>` element before bootstrap table is initialized, the initialization crashes with: `Uncaught RangeError: Maximum call stack size exceeded` error message in the browser console:

![image](https://github.com/wenzhixin/bootstrap-table/assets/1277199/116aeb3e-677a-432c-8b12-f7ade8b94022)

In my case that was because of another jQuery plugin (that use the recursion) used on the `<table>` element. 

### Example(s)

https://live.bootstrap-table.com/code/kkozlik/15287

When you comment the line 20, it will work fine.
![image](https://github.com/wenzhixin/bootstrap-table/assets/1277199/f052a0db-e6c3-4156-8566-887bf2feec29)

### Possible Solutions

The culprit seems to be a deep copy of options used on table initialization which has been added in 1.21.3:

https://github.com/wenzhixin/bootstrap-table/blob/9a93bd8d35de8d6dea43ace4de48413ded643068/src/bootstrap-table.js#L3438

particularly the the fourth argument `$(el).data()`. I do not know reasons behind adding this line, but a solution could be remove this argument from the `Utils.extend()`, or call that function without the deep copy. I mean something like:

```js
let options = Utils.extend(true, {}, BootstrapTable.DEFAULTS);
options = Utils.extend(false, options, $(el).data(), typeof option === 'object' && option);
```

Another, maybe better but probably more difficult solution would be improve the `Utils.extend()` function to detect the recursion and deal with it.

**Comment by kkozlik** [comment]
As looking more to it, 1.21.2 is probably also affected. It's because of this commit: https://github.com/wenzhixin/bootstrap-table/commit/3000dc267562135aef7a123223b5f45c609e87d6

**Comment by UtechtDustin** [comment]
The fourth option is needed because you can configure the table using data attributes (you also did it in you're example using `data-field`).      
As you already found the commit, the commit message says the reason why we need the deep copy.   
More infos in the [pull request)(https://github.com/wenzhixin/bootstrap-table/pull/6448) and/or in the related [issue](https://github.com/wenzhixin/bootstrap-table/issues/6438).

I'm more intrested why do you need an recurisve object which has no end...It will always fail.   
Please explain us the usecase.

**Comment by kkozlik** [comment]
> The fourth option is needed because you can configure the table using data attributes (you also did it in you're example using `data-field`). As you already found the commit, the commit message says the reason why we need the deep copy. More infos in the [pull request)(https://github.com/[/pull/6448](https://github.com/wenzhixin/bootstrap-table/pull/6448)) and/or in the related [issue](https://github.com/wenzhixin/bootstrap-table/issues/6438).
> 

I understand the need of deep copy for `BootstrapTable.DEFAULTS`. But is it needed also for the `$(el).data()`? I do not think so. Shallow copy shall be enough for data attributes, is not it?

> I'm more intrested why do you need an recurisve object which has no end...It will always fail. Please explain us the usecase.

As I stated in the issue, in my case the recursion is used in third party (private) jQuery extension which is used on the `<table>` element too and which put itself to a data attribute. Exactly same way as bootsrap table do it here: https://github.com/wenzhixin/bootstrap-table/blob/9a93bd8d35de8d6dea43ace4de48413ded643068/src/bootstrap-table.js#L3442


That extension is more complicated, but does the details matter here? I think it use multiple objects which have cross references between them. Something like:
```
function A(){
  this.b = <reference to B()>
}
function B(){
  this.a = <reference to A()>
}
```

Well in case the deep copy is for whatever reason needed also for the data attributes, cannot it be limited only to those attributes belonging to bootstrap table and ignore the others?

**Comment by wenzhixin** [comment]
Fixed in develop.
