### ISSUE TITLE
Editable extension - Empty placeholder

### ISSUE THREAD

**Issue by vicentor** [wenzhixin/bootstrap-table#680]
I apologize if I should be posting this elsewhere, please let me know where if it's not the proper area.

It seems like there is no way to affect the Editable extension options when it's integrated directly unto the Bootstrap Table from wenzhixin.

In fact, we'd like to simply show "Vide" instead of "Empty" as the emptytext, but anywhere we set the option, it's ignored and the Bootstrap Table locale file doesn't include this expression since it's an external library.

We tried `data-emptytext` on the `table` or `th` or `tr` or `td` without success. We tried in the JavaScript initialization too.

Can anyone show us a working exemple or tell us how it's supposed to be done? If then we still cannot get it to work, we'll provide a JSFiddle.

**Comment by djhvscf** [comment]
I think that feature is not supported @vicentor

**Comment by farwayer** [comment]
Small hack. Include it **after** `bootstrap-table.js` but **before** `bootstrap-table-editable.js`:
```javascript
<script type="text/javascript">
  (function() {
      var BootstrapTable = $.fn.bootstrapTable.Constructor;
      var _initTable = BootstrapTable.prototype.initTable;
      BootstrapTable.prototype.initTable = function () {
        _initTable.apply(this, Array.prototype.slice.apply(arguments));
        this.options.columns[YOU_EDITABLE_COLUMN_INDEX].editable = {
          emptytext: "Vide"
        };
      }
    })();
</script>
```
You can set any x-editable options http://vitalets.github.io/x-editable/docs.html#editable

**Comment by djhvscf** [comment]
Thanks @farwayer

**Comment by wenzhixin** [comment]
You can set `editable` column option to do this via JavaScript.
