### ISSUE TITLE
Calucated fields

### ISSUE THREAD

**Issue by stokito** [wenzhixin/bootstrap-table#6802]
### Description

I have a column that should be calculated from other columns like:
* amount
* price
* total = amount * price

Right now I was able to do this with the `data-response-handler`:

```js
function responseHandler(reportData) {
    for (let reportLine of reportData.rows) {
        if (reportLine.Amount && reportLine.Price) {
            reportLine.Total = reportLine.Amount * reportLine.Price
        }
    }
}
```

This looks for me like a hack and another problem is that I also want to use the `data-response-handler` to parse CSV e.g. I need kind of two response handlers: one generic from #6105 to parse SCV and another one to calculate fields.

Is it possible to make some separate data attribute like `data-response-calculate` for calculable columns?

**Comment by UtechtDustin** [comment]
I guess you are searching for the [formatter](https://bootstrap-table.com/docs/api/column-options/#formatter) column option.

**Comment by wenzhixin** [comment]
Maybe we can create a feature that allows us to share commonly used formatter or code snippets.

**Comment by wenzhixin** [comment]
@stokito https://github.com/wenzhixin/bootstrap-table-examples/tree/develop/utils/natural-sorting any PR is welcome.

**Comment by wenzhixin** [comment]
I will close this issue because it's not a feature.
