### ISSUE TITLE
Sorting not working well

### ISSUE THREAD

**Issue by SuperBoy17** [wenzhixin/bootstrap-table#6809]
### Bootstraptable version(s) affected

1.21.1

### Description

Hi there, I notice that the sorting not working on some certain column which sort by text, date and number, may I know which part of JS need to be checked? Thanks
![Capture1](https://github.com/wenzhixin/bootstrap-table/assets/112933534/bae8aeb1-99bf-4cc2-87f4-df5370b3bd9a)
![Capture](https://github.com/wenzhixin/bootstrap-table/assets/112933534/9d559555-12c8-469e-af0b-cdb8f496ea9e)

### Additional Context

You may reply as Chinese also, no problem for understanding

**Comment by wenzhixin** [comment]
You can use the sorter: https://bootstrap-table.com/docs/api/column-options/#sorter column option to solve your problem.
Example: https://live.bootstrap-table.com/example/column-options/sorter.html

**Comment by SuperBoy17** [comment]
Thank you for reply, but what if im using vueJS? It's also working?

**Comment by wenzhixin** [comment]
Yes, add `sorter` in column option, vue example: https://live.bootstrap-table.com/example/welcomes/vue-component.html

**Comment by SuperBoy17** [comment]
Hello again, regarding last time already guided me how to solve this issue, maybe I misguided which sorting I was on trouble, what I'm using is this sorting button, sorry and please help to check again, much appreciated. 

![image](https://github.com/wenzhixin/bootstrap-table/assets/112933534/75f33b68-8f4c-486b-9cd8-85f59387ab84)

**Comment by SuperBoy17** [comment]
One more problem, if I switched to other page, the sorting not sorted in the same page, it will put in data from other page.
