### ISSUE TITLE
Using the export plugin with a bootstrap table, download type is defaulting the the default values instead of selected type

### ISSUE THREAD

**Issue by nvcastelli** [wenzhixin/bootstrap-table#6818]
### Bootstraptable version(s) affected

1.20.2

### Description

I'm using the table Export [plugin](https://bootstrap-table.com/docs/extensions/export/) with a bootstrap table and am trying to figure out why only links to the default format values in the plugin are shown, and why it's showing links at all.

Attached is an image of what I'm seeing after trying to export the table as a JSON.
![image](https://github.com/wenzhixin/bootstrap-table/assets/3475905/2049b100-1147-412b-908b-1e1958172199)

When selecting the download type the buttons appear on the bottom of the table instead of just downloading the type selected in the dropdown. I'm only able to download using those buttons on the bottom of the table, is that intentional?

At first I thought it might be an issue with the export plugin but I wanted to reach out here to see if it was a function of the bootstrap table or maybe how I've defined some of the options.

Please let me know if there's any other information I can provide.

### Expected Functionality
After selecting the download icon in the upper right hand side of the table a dropdown list of export types should appear. After selecting an export type from the dropdown the table is downloaded in that format.

### Observed Functionality
After selecting the export type to download from the download dropdown, three buttons appear at the bottom of the table, one for each of the default format defined in the tableexport plugin. Selecting any of these buttons downloads the table in the format specified for each button. Additionally, if the user selects a export type from the download dropdown again, the three buttons are added again, this can be done any number of times.

### Additional Context

Here is a ticket I had created against the export plugin repository.

https://github.com/hhurz/tableExport.jquery.plugin/issues/366

**Comment by UtechtDustin** [comment]
Seems working fine like you're expected functionality.
Example: https://live.bootstrap-table.com/code/UtechtDustin/15550

It seems that is an issue of you're setup, we don't add buttons for exporting stuff.
We only use the dropdown, also i can't even find the string "export to" in the source code.
Please provide us an example using our [live editor](https://live.bootstrap-table.com/).

**Comment by nvcastelli** [comment]
You are correct, the issue was with how I was referencing the export plugin in my code. I was able to fix and verify it works. Thank you for your comment.
