### ISSUE TITLE
Using updateRow with Sorting

### ISSUE THREAD

**Issue by rfossella** [wenzhixin/bootstrap-table#682]
I have a table with 200 rows __sorted by time__.  I use **updateRow** to update contents of row, including time.  The table does not refresh the sort.  Do I need to manually reset the view after an updateRow?

```
  var tblData = $('#mytable').bootstrapTable('getData');
  row =  _.find(tblData, function(obj){ return obj.name == name});
   if (row == null)
        return;
    index = _.indexOf(tblData,row);
    $('#myTable').bootstrapTable("updateRow", {index:index, row: {state:state, last_update: time}})
```

Thank you.

**Comment by djhvscf** [comment]
Can you provide a fiddle, please? @rfossella

**Comment by djhvscf** [comment]
What about your table configuration?

**Comment by rfossella** [comment]
Hi.  A bit confused.  I did a pull to get code with lastest fixes.  *bootstrap-table.js* in SRC and DIST folders are different although both same date?  The DIST is the one with fixes?
Thanks.

**Comment by djhvscf** [comment]
No, for now you have to use the src code until the next release

**Comment by rfossella** [comment]
Perfect.  thanks for clarifying
