### ISSUE TITLE
showButtonText only on large screens

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6822]
### Description

Would it be possible to show the button texts (`showButtonText=true`) only on large screens?

The button text in BT is most of the time determined like below; in this for the custom view button:

```
  toggleCustomView () {
    this.customViewDefaultView = !this.customViewDefaultView

    const icon = this.options.showButtonIcons ? this.customViewDefaultView ? this.options.icons.customViewOn : this.options.icons.customViewOff : ''
    const text = this.options.showButtonText ? this.customViewDefaultView ? this.options.formatToggleCustomViewOff() : this.options.formatToggleCustomViewOn() : ''

    this.$toolbar.find('button[name="customView"]')
      .html(`${Utils.sprintf(this.constants.html.icon, this.options.iconsPrefix, icon)} ${text}`)
      .attr('aria-label', text)
      .attr('title', text)

    this.initBody()
    this.trigger('toggle-custom-view', this.customViewDefaultView)
  }
```

One could e.g. do something like:

```
$.extend($.fn.bootstrapTable.defaults, {
  formatToggleCustomViewOn: () => '<span class="d-none d-lg-block">Grid view</span>',
})
```

but the problem is that text is aluse for the `title` attribute which gives issues unfortunately.

I see no workaround unfortunately...

Use case is to only show the button text on large devices as there is not enough space on small devices for the text.

**Comment by marceloverdijk** [comment]
For now I went for icons only, so no big issue.
But maybe good to track and put info here for other users which are looking for the same.

**Comment by UtechtDustin** [comment]
I'm not sure if this is an edge case and if we should support that.   
You can already define the custom buttons with you're own html, so you could use that.
What do you think about @wenzhixin @djhvscf ?
