### ISSUE TITLE
How to hide showColumns toolbar button when customView active

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6828]
### Description

I would like to show the showColumns toolbar button only when the data is presented as a standard table.

When custom view is active (displaying data as a grid) I would like to hide the showColumn toolbar button as it does not make not sense.

Would that be possible?

### Example(s)

https://live.bootstrap-table.com/code/marceloverdijk/15589

<img width="861" alt="image" src="https://github.com/wenzhixin/bootstrap-table/assets/197004/1f299d0e-637c-4434-addb-c259db944f7e">

**Comment by UtechtDustin** [comment]
Listen to events and enable/disable the showColumns option :)

**Comment by marceloverdijk** [comment]
:) yes make sense. I will try this weekend and will post solution here for reference.

**Comment by marceloverdijk** [comment]
@UtechtDustin I was trying but I wonder how I can access the button from the event...

https://live.bootstrap-table.com/code/marceloverdijk/15619

```
      onToggleCustomView: function(state) {
        $columnsButton = // how to access the button?
        if (state) {
          $columnsButton.hide()
        } else {
          $columnsButton.show()
        }
      },
```

I was trying to get the toolbar like:

`const $toolbar = $('#table').$container.find('.fixed-table-toolbar')`

but `$container` is not public.
How can I access the button with the table instance? Probably I'm just missing something obvious...

**Comment by UtechtDustin** [comment]
I meant with the [refreshOptions](https://bootstrap-table.com/docs/api/methods/#refreshoptions) method, not hiding/showing manually :)
Example: https://live.bootstrap-table.com/code/UtechtDustin/15620

**Comment by marceloverdijk** [comment]
Oh I see.
But I want to hide/show that toolbar button (showColumns) when one of the other toolbar buttons (customView) is clicked?

I've updated: https://live.bootstrap-table.com/code/marceloverdijk/15624 and now have:

```
      onToggleCustomView: function(state) {
        $('#table').bootstrapTable('refreshOptions', {
        	showColumns: !state
	      })
      },
```

but calling `refreshOptions` in that event causes the custom view not to work anymore unfortunately.

**Comment by UtechtDustin** [comment]
Oh i guess i know why...
Currently the bootstrap-table will be rendered agian on every action (e.g. update Options) which means the table will be rendered agian and shows the default view...
Optimally the table should be rendered again, again and again, but it's to hard right now to fix/improve that.


So i guess you have to show/hide it manually using a fixed selector (I don't think we have an parameter or something like that).
Example: https://live.bootstrap-table.com/code/UtechtDustin/15625

**Comment by marceloverdijk** [comment]
Thx @UtechtDustin this is what I'm looking for.
Will try this tomorrow when back behind my computer 👍

**Comment by marceloverdijk** [comment]
And for others looking for a fully integrated implementation by extending `BootstapTable` class and overriding `toggleCustomView` this could be useful:

```
$.BootstrapTable = class extends $.BootstrapTable {

  toggleCustomView() {

    super.toggleCustomView() // call super to actually toggle the custom view

    // and now hide/show the Columns button
    if (this.options.showColumns) {
      const $columnsButton = this.$toolbar.find('button[title="Columns"]')
      if ($columnsButton) {
        this.customViewDefaultView ? $columnsButton.hide() : $columnsButton.show()
      }
    }
  }

}
```
