### ISSUE TITLE
Duplicated ID if I use 2 different tables in the same web

### ISSUE THREAD

**Issue by francogp** [wenzhixin/bootstrap-table#6830]
### Bootstraptable version(s) affected

1.21.4

### Description

If I call 2 different tables, I get a lot of warning and errors from EDGE browser, for duplicated ID

### Example(s)

![image](https://github.com/wenzhixin/bootstrap-table/assets/2739706/4242ee15-36db-48a2-be92-fadd430be336)

### Possible Solutions

every input and button should start with the table ID in their ID name

**Comment by UtechtDustin** [comment]
Please provide us an example using our [live editor](https://live.bootstrap-table.com/).

**Comment by francogp** [comment]
For some reason, I use the same code in my end and the ID collision warning are all present. In this demo example, the collision IS PRESENT (you can search button id="add" and button id="delete" in both table multisort button), but it does not appear as a warning (don't know why). In the demo only appear the warnings and errors in this screenshot.
https://live.bootstrap-table.com/code/francogp/15608
![image](https://github.com/wenzhixin/bootstrap-table/assets/2739706/29ada21a-9ecf-4569-a807-80a90da2b3c0)

**Comment by UtechtDustin** [comment]
Is the multisort extension the only extension with duplicated Id's ?
Do you also get errors if the multisort extension is disabled ?

**Comment by UtechtDustin** [comment]
Thank you for the confirmation.
