### ISSUE TITLE
Cannot render two tables on one page

### ISSUE THREAD

**Issue by traffic-go** [wenzhixin/bootstrap-table#6831]
### Bootstraptable version(s) affected

1.21.4

### Description

https://live.bootstrap-table.com/code/traffic-go/15611
I cannot render two tables simultaneously on one page. Even if they have different IDs, they cannot be displayed simultaneously.

**Comment by UtechtDustin** [comment]
You're table is invalid, you don't defined columns (thead -> tr -> th).
Working example: https://live.bootstrap-table.com/code/UtechtDustin/15614
