### ISSUE TITLE
Remember reordered columns

### ISSUE THREAD

**Issue by nl-savills-insightdata** [wenzhixin/bootstrap-table#6833]
### Description

Dear @wenzhixin,
First of all, Huge compliments to you regarding this project.
I'm a big fan of Bootstrap Table. It's amazing work.

I have a usecase where I want to use the collumn reorder extension to work with the cookies extension. 
The goal is that if a user reorders collumns, it remembers the order using the cookies extension.

Unfortunately I cannot get it to work. Is this possible, and would you be able to point me in the right direction?

**Comment by wenzhixin** [comment]
@nl-savills-insightdata 
The cookie extension supports saving the reordered columns.
https://live.bootstrap-table.com/code/wenzhixin/15805
