### ISSUE TITLE
设定高度时，经常出错，特别是隐藏层加载时。(set height, error occurred. hidden layer)

### ISSUE THREAD

**Issue by YSZeng** [wenzhixin/bootstrap-table#6834]
### Bootstraptable version(s) affected

1.21.4

### Description

设定高度时，经常出错，特别是隐藏标签页加载时。(以前版本出错，下载最新版本，仍然错误)
set height, error occurred.(After downloading the latest version, the error still occurs.)

### Example(s)

正常情况(normal)：
![图片](https://github.com/wenzhixin/bootstrap-table/assets/18522726/639c044c-e9e5-4d7f-990b-af1107cc3fd0)
异常情况1(error 1)：
![图片](https://github.com/wenzhixin/bootstrap-table/assets/18522726/b1542f79-c22f-42b8-a47b-e0a4e744509d)
异常情况2(error 2)：
![图片](https://github.com/wenzhixin/bootstrap-table/assets/18522726/b901d9f4-8cc3-493b-b9ad-b28af6b990e8)

**Comment by YSZeng** [comment]
我经过尝试，设置 .fixed-table-container  {padding-bottom: 37px } 可以解决 异常情况1(error 1)。

**Comment by wenzhixin** [comment]
当你的 table 显示时，可以调用（或延迟） `resetView` 方法来解决问题。
希望能帮助你，假如还有问题的话再 reopen 该问题。
