### ISSUE TITLE
Thead and tbody column width mismatch

### ISSUE THREAD

**Issue by iruy** [wenzhixin/bootstrap-table#684]
After loading the table, if I delete some random rows (mainly those with longer text), the width of columns in header is different from the width of body columns, resulting in non-aligned columns vertically
![picture0001](https://cloud.githubusercontent.com/assets/8875681/6980274/68181574-d9ef-11e4-8538-b4ded2e9671d.png)

**Comment by djhvscf** [comment]
If you are using the data-height option you have to call the resetView method to fix that

**Comment by iruy** [comment]
Where and when I should call resetView?

**Comment by wenzhixin** [comment]
Maybe you can provide a jsFiddle @iruy ? I our example: http://issues.wenzhixin.net.cn/bootstrap-table/, after delete selected rows the header is OK.

**Comment by iruy** [comment]
@wenzhixin I think that the error is given when you have a long text in cell.
Here you should be able to see what I get. https://jsfiddle.net/ps6tucqu/3/   As you can see, columns don't match already at begin, then, if you remove the first row, it gets fixed, but if you remove again the next first row.....column mismatch.
I noticed that, if I remove the data-height attribute, everything works as expected...

**Comment by djhvscf** [comment]
Yes, @wenzhixin I think there is a bug with data-height because if you change the size of your browser when you set the data-height the columns mismatch..

**Comment by wenzhixin** [comment]
I guess you need to use `remove` method: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/remove.html instead of `.fadeOut(500)`, because when you remove it by this way, the table data is not remove.

**Comment by iruy** [comment]
@wenzhixin if it is not removed, then the header shouldn't resize...
Anyway, I found another probable bug: when you delete almost all row, in order to make the scrolling bar disappear, the headers doesn't remove the small <th> at the end of thead row..

**Comment by wenzhixin** [comment]
Hi @iruy, the another probable bug what you said, I think I have fixed it: https://github.com/wenzhixin/bootstrap-table/commit/596b00fd48030978770cc816dbdfb4717bc18965. Something advice, use bootstrap methods instead of use jQuery methods to handle the table.

Close this issue.

**Comment by Juniornativa** [comment]
It didn't work to me. I had to remove data-height attribute.
Any idea? 
Thanks in advance!

**Comment by Juniornativa** [comment]
It didn't work to me. I'm with the latest version (1.8.1) and i still had to remove data-height attribute.
Any idea?
Thanks in advance!
