### ISSUE TITLE
data-show-columns button is appearing but nothing happens when I click on it

### ISSUE THREAD

**Issue by bsibul16** [wenzhixin/bootstrap-table#6843]
### Description

Hi, I have set data-show-columns="true" and the button appears above the top right corner of the table, but when I click on it nothing happens.

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by bsibul16** [comment]
https://live.bootstrap-table.com/code/bsibul16/15674

The button is working in the editor. Any ideas as to why it might not be working for me? I am using it in a Flask app, and have added the jquery script in my base.html page. This myteam page is an extension of that page.

**Comment by UtechtDustin** [comment]
Sorry we don't know you're setup, so it could be anything.
I guess a other javascript will interrupt it somehow.

Remove (comment out) any other javascript until it works (as you can see in the editor it works), then readd it part by part.
