### ISSUE TITLE
Bug Description: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by trzhou** [wenzhixin/bootstrap-table#6844]
### Bootstraptable version(s) affected

1.21.4, 1.22.0

### Description

The bug report at https://github.com/wenzhixin/bootstrap-table/issues/6767#issue-1686033945

The bug occurred when update Bootstrap-Table in my project from 1.21.2 to 1.21.4 or 1.22.0. Version 1.21.2 works great! I replaced all lower version files with higher version files. 

This error at

![image](https://github.com/wenzhixin/bootstrap-table/assets/3705816/189e1ece-b185-4100-9bdb-8308c457a09d)

In my project, jquery version is 3.7.0, Bootstrap version is 5.1.0.

**Comment by trzhou** [comment]
This error is caused by the incorrect  options set :
          toolbar: $('# toolbar')
the correct is :
         toolbar: '#toolbar'

Sorry!

**Comment by trzhou** [comment]
This error is caused by the incorrect options set :

> toolbar: $('#toolbar')

the correct is :

> toolbar: '#toolbar'

Sorry!

**Comment by wenzhixin** [comment]
Example: https://live.bootstrap-table.com/code/wenzhixin/15709

> Sorry!

I will close this issue.
