### ISSUE TITLE
Vuejs 3 error 

### ISSUE THREAD

**Issue by avber** [wenzhixin/bootstrap-table#6848]
### Bootstraptable version(s) affected

1.22.0

### Description

Hello,

There is a problem using the component with Vuejs 3

Thanks

### Example(s)

https://live.bootstrap-table.com/example/welcomes/vue-component.html

<script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.22.0/dist/bootstrap-table-vue.min.js"></script>

The table is not shown.

  /* template */
  var __vue_render__ = function () {
    var _vm = this;
    var _h = _vm.$createElement;
    var _c = _vm._self._c || _h;                 <---------             the error is here
    return _c("table")
  };

**Comment by UtechtDustin** [comment]
Vue3 is currently not supported, see #5915
