### ISSUE TITLE
Optional page details

### ISSUE THREAD

**Issue by brliujerry** [wenzhixin/bootstrap-table#685]
Is it possible to add an option to disable page details?

(e.g., don't add the below if the option is turned off)
```javascript
 html.push(
            '<div class="pull-' + this.options.paginationDetailHAlign + ' pagination-detail">',
            '<span class="pagination-info">',
            this.options.formatShowingRows(this.pageFrom, this.pageTo, this.options.totalRows),
            '</span>');
```

**Comment by djhvscf** [comment]
it is possible.. Any pull request is welcome.  @brliujerry

**Comment by dabros** [comment]
@brliujerry - an option for that would be quite simple to code, if you have a few minutes then making a pull request for it would be easy - just look at other options and how they are passed through, then affect the updatePagintion() or similar function with a conditional against it.

Alternatively, you could just use css for something like:

``` css
#my-container .pagination-detail{display:none;}
```

In the case of css, you would have to be careful its not a child of your table itself, but the fixed-table container added - but just use F12 and DOM inspector to find best selector for it.

Im with @djhvscf in that any pull request is welcome, so if you want to do that please do so, allows you option to request any number of other features too and helps create more active editing community : )

**Comment by wenzhixin** [comment]
Just like @brliujerry said, I think it is better to use css to disable the page details.

**Comment by linziguan** [comment]
应该还是需要提供一个控制 page details显示或隐藏的参数及方法。因为即使在同一个container下，也有部分显示，部分不显示的。

**Comment by linziguan** [comment]
在BootstrapTable.DEFAULTS 中增加showPaginationDetail:false,配置；
然后在
html.push(
            '<div class="pull-' + this.options.paginationDetailHAlign + ' pagination-detail '+(this.options.showPaginationDetail?'hide':'')+'">',
            '<span class="pagination-info">',
            this.options.formatShowingRows(this.pageFrom, this.pageTo, this.options.totalRows),
            '</span>');
中增加了(this.options.showPaginationDetail?'hide':'')判断。
