### ISSUE TITLE
iOS data-url fetching issue

### ISSUE THREAD

**Issue by Nevemoire** [wenzhixin/bootstrap-table#6851]
### Bootstraptable version(s) affected

1.22.0

### Description

When fetching info via data-url everything works fine on desktop and android (tested on online-resources like https://appetize.io/), but on iOS table is empty. Any fixes available?

iOS version: 16.3.1

### Example(s)

```html
<table
                  className="table"
                  data-toggle="table"
                  data-url="https://api.npoint.io/050b5bb12b615ed863c5"
                  data-pagination="true"
                  data-search="true"
                  data-search-selector="#search"
                >
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Nickname</th>
                      <th scope="col">Discord</th>
                      <th scope="col">Winline</th>
                      <th scope="col">Participation</th>
                    </tr>
                  </thead>
                </table>
```

**Comment by wenzhixin** [comment]
Added an example with your code: https://live.bootstrap-table.com/code/wenzhixin/15707
Please help to check the result.

**Comment by Nevemoire** [comment]
> Added an example with your code: https://live.bootstrap-table.com/code/wenzhixin/15707 Please help to check the result.

Your example works fine. I asume problem is in that I add jquery/popper manually in react's index.html, otherwise adding via npm/yarn bootstrap-table doesn't work :/
Nevertheless, ty for ur reply!

**Comment by wenzhixin** [comment]
I will close this issue because it's not the plugin problem.
