### ISSUE TITLE
Determine if row is expanded

### ISSUE THREAD

**Issue by codethisio** [wenzhixin/bootstrap-table#6852]
### Description

Is there a way to reliably detect if a row is expanded via the API?
We are sending updates back to the UI and need to check if an expanded row's detail view should be updated.

**Comment by wenzhixin** [comment]
There is no API to do this. But you can use the event to save the expanded state, a working example: https://live.bootstrap-table.com/code/wenzhixin/15708

**Comment by codethisio** [comment]
> There is no API to do this. But you can use the event to save the expanded state, a working example: https://live.bootstrap-table.com/code/wenzhixin/15708

That is perfect. Thank you so much for your help!
