### ISSUE TITLE
Reorder Columns does not work

### ISSUE THREAD

**Issue by francogp** [wenzhixin/bootstrap-table#6857]
### Bootstraptable version(s) affected

1.22

### Description

I tried dragtable 2.0.12 (latest) and jquery-ui 1.10/1.11 and 1.12, but always crash with an internal error like the attached image 
![image](https://github.com/wenzhixin/bootstrap-table/assets/2739706/c0262396-8fe3-44c9-8d84-9c5af45b5380)

### Example(s)

the official link to the example does not work, with other errors, so I cannot provide an example:
https://live.bootstrap-table.com/example/extensions/reorder-columns.html

**Comment by wenzhixin** [comment]
It's a bug in the live editor. This example is working well: https://examples.bootstrap-table.com/#extensions/reorder-columns.html

**Comment by wenzhixin** [comment]
Fixed now: https://live.bootstrap-table.com/example/extensions/reorder-columns.html
Thanks for the feedback.
