### ISSUE TITLE
Function 'From DATA' works but 'From HTML' does not works, why?

### ISSUE THREAD

**Issue by reltua** [wenzhixin/bootstrap-table#6870]
### Description

I need your help understand why this function...
```
  $(function () {
     $('table#table').on('post-body.bs.table', function () {
       $('table#table').bootstrapTable('toggleDetailView', 0)
       $('tbody tr[data-index="0"]').addClass('active')
     })
  });
```
works well fro `From DATA`
does not work for `From HTML`

### Example(s)

From DATA...  https://live.bootstrap-table.com/code/reltua/15754 works well
From HTML... https://live.bootstrap-table.com/code/reltua/15755 does not work

thanks!

**Comment by wenzhixin** [comment]
It seems that the listening event is not taking effect, you can delete the `data-toggle="table"` and initialize it using the following method:

```js
  $(function () {
     $('table#table').on('post-body.bs.table', function () {
       $('table#table').bootstrapTable('toggleDetailView', 0)
       $('tbody tr[data-index="0"]').addClass('active')
     }).bootstrapTable()
  });
```

Working example: https://live.bootstrap-table.com/code/wenzhixin/15775

**Comment by wenzhixin** [comment]
I tested and found the example is working in the development branch: https://live.bootstrap-table.com/code/wenzhixin/15776.

**Comment by reltua** [comment]
thank you for reply...
so, that i just need to update your JS to latest version, is it?

**Comment by UtechtDustin** [comment]
There is no dist version for our develop branch, you have to clone the repository, checkout the develop branch and build the project.   
Or you wait until the next version is released.
