### ISSUE TITLE
Editable is not working

### ISSUE THREAD

**Issue by fabioschunig** [wenzhixin/bootstrap-table#6876]
### Bootstraptable version(s) affected

1.22

### Description

When the link of an editable value is clicked, just an empty white balloon is shown (example bellow).

![table-editable-bug](https://github.com/wenzhixin/bootstrap-table/assets/4001169/42bb7d6e-bb87-45a5-b5c7-a0dc341b573c)

### Example(s)

Examples page:

[Editable](https://examples.bootstrap-table.com/index.html#extensions/editable.html)

### Possible Solutions

Browser console shows the error:

```
Uncaught TypeError: this.tip() is null
    show https://cdn.jsdelivr.net/npm/x-editable@1.5.1/dist/bootstrap3-editable/js/bootstrap-editable.min.js:5
    show https://cdn.jsdelivr.net/npm/x-editable@1.5.1/dist/bootstrap3-editable/js/bootstrap-editable.min.js:5
    toggle https://cdn.jsdelivr.net/npm/x-editable@1.5.1/dist/bootstrap3-editable/js/bootstrap-editable.min.js:5
    init https://cdn.jsdelivr.net/npm/x-editable@1.5.1/dist/bootstrap3-editable/js/bootstrap-editable.min.js:5
    jQuery 3
        i
        dispatch
        handle
2 bootstrap-editable.min.js:5:11016
```

Maybe an incompatibility with [x-editable](https://github.com/vitalets/x-editable)?
The project seems abandoned.

### Additional Context

Tested with:
- MS Windows 11
- Firefox 114.0.2
- Google Chrome 114.0.5735.199

**Comment by wenzhixin** [comment]
You can check out the search results: https://github.com/wenzhixin/bootstrap-table/issues?q=editable+5+
