### ISSUE TITLE
large tables with many columns exceeds cookie max size

### ISSUE THREAD

**Issue by stampycode** [wenzhixin/bootstrap-table#6879]
### Bootstraptable version(s) affected

all

### Description

Max cookie size is 4096 bytes, having many table columns (or hidden columns in my case) causes the cookie to exceed 4096 bytes, so some columns are always displayed on page refresh.

### Possible Solutions

Suggest using multiple cookies for storing this data, or, since the data doesn't need to be sent to the server, there should be a window.localStorage option as alternative to using a cookie.

**Comment by stampycode** [comment]
cc [https://github.com/snipe/snipe-it/issues/13256#issuecomment-1622237152](https://github.com/snipe/snipe-it/issues/13256#issuecomment-1622237152)

**Comment by wenzhixin** [comment]
You can use the [`cookieStorage`](https://bootstrap-table.com/docs/extensions/cookie/#cookiestorage) option to set the storage to `localStorage`.
