### ISSUE TITLE
Maintain sorting on load/refresh flattened json

### ISSUE THREAD

**Issue by dimbslmh** [wenzhixin/bootstrap-table#688]
Hello,

I'm trying to keep the current column sorting on load/refresh data in my table. My current code isn't working. What's the correct way to achieve this? My table loads it's data from a json file.

    var $table = $('#table'),
      columnName = "",
      columnOrder = ""; 

    $table.bootstrapTable().on('sort.bs.table', function (e, name, order) {
      columnName = '[" + name + "]';
      columnOrder = '[" + order + "]';
    });

    $table.bootstrapTable({
      sortName: columnName,
      sortOrder: columnOrder
    });

    $table.bootstrapTable('refresh', {silent: true});

**Comment by djhvscf** [comment]
@dimbslmh, can you provide an fiddle, please?

**Comment by dimbslmh** [comment]
It seems this has something to do with a flattened json. I have proposed a new demo.response.json in and created a jsfiddle here: http://jsfiddle.net/nx6m5c59/

Sort a column and then click refresh.

**Comment by djhvscf** [comment]
Yes.. I already saw the issue.. let me check and fix it

**Comment by dimbslmh** [comment]
Thank you for your time. I appreciate it.

**Comment by dimbslmh** [comment]
I found out that the "data" in BootstrapTable.prototype.initSort is not flattened yet on refresh.
Sorting against a flattened data-field:

    var name = this.options.sortName;
which doesn't exist ends up with 
   
     var aa = a[name], bb = b[name]; // undefined

**Comment by dimbslmh** [comment]
Hi Dennis, somehow the "data" on line 599 in bootstrap-table.js

    BootstrapTable.prototype.initData = function (data, type) { ... }

is not flattened anymore on initial load after latest commit. https://github.com/wenzhixin/bootstrap-table/pull/722
See http://issues.wenzhixin.net.cn/bootstrap-table/#350.html. No flattened data shown in table.

What happends: 
In BootstrapTable.prototype.initData () (bootstrap-table-flatJSON.js) the data gets flattened.
Right after that, the BootstrapTable.prototype.initData gets executed (in bootstrap-table.js), but somehow this.data is still unflattened.

**Comment by djhvscf** [comment]
Ok.. I will check it ASAP becuase I think the last changes were not good.. Sorry.. You can use the file that is in Bootstrap-table repository in meantime.. Sorry for the troubles

**Comment by dimbslmh** [comment]
No worries Dennis. Thank you for your efforts.

**Comment by dimbslmh** [comment]
Hi Dennis, here is a fiddle with the latest flatJSON v1.1: http://jsfiddle.net/dimbslmh/cpe7d2tc/1/
On refresh the sorting is still lost.

**Comment by dimbslmh** [comment]
Excuse me @wenzhixin, the issue has not been fixed yet. Please see: http://jsfiddle.net/dimbslmh/cpe7d2tc/1/ or http://issues.wenzhixin.net.cn/bootstrap-table/#350.html

- Sort a column (for example Description)
- Click on refresh button. 

Result: Sorting lost.

**Comment by djhvscf** [comment]
I'm testing it right now..

**Comment by dimbslmh** [comment]
Hi @djhvscf, I have a Pull Request pending to fix this issue. Please review.
Here is a fiddle with the edited files linked: http://jsfiddle.net/dimbslmh/cpe7d2tc/7/

**Comment by ethompsy** [comment]
I have manually applied the two line changes in fix #738. 
It works! Sorting is maintained on a refresh for all fields nested or not when using flatJSON.
Please, accept this change. It is a vast improvement!

**Comment by ethompsy** [comment]
Hmmm... After this change I am getting an error: 'bootstrap-table.js:397 Uncaught TypeError: undefined is not a function'. This goes away if I comment out any 'classes: [...]' on my bootstrap table declarations.

So I am still rolling with this and not using the 'classes' setting. Instead I am setting the classes on the <table> tag.

**Comment by dimbslmh** [comment]
Don't think this is an issue anymore with the latest version of flatJSON so I'm closing it.. Thanks
