### ISSUE TITLE
Search for 'space' returns all data

### ISSUE THREAD

**Issue by nilsbyte** [wenzhixin/bootstrap-table#6886]
### Bootstraptable version(s) affected

1.22.1

### Description

When searching for the string 'space', all results are displayed, nothing changes. I set up a test table with 3 rows, 2 of them contained the word 'space' in different columns (all searchable). When entering 'space', all 3 rows were displayed.

### Example(s)

https://live.bootstrap-table.com/code/nilsbyte/15779

**Comment by wenzhixin** [comment]
You can remove the code: `<span style="font-family: monospace;">` and define CSS to resolve your problem.

Working example: https://live.bootstrap-table.com/code/wenzhixin/15784
