### ISSUE TITLE
Custom view clashes with parent div

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6887]
### Description

I have a BT inside a parent div which gives the table a card style.

But when toggling to the grid view, I would not like this card parent to be present.

I understand the BT is drawn with the parent div, in which also the custom view is drawn.

Maybe any smart hint that I can do to workaround this?

### Example(s)

https://live.bootstrap-table.com/code/marceloverdijk/15782

**Comment by wenzhixin** [comment]
Maybe you can add a toggle view event listener to update the parent class to solve the problem.

**Comment by marceloverdijk** [comment]
Yes that's what I did. From the table container traverse up and remove/add classes based on the custom view state. Thx!
