### ISSUE TITLE
Does the filter control extension not work if data is already in the table?

### ISSUE THREAD

**Issue by ekaj2** [wenzhixin/bootstrap-table#6889]
### Description

See the super simple live example. It automatically picks up on the values and shows them in the select picker, but won't actually filter with them. Also tried input instead of select and I'm seeing the same thing.

All the examples show loading from a json, but I'm building something super simple with Django templates, so I'd rather not go that route.

### Example(s)

https://live.bootstrap-table.com/code/ekaj2/15798

**Comment by wenzhixin** [comment]
In your case, you need to add a `field` to the column to solve the problem, for example: `data-field="a"`.

Working example: https://live.bootstrap-table.com/code/wenzhixin/15803
