### ISSUE TITLE
Table Export - add params to server request / Front end notification of export in process

### ISSUE THREAD

**Issue by davidbarman** [wenzhixin/bootstrap-table#6890]
### Description

When exporting data, need to send a query param to server to differentiate the request is for an export function.
Tried using the export-started and export-saved events, but saved event like this:

`$('#table').on('export-started.bs.table', function (data) {
		exportStarted = true;
	})
`
`$('#table').on('export-saved.bs.table', function (data) {
		exportStarted = false;
	})`

Then tried using exportStarted value in queryParams function:

`function queryParams(params) {
	if (exportStarted) {
		params.export = true;
	}
    return params;
} `

However, exportStarted remains true even after export is finished.  So this is not working.

Also, export process is slow.  Also, need to have an on-screen indicator, spinner, etc to notify users to wait for export to process.  Otherwise, it is unclear if anything is happening.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by davidbarman** [comment]
I have created an online facsimile of the page I have with the issue.
https://bootstraptableexport2.davidbarman.repl.co/

The table is on the right half of the page.
When analyzing the network traffic, the ajax call has different payload for table creation vs export.  However, the query parameters don't distinguish that the export vs a normal table ajax call.  I want to add a query parameter with the export ajax call so the backend script (PHP) knows if it is for export data or table data.

Here are screen shots of the ajax call params

Initial call when page loads:
![Table first page load - Payload from Chrome Network Tab](https://github.com/wenzhixin/bootstrap-table/assets/13839036/d06b1852-b05d-41f1-92ec-ee9b952a0cd2)

When the export button is clicked:
![Table when export button is clicked - Payload from Chrome Network Tab](https://github.com/wenzhixin/bootstrap-table/assets/13839036/41cc13d6-3a45-4ccf-96d4-29f42dd7e145)

After the export completes:
![Table after export is complete - Payload from Chrome Network Tab](https://github.com/wenzhixin/bootstrap-table/assets/13839036/056f5ea3-7c5a-4c16-8ebf-8f4ca8d58789)

Note, the backend database on this example is very small so the export file is created quickly.  However, in my production version we are exporting several thousand records so it takes a few minutes for the file to download.  In the meantime, I need a way to notify the user to wait.  Otherwise, they may think the site is broken or has an issue.   At a minimum, I would like to see the ability for me to add a spinner right after the export button is clicked and then the ability to turn off my spinner once the file has downloaded.  I have tried the export-started and export-saved events without any luck.

Also, is there a way to open the download in the browser, instead of downloading the file to the disk and requiring the user to know that they have to open the downloaded file?

In addition, how can we customize the exported file?  I am trying to use this feature for a "report" of the requested data.  For example, I would like to add a header to the top of the pages.

**Comment by wenzhixin** [comment]
This problem is fixed in #6892 and merged into the `develop` branch.

Online example: https://live.bootstrap-table.com/code/wenzhixin/15922

> How can we customize the exported file?

You can check out the export repo for more information.

**Comment by davidbarman** [comment]
I have checked the table-export, but have still have not found a solution. At a minimum I need to be able to add a header to the exported PDF.
