### ISSUE TITLE
onhover show image

### ISSUE THREAD

**Issue by dermatzeimnetz** [wenzhixin/bootstrap-table#6901]
### Description

Please enable a tooltip extension or bootstrap-table itself to show images on hover. If possible, allow the Bootstrap Tooltip component https://getbootstrap.com/docs/5.2/components/tooltips/  to work in bootstrap-tables as well.

**Comment by wenzhixin** [comment]
You can enable the tooltips in [`onPostBody`](https://bootstrap-table.com/docs/api/events/#onpostbody) event.
https://live.bootstrap-table.com/code/wenzhixin/15898
