### ISSUE TITLE
$tableContainer padding-bottom set value error when resetView if fixed-header = true and filter-control = true 

### ISSUE THREAD

**Issue by jimmyHuang-thu** [wenzhixin/bootstrap-table#6905]
### Bootstraptable version(s) affected

1.22.1

### Description

I found padding-bottom set value error when initial , but I didn't test other situation.

### Possible Solutions

`padding += this.$header.outerHeight(true) + 1;`
change to
`padding += this.$tableHeader.outerHeight(true) + 1;`

when I change it,  and table-body don't out of bounds.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show the problem. Thanks!

**Comment by UtechtDustin** [comment]
It's almost one year and we got no example for testing purposes.
We will close this issue, if you think that bug still persists please let us know and provide us an example.
