### ISSUE TITLE
CustomStorage issue

### ISSUE THREAD

**Issue by DallasCook** [wenzhixin/bootstrap-table#6908]
### Bootstraptable version(s) affected

1.22.1

### Description

I have enabled customStorage with the following settings:
      data-cookie="true"
      data-cookie-id-table="services-table"
      data-cookie-storage="customStorage"
      data-cookie-custom-storage-delete="customStorageDelete"
      data-cookie-custom-storage-set="customStorageSet"
      data-cookie-custom-storage-get="customStorageGet"
      data-cookies-enabled="['bs.table.sortOrder', 'bs.table.sortName', 'bs.table.sortPriority', 'bs.table.pageNumber', 'bs.table.pageList', 'bs.table.searchText', 'bs.table.filterControl', 'bs.table.cardView']"

but I have had to add the line 'cookieName = cookieName.toLowerCase();' 
on line 2765 for it to work.

e.g.
isCookieEnabled: function isCookieEnabled(that, cookieName) {
      cookieName = cookieName.toLowerCase();
      return that.options.cookiesEnabled.includes(cookieName);
},

### Possible Solutions

added ' cookieName = cookieName.toLowerCase();'
to bootstrap-table-cookie.js line 2765.

**Comment by DallasCook** [comment]
My apologies. We were not using the latest version.

**Comment by UtechtDustin** [comment]
So the bug don't exists in the latest version @DallasCook  ?

**Comment by DallasCook** [comment]
That's correct. It is now working. Thanks.
