### ISSUE TITLE
print report

### ISSUE THREAD

**Issue by hinditutorpoint** [wenzhixin/bootstrap-table#6911]
### Description

Hello developer 
how can i print report except some column
Example
id, username, level, action
here i want to when print list then except action column

**Comment by wenzhixin** [comment]
I think the [`printIgnore`](https://bootstrap-table.com/docs/extensions/print/#printignore) column option can help you to solve your problem.

**Comment by hinditutorpoint** [comment]
can you provide proper guide for implement or example

**Comment by wenzhixin** [comment]
The search may help https://github.com/wenzhixin/bootstrap-table/issues?q=printIgnore

**Comment by hinditutorpoint** [comment]
thank you so much
<tr>
                                <th data-field="id">ID</th>
                                <th data-field="class">Class Name</th>
                                <th data-field="admission">Admission Fee</th>
                                <th data-field="annual">Annual Fee</th>
                                <th data-field="created_at">Created At</th>
                                <th data-field="status">Status</th>
                                <th data-field="action" data-print-ignore="true"></th>
                              </tr>

**Comment by wenzhixin** [comment]
You are welcome.

**Comment by hinditutorpoint** [comment]
hello @wenzhixin 
can you guide me how to getRowID with value for example
```
<tr>
    <th data-field="id">ID</th>
    <th data-field="class">Class Name</th>
  </tr>
  <tr>
     <td>1</td>
    <td>Class-1</td>
  </tr>
  <tr>
     <td>2</td>
    <td>Class-2</td>
  </tr>
```
let $rowIndex = where class equal to "Class-1"
Result : 1
Here is self try please improve my code
```
const checkExits = (txt) => {
        var duplicates = false;
        $('#table tr').each(function(row, tr){
          var input = $(tr).find('td:eq(1)').text();
          if(input == txt){
            duplicates =true;
          }
        });
        return duplicates;
      }
```

**Comment by wenzhixin** [comment]
You can use the `getData` method.

```
$table.bootstrapTable('getData').find(it => it.class === text)
```
