### ISSUE TITLE
Plugin: bootstrap-table-print

### ISSUE THREAD

**Issue by davidbarman** [wenzhixin/bootstrap-table#6919]
### Description

When using the example: https://live.bootstrap-table.com/code/wenzhixin/510

I don't see the <title>Print Table</title>  appear on the print preview or the printed page.
I tried in both Chrome and Edge browsers.

I just see:
![image](https://github.com/wenzhixin/bootstrap-table/assets/13839036/3e96ebfa-96ea-441d-b23e-5c3d9713457b)

What am I missing?

**Comment by wenzhixin** [comment]
Tested using Firefox.
<img width="525" alt="image" src="https://github.com/wenzhixin/bootstrap-table/assets/2117018/dd933d23-41c1-49d2-8527-ecb9ce1e3dd3">

When using Edge, you need to change this option.
<img width="980" alt="image" src="https://github.com/wenzhixin/bootstrap-table/assets/2117018/b5d9f596-0011-4387-97b0-f3fb95e4672c">
