### ISSUE TITLE
Static table, content of single cell different when exiting search

### ISSUE THREAD

**Issue by Voxxie** [wenzhixin/bootstrap-table#6931]
### Description

We are using a static table.

When we change cell during search with a onclick event and clear out the search field, the cell is back to its original state instead of displaying the updated cell. 

When we change a cell before using the search and then use the search, also the orginal cell is displayed. (Without the changes )
Is their a way to sync the search and nog search version of the table ? 

### Example editing before search: 

Start status of the table: 
![image](https://github.com/wenzhixin/bootstrap-table/assets/1845378/ade68389-6b24-4c41-8a66-db616f1245b7)

Changing a cell with a onclick event: 
![image](https://github.com/wenzhixin/bootstrap-table/assets/1845378/598458f8-9105-4212-9578-73ae4811af08)

Using the search: 
![image](https://github.com/wenzhixin/bootstrap-table/assets/1845378/c3fffa13-89a9-4f81-bff4-a2ae08b32162)

### Example editing during search: 
Start status of the table:
![image](https://github.com/wenzhixin/bootstrap-table/assets/1845378/af7f6b38-7ebe-49d4-a874-c84c7318a8d0)

Edit during search:
![image](https://github.com/wenzhixin/bootstrap-table/assets/1845378/dcaddfae-2bb5-45fa-aff1-0c853f65dc1a)

Removing search: 
![image](https://github.com/wenzhixin/bootstrap-table/assets/1845378/a20f06f9-a973-478d-9722-0b3c31765753)

**Comment by DataSupplier** [comment]
I don't know if it helps, but have you tried using the data-maintain-meta-data="true" ?
Basically it is applied to the select option, maybe it also affects on the changed values.

**Comment by wenzhixin** [comment]
You need to update the table's data after the `onclick` event (which can be obtained through `getData`), or you can directly use `updateRow` or `updateCell` to update the data in a row. This way, functions like search and sorting can work properly.
