### ISSUE TITLE
Add "reinit: false" param to the "updateCellByUniqueId" method in the documentation.

### ISSUE THREAD

**Issue by jzielinski-bcp** [wenzhixin/bootstrap-table#6932]
### Description

Got a Jira ticket that this method was clearing the whole table on a screen. Further investigation revealed that it was re-initializing the table, when ran. Finally came across a post from 2018 describing the additional param after digging for a half hour. I think it could save someone else a headache if this was called out in the docs. 
https://bootstrap-table.com/docs/api/methods/#updaterow

**Comment by UtechtDustin** [comment]
You're right the documentation was missing for  the [updateCellByUniqueId](https://bootstrap-table.com/docs/api/methods/#updatecellbyuniqueid) method.
I only was documentated for the [updateCell](https://bootstrap-table.com/docs/api/methods/#updatecell) method.
The PR #7003 will improve the documentation.

**Comment by jzielinski-bcp** [comment]
Awesome, thanks for replying. Will close issue.
