### ISSUE TITLE
File Format and Extension Don’t Match when exporting to excel

### ISSUE THREAD

**Issue by trouble2** [wenzhixin/bootstrap-table#6935]
### Bootstraptable version(s) affected

1.22.1

### Description

When I export to excel and try to open the excel file I get a warning saying the File Format and Extension Don’t Match.
So I found this page which might help solve this issue: https://appuals.com/file-format-and-extension-dont-match/

### Possible Solutions

Perhaps change the extension to xlsx or add the correct content type or something:
Response.ContentType = "application/vnd.ms-excel"  Response.AddHeader "Content-Disposition", "attachment; filename=excelTest.xls"

**Comment by wenzhixin** [comment]
If the problem exists, please create an issue in the https://github.com/hhurz/tableExport.jquery.plugin repo. Thanks!
