### ISSUE TITLE
Cookie Extension Breaks With Reorderable Columns

### ISSUE THREAD

**Issue by Ajohn10** [wenzhixin/bootstrap-table#6941]
### Bootstraptable version(s) affected

1.22.1

### Description

When the cookie extension is enabled and is set to control the Reorderable Columns extension with cookies (which it apparently does by default based on my example), it does not save the reorderable columns correctly.  The headers do properly change, but the data below the headers remains to be what is typically in that location.  For example, if you had columns ID, Name, and Price, and then moved them to be Name, ID, Price, when you reload the page (in the example, just press Run) it will show Name, ID, and Price for the headers but the data will still be ID, Name, and Price.

![Screenshot 2023-08-24 081842](https://github.com/wenzhixin/bootstrap-table/assets/87151710/48ba2172-be2b-4e15-97ce-17801b779b9b)

### Example(s)

https://live.bootstrap-table.com/code/Ajohn10/16079

### Additional Context

Performed on Windows 11 in Google Chrome

**Comment by wenzhixin** [comment]
ref #6728
