### ISSUE TITLE
Storing state of custom card view

### ISSUE THREAD

**Issue by DallasCook** [wenzhixin/bootstrap-table#6947]
### Bootstraptable version(s) affected

1.22.1

### Description

I'm using custom storage to store the table's state.
My table can toggle between table and custom card view
I can't seem to save the card view state.
bs.table.cardView doesn't work.
I think it requires a bs.table.customCardView

Is there a way I can get this to work at the moment?

**Comment by djhvscf** [comment]
@DallasCook 
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by DallasCook** [comment]
https://live.bootstrap-table.com/code/DallasCook/16131

**Comment by DallasCook** [comment]
Example supplied

**Comment by DallasCook** [comment]
Hello, any news on storing the state of the custom view?

**Comment by UtechtDustin** [comment]
Submitted a PR which adds support for the cookie extension to the custom view extension.
