### ISSUE TITLE
export ignore column

### ISSUE THREAD

**Issue by hinditutorpoint** [wenzhixin/bootstrap-table#6967]
### Description

Hi dev please guide how can i ignore to export any specific column

**Comment by hinditutorpoint** [comment]
another question is how to set always show custom view without button click mean always show custom view only

**Comment by wenzhixin** [comment]
> Hi dev please guide how can i ignore to export any specific column

https://github.com/hhurz/tableExport.jquery.plugin

> another question is how to set always show custom view without button click mean always show custom view only

```
customViewDefaultView: true
```

Example: https://live.bootstrap-table.com/code/wenzhixin/16933
