### ISSUE TITLE
Sort tables with tags not working

### ISSUE THREAD

**Issue by pedroaugustobt** [wenzhixin/bootstrap-table#6968]
### Bootstraptable version(s) affected

5

### Description

Tables with <a> tags are not sortable, example [1, 100, 101, 102...]

How to solve this problem?

**Comment by UtechtDustin** [comment]
Please provide us an example using our [online editor](https://live.bootstrap-table.com/).

**Comment by wenzhixin** [comment]
Close this issue because there has been no response in 7 days. If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!
