### ISSUE TITLE
Setting table 'height' option breaks 'Table Filter Control'

### ISSUE THREAD

**Issue by tabookopencart** [wenzhixin/bootstrap-table#697]
1. Set table 'height' option
2. Input/Select control will hide.
Easy reproduced by small example modification, just put following line:
           data-toggle="table"
>>>           data-height="700"
           data-url="../json/data1.json"
           data-filter-control="true">

**Comment by djhvscf** [comment]
Working on it!

**Comment by finallove2** [comment]
BootstrapTable.prototype.fitHeader
        that.$header = $fixedHeader.find('thead'); // add line
        that.$header_ = that.$header.clone(true, true);

is not clear code. anyway work it. 
use until developer fix it.

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/977 this is now fixed

**Comment by grumpy-la** [comment]
This is still broken. http://jsfiddle.net/yoku9v3r/
