### ISSUE TITLE
"Table Page Jump To" extension is not working properly when the pagination is displayed both above and below the table

### ISSUE THREAD

**Issue by kolacekp** [wenzhixin/bootstrap-table#6977]
### Bootstraptable version(s) affected

1.22.1

### Description

When I wanted to display the pagination both above and below the bootstrap table and along with it use the "Table Page Jump To" plugin, only the upper occurrence of plugin is working. If I change page to any other eligible page number in the bottom navigation and clicl "Go", it does not work. The page stays the same.

**Comment by UtechtDustin** [comment]
Please provide us an example using our [online editor](https://live.bootstrap-table.com/).

**Comment by kolacekp-able** [comment]
@UtechtDustin  Example here: https://live.bootstrap-table.com/code/kolacekp-able/16421
