### ISSUE TITLE
bootstrap table is translating english phrases to Chinese characters

### ISSUE THREAD

**Issue by knowltonGitHub** [wenzhixin/bootstrap-table#6979]
### Bootstraptable version(s) affected

1.22.1

### Description

    
    <script src="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"></script>
    
    <script src="https://unpkg.com/bootstrap-table@1.22.1/dist/locale/bootstrap-table-zh-CN.min.js"></script>
    
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css">

Some of the phrases on our website are showing Chinese characters instead of English:

![image](https://github.com/wenzhixin/bootstrap-table/assets/26986675/c6e05dd0-4681-4f22-b966-7a6b3bc1bdfa)

![image](https://github.com/wenzhixin/bootstrap-table/assets/26986675/b25b4643-267a-44ad-9873-54faf43b6a84)

### Example(s)

...

### Possible Solutions

...

### Additional Context

What controls whether or not boostrap-table displays in English or Chinese?

**Comment by UtechtDustin** [comment]
I'm not sure what do you try to tell us.   
You including the chinese locale (`<script src="https://unpkg.com/bootstrap-table@1.22.1/dist/locale/bootstrap-table-zh-CN.min.js"></script>`) so you will see chinese text.

**Comment by wenzhixin** [comment]
If you don't need to display Chinese, you don't need to import the `zh-CN.min.js` file.
