### ISSUE TITLE
inserting new rows

### ISSUE THREAD

**Issue by thibaultvanc** [wenzhixin/bootstrap-table#698]
Hi team,

I am finalizing the script to insert new rows to the table.
Below is the ajax code to insert the data in the data base.

The ajax call -> ajax_insert_rows.php
wich return  :
echo '{"id":"55","nom":"Damien","prenom":"fffff","coiture":"renault"}';
, placed in the javascript variable called 'msg'

The following code insert a new row, but it's written : "undefinided" 

    $(function(){ //Add rows

       $table = $('#table');

        $("#form_new_entry_").bind('submit',function () {

                $.ajax({
                    type: "POST",
                    url: "../../itblockit/block_passif_presentation/10/ajax_insert_rows.php", 
                    data: $('form#form_new_entry').serialize(),
                    success: function(msg){
                       
                        $("#new_entry_").modal('hide'); 
                        
                        alert(msg);

                                            

                        $table.bootstrapTable('togglePagination');
                        
                        $('#table<?= $idcolonne ;?>').bootstrapTable('insertRow', {
                            index: 0,
                            row: msg
                        });

                         $table.bootstrapTable('togglePagination');

                        
                    },
                    error: function(){
                        alert("failure");
                    }
                });

                return false;

        });

    });

**Comment by wenzhixin** [comment]
I think you need to use first:
```
msg = $.parseJSON(msg);
```

**Comment by thibaultvanc** [comment]
fantastic !!
thank you wenzhixin
:+1:
