### ISSUE TITLE
bootstrap-table-mobile toggle condition

### ISSUE THREAD

**Issue by maxgrass** [wenzhixin/bootstrap-table#699]
CardView is activated when BOTH Width and Height are SMALLER than minWidth/minHeight:

https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/mobile/bootstrap-table-mobile.js#L20

the typical use case would be 10 columns, which need to be shown in cardView if and only if WIDTH is less then X. It makes no sense to consider height in this case.

Can we introduce a parameter like `toggleWidthHeightSeparately` or `toggleByWidth[Only]` + `toggleByHeight[Only]`?

If I set height=100000, then it never returns to the normal view from card view.
I know resizing can be painful :)

**Comment by djhvscf** [comment]
Yes.. I will try to improve the extension.. Any pull request is welcome!! @maxgrass

**Comment by djhvscf** [comment]
I think we can do this:

Add an option to validate only the Width
Add an option to validate only the Height

What do you think, @maxgrass ?

**Comment by wenzhixin** [comment]
I think we can set the default value to undefined of minHeight option?

**Comment by djhvscf** [comment]
See: https://github.com/wenzhixin/bootstrap-table/pull/717

**Comment by wenzhixin** [comment]
Close this issue.
