### ISSUE TITLE
Cookie implementation is not working

### ISSUE THREAD

**Issue by xmbohx** [wenzhixin/bootstrap-table#6991]
### Description

Hi,

I modified the cookie example [here](https://jsfiddle.net/agt2021/3jaoy2ew/2/)

I want to have a condition when return to this table/page, the table is in the last state (page/sort/record position) 
however the page does not show as expected.

Please advise

**Comment by UtechtDustin** [comment]
Please provide us an example using our [editor](https://live.bootstrap-table.com/).

**Comment by wenzhixin** [comment]
Close this issue because there has been no response in 7 days. If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!
