### ISSUE TITLE
sort select options do not work

### ISSUE THREAD

**Issue by FranckMARTEAU** [wenzhixin/bootstrap-table#6992]
### Bootstraptable version(s) affected

1.22.1

### Description

The sort select options do not work. It works in 1.19.1 but not in upper versions.

### Example(s)

https://live.bootstrap-table.com/code/FranckMARTEAU/16239

**Comment by UtechtDustin** [comment]
`sortSelectOption` is an table option not an column option, move it to the table element and the sort is working. Example: https://live.bootstrap-table.com/code/UtechtDustin/16251
The `filterOrderBy` option is buggy anyways, this [PR](https://github.com/wenzhixin/bootstrap-table/pull/7000) should fix it.
