### ISSUE TITLE
Sort by multiple columns

### ISSUE THREAD

**Issue by nikolas** [wenzhixin/bootstrap-table#70]
Is there a way to initialize a bootstrap-table to be sorted by multiple columns?

Suppose you have a table like this:

Target Date | Priority
------- | ---------
2/2/2002 | Medium
1/1/2013 | High
1/1/2012 | High
1/1/2014 | High

I want the default view to look like this (sorted first by Priority descending, then Target Date ascending).

Target Date | Priority
------- | ---------
1/1/2012 | High
1/1/2013 | High
1/1/2014 | High
2/2/2002 | Medium

**Comment by abriz** [comment]
+1 on the multiple column sort option!!   Thanks for the tool, big help so far.

**Comment by dimbslmh** [comment]
I made this extension for sorting by multiple columns:
http://jsfiddle.net/dimbslmh/s2h1gzj9/

**Comment by djhvscf** [comment]
Great feature!! Can you review when we hide a column and then we try to open the modal?? I think it is not working

**Comment by dimbslmh** [comment]
Weird, please see if it is working here: https://jsfiddle.net/dimbslmh/s2h1gzj9/embedded/result/

Seems to be working even with only one column visible.

**Comment by dimbslmh** [comment]
Ah.. wait, it happends when you have the columns dropdown open instead of dismissing the columns dropdown first.

**Comment by djhvscf** [comment]
Steps:

1. Sort some column (without the extension)
2. Hide a column
Open the modal (Here the Add Level button is disabled)

**Comment by dimbslmh** [comment]
And also with your steps it seems. Ok, I'll try to fix it.

**Comment by djhvscf** [comment]
Ok, thanks but it is a great great feature!!

**Comment by dimbslmh** [comment]
Should be working correctly now!

**Comment by djhvscf** [comment]
Yes, it is working know!! great! Thanks you!

**Comment by rajeshbtlit** [comment]
Hi, Great to hear this, so this is available in master branch right ? and not in 1.8

**Comment by wenzhixin** [comment]
Thanks @djhvscf and @dimbslmh. 
@rajeshbtlit, you can use it in [src dir](https://github.com/wenzhixin/bootstrap-table/tree/master/src).

**Comment by rajeshbtlit** [comment]
can we use this on top of 1.6  or do we need to first upgrade to 1.8

**Comment by djhvscf** [comment]
I think we should use the lastest release! @wenzhixin @rajeshbtlit

**Comment by rajeshbtlit** [comment]
On 1.6 I see that when i click on any sort i get so many sort icons as shown.
![muliplesort](https://cloud.githubusercontent.com/assets/11829880/7799449/d9be9826-0323-11e5-9d83-6fdf06085ea0.png)

HTML
````
<table id="tableWorkflow" data-toggle="table"
						data-single-select="true" data-url="wf/Admin/simplifiedProcesses"
						data-cache="false" data-height="600" data-click-to-select="true"
						data-striped="true" data-pagination="true" data-search="true"
						data-sort-order="desc" data-sort-name="creationTime"
						data-show-columns="true" data-show-refresh="true"
						data-show-multi-sort="true" data-sort-priority='[{"sortName":"creationTime","sortOrder":"desc"},{"sortName":"wfdName","sortOrder":"desc"},{"sortName":"wfdVersion","sortOrder":"asc"}]'
						data-page-size="50" data-page-list='[50, 75, 100, 200, 300, 500'>


<!-- jQuery -->
<script src="resources/admingui/js/jquery-1.11.2.js"></script>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="resources/admingui/js/jquery-1.11.2.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="resources/admingui/js/bootstrap.min.js"></script>
<script src="resources/admingui/js/bootstrap-table.js"></script>
<script src="resources/admingui/js/extension/bootstrap-table-multiple-sort.js"></script>
<script src="resources/admingui/js/jsoneditor.js"></script>
<script type="text/javascript" src="js/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="js/cs/mapper/jsonlite.js"></script>
<script type="text/javascript" src="js/cs/expEditor/eUtility.js"></script>
<script type="text/javascript" src="js/cs/expEditor/jquery.treeview.js"></script>
<script type="text/javascript" src="js/jsonschemagen/jsonSchemaEditor.js"></script>
<script type="text/javascript" src="js/jsonschemagen/eSchemaParserJson.js"></script>
<script src="js/jsonschemagen/jquery.contextMenu.js" type="text/javascript"></script>
<link href="js/jsonschemagen/jquery.contextMenu.css" rel="stylesheet" type="text/css" />
````

**Comment by djhvscf** [comment]
You have to use also the boostrap-table.css 1.8.0

**Comment by rajeshbtlit** [comment]
Yes I am using the following css

````
<!-- Bootstrap -->
<link rel="stylesheet" href="resources/admingui/css/bootstrap.min.css">
<link rel="stylesheet" href="resources/admingui/css/bootstrap-table.css">
<link rel="stylesheet" href="resources/admingui/css/main.css">
<link href="css/smoothness/jquery-ui.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="css/expEditor/jquery.treeview.css" />
````

**Comment by wenzhixin** [comment]
Please use the latest version: boostrap-table.js 1.8.0 and boostrap-table.css 1.8.0.

**Comment by rajeshbtlit** [comment]
Thanks, will let u know how it goes. And a big thanks for you guys for giving the framework.

**Comment by rajeshbtlit** [comment]
Thanks everyone for there great efforts , see a glitch here, when integrated with another table , on click of the sort icon, the old tables sorting options appear.

JS fiddle here@ https://jsfiddle.net/jupitor/h2c683cn/

**Comment by rajeshbtlit** [comment]
Hi, Could you please have a look at this issue
https://github.com/wenzhixin/bootstrap-table/issues/70

Thanks a ton for all  your great efforts.

On Mon, May 25, 2015 at 9:23 PM, 文翼 <notifications@github.com> wrote:

> Please use the latest version: boostrap-table.js 1.8.0 and
> boostrap-table.css 1.8.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wenzhixin/bootstrap-table/issues/70#issuecomment-105255776>
> .
>



-- 
Regards
Rajesh
ph:+919886636301

**Comment by rajeshbtlit** [comment]
Hi, 
Thank you guys for your efforts, really appreciate it, could you please let us know if we are planning to fix this, as we are using this in our application  and we have multiple tables.

Guys please help!!!

**Comment by nikolas** [comment]
@rajeshbtlit consider switching to jquery-datatables: https://www.datatables.net/

That's what I've done, because it supports sorting by multiple columns.

**Comment by djhvscf** [comment]
We support this feature. See this: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/multiple-sort

**Comment by rajeshbtlit** [comment]
Thanks Dennis,  thing is I have integrated this .
But in my scenario, i have 3 tables, and in first table multiple sort works fine no problem.
When i add it to second table, i see that the same sort modal opens (i mean the sort window of the first table)

JS fiddle here@ https://jsfiddle.net/jupitor/h2c683cn/

I have created two tables and added the multiple sort attribute for both and the second table always shows the first tables sorting columns

**Comment by djhvscf** [comment]
I will create a issue because this is an important issue

**Comment by Taewa** [comment]
Thanks awesome guys!!

**Comment by woltbit** [comment]
pardon, does Bootstrap-table version 1.10.1 support multisort ? or I must use bootstrap-table version 1.8.1?

**Comment by djhvscf** [comment]
It supports it... you should use the multiple-sort extension

**Comment by woltbit** [comment]
@djhvscf Thank you for your reply, but I have tried the version 1.10.1 with multisort v 1.0.0 but nothing seems to be working.. but when i replace the bootstrap-table v 1.10.1 with v1.8.1, it's working..

Here is the jsfiddle which use v1.10.1, thanks in advance
https://jsfiddle.net/juanzheng/m7y6op1w/

**Comment by wenzhixin** [comment]
What's the problem? @woltbit

**Comment by djhvscf** [comment]
I have tested with both versions and it seems it is working as expected

**Comment by woltbit** [comment]
hmphh.. well that is weird, the problem is when I try to use multisort version 1.0.0 with bootstrap-table.js version 1.10.1 it somehow doesn't work properly. But in the end I try to switch to bootstrap-table.js version 1.09.1 and everything was working fine.

so thank you for your time, it should ok for me right now. Keep up the good work!

**Comment by vivek-kandhvar** [comment]
> We support this feature. See this: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/multiple-sort

This extension no more works. Just so that you guys are aware.

**Comment by UtechtDustin** [comment]
#4616
