### ISSUE TITLE
Provide Custom Sort for bootstrap table

### ISSUE THREAD

**Issue by rajeshbtlit** [wenzhixin/bootstrap-table#700]
Could we have custom sort mechanism for a bootstrap table, like for example in a table  if we have 5 columns, we can have a provision to add a filter like , first sort by column, then sort by column 3, then by column 5 etc.

Thanks

**Comment by wenzhixin** [comment]
Multiple sort?

**Comment by djhvscf** [comment]
Maybe you can use the column option data-sort-name.. See the docs here: http://bootstrap-table.wenzhixin.net.cn/documentation/

**Comment by rajeshbtlit** [comment]
Thanks Wen and dj, I am actually looking at multi level custom sorting, currently am able to sort based on columns. But need to create a custom sort as shown in the picture.
It has a table and columns can be individually be sorted , along with that we can create a custom sort as shown in the popup.
![untitled](https://cloud.githubusercontent.com/assets/11829880/7025886/1dfd6dea-dd64-11e4-9a24-23f9508473a6.png)

**Comment by wenzhixin** [comment]
Does not support now. #70

**Comment by rajeshbtlit** [comment]
Thanks Wen, could we have this in near future, I believe this is really a useful functionality.
Appreciate your support.

**Comment by wenzhixin** [comment]
I will consider this feature. This issue is the sample feature with #70, so close it, you can look at the https://github.com/wenzhixin/bootstrap-table/blob/master/CHANGELOG.md to know what feature we added.

**Comment by rajeshbtlit** [comment]
Thanks everyone for there great efforts , see a glitch here, when integrated with another table , on click of the sort icon, the old tables sorting options appear.

JS fiddle here@ https://jsfiddle.net/jupitor/h2c683cn/

I have created two tables and added the multiple sort attribute for both and the second table always shows the first tables sorting columns

@dimbslmh could you please have a look
