### ISSUE TITLE
Search criteria not looking into two columns

### ISSUE THREAD

**Issue by krfa1** [wenzhixin/bootstrap-table#701]
Hello,

I've tested with the version 1.7 and previous, even on your exemple page, if for exemple we have a column with first name, and a second column with last name, it's impossible to user the search box to enter the people full name.

Fabrice

**Comment by djhvscf** [comment]
Right now it is not supported.. I think this is a good feature.. @wenzhixin

**Comment by wenzhixin** [comment]
I think it is not easy to implement this feature.

**Comment by djhvscf** [comment]
I think the best option is use the filter control extension..

**Comment by dabros** [comment]
I agree the filter extension is prob the best, only other option might be to allow option for 'searchDelimiter' and if this is non-null explode/split the search box contents using this (so whitespace or "," or whatever user defines)

**Comment by djhvscf** [comment]
Something like: Dennis, Hernández? and then we will search by name and last name??

**Comment by wenzhixin** [comment]
I think this feature is like an advance search, for example: you enter "wen zhixin", then we split the string to ['wen', 'zhixin'], search the data row contain 'wen' or 'zhixin.

**Comment by krfa1** [comment]
Exactly, I think if two words are present in the search input, it could be searched in whatever column. But how would it be possible to do it with the filter extension?

**Comment by djhvscf** [comment]
For now that feature is not supported in filter control extension.

**Comment by djhvscf** [comment]
You can use the toolbar extension. https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/toolbar

**Comment by krfa1** [comment]
Great news and good job. Well done. Thanks
