### ISSUE TITLE
Page number not reset when data result changed

### ISSUE THREAD

**Issue by ctessandri** [wenzhixin/bootstrap-table#7017]
### Bootstraptable version(s) affected

1.22.1

### Description

Page number is in cookie.
If i am positioned on page 2, and refresh data with a custom filter so that results give just one page, page number is not reset to one and i cannot see my results.

### Possible Solutions

1) set options.pageNumber = 1 in call to refresh botton

2) expose an event occurring "beforeRefresh", with possibility to set pageNumber to what i like

**Comment by harshbsharma** [comment]
Hey @ctessandri can you please add a screenshot or video for better understanding of the issue.

**Comment by ctessandri** [comment]
Hi,
Sorry but a screenshot would not show the problem.

I try to summarize the sequence:

  1.  Page number is in cookies
  2.  I load data, result is 3 pages
  3.  I go on page 3
  4.  I set a filter and reload data. Result is one page.
  5.  I see nothing. PageList disappears, current page remains 3 and I cannot do nothing.

Thank you so much.
Cristina

**Comment by ctessandri** [comment]
Hallo, any news about this?

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

> set options.pageNumber = 1 in call to refresh button

This may be the possible solution.

**Comment by wenzhixin** [comment]
Close this issue because there has been no response. If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!

**Comment by ctessandri** [comment]
As I told you, it’s not possible to provide an example.
Many operating steps are needed to reproduce the problem.
You have the operational sequence, so try it out.

I had to modify the script myself.

Bye
Cristina
