### ISSUE TITLE
有关重写 queryParams 方法的疑问 

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#704]
mvc controller action
public ActionResult PageList(int offset = 0, int limit = 10, string search = "", string sort = "", string order = "", OrderSearchQueryViewModel query = null)

OrderSearchQueryViewModel 是我定义的一个查询参数的集合  有4个字段作为参数

前台 
var SearchQuery={}；
SearchQuery.OrderId='00001';
SearchQuery.OrderDate='2012/11/23';
$orderstable = $('#orders-table').bootstrapTable(
            {
                queryParams: function (p) {
                    return {
                        query: SearchQuery,
                        search: p.search,
                        sort: p.sort,
                        order: p.order,
                        limit: p.limit,
                        offset: p.offset
                    };
                }
            });

 这样写的话 传到服务端后 OrderSearchQueryViewModel query 没有获取的对应的值
也就是说 query 参数没有传递到服务端 
但如果单个参数传是没有问题的

**Comment by wenzhixin** [comment]
get 的话不支持这种，你自己查一下 Network 面板（F12）应该就知道请求什么了。
详细查下 ajax 的 API，估计可以试下用 post 的方式。

**Comment by neozhu** [comment]
明白了，谢谢
