### ISSUE TITLE
cannot initialize twice

### ISSUE THREAD

**Issue by aducom** [wenzhixin/bootstrap-table#7048]
### Bootstraptable version(s) affected

latest

### Description

I have two tables on the form, both have different id's in a master-detail relationship The application seems to work fine, no red dots in the javascript. However if I scroll through I see a message that is sent to the console from the boostrap-table js. 

I have made a file in the editor, not sure if I saved it right though.

Both tables are initialize with    table data-toggle="table"

For completeness the setup of both tables. 
                                                       
table width="100%" class="table table-bordered table-hover table-striped table-sm table-borderless" id="id_mdperssal_dbgrid_1" name="mdperssal_dbgrid_1" data-classes="table table-bordered table-hover table-striped table-sm table-borderless " data-toggle="table" data-url="?component=mdperssal_dbgrid_1" data-sort-class="table-active" data-sortable="true" data-height="" data-id-table="advancedTable" data-search="true" data-maintain-meta-data="true" data-maintain-selected="true" data-select-item-name="dbgrid_1_select" data-id-field="dbgrid_1_select" data-show-header="true" data-show-columns="true" data-show-refresh="true" data-pagination="true" data-show-footer="false" data-show-pagination-switch="true" data-show-toggle="true" data-show-fullscreen="true" data-sticky-header="false" data-loading-template="loadingTemplate" data-cache="true" data-detail-view="false" data-detail-view-by-click="false" data-detail-view-icon="false" data-detail-formatter="id_mdperssal_dbgrid_1_onDetailFormatter" data-mobile-responsive="true" data-content-type="application/xhtml+xml" data-locale="en-US" data-show-export="true" data-export-types="['json','xml','csv','txt','sql']" data-row-style="id_mdperssal_dbgrid_1_rowStyle" data-side-pagination="client" data-page-list="[5, 10, 20, 50, 100, 250]" data-page-size="5" data-sort-order="asc" data-group-by-toggle="false" data-group-by-show-toggle-icon="true" data-group-by="false" data-query-params="queryParams" data-group-by-formatter="groupByFormatter" data-unique-id="employees_emp_no;"

and

table width="100%" class="table table-bordered table-hover table-striped table-sm table-borderless" id="id_mdperssal_dbgrid_3" name="mdperssal_dbgrid_3" data-classes="table table-bordered table-hover table-striped table-sm table-borderless " data-toggle="table" data-url="?component=mdperssal_dbgrid_3" data-sort-class="table-active" data-sortable="true" data-height="" data-id-table="advancedTable" data-search="true" data-maintain-meta-data="true" data-maintain-selected="true" data-select-item-name="dbgrid_3_select" data-id-field="dbgrid_3_select" data-show-header="true" data-show-columns="true" data-show-refresh="true" data-pagination="true" data-show-footer="false" data-show-pagination-switch="true" data-show-toggle="true" data-show-fullscreen="true" data-sticky-header="false" data-loading-template="loadingTemplate" data-cache="true" data-detail-view="false" data-detail-view-by-click="false" data-detail-view-icon="false" data-detail-formatter="id_mdperssal_dbgrid_3_onDetailFormatter" data-mobile-responsive="true" data-content-type="application/xhtml+xml" data-locale="en-US" data-show-export="true" data-export-types="['json','xml','csv','txt','sql']" data-row-style="id_mdperssal_dbgrid_3_rowStyle" data-side-pagination="client" data-page-list="[5, 10, 20, 50, 100, 250]" data-page-size="10" data-sort-order="asc" data-group-by-toggle="false" data-group-by-show-toggle-icon="true" data-group-by="false" data-query-params="queryParams" data-group-by-formatter="groupByFormatter" data-unique-id="salaries_emp_no;salaries_from_date;"

### Example(s)

Made one in live, hope I have done it right.

### Additional Context

PHP 8.2 Windows.

**Comment by aducom** [comment]
![image](https://github.com/wenzhixin/bootstrap-table/assets/5610893/096e6470-0706-497c-9111-c68d844f86fa)

**Comment by wenzhixin** [comment]
Why do you need to initialize two times? You can wait until you need it before initializing it in js.

**Comment by aducom** [comment]
Tnx for your reply. Of course, I don't intentionally initialize twice, but just saw the message in the console and was wondering why. As I could not decide if I was probably doing something wrong, or if it was a bug, I shared my code. Apparently I'm doing something wrong here. Can you give a hint?

**Comment by wenzhixin** [comment]
Remove `data-toggle="table"`？

**Comment by wenzhixin** [comment]
Close this issue because there has been no response in 7 days. If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!
