### ISSUE TITLE
AngularJS cell formatting

### ISSUE THREAD

**Issue by rschakenbos** [wenzhixin/bootstrap-table#705]
We would like to use the bootstrap table for a new project. The application we're building is an AngularJS application, so we use a directive to get the bootstrap table working. All seems well, however the cells have a formatter option that I can't get to work. 

I set up a plunker example that illustrates the problem:
http://plnkr.co/edit/DJWLi2rSDdHM3GXYQd0k?p=preview

In the columns definition of the bootstrap table options, there is this field called "formatter". It is a function that should return the index for each row (similar to the example provided on http://bootstrap-table.wenzhixin.net.cn/examples/#format ). Unfortunately, this is not working. Do you have an idea how we can get around this problem?

**Comment by wenzhixin** [comment]
I think the problem is here, all function options is lost after use `scope.$eval`.
```
var options = scope.$eval(attrs.bsTable);

console.log(options); // all function options is lost
```

**Comment by djhvscf** [comment]
If the @wenzhixin answer is not the solution, then reopen the issue @rschakenbos
