### ISSUE TITLE
Use array response payload as server side data, exception -> error reading property length of undefined

### ISSUE THREAD

**Issue by markusmuellerusi** [wenzhixin/bootstrap-table#7059]
### Bootstraptable version(s) affected

1.22.1

### Description

I use arrays comming back in payload of server response. The following code block in bootstrap-table.js causes an exception.
        if (
          this.options.sidePagination === 'server' &&
          this.options.pageNumber > 1 &&
          res[this.options.totalField] > 0 &&
          !res[this.options.dataField].length
        ) {
          this.updatePagination()
        }

I have no dataField, so this.options.dataField is undefined and !res[this.options.dataField].length causes the exception.
-> I use pagination and I have a total property, but res is my response array itself and it contains the data, not a property for data.
How should I configure this?

### Example(s)

See above. Use an array directly as data source.

### Possible Solutions

No suggestion

### Additional Context

Use Server mode.
I tested 1.22.1 and use currently 1.20.2 in project dependency-track/frontend.
Both have this issue.

**Comment by markusmuellerusi** [comment]
Code above is from bootstrap-table.js line 2052 ff.

**Comment by wenzhixin** [comment]
You should use client-side pagination for this case, right? Why did you use server-side pagination? Or you can use the `responseHandle` to process your return.

**Comment by markusmuellerusi** [comment]
No, I really use server-side pagination. This is what I need. The response coming back from my API server is just a series of records. I know you're expecting a "rows" property or some other property to hold the data by default, but I can't easily cast my array because I don't want to change or minimally change the code of the dependency track frontend itself. Your suggestion means changing a large number of lines of code. That's a project maintained by Steve Springett to analyse SBoMs and find vulnerabilities (https://github.com/DependencyTrack/frontend). The reason I'm asking you is because I often use arrays of data sets in my own projects. This is common when using the simple Rest API. Thanks for your time.

**Comment by wenzhixin** [comment]
If you are using server-side pagination, the data returned should include the total number of records.

**Comment by markusmuellerusi** [comment]
That's right and that's not the problem. The total number works. The problem is "res[this.options.dataField].length". I have no dataField, because res is the array containg the data. There is no property "rows", it's only res[] (with the total as addition prop).

**Comment by wenzhixin** [comment]
You can use this solution to solve this problem first, but in most cases, if you want to return `[],` it is recommended that you use client-side pagination directly. I will close this issue because it's resolved.
