### ISSUE TITLE
DetailView how to?

### ISSUE THREAD

**Issue by PsyBooty** [wenzhixin/bootstrap-table#7068]
### Description

I have a table that i want to use the DatailView but cant figureout how to show the coluns in the datailview.
In the example i have 5 colluns, 3 should be on the grid and 2 on the detail...

### Example(s)
https://live.bootstrap-table.com/code/PsyBooty/16507
<table
  id="table"
  data-toggle="table"
  data-height="460"
  data-detail-view="true"       
  data-detail-view-icon="true">
  <thead>
    <tr>
      <th >ID</th>
      <th>Item Name</th>
      <th >Item Price</th>
    </tr>
    
  </thead>
  <tbody>
    <tr>
    <td>1</td>
    <td>Item 01</td>
    <td>Price 2000</td>
    <td>Detail 01</td>
    <td>Detail 02</td>
    </tr>
  </tbody>
</table>

**Comment by wenzhixin** [comment]
Example: https://live.bootstrap-table.com/example/options/detail-view.html

**Comment by 627721565** [comment]
您好，邮件已经收到，查阅后会尽快给您回复！
