### ISSUE TITLE
How to set table header width

### ISSUE THREAD

**Issue by ravi-ku** [wenzhixin/bootstrap-table#707]
Hi,

I want set table header width.Please help how to achieve it.

OR How to wrap table header with set width.

Regards,
Ravi
mcamail2002@gmail.com
![table-header-width](https://cloud.githubusercontent.com/assets/11146609/7040651/fda90c6c-ddee-11e4-9c64-677fc01183ee.png)

**Comment by rschakenbos** [comment]
You can specify the width in the column definition. For example, see the Stars column (edited from http://jsfiddle.net/wenyi/e3nk137y/13/light/ ):

```javascript
<table id="table">
    <thead>
    <tr>
        <th data-field="name">Name</th>
        <th data-field="stargazers_count" data-width="200">Stars</th>
        <th data-field="forks_count">Forks</th>
        <th data-field="description">Description</th>
    </tr>
    </thead>
</table>
```

**Comment by RikStage** [comment]
When I try to set the width of my columns to be less than the width bootstrap-table makes them by default nothing happens. The width of a column can increase, but it cannot decrease. I'm looking for a way to give my columns a maximum width. Is this possible?

**Comment by dabros** [comment]
@RikStage - the best way about it is prob to just use the column 'class' option http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

While having to use explicit class for each is bad form, it doesnt have to be unique - you can setup a few classes like this:

```css
.minw100{ min-width:100px!important; }
.w100{ max-width:100px!important; }
.maxw100{ max-width:100px!important; }
```

I have used something similar before, and it works alright when you make them reusable and consistent

**Comment by djhvscf** [comment]
Thanks @dabros

**Comment by wenzhixin** [comment]
Yes, you can use the class to define your width: http://jsfiddle.net/e3nk137y/1702/

**Comment by kofm** [comment]
Thank you very much, that work fine.
What if i want to wrap column headers?

Thanks for your really awesome work.
