### ISSUE TITLE
Table-Export with Group-By-V2

### ISSUE THREAD

**Issue by Xypocat** [wenzhixin/bootstrap-table#7070]
### Description

Hello

I don't know if it's me who hasn't looked in the right place or if it's not possible, but I haven't found a solution for not having the group lines in the exports.

**Comment by wenzhixin** [comment]
![image](https://github.com/wenzhixin/bootstrap-table/assets/2117018/36837ced-1349-4c67-a7d6-132cecfea15e)

Working example: https://live.bootstrap-table.com/code/wenzhixin/16926

**Comment by Xypocat** [comment]
Instead of this:
![image](https://github.com/wenzhixin/bootstrap-table/assets/34869652/6221e008-40bc-43f6-b969-c063379cb463)

I would like this:
![image](https://github.com/wenzhixin/bootstrap-table/assets/34869652/4c340403-4dd7-4814-a0b4-54352e5c7136)
