### ISSUE TITLE
Editable plugin: Assign column formatter and display/value member of X-Editable

### ISSUE THREAD

**Issue by tabookopencart** [wenzhixin/bootstrap-table#709]
Editable plugin not support 'formatted' fields.
My suggestions is:
1) Separate Display/Value members here:

                var display_value = _formatter ? _formatter(value, row, index) : '';
                return ['<a href="javascript:void(0)"',
                    ' data-name="' + column.field + '"',
                    ' data-pk="' + row[that.options.idField] + '"',
                    ' data-value="' + value + '"',
                    '>' + display_value + '</a>'
                ].join('');

This modified code help to show 'Formatted data' before edit and work with a real 'Value' data. 
However, after editing x-editable shows raw value, not 'formatted' data. 

So the way to assign column formatter (if any) with 'display' option of x-editable plugin is really needed.

**Comment by wenzhixin** [comment]
OK, any pull request is welcome.

**Comment by tabookopencart** [comment]
Actually, the code above it's not a solution. It's only part of the problem. After editor is closed, cell shows 'real' value, not formatted. How can we force to repaint the cell after edit ?

**Comment by tabookopencart** [comment]
I guess, the issue can be closed.
As a summary: if you need to edit formatted cell you should perform following:
- remove 'formatter' option from the column
- add 'editable' object with custom 'display' option that shoud work as removed 'formatter' option.
