### ISSUE TITLE
About null data in json

### ISSUE THREAD

**Issue by peoplehlj** [wenzhixin/bootstrap-table#71]
Hello, thanks for your bootstrap table, it is useful.
But now I seems to meet a bug, when there is 'null' data in json, the bootstrap table will stay on the 'loading', without showing any data. Is it a bug?
The json is like:
 [{"id":"1"},{"id":null},{"id":"3"}]

Thank you very much.

**Comment by csujiabin** [comment]
@wenzhixin It seems the bug still exists in the latest version(1.11.0).
When I return `null` instead of `[]`, error occurs:
`bootstrap-table.min.js:8 Uncaught TypeError: Cannot read property 'fixedScroll' of null`
