### ISSUE TITLE
What is the return of totalNotFiltered for?

### ISSUE THREAD

**Issue by MarksEliel** [wenzhixin/bootstrap-table#7104]
### Description

Doubt!

What is the need for +1 mysql query to return totalNotFiltered, what is the function of this item in the return?

I confess that I tested it here, and I didn't notice any difference in having to perform a query to count unfiltered values...

For now I will disable the return of totalNotFiltered

**Comment by wenzhixin** [comment]
If you're not using search, you can ignore this property.

Example: https://examples.bootstrap-table.com/index.html#options/total-not-filtered-field.html

![image](https://github.com/wenzhixin/bootstrap-table/assets/2117018/31a68551-80c8-4563-837f-0614058cbcd0)
