### ISSUE TITLE
bootstrap-table-cookie: error

### ISSUE THREAD

**Issue by axelwass** [wenzhixin/bootstrap-table#711]
Error:
Uncaught TypeError: undefined is not a function
bootstrap-table-cookie.js:151

Options used:
data-state-save="True"
data-state-save-expire="1y"
data-state-save-id-table="preferencias-tabla-tareas"

**Comment by djhvscf** [comment]
Ok, what is the version of the file? can you put a screenshot to see the line??

**Comment by axelwass** [comment]
@version: v1.1.0
![image](https://cloud.githubusercontent.com/assets/784230/7054660/8ffea450-de03-11e4-8ef1-d8e529d61137.png)

<table
        style="cursor: pointer; cursor: hand;"
        data-url="lista_pendientes"
        id="contentTable"
        class="table table-striped table-hover table-condensed"
        data-toolbar="#toolbar-extra"
        data-toggle="table"
        data-sort-name="numero"
        data-sort-order="desc"
        data-show-export="true"
        data-show-refresh="true"
        data-show-toggle="true"
        data-show-columns="true"
        data-search="true"
        data-select-item-name="toolbar1"
        data-pagination="true"
        data-page-number="1"
        data-total-rows="100"
        data-page-list="[5, 10, 20, 50, 100, 200]"
        data-row-style="rowStyle"
        data-side-pagination="server"
        data-state-save="True"
        data-state-save-expire="1y"
        data-state-save-id-table="preferencias-tabla-tareas">

**Comment by djhvscf** [comment]
See this.. http://jsfiddle.net/4r6g4cfu/38/

**Comment by djhvscf** [comment]
Any update? @axelwass

**Comment by axelwass** [comment]
I finally found out what the problem was. I was using bootstrap-table version 1.6.0. With version 1.7.0 it works fine.
Thanks for your time.

**Comment by djhvscf** [comment]
Sounds great! @axelwass
