### ISSUE TITLE
How to use data-url for JSON?

### ISSUE THREAD

**Issue by henrysan96** [wenzhixin/bootstrap-table#712]
Hi, I don't know how to use the data-url. Do I also need any extension to use the data-url function like flatJSON. Because in this page http://jsfiddle.net/wenyi/e3nk137y/14/light/ ,  when I change the data-url to data-url="https://raw.githubusercontent.com/wenzhixin/bootstrap-table/master/docs/data/data1/demo.response.json"  instead of "/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data1/" like in the example. The table won't show any data anymore? Thanks for helping me.

**Comment by djhvscf** [comment]
Your table config or json response or fiddle please just for help you

**Comment by meetconverge** [comment]
That is because content is being served as ```` Content-Type: text/plain ```` instead of ```` Content-type:application/javascript ````

try it offline using a .json file in the same directory as your test html, and it'll work. If you have access to some other json, that isnt being served as ```` Content-type:text/plain ```` , that will work too.

**Comment by wenzhixin** [comment]
This is cross domain problem of ajax, your html file and your data url need to put in the same domain.

**Comment by henrysan96** [comment]
http://www.cc.puv.fi/~e1400477/hei.html
http://www.cc.puv.fi/~e1400477/workqueue.json
The json file is in the same folder as my html page. I also have data-content-type="application/javascript" but still No matching records found. I don't know what is the problem then. Thanks for helping me.

**Comment by djhvscf** [comment]
Use the FlatJSON extension and then do this to get the data into the table:

```html
<th data-field="ma_work order.work_id">Work ID</th>
<th data-field="ma_work order.customer">Customer</th>
<th data-field="ma_work order.material">Material</th>
<th data-field="ma_work order.work_name">Work</th>
<th data-field="ma_work order.patch_time">Time</th>
<th data-field="ma_work order.quantity">Quantity</th>
<th data-field="ma_work order.output package">Output package</th>
```

**Comment by henrysan96** [comment]
Hi djhvscf, I add the the bootstrap-table-flatJSON.js and set data-flat="true" but it is still the same. Here is my page http://www.cc.puv.fi/~e1400477/hei.html. Thanks for answering me.
![testing_bootstrap](https://cloud.githubusercontent.com/assets/11860138/7074499/34dbf83e-df25-11e4-99e9-4d073814ee2f.png)

**Comment by djhvscf** [comment]
Please put the reference of flatJSON after the reference of the boostrap-table file

**Comment by henrysan96** [comment]
![testing_bootstrap](https://cloud.githubusercontent.com/assets/11860138/7075284/ead189d8-df2a-11e4-8cde-129109ede646.png)
I put like you said but nothing showed up. Sorry for meshing things up.

**Comment by djhvscf** [comment]
See this:
http://jsfiddle.net/e3nk137y/1255/ 

I found the problem..

**Comment by djhvscf** [comment]
Ready https://github.com/djhvscf/bootstrap-table-flatJSON please update your js file

**Comment by henrysan96** [comment]
Hi, so I updated the flatJSON.js . So is there anything else I have to change? 
http://www.cc.puv.fi/~e1400477/hei.html

**Comment by djhvscf** [comment]
I think is not updated..

**Comment by djhvscf** [comment]
```html
<th data-field="ma_work order.0.customer">Customer</th>
<th data-field="ma_work order.0.material">Material</th>
<th data-field="ma_work order.0.work_name">Work</th>
<th data-field="ma_work order.0.patch_time">Time</th>
<th data-field="ma_work order.0.quantity">Quantity</th>
<th data-field="ma_work order.0.output package">Output package</th>
```

And then-- can you use the last version of bootstrap-table?? v1.7

**Comment by henrysan96** [comment]
I already used bootstrap-table version 1.7 and I changed what you told me.
http://www.cc.puv.fi/~e1400477/hei.html

**Comment by djhvscf** [comment]
![capture](https://cloud.githubusercontent.com/assets/4496763/7076086/28bfae1c-dec4-11e4-9d8f-b56ce792953e.PNG)

You are using the v1.6.. Just for help could you use the v1.7 but no the minified version.. just for debugging:)

**Comment by henrysan96** [comment]
I used the CDN so I don't recognize that it's 1.6 even though the link is 1.7. However, I updated it.
http://www.cc.puv.fi/~e1400477/hei.html

**Comment by djhvscf** [comment]
Thanks.. please update the flatJSON extension again.. sorry

**Comment by henrysan96** [comment]
So I updated it.
http://www.cc.puv.fi/~e1400477/hei.html

**Comment by djhvscf** [comment]
Ok, I think now it should work.. if not let me test it again I will update it until the issue is fixed

**Comment by henrysan96** [comment]
Okay thanks it's working right now. 
![testing_bootstrap](https://cloud.githubusercontent.com/assets/11860138/7076741/a9b1511c-df35-11e4-8ee1-bac27eb52ae5.png)
But when I change back to ma_work order.work_id . It doesn't show no matching records but displays nothing.

**Comment by djhvscf** [comment]
yes, that is because the flatJSON extension put an .0. so you have to use this format:

ma_work order.0.customer

**Comment by henrysan96** [comment]
So how do I display all of the datas not just 1 row?

**Comment by wenzhixin** [comment]
You can use responseHandler option.

**Comment by henrysan96** [comment]
Hi, I tried to do what you suggested but I don't know if I make some mistake here.
```
function responseHandler(res) {
    return res.ma_work order;
}
```

**Comment by djhvscf** [comment]
I think the function is not been added to the Window object.. check it the F12

**Comment by henrysan96** [comment]
Hi djhvscf, sorry for asking this, how can I do it? I tried to do like this but it didn't work: https://github.com/wenzhixin/bootstrap-table/issues/227

**Comment by henrysan96** [comment]
So I tried like this one, do I miss something here?
![testingbootstp](https://cloud.githubusercontent.com/assets/11860138/7087455/68b66a26-df94-11e4-82fe-1c82f21fb2aa.PNG)

**Comment by kapsyDev** [comment]
![capture](https://cloud.githubusercontent.com/assets/24729431/21448954/09f0e4ca-c90e-11e6-9d8b-8f12c9fada43.PNG)

I have this kind of json being return. How can i use this in data-url of bootstrap table

**Comment by wenzhixin** [comment]
You can try: `dataType: 'xml'`
