### ISSUE TITLE
Add possibility to change default classes for pageSize and pageList parts

### ISSUE THREAD

**Issue by AlexVanK** [wenzhixin/bootstrap-table#7133]
### Description

Just like it is possible to change the default toolbar classes:
https://bootstrap-table.com/docs/api/table-options/#buttonsclass

implement the possibility of changing the default classes for pageSize and pageList parts of the pagination module:

![image](https://github.com/wenzhixin/bootstrap-table/assets/56647386/ecd81d88-f94d-4fab-bda6-19347ca762e1)

**Comment by wenzhixin** [comment]
Not currently, but you can do so with custom CSS:
https://live.bootstrap-table.com/code/wenzhixin/16920
