### ISSUE TITLE
有左右滚动条和固定高度的情况下，列宽拖拽失效或错位！！！

### ISSUE THREAD

**Issue by 18539344511** [wenzhixin/bootstrap-table#7138]
### Bootstraptable version(s) affected

1.22.1

### Description

1.出现左右滚动条时，拖拽失效
![image](https://github.com/wenzhixin/bootstrap-table/assets/80297195/dd9e6edd-770e-4268-8ea3-1daa1a970cc3)
2.当给表格固定高度时，拖拽 列头失效
![image](https://github.com/wenzhixin/bootstrap-table/assets/80297195/c6cfce0e-4a14-4b23-bc29-5ddb173cc5ff)

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!
麻烦提供下在线的例子。

**Comment by UtechtDustin** [comment]
We got no example from you, so we have to close this issue.
If you still need help, please let us know and we will reopen it.

**Comment by 18539344511** [comment]
@wenzhixin 加一下微信吧 18539344511
