### ISSUE TITLE
Accessing Nested json via data-field attribute

### ISSUE THREAD

**Issue by meetconverge** [wenzhixin/bootstrap-table#714]
I am trying to access a nested json value for the data-field attribute.

```
{
   "version":"1.0",
   "encoding":"UTF-8",
   "feed":{
             "xmlns":"http://www.w3.org/2005/Atom",
             "xmlns$gsx":"http://schemas.google.com/spreadsheets/2006/extended",
     "category":[
         {
            "scheme":"http://schemas.google.com/spreadsheets/2006",
            "$term":"http://schemas.google.com/spreadsheets/2006#list"
         }
      ]
   }
}
```

If I wanted to get the value of $term as my data-field, what would I use? i did look over the documentation, and I couldn't find any mention of nested json values.

**Comment by djhvscf** [comment]
Use the flatJSON extension... http://issues.wenzhixin.net.cn/bootstrap-table/index.html#extensions/flatJSON.html

**Comment by meetconverge** [comment]
Is it just me or is that example blank?

**Comment by wenzhixin** [comment]
@meetconverge Are you using the `git clone` to get the examples? If not, you need to download bootstrap-table to assets/bootstrap-table.

**Comment by wenzhixin** [comment]
Use the flatJSON extension would solve your problem, close this issue.
