### ISSUE TITLE
Problem when exporting to excel, <thead> does not keep empty space and changes it to 0.

### ISSUE THREAD

**Issue by RodrigoEscAlm** [wenzhixin/bootstrap-table#7142]
### Description

Good morning,

I am making a table to export to excel, and when exporting the white spaces in the `<theat>` are converted to 0

I attach images of the table configuration and how it is displayed in Excel.

Thead declaration has the table-dark class `"<thead class='table-dark'>"`

and the values are displayed like this:
`
'<tr >'
'<th > <h6> valueName: '+value+"</h6></th>";
"</tr>"
`
When I want to leave a free space:
`"<th></th>";`
In Excel a 0 will appear in that cell.

Thanks in advance.

![excel problem](https://github.com/hhurz/tableExport.jquery.plugin/assets/92976649/920d1f32-dada-410b-bc09-2a6d58b56cdb)
![thead problem](https://github.com/hhurz/tableExport.jquery.plugin/assets/92976649/02d7ab90-ba3a-401a-867c-93d2fdcc96d0)

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!
