### ISSUE TITLE
How to add fields at the beginning or end in a table export to Excel.

### ISSUE THREAD

**Issue by RodrigoEscAlm** [wenzhixin/bootstrap-table#7143]
### Description

Good morning,

I would like to know if there is the possibility, when exporting the table to Excel, of attaching fields to the beginning and/or end of the table, such as the day, a title, that are loaded dynamically according to a variable.

Thanks in advance.

**Comment by wenzhixin** [comment]
Hello, you can check the documentation for the https://github.com/hhurz/tableExport.jquery.plugin repo first, and if it doesn't support it, you can submit the issue to that repo because we use this plugin for exporting.
