### ISSUE TITLE
How can we add a 'more/less' option if the text is long?

### ISSUE THREAD

**Issue by ShreeSoftech-Rupesh** [wenzhixin/bootstrap-table#7145]
### Description

I use Bootstrap Table in every project, and I love this library. I have one question: How can we add a 'more/less' option if the text is long?

![image](https://github.com/wenzhixin/bootstrap-table/assets/92097236/34593adb-bd8b-4e9c-ac09-acb3712b82d2)

**Comment by wenzhixin** [comment]
You can use the `text-overflow: ellipsis;` CSS style to solve your problem.
Online example: https://live.bootstrap-table.com/code/wenzhixin/16918

**Comment by ShreeSoftech-Rupesh** [comment]
Could you please add a feature to the code, such as data-text-limit=true, data-width="600", and data-width-unit="px"? If we set this, it means we will display limited text in the column, which would be very helpful for us

**Comment by wenzhixin** [comment]
I don't know if this feature needs to be added to the feature, but if anyone else needs it, consider adding it. See if anyone else reconsiders or agrees.
