### ISSUE TITLE
Could this function able to let me search by multiple column or data?

### ISSUE THREAD

**Issue by SuperBoy17** [wenzhixin/bootstrap-table#7146]
### Description

Good day sir, may I ask is there any way to able search different data with multiple text in a text field, for example: if I want search 2 or more data, in text field I put something like "abc,123" or "monkey,animal"?
![image](https://github.com/wenzhixin/bootstrap-table/assets/112933534/8beed8bf-6478-479f-ad32-581e7ddde630)

Thank you!

**Comment by wenzhixin** [comment]
Yes, you can use the `customSearch` option to define what you want.
An online example: https://live.bootstrap-table.com/code/wenzhixin/16919
![image](https://github.com/wenzhixin/bootstrap-table/assets/2117018/f017de43-3133-40c1-a218-b538c217ead0)
