### ISSUE TITLE
onclickrow  addclass highlight no effect

### ISSUE THREAD

**Issue by sleefd** [wenzhixin/bootstrap-table#715]
.highlight{
background: green;
}
$("#table").bootstraptable({
onClickRow:function(row, $element){
$element.addClass("highlight");
});

**Comment by dabros** [comment]
@sleefd 

I add events after, using jquery $.on sytax like:

``` javascript

$tt.on('click-row.bs.table', function (e, row, $element) {
    // When row is clicked
    $tt.find('tbody tr.active').removeClass('active info');
    $element.addClass('active info');

```

I have no issues with this, and the code is the same as if you ran it through the options {} on init

Can you please try changing your css to:

``` css 
.highlight{
background: green!important;
}
``` 

And also opening inspector with F12 and using spyglass (or similar tool in other browsers) to select that row and see if class applied but css just not showing for some reason?

**Comment by sleefd** [comment]
@dabros 
Thanks. It works with !important added. :)

**Comment by djhvscf** [comment]
Here an example http://issues.wenzhixin.net.cn/bootstrap-table/#563.html

**Comment by sleefd** [comment]
@dabros 
another problem came out.
when I change the pagination, then went back , the hightlight has no effect.
why?

**Comment by sleefd** [comment]
@dabros 
I guess when pagination changes , the data is loaded again, so the css is unavailable.

**Comment by djhvscf** [comment]
Exactly

**Comment by dabros** [comment]
@sleefd - sorry, i actually forgot i already fixed that in my own variation, but that was by adding an option value and setter getters and adding this line to initBody

``` javascript
if (that.options.activeItemId !== undefined
                && that.options.itemId !== undefined
                && item.hasOwnProperty(that.options.itemId)
                && item[that.options.itemId] == that.options.activeItemId) {
                // Append desired 'active' classes (if need, can pass these in as option)
                style["classes"] = ( (style.hasOwnProperty("classes")) ? style["classes"] : '' ) + ' info active ';
            }
```

You can see some of that in #678 , but your better off maybe persisting your last choice just in js outside of code

Something like:
``` javascript
var global = {'activeRow': null};

// and then later on using click-row.bs.table callback


$tt.on('click-row.bs.table', function (e, row, $element) {
    // When row is clicked
    $tt.find('tbody tr.active').removeClass('active info');
    $element.addClass('active info');
    global.activeRow = $element;
});

// then maybe (untested)
$tt.on('post-body.bs.table',function(){
  /// TODO - add matching conditions using stored $element in global.activeRow 
  $tt.find('tr ...').addClass('active info');
});
```
