### ISSUE TITLE
Continue for Issue Ticket #7146

### ISSUE THREAD

**Issue by SuperBoy17** [wenzhixin/bootstrap-table#7152]
### Description

Hi wenzhixin, thank you for the quick response, as I tried link you gave, unfortunately, it won't work for what I expected, is there any mistake I made? Thank You

![image](https://github.com/wenzhixin/bootstrap-table/assets/112933534/28f12ddb-aadf-4829-91b7-ce26819985bb)

**Comment by SuperBoy17** [comment]
My apologies, noted for future while continue the issue.

Could you show me some example how to configure that because the code only like that, if can I would like search for multiple data like above? Many thanks

![image](https://github.com/wenzhixin/bootstrap-table/assets/112933534/76428c49-0ce1-4842-8bb2-01cd71ac6638)

**Comment by wenzhixin** [comment]
Here is the example: https://live.bootstrap-table.com/code/wenzhixin/16919
You need to define your own customSearch to implement the logic you want.

```js
<table
  id="table"
  data-search="true"
  data-custom-search="customSearch"
  data-url="json/data1.json">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Item Name</th>
      <th data-field="price">Item Price</th>
    </tr>
  </thead>
</table>

<script>
  $(function() {
    $('#table').bootstrapTable({
      formatSearch: function () {
        return 'Search (name,price)'
      }
    })
  })

  function customSearch(data, text) {
    if (!text) {
      return data
    }
    
    const [name, price] = text.split(',')
    
    return data.filter(function (row) {
      return row.name.includes(name || '') && row.price.includes(price || '')
    })
  }
</script>
```
