### ISSUE TITLE
onSort event is not working on live in version 1.22.2. and latest version

### ISSUE THREAD

**Issue by bankotigaurav** [wenzhixin/bootstrap-table#7154]
### Bootstraptable version(s) affected

1.22.2

### Description

I am using onSort method. Suddenly its not working now. is this method deprecated now?

```

  $('#audience-list').bootstrapTable({
            data: res.map.OBJECT && res.map.OBJECT.list ? res.map.OBJECT.list : [],
            totalRows:res.map.OBJECT && res.map.OBJECT.count ? res.map.OBJECT.count : 0,
            totalNotFiltered:res.map.OBJECT && res.map.OBJECT.count ? res.map.OBJECT.count : 0,
            theadClasses: 'thead-light',
            onPageChange: (number,size)=>{
                let req = {
                    type: 'page',
                    offset: 20*(number-1),
                    sortKey: null,
                    sortType: null
                }
                this.onOutputEvent(req);
            },
            onSort: (name,order)=>{
                let req = {
                    type: 'page',
                    offset: 0,
                    sortKey: name,
                    sortOrder: order
                }
                this.onOutputEvent(req);
            },
```
```

### Example(s)

_No response_

### Possible Solutions

_No response_

### Additional Context

_No response_

**Comment by wenzhixin** [comment]
Verified that it works appropriately: https://live.bootstrap-table.com/code/wenzhixin/16937

**Comment by bankotigaurav** [comment]
But its not working the way I am using it. I am creating the table through typescript

    columns: [
              {
                field: 'audienceName',
                title: 'NAME1',
                sortable: true,
                formatter: (_,row)=>{
                  if(row !== undefined){
                    return '<a class="text-link txt-color" href="/audience/refine/'+row.id+'"> '+row.audienceName+'</a>';
                  }
                }
              },
              {
                field: 'uniqueCompanies',
                title: 'COMPANY LOCATIONS',
                sortable: true,
                formatter: (_,row)=>{
                    return (row.uniqueCompanies || row.uniqueCompanies === 0) ? this.thousandSeperatorPipe.transform(row.uniqueCompanies) : "";
                }
              },

**Comment by wenzhixin** [comment]
Using columns is working too: https://live.bootstrap-table.com/code/wenzhixin/16939
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem.

**Comment by bankotigaurav** [comment]
Hi wenzhixin ! Any update on the issue?

**Comment by wenzhixin** [comment]
Your example cannot work.

**Comment by wenzhixin** [comment]
You can help to debug the source code to find your problem.

**Comment by wenzhixin** [comment]
I'm closing this issue because I don't think it's a bug. If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!

**Comment by codethisio** [comment]
It only seems to work if side-pagination is "client". If using server pagination, the onSort event doesn't seem to fire.
