### ISSUE TITLE
When data-mobile-responsive="true" the data-filter-control="select" does not work in Chrome and Edge (but works in Safari)

### ISSUE THREAD

**Issue by thiazzz** [wenzhixin/bootstrap-table#7155]
### Bootstraptable version(s) affected

1.22.2

### Description

in the settings of a table I had the following:

data-mobile-responsive="true" 

and I'm using a data-filter-control="select"  on a table.

This works in Safari, but apparently not in Chrome and Edge.

I found based on trial-and-error that when I put:
data-mobile-responsive="false"

the filters do work.

**Comment by wenzhixin** [comment]
It works in Chrome. Please confirm it: https://live.bootstrap-table.com/code/wenzhixin/16938.

**Comment by wenzhixin** [comment]
Close this issue because there has been no response. If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!
