### ISSUE TITLE
Values of first column are not printed when data-fields are not specified

### ISSUE THREAD

**Issue by serra** [wenzhixin/bootstrap-table#7157]
### Bootstraptable version(s) affected

1.22.2

### Description

When creating an html table and adding the printing extension, the data of the first column is not printed (the column header is printed).

Workaround is to specify unique data-field attributes for each column.

### Example(s)

See https://live.bootstrap-table.com/code/serra/16958 for the code for a html page that reproduces the issue.

Please note that the online editor hides the problem; please save the code in an html file and open it locally.

https://github.com/wenzhixin/bootstrap-table/assets/285398/983e8cc6-9f4f-4c26-b696-cb9222504f6e

### Possible Solutions

Adding a unique `data-field` attribute to each column is a work-around for this bug.
But this is not documented, and even when documented, it should not be necessary. 

### Additional Context

tested on Brave 1.61.116 only

**Comment by wenzhixin** [comment]
Fixed in #7160
