### ISSUE TITLE
能选中合并任意单元格吗

### ISSUE THREAD

**Issue by Yaphats** [wenzhixin/bootstrap-table#716]
我想要合并选中的任意单元格,或者啥办法可以获取到某个cell的数据,所属行跟列吗?
还有拆分单元格功能有考虑吗

**Comment by wenzhixin** [comment]
目前不支持，只有一个 `mergeCells` 方法。

**Comment by Yaphats** [comment]
恩 我知道有个mergeCells方法   我试着用了下  也不是很好用
如果已经有合并的单元格了  再合并的话就会出问题 表格就乱了
$table.bootstrapTable('mergeCells', {
                index: 0,
                field: 'name',
                colspan: 2,
                rowspan: 1
            });
 {
                index: 1,
                field: 'name',
                colspan: 2,
                rowspan: 1
            }

 {
                index: 0,
                field: 'name',
                colspan: 1,
                rowspan: 2
            }

这样表格就乱了

**Comment by wenzhixin** [comment]
是的，目前不支持。
