### ISSUE TITLE
incorrect information in documentation

### ISSUE THREAD

**Issue by harshgpt816** [wenzhixin/bootstrap-table#7162]
### Description

The text "Defines icon set name ('glyphicon' or 'fa' for FontAwesome). By default, 'fa' is used for Bootstrap v4."

should actually be "Defines icon set name ('glyphicon' or 'fa' for FontAwesome). By default, 'fa' is used for FontAwesome"

Detail:
 - while working on https://bootstrap-table.com/docs/api/table-options/  I observed the icons were not coming, I use bootstrap-icon, which uses 'bi' .

Ask:
- Please correct the typing mistake in documentation such that it clearly states that bootstrap-table uses 'fa' and not 'bi' by default.

**Comment by wenzhixin** [comment]
Thanks for your feedback!
