### ISSUE TITLE
Icon initialization ignores configures icon prefix

### ISSUE THREAD

**Issue by gonozalviii** [wenzhixin/bootstrap-table#7165]
### Bootstraptable version(s) affected

1.22.2

### Description

When configuring iconPrefix, the prefix is not taken into account for the icon itself.

### Example(s)

I'm on bootstrap 5 and want to use font awesome. I am configuring the iconPrefix to be "fa". The resulting icon for example the clear-search-button is "fa bi-trash".

### Possible Solutions

The item prefix should be used when initializing the icons.
`
        // init iconsPrefix and icons
        const iconsPrefix = opts.iconsPrefix || Utils.getIconsPrefix($.fn.bootstrapTable.theme)
`

**Comment by wenzhixin** [comment]
You need to define the icons you are using, for example:
```js
{
  iconsPrefix: 'fa',
  icons: {
    refresh: 'fa-refresh',
    toggle: 'fa-toggle-on',
    columns: 'fa-th-list',
    detailOpen: 'fa-plus-square-o',
    detailClose: 'fa-minus-square-o'
  }
}
```

**Comment by gonozalviii** [comment]
They are already defined under the fa prefix, that gets used for bootstrap 4, I don't see why I should define them again. The initialisation should just pay attention the the prefix I provide. So when I say my prefix is "fa" it should pull the fa-icons and not the bi-icons like it is doing now. It is a minimal code change I posted above.
