### ISSUE TITLE
Button group within custom toolbar

### ISSUE THREAD

**Issue by Jack-Bristow** [wenzhixin/bootstrap-table#7168]
### Description

Is there any way I can use the table open data-buttons to create a dropdown button group? I have achieved this task by using the custom html option, but was wondering if there's a way I'm missing to have the HTML autogenerated rather than using custom HTML.

### Example(s)

Current button function:

```
function buttons() {
    return {
        btnGroup: {
            html:
            `<div class="btn-group"><button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-download"></i></button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" onclick="exportTableToCSV('#'+$(this).closest('.bootstrap-table').find('table').attr('id'))", 'export')"><i class="bi bi-filetype-csv"></i> CSV</a></li>
                    <li><a class="dropdown-item" onclick="exportTableToText('#'+$(this).closest('.bootstrap-table').find('table').attr('id'))", 'export')"><i class="bi bi-file-earmark-text"></i> Fixed width</a></li>
                </ul>
            </div>`
        }
    };
}

**Comment by wenzhixin** [comment]
Currently, only a single button is supported, and button groups are not supported. However, they can be processed with the `html` option, like what you implemented. 

If many people need this feature, I will consider adding it as a feature.

**Comment by hepcat72** [comment]
Would love to have this option. I implemented my own button outside the BST toolbar to achieve it.
