### ISSUE TITLE
Formatter calling

### ISSUE THREAD

**Issue by dfajtai** [wenzhixin/bootstrap-table#7175]
### Description

I am working on a project where I would like to implement a locking mechanism to ensure data integrity.

To indicate a resource ( a row in a bootstrap-table ) is being locked I added a column with a simple formatter:

> function subject_lock_formatter(value,row){
>     if(active_subject_locks.includes(row["SubjectIndex"])){
>         return $("<span/>").addClass("bi bi-lock-fill text-danger").prop("outerHTML");
>     }
>     return $("<span/>").addClass("bi bi-unlock-fill text-success").prop("outerHTML");
> }

... and so for the checkbox

> function subject_checkbox_formatter(value,row, index){
>     if(active_subject_locks.includes(row["SubjectIndex"])){
>         return {disabled: true, checked:false}
>     }
>     return {disabled: false};
> }

As you can see, my implementation relies on a global variable, called "**active_subject_locks**" which contains the ID of the "locked resources" - that is identified by "**SubjectIndex**" in this particular example.

The global variable is updated by an effective ajax call every 5 seconds. This works fine, however I need to call a bootstrap-table function to trigger the formatter somehow. 

I have tried several ways:

1. table.bootstrapTable("refreshOptions",{}) -> _this will result in a new database request which is quite un-efficient - however pagination and search remains untouched_
2. table.bootstrapTable("filterBy",{}) -> _this resets paging and detail view - however data request is not repeated_
3.  table.bootstrapTable("resetView") -> _not calls the formatter...._
4. table.bootstrapTable("resetSearch") -> _like option 2._

So the question is:
**How to call / re-call the column formatters manually?**

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by dfajtai** [comment]
Here is an example. I have tried my best to mimic the case I explained above.

https://live.bootstrap-table.com/code/dfajtai/17087

**Comment by dfajtai** [comment]
I have updated the example.
https://live.bootstrap-table.com/code/dfajtai/17113

**Comment by wenzhixin** [comment]
I think the `refresh` method can help you.
https://live.bootstrap-table.com/code/wenzhixin/17118
