### ISSUE TITLE
bootstrap-table-mobile toggle does not respect change from outside of plugin

### ISSUE THREAD

**Issue by maxgrass** [wenzhixin/bootstrap-table#718]
A thought about manual toggle vs/plus auto-toggle.

The var `toggled` saves not the state but the event occurrence, so toggling with the toggle BUTTON (or programmatically) will toggle the table and then when automatic/mobile toggle kicks in it does not consider the static/button toggle i.e. the actual state of the table.

Repro:

mobileResponsive: true,
showToggle: true

- minimize the window, so table toggles into the cardView.
- click on toggleView button.
- maximize the window

Expected:

as mobile constraint states
`toggle INTO CARDVIEW should happen, iff WIDTH <= MINWIDTH`
by MAXIMIZING the window `width>minwidth` so the "table must not switch into the cardView"

Happens:

on maximize table switches into cardView

Solution:

as cardView toggle is already supported in "main"-module, it should be managed from there. Meaning saving a `private STATE` variable which can be toggled only by enableCardView() and disableCardView() (or simpler toggle(true), toggle(false) ) and mobile-plugin must use these.

http://jsfiddle.net/ppcr48vn/

**Comment by maxgrass** [comment]
@djhvscf

**Comment by djhvscf** [comment]
Yes, you're right.. let me fix it!!

**Comment by wenzhixin** [comment]
Is this the sample problem with #721?

**Comment by maxgrass** [comment]
looks same, but I forked it on jsfiddle

**Comment by wenzhixin** [comment]
Please update the code and check it out. @maxgrass

**Comment by maxgrass** [comment]
well, jsfiddle takes the source code directly, I've checked out cee2bb0130c3fe87a93a4443a8b7bc9d80ae95f2 locally as well
and the toggle still broken, 

because on condition change toggle happens if NEW state != OLD state which always true.

**Comment by djhvscf** [comment]
See this: https://github.com/djhvscf/bootstrap-table/commit/2588a5eb59c278d49f717b8374b37d2644757b23

**Comment by maxgrass** [comment]
tested, it works ✅

**Comment by wenzhixin** [comment]
Merged!
