### ISSUE TITLE
How to pass composite key to X-editable plugin?

### ISSUE THREAD

**Issue by bounlu** [wenzhixin/bootstrap-table#7181]
I am using X-editable 1.5.3 with Bootstrap5 and it works fine with editable fields with a single primary key.

X-editable [doc](http://vitalets.github.io/x-editable/docs.html#editable) says it supports composite keys to pass to DB as an object with multiple values for `pk` parameter:

`{id: 1, lang: 'en'}`

Currently I have it for single key as below:

`data-id-field="id"`

```
<th data-field="id" data-editable="true">ID</th>
<th data-field="lang" data-editable="true">Lang</th>
```

How can I pass multiple keys in bootstrap table parameters using `data-id-field`? i.e. `id` + `lang`

**Comment by wenzhixin** [comment]
Not now, but you can set it up in the following ways.
https://live.bootstrap-table.com/code/wenzhixin/17288

<img width="523" alt="image" src="https://github.com/wenzhixin/bootstrap-table/assets/2117018/49c2f7bb-26fd-4ce2-b871-2d14f83af775">
