### ISSUE TITLE
Scrolling Columns vertical

### ISSUE THREAD

**Issue by dermatzeimnetz** [wenzhixin/bootstrap-table#7183]
### Description

Hello, Id like to add 100 columns, but only 10 of them can be viewed on screen. By clicking on an arrow to the right, the table shows then columns 2-12, another time i click on it, the table shows columns 3-13.
Is that possible?

**Comment by wenzhixin** [comment]
The table does not support this feature, but you can use the javascript (or jQuery) to do what you want: https://live.bootstrap-table.com/code/wenzhixin/17277.
