### ISSUE TITLE
bootstrap-table-mobile toggle doesn't work with multiple tables

### ISSUE THREAD

**Issue by maxgrass** [wenzhixin/bootstrap-table#719]
Repro:
two tables with
mobileResponsive: true

http://jsfiddle.net/maxgrass/0xctquf6/

Expected:
both in cardView

Happens:
only first in the cardView

@djhvscf

**Comment by murphmar** [comment]
Just took a quick look, I'd imagine it's because 'toggled' is a var declared at the top of the extension and isn't tied to any specific table. It should probably be a table-specific property and passed from changeView() (as el.options.toggled?) to checkToggledStatus.

**Comment by djhvscf** [comment]
Great!! thanks a lot @murphmar

**Comment by wenzhixin** [comment]
Great, merged!
