### ISSUE TITLE
 Multiple Select Row not selecting multiple rows

### ISSUE THREAD

**Issue by umefarooq** [wenzhixin/bootstrap-table#7199]
### Bootstraptable version(s) affected

1.22.2

### Description

 Multiple Select Row not selecting multiple rows. I thought it is not working with my table but i try example script it not working on example also

https://examples.bootstrap-table.com/index.html#options/multiple-select-row.html

**Comment by umefarooq** [comment]
Any help team?

**Comment by wenzhixin** [comment]
You can use the `ctrl+click` to select one row or `shift+click` to select a range of rows.

**Comment by wenzhixin** [comment]
You can use the `ctrl+click` to select one row or `shift+click` to select a range of rows.

**Comment by wenzhixin** [comment]
You can use the `ctrl+click` to select one row or `shift+click` to select a range of rows.

**Comment by wenzhixin** [comment]
If Multiple Select Row is not enabled, it should behave like a normal checkbox, regardless of whether you press Ctrl.
