### ISSUE TITLE
OData

### ISSUE THREAD

**Issue by michaelsogos** [wenzhixin/bootstrap-table#72]
Hi,

Great plugin, really!

I question, can you give us the support for OData? I mean the queryParams could have a default set of parameter already compatible for OData api?

**Comment by abh30** [comment]
Hi wenzhixin,
On similar lines, can you please guide me on setting a default/initial value for a filter field if i am using bootstrapFilterTable (bootstrap-table-filter.js))?

filters:[
                {
                    field: 'id',
                    label: 'Item ID',
                    type: 'select',
                    values: [
                        {id: '0', label: '0'},
                        {id: '1', label: '1'},
                        {id: '2', label: '2'}
                    ]
                }

in the above filter, i need to set lets ssay id 1 as selected by default when the page loads.
