### ISSUE TITLE
Advanced search columns do not refresh upon switching tab panes

### ISSUE THREAD

**Issue by bounlu** [wenzhixin/bootstrap-table#7208]
### Bootstraptable version(s) affected

1.22.1

### Description

When using Tab panes with a different Bootstrap table in each pane with Advanced search on, the columns in the Advanced search do not refresh when switching from one tab to another. It only refreshes when the page is refreshed.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by bounlu** [comment]
I found out that this was due to the same `data-id-table` name I was using across the tabs. I copy pasted from the [example](https://examples.bootstrap-table.com/#extensions/toolbar.html#view-source) the same id for all the different tabs:

`data-id-table="advancedTable"`

Once I gave a different ID for each tab, it worked as expected:

```
data-id-table="tab1"
data-id-table="tab2"
data-id-table="tab3"
data-id-table="tab4"
```
