### ISSUE TITLE
`data-filter-control-multiple-search` do not work

### ISSUE THREAD

**Issue by bounlu** [wenzhixin/bootstrap-table#7209]
### Bootstraptable version(s) affected

1.22.1

### Description

Setting `data-filter-control-multiple-search` to `true` does not allow to search multiple values at once separated by comma. Instead it returns nothing found.

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by UtechtDustin** [comment]
Works fine for me, please check this [demo](https://live.bootstrap-table.com/code/UtechtDustin/17710).
If you search for `Item 0,Item 2` you will find three results `Item 0`, `Item 2` and `Item 20`.
Also we go not no example from you as @wenzhixin asked for.
If you still need help please provide us an example.
