### ISSUE TITLE
Sticky column break, when multiple column use the same field

### ISSUE THREAD

**Issue by gonozalviii** [wenzhixin/bootstrap-table#7215]
### Bootstraptable version(s) affected

1.22.3

### Description

I have configured 1 sticky column right, where I use a field "status" and a special formatter to display the status in color.
But I have another column that is not sticky that also uses "status" without a formatter.
So 2 column use the same field, one of them should be sticky.

The selecter in https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/fixed-columns/bootstrap-table-fixed-columns.js#L275 fetches the first column and uses its outerwidth instead of the second column which is sticky resulting in the sticky column to be too wide and displaying more than the last column as sticky.

### Possible Solutions

It might be better to not select the the column by "data-field", but to select all columns in the header (reverse it for 'isRight) and then iterate over over them to get the width.

`this.$header.find("th").get().reverse()`

**Comment by UtechtDustin** [comment]
We will close this issue as we got no response from you, if you still need help please provide us an example as @wenzhixin described.   
Btw. you should avoid using two columns with the same field name.
