### ISSUE TITLE
Add attribute

### ISSUE THREAD

**Issue by SuperBoy17** [wenzhixin/bootstrap-table#7224]
### Description

Hi, is there any possible add extra attribute for the checkbox? just to add value attribute for the checkbox column, thanks

### Example(s)

![image](https://github.com/wenzhixin/bootstrap-table/assets/112933534/e2fe037f-a560-47bd-8296-82e5eaf92d9b)
![image](https://github.com/wenzhixin/bootstrap-table/assets/112933534/7ae80987-fd14-4517-b3cf-4139c4f48e58)
![image](https://github.com/wenzhixin/bootstrap-table/assets/112933534/2410a3ea-c8b5-415c-8084-8010c81683f1)

**Comment by wenzhixin** [comment]
The `idField` option can do what you want: https://live.bootstrap-table.com/code/wenzhixin/17287.

> Another question: is there possible capture all id if there is any ticked checkbox?

Yes.
