### ISSUE TITLE
How to highlight different cells between rows?

### ISSUE THREAD

**Issue by bounlu** [wenzhixin/bootstrap-table#7227]
### Description

I want to keep track of changes in a table after editing. I managed to do this by using `SYSTEM VERSIONING` on the database part and displaying it on a modal on the webpage. Now I want to highlight the cells in each row that are different than the previous row. How to achieve this? `rowStyle` and `cellStyle` only works with the current row in a table.

### Example(s)

For example:

**Name | Code | Category | Color | Site | UserName**
**ABD** | ABC_1 | **test** | red | T3 | omeran
ABC | ABC_1 | control | red | **T3** | omeran
ABC | ABC_1 | control | red | T2 | omeran

In the above table, I want to highlight **ABD** and **test** in the first row, and **T3** in the second row as they are different from the previous row (going from bottom to up).

**Comment by bounlu** [comment]
Thanks @wenzhixin 

However your example does not work for me. I need `cellStyle` function to remember the previous row and check if any value has changed. In your case, you input the values or index yourself.

**Comment by wenzhixin** [comment]
Maybe you can save the previous row to the current row for check.

**Comment by bounlu** [comment]
Ok I achieved this without `cellStyle` attribute with the below function (thanks to ChatGPT haha):

```
var tableVersionHistory = $('#tableVersionHistory');
var rowCount = tableVersionHistory.find('tr').length;

for (var rowIndex = rowCount - 2; rowIndex > 0; rowIndex--) {
    tableVersionHistory.find('tr:eq(' + rowIndex + ') td:not(:last-child)').each(function(cellIndex) {
        var currentValue = $(this).text();
        var nextRowValue = tableVersionHistory.find('tr:eq(' + (rowIndex + 1) + ') td:not(:last-child)').eq(cellIndex).text();
        if (currentValue !== nextRowValue) {
            $(this).css('background-color', 'yellow');
        }
    });
}
```
