### ISSUE TITLE
Pagination and toolbar in the same line

### ISSUE THREAD

**Issue by ctessandri** [wenzhixin/bootstrap-table#7231]
### Description

Hallo, it would be useful to put pagination section and toolbar on the same line, just to save space when there are few buttons and only few parts of pagination section are shown.
A new grid property would be nice.
Or is it already possible?
Thank you

**Comment by wenzhixin** [comment]
You can customize the style to do this: https://live.bootstrap-table.com/code/wenzhixin/17316.
