### ISSUE TITLE
Support user's abiliity to add custom icons

### ISSUE THREAD

**Issue by manhbi18112005** [wenzhixin/bootstrap-table#7233]
### Description

After trying to add custom icons via the **icons** and **iconsPrefix** attribute, I keep getting the error
```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
```

I figured that because this function **`bootstrapTable.utils.getIconsPrefix`** only returns a list of predefined icon packs like "bi", "fa", ...
```js
getIconsPrefix: function(t) {
            return {
                bootstrap3: "glyphicon",
                bootstrap4: "fa",
                bootstrap5: "bi",
                "bootstrap-table": "icon",
                bulma: "fa",
                foundation: "fa",
                materialize: "material-icons",
                semantic: "fa"
            }[t] || "fa"
        }
``` 
I think it would be much better for users to freely add their favorite icon packs. I have managed to use tabler-icons on my websites so I can also make a pull request for this feature here.

**Comment by UtechtDustin** [comment]
I'm not sure what do you mean.   
You can change the icon class using the [icons](https://bootstrap-table.com/docs/api/table-options/#icons) option and the prefix using the [iconPrefix](https://examples.bootstrap-table.com/#options/icons-prefix.html) option.

Please provide us an example, thanks ! :)

**Comment by manhbi18112005** [comment]
For example I am using tabler-icons with prefix **ti**, maybe an example is **ti ti-x**. 
```js
$('#grade-table').bootstrapTable({
        iconsPrefix: "ti",
        icons: {...}
})
```
However when I set [iconPrefix](https://examples.bootstrap-table.com/#options/icons-prefix.html) as "ti" it returns the following error.
```js
bootstrap-table.min.js:10  Uncaught TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at e.value (bootstrap-table.min.js:10:65959)
    at e.value (bootstrap-table.min.js:10:65315)
    at HTMLTableElement.<anonymous> (bootstrap-table.min.js:10:135901)
    at Function.each (jquery.min.js:2:2976)
    at S.fn.init.each (jquery.min.js:2:1454)
    at t.fn.bootstrapTable (bootstrap-table.min.js:10:135445)
    at HTMLInputElement.<anonymous> (<anonymous>:6:40)
    at HTMLInputElement.dispatch (jquery.min.js:2:43090)
    at v.handle (jquery.min.js:2:41074)
```

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by manhbi18112005** [comment]
Here is an example: https://live.bootstrap-table.com/code/manhbi18112005/17329
