### ISSUE TITLE
sort.bs.table event not triggered when sorting from server

### ISSUE THREAD

**Issue by merinosky** [wenzhixin/bootstrap-table#7252]
### Bootstraptable version(s) affected

1.22.4

### Description

As far as I know the 'onSort' event (or 'sort.bs.table' jquery event in my case) should be triggered anytime user sorts a column, whether the sorting is performed by the client or the server. But it actually does not.

Not sure if this behaviour is normal and documentation does not state it, but would not the event be triggered regardless where it is executed on?

### Examples

Here the table is sorted by the client and the sort event is triggered
https://live.bootstrap-table.com/code/merinosky/17357
Here the table is sorted by the server and the sort event **is not** triggered
https://live.bootstrap-table.com/code/merinosky/17358

**Comment by wenzhixin** [comment]
It's a bug caused by #7038.
