### ISSUE TITLE
Virtual Scroll in Modal

### ISSUE THREAD

**Issue by timothy-lassiter** [wenzhixin/bootstrap-table#7276]
### Bootstraptable version(s) affected

1.22.4

### Description

Scrolling does not work when virtual scroll is enabled and the table is placed in a modal. Number of rows must be >= BLOCK_ROWS for the bug to appear.

### Example(s)

[Bug](https://live.bootstrap-table.com/code/timothy-lassiter/17470)
[Working Solution](https://live.bootstrap-table.com/code/timothy-lassiter/17471)

### Possible Solutions

The problem seems to stem from the `getRowsHeight` function. It sets the `itemHeight` to 0 when the table is in a modal. When `itemHeight` is 0 it results in the `blockHeight` and `clusterHeight` both being 0. This results in the `getNum` function returning Infinity which results in the bug. My fix below is fairly simple but I haven't thoroughly tested it. I'm not sure what else it may affect.

[Simple Fix](https://github.com/timothy-lassiter/bootstrap-table/commit/a9f781b166f4e6b451fdc0a85075d9908526ace9)

**Comment by wenzhixin** [comment]
Thanks for your information, create a PR: #7297.
