### ISSUE TITLE
image zoom not appearing above table element

### ISSUE THREAD

**Issue by Scnck** [wenzhixin/bootstrap-table#7285]
### Description

trying to get image appear above table but unable to get the css correct any idea what I'm doing wrong?

![image](https://github.com/wenzhixin/bootstrap-table/assets/17710395/25df9256-655d-46c0-8edf-2cf0c6996845)

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by wenzhixin** [comment]
Close this issue because there has been no response. If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!
