### ISSUE TITLE
Custom parameters with AddrBar

### ISSUE THREAD

**Issue by codethisio** [wenzhixin/bootstrap-table#7288]
### Description

Hello,

Is it possible to use AddBar with custom parameters? I have a multi-select with filter options that I use to update the table using server-side pagination. The table refreshes with the correct filtered data. However, the URL does not update with the custom selected filter parameters.

I also tried updating the URL parameters manually, but when the grid refreshes, it overwrites the parameters.

I use this function to update the table and force a refresh:

    Tables.UpdateQueryParams = function (customParams) {
        Tables.TableElement.bootstrapTable("refreshOptions", {
            queryParams: function (params) {
                return $.extend(params, customParams);
            }
        });
    };

Thanks for your help.

<img width="1012" alt="image" src="https://github.com/wenzhixin/bootstrap-table/assets/5332720/81c20b65-43e4-4751-99a1-9a983524941e">

**Comment by wenzhixin** [comment]
This feature is not currently supported in the extension but may be available as a new feature.

**Comment by codethisio** [comment]
> I use this function to update the table and force a refresh:

Thank you for the confirmation!

**Comment by 6tronl** [comment]
@codethisio Hi, How did you manage to use a multi-select with filter controls on the table please?
