### ISSUE TITLE
Support subfields

### ISSUE THREAD

**Issue by meetraz** [wenzhixin/bootstrap-table#729]
I am using bootstrap-table with hierarchical json data.  Some properties are strings, and some are subobjects. Right now I can do in my column, data-field="something" and if that field is a string value, it works.  But if that field is an object, I'd like to do data-field="something.name" so that it fetches the "name" property of the something object.  Unfortunately, this doesn't work and it forces me to use a new formatter for every field.

**Comment by dabros** [comment]
@meetraz - the something.name is only a shortcut, you can just as easily use formatter option for that column, and have that formatter semi-generic to easily print the contents of certain objects differently based on column name, or print all others with interator

For example (tested and working):

``` javascript
// Generic formatter function that uses name to determine action
function my_tablerow_object_formatter(value, row, index, name, context) {

    /// 
    console.log('my_tablerow_object_formatter', [value, row, index, name, context]);

    var str = "";
    switch (name) {
        case "y":
            str = "<span class='text-muted'>" + value.one + "</span><br/><span class='text-primary'>" + value.two + "</span>";
            break;
        default:
            $.each(value, function (value_i, value_val) { str += "<span class='clearfix'><label>" + value_i + "</label> <span class='text-muted'>" + value_val + "</span></span>"; });
            break;
    }
    return str;
} 
```

**Comment by wenzhixin** [comment]
Use flat-json extension please @meetraz, http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/flat-json.html
