### ISSUE TITLE
GroupBy

### ISSUE THREAD

**Issue by michaelsogos** [wenzhixin/bootstrap-table#73]
Hi,

Can you give us the functionality to group by a column?

It is very usefull for "enterprise-level" web app.

**Comment by djhvscf** [comment]
Do you mean something like this? http://www.datatables.net/release-datatables/extensions/ColVis/examples/group_columns.html 

@michaelsogos @pikaleize

**Comment by pikaleize** [comment]
@djhvscf Thanks for showing me ColVis example. But "grouping by" I mean that we have a table of students and I want to group students by class compare average GPA by classes.

**Comment by djhvscf** [comment]
Something like: http://jsfiddle.net/e3nk137y/1210/ ??

**Comment by pikaleize** [comment]
@djhvscf  something like this, http://jsfiddle.net/e8ysxdwL/
"grouping by name" will aggregate records with same name (e.g., "bootstrap-table") and aggregate the numerical column value by sum (or other reduce function)
apparently, the given code does not do that.

Also, I'm curious, it seems like "groupBy" is not documented in bootstrapTable. How did you do that?

**Comment by djhvscf** [comment]
Ok, got it.. And the code is because I'm developing the extension to do that.. the group by :) @pikaleize

**Comment by kryptonianson** [comment]
Any movement on this? I really need this functionality and it would be fantastic to have. Thank you!

**Comment by wenzhixin** [comment]
Merged this feature

**Comment by MKHARRAT** [comment]
J'utilise bootstrap-table/extensions/group-by/bootstrap-table-group-by.js (version1.1.0), j'ai trouvé une erreur lors du groupement des données (création d'un seul group) au lieu de plusieurs groupe ma colonne est nommée ('FirstName').

J'ai vérifié le groupement avec la version 1.0.0 de l'extension groupby et elle donne le résultat demandé.

J'ai vérifie la dernière version  et comparer le code pour corriger l'erreur et j'ai trouvé :

    BootstrapTable.prototype.initData = function (data, type) {
        //Temporal validation
        if (!this.options.sortName) {
            if ((this.options.groupBy) && (this.options.groupByField.length > 0)) {

                this.options.groupByField = typeof this.options.groupByField === 'string' ?
                    this.options.groupByField.replace('[', '').replace(']', '')
                        .replace(/ /g, '').toLowerCase().split(',') : this.options.groupByField;

                data = makeGrouped(this, data ? data : this.options.data);
            }
        }
        _initData.apply(this, [data, type]);
    };

résultat =>  erreur de groupement pour une colonne qui contient des majiscule au milieu

Cette anomalie est corrigée:

    BootstrapTable.prototype.initData = function (data, type) {
        //Temporal validation
        if (!this.options.sortName) {
            if ((this.options.groupBy) && (this.options.groupByField.length > 0)) {

                this.options.groupByField = typeof this.options.groupByField === 'string' ?
                    this.options.groupByField.replace('[', '').replace(']', '')
                        .replace(/ /g, '')/*.toLowerCase()*/.split(',') : this.options.groupByField;

                data = makeGrouped(this, data ? data : this.options.data);
            }
        }
        _initData.apply(this, [data, type]);
    };

Est ce que vous pouvez intégrer cette modification dans le code?

**Comment by MKHARRAT** [comment]
Est ce que vous pouvez ajouter les fonctions d’agrégation par colonne (somme, count, ecart) est les afficher sur la colonne parente?
