### ISSUE TITLE
bootstrap-table/1.7.0/bootstrap-table.min.js

### ISSUE THREAD

**Issue by gurumark** [wenzhixin/bootstrap-table#730]
The file content in the CDN is incorrecty says 1.7.0. It is 1.6. version but the file name is 1.7.
 https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.7.0/bootstrap-table.min.js

It creates all sorts of issues.

**Comment by wenzhixin** [comment]
Thanks for your feedback, it seems the files are added error. 
Ref https://github.com/cdnjs/cdnjs/pull/4510

**Comment by wenzhixin** [comment]
Will fix in next version.
