### ISSUE TITLE
How to use filter-control to search records between two dates

### ISSUE THREAD

**Issue by merinosky** [wenzhixin/bootstrap-table#7301]
### Description

Let's say my table has a "Date" column and I want to filter records between two given dates. Besides the filter date inputs must be outside the table. I have tried to achieve this by creating two filters like these:

```
<div id="filterDateFrom">
    <input type="date" id="inputFilterDateFrom" class="bootstrap-table-filter-control-dateFrom"></input>
</div>
<div id="filterDateTo">
    <input type="date" id="inputFilterDateTo" class="bootstrap-table-filter-control-dateTo"></input>
</div>
```
and defining the table like this:
```
<table id="tableWithDates" class="table"
			data-toggle="table"
			data-side-pagination="server"
			data-filter-control="true"
			data-filter-control-container="#filterDateFrom"
			data-filter-control-container="#filterDateTo">
```				
And the date columns like this:
```
<th data-field="dateFrom" data-searchable="false" data-filter-control="datepicker"></th>
<th data-field="dateTo" data-searchable="false" data-filter-control="datepicker"></th>
```
Inputs are displayed properly, but nothing happens when I change date inputs.

1- Do I need to trigger manually the filter event? If so, why? Select filters are triggered when they change.
2- As you see I have included two `data-filter-control-container` options, but I don't know if that is even accepted.
3- Is there a better way to filter records between two dates? Perhaps I am missing something obvious.

**Comment by merinosky** [comment]
Already figured it out. You can close it!

**Comment by wenzhixin** [comment]
OK, thanks for the feedback.

**Comment by snipe** [comment]
@merinosky - do you have a fiddle of how you accomplished this? It would save me a ton of time of figuring it out myself :D TIA!
