### ISSUE TITLE
Asked before, but answer unclear - how to implement case INsensitive searches

### ISSUE THREAD

**Issue by achaffman** [wenzhixin/bootstrap-table#731]
Searching appears to be client side only - is there a way to implement searching that is not case sensitive?

**Comment by dabros** [comment]
@achaffman - if you want to search server side, you have to setup code on your server to do that - the js plugin ofcourse cant do that for you but it does pass param through the data-url using query string or post data - see queryParams, ajaxOptions, method and maybe even ajax (maybe you could make a wrapper function for your ajax calls if you want to pass extra data through, or queryParam alone can do that without hassle, ive never done so not sure)

http://bootstrap-table.wenzhixin.net.cn/documentation/#top


Case insensitive searches will then be part of your server code, which would assumingly have to answer sidePagination="server" aswell. 

For Client-Side insesitive, thats already there, so not sure why you have trouble with it as i see obvious calls to this.searchText.toLowerCase() and it checks for partial matches using forced lowercase strings on both sides - filterBy by default does not, as i quote in #678 , but the filterControl option should be able to allow that easier than my pre-filterControl workaround.

**Comment by achaffman** [comment]
I'll have to look in to the client side case insensitive.  In my preliminary testing it seemed like it was case sensitive and I didn't see any options anywhere in the documentation to set one way or the other.  For this simple table, client side is all I need.

**Comment by achaffman** [comment]
I was mistaken, the searches are case insensitive.  thank you
