### ISSUE TITLE
Scroll top when call `updateRow` with `customView` extension

### ISSUE THREAD

**Issue by fabienwnklr** [wenzhixin/bootstrap-table#7326]
### Bootstraptable version(s) affected

1.22.5

### Description

If i use extension `customView` and want to update row data, view is refreshed and scrolled to top of table..

Work fine without `customView` extension

### Example(s)

For reproduce scroll to bottom of table and click on updateRow button here : [https://live.bootstrap-table.com/code/fabienwnklr/17637](https://live.bootstrap-table.com/code/fabienwnklr/17637)

### Possible Solutions

I think issue come from here [https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/custom-view/bootstrap-table-custom-view.js#L92](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/custom-view/bootstrap-table-custom-view.js#L92), `super.initBody` is call without params where is call with `true` here [https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L2646](https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L2646)

**Comment by UtechtDustin** [comment]
The problem is that you used a fixed height `data-height="460"`.
A fixed height for a custom view don't really makes sense. If you still wan't it you can implement it by you're self (as it is a **custom** view).
Working demo: https://live.bootstrap-table.com/code/UtechtDustin/17715

**Comment by UtechtDustin** [comment]
We will close this issue, as we got no response from you within the last month.
Please let us know if you need further support.
