### ISSUE TITLE
[SOLVED] How to set x-editable options

### ISSUE THREAD

**Issue by dirtyrobinson** [wenzhixin/bootstrap-table#733]
EDIT:

Nvm, I figured out how to set x-editable options.  For anyone searching for a similar answer I used this code to properly set options for x-editable:

        var $table = $('#table');
	
        $table.bootstrapTable({
            //enter bootstrapTable options here
        }).on('editable-init.bs.table', function(e){
            $('.editable').editable('option', { 
                //enter x-editable options here
            });
        });

**Comment by djhvscf** [comment]
:+1:

**Comment by alvin0618** [comment]
var columns: [ {
field: 'editField',
 title: 'col 1',
 editable: {
clear: true,
showbuttons: 'bottom',
unsavedclass: null,
type: 'text',
inputclass: 'form-control',
title: 'Input field'
}
}]

**Comment by wenzhixin** [comment]
Just like @alvin0618 said. Docs: http://bootstrap-table.wenzhixin.net.cn/extensions/#table-editable-column-options
