### ISSUE TITLE
How can I change the arrow PNG color when a column is sorted?

### ISSUE THREAD

**Issue by ivan-ortega-grifols** [wenzhixin/bootstrap-table#7334]
### Description

I want to know if it is possible to change the little blue triangles used when a column is sorted without overwirtting it through CSS.

I'm refering to this one (e.g.):

.bootstrap-table .fixed-table-container .table tfoot th .asc, .bootstrap-table .fixed-table-container .table thead th .asc {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAYAAAByUDbMAAAAZ0lEQVQ4y2NgGLKgquEuFxBPAGI2ahhWCsS/gDibUoO0gPgxEP8H4ttArEyuQYxAPBdqEAxPBImTY5gjEL9DM+wTENuQahAvEO9DMwiGdwAxOymGJQLxTyD+jgWDxCMZRsEoGAVoAADeemwtPcZI2wAAAABJRU5ErkJggg==);
}

**Comment by UtechtDustin** [comment]
As you already found out, the image is within the CSS, so you can't configure it.
But you can overwrite it through you're own CSS, but you wrote you don't want to do that. What is the reason for that ?

**Comment by ivan-ortega-grifols** [comment]
Well, basically is for the same reason to answer why is better use CSS drawings than PNG images: best for simple, geometric shapes, icons, and designs that require responsiveness and lightweight performance. Additionally, my webpages should support a few different themes, so I have a bunch of CSS that user can use (something like dark-theme...) and the arrow colors should mantain the color themes (e.g. I need that my banner app color be the same as that little arrow and I was trying to avoid having same number of PNG arrow images than colors needed; if it was a CSS arrow a only need to share the same "var (--banner-color)".

Please, consider to open the possibility to add manually classes to the bootstrap-datatable to be used instead of your PNG (that can be used as default). Something that "data-sort-icon-up" and "data-sort-icon-down" (e.g. data-sort-icon-up= "fas fa-caret-up", to use the typical font-awesome icon). With this option we achieve a more customizable datatble.

**Comment by UtechtDustin** [comment]
I'm not sure if we should spend time on that feature (request), as you already have the option to overwrite it with custom css.  
It seems this is a edge case, as the most users will not need custom caret's.
I'm fine with marking this issue as feature request, as this is a nice to have thing. But then it would have very low priority.

@wenzhixin What do you think ?

**Comment by wenzhixin** [comment]
@UtechtDustin, I agree with your point but find this issue quite interesting. 

So, I spent some time researching how to replace PNG with SVG and learning how to draw SVGs. 

Once this is implemented, it becomes easy to set colors through CSS.

**Comment by wenzhixin** [comment]
PR: https://github.com/wenzhixin/bootstrap-table/pull/7417

An example changed the color to green: https://live.bootstrap-table.com/code/wenzhixin/17945

**Comment by UtechtDustin** [comment]
@wenzhixin i guess you're example is broken, the caret ist to huge.    
Also i'm not sure if that is good way to solve the issue, we should change the carret so we can change the color by background-color and/or data attribute.   
Passing a new/modified svg is just a replacement not a feature, before we also could overwrite the png.

**Comment by wenzhixin** [comment]
I will check what the issue is. For now, replacing it with SVG has optimized some clarity, which can improve the image resolution.

**Comment by wenzhixin** [comment]
> example is broken, the caret ist to huge.

It's the online editor bug.
