### ISSUE TITLE
Extension [ToolBar] column title display difference

### ISSUE THREAD

**Issue by f108156106** [wenzhixin/bootstrap-table#7336]
### Bootstraptable version(s) affected

1.22.6

### Description

version 1.22.5 can show title color,
but update version 1.22.6,
title color disappear

### Example(s)

https://live.bootstrap-table.com/code/f108156106/17665

**Comment by UtechtDustin** [comment]
You're example uses the version 1.22.6 and the title color (red) is visible.   
Could please explain what do you mean ?
![Bildschirmfoto 2024-05-26 um 21 28 20](https://github.com/wenzhixin/bootstrap-table/assets/13292481/ad4253ab-e253-4dd4-9518-77f44f1803a7)

**Comment by UtechtDustin** [comment]
We will close this issue, as we got no response from you within the last month.   
Please let us know if you need further support.
