### ISSUE TITLE
groupByCollapsedGroups not collapsing on grouped columns 

### ISSUE THREAD

**Issue by DataSupplier** [wenzhixin/bootstrap-table#7337]
### Bootstraptable version(s) affected

1.22.6

### Description

Hi mates,

I'm facing a bug or difficulties when collapsing on grouped columns. 
The groupByField accepts an array, which work nice in order to group on multiple columns.
When applying the groupByCollapsedGroups, it fails to collapse on these columns.

The groupByCollapsedGroups work on a single grouped column.
Therefore I'm providing two examples, 

1. grouped and collapsed on one column (works)
2. grouped and collapsed on two columns (fails)

The reason might be, that I'm not providing the right details, maybe you guys can help me out.
Thanks!

### Example(s)

1. https://live.bootstrap-table.com/code/DataSupplier/17672 (works)
2. https://live.bootstrap-table.com/code/DataSupplier/17673 (fails)

**Comment by UtechtDustin** [comment]
You don't use the correct synatx.
Please check my working [demo](https://live.bootstrap-table.com/code/UtechtDustin/17714).

As you have a composite group by field you also have to composite the collapsed groups.
Does this solves you're issue ?

**Comment by DataSupplier** [comment]
aaa now I see, I got it thanks!
