### ISSUE TITLE
editable扩展列中如何把当前的row的对象传给editable

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#735]
editable扩展列中如何把当前的row的对象传给editable

**Comment by alvin0618** [comment]
display: function(value, sourceData) {
var data = $('#table').bootstrapTable('getData');
var index = $(this).parents('tr[data-index]').data('index');
var row = data[index];
}

**Comment by neozhu** [comment]
我的需求是在editable col 的 vaildate function 和当前行的其他列进行比较严重
editable: {
type: 'text',
title: '确认重量',
validate: function (value) {
if($.trim(value) == '') return 'This field is required';
//如何获取当前行
}

**Comment by wenzhixin** [comment]
#734, #845
