### ISSUE TITLE
Change kaylashri's tableExport.jquery.plugin to hhurz's fork

### ISSUE THREAD

**Issue by ibriq** [wenzhixin/bootstrap-table#736]
The currently maintained version of [kayalshri](https://github.com/kayalshri/)'s tableExport.jquery.plugin is [a fork](https://github.com/hhurz/tableExport.jquery.plugin) by user [hhurz](https://github.com/hhurz/). I am not aware if there's any large differences between the two, but I observed that the newer version returns valid extensions for the downloaded files, which is pretty cool.

**Comment by wenzhixin** [comment]
Thanks, updated.

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html
