### ISSUE TITLE
Example for cookieCustomStorageGet

### ISSUE THREAD

**Issue by tooliload** [wenzhixin/bootstrap-table#7363]
### Description

Is there a working example for cookieCustomStorageGet (custom-storage-get)? I can handle custom-storage-set and custom-storage-delete, to save and delete Settings, but it will fail, if i try to use custom-storage-get. (filterBy Error in Console)

https://live.bootstrap-table.com/code/tooliload/17771

### Example(s)

https://live.bootstrap-table.com/code/tooliload/17771

**Comment by UtechtDustin** [comment]
Please provide us an valid example.   
In you're example you have a static endpoint, which can't work as every cookie have a other structure.

**Comment by UtechtDustin** [comment]
We will close this issue, as we got no response from you.   
If you still need help, please let us know!
