### ISSUE TITLE
Issue for using the sticky-header and fixed column plugins together

### ISSUE THREAD

**Issue by Huangzc88** [wenzhixin/bootstrap-table#7377]
### Bootstraptable version(s) affected

1.22.6

### Description

When using both the fixed column and sticky-header plugins simultaneously, when scrolling down the vertical scroll bar and reaching a point where the header column is fixed at the top of the visible window,  then click on a column header to sort and scroll back up the browser's vertical scroll bar, two headers will appear, with an abnormal extra header still fixed at the top of the screen.

This issue seems to occur only when both plugins are used together. I don't have this problem when using the sticky-header plugin alone.

### Example(s)

https://live.bootstrap-table.com/code/Huangzc88/17854

![image](https://github.com/wenzhixin/bootstrap-table/assets/31158857/56e08500-283a-4572-a437-bce3abc1dfda)

**Comment by Huangzc88** [comment]
Sorry, please ignore the double header issue mentioned above. I found that there was a problem with the order of use. After testing, I found that if the reference of the sticky-header plugin is placed before the reference of the fixed-columns plugin, this issue will not occur. It is recommended to add a document description of the reference order between plugins to avoid unnecessary problems. 

At the same time, I still found another issue when using two plugins at the same time: the header and the content columns are not aligned.

Please see the following example：

https://live.bootstrap-table.com/code/Huangzc88/17863

The test results are as follows:

![image](https://github.com/wenzhixin/bootstrap-table/assets/31158857/b6e461a5-7d48-4b42-bc6e-e7bbbc895386)

After setting the last column on the right as a fixed column, when the table header is stickily fixed at the top, there is a misalignment issue between the column header and the content.

**Comment by wenzhixin** [comment]
It's the same issue as #7377.
