### ISSUE TITLE
One file with all translations

### ISSUE THREAD

**Issue by snipe** [wenzhixin/bootstrap-table#7385]
### Description

Hi everyone - just wanted to first say thanks for this wonderful library. It's the best!

I have a bit of a challenge. We use Bootstrap Table with a Laravel app, and within the app, the user can set their own localization in their profile settings, stored in the database. We have some locales bootstrap-table doesn't have, and you have a bunch we don't have. 

We considered using the formatters and making our own translations within the Laravel translation system, but of course, passing values into those doesn't really work via JS, since our translations use server-side code and those numbers update dynamically, `formatShowingRows()` for example.

We also considered copying one-by-one all of the languages bootstrap-table supports that we also support, but then we'd potentially have a 404 on that language file if the language our users have picked doesn't exist in your localizations, and I'd rather not have to stat to see if the language file exists on every page load.   

It would be ideal if all of the translations could be in one file, with the dynamic locale being loaded from our database and then the table rendering in that language. 

I guess the other alternative is to copy over the files that match our localizations and write a helper Laravel function to only pull in the language file from bootstrap-table if it matches one we have. 

I know it's a longshot, but I figured I'd ask. 

Thanks again for the fantastic package!

**Comment by UtechtDustin** [comment]
I'm not sure if i miss something, but we already have a file with all existing locales: [dist/bootstrap-table-locale-all.min.js](https://github.com/wenzhixin/bootstrap-table/blob/develop/dist/bootstrap-table-locale-all.min.js).

**Comment by snipe** [comment]
Ah, perfect! I was looking for an all.js but I didn’t find it. Thanks!!!

**Comment by UtechtDustin** [comment]
You're welcome :)
