### ISSUE TITLE
Vue Component  showColumns: true not work, have example

### ISSUE THREAD

**Issue by szwss** [wenzhixin/bootstrap-table#7387]
### Bootstraptable version(s) affected

1.22.6

### Description

options: showColumns: true

Column is display, but click it not work, when use theme bootstrap 4

theme bootstrap 5 is ok, but i useing bootstrap 4 only

### Example(s)

Example(s):

https://live.bootstrap-table.com/code/szwss/17899

**Comment by szwss** [comment]
I add popper.js and bootstrap.bundle.js and use advancedSearch: true,

https://live.bootstrap-table.com/code/szwss/17906

advancedSearch also not work

**Comment by UtechtDustin** [comment]
I don't use vue, but please check [our example](https://live.bootstrap-table.com/example/welcomes/vue-component.html) which semms working with `showColumns`.
Maybe you will find the difference :)
