### ISSUE TITLE
Reset sort order to original order

### ISSUE THREAD

**Issue by fxwiegand** [wenzhixin/bootstrap-table#7390]
### Description

Is it possible to reset to the original order after calling [sortBy](https://bootstrap-table.com/docs/api/methods/#sortby) on one specific field? I cannot find anything within the `sortBy` documentation.

**Comment by wenzhixin** [comment]
There is currently no method to reset the original order, but you might be able to record it using a local variable.

**Comment by fxwiegand** [comment]
> There is currently no method to reset the original order, but you might be able to record it using a local variable.
Actually after some more trying around we found that `$('#table').bootstrapTable('sortBy', {"":""})` does in fact reinstate the original order. Maybe it is possible to add this to the docs?

**Comment by UtechtDustin** [comment]
Opened a PR for that.  
Example with the new method `sortReset`: https://live.bootstrap-table.com/code/UtechtDustin/18004
