### ISSUE TITLE
X-editable extension not working

### ISSUE THREAD

**Issue by henrysan96** [wenzhixin/bootstrap-table#740]
Hi, I try to use the x-editable extension but it's not working on my page.
Here is my page: http://www.cc.puv.fi/~e1400477/final2.html
I tried to add the data-editable="true" but somehow I cannot still edit the data. So is there any other things I have to do except adding the data-editable="true"?
Thanks for your help.

**Comment by maxgrass** [comment]
x-editable is working perfectly. Create a simple jsfiddle with 1 column table only with editable functionality  without any other tweaks to understand how it works.

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html
