### ISSUE TITLE
Column width not working when table has Y scroll

### ISSUE THREAD

**Issue by Thang1PV** [wenzhixin/bootstrap-table#7404]
### Bootstraptable version(s) affected

1.23.0

### Description

I configure data-width="900", it's working until table has Y scroll.

### Example(s)

https://live.bootstrap-table.com/code/Thang1PV/17924

**Comment by UtechtDustin** [comment]
This is the expected behavior, as the table has to less space.
Please check the documentation of the [width option](https://bootstrap-table.com/docs/api/column-options/#width).

> Though if the table is left responsive and sized too small, this 'width' might be **ignored** (use min/max-width via class or such then)
