### ISSUE TITLE
CSV compatibility

### ISSUE THREAD

**Issue by Martinomagnifico** [wenzhixin/bootstrap-table#743]
Is there a possibility to have the source url point to a CSV file instead of a JSON file/source? If there's a header row included, that might then also be used for the th's, (so we can skip the `<th data-field="name">Name</th>` part). I understand that CSV's can be different in delimiters and line endings, so I hope there could be some fix for that in data attributes (like data-csv-delimiter="tab"). 
Is there something like it already?

**Comment by wenzhixin** [comment]
It does not support CSV file at the moment, maybe will consider to add this feature, you can use change CSV data to JSON first.

**Comment by wenzhixin** [comment]
You can try this: https://github.com/mholt/PapaParse
