### ISSUE TITLE
Setting an ID in first column

### ISSUE THREAD

**Issue by Keirodev** [wenzhixin/bootstrap-table#744]
Hi there,

I'm using this amazing bootstrap-table, but i'm having an issue, and i didn't suceed to solve it with others issues and documentation.

I have this table
```html
<table id="adresse-table" data-height="500" class="adresse-table">
  <thead>
    <tr>
      <th data-field="num" data-sortable="true" class="col-sm-6">Num</th>
      <th data-field="name" class="col-sm-6">Name</th>
           
  <tbody>                                                         
  </tbody>
</table>
````

Filled in php thanks to 
```php
while($line= $request1->fetch(PDO::FETCH_OBJ)){
	
  $tab[$i] = array(		
    'num' => $line->num,
    'name' => $line->name,
  );
  $i++;
}
		
print json_encode(
array( 'data' => $tab,
 ));
```
And loaded via javascript
```javascript
$('#adresse-table').bootstrapTable('load', elementsValues.data)
```

Do you have an idea how using BT to set first td of each row an  "id" with value of content of this first td ?
```html
<tr>
 <td id=502>502</td>
 <td>name1</td>
</tr>

<tr>
 <td id=600>600</td>
 <td>name2</td>
</tr>

.
.
.

```

**Comment by djhvscf** [comment]
You can use the data-unique-id to set the <tr> element with an Id

**Comment by Keirodev** [comment]
Thanks for your reply.

Then, I'm supposed to set in html 
```html
<table id="adresse-table" data-height="500" class="adresse-table">
  <thead>
    <tr>
      <th data-unique-id="true" data-field="num" data-sortable="true" class="col-sm-6">Num</th>
```

and to send via Json : 
```PHP
  $tab[$i] = array(     
    'num' => $line->num,
    'name' => $line->name,
    'data-unique-id' => $line->num
  );
```

Is that true ?

**Comment by wenzhixin** [comment]
No, the type is String(Indicate an unique identifier for each row):
http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
Here is an example: http://jsfiddle.net/pts5rnqm/

**Comment by dabros** [comment]
@Keirodev - that fiddle seems to answer your question, can you please share whether it did so we can consider this closed or not?

**Comment by wenzhixin** [comment]
Close this issue. If the problem exists, please reopen it.
