### ISSUE TITLE
this is a bug?

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#747]
BootstrapTable.prototype.resetFooter = function () {
       // bt= this not def that=this,
        var bt   = this,
            data = bt.getData(),
            html = [];

        if (!this.options.showFooter || this.options.cardView) { //do nothing
            return;
        }

        $.each(bt.options.columns, function (i, column) {
            var falign = '', // footer align style
                style  = '',
                class_ = sprintf(' class="%s"', column['class']);

            if (!column.visible) {
                return;
            }
            // so this is error.
            if (that.options.cardView && (!column.cardVisible)) {
                return;
            }

            falign = sprintf('text-align: %s; ', column.falign ? column.falign : column.align);
            style = sprintf('vertical-align: %s; ', column.valign);

            html.push('<td', class_, sprintf(' style="%s"', falign + style), '>');

            html.push(calculateObjectValue(column, column.footerFormatter, [data], '&nbsp;') || '&nbsp;');
            html.push('</td>');
        });

        bt.$footer.find('tr').html(html.join(''));
        clearTimeout(bt.timeoutFooter_);
        bt.timeoutFooter_ = setTimeout($.proxy(bt.fitFooter, bt), bt.$el.is(':hidden') ? 100: 0);
        return;
    };

**Comment by wenzhixin** [comment]
Please format the code or provide a jsFiddle. Otherwise, it is hard to understand what you said.

**Comment by wenzhixin** [comment]
This problem is fixed now, please update the code.
