### ISSUE TITLE
Improve check to hide loadingTemplate

### ISSUE THREAD

**Issue by dheldt** [wenzhixin/bootstrap-table#7490]
### Description

Currently, the check if the loadingTemplate is hidden is based on an if-statement, checking if the (re-)loading is silent. Please adept this to check, if the loadingTemplate is visible.

Background: The last three days i did debug an app, where we have a slow server response (~10 seconds due to a huge database and complicated filters). The app auto-reloads silently, but the initial load is not. 

The first reload was triggered (sometimes) before the initial load was completed. In this cases, the check to remove the loadingTemplate failed (it was visible due to the intial load not being completed, but the silent reload set the corresponding setting to silent). So the loadingTemplate was never hidden an no data were visible. 

I guess it is not to hard to check, if it is visible, instead of relying on the setting, which might have been changed? 

Surely, the issue i debugged was in my code by reloading to early, still I think bootstrap-table can be improved here to be more reliant (and prevent maybe somebody else some debugging-time). 

thank you!

with kind regards,

daniel

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!
