### ISSUE TITLE
Add/Update row shows hidden rows ?!

### ISSUE THREAD

**Issue by iTouchTheSky** [wenzhixin/bootstrap-table#750]
Hi, I think this is a bug, if it's not, it's not a really cool feature ...
Each time I add a new row to the table or update an existing one, all my hiddens rows are shown

**Comment by djhvscf** [comment]
Ref to: https://github.com/wenzhixin/bootstrap-table/issues/583

**Comment by wenzhixin** [comment]
Please provide a jsFiddle: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by iTouchTheSky** [comment]
@wenzhixin Here !
https://jsfiddle.net/fh67L9h7/

**Comment by iTouchTheSky** [comment]
@wenzhixin Here it is : https://jsfiddle.net/fh67L9h7/1/

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table/pull/760 you have to set the data-unique-id table option to show/hide a row by id

**Comment by wenzhixin** [comment]
This bug is not fixed now.

**Comment by Dre-amer** [comment]
Hi, I have the same question, is it fixed now

**Comment by wenzhixin** [comment]
Fixed in develop branch.
