### ISSUE TITLE
getData method invocation with the `formatted` detail parameter set to true returns formatted data for only the first column of every row

### ISSUE THREAD

**Issue by Darc-Charlie** [wenzhixin/bootstrap-table#7500]
### Bootstraptable version(s) affected

1.23.0+

### Description

When getData is called with the formatted parameter set to true, not only does it return the formatted data for only the first column of every row, but the `{"column1key":"column1data","column2key":"column2data"}` structure of each row item in the array was lost.

### Example(s)

Before Bug v1.22.6 
https://live.bootstrap-table.com/code/Darc-Charlie/18173

With Bug v1.23.0
https://live.bootstrap-table.com/code/Darc-Charlie/18172

### Possible Solutions

The issue seems to stem from this commit:
https://github.com/wenzhixin/bootstrap-table/commit/5c1da3bdf56d7fcb762eb4f9dfc20a9876fcf55c under this PR #7365.

My suggestion for a fix: accumulate the key and formatted values for each found column into an object. Then return that object as the mapped value of the current row.

```diff
    if (params && params.formatted) {
      return data.map(row => {
+       const formattedColumnData = {};
        for (const [key, value] of Object.entries(row)) {
          const column = this.columns[this.fieldsColumnsIndex[key]]

          if (!column) {
            continue
          }

-         return Utils.calculateObjectValue(column, this.header.formatters[column.fieldIndex],
            [value, row, row.index, column.field], value)
+        formattedColumnData[key] = Utils.calculateObjectValue(column, this.header.formatters[column.fieldIndex],
            [value, row, row.index, column.field], value)
        }
+       return formattedColumnData;
      })
    }
```

**Comment by wenzhixin** [comment]
PR is welcome.
