### ISSUE TITLE
bootstrap-table-all.js

### ISSUE THREAD

**Issue by ehartford** [wenzhixin/bootstrap-table#751]
Can you please create a bootstrap-table-all.js and bootstrap-table-all.min.js that contains all the extensions?  I really just want to download one .js and one .css, include them in my html, and be up and running.

**Comment by djhvscf** [comment]
Good idea.. Ref to: https://github.com/wenzhixin/bootstrap-table/issues/333 and to https://github.com/wenzhixin/bootstrap-table/issues/270

**Comment by ehartford** [comment]
That's not right.
First you choose a build tool.
Then check in to the root a build file, such as a [gruntfile](http://gruntjs.com/sample-gruntfile) or [gulpfile](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md) or [cakefile](http://coffeescript.org/#cake) or pom.xml, build.sbt, etc.  (whatever build tool you are using)
Then configure the file such that the chosen build tool outputs bundled and unbundled .min.js and .js.
Then you need to add a section in the readme.md with build instructions.
Then, for each release milestone, execute the build process (manually or otherwise) and check in the results and the release notes.

**Comment by ehartford** [comment]
I don't know if locales are wanted/needed.  I did not include them.  That's easy enough to change if needed.

**Comment by wenzhixin** [comment]
Added `bootstrap-table-locale-all.js` and `bootstrap-table-locale-all.min.js`
