### ISSUE TITLE
Adding a button-group

### ISSUE THREAD

**Issue by MartinPerrie** [wenzhixin/bootstrap-table#7528]
### Description

I know we can add custom buttons using data-buttons. I was wondering if it is possible to add a button-group that contains multiple buttons on a drop-down (similar to the way the built-in export button shows the different options grouped together).

Ideally I would like to combine the built-in export to CSV button with a custom button under the same button-group - but I don't know whether that would be a step too far!

Thanks for any advice.

**Comment by wenzhixin** [comment]
You can implement this feature using the `buttons` option and `html` function.

https://live.bootstrap-table.com/code/wenzhixin/18234
