### ISSUE TITLE
Update URL without calling refresh (useful for SEO/progressive enhancement)?

### ISSUE THREAD

**Issue by prograhammer** [wenzhixin/bootstrap-table#753]
We need the ability to load first locally (perhaps server-side reads some params from URL, runs database query, and outputs HTML table for client-side to work with locally). Then load from remote on all further interactions.

This is progressive enhancement and good for SEO purposes. Google bot will see the HTML, regardless of whether it can run the javascript on the page. Also this prevents an unnecessary extra ajax call at the first page load when using remote. This makes a lot of sense for apps that are using the history pushState (where I can update the browser address bar without refreshing the page).

**Comment by prograhammer** [comment]
An option like `deferRemoteLoad` or `skipFirstLoad`. Or maybe even on the method:

    BootstrapTable.prototype.refresh = function (params) {
      
        if (params && params.url) {
            this.options.url = params.url;
            this.options.pageNumber = 1;
        }
  
        var defer = false;
        if (params && params.defer) {
              defer = true;
        }
       
        if(!defer){
             this.initServer(params && params.silent, params && params.query);
        }
    };

**Comment by prograhammer** [comment]
Created a PR at https://github.com/wenzhixin/bootstrap-table/pull/754

**Comment by djhvscf** [comment]
Close this issue because the PR was not merged
