### ISSUE TITLE
After update to 1.23.4 no-wrap being ignored

### ISSUE THREAD

**Issue by DataSupplier** [wenzhixin/bootstrap-table#7535]
### Bootstraptable version(s) affected

1.23.4 and 1.23.3

### Description

Today I've updated from version 1.23.2 to 1.23.4. 
In the recent version the column value is now being wrapped into multiple lines while I've applied the class text-nowrap which worked like a charm previously. I like to keep rows on a single line, now it is all messed up. :(

### Example(s)

[text-nowrap version 1.23.4](https://live.bootstrap-table.com/code/DataSupplier/18231) -- recent version ignores no-wrap
[text-nowrap version 1.23.2](https://live.bootstrap-table.com/code/DataSupplier/18233) -- previous version applies no-wrap

**Comment by wenzhixin** [comment]
Fixed in https://github.com/wenzhixin/bootstrap-table/pull/7521
Example: https://live.bootstrap-table.com/code/wenzhixin/18235
I will consider releasing a new version soon.
