### ISSUE TITLE
After update to 1.23.5 reorder-row.bs.table is broken

### ISSUE THREAD

**Issue by DataSupplier** [wenzhixin/bootstrap-table#7554]
### Bootstraptable version(s) affected

1.23.5, 1.23.4, 1.23.3

### Description

Hi devs, Last week I reported a bug (https://github.com/wenzhixin/bootstrap-table/issues/7535) regarding class attribute which was broken. In addition to that bug now I see the event reorder-row is also broken. I reverted my update from 1.23.5 back to 1.23.2, the event working in this version. 

Probably there could me more things that are broken, for now it does not feel comfortable to update to a higher version than 1.23.2.

**Comment by wenzhixin** [comment]
The `onDrop` option of (TableDnD)[https://isocra.github.io/TableDnD/] is not working.

**Comment by DataSupplier** [comment]
cool
