### ISSUE TITLE
bootrap-table 如何实现列编辑或单元格编辑？

### ISSUE THREAD

**Issue by liuwenfeng554** [wenzhixin/bootstrap-table#756]
似乎没有看到api中有列或单元格编辑的内容，是没有嘛？如果有是怎么实现的？

**Comment by wenzhixin** [comment]
麻烦提 issue 前先看下文档和例子，谢谢：http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html

**Comment by liuwenfeng554** [comment]
哦 不好意思  谢谢
