### ISSUE TITLE
bootstrap-table如何选中某行？

### ISSUE THREAD

**Issue by liuwenfeng554** [wenzhixin/bootstrap-table#758]
bootstrap-table 如何进行行选中

**Comment by neozhu** [comment]
这个有例子

**Comment by wenzhixin** [comment]
文档或者例子都有啊：http://bootstrap-table.wenzhixin.net.cn/documentation/#methods
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/check-uncheck.html
