### ISSUE TITLE
Change table row color

### ISSUE THREAD

**Issue by webtogest** [wenzhixin/bootstrap-table#7586]
### Description

Is it possible to change the background-color of a row knowing only the index? thanks

**Comment by wenzhixin** [comment]
Example: https://live.bootstrap-table.com/code/wenzhixin/18310

**Comment by webtogest** [comment]
ok when the table is created,
when it is already created and when I click one <button>

**Comment by wenzhixin** [comment]
Like this: https://live.bootstrap-table.com/example/issues/563.html

**Comment by webtogest** [comment]
it doesn't change color only bold

**Comment by wenzhixin** [comment]
Updated the example: https://live.bootstrap-table.com/code/wenzhixin/18315

https://github.com/wenzhixin/bootstrap-table-examples/pull/539/files
