### ISSUE TITLE
refreshOptions() error if columns in group are hidden

### ISSUE THREAD

**Issue by amiart** [wenzhixin/bootstrap-table#7588]
### Bootstraptable version(s) affected

1.23.5

### Description

refreshOptions() throws error `Uncaught TypeError: column is undefined` in `updateFieldGroup()` function if columns in group are hidden.

### Example(s)

Working example:
https://live.bootstrap-table.com/code/amiart/18312

Hide 'Quantity' and 'Total' columns and then click 'RefreshOptions' button to see error.

### Additional Context

Windows 10
Firefox 132.0
Bootstrap 5

**Comment by wenzhixin** [comment]
OK, thanks for your feedback.

**Comment by amiart** [comment]
My workaround:

Added this function in my code:

```
function setBootstrapTableOptions(table, options) {
    // WORKAROUND BUG #7588
    var hiddenColumns = $.map(table.bootstrapTable('getHiddenColumns'),
        function(col) { return col.field; });
    if (hiddenColumns.length > 0)
        table.bootstrapTable('showAllColumns');
    table.bootstrapTable('refreshOptions', options)
         .bootstrapTable('resetView', {});
    for (var i=0; i<hiddenColumns.length; ++i) {
        table.bootstrapTable('hideColumn', hiddenColumns[i]);
    }
}
```

And then if want to change bootstrap table options I use:

`setBootstrapTableOptions($table, { showToggle: true });`

instead of:

`$table.bootstrapTable('refreshOptions', { showToggle: true });`
