### ISSUE TITLE
How to send pk =  column id to server   when using x-editable plugin? 

### ISSUE THREAD

**Issue by wanglf** [wenzhixin/bootstrap-table#759]
How to get the column id and assign it to pk in x-editable plugin ? At server side, update row value to database according to column id .

**Comment by wenzhixin** [comment]
You can the `idField` option, for example:
```html
data-id-field="id"
```

**Comment by nishadtaylor1** [comment]
Hello, 

I'm new and this might not be the right place, but he's question is so close to what I am looking for.  I just don't understand the answer.  So here is my problem.  Please take a look at the following object.  I'm using the editable plugin and I'm trying to set the pk value.

Thanks you for your time.

tableOptions = {
		method: 'get',
		cache: false,
		striped: true,
		pagination: true,
		pageSize: 50,
		pageList: [10, 25, 50, 100, 200],
		search: true,
		showColumns: true,
		showRefresh: true,
		minimumCountColumns: 2,
		clickToSelect: true,

		columns: [
			{
				field: 'title',
				title: 'Title',
				align: 'right',
				valign: 'bottom',
				idfield: 'webinar_id',
				sortable: true,
				editable: {
					type: 'text',
					title: 'Edit Title',
					url: '/online/webinar/update/title',
					**pk: function(row){
						return row.webinar_id;
					},**
					validate: function (value) {
						value = $.trim(value);
						if (!value) {
							return 'This field is required';
						}
						if (!/^\$/.test(value)) {
							return 'This field needs to start width $.'
						}
						var data = $table.bootstrapTable('getData'),
							index = $(this).parents('tr').data('index');
						console.log(data[index]);
						return '';
					}
				},
			},
			{
				field: 'webinar_id',
				title: 'Webinar ID',
				align: 'right',
				valign: 'bottom',
				sortable: true
			},
			{
				field: 'description',
				title: 'Description',
				align: 'right',
				valign: 'bottom',
				sortable: true
			},
			{
				field: 'operate',
				title: 'Item Operate',
				align: 'center',
				events: operateEvents,
				formatter: operateFormatter
			}

		],
		url: '/online/webinar/getWebinarInfo'
	};

**Comment by wenzhixin** [comment]
`idField` is the table option @nishadtaylor1 http://bootstrap-table.wenzhixin.net.cn/documentation/

**Comment by CarsonSlovoka** [comment]
Hi, @nishadtaylor1 
you need to 

```js
$("#tb_user").bootstrapTable({
  columns: [
    {
      checkbox: true,
    },
    {
      field: 'username',
      title: '用户名',
      width: '10%',
      align: 'center',
      editable: {
        type: 'text',
        placement: 'right',
        emptytext: "...",
        validate: function (v) {
          if (!v) return 'username is null';
        }
      },
    },
    {
      field: 'password',
      title: '密码',
      editable: {
        type: 'text',
        placement: 'right',
        validate: function (v) {
          if (!v) return 'password is null';
        }
      },
    },
  ],

  // 👇👇👇👇below is options👇👇👇👇
  idField: "id", // <-- this is what you want
  striped: true,
  url: 'json/data1.json',
  cache: false,
  pagination: true,
  sortable: false,
  sortOrder: "asc",
  sidePagination: "client",
  pageNumber: 1,
  pageSize: 10,
  pageList: [10, 25, 50, 100],
  search: false,
  strictSearch: false,
  showColumns: false,
  showRefresh: false,
  minimumCountColumns: 2,
  clickToSelect: false,
  // height: 500,
  showToggle: false,
  cardView: false,
  detailView: false,
  onLoadSuccess: function () {
  }
});
```
- [uniqueid](https://bootstrap-table.com/docs/api/table-options/#uniqueid)
- [idField](https://bootstrap-table.com/docs/api/table-options/#idfield)
