### ISSUE TITLE
bootstrap-reorder-rows extension not firing 'onReorderRow' event

### ISSUE THREAD

**Issue by ray-niptech** [wenzhixin/bootstrap-table#7592]
### Bootstraptable version(s) affected

1.23.5

### Description

We are using the reorder row extension with jquery.tablednd version 1.05 as in the example.

There are 2 issues 
1) onReorderRow does not fire after dragging a row.
2) Pressing the 'getData' button in the example does not show the correct order of the rows after dragging a row

### Example(s)

https://live.bootstrap-table.com/example/extensions/reorder-rows.html

Change table initialization in above example to 

$('#table').bootstrapTable({
    onReorderRow: function () {
                     alert('ReorderRow triggered');
                  },
    });

### Possible Solutions

possible incompatibity with current version of BS table and jquery.tablednd

### Additional Context

google chrome version  130.0.6723.92 on Windows 10

**Comment by wenzhixin** [comment]
Ref #7554
Fixed in #7571
