### ISSUE TITLE
Sorting not working correctly 

### ISSUE THREAD

**Issue by turucz** [wenzhixin/bootstrap-table#7601]
### Bootstraptable version(s) affected

1.22.3

### Description

Sorting not working correctly as it can see the attached screenshot

### Example(s)

2004/0001
2024/0487
2004/0001
2004/0485

### Additional Context

![kép](https://github.com/user-attachments/assets/e649f1a5-8670-4781-b8a4-0c54d9ed4124)

**Comment by wenzhixin** [comment]
Cannot reproduce your issue: https://live.bootstrap-table.com/code/wenzhixin/18346
