### ISSUE TITLE
Sort data don't work

### ISSUE THREAD

**Issue by jmmaugis** [wenzhixin/bootstrap-table#7619]
### Bootstraptable version(s) affected

1.20.2

### Description

The data-sortable="true" doesn't work nothing is sorted when i click on ther column.
My bootstrap version is the 5.2.3

### Example(s)

 <table id="tableSearch" class="table tableSearch table-sm tableIrp"
        data-toggle="table"
        data-side-pagination="server"
        data-pagination="true"
        data-sortable="true"
        data-page-list="[20, 50, 100]"
        data-page-size="20"
        data-defer-url="Search"
        data-query-params="searchParams"
        data-cache="true"
        data-click-to-select="true"
        data-id-field="documentId"
        data-row-attributes="rowAttributes">
     <caption class="d-none">Résultats</caption>
     <thead>
         <tr>
             <th data-field="documentId" data-visible="false">DocumentId</th>
             <th data-field="domaine" data-formatter="domaineFormatter">Domaine métier</th>
             <th data-field="codeNotice">Identifiant de la notice</th>
             <th data-field="dateDebutValidite" data-align="center" data-formatter="dateFormatter">Début de validité</th>
             <th data-field="dateFinValidite" data-align="center" data-formatter="dateFormatter">Fin de validité</th>
             <th data-field="nomDocument" data-formatter="nomDocumentFormatter" data-cell-style="fileCellStyle">Nom Du Fichier</th>
             <th data-field="mappingCode" data-sortable="true">Identifiant de la clé de recherche</th>
             <th data-field="etat" data-sortable="true">Etat de la notice</th>
             <th data-field="dateCreation" data-formatter="dateFormatter">Date Création</th>
             <th data-field="metadonnees" data-align="center" data-formatter="metadataFormatter" data-cell-style="metadataCellStyle">Données</th>
             <th data-field="actions" data-align="center" data-formatter="actionsFormatter">Actions</th>
         </tr>
     </thead>
 </table>

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/18463
If the problem exists, reopen it and provide an [Online Example](https://live.bootstrap-table.com). Thanks!
