### ISSUE TITLE
bootstrap-table 1.7 erases data-*  form tr elements

### ISSUE THREAD

**Issue by mimoriarty** [wenzhixin/bootstrap-table#762]
Hi,
I can't make it hold the data-* contained in tr elements. I've read other issues and it's supposed to be fixed in 1.7. Maybe I'm not getting the grip op it.

A text: http://jsfiddle.net/mimoriarty/3hknpawp/

**Comment by wenzhixin** [comment]
bug, tr missed: http://jsfiddle.net/e3nk137y/1323/

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-html.html
