### ISSUE TITLE
Colspan don't work when use it outside of header

### ISSUE THREAD

**Issue by Azalmut** [wenzhixin/bootstrap-table#7621]
### Bootstraptable version(s) affected

1.23.3

### Description

The colspan option don't work inside the tbody.
I need to span several columns in some row of my table and it doesn't work since the 1.23.3

### Example(s)

https://live.bootstrap-table.com/code/Azalmut/18385

**Comment by wenzhixin** [comment]
Fixed in the develop branch: https://live.bootstrap-table.com/code/wenzhixin/18479
