### ISSUE TITLE
cdnjs serving downlevel version

### ISSUE THREAD

**Issue by IanWorthington** [wenzhixin/bootstrap-table#763]
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.7.0/bootstrap-table.min.js is serving version 1.6.0

**Comment by wenzhixin** [comment]
This bug is fixed in v1.8.0.

**Comment by wenzhixin** [comment]
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.8.0/bootstrap-table.min.js
