### ISSUE TITLE
Allow query params to be specified during refresh.

### ISSUE THREAD

**Issue by Sivalingaamorthy** [wenzhixin/bootstrap-table#764]
Hi 

From change log I came to know that I can specify the queryparam on refresh, how to do it, can you provide one sample code for this.

https://github.com/wenzhixin/bootstrap-table/blob/master/CHANGELOG.md
1.6.0 - [enh] Allow query params to be specified during refresh.

I tried specifying the queryparam for refresh, but it takes the queryparam values, when table got initialized.

My requirement is, on initialize the table, i will initialize default value

var startDate='12/12/2014'

  $("#myTable").bootstrapTable({
        url: urlPrefix,
        method: 'post',
        queryParams: function (p) {
            return {
                availabilityDate: startDate
            };
        },

on refresh i want to assign different value and refresh the grid data.

startDate='12/13/2014'

   $('#myTable').bootstrapTable('refresh', {
                url: urlPrefix
                , method: 'post',
                queryParams: function (p) {
                    return {
                        availabilityDate: startDate
                             };
                },
            });
but when I check using jsfiddle, on refresh found json data has date ''12/12/2014''  instead of 12/13/2014. what is wrong ? how to reset the queryParam on refresh. 

Please suggest.

**Comment by wenzhixin** [comment]
Hi @Sivalingaamorthy , you can do it by this:
```js
queryParams: function (p) {
    return {
        availabilityDate: $('#startDate').val() // your date element
    };
}
```
or:
```js
$('#myTable').bootstrapTable('refresh', {
    query: {
        availabilityDate: startDate
    }
});
```

The docs: http://bootstrap-table.wenzhixin.net.cn/documentation/#methods
