### ISSUE TITLE
Uncaught InternalError: too much recursion using extension treegird

### ISSUE THREAD

**Issue by pnukeid** [wenzhixin/bootstrap-table#7646]
### Description

hello there,

i've been try using example treegird, table is displayed but always getting error `Uncaught InternalError: too much recursion` 

Are there also people experiencing it or is there a solution for that error

![image](https://github.com/user-attachments/assets/1fc6274a-225e-4bc6-a36d-e7f1050b50d3)

**Comment by wenzhixin** [comment]
I checked the example at https://examples.bootstrap-table.com/#extensions/treegrid.html, and the issue you mentioned does not appear. Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!
