### ISSUE TITLE
Internet Explorer - Render issue

### ISSUE THREAD

**Issue by TreyTaylor** [wenzhixin/bootstrap-table#765]
Hey :smile: 

Just came across a rendering issue in Internet Explorer, it removes spaces in between words unless typed really fast. I don't know what causes the issue with the plug-in, it works with Firefox and Chrome so I'm guessing another one of IE's notorious rendering bugs.

**Comment by TreyTaylor** [comment]
UPDATE: Also does this with Google Chrome (latest version)

**Comment by toontilley** [comment]
I have just spotted this in my clients system as well. did any one manage to fix this?

**Comment by wenzhixin** [comment]
@TreyTaylor @toontilley , I have tested this problem in IE browser, an I think this is not a bug, you can try to set `searchTimeOut` option.
