### ISSUE TITLE
Column width via javascript fails for percentage spec

### ISSUE THREAD

**Issue by moriciogithub** [wenzhixin/bootstrap-table#7656]
### Bootstraptable version(s) affected

1.23.5

### Description

When specifying a column via json
```
                  {
                    field: 'interacciones_resumen_tercerosid_solucionadas',
                    title: 'S',
                    align: 'right',
                    width: "16",
                    "width-unit": "%",
                  },

```
the column will be formatted with 16px.

**Comment by wenzhixin** [comment]
Use `widthUnit` instead.

**Comment by moriciogithub** [comment]
I'm sorry for bothering you with this non-sense, really sorry.

Thank you for your excellent work.

Mauricio.
