### ISSUE TITLE
does not support chinese parameter values

### ISSUE THREAD

**Issue by gooree** [wenzhixin/bootstrap-table#766]
Hi wenzhixin,

我在尝试做一个demo程序时发现无法支持中文的请求参数，传到后台以后会成为乱码。我试了调整ajax的部分请求参数，发现解决不了该问题，请问如何修正？

**Comment by djhvscf** [comment]
Can you translate it to english and then provide a fiddle?

**Comment by wenzhixin** [comment]
@gooree 是可以的，我们现在的项目正在使用中文的请求，没有问题，因为 bootstrap table 使用的是 jquery 的 ajax 请求，所以应该不属于 bootstrap table 的问题，而是属于你后台处理的问题。你可以尝试写个简单的 ajax 请求看下是否有问题。

**Comment by gooree** [comment]
多谢回复，后面试过了可以的。






在 2015-05-27 00:54:03，"文翼" <notifications@github.com> 写道：


@gooree 是可以的，我们现在的项目正在使用中文的请求，没有问题，因为 bootstrap table 使用的是 jquery 的 ajax 请求，所以应该不属于 bootstrap table 的问题，而是属于你后台处理的问题。你可以尝试写个简单的 ajax 请求看下是否有问题。

**Comment by spp1987** [comment]
是否 可以贴下代码
