### ISSUE TITLE
How to get number of Rows (jquery) in the Bootstrap table.

### ISSUE THREAD

**Issue by Sivalingaamorthy** [wenzhixin/bootstrap-table#767]
how to get (in jquery) total number of rows listed in the bootstrap table. 

it displays the message 'Showing 1 to 8 of 8 rows', but i need to get the total rows [8 rows] in jquery, can you provide one sample code.

I searched the documentation but there is no information.

**Comment by wenzhixin** [comment]
Use `$('#table').bootstrapTable('getOptions').totalRows` or `$('#table').bootstrapTable('getData').length`.

**Comment by Sivalingaamorthy** [comment]
Thanks for your inputs.

**Comment by zeeshanyshaikh** [comment]
On refreshing the page `$('#table').bootstrapTable('getOptions').totalRows` shows 0. Can you explain why?

**Comment by djhvscf** [comment]
Can you create a new issue an share us an example?

**Comment by zeeshanyshaikh** [comment]
Yes, please check https://github.com/wenzhixin/bootstrap-table/issues/2967
