### ISSUE TITLE
Height set causes headers not to resize

### ISSUE THREAD

**Issue by ehartford** [wenzhixin/bootstrap-table#768]
If Height is set, the headers are not redrawn when the table is resized.

When height is not set, it works as expected.
  Before resize:
![image](https://cloud.githubusercontent.com/assets/1117701/7238898/ac2d6d9a-e75a-11e4-932c-25ff62e2666d.png)
  After resize, I see the expected result is good.
![image](https://cloud.githubusercontent.com/assets/1117701/7238913/c890ded6-e75a-11e4-9fc0-1d1e777df110.png)

But, when height is set:
![image](https://cloud.githubusercontent.com/assets/1117701/7239019/7817db48-e75b-11e4-9fa2-dd3fb5f22199.png)
The body redraws but not the headers.
  Before resize:
![image](https://cloud.githubusercontent.com/assets/1117701/7238960/11feb71e-e75b-11e4-9cc9-ca15d4f32202.png)
  After resize, the headers don't get redrawn:
![image](https://cloud.githubusercontent.com/assets/1117701/7238968/26b9d508-e75b-11e4-847b-90b662954986.png)

**Comment by wenzhixin** [comment]
Use `$table.bootstrapTable('resetView');` http://bootstrap-table.wenzhixin.net.cn/faq/

**Comment by larboyer** [comment]
Awesome. Thanks for the tip. I removed the data-height and it solved the bug.
