### ISSUE TITLE
Pagnination rows number are incorrect when combined with Child Row

### ISSUE THREAD

**Issue by KreatixDev** [wenzhixin/bootstrap-table#769]
I'm using this example : http://gotogurudev.wynconnections.co.uk/tpl/gotoguru/test.html

In combination with pagination, rows count are doubled (it count the hidden row)

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle to save our time? Please review [the guidelines for contributing](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md) to this repository. Thanks

**Comment by KreatixDev** [comment]
http://jsfiddle.net/rj3f8Lq5/

Note that part of the manual javascript seems to be not working on jsfiddle (I didn't really take time to see why) Anyway, the part I want you to check is the line stating : Showing 1 to 4 of 4 rows

I only have 2 visible rows, and I think it would be better to not count the hidden rows

**Comment by KreatixDev** [comment]
Just noticed that if I have more pages, the colspan become messy

**Comment by KreatixDev** [comment]
Did you find something ?

**Comment by djhvscf** [comment]
Ok this is happening because we don't support the child row feature right now.

**Comment by wenzhixin** [comment]
Added child row. #892
