### ISSUE TITLE
Is there a way to trim text in cell

### ISSUE THREAD

**Issue by iamthestreets** [wenzhixin/bootstrap-table#770]
HI,

I tried searching for something like this but could not find anything. 

I have a column in the table that has a lot of text, but I do not want to show all text. Is there a way to trim the text to display a certain number of characters?

For example if my full text was:
`I want to trim this text to a certain number of characters`

I would want to trim it down to look like this:
`I want to trim this text to a cer...`

**Comment by djhvscf** [comment]
This is a good feature!!

**Comment by iamthestreets** [comment]
So this does not exist yet?

**Comment by jimgit** [comment]
Could you use the dataformatting function?
  <th data-sortable=" true" data-field="customer" data-formatter="maxLengthFormatter">Elevation LH</th>

 function maxLengthFormatter(value) {
var maxLength=6;
if (value.length>maxLength)
            return var res = value.substring(0, maxLength) + '...';
else {    
         return value;
}
}

**Comment by wenzhixin** [comment]
Please use `data-formatter` option to format your string just what @jimgit said, we do not provide this feature.

**Comment by iamthestreets** [comment]
@jimgit Thanks I got it working, but I had to change this code:
`return var res = value.substring(0, maxLength) + '...';`
to this:
`return value.substring(0, maxLength) + '...';`

Now the issue i'm having is that once I increase the maxLength to 40 or higher it removes text from my last column of a specific row then adds it to the column i set the maxLength for.

So to give a better example - I have a message column that has a message displayed that reads:
"Testing this message with a link"
the word link is hyperlinked. 
Then the last column after message is date that display the date in this format:
"4th June 2010"

Once I set the maxLength to 40 or higher it replaces the message column text to:
"Testing this message with a 4th June 2010"
the date is being hyperlinked. 
and removing it from the date column.

**Comment by djhvscf** [comment]
I think the best option to do this is into the plugin

**Comment by wenzhixin** [comment]
Try this: http://jsfiddle.net/e3nk137y/1366/

**Comment by iamthestreets** [comment]
Thanks! that will work for now.
