### ISSUE TITLE
New reimplementation on BootstrapTableHelper 

### ISSUE THREAD

**Issue by franklupo** [wenzhixin/bootstrap-table#772]
Reimplementation on BootstrapTableHelper https://github.com/franklupo/BootstrapTableHelper

Best regards

**Comment by wenzhixin** [comment]
Added to [README.md](https://github.com/wenzhixin/bootstrap-table#bootstrap-table) [Resource issues](https://github.com/wenzhixin/bootstrap-table/issues?q=label%3Aresource+is%3Aclosed) list.
