### ISSUE TITLE
bootstrap table getting index

### ISSUE THREAD

**Issue by KulanthaivelChinnadurai** [wenzhixin/bootstrap-table#773]
Hi, Im very new to BootStrap. I have implemented a table like this
<table id="table" class='clickable-row' data-href='url://' DATA-URL="" data-flat="true" data-toggle="table"  >	
			 <thead><tr >  
				   <th data-field="jtmeta.JT_State" data-unique-id='<c:set>1</c:set>' >Job Status </th>
			       <th data-field="jtmeta.LocationName" >Location</th>			        
			       <th data-field="jtmeta.JT_Name" >Job Name</th>			        
			       <th data-field="jtmeta.DueDate" >Due Date</th>
			       <th data-field="jtmeta.JT_UserName" >User Name</th>
			       <th data-field="jtmeta.NUMTOTALPAGE" >Total Pages</th>	      			      
			   </tr> </thead>  </table>

I am getting the JSON object from the server and display it in bootstrap table on scroll event. Now I need to take the index of a selected row and do processing some actions. Request to provide how I can achieve this.

js file.
var offset=0;
var jobcount=10;
function bindScroll(){ 	
        if(($(this).scrollTop() + $(this).innerHeight() >= this.scrollHeight)&& JobEnd==false) {
        	offset=offset+jobcount;
      	  $.ajax({
    		 	//contentType: "application/json; charset=utf-8",
    			dataType: "json",
    			url: "/DDServer/rest/jobs?action=Retrievejobs&offset="+offset+"&jobcount="+jobcount,
    	    }).then(function(data) {     	    	
    	    	if(data.results !=undefined){    	    	
    	    	$('#bootdiv').unbind('scroll');    	      
    	    	$('#table').bootstrapTable('append', data.results);  	    	
    	    	}
    	    	else{
    	    		//
    	    	}
    		});          
        }
    } 

How Can I get the dynamic table selected rows index.

**Comment by KulanthaivelChinnadurai** [comment]
My HTML design is like this.

**Comment by KulanthaivelChinnadurai** [comment]
my HTML is like this.. 
<table id="table" class='clickable-row' data-href='url://' DATA-URL="" data-flat="true" data-toggle="table"  >	
			 <thead><tr >  
				   <th data-field="jtmeta.JT_State" data-unique-id='<c:set>1</c:set>' >Job Status </th>
			       <th data-field="jtmeta.LocationName" >Location</th>			        
			       <th data-field="jtmeta.JT_Name" >Job Name</th>			        
			       <th data-field="jtmeta.DueDate" >Due Date</th>
			       <th data-field="jtmeta.JT_UserName" >User Name</th>
			       <th data-field="jtmeta.NUMTOTALPAGE" >Total Pages</th>	      			      
			   </tr> </thead>

**Comment by wenzhixin** [comment]
Please format your code or provide a jsFiddle to explain what you want, thanks. Check out this: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by djhvscf** [comment]
Any update here?

**Comment by wenzhixin** [comment]
The example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/415.html
