### ISSUE TITLE
Get Selections Bootstrap Table

### ISSUE THREAD

**Issue by jorgemejia** [wenzhixin/bootstrap-table#774]
i´ve used this method to get selections:
```javascript
$('#mantto_piezas').on('click-row.bs.table', function (e, row, $element) {
      selections = $('#mantto_piezas').bootstrapTable('getSelections');
     alert(JSON.stringify(selections));
});
```

 but when this method is called it does not show the last selection.

**Comment by djhvscf** [comment]
Please read this to report an issue: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
I guess you can use `check.bs.table` or `uncheck.bs.table` event instead.

**Comment by stevenjlho** [comment]
But why check.bs.table event don't have $element param. I want to get current checkbox when i trigger check.bs.table event.

**Comment by wenzhixin** [comment]
Sorry @stevenjlho , we don't support this feature. Maybe you can use the row data to find what element you want.

**Comment by stevenjlho** [comment]
Thanks for you reply. But i really need this feature. Please considering to add this feature.

**Comment by wenzhixin** [comment]
You can submit a new issue for this new feature @stevenjlho
