### ISSUE TITLE
Two checkboxes - bound to data field

### ISSUE THREAD

**Issue by jimgit** [wenzhixin/bootstrap-table#775]
My json data has two 1/0 fields that I am representing using the data-formatter with a checkbox.   

function cbFormatter(){value) return '<input type="checkbox" (value==1?'checked':'') + '>'

When I check the checkboxes I get an error saying the "check" property is undefined. I would like to change the json data.  Can I bind the checkboxes to the data so that when the users check boxes,  the changes are represented in the underlying json data and does this persist when sorting / filtering is done?  Or is there a better way using the data-checkbox property?

**Comment by wenzhixin** [comment]
Is this question same with this: http://stackoverflow.com/questions/29771221/bootstrap-table-getting-click-error-on-my-data-formmatter-checkboxes?

**Comment by jimgit** [comment]
Yes - thank you for your reply.  I was not using the updateRow method - I was updating the source data but your feedback helped me find the right results. Was also trying to have exclusive checkboxes
https://jsfiddle.net/jimkennelly/yxquu35c/1/
