### ISSUE TITLE
Sort table where table data is HTML ActionLink

### ISSUE THREAD

**Issue by rizvisarwar** [wenzhixin/bootstrap-table#777]
I have a table where data in ID column is html ActionLink. How can I sort my table on this ID column? 
![table](https://cloud.githubusercontent.com/assets/478854/7274246/7c09e362-e8fb-11e4-83fd-c3921233e8e1.jpg)

The html code for the ID column:
<td>
    @Html.ActionLink(linkText, actionName, controllerName, routeValues, null)
</td>

Basic table sorting doesn't work. So I have used Custom sorting using 'data-sorter' column option. In the custom sorting function I can see that instead of just the text in the cell, sorting is done based on the whole action link!
To solve the problem for now, in the custom sorting JavaScript function, I have done some string operations to get the Column sorted based on only the linkText (Label). It would be nice to have a built-in functionality for sorting ActionLinks.

**Comment by wenzhixin** [comment]
You can use jQuery: 
```
a = $(a).text();
b = $(b).text();
```

**Comment by rizvisarwar** [comment]
Worked. Thanks.
