### ISSUE TITLE
Change default "Search" text placeholder

### ISSUE THREAD

**Issue by rshov** [wenzhixin/bootstrap-table#780]
Hello, I'm performing search on the server-side and due to my database schema I'm only searching one of the fields shown in my table. I was hoping to change the "Search" text placeholder to say something like "Search name" so that the user knows it is not searching all of the fields.

Is there any way to customize this text?

Thanks,
Raymond

**Comment by djhvscf** [comment]
You have to set the formatSearch function.. See the Localization section in this page: http://bootstrap-table.wenzhixin.net.cn/documentation/

**Comment by rshov** [comment]
Would this change the "Search" text for all bootstrap tables in the site? I'm hoping to customize this on a table by table basis.

**Comment by djhvscf** [comment]
No, this change is for individual table in the site.. (POO)

**Comment by rshov** [comment]
I see how this would work now. I was hoping there was a configuration on the table, but at least this lets me change it if needed. Thanks for help.

**Comment by wenzhixin** [comment]
@rshov https://github.com/wenzhixin/bootstrap-table-examples/blob/master/457.html

**Comment by rshov** [comment]
@wenzhixin Thanks for the link, that definitely helped!
