### ISSUE TITLE
Initialize existing full table from JavaScript

### ISSUE THREAD

**Issue by gregpettit** [wenzhixin/bootstrap-table#781]
So, I have a table that loads via Ajax and therefore the data-attribute method of initializing the table with Bootstrap-Table doesn't kick in.

The JavaScript examples want you to supply the data. But I already have the data! The table is built already.

On a guess and a whim, I tried to just call $('#myTable').bootstrapTable() on it, and it does... "something"...? But the loading message appears above the table. Naturally, I'm not actually loading anything at that point.

Is there a way to "convert" a plain HTML table to a Bootstrap-Table with JavaScript?

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-html.html

**Comment by gregpettit** [comment]
Thanks for the speedy reply! Alas, that page doesn't contain anything answering the question. I see a table that was maybe created from existing HTML? But it doesn't show the JS call needed to do so nor explain the example.

If I look at the source code, it is using the data-attribute method (data-toggle="table"), which I already explained does not work when the table is fetched via Ajax after page load.

**Comment by gregpettit** [comment]
Internally, the plugin probably waits for the document to be ready, searches for instances of data-toggle="table", and then executes a method on that table that converts it to a Bootstrap-Table. All I really need is for that method to be part of the public API either as the default behaviour when bootstrapTable is called with no parameters, or with a particular parameter/option being passed in.

**Comment by gregpettit** [comment]
Strange... looking at the source code, I find this:

```javascript
$(function () {
    $('[data-toggle="table"]').bootstrapTable();
});

Which is exactly what I expected. However, the call being made implies that what I intuitively tried (just calling a void bootstrapTable) should have worked. Yet I am seeing the loading message...?

**Comment by gregpettit** [comment]
I'm going to close this because I discovered that even with normal initialization (no Ajax) the loading message is appearing. It was a false negative. The entire plugin has the "bug". ;)

**Comment by wenzhixin** [comment]
Via JavaScript: http://bootstrap-table.wenzhixin.net.cn/getting-started/#usage-via-javascript
```
$table.bootstrapTable();
```
