### ISSUE TITLE
Can you add a Mouseover Event?

### ISSUE THREAD

**Issue by LathamZ** [wenzhixin/bootstrap-table#782]
I'm new to jQuery and don't know how to add a Mouseover Event to your code.

I mean to add an  Mouseover Event to "bootstrap-table" just as other events it already have like "click-row.bs.table" and need to return the $element.

**Comment by djhvscf** [comment]
What do you want to do?

**Comment by LathamZ** [comment]
just like "click-row.bs.table" event but triggered by mouseover event. maybe you can name it as "mouse-over-row.bs.table"

**Comment by djhvscf** [comment]
Take the postbody event and then do a loop in the tr elements and then bind that event

**Comment by LathamZ** [comment]
Can I retrieve the $elememt by this way? I need the $element .

**Comment by djhvscf** [comment]
Try this $(tr)

**Comment by LathamZ** [comment]
Actually, there is some data in the $element but not displayed on the table, so I can't retrieve it by $('tr'). Still need the $element.

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/e3nk137y/1374/

**Comment by amartinezhernandez** [comment]
@djhvscf Your fiddle is not working as it should (it finds the index of the "tr" element instead of the "td"). A functional code based on your fiddle is:

`$(function () {
    $('#table').bootstrapTable({
        data: data,
        onPostBody: postBody
    });
    
    function postBody() {
        var trs = $('#table').find('tbody').children();
     
         for (var i = 0; i < trs.length; i++) {
            $(trs[i]).mouseover(function(e) {
                console.log($(e.currentTarget).parent().parent().find('thead').find('th').eq($(e.currentTarget).data('index')).data());
            });                
        };
    };
});`
