### ISSUE TITLE
"Loading" message appears for converting existing HTML tables

### ISSUE THREAD

**Issue by gregpettit** [wenzhixin/bootstrap-table#783]
1. Make a table with the attribute `data-toggle="table"`
2. Fill in the table with rows and cells containing actual data. Ie. a completed marked-up table
3. With Bootstrap-Table properly included on the page, load the page

Expected result: table is formatted as a Bootstrap-Table

Actual result: table is formatted as a Bootstrap-Table and there is a loading message above the table

**Comment by gregpettit** [comment]
As a hack, you can pass "hideLoading" into a bootstrapTable() call, but based on the examples, one shouldn't need to...?

**Comment by wenzhixin** [comment]
@gregpettit , https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports, can you provide a jsFiddle to show your problem, for example: http://jsfiddle.net/wenyi/e3nk137y/11/light/.

**Comment by gregpettit** [comment]
It would be non-trivial. Since I have moved to another technology, no point wasting your time on me. ;)
