### ISSUE TITLE
Refreh data from other url

### ISSUE THREAD

**Issue by adonet** [wenzhixin/bootstrap-table#785]
How can i refresh a table optain data from other data-url?

script type="text/javascript"
function change_url()
{
  alert($('#tabla').data('url'));
  $('#tabla').data('url', './json/mydata.php');

  alert($('#tabla').data('url'));

 $('#tabla').bootstrapTable('refresh');
 }
/script

don't refresh the new data

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#409.html

**Comment by adonet** [comment]
great! thanks!
