### ISSUE TITLE
bug getScrollPosition

### ISSUE THREAD

**Issue by 1534854467** [wenzhixin/bootstrap-table#786]
$('#table).bootstrapTable('getScrollPosition');

it can‘t return the right value ,

and this code in bootstrap-table.js

    BootstrapTable.prototype.scrollTo = function (value) {
        var $tbody = this.$container.find('.fixed-table-body');
        if (typeof value === 'string') {
            value = value === 'bottom' ? $tbody[0].scrollHeight : 0;
        }
        if (typeof value === 'number') {
            $tbody.scrollTop(value);
        }

        if (typeof value === undefined) {
            return $tbody.scrollTop();
        }
   };

that is no return,  no run in "return $tbody.scrollTop();"

because the  'type value' is 'undefined', is  ('undefined' === undefined) is false 

so I think shoud change 

      typeof value === undefined 

to

      value === undefined

**Comment by djhvscf** [comment]
Refer to: https://github.com/wenzhixin/bootstrap-table/pull/793
