### ISSUE TITLE
Table height changed after operation

### ISSUE THREAD

**Issue by myeclipse1989** [wenzhixin/bootstrap-table#788]
It's a perfect project,but some bugs.
When I do some operation,the table height always changed automatically,I have spent much time on trying to fix it,but I did't find the root of problem.
As far as the footer in Chrome,I don't think it was fixed.
Thanks.
![screen shot 2015-04-24 at 12 10 55](https://cloud.githubusercontent.com/assets/10670676/7316912/79c083f0-ea7b-11e4-8034-8e19d8c6e9ba.png)
![screen shot 2015-04-24 at 12 10 46](https://cloud.githubusercontent.com/assets/10670676/7316911/79be7934-ea7b-11e4-82ef-09acf7c0d5de.png)

**Comment by wenzhixin** [comment]
What operation do you do? Please provide a jsFiddle or example code. Otherwise I don't know how and why the problem happened.

**Comment by myeclipse1989** [comment]
thanks,in JsFiddle works perfect,but it's weird that can't work on local machine,I think because I imported third-party theme,then embed in a tab page,it cause conflict,and other problem is,how can we keep selected rows when we use pagination functions on server.

**Comment by djhvscf** [comment]
Close this issue
