### ISSUE TITLE
click to select with pre-checked radios

### ISSUE THREAD

**Issue by My1** [wenzhixin/bootstrap-table#789]
I have the problem that when I try to pre-set radios with the standard HTML part of the input the "checked" attribute it wont be checked when I load the page with the js. without the js it's perfectly fine.

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#methods/checkBy-uncheckBy.html

**Comment by My1** [comment]
how about NOT making it more complex than it is, I mean why do we have to set at 2 places where a chekmar and/or radio is set (since you should still use the checked attribute in case of a non-js user...
how about including a check for the check attribute instead...

**Comment by wenzhixin** [comment]
I guess it is `filed` setting problem

**Comment by My1** [comment]
what do you exactly mean with that?

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle to show the problem @My1?
