### ISSUE TITLE
Reorder the rows

### ISSUE THREAD

**Issue by pedrosalpr** [wenzhixin/bootstrap-table#790]
Reorder the rows with drag and drop

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder.html

**Comment by pedrosalpr** [comment]
I saw, but he reorders the columns only. I have not seen to reorder the lines. I tried to do the sorting for the rows, but I could not.

**Comment by djhvscf** [comment]
Ok, remember any Pull Request is welcome
