### ISSUE TITLE
Inline edit

### ISSUE THREAD

**Issue by brauliobo** [wenzhixin/bootstrap-table#791]
First of all, this is an incredible project, congrats!

We are planning to migrating our tables to bootstrap tables.

The only missing thing we need that I could not find in bootstrap-table was inline edit: when the user clicks a row another row appear just below with an edition HTML, which for us is a complex and different view, even other tables (for example, one order has many items). On the below screenshot you should see the blank area below row and the row highlighted after the user click.

Is there an easy way to this with bootstrap-table?

![table-inline-edit](https://cloud.githubusercontent.com/assets/41740/7333925/d4cfe480-eb56-11e4-8251-79fedf60de85.png)

**Comment by djhvscf** [comment]
You can see this: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html

**Comment by brauliobo** [comment]
@djhvscf this is not enough :( I need to put an bootstrap-table inside this inline edit space). think on the example of a table of orders and when you click to edit it show the table of items.

**Comment by brauliobo** [comment]
maybe this could be implemented using multiple `tbody`: http://stackoverflow.com/questions/3076708/can-we-have-multiple-tbody-in-same-table

**Comment by djhvscf** [comment]
Sorry but I don't understand your example

**Comment by brauliobo** [comment]
@djhvscf it would be something like this:
```html
<tbody>
  <tr class="view"> </tr>
  <tr class="edit"> </tr>
</tbody>
```
The `<tr class="edit"> </tr>` is hidden by default, and it is activated only when `<tr class="view"> </tr>` is clicked

**Comment by djhvscf** [comment]
Oh! Ok got it.. I think this feature is not supported right now.. The only thing that you can do is try with the Editable extension for now... Any pull request is welcome :+1:

**Comment by brauliobo** [comment]
@djhvscf will try it latter when the migration starts :)

**Comment by ravi-ku** [comment]
If want to edit dropdownlist with some validation. Then how we can achieve this?

regards,
mcamail2002@gmail.com

**Comment by djhvscf** [comment]
Can you explain that? @ravi-ku

**Comment by wenzhixin** [comment]
@brauliobo , you can use detaiView now. #499

**Comment by brauliobo** [comment]
beautiful, perfect, thanks!
