### ISSUE TITLE
Show div on row click

### ISSUE THREAD

**Issue by iamthestreets** [wenzhixin/bootstrap-table#792]
Hi,

I have a messages table and wanted to hide the table on row click and show another div. 
Here is the div for my table:
`<div id="msg-inbox">`

Here is the div to view the message:
`<div id="msg-view">`

I tried this:
.on('click-row.bs.table', function (e, row, $element) {
       $("#msg-inbox").hide();
       $("#msg-view").show();
    })

but it does not work. Any ideas on how I should do this?

**Comment by djhvscf** [comment]
Provide a fiddle please.. https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

**Comment by ksidibe** [comment]
I'm having the same problem. I have an element in my td which is supposed to respond to the onclick event. But nothing happens. I have used 
$('#grades_tables').on('click-row.bs.table', function (e, row, $element) {
    	console.log(e);
    	console.log(row);
    	console.log(element);
    }); to see what happens. But, the event is never fired
 Does the plugin stop the normal propagation of events?

**Comment by djhvscf** [comment]
You have to bind the events before the bootstrap-table creation.. before this $table.bootstraptable();

**Comment by jorgemejia** [comment]
I did something similar, I used.
```
 <form class="form-horizontal" role="form" enctype="multipart/form-data" id="msg-inbox" style='display: none;'>
</form>
```
```javascript
$('#msg-inbox').fadeIn("slow", 4000);
```

**Comment by djhvscf** [comment]
@jorgemejia provide a jsfiddle.. We can help you with that

**Comment by jorgemejia** [comment]
https://jsfiddle.net/L7n7c9Le/12/

**Comment by djhvscf** [comment]
What do I have to see?

**Comment by djhvscf** [comment]
Any update here?

**Comment by dabros** [comment]
@jorgemejia - im with @djhvscf, looked at the fiddle but cant quite well what you want to achieve as opposed to whats happening

Please clarify

Thanks

**Comment by wenzhixin** [comment]
In our example: http://issues.wenzhixin.net.cn/bootstrap-table/, we can see the event has been triggered use console panel (F12) when you click the row. Close this issue, if problem exists, reopen it and provide a jsFiddle to show the bug.
```
click-row.bs.table [Object, n.fn.init[1]]
```
