### ISSUE TITLE
calculateObjectValue is call for every rows when update single row

### ISSUE THREAD

**Issue by nguyennp** [wenzhixin/bootstrap-table#794]
I hava a 1000 rows, 20 colums tables with columFormatter and data-cell-type with high frequent update on rows. The issue is that a single row update result in recalculation of every remain rows ( in turn call formatter/cell-type on un changed rows). Is there any way that I can mark some row changed and update just the changed rows only?

**Comment by wenzhixin** [comment]
I think you can use pagination to avoid this problem at the moment.
