### ISSUE TITLE
A bug when data is null

### ISSUE THREAD

**Issue by esandXu** [wenzhixin/bootstrap-table#795]
I create a basic table with remote data url, when the data is null, line 1708 report a error: "TypeError: data is null ", and the table will stay on loading. So I fix it with "else if (!$.isArray(data) && data)", but the bootstrap table can not trigger the "load-error.bs.table" event. Hope you notice this.

**Comment by djhvscf** [comment]
Please provide a fiddle

and remember this: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

**Comment by wenzhixin** [comment]
The response data can not be `null`, please use empty array instead, or you can use `responseHandler` to handle your response data:
```
function responseHandler(res) {
    return res || [];
}
```

**Comment by esandXu** [comment]
@wenzhixin  ok, it works.
