### ISSUE TITLE
Disable x-editable at the beginning?

### ISSUE THREAD

**Issue by henrysan96** [wenzhixin/bootstrap-table#797]
Hi, I tried to disabled the inline edit at the beginning so that I can use it by toggling.     
```javascript
$(window).load(function () {
    $('#table-hover .editable').editable('disable');
});
```
It works on my server after reloading, but on JS fiddle, I cannot disable it.
http://jsfiddle.net/e3nk137y/1397/

**Comment by djhvscf** [comment]
Review the Framworks and extensions section in the left panel, there is a combo, select No wrap in head

**Comment by henrysan96** [comment]
I chose no wrap in head but it is still enabled.
http://jsfiddle.net/e3nk137y/1402/

**Comment by wenzhixin** [comment]
Remove your `jquery.min.js` file and use `editable-init.bs.table` event: http://jsfiddle.net/e3nk137y/1413/
