### ISSUE TITLE
Help with filter control select

### ISSUE THREAD

**Issue by raku** [wenzhixin/bootstrap-table#798]
How to preload filter control select with custom data or with data from server side?

**Comment by djhvscf** [comment]
Filter control plugin?? this one? http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/filtercontrol.html

**Comment by raku** [comment]
Yes, that one

**Comment by raku** [comment]
I'm loading data from server, and I want to fill select type filter with all data from a column not only visible one at certain time

**Comment by djhvscf** [comment]
Ok, that feature is not supported.. Any pull request is welcome

**Comment by raku** [comment]
check my pull request https://github.com/wenzhixin/bootstrap-table/pull/804
thanks
