### ISSUE TITLE
is there a direct method to change the number of records per page ?

### ISSUE THREAD

**Issue by DigitalCoder** [wenzhixin/bootstrap-table#799]
Hi !

I'd like to know if you've got a direct method to change the number of records per page ?
because I'd like to try to put page-list drop-down menu in the fixed-table-toolbar

thanks for advance for your answer.

Regards.

**Comment by djhvscf** [comment]
You want to change the page number list in "run time"?

**Comment by DigitalCoder** [comment]
I want to get only page-list drop-down menu in the fixed-table-toolbar, 
also still get the trigger click to change the number of records too

**Comment by djhvscf** [comment]
oh! It seems like a bug.. provide a jsfiddle please

**Comment by djhvscf** [comment]
Any update here?? @DigitalCoder

**Comment by djhvscf** [comment]
@DigitalCoder see this http://jsfiddle.net/djhvscf/e3nk137y/1878/

**Comment by wenzhixin** [comment]
Merged.
