### ISSUE TITLE
使用 modal-table 弹出框出现两个tr内容？

### ISSUE THREAD

**Issue by liuwenfeng554** [wenzhixin/bootstrap-table#800]
在table 上弹出  modal-table  出现tr内容相同的表头信息，这是因为什么导致。

**Comment by phantom0424** [comment]
貌似作者很少回答中文的问题。

**Comment by liuwenfeng554** [comment]
其实我也很好奇，明明中国人 为何偏偏只处理英文的提问多

**Comment by wenzhixin** [comment]
@phantom0424, @liuwenfeng554 大部分问题并不是我回答的，平时也没有那么多时间来一一作答所有人提的问题，现在主要都是由 @djhvscf 来查看问题和帮忙维护，他是哥斯达黎加的，看不懂中文，所以假如可以的话尽量用英文来提问吧，当然其他人也会参与讨论问题，例如 http://stackoverflow.com/questions/tagged/bootstrap-table。

另外提问题希望可以提供详细的版本，使用的代码或者 jsFiddle 例子，方便查找问题的原因，不然我还得去重现你们说的问题。毕竟个人时间有限，免费开源出来也是希望能帮到更多的人，希望其他人也能参与进来，例如帮忙查找原因或者能提交 Pull Request：https://github.com/wenzhixin/bootstrap-table/pulls（目前已有184个Pull Request），而不是单纯的提问题或者需求，然后我来解决或实现。详细见文档：https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

**Comment by wenzhixin** [comment]
关联到 #765

**Comment by wenzhixin** [comment]
已增加例子：http://issues.wenzhixin.net.cn/bootstrap-table/#options/modal-table.html
