### ISSUE TITLE
How to assign an id to the toolbar

### ISSUE THREAD

**Issue by henrysan96** [wenzhixin/bootstrap-table#801]
I want to make an onclick event for the **refresh** button but I don't know how to assign an id after setting **data-show-refresh="true"** . Thanks for helping me.

**Comment by djhvscf** [comment]
With this code:

    $search = this.$toolbar.find('.search input');

You can get the button object and then you can set the id

**Comment by wenzhixin** [comment]
Try this:
```js
$('button[name="refresh"]').click(function () {
    // ...
});
```
