### ISSUE TITLE
Select checkbox after refresh

### ISSUE THREAD

**Issue by CaRLiTRoS85** [wenzhixin/bootstrap-table#806]
Hi,
when i call refresh method to reload the list... how can i mantain the selected checkbox checked?
I've tried with checkby method, but it doesn't run after refresh. However, if i do checkby without refresh, it works.

How can i do this? The maintainSelected attributte only works in pagination and order, but not in refresh.

Thanks in advance.

**Comment by djhvscf** [comment]
I think you can try handling the load-success event after the ajax call

**Comment by CaRLiTRoS85** [comment]
Thanks, i finally did this.

$("#ApprovalTemplateFlowsTable").bootstrapTable('refresh');
$('#ApprovalTemplateFlowsTable').on('load-success.bs.table', function (e, data) {
        $("#ApprovalTemplateFlowsTable").bootstrapTable('checkBy', {field:'ApprovalTemplateFlowId', values: array});
});

**Comment by wenzhixin** [comment]
ref #450

**Comment by abhsk1** [comment]
@carlosg85 Even I am facing the same issue wherein bootstrap table refresh unchecked the selected rows.

I was following you post :
$("#ApprovalTemplateFlowsTable").bootstrapTable('refresh');
$('#ApprovalTemplateFlowsTable').on('load-success.bs.table', function (e, data) {
$("#ApprovalTemplateFlowsTable").bootstrapTable('checkBy', {field:'ApprovalTemplateFlowId', values: array});
});

Here 'array' in line 3 comes from "$table.bootstrapTable('getSelections')" ??

**Comment by abhsk1** [comment]
@carlosg85 @wenzhixin I am new to bootstrap , you help will be much appreciated for above concern.

**Comment by carlosg85** [comment]
yes @abhsk1, i get the array like you say.

var selected =  $("#ApprovalTemplateFlowsTable").bootstrapTable('getSelections');

I dont' remember exactly how it works, but my code is like that:

`var selected =  $("#ApprovalTemplateFlowsTable").bootstrapTable('getSelections');
            
            if (selected.length > 0)
            {
                var id = selected[0].ApprovalTemplateFlowId;
                array[0] = id;

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("MoveFlow", "ApprovalTemplates")',
                    data:
                    { 
                        id: id,
                        order: order
                    },
                    success: function (response) {
                        if (response.result == "success") {
                            $("#ApprovalTemplateFlowsTable").bootstrapTable('uncheckAll');
                            $("#ApprovalTemplateFlowsTable").bootstrapTable('refresh', {silent: true});

                        }
                        else if (response.result == "error") {
                            ShowError(response.errorMessage);
                        }
                    },
                    dataType: "json",
                    cache: false
                });    
            }`

Like you can see, i managed the array and then I do de 'uncheckAll' method, and then the refresh.


The refresh use the next method to do de 'checkBy function'
`        $('#ApprovalTemplateFlowsTable').on('load-success.bs.table', function (e, data) {
            $("#ApprovalTemplateFlowsTable").bootstrapTable('checkBy', { field:'ApprovalTemplateFlowId', values: array });
        });`

**Comment by abhsk1** [comment]
Thanks @carlosg85 , Now it worked like a charm. Thanks alot for your guidance and support. Keep up the good work :+1:

**Comment by Rich2020** [comment]
The problem here is that when the row is selected via 'load-success.bs.table', 'check.bs.table' will be called again... 

This means that if we have a table which periodically refreshes, any ajax calls or events bound to the 'check.bs.table' event will fire again. 

Is it possible to 'silently' check the row (without it triggering the 'check.bs.table' event)?
