### ISSUE TITLE
Rounded Corners for Hidden/Shown Columns

### ISSUE THREAD

**Issue by SarahD** [wenzhixin/bootstrap-table#807]
Hi everyone!
I need to create rounded corners on specific headers (like in the image attached). To compound the issue, we are making it so the user can hide/show the columns. If a particular column is hidden, the one to the left or right of it will need to have the rounded corner. I need to round the last cells to match as well. I would appreciate any advice on how to perform this.
Since I have empty columns to provide spacing, I've tried this, but even though the column is hidden, it is still in the DOM, so I am not sure what else I can try.
$('th#space2').prev('th').addClass("someclass");

![col rounded headers fw](https://cloud.githubusercontent.com/assets/948608/7375728/8ebff10c-eda8-11e4-8b1c-b875853a6d2a.png)

Thanks,
Sarah

**Comment by djhvscf** [comment]
Provide a jsfiddle please, we can help you

**Comment by SarahD** [comment]
Thank you! http://jsfiddle.net/webdevsarah/pg3pLtdr/

**Comment by dabros** [comment]
@SarahD 

Im bit busy to write full example, but i would refer you to my filter workaround that used callbacks to alter the th contents each time (see "UI Implementation" subheader)

#678 (Partial Filter Matches)

This 'onPostHeader' callback should provide example of how to access and affect html of all columns, and debugging the $_header object can prob tell you whether hidden or not, index, ect. 

And being a callback, no need for anything too fancy as its just an extra bit of code in your file run post-bootstrap-table-logic - no need for the base code mods i use to add other event callbacks either

Hope this helps

**Comment by djhvscf** [comment]
If this issue is not resolved then reopen it please @SarahD
