### ISSUE TITLE
Problem with hideRow

### ISSUE THREAD

**Issue by tm1000** [wenzhixin/bootstrap-table#808]
It seems when trying to use 

```$('table').bootstrapTable('hideRow', {index: 'row-0',isIdField: true})```

Nothing happens because bootstrap-table transforms: data-unique-id="row-1" into data-uniqueid="row-1"

Therefore the filter on line 1666 (https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1666) never matches. If I change the filter to data-uniqueid it works as expected.

Using master branch

**Comment by djhvscf** [comment]
Yes, you're right!! Any pull request is welcome!

**Comment by tm1000** [comment]
Sure. I partially posted this because I was not sure if data-unique-id was the right reference when reviewing http://bootstrap-table.wenzhixin.net.cn/documentation/#methods as you say "idField" which there is also an idField.

So I am not sure which one it should be, I assume "data-unique-id" as that is FOR a row, as opposed.

idField	data-id-field	String	undefined	Indicate which field is an identity field.
uniqueId	data-unique-id	String	undefined	Indicate an unique identifier for each row.

Once I get the confirmation on this I will submit a PR that fixes hide row, checks show row and updates the docs

**Comment by djhvscf** [comment]
Yes, please update the docs and double check the showRow method.. We should use data-unique-id for show/hide row

**Comment by tm1000** [comment]
Done. Thanks for responding so quickly!
