### ISSUE TITLE
Filter control multiple select

### ISSUE THREAD

**Issue by Fanda36** [wenzhixin/bootstrap-table#809]
Hi,

I look to nice extension filtercontrol. Is possible have multi-select in filter?
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#extensions/filtercontrol.html

![image](https://cloud.githubusercontent.com/assets/3972954/7380206/a43ef5bc-edfa-11e4-92bb-bcd4a1412f0a.png)

Thanks.

**Comment by djhvscf** [comment]
Di you mean this multi-select plugin?? http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/boolean-options.html

**Comment by Fanda36** [comment]
Yes, but on the filter values (I will check more values in filter - for example 1$ and 13$).

**Comment by djhvscf** [comment]
I think it is not possible because we search by text and not by specific value.. This means:

I search $!, for example, then the result will be $1, $10, $11, $12, $13, $14... all of those values contains $1

**Comment by Fanda36** [comment]
And using for search regexp?

If checked $2 and $5 - search (*$2*)|(*$5*) (string like $2 or $5)

**Comment by djhvscf** [comment]
Good idea, but we have to develop it.. Remember any pull request is welcome

**Comment by djhvscf** [comment]
This feature can't be implemented because we search by text and not using regexp
