### ISSUE TITLE
js events from inside a cell are overwritten

### ISSUE THREAD

**Issue by creadicted** [wenzhixin/bootstrap-table#811]
Hello. 
I have a button inside a cell: 
`<button class="statusbtn btn btn-success" style="">Button</button>`
and a js function that is called when clicked on this button: 
`$(".statusbtn").on("click", function () {...`
It works fine when i have `data-toggle="table"` not active. But if i have the event never is fired. 
Any ideas?

**Comment by tm1000** [comment]
The tables are regenerated on any user action so any bindings will be lost. Instead of binding globally bind within:
```
$("table").on("post-body.bs.table",function() {
```

**Comment by creadicted** [comment]
Thank you! That works fine
