### ISSUE TITLE
good practice to integrate select2 plugin or select tag inside table cells 

### ISSUE THREAD

**Issue by l7777777b** [wenzhixin/bootstrap-table#812]
Currently im using select2 plugin for my select option inside table cells. the table is for user entry, so its going to be editable and im thinking to use insertrow method to add new row.
first, im using ajax to fetch the content of the select box and put it in the first row, if the user add new row i clone the select box using jquery to the next row and so on. but the problem is everytime i use insertrow method, it clears my select2 content. and also looking at the insertrow method, seems i cannot add html content into column because its accepting json format (text).
is there any good practice to implement the select2 plugin or maybe standard select tag into table cells with insert row method?

*out of topic: is there any method to get current total row? not the current row index.

**Comment by wenzhixin** [comment]
Q1 ref #831: 
```
$table.on('post-body.bs.table', function () {
    $('.select2').select2();
});
```

Q2: Try this `$table.bootstrapTable('getOptions').totalRows`.
