### ISSUE TITLE
How to customize query string parameters?

### ISSUE THREAD

**Issue by alexbooker** [wenzhixin/bootstrap-table#813]
```jade
table(
  data-toggle="table", 
  data-url="/data", 
  data-pagination="true", 
  data-side-pagination="server", 
  data-show-header="false",
  data-page-list="[]")
```

    Request URL:http://localhost:3000/data?order=asc&limit=10&offset=0

How do you add a custom parameter? e.g:

    Request URL:http://localhost:3000/data?order=asc&limit=10&offset=0&return=newRecords

or

    Request URL:http://localhost:3000/data?order=asc&limit=10&offset=0&return=popularRec

Thank you.

**Comment by djhvscf** [comment]
USe the query-params table option to do that.. and please provide a jsfiddle

**Comment by alexbooker** [comment]
I tried all kind of things but I could not get it to work. Can you please show me how?

**Comment by djhvscf** [comment]
Provide us a jsfiddle with your code, we can help you then

**Comment by alexbooker** [comment]
Here: https://jsfiddle.net/84cL5Ltt/2/

**Comment by djhvscf** [comment]
Ok.. Did you check this https://github.com/wenzhixin/bootstrap-table-examples/blob/master/152.html ?

**Comment by alexbooker** [comment]
Thanks.

**Comment by alexbooker** [comment]
It would be nice if you linked these examples from the main documentation by the way.

**Comment by carolgomesm** [comment]
The example link does not work anymore...

**Comment by wenzhixin** [comment]
@ carolgomesm https://github.com/wenzhixin/bootstrap-table-examples/blob/master/issues/152.html
