### ISSUE TITLE
如何处理列内容过长的问题？

### ISSUE THREAD

**Issue by liuwenfeng554** [wenzhixin/bootstrap-table#814]
@wenzhixin 内容过长会拉宽，切换页面不一致，怎么处理

**Comment by wenzhixin** [comment]
可以使用 class 属性

**Comment by liuwenfeng554** [comment]
ok谢谢

**Comment by wenzhixin** [comment]
参考例子：http://issues.wenzhixin.net.cn/bootstrap-table/#options/table-style.html
