### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by alexbooker** [wenzhixin/bootstrap-table#815]
Hello, all, 

I want to use this [new feature](https://github.com/wenzhixin/bootstrap-table/issues/649). It was added to`master` 22 days ago but the last release was 28 days ago. I am actually using Bower and am stuck on version 1.7.0. 

Please release the latest `dist`!

**Comment by djhvscf** [comment]
I don't know.. @wenzhixin is the owner of this project!

**Comment by alexbooker** [comment]
Any recommendation on how to use the latest code-base without having to sacrifice tooling?

**Comment by use** [comment]
@alexbooker in your bower.json file, you can specify a specific commit to use, for example:

      "dependencies": {
         "bootstrap-table": "6c1019e931a"
      }

Does that help for now?

**Comment by alexbooker** [comment]
Thank you. But not really. `dist` has not been updated in 20+ days.

**Comment by wenzhixin** [comment]
I would release a new version.

**Comment by alexbooker** [comment]
Any update on this?
