### ISSUE TITLE
Filter by initial search value on table load

### ISSUE THREAD

**Issue by grillmaster** [wenzhixin/bootstrap-table#816]
I'm trying to set up a table that automatically searches for the default search value when the table loads. I set the default value inside the javascript file, but it won't initiate the search unless you click in the search box and press any key.

I also tried creating a new javascript file to load after everything else, and it sets the initial value, but has the same problem. I'm trying to figure out how i can initialize the search without pressing a key.

    var srch_str = 'v1.00';
    var bstable_first_load = true;

    $(document.getElementById('server_table')).on('load-success.bs.table',function () {//when the table is loaded the first time and visible, set the search string...
        if(srch_str.length > 0 && bstable_first_load){$('.fixed-table-toolbar').find('.search > :input').val(srch_str);
        bstable_first_load = false};
    })

**Comment by djhvscf** [comment]
Use the data-search-text table option to do that

**Comment by grillmaster** [comment]
Thanks. I had tried that, but I didn't realize I was using an old version.  Updated and it works now!

**Comment by pavanbangaloreraju** [comment]
> Use the data-search-text table option to do that
> http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

it didn't work for me , 


        $('#EngSummaryTable').bootstrapTable({
            exportDataType: "all",
            exportOptions: {
                fileName: 'EngSummary'
            },
            stickyHeader: true,
            stickyHeaderOffsetY: stickyHeaderOffsetY + 'px',
            columns: [
                [
                    { title: 'Slot', field: 'SystemNumber', width: '15px', editable: false, sortable: true, formatter: removeNullWithSpacesFormatter, filterControl: 'input' },
                    { title: 'SO', field: 'SalesOrder', width: '15px', editable: false, sortable: true, filterControl: 'input', formatter: removeNullWithSpacesFormatter, searchText: searchTextSO },
                    { title: 'Item', field: 'item', width: '15px', editable: false, sortable: true, filterControl: 'input', formatter: removeNullWithSpacesFormatter },
                    { title: 'Material', field: 'PartNumber', width: '15px', editable: false, sortable: true, formatter: anchorTagFormatter, filterControl: 'input' },
                    { title: 'Prod Order', field: 'ProductionOrder', width: '80px', editable: false, sortable: true, formatter: removeNullWithSpacesFormatter, filterControl: 'input' },
                    { title: 'Product', field: 'Product', editable: false, width: '15px', sortable: true, formatter: removeNullWithSpacesFormatter, filterControl: 'input' },
                    { title: 'Type', field: 'ProductType', editable: false, width: '15px', sortable: true, formatter: removeNullWithSpacesFormatter, filterControl: 'input' },
                    { title: 'BOM', field: 'OMSConfigPercent', width: '15px', editable: false, sortable: true, formatter: PercentFormatter, filterControl: 'input' },
                    { title: 'Qi', field: 'QiConfigPercent', width: '15px', editable: false, sortable: true, formatter: PercentFormatter, filterControl: 'input' },
                    { title: 'Recon', field: 'ProfileReconciled', width: '15px', editable: false, formatter: checkboxIsReconciled, filterControl: 'select' },
                    { title: 'Released', field: 'ProfileReleased', width: '15px', editable: false, formatter: checkboxIsReconciled, filterControl: 'select' },
                    { title: 'PlanReady', field: 'PlanReady', width: '15px', editable: false, formatter: checkboxIsReconciled, filterControl: 'select' },
                    { title: 'DJ Start', field: 'PlanBuildStart', width: '15px', editable: false, sortable: true, formatter: DateFormatter, filterControl: 'input' },
                    { title: 'DJ Comp', field: 'DJComplete', width: '15px', editable: false, sortable: true, formatter: DateFormatter, filterControl: 'input' },
                    { title: 'Field', field: 'Field', width: '50px', editable: false, sortable: true, formatter: checkboxIsReconciled, filterControl: 'input' },
                    { title: 'Owner', field: 'UserFullName', width: '50px', editable: false, sortable: true, formatter: removeNullWithSpacesFormatter, filterControl: 'input' },
                    { title: 'Source', field: 'ModSource', width: '50px', editable: false, sortable: true, formatter: removeNullWithSpacesFormatter, filterControl: 'input' },

                ]
            ]
        });


 searchText: searchTextSO and a function is written but it doesn't hit . formatter is also a function and it works fine but searchText doesn't hit
