### ISSUE TITLE
Sort by custom data attribute on a <td>?

### ISSUE THREAD

**Issue by use** [wenzhixin/bootstrap-table#821]
Hi, I read a couple issues about people trying to do (I think) the same thing I am: #500, #546.

I am creating an html table, and I want to sort a column by a custom attribute instead of the actual contents of the <td>.  Is there a way to do this?

I thought this is what [data-sort-name column option](http://bootstrap-table.wenzhixin.net.cn/documentation/) is for, but I can't get it to work.

For example:

    <table data-toggle="table"
        >
        <thead>
            <tr>
                <th data-field="fruit" data-sortable="true">Item</th>
                <th data-field="date"  data-sortable="true" data-sort-name="month">Date</th>
                <th data-field="type"  data-sortable="true">Type</th>
            </tr>
        </thead>
        <tbody>
            <tr><td>Pear  </td><td data-month="1">January</td> <td>Fruit</td></tr>
            <tr><td>Carrot</td><td data-month="3">March</td>   <td>Vegetable</td></tr>
            <tr><td>Apple </td><td data-month="2">February</td><td>Fruit</td></tr>
        </tbody>
    </table>

When I click the "Date" header, I want it to sort by the numerical data-month attribute (1, 2, 3) rather than the <td> text value (January, February, March).

Is this possible?

**Comment by djhvscf** [comment]
Can you provide a jsfiddle, we can help you

**Comment by use** [comment]
http://jsfiddle.net/e3nk137y/1432/

To summarize: I'd like to sort by the numerical data-month attribute in my second column, rather than the alphabetical "month name" value in the <td> cells

**Comment by wenzhixin** [comment]
Example: http://jsfiddle.net/e3nk137y/1434/

**Comment by zkan** [comment]
Suppose I have my data stored in a JSON file. How could I set the data attribute on `<td>`? I tried my best to find an example but have no luck so far. Please advise.

**Comment by gpassero** [comment]
Same situation as zkan here. ´´´table data-sortable="true"´´´ doesn't work.

**Comment by Aabling** [comment]
Hi @wenzhixin. Maybe a simple question, but how do a add the data-month attribute and its value like in "http://jsfiddle.net/e3nk137y/1434/", but only using jquery? Is it a column option or?

**Comment by moussa1** [comment]
@wenzhixin Can you please answer Aabling and zkan? I have the same issue and cannot seem to find a solution.

**Comment by moussa1** [comment]
@Aabling @zkan Were you able to figure out a workaround for this issue?

**Comment by darylldawn** [comment]
I am also trying to add an extra data attribute in a column so bumping this for updates. Advance thanks @wenzhixin!

**Comment by bustersg** [comment]
i am also using json. how can i add e.g. data-month4="1" in <td>
as per example 
http://jsfiddle.net/e3nk137y/9647/

**Comment by yujinyuz** [comment]
> Example: http://jsfiddle.net/e3nk137y/1434/

This seems to be not working as of the latest version of bootstrap tables.

I tried

```
    console.log(typeof a, typeof b)
```

But it's returning a string. Any ideas?

Currently I have `data-datetime` attribute in my `td` and I can only access it via `rowA._last_sub_data.datetime`

**Comment by UtechtDustin** [comment]
@yujinyuz 
You have to to use the third and fourth, as writte in our [documentation](https://bootstrap-table.com/docs/api/column-options/#sorter).

**Comment by yujinyuz** [comment]
Here is my function

```
  function customSort(a, b, rowA, rowB) {

  console.log(rowA.dataset); // undefined
  console.log(rowA._last_sub_data.datetime) // 2019-20-04 7:00 PM

    return a - b;
  }
```

**Comment by UtechtDustin** [comment]
Please provide us an example with our [editor](live.bootstrap-table.com/).

**Comment by yujinyuz** [comment]
@UtechtDustin https://live.bootstrap-table.com/code/yujinyuz/2513

**Comment by UtechtDustin** [comment]
Yea thats the way you can go, or you can create a other column which is not visible and on the registered column you use the [sortname](https://bootstrap-table.com/docs/api/table-options/#sortname) column option.

**Comment by yujinyuz** [comment]
Is there any reason why `rowA._registered_data.datetime` is undocumented?

And the author wrote this before: http://jsfiddle.net/e3nk137y/1434/ but it's not working as expected.

**Comment by UtechtDustin** [comment]
Because this is not the the way you should go.
The example from @wenzhixin is almost 5 years old (!), so its not up to date!

**Comment by yujinyuz** [comment]
Okay thanks! I'm following the approach with the `data-visible` since using this `rowA._registered_data.datetime` might break the code in the future as well

**Comment by 8ivek** [comment]
> Example: http://jsfiddle.net/e3nk137y/1434/

thanks for this
