### ISSUE TITLE
How do you reload local data

### ISSUE THREAD

**Issue by ksidibe** [wenzhixin/bootstrap-table#822]
I need to reload the local table data(i.e no server side involved). How do I do that?
Thanks.

**Comment by djhvscf** [comment]
You have to use the 'load' method

**Comment by ksidibe** [comment]
I saw that in the doc. But that method requires the data to be passed in as a parameter. But I need the data to be populated from the table itself.

**Comment by ksidibe** [comment]
I saw that method in the document. The problem is that it requires the parameter data. The data is already in the table. I simply want the Bootstrap Table to refresh it's copy of the data from the table.
I do this in my js $('#grades_table').bootstrapTable('load').
I get the following error: TypeError: data is undefined.

**Comment by wenzhixin** [comment]
Use `refresh` method @ksidibe .

**Comment by ksidibe** [comment]
Thanks guys for you responses. I tried that too. Looking through the code of the plugin, it looks like it reloads the data from the server. In my case, the data is not coming from the server. It is already loaded in the table
Any suggestion. I would suggest exposing a method to do refresh the table locally.
BootstrapTable.prototype.refresh = function (params) {
        if (params && params.url) {
            this.options.url = params.url;
            this.options.pageNumber = 1;
        }
        this.initServer(params && params.silent, params && params.query);
    };

**Comment by wenzhixin** [comment]
Why do you want to reload the data?

Try this:
```
$table.bootstrapTable('load', $table.bootstrapTable('getData'));
```

**Comment by ksidibe** [comment]
We use x-editable to update save the data back to the server. Once the data is successfully saved on the server, the td value is updated locally. But When you switch from a normal table view to a card-view, it's the old value that shows up. The same thing happens when you hide or show a column, the old data is displayed instead of the new one. The requirement is not to reload the data from the server because it is huge and doing so would degrade the performance of the application.

**Comment by wenzhixin** [comment]
OK, does that work?

**Comment by ksidibe** [comment]
No, doing $table.bootstrapTable('load', $table.bootstrapTable('getData')); loads the data that existed when bootstraptable was first instantiated.  Any other suggestion will be greatly appreciated.
Thanks.

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle @ksidibe ?

**Comment by jtrumbull** [comment]
@ksidibe: The results of `getData()` is the local data, there is nothing to reload.

The below jsFiddle, using `x-editable` plugin and the `bootstrap-table-editable` extension, is working as expected. The value is updated in the html and in `bootstrapTable.data`, and the value remains updated when toggling the card view.

http://jsfiddle.net/joeycakes/e3nk137y/1698/

Could you provide any other settings that may be causing this issue, or has this been resolved?

**Comment by wenzhixin** [comment]
It seems the answer of @jtrumbull solve your problem now @ksidibe. Close this, if not, reopen it.

**Comment by sodeindeakintoye** [comment]
hello please i have a data-table with data,and i want to reload the data data with another data,but the old data is still there,until i refresh the browser

**Comment by sodeindeakintoye** [comment]
``$(document).ready(function () {
    $("#btnstaff").click(function () {
        debugger
        $(dataTable).bootstrapTable('refresh');
        var app = {};
        var data = $("#staff").select2('data')

        app.StaffName = data[0].text;
        app.StaffNo = data[0].id;


        $.ajax({
            url: url_path + "/ShowStaff",
            method: "GET",
            data: app,
            dataType: "json",
            success: function (response) {

                console.log(response);

                initDataTable(response);
            }
        })
    });
});






function initDataTable(data) {

    $("#data-table").bootstrapTable('showLoading');

    debugger

    $("#data-table").bootstrapTable({

        search: true,
        searchAlign: "right",

        showPaginationSwitch: true,
        pagination: true,
        mobileResponsive: true,
        checkOnInit: true,
        minWidth: 626,
        //toolbar: "#custom-toolbar",
        showRefresh: true,
        showToggle: true,
        buttonsClass: "danger",

        data: data,
        columns: [
            {
                field: 'Operations',
                title: 'Operations',
                sortable: true
            },
            {
                field: 'Designation',
                title: 'Designation',
                sortable: true
            },
            {
                field: 'ApprovingLevel',
                title: 'Approving Level',
                sortable: true,
                align: "right",
            },
            {
                field: 'MinAmt',
                title: 'Minimum Amount',
                sortable: true,
            },
            {
                field: 'MaxAmt',
                title: 'Maximum Amount',
                sortable: true,
            }



        ],
    });

    //$("#data-table")
    //    .bootstrapTable("refresh", {
    //        url: "../ApprovalStaff/ShowStaff"
    //    });

};

**Comment by wenzhixin** [comment]
@sodeindeakintoye Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by Script-kidd007** [comment]
s
