### ISSUE TITLE
Does bootstrap-table break rowspan?

### ISSUE THREAD

**Issue by IanWorthington** [wenzhixin/bootstrap-table#823]
Does bootstrap-table break rowspan?  The following code should has the date spanning two rows in the first column UNTIL I add data-toggle="table".

											<table data-toggle="table">
											    <thead>
											            <th>Date</th>
											            <th>Price</th>
											    </thead>
											    <tbody>
											        <tr>
											            <td rowspan="2">2015-04-19 20:03:00</td>
											            <td>US$ 4,499</td>
											        </tr>
											        <tr>
											            <td>US$ 4,499 / $ 2.836.688</td>
											        </tr>											        
											        
											        
											    </tbody>
											</table>

**Comment by djhvscf** [comment]
Provide a jsfiddle please

**Comment by wenzhixin** [comment]
Does not support this feature.

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/e3nk137y/1488/

**Comment by IanWorthington** [comment]
Love it!  Thanks djhvscf!

**Comment by djhvscf** [comment]
Great!! But remember that you can use the mergecell method

**Comment by jhourlad** [comment]
This is not working even in the Fiddle example. Columns are swapping unconditionally when sorted.

**Comment by jstdoit** [comment]
I met the problem too.

**Comment by wenzhixin** [comment]
Fixed in the develop branch.

**Comment by jstdoit** [comment]
I hacked by remove all empty <td></td> after body rendered temp.
