### ISSUE TITLE
PageList error if pageSize = totalRows

### ISSUE THREAD

**Issue by whiteproud** [wenzhixin/bootstrap-table#826]
Error in pagination where the page size has the same value of total row of the table

![image](https://cloud.githubusercontent.com/assets/7511412/7409324/ace2eddc-ef25-11e4-9d11-4ce6c62e1389.png)

![image](https://cloud.githubusercontent.com/assets/7511412/7409365/1f2ebc90-ef26-11e4-9025-bbf2bbc5cf12.png)

in this case pageList is an array and crashes calling the replace function.

**Comment by djhvscf** [comment]
What version of bootstra-table are you using?

**Comment by whiteproud** [comment]
1.6.0

**Comment by djhvscf** [comment]
Ok, you have to use the version 1.7.0

**Comment by whiteproud** [comment]
Ok thanks
