### ISSUE TITLE
bootstrap-table-cookie - formatAllRows Error

### ISSUE THREAD

**Issue by snahreed** [wenzhixin/bootstrap-table#827]
hi guys, 

thanks again for this great bootstrap-table plugin and all its extensions.

Juste a report here on an issue with the saving states cookie, spotted with the new feature "formatAllRows".

" Error : this.options.formatAllRows is not a function "

Assumed in the cookie.js :
this.options.formatAllRows() ? pageListStateSave : +pageListStateSave;

guess " () " should be removed on line 150

Thanks for all your job here

snahreed

**Comment by djhvscf** [comment]
What version of bootstrap-table are you using?

**Comment by snahreed** [comment]
i'm using the very last files i think, from the src/ directory
removing the "( )" seems to solve the problem for now

**Comment by snahreed** [comment]
actually, after verification , i download the 1.7 release zip, but the files are still versioned 1.6 ? is it juste a version number error , or the 1.7 files are not the good ones ?

i see definition of formatAllRows as a function in the files , but using them with the cookie unabled throw me the error

**Comment by snahreed** [comment]
Even with my poor js skills, i see that removing the "()" is NOT the answer, as formatAllRows is a function and is called everywhere as it. 

My apologies for the wrong solving solution. But error is still there for the moment.

Thx for your time :)

**Comment by djhvscf** [comment]
Can you provide a jsfiddle?? We can help you with your issue

**Comment by snahreed** [comment]
re-downloaded the latest versions of main and extension, and it fixed the problem.
Sorry, Maybe all my files weren't up to date.

thx for your time and for the great job guys :)
