### ISSUE TITLE
data-sort-name on column is ignored -- defaults to data-field

### ISSUE THREAD

**Issue by julianray** [wenzhixin/bootstrap-table#828]
Seems that the column option data-sort-name is ignored and *always* defaults to using the field name

**Comment by djhvscf** [comment]
Please provide a jsfiddle..  

See this: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

**Comment by wenzhixin** [comment]
A jsfiddle show your problem will save our time.

**Comment by djhvscf** [comment]
@julianray any update here??

**Comment by djhvscf** [comment]
If your issue is nor resolved, reopen it
