### ISSUE TITLE
Load function does not work for static data with server side pagination

### ISSUE THREAD

**Issue by ikilledmypc** [wenzhixin/bootstrap-table#830]
I have run into an issue in which I have data loaded from an external API with server side pagination enabled( a lot of data). The problem is that I want to be able to search on id and fill the table with the single result that this will deliver. With pagination on client side this works with the load method but with server side pagination it doesn't work.
I'm using the following code:
```
jQuery.getJSON('/api/subscriber/' + searchText, function (data) {
    var objects = "{\"total\":1, \"rows\":[" + data + "]}";
    $('#subscriber-table').bootstrapTable('load', objects);
 });
```
this used to work with client side pagination
```
jQuery.getJSON('/api/subscriber/' + searchText, function (data) {
	var objects = [data];
	$('#subscriber-table').bootstrapTable('load', objects);
});
```
Anyone know how I can make this work again using server side pagination?

**Comment by wenzhixin** [comment]
Try this:
```
// var objects = "{\"total\":1, \"rows\":[" + data + "]}";
var objects = {total:1, rows: data};
$('#subscriber-table').bootstrapTable('load', objects);
```

**Comment by jtrumbull** [comment]
@ikilledmypc timing issue? Try:

```javascript
$('#subscriber-table').on('load-success.bs.table', function(e, data){

    // Adding your code in here is just assuring that the pagination
    // response calls load() before you do.

    jQuery.getJSON('/api/subscriber/' + searchText, function (data) {
        var objects = { total:1, rows: data };
        $('#subscriber-table').bootstrapTable('load', objects);
    });

});
```

Question: Why are you calling the data from outside of `bootstrap-table`? Why not use the `queryParams` setting -or is `/api/subscriber/` seperate from your `data-url`?

**Comment by wenzhixin** [comment]
Any update? @ikilledmypc

**Comment by ikilledmypc** [comment]
sorry for the late reply.
I have no clue what went wrong the first time around but I'm guessing the escaping of the " chars screwed something up.
using:
````JavaScript
jQuery.getJSON('/api/subscriber/' + searchText, function (data) {
var objects = { total: 1, rows: [data] };
$('#subscriber-table').bootstrapTable('load', objects);
});
````
its now functioning like it should. 
Sorry about posting this and thanks for your help all, it was my error after all.
Keep up the good work!

**Comment by wenzhixin** [comment]
Never mind! Close this issue.
