### ISSUE TITLE
Show image on mouse over td

### ISSUE THREAD

**Issue by adonet** [wenzhixin/bootstrap-table#831]
It's posible to show an image when mouse over a specific row?

i'm try to use http://iamceege.github.io/tooltipster/ with bootstrap table on every row

it will be a list of users (from databse) with a photo of every  one, when i show a table of all, on mouse over i need to show the photo take from database table

Sorry for my english :)

**Comment by wenzhixin** [comment]
You can init to tooltip after data rendered, for example:
```
$table.on('post-body.bs.table', function () {
    $('.tooltip').tooltipster();
});
```

**Comment by djhvscf** [comment]
Close this issue because there is a solution
