### ISSUE TITLE
data-pagination-text not working

### ISSUE THREAD

**Issue by telle80** [wenzhixin/bootstrap-table#833]
Hi,

My table is defined as below:

<table id="table"
data-toggle="table"
data-classes="table table-no-bordered"
data-show-header="false"
data-pagination="true"
data-page-size="5"
data-page-list="[5, 10, 20, 50, 100, 200]"
data-pagination-first-text="First"
data-pagination-pre-text="Previous"
data-pagination-next-text="Next"
data-pagination-last-text="Last"
>

But the data-pagination-first-text along with the ones below does not change the text, it's still arrows displayed instead of text for the pagination.

Also the line data-classes="table table-no-bordered" does not work. My borders are not removed.

I have checked so I'm using the right .css and .js files I'm sure of it. What could be wrong?

**Comment by djhvscf** [comment]
Can you provide a jsfiddle with example?

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/pagination-custom-text.html

**Comment by DrunkLife** [comment]
src目录下面的代码和 dist目录的代码不一致引起的

**Comment by stephen1944** [comment]
Yes, I encounter the same issue.

**Comment by djhvscf** [comment]
See this: https://github.com/wenzhixin/bootstrap-table-examples/issues/28

**Comment by djhvscf** [comment]
You have to use the src code until the next release

**Comment by cindymarie** [comment]
hi! Is this issue already solved in the latest release? I'm still encountering the same issue. :(
