### ISSUE TITLE
Injected html doesn't get CSS style

### ISSUE THREAD

**Issue by rizvisarwar** [wenzhixin/bootstrap-table#838]
How can I get bootstrap-table styles in HTML (partial view) injected by Ajax call? I want to use the Checkbox feature in a table.

**Comment by djhvscf** [comment]
Can you provide a jsfiddle please??

**Comment by rizvisarwar** [comment]
Hello djhvscf, I don't know how to create a jsfiddle with the scenario I have!
I have a partial view, where I have a table like this:
<table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th></th>
                <th>ID</th>
                <th>Some other headers...</th>                
            </tr>
        </thead>
        <tbody>I get data from the Model object passed to this view</tbody>
</table>

From another View I call a JavaScript function, which does an AJAX call to a controller method. The Controller method returns the PartialViewResult (the Partial View with table). In the SUCCESS of the AJAX call I inject the returned data in a DIV tag of my View.
I have imported the bootstrap-table css and script in the Layout. So I get them working in the main View, but they don't work in the injected PartialView.

**Comment by jorgemejia** [comment]
Try with this:
```javascript
$.ajax
            ({
                type: "POST",
                url: page,
                async : true,
                success: function(a)
                {
                    $('#div_container').append(a).trigger("create");
                }
            });
```

**Comment by rizvisarwar** [comment]
@jorgemejia , thanks for your reply but still it doesn't work for me.
* I get the Bootstrap style and JavaScript working in the injected html view. But not bootstrap-table!
I have imported the Style and Script files in the <head> section of the _Layout.cshtml file in this way:
@Styles.Render("~/Content/css")
@Styles.Render("~/Content/bootstrap.min.css")
@Styles.Render("~/Content/bootstrap-table.css")
@Styles.Render("~/Content/datepicker.css")
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
@Scripts.Render("~/Scripts/bootstrap.min.js")
@Scripts.Render("~/Scripts/bootstrap-table.js")
@Scripts.Render("~/Scripts/bootstrap-datepicker.js")
@Scripts.Render("~/Scripts/Utils.js")
Is there anything wrong in the sequence of the import ?!
PS. I'm developing with ASP.NET MVC 5.

**Comment by jorgemejia** [comment]
You can use firebug, a complement for firefox and you can check if the styles are loaded.
I guess you forget for the Styles for the bootstrap table.

bootstrap-table.css

or you can use something like this to import your styles in ASP
<link href="<%= Me.ResolveClientUrl("~/css/Estilo.css") %>" rel="stylesheet">

**Comment by wenzhixin** [comment]
@rizvisarwar does it work now?

**Comment by rizvisarwar** [comment]
@wenzhixin Hi, thanks for the concern. It didn't work. I solved the problem by implementing my own JavaScript code.

**Comment by wenzhixin** [comment]
OK, can we close this issue?

**Comment by rizvisarwar** [comment]
Yes we can.
