### ISSUE TITLE
Records deleted when adding new row on filtered table

### ISSUE THREAD

**Issue by alexylem** [wenzhixin/bootstrap-table#839]
I'm facing an issue when I prepend a new record on a table that is filtered using the search field.

See below jsfiddle:
http://jsfiddle.net/alexylem/e3nk137y/1446/

1) Search for a text so that is returns no row (ex: "qldkflkqdhflk")
2) Click on `New` button
3) Clear the search filter
=> Only the new record remains, all the rest seems to be lost.

I managed to workaround it by, on `New`:
1) Manually clear the search filter:
```javascript
$('.bootstrap-table .search > input').val('').trigger('keyup');
```
2) Wait at least boostrap table search timeout to add the row:
```javascript
setTimeout (function () {
    $table.bootstrapTable ('prepend', record); // needs nosort !
}, 1000); // has to be greater than bootstrap table searchtimeout
```

Which is terribly dirty.

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/e3nk137y/1447/

**Comment by alexylem** [comment]
Proposed code seems to work fine.
Thanks a lot, great job!
