### ISSUE TITLE
Rows hidden by Search filter are not returned by getData

### ISSUE THREAD

**Issue by alexylem** [wenzhixin/bootstrap-table#840]
It seems that when filtering a table using the build-in bootstrap table search, calling `getData` method does not return rows that are not part of the search results.

See below jsfiddle:
http://jsfiddle.net/alexylem/e3nk137y/1448/

According to the documentation, should return loaded data, and not visible data.
Thanks in advance for taking a look.

**Comment by djhvscf** [comment]
I think the documentation has a bad description about this method... This method will return the data in the table at the moment that it is called

**Comment by alexylem** [comment]
Ok, after looking at the bootstrap table source, I managed to access the raw data by:
```js
$('#table').bootstrapTable('getOptions').data
```
jsfiddle updated:
http://jsfiddle.net/alexylem/e3nk137y/1449/

I let you close the ticket unless you want to keep it for documentation update.
Alex.

**Comment by djhvscf** [comment]
Ok, great! We will update the documentation.. And also you don't need to do this:

       $('.bootstrap-table .search > input').val('azerty').trigger('keyup')

You have to use the data-search-text option to set a default value in the search textbox

**Comment by alexylem** [comment]
Sure, I replicated this trick from my own code to simulate an end user search post table initialization. (to replicate my use-case) - was indeed not the straightest path to reproduce this issue :smile:
Thanks a lot for your time. :+1:
