### ISSUE TITLE
Freeze/Lock left Column

### ISSUE THREAD

**Issue by SarahD** [wenzhixin/bootstrap-table#841]
Hi guys,
Loving your plugin! By any chance, is there a way to freeze or lock the left column upon horizontal scrolling?

All the best,
Sarah

**Comment by djhvscf** [comment]
Hi @SarahD 

We are working on it.. I'm trying to finish it before the next release

**Comment by SarahD** [comment]
Thank you so much!

**Comment by djhvscf** [comment]
Close this issue because it is the same of https://github.com/wenzhixin/bootstrap-table/issues/554 and https://github.com/wenzhixin/bootstrap-table/issues/265
