### ISSUE TITLE
IE >8 Fixed TH dissapear if table has a height

### ISSUE THREAD

**Issue by ssalaberry** [wenzhixin/bootstrap-table#842]
IE 11
![image](https://cloud.githubusercontent.com/assets/8443838/7481156/66852e68-f344-11e4-867c-77ebe3746b6f.png)

HTML generated :
![image](https://cloud.githubusercontent.com/assets/8443838/7481202/bc0d7476-f344-11e4-80a4-8dc6fe03daea.png)

In FF works fine :

The THs have data 

![image](https://cloud.githubusercontent.com/assets/8443838/7481233/f21578ca-f344-11e4-88fe-96999cba5f6e.png)

I am working with 1.7.0 version of Bootstrap Table

My js code is :

<pre>
self.loadBalancePatrimonial = function(mes, moneda, unidad) {
    		var $table = jQuery('#balancePatrimonialList');
    		$table.bootstrapTable('destroy');
    		jQuery('#loadingModal').modal();
    		jQuery.post('bscPanelControlBalance.do?dispatch=consultar', 
        			{
    				'mes1': mes,
    				'codMoneda': moneda,
    				'codUnidad': unidad,
    				'enumTipoRelatorio': '19'
    			}, 
    			function(data){
    				jQuery('#loadingModal').modal('hide');
    				if (data.controlBalance){
    				self.mesActual(data.controlBalance.header[3]);
    				self.mesAnterior(data.controlBalance.header[4]);
    		    	self.mesDicAnterior(data.controlBalance.header[5]);
    		    	self.mesHomonimo (data.controlBalance.header[6]);
    				}
    				$table.bootstrapTable({
		 		        data: data.controlBalance.listRelatorio,
		 		        columns : self.columnsBalancePatrimonial(data.controlBalance.header),
			 		       height : '400'
		 		    });
    				$table.bootstrapTable('resetView');
    			});
        	};
</pre>

If I remove the height works well.

My markup is the following and the table is inside a bootstrap tab.

![image](https://cloud.githubusercontent.com/assets/8443838/7481492/aa5df136-f346-11e4-99b8-c352d7cc0f59.png)

**Comment by ssalaberry** [comment]
This is not a  bug the $table.bootstrapTable('resetView'); should be placed outside the ajax callback

<pre>
self.loadBalancePatrimonial = function(mes, moneda, unidad) {
            var $table = jQuery('#balancePatrimonialList');
            $table.bootstrapTable('destroy');
            jQuery('#loadingModal').modal();
            jQuery.post('bscPanelControlBalance.do?dispatch=consultar', 
                    {
                    'mes1': mes,
                    'codMoneda': moneda,
                    'codUnidad': unidad,
                    'enumTipoRelatorio': '19'
                }, 
                function(data){
                    jQuery('#loadingModal').modal('hide');
                    if (data.controlBalance){
                    self.mesActual(data.controlBalance.header[3]);
                    self.mesAnterior(data.controlBalance.header[4]);
                    self.mesDicAnterior(data.controlBalance.header[5]);
                    self.mesHomonimo (data.controlBalance.header[6]);
                    }
                    $table.bootstrapTable({
                        data: data.controlBalance.listRelatorio,
                        columns : self.columnsBalancePatrimonial(data.controlBalance.header),
                           height : '400'
                    });
                  
                });
                $table.bootstrapTable('resetView');
            };
</pre>

**Comment by djhvscf** [comment]
Thanks @ssalaberry

**Comment by ssalaberry** [comment]
Hey Dennis, If I change  the columns using showColumns/ hideColumns in IE > 8, outside of the ajax callback in IE the header disappears. If I change the import of the js from .min.js to .js and works fine,  I think there are some differences between .js and .min.js

Anyway the issue is solved :)

I just to let you know about it.

Regards

 

De: Dennis Hernández [mailto:notifications@github.com] 
Enviado el: jueves, 07 de mayo de 2015 13:27
Para: wenzhixin/bootstrap-table
CC: Santiago Salaberry
Asunto: Re: [bootstrap-table] IE >8 Fixed TH dissapear if table has a height (#842)

 

Thanks @ssalaberry <https://github.com/ssalaberry>
