### ISSUE TITLE
version 1.7.0 on sample page doesn't match version 1.7.0 of download

### ISSUE THREAD

**Issue by Ka3m0n** [wenzhixin/bootstrap-table#843]
After downloading ver 1.7.0, I couldn't see the same sort indicators as shown on the sample page below
http://issues.wenzhixin.net.cn/bootstrap-table/#options/basic-sort.html

To make my page work like the sample page above, I had to download a copy of the bootstrap-table.js and bootstrap-table.css from the sample page above and reference those files instead of using bootstrap-table.js and bootstrap-table.css in the dist folder from the "Getting Started Page" (http://bootstrap-table.wenzhixin.net.cn/getting-started/)

Even though both versions of the files say version 1.7.0 in the comment section at the top 
Using Beyond Compare, I identified numerous differences between the version provided in the download vs the version copied from the website sample page.

As one example, this is the difference in one CSS definitions explaining why I couldn't get my sort indicators to look like the example:

Snippet of bootstrap-table.css in dist folder from Getting Started page:
.fixed-table-container thead th .sortable {
    cursor: pointer;
}

Snippet of bootstrap-table.css copied from sample page:
.fixed-table-container thead th .sortable {
    cursor: pointer;
    background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAQAAADYWf5HAAAAkElEQVQoz7X QMQ5AQBCF4dWQSJxC5wwax1Cq1e7BAdxD5SL+Tq/QCM1oNiJidwox0355mXnG/DrEtIQ6azioNZQxI0ykPhTQIwhCR+BmBYtlK7kLJYwWCcJA9M4qdrZrd8pPjZWPtOqdRQy320YSV17OatFC4euts6z39GYMKRPCTKY9UnPQ6P+GtMRfGtPnBCiqhAeJPmkqAAAAAElFTkSuQmCC');
    background-position: right;
    background-repeat: no-repeat;
    padding-right: 30px;
}

**Comment by djhvscf** [comment]
Hi! 

That is because in the sample page we are using the last version comitted of boostrap-table.js/.css and we are not using the last release (v1.7.0)  why this? Because sometimes we need add some example or solution to the sample page and maybe that is not implemented in the las release yet.

**Comment by Ka3m0n** [comment]
gotcha. I think it might help a lot of people to clarify that the demo is using a yet-to-be-released version.  Our other developer and I have both spent a good bit of time trying to troubleshoot why our sort indicators weren't working like the example. We LOVE the library!!  Please keep up the great work!  :)

**Comment by djhvscf** [comment]
Yes, you're right. Thank you
