### ISSUE TITLE
Asynchronous updates to table

### ISSUE THREAD

**Issue by rfossella** [wenzhixin/bootstrap-table#844]
Hi - Question.
I have an existing bootstrap table with ~1500 entries.  When my app opens I have to update an arbitrary number of rows in the table - typically on the order of 500.  I am using the *updateRow* method.  The browser takes a noticeable hit/delay while updates occur since (I believe) I have a number of display methods being fired - e.g. turning true/false into checkmarks, dates, times using moment.js, etc.

Is there a way to do this as a background process - i.e. is there an *async* option to handle the updating or is this something I'd have to do?  Any info or guidance appreciated.

Thanks!

**Comment by djhvscf** [comment]
Oh! Let me think about this

**Comment by wenzhixin** [comment]
Because your data rows are very large(1500 entries), so when we handle the DOM, the browser takes a noticeable hit/delay, I suggest you can use the pagination feature instead. We do not deal with this problem in the moment.
