### ISSUE TITLE
Unexpected search results

### ISSUE THREAD

**Issue by mahdilamb** [wenzhixin/bootstrap-table#846]
Hi,
Can I suggest removing line 241 of bootstrap-table-filtercontrol.js? It updates the search to only show the last filter result (may provide unexpected results). However, removing it means you can have both a global search with individual filters, unless I am missing something?

Mahdi

**Comment by djhvscf** [comment]
If we delete that line.. how can we search into the data?

**Comment by djhvscf** [comment]
@mahdilamb can you provide a jsfiddle??

**Comment by mahdilamb** [comment]
Hi,

I've removed the line in my local version and it seems fine



Mahdi

**Comment by djhvscf** [comment]
Any update here?

**Comment by mahdilamb** [comment]
Hi,

It is fine to close this. I shall just delete the line from my own version.


Mahdi
