### ISSUE TITLE
filter does only work if not self-defined

### ISSUE THREAD

**Issue by Adam-Harrys** [wenzhixin/bootstrap-table#847]
Hi guys

For my table I use the bootstrap-table-filter from here:
https://github.com/lukaskral/bootstrap-table-filter

Case 1
I defined a filter:

![image](https://cloud.githubusercontent.com/assets/9960571/7493464/5a61721e-f401-11e4-9ab8-a9af87691b5c.png)

On the website I saw the filter:

![image](https://cloud.githubusercontent.com/assets/9960571/7493492/89d3727c-f401-11e4-9eca-d4d7619403cc.png)

But if I now set the filter, it doesn't do anything!

Case 2
In a second step I did not define any filters and let the application itself create the filters. Then it worked. But the filters did not contain all of the values I wanted. So I have to create the filters myself.

Does anyone have any idea, what I did wrong or how I can fix it?

Many thanks,
adam

**Comment by djhvscf** [comment]
Can you help us with this? @hhurz

**Comment by djhvscf** [comment]
Any update here?

**Comment by wenzhixin** [comment]
Please go to repo https://github.com/lukaskral/bootstrap-table-filter/issues to discuss this issue, thanks.
