### ISSUE TITLE
Tooltip and other attributes on table tags gets deleted or altered by bootstrap table

### ISSUE THREAD

**Issue by PlippiePlop** [wenzhixin/bootstrap-table#850]
bootstrap table is messing around with attributes inside table  tags. It removes attributes or changes the name of data attributes.

See example here with bootstrap tables: 
inspect the TH elements all attributes are removed
inspect TD element, attributes removed or altered.
https://jsfiddle.net/zac8z18m/1/

And without bootstrap tables here:
https://jsfiddle.net/8dou6d7u/1/

**Comment by djhvscf** [comment]
You can see this: https://xenforo.com/community/threads/html-5-data-attributes-and-case-sensitivity.15609/ but we are working to solve this in our code

**Comment by djhvscf** [comment]
See this: https://jsfiddle.net/djhvscf/zac8z18m/2/

**Comment by PlippiePlop** [comment]
A big improvement! but some tags attributes are still modified:

<thead><tr data attributes> OK
<thead><tr><td data attributes>  attributes are removed

<tbody><tr data-attributes>  data-some-option converted to data-someoption
<tbody><tr><td data-attributes> OK

<tfoot><tr data-attributes> OK
<tfoot><tr><td data-attributes> OK

, the TH tag all data attributes are removed. the data attributes of TR tag of body are modified if it contains multiple dashes. (data-some-option="blabla" > data-someoption

Fiddle:
https://jsfiddle.net/y1avf8k8/4/

**Comment by djhvscf** [comment]
See this: https://jsfiddle.net/djhvscf/y1avf8k8/5/

**Comment by PlippiePlop** [comment]
Only the TH tag needs some attention. All others test seems to work ok.

**Comment by djhvscf** [comment]
Great!

**Comment by Wardrop** [comment]
This is still happening in v1.8.1? Adding data-toggle="table" to my table removes my width and style attributes from th and td elements.

**Comment by wenzhixin** [comment]
Use `src` code and try again.

**Comment by serlogo53** [comment]
is it possible to do this on json data source table?

**Comment by djhvscf** [comment]
I think yes.. Do you have any problem with this? @serlogo53

**Comment by serlogo53** [comment]
i need it. i couldn't do along a week. https://jsfiddle.net/djhvscf/y1avf8k8/5/ for example on this example if we change to source to json data how can we work tooltip and cell style. can you help me. thanks.

**Comment by djhvscf** [comment]
Do you have the same example but using the latest version of bootstrap-table?? @serlogo53

**Comment by serlogo53** [comment]
Yes. Same example with hson datasource. İ made with data-formatter but style not working. İn your sample wonderfull
