### ISSUE TITLE
How do you add conditional class?

### ISSUE THREAD

**Issue by zardaloop** [wenzhixin/bootstrap-table#851]
Hi,
Is it possible to add a conditional class to the column something similar to ng-class in angular?
I am currently using formatter do that, but the problem with formatter is that then I can't search anything.

**Comment by djhvscf** [comment]
Can you provide a jsfiddle?? Here is an example with formatter -> http://jsfiddle.net/wenyi/e3nk137y/21/light/

**Comment by wenzhixin** [comment]
You can use `rowStyle` and `cellStyle`, example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/table-style.html.

**Comment by zardaloop** [comment]
Cool thanks :)
