### ISSUE TITLE
Search un-hides hidden rows

### ISSUE THREAD

**Issue by achaffman** [wenzhixin/bootstrap-table#852]
I mentioned this as a comment, but i figured I would open a new issue specifically.  

For others,if you hide rows using the ```hideRow``` method and then perform a search - it clears hidden rows and then just hides the rows that don't match the search.  There will need to be a separate variable to hold the forcibly hidden rows that should be reapplied after the search does its thing. 

@djhvscf, i noticed you did reply saying @wenzhixin is working on it.  Thanks for the update.

**Comment by djhvscf** [comment]
Same of https://github.com/wenzhixin/bootstrap-table/issues/750 .. We are working on it.. Close this issue
