### ISSUE TITLE
Removing a row

### ISSUE THREAD

**Issue by promogest** [wenzhixin/bootstrap-table#854]
I manage to remove a row easily when rows are different but i have a case when many rows can be with the same data. ( using a barcode reader multiple times on the same product ) 
is it possibile something like that :
$table.bootstrapTable('remove', row);
or a way to have an unique rowid to use ? 
thanks

**Comment by djhvscf** [comment]
See this;  http://jsfiddle.net/djhvscf/e3nk137y/1492/

**Comment by promogest** [comment]
Hi, Thanks, if i correct understanding the jsfiddle not i can select the row just by a value in a determinated column selected by data-unique-id="contatore"
i modified the jsfiddle into this http://jsfiddle.net/ofbLfgrr/ and i tried to use the first column but whit no luck. if i understand correctly i can't still no select a row just by "inside the row" o just by the row itself or the index of the row.. If in your jsfeddle i have all the same rows with the same forks_count it delete ALL the rows. Am i right?

**Comment by djhvscf** [comment]
For use this method...

You have to set the data-unique-id with a valid field.. This field must be in your data.. Right now you're using contatore but it is not in the data

**Comment by tm1000** [comment]
This seriously needs better documentation. The only way I actually figured out how to make it work was with what @djhvscf said. With that I was able to do the following:

```
<table data-toggle="table" data-unique-id="_id" data-sort-name="stargazers_count" data-sort-order="desc">
```

Then I could delete items by their actual ID (The HTML ID)!
```
$('table').bootstrapTable('removeByUniqueId', "Default")
```

**Comment by promogest** [comment]
@tm1000 have you a jsfiddle to view? 
thanks

**Comment by tm1000** [comment]
@djhvscf already gave you the hint. You can't delete based on the numberFormatter its dynamically adding. The column data has to have previously existed.

See this fiddle: http://jsfiddle.net/rdbyk4aa/

**Comment by djhvscf** [comment]
Sorry but I don't understand what you are saying!! @tm1000

**Comment by tm1000** [comment]
@djhvscf no worries. It will be nice when all of these new features have examples. That is all :-)

**Comment by xterwolf** [comment]
My solution;

```
      'click .row_delete': function (e, value, row, index) {

        var table_data_array = $('#ttable').bootstrapTable('getData');
        table_data_array.splice(index, 1);

        $('#ttable').bootstrapTable({
              height: 450,
              columns: [....],
              data: table_data_array
        });
     }
```
