### ISSUE TITLE
Table resizes after refresh

### ISSUE THREAD

**Issue by Adam-Harrys** [wenzhixin/bootstrap-table#855]
Hi guys

If I use the bootstrap-table-filter extension from @lukaskral (https://github.com/lukaskral/bootstrap-table-filter), the table changes his height after a refresh.
How can I prevent that?

Many Thanks,
Adam-Harrys

**Comment by djhvscf** [comment]
Can you create a jsfiddle with your issue?? please

**Comment by djhvscf** [comment]
Any update here?

**Comment by djhvscf** [comment]
You can use the resetView method to that.. If this is not the solution reopen this issue
