### ISSUE TITLE
Results on JSON property

### ISSUE THREAD

**Issue by jimmywyatt** [wenzhixin/bootstrap-table#856]
Hi,

The JSON table values from our web API are normally returned as a sub property i.e. 
{
success: true,
message: 'Hi',
results: [,,,]
}

Is it possible via the attributes to tell it to look at that collection?

i.e. <table data-url="/examples/bootstrap_table/data" data-collection="results" >

Thanks

**Comment by djhvscf** [comment]
Maybe you can use the flatJSON: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/flatJSON.html

**Comment by jimmywyatt** [comment]
Thanks, that look like it will probably do it.
