### ISSUE TITLE
Search doesn't work with formatter

### ISSUE THREAD

**Issue by zardaloop** [wenzhixin/bootstrap-table#857]
Hi Guys,

If you implement the bootstrapper-table the way I have implemented in this Jsfiddle http://jsfiddle.net/zardaloop/8eccoqec/ , then search function doesn't work.

does anyone know a quick fix for this? I desperately need a solution to this issue. 

Many thanks in advance.

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/8eccoqec/2/ you must to set the field in the column options

**Comment by zardaloop** [comment]
Thanks @djhvscf Denniz, that was it. :)

**Comment by djhvscf** [comment]
Sounds great! Close this issue
