### ISSUE TITLE
export all data using bootstrap-table-export.js

### ISSUE THREAD

**Issue by stephen1944** [wenzhixin/bootstrap-table#858]
At this time, I just could export one page data, how could I export all data by the extensions of export?

**Comment by djhvscf** [comment]
See this: https://github.com/hhurz/tableExport.jquery.plugin

**Comment by wenzhixin** [comment]
Use `pageList` option to set `ALL`, then export the data.
Or use `showPaginationSwitch` to disable pagination and then export the data.

**Comment by songqinghehe** [comment]
Use pageList option to set ALL, then export the data.
Or use showPaginationSwitch to disable pagination and then export the data.
=================================================
So，this is to get all the data?

**Comment by jwwb681232** [comment]
@wenzhixin In fact, this method still exports a page of data
