### ISSUE TITLE
Integration with React.js?

### ISSUE THREAD

**Issue by komocode** [wenzhixin/bootstrap-table#860]
Sorry if it's is more of a React.js question than a bootstrap-table question. I'm trying to use this in React.js. 

I post this on StackOverflow: http://stackoverflow.com/questions/30180290/react-js-bootstrap-table-working-only-on-first-load-but-transitions-break-the

Basically bootstrap-table works on first load, but when I transition to different components using react-router, it looks like bootstrap-table.js magically "unloads" and table no longer works. Any ideas on how to fix this?

**Comment by djhvscf** [comment]
do you have some jsfiddle?? We can help you

**Comment by komocode** [comment]
Haven't used JSFiddle, trying to set this up, but can't get a basic table rendered in React. This is what I have so far:
https://jsfiddle.net/uzgkzjcp/5/

**Comment by djhvscf** [comment]
The fildde that you provided is not working

**Comment by wenzhixin** [comment]
Try this: https://jsfiddle.net/wenyi/uzgkzjcp/7/

**Comment by eddyLazar** [comment]
Here is another way of cooking it with react, the advantage that you can use all table options as Component props.

https://gist.github.com/eddyLazar/e0f3411d2c2ea6d756cb3eb0f9e4d815
