### ISSUE TITLE
当用append后，updateRow有问题

### ISSUE THREAD

**Issue by baiheng** [wenzhixin/bootstrap-table#861]
var data = [{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
	{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
	{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
	{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remssssssark"},
	{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"}];
	$("#second_table").bootstrapTable('append', data);
	$("#second_table").bootstrapTable('append', data);
	$("#second_table").bootstrapTable('append', data);
	$("#second_table").bootstrapTable('append', data);
	$("#second_table").bootstrapTable('append', data);

       $('#second_table').on('dbl-click-row.bs.table', function (e, row, $element) {
            var i = $element.index();
            $('#second_table').bootstrapTable('updateRow', {"index": i, "row": {"id": 0, "produce_id": "<button>sss</button>", "produce_name": "w11111", "formula": "911110w*09", "remark": "remark"}});
   });
       // 这里会出现多行数据被替换，求解决

**Comment by djhvscf** [comment]
First: can you translate it to english??
Second: provide a jsfiddle, please

**Comment by djhvscf** [comment]
Any update here?

**Comment by baiheng** [comment]
oh, it's my coding problem, above coding, after the var "data" appending into bootstraptable, when i update one row, it would have the deep copy and light copy problem. 
so the resolution is when i append into bootstraptable, the data should be new one. 

thx

like this:

var data = [{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remssssssark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"}];
$("#second_table").bootstrapTable('append', data);
var data = [{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remssssssark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"}];
$("#second_table").bootstrapTable('append', data);
var data = [{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remssssssark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"}];
$("#second_table").bootstrapTable('append', data);
var data = [{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remssssssark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"}];
$("#second_table").bootstrapTable('append', data);
var data = [{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remssssssark"},
{"id": 0, "produce_id": 1, "produce_name": "w1", "formula": "90w*09", "remark": "remark"}];
$("#second_table").bootstrapTable('append', data);

**Comment by wenzhixin** [comment]
OK
