### ISSUE TITLE
how to persist state checkbox after search/filter

### ISSUE THREAD

**Issue by Bajnep** [wenzhixin/bootstrap-table#862]
How do I keep the state checkbox after applying the search filter? I load my data from an url, I get a json with the field "state". When the table loads, the checkboxes are checked when they're supposed to. However, after I filter the table, those checkboxes are cleared.

html
```html
    <table id="#tbl_xy"></table>
```
javascript
```javascript
	$('#tbl_xy').bootstrapTable({
		height: 500,
		method: 'get',
		url: 'http://api/ajax_get_json.php',
		queryParams: function (p) {
			return { id: 1234 }
		},
		pagination: false,
		search: true,
		showColumns: true,
		showRefresh: true,
		clickToSelect: true,
		selectItemName: 'stateCheck',
		columns: [
			{
				field: 'state',
				checkbox: true
			},
			{
				field: 'id',
				title: '#',
			},
			{
				field: 'city',
				title: 'City',
			},
			{
				field: 'name',
				title: 'Name',
			},
			{
				field: 'address',
				title: 'Address'
			}
		],
	});
```
json
```json
	[{"id":"1234","city":"Gotham","name":"Batman","address":"Wayne Manor","state":true}]
```

**Comment by djhvscf** [comment]
Use the data-maintain-selected="true" table option

**Comment by Bajnep** [comment]
awesome, thanks. to anyone who's using this, use getAllSelections to get all rows, not just the ones displayed.

**Comment by scaret** [comment]
thanks!

**Comment by FritzMatthaeus** [comment]
Hi,

sorry to reopen this issue. I am having the same issue, that my checkboxes get unchecked once a filter or pagination is used. maintainSelected: true did not do the trick for me, or i applied it the wrong way. Here is my code.

`var columns = [{
		field: 'offerId',
		title: 'Angebot',
		order: 'asc',
		sortable: true
	}, {
		field: 'title',
		title: 'Title',
		sortable: true
	}, {
		field: 'clients',
		title: 'Kunden',
		formatter: 'formatterClients',
		events: window.clientsEvents
	}, {
		field: 'active',
		title: 'Aktiv',
		checkbox: true,
		sortable: true
	}, {
		field: 'push',
		formatter: "formatterPush",
		events: window.pushEvents,
		title: 'Push'
		//	}, {
		//		field: 'sender',
		//		title: 'Erstellt von',
		//		sortable: true
	}, {
		field: 'delete',
		title: 'Löschen',
		events: window.deleteEvents,
		formatter: 'deleteFormatter'
	}];


	//console.log(data);
	$('#tableOffers').bootstrapTable('destroy');

	$('#tableOffers').bootstrapTable({
		columns: columns,
		pagination: true,
		pageSize: 100,
		pageList: [10, 25, 50, 100],
		search: true,
		data: data,
		width: '100%',
		sortable: true,
		maintainSelected: true
	});
`
Where did i do wrong?

Thanx a lot!

**Comment by UtechtDustin** [comment]
@FritzMatthaeus please provide us an example using our [Editor](https://live.bootstrap-table.com/) instead of posting code :)

**Comment by FritzMatthaeus** [comment]
@UtechtDustin better this way? Sorry, new to this

**Comment by UtechtDustin** [comment]
Your example dont work, on the left site you have to post your html code (inklusive <script> tags).
So on the right site you see the result.

**Comment by FritzMatthaeus** [comment]
@UtechtDustin Thank you for patience. I posted a working code example.

**Comment by UtechtDustin** [comment]
Können auch gerne auf deutsch weiter schreiben.
Wo hast du den dein Beispiel gepostet ?
Das Beispiel von oben funktioniert nicht, da du kein script tag benutzt hast.
Auf der rechten Seite musst du nach dem du auf "Run" klickst die Tabelle sehen können!

**Comment by FritzMatthaeus** [comment]
https://live.bootstrap-table.com/code/FritzMatthaeus/1686

Bei mir läuft's mit run

**Comment by UtechtDustin** [comment]
Den Link hast du auch noch nicht gepostet ;)
Du hast statt `maintainMetaData` `maintainSelected` genutzt, es wurd eim laufe der Zeit umbenannt.
In unsere [Dokumentation](https://bootstrap-table.com/docs/api/table-options/#maintainmetadata) steht immer die aktuellen namen!

Dein Beispiel mit der richtigen option: https://live.bootstrap-table.com/code/UtechtDustin/1689

**Comment by FritzMatthaeus** [comment]
@UtechtDustin : Thank you very much. Sorry, i did see maintainMetaData, but i did not get that this one replaced the maintainSelected. Thank you very much for your immediate help. Just sticking to english in case anyone else reads the post 👍

**Comment by UtechtDustin** [comment]
No problem, your welcome!
