### ISSUE TITLE
Why popover does not work with bootstrap-table?

### ISSUE THREAD

**Issue by jipexu** [wenzhixin/bootstrap-table#864]
I use bootstrap-table with some bootstrap-popover and or tooltip. When i resize the window or use some table function (example: search or toggle or sort).Then the popover or tooltip does not work any more. (for example the tooltip become as a standard html tooltip.). What i miss? or it is some problem? Any help is welcome! I tried with a standard bootstrap table and i do not find this problem.

I just add a JSFiddle here test with tooltip and popover

http://jsfiddle.net/jipexu/8vgk5626/12/

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/8vgk5626/14/

**Comment by jipexu** [comment]
waoow ! many thanks !! It's works !
Even if i not understand why and what is the utility of the name and args argument ?..
Thanks

**Comment by djhvscf** [comment]
You can do things with that.. see the documentation: http://bootstrap-table.wenzhixin.net.cn/documentation/#events

**Comment by serlogo53** [comment]
if we try to do this sample to json data source table. how can we do it?

**Comment by djhvscf** [comment]
I'm not sure what you want.. Can you explain a little bit more?? @serlogo53
