### ISSUE TITLE
getSelections() not working with search

### ISSUE THREAD

**Issue by adc90** [wenzhixin/bootstrap-table#866]
I've set up a table where I set maintainSelected to true and I'm having trouble getting the correct  selections from getSelections() when I search for a record. Whenever I search for a record and call getSelections() I'm only able to get those selections are visible in the search. However when I clear the search all my previous selections are still saved. 

[jsfiddle](https://jsfiddle.net/e3nk137y/1534/)

**Comment by djhvscf** [comment]
@adc90 that is the expected behavior

**Comment by adc90** [comment]
@djhvscf I thought that might be the case since everything still worked when I cleared it lol. Is there any way to get around this?

**Comment by wenzhixin** [comment]
You can use `getAllSelections` method @adc90.

**Comment by adc90** [comment]
@wenzhixin That works great, thanks!

**Comment by djhvscf** [comment]
Is it not working yet?

**Comment by adc90** [comment]
@djhvscf Sorry, I wasn't familiar with the issue system I didn't know it would reopen it every time lol. It is working with the latest version. However I don't think it's included in the distribution yet. I'm also having an issue with the arrows for the ascending and descending indicators [not being clipped correctly](http://imgur.com/hZho8dh). Although that might be something to do with me installing the css incorrectly.

**Comment by djhvscf** [comment]
Yes, I think you have to use the src master code for now.. can I close this issue?

**Comment by adc90** [comment]
@djhvscf Sure, thanks!
