### ISSUE TITLE
custom scrollbar ( perfect-scrollbar )

### ISSUE THREAD

**Issue by nicosalto** [wenzhixin/bootstrap-table#869]
Hi,
iam using bootstrap-table and it looks great. But i want to have controls over the look of the scrollbar.
Iam using perfect-scrollbar in my website and it looks good but i can't figure out how to use it on bootstrap-table.

This is the website:
http://noraesae.github.io/perfect-scrollbar/
and this is how to use it:
$(function() {
    $('#resizable').perfectScrollbar();
});

Would you know which object i should apply it onto to get those scrollbar in the table ?

**Comment by djhvscf** [comment]
See this as example: http://jsfiddle.net/djhvscf/8vgk5626/14/

**Comment by nicosalto** [comment]
Thanks for your answer djhvscf,
i think i understand why you are referring to this example; i should be able to target an element such as : $('[data-toggle="tooltip"]'), to apply the scrollbar function.
My issue is i don't know which element i should target to make the perfect-scrollbar works.
I tried on the table and the tbody but the scrollbar always stay i basic mode...

**Comment by djhvscf** [comment]
Can you provide a jsfiddle?? we will save a lot of time

**Comment by djhvscf** [comment]
Any update here?

**Comment by djhvscf** [comment]
Ok, @nicosalto if you have the issue, reopen it.
