### ISSUE TITLE
update bootstrap-table with javascript function.

### ISSUE THREAD

**Issue by nicosalto** [wenzhixin/bootstrap-table#870]
This is a basic question but i can't figure it out.
I start my bootstrap-table that way:
$queue_table.bootstrapTable()

then later i want to update the data, but can't figure a way to do it:
$queue_table.bootstrapTable({data:  {...} }); -> doesnt work
$queue_table.bootstrapTable('refresh', {data: {...} }); -> doesnt work
i tried with data-ajax="ajaxRequest" in the table options but doesnt work either (maybe iam not declaring the ajaxRequest the right way ?  )

( i can't use the url/json solutions as i am not using a web server, data come from a QTapp/python )

Any help is welcome! Thanks

**Comment by djhvscf** [comment]
did you see this http://issues.wenzhixin.net.cn/bootstrap-table/#methods/refresh.html ?

**Comment by nicosalto** [comment]
Hi djhvscf,
Yes i saw this. But in my case i don't access the datas from a web url such as  "../json/data1.json".
Iam embedding a webpage into a python QWebView(). The way i access the data is with a javascript object such as object.get_jobs( id ).

So i need a javascript function such as $queue_table.bootstrapTable('refresh', {data: {...} }); 
Is this supposed to work btw ?

**Comment by djhvscf** [comment]
Use the load method.. if it does not work then provide a jsfiddle

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/load.html
