### ISSUE TITLE
Several Components on the same page...  Possible or Not ? 

### ISSUE THREAD

**Issue by petertiny** [wenzhixin/bootstrap-table#871]
Is it possible to use several bootstrapTable components on the same page ?
I try it and only the first table has become a table " Bootstat - Table " , even though I switched the two lines !

$('#bstActExp1').bootstrapTable();
$('#bstActBudget1').bootstrapTable();

Thanks a lot 
Peter

**Comment by djhvscf** [comment]
Yes it is possible of course.. can you provide a jsfiddle?

**Comment by wenzhixin** [comment]
Use attribute or class, for example `data-toggle="table"` or `$('.table').bootstrapTable();`

**Comment by djhvscf** [comment]
@wenzhixin I think we can close this issue
