### ISSUE TITLE
Multiple column headers with data-checkbox="true" checks all boxes in table

### ISSUE THREAD

**Issue by banderson5144** [wenzhixin/bootstrap-table#872]
If I have something similar to this

```
<table>
	<thead>
		<tr>
			<td data-checkbox="true"/>
			<td data-checkbox="true"/>
			<td data-checkbox="true"/>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Test</td>
			<td>Test</td>
			<td>Test</td>
		</tr>
	</tbody>
</table>
```

And I check the column header on any column, it marks all cells. Any way we can get it to respect just the column that is clicked.

**Comment by djhvscf** [comment]
Provide a jsfiddle with your code.. it will save our time

**Comment by banderson5144** [comment]
https://jsfiddle.net/e3nk137y/1574/

**Comment by djhvscf** [comment]
This is an issue

**Comment by banderson5144** [comment]
When you think this will be fixed?

**Comment by jimgit** [comment]
anderson5144  - As a workaround, can you use the data-formatter to return html for a checkbox? 

http://jsfiddle.net/3u8ydz7s/

**Comment by banderson5144** [comment]
@jimgit This does not solve the issue at hand.

**Comment by jimgit** [comment]
Could you explain what your overall intention is - what are your trying to accomplish?

**Comment by 3cc3h0m0** [comment]
hi, same problem here. i am trying to make table with 12columns - every one is a checkbox.
everything seems ok but json is not updated when i check or uncheck the boxes..

**Comment by jimgit** [comment]
I had to do this before and used the bootstraptable updateRow method.  I used something like this:
   $('#table').bootstrapTable('updateRow', { index: index, row: { IsDelegate: newIsDelegate, IsAlternate: newIsAlternate } });

**Comment by jimgit** [comment]
The way I did this, I used the DATA-FORMATTER to return a checkbox, then jquery setup on the checkbox check event and built the updated row and also sent it back to the server via ajax.  This gave the local copy the change if the user scrolled or filtered and instantly changed the source data at the server.

**Comment by banderson5144** [comment]
I feel like this has become a little off the original topic

**Comment by 3cc3h0m0** [comment]
@jimgit but that's a working hack not a good solution.
any other suggestions please?

**Comment by jimgit** [comment]
I think the checkbox function of the bootstraptable is a RECORD SELECTOR
not a multiple column data input method.  You may want to look at another
package or modify the base code yourself.  In my case,  I had to implement
additional business logic tied to the checkbox interaction (i.e. click
column 2 checkbox , turns off column 5 and 6 checkboxes - also had to limit
the total checked box count per group of data).

On Thu, May 28, 2015 at 5:23 PM, Damian <notifications@github.com> wrote:

> @jimgit <https://github.com/jimgit> but that's a working hack not a good
> solution.
> any other suggestions please?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/wenzhixin/bootstrap-table/issues/872#issuecomment-106616898>
> .
>



-- 
Jim Kennelly
THE-E-OFFICE
(219) 741-7304

**Comment by wenzhixin** [comment]
@jimgit is right, in our plugin the checkbox function is a RECORD SELECTOR not a multiple column data input method. Please use formatter to do what you want: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/987.html
