### ISSUE TITLE
Data json doesnt work

### ISSUE THREAD

**Issue by MrAjdin** [wenzhixin/bootstrap-table#873]
How can i display mid, author and title in this json in bootstrao table? i tried using javascript but nothing works and i getting error no matching records found: https://cdn.rawgit.com/MrAjdin/BalkanBot/master/blackList/NSFW.json

**Comment by banderson5144** [comment]
What does your table HTML look like?

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#350.html

**Comment by MrAjdin** [comment]
@djhvscf it still wont display this can you explain how there is 1,  2 and 3 numbers https://cdn.rawgit.com/MrAjdin/BalkanBot/master/blackList/NSFW.json

**Comment by wenzhixin** [comment]
This is cross domain problem, please put the json file and html file the same domain @MrAjdin .
