### ISSUE TITLE
duplication of requests options and get

### ISSUE THREAD

**Issue by setis** [wenzhixin/bootstrap-table#874]
When called via Javascript is duplication of requests 1 - options 2 - get I need only one request get tried to establish settings through  
```
$.ajaxSetup({
            global: true,
            type: "GET"
        });
```
![screen] (http://rghost.ru/6LbMYyGj9/thumb.png)
http://rghost.ru/6LbMYyGj9/image.png

**Comment by djhvscf** [comment]
Can you provide a fiddle?

**Comment by wenzhixin** [comment]
Do not have this problem in our example: http://issues.wenzhixin.net.cn/bootstrap-table/, please check your code.
![1](https://cloud.githubusercontent.com/assets/2117018/7833787/02966b6a-049c-11e5-9450-b37e8f15dba9.png)
