### ISSUE TITLE
How to do ajax polling in a table td?

### ISSUE THREAD

**Issue by sleefd** [wenzhixin/bootstrap-table#875]
Hi:
I want to display a processbar in a table column.
The processbar will change its width according to ajax polling.
I dont know how to do ajax request in a table td. 
I'm trying to use formatter, but seems to make no effects.
Can you help?

**Comment by djhvscf** [comment]
Please provide a fiddle

**Comment by wenzhixin** [comment]
You can use `setTimeout` or `setInterval` function to do ajax request or websocket(html5 feature), and then update the table.
