### ISSUE TITLE
No matching records found when getting data server side

### ISSUE THREAD

**Issue by kwingat** [wenzhixin/bootstrap-table#876]
What am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/12445390/7632251/1b30268a-fa19-11e4-8db7-db5ea4ac57c9.png)

![image](https://cloud.githubusercontent.com/assets/12445390/7632265/3385783e-fa19-11e4-84a4-de1c9bac8828.png)

![image](https://cloud.githubusercontent.com/assets/12445390/7632533/00bf78b6-fa1c-11e4-822e-27be3eccea9f.png)

![image](https://cloud.githubusercontent.com/assets/12445390/7632281/5b2b8216-fa19-11e4-8582-c70d01be8036.png)

![image](https://cloud.githubusercontent.com/assets/12445390/7633987/f3b21bf6-fa25-11e4-92f0-53c536d656d7.png)

**Comment by djhvscf** [comment]
Hmm your code seems to be ok.. Can you share your html table? I mean when it is rendered and also can you debug the code when the bootstrap-table receive by parameter the data??

**Comment by kwingat** [comment]
![image](https://cloud.githubusercontent.com/assets/12445390/7634004/fe3dce4e-fa25-11e4-9d2a-8d0b7a1f05dc.png)

Yes, I can step into the code.

**Comment by AnThO16** [comment]
Hey, I have the same problem,so if you find a solution..

**Comment by kwingat** [comment]
I abandoned my original methods and went with the following but as soon as I set "sidePagination: 'server'", I get no results otherwise I get results.

![image](https://cloud.githubusercontent.com/assets/12445390/7655995/a34b6944-faf5-11e4-84d2-de545e4923d5.png)

![image](https://cloud.githubusercontent.com/assets/12445390/7656002/b0824b5a-faf5-11e4-9e47-3fefd00b27c9.png)

With
![image](https://cloud.githubusercontent.com/assets/12445390/7656029/e7e475b4-faf5-11e4-9cde-1159e43b8808.png)

Without 
![image](https://cloud.githubusercontent.com/assets/12445390/7656012/c479cd90-faf5-11e4-9143-3a5f3c50dadf.png)

What's going on?

**Comment by djhvscf** [comment]
ok.. I need your json response and the table configuration to test what is going on

**Comment by djhvscf** [comment]
Can you paste it?? Here?

**Comment by kwingat** [comment]
![image](https://cloud.githubusercontent.com/assets/12445390/7656332/daadcfa6-faf7-11e4-98a4-06a762225ad7.png)

![image](https://cloud.githubusercontent.com/assets/12445390/7656346/e8e0ea04-faf7-11e4-86f5-f0904fa23edb.png)

**Comment by djhvscf** [comment]
I mean.. paste the code please.. I would like to help you but I don't have enough time

**Comment by kwingat** [comment]
![image](https://cloud.githubusercontent.com/assets/12445390/7656415/5ab6d51c-faf8-11e4-8437-6b8c78c7d7b3.png)

**Comment by kwingat** [comment]
![image](https://cloud.githubusercontent.com/assets/12445390/7656748/94eac48a-fafa-11e4-85ca-940e4acb3e43.png)

**Comment by jtrumbull** [comment]
You JSON response is returning an array of data. To paginate on the server side, you need to tell the client the `total` number of records, and which `rows` to display. The response from the server should look like:

```json
{
     total: 100,
     rows: [
          { CampaignName: "Cigna-HealthSpring 2013" },
          { CampaignName: "Cigna-HealthSpring 2014" },
          ...
     ]
}
```

This is not well documented in the examples, but the format can be found here:
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/json/data2.json

In short, your client is responding with "No matching records found", because it is looking for the `rows` key and not finding it. Hope that gets you unstuck.

**Comment by wenzhixin** [comment]
Just like @jtrumbull said, example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/server-side-pagination.html, and the data: http://issues.wenzhixin.net.cn/examples/bootstrap_table/data?order=asc&limit=10&offset=0

**Comment by kwingat** [comment]
I hope this help someone somewhere.

This isn't the best way but this works.

![image](https://cloud.githubusercontent.com/assets/12445390/7681907/e6c18020-fd41-11e4-81bb-292e55e4ab32.png)

![image](https://cloud.githubusercontent.com/assets/12445390/7681911/f4247a6a-fd41-11e4-93ed-58705ce222ea.png)

**Comment by kwingat** [comment]
Thanks for all of your help.

**Comment by AnThO16** [comment]
can you help me ? , because your solution doesn't work for me..

**Comment by kwingat** [comment]
Sure.

**Comment by AnThO16** [comment]
Thanks so this my table
![data-table](https://cloud.githubusercontent.com/assets/12412756/7707144/c3fc6e84-fe4e-11e4-9c98-2bbe3f0f5cb5.PNG)

and my controller
![controller](https://cloud.githubusercontent.com/assets/12412756/7707176/e8322af0-fe4e-11e4-9023-9be8db318145.PNG)

and my json result seems good 
![jsonresult](https://cloud.githubusercontent.com/assets/12412756/7707185/f4d2ecb8-fe4e-11e4-978b-b9e71cbfa847.PNG)

with Javascript, that work 
![jquery](https://cloud.githubusercontent.com/assets/12412756/7707250/3836aa8a-fe4f-11e4-93f1-59f2ddcd2ec7.PNG)

but with server side pagination how do you sort,filter ?

**Comment by kwingat** [comment]
Total may have to come first. I'm working on filtering now.

**Comment by AnThO16** [comment]
Total comes first if you look the return Json

**Comment by AnThO16** [comment]
and sortable works??

**Comment by kwingat** [comment]
![image](https://cloud.githubusercontent.com/assets/12445390/7707803/acfcc1cc-fe1f-11e4-92ef-420b526cacd9.png)

Notice that the dataQueryParamsType is "Else". Otherwise the default type is limit and a different set of paramerters will be passed to your JsonResult method. Check the developer tools to see just what parameters are being passed back.

Example:
![image](https://cloud.githubusercontent.com/assets/12445390/7707910/5e11b71a-fe20-11e4-9f53-16acc84461ca.png)

**Comment by AnThO16** [comment]
i have this 
![test](https://cloud.githubusercontent.com/assets/12412756/7708111/e9fd0ada-fe53-11e4-82ab-c0d3c286cb59.png)

**Comment by snomula-idc** [comment]
Did any one fixed the server pagination using bootstrap table c#? please post the working solution
Thanks in advance.

**Comment by snomula-idc** [comment]
@kwingat: please post the working code along with controller code.

thanks.

**Comment by kwingat** [comment]
I no longer have access to the working code. Sorry.

**Comment by snomula-idc** [comment]
@AnThO16 : Did you fixed it? please post the working code along with controller code.

thanks.
