### ISSUE TITLE
open the url when click row

### ISSUE THREAD

**Issue by rafaoli** [wenzhixin/bootstrap-table#877]
Hi, i'm try the open the url when click row the 	following:

sp works..
```
tr onclick="location.href='${pageContext.request.contextPath}/poultry/${poultry.token}';"  style="cursor: pointer;"
```

but when use data-table no can do:
```
<table data-toggle="table" data-classes="table table-no-bordered"
					data-flat="true".....
```
js
```
$(function () {

	    $('#datatable').on('all.bs.table', function (e, name, args) {
	        console.log('Event:', name, ', data:', args);
	    })
	    .on('click-row.bs.table', function (e, row, $element) {
	       
               call de URL here...(change the cursor type also..)
	     	/cadastro/grupo/{id}
	    	
	    })
	    
});
```

**Comment by djhvscf** [comment]
ok.. do you use bind them in the page load method?

**Comment by rafaoli** [comment]
Yes, and redirect to url using id value.. (my native language not English)

**Comment by djhvscf** [comment]
Sorry the question is: are you binding them in the page load method?

**Comment by rafaoli** [comment]
Yes, but I would like to know how to write code to open the url.

**Comment by djhvscf** [comment]
provide a jsfiddle please.. it will save our time

**Comment by dabros** [comment]
@rafaoli - the fiddle will help us see where this url is retrieved from, and give you example to pass it in correctly, but the command to open actual url would be:

**window.open**

http://www.w3schools.com/jsref/met_win_open.asp

```javascript
window.open("http://www.w3schools.com");
```

Cursor in this case is just css on table row ("table tbody tr" for example) - http://www.w3schools.com/cssref/pr_class_cursor.asp




**however, why not just format column?**

However, why dont you just use a formatter option on a column if that column contains the link url?

http://bootstrap-table.wenzhixin.net.cn/examples/#format

For example (untested)

```javascript
function my_url_formatter(value, row, index) {
    return "<a href='" + value + "' target='_blank'>" + value + "</a>";
}
```

That way that column contains a hyperlink, which uses normal html markup, and user can still copy paste cells and do whatever else with the table (no need for row.click function)

**Comment by wenzhixin** [comment]
Can the answer help you @rafaoli?

**Comment by rafaoli** [comment]
hello, I'm trying to make as follows (but not works)
this table is the default..
```
<tbody>
	<tr onclick="location.href='${pageContext.request.contextPath}/poultry/${poultry.token}';"
		style="cursor: pointer;">
		<td>${poultry.name}</td>
		<td>${poultry.number}</td>
		<td>${poultry.center.name}</td>										
	</tr>
</tbody>
```
So the full line is formated.
Thank you!

**Comment by wenzhixin** [comment]
You can use formatter option @rafaoli like @dabros said.
