### ISSUE TITLE
Buttons toolbar with Font Awesome

### ISSUE THREAD

**Issue by promogest** [wenzhixin/bootstrap-table#878]
Hi, is there a way to switch from Glyphicons to Awesome in the buttons-toolbar ? 
thanks

**Comment by djhvscf** [comment]
See this http://issues.wenzhixin.net.cn/bootstrap-table/#337.html

**Comment by promogest** [comment]
Sorry for the duplicate issue. i searched a lot but clearly it wasn't enough.

**Comment by promogest** [comment]
It works but not for this button
name="paginationSwitch" 
i tried :
window.icons = {
        paginationSwitch:'fa-collapse-up',
        refresh: 'fa-refresh',
        toggle: 'fa-toggle-on',
        columns: 'fa-th-list'
    };

**Comment by djhvscf** [comment]
Provide a jsfiddle, please

**Comment by promogest** [comment]
http://jsfiddle.net/e3nk137y/1613/

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/e3nk137y/1619/

**Comment by promogest** [comment]
thanks
