### ISSUE TITLE
How to keep CSS-Class when switching to Cardview or assign a new one

### ISSUE THREAD

**Issue by docholiday** [wenzhixin/bootstrap-table#879]
Hi wenzhixin,
I'm using CSS classes to style some columns by inserting additional classes to the th-line:
e.g: `<th class='test test2' data-field='whatever'>`

However, when I switch to Cardview, the classes are lost.
So how can I assign a CSS-class to a column in cardview?

**Comment by djhvscf** [comment]
You can use the row style function or the row attribute function.. See: http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by djhvscf** [comment]
Close this issue, if the answer is not the solution please reopen this issue @docholiday
