### ISSUE TITLE
Using Title Attribute for Table Header

### ISSUE THREAD

**Issue by SarahD** [wenzhixin/bootstrap-table#880]
Hi guys,
I need to use a <th title="Resident">Resident</th> and make it so the title shows up on hover. It seems to be ignoring it. Any suggestions?

Thanks,
Sarah

**Comment by djhvscf** [comment]
Can you provide some code?

**Comment by SarahD** [comment]
gah sorry... it converted it   < table >< th title="Resident"  > Resident <   th  >< /table>

**Comment by djhvscf** [comment]
ok.. but.. what do you want?? Set the title attr in html directly or the plugin sets the title with the column name?

**Comment by wenzhixin** [comment]
I think you can use a child div to do that @SarahD, see this jsFiddle: http://jsfiddle.net/e3nk137y/1635/, close this issue.

**Comment by SarahD** [comment]
Morning guys,
I've come across a more complex situation where I need the tooltip to be a table. I've tried a couple techniques, but am unable to get it to render in the tooltip: http://jsfiddle.net/webdevsarah/9suk3w8b/

I would so appreciate any help with this!

All the best,
Sarah

**Comment by djhvscf** [comment]
I don't understand what you want

**Comment by SarahD** [comment]
This is a screenshot of what I need to build: 
![5-26-2015 10-46-51 am](https://cloud.githubusercontent.com/assets/948608/7815138/98548992-0394-11e5-9dd8-28eb914b5d63.png)

**Comment by wenzhixin** [comment]
Updated: http://jsfiddle.net/9suk3w8b/1/, the problem:
1. There is a conflict when you use a <table> in `th` element.
2. The `class="tooltip"` is defined by bootstrap css.
