### ISSUE TITLE
getSelections() returning empty array after checkBy() is called -isolated to multidimensional data

### ISSUE THREAD

**Issue by jtrumbull** [wenzhixin/bootstrap-table#881]
I found an issue wherein `bootstrapTable('getSelections')` returns an empty array after calling `bootstrapTable('checkBy')`, only when using multidimensional data and the flatJSON extension.

##### Table using standard data
jsFiddle test: https://jsfiddle.net/joeycakes/wkwx917n/1/

The test runs each check methods (`checkAll`, `uncheckAll`, `check`, `uncheck`, `checkBy`, and `uncheckBy`), then outputs in the method name followed by the length of `getSelections()` on a dataset of 5. The results being:

```
checkAll()      @ 5
uncheckAll()    @ 0
check()         @ 1
uncheck()       @ 0
checkBy()       @ 1
uncheckBy()     @ 0
```
The results are as expected.

##### Table using multidimensional data
jsFiddle test: https://jsfiddle.net/joeycakes/p7x0bn2k/1/

Using the same test above, but with multidimensional data, results in:

```
checkAll()      @ 5
uncheckAll()    @ 0
check()         @ 1
uncheck()       @ 0
checkBy()       @ 0
uncheckBy()     @ 0
```
The result of `checkBy()` should be `1`. The above example passes the `$.inArray` test @ [Line 2018](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L2018), and even renders the checkbox. I cannot easily find a reason as to why this would work on standard data and not multidimensional data, however I believe the problem to be the positioning of `updateSelected()` @ [Line 2024](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L2024) (see my solution in comment below).
<br />
\* I reformatted this issue for coherency.

**Comment by jtrumbull** [comment]
I've corrected the issue on my side by calling the `check_()` method within the iteration @ [Line 2014](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L2014). This assures that the `updateSelected()` is being called immediately also before the `check.bs.table` or `uncheck.bs.table` events are triggered -however losing the efficiency of calling `updateSelected()` once.

```javascript
BootstrapTable.prototype.checkBy_ = function (checked, obj) {
    if (!obj.hasOwnProperty('field') || !obj.hasOwnProperty('values')) {
		return;
    }

    var that = this;
    $.each(this.options.data, function (index, row) {
		if (!row.hasOwnProperty(obj.field)) {
			return false;
        }
        if ($.inArray(row[obj.field], obj.values) !== -1) {
			// that.$selectItem.filter(sprintf('[data-index="%s"]', index)).prop('checked', checked);
            // row[that.header.stateField] = checked;
            // that.trigger(checked ? 'check' : 'uncheck', row);
            that.check_(checked, index);
        }
    });
    //this.updateSelected();
};
```
Using the same test as above, with multidimensional data, the results are as expected:
```
checkAll()      @ 5
uncheckAll()    @ 0
check()         @ 1
uncheck()       @ 0
checkBy()       @ 1
uncheckBy()     @ 0
```

Working jsFiddle: https://jsfiddle.net/joeycakes/q9hze20L/2/

Would you guys consider supporting this change in future versions?

**Comment by djhvscf** [comment]
sure.. I already tested and you're right.. This is a issue that we have to fix.. Thanks a lot @jtrumbull

**Comment by jtrumbull** [comment]
Thank you @djhvscf

**Comment by jtrumbull** [comment]
@djhvscf: Should I create a PR for this, or is this something your sorting out on flatJSON? Wanted to check first to make sure there wasn't any duplication of effort.

**Comment by djhvscf** [comment]
Ok I think we have to review the flat-json extensión.. Can you review it?? I think it is an issue in flatjson

**Comment by jtrumbull** [comment]
@djhvscf: Gladly. I've forked and am playing around in there now. I'm mapping out what gets called where in the extension and `BootstrapTable`, to identify where the root of the trouble is -proving to be difficult, but I have faith.

**Comment by jtrumbull** [comment]
@djhvscf: I moved this to [Issue #8](https://github.com/djhvscf/bootstrap-table-flatJSON/issues/8) in the flatJSON repository.

**Comment by djhvscf** [comment]
Ok, thank you! @jtrumbull great job!!!
