### ISSUE TITLE
how can i frozen my first column

### ISSUE THREAD

**Issue by toadprince** [wenzhixin/bootstrap-table#884]
怎样冻结第一列或前几列呢？有没有相关扩展

**Comment by toadprince** [comment]
how can i frozen my first column

**Comment by djhvscf** [comment]
We are working on it right now

**Comment by djhvscf** [comment]
Same of https://github.com/wenzhixin/bootstrap-table/issues/265 close this issue

**Comment by toadprince** [comment]
can i know the progress of the work

**Comment by djhvscf** [comment]
Well I'm testing.. It is difficult because I don't want to modify the core js and css

**Comment by toadprince** [comment]
22 day later:  and now?
or , can i get the beta version now?

**Comment by ediri** [comment]
@djhvscf is there some branch were i can test your improvements too?

**Comment by wenzhixin** [comment]
ref #265
