### ISSUE TITLE
In the case of all selected table row to get a single row of ID

### ISSUE THREAD

**Issue by xujianghao** [wenzhixin/bootstrap-table#887]
当选中多行数据后，点击某一行的编辑按钮后，怎么获得改行的ID？
ids = $.map($('#table').bootstrapTable('getSelections'), function (row) {
            return row.id
        });这种写法会造成点击任意一个编辑按钮，获得所有选中行的ID的情况！

**Comment by PlippiePlop** [comment]
I do not exactly know what you want, do you want the row ID if you click the row or do you want the id of every row in the table if you click a row?

**Comment by xujianghao** [comment]
when i select all rows,than i click the edit button,i want get the row ID

**Comment by PlippiePlop** [comment]
Check this:
http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#table-events

**Comment by xujianghao** [comment]
thanks for you
