### ISSUE TITLE
extensions名称规则问题

### ISSUE THREAD

**Issue by tangjn** [wenzhixin/bootstrap-table#890]
I suggest component at extensions have the same name rule.
after the https://github.com/wenzhixin/bootstrap-table/commit/0a534fd22a63e4b810d7bbbe1419a5a9a26108d0  commit, I found same compont name is not match with others. 
eg:
├── cookie
│   ├── bootstrap-table-cookie.js
│   └── README.md
if I include cookie component, the path could auto general like: '%s/bootstrap-table-%s.js'%('cookie')

but the component beloow cannot general by my script:  '%s/bootstrap-table-%s.js'%('reordercolumns')

suggest two ways:
1. components  "reordercolumns", "reorderrows" change to "reorder-columns", "reorder-rows"
2. change the   bootstrap-table-reorder-columns.js  to bootstrap-table-reordercolumns.js 
    change the   bootstrap-table-reorder-rows.js  to bootstrap-table-reorderrows.js
    change the   bootstrap-table-reorder-rows.css  to bootstrap-table-reorderrows.css
├── reordercolumns
│   ├── bootstrap-table-reorder-columns.js
│   └── README.md
├── reorderrows
│   ├── bootstrap-table-reorder-rows.css
│   ├── bootstrap-table-reorder-rows.js
│   └── README.md

**Comment by djhvscf** [comment]
Can you translate it to english, please?

**Comment by djhvscf** [comment]
Remember any pull request is welcome

**Comment by wenzhixin** [comment]
Updated:
```
├── cookie
│   ├── bootstrap-table-cookie.js
│   └── README.md
├── editable
│   ├── bootstrap-table-editable.js
│   └── README.md
├── export
│   ├── bootstrap-table-export.js
│   └── README.md
├── filter
│   ├── bootstrap-table-filter.js
│   └── README.md
├── filter-control
│   ├── bootstrap-table-filter-control.js
│   └── README.md
├── flat-json
│   ├── bootstrap-table-flat-json.js
│   └── README.md
├── key-events
│   ├── bootstrap-table-key-events.js
│   └── README.md
├── mobile
│   ├── bootstrap-table-mobile.js
│   └── README.md
├── natural-sorting
│   ├── bootstrap-table-natural-sorting.js
│   └── README.md
├── reorder-columns
│   ├── bootstrap-table-reorder-columns.js
│   └── README.md
├── reorder-rows
│   ├── bootstrap-table-reorder-rows.css
│   ├── bootstrap-table-reorder-rows.js
│   └── README.md
├── resizable
│   ├── bootstrap-table-resizable.js
│   └── README.md
└── toolbar
    ├── bootstrap-table-toolbar.js
    └── README.md
```
