### ISSUE TITLE
能否用 Nice-JQuery-Table-Filter 替换 filtercontrol 

### ISSUE THREAD

**Issue by neozhu** [wenzhixin/bootstrap-table#891]
![](http://www.htmldrive.net/media/2010/12/2/1291273362.jpg)

[![Nice-JQuery-Table-Filter.html]](http://www.htmldrive.net/items/show/770/Nice-JQuery-Table-Filter.html)

感觉这样的显示比较和谐,通用性更强
不知道能否实现
当然必须整合boostrap-table 的search方法 和 Server端分页的功能

如果集成这样的功能那么就更佳完美了

**Comment by djhvscf** [comment]
We already have something similar
