### ISSUE TITLE
Detail-View

### ISSUE THREAD

**Issue by mmoossen** [wenzhixin/bootstrap-table#892]
Hi there,

great piece of software, but is there any way to implement a row master-detail view? 
like here:
http://www.codeproject.com/KB/aspnet/Expandabe-DataTable-MVC/expandableDataTables-table.png
(not necessarily a child table, but that should not constrained).

I have been playing with the show/hideRow methods, but it is not really the way, since the hidden rows are still considered as table data.

Many thanks,
Michael

**Comment by wenzhixin** [comment]
Added this feature, use `detailView` option, [docs](http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options), [example 1](http://issues.wenzhixin.net.cn/bootstrap-table/), [example 2](http://issues.wenzhixin.net.cn/bootstrap-table/#options/detail-view.html), [example 3](http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html).

**Comment by wenzhixin** [comment]
#499

**Comment by mmoossen** [comment]
wow. great. thank you so much for your effort!

**Comment by brauliobo** [comment]
beautiful, perfect, thanks!

**Comment by brauliobo** [comment]
hello @wenzhixin. I've added `tr class="detail-view` with some custom html and it seems not to work. Can detail-view work with custom HTML and just a formatter?
