### ISSUE TITLE
Sortable wont work when using Formatter

### ISSUE THREAD

**Issue by zpf364** [wenzhixin/bootstrap-table#893]
https://jsfiddle.net/yx275pyd/8/

Click index  ,it's doesn't work.

**Comment by jtrumbull** [comment]
@zpf364 and @djhvscf: The above jsFiddle example _shouldn't_ work. The function `runningFormatter()` is simply returning the insertion order of the `<tr>` into the html, and will always produce `1,2,3...` as it should. Also, `Index` is not a field in the data, so there is nothing to sort.

Here is an example of `sortable` with `formatter` working properly: https://jsfiddle.net/joeycakes/yx275pyd/9/

@zpf364: If you want to sort by the insertion index of your data, you would need to add an `index` field to your rows.
https://jsfiddle.net/joeycakes/nag5d579/1/

**Comment by wenzhixin** [comment]
Thanks for the answer of @jtrumbull
