### ISSUE TITLE
click event on a cell and not entire row

### ISSUE THREAD

**Issue by flook** [wenzhixin/bootstrap-table#894]
The below code triggers a click event for the entire row.

     $('#myTable').bootstrapTable().on('click-row.bs.table', function (e, row, $element) 

How do we do it for a single cell and not for the entire row?. Remember, would want to use the `row and $element` arguments.

**Comment by djhvscf** [comment]
Single cell for what?

**Comment by jtrumbull** [comment]
Here is a working example: http://jsfiddle.net/joeycakes/a0udds4u/5/
```javascript
$('#myTable').on('click', 'tbody > tr > td', function (e){
    var table = $table.data('bootstrap.table'),
        $element = $(this),
        $tr = $element.parent(),
        row = table.data[$tr.data('index')],
        cellIndex = $element[0].cellIndex,
        $headerCell = table.$header.find('th:eq(' + cellIndex + ')'),
        field = $headerCell.data('field'),
        value = row[field];
    
    table.$el.trigger($.Event('click-cell.bs.table'), [value, row, $element]);
});
```

Then simply call:
```javascript
$('#myTable').on('click-cell.bs.table', function(e, value, row, $element){
    // code...
});
```

**Comment by wenzhixin** [comment]
We can consider add this event, any pull request is welcome! @jtrumbull

**Comment by jtrumbull** [comment]
@flook: The `click-cell.bs.table` and `dbl-click-cell.bs.table` events are now supported in version 1.8.0, the documentation can be found [here](http://bootstrap-table.wenzhixin.net.cn/documentation/#events).
