### ISSUE TITLE
Records pr. page

### ISSUE THREAD

**Issue by larsbrandi** [wenzhixin/bootstrap-table#895]
Hi

I am having a minor issue here. Everything works except from selecting records pr page when pagination is set. Any experiencing the same behaviour ?

**Comment by djhvscf** [comment]
Can you provide a fiddle, please?

**Comment by larsbrandi** [comment]
I have it here on my test site : http://www.sunentry.com/amarc/

**Comment by larsbrandi** [comment]
Oh dear. Palm to forehead slab x 10.  Forgot  <script src="/bootstrap/js/bootstrap.min.js"></script>. Everything is okay now.

**Comment by djhvscf** [comment]
Ok, sounds great
