### ISSUE TITLE
header appears twice in bootstrap modal since version 1.7.0 (1.6.0 is ok)

### ISSUE THREAD

**Issue by ulluoink** [wenzhixin/bootstrap-table#896]
the table Header appears twice when using Version 1.7.0. in Version 1.6.0 it was ok.

the table is in a bootstrap modal

**Comment by djhvscf** [comment]
Can you provide a fiddle?

**Comment by RataDP** [comment]
I don't know how to create a fiddle, but i uploaded the result of execution on my website. The image is the following:
![1](https://cloud.githubusercontent.com/assets/3502137/7761338/ec61b1e0-0024-11e5-8396-d0435336f728.png)
And this is the html:
```html
<table id="instructorsTable"  
	  data-toggle="table" 
      	  data-classes="table table-no-bordered"
         data-query-params="queryParams"
         data-pagination="true">
		<thead>
	        <tr>
	            <th data-field="name" data-sortable="true">Name</th>
	            <th data-field="lname" data-sortable="true">Last name</th>
	            <th data-field="ssn" data-sortable="true">ssNumber</th>
	            <th data-field="idn" data-sortable="true">idNumber</th>
	            <th data-field="email" data-sortable="true">Email</th>
	            <th data-field="tlf" data-sortable="true">Telephone</th>
	            <th data-field="expire" data-sortable="true">Expire date</th>
	            <th data-field="active" data-sortable="true">is Active?</th>
	            <th></th>
	            <th></th>
	        </tr>
        </thead>
        <tbody>
```

**Comment by wenzhixin** [comment]
OK, we will check it.

**Comment by yangxueping** [comment]
what it is? who are you? I don't know you.
 
------------------ Original ------------------

**Comment by wenzhixin** [comment]
Added example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/modal-table.html

**Comment by evanrich** [comment]
What was the fix for this?  I have the same problem with 1.8.0.    
![image](https://cloud.githubusercontent.com/assets/518320/7870280/17222cc6-053d-11e5-9951-b2fb564ba6f8.png)

using data-show-header="false" hides both the header and the empty row...re-enabling the header shows both header and empty row

**Comment by djhvscf** [comment]
In meantime, you have to use the src code because the v1.8.0 has that issue, sorry
