### ISSUE TITLE
Header sorting not functioning correctly

### ISSUE THREAD

**Issue by xvisor16** [wenzhixin/bootstrap-table#897]
Hi there,

I'd like to use the bootstrap-table extension in our projects. I use it with Bootstrap 3.2.2-3.2.4 and jquery 2.1.4 or 1.11.2. Now when i'm trying to sort by pressing a column header the sort works fine for numbers but not for any other information like text, names, currency, etc. While having tried many things i tried the sample on http://issues.wenzhixin.net.cn/bootstrap-table/#options/basic-sort.html and came to the conclusion that the problem also exist in all of the samples. You can sort numbers and all but not the names, it continuesly changes the sort but never in the same way. Is this a bug or is this on purpose?

Cheers,
Peter Gerritsen

**Comment by wenzhixin** [comment]
Sorry, can you provide some screenshot to explain your problem?

**Comment by xvisor16** [comment]
Offcourse: I pressed on the right most column.

![image](https://cloud.githubusercontent.com/assets/12544669/7749000/196abebc-ffca-11e4-9112-b7abb7d52533.png)

**Comment by xvisor16** [comment]
Aah I found a solution, i'm now using master and added the naturalsorting extension. This works better :+1: )
