### ISSUE TITLE
How can you search on combined fields i.e. name + " " + surname

### ISSUE THREAD

**Issue by JayAtCornwallCollege** [wenzhixin/bootstrap-table#898]

**Comment by djhvscf** [comment]
You can use the toolbar extension: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/toolbar

**Comment by JayAtCornwallCollege** [comment]
Solved with class="hidden" headings

**Comment by JayAtCornwallCollege** [comment]
Now needing to combine search splitting search up by spaces and where any combination of words exist

**Comment by blomdahldaniel** [comment]
@djhvscf Hm... i imported your [extension](https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/toolbar) but i cant understand how to use the advanced search?

As of now i import the bootstrap-table from cdn and yout script localy (and correct).
I have tried to add `data-advancedSearch="true"` but i dont get it to work?

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/toolbar.html
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/toolbar.html
use `data-advanced-search="true"` @blomdahldaniel
