### ISSUE TITLE
Wrapping long table headers

### ISSUE THREAD

**Issue by kofm** [wenzhixin/bootstrap-table#899]
Hi.

I'm reposting this since i wrote in a closed issue.
I have very large column headings in my table and a table with 40 columns.
I'm able to set horizontal scrolling for table and setting a custom max-width for columns. Setting text-overflow truncate text at desidered width.

Is it possible to NOT truncate text and instead wrapping it maintaining my fixed width?

Thanks for your awesome work.

**Comment by kofm** [comment]
An update:

setting a custom class and specifying `max-width` will result like this:
![screen1](https://cloud.githubusercontent.com/assets/12545394/7766401/339cb3a4-0069-11e5-84d0-0dc93beeeee1.png)

Removing `<thead>` tags will do the trick but other functions, like pagination, will not work anymore.
This is the result i want to achieve:
![screen2](https://cloud.githubusercontent.com/assets/12545394/7766411/4eb051be-0069-11e5-9a82-fa4fd22fca57.png)

Is it possible to do this without removing `<thead>`?

Thanks.

**Comment by dabros** [comment]
NOTE: related to #848, though not answered by it (or at least yet)

**Comment by dabros** [comment]
@kofm - can you please provide a fiddle so we can play with this?

Of top of my head, i would try looking at the "white-space" and "word-wrap" css properties, though if truncating then it would likely be js side, in which case can we pass in custom html to thead contents, or even run a formatter on th?

**Comment by kofm** [comment]
Here it is
https://jsfiddle.net/pj3g56qo/

I managed to obtain the wanted result removing the property `height` (commented as "cellHeight") of `.fixed-table-header` in `bootstrap-table.css
Is there another way without touching the original .css file?

Thank you **very much** for your help.

**Comment by wenzhixin** [comment]
@kofm , you can reset the `white-space` property of `.th-inner` class, for example: https://jsfiddle.net/pj3g56qo/2/.
But I think this apply only to the not fixed header. If you want to use fixed header feature, because of the reason of implementation, it is more complex.

**Comment by kofm** [comment]
Thanks, this is what i need but i also need to use fixed header feature.
My method (removing `height` property from `fixed-table-header`) gives the same problem: when it renders the table header cells not aligned with body cells. `resetView` does the trick but only after the page is loaded, so the first view at the page looks like this:

![image](https://cloud.githubusercontent.com/assets/12545394/7836528/19d0a1bc-0481-11e5-810d-4ad1a27a90fb.png)

Where i can start to figure out how to fix this?

**Comment by wenzhixin** [comment]
Supported this feature now: https://jsfiddle.net/wenyi/pj3g56qo/6/

**Comment by wizeird** [comment]
Thank you! I was just grappling with this issue today, what a coincedence.

Great plugin.

**Comment by kofm** [comment]
Thank you again for your awesome work!

**Comment by hepcat72** [comment]
I don't understand why this doesn't work for me *unless* I manually put `<br>` in the `th` inner HTML...

**Comment by JonasR** [comment]
I also cannot get this to work without hardcoded `<br>` elements. The jsfiddle above seems to no longer work with current versions of Bootstrap and bootstrapt-table
