### ISSUE TITLE
Selected row without checkbox or radiobox columns

### ISSUE THREAD

**Issue by mojtabakaviani** [wenzhixin/bootstrap-table#9]
selected row with checkbox or radiobox very good but add other option to selected row with click and highlight current row.finaly get selected row with getSelections function

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#563.html

**Comment by sivagurupr** [comment]
Hai dudes,
                I designed four columns and three rows table.The fourth column is drop down(value is yes/no),if the value is no means we need add all the third columns values(numeric),anybody done it..using bootstrap table

**Comment by wenzhixin** [comment]
Sorry @sivagurupr , do not understand what you want, maybe you can provide a jsFiddle.

**Comment by sivagurupr** [comment]
I click a edit   control then dialog open and edit  some values,after that i click a add  control edit values replace in add dialog.How to solve this problem

**Comment by sivagurupr** [comment]
How to refresh dialog in bootstrap ?

**Comment by wenzhixin** [comment]
Refresh dialog? @sivagurupr

**Comment by KulanthaivelChinnadurai** [comment]
Hi im very new to bootstrap . 
![untitled](https://cloud.githubusercontent.com/assets/12044331/7272798/4ff03e1a-e90b-11e4-9dd7-d1cf4caebd97.png)

My table is something like this. Now im trying to select the rows . But i couldnt.t anyone please help me to get resolve this.
what property I need to add in html.. what should I do in js. Please help me in this. 
Thanks.
Im using JSON objects. 

My js is something like this. 
     var offset=0;
	var jobcount=10;
	var JobEnd=false;	 
	$.ajax({
	 	//contentType: "application/json; charset=utf-8",
		dataType: "json",
		url: "/DDServer/rest/jobs?action=Retrievejobs&offset="+offset+"&jobcount="+jobcount,
    }).then(function(data) {    	
    	$('#table').bootstrapTable('load', data.results);
    	//alert(jtmeta.JT_Name);
	});
     
    function loadMore(data)
    {       	
    	$('#table').bootstrapTable('append', data.results);    	
    	$('#bootdiv').bind('scroll',bindScroll);
    }    
    $('#bootdiv').scroll(bindScroll);
    function bindScroll(){ 	
        if(($(this).scrollTop() + $(this).innerHeight() >= this.scrollHeight)&& JobEnd==false) {
        	offset=offset+jobcount;
      	  $.ajax({
    		 	//contentType: "application/json; charset=utf-8",
    			dataType: "json",
    			url: "/DDServer/rest/jobs?action=Retrievejobs&offset="+offset+"&jobcount="+jobcount,
    	    }).then(function(data) {     	    	
    	    	if(data.results !=undefined){    	    	
    	    	$('#bootdiv').unbind('scroll');
    	        loadMore(data);	
    	    	//$('#table').bootstrapTable('append', data.results);  	    	
    	    	}
    	    	else{
    	    		JobEnd=true;
    	    	}
    		});     	
          
        }
    }  
});
