### ISSUE TITLE
reorderrows example

### ISSUE THREAD

**Issue by xclntdesign** [wenzhixin/bootstrap-table#902]
Whenever possible, can a demo of the reorderrows extension be added to the documentation?  I've been fooling around with it, but I am missing something because I can't get it to work.

Thanks!

**Comment by djhvscf** [comment]
Sure.. I'm working on it

**Comment by wenzhixin** [comment]
@djhvscf Is it http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/reorder-rows.html?

**Comment by djhvscf** [comment]
Yes, it is but we need to update the issues site because right now the example is not working

**Comment by wenzhixin** [comment]
Updated.
