### ISSUE TITLE
filtercontrol dropdown not loading full set

### ISSUE THREAD

**Issue by bobobuny** [wenzhixin/bootstrap-table#904]
The filter dropdown on the filtercontrol does not load the full list. I have a table with 10,000 rows and the dropdown options only contains a few of the unique values.

**Comment by djhvscf** [comment]
Can you provide some fiddle?? or screenshot??

**Comment by djhvscf** [comment]
Any update here??

**Comment by raku** [comment]
I think this can be done with my patch. He need to fill the select filter with data from a server not from table column

**Comment by djhvscf** [comment]
I think you are right @raku .

**Comment by trainspotting** [comment]
I'm trying to achieve this too... have the filter include all possible values from the whole data-set.... @raku you mention a 'patch'... is this available for me to try anywhere? Thanks!

**Comment by raku** [comment]
the patch is included in current version of bootstrap-table

**Comment by trainspotting** [comment]
@raku Thanks... I'm using 1.8.1. Is in in there and do I need to do anything special to make it work? I have the filter in use on a paginated client-side table and it only shows the options available from the current page view...
