### ISSUE TITLE
A table with a fixed header clears the filtercontrol fields after filter runs

### ISSUE THREAD

**Issue by bobobuny** [wenzhixin/bootstrap-table#905]
A table with a fixed header clears the fields after filtercontrol runs.  So, if a user enters a value into the filter the filter works correctly,  However, after the filter completes the filter fields clear out

**Comment by djhvscf** [comment]
Yes. this is a bug

**Comment by bobobuny** [comment]
I've created a fix although I have not done a full regression test.  Inside the fitHeader method before clearing the fields store the input/select values.  Then, after clearing and reseting the input.select fields restore the values.

**Comment by bobobuny** [comment]
copy values:
var vals = [];
        this.$tableHeader.find('table select, table input').each(function () {
        	vals.push($(this).val());
        });

reset fields:
this.$tableHeader.css({
            'margin-right': scrollWidth
        }).find('table').css('width', this.$el.css('width'))
            .html('').attr('class', this.$el.attr('class'))
            .append(this.$header_);

restore values:
 this.$tableHeader.find('table select, table input').each(function (index, ele) {
        	$(this).val(vals[index]);
        });

**Comment by djhvscf** [comment]
Good idea.. can you do a pull request??

**Comment by albertoronu** [comment]
I'm experiencing the same issue, when the header is fixed, the fields are cleared after filters applied. Is this going to be fixed anytime soon?

Thanks!

**Comment by djhvscf** [comment]
yes, I'm applying the solution above and testing now.. I think perhaps today night or tomorrow I will commit the changes
