### ISSUE TITLE
初始化表单关于search默认值的问题

### ISSUE THREAD

**Issue by jackie1982** [wenzhixin/bootstrap-table#906]
URL：   http://xxxxxxx.com/
表单内容：   ajax取数据没问题，此时不加任何search内容。

我希望输入URL      http://xxxxxxx.com/?search=abc
表单search框内容为abc，查询内容取  search=abc的数据

我目前的配置：

queryParams: function (p) {
            alert(p.search);
            return {
                page_size: p.limit,
                page: p.offset/p.limit+1,
                search: p.search
            };
        },
        pagination: true,
        pageSize: 50,
        pageList: [10,20,100],
        sidePagination: 'server',
        showRefresh: true,
        search: true,
        searchText: '{{s}}'
        showColumns: true,
        toolbar: "#toolbar",
        cache: false

{{s}}的内容为我从URL的  &search=abc  获取到的值。

但是表单没有效果，还是查询所有内容，并且search框的内容为空。

试了好多次，都不行，可能是个低级错误，但目前还未查出来，求助。。。。

**Comment by wenzhixin** [comment]
能够将代码转换为 jsFiddle？ https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wenzhixin** [comment]
见：http://jsfiddle.net/e3nk137y/1821/
