### ISSUE TITLE
editable save-event doesn't fire in card view

### ISSUE THREAD

**Issue by docholiday** [wenzhixin/bootstrap-table#907]
Hi there,

I save changes done with the editable extension by calling a function whenever 'editable-save.bs.table' is fired. This works great in regular view. In card view however the event is never fired. As I use the same code for both views, I can only assume that this is a bug.

**Comment by djhvscf** [comment]
Provide a fiddle, please

**Comment by docholiday** [comment]
I tried to create one, but card view doesn't seem to work in jsfiddle:
http://jsfiddle.net/xtjnasua/8/

You can see my function "watchEdits" working in table view.
Add the data-card-view="true" option and you get an error in the console.

I added a toggleView-Button, but by using this, the editable-option doesn't work at all -> fields are not editable anymore in card view (bug?).

But at least you get an idea of my setup. To clarify:
Other than in this fiddle, on my website card-view works as expected and the fields are editable.

The only problem I have, is that the event 'editable-save.bs.table' doesn't fire in card view.

**Comment by jtrumbull** [comment]
Any errors being thrown at the console?

**Comment by docholiday** [comment]
Nope, no errors - therefore no idea how to fix it.

**Comment by wenzhixin** [comment]
It's a bug in card view and fixed now, please use the src source: http://jsfiddle.net/xtjnasua/10/

**Comment by docholiday** [comment]
Thx, now it works as expected :-)
