### ISSUE TITLE
filter-control incorrect value comparison

### ISSUE THREAD

**Issue by vicentor** [wenzhixin/bootstrap-table#909]
Here is an animated gif that shows the behaviour I am talking about. It's using its native feature.
Latest version.

Is this a normal thing? Or a bug?
![possible-bug](https://cloud.githubusercontent.com/assets/2099885/7777848/48b6699e-0094-11e5-9c97-173b7e7d85d1.gif)

**Comment by vicentor** [comment]
Additional info: The Division column behaves perfectly, only the Classe column doesn't seem to compare values properly.

Lemme know if I'm not using it properly!

**Comment by djhvscf** [comment]
Hi! I think maybe it could be a bug but we need some fiddle to test the extension.. provide one, please

**Comment by vicentor** [comment]
I'm a total JS Fiddle beginner, here's what I tried: https://jsfiddle.net/e3nk137y/1434/

The URL should return values normally (39), it reaches the page and I have logs of the results being returned but nothing is shown in the table.

Is there a list of hosted libraries I can use for Bootstrap-table? Any JS Fiddle tips?

**Comment by djhvscf** [comment]
See this http://jsfiddle.net/e3nk137y/1764/

**Comment by vicentor** [comment]
Ohh! Using local values would of been simpler. I see you reproduced the same behaviour as a matter of fact. Thank you!

**Comment by djhvscf** [comment]
Lets modify the data object with your data structure and then share us the fiddle to see if there is a bug or there is not

**Comment by vicentor** [comment]
Using your JS Fiddle and setting 01 as the filter-control value returns two values. One being 01a which seems to not be an expected value. Isn't that by itself a bug?

Otherwise, I'm very new to JS Fiddle and terms, gimme more details about what you'd like me to do and I'll provide what I can.

**Comment by djhvscf** [comment]
Ok, the filter-control extension use the search method of Boostrap-table to search into the data object. I think there is not issue here.. The extension works as expected!
