### ISSUE TITLE
Bug when switching to card view

### ISSUE THREAD

**Issue by jtrumbull** [wenzhixin/bootstrap-table#912]
BootstrapTable throwing `Uncaught ReferenceError: $tableContainer is not defined` when switch to card view. [Line 1805](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1805) is missing `this.` before `$tableContainer`.

**Comment by djhvscf** [comment]
Yes.. ok let me modify that!

**Comment by wenzhixin** [comment]
Fixed this: https://github.com/wenzhixin/bootstrap-table/commit/467336d437f2fecbb659a2e190d0059c8c228b6f!
