### ISSUE TITLE
table default search box

### ISSUE THREAD

**Issue by pipiscrew** [wenzhixin/bootstrap-table#916]
hi, currently I reference to search box with 

$("input.form-control").val(); 

which is not the best method...  is any alternative?

also when I write 'good' (or whatever) then press space goes back (like I press backspace the space)

tested&using ***bootstrap-table - v1.3.0 - 2014-10-16***

**Comment by djhvscf** [comment]
Use trimOnSearch='false' to avoid that.. And you can access the search button: $('.search input')

**Comment by pipiscrew** [comment]
thanks for quick reply 

$('.search input') tested&working

data-trim-on-search="false" tested&no working 

on this http://jsfiddle.net/e3nk137y/1784/ - is working
