### ISSUE TITLE
howto change "method: 'GET'" to method: 'POST',

### ISSUE THREAD

**Issue by abanger** [wenzhixin/bootstrap-table#918]
howto change "method: 'GET'" to method: 'POST',

**Comment by wenzhixin** [comment]
Set `method` option: 
```html
data-method="POST"
```
or
```js
$table.bootstrapTable({
    method: 'POST'
});
```

**Comment by abanger** [comment]
thx @wenzhixin 
but server  can not post $_POST["order"] value

**Comment by wenzhixin** [comment]
You can try to set `contentType`.

**Comment by abanger** [comment]
add data-content-type="application/x-www-form-urlencoded"
is ok

**Comment by wenzhixin** [comment]
Good :+1:
