### ISSUE TITLE
sortable columns - arrows are shown more than once

### ISSUE THREAD

**Issue by locito54** [wenzhixin/bootstrap-table#923]
after switching from 1.6 to 1.8 the arrows in sortable columns are shown more than once. What I am doing wrong?

![bildschirmfoto 2015-05-26 um 13 07 09](https://cloud.githubusercontent.com/assets/876995/7811155/5d0533e6-03a8-11e5-8eec-d74ed3a31a0f.png)

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle?

**Comment by djhvscf** [comment]
You have to use the bootstrap-table.css v1.8.0

**Comment by locito54** [comment]
thx, changed the css, but It was linked to the old one at a different location :)
