### ISSUE TITLE
how to change editable icons?

### ISSUE THREAD

**Issue by kaenry** [wenzhixin/bootstrap-table#924]
change 'glyphicon' to 'fa-check' ..

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/337.html

**Comment by kaenry** [comment]
I tried. but I want to change the icons in the editable extensions alert box

**Comment by wenzhixin** [comment]
Hi @kaenry , that problem is belong to the extensions plugin dependence repo: https://github.com/vitalets/x-editable   ([using-the-issue-tracker](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker)).
