### ISSUE TITLE
Card view mode problem

### ISSUE THREAD

**Issue by fbinfopro** [wenzhixin/bootstrap-table#930]
When i switch in cardview mode and i change the record per page, the loading please wait .. loop in infinite. 
No problem with the list mode, my server side code in php work correctly.
bootstrap-table v1.8.0
windows 7
Firefox v 33.1
Thanks

**Comment by djhvscf** [comment]
Provide a fiddle please

**Comment by burnspirit** [comment]
line 1803: `$tableContainer.css('padding-bottom', '0');`

**Comment by fbinfopro** [comment]
I have tested this fix and it works fine. Thank you for your help.
