### ISSUE TITLE
"filterBy" method doesn't works and breaks column ordering

### ISSUE THREAD

**Issue by gmcinalli** [wenzhixin/bootstrap-table#932]
Hi, seems that there is a problem with the `*-all.js` scripts added in this new release (**1.8.0**), the filterBy the method does not work with this kind of files, but with the standard `.js` version is ok. I've tried to download from the releases page and also to recompile with grunt from master branch.

PS: I've noticed that also the call of `filterBy` breaks the ordering of the single columns, before the call everything is ok, after, nothing.

**UPDATE**
A demonstration on JSFiddle:
> **bootstrap-table-all.js** - https://jsfiddle.net/e3nk137y/1875/
> **bootstrap-table.js** - https://jsfiddle.net/e3nk137y/1876/

**Comment by djhvscf** [comment]
Ok, this is an issue because our ...-all.js file does not the same of our src .js file.. So @wenzhixin we have to review that because the -all.js has some issues

**Comment by djhvscf** [comment]
@gmcinalli please use the src files not the -all.js

**Comment by gmcinalli** [comment]
Thanks, for that and for this **great** project. I'll wait the fix.

**Comment by djhvscf** [comment]
@wenzhixin the new version (1.8.1) is not fixing this issue.. can you check please?

**Comment by wenzhixin** [comment]
OK, I will check, @gmcinalli any pull request is welcome.

**Comment by tannermccoleman** [comment]
Any update on this?

**Comment by wenzhixin** [comment]
Next release will fix this, you can use src file until next version release, or `grunt` dist by yourself.

**Comment by gmcinalli** [comment]
I've grunt dist but it seems that the issue is not yet solved. If I use `bootstrap-table-all.js` filterBy method doesn't work.
* **bootstrap-table-all.js**: https://jsfiddle.net/e3nk137y/2560/
* **bootstrap-table.js**: https://jsfiddle.net/zswL2654/

> NOTE: I've created gists of both compiled .js to show you the issue into jsfiddle.

**Comment by wenzhixin** [comment]
OK, remember any pull request is welcome!

**Comment by gmcinalli** [comment]
I'd love to help, but unfortunately I'm not an experienced programmer. But I will do my best to find the bug. :thumbsup:

**Comment by gmcinalli** [comment]
Sorry, reopen.

**Comment by wenzhixin** [comment]
Removed all.js after 1.9.0, close this issue.
