### ISSUE TITLE
Sort carets shouldn't be inline-styled by JS

### ISSUE THREAD

**Issue by tannermccoleman** [wenzhixin/bootstrap-table#936]
The carets in the sortable table headers look awful with the new version and require overuse of !important in styles to make them palatable. Why are they being done as backgrounds, why are they set inline and why are they hardcoded into the plugin? Can these things be changed, or is there some functionality that requires this?

**Comment by djhvscf** [comment]
What is your solution for this?? Provide a fiddle please

**Comment by tannermccoleman** [comment]
Thanks for the fix!

**Comment by jtrumbull** [comment]
Also, this jsFiddle is an example of reverting to the old caret styling, using the triangle trick.
http://jsfiddle.net/joeycakes/e3nk137y/1905/
(javascript will be unnecessary after pull request)

**Comment by wenzhixin** [comment]
Merged.
