### ISSUE TITLE
The identify arrow for multiple sort will change to no sortable with some action.

### ISSUE THREAD

**Issue by QuYunpeng** [wenzhixin/bootstrap-table#938]
The resetview , hide/Show Column will make the sorted arrow change to grey color for multiple sort.

But this will not happening to single sort.

**Comment by djhvscf** [comment]
Provide a fiddle, please

**Comment by QuYunpeng** [comment]
https://jsfiddle.net/cma66gng/1/

If you click the resetView or change the shown columns, the sort identify will change to no sort.

**Comment by djhvscf** [comment]
Ok, this is an issue.. Can you review it, @dimbslmh ?

**Comment by djhvscf** [comment]
Thanks @QuYunpeng

**Comment by dimbslmh** [comment]
@djhvscf I'll take a look.

**Comment by dimbslmh** [comment]
@djhvscf resetView calls getCaretHtml() which resets all assigned arrows (done by multiple sort).
The Multiple Sort uses it's own method to assign arrows which isn't called on resetView.
I can listen to onPostHeader, but this is triggered before getCaretHtml().

Can you add a onResetView event  and trigger it at the end of resetView?

I do have a fix for the onColumnSwitch issue. I will PR shortly..

**Comment by djhvscf** [comment]
but.. What event?

**Comment by djhvscf** [comment]
Maybe we can put the getCaret method in the beginning of the resetView method

**Comment by dimbslmh** [comment]
@djhvscf  a new event called onResetView or move the getCaret method before onPostHeader is triggered.

**Comment by dimbslmh** [comment]
onColumnSwitch works correctly here with https://github.com/wenzhixin/bootstrap-table/issues/940: https://jsfiddle.net/dimbslmh/s2h1gzj9/
