### ISSUE TITLE
The extention  bootstrap-table-reorder-rows.js is not working  

### ISSUE THREAD

**Issue by shooter27** [wenzhixin/bootstrap-table#944]
1. When we use data attributes data-toggle="table"
2. Via JavaScript

And work only when we use  url: 'data1.json'

**Comment by djhvscf** [comment]
Can you provide a fiddle??

**Comment by djhvscf** [comment]
Any update here??

**Comment by djhvscf** [comment]
When you create the fiddle then reopen the issue. @shooter27
