### ISSUE TITLE
Work with React natively

### ISSUE THREAD

**Issue by cbalmeida** [wenzhixin/bootstrap-table#946]
Any chance to work with react natively?

**Comment by djhvscf** [comment]
Well I don't know React enough to reply you but you can explain more what you want to do

**Comment by wenzhixin** [comment]
Try this: https://jsfiddle.net/wenyi/uzgkzjcp/7/

**Comment by djhvscf** [comment]
If this solution is not the correct one then reopen the issue. @cbalmeida
