### ISSUE TITLE
How to get hidden columns?

### ISSUE THREAD

**Issue by xvisor16** [wenzhixin/bootstrap-table#947]
Hi,

I'd like to know how i could get the hidden columns (by deselecting a colums in the columnpicker) so i can use the info to show the values of the columns that were hidden in the detailView. To put it simple, I want to use the detailFormatter to show the info of the hidden columns and it would be nice to only show the detailView button on the rows if there are 1 or more hidden columns.

Thanks a lot for you help!

Peter

**Comment by djhvscf** [comment]
You can get the column-switch.bs.table event to save the columns hidden and then use the getData method in order to filter your data with your columns names hidden

**Comment by xvisor16** [comment]
Do you have a little example for me on the saving en getting with getData? That would be really nice :)

**Comment by djhvscf** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#methods/getData.html

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/e3nk137y/1980/
