### ISSUE TITLE
Using Backbone

### ISSUE THREAD

**Issue by NitroGhost** [wenzhixin/bootstrap-table#948]
is it possible to generate the table using backbone? I can query the data using backbone and manually add the data, but this means the refresh button won't work because it's not getting the data from a URL directly

**Comment by djhvscf** [comment]
Exaclty, but instead of using the refresh button, you can use the load method to do that

**Comment by wenzhixin** [comment]
Yes @NitroGhost , in your case you need to use `load` method to refresh your data manually.
