### ISSUE TITLE
Personalizar filtros "bootstrap-table-filter" Como lo Hago?

### ISSUE THREAD

**Issue by josedeyvi** [wenzhixin/bootstrap-table#949]
hello, as I personalize the filters; only show me 2 columns to filter a total of five

**Comment by djhvscf** [comment]
Can you provide a fiddle or more explanation about your issue??

**Comment by djhvscf** [comment]
Ref to https://github.com/lukaskral/bootstrap-table-filter please go to plugin repo to discuss this problem
