### ISSUE TITLE
Data-field:"(Object).Field" doesn´t work, any idea

### ISSUE THREAD

**Issue by abazanvillanueva** [wenzhixin/bootstrap-table#950]
A get a data.json which contrains an array of Objects X, which Object X contains a Object Y (FK pretends). I want to do this. 
columns: [{
                field: ObjectY.Field,
but it seems not to work, any idea?

**Comment by djhvscf** [comment]
You can use the Flat-Json extension to do that.. See this: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/flat-json.html
