### ISSUE TITLE
Feature Request: Formatter Options

### ISSUE THREAD

**Issue by D144** [wenzhixin/bootstrap-table#951]
For example:
```html
<th data-field="date" data-formatter="dateFormatter" data-formatter-options='{ style:"m/d/y" }'>
```
```javascript
function dateFormatter(value, row, index, options) {
	return moment(value).format(options.style);
}
```

Could use naming convention like this: `data-formatter-options-style="m/d/y"` to avoid issues with inline JSON

**Comment by djhvscf** [comment]
Provide a fiddle please with your current code

**Comment by docholiday** [comment]
Can't see a reason yet, why you wouldn't just use the wanted formatting style directly within the formatter-function.

**Comment by wenzhixin** [comment]
wonfix.

**Comment by D144** [comment]
The additional options would allow for one Formatter function to be reused in multiple places throughout an entire site. So, in the example I gave above, I may have

```html
<th data-field="date" data-formatter="dateFormatter" data-formatter-options='{ style:"M/D/YY" }'>`

while somewhere else I may have

```html
<th data-field="date" data-formatter="dateFormatter" data-formatter-options='{ style:"MMM D, YYYY h:mm a" }'>`

**Comment by wenzhixin** [comment]
Got it, but implementing such a feature is not very general.
