### ISSUE TITLE
Event on Loading, Please Wait

### ISSUE THREAD

**Issue by Sivalingaamorthy** [wenzhixin/bootstrap-table#952]
Hi,

I have a requirement, when Bootstrap table displays 'Loading. Please wait ...' i want to display progress indicator image ... Can help me to know what is the event I can use.

I found when when to stop the progress indicator, i.e on load-success or error.

 $(id).bootstrapTable({}).
             on('pre-body.bs.table', function (e, data) {
                 sybaan.utls.displayAjax(); // this is wrong, I need to display progress indicator when 'Loading. Please wait ...'
             }).on('load-success.bs.table', function (e, data) {
                 sybaan.utls.hideAjax();
             }).on('load-error.bs.table', function (e, status) {
                 sybaan.utls.hideAjax();
             });

**Comment by djhvscf** [comment]
Provide a fiddle with your current code, please

**Comment by wenzhixin** [comment]
Is it like this: http://jsfiddle.net/wenyi/e3nk137y/1971/?
