### ISSUE TITLE
Small Feature Request related to search input field

### ISSUE THREAD

**Issue by webcliq** [wenzhixin/bootstrap-table#955]
Please can you add a "class" such as "searchbox" to the search input box changing class="form-control" to class="form-control searchbox".

Please can you split the ability to display the Search Box from the ability to respond to a "keyup" by the entry of characters in the search box. I need to display it but switch off the internal "keyup" response.

The overall result of these minor changes (which I have already tested), is that one can implement Server-side searching without any difficulty.

I may also need to do something similar for searching by column but that can come later.

After the change is released, I can then write up a set of instructions for PHP Server side data generation and searching based on an overall search or a column by column search.

**Comment by wenzhixin** [comment]
We will consider the feature, remember  any pull request is welcome.

**Comment by dabros** [comment]
@webcliq - to help with this, if unable to provide a pull, can you show us in fiddle your "tested" code (which i assume was in callback/s or base code modifications). Obviously cant simulate actual server side search, but easy enough to see even with standard client side in fiddle (and anyone can use it with thier own server url)

This will help illustrate what your trying to achieve and show what code you tested

Thanks

**Comment by wenzhixin** [comment]
Hi @webcliq, first question, you can use `$('.fixed-table-toolbar search input')` instead.
And the feature you said, I think you can custom your search input for example like this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html.
So we don't add the feature in our plugin.
