### ISSUE TITLE
rowspan / colspan breaking tables

### ISSUE THREAD

**Issue by maciejrozanski** [wenzhixin/bootstrap-table#957]
Hi,

please look at: 
http://jsfiddle.net/8mzLb8gk/
or
http://jsfiddle.net/e3nk137y/1951/

rowspan on row is adding unnecessary column with "-"
colspan on header duplicates it

**Comment by wenzhixin** [comment]
Fixed this bug, your jsFiddle is working now.

**Comment by maciejrozanski** [comment]
Colspan on header is now ok, but rowspan still didn't work:
http://jsfiddle.net/e3nk137y/2260/

**Comment by wenzhixin** [comment]
OK, please submit a bug in a new issue.

**Comment by wenzhixin** [comment]
Reopen this.

**Comment by bassrock** [comment]
Seeing the same issue and it is causing the table to misalign. I can create a pull request but need an idea on where to start.

**Comment by wenzhixin** [comment]
@bassrock https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

**Comment by wenzhixin** [comment]
@bashlakov any update?

**Comment by dabros** [comment]
ref: #1891 (only maybe of interest, prob diff core problem)

**Comment by bashlakov** [comment]
@wenzhixin, maybe you mention @bassrock?

**Comment by wenzhixin** [comment]
Fixed this: http://jsfiddle.net/wenyi/e3nk137y/4761/

**Comment by wenzhixin** [comment]
@maciejrozanski http://jsfiddle.net/wenyi/e3nk137y/4762/

**Comment by edouardberthe** [comment]
Thank you :+1: :)
I have done the work for the fixed-columns extension : https://github.com/wenzhixin/bootstrap-table-fixed-columns/pull/12 (which didn't work, but should after your correction)
