### ISSUE TITLE
Multiple-sort with multiple tables is not working

### ISSUE THREAD

**Issue by djhvscf** [wenzhixin/bootstrap-table#959]
(By @rajeshbtlit)  In my scenario, i have 3 tables, and in first table multiple sort works fine no problem.
When i add it to second table, i see that the same sort modal opens (I mean the sort window of the first table)

JS fiddle here@ https://jsfiddle.net/jupitor/h2c683cn/

I have created two tables and added the multiple sort attribute for both and the second table always shows the first tables sorting columns

**Comment by djhvscf** [comment]
Can you check this @dimbslmh??

**Comment by dimbslmh** [comment]
@djhvscf I already have a fix for this to work with multiple tables.. I'm still waiting for my PR to be merged first.. Can you see what's conflicting at PR #940?

**Comment by rajeshbtlit** [comment]
Thanks so much guys, much appreciated, waiting for the fix.

**Comment by djhvscf** [comment]
@dimbslmh the PR is already merged, can you create a PR to fix this issue, please?

**Comment by rajeshbtlit** [comment]
Hi, could you please let us  know when we can pick up the js from 
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/multiple-sort

**Comment by rajeshbtlit** [comment]
Hi Guys, could you please let us know, when we can pick up the changes ?

**Comment by djhvscf** [comment]
Can you help us with this issue, @dimbslmh??

**Comment by djhvscf** [comment]
We are waiting for you, @dimbslmh

**Comment by dimbslmh** [comment]
Sorry for the wait guys.. I'm currently updating my project with the latest changes. I'll create a PR asap.

**Comment by dimbslmh** [comment]
@djhvscf Can you checkout my repo..? 
https://github.com/wenzhixin/bootstrap-table/compare/master...dimbslmh:master

I think because of my previous failed (rebased) merge at #940 it now contains a lot of commits. But it still has only one file changed which is the one I want to PR. 
If it's fine I'll create the PR.

**Comment by djhvscf** [comment]
I think it is fine, you can create the PR, please

**Comment by rajeshbtlit** [comment]
Hi Guys,
Thanks a lot for your commitment, really appreciate you guys for the work done.
