### ISSUE TITLE
Javascript not work when click, refresh or...

### ISSUE THREAD

**Issue by limbail** [wenzhixin/bootstrap-table#960]
Hi guys,

I try to make a row content invisible and show on hover, this is my code:

jsfiddle:
http://jsfiddle.net/limbail/wgr4c1kr/6/

This work one time, but... if I use search or click something related to bootstrap-table not work anymore my java part. I try use data*att.., unique-id..., and nothing. Anyone can help me please?, Is my first app...

Sorry for my english.

**Comment by djhvscf** [comment]
Provide a fiddle because with that code is not clear.. That will save our time

**Comment by limbail** [comment]
Example on fiddle updated,

reproduce:
Hover pass
Click toggle buttom
Hover again (not work)

**Comment by djhvscf** [comment]
You can try something like this: http://jsfiddle.net/djhvscf/wgr4c1kr/7/
