### ISSUE TITLE
Selected row data when creating table from html

### ISSUE THREAD

**Issue by rshov** [wenzhixin/bootstrap-table#961]
Is there a way to get data from a table created with html? I have radio buttons for the first column and want to use the function `table.bootstrapTable('getSelections');` to find the selected row. But I need an ID that is not displayed to the user in the columns. I was hoping to add it to the rows such as `<tr data-contactId="1234">`, and then access it from the selected row (or something similar). Thanks for any help, it's a great project!

**Comment by djhvscf** [comment]
You can use the data-unique-id table option

**Comment by rshov** [comment]
@djhvscf Thanks Dennis, that sounds like what I would want. But from the documentation I'm not clear on how it is used. Is it added to the `<tr>` element? I tried this but don't see it in the object when I get the selected items. Unfortunately I can't find any example code using this option either.

**Comment by rshov** [comment]
I was able to achieve what I needed by adding a column and just making it hidden using the `data-visible='false'` option, but I'm still interested in the data-unique-id option since this might be a better approach.

**Comment by wenzhixin** [comment]
@rshov, See this example: http://jsfiddle.net/wenyi/e3nk137y/2047/

**Comment by djhvscf** [comment]
If this is not a good solution then reopen the issue
