### ISSUE TITLE
How to add $detail object to card view

### ISSUE THREAD

**Issue by DavidKrupi** [wenzhixin/bootstrap-table#963]
Hello,
first of all, thanks for such a great effort in making this plugin. It is just awesome.

I would like to ask, how to pass $detail object to card view, so it will be displayed together with columns.
Please help, I am not expert on jquery.
I am using Template Toolkit, maybe there is simpler way... I have this in HTML:

```
<span style="display: none;" id="desc[% loop.index %]">
    <strong class="bold">[% t_description %]:</strong><br>
    <pre>[% description %]</pre>
</span>
```

where loop.index is the index of the row.

**Comment by wenzhixin** [comment]
sorry, I do not know what you want.

**Comment by DavidKrupi** [comment]
Hello,
in http://issues.wenzhixin.net.cn/bootstrap-table/ there is + sign, which unwraps some more information. I mean license for all odd rows, let's call it the description in my case, which is shown for every row. This is not a column of the table.
If I toggle the the card view with toggle button, + sign disappears and the description is not there.

So I would like to include it, maybe I could add hidden column with the description, which will be shown only when card view is toggled?

**Comment by wenzhixin** [comment]
The detail view can not be supported in card view at the moment. When you toggle to card view, we will remove  the detail view.

**Comment by DavidKrupi** [comment]
Ok, thank you very much for information. It's not so crucial for my implementation. Still I think this plugin is wonderful and I will continue to use it.
Best regards
David
