### ISSUE TITLE
Export doesn't work on IE10 and IE11

### ISSUE THREAD

**Issue by zardaloop** [wenzhixin/bootstrap-table#965]
When I try to export int IE10 and IE11 it goes to another error page rather than downloading. However the same thing looks fine in Chrome. Any idea?

**Comment by wenzhixin** [comment]
The same with #956?

**Comment by zardaloop** [comment]
Yes it is a similar issue.
Let say you want to export the table into json. 
So if you debug the code in line 223 of this javascript file (http://rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js) it fails when it tries to call saveAs method.

Then the error is caught and it goes to line 226 which the downloadFile method is called which fails. However the method works fine in Chrome, but it fails in IE10 and IE11, I haven't checked it for the other IE's so probably it fails for all. 

Cheers,
Farzan

**Comment by djhvscf** [comment]
Same https://github.com/wenzhixin/bootstrap-table/issues/956

Close this issue
