### ISSUE TITLE
Sort icons not visible as in your examples

### ISSUE THREAD

**Issue by andrea-schneider** [wenzhixin/bootstrap-table#968]
Hi 
I would like to have the sort icons as you have them in your examples, but I cannot find out how to do so.
This is how it looks on my site:
![missing-icons](https://cloud.githubusercontent.com/assets/4055656/8001621/a84782ca-0b67-11e5-9f24-3c36ff5ded94.png)

instead of your example:
![icons-available](https://cloud.githubusercontent.com/assets/4055656/8001768/2c54568c-0b69-11e5-98f2-3d03752a065e.png)

These are my used CSS an JS
```<link href="../bootstrap.min.css" type="text/css" rel="stylesheet" media="all" />```
```<link href="../bootstrap-table.css" type="text/css" rel="stylesheet" media="all" />```
```<link href="../bootstrap-theme.min.css" type="text/css" rel="stylesheet" media="all" />```

```<script language="javascript" type="text/javascript" src="../jquery-1.10.js"></script>```
```<script language="javascript" type="text/javascript" src="../bootstrap.min.js"></script>```
```<script language="javascript" type="text/javascript" src="../bootstrap-table.js"></script>```
```<script language="javascript" type="text/javascript" src="../bootstrap-table-mobile.js"></script>```

What is wrong with this?

Thanks for your help

**Comment by wenzhixin** [comment]
What version of bootstrap-table are you using?

**Comment by andrea-schneider** [comment]
Hi 
I'm on 1.7.0

**Comment by andrea-schneider** [comment]
Hi
I have installed the latest and it is working, sorry to bother you and thanks for your great work!

**Comment by wenzhixin** [comment]
OK, close this issue.
