### ISSUE TITLE
On a number of issues in IE8

### ISSUE THREAD

**Issue by xujianghao** [wenzhixin/bootstrap-table#969]
When I use IE8, the data can be acquired and displayed, but you can not click on each row. Use showHeader:  "false", click on the event can be executed for each row. As mentioned there is a problem, there should be covering the phenomenon caused by two Header, how to solve?

**Comment by djhvscf** [comment]
Provide a fiddle, please

**Comment by wenzhixin** [comment]
In the latest version, I have fixed the header bug of IE, https://github.com/wenzhixin/bootstrap-table/commit/d0abc237bdd2c4777f4beaaf0923c4ad0f31dd4c. Can you provide a jsFiddle or some code to show your problem?

**Comment by xujianghao** [comment]
jsp:
![jsp](https://cloud.githubusercontent.com/assets/12029702/8049739/9b30a48c-0e95-11e5-95fd-3aa3e7c53229.JPG)

js:
![js](https://cloud.githubusercontent.com/assets/12029702/8049745/ab56c756-0e95-11e5-99f7-7b4aa9b2d461.JPG)

when i use the win7 32bit ie 8,i couldn't check the row.

**Comment by xujianghao** [comment]
@wenzhixin  Hey, you put this problem solved?

**Comment by wenzhixin** [comment]
No, I cannot check it out because I don't have the environment. Can you use the debug mode to find out the problem?

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by xujianghao** [comment]
@wenzhixin I am sorry, because the project schedule needs, has been used in other programs, so the question I did not how to study, so the problem has not been resolved!

**Comment by wenzhixin** [comment]
OK, close the issue.
