### ISSUE TITLE
Click on no-rows table

### ISSUE THREAD

**Issue by CaRLiTRoS85** [wenzhixin/bootstrap-table#970]
Hi,
when i click on a table with not records found, in the tr where should be the data if those exists... the js returns an error on the last line of this code: LINE 1429 of the bootstrap-table.js

My table aren't selectables.

        this.$body.find('> tr > td').off('click').on('click', function () {
            var $td = $(this),
                $tr = $td.parent(),
                item = that.data[$tr.data('index')],
                cellIndex = $td[0].cellIndex,
                $headerCell = that.$header.find('th:eq(' + cellIndex + ')'),
                field = $headerCell.data('field'),
                value = item[field];

**Comment by djhvscf** [comment]
Can you provide a fiddle please?

**Comment by CaRLiTRoS85** [comment]
https://jsfiddle.net/fbv1s377/

In fiddle i cannot runs the error, but the code is the same i have on my application. The error occurs when i click on the row of "No matching records found"
