### ISSUE TITLE
Table Filter Control on modal windows with data-height

### ISSUE THREAD

**Issue by Ajitweb** [wenzhixin/bootstrap-table#972]
Hi @wenzhixin 

I could not see the filter row (underneath the header) when I am using the table filter control in a modal of my MVC application. F12 clearly shows that the data is existing. 
I found that if I remove the data-height attribute, then the filter works correctly.
(Of course, I have to turn on the pagination in this case)
So the issue is filter row cannot be seen when a value is set on data-height.
I am using version 1.8.0

When I tried it with 1.8.1, there is an error
Unable to get property 'options' of undefined or null reference 
Line of error -> selectControl.get(0).options

**Comment by djhvscf** [comment]
Well the first part of the issue is a known issue and we are working on it, and the second can you provide a fiddle to see the problem?? @Ajitweb

**Comment by Ajitweb** [comment]
Hi @djhvscf. Thanks for your fast response. I am generating the desired bootstrap html with the help of   @DmitryEfimenko  twitterbootstrapmvc utility. So it will take time to replicate that into jsfiddle. 
But I do get an error with 1.8.1 and that is
Unhandled exception at line 206, column 33 in http://localhost:7239/Scripts/bootstrap-table-filter-control.js
0x800a138f - JavaScript runtime error: Unable to get property 'options' of undefined or null reference

It works fine with 1.8.0 after removing the data-height attribute.

**Comment by djhvscf** [comment]
The solution is this PR: https://github.com/wenzhixin/bootstrap-table/pull/977
