### ISSUE TITLE
duplicate headers

### ISSUE THREAD

**Issue by rsdenijs** [wenzhixin/bootstrap-table#973]
Hi, Im starting with boostrap-table, I am probably doing something wrong. 
Why am I getting duplicate headers here? And less importantly,  why doesnt the data load for this example?

https://jsfiddle.net/mwrnu31f/1/

**Comment by rsdenijs** [comment]
Nevermind,  I was missing the an import.

**Comment by sidd-s** [comment]
Just curious, what was the fix, I come across similar issue while displaying bootstrap-table in bootstrap model form. Let me know.

**Comment by wenzhixin** [comment]
See this example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/modal-table.html

**Comment by rsdenijs** [comment]
@sidd-s  I was missing the css

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.8.1/bootstrap-table.min.css">

**Comment by djhvscf** [comment]
Ok great @rsdenijs ,

**Comment by sidd-s** [comment]
Thanks Will check that.  I am using version 1.7.0

![image](https://cloud.githubusercontent.com/assets/2931970/8117880/a00b8ec0-1059-11e5-8073-6806ce8fef41.png)

**Comment by sidd-s** [comment]
its seems this might be a bug in 1.7.0, Same code works fine with 1.6.0 and 1.8.0, I mean no double headers. Recently my team member upgraded lib to 1.7.0, so then I saw this side affect.

**Comment by djhvscf** [comment]
Yes, if you can, use the lastest version
