### ISSUE TITLE
Access the column in the formatter

### ISSUE THREAD

**Issue by pedrosalpr** [wenzhixin/bootstrap-table#974]
How do I access the column in the formatter? 
I need to access the column that is being formatted. 
Currently, there are three parameters (value, row, index), has no way to add the 4th parameter (column)?

**Comment by wenzhixin** [comment]
You can use `this.field` in `formatter` function.

**Comment by wenzhixin** [comment]
http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options
```
The context (this) is the column Object. 
The cell formatter function, take three parameters: 
value: the field value. 
row: the row record data.
index: the row index.
```
