### ISSUE TITLE
how do i define my pagination text

### ISSUE THREAD

**Issue by qqcome110** [wenzhixin/bootstrap-table#976]
## default style
![image](https://cloud.githubusercontent.com/assets/5085523/8049657/61efc8b6-0e94-11e5-8e62-9d6a21551855.png)

see this issue title!

**Comment by djhvscf** [comment]
See this: http://issues.wenzhixin.net.cn/bootstrap-table/#options/pagination-custom-text.html

**Comment by wenzhixin** [comment]
```js
bootstrapTable({
    formatShowingRows: function (pageFrom, pageTo, totalRows) {
        // ...
    }
});
```

**Comment by qqcome110** [comment]
thanks! is resolved my problem
