### ISSUE TITLE
Hiding currently sorted column breaks table

### ISSUE THREAD

**Issue by wahlstrand** [wenzhixin/bootstrap-table#978]
![2015-06-09_0946](https://cloud.githubusercontent.com/assets/5912595/8052970/9900c90c-0e8c-11e5-8f95-b9958c65cd02.png)

Showing "Ändrat" column.

![2015-06-09_0948](https://cloud.githubusercontent.com/assets/5912595/8052986/baf66940-0e8c-11e5-8236-049e8a2b8c9b.png)

Hiding "Ändrat" column.

Any ideas?

**Comment by wahlstrand** [comment]
Flow:
1.Load data into table - sort by "Ändrad" (in this case).
2.Hide column "Ändrad"

Result: Column Header "Ändrad" is hid, table body stays the same.
Expected result: Entire column "Ändrad" is hid, either change sort to (now) 1st table column or continue sort on now hidden "Ändrad" column.

**Comment by wenzhixin** [comment]
Same problem with #967, you can update to the latest code and try it again.
