### ISSUE TITLE
Column option class not present in card view state

### ISSUE THREAD

**Issue by bart-mertens** [wenzhixin/bootstrap-table#979]
I am using the *class* option on certain columns in order to handle them in CSS. When switching to the card view state, I notice this *class* is not available on the div.class-view.

I think it makes sense to maintain *class* option.

I am using the bootstrap-table-mobile extension to activate the card view state.

**Comment by djhvscf** [comment]
Can you provide a fiddle please?

**Comment by bart-mertens** [comment]
The [Fiddle](https://jsfiddle.net/CM_Bart/7xfj42mt/1/) is available.

When you make the output result smaller then 800px, you will get the cardView. But I expected the class "demo" on the related div.card-view for each row in the table. Appareantly the class option is not taken into account when generating the card view state.

**Comment by djhvscf** [comment]
You can use the row style function or the row attribute function.. See: http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options

**Comment by djhvscf** [comment]
Close this issue. it is the same of https://github.com/wenzhixin/bootstrap-table/issues/879
