### ISSUE TITLE
Detail view, when searching, returns wrong row

### ISSUE THREAD

**Issue by OfficialBAMM** [wenzhixin/bootstrap-table#980]
Using version 1.8.1, windows 7 32 bits, Browsers: All
As I said in the title, if you search and then press the + sign, you'll get the wrong info returned. As english isn't my nature tongue let me present you with a example.

    onExpandRow: function (index, row, $detail) {
        console.log(row);
    }

The above 'row' doesn't return the information that is inside that row.

Here's a fiddle!:
http://jsfiddle.net/e3nk137y/1997/

To reproduce, search for example '02' and click on the + thingy. I've console.log'd it.

OfficialBAMM

For people needing a solution asap:

    var temp = $detail.context;
    var debID = $(temp).parent().parent().children(".debID").html();

I've added a class on the ID i needed to get, maybe it's handy for someone.

**Comment by wenzhixin** [comment]
You mean: `undefined: false`?

**Comment by OfficialBAMM** [comment]
No hard feelings, but there's a fiddle? 

The row it returns is the row that is original in the place like you were not searching.

**Comment by tannermccoleman** [comment]
I've fixed the problem locally and I'll try to get it up tomorrow, but my solution isn't IE8 friendly.

initSearch() needs to store this.data as an object with the original numeric keys at the end of the method. 
```javascript
var nd = {};

$.each(this.data, function(i, item){
    $.each(that.options.data, function(j, jtem){
        if (item === jtem) {
            nd[j] = jtem;
        }
    });
});

this.data = nd;
```
Then, initBody needs to be grabbing the nth key during the first for loop.
```javascript
for (var j = this.pageFrom - 1; j < this.pageTo; j++) {
    var key,
        i = Object.keys(data)[j],
        item = data[i],
        style = {},
        csses = [],
        data_ = '',
        attributes = {},
        htmlAttributes = [];
```
If anyone knows of a good IE8 compatible solution, please let me know.
