### ISSUE TITLE
How does the data size effects the client side pagination?

### ISSUE THREAD

**Issue by zgjsyxwj** [wenzhixin/bootstrap-table#983]
Hi,文翼,I'm also from China.  One problem bothered me for days. This is my respone data, you can just copy the {} object for about 130 times. When the data size goes above like 125, then the client side pagination just doesnt work. The response handler doesnt invoke. while the size goes down, it invokes. 
{"sys_header":{
"status":"ok"
},
"appdata":[{
"createdby":"1020",
"updatedby":"1020",
"srctype":"2",
"urlpath":"index_manpower.html",
"srccode":"100101",
"srcname":"人力资源管理子系统",
"_bean$cls$type":"com.wk.rec.db.info.pow.PowSrcInfo"
}]}

	<table id="usertable" data-toggle="table"
			class="table table-condensed "
			data-url="data.json" data-height="600"
			data-response-handler="handleClientData" data-show-columns="true"
			data-method="post" data-show-refresh="true" data-show-toggle="true"
			data-show-pagination-switch="true" data-page-number="1"
			data-page-size="12" data-striped="true" data-side-pagination="client"
			 data-pagination="true"
			data-page-list="[5, 10, 20, 50, 100, 200]" data-search="true">
			<thead>
				<tr>	<th data-field="srcname" data-sortable="true"><i
						class="fa fa-calendar fa-fw"></i>&nbsp;资源名称</th>
					
				</tr>
			</thead>
		</table>

// 处理客户端分页
		function handleClientData(res) {
			alert("handle");
			return res.appdata;
		}

**Comment by zgjsyxwj** [comment]
BTW, if I dont query the attribute 'url path' from database, the response handler also works fine.

**Comment by wenzhixin** [comment]
What's the problem? http://jsfiddle.net/wenyi/e3nk137y/2001/

**Comment by zgjsyxwj** [comment]
Ok,thx, I find the problem, some tab in database, so the jquery ajax gets the data, but goes to error block. The data I posted above got no such problem, so your expamle shows without error. Thanks for your help, have a nice day!

**Comment by djhvscf** [comment]
Great! Thanks @zgjsyxwj
