### ISSUE TITLE
editable select box

### ISSUE THREAD

**Issue by kodeine** [wenzhixin/bootstrap-table#986]
How can i use editable using select box with options. where by html table has data-url="...".
Do i have to modify the json data file? if so how it should look. I am using this [example](http://issues.wenzhixin.net.cn/bootstrap-table/welcome.html)

```
{
  "total": 5,
  "rows": [
    {
      "id": 0,
      "name": "Item 0",
      "price": "$0"
    }
  ]
}
```

**Comment by wenzhixin** [comment]
Ref this issue: #626, it may be help.

**Comment by kodeine** [comment]
@wenzhixin 
Yes, i saw that but im trying to set that editable via htmk <table ...>
Any idea?

**Comment by wenzhixin** [comment]
At the moment it does not support via data attribute feature, it seems that hard to implement this. 
But I will consider that in the further version, if you have any good solution, remember any pull request is welcome.

**Comment by kodeine** [comment]
@wenzhixin 
thank you for prompt response.

I tried the following, but instead of price it shows `empty`

```
$table.bootstrapTable({
        //idField: 'id',
        height: getHeight(),
        columns: [{
            field: 'state',
            title: '',
            checkbox: true

        }, {
            field: 'id',
            title: 'ids',
            sortable: true
        }, {
            field: 'name',
            title: 'names',
            sortable: true,
            editable: {
                type: 'text'
            }
            editable: {
                type: 'select',
                source: [
                    {value: 1, text: 'Active'},
                    {value: 2, text: 'Blocked'},
                    {value: 3, text: 'Deleted'}
                ],
                //'title': 'Herd Tag',
                'prepend': {none: "--------------"}
            }
        }, {
            field: 'price',
            title: 'prices',
            sortable: true,
            switchable: true
        }, {
            field: 'operate',
            title: 'Action',
            sortable: true,
            editable: false,
            formatter: "operateFormatter",
            events: "operateEvents"

        }]
    });
```

**Comment by kodeine** [comment]
@wenzhixin 
I set my data as 
```
{
      "id": 1,
      "name": 2,
      "price": "$1"
    },
```
and it selects the value id 2 from select options. Is there a way to define the default value from the JS and not the data source?

**Comment by wenzhixin** [comment]
Added example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/986.html

**Comment by kodeine** [comment]
@wenzhixin 
Thanks a lot bud.

**Comment by djhvscf** [comment]
Close this isse

**Comment by nicro87** [comment]
Hi,

when I try your example i get this error in my console:
"ReferenceError: assignment to undeclared variable success
success = deferred.then(function () {"

When I'm trying on my own I get the same error. Can you please post an working example?

It would be nice if you can post an example with select2 too.
I'm trying since many hours to get one of them working.

Thanks in advance
Nico

**Comment by jls010387** [comment]
I'm use this to edit cell data you only need change the input type and populate the option
```
function xedit(value, row, index) {
      var objStr = JSON.stringify(row)
      var obj = JSON.parse(objStr)
    return [
      '<a href="#" id="sugerido" data-type="text" data-placement="right" data-field="sugerido" data-title="sugerido">',
      '<input type=text id="tFileSug" value="'+ obj.sugerido +'" size="4"></input>',    
      '</a>',
     ].join('')
  }
```

```
{
          title: 'names',
          field: 'name',
          sortable: true,
          align: 'center',
          footerFormatter: xedit
        }
```

**Comment by tenshs** [comment]
<img width="686" alt="Capture" src="https://user-images.githubusercontent.com/2256582/98397150-762dec80-2091-11eb-80a6-f7010e74f208.PNG">

Hi, how to know the error when first click on the field to be edited?

**Comment by wenzhixin** [comment]
https://blog.bootstrap-table.com/2019/10/06/use-editable-in-bootstrap-v4/

**Comment by mrsof** [comment]
> https://blog.bootstrap-table.com/2019/10/06/use-editable-in-bootstrap-v4/

Unfortunately your demo page does not work

**Comment by dharmraj-chauhan** [comment]
Any update on this ?
I tried below example, but its not working.
Bootstrap5: [https://live.bootstrap-table.com/example/extensions/editable.html](url) 

Thanks
