### ISSUE TITLE
Input fields in table clearing on sort, pagination or search

### ISSUE THREAD

**Issue by austinstudio** [wenzhixin/bootstrap-table#987]
Is there a way to have a column of input tags that keep their values, like checkboxes and radios, when the data is sorted, paginated or searched?  I have a need to update quantities, like in a shopping cart, but give the user the ability to sort, page and filter out values.  By default, when the user fills in the values and tries any of those actions, the data in the fields all reset to their original values.

Thank you in advance for any guidance on this.

**Comment by wenzhixin** [comment]
I think you can use editable extension: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html

**Comment by austinstudio** [comment]
I looked at that but it isn't that accessible.  Unfortunately, I need a plain table with input tags in it that have editable values all of the time.  Currently we are just not allowing paging and are just training people that they will lose values when they sort or filter but we would like to keep the values like you do for the check boxes and radios.

**Comment by dabros** [comment]
@austinstudio - if you can provide a fiddle showing examples of input fields you want, maybe someone who has used that extension could help you, and/or suggest using certain callbacks to help achieve it

**Comment by wenzhixin** [comment]
Added an example: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/987.html

**Comment by Kristianwiley** [comment]
Is there any way the inputs retain values if they're not checkboxes? On your main page for example if you check rows 0 and 1, and then change the Item Name values to something new. The new values will be removed/reset if you sort any column but the checkboxes remain checked.

http://issues.wenzhixin.net.cn/bootstrap-table/index.html

**Comment by princenaman** [comment]
Modified example for input text
http://jsfiddle.net/c8zv4uhm/

**Comment by sdespont** [comment]
I think it is better to update the html element and use the full html code of the cell instead of recreate the input element with a formatter like others examples above. 
This way, it permits to retain "outer HTML" code, input attributes like "id", classes, ... 

Checkbox example : http://jsfiddle.net/sdespont/16gywqts/94/

    window.inputEvents = {
      'change :checkbox': function(e, value, row, index) {
        var $this = $(this);

        // Apply row class
        if ($this.is(":checked")) {
          $this.closest('tr').addClass('success');
        } else {
          $this.closest('tr').removeClass('success');
        }

        // Update target HTML code
        $this.attr('checked', $this.is(":checked"));
        row.choice = $this.closest('td')[0].innerHTML;
        $table.bootstrapTable('updateRow', {
          index: index,
          row: row
        });
      }
    };

Select example : http://jsfiddle.net/sdespont/04813xck/60/

    window.inputEvents = {
      'change select': function(e, value, row, index) {
        var $this = $(this);

        // Apply row class
        if ($this.val() !== "") {
          $this.closest('tr').addClass('success');
        } else {
          $this.closest('tr').removeClass('success');
        }

        // Remove previously selected options
        $this.find('option').attr("selected", false);
        // Add selected option
        $this.find('option[value="' + this.value + '"]').attr("selected", true);

        // Update target HTML code
        row.choice = $this.closest('td')[0].innerHTML;
        $table.bootstrapTable('updateRow', {
          index: index,
          row: row
        });
      }
    };

**Comment by cipley** [comment]
Hello,
I have the same problem, but in my case, the data my table was reset every time I insert or remove a row(s).
My solution was using the `onchange` function to update the data in the table every time the field's value was updated. This works for me.
This includes checkbox, text field, and number, so I'm pretty sure it works for other input fields as well.
The idea in principle is more or less the same as @sdespont 's, I just use a more localized events. This will also works on sorting and pagination as the updated data is saved to the Bootstrap Table's data, so even if the table 'reloads', it will reload the data that has been updated.

(somehow my code isn't running in jsFiddle, so pardon me if I'm pasting here instead.)

Table:
```
<button name="Add Row" class="btn btn-default" onclick="addRow()">
  Add Row
</button>
<table id="testTable" data-toggle="table" data-sortable="true">
  <thead>
    <tr>
      <th data-field="selected"
        data-formatter="checkboxFormatter">
        Selected
      </th>
      <th data-field="name"
        data-formatter="nameFormatter">
        Name
      </th>
      <th data-field="qty"
        data-formatter="qtyFormatter">
        Qty
      </th>
    </tr>
  </thead>
</table>
```
JS:
```
function checkboxFormatter(value, row, index){
	if(value)
		return '<input type="checkbox" class="chk" checked		onchange="checkboxChange(this, '+index+')">';
  else
  	return '<input type="checkbox" class="chk"		onchange="checkboxChange(this, '+index+')">';
}

function nameFormatter(value, row, index){
	return '<input type="text" value="'+value+'" 	onchange="nameChange(this, '+index+')">';
}

function qtyFormatter(value, row, index){
	return '<input type="number" value="'+value+'" 	onchange="qtyChange(this, '+index+')">';
}

function checkboxChange(checkbox, index){
	$('#testTable').bootstrapTable('updateCell', {
  	index: index,
    field: 'selected',
    value: checkbox.checked,
    reinit: false
  });
}

function nameChange(textinput, index){
	$('#testTable').bootstrapTable('updateCell', {
  	index: index,
    field: 'name',
    value: textinput.value,
    reinit: false
  });
}

function qtyChange(numberinput, index){
	$('#testTable').bootstrapTable('updateCell', {
  	index: index,
    field: 'qty',
    value: numberinput.value,
    reinit: false
  });
}

var data = [{
	"selected" : true,
  "name" : "Test 1",
  "qty" : 12
},
{
	"selected" : false,
  "name" : "Test 2",
  "qty" : 9
}];

$('#testTable').bootstrapTable('load', data);

function addRow(){
	var newVal = [{
  	"selected" : false,
    "name" : "",
    "qty" : 0
  }];
  $('#testTable').bootstrapTable('append', newVal);
}
```

Hope this helps!

**Comment by matpowel** [comment]
Just a note for future travelers that I found this way of solving it fairly onerous, in our case because we have some nested form fields with complicated html names/ids etc. It was much easier for us to handle the "change" event on each input, store the new value in a global hash and then handle the 'reset-view.bs.table' event on the bootstrap-table to repopulate the most recently set value for each row.
