### ISSUE TITLE
hide all rows when table is filled and show only you have an option selected in the filter control ..

### ISSUE THREAD

**Issue by dlhenke** [wenzhixin/bootstrap-table#991]
i have this in my webpage..
$('#tblInstrutores').bootstrapTable({
				columns: [{
					field: 'nome',
					title: 'Nome Instrutor',
					filterControl:"input"
				},{
					field: 'Thomol',
					title: 'Homologacao' //$myresult['Tahomol']="";
				},{
					field: 'email',
					title: 'Email' //$myresult['Tahomol']="";
				},{
					field: 'estado',
					title: 'Estado',
					filterControl:'select'
				}, {
					field: 'encerramento',
					title: 'Enpi válido até:'
				}, {
					field: 'homologacao',
					title: 'Homologação'
				}, {
					field: 'data_termino',
					title: 'Termino'
				}],
				data: data.instr,
				filterControl: true,
				});

what i need is : show rows only when the select box changes to a value != empty.
can you help me with this ?
thank you..

**Comment by djhvscf** [comment]
Well I don't know if this is a common feature, what do you think @wenzhixin ??

**Comment by wenzhixin** [comment]
Yes, I think so.
