### ISSUE TITLE
hand mousepointer on table rows

### ISSUE THREAD

**Issue by chokeholder** [wenzhixin/bootstrap-table#995]
How can i change the css to get a hand cursor when hovering table rows ?

I've tried this:

.table-hover tbody tr:hover > td {
  cursor: pointer;
}

but no success

**Comment by djhvscf** [comment]
See this: http://jsfiddle.net/djhvscf/e3nk137y/2079/ it is working as expected

**Comment by chokeholder** [comment]
OK .. Strange  .. i have inserted it into the bootstrap-table.css but it has no effect. ?

**Comment by chokeholder** [comment]
Nevermind .. I feel so stupid .. i put <! ---- when inserting comment for the style ... that is html comment syntax NOT css :) ... Thanks a lot for the help anyways :+1:

**Comment by BasitMaqsood** [comment]
Working for me
