### ISSUE TITLE
Add details thanks to "detailView" directly in the html ?

### ISSUE THREAD

**Issue by zagloo** [wenzhixin/bootstrap-table#997]
Hi,

Is it possible to add details without script when "detailView" is using ? 

I need to do the same thing as this : 
http://issues.wenzhixin.net.cn/bootstrap-table/#options/sub-table.html

But when I click on the "+" I need to show another table with some values without using function in JS.

Thanks

**Comment by wenzhixin** [comment]
We do not support this feature at the moment.

**Comment by zagloo** [comment]
oh... ok ... so bad. May be soon ?

**Comment by wenzhixin** [comment]
I think implement this feature use data attribute is a little difficult, If you have some advice you can send us a pull request.

**Comment by dabros** [comment]
@zagloo 

What do you mean when you say "when I click on the "+" I need to show another table with some values without using function in JS." ?

What is the purpose of this second table, does it already have data, is it bootstrap table

Also, i cant see working example of detailsView, do you have one. Ideally actually post fiddle showing what other code your using, mimicing data-url and loading as local data if needed (store json or whatever output from data-url into variable and use that)

Thanks

**Comment by wenzhixin** [comment]
Do not support this feature.
