### ISSUE TITLE
Cant use custom toolbar.

### ISSUE THREAD

**Issue by MrTuan-FptAptech** [wenzhixin/bootstrap-table#998]
Here is my code:
<pre><div id="libToolbar">
                    <div class="form-inline" role="form">
                        <div class="form-group">
                            <span>Tìm kiếm </span>
                        </div>
                        <div class="form-group">
                            <span>Trình độ: </span>
                            <select class="form-control" name="level">
                                <option value="N1">N1</option>
                                <option value="N2">N2</option>
                                <option value="N3">N3</option>
                                <option value="N4">N4</option>
                                <option value="N5">N5</option>
                            </select>
                        </div>
                      <div class="form-group">
                            <span>Loại giáo trình: </span>
                            <select class="form-control" name="type">
                                <option value="Tu vung">Từ vựng</option>
                                <option value="Tu loai">Từ loại</option>
                            </select>
                        </div>
                        <button id="ok" type="submit" class="btn btn-default">OK</button>
                    </div>
                </div>
                
                <table id="libTable"
                       data-toolbar="#libToolbar"
                       data-toggle="table"
                       data-url="library.json"
                       data-sort-name="no"
                       data-sort-order="asc"
                       data-show-columns="true"
                       data-pagination="true"
                       data-query-params="queryParams"
                       data-search="true">
                    <thead>
                    <tr>
                        <th data-field="no" data-align="center" data-sortable="true">No</th>
                        <th data-field="name" data-sortable="true">Library Name</th>
                        <th data-field="level" data-align="center" data-sortable="true">Level</th>
                        <th data-field="type" data-align="center" data-sortable="true">Type</th>
                        <th data-field="numberOfLesson" data-align="center" data-sortable="true">Lesson</th>
                        <th data-field="estimateHour" data-align="center" data-sortable="true">Estimate Hour</th>
                        <th data-field="numberOfRecommend" data-align="center" data-sortable="true">Recommend</th>
                        <th data-field="numberOfUser" data-align="center" data-sortable="true">Used</th>
                    </tr>
                    </thead>
                </table>
                <script>
                    var $table = $('#libTable'),
                            $ok = $('#ok');
                    $(function () {
                        $ok.click(function () {
                            $table.bootstrapTable('refresh');
                        });
                    });
                    function queryParams(params) {
                        $('#libToolbar').find('select[name]').each(function () {
                            params[$(this).attr('name')] = $(this).val();
                        });
                        return params;
                    }
                </script>
</pre>
Please help me to using custom toolbar. I imported Jquery, Bootstrap and bootstrap table.

**Comment by wenzhixin** [comment]
See this example: http://issues.wenzhixin.net.cn/bootstrap-table/#options/custom-toolbar.html
