### ISSUE TITLE
Please update package.json to 1.8.1 and upload the latest version to npm

### ISSUE THREAD

**Issue by vcarel** [wenzhixin/bootstrap-table#999]
The package.json refers to an outdated version (1.7.0) and the latest available version on npm is 1.6.0.
Could you please do the update ?

Thanks :-)

**Comment by deefour** [comment]
`package.json` looks fine now, but this still 1.8.1 still needs to be published to NPM.

**Comment by wenzhixin** [comment]
Updated to 1.8.1: https://www.npmjs.com/package/bootstrap-table
